### ISSUE TITLE
Audit selectKernel dialog to make sure it always has translator

### ISSUE THREAD

**Issue by JessicaBarh** [jupyterlab/jupyterlab#10003]
## Description
"Select Kernel" dialog does not display in selected UI language. 
the options.translator seems to be null in: https://github.com/jupyterlab/jupyterlab/blob/dd73fa37ef5a4daed6a900ee729cab53f84c7141/packages/apputils/src/sessioncontext.tsx#L320

![image](https://user-images.githubusercontent.com/71149531/112410000-da73e480-8cf0-11eb-814f-40c18160d658.png)

![image](https://user-images.githubusercontent.com/71149531/112409831-91bc2b80-8cf0-11eb-8078-00cdb1d5441f.png)

## Reproduce

1. Go to File -> New -> Notebook
2. "Select Kernel" dialog comes up

## Expected behavior

![image](https://user-images.githubusercontent.com/71149531/112410991-8669ff80-8cf2-11eb-80e6-a17dec539f10.png)

This is the dialog displayed working correctly if opened by clicking on the kernel name at the top right corner of a notebook:
![image](https://user-images.githubusercontent.com/71149531/112411253-fb3d3980-8cf2-11eb-843f-7cbd9b6327b9.png)

## Context

- JupyterLab version: 3.0.11

**Comment by jasongrout** [comment]
It does look like there are a few places that selectKernel is being called without a translator: https://github.com/jupyterlab/jupyterlab/search?q=selectKernel%28

**Comment by jasongrout** [comment]
My guess is the place you are seeing is from https://github.com/jupyterlab/jupyterlab/blob/36db8f75655d487d06cabe6b0fd5ecb0ca5c7d54/packages/docregistry/src/context.ts#L496

You could verify it by setting a breakpoint and looking at the stack trace, to see who is calling selectKernel without a translator argument.

**Comment by SRILEKHA-V19** [comment]
I can take a look at this issue and give it a try :)

**Comment by fcollonval** [comment]
Fix was included in https://github.com/jupyterlab/jupyterlab/pull/12858
