### ISSUE TITLE
[HOTFIX] Release 2.3.1

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#10007]
We need to hotfix the issue of 2.3.0 not working on safari, see https://github.com/jupyterlab/jupyterlab/issues/9983

This should be fixed by https://github.com/jupyterlab/jupyterlab/pull/10001.

Is it ok that I release a 2.3.1 with that fix only?

cc/ @jasongrout @blink1073 @goanpeca

**Comment by jasongrout** [comment]
+1 to releasing a patch release. Can you do that?

**Comment by echarles** [comment]
yes, I can do that my tomorrow.

**Comment by echarles** [comment]
2.3.1 is now released with the fix for https://github.com/jupyterlab/jupyterlab/issues/9983

**Comment by lewisl** [comment]
As of April 21, 2021 it still does not work. Safari launches, a tab is created and the tab remains empty.

macOS 11.2.3

jupyter server version 1.4.1

Python version 3.9.1 (Anaconda)

It does work on Firefox on MacOS.
