### ISSUE TITLE
Is the Extension Tutorial outdated?

### ISSUE THREAD

**Issue by 0618** [jupyterlab/jupyterlab#10017]
## Description

"The command palette is now a floating window that appears on top of your JupyterLab workspace. " since [v3.0.0](https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html#command-palette) but the Extension Tutorial still tells the user to find the Command Palette from the sidebar ([ref](https://jupyterlab.readthedocs.io/en/latest/extension/extension_tutorial.html#add-an-astronomy-picture-of-the-day-widget))

![image](https://user-images.githubusercontent.com/11983489/112770367-587b0880-8fdb-11eb-955e-92ebc2e25caf.png)

I can update it. Is there any other page need to update too?

**Comment by jtpio** [comment]
Fixed by #10026.
