### ISSUE TITLE
JupyterLab 3 git dependency

### ISSUE THREAD

**Issue by danolson1** [jupyterlab/jupyterlab#10028]
## Description

I am running a course and having students install JupyterLab 3.0.11 on their computers. Many of them are running into a problem where the "jupyter lab build" command does not work if git is not installed

## Reproduce

1. Install miniconda
2. Create an environment from the attached me21.yml file
3. Install the escher plugin "jupyter labextension install escher." I'm not sure if this affected things, but it was part of the instructions I gave to the students.
4. Run "jupyter lab build". This fails and gives an error log (2 examples attached).

I spent some time troubleshooting this with a student. Installing git, and adding it to the PATH fixed the problem.

## Expected behavior
If git is necessary for JupyterLab, I would have expected it to be installed automatically by conda during the installation process.

## Context

- Operating System and version: Only students with Windows machines seem to have this problem
- Browser and version: Various
- JupyterLab version: 3.0.11

[me21.zip](https://github.com/jupyterlab/jupyterlab/files/6236629/me21.zip), contains me21.yml environment setup file, and 2 error log files

**Comment by bollwyvl** [comment]
Thanks for the logs.

The `git` dependency comes from [`escher` itself](https://github.com/zakandrewking/escher/blob/master/package.json#L61). 

Quick fixes:
- If you are already encouraging folks to use conda, encourage starting from [miniforge](https://github.com/conda-forge/miniforge) which has the default channel of `conda-forge`. That channel offers `git` (though on windows, `m2-git` is preferable, but plain-old `git` is serviceable, but weird) so you can add `git` to your `environment.yml`.

Longer term:
- encourage the `escher` extension with a polite issue to distribute a/add to their `pypi` package, which won't require `git` (or `nodejs` for that matter, which we _also_ don't declare as a dependency for `jupyterlab`, as it's the _extensions_ that require `nodejs`.
- fork it and do it yourself, or offer extra credit to a student, and publish it

**Comment by danolson1** [comment]
Ok. Yeah, my workaround is to have students install git via `conda install git`. For next year, I'll add `conda install git` to the `environment.yml` file.

I started an [issue on the escher github site](https://github.com/zakandrewking/escher/issues/347), as you suggested.
