### ISSUE TITLE
JLab 3 Extension working on Mac, but not on Windows

### ISSUE THREAD

**Issue by naterush** [jupyterlab/jupyterlab#10022]
## Description

I'm an extension author, namely of the `mitosheet3` package (`mitosheet` works on JLab 2, but we're in the process of migrating to 3). 

The `mitosheet3` package works properly on Mac, but appears to not work at all on Windows. 

As far as I can tell, the bug is in the JLab Widget registry code; at least, it appears that the widget registry is looking up the `mitosheet3` package up under the wrong version (3.0.12, which is jupyter lab's version itself, rather than 0.3.5, which is mitosheet3's version). In turn, this leads to the widget not rendering.

### On Mac:

Run the commands (note that installing Mito will install the other packages you need, including JLab3).
```
python3 -m venv venv
source venv/bin/activate
pip install mitosheet3 
jupyter lab
```
Then, run the follow code in a JLab notebook:
```
import mitosheet3 as mitosheet
mitosheet.sheet()
```
And a widget will appear!

### Context for Mac

- macOS Catilina Version 10.15.7
- Using Firefox 87.0 (64-bit)
- JLab 3.0.12

<details><summary>Troubleshoot Output</summary>
<pre>
CondaEnvException: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.

$PATH:
	/Users/nate/tmp3/venv/bin
	/Users/nate/opt/anaconda3/condabin
	/Users/nate/Downloads/google-cloud-sdk/bin
	/Library/Frameworks/Python.framework/Versions/3.8/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/Library/TeX/texbin
	/Library/Apple/usr/bin
	/Users/nate/.cargo/bin
	/Users/nate/.rvm/bin

sys.path:
	/Users/nate/tmp3/venv/bin
	/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip
	/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8
	/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload
	/Users/nate/tmp3/venv/lib/python3.8/site-packages

sys.executable:
	/Users/nate/tmp3/venv/bin/python3

sys.version:
	3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27)
	[Clang 6.0 (clang-600.0.57)]

platform.platform():
	macOS-10.15.7-x86_64-i386-64bit

which -a jupyter:
	/Users/nate/tmp3/venv/bin/jupyter

pip list:
	Package             Version
	------------------- ---------
	analytics-python    1.2.9
	anyio               2.2.0
	appnope             0.1.2
	argon2-cffi         20.1.0
	async-generator     1.10
	attrs               20.3.0
	Babel               2.9.0
	backcall            0.2.0
	bleach              3.3.0
	certifi             2020.12.5
	cffi                1.14.5
	chardet             4.0.0
	cycler              0.10.0
	decorator           4.4.2
	defusedxml          0.7.1
	entrypoints         0.3
	idna                2.10
	ipykernel           5.5.2
	ipython             7.22.0
	ipython-genutils    0.2.0
	ipywidgets          7.6.3
	jedi                0.18.0
	Jinja2              2.11.3
	json5               0.9.5
	jsonschema          3.2.0
	jupyter-client      6.1.12
	jupyter-core        4.7.1
	jupyter-packaging   0.7.12
	jupyter-server      1.5.1
	jupyterlab          3.0.12
	jupyterlab-pygments 0.1.2
	jupyterlab-server   2.3.0
	jupyterlab-widgets  1.0.0
	kiwisolver          1.3.1
	MarkupSafe          1.1.1
	matplotlib          3.4.0
	mistune             0.8.4
	mitosheet3          0.3.5
	nbclassic           0.2.6
	nbclient            0.5.3
	nbconvert           6.0.7
	nbformat            5.1.2
	nest-asyncio        1.5.1
	notebook            6.3.0
	numpy               1.20.2
	packaging           20.9
	pandas              1.2.3
	pandocfilters       1.4.3
	parso               0.8.1
	pexpect             4.8.0
	pickleshare         0.7.5
	Pillow              8.1.2
	pip                 20.1.1
	prometheus-client   0.9.0
	prompt-toolkit      3.0.18
	ptyprocess          0.7.0
	pycparser           2.20
	Pygments            2.8.1
	pyparsing           2.4.7
	pyrsistent          0.17.3
	python-dateutil     2.8.1
	pytz                2021.1
	pyzmq               22.0.3
	requests            2.25.1
	Send2Trash          1.5.0
	setuptools          47.1.0
	six                 1.15.0
	sniffio             1.2.0
	terminado           0.9.4
	testpath            0.4.4
	tornado             6.1
	traitlets           5.0.5
	urllib3             1.26.4
	wcwidth             0.2.5
	webencodings        0.5.1
	widgetsnbextension  3.5.1

conda list:
	# packages in environment at /Users/nate/opt/anaconda3:
	#
	# Name                    Version                   Build  Channel
	_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
	anaconda                  2020.11                  py38_0
	backports                 1.0                        py_2
	backports.functools_lru_cache 1.6.1                      py_0
	backports.tempfile        1.0                        py_1
	blas                      1.0                         mkl
	blosc                     1.20.1               hab81aa3_0
	boto                      2.49.0                   py38_0
	bottleneck                1.3.2            py38hf1fa96c_1
	brotlipy                  0.7.0           py38haf1e3a3_1000
	bzip2                     1.0.8                h1de35cc_0
	ca-certificates           2020.10.14                    0
	certifi                   2020.6.20          pyhd3eb1b0_3
	cffi                      1.14.3           py38hed5b41f_0
	chardet                   3.0.4                 py38_1003
	click                     7.1.2                      py_0
	cloudpickle               1.6.0                      py_0
	clyent                    1.2.2                    py38_1
	colorama                  0.4.4                      py_0
	conda                     4.9.2            py38hecd8cb5_0
	conda-build               3.20.5                   py38_1
	conda-env                 2.6.0                         1
	conda-package-handling    1.7.2            py38h22f3db7_0
	conda-verify              3.4.2                      py_1
	contextlib2               0.6.0.post1                py_0
	cryptography              3.1.1            py38hddc9c9b_0
	curl                      7.71.1               hb0a8c7a_1
	cycler                    0.10.0                   py38_0
	cython                    0.29.21          py38hb1e8313_0
	cytoolz                   0.11.0           py38haf1e3a3_0
	dask                      2.30.0                     py_0
	dask-core                 2.30.0                     py_0
	dbus                      1.13.18              h18a8e69_0
	decorator                 4.4.2                      py_0
	defusedxml                0.6.0                      py_0
	diff-match-patch          20200713                   py_0
	distributed               2.30.1           py38hecd8cb5_0
	docutils                  0.16                     py38_1
	entrypoints               0.3                      py38_0
	et_xmlfile                1.0.1                   py_1001
	expat                     2.2.10               hb1e8313_2
	fastcache                 1.1.0            py38h1de35cc_0
	filelock                  3.0.12                     py_0
	flake8                    3.8.4                      py_0
	flask                     1.1.2                      py_0
	freetype                  2.10.4               ha233b18_0
	fsspec                    0.8.3                      py_0
	future                    0.18.2                   py38_1
	get_terminal_size         1.0.0                h7520d66_0
	gettext                   0.19.8.1             hb0f4f8b_2
	gevent                    20.9.0           py38haf1e3a3_0
	glib                      2.66.1               h9bbe63b_0
	glob2                     0.7                        py_0
	gmp                       6.1.2                hb37e062_1
	gmpy2                     2.0.8            py38h6ef4df4_3
	greenlet                  0.4.17           py38haf1e3a3_0
	h5py                      2.10.0           py38h3134771_0
	hdf5                      1.10.4               hfa1e0ec_0
	heapdict                  1.0.1                      py_0
	html5lib                  1.1                        py_0
	icu                       58.2                 h0a44026_3
	idna                      2.10                       py_0
	imageio                   2.9.0                      py_0
	imagesize                 1.2.0                      py_0
	importlib-metadata        2.0.0                      py_1
	importlib_metadata        2.0.0                         1
	iniconfig                 1.1.1                      py_0
	intel-openmp              2019.4                      233
	intervaltree              3.1.0                      py_0
	ipykernel                 5.3.4            py38h5ca1d4c_0
	ipython                   7.19.0           py38h01d92e1_0
	ipython_genutils          0.2.0                    py38_0
	ipywidgets                7.5.1                      py_1
	isort                     5.6.4                      py_0
	itsdangerous              1.1.0                      py_0
	jbig                      2.1                  h4d881f8_0
	jdcal                     1.4.1                      py_0
	jedi                      0.17.1                   py38_0
	jinja2                    2.11.2                     py_0
	joblib                    0.17.0                     py_0
	jpeg                      9b                   he5867d9_2
	json5                     0.9.5                      py_0
	jsonschema                3.2.0                      py_2
	jupyter                   1.0.0                    py38_7
	jupyter-packaging         0.7.12                   pypi_0    pypi
	jupyter-server            1.4.1                    pypi_0    pypi
	jupyter_client            6.1.7                      py_0
	jupyter_console           6.2.0                      py_0
	jupyter_core              4.6.3                    py38_0
	jupyterlab                3.0.12                   pypi_0    pypi
	jupyterlab-server         2.3.0                    pypi_0    pypi
	jupyterlab_pygments       0.1.2                      py_0
	keyring                   21.4.0                   py38_1
	kiwisolver                1.3.0            py38h23ab428_0
	krb5                      1.18.2               h75d18d8_0
	lazy-object-proxy         1.4.3            py38h1de35cc_0
	lcms2                     2.11                 h92f6f08_0
	libarchive                3.4.2                haa3ed63_0
	libcurl                   7.71.1               h8a08a2b_1
	libcxx                    10.0.0                        1
	libedit                   3.1.20191231         h1de35cc_1
	libffi                    3.3                  hb1e8313_2
	libgfortran               3.0.1                h93005f0_2
	libiconv                  1.16                 h1de35cc_0
	liblief                   0.10.1               h0a44026_0
	libllvm10                 10.0.1               h76017ad_5
	libpng                    1.6.37               ha441bb4_0
	libsodium                 1.0.18               h1de35cc_0
	libspatialindex           1.9.3                h0a44026_0
	libssh2                   1.9.0                ha12b0ac_1
	libtiff                   4.1.0                hcb84e12_1
	libxml2                   2.9.10               h7cdb67c_3
	libxslt                   1.1.34               h83b36ba_0
	llvm-openmp               10.0.0               h28b9765_0
	llvmlite                  0.34.0           py38h739e7dc_4
	locket                    0.2.0                    py38_1
	lxml                      4.6.1            py38h63b7cb6_0
	lz4-c                     1.9.2                h79c402e_3
	lzo                       2.10                 haf1e3a3_2
	markupsafe                1.1.1            py38h1de35cc_1
	matplotlib                3.3.2                         0
	matplotlib-base           3.3.2            py38h181983e_0
	mccabe                    0.6.1                    py38_1
	mistune                   0.8.4           py38h1de35cc_1001
	mitosheet                 0.1.88                   pypi_0    pypi
	mitosheet3                0.3.1                    pypi_0    pypi
	mkl                       2019.4                      233
	mkl-service               2.3.0            py38hfbe908c_0
	mkl_fft                   1.2.0            py38hc64f4ea_0
	mkl_random                1.1.1            py38h959d312_0
	mock                      4.0.2                      py_0
	more-itertools            8.6.0              pyhd3eb1b0_0
	mpc                       1.1.0                h6ef4df4_1
	mpfr                      4.0.2                h9066e36_1
	mpmath                    1.1.0                    py38_0
	msgpack-python            1.0.0            py38h04f5b5a_1
	multipledispatch          0.6.0                    py38_0
	navigator-updater         0.2.1                    py38_0
	nbclassic                 0.2.6                    pypi_0    pypi
	nbclient                  0.5.1                      py_0
	nbconvert                 6.0.7                    py38_0
	nbformat                  5.0.8                      py_0
	ncurses                   6.2                  h0a44026_1
	nest-asyncio              1.4.2              pyhd3eb1b0_0
	networkx                  2.5                        py_0
	nltk                      3.5                        py_0
	nose                      1.3.7                 py38_1004
	notebook                  6.1.4                    py38_0
	numba                     0.51.2           py38h6440ff4_1
	numexpr                   2.7.1            py38hce01a72_0
	numpy                     1.19.2           py38h456fd55_0
	numpy-base                1.19.2           py38hcfb5961_0
	numpydoc                  1.1.0              pyhd3eb1b0_1
	olefile                   0.46                       py_0
	openpyxl                  3.0.5                      py_0
	openssl                   1.1.1h               haf1e3a3_0
	packaging                 20.4                       py_0
	pandas                    1.1.3            py38hb1e8313_0
	pandoc                    2.11                 h0dc7051_0
	pandocfilters             1.4.3            py38hecd8cb5_1
	parso                     0.7.0                      py_0
	partd                     1.1.0                      py_0
	path                      15.0.0                   py38_0
	path.py                   12.5.0                        0
	pathlib2                  2.3.5                    py38_1
	pathtools                 0.1.2                      py_1
	patsy                     0.5.1                    py38_0
	pcre                      8.44                 hb1e8313_0
	pep8                      1.7.1                    py38_0
	pexpect                   4.8.0                    py38_1
	pickleshare               0.7.5                 py38_1001
	pillow                    8.0.1            py38h5270095_0
	pip                       20.2.4           py38hecd8cb5_0
	pkginfo                   1.6.1            py38hecd8cb5_0
	pluggy                    0.13.1                   py38_0
	ply                       3.11                     py38_0
	prometheus_client         0.8.0                      py_0
	prompt-toolkit            3.0.8                      py_0
	prompt_toolkit            3.0.8                         0
	psutil                    5.7.2            py38haf1e3a3_0
	ptyprocess                0.6.0                    py38_0
	py                        1.9.0                      py_0
	py-lief                   0.10.1           py38haf313ee_0
	pycodestyle               2.6.0                      py_0
	pycosat                   0.6.3            py38h1de35cc_1
	pycparser                 2.20                       py_2
	pycurl                    7.43.0.6         py38hddc9c9b_0
	pydocstyle                5.1.1                      py_0
	pyflakes                  2.2.0                      py_0
	pygments                  2.7.2              pyhd3eb1b0_0
	pylint                    2.6.0                    py38_0
	pyodbc                    4.0.30           py38h0a44026_0
	pyopenssl                 19.1.0                     py_1
	pyparsing                 2.4.7                      py_0
	pyqt                      5.9.2            py38h655552a_2
	pyrsistent                0.17.3           py38haf1e3a3_0
	pysocks                   1.7.1                    py38_1
	pytables                  3.6.1            py38h4727e94_0
	pytest                    6.1.1                    py38_0
	python                    3.8.5                h26836e1_1
	python-dateutil           2.8.1                      py_0
	python-jsonrpc-server     0.4.0                      py_0
	python-language-server    0.35.1                     py_0
	python-libarchive-c       2.9                        py_0
	python.app                2                       py38_10
	pytz                      2020.1                     py_0
	pywavelets                1.1.1            py38haf1e3a3_2
	pyyaml                    5.3.1            py38haf1e3a3_1
	pyzmq                     19.0.2           py38hb1e8313_1
	qdarkstyle                2.8.1                      py_0
	qt                        5.9.7                h468cd18_1
	qtawesome                 1.0.1                      py_0
	qtconsole                 4.7.7                      py_0
	qtpy                      1.9.0                      py_0
	readline                  8.0                  h1de35cc_0
	regex                     2020.10.15       py38haf1e3a3_0
	requests                  2.24.0                     py_0
	ripgrep                   12.1.1                        0
	rope                      0.18.0                     py_0
	rtree                     0.9.4                    py38_1
	ruamel_yaml               0.15.87          py38haf1e3a3_1
	scikit-image              0.17.2           py38h81aa140_0
	scikit-learn              0.23.2           py38h959d312_0
	scipy                     1.5.2            py38h2515648_0
	seaborn                   0.11.0                     py_0
	send2trash                1.5.0                    py38_0
	setuptools                50.3.1           py38hecd8cb5_1
	simplegeneric             0.8.1                    py38_2
	singledispatch            3.4.0.3                 py_1001
	sip                       4.19.8           py38h0a44026_0
	six                       1.15.0           py38hecd8cb5_0
	sniffio                   1.2.0                    pypi_0    pypi
	snowballstemmer           2.0.0                      py_0
	sortedcollections         1.2.1                      py_0
	sortedcontainers          2.2.2                      py_0
	soupsieve                 2.0.1                      py_0
	sphinx                    3.2.1                      py_0
	sphinxcontrib             1.0                      py38_1
	sphinxcontrib-applehelp   1.0.2                      py_0
	sphinxcontrib-devhelp     1.0.2                      py_0
	sphinxcontrib-htmlhelp    1.0.3                      py_0
	sphinxcontrib-jsmath      1.0.1                      py_0
	sphinxcontrib-qthelp      1.0.3                      py_0
	sphinxcontrib-serializinghtml 1.1.4                      py_0
	sphinxcontrib-websupport  1.2.4                      py_0
	spyder                    4.1.5                    py38_0
	spyder-kernels            1.9.4                    py38_0
	sqlalchemy                1.3.20           py38h9ed2024_0
	sqlite                    3.33.0               hffcf06c_0
	statsmodels               0.12.0           py38haf1e3a3_0
	sympy                     1.6.2            py38hecd8cb5_1
	tblib                     1.7.0                      py_0
	terminado                 0.9.1                    py38_0
	testpath                  0.4.4                      py_0
	threadpoolctl             2.1.0              pyh5ca1d4c_0
	tifffile                  2020.10.1        py38h0cf3a3e_2
	tk                        8.6.10               hb0a8c7a_0
	toml                      0.10.1                     py_0
	toolz                     0.11.1                     py_0
	tornado                   6.1                      pypi_0    pypi
	tqdm                      4.50.2                     py_0
	traitlets                 5.0.5                      py_0
	typing_extensions         3.7.4.3                    py_0
	ujson                     4.0.1            py38hb1e8313_0
	unicodecsv                0.14.1                   py38_0
	unixodbc                  2.3.9                haf1e3a3_0
	urllib3                   1.25.11                    py_0
	watchdog                  0.10.3           py38haf1e3a3_0
	wcwidth                   0.2.5                      py_0
	webencodings              0.5.1                    py38_1
	werkzeug                  1.0.1                      py_0
	wheel                     0.35.1                     py_0
	widgetsnbextension        3.5.1                    py38_0
	wrapt                     1.11.2           py38h1de35cc_0
	wurlitzer                 2.0.1                    py38_0
	xlrd                      1.2.0                      py_0
	xlsxwriter                1.3.7                      py_0
	xlwings                   0.20.8                   py38_0
	xlwt                      1.3.0                    py38_0
	xmltodict                 0.12.0                     py_0
	xz                        5.2.5                h1de35cc_0
	yaml                      0.2.5                haf1e3a3_0
	yapf                      0.30.0                     py_0
	zeromq                    4.3.3                hb1e8313_3
	zict                      2.0.0                      py_0
	zipp                      3.4.0              pyhd3eb1b0_0
	zlib                      1.2.11               h1de35cc_3
	zope                      1.0                      py38_1
	zope.event                4.5.0                    py38_0
	zope.interface            5.1.2            py38haf1e3a3_0
	zstd                      1.4.5                h41d2c2f_0
</pre>
</details>

### On Windows
Run the commands
```
python3 -m venv venv
venv\Scripts\activate.bat
pip install mitosheet3 
jupyter lab
```
Then, run the follow code in a JLab notebook:
```
import mitosheet3 as mitosheet
mitosheet.sheet()
```
Instead of displaying a widget, this will throw the following error in the console:
![image](https://user-images.githubusercontent.com/21002431/112896968-e5819880-9093-11eb-819b-e9c4d0248766.jpg)

And further say "Error displaying widget" in the notebook.

**As far as I can tell, this error is a result of the widget manager trying to look up mitosheet using the JupyterLab version (3.0.12), rather than the mitosheet version (0.3.5). Any idea why this would be the case?**

### Context for Windows

- Windows 10 pro - 1909
- Using Edge Version 89.0.774.63 (Official build) (64-bit)
- JLab 3.0.12

<details><summary>Troubleshoot Output</summary>
<pre>
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\users\nater\testing\venv\scripts\python.exe -m pip install --upgrade pip' command.
$PATH:
        C:\Users\nater\testing\venv\Scripts
        C:\Windows\system32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0\
        C:\Windows\System32\OpenSSH\
        C:\Program Files\Intel\WiFi\bin\
        C:\Program Files\Common Files\Intel\WirelessCommon\
        c:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
        c:\Program Files\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files\Git\cmd
        C:\Program Files\nodejs\
        C:\Users\nater\AppData\Local\Microsoft\WindowsApps

        C:\Users\nater\AppData\Local\Programs\Microsoft VS Code\bin
        C:\Users\nater\AppData\Roaming\npm

sys.path:
        C:\Users\nater\testing\venv\Scripts\jupyter-troubleshoot.EXE
        C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\python38.zip
        C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\DLLs
        C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib
        C:\Users\nater\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0
        c:\users\nater\testing\venv
        c:\users\nater\testing\venv\lib\site-packages
        c:\users\nater\testing\venv\lib\site-packages\win32
        c:\users\nater\testing\venv\lib\site-packages\win32\lib
        c:\users\nater\testing\venv\lib\site-packages\Pythonwin

sys.executable:
        c:\users\nater\testing\venv\scripts\python.exe

sys.version:
        3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.18362-SP0

where jupyter:
        C:\Users\nater\testing\venv\Scripts\jupyter.exe

pip list:
        Package             Version
        ------------------- ---------
        analytics-python    1.2.9
        anyio               2.2.0
        argon2-cffi         20.1.0
        async-generator     1.10
        attrs               20.3.0
        Babel               2.9.0
        backcall            0.2.0
        bleach              3.3.0
        certifi             2020.12.5
        cffi                1.14.5
        chardet             4.0.0
        colorama            0.4.4
        cycler              0.10.0
        decorator           4.4.2
        defusedxml          0.7.1
        entrypoints         0.3
        idna                2.10
        ipykernel           5.5.2
        ipython             7.22.0
        ipython-genutils    0.2.0
        ipywidgets          7.6.3
        jedi                0.18.0
        Jinja2              2.11.3
        json5               0.9.5
        jsonschema          3.2.0
        jupyter-client      6.1.12
        jupyter-core        4.7.1
        jupyter-packaging   0.7.12
        jupyter-server      1.5.1
        jupyterlab          3.0.12
        jupyterlab-pygments 0.1.2
        jupyterlab-server   2.3.0
        jupyterlab-widgets  1.0.0
        kiwisolver          1.3.1
        MarkupSafe          1.1.1
        matplotlib          3.4.0
        mistune             0.8.4
        mitosheet3          0.3.5
        nbclassic           0.2.6
        nbclient            0.5.3
        nbconvert           6.0.7
        nbformat            5.1.2
        nest-asyncio        1.5.1
        notebook            6.3.0
        numpy               1.20.2
        packaging           20.9
        pandas              1.2.3
        pandocfilters       1.4.3
        parso               0.8.1
        pickleshare         0.7.5
        Pillow              8.1.2
        pip                 20.2.3
        prometheus-client   0.9.0
        prompt-toolkit      3.0.18
        pycparser           2.20
        Pygments            2.8.1
        pyparsing           2.4.7
        pyrsistent          0.17.3
        python-dateutil     2.8.1
        pytz                2021.1
        pywin32             300
        pywinpty            0.5.7
        pyzmq               22.0.3
        requests            2.25.1
        Send2Trash          1.5.0
        setuptools          49.2.1
        six                 1.15.0
        sniffio             1.2.0
        terminado           0.9.4
        testpath            0.4.4
        tornado             6.1
        traitlets           5.0.5
        urllib3             1.26.4
        wcwidth             0.2.5
        webencodings        0.5.1
        widgetsnbextension  3.5.1
</pre>
</details>

**Comment by jasongrout** [comment]
The widget manager is trying to look up the version that mitosheet tells it to look up in its initial message from the python side. To diagnose this, first look at what mitosheet is setting as its `_view_module_version_` and `_model_module_version_` in python. You can also look at the websocket message coming from the kernel to see what version mitosheet is claiming it is.

Is the mitosheet code somewhere?

**Comment by jasongrout** [comment]
My guess is that your code in `_version.py` is fetching the jlab version number, rather than the mito version number. Perhaps instead of going up several directories and doing an rglob to find the first package.json it can, just hardcode the path to exactly where you know the package.json is, or just write the version number twice.

**Comment by naterush** [comment]
Sweet. I'm sure you're right about _version.py; I'll verify this today and post an update here. 

Thanks so much for getting back to me @jasongrout. You are stupendously appreciated!

**Comment by naterush** [comment]
This worked! I just hardcoded the version number, and everything worked everywhere!

**Comment by jasongrout** [comment]
Great, thanks for following up here.
