### ISSUE TITLE
Do not clear existing selection when click-activating a cell

### ISSUE THREAD

**Issue by homofortis** [jupyterlab/jupyterlab#10038]
Please leave any existing selection active when a cell has been clicked to be selected/activated. Currently, when a cell is activated with a click any existing selection inside is cleared. It frequently happens that you need to re-copy a selection from previously used cells and it's a bit annoying to see the selection is there but when you click the cell it disappears and needs to be re-selected.

**Comment by agoose77** [comment]
@homofortis I would expect my cursor to move to the clicked position when I click on a code cell. 

When you select a cell in the notebook by clicking the left-hand region, you can use the <kbd>Enter</kbd> key to enter edit mode without changing the selection.
