### ISSUE TITLE
Can't click file browser item with one click

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1006]
If the file browser isn't focused, you can't select an item in it with a single click. If the file browser is focused, a single click will select it. Because there is no indicator to the user that the file browser is focused or not, this is confusing. 

The desired behavior is that a single click should select a file browser item always, no matter which element on the page was focused previously.

@blink1073

**Comment by blink1073** [comment]
I am unable to reproduce this, and a read-through of the mousedown handler in `listing.ts` looks like it should be doing the right thing.

![filebrowser-select](https://cloud.githubusercontent.com/assets/2096628/19118535/463f28b6-8ae2-11e6-846f-cb1a5ae8a4a8.gif)

**Comment by ellisonbg** [comment]
I am still seeing this and trying to work out when it happens...

**Comment by ellisonbg** [comment]
This is maddening - still see this regularly, but can't reproduce.

**Comment by ellisonbg** [comment]
Wow, I think I just found at least one reliable way of reproducing this:

* Create a new notebook
* Delete the notebook using the file browser context menu
* Confirm delete in the dialog
* Then try to immediately try to select something else in the file browser - it will take two clicks.

**Comment by blink1073** [comment]
Hurray, I can repro!
