### ISSUE TITLE
Support editing filename in simple mode's title bar.

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#10072]
I would be nice to support this way of editing the filname in the title bar for the simple mode just like in the classic notebook.

![simple-mode](https://user-images.githubusercontent.com/2397974/114222809-5582ff00-996f-11eb-9707-623677fe9d8f.png)

**Comment by cameron-toy** [comment]
I agree, that would be nice. I can work on this, seems straightforward enough.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/10140
