### ISSUE TITLE
Registering kernels for environments where ipykernel is not present

### ISSUE THREAD

**Issue by RubendeBruin** [jupyterlab/jupyterlab#10077]
## Description

When a notebook is created using a kernel other than the environment that jupyter lab was started from, then the paths should be adjusted accordingly.

I have two conda environments:
1. juplab
2. numpy

the juplab environment contains only jupyter lab and numpy only contains numpy.

*ipykernel is not present in the "numpy" environment"*

When I start jupyter-lab from the juplab environment then jupyter lab starts. When I start a notebook using the numpy kernel then I expect the PATH variable to be as follows:

```
...... c:\Data\apps\miniconda3\envs\numpy;c:\Data\apps\miniconda3\envs\numpy\Library\mingw-w64\bin;c:\Data\apps\miniconda3\envs\numpy\Library\usr\bin;c:\Data\apps\miniconda3\envs\numpy\Library\bin;c:\Data\apps\miniconda3\envs\numpy\Scripts;c:\Data\apps\miniconda3\envs\numpy\bin  ....
```
but instead it is:

```
...... c:\Data\apps\miniconda3\envs\juplab;c:\Data\apps\miniconda3\envs\juplab\Library\mingw-w64\bin;c:\Data\apps\miniconda3\envs\juplab\Library\usr\bin;c:\Data\apps\miniconda3\envs\juplab\Library\bin;c:\Data\apps\miniconda3\envs\juplab\Scripts;c:\Data\apps\miniconda3\envs\juplab\bin  ....
```
The effect of this is that numpy can not be imported: 
```
ModuleNotFoundError: No module named 'numpy'
```

### Windows 10:

1. Create two conda environments:

```
> conda create -n juplab jupyterlab
> conda create -n numpy numpy
```

2. Activate juplab and start jupyterlab
```
>activate juplab
> python -m ipykernel install --user --name numpy --display-name "np"
(juplab)> jupyter lab
```

3. In jupyter, start a new notebook based on np:

![image](https://user-images.githubusercontent.com/34062862/114338146-031b2b80-9b85-11eb-9664-9ddb360dca28.png)

4. Try to import numpy: It will fail with a "module can not be found" error

5. Display the active paths:

```
import sys

for p in sys.path:
    print(p)

c:\Data\apps\miniconda3\envs\juplab\python39.zip
c:\Data\apps\miniconda3\envs\juplab\DLLs
c:\Data\apps\miniconda3\envs\juplab\lib
c:\Data\apps\miniconda3\envs\juplab

c:\Data\apps\miniconda3\envs\juplab\lib\site-packages
c:\Data\apps\miniconda3\envs\juplab\lib\site-packages\win32
c:\Data\apps\miniconda3\envs\juplab\lib\site-packages\win32\lib
c:\Data\apps\miniconda3\envs\juplab\lib\site-packages\Pythonwin
c:\Data\apps\miniconda3\envs\juplab\lib\site-packages\IPython\extensions
C:\Users\rubendb\.ipython
```

```
import os
PATH = os.environ['PATH']
for p in PATH.split(';'):
    print(p)

c:\Data\apps\miniconda3\envs\juplab
c:\Data\apps\miniconda3\envs\juplab\Library\mingw-w64\bin
c:\Data\apps\miniconda3\envs\juplab\Library\usr\bin
c:\Data\apps\miniconda3\envs\juplab\Library\bin
c:\Data\apps\miniconda3\envs\juplab\Scripts
c:\Data\apps\miniconda3\envs\juplab\bin
c:\Data\apps\miniconda3\condabin
....
```

## Expected behavior

I would expect the paths to be updated to point to the "np" environment instead of the "juplab" invironment.

## Context

- Operating System and version: Windows 10
- Browser and version: Edge
- JupyterLab version: 3.0.13

<details><summary>Command Line Output</summary>
<pre>
(juplab) C:\Data>jupyter lab
[I 2021-04-12 11:49:29.231 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-04-12 11:49:29.250 ServerApp] The 'min_open_files_limit' trait of a ServerApp instance expected an int, not the NoneType None.
[I 2021-04-12 11:49:29.276 LabApp] JupyterLab extension loaded from c:\Data\apps\miniconda3\envs\juplab\lib\site-packages\jupyterlab
[I 2021-04-12 11:49:29.276 LabApp] JupyterLab application directory is C:\Data\apps\miniconda3\envs\juplab\share\jupyter\lab
[I 2021-04-12 11:49:29.282 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-04-12 11:49:29.602 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-04-12 11:49:29.741 ServerApp] Serving notebooks from local directory: C:\Data
[I 2021-04-12 11:49:29.741 ServerApp] Jupyter Server 1.6.0 is running at:
[I 2021-04-12 11:49:29.743 ServerApp] http://localhost:8888/lab?token=0e7e86fa3583749b5531717005718362aca021b54ad20045
[I 2021-04-12 11:49:29.743 ServerApp]     http://127.0.0.1:8888/lab?token=0e7e86fa3583749b5531717005718362aca021b54ad20045
[I 2021-04-12 11:49:29.743 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-04-12 11:49:29.796 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/rubendb/AppData/Roaming/jupyter/runtime/jpserver-8712-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=0e7e86fa3583749b5531717005718362aca021b54ad20045
        http://127.0.0.1:8888/lab?token=0e7e86fa3583749b5531717005718362aca021b54ad20045
[W 2021-04-12 11:49:42.390 LabApp] Could not determine jupyterlab build status without nodejs
[I 2021-04-12 11:49:45.554 ServerApp] Creating new notebook in
[I 2021-04-12 11:49:45.832 ServerApp] Kernel started: 3b70ed87-09d0-4363-bafb-5dd620f44056
[I 2021-04-12 11:51:45.701 ServerApp] Saving file at /Untitled8.ipynb
</pre>
</details>

**Comment by RubendeBruin** [comment]
The problem only occurs when ipykernel is not available in the selected environment

**Comment by agoose77** [comment]
It is my understanding that installing kernels in separate virtualenvironments/Conda environments is not a recommended practice. The `kernelspec` standard doesn't know about environments. There was `nb_conda_kernels`, but it is no longer maintained by its developers IIRC. You can implement this yourself with a simple shim to activate the environment before `exec`-ing the kernel and creating the kernelspec yourself, or you can install JupyterLab into each environment that you use.

**Comment by RubendeBruin** [comment]
Hi @agoose77 , thanks you for reply.
I just shamefully realize that I [double posted](https://discourse.jupyter.org/t/windows-path-not-adjusted-to-reflect-kernel-location-prefix/8766) this issue (I have a jetlag that I can blame though).

The IPython-documentation explicitly mentions the possibility to install kernels in different conda environments is a possibility.  And spyder-kernels _does_ get it working correctly.

Will close there.
