### ISSUE TITLE
raw_input on a py2 kernel doesnt work as intended

### ISSUE THREAD

**Issue by StatsThoughts** [jupyterlab/jupyterlab#10071]
## Description

On Jupyterlab 3 (Classic notebooks and in lab) the raw_input on a python 2 kernel will fail (~5-20%) to produce an output that will allow for any keyboard input for a raw_input() call. This error can take up two forms:

- The cell will show [*] with no output of the cell (even if a print statement is called before the raw_input function is called)
- The cell will show the results of all code before the raw_input statement (such as a print statement) 

Occationally when sending a stop stignal to the kernel, the cell will stop running (allowing for other cells to be run) the cell will always show [*] despite not running. This can only be gotten rid of by restarting the kernel. Furthermore, if the error appears once, any other cell that contains a raw_input() call will always yield the same frozen result. This behavior can only be reset by restarting the kernel

We've only been able to reproduce this on our enteriprise soloution which uses a JupyterHub Docker and have been unable to reproduce this on a local build of Jupyterlab. 

## Reproduce

1. Open a workbook and switch to a Python 2 Kernel 
2. In a cell run the following code 
<details><summary>Browser Output</summary>
<pre>
print("asdf")
raw_input("a")
</pre>
</details>

3. Repeat step 2 until error is seen. If cell execution count >100 then its likely the error wont occur. For us this typically occurs after execution count 25-40. 

## Expected behavior

raw_input() will work properly at without failure

## Context
We've tested a nunmber of different package versions, and found that this will appear with the base python 2 version packaged with the Anaconda distriburtion. This error is not consistent and we've have not been able to reproduce this on a local build of Jupyterlab. Updating to the latest versions of Ipykernel, and ipywidgets did not resovle the issue. 

Furthermore, input() in any Py3 kernel will work as intended - this is only an issue affecting py2 kernels. 

I couldnt gleam any infromation from a pdb stack trace, as the internals of raw_input would work fine when i run the stack trace, so I can't see this as an error with the code itself. Not sure if there is anything else I could try as its a basic python function, so it should work fine (but its clearly not)

**Comment by agoose77** [comment]
@StatsThoughts would you be able to share a Dockerfile that generates this environment? I'm happy to take a quick look at this for triage but it would be helpful if I didn't need to setup the env as well!

**Comment by StatsThoughts** [comment]
Hi @agoose77 - unfortunately i'm not able to provide any more information that I've mentioned above :(
