### ISSUE TITLE
3.0.13 changelog links broken

### ISSUE THREAD

**Issue by jabbera** [jupyterlab/jupyterlab#10084]
## Description

https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html links to the PRs include bad links. Dunno why /repos is in there?

https://github.com/repos/jupyterlab/jupyterlab/pull/10018

**Comment by blink1073** [comment]
Thanks for the report @jabbera!  I had an issue with my changelog generator tool, I'll post a fix soon.
