### ISSUE TITLE
Error in @jupyterlab/filebrowser 

### ISSUE THREAD

**Issue by florist-gump** [jupyterlab/jupyterlab#10088]
## ts error in @jupyterlab/filebrowser 

After installing @jupyterlab/filebrowser  I get the following error:
`node_modules/@jupyterlab/filebrowser/lib/browser.d.ts:33:5 - error TS2610: 'layout' is defined as an accessor in class 'Widget', but is overridden here in 'FileBrowser' as an instance property.` 

## Reproduce

I was trying to follow the basic example to add a new context menu item [here](https://github.com/jupyterlab/extension-examples/tree/master/context-menu)

But after installing @jupyterlab/filebrowser  I get the error shown above.

I used the cookiecutter ts [template](https://github.com/jupyterlab/extension-cookiecutter-ts) to setup the extention project.

**Comment by krassowski** [comment]
Just a guess: may you have incompatible versions installed? What is your

```
jlpm list --pattern "@jupyterlab/filebrowser"
```

and

```
jupyter lab --version
```
?

**Comment by fcollonval** [comment]
Hey I hit that one when upgrading the `yarn.lock` on @jupyterlab/git: https://github.com/jupyterlab/jupyterlab-git/pull/926/checks?check_run_id=2359801487

I check there are only one version of @jupyterlab/filebrowser and @lumino/widgets in the yarn.lock.

**Comment by fcollonval** [comment]
That new behaviour was introduced by [Typescript 4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html?ref=hvper.com#properties-overriding-accessors-and-vice-versa-is-an-error). But I don't know why it was not it before...

**Comment by fcollonval** [comment]
I was able to reproduce it on a simple example:

1. Create a new extension from the cookiecutter
```
cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts
cd myextension
```
2. Add @jupyterlab/filebrowser as dependency
```
jlpm add @jupyterlab/filebrowser
```
3. Modify index.ts
```ts
import {
  JupyterFrontEnd,
  JupyterFrontEndPlugin
} from '@jupyterlab/application';

import {IFileBrowserFactory} from '@jupyterlab/filebrowser'

/**
 * Initialization data for the myextension extension.
 */
const extension: JupyterFrontEndPlugin<void> = {
  id: 'myextension:plugin',
  autoStart: true,
  requires: [IFileBrowserFactory],
  activate: (app: JupyterFrontEnd, factory: IFileBrowserFactory) => {
    console.log('JupyterLab extension myextension is activated!');
  }
};

export default extension;
```
4. Run jlpm run build

You will hit the error.

**Comment by fcollonval** [comment]
I dig this one up and it is quite tricky. The trouble comes from a change in the type file generated by the lumino package. In 1.19.0, the `layout` accessor was translated as property in the type declaration. But now in 1.20.0, the accessor is kept:

![image](https://user-images.githubusercontent.com/8435071/115112688-f46ab500-9f86-11eb-8359-a787eeb25c79.png)

This coupled with the new constrain on Typescript v4 will break code. The error is now seen on JupyterLab yet as the lock file is pulling version 1.19.0 of @lumino/widgets.

I'm opening an issue on lumino.

**Comment by fcollonval** [comment]
If @lumino/widgets is upgrading on JupyterLab, we indeed hit the issue:

```
../celltags/src/widget.ts:150:10 - error TS2610: 'parent' is defined as an accessor in class 'Widget', but is overridden here in 'TagWidget' as an instance property.

150   public parent: TagTool | null = null;
             ~~~~~~

../celltags/src/addwidget.ts:164:10 - error TS2610: 'parent' is defined as an accessor in class 'Widget', but is overridden here in 'AddWidget' as an instance property.

164   public parent: TagTool | null = null;
             ~~~~~~

../debugger/src/sidebar.ts:131:3 - error TS2610: 'isDisposed' is defined as an accessor in class 'Panel', but is overridden here in 'DebuggerSidebar' as an instance property.

131   isDisposed: boolean;
      ~~~~~~~~~~

../filebrowser/src/browser.ts:159:3 - error TS2610: 'layout' is defined as an accessor in class 'Widget', but is overridden here in 'FileBrowser' as an instance property.

159   layout: PanelLayout;

**Comment by Mathemmagician** [comment]
Is there a quick workaround for this? Getting the same issue

```
> jupyter lab --version
3.0.14

> jlpm list --pattern "@jupyterlab/filebrowser"
yarn list v1.21.1
└─ @jupyterlab/filebrowser@3.1.0-alpha.4
```

**Comment by fcollonval** [comment]
@Mathemmagician I would recommend forcing the resolution of @lumino/widgets to 1.19.0 by adding the following section in the `package.json` file:

```
  "resolutions": {
    "@lumino/widgets": "~1.19.0"
  }
```

**Comment by fcollonval** [comment]
A fix was pushed upstream in https://github.com/jupyterlab/lumino/pull/172

You should not see the error any more after running `jlpm upgrade`.

In case you are still having trouble, you may define in `package.json` the following section:

```json
  "resolutions": {
    "@lumino/widgets": "^1.21.0"
  }
```

**Comment by Mathemmagician** [comment]
`"@lumino/widgets": "^1.21.0"` was giving me some other errors, but pulling back to 1.18 with `jlpm add @lumino/widgets@1.18` solved the issue

**Comment by LTKy** [comment]
@fcollonva All dependencies are latest, but still this problem exists.
Attempts to add resolutions configuration to `package.json` cause other problems as well.

**Comment by fcollonval** [comment]
Hey **@all**, sorry indeed the fix on lumino is not working as the type file is still altered... I'm reopening this one.

**Comment by raulotaolea** [comment]
I also hit this when updating versions.

**Comment by jtpio** [comment]
Are you able to check with the latest `lumino` release? https://github.com/jupyterlab/lumino/releases/tag/2021.4.27

This should hopefully help fix the issue.
