### ISSUE TITLE
Properly way to define new CodeMirror mode in JLab extension

### ISSUE THREAD

**Issue by BoPeng** [jupyterlab/jupyterlab#10095]
I have tried to upgrade [jupyterlab-sos](https://github.com/vatlab/jupyterlab-sos) to work with JLab 3.x but could not get syntax highlighting to work. I used to define my own mode in [`codemirror-sos.ts`](https://github.com/vatlab/jupyterlab-sos/blob/11abe06348563ad1e596384a339d2cdd19f411e4/src/codemirror-sos.ts#L252-L254) as

```javascript
import * as CodeMirror from "codemirror";
(CodeMirror as any).defineMode(
  "sos",
  function (conf: CodeMirror.EditorConfiguration, parserConf: any) {
 ...
})

(CodeMirror as any).defineMIME("text/x-sos", "sos");

(CodeMirror as any).modeInfo.push({
  ext: ["sos"],
  mime: "text/x-sos",
  mode: "sos",
  name: "SoS"
});
```

and then import it in [`index.ts`](https://github.com/vatlab/jupyterlab-sos/blob/11abe06348563ad1e596384a339d2cdd19f411e4/src/index.ts#L28)

```javascript
import * as CodeMirror from "codemirror";
```

The code still compiles but the mode is never defined for JLab 3.  I read a few discussions on this issue (#9124, #9161 etc). It looks that it has something to do with lazy loading or "singleton CodeMirror instance" but I could not find an example on how to define my own CodeMirror mode in an extension. @jasongrout Could you help me out?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/kernel-with-codemirror-simplemode-defined-not-surviving-refresh/1692/2

**Comment by krassowski** [comment]
I think that you need to use `ICodeMirror` token to get the CodeMirror instance as used by the lab:

```
import { ICodeMirror } from '@jupyterlab/codemirror';
```

This works well for spellchecker:
- https://github.com/jupyterlab-contrib/spellchecker/blob/406631ef24c8c7cfd0611543626a67123ee14ccc/src/index.ts#L597
- https://github.com/jupyterlab-contrib/spellchecker/blob/406631ef24c8c7cfd0611543626a67123ee14ccc/src/index.ts#L503

and in the LSP: https://github.com/krassowski/jupyterlab-lsp/pull/576

**Comment by BoPeng** [comment]
Thanks. I will try `ICodeMirror` and post the solution back here if I can make it work.

**Comment by BoPeng** [comment]
Got it to work! A direct translation of the JLab 2.x => 3.x method would be

1. In `codemirror-sos.ts`, instead of calling `defineMode` as shown above, define and export the mode function as

```javascript
import CodeMirror from 'codemirror';
export function sos_mode(conf: CodeMirror.EditorConfiguration, parserConf: any) {
 ...
};
```

2. In `index.ts`, call `ICodeMirror.CodeMirror.defineMode` as 

```javascript

import {
  ICodeMirror
} from '@jupyterlab/codemirror';
import {
 sos_mode
} from "./codemirror-sos";

function defineSoSCodeMirrorMode(code_mirror_singleton) {
  (code_mirror_singleton as any).defineMode(
    "sos",
    sos_mode,
    "python");

  (code_mirror_singleton as any).defineMIME("text/x-sos", "sos");

  (code_mirror_singleton as any).modeInfo.push({
    ext: ["sos"],
    mime: "text/x-sos",
    mode: "sos",
    name: "SoS"
  });
}


const extension: JupyterFrontEndPlugin<void> = {
  id: "vatlab/jupyterlab-extension:sos",
  autoStart: true,
  requires: [INotebookTracker, IConsoleTracker, ICommandPalette, ICodeMirror],
  activate: (
    app: JupyterFrontEnd,
    notebook_tracker: INotebookTracker,
    console_tracker: IConsoleTracker,
    palette: ICommandPalette,
    codeMirror: ICodeMirror,
  ) => {
    defineSoSCodeMirrorMode(codeMirror.CodeMirror);
   ...
```

The code is not pretty but does the job.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/whats-wrong-with-the-way-im-using-codemirror-in-this-prebuilt-version-of-jupyterlab-ihaskell/10539/3
