### ISSUE TITLE
Topbar menu items importance

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#10091]
An issue that has come up a couple of times, is people interested in providing only a subset of the menu items available in the topbar menus, that they thought were more important. For example, "**Restart Kernel and Run All**" is probably more important than "**Restart Kernel and Run up to Selected Cell**" which could still be made available as a command in the palette.

A solution to that issue would be for these items to have a **weight** or **importance level**,  and to only show items that are beyond a certain threeshold when running lab in a light mode (very much like we have log levels for messages).

**Comment by jasongrout** [comment]
> An issue that has come up a couple of times, is people interested in providing only a subset of the menu items available in the topbar menus, that they thought were more important

From the way you phrase this, it sounds like it is a user decision about what is important. Instead of making the plugin assigning an importance level, what if we make a user setting for the menu plugin that allows them to remove menu items (i.e., command ids) from certain menus? A system administrator could seed this list if they wanted using `overrides.json`.

**Comment by bollwyvl** [comment]
Yeah: there are a lot of things that are currently TS-only APIs that could be more interesting if they were hoisted to a data/schema layer. Basically anything that has a `rank` or `order`, to be sure.

Menus in particular are (generally, hopefully) well-behaved... if they were data-backed, I could imagine a very nice UI for dragging menu items up and down, making new menus, hiding things.


But, as has been mentioned a few times, for really _removing_ things, a feature flag approach might be more powerful. With this approach, one could eventually start with something closer to jupyterlab-classic and incrementally add features, though i would imagine they would require reloads. It seems like features might live naturally in a chain of:
- defaults
- workspace definition
- settings

I'd see the definition of the flags themselves as being squarely in `schema`, so they could carry documentation and eventually participate in nice UI... even if they lived in a "custom" part of settings, like keyboard shortcuts.

**Comment by bollwyvl** [comment]
Lost in the above, but i feel like trying to establish a A One The Number for how much UI to get sounds... hard to coordinate.

**Comment by fcollonval** [comment]
Hey I'll push a proposition based on @jasongrout suggestion.

**Comment by ellisonbg** [comment]
This is an interesting idea. Are there other applications that we can look to for ideas?

**Comment by fcollonval** [comment]
Office softwares have a similar feature (it was kind of standard on major Microsoft desktop app back in the days). In those software the customization is huge as you can basically pick any commands in the order you would like.

- Office Ribbon: https://support.microsoft.com/en-us/topic/customize-the-ribbon-in-office-00f24ca7-6021-48d3-9514-a31a460ecb31
> They have locked some menus it seems. Before the ribbon UI, the customization was similar to the one in LibreOffice.
- LibreOffice : https://help.libreoffice.org/7.1/en-US/text/shared/01/06140100.html?DbPAR=SHARED
![image](https://user-images.githubusercontent.com/8435071/117252363-22387080-ae46-11eb-94db-59a56f77e0d0.png)
> Sorry for the french
- visual studio 2019: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-customize-menus-and-toolbars-in-visual-studio?view=vs-2019

**Comment by krassowski** [comment]
- PyCharm

![pycharm](https://user-images.githubusercontent.com/5832902/117328779-de685a00-ae8b-11eb-9af2-e083d3f0a78b.gif)

https://www.jetbrains.com/help/pycharm/customize-actions-menus-and-toolbars.html#da6e2d1d

- VSCode:

Change of order of items in context menu is possible using JSON: https://stackoverflow.com/questions/46714353/how-to-customize-context-menu-in-visual-studio-code

**Comment by fcollonval** [comment]
Thanks @krassowski to add all those examples. I'm working on a new approach from @bollwyvl thoughts.
