### ISSUE TITLE
Ability to configure NPM Registry and CDN for ExtensionManager

### ISSUE THREAD

**Issue by jhamet93** [jupyterlab/jupyterlab#10109]
At the moment, the NPM Registry and the CDN used to grab metadata from a packages `package.json` are hardcoded.  In some organizations (like my own), access to the outside internet is not allowed directly from our internal compute instances which makes users unable to utilize the `ExtensionManager`.  Thus, the ability for a user to configure these URL's would be ideal to extend access to those who may have artifact repositories that their services can talk to for these dependencies but not the outside internet.

**Comment by fcollonval** [comment]
Closing as fixed
