### ISSUE TITLE
"Alt + -" does not input "<-" when using IRkernel in JupyterLab (it worked in Jupyter Notebook)

### ISSUE THREAD

**Issue by HelangelCovno** [jupyterlab/jupyterlab#10114]
### Problem

When using r language , jubyter can use "alt+-" to input <- quickly but jubyterlab can 't .

**Comment by krassowski** [comment]
This was previously tracked in https://github.com/jupyterlab/jupyterlab/issues/4519, but appears that it was never documented (outside of changelog). I think that we should document how to make adjustments like that possible. In particular, thanks to https://github.com/jupyterlab/jupyterlab/pull/7908 you can configure your keyboard shortcuts to resemble that of RStudio with the following:

```json
{
    "shortcuts": [
        {
            "command": "apputils:run-first-enabled",
            "selector": "body",
            "keys": ["Alt -"],
            "args": {
                "commands": [
                    "console:replace-selection",
                    "fileeditor:replace-selection",
                    "notebook:replace-selection",
                ],
                "args": {"text": "<- "}
            }
        },
        {
            "command": "apputils:run-first-enabled",
            "selector": "body",
            "keys": ["Accel Shift M"],
            "args": {
                "commands": [
                    "console:replace-selection",
                    "fileeditor:replace-selection",
                    "notebook:replace-selection",
                ],
                "args": {"text": ">%> "}
            }
        }
    ]
}
```

`Accel` means <kbd>Ctrl</kbd> on Linux and Windows, or <kbd>Command</kbd> on Mac.

Just go to the `Advanced Settings Editor` -> `Keyboard Shortcuts`, paste and save:

![rstudio](https://user-images.githubusercontent.com/5832902/115147572-88a24e00-a053-11eb-9a2e-2b44cece41d4.gif)

PS. You will need a modern JupyterLab version, at least 2.1+ (I usually recommend the latest, currently 3.0).

**Comment by HelangelCovno** [comment]
Thank you, this solves a big problem that has been bothering me for a long time!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Michał ***@***.***>
发送时间: 2021年4月18日 21:40
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [jupyterlab/jupyterlab] When using r language , jubyter can use "alt+-" to input <- quickly but jubyterlab can 't . (#10114)


This was previously tracked in #4519<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjupyterlab%2Fjupyterlab%2Fissues%2F4519&data=04%7C01%7C%7C821b0692d32e427bd3d608d9026f85a5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637543500265600521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yydhM9ceWmFxCMSR0ctxJkwWEFxqqGne8I5jidbsjFI%3D&reserved=0>, but appears that it was never documented (outside of changelog). I think that we should document how to make adjustments like that possible. In particular, thanks to #7908<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjupyterlab%2Fjupyterlab%2Fpull%2F7908&data=04%7C01%7C%7C821b0692d32e427bd3d608d9026f85a5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637543500265610517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0N3oMDF44mnpHvY7IUuCM89YhbD4fXQrjF15boZuqrQ%3D&reserved=0> you can configure your keyboard shortcuts to resemble that of RStudio with the following:

{

    "shortcuts": [

        {

            "command": "apputils:run-first-enabled",

            "selector": "body",

            "keys": ["Alt -"],

            "args": {

                "commands": [

                    "console:replace-selection",

                    "fileeditor:replace-selection",

                    "notebook:replace-selection",

                ],

                "args": {"text": "<- "}

            }

        },

        {

            "command": "apputils:run-first-enabled",

            "selector": "body",

            "keys": ["Accel Shift M"],

            "args": {

                "commands": [

                    "console:replace-selection",

                    "fileeditor:replace-selection",

                    "notebook:replace-selection",

                ],

                "args": {"text": ">%> "}

            }

        }

    ]

}

Accel means Ctrl on Linux and Windows, or Command on Mac.

Just go to the Advanced Settings Editor -> Keyboard Shortcuts, paste and save:

[rstudio]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F5832902%2F115147572-88a24e00-a053-11eb-9a2e-2b44cece41d4.gif&data=04%7C01%7C%7C821b0692d32e427bd3d608d9026f85a5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637543500265610517%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VWWnnkhjCBWvbpUmIB6w22f%2FzUWJx%2F3RRthNj47ulig%3D&reserved=0>

PS. You will need a modern JupyterLab version, at least 2.1+ (I usually recommend the latest, currently 3.0).

**Comment by agoose77** [comment]
I'm closing this issue now, given that the author seems happy with the solution.
