### ISSUE TITLE
Terminal not showing specified `fontFamily`

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#10112]
## Description

I've installed `Fira Code` in my Ubuntu 18.04 container and am trying to use it for the JupyterLab terminal with no success..

The font is recognised by `fc-list`:

![image](https://user-images.githubusercontent.com/881019/115113437-aaf18880-9fcd-11eb-88c9-f04312aff54e.png)

...but when I specify it in my terminal config:
```json
{
    "fontFamily": "FiraCode Nerd Font",
    "fontSize": 16
}
```
It results in something that looks like double-spaced Times New Roman:

![image](https://user-images.githubusercontent.com/881019/115113464-d83e3680-9fcd-11eb-8332-8bda467cc5b1.png)

...which seems to be what happens when JupyterLab doesn't recognise the specified font (e.g. if you specify `"dsfafds"` you get the same result.)

If I specify `consolas` (or a fallback to `consolas`) the font renders correctly:

![image](https://user-images.githubusercontent.com/881019/115113460-c9578400-9fcd-11eb-840a-f73fcbf19c31.png)

I've pretty exhaustively tried all ways of specifying the name, including quotes and no quote with no joy.

----
- Operating System and version:
- Browser and version:  chrome 89.0.4389.90 
- JupyterLab version: 3.0.14

**Comment by dhirschfeld** [comment]
Has anyone actually gotten this to work with a user installed font?

Does anyone have any suggestions of how to debug this?

**Comment by dhirschfeld** [comment]
***xref:*** #6657

**Comment by dhirschfeld** [comment]
If I run the container as root specifying `"fontFamily": "FiraCode Nerd Font"` works :tada:

![image](https://user-images.githubusercontent.com/881019/116493792-cff5cd80-a8e2-11eb-9908-3488ecf4fda8.png)


...so it seems like a permission error :/

**Comment by dhirschfeld** [comment]
I'm not sure running the container as root had any effect *however* what did work was installing the `Fira Code` font on the local users computer - i.e. it's not enough to just install the font in the JupyterLab container the user running JupyterLab also needs to have the font installed locally.

I'm not sure if there's a better way? Since this works though, I'll go ahead and close this...

**Comment by telamonian** [comment]
@dhirschfeld Dumb question: did you try setting

```json
"fontFamily": "Fira Code"
```

?

I've run into similar trouble in the past, and in my case it was always about using the wrong font-family name. I just now tested this, this value:


```json
"fontFamily": "FiraCode"
```

or any nonsense value:

```json
"fontFamily": "foobarlas89yu3"
```

gives the strange double spaced font shown in the OP, while:

```json
"fontFamily": "Fira Code"
```

and 

```json
"fontFamily": "fira code"
```

both correctly display Fira Code. I think the caps thing is because my apple filesystem is case insensitive

**Comment by dhirschfeld** [comment]
I *think* I tried all possible ways of specifying the Fira Code font name. I can double check...

**Comment by telamonian** [comment]
> I think I tried all possible ways

I assumed. But the alternative explanation seems to be that your container runtime is leaking font config. Which seems both fantastical and awful

**Comment by dhirschfeld** [comment]
Yeah - just tested all combos from a desktop without the Fira Code font installed and no joy.

**Comment by dhirschfeld** [comment]
In case it matters, it's actually the Fira Code Nerd Font:
https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip

Which (IIUC) is a patched version of Fira Code to include symbols used by the https://starship.rs/ prompt.

> But the alternative explanation seems to be that your container runtime is leaking font config. Which sounds both fantastical and awful!

😆 It seems strange to me that I have to install a font locally. It's a bit of a hassle, but I'm glad found a workaround. If someone figures out a better solution I'm all ears. AFAIK my container is just an ordinary Ubuntu container with Python/JupyterLab installed. The relevant config:
```dockerfile
RUN mkdir -p /usr/share/fonts/truetype/firacode \
    && curl -sSL https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip -o ~/FiraCode.zip \
    && unzip ~/FiraCode.zip -d /usr/share/fonts/truetype/firacode/ \
    && find /usr/share/fonts/truetype/firacode/ -type f -name '*Windows*' -delete \
    && find /usr/share/fonts/truetype/firacode/ -type f -name '*otf' -delete \
    && fc-cache -fv \
    && chown -Rv 1000:1000 /usr/share/fonts/truetype/firacode \
    && rm -f ~/FiraCode.zip
```
