### ISSUE TITLE
Handle compatibility of Lab Extensions

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1011]
## Problem

Currently, if a Lab extension is built against an incompatible version of JupyterLab, it causes the Application to fail to load with an error similar to the one below due to incompatible versions of `Token` objects.

<img width="451" alt="screen shot 2016-09-29 at 1 26 26 pm" src="https://cloud.githubusercontent.com/assets/2096628/18970080/6e77cc0c-8655-11e6-9851-20253a59e906.png">
## Proposal
- Special case JupyterLab and perhaps Phosphor in the JupyterLab builder script to be version-less (and perhaps not include them in the bundle).
- Add the JupyterLab semver data to the manifest file, so we can determine whether it is a compatible extension.  
- Force JupyterLab itself to a `devDependency` or a `dependency` of the extension that is being built, and throw an error if it does not exist.
## Precedent

Both VSCode and Atom have an `"engines"` field in their `package.json` to specify a semver range of compatible versions of the application, and that code is expected to be provided by the environment.

https://code.visualstudio.com/docs/extensionAPI/extension-manifest
http://flight-manual.atom.io/hacking-atom/sections/package-word-count/

**Comment by blink1073** [comment]
The temporary workaround is to manually disable all extensions that are note compatible.

**Comment by blink1073** [comment]
@afshin and I discussed this this morning, here are our thoughts.

- JupyterLab should include `phosphor` as `jupyterlab/lib/phosphor/lib/foo`.
- We make a shim that includes all of the phosphor modules on that path.
- An extension author must include`jupyterlab` as a `dependency` or a `devDependency`, signaling with which versions of JupyterLab it is compatible.  We put this value in the built `.manifest` file.

In this way, we ensure that the extension is fully compatible with the current version of JuptyerLab and that it can move its widgets within the dock panel.  Otherwise, even a patch release difference in Phosphor would have caused `instancef(widget)` to fail.

**Comment by blink1073** [comment]
I looked more into what the original stack trace meant, and it is a symptom of having two distinct application objects, one of which has the document registry provider and the other which does not.

**Comment by blink1073** [comment]
No, the actual issue is that we have two `Token` objects with the same name, as I had original thought.

**Comment by jasongrout** [comment]
> No, the actual issue is that we have two Token objects with the same name, as I had originally thought.

To elaborate (correct me if I'm wrong), the problem is illustrated in the following steps:

* JLab activates plugin A version 1.2.3, which provides a token for A.
* Plugin B requires version 1.2.x of plugin A, but bundles version 1.2.4 of plugin A.
* The versioned loader gives plugin B the 1.2.4 token (since that's the maximal version around).
* The DI container can't find 1.2.4's token, and throws an error.

Some thoughts or ways we could deal with this:

* If the DI container had some constant value that spanned multiple versions of a token (like the string ID), it could dedupe requests for the object. Even better would be to store the version of the token in the DI container, and check it against the semver required by the consumer, so you can warn the user if you are handing a plugin the wrong version of a dependency.
* Have the loader prefer the version of any package that indicates it is loading a token into the DI container. How it notifies the loader is to be determined. This breaks the "max satisfying version" rule, but ensures you get the right token.

**Comment by blink1073** [comment]
I agree with your assessment of the problem.  I think the way around the problem should be on the server side: it has more information than either the DI container or the loader.

**Comment by jasongrout** [comment]
The server may not have knowledge of the plugin. I could be loading a plugin from a CDN on the web, and the server will have no knowledge of it. (We don't support this right now, but it's a natural direction to go...)

**Comment by blink1073** [comment]
Minor point: the token itself is not in the same file as the plugin.

**Comment by jasongrout** [comment]
(Thinking out loud) - essentially the token system now insists that if you request something out of the DI container, you get *exactly* the version you request. However the actual version you request is left up to the versioned loader. Some ways to fix this:

(a) making the version you request exactly what is loaded in the DI container, or 
(b) making the DI container understand semver ranges so you can request one version and possibly get back a different (hopefully compatible) version.
(c) do (b), but without any notion of semver ranges - for example, a string id identifies the object. Notions of compatibility then should be taken care of some other way.

In (a), you'll need (1) a way to know what version of a package is providing a token to the DI container, (2) a way to tell the loader to return that version of the package when a compatible semver range is requested. In our current setup, you can also do (a) by deduping on the server side, which ensures that there is exactly one version of each package from the start. That of course won't work as well if/when we load plugins directly from the web.

**Comment by blink1073** [comment]
I don't like the idea of pushing any semver information into the DI container itself.

Here is what I propose:
1) Have a `jupyterlab-core` that must be compatible with the core system.
2) Break phosphor and jupyterlab up into sub-packages and stop importing single modules.
3) We load plugins by consuming their manifest on the client - the same would apply to those loaded via CDN - and refuse to load ones whose `jupyterlab-core` does not match semver.
4) We prefer modules (which will be packages moving forward with the exception of CodeMirror) that have already been loaded by the loader where there is more than one matching version.
5) As a last line of defense, we allow plugins to fail to load on application startup (or later), with a warning.  Instead of the current `Promise.all()` methods of ensuring all plugins are loaded, we use the approach [here](http://stackoverflow.com/a/31424853).

**Comment by jasongrout** [comment]
> 1) Have a jupyterlab-core that must be compatible with the core system.

So the jupyterlab-core is a semver range specified in something like the "engine" package.json key mentioned earlier, that is checked against the actual jupyter core? What is in the "core" system? Minimally, you need the plugin interface to be the same as what the current jupyterlab requires.

> 2) Break phosphor and jupyterlab up into sub-packages and stop importing single modules.

How does this help?

> 3) We load plugins by consuming their manifest on the client - the same would apply to those loaded via CDN - and refuse to load ones whose jupyterlab-core does not match semver.

Fair enough. Again, minimally all we care about is if the plugin specification interface changes.

> 4) We prefer modules (which will be packages moving forward with the exception of CodeMirror) that have already been loaded by the loader where there is more than one matching version.

So you get the first loaded module that matches your semver range, rather than the max satisfying version? This also introduces problems with deduplication - if plugin A requires version `^1.2.1` of a file, and plugin B requires version `^1.2.2`, and A is loaded first, then we won't dedupe, whereas we would before. Since semver encourages lower bounds on ranges, it still makes sense to do deduping with maxSatisfying.

> 5) As a last line of defense, we allow plugins to fail to load on application startup (or later), with a warning. Instead of the current Promise.all() method of ensuring all plugins are loaded, we use the approach here.

Definitely!

**Comment by jasongrout** [comment]
Another idea is to treat the primary package modules differently than dependencies. Maybe the versioned loader should have this priority:

(a) Find the max satisfying version of the primary package
(b) If no primary package was found, find the max satisfying version of the specific module needed.

**Comment by jasongrout** [comment]
Oh, I think I understand something more from your proposal. Restricting imports to a package entry point essentially makes the versioning package-based instead of module-based, since the version number on the entry file then controls the version number of the entire package. I like that in principle (possibly getting different versions of modules from the same package bothered me), but I'm not sure we should depend on that (though it's probably a useful assumption early on).

**Comment by blink1073** [comment]
The main issue I'm trying to avoid is bringing "part" of a package with your extension and expecting it to function well with another "part" of a package.  
In a normal `node_modules` setup on a user's machine, you'd have the *entire* package at your disposal for deduping, not just the handful of modules you happen to be using.

The key point to having a `jupyter-core` is that it can be a slower-moving part of the application.  I am trying to avoid having an extension that depends only on the `DocumentRegistry` from requiring an update when we change something in the `Terminal` for example.

**Comment by jasongrout** [comment]
Thanks. So which modules would be in `jupyter-core`? Perhaps just the things that are attached to the application object?

Here's something interesting I just saw in the bundle for jupyterlab_widgets. Notice that the version of phosphor that is required has a different semver range for the signaling phosphor module compared to the other ones. It seems to me that they should all be the same: `phosphor@^0.6.1/path/to/module`

```

/** START DEFINE BLOCK for jupyterlab@0.5.0/lib/docregistry/registry.js **/
jupyter.define('jupyterlab@0.5.0/lib/docregistry/registry.js', function (module, exports, __jupyter_require__) {
	// Copyright (c) Jupyter Development Team.
	// Distributed under the terms of the Modified BSD License.
	"use strict";
	var disposable_1 = __jupyter_require__('phosphor@^0.6.1/lib/core/disposable.js');
	var signaling_1 = __jupyter_require__('phosphor@~0.6.1/lib/core/signaling.js');
	var token_1 = __jupyter_require__('phosphor@^0.6.1/lib/core/token.js');
```

**Comment by blink1073** [comment]
I'd say the shell and the document registry belong in core along with some core tokens like the `pathtracker`.  

What you are seeing is intentional but we now see is incorrect behavior of the JupyterLabPlugin.

**Comment by blink1073** [comment]
Putting down some thoughts:
The manifest file should contain the top level semver requirements for the bundle.  
JupyterLab should check that file against its own manifest for compatibility.
The extension builder should call that function when creating the bundle to ensure compatibility at build time.
The "version" of `JupyterLab` will be tied to the Python package, since each submodule will have its own version, and we add that to the manifest as well.

**Comment by blink1073** [comment]
cc @gnestor, the approach in the previous comment would prevent the `CodeMirror` incompatibilities you were seeing.

**Comment by gnestor** [comment]
@blink1073 Nice! Thanks for catching that.

**Comment by blink1073** [comment]
Notes from today's meeting:

Our previous approach was not handling incompatible semver ranges between sibling packages, because it was naively using the maximal satisfying for any constraint.

We proposed the following approach:

- Add a separate Python-based builder on the server that is cached for the currently enabled extensions (would be a no-op on a fresh install with no enabled extensions).
- The builder creates a single de-duplicated bundle from the JupyterLab main bundle and the third party extension bundles, possibly using a SAT solver.
- The builder would refuse to allow duplicate versions of a library that have not been whitelisted as "duplicate friendly".  These might include external libraries such as `d3-*`.
- The builder could replace the semver-ranged `require` paths with the chosen version, meaning that the loader on the client could be semver-unaware.
- Because we are handling de-duplication on the server, we can no longer support dynamic loading of extensions.  They would have to be installed and enabled, then built into a new bundle on the server.  A refresh of the page would pick up the new bundle.

**Comment by jasongrout** [comment]
> Because we are handling de-duplication on the server, we can no longer support dynamic loading of extensions.

I just want to point out that we *can* support dynamic enabling/disabling of extensions, but they would have to be loaded (i.e., bundled) in at the server.

**Comment by jasongrout** [comment]
> I just want to point out that we can support dynamic enabling/disabling of extensions, but they would have to be loaded (i.e., bundled) in at the server.

I mean, we can support not enabling all extensions by default, and then enabling them in the browser  as needed. Disabling extensions is still tricky because of unloading the javascript.

**Comment by sccolbert** [comment]
> I mean, we can support not enabling all extensions by default, and then enabling them in the browser as needed. Disabling extensions is still tricky because of unloading the javascript.

I'd suggest this as a "we'll do this if the need arises". My takeaway from the call is that enabling an extension on the server means it will be activated on lab start.

**Comment by blink1073** [comment]
The activation is handled by the extension using the `autoStart` field of the plugin.  The enable/disable is done via labextension configuration.

**Comment by sccolbert** [comment]
Ah. Gotcha.

**Comment by AbdealiJK** [comment]
Quick note that when doing this the Python builder needs to be made aware of the settings the bundle is going to be working with.
If I want to run 2 `jupyter lab` instances on two different ports with 2 different configs, there should be 2 bundles created.

**Comment by sccolbert** [comment]
@AbdealiJK I think the config (which plugins are loaded) is only thing that matters in this case.

**Comment by blink1073** [comment]
Part of the implementation problem was that the npm algorithm is so tightly coupled to the npm core.   I found this: https://github.com/arifsetiawan/flatten/blob/master/lib/flatten.js, which does part of the work we want, except that it unambiguously uses a new version when two versions are in [conflict](https://github.com/arifsetiawan/flatten/blob/88a317fa35991243ffb629bc6b4dda1709e77261/lib/flatten.js#L101), but we can alter that behavior.

**Comment by blink1073** [comment]
Tracking in #2011.
