### ISSUE TITLE
Can't find the cell that failed in a long notebook

### ISSUE THREAD

**Issue by aiqc** [jupyterlab/jupyterlab#10123]
_Making a few extra issues that tested well in the survey for the new team members that Darian mentioned._

### Problem
When running a long notebook, it is a pain to figure out which cell failed. You have to scroll around until you found it. Especially if you used the "run all above" from the bottom of the notebook, or "run all cells" when viewing the top of the notebook.

---

### Proposed Solution

If cells are executed in a queue with a pass/fail status, then the status indicator could provide the cell id that failed. The status icon could show as an error. Could it somehow link to that cell ID? If so, the UI would have to somehow indicate that it can be clicked on - maybe it would be the same color as the hyperlink text.

![image](https://user-images.githubusercontent.com/74990642/115446783-b4553d80-a1e5-11eb-8458-2b2cc0a57819.png)
![image](https://user-images.githubusercontent.com/74990642/115447382-71e03080-a1e6-11eb-887b-156bfe98b567.png)

---

### Additional context
Survey results:
![image](https://user-images.githubusercontent.com/74990642/115449280-a359fb80-a1e8-11eb-84d9-d06dab0ba500.png)

**Comment by krassowski** [comment]
Previously discussed in #9786, #8714, and #5790.
