### ISSUE TITLE
Fix issues related to performance work

### ISSUE THREAD

**Issue by goanpeca** [jupyterlab/jupyterlab#10130]
## Description

- [x] Horizontal scrollbar (see this in the JupyterLab examples/notebooks/… folder)
- [x] The prompt in the Code Console is in the wrong spot.
- [x] Test with notebooks that have very large text outputs, because they seem *worse* in virtual than in regular rendering.

**Comment by goanpeca** [comment]
@blink1073 shared these issues you found @afshin.

I am working on these fixes. Please use this issue to report any additional problems.

Thanks!

**Comment by ichsan2895** [comment]
> ## Description
> * [ ]  Horizontal scrollbar (see this in the JupyterLab examples/notebooks/… folder)
> * [ ]  The prompt in the Code Console is in the wrong spot.
> * [ ]  Test with notebooks that have very large text outputs, because they seem _worse_ in virtual than in regular rendering.

Hello, I have done performance profiling with large notebook (over 500 cells). Please kindly check this issue for futher information.
https://github.com/jupyterlab/jupyterlab/issues/10213

Hopefully it will help you.

**Comment by fcollonval** [comment]
Closing as all tasks are done
