### ISSUE TITLE
SVG figure can not be shown in jupyterlab 3 when reopeing or refreshing.

### ISSUE THREAD

**Issue by taozuoqiao** [jupyterlab/jupyterlab#10148]
## Description

When I set matplotlib formats to svg and plot a figure inline, the SVG figure can be shown normally. However, after refreshing the brower or reopening jupyterlab, the original SVG figure can not be shown in jupyterlab any more.

However, SVG figure can still be shown when the notebook is opened in vscode or pycharm. 
Whats'more, SVG figures in old notebooks created by jupyterlab 2 can also be shown in jupyterlab 3.

## Reproduce
1. open a notebook in jupyterlab, and run
```python
from IPython.display import set_matplotlib_formats
from matplotlib import pyplot as plt
set_matplotlib_formats("svg")
plt.plot([0,1])
plt.show()
```
The SVG can be shown:
<img src="https://user-images.githubusercontent.com/18346451/115949351-2213a900-a507-11eb-913e-b2e43fa27f0a.png" width="300" height="250">
2. after refreshing the chrome brower or reopening jupyterlab in new tab, SVG figure can not be shown:
<img src="https://user-images.githubusercontent.com/18346451/115949377-5c7d4600-a507-11eb-9a3d-d5d94973134f.png" width="300" height="120">
3. open the same notebook in vscode, SVG figure can be shown directly without re-running:
<img src="https://user-images.githubusercontent.com/18346451/115949393-74ed6080-a507-11eb-9105-78a72890a461.png" width="400" height="400">

## Context

- Operating System and version: Windows 10 20H2, 19042.906
- Browser and version: Chrome, 90.0.4430.85
- JupyterLab version: 3.0.12

**Comment by taozuoqiao** [comment]
I have found solutions from stackoverflow, https://stackoverflow.com/questions/68398033/svg-figures-hidden-in-jupyterlab-after-some-time

**Comment by krassowski** [comment]
This is not how this should behave. I think this is due to a trust issue possibly, https://github.com/jupyterlab/jupyterlab/issues/9765.
