### ISSUE TITLE
Installing labextension doesn't work with namespace packages

### ISSUE THREAD

**Issue by mellesies** [jupyterlab/jupyterlab#10149]
## Description

I'm writing a Widget/JupyterLab extension using `ipywidgets` that's part of a collection of namespace packages. When calling `jupyter labextension develop . --overwrite` linking fails.

## Reproduce
Follow the initial steps from [ipywidgets](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Custom.html#Implementing-the-widget):
1. Run the cookiecutter: `cookiecutter https://github.com/jupyter-widgets/widget-cookiecutter` accepting defaults
2. Modify the package structure:
  -  create a directory `mynamespace`
  - move the folder in `jupyter_widget_example` into it
  - modify `setup.py`:
     - find & replace `find_packages` with `find_namespace_packages`
     - comment out lines 19-20 (the log statements) as these will cause a separate issue
     - line 26: modify the path provided to `get_version(pjoin('mynamespace', name, '_version.py'))`
     - line 36-37: prepend `mynamespace` to the paths
3. Install the package & link with JupyterLab
  - run `pip install -e .` (this should succeed)
  - run `jupyter labextension develop . --overwrite` (this should fail) with the following output
```
setup.py:42: DeprecatedWarning: create_cmdclass is deprecated as of 0.8 and will be removed in 1.0. "
Use `wrap_installers` to handle prebuild steps in cmdclass.
Use `get_data_files` to handle data files.
Use `include_package_data=True` and `MANIFEST.in` for package data.

  cmdclass = create_cmdclass('jsdeps', data_files_spec=data_files_spec)
setup.py:44: DeprecatedWarning: install_npm is deprecated as of 0.8 and will be removed in 1.0. Use `npm_builder` and `wrap_installers`
  install_npm(js_dir, npm=['yarn'], build_cmd='build:prod'), ensure_targets(jstargets),
An error occured.
ModuleNotFoundError: There is not a labextensions at .
See the log file for details:  /var/folders/t5/pkrbz33n6ddbm5d1q4l9fc5h0000gn/T/jupyterlab-debug-x_2u1u5i.log
```

The traceback provided in the log was:
```
Traceback (most recent call last):

  File "/Users/melle/.virtualenvs/thomas-jupyter3/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/Users/melle/.virtualenvs/thomas-jupyter3/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 128, in start
    ans = self.run_task()

  File "/Users/melle/.virtualenvs/thomas-jupyter3/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 199, in run_task
    develop_labextension_py(arg, user=self.user, sys_prefix=self.sys_prefix, labextensions_dir=self.labextensions_dir, logger=self.log, overwrite=self.overwrite,

  File "/Users/melle/.virtualenvs/thomas-jupyter3/lib/python3.8/site-packages/jupyterlab/federated_labextensions.py", line 135, in develop_labextension_py
    m, labexts = _get_labextension_metadata(module)

  File "/Users/melle/.virtualenvs/thomas-jupyter3/lib/python3.8/site-packages/jupyterlab/federated_labextensions.py", line 412, in _get_labextension_metadata
    raise ModuleNotFoundError('There is not a labextensions at {}'.format(module))

ModuleNotFoundError: There is not a labextensions at .

Exiting application: lab
```

Inspection of https://github.com/jupyterlab/jupyterlab/blob/1db6c29c4c52d4aa61ae5823c728a293209857de/jupyterlab/federated_labextensions.py#L401 suggested only 'regular' packages were found when searching for extensions. Inserting the following code (around line 413, just above `raise ModuleNotFoundError('There is not a labextensions at {}'.format(module))`), fixed the issue:
```python
    # Looking for namespace packages
    if m is None:
        from setuptools import find_namespace_packages
        packages = find_namespace_packages(mod_path)

        # Looking for the labextension metadata
        for package in packages:
            try:
                m = importlib.import_module(package)
                if hasattr(m, '_jupyter_labextension_paths') :
                    return m, m._jupyter_labextension_paths()
            except Exception:
                m = None 
```
(see [fork](https://github.com/mellesies/jupyterlab/blob/465e651bb725ba3c559ac126e896ecbaefd3568f/jupyterlab/federated_labextensions.py#L414-L425))

## Expected behavior
I expected the link to complete successfully.

## Context
- Operating System and version: macOS, debian linux
- JupyterLab version: 3.0.14, issue still present in commit 1db6c29c4c52d4aa61ae5823c728a293209857de

**Comment by agoose77** [comment]
I'm going to assume that, given that you authored the PR, this issue can be closed! Thanks for contributing :)
