### ISSUE TITLE
Title Bar Count is Wrong

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#10159]
## Description
Open any number of notebooks and the parenetical says there are 2 more than there really is. As shown below, there are 2 notebooks open, but document title says there are 4.

![image](https://user-images.githubusercontent.com/1813603/116103237-688b1400-a67d-11eb-9797-95c734faa7e8.png)

## Reproduce

Open any number of notebooks.

## Expected behavior

The count to reflect number of open notebooks only

## Context

- Operating System and version: Windows
- Browser and version: Chrome
- JupyterLab version:  850445a3685aecac4c8a0dd942709ad212e248fc

Related: https://github.com/jupyterlab/jupyterlab/pull/10002

CC @jess-x

**Comment by jess-x** [comment]
I could not reproduce this bug, but hopefully #10168 is helpful in fixing it.

**Comment by goanpeca** [comment]
@mlucool could you check if the issue is still present in the latests alpha?

Thanks!

**Comment by mlucool** [comment]
LGTM now. Thanks!
