### ISSUE TITLE
File browser -> new file -> rename

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/jupyterlab#10164]
## Description

When creating a new file from the context menu, we should allow the user to directly rename the file. It works like that for folders, but not for files.

## Reproduce

![filerename](https://user-images.githubusercontent.com/21197331/116248395-2260ae00-a76c-11eb-937b-5726bd36f734.gif)

## Expected behavior

The user should be prompt to rename the file directly after the creation

I am happy to open a PR myself.

**Comment by yash112-lang** [comment]
Do you currently working on this problem @martinRenou and if yes then did you solved this issue?
