### ISSUE TITLE
Improve filebrowser context menu UI

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/jupyterlab#10165]
### Problem

The context menu in the filebrowser is difficult to navigate, there are many items and it's difficult to quickly find the item you want.

![contextmenu](https://user-images.githubusercontent.com/21197331/116248974-a0bd5000-a76c-11eb-96fe-963a863c87af.png)

### Proposed Solution

We could either sort alphabetically (not a big fan of this solution myself), or we could add separators to group items, like vscode does:

![vscode](https://user-images.githubusercontent.com/21197331/116249286-f2fe7100-a76c-11eb-9e4c-3e13b9928ed6.png)

We could do something like:

---
Open
Open With
Open in New Browser Tab

---
Rename
Delete
Cut
Copy
Paste
Copy Shareable Link
Copy Path
Copy Download Link
Duplicate

---
Download

---
Shut Down Kernel

---
New Folder
New File
New Markdown File

**Comment by agoose77** [comment]
In addition / in parallel with this suggestion, perhaps we should have a submenu for some of these commands? For example, as extensions add new file types, it might be better to move them into their own `new file` submenu?

**Comment by krassowski** [comment]
Maybe also group all four "Copy" operations together?
