### ISSUE TITLE
Command Search Bar is too discreet

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1017]
THe search bar looks fine, though when not focused, and with text in it it is difficult to differentiate from normal text. 

While the current user il likely to know that there is a search field, for the casual observer (which is following a tutorial) it might be hard to understand this is a search field. 

![screen shot 2016-10-03 at 14 27 04](https://cloud.githubusercontent.com/assets/335567/19054717/7b718ef2-8975-11e6-9024-605316b8e960.png)

I got caught myself into it where for a few seconds I was "Where the _fabulous_ search field is gone" and lost my train of thought. 

So now because I don't know what I was doing I open this issue.

**Comment by ellisonbg** [comment]
Hmmm, that isn't what the search field looks like in master. Can you pull and rebuild?

**Comment by ellisonbg** [comment]
Opps, nevermind, master got changed while I was away over the weekend. I will work on this one...

**Comment by Deborah-Digges** [comment]
I had worked on removing the blue background for the search box. I could help with improving the Style for the search box. What do you have in mind?

**Comment by ellisonbg** [comment]
Fixed in master.
