### ISSUE TITLE
Jupyterlab or notebook in Archlinux bugs

### ISSUE THREAD

**Issue by Edenharder** [jupyterlab/jupyterlab#10172]
## Description

My OS is Archlinux, I have installed Jupyterlab from Archlinux community.

My problem is, no matter in Jupyterlab or Jupyter notebook, I cannot set it to auto close the bracket, even after purging out every setting files and reinstall them.

Another problem is that, any keystrokes except the arrows do not work if the plugin `axelfahy/jupyterlab-vim` is on.

I have thought that it was a problem of the browser firefox, then I tested chromium, same problems were still there.

## Reproduce

1. Install Jupyterlab from [Archlinux community](https://archlinux.org/packages/community/any/jupyterlab/)
2. Run Jupyterlab and open an `ipynb` file.
3. Type `(`, it does not auto close the bracket.
4. Set the user path for extensions and install the extension [`axelfahy/jupyterlab-vim` ](https://github.com/axelfahy/jupyterlab-vim)
5. Re-run Jupyterlab and open an `ipynb` file.
6. Any keystrokes except the arrows do not work if the plugin `axelfahy/jupyterlab-vim` is on.

Since I have not install Jupyterlab within Conda, I cannot follow the guideline to diagnose it.

## Expected behavior

1. Autoclose bracket.
2. Keystrokes work when the plugin `axelfahy/jupyterlab-vim` is on.

## Context

- Operating System and version: Archlinux x86_64 Linux 5.10.32-1-lts
- Browser and version: Firefox Developer Edition 89.0b4 
- JupyterLab version: JupyterLab 3.0.14

<details><summary>Troubleshoot Output</summary>
<pre>
~ ❯ jupyter troubleshoot
/usr/bin/python: No module named pip
$PATH:
        /home/x/.local/bin
        /usr/local/bin
        /usr/bin
        /bin
        /usr/local/sbin
        /usr/bin/site_perl
        /usr/bin/vendor_perl
        /usr/bin/core_perl

sys.path:
        /home/x/.local/bin
        /usr/lib/python39.zip
        /usr/lib/python3.9
        /usr/lib/python3.9/lib-dynload
        /home/x/.local/lib/python3.9/site-packages
        /usr/lib/python3.9/site-packages

sys.executable:
        /usr/bin/python

sys.version:
        3.9.4 (default, Apr 20 2021, 15:51:38) 
        [GCC 10.2.0]

platform.platform():
        Linux-5.10.32-1-lts-x86_64-with-glibc2.33

which -a jupyter:
        /home/x/.local/bin/jupyter
        /usr/bin/jupyter
        /bin/jupyter
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
jupyter lab --debug                                       
[D 2021-04-28 19:30:58.056 ServerApp] Searching ['/home/x/ownCloud/Notes/ipynb', '/home/x/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2021-04-28 19:30:58.056 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2021-04-28 19:30:58.057 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2021-04-28 19:30:58.057 ServerApp] Looking for jupyter_config in /usr/etc/jupyter
[D 2021-04-28 19:30:58.057 ServerApp] Looking for jupyter_config in /home/x/.jupyter
[D 2021-04-28 19:30:58.057 ServerApp] Looking for jupyter_config in /home/x/ownCloud/Notes/ipynb
[D 2021-04-28 19:30:58.059 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2021-04-28 19:30:58.060 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2021-04-28 19:30:58.060 ServerApp] Looking for jupyter_server_config in /usr/etc/jupyter
[D 2021-04-28 19:30:58.060 ServerApp] Looking for jupyter_server_config in /home/x/.jupyter
[D 2021-04-28 19:30:58.060 ServerApp] Looking for jupyter_server_config in /home/x/ownCloud/Notes/ipynb
[D 2021-04-28 19:30:58.064 ServerApp] Paths used for configuration of jupyter_server_config: 
        /etc/jupyter/jupyter_server_config.d/jupyterlab.json
        /etc/jupyter/jupyter_server_config.json
[D 2021-04-28 19:30:58.065 ServerApp] Paths used for configuration of jupyter_server_config: 
        /usr/local/etc/jupyter/jupyter_server_config.json
[D 2021-04-28 19:30:58.066 ServerApp] Paths used for configuration of jupyter_server_config: 
        /usr/etc/jupyter/jupyter_server_config.json
[D 2021-04-28 19:30:58.068 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/x/.jupyter/jupyter_server_config.json
[I 2021-04-28 19:30:58.086 ServerApp] jupyterlab | extension was successfully linked.
[D 2021-04-28 19:30:58.087 ServerApp] Raising open file limit: soft 1024->4096; hard 524288->524288
[I 2021-04-28 19:30:58.117 LabApp] JupyterLab extension loaded from /usr/lib/python3.9/site-packages/jupyterlab
[I 2021-04-28 19:30:58.118 LabApp] JupyterLab application directory is /home/x/.local/share/jupyter/lab
[I 2021-04-28 19:30:58.124 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-04-28 19:30:58.129 ServerApp] Serving notebooks from local directory: /home/x/ownCloud/Notes/ipynb
[I 2021-04-28 19:30:58.130 ServerApp] Jupyter Server 1.6.4 is running at:
[I 2021-04-28 19:30:58.130 ServerApp] http://localhost:8888/lab?token=94d3f9a8df7719aae97d26b838237668897d2029ef0fefe1
[I 2021-04-28 19:30:58.130 ServerApp]     http://127.0.0.1:8888/lab?token=94d3f9a8df7719aae97d26b838237668897d2029ef0fefe1
[I 2021-04-28 19:30:58.130 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-04-28 19:30:58.356 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/x/.local/share/jupyter/runtime/jpserver-36421-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=94d3f9a8df7719aae97d26b838237668897d2029ef0fefe1
        http://127.0.0.1:8888/lab?token=94d3f9a8df7719aae97d26b838237668897d2029ef0fefe1
[D 2021-04-28 19:30:59.938 ServerApp] Accepting token-authenticated connection from 127.0.0.1
[D 2021-04-28 19:30:59.943 ServerApp] Paths used for configuration of page_config: 
        /etc/jupyter/labconfig/page_config.json
[D 2021-04-28 19:30:59.945 ServerApp] Paths used for configuration of page_config: 
        /usr/local/etc/jupyter/labconfig/page_config.json
[D 2021-04-28 19:30:59.946 ServerApp] Paths used for configuration of page_config: 
        /usr/etc/jupyter/labconfig/page_config.json
[D 2021-04-28 19:30:59.946 ServerApp] Paths used for configuration of page_config: 
        /home/x/.jupyter/labconfig/page_config.json
[D 2021-04-28 19:30:59.950 LabApp] Using contents: services/contents
[D 2021-04-28 19:30:59.959 LabApp] 200 GET /lab?token=94d3f9a8df7719aae97d26b838237668897d2029ef0fefe1 (127.0.0.1) 20.96ms
[D 2021-04-28 19:31:00.139 ServerApp] Path main.95e168bb4d247926af72.js served from /home/x/.local/share/jupyter/lab/static/main.95e168bb4d247926af72.js
[D 2021-04-28 19:31:00.141 ServerApp] 200 GET /static/lab/main.95e168bb4d247926af72.js?v=95e168bb4d247926af72 (127.0.0.1) 3.39ms
[D 2021-04-28 19:31:00.361 ServerApp] Path 8173.b3cdc88dcb401955d50e.js served from /home/x/.local/share/jupyter/lab/static/8173.b3cdc88dcb401955d50e.js
[D 2021-04-28 19:31:00.362 ServerApp] 200 GET /static/lab/8173.b3cdc88dcb401955d50e.js?v=b3cdc88dcb401955d50e (127.0.0.1) 1.48ms
[D 2021-04-28 19:31:00.370 ServerApp] Path 6700.e6662c91dc5086ac3113.js served from /home/x/.local/share/jupyter/lab/static/6700.e6662c91dc5086ac3113.js
[D 2021-04-28 19:31:00.372 ServerApp] 200 GET /static/lab/6700.e6662c91dc5086ac3113.js?v=e6662c91dc5086ac3113 (127.0.0.1) 3.69ms
[D 2021-04-28 19:31:04.763 ServerApp] Paths used for configuration of default_setting_overrides: 
        /home/x/.jupyter/labconfig/default_setting_overrides.json
[D 2021-04-28 19:31:04.808 LabApp] 200 GET /lab/api/settings?1619631064748 (127.0.0.1) 48.68ms
[D 2021-04-28 19:31:04.843 LabApp] > /usr/bin/npm pack @axlair/jupyterlab_vim@0.13.4
-[D 2021-04-28 19:31:05.266 ServerApp] Accepting token-authenticated connection from 127.0.0.1
[D 2021-04-28 19:31:05.267 LabApp] 204 PUT /lab/api/workspaces/default?1619631065262 (127.0.0.1) 1.75ms
[D 2021-04-28 19:31:05.281 ServerApp] Serving kernel resource from: /usr/share/jupyter/kernels/python3
[D 2021-04-28 19:31:05.282 ServerApp] 200 GET /kernelspecs/python3/logo-64x64.png (127.0.0.1) 2.22ms
\[D 2021-04-28 19:31:05.358 ServerApp] Accepting token-authenticated connection from 127.0.0.1
[D 2021-04-28 19:31:05.365 ServerApp] 200 GET /api/contents?content=1&1619631065308 (127.0.0.1) 7.22ms
|[D 2021-04-28 19:31:05.470 LabApp] npm notice 
    npm notice 📦  @axlair/jupyterlab_vim@0.13.4
    npm notice === Tarball Contents === 
    npm notice 2.2kB  History.md     
    npm notice 1.1kB  LICENSE        
    npm notice 6.4kB  README.md      
    npm notice 210B   lib/index.d.ts 
    npm notice 22.1kB lib/index.js   
    npm notice 2.5kB  package.json   
    npm notice 0B     style/index.css
    npm notice === Tarball Details === 
    npm notice name:          @axlair/jupyterlab_vim                  
    npm notice version:       0.13.4                                  
    npm notice filename:      @axlair/jupyterlab_vim-0.13.4.tgz       
    npm notice package size:  8.0 kB                                  
    npm notice unpacked size: 34.4 kB                                 
    npm notice shasum:        5551c63016a87ebcb6814cf288a47c7dbb01d472
    npm notice integrity:     sha512-o4XmIBDp9QUK7[...]sUjsKraM7gD8A==
    npm notice total files:   7                                       
    npm notice 
    axlair-jupyterlab_vim-0.13.4.tgz
[D 2021-04-28 19:31:14.149 ServerApp] activity on d4e263b1-c720-4220-83f7-4d3999ef4fc4: status (idle)
[D 2021-04-28 19:31:14.150 ServerApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.3', 'implementation': 'ipython', 'implementation_version': '7.22.0', 'language_info': {'name': 'python', 'version': '3.9.4', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': "Python 3.9.4 (default, Apr 20 2021, 15:51:38) \nType 'copyright', 'credits' or 'license' for more information\nIPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.\n", 'help_links': [{'text': 'Python Reference', 'url': 'https://docs.python.org/3.9'}, {'text': 'IPython Reference', 'url': 'https://ipython.org/documentation.html'}, {'text': 'NumPy Reference', 'url': 'https://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy Reference', 'url': 'https://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib Reference', 'url': 'https://matplotlib.org/contents.html'}, {'text': 'SymPy Reference', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas Reference', 'url': 'https://pandas.pydata.org/pandas-docs/stable/'}]}
[D 2021-04-28 19:31:14.150 ServerApp] 101 GET /api/kernels/d4e263b1-c720-4220-83f7-4d3999ef4fc4/channels?session_id=7d3fa825-c29b-4fb7-b341-d1021d776713 (127.0.0.1) 428.13ms
[D 2021-04-28 19:31:14.151 ServerApp] Opening websocket /api/kernels/d4e263b1-c720-4220-83f7-4d3999ef4fc4/channels
[D 2021-04-28 19:31:14.151 ServerApp] Getting buffer for d4e263b1-c720-4220-83f7-4d3999ef4fc4
[D 2021-04-28 19:31:14.151 ServerApp] Connecting to: tcp://127.0.0.1:58907
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Some cookies are misusing the recommended “SameSite“ attribute 168
Starting application in workspace: "default" index.js:72:16
Starting WebSocket: ws://localhost:8888/api/kernels/91101bbf-4b4d-47a2-b832-67391022b598 default.js:65:20
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at about:blank. (Reason: CORS request not http).

downloadable font: failed to start download (font-family: "MathJax_Blank" style:normal weight:400 stretch:100 src index:0): bad URI or cross-site access not allowed source: about:blank
Starting WebSocket: ws://localhost:8888/api/kernels/91101bbf-4b4d-47a2-b832-67391022b598 default.js:65:20
Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/select/src/components/omnibar/_omnibar.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/node_modules/@blueprintjs/core/src/common/_react-transition.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/lib/css/blueprint.css

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/node_modules/@blueprintjs/core/src/common/_colors.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/_reset.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/node_modules/@blueprintjs/core/src/common/_variables.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/common/_mixins.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/select/src/components/select/_select.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/common/_variables.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/select/src/components/select/_multi-select.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/common/_colors.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/select/lib/css/blueprint-select.css

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/common/_color-aliases.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/_typography.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/accessibility/_focus-states.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/alert/_alert.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/breadcrumbs/_breadcrumbs.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/button/_button.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/common/_flex.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/button/_common.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/node_modules/@blueprintjs/icons/src/_icons.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/button/_button-group.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/callout/_callout.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/card/_card.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/collapse/_collapse.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/context-menu/_context-menu.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/divider/_divider.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/dialog/_dialog.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/common/_react-transition.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/dialog/_multistep-dialog.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/drawer/_drawer.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/editable-text/_editable-text.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/forms/_common.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/forms/_control-group.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/forms/_controls.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/forms/_file-input.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/forms/_form-group.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/forms/_input-group.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/forms/_input.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/forms/_label.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/forms/_numeric-input.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/forms/_index.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/html-select/_html-select.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/html-select/_common.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/node_modules/@blueprintjs/icons/src/generated/_icon-variables.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/html-table/_html-table.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/hotkeys/_hotkeys.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/icon/_icon.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/menu/_submenu.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/menu/_common.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/menu/_menu.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/navbar/_navbar.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/non-ideal-state/_non-ideal-state.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/overflow-list/_overflow-list.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/overlay/_overlay.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/panel-stack/_panel-stack.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/node_modules/@blueprintjs/core/src/common/_react-transition.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/panel-stack2/_panel-stack2.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/popover/_popover.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/popover/_common.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/portal/_portal.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/progress-bar/_progress-bar.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/skeleton/_skeleton.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/skeleton/_common.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/slider/_slider.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/slider/_common.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/spinner/_spinner.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/tabs/_tabs.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/tag/_tag.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/tag/_common.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/tag-input/_tag-input.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/toast/_toast.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/tooltip/_tooltip.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/tooltip/_common.scss

Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: webpack://./node_modules/@blueprintjs/core/src/components/tree/_tree.scss
</pre>
</details>

**Comment by Edenharder** [comment]
Finally, I find out the reason. It's a problem with my input method. Everything works fine if I just switch to the normal input method.

**Comment by telamonian** [comment]
@Edenharder Great that you figured out the problem.

> It's a problem with my input method. Everything works fine if I just switch to the normal input method.

Could you please add a few more details about what you mean by "input method" and "normal input method"? Just in case anyone else runs into similar trouble.

**Comment by Edenharder** [comment]
@telamonian I will try to explain. I have used `ibus-rime` for English with some special symbols. As it turns out, 
1. in Jupyterlab, brackets do not auto complete;
2. the extension `axelfahy/jupyterlab-vim` does not work;
Besides, the `Mathematica notebook` is also affected. For example, the indication of completion does not appear.

If I change back to the normal English input method in `ibus`, then everything works fine.

**Comment by telamonian** [comment]
If I understand correctly, the OP was using a piece of specialty software [`ibus-rime`](https://github.com/rime/ibus-rime) to input Chinese characters by converting sequences of keystrokes made using a "standard" Roman keyboard.

If this is an ongoing issue for other users of Chinese input, it would be nice to know what the actual problem was here. Some guesses:

- `ibus` (the part of `ibus-rime` that actually handles the input) is screwing up `onkeydown` (and similar events) listeners, since different physical keys are actually getting pressed than expected
- the Chinese characters in this case were not unicode

**Comment by Edenharder** [comment]
@telamonian Thank you for the explanation. In fact, I use `ibus-rime` with the scheme [`international latin by polyhedron`](https://github.com/biopolyhedron/rime-latin-international) to input some special characters like `α, β`. To input those characters which are not on the keyboard, we have to use combination of keys, like `;gra` for `α`.
