### ISSUE TITLE
Markdown details no longer works in 3.x but worked in 2.x

### ISSUE THREAD

**Issue by afonit** [jupyterlab/jupyterlab#10171]
In `2.x` this would work:
```python
<details>
  <summary>Click to get a detailed explanation.</summary>
  
  ## Selecting Offsets
  1. something
    * something 1
    * something 2
        * something 2.1
    |pre-offset|post-offset|formula|
    |--|--|--|
    |-1|1|1-(-1)|
    |-2|2|2-(-2)|
    |-3|3|3-(-3)|
    |-4|4|4-(-4)|
    |-5|5|5-(-5)|
    ...
  2. something else
     * something else 1
    |pre-offset|post-offset|formula|
    |--|--|--|
    |-14|3|3-(-14)|
    |-15|4|4-(-15)|
    |-16|5|5-(-16)|
    |-17|6|6-(-17)|
    |-18|7|7-(-18)|
    ...
  
</details>
```

and would look like this:
![image](https://user-images.githubusercontent.com/1798497/116444694-feac6f00-a822-11eb-965e-7ae8ed85fd54.png)

However, after upgrading to `3.x` (I am on 3.0.14), it now does not render and looks like this:
![image](https://user-images.githubusercontent.com/1798497/116444757-108e1200-a823-11eb-88e2-f240aa4a84ea.png)

**Comment by afonit** [comment]
_Note:_ @krassowska  pointed out that `3.x` jupyterlab does render properly if there is no indentation in the markdown:

```
<details><summary>Click to get a detailed explanation.</summary>



## Selecting Offsets
1. something
* something 1
* something 2
    * something 2.1
|pre-offset|post-offset|formula|
|--|--|--|
|-1|1|1-(-1)|
|-2|2|2-(-2)|
|-3|3|3-(-3)|
|-4|4|4-(-4)|
|-5|5|5-(-5)|
...
2. something else
 * something else 1
|pre-offset|post-offset|formula|
|--|--|--|
|-14|3|3-(-14)|
|-15|4|4-(-15)|
|-16|5|5-(-16)|
|-17|6|6-(-17)|
|-18|7|7-(-18)|
...
  
</details>
```

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/details-tag-missing-disclosure-triangle/9152/2

**Comment by krassowski** [comment]
We could add a test case here:
https://github.com/jupyterlab/jupyterlab/blob/f0790b3ffd187b7dc923156b8ae227855abecefb/packages/rendermime/test/factories.spec.ts#L227

And markdown rendering logic is mostly delegated to marked.js:

https://github.com/jupyterlab/jupyterlab/blob/f0790b3ffd187b7dc923156b8ae227855abecefb/packages/rendermime/src/renderers.ts#L626-L637

And there is already an open issue in marked.js on this: https://github.com/markedjs/marked/issues/2018; this is a regression in 2.x line (to which we upgraded in JupyterLab 3).

**Comment by krassowski** [comment]
Also, upon consulting https://github.com/markedjs/marked/issues/2018 it is indeed sufficient to remove whitespaces in empty lines to get it working:

```markdown
<details>
  <summary>Click to get a detailed explanation. (See no spaces in line below)</summary>

  ## Selecting Offsets
  1. something
    * something 1
    * something 2
        * something 2.1
    |pre-offset|post-offset|formula|
    |--|--|--|
    |-1|1|1-(-1)|
    |-2|2|2-(-2)|
    |-3|3|3-(-3)|
    |-4|4|4-(-4)|
    |-5|5|5-(-5)|
    ...
  2. something else
     * something else 1
    |pre-offset|post-offset|formula|
    |--|--|--|
    |-14|3|3-(-14)|
    |-15|4|4-(-15)|
    |-16|5|5-(-16)|
    |-17|6|6-(-17)|
    |-18|7|7-(-18)|
    ...(See no spaces in line below)

</details>
```
