### ISSUE TITLE
cannot start jupyter lab session anymore after accidental file move of running notebook

### ISSUE THREAD

**Issue by ReneHamburger1993** [jupyterlab/jupyterlab#10183]
## Description

jupyter lab now went to `http://localhost:8888/lab/workspaces/auto-G?reset` looping over characters from a to ... (going on a while)
I tried to start it via `jupyter lab` from the same path where I started when it broke.
Even stopping the session and restarting it does not help.
Even trying out a different python enviroment.
Though this must be something with state files reloaded from previous session I guess?

## Reproduce

I had a runing jupyter lab session with several open notebooks and kernels.
I accidently moved a folder containing *running* notebooks to a another folder via the GUI.
I undo this via file explorer (LINUX).
I reloaded the jupyter browser page that was aware of the first uninteded moving of files

## Expected behavior

Just reload the workspace or be able to start from a clean workspace..

## Context

- Operating System and version:
Linux RHEL 7.8

- Browser and version:
Firefox: 78.9
- JupyterLab version:
For both python env 3.6.3 and Python env 3.8.3
jupyter-client           6.1.11
jupyter-core             4.7.0
jupyter-server           1.2.1
jupyterlab               3.0.4
jupyterlab-pygments      0.1.2
jupyterlab-server        2.1.2

**Comment by ReneHamburger1993** [comment]
**fixed by restarting Firefox**

**Comment by adaaaaaa** [comment]
i have a similar [problem](https://github.com/jupyterlab/jupyterlab/issues/10261)...
