### ISSUE TITLE
Remember/restore sidebar width

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10180]
### Problem

* I'm always frustrated when I adjust the size of the sidebar but it is lost after refreshing the JupyterLab/window/opening it again
* I would like it if remembered it width because it saves time and gives a smoother UX

### Proposed Solution

Maybe restoring relative sizes as experimented in https://github.com/jupyterlab/jupyterlab/pull/9292 could help here? Or maybe there is a simpler way to implement this? Like, layout restorer know how to restore the main are widget sizes somehow so it should be possible for the sidebar too.

Once ready, we could check with authors of extensions who modify the sidebar width that they are aware of the change/it i is not breaking for them - see https://github.com/jupyterlab/jupyterlab/issues/9269.

### Additional context

It was annoying me about once a week but not enough to open an issue, but today I saw someone else ask about it at [SO](https://stackoverflow.com/questions/67343257/how-do-i-save-jupyterlabs-sidebar-width-or-set-the-default-width) so here we are.

![sidebar-width-not-remembered](https://user-images.githubusercontent.com/5832902/116775369-a1026780-aa5a-11eb-8325-0f0b59710a16.gif)

**Comment by goanpeca** [comment]
I feel your pain!

Thanks for opening this issue

**Comment by alone-86** [comment]
I really hope this problem can be solved soon.

**Comment by telamonian** [comment]
On the plus side, we now restore the open/close state for both left/right sidebars. But yeah, this is a longstanding issue that would be nice to fix
