### ISSUE TITLE
UI says "No kernel" while I definitively have one

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1018]
![screen shot 2016-10-03 at 14 31 00](https://cloud.githubusercontent.com/assets/335567/19054940/6e6389b2-8976-11e6-8122-9acdf8f10e43.png)

So the initial kernel store in the notebook might have not existed, so I "Switched kernel" and not it's still showing "No kernels".

**Comment by ellisonbg** [comment]
Any hints on how can this be reproduced?

**Comment by Carreau** [comment]
> Any hints on how can this be reproduced?

No not really, that just reliably do it on my machine with a specific notebook, that has nothing different from another one. 

Here is the notebook medatata kernelspec:
```
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python 3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }

```

Which definitively exists.

**Comment by blink1073** [comment]
This only happens with the one notebook?

**Comment by blink1073** [comment]
I tried replacing the metadata of one of my notebooks with the above and I get the expected console log: "No exact match found for python3, using kernel python3 that matches language=python", and it starts my `python3` kernel.  Not sure why it didn't print it with a space in the name off the top of my head.

**Comment by Carreau** [comment]
> This only happens with the one notebook?

No I've seen it with other. It's just this one is currently the one where I can reproduce it.

**Comment by Carreau** [comment]
So I can still reliably reproduce that,:

```
    "python 3": {
      "resource_dir": "/usr/local/share/jupyter/kernels/python 3",
      "spec": {
        "language": "python",
        "env": {
          "DYLD_FALLBACK_LIBRARY_PATH": "/Users/bussonniermatthias/anaconda/pkgs/icu-54.1-0/lib:/Users/bussonniermatthias/anaconda/pkgs/zlib-1.2.8-3/lib"
        },
        "display_name": "Python 3",
        "argv": [
          "/Users/bussonniermatthias/anaconda/bin/python",
          "-m",
          "ipykernel",
          "-f",
          "{connection_file}"
        ]
      }
    },
```

One thing I don't get is that the classic notebook seem seem  to never trigger the server get handler to `kernelspec/<whatever>`

**Comment by Carreau** [comment]
i'm going to assume the space in "python 3" is not handled correctly everywhere. If it's that we should : 1) have jupyter client raise warning that these are not valid kspecs. and 2) still try to handle that correctly in our code.

**Comment by Carreau** [comment]
@blink1073 Sorry for the meeting this morning, my connection keeps shutting down every 30-60 seconds. No clue why, but it doesn't surprise me. Getting tough to do anything done since then.

**Comment by blink1073** [comment]
Aha!  This is related to https://github.com/jupyterlab/jupyterlab/issues/1108.  I realize the problem now.  We are url encoding the name of the kernel spec in `jupyterlab/services`, but the server is not using `url_unescape` on the result.

**Comment by blink1073** [comment]
We can work around this by caching the full set of kernel specs once and then looking up those values by name.

**Comment by blink1073** [comment]
(Which is actually a much cheaper operation in the long run).

**Comment by blink1073** [comment]
@Carreau, in the mean time, if you change your folder name to `python_3`, it will work.

**Comment by Carreau** [comment]
> @Carreau, in the mean time, if you change your folder name to python_3, it will work.

Thanks !  Kernelspec names should be limited to `[-\w.]+` right ? Maybe we need to be a bit stricter on jupyter_core ? @minrk  ?

**Comment by minrk** [comment]
Yeah, we should be strict in jupyter-client that kernelspec names should be url-safe (i.e. `urlescape(name) == name`

**Comment by minrk** [comment]
https://github.com/jupyter/jupyter_client/issues/221 validates names with a strict regex. We could also directly check `url_quote(name) == name` as the requirement, if we wanted to define it that way.
