### ISSUE TITLE
Right sidebar does not get restored when it has only TOC in there

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10195]
## Description

Follow-up on https://github.com/jupyterlab/jupyterlab/issues/10180, based on @telamonian's note:

> On the plus side, we now restore the open/close state for both left/right sidebars. But yeah, this is a longstanding issue that would be nice to fix

Do we? If only the table of contents is in the right sidebar, it does not work for me. I was not aware of this before as I only have TOC in my right area and was always annoyed it gets collapsed on refresh.

## Reproduce

![toc-is-not-restored](https://user-images.githubusercontent.com/5832902/117172676-ee1c6b80-adc3-11eb-9381-8d959a04ad4d.gif)

It seems this is an issue specifically with TOC, as property inspector does work:

![property-inspector-gets-restored](https://user-images.githubusercontent.com/5832902/117172735-fc6a8780-adc3-11eb-9d02-4eb957d8810f.gif)

## Expected behavior

Should get restored too.

## Context

- Browser and version: Chrome
- JupyterLab version: 3.0.14 / master

**Comment by afshin** [comment]
After some investigation: this bug is unrelated to #9590. It is a side-effect of the logic that allows a user to override the original sidebar.
