### ISSUE TITLE
Allow to use arrows to switch focus of buttons in dialogs

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10194]
### Problem

* I would like it if the buttons in dialog windows were focusable using arrows because I sometimes use arrows for navigation instead of tab/shift tab.
* Currently using arrows does not work:

![dialog](https://user-images.githubusercontent.com/5832902/117156202-5c0d6680-adb5-11eb-835e-cc5ebe5ede1d.gif)

### Proposed Solution

When a dialog with buttons is open and one of its buttons are focused:
- pressing left arrow key should act like <kbd>shift</kbd> + <kbd>tab</kbd>
- pressing right arrow key should act like <kbd>tab</kbd>

### Additional context

Other projects support arrows navigation on par with tab navigation:

Gedit:

![gedit-keys](https://user-images.githubusercontent.com/5832902/117156299-6e87a000-adb5-11eb-86ff-a5a961d90d79.gif)

PyCharm:

![pycharm-keys](https://user-images.githubusercontent.com/5832902/117156306-721b2700-adb5-11eb-87b4-5c8079f851ea.gif)

**Comment by jahn96** [comment]
Is there anyone working on this?

**Comment by krassowski** [comment]
I'm not, so I think it's up for grabs

**Comment by jahn96** [comment]
I see. I will take a stab at this!

**Comment by krassowski** [comment]
Implemented in #10349 :tada: . Thank you @jahn96.
