### ISSUE TITLE
Refine styling of JupyterLab dialog boxes

### ISSUE THREAD

**Issue by cameronoelsen** [jupyterlab/jupyterlab#1020]
While revisiting the dialog boxes, I found that there were some tweaks and fixes that should be made just to polish them in regards to design. Here are the before and afters of the two dialog boxes that JupyterLab current has:
### Create New Text File Dialog

Before:
![screen shot 2016-10-03 at 2 48 52 pm](https://cloud.githubusercontent.com/assets/6437976/19055440/ca35483c-8978-11e6-8791-6072bc90825d.png)

After:
![screen shot 2016-10-03 at 2 48 46 pm](https://cloud.githubusercontent.com/assets/6437976/19055449/d20e71a0-8978-11e6-8ec5-c5379d369105.png)
### Create New Notebook Dialog

Before:
![screen shot 2016-10-03 at 2 48 54 pm](https://cloud.githubusercontent.com/assets/6437976/19055478/f7ee1010-8978-11e6-883e-7a8d2de1a6de.png)

After:
![screen shot 2016-10-03 at 2 48 49 pm](https://cloud.githubusercontent.com/assets/6437976/19055484/fe70450c-8978-11e6-950e-d45500d6328f.png)

Before making the specification for this, I wanted to post and get feedback. I think these refinements help a lot with the text hierarchy and help to make it clear what the dialog's header, body and footer are.

**Comment by sccolbert** [comment]
I think dialog buttons should be right-aligned ala Windows and Android.

**Comment by cameronoelsen** [comment]
@sccolbert This is what is looks like with the right alignment for both:

![new_text_right](https://cloud.githubusercontent.com/assets/6437976/19130062/8b6d3ae2-8afe-11e6-9292-e8b61d9283f8.png)

![new_notebook_right](https://cloud.githubusercontent.com/assets/6437976/19130065/8ec4e014-8afe-11e6-80dc-1c3091f0b853.png)

Thought it was a little funky looking but worth getting feedback from everyone else!

**Comment by sccolbert** [comment]
I definitely prefer the right-aligned. But I work on Windows and use an Android :)

**Comment by cameronoelsen** [comment]
Yeah looking around it looks like right-aligned will probably be the "right" way to go about it, besides that you like the changes @sccolbert? I can make a spec for those quick changes whenever you guys get a sec to tweak!

**Comment by sccolbert** [comment]
Yep. I'm :+1: on the other changes.

**Comment by blink1073** [comment]
I am 👍 overall, and also prefer the buttons to lean forward (align right).

**Comment by cameronoelsen** [comment]
### Here is the updated spacing spec for the New Notebook Dialog:
![new_notebook](https://cloud.githubusercontent.com/assets/6437976/19132131/0c5c1abc-8b07-11e6-9c08-e2882a7110a8.png)

### As well as for the New Text Document Dialog:
![new_text](https://cloud.githubusercontent.com/assets/6437976/19132371/f8bc8c70-8b07-11e6-978d-020553fa2228.png)

Also, here are the changes to elements within the dialog:
#### Dialog Header: 
**Font Size:** 20px
**Font Weight:** 300

#### Dialog Buttons:
I think we should, instead of setting the min-width and min-height within the button, just have a 24px padding on both sides (left and right) of the type inside the buttons and keep the padding/spacing on top and bottom of the type the same.

**Font Size:** 12px

**Comment by vidartf** [comment]
If you want to go very advanced, you could have a look at what Qt does: they lay out buttons depending on the user's platform :) http://doc.qt.io/qt-4.8/qdialogbuttonbox.html#details

**Comment by ellisonbg** [comment]
+1 on the right aligned buttons. A few other comments:

* We are now using CSS variables to style everything. This has cleaned up the design and made it much more consistent. However, the dialogs are one thing we hadn't converted to start using the CSS variables. Link:

https://github.com/jupyter/jupyterlab/blob/master/src/default-theme/variables.css

Some that will be relevant for the dialogs:

* `--jp-ui-font-size` 
* `--jp-ui-font-color`
* The layout and brand colors...

* We are also starting to size things a bit smaller. We haven't made a final decision, but think we will want to create a CSS variable for the button height and width...

@cameronoelsen we can go over some of this tomorrow on our call...

**Comment by Deborah-Digges** [comment]
I'd love to help out with this! Is someone already working on this piece?

**Comment by blink1073** [comment]
As far as I know we are still waiting on a final design spec, but by all means after that.

**Comment by Deborah-Digges** [comment]
Awesome 👍
