### ISSUE TITLE
'ExtensionManager' object has no attribute '_extensions' when starting JupyterLab

### ISSUE THREAD

**Issue by zhzhang2018** [jupyterlab/jupyterlab#10228]
## Description
I recently upgraded my OS to Big Sur. As a result, Python 3.6 doesn't work anymore, and I believe I followed all the right procedures to install Python 3.9.5, followed by new installations of JupyterLab and all other packages I've been using. 

The error shows up when I try to run Jupyter Lab: 

```
$ jupyter lab

[I 2021-05-10 17:45:40.849 ServerApp] jupyterlab | extension was successfully linked.

[W 2021-05-10 17:45:41.200 ServerApp] 'ExtensionManager' object has no attribute '_extensions'

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/jupyter-lab", line 8, in <module>

    sys.exit(main())

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 518, in launch_instance

    serverapp = cls.initialize_server(argv=args)

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 488, in initialize_server

    serverapp.initialize(

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/traitlets/config/application.py", line 87, in inner

    return method(app, *args, **kwargs)

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 1855, in initialize

    point = self.extension_manager.extension_points[starter_extension]

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 290, in extension_points

    extensions = self.extensions

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nbclassic/nbserver.py", line 80, in extensions

    nb = self._extensions.get("nbclassic")

AttributeError: 'ExtensionManager' object has no attribute '_extensions'
```
For some reason, I wasn't able to find this exact error anywhere on Google. I might try changing `jupyter_notebook_config.json` later.

## Reproduce

I guess it'll be hard to describe the exact steps to reproduce, because reinstalling Python and redirecting the terminal command to the right file took a lot of trials and errors for me. Here's a rough timeline:

1. Upgrade OS into Big Sur and find out that python 3.6 won't work anymore with an error message:
dyld: Library not loaded: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python
  Reason: image not found
2. Try to install newest package using Homebrew, which ended up being in `usr/local/bin` instead of `Library/Frameworks/...`, and then being confused as to why Jupyter is still using the corrupted 3.6;
3. Install the newest package from python.org, which installed Python 3.9 in `Library/Frameworks/...` successfully;
4. Modify the paths from `open ~/.bash_profile` to remove the old 3.6;
5. Install Jupyter, Jupyterlab, iPython etc., using the newly-installed pip3. Type `$ jupyter lab`, and this issue showed up. 

## What I tried
1. Tried to run `pip3 install nbclassic` again, but didn't work (nothing new was installed or reinstalled).
2. Tried to run `jupyter labextension list` as suggested by some answers that Google was able to find (but not relevant). The printed result:

```
JupyterLab v3.0.15
/Library/Frameworks/Python.framework/Versions/3.9/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
```

3. Tried running `jupyter lab build`. The first time it told me to install node.js (which I assume should've already been there. I was able to run Jupyter Lab without issues before.). The second time there's no error message, and I only got: 
```
[LabBuildApp] JupyterLab 3.0.15
[LabBuildApp] Building in /Library/Frameworks/Python.framework/Versions/3.9/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
```

## Expected behavior

I expected it to work just like before, by opening a new browser window and showing me the file directory. In fact, running `python3 -m notebook` successfully launched a new browser window, albeit with some other errors regarding missing extensions (tensorboard; unrelated). 

## Context

- Operating System and version: Big Sur 11.3.1
- Browser and version: Firefox 
- JupyterLab version: 6.3.0

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/Library/Frameworks/Python.framework/Versions/3.9/bin
	/opt/local/bin
	/opt/local/sbin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/Library/TeX/texbin
	/usr/local/share/dotnet
	~/.dotnet/tools
	/Library/Frameworks/Mono.framework/Versions/Current/Commands

sys.path:
	/Library/Frameworks/Python.framework/Versions/3.9/bin
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
	/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages

sys.executable:
	/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9

sys.version:
	3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02) 
	[Clang 6.0 (clang-600.0.57)]

platform.platform():
	macOS-10.16-x86_64-i386-64bit

which -a jupyter:
	/Library/Frameworks/Python.framework/Versions/3.9/bin/jupyter

pip list:
	Package                 Version
	----------------------- -------------------
	absl-py                 0.12.0
	anyio                   3.0.1
	appdirs                 1.4.4
	appnope                 0.1.2
	argon2-cffi             20.1.0
	astunparse              1.6.3
	async-generator         1.10
	attrs                   21.2.0
	Babel                   2.9.1
	backcall                0.2.0
	beautifulsoup4          4.9.3
	bleach                  3.3.0
	cachetools              4.2.2
	certifi                 2020.12.5
	cffi                    1.14.5
	chardet                 4.0.0
	cycler                  0.10.0
	decorator               4.4.2
	defusedxml              0.7.1
	distlib                 0.3.1
	entrypoints             0.3
	filelock                3.0.12
	flatbuffers             1.12
	gast                    0.4.0
	google-auth             1.30.0
	google-auth-oauthlib    0.4.4
	google-pasta            0.2.0
	grpcio                  1.34.1
	h5py                    3.1.0
	idna                    2.10
	ipykernel               5.5.4
	ipython                 7.23.1
	ipython-genutils        0.2.0
	ipywidgets              7.6.3
	jedi                    0.18.0
	Jinja2                  2.11.3
	joblib                  1.0.1
	json5                   0.9.5
	jsonschema              3.2.0
	jupyter                 1.0.0
	jupyter-client          6.1.12
	jupyter-console         6.4.0
	jupyter-core            4.7.1
	jupyter-server          1.7.0
	jupyterlab              3.0.15
	jupyterlab-pygments     0.1.2
	jupyterlab-server       2.5.1
	jupyterlab-widgets      1.0.0
	keras-nightly           2.5.0.dev2021032900
	Keras-Preprocessing     1.1.2
	kiwisolver              1.3.1
	Markdown                3.3.4
	MarkupSafe              1.1.1
	matplotlib              3.4.2
	matplotlib-inline       0.1.2
	mistune                 0.8.4
	nbclassic               0.2.7
	nbclient                0.5.3
	nbconvert               6.0.7
	nbformat                5.1.3
	nest-asyncio            1.5.1
	networkx                2.5.1
	notebook                6.3.0
	numpy                   1.19.5
	oauthlib                3.1.0
	openai                  0.6.3
	opencv-python           4.5.2.52
	opt-einsum              3.3.0
	packaging               20.9
	pandas                  1.2.4
	pandocfilters           1.4.3
	parso                   0.8.2
	patsy                   0.5.1
	pexpect                 4.8.0
	pgmpy                   0.1.14
	pickleshare             0.7.5
	Pillow                  8.2.0
	pip                     21.1.1
	prometheus-client       0.10.1
	prompt-toolkit          3.0.18
	protobuf                3.16.0
	ptyprocess              0.7.0
	pyasn1                  0.4.8
	pyasn1-modules          0.2.8
	pycparser               2.20
	Pygments                2.9.0
	pyparsing               2.4.7
	pyrsistent              0.17.3
	python-dateutil         2.8.1
	pytz                    2021.1
	pyzmq                   22.0.3
	qtconsole               5.1.0
	QtPy                    1.9.0
	requests                2.25.1
	requests-oauthlib       1.3.0
	rsa                     4.7.2
	scikit-learn            0.24.2
	scipy                   1.6.3
	seaborn                 0.11.1
	Send2Trash              1.5.0
	setuptools              56.0.0
	six                     1.15.0
	sniffio                 1.2.0
	soupsieve               2.2.1
	statsmodels             0.12.2
	tensorboard             2.5.0
	tensorboard-data-server 0.6.1
	tensorboard-plugin-wit  1.8.0
	tensorflow              2.5.0rc3
	tensorflow-estimator    2.5.0rc0
	termcolor               1.1.0
	terminado               0.9.4
	testpath                0.4.4
	threadpoolctl           2.1.0
	torch                   1.8.1
	tornado                 6.1
	tqdm                    4.60.0
	traitlets               5.0.5
	typing-extensions       3.7.4.3
	urllib3                 1.26.4
	virtualenv              20.4.6
	wcwidth                 0.2.5
	webencodings            0.5.1
	websocket-client        0.59.0
	Werkzeug                1.0.1
	wheel                   0.36.2
	widgetsnbextension      3.5.1
	wrapt                   1.12.1
</pre>
</details> 

<details><summary>Command Line Output</summary>
<pre>
[D 2021-05-10 18:29:33.770 ServerApp] Searching ['/Users/xxx/.jupyter', '/Library/Frameworks/Python.framework/Versions/3.9/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2021-05-10 18:29:33.770 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2021-05-10 18:29:33.771 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2021-05-10 18:29:33.771 ServerApp] Looking for jupyter_config in /Library/Frameworks/Python.framework/Versions/3.9/etc/jupyter
[D 2021-05-10 18:29:33.771 ServerApp] Looking for jupyter_config in /Users/xxx/.jupyter
[D 2021-05-10 18:29:33.771 ServerApp] Looking for jupyter_config in /Users/xxx/<root directory>
[D 2021-05-10 18:29:33.772 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2021-05-10 18:29:33.772 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2021-05-10 18:29:33.772 ServerApp] Looking for jupyter_server_config in /Library/Frameworks/Python.framework/Versions/3.9/etc/jupyter
[D 2021-05-10 18:29:33.772 ServerApp] Looking for jupyter_server_config in /Users/xxx/.jupyter
[D 2021-05-10 18:29:33.773 ServerApp] Looking for jupyter_server_config in /Users/<root directory>
[D 2021-05-10 18:29:33.775 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/etc/jupyter/jupyter_server_config.json
[D 2021-05-10 18:29:33.775 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/usr/local/etc/jupyter/jupyter_server_config.json
[D 2021-05-10 18:29:33.775 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/Library/Frameworks/Python.framework/Versions/3.9/etc/jupyter/jupyter_server_config.d/jupyterlab.json
    	/Library/Frameworks/Python.framework/Versions/3.9/etc/jupyter/jupyter_server_config.d/nbclassic.json
    	/Library/Frameworks/Python.framework/Versions/3.9/etc/jupyter/jupyter_server_config.json
[D 2021-05-10 18:29:33.777 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/Users/xxx/.jupyter/jupyter_server_config.json
[D 2021-05-10 18:29:33.791 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue {'update': {'nbclassic': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2021-05-10 18:29:33.792 ServerApp] jupyterlab | extension was successfully linked.
[D 2021-05-10 18:29:33.805 NotebookApp] Config changed: {'NotebookApp': {'nbserver_extensions': {'jlstaticserve': True, 'jupyter_tensorboard': True}}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'nbclassic': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2021-05-10 18:29:34.138 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/Users/xxx/.jupyter/jupyter_notebook_config.json
[D 2021-05-10 18:29:34.139 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 2021-05-10 18:29:34.140 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2021-05-10 18:29:34.140 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/Library/Frameworks/Python.framework/Versions/3.9/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/Library/Frameworks/Python.framework/Versions/3.9/etc/jupyter/jupyter_notebook_config.json
[D 2021-05-10 18:29:34.141 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/Users/xxx/.jupyter/jupyter_notebook_config.json
[W 2021-05-10 18:29:34.141 ServerApp] 'ExtensionManager' object has no attribute '_extensions'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 518, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 488, in initialize_server
    serverapp.initialize(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 1855, in initialize
    point = self.extension_manager.extension_points[starter_extension]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 290, in extension_points
    extensions = self.extensions
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nbclassic/nbserver.py", line 80, in extensions
    nb = self._extensions.get("nbclassic")
AttributeError: 'ExtensionManager' object has no attribute '_extensions'
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
(None)
</pre>
</details>

**Comment by StephenWithPH** [comment]
I receive the exact same error and stack trace.

Salient info:
* `Python 3.8.5`
* running in a shell spawned via `nix-shell --pure` ([info](https://nix.dev/tutorials/ad-hoc-developer-environments.html#towards-reproducibility)), so about as pristine of a runtime environment as one could ever have.
* installed via Poetry (`Poetry version 1.0.10`)
* `jupyterlab = "^3.0.15"`
* pinning `nbclassic = "0.2.6"` didn't help

**Comment by kevin-bates** [comment]
Looks like the `nbclassic` server extension is side-effected by https://github.com/jupyter-server/jupyter_server/pull/502 - which just released its 1.7.0 release today.

Folks should probably downgrade `jupyter_server` (temporarily) to `1.6.4` until `nbclassic` is fixed.  Sorry for the inconvenience.

**Comment by EulerFaria** [comment]
Same Issue here guys. 

I created a virtualenv from scratch with Python 3.7.0.  and ran `pip install jupyterlab`.  


```
[I 2021-05-10 21:21:12.781 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-05-10 21:21:12.815 ServerApp] The 'min_open_files_limit' trait of a ServerApp instance expected an int, not the NoneType None.
Traceback (most recent call last):
  File "C:\Users\.......\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
 ......
    nb = self._extensions.get("nbclassic")
AttributeError: 'ExtensionManager' object has no attribute '_extensions'
```

**Comment by Zsailer** [comment]
As @kevin-bates said, downgrading jupyter_server temporarily should do the trick.

**Comment by sikyeong** [comment]
same with me 

> 'ExtensionManager' object has no attribute '_extensions'
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 518, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 488, in initialize_server
    serverapp.initialize(
  File "/usr/local/lib/python3.8/site-packages/traitlets/config/application.py", line 86, in inner
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1855, in initialize
    point = self.extension_manager.extension_points[starter_extension]
  File "/usr/local/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 290, in extension_points
    extensions = self.extensions
  File "/usr/local/lib/python3.8/site-packages/nbclassic/nbserver.py", line 80, in extensions
    nb = self._extensions.get("nbclassic")
AttributeError: 'ExtensionManager' object has no attribute '_extensions'


Salient info:

`python 3.8.8`
`jupyterlab-3.0.15`
`nbclassic-0.2.7`


so, i use jupyter notebook Instead of lab

**Comment by kevin-bates** [comment]
I also found you can keep `jupyter_server` at `1.7.0` but **disable** `nbclassic` if you know you don't need it...
```
jupyter server extension disable nbclassic
```
This might be easier for some.

**Comment by jingfang** [comment]
same problem here, and @kevin-bates's solution worked!

**Comment by trungnghiahoang96** [comment]
thanks, @kevin-bates. The solution worked!

**Comment by sikyeong** [comment]
thanks, @kevin-bates. it worked well!

**Comment by wrogner** [comment]
Same issue on MacOS 11.3.1, Python 3.9.5, jupyter_server 1.7.0.

Starting jupyter lab brings the above mentioned error.
Starting jupyter notebook starts the server.
Starting jupyter notebook and changing the URL from http://localhost:8888/tree to http://localhost:8888/lab **launches the lab**
==> Jupyter Lab works

**Analysis:**
The error message (last line) shows that jupyter server gets "nbclassic" extensions:
```
File "venv/lib/python3.9/site-packages/nbclassic/nbserver.py", line 80, in extensions
    nb = self._extensions.get("nbclassic")
```

**Solution:**
Go to "venv/etc/jupyter/jupyter_server_config.d"
move nbclassic.json to nbclassic.json_orig and
copy jupyterlab.json to nbclassic.json

Launch jupyter lab ==> works (launches web interface for lab)
Launch jupyter notebook ==> works (launches web interface for notebooks)

**Explanation:**
It's just a wrong setting in nbclassic.json
Installed:
```
{
    "ServerApp": {
        "jpserver_extensions": {
            "nbclassic": true
        }
    }
}
```

Required:
```
{
  "ServerApp": {
    "jpserver_extensions": {
      "jupyterlab": true
    }
  }
}
```

**Comment by krassowski** [comment]
As this seems to affect many users, I wanted to highlight that you can now just:

```bash
pip install -U "nbclassic>=0.2.8"
```

or, if using conda:

```bash
conda install "nbclassic>=0.2.8"
```

to solve the problem.
