### ISSUE TITLE
Embed it into <iframe>

### ISSUE THREAD

**Issue by kbmelo** [jupyterlab/jupyterlab#10231]
I am having trouble trying to embed the jupyterlab into an iframe. Does anyone know how to get it working?
I tried changing the Content-Security-Policy header, but couldn't do it, in case anyone has any idea.
PS: Trying to get it with axios returns `Refused to frame 'http://127.0.0.1:8888/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".`

![image](https://user-images.githubusercontent.com/43002117/117802171-846ce900-b22b-11eb-9e06-927342fde984.png)

**Comment by ashishkshukla** [comment]
Hi @kbmelo , I am able to embed by providing below command while starting the jupyterlab

`jupyter lab --LabApp.token="abc2343"  --NotebookApp.base_url=testpath --LabApp.tornado_settings='{"headers":{"Content-Security-Policy":"frame-ancestors * self "}}' --ip=0.0.0.0` 

and in iframe

`<iframe id="jupyterid" src="http://<hostip>:8888/testpath?token=abc2343" width="100%" height="600px" border=0></iframe>` 

this is working fine in mozilla firefox.

The only issue I am facing is in case of chrome. In chrome it is not able to get the python kernel images on the UI. 
It would be really great if some can help it here.

**Comment by kbmelo** [comment]
@ashishkshukla Thank you so much! It works, just adding: I'm running on macOS with M1, so I also had to add the flag --core-mode.
Btw: When I run with this big command, for some reason it hides the token on the terminal (showing "..." instead), does the same happen to you?

![image](https://user-images.githubusercontent.com/43002117/118154261-356eb180-b3ed-11eb-9374-c4ea73d90f9f.png)

**Comment by kbmelo** [comment]
Oh, I removed the first flag (--LabApp.token="abc2343") and now it worked. The problem is that it doesn't actually run the python code.

**Comment by kbmelo** [comment]
@ashishkshukla Thank you so much! It works, just adding: I'm running on macOS with M1, so I also had to add the flag --core-mode.
The problem now is that the kernel doesn't connect, it shows "Python 3 | disconnected" and I can't run the code. Anyone facing the same issue?

**Comment by kbmelo** [comment]
I figured it out, I had to downgrade some packages.
I was using:  tornado 6.1,   notebook 6.3.0, jupyterlab 3.0.14.
Changed to: tornado 5.1.1, notebook 5.7.8, jupyterlab 2.1.2
```
% jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 5.7.8
qtconsole        : 5.1.0
ipython          : 7.23.1
ipykernel        : 5.5.5
jupyter client   : 6.1.12
jupyter lab      : 2.1.2
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```
