### ISSUE TITLE
Improvements on the completer

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyterlab#10243]
I'm working o a completer extension with lazy loading of the documentation. The problem is that we need to know which index is selected and when the selected item changes.

Some extensions like [JupyterLab-LSP](https://github.com/krassowski/jupyterlab-lsp) uses some hacks to [access the `_activeIndex`]( https://github.com/krassowski/jupyterlab-lsp/blob/309b3fa7ba506f5597d3ace35aa3e4eefef55e4a/packages/jupyterlab-lsp/src/features/completion/completion.ts#L317) and [observes the items](https://github.com/krassowski/jupyterlab-lsp/blob/309b3fa7ba506f5597d3ace35aa3e4eefef55e4a/packages/jupyterlab-lsp/src/features/completion/renderer.ts#L62) to know if the `_activeIndex` changes.

Another problem is that the connector in `CompletionHandler` [could be either a `IDataConnector` or `ICompletionItemsConnector`](https://github.com/jupyterlab/jupyterlab/blob/aaee10afedd0896e60c4d02d45a3673f4994309c/packages/completer/src/handler.ts#L528) but his [public accessor is only `IDataConnector`](https://github.com/jupyterlab/jupyterlab/blob/aaee10afedd0896e60c4d02d45a3673f4994309c/packages/completer/src/handler.ts#L60)

### Proposed Solution
It would be great to add a getter to `_activeIndex`, a `Signal` triggered when the active index changes, and make the public API for the connector more generic.

I can open a PR.

**Comment by krassowski** [comment]
You might be also interested in the proposed completer refactor notes in https://github.com/jupyterlab/jupyterlab/issues/9763. I was planning to work on it for 4.0 (and don't have bandwidth to do it right now - I am doing stuff in my free time and don't have that currently), but I am happy to champion for any changes to make it sooner.

**Comment by krassowski** [comment]
Also, would love to learn about the extension an how it fits with LSP (and how to possibly avoid clashes if users decide to install both).

**Comment by hbcarlos** [comment]
Thanks for the notes. I'll take a look later.

> Also, would love to learn about the extension an how it fits with LSP (and how to possibly avoid clashes if users decide to install both).

For now, it's just a prototype, but, yes we should catch up at some point. We want compatibility with LSP and kite.

**Comment by hbcarlos** [comment]
Btw, I have a question.
Is the [`DummyConnector`](https://github.com/jupyterlab/jupyterlab/blob/0021d40004df716bd244e433a070ec6ab0985476/packages/completer/src/handler.ts#L65) there only to keep backwards compatibility?

**Comment by krassowski** [comment]
I think so, [see](https://github.com/jupyterlab/jupyterlab/commit/d310fc2a26a0ee7c9dc3ff65e6b27971b8a1d623), I would be happy to see this duality of old and new API to go away in 4.0 (deprecate in 3.1).

**Comment by krassowski** [comment]
Also see https://github.com/krassowski/jupyterlab-lsp/pull/600. I am trying to make creating custom completion providers easy, feature-complete while compatible with LSP. I would be happy to hear your thoughts on it.

This is just a draft for now (and requires LSP extension in the first place), but I will be also working to hook it up as completely independent (and hopefully move it into `@jupyterlab/` for 4.0, while moving many parts into `/completer` and `/completer-extension`; the goal for now is to experiment with the API to get something that would be flexible and future-proof).

**Comment by hbcarlos** [comment]
> I think so, [see](https://github.com/jupyterlab/jupyterlab/commit/d310fc2a26a0ee7c9dc3ff65e6b27971b8a1d623), I would be happy to see this duality of old and new API to go away in 4.0 (deprecate in 3.1).

I think that's an old PR, and the actual behaviour is different. I would say we can't access the connector if this is an `ICompletionItemsConnector`.

To create a `CompletionItemsConnector` we need to implement `ICompleterConnecterResponseType` see https://github.com/jupyterlab/jupyterlab/blob/8c608df4b2b4fee9d4e668cf3c9d37d439a8b122/packages/completer/src/handler.ts#L613
that has the property `responseType` see https://github.com/jupyterlab/jupyterlab/blob/8c608df4b2b4fee9d4e668cf3c9d37d439a8b122/packages/completer/src/handler.ts#L639

And if the connector has the property `responseType` the handler returns a `DummyConnector` see https://github.com/jupyterlab/jupyterlab/blob/8c608df4b2b4fee9d4e668cf3c9d37d439a8b122/packages/completer/src/handler.ts#L65

Is that correct?

**Comment by hbcarlos** [comment]
Solved in #10244
