### ISSUE TITLE
Dark Theme Plot settings

### ISSUE THREAD

**Issue by kr-hansen** [jupyterlab/jupyterlab#10242]
## Description

Issue with Plot axes/titles with the Jupyter Lab Dark Theme.  It seems this was fixed/addressed a while ago with this issue [#5232](https://github.com/jupyterlab/jupyterlab/pull/5232).  However, maybe something broke it with Jupyter Lab 3.0?  I was unsure why I'm seeing that same issue with the newer version of Jupyter Lab.

## Reproduce

Make a plot in a notebook in Jupyter Lab with the JupyterLab Dark Theme.  The axes are missing (same thing happens with titles)

![image](https://user-images.githubusercontent.com/15696062/118187828-bd0fec80-b3fc-11eb-8b1e-e7e193e5dd1d.png)

Here is the same setup after just switching to the Light theme. The axes are back!

![image](https://user-images.githubusercontent.com/15696062/118187921-e3358c80-b3fc-11eb-960c-62cab972181e.png)

## Expected behavior

Expected to be able to see the axes/title info in the Dark Theme.

## Context
- Operating System and version: Mac OSX Big Sur 11.2.3
- Browser and version: Chrome Version 90.0.4430.93
- JupyterLab version: 3.0.14

![image](https://user-images.githubusercontent.com/15696062/118188228-4c1d0480-b3fd-11eb-9ad1-dedb3b27c748.png)

**Comment by krassowski** [comment]
The code contributed in that patch is still there, and it does work for me:

![Screenshot from 2021-05-14 10-52-03](https://user-images.githubusercontent.com/5832902/118253999-8096cc00-b4a2-11eb-88cd-c62112a18350.png)


Did you use any kind of `%matplotlib` magic in the cells that you run before?

**Comment by krassowski** [comment]
I saw this issue affect users of matplotlib wrappers such as single cell spatial package before: [SO: Change the color of a single *output* cell in jupyter notebook?](https://stackoverflow.com/questions/66980763/change-the-color-of-a-single-output-cell-in-jupyter-notebook).

Also for ease of testing:

```
import matplotlib.pyplot as plt
plt.plot(range(5))
```

**Comment by ichsan2895** [comment]
> ## Description
> Issue with Plot axes/titles with the Jupyter Lab Dark Theme. It seems this was fixed/addressed a while ago with this issue [#5232](https://github.com/jupyterlab/jupyterlab/pull/5232). However, maybe something broke it with Jupyter Lab 3.0? I was unsure why I'm seeing that same issue with the newer version of Jupyter Lab.
> 
> ## Reproduce
> Make a plot in a notebook in Jupyter Lab with the JupyterLab Dark Theme. The axes are missing (same thing happens with titles)
> 
> ![image](https://user-images.githubusercontent.com/15696062/118187828-bd0fec80-b3fc-11eb-8b1e-e7e193e5dd1d.png)
> 
> Here is the same setup after just switching to the Light theme. The axes are back!
> 
> ![image](https://user-images.githubusercontent.com/15696062/118187921-e3358c80-b3fc-11eb-960c-62cab972181e.png)
> 
> ## Expected behavior
> Expected to be able to see the axes/title info in the Dark Theme.
> 
> ## Context
> * Operating System and version: Mac OSX Big Sur 11.2.3
> * Browser and version: Chrome Version 90.0.4430.93
> * JupyterLab version: 3.0.14
> 
> ![image](https://user-images.githubusercontent.com/15696062/118188228-4c1d0480-b3fd-11eb-9ad1-dedb3b27c748.png)

Works good in Jupyter 3.0.7
![image](https://user-images.githubusercontent.com/60387342/118266070-4e0dc300-b4e4-11eb-8be0-96c051cf089a.png)

**Comment by kr-hansen** [comment]
`matplotlib` magic doesn't change anything.  The first in the OP are without any magic, and I tried adding the inline which still didn't work.  See below:

![image](https://user-images.githubusercontent.com/15696062/118292509-efb9f380-b495-11eb-9d32-f6b795fc78c9.png)

Additionally, I've tried it in Firefox with the same issue.  I also tried turning my Mac "Dark Mode" off as well without changing anything either.  Any other ideas to try tweaking?

Is it possibly and issue with more recent versions of JupyterLab?  Any other ideas of things to try as to why this might be happening?

**Comment by krassowski** [comment]
> Is it possibly and issue with more recent versions of JupyterLab?

No, I tried with 3.0.15 which is the most recent version.

>  Any other ideas of things to try as to why this might be happening?

- What version of IPython, ipykernel, and matplotlib are you using? 
- Do you have any non-standard themes installed?
- Could you show you theme settings? Mine are:

![Screenshot from 2021-05-14 17-08-54](https://user-images.githubusercontent.com/5832902/118298216-177d7b80-b4d7-11eb-96db-81bb7d050d67.png)

**Comment by kr-hansen** [comment]
IPython: 7.16.1
ipykernel: 4.8.2
matplotlib: 3.3.2

No non-standard themes installed at all:

![image](https://user-images.githubusercontent.com/15696062/118299548-1ed46300-b49e-11eb-8168-335ce081848d.png)

**Comment by krassowski** [comment]
Final idea: are you able to reproduce this on binder: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/5a5eb6b?urlpath=lab/tree/demo)?

**Comment by kr-hansen** [comment]
Interesting.  So it works on binder.

![image](https://user-images.githubusercontent.com/15696062/118301982-e84c1780-b4a0-11eb-839a-57d5390398db.png)

Other packages to check versioning on with my local version that may be causing it?

**Comment by krassowski** [comment]
Oh, it is **ipykernel**. You have too old version (4.8). The https://github.com/ipython/ipykernel/pull/336 PR which is sister to https://github.com/jupyterlab/jupyterlab/pull/5232 was only merged for 4.9. Given the current version is 5.5.5 and 6.0 is coming I would say just try upgrading to 5.x for now.

**Comment by kr-hansen** [comment]
That was it!  Upgraded to ipykernel - 5.3.4 and it works now.

![image](https://user-images.githubusercontent.com/15696062/118315122-55b47400-b4b2-11eb-8423-a135e7e5bd1d.png)

Thank you for helping me track down that dependency and ironing it out!  This issue can be closed by my opinion.
