### ISSUE TITLE
Rename/F2 does not work when not in root

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10248]
## Description

After https://github.com/jupyterlab/jupyterlab/pull/10206 the added F2 shortcut does not work on master when outside of root. https://github.com/jupyterlab/jupyterlab/pull/10237 might be related. CC @martinRenou. It might also affect other shortcuts.

## Reproduce

![f2-broken](https://user-images.githubusercontent.com/5832902/118340005-6d234980-b512-11eb-9ab5-5f4d4fdd2d10.gif)

## Context

- Browser and version: Chrome
- JupyterLab version: 3.1a8/master

<details><summary>Browser Output</summary>
<pre>
domutils.js:24 Uncaught (in promise) TypeError: Cannot read property 'querySelector' of undefined
    at Object.findElement (domutils.js:24)
    at Renderer.getNameNode (listing.js:1596)
    at DirListing._doRename (listing.js:1250)
    at DirListing.rename (listing.js:267)
    at FileBrowser.rename (browser.js:176)
    at execute (index.js:731)
    at CommandRegistry.execute (index.es6.js:372)
    at CommandRegistry._executeKeyBinding (index.es6.js:532)
    at CommandRegistry.processKeydownEvent (index.es6.js:471)
    at JupyterLab.Application.evtKeydown (index.es6.js:355)
findElement @ domutils.js:24
getNameNode @ listing.js:1596
_doRename @ listing.js:1250
rename @ listing.js:267
rename @ browser.js:176
execute @ index.js:731
CommandRegistry.execute @ index.es6.js:372
CommandRegistry._executeKeyBinding @ index.es6.js:532
CommandRegistry.processKeydownEvent @ index.es6.js:471
Application.evtKeydown @ index.es6.js:355
Application.handleEvent @ index.es6.js:311
</pre>
</details>

**Comment by krassowski** [comment]
Actually it also affects rename triggered by context menu:

![rename-does-not-work](https://user-images.githubusercontent.com/5832902/118340337-487ba180-b513-11eb-9383-258f20afa7e0.gif)

**Comment by krassowski** [comment]
Also navigation between files with arrows is broken:

![go-up-down](https://user-images.githubusercontent.com/5832902/118342187-318c7d80-b51a-11eb-9478-cf6f7b0a4f7f.gif)

**Comment by martinRenou** [comment]
> After #10206 the added F2 shortcut does not work on master

Are you sure #10206 is the culprit? From my understanding, adding keybindings should not change the behavior, it should just add shortcuts to already existing behaviors?

**Comment by krassowski** [comment]
Absolutely not, sorry I meant to edit it and said that it is likely #10237 but forgotten.

**Comment by martinRenou** [comment]
No worries. I am leaving for vacation this week and won't be able to work on this (no available laptop). Do you think we should revert this PR before I work again on this?

**Comment by krassowski** [comment]
I guess reverting the use of paths over names would help to ensure that my fixes for shortcuts in #6859 are good enough.

**Comment by martinRenou** [comment]
I suspect the root cause of this issue is that the rename/delete and other commands are based on the selection, so they might rely on the name of the currently selected files and the current basepath. We would need to make those commands rely on the clicked files's paths as well, without the need of appending the basepath anymore.

**Comment by krassowski** [comment]
Agreed. And I like the idea of moving towards paths rather than using names in general. What I am afraid is that in addition to issues listed above it could also break some extensions (jupyterlab-git has adds context menu actions - for example) so maybe it would benefit from extra attention and testing.
