### ISSUE TITLE
Pluggable provider for real time collaboration

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#10252]
### Problem

For now the provider for real time collaboration is defined in the doc registry `Context`:

https://github.com/jupyterlab/jupyterlab/blob/27ecb2f9a22736c13a8b0e2722fbdf046d37c43c/packages/docregistry/src/context.ts#L92-L96

It relies on the backend exposing the `/api/yjs` endpoint, and uses the `WebsocketProviderWithLocks` to connect to it.

This should ideally be configurable, so extension authors could use a different provider if they would like to.

### Proposed Solution

One way to implement this would be to move that logic to a plugin in the `docmanager-extension` package.

In JupyterLab the plugin would still use the `WebsocketProviderWithLocks` class if `collaborative` is set in the page config, so pretty much the same behavior.

Third-party extensions could provide a different plugin and replace it using the existing mechanism to disable other extensions: https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html?#disabling-other-extensions

### Additional context

Alternative distributions could do something similar and not include the upstream JupyterLab plugin, and instead provide a custom one.

**Comment by echarles** [comment]
I've discussed that aspect with @dmonad when we have created that new package, and logged the issued in https://github.com/jupyter-rtc/jupyterlab/issues/13

To be deliver, we have picked the approach initially implemented in the `docregistry`package. I have started experimenting to make the current `docregistry` an extension, so having `docregistry-extension` package. This would allow to support configuration to the current yjs provider (say finer-grain setting on websocket provider, or define another protocol provider, or even define another library than yjs). Having such `docregistry-extension` had quite some impact to the current packages using the `docregistry`, so I did not complete that road.

Moving the logic to `docmanager-extension` may show less impact as the extension is already there.

So if moving that logic is painless, this may be a better approach.

**Comment by jtpio** [comment]
> Having such `docregistry-extension` had quite some impact to the current packages using the `docregistry`, so I did not complete that road.

Or maybe we need a `docprovider-extension` package?

Probably what we need in the end is a plugin that provides an `IProvider`?

https://github.com/jupyterlab/jupyterlab/blob/27ecb2f9a22736c13a8b0e2722fbdf046d37c43c/packages/docprovider/src/index.ts#L10

**Comment by echarles** [comment]
> Or maybe we need a docprovider-extension package?

In that case, we would need a `docregistry-extension` to consume `docprovider-extension` ?

**Comment by jtpio** [comment]
> In that case, we would need a `docregistry-extension` to consume `docprovider-extension` ?

Or `docmanager-extension` requiring the token from `docprovider-extension` with:

```typescript
import { IProvider } from `@jupyterlab/docprovider`;

// then expose a plugin that provides `IProvider`
```

Still thinking through this, but at first it looked like `docmanager-extension` could be a good candidate, since the `docmanager` creates the new `Context` here:

https://github.com/jupyterlab/jupyterlab/blob/27ecb2f9a22736c13a8b0e2722fbdf046d37c43c/packages/docmanager/src/manager.ts#L477-L487

We could then  pass the (optional) `IProvider` when creating the `DocumentManager` here?

https://github.com/jupyterlab/jupyterlab/blob/27ecb2f9a22736c13a8b0e2722fbdf046d37c43c/packages/docmanager-extension/src/index.ts#L143-L152

**Comment by jtpio** [comment]
@echarles https://github.com/jupyterlab/jupyterlab/pull/10256 implements this idea, in case you want to check it out.

Going down this road, it looks like it would indeed make sense to have a `docprovider-extension` package (with a single plugin for now). So it's consistent with the rest of the code base.
