### ISSUE TITLE
Emit cell execution signal for both successful and failed notebook cell

### ISSUE THREAD

**Issue by mwakaba2** [jupyterlab/jupyterlab#10259]
### Problem

Hi there! I have a [lab extension](https://github.com/mwakaba2/jupyterlab-notifications) that sends a browser notification to users after a notebook cell execution is complete.
The extension relies on the [`NotebookActions.executed`](https://jupyterlab.github.io/jupyterlab/classes/_notebook_src_index_.notebookactions.html#executed) signal and `execution` metadata to trigger the notification. 

However, it looks like the signal is only emitted if the notebook cell execution was successful, so the labextension is unable to trigger a browser notification when the cell has any exceptions in the code. 

[source: actions code](https://github.com/jupyterlab/jupyterlab/blob/765ee24f8923b907dc2a3a6cf158ca40f3e9fab7/packages/notebook/src/actions.tsx#L1661)
```javascript
.then(ran => {
  if (ran) {
    executed.emit({ notebook, cell });
 }
```
I'd like the signal to be emitted for both successful and failed notebook cell and also include the status of the execution in the cell metadata. (`status` = `error`, `ok`, etc)

### Proposed Solution

- Emit a signal for a code cell that has `reply.content.status` == `error`.
- Create a `status` attribute in the metadata object.

```javascript
if (reply.content.status === 'ok') {
 ....
  cell.model.metadata.set('status', 'ok');
  return true;
} 
else if (reply.content.status == 'error') {
  cell.model.metadata.set('status', 'error');
   return true;
} ....
...
.then(ran => {
  if (ran) {
    executed.emit({ notebook, cell });
 }

  return ran;
});
```

This is just one solution I can think of at the moment. If there's a better one or other solutions, I'd love to learn!
Also, if the proposed solution looks good, I'm happy to make the update.

### Additional context

For more context, this is the issue in the [jupyterlab-notifications repo](https://github.com/mwakaba2/jupyterlab-notifications).
[Notification is not triggered when the cell has an error.](https://github.com/mwakaba2/jupyterlab-notifications/issues/10)

**Comment by krassowski** [comment]
I don't think that changing metadata is necessary. Another solution would be to have another signal for exceptions, for example:

- `ran: Signal<any, { notebook: Notebook; cell: Cell }>` - when cell starts running so you can record the start time without relying on `recordTiming` (it would simplify configuration for users of your very useful extensions); `recordTiming` is probably preferred as I imagine it is (or could be made) persistent in case if someone refreshes browser
- `raised: Signal<any, { notebook: Notebook; cell: Cell, error: Error }>` and modify the throw from `throw new Error('KernelReplyNotOK');` to `throw new KernelError(reply.content);` (Errors can be subclassed in recent TypeScript assuming ES2015+ target); I think that this would allow you to get the traceback info and display it in the notification (but I am no sure).

**Comment by mwakaba2** [comment]
@krassowski Thanks for your suggestion!
I wrote a bit of pseudocode to make sure I understand your solution correctly. 

```javascript
ran.emit("ran: Signal<any, { notebook: Notebook; cell: Cell }>")
return CodeCell.execute(cell as CodeCell, sessionContext, 
                                          { deletedCells, recordTiming: notebook.notebookConfig.recordTiming})
.then(reply, => {
  ...throw new KernelError(reply.content);
}.catch(reason, => {
  raised.emit("raised: Signal<any, { notebook: Notebook; cell: Cell, error: Error }>")
}.then(ran, => {
  executed.emit(emit "executed: Signal<any, { notebook: Notebook; cell: Cell }>")
}
```
Is this close to your suggestion?

Or for the `ran` signal, would it make sense to emit that in the `CodeCell.execute` function?

**Comment by krassowski** [comment]
> Is this close to your suggestion?

Yes.

> Or for the ran signal, would it make sense to emit that in the CodeCell.execute function?

Yes, that would make sense too. Personally I think having related signals close in the codebase might make it easier to comprehend.

At second thought maybe instead of _ran_ naming it _executionScheduled_ would be better? We could also have _executionStarted_ inside CodeCell.execute - I am guessing that there should be a place where it belongs, close to the timer start code?

**Comment by mwakaba2** [comment]
Yup, I agree, those are all good descriptive names and signals to have. I'll work on a draft sometime this week or next.

**Comment by krassowski** [comment]
One more thought: what would be super useful for me is a notification once **all** scheduled cells finished execution. It would improve my productivity quite a bit I believe. I wonder if the three proposed signals:
- `executionScheduled`
- `executionStarted`
- `raised`

(+ the existing `executed`) are enough to implement this or whether we would need also `allExecuted` signal (or something like that). CC @jasongrout for API design? (I think that the need for extra signals was brought up before but it was probably in a zoom meeting as I could not find an issue).

**Comment by mwakaba2** [comment]
>notification once all scheduled cells finished execution.

Oh yeah I also think that'd be super useful. That would probably require knowing if the currently running cell is the last scheduled run for one notebook. I'm not sure if that information is already available.

**Comment by krassowski** [comment]
Closing as implemented in https://github.com/jupyterlab/jupyterlab/pull/10493 (with slightly different in signal naming - see the discussion on the PR).

**Comment by mwakaba2** [comment]
@krassowski Thanks again for the suggestions/feedback! 
Just wanted to let you know that the feature to only get notified once all selected cells finished executions is out. 🙂
https://github.com/mwakaba2/jupyterlab-notifications/releases/tag/0.3.0
