### ISSUE TITLE
Add yjs as shared dependency

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyterlab#10266]
## Description
I'm trying to create a new shared model for an [extension](https://github.com/QuantStack/jupyterlab-drawio/pull/89); for that reason, I need to import yjs. The problem comes from yjs that need only one copy of the library, and we have two (one in JupyterLab and another in the extension).

The solution would be to add yjs to resolutions in JupyterLab's [package.json](https://github.com/jupyterlab/jupyterlab/blob/2dd172de23b19eec6e781a0432c7da193da46841/jupyterlab/staging/package.json#L17).
Another solution would be to add yjs to `jupyterlab.sharedPackages` in those core extension that uses yjs. Still, yjs is used in core packages, not in extensions (docprovider, docregistry and shared-models), and I think JupyterLab only deduplicates dependencies from extensions (core packages don't have `jupyterlab.sharedPackages`).

The second solution implicates to modify [webpack.config](https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/staging/webpack.config.js) to get shared packages from core packages.

## Expected behavior

Import yjs on extensions.

## Context
I have an error with yjs coming from:
https://github.com/QuantStack/jupyterlab-drawio/blob/f66b1c571b9b4007a7b08a0bd42c4e3c967cc916/src/model.ts#L167

It looks like there are two instances, one coming from JupyterLab and another from the extension.

<details><summary>Browser Output</summary>
<pre>
9795.87a9ff4f3c3919e683d2.js?v=87a9ff4f3c3919e683d2:1 Uncaught Error: Unexpected content type in insert operation
    at 9795.87a9ff4f3c3919e683d2.js?v=87a9ff4f3c3919e683d2:1
    at Array.forEach (<anonymous>)
    at Vs (9795.87a9ff4f3c3919e683d2.js?v=87a9ff4f3c3919e683d2:1)
    at Ps (9795.87a9ff4f3c3919e683d2.js?v=87a9ff4f3c3919e683d2:1)
    at 9795.87a9ff4f3c3919e683d2.js?v=87a9ff4f3c3919e683d2:1
    at Yn (9795.87a9ff4f3c3919e683d2.js?v=87a9ff4f3c3919e683d2:1)
    at mr.insert (9795.87a9ff4f3c3919e683d2.js?v=87a9ff4f3c3919e683d2:1)
    at new Q (646.3107e1e3e0432c8636f0.js?v=3107e1e3e0432c8636f0:1)
    at Function.create (646.3107e1e3e0432c8636f0.js?v=3107e1e3e0432c8636f0:1)
    at new z (646.3107e1e3e0432c8636f0.js?v=3107e1e3e0432c8636f0:1)
</pre>
</details>

This line returns false, being `ydoc` an instance coming from JupyterLab and `Y.XmlFragment` a class imported from Yjs in the extension.
```typescript
this.ydoc.getXmlFragment('root') instanceof Y.XmlFragment
```
https://github.com/QuantStack/jupyterlab-drawio/blob/f66b1c571b9b4007a7b08a0bd42c4e3c967cc916/src/model.ts#L166

cc @jtpio @dmonad

**Comment by krassowski** [comment]
This looks very much like the issue with CodeMirror, which was solved by using a token that provides a "singleton" instance: https://github.com/jupyterlab/jupyterlab/issues/10095; would this pattern help here too?

**Comment by hbcarlos** [comment]
Hey, thanks for the help Michał.

That maybe works. I need to try it out.

**Comment by jtpio** [comment]
> This looks very much like the issue with CodeMirror, which was solved by using a token that provides a "singleton" instance:

Looks like its refers to this plugin?

https://github.com/jupyterlab/jupyterlab/blob/8c608df4b2b4fee9d4e668cf3c9d37d439a8b122/packages/codemirror-extension/src/index.ts#L55-L60

**Comment by jtpio** [comment]
> The problem comes from yjs that need only one instance, and we have two (one in JupyterLab and another in the extension).

Just to double check: is the issue related to having two instances of Yjs (and does Yjs need to be a singleton on the page?), or two copies of the library (possibly with different versions)?

**Comment by hbcarlos** [comment]
Sorry, my bad. It's two copies of the library.

The problem is that yjs uses `instanceof` to check the type of item added https://github.com/yjs/yjs/blob/7bd764fba73fecb8bacd1eb82a4bd7c9e15a33ee/src/types/AbstractType.js#L670
and fails when coming from different libraries.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/10301
