### ISSUE TITLE
open a page with only an icon...

### ISSUE THREAD

**Issue by adaaaaaa** [jupyterlab/jupyterlab#10261]
[captain@captain-notebook pip]$ jupyter-lab
[I 2021-05-18 15:31:49.543 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-05-18 15:31:49.543 ServerApp] jupytext | extension was successfully linked.
[I 2021-05-18 15:31:49.793 ServerApp] nbresuse | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2021-05-18 15:31:49.794 ServerApp] nbresuse | extension was successfully linked.
[I 2021-05-18 15:31:49.794 ServerApp] nbclassic | extension was successfully linked.
[I 2021-05-18 15:31:49.862 LabApp] JupyterLab extension loaded from /home/captain/.pyenv/versions/3.8.6/lib/python3.8/site-packages/jupyterlab
[I 2021-05-18 15:31:49.862 LabApp] JupyterLab application directory is /home/captain/.pyenv/versions/3.8.6/share/jupyter/lab
[I 2021-05-18 15:31:49.866 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-05-18 15:31:49.866 ServerApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager
[I 2021-05-18 15:31:49.867 ServerApp] jupytext | extension was successfully loaded.
[I 2021-05-18 15:31:49.871 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-05-18 15:31:49.872 ServerApp] nbresuse | extension was successfully loaded.
[I 2021-05-18 15:31:49.872 ServerApp] 启动notebooks 在本地路径: /home/captain/competition
[I 2021-05-18 15:31:49.872 ServerApp] Jupyter Server 1.6.4 is running at:
[I 2021-05-18 15:31:49.872 ServerApp] http://localhost:8888/lab?token=9f73c9dd7bd4bef42e84d1a9c2128332ba9704dbe88d4921
[I 2021-05-18 15:31:49.872 ServerApp]     http://127.0.0.1:8888/lab?token=9f73c9dd7bd4bef42e84d1a9c2128332ba9704dbe88d4921
[I 2021-05-18 15:31:49.872 ServerApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 2021-05-18 15:31:49.898 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/captain/.local/share/jupyter/runtime/jpserver-27459-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=9f73c9dd7bd4bef42e84d1a9c2128332ba9704dbe88d4921
        http://127.0.0.1:8888/lab?token=9f73c9dd7bd4bef42e84d1a9c2128332ba9704dbe88d4921

![Screenshot_2021-05-18 JupyterLab](https://user-images.githubusercontent.com/23206387/118613445-58d09c80-b7f1-11eb-9e3c-8019b09c59de.png)

**Comment by ReneHamburger1993** [comment]
does it help to close the session + terminal and restart your browser?
does it work opening the link in another browser?
