### ISSUE TITLE
Skip links review

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#10268]
I was looking through the skiplinks implementation recently merged in #10126. It is great to see code helping us with accessibility. Thanks @0618 and @telamonian and others for reviewing and merging it.

As a follow-up, here are some things I think we can improve with the implementation details.

For reference, the code lives in https://github.com/jupyterlab/jupyterlab/blob/8c608df4b2b4fee9d4e668cf3c9d37d439a8b122/packages/application/src/shell.ts#L349-L355 and https://github.com/jupyterlab/jupyterlab/blob/8c608df4b2b4fee9d4e668cf3c9d37d439a8b122/packages/application/src/shell.ts#L1578-L1652 and was introduced in https://github.com/jupyterlab/jupyterlab/pull/10126

The biggest comment is that in general, the `LabShell` class is meant to be very generic, and in general does not rely on specific extensions to be installed. It looks like the skiplink functionality assumes the file browser extension is installed (i.e., it assumes specific css that is an implementation detail of our core filebrowser): 

https://github.com/jupyterlab/jupyterlab/blob/8c608df4b2b4fee9d4e668cf3c9d37d439a8b122/packages/application/src/shell.ts#L1603-L1608

Instead, perhaps the LabShell could make a generic skiplink area or skiplink registry in which plugins can register links. Then the filebrowser plugin is the one responsible for registering the existing skiplink. Or perhaps we have a single other extension that populates this skiplink registry for all of the core extensions

A few other comments:

1. The pattern for Lumino widgets having event handlers is to attach them in the onAfterAttach handler, remove them in the onBeforeDetach handler. You can search the codebase for addEventListener to see lots of examples, like https://github.com/jupyterlab/jupyterlab/blob/aeaf7c9c348b970c898eb61821d4cd0d3367f8b3/packages/cells/src/widget.ts#L1176-L1202 (a side note - it does appear that we aren't consistently using onBeforeDetach, and sometimes use onAfterDetach. I think it makes most sense to use onBeforeDetach, but there may be other reasons like performance for using onAfterDetach. Either way, we should probably be consistent.)

2. The skip links handler has a dispose function, but if I am seeing things correctly, it would never be called. Lumino widgets that are in the lumino tree will have their dispose methods called, but no one really knows about the skiplink handler's dispose method.

Anyway, thanks again for pushing forward on this. It's really exciting to see accessibility getting more attention.

**Comment by 0618** [comment]
Thanks @jasongrout ! Those are great suggestions, which covers a lot things I was not sure before. Like how the SkipLink should behave like, the the eventListeners etc. 

I do have some more detailed questions and I'll ask you once I resume the work. Thanks!

**Comment by jasongrout** [comment]
@manfromjupyter helped me understand today that the end goal of skiplinks is to just link to main application areas (e.g., left, right, main, menu, bottom, etc.), not to specific hardcoded content. With that understanding, I don't think we need a registry after all for plugins to register specific content areas to skip to.

**Comment by jasongrout** [comment]
We are currently triaging issues for 3.1. Just confirming here that I'd still like to work on getting this in for 3.1.
