### ISSUE TITLE
Rename in simple mode review

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#10269]
I was looking through the renaming implementation recently merged in #10140. First, it is really great to see this feature. People have been asking for it for a long time. Thanks @cameron-toy and the reviewers for working on this.

For reference, here is the implementation: https://github.com/jupyterlab/jupyterlab/blob/8c608df4b2b4fee9d4e668cf3c9d37d439a8b122/packages/application/src/shell.ts#L1654-L1784

As a follow-up, here are some things I think we can improve with the implementation details.

The title handler introduces a new dependency for the application package on `@jupyterlab/docmanager`, just to have the function 'isValidFilename'. The application package is meant to be very generic, so I think if we have to introduce a dependency there, we should try to see if there is a more generic or extensible way to accomplish our goal. In this case, it is customizing the behavior of the widget title for DocumentWidgets. That is putting some assumptions in about how DocumentWidgets work that (a) may be hard to change later, and (b) we may want for things other than DocumentWidgets. Taking a step back and thinking about things very generically, fundamentally we just want a way to edit a widget's title. Perhaps we let the widget itself decide how to deal with edits to its title (and whether the title is even editable). At the application level, we could just ask the widget if we can edit its title, and if we can, we just set it to whatever the user gives us. The widget itself can then validate the new title and take any action it likes (such as renaming the document). The other nice thing the current implementation does is automatically select the root of the filename (without the extension), so perhaps a widget can provide that information as well (initial selection for editing).

Also, it seems that the title handler adopted some conventions from the skiplinks handler next to it in the code. I think some of my comments over in #10268 also apply here, like the following:

1. The pattern for Lumino widgets having event handlers is to attach them in the onAfterAttach handler, remove them in the onBeforeDetach handler. You can search the codebase for addEventListener to see lots of examples, like https://github.com/jupyterlab/jupyterlab/blob/aeaf7c9c348b970c898eb61821d4cd0d3367f8b3/packages/cells/src/widget.ts#L1176-L1202
2. The title handler has a dispose function, but if I am seeing things correctly, it would never be called. Lumino widgets that are in the lumino tree will have their dispose methods called, but no one really knows about the title handler's dispose method.

Thanks again for working on this.

**Comment by cameron-toy** [comment]
Thank you @jasongrout! These are all really good points--I'm always open to making things more extensible. Also, the title handler's dispose method is called in the dispose method of the LabShell. However, I do think it's confusing that the title handler class is a class that acts like a widget but follows only some widget conventions and isn't a `Widget`.

**Comment by jasongrout** [comment]
We are triaging issues/PRs for 3.1. I'm just confirming here that I'd like to help get #10309 in to fix this issue for 3.1.

**Comment by cameron-toy** [comment]
@jasongrout Yes, is there a way to re-run the tests? I fixed the package integrity issues in my repo but the tests haven't re-run.

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/10518
