### ISSUE TITLE
Can't install any jupyterlab extensions in docker image

### ISSUE THREAD

**Issue by yashali** [jupyterlab/jupyterlab#10272]
I am running docker build task in Azure pipelines on a pipeline agent that runs on an on-prem host. I am trying to "RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager".  

In the base image:
node=14.14.0
jupyter=1.0.0
jupyter-packaging = 0.7.12
jupyter-resource-usage=   0.5.1
jupyter_client  =   6.1.7
jupyter_console  =   6.2.0 
jupyter_core    =    4.7.0  
jupyter_server =  1.6.1  
jupyter_telemetry =   0.1.0 
jupyterhub =   1.3.0  
jupyterhub-base  =   1.3.0  
jupyterlab  =   3.0.12  
jupyterlab-git   =  0.30.0b2  
jupyterlab-templates  =    0.2.5
jupyterlab_code_formatter=1.4.5 
jupyterlab_pygments =      0.1.2  
jupyterlab_server   =      2.3.0   

Dockerfile looks like this:

`USER root`
`COPY files/.npmrc $HOME/.npmrc`
`RUN  jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager .....`

.npmrc looks like so:

`always-auth=true`
`strict-ssl=false`
`registry=https://pkgs.dev.azure.com/org-name/proj-name/_packaging/proj-name/npm/registry/`
`https-proxy=the-proxy-url`
`proxy=the-proxy-url`

The pipeline does the following tasks:

1. Runs npmAuthenticate task on .npmrc to edit the .npmrc file with the auth-token. This succeeds..
2. Next runs docker build. The Dockerfile instructs to copy this modified .npmrc to $HOME and tries to install lab extensions

Found this thread : https://github.com/jupyter-widgets/ipywidgets/issues/1982#issuecomment-468716770
We use jupyterlab v3. So a node>=12 is required. So I changed the Dockerfile to:

`USER root`
`COPY files/.npmrc $HOME/.npmrc`
`RUN  conda remove nodejs && conda install -c conda-forge nodejs=12 && conda list | grep nodejs &&\`
`jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager .....`

Tried this also: https://stackoverflow.com/a/52484330/3575135 . Didnt help

The normal "npm install @angular/cli" works. But the lab extensions are giving me a hard time. Nothing seems to be working at this point..

This is the error:

`ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid npm package`

Please help!

**Comment by jtpio** [comment]
Thanks @yashali.

Although the `jupyter labextension install` command should also work with JupyterLab 3.0, you might want to install `@jupyter-widgets/jupyterlab-manager` with `pip` or `conda` instead.

This extension should automatically be installed with `conda install -c conda-forge ipywidgets=7.6`, which doesn't require having `node` installed anymore.

**Comment by yashali** [comment]
@jtpio We have all of these extensions to be installed. I got jupyterlab-manager installed with pip. Then " jupyterlab-plotly" failed to install.. 

jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager \
                                 jupyterlab-plotly \
                                 jupyter-leaflet \
                                 jupyter-vuetify \
                                 jupyterlab-drawio \
                                 @jupyterlab/toc \
                                 private extensions... etc 
                                 
jupyterlab-plotly doesnt get installed if I remove "@jupyter-widgets/jupyterlab-manager"

**Comment by jtpio** [comment]
Looks like you might be able to install all the extensions mentioned above with pip or conda:

Have you tried something like the following?

```bash
pip install ipywidgets~=7.6 plotly ipyleaflet jupyterlab-drawio ipyvuetify
```

`@jupyterlab/toc` is now included in core JupyterLab by default.

**Comment by yashali** [comment]
I looked at this https://github.com/postmanlabs/npm-cli-login/issues/47#issuecomment-580102203 and copied the npmrc to /.npmrc instead of $HOME/.npmrc. It seems to have worked. The build will take another 2-4 hours to complete. Will test the image and close the issue if things work out! :) thanks! @jtpio

**Comment by yashali** [comment]
copied the npmrc to /.npmrc instead of $HOME/.npmrc. This worked
