### ISSUE TITLE
somebody help me out 

### ISSUE THREAD

**Issue by realKarthikNair** [jupyterlab/jupyterlab#10270]
hey there

in jupyterlab, switching to command mode and pressing "h" showed up all keyboard shortcuts which doesnt seem to show up in jupyterlab , i've tried googling but nothing regarding this has been found anywhere

help is much appreciated

**Comment by krassowski** [comment]
There is no such an overview of shortcuts currently available in JupyterLab. However, someone created a PDF and PNG overview as a cheat sheet which should help you in the meantime: https://github.com/Jakeler/jupyter-shortcuts. There is also https://github.com/jupyterlab/jupyterlab-shortcutui but it was not updated for JupyterLab 3.0 yet (https://github.com/jupyterlab/jupyterlab-shortcutui/issues/63).

<details>

For reference in classic Notebook the overview looked like this:

![Screenshot from 2021-05-19 15-30-04](https://user-images.githubusercontent.com/5832902/118830847-3012da80-b8b7-11eb-8483-7c8ea59ec0e8.png)

</details>

**Comment by agoose77** [comment]
You can also press <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>c</kbd> to bring up a search menu.

**Comment by realKarthikNair** [comment]
> There is no such an overview of shortcuts currently available in JupyterLab. However, someone created a PDF and PNG overview as a cheat sheet which should help you in the meantime: https://github.com/Jakeler/jupyter-shortcuts. There is also https://github.com/jupyterlab/jupyterlab-shortcutui but it was not updated for JupyterLab 3.0 yet ([jupyterlab/jupyterlab-shortcutui#63](https://github.com/jupyterlab/jupyterlab-shortcutui/issues/63)).
> 
> For reference in classic Notebook the overview looked like this:
> 
> ![Screenshot from 2021-05-19 15-30-04](https://user-images.githubusercontent.com/5832902/118830847-3012da80-b8b7-11eb-8483-7c8ea59ec0e8.png)


Thanks

**Comment by realKarthikNair** [comment]
> You can also press ctrl+shift+c to bring up a search menu.

Thank u
