### ISSUE TITLE
Jupyter Lab in Terminal

### ISSUE THREAD

**Issue by Shahin-rmz** [jupyterlab/jupyterlab#10283]
Hello 
Thanks for very helpful repo.
I am vim user, there is some repos that wanted to connect vim and Jupyter (although most of them work with Jupyter notebook),
Wanted to know if there is possibility to work 100% from Terminal?
it will be very time saving.
Could you please tell how is going on with Mouse less Jupyter lab functions?

- the main issue, is for searching the web, consuming the data and implementing the code, it should be no delay by using mouse.

thanks

**Comment by fcollonval** [comment]
@Shahin-rmz you may be interested by those projects:
- [Euporie](https://github.com/joouha/euporie)
- [nbterm](https://github.com/davidbrochart/nbterm)

**Comment by Shahin-rmz** [comment]
Thanks.
very interesting.
Please feel free to add more repos if you find.

**Comment by telamonian** [comment]
@fcollonval Those are both very cool. Especially nbterm, which I guess is brand new? Seems to have a goodly quantity of momentum behind it

**Comment by Shahin-rmz** [comment]
nbterm seems like a complete version of Jupyetr lab in Terminal, which is pretty much nice!
wish key bindings were configurable so I could make it more " my muscle memory friendlier".
But pretty happy with the interface and functionality.

**Comment by fcollonval** [comment]
> Especially nbterm, which I guess is brand new?

Indeed it is a recent work of @davidbrochart
