### ISSUE TITLE
Pass Configuration for JupyterLab extension

### ISSUE THREAD

**Issue by makammoun** [jupyterlab/jupyterlab#10287]
Hello,

I have a setup where jupyter notebook and jupyterLab are running on the same server.
I achieved this by enabling the jupyterlab server extension and then running jupyter notebook.
```
jupyter serverextension enable --py jupyterlab
```

I pass a `.py` configuration file on the server startup by running
```
jupyter notebook --config=<path-to-config>
```
But this configuration is only read by notebook and not by the jupyterLab extension.

I want to configure
```
c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False
```
because I am running this in a low memory environment and sometimes the build fails because of an out-of-memory error. I read that these settings might help with that.
I tried to put these parameters in the `.py` config file but it didn't work for me.

Are there any tips on how to achieve this?
Thank you 🙂

**Comment by krassowski** [comment]
If you are using JupyterLab 3.0+ then the settings file for JupyterLab (and nbclassic) has been migrated to `jupyter_server_config.py` and this might be the reason why your settings are not getting picked up. To migrate see: https://jupyter-server.readthedocs.io/en/latest/operators/migrate-from-nbserver.html

There might be also a need to adjust how you install/enable jupyterlab extension (`jupyter serverextension enable` vs `jupyter server extension enable`) and/or how you specify the config and/or start JupyterLab. It would help if you could describe your environment in more detail and show how you start JupyterLab.

**Comment by makammoun** [comment]
This is my `Jupyter --version` output
 ```
jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : not installed
ipython          : 7.16.1
ipykernel        : 5.5.5
jupyter client   : 6.1.12
jupyter lab      : 3.0.16
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 4.3.3
```

This is how I configure and start my server
```
jupyter serverextension enable --user --py jupyterlab
jupyter notebook --config=<path-to-my-config.py>
```
The configuration file includes a custom contentManager and some other settings like `display_url` and `port`

With this, both `/tree` and `/lab` are accessible from the same port which is my objective.

**Comment by agoose77** [comment]
Jupyter Server is a project to separate the Notebook part of Jupyter Notebook/Lab from the Server part. The new JupyterLab 3.x uses Jupyter Server, rather than the old notebook server *except* if you load `jupyter notebook`. So, for future-proofing you need to make the following changes:

* Change `jupyter notebook` to `jupyter nbclassic`
* Change `jupyter serverextension` to `jupyter server extension`

Now,  as to why it isn't working when you pass the settings via the commandline, I'm not sure; I can see that the settings are being passed to the builder, my best guess from looking at the source is that these are command-line-only settings; the `LabBuildApp` is a command-line application (only). It seems that the end-point that JupyterLab uses to trigger a build directly does not have any mechanism for specifying these parameters. 

I'd welcome someone a bit more knowledgeable like @blink1073 to perhaps weigh in here.

**Comment by telamonian** [comment]
@agoose77 I think I can claim at least a little authority, as the one who originally implemented the

```
c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False
```

options the OP mentioned.

@makammoun If you call the `LabBuildApp` directly via `jupyter lab build`, then you should be able to pass in the options like you're expecting

```
jupyter lab build --config=<path-to-config>
```

If you trying to set these options for indirectly triggered builds (eg the build that the jlab UI prompts the user for when an extension package changes), there is literally only one working way that I know of. The exact instructions are laid out as part of the [error message](https://github.com/jupyterlab/jupyterlab/blob/2437311390eb0c1e5350c03342c509476ae0ff91/jupyterlab/labapp.py#L88-L98) that gets shown whenever there's any build failure:

> You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:
>
>```
>c.LabBuildApp.minimize = False
>c.LabBuildApp.dev_build = False
>```
>
>If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:
>
>```
>jupyter --paths
>```

You have to put your `jupyter_config.py` file in one of the config dirs reported by `jupyter --paths` (probably just put it in the first config dir shown), and you absolutely **have** to name your config file `jupyter_config.py`

**Comment by telamonian** [comment]
As I recall, me and @blink1073 had to spend ~4 hours one day trying to debug and figure this out. He's the one who came up with the exact right magical config file name in the end.

**Comment by agoose77** [comment]
@telamonian thanks for jumping in. 

> If you trying to set these options for indirectly triggered builds (eg the build that the jlab UI prompts the user for when an extension package changes), there is literally only one working way that I know of. The exact instructions are laid out as part of the [error message](https://github.com/jupyterlab/jupyterlab/blob/2437311390eb0c1e5350c03342c509476ae0ff91/jupyterlab/labapp.py#L88-L98) that gets shown whenever there's any build failure:
> 
> > You can also disable these options for all JupyterLab builds by adding these
> > lines to a Jupyter config file named `jupyter_config.py`:
> > ```
> > c.LabBuildApp.minimize = False
> > c.LabBuildApp.dev_build = False
> > ```

Is this correct? I looked [at the end-points](https://github.com/jupyterlab/jupyterlab/blob/2437311390eb0c1e5350c03342c509476ae0ff91/jupyterlab/handlers/build_handler.py#L104) that Jupyter calls and they don't pass those flags to the ultimate build step.

**Comment by telamonian** [comment]
Putting the options in `jupyter_config.py` definitely works for any call to `juopyter lab build`.

But now we're getting into the deep dark weeds of path and config handling in `traitlets.Application`. So if the code that triggers the rebuild request on stale extensions never actually invokes the `LabBuildApp`, then of course the `LabBuildApp` specific options will never actually get applied.

@agoose77 If you really want to know you'll  have to look up the rebuild-on-stale code. I think it at least used to live in the extension manager package. If it invokes `LabBuildApp` in a subprocess, then the options will get applied, but if it interacts with `Builder` in a more direct way then maybe not

**Comment by makammoun** [comment]
Thank you for making me aware of the `jupyter server` project.

So I switched to `jupyter-server` and I tried the solution suggested by @telamonian but it didn't work

The first config folder in `jupyter --paths` output is `/home/ma.kammoun/.jupyter`
I have two files in there:
- `jupyter_config.py` includes `c.LabBuildApp.minimize = False` and `c.LabBuildApp.dev_build = False`
- `jupyter_server_config.py` includes my config

These are the commands I have launched
```
jupyter server extension enable --user jupyterlab
jupyter server extension enable --user nbclassic
jupyter server
```

After installing an extension from the JLab UI and clicking `rebuild`, the output in my terminal indicates that the build is minimized.
```
[I 2021-05-26 10:51:39.782 LabApp] Building jupyterlab assets (production, minimized)
```

I also tried:
- Deleting `jupyter_server_config.py` and running `jupyter server`
- Running `jupyter lab` directly
But the problem is still there

Am I missing something here?

**Comment by telamonian** [comment]
@agoose77 One of these days we need to get @Zsailer to give a lecture series on of the many lovely intricacies of pathing/config in `traitlets`. It would be excruciating, but probably quite useful

**Comment by telamonian** [comment]
@makammoun As me and @agoose77 are discussing, it may actually not be possible currently to set these options for builds triggered via the lab UI. The original use case for the `minimize` and `dev-mode` options were to act as minor band-aids for build failures that people running into on free-tier CI containers (typically only 2-4 Gb of ram). I guess we originally didn't really consider that interactive users would be operating in such constrained environments.

In any case I'll bring this up today at the dev meetings and see if anyone knows an easy way to make this happen. Unfortunately I suspect there may not any straightforward ones...

**Comment by agoose77** [comment]
@telamonian haha yes, probably. I recently went down that rabbit hole with [Literary](https://github.com/agoose77/literary) when I moved over to using traitlets to configure it. It was a bit of an eye opener! But, I'm now using it, so it can't have been too bad an experience ;)

**Comment by agoose77** [comment]
@makammoun and to re-summarise my question; what are you building in JupyterLab 3.x? Most of the big extensions should have moved over to the pre-built extension system (completely installed using pip/conda), but some installation instructions haven't yet been updated to reflect that.

**Comment by makammoun** [comment]
@agoose77 @telamonian Thank you for your investigation, you helped clear so many things for me.

@agoose77 We are trying to provide the freedom to our end-users to install any extension they want. For my testing, I just install an extension which I know will trigger a rebuild. So there's no particular thing that I'm trying to build on JupyterLab.

**Comment by agoose77** [comment]
Just to update this, one *ugly* solution would be to hack the configuration files that `JupyterLab` uses to control the build. I'm not advising you to do this, but in theory you can just patch `lib/python3.9/site-packages/jupyterlab/staging/package.json` to only ever perform a production minimized build.

**Comment by agoose77** [comment]
Alternatively, you can create a new `LabApp` subclass in a Python script, and hack at the `initialize_handlers` method to replace the` Builder` object  with your own subclass that allows you to configure the builds settings .

Or, you create a fork of JupyterLab and just patch it yourself!
