### ISSUE TITLE
Collapsible Code and Markdown Cells does not show up 

### ISSUE THREAD

**Issue by Rajiv2806** [jupyterlab/jupyterlab#10295]
Hi 

when ever i click in the blue collapse bar on code and Markdown cells, i stopped seeing the 3 dots collapsible section of that cell. 
My expected behaviour is i should see my collapsed cell as below image.

![6e6480b9856d24ea46efab96b85d8bc1bd34110e](https://user-images.githubusercontent.com/22934947/119647586-12f18500-be3e-11eb-85dd-8815773644a1.png)

But when i click in the blue line, i dont see the collapsed with the 3 dots. 
![Capture1](https://user-images.githubusercontent.com/22934947/119648433-13d6e680-be3f-11eb-8c22-d312c4d5f3f3.JPG)

In the example i have shown results for the output cell. Same happens for Code, Markdown cells too.

Note: I have recently upgraded my jupyter lab to 3.0.16, made some changes through advanced settings of my jupyter lab interface (i am not able to remember the changes clearly), and also i added some extensions through extension manager. Not sure if the issue is because of any of these changes.

**Comment by agoose77** [comment]
@Rajiv2806 I can still see the ellipses in JupyterLab 3.0.16. Can you try to reproduce the cause in a new virtual/Conda environment?

**Comment by Rajiv2806** [comment]
Hi,
@agoose77, if it's not because of the upgradition issue, maybe it is because of some changes in the "Advanced Settings" that I might have made. 
I am not able to remember the exact value that i might have reset. 

![Animation](https://user-images.githubusercontent.com/22934947/119654874-87c8bd00-be46-11eb-8dc5-76bef4bc7020.gif)

**Comment by agoose77** [comment]
I am not hugely familiar with all of the settings that we expose to configure the notebook. I would suspect that one of the settings you have changed has done this. 

When you launch JupyterLab with `--LabApp.user_settings_dir=$(mktemp -d)`, does that fix the issue?

**Comment by Rajiv2806** [comment]
No, i tried with the above command. It problem persists.

**Comment by agoose77** [comment]
Hmm. Does it happen if you create a new virtualenv?

**Comment by Rajiv2806** [comment]
I have been using the same virtual env for several months. 
And no new venv's are created before this problem popped up.
(Again, as mentioned above: I updated jupyer, made some changes in advance settings and activated/deactivated some extensions and stated seeing this issue.)

**Comment by agoose77** [comment]
@Rajiv2806 I'm asking you to create a new virtualenv environment and just install JupyterLab. If that doesn't show the issue, then you can sequentially add the different extensions until you find the cause.

**Comment by Rajiv2806** [comment]
Will update in a while.

**Comment by Rajiv2806** [comment]
@agoose77 : As mentioned i tried with the new virtual env. And it is working as expected. Please find the related info below. I am also attaching the jupyter environment where it is not working. 

![Working](https://user-images.githubusercontent.com/22934947/119808774-13ebea80-bf02-11eb-9cc6-4127bcec66ec.gif)


Below is old Jupyter where I don't see expected behavior. 

![NotWorking](https://user-images.githubusercontent.com/22934947/119808854-282fe780-bf02-11eb-8987-b643d4dca9be.gif)

**Comment by Rajiv2806** [comment]
Hi @agoose77 : 
I tried comparing both the jupyterlab environments. 
Looks like i have installed an extension called [jupyterlab_hidecode](https://github.com/lsst-epo/jupyterlab_celltools), which caused all the issue. 

Thank you so much for your support. 

![Capture2](https://user-images.githubusercontent.com/22934947/119813230-a5f5f200-bf06-11eb-8776-4ca132ab59ff.JPG)

Will be closing the issue here.

**Comment by agoose77** [comment]
Great, nice work.
