### ISSUE TITLE
Add linter rule for sorting import

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#10319]
The import sort order is not standardized. It will be good to force a stable order
by setting an eslint rule.

There is the sort-import rule: https://eslint.org/docs/rules/sort-imports

We could use those parameters:

```json
    "sort-imports": ["error", {
        "ignoreCase": false,
        "ignoreDeclarationSort": false,
        "ignoreMemberSort": false,
        "memberSyntaxSortOrder": ["none", "all", "multiple", "single"],
        "allowSeparatedGroups": true
    }]
```

**Comment by goanpeca** [comment]
This sounds like a great idea. Would that PR be massive with lots of changes? 🤔
