### ISSUE TITLE
Dead links on jupyterlab.io

### ISSUE THREAD

**Issue by chmp** [jupyterlab/jupyterlab#10312]
Not sure this is the right place, to post this, but while browsing the jupyterlab.io homepage I ran into two dead links on the [documentation page](http://jupyterlab.io/documentation):

- General / Contributing to Jupyter
- User Interfaces / JupyterLab

**Comment by krassowski** [comment]
I did not know about jupyterlab.io (and who operates it), but it looks like it was last updated in 2018 and at the time was just a mirror of main Jupyter site. I think that the official/up-to date site is https://jupyter.org/documentation

How did you end up there? Are there any links in the official Jupyter documentation pointing to the jupyterlab.io domain?

**Comment by chmp** [comment]
> How did you end up there? Are there any links in the official Jupyter documentation pointing to the jupyterlab.io domain?

I found it via duckduckgo, where it is the top result for the search term "jupyterlab" for me. 

> I think that the official/up-to date site is ...

Cool. Will keep it in mind :)
