### ISSUE TITLE
correct steps of uninstalling jupyter lab with all extensions

### ISSUE THREAD

**Issue by Arij-Aladel** [jupyterlab/jupyterlab#10318]
Jupyterlab always fails to build I have tried probably all the solutions mentioned in the issues .
May it is better to uninstall all at once then redo the installation process, so what are the right steps to do that, please?

**Comment by agoose77** [comment]
@Arij-Aladel why are you building JupyterLab, out of interest? Most extensions that people use should have pre-built versions on PyPI / conda-forge now.

**Comment by krassowski** [comment]
If you really need a blunt method to remove extensions you could use `jupyter --paths` to see where Jupyter stores your **data**, then you will find `labextension` directory in one of the listed paths and you could remove it (or better move it to a safe place so you have it as a backup), and then remove `jupyter\lab\settings\build_config.json` and `jupyter/lab/extensions/`. I obviously recommend against doing so as it might break something, unless it is the last resort.

**Comment by goanpeca** [comment]
Should there be a CLI option to be able to do this?

**Comment by Arij-Aladel** [comment]
@agoose77 Actually I am not an expert these are my new steps , I just do as I see from the  messages that popup from jupyter, I have Linux (Ubuntu 20.04) OS. I tried to install jupyter lab , that was Ok, then I wanted to make my life easier and install extensions  for example to autocomplete the code , debug etc.,  so simply searched on the YouTube to see how to do that and did, but after installing the extensions messages from jupyter started to popup saying the the build process was failed, I did what I supposed logical and searched again on the internet to find why is that happening but I could not figure out. 
@krassowski  I have a uestion please,I did not understand what do you mean by "break something"?  If I have my work and files in separate folder , what will uninstalling jupyterlab and its extentions and reinstalling every thing affect?

**Comment by Arij-Aladel** [comment]
close for no response

**Comment by krassowski** [comment]
Hi @Arij-Aladel sorry for lack of response - I had nothing to add.

> I have a uestion please,I did not understand what do you mean by "break something"? If I have my work and files in separate folder , what will uninstalling jupyterlab and its extentions and reinstalling every thing affect?

I mean that there **might** be something that **might** break **if** you remove all extensions using the brute-force method of removing the file and directory that I mentioned. I am not aware of anything that would, but given that extension authors and the extension system does not expect users to be deleting files just like that, there might be some logic implemented by third-party extension that stores some information there or depends on these locations in any other way. I meant to recommend caution. If there was a specific thing that I knew would break I would mention it.
