### ISSUE TITLE
Name File Dialog: clicking on "Don't ask me again" should check the box

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#10317]
### Problem

 
With the new "Name File" dialog added in #10043, clicking on "Don't ask me again" doesn't tick the checkbox:

https://user-images.githubusercontent.com/591645/120283391-6c810600-c2bb-11eb-8a3f-268767742593.mp4

### Proposed Solution

It's usually common practice to check the box associated to the label when clicking on the label.
Ideally the Name File dialog should also behave like that.

**Comment by goanpeca** [comment]
@jess-x seems like something worth fixing :)

**Comment by jess-x** [comment]
agree, I am on it :)
