### ISSUE TITLE
Typo in JupyterLab documentation

### ISSUE THREAD

**Issue by VladimirFokow** [jupyterlab/jupyterlab#10328]
On the FAQ page of JupyterLab documentation on:
https://jupyterlab.readthedocs.io/en/stable/getting_started/faq.html

There is a typo there: "Javsacript" is written instead of "Javascript".

**Comment by jasongrout** [comment]
Looks like that typo also happens in a comment elsewhere: https://github.com/jupyterlab/jupyterlab/search?q=Javsacript

Thanks for pointing this out. Labeling this as a good first issue.

**Comment by manavendrasen** [comment]
Hey! I would like to fix this. This will be my first issue :)

**Comment by manavendrasen** [comment]
Let me know if that's ok.

**Comment by VladimirFokow** [comment]
Thanks!
