### ISSUE TITLE
Contextual Help menu cannot be moved to the side

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10334]
Now that #10201 is merged it is not possible to move Contextual Help to side. Opening this ticket to ensure it get fixed before 3.1 as this is a major usability regression.

> I am concerned about the inability to move the Contextual Help to the side. I use it this way a lot, and I believe that other users with monitors which are wider rather than taller use it this way too. This is a substantial restrictive change, and I think that it might annoy users.
> 
> But maybe I am doing something wrong? Screencast from binder test below:
> 
> ![contextual-to-side](https://user-images.githubusercontent.com/5832902/118023803-e0cc2780-b355-11eb-8478-b781e0abeb7a.gif)
> 
> Edit: though I obviously love the idea of having the botom panel designated for specific features to land there by default.

_Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab/issues/10201#issuecomment-839991277_

> > This is gonna be tricky if we don't allow all widgets to move from that area to the main area.
> 
> @fcollonval I agree! At the moment, I don't see a reason for not having all widgets being able to move in or out of this area. I understand the idea is to have a new widget area to provide a familiar experience from other IDEs and to group similar outputs, but since all other widget areas allow for the user to personalize I think it would be unpleasant to have a new widget be the only widget area in the interface to break the pattern. It still makes sense to me to change these outputs to default to this new area, but I also think it makes sense to be able to move them into any other widget area. 
> 
> I think this is what @bollwyvl is saying here
> > Further, i'd rather see the all the areas become equivalent drop targets, rather than further constraining it.
so I think it's not just me thinking this. Does that make more sense?

_Originally posted by @isabela-pf in https://github.com/jupyterlab/jupyterlab/issues/10201#issuecomment-847385951_

**Comment by fcollonval** [comment]
@krassowski following your comment I revert that change in the mentioned PR (after taking the latest screenshots to have two panels). So for now only the log console will be set there.

**Comment by krassowski** [comment]
Thanks, sorry for the noise then!

**Comment by fcollonval** [comment]
No prob better to be sure than to let slip a regression :wink:
