### ISSUE TITLE
Replace Menu Items

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#10343]
### Problem

When developing a newer version of a similar feature in lab, you often want to override the current behavior of a menu item. For example, I may create a better "Open from Path..." that lets you also open from a URL or a path. Today I can only appended yet another option to the File menu, which is confusing for users. Instead, I want to replace "Open from Path..." with "Open from Path or URL..." so users have just one option.

### Proposed Solution

Menu items should be able to be removed or replaced via an API.

**Comment by fcollonval** [comment]
With #10254 , it should be possible to disable an core menu entry. So you can plug yours. This will be more reliable than adding the ability of removing/replacing item.

Two comments:
- I did not try to do it
- You actually can remove an item from the menu by using the [`removeItem`](https://jupyterlab.github.io/lumino/widgets/classes/menu.html#removeitem) method of `Menu` widget. For the context menu, the menu widget is accessible as [`menu` attribute](https://jupyterlab.github.io/lumino/widgets/classes/contextmenu.html#menu). See for example:
https://github.com/jupyterlab/jupyterlab/blob/a8dff39a1a2be850a80861e05145e763079b8794/packages/apputils/src/menufactory.ts#L129-L137

**Comment by jtpio** [comment]
There is now documentation about this feature: https://jupyterlab.readthedocs.io/en/stable/extension/extension_points.html?#settings-defined-menu

@mlucool were you able to check whether this feature works for you in JupyterLab 3.1 / 3.2?

**Comment by mlucool** [comment]
Thanks for checking in @jtpio. Yes and no.

This works in 3.x:
```
    activate: async (
        app: JupyterFrontEnd,
        commandPalette: ICommandPalette,
        mainMenu: IMainMenu
    ) => {
....
        const prevOpenItem = mainMenu.fileMenu.items.find(
            (i) => i.type === 'command' && i.command === 'filebrowser:open-path'
        );
        if (prevOpenItem) {
            mainMenu.fileMenu.menu.removeItem(prevOpenItem);
        }
```

But `menu` in `mainMenu.fileMenu.menu` is deprecated/removed in v4 ([ref](https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/ui-components/src/components/menu.ts#L59)). Is there a future proof way to do this?

**Comment by fcollonval** [comment]
@mlucool since 3.1, you can set the following in the `overrides.json` file or your custom extension to hide that particular entry without coding anything:

```json
{
  "jupyter.lab.menus": {
  "main": [
    {
      "id": "jp-mainmenu-file",
      "items": [
        {
          "command": "filebrowser:open-path",
          "disabled": true
        }
      ]
    }
  ]
}
```

This will forbid the menu item associated to the command `filebrowser:open-path` to be created.

**Comment by mlucool** [comment]
Using 3.2.2 I don't see the `overrides.json` or adding that schema of my plugin solution working. What can I provide to debug? (I know my overrrides.json is being picked up as other settings are being overwritten).

**Comment by jtpio** [comment]
> What can I provide to debug?

@mlucool maybe checking the request to `overrides.json` or the plugin setting in the dev tools network tab? Just to make sure the content is correctly fetched.

Otherwise it could be related to a missing `"properties": {}` entry in the settings, which could lead to the menus defined in `jupyter.lab.menus` to not be picked up (to be confirmed but I remember seeing something like this when overriding menus in https://github.com/jupyterlab/retrolab/pull/289).

**Comment by mlucool** [comment]
What request should I see it coming in?

I know this is picking up some settings in override.json as it picks up:
```
"@jupyterlab/filebrowser-extension:browser": {
        "navigateToCurrentDirectory": true,
}
```

**Comment by fcollonval** [comment]
@mlucool I created a small gist to demonstrate the customization: https://gist.github.com/fcollonval/facfadcd926621a84556a040aac71a8f

> The run menu is disabled as well as the open path command in file menu.
> I try to change the rank of the tab menu but strangely, it did not work when specifying it as overrides. Although it works if you set it as user settings - it sounds like a bad order to pick default values.

**Comment by mlucool** [comment]
Thanks @fcollonval - that was perfect!
