### ISSUE TITLE
Prepare JupyterLab for use with Jupyter Releaser

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#10340]
Prepare JupyterLab for use with [`jupyter_releaser`](https://github.com/jupyter-server/jupyter_releaser).

Prerequisities:

- Convert `jlpm patch:release` to `jlpm bumpversion patch` so we have a single bump version command.
- Publish packages using verdaccio during the Python build stage so we can use them in the `check_release` step
  when updating core mode and testing the release (we don't actually publish in `check_release`).  This means we don't have to wait until the packages
  propagate to the CDNs when doing the actual release.  Required changes:
  - Add scripts to start/stop [verdaccio](https://github.com/facebook/create-react-app/blob/7e4949a20fc828577fb7626a3262832422f3ae3b/tasks/local-registry.sh)
  - Add a script to replace verdaccio registry links with public registry links in the yarn lock file
  - Separate out the tag fixing [logic](https://github.com/jupyterlab/jupyterlab/blob/f0790b3ffd187b7dc923156b8ae227855abecefb/buildutils/src/publish.ts#L44)
    into a separate script
  - Remove the check for [published JS packages](https://github.com/jupyterlab/jupyterlab/blob/7237fdccca3dfb2191942403b8f2c153c4525fc2/buildutils/src/prepare-python-release.ts#L39)
- Then we can use the following `jupyter-releaser` config:
  - `bump-version-cmd`: `jlpm bumpversion --yes`
  - `before-build-python`: `start-verdaccio`, `npm publish:js --yes`, `npm prepare:python-release`, `stop-verdaccio`
  - `after-build-python`: `start-verdaccio`, `release_test`, fixup registry links in yarn lock, `stop-verdaccio`
  - `after-publish-assets`: fixup npm dist tags
- Replace `linkcheck` job with `jupyter_releaser` [config](https://github.com/jupyter/notebook/blob/6fe9755971dba3357054766806d56cb8c6c1bca7/pyproject.toml#L14)
- Add the changelog markers
- Add `check_manifest` [config](https://github.com/jupyter/notebook/blob/6fe9755971dba3357054766806d56cb8c6c1bca7/pyproject.toml#L6)
- Replace the `release_check` job with a [`check_release`](https://github.com/jupyterlab/lumino/blob/5c1028dc37fa027612df8351915c20105c50c293/.github/workflows/tests.yml#L82) build step

**Comment by jtpio** [comment]
With a couple of `4.0.0` alpha releases made with the releaser, maybe this can be closed?

cc @blink1073

**Comment by blink1073** [comment]
I am waiting until I make a release in 3.1.x and verify that the forwardport PR works, which I plan to do next week

**Comment by jtpio** [comment]
I believe this one can now be closed, with https://github.com/jupyterlab/jupyterlab/pull/11072 as an example of a forward port PR.

**Comment by blink1073** [comment]
Agreed!
