### ISSUE TITLE
half of jupyter lab screen appears to be gray

### ISSUE THREAD

**Issue by stigersh** [jupyterlab/jupyterlab#10365]
Hi,
Basically I have the same as in [git issue](https://github.com/jupyterlab/jupyterlab/issues/3329)
but the issue is closed and running `jupyter labextension install @jupyter-widgets/jupyterlab-manager` didn't work.
I installed jupyter lab on my M1 Mac with Anaconda, jupyter lab 3, when I started running a notebook the view messed up to half screen and I couldn't fix it by unstalling nodejs and jupyterlab-manager and whatever was suggested..
Please help..
<img width="1437" alt="Screenshot 2021-06-08 at 10 41 04" src="https://user-images.githubusercontent.com/3474639/121153411-55579080-c846-11eb-9ef3-5064770abb3b.png">

**Comment by jasongrout** [comment]
I'd suggest trying to narrow this down by following the guidelines in https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html

**Comment by stigersh** [comment]
> I'd suggest trying to narrow this down by following the guidelines in https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html

Hi thanks, I went through the link, and it's reproduced in the test environment, isn't reproduced for jupyter notebook mode, and reproduced for incognito browser settings.
I think it first happened after I ran the first notebook after installation which saved and loaded an html:
<img width="678" alt="Screenshot 2021-06-09 at 13 51 30" src="https://user-images.githubusercontent.com/3474639/121349480-d9cf0f80-c929-11eb-97ae-5fa9ff9ef8c3.png">

Afterwards I tried reinstalling jupyter lab from scratch and even then it opened in the browser with the gray screen

**Comment by krassowski** [comment]
Thanks for follow-up @stigersh. It might help to narrow it further down if you could add:

1. name and version of you browser,
2. name of your operating system (Mac/Windows/Linux)
3. the output of `jupyter labextension list`
4. logs from the developer console in your browser (please see [instructions here](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#how_to_open_the_devtools_in_your_browser) on how to open the console in various browsers)

As it might be a browser-specific issue, it would be also ideal if you could test with a different browser (e.g. if you see this in Chrome then try out Firefox).

**Comment by stigersh** [comment]
Hi Thanks for the answer, here is the info:
1. chrome Version 90.0.4430.212 (Official Build) (arm64)
2. MacOS BigSur version 11.4, chip Apple M1
3. output of `jupyter labextension list:`
`JupyterLab v3.0.16
/Users/annashtengel/anaconda3/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /Users/annashtengel/anaconda3/share/jupyter/lab
`
4. logs for errors: 
```
default.js:40 WebSocket connection to 'ws://localhost:8889/terminals/websocket/1' failed: 
_createSocket @ default.js:40
default.js:71 Terminal websocket closed: undefined
_onWSClose @ default.js:71
default.js:228 Connection lost, reconnecting in 0 seconds.
_reconnect @ default.js:228
default.js:254 WebSocket connection to 'ws://localhost:8889/terminals/websocket/1' failed: WebSocket is closed before the connection is established.
_clearSocket @ default.js:254
VF.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
jupyter-threejs.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
21embed-amd.js:346 Falling back to https://unpkg.com/ for jupyter-threejs@^2.1.0
index.js:1 THREE.WebGLRenderer 97
29523.fa256ee012d38a89b65a.js:1 Error: widget model not found
    at x.get_model (523.fa256ee012d38a89b65a.js:1)
    at u.renderModel (523.fa256ee012d38a89b65a.js:1)

```
<img width="538" alt="Screenshot 2021-06-14 at 13 53 01" src="https://user-images.githubusercontent.com/3474639/121888400-3eb6ab00-cd18-11eb-9d2a-efc3ddf559ee.png">



tried in firefox and the same happens

**Comment by stigersh** [comment]
This is the notebook by the way, which works fine in jupyter notebook on my Mac.
[link to notebook](https://geometryprocessing.github.io/blackbox-computing-python/geo_viz/)
