### ISSUE TITLE
docker stack for jupyterlab

### ISSUE THREAD

**Issue by donaldbraman** [jupyterlab/jupyterlab#1036]
If you have time to write up a Dockerfile, a docker stack would make it very easy for folks to help kick the tires & adopt in heterogenous environments. I can't wait to test it out!

**Comment by blink1073** [comment]
Hi @donaldbraman, thank you for the suggestion.

I don't have docker set up myself, but a compelling example could be built on top of the [datascience-notebook](https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/Dockerfile) which installs and enables jupyterlab on top of that image.

**Comment by donaldbraman** [comment]
I'll give it a shot.  I love those opinionated stacks.

**Comment by ellisonbg** [comment]
Thanks!

**Comment by rushtehrani** [comment]
Thanks to this [PR](https://github.com/jupyter/docker-stacks/pull/258), this is as simple as creating the following `Dockerfile`:

```sh
FROM jupyter/datascience-notebook

RUN pip install jupyterlab && \
    jupyter serverextension enable --py jupyterlab

CMD ["start.sh", "jupyter", "lab"]
```

And building the image.  I have tested this and it works and I'll be more than happy to provide a PR if it makes sense.

**Comment by donaldbraman** [comment]
Sorry I dropped the ball -- thanks for doing this! This will make it easy and fun to play with jupyterlab!

**Comment by parente** [comment]
I think this issue can be closed. JupyterLab is part of the `jupyter/base-notebook` image which means it's available in every Docker stack. Every README will soon have a small example about how to launch the stacks with lab instead of notebook.
