### ISSUE TITLE
jupyterlab 3.0 doesn't support for collapsing notebook sections via the ToC

### ISSUE THREAD

**Issue by icankeep** [jupyterlab/jupyterlab#10361]
## Description

jupyterlab 3.0 doesn't support for collapsing notebook sections via the ToC

toc extension pr: https://github.com/jupyterlab/jupyterlab-toc/pull/103

jupyterlab 3.0

![image](https://user-images.githubusercontent.com/39434627/121134245-c22e5300-c865-11eb-9c7e-46fcff97b7fc.png)

jupyterlab 2.2.4  install toc extension

![image](https://user-images.githubusercontent.com/39434627/121134311-d70ae680-c865-11eb-92d8-07df79d75842.png)

**Comment by krassowski** [comment]
Hi @icankeep thanks for opening this issue. I have a good news: this feature is still there! However, since https://github.com/jupyterlab/jupyterlab/pull/9275 you need to click on the blue bar rather than on an arrow.

@marthacryan: should we think about discoverability of this feature (e.g. add a small arrow on hover), or would adding a gif from the PR that introduced this change to the documentation be enough?

Also CC @isabela-pf

**Comment by icankeep** [comment]
@krassowski  I have tried it, clicking the blue bar does not collapse the code. But the previous toc works

**Comment by icankeep** [comment]
just like this gif

![](https://user-images.githubusercontent.com/2643044/66435384-8e888f00-e9d9-11e9-9b33-5d259cf7d387.gif)

**Comment by krassowski** [comment]
I see. Thanks for the GIF! If I remember correctly, this feature was deemed to be too [confusing behaviour]( https://github.com/jupyterlab/jupyterlab-toc/issues/123) and was changed to opt-in in https://github.com/jupyterlab/jupyterlab-toc/pull/132. However it seems to me that it is not possible to enable this feature in the TOC version in JupyterLab core indeed.

In the meantime you may be interested to check out the generic function for collapsing cells as implemented in https://github.com/jupyterlab/jupyterlab/pull/10260 which will arrive in JupyterLab 3.1. Would this be good enough for your use case or would you still prefer to have it also available in the TOC?

**Comment by icankeep** [comment]
> In the meantime you may be interested to check out the generic function for collapsing cells as implemented in #10260 which will arrive in JupyterLab 3.1

this commit is great, but I think it's more convenient to collapse the code via toc. Is it possible to add this feature in the future?
If not, I'm looking forward to the 3.1 release, thank you
