### ISSUE TITLE
Visual regression introduced in #10127

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#10375]
This is indeed visible when pulling the report from the commit (https://github.com/jupyterlab/jupyterlab/commit/d3915f659e76fedd0516da92925431e3e0b3c17b) that merged #10127: 

https://github.com/jupyterlab/jupyterlab/runs/2775919871

We can see the difference before and after:

https://user-images.githubusercontent.com/591645/121357917-7dbcb900-c932-11eb-9f2a-3d62593e4d57.mp4

_Originally posted by @jtpio in https://github.com/jupyterlab/jupyterlab/issues/10372#issuecomment-857669625_

**Comment by goanpeca** [comment]
Is this different from https://github.com/jupyterlab/jupyterlab/pull/10372 ?

**Comment by jtpio** [comment]
> Is this different from #10372 ?

Yes it's the follow-up issue to fix the visual regression.

**Comment by goanpeca** [comment]
:+1:
