### ISSUE TITLE
Add a screenshot for each of the examples

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#10377]
### Problem

At the moment it's a bit difficult to get an idea of what the examples in the `examples/` folder look like: https://github.com/jupyterlab/jupyterlab/tree/master/examples

For example browsing the `console` example just gives a list of files, but it would be great to have a README there:

![image](https://user-images.githubusercontent.com/591645/121385727-a7350f00-c949-11eb-9298-6874c6f3c052.png)
 

### Proposed Solution

Add a README with a screenshot to each of the example.

There is of course the risk of the screenshot being out-of-date at some point. But maybe this could be automated with `galata`.

**Comment by goanpeca** [comment]
Great idea @jtpio.

>But maybe this could be automated with galata.!

Yes :)

**Comment by krassowski** [comment]
In addition to examples in `examples/`, what do you think about moving examples which are already in the docs and to there? 

For example the add [notebook button](https://jupyterlab.readthedocs.io/en/stable/extension/notebook.html ) example got out of date (the font awesome icon no longer shows up). We could just embed source code from appropriate file into the documentation which is easy with MyST I believe (and which would also ensure it is formatted according to the current linter rules). Not sure if this is the best solution, but it is a solution.
