### ISSUE TITLE
Visual regression: border of the main area shrank

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10387]
## Description

The main area border is now smaller which looks less appealing and strange. <s>My hunch is that this is caused by #10127</s>.

## Reproduce

**Before (stable):**

![Screenshot from 2021-06-11 11-50-39](https://user-images.githubusercontent.com/5832902/121683980-0152e300-cab6-11eb-8510-7c17b1599724.png)

**After (master):**

![Screenshot from 2021-06-11 13-07-44](https://user-images.githubusercontent.com/5832902/121684007-09ab1e00-cab6-11eb-8f87-bedba3daf7ff.png)

## Expected behavior

The visuals are restored.

**Comment by fcollonval** [comment]
Actually I'm the one to blame :sweat_smile:  - I miss that one when moving the down area panel to make it full width.
See final screenshots in https://github.com/jupyterlab/jupyterlab/pull/10201#issuecomment-852835206

**Comment by krassowski** [comment]
Yes, just noticed this:

https://github.com/jupyterlab/jupyterlab/pull/10201/files#diff-c79b43ad4074f00ee71f9afc7d4d4cfc20ddd242a80367d2b52a0835254f81b1L34-L41

**Comment by krassowski** [comment]
We all missed it in the review but this is where the visual regression tests will come in handy now ;)

**Comment by fcollonval** [comment]
Do you want to push a fix?

**Comment by krassowski** [comment]
Feel free to go ahead - you know this part better after #10201 I assume; I did not start any work other than dissecting regressions I got after upgrading my work env to get the debugger working :)

**Comment by fcollonval** [comment]
> Feel free to go ahead

I'll do

Thanks for the analysis
