### ISSUE TITLE
Watch mode broken

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#10389]
## Description

I cannot run jupyter lab in watch mode - it get stuck at the `watching files for updates.`... And does not open the web page.
Commit hash: 97fd1a19b
## Reproduce

1. `jlpm install`
2. `jlpm run build`
3. `jupyter lab --dev-mode --watch`

## Expected behavior

watch mode is working

## Context

- Operating System and version: Debian 11
- JupyterLab version: master

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by echarles** [comment]
Same here, reverted a few commit back and it works (don't remember the exact commit)

**Comment by fcollonval** [comment]
I'm looking to isolate the commit

**Comment by fcollonval** [comment]
If I revert that commit locally, the watch mode is working again.

**Comment by jtpio** [comment]
Maybe it's related to the `index.css` -> `theme.css` renaming.
