### ISSUE TITLE
[JL 2.2.6] Invalid hook warning in LabIcon component

### ISSUE THREAD

**Issue by rohit-guitar** [jupyterlab/jupyterlab#10396]
Hi folks, 

I am getting stuck at invalid hook warning in LabIcon component. In my project jupyterlab and all of the extensions are my dependencies and I am instantiating a new jupyterlab application in my index file. Everything is working except LabIcon component, it's a class component but using hooks which is anti-pattern for hooks. When i run jupyter lab from conda it works fine but in my own webapp it is complaining about Invalid hooks. 

Any suggestions will be great help thanks. 

```
export class LabIcon {
    constructor() {
        this._initReact();
    }
    _initReact(displayName) {
        const component = React.forwardRef((props = {}, ref) => {
            const _a = Object.assign(Object.assign({}, this._props), props), { className, container, label, title, tag = 'div' } = _a, styleProps = __rest(_a, ["className", "container", "label", "title", "tag"]);
            // set up component state via useState hook
            const [, setId] = React.useState(this._uuid);
            // subscribe to svg replacement via useEffect hook
            React.useEffect(() => {
                const onSvgReplaced = () => {
                    setId(this._uuid);
                };
                this._svgReplaced.connect(onSvgReplaced);
                // specify cleanup callback as hook return
                return () => {
                    this._svgReplaced.disconnect(onSvgReplaced);
                };
            });
            // make it so that tag can be used as a jsx component
            const Tag = tag;
            // ensure that svg html is valid
            if (!(this.svgInnerHTML && this.svgReactAttrs)) {
                // bail if failing silently
                return React.createElement(React.Fragment, null);
            }
            const svgComponent = (React.createElement("svg", Object.assign({}, this.svgReactAttrs, { dangerouslySetInnerHTML: { __html: this.svgInnerHTML }, ref: ref })));
            if (container) {
                Private.initContainer({ container, className, styleProps, title });
                return (React.createElement(React.Fragment, null,
                    svgComponent,
                    label));
            }
            else {
                return (React.createElement(Tag, { className: classes(className, LabIconStyle.styleClass(styleProps)) },
                    svgComponent,
                    label));
            }
        });
        component.displayName = `LabIcon_${displayName}`;
        return component;
    }
}
```

**Comment by fcollonval** [comment]
@rohit-guitar I don't know where your snippet is coming from. But looking at the 2.2.x branch code, I found:

https://github.com/jupyterlab/jupyterlab/blob/9a8dadf59424ed2a6ff2a3c84001d46e37104d75/packages/ui-components/src/icon/labicon.tsx#L252

This means an attribute of the `LabIcon` class is a react component (hence this is not an anti-pattern).

Regarding the error, [React documentation](https://reactjs.org/warnings/invalid-hook-call-warning.html) lists three reasons for the error:

    You might have mismatching versions of React and React DOM.
    You might be breaking the Rules of Hooks.
    You might have more than one copy of React in the same app.

Did you check there is only one copy of React in the bundle?

**Comment by rohit-guitar** [comment]
So I have the force resolution for the react and react-dom version in my package.json
```
{
    "resolutions": {
        "react": "~16.9.0",
        "react-dom": "~16.9.0"
    }
}
```

So I don't that could cause the issue ? 
@fcollonval So you found the right branch and the package. It's version 2.2.x and file LabIcon.tsx.
But _initReact function is returning a functional component inside a class component. 
Don't you think that's anti pattern ?

**Comment by rohit-guitar** [comment]
Issue got resolved by resolving the dependency and making sure there is only one react app running. Yarn resolutions saved my day thanks.
