### ISSUE TITLE
Completer places cursor in wrong position after dot complete (master)

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10391]
## Description

Probably follow up after #10234 is needed. Any thoughts @dmonad?

## Reproduce

0. Using Python kernel
1. Enter `dict.` into a cell
2. Press <kbd>Tab</kbd>
3. Select any completion
4. See the cursor still remaining after the dot rather than at the end of the chosen method

![completer-cursor-issue](https://user-images.githubusercontent.com/5832902/121724522-e1d0b000-cadf-11eb-8902-0727e10c4ab1.gif)

## Expected behavior

The cursor caret lands after the chosen method i.e. `dict.clear|` (as it does in stable version) rather than `dict.|clear`

## Context

- Browser and version: Chrome
- JupyterLab version: 3.1.0a12 / master

**Comment by dmonad** [comment]
Thanks for the report, I'll work on this!

**Comment by krassowski** [comment]
This is also happening on `from ... import ...`:

![from-import](https://user-images.githubusercontent.com/5832902/125197673-98968c00-e256-11eb-9f44-c2d6596f53b1.gif)
