### ISSUE TITLE
Julia file does not have an icon

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10392]
## Description

In JupyterLab 3.1.0a12 "Julia file" entry in the launcher is missing a dedicated icon:

![Screenshot from 2021-06-11 18-50-19](https://user-images.githubusercontent.com/5832902/121729142-09c31200-cae6-11eb-9b77-759f28c22f58.png)

While both Python and R have an icon. It might be nice to add an icon for Julia too. The same icon as used by IJulia might be fine, but it would be good to check that it renders well in the file browser too:

![Screenshot from 2021-06-11 18-52-38](https://user-images.githubusercontent.com/5832902/121729307-3b3bdd80-cae6-11eb-9548-ec4c79f140f9.png)

For reference the Python icon stored in:

https://github.com/jupyterlab/jupyterlab/tree/master/packages/ui-components/style/icons/filetype

imported in:

https://github.com/jupyterlab/jupyterlab/blob/4817dbc6b15081c7d45080f74151b48f949a026b/packages/ui-components/src/icon/iconimports.ts#L64

and created in:

https://github.com/jupyterlab/jupyterlab/blob/4817dbc6b15081c7d45080f74151b48f949a026b/packages/ui-components/src/icon/iconimports.ts#L143

and used to define it as one of default file types in:

https://github.com/jupyterlab/jupyterlab/blob/dbdefed9db9332381fe4104bdf53ec314451951f/packages/docregistry/src/registry.ts#L1382-L1387

**Comment by shngt** [comment]
Hi, is there a preference in terms of resolution? Most of the other icons seem to be either 16x22 or 16x24, but I do see 16x295 for React and 16x512 for HTML5 as well.

**Comment by krassowski** [comment]
It is just a convention that the width is set to 16px and the then the default height becomes matched to that (so r-kernel is 16x16 as it has rectangular view box of 22x22, html becomes 16x16 as it also has a rectangular view box but of 512x512). There is no preference about the view box dimensions currently I think.

**Comment by yash112-lang** [comment]
Hello @krassowski, is this issue is still open. I want to work on this issue. I am new to open source & want to contribute to the community.

**Comment by krassowski** [comment]
Hi you are certainly welcome to. I don't know if @shngt started something already but usually an issue is not considered taken untill there is a (possibly draft) pull request or someone is assigned to it, so unless we get a response from @shngt feel free to prepare a pull request yourself.

If you both happen to prepare a PR  at the same time that's also great - it means that you can cross check your solutions and one of you would contribute a review of the other one which is as valuable :)

**Comment by shngt** [comment]
Yes, please feel free to work on this! I started to take a look but the svg file I found isn't getting encoded/decoded properly (at least I think so). I'll continue to investigate what's going on when I have some time

**Comment by krassowski** [comment]
Closing as implemented in #10397. Thank you @shngt, and congrats on your first contribution to JupyterLab :)

**Comment by shngt** [comment]
Thank you @krassowski ! :)
