### ISSUE TITLE
Using arrows in file dialog and others is broken

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10394]
## Description

Using arrows is not possible in the file browser input field since merging #10349.

## Reproduce

1. Open rename dialog
2. Try to use arrow keys in the input field
3. See buttons getting focus instead

![input-bug](https://user-images.githubusercontent.com/5832902/121730812-12b4e300-cae8-11eb-9710-31e9ccbf8f7c.gif)

## Expected behavior

Buttons do not steal focus from input fields

## Context

- Browser and version: Chrome
- JupyterLab version: 3.1.0a12

**Comment by krassowski** [comment]
@jahn96 would you like to look into this one? This should be fixable with a simple guard checking if the currently focused element is one of the buttons and otherwise aborting.

**Comment by jahn96** [comment]
Yes! I am looking into it right now. Thank you for catching the bug!
