### ISSUE TITLE
Jupyter Forum (discourse) does not open correctly in 3.1.0.a12

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10398]
## Description

In Chrome and Firefox selecting `Help` → `Jupyter Forum` from the menu results in "Refused 

This menu entry was requested in #8678 and introduced in #9892

## Reproduce

1. Open "Help" menu
2. Select "Jupyter Forum"
3. See error "discourse.jupyter.org refused to connect."

![Screenshot from 2021-06-13 10-35-01](https://user-images.githubusercontent.com/5832902/121802238-4c463500-cc33-11eb-965b-756593f3d514.png)

![Screenshot from 2021-06-13 10-36-32](https://user-images.githubusercontent.com/5832902/121802246-4ea88f00-cc33-11eb-9950-95306b0f790b.png)

## Expected behavior

The discourse is configured to allow embedding and opens ok

## Context

- JupyterLab version: 3.1.0.a12

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/allow-embedding-opening-from-within-jupyterlab/9578/1

**Comment by krassowski** [comment]
It appears that the solution may need to be implemented in JupyterLab and that would be to open the discourse in a new tab.
