### ISSUE TITLE
Cannot change cell type (Firefox)

### ISSUE THREAD

**Issue by coulanuk** [jupyterlab/jupyterlab#10407]
Dropdown Menu to select Code / Markdown / Raw does not respond to mouse cursor selection on:
JupyterLab 3.0.15
Firefox 89.0
Ubuntu 20.04.2
This issue was previous reported and fixed in [#2995](https://github.com/jupyterlab/jupyterlab/issues/2995).
Workaround is to use keyboard arrow keys to change the selection.

**Comment by krassowski** [comment]
Thank you for the report @coulanuk. We are already tracking this in https://github.com/jupyterlab/jupyterlab/issues/10189. Do you think that we can close this one as a duplicate and focus discussion over there?

**Comment by coulanuk** [comment]
@krassowski Yes I have closed it. Thanks
