### ISSUE TITLE
Customized widget toolbars

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#10419]
### Problem

Document widgets are using a common widget `MainAreaWidget` that provides a toolbar. The toolbar items can be added through an API. But it happens regularly that institutions or user want more or less items.
Moreover we could support a more data-backed oriented configuration like for the menus or the shortcuts based on command id and a toolbar widget factory.

The widget factory will hold the match between the tuple (command id, widget type [optional]) and the item widget. And it will allow to define a default widget (the standard default will be a `CommandToolbarButton`).

### Proposed Solution

- Implements a toolbar item factory
- Implements a mechanism to set the toolbar items from a json description (provided through the settings file):

```json5
"toolbars": {
  "notebook": [
    {
      "command": "command-id",
      "args": {}, // optional TBC
      "disabled": false, // optional to allow hiding default items
      "rank": 100 // optional
    },
    {
      "type": "spacer" // or "command" the default
      "rank": 101
    },
    ...
  ],
  "editor": [...]
}
```

- Update the code base to use this new mechanism

**Comment by krassowski** [comment]
Having this in settings would alleviate https://github.com/jupyterlab/jupyterlab/issues/4170 for some users.
