### ISSUE TITLE
Translation of settings

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#10414]
### Problem

JupyterLab has the infrastructure of translating text since v3. But this works only for strings defined in the code (or title and description of settings). It would be interesting to allow the translation of strings from settings for UI built out of a data representation as:
- introduced by #10254 #10373 
- extension like jupyterlab-tour that allow tour step to be defined in settings.

### Proposed Solution

After discussion at the JLab meeting and on https://github.com/jupyterlab/jupyterlab-translate/issues/1, the path to achieve that is:

- Use jinja2 templating style on settings with functions replicating the TS translator API
- Update the settings handlers to conditional process the schema with jinja2 - default value true. But for JLab it will be false to defer the template process in the frontend where the translation is available ([nunjucks](https://mozilla.github.io/nunjucks/) will be used)
- Update the jupyterlab-translate project to extract those new strings from the settings: https://github.com/jupyterlab/jupyterlab-translate/pull/2

**Comment by krassowski** [comment]
This will likely mess with `json2ts` we are using for jupyterlab-lsp (and I would love see adopted in core too) if I am not wrong.

I would like to explore a different solution. I will get back to it after work.

**Comment by fcollonval** [comment]
Hey @krassowski could you elaborate a bit what you have in mind?

**Comment by krassowski** [comment]
So my concerns are the same as https://github.com/jupyterlab/jupyterlab-translate/issues/1#issuecomment-846325140 but also the addition of nunjucks as a dependency (not that I don't like it - used it and it is great, just not very active and possibly not necessary). I was thinking that maybe we could use something smarter even if it would require some work.

To start with a productive discussion, have we considered something like [JSON ITS](https://www.w3.org/International/its/wiki/JSON%2BITS) standard? I know that an extractor would need to be written, but this would make the JSON schema file much cleaner I believe.

**Comment by krassowski** [comment]
We would still need to modify settings system to hot-swap the strings but, we would not have:
- an extra runtime dependency (with its set of dependencies)
- a risk of injection or evaluation of something from settings strings which otherwise seem as safe things (neither nunjucks nor jinja is bulletproof; while we should usually trust the settings strings, why not to avoid the danger whatsoever)
- a need to modify every single string in schema
- less clean schema files

I mean, the JSON is not dynamic in the first place, it will not need dynamic plurals or anything like that, right?

**Comment by fcollonval** [comment]
Thanks @krassowski 

I'm definitely :+1: for keeping thing simple - that was my intention with jupyterlab/jupyterlab-translate#2. And indeed JSON ITS could be a nice simpler possibility (did not know it so thanks for bringing up).

It will allow to simply extend the current logic that translate `title` and `description` of settings schema.

> it will not need dynamic plurals or anything like that, right?

Good point.

---

cc @goanpeca @bollwyvl what do you think?

**Comment by krassowski** [comment]
When drafting https://github.com/jupyterlab/jupyterlab/pull/10752 I noticed descriptions are not available for many plugins. I will look in more detail later (if time permits, from Monday onwards I am back to regular weekend-only contributions).
