### ISSUE TITLE
Running cell focused on output broken in 3.1.0a13

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10429]
## Description

It is no longer possible to <kbd>shift</kbd> + <kbd>enter</kbd> or <kbd>ctrl</kbd> + <kbd>enter</kbd> a cell focused by clicking on output. Clicking on cell code first or clicking "Run cell" button still works.

## Reproduce

![cannot-run](https://user-images.githubusercontent.com/5832902/122273498-66a13c80-ced9-11eb-94e2-65a28f5f126d.gif)

It worked well on 3.0:

![used-to-work](https://user-images.githubusercontent.com/5832902/122273652-96504480-ced9-11eb-919c-a74a877f75f2.gif)

1. Click on cell output
2. See cell getting focused
3. Press <kbd>shift</kbd> + <kbd>enter</kbd>
4. See cell does not run

## Expected behavior

Should work as in 3.0.

## Context

- Browser and version: Chrome
- JupyterLab version: 3.1.0a13

**Comment by krassowski** [comment]
Other shortcuts such as add cell above (<kbd>a</kbd>) or below (<kbd>b</kbd>) do not work either.

**Comment by krassowski** [comment]
It seems it was introduced in https://github.com/jupyterlab/jupyterlab/pull/10282. CC @cameron-toy.

**Comment by cameron-toy** [comment]
I have the desired behavior working by having the `jpCodeRunner` attribute always set to true for the notebook widget. Is there some situation where we wouldn't want `jpCodeRunner` to be set to true? The only time the attribute is referenced for the notebook is here:

https://github.com/jupyterlab/jupyterlab/blob/699ddb4b96e4de94e650c6b19c687056b3f80995/packages/mainmenu-extension/schema/plugin.json#L61-L74

**Comment by krassowski** [comment]
This was fixed by #10517 and related issues were fixed by #10580.
