### ISSUE TITLE
Scroll Bar Bug

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#10428]
## Description

Given a long notebook, the scroll bar is very jumpy. I think it's because the scroll bar isn't calculating the right size (based on the difference of height of the bar).

## Reproduce

Given a long (e.g. 300+ cell) notebook, try to scroll. The left is lab 2.3 and the right is 3.1.0a13 with the same notebook. Note the difference in scrolling and the difference in bar height.

![scroll](https://user-images.githubusercontent.com/1813603/122268666-5d4cab80-ceaa-11eb-8dc8-beb42df778ed.gif)

Please let me know if I should upload a notebook to help with reproducing this issue.

## Expected behavior

It should feel at least as good as lab@2.

## Context

- Operating System and version: Windows
- Browser and version: Chrome
- JupyterLab version: 3.1.0a13

**Comment by krassowski** [comment]
Likely related - the scroll is not properly restored when switching tabs:

![scroll-not-preserved](https://user-images.githubusercontent.com/5832902/122272112-19709b00-ced8-11eb-8bd2-929bb8c03e31.gif)
