### ISSUE TITLE
Save notebooks in indented JSON for version control

### ISSUE THREAD

**Issue by abitrolly** [jupyterlab/jupyterlab#10437]
* I'm always frustrated when I can't view changes in notebook commits, because notebook is serialized as one long JSON string.

### Proposed Solution

* Save notebooks in human readable indented JSON, so that when saved notebook is committed to `git` the changes are readable.
* Ideally add an option to rerun notebook to renumber steps from start, so that resulting diff differences are minimal. 
* And show a warning when steps are not sequentially numbered, so that a person could rerun it before save.

### Additional context

https://nbdime.readthedocs.io/en/latest/ is more helpful than plain `git` commits, but it is not enabled for all repos.

**Comment by fcollonval** [comment]
Hey @abitrolly 

The writing of the notebook is done using [`nbformat` package](https://github.com/jupyter/nbformat).

But I'm surprised by your comment as per default it should write a notebook using one single space indentation: https://github.com/jupyter/nbformat/blob/f101cd2b062609823e9cdbf0e8de697a6c22638e/nbformat/v4/nbjson.py#L47

**Comment by abitrolly** [comment]
@fcollonval the bug it is easily repeatable,

1. Go https://jupyter.org/try
2. Click "Try JupyterLab"
3. Select Python and type anything
4. Click "Download"

You should get this JSON.
```json
{"metadata":{"language_info":{"name":"python","version":"3.7.8","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kernelspec":{"name":"python3","display_name":"Python 3","language":"python"}},"nbformat_minor":5,"nbformat":4,"cells":[{"cell_type":"code","source":"anything","metadata":{"trusted":true},"execution_count":1,"outputs":[{"traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-1-86b18486b5d0>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0manything\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mNameError\u001b[0m: name 'anything' is not defined"],"ename":"NameError","evalue":"name 'anything' is not defined","output_type":"error"}],"id":"3ea0d3e1-bb23-4c4b-a6eb-fafd97986634"}]}
```

**Comment by fcollonval** [comment]
On which OS are you because for me the notebook is indented:

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a2f20e90-b84d-46bf-9137-542543b5a674",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "",
   "name": ""
  },
  "language_info": {
   "name": ""
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

**Comment by abitrolly** [comment]
@fcollonval Linux, Fedora 34, Firefox 90.

Not sure why would OS matter for the download from online service. Does the Binder attempt content negotiation based on target OS? The complete URL is https://hub.gke2.mybinder.org/user/jupyterlab-jupyterlab-demo-13p85w1v/lab/tree/demo/Untitled.ipynb

[Untitled.zip](https://github.com/jupyterlab/jupyterlab/files/6975666/Untitled.zip)

**Comment by abitrolly** [comment]
@yes, it is indented for me too in console. But when I download it, it is still one line long. And the size of downloaded blob is different.

![image](https://user-images.githubusercontent.com/8781107/129227217-5f17c4e6-4e4e-4f50-86bf-3ff94a8adb11.png)

**Comment by fcollonval** [comment]
Thanks for trying that out. Now with your screenshot I got it. We were not using the same _Download_ capability.

The one that bring you this issue is actually an extension for Binder: (jupyter-offlinenotebook)[https://github.com/manics/jupyter-offlinenotebook/].

It had the _Download_ button in the notebook toolbar. And looking at the code, they are doing something different that what I said:

https://github.com/manics/jupyter-offlinenotebook/blob/700064ab094ba7842125f8fcf745e728fc1d4460/src/index.ts#L232

Hence the absence of indent.

Could you please open the issue on that folder?

> Workaround for you (actually what I was doing), use _Download_ from the _File_ menu or from the context menu (right click on the file in the file browser).

**Comment by abitrolly** [comment]
Opened an issue in `jupyter-offlinenotebook`. Using `File -> Download` produces indented JSON indeed.

**Comment by abitrolly** [comment]
https://github.com/manics/jupyter-offlinenotebook/issues/272 still not answered.
