### ISSUE TITLE
Empty raw cell & lost code cells in the virtual notebook

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10435]
## Description

An empty un-rendered raw cell appears in the virtual notebook on some undetermined actions. It can also eat the code cells as on the gif below.

## Reproduce

This one is extremely difficult to reproduce. There is some chaos factor and it only appears one in a dozen attempts. Async isuse/race condition?

![virtual-bug](https://user-images.githubusercontent.com/5832902/122286820-2b5a3a00-cee8-11eb-8d7a-1e8d269d1bfd.gif)

## Context

- Browser and version: Chrome 91.0
- JupyterLab version: 3.1.0a13

**Comment by krassowski** [comment]
I originally noticed it in an existing log notebook at the very end of it (so my reproduction attempts focused on it), but in that case it was not related to running cells at all - it was in there since the notebook was opened.

**Comment by echarles** [comment]
@krassowski I have tried a notebook with many empty cells (like your example) with current master, and indeed, I see a un-rendered cell at the end when I scroll. This happens in the case [1] I wait to scroll so the rendering is complete, and then scroll down to the bottom [2] If I scroll down while the virtual rendering is still happening. Is this the issue you were reporting or do you see also other issue (you are talking about "eat code cell")?

The remaining unrendered cell issue does not show-up with jupyterlab 2.3. Master aims to contain a port of the logic present in 2.3, so many there is something to look there and this may help to nail-down the issue.

**Comment by krassowski** [comment]
> Is this the issue you were reporting or do you see also other issue (you are talking about "eat code cell")?

Yes this is the same issue, and yes there is (sometimes, not every time) an extra issue of executed cell disappearing; please see the GIF in first comment it was caught on record there; it does not happen every time I could not narrow conditions down.

> The remaining unrendered cell issue does not show-up with jupyterlab 2.3. Master aims to contain a port of the logic present in 2.3, so many there is something to look there and this may help to nail-down the issue.

Yes, https://github.com/jupyterlab/jupyterlab/issues/10428 is another issue where it worked in 2.3 but does not work in 3.1.

**Comment by krassowski** [comment]
The reproduction for the lost cell is in https://github.com/jupyterlab/jupyterlab/issues/10488.

**Comment by echarles** [comment]
Fixed with https://github.com/jupyterlab/jupyterlab/pull/10505
