### ISSUE TITLE
The rename file dialog should not show up after the file is closed?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10433]
## Description

There is an edge case scenario for the rename dialog related to closing an unsaved file which was never manually saved. In such case a dialog shows up asking user to either cancel closing the tab, discard the changes and close tab or save the changes and close the tab. However currently the "rename file" dialog is still showing up even though the file was already closed.

## Reproduce

![rename-after-discard](https://user-images.githubusercontent.com/5832902/122284003-0e703780-cee5-11eb-918c-3088a95ccb34.gif)

## Expected behavior

The notebook just gets saved, without a prompt for renaming?

## Context

- JupyterLab version: 3.1.0a13

**Comment by krassowski** [comment]
To clarify, I do not consider this a bug. The current behaviour seems slightly strange, but it is not immediately clear what would be the optimal UX.

**Comment by jess-x** [comment]
closing, as the feature has been reverted
