### ISSUE TITLE
Tab cycling in completer does not work when items are filtered

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10439]
## Description

- [x] The tab cycling (which is an alternative to arrow key cycling) in completer introduced in #10147 does not work properly when items are filtered.
- [ ] when items are filtered, in some cases the shift tab signature pop-up silencing does not work properly

## Reproduce

1. Open IPython notebook
2. Enter `s` in a code cell
3. Press <kbd>tab</kbd> to bring up completer
4. Press <kbd>e</kbd> to filter completions
5. Press <kbd>tab</kbd> to cycle to next item, see it work
6. Press <kbd>tab</kbd> to cycle to next item, see it is stuck
7. Try to cycle up with <kbd>shift</kbd> + <kbd>tab</kbd>, see the selection disappear

Simple repro:

![completer-tab-shift-tab-bug-1](https://user-images.githubusercontent.com/5832902/122431818-b3921b00-cf8c-11eb-943d-aea2a35c8f8a.gif)

A bit more weird repro:

![completer-tab-shift-tab-bug](https://user-images.githubusercontent.com/5832902/122431152-1cc55e80-cf8c-11eb-903e-fbc9bb4f7e18.gif)

## Expected behavior

Should cycle in the order displayed (after filtering).

## Context

- JupyterLab version: 3.1.0a13

**Comment by krassowski** [comment]
CC @cameron-toy

**Comment by krassowski** [comment]
The problem appears to be that on the second pass the `this._activeIndex` is 0 even though in the first pass it was set to `this._activeIndex = index = 1`. This is because the following lines:

https://github.com/jupyterlab/jupyterlab/blob/699ddb4b96e4de94e650c6b19c687056b3f80995/packages/completer/src/widget.ts#L438-L442

Run at every <kbd>tab</kbd> press (and reset `_activeIndex` to 0). However, if the query has _not_ changed, there may be no need to filter again.

**Comment by krassowski** [comment]
@cameron-toy I see a thumb up, would you like to take it from here and add a test for this case as well?

**Comment by cameron-toy** [comment]
@krassowski Yes I think I have a fix, I'll add a test and make a PR in a sec.

**Comment by krassowski** [comment]
Hi @cameron-toy just checking up on this, did you fix work or would you like me to take a look?

**Comment by cameron-toy** [comment]
@krassowski Ah, sorry! No, my fix did not work ): if you have time please take a look.

**Comment by krassowski** [comment]
Okey, so the chain of events is a bit complex. Here is my best idea of what is happening:

1. The completer has a mechanism of adding a partial match. Given two options: `test1`, `test2`, and starting string `t` it should complete (_select on a subset match_) `est` so the user gets `test` as a common prefix (a _subset_) of `test1` and `test2`. It seems to only kick in in some circumstances but not others (/is somewhat broken).
2. The _subset match selection_ behaviour shares a code path with the `query` behaviour - the `query` gets _populated_ with the subset match (annoyingly `subsetMatch` is de-facto a global boolean indicator used in conjunction with signals)
3. The _subset match selection_ announcement code path gets activated **every time** on <kbd>Tab</kbd> if `query` exists, which triggers an update to the editor (a patch gets emitted)
4. The handler receives the spurious announcement of subset match selection (`CompletionHandler.onCompletionSelected`) which triggers a change in the editor model (for the example in the GIF a patch of `{start: 0, end: 2, value: "se"}` is applied; this patch does not change the editor content at all, but it can trigger other signals; worth noting this is now handled by the `sharedModel`; we should not do that because we could be polluting the edits history.
5. (I guess that) The change in the editor model triggers a completer update (equivalent to user pressing a key)
5. (I guess that) The completer update resets the active item index as it thinks that a change was made (even though the patch applied did not result in any change)

All of this is terribly annoying to unit test (if it even should be unit tested). A galata-level test might be more appropriate.

**Comment by krassowski** [comment]
One way to see this is to say that the test cases:
- "should mark common subset on start and complete that subset on tab"
- "should mark common subset of completion items on start and complete that subset on tab"

Conflict with the "<kbd>Tab</kbd> as cycler" behaviour. But we can still have both; the solution would be to be a bit smarter in the step (3) and only announce the change if the `query` did change.

On the other hand, I am not sure if we want to keep the `select on a subset match` behaviour long-term. For backwards compatibility I would prefer to keep it as is 3.1, which may seem to lead to double action on <kbd>Tab</kbd> (which is not a great UX):

![double-beh](https://user-images.githubusercontent.com/5832902/124685880-072bc080-deca-11eb-94dd-b344e12a7ce0.gif)

**Comment by krassowski** [comment]
I opened a PR for the that, but we still need to resolve the second problem of occlusion on <kbd>Shift</kbd> + <kbd>Tab</kbd> (as shown on the `str.` example). Please let me know if you have any thoughts on that bit.
