### ISSUE TITLE
False positive "File Changed" popup after renaming file

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10436]
## Description

A dialog with:

```
File Changed
"Untitled1.ipynb" has changed on disk since the last time it was opened or saved. Do you want to overwrite the file on disk with the version open here, or load the version on disk (revert)?
```

show up if we save `Untitled1.ipynb` notebook and then rename it immediately via the new dialog window and then create a new notebook (which automatically will become named `Untitled1.ipynb`).

## Reproduce

Here I had `Untitled2.ipynb` (as `Untitled1.ipynb` already existed in the directory):

![rename-after-save-race-condition](https://user-images.githubusercontent.com/5832902/122290635-dd473580-ceeb-11eb-99c5-3d741506b868.gif)

## Expected behavior

Disk watcher should not prompt about the old file which was renamed.

## Context

- JupyterLab version: 3.1.0a13

**Comment by jess-x** [comment]
closing, as the feature has been reverted
