### ISSUE TITLE
Edge navigation is broken in some circumstances with virtual notebook

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10434]
## Description

With virtual notebook navigating to previous cell by pressing up and down arrow keys does not always work.

## Reproduce

1. Create a notebook with multiple cells
2. In the last cell enter "test" and execute the cell with <kbd>Shift</kbd> + <kbd>enter</kbd> so that exception is shown
3. Enter the new final cell
4. Try to move out of it using <kbd>↑</kbd> up arrow key
5. See it is no longer possible

![does-not-work](https://user-images.githubusercontent.com/5832902/122285459-a6225580-cee6-11eb-9164-ee6bc9d7cfc1.gif)

It works well if virtual notebook does not kick in:

![works-ok](https://user-images.githubusercontent.com/5832902/122285773-05806580-cee7-11eb-9de2-673baa45df0d.gif)

## Expected behavior

Should work.

## Context

- JupyterLab version: 3.1.0a13.

**Comment by echarles** [comment]
Fix in https://github.com/jupyterlab/jupyterlab/pull/10602
