### ISSUE TITLE
Can't disable cursor-blinking

### ISSUE THREAD

**Issue by gloryVine** [jupyterlab/jupyterlab#10443]
I am using JupyterLab on macOS. I need a non-blinking cursor, because the blinking is incredibly distracting, especially so since I am using a block cursor.
I tried following the suggestions in [this Jupyter issue](https://github.com/jupyter/notebook/issues/1570), in particular I added the code 
`"CodeCell": { "cm_config": {"cursorBlinkRate": 0}}`
 in 
`/.jupyter/nbconfig/notebook.json`
 and since this didn't work, also in 
`jupyter_notebook_config.json`
but to no avail.

The expected behavior is a non-blinking cursor.

- Operating System and version: macOS Catalina 10.15
- Browsers: Safari, Opera, Firefox. All have the same problem.
- JupyterLab version: 3.0.16

**Comment by appomsk** [comment]
I was able to remove the blinking cursor from jupyter labs for google chrome using Stylus extension by adding for `http://localhost:8888/lab`:

``` css
.CodeMirror-cursor {
  border-left: 2px solid black;
  border-right: none;
  width: 0;
  visibility: visible;
}
```

There is the same extension for Firefox, so I think it should work for this browser too.

>  _A little grunt_: The blinking cursor is not good for any people - just google "Lavender Town Syndrome", but for some, for me, for example, it makes it impossible to use the software. This also leads to some thoughts about the developers of this product, especially when there is a possibility of setting (codemirror allows to set this), but this possibility has not been used for some reason.

**Comment by fcollonval** [comment]
Thanks @appomsk for sharing the trick.

**Comment by gloryVine** [comment]
Thank you @appomsk, this works. Hopefully we can have a Jupyter-native solution at some point, because I don't like having to add more and more extensions which can access all my website data (Stylus in this case).

**Comment by gloryVine** [comment]
If anybody still has this problem, see this issue [this issue](https://github.com/jupyterlab/jupyterlab/pull/10485) for the solution.

**Comment by jan-swiecki** [comment]
> I was able to remove the blinking cursor from jupyter labs for google chrome using Stylus extension by adding for `http://localhost:8888/lab`:
> 
> ```css
> .CodeMirror-cursor {
>   border-left: 2px solid black;
>   border-right: none;
>   width: 0;
>   visibility: visible;
> }
> ```
> 
> There is the same extension for Firefox, so I think it should work for this browser too.

Or copy paste below into dev tools console:

    s = document.createElement("style"); s.innerHTML = ".CodeMirror-cursor {  border-left: 2px solid black;  border-right: none;  width: 0;  visibility: visible;}"; document.body.appendChild(s);

**Comment by krassowski** [comment]
@jan-swiecki, you don't need to resort to such workarounds since the `cursorBlinkRate` option is now available in the settings (as explained in https://github.com/jupyterlab/jupyterlab/pull/10485#issuecomment-871136470).
