### ISSUE TITLE
JupyterLab hangs on server shut down

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#10442]
## Description

It appears that JupyterLab sometimes fail to gracefully shut down when it is stopped in the terminal with Ctrl-C.

## Reproduce

1. Start JupyterLab
2. Generate some activity: create notebook, start kernel...
3. Close the browser tab
4. Hit Ctrl-C in the terminal
5. Try sending a SIGTERM to the process

![image](https://user-images.githubusercontent.com/591645/122461023-1c8c8980-cfb3-11eb-946c-d6387e1e44c5.png)

The only way out then is manually sending a SIGKILL to the process, or closing the terminal window.

## Expected behavior

JupyterLab should shut down gracefully.

## Context

This does not seem to be reproducible all the time.

- Operating System and version: Ubuntu 20.04
- Browser and version: Chromium 91
- JupyterLab version: 3.0.16

cc @davidbrochart who also mentioned this issue a little while ago

**Comment by goanpeca** [comment]
Yes, I started seeing this a couple of days ago.

**Comment by davidbrochart** [comment]
https://github.com/jupyter-server/jupyter_server/pull/543 should fix it.

**Comment by davidbrochart** [comment]
OK that didn't fix the issue, what I can see is that it is related to Jupyter Server using AnyIO worker threads to run tasks in the background, introduced in https://github.com/jupyter-server/jupyter_server/pull/324.

**Comment by icankeep** [comment]
I had the same problem

**Comment by davidbrochart** [comment]
I opened https://github.com/agronholm/anyio/pull/321 which should fix this issue.

**Comment by davidbrochart** [comment]
Third attempt :smile: in https://github.com/jupyter-server/jupyter_server/pull/545

**Comment by jtpio** [comment]
Thanks @davidbrochart!
