### ISSUE TITLE
create new notebook is failing in UI tests

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#10445]
## Description

Since we check that the `createNew` notebook helper of galata is successful, the UI test is often failing. Most probably because of the notebook being name the same in multiple test files.

**Comment by fcollonval** [comment]
Xref #10410

**Comment by mbektas** [comment]
> Most probably because of the notebook being name the same in multiple test files.

@fcollonval tests are run in series, so I wouldn't think failures are caused by name clash. It could be due to a wait issue in Galata's `notebook.createNew` API. I am investigating as well.

**Comment by mbektas** [comment]
I confirmed that it is a wait issue. When a name is set, notebook.createNew is not waiting enough for the rename operation. created https://github.com/jupyterlab/galata/issues/60 and will be pushing a fix.

**Comment by fcollonval** [comment]
Thanks for fixing this @mbektas
