### ISSUE TITLE
Deleting a notebook should first stop its kernel

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1045]
Right now if you delete a notebook in the file browser while its kernel is running, the kernel remains. If you then go try to kill the kernel in the Running tab it gives an error that the file doesn't exist. Until we allow arbitrary mappings between files/kernels we should kill a kernel if a document is deleted.

**Comment by blink1073** [comment]
I agree with this, provided we run `Session.listRunning` and make sure it is the thing using the kernel.  Another question though is what to do if that file is open in the dock panel?  Most text editors will leave a file open and mark it as orphaned, but how does that extend to running kernels?

**Comment by jasongrout** [comment]
Related to #1070.

**Comment by ellisonbg** [comment]
Yes, we should make sure no-one else is using the kernel first.

**Comment by blink1073** [comment]
Fixed by #1515.
