### ISSUE TITLE
Show pending/executing in TOC

### ISSUE THREAD

**Issue by goerz** [jupyterlab/jupyterlab#10452]
The [classic notebook TOC2 extension](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html) would show a color highlight to indicate which section was being edited/pending/executing. This was extremely useful for "Run all", as the TOC would serve as a nice progress indicator.

In the latest version of the jupyterlab TOC, in the form that is now built-in to Jupyterlab 3 (I'm running 3.1.0a13 specifically), the TOC already shows a color indicator for the active cell. I'm very impressed with all the work that has gone into the version 3 user interface. A big thanks to everyone who's been putting work into this! The TOC has definitely much progressed since the early versions of the [third-party-plugin](https://github.com/jupyterlab/jupyterlab-toc). It's *almost* at the functionality of the classic TOC. So: Would it be feasible to extend the "active" indicator with color-coded indicators for pending/executing, like in the classic TOC?

I'd also love the see an option to skip the main title in the TOC numbering, cf https://github.com/jupyterlab/jupyterlab-toc/issues/66 and https://github.com/jupyterlab/jupyterlab-toc/issues/97.

**Comment by krassowski** [comment]
Nice ideas!

> I'd also love the see an option to skip the main title in the TOC numbering

There is a PR open for it, which is almost ready (basically waiting to be merged): https://github.com/jupyterlab/jupyterlab/pull/9994; would you like to have a quick look and see if this implements the expected functionality well?

Minor detail: did you wish to cross-reference issues from another repository?

**Comment by goerz** [comment]
> > I'd also love the see an option to skip the main title in the TOC numbering
> 
> There is a PR open for it, which is almost ready (basically waiting to be merged): #9994; would you like to have a quick look and see if this implements the expected functionality well?

The screenshots in the PR look exactly like what I'd be hoping for, as far as section numbering is concerned 👍 

> Minor detail: did you wish to cross-reference issues from another repository?

You mean https://github.com/jupyterlab/retrolab/issues/168? I did want to crosslink from that issue to here, yes. Seems like Github creates the backlink automatically.

**Comment by krassowski** [comment]
No, I mean issues 66 (enable mathjax) and 97 (clarify extension installation language).

**Comment by goerz** [comment]
Ah... sorry, I'm a bit slow today. And yes, I completely missed that these issues are in the `jupyterlab-toc` repository. I meant to reference https://github.com/jupyterlab/jupyterlab-toc/issues/66 and https://github.com/jupyterlab/jupyterlab-toc/issues/97. Sorry about that! I edited the original comment, too.

**Comment by fcollonval** [comment]
Closing as implemented
