### ISSUE TITLE
First cell is broken when creating a new notebook.

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyterlab#10456]
## Description

First cell is broken when creating a new notebook. You can select the first cell for writing.

![issue_first_cell](https://user-images.githubusercontent.com/26092748/122746816-afb31100-d28a-11eb-8912-c29e784780b1.gif)

## Reproduce

Using master in dev mode, when creating a new notebook the default cell is broken.

Using Chrome Version 91.0.4472.114-1.
Using Firefox works fine

**Comment by jtpio** [comment]
Thanks Carlos for the report.

Just tested on Brave with Chromium 91 using the dev Binder on the latest `master` (https://mybinder.org/v2/gh/jupyterlab/jupyterlab/master?urlpath=lab-dev), and it seems to be working fine:

https://user-images.githubusercontent.com/591645/122921692-13107200-d363-11eb-96c3-7ad1dbc46152.mp4

Would you be able to also check on the dev Binder, just to make sure it's not an issue with a stale local dev environment?

**Comment by hbcarlos** [comment]
Yes, it's broken on binder too. But since no one else reported this, I suppose what's broken is my Google Chrome. 😔

https://user-images.githubusercontent.com/26092748/122922614-19531e00-d364-11eb-9bc4-a17f36e158b1.mp4

**Comment by jtpio** [comment]
> Yes, it's broken on binder too. But since no one else reported this, I suppose what's broken is my Google Chrome

Just double checked the dev Binder with stock Chromium 91 on Ubuntu, and it works fine.

**Comment by blink1073** [comment]
Looks like this one is settled for now
