### ISSUE TITLE
migrate nameFileOnSave to docmanager-extension

### ISSUE THREAD

**Issue by jess-x** [jupyterlab/jupyterlab#10463]
### Problem

In Name File Dialog

> Setting manager.nameFileOnSave directly might be misleading for example when the checkbox is ticked, but the dialog is "canceled" by clicking outside of it.
> In that case one could expect the change to not have taken effect since "Enter" was not clicked.
> 

https://github.com/jupyterlab/jupyterlab/pull/10294/files#r652503847

### Proposed Solution

> keep the state in the rename dialog instead, and wait for Enter to be clicked before deciding whether or not to apply the settings (by checking result.value)
> 
> And maybe this logic could then be moved to the plugin level in the docmanager-extension package, removing the need for having nameFileOnSave on the doc manager.

https://github.com/jupyterlab/jupyterlab/pull/10294/files#r652506058

**Comment by jtpio** [comment]
Closing as the feature has been reverted for now.

Thanks @jess-x for working on this!
