### ISSUE TITLE
Rename dialog: clicking on the label does not change the checkbox

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#10460]
## Description

in the rename dialog, the user needs to click explicitly on the checkbox. Clicking on the label does not work

![only_checkbox](https://user-images.githubusercontent.com/8435071/122886988-bac87880-d340-11eb-860e-225558eca179.gif)

## Reproduce

1. Create a new notebook
2. Close it
3. in the dialog click on the text _Don't ask me again_
4. The checkbox does not change

## Expected behavior

Checkbox state should change when clicking on the label.

## context

Webbrowser: Firefox

**Comment by jtpio** [comment]
Thanks @fcollonval.

This looks like the same as https://github.com/jupyterlab/jupyterlab/issues/10317?

**Comment by fcollonval** [comment]
Thanks sorry I miss that one...
