### ISSUE TITLE
selecting markdown and inputting `[` should add a link, not replace the selected text with [

### ISSUE THREAD

**Issue by alexlenail** [jupyterlab/jupyterlab#10473]
- In a code cell, selecting some `code` and inputting `(` results in `(code)`. 
- In a text editor (I use sublime), selecting some `markdown` and inputting `[` results in `[markdown]`. 
- In a markdown cell in jupyter lab, selecting `markdown` and inputting `[` results in `[`. 

I'd love if selecting `markdown` in a markdown cell and inputting `[` would result in `[markdown]`.

**Comment by gereleth** [comment]
It's possible to change this through settings. 
Select "Settings > Advanced Settings Editor" from top menu. 
Then choose "Notebook" on the left and look for `markdownCellConfig` in the System Defaults. You'll see that it has `"autoClosingBrackets": false`. You can set that to `true` in User Preferences like this:

```
{
    "markdownCellConfig": {
        "autoClosingBrackets": true
    }
}
```

Here's a screenshot showing the relevant settings:

![Screenshot_2021-06-28 setting-editor (auto-r) - JupyterLab](https://user-images.githubusercontent.com/6080076/123612604-607d5b00-d80b-11eb-8f15-f10276142a82.png)

**Comment by alexlenail** [comment]
Thanks for this! 

I'd advocate this be the default, but if that doesn't seem right, then please close this issue. 

Strangely, I'm not able to open the advanced settings editor at the moment -- clicking it or using the shortcut both don't work -- but that seems like something I need to sort out myself.

**Comment by jasongrout** [comment]
> I'd advocate this be the default, but if that doesn't seem right, then please close this issue.

Interestingly, we've just concluded conversation over the last several years about changing this setting to 'false' by default. See #9488, https://github.com/jupyterlab/jupyterlab/issues/5741

**Comment by jasongrout** [comment]
Also, I don't think having autoclosing brackets off necessarily precludes having automatic link insertion.

One of my favorite markdown editing features in other editors is being able to select some text and paste, and if the text in the clipboard is a link, the selected text turns into a link rather than having the clipboard replace the selected text. I'd love to see that supported too.

**Comment by alexlenail** [comment]
ha! Well I'm happy so long as I can turn autoclose on.
