### ISSUE TITLE
Checkbox styling is broken

### ISSUE THREAD

**Issue by ktaletsk** [jupyterlab/jupyterlab#10471]
## Description

When upgrading my extension to JupyterLab 3.0 I noticed that the checkbox that I used in one of the forms is not rendered correctly, rather it is shown as a text field and lost the checkbox functionality. I narrowed down the issue to `appearance` and `webkit-appearance` being set to `none` instead of `checkbox` in CSS. To demonstrate, I created the cookiecutter extension that shows simple boolean dialog from https://jupyterlab.readthedocs.io/en/stable/extension/ui_helpers.html#input-dialogs here: https://github.com/ktaletsk/jupyterlab-test-checkbox. 

 ![Before fix](https://files.gitter.im/58216e89d73408ce4f346b05/BfJn/image.png)

 ![Before fix](https://files.gitter.im/58216e89d73408ce4f346b05/lHf7/image.png)

I think this is related to jupyterlab/jupyterlab#9222. When I manually add this css block to the extension's base.css, the issue disappears:
```css
input[type='checkbox'] {
  appearance: checkbox;
  -webkit-appearance: checkbox;
  -moz-appearance: checkbox;
  height: auto;
```

## Reproduce

1. Add checkbox to the extension
2. Load extension
4. Observe styling error

## Expected behavior

Checkbox is shown as a checkbox.

## Context

- Operating System and version: Linux, macOS
- Browser and version: Edge on Windows, Safari on macOS
- JupyterLab version: 3.0

**Comment by krassowski** [comment]
As this was an element of public API (`InputDialog.getBoolean`) which got defunct in 3.0 and there are still extensions that have not migrated to 3.0 I think it would be good adding it back, but the styles should go to https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/style/styling.css instead. This is a good way to implement disclaimers where an extra click is wanted from the user (as distinct from just clicking on "Ok" button - which is useful for legal stuff or very destructive actions).

**Comment by ktaletsk** [comment]
Hi @krassowski, I have couple of questions/comments:
1. When was `InputDialog.getBoolean` deprecated? I can still see the code for it https://github.com/jupyterlab/jupyterlab/blob/dbdefed9db9332381fe4104bdf53ec314451951f/packages/apputils/src/inputdialog.ts#L67 and it is still mentioned in docs https://github.com/jupyterlab/jupyterlab/blob/f0790b3ffd187b7dc923156b8ae227855abecefb/docs/source/extension/ui_helpers.rst#L27
2. The issue in general is related to any checkboxes, not only in `InputDialog.getBoolean`. Extensions should be able to display a checkboxes that would just work without much tinkering in css.

**Comment by krassowski** [comment]
> When was InputDialog.getBoolean deprecated?

I don't think it was ever deprecated. I did not mean to say that it was deprecated and if you got this from my comment - sorry! I am working on making my English cleaner and easier to understand. I only meant to say that the CSS styles removed in 3.0 rendering checkboxes broken since 3.0. Then I added a comment on why I believe this function should continiue to be supported in future versions.

> The issue in general is related to any checkboxes, not only in InputDialog.getBoolean. Extensions should be able to display a checkboxes that would just work without much tinkering in css.

Thanks for highlighting that, I 100% agree.

**Comment by ktaletsk** [comment]
Oh, no problem, sorry for misunderstanding. Good to be on the same page

**Comment by krassowski** [comment]
Also, please note that https://github.com/jupyterlab/jupyterlab/pull/10043 introduced checkbox styles for file dialogs here: https://github.com/jupyterlab/jupyterlab/pull/10043/files#diff-44b56bf79f838c9023ebd121a0ae3a2d6e603331ba60bda47fbda2760b6735ddR43-R96

Maybe we could generalize that styles to make checkboxes work for all dialog windows?
