### ISSUE TITLE
ToC: nested functions/classes are not indented in ToC

### ISSUE THREAD

**Issue by hottwaj** [jupyterlab/jupyterlab#10477]
### Problem

Nested functions/classes are not indended in ToC.  

e.g. given code:
```python
class Dog:
    def bark():
        pass
```

Users will currently see in ToC:
```
class Dog
def bark
```

But it would be preferable if they saw:
```
class Dog
    def bark
```

### Proposed Solution

Keep track of indentation in order to appropriately nest functions/classes

### Additional context

This issue was originally raised by @stefansimik on jupyterlab-toc project, see https://github.com/jupyterlab/jupyterlab-toc/issues/140.

I submitted a PR implementing changes to make this work to jupyterlab-toc and was asked to resubmit it here: https://github.com/jupyterlab/jupyterlab-toc/pull/153

Thanks!

**Comment by fcollonval** [comment]
Closed by https://github.com/jupyterlab/jupyterlab/pull/12374
