### ISSUE TITLE
“jupyter lab build” fails with Invalid regular expression

### ISSUE THREAD

**Issue by pelacables** [jupyterlab/jupyterlab#10487]
## Description

Dear all,

I’m running a fresh new jupyterhub 1.4.1 installtion follwoing the offcial docs.

```bash
$ jupyterhub --version
1.4.1

$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : not installed
ipython          : 7.24.1
ipykernel        : 5.5.5
jupyter client   : 6.1.12
jupyter lab      : 3.0.16
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```

The hub is up and running and now I’d like to add Jupyterlab extension.
the package is installed (among others):

```bash
$ pip list|grep -i lab
jupyterlab                        3.0.16
jupyterlab-git                    0.30.1
jupyterlab-pygments               0.1.2
jupyterlab-server                 2.6.0
jupyterlab-widgets                1.0.0

$ jupyter labextension list
JupyterLab v3.0.16

Build recommended, please run `jupyter lab build`:
    No built application
```

but when I build it always fails with the next error:

```bash
[LabBuildApp] Node v12.19.0
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/jupyterhub/1.4.1-foss-2021a-Python-3.9.5/lib/python3.9/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.46s.
[...]
[LabBuildApp] > node /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/jupyterhub/1.4.1-foss-2021a-Python-3.9.5/lib/python3.9/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid property name
    at pathToArgumentName (/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:66:4)
    at addFlag (/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:170:16)
    at traverse (/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:243:21)
    at traverse (/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:299:23)
    at traverse (/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:248:24)
    at Object.getArguments (/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:308:2)
    at WebpackCLI.getBuiltInOptions (/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/share/jupyter/lab/staging/node_modules/webpack-cli/lib/webpack-cli.js:591:47)
    at loadCommandByName (/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/share/jupyter/lab/staging/node_modules/webpack-cli/lib/webpack-cli.js:732:38)
    at Command.<anonymous> (/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/share/jupyter/lab/staging/node_modules/webpack-cli/lib/webpack-cli.js:1260:23)
    at Command.listener [as _actionHandler] (/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/share/jupyter/lab/staging/node_modules/webpack-cli/node_modules/commander/index.js:922:31)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
```

## Reproduce

1. Install Jupyterhub & jupyterlab extension
2. run `jupyter lab build`

## Expected behavior

Jupyterlab builds without errors.

## Context

- Operating System and version: Scientific Linux 7 (software installed using EasyBuild)
- JupyterLab version: 3.0.16

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/jupyterhub/1.4.1-foss-2021a-Python-3.9.5/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/configurable-http-proxy/4.2.1-GCCcore-10.3.0
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/configurable-http-proxy/4.2.1-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/nodejs/12.19.0-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/SQLite/3.35.4-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Tcl/8.6.11-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/ncurses/6.2-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/bzip2/1.0.8-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/FFTW/3.3.9-gompi-2021a/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/FlexiBLAS/3.0.4-GCC-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/OpenMPI/4.1.1-GCC-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/PMIx/3.2.3-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/libfabric/1.12.1-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/UCX/1.10.0-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/libevent/2.1.12-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/OpenSSL/1.1/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/hwloc/2.4.1-GCCcore-10.3.0/sbin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/hwloc/2.4.1-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/libxml2/2.9.10-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/XZ/5.2.5-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/numactl/2.0.14-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/binutils/2.36.1-GCCcore-10.3.0/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/GCCcore/10.3.0/bin
        /home/x2bioc/bin
        /usr/lib64/qt-3.3/bin
        /usr/local/bin
        /usr/bin
        /usr/local/sbin
        /usr/sbin
        /opt/slurm/prod/bin
        /opt/puppetlabs/bin
        /opt/singularity/bin

sys.path:
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/jupyterhub/1.4.1-foss-2021a-Python-3.9.5/bin
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/jupyterhub/1.4.1-foss-2021a-Python-3.9.5/lib/python3.9/site-packages
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/easybuild/python
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/lib/python39.zip
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/lib/python3.9
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/lib/python3.9/lib-dynload
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/lib/python3.9/site-packages

sys.executable:
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/bin/python3.9

sys.version:
        3.9.5 (default, Jun 14 2021, 12:37:20)
        [GCC 10.3.0]

platform.platform():
        Linux-3.10.0-1160.21.1.el7.x86_64-x86_64-with-glibc2.17
which -a jupyter:                                                                                                                             [53/155]
        /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/jupyterhub/1.4.1-foss-2021a-Python-3.9.5/bin/jupyter

pip list:
        Package                           Version
        --------------------------------- ---------
        alembic                           1.6.5
        anyio                             3.1.0
        argon2-cffi                       20.1.0
        async-generator                   1.10
        attrs                             21.2.0
        Babel                             2.9.1
        backcall                          0.2.0
        bleach                            3.3.0
        certifi                           2021.5.30
        certipy                           0.1.3
        cffi                              1.14.5
        chardet                           4.0.0
        colorama                          0.4.4
        cryptography                      3.4.7
        decorator                         5.0.9
        defusedxml                        0.7.1
        deprecation                       2.1.0
        entrypoints                       0.3
        environment-kernels               1.1.1
        gitdb                             4.0.7
        GitPython                         3.1.17
        greenlet                          1.1.0
        idna                              2.10
        ipykernel                         5.5.5
        ipython                           7.24.1
        ipython-genutils                  0.2.0
        ipywidgets                        7.6.3
        jedi                              0.18.0
        Jinja2                            3.0.1
        json5                             0.9.5
        jsonschema                        3.2.0
        jupyter-client                    6.1.12
        jupyter-contrib-core              0.3.3
        jupyter-contrib-nbextensions      0.5.1
        jupyter-core                      4.7.1
        jupyter-highlight-selected-word   0.2.0
        jupyter-latex-envs                1.4.6
        jupyter-nbextensions-configurator 0.4.1
        jupyter-packaging                 0.10.2
        jupyter-server                    1.8.0
        jupyter-server-mathjax            0.2.3
        jupyter-telemetry                 0.1.0
        jupyterhub                        1.4.1
        jupyterlab                        2.3.1
        jupyterlab-pygments               0.1.2
        jupyterlab-server                 1.2.0
        jupyterlab-widgets                1.0.0
        lxml                              4.6.3
        Mako                              1.1.4
        MarkupSafe                        2.0.1
        matplotlib-inline                 0.1.2
        mistune                           0.8.4
        nbclassic                         0.3.1
        nbclient                          0.5.3
        nbconvert                         6.0.7
        nbdime                            3.1.0
        nbformat                          5.1.3
        nest-asyncio                      1.5.1
        notebook                          6.4.0
        oauthlib                          3.1.1
        packaging                         20.9
        pamela                            1.0.0
        pandocfilters                     1.4.3
        parso                             0.8.2
        pexpect                           4.8.0
        pickleshare                       0.7.5
        pip                               21.1.1
        prometheus-client                 0.11.0
        prompt-toolkit                    3.0.18
        ptyprocess                        0.7.0
        pycparser                         2.20
        Pygments                          2.9.0
        pyOpenSSL                         20.0.1
        pyparsing                         2.4.7
        pyrsistent                        0.17.3
        python-dateutil                   2.8.1
        python-editor                     1.0.4
        python-json-logger                2.0.1
        pytz                              2021.1
        PyYAML                            5.4.1
        pyzmq                             22.1.0
        requests                          2.25.1
        ruamel.yaml                       0.17.9
        ruamel.yaml.clib                  0.2.2
        Send2Trash                        1.5.0
        setuptools                        57.0.0
        six                               1.16.0
        smmap                             4.0.0
        sniffio                           1.2.0
        SQLAlchemy                        1.4.18
        terminado                         0.10.1
        testpath                          0.5.0
        tomlkit                           0.7.2
        tornado                           6.1
        traitlets                         5.0.5
        urllib3                           1.26.5
        wcwidth                           0.2.5
        webencodings                      0.5.1
        websocket-client                  1.1.0
        wheel                             0.36.2
        widgetsnbextension                3.5.1
</pre>
</details>

**Comment by Mycron** [comment]
Hi! I've got the same trying to compose Jupyterlab as environment module (with Lmod).
My context is:
OS: Red Hat Enterprise Linux Server release 7.8
Jupyterlab: 3.0.16
NodeJS: 14.17.1, (also got the same result with 12.19.0)
Extensions to install: jupyterlab_widgets(1.0.0), jupyterlab_git(0.30.1), nbdime(3.1.0), qgrid(1.3.1)

**Comment by krassowski** [comment]
It looks like something which is not specific to JupyterLab: https://stackoverflow.com/questions/64413433/webpack-serve-giving-invalid-regular-expression-error. One [answer](https://stackoverflow.com/a/64712032/6646912) recommends updating webpack-cli to 4.2.0; could you try doing so and see if it solves the problem, please?

By the way I would recommend migration to federated version of extensions which do not require the build step or having node.js installed.

**Comment by Mycron** [comment]
Hi, @krassowski ! Thank you for your attention!
I saw this topic on Stackoverflow, but their receipt didn't fit for me - I've got the same result with webpack@4.42.0 webpack-cli@3.3.11 or just webpack-cli@4.2.0.
Generally I'm trying to install **nbdime@3.1.0** extension by **pip install nbdime** , but as of [nbdime documentation](https://nbdime.readthedocs.io/en/latest/installing.html) saying me that I have to run _'nbdime extensions --disable'_ to enable it in Jupyterlab.
Additionally I got 
`
[W 2021-06-29 10:08:10.853 LabApp] Build recommended
[W 2021-06-29 10:08:10.853 LabApp] nbdime-jupyterlab needs to be included in build
`

**Comment by krassowski** [comment]
@Mycron no, you do not need to run `nbdime extensions --disable` (this is for disabling the extension). Please just run:

```
jupyter labextension uninstall nbdime-jupyterlab
pip install --upgrade nbdime
```

which should first remove the extension installed using the old extensions system and then install the new version using the new system. If this does not help then share the output of:

```
jupyter labextension list
```

**Comment by Mycron** [comment]
Yes, sorry!
I meant `nbdime extensions --enable`

**Comment by Mycron** [comment]
When running Jupyterlab session, I see in log these lines
> [W 2021-06-29 11:44:18.349 LabApp] Build recommended
> [W 2021-06-29 11:44:18.349 LabApp] nbdime-jupyterlab needs to be included in build
It's a cause why I'm trying to invoke previous command

**Comment by Mycron** [comment]
Sufficient progress while searching possible cause of this issue.
@pelacables , check if your NodeJS was built with libICU support.
I've rebuild my NodeJS 14.17.1 with
` configopts = [
    '--with-intl=system-icu',          
    '--shared --with-intl=system-icu', 
 ]
` and this error is gone, while executing `'jupyter lab build'`

**Comment by pelacables** [comment]
Thanks, I'll give it a try later today but, did that fix the issue?

**Comment by Mycron** [comment]
> Thanks, I'll give it a try later today but, did that fix the issue?

Yes, for me it's a final solution to solve this issue

**Comment by Mycron** [comment]
Of course, you have 2 options here:
* install libicu in a system
* use ICU module as a dependency for NodeJS

**Comment by pelacables** [comment]
@Mycron  thanks a lot, I managed to build it. But the extension is not listed yet:

```bash
$ jupyter serverextension list
config dir: /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.3.1 OK
    jupyterlab_git  enabled
    - Validating...
      jupyterlab_git 0.30.1 OK
    jupyter_nbextensions_configurator  enabled
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK
$ jupyter labextension list
JupyterLab v2.3.1
No installed extensions
```

@krassowski what config file is missing?

```bash
$ jupyter labextension list --debug
Searching ['/home/x2bioc/git/easyconfigs', '/home/x2bioc/.jupyter', '/apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /apps/prod/easybuild/sl7.x86_64.foss-2021a/software/Python/3.9.5-GCCcore-10.3.0-bare/etc/jupyter
Looking for jupyter_config in /home/x2bioc/.jupyter
Looking for jupyter_config in /home/x2bioc/git/easyconfigs
Yarn configuration loaded.
JupyterLab v2.3.1
No installed extensions
```

a bit of explanation on what lab is looking for?

(BTW, I've downgraded jupyterlab to version 2).

**Comment by Mycron** [comment]
@pelacables , please take a look for your config paths. It might be a problem here that when you are building Jupyterlab, you are possibly using its config directory, but when you are running Jupyterlab you are using only system(/etc/jupyter, /usr/local/etc/jupyter), user(/home/x2bioc/...) and Python module specific paths, not Jupyterlab's one

**Comment by Mycron** [comment]
I found interesting docs related to additional Jupyterlab configuration
https://jupyter.readthedocs.io/en/latest/use/jupyter-directories.html

**Comment by pelacables** [comment]
The build issue is fixed. My config problem (related to the specific extension) has nothing to do with the original issue anymore.
I close the issue. Thanks @Mycron for your help.
