### ISSUE TITLE
Can JupyterLab support foldable directories?

### ISSUE THREAD

**Issue by icankeep** [jupyterlab/jupyterlab#10482]
## Current
![image](https://user-images.githubusercontent.com/39434627/123379211-60d5e600-d5c0-11eb-8cc3-4a54da9109ea.png)

## Expect
![image](https://user-images.githubusercontent.com/39434627/123379051-1e140e00-d5c0-11eb-8ac9-6c928ac6b9f9.png)

## detail
In the current directory structure, you cannot see other subdirectories of the parent directory after entering the subdirectory, which is very inconvenient to use

**Comment by fcollonval** [comment]
Hey @icankeep 

This is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/5526
FYI it is actually on the roadmap for 4.0. But in the mean time, you can use an extension:
- https://github.com/martinRenou/jupyterlab-unfold
- https://github.com/youngthejames/jupyterlab_filetree
