### ISSUE TITLE
Set codemirror settings in one place

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#10486]
### Problem

There are currently 4 places to set some codemirror settings like code folding. And there is no place to set such settings for the console. It will be better to have an unique place to define default options. And then to be able to override them if required - for example the font size may be changed by the user for the console.

### Proposed Solution

With codemirror to become the official code editor #10380 , we should probably move those default setting there.

**Comment by krassowski** [comment]
Related to: https://github.com/jupyterlab/jupyterlab/issues/10352 and https://github.com/jupyterlab/jupyterlab/pull/9142
