### ISSUE TITLE
handlePaste is not a valid property in Advanced Settings Editor

### ISSUE THREAD

**Issue by richardkang112** [jupyterlab/jupyterlab#10489]
## Description

'[additional property error] handlePaste is not a valid property' message is displayed when I go to 'Advanced Settings Editor -> Text Editor' after enabling 'Indent with Tab' option. It seems 'Indent with Tab' doesn't get applied due to the error. 

![image](https://user-images.githubusercontent.com/50002894/123454485-9d98e180-d5ae-11eb-8e4c-4df60b60a1ca.png)

## Reproduce

1. Enable 'Indent with Tab' on Command Palette or 'settings -> Text Editor Indentation'
2. Go to 'settings -> Advanced Settings Editor -> Text Editor'
3.  Notice the message '[additional property error] handlePaste is not a valid property' on the bottom right hand corner.
4. Reload the page. 'Indent with Tab' is not enabled anymore

## Expected behavior

No '[additional property error] handlePaste is not a valid property' message, and 'Indent with Tab' is enabled after page reload.

## Context

- Operating System and version: Operating System and version: Windows Version 10.0.19042 Build 19042
- Browser and version:  Firefox 84.0.2 (64-bit), Google Chrome Version 91.0.4472.114 (Official Build) (64-bit)

JupyterLab version: v3.0.16

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools react-dom.development.js:26244
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/apputils (required ^3.0.2) remoteEntry.479e2f46faad00872479.js:1:5137
Unsatisfied version 5.1.0-alpha.13 of shared singleton module @jupyterlab/coreutils (required ^5.0.1) remoteEntry.479e2f46faad00872479.js:1:5137
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/apputils (required ^3.0.2) remoteEntry.91cdfed070abe7b67cf7.js:1:4933
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/translation (required ^3.0.2) remoteEntry.91cdfed070abe7b67cf7.js:1:4933
Unsatisfied version 6.1.0-alpha.13 of shared singleton module @jupyterlab/services (required ^6.0.2) remoteEntry.91cdfed070abe7b67cf7.js:1:4933
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/mainmenu (required ^3.0.2) remoteEntry.91cdfed070abe7b67cf7.js:1:4933
Unsatisfied version 5.1.0-alpha.13 of shared singleton module @jupyterlab/coreutils (required ^5.0.1) remoteEntry.91cdfed070abe7b67cf7.js:1:4933
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/notebook (required ^3.0.0) remoteEntry.ca1efc27dc965162ca86.js:1:6232
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/logconsole (required ^3.0.0) remoteEntry.ca1efc27dc965162ca86.js:1:6232
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/settingregistry (required ^3.0.0) remoteEntry.ca1efc27dc965162ca86.js:1:6232
Unsatisfied version 6.1.0-alpha.13 of shared singleton module @jupyterlab/services (required ^6.0.0) remoteEntry.ca1efc27dc965162ca86.js:1:6232
No satisfying version (^3.0.0) of shared module @jupyterlab/outputarea found in shared scope default.
Available versions: 3.1.0-alpha.13 from @jupyterlab/application-top remoteEntry.ca1efc27dc965162ca86.js:1:6620
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/mainmenu (required ^3.0.0) remoteEntry.ca1efc27dc965162ca86.js:1:6232
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/rendermime (required ^3.0.0) remoteEntry.ca1efc27dc965162ca86.js:1:6232
Unsatisfied version 5.1.0-alpha.13 of shared singleton module @jupyterlab/coreutils (required ^5.0.0-rc.14) remoteEntry.5c46d09863feb29e162a.js:1:5134
Unsatisfied version 6.1.0-alpha.13 of shared singleton module @jupyterlab/services (required ^6.0.0-rc.14) remoteEntry.5c46d09863feb29e162a.js:1:5134
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/apputils (required ^3.0.0-rc.14) remoteEntry.5c46d09863feb29e162a.js:1:5134
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/translation (required ^3.0.0-rc.14) remoteEntry.5c46d09863feb29e162a.js:1:5134
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/statusbar (required ^3.0.0-rc.14) remoteEntry.5c46d09863feb29e162a.js:1:5134
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/application (required ^3.0.6) remoteEntry.fa40ab1c207171c20b8b.js:1:4855
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/launcher (required ^3.0.5) remoteEntry.fa40ab1c207171c20b8b.js:1:4855
Unsatisfied version 5.1.0-alpha.13 of shared singleton module @jupyterlab/coreutils (required ^5.0.3) remoteEntry.fa40ab1c207171c20b8b.js:1:4855
Unsatisfied version 3.1.0-alpha.13 of shared singleton module @jupyterlab/apputils (required ^3.0.5) remoteEntry.fa40ab1c207171c20b8b.js:1:4855
Activating jupyter-offlinenotebook JupyterLab extension 751.478bb3b251bd2e02a937.js:1:883
offline-notebook repoid: https://github.com/jupyterlab/jupyterlab 751.478bb3b251bd2e02a937.js:1:1058
offline-notebook repoLabel: GitHub 751.478bb3b251bd2e02a937.js:1:1190
offline-notebook binderRefUrl: https://github.com/jupyterlab/jupyterlab/tree/105c72631e5d7c248a3cbee8024e880410b51685 751.478bb3b251bd2e02a937.js:1:1255
offline-notebook binderPersistentUrl: https://mybinder.org/v2/gh/jupyterlab/jupyterlab/105c72631e5d7c248a3cbee8024e880410b51685 751.478bb3b251bd2e02a937.js:1:1330
Starting application in workspace: "default" index.tsx:442:12
Starting WebSocket: wss://hub-binder.mybinder.ovh/user/jupyterlab-jupyterlab-dnui18mx/lab-dev/api/kernels/d0e967e2-966a-4884-b879-02b8b599ae53 default.ts:1233:12
@jupyterlab/fileeditor-extension:plugin validation errors: 
Array [ {…} ]
settingregistry.ts:559:14
Failed to set @jupyterlab/fileeditor-extension:plugin: @jupyterlab/fileeditor-extension:plugin failed to validate; check console. commands.ts:363:20
Kernel: dead (d0e967e2-966a-4884-b879-02b8b599ae53) default.ts:1586:16
Some cookies are misusing the recommended “SameSite“ attribute 110
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernelspecs
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernelspecs
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. terminals
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. kernels
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. sessions
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. contents
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
Cookie “username-hub-binder-mybinder-ovh” has been rejected because it is already expired. v1
</pre>
</details>

**Comment by krassowski** [comment]
Thank you for the report. It looks like a duplicate of https://github.com/jupyterlab/jupyterlab/issues/9411.

The good news is that there already is a pull request open with a fix that may be included in 3.1.

 Do you think that we can close this one and keep tracking the progress in https://github.com/jupyterlab/jupyterlab/issues/9411?

**Comment by richardkang112** [comment]
@krassowski I'll close this issue. Thank you.
