### ISSUE TITLE
Using debugger with xeus-python from separate env

### ISSUE THREAD

**Issue by marvinbernhardt** [jupyterlab/jupyterlab#10497]
## Description

I have my jupyter packages in one conda environment.
In other conda environments I install and register ipykernels, which worked fine so far.
However I can not get the debugger to work with xeus-python and ipykernel installed in a separate environment. Is this supported?

## Reproduce

1. Install jupyter lab in one env called jupyter
2. Install xeus-python and ipykernel in a second env called xeus-python
3. Register kernel from second env `python -m ipykernel install --user --name "xeus-python"  --display-name "Python (xeus)"`
4. Run JupyterLab from first env
5. Open notebook with xeus-python kernel but see no debugger interface

## Expected behavior

Seeing some debugger interface.

## Context

Not a lot of people seem to split jupyter and kernel envs I think.

- Operating System and version: Arch linux, just updated
- Browser and version: 89.0.2
- JupyterLab version: 3.0.16

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
    sanitized

sys.path:
    sanitized

sys.executable:
	/home/marvin/offline/miniconda3/envs/jupyter/bin/python

sys.version:
	3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:32:32) 
	[GCC 9.3.0]

platform.platform():
	Linux-5.10.46-1-lts-x86_64-with-glibc2.33

which -a jupyter:
	/home/marvin/offline/miniconda3/envs/jupyter/bin/jupyter

pip list:
	Package                       Version
	----------------------------- -------------------
	anyio                         3.2.1
	appdirs                       1.4.4
	argon2-cffi                   20.1.0
	async-generator               1.10
	attrs                         21.2.0
	Babel                         2.9.1
	backcall                      0.2.0
	backports.functools-lru-cache 1.6.4
	bleach                        3.3.0
	bqplot                        0.12.29
	brotlipy                      0.7.0
	certifi                       2021.5.30
	cffi                          1.14.5
	chardet                       4.0.0
	cloudpickle                   1.6.0
	cryptography                  3.4.7
	cycler                        0.10.0
	cytoolz                       0.11.0
	dask                          2021.6.2
	decorator                     4.4.2
	defusedxml                    0.7.1
	deprecation                   2.1.0
	entrypoints                   0.3
	fsspec                        2021.6.1
	idna                          2.10
	imagecodecs                   2021.6.8
	imageio                       2.9.0
	importlib-metadata            4.6.0
	ipydatawidgets                4.2.0
	ipykernel                     5.5.5
	ipympl                        0.7.0
	ipython                       7.25.0
	ipython-genutils              0.2.0
	ipyvolume                     0.6.0a8
	ipywebrtc                     0.6.0
	ipywidgets                    7.6.3
	jedi                          0.18.0
	Jinja2                        3.0.1
	json5                         0.9.6
	jsonschema                    3.2.0
	jupyter-client                6.2.0
	jupyter-core                  4.7.1
	jupyter-packaging             0.10.3
	jupyter-server                1.9.0
	jupyterlab                    3.0.16
	jupyterlab-pygments           0.1.2
	jupyterlab-server             2.6.0
	jupyterlab-vim                0.14.2
	jupyterlab-widgets            1.0.0
	kiwisolver                    1.3.1
	locket                        0.2.1
	MarkupSafe                    2.0.1
	matplotlib                    3.4.2
	matplotlib-inline             0.1.2
	mistune                       0.8.4
	nbclassic                     0.3.1
	nbclient                      0.5.3
	nbconvert                     6.1.0
	nbformat                      5.1.3
	nest-asyncio                  1.5.1
	networkx                      2.5.1
	nglview                       3.0.3
	notebook                      6.4.0
	numpy                         1.21.0
	olefile                       0.46
	packaging                     20.9
	pandas                        1.2.5
	pandocfilters                 1.4.3
	parso                         0.8.2
	partd                         1.2.0
	pexpect                       4.8.0
	pickleshare                   0.7.5
	Pillow                        8.2.0
	pip                           21.1.3
	pooch                         1.4.0
	prometheus-client             0.11.0
	prompt-toolkit                3.0.19
	ptyprocess                    0.7.0
	pycparser                     2.20
	Pygments                      2.9.0
	pyOpenSSL                     20.0.1
	pyparsing                     2.4.7
	pyrsistent                    0.17.3
	PySocks                       1.7.1
	python-dateutil               2.8.1
	pythreejs                     2.3.0
	pytz                          2021.1
	PyWavelets                    1.1.1
	PyYAML                        5.4.1
	pyzmq                         22.1.0
	requests                      2.25.1
	requests-unixsocket           0.2.0
	scikit-image                  0.18.1
	scipy                         1.7.0
	Send2Trash                    1.7.1
	setuptools                    52.0.0.post20210125
	six                           1.16.0
	sniffio                       1.2.0
	terminado                     0.10.1
	testpath                      0.5.0
	tifffile                      2021.6.14
	tomlkit                       0.7.2
	toolz                         0.11.1
	tornado                       6.1
	traitlets                     5.0.5
	traittypes                    0.2.1
	urllib3                       1.26.6
	wcwidth                       0.2.5
	webencodings                  0.5.1
	websocket-client              0.58.0
	wheel                         0.36.2
	widgetsnbextension            3.5.1
	zipp                          3.4.1

conda list:
	# packages in environment at /home/marvin/offline/miniconda3/envs/jupyter:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                 conda_forge    conda-forge
	_openmp_mutex             4.5                       1_gnu    conda-forge
	anyio                     3.2.1            py39hf3d152e_0    conda-forge
	appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
	argon2-cffi               20.1.0           py39hbd71b63_2    conda-forge
	async_generator           1.10                       py_0    conda-forge
	attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
	babel                     2.9.1              pyh44b312d_0    conda-forge
	backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
	backports                 1.0                        py_2    conda-forge
	backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
	bleach                    3.3.0              pyh44b312d_0    conda-forge
	blosc                     1.21.0               h9c3ff4c_0    conda-forge
	bqplot                    0.12.29            pyhd8ed1ab_0    conda-forge
	brotli                    1.0.9                h9c3ff4c_4    conda-forge
	brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
	brunsli                   0.1                  he1b5a44_0    conda-forge
	bzip2                     1.0.8                h7f98852_4    conda-forge
	c-ares                    1.17.1               h7f98852_1    conda-forge
	ca-certificates           2021.5.30            ha878542_0    conda-forge
	certifi                   2021.5.30        py39hf3d152e_0    conda-forge
	cffi                      1.14.5           py39he32792d_0    conda-forge
	cfitsio                   3.470                hb418390_7    conda-forge
	chardet                   4.0.0            py39hf3d152e_1    conda-forge
	charls                    2.2.0                h9c3ff4c_0    conda-forge
	cloudpickle               1.6.0                      py_0    conda-forge
	cryptography              3.4.7            py39hbca0aa6_0    conda-forge
	cycler                    0.10.0                     py_2    conda-forge
	cytoolz                   0.11.0           py39h3811e60_3    conda-forge
	dask-core                 2021.6.2           pyhd8ed1ab_0    conda-forge
	decorator                 4.4.2                      py_0    conda-forge
	defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
	deprecation               2.1.0              pyh9f0ad1d_0    conda-forge
	entrypoints               0.3             py39hde42818_1002    conda-forge
	freetype                  2.10.4               h0708190_1    conda-forge
	fsspec                    2021.6.1           pyhd8ed1ab_0    conda-forge
	giflib                    5.2.1                h516909a_2    conda-forge
	idna                      2.10               pyh9f0ad1d_0    conda-forge
	imagecodecs               2021.6.8         py39h44211f0_0    conda-forge
	imageio                   2.9.0                      py_0    conda-forge
	importlib-metadata        4.6.0            py39hf3d152e_0    conda-forge
	ipydatawidgets            4.2.0              pyhd3deb0d_0    conda-forge
	ipykernel                 5.5.5            py39hef51801_0    conda-forge
	ipympl                    0.7.0              pyhd8ed1ab_0    conda-forge
	ipython                   7.25.0           py39hef51801_0    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	ipyvolume                 0.6.0a8            pyhd8ed1ab_0    conda-forge
	ipywebrtc                 0.6.0              pyhd8ed1ab_0    conda-forge
	ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
	jbig                      2.1               h7f98852_2003    conda-forge
	jedi                      0.18.0           py39hf3d152e_2    conda-forge
	jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
	jpeg                      9d                   h516909a_0    conda-forge
	json5                     0.9.6              pyhd3eb1b0_0  
	jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
	jupyter-packaging         0.10.3             pyhd8ed1ab_0    conda-forge
	jupyter_client            6.2.0              pyhd8ed1ab_0    conda-forge
	jupyter_core              4.7.1            py39hf3d152e_0    conda-forge
	jupyter_server            1.9.0              pyhd8ed1ab_0    conda-forge
	jupyterlab                3.0.16             pyhd8ed1ab_0    conda-forge
	jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
	jupyterlab_server         2.6.0              pyhd8ed1ab_0    conda-forge
	jupyterlab_vim            0.14.2             pyhd8ed1ab_0    conda-forge
	jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
	jxrlib                    1.1                  h516909a_2    conda-forge
	kiwisolver                1.3.1            py39h1a9c180_1    conda-forge
	krb5                      1.19.1               hcc1bbae_0    conda-forge
	lcms2                     2.12                 hddcbb42_0    conda-forge
	ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
	lerc                      2.2.1                h9c3ff4c_0    conda-forge
	libaec                    1.0.5                h9c3ff4c_0    conda-forge
	libblas                   3.9.0                9_openblas    conda-forge
	libcblas                  3.9.0                9_openblas    conda-forge
	libcurl                   7.77.0               h2574ce0_0    conda-forge
	libdeflate                1.7                  h7f98852_5    conda-forge
	libedit                   3.1.20210216         h27cfd23_1  
	libev                     4.33                 h516909a_1    conda-forge
	libffi                    3.3                  h58526e2_2    conda-forge
	libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
	libgfortran-ng            9.3.0               hff62375_19    conda-forge
	libgfortran5              9.3.0               hff62375_19    conda-forge
	libgomp                   9.3.0               h2828fa1_19    conda-forge
	liblapack                 3.9.0                9_openblas    conda-forge
	libnghttp2                1.43.0               h812cca2_0    conda-forge
	libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
	libpng                    1.6.37               hed695b0_2    conda-forge
	libsodium                 1.0.18               h516909a_1    conda-forge
	libssh2                   1.9.0                ha56f1ee_6    conda-forge
	libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
	libtiff                   4.3.0                hf544144_1    conda-forge
	libwebp-base              1.2.0                h7f98852_2    conda-forge
	libzopfli                 1.0.3                he1b5a44_0    conda-forge
	locket                    0.2.1            py39h06a4308_1  
	lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
	markupsafe                2.0.1            py39h3811e60_0    conda-forge
	matplotlib-base           3.4.2            py39h2fa2bec_0    conda-forge
	matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
	mistune                   0.8.4           py39h3811e60_1003    conda-forge
	nbclassic                 0.3.1              pyhd8ed1ab_1    conda-forge
	nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
	nbconvert                 6.1.0            py39hf3d152e_0    conda-forge
	nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
	ncurses                   6.2                  h58526e2_4    conda-forge
	nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
	networkx                  2.5.1              pyhd8ed1ab_0    conda-forge
	nglview                   3.0.3              pyh8a188c0_0    conda-forge
	notebook                  6.4.0              pyha770c72_0    conda-forge
	numpy                     1.21.0           py39hdbf815f_0    conda-forge
	olefile                   0.46               pyh9f0ad1d_1    conda-forge
	openjpeg                  2.4.0                hb52868f_1    conda-forge
	openssl                   1.1.1k               h7f98852_0    conda-forge
	packaging                 20.9               pyh44b312d_0    conda-forge
	pandas                    1.2.5            py39hde0f152_0    conda-forge
	pandoc                    2.14.0.3             h7f98852_0    conda-forge
	pandocfilters             1.4.3            py39h06a4308_1  
	parso                     0.8.2              pyhd8ed1ab_0    conda-forge
	partd                     1.2.0              pyhd8ed1ab_0    conda-forge
	pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
	pickleshare               0.7.5           py39hde42818_1002    conda-forge
	pillow                    8.2.0            py39hf95b381_1    conda-forge
	pip                       21.1.3             pyhd8ed1ab_0    conda-forge
	pooch                     1.4.0              pyhd8ed1ab_0    conda-forge
	prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
	prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
	ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
	pycparser                 2.20               pyh9f0ad1d_2    conda-forge
	pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
	pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
	pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
	pyrsistent                0.17.3           py39h3811e60_2    conda-forge
	pysocks                   1.7.1            py39hf3d152e_3    conda-forge
	python                    3.9.5           h49503c6_0_cpython    conda-forge
	python-dateutil           2.8.1                      py_0    conda-forge
	python_abi                3.9                      2_cp39    conda-forge
	pythreejs                 2.3.0              pyhd8ed1ab_0    conda-forge
	pytz                      2021.1             pyhd8ed1ab_0    conda-forge
	pywavelets                1.1.1            py39hce5d2b2_3    conda-forge
	pyyaml                    5.4.1            py39h3811e60_0    conda-forge
	pyzmq                     22.1.0           py39h37b5a0c_0    conda-forge
	readline                  8.1                  h46c0cb4_0    conda-forge
	requests                  2.25.1             pyhd3deb0d_0    conda-forge
	requests-unixsocket       0.2.0                      py_0    conda-forge
	scikit-image              0.18.1           py39hde0f152_0    conda-forge
	scipy                     1.7.0            py39hee8e79c_0    conda-forge
	send2trash                1.7.1              pyhd8ed1ab_0    conda-forge
	setuptools                52.0.0           py39h06a4308_0  
	six                       1.16.0             pyh6c4a22f_0    conda-forge
	snappy                    1.1.8                he1b5a44_3    conda-forge
	sniffio                   1.2.0            py39hf3d152e_1    conda-forge
	sqlite                    3.36.0               h9cd32fc_0    conda-forge
	terminado                 0.10.1           py39hf3d152e_0    conda-forge
	testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
	tifffile                  2021.6.14          pyhd8ed1ab_0    conda-forge
	tk                        8.6.10               hed695b0_1    conda-forge
	tomlkit                   0.7.2            py39hf3d152e_0    conda-forge
	toolz                     0.11.1                     py_0    conda-forge
	tornado                   6.1              py39h3811e60_1    conda-forge
	traitlets                 5.0.5                      py_0    conda-forge
	traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
	tzdata                    2021a                he74cb21_0    conda-forge
	urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
	wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
	webencodings              0.5.1                      py_1    conda-forge
	websocket-client          0.58.0           py39h06a4308_4  
	wheel                     0.36.2             pyhd3deb0d_0    conda-forge
	widgetsnbextension        3.5.1            py39hf3d152e_4    conda-forge
	xz                        5.2.5                h516909a_1    conda-forge
	yaml                      0.2.5                h516909a_0    conda-forge
	zeromq                    4.3.4                h9c3ff4c_0    conda-forge
	zfp                       0.5.5                h9c3ff4c_5    conda-forge
	zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
	zlib                      1.2.11            h516909a_1010    conda-forge
	zstd                      1.5.0                ha95c52a_0    conda-forge

conda env:
	name: jupyter
	channels:
	  - conda-forge
	  - defaults
	dependencies:
	  - _libgcc_mutex=0.1=conda_forge
	  - _openmp_mutex=4.5=1_gnu
	  - anyio=3.2.1=py39hf3d152e_0
	  - appdirs=1.4.4=pyh9f0ad1d_0
	  - argon2-cffi=20.1.0=py39hbd71b63_2
	  - async_generator=1.10=py_0
	  - attrs=21.2.0=pyhd8ed1ab_0
	  - babel=2.9.1=pyh44b312d_0
	  - backcall=0.2.0=pyh9f0ad1d_0
	  - backports=1.0=py_2
	  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
	  - bleach=3.3.0=pyh44b312d_0
	  - blosc=1.21.0=h9c3ff4c_0
	  - bqplot=0.12.29=pyhd8ed1ab_0
	  - brotli=1.0.9=h9c3ff4c_4
	  - brotlipy=0.7.0=py39h3811e60_1001
	  - brunsli=0.1=he1b5a44_0
	  - bzip2=1.0.8=h7f98852_4
	  - c-ares=1.17.1=h7f98852_1
	  - ca-certificates=2021.5.30=ha878542_0
	  - certifi=2021.5.30=py39hf3d152e_0
	  - cffi=1.14.5=py39he32792d_0
	  - cfitsio=3.470=hb418390_7
	  - chardet=4.0.0=py39hf3d152e_1
	  - charls=2.2.0=h9c3ff4c_0
	  - cloudpickle=1.6.0=py_0
	  - cryptography=3.4.7=py39hbca0aa6_0
	  - cycler=0.10.0=py_2
	  - cytoolz=0.11.0=py39h3811e60_3
	  - dask-core=2021.6.2=pyhd8ed1ab_0
	  - decorator=4.4.2=py_0
	  - defusedxml=0.7.1=pyhd8ed1ab_0
	  - deprecation=2.1.0=pyh9f0ad1d_0
	  - entrypoints=0.3=py39hde42818_1002
	  - freetype=2.10.4=h0708190_1
	  - fsspec=2021.6.1=pyhd8ed1ab_0
	  - giflib=5.2.1=h516909a_2
	  - idna=2.10=pyh9f0ad1d_0
	  - imagecodecs=2021.6.8=py39h44211f0_0
	  - imageio=2.9.0=py_0
	  - importlib-metadata=4.6.0=py39hf3d152e_0
	  - ipydatawidgets=4.2.0=pyhd3deb0d_0
	  - ipykernel=5.5.5=py39hef51801_0
	  - ipympl=0.7.0=pyhd8ed1ab_0
	  - ipython=7.25.0=py39hef51801_0
	  - ipython_genutils=0.2.0=py_1
	  - ipyvolume=0.6.0a8=pyhd8ed1ab_0
	  - ipywebrtc=0.6.0=pyhd8ed1ab_0
	  - ipywidgets=7.6.3=pyhd3deb0d_0
	  - jbig=2.1=h7f98852_2003
	  - jedi=0.18.0=py39hf3d152e_2
	  - jinja2=3.0.1=pyhd8ed1ab_0
	  - jpeg=9d=h516909a_0
	  - json5=0.9.6=pyhd3eb1b0_0
	  - jsonschema=3.2.0=pyhd8ed1ab_3
	  - jupyter-packaging=0.10.3=pyhd8ed1ab_0
	  - jupyter_client=6.2.0=pyhd8ed1ab_0
	  - jupyter_core=4.7.1=py39hf3d152e_0
	  - jupyter_server=1.9.0=pyhd8ed1ab_0
	  - jupyterlab=3.0.16=pyhd8ed1ab_0
	  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
	  - jupyterlab_server=2.6.0=pyhd8ed1ab_0
	  - jupyterlab_vim=0.14.2=pyhd8ed1ab_0
	  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
	  - jxrlib=1.1=h516909a_2
	  - kiwisolver=1.3.1=py39h1a9c180_1
	  - krb5=1.19.1=hcc1bbae_0
	  - lcms2=2.12=hddcbb42_0
	  - ld_impl_linux-64=2.35.1=hea4e1c9_2
	  - lerc=2.2.1=h9c3ff4c_0
	  - libaec=1.0.5=h9c3ff4c_0
	  - libblas=3.9.0=9_openblas
	  - libcblas=3.9.0=9_openblas
	  - libcurl=7.77.0=h2574ce0_0
	  - libdeflate=1.7=h7f98852_5
	  - libedit=3.1.20210216=h27cfd23_1
	  - libev=4.33=h516909a_1
	  - libffi=3.3=h58526e2_2
	  - libgcc-ng=9.3.0=h2828fa1_19
	  - libgfortran-ng=9.3.0=hff62375_19
	  - libgfortran5=9.3.0=hff62375_19
	  - libgomp=9.3.0=h2828fa1_19
	  - liblapack=3.9.0=9_openblas
	  - libnghttp2=1.43.0=h812cca2_0
	  - libopenblas=0.3.15=pthreads_h8fe5266_1
	  - libpng=1.6.37=hed695b0_2
	  - libsodium=1.0.18=h516909a_1
	  - libssh2=1.9.0=ha56f1ee_6
	  - libstdcxx-ng=9.3.0=h6de172a_19
	  - libtiff=4.3.0=hf544144_1
	  - libwebp-base=1.2.0=h7f98852_2
	  - libzopfli=1.0.3=he1b5a44_0
	  - locket=0.2.1=py39h06a4308_1
	  - lz4-c=1.9.3=h9c3ff4c_0
	  - markupsafe=2.0.1=py39h3811e60_0
	  - matplotlib-base=3.4.2=py39h2fa2bec_0
	  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
	  - mistune=0.8.4=py39h3811e60_1003
	  - nbclassic=0.3.1=pyhd8ed1ab_1
	  - nbclient=0.5.3=pyhd8ed1ab_0
	  - nbconvert=6.1.0=py39hf3d152e_0
	  - nbformat=5.1.3=pyhd8ed1ab_0
	  - ncurses=6.2=h58526e2_4
	  - nest-asyncio=1.5.1=pyhd8ed1ab_0
	  - networkx=2.5.1=pyhd8ed1ab_0
	  - nglview=3.0.3=pyh8a188c0_0
	  - notebook=6.4.0=pyha770c72_0
	  - numpy=1.21.0=py39hdbf815f_0
	  - olefile=0.46=pyh9f0ad1d_1
	  - openjpeg=2.4.0=hb52868f_1
	  - openssl=1.1.1k=h7f98852_0
	  - packaging=20.9=pyh44b312d_0
	  - pandas=1.2.5=py39hde0f152_0
	  - pandoc=2.14.0.3=h7f98852_0
	  - pandocfilters=1.4.3=py39h06a4308_1
	  - parso=0.8.2=pyhd8ed1ab_0
	  - partd=1.2.0=pyhd8ed1ab_0
	  - pexpect=4.8.0=pyh9f0ad1d_2
	  - pickleshare=0.7.5=py39hde42818_1002
	  - pillow=8.2.0=py39hf95b381_1
	  - pip=21.1.3=pyhd8ed1ab_0
	  - pooch=1.4.0=pyhd8ed1ab_0
	  - prometheus_client=0.11.0=pyhd8ed1ab_0
	  - prompt-toolkit=3.0.19=pyha770c72_0
	  - ptyprocess=0.7.0=pyhd3deb0d_0
	  - pycparser=2.20=pyh9f0ad1d_2
	  - pygments=2.9.0=pyhd8ed1ab_0
	  - pyopenssl=20.0.1=pyhd8ed1ab_0
	  - pyparsing=2.4.7=pyh9f0ad1d_0
	  - pyrsistent=0.17.3=py39h3811e60_2
	  - pysocks=1.7.1=py39hf3d152e_3
	  - python=3.9.5=h49503c6_0_cpython
	  - python-dateutil=2.8.1=py_0
	  - python_abi=3.9=2_cp39
	  - pythreejs=2.3.0=pyhd8ed1ab_0
	  - pytz=2021.1=pyhd8ed1ab_0
	  - pywavelets=1.1.1=py39hce5d2b2_3
	  - pyyaml=5.4.1=py39h3811e60_0
	  - pyzmq=22.1.0=py39h37b5a0c_0
	  - readline=8.1=h46c0cb4_0
	  - requests=2.25.1=pyhd3deb0d_0
	  - requests-unixsocket=0.2.0=py_0
	  - scikit-image=0.18.1=py39hde0f152_0
	  - scipy=1.7.0=py39hee8e79c_0
	  - send2trash=1.7.1=pyhd8ed1ab_0
	  - setuptools=52.0.0=py39h06a4308_0
	  - six=1.16.0=pyh6c4a22f_0
	  - snappy=1.1.8=he1b5a44_3
	  - sniffio=1.2.0=py39hf3d152e_1
	  - sqlite=3.36.0=h9cd32fc_0
	  - terminado=0.10.1=py39hf3d152e_0
	  - testpath=0.5.0=pyhd8ed1ab_0
	  - tifffile=2021.6.14=pyhd8ed1ab_0
	  - tk=8.6.10=hed695b0_1
	  - tomlkit=0.7.2=py39hf3d152e_0
	  - toolz=0.11.1=py_0
	  - tornado=6.1=py39h3811e60_1
	  - traitlets=5.0.5=py_0
	  - traittypes=0.2.1=pyh9f0ad1d_2
	  - tzdata=2021a=he74cb21_0
	  - urllib3=1.26.6=pyhd8ed1ab_0
	  - wcwidth=0.2.5=pyh9f0ad1d_2
	  - webencodings=0.5.1=py_1
	  - websocket-client=0.58.0=py39h06a4308_4
	  - wheel=0.36.2=pyhd3deb0d_0
	  - widgetsnbextension=3.5.1=py39hf3d152e_4
	  - xz=5.2.5=h516909a_1
	  - yaml=0.2.5=h516909a_0
	  - zeromq=4.3.4=h9c3ff4c_0
	  - zfp=0.5.5=h9c3ff4c_5
	  - zipp=3.4.1=pyhd8ed1ab_0
	  - zlib=1.2.11=h516909a_1010
	  - zstd=1.5.0=ha95c52a_0
	prefix: /home/marvin/offline/miniconda3/envs/jupyter
</pre>
</details>

**Comment by fcollonval** [comment]
Hey @marvinbernhardt have a look at the documentation of xeus-python to install that kernel: https://xeus-python.readthedocs.io/en/latest/installation.html#installing-the-kernel-spec

> If you are using conda, I strongly suggest you install [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) in the same environment as your JupyterLab. It will make your life easier by dynamically listing available kernels in all environments.

**Comment by marvinbernhardt** [comment]
Thank you so much!
