### ISSUE TITLE
TOC add option to include or not titles from cell outputs

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterlab/jupyterlab#10496]
## Description

In Dask Distributed we recently improved our rich HTML reprs for a few objects. However it appears that some of these objects use `<h1/2/3>` elements in their reprs and they are being listed in the toc.

xref https://github.com/dask/distributed/issues/4949

![image](https://user-images.githubusercontent.com/1610850/123643170-06d15c80-d81c-11eb-91b8-14644a746922.png)

## Reproduce

1. `conda create -n dasktoc -c conda-forge python=3.8 dask distributed jupyterlab -y`
2. Open a new notebook
3. Create a `dask.distributed.Client` object and view the repr
4. See the toc panel

## Expected behavior

I would expect titles from code cell outputs to not be included in the toc, only those from markdown cells.

We can work around this in Dask by using alternative elements and some more CSS, but I wanted to raise this here first. I expect `<hx>` elements may be used in reprs from time to time with unexpected results.

## Context

- Operating System and version: macos 11
- Browser and version: Firefox 89
- JupyterLab version: 3.0.16

**Comment by ian-r-rose** [comment]
Thanks for the report @jacobtomlinson. This is a deliberate feature from the early days of the ToC extension (see the now archived https://github.com/jupyterlab/jupyterlab-toc/pull/16), though one that not everyone likes. The idea was for users to be able to generate TOC entries with code, so we also sniff the cell outputs for header-ish material. It's probably worth making the behavior configurable (I could swear there used to be an issue for this, but I could not find it just now).

**Comment by jasongrout** [comment]
Good to hear from you @ian-r-rose! I hope things are going well.

> I would expect titles from code cell outputs to not be included in the toc, only those from markdown cells.

I would expect the same thing by default, since in general the notebook author is in control of the markdown cells, but is not (directly) in control of the outputs generated by libraries, etc.

**Comment by krassowski** [comment]
I would like this to be configurable too. I have notebooks where I want it to include the headings from outputs, and notebooks where I want it to skip them. Nevertheless we could ignore headings with special class name, e.g.

```html
<h3 class="jp-toc-ignore">Heading from cell output of a package that cares</h1>
```

This could also help if a user wants to skip a specific heading in the notebook. What do you think about this idea?

**Comment by jacobtomlinson** [comment]
This functionality [took me by surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), so my preference would be for the TOC to only use markdown outputs by default. Having a configurable option to include code cell outputs could be useful for those that like the feature.

I also like the idea of having a class to explicitly exclude headings from the TOC. This is something we could quickly implement in Dask regardless of the long term decision.

**Comment by skyetim** [comment]
If no one has taken this, I will have a go.

**Comment by blink1073** [comment]
> If no one has taken this, I will have a go.

Yes, please!
