### ISSUE TITLE
Jupyterlab doesn't find the correct version of nodejs: Says to install >= 12 even though I have 14

### ISSUE THREAD

**Issue by rhedak** [jupyterlab/jupyterlab#10499]
## Description

I've installed jupyterlab 3.0.16 on Ubuntu 18.04
I then tried to install @jupyter-widgets/jupyterlab-manager but I got the error 

"Please install nodejs >=12.0.0 before continuing. nodejs may be installed using conda or directly from the nodejs website."

But I have nodejs v14.17.1 installed...

## Reproduce

1. Install nodejs v14.17.1, jupyterlab 3.0.16 on Ubuntu 18.04
2. Try to install @jupyter-widgets/jupyterlab-manager or any other extension requiring nodejs >= 12

## Expected behavior
Jupyterlab detects the correct version of nodejs

## Context

- Operating System and version: Ubuntu 18.04
- Browser and version: Chrome 91.0.4472.114
- JupyterLab version: 3.0.16

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

$PATH:
        /home/henrik/.local/bin
        /home/henrik/.pyenv/plugins/pyenv-virtualenv/shims
        /home/henrik/.pyenv/shims
        /home/henrik/.pyenv/bin
        /home/henrik/.local/bin
        /usr/local/cuda/bin
        /usr/local/nvidia/bin
        /usr/local/cuda/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/local/cuda-10.1/bin

sys.path:
        /home/henrik/.local/bin
        /usr/lib/python36.zip
        /usr/lib/python3.6
        /usr/lib/python3.6/lib-dynload
        /home/henrik/.local/lib/python3.6/site-packages
        /usr/local/lib/python3.6/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.6.9 (default, Jan 26 2021, 15:33:00) 
        [GCC 8.4.0]

platform.platform():
        Linux-4.15.0-144-generic-x86_64-with-Ubuntu-18.04-bionic

which -a jupyter:
        /home/henrik/.local/bin/jupyter
        /home/henrik/.pyenv/shims/jupyter
        /home/henrik/.local/bin/jupyter
        /usr/bin/jupyter

pip list:
        Package               Version
        --------------------- -----------
        anyio                 3.2.1
        argon2-cffi           20.1.0
        asn1crypto            0.24.0
        async-generator       1.10
        attrs                 21.2.0
        Babel                 2.9.1
        bleach                2.1.2
        certifi               2018.1.18
        cffi                  1.14.5
        chardet               3.0.4
        contextvars           2.4
        cryptography          2.1.4
        cycler                0.10.0
        dataclasses           0.8
        decorator             4.1.2
        entrypoints           0.2.3.post1
        html5lib              0.999999999
        idna                  3.2
        immutables            0.15
        importlib-metadata    4.5.0
        ipykernel             4.8.2
        ipython               5.5.0
        ipython-genutils      0.2.0
        ipywidgets            6.0.0
        Jinja2                2.10
        joblib                1.0.1
        json5                 0.9.6
        jsonschema            3.2.0
        jupyter               1.0.0
        jupyter-client        6.1.12
        jupyter-console       6.4.0
        jupyter-core          4.7.1
        jupyter-server        1.9.0
        jupyterlab            3.0.16
        jupyterlab-server     2.6.0
        jupyterlab-widgets    1.0.0
        keyring               10.6.0
        keyrings.alt          3.0
        kiwisolver            1.3.1
        lightgbm              3.2.1
        MarkupSafe            1.0
        matplotlib            3.3.4
        mistune               0.8.3
        nbclassic             0.3.1
        nbconvert             5.3.1
        nbformat              4.4.0
        notebook              5.2.2
        numpy                 1.19.5
        opencv-contrib-python 4.5.2.54
        opencv-python         4.5.2.54
        packaging             20.9
        pandas                1.1.5
        pandocfilters         1.4.2
        pexpect               4.2.1
        pickleshare           0.7.4
        Pillow                8.2.0
        pip                   21.1.2
        prometheus-client     0.11.0
        prompt-toolkit        3.0.19
        ptyprocess            0.7.0
        pycparser             2.20
        pycrypto              2.6.1
        Pygments              2.2.0
        pygobject             3.26.1
        pyparsing             2.4.7
        pyrsistent            0.17.3
        python-dateutil       2.8.1
        pytz                  2021.1
        pyxdg                 0.25
        pyzmq                 22.1.0
        qtconsole             5.1.0
        QtPy                  1.9.0
        requests              2.18.4
        requests-unixsocket   0.2.0
        scikit-learn          0.24.2
        scipy                 1.5.4
        SecretStorage         2.3.1
        Send2Trash            1.7.1
        setuptools            39.0.1
        simplegeneric         0.8.1
        six                   1.11.0
        sniffio               1.2.0
        ssh-import-id         5.7
        terminado             0.10.1
        testpath              0.3.1
        threadpoolctl         2.1.0
        tornado               6.1
        tqdm                  4.61.0
        traitlets             4.3.2
        typing-extensions     3.10.0.0
        urllib3               1.22
        wcwidth               0.1.7
        webencodings          0.5
        websocket-client      1.1.0
        wheel                 0.30.0
        widgetsnbextension    2.0.1
        zipp                  3.4.1
<img width="1020" alt="Screen Shot 2021-06-29 at 8 09 47" src="https://user-images.githubusercontent.com/5147244/123715613-9d049180-d8b3-11eb-9983-71d43023e0b1.png">
<img width="438" alt="Screen Shot 2021-06-29 at 8 10 14" src="https://user-images.githubusercontent.com/5147244/123715622-9f66eb80-d8b3-11eb-821e-a86b3b41c495.png">

**Comment by fcollonval** [comment]
Hey @rhedak 

Since JupyterLab 3, you don't need to install nodeJS to get most extension working. In particular, you do not need it for ipywidgets. Simply run

```
pip install jupyterlab=3 ipywidgets
```

Then you can check `@jupyter-widgets/jupyterlab-manager` is installed by running:

```
jupyter labextension list
```

**Comment by rhedak** [comment]
Thank you it worked! I wonder why I get the error when I try to do it from the GUI then?

can you help me out how to install the other extensions by code? E.g. @jupyterlab/toc-extension

**Comment by fcollonval** [comment]
ToC is part of JupyterLab since v3.

**Comment by rhedak** [comment]
Thank you very much. I'll close this issue then.
