### ISSUE TITLE
SciPy 2021 Plenary session updates.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#10508]
Apologies for the slightly off-topic issue, 

I'm gathering all project updates from Jupyter to prepare a 5 minutes updates for the SciPy plenary session. 

The discourse thread is here, but does not seem to have seem many updates WRT Jlab.:

https://discourse.jupyter.org/t/scipy-tools-plenary-session-at-scipy-2021/9567/3

We only have 5 minutes for all of Jupyter, so if one of you could post a minimal list of what the jupyterlab team would like to say/announce that would be fantastic.

I think that RTC is a major announcement, as well as debugger.

If you want to provide screenshots as well that would be awesome.

**Comment by agoose77** [comment]
Is it within scope of the talk to mention the new federated extensions? I wouldn't imagine it needs to be a lengthy conversation, probably just want to mention the highlights
* zero build installs (no need for Node)
* single-package installs (via PyPI, conda-forge, etc.)

**Comment by krassowski** [comment]
Additional things to consider as worth mentioning:

- RetroLab as an official remix of JupyterLab catering to users feeling more comfortable with classic layout
- ongoing effort to improve performance, testing of 3.1 pre-releases (or release depending where we will be at) welcome
- ongoing effort to improve accessibility (in a multitude of ways, but color contrast and keyboard navigation may be of general interest), feedback and engagement welcome

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/scipy-tools-plenary-session-at-scipy-2021/9567/9

**Comment by Carreau** [comment]
I'd love if you can expand on the discourse thread, I'm not going to be the one presenting, and having a text for the presenter and something clearer for attendees; what the benefits are etc... would be a huge plus.

**Comment by jtpio** [comment]
Closing as Scipy 2021 is now over.

Thanks all!
