### ISSUE TITLE
Restore test for kernel that does not support debugger

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10525]
## Description

`js-debugger` tests [started failing](https://github.com/jupyterlab/jupyterlab/pull/10519/checks?check_run_id=2957338995#step:9:31729) as can be seen on #10519 and #10524 on "Debugging support" → `#isAvailable` → `should return false for kernels that do not have support for debugging`. This is likely due to `ipykernel` 6 release:

https://github.com/jupyterlab/jupyterlab/blob/dbdefed9db9332381fe4104bdf53ec314451951f/packages/debugger/test/service.spec.ts#L95-L98

I wonder if we have another another kernel that does not support debugging that we could use here?

**Comment by jtpio** [comment]
Thanks for catching this.

> I wonder if we have another another kernel that does not support debugging that we could use here?

Ideally we would continue testing the behavior with kernels that don't support debugging. But maybe the simplest for now would be to remove and skip that test?

**Comment by fcollonval** [comment]
I'll try to tackle this one. It should be possible to use playwright request mock capability (if galata has no strange interaction with that).

**Comment by fcollonval** [comment]
Let's reopen this one as the test needs to be fixed.
