### ISSUE TITLE
Failing CodeQL check on CI

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#10522]
We should check what is happening with the CodeQL check (javascript) now failing on CI:

https://github.com/jupyterlab/jupyterlab/runs/2956252150

Looking at the commits on `master`, it seems to have started with the `3.1.0b0` commit: 50ec56bea3ee8c00c20083da8c3768e51508baba

**Comment by krassowski** [comment]
I opened https://github.com/github/codeql/issues/6190

**Comment by fcollonval** [comment]
The error arises when parsing:

https://github.com/jupyterlab/jupyterlab/blob/c957e3f2b9a31f819a28a99cbbbfd1d08abaea21/packages/services/src/kernel/messages.ts#L134-L150

The error `Maximum call stack size exceeded` arises usually when recursive calls hit a certain limit. So I guess the template couple with `as T` is bringing problem. But why now and not before, I had no idea.

**Comment by krassowski** [comment]
CodeQL team will be updating TypeScript to address this problem, but it may need ~two weeks before ending up in production, see: https://github.com/github/codeql/issues/6190#issuecomment-872900115

Should we just ignore this file for now?

**Comment by jtpio** [comment]
> Should we just ignore this file for now?

Sounds like we could yes. So we can have the CodeQL check green again while the upstream is being worked on.
