### ISSUE TITLE
Widget don't show the first time with akernel

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#10533]
## Description

[akernel](https://github.com/davidbrochart/akernel) is a new Python kernel which supports Comms. Widgets have to be created twice in order to work in Jupyter Lab (they don't display the first time), although it works fine the first time in the Classic Notebook. The issue could be in akernel, but since it works fine in the Classic Notebook, I am not sure.

## Reproduce

1. Create a new environment and install:
```bash
pip install akernel ipywidgets jupyterlab notebook
```
4. Launch `jupyter lab` and select `akernel`. Create a new notebook with the following:
```python
from ipywidgets import IntSlider
slider = IntSlider()
slider
```
There is an `Error displaying widget: model not found` in the notebook the first time the slider is rendered, and an `Error: widget model not found` in the browser console. If you re-execute:
```python
slider = IntSlider()
slider
```
Then the slider is displayed correctly.

## Expected behavior

It should work fine the first time, and it does in the Classic Notebook.

## Context

- Operating System and version: Ubuntu 21.04
- Browser and version: Firefox 89.0.2
- JupyterLab version: 3.0.16

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/david/mambaforge/envs/akernel/bin
	/home/david/mambaforge/condabin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/home/david/mambaforge/envs/akernel/bin
	/home/david/mambaforge/envs/akernel/lib/python39.zip
	/home/david/mambaforge/envs/akernel/lib/python3.9
	/home/david/mambaforge/envs/akernel/lib/python3.9/lib-dynload
	/home/david/mambaforge/envs/akernel/lib/python3.9/site-packages

sys.executable:
	/home/david/mambaforge/envs/akernel/bin/python3.9

sys.version:
	3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:32:32) 
	[GCC 9.3.0]

platform.platform():
	Linux-5.11.0-22-generic-x86_64-with-glibc2.33

which -a jupyter:
	/home/david/mambaforge/envs/akernel/bin/jupyter

pip list:
	Package             Version
	------------------- -------------------
	akernel             0.0.7
	anyio               3.2.1
	argon2-cffi         20.1.0
	async-generator     1.10
	attrs               21.2.0
	Babel               2.9.1
	backcall            0.2.0
	bleach              3.3.0
	certifi             2021.5.30
	cffi                1.14.5
	chardet             4.0.0
	click               7.1.2
	debugpy             1.3.0
	decorator           5.0.9
	defusedxml          0.7.1
	entrypoints         0.3
	idna                2.10
	ipykernel           6.0.1
	ipython             7.25.0
	ipython-genutils    0.2.0
	ipywidgets          7.6.3
	jedi                0.18.0
	Jinja2              3.0.1
	json5               0.9.6
	jsonschema          3.2.0
	jupyter-client      6.1.12
	jupyter-core        4.7.1
	jupyter-server      1.9.0
	jupyterlab          3.0.16
	jupyterlab-pygments 0.1.2
	jupyterlab-server   2.6.0
	jupyterlab-widgets  1.0.0
	MarkupSafe          2.0.1
	matplotlib-inline   0.1.2
	mistune             0.8.4
	nbclassic           0.3.1
	nbclient            0.5.3
	nbconvert           6.1.0
	nbformat            5.1.3
	nest-asyncio        1.5.1
	notebook            6.4.0
	packaging           20.9
	pandocfilters       1.4.3
	parso               0.8.2
	pexpect             4.8.0
	pickleshare         0.7.5
	pip                 21.1.3
	prometheus-client   0.11.0
	prompt-toolkit      3.0.19
	ptyprocess          0.7.0
	pycparser           2.20
	Pygments            2.9.0
	pyparsing           2.4.7
	pyrsistent          0.18.0
	python-dateutil     2.8.1
	pytz                2021.1
	pyzmq               22.1.0
	requests            2.25.1
	requests-unixsocket 0.2.0
	Send2Trash          1.7.1
	setuptools          49.6.0.post20210108
	six                 1.16.0
	sniffio             1.2.0
	terminado           0.10.1
	testpath            0.5.0
	tornado             6.1
	traitlets           5.0.5
	typer               0.3.2
	urllib3             1.26.6
	wcwidth             0.2.5
	webencodings        0.5.1
	websocket-client    1.1.0
	wheel               0.36.2
	widgetsnbextension  3.5.1

conda list:
	# packages in environment at /home/david/mambaforge/envs/akernel:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                 conda_forge    conda-forge
	_openmp_mutex             4.5                       1_gnu    conda-forge
	akernel                   0.0.7                    pypi_0    pypi
	anyio                     3.2.1                    pypi_0    pypi
	argon2-cffi               20.1.0                   pypi_0    pypi
	async-generator           1.10                     pypi_0    pypi
	attrs                     21.2.0                   pypi_0    pypi
	babel                     2.9.1                    pypi_0    pypi
	backcall                  0.2.0                    pypi_0    pypi
	bleach                    3.3.0                    pypi_0    pypi
	ca-certificates           2021.5.30            ha878542_0    conda-forge
	certifi                   2021.5.30        py39hf3d152e_0    conda-forge
	cffi                      1.14.5                   pypi_0    pypi
	chardet                   4.0.0                    pypi_0    pypi
	click                     7.1.2                    pypi_0    pypi
	debugpy                   1.3.0                    pypi_0    pypi
	decorator                 5.0.9                    pypi_0    pypi
	defusedxml                0.7.1                    pypi_0    pypi
	entrypoints               0.3                      pypi_0    pypi
	idna                      2.10                     pypi_0    pypi
	ipykernel                 6.0.1                    pypi_0    pypi
	ipython                   7.25.0                   pypi_0    pypi
	ipython-genutils          0.2.0                    pypi_0    pypi
	ipywidgets                7.6.3                    pypi_0    pypi
	jedi                      0.18.0                   pypi_0    pypi
	jinja2                    3.0.1                    pypi_0    pypi
	json5                     0.9.6                    pypi_0    pypi
	jsonschema                3.2.0                    pypi_0    pypi
	jupyter-client            6.1.12                   pypi_0    pypi
	jupyter-core              4.7.1                    pypi_0    pypi
	jupyter-server            1.9.0                    pypi_0    pypi
	jupyterlab                3.0.16                   pypi_0    pypi
	jupyterlab-pygments       0.1.2                    pypi_0    pypi
	jupyterlab-server         2.6.0                    pypi_0    pypi
	jupyterlab-widgets        1.0.0                    pypi_0    pypi
	ld_impl_linux-64          2.36.1               hea4e1c9_0    conda-forge
	libffi                    3.3                  h58526e2_2    conda-forge
	libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
	libgomp                   9.3.0               h2828fa1_19    conda-forge
	libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
	markupsafe                2.0.1                    pypi_0    pypi
	matplotlib-inline         0.1.2                    pypi_0    pypi
	mistune                   0.8.4                    pypi_0    pypi
	nbclassic                 0.3.1                    pypi_0    pypi
	nbclient                  0.5.3                    pypi_0    pypi
	nbconvert                 6.1.0                    pypi_0    pypi
	nbformat                  5.1.3                    pypi_0    pypi
	ncurses                   6.2                  h58526e2_4    conda-forge
	nest-asyncio              1.5.1                    pypi_0    pypi
	notebook                  6.4.0                    pypi_0    pypi
	openssl                   1.1.1k               h7f98852_0    conda-forge
	packaging                 20.9                     pypi_0    pypi
	pandocfilters             1.4.3                    pypi_0    pypi
	parso                     0.8.2                    pypi_0    pypi
	pexpect                   4.8.0                    pypi_0    pypi
	pickleshare               0.7.5                    pypi_0    pypi
	pip                       21.1.3             pyhd8ed1ab_0    conda-forge
	prometheus-client         0.11.0                   pypi_0    pypi
	prompt-toolkit            3.0.19                   pypi_0    pypi
	ptyprocess                0.7.0                    pypi_0    pypi
	pycparser                 2.20                     pypi_0    pypi
	pygments                  2.9.0                    pypi_0    pypi
	pyparsing                 2.4.7                    pypi_0    pypi
	pyrsistent                0.18.0                   pypi_0    pypi
	python                    3.9.5           h49503c6_0_cpython    conda-forge
	python-dateutil           2.8.1                    pypi_0    pypi
	python_abi                3.9                      2_cp39    conda-forge
	pytz                      2021.1                   pypi_0    pypi
	pyzmq                     22.1.0                   pypi_0    pypi
	readline                  8.1                  h46c0cb4_0    conda-forge
	requests                  2.25.1                   pypi_0    pypi
	requests-unixsocket       0.2.0                    pypi_0    pypi
	send2trash                1.7.1                    pypi_0    pypi
	setuptools                49.6.0           py39hf3d152e_3    conda-forge
	six                       1.16.0                   pypi_0    pypi
	sniffio                   1.2.0                    pypi_0    pypi
	sqlite                    3.36.0               h9cd32fc_0    conda-forge
	terminado                 0.10.1                   pypi_0    pypi
	testpath                  0.5.0                    pypi_0    pypi
	tk                        8.6.10               hed695b0_1    conda-forge
	tornado                   6.1                      pypi_0    pypi
	traitlets                 5.0.5                    pypi_0    pypi
	typer                     0.3.2                    pypi_0    pypi
	tzdata                    2021a                he74cb21_0    conda-forge
	urllib3                   1.26.6                   pypi_0    pypi
	wcwidth                   0.2.5                    pypi_0    pypi
	webencodings              0.5.1                    pypi_0    pypi
	websocket-client          1.1.0                    pypi_0    pypi
	wheel                     0.36.2             pyhd3deb0d_0    conda-forge
	widgetsnbextension        3.5.1                    pypi_0    pypi
	xz                        5.2.5                h516909a_1    conda-forge
	zlib                      1.2.11            h516909a_1010    conda-forge

conda env:
	name: akernel
	channels:
	  - conda-forge
	dependencies:
	  - _libgcc_mutex=0.1=conda_forge
	  - _openmp_mutex=4.5=1_gnu
	  - ca-certificates=2021.5.30=ha878542_0
	  - certifi=2021.5.30=py39hf3d152e_0
	  - ld_impl_linux-64=2.36.1=hea4e1c9_0
	  - libffi=3.3=h58526e2_2
	  - libgcc-ng=9.3.0=h2828fa1_19
	  - libgomp=9.3.0=h2828fa1_19
	  - libstdcxx-ng=9.3.0=h6de172a_19
	  - ncurses=6.2=h58526e2_4
	  - openssl=1.1.1k=h7f98852_0
	  - pip=21.1.3=pyhd8ed1ab_0
	  - python=3.9.5=h49503c6_0_cpython
	  - python_abi=3.9=2_cp39
	  - readline=8.1=h46c0cb4_0
	  - setuptools=49.6.0=py39hf3d152e_3
	  - sqlite=3.36.0=h9cd32fc_0
	  - tk=8.6.10=hed695b0_1
	  - tzdata=2021a=he74cb21_0
	  - wheel=0.36.2=pyhd3deb0d_0
	  - xz=5.2.5=h516909a_1
	  - zlib=1.2.11=h516909a_1010
	  - pip:
	    - akernel==0.0.7
	    - anyio==3.2.1
	    - argon2-cffi==20.1.0
	    - async-generator==1.10
	    - attrs==21.2.0
	    - babel==2.9.1
	    - backcall==0.2.0
	    - bleach==3.3.0
	    - cffi==1.14.5
	    - chardet==4.0.0
	    - click==7.1.2
	    - debugpy==1.3.0
	    - decorator==5.0.9
	    - defusedxml==0.7.1
	    - entrypoints==0.3
	    - idna==2.10
	    - ipykernel==6.0.1
	    - ipython==7.25.0
	    - ipython-genutils==0.2.0
	    - ipywidgets==7.6.3
	    - jedi==0.18.0
	    - jinja2==3.0.1
	    - json5==0.9.6
	    - jsonschema==3.2.0
	    - jupyter-client==6.1.12
	    - jupyter-core==4.7.1
	    - jupyter-server==1.9.0
	    - jupyterlab==3.0.16
	    - jupyterlab-pygments==0.1.2
	    - jupyterlab-server==2.6.0
	    - jupyterlab-widgets==1.0.0
	    - markupsafe==2.0.1
	    - matplotlib-inline==0.1.2
	    - mistune==0.8.4
	    - nbclassic==0.3.1
	    - nbclient==0.5.3
	    - nbconvert==6.1.0
	    - nbformat==5.1.3
	    - nest-asyncio==1.5.1
	    - notebook==6.4.0
	    - packaging==20.9
	    - pandocfilters==1.4.3
	    - parso==0.8.2
	    - pexpect==4.8.0
	    - pickleshare==0.7.5
	    - prometheus-client==0.11.0
	    - prompt-toolkit==3.0.19
	    - ptyprocess==0.7.0
	    - pycparser==2.20
	    - pygments==2.9.0
	    - pyparsing==2.4.7
	    - pyrsistent==0.18.0
	    - python-dateutil==2.8.1
	    - pytz==2021.1
	    - pyzmq==22.1.0
	    - requests==2.25.1
	    - requests-unixsocket==0.2.0
	    - send2trash==1.7.1
	    - six==1.16.0
	    - sniffio==1.2.0
	    - terminado==0.10.1
	    - testpath==0.5.0
	    - tornado==6.1
	    - traitlets==5.0.5
	    - typer==0.3.2
	    - urllib3==1.26.6
	    - wcwidth==0.2.5
	    - webencodings==0.5.1
	    - websocket-client==1.1.0
	    - widgetsnbextension==3.5.1
	prefix: /home/david/mambaforge/envs/akernel
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 2021-07-02 23:58:30.946 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-07-02 23:58:31.071 ServerApp] nbclassic | extension was successfully linked.
[I 2021-07-02 23:58:31.088 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-07-02 23:58:31.089 LabApp] JupyterLab extension loaded from /home/david/mambaforge/envs/akernel/lib/python3.9/site-packages/jupyterlab
[I 2021-07-02 23:58:31.089 LabApp] JupyterLab application directory is /home/david/mambaforge/envs/akernel/share/jupyter/lab
[I 2021-07-02 23:58:31.092 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-07-02 23:58:31.092 ServerApp] The port 8888 is already in use, trying another port.
[I 2021-07-02 23:58:31.092 ServerApp] Serving notebooks from local directory: /home/david/github/davidbrochart/akernel
[I 2021-07-02 23:58:31.092 ServerApp] Jupyter Server 1.9.0 is running at:
[I 2021-07-02 23:58:31.092 ServerApp] http://localhost:8889/lab?token=8bad48b7c2643918a15a5077d4eefb6c49cc7415d206e6c0
[I 2021-07-02 23:58:31.092 ServerApp]  or http://127.0.0.1:8889/lab?token=8bad48b7c2643918a15a5077d4eefb6c49cc7415d206e6c0
[I 2021-07-02 23:58:31.093 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-07-02 23:58:31.285 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/david/.local/share/jupyter/runtime/jpserver-78140-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/lab?token=8bad48b7c2643918a15a5077d4eefb6c49cc7415d206e6c0
     or http://127.0.0.1:8889/lab?token=8bad48b7c2643918a15a5077d4eefb6c49cc7415d206e6c0
[W 2021-07-02 23:58:34.372 LabApp] Could not determine jupyterlab build status without nodejs
[I 2021-07-02 23:58:36.000 ServerApp] Kernel started: d3d71527-9ba4-4093-8b42-f6021fea555e
[I 2021-07-02 23:58:36.204 ServerApp] Adapting from protocol version 5.5 (kernel d3d71527-9ba4-4093-8b42-f6021fea555e) to 5.3 (client).
[I 2021-07-02 23:58:36.216 ServerApp] Adapting from protocol version 5.5 (kernel d3d71527-9ba4-4093-8b42-f6021fea555e) to 5.3 (client).
[I 2021-07-02 23:58:36.232 ServerApp] Adapting from protocol version 5.5 (kernel d3d71527-9ba4-4093-8b42-f6021fea555e) to 5.3 (client).
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Error: widget model not found
    get_model http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/523.fa256ee012d38a89b65a.js:1
    renderModel http://localhost:8889/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/523.fa256ee012d38a89b65a.js:1
    createRenderedMimetype http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    createOutputItem http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _insertOutput http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    onModelChanged http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    m http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    l http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    emit http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _onListChanged http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    m http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    l http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    emit http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    push http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _add http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    add http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _onIOPub http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _handleIOPub http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    handleMsg http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _handleMessage http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _msgChain http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    promise callback*C/this._onWSMessage http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _createSocket http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    C http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    connectTo http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _connectToKernel http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    setupKernel http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    a http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    connectTo http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    startNew http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _changeKernel http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _startIfNecessary http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _initialize http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    initialize http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _populate http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    promise callback*_populate http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    _revert http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    promise callback*_revert http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    initialize http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    d http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    promise callback*_createOrOpenDocument http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    open http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    openOrReveal http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    execute http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    promise callback*execute http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    execute http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    l http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    restore http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    restore http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    restore http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    H http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
    promise http://localhost:8889/static/lab/jlab_core.4cb3c625b5e8bf236b99.js?v=4cb3c625b5e8bf236b99:2
523.fa256ee012d38a89b65a.js:1:1139
</pre>
</details>

**Comment by echarles** [comment]
It never shows for me at first time for any kernel. I always have to refresh the page...

**Comment by echarles** [comment]
> It never shows for me at first time for any kernel. I always have to refresh the page...

Sorry, I was meaning `I always have to run the cell to view the widget, it does not show up on the first page load`

**Comment by davidbrochart** [comment]
I think you are referring to a notebook that had a widget rendered and which was saved, then opened again. But in my case I'm starting from a new notebook and I actually run the cell, but I need to run it again to view the widget.
