### ISSUE TITLE
Scroll bar jumps in 3.1.0b0

### ISSUE THREAD

**Issue by asteppke** [jupyterlab/jupyterlab#10540]
## Description

When trying out the new beta version 3.1.0b0 and opening a notebook which works without problems in 3.0.16 the scroll bar jumps around and becomes unusable. 

## Reproduce

In a longer notebook trying scrolling up and down. I cannot pinpoint the exact ingredients required to reproduce but here is a video showing the issue:

https://user-images.githubusercontent.com/5851636/124449580-e3f6f900-dd83-11eb-9600-ccbe798ca583.mp4

The notebook contains matplotlib widgets and markdown cells but no other special features.

## Context

This occurs on Windows 10 using Chrome 91 with the following configuration:
````
(jupyter) C:\Users>jupyter labextension list
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
[W 2021-07-05 11:29:15.456 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
JupyterLab v3.1.0b0
C:\tools\miniconda3\envs\jupyter\share\jupyter\labextensions
        jupyter-matplotlib v0.9.0 enabled ok
        jupyterlab-jupytext v1.3.3 enabled ok (python, jupytext)
        nbdime-jupyterlab v2.1.0 enabled ok
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled ok (python, jupyterlab_widgets)
        @ryantam626/jupyterlab_code_formatter v1.4.10 enabled ok (python, jupyterlab-code-formatter)
        @voila-dashboards/jupyterlab-preview v2.0.2 enabled ok (python, voila)

Other labextensions (built into JupyterLab)
   app dir: C:\tools\miniconda3\envs\jupyter\share\jupyter\lab
        @aquirdturtle/collapsible_headings v3.0.0 enabled ok
````

Jupyter lab is installed from conda-forge, conda list states:
````
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyter_server            1.9.0              pyhd8ed1ab_0    conda-forge
jupyterlab                3.1.0b0            pyh62ca5b2_0    conda-forge/label/jupyterlab_beta
jupyterlab_code_formatter 1.4.10             pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.6.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
````

**Comment by krassowski** [comment]
Thank you for the report. This was previously reported in https://github.com/jupyterlab/jupyterlab/issues/10428 and fixed in https://github.com/jupyterlab/jupyterlab/pull/10503; the next beta to be released this week will include this fix.

**Comment by asteppke** [comment]
@krassowski Thank you for the instant reply. I obviously used the wrong search terms and missed the previous reports. Looking very much forward to the next beta!
