### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyterlab#10542]
## Description
The section [Writing Documentation](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#writing-documentation) on Read the Docs is outdated.

The documentation says we need to use `pip` to install the dependencies but the `docs/requirements.txt` file doesn't exist anymore, instead, there is a `conda` env file `docs/environment.yml`.

Also, once we have the dependencies installed, trying to run the test on docs with the command indicated on Read the Docs `py.test --check-links -k .md . || py.test --check-links -k .md --lf .` it fails due to a missing dependency `pytest_tornasync`. But even installing the dependency the command fails with the following error:

```bash
ERROR: usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --check-links
  inifile: /home/carlos/Documents/rtc/docs/jupyterlab/pyproject.toml
  rootdir: /home/carlos/Documents/rtc/docs/jupyterlab

ERROR: usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --check-links
  inifile: /home/carlos/Documents/rtc/docs/jupyterlab/pyproject.toml
  rootdir: /home/carlos/Documents/rtc/docs/jupyterlab
```

## Reproduce
Try to build the documentation following the instructions on [Read the Docs](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#writing-documentation)

**Comment by blink1073** [comment]
Fixed by #10543, thanks!
