### ISSUE TITLE
References are duplicated in tsconfig.test.json

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#10541]
## Description

In `tsconfig.test.json` files like https://github.com/jupyterlab/jupyterlab/blob/master/packages/application/tsconfig.test.json package folders are duplicated.

```json
"references": [
    {
      "path": "../apputils"
    },
    {
      "path": "../coreutils"
    },
    {
      "path": "../docmanager"
    },
    ...
    {
      "path": "."
    },
    {
      "path": "../../testutils"
    },
    {
      "path": "../apputils"
    },
    {
      "path": "../coreutils"
    },
    ...
  ]
```

Is there a reason for that or should this be fixed (I presume it is a consequence of the integrity script).

**Comment by jtpio** [comment]
Thanks, good catch :+1: 

Looks like it might be coming from the following logic?

https://github.com/jupyterlab/jupyterlab/blob/2dbf25bf0e150fec3992697eaa84056ca236ea28/buildutils/src/ensure-package.ts#L309-L338

**Comment by fcollonval** [comment]
Ok I switch this to maintenance.
