### ISSUE TITLE
I can not install jupyterlab-language-pack-zh-CN

### ISSUE THREAD

**Issue by yyf1986** [jupyterlab/jupyterlab#10558]
when I use `pip install jupyterlab-language-pack-zh-CN`,
the comand output like
 `WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fdfa108fe48>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/jupyterlab-language-pack-zh-cn/
ERROR: Could not find a version that satisfies the requirement jupyterlab-language-pack-zh-CN (from versions: none)
ERROR: No matching distribution found for jupyterlab-language-pack-zh-CN`

**Comment by jtpio** [comment]
Thanks @yyf1986.

The package should be available on PyPI: https://pypi.org/project/jupyterlab-language-pack-zh-CN/

Would you mind trying again to see if it's still an issue?
