### ISSUE TITLE
Cells collapsed in notebook stay hidden after moving heading

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10551]
## Description

Cells collapsed in notebook stay hidden (/or in wrong place) after moving the cell with the heading.

## Reproduce

1. Collapse a heading that contains some extra cells below
2. Move the cell with the heading
3. See that the other cells disappeared

![lost-cell-after-drag](https://user-images.githubusercontent.com/5832902/124636876-f3a83780-de80-11eb-84cd-212e97eaf06c.gif)

## Expected behavior

Either:
- the collapsed cell gets moved together with the header
- the  collapsed cell get un-collapsed when the header that was collapsed gets moved

## Context

- JupyterLab version: 3.1b0/master

CC @marthacryan

**Comment by marthacryan** [comment]
I think the most intuitive behavior would be to just move all of the hidden cells along with the heading
