### ISSUE TITLE
jupyter-lab --notebook-dir is broken

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#10573]
## Description

In JupyterLab@2 `jupyter-lab --notebook-dir=/some/path` works. In lab@3 it no longer works via the CLI. 

## Reproduce

`jupyter-lab --notebook-dir=/some/path` 

## Expected behavior

Per `--help`:
```
--notebook-dir=<Unicode>
    The directory to use for notebooks and kernels.
    Default: ''
    Equivalent to: [--ServerApp.root_dir]
```

## Context

- Operating System and version: Linux
- Browser and version: Chrome
- JupyterLab version: 3.1.0b1

**Comment by goanpeca** [comment]
Will take a look.

**Comment by goanpeca** [comment]
@mlucool I tried with the latest pip version and things work as expected for me.

I did this:

```bash
conda create -n jlab python -c conda-forge
conda activate jlab
pip install jupyterlab --pre
jupyter-lab --notebook-dir /Users/
```

**Comment by mlucool** [comment]
FTR, this was my bug. My contents manger imported from `notebook` instead of `jupyter_server`
