### ISSUE TITLE
ToC Run Cell(s) Bug (Prop#256497)

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#10581]
## Description

The ToC should execute all cells in a header, even when code cells are hidden. Also, sometimes I click execute and the cell does not run (maybe the kernel is busy). See gif below

## Reproduce

![runCells](https://user-images.githubusercontent.com/1813603/124977611-ace04c00-dffe-11eb-88e0-a21ec29fe52c.gif)

## Context

- Operating System and version: Linux
- Browser and version: Chrome
- JupyterLab version: 3.1.0b1

CC @jess-x

**Comment by jess-x** [comment]
Thanks @mlucool for reporting this. I will take a look :)

**Comment by andrewfulton9** [comment]
I haven't found exactly what is causing this issue, but this seems to only be an issue with 3.1.x. I can reproduce on that branch, but not on 3.2.x, 3.3.x or master branch.

**Comment by krassowski** [comment]
I believe we can closing this as fixed in https://github.com/jupyterlab/jupyterlab/pull/10729 and back-ported in https://github.com/jupyterlab/jupyterlab/pull/11375 (which was released in 3.2.2).
