### ISSUE TITLE
Add Table of Contents to User Guide documentation

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10597]
### Problem

* There is no documentation for Table of Contents
* Multiple new ToC options and conditional behaviour was (/is going to be) introduced recently,
   * including already merged:
      * [ ] #9994,
      * [ ] #10167 
    * and upcoming:
       * [ ] #10545,
       * [ ] #10537 (esp. `jp-toc-ignore` class)

### Proposed Solution

Add a brief overview of ToC into the User Guide part of the documentation as a new section.

- [ ] The collapsing behaviour may not be immediately apparent since it uses blue bar rather than caret down/up icons, so it should be demonstrated. This is demonstrated by user question in #9902.

**Comment by AnudeepGunukula** [comment]
Hi i am interested in this project. I have started working on it. Will try to add the table of contents to user guide documentation

**Comment by AnudeepGunukula** [comment]
Hi krassowski,  "jupyterlab/docs/source/user/" is this the path where Toc.rst documentation for user is to be added ?

**Comment by AnudeepGunukula** [comment]
I have also seen that there is no README.md in jupyterlab/packages/toc/
assign issue to me i will complete both of them and will make a pr

**Comment by krassowski** [comment]
> "jupyterlab/docs/source/user/" is this the path where Toc.rst documentation for user is to be added ?

Yes, `toc.rst` (lowercase for consistency) in https://github.com/jupyterlab/jupyterlab/tree/master/docs/source/user sounds good to me.

> I have also seen that there is no README.md in jupyterlab/packages/toc/

Good catch! This could be useful too, but I think it is a bit lower priority.

> assign issue to me i will complete both of them and will make a pr

Assigned! Please let me know if you have any questions or problems.

**Comment by AnudeepGunukula** [comment]
Thankyou krassowski , 
everything is now clear. i started working
