### ISSUE TITLE
Select file by typing in the file browser

### ISSUE THREAD

**Issue by StevenCHowell** [jupyterlab/jupyterlab#1059]
It would be nice to be able to select a file, or narrow the selection, by typing in the file browser.  For example, if I had many files in a directory and I want to open the file titled `example.ipynb`, I would like to be able to start typing `ex` and the file selector highlights the first file that begins with `ex`.

**Comment by stvn66** [comment]
As a note, as of October 2016, the bit of code that currently handles this is line 197 of [src/csvwidget/widget.ts](https://github.com/jupyter/jupyterlab/blob/master/src/csvwidget/widget.ts).

**Comment by stvn66** [comment]
I do not have time to edit and test this right now but if regular expressions are interpreted, adding an option for `'\+s'` should select all continuous space characters.

**Comment by eskirk** [comment]
I'll check this out now, hopefully the fix will be as simple as that.

**Comment by blink1073** [comment]
Fixed by #2190.
