### ISSUE TITLE
Responsive document toolbars

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#10595]
### Problem

Documents such as notebooks in JupyterLab can have a toolbar of widgets (buttons, dropdowns, etc.). Extensions can add widgets to the toolbars and for a given panel width, the total number of widgets may not fit in the available space. Currently, buttons that overflow off the right side of the toolbar are not visible and there is no way for users to see or use those widgets. 

### Proposed Solution

We should explore ways to make the extensible toolbar widgets responsive. The solution I would propose is to put widgets that don't fit behind a triple-doc or "more" button that contains the additional widgets. This is a common pattern is responsive toolbar design.

One aspect we will need to consider is which widgets will be hidden. My sense is that builtin widgets of JupyterLab should be hidden last. We may need additional widget metadata or sectioning in the toolbar that can be used to determine which widgets are hidden in the "more" button.

### Additional context

https://github.com/jupyterlab/jupyterlab/pull/10469 does help some by allowing users to change the content of the toolbars using settings. But as the user adjusts the width of panels, this can still be an issue.

**Comment by jasongrout** [comment]
> triple-doc

triple-dot?

Another thing I've seen is a double chevron, like &raquo;

**Comment by fcollonval** [comment]
> We may need additional widget metadata

FYI VS Code has a notion of primary/secondary items to distinguish those that will be gathered in a sub menu or not.

**Comment by 3coins** [comment]
I will start looking into this, will add some screenshots of possible solutions.

**Comment by fcollonval** [comment]
Hey @3coins if you can provide you support for technical question. The best would be to open quickly a PR so we can discuss there. Or you can contact me via [gitter](https://gitter.im/jupyterlab/jupyterlab). Let me know also if you want to discuss design for this feature.

**Comment by 3coins** [comment]
> Hey @3coins if you can provide you support for technical question. The best would be to open quickly a PR so we can discuss there. Or you can contact me via [gitter](https://gitter.im/jupyterlab/jupyterlab). Let me know also if you want to discuss design for this feature.

Sure, I don't have any code changes yet to create a pull request. Will contact you on gitter to discuss.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/10720, thanks!

With a follow-up issue: https://github.com/jupyterlab/jupyterlab/issues/10749
