### ISSUE TITLE
[3.1.0rc1] Markdown cell automatically switches to edit mode

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#10619]
## Description

Using `jupyterlab==3.1.0rc1` on Binder:

https://user-images.githubusercontent.com/591645/125591145-f53e5c74-6200-4684-a47c-5288529c1a51.mp4

## Reproduce

1. Open JupyterLab 3.1.0rc1
2. Create a first markdown cell, then a code cell
3. Click on the markdown cell, then the code cell
4. The markdown cell switches to edit mode

Tested with:

- gist: https://gist.github.com/jtpio/c54863279a09e6f2cd2c0216d55df5c2
- Binder: https://mybinder.org/v2/gist/jtpio/c54863279a09e6f2cd2c0216d55df5c2/master?urlpath=/lab

## Expected behavior

The markdown cell should stay as rendered.

## Context

Noticed downstream in https://github.com/jupyterlite/jupyterlite/pull/207

- Browser: Firefox 89 and Chromium 91
- JupyterLab: 3.1.0rc1

**Comment by krassowski** [comment]
This might have been introduced in #10517. My other fix (#10580) for related issue introduced in the culprit PR (#10282) might be a sufficient fix for both, so maybe we could just revert #10580 (or amend it).
