### ISSUE TITLE
Does JupyterLab support keyboard shortcut with '⌘' button on Mac? 

### ISSUE THREAD

**Issue by hawkiyc** [jupyterlab/jupyterlab#10637]
Dear All,

JupyterLab is a wonderful IDE with extraordinary UI. However, I am used to some keyboard shortcuts with the '⌘' button in other IDE, and so, I want those shortcuts can work in JupyterLab too. Hence, I tried to set the keyboard shortcut as following,

`
{"shortcuts":[
{"command": "console:run-forced",
"keys": ["command Enter"],
"selector": ".jp-CodeConsole[data-jp-interaction-mode='notebook'] .jp-CodeConsole-promptCell"},
{"command": "console:run-forced",
"keys": ["command Enter"],
"selector": ".jp-CodeConsole[data-jp-interaction-mode='terminal'] .jp-CodeConsole-promptCell"}]}
`
However, it seems that '⌘+Enter' doesn't work at all. 

Do I miss something or '⌘' is not supported in JupyterLab?

I appreciate and looking forward to your kind help.

Sincerely,

hawkiyc

**Comment by krassowski** [comment]
Yes, but I think it is named `Cmd` or `Accel` (for platform-independent version). In your example it would be `"keys": ["Accel Enter"]` or `"keys": ["Cmd Enter"]`. Please let me know if it worked for you. While it might be good to include it in the docs, I believe that ideally we would revive the shortcut configuration UI and merge it into the core (so it does not get outdated).

There is a bit about platform-specific keyboards in the changelog, but it is only incidental to introduction of optional platform-specific keyboards (and that bit should probably go to extension developer documentation).

https://github.com/jupyterlab/jupyterlab/blob/af98f5be2f7b557e0f355b4f1ea5e513fc79f721/CHANGELOG.md#L1843-L1856

**Comment by hawkiyc** [comment]
HI @krassowski,

Yes, it works fine after setting it to `Cmd Enter`. Thank you very much for your kind help.

Sincerely,

hawkiyc

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/does-jupyterlab-support-keyboard-shortcut-with-button-on-mac/10004/2
