### ISSUE TITLE
Add `activeCellChanged` signal to `NotebookTracker`

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1063]
I am starting to work with @cameronoelsen on a "Cell Tools" panel that will implement the cell toolbar capabilities of the classic notebook. This will be a panel that provide a set of actions that apply to the currently active cell of the active notebook. This includes things like:

* Cell metadata (slideshows, nbgrader, etc.)
* Various cell actions (clear output, hide/show input/output)

To implement this I propose that the `NotebookTracker` have an additional signal, `activeCellChanged` that fires when the active cell of the active notebook changes. Its arg should be the `BaseCellWidget` or `void 0` (if no notebook is active).

@blink1073 @afshin

**Comment by afshin** [comment]
@ellisonbg, @blink1073,

Just to be clear before adding this: it is currently the case that if you have access to the `NotebookPanel` instance (let's call it `panel`), you can access the active cell by referencing `panel.content.activeCell`. Is this insufficient?

You would like to have the tracker offer:

1. `.currentChanged`: a signal that emits a reference to the current notebook panel, if any
2. `.currentWidget`: an attribute on the tracker that gives you a reference to the current notebook panel, if any
3. `.activeCellChanged`: a signal that emits a reference to the currently active cell of the current notebook panel, if any
4. `.activeCell`: an attribute on the tracker that gives you a reference to the active cell of the current notebook panel, if any

Numbers 3 and 4 are basically just convenience wrappers, 1 and 2 were already sufficient to have access to them. I don't have a problem creating them, but I just want to confirm that this is where we want to go.

**Comment by afshin** [comment]
FYI, what I left out above is that `panel.content.activeCellChanged` also exists already.

**Comment by afshin** [comment]
After some additional thought, I realized that the overhead of connecting and disconnecting signals to each notebook panel as the signals come in is onerous and should be handled by the notebook tracker.
