### ISSUE TITLE
When i reopen the Jupyter lab browser, how can i see the output continuously??

### ISSUE THREAD

**Issue by sejin-k** [jupyterlab/jupyterlab#10640]
I want see the output in progress, When i reopen the Jupyter lab browser without turning off Jupyter Server.
For example,
Here are two jupyter browser (same jupyter server)
![그림1](https://user-images.githubusercontent.com/48510236/126076925-da5701c7-cbc6-4856-85e4-efe41174f580.png)
(left is browser A, right is browser B)
So i run the code on browser A, and i turn off the browser but  jupyter server was not shut down. so the code are still running . When i reopen jupyter lab(right picture), the code is running but i can't see the output.
Is there a way to see the output continuously??

**Comment by krassowski** [comment]
Hi @sejin-k I think this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/2833, is this correct? We plan to tackle this for 4.0 release - any help would be greatly appreciated.

**Comment by sejin-k** [comment]
> Hi @sejin-k I think this is a duplicate of #2833, is this correct? We plan to tackle this for 4.0 release - any help would be greatly appreciated.

[#2833](https://github.com/jupyterlab/jupyterlab/issues/2833) is the same issue as I thought. Thank you for your answer :)
