### ISSUE TITLE
[3.1.0rc1] autoscroll center on  output of previously  selected cell  when clicking on new cell with text/code

### ISSUE THREAD

**Issue by danieltomasz** [jupyterlab/jupyterlab#10657]
## Description

After clicking on output, the next click anywhere else on another cell still centre the cell with output from first click
Here is the recording
https://www.dropbox.com/s/nu56qxqq9dx291m/simplescreenrecorder-2021-07-20_19.37.47.mp4?dl=0

I installed fresh pyenv virtualenv with  only  jupyterlab 3.1.rc , this behaviour persisted

Then I cleaned pip cache
I installed fresh pyenv virtualenv with 3. 0.16 , this behaviour diseappered

I installed  again another virtualenv with 3.1.rc , this behaviour persisted

Previosly I reverted to 3. 0.16 without cleaning pip cache, and this behaviour persisted on 3.0.16 too
Cleaning cache and reverting to 3.0.16 helped with the issue

## Reproduce

1.Create a long enough notebook with many cells, some of them have output (plots or any other kind of outpit)
2. Click on  the output of the cell
3. Click on the cell with code/markdown that is below the output
4. Jupyter will autoscroll to the code even when the code cell is positioned OK
5. The same behaviour doesnt happen when I click on the cell with code that is positioned above the cell with output.

## Expected behavior

Position in the notebook will not jump.

## Context

- Operating System and version: Pop OS Linux 21.04
- Browser and version: Firefox 90
- JupyterLab version: Jupyter 3.1rc1

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by krassowski** [comment]
Would you be able to create a GIF reproducing the issue when it does happen?

**Comment by danieltomasz** [comment]
Here is the recording 
https://www.dropbox.com/s/nu56qxqq9dx291m/simplescreenrecorder-2021-07-20_19.37.47.mp4?dl=0

After recording, I would reformulate  my previous  post
After clicking on output, the next  click anywhere else  on another cell still centre the  cell with output  from first click

This behaviour doesn't happen with the clean env with the same extension installed.
It still happens even after disabling the extension and restarting the instance of jupyter lab where it happened.

**Comment by krassowski** [comment]
Thank you. Could it be something with a specific notebook? Did you try to check the same notebook in the clean environment?

**Comment by danieltomasz** [comment]
The same notebook is ok in the clean conda environment 
From the browser developer tools I got this when I am reproducing this behaviour
```
LSP.WidgetAdapter: Editor not found in editor_to_source_line map 364.9d480cbdf22d4a4b738a.js:1:152518
LSP.WidgetAdapter.LSP Highlights: no root position available 364.9d480cbdf22d4a4b738a.js:1:121147
LSP.WidgetAdapter: Editor not found in editor_to_source_line map 364.9d480cbdf22d4a4b738a.js:1:152518
LSP.WidgetAdapter.LSP Highlights: no root position available
```

**Comment by danieltomasz** [comment]
Ok @krassowski  I think I found a possible cause
I installed fresh pyenv  with  3.1.rc , this behaviour persisted 

Then I cleaned pip cache
I installed fresh pyenv  with  3. 0.16 , this behaviour disseapered

Previosly I reverted to   3. 0.16  without cleaning pip cache, and this behaviour persisted on 3.0.16 too

**Comment by krassowski** [comment]
This might be related to https://github.com/jupyterlab/jupyterlab/pull/10491

**Comment by krassowski** [comment]
Actually not, its not that. It seems like it is due to #10517. I reverted part of it https://github.com/jupyterlab/jupyterlab/pull/10664 and it might also fix this one. @danieltomasz could you please test if you can still reproduce it on this binder: https://mybinder.org/v2/gh/krassowski/jupyterlab/fix-unrender-markdown?urlpath=lab-dev ?

**Comment by danieltomasz** [comment]
It seems to be ok now

**Comment by krassowski** [comment]
Hi @danieltomasz the fix was included in Release Candidate 2, I hope it will be working fine for you know, but if you find any other issues please let me know.
