### ISSUE TITLE
Missing cell ID on ICellModel instance

### ISSUE THREAD

**Issue by mwakaba2** [jupyterlab/jupyterlab#10697]
## Description

When I try to access a cell's ID via `cell.id`, it's undefined. However, I'm able to get the id at `cell.model.id`.
The cell's instance type is [`ICellModel`](https://jupyterlab.readthedocs.io/en/latest/api/interfaces/cells.icellmodel.html)

## Reproduce

```typescript
import { NotebookActions } from '@jupyterlab/notebook';

NotebookActions.executionScheduled.connect((_, args) => {
      const { cell } = args;
        console.log(`Cell.id: ${cell.id}`);
        console.log(`Cell.model.id: ${cell.model.id}`);
});

NotebookActions.executed.connect((_, args) => {
        const { cell, notebook, success, error } = args;
        console.log(`Cell.id: ${cell.id}`);
        console.log(`Cell.model.id: ${cell.model.id}`);
});
```

## Expected behavior

Expected the cell id to be defined.

## Context

- Operating System and version: mac Catalina 10.15.7
- Browser and version: Chrome 91
- JupyterLab version: `3.1.0b1`

**Comment by fcollonval** [comment]
The `Cell` class is actually a `Widget`, it's `id` is the DOM id of the widget node. I'm not sure it is desired to have it match the notebook cell id.

**Comment by mwakaba2** [comment]
Hi @fcollonval, ah ok, thanks for the clarification! I'll continue to use the models. Just wasn't sure if the `cell.id` is supposed to be non-empty or not.
