### ISSUE TITLE
JupyterLabs does not find config files when installed in __pypackages__ according to PEP582 (e.g. using pdm)

### ISSUE THREAD

**Issue by pohlt** [jupyterlab/jupyterlab#10696]
## Description

I'm using [PDM](https://github.com/pdm-project/pdm) to install jupyterlab. PDM installs packages according to PEP582, i.e., the packages are installed in a local `__pypackages__` directory.

When I start jupyterlab using `pdm run jupyter-lab` the configuration search paths do not include to directory `__pypackages__/3.8/etc/jupyter` where to configs are actually located. In the browser, I get a "JupyterLab Error - 
JupyterLab application assets not found in "/usr/share/jupyter/lab"" because of the missing configs.

## Analysis

When I use poetry for installation and start jupyterlab with `poetry run jupyter-lab`, jupyterlab seems to interpret the `VIRTUAL_ENV` variable correctly and looks there for the config.

PDM sets a similar variable (I'm not sure if this required or conformant with PEP582) `PEP582_PACKAGES` pointing to `/home/tom/proj/jltest/__pypackages__/3.8` where `etc/jupyter` would be found. If juypterlab included that path in the default search paths, the problem would be solved, I guess.

Thanks for looking into this issue. 🙏🏼 

## Context

- Operating System and version: Linux 5.13.2
- Browser and version: irrelevant
- JupyterLab version: 3.0.16

<details><summary>Troubleshoot Output</summary>
<pre>
> pdm run jupyter troubleshoot
$PATH:
        /bin
        /home/tom/proj/jltest/__pypackages__/3.8/bin
        /home/tom/.local/bin
        /home/tom/.local/bin
        /usr/local/bin
        /usr/bin
        /bin
        /usr/X11R6/bin

sys.path:
        /home/tom/proj/jltest/__pypackages__/3.8/bin
        /usr/lib/python38.zip
        /usr/lib64/python3.8
        /usr/lib64/python3.8/lib-dynload
        /home/tom/proj/jltest/__pypackages__/3.8/lib
        /home/tom/.local/lib/python3.8/site-packages
        /usr/lib64/python3.8/site-packages
        /usr/lib64/python3.8/_import_failed
        /usr/lib/python3.8/site-packages

sys.executable:
        /bin/python3

sys.version:
        3.8.10 (default, May 05 2021, 15:36:36) [GCC]

platform.platform():
        Linux-5.13.2-1-default-x86_64-with-glibc2.2.5

which -a jupyter:
        /home/tom/proj/jltest/__pypackages__/3.8/bin/jupyter

pip list:
        Package             Version
        ------------------- ---------
        anyio               3.3.0
        apipkg              1.5
        apparmor            3.0.1
        appdirs             1.4.4
        argcomplete         1.12.3
        argon2-cffi         20.1.0
        asn1crypto          1.4.0
        async-generator     1.10
        attrs               21.2.0
        Babel               2.9.1
        backcall            0.2.0
        bcrypt              3.2.0
        bleach              3.3.1
        brotlipy            0.7.0
        cached-property     1.5.2
        certifi             2021.5.30
        cffi                1.14.6
        chardet             4.0.0
        charset-normalizer  2.0.3
        click               8.0.1
        cmdln               2.0.0
        configobj           5.0.6
        createrepo-c        0.16.0
        crit                0.0.1
        cryptography        3.3.2
        cupshelpers         1.0
        debugpy             1.4.1
        decorator           5.0.9
        defusedxml          0.7.1
        distro              1.5.0
        docker              4.4.4
        docker-compose      1.28.5
        docker-pycreds      0.4.0
        dockerpty           0.4.1
        docopt              0.6.2
        entrypoints         0.3
        fluidity-sm         0.2.0
        gssapi              1.6.12
        idna                3.2
        importlib-metadata  3.7.2
        iniconfig           0.0.0
        invoke              1.4.1
        ipaddr              2.2.0
        ipykernel           6.0.3
        ipython             7.25.0
        ipython-genutils    0.2.0
        isc                 2.0
        jedi                0.18.0
        Jinja2              3.0.1
        json5               0.9.6
        jsonschema          3.2.0
        jupyter-client      6.2.0
        jupyter-core        4.7.1
        jupyter-server      1.10.1
        jupyterlab          3.0.16
        jupyterlab-pygments 0.1.2
        jupyterlab-server   2.6.1
        lexicon             1.0.0
        LibAppArmor         3.0.1
        MarkupSafe          2.0.1
        matplotlib-inline   0.1.2
        mistune             0.8.4
        more-itertools      8.8.0
        mysqlclient         2.0.3
        nbclassic           0.3.1
        nbclient            0.5.3
        nbconvert           6.1.0
        nbformat            5.1.3
        nest-asyncio        1.5.1
        nftables            0.1
        notebook            6.4.0
        notify2             0.3.1
        ordered-set         3.1.1
        packaging           21.0
        pandocfilters       1.4.3
        paramiko            2.7.2
        parso               0.8.2
        pexpect             4.8.0
        pickleshare         0.7.5
        pip                 20.2.4
        pipx                0.16.3
        ply                 3.11
        prometheus-client   0.11.0
        prompt-toolkit      3.0.19
        protobuf            3.17.3
        psutil              5.8.0
        ptyprocess          0.7.0
        py                  1.10.0
        pyasn1              0.4.8
        pycparser           2.20
        pycups              2.0.1
        pycurl              7.43.0.6
        Pygments            2.9.0
        PyGObject           3.40.1
        PyNaCl              1.4.0
        pyOpenSSL           20.0.1
        pyparsing           2.4.7
        pyrsistent          0.18.0
        PySocks             1.7.1
        python-dateutil     2.8.2
        python-dotenv       0.15.0
        python-linux-procfs 0.6
        pytz                2021.1
        pyudev              0.22.0
        PyYAML              5.4.1
        pyzmq               22.1.0
        requests            2.26.0
        requests-unixsocket 0.2.0
        rpm                 4.16.1.3
        Send2Trash          1.7.1
        setuptools          57.4.0
        six                 1.16.0
        slip                0.6.5
        slip.dbus           0.6.5
        sniffio             1.2.0
        terminado           0.10.1
        testpath            0.5.0
        texttable           1.6.3
        tornado             6.1
        traitlets           5.0.5
        urllib3             1.26.6
        userpath            1.6.0
        wcwidth             0.2.5
        webencodings        0.5.1
        websocket-client    1.1.0
        zipp                3.5.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
> pdm run jupyter lab --debug
[D 2021-07-24 23:17:45.454 ServerApp] Searching ['/home/tom/proj/jltest', '/home/tom/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2021-07-24 23:17:45.454 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2021-07-24 23:17:45.455 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2021-07-24 23:17:45.455 ServerApp] Looking for jupyter_config in /usr/etc/jupyter
[D 2021-07-24 23:17:45.455 ServerApp] Looking for jupyter_config in /home/tom/.jupyter
[D 2021-07-24 23:17:45.455 ServerApp] Looking for jupyter_config in /home/tom/proj/jltest
[D 2021-07-24 23:17:45.456 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2021-07-24 23:17:45.456 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2021-07-24 23:17:45.457 ServerApp] Looking for jupyter_server_config in /usr/etc/jupyter
[D 2021-07-24 23:17:45.457 ServerApp] Looking for jupyter_server_config in /home/tom/.jupyter
[D 2021-07-24 23:17:45.457 ServerApp] Looking for jupyter_server_config in /home/tom/proj/jltest
[D 2021-07-24 23:17:45.460 ServerApp] Paths used for configuration of jupyter_server_config: 
        /etc/jupyter/jupyter_server_config.json
[D 2021-07-24 23:17:45.461 ServerApp] Paths used for configuration of jupyter_server_config: 
        /usr/local/etc/jupyter/jupyter_server_config.json
[D 2021-07-24 23:17:45.462 ServerApp] Paths used for configuration of jupyter_server_config: 
        /usr/etc/jupyter/jupyter_server_config.json
[D 2021-07-24 23:17:45.462 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/tom/.jupyter/jupyter_server_config.json
[I 2021-07-24 23:17:45.486 ServerApp] jupyterlab | extension was successfully linked.
[D 2021-07-24 23:17:45.487 ServerApp] Raising open file limit: soft 1024->4096; hard 524288->524288
[I 2021-07-24 23:17:45.520 LabApp] JupyterLab extension loaded from /home/tom/proj/jltest/__pypackages__/3.8/lib/jupyterlab
[I 2021-07-24 23:17:45.520 LabApp] JupyterLab application directory is /usr/share/jupyter/lab
[E 2021-07-24 23:17:45.521 LabApp] JupyterLab application assets not found in "/usr/share/jupyter/lab"
[E 2021-07-24 23:17:45.521 LabApp] Please run `jupyter lab build` or use a different app directory
[I 2021-07-24 23:17:45.527 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-07-24 23:17:45.528 ServerApp] Serving notebooks from local directory: /home/tom/proj/jltest
[I 2021-07-24 23:17:45.528 ServerApp] Jupyter Server 1.10.1 is running at:
[I 2021-07-24 23:17:45.528 ServerApp] http://localhost:8888/lab?token=f707ac188cfb86dc525263c84a4b920424a74ba80c15c9ec
[I 2021-07-24 23:17:45.528 ServerApp]  or http://127.0.0.1:8888/lab?token=f707ac188cfb86dc525263c84a4b920424a74ba80c15c9ec
[I 2021-07-24 23:17:45.528 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-07-24 23:17:45.557 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/tom/.local/share/jupyter/runtime/jpserver-5734-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=f707ac188cfb86dc525263c84a4b920424a74ba80c15c9ec
     or http://127.0.0.1:8888/lab?token=f707ac188cfb86dc525263c84a4b920424a74ba80c15c9ec
[D 2021-07-24 23:17:47.520 ServerApp] Accepting token-authenticated connection from ::1
[D 2021-07-24 23:17:47.523 LabApp] 200 GET /lab?token=f707ac188cfb86dc525263c84a4b920424a74ba80c15c9ec (::1) 4.28ms
</pre>
</details>

**Comment by krassowski** [comment]
Thanks for bringing this up @pohlt. I believe that PEP 582 is still a draft, is this correct?

Have you tried passing the path to the config file using the `--config` argument? See `jupyter lab --help` for full description :)

**Comment by fcollonval** [comment]
> I believe that PEP 582 is still a draft, is this correct?

Yes it is.

Xref: https://www.python.org/dev/peps/pep-0582/

**Comment by bollwyvl** [comment]
> passing the path to the config file

The (deprecated) `data_files` mechanism, and `zip_safe=False` is _pretty much_ required so that files end up in a _countable number of well-known places_ (about 5), whether installed by `pip`, `conda`, `julia`, `apt`, `cran`, etc. 

In addition to that, there are a number of [environment variables](https://jupyter.readthedocs.io/en/latest/use/jupyter-directories.html#configuration-files), [`traitlets`](https://github.com/jupyterlab/jupyterlab_server/blob/master/jupyterlab_server/config.py#L198), etc. which can be used to add more paths... if the number and location of the extra search paths are _known in advance_.

Adding _one or two_ more paths to the search path is not disasterous, but adding `n` more (e.g. walking parent directories, or worst of all, one per pacakge), as we've discovered in a [number of explorations](https://github.com/jupyter/jupyter_core/pull/209), almost cripples certain activities (e.g. finding/serving static files, looking up templates).

So: much as we don't support serving/finding assets from inside zip files (which _is_ an accepted PEP), I wouldn't hold out hope for jupyter being able to support this discovery automagically, even if the PEP is ratified, backported to all supported pythons, etc.

**Comment by pohlt** [comment]
Turns out that PDM pulls this `__pypackages__` thing off without relying on
PEP582.

Anyway, I understand your point. Thanks for looking into it.
