### ISSUE TITLE
How should sessions be managed?

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#1070]
Since we are thinking about real-time collaboration's constraints and we are already supporting multiple clients connecting to the same session (_e.g._, a console connection to the same session as a notebook), we need to have a coherent policy on when sessions ought to be shut down.

Currently, we expect clients to clean up after themselves: so when you close a notebook or a console, it'll ask if you want to shut down its kernel as well. But there are some cases where we were doing that for users automatically: _e.g._, when the "switch kernel" dialog was used to switch to "None".  An outstanding PR (https://github.com/jupyter/jupyterlab/pull/1052) actually removes that option.

But the larger question remains: should clients be responsible for abandoned sessions? It seems reasonable that if we have a heterogenous environment with many clients connecting to the same server, that we should remove the onus of session management from the client to the server. Perhaps some sort of sweep or garbage collector that says "this session hasn't been touched for **x** minutes, therefore it ought to be discarded".

cc: @ellisonbg @blink1073 @jasongrout @ian-r-rose @SylvainCorlay @sccolbert @minrk @danielballan

**Comment by minrk** [comment]
The "hasn't been touched in some time" certainly makes sense, and I've been meaning to add activity-tracking to kernels, at least.

**Comment by minrk** [comment]
Tracking activity is added server-side in jupyter/notebook#1827

**Comment by ellisonbg** [comment]
Can I close this?

**Comment by blink1073** [comment]
Yep.
