### ISSUE TITLE
Repeated keys only within a Jupyterlab terminal (3.0.16)

### ISSUE THREAD

**Issue by avasbr** [jupyterlab/jupyterlab#10705]
## Description
I'm on the current set of versions for jupyter

jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : not installed
ipython          : 7.25.0
ipykernel        : 6.0.3
jupyter client   : 6.1.12
jupyter lab      : 3.0.16
nbconvert        : 6.1.0
ipywidgets       : not installed
nbformat         : 5.1.3
traitlets        : 5.0.5

.. and I've recently had this issue where, while typing inside the jupyter-lab terminal, I get randomly repeated keys. e.g. "cleaar", "lss", "doocker", etc. There doesn't seem to be a noticeable pattern to when it happens, or to which keys, but it's quite often - maybe every 4th or 5th word I type will have a repeated letter somewhere. Also, this doesn't happen anywhere else; notebooks, text files, bash files, and more generally outside of jupyterlab, so it's definitely not an issue with my keyboard. Only in the terminal. For what it's worth, I use a ducky one 2 sf, and it's wired in. 

Anyone else experiencing anything like this? I couldn't find any other issues around it, and for the last 2-3 years that I've used jupyterlab, I've never experienced this so I'm not sure how to address this. I apologize if this has already been discussed elsewhere, and i'll be happy to read through any threads that may already exist on this topic if someone could point me to it, but I wasn't able to find much. The title of this issue here https://github.com/jupyterlab/jupyterlab/issues/1100 seems to indicate that its' a similar issue but upon reading it, couldn't really tell if it had anything to do with what I just described. 

Thanks!

**Comment by krassowski** [comment]
The JupyterLab terminal is built using xterm.js and indeed there was a recent (1 month old) report of a similar new issue specifically with Chrome 92: https://github.com/xtermjs/xterm.js/issues/3377. Please check with a newer version of Chrome and go to issue in xterm.js repo and let maintainers know what you find, give as many details as possible, and also please keep us updated if you find a solution :)

**Comment by avasbr** [comment]
Ahh, thanks for that link! I was indeed on Chrome 92.0.4515.107 (latest version as of writing) but on Firefox 90.0 I do not have this issue. I'll definitely comment back in this thread if an update to chrome fixes this issue. In the meantime, using Firefox (and it seems other browsers in general) is a perfectly reasonable solution for me so I will close this.
