### ISSUE TITLE
Custom appName reverts to JupyterLab

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab#10722]
## Description

For a custom Lab app, the `appName` (set at build time or via `jupyter-config-data`) should remain customized.

## Reproduce

- Build a custom lab with an `appName` of `CustomLab` or overwrite `index.html` on-the-fly by subclassing `LabApp`
- Open lab
- See `CustomLab` while the moons spin
- Once the workspace loads, it will be replaced with `JupyterLab (workspace stuff)`

## Expected behavior

- The tab (even after updating) remains `CustomLab`

## Context

- JupyterLab version: 3.1.0
- hard-coded here:
  - https://github.com/jupyterlab/jupyterlab/blob/v3.1.0/packages/apputils-extension/src/index.ts#L338
- proposed fix: read the `appName` from `PageConfig`
- working on a reproducer on jupyterlite... but we don't support workspaces yet :rofl:

**Comment by xeliba** [comment]
Sorry for my question being a little off-topic. 

How can you actually configure `appName`. And is it the same as the browser tab name, e.g. in Chrome?

For `jupyterlab==3.0`, I was able to change the name of the browser tab via
`jupyter lab build --name='MyFancyName'`
But it seems that this does not work anymore (not even on jupyterlab==3.1.1).

Actually the broswer tab name now shows something like this for a new notebook:
`Untitled.ipynb (14) - JupyterLab`
What do the parantheses mean?

Best regards and many thanks for your great efforts on JuypterLab!
Its the best analysis environment ever!

**Comment by bollwyvl** [comment]
Actually, we shipped this on 3.1.1 for #10724 (which was my need for right now), so I'm going to close this out...

But yeah, setting the `appName` and a few other things is weird. We ended up shipping a wrapper python package with a custom CLI, and just rewrite the JSON on the fly that comes out of `/lab`, as we have no interest in re-building anything, just helping distinguish in the browser tab bar between vanilla, core lab with all our/the user's extensions, and our extremely hacked-up UI which barely looks like lab when all the bells and whistles are turned on, but works with all the same extensions.

**Comment by SarunasAzna** [comment]
I am testing 3.1.4 and after each build (`jupyter lab build --name='MyFancyName'`) you can see `MyFancyName` for a short time but it is being replaced with `JupyterLab`  immediately. So it seems like the issue is not being solved, or am I doing something wrong?
