### ISSUE TITLE
A backward incompatible change was made to the saveState Signal.

### ISSUE THREAD

**Issue by adpatter** [jupyterlab/jupyterlab#10721]
## Description

A backward incompatible change was made to the saveState Signal.  Previously the Signal emitted with a `completed` message regardless of how the save happened.  Now it appears that if the save was done manually, the Signal emits with `completed-manually` and otherwise emits with `completed`.  
## Reproduce

Connect a Slot to NotebookPanel#context.saveState and observe the change in messages between commits. 

## Expected behavior

I would like to suggest that we have the Signal emit with the `completed` message regardless of how the save event happened.  And, then subsequently emit with a more descriptive message e.g., `completed-manually` or `completed-automatically`, depending on how the save event happened.

Then, perhaps, in 4.0 we can make breaking changes and clean up any Signals that are deemed to be extraneous.

## Context

- JupyterLab version: 3.1

Please see:  https://github.com/jupyterlab/jupyterlab/commit/81b1163d68fc2c4d05bcbb92d1237415d8bb2bab#diff-bd91309321cead1ad13aa66f461c81110113c117fababf12ea04e346b0b5afb5R626

**Comment by adpatter** [comment]
This Issue was mentioned during the 2021-07-28 WebDev Meeting: https://github.com/jupyterlab/team-compass/issues/117

**Comment by krassowski** [comment]
I think that this change can be safely reverted for now as we ended up reverting #10043 in #10609. Once we get the rename feature into 4.0 (/if) then I would even imaging emitting an object rather than a string which could follow something like (very rough draft, names and types subject to change):

```typescript
interface ISaveNotification {
   state: string;
   extra?: any
}
```
