### ISSUE TITLE
Enable `conf.d` style enabling of labextension

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1073]
We now have third party extensions. Before releasing 1.0 we need to convert their enabling to a `conf.d` style approach.

---

Blocked on having a conf.d system for extensions in the notebook server.

**Comment by jasongrout** [comment]
We would like to adopt a conf.d style approach before releasing 1.0 so that people don't have to change their extensions drastically after 1.0.

**Comment by ellisonbg** [comment]
Closing as our extension system is now completely different - I don't think this is relevant any longer.
