### ISSUE TITLE
`null` fileFormat raise `Format is invalid` error 400

### ISSUE THREAD

**Issue by loichuder** [jupyterlab/jupyterlab#10757]
## Description

Playing around with the new `null` fileFormat introduced in #7596, I noticed that it is in fact not usable in its current state. The url to get model contents (https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/contents/index.ts#L1057) translates the option `format: null` into `...&format=null` (`null` is serialized as string by `objectToQueryString`: https://github.com/jupyterlab/jupyterlab/blob/e59aed79d0e61c53088f24b0e0eff8e64557690d/packages/coreutils/src/url.ts#L93).

This throws an error in the backend as the option `'null'` is not in the expected values (`'text'`, `'base64'` or `None`): https://github.com/jupyter-server/jupyter_server/blob/a0f98a0f1a3bc6567ca0a4d64954d1ac5ab1f127/jupyter_server/services/contents/handlers.py#L103.

## Reproduce

Make a GET request to `/api/contents` with `format=null`

## Expected behavior

I see two possbilities for the request to go through:
- `format` should be removed from the URL if `null`
- `format=null` should be converted to `None` on the server-side.

## Context

- Operating System and version: Linux Ubuntu 20.04
- Browser and version: Firefox 90.0
- JupyterLab version: 3.1.1
- `jupyter_server` version: 1.10.1

<details><summary>Command Line Output</summary>
<pre>
[W 2021-08-02 12:54:20.531 ServerApp] 400 GET /api/contents/simple.h5?format=null&type=file&content=0&1627901660525 (127.0.0.1): Format 'null' is invalid
[W 2021-08-02 12:54:20.532 ServerApp] Format 'null' is invalid
</pre>
</details>

**Comment by jasongrout** [comment]
> * `format` should be removed from the URL if `null`
> 
> * `format=null` should be converted to `None` on the server-side.

I haven't looked into this very deeply, but as a general rule, it's probably better to be explicit, i.e., `format=None`?

**Comment by loichuder** [comment]
> I haven't looked into this very deeply, but as a general rule, it's probably better to be explicit, i.e., format=None?

Then, we will run into a similar problem as the query arg is recovered as a string. It will be interpreted as `"None"` (as a string) on the back-end which will trigger the check https://github.com/jupyter-server/jupyter_server/blob/a0f98a0f1a3bc6567ca0a4d64954d1ac5ab1f127/jupyter_server/services/contents/handlers.py#L103

**Comment by fcollonval** [comment]
Looking at the code, there is already a case for which an attribute is deleted before building the request:

https://github.com/jupyterlab/jupyterlab/blob/8c693aec308a57cf716c9a876a0a056b429c45b2/packages/services/src/contents/index.ts#L1064-L1066

Using a similar pattern for format (your first suggestion) sounds the best approach.
