### ISSUE TITLE
Customize user login for JupyterLab

### ISSUE THREAD

**Issue by timfeirg** [jupyterlab/jupyterlab#10765]
### Problem

JupyterHub brings multi-user support to JupyterLab, via a multi-kernel architecture, but now since JupyterLab itself supports real-time collaboration, it's possible for multiple user to operate under the same JupyterLab server, which is even greater collaboration experience than what JupyterHub is offering.

Why? Because JupyterHub spawns a separate kernel for each user, thus it looks like the project cannot benefit from the real-time collaboration support.

Is there any way that we can customize the login process of JupyterLab? e.g. Oauth2. So that JupyterLab can be integrated with existing login service providers?

### Proposed Solution

From [the docs](https://jupyter-server.readthedocs.io/en/latest/other/full-config.html), I noticed there's this `ServerApp.login_handler_class`thing, which defaults to `jupyter_server.auth.login.LoginHandler`, maybe I can override this into my custom Oauth2 login class?

I haven't looked into the code closely, but custom login on top of JupyterLab seems to revolve around the JupyterHub project, so I'm not sure what's the best way to do this.

**Comment by krassowski** [comment]
There is a discussion on RTC in JupyterHub on Jupyter Discurse: https://discourse.jupyter.org/t/plans-on-bringing-rtc-to-jupyterhub/9813/7 - it might be a good place to discuss it there since there are members of both Lab and Hub teams there.
