### ISSUE TITLE
Regression: cursor lands in wrong place on cell split

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10760]
## Description

Split cells is a function that I use pretty often and I expect the cursor to remain in the same place when it was before split, but in 3.1 it goes to the end of the cell instead.

Potentially related to #10297? My guess is that or the shared models for RTC.

## Reproduce

1. Open notebook
2. Create a cell with two lines, insert empty line in between
3. Set cursor on the empty line and trigger split with `Ctrl` + `Shift` + `-`
4. See the cursor go to the end of the second cell rather than stay at the beginning of the cell

JupyterLab 3.0:

![split-3 0](https://user-images.githubusercontent.com/5832902/127896027-d7d90f82-1162-4289-a6e9-adc24cb8de31.gif)

JupyterLab 3.1:

![split-3 1](https://user-images.githubusercontent.com/5832902/127896058-9c1067f3-7266-467b-98d5-35ccaee6721d.gif)

## Expected behavior

As in 3.0.

## Context

- JupyterLab version: 3.1.1

**Comment by krassowski** [comment]
@mlucool was moving the cursor to the end of line part of the behaviour that you requested in #10210? Should we have two code paths depending on whether there is a selection or not?

**Comment by mlucool** [comment]
I agree that the cursor position looks worse in the example above. I too think that the cursor should stay at the same spot relative to where it was in the previous cell in both cases. In the case above, it should be start of line (as you suggest) and at the end of the line when highlighting/using split.
