### ISSUE TITLE
Incomplete widgets display of jupyterlab

### ISSUE THREAD

**Issue by hanmala123** [jupyterlab/jupyterlab#10763]
## Description

In jupyterlab, horizontal scrollbar and picture in widgets is incomplete, it can not display the last picture and the end of scrollbar.
![01](https://user-images.githubusercontent.com/35035210/127909760-d5fd357c-b806-42f4-9b39-daec5c7c24cf.png)

But in classic notebook, it has not this problem.
![00](https://user-images.githubusercontent.com/35035210/127909843-44d38987-961c-4456-b33a-261fb8bcfe4d.png)

## Reproduce
I use widgets of fastai course(fastai.vision.widgets).
I think this is a bug which will happen in widgets which has horizontal scrollbar.

## Expected behavior
looks like in classic notebook.

## Context

- Operating System and version: Windows 10 19043.1110
- Browser and version: Microsoft Edge 92.0.902.62 
- JupyterLab version: 3.1.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
It would really help if you could create a reproducible example, for example a minimal notebook with `fastai.vision.widgets` code that will install its dependencies and run on [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/5a5eb6b?urlpath=lab/tree/demo).

**Comment by hanmala123** [comment]
> It would really help if you could create a reproducible example, for example a minimal notebook with `fastai.vision.widgets` code that will install its dependencies and run on [![Binder](https://camo.githubusercontent.com/581c077bdbc6ca6899c86d0acc6145ae85e9d80e6f805a1071793dbe48917982/68747470733a2f2f6d7962696e6465722e6f72672f62616467655f6c6f676f2e737667)](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/5a5eb6b?urlpath=lab/tree/demo).

This is binder [link](https://hub.gke2.mybinder.org/user/jupyterlab-jupyterlab-demo-ovyrrppw/doc/tree/demo/binder.ipynb)
---
I just copied fastai widget source code in order to not install redundant packages.
In jupyterlab output, it's incomplete, but in  "new view for output", it is normal.
![00](https://user-images.githubusercontent.com/35035210/127964223-5d37d8b7-b9f5-4eff-83df-c7f7b38b372c.png)
![01](https://user-images.githubusercontent.com/35035210/127964233-34e75f59-0c9a-440c-8947-8b4ee44d3d7b.png)

**Comment by krassowski** [comment]
The binder link that you posted does not seem to work. I would recommend you to create a gist: https://gist.github.com/ by dragging notebook into the gist editor and share that gist. I can then create the binder from that.

**Comment by hanmala123** [comment]
> The binder link that you posted does not seem to work. I would recommend you to create a gist: https://gist.github.com/ by dragging notebook into the gist editor and share that gist. I can then create the binder from that.

[gist link](https://gist.github.com/hanmala123/290dabc1269e21d8ea622b9c25a7dc7a)

**Comment by jasongrout** [comment]
Thanks for reporting this.

I think this is an ipywidgets issue. I investigated and narrowed it down to what I think the root problem is at https://github.com/jupyter-widgets/ipywidgets/issues/3247

Let's move the conversation over there.
