### ISSUE TITLE
Do not un-render markdown cells for search and replace if not needed

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10768]
### Problem

Currently the markdown cells get un-rendered for search operations and stay as such until the search bar gets closed. This is annoying visually as the context (e.g. rendered equations) is lost and performance-wise as it causes layout shift in the notebook.

### Proposed Solution

Instead of showing un-rendered cell we can hook into marked.js renderer using its public API (https://marked.js.org/using_pro#renderer) to highlight the matches.

This should provide a substantial performance boost as it can avoid layout shift (assuming the highlights only change background color and do not change text dimensions).

**Comment by Ayad0net** [comment]
The same issue with "**Show Contextual Help**", the Markdown is still un-rendered!

**Comment by fcollonval** [comment]
This is fixed by https://github.com/jupyterlab/jupyterlab/pull/11689
