### ISSUE TITLE
Editor writes inserted text to different in-file location than displayed #2951

### ISSUE THREAD

**Issue by Pardova** [jupyterlab/jupyterlab#10770]
## Description

Open a ipynb file contain "\r\n" at the end of the line. 
Try to edit the line cause error which may cause delete or insert text in wrong location in the same line after saving the file. 
![image](https://user-images.githubusercontent.com/49127268/128165011-4a7cce8a-9ca4-494f-8b53-0fbcbce7ce76.png)
![image](https://user-images.githubusercontent.com/49127268/128165139-1a85efd7-09f5-4358-973e-a444658bddbb.png)
Try to add a "s" at the end of 1st line or "a" at the end of file name at 2nd line cause the same error.  
![image](https://user-images.githubusercontent.com/49127268/128165413-db5c9815-fa37-4936-aee3-f5568b371be2.png)

## Reproduce

1. create a jupyter notebook file and type any words
2. save the file and close it
3. edit the file with text editor and add on "\r\n" at the end of the words
4. re-open the file by jupyter notebook

When copy the text under jupyter lab to another jupyter lab file the condition won't happen again.

## Expected behavior

Maybe filter out the "/r" in opening files or try to fix the error in javascript.

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome 86 92.0.4515.107
- JupyterLab version: Version 2.2.6

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
{"model":"\r\ndata = Data(filepath) # main data object","view":"data = Data(filepath) # main data object","selections":[{"uuid":"2c19a64b-b37d-40ec-8c01-400b3273863d","start":{"line":0,"column":0},"end":{"line":0,"column":0},"style":{"className":"","displayName":"","color":"black"}}],"cursor":{"line":0,"column":0},"lineSep":null,"mode":"text/x-ipython","change":{"from":{"line":0,"ch":0,"sticky":"after"},"to":{"line":2,"ch":0,"sticky":"after","xRel":0},"text":[""],"origin":"+delete","removed":["# open csv files","filepath = \"./ALL_Data_List_66a.csv\"",""]}}

</pre>
</details>

**Comment by krassowski** [comment]
Thank you for the report. Where did this notebook came from? Was it created by another editor perhaps, or downloaded from a specific website? It looks like related to #9465.

**Comment by MichaelMadden-SDev** [comment]
I am experiencing this issue as well, and my notebook did come from a co-worker.  Same \r\n issue

**Comment by krassowski** [comment]
Closing as this was fixed in 3.0.18: https://github.com/jupyterlab/jupyterlab/issues/9465#issuecomment-928868842
