### ISSUE TITLE
The new green "Panel" button opens a new tab that renders a 404 message

### ISSUE THREAD

**Issue by odedbadtcloudinary** [jupyterlab/jupyterlab#10777]
It seems this new green  "Panel" button is an undocumented feature (I googled all around for it): 
<br>
<br>

<img width="300" alt="Screen Shot 2021-08-05 at 12 46 46" src="https://user-images.githubusercontent.com/76327382/128330510-b834a30b-a232-40e6-a49c-237633bcc192.png">
I write a "panel" rich notebook and clicked it and all I got was a new tab with a 404:
<img width="600" alt="Screen Shot 2021-08-05 at 12 47 23" src="https://user-images.githubusercontent.com/76327382/128330484-a21dbb5d-247d-44d2-9c14-d99a988168ec.png">

Is this a bug?

**Comment by krassowski** [comment]
Hi @odedbadtcloudinary, thanks for opening the issue. This is not a part of JupyterLab - we do not have a green Panel button. I think it might be coming from [holoviz Panel](https://panel.holoviz.org/index.html) extension and seems like an installation issue. I would guess that you may have only one part of the extension installed (the frotnend one), but are missing the backend (server extension) part. Or maybe you just need to restart JupyterLab if you installed it recently. But this is just a guess, I do not use that extension.

I think that https://github.com/holoviz/panel might be a good place to seek help. I will mark this one as answered.

**Comment by odedbadtcloudinary** [comment]
Thanks!
