### ISSUE TITLE
It is difficult to find the right width of panel for toolbar to display intended items

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#10826]
#10720 implemented a responsive toolbar by adding a pop-up tray hidden behind a toolbar button `[...]` to collect toolbar items that would overflow. However the current experience when resizing is a bit jumpy:

![resize-event-handling](https://user-images.githubusercontent.com/5832902/129271764-31d117ca-a325-4fe0-addb-2018b737c9a3.gif)

with the relevant code in:

https://github.com/jupyterlab/jupyterlab/blob/b2156c04191082ae6c58b239d766e39dd3f6b8c1/packages/apputils/src/toolbar.tsx#L382-L393

The above code is a custom debouncer (executing the function after the resizing settled), but for a better UX we may need a throttler (executing the function at most as often as, say 150ms). Conveniently we already have a `Throttler` available in `@lumino/polling`.

What do you think @3coins, is this a good idea?

**Comment by 3coins** [comment]
@krassowski 
Yes, this might help with smoothing out the resize. Feel free to assign this issue to me.
