### ISSUE TITLE
Add Solarized application themes

### ISSUE THREAD

**Issue by StevenCHowell** [jupyterlab/jupyterlab#1082]
I am partial to the [Solarized themes](http://ethanschoonover.com/solarized).  It seems a great deal of thought was put into making them.  It would be nice to add these as another theme option.

**Comment by ellisonbg** [comment]
I think that is a good idea. Although, it seems like those theme are focused on the text editor component alone, so we may have to put some effort into figuring out how to apply them more broadly. But worth doing research!

**Comment by jasongrout** [comment]
Moving to backlog - but also Help Wanted - if someone wants to come up with the right css variable settings and submit a PR, that's great!

**Comment by stvn66** [comment]
For what they are worth, here are a few example implementations  of Solarized Dark into applications.

[Wingware IDE](http://wingware.com/)
![wing_solarized_dark](https://cloud.githubusercontent.com/assets/9484229/19365550/444e2978-9161-11e6-8adc-75de46bccedd.png)

[Krusader file browser](http://www.krusader.org/) (note that much of the dark application coloring is actually the [Ambiance Dark Blue theme](https://www.gnome-look.org/content/show.php/Ambiance+Dark+Blue?content=169553))
![krusader_solarized_dark](https://cloud.githubusercontent.com/assets/9484229/19365607/88419b24-9161-11e6-9d40-5860eeab9a3a.png)

[Atom text editor](https://atom.io/)
![atom_solarized_dark](https://cloud.githubusercontent.com/assets/9484229/19365608/8b6d298a-9161-11e6-9927-604bcf30ed1e.png)

I may take a stab at this sometime in the next few months, though if someone else wants to take it please feel free.

**Comment by stvn66** [comment]
I was able to edit [index.css](https://github.com/jupyterlab/jupyterlab/blob/master/src/default-theme/index.css)  to import variablesdark.css instead of variables.css.  This would be the place to add another css file right?  

This is actually a relatively short files, `variablesdark.css` being much shorter than `variables.css`.

**Comment by diazgilberto** [comment]
I create the solarized light for JN. I don't know if the css could work with JL.

[Solarized Light for Jupyter Notebook](https://github.com/data-science-work/solarized-light-jupyter-theme)

**Comment by dschaehi** [comment]
Check my gist for replacing jupyterlab dark theme with solarized dark theme.
https://gist.github.com/dschaehi/ff6d30e6779a683053a1f078af178cdb#gistcomment-2980539

**Comment by jasongrout** [comment]
Cool! You can make a theme extension so people can easily install this theme. See https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#themes, or just copy one of the theme packages in core and modify it for your theme.

**Comment by dschaehi** [comment]
Here is an easy way to install my solarized dark theme:
1. Install the [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en) Extension
2. Install the solarized dark theme available [here](https://userstyles.org/styles/177019/jupyterlab-solarized)

**Comment by dschaehi** [comment]
[AllanChain](https://github.com/AllanChain) created a JupyterLab Solarized dark them. Check this out: https://github.com/AllanChain/jupyterlab-theme-solarized-dark

**Comment by dschaehi** [comment]
> Cool! You can make a theme extension so people can easily install this theme. See https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#themes, or just copy one of the theme packages in core and modify it for your theme.

@jasongrout I think we can close this issue now as there is now an extension for the theme (see my post above)?

**Comment by jtpio** [comment]
> @jasongrout I think we can close this issue now as there is now an extension for the theme (see my post above)?

Yes, thanks @dschaehi. And that theme can now be installed with `pip` for JupyterLab 3.0.

Also searching for "jupyterlab solarized" on common search engines returns that repo as the first result:

![image](https://user-images.githubusercontent.com/591645/139815685-7246dd04-73cd-4fef-913d-05d009b578f7.png)

![image](https://user-images.githubusercontent.com/591645/139815810-32690d37-9353-4aba-a7e4-ceb982be781b.png)

Thanks all!
