### ISSUE TITLE
"The kernel appears to have died. It will restart automatically." error in jupyterlab 3.1.6 that is solved by reverting to jupyter 3.0.5 : 

### ISSUE THREAD

**Issue by JesseRop** [jupyterlab/jupyterlab#10827]
Dear jupyterlab developers,

Many thanks for the great tool!

While importing scvelo 0.2.3 (installed using pip in a conda environment) on jupyterlab 3.1.6, I was getting an error, "The kernel appears to have died. It will restart automatically.".
However, this resolved when I reverted to jupyterlab 3.0.5 and I am able to import scvelo 0.2.3 successfully.

Kindly check on this.

Thanks

**Comment by krassowski** [comment]
Thanks for opening the issue. I tried to reproduce it but my attempts were not successful - `import scvelo` works fine for me when using:

> anndata-0.7.6 llvmlite-0.36.0 loompy-3.0.6 natsort-7.1.1 numba-0.53.1 numexpr-2.7.3 numpy-groupies-0.9.13 scVelo-0.2.3 scanpy-1.8.1 scikit-learn-0.24.2 sinfo-0.3.4 stdlib-list-0.8.0 tables-3.6.1 threadpoolctl-2.2.0 tqdm-4.62.0 umap-learn-0.4.6 xlrd-1.2.0

after installing it with pip in conda environment. I tested with: JupyterLab 3.1.0, 3.1.5, JupyterLab 4.0.0a2 and also checked two different versions of ipykernel (6.1.0 and 5.5.0) and xeus-python kernel 0.12.5.

It would be much easier to help you if you could fill in all the details in the [bug report template](https://github.com/jupyterlab/jupyterlab/issues/new?assignees=&labels=bug&template=bug_report.md). I would also suggest trying a clean installation (a new conda environment).
