### ISSUE TITLE
Update documentation theme to pydata_sphinx_theme

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#10834]
# Background

In #8768 @fcollonval mentioned that the JupyterLab team decided that they'd like to use `pydata-sphinx-theme` in this repository. This is an issue to keep track of the major things you'd need to consider for this. I might be able to help out with this in the coming weeks, but I'm not sure whether I'll have time, so invite others to give it a shot.

# Major tasks to do

- Decide if you want to use a logo image for the PyData theme, or just use `JupyterLab` as the site title.
- Decide what kind of top-level pages do you want? The top navigation bar will have a link for each top-level **page**. (I suggest you convert each `part` into a top-level "index" page and use that.
- Decide on the topbar links etc and other UI elements you'd like [in the theme configuration](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html)
- Decide if you want to change the theme defaults. There are [many ways to customize colors etc](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/customizing.html).

### Additional context

Check out the pydata sphinx theme docs here: https://pydata-sphinx-theme.readthedocs.io/en/latest/index.html

**Comment by fcollonval** [comment]
Thanks for starting this. I'll have a look at the doc.

**Comment by fcollonval** [comment]
Here are my suggestions

> * Decide if you want to use a logo image for the PyData theme, or just use `JupyterLab` as the site title.

I think it will be nice to add the JupyterLab logo as there is one; this will fit the pattern used by jupyter-server (but not by jupyterlab-server)

> * Decide what kind of top-level pages do you want? The top navigation bar will have a link for each top-level **page**. (I suggest you convert each `part` into a top-level "index" page and use that.

I agree with that. This means:
- Getting Started
- User Guide
- Extension Developer Guide
- JupyterLab Developer Guide

External links:

- It will be nice to link to `jupyter-server` and `jupyterlab-server` documentation. Although having the two may be confusing :question: 

> * Decide on the topbar links etc and other UI elements you'd like [in the theme configuration](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html)

External links:

- It will be nice to link to `jupyter-server` and `jupyterlab-server` documentation. Although having the two may be confusing :question: 

Icon links:
- Jupyter.org
- GitHub
- Binder?
- Gitter?
- Discourse?

Definitely add edit in GitHub

> * Decide if you want to change the theme defaults. There are [many ways to customize colors etc](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/customizing.html).

I don't think we need to tune it at first (jupyter-server and jupyterlab-server do not seems doing it).
