### ISSUE TITLE
jupyter: 'serverextension' is not a Jupyter command

### ISSUE THREAD

**Issue by ieee8023** [jupyterlab/jupyterlab#1083]
I followed the install instructions using pip but I cannot enable the jupyterlab serverextension. Is there an added package I need to install?

$ jupyter --version
4.2.0
$ jupyter notebook --version
4.2.3
$ jupyter serverextension enable --py jupyterlab --sys-prefix
jupyter: 'serverextension' is not a Jupyter command

**Comment by jasongrout** [comment]
Thanks. What operating system? Can you find where the jupyter binary is, and look for `jupyter-serverextension` in that same directory?

**Comment by jasongrout** [comment]
How did you install jupyter? Via pip? Anaconda?

**Comment by ieee8023** [comment]
My fault. jupyter-serverextension was installed to ~/.local/bin but my path was set wrong. It's all set now!
