### ISSUE TITLE
typing bracket with highlighted code removes code instead of surrounding it with brackets

### ISSUE THREAD

**Issue by RafalSkolasinski** [jupyterlab/jupyterlab#10835]
Seems like regression between 3.0.x and 3.1.x (works fine on 3.0.16 and 3.0.17 and does not work on 3.1.6)

## Description

When selecting code and pressing `(` or `[` to surround it with brackets code gets removed instead.

## Reproduce

1. Code cell
2. type code
3. select code
4. press `(`

## Expected behavior

Code gets surrounded with brackets and not removed. 

## Context

- Operating System and version: Ubuntu 21.04
- Browser and version: Firefox
- JupyterLab version: 3.1.6

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
Hi @RafalSkolasinski, this is related to the highly requested disabling auto-closing bracket by default, see #5741 (the default changed in JupyterLab 3.1). However, it is easy to re-enable this behaviour as shown in https://github.com/jupyterlab/jupyterlab/issues/5741#issuecomment-896768246. Would that work for you, or would you expect the surrounding with brackets to work even if auto-closing bracket function is disabled?

**Comment by RafalSkolasinski** [comment]
Hi @krassowski, when now googling for the issue I hit few times the "auto-closing" of brackets - first I didn't even think these are related. 

I can confirm that in 3.1.6 if I set `Settings -> Auto Close Brackets` then indeed it starts to work as expected (does not remove the selected code - so it kind of solves the issue for me. 

However, I somehow have the feeling that with closing-brackets option disabled the removal of selected text is not exactly an expected behaviour. 

It is different situation from scenario when user just type `(` and does not want to `)` appear and cursor be set in between.

**Comment by krassowski** [comment]
I agree. I think this should be implemented together with analogue behaviour for `"`, `'` and ` as suggested in #9897 and have a separate setting.

**Comment by jasongrout** [comment]
Thanks for bringing this up. Since the suggestion is already being tracked over in #9897, let's consolidate the discussion over in that issue.

**Comment by halhenke** [comment]
Still happening for me
