### ISSUE TITLE
Trust this notebook dialog missing linkification

### ISSUE THREAD

**Issue by blois** [jupyterlab/jupyterlab#10831]
## Description

The 'trust this notebook' dialog has an anchor tag / URL which isn't rendered as a link:
![image](https://user-images.githubusercontent.com/2152569/129392276-0614eb59-9d70-4579-8ac7-acfaf086c980.png)

## Reproduce
Execute 'Trust Notebook'

## Expected behavior

Anchor is rendered as a navigable link.

## Context

- JupyterLab version:  3.0.16

**Comment by jasongrout** [comment]
For reference, that text is here: https://github.com/jupyterlab/jupyterlab/blob/ae1846768e7cb22fbef63cce325fe5ad395b655f/packages/notebook/src/actions.tsx#L1741
