### ISSUE TITLE
Add option to change application theme

### ISSUE THREAD

**Issue by StevenCHowell** [jupyterlab/jupyterlab#1084]
I find looking at white screen all days strains my eyes, particularly when I switching from dark themed windows (terminal, text editor, etc.) to white themed ones.  I like that jupyterlab provides the option to change the theme from the **Editor > Theme** menu but it would be even better if this changed the theme of all jupyterlab windows.  I realize this gets tricky with plots for publication, which typically have a white background, but interactive plot would be simpler (and look fantastic with a dark theme!).

I was able to edit [index.css](https://github.com/jupyterlab/jupyterlab/blob/master/src/default-theme/index.css)  to import variablesdark.css instead of variables.css.  It would be nice to add a menu option for this.

**Comment by jasongrout** [comment]
Great idea, thanks! We want to have a pretty comprehensive theme selection story.

**Comment by hainm** [comment]
In my opinion, only a few best themes should only available (vs lots of themes). It's very distracting for general users to choose from sea of selections.

**Comment by jasongrout** [comment]
We plan to have several (maybe just light and dark) official themes bundled, but users would be free to distribute their own themes as plugins.

**Comment by hainm** [comment]
Ah agree

**Comment by draperjames** [comment]
I think that this is a great idea. I've made my own [fork of jupyter lab](https://github.com/draperjames/jupyterlab/tree/one-dark-lab) styled after Atom Editor's One Dark UI and Syntax theme. Here's a screenshot:    

![screen_cap636211053122475806](https://cloud.githubusercontent.com/assets/22569604/22373888/c3696296-e471-11e6-956b-719923953d7c.png)

It was pretty easy to get my desired results by manipulating the variables in variables.css but I did have problems changing the color of the svg icons. As a work around I added another variable to the style sheet `--jp-fa-color-invert: .7;` and then added filter styles to all of the relevent icon in icon.css like so:

```css
.jp-SaveIcon {
  -webkit-filter: invert( var(--jp-fa-color-invert) );
  background-image: url(icons/md/save.svg);
}
```
So now the icons can easily be rendered to all shades of gray 😉  from the variables.css file. I was thinking about making a feature request issue with a cleaned up PR with the added variable. What do you guys think?

**Comment by StevenCHowell** [comment]
@draperjames, this looks nice and unified.  How does this compare to, or build on, the existing [index.css](https://github.com/jupyterlab/jupyterlab/blob/master/src/default-theme/index.css) file which calls either [variables.css](https://github.com/jupyterlab/jupyterlab/blob/master/src/default-theme/variables.css) or [variablesdark.css](https://github.com/jupyterlab/jupyterlab/blob/master/src/default-theme/variablesdark.css)?  Does this go to the extent of adding a menu item to change the jupyter system css, similar to how **Editor > Theme** changes the editor colors but for the entire system?  I realize this may be tricky but it would provide great functionality for changing the interface style.

**Comment by draperjames** [comment]
@StevenCHowell thanks! Honestly it is a real hack-job I  hard coded stuff in variables.css as well as some other css files. I wasn't even aware of index.css! But not that I know about I think I'll create a fresh branch with some separate css files callable from index.css. I don't have menu item to change the jupyter system (or jupyter ui?) css but  I'll definitely look into that. Do you happen to know which files have the core menu functionality? Are they the `.ts` files I've been seeing around?

**Comment by jasongrout** [comment]
The .ts files are the original source files (.ts = Typescript). Any plugins can add menu items (for example, the console menu is formed here: https://github.com/jupyterlab/jupyterlab/blob/master/src/console/plugin.ts - search for "menu")

We've wanted to have a theme manager plugin for a while (that's essentially what this issue is tracking), and then each theme could provide a css file that sets the appropriate css variables according to the theme. In order for that to work well, we need the parts of jupyerlab that can be themed to be expressed as CSS variables. It sounds like you found a few more bits that need to be expressed as variables? Can you submit those changes as a PR?

**Comment by draperjames** [comment]
@jasongrout I'd be happy to submit a PR. I'll try to get it in this weekend. BTW I'm really enjoying jupyterlab. Great job yall! 👍 😄

**Comment by jasongrout** [comment]
Sorry, I just realized we left you hanging. The style guide is at https://github.com/jupyterlab/jupyterlab/wiki/TypeScript-Style-Guide (@blink1073, is that still up to date?). There are a lot of Typescript tutorials out there - I found the reference manual great: https://www.typescriptlang.org/docs/tutorial.html

**Comment by jasongrout** [comment]
(@draperjames, see above)

**Comment by jasongrout** [comment]
Basically, I see a theme switching plugin as (1) providing a way to add and remove a style tag on a page with a given set of CSS variable settings, (2) a way for plugins to register new themes (which basically would be a chunk of CSS variable setting code to add in a style tag), and (3) adding say a top-level menu item that lists themes and lets you choose another one.

This wouldn't change the editor themes - I think that would probably need some more work. Perhaps @blink1073 has thought about how we might be able to change the editor themes as he's done work abstracting the editor components out.

**Comment by blink1073** [comment]
Sublime has a `color_scheme` for the text area and a `theme` for UI itself.  I think it is fair to keep them separate.

**Comment by sccolbert** [comment]
cc @nfultz

**Comment by megamindbrian** [comment]
Cross-posting this here in case anyone enters from Google search: 

https://github.com/jupyterlab/jupyterlab/pull/2759

**Comment by ellisonbg** [comment]
I think we can close this, as you can change themes in the settings system in master.
