### ISSUE TITLE
Real-time collaborative editing is broken 

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#10852]
## Description

I  visited the same JupyterLab server (with RTC enabled) from 2 computers. RTC keeps adding copies of existing cells into the notebook. And the worst thing was that the latest change from a computer was lost. 

## Reproduce

I do not know how to reproduce this issue exactly but I can describe my situation here. 
Hopefully, someone can confirm the same observation later. 

1. Started a JupyterLab service with RTC enabled. 
2. Worked on a notebook from a Windows PC for a while.
3. Visit the notebook from a Mac Book (authenticated using the JupyterLab sever's token) while someone is still working on the notebook on the Windows PC. 
4. Put the Mac Book to sleep (by close its lid). 
5. Done working on the notebook on the Windows PC but leave the browser and notebook tabs open. 
6. Several hours later I found that the notebook on the Windows PC has been altered. The most recent changes in the notebook was gone. And existing cells was duplicated and pasted into the notebook. When I visited the JupyterLab server on the Mac Book again, the duplicating existing cells becomes even more obvious. I literally see new cells being added into the notebook. 

## Expected behavior

RTC editing should work well (like Google docs). 

## Context

- JupyterLab 3.1.6 was launched in a Docker container and Docker container was launch from WSL 2 (Ubuntu 20.04).
- Browser One: Chrome 92.0.4515.131 on macOS Big Sur (11.5)
- Browser Two: Chrome on Windows 10

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by hbcarlos** [comment]
Hi @dclong, this is an issue we have been trying to reproduce for a while without success.

Maybe this could be related to #10816, which I'm working on right now.

I'll keep updating this thread with new findings.

**Comment by dmonad** [comment]
This is probably related to the locking mechanism that we implemented. When many users connect, there is a chance that a user with a slow network connection writes a document with a timed-out lock. I recommend that we first increase the lock-timeout and then also check locally whether the lock has expired before overwriting a document.

**Comment by astrojuanlu** [comment]
Possibly this can be closed now that 3.6.0 is released with a revamped collaborative mode?

**Comment by hbcarlos** [comment]
Yes, this can be closed. Thanks, @astrojuanlu.

Please don't hesitate to reopen if this issue happens again.

**Comment by EZBUTD** [comment]
Hi! I'm experiencing what appears to be the same issue described in this issue where cells duplicate at the bottom of the notebook. I'm on jupyterlab 4.0.9. 

Should I create a new issue to document my problem?

**Comment by fcollonval** [comment]
@EZBUTD thanks for reaching out?

 yes please open a new issue and try to provide as much information as you can.
