### ISSUE TITLE
Please consider using appdirs

### ISSUE THREAD

**Issue by NeilGirdhar** [jupyterlab/jupyterlab#10851]
[appdirs](https://pypi.org/project/appdirs/) takes care of OS dependent directories.  Using it would be a small change to [this file](https://github.com/jupyterlab/jupyterlab/blob/e9a3c6e93d7fa598a78e7379124a98cf90d3b4f8/jupyterlab/commands.py#L135).

**Comment by jasongrout** [comment]
That file uses `jupyter_config_path`, from the [jupyter_core](https://github.com/jupyter/jupyter_core/blob/2dc34f70806b6668f965bfaa39623143cb2cda59/jupyter_core/paths.py#L56) package, to be consistent with other Jupyter programs. If we were to switch to using appdirs, `jupyter_core` would likely be the right place to make the change.

**Comment by NeilGirdhar** [comment]
Thanks, I submitted it there.
