### ISSUE TITLE
Error detecting kernel

### ISSUE THREAD

**Issue by cosmoscalibur** [jupyterlab/jupyterlab#1086]
When open an existing notebook, jupyterlab open the notebook with python 2 kernel but metadata of notebook specify python 3 or IR kernel (I haven't used python 2 kernel in my own documents).  
Version of related packages:    
- ipykernel (4.5.0)  
- ipython (5.1.0)  
- ipywidgets (5.2.2)  
- jupyter (1.0.0)  
- jupyter-client (4.4.0)  
- jupyter-console (5.0.0)  
- jupyter-core (4.2.0)  
- jupyterlab (0.5.0)

**Comment by blink1073** [comment]
Hi @cosmoscalibur, can you paste the `kernelspec` portion of the notebook file, as well as the output of `jupyter kernelspec list`?

**Comment by cosmoscalibur** [comment]
Portion of  `kernelspec` from R notebook
```

"kernelspec": {
    "name": "ir",
    "display_name": "R",
    "language": "R"
  }
```
but this notebook open with `jupyter lab` change the kernel to `python 2`.
Output from `jupyter kernelspec list`
    
    ir           /home/cosmoscalibur/.local/share/jupyter/kernels/ir
    julia-0.4    /home/cosmoscalibur/.local/share/jupyter/kernels/julia-0.4
    gnuplot      /usr/local/share/jupyter/kernels/gnuplot
    python3      /usr/local/share/jupyter/kernels/python3

**Comment by blink1073** [comment]
Sorry @cosmoscalibur, this one fell through the cracks.  I suspect it is fixed now by changes we made around the handling of kernelspecs but will verify.

**Comment by blink1073** [comment]
I confirmed that this works now in master (not yet released).

**Comment by cosmoscalibur** [comment]
yes, I confirmed that update works. Thanks.
