### ISSUE TITLE
Auto-close brackets does not work in console

### ISSUE THREAD

**Issue by gioarma** [jupyterlab/jupyterlab#10874]
## Description

After turning on `Auto Close Brackets`, the feature works in the notebook, but not in the console.

## Reproduce

1. Open a new notebook
2. Click on `Settings -> Auto Close Brackets` to turn on the feature
3. Type `(` in the notebook and `()` automatically appears
4. Open a new console for the notebook and repeat 3.  `()` does not appear

## Expected behavior

Auto Close Brackets works also in console

## Context

- Operating System and version: macOS 10.15.7
- Browser and version: Chrome 92.0.4515.159
- JupyterLab version: 3.1.7

**Comment by eemilhaa** [comment]
Was able to reproduce this with:
- Operating system: Linux, Pop_os 21.04
- Browser and version: Firefox 91.0 (64-bit)
- JupyterLab versions 3.1.4 and 3.1.7

Also noticed that disabling/enabling the setting once the console window has been opened seems to work

**Comment by Dharanikanna** [comment]
Hello All,
I'm Dharani Kanna. I have interested to Contribute and resolve this issue. I'm just beginner for open source contribution. Please some one guide me to catch the path of a open source contributor.

**Comment by jasongrout** [comment]
@Dharanikanna - our new contributor guide helps you get a development environment set up: https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html

**Comment by Dharanikanna** [comment]
Thank you @jasongrout sir.

**Comment by lucabarcelos** [comment]
I would like to work on this issue.

**Comment by jasongrout** [comment]
Excellent! Please post a comment here with the PR link when you submit the PR.

**Comment by ohrely** [comment]
I will work on this issue.

**Comment by gioarma** [comment]
With version 3.2.3 the issue is solved only for the first time a cell is executed in the console.

Once the first cell is executed, if I try to type something new in the console I see the exact same problem. Do you see this as well?

**Comment by fcollonval** [comment]
I can confirm that it works only on the first executed block. Then the setting is not effective any longer.

--> re-opening

**Comment by pree-T** [comment]
@fcollonval  May I work on this? Can anyone help me a bit?

**Comment by fcollonval** [comment]
> FYI you don't need to ask to start working on an issue. The best is to open early a draft PR with what you are doing and ask for review and/or help.

For this one, the path I would take is to save the editor options as a new attribute in the `CodeConsole` class. 

https://github.com/jupyterlab/jupyterlab/blob/05096d47a732e89fd7513eae969556a2e2b05021/packages/console/src/widget.ts#L87

Those options will be set from the settings in 

https://github.com/jupyterlab/jupyterlab/blob/05096d47a732e89fd7513eae969556a2e2b05021/packages/console-extension/src/index.ts#L380

And they will need to be applied to the editor each time a prompt cell is created at

https://github.com/jupyterlab/jupyterlab/blob/05096d47a732e89fd7513eae969556a2e2b05021/packages/console/src/widget.ts#L590-L591

**Comment by pree-T** [comment]
This project is showing several errors when opened through vscode. What are the system prerequisites of this ?

**Comment by GF-Huang** [comment]
It only works for first `shift + enter` each console. 

## **This problem has been going on for over a year now, hoping someone will fix it soon, it's a real pain.**

https://user-images.githubusercontent.com/4510984/156917880-41481adb-eb6b-4d80-ba4d-d777f0fbb122.mp4

```
>> pip list | findstr.exe jupyter
jupyter-client                6.1.12
jupyter-core                  4.7.1
jupyter-server                1.9.0
jupyterlab                    3.3.0
jupyterlab-code-formatter     1.4.10
jupyterlab-notifications      0.2.2
jupyterlab-pygments           0.1.2
jupyterlab-server             2.10.3
jupyterlab-widgets            1.0.0
```
Win10 21H2
