### ISSUE TITLE
importing variables from another notebook into Jupyter Lab

### ISSUE THREAD

**Issue by akitxu** [jupyterlab/jupyterlab#10873]
I want to close and delete this query. I have found answers to it on StacjOverflow, so it cannot be considered as an Issue. excuse me

**Comment by krassowski** [comment]
> I want to close and delete this query. I have found answers to it on StacjOverflow, so it cannot be considered as an Issue. excuse me

No worries, we can close this :)

However, it would probably help if you could link to the StackOverflow post that you found helpful as other users will likely find this issue via their search engine and may benefit from a suggestion ;)

A few useful links from me:
- https://stackoverflow.com/questions/31621414/share-data-between-ipython-notebooks/60863662
- https://stackoverflow.com/questions/19564625/how-can-i-import-from-another-ipython-notebook
- https://stackoverflow.com/questions/54317381/selectively-import-from-another-jupyter-notebook
