### ISSUE TITLE
workspace is restored instead of loading requested document via `/tree/notebook.ipynb`

### ISSUE THREAD

**Issue by nibheis** [jupyterlab/jupyterlab#10876]
## Description

Using `/user-redirect/...` does not get the user to the destination **if** the workspace is not **empty** (i.e. a notebook was already opened previously). Instead of opening the requested URL, the user is sent to his restored workspace.

If the workspace has been cleaned (closing all tabs and terminals, leaving only the launcher) before using the `/user-redirect/...` URL, then the redirection works as expected.

## Reproduce

There are many scenarios that are impacted by this bug. Here are several ways to reproduce this issue:

1. Start your jupyterlab session. Open notebook `A.ipynb`. 
URL is `https://[hubname]/user/[user-id]/lab/tree/A.ipynb`
Change URL to `https://[hubname]/user-redirect/lab/tree/B.ipynb`, press [ENTER]
=> `A.ipynb` is still displayed.
If workspace is emply, then redirection works as expected.

2. Using a jupyterhub: log in and Open notebook `A.ipynb` and then logout.
Add `?next=/user-redirect/lab/tree/B.ipynb` to the hub URL and log in again
=> `A.ipynb` is still displayed.
If workspace is emply, then redirection works as expected.

3. Using nbgitpuller server extension - basically the same as above, but there is a little difference: when nbgitpuller has to clone the repository (first time the URL is used), then the redirection works. However, when the repository is already available in the user's workspace, then the redirection fails and the user is sent to his workspace.
If workspace is emply, then redirection works as expected.

Note: you need a patched version of nbgitpuller for jupyterlab 3.1.x, see https://github.com/jupyterhub/nbgitpuller/pull/193

## Expected behavior

I expect the user to be **always** sent to the specified `/user-redirect/...` URL.

I expect the events to happen **always** in the following order:
1. The workspace (tabs, etc.) is restored first
2. The `/user-redirect/...` redirection happens

## Context

- Operating System and version:  Gentoo Linux (same behavior on other OSes)
- Browser and version:  Google Chrome Version 92.0.4515.159 (Official Build) (64-bit) (Same behavior with Firefox)
- JupyterLab version:  3.1.x (tested with 3.1.6 and 3.1.7)

<details><summary>Troubleshoot Output</summary>
<pre>
n/a
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
When running JupyterLab with `--debug` parameter, no warning or errors are displayed.
We can see from the logs that the `/user-redirect/...` URL is processed first,
then we can see a GET on the workspace URL.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
No javascript errors or warnings are visible.
</pre>
</details>

**Comment by nibheis** [comment]
Hi all,

This bug is quite annoying. I've been tracing it for hours, but I could not find anything (nothing appears in the debug logs).
I also took the time to update all the components (jupyther hub 1.4.2, lab 3.1.7 and more) to their latest versions... but nothing solves this issue.

It is very easy to reproduce:

https://user-images.githubusercontent.com/52066010/130621661-57d495b0-2d9f-4783-bd98-740dd87da211.mp4

In this short demo, you can see that the `/user-redirect/...` URLs only work when the workspace was left empty before launching the URLs:
- Notebook A opens
- Notebook B fails because A is opened
- Notebook B opens when I close A

I would be happy to learn that this only happens on my jupyterlab deployments (all my jupyterlab3 deployments)  - I would continue investigating and testing components. Could anyone please confirm that `/user-redirect/...` fully works with their jupyterlab 3.1.x? Thanks!!

**Comment by krassowski** [comment]
I am not familiar with this part of the codebase, but I would suggest asking on the [JupyterHub gitter](https://gitter.im/jupyterhub/jupyterhub) or on the [Discourse](http://discourse.jupyter.org/).

**Comment by nibheis** [comment]
Thanks @krassowski ; I went and ask on the [JupyterHub gitter](https://gitter.im/jupyterhub/jupyterhub).
Can you try to reproduce this issue on your side by any chance?

**Comment by minrk** [comment]
I don't think JupyterHub is involved in this. It should be purely a JupyterLab issue. Visiting `/user-redirect/` is just a redirect to lab with the same path. So the result should be the same if you exclude `/user-redirect/` and visit the lab urls directly:

```
/user/povalles/lab/tree/A.ipynb
/user/povalles/lab/tree/B.ipynb
```

Can you reproduce the issue without involving `/user-redirect/`?

**Comment by nibheis** [comment]
Hi @minrk,
I confirm the same issue without involving `/user-redirect/`: The notebook referenced in the URL is opened only if the workspace was empty.

I can reproduce this on 2 platforms that I migrated to jupyterlab 3.1.x ; in fact, in both cases I completely re-installed the servers from scratch, so there should not be left-overs from jupyterlab 1.x.
All that is left over are the user files ; are there some configuration files in `~/.jupyter/lab` from jupyterlab 1 that could be problematic? I'll clean this folder and test again.

**Comment by nibheis** [comment]
I started with a clean `~/.jupyter` dir (I deleted it), but nothing changed.

**Comment by minrk** [comment]
Yup, this is easily reproducible with a regular local lab (3.1.7) 

1. `jupyter lab`
1. create notebooks `A`, `B`
2. visit `/lab/tree/A.ipynb`
3. edit URL to `/lab/tree/B.ipynb` and press enter
4. page loads and redirects to`/lab/tree/A.ipynb` instead of opening B

presumably something like restoring the workspace taking priority over the requested URL

https://user-images.githubusercontent.com/151929/130764297-937fb4bf-cd70-4406-a4f2-6425ad46061f.mov

**Comment by nibheis** [comment]
I'm willing to investigate and dig into the code ; can anyone offer pointers to where I should start ?

This bug is annoying, especially for our LTI users, and more generally to anyone using a nbgitpuller link... which represents 90% of our users. Getting this fixed before the start of the semester is my goal.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/tree-navigation-not-working/12287/2
