### ISSUE TITLE
Support for jupyter config files?

### ISSUE THREAD

**Issue by marks** [jupyterlab/jupyterlab#1087]
Does Jupyter Lab support reading in Jupyter's `NotebookApp.config_file`s?

**Comment by blink1073** [comment]
Hi @marks, we are not using any of the existing configuration system, see #515 for discussion.

**Comment by ellisonbg** [comment]
Although, jupyterlab is just using the classic notebook server, so arn't those files being read in anyways. IOW, *server* config files should be working fine. Is this what you are asking?

**Comment by jasongrout** [comment]
Closing since there was no followup questions. @marks, feel free to post a comment here if you'd like to continue the discussion.
