### ISSUE TITLE
Version conficts in jupyterlab and jupyter-js-services

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1088]
@jasongrout and I were updating the jupyterlab_vega extension today and we found that the version of jupyter-js-service used by the latest release of jupyter (0.5.0) is behind the latest stable of jupyter-js-services itself. To build my extension I had to depend on jupyter-js-services, but that ended up conflicting with the version in jupyterlab. We had to monkey patch around all of this.

Can we release a minor version of jupyterlab that depends on latest jupyter-js-services?

**Comment by blink1073** [comment]
We are still in the middle of migrating, I'd prefer to wait until we finish switching to `@jupyterlab/services`.
