### ISSUE TITLE
JupyterLab | stdin user input via. shell. Entry into output cell field

### ISSUE THREAD

**Issue by DanielBell-Io** [jupyterlab/jupyterlab#10881]
`Google Colab` allows you to enter values into an output cell, during runtime.

**Can I enter in user input, when calling a program via. the shell?**

**Can JupyterLab handle stdin from the shell?**

Example:

Cell: `!tensorboard dev upload --logdir tb_logs --name "OntologyTagger" --description "OntologyTagger" --one_shot`

Output: `Continue? (yes/NO)`, I click a text field and enter text.
[![enter image description here][1]][1]

---

**How can I do this in `JupyterLab`?**

JupyterLab:
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/j8X3G.png
  [2]: https://i.stack.imgur.com/qeWqX.png

**Comment by jasongrout** [comment]
Colab does some interesting tricks to enable the input. IIRC, Colab waits a bit (like 500ms) and then assumes the shell is waiting for input and puts in an input. I thought we had an issue open discussing this, but I can't find it now.

CC @blois

**Comment by jasongrout** [comment]
Oh yes, here is the issue where we discussed this: https://github.com/jupyterlab/jupyterlab/issues/8522

The conclusion there was that the issue should be brought up in the ipykernel repo. In other words, it's the kernel's responsibility to monitor the shell output, and send a stdin request to the frontend if needed.

**Comment by jasongrout** [comment]
More discussion, including how Colab seems to function, is at the ipykernel issue: https://github.com/ipython/ipykernel/issues/513 (it seems like the 500ms idea was from our discussion on that issue, and not necessarily what Colab does).

**Comment by DanielBell-Io** [comment]
I've had a read of #8522. Might there be a way to mock stdin via. a code cell, in Python?
