### ISSUE TITLE
Hide the code in the exported html

### ISSUE THREAD

**Issue by akitxu** [jupyterlab/jupyterlab#10896]
Dear all, is there any possibility of exporting a notebook to html, hiding its code? Another option would be to be able to hide the code in the exported html, is it possible? Kind regards

**Comment by goanpeca** [comment]
Hi @akitxu, thanks for the suggestion, could you provide an example to explain in more detail the feature you are requesting?

Cheers!

**Comment by krassowski** [comment]
@akitxu could the answers in this link [Hide Code when exporting Jupyter notebook to HTML](https://stackoverflow.com/questions/49907455/hide-code-when-exporting-jupyter-notebook-to-html) be of any use? It does require going to command line and IMO JupyterLab should enable users to customize nbconvert from GUI. This was previously suggested in https://github.com/jupyterlab/jupyterlab/issues/8129#issuecomment-609089019 (covering the option to only export outputs) and in https://github.com/jupyterlab/jupyterlab/issues/5199. This would be a huge improvement, but I do not know if there is a single issue to track it, and how to integrate with nbconvert best to auto-create options form.

**Comment by krassowski** [comment]
There seems to be extension for that as suggested in https://github.com/jupyterlab/jupyterlab/issues/8629#issuecomment-651885819: https://github.com/timkpaine/jupyterlab_nbconvert_nocode but I really believe this should be baked in the core and have a dialog or more extensive customization.

**Comment by timkpaine** [comment]
@krassowski its exposed but only from the CLI, Jlab powers the dialog off the present nbconvert entry points so nbconvert or jupyter would need to put this on disk. Me and @vidartf are the only contributors so we can relicense to bsd and ingest into either project if we want.

**Comment by krassowski** [comment]
Well, we can change how JupyterLab learns about nbconvert capabilities to make it more flexible :)

I do not know much about nbconvert (just basics), but I would love to have all [configuration options](https://nbconvert.readthedocs.io/en/latest/config_options.html) customizable from a pop-up (and maybe even include a template editor!), building upon the mock-up from https://github.com/jupyterlab/jupyterlab/issues/8129#issuecomment-609089019:
 >  ![image](https://user-images.githubusercontent.com/5832902/130490332-c69ecf40-06a1-4368-90be-0b06ca1d3ce1.png)

I guess that we would need to export the traitlets to a JSON schema and auto-generate dialog from that, possibly re-using the configuration UI that @marthacryan is working on. Do you think that this is the right way forward? Is there a solution to get traitlets configuration into a JSON schema?

**Comment by akitxu** [comment]
In jupyter notebook, with cells in mode raw, with this code that I found in Intermnet, you export an notebook as html in which ther is a boton to hire the sscript.
Cell 1
 `<script>
  jQuery(document).ready(function($) {  
  
  $(window).on('load', function(){
    $('#preloader').fadeOut('slow',function(){$(this).remove();});
  });
  
  });
</script>

<style type="text/css">
  div#preloader { position: fixed; 
      left: 0; 
      top: 0; 
      z-index: 999; 
      width: 100%; 
      height: 100%; 
      overflow: visible; 
      background: #fff url('http://preloaders.net/preloaders/720/Moving%20line.gif') no-repeat center center; 
  }

</style>

<div id="preloader">

</div>`

Cell 2

<script>
  function code_toggle() {
    if (code_shown){
      $('div.input').hide('500');
      $('#toggleButton').val('Show Code')
    } else {
      $('div.input').show('500');
      $('#toggleButton').val('Hide Code')
    }
    code_shown = !code_shown
  } 
  
  $( document ).ready(function(){
    code_shown=false; 
    $('div.input').hide()
  });
</script>
<form action="javascript:code_toggle()"><input type="submit" id="toggleButton" value="Show Code"></form>

The same code in jupyter lab, get an html documento empy.

**Comment by akitxu** [comment]
krassowski . 
In my opinion, the usefulness is that if we make a script whose result interests a group of people who do not know programming, they can get it as clean as possible.
For example, let's imagine a script with an investment strategy that a potential user can customize with a specific investment / investments, and whose execution reports certain statistical data.
Another possible use would be to design a script whose output is practically a report.

**Comment by akitxu** [comment]
@Krassowski 
I found a solution in your link. `jupyter nbconvert @bandas_bollinger.ipynb --no-input --to html
`
Regarding the  `jupyterlab_nbconvert_nocode` extension, it seems good to me. The problem I see is that it cannot be installed with either pip or conda. I am trying to do it from the linux console and so far I have not succeeded. `./configure` gives me error. I'll keep trying, but I insist that I think it would be practical to have an option integrated in the download menu of Jupyter Lab. Thank you for your attention.

**Comment by akitxu** [comment]
This link is helpful  [How to make polished Jupyter presentations with optional code visibility] `https://chris-said.io/2016/02/13/how-to-make-polished-jupyter-presentations-with-optional-code-visibility/`

**Comment by krassowski** [comment]
Marking this as answered (see above for workarounds) and closing to focus the conversation on the enhancement which will enable this workflow in #8129. Again, thank you for bringing up attention to this one!

**Comment by aperkins4008** [comment]
I think this would also be helpful. From and end user experience, no-one wants to see the programming. I've worked in fortune 500 companies as well as start-ups. Leadership and end users don't want to see programming they want to see the end result. The code itself merely gives alot of noise.
