### ISSUE TITLE
Treating of pure python files in jupyter notebook using GUI

### ISSUE THREAD

**Issue by RAJSINGH-Bitian** [jupyterlab/jupyterlab#10935]
###

**Comment by RAJSINGH-Bitian** [comment]
i'm not talking about only allow to edit i'm talking about.provide full interface which is provided to .ipynb .and we didn't need the cell information inside of .py beacause In  maximum of the ide codes are works as a single unit.

**Comment by RAJSINGH-Bitian** [comment]
@agoose77  i need your help , if you are ready to guide me  i will be very greatful to you. let me know how can we communicate.

**Comment by agoose77** [comment]
@RAJSINGH-Bitian please read the links I sent you earlier - they provide a way to treat '.py' files (and others) as notebooks (and provide the user interface)

**Comment by RAJSINGH-Bitian** [comment]
i need a contribuation to any project whose hit star is greater than 100 for interview of microsoft .will you please help me?
@agoose77

**Comment by agoose77** [comment]
If you want to contribute to the Jupyter ecosystem, then I would recommend looking at some of the `good-first-issue` issues on different repositories, e.g. 
- https://github.com/jupyterlab/jupyterlab/labels/good%20first%20issue
- https://github.com/jupyter/nbconvert/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by jondo** [comment]
Maybe this issue can be closed.
However, one might wish for newbies to get [this comment](https://github.com/jupyterlab/jupyterlab/issues/10935#issuecomment-907167425)'s information directly when opening a `.py` file within JupyterLab.
