### ISSUE TITLE
Jupyter notebook stuck loading, not showing content, in VSCode

### ISSUE THREAD

**Issue by Dervis-vL** [jupyterlab/jupyterlab#10934]
When I open an .ipynb file in VSCode it pops up on my screen but no content appears. The loading bar keeps going and nothing happens. So I am not able to use Jupyter or access and modify existing or new files.

Screenshot of the loading bar:
![image](https://user-images.githubusercontent.com/65704977/131088400-51c0a456-0e6e-455b-af93-47f88b20c262.png)

I can't seem to find similar issues that solve this problem. I'm not certain but maybe the problem started when I started using Git in my terminal in VSCode. I tried a reinstall of Jupyter and VSCode.

**Comment by agoose77** [comment]
This is not a JupyterLab issue, so this might not be the best place to ask for help. I would suggest filing an issue over at https://github.com/microsoft/vscode

It "might" be something to do with the Jupyter Server, but until we know more we can't provide much help. Hopefully, someone over at vscode will have some suggestions.

**Comment by Dervis-vL** [comment]
> This is not a JupyterLab issue, so this might not be the best place to ask for help. I would suggest filing an issue over at https://github.com/microsoft/vscode.
> Because of this, I'm adding the `status:Invalid` tag, but please open a new issue if you determine that something is broken on the Jupyter side of things!
> 
> It "might" be something to do with the Jupyter Server, but until we know more we can't provide much help. Hopefully, someone over at vscode will have some suggestions.

I see the issue is already closed unfortunately. 

VSCode refers all extension related issues directly to the extensions repo. I'm looking for possible settings in Jupyter that could cause Jupyter to not load any cells. The notebook stays empty and no input is shown at all.

**Comment by jasongrout** [comment]
> VSCode refers all extension related issues directly to the extensions repo. I'm looking for possible settings in Jupyter that could cause Jupyter to not load any cells. The notebook stays empty and no input is shown at all.

We don't maintain the VSCode extension for ipynb files. I suggest filing an issue with the maintainers (who work at Microsoft, IIRC).

**Comment by jasongrout** [comment]
I think it is this repo: https://github.com/microsoft/vscode-jupyter
