### ISSUE TITLE
jupyterlab 3 can't recongize nodejs installed by nvm

### ISSUE THREAD

**Issue by HenryJi529** [jupyterlab/jupyterlab#10942]
## Description

jupyterlab 3 can't recongize nodejs installed with nvm.

<img width="985" alt="Screen Shot 2021-08-27 at 10 59 45 PM" src="https://user-images.githubusercontent.com/41288155/131147874-ad21afca-8745-454d-877b-d5828ced79f2.png">

## Reproduce
 Node16.x has been Installed with nvm.
<img width="439" alt="Screen Shot 2021-08-27 at 11 01 20 PM" src="https://user-images.githubusercontent.com/41288155/131148111-85a73321-15f3-44c4-9f20-6fb820f80b3d.png">

- Operating System and version: Linux Ubuntu 20.04 
- JupyterLab version: 3.1.9

<details><summary>Troubleshoot Output</summary>
<pre>
<img width="551" alt="Screen Shot 2021-08-27 at 11 09 17 PM" src="https://user-images.githubusercontent.com/41288155/131149224-9bcd5df5-0fdf-48ce-96b7-5c65240c3a2d.png">
</pre>
</details>

**Comment by HenryJi529** [comment]
The dialog is still there.

**Comment by krassowski** [comment]
Please try: `jupyter server extension enable --py jupyterlab_git` and run `jupyter server extension list` again to check if this shows up this time. There are further troubleshooting instructions in https://github.com/jupyterlab/jupyterlab-git#troubleshoot if this does not help. In any case please let me know if it helped!

**Comment by HenryJi529** [comment]
```
jeep_jipu@morningstar /home/jeep_jipu                                           
⚡ jupyter server extension enable --py jupyterlab_git

Enabling: jupyterlab_git
- Writing config: /usr/etc/jupyter
    - Validating jupyterlab_git...
      jupyterlab_git 0.32.2 OK
      X Validation failed: [Errno 13] Permission denied: '/usr/etc'
```
At first, the config dir(`/usr/etc/jupyter`) doesn't exist. 
After making the config dir in `/usr`,  the jupyterlab-git works now.

**Comment by krassowski** [comment]
That's great! I would recommend using a virtual environment (pyenv-virtualenv, conda, or any number of others) for future Python installations it removes a lot of headaches like that.

> However, does jupyterlab-git have any relationship with Nodejs?

No. It does not need Node.js at all, if you installed Node.js only for that purpose you can uninstall it... unless you would like to contribute, then for developing jupyterlab-git Node.js is indeed useful (but not needed for the user at all).
