### ISSUE TITLE
Toggling Single Document mode (Simple Interface) On & Off messes up multi-pane layout

### ISSUE THREAD

**Issue by slonik-az** [jupyterlab/jupyterlab#10947]
## Description
If I start with Jupyterlab layout with two or more panes (arranged horizontally or vertically) and then switch _Simple Interface_ On and then Off the resulting layout has only one pane remaining (not counting the sidebar). The other panes appear as tabs. Here are the screenshots:

### Before 
I started with having 3 panes:
<img width="1536" alt="jupyterlab-before" src="https://user-images.githubusercontent.com/11963186/131231450-7f38485c-d0d9-47fd-8819-15c255b6724f.png">

### After switching Simple Interface On and then Off
only one pane remains:
<img width="1536" alt="jupyterlab-after" src="https://user-images.githubusercontent.com/11963186/131231472-38435276-5601-44ab-b34b-090fb166370c.png">

## Reproduce

1. Start Jupyterlab and open a notebook. 
2. Create a multi-pane layout with 2 or more panes (not counting the left sidebar)
3. Toggle Simple Interface On (Button located in the low left corner of the screen)
4. Toggle Simple Interface Off
5. Observe the collapse of all panes into one.

## Expected behavior
Toggling Simple Interface On and then Off should result in no-op. The layout of windows and panes should be restored to its initial state.

## Context

- Operating System and version: MacOS 11.5.2 (Big Sure), Intel CPU
- Browser and version: Chrome 92
- JupyterLab version:  3.1.9

**Comment by fperez** [comment]
I was just about to file this same issue! As I try to use it more often, I think it's really important for the simple mode toggle to remember the state it came from and restore it seamlessly upon deactivation (as long as the other objects still exist, obviously - any of them could have been closed in the interim). Without this feature, it's harder to use simple mode as a mental "zoom in to focus, zoom out to take care of a few other things for a minute that need the rest of the tools, zoom back in to keep working." In my mind, that is the beauty of simple mode, and the lack of workspace restoration breaks this flow...

I realize that handling objects whose lifecycle is outside the control of simple mode is tricky, but I suspect some compromise solutions can be devised.

**Comment by jasongrout** [comment]
I'll note this is a regression in JLab 3.1. It works fine for me in 3.0.18 (i.e., the layout is persisted across toggling simple mode).

**Comment by fperez** [comment]
Ah, thanks for that note, @jasongrout! I _thought_ the same, b/c it felt off, but I wasn't sure and didn't have the patience to test... Good to know, in that case it's "just a bug to fix" :)

**Comment by jasongrout** [comment]
Fix over in #11203
