### ISSUE TITLE
Code Editor out of Sync

### ISSUE THREAD

**Issue by BruniGui** [jupyterlab/jupyterlab#10941]
{"model":"# Local:\r#df = pd.read_csv('./dados/brasileirao2018_p.csv', index_col = 0)\r","view":"# Local:\n#df = pd.read_csv('./dados/brasileirao2018_p.csv', index_col = 0)\n","selections":[{"uuid":"98fc8ccd-0035-4151-9847-91f3fc05415a","start":{"line":0,"column":0},"end":{"line":0,"column":0},"style":{"className":"","displayName":"","color":"black"}}],"cursor":{"line":0,"column":0},"lineSep":null,"mode":"text/x-ipython","change":{"from":{"line":0,"ch":0,"sticky":null},"to":{"line":1,"ch":0,"sticky":null},"text":["# Local:","#df = pd.read_csv('./dados/brasileirao2018_p.csv', index_col = 0)",""],"origin":"setValue","removed":["# Local:",""]}}
_checkSync @ jlab_core.64abc115a1efeec58694.js?v=64abc115a1efeec58694:2

**Comment by jasongrout** [comment]
@BruniGui - very interesting, we haven't seen this before. You have just carriage returns as newlines, i.e., instead of a typical `\n` or `\r\n` separating your lines, you have `\r`. What tool did you use to generate this notebook file?

**Comment by jasongrout** [comment]
This is related to #9465, but different in that the line endings here are not `\r\n`, but rather just `\r`.
