### ISSUE TITLE
`breakpoint()` not working [ipykernel bug]

### ISSUE THREAD

**Issue by ianozsvald** [jupyterlab/jupyterlab#10996]
Using a fresh install of Jupyter Lab my usual `breakpoint()` to invoke the debugger in a Notebook is skipped (see screenshot). Using `import pdb; pdb.set_trace()` instead invokes `pdb` as expected. 

I was expecting (am I wrong?) that a call to `breakpoint()` in a cell would invoke `pdb`. 

This is using a fresh conda install of Jupyter Lab this morning, no reconfiguration of the environment has occurred.

## Description

![image](https://user-images.githubusercontent.com/273210/131856800-69247991-9393-49ca-9d20-e3909164fa34.png)

## Reproduce

I've created a fresh minimal environment:

```
$ conda create -n tmp_env python=3.8 jupyterlab

$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.4.3
qtconsole        : not installed
ipython          : 7.27.0
ipykernel        : 6.3.1
jupyter client   : 7.0.2
jupyter lab      : 3.1.10
nbconvert        : 6.1.0
ipywidgets       : not installed
nbformat         : 5.1.3
traitlets        : 5.1.0
```

and then I run `jupyter lab` and try to call `breakpoint()` as noted in the screenshot above.

I used `jupyter lab --debug` and scanned the output, nothing looked amiss (but there's a lot and I'm not sure what to look for) - I can attach a copy if needed?

I noticed this originally in a second more complex environment (also built today, making me think this is a library update issue somewhere) and I made the above simple environment to try to narrow things down, but the issue remains.

## Environment

Linux Cinnamon using Anaconda with Firefox, the OS is all up to date.

```
$ inxi -b
System:    Host: ian-XPS-15-9550 Kernel: 5.4.0-77-generic x86_64 bits: 64 Desktop: Cinnamon 4.8.6 
           Distro: Linux Mint 20.1 Ulyssa 
Machine:   Type: Laptop System: Dell product: XPS 15 9550 v: N/A serial: <superuser/root required> 
           Mobo: Dell model: 0N7TVV v: A00 serial: <superuser/root required> UEFI [Legacy]: Dell v: 1.9.0 date: 10/11/2018
```

**Comment by ianozsvald** [comment]
There may be more clues here. `breakpoint()` appears to have been reconfigured to `debugpy` (I don't know what this is). The environment variable that can control `breakpoint()` has not been set (I didn't expect it to be set, I haven't messed with it).

Calling `sys.breakpointhook()` does nothing, calling `sys.__breakpointhook__()` drops into `pdb`.

![image](https://user-images.githubusercontent.com/273210/131893060-efbbd754-da36-4132-b0c8-e2c742a1b37f.png)

`debugpy` appears to be https://github.com/microsoft/debugpy which I haven't explicitly installed. I do have Microsoft's Visual Code but I don't actively use it, I certainly haven't tried to integrate it into this temporary environment. Is `debugpy` integrated into Jupyter as a new thing?

**Comment by krassowski** [comment]
Hi @ianozsvald, nice to see you here, thank you for your work on PyDataLondon!

Yes, that's sounds right: beginning with version [6.0](https://github.com/ipython/ipykernel/releases/tag/6.0.0) ipykernel supports the debugger adapter protocol and uses debugpy underneath. Starting with JupyterLab 3.0 we have a [GUI debugger](https://jupyterlab.readthedocs.io/en/stable/user/debugger.html), which is still actively developed (some new features shipped in 3.1 and even more coming soon). What version of JupyterLab are you using?

I can confirm that the `breakpoint()` is ignored when the debugger UI is turned off (which should not be the case), and that it works correctly when the debugger GUI switch is flicked on. I think that this issue belongs in https://github.com/ipython/ipykernel - I don't think this behaviour comes from JupyterLab itself.

In the meantime you could try out the JupyterLab debugger GUI (you may need to upgrade JupyterLab), or if it does not suit your needs you may want to downgrade to `ipykernel` <5.

**Comment by ianozsvald** [comment]
@krassowski many thanks for your reply and thanks for the hat-tip :-) I haven't tried the graphical debugger yet, that's on my list now. I'm on `jupyter lab      : 3.1.10` (all version details noted above). I haven't tried the new debugger interface (at all) in Labs, I need to have a play. 
I did try `breakpoint()` having flicked the debugger toggle and it didn't break on my line, I also tried `import pdb; pdb.set_trace()` and I got a warning about conflicts between pdb and the debugging system. I need to play some more with this!

**Comment by marctorsoc** [comment]
I think this is the related issue https://github.com/ipython/ipykernel/issues/770

**Comment by fcollonval** [comment]
Linking a workaround from IPython: https://github.com/ipython/ipython/issues/13262

```
import sys

def override_sys_breakpoint(frame=None):
    from IPython.core.debugger import set_trace
    set_trace(frame=frame)

sys.breakpointhook = override_sys_breakpoint
```

**Comment by cocoaaa** [comment]
I've experienced the same issue in jupyterlab 3.0.0, ipykernel 6.5.0.
An alternate workaround is to override the `breakpoint` function with IPython's `set_trace` function as follows:
```python
from IPython.core.debugger import set_trace as breakpoint
```

**Comment by DiSchi123** [comment]
I am experiencing the same issue very likely. This seems important, is there an ETA when this will be fixed?

**Comment by fcollonval** [comment]
As mentioned in https://github.com/jupyterlab/jupyterlab/issues/10996#issuecomment-911938250, this is a bug in the execution kernel (aka ipykernel). I opened https://github.com/ipython/ipykernel/issues/897.
