### ISSUE TITLE
With RTC enabled, large notebooks to fail on save and whole UI becomes extremely sluggish.

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab#10997]
## Description

When Lab is started with `--collaborative`, certain large notebooks fail to save or take inordinately long to do so.

## Reproduce

[This Gist](https://gist.github.com/06cc8cab195a7ebaa97bf42ff77dd141.git) contains a notebook that illustrates the problem. To reproduce, clone the gist and run side-by-side JupyterLab with and without `--collaborative`. 

I tested on a Mac Mini with Big Sur, Python 3.9, 64GB of RAM and JupyterLab 3.1.10.

The version with `--collaborative` on will either not save at all, or take easily 10 minutes to do a save. In addition, the whole UI gets very sluggish, and the browser occasionally pops warnings about the page consuming too many resources (seen on Firefox, Chrome and Safari).

## Additional context

We spent some time tracking down this problem [over at the Jupyter meets the Earth repo](https://github.com/pangeo-data/jupyter-earth/issues/78). Flagging that thread for reference, but all relevant info is here.

**Comment by echarles** [comment]
> The version with --collaborative on will either not save at all, or take easily 10 minutes to do a save. In addition, the whole UI gets very sluggish

Does this happen only when multiple users are using the notebook (which has implications because the shared models are solicited more) or also if a single user is using the notebook without any other collaborators ?

... or maybe the user is doing collaborative sessions before (or in other notebooks) and at some points hits a condition which makes jupyterlab sluggish?

More context on how the issues come live will help to narrow down the source.

**Comment by fperez** [comment]
Single user - as I mention above, you can replicate it at home right now :) Just clone that gist (or download the notebook in it) and open it with Lab, with and without `--collaborative`. At least for me, the difference is immediately apparent: with collaborative mode on, once I change anything in the notebook, it's almost impossible to save it (and the UI gets really sluggish).

The test case in the gist is fully self-contained so you can play with it :)

**Comment by fperez** [comment]
I just tested it again on a different machine (Macbook Pro 13, 16GB RAM), same story. With `--collaborative` on, it won't save.

**Comment by fperez** [comment]
Gotta sleep now but I'll check in tomorrow, thanks for looking into it!

**Comment by echarles** [comment]
> Single user - as I mention above, you can replicate it at home right now :) Just clone that gist (or download the notebook in it) and open it with Lab, with and without --collaborative. At least for me, the difference is immediately apparent: with collaborative mode on, once I change anything in the notebook, it's almost impossible to save it (and the UI gets really sluggish).

Oops, the reproducer is there with documentation. . sorry I have not read carefully enough.

I have tried the given notebook on a powerfull MacBook Pro, and I confirm that I face exactly the same reported issue. Another simple notebook saves fine. Looking at the network, the connection to ws://localhost:8888/api/yjs/notebook:Untitled.ipynb consantanly retries its Y.js Websocket connection after exchanging a few binary messages. The server does not say anything (starting with --debug just confirms the 101 `[D 2021-09-03 11:01:23.917 ServerApp] 101 GET /api/yjs/notebook:saving-bug.ipynb (::1) 3.65ms`). We prolly need to add more debugging client and server side to print the decoded Y.js messages and understand what is going on.

<img width="694" alt="Screenshot 2021-09-03 at 10 55 55" src="https://user-images.githubusercontent.com/226720/131979914-d7e1d843-4c05-4528-a63a-a4e0278e56f3.png">

> Gotta sleep now but I'll check in tomorrow, thanks for looking into it!

Hope we get good news when you get awake.

**Comment by echarles** [comment]
The notebook has only 45 cells but weights 18 Mbytes.

Firefox has relative pain to display the tree, and VSCode (with a json tree viewer) has pain to open it.

<img width="341" alt="Screenshot 2021-09-03 at 15 09 05" src="https://user-images.githubusercontent.com/226720/132010300-bda011bd-79d0-4f43-b537-32100b92d820.png">

<img width="453" alt="Screenshot 2021-09-03 at 15 09 16" src="https://user-images.githubusercontent.com/226720/132010314-897f8381-9dce-489f-9c19-efe592a7da91.png">

**Comment by dmonad** [comment]
The problem is that tornado's Websocket connections are configured to close when they receive messages larger than 10mb. The client indefinitely reconnects and tries to send the same large document which will break the connection again. Since computing the Yjs update for such a large document is mildly expensive (~300ms), you will get noticeable performance problems. 

I'll fix this problem by increasing the `websocket_max_message_size` of tornado to the same size of the max body size.

**Comment by dmonad** [comment]
Thanks for this super helpful bug report @fperez! 

I provided a fix in #11003

**Comment by fperez** [comment]
Awesome, thanks so much @echarles and @dmonad for the fast response! The fix is basically a one-liner, that's great to see!

Credit for tracking this down goes to @consideRatio and @tsnow03, who found the original problem and patiently dealt with it, for weeks privately in our hub and finally on [this issue](https://github.com/pangeo-data/jupyter-earth/issues/78) once we had enough specifics to report something.

Excellent team work all around!  We'll report back once this is merged/released (we don't run pre-release versions on that hub) if we see any other issues.

I have one last question: if for certain documents (this notebook was a real-life, work-related notebook, not something contrived to highlight pathological edge cases) the RTC setup imposes a noticeable penalty, would it be possible to find ways to toggle it with more granularity? Right now it's a Lab startup flag, which makes it particularly tricky to control in hosted hubs, where the user's session is normally pre-configured. And that configuration may be long-lived - ideally one should be able to activate the feature only when needed.

I'm not sure how much this has been discussed, or if you think it's worthwhile I can either open an issue for it or make a persistent post on Discourse. Just LMK what works best for you all.

Thanks again, great work!

**Comment by echarles** [comment]
> would it be possible to find ways to toggle it with more granularity

I can imagine a visual toggle per notebook, with a rtc metadata true/false stored in the ipynb file). That is not implemented today, but should be fairly easy to do and really useful to avoid penalties.

**Comment by echarles** [comment]
>  but should be fairly easy to do and really useful to avoid penalties

I have opened https://github.com/jupyterlab/jupyterlab/issues/11004

Thinking a bit more, we may face various use case less easy than expected. Potential difficulties are:

- What if 2 users have already loaded the same notebook and start to make it collaborative at different time.

Pretty sure there are other user-facing issues to identify and that will appear...
