### ISSUE TITLE
Handle repeated keys in the Terminal

### ISSUE THREAD

**Issue by 0x0L** [jupyterlab/jupyterlab#1100]
When using vim in a terminal pane, I'm unable to scroll with `hjkl` keys though I can using keyboard arrows.

It works fine in the traditional terminal.

**Comment by blink1073** [comment]
I @0x0L, I tried running `vim` using JupyterLab on OSX in Firefox and Chrome and I was able to navigate using the standard keys.  Can you describe your environment?

**Comment by blink1073** [comment]
Ah yes, sorry, I see what you mean now.  I can confirm this behavior works in a standalone terminal window but not in JupyterLab.

**Comment by jasongrout** [comment]
Perhaps we are trapping key up events, rather than keypress events? (holding a key down repeats keypress events, but doesn't repeat key up events)

**Comment by jasongrout** [comment]
I just checked, and key repeat works just fine for me in the terminal in JupyterLab. Alpha-numeric in bash, as well as `hjkl` in vi all repeat fine when I hold down a key. I'm running 3bc0451c8592c47f561d7841b09fdcf4ded129bd

**Comment by 0x0L** [comment]
I tried to build from source with no success in a pristine anaconda3 docker image (same issue as #1103)

**Comment by jasongrout** [comment]
#1136 should fix the issue in #1103

**Comment by 0x0L** [comment]
@jasongrout @blink1073 

Turn out it was a keyboard extension from Apple that caused the issue. It's fixed with
```
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
```
and restarting the browser.

(and I was able to build using #1136 thanks)

**Comment by blink1073** [comment]
👍
