### ISSUE TITLE
Default variable filters no longer work for xeus-python

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#11012]
## Description

The default variable filters do not seem to work anymore in the debugger for xeus on 4.0 / master. It works well on JupyterLab 3.1 demo binder.

## Reproduce

1. Switch to xeus-python kernel
2. Activate the debugger
3. Enter a breakpoint
4. See that `debugpy` shows up on the list of variables

![Screenshot from 2021-09-04 19-12-24](https://user-images.githubusercontent.com/5832902/132104353-e79e0c59-7541-47f0-bc37-963225471684.png)

## Expected behavior

Should work as it used to in 3.1.

## Context

- JupyterLab version: 4.0.a7

**Comment by jtpio** [comment]
Thanks @krassowski for reporting.

For reference the filter is still defined here: 

https://github.com/jupyterlab/jupyterlab/blob/8c693aec308a57cf716c9a876a0a056b429c45b2/packages/debugger-extension/schema/main.json#L93-L115

But maybe it's not set correctly anymore.

**Comment by Mithil467** [comment]
I tried reproducing this issue but it seems to be working fine for me.
![image](https://user-images.githubusercontent.com/41439841/132909978-33f4136a-7213-4dda-946a-18a245284ccc.png)

I am on wsl.
Installed `xeus-python-0.12.5` from pypi.
Dev mode logs says `Run with XEUS 1.0.3`.
Running latest commit https://github.com/jupyterlab/jupyterlab/commit/b89064d77803c4b10fe2fc44d885507d2aa3051a on master.

**Comment by krassowski** [comment]
I cannot reproduce it either using current master/binder - interesting. I will take another look later on.

**Comment by krassowski** [comment]
I was able to reproduce it in the same session after switching tabs a few times between two debugger sessions (one with ipykernel, and one with xeus-python). Clearly my reproduction instructions were incomplete. I will try to narrow it down further later.
