### ISSUE TITLE
Rendering special and function variables broken after executing a cell

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/jupyterlab#11023]
## Description

The special variabels and function variables cannot be expanded after a cell has been executed, as shown below:

![bug_inspect_variable](https://user-images.githubusercontent.com/6754742/132469446-6b6d4a0f-b8d9-4cb6-8cc6-d71ecb1e0b1d.gif)

## Reproduce

1. Start the debugger
2. Click the special (or function) variables in the variables panel of the debugger => it's empty but that's expected
3. Execute a cell defining a new variable
4. Click again on the special (or function) variables, nothing happens in the UI, and an error message is shown in the console where you launched jupyter lab.

## Root of the bug

I've tracked down the bug, it seems that the variables are not correctly updated in the UI. Each variable has a variable_ref number. This number is generated by the kernel when it receives a [inspectVariable request](https://github.com/jupyterlab/jupyterlab/blob/master/packages/debugger/src/service.ts#L323). This request is sent when the debugger starts, and after each cell execution. When you expand a variable, a new request is sent to the kernel, with the variable_ref of the variable you want to expand.

Here, the spcial and function variables have variable reference when you start the debugger. Then, when executing the cell, new variable_ref numbers are generated by the kernel and sent back to the frontend. But when expanding the variable, JupyterLab sends the old variable_ref instead of the new one.

**Comment by jtpio** [comment]
Thanks @JohanMabille for reporting and @hbcarlos for investigating.

Looks like the relevant place in the code is here:

https://github.com/jupyterlab/jupyterlab/blob/96d76ef86fde932e8cfa6e9ffb69ac5a38a943a4/packages/debugger/src/panels/variables/tree.tsx#L157

And adding `variablesReference` to the key should help fix this case.

**Comment by jtpio** [comment]
@JohanMabille which version of JupyterLab is it? To know whether this needs a backport to 3.1.

**Comment by JohanMabille** [comment]
I was testing with 3.1.8.

**Comment by krassowski** [comment]
I saw this traceback on master, but don't have repro instructions:

```
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 267, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 193, in process_net_command_json
    cmd = on_request(py_db, request)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 949, in on_scopes_request
    Scope('Locals', ScopeRequest(int(variables_reference), 'locals'), False, presentationHint='locals'),
ValueError: invalid literal for int() with base 10: 'pid_101_id_140706351420800'
```

I don't think this is related to the PR that fixed this issue, but just leaving a note in case if you would think of a scenario in which fixing this bug could have lead to exposition of the issue giving the traceback above.
