### ISSUE TITLE
"\r" acts as "\n" in notebook's output

### ISSUE THREAD

**Issue by zachmoshe** [jupyterlab/jupyterlab#1104]
Seems like no matter what kernel I use, if I enter 'print("a\rb")' I see 'a' and 'b' as separate lines in the cell's output.
It's annoying as many packages use '\r' for textual progressbars (Keras for example) which leads to a lot of output..

**Comment by blink1073** [comment]
Hi @zachmoshe, thank you for the report.  It looks like we need to bring forward the [output cleanup](https://github.com/jupyter/notebook/blob/e77d7ebfb060d7ce45fb85e865a2c6d8e7635900/notebook/static/base/js/utils.js#L467) functionality of the classic notebook.
