### ISSUE TITLE
Notebook shows cells as hidden and does not unhide them

### ISSUE THREAD

**Issue by acelere** [jupyterlab/jupyterlab#11059]
## Description

When opening certain notebooks (this does not happen to all of the ones I have), some cells become hidden and even after clicking in the "+1 hidden cell" button, it does not become visible.
The cells have no tags (see gif below).
To unhide cells, as a workaround, I have to create another view for the notebook, which then shows all cells.

## Reproduce

See attached gif
![p8TZyXxXDS](https://user-images.githubusercontent.com/12059585/132900348-f4f80a48-9292-4f61-9c2d-fdf765f0b7ed.gif)

## Expected behavior

Original notebook should show all cells

## Context

- Operating System and version: Windows 11
- Browser and version: Chrome 93.0
System running on a Juoyterhub container with pip freeze below:

`jupyter troubleshoot`

$PATH:
        /usr/local/bin
        /usr/bin
        /bin
        /usr/local/games
        /usr/games

sys.path:
        /usr/local/bin
        /usr/local/lib/python39.zip
        /usr/local/lib/python3.9
        /usr/local/lib/python3.9/lib-dynload
        /usr/local/lib/python3.9/site-packages
        /usr/local/lib/python3.9/site-packages/CoolProp-6.4.2.dev0-py3.9-linux-x86_64.egg

sys.executable:
        /usr/local/bin/python

sys.version:
        3.9.6 (default, Jul 22 2021, 15:16:20) 
        [GCC 8.3.0]

platform.platform():
        Linux-5.4.0-81-generic-x86_64-with-glibc2.28

which -a jupyter:
        /usr/local/bin/jupyter

pip list:
        Package               Version
        --------------------- -----------
        absl-py               0.13.0
        aiohttp               3.7.4.post0
        alembic               1.7.0
        anyio                 3.3.0
        argon2-cffi           21.1.0
        asttokens             2.0.5
        async-generator       1.10
        async-timeout         3.0.1
        attrs                 21.2.0
        Babel                 2.9.1
        backcall              0.2.0
        bleach                4.1.0
        bqplot                0.12.30
        certifi               2021.5.30
        certipy               0.1.3
        cffi                  1.14.6
        chardet               4.0.0
        charset-normalizer    2.0.4
        click                 8.0.1
        colorama              0.4.4
        control               0.9.0
        CoolProp              6.4.2.dev0
        cryptography          3.4.8
        cvxpy                 1.1.15
        cycler                0.10.0
        Cython                0.29.24
        debugpy               1.4.1
        decorator             5.0.9
        defusedxml            0.7.1
        ecos                  2.0.7.post1
        entrypoints           0.3
        et-xmlfile            1.1.0
        executing             0.8.0
        flatbuffers           2.0
        future                0.18.2
        greenlet              1.1.1
        h5py                  3.4.0
        icecream              2.1.1
        idna                  3.2
        ipyfilechooser        0.4.4
        ipykernel             6.3.0
        ipympl                0.7.0
        ipython               7.27.0
        ipython-genutils      0.2.0
        ipywidgets            7.6.3
        jax                   0.2.19
        jaxlib                0.1.70
        jedi                  0.18.0
        jhsingle-native-proxy 0.7.6
        Jinja2                3.0.1
        json5                 0.9.6
        jsonschema            3.2.0
        jupyter-client        6.1.12
        jupyter-core          4.7.1
        jupyter-server        1.10.2
        jupyter-telemetry     0.1.0
        jupyterhub            1.4.2
        jupyterlab            3.1.9
        jupyterlab-pygments   0.1.2
        jupyterlab-server     2.7.2
        jupyterlab-widgets    1.0.0
        kiwisolver            1.3.2
        Mako                  1.1.5
        MarkupSafe            2.0.1
        matplotlib            3.4.3
        matplotlib-inline     0.1.2
        metakernel            0.27.5
        mistune               0.8.4
        mpmath                1.2.1
        multidict             5.1.0
        nbclassic             0.3.1
        nbclient              0.5.4
        nbconvert             6.1.0
        nbformat              5.1.3
        nest-asyncio          1.5.1
        notebook              6.4.3
        numpy                 1.21.2
        oauthlib              3.1.1
        octave-kernel         0.32.0
        openpyxl              3.0.7
        opt-einsum            3.3.0
        osqp                  0.6.2.post0
        packaging             21.0
        pamela                1.0.0
        pandas                1.3.2
        pandocfilters         1.4.3
        parso                 0.8.2
        pexpect               4.8.0
        pickleshare           0.7.5
        Pillow                8.3.1
        pip                   21.2.4
        prometheus-client     0.11.0
        prompt-toolkit        3.0.20
        ptyprocess            0.7.0
        pycparser             2.20
        Pygments              2.10.0
        pyOpenSSL             20.0.1
        pyparsing             2.4.7
        pyrsistent            0.18.0
        python-dateutil       2.8.2
        python-json-logger    2.0.2
        pytz                  2021.1
        pyzmq                 22.2.1
        qdldl                 0.1.5.post0
        requests              2.26.0
        requests-unixsocket   0.2.0
        ruamel.yaml           0.17.16
        ruamel.yaml.clib      0.2.6
        scikit-aero           0.1
        scipy                 1.7.1
        scs                   2.1.4
        seaborn               0.11.2
        Send2Trash            1.8.0
        setuptools            57.4.0
        simpervisor           0.4
        six                   1.16.0
        slycot                0.4.0
        sniffio               1.2.0
        SQLAlchemy            1.4.23
        sympy                 1.8
        terminado             0.11.1
        testpath              0.5.0
        torch                 1.8.1+cpu
        torchaudio            0.8.1
        torchvision           0.9.1+cpu
        tornado               6.1
        traitlets             5.0.5
        traittypes            0.2.1
        typing-extensions     3.10.0.1
        uncertainties         3.1.6
        urllib3               1.26.6
        voila                 0.2.10
        wcwidth               0.2.5
        webencodings          0.5.1
        websocket-client      1.2.1
        wheel                 0.36.2
        widgetsnbextension    3.5.1
        xarray                0.19.0
        xeus-python           0.12.5
        xlrd                  2.0.1
        yarl                  1.6.3

**Comment by fcollonval** [comment]
Thanks you for reporting the bug @acelere 

Some root causes of similar issues have been fixed in the latest versions. Could you please upgrade to the latest (3.1.11) ? And report here if it fixes your issue?

If you are still seeing the issue, you could try using those settings for the notebook:

```
{
    "renderCellOnIdle": false,
    "numberCellsToRenderDirectly": 10000000000000
}
```

You can access the settings through the menu `Settings` -> `Advanced Settings Editor` -> `Notebook` and in the right pane (User Preferences) paste the above settings.

**Comment by acelere** [comment]
Thanks for the quick response @fcollonval !

I tried editing the settings and it worked.
I will need to generate a new container to test 3.1.11, but that might take a few days due to workload. I will post when done.

Thanks again!

**Comment by acelere** [comment]
Hello,

I can confirm that with Jupyterlab 3.1.11 this bug is gone. Closing the issue.

Thank you very much for responding quickly.
