### ISSUE TITLE
Change in behaviour of adding parentheses around highleted text in code editor

### ISSUE THREAD

**Issue by catalys1** [jupyterlab/jupyterlab#11051]
## Description

Prior to version `3.1`, I was able to highlight text in the editor and type `(` (opening paren), and the highlighted text would be automatically enclosed in parentheses. Same for brackets and curly braces. But after upgrading to `3.1.*`, this feature has dissapeared, and the text simply gets replaced with the character in question.

## Reproduce

1. Install jupyterlab >= 3.1
2. In a code cell, type some alphanumeric characters
3. Highlight the characters
4. Type the `(` character, the highlighted characters will be replaced

I verified that the new behaviour occurs starting in the `3.1.0` release.

## Expected behavior

The old behaviour of versions < 3.1, where the text gets surrounded by (parenthesis, brackets, braces).

## Context

- Operating System and version: Linux Ubuntu 20.04 
- Browser and version: Chrome 93
- JupyterLab version: 3.1.11

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/user/testenv/bin
	/home/user/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin
	/home/user/mongodb/mongodb/bin

sys.path:
	/home/user/testenv/bin
	/usr/lib/python38.zip
	/usr/lib/python3.8
	/usr/lib/python3.8/lib-dynload
	/home/user/testenv/lib/python3.8/site-packages

sys.executable:
	/home/user/testenv/bin/python3

sys.version:
	3.8.10 (default, Jun  2 2021, 10:49:15) 
	[GCC 9.4.0]

platform.platform():
	Linux-5.4.0-81-generic-x86_64-with-glibc2.29

which -a jupyter:
	/home/user/testenv/bin/jupyter

pip list:
	Package             Version  
	------------------- ---------
	anyio               3.3.1    
	argon2-cffi         21.1.0   
	attrs               21.2.0   
	Babel               2.9.1    
	backcall            0.2.0    
	bleach              4.1.0    
	certifi             2021.5.30
	cffi                1.14.6   
	charset-normalizer  2.0.4    
	debugpy             1.4.3    
	decorator           5.0.9    
	defusedxml          0.7.1    
	entrypoints         0.3      
	idna                3.2      
	ipykernel           6.4.0    
	ipython             7.27.0   
	ipython-genutils    0.2.0    
	ipywidgets          7.6.4    
	jedi                0.18.0   
	Jinja2              3.0.1    
	json5               0.9.6    
	jsonschema          3.2.0    
	jupyter             1.0.0    
	jupyter-client      7.0.2    
	jupyter-console     6.4.0    
	jupyter-core        4.7.1    
	jupyter-packaging   0.7.12   
	jupyter-server      1.11.0   
	jupyterlab          3.1.11   
	jupyterlab-pygments 0.1.2    
	jupyterlab-server   2.8.1    
	jupyterlab-widgets  1.0.1    
	MarkupSafe          2.0.1    
	matplotlib-inline   0.1.3    
	mistune             0.8.4    
	nbclassic           0.3.1    
	nbclient            0.5.4    
	nbconvert           6.1.0    
	nbformat            5.1.3    
	nest-asyncio        1.5.1    
	notebook            6.4.3    
	packaging           21.0     
	pandocfilters       1.4.3    
	parso               0.8.2    
	pexpect             4.8.0    
	pickleshare         0.7.5    
	pip                 20.0.2   
	pkg-resources       0.0.0    
	prometheus-client   0.11.0   
	prompt-toolkit      3.0.20   
	ptyprocess          0.7.0    
	pycparser           2.20     
	Pygments            2.10.0   
	pyparsing           2.4.7    
	pyrsistent          0.18.0   
	python-dateutil     2.8.2    
	pytz                2021.1   
	pyzmq               22.2.1   
	qtconsole           5.1.1    
	QtPy                1.11.0   
	requests            2.26.0   
	requests-unixsocket 0.2.0    
	Send2Trash          1.8.0    
	setuptools          44.0.0   
	six                 1.16.0   
	sniffio             1.2.0    
	terminado           0.12.1   
	testpath            0.5.0    
	tornado             6.1      
	traitlets           5.1.0    
	urllib3             1.26.6   
	wcwidth             0.2.5    
	webencodings        0.5.1    
	websocket-client    1.2.1    
	widgetsnbextension  3.5.1
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 2021-09-09 15:34:26.239 ServerApp] jupyterlab | extension was successfully linked.
[I 2021-09-09 15:34:26.370 ServerApp] nbclassic | extension was successfully linked.
[I 2021-09-09 15:34:26.392 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-09-09 15:34:26.393 LabApp] JupyterLab extension loaded from /home/user/testenv/lib/python3.8/site-packages/jupyterlab
[I 2021-09-09 15:34:26.393 LabApp] JupyterLab application directory is /home/user/testenv/share/jupyter/lab
[I 2021-09-09 15:34:26.396 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-09-09 15:34:26.396 ServerApp] The port 8888 is already in use, trying another port.
[I 2021-09-09 15:34:26.397 ServerApp] Serving notebooks from local directory: /home/catalys1/testenv/lab
[I 2021-09-09 15:34:26.397 ServerApp] Jupyter Server 1.11.0 is running at:
[I 2021-09-09 15:34:26.397 ServerApp] http://localhost:8889/lab?token=b35a16129b153e58bfea3bbd2941a9cfc8c09e2206ed88bb
[I 2021-09-09 15:34:26.397 ServerApp]  or http://127.0.0.1:8889/lab?token=b35a16129b153e58bfea3bbd2941a9cfc8c09e2206ed88bb
[I 2021-09-09 15:34:26.397 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-09-09 15:34:26.417 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/user/.local/share/jupyter/runtime/jpserver-816277-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/lab?token=b35a16129b153e58bfea3bbd2941a9cfc8c09e2206ed88bb
     or http://127.0.0.1:8889/lab?token=b35a16129b153e58bfea3bbd2941a9cfc8c09e2206ed88bb
[W 2021-09-09 15:34:29.721 LabApp] Could not determine jupyterlab build status without nodejs
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
None

</pre>
</details>

**Comment by jasongrout** [comment]
Thanks for filing this. We're already discussing it at #9897, and we invite you to post a comment there.

**Comment by jasongrout** [comment]
In particular, you can enable the previous behavior by selecting the "Setting > Auto Close Brackets" option to turn it back on.

**Comment by catalys1** [comment]
Ok great, thanks!
