### ISSUE TITLE
Jupyter lab build fail with "svgbob-wasm and webpack 5.52.0"

### ISSUE THREAD

**Issue by kimyoungjin06** [jupyterlab/jupyterlab#11060]
## Description

Jupyter lab build fail with **"svgbob-wasm and webpack 5.52.0"**

## Reproduce

```cmd
$jupyter lab build

... highlighted
ERROR in ./node_modules/svgbob-wasm/svgbob_wasm_bg.wasm 1:0
Module parse failed: Unexpected character '' (1:0)
The module seem to be a WebAssembly module, but module is not flagged as WebAssembly module for webpack.
...
webpack 5.52.0 compiled with 1 error and 10 warnings in 13277 ms
...
```

## Context

- Operating System and version: Ubuntu 20.04 
- Browser and version: Chrome.. 
- JupyterLab version: 3.1.11 

<details><summary>Command Line Output</summary>
<pre>
[LabBuildApp] Searching ['/root', '/root/.jupyter', '/opt/conda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[LabBuildApp] Looking for jupyter_config in /etc/jupyter
[LabBuildApp] Looking for jupyter_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /opt/conda/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /root/.jupyter
[LabBuildApp] Looking for jupyter_config in /root
[LabBuildApp] Looking for JupyterLab_config in /etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /opt/conda/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /root/.jupyter
[LabBuildApp] Looking for JupyterLab_config in /root
[LabBuildApp] JupyterLab 3.1.11
[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Node v15.12.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, not minimized)
[LabBuildApp] > node /opt/conda/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
/[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.47s.

[LabBuildApp] > node /opt/conda/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
\[LabBuildApp] yarn run v1.21.1
$ /opt/conda/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.27s.

[LabBuildApp] > node /opt/conda/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod
-[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.config.js
assets by status 31.6 MiB [cached] 152 assets
orphan modules 6.37 MiB [orphan] 2359 modules
runtime modules 115 KiB 15 modules
built modules 26.6 MiB (javascript) 5.25 KiB (share-init) 5.25 KiB (consume-shared) [built]
  modules by path ./node_modules/ 26.6 MiB
    javascript modules 26.6 MiB 1545 modules
    json modules 37.7 KiB 8 modules
  provide-module modules 5.25 KiB
    modules by path provide shared module (default) @jupyterlab/ 3.65 KiB 89 modules
    modules by path provide shared module (default) @lumino/ 588 bytes 14 modules
    modules by path provide shared module (default) @jupyter-widgets/ 168 bytes 4 modules
  consume-shared-module modules 5.25 KiB 62 modules
  modules by path ./build/ 25.1 KiB
    ./build/bootstrap.js 3.86 KiB [built] [code generated]
    ./build/index.out.js + 1 modules 21.3 KiB [built] [code generated]

WARNING in ./node_modules/vega-lite/build/src/index.js 5:0-30
Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)
 @ consume shared module (default) vega-lite@^4.0.2 (strict) (fallback: ./node_modules/vega-lite/build/src/index.js)
 @ ./node_modules/vega-embed/build/vega-embed.module.js 6:0-44 821:16-30
 @ consume shared module (default) vega-embed@^6.2.1 (strict) (fallback: ./node_modules/vega-embed/build/vega-embed.module.js)
 @ ./node_modules/@jupyterlab/vega5-extension/lib/index.js 166:28-48
 @ consume shared module (default) @jupyterlab/vega5-extension@~3.1.11 (strict) (fallback: ./node_modules/@jupyterlab/vega5-extension/lib/index.js)
 @ ./build/index.out.js 171:16-54
 @ ./build/bootstrap.js

WARNING in license-webpack-plugin: could not find any license file for jupyterlab-dash. Use the licenseTextOverrides option to add the license text if desired.

WARNING in license-webpack-plugin: could not find any license file for markdown-it-anchor. Use the licenseTextOverrides option to add the license text if desired.

WARNING in license-webpack-plugin: could not find any license file for markdown-it-diagrams. Use the licenseTextOverrides option to add the license text if desired.

WARNING in license-webpack-plugin: could not find any license file for vega-lite. Use the licenseTextOverrides option to add the license text if desired.

WARNING in license-webpack-plugin: could not find any license file for popper.js. Use the licenseTextOverrides option to add the license text if desired.

WARNING in license-webpack-plugin: could not find any license file for gud. Use the licenseTextOverrides option to add the license text if desired.

WARNING in license-webpack-plugin: could not find any license file for moment-mini. Use the licenseTextOverrides option to add the license text if desired.

WARNING in license-webpack-plugin: could not find any license file for backbone. Use the licenseTextOverrides option to add the license text if desired.

WARNING in license-webpack-plugin: could not find any license file for jupyterlab-plotly. Use the licenseTextOverrides option to add the license text if desired.

ERROR in ./node_modules/svgbob-wasm/svgbob_wasm_bg.wasm 1:0
Module parse failed: Unexpected character '' (1:0)
The module seem to be a WebAssembly module, but module is not flagged as WebAssembly module for webpack.
BREAKING CHANGE: Since webpack 5 WebAssembly is not enabled by default and flagged as experimental feature.
You need to enable one of the WebAssembly experiments via 'experiments.asyncWebAssembly: true' (based on async modules) or 'experiments.syncWebAssembly: true' (like webpack 4, deprecated).
For files that transpile to WebAssembly, make sure to set the module type in the 'module.rules' section of the config (e. g. 'type: "webassembly/async"').
(Source code omitted for this binary file)
 @ ./node_modules/svgbob-wasm/svgbob_wasm.js 1:0-46
 @ ./node_modules/markdown-it-diagrams/lib/index.js 14:29-50
 @ consume shared module (default) markdown-it-diagrams@=0.2.0-alpha.0 (strict) (fallback: ./node_modules/markdown-it-diagrams/lib/index.js)
 @ ./node_modules/@agoose77/jupyterlab-markup/lib/builtins/diagrams.js 36:44-37:78
 @ ./node_modules/@agoose77/jupyterlab-markup/lib/builtins/index.js 3:0-38 9:42-50
 @ ./node_modules/@agoose77/jupyterlab-markup/lib/plugin.js 10:0-38 89:25-33
 @ ./build/index.out.js
 @ ./build/bootstrap.js

webpack 5.52.0 compiled with 1 error and 10 warnings in 13277 ms

asset index.css 15.8 KiB [compared for emit] (name: index)
asset index.js 0 bytes [compared for emit] [minimized] (name: index)
Entrypoint index 15.8 KiB = index.css 15.8 KiB index.js 0 bytes
./node_modules/@jupyterlab/theme-dark-extension/style/theme.css 50 bytes [built] [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/variables.css 15.3 KiB [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-dark-extension/style/theme.css 472 bytes [code generated]
webpack 5.52.0 compiled successfully in 953 ms

asset index.css 14.7 KiB [compared for emit] (name: index)
asset index.js 0 bytes [compared for emit] [minimized] (name: index)
Entrypoint index 14.7 KiB = index.css 14.7 KiB index.js 0 bytes
./node_modules/@jupyterlab/theme-light-extension/style/theme.css 50 bytes [built] [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/variables.css 14.3 KiB [code generated]
css ./node_modules/css-loader/dist/cjs.js!./node_modules/@jupyterlab/theme-light-extension/style/theme.css 472 bytes [code generated]
webpack 5.52.0 compiled successfully in 950 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 48, in debug_logging
    yield

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/labapp.py", line 176, in start
    raise e

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/labapp.py", line 172, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/commands.py", line 482, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/commands.py", line 697, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

An error occurred.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-j56earj3.log
[LabBuildApp] Exiting application: JupyterLab

</pre>
</details>

**Comment by kimyoungjin06** [comment]
with `conda update --all`

same problem with `jupyterlab 3.1.7 and webpack 5.50.0`

```
jupyter_client-7.0.1 | 88 KB     | ##################################### | 100% 
wheel-0.37.0         | 33 KB     | ##################################### | 100% 
prompt-toolkit-3.0.1 | 249 KB    | ##################################### | 100% 
threadpoolctl-2.2.0  | 16 KB     | ##################################### | 100% 
conda-build-3.21.5   | 551 KB    | ##################################### | 100% 
jupyterlab_server-2. | 44 KB     | ##################################### | 100% 
wcwidth-0.2.5        | 26 KB     | ##################################### | 100% 
scipy-1.7.1          | 16.6 MB   | ##################################### | 100% 
patchelf-0.13        | 85 KB     | ##################################### | 100% 
```

**Comment by agoose77** [comment]
Hi @kimyoungjin06 

Why are you calling `jupyter lab build`? Is there a particular extension you need to compile from source?

`svgbob-wasm` is a module used by `jupyterlab-markup`, an extension that I maintain. This can be installed from conda-forge or PyPI without building JupyterLab. In any case, I don't think these errors should happen, so try clearing your build directory of the various generated files (e.g. `node_modules`) and try again (if you need to build JupyterLab).

**Comment by kimyoungjin06** [comment]
@agoose77 

My extension list

```cmd
# jupyter labextension list
JupyterLab v3.1.7
/opt/conda/share/jupyter/labextensions
        jupyterlab-plotly v5.1.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
        @agoose77/jupyterlab-markup v1.0.0 enabled OK
        jupyterlab-dash v0.4.0 enabled OK
        jupyterlab-slide-mode-keyboard-shortcuts v0.3.0 enabled OK


The following source extensions are overshadowed by older prebuilt extensions:
    jupyterlab-plotly

Build recommended, please run `jupyter lab build`:
    @agoose77/jupyterlab-markup needs to be included in build
    jupyterlab-slide-mode-keyboard-shortcuts needs to be included in build
    jupyterlab-dash needs to be included in build
```

And check the pre-install case with `svgbob-wasm`.
```cmd
# conda uninstall svgbob-wasm
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - svgbob-wasm


# pip uninstall svgbob-wasm
WARNING: Skipping svgbob-wasm as it is not installed.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

Is there any test for `jupyter lab build`?

**Comment by agoose77** [comment]
Ah, you're using `jupyterlab-slide-mode-keyboard-shortcuts`, which doesn't have a PyPI / conda package at the moment.

In any case, it looks like you're using a mix of pre-built (from PyPI and conda) and source extensions (from npm). I would suggest creating a clean environment, and avoid installing from npm unless you have to. The following extensions are available on Conda:
- jupyterlab-markup
- jupyterlab-plotly
-  jupyterlab-dash

Only `jupyterlab-slide-mode-keyboard-shortcuts` isn't on Conda, but it is on PyPI!

So, it looks like you won't need to perform any source builds

**Comment by kimyoungjin06** [comment]
I was confused about **best install method** within PyPi(is this pip?) / conda or labextension install.

I remove `jupyterlab-markup` with `jupyter labextension uninstall`.
And install with `PyPi`.
Finally, success to build.

But, still, I have a tiny stupid question.
What is the best installation method or maintenance lab extension packages?

**Comment by agoose77** [comment]
With JupyterLab >= 3.0, the new _prebuilt_ extensions are much faster for end-users to install, (because) they don't require NodeJS. There are benefits to building a monolithic JupyterLab, but someone with more knowledge can probably chime in there. For most users, the Conda/PyPI installation methods should be prefered.

**Comment by kimyoungjin06** [comment]
Thanks for your hospitable explanation @agoose77.

Your jupyter-markup is so nice :)
Sincely,
