### ISSUE TITLE
404 errors logged when using "Python [py3k]" kernel

### ISSUE THREAD

**Issue by svenefftinge** [jupyterlab/jupyterlab#1108]
I see
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8889/api/kernelspecs/Python%20%5Bpy3k%5D?1476798847519 
when starting a notebook for python 3.
Also the kernel indicator doesn't show the name. 
Seems like the jupyter webservice doesn't translate special characters like jupyterlab does?

**Comment by blink1073** [comment]
Hi @svenefftinge, how did you arrive at this condition?  I just tried on master these steps and it worked fine:

File > New Notebook
Selected "Python [conda env:jlab-0.5]"

<img width="540" alt="screen shot 2016-10-18 at 1 00 21 pm" src="https://cloud.githubusercontent.com/assets/2096628/19489966/dd3dc51a-9532-11e6-8605-0d01a90a6e5c.png">

**Comment by svenefftinge** [comment]
I could even reproduce something similar with the classic notebook. When switching the kernel to "Python [Root]" or "Python [py3k]" (installed through conda AFAIR), I get:

logo-64x64.png:1 GET http://localhost:8888/kernelspecs/Python%20[py3k]/logo-64x64.png 404 (Not Found)

Looks to me that the get API for kernelspecs doesn't handle encoded characters well, but it's really strange that only I see it.

**Comment by svenefftinge** [comment]
What should the API call look like for a kernelspec name "Python [py3k]"?
http://localhost:8889/api/kernelspecs/Python%20%5Bpy3k%5D returns 404
while http://localhost:8889/api/kernelspecs lists the kernel spec.

If I use another kernel without special characters it works. E.g.

http://localhost:8889/api/kernelspecs/ir

Any ideas?

**Comment by svenefftinge** [comment]
Looks like this is a jupyter issue.
The regex  in [1] suggests that whitespace and brackets are not allowed.

[1] https://github.com/jupyter/notebook/blob/master/notebook/services/kernelspecs/handlers.py#L82

suggests that only

**Comment by svenefftinge** [comment]
For me it is done on updateKernelNameItem

https://github.com/jupyterlab/jupyterlab/blob/master/src/toolbar/kernel.ts#L129

which calls

https://github.com/jupyterlab/services/blob/master/src/kernel/default.ts#L1247

where you can see that the name is just encoded and appended to the URL.

**Comment by svenefftinge** [comment]
@blink1073 Is it really the name or the displayname in your case? 
Seems like my kernelspecs are bogus.

**Comment by blink1073** [comment]
Ah, right, the actual kernel name should be something like `python3`.  Can you try updating `conda install nb_conda_kernels`?

**Comment by blink1073** [comment]
This was fixed by #1201.
