### ISSUE TITLE
Highlight all found matches in scroll bar

### ISSUE THREAD

**Issue by pmarcellino** [jupyterlab/jupyterlab#11098]
I'm not sure if this is a feature request, or if it already exists, and I just can't find it.

When using other common tools, e.g. google chrome, spyder, adobe reader, if you search for something, it will highlight all locations in the scroll bar on the right side of the document.

Does this exist for jupyter lab?

**Comment by krassowski** [comment]
It does not exist currently. It was previously brought up in #7073, let's focus the discussion there.
