### ISSUE TITLE
Cells disappear after closing notebook

### ISSUE THREAD

**Issue by NA-Dev** [jupyterlab/jupyterlab#11097]
## Description

I saved a notebook with no cells collapsed. Later, when I open it, a few of the cells have become invisible. They just appear as a line in the notebook, not the three dots I get when I collapse cells. The code is still there, just invisible. If I copy paste the cell, it shows up again. But, next time I reopen the notebook, they will be gone again. If I open the file in VS Code instead of Jupyter Lab, the cell and code are displayed normally.

![image](https://user-images.githubusercontent.com/31260131/133649589-f2594547-302f-4cf3-9596-e7eacf62271c.png)

## Reproduce

Create notebook, save, close notebook, reopen.

## Expected behavior

Cells to appear

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /home/username/.local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games
        /snap/bin

sys.path:
        /home/username/.local/bin
        /home/username
        /usr/lib/python38.zip
        /usr/lib/python3.8
        /usr/lib/python3.8/lib-dynload
        /home/username/.local/lib/python3.8/site-packages
        /usr/local/lib/python3.8/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.8.10 (default, Jun  2 2021, 10:49:15)
        [GCC 9.4.0]

platform.platform():
        Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29

which -a jupyter:
        /home/username/.local/bin/jupyter
        /usr/bin/jupyter
        /bin/jupyter

pip list:
        Package                Version
        ---------------------- --------------------
        anyio                  3.3.0
        argon2-cffi            20.1.0
        async-generator        1.10
        attrs                  19.3.0
        Automat                0.8.0
        Babel                  2.9.1
        backcall               0.2.0
        bleach                 4.0.0
        blinker                1.4
        certifi                2019.11.28
        cffi                   1.14.6
        chardet                3.0.4
        cliapp                 1.20180812.1
        Click                  7.0
        cloud-init             21.2
        cmdtest                0.32+git
        colorama               0.4.3
        command-not-found      0.3
        configobj              5.0.6
        constantly             15.1.0
        cryptography           2.8
        dbus-python            1.2.16
        debugpy                1.4.1
        decorator              5.0.9
        defusedxml             0.7.1
        distro                 1.4.0
        distro-info            0.23ubuntu1
        entrypoints            0.3
        Flask                  1.1.1
        httplib2               0.14.0
        hyperlink              19.0.0
        idna                   2.8
        importlib-metadata     1.5.0
        incremental            16.10.1
        ipykernel              6.0.3
        ipython                7.26.0
        ipython-genutils       0.2.0
        ipywidgets             7.6.3
        itsdangerous           1.1.0
        jedi                   0.18.0
        Jinja2                 2.10.1
        json5                  0.9.6
        jsonpatch              1.22
        jsonpointer            2.0
        jsonschema             3.2.0
        jupyter                1.0.0
        jupyter-client         6.1.12
        jupyter-console        6.4.0
        jupyter-core           4.7.1
        jupyter-server         1.10.2
        jupyterlab             3.1.6
        jupyterlab-pygments    0.1.2
        jupyterlab-server      2.6.2
        jupyterlab-widgets     1.0.0
        keyring                18.0.1
        language-selector      0.1
        launchpadlib           1.10.13
        lazr.restfulclient     0.14.2
        lazr.uri               1.0.3
        Markdown               3.1.1
        MarkupSafe             1.1.0
        matplotlib-inline      0.1.2
        mistune                0.8.4
        more-itertools         4.2.0
        nbclassic              0.3.1
        nbclient               0.5.3
        nbconvert              6.1.0
        nbformat               5.1.3
        nest-asyncio           1.5.1
        netifaces              0.10.4
        notebook               6.4.1
        oauthlib               3.1.0
        packaging              21.0
        pandocfilters          1.4.3
        parso                  0.8.2
        pexpect                4.6.0
        pickleshare            0.7.5
        pip                    21.2.4
        prometheus-client      0.11.0
        prompt-toolkit         3.0.19
        ptyprocess             0.7.0
        pyasn1                 0.4.2
        pyasn1-modules         0.2.1
        pycparser              2.20
        Pygments               2.9.0
        PyGObject              3.36.0
        PyHamcrest             1.9.0
        pyinotify              0.9.6
        PyJWT                  1.7.1
        pymacaroons            0.13.0
        PyNaCl                 1.3.0
        pyngrok                5.0.5
        pyOpenSSL              19.0.0
        pyparsing              2.4.7
        pyrsistent             0.15.5
        pyserial               3.4
        python-apt             2.0.0+ubuntu0.20.4.5
        python-dateutil        2.8.2
        python-debian          0.1.36ubuntu1
        pytz                   2021.1
        PyYAML                 5.3.1
        pyzmq                  22.2.1
        qtconsole              5.1.1
        QtPy                   1.9.0
        redis                  3.5.3
        requests               2.22.0
        requests-unixsocket    0.2.0
        rise                   5.7.1
        SecretStorage          2.3.1
        Send2Trash             1.7.1
        service-identity       18.1.0
        setuptools             45.2.0
        simplejson             3.16.0
        six                    1.14.0
        sniffio                1.2.0
        sos                    4.1
        ssh-import-id          5.10
        systemd-python         234
        terminado              0.10.1
        testpath               0.5.0
        tornado                6.1
        traitlets              5.0.5
        ttystatus              0.38
        Twisted                18.9.0
        ubuntu-advantage-tools 27.2
        ufw                    0.36
        unattended-upgrades    0.1
        urllib3                1.25.8
        wadllib                1.3.3
        wcwidth                0.2.5
        webencodings           0.5.1
        websocket-client       1.1.0
        Werkzeug               0.16.1
        wheel                  0.34.2
        widgetsnbextension     3.5.1
        zipp                   1.0.0
        zope.interface         4.7.1
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 2021-09-16 12:19:55.735 ServerApp] Searching ['/home/username', '/home/username/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2021-09-16 12:19:55.735 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2021-09-16 12:19:55.736 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2021-09-16 12:19:55.736 ServerApp] Looking for jupyter_config in /usr/etc/jupyter
[D 2021-09-16 12:19:55.736 ServerApp] Looking for jupyter_config in /home/username/.jupyter
[D 2021-09-16 12:19:55.736 ServerApp] Looking for jupyter_config in /home/username
[D 2021-09-16 12:19:55.737 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2021-09-16 12:19:55.737 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2021-09-16 12:19:55.737 ServerApp] Looking for jupyter_server_config in /usr/etc/jupyter
[D 2021-09-16 12:19:55.737 ServerApp] Looking for jupyter_server_config in /home/username/.jupyter
[D 2021-09-16 12:19:55.737 ServerApp] Looking for jupyter_server_config in /home/username
[D 2021-09-16 12:19:55.738 ServerApp] Paths used for configuration of jupyter_server_config:
        /etc/jupyter/jupyter_server_config.json
[D 2021-09-16 12:19:55.739 ServerApp] Paths used for configuration of jupyter_server_config:
        /usr/local/etc/jupyter/jupyter_server_config.json
[D 2021-09-16 12:19:55.739 ServerApp] Paths used for configuration of jupyter_server_config:
        /usr/etc/jupyter/jupyter_server_config.json
[D 2021-09-16 12:19:55.739 ServerApp] Paths used for configuration of jupyter_server_config:
        /home/username/.jupyter/jupyter_server_config.json
[I 2021-09-16 12:19:55.748 ServerApp] jupyterlab | extension was successfully linked.
[D 2021-09-16 12:19:55.749 ServerApp] Raising open file limit: soft 1024->4096; hard 4096->4096
[I 2021-09-16 12:19:55.766 LabApp] JupyterLab extension loaded from /home/username/.local/lib/python3.8/site-packages/jupyterlab
[I 2021-09-16 12:19:55.766 LabApp] JupyterLab application directory is /home/username/.local/share/jupyter/lab
[I 2021-09-16 12:19:55.769 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-09-16 12:19:55.770 ServerApp] Serving notebooks from local directory: /home/username
[I 2021-09-16 12:19:55.770 ServerApp] Jupyter Server 1.10.2 is running at:
[I 2021-09-16 12:19:55.770 ServerApp] http://localhost:8888/lab?token=c1034f69b5c93fa8f83d7e250337a90d3a5e59a5927dee95
[I 2021-09-16 12:19:55.770 ServerApp]  or http://127.0.0.1:8888/lab?token=c1034f69b5c93fa8f83d7e250337a90d3a5e59a5927dee95
[I 2021-09-16 12:19:55.770 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-09-16 12:19:55.773 ServerApp]

    To access the server, open this file in a browser:
        file:///home/username/.local/share/jupyter/runtime/jpserver-24001-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=c1034f69b5c93fa8f83d7e250337a90d3a5e59a5927dee95
     or http://127.0.0.1:8888/lab?token=c1034f69b5c93fa8f83d7e250337a90d3a5e59a5927dee95
[D 2021-09-16 12:19:57.270 ServerApp] Initializing websocket connection /api/kernels/67a0d1b6-d6bb-428e-9470-df242cafc989/channels
[W 2021-09-16 12:19:57.273 ServerApp] 404 GET /api/kernels/67a0d1b6-d6bb-428e-9470-df242cafc989/channels?session_id=5d7e5430-7a98-47a8-ade8-813ad43ed995 (127.0.0.1): Kernel does not exist: 67a0d1b6-d6bb-428e-9470-df242cafc989
[D 2021-09-16 12:19:57.273 ServerApp] Using contents: services/contents
[D 2021-09-16 12:19:57.298 ServerApp] Path favicon.ico served from /home/username/.local/lib/python3.8/site-packages/jupyter_server/static/favicon.ico
[D 2021-09-16 12:19:57.300 ServerApp] Path style/bootstrap.min.css served from /home/username/.local/lib/python3.8/site-packages/jupyter_server/static/style/bootstrap.min.css
[D 2021-09-16 12:19:57.302 ServerApp] Path style/bootstrap-theme.min.css served from /home/username/.local/lib/python3.8/site-packages/jupyter_server/static/style/bootstrap-theme.min.css
[D 2021-09-16 12:19:57.303 ServerApp] Path style/index.css served from /home/username/.local/lib/python3.8/site-packages/jupyter_server/static/style/index.css
[D 2021-09-16 12:19:57.305 ServerApp] Path logo/logo.png served from /home/username/.local/lib/python3.8/site-packages/jupyter_server/static/logo/logo.png
[W 2021-09-16 12:19:57.306 ServerApp] 404 GET /api/kernels/67a0d1b6-d6bb-428e-9470-df242cafc989/channels?session_id=5d7e5430-7a98-47a8-ade8-813ad43ed995 (127.0.0.1) 36.24ms referer=None
[D 2021-09-16 12:19:57.320 ServerApp] Initializing websocket connection /api/kernels/67a0d1b6-d6bb-428e-9470-df242cafc989/channels
[W 2021-09-16 12:19:57.322 ServerApp] 404 GET /api/kernels/67a0d1b6-d6bb-428e-9470-df242cafc989/channels?session_id=b1160666-3397-4445-afbd-495a9fbb6808 (127.0.0.1): Kernel does not exist: 67a0d1b6-d6bb-428e-9470-df242cafc989
[D 2021-09-16 12:19:57.322 ServerApp] Using contents: services/contents
[W 2021-09-16 12:19:57.322 ServerApp] 404 GET /api/kernels/67a0d1b6-d6bb-428e-9470-df242cafc989/channels?session_id=b1160666-3397-4445-afbd-495a9fbb6808 (127.0.0.1) 2.12ms referer=None
[D 2021-09-16 12:20:01.278 ServerApp] Initializing websocket connection /api/kernels/67a0d1b6-d6bb-428e-9470-df242cafc989/channels
[W 2021-09-16 12:20:01.279 ServerApp] Replacing stale connection: 67a0d1b6-d6bb-428e-9470-df242cafc989:5d7e5430-7a98-47a8-ade8-813ad43ed995
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Nothing output in console
</pre>
</details>

**Comment by echarles** [comment]
Hi, can you upgrade to latest jupyterlab and try again. The issue should be solved.

**Comment by NA-Dev** [comment]
Updated to 3.1.6 with pip. Indeed it is fixed! Thank you so much!
