### ISSUE TITLE
Add a configuration to avoid checkSync function

### ISSUE THREAD

**Issue by jmari** [jupyterlab/jupyterlab#11103]
### Problem

Pharo Smalltalk kernel for Jupyter is already working with debugging support, but I can not avoid a continuous alert about code editor out of sync.
Because Smalltalk is not text file code oriented, the debugged code is always slightly different from the code you write.
- Code within the current execution stack  has tabs and other characters (or a "self halt"  added to stop the execution)
- You should be able to debug inside other classes, this classes has its own code. When you step in inside (in the vide we look inside the "add:" method in an Ordered collection instance), code will be totally different from our executed code so that we will be always out of sync 

### Proposed Solution

I think a configuration property or other way to disable the message will be enough, I know current execution line won't be flashed, but it is better to be able to debug inside other objects than flashing the current exec row in the code editor. For me having this information in the debugger panel is ok.

@krassowski I leave you a video, let me now if I have made a clear exposition of the subject. Thanks

https://user-images.githubusercontent.com/1989894/133825108-cabdeb33-21f1-4057-a97c-f94c67da5294.mp4

**Comment by jasongrout** [comment]
A shot in the dark: are the code line endings `\n` or `\r\n` in what is sent from the kernel? This message pops up frequently when notebooks have code cells where the line endings are `\r\n` instead of `\n`. See many related issues at https://github.com/jupyterlab/jupyterlab/search?q=code+editor+out+of+sync&type=issues

**Comment by jmari** [comment]
did you see the video? the code is indeed totally different, I know that code from the stack is different from the editor, not only tabs or lf

**Comment by krassowski** [comment]
@jmari this is the same what I was suggesting on gitter: maybe it does not matter that the code is different and the only thing that matters is that the line endings and different.

**Comment by jmari** [comment]
You mean the _checkSync function only checks the end line characters? What a strange function and alert message...anyway I will test it replacing the end lines to be sure it has the same codification and I will let you know! Sorry I didn't understand the only thing that matters is line ending!

**Comment by jasongrout** [comment]
> You mean the _checkSync function only checks the end line characters?

No. Just that there is a known bug that causes that error that has to do with the line endings being `\r\n` instead of `\n`.

**Comment by jmari** [comment]
You are right, replacing cr by lf solved the problem...I'm sorry for my missunderstood and thaks for your help!

**Comment by jasongrout** [comment]
By the way, I think it is really cool that you are using Smalltalk in JupyterLab!

**Comment by jasongrout** [comment]
> No. Just that there is a known bug that causes that error that has to do with the line endings being `\r\n` instead of `\n`.

FYI, this bug of line endings in notebook cells is being tracked in #9465.
