### ISSUE TITLE
ipykernel status changes from busy to idle after few seconds during while loop execution.

### ISSUE THREAD

**Issue by ttemp0825** [jupyterlab/jupyterlab#11118]
Description:  ipykernel status changes from busy to idle after few seconds during while loop execution. This is happening since i have updated the Jupyter/Anaconda few days back. My previous Python 3 kernel got replaced with ipykernel and the issue started.

steps:
1. Create a while loop.
2. run the code.
3. observe that ipykernel shows busy and Black dot is shown.
4. after few seconds, the while loop keeps on running properly but the black dot turns into white dot and ipykernel says 'idle'.

Code runs properly but the UI confuses the user.

**Comment by trungleduc** [comment]
Possible duplicated with https://github.com/jupyterlab/jupyterlab/issues/10701
