### ISSUE TITLE
renaming and a notebook (a.ipynb -> b.ipynb) and creating a new one (a.ipynb) lets edits appear in both 

### ISSUE THREAD

**Issue by pfarndt** [jupyterlab/jupyterlab#11116]
## Description

Edits in one notebook show up in another as well.

## Reproduce

1. Create a new (empty) subfolder and change into it
2. Create a new notebook - it will be named "Untitled.ipynb"
3. Create some cells and save it - keep it open - rename it in the file browser to e.g. "t1.ipynb"
4. Create yet another new (empty) notebook - it will be again named "Untitled.ipynb".
5. Create some cell in it - these cells will now also show up in "t1.ipynb", i.e. in two notebooks at the same time.

This is for sure not expected and I lost some large chunks of work stumbling into this issue. This stops as soon as I rename "Untitled.ipynb" to something else.

- Operating System and version: Linux
- Browser and version: Safari (from remote) 
- JupyterLab version: 3.1.12

**Comment by pfarndt** [comment]
Some more factss:
- this bug is persistent in JupyterLab 3.1.14. 
- it also happens if the notebook is mv'ed on the command line.
- it happens also for other filenames - not just 'Untitled.ipynb'
- it happens also if the kernel of the nb is shut down

I find this bug very disturbing, because it messes with notebooks which I do not edit at the moment but had the same name earlier. Lowers my confidence enormously.

**Comment by jasongrout** [comment]
I could not reproduce this just launching JupyterLab with `jupyter lab`. However, I was able to reproduce all sorts of problems around renaming files when launching with the experimental `jupyter lab --collaborative` flag. Please note that the collaborative features are still experimental, and not recommended for production. (Side note: I notice that the `--collaborative` command line option does not note that it is experimental, but probably should).

@dmonad - Can you take a look at this? Here is a screencast of some of the issues happening for me. If I had to guess, it seems that a rename in the file browser is not propagating to open files to change the collaboration models for those open notebook widgets.

![renamingproblems](https://user-images.githubusercontent.com/192614/135658647-8b5a8b10-c3b3-4e61-8233-84949c0bce85.gif)

**Comment by jasongrout** [comment]
@pfarndt - can you confirm my findings above, i.e., that you see the problems only with the `--collaborative` flag, but running without the `--collaborative` flag is fine?

**Comment by krassowski** [comment]
There was an issue in similar vein earlier on master https://github.com/jupyterlab/jupyterlab/issues/10436 before the rename dialog was postponed. It might have a common cause.

**Comment by pfarndt** [comment]
ok - I get the same (less severe - but equally disturbing) behavior as shown in the screen cast only with `--collaborative` flag. 

However with the `jupyterlab jupyterlab-git` extension (and  `--collaborative`) my above reported issue can probably fully be recovered - see a screenshot below (I use a julia kernel):

<img width="1056" alt="Screen Shot 2021-10-01 at 5 24 51 PM" src="https://user-images.githubusercontent.com/11805999/135688397-41f9f848-29bd-4cfa-a058-38c76c18c4d8.png">

**Comment by SylvainCorlay** [comment]
cc @hbcarlos @dmonad

**Comment by dmonad** [comment]
I can reproduce this issue easily. Thanks @pfarndt!

This is because the cross-window communication feature of Yjs. While we handle renaming of files on the server, the y-websocket provider is not aware that the file was renamed. 

I'm going to work on this. We either have to disable cross-window communication or re-initialize the y-websocket provider properly.
