### ISSUE TITLE
how to set the default end of line character in jupyterlab

### ISSUE THREAD

**Issue by HGladiator** [jupyterlab/jupyterlab#11122]
## Description
I am seeing the error message in my JupyterLab.:

"Code Editor out of Sync. 
Please open your browser JavaScript console for bug report instructions" 

[the answer in stackoverflow](https://stackoverflow.com/questions/65673839/how-can-i-fix-a-jupyterlab-code-editor-out-of-sync-error-message)

replace all `\r\n` with `\n` to fix this error .
but the default end of line character is `CRLF` on windows

I didn't find any way to modify the default in jupyterlab.

## Reproduce

replace the default end of line character with `CRLF`  will reproduce this error

**Comment by jasongrout** [comment]
There is a long conversation about this issue over at #9465, let's please consolidate the conversation over there.

Over there, we are exploring normalizing the code cell line endings to `\n` as a convention in Jupyter.
