### ISSUE TITLE
"Server unavailable or unreachable" frequent pop up but server is reachable

### ISSUE THREAD

**Issue by lgonzalezsa** [jupyterlab/jupyterlab#11134]
## Description

Since JupyterLab 3.0.15 was seeing the popup message below quite often. I did always have in parallel vscode with remote-ssh and a ssh terminal against the server and the connection looks fine. Seems to me is not a network glitch or VPN problem because I can establish HTTPS and SSH steady connections.
Today we ran conda update --all and **JupyterHub is 1.4.2** and **JupyterLab is 3.1.13**
Expectation was to the message to disappear but was not the case.
_Issue is not happening in the Jupyter Classic notebook interface._

Server unavailable or unreachable
Your server at /user/gonluisr/ is not running. Would you like to restart it?
![image](https://user-images.githubusercontent.com/704686/134579471-5b241467-390f-407d-99d6-f7997f3317b0.png)

## Reproduce

1. Connect to JupyterLab
2. Working on a notebook the popup appears multiple times during 15 minutes period

## Expected behavior

Don't get the popup if my connection is stable and server is avaiable.

## Context

- Operating System and version:  openSUSE Leap 15.3
- Browser and version:  Chrome 93.0
- JupyterLab version:  3.1.13

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
Would you be able to downgrade JupyterLab step-by-step to narrow down which version introduced this issue?

**Comment by lgonzalezsa** [comment]
Doing more troubleshooting seems it is a network issue from my side. I am connected also from a another client but in the same network of JupyterHub and more than 5 hours without any issues in JupyerLab interface. 

Interestingly, also running the classic notebook interface in another tab in my laptop and never complaint about network issues.

Seems the JupyterLab interface could be sensitive or requires a more solid network connection? 

Is there a setting I could adjust to minimize the frequency this popup message appears?

**Comment by lgonzalezsa** [comment]
Now confirmed, McAfee firewall causing JupyterLab popup. 
Agreed with @icankeep, in any of the times when the popup appears I need to click on restart button, at least in my case was just to dismiss and continue working.

**Comment by raybellwaves** [comment]
Just want to add i'm also seeing this. I'm connected to an instance in a VPC so could be related. I may open an issue in the future

**Comment by raybellwaves** [comment]
> Just want to add i'm also seeing this. I'm connected to an instance in a VPC so could be related. I may open an issue in the future

Ignore me. I think I was seeing https://tljh.jupyter.org/en/latest/topic/idle-culler.html#default-settings
