### ISSUE TITLE
Making lab extensions discoverable on pypi

### ISSUE THREAD

**Issue by ClaytonPassmore** [jupyterlab/jupyterlab#1113]
I have talked offline with @jasongrout about this and he suggested I post here so we could get some opinions.

Currently, it's really hard for users to discover new extensions on pypi. To make it easier, something should probably be added to the extension cookie cutter. The end goal would be to have an extension manager of some kind that could search pypi for extensions.

Originally I was thinking that we could modify the setup args in `setup.py` to include the `platforms` attribute which would contain 'JupyterLab'. Then we could search against that attribute with [pypi's XML RPC search method](https://wiki.python.org/moin/PyPIXmlRpc).

@jasongrout mentioned we should at least add a 'JupyterLab' keyword.

What's the best way to do this?

**Comment by blink1073** [comment]
I think having `jupyterlab` and `extension` keywords as part of the the cookiecutter `setup.py` and the documentation for creating a JupyterLab plugin would be a sound solution.

**Comment by jasongrout** [comment]
+1 to using the keywords field. I think the platform field *could* be used, but I think it's also misusing the purpose of the platform field a bit.

@ClaytonPassmore, do you want to open PRs to the cookie cutter and the documentation?

**Comment by ClaytonPassmore** [comment]
@jasongrout can we close this?
