### ISSUE TITLE
Language packs break JupyterLab on Python 3.7 completely

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#11148]
## Description

I just noticed while trying to test localization of an extension that language packs are broken with JupyterLab 3.1.13 and 3.1.12 (and possibly older too as the issue comes from `jupyterlab_server`/`gettext`) on binder, and they completely break JupyterLab UI once activated (by crashing server).

## Reproduce

1. Install a language pack on binder or use a repro gist: https://gist.github.com/krassowski/b1737a6d77d29ea08dd7d73f39d159c1
2. Change language from Menu Settings → Language
2. See the page does not reload
3. See the error in console:

```python
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/tornado/web.py", line 3173, in wrapper
    return method(self, *args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab_server/settings_handler.py", line 54, in get
    translator=translator.translate_schema
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab_server/settings_utils.py", line 342, in get_settings
    schema = translator(schema)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab_server/translation_utils.py", line 737, in translate_schema
    translator._translate_schema_strings(translations, schema.copy())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab_server/translation_utils.py", line 696, in _translate_schema_strings
    schema[key] = translations.pgettext(context, value)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab_server/translation_utils.py", line 490, in pgettext
    return gettext.dpgettext(self._domain, msgctxt, msgid)
AttributeError: module 'gettext' has no attribute 'dpgettext'
```

5. Reload manually
6. See JupyterLab not loading due to server errors

![crash](https://user-images.githubusercontent.com/5832902/134774143-e0a2d0ff-bf0e-48a5-9ede-276d6497439e.gif)

## Expected behavior

Language packs work, UI server does not crash

## Context

- Operating System and version: Linux Ubuntu 21.04
- Browser and version: Chrome 92
- JupyterLab version: 3.1.13

**Comment by krassowski** [comment]
It seems that this Binder is currently picking Python 3.7.10. The context translations functions are not available in Python 3.8. I think that we did not use context translations prior to `jupyterlab_server` 2.8.0 (released 18 days ago) which included translation of settings schema (https://github.com/jupyterlab/jupyterlab_server/pull/205 by @fcollonval).

It looks like other projects were bitten by this too: https://github.com/napari/napari/issues/2299 and @goanpeca has had prepared a workaround there: https://github.com/napari/napari/pull/2305. Should we just fallback to non-context alternatives too?

**Comment by krassowski** [comment]
Also, I think that we should add integration testing across `jupyterlab-language-packs`, `jupytelab-server` and `jupyterlab` so that it does not happen again.

**Comment by goanpeca** [comment]
>It looks like other projects were bitten by this too: napari/napari#2299 and @goanpeca has had prepared a workaround there: napari/napari#2305. Should we just fallback to non-context alternatives too?

Sure, we can do that, will open a PR!

**Comment by krassowski** [comment]
Already opened one: https://github.com/jupyterlab/jupyterlab_server/pull/213
