### ISSUE TITLE
The type of a non-editable cell can be changed

### ISSUE THREAD

**Issue by raffaele-cappelli** [jupyterlab/jupyterlab#11165]
## Description

The type of cells with "editable": false can be changed (e.g. from Code to Markdown or Raw).

## Reproduce

In a new notebook, edit metadata adding  

    "editable": false

the cell cannot be edited, but it is possible to change its type from the toolbar.

## Expected behavior

It should not be possible to change the type, as in jupyter notebook.

## Context

Reproduced in a clean env (conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c nodefaults jupyterlab)

JupyterLab Version 3.1.13
Google Chrome | 93.0.4577.82
Windows 10 OS Version 2009
JavaScript | V8 9.3.345.19

I was NOT able to reproduce the problem in Jupyter notebook.

**Comment by trevorcampbell** [comment]
I will bump this issue and add one more additional concern: the cell toolbar also ignores metadata.

If I have a cell that is false for both editable and deletable, the "trash can" button in the cell toolbar will still delete the cell.

**Comment by firai** [comment]
> I will bump this issue and add one more additional concern: the cell toolbar (that comes up when you hover over a cell) also ignores metadata.
> 
> If I have a cell that is false for both editable and deletable, the "trash can" button in the cell toolbar will still delete the cell.

Which version are you running? I just tested the built-in cell toolbars in both 3.4.8 and the latest master, and neither toolbars will delete the cell when `deletable` is `false`. Are you referring to the `enhanced-cell-toolbar` extension (which I don't have installed and which is in a different repo) by any chance? If you can reproduce it with the built-in cell toolbar in the latest version, this might need to be filed as a separate issue?

**Comment by nthiery** [comment]
Let me bump this ticket. Our beginning students frequently change cell types by accident, e.g. by inadvertently typing keyboard shortcuts. And then they don't understand why the examples that we provide them with in locked cells are broken. When this happens outside of the classroom, it is a pain to debug remotely their "your example does not work" calls for help.

As an alternative, one could imagine having a separate flag called, say, `can_change_type`. Which would be useful by itself for answer cells that students are supposed to edit, but without changing their type.

cc @brichet

**Comment by krassowski** [comment]
Of note a guard of similar nature (but for pending input) was added in https://github.com/jupyterlab/jupyterlab/pull/16032. To solve this issue, one would need to add a check for read-only status, similar to the check for pending input in:

https://github.com/jupyterlab/jupyterlab/blob/c0050f23686088318b6800e4591d9dad6dc89e0d/packages/notebook/src/actions.tsx#L2731-L2746

One could also add a test, building upon the test case in:

https://github.com/jupyterlab/jupyterlab/blob/c0050f23686088318b6800e4591d9dad6dc89e0d/packages/notebook/test/actions.spec.ts#L669-L700
