### ISSUE TITLE
Add "system" color theme

### ISSUE THREAD

**Issue by Yura52** [jupyterlab/jupyterlab#11167]
When I switch my OS to dark/light mode, I have to manually change all JupyterLab windows to change their themes to match the system theme. Is it possible to automate this by introducing the "system" theme?

**Comment by krassowski** [comment]
I think that it would be reasonable to have such an option in the Theme menu.

I think that it should detect [@media/prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme); some examples are given on [SO](https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript).

**Comment by krassowski** [comment]
I just noticed that we already have an issue on this one: #8777. I will close this one and move my comment over there. Please feel free to give a thump op on the other issue.

PS. There is also https://github.com/jtpio/jupyterlab-theme-toggle
