### ISSUE TITLE
Continuous retry of `GET /api/contents` on 404

### ISSUE THREAD

**Issue by minrk** [jupyterlab/jupyterlab#11207]
## Description

When listing files returns a 404, jupyterlab continuously and rapidly retries the request, flooding the server with the same failing request, apparently as fast as it can.

## Reproduce

1. `mkdir /tmp/notebooks`
2. `jupyter lab /tmp/notebooks`
3. `rmdir /tmp/notebooks`
4. visit jupyterlab main page
5. See flood of the same request, failing with 404:

```
[W 2021-10-05 11:23:24.189 ServerApp] No such file or directory:
[W 2021-10-05 11:23:24.189 ServerApp] 404 GET /api/contents?content=1&1633425804186 (::1) 1.04ms referer=http://localhost:8888/lab
[W 2021-10-05 11:23:24.193 ServerApp] No such file or directory:
[W 2021-10-05 11:23:24.194 ServerApp] 404 GET /api/contents?content=1&1633425804190 (::1) 1.71ms referer=http://localhost:8888/lab
[W 2021-10-05 11:23:24.199 ServerApp] No such file or directory:
[W 2021-10-05 11:23:24.200 ServerApp] 404 GET /api/contents?content=1&1633425804196 (::1) 1.52ms referer=http://localhost:8888/lab
[W 2021-10-05 11:23:24.203 ServerApp] No such file or directory:
[W 2021-10-05 11:23:24.203 ServerApp] 404 GET /api/contents?content=1&1633425804201 (::1) 1.09ms referer=http://localhost:8888/lab
```

## Expected behavior

Fail at most once until explicit user-initiated requests for locations that don't exist. Or at least exponential back-off and eventual giving up if retry is still desirable.

## Context

- Operating System and version: macOS 11.6
- Browser and version: Safari 15.0
- JupyterLab version: 3.1.12

Removing the root directory isn't what I really care about, since that's not realistic, but it's the easiest way to reproduce the issue without pulling in a PR to JupyterHub. I came across this while testing https://github.com/jupyterlab/jupyterlab/pull/11205 and https://github.com/jupyterhub/jupyterhub/pull/3636 where we are considering a change to the error code returned when a request for a not-running server is routed to the Hub. The same situation actually occurs today on mybinder.org, which returns a 404 for requests to a server that's been shutdown, and I believe is the primary reason that Hub is currently serving over 70% 404s:

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/151929/135998309-1e448476-eddd-45ad-866c-0d7ab17e1c3e.png">

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
[Warning] 3140 console messages are not shown.
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
[Warning] Showing error: – Error: Directory not found: "" (jlab_core.1ad82bcd8c48e07a8392.js, line 2)
Error: Directory not found: ""
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (contents, line 0)
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
[Warning] Showing error: – Error: Directory not found: "" (jlab_core.1ad82bcd8c48e07a8392.js, line 2)
Error: Directory not found: ""
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (contents, line 0)
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
[Warning] Showing error: – Error: Directory not found: "" (jlab_core.1ad82bcd8c48e07a8392.js, line 2)
Error: Directory not found: ""
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (contents, line 0)
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
[Warning] Showing error: – Error: Directory not found: "" (jlab_core.1ad82bcd8c48e07a8392.js, line 2)
Error: Directory not found: ""
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (contents, line 0)
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
[Warning] Showing error: – Error: Directory not found: "" (jlab_core.1ad82bcd8c48e07a8392.js, line 2)
Error: Directory not found: ""
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (contents, line 0)
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
[Warning] Showing error: – Error: Directory not found: "" (jlab_core.1ad82bcd8c48e07a8392.js, line 2)
Error: Directory not found: ""
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (contents, line 0)
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
[Warning] Showing error: – Error: Directory not found: "" (jlab_core.1ad82bcd8c48e07a8392.js, line 2)
Error: Directory not found: ""
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (contents, line 0)
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
[Warning] Showing error: – Error: Directory not found: "" (jlab_core.1ad82bcd8c48e07a8392.js, line 2)
Error: Directory not found: ""
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (contents, line 0)
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
[Warning] Showing error: – Error: Directory not found: "" (jlab_core.1ad82bcd8c48e07a8392.js, line 2)
Error: Directory not found: ""
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (contents, line 0)
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
[Warning] Showing error: – Error: Directory not found: "" (jlab_core.1ad82bcd8c48e07a8392.js, line 2)
Error: Directory not found: ""
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (contents, line 0)
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
[Warning] Showing error: – Error: Directory not found: "" (jlab_core.1ad82bcd8c48e07a8392.js, line 2)
Error: Directory not found: ""
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (contents, line 0)
[Error] Error: Directory not found: ""
	(anonymous function) (jlab_core.1ad82bcd8c48e07a8392.js:2:581672)
	promiseReactionJob
</pre>
</details>

**Comment by blink1073** [comment]
It looks like we are using a poll with [backoff](https://github.com/jupyterlab/jupyterlab/blob/6e655233fd745cfd9087f3b177fd57f0e27bc9b3/packages/filebrowser/src/model.ts#L97), but the backoff is being short-circuited when we get a 404 [here](https://github.com/jupyterlab/jupyterlab/blob/6e655233fd745cfd9087f3b177fd57f0e27bc9b3/packages/filebrowser/src/model.ts#L307).

**Comment by minrk** [comment]
@blink1073 good catch. Looks like at least that short-circuit path shouldn't take effect when the path is *already* `/`.
