### ISSUE TITLE
Unable to open folder in file browser as long as it is named "checkpoints"

### ISSUE THREAD

**Issue by simonrouse9461** [jupyterlab/jupyterlab#11200]
## Description

File browser doesn't like the name "checkpoints". If a folder is named "checkpoints", it will run into trouble. You can't neither open it, nor rename/delete it.

## Reproduce

1. Create a folder and name it "checkpoints"
2. Try to do anything with it (double click, right click then rename/delete)
3. It will fail

## Expected behavior

It should behave just like any other folders

## Context

- Operating System and version: Both Linux and MacOS
- Browser and version: Both Chrome and Safari
- JupyterLab version: 3.0.17

**Comment by Mithil467** [comment]
Can confirm this issue still exists.
Found a similar issue and quoting https://github.com/jupyterlab/jupyterlab/issues/9913#issuecomment-793760113 -

> This is a problem with the underlying server API, and needs to be fixed there. It is documented at jupyter-server/jupyter_server#58 and jupyter/notebook#5569. It would need to be fixed in Jupyter Server.
> 
> Let's move the conversation about a fix over to jupyter-server/jupyter_server#58. In the meantime, it seems like the best workaround is to rename your directory.

**Comment by jasongrout** [comment]
Thank you for quoting that issue, @Mithil467. Yes, it still is an issue with the Jupyter Server, as explained on those issues, and should be discussed and solved there.
