### ISSUE TITLE
Webpack Hashing Problems

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#11248]
## Description
We have seen a bug in [CI](https://github.com/jupyterlab/jupyterlab/runs/3808333301?check_suite_focus=true#step:10:3450) related to hashing and Webpack that affects the ability to build JupyterLab and source extensions. 

The underlying issue is that for versions of OpenSSL built with [FIPS compliance](https://docs.oracle.com/cd/E36784_01/html/E54953/fips-notok-1.html), the default hashing algorithm used by Webpack and loaders is not available (`md4`).

We started seeing failures recently because the latest version of `openssl` on `conda-forge` was built with [FIPS compliance](https://github.com/conda-forge/openssl-feedstock/pull/72/files#diff-d7075654874cb08007a21aaab3ecd4b3453a9087e7505d034d548b8938b599bcR7).

The solution suggested by the [Webpack developers](https://github.com/webpack/webpack/issues/13572#issuecomment-923742724) is to use `output.hashFunction`.  However, this setting is not respected by [loaders](https://github.com/webpack/loader-utils/blob/d9f4e23cf411d8556f8bac2d3bf05a6e0103b568/lib/getHashDigest.js#L43), causing the build to fail for loaders even with the setting.  Loaders are also deprecated in favor of [asset modules](https://webpack.js.org/guides/asset-modules/).

For now we need to use the hard [workaround](https://github.com/webpack/webpack/issues/13572#issuecomment-923736472) over overriding the built-in `crypto.hashFunction` to prevent the usage of `md4`.  This fix will have to be applied to all of our usages of `webpack` config files, including the one in [`notebook`](https://github.com/jupyter/notebook/blob/76d051eb5ed031f33664c0d1bd1f946bf6cd6542/webpack.config.js).

Longer term, we should migrate away from using loaders in favor of `asset modules`.  It would take some work to handle the loaders configured in our [base config](https://github.com/jupyterlab/jupyterlab/blob/master/builder/src/webpack.config.base.ts), especially the third-party [`svg-url-loader`](https://github.com/bhovhannes/svg-url-loader).

A workaround for `conda` users in general when facing this bug is to install an older version of `openssl`:  `conda install -c conda-forge "openssl<3"`

## Reproduce

1. Create and activate new conda environment
2. Install nodejs: `conda install nodejs=16`
2. Install JupyterLab: `pip install jupyterlab==3.1.17`
3. Build JupyterLab: `jupyter lab build --debug`

Note the output:

```
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/webpack/lib/util/createHash.js:80:21)
    at /private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/webpack/lib/DefinePlugin.js:595:38
    at _next31 (eval at create (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:42:1)
    at _next9 (eval at create (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:119:1)
    at Hook.CALL_DELEGATE [as _call] (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/webpack/lib/Compiler.js:1053:26) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Command failed with exit code 2.
```

## Expected behavior
Successful build

## Context

- Operating System and version: macOS 11.6
- Browser and version: N/A
- JupyterLab version: 3.1.17

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/tmp/conda_envs/4b408eff2eae179edb316cfd/bin
	/Users/silvester/miniconda/condabin
	/Users/silvester/.yvm/shim
	/Users/silvester/.nvm/versions/node/v12.16.0/bin
	/Users/silvester/bin
	/opt/brew/bin
	/opt/brew/sbin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/opt/brew/bin

sys.path:
	/private/tmp/conda_envs/4b408eff2eae179edb316cfd/bin
	/tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python38.zip
	/tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8
	/tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8/lib-dynload
	/tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8/site-packages

sys.executable:
	/tmp/conda_envs/4b408eff2eae179edb316cfd/bin/python

sys.version:
	3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:42:05) 
	[Clang 11.1.0 ]

platform.platform():
	macOS-10.16-x86_64-i386-64bit

which -a jupyter:
	/tmp/conda_envs/4b408eff2eae179edb316cfd/bin/jupyter

pip list:
	Package                       Version
	----------------------------- ---------
	anyio                         3.3.2
	appnope                       0.1.2
	argon2-cffi                   21.1.0
	attrs                         21.2.0
	Babel                         2.9.1
	backcall                      0.2.0
	backports.functools-lru-cache 1.6.4
	bleach                        4.1.0
	certifi                       2021.5.30
	cffi                          1.14.6
	charset-normalizer            2.0.6
	debugpy                       1.4.1
	decorator                     5.1.0
	defusedxml                    0.7.1
	entrypoints                   0.3
	idna                          3.2
	ipdb                          0.13.9
	ipykernel                     6.4.1
	ipython                       7.28.0
	ipython-genutils              0.2.0
	jedi                          0.18.0
	Jinja2                        3.0.2
	json5                         0.9.6
	jsonschema                    4.0.1
	jupyter-client                7.0.6
	jupyter-core                  4.8.1
	jupyter-server                1.11.1
	jupyterlab                    3.1.17
	jupyterlab-pygments           0.1.2
	jupyterlab-server             2.8.2
	MarkupSafe                    2.0.1
	matplotlib-inline             0.1.3
	mistune                       0.8.4
	nbclassic                     0.3.2
	nbclient                      0.5.4
	nbconvert                     6.2.0
	nbformat                      5.1.3
	nest-asyncio                  1.5.1
	notebook                      6.4.4
	packaging                     21.0
	pandocfilters                 1.5.0
	parso                         0.8.2
	pexpect                       4.8.0
	pickleshare                   0.7.5
	pip                           21.2.4
	prometheus-client             0.11.0
	prompt-toolkit                3.0.20
	ptyprocess                    0.7.0
	pycparser                     2.20
	Pygments                      2.10.0
	pyparsing                     2.4.7
	pyrsistent                    0.18.0
	python-dateutil               2.8.2
	pytz                          2021.3
	pyzmq                         22.3.0
	requests                      2.26.0
	requests-unixsocket           0.2.0
	Send2Trash                    1.8.0
	setuptools                    58.2.0
	six                           1.16.0
	sniffio                       1.2.0
	terminado                     0.12.1
	testpath                      0.5.0
	tornado                       6.1
	traitlets                     5.1.0
	urllib3                       1.26.7
	wcwidth                       0.2.5
	webencodings                  0.5.1
	websocket-client              1.2.1
	wheel                         0.37.0

conda list:
	# packages in environment at /tmp/conda_envs/4b408eff2eae179edb316cfd:
	#
	# Name                    Version                   Build  Channel
	anyio                     3.3.2                    pypi_0    pypi
	appnope                   0.1.2            py38h50d1736_1    conda-forge
	argon2-cffi               21.1.0                   pypi_0    pypi
	attrs                     21.2.0                   pypi_0    pypi
	babel                     2.9.1                    pypi_0    pypi
	backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
	backports                 1.0                        py_2    conda-forge
	backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
	bleach                    4.1.0                    pypi_0    pypi
	ca-certificates           2021.5.30            h033912b_0    conda-forge
	certifi                   2021.5.30                pypi_0    pypi
	cffi                      1.14.6                   pypi_0    pypi
	charset-normalizer        2.0.6                    pypi_0    pypi
	debugpy                   1.4.1            py38ha048514_0    conda-forge
	decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
	defusedxml                0.7.1                    pypi_0    pypi
	entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
	icu                       68.1                 h74dc148_0    conda-forge
	idna                      3.2                      pypi_0    pypi
	ipdb                      0.13.9             pyhd8ed1ab_0    conda-forge
	ipykernel                 6.4.1            py38h5fd9f69_0    conda-forge
	ipython                   7.28.0           py38h5fd9f69_0    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	jedi                      0.18.0           py38h50d1736_2    conda-forge
	jinja2                    3.0.2                    pypi_0    pypi
	json5                     0.9.6                    pypi_0    pypi
	jsonschema                4.0.1                    pypi_0    pypi
	jupyter-server            1.11.1                   pypi_0    pypi
	jupyter_client            7.0.6              pyhd8ed1ab_0    conda-forge
	jupyter_core              4.8.1            py38h50d1736_0    conda-forge
	jupyterlab                3.1.17                   pypi_0    pypi
	jupyterlab-pygments       0.1.2                    pypi_0    pypi
	jupyterlab-server         2.8.2                    pypi_0    pypi
	libcxx                    12.0.1               habf9029_0    conda-forge
	libffi                    3.4.2                he49afe7_4    conda-forge
	libsodium                 1.0.18               hbcb3906_1    conda-forge
	libuv                     1.42.0               h0d85af4_0    conda-forge
	libzlib                   1.2.11            h9173be1_1013    conda-forge
	markupsafe                2.0.1                    pypi_0    pypi
	matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
	mistune                   0.8.4                    pypi_0    pypi
	nbclassic                 0.3.2                    pypi_0    pypi
	nbclient                  0.5.4                    pypi_0    pypi
	nbconvert                 6.2.0                    pypi_0    pypi
	nbformat                  5.1.3                    pypi_0    pypi
	ncurses                   6.2                  h2e338ed_4    conda-forge
	nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
	nodejs                    16.10.0              h3fbb2f5_1    conda-forge
	notebook                  6.4.4                    pypi_0    pypi
	openssl                   3.0.0                h0d85af4_1    conda-forge
	packaging                 21.0                     pypi_0    pypi
	pandocfilters             1.5.0                    pypi_0    pypi
	parso                     0.8.2              pyhd8ed1ab_0    conda-forge
	pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
	pickleshare               0.7.5                   py_1003    conda-forge
	pip                       21.2.4             pyhd8ed1ab_0    conda-forge
	prometheus-client         0.11.0                   pypi_0    pypi
	prompt-toolkit            3.0.20             pyha770c72_0    conda-forge
	ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
	pycparser                 2.20                     pypi_0    pypi
	pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
	pyparsing                 2.4.7                    pypi_0    pypi
	pyrsistent                0.18.0                   pypi_0    pypi
	python                    3.8.12          h43ca1e7_1_cpython    conda-forge
	python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
	python_abi                3.8                      2_cp38    conda-forge
	pytz                      2021.3                   pypi_0    pypi
	pyzmq                     22.3.0           py38hd3b92b6_0    conda-forge
	readline                  8.1                  h05e3726_0    conda-forge
	requests                  2.26.0                   pypi_0    pypi
	requests-unixsocket       0.2.0                    pypi_0    pypi
	send2trash                1.8.0                    pypi_0    pypi
	setuptools                58.2.0           py38h50d1736_0    conda-forge
	six                       1.16.0             pyh6c4a22f_0    conda-forge
	sniffio                   1.2.0                    pypi_0    pypi
	sqlite                    3.36.0               h23a322b_2    conda-forge
	terminado                 0.12.1                   pypi_0    pypi
	testpath                  0.5.0                    pypi_0    pypi
	tk                        8.6.11               h5dbffcc_1    conda-forge
	tornado                   6.1              py38h96a0964_1    conda-forge
	traitlets                 5.1.0              pyhd8ed1ab_0    conda-forge
	urllib3                   1.26.7                   pypi_0    pypi
	wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
	webencodings              0.5.1                    pypi_0    pypi
	websocket-client          1.2.1                    pypi_0    pypi
	wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
	xz                        5.2.5                haf1e3a3_1    conda-forge
	zeromq                    4.3.4                he49afe7_1    conda-forge
	zlib                      1.2.11            h9173be1_1013    conda-forge

conda env:
	name: /tmp/conda_envs/4b408eff2eae179edb316cfd
	channels:
	  - conda-forge
	  - defaults
	dependencies:
	  - appnope=0.1.2=py38h50d1736_1
	  - backcall=0.2.0=pyh9f0ad1d_0
	  - backports=1.0=py_2
	  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
	  - ca-certificates=2021.5.30=h033912b_0
	  - debugpy=1.4.1=py38ha048514_0
	  - decorator=5.1.0=pyhd8ed1ab_0
	  - entrypoints=0.3=pyhd8ed1ab_1003
	  - icu=68.1=h74dc148_0
	  - ipdb=0.13.9=pyhd8ed1ab_0
	  - ipykernel=6.4.1=py38h5fd9f69_0
	  - ipython=7.28.0=py38h5fd9f69_0
	  - ipython_genutils=0.2.0=py_1
	  - jedi=0.18.0=py38h50d1736_2
	  - jupyter_client=7.0.6=pyhd8ed1ab_0
	  - jupyter_core=4.8.1=py38h50d1736_0
	  - libcxx=12.0.1=habf9029_0
	  - libffi=3.4.2=he49afe7_4
	  - libsodium=1.0.18=hbcb3906_1
	  - libuv=1.42.0=h0d85af4_0
	  - libzlib=1.2.11=h9173be1_1013
	  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
	  - ncurses=6.2=h2e338ed_4
	  - nest-asyncio=1.5.1=pyhd8ed1ab_0
	  - nodejs=16.10.0=h3fbb2f5_1
	  - openssl=3.0.0=h0d85af4_1
	  - parso=0.8.2=pyhd8ed1ab_0
	  - pexpect=4.8.0=pyh9f0ad1d_2
	  - pickleshare=0.7.5=py_1003
	  - pip=21.2.4=pyhd8ed1ab_0
	  - prompt-toolkit=3.0.20=pyha770c72_0
	  - ptyprocess=0.7.0=pyhd3deb0d_0
	  - pygments=2.10.0=pyhd8ed1ab_0
	  - python=3.8.12=h43ca1e7_1_cpython
	  - python-dateutil=2.8.2=pyhd8ed1ab_0
	  - python_abi=3.8=2_cp38
	  - pyzmq=22.3.0=py38hd3b92b6_0
	  - readline=8.1=h05e3726_0
	  - setuptools=58.2.0=py38h50d1736_0
	  - six=1.16.0=pyh6c4a22f_0
	  - sqlite=3.36.0=h23a322b_2
	  - tk=8.6.11=h5dbffcc_1
	  - tornado=6.1=py38h96a0964_1
	  - traitlets=5.1.0=pyhd8ed1ab_0
	  - wcwidth=0.2.5=pyh9f0ad1d_2
	  - wheel=0.37.0=pyhd8ed1ab_1
	  - xz=5.2.5=haf1e3a3_1
	  - zeromq=4.3.4=he49afe7_1
	  - zlib=1.2.11=h9173be1_1013
	  - pip:
	    - anyio==3.3.2
	    - argon2-cffi==21.1.0
	    - attrs==21.2.0
	    - babel==2.9.1
	    - bleach==4.1.0
	    - certifi==2021.5.30
	    - cffi==1.14.6
	    - charset-normalizer==2.0.6
	    - defusedxml==0.7.1
	    - idna==3.2
	    - jinja2==3.0.2
	    - json5==0.9.6
	    - jsonschema==4.0.1
	    - jupyter-server==1.11.1
	    - jupyterlab==3.1.17
	    - jupyterlab-pygments==0.1.2
	    - jupyterlab-server==2.8.2
	    - markupsafe==2.0.1
	    - mistune==0.8.4
	    - nbclassic==0.3.2
	    - nbclient==0.5.4
	    - nbconvert==6.2.0
	    - nbformat==5.1.3
	    - notebook==6.4.4
	    - packaging==21.0
	    - pandocfilters==1.5.0
	    - prometheus-client==0.11.0
	    - pycparser==2.20
	    - pyparsing==2.4.7
	    - pyrsistent==0.18.0
	    - pytz==2021.3
	    - requests==2.26.0
	    - requests-unixsocket==0.2.0
	    - send2trash==1.8.0
	    - sniffio==1.2.0
	    - terminado==0.12.1
	    - testpath==0.5.0
	    - urllib3==1.26.7
	    - webencodings==0.5.1
	    - websocket-client==1.2.1
	prefix: /tmp/conda_envs/4b408eff2eae179edb316cfd
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
(/tmp/conda_envs/4b408eff2eae179edb316cfd) ➜  ~ jupyter lab build --debug
[LabBuildApp] Searching ['/Users/silvester', '/Users/silvester/.jupyter', '/tmp/conda_envs/4b408eff2eae179edb316cfd/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[LabBuildApp] Looking for jupyter_config in /etc/jupyter
[LabBuildApp] Looking for jupyter_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /tmp/conda_envs/4b408eff2eae179edb316cfd/etc/jupyter
[LabBuildApp] Looking for jupyter_config in /Users/silvester/.jupyter
[LabBuildApp] Looking for jupyter_config in /Users/silvester
[LabBuildApp] Looking for JupyterLab_config in /etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /usr/local/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /tmp/conda_envs/4b408eff2eae179edb316cfd/etc/jupyter
[LabBuildApp] Looking for JupyterLab_config in /Users/silvester/.jupyter
[LabBuildApp] Looking for JupyterLab_config in /Users/silvester
[LabBuildApp] JupyterLab 3.1.17
[LabBuildApp] Building in /private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab
[LabBuildApp] Node v16.10.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node /tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
|[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.15.0" has unmet peer dependency "@types/react@^16.3.0 || ^17.0.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.10.0" has unmet peer dependency "crypto@1.0.1".
warning "@jupyterlab/builder > @jupyterlab/buildutils > verdaccio > clipanion@3.0.1" has unmet peer dependency "typanion@*".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
Done in 13.68s.

[LabBuildApp] > node /tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
-[LabBuildApp] yarn run v1.21.1
$ /private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] > node /tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8/site-packages/jupyterlab/staging/yarn.js
\[LabBuildApp]
[LabBuildApp] > node /tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
/[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.digest (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/webpack/lib/util/createHash.js:80:21)
    at /private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/webpack/lib/DefinePlugin.js:595:38
    at _next31 (eval at create (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:42:1)
    at _next9 (eval at create (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:119:1)
    at Hook.CALL_DELEGATE [as _call] (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/private/tmp/conda_envs/4b408eff2eae179edb316cfd/share/jupyter/lab/staging/node_modules/webpack/lib/Compiler.js:1053:26) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 48, in debug_logging
    yield

[LabBuildApp]   File "/tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8/site-packages/jupyterlab/labapp.py", line 176, in start
    raise e

[LabBuildApp]   File "/tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8/site-packages/jupyterlab/labapp.py", line 172, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "/tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8/site-packages/jupyterlab/commands.py", line 482, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "/tmp/conda_envs/4b408eff2eae179edb316cfd/lib/python3.8/site-packages/jupyterlab/commands.py", line 697, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

An error occurred.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-wrv8z4cy.log
[LabBuildApp] Exiting application: JupyterLab
</pre>
</details>

<details><summary>Browser Output</summary>
N/A
</details>

**Comment by ErichBSchulz** [comment]
fyi 

still seeing this with JupyterLab version: 3.3 and Node.js v17.2.0

**Comment by ErichBSchulz** [comment]
running this before running build command seems to fix the issue:

    export NODE_OPTIONS=--openssl-legacy-provider
