### ISSUE TITLE
Can I disable image download?

### ISSUE THREAD

**Issue by kwon14** [jupyterlab/jupyterlab#11242]
Always appreciate your passionate work.

Currently, I am using Jupyterlab version 3.1.11.
I am controlling the file download method using the following.

    #jupyterlab download disable
    jupyter labextension disable @jupyterlab/filebrowser-extension:download
    jupyter labextension disable @jupyterlab/docmanager-extension:download

 However, if you right-click after clicking the image, the image is saved locally as "Save As".
 For security reasons, images should not be downloaded locally.

 If there is a way to prevent image storage, please share.

 Thank you always.

**Comment by krassowski** [comment]
Two extra points:
- we added "Copy cell output to clipboard" context menu action in #10282; having an option to disable that would be in scope, but this can already be done by modifying context menu via settings, so no action is required I believe
- as Jason mentions, JuptyterLab cannot control browser menu and any hack doing so can be circumvented by an advanced user (not only would it be inefficient and annoying, but also could pose an accessibility barrier); however it could be in scope of https://github.com/jupyterlab/jupyterlab_app which can actually control its context menu.

I understand why some regulators want to impose this change (e.g. data banks which control what users can take out of their content), and I am enthusiastic to help if this is the only way for allowing JupyterLab to be used in such scenarios. I also know that making programs too inconvenient with this regard ends by users taking a screenshot using their phone. Not saying that we cannot help in implementing strategies to make data which needs protection safer, but also trying to be realistic about how useful is making the system more airtight past some point.
