### ISSUE TITLE
jupyter lab command not recognized

### ISSUE THREAD

**Issue by juliohm** [jupyterlab/jupyterlab#1125]
I have installed jupyterlabs with pip following the instructions in the README:

```bash
pip install --user jupyterlab
jupyter serverextension enable --py jupyterlab
```

No error messages were displayed. However, when I try to start the lab, the command is not recognized:

```bash
jupyter lab
```
>jupyter: 'lab' is not a Jupyter command

Could you please guide me on how to fix this? I am looking forward to give JupyterLab a try.

**Comment by blink1073** [comment]
Hi @juliohm, it looks like you may need to alter your enable command to match your `pip install` command, please try `jupyter serverextension enable --user --py jupyterlab`

**Comment by juliohm** [comment]
@blink1073 I just tried and it didn't change the error.

**Comment by blink1073** [comment]
What is the output of `jupyter serverextension list`?

**Comment by juliohm** [comment]
>config dir: /home/juliohm/.jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab  OK

**Comment by juliohm** [comment]
There is definitely an issue with this instructions, I now have JupyterLab installed on my Arch Linux from the jupyterlab-git AUR package. It is looking awesome!

**Comment by blink1073** [comment]
@juliohm, what was the command that did the trick?  I agree these options are confusing, this [issue](https://github.com/jupyter/notebook/issues/1706) is tracking the problem.

**Comment by juliohm** [comment]
I uninstalled jupyter lab with pip (pip uninstall jupyterlab) and installed it using the Arch Linux package system:

```bash
yaourt -S jupyterlab-git
```

**Comment by blink1073** [comment]
Ah, okay.
