### ISSUE TITLE
Julia kernel not available

### ISSUE THREAD

**Issue by juliohm** [jupyterlab/jupyterlab#1129]
Hi,

I have just installed JupyterLab, but when I open it I can only see Python 3. How do I make the Julia kernel visible? I can choose the Julia kernel in Jupyter notebooks.

**Comment by blink1073** [comment]
Hi @juliohm, I just followed the latest instructions on https://github.com/JuliaLang/IJulia.jl and I am able to start a Julia notebook in JupyterLab.  I am using OSX 10.11.  Can you describe your setup?

<img width="717" alt="screen shot 2016-10-21 at 7 02 49 am" src="https://cloud.githubusercontent.com/assets/2096628/19597822/98d3964e-975c-11e6-9b81-4be2b1439bde.png">

**Comment by juliohm** [comment]
Hi @blink1073, I had sent you an email replying to your question, but apparently the big DNS attack in the last days putted GitHub down.

I can create a new notebook with the Julia kernel just fine, the problem is when I try to open an existing Julia notebook in JupyterLab, it is incorrectly recognized as Python 3 and I cannot change the kernel.

Also, code highlighting is still not happening for Julia, even though it is working in Jupyter notebooks.

**Comment by juliohm** [comment]
Hi Steven,

I tried to create a new notebook with the Julia kernel and it works, except
that there is no code highlight yet. I think there are issues tracking this
already.

The problem is when I try to open an existing Julia notebook, it is
incorrectly recognized as Python 3 and I cannot switch the kernel in
JupyterLab.

-Júlio

**Comment by blink1073** [comment]
Hi @juliohm, the highlighting is fixed in master and #1147 fixes the kernel selection problem.

**Comment by juliohm** [comment]
Amazing @blink1073 , I will get the latest from AUR and close the issue soon.
