### ISSUE TITLE
Widget not rendering on JupyterLab, when starting main.py examples/app and examples/notebook

### ISSUE THREAD

**Issue by erkin98** [jupyterlab/jupyterlab#11297]
## Description

Widget not rendering on JupyterLab examples

## Reproduce

1. Go to root folder after cloning https://github.com/jupyterlab/jupyterlab
2. Build examples folder after installing and building all node modules
3. Go to examples/app, run `python main,py` , open notebook type and run

```
import ipywidgets as widgets
widgets.Button(description="Hello")
```
![Screenshot from 2021-10-16 18-17-29](https://user-images.githubusercontent.com/20378722/137590952-4011bf38-b1a9-4ea6-9750-51f4344d141e.png)
4. See an error in console `Exception opening new comm`

## Expected behavior

![Screenshot from 2021-10-16 16-33-05](https://user-images.githubusercontent.com/20378722/137587638-9fa760bc-a436-4516-a0fb-13f85fa1daa8.png)
## Context

- Operating System and version: Linux Ubuntu 20.04 
- Browser and version: Chrome 94.0.4606.71 
- JupyterLab version: 3.1.18
- Nodejs version: 14.17.4

<details><summary>Troubleshoot Output</summary>
<pre>

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Access to font at 'about:blank' from origin 'http://localhost:8888' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
about:blank:1 Failed to load resource: net::ERR_FAILED
3 default.js:1027 Exception opening new comm
_handleCommOpen @ default.js:1027
</pre>
</details>

**Comment by krassowski** [comment]
Also see https://github.com/jupyterlab/jupyterlab/issues/15398#issuecomment-1810831962
