### ISSUE TITLE
Kernel selection is not respected

### ISSUE THREAD

**Issue by aggFTW** [jupyterlab/jupyterlab#1131]
When passing in the `Kernel.IModel` as `{ "name": "pysparkkernel" }` to `DocumentManager.open()`, I'm still getting back a `python2` kernel.

If I do `jupyter kernelspec list`, I get:
```
Available kernels:
  python2          /usr/local/lib/python2.7/dist-packages/ipykernel/resources
  pysparkkernel   /usr/local/lib/python2.7/dist-packages/sparkmagic/kernels/pysparkkernel
  sparkkernel      /usr/local/lib/python2.7/dist-packages/sparkmagic/kernels/sparkkernel
```

cc @blink1073 

Thanks!

**Comment by blink1073** [comment]
Hi @aggFTW, in this case it is up to the widget factory itself to start the kernel:

https://github.com/jupyterlab/jupyterlab/blob/74b07e7d7850acbee4adde4fe9e48e7c61c74763/src/docmanager/manager.ts#L123
https://github.com/jupyterlab/jupyterlab/blob/74b07e7d7850acbee4adde4fe9e48e7c61c74763/src/docmanager/widgetmanager.ts#L94

e.g.
https://github.com/jupyterlab/jupyterlab/blob/74b07e7d7850acbee4adde4fe9e48e7c61c74763/src/notebook/notebook/widgetfactory.ts#L71

If you are calling your own widget factory, then you need to add that logic to it.  If you are calling the notebook widget factory then there is another problem.

**Comment by aggFTW** [comment]
I am indeed using the `NotebookWidgetFactory`, and not my own. The code I have is here: https://github.com/aggFTW/jupyterlab/blob/ipywidgetsexample/examples/notebook/src/index.ts#L269

**Comment by aggFTW** [comment]
I believe I've finally found the source of this bug. I'm sorry I made you waste some time. Turns out one of the server extensions was changing the kernel to be used... No bug from jupyterlab as far as I've found.

Thanks!

**Comment by blink1073** [comment]
Glad you got sorted.
