### ISSUE TITLE
Export or move PanelWithToolbar from debugger to apputils or ui-components

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyterlab#11325]
I'm using the accordion panel in another package in Jupyterlab, and I would like to reuse the PanelWithToolbar from the debugger to create the widgets inserted in the AccordionPanel.

The problem is that this widget is not exported. Since it is generic and could be used everywhere, I would like to move it to `apputils` or `ui-components`. Another possibility is to move it upstream to lumino widgets.

### Additional context
I'm talking about moving out of the debugger these classes:
[PanelWithToolbar](https://github.com/jupyterlab/jupyterlab/blob/8c67f5949af19503e447a83584885f919e115c47/packages/debugger/src/panels/panelwithtoolbar.ts#L16)
[Renderer](https://github.com/jupyterlab/jupyterlab/blob/8c67f5949af19503e447a83584885f919e115c47/packages/debugger/src/panels/panelbody.ts#L11)

cc @trungleduc @jtpio

**Comment by fcollonval** [comment]
Closing as resolved by #11369
