### ISSUE TITLE
Could not install extension on windows due to missing "cat" command

### ISSUE THREAD

**Issue by stefaneidelloth** [jupyterlab/jupyterlab#11333]
## Description

I tried to install a custom extension with following command:

`jupyter labextension install .`

with JupyterLab 3.2.0, Nodejs v14.17.6, Windows 10

and JupyterLab fails to build. The referenced log file includes the hint

> @jupyterlab/application-top@3.2.0 build
> cat package.json && npm run clean && webpack

**Der Befehl "cat" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.**
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

=> How can I fix this?

Source of my extension:

https://github.com/stefaneidelloth/treezjs/tree/master/jupyter_lab_extension/jupyterlab_workspace_module

Related:

https://stackoverflow.com/questions/60244/is-there-replacement-for-cat-on-windows

**Comment by blink1073** [comment]
It was used for debugging, we can [remove it](https://github.com/jupyterlab/jupyterlab/blob/a5c8c34afd2a8e2f95e25cd731928cb9088ea675/dev_mode/package.json#L7)

**Comment by krassowski** [comment]
Fixed by #11372.
