### ISSUE TITLE
Adjust/customize CSS for editor

### ISSUE THREAD

**Issue by rkpatel33** [jupyterlab/jupyterlab#1133]
Is there a way to customize the CSS by adding a file to the `~/.jupyter/` folder or some other way aside from adjusting the main css file? 

I have customization for my regular Jupyter notebooks but those styles are not picked up at all in Jupyter lab of course. But I would lik to translate them over if possible.

**Comment by blink1073** [comment]
User customization has not been added yet, but is being tracked in #515.

**Comment by jasongrout** [comment]
You can (hackily) customize the styling by manually executing a `%%html` fragment in a document each time you open the page, for example. But the proper customization should come after the settings system is in place.

**Comment by ellisonbg** [comment]
Done with themes...
