### ISSUE TITLE
Malformed file browser icon on Binder in 3.2.x

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#11343]
## Description

The file browser icon on Binder instances is malformed and behaves strangely. A different code path is activated on binder; I do not see this issue on local installations.

## Reproduce

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab)

![visual-glitch-folder-icon-3 2](https://user-images.githubusercontent.com/5832902/138518482-4055f4cf-fec6-41fb-9ebb-cc033041638e.gif)

## Expected behavior

The icon is properly sized and does not jittter when opening/closing sidebar.

## Context

- Browser and version: Chrome 94
- JupyterLab version: 3.2.1 and 3.2.0

**Comment by fcollonval** [comment]
I'm looking into this. From a quick analysis, it looks like we are not setting the sidebar icon in the plugin we are attaching the browser to the shell.

**Comment by fcollonval** [comment]
Bingo, the widget is attached in `@jupyterlab/filebrowser-extension:widget` while the icon is set in `@jupyterlab/filebrowser-extension:browser`
