### ISSUE TITLE
Build failure with Node 17

### ISSUE THREAD

**Issue by jweill-aws** [jupyterlab/jupyterlab#11359]
## Description

On macOS using Node v17.0.1, the current version installed by Homebrew, I get an error when I run `jlpm run build`.

## Reproduce

1. Check out source
2. Satisfy `canvas` dependencies with `brew install pkg-config cairo pango libpng jpeg giflib librsvg`
3. Run `pip install -e .` (successfully)
3. Run `jlpm run build`
4. Compilation error as described below in Command Line Output section.

With Node 16.13.0 or Node 14.18.1, as installed by `nvm`, the compilation step completes successfully. Node 17.0.1 as installed by `nvm` demonstrates the error below as well.

## Expected behavior

Compilation completes successfully.

## Context

- Operating System and version: macOS Big Sur 11.6
- Browser and version:N/A
- JupyterLab version: Building from head of source tree (4 alpha)

<details><summary>Troubleshoot Output</summary>
<pre>
N/A
</pre>
</details>

<details><summary>Command Line Output</summary>
Compilation error:
<pre>
yarn run v1.21.1
$ jlpm run build:dev
$ jlpm run integrity && jlpm run build:all && cd dev_mode && jlpm run build
$ node scripts/ensure-buildutils.js && node buildutils/lib/ensure-repo.js
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/jweill/git/jupyterlab/node_modules/@playwright/test/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:416:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:669:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
 *at requirePackage (/Users/jweill/git/jupyterlab/buildutils/lib/utils.js:312:16) {
*  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v17.0.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
N/A
</pre>
</details>

**Comment by jtpio** [comment]
@jweill-aws is this still an issue now that #11112 is merged (which updates `playwright` to the latest `1.16.2`)?

**Comment by jweill-aws** [comment]
After updating my repo, using Node 17, and running `jlpm run build`, the build now completes with an error while running `@jupyterlab/galata`. Build log excerpt below.

```
$ webpack --mode=production
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:all stderr:
/Users/jweill/git/jupyterlab/node_modules/loader-runner/lib/LoaderRunner.js:146
		if(isError) throw e;
		            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/Users/jweill/git/jupyterlab/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.update (/Users/jweill/git/jupyterlab/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/Users/jweill/git/jupyterlab/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:231:8)
    at NormalModule._initBuildHash (/Users/jweill/git/jupyterlab/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/Users/jweill/git/jupyterlab/node_modules/webpack/lib/NormalModule.js:954:10)
    at /Users/jweill/git/jupyterlab/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/Users/jweill/git/jupyterlab/node_modules/webpack/lib/NormalModule.js:763:11)
    at /Users/jweill/git/jupyterlab/node_modules/webpack/lib/NormalModule.js:827:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
error Command failed with exit code 1.
error Command failed with exit code 1.
lerna ERR! yarn run build:all exited 1 in '@jupyterlab/galata'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 3coins** [comment]
A general note about Node releases, LTS version is what Node recommends for general use. Another point to note is that after 6 months of initial release, odd-numbered versions become unsupported. Here is more information about releases.
https://nodejs.org/en/about/releases/

v17 is too new at the moment to have a wider support, and I have a feeling that there might be a number of dependencies that might cause build issues at the moment. With that knowledge, does it feel worthwhile looking to support builds for node v17? Perhaps we should update documentation to limit the supporting node version to current LTS, and that solves this problem?

**Comment by jweill-aws** [comment]
I'm OK with updating the docs to indicate that we should be using LTS versions instead of Node 17. I am a bit concerned, though that if the build is broken with Node 17, future LTS versions may have the same error.

**Comment by 3coins** [comment]
Agree that we should tackle this at some point, perhaps add it to the next year roadmap so that it ties along with the v18 release.

**Comment by jtpio** [comment]
Just checking whether this is still an issue?

I recently created a new environment with node `17.1.0` on Ubuntu 20.04, and everything seems to be building fine locally.

**Comment by jweill-aws** [comment]
@gabalafou on Gitter reports that Node 17 does not work to build JupyterLab.

https://gitter.im/jupyterlab/jupyterlab?at=61ba776e0c681346aee9a181

**Comment by davidbrochart** [comment]
I'm using a conda environment on Linux, what I see is that it doesn't build with node v16 and v17 because they are pulling openssl v3.0.0. With nodejs v15 it builds fine because it requires openssl v1.1.1l.

**Comment by jweill-aws** [comment]
I still see an error in macOS with Node 17.0.1 and with Node 17.1.0.

Error details:
```
$ webpack --mode=production
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:all stderr:
/Users/jweill/git/jupyterlab/node_modules/loader-runner/lib/LoaderRunner.js:146
		if(isError) throw e;
		            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/Users/jweill/git/jupyterlab/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.update (/Users/jweill/git/jupyterlab/node_modules/webpack/lib/util/createHash.js:46:50)
    at SourceMapSource.updateHash (/Users/jweill/git/jupyterlab/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:231:8)
    at NormalModule._initBuildHash (/Users/jweill/git/jupyterlab/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/Users/jweill/git/jupyterlab/node_modules/webpack/lib/NormalModule.js:954:10)
    at /Users/jweill/git/jupyterlab/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/Users/jweill/git/jupyterlab/node_modules/webpack/lib/NormalModule.js:763:11)
    at /Users/jweill/git/jupyterlab/node_modules/webpack/lib/NormalModule.js:827:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

**Comment by davidbrochart** [comment]
I suppose you have openssl v3. Can you try downgrading to v1?

**Comment by jtpio** [comment]
> I recently created a new environment with node `17.1.0` on Ubuntu 20.04, and everything seems to be building fine locally.

For reference this new environment was created with:

```
mamba create -n jupyterlab -c conda-forge nodejs python yarn "openssl<3" -y
```

Linking to https://github.com/jupyterlab/jupyterlab/issues/11248 as related.

**Comment by jweill-aws** [comment]
@jtpio I created an environment with the same command and, after modifying my `PATH` to include `~/mambaforge/bin` (where `jlpm` is located), I was able to build successfully with Node v17.1.0.

**Comment by jtpio** [comment]
@jweill-aws would you be able to try that out again on the `master` branch, now that #12350 has been merged?

**Comment by jweill-aws** [comment]
With a clean repository on the `master` branch, and Node 17.8.0 installed, I can build JupyterLab successfully.
