### ISSUE TITLE
Add VSCode recommendation for Prettier extension

### ISSUE THREAD

**Issue by jweill-aws** [jupyterlab/jupyterlab#11362]
### Problem

Jupyter recommends the Prettier extension and invokes it as a pre-commit hook to style code. For people who use Visual Studio Code, we can install such an extension locally, but the Jupyter package does not [recommend](https://code.visualstudio.com/docs/editor/extension-marketplace#_extensions-view-filters) that developers do so.

### Proposed Solution

Add a `.vscode/extensions.json` file to recommend that the Prettier extension be installed. This will yield a non-modal popup if a VSCode user opens the repository and doesn't have the extension installed.

### Additional context

Microsoft extensions documentation: https://code.visualstudio.com/docs/editor/extension-marketplace#_extensions-view-filters

**Comment by jtpio** [comment]
Fixed by #11363, thanks!
