### ISSUE TITLE
Add canvas dependency info to docs

### ISSUE THREAD

**Issue by jweill-aws** [jupyterlab/jupyterlab#11364]
### Problem

While running through the [contributing instructions](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html), I encountered a problem while running `pip install -e` that hadn't been covered in the docs. I found a one-line command to run to satisfy `canvas` dependencies.

### Proposed Solution

Add info about the needed `canvas` dependencies to the docs.

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/11365, thanks!
