### ISSUE TITLE
Kite extension doesn't work for Jupyter

### ISSUE THREAD

**Issue by mrexito** [jupyterlab/jupyterlab#11383]
## Description

When I start the co-pilot Kite I don't get any suggestions for auto-completion in my notebook..

## Reproduce

I installed kite with  `pip install jupyter-kite `  and then installed the extension displayed in my Jupyterlab
Then I build Jupyterlab with ` jupyter lab build`
![image](https://user-images.githubusercontent.com/51750327/139644256-d075a745-ff8d-4ae9-aa57-49b2233ab0d4.png)

## Expected behavior

I should get auto-completion suggestion as I type code

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome 92 
- JupyterLab version: 3.2.1 
- in my extension list I see  @kiteco/jupyterlab-kite v1.2.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

**Comment by krassowski** [comment]
Kite extension is maintained by Kite Corporation in https://github.com/kiteco/jupyterlab-kite. Please report any issues directly to Kite on https://github.com/kiteco/issue-tracker. I heard they no longer offer some of the services the way they used to btw, I don't know if this is related.
