### ISSUE TITLE
Building Notebook for Sierra MacOS

### ISSUE THREAD

**Issue by assolisc** [jupyterlab/jupyterlab#1138]
Using python 2.7. Following errors found:

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/piasolis/anaconda2/bin/node" "/Users/piasolis/anaconda2/bin/npm" "dedupe"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20

npm ERR! Callback called more than once.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/piasolis/Documents/jupyterlab/examples/notebook/npm-debug.log
child_process.js:507
    throw err;
    ^

Error: Command failed: npm dedupe
    at checkExecSyncError (child_process.js:464:13)
    at Object.execSync (child_process.js:504:13)
    at Object.<anonymous> (/Users/piasolis/Documents/jupyterlab/scripts/dedupe.js:10:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/piasolis/anaconda2/bin/node" "/Users/piasolis/anaconda2/bin/npm" "install"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! jupyterlab-example-notebook@ postinstall: `node ../../scripts/dedupe.js && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupyterlab-example-notebook@ postinstall script 'node ../../scripts/dedupe.js && npm run build'.
npm ERR! This is most likely a problem with the jupyterlab-example-notebook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../../scripts/dedupe.js && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyterlab-example-notebook
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls jupyterlab-example-notebook
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/piasolis/Documents/jupyterlab/examples/notebook/npm-debug.log

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/piasolis/anaconda2/bin/node" "/Users/piasolis/anaconda2/bin/npm" "run" "update"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! jupyterlab-example-notebook@ update: `rimraf node_modules/jupyterlab && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupyterlab-example-notebook@ update script 'rimraf node_modules/jupyterlab && npm install'.
npm ERR! This is most likely a problem with the jupyterlab-example-notebook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf node_modules/jupyterlab && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyterlab-example-notebook
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls jupyterlab-example-notebook
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/piasolis/Documents/jupyterlab/examples/notebook/npm-debug.log
child_process.js:507
    throw err;
    ^

Error: Command failed: npm run update
    at checkExecSyncError (child_process.js:464:13)
    at Object.execSync (child_process.js:504:13)
    at Object.<anonymous> (/Users/piasolis/Documents/jupyterlab/scripts/buildexamples.js:14:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/piasolis/anaconda2/bin/node" "/Users/piasolis/anaconda2/bin/npm" "run" "build:examples"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! jupyterlab@0.5.1 build:examples: `node scripts/buildexamples.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupyterlab@0.5.1 build:examples script 'node scripts/buildexamples.js'.
npm ERR! This is most likely a problem with the jupyterlab package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/buildexamples.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyterlab
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls jupyterlab
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/piasolis/Documents/jupyterlab/npm-debug.log

Here is the debug log: 
[npm-debug copy.log.txt](https://github.com/jupyterlab/jupyterlab/files/544890/npm-debug.copy.log.txt)

**Comment by blink1073** [comment]
Hi @assolisc, are you able to upgrade your version of `npm`?  We rely on having de-duplicated modules, which requires the `npm dedupe` command to work (which it does not seem to in your case), or `npm v3+`, which is de-duplicated by default.

**Comment by blink1073** [comment]
Closing as stale, please feel free to reopen if you are still having the issue after upgrading.
