### ISSUE TITLE
Filebrowser Context Menu should exclude `Shut Down kernel` for documents that don't support a kernel

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab#11392]
## Description
The context menu give the option to `Shut Down Kernel` even for documents that don't support one such as a `.zip` file and also for notebooks without a currently running kernel.

Continuation of https://github.com/jupyterlab/jupyterlab/issues/9960

## Reproduce
Open filebrowser and right click on any non-folder item

## Expected behavior
`Shut Down Kernel` only present in menu when there is a kernel to be shut down.
## Context

- Operating System and version: Linux Ubuntu 21.04 
- Browser and version: Firefox 93 
- JupyterLab version:  3.2.1

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by jasongrout** [comment]
I think to do this well, it requires some changes in how the filebrowser exposes the selected items and the sessions it knows about, so the command can decide to disable itself if there are no current kernels running on the selected items. Presumably the command at https://github.com/jupyterlab/jupyterlab/blob/b228e5d6cb4f4cdb5fc9ad09a24ad8accb727508/packages/filebrowser-extension/src/index.ts#L995-L1005 would be able to determine what was selected and if any of the selected items had associated kernel sessions.

I also tried this, but it didn't seem to work.

```diff
diff --git a/packages/filebrowser-extension/schema/browser.json b/packages/filebrowser-extension/schema/browser.json
index c2a19defdf..24dc3dccd8 100644
--- a/packages/filebrowser-extension/schema/browser.json
+++ b/packages/filebrowser-extension/schema/browser.json
@@ -104,7 +104,7 @@
       },
       {
         "command": "filebrowser:shutdown",
-        "selector": ".jp-DirListing-item[data-isdir=\"false\"]",
+        "selector": ".jp-DirListing-item[data-isdir=\"false\"]:not(.jp-mod-running)",
         "rank": 11
       },
       {
```
