### ISSUE TITLE
Continously output notebook result when run with command line

### ISSUE THREAD

**Issue by qqdaiyu55** [jupyterlab/jupyterlab#11396]
### Problem

Hi there, I know we can use `jupyter nbconvert --execute --to notebook <notebook>` to execute notebook with command line, it will create the output file after execution.
Can we support continously output the result? Like create the output file on start, then continously update it.

**Comment by krassowski** [comment]
Welcome, @qqdaiyu55! Could you please provide some more context and describe example use-cases? It would help to understand fully what you are trying to achieve.

**Comment by qqdaiyu55** [comment]
Hi @krassowski thanks for quick response. For example, I have a service which executes notebook in background, and I would like to see the progress if the execution takes a long time.

**Comment by qqdaiyu55** [comment]
Resolved. Hacked with `ExecutePreprocessor` in `nbconvert`
