### ISSUE TITLE
Keyboard shortcut parity (with notebook) for collapsible headings

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#11401]
The classic collapsible headings have some keyboard shortcuts that are a key part of the user experience and would be a positive addition to JupyterLab:

> ... lab doesn't have the keyboard shortcuts, which is the key thing - since with the keyboard shortcuts one can jump to start and end of sections so easily, collapsing them actually becomes much less important. Note also that collapsible headings integrates with the TOC2 extension to allow them to optionally sync collapsed sections.

(@jph00 -- https://github.com/jupyter/notebook/issues/6210#issuecomment-960256975)

### Problem

@jph00 continues, describing the behavior in the classic extension that does not exist in JupyterLab:

> Here's what the docs say about the keyboard shortcuts:
> * Command-mode keyboard shortcuts, (enabled by default, and set to left and right arrow keys to collapse/expand sections, or go to the previous/next heading, plus shift-right to select a heading cell's section, shift-a/b to insert a heading above/below the current cell, ctrl-shift-left and ctrl-shift-right to collapse/uncollapse all headings). Bindings are also configurable from the config page
> 
> Details: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/collapsible_headings/readme.html

### Proposed Solution
Let's add these shortcuts by default.

### Additional context
* Original discussion thread: https://github.com/jupyter/notebook/issues/6210#issuecomment-960256975
* Notebook v7 issue: https://github.com/jupyter/notebook/issues/6220

cc: @fcollonval @ajbozarth @marthacryan -- If no one has claimed this issue by next week, could you please raise it at the weekly JupyterLab call?

**Comment by jph00** [comment]
Thanks @afshin . Important correction - the relevent extension for this feature is "collapsible headings", not TOC. It would be good if you could update the title and details to correct this if possible.

**Comment by afshin** [comment]
Thanks for the correction @jph00; I've updated it!

**Comment by fperez** [comment]
Thx for the clarification @jph00! I've added the collapsible headings one to the "day 1" list, along with a note on the keyboard behavior, so it's part of the body of the JEP (draft at this point).
