### ISSUE TITLE
Make toc extension compatible with RetroLab

### ISSUE THREAD

**Issue by jweill-aws** [jupyterlab/jupyterlab#11419]
### Problem

The `toc` extension is not compatible with RetroLab because RetroLab uses an `IRetroShell` as its shell whereas JupyterLab uses an `ILabShell`. The extension expects an `ILabShell` object to be passed in.

This blocks https://github.com/jupyterlab/retrolab/issues/272 which I'd like to resolve by adding a dependency on `@jupyterlab/toc`.

### Proposed Solution

Per suggestion by @jtpio in https://github.com/jupyterlab/retrolab/issues/272#issuecomment-963475247, make the `toc` extension optionally dependent on `ILabShell` and, where `ILabShell` is not required, use `app.shell` to refer to the shell (an instance of `IShell`).

### Additional context

See https://github.com/jupyterlab/retrolab/issues/272 including comments.

**Comment by jtpio** [comment]
Fixed by #11420
