### ISSUE TITLE
Avoid refreshing contextual help just to show the same thing again

### ISSUE THREAD

**Issue by bluss** [jupyterlab/jupyterlab#11410]
### Problem
The contextual help pane updates its view, even if it is just to re-display the same thing. This can reset the scroll and disrupt reading in the context help pane. 

### Proposed Solution

Avoid updating/refreshing the contextual help pane if it would be just for showing the same docs it's already displaying.

**Comment by jasongrout** [comment]
I put in a simple fix in #11447. Feel free to test it with the binder link there and comment: https://mybinder.org/v2/gh/jasongrout/jupyterlab/inspectcache?urlpath=lab-dev
