### ISSUE TITLE
Make ILayoutRestorer optional in toc-extension

### ISSUE THREAD

**Issue by jweill-aws** [jupyterlab/jupyterlab#11444]
### Problem

`IRetroShell` in RetroLab cannot use the `toc-extension` because the required parameter `restorer` (of type `ILayoutRestorer`) is not accessible. Error:

```
Plugin '@jupyterlab/toc:plugin' failed to activate. index.es6.js:292:25
Error: No provider for: @jupyterlab/application:ILayoutRestorer
```

### Proposed Solution

Make the `restorer` parameter optional in `toc-extension`.

### Additional context

See also PR #11420 which made `labShell` optional in this extension.

**Comment by fcollonval** [comment]
> Make the `restorer` parameter optional in `toc-extension`.

I know that this is the easiest approach. But from a user experience point of view, I think it makes sense to restore any side panel previously open for a given notebook in retrolab.

cc @jtpio @ellisonbg

**Comment by jtpio** [comment]
> I think it makes sense to restore any side panel previously open for a given notebook in retrolab.

Sure. But that is a different question than making the restorer optional.

Having the restorer optional makes it possible for other lab-based applications to reuse the plugin as is. For example if someone wants to show a notebook with the toc on the left always visible (similar to some of the [examples](https://github.com/jupyterlab/jupyterlab/tree/master/examples))
