### ISSUE TITLE
jupyterlab-0.5.1 is not published on pypi ?

### ISSUE THREAD

**Issue by stonebig** [jupyterlab/jupyterlab#1144]

**Comment by jasongrout** [comment]
https://github.com/jupyterlab/jupyterlab/releases/tag/v0.5.1

**Comment by jasongrout** [comment]
(be aware that it should probably have been called 0.6.0 - there were probably some breaking changes.

**Comment by jasongrout** [comment]
Does that answer your question?

**Comment by stonebig** [comment]
not really, I was looking for a wheel packaging of it

**Comment by jasongrout** [comment]
ah, yes. We released 0.5.1 of just the javascript library so we could use it in development. We'll soon be releasing 0.6.0 on pypi.

**Comment by stonebig** [comment]
soon... today ?

**Comment by jasongrout** [comment]
Probably next week
