### ISSUE TITLE
executionScheduled should be emitted after the code cell's execute() is called

### ISSUE THREAD

**Issue by xiaohk** [jupyterlab/jupyterlab#11452]
## Description

Right now the `executionScheduled` signal is emitted before `CodeCell.execute` is called.

https://github.com/jupyterlab/jupyterlab/blob/5755ea86fef3fdbba10cd05b23703b9d60b53226/packages/notebook/src/actions.tsx#L2026-L2027

It can cause execution racing in widget development. See the example below.

## Reproduce

Say we are developing a widget that automatically executes a code cell A whenever any other code cell is executed. We can listen to the `executionScheduled` signal:

```ts
// Listen to the notebook execution events so we can auto-run cell A
NotebookActions.executionScheduled.connect((_, args) => {
  if (args.cell.node !== this.cell.node) {
    this.execute();
  }
});
```

Our custom `execute` in this widget is defined as:

```ts
/**
 * Run the code cell. The implementation logic is: (1) change the original cell
 * as the active cell, (2) use the NotebookActions to run the current active
 * cell
 */
execute = () => {
  // Find the cell index of the original cell
  // https://github.com/jupyterlab/jupyterlab/blob/5755ea86fef3fdbba10cd05b23703b9d60b53226/packages/notebook/src/widget.ts#L1803
  const cellIndex = ArrayExt.findFirstIndex(
    this.notebook.content.widgets,
    widget => widget.node === this.originalCell.node
  );

  // Change the active cell to the original cell
  this.notebook.content.activeCellIndex = cellIndex;

  // Run the active cell
  NotebookActions.run(
    this.notebook.content,
    this.notebook.context.sessionContext
  );
};
```

Now we run cell B; it would trigger cell A to run as well.

## Expected behavior

We would expected cell B to execute before cell A. However, cell A would actually run before cell B, because executionScheduled is emitted [before we actually call cell B's `execute` function](https://github.com/jupyterlab/jupyterlab/blob/5755ea86fef3fdbba10cd05b23703b9d60b53226/packages/notebook/src/actions.tsx#L2026-L2027).

A workaround would be setting a timeout:

```ts
// Listen to the notebook execution events so we can auto-run cell A
NotebookActions.executionScheduled.connect((_, args) => {
  if (args.cell.node !== this.cell.node) {
      setTimeout(() => {
        cd.execute();
      }, 1);
  }
});
```

## Context

- Operating System and version: macOS 12.0.1
- Browser and version: Firefox Developer 95.0b6
- JupyterLab version: 3.2.2

**Comment by krassowski** [comment]
Thank you for opening the issue and for the PR. Previously I suggested adding a separate `executionStarted` signal, but it did not end up in #10493. I see how proposed change will indeed solve the race you are experiencing, but it could potentially change edge conditions for existing users - let's see what @mwakaba2 thinks.

@trungleduc I recall you tried to use `executionScheduled` for progress bar (#10730) but don't see that in the codebase, instead I see the final version listens directly to the Comm messages (code linked below). Is this something which should be encouraged for uses like in this issue too?

https://github.com/jupyterlab/jupyterlab/blob/c43be83a988e0826f75fb21bb3ca120d43f3b10e/packages/notebook/src/executionindicator.tsx#L287-L320

**Comment by xiaohk** [comment]
> Thank you for opening the issue and for the PR. Previously I suggested adding a separate `executionStarted` signal, but it did not end up in #10493. I see how proposed change will indeed solve the race you are experiencing, but it could potentially change edge conditions for existing users - let's see what @mwakaba2 thinks.

Got it! I think adding a separate `executionStarted` which is emitted after the `execute()` call would be very valuable. Right now the naming of `executionScheduled` is a bit misleading, as it is actually `beforeExecutionScheduled`. I think adding `executionStarted` can make it more clear. I can update my PR to add a `executionStarted`. Would love to hear @mwakaba2's feedback as well. Thanks!

**Comment by fcollonval** [comment]
Hey a couple of comments below, but to summarize it -> I don't think we should not change anything but we could add the `executionStarted` (but don't like the idea see the race condition mentioned below).

First about the wording `executionScheduled` means _The execution of a cell has been planed at a later time_. It promises that your cell is not yet executed but will be later.

If we do the permutation suggested in #11453 (aka emitting `executionScheduled` after starting the execution). We can end up in a race condition because there is now way to ensure all listeners will receive `executionScheduled` before `executed` started to be emitted.

If you want to react to a cell execution, I would advice tempering directly with kernel messaging similarly to what the debugger is doing. One of the reason is that multiple cells may be selected and executed in a batch. With your snippet, that feature will be broken as you change the active cell.

**Comment by fcollonval** [comment]
Another source of inspiration can be the variables inspector: https://github.com/lckr/jupyterlab-variableInspector/blob/70220c75ec8047ebdec38e5123915073a084e8ed/src/handler.ts#L75

**Comment by trungleduc** [comment]
Hi all, I'm completely in line with what @fcollonval suggested. In  #10730 the reason i used the `Comm` messages instead of the `executionScheduled`  signal is to capture the execution requests come from both code cells and widgets.

**Comment by xiaohk** [comment]
Sounds good! Thanks for the helpful feedback @fcollonval. I will look into the `Comm` messages.
