### ISSUE TITLE
Jupyter Lab not launching

### ISSUE THREAD

**Issue by JayTWWM** [jupyterlab/jupyterlab#11486]
## Description

Installed using pip......
Tried to launch

![Yeet](https://user-images.githubusercontent.com/54232875/142257243-c6f151de-7f88-43d4-9143-ec933eb354f4.PNG)

It gets stuck here
It wasn't launching from Anaconda Navigator as well

## Reproduce

$ pip install jupyterlab
$ jupyter-lab

## Expected behavior

Jupyter Lab should open

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome 96
- JupyterLab version: 3.2.3

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>

![Yeet](https://user-images.githubusercontent.com/54232875/142361841-bc2afa41-c89f-474e-8bd6-03d0e8c369e0.PNG)

</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
Hi @JayTWWM could you please fill in the [bug issue template](https://github.com/jupyterlab/jupyterlab/issues/new?assignees=&labels=bug&template=bug_report.md) providing troubleshooting information?

**Comment by JayTWWM** [comment]
## Description



## Reproduce

$ pip install jupyterlab
$ jupyter-lab

## Expected behavior

Jupyter Lab should open

## Context



- Operating System and version: Windows 10
- Browser and version: Chrome 96
- JupyterLab version: 3.1.14



<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>

![Yeet](https://user-images.githubusercontent.com/54232875/142361841-bc2afa41-c89f-474e-8bd6-03d0e8c369e0.PNG)

</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
One more section is missing (`jupyter troubleshoot`) so we can check the versions of server

**Comment by JayTWWM** [comment]
I’m so sorry to trouble you, it was my antivirus that creating a problem. The issue isn’t fully solved yet…. I’ll have to talk to my antivirus provider.
Thanks.

**Comment by krassowski** [comment]
That's interesting! Thank you for explaining the situation. Would you mind sharing the name of the antivirus software, or would you prefer not to?

**Comment by JayTWWM** [comment]
Yeah it is the QuickHeal antivirus. It is basically stopping anything from running a local server. You can switch off the browser protection and it’ll work for you!
