### ISSUE TITLE
Undo of cell deletion loses cell metadata

### ISSUE THREAD

**Issue by The-Compiler** [jupyterlab/jupyterlab#11483]
## Description

When deleting a cell (via `dd` or the "cut" button) and then undoing that operation, the cell metadata gets lost.

## Reproduce

1. Create a file with a cell with a cell tag; or download this example file: 
[before-undo.ipynb.txt](https://github.com/jupyterlab/jupyterlab/files/7556088/before-undo.ipynb.txt) (added `.txt` to make the GitHub upload accept it...)

![image](https://user-images.githubusercontent.com/625793/142235514-f6e40318-0fb3-4b58-9f67-56c71c1c059f.png)

2. Delete the cell, e.g. via `dd` or the "cut" button
3. Undo the operation, via either "undo" or "undo cell operation"
4. Observe how the tag is removed:

![image](https://user-images.githubusercontent.com/625793/142235979-94e3ce15-5cd6-45af-873b-7ecc44cc195c.png)

See [after-undo.ipynb.txt](https://github.com/jupyterlab/jupyterlab/files/7556110/after-undo.ipynb.txt)

## Expected behavior

The cell gets restored in the same state as it was deleted.

## Context

diff between the resulting files:

```diff
--- before-undo.ipynb	2021-11-17 17:02:43.648317508 +0100
+++ after-undo.ipynb	2021-11-17 17:03:00.331668154 +0100
@@ -3,11 +3,7 @@
   {
    "cell_type": "markdown",
    "id": "1a4b9600-d074-4301-ac23-cf2e754f6138",
-   "metadata": {
-    "tags": [
-     "i-am-a-tag"
-    ]
-   },
+   "metadata": {},
    "source": [
     "This cell has a tag..."
    ]

```

- Operating System and version: Archlinux
- Browser and version: Chromium 95.0.4638.69, Firefox 94.0
- JupyterLab version: 3.2.1, 4.0.0a15 (current git master, b6470ce3aa898a8d6d6271f5ec90d52eaee66716)

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/opt/pyenv/plugins/pyenv-virtualenv/shims
	/usr/share/perl5/vendor_perl/auto/share/dist/Cope
	/home/florian/.pyenv/shims
	/home/florian/.pyenv/bin
	/usr/lib/ccache/bin/
	/usr/local/sbin
	/usr/local/bin
	/usr/bin
	/opt/android-sdk/platform-tools
	/home/florian/.local/share/flatpak/exports/bin
	/usr/lib/jvm/default/bin
	/usr/bin/site_perl
	/usr/bin/vendor_perl
	/usr/bin/core_perl
	/home/florian/bin
	/home/florian/bin/go/bin
	/home/florian/.emacs.d/bin

sys.path:
	/home/florian/tmp/jupyterlab/.venv/bin
	/usr/lib/python39.zip
	/usr/lib/python3.9
	/usr/lib/python3.9/lib-dynload
	/home/florian/tmp/jupyterlab/.venv/lib/python3.9/site-packages
	/home/florian/tmp/jupyterlab

sys.executable:
	/home/florian/tmp/jupyterlab/.venv/bin/python3

sys.version:
	3.9.7 (default, Oct 10 2021, 15:13:22) 
	[GCC 11.1.0]

platform.platform():
	Linux-5.14.16-arch1-1-x86_64-with-glibc2.33

which -a jupyter:
	/usr/bin/jupyter

pip list:
	Package             Version   Location
	------------------- --------- ----------------------------
	anyio               3.3.4
	argon2-cffi         21.1.0
	attrs               21.2.0
	Babel               2.9.1
	backcall            0.2.0
	bleach              4.1.0
	certifi             2021.10.8
	cffi                1.15.0
	charset-normalizer  2.0.7
	debugpy             1.5.1
	decorator           5.1.0
	defusedxml          0.7.1
	entrypoints         0.3
	idna                3.3
	ipykernel           6.5.0
	ipython             7.29.0
	ipython-genutils    0.2.0
	jedi                0.18.1
	Jinja2              3.0.3
	json5               0.9.6
	jsonschema          4.2.1
	jupyter-client      7.0.6
	jupyter-core        4.9.1
	jupyter-server      1.11.2
	jupyterlab          4.0.0a15  /home/florian/tmp/jupyterlab
	jupyterlab-pygments 0.1.2
	jupyterlab-server   2.8.2
	MarkupSafe          2.0.1
	matplotlib-inline   0.1.3
	mistune             0.8.4
	nbclassic           0.3.4
	nbclient            0.5.8
	nbconvert           6.3.0
	nbformat            5.1.3
	nest-asyncio        1.5.1
	notebook            6.4.6
	packaging           21.2
	pandocfilters       1.5.0
	parso               0.8.2
	pexpect             4.8.0
	pickleshare         0.7.5
	pip                 21.2.3
	prometheus-client   0.12.0
	prompt-toolkit      3.0.22
	ptyprocess          0.7.0
	pycparser           2.21
	Pygments            2.10.0
	pyparsing           2.4.7
	pyrsistent          0.18.0
	python-dateutil     2.8.2
	pytz                2021.3
	pyzmq               22.3.0
	requests            2.26.0
	Send2Trash          1.8.0
	setuptools          57.4.0
	six                 1.16.0
	sniffio             1.2.0
	terminado           0.12.1
	testpath            0.5.0
	tornado             6.1
	traitlets           5.1.1
	urllib3             1.26.7
	wcwidth             0.2.5
	webencodings        0.5.1
	websocket-client    1.2.1
</pre>
</details>

<details><summary>Command Line Output</summary>
Nothing relevant during delete/undo operation.
</details>

<details><summary>Browser Output</summary>
<pre>
Nothing  during delete/undo operation.
</pre>
</details>

**Comment by hbcarlos** [comment]
Hi @The-Compiler, thanks for opening this issue.
Indeed, this is a critical bug. It looks like when undoing the operation, we are not adding the metadata from the shared model to ModelDB.

I'm working on this.
