### ISSUE TITLE
Readthedocs API missing for 1.2.x

### ISSUE THREAD

**Issue by aolney** [jupyterlab/jupyterlab#11489]
## Description

No API documentation seems to be available for 1.2.x, e.g.

https://jupyterlab.readthedocs.io/en/1.2.x/api/index.html

## Reproduce

1. Go to https://jupyterlab.readthedocs.io/en/3.2.x/api/index.html
2. Observe the 3.2.x documentation is there
3. Go to https://jupyterlab.readthedocs.io/en/1.2.x/api/index.html
4. Observe the error page

## Expected behavior

To see documentation when visiting https://jupyterlab.readthedocs.io/en/1.2.x/api/index.html

## Context

NA

**Comment by ohrely** [comment]
I am able to see the 1.2.x docs at https://jupyterlab.readthedocs.io/en/1.2.x/ , are you @aolney ?  Is there a reason you expect or need the specific `api/index.html` path to work?

**Comment by aolney** [comment]
Thanks @ohrely . Those are the general docs, not the API docs. I'm specifically looking for the API docs.

**Comment by krassowski** [comment]
I believe that the API reference were not there for 1.2.x. Personally I would really recommend developing against JupyterLab 3.x as the extension ecosystem improved a lot since 1.x.

**Comment by aolney** [comment]
@krassowski if you know where the API reference previously was for 1.2.x, a link or guess of where to look would be appreciated. I have tried using the wayback machine, but it has not been able to fill much in, .e.g: https://web.archive.org/web/20190911021505/http://jupyterlab.github.io/jupyterlab/modules/_application_src_index_.html 

I'm currently supporting a project developed against 1.2.x. I would like to migrate it to 3.x at some point, but until then, I need access to the documentation for 1.2.x. 

I imagine 1.2.x documentation would also help with migration to 3.x  :smiley_cat:

**Comment by ohrely** [comment]
> Thanks @ohrely . Those are the general docs, not the API docs. I'm specifically looking for the API docs.

Ah didn't read closely enough, thanks for your patience 🙃

It looks like the API docs weren't included in Sphinx builds until last year: https://github.com/jupyterlab/jupyterlab/pull/9179 .  I'll let folks with more context opine on whether it would be possible/practical to backport that change to 1.2.
