### ISSUE TITLE
Make the hidden cells button optional

### ISSUE THREAD

**Issue by schmidi314** [jupyterlab/jupyterlab#11490]
### Problem

In large notebooks with many headings that are usually collapsed, the hidden-cells buttons next to a collapsed heading take quite some space. I would like the display of this button to be optional.

### Proposed Solution

* Add an option "showHiddenCellsButton" to TOC
* Basically add dependency on this option in maybeCreateOrUpdateExpandButton() to
https://github.com/jupyterlab/jupyterlab/blob/7aba384baa09393e98432619b3355f57d7529012/packages/cells/src/widget.ts#L1604-L1608
(But it would probably be better to rework the if/else structure slightly)

### Open questions

* Should this option actually be located in TOC? Notebook might also be a good place for this.

**Comment by schmidi314** [comment]
More specific solution proposal:
* Option `showHiddenCellsButton` goes to Notebook settings (ToC hasn't much to do with the collapsing of headings.)
* Option is communicated to `MarkdownCell` widget --> `MarkdownCell._showHiddenCellsButton`
* In `MarkdownCell.maybeCreateOrUpdateExpandButton()` this property is used to decide whether or not the button shall be displayed.

And this is what it looks like:

![optional_hidden_cells_button](https://user-images.githubusercontent.com/74381262/142507691-3c375a9f-0d7d-4490-9972-8c399c4822d0.gif)

Available in schmidi314/jupyterlab branch feature/optional_hidden_cells_button

...not sure what to do now. Pull request?

**Comment by krassowski** [comment]
> ...not sure what to do now. Pull request?

 :+1: Opening a draft pull request is always a good idea once you are at a working prototype stage and would like to get feedback :)

I would suggest that there should always be an indication of cells being hidden even when `showHiddenCellsButton` is set to `false`. I would suggest when `showHiddenCellsButton == false` the little arrow which shows on headers when hovering over should be persisted as a subtle indication. Maybe even something more prominent (but obviously not as prominent as the current button which as you note takes a lot of space).

Another thing that we like to have before adding any more features/configuration options to notebook is more visual tests. The chances of the PR getting approved will rise significantly if it will come with a visual regression test (or a few) using [galata](https://github.com/jupyterlab/jupyterlab/tree/master/galata).

**Comment by schmidi314** [comment]
Thanks for the input. Making the little arrow persistent sounds good to me. Also making the little arrow somewhat less little would be a general suggestion of mine. So, how about:
* make the arrow persistent if `showHiddenCellsButton == false`
* making arrows bigger (not using the same one as the code folding arrows)

**Comment by krassowski** [comment]
This plan sounds good to me.
