### ISSUE TITLE
Switching console kernels is confusing.

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#1151]
The "switch kernel" interface relies on the unique names that are generated for each console, so if you want to switch between one console session and another, the truncated names that show up in the dropdown are insufficient information.

Here is the problem illustrated in a screenshot:

<img width="793" src="https://cloud.githubusercontent.com/assets/159529/19654668/3513d5a8-9a11-11e6-836a-4954476314b1.png">

**Comment by blink1073** [comment]
We discussed special-casing consoles in the kernel switcher and the running dialog to parse a path of the form `console-<number>-uuid` and display it as `Console <number>`.

**Comment by blink1073** [comment]
And then removing this special case when Notebook 4.3 is released with the expanded Sessions API that includes `name` and `type`.

**Comment by mircealex** [comment]
Related -- when I want to open a new console for a certain active kernel, it's almost impossible to select the kernel I want because of the truncated name of the notebooks.

![image](https://user-images.githubusercontent.com/22998607/37558322-ea76b6e6-2a1a-11e8-9fae-e3726a026ae3.png)
