### ISSUE TITLE
Kernelspec icon broken when base_url is used

### ISSUE THREAD

**Issue by ricklamers** [jupyterlab/jupyterlab#11527]
## Description
The kernelspec icon is broken when a `--LabApp.base_url` is specified. This has to do with how the kernelspec path is used directly for the <img /> element.

See https://github.com/jupyterlab/jupyterlab/blob/f5d186ce59c30dfd645178e54a21e00ab661607f/packages/notebook-extension/src/index.ts#L1432

## Reproduce

1. Configure a `base_url` that's not `""`.
2. Open the launcher tab
3. Observe broken kernel icons (because the image path can't be resolved)

## Expected behavior
Kernelspec icons should respect the configured `base_url`. This can be achieved in multiple ways, a relative path seems to work (stripping the leading `/` from the path `/kernelspecs/python3/logo-64x64.png`). Ideally the path resolve is harmonized with how resource paths in general in the application respect the `base_url`.

## Context

- Operating System and version: Debian Linux
- Browser and version: Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit) 
- JupyterLab version: 3.2.4

## Screenshot
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1309307/143011367-9aa2c2f7-5808-4c86-ae28-a0ffd5e98dd6.png">

**Comment by ricklamers** [comment]
I think in 3.1 this is how it makes the path issue take the `base_url` into account:

https://github.com/jupyterlab/jupyterlab/blob/90ed111b152665357b069cf4a42590fe07d630e8/packages/notebook-extension/src/index.ts#L1266

**Comment by krassowski** [comment]
This is likely due to https://github.com/jupyterlab/jupyterlab/pull/11175 which also introduced this issue in JupyterLab Desktop where we worked around this by adding `<base href="${juypter_server_url}">` (in https://github.com/jupyterlab/jupyterlab-desktop/pull/322), but it caused other issues, some of which were fixed in https://github.com/jupyterlab/jupyterlab-desktop/pull/344 but I am still not fully satisfied with it. CC @jtpio

**Comment by jtpio** [comment]
Thanks @ricklamers for reporting and @krassowski for the input.

It does sound related to the change in https://github.com/jupyterlab/jupyterlab/pull/11175. #11175 points to the code in `jupyter_server` handling the base url:

https://github.com/jupyter-server/jupyter_server/blob/ac93dd8f60de54db99167016f0396959826b8ed9/jupyter_server/services/kernelspecs/handlers.py#L33

Which happens to be working fine when the base url is set to something else, for example on Binder: https://github.com/jupyterlab/jupyterlab/pull/11175#issuecomment-929592422

@ricklamers could it be that the kernelspecs in your setup are handled differently?

The observation that lead to #11175 was the fact that `kernelspecs` was hardcoded in the logic and expected to be part of the resource URLs:

https://github.com/jupyterlab/jupyterlab/blob/90ed111b152665357b069cf4a42590fe07d630e8/packages/notebook-extension/src/index.ts#L1265

**Comment by ricklamers** [comment]
I think it might be caused by the fact that in my configuration I'm using the Jupyter Enterprise Gateway (which in turn uses the Jupyter Kernel Gateway). They both have `base_url` configured (using `KG_BASE_URL` and `EG_BASE_URL` respectively). But the `/api/kernelspecs` still returns resources with an absolute path that doesn't respect the configured `base_url`:

```json
{
  "resources": {
    "logo-64x64": "/kernelspecs/my-kernel/logo-64x64.png",
    "logo-32x32": "/kernelspecs/my-kernel/logo-32x32.png"
  }
}
```

**Comment by jtpio** [comment]
Ah ok then that would explain why. So probably something that should be investigated in Jupyter Kernel / Entreprise Gateway to check the `base_url` is correctly handled?

**Comment by ricklamers** [comment]
After merging https://github.com/jupyter/enterprise_gateway/pull/1019 the problem went away for us. I think this was eventually the responsibility of the kernel manager (and the resource paths it returns). So I think we can consider this solved (never being an issue in JupyterLab itself).

**Comment by ricklamers** [comment]
For the record, I also contributed that fix to the Kernel Gateway project because it was also affected: https://github.com/jupyter/kernel_gateway/pull/372
