### ISSUE TITLE
Show the list of current connected users in RTC mode

### ISSUE THREAD

**Issue by trungleduc** [jupyterlab/jupyterlab#11528]
### Problem

The list of connected users is initially started by @hbcarlos in https://github.com/jupyterlab/jupyterlab/pull/11180 but then is dropped in https://github.com/jupyterlab/jupyterlab/pull/11443. I think this feature is very useful and I'm planning to work on it so I open this issue to discuss the ways to fit this UI element into the current interface of JupyterLab.

### Proposed Solution
I created some mockups for this widget, any comments or suggestions are welcome! 

1. Show the list on the top menu:

![topbar (4)](https://user-images.githubusercontent.com/4451292/143043415-7368d88b-02a1-4b50-8c11-cba515b9e1fd.png)
      
      - Pros: Easy to access, the same position as other collaborative software (Google Docs,...).
      - Cons:  Too distracting, is not directly linked with the notebook. 
    
2. Show the list on the right corner:

![rightbar (2)](https://user-images.githubusercontent.com/4451292/143040479-b755c445-1566-4ccf-babb-79eebb34f3cd.png)
    
     - Pros: Easy to access, less distracting than case 1.
     - Cons:  Is not directly linked with the notebook. 

3. Show the number of connected users with the name of the notebook on the status bar, show the popup of connected users when users click on it:

![statusbar (2)](https://user-images.githubusercontent.com/4451292/143040488-ed448cf4-1391-48bf-a802-b48165e73f78.png)

      - Pros: Linked with the notebook, not distracting.
      - Cons:  Is not easy to access.
      
### Additional context

The positioning of this widget depends also on the position of the current user widget, which is the output of  https://github.com/jupyterlab/jupyterlab/pull/11443

**Comment by martinRenou** [comment]
Other possible solution: show user icons (in front/in/on top) of the cells collaborators are working on.

**Comment by wolfv** [comment]
I think on the right side looks nice. And it would allow for other features (like a chat feature) later, where one could click on the collaborator icons and that opens a widget in the right sidebar. 
@martinRenou are the cursors not visible anyways (with a name attached to them?).

**Comment by martinRenou** [comment]
> @martinRenou are the cursors not visible anyways (with a name attached to them?).

Not always. If a collaborator has focus on one cell but is not in "edit" mode, you would not see the cursor.
So showing the collaborator logo next to the cell could be a visual indicator that the other collaborator has focus on that cell.

**Comment by trungleduc** [comment]
> Thanks for working on this @trungleduc! Some feedback from the team meeting is that we need to hide the widget if there aren't collaborators or the collaborative mode is disabled.
 
Indeed, this is what I planned too.

**Comment by jtpio** [comment]
Referencing the comment in https://github.com/jupyterlab/jupyterlab/pull/11443#issuecomment-977747494, something a bit more discreet like proposal 2 and 3 sounds good.

**Comment by krassowski** [comment]
I like the proposal (1) because it follows the established pattern of showing the active users indicator in top right corner. This is how Office 365, Google Docs, Deepnote and many other applications place their indicator. I think this is a very strong argument - we should not try to be innovative with placement, but place it where the user expect it to be. I think there is plenty of place there.

**Comment by SylvainCorlay** [comment]
> I like the proposal (1) because it follows the established pattern of showing the active users indicator in top right corner. This is how Office 365, Google Docs, Deepnote and many other applications place their indicator. I think this is a very strong argument - we should not try to be innovative with placement, but place it where the user expect it to be. I think there is plenty of place there.

I agree with @krassowski on this one. This is the behavior that most people will expect and understand.
