### ISSUE TITLE
Kernel auto re-connect stops after 7 attempts

### ISSUE THREAD

**Issue by 3coins** [jupyterlab/jupyterlab#11534]
### Problem
Current kernel connection makes only 7 attempts to re-connect after a network connection fails; this amounts to about 1-2 minutes in actual notebook sessions. Many users leave their machines, close them or engage in other activities after they submit a long running task. If a network connection is severed during this time for any reason, although the long running task continues to execute on the kernel, the UI stops re-connecting after 1-2 minutes and shows a state of "Disconnected". When the users return to the notebook and even if network connection is resumed, there is no attempt to re-connect to the kernel and so the task output is stuck at the initial state. 

Although, manually reconnecting to kernel (Kernel -> Reconnect to Kernel) re-hydrates the task output to correct state, most users end up refreshing the notebook and re-submitting the task. This ends up being an immense waste of resources and a frustrating experience for users especially for long running tasks. 

### Proposed Solution

* After UI has exhausted connecting to the kernel, update the dialog with an action button/link to re-connect to kernel. This should bring the option to re-connect front and center to the users and help alleviate this issue.
* Make reconnect limit configurable, so this can be controlled at runtime or through settings. See [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/kernel/default.ts#L1464-L1465)  for more context.
* Auto-close the "Server Connection Error" dialog if the kernel connection is resumed. This has to be manually closed today even after the connection to the kernel is resumed.
* Backport kernel re-connect API to version 1.2.x. Lab users for this version doesn't have an option to re-connect to kernel.

#### Reproducing the issue locally
1. Start Jupyter Lab - `jupyter lab`
2. Setup port forwarding to port 8889 - `ssh -L 8889:localhost:8888 localhost`
3. Open lab on port 8889 - `http://localhost:8889/lab`
4. Open a new ipython notebook, paste this code and execute
```python
import time

step = 1

while step < 10:
    print(f"Step {step}")
    time.sleep(30)
    step = step + 1
    
print('Done')
``` 
5. Stop local port forwarding - `kill $(ps aux | awk '/localhost/ && !/awk/ {print $2}')`
6. Wait for the kernel status to become "Disconnected" in the status bar, this should take 1-2 mins.
7. Re-setup the port forwarding - `ssh -L 8889:localhost:8888 localhost`
8. No more output is seen from the cell, refreshing the notebook will not re-connect to the same kernel session.

**Comment by krassowski** [comment]
Cross referencing a related issue: https://github.com/jupyterlab/jupyterlab/issues/11303

**Comment by 3coins** [comment]
@blink1073 @Zsailer 
While working on this today, I noticed a change in the kernel reconnect behavior. Here is the related PR - [#593](https://github.com/jupyter-server/jupyter_server/pull/593). It seems like with these changes, when the network connection is dropped for a short period, notebook never attempts to re-connect to the kernel. 

![Jan-25-2022 20-37-42](https://user-images.githubusercontent.com/289369/151104790-dbf56b8d-5ae6-40bd-81e2-7116b92cfe6c.gif)


Here are my installation details:
```
jupyter-server: 1.13.0
jupyter-client: 7.1.2
jupyterlab: 4.0.0a19
```
This is quite different from JupyterLab's earlier behavior where a re-connect was attempted if the network connection was severed for a short period; users could also manually attempt to re-connect to the kernel from the Kernel menu options. This no longer seems to work in 4.x. 

Manual reconnect seems to work with 3.2.x, but auto re-connect is still not working.

Is this behavior intended, or am I missing any configuration?

**Comment by blink1073** [comment]
I think what you're seeing is the new behavior introduced #11358.  If the initial connection fails, it attempts to get the kernel model using `GET` to see if the kernel is still alive.  I think that should also keep trying if it gets a server error in order to handle the case of a severed network connection.
