### ISSUE TITLE
Scrolling output - allow to resize height

### ISSUE THREAD

**Issue by stefansimik** [jupyterlab/jupyterlab#11549]
### Problem

It would be nice, if **height of scrolling output** could be resize-able.
Currently - it has static fixed height, without any possibility to resize it, according to the individual preference.

Idea visualized:
![idea](https://user-images.githubusercontent.com/6208056/143425469-c4f7316b-49ee-4034-a702-d422141c1e0c.png)

### Proposed Solution

Add some small drag/drop area **at the bottom** of the scrolling output,
This will be intuitively used for changing height of the scrolling output.

**Comment by krassowski** [comment]
This was implemented in JupyterLab 4.0 (https://github.com/jupyterlab/jupyterlab/pull/12740). It was also tracked in. https://github.com/jupyterlab/jupyterlab/issues/12100.
