### ISSUE TITLE
Clicking out of input box traps cursor in console prompt

### ISSUE THREAD

**Issue by ClaytonPassmore** [jupyterlab/jupyterlab#1154]
I found a bug while playing around with `input`.
To reproduce, open a console, type `input()` and hit enter. The input box should have focus.

Now click outside of the input box and the cursor returns to the console prompt.
If you try to focus the input box by clicking, focus always returns to the console prompt so you can never move on because the `input` function never returns.

Pretty sure it has to do with the click event listener forcing the focus of the console prompt.

**Comment by blink1073** [comment]
Hi @ClaytonPassmore, this behavior is fixed in master and will be in the next release.

**Comment by ClaytonPassmore** [comment]
@blink1073 are you sure? I'm still seeing it in master.

**Comment by blink1073** [comment]
Yes, I just tried it again.  What is the output of `git rev-parse HEAD`?

**Comment by ClaytonPassmore** [comment]
Ok I just pulled latest and it seems to be working... I pulled this morning... so did this get fixed _today_?

**Comment by blink1073** [comment]
It was fixed in https://github.com/jupyterlab/jupyterlab/pull/1123.

**Comment by ClaytonPassmore** [comment]
Strange. Thanks for the info.
