### ISSUE TITLE
`experimentalDisableDocumentWideUndoRedo` breaks undo of completer

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#11556]
## Description

When `experimentalDisableDocumentWideUndoRedo` (#10791) is enabled the undo does not work on text inserted by completer.

## Reproduce

1. Go to settings -> `Notebook` and set:
    ```js
    {
        "experimentalDisableDocumentWideUndoRedo": true
    }
    ```
2. Open a new notebook
3. Type `f<tab>`, select "from", type "a" select "abc", type "im" select "import", type "A" select "ABCMeta"
4. See `from abc import ABCMeta`
4. Press ctrl + Z three times
5. See `fromabcimportABCMeta` - spaces were removed but the text that was auto-completed was not

![problem-with-undo](https://user-images.githubusercontent.com/5832902/143573393-b59689f4-2389-472d-ac26-4f8fc43c49d5.gif)

## Expected behavior

Undo removes completed text when document-wide undo/red is disabled.

## Context

- Browser and version: Chrome 96
- JupyterLab version: 3.2.4

**Comment by cyaris** [comment]
Same issue for me.

**Comment by suganya-sk** [comment]
Hello! This issue is still present in version 3.4.3. Any updates on a timeline here please?

**Comment by nishikantparmariam** [comment]
+1 for this, I encountered it while writing an extension. Looking forward to https://github.com/jupyterlab/jupyterlab/pull/14063!

I am using below API which completer also uses:

https://github.com/jupyterlab/jupyterlab/blob/b806333290052c3d549876213191a1e2094793ee/packages/completer/src/handler.ts#L170

But, running into the same problem as above. Is there a cheap workaround here other than setting `experimentalDisableDocumentWideUndoRedo` to `false`?
