### ISSUE TITLE
Terminal loses data on resize

### ISSUE THREAD

**Issue by metaperture** [jupyterlab/jupyterlab#1155]
After performing some operations in the terminal at a larger width, when resizing to a shorter width many characters get hidden. Upon resizing to a larger width, the text is now gone completely.

[version 0.5.0]

**Comment by blink1073** [comment]
This appears to be a limitation of `xterm.js`, the library we are using for the terminal.  I opened https://github.com/sourcelair/xterm.js/issues/325.

**Comment by blink1073** [comment]
Update: this was fixed upstream in https://github.com/sourcelair/xterm.js/pull/616, will be in the 2.5 release of xterm.
