### ISSUE TITLE
[PATCH] bad import of the 'marked' javascript package?

### ISSUE THREAD

**Issue by SnarkBoojum** [jupyterlab/jupyterlab#11569]
Still trying my hand at jupyterlab for Debian, in packages/rendermime, once I point to the type definitions, I get:
```
src/renderers.ts(746,7): error TS2349: This expression is not callable.
  Type 'typeof import("/usr/share/nodejs/@types/marked/index")' has no call signatures.
src/renderers.ts(952,12): error TS2339: Property 'setOptions' does not exist on type 'typeof import("/usr/share/nodejs/@types/marked/index")'.
```
which means each and every use of marked is an error:
```
$ grep src/renderers.ts -e marked -n
13:import marked from 'marked';
746:      marked(content, (err: any, content: string) => {
942:  let markedInitialized = false;
948:    if (markedInitialized) {
951:    markedInitialized = true;
952:    marked.setOptions({
```

Notice that in packages/rendermime, the deps are 2.0.0 for marked and 1.1.0 for @types/marked, but Debian has marked 4.0.5 and @types/marked 4.0.1.

It turns out just changing line 13 to:
```
import { marked } from 'marked';
```
is enough to please tsc ; so perhaps that's a good change to make?

**Comment by fcollonval** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/11879
