### ISSUE TITLE
[PATCH] Obsolete dep on webpack-env in packages/ui-components ?

### ISSUE THREAD

**Issue by SnarkBoojum** [jupyterlab/jupyterlab#11567]
In packages/ui-components/tsconfig.json, webpack-env is cited, but doesn't look like it's getting used, so perhaps it can be dropped:
```
--- jupyterlab-3.2.4.orig/packages/ui-components/tsconfig.json
+++ jupyterlab-3.2.4/packages/ui-components/tsconfig.json
@@ -3,7 +3,7 @@
   "compilerOptions": {
     "outDir": "lib",
     "rootDir": "src",
-    "types": ["webpack-env", "node"]
+    "types": ["node"]
   },
   "include": ["src/**/*"],
   "references": [
```

(I'm still trying to get the deps right in Debian, so perhaps I'm wrong)

**Comment by jtpio** [comment]
Thanks @SnarkBoojum.

According to the git history the dependency on `@types/webpack-env` was added in https://github.com/jupyterlab/jupyterlab/commit/9c7bda994d76c1e716cfa6c746ef647c8b103c03, as part of this PR: https://github.com/jupyterlab/jupyterlab/pull/6034

Not sure we still need it. Would you like to open a PR that removes to check whether the CI check pass? Thanks!

**Comment by SnarkBoojum** [comment]
Uh... I don't have a clue how to do a PR...

**Comment by jtpio** [comment]
@SnarkBoojum I opened https://github.com/jupyterlab/jupyterlab/pull/11587 to check if removing `webpack-env` has any side effect.
