### ISSUE TITLE
Check Release failing on CI - unpin `vega-embed` dependency

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#11563]
## Description

One more failing check left on CI.

The Check Release is now failing, for example this run on the latest commit: https://github.com/jupyterlab/jupyterlab/runs/4342119386?check_suite_focus=true

Which is picking up the latest `vega-embed@6.20.4`: 

![image](https://user-images.githubusercontent.com/591645/143715417-41cdb2b5-6738-4493-aafa-0693a829da1e.png)

This PR sounds related: https://github.com/vega/vega-embed/pull/802

**Comment by fcollonval** [comment]
I opened an issue upstream: https://github.com/vega/vega-embed/issues/806

**Comment by fcollonval** [comment]
Upstream issue has been fixed and a new vega-embed version has been published - I opened #11578 to revert the temporary fix.
