### ISSUE TITLE
How to render JupyterLab Service Session Time

### ISSUE THREAD

**Issue by sachinkaushik** [jupyterlab/jupyterlab#11579]
Hi Team,

I need your help. This is not bug.

We have a requirement where we want to show session time on JupyterLab's top bar, whenever User get access to JupyterLab.
Let say we have session time 2Hrs, then in this case it should be shown on Jupyterlab.

Do we have any such configuration file where we can make changes related to session time configuration.

Please help me here. Thank you in advance.!

Thanks,
Sachin

**Comment by jtpio** [comment]
Thanks @sachinkaushik.

Would you like to open a new thread on Discourse: https://discourse.jupyter.org/latest?

This is a great place to discuss ideas about implementing custom extensions.

**Comment by sachinkaushik** [comment]
I have created below discussion.

https://discourse.jupyter.org/t/how-to-render-jupyterlab-service-session-time/11958

**Comment by jtpio** [comment]
Thanks @sachinkaushik.

Let's close this issue then so we can keep the conversation in one place.

**Comment by sachinkaushik** [comment]
sure we can close it...

and waiting for reply on that link..
