### ISSUE TITLE
Cannot build examples

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#11586]
## Description

While trying to [build the examples](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#build-and-run-the-stand-alone-examples), I get the following error:
```
lerna ERR! yarn run build stderr:

Compilation starting…


Compilation finished


Compilation starting…

Cannot read JSON for path /home/david/github/davidbrochart/jupyterlab/examples/federated/labextensions/@jupyterlab/example-federated-md/package.json: Error: ENOENT: no such file or directory, open '/home/david/github/davidbrochart/jupyterlab/examples/federated/labextensions/@jupyterlab/example-federated-md/package.json'
/home/david/github/davidbrochart/jupyterlab/builder/lib/build-labextension.js:100
            throw new Error(err.details);
            ^

Error
    at compilerCallback (/home/david/github/davidbrochart/jupyterlab/builder/lib/build-labextension.js:100:19)
    at /home/david/github/davidbrochart/jupyterlab/builder/lib/build-labextension.js:142:21
    at /home/david/github/davidbrochart/jupyterlab/node_modules/neo-async/async.js:2830:7
    at done (/home/david/github/davidbrochart/jupyterlab/node_modules/neo-async/async.js:2865:11)
    at /home/david/github/davidbrochart/jupyterlab/node_modules/neo-async/async.js:2818:7
    at /home/david/github/davidbrochart/jupyterlab/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/david/github/davidbrochart/jupyterlab/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/david/github/davidbrochart/jupyterlab/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/home/david/github/davidbrochart/jupyterlab/node_modules/webpack/lib/Cache.js:150:23)
    at /home/david/github/davidbrochart/jupyterlab/node_modules/webpack/lib/Compiler.js:1156:15
error Command failed with exit code 1.
lerna ERR! yarn run build exited 1 in '@jupyterlab/example-federated'
lerna WARN complete Waiting for 6 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
```

## Reproduce

1. [Install JupyterLab](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#installing-jupyterlab):
```
git clone https://github.com/<your-github-username>/jupyterlab.git
cd jupyterlab
pip install -e .
jlpm install
jlpm run build
jlpm run build:core
jupyter lab build
```
2. Build the examples: `jlpm run build:examples`
3. See the error message

## Expected behavior

The path `/home/david/github/davidbrochart/jupyterlab/examples/federated/labextensions/@jupyterlab/example-federated-md/package.json` exists, so I don't understand the error message.

## Context

- Operating System and version: Linux Ubuntu 21.04
- JupyterLab version: master

**Comment by jtpio** [comment]
Thanks @davidbrochart.

> git clone https://github.com/<your-github-username>/jupyterlab.git

Is this from a clean copy of the repo?

I just run `jlpm run build:examples` locally from an existing fork on the latest `master` and it seems to have correctly built all the examples:

![image](https://user-images.githubusercontent.com/591645/144055241-430be655-018d-4d4e-aaba-9072a5f3b127.png)

Also the examples test is still passing on CI which runs the following commands: 

https://github.com/jupyterlab/jupyterlab/blob/ef35fd02a0cf1c787ba5782815df040c1589bee9/scripts/ci_script.sh#L154-L164

**Comment by davidbrochart** [comment]
Starting from a new repo solved the issue, thanks @jtpio.
The error message was very confusing, though.
