### ISSUE TITLE
Make scrolled output shadow visible at the bottom

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#11583]
The current behavior matches the one of the classical notebook (aka content is below top shadow but above bottom shadow - see https://github.com/berkeley-dsep-infra/datahub/issues/2993). Should the content be below the bottom shadow too?

![image](https://user-images.githubusercontent.com/591645/142254775-fd809e21-d567-4a05-82a3-3de2d8e6a48f.png)

I personnally in favor of applying the same trick to have the content below the bottom shadow too as it should emphasize the content is enclosed within a scrollable container.

_Originally posted by @fcollonval in https://github.com/jupyterlab/jupyterlab/issues/11478#issuecomment-973830299_

**Comment by thesinepainter** [comment]
The background material of the table rows are drawing over the inset shadows, this happens both at the top and bottom when scrolling. I disabled the row background to check it, and the shadows are drawn over the table again. 

![CSS-Fix](https://user-images.githubusercontent.com/54241101/148030496-c39d0865-ddc5-4b7d-b905-ae2d936bf4ab.jpg)

I'd like to try working on this some more, however when I make changes to the css files in the repo, they aren't reflected when I refresh the page. Would greatly appreciate some help wrt how to get it to reflect back when refreshing the page. I'm running jupyter through "jupyter lab --dev-mode"
