### ISSUE TITLE
Benchmark tests broken following update of NodeJS in ubuntu image

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#11606]
## Description

[Benchmark tests](https://github.com/jupyterlab/jupyterlab/actions/workflows/benchmark.yml) are failing due to an update of NodeJS in the ubuntu image that is incompatible with CML action (to publish the benchmark image).

```
Error: The module '/usr/local/lib/node_modules/@dvcorg/cml/node_modules/mmmagic/build/Release/magic.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 83.
```

## Reproduce

Execute a benchmark job

## Expected behavior

No error

**Comment by casperdcl** [comment]
technically should be re-opened as #11607 was a work-around not a fix :)
