### ISSUE TITLE
Question: remove classic notebook server traitlets shim?

### ISSUE THREAD

**Issue by Zsailer** [jupyterlab/jupyterlab#11612]
In JupyterLab 3.x, we switched from the classic Notebook Tornado server to Jupyter Server's Tornado server. When doing this, the underlying traitlets `Configurable` object that holds the server's traits changed names (i.e. `NotebookApp` to  `ServerApp`). Anyone who knows traitlets also knows that this is kind of transition is a pain, because it forces all users to change the trait prefixes in all of their configuration files. 

To help smooth this transition, we added a [shim layer](https://github.com/jupyterlab/jupyterlab/blob/295443beccdc1b0d19834e1ae60a13733f4e655b/jupyterlab/labapp.py#L478) in JupyterLab 3.x (coming from nbclassic) that *did its best* to automatically port traits with the wrong prefix name to the correct object. This layer raises a bunch of warnings every time it shims a trait. 

**Now that we're nearing a 4.x release, should we remove this shim layer?**

Removing this layer requires a major release. The question is should we remove it in 4.x or 5.x.

**Comment by jtpio** [comment]
Thanks @Zsailer for opening this :+1: 

I would be in favor of dropping it for 4.0, which is most likely still a few months away before being released.

We can communicate about breaking changes early enough so folks have time to process them and update their config, ideally early enough in the beta phase.

**Comment by jtpio** [comment]
I opened https://github.com/jupyterlab/jupyterlab/pull/11894 to consider removing it for `4.0`.

**Comment by echarles** [comment]
What does it cost to keep it as it is as long as possible? nbclassic has done a great work for some extensions I have been using. Not sure if they are migrated now.

If there is a cost to maintain nbclassic, I guess a scan of server extensions that are not migrated would help to take a decision.

**Comment by jtpio** [comment]
Linking to https://github.com/jupyterlab/team-compass/issues/133#issuecomment-989018555, https://github.com/jupyterlab/nbclassic/issues/81 and related issues for more context.

One of the main reasons for this would be to allow installing JupyterLab 4.0 with Notebook 7 as part of the Notebook 7 JEP: https://jupyter.org/enhancement-proposals/79-notebook-v7/notebook-v7.html.

At the moment `nbclassic` has `notebook<7` as a dependency: https://github.com/jupyterlab/nbclassic/blob/623b8fa136031b0d32aee0385327df82f0060ac5/setup.cfg#L30
