### ISSUE TITLE
Open recently closed notebook

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#11613]
### Problem

I sometimes close a notebook only to want to come back to it quickly (oops forgot to do X). Since I use a lot of folders, they are buried somewhere that takes a lot of navigating. It should be possible to reopen a notebook quickly. 

### Proposed Solution

Similar to browser's recently closed feature, we should add a recently closed feature to jupyter ([example](https://www.businessinsider.com/how-to-restore-google-chrome-tabs)). I don't think we need to implement a full history but the last N from the session (I think 10 is a good default).

**Comment by davidbrochart** [comment]
Actually your workspace is restored when you relaunch JupyterLab, and it reopens the notebooks you had opened. Isn't it the behavior you are asking for?
Or maybe you are referring to the case where you close a notebook tab (not the whole JupyterLab window), and want to reopen it? In that case, if you didn't shut down the associated kernel, you can double click on the notebook in the Kernels list:

![image](https://user-images.githubusercontent.com/4711805/144682329-0e06f3dc-f5c0-490f-8e7d-094288a8ea00.png)

**Comment by krassowski** [comment]
+1 on this. I think "Reopen Closed Tab" could be in the context menu of the main area tab, because:
- this is where "Close Tab", "Close All Other Tabs" and "Close Tabs to Right" are
- this is where it is in web browsers

Also, somehow related extension: https://github.com/jupyterlab-contrib/jupyterlab-recents/
