### ISSUE TITLE
Dropdown widget is not preserving the sort of a list passed to the options parameter.

### ISSUE THREAD

**Issue by afonit** [jupyterlab/jupyterlab#11624]
I have upgraded recently to:
|package|version|
|--|--|
|ipywidgets|7.6.5|
|jupyterlab|3.2.4|

Issue:
The dropdown widget is no longer preserving the order of the list.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/1798497/144867343-0b531cd4-fd85-4dde-a787-577d33c4667a.png)

You can see the `data` variable has the data in order, but when the dropdown is selected - the dates are not in the same order.

In previous versions of ipywidgets the order was preserved.

here is the code I was using:

```python
import ipywidgets as widgets

data = [
        '2021-11-25',
        '2021-11-28',
        '2021-11-27',
        '2021-12-01',
        '2021-11-29',
        '2021-12-04',
        '2021-12-03',
        '2021-11-26',
        '2021-11-30',
        '2021-12-02'
]

dropdown = widgets.Dropdown(value=data[0], options=data)
dropdown
```

To ensure it was not a used environment issue I created a new one to test this out (it installed the versions at the top of this issue):
```bash
conda create -n sort_issue
conda activate sort_issue
mamba install -c conda-forge jupyterlab ipywidgets
```

**Comment by davidbrochart** [comment]
I'm not sure to understand, from your screenshot it looks like the dropdown has the same list (and order) than the data that is passed, or am I missing something?
