### ISSUE TITLE
Kernel is `idle` but cells are busy when restarting a notebook

### ISSUE THREAD

**Issue by bloussou** [jupyterlab/jupyterlab#11636]
## Description
I manged to be in the state the image shows :
![image](https://user-images.githubusercontent.com/32448554/145214822-cad7fa9f-626e-4202-a4c4-1e6eb5734787.png)

## Reproduce

```python
import pandas as pd

position_data = [
    ['001', 'Hermes', 'IBM', 100.0],
    ['002', 'Hermes', 'GM', 100.0],
    ['003', 'Benchoo', 'IBM', 90.0],
    ['004', 'Benchoo', 'TSLA', 8.0],
]
position_df = pd.DataFrame(position_data, columns = ['Id', 'Portfolio', 'Instrument', 'Quantity'])

instrument_data = [
    ['IBM', 'Tech', 122.0],
    ['GM', 'Automotive', 61.0],
    ['TSLA', 'Automotive', 1051.0],
]
instrument_df = pd.DataFrame(instrument_data, columns = ['Instrument', 'Sector', 'Value'])
```

1. restart the kernel
2. Execute very fastly `shift+enter` to run the cells
3. Status will be idle even if cells are busy
4. After a while cells are executed normaly

Workaround : fastforward button

## Expected behavior
kernel should be busy and cells must be execute one after the other the normal way. It does not happen if `shift+enter` is pressed after status has been changed for `restarting->idle`.

## Context

- Operating System and version: Windows 10 and ubuntu 21.10
- Browser and version: Firefox 94.0
- JupyterLab version: 3.0.15

**Comment by davidbrochart** [comment]
Hi @bloussou, thanks for reporting the issue. I cannot reproduce it locally on Ubuntu 21.04 with Jupyterlab 3.0.15 and Firefox 94.0.
Does is happen often? Can you upgrade JupyterLab to a newer version?

**Comment by bloussou** [comment]
I'm closing this as I cannot reproduce it anymore
