### ISSUE TITLE
JupyterLab 3.3 Release

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#11643]
Hi, I am opening this to discuss and gather inputs on a potential 3.3. release from the current 3.2 branch before the 4.0 release. We have a few ongoing PR that, if merged, would deserve a release before the 4.0 release.

The idea would be to get a 3.3. release in January 2022. Of course, if the 4.0 release is achievable by that time, we could skip that intermediary step.

List of pending PR to consider for 3.3 - Please edit this comment to add yours.

- [x] https://github.com/jupyterlab/jupyterlab/pull/11752
- [x] :ballot_box_with_check: https://github.com/jupyterlab/jupyterlab/pull/11608  
       https://github.com/jupyterlab/jupyterlab/pull/11718  
       https://github.com/jupyterlab/jupyterlab/pull/11794
  -  Check if PR for resizing is already backported in 3.x
- [x] https://github.com/jupyterlab/jupyterlab/pull/11566  
  https://github.com/jupyterlab/jupyterlab/pull/11954
  https://github.com/jupyterlab/jupyterlab/pull/12068
- [x] https://github.com/jupyterlab/jupyterlab/issues/11735. 
  https://github.com/jupyterlab/jupyterlab/pull/11909
- [x] :ballot_box_with_check: https://github.com/jupyterlab/jupyterlab/issues/11719
  https://github.com/jupyterlab/jupyterlab/pull/11948
- [x] :ballot_box_with_check: https://github.com/jupyterlab/jupyterlab/issues/11700
  https://github.com/jupyterlab/jupyterlab/pull/11929
- [x] https://github.com/jupyterlab/jupyterlab/issues/11710
  https://github.com/jupyterlab/jupyterlab/pull/11956
- [x] :ballot_box_with_check: https://github.com/jupyterlab/jupyterlab/pull/11646  
  https://github.com/jupyterlab/jupyterlab/pull/11867
- [x] :ballot_box_with_check: https://github.com/jupyterlab/jupyterlab/pull/11740  
  https://github.com/jupyterlab/jupyterlab/pull/11866
- [x] :ballot_box_with_check: https://github.com/jupyterlab/jupyterlab/pull/10299  
  https://github.com/jupyterlab/jupyterlab/pull/11874
- [x] :ballot_box_with_check: https://github.com/jupyterlab/jupyterlab/pull/11171  
  https://github.com/jupyterlab/jupyterlab/pull/11874
- [x] :ballot_box_with_check: https://github.com/jupyterlab/jupyterlab/pull/11637  
  https://github.com/jupyterlab/jupyterlab/pull/11868
- [x] https://github.com/jupyterlab/jupyterlab/pull/11079
  - When backported rename the menu entry to keep the same _Advanced Settings Editor_
  - Check that the shortcut is maintained when backported
- [x] :ballot_box_with_check: https://github.com/jupyterlab/jupyterlab/pull/10469  
  https://github.com/jupyterlab/jupyterlab/pull/11873
- [x] :ballot_box_with_check: https://github.com/jupyterlab/jupyterlab/pull/11730  
  https://github.com/jupyterlab/jupyterlab/pull/11869
- [x] :ballot_box_with_check: https://github.com/jupyterlab/jupyterlab/pull/11387  
  https://github.com/jupyterlab/jupyterlab/pull/11870
- [ ] https://github.com/jupyterlab/jupyterlab/issues/10633
  - Pinging on the issue to figure out if someone plans to push a fix
- [x] https://github.com/jupyterlab/jupyterlab/pull/11540  
  https://github.com/jupyterlab/jupyterlab/pull/11940
- [x] https://github.com/jupyterlab/jupyterlab/pull/11941
- [x] https://github.com/jupyterlab/jupyterlab/pull/11963
---
Edited to gather all suggestions
Edited with :ballot_box_with_check: to highlight backported PR to 3.3.x has been created

**Comment by krassowski** [comment]
I would propose:
- [ ] https://github.com/jupyterlab/jupyterlab/pull/10299
- [ ] https://github.com/jupyterlab/jupyterlab/pull/11171

**Comment by fcollonval** [comment]
@echarles in this week meeting, it was decided to carry out a 3.3 release in January (RC0 on 3rd week). We will review which features to bring in on January 12th meeting.

I propose:
- [ ] https://github.com/jupyterlab/jupyterlab/pull/11079

**Comment by ajbozarth** [comment]
I'll need to comb through the issues in more detail later, but off the cuff I know the small fix in https://github.com/jupyterlab/jupyterlab/pull/11540 is something Elyra would love to see in 3.3

**Comment by fcollonval** [comment]
- [ ] https://github.com/jupyterlab/jupyterlab/pull/11730

**Comment by ohrely** [comment]
Could #11387 be included?

**Comment by zer0-memory** [comment]
I propose #10633

**Comment by fcollonval** [comment]
> I propose #10633

@zer0-memory thanks for the suggestion. Due to our limited bandwidth, only features that are part of master will be added to JLab 3.3. So if you can help with fixing the mentioned issue, it will be great.

**Comment by jtpio** [comment]
Posting here some thoughts on how the JS packages should be versioned for `3.3`.

Currently the packages are at the `3.2.x` version on the `3.3.x` branch:

![image](https://user-images.githubusercontent.com/591645/148564946-cb5f2b95-0700-4dc7-8c34-fb8324487346.png)

If we want to go through the usual alpha -> beta -> rc -> final cycle, the versions will then be bumped to `3.3.0-alpha.x` when we start releasing `3.3.0ax`.

However these versions have already been used on `master` during the `4.0.0ax` release series. For example:

https://github.com/jupyterlab/jupyterlab/blob/d1244eaa11eada494d98826e16ca42b31b9476f5/packages/application/package.json

![image](https://user-images.githubusercontent.com/591645/148565166-ff3618d6-bebe-4d4c-ae0d-91e47d6ffe2c.png)

And published to npm: https://www.npmjs.com/package/@jupyterlab/application/v/3.3.0-alpha.1

Something to keep in mind when we start making the `3.3` pre-releases. We might have to manually bump the versions first.

**Comment by jtpio** [comment]
> Something to keep in mind when we start making the 3.3 pre-releases. We might have to manually bump the versions first.

Probably the simplest would then be to manually bump the JS packages to `3.3.0-alpha.16` on the `3.3.x` branch. So we are still on alpha. This should help fix CI issues when backporting to that branch, as noticed in https://github.com/jupyterlab/jupyterlab/pull/11804.

**Comment by blink1073** [comment]
Any objections to backporting https://github.com/jupyterlab/jupyterlab/pull/11358 to 3.3.x?  I can help @Zsailer with the backport if manual changes are required.

**Comment by jtpio** [comment]
FYI the first `3.3` prerelease is out: https://pypi.org/project/jupyterlab/3.3.0a1/

**Comment by jtpio** [comment]
`3.3.0a2` is out: https://github.com/jupyterlab/jupyterlab/releases/tag/v3.3.0a2

**Comment by krassowski** [comment]
This one is a common ask:
- [ ] https://github.com/jupyterlab/jupyterlab/issues/11903#issuecomment-1021586697

**Comment by trungleduc** [comment]
@krassowski I'm working on it https://github.com/jupyterlab/jupyterlab/pull/11941

**Comment by echarles** [comment]
We have said during our last dev meeting yesterday https://github.com/jupyterlab/team-compass/issues/135#issuecomment-1028208651 that we would release a new alpha next week.

Looking at all the PR merged since the last alpha release, I step-in to already make a new alpha release this week. Base on the status of the merged PR and the remaining ones, we can always make a new alpha release next week.

I hope this will work for everyone and that it will help to speed up the process for 3.3 final.

**Comment by fcollonval** [comment]
Major features are now merged in 3.3.x. Remaining PRs are listed in the [3.3.x milestone](https://github.com/jupyterlab/jupyterlab/milestone/65)

**Comment by fcollonval** [comment]
@jtpio @echarles I saw in the latest [changelog](https://github.com/jupyterlab/jupyterlab/pull/11997) that `@jupyterlab/ui-components` has a different version (it is `alpha.17` when all others are `alpha.18`). Should that be fixed or it does not matter?

**Comment by jtpio** [comment]
@fcollonval I think this is expected and related to the `3.3.0-alpha.x` versioning that was on `master` (targeting 4.0) for a while (https://github.com/jupyterlab/jupyterlab/issues/11643#issuecomment-1007493038)

This was noticed in https://github.com/jupyterlab/jupyterlab/pull/11810.

When we bump to `3.3.0b0` these numbers should normally be realigned.

**Comment by echarles** [comment]
Yes, I asked my self similar question in former releases. The different jupyterlab packages are bumped, but not enforced to be the same. I guess that is no change is seen, there is no bump. So a 3.3.0-alpha.x release will be composed of various npm packages version number. The pypi version has however to be aligned

Then bumping from eg alpha to beta will reset all that.

**Comment by echarles** [comment]
@jtpio we have further discussed the release plan and the consensus was to keep the final release date by end of February. This would imply a Beta release this week. I can handle that today if OK for you.

**Comment by jtpio** [comment]
Right we should be good for the beta now that most of the features have been backported. The remaining `3.3.x` PRs are for fixing issues and they can be addressed during the beta cycle.

**Comment by fcollonval** [comment]
JupyterLab release 3.3.0 will be done on March 2nd at 4pm CET (7am PT). You can join the release on [Zoom](https://zoom.us/my/jovyan?pwd=c0JZTHlNdS9Sek9vdzR3aTJ4SzFTQT09).

**Comment by jtpio** [comment]
JupyterLab 3.3.0 is out :tada: 

- Release notes: https://github.com/jupyterlab/jupyterlab/releases/tag/v3.3.0
- Install with: `pip install jupyterlab==3.3.0`
- Some bug fixes are on the way and we will be releasing `3.3.x`

Let us know if you find any issue. Thanks all!
