### ISSUE TITLE
CSS background-color jp-layout-color1 not showing up properly

### ISSUE THREAD

**Issue by andrewfulton9** [jupyterlab/jupyterlab#11656]
## Description

Recently, when I build off of master, selected menu items in the debugger have stopped having the background color show that they are selected. I suspect this issue isn't debugger specific though. In the gif below I try to demonstrate the css not working by changing between the table and tree views of the variable panel in the debugger. Notice how it isn't clear from the buttons which one is clicked.

![chrome-capture (1)](https://user-images.githubusercontent.com/13774419/145594333-032962be-2a8f-4949-b135-b94bd7c690e8.gif)

Below is what the styles section of the inspector console is showing:

![jp-ViewModeSelected](https://user-images.githubusercontent.com/13774419/145594854-1b92dcbd-f111-4ac0-80c0-b30b9f519496.png)

## Reproduce

From a master branch build:
1) open a notebook
2) turn on debugger
3) toggle back and forth between tree and table view of the variables panel in the debugger.

## Expected behavior

a button that is toggled on has a grey background to indicate it is toggled.

## Context

- Operating System and version: 
linux ubuntu 18.04.6
- Browser and version: 
Chrome  96.0.4664.45 
- JupyterLab version: 
-Master Branch

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by echarles** [comment]
Thx @andrewfulton9 for opening this.

@fcollonval To give you a bit more background, this issue has been seen while reviewing https://github.com/jupyterlab/jupyterlab/pull/10298 but it looks like a general issue in master. I remember you have participated to large changes around CSS (blueprint removal...). Could this issue be related to those changes?

**Comment by krassowski** [comment]
On 3.x the panel is headers are grey, so the white background for the buttons makes sense:

![Screenshot from 2021-12-12 14-29-54](https://user-images.githubusercontent.com/5832902/145716511-5973ac3d-465d-4d85-8631-a083fb7e3c5f.png)

The change to white bakcground was introduced in https://github.com/jupyterlab/jupyterlab/pull/11369 (CC @hbcarlos) (unrelated to blueprint removal). Previously we had:

```css
.jp-DebuggerSidebar-body .jp-stack-panel-header {
  background-color: var(--jp-layout-color2);
}
```

While currently we have:

https://github.com/jupyterlab/jupyterlab/blob/2263baaa6f8452c02cd9800ed9c7e42e92de812f/packages/ui-components/style/sidepanel.css#L36-L46

where `--jp-toolbar-background` is white in the default theme.

I think I preferred the old style where toolbars had the grey background - it was strengthening the visual hierarchy.

Please note that in addition to changing the background of toolbars to `background: var(--jp-layout-color2);` we would also need to change:
- background of some buttons (`.jp-ToolbarButtonComponent` in Breakpoints, Source, etc) in hover state - we cold match to the behaviour of `.jp-ToolbarButton` in Variables)
- and we could consider adding back the 1 pixel border of darker grey on the toolbars

What do you all think?

**Comment by hbcarlos** [comment]
Indeed this comes from the accordion panel PR. We need to change the toolbar's background color in the accordion panel. The actual colors are a bit confusing.

I believe this could be a "good first issue". What do you think?

**Comment by echarles** [comment]
> I believe this could be a "good first issue". What do you think?

This blocks for now https://github.com/jupyterlab/jupyterlab/pull/10298 so we could pick that asap.

I have not tested, but the point is that the button do not change, I wonder if changing the toolbar color will fix the issue.

**Comment by fcollonval** [comment]
The idea of switching to white background is to move towards homogeneity in side panels. The debugger panel was the only using section title with non-white color (compare to the extension manager, tabs/running panels, property inspector). I don't have strong opinion regarding the styling itself; only that we should push towards homogeneity between widgets used to improve usability, accessibility and maintenance.

**Comment by echarles** [comment]
At the end, we need to ensure the button has a visual state (on/off) as shown in https://user-images.githubusercontent.com/3627835/121290061-9930b100-c8ab-11eb-9700-055cab2f19a1.gif

Before, the button (transparent?) was grey, and then when clicked it was becoming white.

We have lost that now. If the default is white, the pressed should be grey, right?

**Comment by fcollonval** [comment]
> If the default is white, the pressed should be grey, right?

Yes it should

**Comment by andrewfulton9** [comment]
I created PR #11688 to change the icon background colors in the debugger. I haven't seen any other places this is an issue, so I think this may be all that's needed.

**Comment by echarles** [comment]
Closed via https://github.com/jupyterlab/jupyterlab/pull/11688
