### ISSUE TITLE
Drop `familyName` from the `ICurrentUser` interface?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#11657]
### Problem

https://github.com/jupyterlab/jupyterlab/pull/11443 added the `ICurrentUser` interface to represent the user.

In this interface there is the `familyName` attribute. However the notion of "family name" could be problematic in some cases because for some people it might not mean anything. For example this talk covers common issues with names: https://www.youtube.com/watch?v=pBuS7EUPnQA

This issue raises the question of whether we want to keep it that way, or try to reduce the number of fields related to the name.

### Proposed Solution

Maybe we should try to keep only one field to encode the `name` of the user?

For the initials that would mean keeping the existing logic with the split, which should be enough?

https://github.com/jupyterlab/jupyterlab/blob/b80475fbd409385eae2017fbb82c72c638fd6959/packages/user/src/utils.ts#L138-L153

### Additional context

Follow-up to https://github.com/jupyterlab/jupyterlab/pull/11443.

Raising this question now since we are still in the 4.0 alpha release cycle and able to make API breaking changes and iterate on this interface.

cc @hbcarlos if you have any input on this

**Comment by davidbrochart** [comment]
> Maybe we should try to keep only one field to encode the `name` of the user?

Sounds reasonable.

**Comment by krassowski** [comment]
Sounds like a good opportunity to mention: https://github.com/kdeldycke/awesome-falsehood#human-identity.

Also linking to https://www.w3.org/International/questions/qa-personal-names which was mentioned in a previous discussion on this topic in  https://github.com/jupyterlab/jupyterlab/pull/11443/files#r761474932.

- [ ] Another tiny thing about `getInitials` function: `name = "  Name"` (two spaces, only one rendered because HTML) could get blank initials if I read it correctly.

**Comment by hbcarlos** [comment]
Thanks for opening this issue @jtpio.

> Also linking to https://www.w3.org/International/questions/qa-personal-names which was mentioned in a previous discussion on this topic in https://github.com/jupyterlab/jupyterlab/pull/11443/files#r761474932.

Yes, @vidartf pointed out this article about handling fields for names.
A summarize, the safest way of treating this problem is to use only one field, `name`, and even remove the `getInitials` function and directly ask users for their initials.

**Comment by ellisonbg** [comment]
This is a useful reference:

https://developer.apple.com/documentation/foundation/personnamecomponentsformatter

**Comment by krassowski** [comment]
@tonyfast also mentioned FOAF core: http://xmlns.com/foaf/spec/#glance

**Comment by ellisonbg** [comment]
I think we or extension authors will likely want to use a users initials and/or the users "first" or "display" name (Brian in my case). Given the problems in a strict first/last name approach what if the data model had:

* `name` (maybe `fullName` to be more explicit?)
* `displayName` (or `firstName`?)
* initials

I do agree that we should not try to compute in a general manner the `initials` or `displayName` from the name, but a particular implementer of this plugin could make decisions about that as needed.

In the case of random users, I think something like the following would make sense:

* `name` = "<random moon> Anonymous"
* `displayName = "<random moon>"
* `initials` = "" or "<M>A"

**Comment by jweill-aws** [comment]
I like @ellisonbg 's suggestion of `name`, `displayName`, and `initials` (extremely brief name). This avoids cross-cultural issues with naming conventions, none of which are essential to the functionality of JupyterLab.

**Comment by hbcarlos** [comment]
I like the idea of having `name`, `displayName`, and `initials`. I can open a PR to change it.
Regarding the anonymous users, I'm not sure I understand what @ellisonbg meant here:

> In the case of random users, I think something like the following would make sense:
> - name = " Anonymous"
> - `displayName = ""
> - initials = "" or "A"

Currently, the anonymous names are randomly generated as "Anonymous" + moon of Jupiter.
If the idea of having `displayName` is to show that on the UI, wouldn't the following be better?
- `name` = "Anonymous moon"
- `displayName` = "Anonymous moon" or "A. moon" or "moon"
- `initials` = "A E" or "E" => Where E is the initial of the moon

In addition, we should create a widget to allow anonymous users to change at least `displayName` and `initials`.

**Comment by hbcarlos** [comment]
Solved in #11774
