### ISSUE TITLE
"Print" in JupyterLab 4.0 yields "500 Internal Server Error"

### ISSUE THREAD

**Issue by rfox12** [jupyterlab/jupyterlab#11686]
## Description

I'm running clean/plain build of JupyterLab 4.0.0a17
Firefox 

When printing a page does come up, but the contents are an error report (see screenshot)
![image](https://user-images.githubusercontent.com/33066940/146008739-114cfd18-c849-41bc-b588-2772024393eb.png)

The text may be hard to read:
```
Jupyter Server requires Javascript. 
Please enable it to proceed.  
```

But the more helpful message was in the JupyterLab terminal console:
```
 File ".../lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 610, in get_template_names
        raise ValueError('No template sub-directory with name %r found in the following paths:\n\t%s' % (base_template, paths))
    ValueError: No template sub-directory with name 'lab' found in the following paths:
        /home/robert/.local/share/jupyter
        /home/robert/mambaforge/envs/.../share/jupyter
        /usr/local/share/jupyter
        /usr/share/jupyter
```
Which I believe may be the root cause.  I've built for dev and prod with only success messages and taken careful note of all instructions... but it's possible I've missed a prerequisite?  

## Reproduce

Simply create a new notebook and then select "Print" from the "File" menu.

**Comment by jtpio** [comment]
Thanks @rfox12 for trying out the 4.0 alpha release.

Which version of `nbconvert` are you using?

**Comment by rfox12** [comment]
I suspect if nbconvert is the culprit then this is related... https://github.com/jupyterlab/jupyterlab/issues/11687

**Comment by fcollonval** [comment]
It may be related indeed because I successfully print a notebook with the same alpha version.

![image](https://user-images.githubusercontent.com/8435071/146204187-97b93022-ee39-4a48-ae3e-69fe7931a5aa.png)

**Comment by rfox12** [comment]
So... what's the proper way to install nbconvert with a local clone/build of JupyterLab?  When I do a `conda list` it already shows up as present.  I did a clean install on a brand new conda env (with only pyhthon=3).

**Comment by fcollonval** [comment]
Could you try forcing Python < 3.10? I have seen issue with conda package and Python 3.10. I tested successfully with JLab v4.0.0a17, nbconvert 6.3.0 and Python 3.9 on Debian 11.

**Comment by rfox12** [comment]
@fcollonval You're absolutely right.  I tried a clean install with python 3.9 this morning and "Print" works fine!  The "Save and Export Notebook As..." menu works fine as well.  I'm a little awestruck (like you pulled a rabbit out of the hat)... not sure I would have identified this root cause any time soon...
