### ISSUE TITLE
Server Error 500 when saving notebooks

### ISSUE THREAD

**Issue by tharwan** [jupyterlab/jupyterlab#11708]
## Description

We have a zero to jupyter Hub instance and recently the saving of notebooks stopped working for (almost) all users using the lab. Editing files via the shell or the notebook interface works just fine. 

We see an error in the Java script console. But without any more info.

Any ideas how to debug this? 

## Reproduce

we did not manage to reproduce outside of the hub installation. Also we have at least one user where things seem to be fine.

## Context

- Browser and version: various
- JupyterLab version: 3.2.5

**Comment by tharwan** [comment]
We tried to check the logs of the pods but could not find any corresponding log message showing a 500. Any log in particular that should be useful?

**Comment by tharwan** [comment]
So you mean we might be looking for a python traceback? We will try to look for it again tomorrow, but watching the logs while trying to save did not show anything except in the browser console.

**Comment by davidbrochart** [comment]
> So you mean we might be looking for a python traceback?

Yes, a `500` is an internal server error, usually caused by a Python runtime error.

**Comment by tharwan** [comment]
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/964241/146523177-73f23a08-6394-48c2-b807-a52252b056e4.png)

We only found this so far. Not sure if this is even related.

**Comment by davidbrochart** [comment]
`Removing route /user/florian kuhnlenz` doesn't look good, if you're requesting that user afterwards?

**Comment by tharwan** [comment]
yes that is during a session, so that should still be used.

**Comment by davidbrochart** [comment]
But isn't there a problem accessing a deleted user?

**Comment by tharwan** [comment]
I don’t know how the whole stack works here to be honest. We will try to work the logs some more. But since it is only the lab interface making problems I still believe the error is rooted there.

**Comment by tharwan** [comment]
We tried some more to see any error in the logs while performing a save but there is nothing where we are looking.

**Comment by tharwan** [comment]
The only other trace we see is in the browser console, but it is not really giving anything away either
<img width="750" alt="Screenshot 2021-12-17 at 15 43 37" src="https://user-images.githubusercontent.com/964241/146561494-46f3e491-3900-4e8a-b5a7-67e535430d87.png">

**Comment by tharwan** [comment]
The only other trace we could find is in the browser console. But it is not giving anything away either.
<img width="750" alt="Screenshot 2021-12-17 at 15 44 42" src="https://user-images.githubusercontent.com/964241/146561693-76603476-6b3b-43e4-947d-fc95301a50a3.png">
