### ISSUE TITLE
Autocomplete broken for console

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#11710]
## Description

I'm pretty sure autocomplete used to work in console as well. Now using tab adds a space.

## Reproduce
![ipython-autocomplete](https://user-images.githubusercontent.com/1813603/146465854-526fde37-0365-4b7e-a632-728bfb1e250a.gif)

## Expected behavior

Autocomplete works with tab press in console.

## Context

Lab@3.2.5

**Comment by echarles** [comment]
I have quickly tried on 3.1.0 and console autocomplete works well with the default builtin completer but does not work with LSP (which looks like the one you are showing @mlucool )

<img width="433" alt="Screenshot 2021-12-17 at 07 45 19" src="https://user-images.githubusercontent.com/226720/146501285-b3712cbc-5589-4ac2-bf41-79066280dbba.png">

<img width="817" alt="Screenshot 2021-12-17 at 07 55 04" src="https://user-images.githubusercontent.com/226720/146502460-1b117301-2e63-4a33-bd30-bbfe53e5db00.png">

**Comment by mlucool** [comment]
This seems unrelated to LSP. With a fresh install, I can see this works as expected with 3.2.0 and does not work with 3.2.5

**Comment by vosak** [comment]
I experience the same. I found a kinda annoying workaround - to switch to a different tab and back to the console, the completer then works until a command execution. The tab switch is needed after each command execution in the console.

**Comment by krassowski** [comment]
Thanks @vosak this is a useful observation.

It worked fine in 3.2.2 but it seems like it regressed in 3.2.3. This was a small release, and contained a bugfix related to completer (https://github.com/jupyterlab/jupyterlab/pull/11398), but we indeed did not add a test for console.

@dmonad could it be possible that we also need to make prompt cells creation y-js aware for the completer to work after the changes to `cursorActivity` event and/or mutex (note: the prompt cells are based on code cell; code cells in notebook are y-js aware and work fine; I wonder what is different about the prompt cells that they bail)? The relevant place in the code is:

https://github.com/jupyterlab/jupyterlab/blob/52e4ae9d959838023043853c66bfa5732513e263/packages/console/src/widget.ts#L588-L596

**Comment by echarles** [comment]
@dmonad I see you assigned this to you. We have been discussing with @krassowski on https://github.com/jupyterlab/jupyterlab/pull/11718#issuecomment-997196916 that we would need a fix before the 3.3. release planned somewhere end of January. Please ping me if you need help on this, and also happy to know about your progress.

**Comment by krassowski** [comment]
Strictly I hoped this could go to 3.2 :)

**Comment by fcollonval** [comment]
When working on https://github.com/jupyterlab/jupyterlab/pull/11450, I realize yesterday that the cursor activity event is indeed not emitted for the prompt cell (the visual impact I saw is the position of the cursor in the status bar that is not updating). So this confirms @krassowski comment.

**Comment by fcollonval** [comment]
@dmonad @echarles does one of you will have time to push a PR before the end of January to get it in 3.3?

**Comment by echarles** [comment]
@fcollonval Happy to take that over. For now I have not started as @dmonad has assigned the issue to himself, and I said I would wait on further feedback to avoid double work. Looping now to get @dmonad inputs.

**Comment by fcollonval** [comment]
Pinging @echarles @dmonad do any of you plan to address this one in the next 2 weeks to get it in 3.3?
