### ISSUE TITLE
Add setting for the cell margin in side-by-side layout mode

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#11719]
### Problem

The margin in side-by-side has been updated in https://github.com/jupyterlab/jupyterlab/pull/11539 but some users gave feedback that is was not like they wanted (too large number...).

It is difficult to have a number fitting all users requirements, all especially for different screens.

### Proposed Solution

Add a setting to allow the user change that value

**Comment by echarles** [comment]
Thinking a bit more to a potential implementation, the Lumino widget can add a class to a node, but I do not see how it can set style in a dynamic way. In other words, we don't have for now some kind of `css-in-js` functionality. Any pointer appreciated for ways to achieve this.

**Comment by krassowski** [comment]
Yes, it is not a pattern we utilise in core; https://github.com/deathbeds/jupyterlab-fonts do css-via-settings and we can always just have some categorical big/medium/small if we want to stay with class-based approach.

**Comment by echarles** [comment]
Introducing css-in-js is a initiative as such. We should stick to your `large/medium/small` approach.

Iterations will happen, maybe someone will ask for `x-large`and `x-small` on top. Are we going to use `%` or fixed units?

Maybe XL/L/M/S/XS with a fixed value increment between them.

**Comment by echarles** [comment]
Draft PR on https://github.com/jupyterlab/jupyterlab/pull/11880
