### ISSUE TITLE
CSS are loaded even for disabled extension

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#11728]
## Description

I ran into a css side-effect problem between an extension and a python module injecting html/css in notebook cells via repr. That specific problem was solved, but I wanted to find out how to deal with an extension conflict besides uninstalling it. It looks like disabled extensions can still have css loaded (appears in the DOM regardless of disabled or enabled). I wanted to check to see how a disabled extension is handled, whether it makes sense to prevent a disabled extension from importing anything, or if the only resolution is to uninstall. The context is a centrally managed Lab install where many extensions may exist, but users can choose to enable or disable specific extensions for themselves out of that set.

from @mlhenderson on [Gitter](https://gitter.im/jupyterlab/jupyterlab?at=61bbb163fd9244223e4b8744)

## Expected behavior

The styles are not loaded for disabled extensions.

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by fcollonval** [comment]
pinging @blink1073 @jasongrout that knows better the mechanism.

**Comment by blink1073** [comment]
iirc this is why we introduced the [`style/index.js`](https://github.com/jupyterlab/jupyterlab/blob/9ad40ceed4f74470f2ea1d99f12c883f8d460a16/packages/application/style/index.js) pattern, cf https://github.com/jupyterlab/jupyterlab/pull/9407

**Comment by jasongrout** [comment]
The `style/index.js` pattern was to work around recent changes in css-loader where css was not being deduplicated.

I'm not sure why disabled plugins are having css loaded. I wouldn't expect that.

**Comment by jtpio** [comment]
Another idea could be that the module is first created here:

https://github.com/jupyterlab/jupyterlab/blob/9ad40ceed4f74470f2ea1d99f12c883f8d460a16/dev_mode/index.js#L95

Before checking for `disabledExtensions` here: 

https://github.com/jupyterlab/jupyterlab/blob/9ad40ceed4f74470f2ea1d99f12c883f8d460a16/dev_mode/index.js#L181-L183

**Comment by jtpio** [comment]
> Another idea could be that the module is first created here:

Correction: federated styles are handled here:

https://github.com/jupyterlab/jupyterlab/blob/4ee00194f263a7f729b1607e64c6efbf8a012545/dev_mode/index.js#L83-L85

This is reproducible with a simple federated extension that adds the following CSS:

```css
#jp-topbar-spacer {
  background: blue;
}
```

![image](https://user-images.githubusercontent.com/591645/151797973-e33237e9-4fc4-4032-8c6e-faeb0188dd0d.png)
