### ISSUE TITLE
Special characters appear incorrectly in file panel

### ISSUE THREAD

**Issue by prhbrt** [jupyterlab/jupyterlab#11721]
## Description

Special characters aren't shown properly in the left filepanel.

![image](https://user-images.githubusercontent.com/7011110/146656012-ce922fb4-3258-4c5a-8c13-dfc0b2a8f68e.png)

## Reproduce

Create a file or folder with special characters, browse there via the panel.

    mkdir -p 'test/special_châracters'

Using the developer console, it seems the encoding error comes from the server, that is when I explicitly decode, unicode-escapes appear properly in the raw JSON-text, which then decode to the wrong unicode characters.

    fetch("/user/username/api/contents/test", {
      "headers": {
        "accept": "*/*",
        "accept-language": "en-US,en;q=0.9,nl;q=0.8",
        "content-type": "application/json",
      },
      "method": "GET",
    }).then(response => { response.blob().then(body => body.arrayBuffer().then(blob => {window.iamlazy = JSON.parse((new TextDecoder('UTF-8')).decode(blob));}))});

    window.iamlazy.content[0]['name']
    'special_chÃ¢racters'

## Expected behavior

To show special characters properly.

## Context

- Operating System and version: Ubuntu 20.04 (server and client)
- Browser and version: Google Chrome 96.0.4664.93 (Official Build) (64-bit)
- JupyterLab version: 3.2.5

**Comment by krassowski** [comment]
Thanks for reporting @prhbrt. Could you please provide the output of `jupyter --version`? I could not reproduce this issue on binder using:

```
$ jupyter --version
Selected Jupyter core packages...
IPython          : 7.29.0
ipykernel        : 6.5.0
ipywidgets       : 7.6.3
jupyter_client   : 7.0.6
jupyter_core     : 4.9.1
jupyter_server   : 1.11.2
jupyterlab       : 3.2.5
nbclient         : 0.5.9
nbconvert        : 6.0.7
nbformat         : 5.1.3
notebook         : 6.3.0
qtconsole        : not installed
traitlets        : 5.1.1
```

and JupyterLab version: 3.2.5. Also, could you please share what [locale environment variables](https://help.ubuntu.com/community/EnvironmentVariables#Locale_setting_variables) you have set and to what? You can do so with two commands:

```
printenv | grep LC_
# and
echo $LANG
```

![Screenshot from 2021-12-19 16-40-58](https://user-images.githubusercontent.com/5832902/146683258-ce7f3583-7fb5-4b95-93d1-686bf3ddcd19.png)

**Comment by JasonWeill** [comment]
No longer happening in Lab 4.1.0; `special_chåracters` renders correctly in the file browser.
