### ISSUE TITLE
Why is there a second plot in the animation?

### ISSUE THREAD

**Issue by husnoo** [jupyterlab/jupyterlab#11729]
Hi,

I'm trying to animate a plot in Jupyterlab - it works but shows a second plot with the last frame. This is identical to the image below. How do I hide the second plot?

thanks,

Nawal

```
# https://github.com/jupyterlab/jupyterlab/issues/4492#issue-318735972
#%matplotlib inline
import orbits

import numpy as np
import matplotlib.pyplot as plt

from matplotlib import animation, rc
from IPython.display import HTML

# First set up the figure, the axis, and the plot element we want to animate
fig, ax = plt.subplots()

ax.set_xlim(( 0, 2))
ax.set_ylim((-2, 2))

line, = ax.plot([], [], lw=2)

# initialization function: plot the background of each frame
def init():
    line.set_data([], [])
    return (line,)

# animation function. This is called sequentially
def animate(i):
    x = np.linspace(0, 2, 1000)
    y = np.sin(2 * np.pi * (x - 0.1 * i))
    line.set_data(x, y)
    return (line,)

### call the animator. blit=True means only re-draw the parts that have changed.
anim = animation.FuncAnimation(fig, animate, init_func=init,
                               frames=10, interval=100, blit=True)

# equivalent to rcParams['animation.html'] = 'html5'
#rc('animation', html='jshtml')
#rc
HTML(anim.to_jshtml())

```

-------- original post------
In JLab 2.1.4, I now get what appears to be the same output and functionality as Jupyter Notebook:

<img width="434" alt="Screen Shot 2020-06-04 at 9 25 30 AM" src="https://user-images.githubusercontent.com/192614/83784731-67a45a80-a645-11ea-8691-987b04f6de9b.png">

_Originally posted by @jasongrout in https://github.com/jupyterlab/jupyterlab/issues/4492#issuecomment-638964257_

**Comment by husnoo** [comment]
Maybe this is helpful - adding the magic
```
%matplotlib notebook
```

causes the error to appear:
```
Javascript Error: IPython is not defined
```
but then it shows just the animation as I would hope. So maybe there's some way to disable the "echo" static image, while keeping the animation and not showing an error?

**Comment by timhoffm** [comment]
All figure objects created in a cell, but not explicitly shown (via `plt.show()`) are automatically shown when the cell is executed. `anim.to_jshtml()` uses the figure, but does not count as showing (similar to `savefig()`). To prevent the extra plot, close the Figure in the same cell using `plt.close()`.

---

The issue can be closed based on above explanation.

**Comment by krassowski** [comment]
Thank you for providing the explanation and a solution, it is really appreciated! Closing this issue as suggested.

For anyone reading this in the future: if you have further questions relating to the above, generic programming Q&A sites might get you an answer faster. If you think you found a bug in matplotlib and can reproduce it in both JupyterLab and in another interface (e.g. Jupyter Notebook) it is likely unrelated to JupyterLab itself and it is more productive to report it in matplotlib repository or ipympl (in case of interactive use) following the matplotlib issue reporting guidelines.
