### ISSUE TITLE
Unable to run 'jupyter lab build' with jupyterlab 3.2.5, previous 3.2.4 was working fine

### ISSUE THREAD

**Issue by tlvu** [jupyterlab/jupyterlab#11726]
## Description

`jupyter lab build` result in error 
```
[3/5] Fetching packages...
warning @blueprintjs/core@3.52.0: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
warning @blueprintjs/core@3.52.0: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
error @npmcli/fs@1.1.0: The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || >=16". Got "14.8.0"
error Found incompatible module.
```

I have another env with `nodejs 15.14.0`, same error.

`jupyterlab 3.2.4` was able to run that command fine.

## Reproduce

1. `mamba create -n testjupyterlabbuild jupyterlab=3.2.5 jupyterhub` # gives nodejs=14.8.0
2. `conda activate testjupyterlabbuild`
3. `jupyter lab build`  # fails
4. `mamba install jupyterlab=3.2.4`  # downgrade
5. `jupyter lab build`  # works

## Reproduce using docker to ensure clean environment

Dockerfile:
```dockerfile
FROM continuumio/miniconda3

# conda=4.11.0=py39h06a4308_0
# mamba=0.19.1=py39hfa8f2c8_0
RUN conda update conda -n base && \
    conda install mamba -n base -c defaults -c conda-forge

# jupyterlab=3.2.5=pyhd8ed1ab_0
# jupyterhub=2.0.0=pyhd3eb1b0_0
# nodejs=14.8.0=hda19d22_0
RUN mamba create -n testjupyterlabbuild -c defaults -c conda-forge jupyterlab=3.2.5 jupyterhub

RUN conda env export -n testjupyterlabbuild > /env-testjupyterlabbuild.yml.txt && \ 
    conda env export -n base > /env-base.yml.txt

RUN conda run -n testjupyterlabbuild jupyter lab build
```
[env-base.yml.txt](https://github.com/jupyterlab/jupyterlab/files/7756351/env-base.yml.txt)
[env-testjupyterlabbuild.yml.txt](https://github.com/jupyterlab/jupyterlab/files/7756352/env-testjupyterlabbuild.yml.txt)

Edit:
* add reproducible steps using docker to ensure clean test environment

**Comment by davidbrochart** [comment]
For me `mamba create -n testjupyterlabbuild jupyterlab=3.2.5 jupyterhub` installs `nodejs=17.1.0`, and `jupyter lab build` works.
After `mamba install nodejs=14.8.0`, `jupyter lab build` fails.
Are you sure your root conda environment is (almost) empty? You shouldn't install anything in the root env, except for `mamba` if you don't use mamba-forge already.

**Comment by tlvu** [comment]
> Are you sure your root conda environment is (almost) empty? You shouldn't install anything in the root env, except for `mamba` if you don't use mamba-forge already.

@davidbrochart good point.

I retested in a Dockerfile to be 100% sure the environment is clean.  See update to this issue description.

**Comment by davidbrochart** [comment]
What if you install `nodejs=17.1.0`?

**Comment by krassowski** [comment]
1. Why do you run `jupyter lab build`? Is it necessary?
2. The issue steams from the specified channel priorities: the `defaults` channel from anaconda has an outdated `nodejs` version (14.8.0) which you should not use; the `conda-forge` channel has the latest 14.x version (`14.17.4`). Our [installation instructions](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#installation) do not include `-c defaults` but you have it in your `mamba create` line.

**Comment by tlvu** [comment]
> What if you install `nodejs=17.1.0`?

Was thinking exactly the same thing, force `nodejs=17.1.0` in the Dockerfile.

Trying it now ...

**Comment by tlvu** [comment]
> 1. Why do you run `jupyter lab build`? Is it necessary?
> 

@krassowski 

This screenshot seems to tell me I need `jupyter lab build` ?

![Screenshot from 2021-12-21 10-47-01](https://user-images.githubusercontent.com/11966697/146959076-73254106-bd21-4a04-a3d3-47e09074f1ba.png)

You can try it yourself, this is docker image `pavics/workflow-tests:211220-dev-commit-5d3c259-7-downgrade-jupyterhub-jupyterlab-jupyter-lab`

Previous build that had `jupyterlab 3.2.4` that worked: `pavics/workflow-tests:211123-update211216`

But the **real reason** I am really trying to get `jupyter lab build` to work is because I am no longer able to launch the newly build Jupyter image from JupyterHub, I get this

![Screenshot from 2021-12-21 10-48-42](https://user-images.githubusercontent.com/11966697/146959588-81c7404c-c8ff-44b0-85dc-e014b6d86d3b.png)

Is this problem even related to `jupyter lab build`?

Our JupyterHub config: https://github.com/bird-house/birdhouse-deploy/blob/0329715a6f6ee81f5435257c98ea5b8eaee8acc1/birdhouse/config/jupyterhub/jupyterhub_config.py.template

The JupyterHub is part of our docker-compose stack: https://github.com/bird-house/birdhouse-deploy/blob/0329715a6f6ee81f5435257c98ea5b8eaee8acc1/birdhouse/docker-compose.yml


>  2. The issue steams from the specified channel priorities: the `defaults` channel from anaconda has an outdated `nodejs` version (14.8.0) which you should not use; the `conda-forge` channel has the latest 14.x version (`14.17.4`). Our [installation instructions](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#installation) do not include `-c defaults` but you have it in your `mamba create` line.

We build our Jupyter env together with a much of other librairies so `conda-forge` and `defaults` channel is part of the same `environment.yml`, see https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/blob/8b18c96802421e08465de6c7e30b4529b84308af/docker/environment.yml and the corresponding Dockerfile https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/blob/8b18c96802421e08465de6c7e30b4529b84308af/docker/Dockerfile

**Comment by tlvu** [comment]
> > What if you install `nodejs=17.1.0`?
> 
> Was thinking exactly the same thing, force `nodejs=17.1.0` in the Dockerfile.

@davidbrochart 

Forcing install of `nodejs=17.1.0` worked and `jupyter lab build` worked.

Will try if it solves my problem with the redirect between JupyterHub and the JupyterLab (in a separate docker container as we use the DockerSpawner).

**Comment by tlvu** [comment]
By the way, this fairly gigantic jupyterlab environment is used by our project https://pavics.ouranos.ca/ so that is the reason why we had to install so so much stuff in there.

**Comment by krassowski** [comment]
> We build our Jupyter env together with a much of other librairies so conda-forge and defaults channel is part of the same environment

you can keep both but the **priorities** are important. When you run:

```
mamba create -n testjupyterlabbuild -c defaults -c conda-forge jupyterlab=3.2.5 jupyterhub
```

you tell mamba that you want the `defaults` channel to have a higher priority than `conda-forge` (see [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/channels.html#specifying-channels-when-installing-packages): *Priority decreases from left to right - the first argument is higher priority than the second.*); in my experience it is almost always a bad idea to have defaults abouve conda-forge (because `conda-forge` is usually more up to date) and `conda-forge` specifically instructs users to set its chanel as the highest priority (see https://conda-forge.org/docs/user/introduction.html).

Instead you could try:

```
mamba create -n testjupyterlabbuild -c conda-forge -c defaults jupyterlab=3.2.5 jupyterhub
```

which should solve your problem without pining Node.js version (but if you pin I would use `>=` to get security patches).

> This screenshot seems to tell me I need jupyter lab build ?

With JupyterLab 3.x you can almost always avoid `jupyter lab build` and installing of Node.js altogether thanks to [prebuilt extensions](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#id12), but here the dialog you highlight seems to be coming from [`jupyterlab-dash`](https://github.com/plotly/jupyterlab-dash) or more likely [`jupyter-dash`](https://github.com/plotly/jupyter-dash); sadly they have not upgraded to prebuilt extensions yet (https://github.com/plotly/jupyter-dash/issues/49), so indeed it requires rebuilding lab.

**Comment by tlvu** [comment]
> > We build our Jupyter env together with a much of other librairies so conda-forge and defaults channel is part of the same environment
> 
> you can keep both but the **priorities** are important.

@krassowski You are right.  I got the sequence reversed on the command line.  But it was just to reproduce the problem.  It's not how we perform our production build.

The production build uses our `environment.yml` file, is this sequence correct:
https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/blob/8b18c96802421e08465de6c7e30b4529b84308af/docker/environment.yml#L3-L8
```yml
channels:
  - conda-forge
  - cdat
  - bokeh
  - plotly  # for jupyter-dash
  - defaults
```

> With JupyterLab 3.x you can almost always avoid `jupyter lab build` and installing of Node.js altogether thanks to [prebuilt extensions](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#id12), but here the dialog you highlight seems to be coming from [`jupyterlab-dash`](https://github.com/plotly/jupyterlab-dash) or more likely [`jupyter-dash`](https://github.com/plotly/jupyter-dash); sadly they have not upgraded to prebuilt extensions yet ([plotly/jupyter-dash#49](https://github.com/plotly/jupyter-dash/issues/49)), so indeed it requires rebuilding lab.

Added a commit https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/ca17d14aa95d06ff6a22f21e0df119358e3c814f for reminder, thanks !

**Comment by tlvu** [comment]
> Forcing install of `nodejs=17.1.0` worked and `jupyter lab build` worked.
> 
> Will try if it solves my problem with the redirect between JupyterHub and the JupyterLab (in a separate docker container as we use the DockerSpawner).

Oh geez tried `mamba install "nodejs>=17.1.0" -c conda-forge -n birdy` into my big conda env result in this error:
```
package nodejs-17.1.0-h8ca31f7_1 requires icu >=69.1,<70.0a0, but none of the providers can be installed
```

So I tried `mamba install "nodejs>=16.0" -c conda-forge -n birdy` and I ended up with some serious downgrade:
```
  Updating specs:

   - nodejs[version='>=16.0']
   - ca-certificates
   - certifi
   - openssl


  Package                    Version  Build              Channel                    Size
──────────────────────────────────────────────────────────────────────────────────────────
  Upgrade:
──────────────────────────────────────────────────────────────────────────────────────────

  - libuv                     1.41.1  h7f98852_0         installed
  + libuv                     1.42.0  h7f98852_0         conda-forge/linux-64       1 MB
  - nodejs                   15.14.0  h92b4a50_0         installed
  + nodejs                   16.12.0  h92b4a50_0         conda-forge/linux-64      15 MB

  Downgrade:
──────────────────────────────────────────────────────────────────────────────────────────

  - configurable-http-proxy    4.5.0  node15_he6ea98c_1  installed
  + configurable-http-proxy    1.3.0  0                  conda-forge/linux-64     233 KB
  - jupyterhub                 2.0.0  hd8ed1ab_0         installed
  + jupyterhub                 1.3.0  py37h89c1867_0     conda-forge/linux-64       5 KB
  - jupyterhub-base            2.0.0  pyhd8ed1ab_0       installed
  + jupyterhub-base            1.3.0  py37h89c1867_0     conda-forge/linux-64       2 MB

  Summary:

  Upgrade: 2 packages
  Downgrade: 3 packages

  Total download: 18 MB
```

I'll take the downgrade and see where it goes.

**Comment by tlvu** [comment]
Forcing `nodejs>=16.0` in my conda env resolve this `jupyter lab build` issue.  Closing.
