### ISSUE TITLE
Check jupyterlab/jupyterlab_apod

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#11724]
This is a reminder issue to check https://github.com/jupyterlab/jupyterlab_apod is up to date with JupyterLab v4.

In particular, the following issues need to be addressed:
- https://github.com/jupyterlab/jupyterlab_apod/issues/10

**Comment by jtpio** [comment]
Was this addressed as part of https://github.com/jupyterlab/jupyterlab/pull/13593?

Or should we keep it open for another pass before the 4.0 final release?
