### ISSUE TITLE
How to set username in collaborative edition mode

### ISSUE THREAD

**Issue by dbeniamine** [jupyterlab/jupyterlab#11745]
Hi,

I am testing jupyterlab collaborative mode in an application that we are developing, first of all : congratulation it's awesome !!!!

Second I have a question when two user edit the same notebook they each see the other one as an anonymous, but they are accessing jupyterlab from an application on which they are logged.

Is it, or would it be possible for the application (that acts as a reverse proxy) to transmit to jupyter there username ?

For instanct by sending them to `/jupyter/lab?user=foo` for the first and `/jupyter/lab?user=bar` so that they see the names `foo` and `bar` on the cursors ?

Best regards and again congratulation for all of your work !

**Comment by krassowski** [comment]
Yes, it's `username`, so something like `?token=<your token>&username=Alice` should work for now (since #10411 included in 3.1 and probably until 4.0 where it might change to a better solution), the final behaviour is still being worked out - feedback is warmly welcome!

**Comment by krassowski** [comment]
In particular, the following discussions would benefit from feedback (leaving a thumbs up for the preferred solution, and/or leaving a comment if the preferred solution is not there is very welcome):
- https://github.com/jupyterlab/jupyterlab/issues/10119
- https://github.com/jupyterlab/jupyterlab/issues/10577
- https://github.com/jupyterlab/jupyterlab/issues/11657
- https://github.com/jupyterlab/jupyterlab/issues/11528
- https://github.com/jupyterlab/jupyterlab/issues/10765
- https://github.com/jupyterlab/jupyterlab/issues/11678 (this is a bit technical, but also important for use cases like yours)

**Comment by dbeniamine** [comment]
Works fine thanks a lot !

I'll take a look at the issues you mentioned
