### ISSUE TITLE
how to debug the source code of the jupyterlab

### ISSUE THREAD

**Issue by pklcoder** [jupyterlab/jupyterlab#11749]
I want to debug the source code of the jupyterlab ,but i do not konw how to do after run the  jupyterlab\jupyterlab\__main__.py in debug pattern.

for example:
1>i want to debug the function to download a file .
 i do not know how to send a url in browser request to download a file ? what is the right url?

2>i want to debug the login function but i do not know how to request the url in the browser ? what is the right url?

who can tell me how to debug the souce code ,thanks

**Comment by fcollonval** [comment]
The JupyterLab server has its API defines from
- `jupyterlab_server` : [REST API](https://jupyterlab-server.readthedocs.io/en/stable/api/rest.html)
- `jupyter_server` (base server): [REST API](https://jupyter-server.readthedocs.io/en/stable/developers/rest-api.html)

> This is only valid for default installation. If you add server extensions, they are likely to add new endpoints to the API.
