### ISSUE TITLE
How internationalize JupyterLab notebooks?

### ISSUE THREAD

**Issue by stefaneidelloth** [jupyterlab/jupyterlab#11753]
I would like to create some notebooks that are able to handle multiple languages, e.g. generate plots in German and English.

Python includes some build in features for internationalization and I tried to use gettext from within JupyterLab notebooks.
However, it does not seem to be that easy to extract translatable strings from JupyterLab notebooks. The console tool xgettext.exe does not work on *.ipynb files. Also see:

https://stackoverflow.com/questions/70504927/jupyterlab-i18next-how-to-extract-i18next-translatable-strings-from-jupyterlab

**=> What is the recommended way to use i18next in JupyterLab notebooks?**

JupyterLab already seems to use i18next for its user interface:
https://github.com/jupyterlab/jupyterlab/issues/3965

Maybe there is some JupyterLab extension that helps with using i18next? Or some nbconvert option?

**Comment by fcollonval** [comment]
As you mention, the major trouble is to be able to extract the translatable strings. All tools for doing that are parsing the file as plain text and look for some pattern to extract the wanted strings. To translate the JupyterLab interface, translatable strings are either in Python files (for the server), in TypeScript files (for the interface) and in JSON (for settings title and description). There is no need (and therefore no tool) to extract string from the notebook format in core JupyterLab.

Except for JSON settings files, we rely on existing tool like babel. For the JSON settings files, we are doing the extraction _manually_ in

https://github.com/jupyterlab/jupyterlab-translate/blob/5fbd2350bef754e77548da76822802c170a02c63/jupyterlab_translate/utils.py#L331

We use the Python library `polib` to manipulate POT files and extract meaningful keys from the parsed JSON files.

So I would say if you are interested in translatable strings only in code cells, your suggestion in SO to convert the notebook to Python files and extract the strings from the script is the best approach. If you are interested in extracting the Markdown cells too, I would encourage you to combine the code extraction process with the direct parsing of the notebook file to generate an unique POT file.

That said for Markdown cells, you will also need to figure out how to translate the string in the final interface.

**Comment by stefaneidelloth** [comment]
Thank you. Code cells are enough for me. I finally decided to 
manually create and edit *.yml based translation files and use 
https://pypi.org/project/python-i18n/ 
instead of the complex python "build-in" workflow that seems to 
be based on old tools and forces me to use binary *.mo translation files.

Example translation file translations.yml:

```
en_US:
    hello world: Hello World!
    hello: Hello %{name}!
    
de_DE:
    hello world: Hallo Welt!
    hello: Hallo %{name}!
```
    
Example config/import:

```
import i18n
from i18n import t
i18n.set('available_locales', ['en_US','de_DE'])
i18n.set('fallback', 'en_US')
i18n.set('locale', 'en_US')
i18n.set('error_on_missing_translation', True)
i18n.set('error_on_missing_placeholder', True)
i18n.set('filename_format', 'translations.{format}')
i18n.load_path.append('./')
```

Example usage:

`t('hello world')`

`t('hello', name='Bob')`
