### ISSUE TITLE
Check the application includes the plugin and is activated before reconciling settings

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#11754]
## Description

At the moment settings for a plugin seem to be picked up even if the plugin is not loaded on the page.

This also seems to be the case when a plugin is loaded but fails to activate.

## Reproduce

This can be reproduced by creating a new prebuilt extension with settings from the cookiecutter:

1. `cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts`
2. answer `y` to `has_settings`
3. do the dev setup
4. edit `schema/plugin.json` with the following:

```json
{
  "jupyter.lab.shortcuts": [
    {
      "command": "documentsearch:start",
      "keys": ["Accel F"],
      "selector": ".jp-mod-searchable",
      "disabled": true
    }
  ],
  "title": "myextension",
  "description": "myextension settings.",
  "type": "object",
  "properties": {},
  "additionalProperties": false
}
```
5. edit the plugin definition to `require` a token not available in JupyterLab, for example:

```ts
import {
  JupyterFrontEnd,
  JupyterFrontEndPlugin
} from '@jupyterlab/application';

import { IRetroShell } from '@retrolab/application';

import { ISettingRegistry } from '@jupyterlab/settingregistry';

/**
 * Initialization data for the myextension extension.
 */
const plugin: JupyterFrontEndPlugin<void> = {
  id: 'myextension:plugin',
  autoStart: true,
  requires: [IRetroShell],
  optional: [ISettingRegistry],
  activate: (app: JupyterFrontEnd, shell: IRetroShell, settingRegistry: ISettingRegistry | null) => {
    console.log('JupyterLab extension myextension is activated!');

    if (settingRegistry) {
      settingRegistry
        .load(plugin.id)
        .then(settings => {
          console.log('myextension settings loaded:', settings.composite);
        })
        .catch(reason => {
          console.error('Failed to load settings for myextension.', reason);
        });
    }
  }
};

export default plugin;
```
6. rebuild the extension and check the shortcuts in the Advanced Settings editor:

![image](https://user-images.githubusercontent.com/591645/147553340-742f9256-9636-4260-8a9b-f299f103794b.png)

## Expected behavior

The settings for a given plugin should not be picked up if the plugin is not loaded on the page or failed to activate.

Maybe the plugin should checked with `app.hasPlugin(pluginId)` before reconciling its settings?

## Context

This was first noticed in https://github.com/jupyterlab/retrolab/pull/294#issuecomment-1000868849, which tries to disable a shortcut via a plugin that should only be loaded in RetroLab.

**Comment by jtpio** [comment]
> Maybe the plugin should checked with `app.hasPlugin(pluginId)` before reconciling its settings?


Looks like there might not be a convenient way to know if a given plugin is activated, based on this logic in Galata which accesses the private `app._pluginMap` Lumino attribute:

https://github.com/jupyterlab/jupyterlab/blob/9ad40ceed4f74470f2ea1d99f12c883f8d460a16/galata/src/inpage/index.ts#L50-L66

Although the `app.hasPlugin()` check should already help with the case of RetroLab plugins only loaded in RetroLab.

**Comment by jtpio** [comment]
Adding to 4.0 for consideration.

**Comment by fcollonval** [comment]
I would lean towards filtering the settings in the backend (in the settings REST API get) rather than in the frontend.

**Comment by jtpio** [comment]
Hitting that one too when trying to customize the RetroLab menu items via the settings in https://github.com/jupyterlab/retrolab/pull/328.

Linking to where the settings are retrieved in `jupyterlab_server` for reference: https://github.com/jupyterlab/jupyterlab_server/blob/main/jupyterlab_server/settings_utils.py

In particular: https://github.com/jupyterlab/jupyterlab_server/blob/dac0a55165891fd7b29ea6c4a29820dbbdfb290a/jupyterlab_server/settings_utils.py#L150-L152

**Comment by jtpio** [comment]
> I would lean towards filtering the settings in the backend (in the settings REST API get) rather than in the frontend.

At first glance adding a frontend check sounds more flexible, for example in the case of (federated) `disabledExtensions` and JupyterLite (but to be confirmed).
