### ISSUE TITLE
Use websockets/SSE for receiving backend changes

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#11789]
### Problem

JupyterLab constantly polls the server to retrieve information about:
- files and directories (`contents` API)
- running terminals (`terminals` API)
- running notebooks (`sessions` API)
- running kernels (`kernels` API)

### Proposed Solution

Would it make sense to use websockets or SSE, so that the client gets the information when it changes, without asking for it at regular intervals?
I know it's a major change in the API, and it would be more complicated, I'm just wondering if there would be an interest in that.

**Comment by timkpaine** [comment]
Just remember that for SSE, your browser has a max number of concurrent HTTP connections so you don't want to keep long open http connections. e.g. if you did all 4 listed here on separate http requests naively, your browser would only be able to open jupyterlab tab

**Comment by davidbrochart** [comment]
Thanks, I don't know much about SSE, except that they are unidirectional (I think?), which would be more suited here.
I guess with these low-level protocols one difficulty would be data validation, e.g. there's no equivalent of FastAPI for websockets.

**Comment by davidbrochart** [comment]
I think using GraphQL would be a solution.

**Comment by davidbrochart** [comment]
I think the [Jupyter event system](https://github.com/jupyter-server/jupyter_server/issues/780) could serve this purpose.
