### ISSUE TITLE
Cursor activity event is not fired on console prompt 

### ISSUE THREAD

**Issue by trungleduc** [jupyterlab/jupyterlab#11787]
## Description

In a code mirror editor, when users are typing, a `cursorActivity` event is fired on every change, the logic to handle this event is moved from `CodeMirror` to `YJs` in #11398  [(packages/codemirror/src/editor.ts)](https://github.com/jupyterlab/jupyterlab/pull/11398/files#diff-9705cdaacb4660fc2de7eaabf424d6c24b672acc499292fec723a779be32fbc7)

Since then, it works well in notebook cells, but this event is not fired anymore on the console prompt. The completer depends on this event to activate/deactivate the command so the code completion in the console prompt does not work correctly. 

**Lab 3.2.2**

![lab3-2-2](https://user-images.githubusercontent.com/4451292/148200695-e167f39a-7a19-4458-b070-684b4431ce81.gif)

**Lab 3.2.5**

![lab3-2-5](https://user-images.githubusercontent.com/4451292/148200731-0ce860b8-3098-4232-856d-e0e45f9c8c4b.gif)

## Reproduce

Log something in this  `_onCursorActivity`  method and compare between a notebook cell and a console prompt. 

https://github.com/jupyterlab/jupyterlab/blob/a1a68d1f85187ad18dead613898efc545f347b08/packages/codemirror/src/editor.ts#L880-L887

## Expected behavior

`_onCursorActivity` is called in all contexts.

## Context

`JupyterLab >=3.2.3`

**Comment by trungleduc** [comment]
@dmonad @hbcarlos I tried to fix it but have no clue.

**Comment by hbcarlos** [comment]
Hey @trungleduc, thank you so much for debugging it.

I haven't looked at it yet, and I'm also lost. Anyway, this issue could be related to https://github.com/jupyterlab/jupyterlab/pull/11398.

Btw, this issue was already tracked here https://github.com/jupyterlab/jupyterlab/issues/11710.

**Comment by trungleduc** [comment]
Ah sorry, I did not search for it before submitting this issue.
