### ISSUE TITLE
Allow for notebooks without an active kernel

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#1178]
I had a conversation at the MSDSE summit where a user asked about the ability to edit a notebook without a kernel running. Her use case involved wanting to edit the markdown in a notebook in collaboration with a student, even if on a computer without the appropriate development environment. This would also be useful for realtime-collab, since we want the ability to bring a collaborator into a shared document without giving them code-execution privileges. 

I talked briefly about this with @Carreau and @fperez , where the idea of "no-op" or "echo" kernels came up, but just having no kernel is probably simpler and closer to the desired use-case.

**Comment by jasongrout** [comment]
Definitely +1. We shouldn't need a kernel to view or edit a notebook.

**Comment by jasongrout** [comment]
(note that we start up a kernel by default for compatibility with the current notebook behavior, so we'd need to decide how to have the user specify that no kernel is desired.
