### ISSUE TITLE
Update TypeDoc theme.

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyterlab#11788]
### Problem
In #11707 we updated TypeDoc to v0.22.10 to support TypeScript v4.5. In v0.22 typedoc drop support to create custom themes using Handlebars because of performance and other issues, see [CHANGELOG](https://github.com/TypeStrong/typedoc/releases?page=2). In JupyterLab, we used a custom theme to add an extra filter checkbox (see image) and solve other issues with typedoc themes. In #11707, we removed the custom theme when updating to the latest typedoc, and we are using the default theme from typedoc.

![JupyterLab-API-Docs-Header](https://user-images.githubusercontent.com/26092748/148207989-8b7a0f7e-8397-4e85-a928-d2fa1698b1d4.jpg)

In the latest typedoc, to create a custom theme, we need to create a TypeScript plugin for typedoc. As I commented [here](https://github.com/jupyterlab/jupyterlab/pull/11707#issuecomment-998746227), there are some issues when building the JupyterLab API docs with a new plugin for the theme.

The question is, do we need a custom theme for the API docs?

**Comment by jtpio** [comment]
Closing as per @fcollonval's comment: https://github.com/jupyterlab/jupyterlab/pull/16140#issuecomment-2050146708
