### ISSUE TITLE
Trailing slash in GET /lab/api/translations/

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#11780]
## Description

I can see that the `GET /lab/api/translations/` request has a trailing slash. This doesn't seem to be a problem, but I don't see a reason for this.

## Reproduce

1. Launch JupyterLab
2. Open the network monitor in the browser
3. See a GET request at e.g. `/lab/api/translations/?1641288026431=`

## Expected behavior

There is not need to have a trailing slash.

## Context

- Operating System and version: Linux Ubuntu 21.04
- Browser and version: Firefox 95.0.1
- JupyterLab version: 3.2.5

**Comment by jtpio** [comment]
Thanks @davidbrochart.

Probably this is coming from `jupyterlab_server`?

https://github.com/jupyterlab/jupyterlab_server/blob/788e118e25cd7ad29a3041767201a0e3f66ba28e/jupyterlab_server/config.py#L291-L293

**Comment by davidbrochart** [comment]
I don't think so, because I can see it in Jupyverse too, and the translation endpoint in the config doesn't have the trailing slash there.
