### ISSUE TITLE
JupyterLab(v3.2.5) components (examples/notebook)  ipywidgets not showing

### ISSUE THREAD

**Issue by iamyuchen** [jupyterlab/jupyterlab#11792]
When I use JupyterLab(v3.2.5) components (examples/notebook) , I met a problem。

I clone jupyterlab repo, from root directory run the component by 
`cd examples/notebook`
`npm install `
`npm run build `
`python main.py`

the brower open address http://localhost:8888/example,

then enter the code to run
_import ipywidgets
out = ipywidgets.Dropdown(options=['1', '2', '3'], value='2', description='Number')
display(out)_

the cell didn't show the dropdown ui, only show the output 'Dropdown(description='Number', index=1, options=('1', '2', '3'), value='2')', and the console print errors 'Exception opening new comm'
![image](https://user-images.githubusercontent.com/11264714/148365579-1b07565c-9eae-40f8-b18a-08b228c89c9d.png)
![image](https://user-images.githubusercontent.com/11264714/148365730-b5cc8ea9-30ed-4dcd-935c-79b659b4ea7a.png)

I have install @jupyter-widgets/jupyterlab-manager already by 
`$ jupyter labextension install @jupyter-widgets/jupyterlab-manager`

command 'jupyter labextension list' output is as below
![image](https://user-images.githubusercontent.com/11264714/148316947-3cd4c2c1-7990-4b99-a7d3-fb9bcddb140b.png)

by the way, when I run `jupyter lab --dev-mode` command to start jupyter hub, and run the code above, the output and error info are the same.
![image](https://user-images.githubusercontent.com/11264714/148366826-8d436f44-3313-476b-a6fc-4f59d4b4e15a.png)

![image](https://user-images.githubusercontent.com/11264714/148366712-bd4f65ac-8d79-49ef-a992-37e5c5bab587.png)

but when I run  jupyter hub by `jupyter lab`, the code works fine.
![image](https://user-images.githubusercontent.com/11264714/148375793-4bebb61a-bf9a-4a76-ae57-b61c375d01f1.png)

It seems extensions did not take effect in example components, how can I fix the problem? thx~

**Comment by fcollonval** [comment]
Thanks for reaching out.

The examples provided within this repository are highly simplified standalone application. The `example/notebook` in particular does not have the ability to load extensions. Hence you are not seeing the rich display. Using `jupyter labextension` cli won't help as it only works with JupyterLab not the examples.

About the dev mode behavior, by default in dev mode all third-party extensions are ignored (as that mode is mainly for JupyterLab core developers). However if you do want to activate extensions in that mode, you will need to set an additional option when starting JupyterLab:

```
jupyter lab --dev-mode --extensions-in-dev-mode
```

**Comment by iamyuchen** [comment]
> Thanks for reaching out.
> 
> The examples provided within this repository are highly simplified standalone application. The `example/notebook` in particular does not have the ability to load extensions. Hence you are not seeing the rich display. Using `jupyter labextension` cli won't help as it only works with JupyterLab not the examples.
> 
> About the dev mode behavior, by default in dev mode all third-party extensions are ignored (as that mode is mainly for JupyterLab core developers). However if you do want to activate extensions in that mode, you will need to set an additional option when starting JupyterLab:
> 
> ```
> jupyter lab --dev-mode --extensions-in-dev-mode
> ```

Thanks for you reply.

It works fine when start JupyterLab by `jupyter lab --dev-mode --extensions-in-dev-mode`.

Since I just want to use JupyterLab components(@jupyterlab/notebook) to build my own product, is there any way to load third-party extensions in jupyter notebook? or show me an example. 

Thx~

**Comment by fcollonval** [comment]
You can have a look at retrolab that is a remix of JupyterLab: https://github.com/jupyterlab/retrolab

**Comment by iamyuchen** [comment]
> Thanks for reaching out.
> 
> The examples provided within this repository are highly simplified standalone application. The `example/notebook` in particular does not have the ability to load extensions. Hence you are not seeing the rich display. Using `jupyter labextension` cli won't help as it only works with JupyterLab not the examples.
> 
> About the dev mode behavior, by default in dev mode all third-party extensions are ignored (as that mode is mainly for JupyterLab core developers). However if you do want to activate extensions in that mode, you will need to set an additional option when starting JupyterLab:
> 
> ```
> jupyter lab --dev-mode --extensions-in-dev-mode
> ```
