### ISSUE TITLE
Limit cell drag initialization to input prompt area

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1179]

**Comment by jasongrout** [comment]
Looking into this, I think it makes sense to refactor the code so that the cell has control over the prompt, rather than the input area and the MarkdownOutput area.

**Comment by jasongrout** [comment]
Then the cell could just check to see if the drag starts in its prompt node.

**Comment by jasongrout** [comment]
Actually, it seems like maybe this won't work as nicely as I thought since the prompt and input area are side by side, but the cell flows vertically, so it may be best to have an input area anyway.
