### ISSUE TITLE
Jupyterlab 3.2.5: autocomplete not working in console

### ISSUE THREAD

**Issue by bigO6377** [jupyterlab/jupyterlab#11796]
## Description
Using a clean conda environment, I ran into some issues when I upgraded to Jupyterlab 3.2.5. Namely, the auto-complete does not work when using a console (regardless of whether it's a standalone kernel, or whether it is attached to the kernel of an open notebook).

## Reproduce

1. Open a new console

![image](https://user-images.githubusercontent.com/16709327/148470020-f7929f88-8fc0-4fbb-a732-1d6ca74452e7.png)

2. Select any python or R kernel

3. Define a variable "variable" in the console

4. Then try typing first few letters of "variable" and press Tab. Instead of autocompletion, it just adds spaces (see screenshot below)

![image](https://user-images.githubusercontent.com/16709327/148470173-639b6ea8-217b-4a17-bb83-c860770b6507.png)

## Expected behavior

I expected the auto-complete to immediately suggest the full name "variable" after I pressed Tab

## Context

- Operating System and version: MacOS Catalina  10.15.7 
- Browser and version: Chrome Version 96.0.4664.110 (Official Build) (x86_64) 
- JupyterLab version: 3.2.5

## Other details

- Did not have this issue with jupyter-lab 3.0.x
- The autocomplete within the notebook itself still works fine

**Comment by krassowski** [comment]
Thank you for opening this issue @bigO6377. There already is an issue where we track this problem: #11710, so I will mark this one as a duplicate.
