### ISSUE TITLE
"Output of this cell has been trimmed on the initial display": cell doesn't update continuously if I click the message

### ISSUE THREAD

**Issue by jeanmonet** [jupyterlab/jupyterlab#11797]
## Description

Jupyter Lab trims output of cells if output is beyond 100 lines (https://stackoverflow.com/questions/69617756/jupyter-lab-max-number-of-outputs-trimmed), and you can click on the message to expand the cell output nonetheless.

```
Output of this cell has been trimmed on the initial display. 
Displaying the first 50 top and last bottom outputs. 
Click on this message to get the complete output.
```

If I click on the message, the cell does indeed expand **however it only expands up to the point in time on which I clicked on the message, and no longer updates subsequent outputs even if the cell keeps running**.  The cell output is thus no longer updated continuously.  In order to get the remaining output I would have to reload the whole page.

## Context

- Operating System and version: Ubuntu 20.04 LTS
- Browser and version: Firefox 95.0.2 (64-bit)
- Python 3.9
- JupyterLab version:

```
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py39hf3d152e_1    conda-forge
jupyter_server            1.13.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.2.5              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.10.2             pyhd8ed1ab_0    conda-forge
```

**Comment by krassowski** [comment]
Based on the text of the message, you are using an old version of JupyterLab. This feature was improved by https://github.com/jupyterlab/jupyterlab/pull/11457/ which changed the message and behaviour; it was included in 3.2.5 version (current is 3.2.6). Could you please check with the most recent version of JupyterLab, and if it is still an issue, provide a reproducible example?

**Comment by jeanmonet** [comment]
Thanks! I have updated and seems cannot reproduce.

**Comment by jeanmonet** [comment]
I'd like to reopen this issue because I'm still having the same problem. See below Jupyter Lab version:
```
jupyter_client            7.1.2              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1           py310hff52083_1    conda-forge
jupyter_server            1.13.5             pyhd8ed1ab_0    conda-forge
jupyterlab                3.2.9              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.10.3             pyhd8ed1ab_0    conda-forge
```

The cell is trimmed due to increased number of lines over a period of time (ie a day). When I click to expand the trimmed part, I get the content **up to the point in time when I expanded the cell, but the cell doesn't continuously update the rest**!  In order to have the remaining output I would need to refresh the page (so the output is stored somewhere apparently, just that it no longer updates until I hit refresh).

I have a hunch this happens specifically in the case of a prolonged period of runtime (ie 1 day), and I'm having a hard time providing you with a quick-run snipped to reproduce.  However the issue is systematic when I have a cell running for longer periods.

Note, if relevant, I'm using Firefox (latest as of date).

**Comment by athornton** [comment]
I can confirm we're seeing this at Rubin Observatory too (when, ultimately, using `Ipython.display.display()` to display a lot of lines).

**Comment by timj** [comment]
I have also noticed that if I "clear all outputs" then new output does suddenly appear.

**Comment by lneuhaus** [comment]
I can reproduce this issue as well. 

My code:
import matplotlib.pyplot as plt
import time
x = list(range(10))

for i in range(100):
    plt.figure()
    plt.plot(x);
    plt.title(str(i))
    time.sleep(0.1)
```
After the first 50 plots, I get the "Output of this cell has been trimmed" message. When I click on it before all plots are generated, I can never see the ones generated after that.

My versions:
```
Selected Jupyter core packages...
IPython          : 8.4.0
ipykernel        : 5.5.6
ipywidgets       : 7.7.0
jupyter_client   : 7.3.1
jupyter_core     : 4.10.0
jupyter_server   : 1.17.0
jupyterlab       : 3.4.2
nbclient         : 0.6.4
nbconvert        : 6.5.0
nbformat         : 5.4.0
notebook         : 6.4.11
qtconsole        : not installed
traitlets        : 5.2.2
```

**Comment by nkh0472** [comment]
same problem!
```
jupyter                   1.0.0                    py38_7    defaults
jupyter_client            7.2.2            py38haa95532_0    defaults
jupyter_console           6.4.3              pyhd3eb1b0_0    defaults
jupyter_core              4.10.0           py38haa95532_0    defaults
jupyter_server            1.17.1           py38haa95532_0    defaults
jupyterlab                3.3.2              pyhd3eb1b0_0    defaults
jupyterlab-code-formatter 1.4.11                   pypi_0    pypi
jupyterlab-language-pack-zh-cn 3.4.post1          pyh3752e69_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.12.0           py38haa95532_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
```

**Comment by GregSilverman** [comment]
Same (just upgraded everything, too:

```
Selected Jupyter core packages...
IPython          : 8.2.0
ipykernel        : 6.9.1
ipywidgets       : 7.6.5
jupyter_client   : 6.1.12
jupyter_core     : 4.9.2
jupyter_server   : 1.13.5
jupyterlab       : 3.3.2
nbclient         : 0.5.13
nbconvert        : 6.4.4
nbformat         : 5.3.0
notebook         : 6.4.8
qtconsole        : 5.3.0
traitlets        : 5.1.1
```

**Comment by pyppapig** [comment]
i get a way to solve it!
click on Menu → Settings → Advanced Settings Editor → Notebook → set maxNumberOutputs in the User Preferences tab, like:
`{
    "maxNumberOutputs": 100
}`
save, and reload.

**Comment by jeanmonet** [comment]
The current version of Jupyter Lab seems to work fine. Expanding the hidden output does not stop subsequent output from being streamed. Closing the issue.

```
Firefox 109.0

jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_core              5.1.3           py310hbe9552e_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.1.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                3.5.2              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.19.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.5              pyhd8ed1ab_0    conda-forge
```
