### ISSUE TITLE
Clear button is not displayed in command palette search bar

### ISSUE THREAD

**Issue by marthacryan** [jupyterlab/jupyterlab#11791]
## Description
Seems like there's a CSS bug where the clear button in the search bar of the command palette is not being displayed correctly. It's currently showing up under the magnifying glass icon and is clickable but has a very small width.
![image](https://user-images.githubusercontent.com/6673460/148263525-b4eeb693-83ba-4e31-9867-ee29442678e7.png)

## Reproduce
Type something into the search bar of the command palette, then hover over the magnifying glass logo (might have to move your mouse around to find the spot that triggers the pointer cursor), then click and it will clear the contents of the search bar. 

## Expected behavior
Seems like there should be a button with an "X" icon to trigger clearing the search bar.

## Context
Looks like this is the element that's not displaying correctly: `<button class="lm-close-icon" style="display: inherit;"></button>`
And this is the CSS being applied to it:
```
.lm-close-icon {
    border: 1px solid transparent;
    background-color: transparent;
    position: absolute;
    z-index: 1;
    right: 3%;
    top: 0;
    bottom: 0;
    margin: auto;
    padding: 7px 0;
    display: none;
    vertical-align: middle;
    outline: 0;
    cursor: pointer;
}
```

**Comment by jweill-aws** [comment]
I manually modified this button to have a textual `X` inside, and it rendered in the middle of the commands, not immediately to the left of the magnifying glass button inside the text box. If we actually want this X button to display, we'll also need to modify the CSS.

Screen shot below is from Firefox 91.4.0esr.

![image](https://user-images.githubusercontent.com/93281816/148290868-28bff5b2-1f0e-44fa-8522-2907aac65fdb.png)

**Comment by krassowski** [comment]
Thanks for opening the issue. I think that adding the clear button is already tracked in: https://github.com/jupyterlab/jupyterlab/issues/342.

I agree that it would be useful to fix the styles and show an "x" prominently when anything is typed in (replacing the magnifying glass when there is any text in the input).

Side-note:
> It is really strange that this button lands in a random position, but I suspect it is a consequence of it being implemented in lumino and no one really looking over there when reworking command palette in lab (as most components like that live in Lab it seems a bit unusual that command palette is in Lumino).
> 
> I would be happy to add the clear button in the proposed rewrite of command palette (see https://github.com/jupyterlab/jupyterlab/issues/11776).

**Comment by jweill-aws** [comment]
Closing in favor of #342.
