### ISSUE TITLE
documentation should include pip(3) on Mac instructions (in two places)

### ISSUE THREAD

**Issue by antNIH** [jupyterlab/jupyterlab#11815]
Mac comes with Python 2.7, and installing Python installs it as python3.
When a new user tries to follow the **Install JN** [here](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html) or [here](https://jupyter.org/install) documentation they will get stuck:

```
C603:~ ant$ pip install jupyterlab
-sh: pip: command not found
```

Documentation should simply include "if on Mac, use pip3".

```
C603:~ ant$ pip3 install jupyterlab
Collecting jupyterlab
  Downloading jupyterlab-3.2.6-py3-none-any.whl (8.6 MB)
     |████████████████████████████████| 8.6 MB 2.1 MB/s ```

**Comment by fcollonval** [comment]
closed by #11816
