### ISSUE TITLE
`username` query parameter does not support escaping.

### ISSUE THREAD

**Issue by HoseonRyu** [jupyterlab/jupyterlab#11820]
### Problem
Currently, I'm using `jupyterlab 3.2.5`.

An issue was discovered while using the **collaborative edition mode**. When I put some Korean username in the `username` parameter like this `... /Untitled.ipynb?username=사용자`, it looks like the picture below to others.

![image](https://user-images.githubusercontent.com/31889783/148915487-c38062ad-f50e-4322-be86-c47a4f439475.png)

Also, I tried to include a space to `username` via this url : `... /Untitled.ipynb?username=space space`.

![image](https://user-images.githubusercontent.com/31889783/148912464-9a209084-8bdb-429f-bc6e-ac05dacd047a.png)
The percent encoded name appears, again.

In the `/packages/user/src/model.ts`: line 157, `getParam` gives parsed `username` parameter. However, this function just splits with `&` character as you can check in https://github.com/dmonad/lib0/blob/main/environment.js .
I hope it will be solved for the use of special characters including space and for global users.

### Proposed Solution
It can be solved by simply adding percent decoding codes.

Always thank you for providing great services!

**Comment by hbcarlos** [comment]
Hi @HoseonRyu! Thank you for opening the issue.

Indeed this parameter only supports limited use cases, this was a temporary solution until we built a proper UI to rename anonymous users.

Since you have already debugged the issue and know a solution, do you want to open a PR to solve it?

**Comment by hbcarlos** [comment]
> In the /packages/user/src/model.ts: line 157, getParam gives parsed username parameter.

I think you are looking at the master branch. The master branch has already some features for v4.0. In v3.2.x, we had the same functionality in another package, see:
https://github.com/jupyterlab/jupyterlab/blob/d8e9192baf193c55bbee07c4acef3e262e033391/packages/docprovider/src/yprovider.ts#L45-L46

**Comment by HoseonRyu** [comment]
Hello, @hbcarlos  , thanks for your quick reply!

Then, I'll start to work on `3.2.x` branch. Should I also provide fixes for other versions like 3.3 or 4.0?

**Comment by hbcarlos** [comment]
> Then, I'll start to work on 3.2.x branch.

I'm not sure how to do it in this case, because we move it to another package. Usually, we make the fix in master and then backport it automatically but in this case, I'm not sure if the backport will work. Let me ping someone with more experience.
@jtpio @fcollonval.

> Should I also provide fixes for other versions like 3.3 or 4.0?

Yes, that would be great. Thank you so much!

**Comment by jtpio** [comment]
We can try the usual backport with Meeseeks and see if it is able to handle the move.

Otherwise it will probably have to be done manually.

**Comment by hbcarlos** [comment]
Thanks, Jeremy!

@HoseonRyu It is better to fix it in the master branch in the user package as you pointed out here
> In the /packages/user/src/model.ts: line 157, getParam gives parsed username parameter.

And then we can backport it to the other branches.

**Comment by HoseonRyu** [comment]
Got it! I'm gonna open PR on master branch.

**Comment by fcollonval** [comment]
Fixed by #11852
