### ISSUE TITLE
Lab tour improvements

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1184]
The moving arrow to see "Next" section is nice. It would be great if it could scroll smoothly instead of jumping to a new location to give visual clue to the user. 

Further improvement could be:

- Arrow to "Previous"  section. 
- Advancement indicator (especially now that many OS "fade" the scrollbar")

**Comment by charnpreetsingh185** [comment]
I can work on this!

**Comment by ellisonbg** [comment]
Closing in favor of #1621
