### ISSUE TITLE
Unable to open an old workspace in 3.2.7

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#11856]
## Description

After upgrading to 3.2.7 I am unable to open previously created workspaces (there's a JS error on load)

## Reproduce

1. Install jlab 3.2.6 `mamba create -n jlab_bug "jupyterlab==3.2.6"`
2. Launch jlab with an empty config `jupyter lab --config /path/to/empty/folder`, go to /lab/workspaces/test, open a notebook (not sure if necessary).
3. Install jlab 3.2.7
4. Launch jlab, go to /lab/workspaces/test, observe that it does not load

The JS console shows the following traceback:

```
jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_document')
    at u (jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2:1551552)
    at Object.o [as realizeAreaConfig] (jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2:1543944)
    at t.restoreLayout (jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2:1535700)
    at Jn.t.restoreLayout (jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2:1555690)
    at O.restoreLayout (jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2:35862)
    at jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2:9079
u @ jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2
o @ jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2
t.restoreLayout @ jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2
t.restoreLayout @ jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2
restoreLayout @ jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2
(anonymous) @ jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2
Promise.then (async)
activate @ jlab_core.b0391eb9bfd173e3a974.js?v=b0391eb9bfd173e3a974:2
```

## Expected behavior

The workspace loads and shows the notebook.

## Context

- Operating System and version: ubuntu 21.10
- Browser and version: Chrome 97.0.4692.71 (Official Build) (64-bit)
- JupyterLab version: 3.2.7

**Comment by krassowski** [comment]
This is a regression in lumino which is getting fixed in https://github.com/jupyterlab/lumino/pull/281.

**Comment by jtpio** [comment]
@akhmerov mind trying with the latest `3.2.8` release?

**Comment by akhmerov** [comment]
Ah, thanks for the reminder. All good, as expected.
