### ISSUE TITLE
Debounce document search

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#11876]
### Problem

If you have a large notebook, document search is slow. This is made a bit more frustrating to end users by the fact that every keypress does another search.

### Proposed Solution

If we debounce the document searchbox, this would greatly reduce the problem. If that is not feasible, we could have a setting that forces users to push enter to search.

### Additional context

N/A

**Comment by oeway** [comment]
I second this! The search is rather slow for large notebooks, especially for the first key stroke. It would be much better if we can disable the hot search and only do it when we press enter.

**Comment by echarles** [comment]
Actually, there is already a debouncer on the search box https://github.com/jupyterlab/jupyterlab/blob/c5df985383964b027e475e667d69a7e8facf42bb/packages/documentsearch/src/searchoverlay.tsx#L639-L642

The debounce time value is set to `500ms` (half a second) and is effective: Try typing fast, then stop, you will see the search highlighting after that 0,5 second.

We could e.g. double that value, but I don't think this will ease the search in large notebooks.

@fcollonval has a WIP PR https://github.com/jupyterlab/jupyterlab/pull/11689 to rely on a search done on the data model, with performance improvements for the end-user.

**Comment by echarles** [comment]
I have a opened PR to mitigate the search performance issue https://github.com/jupyterlab/jupyterlab/pull/12097. It allows the user to set the debounce time value to e.g. a large number while relying on `Enter` keystroke to trigger the search.

cc/ @fcollonval

**Comment by fcollonval** [comment]
Closing as addressed by #12097
