### ISSUE TITLE
404 : Not Found

### ISSUE THREAD

**Issue by post2web** [jupyterlab/jupyterlab#1187]
jupyterlab was installed with pip, enabled jupyter serverextension all without any errors.
It also starts without any console errors:
![screen shot 2016-10-31 at 5 59 40 pm](https://cloud.githubusercontent.com/assets/187587/19873170/e37f2084-9f93-11e6-8524-518a6e10da38.png)
However, the browser keeps on redirecting to **http://localhost:8888/lab** and it shows **404 : Not Found**. It would redirect me back to **/lab** for anything I type after http://localhost:8888/<br/>
All I able to see is **404 : Not Found**.

**Comment by dschick** [comment]
same problem for me.
Installed latest jupyter lab version without errors using pip in WinPython 3.4.4.
For version 0.4 everything was fine, but vor 0.6 & 0.7 I get the 404 error. 

Thanks in advance

**Comment by blink1073** [comment]
Hi @post2web, @dschick,  I just tried the installation instructions from the [readme](https://github.com/jupyterlab/jupyterlab#installation) on Windows 10 from a fresh conda environment and it launched successfully.

Can you give the output of `jupyter serverextension list`?

**Comment by blink1073** [comment]
To be clear: I used the `pip` install instructions.

**Comment by post2web** [comment]
<pre>
evo ~/ : jupyter serverextension list
config dir: /Users/evo/.jupyter
    jupyter_nbextensions_configurator  enabled
    - Validating...
      jupyter_nbextensions_configurator  OK
    ipyparallel.nbextension  enabled
    - Validating...
      ipyparallel.nbextension  OK
config dir: /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/etc/jupyter
    jupyter_cms  enabled
    - Validating...
      jupyter_cms  OK
    jupyterlab  enabled
    - Validating...
      jupyterlab  OK
config dir: /usr/local/etc/jupyter
    ipyparallel.nbextension disabled
    - Validating...
      ipyparallel.nbextension  OK
</pre>

**Comment by blink1073** [comment]
@post2web, can you verify that there is a `lab.html` file in the folder given by `python -c "import jupyterlab; print(jupyterlab.__path__)"`?

**Comment by post2web** [comment]
lab.html is in that folder

**Comment by blink1073** [comment]
@post2web, are you able to launch `jupyter notebook` successfully?

**Comment by post2web** [comment]
Yes I am able to use `jupyter notebook` successfully

**Comment by blink1073** [comment]
Can you please try `jupyter lab --debug` and past the output?

**Comment by post2web** [comment]
Here is the debug output:
<pre>
evo ~/ : jupyter lab --debug
[D 09:43:38.417 LabApp] Searching [u'/Users/evo', '/Users/evo/.jupyter', '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 09:43:38.418 LabApp] Looking for jupyter_config in /etc/jupyter
[D 09:43:38.418 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 09:43:38.418 LabApp] Looking for jupyter_config in /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/etc/jupyter
[D 09:43:38.418 LabApp] Looking for jupyter_config in /Users/evo/.jupyter
[D 09:43:38.419 LabApp] Looking for jupyter_config in /Users/evo
[D 09:43:38.420 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 09:43:38.420 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 09:43:38.421 LabApp] Loaded config file: /usr/local/etc/jupyter/jupyter_notebook_config.json
[D 09:43:38.421 LabApp] Looking for jupyter_notebook_config in /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/etc/jupyter
[D 09:43:38.421 LabApp] Loaded config file: /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/etc/jupyter/jupyter_notebook_config.json
[D 09:43:38.422 LabApp] Looking for jupyter_notebook_config in /Users/evo/.jupyter
[D 09:43:38.423 LabApp] Loaded config file: /Users/evo/.jupyter/jupyter_notebook_config.py
[D 09:43:38.424 LabApp] Loaded config file: /Users/evo/.jupyter/jupyter_notebook_config.json
[D 09:43:38.424 LabApp] Looking for jupyter_notebook_config in /Users/evo
[I 09:43:38.986 LabApp] The port 8888 is already in use, trying another port.
[D 09:43:39.043 LabApp] Loading extension jupyter_nbextensions_configurator
[D 09:43:39.043 LabApp]   Editing template path to add /usr/local/lib/python2.7/site-packages/jupyter_nbextensions_configurator/templates
[D 09:43:39.043 LabApp]   Editing nbextensions path to add /usr/local/lib/python2.7/site-packages/jupyter_nbextensions_configurator/static
[D 09:43:39.044 LabApp]   Adding new handlers
[I 09:43:39.044 LabApp] Loaded extension jupyter_nbextensions_configurator
[I 09:43:39.070 LabApp] Loading IPython parallel extension
[I 09:43:39.080 LabApp] Serving notebooks from local directory: /Users/evo
[I 09:43:39.080 LabApp] 0 active kernels
[I 09:43:39.080 LabApp] The Jupyter Notebook is running at: http://localhost:8889/
[I 09:43:39.080 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 09:43:39.491 LabApp] 304 GET /custom/custom.css (::1) 1.74ms
[D 09:43:39.493 LabApp] Using contents: services/contents
[W 09:43:39.526 LabApp] 404 GET /lab (::1) 33.94ms referer=None
[D 09:43:39.570 LabApp] 200 GET /static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe (::1) 0.90ms
[D 09:43:39.682 LabApp] 200 GET /static/base/images/logo.png?v=7c4597ba713d804995e8f8dad448a397 (::1) 0.98ms
</pre>

**Comment by blink1073** [comment]
Ugh, sorry, I thought that because it had said `[LabApp]` that your server extension was properly installed, but that prompt is provided by the `jupyter lab` entry point.  It looks like you need to enable it as user: `jupyter serverextension enable --py jupyterlab --user`.

**Comment by post2web** [comment]
I finally works! Thanks!

**Comment by blink1073** [comment]
Great!  Sorry for the confusion.  We are discussing improving the overall extension install/enable process here: https://github.com/jupyter/notebook/issues/1706.

Can we close this one?

**Comment by dschick** [comment]
Works for me, too. Thanks!

**Comment by post2web** [comment]
Yes, close it.
