### ISSUE TITLE
`js-apputils` check is failing on CI

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#11886]
## Description

It looks like the `js-apputils` check has started failing on CI.

![image](https://user-images.githubusercontent.com/591645/149728341-1f8e95ce-4127-4804-8289-7252f15e0617.png)

## Reproduce

Example run on the latest commit on `master`: https://github.com/jupyterlab/jupyterlab/runs/4837529806?check_suite_focus=true

## Expected behavior

Check should pass.

## Context

Probably a new upstream dependency that got released.

**Comment by jtpio** [comment]
> Probably a new upstream dependency that got released.

Maybe related to the `jupyter_client==7.1.1` release that has some changes related to pending kernels? https://github.com/jupyter/jupyter_client/releases/tag/v7.1.1

**Comment by jtpio** [comment]
Yes this seems related to `jupyter_client==7.1.1`: https://github.com/jupyter/jupyter_client/pull/732#issuecomment-1014247566

**Comment by Zsailer** [comment]
Thanks, @jtpio. I'll dive into this tomorrow and get this working again.

**Comment by jtpio** [comment]
This can be reproduced locally with:

```
pip install jupyter_client==7.1.1
cd packages/apputils
jlpm run build:test
jlpm run test test/sessioncontext.spec.ts --testNamePattern="should handle multiple requests"
```

By removing the `flakyIt` alias defined here:

https://github.com/jupyterlab/jupyterlab/blob/ea1529b6683adb692b1c9908f04d0a2cead44a9f/packages/apputils/test/sessioncontext.spec.ts#L19

We get a more descriptive error message:

![image](https://user-images.githubusercontent.com/591645/150487674-9fbd7d1c-b7ba-40a4-b110-08829f104eeb.png)

**Comment by jtpio** [comment]
The error comes from the second call to `sessionContext.changeKernel()`:

https://github.com/jupyterlab/jupyterlab/blob/ea1529b6683adb692b1c9908f04d0a2cead44a9f/packages/apputils/test/sessioncontext.spec.ts#L458

**Comment by Zsailer** [comment]
Thanks, @jtpio. This is super helpful. Debugging this issue has been really challenging 😅

**Comment by Zsailer** [comment]
this should be fixed in jupyter_client==7.1.2

**Comment by jtpio** [comment]
Thanks @Zsailer!

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter/jupyter_client/pull/740
