### ISSUE TITLE
Exporting notebook using `Save and Export Notebook As` raises `"tuple" object is not callable` from `anyio`

### ISSUE THREAD

**Issue by kagesenshi** [jupyterlab/jupyterlab#11885]
## Description

Exporting notebook using `Save and Export Notebook As` raises `"tuple" object is not callable` from `anyio`

```
Jan 17 00:32:28 hadoop.home.kagesenshi.org jupyterhub[177666]: [E 2022-01-17 00:32:28.408 SingleUserLabApp handlers:125] nbconvert failed: 'tuple' object is not callable
Jan 17 00:32:28 hadoop.home.kagesenshi.org jupyterhub[177666]:     Traceback (most recent call last):
Jan 17 00:32:28 hadoop.home.kagesenshi.org jupyterhub[177666]:       File "/opt/jupyterhub/lib64/python3.8/site-packages/jupyter_server/nbconvert/handlers.py", line 121, in get
Jan 17 00:32:28 hadoop.home.kagesenshi.org jupyterhub[177666]:         output, resources = await run_sync(
Jan 17 00:32:28 hadoop.home.kagesenshi.org jupyterhub[177666]:       File "/opt/jupyterhub/lib64/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
Jan 17 00:32:28 hadoop.home.kagesenshi.org jupyterhub[177666]:         return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
Jan 17 00:32:28 hadoop.home.kagesenshi.org jupyterhub[177666]:       File "/opt/jupyterhub/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
Jan 17 00:32:28 hadoop.home.kagesenshi.org jupyterhub[177666]:         return await future
Jan 17 00:32:28 hadoop.home.kagesenshi.org jupyterhub[177666]:       File "/opt/jupyterhub/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
Jan 17 00:32:28 hadoop.home.kagesenshi.org jupyterhub[177666]:         result = context.run(func, *args)
Jan 17 00:32:28 hadoop.home.kagesenshi.org jupyterhub[177666]:     TypeError: 'tuple' object is not callable
```

running `jupyter-nbconvert` directly on CLI works fine however

## Reproduce

1. Create a notebook
2. Click on `Save and Export Notebook As` > `HTML`

## Expected behavior

HTML export successful

## Context

- Operating System and version: Fedora 34
- Browser and version: Chrome 96
- JupyterLab version: 3.2.8

Setup is using `python3.8` in virtualenv, through `jupyterhub=2.0.2`,
 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.

WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
You should consider upgrading via the '/opt/jupyterhub/bin/python3.8 -m pip install --upgrade pip' command.
$PATH:
	/opt/jupyterhub/bin/
	/home/demo/.local/bin
	/home/demo/bin
	/usr/local/bin
	/usr/bin
	/usr/local/sbin
	/usr/sbin

sys.path:
	/opt/jupyterhub/bin
	/usr/lib64/python38.zip
	/usr/lib64/python3.8
	/usr/lib64/python3.8/lib-dynload
	/opt/jupyterhub/lib64/python3.8/site-packages
	/opt/jupyterhub/lib/python3.8/site-packages

sys.executable:
	/opt/jupyterhub/bin/python3.8

sys.version:
	3.8.12 (default, Aug 30 2021, 00:00:00) 
	[GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]

platform.platform():
	Linux-5.11.12-300.fc34.x86_64-x86_64-with-glibc2.2.5

which -a jupyter:
	/opt/jupyterhub/bin/jupyter

pip list:
	Package                 Version
	----------------------- ---------
	aiohttp                 3.8.1
	aiosignal               1.2.0
	alembic                 1.7.5
	anyio                   3.4.0
	argon2-cffi             21.3.0
	argon2-cffi-bindings    21.2.0
	asttokens               2.0.5
	async-generator         1.10
	async-timeout           4.0.2
	attrs                   21.4.0
	Babel                   2.9.1
	backcall                0.2.0
	black                   21.12b0
	bleach                  4.1.0
	certifi                 2021.10.8
	certipy                 0.1.3
	cffi                    1.15.0
	charset-normalizer      2.0.10
	click                   8.0.3
	colorama                0.4.4
	cryptography            36.0.1
	debugpy                 1.5.1
	decorator               5.1.1
	defusedxml              0.7.1
	entrypoints             0.3
	executing               0.8.2
	frozenlist              1.2.0
	gitdb                   4.0.9
	GitPython               3.1.26
	greenlet                1.1.2
	idna                    3.3
	importlib-metadata      4.10.0
	importlib-resources     5.4.0
	ipykernel               6.7.0
	ipython                 8.0.0
	ipython-genutils        0.2.0
	jedi                    0.18.1
	Jinja2                  3.0.3
	json5                   0.9.6
	jsonschema              4.4.0
	jupyter-client          7.1.1
	jupyter-core            4.9.1
	jupyter-server          1.13.3
	jupyter-server-mathjax  0.2.3
	jupyter-server-proxy    3.2.0
	jupyter-telemetry       0.1.0
	jupyterhub              2.0.2
	jupyterlab              3.2.8
	jupyterlab-fasta        3.1.1
	jupyterlab-geojson      3.1.2
	jupyterlab-git          0.34.2
	jupyterlab-katex        3.2.2
	jupyterlab-latex        3.1.0
	jupyterlab-mathjax3     4.2.2
	jupyterlab-pullrequests 3.0.2
	jupyterlab-pygments     0.1.2
	jupyterlab-server       2.10.3
	jupyterlab-vega2        3.1.3
	jupyterlab-vega3        3.1.3
	jupyterlab-widgets      1.0.2
	Mako                    1.1.6
	MarkupSafe              2.0.1
	matplotlib-inline       0.1.3
	mistune                 0.8.4
	multidict               5.2.0
	mypy-extensions         0.4.3
	nbclassic               0.3.5
	nbclient                0.5.10
	nbconvert               6.4.0
	nbdime                  3.1.1
	nbformat                5.1.3
	nest-asyncio            1.5.4
	notebook                6.4.7
	oauthlib                3.1.1
	packaging               21.3
	pamela                  1.0.0
	pandocfilters           1.5.0
	parso                   0.8.3
	pathspec                0.9.0
	pexpect                 4.8.0
	pickleshare             0.7.5
	pip                     21.0.1
	platformdirs            2.4.1
	prometheus-client       0.12.0
	prompt-toolkit          3.0.24
	psycopg2-binary         2.9.3
	ptyprocess              0.7.0
	pure-eval               0.2.1
	pycparser               2.21
	Pygments                2.11.2
	pymssql                 2.2.3
	pyOpenSSL               21.0.0
	pyparsing               3.0.6
	pyrsistent              0.18.1
	python-dateutil         2.8.2
	python-json-logger      2.0.2
	pytz                    2021.3
	pyzmq                   22.3.0
	requests                2.27.1
	ruamel.yaml             0.17.20
	ruamel.yaml.clib        0.2.6
	Send2Trash              1.8.0
	setuptools              53.0.0
	simpervisor             0.4
	six                     1.16.0
	smmap                   5.0.0
	sniffio                 1.2.0
	SQLAlchemy              1.4.29
	stack-data              0.1.4
	terminado               0.12.1
	testpath                0.5.0
	tomli                   1.2.3
	tornado                 6.1
	traitlets               5.1.1
	typing-extensions       4.0.1
	urllib3                 1.26.8
	wcwidth                 0.2.5
	webencodings            0.5.1
	websocket-client        1.2.3
	yarl                    1.7.2
	zipp                    3.7.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.

[D 2022-01-17 00:42:30.277 ServerApp] Searching ['/home/demo', '/home/demo/.jupyter', '/opt/jupyterhub/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2022-01-17 00:42:30.277 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2022-01-17 00:42:30.278 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2022-01-17 00:42:30.278 ServerApp] Looking for jupyter_config in /opt/jupyterhub/etc/jupyter
[D 2022-01-17 00:42:30.278 ServerApp] Looking for jupyter_config in /home/demo/.jupyter
[D 2022-01-17 00:42:30.278 ServerApp] Looking for jupyter_config in /home/demo
[D 2022-01-17 00:42:30.279 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2022-01-17 00:42:30.279 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2022-01-17 00:42:30.279 ServerApp] Looking for jupyter_server_config in /opt/jupyterhub/etc/jupyter
[D 2022-01-17 00:42:30.279 ServerApp] Looking for jupyter_server_config in /home/demo/.jupyter
[D 2022-01-17 00:42:30.279 ServerApp] Loaded config file: /home/demo/.jupyter/jupyter_server_config.json
[D 2022-01-17 00:42:30.279 ServerApp] Looking for jupyter_server_config in /home/demo
[D 2022-01-17 00:42:30.281 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/etc/jupyter/jupyter_server_config.json
[D 2022-01-17 00:42:30.281 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/usr/local/etc/jupyter/jupyter_server_config.json
[D 2022-01-17 00:42:30.281 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/opt/jupyterhub/etc/jupyter/jupyter_server_config.d/jupyter-server-proxy-jupyterserverextension.json
    	/opt/jupyterhub/etc/jupyter/jupyter_server_config.d/jupyter_server_mathjax.json
    	/opt/jupyterhub/etc/jupyter/jupyter_server_config.d/jupyterlab.json
    	/opt/jupyterhub/etc/jupyter/jupyter_server_config.d/jupyterlab_git.json
    	/opt/jupyterhub/etc/jupyter/jupyter_server_config.d/jupyterlab_latex.json
    	/opt/jupyterhub/etc/jupyter/jupyter_server_config.d/jupyterlab_pullrequests_server.json
    	/opt/jupyterhub/etc/jupyter/jupyter_server_config.d/nbclassic.json
    	/opt/jupyterhub/etc/jupyter/jupyter_server_config.d/nbdime.json
    	/opt/jupyterhub/etc/jupyter/jupyter_server_config.json
[D 2022-01-17 00:42:30.282 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/home/demo/.jupyter/jupyter_server_config.json
/opt/jupyterhub/lib64/python3.8/site-packages/jupyter_server_mathjax/app.py:40: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  help=_("""The MathJax.js configuration file that is to be used."""),
[D 2022-01-17 00:42:30.524 MathJaxExtension] Config changed: {'ServerApp': {'ip': '0.0.0.0', 'log_level': 'DEBUG', 'password': 'argon2:$argon2id$v=19$m=10240,t=10,p=8$1l/BEPsceo2H5MHQ+o9smA$ljoMSWVCyiKjAaUKVFld5Wtx4mJ+HPh/p5jYuRAhXpw', 'jpserver_extensions': <LazyConfigValue {'update': {'jupyter_server_mathjax': True, 'jupyter_server_proxy': True, 'jupyterlab_git': True, 'jupyterlab_latex': True, 'jupyterlab_pullrequests': True, 'nbclassic': True, 'nbdime': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2022-01-17 00:42:30.525 ServerApp] Config changed: {'ServerApp': {'ip': '0.0.0.0', 'log_level': 'DEBUG', 'password': 'argon2:$argon2id$v=19$m=10240,t=10,p=8$1l/BEPsceo2H5MHQ+o9smA$ljoMSWVCyiKjAaUKVFld5Wtx4mJ+HPh/p5jYuRAhXpw', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_mathjax': True, 'jupyter_server_proxy': True, 'jupyterlab_git': True, 'jupyterlab_latex': True, 'jupyterlab_pullrequests': True, 'nbclassic': True, 'nbdime': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2022-01-17 00:42:30.525 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2022-01-17 00:42:30.526 ServerApp] jupyter_server_proxy | extension was successfully linked.
[D 2022-01-17 00:42:30.534 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'ip': '0.0.0.0', 'log_level': 'DEBUG', 'password': 'argon2:$argon2id$v=19$m=10240,t=10,p=8$1l/BEPsceo2H5MHQ+o9smA$ljoMSWVCyiKjAaUKVFld5Wtx4mJ+HPh/p5jYuRAhXpw', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_mathjax': True, 'jupyter_server_proxy': True, 'jupyterlab_git': True, 'jupyterlab_latex': True, 'jupyterlab_pullrequests': True, 'nbclassic': True, 'nbdime': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2022-01-17 00:42:30.534 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-01-17 00:42:30.534 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2022-01-17 00:42:30.534 ServerApp] jupyterlab_latex | extension was successfully linked.
[I 2022-01-17 00:42:30.534 ServerApp] jupyterlab_pullrequests | extension was successfully linked.
[D 2022-01-17 00:42:30.541 NotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'ip': '0.0.0.0', 'log_level': 'DEBUG', 'password': 'argon2:$argon2id$v=19$m=10240,t=10,p=8$1l/BEPsceo2H5MHQ+o9smA$ljoMSWVCyiKjAaUKVFld5Wtx4mJ+HPh/p5jYuRAhXpw', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_mathjax': True, 'jupyter_server_proxy': True, 'jupyterlab_git': True, 'jupyterlab_latex': True, 'jupyterlab_pullrequests': True, 'nbclassic': True, 'nbdime': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2022-01-17 00:42:30.965 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/demo/.jupyter/jupyter_notebook_config.json
[D 2022-01-17 00:42:30.965 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 2022-01-17 00:42:30.965 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2022-01-17 00:42:30.966 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/opt/jupyterhub/etc/jupyter/jupyter_notebook_config.d/jupyter-server-proxy-notebookserverextension.json
    	/opt/jupyterhub/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/opt/jupyterhub/etc/jupyter/jupyter_notebook_config.d/jupyterlab_git.json
    	/opt/jupyterhub/etc/jupyter/jupyter_notebook_config.d/jupyterlab_latex.json
    	/opt/jupyterhub/etc/jupyter/jupyter_notebook_config.d/jupyterlab_pullrequests_notebook.json
    	/opt/jupyterhub/etc/jupyter/jupyter_notebook_config.d/nbdime.json
    	/opt/jupyterhub/etc/jupyter/jupyter_notebook_config.json
[D 2022-01-17 00:42:30.966 ServerApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/demo/.jupyter/jupyter_notebook_config.json
[I 2022-01-17 00:42:30.966 ServerApp] nbclassic | extension was successfully linked.
[I 2022-01-17 00:42:30.966 ServerApp] nbdime | extension was successfully linked.
[D 2022-01-17 00:42:30.967 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'NotebookApp': {}, 'ServerApp': {'ip': '0.0.0.0', 'log_level': 'DEBUG', 'password': 'argon2:$argon2id$v=19$m=10240,t=10,p=8$1l/BEPsceo2H5MHQ+o9smA$ljoMSWVCyiKjAaUKVFld5Wtx4mJ+HPh/p5jYuRAhXpw', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_mathjax': True, 'jupyter_server_proxy': True, 'jupyterlab_git': True, 'jupyterlab_latex': True, 'jupyterlab_pullrequests': True, 'nbclassic': True, 'nbdime': True}>}}
[D 2022-01-17 00:42:30.967 ServerApp] Raising open file limit: soft 1024->4096; hard 524288->524288
[I 2022-01-17 00:42:30.991 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-01-17 00:42:30.992 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2022-01-17 00:42:30.997 ServerApp] jupyter_server_proxy | extension was successfully loaded.
[I 2022-01-17 00:42:30.998 LabApp] JupyterLab extension loaded from /opt/jupyterhub/lib64/python3.8/site-packages/jupyterlab
[I 2022-01-17 00:42:30.998 LabApp] JupyterLab application directory is /opt/jupyterhub/share/jupyter/lab
[I 2022-01-17 00:42:31.001 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-01-17 00:42:31.005 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2022-01-17 00:42:31.007 ServerApp] jupyterlab_latex | extension was successfully loaded.
PR Manager Class <function get_github_manager at 0x7f081ec09d30>
[I 2022-01-17 00:42:31.019 ServerApp] Registered jupyterlab_pullrequests extension
[I 2022-01-17 00:42:31.019 ServerApp] jupyterlab_pullrequests | extension was successfully loaded.
[D 2022-01-17 00:42:31.115 ServerApp] Using default logger
[D 2022-01-17 00:42:31.116 ServerApp] Using default logger
[D 2022-01-17 00:42:31.116 ServerApp] Using default logger
[D 2022-01-17 00:42:31.116 ServerApp] Using default logger
[D 2022-01-17 00:42:31.116 ServerApp] Using default logger
[I 2022-01-17 00:42:31.117 ServerApp] nbdime | extension was successfully loaded.
[I 2022-01-17 00:42:31.117 ServerApp] Serving notebooks from local directory: /home/demo
[I 2022-01-17 00:42:31.117 ServerApp] Jupyter Server 1.13.3 is running at:
[I 2022-01-17 00:42:31.117 ServerApp] http://hadoop.home.kagesenshi.org:8888/lab
[I 2022-01-17 00:42:31.117 ServerApp]  or http://127.0.0.1:8888/lab
[I 2022-01-17 00:42:31.117 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2022-01-17 00:42:31.120 ServerApp] No web browser found: could not locate runnable browser.
[W 2022-01-17 00:42:34.321 ServerApp] Clearing invalid/expired login cookie username-10-210-14-53-8888
[W 2022-01-17 00:42:34.322 ServerApp] Clearing invalid/expired login cookie username-10-210-14-53-8888
[I 2022-01-17 00:42:34.322 ServerApp] 302 GET /nbconvert/html/simulasi_1_2.ipynb?download=true (10.210.14.99) 1.57ms
[D 2022-01-17 00:42:34.325 ServerApp] Using contents: services/contents
[D 2022-01-17 00:42:34.344 ServerApp] Path favicon.ico served from /opt/jupyterhub/lib64/python3.8/site-packages/jupyter_server/static/favicon.ico
[D 2022-01-17 00:42:34.345 ServerApp] Path style/bootstrap.min.css served from /opt/jupyterhub/lib64/python3.8/site-packages/jupyter_server/static/style/bootstrap.min.css
[D 2022-01-17 00:42:34.345 ServerApp] Path style/bootstrap-theme.min.css served from /opt/jupyterhub/lib64/python3.8/site-packages/jupyter_server/static/style/bootstrap-theme.min.css
[D 2022-01-17 00:42:34.345 ServerApp] Path style/index.css served from /opt/jupyterhub/lib64/python3.8/site-packages/jupyter_server/static/style/index.css
[D 2022-01-17 00:42:34.345 ServerApp] Path logo/logo.png served from /opt/jupyterhub/lib64/python3.8/site-packages/jupyter_server/static/logo/logo.png
[D 2022-01-17 00:42:34.346 ServerApp] 200 GET /login?next=%2Fnbconvert%2Fhtml%2Fsimulasi_1_2.ipynb%3Fdownload%3Dtrue (10.210.14.99) 22.33ms
[I 2022-01-17 00:42:37.884 ServerApp] 302 POST /login?next=%2Fnbconvert%2Fhtml%2Fsimulasi_1_2.ipynb%3Fdownload%3Dtrue (10.210.14.99) 43.39ms
[D 2022-01-17 00:42:37.978 ServerApp] Template paths:
    	/opt/jupyterhub/share/jupyter/nbconvert/templates/lab
    	/opt/jupyterhub/share/jupyter/nbconvert/templates/base
    	/home/demo/.local/share/jupyter
    	/home/demo/.local/share/jupyter/nbconvert/templates
    	/home/demo/.local/share/jupyter/nbconvert/templates/compatibility
    	/opt/jupyterhub/share/jupyter
    	/opt/jupyterhub/share/jupyter/nbconvert/templates
    	/opt/jupyterhub/share/jupyter/nbconvert/templates/compatibility
    	/usr/local/share/jupyter
    	/usr/local/share/jupyter/nbconvert/templates
    	/usr/local/share/jupyter/nbconvert/templates/compatibility
    	/usr/share/jupyter
    	/usr/share/jupyter/nbconvert/templates
    	/usr/share/jupyter/nbconvert/templates/compatibility
    	/opt/jupyterhub/share/jupyter/nbconvert/templates
[D 2022-01-17 00:42:37.981 ServerApp] Applying preprocessor: TagRemovePreprocessor
[D 2022-01-17 00:42:37.986 ServerApp] Applying preprocessor: RegexRemovePreprocessor
[D 2022-01-17 00:42:38.003 ServerApp] Applying preprocessor: coalesce_streams
[D 2022-01-17 00:42:38.020 ServerApp] Applying preprocessor: HighlightMagicsPreprocessor
[D 2022-01-17 00:42:38.036 ServerApp] Applying preprocessor: CSSHTMLHeaderPreprocessor
[D 2022-01-17 00:42:38.042 ServerApp] Attempting to load template index.html.j2
[D 2022-01-17 00:42:38.042 ServerApp]     template_paths: /opt/jupyterhub/share/jupyter/nbconvert/templates/lab:/opt/jupyterhub/share/jupyter/nbconvert/templates/base:/home/demo/.local/share/jupyter:/home/demo/.local/share/jupyter/nbconvert/templates:/home/demo/.local/share/jupyter/nbconvert/templates/compatibility:/opt/jupyterhub/share/jupyter:/opt/jupyterhub/share/jupyter/nbconvert/templates:/opt/jupyterhub/share/jupyter/nbconvert/templates/compatibility:/usr/local/share/jupyter:/usr/local/share/jupyter/nbconvert/templates:/usr/local/share/jupyter/nbconvert/templates/compatibility:/usr/share/jupyter:/usr/share/jupyter/nbconvert/templates:/usr/share/jupyter/nbconvert/templates/compatibility:/opt/jupyterhub/share/jupyter/nbconvert/templates
[E 2022-01-17 00:42:38.174 ServerApp] nbconvert failed: 'tuple' object is not callable
    Traceback (most recent call last):
      File "/opt/jupyterhub/lib64/python3.8/site-packages/jupyter_server/nbconvert/handlers.py", line 121, in get
        output, resources = await run_sync(
      File "/opt/jupyterhub/lib64/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
      File "/opt/jupyterhub/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
        return await future
      File "/opt/jupyterhub/lib64/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
        result = context.run(func, *args)
    TypeError: 'tuple' object is not callable
[W 2022-01-17 00:42:38.175 ServerApp] 500 GET /nbconvert/html/simulasi_1_2.ipynb?download=true (10.210.14.99): nbconvert failed: 'tuple' object is not callable
[D 2022-01-17 00:42:38.175 ServerApp] Using contents: services/contents
[D 2022-01-17 00:42:38.175 ServerApp] Using contents: services/contents
[E 2022-01-17 00:42:38.178 ServerApp] {
      "Host": "10.210.14.53:8888",
      "Connection": "keep-alive",
      "Cache-Control": "max-age=0",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Referer": "http://10.210.14.53:8888/login?next=%2Fnbconvert%2Fhtml%2Fsimulasi_1_2.ipynb%3Fdownload%3Dtrue",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "session=.eJwtkN1OwzAMRt8lF1xNa5w0f5UmHgShyElsNtF1o00lEOLd8QQXufliHx_7W2VeaTuriXHe6KDypalJsa81sAljAA9NW20imMrGkCEAsNCgIprEYzJkq7eBC1r2EZBKlIw5eeuj14RJ-wAxonFUqvNprI6TTcaDD9Eb6wJrQVRKxVZAaKWOSkTutF5xoaWrqa-7qNVt5dxv77SIoUveOB1G0swUUxibTw4ITYjFFYBW2ZfCKKSGb3nr2Pct82XutEr7HfeNmnzOt4ozSSLUg8RvlM-Xrd_WLzW9qHPv92kYQB-NPBiPzk5RRz0Ic92XYZbS4Tnz3LPNjzmXdqJPvN5nygW3c77JFii0p_-ahwedPnbaZfrrQYnF-ndyUD-_ERV67w.YeKzZQ.jTgptIUiIr62KdD0-UpA2Q8A2zE; jupyterhub-session-id=f1fb2069dab544fb898851de2328b8c1; ajs_user_id=7e8319f9-e7f8-420c-a506-1c4688ec5145; ajs_anonymous_id=59fc202e-97bc-43b4-84aa-5411ecf3fb26; _xsrf=2|b9532f98|59de6e8c1943775a2f2cf7674ef77e7d|1642351263; username-10-210-14-53-8888=\"2|1:0|10:1642351357|26:username-10-210-14-53-8888|44:NWY1ZDIxNGM4YjhlNGIyMTg5ZTdlZWI4ZGM5ODU4YjE=|7ba3627b50beb6b5f8b71f35b790ce1def947de521763fbeefe3350f64202c9f\""
    }
[E 2022-01-17 00:42:38.178 ServerApp] 500 GET /nbconvert/html/simulasi_1_2.ipynb?download=true (10.210.14.99) 292.17ms referer=http://10.210.14.53:8888/login?next=%2Fnbconvert%2Fhtml%2Fsimulasi_1_2.ipynb%3Fdownload%3Dtrue
[D 2022-01-17 00:42:39.960 ServerApp] Initializing websocket connection /api/kernels/c5749d67-3a10-47b1-a36e-6e7204abeec5/channels
[W 2022-01-17 00:42:39.961 ServerApp] 404 GET /api/kernels/c5749d67-3a10-47b1-a36e-6e7204abeec5/channels?session_id=3f7815cc-74e5-4945-a6cb-6e544d87790e (10.210.14.99): Kernel does not exist: c5749d67-3a10-47b1-a36e-6e7204abeec5
[D 2022-01-17 00:42:39.961 ServerApp] Using contents: services/contents
[W 2022-01-17 00:42:39.963 ServerApp] 404 GET /api/kernels/c5749d67-3a10-47b1-a36e-6e7204abeec5/channels?session_id=3f7815cc-74e5-4945-a6cb-6e544d87790e (10.210.14.99) 3.91ms referer=None

</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by davidbrochart** [comment]
Thanks for reporting, I opened https://github.com/jupyter-server/jupyter_server/pull/667.
