### ISSUE TITLE
Error is thrown when Dialog has no buttons

### ISSUE THREAD

**Issue by mnowacki-b** [jupyterlab/jupyterlab#11897]
## Description
Seems there are insufficient checks being performed in `apputils` Dialog class. When a dialog with no buttons is created it results in an error. The dialog is still visible but in the console you can see an error log.

## Reproduce

1. Create a new dialog without any buttons:
```ts
import {]
  Dialog
} from '@jupyterlab/apputils';

const dialog = new Dialog({
    title: 'title',
    body: createPreformattedTextWidget('body'),
    buttons: [],
    hasClose: false,
  });
```
2. launch the dialog:
```ts
dialog.launch()
```
3. Observe the console log:
error:
```
TypeError: Cannot read properties of undefined (reading 'focus')
    at Dialog.onAfterAttach (dialog.js:212:1)
    at Dialog.Widget.processMessage (index.es6.js:1445:1)
    at invokeHandler (index.es6.js:444:1)
    at Object.sendMessage (index.es6.js:180:1)
    at Function.attach (index.es6.js:1838:9)
    at dialog.js:130:13
 ```

## Expected behavior

There should be no errors.

## Context

- Operating System and version: macOS Big Sure
- Browser and version: Chrome 97.0.4692.7
- JupyterLab version: 3.2.5

**Comment by mnowacki-b** [comment]
Maybe adding a check here:
https://github.com/jupyterlab/jupyterlab/blob/80a00385b776ce2bafbac0e65e5ef6aa36421023/packages/apputils/src/dialog.tsx#L252
to see if `_primary` is set, ignoring the focus if it is not set?
```ts
if (this._primary) {
  this._primary.focus();
}
```
Or perhaps here:
https://github.com/jupyterlab/jupyterlab/blob/80a00385b776ce2bafbac0e65e5ef6aa36421023/packages/apputils/src/dialog.tsx#L123
if no button is present default to focus on the body?
```ts
this._primary = this._buttonNodes[this._defaultButton] || body;
```

**Comment by mnowacki-b** [comment]
Another area that would require some change is here:
https://github.com/jupyterlab/jupyterlab/blob/80a00385b776ce2bafbac0e65e5ef6aa36421023/packages/apputils/src/dialog.tsx#L395

**Comment by anngedeus** [comment]
Hello, I would like to work on this issue. If it is still available

**Comment by mnowacki-b** [comment]
I was planing on working on it but haven't started yet. So if you like to work on it go for it.

**Comment by jayeshsingh9767** [comment]
Looks like this issue is fixed and merged, its better if we close the PR.

**Comment by fcollonval** [comment]
Good catch @jayeshsingh9767 and sorry for the late feedback
