### ISSUE TITLE
Fast forward button in notebook toolbar has tooltip " and "

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#11898]
The fast-forward button in the notebook toolbar has the wrong tooltip.

## Description

The ⏩ (fast forward) button in the notebook toolbar should have a tooltip that reads, in English, "Restart Kernel and Run All Cells …". This button was introduced in #8024.

Instead, this button has the tooltip " and " (with a space before and after the word) with no additional content. You can verify this by inspecting the element in your browser.

![Screen Shot 2022-01-18 at 3 33 30 PM](https://user-images.githubusercontent.com/93281816/150036186-8a5bc180-e564-4dd0-9e94-662362946e76.png)

If you hover over a *disabled* fast-forward button, the tooltip is complete and present.

## Reproduce

Open a notebook using JupyterLab (tip of `master` branch). Hover over the ⏩ button on the toolbar.

## Expected behavior

A complete, comprehensible tooltip appears.

## Context

- Operating System and version: macOS 11.6.2 (Big Sur)
- Browser and version: Firefox 91.4.1esr (64-bit), Chrome 97.0.4692.71 (Official Build) (x86_64)
- JupyterLab version: 4.0.0a19

**Comment by krassowski** [comment]
It sounds like related to "semantic commands" rewrite in https://github.com/jupyterlab/jupyterlab/pull/11386. It might have something to do with `concatenateTexts` (below)?

https://github.com/jupyterlab/jupyterlab/blob/50fa0047d63287005a2c3b1d8f5bfedfe56cde7e/packages/application/src/utils.ts#L119-L140

**Comment by JasonWeill** [comment]
Still shows up in tip-of-`master`
