### ISSUE TITLE
Is there a plugin that can fold functions?

### ISSUE THREAD

**Issue by icankeep** [jupyterlab/jupyterlab#11906]
just like this:

![image](https://user-images.githubusercontent.com/39434627/150488671-4c496812-dc18-4ea2-aae1-c22098a3e29c.png)

**Comment by krassowski** [comment]
No plugin needed, just enable it in the settings (/`Advanced Settings Editor`):
- for notebook code cells: `Notebook` → `{ "codeCellConfig": { "codeFolding": true } }`
- for text editor: `Text Editor` → `{ "editorConfig": { "codeFolding": true } }`

**Comment by icankeep** [comment]
thank you for your reply, this feature is very nice
