### ISSUE TITLE
Explicitly specify issue triage label

### ISSUE THREAD

**Issue by jweill-aws** [jupyterlab/jupyterlab#11911]
### Problem

Per comments in  https://github.com/jupyterlab/jupyterlab-probot/pull/11 (https://github.com/jupyterlab/jupyterlab-probot/pull/11#issuecomment-1018725789) the bot is tagging all issues with `status:Needs Triage`, even issues in repositories without a triage process.

### Proposed Solution

Explicitly specify the triage label so that jupyterlab-probot can avoid using a default value for this property. Repos without a triage label will not be tagged with a default triage label.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/11912
