### ISSUE TITLE
jupyter labextension list should indicate what directories the extensions are in.

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#1192]
Instead of just the "OK" for validation, `jupyter labextension list` should list the directory the extension is in so you can verify that it is the correct installation.

**Comment by jasongrout** [comment]
I think this is obsolete now? @blink1073?

**Comment by blink1073** [comment]
This is still relevant because extensions can come from `<sys-prefix>` or the app dir, with similar semantics to `pip --user`.  You may also want an indication of which ones are linked.

**Comment by blink1073** [comment]
Fixed by #2409.
