### ISSUE TITLE
Add column selection mode

### ISSUE THREAD

**Issue by icankeep** [jupyterlab/jupyterlab#11926]
1. Is there a plugin that supports cursor multiple selection?
like this
![image](https://user-images.githubusercontent.com/39434627/150927747-a5b5193a-cc4f-41f1-a8bb-0e6bfcc41f96.png)

2. Can jupyterlab execute the cells of the specified tag?

**Comment by jweill-aws** [comment]
In what application did you take that screen shot? What does column selection mode let the user do?

**Comment by fcollonval** [comment]
For the first point: you can turn on the feature in a code editor by pressing `Alt`
For the second one see #12069

**Comment by icankeep** [comment]
> For the first point: you can turn on the feature in a code editor by holding `Alt` For the second one see #12069

Thank you. It would be better if there is a document related to the tips of jupyter lab
