### ISSUE TITLE
Align heading collapse buttons with corresponding <h> tag in rendered markdown

### ISSUE THREAD

**Issue by Pugio** [jupyterlab/jupyterlab#11924]
### Problem

Currently, the collapse button (triangle) is rendered at the very center of each cell:
![image](https://user-images.githubusercontent.com/286180/150900754-f144013b-f298-4004-953f-b52e85166ec9.png)

This breaks the connection between the heading and the collapse button, especially for very large cells where a random triangle right in the middle is unclear and hard to discover.

### Proposed Solution

Add a class to the collapse button representing its corresponding header level (as the Classic notebook does), e.g.:

[packages/cells/src/widgets.ts#L1580](https://github.com/jupyterlab/jupyterlab/blob/4dc0ec21fef81c18a912ea358800f5fd7e568dfa/packages/cells/src/widget.ts#L1580)
```typescript
collapseButton.className = `jp-Button jp-mod-minimal ${HEADING_COLLAPSER_CLASS} ${HEADING_COLLAPSER_CLASS}-h${this.headingInfo.level}`;
```

Then add the corresponding rules to `widgets.css` to position the collapse button based on the heading level. Resulting in:

![image](https://user-images.githubusercontent.com/286180/150901176-fa3969a8-676e-4ee2-b8ab-5fa6571aea72.png)

I have pull request ready to go, but am creating an issue first (as mentioned in the Contributing document).

**Comment by fcollonval** [comment]
Thanks for the proposal
I definitely agree it looks much better and improve user experience. i'll make comment on the associated PR
