### ISSUE TITLE
How can the left/right sidebar show text rather than icon?

### ISSUE THREAD

**Issue by zymmatt** [jupyterlab/jupyterlab#11936]
![icon](https://user-images.githubusercontent.com/46815660/151115900-308dad1e-f9a4-4827-98cf-fded51733662.png)
<img width="470" alt="text" src="https://user-images.githubusercontent.com/46815660/151115917-f982e290-3eb4-427c-9229-9efb841a559a.png">

I hope to show the title of each sidebar plugin. Shall I add something into advanced settings, or install any extension ?

**Comment by zymmatt** [comment]
I found the solution by myself, just define the property : class widget.title.label
<img width="386" alt="企业微信截图_16432500037962" src="https://user-images.githubusercontent.com/46815660/151280244-3fe753a0-33c9-4485-a38b-59e3cdb4dc81.png">

**Comment by jasongrout** [comment]
Awesome, thanks for updating this issue with the solution!
