### ISSUE TITLE
Adding more options to notebook-pdf conversion

### ISSUE THREAD

**Issue by KhaoulaSoussi** [jupyterlab/jupyterlab#11935]
### Problem

I would like it if there is a way to export the code in the notebook only (no outputs) as pdf without having to manually clear the outputs because you may want to share the code only, if the output was there just for testing purposes.
And also the opposite because in many cases you may want to share the outputs only, if you just want the code for yourself.

### Proposed solution

In the notebook editor, once the "File->Download as-> pdf with Latex" is clicked, a dialogue with checkbox options (Output Only, Code Only) should pop up. Once the user chooses an option and clicks a confirm button the pdf is generated.

### Additional context

Ideally, there should also be useful option combinations like: Code + Graphs Only (i.e., not all outputs) ; Code + No Comments + Outputs ...

**Comment by KhaoulaSoussi** [comment]
I actually want to work on this feature myself. I decided to post it so that I can receive some feedback from experienced contributors since I am a new one.
Please tell me what you think about the feature in general. Is it feasible? How long would it take me to complete it? and what possible problems should I keep in mind while working on it?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/new-contributor-to-jupyter-noteook-got-stuck-in-the-configuration-of-the-development-environment/12748/4

**Comment by KhaoulaSoussi** [comment]
@meeseeksmachine I believe you wanted to share another link, no?

**Comment by krassowski** [comment]
Thank you for opening this one @KhaoulaSoussi. It looks like this was previously discussed in https://github.com/jupyterlab/jupyterlab/issues/8129#issuecomment-609089019. You are very welcome to work on this, and I personally very like the idea of having a pop-up window allowing to cusomize the nbconvert settings (ideally based on the results of querying the server to return the nbconvert options).

Could we close this one and consolidate conversation into #8129?

PS. @meeseeksmachine is our bot which automatically links to Discourse topics which mention specific issues.

**Comment by KhaoulaSoussi** [comment]
Thank you @krassowski, I'll close this issue and consolidate conversation into the other one.
I didn't know @meeseeksmachine is a bot hahahaha
