### ISSUE TITLE
Drop the dependency on `ipykernel`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#11958]
### Problem

Currently `jupyterlab` doesn't **directly** depend on `ipykernel`.

The upcoming drop of the `nbclassic` dependency for JupyterLab 4.0 started in https://github.com/jupyterlab/jupyterlab/pull/11894 has the side-effect of also dropping the transitive `ipykernel` dependency:

`jupyterlab` -> `nbclassic` -> `notebook` -> `ipykernel`

This can also be inspected in a new environment:

```bash
mamba create -n tmp -c conda-forge jupyterlab=3 pipdeptree -y
conda activate tmp
pipdeptree -ar
```

Gives:

![image](https://user-images.githubusercontent.com/591645/151561989-03a2039a-faff-4b0c-a757-61ae733cea9d.png)

### Proposed Solution

There are two options:

1. We add `ipykernel` as an explicit dependency for `jupyterlab`. This means users can expect to find a kernel ready to use on `pip install jupyterlab`
2. We don't add `ipykernel` as an explicit dependency for `jupyterlab`. End users will have to install `ipykernel` manually when installing `jupyterlab`, for example with:

```
pip install jupyterlab ipykernel
mamba install -c conda-forge jupyterlab ipykernel
```

Since Jupyter is language agnostic, option 2 is cleaner and lets users choose the kernel(s) they want from the start. For example they could be using `xeus-python` instead of `ipykernel` for the Python language.

Option 1 is however more convervative, which might be expected by users who want things "that just work".

### Additional context

Noticed when dropping `nbclassic`: https://github.com/jupyterlab/jupyterlab/pull/11894#issuecomment-1024011925

Related: https://github.com/jupyterlab/jupyterlab/pull/11334

**Comment by echarles** [comment]
I like things "that just work".

**Comment by Zsailer** [comment]
I think, for historical reasons, we have to require ipykernel.

**Comment by jtpio** [comment]
`ipykernel` has been added as an explicit dependency in https://github.com/jupyterlab/jupyterlab/pull/11894 for now

**Comment by vidartf** [comment]
+1. It makes sense for me that the JupyterLab *python* package includes ipykernel. Low cost, high reward 👍

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/11894, since `ipykernel` is now an explicit dependency in JupyterLab:

https://github.com/jupyterlab/jupyterlab/blob/24d9c64fbfd032cf13a1fd455a55452197d65845/setup.cfg#L33-L34
