### ISSUE TITLE
Can't load module from jupyter lab

### ISSUE THREAD

**Issue by suuuehgi** [jupyterlab/jupyterlab#11959]
## Description

Jupyter fails to load module although it's installed on a freshly installed conda env.

## Reproduce

```
$ conda create --name test -c conda-forge jupyter
$ conda activate test
$ jupyter lab .
```

```
import bidict
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_739729/2317910766.py in <module>
----> 1 import bidict

ModuleNotFoundError: No module named 'bidict'

!pip install --user bidict
Requirement already satisfied: bidict in /home/username/.local/lib/python3.10/site-packages (0.21.4)
```

![demo](https://user-images.githubusercontent.com/7861774/151604196-fb428e47-dbc3-409c-9629-164f15dded49.jpg)

Whereat from ipython interface, it works.

## Context

- Operating System and version: `Linux hostname 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- JupyterLab version: 3.2.0

**Comment by krassowski** [comment]
Thank you for asking. This is not a bug in JupyterLab - by using `!pip` you are very likely installing the module in a different location than the where the kernel is located. Try using `%pip install` instead (never use `!pip` always use `%pip`); you may also need to restart kernel to see this module work (which is something that `%pip` magic will advise you to do).

Also, I would recommend using a proper virtual environment solution over installing packages to a local user library - this may lead to conflicts in the future.

I will mark this as answered and remove the bug label - this is not an issue with JupyterLab, but a consequence of how IPython kernel executes shell commands with the bang syntax vs how it executes `%`. See https://stackoverflow.com/a/70604999/6646912 and https://github.com/ipython/ipython/pull/11524 for more details.

**Comment by suuuehgi** [comment]
I thank you for the nice answer! I will try this on monday, when I'm back in office.

One question: `!pip` was my second attempt after installing it using conda. Beforehand I tried `conda create --name test -c conda-forge jupyter bidict` but `bidict` was not found by jupyter.
Was that what you mean by "proper virtual environment solution"?

**Comment by krassowski** [comment]
Yes, but if you intend to install JupyterLab, you would likely want to install `jupyterlab` conda package too. Very likely you were running a JupyterLab/kernel installation outside of the conda environment you created. You need to activate that environment and only then start JupyterLab (or use something like https://github.com/Anaconda-Platform/nb_conda_kernels)

**Comment by suuuehgi** [comment]
> Very likely you were running a JupyterLab/kernel installation outside of the conda environment you created.

I'm 99 % sure that I ran it within the environment but indeed, I forgot to install `jupyterlab`. Whatever mess is happening there, I'm gonna try it again on Monday with the aforementioned package installed.

**Comment by suuuehgi** [comment]
I was within the conda-env but it was a mess with conda and local pip. I fixed it the conda / modern way: Burn everything to the ground.

I deleted everything related to conda, pip and jupyter within my home folder and recreated the conda-env now without pip.

Now it works ...
