### ISSUE TITLE
Pause on exception button does not show up

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#11965]
Giving a spin to 3.3 alpha because I very much need the "pause on exception" debugger feature. I noticed that the button is missing. I guess a specific kernel version is required for it to show up based on:

https://github.com/jupyterlab/jupyterlab/blob/f7aa928c48fb6cef71d21e661cb8832185aaaac1/packages/debugger-extension/src/index.ts#L733-L735

### Problem

Hiding buttons when features are not available makes the features less discoverable. When we added debugger many users did not realise that they just needed to update ipykernel/xeus kernel to get it working and we got a lot of questions from confused users, exacerbated by the fact that some of them were genuine issues with how debugger capability was detected.
 
### Proposed Solution

- [ ] Always show the pause button; when it is not available make it disabled add a tooltip "Your kernel version does not support pausing on exception yet"
- [ ] Document what kernels are know to work with this feature in user-facing documentation

### Context

We discussed this problem for the debugger bug icon in: https://github.com/jupyterlab/jupyterlab/pull/10727#issuecomment-892534609 and https://github.com/jupyterlab/jupyterlab/pull/10727#issuecomment-892819037

We also use a condition like this for rich variable rendering:

https://github.com/jupyterlab/jupyterlab/blob/f7aa928c48fb6cef71d21e661cb8832185aaaac1/packages/debugger-extension/src/index.ts#L417-L419

**Comment by krassowski** [comment]
Would anyone mind checking if pause on breakpoint works for them with https://github.com/ipython/ipykernel main branch? It works in the latest stable (6.7) but did not work for me when I tried the latest commit.

**Comment by echarles** [comment]
I have tested with latest ipykernel main branch, and it looks to be working for me cc/ @andrewfulton9 

<img width="801" alt="Screenshot 2022-02-01 at 08 45 05" src="https://user-images.githubusercontent.com/226720/151930378-04a04a60-070e-4214-b280-97d421f18395.png">

**Comment by fcollonval** [comment]
:+1: with @krassowski to make it always visible but disabled if not available with a meaningful title.
