### ISSUE TITLE
Can I use JupyterLab as SQL IDE?

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#1197]
Does JupyterLab support, e.g., Teradata SQL? Or is SQL supported via magics for Python/R?

**Comment by blink1073** [comment]
Hi @dclong, JupyterLab supports the same set of languages and magics as the Jupyter Notebook: https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages.  It looks like no one has advertised a SQL kernel there, but:

Here is a possible kernel: https://github.com/jablonskim/jupyter-sql
And a possible magic: https://github.com/catherinedevlin/ipython-sql.

**Comment by jasongrout** [comment]
Closing as answered - @dclong, feel free to reopen to continue discussion if you'd like.
