### ISSUE TITLE
Shutdown from running panel vs. kernel menu gives different status indicators

### ISSUE THREAD

**Issue by Zsailer** [jupyterlab/jupyterlab#11984]
## Description

Clicking the "X" to shutdown a kernel in the "Running" Tab vs. clicking "Shut Down Kernel" in the Kernel Menu shows different, inconsistent status indicators. The screenshots below demonstrate the difference.

The "Shut Down Kernel" menu item causes the kernel status to go into a "No Kernel" and *"Idle"* state. See the kernel bubble in the top right corner and the status bar item at the bottom.

![Screen Shot 2022-02-02 at 9 05 26 AM](https://user-images.githubusercontent.com/2791223/152206082-b70a50cb-c459-4774-8c24-feae21b3f4f6.png)
![Screen Shot 2022-02-02 at 9 05 35 AM](https://user-images.githubusercontent.com/2791223/152206103-ae1442cd-5e14-4b3d-ab42-5121ae5f0576.png)

The "X" in the Running tab causes the kernel to go into a "No Kernel" and "Unknown" state.

![Screen Shot 2022-02-02 at 9 05 45 AM](https://user-images.githubusercontent.com/2791223/152206117-b9fca5e4-0e6b-4208-9e36-feb4975b30f0.png)
![Screen Shot 2022-02-02 at 9 05 53 AM](https://user-images.githubusercontent.com/2791223/152206138-0815831f-e55a-4a3d-af6c-9ccd4154a1ef.png)

## Reproduce

1. Open a notebook with a vanilla Python kernel.
2. Go to the "Kernel" menu and click "Shut Down Kernel". 
3. Observe the kernel status from the bubble in the top right corner of the notebook and the status bar at the bottom.
4. Open another notebook with vanilla Python kernel.
5. Go to the "Running" side panel on the right side of the screen
6. Click the "X" next to the second kernel
7. Observe the kernel status from the bubble in the top right corner of the notebook and the status bar at the bottom.

You will see different results, even though they are equivalent actions from a user's perspective.

## Expected behavior

Shutting down a kernel from the kernel menu or the running side panel should produce the same final status.

## Context

- Operating System and version:  Mac OS 
- Browser and version:  Chrome 97.x
- JupyterLab version:  3.2.x and above

**Comment by 3coins** [comment]
There is a similar issue in RTC mode, where the top kernel status doesn't match with the status bar. In this case, bottom status bar is showing the correct status, while the top kernel progress bar is empty.

<img width="1621" alt="Screen Shot 2022-02-04 at 12 47 45 PM" src="https://user-images.githubusercontent.com/289369/152601191-276bc1a5-093c-4a61-99a4-70c2fa9129f8.png">

### Reproduce

1. Open JupyterLab in collaborative mode. `jupyter lab --collaborative`
2. Open the same session in another browser.
3. Run this code inside a cell in browser 1.
```python
import time

for step in range(1, 20):
    print(f"Step {step}")
    time.sleep(10)
    
print('Done')
```
4. In Browser 1, both bottom status bar and top right kernel icon will show busy status.
5. Browser 2 will show the "Busy" indicator in bottom status bar, but top right icon looks like 〇 indicating idle status.
