### ISSUE TITLE
Editor hardcodes keybindings

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#12]
Tab, up arrow, and down arrow have hard-coded keybindings at https://github.com/jupyter/jupyterlab/blob/91e33ae71c9b7235cbd7270ef5c6746f1f5b1643/src/notebook/cells/editor.ts#L250. If it's not prohibitive, we should have these keys assigned at the application level so they can remapped by the user.

**Comment by blink1073** [comment]
Agreed.

**Comment by jasongrout** [comment]
I think this is sufficiently abstracted away now - the up/down arrows emit events, and tab doesn't appear in the key checking: https://github.com/jupyterlab/jupyterlab/blob/f378e7cbb512c6b8da6c96ab56e5ff7e4f78d658/packages/codemirror/src/editor.ts#L502
