### ISSUE TITLE
Enable Shell Support for Windows 10

### ISSUE THREAD

**Issue by eskirk** [jupyterlab/jupyterlab#120]
With the new native Linux shell coming to Windows 10, I had a friend of mine recommend that we set up Jupyter to recognize it so Windows users can actually use their own shell within Juypter. That would be a pretty neat ¯\_(ツ)_/¯

**Comment by blink1073** [comment]
I wholeheartedly like this idea, and would use it myself.  Will probably have to wait for the Windows 10 Anniversary Update (hopefully next month).

**Comment by eskirk** [comment]
Yeah it is definitely the next logical step for this project. I'd definitely be interested helping out once this is possible.

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyter/notebook/pull/3087, will be available in Notebook 5.3
