### ISSUE TITLE
`timeout` variable value not taking effect in notebook

### ISSUE THREAD

**Issue by jhlegarreta** [jupyterlab/jupyterlab#12018]
## Description

Jupyter notebooks seem not to take into account the execution `timeout` variable value.

We are developing a [Carpentries](https://carpentries.org/) lesson named [Introduction to dMRI](https://carpentries-incubator.github.io/SDC-BIDS-dMRI/)

We are using Jupyter Notebooks to develop our teaching materials. We are having issues to run the cells on one of our notebooks that require prolonged running times.

As it can be read in [this comment](https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/190#issuecomment-939490198), the notebook is not running for the specified amount of time.

## Reproduce

1. Clone the https://github.com/carpentries-incubator/SDC-BIDS-dMRI repository.
2. Checkout the [`IncreasePreprocessingCellExecutionTimeout` branch](https://github.com/jhlegarreta/SDC-BIDS-dMRI/tree/IncreasePreprocessingCellExecutionTimeout)
2. Install the requirements and download the necessary data. See the [setup documentation](https://carpentries-incubator.github.io/SDC-BIDS-dMRI/setup.html).
3. Start an ipython kernel.
4. Run the [`preprocessing` notebook](https://github.com/carpentries-incubator/SDC-BIDS-dMRI/blob/main/code/preprocessing.ipynb)
5. See that the cells with an increased execution time do not run for the specified amount of time, and they do not finish.

## Expected behavior

The offending cells should at least take the allocated time if not failing or if not finishing successfully before.

## Context

 - OS: Ubuntu 20.04.3 LTS
 - Browser: Firefox
 - Version 93.0 (64-bit)

The GitHub actions triggered by the related PR https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/190 demonstrates the problem as well, but the log seems to no longer be available. We could create a new PR upon request to demonstrate the problem.

**Comment by fcollonval** [comment]
Would it be possible to set up a live demo on [binder](https://mybinder.org/) (maybe a smaller reproducible case)?

**Comment by bollwyvl** [comment]
It appears that `cells/*metadata/timeout` is an [nbval-specific behavior](https://github.com/computationalmodelling/nbval/issues/40).


To bring this to the jupyterlab UI, one could add a third-party extension, but it's unclear what it would actually do...  interrupt the notebook?

**Comment by jhlegarreta** [comment]
Thanks both @fcollonval @bollwyvl for caring about this, and sorry for the late reply.

> Would it be possible to set up a live demo on [binder](https://mybinder.org/) (maybe a smaller reproducible case)?

Although we would very much like to be able to run the repository notebooks using binder, and despite having the access in the `README`:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI

It turns out that our data/the processing required by our data is too heavy to successfully run on `mybinder`, which has a 2 GB memory limitation. For the lesson at issue, we cannot use a smaller piece of data since the preprocessing only makes sense for a complete image volume.

I am unsure whether the effect can be seen by setting up the environment locally and setting the timeout value locally (e.g. to a very short time to see the cell is killed).

> It appears that cells/*metadata/timeout is an https://github.com/computationalmodelling/nbval/issues/40.

We do use `nbval` in our notebook to e.g. skip some cells:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/search?q=nbval&type=

I honestly have run out of ideas on how to investigate this.

**Comment by fcollonval** [comment]
I think we have a misunderstanding. The metadata `cells/*metadata/timeout` is not standard metadata (see [official format description]). It is only used by `nbval`. So other tools (such as JupyterLab) are ignoring it.

**Comment by jhlegarreta** [comment]
> I think we have a misunderstanding. The metadata cells/*metadata/timeout is not standard metadata (see [official format description]). It is only used by nbval. So other tools (such as JupyterLab) are ignoring it.

I assume the missing link "[official format description]" intended to point to https://nbformat.readthedocs.io/en/latest/format_description.html#cell-metadata. Thanks for the pointer.

Maybe I am mixing things due to a limited knowledge about the ecosystem behind. Sorry if that is the case.

So our aim is to validate and run all our notebooks using a GitHub workflow prior to merging a PR to avoid merging changes that break our notebooks. Thus, we need a way to automatically run our notebooks. We call our notebooks like:
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/blob/main/.github/workflows/build-test.yaml#L124

And for such purpose we are using `nbval`. It turns out that `nbval` has a timeout limit of 30 seconds, and hence our intended use of the metadata to try to bypass the limit.

Eventually, we would also like to compare the output of cells (where applicable).

We also wanted to skip some cells in the checks, which `nbval` was apparently allowing us to do with the `nbval-skip` tag (I may have found a way to execute those cells also, though).

We ignore if there is a native way to do all this. If there is, we would be happy to use it. If not, is there any other workaround?

Thanks.

**Comment by bollwyvl** [comment]
So... how is JupyterLab inviolved? Do you test with real browsers running cells? 

Perhaps this issue belongs on [nbval's issue tracker](https://github.com/computationalmodelling/nbval/issues)?

**Comment by jhlegarreta** [comment]
> Do you test with real browsers running cells?

AFAIK `nbval` allows `pytest` to discover the cells to execute and arranges the necessary things for `pytest` to run the cells (as if they were a regular Python method I guess). So it does not involve a browser.

If there is no native way to achieve the above goals these using `jupyter`, then it may be more an `nbval` issue, or maybe `jupyter` issue for allowing more metadata to achieve these in the standard metadata format?

**Comment by fcollonval** [comment]
Sorry for forgetting the link - but yes that was to nbformat.

I second Nick that the issue belong to `nbval`.

**Comment by jhlegarreta** [comment]
OK, thanks both. I'll open the issue in `nbval`'s repository. Closing it here.
