### ISSUE TITLE
Visual Regression Documentation CI check is failing

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#12023]
## Description

It looks like the main Visual Regression check now passes with the latest commit on master after restarting the CI:

https://github.com/jupyterlab/jupyterlab/actions/runs/1805191540

![image](https://user-images.githubusercontent.com/591645/152955587-e40f5334-6be9-4c7a-bef0-0fc28f9f3d73.png)

However the "Visual Regression Documentation" check seems to be failing:

![image](https://user-images.githubusercontent.com/591645/152955783-0848584b-32f7-4b2e-be6a-9463a4b9ff29.png)

We should double check whether this failure is relevant or not, since this seems related to the default side bar width.

## Reproduce

The latest commit on master: https://github.com/jupyterlab/jupyterlab/actions/runs/1805191540

**Comment by jtpio** [comment]
cc @fcollonval who might know if this needs to be investigated, or if we just need to update the reference snapshots.

**Comment by fcollonval** [comment]
There is an instability to the sidebar width (probably due to some race condition). It makes UI tests flaky. But up to now I could not figure out the root cause.

I think it could be solved if we address https://github.com/jupyterlab/jupyterlab/issues/9904.

**Comment by jtpio** [comment]
One of the failures looks relevant and might be related to the Settings UI:

![image](https://user-images.githubusercontent.com/591645/153187467-ed4f2a2a-40f5-4da3-8860-ffc10dff29c9.png)

Maybe we can look into updating the reference snapshots since the check seems to be failing consistently now.

**Comment by jtpio** [comment]
Reopening since the check is still failing.

**Comment by fcollonval** [comment]
I'm looking into a way to freeze the sidebar width

**Comment by jtpio** [comment]
Looks like the check might still be a bit flaky, as noticed with https://github.com/jupyterlab/jupyterlab/pull/11894 after a rebase: https://github.com/jupyterlab/jupyterlab/runs/5274832370?check_suite_focus=true

**Comment by jtpio** [comment]
Maybe there could be a way to manually grab the split panel handle (`lm-SplitPanel-handle`) and move the mouse to a arbitrary x position?

```ts
await page.mouse.down()
await page.mouse.move(x, y)
await page.mouse.up()
```

So we resize the sidebar like a user would do. Like we do here:

https://github.com/jupyterlab/jupyterlab/blob/c7b14eee863dc2b764378be5e9533ea2e7714d89/galata/test/documentation/general.test.ts#L65-L71

**Comment by fcollonval** [comment]
Yes it could be a workaround. I will try to set up a PR within the next days.
