### ISSUE TITLE
Gitter channel is still jupyter/jupyterlab.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1202]
Just want to point that out, I don't know how many user will/could be confused by that. 

There are pros and cons about staying where it is and migrating it.

**Comment by blink1073** [comment]
Jupyterhub is in Jupyterhub/Jupyterhub.  We could add a welcome message to the old room pointing to the new room, and eventually the top google result would point to the new room.

**Comment by jasongrout** [comment]
+1 for changing to lessen confusion. Any objections, anyone? CC @SylvainCorlay, @afshin, @ellisonbg....
