### ISSUE TITLE
File->Print causes notebook to hang

### ISSUE THREAD

**Issue by callegar** [jupyterlab/jupyterlab#12031]
## Description

Trying to print a notebook from inside the browser causes everything to hang.  Sometimes, the browser shows a green banner saying "Connecting" at the bottom.

If this is a browser sandboxing issue, jupyter should probably suggest how to work it around at startup, unless it can work it around itself.

## Reproduce

1. Open a notebook using `jupyter lab`. I am currently using chrome as the browser.
2. Click on File->Print
3. See the browser window hang

When the notebook hangs, nothing works in it.

## Expected behavior

The browser should open its print preview window.

## Context

- Operating System and version:  Ubuntu 20.04
- Browser and version:  Chrome 99.0.4844.17 beta
- JupyterLab version:  3.2.9

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /home/.../PythonEnvs/Py3.8-devel/bin
        /home/.../.local/bin
        /home/.../bin
        /usr/local/texlive/2021/bin/x86_64-linux
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games
        /snap/bin

sys.path:
        /home/.../PythonEnvs/Py3.8-devel/bin
        /usr/lib/python38.zip
        /usr/lib/python3.8
        /usr/lib/python3.8/lib-dynload
        /home/.../PythonEnvs/Py3.8-devel/lib/python3.8/site-packages

sys.executable:
        /home/.../PythonEnvs/Py3.8-devel/bin/python

sys.version:
        3.8.10 (default, Nov 26 2021, 20:14:08) 
        [GCC 9.3.0]

platform.platform():
        Linux-5.13.0-28-generic-x86_64-with-glibc2.29

which -a jupyter:
        /home/.../PythonEnvs/Py3.8-devel/bin/jupyter

pip list:
        Package                       Version
        ----------------------------- -----------
        alabaster                     0.7.12
        anyio                         3.5.0
        appdirs                       1.4.4
        argon2-cffi                   21.3.0
        argon2-cffi-bindings          21.2.0
        arrow                         1.2.2
        astroid                       2.9.3
        async-generator               1.10
        atomicwrites                  1.4.0
        attrs                         21.4.0
        autopep8                      1.6.0
        Babel                         2.9.1
        backcall                      0.2.0
        binaryornot                   0.4.4
        black                         22.1.0
        bleach                        4.1.0
        CacheControl                  0.12.6
        certifi                       2021.10.8
        cffi                          1.15.0
        chardet                       4.0.0
        charset-normalizer            2.0.11
        click                         8.0.3
        cloudpickle                   2.0.0
        colorama                      0.4.3
        contextlib2                   0.6.0
        control                       0.9.1
        cookiecutter                  1.7.3
        cryptography                  36.0.1
        cvxopt                        1.2.7
        cvxpy                         1.1.18
        cycler                        0.11.0
        Cython                        0.29.27
        debugpy                       1.5.1
        decorator                     5.1.1
        defusedxml                    0.7.1
        deprecation                   2.1.0
        diff-match-patch              20200713
        dill                          0.3.1.1
        distlib                       0.3.0
        distro                        1.4.0
        docutils                      0.17.1
        ecos                          2.0.10
        entrypoints                   0.4
        flake8                        4.0.1
        fonttools                     4.29.1
        future                        0.18.2
        helpdev                       0.7.1
        html5lib                      1.0.1
        idna                          3.3
        imagesize                     1.3.0
        importlib-metadata            4.10.1
        importlib-resources           5.4.0
        inflection                    0.5.1
        intervaltree                  3.1.0
        ipaddr                        2.2.0
        ipykernel                     6.9.0
        ipython                       7.31.1
        ipython-genutils              0.2.0
        ipywidgets                    7.6.5
        isort                         5.10.1
        jedi                          0.18.1
        jeepney                       0.7.1
        jellyfish                     0.9.0
        Jinja2                        3.0.3
        jinja2-time                   0.2.0
        json5                         0.9.6
        jsonschema                    4.4.0
        jupyter                       1.0.0
        jupyter-client                7.1.2
        jupyter-console               6.4.0
        jupyter-core                  4.9.1
        jupyter-packaging             0.10.1
        jupyter-server                1.13.5
        jupyterlab                    3.2.9
        jupyterlab-pygments           0.1.2
        jupyterlab-server             2.10.3
        jupyterlab-widgets            1.0.2
        keyring                       23.5.0
        kiwisolver                    1.3.2
        lazy-object-proxy             1.7.1
        lockfile                      0.12.2
        markdown-it-py                1.1.0
        MarkupSafe                    2.0.1
        matplotlib                    3.5.1
        matplotlib-inline             0.1.3
        mccabe                        0.6.1
        mistune                       0.8.4
        mpmath                        1.2.1
        msgpack                       0.6.2
        multiprocess                  0.70.9
        mypy-extensions               0.4.3
        nbclassic                     0.3.5
        nbclient                      0.5.10
        nbconvert                     6.4.1
        nbformat                      5.1.3
        nest-asyncio                  1.5.4
        nose                          1.3.7
        notebook                      6.4.8
        numpy                         1.22.2
        numpydoc                      1.2
        osqp                          0.6.2.post5
        packaging                     21.3
        pandas                        1.4.0
        pandocfilters                 1.5.0
        parso                         0.8.3
        pathspec                      0.9.0
        pathtools                     0.1.2
        pep517                        0.8.2
        pexpect                       4.8.0
        pickleshare                   0.7.5
        PICOS                         2.3.13
        Pillow                        9.0.1
        pip                           22.0.3
        pkg_resources                 0.0.0
        platformdirs                  2.4.1
        pluggy                        1.0.0
        ply                           3.11
        poyo                          0.5.0
        progress                      1.5
        prometheus-client             0.13.1
        prompt-toolkit                3.0.27
        psutil                        5.9.0
        ptyprocess                    0.7.0
        pycodestyle                   2.8.0
        pycparser                     2.21
        pydocstyle                    6.1.1
        pyee                          8.2.2
        pyflakes                      2.4.0
        Pygments                      2.11.2
        pylint                        2.12.2
        pyls-black                    0.4.7
        pyls-spyder                   0.4.0
        pyparsing                     3.0.7
        pyppeteer                     0.2.6
        PyQt5                         5.12.3
        PyQt5-sip                     12.9.1
        PyQtWebEngine                 5.12.1
        pyrsistent                    0.18.1
        python-dateutil               2.8.2
        python-jsonrpc-server         0.4.0
        python-language-server        0.36.2
        python-lsp-black              1.1.0
        python-lsp-jsonrpc            1.0.0
        python-lsp-server             1.3.3
        python-slugify                5.0.2
        pytoml                        0.1.21
        pytz                          2021.3
        pyxdg                         0.27
        PyYAML                        5.3.1
        pyzmq                         22.3.0
        QDarkStyle                    3.0.2
        qdldl                         0.1.5.post0
        qstylizer                     0.2.1
        QtAwesome                     1.1.1
        qtconsole                     5.2.2
        QtPy                          2.0.1
        quantiphy                     2.15.0
        regex                         2021.11.10
        requests                      2.27.1
        requests-unixsocket           0.2.0
        retrying                      1.3.3
        rope                          0.22.0
        Rtree                         0.9.7
        scikits.odes                  2.6.3
        scipy                         1.8.0
        scs                           3.1.0
        SecretStorage                 3.3.1
        Send2Trash                    1.8.0
        setuptools                    60.8.1
        setuptools-scm                6.3.2
        six                           1.16.0
        sniffio                       1.2.0
        snowballstemmer               2.2.0
        sortedcontainers              2.4.0
        sounddevice                   0.4.1
        Sphinx                        4.4.0
        sphinxcontrib-applehelp       1.0.2
        sphinxcontrib-devhelp         1.0.2
        sphinxcontrib-htmlhelp        2.0.0
        sphinxcontrib-jsmath          1.0.1
        sphinxcontrib-qthelp          1.0.3
        sphinxcontrib-serializinghtml 1.1.5
        spyder                        5.2.2
        spyder-kernels                2.2.1
        sympy                         1.9
        terminado                     0.13.1
        testpath                      0.5.0
        text-unidecode                1.3
        textdistance                  4.2.2
        three-merge                   0.1.1
        tinycss                       0.4
        tinycss2                      1.1.1
        toml                          0.10.2
        tomli                         2.0.1
        tomlkit                       0.7.0
        tornado                       6.1
        tqdm                          4.62.3
        traitlets                     5.1.1
        typed-ast                     1.4.3
        typing_extensions             4.0.1
        ujson                         5.1.0
        urllib3                       1.26.8
        watchdog                      2.1.6
        wcwidth                       0.2.5
        webencodings                  0.5.1
        websocket-client              1.2.3
        websockets                    9.1
        wheel                         0.36.2
        whichcraft                    0.6.1
        widgetsnbextension            3.5.1
        wrapt                         1.13.3
        wurlitzer                     3.0.2
        yapf                          0.32.0
        zipp                          3.7.0
</pre>
</details>

<details><summary>Command Line Output</summary>
This is the end of the debug log, where the print action is required...
<pre>
[D 2022-02-09 15:29:54.305 ServerApp] Accepting token-authenticated connection from 127.0.0.1
[D 2022-02-09 15:29:54.307 ServerApp] 200 GET /api/contents/Report_demo?content=1&1644416994300 (127.0.0.1) 3.18ms
[D 2022-02-09 15:29:54.796 ServerApp] Accepting token-authenticated connection from 127.0.0.1
[D 2022-02-09 15:29:54.798 ServerApp] 200 GET /api/sessions?1644416994791 (127.0.0.1) 2.73ms
[D 2022-02-09 15:29:54.800 ServerApp] Accepting token-authenticated connection from 127.0.0.1
[D 2022-02-09 15:29:54.802 ServerApp] 200 GET /api/kernels?1644416994794 (127.0.0.1) 2.39ms
[D 2022-02-09 15:29:56.651 ServerApp] Accepting token-authenticated connection from 127.0.0.1
[D 2022-02-09 15:29:56.766 ServerApp] Template paths:
    	/home/.../PythonEnvs/Py3.8-devel/share/jupyter/nbconvert/templates/lab
    	/home/.../PythonEnvs/Py3.8-devel/share/jupyter/nbconvert/templates/base
    	/home/.../.local/share/jupyter
    	/home/.../.local/share/jupyter/nbconvert/templates
    	/home/.../.local/share/jupyter/nbconvert/templates/compatibility
    	/home/.../PythonEnvs/Py3.8-devel/share/jupyter
    	/home/.../PythonEnvs/Py3.8-devel/share/jupyter/nbconvert/templates
    	/home/.../PythonEnvs/Py3.8-devel/share/jupyter/nbconvert/templates/compatibility
    	/usr/local/share/jupyter
    	/usr/local/share/jupyter/nbconvert/templates
    	/usr/local/share/jupyter/nbconvert/templates/compatibility
    	/usr/share/jupyter
    	/usr/share/jupyter/nbconvert/templates
    	/usr/share/jupyter/nbconvert/templates/compatibility
    	/home/.../.local/share/jupyter/nbconvert/templates
    	/home/.../PythonEnvs/Py3.8-devel/share/jupyter/nbconvert/templates
[D 2022-02-09 15:29:56.772 ServerApp] Applying preprocessor: TagRemovePreprocessor
[D 2022-02-09 15:29:56.797 ServerApp] Applying preprocessor: RegexRemovePreprocessor
[D 2022-02-09 15:29:56.870 ServerApp] Applying preprocessor: coalesce_streams
[D 2022-02-09 15:29:56.937 ServerApp] Applying preprocessor: HighlightMagicsPreprocessor
[D 2022-02-09 15:29:57.006 ServerApp] Applying preprocessor: CSSHTMLHeaderPreprocessor
[D 2022-02-09 15:29:57.030 ServerApp] Attempting to load template index.html.j2
[D 2022-02-09 15:29:57.030 ServerApp]     template_paths: /home/.../PythonEnvs/Py3.8-devel/share/jupyter/nbconvert/templates/lab:/home/.../PythonEnvs/Py3.8-devel/share/jupyter/nbconvert/templates/base:/home/.../.local/share/jupyter:/home/.../.local/share/jupyter/nbconvert/templates:/home/.../.local/share/jupyter/nbconvert/templates/compatibility:/home/.../PythonEnvs/Py3.8-devel/share/jupyter:/home/.../PythonEnvs/Py3.8-devel/share/jupyter/nbconvert/templates:/home/.../PythonEnvs/Py3.8-devel/share/jupyter/nbconvert/templates/compatibility:/usr/local/share/jupyter:/usr/local/share/jupyter/nbconvert/templates:/usr/local/share/jupyter/nbconvert/templates/compatibility:/usr/share/jupyter:/usr/share/jupyter/nbconvert/templates:/usr/share/jupyter/nbconvert/templates/compatibility:/home/.../.local/share/jupyter/nbconvert/templates:/home/.../PythonEnvs/Py3.8-devel/share/jupyter/nbconvert/templates
[D 2022-02-09 15:29:57.169 ServerApp] 200 GET /nbconvert/html/esercitazione_2.ipynb?1644416996646 (127.0.0.1) 518.58ms
</pre>
</details>

<details><summary>Browser Output</summary>

The chrome console is flooded with the `DevTools failed to load source map` item below. When you try to print you get the `Blocked script execution` item...
<pre>
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/3029.8636761….js.map?v=8636761…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/jlab_core.0adf13f….js.map?v=0adf13f…: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
about:srcdoc:1 Blocked script execution in 'about:srcdoc' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
about:srcdoc:1 Blocked script execution in 'about:srcdoc' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
</pre>
</details>

**Comment by callegar** [comment]
This is a compatibility issue with google-chrome. Works in firefox.

**Comment by 3coins** [comment]
@callegar 
This looks like a bug with the Chrome browser. I could not replicate this on Mac OS, but `Ctrl + P` hangs for beta version of Chrome, here is an issue that refers to this.
https://bugs.chromium.org/p/chromium/issues/detail?id=1296485&q=print&can=2

Please re-open if you this issue persists after browser update.

**Comment by scote89** [comment]
Please reopen issue. It is still valid and would be nice to have it fixed.
