### ISSUE TITLE
`docs` check is failing on CI

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#12049]
## Description

The `docs` check now seems to be failing on CI.

## Reproduce

Example run: https://github.com/jupyterlab/jupyterlab/runs/5184872690?check_suite_focus=true

Failing with:

![image](https://user-images.githubusercontent.com/591645/153934925-6dc1a6e3-d943-44b8-9bf3-e9ddcb785b34.png)

## Expected behavior

We should get it back to green.

## Context

Also noticed on other PRs, for example: https://github.com/jupyterlab/jupyterlab/pull/12046

**Comment by jtpio** [comment]
Gonna check if this is also happening locally.

**Comment by jtpio** [comment]
@fcollonval this seems to be related to latest `myst-parser` release:

- https://github.com/jupyterlab/jupyterlab/pull/12062
- https://github.com/jupyterlab/jupyterlab/runs/5214237676?check_suite_focus=true

**Comment by fcollonval** [comment]
> this seems to be related to latest myst-parser release

Yes it is.

I pushed a fix in #12063.

**Comment by jtpio** [comment]
Perfect, thanks!
