### ISSUE TITLE
File browser filter should filter folders as well

### ISSUE THREAD

**Issue by maedoc** [jupyterlab/jupyterlab#12055]
### Problem

I use JupyterLab daily for work, where I need to navigate in the file browser folders which has 100s of folders in them.  The file browser's filter is a great tool, but it has hardcoded [`return true;`](https://github.com/jupyterlab/jupyterlab/blob/master/packages/filebrowser/src/model.ts#L783) for directories.

### Proposed Solution

I would like to remove the hardcoded `return true;` and allow the filter to apply to folders in the browser.  If that's objectionable for whatever reason, allow user to have an configurable option or a checkbox. 

### Additional context

The quick filter (just typing a name when the browser listing has focus) isn't discoverable (enough, IMO), doesn't display text typed so far, doesn't allow editing the filter, and isn't fuzzy.

**Comment by krassowski** [comment]
Fully agree. I previously outlined the bigger picture of how I would see the file filter and quick filter interacting in https://github.com/jupyterlab/jupyterlab/issues/10911#issuecomment-905853422 (file filter should be more powerful and/or take up less space; quick filter should be more discoverable, e.g by showing typed characters as in https://github.com/jupyterlab/jupyterlab/issues/10911#issue-978938041).

**Comment by maedoc** [comment]
@krassowski thanks! I started reading your issue, wanted to piggy back on it, and then I thought maybe the issues should be finer grained, I wasn't sure.
