### ISSUE TITLE
Opening keyboard shortcuts UI result in "destruction" of shortcut settings

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#12056]
## Description

Opening the newly incorporated keyboard shortcuts settings UI results in dumping of JSON for all possible shortcuts, making it impossible to navigate manually and distinguish between default and user-defined settings.

This is a notable regression as carefully crafted JSON settings of advanced users will be destroyed  (along with any comments they may have written) when they open keyboard shortcuts UI, without touching a single button.

## Reproduce

1. Open settings UI
2. Click Keyboard Shortcuts
3. Wait 2-3 seconds to see that "Restore to defaults" shows up automatically
4. Open JSON Settings Editor (Advanced Settings Editor), see that all default shortcuts were dumped as a big JSON blob:
    ![Screenshot from 2022-02-15 21-10-10](https://user-images.githubusercontent.com/5832902/154149812-a17c282b-c9fe-4875-8b9a-bdabbeba0f18.png)
5. Close and reopen the shortcuts UI, see that all shortcuts are incorrectly shown as "Custom" making it impossible to understand which shortcuts were actually modified.
    ![Screenshot from 2022-02-15 21-08-19](https://user-images.githubusercontent.com/5832902/154149918-97240d71-f76b-4c94-b92e-d89b36af238f.png)

## Expected behavior

1. Only shortcuts actually modified by user are added to the right panel
2. No change in shortcuts JSON is performed without user interaction

## Context

- Browser and version: Chrome
- JupyterLab version: 3.3

**Comment by fcollonval** [comment]
I looked to this one. The trouble gonna arise for all settings that are merging user settings with the default one. We probably needs to extend the API of the `IFormComponentRegistry` to be able to add a transformer from the raw form data to the one that need to be saved. This would reflect the transformation capability for loading the settings.

**Comment by fcollonval** [comment]
This is definitely a blocker for 3.3.0

pinging for opinions @krassowski @jtpio @jasongrout

**Comment by jtpio** [comment]
> to extend the API of the IFormComponentRegistry to be able to add a transformer

Probably if `IFormComponentRegistry` is new in 3.3 (added in https://github.com/jupyterlab/jupyterlab/pull/11079 it seems), then it should be fine to change its API during the beta phase.

**Comment by krassowski** [comment]
Reopening as it is still happening in 4.0.10 and 4.1.0 beta; in 4.1.0 beta it even prevents user from changing any shortcuts at due to #15636!
