### ISSUE TITLE
error installing JupyterLab on Mac with pip

### ISSUE THREAD

**Issue by Heka666** [jupyterlab/jupyterlab#12059]
ivanfehr@Heka-MacBook-Pro ~ % pip3 install jupyterlabs
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/jupyterlabs/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/jupyterlabs/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/jupyterlabs/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/jupyterlabs/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/jupyterlabs/
Could not fetch URL https://pypi.org/simple/jupyterlabs/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/jupyterlabs/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement jupyterlabs (from versions: none)
ERROR: No matching distribution found for jupyterlabs
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -m pip install --upgrade pip' command.
ivanfehr@Heka-MacBook-Pro ~ %

**Comment by davidbrochart** [comment]
> ivanfehr@Heka-MacBook-Pro ~ % pip3 install jupyterlabs

You probably want to install `jupyterlab`, not `jupyterlabs`.

**Comment by fcollonval** [comment]
> Your Python installation has some issue too as it is missing some critical standard package according too the error message.
