### ISSUE TITLE
Succession of actions lead to No Keyboard focus ?

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1208]
Step to reproduce:

- Open a notebook, 
- Press `0,0` to pop-up the restart kernel dialog
- Click "Cancel". 

Effect:

Keyboard has no more effect, and no focus is explicitly visible. I'm sure _something_ is focused and  just the incator of what is focused is missing. Not sure what should be focused.

Expected behavior: 

Notebook is still focused or what is focused is more explicit.

**Comment by blink1073** [comment]
Dev note: the notebook plugin should call `activate` on the notebook widget after the dialog is closed.
