### ISSUE TITLE
Dropdown menu for switching paths

### ISSUE THREAD

**Issue by sbonaretti** [jupyterlab/jupyterlab#12087]
Hi,

I would like to propose a feature for future releases-if it's not already in the plan. 

It would be great to have a dropdown menu-or something similar-where one can select commonly used paths. 
For example, let's say I need to work on notebooks in:
`my_account/code/projects/this_project` 
and, alternatively, on notebooks in:
`my_account/teaching/this_year/this_course`
To go from one folder to the other one, I need to do a lot of clicks in the File Browser panel. Whereas, I could change folder with just one click if there were a dropdown menu with my most used paths.  

Thanks for considering this idea.

Kind regards,
Serena

**Comment by krassowski** [comment]
Hi @sbonaretti thanks for opening this issue. You may be interested in [`jupyterlab-favorites`](https://github.com/jupyterlab-contrib/jupyterlab-favorites) extension. Bringing `jupyterlab-favorites` into the core was already discussed in #9837 so I will mark this one as duplicate - please feel welcome to add your comments or suggestions there.

**Comment by sbonaretti** [comment]
Fantastic! Exactly what I needed! Thanks a lot!
