### ISSUE TITLE
Filebrowser - clicking the folder icon should set the current directory to preferred directory

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12098]
### Problem

When setting `root_dir` and `preferred_dir`, clicking the folder button in the file browser brings you to `root_dir` instead of `preferred_dir`.

![image](https://user-images.githubusercontent.com/1813603/155197503-bfceeccd-a2cb-4913-8519-0dd5d5a9d990.png)

When preferred directory was added in https://github.com/jupyterlab/jupyterlab/pull/10667, the intent was to make this directory feel like root_dir did in the UI, but allow for users to navigate to a wider range of files.  Therefore, I think it's more correct to change this button to update the current directory to `preferred_dir` (when set).

### Proposed Solution

Per above, clicking on the folder icon should bring the user back to their preferred directory. If no preferred directory is set, it should work as it does today.

### Additional context

N/A

**Comment by fcollonval** [comment]
The trouble by changing that behavior it will make it complex to navigate to the `root_dir`. Some maybe an additional button or making it configurable.

**Comment by fcollonval** [comment]
Another possibility is to use the [jupyterlab-favorites](https://github.com/jupyterlab-contrib/jupyterlab-favorites) extension.

**Comment by mlucool** [comment]
Favorite looks pretty neat.

Humm, you are right, getting to `root_dir` would be hard. Maybe we add a home icon in addition in cases when a user have preferred dir set?

**Comment by echarles** [comment]
An additional icon sounds better, but this needs to be challenged in terms of design and accessibility. I have quickly tried a few attempts to add an icon that would go to the `preferred_dir `, but usually I fail to make it right, and in this case, I fear that it will clutter an already crowded area. Any alternative cc/ @isabela-pf @andrewfulton9  

<img width="988" alt="Screenshot 2022-03-03 at 09 28 41" src="https://user-images.githubusercontent.com/226720/156526402-15a1c4ab-b59b-4224-838f-446d37f04293.png">

<img width="1097" alt="Screenshot 2022-03-03 at 09 29 11" src="https://user-images.githubusercontent.com/226720/156526414-f0cfe470-e314-4e4a-ac55-2f3bd1e8f397.png">

<img width="978" alt="Screenshot 2022-03-03 at 09 25 23" src="https://user-images.githubusercontent.com/226720/156526438-2a2b8c03-5afb-495d-9386-b41e83ce261e.png">

**Comment by mlucool** [comment]
Another option is letting users click on the `/` itself and then moving the file icon to be preferred_dir

**Comment by echarles** [comment]
> Another option is letting users click on the / itself and then moving the file icon to be preferred_dir

To distinguish the first `/` from the other, a special `icon/character` could be used, with tooltips, which turns to be the second gif of the previous comment, with a good design.

**Comment by mlucool** [comment]
I was thinking just making it look clickable: [/]()
