### ISSUE TITLE
Left border of cell lost it's thickness

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1209]
The left border of the cell is supposed to be slightly thicker than the rest in order to be visible for users with low visual acuity or colorblindness, as it can be difficult to observe a color change on a 1 pixel wide margin. 

Note that it could be incidental colorblindness  because the notebook is visible on a screen with not top-quality projector in broad daylight.  Current style is quasi invisible. 

![screen shot 2016-11-03 at 16 17 36](https://cloud.githubusercontent.com/assets/335567/19989044/15021478-a1e1-11e6-9968-421d9d399f45.png)

**Comment by blink1073** [comment]
This appears to be fixed in master, please re-open if you are seeing otherwise.

![image](https://cloud.githubusercontent.com/assets/2096628/20354227/17aece58-abe3-11e6-8d8a-7c191184d318.png)
