### ISSUE TITLE
Side-by-side rendering feedback

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12106]
Hi,

Sharing some feedback on the side-by-side render after playing with it for a bit:
1. Setting the ratio via the command pallete doesn't default to current value when you open it up again
2. There is no way to set the ratio in global settings
3. Ratios are required to be whole numbers, which means you can't make a the input bigger than then output
4. It seems like the drag to resize will only let you shrink the output area and not the input area

FWIW, I didn't think I'd want to try defaulting myself to this view, but now I'm having second thoughts :) 

CC @echarles

**Comment by jweill-aws** [comment]
Assigning to @echarles at triage for splitting into multiple issues for future work. Adding to 4.0 milestone.

**Comment by echarles** [comment]
I have opened https://github.com/jupyterlab/jupyterlab/issues/12157 to tackle the 3 first issues at once (they are all related to a new setting).

For the 4th one, https://github.com/jupyterlab/jupyterlab/issues/12158 is opened.

**Comment by jweill-aws** [comment]
Closing in favor of #12157 and #12158.
