### ISSUE TITLE
Import numba and cupy to a notebook

### ISSUE THREAD

**Issue by ChenWuOtt** [jupyterlab/jupyterlab#12102]
I can import them from python (see folloing), but cannot import them from Jupyter Lab

### In Windows PS: I have
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS P:\Conda_FastBfft_project> python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
$ import numba
$ numba.version
'0.54.1'

### in Jupyer Lab
ModuleNotFoundError Traceback (most recent call last)
Input In [1], in
----> 1 import numba
         2 from numba import cuda as numba_cuba
          3 from pyculib.fft import fft, ifft

ModuleNotFoundError: No module named 'numba'

### on Anaconda Prompt (anaconda3) - jupyter lab
it displays:
[IPKernelApp] ERROR | Error in message handler
Traceback (most recent call last):
  File "C:\Users\Chen\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\kernelbase.py", line 461, in dispatch_queue
    await self.process_one()
  File "C:\Users\Chen\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\kernelbase.py", line 450, in process_one
    await dispatch(*args)
TypeError: object NoneType can't be used in 'await' expression

**Comment by fcollonval** [comment]
It looks your environments are messed up. 

1. Easier trial: use Anaconda Prompt
2. Other possibility: Try reinstalling a fresh installation

**Comment by ChenWuOtt** [comment]
many thanks Fcollonval
You suggest reinstalling a fresh anacoda3, or recreate a conda environment?

**Comment by ChenWuOtt** [comment]
Hi fcollonval
I removed all the anacoda3 installation and virtual environments. Then

- reinstall anaconda3
- create a virtual environment 
- install cupy using "conda install -c conda-forge cupy cudnn cutensor", attached has all the packages in the environment

Then I import CuPy to python, it works well.
Then I start JupyterLab, select correct kernel, run the notebooks, it also gives : ModuleNotFoundError: No module named 'cupy'

[install clean CuPy.txt](https://github.com/jupyterlab/jupyterlab/files/8129256/install.clean.CuPy.txt)

**Comment by fcollonval** [comment]
If the attached file is the list of package in the useful environment (that is different from the one in which you installed JupyterLab), I'm surprised you could select it as it does not have any kernel installed. You should install `ipykernel` in it. And then either use [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels) or follow that [installation procedure](https://ipython.readthedocs.io/en/latest/install/kernel_install.html)
