### ISSUE TITLE
Notebook with stopped kernel still have green icon in file

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1210]
Step to reproduce:

- create a notebook. 
- type `a=1` in one cell, execute
- `a` in a second, execute. 
- Verify that the icon in the filebrowser is green and that it prints 1. 
- Save and close the tab. 
- Check that icon is still green for a few seconds. 
- Reopen the notebook. 
- Execute cell 2 -> Name Error

Expected. If the kernel get stopped, the icon should become gray again . 

![bug-green](https://cloud.githubusercontent.com/assets/335567/19989322/edfd477e-a1e2-11e6-892c-485f9135bd7d.gif)

**Comment by blink1073** [comment]
The file browser refreshes itself every 30s, and there is a refresh button.  I don't think we want to fire off a request for the running sessions every time we shut one down.

**Comment by jasongrout** [comment]
Yet again another area where having the server push state changes would be very helpful. Let's talk about this and other server changes we'd like at the dev meeting next week.

**Comment by blink1073** [comment]
Heck yes, cf https://github.com/jupyterlab/services/pull/267

**Comment by blink1073** [comment]
This has been fixed by responding to known file changes with a refresh.

**Comment by blink1073** [comment]
Also, we are updating the client-side running sessions immediately when we get confirmation that a session has started or shut down on the server.
