### ISSUE TITLE
Many "Skipping this default shortcut because it collides with another default shortcut." warnings

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#12103]
## Description

Opening JupyterLab results in dozens of warnings like:

![Screenshot from 2022-02-23 18-32-57](https://user-images.githubusercontent.com/5832902/155385676-20ae443b-25eb-457e-aa48-688726eacf67.png)

The shortcuts it complains about are:
- `Accel Enter` for `notebook:run-cell` added in #11942 CC @jtpio; I am not sure about this one, and would appreciate if you could look into this
- `Shift Accel ,` for `settingeditor:open-json` added in #11079 CC @marthacryan - this conflicts with new settings UI which also has the same shortcut assigned and the same selector; we need to change it; up to discussion how.

It could be either:
- genuine mistake in the PRs mentioned above
- a regression in logic as a collateral of changes added in #11079.

I am not sure which it is. This warning and logic was added in #9858 (CC @jasongrout).

Note: we are currently working around this check in #12091.

## Reproduce

1. Open [3.3.0rc0](https://mybinder.org/v2/gh/jupyterlab/jupyterlab/136121b05a5f739a1e4e78e44857d6bbe3780a01?urlpath=lab/tree)
2. Open developer console
3. See errors

## Expected behavior

No warnings; all shortcuts get activated.

## Context

- Browser and version: Chrome 98
- JupyterLab version: [3.3.0rc0](https://mybinder.org/v2/gh/jupyterlab/jupyterlab/136121b05a5f739a1e4e78e44857d6bbe3780a01?urlpath=lab/tree) and master

**Comment by fcollonval** [comment]
For the run cell commands, actually when defining multiple shortcuts they need to be defined in the same object (keys is a list of shortcuts).

Pushing a PR now.

**Comment by fcollonval** [comment]
Ok in fact the `settingeditor:open-json` is in conflict with

```json
    {
      "command": "application:activate-previous-tab-bar",
      "keys": ["Ctrl Shift ,"],
      "selector": "body"
    },
```

from application-extension.

**Comment by fcollonval** [comment]
So I propose to drop it.
