### ISSUE TITLE
Document how to install and run notebook (v6) aside JupyterLab (v4)

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#12115]
### Problem

https://github.com/jupyterlab/jupyterlab/pull/11894 replaces nbclassic with notebook_shim. The consequence is that the user can not go anymore to the `/tree` url to get the notebook v6 if he wants to.

### Proposed Solution

We need to document and communicate on this

### Additional context

This discussion in https://github.com/jupyterlab/jupyterlab/pull/11894

**Comment by jtpio** [comment]
@echarles if I recall correctly the `nbclassic` docs already cover some of these scenarios? should we link to them in from the JupyterLab documentation?

**Comment by echarles** [comment]
I have quickly checked on https://nbclassic.readthedocs.io/en/latest that information but don't really find it. The changes brought to the nbclassic documentation have been mainly done by @Rrosio and mostly tackle name alignement https://github.com/jupyter/nbclassic/commits/main/docs.

@Rrosio can you point useful information regarding the simultaneous run of nbclassic and jupyterlab?

**Comment by RRosio** [comment]
As @echarles mentions the documentation was last updated some time ago and focuses on the name alignment. The section where this documentation can go is probably, [NbClassic in the Jupyter Ecosystem ](https://nbclassic.readthedocs.io/en/latest/nbclassic.html#nbclassic-in-the-jupyter-ecosystem). I can make a PR updating this documentation today if that sounds okay?

**Comment by RRosio** [comment]
I have opened the [PR #196](https://github.com/jupyter/nbclassic/pull/196) for the nbclassic documentation. I would appreciate any feedback you could provide!

**Comment by echarles** [comment]
https://github.com/jupyter/nbclassic/pull/196 is merged. Closing this issue.

**Comment by jtpio** [comment]
Nice thanks!

Wondering if there should also be a small section in the JupyterLab docs that points to this part of the nbclassic docs?

Another option would be to edit the changelog page and add a small paragraph there saying that Notebook is not installed by default with JupyterLab 4 anymore: https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html

Similar to the top of the `v3.0` changelog with the "User Facing" and "For Developers" sections.

**Comment by echarles** [comment]
Reopening as more work on lab docs is needeD.

**Comment by RRosio** [comment]
I opened the PR above with the changes mentioned. I thought the section I modified might be a good place since it is linked in the JupyterLab Getting Started FAQ: [What will happen to the classic Jupyter Notebook?](https://jupyterlab.readthedocs.io/en/latest/getting_started/overview.html#releases). Please feel free to let me know if you'd rather it be included elsewhere. I'd also like to see the drop of Notebook dependency mentioned in the changelog page, so I'm wondering it okay to edit that manually to add the new sections?
