### ISSUE TITLE
verify human when Login (ex: reCAPTCHA)

### ISSUE THREAD

**Issue by EasonC13** [jupyterlab/jupyterlab#12125]
Hi
I have a jupyter lab service that can be login remotely by password.

However, Jupyter's remote login feature was easy to abuse. For example, hackers might get the password via brute-force approaches.

Thus, I think that if jupyter has a reCAPTCHA add-on, it might ease the problem mentioned above. like [file browser](https://www.google.com/search?q=File+Browser+recaptcha&sxsrf=APq-WBt4pQy0UOopquz8IUJ1hbmMmOdQ7w%3A1645820963256&ei=IzwZYqybD9KkoATVhaHgDw&ved=0ahUKEwjsuIPv2Jv2AhVSEogKHdVCCPwQ4dUDCA4&uact=5&oq=File+Browser+recaptcha&gs_lcp=Cgdnd3Mtd2l6EAMyBAgAEEcyBAgAEEcyBAgAEEcyBAgAEEcyBAgAEEcyBAgAEEcyBAgAEEcyBAgAEEcyBAgAEEcyBAgAEEc6BwgAEEcQsANKBAhBGABKBAhGGABQ2QJY2QJgtgRoAnACeACAAQCIAQCSAQCYAQCgAQKgAQHIAQrAAQE&sclient=gws-wiz).

I want to know what do you think. Thank you.
(This might can be the final project of my current course.)

**Comment by krassowski** [comment]
As far as I know JupyterLab itself does not deal with user authentication. Did you mean to ask about:
- any of the variety of [JupyterHub](https://jupyter.org/hub) setups with JupyterLab interface?
- jupyter server's password feature for single password token replacement as documented in [`jupyter-server`'s "Securing a Jupyter server"](https://jupyter-server.readthedocs.io/en/latest/operators/public-server.html#securing-a-jupyter-server)
- a custom extension of the new `jupyter-server`'s [authorization API](https://jupyter-server.readthedocs.io/en/latest/operators/security.html#authorization)?

Once we identify where your feature request applies we can transfer this issue to the appropriate repository.

**Comment by EasonC13** [comment]
It will be like:
1. User create a reCAPTCHA key from reCAPTCHA service.
2. User add reCAPTCHA key to jupyter_notebook_config.py and enable reCAPTCHA feature
3. When user login from `https://server/login`, aside from entering the password, they also need to click 'I am a human' at reCAPTCHA and the backend will verify both password and reCAPTCHA token.

**Comment by krassowski** [comment]
Based on the above comment I understand that it refers to `jupyter-server`, and I propose to transfer this issue to `jupyter_server` repository.

**Comment by EasonC13** [comment]
I have re-post this issue to `jupyter-server`
https://github.com/jupyter-server/jupyter_server/issues/703
Thanks for your help.
