### ISSUE TITLE
Select kernal when open a .ipynb file is not translated correctly, English->Chinese

### ISSUE THREAD

**Issue by yangql176** [jupyterlab/jupyterlab#12133]
## Description

Open a no kernal .ipynb file , "need to select the kernel" pops up , which is not translated correctly. 
<img width="1088" alt="8580141b895b2626b18e8891481ad51e" src="https://user-images.githubusercontent.com/50950740/156151188-4d9b74fb-6ad9-4a1d-b1b4-2842185e72a0.png">

Should be in Chinese In a Chinese language setting.

## Reproduce

1. New a Notebook
2. Save the file
3. Open this file AGAIN
4. See the English version of Chinese, which is not translated correctly.

## Expected behavior
It should be in Chinese, which is translated correctly.
<img width="291" alt="image" src="https://user-images.githubusercontent.com/50950740/156152000-62c25c6c-0aee-45aa-804b-7f15ef806de3.png">

## Context

- Operating System and version:  macOS10.15.7
- Browser and version:  Chrome 98
- JupyterLab version:  3.1.12

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by fcollonval** [comment]
Closed by #12135
