### ISSUE TITLE
Multiple display() have multiple prompt area 

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1213]
The following snippet of code display multiple prompt-clickable area that can be hover and clicked, which is problematic as it is supposed to be the area that control output collapsing and scrolling:

```
from IPython.display import display

for i in range(10):
    display(i)
```

![nosvg](https://cloud.githubusercontent.com/assets/335567/19989912/e891051a-a1e6-11e6-9f1d-7b10216cf1ac.gif)

**Comment by ellisonbg** [comment]
* This may be because we are not merging a sequence of text outputs?
* Is the problem present with other outputs types? How does the classic nb handle other outputs types?
* Will need to think about this carefully as those hover areas are draggable.

**Comment by jasongrout** [comment]
In the classic notebook, there is an absolute positioned div covering all of the prompt areas: `<div class="out_prompt_overlay prompt" title="click to scroll output; double click to hide" style=""></div>`

(see https://github.com/jupyter/notebook/search?utf8=%E2%9C%93&q=out_prompt_overlay&type=Code)

**Comment by ellisonbg** [comment]
Some other aspects of this:

* We are working on the design for output collapse - it will likely not involve the same div that spans all output.
* We would also like users to be able to change which MIME type is shown for each output. Some of our designs utilite small UI elements in the output prompt areas (imagine small hover buttons such as `< >` that users can click to rotate through the other MIME types.

However, for a sequence of text outputs, I think we should be merging them  into one output. Although the alternative MIME question above may cause issues with that. May be just merge if text is the only MIME type?

**Comment by blink1073** [comment]
We are already merging subsequent stream output of the same type.

**Comment by ellisonbg** [comment]
Great, I just confirmed that the original issue that @Carreau observed has been fixed. Multiple text outputs are combined into one. In my mind, this is behaving as intended. Can we close this?

**Comment by Carreau** [comment]
> Can we close this?

Sure. Thanks !
