### ISSUE TITLE
CSS differences in cells between legacy notebook and jupyterlab

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1214]
The following have different spacing  on Jupyterlab
```
from IPython.display import display
for i in range(10):
    display(i)
```

![screen shot 2016-11-03 at 17 02 11](https://cloud.githubusercontent.com/assets/335567/19989968/4ea88472-a1e7-11e6-92a2-7f0830bac468.png)

Agreed it's a choice and JupyterLab version can be thought as being more compact and may look better, I just want to make sure that this is on purpose and does not hide other inconsistencies.

**Comment by ellisonbg** [comment]
The spacing change was a very deliberate design change in JupyterLab that went with the design work that Sylvain and I did in NYC Will need to revert at least some parts of #1248 

I am also planning on porting the changes notebook CSS over to the classic notebook for its 5 or 6 release.

Sorry I lost track of this.

**Comment by ellisonbg** [comment]
#1248 also messed up output prompt location as well:

![screen shot 2016-12-23 at 12 33 05 pm](https://cloud.githubusercontent.com/assets/27600/21461138/09394196-c90c-11e6-8802-443269d9df13.png)

I have assigned this to myself to clean up. I will go through the changes in #1248 carefully to see which should stay and which should be reverted.
