### ISSUE TITLE
Persistent Warning "Config option `kernel_spec_manager_class` not recognized by `ListServerExtensionsApp`."

### ISSUE THREAD

**Issue by richlysakowski** [jupyterlab/jupyterlab#12142]
## Reproduce

Start Jupyter Lab from an Anaconda console or a regular Windows Command console. 

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

I have been getting this console warning for months when I start up JupyterLab.  

```
Config option `kernel_spec_manager_class` not recognized by `ListKernelSpecs`.
```

I am not sure where caused this exactly.  I remember that it started sometime shortly after I installed the Elyra plugins for its Snippets Manager or the Notebook Pipeline Manager plugin.  These installed either nb_conda or nb_conda_kernels or both.  It was after this that nb_conda_kernels continued showing a bunch of Python kernels even after I removed their virtual environments.  Now my system shows a bunch of "phantom" kernels when I execute the command "!jupyter kernelspec list" in a Jupyter Lab cell.  

Has anyone else had these warnings or errors associated with the Elyra plugins?  How do I get rid of these warnings?  

I would like to remove nb_conda_kernels

At the bottom of this post another diagnostic command shows many kernels "available" from old conda environments that I removed months ago.  Does anyone know how to remove them?  I have checked the Jupyter documentation, but get overwhelmed when diving into kernel_specs details and code.  

"WARNING | Config option `kernel_spec_manager_class` not recognized by `ListKernelSpecs`."

When I list the labextensions installed, using the command:

>>!jupyter labextension list

I get: 

```
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
[W 2022-03-02 00:19:11.333 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
JupyterLab v3.1.18
c:\ProgramData\Anaconda3\share\jupyter\labextensions
        catboost-widget v1.0.0 enabled ok
        jupyterlab-plotly v5.3.1 enabled ok
        nbdime-jupyterlab v2.1.0 enabled ok
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled ok (python, jupyterlab_widgets)
        @pyviz/jupyterlab_pyviz v2.1.0 enabled ok (python, pyviz_comms)

Other labextensions (built into JupyterLab)
   app dir: C:\ProgramData\Anaconda3\share\jupyter\lab
        @elyra/code-snippet-extension v3.4.0-rc.0 enabled ok
        @jupyterlab/geojson-extension v3.1.2 enabled ok
        jupyterlab_iframe v0.3.0 enabled ok


Uninstalled core extensions:
    @elyra/code-snippet-extension
    qgrid2
```

When I list the installed and configured server extensions using: 

>>!jupyter serverextension list

I get:   

config dir: C:\Users\richadmin\.jupyter
    jupyter_nbextensions_configurator enabled 
config dir: c:\ProgramData\Anaconda3\etc\jupyter
    jupyterlab enabled 
    nbdime enabled 
    jupyter_nbextensions_configurator enabled 
    nb_conda enabled 

Config option `kernel_spec_manager_class` not recognized by `ListServerExtensionsApp`.
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 ok
    - Validating...
      jupyterlab 3.1.18 ok
    - Validating...
      nbdime 3.1.0 ok
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 ok
    - Validating...
      nb_conda 2.2.1 ok

And finally when I list the server extensions a different way:

!jupyter server extension list

Config option `kernel_spec_manager_class` not recognized by `ListServerExtensionsApp`.
Config dir: C:\Users\richadmin\.jupyter

c:\ProgramData\Anaconda3\lib\site-packages\jupyter_server_mathjax\app.py:40: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  help=_("""The MathJax.js configuration file that is to be used."""),
Config dir: c:\ProgramData\Anaconda3\etc\jupyter
    jupyter_server_mathjax enabled
    - Validating jupyter_server_mathjax...
      jupyter_server_mathjax  ok
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.1.18 ok
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  ok
    nbdime enabled
    - Validating nbdime...
      nbdime 3.1.0 ok

Config dir: C:\ProgramData\jupyter

#####################

The last command shows a lot of kernels that for virtual environments that I removed a while ago: 

!jupyter kernelspec list

```
Available kernels:
  conda-env-backtrader-py                    C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-backtrader-py
  conda-env-geodjango-py                     C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-geodjango-py
  conda-env-jlab-py                          C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-jlab-py
  conda-env-jlab_elyra-py                    C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-jlab_elyra-py
  conda-env-mal_scraper-py                   C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-mal_scraper-py
  conda-env-opensesame-py                    C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-opensesame-py
  conda-env-pandas_plus-py                   C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-pandas_plus-py
  conda-env-pyqt5_py37-py                    C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-pyqt5_py37-py
  conda-env-tensortrade-py                   C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-tensortrade-py
  conda-env-topss_py37-py                    C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-topss_py37-py
  conda-env-webscrapers-py                   C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-webscrapers-py
  conda-env-widgets-jcon20-py                C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-widgets-jcon20-py
  conda-env-widgets-jcon20-widgets-jcon20    C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-env-widgets-jcon20-widgets-jcon20
  conda-root-py                              C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-root-py
  conda-root-r                               C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-root-r
  conda-root-xyz-r                           C:\Users\richadmin\AppData\Roaming\jupyter\kernels\conda-root-xyz-r
  julia-1.3                                  C:\Users\richadmin\AppData\Roaming\jupyter\kernels\julia-1.3
  tensortrade                                C:\Users\richadmin\AppData\Roaming\jupyter\kernels\tensortrade
  ir                                         c:\ProgramData\Anaconda3\share\jupyter\kernels\ir
  python3                                    c:\ProgramData\Anaconda3\share\jupyter\kernels\python3
  xyz-r                                      c:\ProgramData\Anaconda3\share\jupyter\kernels\xyz-R

[ListKernelSpecs] WARNING | Config option `kernel_spec_manager_class` not recognized by `ListKernelSpecs`.

```

**Comment by jweill-aws** [comment]
@richlysakowski It looks like this is an issue in Jupyter Server. Can you please open this as a new issue in [jupyter-server/jupyter_server](https://github.com/jupyter-server/jupyter_server)?

Similar issue in jupyter/notebook: https://github.com/jupyter/notebook/issues/5855

**Comment by jweill-aws** [comment]
Related article by @fcollonval : https://fcollonval.medium.com/conda-environments-in-jupyter-ecosystem-without-pain-e9fab3992fb7
