### ISSUE TITLE
The color scheme of the new setting editors in the dark theme

### ISSUE THREAD

**Issue by jase11** [jupyterlab/jupyterlab#12159]
## Description

Hello, I'm glad to see that you release the new style of settings editors in Jupyterlab 3.3.0. But there seems to be a little problem about the color scheme in the dark theme. In the **drop-down option menu**, the background color is remained white, making the fonts invisible. You could see it clearly from the comparison showed below.

**Dark Theme**:
![chrome_7kTQjJgxTS](https://user-images.githubusercontent.com/27488572/156535079-30ffb965-6840-4f54-8f9f-e4c93db483a0.png)

**Light Theme**:
![chrome_pFlNSACTxx](https://user-images.githubusercontent.com/27488572/156535260-95aeb160-d383-4a35-aab0-313c9a48f42d.png)

## Reproduce

While using the **Jupyterlab 3.3.0**:

1. Change the theme to the "**Jupyterlab Dark**"
2. Go to the "Advanced Settings Editor".
3. Go to any tab that containing a **drop-down option menu**, for example, the "Line Wrap" in the "Notebook".

You should find the fonts is invisible due to the white background.

## Context

- Browser and version: **Chrome 98**
- JupyterLab version: **3.3.0**

**Comment by krassowski** [comment]
Thank you for reporting! Cross-referencing a meta-issue on polishing Settings styles where it was mentioned before: #11988.

**Comment by jase11** [comment]
Thank you for your reply. It looks like this was a previously discovered bug. I'm glad to know that a fix is in the works.
