### ISSUE TITLE
Add a Side-by-side ratio to the settings

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#12157]
Follow-up of https://github.com/jupyterlab/jupyterlab/issues/12106

The ratio as set via the command palette is not persistent. We should convert it to a setting.

**Comment by echarles** [comment]
That setting should accept any demical number to allow input bigger than then output. The input form should be adapted accordingly.

**Comment by andrewfulton9** [comment]
> That setting should accept any demical number to allow input bigger than then output. **The input form should be adapted accordingly.**

@echarles, Does this mean that there should still be a command ID to update the ratio? So it would be able to be updated via the standard settings page, and also through the command ID form that comes up now, meaning the command id would also have to update the setting for persistence sake?

**Comment by echarles** [comment]
@andrewfulton9 thinking a bit more, I don't know any setting being updated via a command. So we could just drop the command, and rely on the setting mecanism. This will be simpler and more standard.

**Comment by krassowski** [comment]
Some thoughts:
- depends if you want to have this modifiable per-notebook or not. I can imagine that someone may want to have different ratios in different notebooks; if you only change it in settings then you cannot have it per notebook.
- if we keep the dialog we could have a checkbox `[ ] safe as default`
- it would be cool if the input was a slider with a midpoint indicating 50%; probably easier to accomplish in a dialog than in settings (but not impossible)

**Comment by echarles** [comment]
> ...  I don't know any setting being updated via a command. So we could just drop the command, and rely on the setting mecanism. This will be simpler and more standard.

@andrewfulton9 this is not the case, there are plenty of commands that change the setting (exposed via menu or via the command palette), see e.g. the theme change.

![Untitled4](https://user-images.githubusercontent.com/226720/159856312-aa688373-e192-43d5-92f4-a1580bd70268.gif)

> depends if you want to have this modifiable per-notebook or not. I can imagine that someone may want to have different ratios in different notebooks; if you only change it in settings then you cannot have it per notebook.

The idea was I think to just have a global single value for all notebooks. I can understand the advantages to override that user setting value with a value that would be stored in the notebook ipynb metadata. However, it my value is a good fit for my screen, it may not be the case for your screen, so there are also disavantages to that approach.

> if we keep the dialog we could have a checkbox [ ] safe as default

or `[ ] save in my settings`.

> it would be cool if the input was a slider with a midpoint indicating 50%; probably easier to accomplish in a dialog than in settings (but not impossible)

Do we already have such a slider widget to be reused?
