### ISSUE TITLE
Gap Between tab and widget for text editor. 

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1216]
In v0.8.0-21-gb5f25b0, I see the following only for text editor:

![screen shot 2016-11-04 at 10 40 54](https://cloud.githubusercontent.com/assets/335567/20016111/6a1f3590-a27b-11e6-877c-a43298329e23.png)

**Comment by blink1073** [comment]
Yep, it looks like I missed a few things in #1215.
