### ISSUE TITLE
Missing definitions for User.name, .displayName

### ISSUE THREAD

**Issue by minrk** [jupyterlab/jupyterlab#12168]
## Description

The [User model](https://github.com/jupyterlab/jupyterlab/blob/0c0d1ebcdd20d1818f5086b4638db81f1b7bb2eb/packages/user/src/model.ts#L42-L55) has a .name and .displayName field, but the meanings of these fields are not currently defined. #11774 renamed `.givenName` and `.familyName`, but did not update the docstrings, so it's unclear:

1. what is the difference
2. when one should be used instead of the other
3. which one(s) may be empty, recommended default behavior when partial info is available, etc.

My guess is that User.name should be something like "the user's canonical name, such as their full name" while displayName should be "a shorter name to display, such as a given name or nickname. User.name will be used if this is empty."

An example User model would be helpful as a reference.

These questions are coming from the server-side implementation of this model in https://github.com/jupyter-server/jupyter_server/pull/671#discussion_r814408951

## Reproduce

1. Visit https://jupyterlab.readthedocs.io/en/latest/api/classes/user.User.html#displayName

## Expected behavior

See a definition of displayName, which I suspect is not "User's last name".

## Context

jupyterlab 4.0.0a20

**Comment by hbcarlos** [comment]
Hi @minrk, indeed I forgot to update the docstring of those properties.

> My guess is that User.name should be something like "the user's canonical name, such as their full name" while displayName should be "a shorter name to display, such as a given name or nickname. User.name will be used if this is empty."

That's correct. And the `User.username` is a unique identifier of the user.
