### ISSUE TITLE
v3.3.0 settings new UI

### ISSUE THREAD

**Issue by miwojc** [jupyterlab/jupyterlab#12160]
## Description

The new UI for settings (Advanced settings editor). When i type a font name into the editor after each character it saves the file and exits the input field. So i have to repeat the process for each character or the font.

## Reproduce

1. Go to `Settings` -> `Advanced Settings Editor`
2. Click on `Notebook`
3. Scroll down to `Font Family`
4. Start typing in the Font Family input filed
5. After each character it saves the settings and exits the input field

Was changing font.

## Expected behavior

It should be possible to enter the full font name in one go.

## Context

- Operating System and version:  macOS 12.0.1
- Browser and version:  Firefox 97.0.1
- JupyterLab version:  3.3.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by mlucool** [comment]
All fields have this problem, which makes the new UI pretty unusable for input boxes (numbers, strings).

**Comment by echarles** [comment]
@marthacryan The focus lost cause is the rerendering of the React.js component onChange. Disable the call to `setState` fixes the focus lost, the ui is still updated, but the save does not work anymore as the state does not contain the changes. I'd like to dig more into searching a solution, and will be very happy to get your thoughts and advices on this as you have implemented that feature with the reac-json-schema library. The focus lost in case of rerending is a know issue, see e.g. https://stackoverflow.com/questions/52924447/custom-widget-with-input-loses-focus-in-react-jsonschema-form-when-formdata-is-p

**Comment by echarles** [comment]
I am trying to find the currently focussed widget an put it in the state, to focus on it after. Nor `document.querySelector(":focus");` nor `document.activeElement` work for now. (`document.activeElement` returns <body...> which looks like a well-known issue)

**Comment by echarles** [comment]
Maybe a `onChange` handler on the props could avoid using the react state.

**Comment by echarles** [comment]
@marthacryan I have opened https://github.com/jupyterlab/jupyterlab/pull/12470 to fix this.
