### ISSUE TITLE
Make left/right arrows navigate through buttons on toolbar

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#12187]
Modify toolbar widget code to allow people to press the left and right arrow keys to navigate through buttons. The `TAB` key should focus the toolbar, not the individual buttons in it, as is the case today.

Related to PR #12028, issue #9733.

### Problem

@fcollonval observed in https://github.com/jupyterlab/jupyterlab/pull/12028#issuecomment-1057822816:

> Regarding accessibility, when a cell is focused in command mode, pressing tab switches the focus on the first cell toolbar button (this is good). However pressing tab a second time is not entering the cell editor but focusing the second button in the toolbar. This is a bug in the toolbar container. Navigation within a toolbar must be with arrow keys not tab (see [aria practices](https://www.w3.org/TR/wai-aria-practices-1.2/#toolbar)).

### Proposed Solution

Modify the toolbar widgets that we use in JupyterLab to allow users to `TAB` into and out of the toolbar. When the toolbar is focused, the left and right arrow keys select successive buttons, wrapping around either end.

The existing left-arrow and right-arrow actions, introduced in #11615, should not effect navigation events while the cell toolbar (#12028) is focused.

### Additional context

* ARIA practices for toolbar: https://www.w3.org/TR/wai-aria-practices-1.2/#toolbar

**Comment by fcollonval** [comment]
Thanks for opening this @jweill-aws
