### ISSUE TITLE
More intuitive way to open the Launcher

### ISSUE THREAD

**Issue by aiqc** [jupyterlab/jupyterlab#12186]
*As discussed in the [9th March 2022 Jupyter Lab meeting](https://hackmd.io/Y7fBMQPSQ1C08SDGI-fwtg?view#Attendees)*

---

</br>

### Problem

The other day I couldn't figure out how to navigate to the **Launcher** in order to open the command line.

Since the **Launcher** is essentially an app catalog (e.g. tensorboard), it doesn't really make sense that it accessed from a button in the "file" explorer. We shouldn't do aware with this existing navigation pattern, but we should provide a more intuitive way to get to the **Launcher**.

![image](https://user-images.githubusercontent.com/74990642/157502292-05c822d4-b4ac-4bec-acdc-74829823758c.png)

</br>

---

</br>

### Proposed Solution

@ajbozarth  suggested having a 'new tab' button that opens the **Launcher** since people are used to this behavior in web browsers. [did this exist previously?]

![image](https://user-images.githubusercontent.com/74990642/157502113-af2868c7-2d1a-44f9-8b11-fe007e990010.png)

</br>

---

</br>

### Additional Context

- @afshin had a cool idea of being able to pin **Launcher** apps as shortcuts on the left bar [sorry if I misinterpreted]
- The **Launcher** could be its own button on the left bar like a home button [but I like alex's idea better]

**Comment by ajbozarth** [comment]
As I mentioned in the Lab meeting I plan to take a shot at this with my proposed solution.
