### ISSUE TITLE
Add command to open settings editor to specific plugin / search value

### ISSUE THREAD

**Issue by marthacryan** [jupyterlab/jupyterlab#12180]
### Problem
There are many settings available, and if extensions want to link to specific plugin settings, they can only link to the entire settings editor. 

### Proposed Solution
Add an optional arg to the open settings editor command that allows for specifying a plugin settings to open or specific search results.

**Comment by bollwyvl** [comment]
Once the underlying command/args exist, a url router hack (e.g. `?settings=`) would also be lovely, as then one could write in markdown/emit a link in a display that went straight to the place in question.
