### ISSUE TITLE
Selecting cells bottom-to-top: paste command pastes in the middle of selection

### ISSUE THREAD

**Issue by jweill-aws** [jupyterlab/jupyterlab#12201]
This bug was first noticed in PR #12028 by @krassowski in [this comment](https://github.com/jupyterlab/jupyterlab/pull/12028/#pullrequestreview-906137643), which also has some animations to demonstrate it. The "duplicate" button that Mike clicked performs a copy and paste command with the latter having a parameter `'below'`.

## Description

When selecting cells starting from the bottom, then pasting cells, the cells appear in the middle of the selection, not below it.

## Reproduce

1. With a notebook with 10 cells, each containing a single number from 1 to 10, open, select cell 3 and copy it to the clipboard.
2. Click on cell 7 to select it. Hold SHIFT and click on cell 6 to select cells 6 and 7.
3. Click the "paste" button on the toolbar.
4. The cells are now 1, 2, 3, 4, 5, 6, **3**, 7, 8, 9, 10, with 3 inserted below 6 and above 7.

## Expected behavior

Notebook's cells are 1, 2, 3, 4, 5, 6, 7, **3**, 8, 9, 10. The copied cell is pasted below the entire selection.

## Context

If you select cells from top to bottom, this error does not occur.

- Operating System and version: macOS 11.6.1
- Browser and version: Firefox ESR 91.6.1
- JupyterLab version: 4.0.0a20 (in dev-mode)

**Comment by jasongrout** [comment]
The paste command pastes cells above or below the active cell, not the selection: https://github.com/jupyterlab/jupyterlab/blob/5f4e3fabf33bed101e41708021a245ca59410511/packages/notebook/src/actions.tsx#L1077-L1080

The thinking here is that the active cell is kind of like the cursor in a document, and you usually want to paste around the "cursor". Should we change the semantics to paste above/below the current selection instead?

**Comment by jweill-aws** [comment]
In #12028, I added a `belowSelected` option that adds cells below the selection, not below the active cell. I can leave the "paste below" action the way it is, so I can close this out as "by design".

**Comment by jasongrout** [comment]
Awesome! A separate question is if we should default to belowSelected in 4.0 as well. I think that makes sense?
