### ISSUE TITLE
Websocket error when opening a notebook in chrome 

### ISSUE THREAD

**Issue by trungleduc** [jupyterlab/jupyterlab#12222]
## Description
When opening a notebook in Chome, I get a WebSocket error message in the browser's console, this bug only happens in Chrome and not  Firefox. The notebook still works well. 

- chome 

![chrome](https://user-images.githubusercontent.com/4451292/158479443-82029dac-d7f4-4d89-9482-4d87f3b559d9.gif)

- firefox

![firefox](https://user-images.githubusercontent.com/4451292/158479482-10327d8a-9a7c-464e-b8d3-435477d9003d.gif)

## Reproduce

1. Open a notebook
2. Open browser's console
3. See error 
```
WebSocket connection to 'ws://192.168.1.161:8888/api/kernels/400b09d2-49bc-4c4d-8454-7cfaab29cf3a/channels?session_id=da692e73-1699-45b4-8e2d-c90c3bd2fb8b' failed: 
```

## Expected behavior

No error is logged.

## Context

- Operating System and version: Linux Ubuntu 20.04
- Browser and version:  Chrome 99.0.4844.51 on  Windows 11
- JupyterLab version: current master.

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by trungleduc** [comment]
@davidbrochart might related to [Protocol alignment](https://github.com/jupyterlab/jupyterlab/commit/e89ba66e466ace65c8581d55a550d09f86b9cbce)?

**Comment by davidbrochart** [comment]
Yes, probably. This happens when the client supports the new protocol, but the server doesn't. It is a normal fallback mechanism, until JupyterLab uses a newer jupyter-server.
Also, Tornado doesn't support all websocket versions, which might explain the different behaviors on different browsers.

**Comment by jweill-aws** [comment]
@trungleduc Can you provide the Jupyter versions so that we have the component versions available? `jupyter --version` or `jupyter troubleshoot` should provide this info. Thanks.

**Comment by trungleduc** [comment]
By updating `jupyter_server` to `1.15.6` and `jupyterlab-server` to `2.8.2`, this issue is gone.

**Comment by jtpio** [comment]
Great, thanks @trungleduc for providing the extra context :+1:
