### ISSUE TITLE
Drop deprecated url-loader and file-loader

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#12225]
### Problem

From a point raised by @bollwyvl at the weekly meeting, 

> webpack: lab 4.0 should evaluate replacing url-loader and file-loader with assets 

See [documentation](https://webpack.js.org/guides/asset-modules/)

### Proposed Solution

Use new asset loader of webpack 5 for Lab 4.

### Additional context

Xref https://github.com/jupyterlite/jupyterlite/pull/557

**Comment by fcollonval** [comment]
Seems like `raw-loader` is deprecated too.

**Comment by bollwyvl** [comment]
thanks for making this!

Some notes: 
- to my understanding, with the non-inline `asset/*` types, webpack doesn't even bring the bytes in.nto memory, which might help the top-line memory of a build: we have hundreds of JSON, svg, fonts, etc. files.
- `style-loader` and `css-loader` major versions should be bumped to support some of these changes.
- this change should probably _not_ be backported `@jupyterlab/builder@3.x`, as it would be a fairly significant departure from the existing build API surface, and would be hard to intrepret the errors during `jupyter lab build`

**Comment by fcollonval** [comment]
Xref: [Meeting notes](https://github.com/jupyterlab/team-compass/issues/135#issuecomment-1069381431)

**Comment by blink1073** [comment]
This is also related to https://github.com/jupyterlab/jupyterlab/issues/11248

**Comment by jtpio** [comment]
Some work in progress started in https://github.com/jupyterlab/jupyterlab/pull/12350
