### ISSUE TITLE
Improve keyboard navigability, accessibility, and general UX of "find" feature

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#12230]
The find in notebooks and cells feature of JupyterLab is mouse-dependent for a lot of straightforward actions. Additionally, preferences are not "sticky".

### Problem
One paradigmatic example is: I want to replace all the instances of a variable name in one single cell within my notebook. This action requires four mouse interactions before I can do it. If I decide to do the same thing again, it'll require the same four mouse interactions the second time as well because the checkbox does not "remember" what my last search parameters were. This can be frustrating compared to the integrated find/replace functionality in other environments I am used to.

### Proposed Solution
- Make the find *and* replace features completely available with keyboard interactions.
- Possibly remember the last state of a search and leave checked boxes checked.

**Comment by krassowski** [comment]
I think that we can close this one as the search box is now keyboard navigable and remembers preferences (checkboxes/buttons/filters). It would be much easier to address any remaining tasks if those were delineated Some recent PRs:
- the last remaining state (collapsing/expanding of filters) was made persistent with https://github.com/jupyterlab/jupyterlab/pull/14090
- the last search text is now remembered with:
  - https://github.com/jupyterlab/jupyterlab/pull/13802
  - https://github.com/jupyterlab/jupyterlab/pull/14353 

I opened https://github.com/jupyterlab/jupyterlab/issues/14354 to track a minor focus indicator issue specific to my OS/browser.

**Comment by krassowski** [comment]
A related issue about making it faster to toggle search in selection from keyboard (currently requires tabbing a lot):
- https://github.com/jupyterlab/jupyterlab/issues/14309
