### ISSUE TITLE
When regain internet connection I shouldn't have to refresh and lose everything open in the process

### ISSUE THREAD

**Issue by timothyclemansinsea** [jupyterlab/jupyterlab#1224]
I port forward my JupyterLab via SSH. I lost connection. When I restored connection I ended up having to refresh.

**Comment by blink1073** [comment]
We should at least look at this for beta.

**Comment by blink1073** [comment]
Hi @timothyclemansinsea, the latest version of JupyterLab (0.11.2) has support for re-opening the documents that were open and restoring the directory that was open in the file browser.  We have planned support for restoring the actual layout of the items in the main area.  Does this meet your need?

**Comment by timothyclemansinsea** [comment]
Yes

**Comment by blink1073** [comment]
Great, I'll close this one since #502 is tracking the layout piece.
