### ISSUE TITLE
gitpod badge doesnt launch Lab but binder does

### ISSUE THREAD

**Issue by pflegende** [jupyterlab/jupyterlab#12246]
## Description

like title

## Reproduce

1. Go to '...' klick badge gitpod
3. Click on '...'  [![Gitpod](https://img.shields.io/badge/gitpod_editor-open-blue.svg)](https://gitpod.io/#https://github.com/jupyterlab/jupyterlab)
4. Opening in new window '...' https://8888-jupyterlab-jupyterlab-g7bc717l617.ws-eu38.gitpod.io/lab?
5. See error '...' see only a blank page with the jupy-favicon on top the browser-tab
the source-view of the generated blank web-site:

```
<html>
<body>
<!--StartFragment-->

  | <!doctype html>
-- | --
  | <html lang="en">
  | <head>
  | <meta charset="utf-8">
  | <title>JupyterLab</title>
  | <meta name="viewport" content="width=device-width, initial-scale=1">
  |  
  |  
  |  
  |  
  |  
  |  
  | <script id="jupyter-config-data" type="application/json">
  | {"allow_hidden_files": false, "appName": "JupyterLab", "appNamespace": "lab", "appSettingsDir": "/workspace/jupyterlab/dev_mode/settings", "appUrl": "/lab", "appVersion": "4.0.0a22", "baseUrl": "/", "buildAvailable": false, "buildCheck": false, "cacheFiles": false, "collaborative": false, "devMode": true, "disabledExtensions": [], "exposeAppInBrowser": false, "extraLabextensionsPath": [], "federated_extensions": [], "fullAppUrl": "/lab", "fullLabextensionsUrl": "/lab/extensions", "fullLicensesUrl": "/lab/api/licenses", "fullListingsUrl": "/lab/api/listings", "fullMathjaxUrl": "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js", "fullSettingsUrl": "/lab/api/settings", "fullStaticUrl": "/static/lab", "fullThemesUrl": "/lab/api/themes", "fullTranslationsApiUrl": "/lab/api/translations", "fullTreeUrl": "/lab/tree", "fullWorkspacesApiUrl": "/lab/api/workspaces", "ignorePlugins": [], "labextensionsPath": [], "labextensionsUrl": "/lab/extensions", "licensesUrl": "/lab/api/licenses", "listingsUrl": "/lab/api/listings", "mathjaxConfig": "TeX-AMS_HTML-full,Safe", "mode": "multiple-document", "notebookVersion": "[1, 15, 6, \"\", \"\"]", "preferredPath": "/", "quitButton": true, "schemasDir": "/workspace/jupyterlab/dev_mode/schemas", "serverRoot": "/workspace/jupyterlab", "settingsUrl": "/lab/api/settings", "staticDir": "/workspace/jupyterlab/dev_mode/static", "store_id": 4, "templatesDir": "/workspace/jupyterlab/dev_mode/static", "terminalsAvailable": true, "themesDir": "/workspace/jupyterlab/dev_mode/themes", "themesUrl": "/lab/api/themes", "token": "", "translationsApiUrl": "/lab/api/translations", "treePath": "", "treeUrl": "/lab/tree", "userSettingsDir": "/home/gitpod/.jupyter/lab/user-settings", "workspace": "default", "workspacesApiUrl": "/lab/api/workspaces", "workspacesDir": "/home/gitpod/.jupyter/lab/workspaces", "wsUrl": ""}
  | </script>
  |  
  |  
  | <link rel="icon" type="image/x-icon" href="/static/favicons/favicon.ico" class="idle favicon">
  | <link rel="" type="image/x-icon" href="/static/favicons/favicon-busy-1.ico" class="busy favicon">
  |  
  |  
  | <script defer src="/static/lab/vendors-node_modules_whatwg-fetch_fetch_js.ca4e2e1e816b94c47010.js"></script><script defer src="/static/lab/main.4c608567fef39bf8e628.js"></script></head>
  | <body>
  |  
  | <script type="text/javascript">
  | /* Remove token from URL. */
  | (function () {
  | var location = window.location;
  | var search = location.search;
  |  
  | // If there is no query string, bail.
  | if (search.length <= 1) {
  | return;
  | }
  |  
  | // Rebuild the query string without the `token`.
  | var query = '?' + search.slice(1).split('&')
  | .filter(function (param) { return param.split('=')[0] !== 'token'; })
  | .join('&');
  |  
  | // Rebuild the URL with the new query string.
  | var url = location.origin + location.pathname +
  | (query !== '?' ? query : '') + location.hash;
  |  
  | if (url === location.href) {
  | return;
  | }
  |  
  | window.history.replaceState({ }, '', url);
  | })();
  | </script>
  |  
  | </body>
  | </html>

<!--EndFragment-->
</body>
</html>
```

## Expected behavior

should looking like launched in bender

may be, the gitpod laucher badge only need the right link like in the binder badge attached. The gitpod badge seems need a link to a file with a "ipynb" extension, so it should be a happier greenhorn leaving the readme

;)

<html>
<body>

--

<br class="Apple-interchange-newline">
</body>
</html>

 <html>
<body>

--

<br class="Apple-interchange-newline">
</body>
</html>

## Context

- Operating System and version: 
- Browser and version:  Opera 84.0.4316.31, latest
- JupyterLab version: initial like 

in the readme presented

---
---

![Opera Momentaufnahme_2022-03-20_234935_jupyterlab-jupyterlab-g7bc717l617 ws-eu38 gitpod io](https://user-images.githubusercontent.com/52720420/159189834-dbab8a64-7a5c-47df-91a6-84840198887a.png)
![Opera Momentaufnahme_2022-03-20_235129_jupyterlab-jupyterlab-g7bc717l617 ws-eu38 gitpod io](https://user-images.githubusercontent.com/52720420/159189836-ed171ef2-2c2d-4251-99a9-6a9e55ead547.png)
![Opera Momentaufnahme_2022-03-20_235553_jupyterlab-jupyterlab-g7bc717l617 ws-eu38 gitpod io](https://user-images.githubusercontent.com/52720420/159189838-faba8a51-a3d2-4014-bac0-55af8a9a194c.png)

---
---

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>JupyterLab</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  

  <script id="jupyter-config-data" type="application/json">
    {"allow_hidden_files": false, "appName": "JupyterLab", "appNamespace": "lab", "appSettingsDir": "/workspace/jupyterlab/dev_mode/settings", "appUrl": "/lab", "appVersion": "4.0.0a22", "baseUrl": "/", "buildAvailable": false, "buildCheck": false, "cacheFiles": false, "collaborative": false, "devMode": true, "disabledExtensions": [], "exposeAppInBrowser": false, "extraLabextensionsPath": [], "federated_extensions": [], "fullAppUrl": "/lab", "fullLabextensionsUrl": "/lab/extensions", "fullLicensesUrl": "/lab/api/licenses", "fullListingsUrl": "/lab/api/listings", "fullMathjaxUrl": "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js", "fullSettingsUrl": "/lab/api/settings", "fullStaticUrl": "/static/lab", "fullThemesUrl": "/lab/api/themes", "fullTranslationsApiUrl": "/lab/api/translations", "fullTreeUrl": "/lab/tree", "fullWorkspacesApiUrl": "/lab/api/workspaces", "ignorePlugins": [], "labextensionsPath": [], "labextensionsUrl": "/lab/extensions", "licensesUrl": "/lab/api/licenses", "listingsUrl": "/lab/api/listings", "mathjaxConfig": "TeX-AMS_HTML-full,Safe", "mode": "multiple-document", "notebookVersion": "[1, 15, 6, \"\", \"\"]", "preferredPath": "/", "quitButton": true, "schemasDir": "/workspace/jupyterlab/dev_mode/schemas", "serverRoot": "/workspace/jupyterlab", "settingsUrl": "/lab/api/settings", "staticDir": "/workspace/jupyterlab/dev_mode/static", "store_id": 4, "templatesDir": "/workspace/jupyterlab/dev_mode/static", "terminalsAvailable": true, "themesDir": "/workspace/jupyterlab/dev_mode/themes", "themesUrl": "/lab/api/themes", "token": "", "translationsApiUrl": "/lab/api/translations", "treePath": "", "treeUrl": "/lab/tree", "userSettingsDir": "/home/gitpod/.jupyter/lab/user-settings", "workspace": "default", "workspacesApiUrl": "/lab/api/workspaces", "workspacesDir": "/home/gitpod/.jupyter/lab/workspaces", "wsUrl": ""}
  </script>

  
  <link rel="icon" type="image/x-icon" href="[/static/favicons/favicon.ico](https://8888-jupyterlab-jupyterlab-g7bc717l617.ws-eu38.gitpod.io/static/favicons/favicon.ico)" class="idle favicon">
  <link rel="" type="image/x-icon" href="[/static/favicons/favicon-busy-1.ico](https://8888-jupyterlab-jupyterlab-g7bc717l617.ws-eu38.gitpod.io/static/favicons/favicon-busy-1.ico)" class="busy favicon">
  

<script defer src="[/static/lab/vendors-node_modules_whatwg-fetch_fetch_js.ca4e2e1e816b94c47010.js](https://8888-jupyterlab-jupyterlab-g7bc717l617.ws-eu38.gitpod.io/static/lab/vendors-node_modules_whatwg-fetch_fetch_js.ca4e2e1e816b94c47010.js)"></script><script defer src="[/static/lab/main.4c608567fef39bf8e628.js](https://8888-jupyterlab-jupyterlab-g7bc717l617.ws-eu38.gitpod.io/static/lab/main.4c608567fef39bf8e628.js)"></script></head>
<body>

<script type="text/javascript">
  /* Remove token from URL. */
  (function () {
    var location = window.location;
    var search = location.search;

    // If there is no query string, bail.
    if (search.length <= 1) {
      return;
    }

    // Rebuild the query string without the `token`.
    var query = '?' + search.slice(1).split('&')
      .filter(function (param) { return param.split('=')[0] !== 'token'; })
      .join('&');

    // Rebuild the URL with the new query string.
    var url = location.origin + location.pathname +
      (query !== '?' ? query : '') + location.hash;

    if (url === location.href) {
      return;
    }

    window.history.replaceState({ }, '', url);
  })();
</script>

</body>
</html>

**Comment by jweill-aws** [comment]
Gitpod is intended to be used as a web-based IDE, which looks and works like Visual Studio Code, for editing the source code of JupyterLab. Binder, on the other hand, is an interactive environment for running and testing JupyterLab. Gitpod appears to start a server on its virtual machine running on port 8888, but connecting to that host on port 8888 doesn't appear to work. That may be due to my own firewall or a remote firewall.

Closing because the Gitpod badge is not intended to launch JupyterLab and the Binder badge is intended to launch JupyterLab. Please reopen if you have other questions or if I misinterpreted your question.
