### ISSUE TITLE
Create new text file or notebook and cancel, file still created

### ISSUE THREAD

**Issue by benbovy** [jupyterlab/jupyterlab#1225]
When I create a new notebook or text file, either from the launcher or from the "+" dropdown menu of the file browser, and then I press the cancel button of the dialog, the file is still created in the current folder.

Tested with version 0.8.0.

**Comment by blink1073** [comment]
Hi @benbovy, I suspect that the file has been deleted but the file browser listing had not been updated yet, can you try reproducing this and then hitting the refresh button on the file browser?

**Comment by benbovy** [comment]
Indeed the file has been deleted, I just missed the refresh button on the file browser (which BTW I almost never used in the browser of the classic notebook interface). Is it possible to automatically refresh the browser listing after hitting the cancel button in the create dialog? If not, I don't mind having to refresh the listing manually.

**Comment by blink1073** [comment]
There is more that we can do to update the running files and kernels based on events like these.  I'll leave this open as a reminder.
