### ISSUE TITLE
Search results not getting highlighted in filebrowser

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#12267]
## Description
In jupyterlab 3.3.x, the search results in the filebrowser no longer get highlighted. Here are some screenshots - 
In lab 3.3.x - 
![image](https://user-images.githubusercontent.com/30082866/159863654-d0292665-124b-41a2-89c1-313b1d48b36e.png)
In lab 3.2.4 - 
![image](https://user-images.githubusercontent.com/30082866/159863759-fc1bb119-e127-4167-a477-349deadf6c0b.png)

## Reproduce
Enter a search query in the filebrowser search.

## Expected behavior
Matching search results should be highlighted.

## Context

- Operating System and version: Linux Ubuntu 21.04 
- Browser and version: Chrome 92 
- JupyterLab version: 3.3.2

**Comment by jweill-aws** [comment]
@marthacryan can take a look at this one.
