### ISSUE TITLE
"IPython is not defined" javascript error when using @manipulate

### ISSUE THREAD

**Issue by djsegal** [jupyterlab/jupyterlab#1226]
For example, when running the following code inside `jupyter lab` (and not `jupyter notebook`)

```
using Interact;
@manipulate for x=1:10 
    x/2
end
```

the following errors are raised in the javascript console:

```
(unknown) Uncaught ReferenceError: IPython is not defined(…)
(unknown) Uncaught ReferenceError: $ is not defined(…)
extensions.bundle.js:8988 Uncaught (in promise) Error: Object 'jupyter.widget' not found in registry(…)
```

Any idea what's causing this?

**Comment by jasongrout** [comment]
Is this using the Julia kernel? What commit of the jupyterlab_widgets extension are you using?

**Comment by djsegal** [comment]
I'm guessing this is just one of those things that happened and probably has been fixed somewhere along the line since then.

Closing
