### ISSUE TITLE
JupyterLab 3.4 Release

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#12268]
This is a meta issue to list enhancement candidates for the next minor release 3.4.

Please add a comment with the PRs you would like to be part of 3.4. Eligible candidates cannot break the 3.x API.

- [x] https://github.com/jupyterlab/jupyterlab/pull/12028
- [x] https://github.com/jupyterlab/jupyterlab/pull/12195
- [x] https://github.com/jupyterlab/jupyterlab/pull/12250
- [x] https://github.com/jupyterlab/jupyterlab/pull/12258
- [x] https://github.com/jupyterlab/jupyterlab/pull/12204
- [x] https://github.com/jupyterlab/jupyterlab/pull/11074
- [x] https://github.com/jupyterlab/jupyterlab/pull/12082
- [x] https://github.com/jupyterlab/jupyterlab/pull/12255
- [ ] <s>https://github.com/jupyterlab/jupyterlab/pull/12278</s>
- [x] https://github.com/jupyterlab/jupyterlab/pull/12310
- [x] https://github.com/jupyterlab/jupyterlab/pull/12311
- [x] https://github.com/jupyterlab/jupyterlab/pull/12344

> As discussed in [JupyterLab weekly meeting](https://github.com/jupyterlab/team-compass/issues/135#issuecomment-1083414990), this list will be frozen on Friday. And the release process of 3.4.0 will start when the PRs are merged.

**Comment by jtpio** [comment]
Thanks @fcollonval for opening this.

Since this was discussed in https://github.com/jupyterlab/jupyterlab/pull/12074, should we create a `3.4.0` milestone for the first `3.4.0` final release. And `3.4.x` for backports and future work on `3.4`?

This could help keep track of blockers for the 3.4 final release, such as follow-up improvements to https://github.com/jupyterlab/jupyterlab/pull/12028 as mentioned yesterday during the weekly call.

**Comment by ajbozarth** [comment]
If https://github.com/jupyterlab/jupyterlab/pull/12344 is approved I would love to add it to this list for release

**Comment by jtpio** [comment]
Reposting here for visibility.

According to https://github.com/jupyterlab/team-compass/issues/135#issuecomment-1091630484, the expected release date for 3.4.0 seems to be early May 2022.

Feel free to correct if this has changed in the meantime, thanks!

**Comment by fcollonval** [comment]
> the expected release date for 3.4.0 seems to be early May 2022.

:+1: 

There are still two PRs to merge and I can cut a beta.

**Comment by fcollonval** [comment]
Closing as JupyterLab 3.4.0 has been released.
