### ISSUE TITLE
Switch to Pre-Commit

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#12272]
### Problem
There are several checks that need to by run on the code base.  Some of them are run using `husky`, and slower ones are run on CI.  Additionally, if there is a lint or integrity error, a maintainer or the original PR author has to manually run the command and push the commit.

### Proposed Solution
Now that `meeseeks` supports running `pre-commit`, we should switch to using it. 

- We can add external or local repo checks for existing husky checks
- We would use manual hook for `integrity` and `eslint:check:typed` so it only runs in CI and by meeseeks.
- We could add `pre-commit  install` to editable install since `husky` is currently installed there
- We would add everything used by [`jupyter_server`](https://github.com/jupyter-server/jupyter_server/blob/cd1b1b886db08c6480329c3f0832d05f15d49a19/.pre-commit-config.yaml) except `black`
- We could add `black` and other auto-formatters as a follow up commit

- Then we would add flake8 support and and add a [.git-blame-ignore-revs](https://github.com/jupyter-server/jupyter_server/blob/cd1b1b886db08c6480329c3f0832d05f15d49a19/.git-blame-ignore-revs) file in a follow up PR
- Finally, we would run the auto-formatters on previous branches to make backports easier

**Comment by krassowski** [comment]
:+1: Adding `.git-blame-ignore-revs` would also close #10607; it seems that some kind of GitHub support for ignoring revisions landed recently (as an experimental function? I cannot find any announcement, but saw a notification on GitHub)

**Comment by blink1073** [comment]
Oh sweet!  https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/

**Comment by fcollonval** [comment]
Closing this one as done
