### ISSUE TITLE
Sporadic Input Swallowing

### ISSUE THREAD

**Issue by agoose77** [jupyterlab/jupyterlab#12274]
I've deleted the template here because there's not much detail :( I'm hoping that others will notice this bug and be able to reproduce more easily than I have.

Sometimes, JupyterLab starts swallowing certain keycodes, which requires the front-end to be reloaded in order to be fixed. I originally noticed this with command keys like <kbd>c</kbd> and <kbd>r</kbd>, but I also saw it today with <kbd>-</kbd>. I'm not sure whether it is related to the command system, or if that's just coincidence.

Has anyone else seen such behavior? I reported it first informally  on Jan 13 2022, so it has been around at least since then.
@fcollonval also added (on Matrix/Gitter)
> I'm experiencing that in a PR to port RISE on JupyterLab 3. But did not have time to investigate.

**Comment by JasonWeill** [comment]
@agoose77 Thanks for your issue! Sorry for the delay in following up.

Are you still seeing this issue on newer versions of JupyterLab? If so, can you please share the version(s) that you're using? If possible, could you try using an alpha build of JupyterLab 4.0.0?

Info about your operating system, browser, OS locale, and keyboard type (UK typically uses ISO) can help as well. If you have any extensions, particularly content-blocking extensions like ad blockers, do you see this behavior in private/incognito mode with extensions disabled?

Any JavaScript console errors that you're seeing?

**Comment by JasonWeill** [comment]
There hasn't been any additional activity on this issue, so I'm closing it. If you continue to see this behavior, and if no other open issue documents it, please reopen. Thanks!

**Comment by agoose77** [comment]
Thanks @JasonWeill. I can't say that I've seen this happening recently, so this feels like a good idea! :)
