### ISSUE TITLE
Settings editor should remember last mode

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12283]
### Problem

Not everyone finds the form-based settings editor better than the JSON version. Those users need to click on JSON each time, adding a step to get to their editor of choice.

### Proposed Solution

The settings editor should remember if the user was in form-based or JSON-based last and open itself in that mode.

### Additional context

N/A

**Comment by jweill-aws** [comment]
Triage notes: There is a command to open the JSON settings editor immediately, although the UI only includes a command to open the form-based editor. Accepted as an enhancement.

**Comment by jtpio** [comment]
The default menu entry could be replaced to use the `settingeditor:open` command instead, via the settings system: https://jupyterlab.readthedocs.io/en/latest/extension/extension_points.html#settings-defined-menu

![image](https://user-images.githubusercontent.com/591645/165249884-630a082a-1f49-44e6-8bd2-9e840b06bf4f.png)
