### ISSUE TITLE
Rendering variable is debugger is not working. Waited minutes for it and it didnt show up (keep seeing the spinner icon)

### ISSUE THREAD

**Issue by assadi** [jupyterlab/jupyterlab#12286]
## Description

Rendering variable is debugger is not working. Waited minutes for it and it didnt show up (keep seeing the spinner icon)

## Reproduce

Create a pandas data frame and try to render it in a variable

## Expected behavior

It should render it as a table

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
Could you please complete the bug report template and provide a reproducible example? Versions of jupyterlab, ipython and ipykernel/xeus may be of high importance.

**Comment by jweill-aws** [comment]
@assadi Can you please provide the info @krassowski requested last week? That will help us to diagnose the source of this problem. Thanks.

**Comment by afshin** [comment]
Closing as likely resolved and duplicate of https://github.com/jupyterlab/jupyterlab/issues/12568
