### ISSUE TITLE
Settings editor should show default value

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12284]
### Problem

One of the advantages of JSON editing of settings is the what changed is very clear. The new settings form-based ui does a great job highlighting which plugins have any differences, but not what those differences are.

### Proposed Solution
There are many ways to solve this, below is one idea:
1. Add some styling (e.g. color) to indicate that a setting is different than the default
2. Add tooltip/popover/... to show the original value

**Comment by krassowski** [comment]
There already is some styling highlighting entries that changed - see the blue bar next to "Filter on file name with a fuzzy search" (enabled by default) and "Show hidden files" (disabled by default):

![Screenshot from 2022-03-28 23-41-43](https://user-images.githubusercontent.com/5832902/160498926-fad8b924-e57e-4343-ab3b-25c6d12c4578.png)

Indeed there is no way to preview the default (which is not obvious for non-binary fields). As an alternative to tooltip/popover, we could append "Default: X" to the description.

**Comment by echarles** [comment]
@mlucool 

> Add some styling (e.g. color) to indicate that a setting is different than the default

Does the above image by @krassowski with the blue left bar for changes answer the need?

> Add tooltip/popover/... to show the original value

Should we append "Default: X" to the description if the value is not the default one? So only display that default value for highlighted changed settings.

**Comment by mlucool** [comment]
I think we still need a default shown somewhere, but I think the blue is sufficient.

**Comment by echarles** [comment]
so having the default always shown, even if the value is the default?

**Comment by mlucool** [comment]
No, more like you originally suggested - only show it on changed values. I suspect otherwise the UX may be a bit crowded

**Comment by jweill-aws** [comment]
Triage: As implementation details:
1. Should we show the default value on hover? To the side of the input?
2. Should there be a control to revert a modified value to its default?
3. Should the default value be visible in drop-down controls? (See screen shot of this in VS Code)

![image](https://user-images.githubusercontent.com/93281816/161111974-e49569c0-ba6a-44e8-bb65-7b7f719de7d7.png)
