### ISSUE TITLE
Setting editor has incorrect defaults

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12294]
## Description

The settings editor's "System Defaults" has the incorrect default types for some keys. Instead of arrays, it defaults to objects.

## Reproduce

1. Open the JSON settings editor
2. Copy/paste a shortcut from "Systems Defaults" to "User Preferences"
3. Save

You'll see type errors on `winKeys`, `macKeys`, and `linuxKeys`:
![image](https://user-images.githubusercontent.com/1813603/160674537-6f4311df-693d-443e-a016-2314dc2d293c.png)

## Expected behavior

Copy/paste from system defaults to user preferences just works.

## Context
Lab@3.3.0

**Comment by jweill-aws** [comment]
Triage notes: @krassowski can provide more context for where this occurs in code

**Comment by krassowski** [comment]
The `winKeys`, `macKeys` and `linuxKeys` are handled by lumino; these are described in JupyterLab by:

https://github.com/jupyterlab/jupyterlab/blob/83b2ae958f86b8a6925b9e0c36adb7b897bff62b/packages/shortcuts-extension/schema/shortcuts.json#L26-L37

and:

https://github.com/jupyterlab/jupyterlab/blob/83b2ae958f86b8a6925b9e0c36adb7b897bff62b/packages/settingregistry/src/plugin-schema.json#L228-L250

The bug must be somewhere in the normalization code or JSON schema population, which I am looking at right now as an offshoot from fixing a 4.1 release blocker (https://github.com/jupyterlab/jupyterlab/issues/15636#issuecomment-1890991475).

The population of the defaults happens in:

https://github.com/jupyterlab/jupyterlab/blob/83b2ae958f86b8a6925b9e0c36adb7b897bff62b/packages/settingregistry/src/settingregistry.ts#L1438-L1496

**Comment by krassowski** [comment]
Note to self: rather than having an empty array on the defaults side we want to avoid populating these keys at all because an empty array means that the keybinding is disabled on the specific OS.
