### ISSUE TITLE
play/run button disappears when switching between tabs

### ISSUE THREAD

**Issue by LeoWelter** [jupyterlab/jupyterlab#12292]
## Description
The play button disappears when switching to another tab and back, I first noticed it with text files opened in a tab.
![Kapture 2022-03-29 at 11 41 49](https://user-images.githubusercontent.com/41105099/160606755-d2fc2675-f61a-44e9-ad2a-32aa314560a3.gif)

The cells can still be run with <CTRL><enter>

## Reproduce

- open a jupyterlab notebook (in my case behind jupyterhub)
- open a random textfile in another tab
- switch to the tab and back to the notebok
- play button now disappeared, but cells can still be run.
- Situation reverts on full browser reload (tested on firefox and safari)

when switching tabs, the playbutton remains as it is.

## Context

- Operating System and version: 
two independent Installations on both Ubuntu 18.04 and CentOS7 , both jupyterlab 3.3.2, one installed in a conda env, the other plain virtual env with pip install ...

I noticed after updating the virtual env on the ubuntu 18.04 install from 3.2.0 to 3.3.2
The latest version in which I could NOT reproduce the version was jupyterlab==3.2.9
Upon reinstall of 3.3.2 (or 3.3.1, 3.3.0) I could reproduce the behaviour again.
maybe it has something to do with 

Support dynamic toolbar definition [#12078](https://github.com/jupyterlab/jupyterlab/pull/12078) ([@fcollonval](https://github.com/fcollonval) introduced in 3.3.0

- Browser and version: 
safari and firefox, on MacOS Monterey (M1) and MacOS Bigsur (Intel mac)

- JupyterLab version: 

jupyter-server-mathjax    0.2.5              pyhc268e32_0    conda-forge
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py38h578d9bd_1    conda-forge
jupyter_server            1.13.5             pyhd3eb1b0_0
jupyter_telemetry         0.1.0                      py_0
jupyterhub                1.3.0            py38h578d9bd_0    conda-forge
jupyterhub-base           1.3.0            py38h578d9bd_0    conda-forge
jupyterlab                3.3.2              pyhd3eb1b0_0
jupyterlab-git            0.34.2             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.10.3             pyhd3eb1b0_1
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.
TypeError: i[r] is not a function
    n index.js:567
    caption index.js:414
    caption index.es6.js:242
    t widget.js:902
    Ce widget.js:706
    render vdom.js:172
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    slot vdom.js:161
    m index.es6.js:459
    l index.es6.js:416
    emit index.es6.js:99
    notifyCommandChanged index.es6.js:147
    activate index.js:336
    m index.es6.js:459
    l index.es6.js:416
    emit index.es6.js:99
    _layoutDebouncer shell.js:73
    d 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    factory 114.21ecdb3d2c7cbd7ac487.js:1
    _execute 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    f 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    a 114.21ecdb3d2c7cbd7ac487.js:1
    promise callback*c 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    schedule 114.21ecdb3d2c7cbd7ac487.js:1
    invoke 114.21ecdb3d2c7cbd7ac487.js:1
    _onLayoutModified shell.js:992
    _onCurrentChanged shell.js:977
    m index.es6.js:459
    l index.es6.js:416
    emit index.es6.js:99
    _setWidgets index.es6.js:10953
    _evtFocus index.es6.js:10971
    handleEvent index.es6.js:10934
[react-dom.production.min.js:216:199](webpack://jupyterlab/application-top/node_modules/react-dom/cjs/react-dom.production.min.js)
TypeError: i[r] is not a function
    n index.js:567
    caption index.js:414
    caption index.es6.js:242
    t widget.js:902
    Ce widget.js:706
    render vdom.js:172
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    slot vdom.js:161
    m index.es6.js:459
    l index.es6.js:416
    emit index.es6.js:99
    notifyCommandChanged index.es6.js:147
    activate index.js:336
    m index.es6.js:459
    l index.es6.js:416
    emit index.es6.js:99
    _layoutDebouncer shell.js:73
    d 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    factory 114.21ecdb3d2c7cbd7ac487.js:1
    _execute 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    f 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    a 114.21ecdb3d2c7cbd7ac487.js:1
    promise callback*c 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    schedule 114.21ecdb3d2c7cbd7ac487.js:1
    invoke 114.21ecdb3d2c7cbd7ac487.js:1
    _onLayoutModified shell.js:992
    _onCurrentChanged shell.js:977
    m index.es6.js:459
    l index.es6.js:416
    emit index.es6.js:99
    _setWidgets index.es6.js:10953
    _evtFocus index.es6.js:10971
    handleEvent index.es6.js:10934
[index.es6.js:211:16](webpack://jupyterlab/application-top/node_modules/@lumino/signaling/dist/index.es6.js)
    exceptionHandler index.es6.js:211
    m index.es6.js:462
    l index.es6.js:416
    emit index.es6.js:99
    notifyCommandChanged index.es6.js:147
    activate index.js:336
    m index.es6.js:459
    l index.es6.js:416
    emit index.es6.js:99
    _layoutDebouncer shell.js:73
    d 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    factory 114.21ecdb3d2c7cbd7ac487.js:1
    _execute 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    (Async: FrameRequestCallback)
    f 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    s 114.21ecdb3d2c7cbd7ac487.js:1
    a 114.21ecdb3d2c7cbd7ac487.js:1
    (Async: promise callback)
    c 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    c 114.21ecdb3d2c7cbd7ac487.js:1
    schedule 114.21ecdb3d2c7cbd7ac487.js:1
    invoke 114.21ecdb3d2c7cbd7ac487.js:1
    _onLayoutModified shell.js:992
    _onCurrentChanged shell.js:977
    m index.es6.js:459
    l index.es6.js:416
    emit index.es6.js:99
    _setWidgets index.es6.js:10953
    _evtFocus index.es6.js:10971
    handleEvent index.es6.js:10934

​
</pre>
</details>

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/play-button-disappears-randomly/13556/6

**Comment by ceteri** [comment]
I also encountered this bug in 3.3.2, and it would happen in Chrome-based browsers whenever I switched tabs from viewing a notebook to some other tab in JupyterLab.

Upgrading to 3.3.4 appears to resolve this issue. Thanks -

**Comment by fcollonval** [comment]
This is fixed by #12292 (you will need to upgrade to v3.3.4 or higher)
