### ISSUE TITLE
When I was developing the cell of JupyterLab with React.Component<IProps, IState>, a click event occurred and I could not respond

### ISSUE THREAD

**Issue by javyxu** [jupyterlab/jupyterlab#12305]
## Description

When I was developing the cell of **JupyterLab** with **React.Component<IProps, IState>**, a click event occurred and I could not respond

## Reproduce

<img width="921" alt="image" src="https://user-images.githubusercontent.com/22185273/160873306-5799ee8f-002c-48ff-9901-276d23a65a03.png">

<img width="956" alt="image" src="https://user-images.githubusercontent.com/22185273/160873420-5e10a603-664b-44a0-bbc3-fa684d9e7786.png">

<img width="835" alt="image" src="https://user-images.githubusercontent.com/22185273/160873554-1765d761-5fb7-45b1-953b-f1305b30205d.png">

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/22185273/160873723-5c7a4a49-56ff-4881-92dd-95dc9c3eca8f.png">

## Expected behavior

<img width="1933" alt="image" src="https://user-images.githubusercontent.com/22185273/160874339-d521e7a8-c674-4b26-94c7-29521eb0c1cd.png">

## Context

- Operating System and version: Linux Ubuntu 20.04
- Browser and version: 99.0
- JupyterLab version: 3.3.2

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /opt/conda/bin
        /opt/conda/condabin
        /opt/conda/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /opt/conda/bin
        /opt/conda/lib/python38.zip
        /opt/conda/lib/python3.8
        /opt/conda/lib/python3.8/lib-dynload
        /opt/conda/lib/python3.8/site-packages
        /home/kale/labextension

sys.executable:
        /opt/conda/bin/python3.8

sys.version:
        3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
        [GCC 9.3.0]

platform.platform():
        Linux-5.4.0-65-generic-x86_64-with-glibc2.10

which -a jupyter:
        /opt/conda/bin/jupyter
        /opt/conda/bin/jupyter

pip list:
        Package                    Version   Editable project location
        -------------------------- --------- -------------------------
        absl-py                    0.12.0
        adal                       1.2.7
        anyio                      3.5.0
        argon2-cffi                21.3.0
        argon2-cffi-bindings       21.2.0
        arrow                      1.2.2
        astor                      0.8.1
        asttokens                  2.0.5
        attrs                      20.3.0
        autopep8                   1.4.4
        azure-common               1.1.28
        azure-storage-blob         2.1.0
        azure-storage-common       2.1.0
        Babel                      2.9.1
        backcall                   0.2.0
        beautifulsoup4             4.10.0
        binaryornot                0.4.4
        bleach                     4.1.0
        brotlipy                   0.7.0
        cachetools                 4.2.4
        certifi                    2021.10.8
        cffi                       1.14.6
        chardet                    4.0.0
        charset-normalizer         2.0.12
        click                      8.0.4
        cloudpickle                2.0.0
        colorama                   0.4.4
        conda                      4.10.1
        conda-package-handling     1.8.0
        cookiecutter               1.7.3
        cryptography               36.0.2
        debugpy                    1.6.0
        decorator                  5.1.1
        defusedxml                 0.7.1
        Deprecated                 1.2.13
        deprecation                2.1.0
        dill                       0.3.4
        docstring-parser           0.13
        entrypoints                0.4
        executing                  0.8.3
        fire                       0.4.0
        google-api-core            2.7.1
        google-api-python-client   1.12.11
        google-auth                1.35.0
        google-auth-httplib2       0.1.0
        google-cloud-core          2.2.3
        google-cloud-storage       1.44.0
        google-crc32c              1.3.0
        google-resumable-media     2.3.2
        googleapis-common-protos   1.56.0
        grpcio                     1.44.0
        httplib2                   0.20.4
        idna                       3.3
        importlib-resources        5.4.0
        ipykernel                  6.9.2
        ipython                    8.1.1
        ipython-genutils           0.2.0
        jedi                       0.18.1
        Jinja2                     3.0.3
        jinja2-time                0.2.0
        json5                      0.9.6
        jsonschema                 3.2.0
        jupyter-client             6.1.12
        jupyter-core               4.9.2
        jupyter-packaging          0.12.0
        jupyter-server             1.13.5
        jupyterlab                 3.3.2
        jupyterlab-pygments        0.1.2
        jupyterlab-server          2.11.2
        kfp                        1.8.11
        kfp-pipeline-spec          0.1.14
        kfp-server-api             1.8.1
        kfserving                  0.4.1
        kubeflow-kale              0.7.0
        kubeflow-kale-labextension 0.7.0     /home/kale/labextension
        kubernetes                 10.0.1
        MarkupSafe                 2.1.1
        matplotlib-inline          0.1.3
        minio                      7.1.5
        mistune                    0.8.4
        ml-metadata                0.30.0
        nbclassic                  0.3.7
        nbclient                   0.5.13
        nbconvert                  5.6.1
        nbformat                   4.4.0
        nest-asyncio               1.5.4
        networkx                   2.7.1
        notebook                   6.4.10
        notebook-shim              0.1.0
        numpy                      1.22.3
        oauthlib                   3.2.0
        packaging                  21.3
        pandocfilters              1.5.0
        parso                      0.8.3
        pexpect                    4.8.0
        pickleshare                0.7.5
        pip                        22.0.4
        poyo                       0.5.0
        progress                   1.6
        prometheus-client          0.13.1
        prompt-toolkit             3.0.28
        protobuf                   3.19.4
        psutil                     5.9.0
        ptyprocess                 0.7.0
        pure-eval                  0.2.2
        pyasn1                     0.4.8
        pyasn1-modules             0.2.8
        pycodestyle                2.8.0
        pycosat                    0.6.3
        pycparser                  2.21
        pydantic                   1.9.0
        pyflakes                   2.4.0
        Pygments                   2.11.2
        PyJWT                      2.3.0
        pyOpenSSL                  22.0.0
        pyparsing                  3.0.7
        pyrsistent                 0.18.1
        PySocks                    1.7.1
        python-dateutil            2.8.2
        python-slugify             6.1.1
        pytz                       2022.1
        PyYAML                     5.4.1
        pyzmq                      22.3.0
        requests                   2.27.1
        requests-oauthlib          1.3.1
        requests-toolbelt          0.9.1
        rsa                        4.8
        ruamel-yaml-conda          0.15.80
        Send2Trash                 1.8.0
        setuptools                 60.10.0
        six                        1.15.0
        sniffio                    1.2.0
        soupsieve                  2.3.1
        stack-data                 0.2.0
        strip-hints                0.1.10
        table-logger               0.3.6
        tabulate                   0.8.9
        termcolor                  1.1.0
        terminado                  0.13.3
        testpath                   0.6.0
        text-unidecode             1.3
        tomlkit                    0.10.0
        tornado                    6.1
        tqdm                       4.63.0
        traitlets                  5.1.1
        typer                      0.4.0
        typing-extensions          3.10.0.2
        uritemplate                3.0.1
        urllib3                    1.26.9
        wcwidth                    0.2.5
        webencodings               0.5.1
        websocket-client           1.3.1
        wheel                      0.37.1
        wrapt                      1.14.0
        zipp                       3.7.0

conda list:
        # packages in environment at /opt/conda:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       1_gnu    conda-forge
        absl-py                   0.12.0                   pypi_0    pypi
        adal                      1.2.7                    pypi_0    pypi
        anyio                     3.5.0                    pypi_0    pypi
        argon2-cffi               21.3.0                   pypi_0    pypi
        argon2-cffi-bindings      21.2.0                   pypi_0    pypi
        argparse                  1.4.0                    pypi_0    pypi
        arrow                     1.2.2                    pypi_0    pypi
        astor                     0.8.1                    pypi_0    pypi
        asttokens                 2.0.5                    pypi_0    pypi
        attrs                     20.3.0                   pypi_0    pypi
        autopep8                  1.4.4                    pypi_0    pypi
        azure-common              1.1.28                   pypi_0    pypi
        azure-storage-blob        2.1.0                    pypi_0    pypi
        azure-storage-common      2.1.0                    pypi_0    pypi
        babel                     2.9.1                    pypi_0    pypi
        backcall                  0.2.0                    pypi_0    pypi
        beautifulsoup4            4.10.0                   pypi_0    pypi
        binaryornot               0.4.4                    pypi_0    pypi
        bleach                    4.1.0                    pypi_0    pypi
        brotlipy                  0.7.0           py38h497a2fe_1003    conda-forge
        ca-certificates           2021.10.8            ha878542_0    conda-forge
        cachetools                4.2.4                    pypi_0    pypi
        certifi                   2021.10.8        py38h578d9bd_1    conda-forge
        cffi                      1.14.6           py38ha65f79e_0    conda-forge
        chardet                   4.0.0                    pypi_0    pypi
        charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
        click                     8.0.4                    pypi_0    pypi
        cloudpickle               2.0.0                    pypi_0    pypi
        colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
        conda                     4.10.1           py38h578d9bd_0    conda-forge
        conda-package-handling    1.8.0            py38h0a891b7_0    conda-forge
        cookiecutter              1.7.3                    pypi_0    pypi
        cryptography              36.0.2           py38h2b5fc30_0    conda-forge
        debugpy                   1.6.0                    pypi_0    pypi
        decorator                 5.1.1                    pypi_0    pypi
        defusedxml                0.7.1                    pypi_0    pypi
        deprecated                1.2.13                   pypi_0    pypi
        deprecation               2.1.0                    pypi_0    pypi
        dill                      0.3.4                    pypi_0    pypi
        docstring-parser          0.13                     pypi_0    pypi
        entrypoints               0.4                      pypi_0    pypi
        executing                 0.8.3                    pypi_0    pypi
        fire                      0.4.0                    pypi_0    pypi
        google-api-core           2.7.1                    pypi_0    pypi
        google-api-python-client  1.12.11                  pypi_0    pypi
        google-auth               1.35.0                   pypi_0    pypi
        google-auth-httplib2      0.1.0                    pypi_0    pypi
        google-cloud-core         2.2.3                    pypi_0    pypi
        google-cloud-storage      1.44.0                   pypi_0    pypi
        google-crc32c             1.3.0                    pypi_0    pypi
        google-resumable-media    2.3.2                    pypi_0    pypi
        googleapis-common-protos  1.56.0                   pypi_0    pypi
        grpcio                    1.44.0                   pypi_0    pypi
        httplib2                  0.20.4                   pypi_0    pypi
        idna                      3.3                pyhd8ed1ab_0    conda-forge
        importlib-resources       5.4.0                    pypi_0    pypi
        ipykernel                 6.9.2                    pypi_0    pypi
        ipython                   8.1.1                    pypi_0    pypi
        ipython-genutils          0.2.0                    pypi_0    pypi
        jedi                      0.18.1                   pypi_0    pypi
        jinja2                    3.0.3                    pypi_0    pypi
        jinja2-time               0.2.0                    pypi_0    pypi
        json5                     0.9.6                    pypi_0    pypi
        jsonschema                3.2.0                    pypi_0    pypi
        jupyter-client            6.1.12                   pypi_0    pypi
        jupyter-core              4.9.2                    pypi_0    pypi
        jupyter-packaging         0.12.0                   pypi_0    pypi
        jupyter-server            1.13.5                   pypi_0    pypi
        jupyterlab                3.3.2                    pypi_0    pypi
        jupyterlab-pygments       0.1.2                    pypi_0    pypi
        jupyterlab-server         2.11.2                   pypi_0    pypi
        kfp                       1.8.11                   pypi_0    pypi
        kfp-pipeline-spec         0.1.14                   pypi_0    pypi
        kfp-server-api            1.8.1                    pypi_0    pypi
        kfserving                 0.4.1                    pypi_0    pypi
        kubeflow-kale             0.7.0                    pypi_0    pypi
        kubeflow-kale-labextension 0.7.0                     dev_0    <develop>
        kubernetes                10.0.1                   pypi_0    pypi
        ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
        libffi                    3.3                  h58526e2_2    conda-forge
        libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
        libgomp                   11.2.0              h1d223b6_14    conda-forge
        libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
        libzlib                   1.2.11            h36c2ea0_1013    conda-forge
        markupsafe                2.1.1                    pypi_0    pypi
        matplotlib-inline         0.1.3                    pypi_0    pypi
        minio                     7.1.5                    pypi_0    pypi
        mistune                   0.8.4                    pypi_0    pypi
        ml-metadata               0.30.0                   pypi_0    pypi
        nbclassic                 0.3.7                    pypi_0    pypi
        nbclient                  0.5.13                   pypi_0    pypi
        nbconvert                 5.6.1                    pypi_0    pypi
        nbformat                  4.4.0                    pypi_0    pypi
        ncurses                   6.3                  h9c3ff4c_0    conda-forge
        nest-asyncio              1.5.4                    pypi_0    pypi
        networkx                  2.7.1                    pypi_0    pypi
        notebook                  6.4.10                   pypi_0    pypi
        notebook-shim             0.1.0                    pypi_0    pypi
        numpy                     1.22.3                   pypi_0    pypi
        oauthlib                  3.2.0                    pypi_0    pypi
        openssl                   1.1.1l               h7f98852_0    conda-forge
        packaging                 21.3                     pypi_0    pypi
        pandocfilters             1.5.0                    pypi_0    pypi
        parso                     0.8.3                    pypi_0    pypi
        pexpect                   4.8.0                    pypi_0    pypi
        pickleshare               0.7.5                    pypi_0    pypi
        pip                       22.0.4             pyhd8ed1ab_0    conda-forge
        poyo                      0.5.0                    pypi_0    pypi
        progress                  1.6                      pypi_0    pypi
        prometheus-client         0.13.1                   pypi_0    pypi
        prompt-toolkit            3.0.28                   pypi_0    pypi
        protobuf                  3.19.4                   pypi_0    pypi
        psutil                    5.9.0                    pypi_0    pypi
        ptyprocess                0.7.0                    pypi_0    pypi
        pure-eval                 0.2.2                    pypi_0    pypi
        pyasn1                    0.4.8                    pypi_0    pypi
        pyasn1-modules            0.2.8                    pypi_0    pypi
        pycodestyle               2.8.0                    pypi_0    pypi
        pycosat                   0.6.3           py38h497a2fe_1009    conda-forge
        pycparser                 2.21               pyhd8ed1ab_0    conda-forge
        pydantic                  1.9.0                    pypi_0    pypi
        pyflakes                  2.4.0                    pypi_0    pypi
        pygments                  2.11.2                   pypi_0    pypi
        pyjwt                     2.3.0                    pypi_0    pypi
        pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
        pyparsing                 3.0.7                    pypi_0    pypi
        pyrsistent                0.18.1                   pypi_0    pypi
        pysocks                   1.7.1            py38h578d9bd_4    conda-forge
        python                    3.8.10          h49503c6_1_cpython    conda-forge
        python-dateutil           2.8.2                    pypi_0    pypi
        python-slugify            6.1.1                    pypi_0    pypi
        python_abi                3.8                      2_cp38    conda-forge
        pytz                      2022.1                   pypi_0    pypi
        pyyaml                    5.4.1                    pypi_0    pypi
        pyzmq                     22.3.0                   pypi_0    pypi
        readline                  8.1                  h46c0cb4_0    conda-forge
        requests                  2.27.1             pyhd8ed1ab_0    conda-forge
        requests-oauthlib         1.3.1                    pypi_0    pypi
        requests-toolbelt         0.9.1                    pypi_0    pypi
        rsa                       4.8                      pypi_0    pypi
        ruamel_yaml               0.15.80         py38h497a2fe_1006    conda-forge
        send2trash                1.8.0                    pypi_0    pypi
        setuptools                60.10.0          py38h578d9bd_0    conda-forge
        six                       1.15.0                   pypi_0    pypi
        sniffio                   1.2.0                    pypi_0    pypi
        soupsieve                 2.3.1                    pypi_0    pypi
        sqlite                    3.37.1               h4ff8645_0    conda-forge
        stack-data                0.2.0                    pypi_0    pypi
        strip-hints               0.1.10                   pypi_0    pypi
        table-logger              0.3.6                    pypi_0    pypi
        tabulate                  0.8.9                    pypi_0    pypi
        termcolor                 1.1.0                    pypi_0    pypi
        terminado                 0.13.3                   pypi_0    pypi
        testpath                  0.6.0                    pypi_0    pypi
        text-unidecode            1.3                      pypi_0    pypi
        tk                        8.6.12               h27826a3_0    conda-forge
        tomlkit                   0.10.0                   pypi_0    pypi
        tornado                   6.1                      pypi_0    pypi
        tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
        traitlets                 5.1.1                    pypi_0    pypi
        typer                     0.4.0                    pypi_0    pypi
        typing-extensions         3.10.0.2                 pypi_0    pypi
        uritemplate               3.0.1                    pypi_0    pypi
        urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
        wcwidth                   0.2.5                    pypi_0    pypi
        webencodings              0.5.1                    pypi_0    pypi
        websocket-client          1.3.1                    pypi_0    pypi
        wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
        wrapt                     1.14.0                   pypi_0    pypi
        xz                        5.2.5                h516909a_1    conda-forge
        yaml                      0.2.5                h7f98852_2    conda-forge
        zipp                      3.7.0                    pypi_0    pypi
        zlib                      1.2.11            h36c2ea0_1013    conda-forge

conda env:
        name: base
        channels:
          - conda-forge
        dependencies:
          - _libgcc_mutex=0.1=conda_forge
          - _openmp_mutex=4.5=1_gnu
          - brotlipy=0.7.0=py38h497a2fe_1003
          - ca-certificates=2021.10.8=ha878542_0
          - certifi=2021.10.8=py38h578d9bd_1
          - cffi=1.14.6=py38ha65f79e_0
          - charset-normalizer=2.0.12=pyhd8ed1ab_0
          - colorama=0.4.4=pyh9f0ad1d_0
          - conda=4.10.1=py38h578d9bd_0
          - conda-package-handling=1.8.0=py38h0a891b7_0
          - cryptography=36.0.2=py38h2b5fc30_0
          - idna=3.3=pyhd8ed1ab_0
          - ld_impl_linux-64=2.36.1=hea4e1c9_2
          - libffi=3.3=h58526e2_2
          - libgcc-ng=11.2.0=h1d223b6_14
          - libgomp=11.2.0=h1d223b6_14
          - libstdcxx-ng=11.2.0=he4da1e4_14
          - libzlib=1.2.11=h36c2ea0_1013
          - ncurses=6.3=h9c3ff4c_0
          - openssl=1.1.1l=h7f98852_0
          - pip=22.0.4=pyhd8ed1ab_0
          - pycosat=0.6.3=py38h497a2fe_1009
          - pycparser=2.21=pyhd8ed1ab_0
          - pyopenssl=22.0.0=pyhd8ed1ab_0
          - pysocks=1.7.1=py38h578d9bd_4
          - python=3.8.10=h49503c6_1_cpython
          - python_abi=3.8=2_cp38
          - readline=8.1=h46c0cb4_0
          - requests=2.27.1=pyhd8ed1ab_0
          - ruamel_yaml=0.15.80=py38h497a2fe_1006
          - setuptools=60.10.0=py38h578d9bd_0
          - sqlite=3.37.1=h4ff8645_0
          - tk=8.6.12=h27826a3_0
          - tqdm=4.63.0=pyhd8ed1ab_0
          - urllib3=1.26.9=pyhd8ed1ab_0
          - wheel=0.37.1=pyhd8ed1ab_0
          - xz=5.2.5=h516909a_1
          - yaml=0.2.5=h7f98852_2
          - zlib=1.2.11=h36c2ea0_1013
          - pip:
            - absl-py==0.12.0
            - adal==1.2.7
            - anyio==3.5.0
            - argon2-cffi==21.3.0
            - argon2-cffi-bindings==21.2.0
            - argparse==1.4.0
            - arrow==1.2.2
            - astor==0.8.1
            - asttokens==2.0.5
            - attrs==20.3.0
            - autopep8==1.4.4
            - azure-common==1.1.28
            - azure-storage-blob==2.1.0
            - azure-storage-common==2.1.0
            - babel==2.9.1
            - backcall==0.2.0
            - beautifulsoup4==4.10.0
            - binaryornot==0.4.4
            - bleach==4.1.0
            - cachetools==4.2.4
            - chardet==4.0.0
            - click==8.0.4
            - cloudpickle==2.0.0
            - cookiecutter==1.7.3
            - debugpy==1.6.0
            - decorator==5.1.1
            - defusedxml==0.7.1
            - deprecated==1.2.13
            - deprecation==2.1.0
            - dill==0.3.4
            - docstring-parser==0.13
            - entrypoints==0.4
            - executing==0.8.3
            - fire==0.4.0
            - google-api-core==2.7.1
            - google-api-python-client==1.12.11
            - google-auth==1.35.0
            - google-auth-httplib2==0.1.0
            - google-cloud-core==2.2.3
            - google-cloud-storage==1.44.0
            - google-crc32c==1.3.0
            - google-resumable-media==2.3.2
            - googleapis-common-protos==1.56.0
            - grpcio==1.44.0
            - httplib2==0.20.4
            - importlib-resources==5.4.0
            - ipykernel==6.9.2
            - ipython==8.1.1
            - ipython-genutils==0.2.0
            - jedi==0.18.1
            - jinja2==3.0.3
            - jinja2-time==0.2.0
            - json5==0.9.6
            - jsonschema==3.2.0
            - jupyter-client==6.1.12
            - jupyter-core==4.9.2
            - jupyter-packaging==0.12.0
            - jupyter-server==1.13.5
            - jupyterlab==3.3.2
            - jupyterlab-pygments==0.1.2
            - jupyterlab-server==2.11.2
            - kfp==1.8.11
            - kfp-pipeline-spec==0.1.14
            - kfp-server-api==1.8.1
            - kfserving==0.4.1
            - kubeflow-kale==0.7.0
            - kubernetes==10.0.1
            - markupsafe==2.1.1
            - matplotlib-inline==0.1.3
            - minio==7.1.5
            - mistune==0.8.4
            - ml-metadata==0.30.0
            - nbclassic==0.3.7
            - nbclient==0.5.13
            - nbconvert==5.6.1
            - nbformat==4.4.0
            - nest-asyncio==1.5.4
            - networkx==2.7.1
            - notebook==6.4.10
            - notebook-shim==0.1.0
            - numpy==1.22.3
            - oauthlib==3.2.0
            - packaging==21.3
            - pandocfilters==1.5.0
            - parso==0.8.3
            - pexpect==4.8.0
            - pickleshare==0.7.5
            - poyo==0.5.0
            - progress==1.6
            - prometheus-client==0.13.1
            - prompt-toolkit==3.0.28
            - protobuf==3.19.4
            - psutil==5.9.0
            - ptyprocess==0.7.0
            - pure-eval==0.2.2
            - pyasn1==0.4.8
            - pyasn1-modules==0.2.8
            - pycodestyle==2.8.0
            - pydantic==1.9.0
            - pyflakes==2.4.0
            - pygments==2.11.2
            - pyjwt==2.3.0
            - pyparsing==3.0.7
            - pyrsistent==0.18.1
            - python-dateutil==2.8.2
            - python-slugify==6.1.1
            - pytz==2022.1
            - pyyaml==5.4.1
            - pyzmq==22.3.0
            - requests-oauthlib==1.3.1
            - requests-toolbelt==0.9.1
            - rsa==4.8
            - send2trash==1.8.0
            - six==1.15.0
            - sniffio==1.2.0
            - soupsieve==2.3.1
            - stack-data==0.2.0
            - strip-hints==0.1.10
            - table-logger==0.3.6
            - tabulate==0.8.9
            - termcolor==1.1.0
            - terminado==0.13.3
            - testpath==0.6.0
            - text-unidecode==1.3
            - tomlkit==0.10.0
            - tornado==6.1
            - traitlets==5.1.1
            - typer==0.4.0
            - typing-extensions==3.10.0.2
            - uritemplate==3.0.1
            - wcwidth==0.2.5
            - webencodings==0.5.1
            - websocket-client==1.3.1
            - wrapt==1.14.0
            - zipp==3.7.0
        prefix: /opt/conda
</pre>
</details>

**Comment by jweill-aws** [comment]
Triage notes:
1. Please include code snippets as text rather than (or in addition to) marked-up screen shots as this makes it easier to read and search through the text of your issue.
2. Typically, widgets listen to the `mouseDown` event rather than the `onClick` event, although you can override this with the `actualOnClick` parameter in a `Widget`'s props. If you are creating a custom element, you might need to listen to both `mouseDown` and `click`, preventing propagation on either if necessary.

Once you've changed your handler from `mouseUp` as described above, do you still see this behavior?

**Comment by javyxu** [comment]
> 



> Triage notes:
> 
> 1. Please include code snippets as text rather than (or in addition to) marked-up screen shots as this makes it easier to read and search through the text of your issue.
> 2. Typically, widgets listen to the `mouseDown` event rather than the `onClick` event, although you can override this with the `actualOnClick` parameter in a `Widget`'s props. If you are creating a custom element, you might need to listen to both `mouseDown` and `click`, preventing propagation on either if necessary.
> 
> Once you've changed your handler from `mouseUp` as described above, do you still see this behavior?

Hello, Thank you for your reply. 
I have tried mouseDown, but still there is no response. The reason is that I cannot trigger a button click event in NotebookPanel after upgrade the original code in Jupyterlab2.0 to the current code in Jupyterlab3.0
But I tried to use **ReactWidget**. It worked, not R**eact.Component<IProps, IState>**

**Comment by javyxu** [comment]
> Triage notes:
> 
> 1. Please include code snippets as text rather than (or in addition to) marked-up screen shots as this makes it easier to read and search through the text of your issue.
> 2. Typically, widgets listen to the `mouseDown` event rather than the `onClick` event, although you can override this with the `actualOnClick` parameter in a `Widget`'s props. If you are creating a custom element, you might need to listen to both `mouseDown` and `click`, preventing propagation on either if necessary.
> 
> Once you've changed your handler from `mouseUp` as described above, do you still see this behavior?

您好，[kale](https://github.com/javyxu/kale/tree/mu5-jupyterlab3)这是我的所有代码，不知道您可以帮我看一下吗，非常感谢

**Comment by javyxu** [comment]
> Triage notes:
> 
> 1. Please include code snippets as text rather than (or in addition to) marked-up screen shots as this makes it easier to read and search through the text of your issue.
> 2. Typically, widgets listen to the `mouseDown` event rather than the `onClick` event, although you can override this with the `actualOnClick` parameter in a `Widget`'s props. If you are creating a custom element, you might need to listen to both `mouseDown` and `click`, preventing propagation on either if necessary.
> 
> Once you've changed your handler from `mouseUp` as described above, do you still see this behavior?

Hello, [kale](https://github.com/javyxu/kale/tree/mu5-jupyterlab3) these are all my codes. I wonder if you could help me have a look. Thank you very much
