### ISSUE TITLE
Export to html fails with jinja template problem

### ISSUE THREAD

**Issue by notuntoward** [jupyterlab/jupyterlab#12307]
When I try to export a notebook to html, I get the following error message:

> nbconvert failed: module 'jinja2' has no attribute 'Markup'

This might be related to [#9468](https://github.com/microsoft/vscode-jupyter/issues/9468) in vscode.

This is with jupyterlab 3.3.2

**Comment by jweill-aws** [comment]
This is fixed by https://github.com/jupyter-server/jupyter_server/pull/756 . If you run `pip install -U jupyter_server`, you should get a fix for this issue.
