### ISSUE TITLE
Add support for custom.css

### ISSUE THREAD

**Issue by yhslai** [jupyterlab/jupyterlab#12318]
## Description

I'm using Jupyterlab Desktop on Windows. I add a `custom.css` in `%AppData%\Roaming\jupyterlab-desktop\custom\custom.css`, but it doesn't take effect at all.

## Reproduce

1. Create `%AppData%\Roaming\jupyterlab-desktop\custom\custom.css`
2. Add styles

## Expected behavior

Styles are applied to Jupyterlab Desktop.

## Context

- Operating System and version: Windows 10
- JupyterLab-Desktop version: 3.2.5-2

**Comment by jtpio** [comment]
Adding to the `4.1` milestone for consideration.

As discussed in https://github.com/jupyterlab/jupyterlab/issues/8457#issuecomment-1598791146, it could be interesting to have support for loading custom.css in JupyterLab 4.1.

For reference this was implemented in Notebook 7 in https://github.com/jupyter/notebook/pull/6841. Likely there is a good chunk of the code that could be moved to JupyterLab directly.
