### ISSUE TITLE
Context Menu option to open a notebook in simple mode

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#12325]
### Problem

Currently there is no easy method to open a notebook in simple mode (and in a new tab).
### Proposed Solution

Add a context menu option to open a notebook in simple mode (and in a new tab).

**Comment by divyansshhh** [comment]
I would like to work on this and raise a PR.

**Comment by jweill-aws** [comment]
@divyansshhh Thank you for your contribution! This looks like a good improvement for the `filebrowser` package. Please feel free to work on this and reference this issue in your PR. I appreciate your help.

**Comment by jtpio** [comment]
Thanks @divyansshhh!

You might want to have a look at the implementation for "Open in New Browser Tab", which might be similar:

https://github.com/jupyterlab/jupyterlab/blob/ffbb016cd8d072654d00285bf0404cafa627a476/packages/filebrowser-extension/src/index.ts#L625-L670
