### ISSUE TITLE
Visual Regression Documentation CI check is failing

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#12328]
## Description

Similar to the previous time: https://github.com/jupyterlab/jupyterlab/issues/12233

This looks like an issue with items not being sorted in the extension manager:

https://user-images.githubusercontent.com/591645/161276234-31aa75e9-9adb-4ec6-84ff-82759ec2014b.mp4

Thus depending on the order returned from the query to npm.

## Reproduce

Example run: https://github.com/jupyterlab/jupyterlab/runs/5788364548?check_suite_focus=true

## Expected behavior

The tests should pass, and the screenshot should be stable.

## Context

https://github.com/jupyterlab/jupyterlab/issues/12233 and https://github.com/jupyterlab/jupyterlab/pull/12249 for reference.

**Comment by jtpio** [comment]
Probably the fix is to sort the extensions in the extension manager.

**Comment by jtpio** [comment]
> Probably the fix is to sort the extensions in the extension manager.

Looks like this is the related code:

https://github.com/jupyterlab/jupyterlab/blob/eeaa3f395cd755e34045611d3d9cc3947626b822/packages/extensionmanager/src/model.ts#L953-L956

Which depends on the sort from the npm API.

So either we consider this new sort the reference, and we update the snapshots accordingly. Or we ensure our own sorting, for example by name.

**Comment by echarles** [comment]
I also see failure for the ui-test visual regression (not the documentation one, the other), see e.g. my comment on https://github.com/jupyterlab/jupyterlab/pull/12297#issuecomment-1086715618
