### ISSUE TITLE
Check Release is failing on CI

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#12336]
## Description

Looks like the check release CI workflow is now failing.

Which seems related to the new Jupyter Releaser 0.15.0.

## Reproduce

Example run: https://github.com/jupyterlab/jupyterlab/runs/5804918410?check_suite_focus=true

![image](https://user-images.githubusercontent.com/591645/161490109-47019404-8ad2-4eba-9191-d769b1d6a50c.png)

## Expected behavior

This check should pass again before we start making new releases.

## Context

This looks related to this change in the releaser: https://github.com/jupyter-server/jupyter_releaser/pull/279

**Comment by jtpio** [comment]
cc @blink1073 who might know if this is related to the changes in https://github.com/jupyter-server/jupyter_releaser/pull/279

**Comment by blink1073** [comment]
Hmm, yes, it sounds that way.  I'll restore the `setup.py --version` check as primary.

**Comment by blink1073** [comment]
https://github.com/jupyter-server/jupyter_releaser/pull/284

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyter-server/jupyter_releaser/pull/284, thanks @blink1073!
