### ISSUE TITLE
Introduce a transient Code Viewer to core

### ISSUE THREAD

**Issue by ajbozarth** [jupyterlab/jupyterlab#12361]
### Problem

Currently if an extension wants to display code in an editor UI int requires persisting the contents as a file.

### Proposed Solution

I recently published the code viewer extension in Elyra, I purpose merging that implementation in core. This would consist of moving the widget code into the code-editor package and the command declaration code into the file editor extension. 

### Additional context

This feature would allow developers to open transient "files" for viewing without the need to persist them to the file system.

Current code: https://github.com/elyra-ai/elyra/tree/master/packages/code-viewer

This feature was demoed and pitched at the April 6th 2022 dev meeting. During that meeting many potential additions to functionality were purposed that could be handled in followup issues such as:
- Allowing for users to save/persist the transient file (this would require re-opening it in an actual editor)
- Add open viewers to the restorer so they persist on page refresh
- This has a similar functionality as the read-only editor in the debugger, but that requires a persisted file that's just outside the workspace.

**Comment by jtpio** [comment]
Thanks @ajbozarth for this suggestion.

The debugger does something similar to open read-only sources in a main area widget.

The code is available here:

https://github.com/jupyterlab/jupyterlab/blob/5aa5f62678dabcc6bdff0d98b6368652ed7713ee/packages/debugger-extension/src/index.ts#L846-L863

So maybe we could indeed bring the functionality from https://github.com/elyra-ai/elyra/tree/master/packages/code-viewer so it's available to extension authors too. And make the debugger code depend on this new helper.

Would you like to open a draft a PR to start with? Thanks!

**Comment by bollwyvl** [comment]
I think for this to be generally useful it would:
- be restorable (as you've pointed out)
- also offer a model instead of just a string so it can be live updated

I'd also point at the related cases of:

- `notebook:create-output-view` which does this, but for any mime type, and can be restored
  - having an optional text-based view for an output would be handy indeed
- other model-based things like
  - complex JSON objects in settings
  - notebook metadata
    - this would be almost certainly better than the editor in the sidebar
