### ISSUE TITLE
extension-cookiecutter-ts out of sync with doc.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#12388]
https://github.com/jupyterlab/extension-cookiecutter-ts uses `const plugin: JupyterFrontEndPlugin<...` while all the documentation on getting started are using `const extension...` so if anyone copy past, you may get non-working code. As the getting started recommend to us the cookie cutter, it would be nice to have it synced

**Comment by Carreau** [comment]
extension_tutorial seem to also miss the fact that `ICommandPalette` needs to be added to `optional: [ICommandPalette]`.

**Comment by jtpio** [comment]
Closing as the tutorial has recently been updated for JupyterLab 4 and should have addressed these issues: https://jupyterlab.readthedocs.io/en/latest/extension/extension_tutorial.html
