### ISSUE TITLE
Focus not set when clicking on cell margin

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#12437]
## Description

When clicking on a cell margin to select a cell without changing it to edit mode, the keyboard shortcuts don't seem to work for the cell. My guess is that the notebook document is not actually focused (i.e., what should happen in command mode) when clicking on a cell margin.

## Reproduce

1. Create an ipywidgets slider
2. Drag the widgets handle (thereby focusing the slider handle DOM element)
3. Click on the margin of a cell
4. Press "A" to create a cell above. This doesn't work.
5. Click inside the cell, thereby focusing its editor
6. Now click on the margin and the "A" keyboard shortcut works.

![focus](https://user-images.githubusercontent.com/192614/163858264-14db698a-02be-4a37-afdc-8d46dc848fe5.gif)

## Expected behavior

Clicking on the cell margin in command mode focuses the notebook DOM element, which enables keyboard shortcuts for the cell.

## Context

- Operating System and version: macos 12.3.1
- Browser and version: Firefox 99
- JupyterLab version: 3.3.4

**Comment by agoose77** [comment]
I'd run into this before but never realised that this is what's happening :facepalm: 

Thanks for filing!
