### ISSUE TITLE
Add simple option to disable any authentication for specific IPs

### ISSUE THREAD

**Issue by maxima120** [jupyterlab/jupyterlab#12459]
I am coming from this issue: https://github.com/jupyter/notebook/issues/2254

### Problem

as many believe - jupyter is run on single user / clearly defined small set of users 95% of the time. Also people who are in data science are not too concerned with security.

Hence need for something what is easily hackable anyway (token - pfff!) 50 times a day is not helpful.

P.S. Idk abt "dns binding" hack - but if that happen (as I read in the ticket above - its the user problem not Jupyter problem".

### Proposed Solution

Therefore I believe that if you add a command line key or config switch to say IP 192.168.0.100 is safe - then bypass the auth, that would make a whole gazillion of people happier with marginally worse security resistance.

Lets be frank here (we all are friends are we not?) - a lot bigger commercial organisations which pay top dollar to bunch of security analysts struggle to stay unhacked for more than 300 days in a row.. So passing a little token is just a pretend play to create false sense of security (hence the pfff above).

*Just give us a small print saying you are not responsible for any hacks and data loss etc in T&C*

Easy

**Comment by davidbrochart** [comment]
Hi @maxima120,

You can disable any form of authentication by running JupyterLab with the following options, although [it is not recommended](https://jupyter-server.readthedocs.io/en/latest/operators/security.html#alternatives-to-token-authentication):
```bash
jupyter lab --ServerApp.token='' --ServerApp.password=''
```
And if you use [Jupyverse](https://github.com/jupyter-server/jupyverse):
```bash
jupyverse --authenticator.mode=noauth
```

**Comment by maxima120** [comment]
Thank you but I don't want to disable any form of authentication. Only for specific IP(s)

**Comment by maxima120** [comment]
Thank you
