### ISSUE TITLE
Cannot browse any folder named checkpoints

### ISSUE THREAD

**Issue by kirk86** [jupyterlab/jupyterlab#12456]
## Description

Cannot browse any folders named `checkpoints` using the jupyterlab browse pane
<img width="425" alt="image" src="https://user-images.githubusercontent.com/2902390/164804440-b4cb773e-664e-44ef-aef6-83212d05e51b.png">

For instance I can easily double click in the folders `checkthese` and `checkthat` but nothing happens when I do the same on the folder `checkpoints`, btw all folders are empty, they contain absolutely nothing in them.

## Reproduce

In a terminal type the following

1. mkdir jupyterlab_project_error
2. mkdir -p jupyterlab_project_error/first_folder
3. mkdir -p jupyterlab_project_error/second_folder
4. mkdir -p jupyterlab_project_error/checkpoints

Then in jupyterlab navigation pane like the one shown in the screen shot try to navigate each folder `first_folder`, `second_folder`, `checkpoints`.

Probably you'll realise that jupyterlab refuses to enter in the directory checkpoints 

## Expected behavior

Expecting to browse the directory `checkpoints` like any other directory.

## Context

- Operating System and version: Linux Manjaro 21.2.6
- Browser and version: Chrome 100.0.4896.127
- JupyterLab version: 3.3.2

<details><summary>Browser Output</summary>

<pre>
Nothing shows in javascript console

</pre>
</details>

**Comment by krassowski** [comment]
Thanks for opening the issue. Could it be a duplicate of recent #12408?

**Comment by kirk86** [comment]
Oops missed that! I am closing this issue then?
