### ISSUE TITLE
Reconnecting the kernel after a refresh does not capture the kernel output correctly

### ISSUE THREAD

**Issue by Wh1isper** [jupyterlab/jupyterlab#12455]
## Description

As this comment says, despite all our efforts on the RTC, there is still nothing we can do about the kernel output after a refresh：
https://github.com/jupyter/notebook/issues/641#issuecomment-1097473357

I think JupyterLab still has room for improvement in the kernel state loop and state preservation.

## Reproduce

Execute the following code and refresh during execution, open the browser's developer tools and you will see that after reconnecting back to the kernel, the kernel is still outputting, while the front-end is unresponsive and the kernel status is wrong (it shows idle, but it should actually be busy)

```python
import time 
while True:
  time.sleep(1)
  print(1)
```

## Expected behavior

I think there are two areas that need to be addressed

1. correctly display the kernel state according to the kernel state returned by websocket
2. add relevant information to ipynb to recover the output

Unfortunately, I don't know anything about front-end code, so I can only give my **general idea** here

![image](https://user-images.githubusercontent.com/43375501/164625621-05c2e765-6912-4bd0-b6b3-8ffd4cd65d7d.png)

Based on the above state transition diagram, the front-end needs to secure the following tasks.

### 1 Start kernel

- HTTP session interface to query or create a session and get the kernel_id in it

- Use kernel_id and session_id to connect to websocket

- Get the initial kernel state, see 2 Event-triggered kernel state transition

### 2 Event-triggered kernel state transition.

- When the kernel has just been started, it will always be in the starting state and needs to connect to the websocket on the front end, using kernel_info_request, the kernel will process this message and enter the busy-idle loop.

- When the kernel process crashes or accidentally happens, the kernel will be converted to dead mode and try to restart immediately, the restarting process will be in restarting state, when the restarting is finished, it will return to starting state, after the front-end recognizes it, it needs to send kernel_info_request to let it enter the busy-idle loop

- Use kernel_info_request query when you are not sure of the kernel state

### 3 Runtime cell and message binding

- Determine the cell to be run

- Generate websocket msg_id

- store msg_id in cell.metadata.msg_id, clear output, save file to prevent user from refreshing before saving

- send msg_type: "execute_request" command to execute cell content

- The return contents of the write are as follows: 4 Determine cell write when message is received

### 4 Determine cell writes when message is received

- Get the parent_header.msg_id of the channel: "iopub" message

- Look up the corresponding msg_id according to the cell.metadata in the traversal file

- continue writing to the matching cell, otherwise ignore

This may require changing some of the default behavior, such as when to save the file, but I think it's good behavior to help the user save the file while the user is doing code execution, just like the auto-save feature for online document editing.

**There may be a place where the above considerations are not in place, welcome to point out my mistakes.**

**Thank you!**

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by Wh1isper** [comment]
Oh I just realized this could be an Enhancement and not a bug

**Comment by Wh1isper** [comment]
> This would probably need a complete rework of JupyterLab's architecture. Currently, the front-end interacts with kernels (almost) directly, through the low-level kernel protocol. I think it should only send high-level orders, like "execute code" or "interrupt kernel execution", and let the back-end speak to kernels. JupyterLab would merely be a "document viewer", as far as kernel execution results are concerned.

Yes, I agree. I've used DeepNote and that's what they seem to do, but the performance can be poor and the lag is worse

Based on the current JupyterLab architecture, I (and my colleagues) have tried to restore the correspondence between the websocket and the front-end model by storing the execute_request.msg_id in the ipynb file, which I think is a feasible improvement, although it still doesn't solve the problem of closing the page, but is refresh-friendly

**Comment by davidbrochart** [comment]
That can't work in the general case, because multiple clients can access the same notebook, and each one would have a different `msg_id`.

**Comment by Wh1isper** [comment]
> That can't work in the general case, because multiple clients can access the same notebook, and each one would have a different `msg_id`.

Yes, but when there is code running, other clients will also receive messages, probably similar to the current text multiplayer collaboration, where other clients can actively transform the state of the kernel and fill the output of the cell (based on ipynb's content) with the received messages correctly, although this requires saving the notebook immediately after running the code

What I want to achieve is that when refresh or other clients connect to the kernel, the output of the running kernel can be correctly positioned to its cell, based on iopub channel's `parent_header.msg_id`.

**Comment by Wh1isper** [comment]
Jupyter Server Team's planning for this issue：

https://github.com/jupyter/notebook/issues/641#issuecomment-1203590878

**Comment by Zsailer** [comment]
Here are some links to issues I've opened around this topic on the server-side:

* https://github.com/jupyter/jupyter_client/issues/838
* https://github.com/jupyter/jupyter_client/issues/839
* https://github.com/jupyter-server/jupyter_server/issues/989
* https://github.com/jupyter-server/jupyter_server/issues/990

**Comment by Wh1isper** [comment]
Go to: https://github.com/jupyterlab/jupyterlab/pull/15448
