### ISSUE TITLE
pip installation within notebook (inline) much much slower than console

### ISSUE THREAD

**Issue by EMCP** [jupyterlab/jupyterlab#12460]
## Description

I am utilizing jupyterlab via kubeflow installed with juju charms.. so if the issue is not the lab, feel free to turn me away and I can go there.. but when I tried pip installing pyspark inline

```
$pip install pyspark
```
it is extremely extremely slow

![image](https://user-images.githubusercontent.com/3691722/164943634-13eafb43-d11b-4068-84ba-0276ef6a49b2.png)

when I go to install via the terminall.. all goes much faster.. same computer .. roughly same time

![image](https://user-images.githubusercontent.com/3691722/164943647-e210442f-119a-4195-b1e3-1994bc6c42cf.png)

## Reproduce

1. install jupyterlab via `juju deploy kubeflow -- trust`

see https://charmed-kubeflow.io/docs/install

2. once logged in, fire up a new notebook with jupyterlab (in my case it was some pytorch cuda image.. if it matters I can grab the exact image name)

## Expected behavior

shouldn't inline pip installs perform just as quick as the terminal? 

## Context

- Operating System and version: Kubuntu 20.04
- Browser and version: Firefox
- JupyterLab version: 3.0.16

**Comment by agoose77** [comment]
This is *probably* constrained by the amount of output that pip is generating. Is it faster if you use `--quiet`?

**Comment by krassowski** [comment]
Also, this looks like an old pip version. Have you tried upgrading pip with `pip install -U pip`? What is the performance when using `!pip` instead of `%pip`?

**Comment by EMCP** [comment]
> Also, this looks like an old pip version. Have you tried upgrading pip with `pip install -U pip`? What is the performance when using `!pip` instead of `%pip`?

`!pip install tensorflow` worked like a charm

I then tried `%pip install pyspark` .. all seems super fast.. so I am closing this for now but.. perhaps I just got unlucky in the notebook
