### ISSUE TITLE
Acknowledge omit_sections as a key in InspectRequestMsg

### ISSUE THREAD

**Issue by fasiha** [jupyterlab/jupyterlab#12489]
### Problem

- Ipykernel 6.6 and on accept an `omit_sections` key in inspect request messages: https://github.com/ipython/ipykernel/pull/809. This allows clients like JupyterLab to customize what they want from `info` and `inspect` messages.
- It would be nice to have this explicitly supported in JupyterLab's TypeScript interface.

### Proposed Solution

I am happy to open a PR to address this—it'll be a single line:
```patch
diff --git a/packages/services/src/kernel/messages.ts b/packages/services/src/kernel/messages.ts
index c998782977..7693a1c8b3 100644
--- a/packages/services/src/kernel/messages.ts
+++ b/packages/services/src/kernel/messages.ts
@@ -837,6 +837,7 @@ export interface IInspectRequestMsg extends IShellMessage<'inspect_request'> {
     code: string;
     cursor_pos: number;
     detail_level: 0 | 1;
+    omit_sections?: string[];
   };
 }
 
```

### Additional context

This was merged into [ipykernel](https://github.com/ipython/ipykernel/pull/809) (and ipython for ultimate support, in https://github.com/ipython/ipython/pull/13343) without much discussion about support for non-Python kernels, so I do have a question: would something like this need to be explicitly added to the [Jupyter messaging spec](https://jupyter-client.readthedocs.io/en/latest/messaging.html#introspection) before it's added to JupyterLab, to avoid Python-centricity?

**Comment by martinRenou** [comment]
This seems to be something very specific to ipykernel? This `omit_sections` entry is not part of the kernel protocol: https://jupyter-client.readthedocs.io/en/stable/messaging.html#introspection.

A proposal should probably be opened in https://github.com/jupyter/enhancement-proposals/issues suggesting to add this entry in the protocol.

**Comment by jweill-aws** [comment]
I'm going to close this issue for now because the discussion should happen in a new Jupyter Enhancement Proposal (JEP), as @martinRenou suggested above. If the JEP is accepted, please reopen this issue and open a pull request as you suggested.
