### ISSUE TITLE
Download data from a Notebook server?

### ISSUE THREAD

**Issue by bbartling** [jupyterlab/jupyterlab#12484]
If I am running a [ notebook server](https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#running-a-notebook-server) for data analyst's to connect to Juypter notebook hosted on a LAN remote Ubuntu instance is there a way for the data analyst do typical data wrangling in Pandas and then download the CSV to their local machine they are browsing in from?

`pandas.to_csv()` to the machine they are browsing in from........ Or can a notebook server serve a static file like a web server of the CSV file?

**Comment by jweill-aws** [comment]
Thanks for your question! If your server is on your local machine, the output CSV is already on your local file system. If your server is running remotely, you can save your output CSV and use the file browser's "download" function to get a copy of your output. I wouldn't expect Jupyter Server to serve static assets like CSV.

If you have any other questions, please either reopen this issue or open a new one in https://github.com/jupyter-server/jupyter_server . Thanks again!

**Comment by bbartling** [comment]
Hi would you have any tips for how to do that with Python and pandas if the Jupyter server is remote? 

For example if I was browsing into a remote Jupyter lab server to do some data wrangling, I know how to use Pandas to save a CSV file to a directory on the remote server but how would you then use the browser to download the file to my local machine? If that an IPython feature or any browser functionality?

**Comment by jweill-aws** [comment]
If you have a file saved on the remote server, you can find it in the file browser, right-click, and choose "Download" to download it:

![image](https://user-images.githubusercontent.com/93281816/167019241-ab6b6568-4b45-40a2-b465-6bdd862353bf.png)

I checked in dev tools and found that the URL that my browser requests after I click "Download" has the file path and a special XSRF token: `http://localhost:8888/files/Untitled.ipynb?_xsrf=2%7C62d0a507%7C3c1e81a24b24f204a0513a7ed7ff11ee%7C1649284786`. If you wanted to automate downloading, you'd have to generate a compatible token yourself.

As an alternative, I've seen this approach, which generates a CSV file and transmits it to the user via a `data` URL: https://gist.github.com/HaiyangXu/244ae64d93c9142197791014f2a92503 . Note that for larger CSVs, the `data` URL may be too long to be practical.
