### ISSUE TITLE
`maxNumberOutputs` breaks interactive cell outputs

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#12497]
## Description

this issue is a superset of #12321

There is a (critical?) bug in the current implementation of `maxNumberOutputs` (a user setting from `notebook-extension`) that breaks ipdb functionality by default for our whole user base. The bug will also affect any other situation in which output is added iteratively to an `OutputArea`.

When the output limit is reached for a given cell, a warning message is displayed instead of further outputs. Currently, clicking on the warning message will remove the warning and flush all outputs that had been queued *up to that specific that point in time*. If further outputs are generated afterwards, as in the ipdb use-case, none of them will be displayed.

## Reproduce

See #12321 for a repro case (@mlucool)

## Expected behavior

`maxNumberOutputs` should either:

  a) behave in a paginated way. Once `maxNumberOutputs` of outputs are shown, display the warning. If the warning is clicked, show up to `maxNumberOutputs * 2` outputs before displaying a new warning. If that warning is clicked, keep going until `maxNumberOutputs * 3`, and so forth

  b) behave as a one-time flood control. Once `maxNumberOutputs` of outputs are shown, display the warning. If the warning is clicked, show all further outputs

Currently I'm leaning towards b) as the correct behavior. It may still cause performance hiccups, but at least in that case said hiccup will be caused directly by a user's input/explicit request.

## Context

The `maxNumberOutputs` machinery is currently implemented in two functions:

https://github.com/jupyterlab/jupyterlab/blob/12c5ed914d6336d1f72fc8f71ec98fcffb0aa57f/packages/outputarea/src/widget.ts#L426-L469

https://github.com/jupyterlab/jupyterlab/blob/12c5ed914d6336d1f72fc8f71ec98fcffb0aa57f/packages/outputarea/src/widget.ts#L488-L499

**Comment by fcollonval** [comment]
I'm working on the rebase
