### ISSUE TITLE
exiting an interactive ipdb session always raises/prints into cell output an unhandled `BdbQuit` exception

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#12501]
## Description

Currently no matter what, if you start an interactive ipdb session, when you exit it an unhandled `BdbQuit` exception occurs. 

## Reproduce

Add a `breakpoint()` to any code cell, run it, then type "exit" and hit enter in the resulting `<input>` element:

![image](https://user-images.githubusercontent.com/2263641/166187232-4e0bd8e7-c2a6-4b86-91dd-91c33f9eb71e.png)

## Expected behavior

It should be possible to cleanly exit an interative ipdb session under the majority of circumstances

## Context

IPython itself does have a `BdbQuit_excepthook` function that seems to have been what as supposed to handle this, but currently it's deprecated and apparently does nothing:

https://github.com/ipython/ipython/blob/master/IPython/core/debugger.py#L141-L155

**Comment by ccordoba12** [comment]
This traceback needs to be catched and skipped in IPykernel. This is what we did in Spyder for that: https://github.com/spyder-ide/spyder-kernels/pull/336 (`_showtraceback` is the method used in IPython to show tracebacks).

**Comment by telamonian** [comment]
@ccordoba12 Blanking all `BdbQuit` tracebacks is a nice and simple approach. I think a similar approach could be upstreamed reasonably cleanly to `InteractiveShell` in `IPython.core.interactiveshell`. This approach raises a fundamental question, tho. Is it more appropriate to:

A) catch and ignore the useless `BdbQuit` exception on the backend
B) blank the associated traceback on the backend
C) blank the associated traceback on the frontend

Information about what exactly `BdbQuit` is for and what it's meant to do is pretty thin, so it's hard to know what's best

**Comment by telamonian** [comment]
I spent a while digging through related issues in the ipython github org. There's like, 10 years worth of them:

ipython/ipython#876
ipython/ipython#1273
ipython/ipython#4474
ipython/ipython#5306
ipython/ipython#9731
ipython/ipython#9942
ipython/ipython#9950
ipython/ipython#10006
ipython/ipython#12378

The code comments in [`Lib/bdb.py`](https://github.com/python/cpython/blob/main/Lib/bdb.py) from the cpython stdlib are also somewhat informative.

Okay, so to the best of my understanding the purpose of `BdbQuit` is for situation like these:

```python
def loop():
    for i in x:
        for j in y:
            breakpoint()
            print(i*j)
```

In other words, if a user puts `breakpoint` or `set_trace` inside a loop, or multiple loops, they probably don't actually want to inspect the breakpoint for each one of 1e4 iterations, and they definitely don't want to have to press `c` 1e4 times just to exit the debugger. By raising a debugger-specific exception like `BdbQuit` when you request `exit`, `(i)pdb` is able to break out of any arbitrary looping/nesting directly. Unless, of course,  the user does something truly pathological such as catching `BdbQuit` within their own code...

Thus, catching and handling `BdbQuit` is the responsibility of the "enclosing" program. So it seems like it would make the most sense to just `try: ... except bdb.BdbQuit: pass` somewhere in `ipython`'s cell execution code. There did used to be just such `BdbQuit` handling code in `ipython`'s version of `set_trace`. However, that broke the use case described in ipython/ipython#9942, where the user wanted to be able to run the `ipython` debugger at top level as `__main__`:

```bash
python -m IPython.terminal.debugger testDebug.py
```

so there's definitely some caveats

**Comment by telamonian** [comment]
I have a PR up for this now at ipython/ipython#13668. For now, at least, I decided on option

> A) catch and ignore the useless `BdbQuit` exception on the backend

I think overall this is the most correct way to handle `BdbQuit`. The role of `BdbQuit` is to jump out of any remaining user code/breakpoint requests once an `exit` cmd has been issued. Once that has happened, the outer program that contains the ipdb session (ie ipython) should cleanup/finalize said session and then prevent the `BdbQuit` from bubbling any further up the stack
