### ISSUE TITLE
Use JupyterLab packages in node

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#12518]
### Problem

I would like to use JupyterLab packages in node. But if I run node with the following file (after installing `@jupyterlab/shared-models` with `npm`):
```js
import { YNotebook } from '@jupyterlab/shared-models'
```
I get:
```
(node:151939) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/david/github/davidbrochart/jupyter_ydoc/tests/foo.js:1
import { YNotebook } from '@jupyterlab/shared-models'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```
If I add `"type": "module"` in `package.json`, I get:
```
import { YNotebook } from '@jupyterlab/shared-models'
         ^^^^^^^^^
SyntaxError: Named export 'YNotebook' not found. The requested module '@jupyterlab/shared-models' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@jupyterlab/shared-models';
const { YNotebook } = pkg;
```
If I change the file with:
```js
import pkg from '@jupyterlab/shared-models'
```
I get:
```
(node:151807) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/david/github/davidbrochart/jupyter_ydoc/tests/node_modules/@jupyterlab/shared-models/lib/index.js:9
export * from './api';
^^^^^^

SyntaxError: Unexpected token 'export'
```
If I add `"type": "module"` in `node_modules/@jupyterlab/shared-models/package.json`, I get:
```
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/david/github/davidbrochart/jupyter_ydoc/tests/node_modules/@jupyterlab/shared-models/lib/api' imported from /home/david/github/davidbrochart/jupyter_ydoc/tests/node_modules/@jupyterlab/shared-models/lib/index.js
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:405:11)
    at moduleResolve (node:internal/modules/esm/resolve:964:10)
    at defaultResolve (node:internal/modules/esm/resolve:1173:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:604:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
If I change `node_modules/@jupyterlab/shared-models/lib/index.js` to the following (adding `.js`):
```js
export * from './api.js';
export * from './ymodels.js';
export * from './utils.js';
```
I get:
```
import pkg from '@jupyterlab/shared-models'
       ^^^
SyntaxError: The requested module '@jupyterlab/shared-models' does not provide an export named 'default'
```
If I change back to:
```js
import { YNotebook } from '@jupyterlab/shared-models'
```
It works!

### Proposed Solution

It looks like the needed changes were:
- add `"type": "module"` to each package's `package.json`
- add `.js` to every `export * from './x';`

But I don't know what I'm doing :smile:

**Comment by jtpio** [comment]
For reference this should work out of the box with Bun, a new JavaScript runtime which was recently a few months ago: https://bun.sh/

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/c47de5c7-98ea-48d6-883c-41b69a41aadc)

**Comment by Falven** [comment]
> For reference this should work out of the box with Bun, a new JavaScript runtime which was recently a few months ago: https://bun.sh/
> 
> ![image](https://private-user-images.githubusercontent.com/591645/287509333-c47de5c7-98ea-48d6-883c-41b69a41aadc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzE0MTMsIm5iZiI6MTcwMjI3MTExMywicGF0aCI6Ii81OTE2NDUvMjg3NTA5MzMzLWM0N2RlNWM3LTk4ZWEtNDhkNi04ODNjLTQxYjY5YTQxYWFkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQwNTA1MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2Q4OGNhZGMzNDM1ZDc0Y2M3ZTkxZmE3YzJlY2MyMWUxY2Q2OTBkODUwOGRhMmI3M2EwNzRhY2IwY2JkNTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kadlQGtfiNmll6_jITtqxn79jf0oQWrD1Z16kqgmlnU)

Good observation, but bun is far from stable for production use.
Additionally, all of these modules should be properlyconfigured as ESModules.
