### ISSUE TITLE
Problem in identification of non-active JupyterLab kernels

### ISSUE THREAD

**Issue by bmll-henri** [jupyterlab/jupyterlab#12530]
## Description

We have a near identical situation to the one described here: https://discourse.jupyter.org/t/problem-in-identification-of-non-active-jupytelab-kernels/10797

We provision EC2 instances for our users and they can specify that their instance is shut down after X hours of idle time. To do this we query `/api/kernels` every 15 minutes and check if any kernels have `execution_state=busy`. If none of the kernels are busy then we compare the `last_activity` timestamps with now and the idle timeout they requested. If they have been idle for over the requested amount we terminate the instance.

This works most of the time however we have had a few situations where customers have reported they had idle notebooks but they were never terminated. An example being:

```
{
    "asctime": "2022-04-24 09:30:19,159",
    "message": "kernels_stats: [{'id': 'cca27982-9979-433c-b198-02542bc8415a', 'name': 'python3', 'last_activity': '2022-04-22T16:48:15.097472Z', 'execution_state': 'idle', 'connections': 0}, {'id': '4d8f1aa0-48ab-403e-91e4-a2007eac114c', 'name': 'python3', 'last_activity': '2022-04-22T16:47:59.291154Z', 'execution_state': 'busy', 'connections': 0}, {'id': '145ad2a1-dd8b-45f5-9dd3-ae9ac2fa98be', 'name': 'python3', 'last_activity': '2022-04-22T16:48:14.718935Z', 'execution_state': 'idle', 'connections': 0}, {'id': '223fa1ef-722b-4ef9-beef-e439d57bf723', 'name': 'python3', 'last_activity': '2022-04-22T16:48:24.445497Z', 'execution_state': 'idle', 'connections': 0}]",
}
```

Which shows one kernel being reported as busy but the last activity being `2022-04-22T16:47:59.291154Z` where the log message was from `2022-04-24 09:30:19,159`.

## Reproduce

I cannot find the exact steps to reproduce this as it seems to occur only on a few instances.

## Expected behavior

I expect kernels to be reported as idle when not busy.

## Context

- Operating System and version:  ubuntu:focal (docker image)
- Browser and version: 
- JupyterLab version:  1.2.21

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

If this is a known issue, I would like to know if there are any other statistics we could use to help detect when a kernel is idle.

**Comment by jweill-aws** [comment]
Hi Henri,

Thank you for your report! It looks like you're using a very old version of JupyterLab. The current newest version is 3.4.0 and 4.0 is currently in development. Do you see this same behavior with newer versions of JupyterLab?

Jason

**Comment by bmll-henri** [comment]
Hi @jweill-aws,

We don't know very much about the occurrences but have had reports of customers who believe their kernels were idle and not being terminated (which would be because it isn't idle on the api results). Although there is a possibility that they just had not realised there was some long-running code.

Were there any reports of kernel activity being misreported by the api in older versions such as 1.2.21 that we are using?

Upgrading to 3 is in our roadmap but it's proven to not be so simple with some of the tools we use.
