### ISSUE TITLE
Proper activation of conda env when working with kernels

### ISSUE THREAD

**Issue by Greedquest** [jupyterlab/jupyterlab#12544]
#### Context

A good* way to install jupyterlab under conda is to keep it isolated in its own environment:

```
conda create --name jup jupyterlab
```

You can still run code from other conda environments using `ipykernels`  (or `nb_conda_kernels`):

```
conda create --name py310 python=3.10 ipykernels
conda activate py310
python -m ipykernel install --user --name py310
```

Then jupyterlab, even though it is installed in an isolated _"jup"_ environment, can still execute cells in a notebook using another environment:
![image](https://user-images.githubusercontent.com/25348920/167268440-d5eb4da1-213c-4b21-8b26-df2c4945fdcd.png)

It's a bit like running `conda activate py310` before executing each cell...

#### Issue

However `conda activate` also sets the PYTHONPATH and other environment variables. This behaviour is essential for some packages like numpy c extensions (see #9338).

### Proposed Solution

A special treatment of conda to allow the environment to be activated, or at least run the important bits of the activate script when the kernel is switched in a notebook/ a new console is created.

### Additional context

*At the moment the workaround is to `conda install jupyterlab` to the env with numpy, however this gets rid of some of the nice features of conda envs (isolate jupyterlab from other packages so it can be updated without conflicts, only one copy of relatively large jupyterlab installation, quick switching of different conda envs from within a notebook etc...)

**Comment by fcollonval** [comment]
From a code infrastructure point of view: the kernels set up and handling is not the responsibility of user interfaces. It needs to be set up by the kernel package or the kernel package manager.

From a user point of view: when dealing with conda environment, you should use `nb_conda_kernels` but not install explicitly the kernel (with python -m ipykernel install).
