### ISSUE TITLE
Enable server stop or restart from UI without Ctr-C in console

### ISSUE THREAD

**Issue by GadgetSteve** [jupyterlab/jupyterlab#1255]
Currently in jupyterlab _& jupyter for that matter_ the only ways to shutdown &/or restart the server is to go to the terminal window that it was started from and Control-C out of the server session or to use tools like ps and kill to get the server PID and stop it. This seems a little primitive and not user friendly it also relies on the user iterating through sessions to ensure that thy are all saved browser interface or risk loosing data.

If the server is started on startup then there may not even be a user accessible terminal/command window to do this.

I would like to suggest adding a (possibly optional) menu item for __server__ shutdown in the top level view. This should probably display a dialog giving options for:

 - Server Halt or Restart _assuming that a mechanism for implementing the latter can be found for each package,_
 - Wait For/Until a specified delay or at a scheduled time 
 - possibly automatically when there are no running kernels - in this it might be an idea to either forbid new kernels being started or issue a warning on any new kernels - _I specifically like the idea of this being combined with the delay/scheduled time so that if there are no kernels running at any point earlier there are no kernels running the restart happens automatically_
 - Display Message _to notify remote users that the server is going down_ this customised message should pop up in each kernel and give the users a chance to save session, _it would be a very good idea if the shutdown time were timezone aware_ 
 - Force Save Sessions,
 - Possibly a password to ensure that the user is authorised to do this _maybe optional if the requesting session is on local host_,
 - It would be really nice if the same notification mechanism could be used to notify users when the server host is shutting down/restarting!
 - It would be nice if the same session offered an option to check for and select available upgrades before Restart and to Install them before the restart takes place but I think that should be a separate ticket.

**Comment by blink1073** [comment]
Hi @GadgetSteve, thank you for the detailed request.  This is definitely something we should discuss and consider for the 1.0. release.

**Comment by ellisonbg** [comment]
I think this is probably beyond the 1.0 scope and may require significant changes to the server to properly support this. Changing to backlog for now

**Comment by jweill-aws** [comment]
Closing now that we have Shut Down on the File menu in JupyterLab (but not Restart).
