### ISSUE TITLE
The advanced settings editor seems to not be displayed the default context menu entries correctly

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#12566]
I noticed the advanced settings editor seems to not be displayed the default context menu entries correctly:

![image](https://user-images.githubusercontent.com/591645/168021166-f6da75e5-b71a-4a1c-beca-9216be3f231a.png)

_Originally posted by @jtpio in https://github.com/jupyterlab/jupyterlab/issues/12532#issuecomment-1124655940_

**Comment by krassowski** [comment]
This was fixed by https://github.com/jupyterlab/jupyterlab/pull/15639
