### ISSUE TITLE
Render local file with whitespace in the name in Markdown cells fails

### ISSUE THREAD

**Issue by rgaiacs** [jupyterlab/jupyterlab#12561]
## Description

Markdown cells with image embedding instructions does **not** work if filename has whitespace.

![Screenshot 2022-05-12 at 13-39-18 Untitled ipynb (12) - JupyterLab](https://user-images.githubusercontent.com/1506457/167999595-41ec0d5d-9d7b-4501-92df-50266a37e386.png)

## Reproduce

1. Run `wget https://jupyter-notebook.readthedocs.io/en/stable/_images/python_logo.svg -O "python logo.svg"` to get the sample image.
2. Open a new Jupyter Notebook with JupyterLab (3.4.0)
4. Create a Markdown cell with `![](python logo.svg)` and render it.

## Expected behavior

Image is render.

## Context

- Operating System and version: Linux Ubuntu 21.10
- Browser and version: Firefox 100.0
- JupyterLab version: 3.4.0

**Comment by jweill-aws** [comment]
[This StackOverflow thread](https://stackoverflow.com/questions/62828966/how-to-escape-spaces-in-filename-when-including-image-in-markdown) suggests using `%20` for spaces, e.g., `python%20logo.png`. If that doesn't work, does quoting the filename (e.g., `"python logo.png"`) work?

**Comment by rgaiacs** [comment]
@jweill-aws Thanks for the reply and the work around. Unfortunately, bug compromises the first experience of a non tech-savvy user as many other tools does **not** require the filename to be escaped by using `%20`. For example, Pandoc:

```
$ pandoc --from markdown --to html <<EOF
> ![](python logo.svg)
> EOF
<p><img src="python%20logo.svg" /></p>
```

And Jupyter's nbconvert also works without the escape:

```
$ cat mwe.ipynb 
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "cc525ba4-7ec8-412d-9086-f79767d26551",
   "metadata": {},
   "source": [
    "![](python logo.svg)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:first-carpal]",
   "language": "python",
   "name": "conda-env-first-carpal-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
$ jupyter nbconvert --to html mwe.ipynb 
[NbConvertApp] WARNING | Config option `kernel_spec_manager_class` not recognized by `NbConvertApp`.
[NbConvertApp] Converting notebook mwe.ipynb to html
[NbConvertApp] Writing 573929 bytes to mwe.html
$ grep "logo.svg" mwe.html 
<p><img src="python logo.svg" alt=""></p>
```

I would love to contribute with a pull request but I don't know where the Markdown parser is.

**Comment by rgaiacs** [comment]
> It looks like different Markdown parsers handle spaces differently.

[Original Markdown](https://daringfireball.net/projects/markdown/dingus) (by John Gruber and Aaron Swartz) allows space in the file names: `![](python logo.svg)` is converted to `<p>!<a href="python logo.svg"></a></p>`.

[CommonMark](https://commonmark.org/) does **not** allow space in the file names: `![](python logo.svg)` is converted to `![](python logo.svg)`. This is part of their specification:

> A [link destination](https://spec.commonmark.org/0.18/#link-destination) consists of either
> 
> - a sequence of zero or more characters between an opening < and a closing > that contains no line breaks or unescaped < or > characters, or
> 
> - a nonempty sequence of characters that does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses that is not itself inside a balanced pair of unescaped paretheses.

Regarding open a bug upstream, it is not a bug given that marked implements CommonMark. marked supports three "markdown flavors": pedantic/original markdown.pl, CommonMark, and GitHub.

My understanding is that JupyterLab team is adopting CommonMark. Can JupyterLab use CommonMark instead of Markdown in the UI and documentation? It will clarify things.

**Comment by jweill-aws** [comment]
There has been an issue open on the topic of adopting CommonMark, opened in 2016 but still discussed as of earlier this year: #272. Closing this issue in favor of the older one.
