### ISSUE TITLE
Debugger render variable does not always work

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12568]
## Description

Rich variables do not always render in the debugger. Sometimes I get a blank area and sometimes I get "The variable is undefined in the active context.". I have also seen it incorrectly render the class name/reference of a variable instead of using its repr (e.g. `<__main__.MyClass at...12cd988d0>`). I have been unable to reliably reproduce the last case.

(May or may not be a repeat of https://github.com/jupyterlab/jupyterlab/issues/12286)
## Reproduce

https://user-images.githubusercontent.com/1813603/168134254-7fff0052-8eb6-446c-9a73-d1013c15dd7d.mov

## Expected behavior

The table renders

## Context
JupyterLab: 3.4.1

**Comment by davidbrochart** [comment]
This should be fixed in https://github.com/ipython/ipykernel/pull/943.

**Comment by SylvainCorlay** [comment]
Closing as fixed.
