### ISSUE TITLE
can't show ipywidgets after i update jupyterlab from notebook

### ISSUE THREAD

**Issue by deadseason** [jupyterlab/jupyterlab#12580]
## Description

run the code:

```
import ipywidgets as widgets	
from IPython.display import display	
text = widgets.Text()
display(text)
 
def print_value(sender):
    print(sender.value)
 
text.on_submit(print_value)
```

this is the result:
Text(value='')
no render ,no widget shows
![image](https://user-images.githubusercontent.com/55622830/168299532-c5eaef48-baff-4967-9bc3-92cd3b4f8460.png)

## Reproduce

someone said use this command:
jupyter nbextension enable --py --sys-prefix widgetsnbextension
but it does not work

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Exception ignored in: <function Application.__del__ at 0x7fc69df0>
Traceback (most recent call last):
ValueError: Unable to configure formatter 'console'

when i use lab, I have uninstall nbextensions,is it the key point?

## Context

- Operating System and version:  Linux Ubuntu 21.04 
- Browser and version:  Chrome 96
widgetsnbextension                 3.5.1
nb-conda-kernels                   2.3.1
nbclassic                          0.2.6
nbclient                           0.5.0
nbconvert                          6.0.7
nbformat                           5.0.7
![image](https://user-images.githubusercontent.com/55622830/168299317-59a08a0a-fc41-4a8f-954e-211e1df8d602.png)

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by afshin** [comment]
Since you're running JupyterLab 2.x there are two ways to resolve this:

1. Install a newer version of JupyterLab along with widgets:
    ```
    pip uninstall jupyterlab ipywidgets
    pip install jupyterlab
    pip install ipywidgets
    ```
    Your notebook should work as is if you run `jupyter lab` after these installs.
2. If you *must* use JupyterLab 2.x, then you need an additional line to get widgets working.
    ```
    pip uninstall ipywidgets
    pip install ipywidgets
    jupyter labextension install @jupyter-widgets/jupyterlab-manager
    ```
    Your notebook should work as is if you run `jupyter lab` after these installs.

If neither of these solutions works for you, please feel free to re-open the issue. Thank you and good luck! @deadseason
