### ISSUE TITLE
Kernel name mismatch bug between the status bar and in-notebook kernel indicator

### ISSUE THREAD

**Issue by yozaydin** [jupyterlab/jupyterlab#12592]
## Description

Kernel names in status bar and the one in notebook don't match after selecting a kernel in one notebook and switching to the other one right after.

![Bug](https://user-images.githubusercontent.com/86684237/168883516-cac4c0c4-f860-43c7-89fd-eeafa156ed9d.gif)

## Reproduce

1- Open 2 notebooks
2- Select kernels on both notebooks
3- Switch the kernel on one of them 
4- Switch to the other notebook right after
5- Wait until the status bar updates to show the other notebook's kernel.

## Expected behavior

I would expect the status bar to show the same kernel name as the one in notebook panel.

## Context

- Operating System and version: Linux
- Browser and version: Chrome 101
- JupyterLab version: 3.3

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by ivan-afonichkin** [comment]
I would like to work on this issue. :)

**Comment by ivan-afonichkin** [comment]
Tried to work on this issue, wasn't able to reproduce, because kernels switch too quickly. Seems to be most probably due to the asynchronous nature of the signal.

**Comment by vidartf** [comment]
I looked at this with @ivan-afonichkin what we notice in the screencapture in the original issue is that neither the statusbar or the Notebook toolbar indicator changes the kernel name after selecting the other kernel. Is the kernel startup slow? It might be that the status bar waits for the kernel startup to complete before updating, and that this should be cancelled once the tab changes.
