### ISSUE TITLE
Browser incompatibility for CSS Variables

### ISSUE THREAD

**Issue by krvkir** [jupyterlab/jupyterlab#1259]
# Summary
TODO: Update docs to indicate we need Chrome >= 49 or Firefox (>=?) while we have CSS variables

---
# Original description
After upgrading jupyterlab from 0.2 to any version starting from 0.3 I encounter this problem:

![2016-11-18-jupyterlab](https://cloud.githubusercontent.com/assets/4031219/20432768/c12abc88-adb1-11e6-9b5f-e9a128247f7a.PNG)

Please give me some advice why this might be happening or where to start looking for the cause.

**Comment by blink1073** [comment]
Hi @krvkir, what browser and operating system are you using?

**Comment by krvkir** [comment]
I'm running JupyterHub on Arch Linux server and connecting it from Windows 7 machine with Google Chrome.

**Comment by blink1073** [comment]
It looks like the css files are not showing up, are there any errors in the Chrome JavaScript console?

**Comment by krvkir** [comment]
No, there are no errors. Actually there's no messages in the console, in contrast to Firefox where everything is ok and there's a lot of messages.

It seems that styles file (`main.css`) is loaded correctly (at least I can see it in resources tab).

**Comment by blink1073** [comment]
It looks like `extensions.css` is not loading.  Is it listed in the resources tab?   If not, can you check for its existence on the JupyterHub install?  It would be in the directory found as `import jupyterlab;  jupyterlab.__path__` under `build/extensions.css`.

**Comment by krvkir** [comment]
You're right, it's not listed in the resources tab, and it doesn't exist in `build` dir. There's only one css file (`main.css`) in this dir.

**Comment by blink1073** [comment]
Hmm, what steps did you use to install Jupyterlab on the server?

**Comment by krvkir** [comment]
I simply installed it from `pip` globally: 
`$ sudo pip install --upgrade jupyterlab`

I haven't installed it in `$HOME/.local` and I don't run JupyterHub in virtualenv.
In case it helps - there's output of `locate` after uninstalling and reinstalling jupyterlab:
```
$ locate jupyterlab
/home/kkrasnoschekov/Documents/2016-11-18-jupyterlab.PNG
/usr/lib/python3.5/site-packages/jupyterlab
/usr/lib/python3.5/site-packages/jupyterlab-0.10.0.dist-info
/usr/lib/python3.5/site-packages/jupyterlab/__init__.py
/usr/lib/python3.5/site-packages/jupyterlab/__pycache__
/usr/lib/python3.5/site-packages/jupyterlab/_version.py
/usr/lib/python3.5/site-packages/jupyterlab/build
/usr/lib/python3.5/site-packages/jupyterlab/lab.html
/usr/lib/python3.5/site-packages/jupyterlab/labapp.py
/usr/lib/python3.5/site-packages/jupyterlab/labextensions.py
/usr/lib/python3.5/site-packages/jupyterlab/semver.py
/usr/lib/python3.5/site-packages/jupyterlab/__pycache__/__init__.cpython-35.pyc
/usr/lib/python3.5/site-packages/jupyterlab/__pycache__/_version.cpython-35.pyc
/usr/lib/python3.5/site-packages/jupyterlab/__pycache__/labapp.cpython-35.pyc
/usr/lib/python3.5/site-packages/jupyterlab/__pycache__/labextensions.cpython-35.pyc
/usr/lib/python3.5/site-packages/jupyterlab/__pycache__/semver.cpython-35.pyc
/usr/lib/python3.5/site-packages/jupyterlab/build/0662c22d4e544cecf2bc66ee4c761ed6.svg
/usr/lib/python3.5/site-packages/jupyterlab/build/1.1.bundle.js
/usr/lib/python3.5/site-packages/jupyterlab/build/1.1.bundle.js.manifest
/usr/lib/python3.5/site-packages/jupyterlab/build/1dc35d25e61d819a9c357074014867ab.ttf
/usr/lib/python3.5/site-packages/jupyterlab/build/25a32416abee198dd821b0b17a198a8f.eot
/usr/lib/python3.5/site-packages/jupyterlab/build/26a0370f727f4667dfbf94b8ec576dc4.svg
/usr/lib/python3.5/site-packages/jupyterlab/build/28f2f5e6ac027acb7fbd41f7e02ebf90.gif
/usr/lib/python3.5/site-packages/jupyterlab/build/2b609d364e2e1d67ba33a81c58d9eb8a.svg
/usr/lib/python3.5/site-packages/jupyterlab/build/5e9fca8da62c2b939b204d8883012664.gif
/usr/lib/python3.5/site-packages/jupyterlab/build/93441bee5fcf0a095b35aa85f722b06c.svg
/usr/lib/python3.5/site-packages/jupyterlab/build/c8ddf1e5e5bf3682bc7bebf30f394148.woff
/usr/lib/python3.5/site-packages/jupyterlab/build/cdbbf3faea3d6d5b7c7c8a27736254df.gif
/usr/lib/python3.5/site-packages/jupyterlab/build/d7c639084f684d66a1bc66855d193ed8.svg
/usr/lib/python3.5/site-packages/jupyterlab/build/e6cf7c6ec7c2d6f670ae9d762604cb0b.woff2
/usr/lib/python3.5/site-packages/jupyterlab/build/extensions.bundle.js
/usr/lib/python3.5/site-packages/jupyterlab/build/extensions.bundle.js.manifest
/usr/lib/python3.5/site-packages/jupyterlab/build/fa396483b7ade73b4727bad6aa027a35.html
/usr/lib/python3.5/site-packages/jupyterlab/build/fcad2f97acb3c868bd1ca7629d36d80e.svg
/usr/lib/python3.5/site-packages/jupyterlab/build/loader.bundle.js
/usr/lib/python3.5/site-packages/jupyterlab/build/loader.bundle.js.map
/usr/lib/python3.5/site-packages/jupyterlab/build/main.bundle.js
/usr/lib/python3.5/site-packages/jupyterlab/build/main.bundle.js.manifest
/usr/lib/python3.5/site-packages/jupyterlab/build/main.css
/usr/lib/python3.5/site-packages/jupyterlab-0.10.0.dist-info/DESCRIPTION.rst
/usr/lib/python3.5/site-packages/jupyterlab-0.10.0.dist-info/INSTALLER
/usr/lib/python3.5/site-packages/jupyterlab-0.10.0.dist-info/METADATA
/usr/lib/python3.5/site-packages/jupyterlab-0.10.0.dist-info/RECORD
/usr/lib/python3.5/site-packages/jupyterlab-0.10.0.dist-info/WHEEL
/usr/lib/python3.5/site-packages/jupyterlab-0.10.0.dist-info/entry_points.txt
/usr/lib/python3.5/site-packages/jupyterlab-0.10.0.dist-info/metadata.json
/usr/lib/python3.5/site-packages/jupyterlab-0.10.0.dist-info/pbr.json
/usr/lib/python3.5/site-packages/jupyterlab-0.10.0.dist-info/top_level.txt
```

**Comment by blink1073** [comment]
Drat, I can confirm that https://pypi.python.org/packages/0d/86/20a80a16c6193b5308b09608e8fd157f868b4ba061ef4e8ce07f22a8e1bb/jupyterlab-0.10.0.tar.gz#md5=ea5da50f3bcb1ce55c09b974ad42e901 does not have the `extensions.css` file in it.  Thanks so much for the detailed report.

**Comment by blink1073** [comment]
Wait, my mistake, there *is* not `extensions.css` anymore, we move all of the css out of the extensions and into the main file.  Here's what my folder looks like:

```
0662c22d4e544cecf2bc66ee4c761ed6.svg   cdbbf3faea3d6d5b7c7c8a27736254df.gif
1.1.bundle.js                          extensions.bundle.js
1.1.bundle.js.manifest                 extensions.bundle.js.manifest
26a0370f727f4667dfbf94b8ec576dc4.svg   fa396483b7ade73b4727bad6aa027a35.html
28f2f5e6ac027acb7fbd41f7e02ebf90.gif   fcad2f97acb3c868bd1ca7629d36d80e.svg
2b609d364e2e1d67ba33a81c58d9eb8a.svg   fee66e712a8a08eef5805a46892932ad.woff
5e9fca8da62c2b939b204d8883012664.gif   loader.bundle.js
674f50d287a8c48dc19ba404d20fe713.eot   loader.bundle.js.map
912ec66d7572ff821749319396470bde.svg   main.bundle.js
93441bee5fcf0a095b35aa85f722b06c.svg   main.bundle.js.manifest
af7ae505a9eed503f8b8e6982036873e.woff2 main.css
b06871f281fee6b241d60582ae9369b9.ttf
```

**Comment by blink1073** [comment]
I am a bit stumped.  I have a pip-installed JupyterLab 0.10 on OSX and launched it as `jupyter lab --ip=0.0.0.0` and it loads in my Windows 10 VM in Chrome with proper styling just fine.

**Comment by blink1073** [comment]
My `main.css` has 7529 lines of content in the loaded page, do you mind opening yours and making sure it got the full content?

**Comment by krvkir** [comment]
My `main.css` has 7529 lines too (both on the server and in the loaded page). I'm not sure where to find it in the repo to compare two files with `diff`.

Tried to run jupyterlab as you did (without JupyterHub), the problem remains.

Btw I looked how jupyterlab is rendered in firefox (on the same Windows machine), here's the screenshot. It seems that styles (or part of them) are not loaded correctly in firefox too, is it right?

![2016-11-23-jupyterlab_in_firefox](https://cloud.githubusercontent.com/assets/4031219/20554315/31f2400e-b16c-11e6-8263-0f1f0559c274.PNG)

**Comment by blink1073** [comment]
Here's what I'm seeing from Firefox on Windows 10, and the css is in this [pastebin](http://pastebin.com/NHt4VAaa).

<img width="558" alt="screen shot 2016-11-23 at 9 06 50 am" src="https://cloud.githubusercontent.com/assets/2096628/20566941/7d003df4-b15c-11e6-98f0-15ce355e520c.png">

**Comment by krvkir** [comment]
I `diff`ed two css files (with `--ignore-all-space` to prevent crlf problems) and found no differences.
So, my firefox renders everything as intended, but chrome and internet explorer (i've tested it too) both fail.

**Comment by blink1073** [comment]
We expect Internet Explorer to not render CSS properly right now because we are using CSS variables, which unfortunately will never be supported in IE.  What version of Chrome are you using on Windows?

**Comment by krvkir** [comment]
It's 48.0.2564.103 m.

**Comment by blink1073** [comment]
Aha!  It looks like support for CSS variables was added in version 49.   http://caniuse.com/#feat=css-variables

**Comment by krvkir** [comment]
I've installed the recent version (54.0.2840.99) and it works well.
Thank you very much. What a shame, the obvious thought to upgrade the browser didn't even came to my head.

**Comment by blink1073** [comment]
Let's leave this open as a reminder to update the docs wrt to browser support.
