### ISSUE TITLE
Terminals don't close on Close All and when manually closed don't always clean up after themselves

### ISSUE THREAD

**Issue by Analect** [jupyterlab/jupyterlab#1261]
I had added this as a [comment](https://github.com/jupyterhub/jupyterhub/issues/874#issuecomment-261515994) to an issue over on the jupyterhub repo, but it probably belongs here.  I came upon this potential bug, when doing some troubleshooting with running JupyterLab on JupyterHub.

To reproduce:
You could run up JupyterLab on JupyterHub using this [pull request](https://github.com/jupyterhub/jupyterhub-deploy-docker/pull/27) on the jupyterhub-deploy-docker repo.

A. If you run up a JupyterLab ... and open a few *.ipynbs ... and a few terminals ... and then select Close All from the menu.  The terminals will remain open.  Not sure if that's by design or not.

![image](https://cloud.githubusercontent.com/assets/4063815/20428686/4dcdc912-ad82-11e6-8ed6-521cf9200e47.png)

B. If you then manually closed out any remaining terminals ... so you just have the JupyterLab IDE, and no component windows 'live' (see no terminals or kernels running), then going back into admin and hitting 'stop server' ... it will still spawn another container after a few seconds.

![image](https://cloud.githubusercontent.com/assets/4063815/20428955/c8e1186a-ad83-11e6-83ae-b870fabe9aae.png)

It seems some phantom terminal doesn't get closed-down properly ... and when it pings back to JuptyerHub ... it catalyses a new container to be spawned.  If you close out the JupyterLab browser window completely, then stop the server from the JupyterHub console, the respawning stops.

I'm looking to be able to do a hard stop on a server/container using the JupyterHub API, with a view to being able to spin up a new server/container for a user potentially against a different image, and this currently isn't possible because it seems the terminals aren't fully cleaning up after themselves when closed and are causing the same server to respawn.

**Comment by blink1073** [comment]
Hi @Analect, terminals and consoles are not affected by the File menu by design.  I'm not sure what could be causing the re-spawn behavior.

**Comment by blink1073** [comment]
Does the same thing not happen when starting and shutting down a terminal from the classic notebook?

**Comment by Analect** [comment]
@blink1073 
I haven't confirmed whether this behaviour is happening with the classic notebook on Jupyterhub.  I will try to do that.

Perhaps I should have been more explicit in why the respawning appears to be happening.  From an interaction with @minrk [here](https://github.com/jupyterhub/jupyterhub/issues/874#issuecomment-261500462), it looks like a living (but not always visible) terminal that pings back to JupyterHub that results in JupyterHub respawning a replacement container.

`jupyterhub | [I 2016-11-17 09:49:30.061 JupyterHub log:100] 302 GET /user/testuser/api/terminals?1479376171385 (@172.18.0.2) 2.68ms`

My point above, is that even if Close All is not intended to close Consoles and Terminals, if a user manually closes these out from within JupyterLab ... and can see from the Jupyter UI (Running tab) that no kernels or terminals are running ... then there should not be any calls (such as the log-entry above) back to JuptyerHub.  That is not what is happening. Somehow a terminal remains alive, even if it's window has been closed and it's not visibly 'existing' according to the JuptyerLab UI.

I'm able to observe this, as I was experimenting with the JupyterHub API to stop a user server on JupyterHub (a JupyterLab session that was being served as a container using dockerspawner) ... and while it could stop the server, another spawned immediately ... which we tracked back to a terminal call (as above) still alive ... so the JupyterLab that originally spawned that terminal somehow didn't close that terminal session properly ... even though a user closed the terminal window in JupyterLab.

**Comment by blink1073** [comment]
Ah, I think the problem is that the Websocket was not being shut down when you shut down a terminal session from the running tab.  Note that the behavior of closing a terminal is the same as closing the terminal page in classic notebook, it keeps the session open until you close it on the running tab.

The zombie terminal session should be fixed by switching to the latest JupyterLab (v0.9.1).  cf https://github.com/jupyterlab/services/pull/279

**Comment by Analect** [comment]
I believe this has been resolved, as per above, with version 0.9.1 of jupyterlab. Thanks.
