### ISSUE TITLE
jupyter labextension dialog suggested rebuild JupyterLab

### ISSUE THREAD

**Issue by xiesibobo** [jupyterlab/jupyterlab#12622]
## Description
 **jupyter labextension plugins appear repeatedly**

``` shell
$ jupyter labextension list
JupyterLab v3.4.2
/home/xx/.local/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyter-rightbar-doc v0.1.6 enabled OK (python, jupyter-rightbar-doc)
        @krassowski/jupyterlab-lsp v3.10.1 enabled OK (python, jupyterlab-lsp)
        @jupyter-widgets/jupyterlab-manager v3.1.0 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /home/xiesibo/.local/share/jupyter/lab
        @jupyterlab/hdf5 v1.2.0 enabled OK
        jupyterlab-ext-rightbar-doc v0.1.5 enabled OK


Build recommended, please run `jupyter lab build`:
    jupyterlab-ext-rightbar-doc needs to be included in build
    @jupyterlab/hdf5 needs to be included in build
```

## Reproduce

1. install jupyterlab-ext-rightbar-doc
2. uninstall jupyterlab-rightbar-doc
3. uninstall jupyterlab-ext-rightbar-doc
4. install jupyterlab-ext-rightbar-doc and  jupyterlab-rightbar-doc

GG

**Comment by jweill-aws** [comment]
@xiesibobo We need some more info about this issue. Can you please provide more info about how you installed and uninstalled these extensions? Have you tried rebuilding, and if so, does the issue go away afterward?

**Comment by jweill-aws** [comment]
We haven't received additional info about how you installed and uninstalled these extensions — see @3coins 's request from two weeks ago. Please reopen this issue with the requested info. Thank you for your contribution!
