### ISSUE TITLE
Sidebar - waste of space

### ISSUE THREAD

**Issue by stefansimik** [jupyterlab/jupyterlab#12624]
### Problem

* I'm always frustrated when, I need more workspace for useful things - and then see waste of space in the TOC.
* This empty space is not useful at all and takes almost as much space as the standard sidebar.

![2022-05-30_130935](https://user-images.githubusercontent.com/6208056/170980871-fb0c0363-9e5d-45c4-8a65-3a03da055ab2.png)

I know there is some blue color block, which appear on-mouse-hover, but this could be easily replaced by changing background color of the item on TOC, no need to reserve so much empty space for it.

### Proposed Solution

- Empty space should be removed (made significantly smaller)
- Blue color block, which occurs on-mouse-hover, should be removed and replaced by blue background color of the item itself.

### Context

- OS: Windows 10
- JupyterLab version: 3.4.0

**Comment by fcollonval** [comment]
Closing as solved by https://github.com/jupyterlab/jupyterlab/pull/12374 - it will be available in JupyterLab 4

> Some margin for the collapse buttons will be present. But the width space was reduced at maximum.

![image](https://user-images.githubusercontent.com/8435071/171809401-19b661a8-8ebe-4fd5-893e-d8f0b4396788.png)
