### ISSUE TITLE
Error running a new install of jupyter lab on windows (AssertionError)

### ISSUE THREAD

**Issue by bobasaurus** [jupyterlab/jupyterlab#12631]
## Description

I just installed the latest version of jupyter lab using pip on a Windows 10 machine and am getting an error when trying to run the "jupyter lab" command (or the "jupyter --version" command):

C:\Users\jordan> jupyter lab
Traceback (most recent call last):
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\Scripts\jupyter-lab.EXE\__main__.py", line 4, in <module>
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyterlab\labapp.py", line 11, in <module>
    from jupyter_core.application import JupyterApp, NoStart, base_aliases, base_flags
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_core\application.py", line 16, in <module>
    from traitlets import Bool, List, Unicode, observe
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\traitlets\__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\traitlets\_version.py", line 7, in <module>
    assert __version__ == (
AssertionError

## Reproduce

(This is on a Windows 10 x64 machine, i7-8700, 32.0 GB RAM)

1. Install the latest version of PowerShell x64 from github (7.2.4 64-bit)
2. Install the latest Windows version of Python (3.10.4)
3. From a standard non-admin instance of PowerShell x64, run the "pip install jupyterlab" command
4. Run the "jupyter lab" command

I completely uninstalled jupyter lab (with pip uninstall), PowerShell, and Python.  I then reinstalled all three from freshly-downloaded installers and I'm still getting the same issue.  

## Context

- Windows 10 x64
- Firefox 101.0 (64-bit)
- JupyterLab version: latest from pip

<details><summary>Troubleshoot Output</summary>
<pre>
C:\Users\jordan> jupyter troubleshoot
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the 'C:\Users\jordan\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.
$PATH:
        C:\Program Files\PowerShell\7
        C:\Program Files (x86)\Common Files\Oracle\Java\javapath
        C:\WinAVR-20100110\bin
        C:\WinAVR-20100110\utils\bin
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\
        C:\WINDOWS\System32\OpenSSH\
        C:\Program Files\dotnet\
        C:\ProgramData\chocolatey\bin
        C:\Program Files (x86)\Microsoft Research\Scientific DataSet 1.3\
        C:\Program Files (x86)\Wolfram Research\WolframScript\
        C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
        C:\Program Files (x86)\HID Global\ActivClient\
        C:\Program Files\HID Global\ActivClient\
        C:\Program Files (x86)\dotnet\
        C:\Program Files\TortoiseGit\bin
        C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files\Git\cmd
        C:\Program Files\PuTTY\
        C:\Program Files\PowerShell\7\
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\Scripts\
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\
        C:\Program Files\7-Zip
        C:\WinAVR-20100110\bin
        C:\WinAVR-20100110\utils\bin
        C:\Users\jordan\AppData\Roaming\ActiveState\bin
        C:\Program Files (x86)\Common Files\Oracle\Java\javapath
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\
        C:\WINDOWS\System32\OpenSSH\
        C:\Program Files\dotnet\
        C:\Program Files (x86)\Microsoft Research\Scientific DataSet 1.3\
        C:\Program Files (x86)\Wolfram Research\WolframScript\
        C:\Program Files\PowerShell\7-preview\preview
        C:\Program Files (x86)\HID Global\ActivClient\
        C:\Program Files\HID Global\ActivClient\
        C:\Program Files\PuTTY\
        C:\Program Files\TortoiseGit\bin
        C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
        C:\Program Files\Git\cmd
        C:\Users\jordan\AppData\Local\Microsoft\WindowsApps

sys.path:
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\Scripts\jupyter-troubleshoot.EXE
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\python310.zip
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\DLLs
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib
        C:\Users\jordan\AppData\Local\Programs\Python\Python310
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\win32\lib
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\Pythonwin

sys.executable:
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\python.exe

sys.version:
        3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.19044-SP0

where jupyter:
        C:\Users\jordan\AppData\Local\Programs\Python\Python310\Scripts\jupyter.exe

pip list:
        Package              Version
        -------------------- -----------
        anyio                3.6.1
        argon2-cffi          21.3.0
        argon2-cffi-bindings 21.2.0
        asttokens            2.0.5
        attrs                21.4.0
        Babel                2.10.1
        backcall             0.2.0
        beautifulsoup4       4.11.1
        bleach               5.0.0
        certifi              2022.5.18.1
        cffi                 1.15.0
        charset-normalizer   2.0.12
        colorama             0.4.4
        debugpy              1.6.0
        decorator            5.1.1
        defusedxml           0.7.1
        entrypoints          0.4
        executing            0.8.3
        fastjsonschema       2.15.3
        idna                 3.3
        ipykernel            6.13.0
        ipython              8.4.0
        ipython-genutils     0.2.0
        jedi                 0.18.1
        Jinja2               3.1.2
        json5                0.9.8
        jsonschema           4.5.1
        jupyter-client       7.3.1
        jupyter-core         4.10.0
        jupyter-server       1.17.0
        jupyterlab           3.4.2
        jupyterlab-pygments  0.2.2
        jupyterlab-server    2.14.0
        MarkupSafe           2.1.1
        matplotlib-inline    0.1.3
        mistune              0.8.4
        nbclassic            0.3.7
        nbclient             0.6.3
        nbconvert            6.5.0
        nbformat             5.4.0
        nest-asyncio         1.5.5
        notebook             6.4.11
        notebook-shim        0.1.0
        packaging            21.3
        pandocfilters        1.5.0
        parso                0.8.3
        pickleshare          0.7.5
        pip                  22.0.4
        prometheus-client    0.14.1
        prompt-toolkit       3.0.29
        psutil               5.9.1
        pure-eval            0.2.2
        pycparser            2.21
        Pygments             2.12.0
        pyparsing            3.0.9
        pyrsistent           0.18.1
        python-dateutil      2.8.2
        pytz                 2022.1
        pywin32              304
        pywinpty             2.0.5
        pyzmq                23.0.0
        requests             2.27.1
        Send2Trash           1.8.0
        setuptools           58.1.0
        six                  1.16.0
        sniffio              1.2.0
        soupsieve            2.3.2.post1
        stack-data           0.2.0
        terminado            0.15.0
        tinycss2             1.1.1
        tornado              6.1
        traitlets            5.2.2
        urllib3              1.26.9
        wcwidth              0.2.5
        webencodings         0.5.1
        websocket-client     1.3.2
C:\Users\jordan>
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
C:\Users\jordan> jupyter lab --debug
Traceback (most recent call last):
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\Scripts\jupyter-lab.EXE\__main__.py", line 4, in <module>
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyterlab\labapp.py", line 11, in <module>
    from jupyter_core.application import JupyterApp, NoStart, base_aliases, base_flags
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_core\application.py", line 16, in <module>
    from traitlets import Bool, List, Unicode, observe
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\traitlets\__init__.py", line 5, in <module>
    from ._version import __version__, version_info
  File "C:\Users\jordan\AppData\Local\Programs\Python\Python310\lib\site-packages\traitlets\_version.py", line 7, in <module>
    assert __version__ == (
AssertionError
C:\Users\jordan>
</pre>
</details>

**Comment by tylerdmace** [comment]
Getting this exact same problem. Ubuntu install with Python 3.8.

**Comment by christopheranderson** [comment]
You can address this by modifying `~/Library/Python/3.8/lib/python/site-packages/traitlets/_version.py`:line 2 to be `__version__ = "5.2.2.final"`

Issue appears to be from trailets commit: https://github.com/ipython/traitlets/commit/93e42e2c0865a2dd4a389615d21f7528da7c43e4

They've already committed a fix: https://github.com/ipython/traitlets/commit/ad10c659385a59c5d015ecae123b9b7a31a108cf

**Comment by JanB1** [comment]
@christopheranderson Correct fix is to alter line one to remove "final".
See [comment by wholtz](https://github.com/ipython/traitlets/pull/739#issuecomment-1142632312) on issue ipython/traitlets#739.

**Comment by fcollonval** [comment]
If you are hit by the error, you can force using the latest version of traitlets:

```
pip install "pip install traitlets>=5.2.2.post1"
```
