### ISSUE TITLE
Throws the error FileNotFoundError: [Errno 44] No such file or directory: 'file.pdf' even though the file is in the same directory.

### ISSUE THREAD

**Issue by NOVEREI** [jupyterlab/jupyterlab#12630]
Get the following error when trying to read pdf even though the file is in the same directory
 https://jupyterlab.readthedocs.io/en/latest/getting_started/issue.html -->

![image](https://user-images.githubusercontent.com/106592810/171170342-abcbb8b9-131a-4db3-bc3d-ee97dc125381.png)

**Comment by 3coins** [comment]
Closing as this does not seem to be an issue with JupyterLab.
