### ISSUE TITLE
LabBuildApp doesn't find proxy

### ISSUE THREAD

**Issue by user799595** [jupyterlab/jupyterlab#12678]
## Description

I run `jupyter lab build`

```
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node ~/mambaforge/envs/main/lib/python3.9/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/fontawesome-free/-/fontawesome-free-5.15.3.tgz: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.31.144:80 - Local (192.168.1.154:50079)".
```

But if I run `node ~/mambaforge/envs/main/lib/python3.9/site-packages/jupyterlab/staging/yarn.js install --non-interactive` it works.

## Context

I'm behind a corporate proxy.

I have set all the appropriate environment variables in my `.zshenv` and also set my `.npmrc`.

Why doesn't jupyter lab build respect the proxy settings?

- Operating System and version: macOS Monterey 12.4
- Browser and version: 
- JupyterLab version: 3.4.3

**Comment by jweill-aws** [comment]
Can you paste in the output of `node ~/mambaforge/envs/main/lib/python3.9/site-packages/jupyterlab/staging/yarn.js install --non-interactive`? Also, which version of `node` are you using? The error you're seeing is `tunneling socket could not be established, cause=connect EHOSTUNREACH`, which suggests that either `registry.yarnpkg.com` was down at the time you ran the command or that `registry.yarnpkg.com` is blocked by your corporate proxy. The `node` output will help understand where you're successfully getting packages from.

Other, possibly relevant issues concerning build failures:
#7298
#9924

**Comment by user799595** [comment]
Unable to reproduce - very sorry!
