### ISSUE TITLE
404 : Not Found on Windows 7

### ISSUE THREAD

**Issue by iraklic** [jupyterlab/jupyterlab#1267]
I am sure this is a rookie question and problem, but I still humbly try to ask. Why I see a 
**404 : Not Found
You are requesting a page that does not exist!** 

when I try to run "jupyter lab" from cmd of windows 7. I installed it using pip and have python 2.7 with anaconda 2 distribution.

Thanks in advance.

**Comment by blink1073** [comment]
Hi @iraklic, did you enable the serverextension?  `jupyter serverextension enable --py jupyterlab --sys-prefix`.

**Comment by iraklic** [comment]
Now I did and it work. Thank you very much. (I am sorry if I didn't notice this in insturctions for running it)

**Comment by iraklic** [comment]
Perhaps I can build here : 
 * now that it runs, it won't launch the Notebook or Editor. It does start the console and kernel though.
 * In kernels I only see Python 2. How can I add R in there (as far as I know jypiterLab does support R now, right?)

**Comment by blink1073** [comment]
You should be able to see all of the kernels that are installed for your current environment.  What does `jupyter kernelspec list` look like?

Mine looks like (I have all of these running in JupyterLab):

```bash
$ jupyter kernelspec list
Available kernels:
  python3          /Users/ssilvester/anaconda/lib/python3.5/site-packages/ipykernel/resources
  calysto_bash     /Users/ssilvester/Library/Jupyter/kernels/calysto_bash
  calysto_xonsh    /Users/ssilvester/Library/Jupyter/kernels/calysto_xonsh
  julia-0.5        /Users/ssilvester/Library/Jupyter/kernels/julia-0.5
  octave           /Users/ssilvester/Library/Jupyter/kernels/octave
  scilab           /Users/ssilvester/Library/Jupyter/kernels/scilab
  ir               /Users/ssilvester/anaconda/share/jupyter/kernels/ir
```

**Comment by iraklic** [comment]
Mine only shows python2
`Available kernels:
  python2    C:\Users\ichakaberia\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\resources`

But I do have R installed and I even opened it to make sure it was running.

**Comment by blink1073** [comment]
It sounds like your R kernel was installed to another python environment.  What steps did you take to test it on its own?

**Comment by iraklic** [comment]
I think I am missing something here. R was installed separately, so I am not sure how to connect it to the python environment.

**Comment by blink1073** [comment]
You can try making it available system-wide using their instructions:  https://irkernel.github.io/installation/

**Comment by iraklic** [comment]
Done! Thank you very much. That did the trick.

Now only thing remaining is that I cannot launch the Notebook or Editor from the launcher. What am I missing?

**Comment by blink1073** [comment]
The other errors are because of the issue raised in #1265.  I am working on the fix for that currently.

**Comment by iraklic** [comment]
Thank you very much!!! Really, thanks.

**Comment by blink1073** [comment]
I'm going to close this one since #1265 is tracking the other part.
