### ISSUE TITLE
More space for the Favorites list

### ISSUE THREAD

**Issue by joel23888** [jupyterlab/jupyterlab#12681]
### Problem

I would like to be able to have more space for the Favorites list. When working on a smaller screen, I can only add five items before scroll bars appear which makes it less efficient to use the Favorites list.

### Proposed Solution

One possible solution from a user perspective may be to allow the user to change the split between the Favorites list and the File Browser. Another possible solution might involve having a separate Favorites button in the side bar.

**Comment by jweill-aws** [comment]
JupyterLab does not have a "favorites" option in its file browser. Are you using the https://github.com/jupyterlab-contrib/jupyterlab-favorites extension? If so, please open a bug in this extension's issues section. Unfortunately, I can't transfer this issue between organizations.

If you find a problem in JupyterLab without additional extensions, please reopen this issue. Thank you for your contribution.

**Comment by joel23888** [comment]
On checking, I am indeed using that extension. I will raise an issue for this extension. Sorry for not realizing this before.
