### ISSUE TITLE
add "show file location in file browser" action for editors

### ISSUE THREAD

**Issue by rursprung** [jupyterlab/jupyterlab#12699]
### Problem
I often have multiple open notebooks which are stored in different folders and then need to open an additional notebook from within the same folder - but am currently located in another folder in the file browser.

i then either have to manually switch directories or have to temporarily activate the "Show Active File in File Browser" setting - which is however not something i want to keep active as it's annoying if the file browser always jumps around when switching tabs.

### Proposed Solution
add a "show file in file location" option which navigates to the file location in the file browser (if the active editor has such a location - which is e.g. not the case for consoles).

open for discussion: how should this be integrated in the GUI? options i see:
* not at all, use it only through the command palette (or add it to the context actions in your own JSON preferences)
* with a UI element in the file browser (see JetBrains screenshot as an example below)
* with a context action on editor tabs (see VS Code screenshot as an example below) - this is my personal favourite

### Additional context
* there's an existing "Show Active File in File Browser" toggle which, if enabled, always navigates to the file when switching editors (presuming the currently active editor has a file behind it):
  https://github.com/jupyterlab/jupyterlab/blob/03046f4d3f1501e1eefcea030261f6774e26c5d3/packages/filebrowser-extension/src/index.ts#L1116-L1130
  https://github.com/jupyterlab/jupyterlab/blob/03046f4d3f1501e1eefcea030261f6774e26c5d3/packages/filebrowser-extension/src/index.ts#L468-L489
* e.g. JetBrains tools (in the screenshot: CLion) have a "select opened file" action in the file browser:
  ![image](https://user-images.githubusercontent.com/39383228/173680324-a8bba7b3-aa51-40c6-b4b2-edd6dcf3e05b.png)
* e.g. VS Code has a "Reveal in Explorer View" context action on editor tabs:
  ![image](https://user-images.githubusercontent.com/39383228/173680877-75144198-6b27-4307-9eb7-7a4ecc53b6da.png)

**Comment by agoose77** [comment]
Have you tried the context menu for the notebook?
![image](https://user-images.githubusercontent.com/1248413/173909950-4193974d-530f-4eaa-a51c-0095e715df77.png)

**Comment by rursprung** [comment]
> Have you tried the context menu for the file?
> ![image](https://user-images.githubusercontent.com/1248413/173909950-4193974d-530f-4eaa-a51c-0095e715df77.png)

i think i need new glasses... i totally missed that the action already exists and is already there! 🤦🙈  thanks a lot for pointing this out!
