### ISSUE TITLE
`labextension develop` assumes setuptools-based package

### ISSUE THREAD

**Issue by agoose77** [jupyterlab/jupyterlab#12696]
After switching to the fantastic new Hatch build plugin for extensions, I ran into https://github.com/jupyter/notebook/pull/6425/commits/d6d3c45b5d21128cf8ac470e12e7fd2c6d380997

Whilst investigating whether we could remove this dependency on setuptools, I noticed that [the current logic](https://github.com/jupyterlab/jupyterlab/blob/82a283b6528663556602ee1e57001adae511c181/jupyterlab/federated_labextensions.py#L398) seems to assume that the `module` passed to the develop command is _either_ a module name or a file path. Despite this, the docs only mention the module name support. Upon closer inspection, we're also conflating package names, package paths, and distribution names. This won't manifest itself as a bug unless someone authors a namespace package with a different distribution name to package name.

Overall, I think we can simplify this code whilst also adding support for any build backend, rather than requiring a setup.py shim in extension projects. 

Some thoughts:

1. Reduce scope of `develop`. Right now it will build the extension if its source does not yet exist. Let's just error out here, and require the generation as part of the editable install step.
1. Only accept module names. Given that we already require that the distributions are installed, this change just removes all the indirection and clarifies the fact that it's up to the package manager (conda, python, apt etc.) to handle the "installation" of the extension in develop mode.
2. Remove need for setuptools. As above, we don't actually care if the package is "installed" as long as it is in `sys.path`(?).
3. Drop special-casing for namespace packages. They should be picked up by importing the module.

**Comment by agoose77** [comment]
@blink1073 given that you've been working on the `hatch-jupyter-builder`, I'd be interested to hear your thoughts on this.

**Comment by blink1073** [comment]
Already in progress.  :smile:  https://github.com/jupyterlab/jupyterlab/pull/12606
