### ISSUE TITLE
Browser tab title does not update on notebook rename

### ISSUE THREAD

**Issue by aclementev** [jupyterlab/jupyterlab#12705]
## Description

The browser tab title does not update on Notebook rename.

## Reproduce

1. Create a new Notebook. The browser title should be set to "Untitled.ipynb - JupyterLab"
2. Right click on the JupyterLab tab for the notebook, rename notebook.
3. The notebook is renamed, but the browser title does not update. 

Additionally, if you switch the active notebook to another one and back, it will update correctly.

## Expected behavior

When you rename a notebook, the browser tab's title should update automatically.

## Context

- Operating System and version: MacOS Monterrey 12.4
- Browser and version: Chrome 102
- JupyterLab version: 3.4.3

Here's a screenshot: 

<img width="643" alt="image" src="https://user-images.githubusercontent.com/55786369/174036297-e08eeebd-eb1f-4af7-b05d-138969983e6c.png">

**Comment by astrojuanlu** [comment]
I worked on this for a few minutes, this is what I found:

The `updateTabTitle` function gets the name of the current document from `data['layout-restorer:data']`:

https://github.com/jupyterlab/jupyterlab/blob/dc55eca669b2730ec33025e8e9bbde91c9b0629c/packages/apputils-extension/src/index.ts#L336-L338

which itself originates from the `changed` event from the `StateDB`:

https://github.com/jupyterlab/jupyterlab/blob/dc55eca669b2730ec33025e8e9bbde91c9b0629c/packages/apputils-extension/src/index.ts#L400-L410

Now, here's the thing: switching JLab tabs triggers a `save` with the key `layout-restorer:data`:

https://github.com/jupyterlab/jupyterlab/blob/dc55eca669b2730ec33025e8e9bbde91c9b0629c/packages/statedb/src/statedb.ts#L134-L137

However, the `renameFile` does not trigger such a `StateDB` update, and therefore the `updateTabTitle` gets called with the old name:

https://github.com/jupyterlab/jupyterlab/blob/dc55eca669b2730ec33025e8e9bbde91c9b0629c/packages/docmanager/src/dialogs.ts#L71-L85

The question, then, is: where exactly should the `.save` be triggered on rename?
