### ISSUE TITLE
Support user-defined `y_doc` document type 

### ISSUE THREAD

**Issue by trungleduc** [jupyterlab/jupyterlab#12711]
### Problem

The current y_doc handler of `JupyterLab` uses the `file_type` of the document to create the corresponding y_doc document, but [JupyterLab](https://github.com/jupyterlab/jupyterlab/blob/b4540166b6afaba3454492591122ca963dbb3350/packages/services/src/contents/index.ts#L121) and [jupyter_server](https://github.com/jupyter-server/jupyter_server/blob/7b5815e0176c079d17c539c3baf6b497197f58a7/jupyter_server/services/contents/handlers.py#L101) hard-coded the file types to `file | notebook | directory` so any new file type registered with  `jupyter_ydoc` can not be used.

### Proposed Solution

Add an optional parameter to the `path` property of `IDocumentProviderFactory.IOptions` to specify the type of  `y_doc`
 document.

**Comment by trungleduc** [comment]
cc @hbcarlos @davidbrochart

**Comment by davidbrochart** [comment]
Thanks @trungleduc, yes that is needed to support collaborative editing for new document types.

**Comment by trungleduc** [comment]
Fixed by https://github.com/jupyter-server/jupyter_server/pull/895.
