### ISSUE TITLE
Bug opening file in hidden directory

### ISSUE THREAD

**Issue by tleonhardt** [jupyterlab/jupyterlab#12713]
## Description

My team maintains a custom JupyterLab-based environment and we have a JL extension which provides an extra help menu for our environment. Recently we encountered an odd bug apparently caused by a change in some open-source Jupyter component because we haven't touched the associated extension code in a long time and it just stopped working recently.  We have a menu option to display all installed software which opens a file `/home/jovyan/.ar/softwareList.txt` for viewing. We are now getting the following error:

```sh
File Load Error for softwareList.txt
file or directory '/.ar/softwareList.txt' does not exist
```

However, we can simply open a terminal in JL and ran any command to view this file such as `cat ~/.ar/softwareList.txt` and it works fine.

## Reproduce

1. Try to open an existing text file in the `.ar` path under the JL root directory using a JL extension
2. Receive an error about the file not existing

This file also cannot be opened using the `File -> Open from Path` option.  I tested and if I put it in a directory `ar` instead of `.ar`, then opening it using `File -> Open from Path` does work fine.  So I suspect some recent change has broken the ability to open files in hidden directories.

## Expected behavior

All readable files should be able to be open.

## Context

- Operating System and version: Amazon Linux 2 with kernel 5.4.188-104.359.amzn2.x86_64 running in EKS
- Browser and version: Firefox 101.0.1 (64-bit)
- JupyterLab version: 3.4.3

Other jupyter versions:
```
jupyterutils==0.20.0
jupyter==1.0.0
jupyter-client==7.3.4
jupyter-console==6.4.3
jupyter-core==4.10.0
jupyter-dash==0.4.2
jupyter-server==1.17.1
jupyter-server-mathjax==0.2.5
jupyter-server-proxy==3.2.1
jupyter-telemetry==0.1.0
jupyterhub==2.3.1
jupyterlab==3.4.3
jupyterlab-git==0.30.1
jupyterlab-pygments==0.2.2
jupyterlab-server==2.14.0
jupyterlab-widgets==1.1.0
```

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

```sh
$ jupyter troubleshoot
/usr/bin/python3: No module named pip
$PATH:
        /opt/amazon/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /home/jovyan/.local/bin
        /home/jovyan/bin

sys.path:
        /usr/local/bin
        /opt/amazon/lib/python3.7/site-packages
        /opt/amazon/lib/python3.7/site-packages/BenderLibApolloLocal
        /home/jovyan
        /usr/lib64/python37.zip
        /usr/lib64/python3.7
        /usr/lib64/python3.7/lib-dynload
        /usr/local/lib64/python3.7/site-packages
        /usr/local/lib/python3.7/site-packages
        /usr/lib64/python3.7/site-packages
        /usr/lib/python3.7/site-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.7.10 (default, Jun  3 2021, 00:02:01) 
        [GCC 7.3.1 20180712 (Red Hat 7.3.1-13)]

platform.platform():
        Linux-5.4.188-104.359.amzn2.x86_64-x86_64-with-glibc2.2.5

which -a jupyter:
        /usr/local/bin/jupyter
```

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

This is a highly secured system and I cannot provide this.

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

JS console output:
```sh
Showing error: Error: file or directory '/.ar/softwareList.txt' does not exist
    r serverconnection.js:88
    create serverconnection.js:107
    get index.js:509
    get index.js:200
    _revert context.js:585
    promise callback*_revert context.js:584
    initialize context.js:225
    d manager.js:470
    promise callback*_createOrOpenDocument manager.js:470
    open manager.js:295
    execute 568.342ad45be2d94b0abe3e.js:1
    execute index.es6.js:370
    triggerActiveItem index.es6.js:6690
    _evtMouseUp index.es6.js:7037
    handleEvent index.es6.js:6836
    onBeforeAttach index.es6.js:6861
    processMessage index.es6.js:1437
    b index.es6.js:444
    t index.es6.js:180
    r index.es6.js:1836
    c index.es6.js:7615
    open index.es6.js:6816
    _openChildMenu index.es6.js:14098
    _evtMouseDown index.es6.js:14023
    handleEvent index.es6.js:13859
[dialog.js:34:12](webpack://jupyterlab/application-top/node_modules/@jupyterlab/apputils/lib/dialog.js)
Failed to initialize the context with 'text' for /.ar/softwareList.txt Error: file or directory '/.ar/softwareList.txt' does not exist
    r serverconnection.js:88
    create serverconnection.js:107
    get index.js:509
    get index.js:200
    _revert context.js:585
    promise callback*_revert context.js:584
    initialize context.js:225
    d manager.js:470
    promise callback*_createOrOpenDocument manager.js:470
    open manager.js:295
    execute 568.342ad45be2d94b0abe3e.js:1
    execute index.es6.js:370
    triggerActiveItem index.es6.js:6690
    _evtMouseUp index.es6.js:7037
    handleEvent index.es6.js:6836
    onBeforeAttach index.es6.js:6861
    processMessage index.es6.js:1437
    b index.es6.js:444
    t index.es6.js:180
    r index.es6.js:1836
    c index.es6.js:7615
    open index.es6.js:6816
    _openChildMenu index.es6.js:14098
    _evtMouseDown index.es6.js:14023
    handleEvent index.es6.js:13859
```

**Comment by DarkmatterVale** [comment]
Confirmed the issue also occurs in JL 3.3.4, not just JL 3.4.x

**Comment by DarkmatterVale** [comment]
Confirmed that the issue still appears in JL 3.0.0. I'm wondering if there was an update to a dependency for our JL extension that has caused the problem.

**Comment by krassowski** [comment]
A week ago jupyter-server v1.17.1 was released which patched https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-q874-g24w-4q9g vulnerability related to hidden files serving. My understanding is that you now need to explicitly allow hidden files to be served by the server; this should be possible with `--ContentsManager.allow_hidden=True`; please note that this will also expose hidden files in the file browser of JupyterLab (which will remain hidden by default but a new option in the `View` menu will become available).

I think that https://github.com/jupyter-server/jupyter_server repository would be a good place to discuss this further.

**Comment by tleonhardt** [comment]
@krassowski Thanks for pointing out that breaking change in a minor release of `jupyter-server`.
