### ISSUE TITLE
How do I add a post-execution hook?

### ISSUE THREAD

**Issue by NightMachinery** [jupyterlab/jupyterlab#12716]
How do I add a pre/post-execution hook?

I want to use this to add, e.g., an auditory bell for cells that take long to execute.

**Comment by krassowski** [comment]
What did you try? There is [`NotebookActions`](https://jupyterlab.readthedocs.io/en/stable/api/classes/notebook.notebookactions-1.html) with `executed` and `selectionExecuted` signals with an example in https://github.com/mwakaba2/jupyterlab-notifications/pull/19

Also, for IPython only: https://stackoverflow.com/a/50648266 https://stackoverflow.com/a/50569680 and https://github.com/krassowski/jupyter-helpers/blob/master/jupyter_helpers/notifications.py

**Comment by NightMachinery** [comment]
I found a solution:
```
import IPython 
from IPython.core.interactiveshell import InteractiveShell

def bell_ipy(result):
    ...
    
    
IPython.get_ipython().events.register('post_run_cell', bell_ipy)
```

Thanks!
