### ISSUE TITLE
Renaming notebooks does not update tab title

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12728]
## Description

If a notebook is renamed, it is not reflected in the browser tab name.

## Reproducer

https://user-images.githubusercontent.com/1813603/175426067-bbdc2c7a-f0ce-4927-a512-377970e1f44f.mov

## Expected behavior

The tab name is updated

## Context
Lab@3.4.2

**Comment by krassowski** [comment]
#12705?

**Comment by mlucool** [comment]
Yes. Closing in favor of that
