### ISSUE TITLE
Inconsistent font size in settings

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#12727]
## Description

Labels for checkboxes are larger than labels for other settings: 

![Screenshot from 2022-06-23 21-10-04](https://user-images.githubusercontent.com/5832902/175389282-cdb91c7f-1af5-4746-ae4e-7d9f38097e78.png)

## Reproduce

1. Open settings editor 
2. Go to Terminal
3. See that "Screen Reader Mode" label is larger than neighbours..

## Expected behavior

IMO this looks inconsistent and it would be better to have them harmonized (as previously suggested in review in https://github.com/jupyterlab/jupyterlab/pull/12082#discussion_r810395080).

In particular I would expect the setting labels to be smaller than the header "Terminal settings.". Right now checkbox label is of the same size.

## Context

- JupyterLab version: 3.4

**Comment by ohrely** [comment]
Changing `font-size` from `--jp-content-font-size2` to `--jp-content-font-size1` for `.jp-SettingsPanel .checkbox label` should fix this.  Marking as a good first issue.
https://github.com/jupyterlab/jupyterlab/blob/4682f927424c4a916ecb5ec673e907b16ba0c8a9/packages/settingeditor/style/base.css#L253-L256

**Comment by siddartha-10** [comment]
Hey can i fix this issue.
