### ISSUE TITLE
3.4.3 breaks ctrl F functionality 

### ISSUE THREAD

**Issue by RSDummy0** [jupyterlab/jupyterlab#12723]
## Description
When searching for text in CTRL+F mode, the searchtool loses focus whenever you hit the enter button. If the enter button is entered consecutively, jupyter starts editing the cell with the first match. Problem didn't not persist once I downgraded to jupyterlab 3.3.4

## Reproduce

1. launch jupyterlab v3.4.3
2.  hit ctrl F, search for a string
3. hit enter to get your first instance of the string
4. the searchbar has lost focus and you're now editing in the cell where you found the first instance of the string. 

## Expected behavior
The searchbar should not lose focus under any circumstances when I'm hitting the enter key.

## Context

- Operating System and version:  W11
- Browser and version:  Firefox and chrome
- JupyterLab version:  3.4.3

**Comment by fcollonval** [comment]
I confirm it was introduced in 3.4.3 - downgrading to 3.4.2 fixes it.

**Comment by fcollonval** [comment]
It is very probably a side effect of https://github.com/jupyterlab/jupyterlab/pull/12447
