### ISSUE TITLE
Support for unix socket

### ISSUE THREAD

**Issue by vsoch** [jupyterlab/jupyterlab#12731]
### Problem

My HPC cluster does not allow ports being exposed, and a unix socket is a good alternative.

### Proposed Solution

Akin to how jupyter notebook provides them (and it looks like someone asked about it here two years ago https://discourse.jupyter.org/t/configure-unix-socket/5941) I'm wondering if it might be possible to open up a running instance via a socket?

### Additional context

I've actually tried the jupyter notebook example https://github.com/jupyter/notebook/pull/4835 (there aren't docs I can find anywhere else) and I can't even reproduce the simple local example to use nc (it doesn't give me an error message but I see no output). So if y'all have ideas / someone to ping over there, I would be immensely grateful! I'd really like to see this working.

**Comment by agoose77** [comment]
It looks like it should: https://github.com/jupyter-server/jupyter_server/pull/525

**Comment by vsoch** [comment]
Oh great, thank you! I provided that same link here https://discourse.jupyter.org/t/configure-unix-socket/5941 and since I (since posting this) got it working with jupyter notebook I'll give a shot at this next weekend and ping if anything else comes up. Thank you kindly @agoose77 !
