### ISSUE TITLE
CVE vulnerabilities in some dependencies

### ISSUE THREAD

**Issue by NextFire** [jupyterlab/jupyterlab#12736]
## Description

- `testutils` uses [`markdown-loader-jest`](https://github.com/gpincheiraa/markdown-loader-jest), a 5 years old lib that locks `marked` to ^0.3.9, vulnerable to the severe https://github.com/advisories/GHSA-rrrm-qjm4-v8hf
- Old versions of `package-json` in `buildutils` and `lighthouse` in `testutils` locks `got` to ^9.6.0, vulnerable to https://github.com/advisories/GHSA-pfrx-2q88-qq97
- (Out of scope for now: JLab uses `verdaccio`, which one of its dependancies locks `jsdom` to 15.2.1, vulnerable to https://github.com/advisories/GHSA-f4c9-cqv8-9v98, [open pr in their end](https://github.com/verdaccio/monorepo/pull/592))

Context: I had these vulnerabilities reported by Dependabot on one of my JupyterLab extensions projects.

## Reproduce

N/A

## Expected behavior

Updated dependancies to patch these vulnerabilities.

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version:  989683cb7f83a9fbbe6caea1e1b0cfb9096f8d16

**Comment by fcollonval** [comment]
Closing as verdaccio was updated as side effect of https://github.com/jupyterlab/jupyterlab/pull/12095

**Comment by willarmiros** [comment]
@fcollonval is there any chance that the PRs fixing this issue, specifically #12776, will get applied to the `3.6.x` branch as these are security issues?
