### ISSUE TITLE
Restart Kernel dialog should get focus

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#1275]
Pressing `Esc`, `0 0` will bring up the Restart Kernel dialog but it doesn't have focus so AFAICS you have to then manually click either OK or Cancel?

It would be good if the OK button could get focus so you could restart a kernel with `Esc`, `0 0`, `Enter`.

Presumably, having already pressed `Esc`, `0 0` you're pretty sure you want to restart so it would be better to have the OK button have focus by default rather than the Cancel button.

**Comment by blink1073** [comment]
Yup, this is the behavior of the classic notebook.
