### ISSUE TITLE
Editor tab-completion

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#1276]
...would be nice to have.

**Comment by blink1073** [comment]
Agreed!

**Comment by ellisonbg** [comment]
+1

I think the right way to abstract this is to use a formal notion of language services that include completion, etc.

**Comment by hrishikeshac** [comment]
It would be awesome to have this feature!

**Comment by zuoxingdong** [comment]
+1

Waiting for this very convenient feature.

**Comment by Mxbonn** [comment]
+1!
The first image on the current documentation shows the scenario how I would use JupyterLab:
![](http://jupyterlab.readthedocs.io/en/stable/_images/jupyterlab.png)
A jupyter notebook next to a python file in which I edit functions that I use often along multiple notebooks. Having the same language support in the text editor as in the notebook would be a game changer!

**Comment by yelled1** [comment]
Why not use neovim (or even emacs) from the terminal? I realize JLab won't show graphics this way, but I bet we can have some python program updating a separate window. 
Both have pretty good repl integrations BTW. Although neovim's iron.vim is rather new.
Also, can something like nyaovim be integrated with backend neovim? It's electron. So, it would even show graphics. 
Not that I am not excited by the prospect but this may take a long long time to get it working.
BTW: I am already on the neovim on terminal. It works extremely well. All except that I cannot get the copy/paste on Elementary Os local machine with gCloud ssh back end.

**Comment by AljoLe** [comment]
Tab auto completion for 'R' and 'Julia' would be very nice! It's the only thing holding me back from switching completely to jupyterlab as my #1 IDE.

**Comment by felixpatzelt** [comment]
Tab completion in the terminal would be great, too!

**Comment by jasongrout** [comment]
We now have tab completion in the editor when a kernel is associated: #5049. Thanks @ian-r-rose!
