### ISSUE TITLE
Unable to save notebook file

### ISSUE THREAD

**Issue by ZhongxuanWang** [jupyterlab/jupyterlab#12790]
## Description

I can't save a notebook file after some editing. I tried command+s, manually save from menu options, and many others, but still couldn't save. The black dot indicating file is changed DOES NOT disappear. And when I had to forfeit the changes in order to refresh the page, I would see my progress disappear.

## Reproduce

One way of making it happen is to press command-S repeatedly (so when the file is saved but you keep pressing save option.) It is especially effective when you do not release your fingers from the button.

## Expected behavior

save my file..

## Context

- Operating System and version: AWS Deep Learning AMI Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1031-aws x86_64v)
- Browser and version: Chrome Version 103.0.5060.114 (Official Build) (arm64) UP-TO-DATE
- JupyterLab version: 3.4.3

<details><summary>Troubleshoot Output</summary>
<pre>
NO WARNING OR ERROR from jupyter lab output.
</pre>
</details>

**Comment by ZhongxuanWang** [comment]
Anyone?

**Comment by ZhongxuanWang** [comment]
> Hi @ZhongxuanWang, this issue is duplicated with #11348. Even without using JupyterLab in collaborative mode, we request the lock to save the content, see
> 
> https://github.com/jupyterlab/jupyterlab/blob/52519b561863836a59664e6071c268506f9c5354/packages/docregistry/src/context.ts#L303
> 
> .
> If you have a slow internet connexion, it could happen that the first request gets lost, and every time you are pressing cmd+s, you are making a new request to obtain the lock to be able to save the document. The problem is that the backend already assigned you that lock, but the frontend did not receive the message because it got lost, blocking every other request to obtain lock.

Thank you so much! My collaborative mode is INDEED turned ON. 

My internet connection is fair, and also since it would always happen when I press cmd+S without releasing the button immediately, I would say the continued pressing may have rendered an internal crash or something that would make the lock lost (my guessing). It would be great if there can be a function to detect the process that acquired the lock is dead, or  add a force saving option, because sometimes I would forget when my lab stopped saving files, it would cause me huge troubles.

**Comment by davidbrochart** [comment]
In JupyterLab 4.0 with RTC on, this issue should disappear since saving will be automatic (Ctrl-S will have no effect).

**Comment by hbcarlos** [comment]
Closing as fixed by #11599
