### ISSUE TITLE
Displaying doc strings in JupyterLab by pressing "SHIFT+TAB"

### ISSUE THREAD

**Issue by juliohm** [jupyterlab/jupyterlab#1279]
In a Jupyter Notebook we can move the cursor over a function and press "SHIFT+TAB" to get the doc string. This feature doesn't work in JupyterLab notebooks.

Do I have something misconfigured by default?

**Comment by dhirschfeld** [comment]
Dup of #714

**Comment by juliohm** [comment]
What about that great inspector functionality described in the post you linked? I don't have that tab on my JupyterLab installation.

**Comment by dhirschfeld** [comment]
You can find it by searching using the Command Palatte (Ctrl-Shift-P)

**Comment by blink1073** [comment]
Thanks for the report, @juliohm, let's track this over on #714.
