### ISSUE TITLE
Add setting `trustbydefault` to `htmlviewer-extension`

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlab/jupyterlab#12792]
As mentioned by  @jtpio in [jupyterlite issue #708](https://github.com/jupyterlite/jupyterlite/issues/708#issuecomment-1180053413).

I think is would be useful to have a new setting that allows to trust `.html` files by default upon opening them.  
The default would be `false` of course, to change nothing of the current safe behavior.  
I would be particularly useful in the context of jupyterlite, I think.

I have written a an extension to do that, but it really feels like overkill given the tiny modification: 
https://github.com/oscar6echo/jupyterlab-trust-html

What do you think ?

**Comment by jtpio** [comment]
Thanks @oscar6echo for suggesting this.

Maybe an example for adding this to the `htmlviewer-extension` would be to define a setting like `flash` in the `logconsole-extension`: 

https://github.com/jupyterlab/jupyterlab/blob/2bd99333aefdc43a442ebe84b4b23d3ac01a011a/packages/logconsole-extension/schema/plugin.json#L37-L42

Which is then used here: 

https://github.com/jupyterlab/jupyterlab/blob/2bd99333aefdc43a442ebe84b4b23d3ac01a011a/packages/logconsole-extension/src/index.tsx#L285

And still default to `false` to keep the existing behavior of not trusting HTML files.

There are other examples across the code base that define a `boolean` setting like this. Happy to provide more guidance if needed.

**Comment by oscar6echo** [comment]
@jtpio Thx for the pointers.  
Getting inspiration from them I created this PR: #12868.  

It works as expected if I set the `trustbydefault` default value to true.  
But I realize that I do not know how to set this param upon jupyterlab launch, neither in the context of jupyterlite, so could not test to set it.  

I do not know where/if the documentation must be modified.  

What do you recommend as next steps ?

**Comment by jtpio** [comment]
Thanks @oscar6echo! Let's continue on the PR then.
