### ISSUE TITLE
jupyterlab shows kernel that is not specified 

### ISSUE THREAD

**Issue by sorenwacker** [jupyterlab/jupyterlab#12805]
My JupyterLab shows a kernel that is not specified under `~/.local/share/jupyter/kernels`.

What other locations can I check to remove that kernel? 

![image](https://user-images.githubusercontent.com/3391614/179205191-ad802ca8-c2cd-4dd6-b4f8-5c91738ba80f.png)
![image](https://user-images.githubusercontent.com/3391614/179205229-0a38870f-712c-413c-b7f0-d9bd51663ef4.png)

**Comment by jweill-aws** [comment]
When you run the command `jupyter kernelspec list`, you should see a list of all available kernels and their directory locations. Do you see all the listed kernels in the results of this command?

**Comment by jweill-aws** [comment]
@sorenwacker Do you see all the listed kernels in the results of `jupyter kernelspec list`?

**Comment by jweill-aws** [comment]
@sorenwacker I'm closing this issue for lack of needed info. Please reopen if you don't see the kernels in `jupyter kernelspec list`'s output.
