### ISSUE TITLE
Allow specific headings to be hidden in TOC

### ISSUE THREAD

**Issue by stefansimik** [jupyterlab/jupyterlab#12808]
### Problem

There are frequent situations, where one needs to have a header in notebook for organizational purposes,
but it is less important and it would be nice, if it would not be displayed in TOC.

Problem is, that when there are many less important headings, then TOC if also full of unimportant sections.
It would really help, if we could remove some heading from the TOC.

### Proposed Solution

Let's add some special flag / marker to the heading, which prevents it from being displayed in TOC.
For example:

`## Less important heading <!--notoc-->`

**Comment by fcollonval** [comment]
This is implemented and will be available in 4.0 - It will test for a html tag with class `jp-toc-ignore` or `tocSkip` e.g. [# Title <a class="jp-toc-ignore tocSkip"></a>.](https://jupyterlab.readthedocs.io/en/latest/user/toc.html).

The syntax comes from the legacy [toc2](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html) extension for the classical notebook.

**Comment by stefansimik** [comment]
Wonderful, I love you guys.
Just followup question, is there any estimate, when possibly the 4.0 version could be released? (this year / next year...)

**Comment by fcollonval** [comment]
We are rushing to reach a beta status. 4.0 final release will hopefully land in fall this year
