### ISSUE TITLE
Ctrl-Enter doesn't work in the Console

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#1280]
By *"doesn't work"* I mean that when you paste in a block and want to put a new line somewhere in the middle you would usually place your cursor where you wanted the new line to go and press Ctrl-Enter.

In JupyterLab doing this puts a new line *at the end of the cell* rather than where your cursor is.

**Comment by blink1073** [comment]
Good catch, thanks!
