### ISSUE TITLE
RuntimeError: Cannot enter into task

### ISSUE THREAD

**Issue by utkonos** [jupyterlab/jupyterlab#12803]
## Description

Certain notebooks raise an exception when they are opened: `RuntimeError: Cannot enter into task`. This is an intermittent error.

## Reproduce

1. Open a notebook
2. Read logs

## Expected behavior

No error.

## Context

- macOS 12.4
- Chrome 103
- JupyterLab 3.4.3

```none
Exception in callback <TaskStepMethWrapper object at 0x113db7a00>()
handle: <Handle <TaskStepMethWrapper object at 0x113db7a00>()>
Traceback (most recent call last):                                                            
  File "/usr/local/Cellar/python@3.10/3.10.5/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)                               
RuntimeError: Cannot enter into task <Task pending name='Task-5' coro=<HTTP1ServerConnection._server_request_loop() running at /Volumes/Jupyter/venv/lib/python3.10/site-packages/tornado/http1connection.py:842>cb=[IOLoop.add_future.<locals>.<lambda>() at /Volumes/Jupyter/venv/lib/python3.10/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-159' coro=<PeriodicCallback._run() running at /Volumes/Jupyter/venv/lib/python3.10/site-packages/tornado/ioloop.py:921> cb=[IOLoop.add_future.<locals>.<lambda>() at /Volumes/Jupyter/venv/lib/python3.10/site-packages/tornado/ioloop.py:694]> is being executed.
```

**Comment by utkonos** [comment]
@jweill-aws I did see that issue, but I decided to open a new specific one because that the original issue reported there is different than the error here. #11934 appears to have become a catchall for a variety of error messages.

I will try to isolate this to a specific notebook. Unfortunately I have many open, and the error in the log is non-specific.

**Comment by elac-safran** [comment]
Hi everyone. For information, downgrading  `tornado` from v6.2 to v6.1 apparently solved the problem for me (on Windows). Fingers crossed.

**Comment by pythonic2020** [comment]
This problem has been killing me with MS Edge Version 103.0.1264.62 (Official build) (64-bit), current Win 10 OS, JLab 3.4.3 in a conda-forge environment.  I have tornado 6.2 installed.

**Comment by InCogNiTo124** [comment]
I had this problem after a fresh install of jupyterlab with `pip install jupyterlab`, however jupyterlab does not exit or stop for me.

Pop!_OS 22.04 LTS (based on ubuntu 22.04 lts)
JupyterLab 3.4.4
Brave [Version 1.39.81 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)](https://brave.com/latest/)

**Comment by JMing-Li** [comment]
I encountered a similar problem in a docker container. The extension Jupyterlab-lsp's code autocompletion (only use jupyterlab-lsp for autocompletion and Jedi was disabled) fails to work for a while when some RuntimeErrors occur.  But autocompletion sometimes can resume after refreshing the page.

Error messages look like the following:

`Exception in callback <TaskWakeupMethWrapper object at 0x7f1d47536850>(<Future finished result=None>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7f1d47536850>(<Future finished result=None>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-128' coro=<LanguageServerSession._read_lsp() running at /opt/venv/reticulate/lib/python3.8/site-packages/jupyter_lsp/session.py:167> wait_for=<Future finished result=None>> while another task <Task pending name='Task-1220' coro=<PeriodicCallback._run() running at /opt/venv/reticulate/lib/python3.8/site-packages/tornado/ioloop.py:921> cb=[IOLoop.add_future.<locals>.<lambda>() at /opt/venv/reticulate/lib/python3.8/site-packages/tornado/ioloop.py:694]> is being executed.`

The error can appear randomly from time to time and I can't reproduce it.

Docker container env: ubuntu: 20.04
tornado: 6.2
jupyterlab: 3.4.3
jupyterlab-lsp: 3.10.1

**Comment by pythonic2020** [comment]
I got the error today using current Firefox x64 on Windows 10, JLab 3.4.4, in a conda-forge environment running Python 3.9.13. Tornado 6.2 is installed.

> [W 2022-07-26 07:15:00.993 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x00000238587EA820>
> [IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
> [IPKernelApp] WARNING | No such comm: c5fa9929-bfb5-4b4c-9728-1944e8a7d5d1
> [I 2022-07-26 07:16:56.910 ServerApp] Saving file at /test.ipynb
> Exception in callback <TaskWakeupMethWrapper object at 0x00000238587177F0>(<Future finis...ache\r\n\r\n'>)
> handle: <Handle <TaskWakeupMethWrapper object at 0x00000238587177F0>(<Future finis...ache\r\n\r\n'>)>
> Traceback (most recent call last):
>   File "C:\Users\xxx\Miniconda3\envs\forge39\lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
> RuntimeError: Cannot enter into task <Task pending name='Task-31' coro=<HTTP1ServerConnection._server_request_loop() running at C:\Users\xxxxx\Miniconda3\envs\forge39\lib\site-packages\tornado\http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...cache\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at C:\Users\xxxxx\Miniconda3\envs\forge39\lib\site-packages\tornado\ioloop.py:687]> while another task <Task pending name='Task-1634' coro=<PeriodicCallback._run() running at C:\Users\xxxxx\Miniconda3\envs\forge39\lib\site-packages\tornado\ioloop.py:921> cb=[IOLoop.add_future.<locals>.<lambda>() at C:\Users\xxxxx\Miniconda3\envs\forge39\lib\site-packages\tornado\ioloop.py:694]> is being executed.

After the error, navigation in the File Explorer was impossible.  Refreshing the browser tab restored such functionality.

**Comment by ConfuseIous** [comment]
I got this error on Firefox x64, Windows 11 with both python 3.8.13 and 3.9.13 environments. Downgraded tornado to 6.1 as suggested above and the error disappeared. Kernel still keeps dying but that appears to be a separate issue.

**Comment by divyansshhh** [comment]
FWIW, I'm seeing this as well. Downgrading to tornado 6.1 fixed it.

**Comment by philippjfr** [comment]
Also started this after upgrading to Tornado 6.2.

**Comment by jleman** [comment]
I ran into this problem as well in Windows 11, Python 3.10.7... even after downgrading to Tornado 6.1.  I ended up deleting the default workspace file per this discussion:  https://stackoverflow.com/questions/70361265/server-connection-error-with-conda-and-jupyter-lab.

**Comment by subwaymatch** [comment]
@jleman Deleting all workspace files in `~/.jupyter/lab/workspaces` fixed the issue for me as well. Thank you for sharing the tip. 👍

**Comment by maajdl** [comment]
Just got the same after tornado upgrate to 6.2

**Comment by manmoi01** [comment]
Downgrading to tornado 6.1 fixed it. Win 11 python 3.10

**Comment by ariasfer** [comment]
Downgrading to tornado 6.1 fixed it. Win 10 python 3.7.3
