### ISSUE TITLE
InputDialog to allow for several values

### ISSUE THREAD

**Issue by luis-chaves-visa** [jupyterlab/jupyterlab#12801]
### Problem

Hi I'd like to request several values to the user via a jupyterlab extension. I am not sure this is currently supported in: https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/inputdialog.ts

But I think it'd be a great feature

**Comment by jweill-aws** [comment]
Although there is no shortcut to display a dialog box with multiple inputs, you can pass in a `Widget` that has multiple inputs and that has a function to return a value that is a composite of multiple inputs. The dialog box will then display multiple inputs. I have done this for a project that is not yet available publicly.

If you display a more complex dialog box in this way, be sure to test it on multiple devices, including mobile devices, to ensure that it displays properly on smaller screens.
