### ISSUE TITLE
How to add multiple server extensions.

### ISSUE THREAD

**Issue by vinurg** [jupyterlab/jupyterlab#12815]
when we are adding two server extensions only one extension is visible. by default it automatically deleted previous server extension and adding new server extension to the jupyterlab. how can we resolve this issue. please help me.

**Comment by fcollonval** [comment]
@vinurg could you provide more information about what you are doing (in particular which extensions are you trying to install). And please provide the server logs.

**Comment by jweill-aws** [comment]
@vinurg To respond to this issue, we need more information about what you're trying to do. Can you please provide the extensions you're trying to install?

**Comment by jweill-aws** [comment]
@vinurg I'm closing this issue for lack of info. If you can provide more info about the extensions in question, please reopen this issue. Thanks!
