### ISSUE TITLE
Migration to CM6 follow up

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/jupyterlab#12812]
This issue tracks the remaining parts to fix or to reimplement when https://github.com/jupyterlab/jupyterlab/pull/11638 is merged:

- [ ] LaTeX highlighting. A parser can be implemented as explained [here](https://codemirror.net/examples/lang-package/)
- ~~Multiplex mode. An example of mixed-language parsing is provided [here](https://codemirror.net/examples/mixed-language/)~~ won't be implemented.
- [x] Once multiplexing and LaTeX highlighting are fixed the visual regression tests for markdown multiplex should look [like before the CM6 merge](https://user-images.githubusercontent.com/5832902/183522825-8221f4e1-d3b9-4554-a305-c4f0454553ef.png).
- ~~Breakpoints gutters should be reworked to be smaller and the breakpoint indicator should be aligned with the line number~~
- [x] The codemirror package should provide a singleton that allow to register new themes and modes.
- [x] Python console header have syntax highlight but it should not
- [x] Source files opened from the debugger kernel source panel don't have syntax highlight
- [x] We need to remove settings that are not supported any longer (see next list)
- Many configuration options are not available anymore or should be implemented a different way,, this shouId be done when https://github.com/jupyterlab/jupyterlab/pull/11638 is merged:
  - [x] cursorBlinkRate: this can be done thanks to another [extension](https://codemirror.net/docs/ref/#view.drawSelection), however this requires some work in the CSS
  - [x] fontFamily: done
  - [x] fontSize: done
  - [x] lineHeight: done
  - [x] lineNumber: done
  - [x] lineWrap: done
  - [x] readOnly: done
  - [x] tabSize: done
  - [x] insertSpaces: done
  - [x] matchBtackets: https://github.com/jupyterlab/jupyterlab/pull/12861
  - [x] autoClosingBrackets: done
  - [x] handlePaste: TODO
  - [x] wordWrapColumn: done
  - [x] rulers: N/A ?
  - [x] codeFolding: https://github.com/jupyterlab/jupyterlab/pull/12861 - ok for file editor but does not work for Python code cells; it may be related to the ipython mode not providing the required information
  - [x] showTrailingSpaces: Probably need to be able to display white space akin to VS Code ?
  - [x] mode: done
  - [x] theme: done
  - smartIndent: N/A
  - electricChar: N/A
  - [x] keyMap: done
  - [x] extraKeys: done
  - [x] gutters: must be injected
  - [x] fixedGutters: must be configured in the gutter itself
  - ~~foldGutter~~: Covered by codeFolding
  - [x] showCursorWhenSelecting: should be implemented with [drawSelection](https://codemirror.net/docs/ref/#view.drawSelection)
  - coverGutterNextToScrollBar: N/A
  - [x] dragDrop: TODO
  - [x] lineSeparator: TODO
  - scrollBarStyle: pur CSS
  - [x] lineWiseCopyCut: N/A ?
  - [x] scrollPastEnd: [TODO](https://discuss.codemirror.net/t/scrollpastend/3433) 
  - [x] styleActiveLine: done
  - styleSelectedText: pure CSS
  - selectionPointer: N/A

N/A means the option is not available in CodeMirror or there is no straighforward way to implement it. Further investigation is required to implement it.

**Comment by fcollonval** [comment]
New memory leaks appeared following the CM6 merge: https://github.com/jupyterlab/benchmarks/actions/runs/2703258687

**Comment by jtpio** [comment]
How many of these should be fixed before being able to make a new 4.0 alpha release?

Thinking that minor visual glitches would be fine for now and could be addressed later.

**Comment by fcollonval** [comment]
## Benchmark report for CM6 PR

:warning: The final version of CM6 PR has worsen the time to open and close a notebook with lots of Markdown cells. But it improves a lot the case for lots of code cells notebook. As this [was not seen](https://github.com/jupyterlab/jupyterlab/pull/11638#issuecomment-1152587974) during the PR, that may be related to the latest addition of parsing code block for highlighting or there is a threshold in favor of optimization when the number of cells increased.

The execution time (in milliseconds) are grouped by test file, test type and browser.
For each case, the following values are computed: _min_ <- [_1st quartile_ - _median_ - _3rd quartile_] -> _max_.

The mean relative comparison is computed with 95% confidence.

<details><summary>Results table</summary>

| Test file | large_code_100_notebook | large_md_100_notebook | longOutput - A single output with 100x100 divs |
| --- | --- | --- | --- |
| **open** | | | |
| `chromium` | | | |
| actual | 1330 <- [1384 - 1409 - 1442] -> 1887 | 1775 <- [1864 - 1901 - 1956] -> 2484 | 1374 <- [1430 - 1454 - 1486] -> 1700 |
| expected | 2997 <- [3059 - 3134 - 3223] -> 3434 | 1312 <- [1391 - 1414 - 1437] -> 1733 | 1397 <- [1459 - 1487 - 1506] -> 1701 |
| Mean relative change | -54.6% ± 0.7% | 34.9% ± 1.7% | -1.5% ± 0.9% |
| **switch-from-copy** | | | |
| `chromium` | | | |
| actual | 36 <- [48 - 68 - 129] -> 464 | 52 <- [71 - 88 - 329] -> 655 | 49 <- [65 - 74 - 109] -> 389 |
| expected | 42 <- [51 - 60 - 276] -> 499 | 41 <- [61 - 73 - 116] -> 643 | 47 <- [64 - 75 - 111] -> 463 |
| Mean relative change | -19.3% ± 11.5% | 60.9% ± 21.9% | -2.6% ± 9.2% |
| **switch-to-copy** | | | |
| `chromium` | | | |
| actual | 504 <- [506 - 508 - 511] -> 546 | 508 <- [530 - 540 - 558] -> 765 | 503 <- [510 - 516 - 523] -> 610 |
| expected | 503 <- [506 - 509 - 513] -> 556 | 503 <- [507 - 509 - 512] -> 537 | 503 <- [508 - 512 - 517] -> 581 |
| Mean relative change | -0.3% ± 0.2% | 8.2% ± 0.9% | 1.1% ± 0.4% |
| **switch-from-txt** | | | |
| `chromium` | | | |
| actual | 31 <- [37 - 42 - 58] -> 121 | 49 <- [67 - 73 - 79] -> 368 | 40 <- [63 - 67 - 73] -> 270 |
| expected | 36 <- [51 - 63 - 68] -> 182 | 34 <- [41 - 52 - 64] -> 211 | 40 <- [62 - 66 - 70] -> 167 |
| Mean relative change | -23.5% ± 3.1% | 65.1% ± 13.9% | 5.5% ± 4.1% |
| **switch-to-txt** | | | |
| `chromium` | | | |
| actual | 31 <- [54 - 64 - 72] -> 200 | 42 <- [63 - 71 - 81] -> 403 | 45 <- [60 - 70 - 82] -> 211 |
| expected | 34 <- [58 - 68 - 79] -> 220 | 32 <- [51 - 58 - 64] -> 105 | 47 <- [61 - 68 - 76] -> 261 |
| Mean relative change | -8.0% ± 4.7% | 39.0% ± 9.6% | 6.3% ± 5.9% |
| **search** | | | |
| `chromium` | | | |
| actual | 1284 <- [1371 - 1418 - 1450] -> 1609 | 2057 <- [3434 - 4739 - 5322] -> 6936 | 16508 <- [17819 - 18447 - 19897] -> 20330 |
| expected | 1907 <- [2143 - 2580 - 3100] -> 4077 | 1426 <- [1602 - 1729 - 1937] -> 2952 | 16757 <- [18365 - 18974 - 20250] -> 20680 |
| Mean relative change | -46.9% ± 2.1% | 144.4% ± 16.9% | -2.3% ± 1.9% |
| **close** | | | |
| `chromium` | | | |
| actual | 393 <- [446 - 469 - 504] -> 737 | 401 <- [430 - 449 - 466] -> 555 | 463 <- [489 - 505 - 515] -> 564 |
| expected | 438 <- [471 - 486 - 499] -> 620 | 347 <- [368 - 381 - 396] -> 430 | 443 <- [477 - 486 - 499] -> 534 |
| Mean relative change | -1.5% ± 2.6% | 18.0% ± 2.0% | 3.0% ± 1.1% |

Changes are computed with _expected_ as reference.

</details>

![image](https://user-images.githubusercontent.com/8435071/181195284-a05d5732-f044-4fcb-8653-e729395d1bae.png)

Expected = [b90ee225ece884dd54b99dc9757bec5b660fb480](https://github.com/jupyterlab/jupyterlab/commit/b90ee225ece884dd54b99dc9757bec5b660fb480) | Actual = [a9761d380251f5dec9243e533ba001613aaaef44](https://github.com/jupyterlab/jupyterlab/commit/a9761d380251f5dec9243e533ba001613aaaef44)
[Go to action log](https://github.com/jupyterlab/benchmarks/actions/runs/2730742364)
[Changelog covered](https://github.com/jupyterlab/jupyterlab/compare/b90ee225ece884dd54b99dc9757bec5b660fb480...a9761d380251f5dec9243e533ba001613aaaef44)

**Comment by jtpio** [comment]
> How many of these should be fixed before being able to make a new 4.0 alpha release?

Looks like https://github.com/jupyterlab/jupyterlab/pull/12861 could get in before the next pre-release.

**Comment by fcollonval** [comment]
In https://github.com/jupyterlab/jupyterlab/pull/12861
- styling has been improved by restoring bold, italic, monospace and link effect.
- internal displayable strings are translated to use JupyterLab `ITranslator`.

**Comment by krassowski** [comment]
- [ ] "Show Trailing Space" setting does not seem to work.

**Comment by fcollonval** [comment]
Closing as the latest point has been extracted in its own issue.
