### ISSUE TITLE
Show whitespace

### ISSUE THREAD

**Issue by palewire** [jupyterlab/jupyterlab#1281]
Wouldn't it be cool if you could easily configure JupyterLab to show the whitespace so you could more easily track indentations? This is a common configuration option in text editors designed for Python coders, like Sublime Text and Atom.

**Comment by blink1073** [comment]
Agreed, thanks @palewire.  This depends on having our Settings system in place: #515.

**Comment by jasongrout** [comment]
See https://github.com/coderaiser/cm-show-invisibles, for an example plugin for showing whitespace. See also https://codemirror.net/demo/visibletabs.html and https://codemirror.net/demo/trailingspace.html

**Comment by p-i-** [comment]
This would be very desirable.
I've just copied a large cell to a `.py` and the whitespace is all over the place.
Could someone provide instructions how to install this?

**Comment by nanoant** [comment]
I concur. Very desirable feature but somewhat not catching attention of the developers here. It seems all the necessary infrastructure is there. Can we have these both https://codemirror.net/demo/visibletabs.html and https://codemirror.net/demo/trailingspace.html exposed via advanced settings please?

**Comment by vidartf** [comment]
PRs to help out are of course always welcome. Even a first attempt where you ask if someone can help clean it up will typically make it easier to get through 👍

**Comment by tiancaigg** [comment]
has there by any plugins to show whitespace in Jupyterlab?

**Comment by opisthofulax** [comment]
Here 5 years later hoping for an update to show invisibel characters.

**Comment by richardkang112** [comment]
Hello everyone. I am trying to add cm-show-invisibles addon to Jupyterlab's Codemirror instance, and it looks like this:

![image](https://user-images.githubusercontent.com/50002894/123521694-30f11600-d686-11eb-8300-aa61a493d6a1.png)

Would this be useful for the issue?

**Comment by krassowski** [comment]
Closing as added in #10632 and available in JupyterLab 3.2.0.

**Comment by krassowski** [comment]
Sorry, this one is focused on indentation and not trailing whitespace it was incorrectly tagged - reopening.

**Comment by fcollonval** [comment]
This is solved in the upcoming JupyterLab 4:

![image](https://user-images.githubusercontent.com/8435071/232783421-2a4273da-68f1-46b4-9d7a-88e8c870797c.png)

**Comment by palewire** [comment]
Hey, this is great! First filed in 2016!
