### ISSUE TITLE
JupyterLab: Cell number has gone blank when I run torch.cuda.device_count()

### ISSUE THREAD

**Issue by Anandhfullstack** [jupyterlab/jupyterlab#12817]
## Description

I want to know the Cuda device count, but if I run the code, I got an empty cell number. 

![Ste1_issue](https://user-images.githubusercontent.com/45931976/179918452-9bceba51-376e-4e9d-b02e-ec22b2c1e735.PNG)

After I run the second cell, the cell number is gone, I don't know why.

When I run the second cell again, I got this error. I think, automatically my kernel is restarted that's why I get the number 1 on the second cell. 

![step_2 issue](https://user-images.githubusercontent.com/45931976/179922366-4a4b91b8-070b-433d-a47c-98f849345af8.PNG)

Is this issue related to my GPU or CUDA thing??.

kindly help me to sort out this issue, Thanks in advance.

**Comment by jweill-aws** [comment]
If you run a Python script with these same commands in a command-line window, do you see any errors? 

I tried the same process on JupyterLab locally, using tip of `master`, and I did not see this problem.

Can you please provide info about the JupyterLab version and Python version you're running?

**Comment by jweill-aws** [comment]
@Anandhfullstack Can you provide the info requested earlier? This may be a problem with your local environment if you can reproduce it using Python in a command-line window.

**Comment by Anandhfullstack** [comment]
Hi Jweill-ws, Sorry for the delayed response, yes you are right.  The error occurs  because of the environment, I reinstall my cuda setting then, everything works fine.

**Comment by jweill-aws** [comment]
OK, no problem! I'll close this issue, but if you notice any bugs or areas for improvement, please open another. Thank you for your assistance.

**Comment by Anandhfullstack** [comment]
Sure, Thank you.
