### ISSUE TITLE
Followup to improved readonly UI: add Toast notifcations

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#12827]
I'm following up on my previous comment with another mockup. The first combines 1 and 2 to provide an approach that might be familiar from Notebook while having an (albeit small) icon indication in the tab as added support.

![IconClassicCrop](https://user-images.githubusercontent.com/50221806/86960276-21df2400-c114-11ea-9ac1-5054c05d9f72.png)

With toast notifications moving forward in #689, I think this could be a good opportunity to remind users a notebook is read-only if they try to save. I could see this being potentially annoying if it repeats, but since toasts last 10 seconds at most I think it could work if it seems like there should be an additional reminder of read-only status.

![IconClassic](https://user-images.githubusercontent.com/50221806/86960303-29063200-c114-11ea-868a-20a1f6d2c92f.png)

_Originally posted by @isabela-pf in https://github.com/jupyterlab/jupyterlab/issues/7980#issuecomment-655703618_

**Comment by telamonian** [comment]
I'm splitting out @isabela-pf's Toast-on-attempted-save UI proposal (described above) out from #7980 into a fresh issue here. The easy way to do this would be to incorporate an already existing quality Snackbar/Toast component, such as these fine examples:

- [material-ui Snackbar](https://mui.com/material-ui/react-snackbar/)
  - looks good
  - super flexible
  - con: have to bring in the large mui package, though in theory tree-shaking should mitigate this
- [light-toast](https://github.com/xinkule/light-toast)
  - small (5 kb as per bundlephobia)
  - con: smallish user base

**Comment by vidartf** [comment]
I think this is the oldest issue tracking toasts: https://github.com/jupyterlab/jupyterlab/issues/689

**Comment by vidartf** [comment]
Someone also mentioned this: https://github.com/jupyterlab-contrib/jupyterlab_toastify

**Comment by fcollonval** [comment]
Copying here the discussion summary from the weekly meeting:

    - Original toast issue: https://github.com/jupyterlab/jupyterlab/issues/689
    - Max would like to add an existing quality Toast implementation to jlab: [#12827](https://github.com/jupyterlab/jupyterlab/issues/12827)
    - eg two reasonable choices of `Toast` component:
      - [material-ui Snackbar](https://mui.com/material-ui/react-snackbar/)
        - looks good
        - super flexible
        - con: have to bring in the large mui package, though in theory tree-shaking should mitigate this
          - @ajbozarth has been using material-ui snackbar in elyra, and likes it
      - [light-toast](https://github.com/xinkule/light-toast)
        - small (5 kb as per bundlephobia)
        - con: smallish user base
      - In [jupyterlab-toastify](https://github.com/jupyterlab-contrib/jupyterlab_toastify), [react-toastify](https://github.com/fkhadra/react-toastify/) is used.
    - Recently we had a vote adopting fastui as a component library
      - Note that [FAST UI](https://fast-ui.netlify.app/index.html) is not the same as Microsoft's [FAST design system](https://www.fast.design/)

**Comment by fcollonval** [comment]
Additional comments:

- [FAST](https://fast.design) Design does not provide a default notification UI. And I support Max that implementing our own is not straighforward.
- [jupyterlab_toastify](https://github.com/jupyterlab-contrib/jupyterlab_toastify) was created to bring an abstracted third-party library for the UI; I think the pattern should be kept to ease maintenance/evolution.
- The material-ui Snackbar is for me missing an easy-to-use API to create toast of a specific type, to dismiss them programmatically and to have a toast following a running task (ability to update it); but this is by essence as the goal of the library is to provide nice customizable components rather that API oriented usage.

What people are using (feel free to update the list):

- Material-UI Snackbar:
  - [Elyra](https://github.com/elyra-ai/elyra)
  - [jupyterlab-git](https://github.com/jupyterlab/jupyterlab-git/blob/master/src/components/Alert.tsx)
- jupyterlab-toastify:
  - [gator](https://github.com/mamba-org/gator)
  - [jupyterlab-tour](https://github.com/jupyterlab-contrib/jupyterlab-tour)
  - [jupyterlab-comments](https://github.com/jupytercalpoly/jupyterlab-comments)

**Comment by krassowski** [comment]
Closing as this was implemented in https://github.com/jupyterlab/jupyterlab/pull/15317
