### ISSUE TITLE
403 File Save Error

### ISSUE THREAD

**Issue by gdebrun2** [jupyterlab/jupyterlab#12831]
## Description

Hi, I'm getting the following file save error in jupyterlab launched through jupyterhub:

![image](https://user-images.githubusercontent.com/60619834/180093683-dea39d06-4eee-4965-b767-0184adf618d0.png)

After this error occurs, I can still interact with the kernel but I have to reload the webpage to be able to save any files. I also cannot launch a new terminal after the error occurs. When I try to, I get the following error:

![image](https://user-images.githubusercontent.com/60619834/180095466-d495b80f-d93d-4a56-a537-8a3d9475f484.png)

## Reproduce

1. Open Google Chrome
2. Navigate to my organization's jupyterhub
3. Login to jupyterhub with my credentials
4. Launch jupyterlab server
5. The error will occur at some point at this stage, whether my python kernel is idle for a prolonged period, or whether I'm continuously running code

## Things I've tried:

1. Clearing Chrome cache
2. A clean virtual environment
3. Switching to Firefox
4. Changing c.ServerApp.root_dir in my jupyter_lab_config.py
5. Setting c.ServerApp.allow_remote_access = True
6.  Setting c.ServerApp.allow_credentials = True
7. Setting c.ServerApp.allow_root = True
8. Setting c.ServerApp.trust_xheaders = True

## Expected behavior

Jupyterlab should be able to continuously save my notebook while working.

## Context

This issue began immediately after joining my organization's jupyterhub, so I believe it is independent of extensions, user configuration, etc. Coworkers also experience this.

Local system info:

- Windows 10 Enterprise v10.0.19044
- Chrome v103.0.5060.134

Server Host info:

- CentOS Linux 7 (Core) / Kernel v.10.0-1160.6.1.el7.x86_64
- Jupyterlab v3.4.3
- Jupyterhub v2.3.1

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /home/$USER/.nvm/versions/node/v18.6.0/bin
        /opt/spack/c7.7/stock-20201208/spack/opt/spack/linux-centos7-x86_64/gcc-7.5.0/texlive-live-fieigbiggeh6tzixv4hvqzgyaiswpnca/bin/x86_64-linux
        /opt/spack/c7.7/stock-20201208/spack/opt/spack/linux-centos7-x86_64/gcc-7.5.0/texlive-live-fieigbiggeh6tzixv4hvqzgyaiswpnca/bin
        /opt/spack/c7.7/stock-20201208/spack/opt/spack/linux-centos7-x86_64/gcc-7.5.0/graphviz-2.44.1-ybhz6nfuauwnnz5lnirxlhxkx2htgix6/bin
        /opt/spack/c7.7/stock-20201208/spack/opt/spack/linux-centos7-x86_64/gcc-7.5.0/gnuplot-5.2.8-7kwelkk5q4qfwjn2li5rhqjypryzrg2x/bin
        /opt/spack/c7.7/stock-20201208/spack/opt/spack/linux-centos7-x86_64/gcc-7.5.0/git-2.29.0-vf2asz2mxhwrwog33uontenpu5smoemh/bin
        /opt/spack/c7.7/compilers-20201207/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/cuda-11.0.2-hyplv2sxrzn3u36dhtqduzyli47db5o2/bin
        /home/$USER/$VENV/bin
        /usr/local/bin
        /sbin
        /bin
        /usr/sbin
        /usr/bin
        /usr/local/sbin
        /opt/ibutils/bin
        /home/$USER/.local/bin
        /home/$USER/bin

sys.path:
        /home/$USER/$VENV/bin
        /opt/spack/c7.7/stock-20201208/spack/opt/spack/linux-centos7-x86_64/gcc-7.5.0/python-3.8.6-i7lr6nhbey7fqgdi7y37d22nsmn434sc/lib/python38.zip
        /opt/spack/c7.7/stock-20201208/spack/opt/spack/linux-centos7-x86_64/gcc-7.5.0/python-3.8.6-i7lr6nhbey7fqgdi7y37d22nsmn434sc/lib/python3.8
        /opt/spack/c7.7/stock-20201208/spack/opt/spack/linux-centos7-x86_64/gcc-7.5.0/python-3.8.6-i7lr6nhbey7fqgdi7y37d22nsmn434sc/lib/python3.8/lib-dynload
        /home/$USER/$VENVt/lib/python3.8/site-packages

sys.executable:
        /home/$USER/$VENV/bin/python

sys.version:
        3.8.6 (default, Dec  9 2020, 20:24:14) 
        [GCC 7.5.0]

platform.platform():
        Linux-3.10.0-1160.6.1.el7.x86_64-x86_64-with-glibc2.2.5

which -a jupyter:
        /home/$USER/$VENV/bin/jupyter

pip list:
        Package                   Version
        ------------------------- -----------
        alembic                   1.8.1
        anyio                     3.6.1
        argon2-cffi               21.3.0
        argon2-cffi-bindings      21.2.0
        astral                    2.2
        asttokens                 2.0.5
        async-generator           1.10
        attrs                     21.4.0
        Babel                     2.10.3
        backcall                  0.2.0
        batchspawner              1.1.0
        beautifulsoup4            4.11.1
        black                     22.6.0
        bleach                    5.0.1
        certifi                   2022.6.15
        certipy                   0.1.3
        cffi                      1.15.1
        charset-normalizer        2.1.0
        click                     8.1.3
        cryptography              37.0.4
        cycler                    0.11.0
        debugpy                   1.6.2
        decorator                 5.1.1
        defisheye                 1.0.0
        defusedxml                0.7.1
        entrypoints               0.4
        executing                 0.8.3
        fastjsonschema            2.15.3
        fonttools                 4.34.4
        greenlet                  1.1.2
        h5py                      3.7.0
        idna                      3.3
        imageio                   2.19.3
        importlib-metadata        4.12.0
        importlib-resources       5.8.0
        ipykernel                 6.15.1
        ipython                   8.4.0
        ipython-genutils          0.2.0
        ipywidgets                7.7.1
        jedi                      0.18.1
        Jinja2                    3.1.2
        json5                     0.9.8
        jsonschema                4.7.2
        jupyter                   1.0.0
        jupyter-client            7.3.4
        jupyter-console           6.4.4
        jupyter-core              4.11.1
        jupyter-server            1.18.1
        jupyter-telemetry         0.1.0
        jupyterhub                2.3.1
        jupyterlab                3.4.3
        jupyterlab-code-formatter 1.5.0
        jupyterlab-pygments       0.2.2
        jupyterlab-server         2.15.0
        jupyterlab-widgets        1.1.1
        kiwisolver                1.4.3
        Mako                      1.2.1
        MarkupSafe                2.1.1
        matplotlib                3.5.2
        matplotlib-inline         0.1.3
        mistune                   0.8.4
        mypy-extensions           0.4.3
        nbclassic                 0.4.3
        nbclient                  0.6.6
        nbconvert                 6.5.0
        nbformat                  5.4.0
        nest-asyncio              1.5.5
        networkx                  2.8.4
        nodejs                    0.1.1
        notebook                  6.4.12
        notebook-shim             0.1.0
        numpy                     1.23.1
        oauthlib                  3.2.0
        opencv-python             4.6.0.66
        optional-django           0.1.0
        packaging                 21.3
        pamela                    1.0.0
        pandas                    1.4.3
        pandocfilters             1.5.0
        parso                     0.8.3
        pathspec                  0.9.0
        pexpect                   4.8.0
        pickleshare               0.7.5
        Pillow                    9.2.0
        pip                       22.1.2
        platformdirs              2.5.2
        prometheus-client         0.14.1
        prompt-toolkit            3.0.30
        psutil                    5.9.1
        ptyprocess                0.7.0
        pure-eval                 0.2.2
        pvlib                     0.9.1
        pycparser                 2.21
        Pygments                  2.12.0
        pyOpenSSL                 22.0.0
        pyparsing                 3.0.9
        pyrsistent                0.18.1
        python-dateutil           2.8.2
        python-json-logger        2.0.4
        pytz                      2022.1
        PyWavelets                1.3.0
        pyzmq                     23.2.0
        qtconsole                 5.3.1
        QtPy                      2.1.0
        requests                  2.28.1
        ruamel.yaml               0.17.21
        ruamel.yaml.clib          0.2.6
        scikit-image              0.19.3
        scipy                     1.8.1
        Send2Trash                1.8.0
        setuptools                63.2.0
        six                       1.16.0
        sniffio                   1.2.0
        soupsieve                 2.3.2.post1
        SQLAlchemy                1.4.39
        stack-data                0.3.0
        terminado                 0.15.0
        tifffile                  2022.5.4
        tinycss2                  1.1.1
        tomli                     2.0.1
        tornado                   6.2
        traitlets                 5.3.0
        typing_extensions         4.3.0
        urllib3                   1.26.10
        wcwidth                   0.2.5
        webencodings              0.5.1
        websocket-client          1.3.3
        wheel                     0.37.1
        widgetsnbextension        3.6.1
        zipp                      3.8.1
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Fail to get yarn configuration. /home/$USER/.nvm/versions/node/v18.6.0/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/$USER//.nvm/versions/node/v18.6.0/bin/node)
/home/$USER/.nvm/versions/node/v18.6.0/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/$USER/.nvm/versions/node/v18.6.0/bin/node)
/home/$USER/.nvm/versions/node/v18.6.0/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/$USER/.nvm/versions/node/v18.6.0/bin/node)
/home/$USER/.nvm/versions/node/v18.6.0/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/$USER/.nvm/versions/node/v18.6.0/bin/node)
/home/$USER/.nvm/versions/node/v18.6.0/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/$USER/.nvm/versions/node/v18.6.0/bin/node)
/home/$USER/.nvm/versions/node/v18.6.0/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/$USER/.nvm/versions/node/v18.6.0/bin/node)

[D 2022-07-20 16:31:33.037 ServerApp] Searching ['/', '/home/$USER/.jupyter', '/home/$USER/$VENV/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2022-07-20 16:31:33.038 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2022-07-20 16:31:33.038 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2022-07-20 16:31:33.038 ServerApp] Looking for jupyter_config in /home/$USER/$VENV/etc/jupyter
[D 2022-07-20 16:31:33.039 ServerApp] Looking for jupyter_config in /home/$USER/.jupyter
[D 2022-07-20 16:31:33.039 ServerApp] Looking for jupyter_config in /
[D 2022-07-20 16:31:33.040 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2022-07-20 16:31:33.040 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2022-07-20 16:31:33.040 ServerApp] Looking for jupyter_server_config in /home/$USER/$VENV/etc/jupyter
[D 2022-07-20 16:31:33.040 ServerApp] Looking for jupyter_server_config in /home/$USER/.jupyter
[D 2022-07-20 16:31:33.040 ServerApp] Looking for jupyter_server_config in /
[D 2022-07-20 16:31:33.043 ServerApp] Paths used for configuration of jupyter_server_config: 
        /etc/jupyter/jupyter_server_config.json
[D 2022-07-20 16:31:33.043 ServerApp] Paths used for configuration of jupyter_server_config: 
        /usr/local/etc/jupyter/jupyter_server_config.json
[D 2022-07-20 16:31:33.044 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/$USER/$VENV/etc/jupyter/jupyter_server_config.d/jupyterlab.json
        /home/$USER/$VENV/etc/jupyter/jupyter_server_config.d/jupyterlab_code_formatter.json
        /home/$USER/$VENV/etc/jupyter/jupyter_server_config.d/nbclassic.json
        /home/$USER/$VENV/etc/jupyter/jupyter_server_config.d/notebook_shim.json
        /home/$USER/$VENV/etc/jupyter/jupyter_server_config.json
[D 2022-07-20 16:31:33.047 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/$USER/.jupyter/jupyter_server_config.json
[D 2022-07-20 16:31:33.048 ServerApp] Paths used for configuration of jupyter_server_config: 
        /jupyter_server_config.json
[D 2022-07-20 16:31:33.083 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'allow_credentials': True, 'allow_origin': '*', 'allow_remote_access': True, 'allow_root': True, 'root_dir': 'home/$USER/', 'trust_xheaders': True, 'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue {'update': {'jupyterlab_code_formatter': True, 'nbclassic': True, 'notebook_shim': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2022-07-20 16:31:33.084 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-07-20 16:31:33.084 ServerApp] jupyterlab_code_formatter | extension was successfully linked.
[D 2022-07-20 16:31:33.096 NotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'allow_credentials': True, 'allow_origin': '*', 'allow_remote_access': True, 'allow_root': True, 'root_dir': 'home/$USER/', 'trust_xheaders': True, 'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyterlab_code_formatter': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2022-07-20 16:31:33.097 ServerApp] nbclassic | extension was successfully linked.
[I 2022-07-20 16:31:33.102 ServerApp] Writing Jupyter server cookie secret to /home/$USER/.local/share/jupyter/runtime/jupyter_cookie_secret
[D 2022-07-20 16:31:33.630 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/$USER/.jupyter/jupyter_notebook_config.json
[D 2022-07-20 16:31:33.630 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /etc/jupyter/jupyter_notebook_config.json
[D 2022-07-20 16:31:33.631 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2022-07-20 16:31:33.632 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/$USER/$VENV/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
        /home/$USER/$VENV/etc/jupyter/jupyter_notebook_config.d/jupyterlab_code_formatter.json
        /home/$USER/$VENV/etc/jupyter/jupyter_notebook_config.json
[D 2022-07-20 16:31:33.634 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/$USER/.jupyter/jupyter_notebook_config.json
[I 2022-07-20 16:31:33.634 ServerApp] notebook_shim | extension was successfully linked.
[D 2022-07-20 16:31:33.635 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'NotebookApp': {}, 'ServerApp': {'allow_credentials': True, 'allow_origin': '*', 'allow_remote_access': True, 'allow_root': True, 'root_dir': 'home/$USER/', 'trust_xheaders': True, 'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyterlab_code_formatter': True, 'nbclassic': True, 'notebook_shim': True}>}}
[I 2022-07-20 16:31:33.701 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-07-20 16:31:33.703 LabApp] JupyterLab extension loaded from /home/$USER/$VENV/lib/python3.8/site-packages/jupyterlab
[I 2022-07-20 16:31:33.703 LabApp] JupyterLab application directory is /home/$USER/$VENV/share/jupyter/lab
[I 2022-07-20 16:31:33.707 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-07-20 16:31:33.707 ServerApp] jupyterlab_code_formatter | extension was successfully loaded.
[I 2022-07-20 16:31:33.721 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-07-20 16:31:33.733 ServerApp] Serving notebooks from local directory: /home/$USER
[I 2022-07-20 16:31:33.733 ServerApp] Jupyter Server 1.18.1 is running at:
[I 2022-07-20 16:31:33.733 ServerApp] http://localhost:8888/lab?token=cf276333ab58d3b9c25408d7a17a03deced89831f4cac979
[I 2022-07-20 16:31:33.733 ServerApp]  or http://127.0.0.1:8888/lab?token=cf276333ab58d3b9c25408d7a17a03deced89831f4cac979
[I 2022-07-20 16:31:33.733 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-07-20 16:31:33.765 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/$USER/.local/share/jupyter/runtime/jpserver-64470-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=cf276333ab58d3b9c25408d7a17a03deced89831f4cac979
     or http://127.0.0.1:8888/lab?token=cf276333ab58d3b9c25408d7a17a03deced89831f4cac979

</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
jlab_core.fc632a0f38747f007842.js?v=fc632a0f38747f007842:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.fc632a0f38747f007842.js?v=fc632a0f38747f007842:2
272.3fcd6d7045eecfb56da6.js:1 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm did not respond in time
(anonymous) @ 272.3fcd6d7045eecfb56da6.js:1
/jupyter/user/$USER/api/contents?content=1&1658355138541:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
/jupyter/user/$USER/api/sessions?1658355138542:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
/jupyter/user/$USER/api/kernels?1658355138543:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
/jupyter/user/$USER/api/terminals?1658355139405:1          Failed to load resource: the server responded with a status of 403 (Forbidden)

</pre>

Running "JSON.parse(document.getElementById('jupyter-config-data').textContent).token" in the Chrome console prints a non-empty string. Running "document.cookie.indexOf('_xsrf')" prints 0

</details>

**Comment by jweill-aws** [comment]
Thanks for your issue! Are you sure that this is an issue in JupyterLab and not with JupyterHub (either generally or as configured by your admins)? Do you see similar behavior when using JupyterLab locally, without JupyterHub? Does the user as which JupyterHub is running have appropriate permissions to write to the hub's local file system?

**Comment by gdebrun2** [comment]
> Thanks for your issue! Are you sure that this is an issue in JupyterLab and not with JupyterHub (either generally or as configured by your admins)? Do you see similar behavior when using JupyterLab locally, without JupyterHub? Does the user as which JupyterHub is running have appropriate permissions to write to the hub's local file system?

Yes, my user profile does have write permissions. I have no issue running Jupyterlab locally. I'll reach out to my admins and see if they can provide more information

**Comment by jweill-aws** [comment]
@gdebrun2 Thanks for the update! Please let me know if this is still an issue. This might be an issue with JupyterHub configuration.

**Comment by jweill-aws** [comment]
@gdebrun2 I'm going to close this issue for now, but if you continue to see it, please reopen with more details. Thanks!
