### ISSUE TITLE
%debug autofocus

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#12846]
## Description

When a user types `%debug` the the cursor used to move to the ipdb prompt. It no longer does this in 3.4.3. This works as expected in 3.3.0.

## Reproduce
3.3.0
![ipdb-3 3 0](https://user-images.githubusercontent.com/1813603/180501676-9217752e-046f-454b-8d64-92493868e8ba.gif)
3.4.3
![ipdb-3 4 3](https://user-images.githubusercontent.com/1813603/180501705-d090be79-eadf-46ba-889a-7e64dd54af9d.gif)

**Comment by krassowski** [comment]
I can no longer reproduce this on 3.4.4. I think that https://github.com/jupyterlab/jupyterlab/pull/12735 may have fixed it. Would you mind checking if it works ok now?
