### ISSUE TITLE
Cursor not visible with dark theme

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#12859]
## Description

With JupyterLab HEAD and the dark theme, the cursor is not visible:

https://user-images.githubusercontent.com/4711805/180956257-958e35ef-399a-4b67-8ffa-1168477a2dd5.mp4

## Reproduce

1. Install JupyterLab HEAD
2. Open a notebook
3. Choose the dark theme
4. See that the cursor is not visible
5. Switch to light theme and see that the cursor is visible

## Expected behavior

The cursor should be visible in dark theme.

**Comment by jweill-aws** [comment]
This was also seen in #12764.

**Comment by fcollonval** [comment]
Closing as working in 769a4d4

![image](https://user-images.githubusercontent.com/8435071/233398278-4269e42c-8576-4be0-8ddb-e4b67294482f.png)
