### ISSUE TITLE
blank page! error msg: ChunkLoadError: Loading chunk 3472 failed

### ISSUE THREAD

**Issue by GinSoda** [jupyterlab/jupyterlab#12864]
Open jupyterlab in Chrome as client, find blank page.
Open F12, then find "Chunk LoadError: Loading chunk 3472 failed." error.
![chrome wrong msg](https://user-images.githubusercontent.com/13716926/181173401-64b9ee4e-3003-4349-8dc7-acf60d370f4b.png)

Chrome version: 103.0.5060.134
JupyterLab version: 3.4.4
OS: Windows 11

Other message:
Other colleague can open jupyterlab normally in the same Chrome version、same JupyterLab server.

Solution:
Use Firefox works well.

**Comment by jweill-aws** [comment]
Because this issue seems to be limited to your instance of Chrome, have you tried:

1. Clear your Chrome cache and reload JupyterLab
2. Disable all Chrome extensions that may interfere with content loading (including ad blockers)

**Comment by jweill-aws** [comment]
This seems to be a browser issue specific to your configuration. If you can reproduce this using a version of Chrome with no extensions running, please reopen. Thanks!

**Comment by jhgoebbert** [comment]
Any network hiccup can cause a ChunkLoadError.  
I wonder if it could be a solution to implement a retry mechanism. For example using this webpack-plugin:  
https://github.com/mattlewis92/webpack-retry-chunk-load-plugin
