### ISSUE TITLE
Notebooks kernel died

### ISSUE THREAD

**Issue by hankgreurrayosin** [jupyterlab/jupyterlab#12860]
Hello, everyone. When I run code in notebook, there is a prompt of kernel death. What's going on?

![image](https://user-images.githubusercontent.com/109416378/180998573-e622df75-4ec6-4b57-8f46-6606fb801b2c.png)

**Comment by davidbrochart** [comment]
Hi @hankgreurrayosin, it could be that the code you are executing blows up the memory, for instance. If you can post the code, we could help you diagnose the issue.

**Comment by hankgreurrayosin** [comment]
ok，
````
import os
if os.path.isfile('../data/pg1553.tar.gz'):
    !tar xzf ../data/pg1553.tar.gz
else:
    !curl -OL https://raw.githubusercontent.com/fermiPy/fermipy-extras/master/data/pg1553.tar.gz
    !tar xzf pg1553.tar.gz
````
if os.path.isdir('../data'):
    os.environ['DATADIR'] = '../data'
else:
    !mkdir pg1553/data
    !mkdir pg1553/data/ft1
    !mkdir pg1553/data/ft2
    os.environ['DATADIR'] = 'pg1553/data'
    !curl -o pg1553/data/ft1/L1504241622054B65347F25_PH00.fits -OL https://raw.githubusercontent.com/fermiPy/fermipy-extras/master/data/ft1/L1504241622054B65347F25_PH00.fits
    !curl -o pg1553/data/ft1/L1504241622054B65347F25_PH01.fits -OL https://raw.githubusercontent.com/fermiPy/fermipy-extras/master/data/ft1/L1504241622054B65347F25_PH01.fits

    
#!curl -o pg1553/L1504241622054B65347F25_PH00.fits http://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/data/pyLikelihood/L1504241622054B65347F25_PH00.fits
#!curl -o pg1553/L1504241622054B65347F25_PH01.fits http://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/data/pyLikelihood/L1504241622054B65347F25_PH01.fits
#!curl -o pg1553/L1504241622054B65347F25_SC00.fits http://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/data/pyLikelihood/L1504241622054B65347F25_SC00.fits
````
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib
import numpy as np

````
When I code in the line of notebooks, I report an error
from fermipy.gtanalysis import GTAnalysis
gta = GTAnalysis('pg1553/config.yaml',logging={'verbosity': 3})
matplotlib.interactive(True)
````

**Comment by davidbrochart** [comment]
Can you try commenting out the last line?
```py
matplotlib.interactive(True)
```
It could the one killing the kernel because data to plot is too big.

**Comment by hankgreurrayosin** [comment]
ok,thank you. @davidbrochart

**Comment by davidbrochart** [comment]
OK, I don't know this library, but glad to know that you spotted the issue!

**Comment by hankgreurrayosin** [comment]
OK，thank you!
