### ISSUE TITLE
A checklist to see what features have already been implemented in JupyterLab notebook

### ISSUE THREAD

**Issue by Analect** [jupyterlab/jupyterlab#1287]
On @blink1073 suggestion over [here](https://github.com/jupyter/nbformat/issues/66#issuecomment-262253133).

I'm testing jupyterlab within jupyterhub and have a development version (master) of the notebook running within jupyterlab.

I was trying to get markdown cell attachments (an embedded image) working, but it turns out it hasn't yet been implemented in the notebook within jupyterlab.  It's also not possible to edit cell meta-data from within the notebook. Meanwhile, other functionality like cell drag/drop and multi-cell selection is working.

It would be great to have a checklist somewhere of what aspects of notebook classic have been implemented within the notebook on jupyterlab. I realise jupyterlab is still alpha and that a stated objective of jupyterlab is to achieve parity with the classic version before shifting to beta/1.0 status.  I'm also aware of the general roadmap [here](https://github.com/jupyter/roadmap/blob/master/notebook.md), but the check-list I'm suggesting would be at a more granular level below this, perhaps.

**Comment by blink1073** [comment]
Thanks for following up, @Analect!

**Comment by jasongrout** [comment]
I think at this point, it would be easier to list the features not implemented yet, as separate issues, with the `cat:Feature Parity` and `component:Notebook` tags. That way the list is automatically kept up to date as we implement things and close the relevant issues: https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aopen+is%3Aissue+label%3A%22cat%3AFeature+Parity%22+label%3Acomponent%3ANotebook

What do you think?

**Comment by blink1073** [comment]
That sounds good, as a link in the roadmap.

**Comment by jasongrout** [comment]
+1. How about we settle this issue with a link in the roadmap to the query, and an invitation to submit more an issue if you see something that is lacking.

**Comment by Analect** [comment]
Thanks @blink1073 @jasongrout 
I suppose your approach of labeling outstanding issues could work, but it presumes that someone knows what's missing and has gone to the trouble of generating an appropriate issue. I don't know the Jupyter code-base well enough to figure that out, but would be prepared to help if someone pointed me in the right direction.

There's a pre-existing issue pertaining to a cell tool-bar [here](https://github.com/jupyterlab/jupyterlab/issues/902).  I'm not sure whether or not that generically covers my use-cases:
a. to get markdown cell attachments (an embedded image) working within notebook on jupyterlab
b. a means of viewing/editing custom meta-data on a cell as referenced [here](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/notebook.js#L504).

I can add these as separate issues, if you think that's advisable, although I don't think I have an ability to set labels.

**Comment by blink1073** [comment]
We had previously attempted to manually curate a feature parity list in https://github.com/jupyter-attic/jupyter-js-notebook/issues/87, but checklists in github issues as well as lists in wiki pages get out of date and sync very quickly. 

 It is unfortunate that you can't add labels to your own issues, but we have been doing a fairly good job of adding and using the labels consistently as a team.  

I think with the right messaging on the roadmap and perhaps as part of an issue template like "please add this as a notebook feature parity issue" would go a long way.

**Comment by blink1073** [comment]
I've updated the roadmap in https://github.com/jupyter/roadmap/issues/33 and made sure we've captured all of the existing feature parity issues, and calling this one addressed.  Please feel free to reopen if you disagree, @Analect.

**Comment by Analect** [comment]
Thanks @blink1073 . Much appreciated.
I added #1398 ... which I don't think was being captured elsewhere ... although it may overlap with other issues that may tackle broad cell-based UI issues ... feel free to remove if you think it's captured elsewhere.
