### ISSUE TITLE
Getting Error while starting jupyter lab

### ISSUE THREAD

**Issue by NitinBhasneria01** [jupyterlab/jupyterlab#12887]
![image](https://user-images.githubusercontent.com/107836085/182022073-fbd30387-b0a6-45f1-9331-ad4e03463903.png)

**Comment by davidbrochart** [comment]
Hi @NitinBhasneria01, this could happen when you start JupyterLab, open a notebook, stop the server (in the terminal), and launch JupyterLab again (without closing your browser window). In this case, the old client (browser window) still makes requests, not knowing it's a different server.
Could it be your case?

**Comment by NitinBhasneria01** [comment]
Thank you @davidbrochart. This works. Actually I am trying to import pandasgui in jupyter-lab, but getting this error.
Can you please help
![image](https://user-images.githubusercontent.com/107836085/182027280-e728b401-ef64-46ca-bdc0-e392abedc40c.png)

**Comment by davidbrochart** [comment]
I installed it through conda-forge (couldn't install it with `pip`):
```bash
mamba create -n pandasgui
mamba activate pandasgui
mamba install jupyterlab pandasgui pyqtwebengine
```
It works fine on my side:

https://user-images.githubusercontent.com/4711805/182027908-ac21f056-6a2d-4a97-9dfe-b0a607494094.mp4

How did you install it?

**Comment by NitinBhasneria01** [comment]
I installed it with pip.

**Comment by davidbrochart** [comment]
I'm suspecting you have some low-level binary incompatibility, I suggest installing through conda-forge.

**Comment by NitinBhasneria01** [comment]
> I'm suspecting you have some low-level binary incompatibility, I suggest installing through conda-forge.

Ok, trying with conda-forge

**Comment by davidbrochart** [comment]
Yes, you can download `mamba` for your platform here: https://github.com/conda-forge/miniforge/releases.

**Comment by NitinBhasneria01** [comment]
@davidbrochart you know anything about this error:
![image](https://user-images.githubusercontent.com/107836085/182029382-d0fda504-7b1f-43be-a268-5c01c082d289.png)

**Comment by NitinBhasneria01** [comment]
Getting same thing
![image](https://user-images.githubusercontent.com/107836085/182031393-c64d6ef1-fa26-43b0-89e9-be3224c78ec5.png)

**Comment by NitinBhasneria01** [comment]
Jupyter Logs


![image](https://user-images.githubusercontent.com/107836085/182031750-977a13fd-30b8-422e-97e2-a75266155b18.png)
![image](https://user-images.githubusercontent.com/107836085/182031758-abb8ac01-0394-4fa6-8522-82c877fb38ff.png)

**Comment by jweill-aws** [comment]
@NitinBhasneria01 So that your errors are indexed for search purposes, please share text output in a code block rather than as a screen shot. You can prevent formatting by placing <code>```</code> on a line before and after your text output.

I noticed your last two screen shots are from within Visual Studio Code. Are you trying to run Jupyter Server from within VS Code? What happens if you follow our setup guide from a standalone terminal outside of VS Code?

**Comment by jweill-aws** [comment]
@NitinBhasneria01 Can you please provide more info about how you're trying to run JupyterLab? Are you running it from a standalone terminal or from within VS Code?

**Comment by jweill-aws** [comment]
@NitinBhasneria01 I haven't heard from you in a couple of weeks now, so I'm going to close this issue. Please reopen if you have any info to add.
