### ISSUE TITLE
Showing small case in showing the shortcuts

### ISSUE THREAD

**Issue by yashpalgoyal1304** [jupyterlab/jupyterlab#12883]
### Problem

* The keyboard shortcuts listed are in all small case

<img src="https://user-images.githubusercontent.com/19423063/181906648-e64b3296-1104-4913-b369-84f0c674ec44.png" height=300px>

* This can be confusing as:
* Jupyter lab is also keyboard oriented/modal in its operations (thanks a lot for it 😇), and
* Many other keyboard oriented softwares use case sensitive letters to show their shortcuts, as in:

| Currently Shown | Proposed       | short notations<br/>in other s/w |
| --------------- | -------------- | -------------------------------- |
| `D`             | `d`            | `d`                              |
| `Ctrl+D`        | `Ctrl+d`       | `^d`                             |
| `Shift+D`       | `Shift+d`      | `↑d` or `D`                      |
| `Ctrl+Shift+D`  | `Ctrl+Shift+d` | `^↑d` or `^D`                    |

### Proposed Solution

The shortcuts to be shown in small case

* I am obviously not saying to go as far as the adopting the case sensitve and complete shorthand notation, 
* but using the small case in the normal notation will help a lot in dealing with the confusion for those who are familiar to that

**Comment by jweill-aws** [comment]
We're following the guidance of other software vendors, such as Apple, which use the uppercase letters because those match the letters typically printed on a keyboard. Example: https://developer.apple.com/design/human-interface-guidelines/inputs/keyboards#keyboard-shortcuts . This pull request concerns Jupyter's behavior in this regard: https://github.com/jupyterlab/lumino/pull/258#pullrequestreview-795964229

Thank you for your suggestion.

**Comment by yashpalgoyal1304** [comment]
1. thanks alot for the conclusive input and linking relevant discussions
2. it further supports my hypothesis that win/mac/android are just there to
keep users dumb lol, its sad that they are also the popular ones, bunch of
dead spirit OS.
3. now that it's done, can u remove the label `status:Needs Triage` ?

**Comment by yashpalgoyal1304** [comment]
yeah, got reminded that those notations are called caret notation (for control characters), and there's also emacs notation.

found while searching for https://github.com/TeamNewPipe/NewPipe/pull/9471
