### ISSUE TITLE
JSON editor broken on 3.4.4

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#12891]
## Description

As reported in https://stackoverflow.com/questions/73191368/json-settings-editor-in-jupyterlab-not-working JSON Settings Editor stopped working. I was able to independently reproduce it on 3.4.4. It works perfectly on 3.4.3.

## Reproduce

1. Open Settings Editor
2. JSON Settings Editor
3. See nothing opens
4. See TypeError in browser console:

```
Uncaught (in promise) TypeError: setting getter-only property "handleMoved"
```

it is raised from transplied:

https://github.com/jupyterlab/jupyterlab/blob/f5ecbf1c0c3209892f4bf6ede4b4c8bc15d8b9e1/packages/settingeditor/src/splitpanel.ts#L13-L17

which at runtime ends up being:

```js
class M extends s.SplitPanel {
    constructor() {
        super(...arguments);
        this.handleMoved = new i.Signal(this)
    }
    handleEvent(e) {
        super.handleEvent(e);
        if (e.type === "mouseup") {
            this.handleMoved.emit(undefined)
        }
    }
}
```

and likely a consequence of merging https://github.com/jupyterlab/lumino/pull/301 which had an accompanying PR on the development branch (https://github.com/jupyterlab/jupyterlab/pull/12593) but not a compatibility fix on 3.4 branch. It was not immediately needed as the `@lumino/widgets` version was not bumped on 3.4.x up until https://github.com/jupyterlab/jupyterlab/pull/12777 which was meant to pull in memory leak fixes. 

## Expected behavior

JSON Settings Editor opens.

## Context

- Browser and version: Firefox
- JupyterLab version: 3.4.4

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/12892

**Comment by jablka** [comment]
hello, 
are you sure that this is fixed?
I just installed the JupyterLab via `pip`, 
went to:
`Settings | Advanced Settings Editor` and then `JSON Settings Editor`
and this is what I get:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/20874763/204316031-5c0731d8-e7ec-45dc-982b-da9e2658d0e1.png">

Even when I try it online at https://jupyter.org/try-jupyter/lab/ 
<img width="753" alt="image" src="https://user-images.githubusercontent.com/20874763/204317366-bff7fb97-80ee-4d18-8ab0-fdc504640f09.png">
