### ISSUE TITLE
Update JupyterLab docs to remove references to jupyter_notebook_config

### ISSUE THREAD

**Issue by st-bender** [jupyterlab/jupyterlab#12897]
Sorry if that is answered somewhere, but a quick search and the FAQ did not turn anything up.

## Description

After updating jupyterlab to 3.4.4, trying to start jupyter(lab) suddenly ignores my `https` configuration setting
and insists on usign plain `http` with a token. I could not find any documentation how to reconcile the previous behaviour,
any pointer would be appreciated.

Edit: I forgot to add that I used `https` and a password for jupyterlab.

## Reproduce

1. Start `jupyter lab --no-browser`

No `https` connection.

## Expected behavior

`https` connection provided as before.

**Comment by jweill-aws** [comment]
Can you provide more info about how you enabled `https` in the configuration? What version were you using before? What server version are you using? The output of `jupyter --version` can help us diagnose your current setup.

**Comment by st-bender** [comment]
Hi,
I think it is a documentation issue, it looked like the latest `jupyter` ignored my configuration completely, and missing https was just the most obvious "failure".
I noticed that the internal handling changed, and apparently someone had the impeccable idea the rename also the configuration files from `jupyter_notebook_config.*` to `jupyter_server_config.*`. Just renaming/copying helped, but it would have been nice to try also the old name in case the new "standard" one can not be found.
It is always a bit frustrating to encounter such surprises after upgrades.

Cheers.

Fyi, `jupyter --version`:
```
Selected Jupyter core packages...
IPython          : 8.4.0
ipykernel        : 6.15.1
ipywidgets       : 7.7.1
jupyter_client   : 7.3.4
jupyter_core     : 4.11.1
jupyter_server   : 1.18.1
jupyterlab       : 3.4.4
nbclient         : 0.6.6
nbconvert        : 6.5.0
nbformat         : 5.4.0
notebook         : 6.4.12
qtconsole        : 5.3.1
traitlets        : 5.3.0
```

**Comment by jweill-aws** [comment]
@st-bender You are correct in that `jupyter_notebook_config` is no longer used. This is because `nbserver` is no longer a dependency, as documented here: https://github.com/jupyter/nbclassic/issues/136

There is documentation about migrating from nbserver here: https://jupyter-server.readthedocs.io/en/latest/operators/migrate-from-nbserver.html

With that said, `jupyter_notebook_config` is still present in JupyterLab's documentation for the newest version; this is a bug. The following pages need to be updated:

* https://jupyterlab.readthedocs.io/en/stable/user/directories.html
* https://jupyterlab.readthedocs.io/en/stable/getting_started/faq.html

This has come up several times before, so the FAQ itself should make reference to migrating off of the old config file location.

Thank you for bringing this issue to our attention!

**Comment by st-bender** [comment]
Hi,
Thanks for the reply. The migration link is very useful, but apparently hard to find. I guess it would be good if it were part of the FAQ.

That being said, I still think it wouldn't hurt to also accept the "old" configuration file even though the dependencies changed. In the end it is just a file name and would probably ease the transition for users. One could even print a (deprecation) warning, or was there one and I missed it?

Cheers.

**Comment by echarles** [comment]
https://github.com/jupyter/nbclassic/pull/137 rolls back `nbclassic` to use `jupyter_notebook_config.py`. We still need to release that patch. Once done, jupyterlab could depend on the latest nbclassic, and in that case, the configs you will put in `jupyter_notebook_config.py` will be read and applied again.

**Comment by st-bender** [comment]
@echarles 
Thanks for the work.
I am not sure what that implies. Will it then read both files? And which one will take precendence?
Adding another dependence for reading a config file seems a lot of trouble to me.
Couldn't `jupyter_server` be made to read `jupyter_notebook_config` in case `jupyter_server_config` does not exist, and print a warning to the user?

Cheers.

**Comment by echarles** [comment]
> I am not sure what that implies. Will it then read both files? And which one will take precendence?

Talking on nbclassic, only one file is read (jupyter_nbclassic_config or jupyter_notebook_config depending on the version, we are documenting that behavior ATM).

> Adding another dependence for reading a config file seems a lot of trouble to me.

Those dependencies should be installed for you if you install jupyterlab.

> Couldn't jupyter_server be made to read jupyter_notebook_config in case jupyter_server_config does not exist, and print a warning to the user?

The traits defined in jupyter_notebook are automatically converted (with warning in the log) to jupyter_server traites

**Comment by jtpio** [comment]
> jupyterlab could depend on the latest nbclassic

Not sure about this. The whole point of https://github.com/jupyterlab/jupyterlab/pull/11894 was to finally be able to drop the dependency on the deprecated classic notebook and unblock the development on Notebook v7.

**Comment by krassowski** [comment]
Either way getting the shims now could change the behaviour for users how migrated to `jupyter_server_config` if they have not deleted their `jupyter_notebook_config`. If the old `jupyter_notebook_config` had disabled password/token authentication and the new `jupyter_server_config` did not explicitly re-enable it and both are loaded this would could be a serious issue. More frequently it will be just confusing for users who were previously told to use `jupyter_server_config`. 

If we want to bring the shims back in, it should be well though-though, communicated and ideally in a major release.

**Comment by st-bender** [comment]
Hi,
I am sorry to have brought this up.
@krassowski my idea is more like the following:
- read `jupyter_server_config` if it exists and start with it.
- **only if** there is **no** `jupyter_server_config`, look if there is a `jupyter_notebook_config` that can be used and use that.

In short, *don't* use both.
I don't know if that approach is feasible. If not, the documentation should be made more clear and easier to find. Apparently I had trouble to find the right place, but needed to be pointed to it by @jweill-aws.

Cheers.
