### ISSUE TITLE
My jupyter lab can not lauch classic notebook

### ISSUE THREAD

**Issue by ltqb** [jupyterlab/jupyterlab#12908]
## Description

hello team,
Here is my jupyter information
```
IPython          : 7.34.0
ipykernel        : 6.6.0
ipywidgets       : 7.6.5
jupyter_client   : 7.3.4
jupyter_core     : 4.10.0
jupyter_server   : 1.15.6
jupyterlab       : 3.2.5
nbclient         : 0.5.13
nbconvert        : 6.3.0
nbformat         : 5.4.0
notebook         : 6.4.6
qtconsole        : not installed
traitlets        : 5.3.0
```
Can you help take a look at ? thanks

## Reproduce

1. Go to 'Help'
2. Click on 'Launch Classic Notebook'
3. See error '404'
<img width="617" alt="Screen Shot 2022-08-04 at 2 46 21 PM" src="https://user-images.githubusercontent.com/48326717/182781470-da8d448d-b22d-4de7-9380-947f152d2fba.png">

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by jweill-aws** [comment]
Can you reproduce this using a newer version of JupyterLab? The newest supported version is 3.4.4, which is designed to work with Notebook 6.

Also, which URL is that menu item sending you to that results in a 404 error?

**Comment by ltqb** [comment]
hi, I have resolved it by downgrade this python package nbclassic  to  0.3.4 and  uninstall notebook-shim.Thank you for your  quick  response.

**Comment by jasongrout** [comment]
Thanks for following up.
