### ISSUE TITLE
Is it possible that there is memory leak in JupyterLab WebAPP?

### ISSUE THREAD

**Issue by nimengliusha** [jupyterlab/jupyterlab#12901]
While open JupyterLab(v3.2.3) page, chrome browser occasionally prompts insufficient memory as below : 

![image](https://user-images.githubusercontent.com/31717221/182513094-808398d7-a8a3-4f2b-a073-d8da24b41b03.png)

But PC has 32GB memory and chrome costs little

**Comment by krassowski** [comment]
Yes. The latest release (https://github.com/jupyterlab/jupyterlab/releases/tag/v3.4.4 at the time of writing) fixed a number of memory leaks (https://github.com/jupyterlab/jupyterlab/pull/12750, https://github.com/jupyterlab/jupyterlab/pull/12774). However, it is more likely that the problem you see could be related to an extension that you are using.

If you experience this issue after an upgrade to the latest version (v3.4.4), please provide a list of extensions you use and I can take a look.

**Comment by nimengliusha** [comment]
Thanks~

**Comment by nimengliusha** [comment]
Thanks

**Comment by jasongrout** [comment]
Another possibility is that it might be loading a file to view (like a very large CSV file), which could exhaust the memory.
