### ISSUE TITLE
Please fix logging color on windows console

### ISSUE THREAD

**Issue by char101** [jupyterlab/jupyterlab#12917]
## Description

It seems that jupyter uses `tornado.log` for logging. In the comment of [tornado.log](https://github.com/tornadoweb/tornado/blob/master/tornado/log.py#L96) it is written

```
Color support on Windows versions that do not support ANSI color codes is
enabled by use of the colorama__ library. Applications that wish to use
this must first initialize colorama with a call to ``colorama.init``.
See the colorama documentation for details.
```

Unfortunately `colorama.init()` is never called by jupyter causing logging ANSI color to be output as raw escape codes.

## Reproduce

1. Run jupyter lab
2. Log shows raw ANSI escape sequences for color `←[2;32m[I 2022-08-07 18:50:14.236 ServerApp]←[0m`

## Expected behavior

Colored log in windows console.

## Context

- Operating System and version: Windows 10
- Browser and version: N/A
- JupyterLab version: 3.4.4

## Resolution

If possible please add `colorama.init()` in the main code

```python
try:
    import colorama
    colorama.init()
except ImportError:
    pass
```

**Comment by afshin** [comment]
@char101 Thanks for opening this issue! I've cross-posted it in the `jupyter_server` repo because I think it may be solvable at that level of the stack: https://github.com/jupyter-server/jupyter_server/issues/943

**Comment by jweill-aws** [comment]
Closing this issue in favor of the Jupyter Server issue @afshin mentioned above. Please reopen if this should be fixed in JupyterLab.
