### ISSUE TITLE
Galata test tool adds unhelpful async/await conditions to page.reload method, rendering it far less useful.

### ISSUE THREAD

**Issue by pauldruce** [jupyterlab/jupyterlab#12924]
## Description

The Playwright method for refreshing the browser page has been overwritten in Galata in the following file:
https://github.dev/jupyterlab/jupyterlab/blob/master/galata/src/jupyterlabpage.ts#L479

The method page.reload() now expects the Launcher to be visible, meaning any tests wanting to refresh the browser can no longer do so in any reasonable way. 

![image](https://user-images.githubusercontent.com/30435358/183685203-388ba295-6184-4409-8a85-5bf495d07efe.png)

## Expected behaviour

I don't see any reason for the reload method to be modified. 
So the expected behaviour is that page.reload() should only reload the page. 
It should not reload the page, then check that the splash screen and the launcher are visible. 

### My workaround for anyone who may see this issue

You can get access to original playwright reload method with the following `context.pages()[0].reload();`. Just make sure to pass `context` into your tests.

**Comment by jweill-aws** [comment]
We may be able to accommodate this by renaming the `reload` method to its actual purpose of "reload and wait for splash screen and launcher." That would allow for the creation of a simpler `reload` method that only performs a browser reload without waiting for any components.

**Comment by fcollonval** [comment]
@pauldruce if you are willing to open a PR, a better path (than the previous suggestion) is to add a new optional argument `waitForIsReady = true`. If it is false, the `await this.waitIsReady` will be skipped.

I would consider it a bug fix and happy to make a release when it is merged.

> This is a better fix because galata relies on Javascript assets being loaded in the webpage (done in `hookHelpersUp`). So accessing the raw reload will skip that and some galata features won't work.
