### ISSUE TITLE
JupyterLab sidebar tree does not automatically change directory to the current notebook

### ISSUE THREAD

**Issue by KwatMDPhD** [jupyterlab/jupyterlab#12940]
It should auto-focus on the active notebook.

**Comment by krassowski** [comment]
I see that you closed the issue just before the triage meeting. Just for reference there is an option to enable showing active file in browser (menu bar `Settings` → `Show Active File in File Browser`). If you had this enabled an it did not wok, that would be a bug, but we would need more information (the bug template properly filled in)
