### ISSUE TITLE
Support resizing image in output

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#1294]
Sometime we need to resize images to get the best effect, however, JupyterLab doesn't support resizing image currently. It's appealing for JupyterLab to  

1. support resizing images
2. use the resized dimension info when the visualization code is rerun

**Comment by blink1073** [comment]
Hi @dclong, thank you for the report.  This is related to #661.

**Comment by jasongrout** [comment]
Is this a feature parity issue? I didn't know this was possible in the current notebook.

**Comment by blink1073** [comment]
I had assumed this was related to the [IPython.display](http://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html?highlight=display#IPython.display.Image) options, is that what you meant @dclong?

**Comment by dclong** [comment]
@blink1073,

Sorry for the vague description. What I want was being able to resize image interactively rather than calling options commands. The reason is that whether a plot looks good often depends on its size. We often don't know the best sizes to uses for images until we play with (resize) them.

**Comment by blink1073** [comment]
Ah, thank you for clarifying.  I'm changing this to an enhancement request since it is not available in the classic notebook.

**Comment by jasongrout** [comment]
We might be able to implement dynamic resizing of output images, but the size information wouldn't be communicated back to the backend to affect future plot sizes. I'd suggest using a plotting library that tries to implement this dynamic resizing (for example, bqplot can resize to take up an area, though I don't think it currently lets you drag to a new size).

**Comment by jasongrout** [comment]
Also, note that you can create a new view of an output in a new jlab tab, and then resize that tab to get different sizes. That is used, for example, in widgets and ipyleaflet to get different sizes for the outputs.
