### ISSUE TITLE
Provide galata support for logging in to a JupyterLab session

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab/jupyterlab#12945]
Jupyter notebook and JupyterLab defaults encourage the use of authentication to access the server. However, the galata test framework expects to run against a server that is wide open / no authentication.

For users in education, at least, galata may be attractive for:

- testing student deployments;
- generating videos of various interactions.

However, the test environments are likely to require authentication.

It would be useful if galata could be extended to optionally allow testing to start with the passing of credentials via the Jupyter authentication page.

Related: https://discourse.jupyter.org/t/using-galata-jupyterlab-ui-test-framework-with-token-password-enabled-sites/15106

**Comment by fcollonval** [comment]
Supporting logging in a generic way is very complicated as there are plenty of possible authentication workflow. So information are given in Playwright documentation: https://playwright.dev/docs/test-auth#reuse-the-signed-in-page-in-multiple-tests.

Could you try setting up an authentication process with Playwright and paste the code here? So we can try to find new APIs to support it.

> Galata is using the [Page Object Model](https://playwright.dev/docs/test-pom) feature of Playwright. It is possible to apply the same feature to customize it for your need:

https://github.com/jupyterlab/jupyterlab/blob/09051b45f33655712ae483631b87e5f856a7b823/galata/src/fixtures.ts#L330

**Comment by psychemedia** [comment]
With a default Jupyter login page, the following will log a user into a session that is running with a predefined token set to `test`:

```python
```python
from playwright.sync_api import Page, expect

# jupyter on 8877 with password: test

def test_initial_load(page: Page):
    page.goto("http://127.0.0.1:8877/")
    page.locator('#password_input').fill('test')
    page.locator('button#login_submit').click()
    # Is there a better way to wait for things to load?
    page.wait_for_url("http://127.0.0.1:8877/lab")
    page.screenshot(path="jupyterlab-screenshot.png")
```
```

**Comment by fcollonval** [comment]
Thanks @psychemedia 

I figure out how to use the cookies storage to support authentication; see #13015. But we will need to carry out a patch release to support it in the direct API calls that are used within galata helpers.
