### ISSUE TITLE
Should kernel info be included in notebook signature computation?

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#12955]
### Problem
At present, when computing the signature of a notebook, the `compute_signature` function ([ref](https://github.com/jupyter/nbformat/blob/main/nbformat/sign.py#L421)) takes into consideration the kernel info. I believe this shouldn't be done because it has no effect on the safety of the output. 

### Proposed Solution

If there is no reason to include kernel info while computing the notebook signature then it should be stripped out. 

### Additional context
In our use-case we have a custom contents manager that can be used to access notebooks from a remote host in a read-only mode. Now, if the original notebook was authored with say `kernel1` then opening that in a host which doesn't have a kernel named `kernel1` makes the notebook untrusted.

**Comment by afshin** [comment]
I opened [an issue in the `jupyter/nbformat` repo](https://github.com/jupyter/nbformat/issues/296) to track this in the relevant repo. Thanks for bringing this up, @divyansshhh. I'll close it here in favor of the `nbformat` issue.
