### ISSUE TITLE
.webp files do not open in 3.4.5

### ISSUE THREAD

**Issue by suganya-sk** [jupyterlab/jupyterlab#12961]
## Description

When I try to open a .webp file in JupyterLab 3.4.5, I get the following error -

![image](https://user-images.githubusercontent.com/19615498/185394780-8af52b14-df91-4481-9b08-0f878b685720.png)

(This is the same issue as reported in https://github.com/jupyterlab/jupyterlab/issues/12832)

The changelog for 3.4.5 mentions that the webp filetype has been added to the docRegistry; should we wait for any more changes to come in before such files can be viewed? Please advise.

## Context

- Browser and version: Chrome 103
- JupyterLab version: JupyterLab 3.4.5

**Comment by krassowski** [comment]
Confirmed. It seems that the patch which was merged was not properly tested. I think that we need to add the `image/webp` mimetype to:

https://github.com/jupyterlab/jupyterlab/blob/744bda9f29f49b41d3842dff3ce8d32b7f2a58e8/packages/rendermime/src/factories.ts#L21-L26

@suganya-sk would you like to open a pull request?

**Comment by suganya-sk** [comment]
Sure, I'll send in the PR by tomorrow.

**Comment by alec-kr** [comment]
Hey everyone. Is this issue still open? I'd like to make my first contribution.

**Comment by suganya-sk** [comment]
Apologies for the delay here; caught up in some other work @alec-kr please feel free to pick this up.

**Comment by suganya-sk** [comment]
Sorry, I dont seem to have the permissions to assign. May be one of the core members could do it?
