### ISSUE TITLE
memory leak for objects that implement _repr_html_

### ISSUE THREAD

**Issue by rkishony** [jupyterlab/jupyterlab#12969]
## Description

An object that implements `_repr_html_` is kept held by several internal referrers and does not get garbage collected. 

## Reproduce

<img width="417" alt="image" src="https://user-images.githubusercontent.com/62783755/185507927-8bd717eb-577e-4793-ac52-107a9f22f862.png">

Note that this behavior occurs whether or not _repr_html_ returns None or a string. 

Note also that such objects do get garbage collected if they are never displayed. 

## Expected behavior

Objects should get deleted.

## Context

- Operating System and version: MAC OS 10.15.7
- Browser and version: Chrome
- JupyterLab version: 

```
IPython          : 8.4.0
ipykernel        : 6.15.1
ipywidgets       : 7.7.1
jupyter_client   : 7.3.4
jupyter_core     : 4.11.1
jupyter_server   : 1.18.1
jupyterlab       : 3.4.5
nbclient         : 0.6.6
nbconvert        : 6.5.3
nbformat         : 5.4.0
notebook         : 6.4.12
qtconsole        : not installed
traitlets        : 5.3.0
```

**Comment by krassowski** [comment]
The origin of this behaviour is not in JupyterLab, but in the IPython. You can reproduce the same behaviour in IPython terminal/console without running JupyterLab.

Quoting my answer [elsewhere](https://stackoverflow.com/a/67398955/6646912) on related topic:

> The Python kernels (IPython and Xeus Python) come with a feature of remembering your input and output for each executed cell; it is useful if you execute a cell with compute-intensive task but forget to assign the result onto a variable, for example instead of:
> 
> ```
> result = do_long_calculation()
> ```
> 
> you do:
> 
> ```
> do_long_calculation()
> ```
> 
> in the latter case you can use the IPython underscore `_` variable which caches the last execution result to recover the output:
> 
> ```python
> result = _
> ```
> 
> If you already overwritten the most recent output, it the previous one goes to `__` and so on. Learn more about this in the [output caching system documentation](https://ipython.org/ipython-doc/3/interactive/reference.html#output-caching-system).
> Similarly `_i`, `_ii`, etc. variables cache most recent input of cells so you can check **what** has been executed. See more in [input caching system documentation](https://ipython.org/ipython-doc/3/interactive/reference.html#input-caching-system). There are also `In` and `Out` variables which store entire execution history for your reference.

The quoted [output caching system documentation](https://ipython.org/ipython-doc/3/interactive/reference.html#output-caching-system) described ways of removing the variables completely (currently via `%xdel` magic) and disabling the caching (currently by setting `InteractiveShell.cache_size` to 0).

**Comment by rkishony** [comment]
perfect. extremely helpful. much thanks!
