### ISSUE TITLE
Running terminal and kernels - Scrollable headers when sections are empty

### ISSUE THREAD

**Issue by firai** [jupyterlab/jupyterlab#12972]
## Description

The section headers in the "Running terminals and kernels" panel are slightly scrollable when the corresponding sections are empty. When the browser is set to use non-overlay scrollbars, scrollbars are visible. The scrollability of the headers and the scrollbars go away if the section is populated. Seems like the behavior might be caused by the hardcoded header height combined with `overflow: auto` in the section container.

**Edit:** This seems to only happen consistently in Firefox with default settings. It happened to me for particular builds inconsistently in Chrome with default font sizes (haven't figured out the pattern), but it also appears when the UI font size is increased.

![image](https://user-images.githubusercontent.com/23555/185653052-fa2c0aed-b50a-4a36-a7a2-9961ac550068.png)

## Reproduce

Open "Running terminal and kernels" with clean start-up.

## Expected behavior

No scrollbars at the headers.

## Context

- Operating System and version: Windows 11
- Browser and version: Chrome (104.0.5112.102) and Firefox (103.0.2)
- JupyterLab version: 3.4.5 and latest development version

**Comment by firai** [comment]
@meeseeksdev tag pkg:running

**Comment by jweill-aws** [comment]
Note for resolver: You should be able to fix this by increasing the `height` of the headers. Please test in Windows 11 using the browsers noted above.

**Comment by firai** [comment]
Rendered obsolete by #13074. It doesn't seem like anyone else noticed the issue anyway.
