### ISSUE TITLE
one of the labextensions failed will prevent jupyterlab display

### ISSUE THREAD

**Issue by hainm** [jupyterlab/jupyterlab#1297]
Hi,

I've trying to build labextension for [nglview](https://github.com/arose/nglview) and got error 
`Uncaught Error: No module found matching: nglview-js@0.5.3/src/labplugin.js(…)` and this error 
prevent jupyterlab shows up (only got grey background with nothing).

Not sure if that behavior is intended or not, just want to report here.

versions: using master branch. ( Wed Nov 23 09:32:45 2016 -0600)

PS: per `nglview` issue, I am working on this so you do not need to reply about its error.

**Comment by blink1073** [comment]
I @hainm, this is related to https://github.com/jupyterlab/jupyterlab/issues/1011.  Currently, if a single plugin throws an error while activating, the entire application is brought down.  We are looking into ways to help fix the problem.

**Comment by blink1073** [comment]
This is fixed in master, thanks to changes in Phosphor.  The application will load, but log the failing conditions in the browser console:

![image](https://cloud.githubusercontent.com/assets/2096628/23276383/a898c1c8-f9cf-11e6-87ef-50212d4621b7.png)

**Comment by hainm** [comment]
awesome. thx.
