### ISSUE TITLE
Emacs in terminal is broken in JL > 3.4.3

### ISSUE THREAD

**Issue by athornton** [jupyterlab/jupyterlab#12973]
## Description

In Jupyterlab 3.4.3, you could (as expected) say `emacs foo.txt` on the command line, and Emacs would indeed open the file foo.txt.

As of 3.4.4 (and continuing into 3.4.5), emacs startup (even if done with `-q` to bypass startup files) behaves as if Control-G were inserted almost immediately: no file is opened, and the `*Messages*` buffer has a `Quit` in it right after the invocation.

I suspect this is tied to the xterm.js update in 3.4.4, and that suggests that the fix is something we'd need to take upstream to them.

## Reproduce

So, here's the thing.  I've only (so far) seen this in the Rubin Science Platform.  If no one else can reproduce this, then this is clearly not the real issue I'm having.

1. Install jupyterlab 3.4.4 or later
2. Ensure that emacs is available in the Terminal environment
3. use `emacs <file>` to open an existing file.
4. You get `Quit` on the bottom and no file opened, rather than emacs opening the file and putting you in that buffer.

## Expected behavior

The file would open in emacs.

## Context

- Operating System and version: lsstsqre/sciplat-lab container (w_2022_30 and later exhibit this behavior)
- JupyterLab version: > 3.4.3

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by athornton** [comment]
Ah.  Looks like this: https://github.com/xtermjs/xterm.js/issues/3700

**Comment by athornton** [comment]
So I think upgrading the JL dependency to xterm 4.19 should do the trick.

**Comment by athornton** [comment]
https://github.com/jupyterlab/jupyterlab/pull/12974
https://github.com/jupyterlab/jupyterlab/pull/12975

**Comment by afshin** [comment]
Thanks for the background research and finding a fix, @athornton!

I can confirm this behavior exists in JupyterLab 3.4.5 and **does not exist** in 3.4.0.

**Comment by athornton** [comment]
I can confirm that updating to xtermjs 4.19 fixes the Emacs behavior.

**Comment by thuzhf** [comment]
So any quick fix for now? Or I need to wait for the next release of jupyterlab?
