### ISSUE TITLE
Running terminals and kernels - Large number of open tabs and/or kernels pushes subsequent sections out of visibility

### ISSUE THREAD

**Issue by firai** [jupyterlab/jupyterlab#12983]
## Description

There appears to be no minimum height to the sections in the Running Terminals and Kernels panel when other sections grow. When there are a large number of open tabs and/or kernels, the items in subsequent sections (i.e. language servers and terminals) become not visible and inaccessible, since the sections also aren't resizable.

**Edit:** Updated screenshot at https://github.com/jupyterlab/jupyterlab/commit/ff37c4f4324fbc6640f5c35777a79d64552696e2. Section header doesn't seem to completely disappear like the earlier screenshot anymore, but the running terminal list is still only visible through a sliver of a box in this example.

![image](https://user-images.githubusercontent.com/23555/185959917-89ccbb95-7e4c-4863-8f86-51e6210a2d62.png)

## Reproduce

1. Open a large number of tabs and/or kernels.
2. Open the "Running Terminals and Kernels" panel.

## Expected behavior

All sections of the "Running Terminals and Kernels" panels are visible and accessible even with a large number of items in one or more sections.

## Context

- Operating System and version: Windows 11
- Browser and version: Chrome (104.0.5112.102) and Firefox (103.0.2)
- JupyterLab version: 3.4.5 and latest development version (the former does not have the "language servers" section)

## Potential solutions

1. Impose minimum heights on the lists in a `:has`, and/or
2. Make the panels resizable (latter is obviously more involved)

**Comment by firai** [comment]
@meeseeksdev tag pkg:running

**Comment by jweill-aws** [comment]
Other responses that may mitigate this:

* Make the widget scrollable vertically
* Make each section collapsible

**Comment by firai** [comment]
Since similar panels (debugger, users and the upcoming extensions manager) all use accordion panels, it seems like this panel should ultimately move to accordion panels as well, which is both resizable as mentioned in my post and collapsible as noted in your comment.
