### ISSUE TITLE
Real-time collaborative editing causes notebook duplication - race condition.

### ISSUE THREAD

**Issue by timovwb** [jupyterlab/jupyterlab#12996]
## Description

When a notebook is opened in two separate browsers, the notebook content is sometimes duplicated.  It appears to be a race condition.

Related issue: #10852

## Reproduce

1. Start jupyterlab in collaborative mode: `$ jupyter lab --collaborative --no-browser`

2. Browser_1 opens the notebook.

3. Browser_1 restarts kernel and runs notebook, edits and runs a cell

4. Browser_1 saves the notebook, and

5. Browser_2 opens the notebook  while Browser_1 is still saving (Timing is important)

6. Unexpected behaviour: The cells of the notebook are duplicated, note how the number of sections is doubled.

## Expected behavior

The notebook should not change.

## Context

- Operating System and version: (server) Linux Ubuntu 18.04 (64-bit)
- Browser and version: Firefox 103.0 and Chromium 103.0.5060.134
- JupyterLab version: 3.4.2 (Installed by conda)

Attached is a notebook that was used to reliably reproduce the issue.  The notebook is deliberately large (a lot of graphical output) so that saving takes some time.  The saving should be clearly visible in network traffic and this can be used to ensure Browser_2 opens the notebook at the correct time.

Saving this notebook takes 20 seconds on a 1.0MiB upload connection. If the network connection is faster, then add more plots to the notebook so that saving takes longer.

`.ipynb` extensions aren't allowed, remove the `.txt`.
[notebook_duplication_bug.ipynb.txt](https://github.com/jupyterlab/jupyterlab/files/9409621/notebook_duplication_bug.ipynb.txt)

**Comment by davidbrochart** [comment]
Hi @timovwb, it should be fixed now. Can you try with the latest pre-release? It's not available in conda-forge yet, but you can install it with `pip install jupyterlab==4.0.0a27`.

**Comment by timovwb** [comment]
Hi @davidbrochart,  thanks for the suggestion.  I've tried `jupyterlab==4.0.0a27` and the problem doesn't persist.  There are no long upload times and I couldn't make the duplication happen.  Great to see this progress!  Looking forward to the 4.0 release.  Is there an expected release date?

**Comment by davidbrochart** [comment]
> Great to see this progress!

Thanks, glad to hear that it works fine!

> Is there an expected release date?

Definitely before the end of the year!
