### ISSUE TITLE
"Show Contextual Help" launcher button label is truncated on Linux

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#12999]
Noticed during @fcollonval 's demo of #12866 at the 2022-08-24 JupyterLab meeting.

## Description

Under the "Other" heading in the Launcher, the rightmost button in the screen shot below should say "Show Contextual Help" and does so on Windows and macOS. On Linux, using a common sans-serif font (Bitstream Vera Sans?), the word "Help" is truncated.

![Screen Shot 2022-08-24 at 9 42 43 AM](https://user-images.githubusercontent.com/93281816/186476151-aa5717a9-1259-4b03-8301-e99b95e603bc.png)

## Context

- Operating System and version: Linux (distro?)
- Browser and version: Firefox (version?)
- JupyterLab version: Tip of `master`

**Comment by krassowski** [comment]
This is kind of an issue is also:
- happening for users with accessibility CSS tweaks (increasing spacing) #9684
- potentially affecting custom branded kernels which have longer names (though previously the assumption was that two lines are enough: https://github.com/jupyterlab/jupyterlab/issues/3795#issuecomment-390362893)
