### ISSUE TITLE
Interface freezes when a PDF tab is open on Chromium browsers

### ISSUE THREAD

**Issue by RW21** [jupyterlab/jupyterlab#13002]
## Description
Interface freezes when a PDF tab exists on Chromium browsers.

The interface freezes. I can not click on anything.

I tested on various PDFs, but it seems to happen on any pdf regardless of size etc.

![image](https://user-images.githubusercontent.com/24377986/186637566-52e689a4-d49d-4d1b-a312-2cb5f9610f2d.png)

This only occurs on Chromium browsers. 

I have only tested on Chromium and Firefox, it always happens on Chromium.
I suspect it does not occur on Firefox because of it forces to refresh everytime a pdf is open.
https://github.com/jupyterlab/jupyterlab/blob/master/packages/pdf-extension/src/index.ts#L67

## Reproduce

1. Open a PDF file on Jupyterlab in a new tab
2. Open an ipynb in another tab, and move to it.
3. Move to a new browser tab
4. Come back to Jupyterlab, the interface is frozen.

It happens on Linux systems, Windows and Macs, regardless of the network configuration.

## Expected behavior

Should not freeze.

## Context

- Operating System and version: Ubuntu 22.04 LTS
- Browser and version: Brave browser Version 1.42.97 Chromium: 104.0.5112.102 (Official Build) (64-bit)
- JupyterLab version: 3.4.5

Happened on Windows and Edge browser as well.

I tested that it only happens for versions above 3.4.0-.

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/___/miniconda3/envs/jlab-test/bin
	/home/___/miniconda3/condabin
	/home/___/.local/bin
	/home/___/Code/zsh-scripts
	/home/linuxbrew/.linuxbrew/bin
	/home/___/.local/bin
	/home/___/Code/zsh-scripts
	/home/linuxbrew/.linuxbrew/bin
	/home/linuxbrew/.linuxbrew/bin
	/home/linuxbrew/.linuxbrew/sbin
	/home/___/.nvm/versions/node/v17.9.0/bin
	/home/___/.local/bin
	/home/___/Code/zsh-scripts
	/home/linuxbrew/.linuxbrew/bin
	/home/___/.local/share/zinit/polaris/bin
	/home/linuxbrew/.linuxbrew/bin
	/home/linuxbrew/.linuxbrew/sbin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin
	/snap/bin

sys.path:
	/home/___/miniconda3/envs/jlab-test/bin
	/home/___/miniconda3/envs/jlab-test/lib/python310.zip
	/home/___/miniconda3/envs/jlab-test/lib/python3.10
	/home/___/miniconda3/envs/jlab-test/lib/python3.10/lib-dynload
	/home/___/.local/lib/python3.10/site-packages
	/home/___/miniconda3/envs/jlab-test/lib/python3.10/site-packages

sys.executable:
	/home/___/miniconda3/envs/jlab-test/bin/python

sys.version:
	3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]

platform.platform():
	Linux-5.19.0-76051900-generic-x86_64-with-glibc2.35

which -a jupyter:
	/home/___/miniconda3/envs/jlab-test/bin/jupyter
	/home/___/.local/bin/jupyter
	/home/___/.local/bin/jupyter
	/home/___/.local/bin/jupyter

pip list:
	Package                       Version
	----------------------------- -----------
	aiofiles                      0.8.0
	aiosqlite                     0.17.0
	anyio                         3.6.1
	argon2-cffi                   21.3.0
	argon2-cffi-bindings          21.2.0
	asttokens                     2.0.5
	attrs                         21.4.0
	Babel                         2.10.3
	backcall                      0.2.0
	backports.functools-lru-cache 1.6.4
	beautifulsoup4                4.11.1
	bleach                        5.0.0
	brotlipy                      0.7.0
	build                         0.8.0
	certifi                       2022.6.15
	cffi                          1.15.0
	charset-normalizer            2.1.1
	cryptography                  37.0.4
	debugpy                       1.6.0
	decorator                     5.1.1
	defusedxml                    0.7.1
	entrypoints                   0.4
	executing                     0.8.3
	fastjsonschema                2.15.3
	ffmpeg-normalize              1.23.0
	ffmpeg-progress-yield         0.2.0
	filelock                      3.7.1
	flit_core                     3.7.1
	huggingface-hub               0.8.1
	idna                          3.3
	importlib-metadata            4.11.4
	importlib-resources           5.9.0
	ipykernel                     6.13.0
	ipython                       8.4.0
	ipython-genutils              0.2.0
	ipywidgets                    7.7.0
	jedi                          0.18.1
	Jinja2                        3.1.2
	json5                         0.9.10
	jsonschema                    4.5.1
	jupyter                       1.0.0
	jupyter-client                7.3.1
	jupyter-console               6.4.3
	jupyter-core                  4.10.0
	jupyter-lsp                   1.5.1
	jupyter-server                1.18.1
	jupyter_server_ydoc           0.1.11
	jupyter-ydoc                  0.1.17
	jupyterlab                    4.0.0a27
	jupyterlab-pygments           0.2.2
	jupyterlab_server             2.15.1
	jupyterlab-widgets            1.1.0
	lxml                          4.9.1
	MarkupSafe                    2.1.1
	matplotlib-inline             0.1.3
	mistune                       0.8.4
	nbclassic                     0.4.3
	nbclient                      0.6.4
	nbconvert                     6.5.0
	nbformat                      5.4.0
	nest-asyncio                  1.5.5
	notebook                      6.4.11
	notebook-shim                 0.1.0
	packaging                     21.3
	pandas                        1.4.2
	pandocfilters                 1.5.0
	parso                         0.8.3
	pep517                        0.13.0
	pexpect                       4.8.0
	pickleshare                   0.7.5
	pip                           22.2.2
	pip-tools                     6.8.0
	pkgutil_resolve_name          1.3.10
	prometheus-client             0.14.1
	prompt-toolkit                3.0.29
	psutil                        5.9.1
	ptyprocess                    0.7.0
	pure-eval                     0.2.2
	pycparser                     2.21
	Pygments                      2.12.0
	pyOpenSSL                     22.0.0
	pyparsing                     3.0.9
	pyrsistent                    0.18.1
	PySocks                       1.7.1
	python-dateutil               2.8.2
	pytz                          2022.2.1
	pyzmq                         23.0.0
	qtconsole                     5.3.0
	QtPy                          2.1.0
	requests                      2.28.1
	Send2Trash                    1.8.0
	setuptools                    65.3.0
	six                           1.16.0
	sniffio                       1.2.0
	soupsieve                     2.3.2.post1
	stack-data                    0.2.0
	terminado                     0.15.0
	tinycss2                      1.1.1
	tomli                         2.0.1
	tornado                       6.1
	tqdm                          4.64.0
	traitlets                     5.2.2.post1
	typing_extensions             4.3.0
	urllib3                       1.26.11
	wcwidth                       0.2.5
	webencodings                  0.5.1
	websocket-client              1.4.0
	wheel                         0.37.1
	widgetsnbextension            3.6.0
	y-py                          0.5.4
	ypy-websocket                 0.3.2
	zipp                          3.8.1

conda list:
	# packages in environment at /home/___/miniconda3/envs/jlab-test:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                 conda_forge    conda-forge
	_openmp_mutex             4.5                       2_gnu    conda-forge
	anyio                     3.6.1              pyhd8ed1ab_1    conda-forge
	argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
	argon2-cffi-bindings      21.2.0          py310h5764c6d_2    conda-forge
	asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
	attrs                     22.1.0             pyh71513ae_1    conda-forge
	babel                     2.10.3             pyhd8ed1ab_0    conda-forge
	backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
	backports                 1.0                        py_2    conda-forge
	backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
	beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
	bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
	brotlipy                  0.7.0           py310h5764c6d_1004    conda-forge
	bzip2                     1.0.8                h7f98852_4    conda-forge
	ca-certificates           2022.6.15            ha878542_0    conda-forge
	certifi                   2022.6.15       py310hff52083_0    conda-forge
	cffi                      1.15.1          py310h255011f_0    conda-forge
	charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
	cryptography              37.0.4          py310h597c629_0    conda-forge
	debugpy                   1.6.3           py310hd8f1fbe_0    conda-forge
	decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
	defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
	entrypoints               0.4                pyhd8ed1ab_0    conda-forge
	executing                 0.10.0             pyhd8ed1ab_0    conda-forge
	flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
	icu                       70.1                 h27087fc_0    conda-forge
	idna                      3.3                pyhd8ed1ab_0    conda-forge
	importlib-metadata        4.11.4          py310hff52083_0    conda-forge
	importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
	importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
	ipykernel                 6.15.1             pyh210e3f2_0    conda-forge
	ipython                   8.4.0           py310hff52083_0    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
	jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
	json5                     0.9.5              pyh9f0ad1d_0    conda-forge
	jsonschema                4.14.0             pyhd8ed1ab_0    conda-forge
	jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
	jupyter_core              4.11.1          py310hff52083_0    conda-forge
	jupyter_server            1.18.1             pyhd8ed1ab_0    conda-forge
	jupyterlab                3.4.5              pyhd8ed1ab_0    conda-forge
	jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
	jupyterlab_server         2.15.1             pyhd8ed1ab_0    conda-forge
	ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
	libffi                    3.4.2                h7f98852_5    conda-forge
	libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
	libgomp                   12.1.0              h8d9b700_16    conda-forge
	libiconv                  1.16                 h516909a_0    conda-forge
	libnsl                    2.0.0                h7f98852_0    conda-forge
	libsodium                 1.0.18               h36c2ea0_1    conda-forge
	libsqlite                 3.39.2               h753d276_1    conda-forge
	libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
	libuuid                   2.32.1            h7f98852_1000    conda-forge
	libxml2                   2.9.14               h22db469_4    conda-forge
	libxslt                   1.1.35               h8affb1d_0    conda-forge
	libzlib                   1.2.12               h166bdaf_2    conda-forge
	lxml                      4.9.1           py310h5764c6d_0    conda-forge
	markupsafe                2.1.1           py310h5764c6d_1    conda-forge
	matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
	mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
	nbclassic                 0.4.3              pyhd8ed1ab_0    conda-forge
	nbclient                  0.6.7              pyhd8ed1ab_0    conda-forge
	nbconvert                 7.0.0              pyhd8ed1ab_0    conda-forge
	nbconvert-core            7.0.0              pyhd8ed1ab_0    conda-forge
	nbconvert-pandoc          7.0.0              pyhd8ed1ab_0    conda-forge
	nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
	ncurses                   6.3                  h27087fc_1    conda-forge
	nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
	notebook                  6.4.12             pyha770c72_0    conda-forge
	notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge
	openssl                   1.1.1q               h166bdaf_0    conda-forge
	packaging                 21.3               pyhd8ed1ab_0    conda-forge
	pandoc                    2.19.2               ha770c72_0    conda-forge
	pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
	parso                     0.8.3              pyhd8ed1ab_0    conda-forge
	pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
	pickleshare               0.7.5                   py_1003    conda-forge
	pip                       22.2.2             pyhd8ed1ab_0    conda-forge
	pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
	prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
	prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
	psutil                    5.9.1           py310h5764c6d_0    conda-forge
	ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
	pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
	pycparser                 2.21               pyhd8ed1ab_0    conda-forge
	pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
	pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
	pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
	pyrsistent                0.18.1          py310h5764c6d_1    conda-forge
	pysocks                   1.7.1           py310hff52083_5    conda-forge
	python                    3.10.6          h582c2e5_0_cpython    conda-forge
	python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
	python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
	python_abi                3.10                    2_cp310    conda-forge
	pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
	pyzmq                     23.2.1          py310h330234f_0    conda-forge
	readline                  8.1.2                h0f457ee_0    conda-forge
	requests                  2.28.1             pyhd8ed1ab_0    conda-forge
	send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
	setuptools                65.3.0          py310hff52083_0    conda-forge
	six                       1.16.0             pyh6c4a22f_0    conda-forge
	sniffio                   1.2.0           py310hff52083_3    conda-forge
	soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
	stack_data                0.4.0              pyhd8ed1ab_0    conda-forge
	terminado                 0.15.0          py310hff52083_0    conda-forge
	tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
	tk                        8.6.12               h27826a3_0    conda-forge
	tornado                   6.2             py310h5764c6d_0    conda-forge
	traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
	typing_extensions         4.3.0              pyha770c72_0    conda-forge
	tzdata                    2022c                h191b570_0    conda-forge
	urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
	wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
	webencodings              0.5.1                      py_1    conda-forge
	websocket-client          1.4.0              pyhd8ed1ab_0    conda-forge
	wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
	xz                        5.2.6                h166bdaf_0    conda-forge
	zeromq                    4.3.4                h9c3ff4c_1    conda-forge
	zipp                      3.8.1              pyhd8ed1ab_0    conda-forge

conda env:
	name: jlab-test
	channels:
	  - conda-forge
	  - defaults
	dependencies:
	  - _libgcc_mutex=0.1=conda_forge
	  - _openmp_mutex=4.5=2_gnu
	  - anyio=3.6.1=pyhd8ed1ab_1
	  - argon2-cffi=21.3.0=pyhd8ed1ab_0
	  - argon2-cffi-bindings=21.2.0=py310h5764c6d_2
	  - asttokens=2.0.8=pyhd8ed1ab_0
	  - attrs=22.1.0=pyh71513ae_1
	  - babel=2.10.3=pyhd8ed1ab_0
	  - backcall=0.2.0=pyh9f0ad1d_0
	  - backports=1.0=py_2
	  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
	  - beautifulsoup4=4.11.1=pyha770c72_0
	  - bleach=5.0.1=pyhd8ed1ab_0
	  - brotlipy=0.7.0=py310h5764c6d_1004
	  - bzip2=1.0.8=h7f98852_4
	  - ca-certificates=2022.6.15=ha878542_0
	  - certifi=2022.6.15=py310hff52083_0
	  - cffi=1.15.1=py310h255011f_0
	  - charset-normalizer=2.1.1=pyhd8ed1ab_0
	  - cryptography=37.0.4=py310h597c629_0
	  - debugpy=1.6.3=py310hd8f1fbe_0
	  - decorator=5.1.1=pyhd8ed1ab_0
	  - defusedxml=0.7.1=pyhd8ed1ab_0
	  - entrypoints=0.4=pyhd8ed1ab_0
	  - executing=0.10.0=pyhd8ed1ab_0
	  - flit-core=3.7.1=pyhd8ed1ab_0
	  - icu=70.1=h27087fc_0
	  - idna=3.3=pyhd8ed1ab_0
	  - importlib-metadata=4.11.4=py310hff52083_0
	  - importlib_metadata=4.11.4=hd8ed1ab_0
	  - importlib_resources=5.9.0=pyhd8ed1ab_0
	  - ipykernel=6.15.1=pyh210e3f2_0
	  - ipython=8.4.0=py310hff52083_0
	  - ipython_genutils=0.2.0=py_1
	  - jedi=0.18.1=pyhd8ed1ab_2
	  - jinja2=3.1.2=pyhd8ed1ab_1
	  - json5=0.9.5=pyh9f0ad1d_0
	  - jsonschema=4.14.0=pyhd8ed1ab_0
	  - jupyter_client=7.3.4=pyhd8ed1ab_0
	  - jupyter_core=4.11.1=py310hff52083_0
	  - jupyter_server=1.18.1=pyhd8ed1ab_0
	  - jupyterlab=3.4.5=pyhd8ed1ab_0
	  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
	  - jupyterlab_server=2.15.1=pyhd8ed1ab_0
	  - ld_impl_linux-64=2.36.1=hea4e1c9_2
	  - libffi=3.4.2=h7f98852_5
	  - libgcc-ng=12.1.0=h8d9b700_16
	  - libgomp=12.1.0=h8d9b700_16
	  - libiconv=1.16=h516909a_0
	  - libnsl=2.0.0=h7f98852_0
	  - libsodium=1.0.18=h36c2ea0_1
	  - libsqlite=3.39.2=h753d276_1
	  - libstdcxx-ng=12.1.0=ha89aaad_16
	  - libuuid=2.32.1=h7f98852_1000
	  - libxml2=2.9.14=h22db469_4
	  - libxslt=1.1.35=h8affb1d_0
	  - libzlib=1.2.12=h166bdaf_2
	  - lxml=4.9.1=py310h5764c6d_0
	  - markupsafe=2.1.1=py310h5764c6d_1
	  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
	  - mistune=2.0.4=pyhd8ed1ab_0
	  - nbclassic=0.4.3=pyhd8ed1ab_0
	  - nbclient=0.6.7=pyhd8ed1ab_0
	  - nbconvert=7.0.0=pyhd8ed1ab_0
	  - nbconvert-core=7.0.0=pyhd8ed1ab_0
	  - nbconvert-pandoc=7.0.0=pyhd8ed1ab_0
	  - nbformat=5.4.0=pyhd8ed1ab_0
	  - ncurses=6.3=h27087fc_1
	  - nest-asyncio=1.5.5=pyhd8ed1ab_0
	  - notebook=6.4.12=pyha770c72_0
	  - notebook-shim=0.1.0=pyhd8ed1ab_0
	  - openssl=1.1.1q=h166bdaf_0
	  - packaging=21.3=pyhd8ed1ab_0
	  - pandoc=2.19.2=ha770c72_0
	  - pandocfilters=1.5.0=pyhd8ed1ab_0
	  - parso=0.8.3=pyhd8ed1ab_0
	  - pexpect=4.8.0=pyh9f0ad1d_2
	  - pickleshare=0.7.5=py_1003
	  - pip=22.2.2=pyhd8ed1ab_0
	  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
	  - prometheus_client=0.14.1=pyhd8ed1ab_0
	  - prompt-toolkit=3.0.30=pyha770c72_0
	  - psutil=5.9.1=py310h5764c6d_0
	  - ptyprocess=0.7.0=pyhd3deb0d_0
	  - pure_eval=0.2.2=pyhd8ed1ab_0
	  - pycparser=2.21=pyhd8ed1ab_0
	  - pygments=2.13.0=pyhd8ed1ab_0
	  - pyopenssl=22.0.0=pyhd8ed1ab_0
	  - pyparsing=3.0.9=pyhd8ed1ab_0
	  - pyrsistent=0.18.1=py310h5764c6d_1
	  - pysocks=1.7.1=py310hff52083_5
	  - python=3.10.6=h582c2e5_0_cpython
	  - python-dateutil=2.8.2=pyhd8ed1ab_0
	  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
	  - python_abi=3.10=2_cp310
	  - pytz=2022.2.1=pyhd8ed1ab_0
	  - pyzmq=23.2.1=py310h330234f_0
	  - readline=8.1.2=h0f457ee_0
	  - requests=2.28.1=pyhd8ed1ab_0
	  - send2trash=1.8.0=pyhd8ed1ab_0
	  - setuptools=65.3.0=py310hff52083_0
	  - six=1.16.0=pyh6c4a22f_0
	  - sniffio=1.2.0=py310hff52083_3
	  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
	  - stack_data=0.4.0=pyhd8ed1ab_0
	  - terminado=0.15.0=py310hff52083_0
	  - tinycss2=1.1.1=pyhd8ed1ab_0
	  - tk=8.6.12=h27826a3_0
	  - tornado=6.2=py310h5764c6d_0
	  - traitlets=5.3.0=pyhd8ed1ab_0
	  - typing_extensions=4.3.0=pyha770c72_0
	  - tzdata=2022c=h191b570_0
	  - urllib3=1.26.11=pyhd8ed1ab_0
	  - wcwidth=0.2.5=pyh9f0ad1d_2
	  - webencodings=0.5.1=py_1
	  - websocket-client=1.4.0=pyhd8ed1ab_0
	  - wheel=0.37.1=pyhd8ed1ab_0
	  - xz=5.2.6=h166bdaf_0
	  - zeromq=4.3.4=h9c3ff4c_1
	  - zipp=3.8.1=pyhd8ed1ab_0
	prefix: /home/___/miniconda3/envs/jlab-test

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 2022-08-25 19:31:31.133 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2022-08-25 19:31:31.133 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2022-08-25 19:31:31.142 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-08-25 19:31:31.150 ServerApp] nbclassic | extension was successfully linked.
[I 2022-08-25 19:31:31.310 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-08-25 19:31:31.324 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-08-25 19:31:31.506 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2022-08-25 19:31:31.548 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2022-08-25 19:31:31.548 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2022-08-25 19:31:31.549 LabApp] JupyterLab extension loaded from /home/rw21/.local/lib/python3.10/site-packages/jupyterlab
[I 2022-08-25 19:31:31.549 LabApp] JupyterLab application directory is /home/rw21/.local/share/jupyter/lab
[I 2022-08-25 19:31:31.552 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-08-25 19:31:31.554 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-08-25 19:31:31.555 ServerApp] Serving notebooks from local directory: /home/rw21/Downloads
[I 2022-08-25 19:31:31.555 ServerApp] Jupyter Server 1.18.1 is running at:
[I 2022-08-25 19:31:31.555 ServerApp] http://localhost:8888/lab?token=337f94cc6ef675d44fd842d30908b7856b139b3cd7a3534c
[I 2022-08-25 19:31:31.555 ServerApp]  or http://127.0.0.1:8888/lab?token=337f94cc6ef675d44fd842d30908b7856b139b3cd7a3534c
[I 2022-08-25 19:31:31.555 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-08-25 19:31:31.571 ServerApp]

    To access the server, open this file in a browser:
        file:///home/rw21/.local/share/jupyter/runtime/jpserver-116053-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=337f94cc6ef675d44fd842d30908b7856b139b3cd7a3534c
     or http://127.0.0.1:8888/lab?token=337f94cc6ef675d44fd842d30908b7856b139b3cd7a3534c
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.

</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by imcovangent** [comment]
Just wanted to let you know that I have exactly the same issue, also with a fresh install of Jupyter Lab on Jupyter Hub. It prevents us now from upgrading beyond 3.3.4.
