### ISSUE TITLE
Smaller padding between items in TOC

### ISSUE THREAD

**Issue by stefansimik** [jupyterlab/jupyterlab#13000]
## Description

Padding between item sin TOC plugin are extremely big.
This is contra-productive because:
-  big padding results in long scrollable content in TOC, and user does not see as many items, as he could
-  it wastes precious space in TOC

If the padding is smaller, it has significant benefits:
- rows in TOC are still nicely visible and readable
- user can see more content without need for scrolling

See image:
![2022-08-24_214934](https://user-images.githubusercontent.com/6208056/186511314-37459a39-43f7-49fb-9cda-2fc7af623bca.png)

## Reproduce

This is simply visible in Jupyterlab v3.4.2 (and probably many versions around)

## Expected behavior

Make the padding smaller.

- current CSS property: padding-top and padding-bottom have value 8px
- new fixed CSS property: padding-top and padding-bottom **should have value 4px**
- 
![2022-08-24_215936](https://user-images.githubusercontent.com/6208056/186513147-078ed751-bcba-479c-9768-8a62ad5dd6fe.png)

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome 104.0.5112.102
- JupyterLab version: 3.4.2

**Comment by jweill-aws** [comment]
Touch/tap/click target sizing is an accessibility issue on mobile devices — we should avoid putting click targets too close together. On desktop devices, though, this is less of an issue.

**Comment by stefansimik** [comment]
JupyterLab is development tool and strong majority of users are some type of programmers / Analysts work with desktop devices, because they need to write some code. That's what Jupyter is about - iterations of write code / see result.

Writing code with mobile phone / tablet with touch/tap/click is at least uncomfortable in practice.
That's why almost nobody is coding in mobile phone.

Typical coder in Jupyterlab has to work with **desktop device**. 
It is the only practical / productive option in real world of coding.

**Comment by krassowski** [comment]
The comment above was based on my input in the triage meeting saying that I looked into how much we can reduce the padding without introducing WCAG compliance issues. I believe that we can reduce it to zero at devices which do not use touch input because the target size requirement (44px) only applies to touch screen devices.
All it is saying is that we can have what you requested AND compliance with other objectives of the project (e.g. being accessible when used on a tablet with a keyboard) without a problem, it's just a matter of having separate CSS rules for different devices.

**Comment by fcollonval** [comment]
I set the target to 3.4.x has it will not apply in JupyterLab 4 that gets a more consistent tree view for the table of content; see https://github.com/jupyterlab/jupyterlab/issues/12993#issuecomment-1224028276 for a capture.

**Comment by jtpio** [comment]
Bumping to `4.0.x` but feel free to close if it is not applicable anymore.

**Comment by stefansimik** [comment]
Checked situation in JupyterLab v4.2.0 and it looks great now.
Closing this issue.

Example:

![CleanShot 2024-06-08 at 00 02 00@2x](https://github.com/jupyterlab/jupyterlab/assets/6208056/70908608-c136-4307-8084-bfd23203d338)
