### ISSUE TITLE
Provide DocumentManager Service

### ISSUE THREAD

**Issue by svenefftinge** [jupyterlab/jupyterlab#1301]
I think there are more occasions where pathes can be opened, than using the file browser. For instance a render mime could provide a link to open an editor. Also our monaco integration for allows to navigate references in code. 

Therefore it would be good to have a common UI-independent component that manages the opened files. the DocumentManager created and hidden in the file browser looks just right. To allow using it form other plugins I would like to expose it as a plugin. Here are the changes I'd like to propose:

1) remove the instance tracker in file browser and just rely on the shell.
2) add a plugin for docmanager that exposes an IDocumentManager service.
3) let file browser use that service

Does that make sense?

**Comment by blink1073** [comment]
That sounds great, are you wanting to take that on?

**Comment by svenefftinge** [comment]
ok

**Comment by jasongrout** [comment]
It sounds like a good idea to make it a separate plugin. I'm a little confused by

> remove the instance tracker in file browser and just rely on the shell.

but I'll wait to see what the PR does.
