### ISSUE TITLE
`link_check` is failing on CI

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13016]
## Description

The `link_check` seems to be failing consistently on CI now. 

## Reproduce

Examples:

- latest commit on `master`: https://github.com/jupyterlab/jupyterlab/runs/8036639522
- recent PR: https://github.com/jupyterlab/jupyterlab/runs/8039684866

## Expected behavior

Should pass.

## Context

This looks related to the recent changes on the Lumino documentation: 

![image](https://user-images.githubusercontent.com/591645/186947938-be146c30-dde3-4cb7-87b1-0212935bfa07.png)

**Comment by krassowski** [comment]
We can add redirects for those (in addition to updating to new location). Probably also worth checking for any dead links in extension examples and elsewhere.
