### ISSUE TITLE
Provide a simple way of accessing notebook metadata

### ISSUE THREAD

**Issue by tonkolviktor** [jupyterlab/jupyterlab#13020]
### Problem

I would like it if I could have a simple way of accessing the notebook name I'm working with. I'd like to use the notebook name in my own metadata collector.

### Proposed Solution

```
import jupyterlab 
jupyterlab.metadata  # returns a dict-like object
```

### Additional context

My own research which maybe not complete, shows me results which are way more complicated than what I'd like to have:
- https://stackoverflow.com/questions/68120235/how-do-you-get-the-currently-active-notebook-name-in-jupyterlab
- https://pyquestions.com/how-do-i-get-the-current-ipython-jupyter-notebook-name

There is a project which tries to fix the lack of such an api in jupyter*, however it's not maintained anymore:
- https://github.com/msm1089/ipynbname/issues/13

In an ideal solution, one would get many metainformation about the notebook, like:
- name
- url
- path in the file system
- last saved date
- create date
- active cell
- cell execution history

Anyhow you get the idea, I'm personally would be only interested ATM in the first 2.

**Comment by krassowski** [comment]
If you are looking for a quick solution, https://github.com/jtpio/ipylab might be the answer. In particular have a look at the `sessions.ipynb` in examples:

```python
from ipylab import JupyterFrontEnd
app = JupyterFrontEnd()
print(app.sessions.current_session)
```

```python
{'id': '1d03724f-53bb-4239-8135-759389495438',
 'kernel': {'id': 'b1dcad03-d4ed-4099-9585-08c410cc078c', 'name': 'python3'},
 'path': 'examples/sessions.ipynb',
 'type': 'notebook',
 'name': 'sessions.ipynb'}
```

However, you should be aware that a kernel may not be bound to a file which exists on a disk, or that the notebook might be on a different/remote machine.

**Comment by jweill-aws** [comment]
@tonkolviktor Does the extension @krassowski mentioned earlier suit your needs?

**Comment by tonkolviktor** [comment]
thanks @jweill-aws for the extra notification
thank you @krassowski that actually helps

> However, you should be aware that a kernel may not be bound to a file which exists on a disk, or that the notebook might be on a different/remote machine.

yes, good point, still we keep it simple so ipylab is enough for us  ;)
