### ISSUE TITLE
Death of notebook kernel

### ISSUE THREAD

**Issue by Jisans** [jupyterlab/jupyterlab#13024]
Hello all,
When I run the code in jupyterlab, the following error occurs:
```
Kernel Restarting

The kernel for Untitled1.ipynb appears to have died. It will restart automatically.
```
I don't know where the problem lies,

###Note
System: Linux DESKTOP-10UCA6U 4.4.0-22000-Microsoft #653-Microsoft Wed Apr 27 16:06:00 PST 2022 x86_64 x86_64 x86_64 GNU/Linux
Python 3.9.1,pip 22.1.2

**Comment by davidbrochart** [comment]
Hi @Jisans,
Difficult to answer without seeing your code, but it usually happens when running out of memory.

**Comment by Jisans** [comment]
@davidbrochart , There is the same problem here,

[Notebooks kernel died ! #487](https://github.com/fermiPy/fermipy/issues/487)
[Module installation #476](https://github.com/fermiPy/fermipy/issues/476)

**Comment by davidbrochart** [comment]
Yes, both issues suggest it's not related to JupyterLab.

**Comment by Jisans** [comment]
Sir, this problem is usually a code problem or a computer problem

**Comment by davidbrochart** [comment]
Agreed.
