### ISSUE TITLE
App freezes when using help

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13039]
## Description

This was first reported in https://github.com/jupyterlite/jupyterlite/issues/767, moving it to the JupyterLab repo since it seems to happen in JupyterLab as well.

Jupyterlite freezes when going to help menu 

## Reproduce

Open JupyterLab in chrome:
  
1. Go to 'help menu'
2. Click on 'markdown reference'
3. Go back to  'previous tab'
4. See error 'the app freeze'

## Expected behavior

app should work 

## Context

- JupyterLab version: `4.0.0a27`
- Operating System and version: Windows 10 Enterprise N 21H1
- Browser and version: Chrome  104.0.5112.81 (Official Build) (64-bit)

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

---

Originally reported in https://github.com/jupyterlite/jupyterlite/issues/767 by @Gal-Peled.

**Comment by harishfalco** [comment]
Greetings, @jtpio  Since I'm new to contributing to open-source, I'd want to fix this problem. Give it to me, if possible.

**Comment by jtpio** [comment]
Thanks @harishfalco! I've assigned the issue to you.

**Comment by krassowski** [comment]
Sounds related to #13002. It could be something with iframe handling, possibly Chromium broke something again.

**Comment by Gal-Peled** [comment]
Hi , seems like I missed some of the action , sorry I am not so conencted. 
@krassowski - I have the same issue with MS EDGE  so it's probably in jupyterlab and not Chromium  
@harishfalco  - Good luck, let us  know if it is solved

**Comment by krassowski** [comment]
@Gal-Peled are you using a very old version of Edge? Since 2020 Edge is built on Chromium.

**Comment by Gal-Peled** [comment]
@krassowski  
Ahh!! I use an update EDGE version. I probably missed it as for me year 2020 was kind of deleted : ( .

**Comment by ekungurov** [comment]
Same on Edge 107.0.1418.35
