### ISSUE TITLE
"Fix License Headers" CI check is failing

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13031]
## Description

Looks like the "Fix License Headers" CI check started to fail recently on new PRs:

- https://github.com/jupyterlab/jupyterlab/pull/13029
- https://github.com/jupyterlab/jupyterlab/pull/13030

Might be related to this recent action update: https://github.com/jupyterlab/jupyterlab/pull/13025

## Reproduce

- https://github.com/jupyterlab/jupyterlab/runs/8096296471?check_suite_focus=true
- https://github.com/jupyterlab/jupyterlab/runs/8094402054?check_suite_focus=true

## Expected behavior

Should not fail if there is no changes to commit.

**Comment by fcollonval** [comment]
I have a fix as part of a PR: https://github.com/jupyterlab/jupyterlab/pull/12866/files#diff-78b12dc6b8e9994fee82dcf50f5a781a27ddfda96e9be4d8facf7df17d7d3e16

**Comment by fcollonval** [comment]
> we hit that for the lumino repository as well.
