### ISSUE TITLE
Change compilation target from ES2017 to ES2018

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#13052]
Update JupyterLab 4's TypeScript compilation `target` from its current value (`ES2017`) to `ES2018` to support native `AsyncIterable` instances (e.g., instances and sub-classes of `Poll` or classes that are composed with it).

cf.:
- https://github.com/jupyterlab/lumino/pull/388
- https://github.com/jupyterlab/lumino/pull/386

**Comment by maartenbreddels** [comment]
FYI, I think this caused our builds to fail with:
```
node_modules/@jupyterlab/services/lib/event/index.d.ts(89,52): error TS2583: Cannot find name 'AsyncIterable'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2018' or later.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by maartenbreddels** [comment]
Hmm, I'm confused. this is only for lab 4 right?

**Comment by fcollonval** [comment]
The `AsyncIterable` is used in 3.6.x since https://github.com/jupyterlab/jupyterlab/pull/13465

It requires a typescript target of es2018.

**Comment by fcollonval** [comment]
We raise our target in JupyterLab with the hypothesis that all browsers are [supported the features](https://caniuse.com/?feats=mdn-javascript_builtins_regexp_dotall,mdn-javascript_builtins_regexp_lookbehind_assertion,mdn-javascript_builtins_regexp_named_capture_groups,mdn-javascript_builtins_regexp_property_escapes,mdn-javascript_builtins_symbol_asynciterator,mdn-javascript_functions_method_definitions_async_generator_methods,mdn-javascript_grammar_template_literals_template_literal_revision,promise-finally) of es2018. So I would advice updating your target - except if you have specific requirements to run on old browsers.
