### ISSUE TITLE
Expected behavior when installing with integrity error(s)

### ISSUE THREAD

**Issue by brichet** [jupyterlab/jupyterlab#13061]
## Description

Installing JupyterLab in edition mode (`pip install -e .`) passes an integrity check.
If there are some integrity errors in packages, the files are modified when possible and a message is displayed. 
The installation process then tries to run `jlpm install` :
https://github.com/jupyterlab/jupyterlab/blob/de6aec7989d5cf9226c294ba1013638c63ab1468/buildutils/src/ensure-repo.ts#L896-L904
which seems not installed at that stage.

This results in an unrelated error message :
```
> jlpm install
  /bin/sh: 1: jlpm: not found
  Error: Command failed: jlpm install

...

AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'
```

## Reproduce
Create an integrity error in a clean JupyterLab repo and run `pip install -e .`.

For example, create a *style* directory in *metapackage*, and add an empty file *index.css*.

## Expected behavior

If the expected behavior is to finalize the installation process anyway, then `jlpm install` can be replaced by `yarn install`, or maybe even removed, as it does not seems to affect the installation.

## Context

- Operating System and version: Linux Ubuntu 22.04
- JupyterLab version: master branch

**Comment by fcollonval** [comment]
Thanks @brichet 

For consistency, we should probably call `node jupyterlab/staging/yarn.js` as defined in hatch settings:

https://github.com/jupyterlab/jupyterlab/blob/de6aec7989d5cf9226c294ba1013638c63ab1468/pyproject.toml#L180

**Comment by ofek** [comment]
> AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'

^ isn't the real error, look down

**Comment by fcollonval** [comment]
@ofek the PEP mentions that that hook is optional: https://peps.python.org/pep-0662/#prepare-metadata-for-build-editable

The real reason is the one reported by @brichet

**Comment by ofek** [comment]
I'm saying that's not the entire traceback, something else happened

**Comment by fcollonval** [comment]
Oh sorry for the misunderstanding @ofek 

Actually he needed to look up - I think because we are using subprocess calls with their own print when something fails. Hence the real error source Nicolas reported is correctly `jlpm not found` that is appearing before the Python error.

**Comment by 3coins** [comment]
I could replicate this on my laptop (M1 Pro, Mac OS Monterey, Python 3.9, JLab master) following @brichet's instructions. In my case there was a similar but different error which pointed to the `jupyterlab` module missing. I have only included the relevant bits here.

```shell
(jlab-install-error) ➜  jupyterlab git:(master) ✗ pip install -e . 
      > jlpm install
      Traceback (most recent call last):
        File "/opt/miniconda3/envs/jlab-install-error/bin/jlpm", line 5, in <module>
          from jupyterlab.jlpmapp import main
      ModuleNotFoundError: No module named 'jupyterlab'
      Error: Command failed: jlpm install
```
This seems a bit confusing to me as running a python console in the same environment, I could load the `jupyterlab` module without any errors.
```shell
(jlab-install-error) ➜  jupyterlab git:(master) ✗ python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00) 
[Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from jupyterlab.jlpmapp import main
>>> 
```

**Comment by ellisonbg** [comment]
I am seeing this error in a clean conda env and a fresh build in master, I had to install a particular version of nodejs to get it to work (14).
