### ISSUE TITLE
Add UI for editing notebook metadata

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1308]

**Comment by vidartf** [comment]
Related to #451 (?).

**Comment by blink1073** [comment]
Could be, the feature parity would be a simple text editor.

**Comment by ellisonbg** [comment]
I am fine with the feature parity version of this being a text editor, but we should implement it in the cell toolbar, which we are planning on making its own L side bar. See #902 for early design ideas.

**Comment by michaelpacer** [comment]
So for full feature parity notebook metadata and cell level metadata should probably be treated separately. 

In the classic notebook:
* notebook level metadata are editable from the "Edit → Notebook Metadata" menu dropdown. 
* cell level metadata are accessed by enabling cell level metadata editing with "View → Cell Toolbar → Edit Metadata" which enables the cell toolbar with an "Edit Metadata" button on the right hand side.

So, even if there is a metadata editor in the cell toolbar (for which I'm +1), it'd probably be good to have an additional/separate UI for editing the *notebook*'s metadata that doesn't appear in the L side *cell* toolbar, even if it means just having a L side *notebook* toolbar if only to avoid confusion. 

The other paradigm I could imagine would be that the notebook metadata is what is accessible when no cells are selected, but that seems a bit of a fraught solution.

**Comment by flying-sheep** [comment]
for feature partity with R notebooks, we also need to consider their advantages, e.g. in the field of metadata:

![image](https://cloud.githubusercontent.com/assets/291575/22099213/b3f3f5e4-de2a-11e6-8840-c5d53ec09853.png)

this is metadata for cell and notebook. note how the dialog for cell metadata has quite some features discoverable in the UI. furthermore cell metadata is autocompleted.

**Comment by yuvipanda** [comment]
I created my first JupyterLab extension to sort through this. You can try it out and check out the source code in https://github.com/yuvipanda/jupyterlab-nbmetadata

**Comment by jasongrout** [comment]
Leaving as 1.0, since we really should have this functionality in core. Perhaps by including @yuvipanda's extension?

**Comment by choldgraf** [comment]
hey all, friendly ping on this :-) did this get in to the RC1?

**Comment by bollwyvl** [comment]
Certainly seems like the right start: I'd like to see the nbformat schema
used to validate this metadata, a la settings, since you can definitely
break your notebook. Ideally this would be served live, since unlike
settings, etc. your server's nbformat is the source of Truth.

Also, so long as cell tools is notebook-only (right?) this should probably
merge with that sidebar.

**Comment by jasongrout** [comment]
FYI, I've included a basic notebook metadata editor in #5968.

**Comment by jasongrout** [comment]
Fixed in #5968.

**Comment by choldgraf** [comment]
Is this feature documented anywhere? I see lots of notes that make me think it's now possible to edit notebook metadata in JupyterLab, but I cannot figure out how to do this...

**Comment by saulshanabrook** [comment]
@choldgraf I don't believe it is documented, but it is available under the "Advanced Tools" section in the cell tools:
<img width="957" alt="Screen Shot 2019-06-19 at 2 06 31 PM" src="https://user-images.githubusercontent.com/1186124/59800416-73afd480-929b-11e9-82e3-3a4c9448c289.png">


If you find a place to document this, that would be much appreciated!

**Comment by choldgraf** [comment]
Hmmm, is that 'Advanced tools' thing activated somehow? I don't have that (running Lab `0.35.6`)

**Comment by saulshanabrook** [comment]
This was added after that release so only appears in the 1.0 releases (see the milestone on this is 1.0)

**Comment by choldgraf** [comment]
ah ok and none of those are up on pip unless you're using `--pre`. gotcha :-)

**Comment by choldgraf** [comment]
y'all I am excited for jupyterlab 1.0 :-)
