### ISSUE TITLE
Jupyter notebook crashing while running in chrome 

### ISSUE THREAD

**Issue by ddharshan** [jupyterlab/jupyterlab#13091]
Hi
i was training my model in jupyter notebook in google chrome for 7 hours. The chrome was crashed. Could anyone help me on this. my RAM is 8GB and windows 11??????

**Comment by jweill-aws** [comment]
Which version of JupyterLab are you using? (If you're using Jupyter Notebook, that project has its own issues repository: https://github.com/jupyter/notebook )

Can you provide info such as code and input data to help us reproduce this problem?

Does the problem recur when you run your notebook in ipython on the command line?

Jupyter kernels tend to do data loading and manipulation entirely in memory, so even with 8 GB of memory, training a complex model might exhaust your system's memory, causing problems.

**Comment by 3coins** [comment]
@ddharshan
Can you answer @jweill-aws questions, this will help debug this issue.

**Comment by ddharshan** [comment]
Previously I used Jupiter notebook which causes the chrome to crash .
However , once I downloaded the desktop version of Jupiter lab, I was able
to train my model without the memory issue.

**Comment by jweill-aws** [comment]
This issue seems to be a memory constraint issue rather than a bug in JupyterLab. I'm glad you were able to find a fix using the desktop version instead!
