### ISSUE TITLE
`Launch classic notebook` breaks image links?

### ISSUE THREAD

**Issue by jchwenger** [jupyterlab/jupyterlab#13095]
## Reproduce

1. Create notebook with a markdown cell and an image stored in a folder.
2. !\[my image\]\(images/image.jpg\)
3. Help → Launch Classic Notebook
4. Open the same notebook.
5. The image link is broken.

## Expected behavior

The image displays normally.

## Context

- Operating System and version: Ubuntu 18.04
- Browser and version: Firefox 104.0
- JupyterLab version: 3.4.4

Is there something I'm missing here?

Thanks for reading.

**Comment by jweill-aws** [comment]
There was a recent issue that was fixed concerning images in nbclassic: https://github.com/jupyter/nbclassic/issues/144

Other issues concerning images that work in JupyterLab but not in notebook/nbclassic:
* https://github.com/jupyter/notebook/issues/6267
* https://github.com/jupyter/nbclassic/issues/89

Do the behaviors in these issues match what you're seeing?

**Comment by jchwenger** [comment]
Brilliant, that's exactly that issue you mention. It does indeed work in notebook, not in nbclassic which I guess is invoked by lab. I guess it'll be fixed in the next update then, thank you.

**Comment by hhuuggoo** [comment]
Posting this because it took me some time to figure out - if you're running 3.4.7, you can get the fix by installing nbclassic=0.4.4. I wasn't clear on the relationship between jupyter lab/nbclassic/notebook/notebook_shim. For 3.4.7 nbclassic is what needs to be upgraded to pick up this fix.
