### ISSUE TITLE
Jupyter lab kernel is killed

### ISSUE THREAD

**Issue by Jisans** [jupyterlab/jupyterlab#13105]
When I use conda to create a virtual environment, I do not install jupyter lab in the created environment, but install jupyter lab in the base environment of conda. When I run code in the created environment, the kernel is killed. Why?

**Comment by davidbrochart** [comment]
Hi @Jisans,
It is considered a bad practice to install anything in the conda base environment. You should keep it minimal, and create new environments to install other packages, including JupyterLab.

**Comment by Jisans** [comment]
Hi @davidbrochart 
I think I understand what you mean. You mean that many software has been integrated in the conda base environment, and I continue to install other modules. This will lead to insufficient memory, which may be one of the reasons why the kernel is killed.

**Comment by davidbrochart** [comment]
That's not what I meant.
On the contrary, there should be the bare minimum installed in the base environment, but it has nothing to do with memory.
If you install JupyterLab in the base environment, it will not play well with your other environment. JupyterLab will look at the environment it is installed in (here, the base environment) for kernels, but your kernels will be installed in your other environment.

**Comment by Jisans** [comment]
It's strange that if we don't separate the jupyter kernel, we can run code in the conda base environment. What's the reason?

**Comment by Jisans** [comment]
@davidbrochart Thank you for your kind answer！
