### ISSUE TITLE
Add announcement feature

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13110]
### Problem

Add a way to send announcement to our user database.

The goal is to reach out to more users directly within the software rather than through our communication channel (gitter, discourse, GitHub,...).

This is not about gathering data from our users.

### Proposed Solution

- Serve statically a JSON file in a GitHub repository within the JupyterLab organization.
  - We can enforce PR rules to update that announcement like having two accepted reviews as a firewall.
  - Using such way, we will not record any information from user requests.
- Fetch from the server that announcement file.
  - ~~The statically fetch JSON URL will be configurable and will deactivate the feature if set to `None`.~~
  - The final implementation uses the Atom feed XML format.
- Display notifications with the current announcements in the frontend.
  - This will be in its own plugin to be disabled if required

### Additional context

Prior art:
- [JupyterHub simple announcement](https://github.com/jupyterhub/jupyterhub/tree/main/examples/service-announcement)
- [JupyterHub announcement](https://github.com/rcthomas/jupyterhub-announcement)
- [JupyterLab announcement](https://github.com/NERSC/nersc-refresh-announcements)

**Comment by bollwyvl** [comment]
If such a thing as this landed, it's probably worth it to consider all the external requests that might be generated here and elsewhere (e.g. extension managers talking to package upstreams, help pages that call out, and any CDN requests) and have a "big red button," which can gate access to what can be contacted, making it easy to say, `*`, don't make any requests.
