### ISSUE TITLE
Failed to build jupyterlab

### ISSUE THREAD

**Issue by yunkai2020** [jupyterlab/jupyterlab#13119]
Building wheels for collected packages: jupyterlab
  Building editable for jupyterlab (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building editable for jupyterlab (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [99 lines of output]
      INFO:hatch_jupyter_builder.utils:Running jupyter-builder
      INFO:hatch_jupyter_builder.utils:Building with buildapi.builder
      INFO:hatch_jupyter_builder.utils:With kwargs: {'build_cmd': 'build', 'source_dir': 'packages', 'build_dir': 'dev_mode/static', 'npm': ['node', 'jupyterlab/staging/yarn.js']}
      INFO:hatch_jupyter_builder.utils:Installing build dependencies with npm.  This may take a while...
      INFO:hatch_jupyter_builder.utils:> D:\package\nodejs\node.EXE jupyterlab/staging/yarn.js install
      yarn install v1.22.19
      warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. 
To clear this warning, remove package-lock.json.
      [1/4] Resolving packages...
      success Already up-to-date.
      $ node scripts/ensure-buildutils.js
     
      > @jupyterlab/buildutils@4.0.0-alpha.13 clean
      > rimraf lib && rimraf tsconfig.tsbuildinfo
     
     
      > @jupyterlab/buildutils@4.0.0-alpha.13 build
      > tsc && cd template && npm run build
     
     
      > @jupyterlab/template@4.0.0-alpha.13 build
      > tsc -b
     
     
      > @jupyterlab/builder@4.0.0-alpha.13 clean
      > rimraf lib && rimraf tsconfig.tsbuildinfo
     
     
      > @jupyterlab/builder@4.0.0-alpha.13 build
      > tsc
     
      Done in 23.54s.
      INFO:hatch_jupyter_builder.utils:> D:\package\nodejs\node.EXE jupyterlab/staging/yarn.js run build
      yarn run v1.22.19
      $ npm run build:dev
     
      > @jupyterlab/repo-top@0.0.1 build:dev
      > npm run integrity && npm run build:all && cd dev_mode && npm run build
      
     
      > @jupyterlab/repo-top@0.0.1 integrity
      > node scripts/ensure-buildutils.js && node buildutils/lib/ensure-repo.js
     
     
      > @jupyterlab/buildutils@4.0.0-alpha.13 clean
      > rimraf lib && rimraf tsconfig.tsbuildinfo
     
     
      > @jupyterlab/buildutils@4.0.0-alpha.13 build
      > tsc && cd template && npm run build
     
     
      > @jupyterlab/template@4.0.0-alpha.13 build
      > tsc -b
     
     
      > @jupyterlab/builder@4.0.0-alpha.13 clean
      > rimraf lib && rimraf tsconfig.tsbuildinfo
     
     
      > @jupyterlab/builder@4.0.0-alpha.13 build
      > tsc
     
      Error: EPERM: operation not permitted, symlink 'E:\work\workspace\python\jupyterlab\builder\lib\build-labextension.js' -> 'E:\work\workspace\python\jupyterlab\node_modules\.bin\build-labextension'
          at Object.symlinkSync (node:fs:1651:3)
          at E:\work\workspace\python\jupyterlab\buildutils\lib\ensure-repo.js:587:16
          at Array.forEach (<anonymous>)
          at ensureBuildUtils (E:\work\workspace\python\jupyterlab\buildutils\lib\ensure-repo.js:574:31)
          at ensureIntegrity (E:\work\workspace\python\jupyterlab\buildutils\lib\ensure-repo.js:774:5)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        errno: -4048,
        syscall: 'symlink',
        code: 'EPERM',
        path: 'E:\\work\\workspace\\python\\jupyterlab\\builder\\lib\\build-labextension.js',
        dest: 'E:\\work\\workspace\\python\\jupyterlab\\node_modules\\.bin\\build-labextension'
      }
      error Command failed with exit code 1.
      info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
      Traceback (most recent call last):
        File "D:\package\Python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "D:\package\Python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\package\Python38\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 283, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "C:\Users\HG\AppData\Local\Temp\pip-build-env-yamkeh81\overlay\Lib\site-packages\hatchling\build.py", line 101, in build_editable
          return os.path.basename(next(builder.build(wheel_directory, ['editable'])))
        File "C:\Users\HG\AppData\Local\Temp\pip-build-env-yamkeh81\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 136, in build
          build_hook.initialize(version, build_data)
        File "C:\Users\HG\AppData\Local\Temp\pip-build-env-yamkeh81\normal\Lib\site-packages\hatch_jupyter_builder\plugin.py", line 70, in initialize
          build_func(self.target_name, version, **build_kwargs)
          npm_builder(target_name, version, *args, **kwargs)
        File "C:\Users\HG\AppData\Local\Temp\pip-build-env-yamkeh81\normal\Lib\site-packages\hatch_jupyter_builder\utils.py", line 116, in npm_builder
          run(npm_cmd + ["run", build_cmd], cwd=str(abs_path))
        File "C:\Users\HG\AppData\Local\Temp\pip-build-env-yamkeh81\normal\Lib\site-packages\hatch_jupyter_builder\utils.py", line 225, in run
          return subprocess.check_call(cmd, **kwargs)
        File "D:\package\Python38\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['D:\\package\\nodejs\\node.EXE', 'jupyterlab/staging/yarn.js', 'run', 'build']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for jupyterlab
Failed to build jupyterlab
ERROR: Could not build wheels for jupyterlab, which is required to install pyproject.toml-based projects

**Comment by jweill-aws** [comment]
Your EPERM error suggests a permissions problem. Does your user have administrative permissions to make a symlink on the volume in question? If this is a network drive, do you see the same error when you try to build on a local drive?

Try the solution listed in this StackOverflow post: https://superuser.com/questions/104845/permission-to-make-symbolic-links-in-windows-7

**Comment by krassowski** [comment]
Do you have the [Windows Developer Mode](https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development) enabled? If that solves it: we mention it in [extension tutorial](https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html#build-and-install-the-extension-for-development) but **not** in the general contributing documentation, so maybe we should include it there too.

**Comment by jweill-aws** [comment]
@yunkai2020 We haven't heard back from you in about 3 weeks. Please try the suggestions listed above; if they don't solve your problem, please reopen this issue and let us know any specific additional errors you see. Thanks for your contribution!
