### ISSUE TITLE
Please check whether Secure Client-Initiated Renegotiation vulnerability exists.

### ISSUE THREAD

**Issue by WangChangsongGit** [jupyterlab/jupyterlab#13120]
## Description

I used the tool to scan port 8888 of the jupyterlab service and found a Secure Client-Initiated Renegotiation vulnerability. DoS attack risks exist. Please check for this problem and solution. Thank you.

## Reproduce

1. Start the Jupyterlab. The port number is 8888.
2. Use a tool to scan port 8888.
3. The report shows that the scanning result of Secure Client-Initiated Renegotiation is vulnerable.

## Expected behavior

No Secure Client Initiated Renegotiation Vulnerability

## Context

- Operating System and version: SUSE Linux Enterprise Server 12 (x86_64)
- Browser and version: 
- JupyterLab version: 
jupyter_client           7.3.5
jupyter-core             4.11.1
jupyter-telemetry        0.1.0
jupyterhub               1.2.2
jupyterlab               2.2.10
jupyterlab-pygments      0.2.2
jupyterlab-server        1.2.0
jupyterlab-widgets       3.0.3
notebook                 6.4.12

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by fcollonval** [comment]
Thanks a lot for reporting this @WangChangsongGit, could you open the issue in the upstream package [jupyter-server](https://github.com/jupyter-server/jupyter_server)? As that should be the place to solve this.

Important note for the future: it is best to not create a public issue to raise security questions. But rather send us an email [see Security.md](https://github.com/jupyterlab/jupyterlab/security/policy).

**Comment by jweill-aws** [comment]
Closing this per @fcollonval . Please follow our process for reporting a potential security vulnerability more privately.
