### ISSUE TITLE
Broken Link in documentation

### ISSUE THREAD

**Issue by kanitw** [jupyterlab/jupyterlab#1313]
On readthedocs.io, the more "plugins" link in [this page](https://jupyterlab-tutorial.readthedocs.io/en/latest/labextensions.html) links to an invalid (does not exist page) https://jupyterlab-tutorial.readthedocs.io/en/latest/plugins.md.

However, the link works fine on github:
(the link in https://github.com/jupyterlab/jupyterlab/blob/master/tutorial/labextensions.md
correctly links to https://github.com/jupyterlab/jupyterlab/blob/master/tutorial/plugins.md)

**Comment by blink1073** [comment]
Thanks for the heads up, @kanitw!
