### ISSUE TITLE
Tooltips (shift-tab) stopped working in code console of 3.4.7

### ISSUE THREAD

**Issue by zhizheng1** [jupyterlab/jupyterlab#13158]
Tooltips, i.e., shift-tab, has stopped working in the code console of jupyterlab 3.4.7. I tested it worked fine in 3.4.6 by "pip install 'jupyterlab==3.4.6'" with everything else being up-to-date.

To test: in latest version (3.4.7), create a code console, execute "dc={}" then type "dc" and press "shift-tab". Nothing happened. All fine in 3.4.6 though.

Note: shift-tab works fine in notebooks and editors, just not working in the console (3.4.7).

**Comment by krassowski** [comment]
I can reproduce this. The tooltip gets `jp-mod-outofview` class indicating that this is caused by changes in #13046.

**Comment by krassowski** [comment]
Would you mind checking if it works as expected on binder in https://github.com/jupyterlab/jupyterlab/pull/13161#issuecomment-1264745497?

**Comment by zhizheng1** [comment]
Confirmed it's been fixed on the binder, thank you!
