### ISSUE TITLE
Installing Lab Extensions in Offline Environment

### ISSUE THREAD

**Issue by fny** [jupyterlab/jupyterlab#13150]
### Problem

I need a way to install lab extensions in always-offline environments. I've tried a few hacks, none have worked.

My current workflow is as follows: build a conda environment with the packages I need, and then I use conda-pack to archive the environment. The archive is then uploaded to a server for use. Everything works perfectly. Extensions entirely encapsulated within a pip repository also work.

However, the Jupyter Lab Extensions that depend on Node break. I've attempted to download the repository, npm install the packages, and then run `jupyter labextension link .` But that didn't work.

It would be really nice for there to be a sanctioned "plug and play" path.

**Comment by jweill-aws** [comment]
Hey @fny, thank you for your contribution! This has come up several times before. It looks like extension work (mainly for dev, but also affecting installs) is being tracked in #5236, although this issue has gone quiet lately. Might be good to follow up in the older issue. For now, I'm going to resolve this as a duplicate, but feel free to reopen if you feel that this request is significantly different.
