### ISSUE TITLE
Side-by-Side rendering: cell toolbar disappears

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13166]
## Description

Using Side-by-Side rendering, the cell toolbar might disappear in some situations:

https://user-images.githubusercontent.com/591645/193530736-40eccc9e-d36e-4608-b4d0-b666d0ce4a6c.mp4

## Reproduce

1. Create a new notebook
2. Add a new cell
3. Switch to `Side-by-side` rendering (`View > Render Side-by-Side`)
4. type `import this`, execute
5. The cell toolbar is gone for that cell

## Expected behavior

The cell toolbar should still be available when executing the stes described above.

## Context

- Operating System and version: Fedora 36
- Browser and version: Chrome 106
- JupyterLab version: 4.0.0a29

**Comment by jweill-aws** [comment]
Related: #12223, a request to show the cell toolbar (at least in part) if it would overlap the content.
