### ISSUE TITLE
Virtual Notebook: `Uncaught TypeError: Cannot read properties of undefined (reading 'model')`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13165]
## Description

Switching cell types might lead to the following error message logged in the browser dev tools console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'model')
    at NotebookViewModel.estimateWidgetSize (windowing.js:28:1)
    at NotebookViewModel._getItemMetadata (windowedlist.js:388:1)
    at NotebookViewModel.setWidgetSize (windowedlist.js:332:1)
    at Notebook._onWidgetResize (windowedlist.js:802:1)
```

This seems to be coming from this line:

https://github.com/jupyterlab/jupyterlab/blob/65b4d7e727aed343160d81fad7f1871758ff7f22/packages/notebook/src/windowing.ts#L50

## Reproduce

1. Create a new notebook
2. Switch the first cell to markdown

https://user-images.githubusercontent.com/591645/193527832-80d0fd7a-98c9-4340-8657-35ed3517f0a9.mp4

## Expected behavior

No error message should be printed in the dev tools console

## Context

- Operating System and version: Fedora 36
- Browser and version: Chromium 106
- JupyterLab version: 4.0.0a29

cc @fcollonval

**Comment by fcollonval** [comment]
Closing as solved on master by https://github.com/jupyterlab/jupyterlab/pull/13137

**Comment by jtpio** [comment]
Ah nice thanks for the fix!
