### ISSUE TITLE
"Search Cell Outputs" Find/Replace is disabled when Replace is expanded, without an indication why

### ISSUE THREAD

**Issue by vitorlppf** [jupyterlab/jupyterlab#13167]
While using the Find/Replace feature I came across the following bug: the "Search Cell Outputs" can't be toggled while the Replace submenu is active. In principle, this is reasonable, as you can't replace the output of a cell. However, if the toggle was active before using the submenu (as is the default) the Find still searches and returns cell output. Thus you have to deactivate the Replace submenu in order to toggle the option off, and then resume trying to Find and Replace cell inputs.

I propose the toggle should be overridden and set to not search cell output while the Replace submenu is active, and return to the last toggled value after the submenu is deactivated.

I found this old issue which coincidentally includes a GIF depicting the described behaviour. Note how the "Search Cell Outputs" toggle turns grey once the Replace submenu is activated.

> Hi @LuckyMD this was implemented in #10067 and is included in JupyterLab 3.1 which is now in release candidate phase (please help testing it if you would like to try out this feature). Example:

![test2](https://user-images.githubusercontent.com/5832902/125598493-e89084df-da98-4131-8825-b0606de82dc3.gif)

_Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab/issues/6650#issuecomment-879741501_

**Comment by krassowski** [comment]
Related to https://github.com/jupyterlab/jupyterlab/issues/6650

**Comment by fcollonval** [comment]
For information this will be corrected in JupyterLab 4 - screencast below taken from JupyterLab 4.0.0a29

![jlab4-search-replace](https://user-images.githubusercontent.com/8435071/194499239-2400beb8-7d08-4476-8425-581de8100ac3.gif)

**Comment by JasonWeill** [comment]
I can confirm that the "search cell outputs" filter is disabled in Lab 4, but it's not clear why this filter is disabled. This could be improved by, for example, modifying the tooltip to explain that the user can't search cell outputs when the "replace" options are shown.
