### ISSUE TITLE
JL 4 regression: JSON settings editor not scrollable by scrollbars or mouse

### ISSUE THREAD

**Issue by firai** [jupyterlab/jupyterlab#13162]
## Description

The JSON settings editor CM widgets don't show scrollbars when the contents overflow, and they aren't scrollable by mouse wheel. Arrow keys do work though.

![Json Editor](https://user-images.githubusercontent.com/23555/193504075-8a87d04b-2860-4cfc-8c2e-ee87c54de44d.gif)

## Reproduce

1. Open the JSON settings editor through the setting editor.
2. Open any of the settings sections which have long defaults.

## Expected behavior

JSON editor widgets scrollable by scrollbars and by mouse wheel, in addition to scrolling by keyboard.

## Context

- Operating System and version: Windows 11
- Browser and version: Firefox 105.0.1 and Chrome 106.0.5249.91
- JupyterLab version: 65b4d7e (The bug does not appear in 3.4.7. I'm assuming it's caused by the upgrade to CM 6.)

**Comment by firai** [comment]
@meeseeksdev tag "pkg:settingeditor"

**Comment by gabalafou** [comment]
I found this bug as well while trying to edit keyboard shortcuts. Page up / page down keys also work, though not quite correctly; sometimes they over-scroll, sometimes they under-scroll.
