### ISSUE TITLE
Should terminal font honor user's Monospace choices in the browser?

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab#1317]
I know full-blown font/theme terminal customization is a can of worms, but I wonder if allowing at least the terminal component to honor the user's choice of monospace font in the browser makes sense.  I just tried and it didn't have any impact, at least on Chrome on OSX.  

My rationale is that we can imagine the user has chosen a mono font they otherwise like and that works well for them in general, so giving them that baseline may do the 80/20 job on this issue...

Thoughts?

**Comment by blink1073** [comment]
IIUC this is a matter of setting `font-family: monospace` instead of the more specific specifier here: https://github.com/jupyterlab/jupyterlab/blob/23e4bfe8cfcc04e280d7d34a30926971097564cd/src/terminal/index.css#L18.

cc @cameronoelsen, thoughts on this?

**Comment by cameronoelsen** [comment]
@blink1073 @fperez How many users have a monospace font preference for terminals? Like the only way I would see this being incorporated would be in the top menus in the terminal settings. I just don't know how many users would use it

**Comment by fperez** [comment]
No, the point is that users are likely to have their browser-wide monospace font selected, and we should honor that.  Right now, by having explicit choices in advance, it seems that if those aren't found, the default user's choice gets overridden.

At least that's what I'm observing on OSX with Chrome 54: I have menlo as my monospace font, but instead at the terminal I'm getting something else that looks hideous.  I don't have DejaVu Sans Mono available, so it seems that Chrome, instead of falling back to my monospace choice, is instead picking some internal fallback (Courier New, I think).

I know this is a tricky one, perhaps you prefer to provide actual JLab-specific customization.  I'm thinking of having a reasonable fallback for the folks at large who won't look into customizing JLab specifically but simply set their browser preferences once and forget about it everafter.

**Comment by fperez** [comment]
Yup, just to confirm that the small change suggested by @blink1073 does the trick. See here, current master at the top, with the change at the bottom:

![image](https://cloud.githubusercontent.com/assets/57394/20898181/3fcf3980-bada-11e6-8f7a-b7c9bd16696e.png)

Now, looking at [the code](https://github.com/jupyterlab/jupyterlab/blob/23e4bfe8cfcc04e280d7d34a30926971097564cd/src/terminal/index.css#L18) makes me wonder why that `"DejaVu Sans Mono", "Liberation Mono"` declaration is there at all, esp. in light of the L26 below, whose intent seems to be to allow the monospace declaration to be the default.  Is it possible that L18 is a stale remnant?

If so, I'm happy to make the (trivial, obviously :) cleanup PR...

**Comment by blink1073** [comment]
Found where it came from, though I don't know what my original logic was (other than Googling about how to set a monospace font), I'll open the PR to fix it.

https://github.com/jupyter-attic/jupyter-js-terminal/commit/c8f3210680207deaf0a70456be2c136b0231db2b#diff-b3c787053edaeedadf1a2430f41506f2

**Comment by fperez** [comment]
Great, thx!
