### ISSUE TITLE
New cell when copy and paste in the markdown

### ISSUE THREAD

**Issue by ambrolla** [jupyterlab/jupyterlab#13179]
## Description

When I copy a paragraph from the other source and paste it into the jupyterlab, then I can not create a new cell near the cell where I've copied and paste a new paragraph as a markdown cell. 

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by jweill-aws** [comment]
@ambrolla Can you please provide the info requested above (version of JupyterLab and screen shots or video)? Thanks!

**Comment by jweill-aws** [comment]
@ambrolla We haven't received any additional information that could help us triage this issue. I'm going to close this issue, but if you have additional screen shots or video as requested above, please reopen. Thanks for your contributions!
