### ISSUE TITLE
Wrong shortcut for "delete cell" hotkey in cell toolbar

### ISSUE THREAD

**Issue by ambrolla** [jupyterlab/jupyterlab#13180]
## Description

When I want to delete a certain cell, I need to press D twice, when in the hot key description it said to press D once. 

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by ambrolla** [comment]
> @ambrolla, where are you seeing this? I have jupyterlab 3.4.7 installed, In the menu when I go to `View`-> `Activate Command Palette` ![image](https://user-images.githubusercontent.com/1798497/193896167-0fc24b77-4d26-48b4-aa7d-67686a8074ca.png)
> 
> Then within the command palette I type `delete` and it brings up the below results: ![image](https://user-images.githubusercontent.com/1798497/193896308-b94933ff-884b-46c7-913d-54e402b45c25.png)
> 
> For `Delete Cells` it says to do `D, D` showing D twice.

![example_github](https://user-images.githubusercontent.com/27083525/193898854-2ae35ec2-36a9-44ad-8fe9-ca749ac40298.png)

When I'm in the Jupyter notebook and my mouse is over the delete cell (I couldn't show it on my print screen, it didn't want to take a print screen with my mouse over and text directions), it shows "Delete Cells (D)", not double D. I had to ask an experienced user about how to I delete something using hot keys. 
Screenshot is attached.

**Comment by afonit** [comment]
Thank you for the additional information, I now see it.
I have taken a screenshot with the popup which appears from hovering over the cell trash can:
![image](https://user-images.githubusercontent.com/1798497/193900427-cb93aa4e-27a7-4868-ab37-3c55f6f83fa9.png)

**Comment by ambrolla** [comment]
Yes, that's the bug/issue. :)

**Comment by afonit** [comment]
Adding some notes in here:
It looks like the cell toolbar is built from here:
https://github.com/jupyterlab/jupyterlab/blob/3.4.x/packages/cell-toolbar-extension/schema/plugin.json#L22

I am trying to find where the tooltip text is coming from.

**Comment by afonit** [comment]
I verified that the tooltips for the other icons/commands match what is shown in the command pallet:
[x] Move cells up (CTRL+Y)
[x] Move cells down (CTRL+E)
[x] Insert cell above (A)
[x] Insert cell below (B)

When we find the delete cells tooltip source it will be interesting to see if these shortcuts are hard coded and not being pulled from wherever the command pallet pulls its keyboard shortcuts from.

**Comment by ambrolla** [comment]
The other commands, so far, looked fine! The only problem was with Delete command. 
There was another issue that I've also noticed, but I've created another request for it.
