### ISSUE TITLE
Debugger: line numbers are lost when running a cell and advancing

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13199]
## Description

Line numbers are lost when debugging is enabled and new cells are created (using the run toolbar button).

## Reproduce

https://user-images.githubusercontent.com/591645/194505482-1584af7d-7aef-4d2d-849b-3cc479dd8d2c.mp4

## Expected behavior

Line numbers should be preserved.

Behavior looks fine when debugging is **not** enabled:

https://user-images.githubusercontent.com/591645/194505440-c98e9ff8-77f9-471b-be0a-72fc70224d49.mp4

## Context

- Operating System and version: Fedora 36
- Browser and version: Firefox 105
- JupyterLab version: latest `master`: https://github.com/jupyterlab/jupyterlab/commit/596f682721b66d04e250b7f08f2e8537f51d365c

Probably an issue introduced during the CodeMirror 6 migration: https://github.com/jupyterlab/jupyterlab/pull/11638

**Comment by firai** [comment]
It seems like the issue is specifically with the last inserted cell when the line number setting is **off**, until another cell gets inserted or deleted:

![Line numbers](https://user-images.githubusercontent.com/23555/194604435-d00a279c-205e-4bbc-9331-e06587e44b13.gif)
