### ISSUE TITLE
Customizable hook for pinfo (?) akin to _ipython_display_

### ISSUE THREAD

**Issue by b3m2a1** [jupyterlab/jupyterlab#13217]
### Problem

I often want ? to provide me with much richer information that it does. I'd like the ability to hook nice widgets/interactive information modules info the `?` interface. For now, I can display them with `_ipython_display_` but I'd like if there were a similar hook I could use to do things like

```python
?SomeExampleClass(...)

<displays a little object explorer>
```
or

```python
?SomeExampleClass

<displays interactive examples>
```

### Proposed Solution

Add a magic method like `__pinfo_display__` that can be used to generate informative displays through the `pinfo` method

### Additional context

Here's an example of what I imagine this looking like (the app is just a random sample app; the real deal would be much more help oriented)

<img width="1631" alt="Screen Shot 2022-10-11 at 3 01 26 AM" src="https://user-images.githubusercontent.com/18367787/195032923-2cc2394f-ce24-47e0-bb0b-817ac6fdc8a6.png">

I can make that app no issue and make it nicely interactive but I can't figure out how to hook it into the help system

**Comment by jweill-aws** [comment]
Triage notes:

@Carreau is building [papyri-lab](https://github.com/carreau/papyri-lab) (see also [papyri](https://github.com/jupyter/papyri)) that may add similar functionality.

Modifying the `?` behavior should probably go first into [an ipykernel issue](https://github.com/ipython/ipykernel/issues); JupyterLab would then display the output of ipykernel interactively, as you describe.

Can you please take a look at the links above? If your idea is different and you would like to keep the proposal open, please also open an issue against ipykernel and link it here.

**Comment by b3m2a1** [comment]
Opened https://github.com/ipython/ipykernel/issues/1005

**Comment by b3m2a1** [comment]
See my further comments there for a way to monkey patch this in while I wait for it to be integrated into the system

**Comment by krassowski** [comment]
Closing as this cannot be solved by JupyterLab - this is an IPython enhancement request.

FYI recent versions of IPython introduced as MIME hook for customising the pinfo output, for reference see
- https://github.com/ipython/ipython/pull/14342
- https://github.com/ipython-contrib/ipython-markdown-inspector
