### ISSUE TITLE
JupyterLab 3.6.0 Release

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13221]
This is a meta issue to list enhancement candidates for the next minor release 3.6.

- [x] RTC upgraded to the newest API implemented for 4.0.0
  - [x] https://github.com/jupyterlab/jupyterlab/pull/13222
  - [x] https://github.com/jupyterlab/jupyterlab/pull/13242
  - [x] https://github.com/jupyterlab/jupyterlab/pull/13274
  - [x] https://github.com/jupyterlab/jupyterlab/pull/13296
  - [x] User service https://github.com/jupyterlab/jupyterlab/pull/12926
  - [x] File ID optional integration: https://github.com/jupyterlab/jupyterlab/pull/13246
  - [x] https://github.com/jupyterlab/jupyterlab/pull/13317
  - [x] https://github.com/jupyterlab/jupyterlab/issues/13332
  - [x] Add runtime check in collaborative mode for jupyter-server v2 and jupyter-server-ydoc
- [x] https://github.com/jupyterlab/jupyterlab/pull/12959
- [x] https://github.com/jupyterlab/jupyterlab/pull/13365
- [x] https://github.com/jupyterlab/jupyterlab/pull/13216
- [x] release new 1.x lumino and include it to pull https://github.com/jupyterlab/lumino/pull/432 and others
  - [x] https://github.com/jupyterlab/jupyterlab/pull/13378
- [x] https://github.com/jupyterlab/jupyterlab/pull/13284
- [x] https://github.com/jupyterlab/jupyterlab/pull/13289
- [x] https://github.com/jupyterlab/jupyterlab/pull/13037
  - [x] https://github.com/jupyterlab/jupyterlab/pull/13300
- [x] https://github.com/jupyterlab/jupyterlab/pull/13321
- [x] https://github.com/jupyterlab/jupyterlab/pull/13341
- [x] https://github.com/jupyterlab/jupyterlab/pull/13255
- [x] https://github.com/jupyterlab/jupyterlab/pull/12502

**Comment by bollwyvl** [comment]
> RTC upgraded to the newest API implemented for 4.0.0

And this will require the full server-side yjs stack?

**Comment by davidbrochart** [comment]
Yes.

**Comment by bollwyvl** [comment]
Is the runtime dependency on the server still gated behind a `collaborative` flag, or will the entire experience fail hard without the new server?

**Comment by davidbrochart** [comment]
Yeah I think that the `collaborative` flag will make JupyterLab's front-end access the "Y WebSocket", so as long as it doesn't do that I don't think you need the new server.

**Comment by mlucool** [comment]
Can we backport https://github.com/jupyterlab/jupyterlab/pull/12502 to be included here? cc @telamonian

**Comment by jtpio** [comment]
FYI I started updated to the JupyterLab 3.6 packages downstream in https://github.com/jupyterlite/jupyterlite/pull/876 to help catch potential issues and breaking changes early.

**Comment by fcollonval** [comment]
Thanks @jtpio

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlab/jupyterlab/pull/13490 which might help fix one.

**Comment by jtpio** [comment]
Looks like we could make a new 3.6 alpha release now that https://github.com/jupyterlab/jupyterlab/pull/13490 has been merged.

Maybe after CI has been stabilized (https://github.com/jupyterlab/jupyterlab/pull/13515 and others).

**Comment by jtpio** [comment]
For those following this issue, the first 3.6 beta (`3.6.0b0`) was released two weeks ago: https://github.com/jupyterlab/jupyterlab/releases/tag/v3.6.0b0

**Comment by fcollonval** [comment]
JupyterLab 3.6.0 has been released
