### ISSUE TITLE
Handle file IDs

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#13233]
### Problem

In RTC, a WebSocket is opened for sending an receiving updates to the shared document. The WebSocket endpoint path has the path to the document, which is used to identify the shared document in the back-end. When the document is renamed in the front-end, the shared document in the back-end must be renamed accordingly. The WebSocket is closed and a new one is opened at an endpoint with the new document path.
Currently, renaming a file goes through an HTTP request, not through the WebSocket. HTTP requests happen on a completely parallel "channel", which means that there is no guarantee that it will arrive before the front-end opens the new WebSocket. In other words, the front-end could start sending updates to the renamed document without the back-end knowing that the document was renamed. To prevent that, there is a "rename acknowledge" mechanism which consists of the front-end waiting for a reply to the HTTP request from the back-end to make sure that it knows that the file was renamed.

### Proposed Solution

With the file ID service that was recently introduced in jupyter-server, this synchronization mechanism could go away, if we used the file ID instead of the file path in the WebSocket endpoint, because the file ID would not change even if the file was renamed. There would be no need to open a new WebSocket.
This means that JupyterLab also has to manage file IDs. For instance, before opening a document, it could make an HTTP request to the server to get the ID of the file, then open the WebSocket with this ID instead of the document path. It could also listen to the event bus to be notified that the file was renamed by someone else, and update the document path in the UI (this is not particular to RTC).
Thoughts?

**Comment by ellisonbg** [comment]
I do think this will simplify things significantly. Also, without the file id service, if a user renames/moves the file in the terminal, they will lose the history of the document.

**Comment by ellisonbg** [comment]
@dlqqq

**Comment by ellisonbg** [comment]
A few notes on the implementation...

* I think a good place to inject the file id is in the `Context` object in the document registry (https://github.com/jupyterlab/jupyterlab/blob/master/packages/docregistry/src/context.ts).
* When a context is created, we could make an async call to the file id service that gets the id for the path. The file id could then be added as a public attribute to `Context`. To coordinate this being an async call, we should not fire `Context.ready` promise until the file id has been retrieved.
* We can then take steps to begin using the file id to handle path changes in the context. One option is for the Context to poll the file id service and automatically update its path in response. Another option would be to use the new Event system to make these updates. For 3.x, we will have to work around the fact that most methods of `Context` are not async, so we can't dynamically fetch the path each time it is needed.
* Downstream users of Context should be able to use its existing path based APIs or the file id to do their work.

**Comment by davidbrochart** [comment]
I opened https://github.com/jupyter-server/jupyter_server_fileid/pull/12 for a `GET /api/fileid/{path}` handler.

**Comment by davidbrochart** [comment]
I opened #13246.
