### ISSUE TITLE
Better way to register a new editor widget factory

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#1323]
We have plugins which register new editor widget factories for special options, e.g. custom languages. Now we stumble across the problem that we should align them and integrate somehow with `editorwidget` plugin, e.g. for [instance tracking](https://github.com/jupyterlab/jupyterlab/issues/1318) by accessing the tracker and state management by copying code around `IStateDB`.

It would be nice if one can just register a new factory and specify a way to get an editor from the created widget and JLab will take care about the rest.

**Comment by blink1073** [comment]
@akosyakov, did #1333 address this concern?

**Comment by akosyakov** [comment]
@blink1073 should be enough

**Comment by blink1073** [comment]
Great, closing then.  Feel free to reopen.
