### ISSUE TITLE
Ask for confirmation when closing a tab

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13258]
### Problem

Some users want to get a confirmation dialog to show up when they close a tab.

> Currently a confirmation dialog is opened only if the document is in a dirty state.

### Proposed Solution

Add an option to always display a close confirmation dialog.

### Additional context

N/A

**Comment by alec-kr** [comment]
Is this issue suitable for a beginner? If so, I'd like to work on it, with some guidance.

**Comment by fcollonval** [comment]
Hey @alec-kr, sure it is adequate.

First of all, the logic to test if a document will close or not is at

https://github.com/jupyterlab/jupyterlab/blob/c835a9ae35b13707b27c840603a8701ee2e5b89a/packages/docmanager/src/widgetmanager.ts#L336

That function returns two booleans: `[shouldClose, ignoreSave]`. To implement this, we should ask the user a confirmation to close the document (if the option is set to true) at L340 (first thing to do). Then if does not want to close returns `[false, true]` else continue.

Passing a flag to turn on/off that feature is more tricky. But here are pseudo step to achieve it:

1. Add an attribute to `DocumentWidgetManager` to store the option to request or not confirmation. The best is to add a private attribute. You can look at `_registry` as an example how to add an attribute. Then add a `get` and `set` method for that option.
https://github.com/jupyterlab/jupyterlab/blob/c835a9ae35b13707b27c840603a8701ee2e5b89a/packages/docmanager/src/widgetmanager.ts#L24
2. Modify the `_maybeClose` method to ask the user if he really wants to close the document (if the option is true). You can look a bit further for an example how to display a dialog:
https://github.com/jupyterlab/jupyterlab/blob/c835a9ae35b13707b27c840603a8701ee2e5b89a/packages/docmanager/src/widgetmanager.ts#L371
3. Add a setting like autosave in https://github.com/jupyterlab/jupyterlab/blob/c835a9ae35b13707b27c840603a8701ee2e5b89a/packages/docmanager-extension/schema/plugin.json#L113
4. Add a getter and setter for the new option in `DocumentManager` like for autosave (the difference is that you will store the attribute value in `this._widgetManager.<option>`) 
https://github.com/jupyterlab/jupyterlab/blob/c835a9ae35b13707b27c840603a8701ee2e5b89a/packages/docmanager/src/manager.ts#L79
5. Connect the new option in `DocumentManager` with the setting; see how it is done for autosave:  
https://github.com/jupyterlab/jupyterlab/blob/c835a9ae35b13707b27c840603a8701ee2e5b89a/packages/docmanager-extension/src/index.tsx#L243

I advice you to open a PR early so we can provide guidance.

**Comment by alec-kr** [comment]
I added something like this in #13267 :

```
if (!shoudClose) {
    return Promise.resolve([false,true]);
}
continue;
```

Please advise.

**Comment by jtpio** [comment]
> Add an option to always display a close confirmation dialog.

Also this option should ideally be opt-in (disabled by default).
