### ISSUE TITLE
Cell toolbar shows up on collapsed cells even when shrunk

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13254]
## Description

Cell toolbar shows up on collapsed cells even when shrunk.

## Reproduce

![Screenshot from 2022-10-16 22-05-06](https://user-images.githubusercontent.com/5832902/196058281-515cf429-334e-41e1-96b3-5d214b21f4d3.png)

1. Create a second cell, enter it
2. Collapse the cell
3. See the cell toolbar stays even when it should be disabled due to space constraints (too narrow window)

## Expected behavior

Cell toolbar is either:
- not visible on collapsed cells
- not visible on collapsed cells on narrow screens to avoid visual overflow and inability to click on the expand button

## Context

- Browser and version: Chromium
- JupyterLab version: 3.x and 4.0.0a30

**Comment by JasonWeill** [comment]
The cell toolbar continues to show up on collapsed cells using JupyterLab 4.0.0a33, as available on Binder here: https://gist.github.com/jtpio/c4b6376bfbd00474b3c0d1d60fe23670

![image](https://user-images.githubusercontent.com/93281816/217975616-b0e31c90-8c8f-4b4a-bdc6-670095dffb3f.png)

**Comment by JasonWeill** [comment]
Neither the `activeCellChanged` nor the `cellCollapsed` events on the Notebook (`panel.content`) get emitted when I click on the InputCollapser.
