### ISSUE TITLE
load exact session

### ISSUE THREAD

**Issue by hainm** [jupyterlab/jupyterlab#1326]
Hi,

is there any way to load exact notebook session I made?

supposed I created a layout like below and want to reproduce that layout without spending much time.

![lab2](https://cloud.githubusercontent.com/assets/4451957/20727250/bf5d6e80-b646-11e6-84dc-98f859d5aa8c.png)

cheers

**Comment by blink1073** [comment]
Hi @hainm, are you wanting save this layout across restarts of the computer and be able to launch as e.g. `jupyter lab --layout my_layout.dat`, or just while a given server session is running?   If it is the latter, we are tracking that part in #502.

**Comment by hainm** [comment]
> jupyter lab --layout my_layout.dat

just like that. thanks. (or there is a button to 'Load layout')

> just while a given server session is running? If it is the latter, we are tracking that part in 

yes too. I should search the issues more carefully. thanks. close now and cheers.

**Comment by blink1073** [comment]
Sorry, I didn't mean to imply that that command existed now.   Let's leave this open to track that part.

**Comment by blink1073** [comment]
Oh, ha, apparently I didn't read the other issue carefully, this is in fact a duplicate.   Cheers!
