### ISSUE TITLE
Re-introduce Jupyter Notebook's "feature" of exposing window.IPython to JavaScript.

### ISSUE THREAD

**Issue by jt0dd** [jupyterlab/jupyterlab#13278]
### Problem

I want to develop a platform within Jupyter with better styling than Widgets by using HTML/JavaScript. I don't want to require the user to install a plugin (since I believe the functionality is there, just hidden by the code packer).

If you're dubious about my use-case, that's probably fair. Here's what I have in mind:

https://github.com/jt0dd/share/blob/main/diag-gui.drawio.png

The "missing" link (again I believe just hidden by the web packer during build) In Jupyter Notebook is the feature described in this StackOverflow question:

https://stackoverflow.com/questions/30902898/ipython-notebook-javascript-retrieve-content-from-javascript-variables

They're complaining about something that's not really a good use-case (trying to make the anync JS code affect the current cell's synchronous output) but just the capability to access IPython is what I'm referring to.

JavaScript executed within a cell accesses `window.IPython` and tells Jupyter to execute some Python.  This works just fine in Jupyter Notebook: `Javascript('''IPython.notebook.kernel.execute("my_out = 'hello world'");''')`. But fails in JupyterLab.

### Proposed Solution

Just expose it. Do something with the packing process to allow the JS executed by a cell to see it. Perhaps you're hiding it on purpose for security. Probably not, but let's say you were defending against some kind of XSS. It should be safe to expose it to the `this` context of JS code executed by a code cell.

I'm about to spend so much time reverse engineering the web packing to locate the variable, when the feature could just be easy.

**Comment by jt0dd** [comment]
And honestly if you guys weren't going to do this but just dropped me a hint about how to approach my RE or even just the most relevant files in the project for IPython being accessed / used, I would appreciate even that much help.

**Comment by krassowski** [comment]
There is a prior discussion in https://github.com/jupyterlab/jupyterlab/issues/5660 and a current discussion in https://github.com/jupyter/notebook/issues/6394.

**Comment by jweill-aws** [comment]
@jt0dd Thank you for your contribution! Per @krassowski 's comment above, I'm going to close this issue in favor of the older issues mentioned. This object is not yet made visible — we recommend writing an extension for this purpose — but the issues above are open, and I think it's best to continue the discussions there instead. I appreciate your interest in JupyterLab.
