### ISSUE TITLE
Jitter when switching cell type to Markdown (4.0 regression) 

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13281]
## Description

Switching cell to markdown causes a jitter: the cell goes into rendered mode and then back to edit mode.

## Reproduce

1. Create code cell
2. Change it type to markdown
3. See jitter (rendered and the unrendered)

## Expected behavior

Switches without jitter

## Context

- Browser and version: Edge 106
- JupyterLab version: HEAD

**Comment by afshin** [comment]
I added the `help wanted` label to encourage anyone with access to an Edge browser and the ability to build JupyterLab from source to try it out.

**Comment by krassowski** [comment]
Thank you for testing this with a recent version! I verified that this was present up until 4.0.0a33 and fixed since 4.0.0a34, closing as no longer an issue.

> Chrome/Edge should be no different for most JS logic but I did see some differences in CSS performance between them even though both are Chromum based.
