### ISSUE TITLE
Pandas Reference not showing up

### ISSUE THREAD

**Issue by Horta** [jupyterlab/jupyterlab#1329]
Help -> Pandas Reference

It opens a blank panel. The does not happen with numpy reference.

**Comment by blink1073** [comment]
Thanks for the report, @Horta!

**Comment by blink1073** [comment]
It appears to be working for me, are you able to load `http://pandas.pydata.org/pandas-docs/stable/?v=20160707164940` in its own browser tab?   

If that works, can you please try restarting lab and see it the site was temporarily down?   
If it works in a separate tab and not in lab, can you please open the browser JavaScript console and get the following?

![image](https://cloud.githubusercontent.com/assets/2096628/20754262/bc48a370-b6cf-11e6-9660-e0ff7001b64a.png)

**Comment by Horta** [comment]
![screen shot 2016-11-30 at 13 44 28](https://cloud.githubusercontent.com/assets/514522/20754531/4167424a-b703-11e6-8c5f-db311d84c8b7.png)

**Comment by Horta** [comment]
I guess it is https issue...

I had restarted lab before and tried again. Also, I can access the link you showed and see the content.

**Comment by blink1073** [comment]
Nice detective work, I opened #1331 with the fix.

**Comment by Horta** [comment]
The whole jupyter is great and is going to change science. Happy to help you =)

**Comment by blink1073** [comment]
It looks like the original reason those were not added as `https` compatible links is because the source urls do not have valid https certificates.  This was not an issue in the classic notebook because the link brought you to a new browser tab.  Unfortunately iframes are not as sandboxed as we need them to be, and we may need to revert to the classic behavior in this case.

**Comment by afshin** [comment]
I think a reasonable workaround to this would be to have the help plugin detect if it is being served via HTTPS. If it is, then it should launch the HTTP pages in a different window, and it should only load the known HTTPS resources inside JupyterLab. While it's not great, it's a way to at least keep links to all of these other helpful sites without breaking the experience.
