### ISSUE TITLE
Pressing esc should exit Find and Replace

### ISSUE THREAD

**Issue by charizard-knows** [jupyterlab/jupyterlab#13311]
## Feature request
After using a search and replace function of Jupyter lab by using `Ctrl + F` it is annoying when you cannot exit it by pressing `esc` 

## Describe the solution you'd like
 I suggest adding a keybinding to exit search and replace when you press the esc key. This will not only be inline with normal conventions but also add productivity as users don't need to reach for the mouse to exit the Find and Replace

## Describe alternatives you've considered
Using mouse to exit the Find and Replace

## Additional context

- Python package version: 3.8.0
- IPython          : 8.4.0
- ipykernel        : 6.13.1
- ipywidgets       : not installed
- jupyter_client   : 7.3.3
- jupyter_core     : 4.10.0
- jupyter_server   : 1.17.1
- jupyterlab       : 3.4.7
- nbclient         : 0.6.4
- nbconvert        : 6.5.0
- nbformat         : 5.4.0
- notebook         : 6.4.12
- qtconsole        : not installed
- traitlets        : 5.2.2

- Operating System and its version:
Windows 10

**Comment by jweill-aws** [comment]
Pressing <kbd>ESC</kbd> will dismiss the search/replace UI when that UI has the focus. I agree that adding this keybinding even when the search/replace box isn't focused is a good idea. Thank you for your contribution @charizard-knows !

**Comment by krassowski** [comment]
Hi @charizard-knows I opened #13340 to improve the behaviour. It is targeting 4.0 release. I do not plan to backport it myself because there were extensive changes in search-and-replace between 3.x and 4.0, but if you or someone else would like to backport it, I am happy to review.
