### ISSUE TITLE
JupyterLab explorer become slower in symbolic link nested at azure fileshare

### ISSUE THREAD

**Issue by linlol** [jupyterlab/jupyterlab#13326]
## Description

I am sorry that this actually shall **not** be a bug but I am unable to find out another proper classificaiton...

Also, I am sorry that I cannot put any screenshot as it is an internal project

In our case, we use jupyterlab in Azure k8s environment controlled by jupyterhub.

we have azure fileshare mount to our jupyterlab pod, with volume mount **denoted as /document,** which stored our workspace settings and lab configurations, when startup, we would create another symbolic link from local container storage to /document, in order to copy our sample notebooks

**(we just do things like ln -s /tmp /document)**

what surprises us is that if we click the symbolink /document/tmp from mounted location /document, it would takes more than 2 seconds to open the /document/tmp even if /tmp is in local container storage, that is, we access local storage even much slower than the location in volume mount.

## Reproduce

I am sorry that maybe only guys using Azure and k8s can 100% follow these step, I can just talk about what I met here

1. startup jupyterlab via jupyterhub in k8s
2. mount an azure fileshare volume to jupyterlab (I guess AWS S3 may work similarly? )
3. create a symbolic link with lots of files to the path mounted in step 2
4. click into the symbolic link

## Expected behavior

it would much slower than access the file itself, or access file in fileshare/s3, it takes 2 or 3 seconds maybe, depend on how many content in the directory routed by symbolic link

## Context

- Operating System and version: Ubuntu 22 in docker image, RHEL 7 in k8s node server (I am not 100% sure)
- Browser and version: Chrome 106
- JupyterLab version: 3.2.6

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by jweill-aws** [comment]
This may be related to the Jupyter Server attempting to retrieve metadata on all files in your Azure file share's directory. (Disclosure: I work for AWS, a competitor to Azure.) This might also be improved by https://github.com/jupyter-server/jupyter_server/issues/962 , support for file pagination, to reduce file system access (including remote file systems).

CC @kevin-bates @Zsailer @fcollonval @ellisonbg

**Comment by linlol** [comment]
> This may be related to the Jupyter Server attempting to retrieve metadata on all files in your Azure file share's directory. (Disclosure: I work for AWS, a competitor to Azure.) This might also be improved by [jupyter-server/jupyter_server#962](https://github.com/jupyter-server/jupyter_server/issues/962) , support for file pagination, to reduce file system access (including remote file systems).
> 
> CC @kevin-bates @Zsailer @fcollonval @ellisonbg

Thanks a lot! 

I took a further look on our case and let me make a better description here.

suppose that we have a mounted directory /mount, and a symbolink /mount/code from container storage /code

in this case, I found that when clicking /mount/code at directory, it invokes API /content/mount/code?content=1&{timestamp}, which takes more than 5 seconds in devtools, while actually it takes just 200 ms for endpoint /content/code when just click /code from local root dir / (actually it shall only take sub 100 in backend jupyter server, as our authentication rules takes large overhead)

in this case, consider that for endpoints like /code it just take a few moment, and actually jupyter_server can determine if the link is a symbolic link, is there any approach like a configuration or like a customised ContentManager with get method overriden to treat the mixed link /document/code same as /code

**Comment by linlol** [comment]
Here is a quick update,

Looks like it is extraordinarily slow for lstat command

1. Suppose we have two filesystem (in my case, one is aks's native filesystem, the other is the mounted azure fileshare

2. Create a symbolic link in fileshare, which is pointed to local disk.

It is irrelevant with jupyter_server
