### ISSUE TITLE
Scrollbar jumps back in a virtualized notebook on scrolling

### ISSUE THREAD

**Issue by suganya-sk** [jupyterlab/jupyterlab#13343]
## Description

In a virtualized notebook, on scrolling, the scrollbar jumps back and shrinks as more content is rendered. This is a bit jarring visually and the original scrollbar is not indicative of the actual size of the notebook.

## Reproduce

In a notebook running from Jupyterlab >= 4.0.0a29, 

1. Open a notebook with about a 100 cells - the scrollbar at this point does not reflect the actual size of the notebook (100 cells)
3. Start scrolling down to view cells below the original viewport
4. The scrollbar jumps back and changes in size as more DOM elements are added.

## Expected behavior

Scroll bar moves smoothly during scrolling

## Context

- Browser and version:  Chrome 106, Firefox 106
- JupyterLab version: 4.0.0a29

**Comment by fcollonval** [comment]
Some background on the root cause:

Virtual rendering requires the estimation of content not rendered. This is a very hard problem for notebook as we have no good way to estimate their sizes. The height estimator is very crude for now (some heuristic for rendered markdown cells and cell outputs would definitely be beneficial) as it only take into account the number of lines in the cell sources to get an estimation of the cell height.

> Any solution that would try to get the real content in the DOM to estimate the height of out of view cells will dramatically reduce the benefit of the windowing.

**Comment by suganya-sk** [comment]
Thanks for the quick reply here.

I agree guessing dimensions of content that has not been rendered is a difficult problem to solve and we wouldn't want to do something that foregoes all the benefit virtualization has brought in.

This isn't much of an improvement but can we consider adding the something like this to èstimateWidgetSize` - it already estimates size of a cell by accessing the number of input cells it has. Could we consider adding similar logic for output for code cells and attachments for markdown/raw cells?


```js
const thisCellModel = this.cells[index].model.sharedModel;
const cellType = thisCellModel.cell_type;
let outputHeight = 0;
if  (cell_type == "code") {
    // this would work for text output but is a vague estimate for other kinds
    // can be refined further by differentiating IExecuteResult, IDisplayData and IStream
    const outputLines = thiscellModel
                            .getOutputs()
                            .split('\n').length;
    outputHeight = (
        // we'll have to define DEFAULT_OUTPUT_LINE_HEIGHT
        NotebookViewModel.DEFAULT_OUTPUT_LINE_HEIGHT * outputLines +
        NotebookViewModel.DEFAULT_CELL_MARGIN
    );
} else if (["markdown", "raw"].includes(cell_type)) {
    // this is a pretty poor estimate since we do not know the size of each MIME bundle attached here
    const attachementsCount = thiscellModel
                                .getAttachments()
                                .length();
    outputHeight = (
       // we'll have to define DEFAULT_ATTACHMENT_HEIGHT
        NotebookViewModel.DEFAULT_ATTACHMENT_HEIGHT * attachementsCount +
        NotebookViewModel.DEFAULT_CELL_MARGIN
    );
}
// assuming the result from the current implementation is already stored in`inputHeight`
return inputHeight + outputHeight;
```
If we want to do this, for code cells, we can refine the output further by differentiating among IExecuteResult, IDisplayData and IStream (which has a `text` attribute, a multi-line string). I dont see a reliable way for estimating the height each attachment will take though.

Please let me know what you think.

**Comment by fcollonval** [comment]
Except for the code editor, as you said, it is really hard to get an idea of the element heights. Currently I think we would be even more robust by 
- either caching the sizes to be able to restore it between user sessions
- or better using a self trained size estimator for which will cached the parameters to restore it between user sessions.

I like a bit better the second one as it will allow some heuristic guess even for new contents and it will have a deterministic cache size. Would you be wiling to open a PR?

**Comment by suganya-sk** [comment]
I'm happy to open a PR here. I'm a bit pinched for time for the next couple of weeks and will be able to work on this after. Does that timeline sound okay?

**Comment by fcollonval** [comment]
Thanks for proposing your help @suganya-sk Don't worry about the timeline, contributions are always welcomed.

**Comment by jtpio** [comment]
Posting the comment from https://github.com/jupyterlab/jupyterlab/issues/14285 here.

---

This was also noticed with JupyterLab `4.0.0b0`:

- open `4.0.0b0` on Binder: https://gist.github.com/jtpio/4e9a3d435d7c3950dc4150c10abbb1d7
- create a long notebook
- grab the scrollbar and move the mouse down

https://user-images.githubusercontent.com/591645/228187180-a065c14e-7177-41b0-bba4-3af42d331da6.mp4

Also this might be more apparent when the notebook has many markdown cells and images.

## Expected behavior

It should be possible to drag the scrollbar all the way to the bottom without jitter.

For reference with 3.6.2 the scrollbar follows the mouse more accurately:

https://user-images.githubusercontent.com/591645/228187782-33fab1c0-d78b-4b8d-b2fd-23027f8f3f81.mp4

**Comment by jtpio** [comment]
And adding to the `4.0.0` milestone to have it on the radar.

This issue seems to be even more visible with Notebook 7 (which can be tested with https://gist.github.com/jtpio/d368ab89cee5123ecee60683115e15f3).

**Comment by fcollonval** [comment]
> Expected behavior
> It should be possible to drag the scrollbar all the way to the bottom without jitter.

Just want to clarify that this will never be possible when using virtual rendering for notebook. We can improve the height cell estimator but we cannot guarantee no jitter scroll experience.

**Comment by jtpio** [comment]
> We can improve the height cell estimator but we cannot guarantee no jitter scroll experience.

Anything that can be done to improve this would be great.

A common workflow is to open a notebook and go to the last cell by dragging the scrollbar all the way to the bottom. This is useful for example to check the results of an analysis which are usually at the end. In JupyterLab 4 trying to do this is more difficult and frustrating because of the UI shifts and scrollbar issues happening on the way.

**Comment by jtpio** [comment]
Or if there could be a way to make some of the heuristics used by the virtual rendering logic customizable via the settings.

**Comment by krassowski** [comment]
Well a simple solution is to replace `display: hidden` with:

```css
/* always on */
contain-intrinsic-size: auto 100px;
/* added when out-of view, using replacing current use of `display: hidden` */
content-visibility: hidden;
```

And remove all custom height guessing. This will also make cells faster to appear when scrolling back at a cost of higher memory usage.

The catch is is that `content-visibility: hidden` support is fresh with Firefox slowly rolling it out (already on by default in Firefox Nightly). The good news is that when a browser does not support it, the behaviour would still be as in JupyterLab 3 (so no performance gain from windowed notebook, but also no UI regressions).

I would say this is certainly worth exploring.

**Comment by krassowski** [comment]
Though this would not solve the issue for cells that were never seen. But it could solve https://github.com/jupyterlab/jupyterlab/issues/14379

**Comment by mlucool** [comment]
Based on reading the other thread, this request will be resolved between 4.0 and 4.1?

**Comment by afshin** [comment]
@suganya-sk I would like to take a look at this issue (or really the constellation of issues around virtual scrolling).

If you plan to work on this, still, I'll happily step aside, though. Cheers!

**Comment by GabrielaVives** [comment]
I have been working with @afshin on the UX of a virtual scrollbar that would allow users to
- identify how long the notebook is 
- scroll through without the scrollbar jumping
- be able to jump to the last cell or a particular cell in the notebook

I would like to run a couple of usability tests on the prototypes to identify any missing or needs or issues with the design. If you are interested please contact me and we can schedule a call for next week. It will take no longer than 15min and help a lot to move forward on this issue!

**Comment by afshin** [comment]
If you are interested in participating in a 15-minute user test / interview on this feature please write a comment below!

(I will link to this comment in the call agendas.)

**Comment by jasongrout** [comment]
I'm happy to help test this for 15 minutes.

**Comment by chbrandt** [comment]
I'm happy to help too.

**Comment by afshin** [comment]
cc: @jupyterlab/jupyterlab-council

**Comment by afshin** [comment]
@vidartf volunteers for this as well!

**Comment by krassowski** [comment]
@GabrielaVives just out of curiosity are the other prototypes that you considered available for public reference?

**Comment by GabrielaVives** [comment]
@krassowski yes of course. Below are the 3 mockups I showed participants: 

<img width="2047" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/105775162/c8fdd6f2-591a-434c-9d91-67aa1ecedd15">

Hovering or clicking on a UI element (not yet defined), displays 3 navigation items:

- a button allowing the user to jump to the top of the notebook
- a button allowing the user to jump to tht bottom of the notebook
- an input field giving information about how many cells are in the notebook, and which cell  is focused. The input field allows the user to navigate and focus on any cell in the notebook.

<img width="2048" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/105775162/404cbe80-edde-4e38-b52c-a926dab9a83d">

- A toggle button allows users to show/hide a virtual scrollbar.
- In the virtual scrollbar, cells are represented by squares that have two states: default or focused.
- The focused cell in the notebook is represented by a focused state in the virtual scrollbar.
- The user can navigate through the virtual scrollbar and changes the cell focus by clicking on the cell representations.
- On top of the virtual scrollbar, text displays information about how many cells are in the users’ view/total number of cells.

<img width="2048" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/105775162/785c5b1c-d6c5-4bb8-b867-7b1bf9d6c5c1">

- A toggle button allows users to show/hide a virtual scrollbar.
- In the virtual scrollbar, cells are represented by squares that have 4 states: default/focused and in view/out of view.
- The focused cell in the notebook is represented by a focused state in the virtual scrollbar.
- The visible cells in the notebook are represented by an highlighted state in the scrollbar.
- The user can navigate through the virtual scrollbar and changes the cell focus by clicking on the cell representations.
- On top of the virtual scrollbar, text displays information about how many cells are in the users’ view/total number of cells.

Interviews and usability tests brought up many pros and cons for each of these versions. I'm now working on trying to summarise the findings in a new version.
For the moment it looks like this :

<img width="2049" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/105775162/8d8eb375-e841-49df-97f8-e3b9937214cc">

This is an evolving prototype, and all feedback is welcome and highly appreciated.

**Comment by krassowski** [comment]
Regarding the height heuristics, two thoughts:
1. when first loading a notebook we could render the cells and their outputs **for all cells in the background, on idle, in small batches** to measure the height; the cells which are out of view would immediately be discarded which means that there would be only a constant memory/CPU load penalty; this would essentially be a combination of `defer` and `full` mode so it should not increase the maintenance burden too much
2. we could cache the cell heights in the layout database (following earlier proposal by @fcollonval); this should be doable given we have unique cell IDs per notebook; cache invalidation could be based on maximum number of notebooks for which the cell height is stored.

**Comment by mlucool** [comment]
> we could cache the cell heights in the layout database

This is hard as the user may resize the window or share it with someone who has a different screen size.
