### ISSUE TITLE
Disabling @jupyterlab/notebook-extension does not disable @jupyterlab/notebook-extensions:copy-output in 3.4.x

### ISSUE THREAD

**Issue by teleginzhenya** [jupyterlab/jupyterlab#13345]
https://github.com/jupyterlab/jupyterlab/blob/ad66d84e61369debfa4894ceb8f7ad76e2a68b9d/packages/notebook-extension/src/index.ts#L672

I've disabled `@jupyterlab/notebook-extension` in order to replace everything with my fork of `notebook-extension` package (since I couldn't find way to customize it, lol)

Steps to reproduce
1. `jupyter labextension disable @jupyterlab/notebook-extension`
2. `jupyter labextension list`
```
Disabled extensions:
    @jupyterlab/notebook-extension (all plugins)
```
3. Opening JupyterLab causes `Command 'notebook:copy-to-clipboard' already registered.`
```
Error: Command 'notebook:copy-to-clipboard' already registered.
    at CommandRegistry.addCommand (VM190 jlab_core.91068d0bcdd7ffb0fdc2.js:109276:19)
    at activateCopyOutput (VM228 vendors-node_modules_ml-platform_lib_main_ts_index_js.8c123c1195c1dcc068e0.js:1064:18)
    at VM190 jlab_core.91068d0bcdd7ffb0fdc2.js:106734:34
    at async Promise.all (index 126)
```
4. This is comes from `@jupyterlab/notebook-extensions:copy-output`. And using devtools I've found that `@jupyterlab/notebook-extensions:copy-output` still not disabled and I guess it is because of typo in extension name, there is plural form in the name. @jupyterlab/notebook-extension`s`:copy-output. (I've highlighted S). And I guess `jupyter labextension disable @jupyterlab/notebook-extension` disable everything with this prefix, however it is not working with the plural extension name with `s` on the end
-----------
I can make pull request which fix it

**Comment by fcollonval** [comment]
Thanks @teleginzhenya 

This is really unfortunate. But as we consider plugin id as part of the API, we have a policy not to change them except when doing a new major release (you can actually see that it is corrected on [master](https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook-extension/src/index.ts#L710) that is targeting v4).

Could you try running `jupyter labextension disable @jupyterlab/notebook-extensions` to see if it is disabling the plugin of interest?

**Comment by fcollonval** [comment]
> A possible workaround could be to allow for setting a matching expression instead of a specific name - but that may have some side effects (especially if we allow `*` pattern).

**Comment by teleginzhenya** [comment]
@fcollonval makes sense about breaking changes. I've disabled this extension directly and it worked. However, issue might be usefull for anyone who could face same issue.

**Comment by andrii-i** [comment]
Since immediate problem is resolved, we're setting the status to "Answered". However, in the future versions of lab we should revisit semantic association of commands provided by extensions with extensions themselves as they might clash.
