### ISSUE TITLE
Page load performance degradation on  jupyter/datascience-notebook:lab-3.5.0

### ISSUE THREAD

**Issue by dnoliver** [jupyterlab/jupyterlab#13363]
## Description

Got a problem while trying to access a Jupyter Lab webpage using an slow internet connection.
I was able to reproduce the issue by simulating an slow network connection with Chrome CDT (Disable Cache + Slow 3G)
Started a jupyter-lab container, using the latest available version in Docker Hub:

```bash
$ docker run -p 9999:8888  \
    -e JUPYTER_ENABLE_LAB=yes \
    -e JUPYTER_TOKEN=docker  \
    --name jupyter-latest  \
    -d jupyter/datascience-notebook:lab-3.5.0
```

And then used a clean Chrome Version 107.0.5304.63 (64-bit) to try to load Lab (Disable Cache + Slow 3G)
I consistently get this exception in CDT, an Jupyter Lab never loads:

```js
main.bf515ddb81bbc946ace6.js?v=bf515ddb81bbc946ace6:1 Uncaught (in promise) ChunkLoadError: Loading chunk 3472 failed.
(timeout: http://127.0.0.1:9999/static/lab/jlab_core.e37d4bbc8c984154bc26.js?v=e37d4bbc8c984154bc26)
    at a.f.j (main.bf515ddb81bbc946ace6.js?v=bf515ddb81bbc946ace6:1:68352)
    at main.bf515ddb81bbc946ace6.js?v=bf515ddb81bbc946ace6:1:12004
    at Array.reduce (<anonymous>)
    at a.e (main.bf515ddb81bbc946ace6.js?v=bf515ddb81bbc946ace6:1:11982)
    at e (main.bf515ddb81bbc946ace6.js?v=bf515ddb81bbc946ace6:1:979)
```

Then, after enabling the cache, I can get the missing chunk loaded correctly, and Jupyter Lab starts.

Now, with Enable Cache + Slow 3G, I can get a Lighthouse report, and this is the score and the recommendations I and getting (enable text compression is the primary recommendation)

![image](https://user-images.githubusercontent.com/7730267/199362055-6c120b54-6c04-4fcb-8d54-a091c42a771a.png)

Doing the same experiment with a jupyter/datascience-notebook:lab-3.2.8 container yields better results (and it can load with Disable Cache and Slow 3G).

![image](https://user-images.githubusercontent.com/7730267/199362531-741fd8fa-1061-4974-8e32-2ff44ca9a4b3.png)

So looks like there was a degradation introduced in newer versions. At least the jcore bundle got significantly bigger too make the chunk load issue consistent.

Anyways:

Any mitigation to the ChunkLoadError on slow networks? other than pressing F5 multiple times until you get all the chunks?
Looks like performance as analyzed by Lighthouse is poor. Any ways to enable text compression, and see if it helps? 

## Reproduce

1. Start a container with the latest version of jupyter lab (jupyter/datascience-notebook:lab-3.5.0)
2. Open a clean Chrome browser session (I am using selenium webdriver here to assure it is clean)
3. Set in Network Tab: Disable Cache and Slow 3G network throttling 
4. Try loading jupyter lab, will fail will a load chunk failed error
5. Enable the cache and run a Lighthouse performance report, you should get something like 20

## Expected behavior

Lab should load Disable Cache and Slow 3G?
Performance metric should be higher?

## Context

- Operating System and version: Windows 11
- Browser and version:  Chrome Version 107.0.5304.63 (64-bit)
- JupyterLab version: 3.5.0

**Comment by andrii-i** [comment]
Thank you for filing this issue! We found few issues that cover these performance problems and are already tracked there: issue #13189 , issue #4634. 

https://github.com/jupyterlab/jupyterlab/issues/4634#issuecomment-803147946 
This comment includes a workaround. Feel free to take a look and try it out.

**Comment by dnoliver** [comment]
Thanks @andrii-i  for that pointer!

I did a quick tests, using jupyter/datascience-notebook:lab-3.2.8 images.

```bash
# Compression enabled
docker run -p 8888:8888 -e JUPYTER_ENABLE_LAB=yes -e JUPYTER_TOKEN=docker --name jupyter-compress jupyter/datascience-notebook:lab-3.2.8 start-notebook.sh --LabApp.tornado_settings="{'compress_response'
: True}"

# Compression disabled
docker run -p 9999:8888 -e JUPYTER_ENABLE_LAB=yes -e JUPYTER_TOKEN=docker --name jupyter-plain jupyter/datascience-notebook:lab-3.2.8 start-notebook.sh
```

Left one is with compression enabled, right one is without it.

![image](https://user-images.githubusercontent.com/7730267/199826337-31e4b5dd-05ea-4cca-b1a2-f14e8435419d.png)

The score is 3x better. Not bad. But the most important thing for me was the size of the files we have to send over the wire. 

Compressed: 1.7 MB transferred
Plain: 6.3 MB transferred

That's a 4x improvement. 

Thank you!

**Comment by andrii-i** [comment]
@dnoliver That's great! Happy we were able to help.
