### ISSUE TITLE
Code folding is broken

### ISSUE THREAD

**Issue by schmidi314** [jupyterlab/jupyterlab#13362]
## Description

Code folding does not work any more.

## Reproduce

![Peek 2022-10-15 15-42](https://user-images.githubusercontent.com/74381262/199213274-edf9f3af-3386-4c8e-a8d4-7c282fcc28a7.gif)

1. Activate code folding [Notebook->Code Cell Configuration->Code Folding]
2. Try to collapse a function.

## Expected behavior

A triangle should appear that, when clicked, collapses the function bodies.

BTW, in jupyter notebook one could collapse a whole code cell to its first line when starting with a #-comment. That never worked in jupyterlab and I'm still kind of missing it.

## Context

- Operating System and version: Ubuntu Linux 20.04.5
- Browser and version: Firefox 105.0
- JupyterLab version: 4.0.0a30

**Comment by andrii-i** [comment]
This is mentioned as a task in issue #12812

**Comment by jtpio** [comment]
Many thanks @schmidi314 for trying out the 4.0 pre-release and reporting this issue :+1:
