### ISSUE TITLE
Syntax Highlighting for `match-case` statements (Python 3.10 - Structural Pattern Matching - PEP634, PEP635, PEP636)

### ISSUE THREAD

**Issue by randolf-scholz** [jupyterlab/jupyterlab#13379]
Consider this example:

```python
x = 1
match x:
    case _:
        raise
```
Executing this in Jupyter yields a funny result: the original code is not highlighted correctly, but the trace back is!

![image](https://user-images.githubusercontent.com/39696536/199975526-3f3cd821-e8f9-4360-bbc1-a95488c1e884.png)

**Comment by randolf-scholz** [comment]
It seems a fix for this was merged in codemirror a few days ago: https://github.com/lezer-parser/python/pull/11

**Comment by fcollonval** [comment]
Thanks for reporting @randolf-scholz 

Small note: the fix in codemirror will only impact CodeMirror 6 (used in JupyterLab 4+). That does not fix JupyterLab <4 - and it will be unlikely to be fixed upstreamed for CodeMirror 5; for reference on CodeMirror 5, the Python keywords are defined [there](https://github.com/codemirror/codemirror5/blob/9296326b0a9e37489e00d4d7bfabd4725f6bfb7b/mode/python/python.js#L19)

**Comment by krassowski** [comment]
This now works in JupyterLab 4.0 - closing as resolved:

![Screenshot from 2023-05-24 20-11-04](https://github.com/jupyterlab/jupyterlab/assets/5832902/fdc119c7-a340-4e73-8270-fb8bb5c3ef68)
