### ISSUE TITLE
Interactive mode like wolframalpha

### ISSUE THREAD

**Issue by lampts** [jupyterlab/jupyterlab#1340]
I would love to have some things similar in jupyterlab as wolframalpha did very well in their app notebook.

Please have a look here: https://develop.open.wolframcloud.com/app/

**Comment by blink1073** [comment]
Hi @lampts, thank you for your interest in JupyterLab.  What specific features are you looking for?

**Comment by jasongrout** [comment]
Closing because of no followup. @lampts - feel free to post a comment here if you'd like to elaborate. Thanks!
