### ISSUE TITLE
Launching JupyterLab without "sudo"

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#1343]
It seems JupyterLab has to be launched using `sudo jupyter lab`  in order for it to work. I somehow managed to make JupyterLab work without requiring launching with `sudo` on one of my servers but I forgot what I did to make it happen. Now after installing JupyterLab on a new server, I have to launch using `sudo jupyter lab` again. Does anyone know which package/plugin I have to install so that I can launch JupyterLab without `sudo`?

**Comment by blink1073** [comment]
Hi @dclong, can you give the output of `jupyter serverextension list`, `jupyter lab` and `sudo jupyter lab`?

**Comment by dclong** [comment]
```
$ jupyter serverextension list
config dir: /usr/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab  OK
```
```
$ jupyter lab
[I 23:29:53.512 LabApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[W 23:29:53.681 LabApp] Widgets are unavailable. Please install widgetsnbextension or ipywidgets 4.0
[I 23:29:53.741 LabApp] JupyterLab alpha preview extension loaded from /usr/local/lib/python3.5/dist-packages/jupyterlab
[I 23:29:53.753 LabApp] Serving notebooks from local directory: /home/dclong/archives/jupyter
[I 23:29:53.753 LabApp] 0 active kernels 
[I 23:29:53.753 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 23:29:53.754 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 23:29:54.302 LabApp] 302 GET /lab (127.0.0.1) 1.30ms
```
```
$ sudo jupyter lab
[sudo] password for dclong: 
[W 23:30:54.815 LabApp] Widgets are unavailable. Please install widgetsnbextension or ipywidgets 4.0
[I 23:30:54.840 LabApp] JupyterLab alpha preview extension loaded from /usr/local/lib/python3.5/dist-packages/jupyterlab
[I 23:30:54.850 LabApp] Serving notebooks from local directory: /home/dclong/archives/jupyter
[I 23:30:54.850 LabApp] 0 active kernels 
[I 23:30:54.850 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 23:30:54.850 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by blink1073** [comment]
Ah, the server extension is enabled at the system level.  Can you please try `jupyter serverextension enable --py jupyterlab --user` to install to your home directory?

**Comment by dclong** [comment]
@blink1073 
It turned out to be that the directory `~/.local/share/python` and its subcontents belong to `root` rather than my account. Changing the owner of the directory and its subcontents to my account solves the problem. Not sure whether this was due to using `sudo` without the `-H` option.

**Comment by blink1073** [comment]
`sudo` is a tricky beast, a reason why we don't recommend using the system Python.

**Comment by ellisonbg** [comment]
Closing for now, please feel free to re-open if needed.
