### ISSUE TITLE
User name changes in collaborative mode with no authentication

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#13432]
## Description

In JupyterLab `master` branch, with collaborative mode enabled, the name of the anonymous user periodically changes.

## Reproduce

1. Install JupyterLab's `master` branch.
2. Launch JupyterLab with `jupyter lab --dev-mode --collaborative`.
3. Wait a couple of minutes.
4. See the name of the user change in the upper-right corner of the UI.

## Expected behavior

The user name should not change.

**Comment by fcollonval** [comment]
@davidbrochart do you think it is linked to the websocket for the global awareness to be reopened?

**Comment by davidbrochart** [comment]
I don't think so, because it still happens after https://github.com/y-crdt/ypy-websocket/pull/42.

**Comment by davidbrochart** [comment]
Also, it happens even when no document is opened.

**Comment by davidbrochart** [comment]
> @davidbrochart do you think it is linked to the websocket for the global awareness to be reopened?

I think I didn't get your question, it could be linked to the global awareness yes.

**Comment by davidbrochart** [comment]
Actually, it is the backend which sends the new name on `/api/me`.

**Comment by davidbrochart** [comment]
It only happens when launching `jupyter lab --ServerApp.token='' --ServerApp.password=''`, and seems to be because of https://github.com/jupyter-server/jupyter_server/issues/1033.

**Comment by hbcarlos** [comment]
@davidbrochart, https://github.com/jupyter-server/jupyter_server/pull/1076 was merged and released in jp-server v2.0.0rc5.
I guess this issue is now fixed? I can not reproduce it.

**Comment by hbcarlos** [comment]
Closing as fixed by https://github.com/jupyter-server/jupyter_server/pull/1076.
I can see the backend always sending the same user identity, even when not using authentication.

**Comment by davidbrochart** [comment]
Yes, it is [fixed](https://github.com/jupyter-server/jupyter_server/pull/1076#pullrequestreview-1186423251).
