### ISSUE TITLE
Start a GUI App/Tool in notebook/terminal of Jupyter lab from client/local machine

### ISSUE THREAD

**Issue by SyrakuShaikh** [jupyterlab/jupyterlab#13451]
*First of all, I'm new to jupyter and not sure if this is a feature request or a naive question, sorry for this.*

## Problem

Our team works on a project that needs to provide GUI for beamline researchers and we choose jupyter lab/notebook.
A docker image with jupyter and all other dependencies packed is deployed by K8s. This is the server side.
Researchers connect the server from web browsers on their local machines.

**Now** we have a request that a GUI app/tool should be started from the terminal in jupyter lab or from voila rendered notebook. For instance, such a GUI app/tool is like *pyFAI-integrate* ([link](http://www.silx.org/doc/pyFAI/dev/man/pyFAI-integrate.html)). However, when we either start it from the terminal at the bottom of the launcher or inside the notebook, the *pyFAI-integrate* GUI appears on the server side, **not** on the local/client side:(

Besides, we also want to start our Qt-based GUI tool from jupyter lab (also the server-client mode). It does not work, either. We think this is the same problem as above.

We tried `ssh -XY -L local:8888:server:8889`, but it does not work.

## Proposed Solution

...

## Additional context

Any comments, suggestions, or clues are highly welcome!

**Comment by SyrakuShaikh** [comment]
Hi there, any clue, comment, or suggestion? Thanks！

**Comment by afshin** [comment]
Hi! Because JupyterLab and Jupyter Notebook are web-based applications, we don't have an API that will allow us to do X-forwarding from the terminal emulator within Jupyter. Unfortunately, you'll need to use a more traditional SSH client that has access to system-level APIs to support X-forwarding.

It is a reasonable question and request, but at this time, I don't believe the APIs exist to implement this feature in a web-based application like JupyterLab. Sorry about that!

**Comment by krassowski** [comment]
In general clients running in a browser cannot open applications on the local side. The only ways I can imagine doing so would be to:
- extend [JupyterLab Desktop](https://github.com/jupyterlab/jupyterlab-desktop) which can access both local resources (start local applications) and remote servers
   - this is unlikely to be in scope of JupyterLab Desktop itself but maybe there could be a way to extend it
- create a browser extension that starts the application locally on some condition that you would emit from within JupyterLab (again, as far as I know browsers do not have privilege)

**Comment by krassowski** [comment]
Another idea: you can use [custom protocols](https://stackoverflow.com/a/39059878/6646912) as in `my-app://`. To allow these in markdown and outputs you need to  allowing the custom protocols in sanitizer settings (an option to do so was recently added in https://github.com/jupyterlab/jupyterlab/pull/13341).

**Comment by SyrakuShaikh** [comment]
Thank @afshin for your explanation of the API mechanism behind Jupyter.
Thank  @krassowski for your valuable suggestions. I will try to look into the "custom protocols" method.
