### ISSUE TITLE
shift-left clicking event is blocked when no text is selected

### ISSUE THREAD

**Issue by Thenorthernsea** [jupyterlab/jupyterlab#13452]
https://github.com/jupyterlab/jupyterlab/blob/26999c5df85dd8a088580b5dafbc5404ef9b4a44/packages/notebook/src/widget.ts#L2140
This caused select multiple widget in ipywidgets to not functioning as expected when try to use shift + click to select in range.

related issue: https://github.com/jupyter-widgets/ipywidgets/issues/3615

**Comment by jmk89** [comment]
In particular, `window.getSelection()` doesn't detect when the list item in the SelectMultiple widget is selected, or has been selected. The call to `window.getSelection()` detects when something else has been **highlighted.** It will also detect a selection if some text **within** the SelectMultiple widget has been highlighted. 

https://github.com/jupyterlab/jupyterlab/blob/6bfef5d478969a6ac59a0ed65405a2df6cdf9109/packages/notebook/src/widget.ts#L2229-L2237

In this case, it seems more useful to consider `window.getSelection()` as something more like `window.getHighlighted()` :stuck_out_tongue_closed_eyes:

**Comment by fcollonval** [comment]
We could probably avoid processing the event if the target node is `select` or `input`?

What do you think @jasongrout ?
@jmk89 or @Thenorthernsea thanks for digging up the code line. Would you be willing to open a PR fixing this?

**Comment by jmk89** [comment]
@fcollonval sure I can get something put together pretty quick. 

How are people testing ipywidgets against the current master branch? Is there a suggestion on how to get a compatible build of ipywidgets to work with the 4.0.0alpha16 dependencies going on?

**Comment by fcollonval** [comment]
Thanks @jmk89 

You can follow the [development installation](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#installing-jupyterlab). Then in your environment, you can install `ipywidgets`. And finally you will need to start JupyterLab with an additional flag:

```
jupyter lab --dev-mode --watch --extensions-in-dev-mode
```

With that you should be able to modify JupyterLab code with ipywidgets installed.

![image](https://user-images.githubusercontent.com/8435071/207261200-78c5042f-33f5-4f2e-8b18-0c7569259a6f.png)

**Comment by jmk89** [comment]
Ah thank you! I've been following the dev install documentation from the [stable](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#installing-jupyterlab) release rather than the latest, which you linked. I think this line `pip install -e ".[dev,test]"` is what made the difference.
