### ISSUE TITLE
Tab completion not working with JupyterLab 3.4.7, even with jedi==0.17.2

### ISSUE THREAD

**Issue by sorenwacker** [jupyterlab/jupyterlab#13459]
This might be reported already, but I did not find an issue with above mentioned version. Usually, installing jedi 0.17.2 fixed the issue in the past, but now this does not seem to work anymore. Which jedi version is recommended nowadays?

**Comment by jweill-aws** [comment]
The newest version in the 3.4.x series is 3.4.8. There are also newer minor versions of JupyterLab 3 (3.6.x being the newest branch). If possible, can you please try updating your JupyterLab version and see if this recurs?

**Comment by afshin** [comment]
I tried this on 3.4.7 and indeed found completion to be broken. But as @jweill-aws suggests, the bug appears to be fixed in 3.4.8. Thanks for the report! I hope this version fixes your problem.
