### ISSUE TITLE
pywin32

### ISSUE THREAD

**Issue by rollmark** [jupyterlab/jupyterlab#13455]
Could not find a version that satisfies the requirement pywin32>=1.0; sys_platform == "win32" and platform_python_implementation != "PyPy" (from jupyter-core->jupyterlab) (from versions: )
No matching distribution found for pywin32>=1.0; sys_platform == "win32" and platform_python_implementation != "PyPy" (from jupyter-core->jupyterlab)

python3:
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by vidartf** [comment]
Thanks for your report! This is a dependency of `jupyter-core`, as your report indicates, so it would have been better opened there. That said, are you using public PyPI? https://pypi.org/project/pywin32/#history seems to have many matching versions, and that dependency declaration has worked on Windows for many years. There might be an issue with your version/config of pip? At least, it does not seem to be an issue with JupyterLab.
