### ISSUE TITLE
Flaky `js-services` check on CI

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13460]
## Description

The `js-services` check on CI has been flaky for quite a while now.

## Reproduce

Here is an example run on the latest commit (79013299873236a01590feaf1dde6bc6ba5fdc0f) on `master`: https://github.com/jupyterlab/jupyterlab/actions/runs/3516180912/jobs/5892407924

![image](https://user-images.githubusercontent.com/591645/203151099-db10b463-acb3-4a5c-95d1-337e19d3fa48.png)

## Expected behavior

This check should fail less often so we are back to PRs with all-green checks :heavy_check_mark:

**Comment by fcollonval** [comment]
I'm working to bump Jest to v29 in https://github.com/jupyterlab/jupyterlab/pull/12584

We will then be able to take advantage of the github action reporter to ease failure analysis as the log for those tests is too long to be handled in GitHub and the ansi color makes the raw format though to work with.

**Comment by jtpio** [comment]
So `js-services` is now passing on the latest `master`: https://github.com/jupyterlab/jupyterlab/actions/runs/3738704614/jobs/6345071954

Closing as fixed by https://github.com/ipython/ipykernel/pull/1056.
