### ISSUE TITLE
[4.0.0a31 / 3.6.0a4] Icons are not properly rendered with custom themes

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13461]
## Description

There seems to be either a regression or a breaking changes related to the theming of icons in JupyterLab 4.0.

**JupyterLab 4.0.0a31**

![image](https://user-images.githubusercontent.com/591645/203165970-ba700da6-12ea-49b9-82bf-9e37922487ea.png)

**JupyterLab 3.5.0**

![image](https://user-images.githubusercontent.com/591645/203166209-1d7a734d-df78-428d-b7ee-486dd4332bec.png)

## Reproduce

Try with both versions as mentioned above.

## Expected behavior

Icons should still be themed properly in 4.0.

## Context

Initially reported in https://github.com/jupyter/notebook/issues/6633, but this appears to be a JupyterLab issue.

**Comment by jtpio** [comment]
Tried to find something related in the extension migration guide but there doesn't seem to be anything: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#jupyterlab-3-x-to-4-x

**Comment by jtpio** [comment]
This also looks fine on `4.0.0a30`:

![image](https://user-images.githubusercontent.com/591645/203168458-e2bbacc6-63d3-4794-ae45-22d6f0b00c6b.png)


So this is likely something that broke with `4.0.0a31`, not sure if it was intentional or not.

**Comment by jtpio** [comment]
Adding to the `3.6.0` milestone since this is also an issue there:

![image](https://user-images.githubusercontent.com/591645/203250498-4e645b6f-681c-4993-a7dd-ccbe994f694d.png)

**Comment by fcollonval** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/13468
