### ISSUE TITLE
[3.6.0a4] Can't create a notebook with RTC enabled

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13463]
## Description

With `3.6.0a4` on Binder it's not  possible to create a new notebook from the launcher:

https://user-images.githubusercontent.com/591645/203251342-4f744a8d-e506-45a0-bb43-17d2dce533ea.mp4

## Reproduce

Using this gist on Binder which has RTC enabled: https://gist.github.com/jtpio/d063489b0843547ceeaaf5ee9832e69d

## Expected behavior

It should be possible to create new notebooks.

## Context

cc @davidbrochart @hbcarlos

**Comment by davidbrochart** [comment]
Thanks for reporting @jtpio.
It looks like `PUT /api/yjs/roomid/{path}` returns a `404`. I will look into it.

**Comment by davidbrochart** [comment]
I opened https://github.com/jupyter-server/jupyter_server_ydoc/pull/61.

**Comment by jtpio** [comment]
Nice thanks @davidbrochart!

**Comment by davidbrochart** [comment]
https://github.com/jupyter-server/jupyter_server_ydoc/pull/61 was merged and released in `jupyter-server-ydoc` v0.5.0.

**Comment by davidbrochart** [comment]
JupyterLab does a `GET` request to the created notebook before the `PUT /api/yjs/roomid/{path}`, so this is not the issue.

**Comment by davidbrochart** [comment]
So the reply to `PUT /api/yjs/roomid/{path}` is an HTML document with:
```
Jupyter Notebook requires JavaScript.
Please enable it to proceed.
```
@jtpio maybe a clue to what's going on?

**Comment by jtpio** [comment]
> I yanked `jupyter-server-ydoc` v0.5.0 in PyPI

Should the GitHub Release be deleted then? https://github.com/jupyter-server/jupyter_server_ydoc/releases/tag/v0.5.0

**Comment by davidbrochart** [comment]
> Should the GitHub Release be deleted then? https://github.com/jupyter-server/jupyter_server_ydoc/releases/tag/v0.5.0

Thanks, done.

> Is this on Binder? Could it be that it is hitting the classic notebook server and not the proxied JupyterLab Server (backed by a Jupyter Server)?

Yes, on Binder only. It works locally even when I change the server `base_url`.
Yes it could be hitting the classic notebook server, as in the previous release `jupyter-server-ydoc` was previously handling the base URL manually and was compatible with the classic notebook server.

**Comment by fcollonval** [comment]
Closing as to solve the trouble JupyterLab must be executed with jupyter server 2

**Comment by jtpio** [comment]
Then it would be nice to document it somewhere. Or at least here in this issue.

Re-opening to keep to track of this.
