### ISSUE TITLE
"404 : Not Found" when launching jupyter lab

### ISSUE THREAD

**Issue by Jessime** [jupyterlab/jupyterlab#1346]
I just downloaded jupyter lab for the first time today, so I might be just messing up something simple. But I installed (on Ubuntu 16.04) and ran by doing:

```
$ conda create --name j_lab python=3.5 anaconda
$ source activate j_lab
$ conda install -c conda-forge jupyter_nbextensions_configurator
$ conda install -c conda-forge jupyterlab
$ jupyter lab
```

The console output of `jupyter lab` is:

```
[I 11:08:00.825 LabApp] [nb_conda_kernels] enabled, 5 kernels found
[I 11:08:01.115 LabApp] Loaded extension jupyter_nbextensions_configurator
[I 11:08:01.118 LabApp] Serving notebooks from local directory: /home/jessime
[I 11:08:01.118 LabApp] 0 active kernels 
[I 11:08:01.118 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 11:08:01.118 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
[W 11:08:01.582 LabApp] 404 GET /lab (127.0.0.1) 42.38ms referer=None
```

This opens a new browser tab that just shows:

![image](https://cloud.githubusercontent.com/assets/8493770/20801657/9e82c6ac-b7b7-11e6-9afe-9b62531dea3e.png)

I repeated the process for Python 2.7, with the same result.

The discussion from issue #1103 made me check if I had `npm` installed, which I didn't, so I ran:

    $ sudo apt install npm

which worked without issue. I tried going through the `jupyter lab` install process one more time afterwards (using the first process I described above), but I'm still getting the same 404 message and console output. 

Any thoughts on what might be going wrong?

**Comment by blink1073** [comment]
Hi @Jessime, it looks like there was a problem with the serverextension install part, which usually happens automatically when installing from conda-forge.   What is the output of `jupyter serverextension list`?

**Comment by Jessime** [comment]
`jupyter serverextension list` appears to be normal. The full output is:

```
config dir: /home/jessime/.jupyter
    jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator  OK
config dir: /home/jessime/anaconda2/envs/j_lab3/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab  OK
    nb_conda  enabled 
    - Validating...
      nb_conda  OK
    jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator  OK
    nbpresent  enabled 
    - Validating...
      nbpresent  OK
    nb_anacondacloud  enabled 
    - Validating...
      nb_anacondacloud  OK
```

**Comment by blink1073** [comment]
And `which python` points to that `j_lab3` instance?

**Comment by Jessime** [comment]
Yep:

`/home/jessime/anaconda2/envs/j_lab3/bin/python`

**Comment by blink1073** [comment]
I'm a bit stumped.  I ran through the same commands just now on Ubuntu and I'm not getting a 404.
What does `cat /home/jessime/anaconda2/envs/j_lab3/etc/jupyter/jupyter_notebook_config.json` show?

**Comment by Jessime** [comment]
I don't have any suspicions of what it might be. Both the anaconda and Ubuntu installs are relatively fresh.

The config shows:

```
{
  "NotebookApp": {
    "kernel_spec_manager_class": "nb_conda_kernels.CondaKernelSpecManager",
    "nbserver_extensions": {
      "nb_conda": true,
      "nb_anacondacloud": true,
      "nbpresent": true,
      "jupyter_nbextensions_configurator": true,
      "jupyterlab": true
    }
  }
}
```

**Comment by blink1073** [comment]
For grins, can you please try enabling at the user level?  `jupyter serverextension enable --py jupyterlab --user`?

**Comment by Jessime** [comment]
Hey! That worked. Thank you!

Just out of curiousity, would you mind explaining what happened? I don't understand why that fixed the issue.

**Comment by blink1073** [comment]
I think this is related to https://github.com/jupyter/notebook/issues/1706, my guess is that the fact that it wasn't enabled at the user level disabled it at the sys-prefix level, which is counter-intuitive, obviously ;).

**Comment by blink1073** [comment]
I'm going to close this one, feel free to reopen if you disagree.  Happy coding!

**Comment by Jessime** [comment]
I don't know enough to disagree, but thanks again!
