### ISSUE TITLE
Introduce disabled states for the cell move up/move down icons in the toolbar

### ISSUE THREAD

**Issue by GabrielaVives** [jupyterlab/jupyterlab#13502]
### Problem

The icons on the cell toolbar to move a cell up or down currently have the following states:
- enabled
- hover

However, the following cases should be visually different to users:
- when a cell is at the top of the notebook, the "move upwards" icon should be disabled.
- when a cell is at the bottom of the notebook, the "move downwards" should be disabled.

Although it can seem obvious that these actions are not permitted in such cases, it is important to provide visual cues to users to avoid the frustration of trying to click on a button that seems enabled, only to notice by error/trial that it doesn't work.

### Proposed Solution
I suggest to add a 3rd state: the disabled state for the icons "move cell below" and "move cell above", as illustrated below:

![Add disabled state to icons](https://user-images.githubusercontent.com/105775162/204345093-04334c7c-7fd5-45d8-b715-75bb4f619497.png)

### Additional context
This issue is a result from a usability study conducted in October and November 2022 on beginner users of JupyterLab, aiming to test a collaborative workflow. Feel free to ask me for the full report.

**Comment by HaudinFlorence** [comment]
I am having a look at this issue.

**Comment by HaudinFlorence** [comment]
PR #13898 proposes a fix for this issue.
