### ISSUE TITLE
Launcher icons text hits margins on Safari

### ISSUE THREAD

**Issue by birdsarah** [jupyterlab/jupyterlab#1353]
Very small styling tweak for launcher styling.

On Safari (but not Chrome and Firefox) launcher icons look like this:

<img width="319" alt="screen shot 2016-12-01 at 5 21 28 pm" src="https://cloud.githubusercontent.com/assets/1796208/20817026/f4e8bc26-b7ea-11e6-815a-75a9b01bfab5.png">

But I would guess this screengrab from Firefox is what's intended:

![screen shot 2016-12-01 at 5 25 10 pm](https://cloud.githubusercontent.com/assets/1796208/20817055/2277f74c-b7eb-11e6-8c0a-b28bfde055b3.png)

**Comment by blink1073** [comment]
Thanks for the report @birdsarah, expositional pictures are much appreciated.

**Comment by sccolbert** [comment]
I'm not sure I see the difference between the two screen grabs?

**Comment by sccolbert** [comment]
Oh, you mean the left padding and text clipping, got it.

**Comment by blink1073** [comment]
Fixed by #1358.
