### ISSUE TITLE
Oval-shaped circles in TOC running markers

### ISSUE THREAD

**Issue by denilsonsa** [jupyterlab/jupyterlab#13545]
## Description

When running all cells of a notebook while having the TOC open, little circles are displayed to the right of each section title. That's great, but those circles are oval-shaped sometimes, depending on the length of the title. This is specially noticeable if the cells take minutes to run.

## Reproduce

1. Create an IPython notebook inside Jupyter Lab.
2. Make sure to create several Markdown cells with titles (headings). Some of those should be long, others should be short.
3. Open the TOC (Table Of Contents) sidebar. Observe how some of the section titles are wrapped into multiple lines.
4. Restart and run all cells.
5. Pay attention to the little circles next to each section title.

## Expected behavior

All the circles should be uniform and look the same.

## What happens

Since each row from the TOC is an horizontal `flex` box, the circle can get its width adjusted according to the flex model. Look at this screenshot:

![Screenshot of the issue, several circles are distorted into ovals](https://user-images.githubusercontent.com/121676/205956868-16502a96-be4e-405e-8fcb-60e4acf93f93.png)

## Solution

Please add `flex: auto 0 0` to `.toc-entry-holder::after` selector. This is a shorthand for setting `flex-shrink` and `flex-grow` to zero, making sure that element maintains a fixed size.

See how I fixed it directly into the browser dev tools:

![Screenshot of the browser dev tools, showing the suggested fix.](https://user-images.githubusercontent.com/121676/205958210-259997de-165e-4393-b2ad-c9ab599a234d.png)

I can't find where this fix should be applied in this repository source-code. Can someone please apply the fix instead of me?

## Context

- Browser and version: Google Chrome 107
- JupyterLab version: 3.5.0

**Comment by uenot** [comment]
I'd like to claim this! I'm a new contributor, but I believe I've found the location of the fix— will open a PR shortly.

**Comment by sagar-ghub** [comment]
is this issue still open or the changes has been made ?

**Comment by uenot** [comment]
Changes have been made, see #13568

**Comment by fcollonval** [comment]
Closing as solved by #13568
