### ISSUE TITLE
Breaking changes in 3.6

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyterlab#13551]
### "@jupyterlab/docprovider" :

* getAnonymousUserName
* getRandomColor
* IDocumentProvider:
  * Added: isDisposed, ready
  * Removed: setPath, requestInitialContent, putInitializedState, acquireLock, releaseLock

The ready promise is important since we do not populate the Context until the provider is ready.

**Comment by jtpio** [comment]
Thanks @hbcarlos for reporting this :+1: 

For reference this was found while trying to use this extension with JupyterLab 3.6: https://github.com/jupyterlite/jupyterlab-webrtc-docprovider

Agree we should try to fix this changes if possible. Or at least document there. Likely there are not that many extensions relying on these extension points for now hopefully.
