### ISSUE TITLE
Update to yarn 3

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13552]
### Problem

For now `jlpm` is still pointing to a pinned version of  `yarn` 1: https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/staging/yarn.js

We should look into 

### Proposed Solution

There is a draft PR already open to update to the new version: https://github.com/jupyterlab/jupyterlab/pull/10929.

We can try to revive it to see if that would just work. Also worth checking how this would work with https://github.com/jupyterlab/hatch-jupyter-builder.

### Additional context

- https://github.com/jupyterlab/jupyterlab/issues/12848
- https://github.com/jupyterlab/jupyterlab/pull/10929

**Comment by jtpio** [comment]
Adding to the 4.0 milestone for consideration since this could be quite of a big change.

**Comment by mlucool** [comment]
Have we considered moving to pnpm? In practice, I have found this makes installs much, much faster, especially in monorepos such as this. While that sort of move requires stricter adherence to how dependencies are declared (read, it can be a bit painful at first), it does get you to a more secure setup.

[Yarn 3.1 includes pnpm support](https://dev.to/arcanis/yarn-31-corepack-esm-pnpm-optional-packages--3hak#new-install-mode-raw-pnpm-endraw-), but I'm not sure the value-add of yarn if you don't use it's linker.

**Comment by mlucool** [comment]
FWIW, lerna also supports pnpm - https://lerna.js.org/docs/recipes/using-pnpm-with-lerna

**Comment by williamstein** [comment]
I recently switched over all over CoCalc to pnpm and I LOVE IT.

**Comment by jtpio** [comment]
cc @brichet who is currently looking into this.

For some reasons I can't assign the issue to him, but posting here for visibility so everyone knows there is on-going work and investigations.
