### ISSUE TITLE
Respect markdown code boundaries for code execution

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1357]
https://github.com/jupyterlab/jupyterlab/issues/450#issuecomment-263817275

**Comment by ellisonbg** [comment]
Just to clarify for others, if there is a fenced code block in a markdown text file and a user has started a kernel/console for that text editor and presses shift+enter (or similar), we should autodetect the entire code block and run it all rather than just the current line or selected.
