### ISSUE TITLE
Error while configuring jupyterlab

### ISSUE THREAD

**Issue by jian374** [jupyterlab/jupyterlab#13583]
hello all,
When I type jupyterlab in the terminal it appears
`jupyter lab`
jupyter lab
[W 2022-12-13 07:03:58.112 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2022-12-13 07:03:58.397 ServerApp] ipyparallel | extension was successfully linked.
[I 2022-12-13 07:03:58.402 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2022-12-13 07:03:58.408 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-12-13 07:03:58.413 ServerApp] nbclassic | extension was successfully linked.
[I 2022-12-13 07:03:58.417 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-12-13 07:03:58.672 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-12-13 07:03:58.673 ServerApp] Loading IPython parallel extension
[I 2022-12-13 07:03:58.674 ServerApp] ipyparallel | extension was successfully loaded.
[I 2022-12-13 07:03:58.676 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2022-12-13 07:03:58.676 LabApp] JupyterLab extension loaded from /home/mj/miniconda3/envs/fermi3ML/lib/python3.9/site-packages/jupyterlab
[I 2022-12-13 07:03:58.677 LabApp] JupyterLab application directory is /home/mj/miniconda3/envs/fermi3ML/share/jupyter/lab
[I 2022-12-13 07:03:58.680 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-12-13 07:03:58.684 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-12-13 07:03:58.684 ServerApp] Serving notebooks from local directory: /home/mj
[I 2022-12-13 07:03:58.684 ServerApp] Jupyter Server 2.0.1 is running at:
[I 2022-12-13 07:03:58.684 ServerApp] http://127.0.0.1:8888/lab
[I 2022-12-13 07:03:58.684 ServerApp]  or http://127.0.0.1:8888/lab
[I 2022-12-13 07:03:58.684 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

Please tell me how to solve  `ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password. ` this warning

thanks

**Comment by jweill-aws** [comment]
The error is in Jupyter Server, not JupyterLab; resolving in favor of the Jupyter Server issue https://github.com/jupyter-server/jupyter_server/issues/1130.
