### ISSUE TITLE
incr-font-size  is not work

### ISSUE THREAD

**Issue by FoSuCloud** [jupyterlab/jupyterlab#13598]
## Description

click 【apputils:incr-font-size】、【apputils:incr-font-size】、【apputils:decr-font-size】、【apputils:decr-font-size】、【apputils:incr-font-size】、【apputils:decr-font-size】 button，
 but font-size not change

## Reproduce

1. install jupyterlab
2.  jupyter lab 
3. click 【apputils:incr-font-size】button , but no size-change, the screen has change

## Expected behavior

click 【apputils:incr-font-size】button , font-size change

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 
max os 12.2
Chrome 108
JupyterLab v3.4.7

1、api request: lab/api/settings response data:
{
id: "@jupyterlab/apputils-extension:themes",
schema:definitions....
code-font-size: {type: ["string", "null"], description: "字体大小"}
}
2、packages/apputils/src/thememanager.ts
function validateCSS 
view this._overrideProps
{code-font-family:"字体集",
code-font-size:"字体大小",
content-font-family:"字体集",
content-font-size1:"字体大小",
ui-font-family:"字体集",
ui-font-size1:"字体大小"}

CSS not supports

**Comment by jweill-aws** [comment]
I can reproduce this in JupyterLab 3.5.1 by opening the command palette and selecting "Increase font size". Neither code cells nor markdown cells increase in size. The "Increase Code Font Size" command does work, though.

**Comment by jweill-aws** [comment]
Possibly related: #12537 / #12178

**Comment by FoSuCloud** [comment]
This problem occurs if the language is not English
