### ISSUE TITLE
Unable to change theme (possible bug)

### ISSUE THREAD

**Issue by rwuthric** [jupyterlab/jupyterlab#13597]
## Description

Unable to change the Settings>Theme neither the Settings>Terminal Theme

When using Settings>Advanced Settings Editor and JSON Settings Editor I can change the theme entries but not save the changes. 

When attempting to save any change an error message "Your changes were not saved. Invalid response: 500 Internal Server Error" pops up.

## Expected behavior

Change from a theme to another

## Context
- Operating System and version:  Linux Ubuntu 22.04 
- Browser and version: FireFox

jupyter==1.0.0
jupyter-client==7.4.8
jupyter-console==6.4.4
jupyter-core==5.1.0
jupyter-events==0.5.0
jupyter-scheduler==1.1.4
jupyter-server==1.23.3
jupyter-server-mathjax==0.2.6
jupyter-server-terminals==0.4.2
jupyter-telemetry==0.1.0
jupyterhub==3.1.0
jupyterlab==3.5.1
jupyterlab-git==0.39.2
jupyterlab-pygments==0.2.2
jupyterlab-server==2.16.5
jupyterlab-widgets==3.0.3

**Comment by jweill-aws** [comment]
The error you're seeing is 500 (Internal Server Error). Can you please share the logs that the server generates at this moment?

Possibly related to #13580.

**Comment by rwuthric** [comment]
Definitively. Where would I find them?

**Comment by jweill-aws** [comment]
If you're running JupyterLab from a terminal (e.g., as `jupyter lab`) the logs should be present in that terminal.

**Comment by rwuthric** [comment]
I am running a JupyterHub server. Where does it create the log files? Then I can go there and dig it out

**Comment by jweill-aws** [comment]
Per https://github.com/jupyterhub/jupyterhub/issues/1522#issuecomment-343104150 , JupyterHub also prints log info to the terminal; you can optionally mirror it to a file.

**Comment by rwuthric** [comment]
Dec 15 16:02:28 navserver jupyterhub[2684726]: [W 2022-12-15 16:02:28.893 SingleUserLabApp web:1796] 500 PUT /user/rwuthric/lab/api/workspaces/default?1671138148853 (::fff>
Dec 15 16:02:28 navserver jupyterhub[2684726]: [W 2022-12-15 16:02:28.893 LabApp] wrote error: "[Errno 13] Permission denied: '/opt/jupyterhub/etc/jupyter/lab'"
Dec 15 16:02:28 navserver jupyterhub[2684726]: [E 2022-12-15 16:02:28.895 SingleUserLabApp log:178] {
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "X-Forwarded-Host": "10.0.0.83:8000",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "X-Forwarded-Proto": "http",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "X-Forwarded-Port": "8000",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "X-Forwarded-For": "::ffff:10.0.0.24",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Cache-Control": "no-cache",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Pragma": "no-cache",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Cookie": "_xsrf=[secret]; jupyterhub-user-rwuthric=[secret]; jupyterhub-session-id=[secret]",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Connection": "close",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Origin": "http://10.0.0.83:8000",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Content-Length": "420",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "X-Xsrftoken": "2|f8b63f2c|8ff623a1e396d7d9c76e6a60b3b10a8a|1669927253",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Authorization": "token [secret]",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Content-Type": "text/plain;charset=UTF-8",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Referer": "http://10.0.0.83:8000/user/rwuthric/lab?redirects=1",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Accept-Encoding": "gzip, deflate",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Accept-Language": "en-US,en;q=0.5",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Accept": "*/*",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0",
Dec 15 16:02:28 navserver jupyterhub[2684726]:       "Host": "10.0.0.83:8000"
Dec 15 16:02:28 navserver jupyterhub[2684726]:     }

**Comment by rwuthric** [comment]
Is this what you look for?

I checked as well this location:

ls -l /opt/jupyterhub/etc/jupyter/
total 12
drwxr-xr-x 2 root root 4096 Dec 15 01:56 jupyter_notebook_config.d
drwxr-xr-x 2 root root 4096 Dec 15 01:56 jupyter_server_config.d
drwxr-xr-x 3 root root 4096 Sep 16 09:06 nbconfig

There is no '/opt/jupyterhub/etc/jupyter/lab'

Maybe it helps for you?

**Comment by rwuthric** [comment]
This JupyterHub runs as root. I created the folder and now I see this error (after a clean logou and lgin with user rwuthric):

Dec 15 17:06:00 navserver jupyterhub[2706836]: [W 2022-12-15 17:06:00.497 LabApp] wrote error: "[Errno 13] Permission denied: '/opt/jupyterhub/etc/jupyter/lab/workspaces'"

When I try to change the theme settings the errors look like that:

Dec 15 17:09:00 navserver jupyterhub[2706836]: [W 2022-12-15 17:09:00.916 LabApp] wrote error: "Failed writing settings (@jupyterlab/apputils-extension:themes): [Errno 13]>
Dec 15 17:09:00 navserver jupyterhub[2706836]: [E 2022-12-15 17:09:00.919 SingleUserLabApp log:178] {
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "X-Forwarded-Host": "10.0.0.83:8000",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "X-Forwarded-Proto": "http",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "X-Forwarded-Port": "8000",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "X-Forwarded-For": "::ffff:10.0.0.24",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Cache-Control": "no-cache",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Pragma": "no-cache",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Cookie": "_xsrf=[secret]; jupyterhub-user-rwuthric=[secret]; jupyterhub-session-id=[secret]",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Connection": "close",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Origin": "http://10.0.0.83:8000",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Content-Length": "260",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "X-Xsrftoken": "2|f8b63f2c|8ff623a1e396d7d9c76e6a60b3b10a8a|1669927253",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Authorization": "token [secret]",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Content-Type": "text/plain;charset=UTF-8",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Referer": "http://10.0.0.83:8000/user/rwuthric/lab/tree/tmp",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Accept-Encoding": "gzip, deflate",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Accept-Language": "en-US,en;q=0.5",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Accept": "*/*",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0",
Dec 15 17:09:00 navserver jupyterhub[2706836]:       "Host": "10.0.0.83:8000"
Dec 15 17:09:00 navserver jupyterhub[2706836]:     }
Dec 15 17:09:00 navserver jupyterhub[2706836]: [E 2022-12-15 17:09:00.919 SingleUserLabApp log:186] 500 PUT /user/rwuthric/lab/api/settings/@jupyterlab/apputils-extension:>

**Comment by jweill-aws** [comment]
OK. It looks like the directory ending in `jupyter/lab/workspaces` might also not exist. After searching the web for `"Errno 13"` and other keywords, this may be an issue with the permissions of directories in your file system. You might be able to work around this by creating the needed subdirectories manually, as you had done above. I'm not able to provide more specific guidance; this doesn't appear to be an issue in JupyterLab.

**Comment by rwuthric** [comment]
Thank you for the help. For info: the issue started to appear when I did upgrade to latest JupyterLab version. Maybe something got messed up with files permissions. Will try to search that.

**Comment by jweill-aws** [comment]
No problem! I'll close out this issue, but please feel free to reopen this one or open another issue if you notice any other problems with JupyterLab.

**Comment by rwuthric** [comment]
I made a fresh install of the JupyterHub following [https://github.com/jupyterhub/jupyterhub-the-hard-way/blob/HEAD/docs/installation-guide-hard.md](https://github.com/jupyterhub/jupyterhub-the-hard-way/blob/HEAD/docs/installation-guide-hard.md)

I still face the same issue: impossible to switch between the themes.
