### ISSUE TITLE
[vega5-extension] The PNG representation added to the output is not scaled according to the `scaleFactor` option

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/jupyterlab#13596]
Hi! 👋 

## Description

When displaying a Vega-Lite chart in JupyterLab or creating a chart with Altair (using the [mimetype renderer](https://altair-viz.github.io/user_guide/display_frontends.html#altair-s-renderer-framework)), the cell output also contains a PNG representation of the chart. Since this representation is created directly from [one of Vega's View API methods](https://vega.github.io/vega/docs/api/view/#view_toImageURL) with only the type argument defined, the `scaleFactor` corresponds to 1, the default value. However, given that it is possible to define a different `scaleFactor` from the [Vega-Embed options](https://github.com/vega/vega-embed#options), if this value is different from 1, it is "ignored" when creating this representation in PNG, as this value is not passed directly when calling the `.toImageURL()` method. The relevant line of code is [this one](https://github.com/jupyterlab/jupyterlab/blob/v3.5.1/packages/vega5-extension/src/index.ts#L136).

## Reproduce

> You can find this example in [this repository folder](https://github.com/joaopalmeiro/python-playground/tree/master/try-vega5-extension).

1. Create a new notebook and `display()` the following chart:

```python
# First cell
from IPython.display import display
```

```python
# Second cell
display(
    {
        "application/vnd.vegalite.v4+json": {
            "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
            "description": "A simple bar chart with embedded data.",
            "data": {
                "values": [
                    {"a": "A", "b": 28},
                    {"a": "B", "b": 55},
                    {"a": "C", "b": 43},
                    {"a": "D", "b": 91},
                    {"a": "E", "b": 81},
                    {"a": "F", "b": 53},
                    {"a": "G", "b": 19},
                    {"a": "H", "b": 87},
                    {"a": "I", "b": 52},
                ]
            },
            "mark": "bar",
            "encoding": {
                "x": {"field": "a", "type": "nominal", "axis": {"labelAngle": 0}},
                "y": {"field": "b", "type": "quantitative"},
            },
        }
    },
    metadata={
        "application/vnd.vegalite.v4+json": {
            "embed_options": {
                "scaleFactor": 5,
            }
        }
    },
    raw=True,
)
```

3. Click on the Vega-Embed button in the upper right corner of the chart and download it in PNG format.
4. Check the width and height of the generated image.
5. Run the following script, reading the previous notebook as a JSON file, and compare the heights and widths of both images (the embedded image was not scaled):

```python
import base64
import json
import struct

if __name__ == "__main__":
    with open("dev.ipynb", "r") as fp:
        nb = json.load(fp)

    output = nb["cells"][1]["outputs"][0]

    base64_img = output["data"]["image/png"]
    binary_img = base64.b64decode(base64_img)

    w, h = struct.unpack(">LL", binary_img[16:24])
    print(f"Width: {w}; Height: {h}")

    scaleFactor = output["metadata"]["application/vnd.vegalite.v4+json"][
        "embed_options"
    ]["scaleFactor"]
    print(f"scaleFactor (metadata): {scaleFactor}")

    with open("via_embedded_image.png", "wb") as fp:
        fp.write(base64.b64decode(base64_img))
```

Alternative: copy and paste the string from the PNG representation into a Base64 image viewer like [this one](https://jaredwinick.github.io/base64-image-viewer/).

#### Via Vega-Embed button

![via_vega_embed_button](https://user-images.githubusercontent.com/17132927/207733194-3485467b-53ba-461f-9fcd-500a8f40f68c.png)

#### Via embedded PNG image

![via_embedded_image](https://user-images.githubusercontent.com/17132927/207733214-1fc83992-05bc-4f0e-99a2-7abd53b20b20.png)

## Expected behavior

The PNG representation added to the output is scaled according to the `scaleFactor` option.

### Proposed solution

If you think this flexibility makes sense for this PNG representation, I would also pass the scaleFactor like this (based on [how it's done in Vega-Embed](https://github.com/vega/vega-embed/pull/75)):

```diff
- const imageURL = await this._result.view.toImageURL('png');
+ const imageURL = await this._result.view.toImageURL('png', embedOptions.scaleFactor);
```

## Context

- Operating System and version: macOS Monterey 12.5
- Browser and version: Chrome 104
- JupyterLab version: 3.5.1 (and 3.2.5)

### References

- https://github.com/vega/vega-embed/issues/73
- https://github.com/vega/vega-embed/pull/75
- https://vega.github.io/vega/docs/api/view/#view_toImageURL
- https://altair-viz.github.io/user_guide/display_frontends.html#altair-s-renderer-framework
- https://github.com/vega/vega-embed#options

**Comment by fcollonval** [comment]
Thanks a lot @joaopalmeiro 

As you figure out what is required (thanks a lot for that), would you be willing to open a PR to fix it?

**Comment by joaopalmeiro** [comment]
> Thanks a lot @joaopalmeiro
> 
> As you figure out what is required (thanks a lot for that), would you be willing to open a PR to fix it?

Thanks, @fcollonval! Sure, it will be a pleasure! I just need some time to look in more detail at the contribution guidelines and what I need to do regarding testing, assuming something is needed.

**Comment by fcollonval** [comment]
Thanks don't hesitate to start a PR early. I'll help you setup a test.
