### ISSUE TITLE
Better method for handling mime renderer order

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#1361]
When registering a mime renderer, the extension can specify its position in the order of renderers:

```js
rendermime.addRenderer('application/json', new JSONRenderer(), 0);
```
https://github.com/jupyterlab/jupyterlab_json/blob/master/src/plugin.ts#L40

However, I have several "+json" renderers, all of which also register themselves as `0`, so the following will be rendered as a JSON tree (when I really want it rendered as a Plotly chart):

```py
from IPython.display import display
data = [
  {'x': [1999, 2000, 2001, 2002], 'y': [10, 15, 13, 17], 'type': 'scatter'},
  {'x': [1999, 2000, 2001, 2002], 'y': [16, 5, 11, 9], 'type': 'scatter'}
]

layout = {
  'title': 'Sales Growth',
  'xaxis': { 'title': 'Year', 'showgrid': False, 'zeroline': False },
  'yaxis': { 'title': 'Percent', 'showline': False }
}

bundle = {
    'application/vnd.plotly.v1+json': {
        'data': data,
        'layout': layout,
    },
    'application/json': {
        'data': data
    },
    'text/plain': '<IPython.core.display.Plotly object>'
}

display(bundle, raw=True)
```

The current solution is to just comment out the `application/json` output, but I'd like to start working on a feature that would allow users to switch between the available renderers given the different output mime types. This will require a more elegant solution for ordering renderers given a mime type. 

To address this specific use case, mime types of "application/*+json" can take presence over "application/json". 

Any suggestions?

**Comment by blink1073** [comment]
What if we added a `setOrder(mimetypes: IterableOrArrayLike): void` that allowed you to set the order explicitly?

**Comment by gnestor** [comment]
@blink1073 Could you provide a usage example? I'm not very familiar with generators, but if I'm catching your drift, would it allow for something (like a [sort compare function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)) to calculate the renderer's index? What if the [`index` argument](http://jupyterlab.github.io/jupyterlab/classes/_rendermime_index_.rendermime.html#addrenderer) of `rendermime.addRenderer` could accept a function? For example:

```js
rendermime.addRenderer('application/json', new JSONRenderer(), otherMimetype => (
  if (otherMimetype.endsWith('+json') return 0;
  return 1;
));
```

**Comment by blink1073** [comment]
It would be a way to manually sort the mimetype preference order.  In your case, I think what you want can be done with the existing api:

```typescript
import {
  toArray
} from 'phosphor/lib/algorithm/iteration';

import {
  findLastIndex
} from 'phosphor/lib/algorithm/searching';

let index = findLastIndex(toArray(rendermime.mimetypes()), mimetype => mimetype.indexOf('+json') !== 0) + 1;
rendermime.addRenderer('application/json', new JSONRenderer(), index);
```

**Comment by gnestor** [comment]
This seems like a pretty good solution to me! I'll give it a try!

**Comment by sccolbert** [comment]
This sounds like it could be a good use of a topological sort. The API could allow you to express ordering with "before" and "after" constraints. Phosphor already has a `topSort` implementation.

**Comment by blink1073** [comment]
The reason we haven't been using `topSort` in cases like this is that we can't be sure of the order of registration of different plugins, so the thing you'd like to be `before` may not be there yet.

**Comment by blink1073** [comment]
We could store the constraints and then re-sort every time something is added, I suppose...

**Comment by sccolbert** [comment]
@blink1073 if it's not there, that's fine. You only sort when you finally need to use something, not every time something is added. The `topSort` algorithm is tolerant of missing nodes and over-constraints.

**Comment by gnestor** [comment]
I'm running into a issue like during the Fall meeting: On build, I'm getting the following errors:

```
src/plugin.ts(53,46): error TS2345: Argument of type 'JSONRenderer' is not assignable to parameter of type 'IRenderer'.
  Types of property 'render' are incompatible.
    Type '(options: IRendererOptions<JSONObject>) => Widget' is not assignable to type '(options: IRendererOptions<string | JSONObject>) => Widget'.
src/plugin.ts(68,29): error TS2345: Argument of type 'JSONWidgetFactory' is not assignable to parameter of type 'IWidgetFactory<Widget, IModel>'.
  Types of property 'widgetCreated' are incompatible.
    Type 'ISignal<IWidgetFactory<JSONWidget, IModel>, JSONWidget>' is not assignable to type 'ISignal<IWidgetFactory<Widget, IModel>, Widget>'.
      Type 'IWidgetFactory<JSONWidget, IModel>' is not assignable to type 'IWidgetFactory<Widget, IModel>'.
        Type 'JSONWidget' is not assignable to type 'Widget'.
          Types of property 'disposed' are incompatible.
            Type 'ISignal<Widget, void>' is not assignable to type 'ISignal<Widget, void>'.
src/renderer.tsx(71,7): error TS2420: Class 'JSONRenderer' incorrectly implements interface 'IRenderer'.
  Types of property 'render' are incompatible.
    Type '(options: IRendererOptions<JSONObject>) => Widget' is not assignable to type '(options: IRendererOptions<string | JSONObject>) => Widget'.
      Type 'Widget' is not assignable to type 'Widget'.
        Types of property 'title' are incompatible.
          Type 'Title' is not assignable to type 'Title'.
            Types have separate declarations of a private property '_label'.
src/widget.tsx(100,50): error TS2344: Type 'JSONWidget' does not satisfy the constraint 'Widget'.
  Types of property 'disposed' are incompatible.
    Type 'ISignal<Widget, void>' is not assignable to type 'ISignal<Widget, void>'.
      Types of property 'connect' are incompatible.
        Type '(slot: (sender: Widget, args: void) => void, thisArg?: any) => boolean' is not assignable to type '(slot: (sender: Widget, args: void) => void, thisArg?: any) => boolean'.
          Types of parameters 'slot' and 'slot' are incompatible.
            Type '(sender: Widget, args: void) => void' is not assignable to type '(sender: Widget, args: void) => void'.
              Types of parameters 'sender' and 'sender' are incompatible.
                Type 'Widget' is not assignable to type 'Widget'.
```

Specifically:

```
Type 'Widget' is not assignable to type 'Widget'.
```

I just upgraded my jupyterlab dependency so I assume that's the culprit, but what is the solution other than downgrading jupyterlab?

**Comment by sccolbert** [comment]
@gnestor This can happy when (for some reason) more than one copy of Phosphor is installed in `node_modules`. You can either run `npm dedupe`, or blow away `node_modules` and rerun `npm install`. That should clear it up.

**Comment by gnestor** [comment]
@sccolbert Tried both of those and no luck... I also updated my dependencies so that there is only one version of phosphor:

```
grant:labextension grant$ npm ls phosphor
jupyterlab_json_labextension@0.1.0 /Users/grant/Sites/jupyter/jupyterlab_json/labextension
├─┬ jupyterlab@0.11.2
│ └── phosphor@0.7.0 
└── phosphor@0.7.0 
```

Any other ideas?

**Comment by sccolbert** [comment]
That's two copies of the same version, and will lead to the same problem. There can be only *one* copy of Phosphor, of *any* version in `node_modules`. `npm dedupe` should have solved this problem for you. Can you paste the output of that command?

To explain the compile errors: What's happening is that a variable of type `Widget` is being passed across library boundaries, where library A is using the Phosphor from the root dir, and library B is using the phosphor from the nested dir. The `typescript` compiler is seeing these as two different types from different libraries, and saying they are not compatible. The message is cryptic, but it's a good error to get because at runtime, this problem manifests as `instanceof` checks failing when they shouldnt, because there are multiple `Widget` prototypes loaded on the page.

**Comment by gnestor** [comment]
Ok, `npm dedupe` after all of this resolved it. That makes sense now. Thanks for the help! Regarding above, can you share an example usage of `topSort`?

**Comment by sccolbert** [comment]
@gnestor What version of `npm` are you running? A clean `npm install` shouldn't require `dedupe` if you are using `npm >= 3`.

**Comment by gnestor** [comment]
Ya that's what I thought. I'm running `3.10.8`.

**Comment by blink1073** [comment]
@gnestor we had previously used topSort to solve for menu item ordering: https://github.com/phosphorjs/phosphide/blob/73b94d2b5307c79aee687f87bfdad1370c7394c3/temp/menus/menusolver.ts

**Comment by gnestor** [comment]
@blink1073 Thanks for sharing 👍

**Comment by gnestor** [comment]
I think this is resolved. I ended up with:

```js
const index = findLastIndex(toArray(rendermime.mimetypes()), mimetype => mimetype.endsWith('+json')) + 1;
rendermime.addRenderer('application/json', new JSONRenderer(), index);
```
