### ISSUE TITLE
Support interactive UI components in cells

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#1363]
Support interactive UI compnents such as buttons, sliders, etc. For JupyterLab to rock, better interactive UI support is necessary. If implemented, users can easily build simple dashboards based on JupyterLab. At least JupyterLab should support existing interactive UI packages.

**Comment by blink1073** [comment]
Hi @dclong, there is tentative support for [ipywidgets](https://github.com/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20List.ipynb) in JupyterLab, https://github.com/ipython/ipywidgets/tree/master/jupyterlab_widgets.   We are still ironing out the third party extension process, but it will be done in time for beta.

**Comment by blink1073** [comment]
Other interactive UI features will also be enabled as third party extensions, such as a geojson viewer that uses open street map: https://github.com/jupyterlab/jupyterlab_geojson.

**Comment by dclong** [comment]
@blink1073 
That is awesome! There are HTML widget packages (e.g., DT, scatterD3, etc.) in R as well. Will JupyterLab support those packages? Or does this belongs to the scope of the IRKernel project?

**Comment by blink1073** [comment]
Our goal is to make better use of mimetypes for rendering (such as `application/table-schema+json` for a JSON table), so that any kernel can output the desired mimetype, and use a JupyterLab plugin to render it.  cf https://github.com/jupyterlab/mimerender-cookiecutter.

**Comment by ellisonbg** [comment]
Closing for now, please feel free to re-open if needed.
