### ISSUE TITLE
Upgrade XTerm to the latest

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13649]
We should update xterm.js to the latest version: https://github.com/xtermjs/xterm.js/releases/tag/5.1.0

It has the benefit of being lighter and using the more efficient webgl renderer.

**Comment by jweill-aws** [comment]
As a downside, the `setOption` function has been removed in 5.0.0. See https://github.com/xtermjs/xterm.js/pull/3947 . 

It looks like we might be able to get around this by letting `theme` and `fontSize` be set in `setOption` in `packages/terminal/src/widget.ts`, then add a `setOptions` function to set all options at once.
