### ISSUE TITLE
Reorganize the source folders

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1364]
## Updated proposal

We are moving toward submodules to address lab extension compatibility.  The heuristic is for non-plugins with a single source file to be in `common/` and everything else in their own folders.

I propose we make the following changes:

| From  | To   |
|---|---|
| sanitizer | common |
| iframe | common |
| dialog | common |
| notebook/common | common |
| notebook/cell | cell |
| notebook/output-area | output-area |
| notebook/notebook | notebook |
| renderers | rendermime |

**Comment by blink1073** [comment]
@afshin @jasongrout, thoughts?

**Comment by ellisonbg** [comment]
Sounds good to me

**Comment by ellisonbg** [comment]
Not quite build system, but close enough..

**Comment by blink1073** [comment]
@ellisonbg, if you agree with the proposal, then I'd like to leave this open until I do it in a PR.

**Comment by ellisonbg** [comment]
LOL, didn't mean to close ;-( too many button to keep track of. Doing a big triage pass right now, very likely will mess up a few times - please feel free to correct me :-)

**Comment by blink1073** [comment]
@ellisonbg, @afshin, I updated the proposal in the original comment.

**Comment by ellisonbg** [comment]
+1 on the proposed changes
