### ISSUE TITLE
Both completer and document search event handlers get dispatched on Esc

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13659]
## Description

`Cannot execute key binding 'Escape': command 'documentsearch:end' is not enabled.` shows up when closing completer with <kbd>Esc</kbd> in file editor

## Reproduce

1. Open text editor with python file
2. Invoke completer
3. Press Esc
4. See error in browser console

## Expected behavior

- completer widget cancels event if handled
- document search selector is more specific selecting only documents with open search view

## Context

- Browser and version: Chrome 108
- JupyterLab version: 4.0.0a31

**Comment by TigreModerata** [comment]
Hi, I tried to work on this, I have a draft solution - do I just make a push my branch and make a pull request? Do I have to assigned the issue first?

**Comment by krassowski** [comment]
Yes, feel welcome to open a pull request!

**Comment by krassowski** [comment]
One part of this issue (search box-side) was solved by https://github.com/jupyterlab/jupyterlab/pull/14421. We also changed a lot about key bindings (capture phase, etc) since this issue was opened so I will close it for now, as I am not sure if this is still a problem.
