### ISSUE TITLE
Reading values into variables from console doesn't work

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#1365]
Reading values to variables from console doesn't work in R. Didn't try this in Python. In addition, shell output when invoked from R are not forwarded to JupyterLab correctly. Again, I didn't try this in Python.

**Comment by blink1073** [comment]
Can you describe what you mean?  Below is the behavior I'd expect.  

![image](https://cloud.githubusercontent.com/assets/2096628/20887697/64e6be0a-bac1-11e6-8e1f-4e18baff712d.png)

**Comment by dclong** [comment]
For example, the following code in R prompt to ask for an input but nothing happens in R Notebook. 
```
x = scan(what=character(), n =1)
```

**Comment by blink1073** [comment]
Ah, it looks like the `IRKernel` is not implementing the  input request of the kernel protocol.  cf https://github.com/IRkernel/IRkernel/issues/199.

**Comment by ellisonbg** [comment]
Closing for now, please feel free to re-open if needed.
