### ISSUE TITLE
Interactive Commandline with Textualize

### ISSUE THREAD

**Issue by TheRook** [jupyterlab/jupyterlab#13658]
Textulize is a library that is far more advanced than ncruses:
https://textual.textualize.io/blog/2022/12/20/a-year-of-building-for-the-terminal/

You can have interactive forms, and buttons that you click on with a mouse - all in the commandline. 

In an ideal world someone could have the option to jypter not in a browser, but with Textulize.  The advantage here is that you can run it over SSH on a thin client and it will use virtually no resources while still having a friendly user interface.

**Comment by krassowski** [comment]
Please see #10283. But, yes it is a neat idea.

**Comment by TheRook** [comment]
There has been major advancements since the days of ncruses.  This library really nails it, I think this library is a really good fit for jupyter.

**Comment by davidbrochart** [comment]
[jpterm](https://github.com/davidbrochart/jpterm) uses Textual, but it is very much a work in progress.

**Comment by TheRook** [comment]
> [jpterm](https://github.com/davidbrochart/jpterm) uses Textual, but it is very much a work in progress.

It would be nice if this was a commandline argument on the mainline so that you can easily run it over SSH.

**Comment by jweill-aws** [comment]
I'm not sure that this is going to be within the scope of JupyterLab; to implement a Textualize front-end in lieu of the current HTML front-end would require pretty much all of the UI components and paradigms to be reimplemented in Textualize. As with JupyterLite, jpterm, etc., I think that your proposal is going to be more easily implemented as a project of its own than as an option in JupyterLab.

I'm going to close this as an issue in JupyterLab, but I think this is still a good idea to discuss on [our Discourse forum](https://discourse.jupyter.org/). Thank you for your contribution!
