### ISSUE TITLE
Unable to change some settings after searching

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13651]
## Description

Settings fail to save as JupyterLab Shell schema defaults does not meet the schema (which is wrong).

## Reproduce

1. Go to 'Settings'
2. Search "panel"
3. Click on 'JupyterLab Shell'

![Screenshot from 2022-12-23 00-13-53](https://user-images.githubusercontent.com/5832902/209246285-625656fb-420a-4827-8612-dc574910b707.png)

## Expected behavior

Settings can be set

## Context
JupyterLab 4.0.0a30

**Comment by krassowski** [comment]
This also happens with LSP completer settings. I think that this is because the `definitions` part of schema gets filtered out and the defaults no longer validate against the filtered schema.

**Comment by jtpio** [comment]
As reported in https://github.com/jupyterlab/jupyterlab/issues/13762, this is still an issue in 4.0.0a32.

**Comment by andrii-i** [comment]
Based on my testing for #14292, it's still not present in 4.0.0a31. When you search, filter is getting applied to schema only and as result doesn't cover all properties thrown at it by the plugin

**Comment by JasonWeill** [comment]
@marthacryan Can you take a look at this issue, please? We need to either fix search or remove it from the settings editor in the 4.0.0 release.
