### ISSUE TITLE
Completer manager plugin is named `:tracker` but probably should be  `:manager`

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13669]
I noticed that the completer-extension manager plugin is named as `:tracker`:

https://github.com/jupyterlab/jupyterlab/blob/552cdfe9314365d668c029e0863cf2fdbbbee4df/packages/completer-extension/src/index.ts#L24

I would think that `:manager` is more appropriate here as it is not a tracker. Is this a copy-paste error, or was this intended? On 3.x branch we did have a `:manager` too (but with a different API).

CC @trungleduc

**Comment by trungleduc** [comment]
I think this is a copy-paste error.
