### ISSUE TITLE
Open terminal in the cwd of the file browser

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#1366]
When opening a new terminal, I think the best working directory should be the current directory in the file explore or the current working directory of the notebook. However, it seems that neither of them of used. The working directory of a new terminal is confusing to me.

**Comment by blink1073** [comment]
Hi @dclong, this issue was being tracked in #782, but I like your title better ;).

**Comment by ellisonbg** [comment]
This could be implemented on top of #2855

**Comment by ellisonbg** [comment]
Then, no server change is required.

**Comment by Madhu94** [comment]
I'd like to try fixing this.

**Comment by nathancarter** [comment]
When using JupyterLab for education, this is a very annoying missing feature.  It means that if I want to teach even something as simple as how to run a Python script with "python file_name.py" I have to first teach

 * `ls`/`pwd`/`cd` to the students who brought Mac laptops,
 * `dir`/`cd`/`cd` to the students who brought PC laptops,
 * and quoting/escaping folder names for those whose paths contain spaces,

in total a huge distraction from the actual educational goals of the lesson.

Seems like a small feature, but ticket open for two years...perhaps it could be reprioritized?  Thank you!

**Comment by vidartf** [comment]
@nathancarter contributions welcome!

**Comment by vidartf** [comment]
More constructively: The efforts of the core contributors are quite thinly stretched, and there are a *lot* "small" issues. This means that the core contributors have no chance of clearing all of them, so we are dependent on other contributors for helping carry the load. If you think that this feature is worthwhile to you, and the feature is indeed a small feature, then hopefully this is something you could help us with. We are more than happy to spend some time in helping new contributors, in the hope that they will also end up contributing further fixes later on.

**Comment by nathancarter** [comment]
Hey @vidartf ...I think we had a beer in Luxembourg together last year.  Hi again!

This seems like a small enough issue that I might be able to attack it.  Right now I'm swamped, but I spent a little time this morning looking over the jupyterlab source for the first time, and I think I at least see where to start, which I'll record here for myself or anyone else later:

 * [Here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/terminal-extension/src/index.ts#L293) is the line where new terminals are created.  This would seem to be the line to tweak, passing in a cd to the new directory as the initial command.
 * [Here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/terminal/src/widget.ts#L41) is the signature for the constructor, which takes an options object including the initial command option from #2866, mentioned above.
 * [Here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/terminal/src/widget.ts#L75) is where that option is used.

I'm not sure when I'll have time to get back to it, though.

If anyone has any tips on the magic incantation that tells you the current directory of the file manager widget, I'd be grateful.  It would seem to be straightforward from there.

Well, that is, once I go through the process of setting up a jupyter lab dev environment, which I haven't tried yet.  Or somebody who already has one and who knows the magic incantations could follow those instructions. :)

**Comment by jasongrout** [comment]
@nathancarter - great to hear from you, it's been a while!

@vidartf - Nathan understands very well what it's like to maintain an open source software project and be stretched thin doing so :).

**Comment by nathancarter** [comment]
Yeah, sorry if my initial post sounded like a demand -- my bad!

**Comment by jasongrout** [comment]
For the path, I think mimicking how the console does it might work: https://github.com/jupyterlab/jupyterlab/blob/6bbe1a12c618413f3aa77ede589cc9c92ab4a7e9/packages/console-extension/src/index.ts#L336-L340

In other words, make it an option that can be passed in with a default of the default filebrowser's directory (there could be more than one file browser in a JLab instance).

**Comment by jasongrout** [comment]
You can also see several other examples, like this example in the notebooks, by searching the source for `defaultBrowser.model.path`:

https://github.com/jupyterlab/jupyterlab/blob/6992d9bc04f6851f062d02568a6066218deb82ad/packages/notebook-extension/src/index.ts#L692-L695

**Comment by jasongrout** [comment]
(actually, the notebook example above is probably better to follow than the console, since it is a bit more defensive and only has one option instead of two)

**Comment by nathancarter** [comment]
OK that sounds like a plan, thank you.  I'll enact that plan if/when I get some free time to set up a jupyter lab dev env.  Thanks again...

**Comment by jasongrout** [comment]
Thanks! Even better, mentor an interested student to be able to do it :)

**Comment by ian-r-rose** [comment]
I haven't been following this in detail, but the `@jupyterlab/git` extension has a command that does something very similar, you could try cribbing from that: https://github.com/jupyterlab/jupyterlab-git/blob/f2abd5250f22657427a73e0b11340033917320bf/src/gitMenuCommands.ts#L44-L71

One thing to keep in mind: we'd like the commands to be as agnostic as possible to the OS that is being used: we should try to make sure that the terminal command works on Windows, Linux, and Macs.

**Comment by jasongrout** [comment]
Luckily, everyone understands `cd` and can use posix forward slashes, IIRC.

**Comment by alemorm** [comment]
Hi everyone, the renewed interest in this issue coupled with the latest Jupyter Open Studio (held today) motivated me to attempt fixing it. I am a complete TypeScript beginner so I won't be fixing it soon but I just want to reach out to others working on it. I was following the leads from @nathancarter and @jasongrout  so I had an idea of where to start. Also, talking to @jasongrout today he suggested fixing this on the back-end, when the terminal gets instantiated, rather than the front-end, with the initial command approach, to avoid dealing with OS compatibility issues. 

I will update you on my progress but feel free to let me know if you have an idea!

**Comment by nathancarter** [comment]
Seems like the git extension @ian-r-rose mentioned actually implements `cd` for the objects in the terminal extension.  Perhaps the DRY thing to do is to move that code into the `ITerminal` class, and then both extensions can just call the same member function as needed.  I realize that this sort of disagrees with @jasongrout's idea to do things on the back end, but doing it in two different ways in two different official extensions seems...   Well, I guess the opposite of DRY is WET (Write Everything Twice?). :)

**Comment by jasongrout** [comment]
I think it's more correct to do it on the backend (where you know what the OS is, and can customize accordingly). But if it works to do it on the front end on all OSs, I think you're right that that is significantly easier.

**Comment by ellisonbg** [comment]
Can we treat this as an interface/implementation pattern and Start with the simpler implementation based on cd, and then improve the implementation over time?

**Comment by moita69** [comment]
I would like to contribute ti this issue as my fisrt issue, during last days I have been diging up this issue. Its look like that the widget receive the CWD but the **@phosphorjs** don't pass forward

**Comment by qntnrbns** [comment]
It seems that the call to `new_named_terminal` from `terminado` in the terminal API in `notebook` doesn't allow us to pass parameters to individual named terminals. So to do it on the server side, we would have to override the `terminal_manager` in the settings and the `TerminalRootHandler` to accept the POST params. Do we think it's worth the effort to do this? And if yes, where would that code belong in the jupyterlab server? 

https://github.com/jupyter/notebook/blob/d145301b5583366fc0c5e938ded80f07a0bc1bbf/notebook/terminal/api_handlers.py#L19-L26

https://github.com/jupyter/terminado/blob/b0b32f3efdde4252466f4e57b98773d9e86951ec/terminado/management.py#L317-L324

**Comment by blink1073** [comment]
Hi @qntnrbns, we are moving towards adopting a new Jupyter server.  I would support that addition there and in terminado:

https://github.com/jupyter/jupyter_server/blob/5476f7cf257a5af18272090115d94e76a82ddd86/jupyter_server/terminal/api_handlers.py#L22

**Comment by itcarroll** [comment]
I really wish I understood how jupyter works and could contribute (where's the absolute beginner guide for contributors, anyway?), but with [jupyter-server/jupyter_server#201](https://github.com/jupyter-server/jupyter_server/pull/201) merged, how do you actually use the feature in jupyter to open a terminal at the file browser. I'm thinking right click in file browser, "open terminal here"
