### ISSUE TITLE
ShortCut key for "Run selected text or current line in console"

### ISSUE THREAD

**Issue by cynthier** [jupyterlab/jupyterlab#13662]
Hi
I found there is no related setting for "Run Selected Text or current Line in Console" in "Keyboard shortcut"  part in jupyterlab 3.5.0, .
I remember this function in previous version, and is it delected in this version now?

**Comment by jweill-aws** [comment]
Found a mention of this command in #10552. I also found #8281, requesting a keyboard shortcut for this command. Closing this issue in favor of 8281. Thank you for your contribution!
