### ISSUE TITLE
Adding cell tags on top of the cells.

### ISSUE THREAD

**Issue by virgilus** [jupyterlab/jupyterlab#13674]
### Problem

I use the cell tag system on almost every cell in my notebooks, it helps me to generate pedagogic content for my students. However I need to select individually each cell to make sure they have the appropriate tags.

### Proposed Solution

On previous Jupyter versions, the tags could be displayed on top of each cell. It seems this can't be possible now. Could you make this feature back please? It could be an option inside the "Notebook Settings" saying "display tags over cells".

(Also adding an option that changes the background color of a cell according to certain tags would be awesome too.)

Thanks! :)

PS : Found a picture of the old feature I want back : ![l495J](https://user-images.githubusercontent.com/29283273/209830386-d6142335-a891-4f72-9ff6-d022ecab1a02.png)

**Comment by krassowski** [comment]
> (Also adding an option that changes the background color of a cell according to certain tags would be awesome too.)

https://github.com/jupyterlab/jupyterlab/issues/8457

**Comment by jweill-aws** [comment]
Have you tried using the [JupyterLab enhanced cell toolbar extension](https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar)? It has options for tagging cells, for example.

**Comment by virgilus** [comment]
Thanks I wasn't aware of this extension, it'd do the job! :)
