### ISSUE TITLE
Debugger invokes `notifyCommandChanged` force-updating commands after tab switch

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13684]
## Description

The debugger extension plugins for notebook, console and file all invoke a full commands update, e.g.:

https://github.com/jupyterlab/jupyterlab/blob/edc294b06fe6607be80094dd590cb9f766ab83ff/packages/debugger-extension/src/index.ts#L138

resulting in a long task preventing fast consecutive tab switch.

## Reproduce

1. Open two notebooks
2. Record profile
3. Switch tabs
4. See a long task invoking React re-render as below:

![Screenshot from 2022-12-29 17-02-45](https://user-images.githubusercontent.com/5832902/209985421-510111d1-0fef-433f-919f-0bdf8d82760c.png)

## Expected behavior

There is no needless updates. Maybe something like;

https://github.com/jupyterlab/jupyterlab/blob/edc294b06fe6607be80094dd590cb9f766ab83ff/packages/toc-extension/src/index.ts#L303-L304

## Context

- JupyterLab version:  4.0.0a31

**Comment by jtpio** [comment]
Thanks @krassowski for opening this.

> There is no needless updates. Maybe something like;

I don't recall exactly why these ` app.commands.notifyCommandChanged();` were needed. Maybe these suggestions can indeed be applied.
