### ISSUE TITLE
UI to enable/disable pre-built extensions

### ISSUE THREAD

**Issue by suganya-sk** [jupyterlab/jupyterlab#13689]
### Problem

Based on my understanding, source extensions can be managed through the extension manager UI, which lists installed/available source extensions and can be used to enable/disable/install these extensions as needed. However, pre-built extensions are managed using the `jupyter labextension` command in CLI and do not have a UI component. This is not very easy to use for a non-tech audience.

### Proposed Solution

Add UI, in / like the existing extension manager to enable/disable pre-built extensions.

### Additional context

I'm trying to disable unused extensions from a global setup so individual users can enable only the extensions they need, for performance issues.

Related discourse thread - https://discourse.jupyter.org/t/jlab-when-are-deferred-extensions-that-define-functionality-triggered-by-ui-interactions-loaded/17133

**Comment by jtpio** [comment]
Thanks @suganya-sk.

This seems to be fixed by https://github.com/jupyterlab/jupyterlab/pull/12866, which will be available in JupyterLab 4.0:

https://user-images.githubusercontent.com/591645/210207668-c191551a-4b40-4c81-86f1-e8a82d60f9b0.mp4

**Comment by suganya-sk** [comment]
Thanks for the quick response here. 

Am I correct in understanding that the PR linked cannot be backported to 3.6.x?

> Backwards-incompatible changes
> Break the api as most features are now in the backend.

**Comment by jtpio** [comment]
That's right.

However it's already possible to use JupyterLab 4.0 pre-release if you would like to: `pip install --pre jupyterlab`

**Comment by suganya-sk** [comment]
Thanks for the confirmation!

Closing this.
