### ISSUE TITLE
Characters between $$ are not displayed corrected. 

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#1368]
For example, when I type the name a function in R, the source code of the function is printed. Sometimes, strange characters like @@1@@ appears. It turns to be that there are $ operations in the R code and characters between 2 $ sign become @@1@@.

**Comment by blink1073** [comment]
Is this in a code cell?  The `$$` delimiters are only expected to work in markdown cells.

**Comment by dclong** [comment]
@blink1073
Yes it's in a code cell. However, `$...$` was not intended to be a Latex inline math equation. `$` is a List operator in R. When there are multiple `$` operators in a code chunk, they are misinterpreted.

**Comment by blink1073** [comment]
Can you give an example?  I have not personally written any R code, so a valid code sample would help me ;).

**Comment by dclong** [comment]
For example, I have a simple function defined as below. 
```
f = function(l) {
    x = l$x
    y = l$y
}
```
When I type `f` it shows the below content. Obviously `$` was misinterpreted.
```
function (l) 
{
    x = l@@0@@y
}
```

**Comment by blink1073** [comment]
Aha, thanks!  The problem is with the output display, not with the input as I had thought.

**Comment by blink1073** [comment]
Dev note: the classic notebook gets this right:

![image](https://cloud.githubusercontent.com/assets/2096628/20926873/59675512-bb84-11e6-9135-a46ada286e4d.png)
