### ISSUE TITLE
Move collaboration features to a separate package

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13726]
### Problem

Once the implementation of RTC through IDrive is done. We can extract every specific RTC UI elements to a separate extension. So RTC is a opt-in through extension installation. And we are able to keep iterating faster on the UI elements.

The elements that need to be in core for RTC are:
- Document model stored in RTC compatible object (= Yjs document)
- Getting user identity and permission (Jupyter Server Identity & Authorization API)

**Comment by jtpio** [comment]
> So RTC is a opt-in through extension installation.

This sounds good. And should help alternative RTC extensions like https://github.com/jupyterlite/jupyterlab-webrtc-docprovider to be used if desired.
