### ISSUE TITLE
How to extract previous output in an R notebook?

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#1372]
Not sure whether this question should ask here or to the IRKernel developers instead. In Python notebook, one can extract the $n^{th}$ output using `_n` or `Out[n]`. How can we do this in an R notebook?

**Comment by blink1073** [comment]
This is up to the kernel author to implement, those magic variables are provided by the Python kernel.

**Comment by ellisonbg** [comment]
Closing for now, feel free to re-open if needed.
