### ISSUE TITLE
Cell toolbar gets broken with undo

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13728]
### Reproduce

1. Create a markdown cell
2. Duplicate it
3. Edit the copy
4. Undo a few times
5. See toolbar is no longer visible and errors show up in console:

```js
index.ts:467 TypeError: Cannot set properties of undefined (setting 'text')
    at m._setValue (jsoneditor.ts:331:19)
    at set source [as source] (jsoneditor.ts:134:10)
    at e.CellMetadataEditorTool._update (notebooktools.ts:672:19)
    at e.CellMetadataEditorTool.onActiveCellChanged (notebooktools.ts:660:12)
    at e.CellMetadataEditorTool.processMessage (notebooktools.ts:348:16)
    at c (index.ts:530:15)
    at Object.e [as sendMessage] (index.ts:220:7)
    at notebooktools.ts:195:7
    at f (iter.ts:227:9)
    at P._onActiveCellChanged (notebooktools.ts:194:5)
```

```js
index.ts:349 TypeError: Cannot read properties of null (reading 'contentChanged')
    at d._removeToolbar (celltoolbartracker.ts:146:11)
    at d._onActiveCellChanged (celltoolbartracker.ts:70:12)
    at u (index.ts:673:12)
    at n.emit (index.ts:594:9)
    at n.emit (index.ts:208:15)
    at set activeCellIndex [as activeCellIndex] (widget.ts:1290:31)
    at oe.onCellInserted (widget.ts:1826:10)
    at oe._insertCell (widget.ts:601:12)
    at widget.ts:506:16
    at f (iter.ts:227:9)
```

![toolbar-breaking](https://user-images.githubusercontent.com/5832902/210979948-3beb8375-fc76-4239-9049-9475568a3e58.gif)

### Context

- Browser: Chrome 108
- JupyterLab version: 3.x

**Comment by krassowski** [comment]
Again, it works fine on 4.x alpha

**Comment by krassowski** [comment]
So this was fixed on master in an unrelated PR by adding a check if `model` is not null:

https://github.com/jupyterlab/jupyterlab/blob/1cda7df0e0005ac51fea4bbb8d68f44f6eb1e216/packages/cell-toolbar/src/celltoolbartracker.ts#L66-L68

But this is on some level wrong because the cell model should never be `null` according to types, but in practice it gets set to null on disposal:

https://github.com/jupyterlab/jupyterlab/blob/282f7ea335428205941567807e1a961f1b6c694f/packages/cells/src/widget.ts#L483-L493

The clean fix would be to check if cell is disposed before removing the toolbar. I am slightly concerned that we may have a memory leak on `Cell._displayChanged` signal as that would not get disconnected properly. We could remove the reference to the signal in `dispose()` which should probably be enough, but may cause the same kind of an issue.

**Comment by bollwyvl** [comment]
Yeah, this would be lovely to fix. It leads to active breakage of some things, such that i've had to disable the toolbar altogether in certain cases. And indeed: having an in-UI setting that allowed that would be lovely if such breakage does occur, or other unwanted behavior.

**Comment by krassowski** [comment]
Another error, with a different error can still happen on 4.0 but with a different error message (https://github.com/jupyterlab/jupyterlab/issues/14380):

```
 Error rendering buttons of the cell toolbar:  TypeError: Cannot read properties of null (reading 'insertWidget')
    at celltoolbartracker.ts:174:40
overrideMethod	@	react_devtools_backend.js:2655
(anonymous)	@	celltoolbartracker.ts:186
Promise.catch (async)		
_addToolbar	@	celltoolbartracker.ts:185
_onActiveCellChanged	@	celltoolbartracker.ts:123
m	@	index.es6.js:543
```

**Comment by krassowski** [comment]
Closing in favour of https://github.com/jupyterlab/jupyterlab/issues/14380
