### ISSUE TITLE
Restore ModelDBFactory in the form of SharedModelFactory

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13724]
## Problem

Restore the ModelDBFactory API to be modified for shared models.

This is gonna be useful to create a `Drive` that use Yjs document of documents (to share a tree of files).

**Comment by hbcarlos** [comment]
We need to restore https://github.com/jupyterlab/jupyterlab/pull/13213

**Comment by hbcarlos** [comment]
Fixed in #13786
