### ISSUE TITLE
Upgrade dependencies from NodeJS 14 to Node 18

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#13720]
## Description

NodeJS 14.x reaches end of life on April 30, 2023. Source: https://github.com/nodejs/release#release-schedule

Node 14 is mentioned in the following places:

https://github.com/jupyterlab/jupyterlab/blob/6d208970f0b950a1c75c0c08960c651b32a3cc0b/.gitpod.yml#L27

https://github.com/jupyterlab/jupyterlab/blob/6d208970f0b950a1c75c0c08960c651b32a3cc0b/readthedocs.yml#L7

https://github.com/jupyterlab/jupyterlab/blob/6d208970f0b950a1c75c0c08960c651b32a3cc0b/binder/environment.yml#L9

## Expected behavior

A currently-supported version of Node, such as 16 or 18, should be used. Prefer Node 18 for maximum remaining life.

**Comment by JasonWeill** [comment]
We could upgrade to Node 16, but 16's end-of-life is 2023-09-11, about 8 months from now.

**Comment by JasonWeill** [comment]
We should backport any fix to the 3.5.x and 3.6.x branches, because these will be used well past 2023-04-30.

**Comment by andrii-i** [comment]
Hey everyone! Was this issue solved by the merged[ PR 174](https://github.com/jupyterlab/maintainer-tools/pull/174). If yes, let's close this issue

CC @JasonWeill

**Comment by jtpio** [comment]
> Was this issue solved by the merged[ PR 174](https://github.com/jupyterlab/maintainer-tools/pull/174)?

Partially, https://github.com/jupyterlab/jupyterlab/pull/13722 is still open. @andrii-i if you would like to review it that would be great, thanks!
