### ISSUE TITLE
blink: Open the preview-markdown  and edit-markdown  tab at the same page

### ISSUE THREAD

**Issue by FoSuCloud** [jupyterlab/jupyterlab#13734]
## Description
Open the preview-markdown  and edit-markdown  tab at the same page

## Reproduce

1、create a markdown file
2、source code:
```
### a
sdsd

a fdsdsd
sdsdsdsadsadasd

sdsd

sdsd
11
sdsdsdasdsad
sdsdsdsdsd
sd
a

sdsdasdsad

### sddsd
    sdsds
    
    
asdas
```
3、As long as you use code syntax, it will cause flicker.
Use the syntax of the following link.
https://github.github.com/gfm/#example-3

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 
max os 12.2
Chrome 108
JupyterLab v3.4.7

1、After editing, the code is executed
marked.marked()
2、debug in highlight
```
        setTimeout(() => {
          highlight(token.text, token.lang, function(err, code) {
            if (err) {
              return done(err);
            }
            if (code != null && code !== token.text) {
              token.text = code;
              token.escaped = true;
            }

            pending--;
            if (pending === 0) {
              done();
            }
          });
        }, 0);
```
3、after setTimeout,the page will blink

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
This may be related to https://github.com/jupyterlab/jupyterlab/issues/13678.
