### ISSUE TITLE
 Cannot override the default rendered viewer for JupyterLab 3

### ISSUE THREAD

**Issue by nthiery** [jupyterlab/jupyterlab#13742]
#11541 very nicely fixed #7776 for JupyterLab 4, enabling in particular to 
[Open linked jupytext .md files as notebooks in Jupyter Lab](https://github.com/mwouts/jupytext/issues/271).
Would it be possible to backport this fix to JupyterLab 3?

Thanks so much in advance!

## Context

#7776 has been a lifesaver for us in Paris-Saclay, as jupytext .md files are heavily used in teaching
contexts. Just for the sake of it, we switched to JupyterLab 4 last septembre. However Jupyter 4
is only a prerelease, and many packages (e.g. nbgrader, ...) are incompatible with it. Using it at
this stage and our scale has proven a maintenance nightmare (literally days spent fighting with mamba
and pip in search for combinations of package versions that are compatible with each other).

cc: @fcollonval, @jasongrout, @mwouts, @parmentelat

**Comment by fcollonval** [comment]
I opened https://github.com/jupyterlab/jupyterlab/issues/13743 that should fix this in 3.6.0

**Comment by fcollonval** [comment]
Closed by #13743

**Comment by nthiery** [comment]
I just tested jupyterlab 3.6.0rc0; and opening linked jupytext .md files as notebooks
works like a charm. Thanks so much for this life saver!
