### ISSUE TITLE
Upgrade json schema version

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13746]
### Problem

It could be interesting to bump the JSON Schema version used from draft04 to some more recent flavor (last proposal is [2020-12](https://json-schema.org/)).

The new version needs to be compatible with:

- JS [ajv](https://www.npmjs.com/package/ajv)
- JS [react-json-schema-form](https://www.npmjs.com/package/@rjsf/validator-ajv8)
- Python [jsonschema](https://pypi.org/project/jsonschema/)

The Python package seems to be the one falling behind in term of standard support.

**Comment by bollwyvl** [comment]
> Python `jsonschema`

Things look mostly fine here: [Draft202012Validator](https://python-jsonschema.readthedocs.io/en/latest/api/jsonschema/validators/#jsonschema.validators.Draft202012Validator), with the README suggesting a key missing useful thing (`$vocabulary`) will be supported, presumably at some point within the `jsonschema@4.*` release cycle.

> JS [react-json-schema-form](https://www.npmjs.com/package/@rjsf/validator-ajv8)

Indeed: I've been waiting with baited breath to get a live [rjsf 5](https://github.com/rjsf-team/react-jsonschema-form/issues/3144#issuecomment-1382404859), which splits out the `ajv` dependency, so it can be upgraded. `ajv` is already a _huge_ dep, so should be moved wholesale to 8, if possible, for lab4.

Getting this hoisted as a shared package would be huge, as well as loading it as lazily as possible, as it is, well, _huge_.

> JS [ajv](https://www.npmjs.com/package/ajv)

Of note: even `ajv@8` _still_ gets flagged for `unsafe-eval`, by default, and there's really no way around it for the kinds of dynamic things jupyterlab does (e.g. translation). When addressing this systematically, it likely makes sense to offer a `IJSONSchema` plugin, such that one _could_ inject a "safe" parser... if it were to exist. It would _definitely_ be slower... even the `rust`-based one says _just go use `ajv`_... and WASM is usually not the _best_ place to go without a sound reason.

**Comment by bollwyvl** [comment]
[rjsf 5 is out](https://github.com/rjsf-team/react-jsonschema-form/releases/tag/v5.0.0) :tada:

**Comment by bollwyvl** [comment]
Buried in updating after 6 months of version drift, the [actual work](https://github.com/deathbeds/jupyterlab-starters/pull/99/commits/49d81509421da1454c1e1420a2df6e9045394392) was not that bad upgrading to rjsf5/ajv8. Once I've done some more work (and gotten a 3.x compatible release out of the stable of downstreams), it should be relatively easy to get a PR together to get lab going. 

I'm working on cutting the file sizes down... but as the lab `ajv` and `rjsf` _aren't_ singletons/exposed, I was paying for it anyway.

However, lowering the bar for extension authors to "ship thoughtful schema, get :candy:" is going to be really good. 

Also: holy mackerel, this looks like an excellent thing:

https://ajv.js.org/guide/typescript.html#type-safe-parsers-and-serializers

There are a lot of places where i do a lot of intermediate processing of schema to get to types, but having the ts _directly consume and validate_ the JSON string off the wire seems really powerful for frequently-used message types.

**Comment by bollwyvl** [comment]
Some notes from the field of #13924:

**Comment by bollwyvl** [comment]
On custom keywords.

- we can't yet use [ajv strict mode](https://ajv.js.org/strict-mode.html)
  - while it is possible to add custom vocabularies...
    - ... we can't even pass _that_, due to use of the `.` character in custom plugin schema keywords
      - i don't know, or really care why 
    - one approach would be to blanket replace `.` with `:` for URN-like constructs, e.g.:
      - `jupyter.lab.internationalization`
      - `jupyter:lab:internationalization`

**Comment by bollwyvl** [comment]
Of note: even if we move the front end to `ajv8`, [`eslint` still uses `ajv6`](https://github.com/eslint/eslint/blob/337f7ed96131d873be7ae6b010739476d0ad15e9/package.json#L63). I don't know what the support window for `ajv6` is.

**Comment by krassowski** [comment]
Closing because we migrated to `draft07` in 4.0.x cycle:
- https://github.com/jupyterlab/jupyterlab/pull/13924 (ajv8 by default uses draft07)
- https://github.com/jupyterlab/jupyterlab_server/pull/423 (explicitly moved backend to draft07 to close the loop)

I believe it would be safer to stay on `draft07` for a while, until support for newer versions stabilises, and because the newer versions have breaking changes we may want to wait until JupyterLab 5.
