### ISSUE TITLE
Pasting in Markdown cells pastes twice.

### ISSUE THREAD

**Issue by yczhangsjtu** [jupyterlab/jupyterlab#13757]
Everything is exactly the same as in this issue.

https://github.com/jupyterlab/jupyterlab/issues/13206#issue-1402906657

It seems that the `replaceSelection` function involved in the original fix has now been completely changed, and the new implementation caused the problem again.

I cannot reopen that issue, so opened a new one.

Version: jupyterlab 4.0.0-alpha.32

**Comment by andrii-i** [comment]
Hi @yczhangsjtu, @JasonWeill! Original issue #13206 was reopened last week and accordingly to [this](https://github.com/jupyterlab/jupyterlab/issues/13206#issuecomment-1387328395) comment there is work in progress to fix it. Closing this as a duplicate.
- #13206
