### ISSUE TITLE
Allow python config to be passed into lab extensions

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1375]
JupyterHub and Flexx have already expressed need to add items to the `lab.html` `jupyter-config-data`.  We should add an optional `_jupyter_labextension_config` function that returns a dictionary of values to add to that data.

cc @almarklein @danielballan @minrk

**Comment by minrk** [comment]
That would be super helpful, thanks @blink1073!

**Comment by almarklein** [comment]
This function will get called for each page load, right?

**Comment by blink1073** [comment]
Yep, that sounds good.

**Comment by rsinha25** [comment]
How can we do this in the latest labextensions?

**Comment by blink1073** [comment]
No, we decided that front end and back end extensions should remain separate.  An extension that wants to affect the backend must use a server extension.  They can affect the front end using `page_config`, an example of which is [here](https://github.com/jupyterlab/jupyterlab/blob/fea2cf52ea980712af61e79262c35017e59bb712/jupyterlab/labhubapp.py#L13).
