### ISSUE TITLE
Running jupyter lab behind a reverse proxy with rewrite rule

### ISSUE THREAD

**Issue by chiragjn** [jupyterlab/jupyterlab#13764]
### Problem

I have jupyter lab running via docker (` jupyter/minimal-notebook:python-3.9.13`) with default settings and I am accessing it via a reverse proxy on `https://<host>/jupyterlab/`. This reverse proxy is out of my control and it works via a rewrite rule i.e. it maps 
`https://<host>/jupyterlab/...` to `http://<k8s-jupyter-service>:8888/...`.

As such I would want the jupyterlab frontend (server APIs are working fine) to understand that all URLs will be relative to `/jupyterlab/` instead of `/`

I already understand that setting `--NotebookApp.base_url='/jupyterlab/'` along with a simple proxy pass rule instead of a rewrite rule can get everything working but the reverse proxy rules are not in my control

I tried setting `--NotebookApp.base_url=''` to get relative URLs in the UI but the documentation states

```
NotebookApp.base_urlUnicode
Default: '/'
The base URL for the notebook server.
Leading and trailing slashes can be omitted, and will automatically be added.
```

So `--NotebookApp.base_url=''` is equivalent to `--NotebookApp.base_url='/'` which is the default.

### Proposed Solution

1. Not adding leading/trailing slash to `--NotebookApp.base_url` when value is explicitly set to empty string. However, I am not sure what else can break with such relative URLs
2. Some base_url flag that only affects rendered URLs in frontend

### Additional context

- [Fastapi has a concept of `root_path`](https://fastapi.tiangolo.com/advanced/behind-a-proxy/) which only affects the rendered URLs and not the backend API locations

**Comment by JasonWeill** [comment]
Hey @chiragjn , thanks for filing this issue!

Have you taken a look at [Jupyter Enterprise Gateway](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/index.html) to see if it offers the options that you need?

This might be an issue better suited for [Jupyter Server](https://github.com/jupyter-server/jupyter-scheduler/issues), which interprets URLs and is included with JupyterLab. If enterprise gateway doesn't suit your needs, you might want to check the server issues list and open a new issue in Jupyter Server if none already exists.

**Comment by JasonWeill** [comment]
Hey @chiragjn — can you please follow up on the questions from last week? Thanks!

**Comment by chiragjn** [comment]
> Have you taken a look at [Jupyter Enterprise Gateway](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/index.html) to see if it offers the options that you need?
Hello, I haven't had a chance to take a look at it yet, I'll check it out sometime next week

> This might be an issue better suited for [Jupyter Server](https://github.com/jupyter-server/jupyter-scheduler/issues), which interprets URLs and is included with JupyterLab.

In my opinion, it is not about interpreting on the server side but rather what value of `base_url` is passed for `href` in the UI templates
https://github.com/search?q=repo%3Ajupyterlab%2Fjupyterlab%20%22base_url%22&type=code

because this cannot be set to empty string `''`, I can't make it work with a proxy doing re-writes instead of proxy pass

**Comment by bollwyvl** [comment]
Yep, it definitely needs a `/`.

As the owner of the docker container, is there any way you can control the base URL dynamically?

Some loci are:
- overload html templates
- overload the `page_config`
- customize the application itself with a custom launcher

It's also worth looking into launching `jupyter_server` (configured with e.g. `ServerApp`) instead of `notebook`'s `NotebookApp`

**Comment by JasonWeill** [comment]
@chiragjn Any update after the comments that @bollwyvl left on this issue last week?

**Comment by JasonWeill** [comment]
Closing this issue because of no new comments in the thread in a couple of weeks. @chiragjn if you have any additional questions, please reopen this issue or open a new one. Thanks!
