### ISSUE TITLE
Several `is an invalid additional property` errors in the Settings Editor UI

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13762]
## Description

Opening the Settings Editor UI and searching for some settings gives the following `is an invalid additional property` errors.

## Reproduce

With JupyterLab 4.0.0a32 on Binder: https://gist.github.com/jtpio/4e9a3d435d7c3950dc4150c10abbb1d7

For example when searching for "startMode":

![image](https://user-images.githubusercontent.com/591645/212180125-06c9dff5-ca64-4b43-987a-7f592a91af16.png)

## Expected behavior

It should be possible to edit the fields via the UI settings editor.

**Comment by krassowski** [comment]
I think this is a duplicate of #13651

**Comment by jtpio** [comment]
Ah thanks @krassowski, closing in favor of https://github.com/jupyterlab/jupyterlab/issues/13651 then.
