### ISSUE TITLE
File browser: add setting to show the full path

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13770]
### Problem

Notebook 7 reuses the same file browser widget as in JupyterLab. However since the file browsers takes the full page in `/tree` there would be plenty of space to show the full folder path:

![image](https://user-images.githubusercontent.com/46796385/123949145-8852f700-d9a2-11eb-80d0-1968fb66dee0.png)

This is less of an issue in JupyterLab because the file browser is in the `left` area and usually does not take that much space.

### Proposed Solution

Add a file browser setting to allow displaying the full path. Maybe make the widget scrollable (horizontally) in case the path is very long. Or provide a setting to set the max number of directories to show.

A more advanced logic would determine when to put an ellipsis automatically based on the current width.

### Additional context

This was originally reported in https://github.com/jupyter/notebook/issues/6404

**Comment by jtpio** [comment]
Digging a little bit into the code, there seems to be some references to a `MAX_DIRECTORIES` here:

https://github.com/jupyterlab/jupyterlab/blob/1cda7df0e0005ac51fea4bbb8d68f44f6eb1e216/packages/filebrowser/src/crumbs.ts#L429-L430

There is also a hardcoded `2` here which might refer to the same max number of directories?

https://github.com/jupyterlab/jupyterlab/blob/1cda7df0e0005ac51fea4bbb8d68f44f6eb1e216/packages/filebrowser/src/crumbs.ts#L374

**Comment by jtpio** [comment]
Adding to `4.0` as it would be nice to have such option that could be used downstream in Notebook 7, and also by regular JupyterLab users.

**Comment by jtpio** [comment]
That would be great, thanks @dharmaquark!

**Comment by zachwaldron4** [comment]
Hello, 
This appears to be an issue still be an issue.  If the feature to allow showing the full path is implemented, I can't seem to find it anywhere in the settings or view menus.

**Comment by jtpio** [comment]
Thanks @zachwaldron4 for reporting here.

Indeed, when the Settings Editor UI does not seem to be showing anything when searching for `showFullPath`:

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/594bc041-e91f-40e4-885d-98dcbfb0a26b)

Although the "Advanced Settings Editor" does:

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/4f1aad87-d098-40bd-a168-be02c9bf1b44)

This was when testing with the latest `4.2.0rc0`, but it looks like a real issue. We should probably open a new issue if one does not exist already.

**Comment by krassowski** [comment]
There is some bug in the filtering logic, If you search for "show full path" (with spaces) instead it shows up nicely:

![Screenshot from 2024-05-02 19-09-46](https://github.com/jupyterlab/jupyterlab/assets/5832902/9ac7154e-02d5-4b26-9f15-0ed8b10691bb)

 There might be an issue for this already
