### ISSUE TITLE
Improving `stdin` line history: option to split line history per notebook

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#13798]
### Problem

Currently, the line history support for `stdin` input boxes (which pop up during eg an ipdb debugging session) is global for a single instance of jupyterlab. This is personally how I prefer line history to work, but I've gotten some feedback that it can be confusing for this history to not be split up for different notebooks.

### Proposed Solution

Add an option that will segregate the `stdin` line history per notebook. This might be a little tricky to do, but I think it can be done relatively easily by making a few modifications to the data structure under which `stdin` line history is currently stored.

**Comment by krassowski** [comment]
Triage meeting notes: this may be good to be optional since some users may be used to status quo. Also, an option to have this per-environment could be nice.
