### ISSUE TITLE
Running kernels can list the same kernel twice

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#13791]
Because we use the `api/sessions` REST endpoints to populate the "Kernels" section of the running items sidebar, we can show the same kernel more than once if it has both a notebook and a console connected to it. Since the label on that section says "Kernels", this is confusing to end users.

Additionally, we have no way of showing kernels that do not have a JupyterLab session context even if they are available and running on the server.

**Comment by krassowski** [comment]
How does this one relate to https://github.com/jupyterlab/jupyterlab/issues/13779? At a glance both seem to discuss the same problems?

**Comment by afshin** [comment]
You're right. It's a duplicate. I didn't realize @SylvainCorlay had posted the issue.

**Comment by afshin** [comment]
Duplicate of #13779
