### ISSUE TITLE
Improving `stdin` line history: forward and reverse search

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#13797]
### Problem

Currently, jlab support line history for `stdin` input boxes (which pop up during eg an `ipdb` debugging session). Said line history can be paged through one-by-one with the up/down arrow keys. However, there's currently no way to search  the history.

### Proposed Solution

Implement forward and reverse history search for `stdin` elements, a la bash/readline

**Comment by krassowski** [comment]
This is a follow up to https://github.com/jupyterlab/jupyterlab/issues/7006

**Comment by krassowski** [comment]
Closing as implemented in https://github.com/jupyterlab/jupyterlab/pull/13937.
