### ISSUE TITLE
Undefined CSS variables

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13799]
## Description

We have a few undefined CSS variables.

## Reproduce

Use https://github.com/sonatype-nexus-community/undefined-css-variable-checker (https://chrome.google.com/webstore/detail/css-undefined-variable-ch/endbpplgeglmgihkpiapmaimegpkhhcn) on JupyterLab, see report:

| variable | stylesheet | selector |
|--|---|--|
| --jp-inverse-layout2 |   | .jp-terminal-icon-background-color[fill]  |
| --jp-inverse-layout2 |   | .jp-terminal-icon-background-color[fill] |
| --jp-inverse-layout3 |   | .jp-text-editor-icon-color[fill] |
| --jp-inverse-layout3 |   | .jp-text-editor-icon-color[fill] |
| --jp-inverse-layout3 |   | .jp-text-editor-icon-color[fill] |
| --jp-inverse-layout3 |   | .jp-text-editor-icon-color[fill] |
| --jp-content-header-font-weight |   | .jp-arrayFieldWrapper legend |
| --jp-content-header-font-weight |   | .jp-arrayFieldWrapper legend |
| --jp-content-header-font-weight |   | .jp-arrayFieldWrapper legend |
| --jp-content-header-font-weight |   | .jp-arrayFieldWrapper legend |
| --jp-content-header-font-weight |   | .jp-arrayFieldWrapper legend |
| --jp-content-header-font-weight |   | .jp-arrayFieldWrapper legend |
| --jp-content-header-font-weight |   | .jp-arrayFieldWrapper legend |
| --jp-font-color1 |   | .jp-DocumentSearch-replace-button |

I am going to fix the last one in #13778.

CC @HaudinFlorence in case if that is relevant.

## Expected behavior

No undefined CSS variables

## Context

- JupyterLab version: 4.0.0a32 with

**Comment by fcollonval** [comment]
Thanks for opening this @krassowski 

It will be good to add a test in the CI; probably through playwright by dynamically injecting [@sonatype/undefined-css-variable-checker](https://www.npmjs.com/package/@sonatype/undefined-css-variable-checker) library.
