### ISSUE TITLE
Prevent Data Loss

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#1381]
Does anyone know how often is a JupyterLab notebook auto saved? I'm worried about data loss when the network connection is lost. This is a serious issue on unstable networks. It actually happened to me once when I tried IBM Data Science Experience (I think it's based on Jupyter) and I lost almost half of my work. 

1. Is a JupyterLab notebook auto saved every few seconds?
2. When I run a cell, is the notebook autosaved?

**Comment by blink1073** [comment]
The notebook (and all documents) are auto-saved every 2 minutes by default.   Auto-saving is not tied to running a cell.  We plan to make the auto-save-to-disk interval configurable, and are moving toward a model where the document model lives entirely on the server, meaning that if your browser crashed at any time you would be able to pick up where you left off.

**Comment by ellisonbg** [comment]
Closing for now, feel free to re-open if needed.
