### ISSUE TITLE
 Contextual help does not work on JupyterLab 4.0.0a32

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13822]
## Description

Contextual help does not work on JupyterLab 4.0.0a32

![image](https://user-images.githubusercontent.com/8435071/213467593-16c761f5-6ca1-45ed-baec-7cdbdd1c6175.png)

## Reproduce

1. Open a notebook
2. Through the context menu, open the contextual help
3. Type code in a cell that call a function. You normally should see some help - but it does not work.

## Expected behavior

Contextual help works

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 4.0.0a32

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by fcollonval** [comment]
It works some times. I think it has to do with the editor being not yet rendered since the introduction of the windowed notebook at lines:

https://github.com/jupyterlab/jupyterlab/blob/834680b92aae77222408ea5d90df050816d1ecf9/packages/inspector-extension/src/index.ts#L269-L275

We should probably wait for the cell to be ready.

**Comment by JasonWeill** [comment]
Still seeing this on tip of `master` (4.0.0a35)
