### ISSUE TITLE
Show in Table of Contents where error occurred

### ISSUE THREAD

**Issue by astrofrog** [jupyterlab/jupyterlab#13826]
### Problem

When I run a very long notebook in Jupyter lab it's nice to have the visual representation in the table of contents of which section is being run:

![Screenshot from 2023-01-20 09-58-24](https://user-images.githubusercontent.com/314716/213668219-cf338d7e-adea-4d93-a912-3c41a03e418c.png)

However if I am not looking at the table of contents and an error occurs, all the indicators disappear and I have to scroll through the whole notebook to find where it failed.

### Proposed Solution

If an error occurs, an indicator such as :warning: or :exclamation:  could be shown next to the section where the empty/filled circles were shown before.

**Comment by krassowski** [comment]
Related issues:
- https://github.com/jupyterlab/jupyterlab/issues/9786
- https://github.com/jupyterlab/jupyterlab/issues/5790
- https://github.com/jupyterlab/jupyterlab/issues/8714

**Comment by fcollonval** [comment]
Closing as #14784 brings that feature
