### ISSUE TITLE
Multiple jupyter lab sessions binding the same port on linux

### ISSUE THREAD

**Issue by rundel** [jupyterlab/jupyterlab#13827]
## Description

When launching two jupyter lab sessions on the same linux machine both will bind to the same port and only the first session will be accessible. This occurs when both sessions are launched by the same user as well as when sessions are launched by different users (including root).

When using the same procedure on a MacOS machine when the 2nd session is launched it will report the default port is in use (e.g. `8888`) and bind an incremented port (e.g. `8889`).

## Reproduce

1. Launch jupyter lab using `jupyter lab . --ip=0.0.0.0`
2. Connect to the provided URL of this 1st session
3. In a separate working directory launch a second session using `jupyter lab . --ip=0.0.0.0`
4. Connect to the provided URL of this 2nd session
5. Both URLs will result in connection to the 1st session and not the 2nd (as seen by the working directory and console logging).

This behavior has been reproduced using docker containers based on Ubuntu 22.04 and Fedora 36 (as root) and on a Fedora 36 test server using user accounts.

## Expected behavior

When launching the 2nd session it should detect that the chosen or default port is in use and bind to an alternative port.

## Context

- Operating System and version: Fedora 36
- Browser and version: Chrome 109.0.5414.87
- JupyterLab version: 3.5.2

<details><summary>Troubleshoot Output</summary>
<pre>
# jupyter troubleshoot
$PATH:
	/root/.local/bin
	/root/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/usr/local/bin
	/usr/lib64/python310.zip
	/usr/lib64/python3.10
	/usr/lib64/python3.10/lib-dynload
	/usr/local/lib64/python3.10/site-packages
	/usr/local/lib/python3.10/site-packages
	/usr/lib64/python3.10/site-packages
	/usr/lib/python3.10/site-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.10.9 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]

platform.platform():
	Linux-6.0.18-200.fc36.x86_64-x86_64-with-glibc2.35

pip list:
	Package                  Version
	------------------------ -----------
	anyio                    3.6.2
	argon2-cffi              21.3.0
	argon2-cffi-bindings     21.2.0
	arrow                    1.2.3
	asttokens                2.2.1
	attrs                    22.2.0
	Babel                    2.11.0
	backcall                 0.2.0
	beautifulsoup4           4.11.1
	bleach                   5.0.1
	certifi                  2022.12.7
	cffi                     1.15.1
	charset-normalizer       3.0.1
	comm                     0.1.2
	debugpy                  1.6.5
	decorator                5.1.1
	defusedxml               0.7.1
	entrypoints              0.4
	executing                1.2.0
	fastjsonschema           2.16.2
	fqdn                     1.5.1
	gpg                      1.17.0
	idna                     3.4
	ipykernel                6.20.2
	ipython                  8.8.0
	ipython-genutils         0.2.0
	isoduration              20.11.0
	jedi                     0.18.2
	Jinja2                   3.1.2
	json5                    0.9.11
	jsonpointer              2.3
	jsonschema               4.17.3
	jupyter_client           7.4.9
	jupyter_core             5.1.3
	jupyter-events           0.6.3
	jupyter_server           2.1.0
	jupyter_server_terminals 0.4.4
	jupyterlab               3.5.2
	jupyterlab-pygments      0.2.2
	jupyterlab_server        2.19.0
	libcomps                 0.1.18
	MarkupSafe               2.1.2
	matplotlib-inline        0.1.6
	mistune                  2.0.4
	nbclassic                0.4.8
	nbclient                 0.7.2
	nbconvert                7.2.8
	nbformat                 5.7.3
	nest-asyncio             1.5.6
	notebook                 6.5.2
	notebook_shim            0.2.2
	packaging                23.0
	pandocfilters            1.5.0
	parso                    0.8.3
	pexpect                  4.8.0
	pickleshare              0.7.5
	pip                      21.3.1
	platformdirs             2.6.2
	prometheus-client        0.15.0
	prompt-toolkit           3.0.36
	psutil                   5.9.4
	ptyprocess               0.7.0
	pure-eval                0.2.2
	pycparser                2.21
	Pygments                 2.14.0
	pyrsistent               0.19.3
	python-dateutil          2.8.2
	python-json-logger       2.0.4
	pytz                     2022.7.1
	PyYAML                   6.0
	pyzmq                    25.0.0
	requests                 2.28.2
	rfc3339-validator        0.1.4
	rfc3986-validator        0.1.1
	rpm                      4.17.1
	Send2Trash               1.8.0
	setuptools               59.6.0
	six                      1.16.0
	sniffio                  1.3.0
	soupsieve                2.3.2.post1
	stack-data               0.6.2
	terminado                0.17.1
	tinycss2                 1.2.1
	tomli                    2.0.1
	tornado                  6.2
	traitlets                5.8.1
	uri-template             1.2.0
	urllib3                  1.26.14
	wcwidth                  0.2.6
	webcolors                1.12
	webencodings             0.5.1
	websocket-client         1.4.2
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
# jupyter lab . --debug --allow-root
[D 2023-01-20 17:51:23.041 ServerApp] Searching ['/root/.jupyter', '/root/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2023-01-20 17:51:23.041 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2023-01-20 17:51:23.041 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2023-01-20 17:51:23.041 ServerApp] Looking for jupyter_config in /usr/etc/jupyter
[D 2023-01-20 17:51:23.041 ServerApp] Looking for jupyter_config in /root/.local/etc/jupyter
[D 2023-01-20 17:51:23.041 ServerApp] Looking for jupyter_config in /root/.jupyter
[D 2023-01-20 17:51:23.042 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2023-01-20 17:51:23.042 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2023-01-20 17:51:23.042 ServerApp] Looking for jupyter_server_config in /usr/etc/jupyter
[D 2023-01-20 17:51:23.042 ServerApp] Looking for jupyter_server_config in /root/.local/etc/jupyter
[D 2023-01-20 17:51:23.042 ServerApp] Looking for jupyter_server_config in /root/.jupyter
[D 2023-01-20 17:51:23.045 ServerApp] Paths used for configuration of jupyter_server_config:
    	/etc/jupyter/jupyter_server_config.json
[D 2023-01-20 17:51:23.045 ServerApp] Paths used for configuration of jupyter_server_config:
    	/usr/local/etc/jupyter/jupyter_server_config.d/jupyter_server_terminals.json
    	/usr/local/etc/jupyter/jupyter_server_config.d/jupyterlab.json
    	/usr/local/etc/jupyter/jupyter_server_config.d/nbclassic.json
    	/usr/local/etc/jupyter/jupyter_server_config.d/notebook_shim.json
    	/usr/local/etc/jupyter/jupyter_server_config.json
[D 2023-01-20 17:51:23.045 ServerApp] Paths used for configuration of jupyter_server_config:
    	/usr/etc/jupyter/jupyter_server_config.json
[D 2023-01-20 17:51:23.045 ServerApp] Paths used for configuration of jupyter_server_config:
    	/root/.local/etc/jupyter/jupyter_server_config.json
[D 2023-01-20 17:51:23.046 ServerApp] Paths used for configuration of jupyter_server_config:
    	/root/.jupyter/jupyter_server_config.json
[D 2023-01-20 17:51:23.057 TerminalsExtensionApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'allow_root': True, 'root_dir': '/', 'jpserver_extensions': <LazyConfigValue {'update': {'jupyter_server_terminals': True, 'nbclassic': True, 'notebook_shim': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2023-01-20 17:51:23.058 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'allow_root': True, 'root_dir': '/', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_terminals': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-01-20 17:51:23.059 ServerApp] jupyter_server_terminals | extension was successfully linked.
[D 2023-01-20 17:51:23.063 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'allow_root': True, 'root_dir': '/', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_terminals': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-01-20 17:51:23.064 ServerApp] jupyterlab | extension was successfully linked.
[D 2023-01-20 17:51:23.067 NotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'allow_root': True, 'root_dir': '/', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_terminals': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-01-20 17:51:23.068 ServerApp] nbclassic | extension was successfully linked.
[D 2023-01-20 17:51:23.232 ServerApp] Paths used for configuration of jupyter_notebook_config:
    	/root/.jupyter/jupyter_notebook_config.json
[D 2023-01-20 17:51:23.232 ServerApp] Paths used for configuration of jupyter_notebook_config:
    	/etc/jupyter/jupyter_notebook_config.json
[D 2023-01-20 17:51:23.232 ServerApp] Paths used for configuration of jupyter_notebook_config:
    	/usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2023-01-20 17:51:23.233 ServerApp] Paths used for configuration of jupyter_notebook_config:
    	/usr/etc/jupyter/jupyter_notebook_config.json
[D 2023-01-20 17:51:23.233 ServerApp] Paths used for configuration of jupyter_notebook_config:
    	/root/.local/etc/jupyter/jupyter_notebook_config.json
[D 2023-01-20 17:51:23.233 ServerApp] Paths used for configuration of jupyter_notebook_config:
    	/root/.jupyter/jupyter_notebook_config.json
[I 2023-01-20 17:51:23.233 ServerApp] notebook_shim | extension was successfully linked.
[D 2023-01-20 17:51:23.234 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'allow_root': True, 'root_dir': '/', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_server_terminals': True, 'nbclassic': True, 'notebook_shim': True}>}}
[I 2023-01-20 17:51:23.250 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-01-20 17:51:23.251 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-01-20 17:51:23.252 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.10/site-packages/jupyterlab
[I 2023-01-20 17:51:23.252 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2023-01-20 17:51:23.254 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-01-20 17:51:23.257 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-01-20 17:51:23.257 ServerApp] Serving notebooks from local directory: /
[I 2023-01-20 17:51:23.257 ServerApp] Jupyter Server 2.1.0 is running at:
[I 2023-01-20 17:51:23.257 ServerApp] http://localhost:8888/lab?token=4914bf5299c499e3bb2dee33b93c6dc0081a54d101a74fe4
[I 2023-01-20 17:51:23.257 ServerApp]  or http://127.0.0.1:8888/lab?token=4914bf5299c499e3bb2dee33b93c6dc0081a54d101a74fe4
[I 2023-01-20 17:51:23.257 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2023-01-20 17:51:23.261 ServerApp] No web browser found: could not locate runnable browser.
[C 2023-01-20 17:51:23.261 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-92-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=4914bf5299c499e3bb2dee33b93c6dc0081a54d101a74fe4
     or http://127.0.0.1:8888/lab?token=4914bf5299c499e3bb2dee33b93c6dc0081a54d101a74fe4
</pre>
</details>

**Comment by krassowski** [comment]
I believe I saw the same behaviour. It seems that there are issues with port handling in the recent `jupyter-server` 2.0+. There is for example this issue: https://github.com/jupyter-server/jupyter_server/issues/1170 - I am not sure if this is a duplicate or not. As I cannot transfer this issue to [jupyter-server](https://github.com/jupyter-server/jupyter_server) where the relevant code resides (there is no way to transfer issues between organisations) would you mind opening a bug report over there (or adding a comment with your observations to the one I linked if you consider them to be the same issue)?

**Comment by rundel** [comment]
The linked issue sounds like it might be something related but the symptoms sound different - after a bit more testing it is looking like our particular issue may be specific to a couple of our servers and not a more general issue. I was not able to replicate the behavior on an independent VM and docker tests mentioned above were on the same machines with the issue so they may have inherited whatever the broken network config was that was allowing port reuse.

On the affected machines I was able to duplicate the problematic behavior with just a basic socket + bind:

```python
import socket

s1 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s1.bind(("0.0.0.0", 8888))

s2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s2.bind(("0.0.0.0", 8888))
```

does not throw a `Address already in use` error on the affected machines while it works correctly (throws an error) elsewhere. I will close this issue for know until I can track down what is causing this on these particular machines.

**Comment by rundel** [comment]
Turns out our specific issue was due to a kernel bug (see https://utcc.utoronto.ca/~cks/space/blog/linux/KernelBindBugIn6016) and updating the Fedora kernel was able to fix things.
