### ISSUE TITLE
[IStateDB] Issues with multiple JLabs for the same origin

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#1383]
`LocalStorage` is unique per an origin (host + port). In our case there are several JLabs deployed for the very same origin. It leads to errors when one switch between them, since it tries to reopen widgets for inexistent paths. It will be nice if:
- `file-operations:open` command checks whether a path exists before trying to open it;
- `IStateDB` append a prefix to keys to distinguish own values from other.

**Comment by blink1073** [comment]
The first is already in master: https://github.com/jupyterlab/jupyterlab/blob/f798de0145ded21764e2fecf7099611e224bb010/src/filebrowser/plugin.ts#L257

**Comment by akosyakov** [comment]
@blink1073 you are right, sorry, somehow i managed to get 404 error in the console from the content service. But now it looks good.

**Comment by afshin** [comment]
Thanks for the issue, I've been thinking about this a lot as well. There are multiple reasons why we'll need to prefix the state database. It's part of the ongoing state restoration work work, so I'll keep track of it in this issue when it's updated.

**Comment by afshin** [comment]
@akosyakov This issue is resolved via: https://github.com/jupyterlab/jupyterlab/issues/1441

You can now create a state database with its own namespace.

**Comment by afshin** [comment]
Sorry, I had the wrong link for the PR, so your email will have an incorrect link. This is the PR that resolves the issue: https://github.com/jupyterlab/jupyterlab/pull/1428
