### ISSUE TITLE
RTC is broken in 4.0.0a32

### ISSUE THREAD

**Issue by trungleduc** [jupyterlab/jupyterlab#13853]
## Description

RTC does not work in `4.0.0a32`

## Reproduce

- Install JupyterLab in a new env.
```bash
mamba create -n test python=3.10 -y
mamba activate test
pip install jupyterlab==4.0.0a32
```
- Start JupyterLab in RTC mode and create a new notebook

![rtc](https://user-images.githubusercontent.com/4451292/214571799-09dc2fd8-360d-4718-933b-cc0b4ebba1f6.png)

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
sys.executable:
        /home/trungle/mambaforge/envs/test/bin/python3.10

sys.version:
        3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]

platform.platform():
        Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

which -a jupyter:
        /home/trungle/mambaforge/envs/test/bin/jupyter

pip list:
        Package                  Version
        ------------------------ -----------
        aiofiles                 22.1.0
        aiosqlite                0.18.0
        anyio                    3.6.2
        argon2-cffi              21.3.0
        argon2-cffi-bindings     21.2.0
        arrow                    1.2.3
        asttokens                2.2.1
        async-lru                1.0.3
        attrs                    22.2.0
        Babel                    2.11.0
        backcall                 0.2.0
        beautifulsoup4           4.11.1
        bleach                   6.0.0
        certifi                  2022.12.7
        cffi                     1.15.1
        charset-normalizer       3.0.1
        comm                     0.1.2
        debugpy                  1.6.6
        decorator                5.1.1
        defusedxml               0.7.1
        entrypoints              0.4
        executing                1.2.0
        fastjsonschema           2.16.2
        fqdn                     1.5.1
        idna                     3.4
        ipykernel                6.20.2
        ipython                  8.8.0
        isoduration              20.11.0
        jedi                     0.18.2
        Jinja2                   3.1.2
        json5                    0.9.11
        jsonpointer              2.3
        jsonschema               4.17.3
        jupyter_client           7.4.9
        jupyter_core             5.1.5
        jupyter-events           0.5.0
        jupyter-lsp              1.5.1
        jupyter_server           2.1.0
        jupyter_server_fileid    0.6.0
        jupyter_server_terminals 0.4.4
        jupyter_server_ydoc      0.6.1
        jupyter-ydoc             0.3.0
        jupyterlab               4.0.0a32
        jupyterlab-pygments      0.2.2
        jupyterlab_server        2.19.0
        MarkupSafe               2.1.2
        matplotlib-inline        0.1.6
        mistune                  2.0.4
        nbclient                 0.7.2
        nbconvert                7.2.9
        nbformat                 5.7.3
        nest-asyncio             1.5.6
        notebook_shim            0.2.2
        packaging                23.0
        pandocfilters            1.5.0
        parso                    0.8.3
        pexpect                  4.8.0
        pickleshare              0.7.5
        pip                      22.3.1
        platformdirs             2.6.2
        prometheus-client        0.16.0
        prompt-toolkit           3.0.36
        psutil                   5.9.4
        ptyprocess               0.7.0
        pure-eval                0.2.2
        pycparser                2.21
        Pygments                 2.14.0
        pyrsistent               0.19.3
        python-dateutil          2.8.2
        python-json-logger       2.0.4
        pytz                     2022.7.1
        PyYAML                   6.0
        pyzmq                    25.0.0
        requests                 2.28.2
        rfc3339-validator        0.1.4
        rfc3986-validator        0.1.1
        Send2Trash               1.8.0
        setuptools               66.1.1
        six                      1.16.0
        sniffio                  1.3.0
        soupsieve                2.3.2.post1
        stack-data               0.6.2
        terminado                0.17.1
        tinycss2                 1.2.1
        tomli                    2.0.1
        tornado                  6.2
        traitlets                5.8.1
        uri-template             1.2.0
        urllib3                  1.26.14
        wcwidth                  0.2.6
        webcolors                1.12
        webencodings             0.5.1
        websocket-client         1.4.2
        wheel                    0.38.4
        y-py                     0.5.5
        ypy-websocket            0.8.2

conda list:
        # packages in environment at /home/trungle/mambaforge/envs/test:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       2_gnu    conda-forge
        aiofiles                  22.1.0                   pypi_0    pypi
        aiosqlite                 0.18.0                   pypi_0    pypi
        anyio                     3.6.2                    pypi_0    pypi
        argon2-cffi               21.3.0                   pypi_0    pypi
        argon2-cffi-bindings      21.2.0                   pypi_0    pypi
        arrow                     1.2.3                    pypi_0    pypi
        asttokens                 2.2.1                    pypi_0    pypi
        async-lru                 1.0.3                    pypi_0    pypi
        attrs                     22.2.0                   pypi_0    pypi
        babel                     2.11.0                   pypi_0    pypi
        backcall                  0.2.0                    pypi_0    pypi
        beautifulsoup4            4.11.1                   pypi_0    pypi
        bleach                    6.0.0                    pypi_0    pypi
        bzip2                     1.0.8                h7f98852_4    conda-forge
        ca-certificates           2022.12.7            ha878542_0    conda-forge
        certifi                   2022.12.7                pypi_0    pypi
        cffi                      1.15.1                   pypi_0    pypi
        charset-normalizer        3.0.1                    pypi_0    pypi
        comm                      0.1.2                    pypi_0    pypi
        debugpy                   1.6.6                    pypi_0    pypi
        decorator                 5.1.1                    pypi_0    pypi
        defusedxml                0.7.1                    pypi_0    pypi
        entrypoints               0.4                      pypi_0    pypi
        executing                 1.2.0                    pypi_0    pypi
        fastjsonschema            2.16.2                   pypi_0    pypi
        fqdn                      1.5.1                    pypi_0    pypi
        idna                      3.4                      pypi_0    pypi
        ipykernel                 6.20.2                   pypi_0    pypi
        ipython                   8.8.0                    pypi_0    pypi
        isoduration               20.11.0                  pypi_0    pypi
        jedi                      0.18.2                   pypi_0    pypi
        jinja2                    3.1.2                    pypi_0    pypi
        json5                     0.9.11                   pypi_0    pypi
        jsonpointer               2.3                      pypi_0    pypi
        jsonschema                4.17.3                   pypi_0    pypi
        jupyter-client            7.4.9                    pypi_0    pypi
        jupyter-core              5.1.5                    pypi_0    pypi
        jupyter-events            0.5.0                    pypi_0    pypi
        jupyter-lsp               1.5.1                    pypi_0    pypi
        jupyter-server            2.1.0                    pypi_0    pypi
        jupyter-server-fileid     0.6.0                    pypi_0    pypi
        jupyter-server-terminals  0.4.4                    pypi_0    pypi
        jupyter-server-ydoc       0.6.1                    pypi_0    pypi
        jupyter-ydoc              0.3.0                    pypi_0    pypi
        jupyterlab                4.0.0a32                 pypi_0    pypi
        jupyterlab-pygments       0.2.2                    pypi_0    pypi
        jupyterlab-server         2.19.0                   pypi_0    pypi
        ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
        libffi                    3.4.2                h7f98852_5    conda-forge
        libgcc-ng                 12.2.0              h65d4601_19    conda-forge
        libgomp                   12.2.0              h65d4601_19    conda-forge
        libnsl                    2.0.0                h7f98852_0    conda-forge
        libsqlite                 3.40.0               h753d276_0    conda-forge
        libuuid                   2.32.1            h7f98852_1000    conda-forge
        libzlib                   1.2.13               h166bdaf_4    conda-forge
        markupsafe                2.1.2                    pypi_0    pypi
        matplotlib-inline         0.1.6                    pypi_0    pypi
        mistune                   2.0.4                    pypi_0    pypi
        nbclient                  0.7.2                    pypi_0    pypi
        nbconvert                 7.2.9                    pypi_0    pypi
        nbformat                  5.7.3                    pypi_0    pypi
        ncurses                   6.3                  h27087fc_1    conda-forge
        nest-asyncio              1.5.6                    pypi_0    pypi
        notebook-shim             0.2.2                    pypi_0    pypi
        openssl                   3.0.7                h0b41bf4_1    conda-forge
        packaging                 23.0                     pypi_0    pypi
        pandocfilters             1.5.0                    pypi_0    pypi
        parso                     0.8.3                    pypi_0    pypi
        pexpect                   4.8.0                    pypi_0    pypi
        pickleshare               0.7.5                    pypi_0    pypi
        pip                       22.3.1             pyhd8ed1ab_0    conda-forge
        platformdirs              2.6.2                    pypi_0    pypi
        prometheus-client         0.16.0                   pypi_0    pypi
        prompt-toolkit            3.0.36                   pypi_0    pypi
        psutil                    5.9.4                    pypi_0    pypi
        ptyprocess                0.7.0                    pypi_0    pypi
        pure-eval                 0.2.2                    pypi_0    pypi
        pycparser                 2.21                     pypi_0    pypi
        pygments                  2.14.0                   pypi_0    pypi
        pyrsistent                0.19.3                   pypi_0    pypi
        python                    3.10.8          h4a9ceb5_0_cpython    conda-forge
        python-dateutil           2.8.2                    pypi_0    pypi
        python-json-logger        2.0.4                    pypi_0    pypi
        pytz                      2022.7.1                 pypi_0    pypi
        pyyaml                    6.0                      pypi_0    pypi
        pyzmq                     25.0.0                   pypi_0    pypi
        readline                  8.1.2                h0f457ee_0    conda-forge
        requests                  2.28.2                   pypi_0    pypi
        rfc3339-validator         0.1.4                    pypi_0    pypi
        rfc3986-validator         0.1.1                    pypi_0    pypi
        send2trash                1.8.0                    pypi_0    pypi
        setuptools                66.1.1             pyhd8ed1ab_0    conda-forge
        six                       1.16.0                   pypi_0    pypi
        sniffio                   1.3.0                    pypi_0    pypi
        soupsieve                 2.3.2.post1              pypi_0    pypi
        stack-data                0.6.2                    pypi_0    pypi
        terminado                 0.17.1                   pypi_0    pypi
        tinycss2                  1.2.1                    pypi_0    pypi
        tk                        8.6.12               h27826a3_0    conda-forge
        tomli                     2.0.1                    pypi_0    pypi
        tornado                   6.2                      pypi_0    pypi
        traitlets                 5.8.1                    pypi_0    pypi
        tzdata                    2022g                h191b570_0    conda-forge
        uri-template              1.2.0                    pypi_0    pypi
        urllib3                   1.26.14                  pypi_0    pypi
        wcwidth                   0.2.6                    pypi_0    pypi
        webcolors                 1.12                     pypi_0    pypi
        webencodings              0.5.1                    pypi_0    pypi
        websocket-client          1.4.2                    pypi_0    pypi
        wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
        xz                        5.2.6                h166bdaf_0    conda-forge
        y-py                      0.5.5                    pypi_0    pypi
        ypy-websocket             0.8.2                    pypi_0    pypi

conda env:
        name: test
        channels:
          - conda-forge
        dependencies:
          - _libgcc_mutex=0.1=conda_forge
          - _openmp_mutex=4.5=2_gnu
          - bzip2=1.0.8=h7f98852_4
          - ca-certificates=2022.12.7=ha878542_0
          - ld_impl_linux-64=2.39=hcc3a1bd_1
          - libffi=3.4.2=h7f98852_5
          - libgcc-ng=12.2.0=h65d4601_19
          - libgomp=12.2.0=h65d4601_19
          - libnsl=2.0.0=h7f98852_0
          - libsqlite=3.40.0=h753d276_0
          - libuuid=2.32.1=h7f98852_1000
          - libzlib=1.2.13=h166bdaf_4
          - ncurses=6.3=h27087fc_1
          - openssl=3.0.7=h0b41bf4_1
          - pip=22.3.1=pyhd8ed1ab_0
          - python=3.10.8=h4a9ceb5_0_cpython
          - readline=8.1.2=h0f457ee_0
          - setuptools=66.1.1=pyhd8ed1ab_0
          - tk=8.6.12=h27826a3_0
          - tzdata=2022g=h191b570_0
          - wheel=0.38.4=pyhd8ed1ab_0
          - xz=5.2.6=h166bdaf_0
          - pip:
            - aiofiles==22.1.0
            - aiosqlite==0.18.0
            - anyio==3.6.2
            - argon2-cffi==21.3.0
            - argon2-cffi-bindings==21.2.0
            - arrow==1.2.3
            - asttokens==2.2.1
            - async-lru==1.0.3
            - attrs==22.2.0
            - babel==2.11.0
            - backcall==0.2.0
            - beautifulsoup4==4.11.1
            - bleach==6.0.0
            - certifi==2022.12.7
            - cffi==1.15.1
            - charset-normalizer==3.0.1
            - comm==0.1.2
            - debugpy==1.6.6
            - decorator==5.1.1
            - defusedxml==0.7.1
            - entrypoints==0.4
            - executing==1.2.0
            - fastjsonschema==2.16.2
            - fqdn==1.5.1
            - idna==3.4
            - ipykernel==6.20.2
            - ipython==8.8.0
            - isoduration==20.11.0
            - jedi==0.18.2
            - jinja2==3.1.2
            - json5==0.9.11
            - jsonpointer==2.3
            - jsonschema==4.17.3
            - jupyter-client==7.4.9
            - jupyter-core==5.1.5
            - jupyter-events==0.5.0
            - jupyter-lsp==1.5.1
            - jupyter-server==2.1.0
            - jupyter-server-fileid==0.6.0
            - jupyter-server-terminals==0.4.4
            - jupyter-server-ydoc==0.6.1
            - jupyter-ydoc==0.3.0
            - jupyterlab==4.0.0a32
            - jupyterlab-pygments==0.2.2
            - jupyterlab-server==2.19.0
            - markupsafe==2.1.2
            - matplotlib-inline==0.1.6
            - mistune==2.0.4
            - nbclient==0.7.2
            - nbconvert==7.2.9
            - nbformat==5.7.3
            - nest-asyncio==1.5.6
            - notebook-shim==0.2.2
            - packaging==23.0
            - pandocfilters==1.5.0
            - parso==0.8.3
            - pexpect==4.8.0
            - pickleshare==0.7.5
            - platformdirs==2.6.2
            - prometheus-client==0.16.0
            - prompt-toolkit==3.0.36
            - psutil==5.9.4
            - ptyprocess==0.7.0
            - pure-eval==0.2.2
            - pycparser==2.21
            - pygments==2.14.0
            - pyrsistent==0.19.3
            - python-dateutil==2.8.2
            - python-json-logger==2.0.4
            - pytz==2022.7.1
            - pyyaml==6.0
            - pyzmq==25.0.0
            - requests==2.28.2
            - rfc3339-validator==0.1.4
            - rfc3986-validator==0.1.1
            - send2trash==1.8.0
            - six==1.16.0
            - sniffio==1.3.0
            - soupsieve==2.3.2.post1
            - stack-data==0.6.2
            - terminado==0.17.1
            - tinycss2==1.2.1
            - tomli==2.0.1
            - tornado==6.2
            - traitlets==5.8.1
            - uri-template==1.2.0
            - urllib3==1.26.14
            - wcwidth==0.2.6
            - webcolors==1.12
            - webencodings==0.5.1
            - websocket-client==1.4.2
            - y-py==0.5.5
            - ypy-websocket==0.8.2
        prefix: /home/trungle/mambaforge/envs/test</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 2023-01-25 14:11:50.986 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-01-25 14:11:50.988 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2023-01-25 14:11:50.990 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-01-25 14:11:50.992 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2023-01-25 14:11:50.995 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-01-25 14:11:51.086 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-01-25 14:11:51.113 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-01-25 14:11:51.332 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2023-01-25 14:11:51.556 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-01-25 14:11:51.556 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-01-25 14:11:51.556 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /home/trungle
[I 2023-01-25 14:11:51.556 FileIdExtension] ArbitraryFileIdManager : Configured database path: /home/trungle/.local/share/jupyter/file_id_manager.db
[I 2023-01-25 14:11:51.556 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-01-25 14:11:51.556 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices.
[I 2023-01-25 14:11:51.557 FileIdExtension] Attached event listeners.
[I 2023-01-25 14:11:51.557 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-01-25 14:11:51.557 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-01-25 14:11:51.558 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2023-01-25 14:11:51.558 LabApp] JupyterLab extension loaded from /home/trungle/mambaforge/envs/test/lib/python3.10/site-packages/jupyterlab
[I 2023-01-25 14:11:51.558 LabApp] JupyterLab application directory is /home/trungle/mambaforge/envs/test/share/jupyter/lab
[I 2023-01-25 14:11:51.558 LabApp] Extension Manager is 'pypi'.
[I 2023-01-25 14:11:51.560 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-01-25 14:11:51.560 ServerApp] Serving notebooks from local directory: /home/trungle
[I 2023-01-25 14:11:51.560 ServerApp] Jupyter Server 2.1.0 is running at:
[I 2023-01-25 14:11:51.560 ServerApp] http://localhost:8888/lab?token=90bfd70b9412dd6bbef635fc0fee73d681ce175f25ccfa4c
[I 2023-01-25 14:11:51.560 ServerApp]  or http://127.0.0.1:8888/lab?token=90bfd70b9412dd6bbef635fc0fee73d681ce175f25ccfa4c
[I 2023-01-25 14:11:51.560 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by davidbrochart** [comment]
I think `jupyter-ydoc` v0.3.0 only works with `master`, right @hbcarlos ?

**Comment by hbcarlos** [comment]
Yes. In addition, we need to make a release of [jupyter_server_ydoc](https://github.com/jupyter-server/jupyter_server_ydoc) with this PR: https://github.com/jupyter-server/jupyter_server_ydoc/pull/72

**Comment by trungleduc** [comment]
> I think `jupyter-ydoc` v0.3.0 only works with `master`, right @hbcarlos ?

indeed, downgrading to `jupyter-ydoc-0.2.2` fixes the issue

**Comment by davidbrochart** [comment]
`jupyter-server-ydoc` [v0.6.2](https://github.com/jupyter-server/jupyter_server_ydoc/releases/tag/v0.6.2) has been released.

**Comment by hbcarlos** [comment]
I'm working on a PR to fix master
