### ISSUE TITLE
Can't open this page. Error 9

### ISSUE THREAD

**Issue by nyctophile-aayu** [jupyterlab/jupyterlab#13850]
I am trying to run a code in Jupyter Lab in Fermi-GBM environment run by Conda (Anaconda). Since yesterday, it is killing the page and not producing any result. Mostly, it happens at a particular set of codes only. But, before yesterday, it was working fine. Including that set of codes as well.

Could anyone please help and suggest how to fix this issue? Since I have to produce result.

![Screenshot from 2023-01-24 16-56-02](https://user-images.githubusercontent.com/101836465/214279863-1e92b6ad-86df-4a2b-8bd6-a3838cf2feaf.png)

**Comment by JasonWeill** [comment]
@nyctophile-aayu Thanks for filing this issue! I'm not sure where this "Error 9" in Chrome is coming from. Is your notebook generating a lot of output, potentially exceeding your system's memory? Does the error go away if you clear your cache in your browser? Can you run your notebook on your local computer using ipython or JupyterLab running locally?

If possible, can you please provide information about your browser, the version of JupyterLab, and any notebook(s) that cause this error to appear when you run them? Thanks again!

**Comment by nyctophile-aayu** [comment]
Thanks for the kind reply. Yes, I have tried clearing the cache of the Browser and even tried to run it in different browser. But, it do not work. Somehow this environment is bound to open in Chrome only. I have tried multiple restart of the system. But, issue persists. Not only that, but when the tab kills then along with it all the tabs opened in that window kills along with it, irrespective of which website is opened in other tabs.

It was running fine until day before yesterday. But, now it doesn't work and kills the tab as well.

The version of the notebook server is: 6.5.2
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]

I wish I could upload the notebook but .pynb file is not supported by the file attache. Please help.

**Comment by JasonWeill** [comment]
@nyctophile-aayu Thanks for your response! The behavior in Chrome, with multiple tabs dying out at once, suggests that your system might be running low on memory generally. If you run a system monitor like `top`, do you see very high levels of memory consumption when you're using this notebook?

I'm not sure how best to attach a notebook to an issue. If `.ipynb` isn't supported as a file extension, could you compress the notebook and upload the `.tar.gz` or `.zip` file? You can also create a [GitHub gist](https://gist.github.com) containing your notebook and link to that (assuming it's OK to share publicly).

Are you seeing any error output in Chrome's developer tools?

What is the output when you run `jupyter labextension list`?

**Comment by nyctophile-aayu** [comment]
Yes, I have seen very worse behaviour of the system. I managed to check the _htop_ as well. I found 5 out of 20 cores are running at 100% and a few of the remaining are running at half of it. 

I wish I could attach the file, but the project is under processing and due to security reasons, I couldn't share the files. But, the issue got resolved with increasing time binning. Previously, I was doing 0.001 s time binning which was causing the error and now when I tried with 0.025, the issue got resolved. However, I still would like to know why the system is doing such a behaviour that all other tabs wee also killing due to died kernel in the Jupyter notebook.

So, I don't have to face the same problem in the future.

Output of the _Jupyter labextension list_ is:

```
JupyterLab v3.5.2
/home/ubuntu/.local/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)

/home/ubuntu/anaconda3/share/jupyter/labextensions
        ipyvolume v0.6.0-alpha.10 enabled OK
        jupyter-vuetify v1.8.4 enabled OK
        jupyter-threejs v2.4.0 enabled OK (python, pythreejs)
        jupyterlab-datawidgets v7.1.2 enabled OK
        jupyter-vue v1.8.0 enabled OK
        jupyter-webrtc v0.6.0 enabled OK
        bqplot v0.5.37 enabled OK (python, bqplot)
        jupyterlab-plotly v5.11.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.1.1 enabled OK (python, jupyterlab_widgets)
        @pyviz/jupyterlab_pyviz v2.2.1 enabled OK (python, pyviz_comms)
        @dunovank/jupyterlab_darkside_ui v0.2.3 enabled OK (python, jupyterlab_darkside_ui)

Other labextensions (built into JupyterLab)
   app dir: /home/ubuntu/anaconda3/share/jupyter/lab

```
