### ISSUE TITLE
pip install -e --user is not resolved by Jupyterlab

### ISSUE THREAD

**Issue by 12rambau** [jupyterlab/jupyterlab#13867]
## Description 

I'm using jupyterlab for development in a cloud environment. It works fantastic but I'm facing a new bug recently: packages installed in editable mode are not resolved anymore. I opened an issue on this I was unsure it was a jupyterlab related issue but it seems it is (it works as expected in scripts)

## Reproduce

from my terminal I run:

```
git clone git@github.com:pydata/numexpr.git
pip install -e --user numexpr
```

In my local folder, I find the following: 

```
.local/
└── lib/
    └── python3.8/
        └── site-packages/
            ├── numexpr-2.8.5.dev1.dist-info/
            ├── __editable___numexpr_2_8_5_dev1_finder.py
            └── __editable___numexpr_2_8_5_dev1_finder.py
```

Now from a jupyter notebook, I execute the following cell: 

```python
import numexpr
numexpr.__version__
```

which give me 2.7.1 which is not version I installed in editable mode. 

But from the terminal, it returns the correct version. 

```
$ pip show numexpr

Version: 2.8.5.dev1
```

## Expected behavior

I would expect terminal and notebook to output the same thing (as they run on the same Python

## Context

- Operating System and version: focal
- Python: 3.8   
- pip: 22.3.1   
- jupyterlab: 3.5.2

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /home/sepal-user/.local/bin
        /home/sepal-user/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/local/lib/orfeo/bin
        /usr/local/snap/bin
        /usr/local/lib/python3.8/dist-packages/sepal_ui/bin

sys.path:
        /usr/local/bin
        /usr/lib/python38.zip
        /usr/lib/python3.8
        /usr/lib/python3.8/lib-dynload
        /home/sepal-user/.local/lib/python3.8/site-packages
        /home/sepal-user/libs/commitizen
        /usr/local/lib/python3.8/dist-packages
        /usr/local/lib/python3.8/dist-packages/biota-0.3-py3.8.egg
        /usr/local/lib/python3.8/dist-packages/sen2mosaic-0.2-py3.8.egg
        /usr/local/lib/python3.8/dist-packages/deforest-0.1-py3.8.egg
        /jupyter_contrib_nbextensions/src
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.8.10 (default, Nov 14 2022, 12:59:47) 
        [GCC 9.4.0]

platform.platform():
        Linux-4.14.268-205.500.amzn2.x86_64-x86_64-with-glibc2.29

which -a jupyter:
        /usr/local/bin/jupyter

pip list:
        Package                           Version              Editable project location
        --------------------------------- -------------------- ---------------------------------
        absl-py                           1.4.0
        affine                            2.3.0
        aiohttp                           3.8.3
        aiosignal                         1.3.1
        alabaster                         0.7.12
        anyio                             3.6.2
        appdirs                           1.4.3
        argcomplete                       1.12.3
        argon2-cffi                       21.3.0
        argon2-cffi-bindings              21.2.0
        arrow                             1.2.3
        astroid                           2.13.2
        asttokens                         2.2.1
        astunparse                        1.6.3
        async-timeout                     4.0.2
        atomicwrites                      1.1.5
        attrs                             19.3.0
        awscli                            1.27.48
        Babel                             2.11.0
        backcall                          0.2.0
        beautifulsoup4                    4.11.1
        bfast                             0.8.dev0
        billiard                          4.1.0
        biota                             0.3
        bleach                            5.0.1
        blinker                           1.4
        bokeh                             2.4.3
        boto3                             1.26.48
        botocore                          1.29.48
        bqplot                            0.12.36
        branca                            0.6.0
        cachetools                        5.2.1
        cadati                            0.0.2
        certifi                           2019.11.28
        cffi                              1.15.1
        cfgv                              3.3.1
        cftime                            1.6.2
        chardet                           3.0.4
        charset-normalizer                2.1.1
        click                             8.1.3
        click-plugins                     1.1.1
        cligj                             0.5.0
        cloudpickle                       2.2.0
        colorama                          0.4.3
        colour                            0.1.5
        comm                              0.1.2
        commitizen                        2.28.0               /home/sepal-user/libs/commitizen
        configobj                         5.0.6
        configparser                      5.3.0
        coverage                          7.0.5
        cryptography                      2.8
        cupshelpers                       1.0
        cvxopt                            1.2.3
        cycler                            0.10.0
        Cython                            0.29.33
        dask                              2022.12.1
        dateutils                         0.6.12
        dbus-python                       1.2.16
        debugpy                           1.6.5
        decli                             0.5.2
        decorator                         4.4.2
        deepdiff                          6.2.3
        defer                             1.0.6
        deforest                          0.1
        defusedxml                        0.7.1
        Deprecated                        1.2.13
        descartes                         1.1.0
        dill                              0.3.6
        distlib                           0.3.6
        distributed                       2022.12.1
        distro                            1.4.0
        distro-info                       0.23ubuntu1
        dm-tree                           0.1.8
        docopt                            0.6.2
        docutils                          0.16
        earthengine-api                   0.1.332
        ee-extra                          0.0.14
        eerepr                            0.0.4
        entrypoints                       0.3
        et-xmlfile                        1.0.1
        executing                         1.2.0
        falcon                            3.1.1
        fastjsonschema                    2.16.2
        ffmpeg-python                     0.2.0
        filelock                          3.9.0
        Fiona                             1.8.22
        flatbuffers                       2.0.7
        folium                            0.14.0
        fqdn                              1.5.1
        frozenlist                        1.3.3
        fsspec                            2022.11.0
        future                            0.18.2
        gast                              0.4.0
        GDAL                              3.4.3
        gdown                             4.6.0
        geeadd                            0.5.6
        geemap                            0.19.2
        geocoder                          1.38.1
        geojson                           2.5.0
        geopandas                         0.10.2
        godale                            0.3
        google-api-core                   1.34.0
        google-api-python-client          1.12.8
        google-auth                       2.16.0
        google-auth-httplib2              0.1.0
        google-auth-oauthlib              0.4.6
        google-cloud-core                 2.3.2
        google-cloud-storage              2.7.0
        google-crc32c                     1.5.0
        google-pasta                      0.2.0
        google-resumable-media            2.4.0
        googleapis-common-protos          1.58.0
        grpcio                            1.51.1
        gunicorn                          20.1.0
        h11                               0.12.0
        h5py                              2.10.0
        haversine                         2.7.0
        HeapDict                          1.0.1
        html5lib                          1.0.1
        httpcore                          0.15.0
        httplib2                          0.21.0
        httpx                             0.23.0
        identify                          2.5.13
        idna                              2.8
        imageio                           2.24.0
        imagesize                         1.4.1
        importlib-metadata                6.0.0
        importlib-resources               5.10.2
        ipyevents                         2.0.1
        ipyfilechooser                    0.6.0
        ipykernel                         6.20.1
        ipyleaflet                        0.17.2
        ipyspin                           1.0.1
        ipython                           8.8.0
        ipython-genutils                  0.2.0
        ipytree                           0.2.2
        ipyurl                            0.1.3
        ipyvue                            1.8.0
        ipyvuetify                        1.8.2
        ipywidgets                        7.7.2
        isoduration                       20.11.0
        isort                             5.11.4
        jdcal                             1.0
        jedi                              0.18.2
        Jinja2                            3.0.3
        jmespath                          1.0.1
        joblib                            0.14.0
        json5                             0.9.11
        jsonpointer                       2.3
        jsonschema                        4.17.3
        jupyter                           1.0.0
        jupyter_client                    7.4.1
        jupyter-console                   6.4.4
        jupyter-contrib-core              0.4.2
        jupyter-contrib-nbextensions      0.7.0                /jupyter_contrib_nbextensions/src
        jupyter_core                      5.1.3
        jupyter-events                    0.6.2
        jupyter-highlight-selected-word   0.2.0
        jupyter-latex-envs                1.4.6
        jupyter-nbextensions-configurator 0.6.1
        jupyter-server                    1.23.4
        jupyter-server-proxy              3.2.2
        jupyter_server_terminals          0.4.4
        jupyterlab                        3.5.2
        jupyterlab-language-pack-es-ES    3.5.post4
        jupyterlab-language-pack-fr-FR    3.5.post4
        jupyterlab-pygments               0.2.2
        jupyterlab_server                 2.18.0
        jupyterlab-widgets                1.1.1
        keras                             2.7.0
        Keras-Preprocessing               1.1.2
        keyring                           18.0.1
        kiwisolver                        1.0.1
        language-selector                 0.1
        launchpadlib                      1.10.13
        lazr.restfulclient                0.14.2
        lazr.uri                          1.0.3
        lazy-object-proxy                 1.9.0
        lckr-jupyterlab-variableinspector 3.0.9
        libclang                          15.0.6.1
        llvmlite                          0.36.0
        locket                            1.0.0
        logzero                           1.7.0
        lxml                              4.5.0
        macaroonbakery                    1.3.1
        Markdown                          3.4.1
        MarkupSafe                        2.1.1
        matplotlib                        3.1.2
        matplotlib-inline                 0.1.6
        mccabe                            0.7.0
        mercantile                        1.2.1
        mistune                           2.0.4
        more-itertools                    4.2.0
        mpi4py                            3.0.3
        msgpack                           1.0.4
        multidict                         6.0.4
        munch                             2.5.0
        natsort                           8.2.0
        nbclassic                         0.4.8
        nbclient                          0.7.2
        nbconvert                         7.2.7
        nbformat                          5.7.2
        nest-asyncio                      1.5.6
        netCDF4                           1.6.2
        networkx                          3.0
        nodeenv                           1.7.0
        nose                              1.3.7
        nosexcover                        1.0.11
        notebook                          6.5.2
        notebook_shim                     0.2.2
        numba                             0.53.1
        numexpr                           2.8.5.dev1           /home/sepal-user/libs/numexpr
        numpy                             1.24.1
        numpydoc                          1.2.1
        oauth2client                      4.1.3
        oauthlib                          3.1.0
        oeel                              0.9.7.5
        olefile                           0.46
        openpyxl                          3.0.3
        opensartoolkit                    0.12.5
        opt-einsum                        3.3.0
        ordered-set                       4.1.0
        orjson                            3.8.5
        packaging                         21.3
        pandas                            1.5.2
        pandocfilters                     1.5.0
        parso                             0.8.3
        partd                             1.3.0
        patsy                             0.5.1
        pbr                               5.11.1
        pexpect                           4.8.0
        pickleshare                       0.7.5
        Pillow                            9.4.0
        pip                               22.3.1
        pipreqs                           0.4.11
        pkgutil_resolve_name              1.3.10
        planet                            2.0a6
        platformdirs                      2.6.2
        plotly                            5.11.0
        pluggy                            0.13.0
        pre-commit                        2.21.0
        prometheus-client                 0.15.0
        prompt-toolkit                    3.0.36
        protobuf                          3.20.3
        psutil                            5.5.1
        psycopg2-binary                   2.9.5
        ptyprocess                        0.7.0
        pure-eval                         0.2.2
        py                                1.8.1
        pyarrow                           10.0.1
        pyasn1                            0.4.8
        pyasn1-modules                    0.2.8
        pycairo                           1.16.2
        pycparser                         2.21
        PyCRS                             1.0.2
        pycrypto                          2.6.1
        pycups                            1.9.73
        pygadm                            0.1.1
        pygeobase                         0.4.0
        pygeogrids                        0.4.1
        Pygments                          2.14.0
        PyGObject                         3.36.0
        PyJWT                             2.6.0
        pykdtree                          1.3.6
        pylint                            2.15.10
        pymacaroons                       0.13.0
        PyNaCl                            1.3.0
        pynetcf                           0.2.3
        pyopencl                          2022.3.1
        pyparsing                         2.4.6
        PyPDF2                            3.0.1
        pyperclip                         1.8.2
        pyproj                            2.6.1
        pyresample                        1.26.0.post0
        pyRFC3339                         1.1
        pyrsistent                        0.19.3
        pyshp                             2.3.1
        PySocks                           1.7.1
        pytesmo                           0.14.3
        pytest                            4.6.9
        python-apt                        2.0.0+ubuntu0.20.4.8
        python-box                        6.1.0
        python-dateutil                   2.8.2
        python-debian                     0.1.36ubuntu1
        python-json-logger                2.0.4
        pytools                           2022.1.14
        pytz                              2022.7
        PyWavelets                        1.4.1
        PyYAML                            5.4.1
        pyzmq                             24.0.1
        qtconsole                         5.4.0
        QtPy                              2.3.0
        questionary                       1.10.0
        rasterio                          1.2.10
        ratelim                           0.1.6
        repurpose                         0.8
        requests                          2.28.1
        requests-futures                  0.9.9
        requests-oauthlib                 1.3.1
        requests-unixsocket               0.2.0
        retrying                          1.3.4
        rfc3339-validator                 0.1.4
        rfc3986                           1.5.0
        rfc3986-validator                 0.1.1
        rioxarray                         0.13.3
        riskmapjnr                        1.2
        rsa                               4.7.2
        Rtree                             1.0.1
        s3transfer                        0.6.0
        sankee                            0.2.1
        scikit-image                      0.19.3
        scikit-learn                      0.22.2.post1
        scipy                             1.10.0
        scooby                            0.7.0
        SecretStorage                     2.3.1
        sen2mosaic                        0.2
        Send2Trash                        1.8.0
        sepal-ui                          2.14.2               /home/sepal-user/libs/sepal_ui
        setuptools                        66.1.1
        shapely                           2.0.0
        shapely-geojson                   0.0.1
        simpervisor                       0.4
        simplejson                        3.16.0
        six                               1.14.0
        sniffio                           1.3.0
        snowballstemmer                   2.2.0
        snuggs                            1.4.7
        sortedcontainers                  2.4.0
        soupsieve                         1.9.5
        Sphinx                            2.2.0
        sphinx-bootstrap-theme            0.7.1
        sphinxcontrib.applehelp           1.0.3
        sphinxcontrib-devhelp             1.0.2
        sphinxcontrib-htmlhelp            2.0.0
        sphinxcontrib-jsmath              1.0.1
        sphinxcontrib-qthelp              1.0.3
        sphinxcontrib-serializinghtml     1.1.5
        ssh-import-id                     5.10
        stack-data                        0.6.2
        statsmodels                       0.11.1
        supervisor                        4.1.0
        systemd-python                    234
        tables                            3.6.1
        tblib                             1.7.0
        tenacity                          8.1.0
        tensorboard                       2.11.0
        tensorboard-data-server           0.6.1
        tensorboard-plugin-wit            1.8.1
        tensorflow                        2.7.0
        tensorflow-estimator              2.7.0
        tensorflow-io-gcs-filesystem      0.29.0
        tensorflow-probability            0.19.0
        termcolor                         1.1.0
        terminado                         0.17.1
        testresources                     2.0.1
        tifffile                          2022.10.10
        tinycss2                          1.2.1
        tomli                             2.0.1
        tomlkit                           0.11.6
        toolz                             0.12.0
        tornado                           6.2
        tqdm                              4.64.1
        traitlets                         5.8.1
        traittypes                        0.2.1
        TuiView                           1.0.4
        typing_extensions                 4.4.0
        unattended-upgrades               0.1
        Unidecode                         1.3.6
        uri-template                      1.2.0
        uritemplate                       3.0.1
        urllib3                           1.25.8
        virtualenv                        20.17.1
        voila                             0.4.0
        wadllib                           1.3.3
        Wand                              0.6.11
        wcwidth                           0.1.8
        webcolors                         1.12
        webencodings                      0.5.1
        websocket-client                  1.4.2
        websockets                        10.4
        Werkzeug                          2.1.2
        wget                              3.2
        wheel                             0.34.2
        whitebox                          2.2.0
        whiteboxgui                       2.2.0
        widgetsnbextension                3.6.1
        wrapt                             1.14.1
        xarray                            2022.12.0
        xarray-leaflet                    0.1.16
        xlrd                              1.1.0
        xlwt                              1.3.0
        xyzservices                       2022.9.0
        yarg                              0.1.9
        yarl                              1.8.2
        zict                              2.2.0
        zipp                              3.11.0
</pre>
</details>

I cannot run `jupyter lab --debug` command, I'm working in a cloud environment that launch jupyterlab for me.

**Comment by JasonWeill** [comment]
@12rambau Thanks for opening this issue! One possible explanation is that your remote Jupyter Server is running in a particular Conda/Mamba environment, and when you install `numexpr` in a terminal, you're installing the package in a different environment. If you know which environment you need to modify, and if you have permissions to modify this environment, then you'll need to install `numexpr` in the same environment as JupyterLab is running in. You might need assistance from your Jupyter Server's administrator.

**Comment by 12rambau** [comment]
I'm positive they both run in the same environment as if I change the command to: 
```
pip install --user numexpr
```

then I see the correct version in Jupyterlab as well. The main difference being: 
when `-e` is not specified, a `numexpress` folder is created in `site_packages`.

**Comment by JasonWeill** [comment]
When you run `which pip` inside your JupyterLab terminal and in a terminal on the system where JupyterLab is running, what's the output of each? Are you sure you're running the same `pip` each time?

Same goes for `which python`. Also, can you share the output of running `env` in each?

Thanks again for your help!

**Comment by 12rambau** [comment]
I'm only installing things from my terminal, nothing from Jupyter itself. 
| jupyterlab |  /usr/bin/python  | /usr/local/bin/pip |
|------------|--------------------|--------------------|
| terminal   | /usr/bin/python    | /usr/local/bin/pip    |

The env is also the same but it's quite long so I wont print it here. curious I checked `!which pip` from a cell but I of course got the same value.

**Comment by krassowski** [comment]
what is `%pip show numexpr` when run from terminal?

**Comment by krassowski** [comment]
From **notebook** not terminal, sorry!

**Comment by 12rambau** [comment]
```
Name: numexpr
Version: 2.8.5.dev1
Summary: Fast numerical expression evaluator for NumPy
Home-page: https://github.com/pydata/numexpr
Author: David M. Cooke, Francesc Alted, and others
Author-email: 
License: MIT
Location: /home/sepal-user/.local/lib/python3.8/site-packages
Requires: numpy
Required-by: 
Note: you may need to restart the kernel to use updated packages.
```

so the correct one

**Comment by krassowski** [comment]
So it should work indeed. To pull the changes (including new `numexpr.__version__`) from an editable package which was previously imported you need to either:
- restart kernel between new installation/modifications,
- or use `%autoreload` magic from IPython

did you do either of these things?

**Comment by 12rambau** [comment]
I always run with "restart kernel and run all cells"

**Comment by JasonWeill** [comment]
@12rambau Thanks for your continued contributions on this issue! Do you see the same behavior if you run [ipython](https://pypi.org/project/ipython/) with your code inside a terminal? You can do this inside of JupyterLab. If you continue to see this behavior inside iPython, this might be an [issue with iPython](https://github.com/ipython/ipython/issues) instead.

**Comment by 12rambau** [comment]
you gave me an idea: Instead of running `pip show` I went to my terminal and run:
```
python3
>>> import numexpr
>>> numexpr.__version__
```
which returns: '2.7.1' => not the editable installed version

The issues is thus not related to jupyterlab but Python 3.8 itself that is not recognizing the elements. I'll move this issue to pip repository maybe they will have an idea (I hope it's trivial).

**Comment by 12rambau** [comment]
Just an update as I found the solution: 

Thanks to another thread (https://github.com/microsoft/pylance-release/issues/78) I finally understand the issue:
`setuptools` recently added support for [PEP660](https://peps.python.org/pep-0660/) which seems unsupported by my environment. 
running `pip install -e . --config-settings editable_mode=compat` as suggested in [`setuptool` documentation](https://setuptools.pypa.io/en/latest/userguide/development_mode.html#legacy-behavior) solved it.
