### ISSUE TITLE
Update to TypeScript 5 final

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13872]
### Problem

TypeScript 5 beta is now available: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/

We should directly update to it for JupyterLab 4.0 since its final release will likely be available before JupyterLab 4 final.

### Proposed Solution

Update to TypeScript 5.

### Additional context

Some work to update TypeScript had already started in https://github.com/jupyterlab/jupyterlab/pull/13028. Although it's been lagging a bit behind and had to go through multiple rebases due to issues in some dependencies.

**Comment by krassowski** [comment]
@JasonWeill we cannot do this in 4.1. Could we avoid moving issues which have to be addressed in 4.0 (either because they are regressions or because they require a major version bump) to 4.1 milestone, please?

**Comment by jasongrout** [comment]
According to the TS 5.0 [timeline](https://github.com/microsoft/TypeScript/issues/51362), 5.0RC is expected 28 Feb, with 5.0 final released 14 Mar.

+1 to updating to TS 5.0 if possible for jlab 4.0.

**Comment by jasongrout** [comment]
I submitted a quick PR at https://github.com/jupyterlab/jupyterlab/pull/13925 to look at upgrading to TS 5.0 beta.

**Comment by jtpio** [comment]
The update to TypeScript 5 beta landed in https://github.com/jupyterlab/jupyterlab/pull/13925.

We can keep this issue open to update to TypeScript 5 final.

**Comment by JasonWeill** [comment]
@jtpio TypeScript 5 is now available: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/

**Comment by jtpio** [comment]
Nice thanks for the heads up. PR incoming.
