### ISSUE TITLE
JupyterLab 3.6.0rc1 - style changes

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13870]
## Description

In JupyterLab 3.6.0rc1, there is two styling changes that I'm not sure feeling comfortable.

![image](https://user-images.githubusercontent.com/8435071/215058145-e79b2002-4b36-4af8-b735-1afa809e5263.png)

The menu is position below the menubar due to the new optimization introduced in Lumino https://github.com/jupyterlab/lumino/pull/432 - this prevent the y position trick to be applied:

https://github.com/jupyterlab/jupyterlab/blob/7227449db8db478dc5e31bbc1ffdfb741766a35d/packages/application/style/menus.css#L30

A submenu get a outline focus. It feels wrong.

> The focus effect is probably the consequence of https://github.com/jupyterlab/jupyterlab/pull/13415

For reference, here is the look in JupyterLab 3.5.3.

![image](https://user-images.githubusercontent.com/8435071/215059530-5ca5d376-53f3-46b0-b7b2-728bab9a8bef.png)

## Reproduce

Install 3.6.0rc1 by executing `python -m pip install jupyterlab==3.6.0rc1`

**Comment by fperez** [comment]
Thx @fcollonval for all your work on these releases! 

I totally agree these visual changes are worrisome. This is what even the main menus look like for me:

![image](https://user-images.githubusercontent.com/57394/215180540-257ce341-9c02-42f6-ab21-c27577374396.png)

Not only is that vertical gap odd, the bold blue outlines on all menus really shouldn't be there. They even persist when a menu is closed:

![image](https://user-images.githubusercontent.com/57394/215181058-7b3628f3-8d46-4df3-877a-77a5fda8fe4a.png)

I think these should be fixed to the behavior of 3.5.x before the 3.6.0 release. B/c of the RTC improvements, 3.6 should really be a very good upgrade for many (we're doing experimental testing for it both at Berkeley and LBL). I really don't think we should have these odd visuals in a widely deployed/advertised release.

**Comment by krassowski** [comment]
CC @gabalafou

**Comment by krassowski** [comment]
The outline thingy on menus is confusing because I cannot reproduce it on master (is it a me problem?), but I do see it on 3.6 branch. I agree that having both outline and background effect is redundant. I am nor sure about the full menu outline effect (this one does not have an existing indicator and may be needed indeed) but that could possibly have a more subtle visual indicator,

**Comment by krassowski** [comment]
Ok, so this is down to removal of bluprint override in the backport (https://github.com/jupyterlab/jupyterlab/pull/13543):

```diff
- /* Override Blueprint's _accessibility.scss styles */
- :focus {
-   outline: unset;
-   outline-offset: unset;
-   -moz-outline-radius: unset;
- }
```

we should keep it on 3.x

**Comment by fcollonval** [comment]
Thanks a lot for fixing all those artifacts @krassowski 

Did you see anything else? If not I think we are good to go for the final release.

**Comment by fcollonval** [comment]
Closing as fixed
