### ISSUE TITLE
Search box cursor jumps to end of input after typing a character

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13881]
## Description

Search box cursor jumps to end of input after typing a character giving bad UX.

## Reproduce

1. Enter `12` in search box
2. Move cursor left so that it is between 1 and 2
3. Press 3
4. See that cursor moved to end
5. Press 4, see that we get 1324 instead of expected 1342

[Screencast from 2023-01-28 22-16-59.webm](https://user-images.githubusercontent.com/5832902/215293651-7e026f68-b2d7-49f2-940d-63e4bd332d2c.webm)

It seems to be a spurious re-render in React.

## Expected behavior

User can modify search text easily

## Context

- JupyterLab version: 4.0.0a32

**Comment by JasonWeill** [comment]
@krassowski @fcollonval I see this is moved to 4.0.0 but it doesn't have an assignee yet. Is one of you available to pick this up? Without an owner, this might need to be moved to a later version. Thanks.

**Comment by krassowski** [comment]
This is a critical regression which can lead to data loss and needs to be addressed before 4.0. I am not happy with moving bugs or of milestone because it seems like making progress - it is not.

**Comment by fcollonval** [comment]
@JasonWeill I move back some issues from 4.1.0 to 4.0.0 that needs to be resolved (or works is on going). What have to be pushed to 4.1.0 are features due to the feature freeze deadline; bugs should be addressed for 4.0.0 release as much as possible.

**Comment by JasonWeill** [comment]
@fcollonval @krassowski Thanks for doing this. As discussed at this past week's meeting, could one of you please assign yourself to this issue? The lack of an assignees was the bigger concern than just the number of items on 4.0.0.
