### ISSUE TITLE
Unexpected text color in file browser when using light theme

### ISSUE THREAD

**Issue by facusapienza21** [jupyterlab/jupyterlab#13894]
## Description

There is an unexpected behavior with the colors of the text in the files browser in the last versions of JupyterLab. With @fperez we have been observing this in both local installations of JupyterLub and in different JupyterHubs. At the moment of creating a new file in the file browser using the light theme, the name of the file doesn't show up: 

<img width="398" alt="Screen Shot 2023-01-30 at 2 22 18 PM" src="https://user-images.githubusercontent.com/39526081/215609199-293f604f-4c67-4100-a257-085b7f2c463d.png">

If you highligh the text, you can see the text. Also, if you change to dark mode you can also see the text:

<img width="399" alt="Screen Shot 2023-01-30 at 2 22 53 PM" src="https://user-images.githubusercontent.com/39526081/215609331-87e737e0-828d-4eac-8149-b7868cef4e6c.png">

## Reproduce

You can reproduce this problem by creting a minimal local environmnet using the following `.yml` file
```
name: minimal

channels:
  - conda-forge

dependencies:
  - python==3.10.8
  - jupyterlab==3.5.2
```
when you lunch JupyterLab from this environment, you can see the problem I was describing before. 

## Context

- Operating System and version: Locally I was able to see this in a Mac Catalina machine, but also this happens in the cloud-supported JupyterHub. 
- Browser and version: Safari 15.6.1 
- JupyterLab version: This example is for `jupyterlab=3.5.2`, but the same happens in `jupyterlab=3.4.5`.

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
I could not reproduce this on Chrome, but I believe it is a real issue which may appear under some edge cases.

**Comment by fperez** [comment]
FWIW, on my Mac laptop, I see it on Firefox, Chrome and Safari, both on a locally-installed and on a remote-hosted instance.

An environment made as follows

```bash
mamba create -n jlbug python=3.10.8
mamba activate jlbug
mamba install jupyterlab==3.5.2
jupyter lab
```

shows the problem for me (MacOS 13.2, all browsers).
