### ISSUE TITLE
New notebook pulldown looks a bit busted 

### ISSUE THREAD

**Issue by palewire** [jupyterlab/jupyterlab#1389]
When I hit the plus button in the upper left and ask to make a new notebook, my pulldown in the dialog looks like this:

![screenshot from 2016-12-06 14-21-19](https://cloud.githubusercontent.com/assets/9993/20946435/7fae31f6-bbbf-11e6-82a4-0a7e3a60802e.png)

**Comment by blink1073** [comment]
Ha, yeah, we can do better here.  We should be more selective in adding separators and let the path extend across.

**Comment by cameronoelsen** [comment]
@blink1073 Why do we have the separators in the dropdown for the kernel in the first place? What was it used for to separate?

**Comment by sccolbert** [comment]
If that dropdown is implemented using a Phosphor `Menu`, those separators should be auto-collapsing so that you don't get two separators right next to each other, even if they are specified that way. If that's happening, maybe some default `p-mod-hidden` CSS rules are getting overridden.

**Comment by blink1073** [comment]
The dropdown is currently a native `<select>`  The separators are for the different types of kernel:  The default named kernel, no kernel, the rest of the named kernels, preferred running sessions, and the rest of the running sessions.   The content and appearance of the dropdown need love.
