### ISSUE TITLE
Unable to save files with 3.6.0rc0 + RTC

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#13890]
## Description

Save disabled with the jupyterlab 3.6.0rc0 + RTC enabled

In our testing jupyterhub with RTC enabled we see that:
- The save button is disabled.
- Save as doesn't actually save the file.

This worked with 3.6.0rc0 just a couple of days ago, but stopped working after an image rebuilt to the latest versions.

Versions:
```
ypy-websocket==0.8.2
jupyter-events==0.5.0
jupyter-server-fileid==0.6.0
jupyter-server-ydoc==0.6.1
jupyterlab==3.6.0rc0
y-py==0.5.5
jupyter_server==2.1.0
jupyter_client==7.4.9
jupyter_core==5.1.4
jupyter-events==0.5.0
```
These are the only messages that I see in the server logs that seem relevant
<details><summary>Command Line Output</summary>
<pre>
[D 2023-01-30 13:28:42.446 SingleUserLabApp websocket_server:140] Sending Y awareness from client with endpoint json:notebook:9c7bddc8-da02-4aa9-b0c8-276f674bd86e to client with endpoint: json:notebook:9c7bddc8-da02-4aa9-b0c8-276f674bd86e
[D 2023-01-30 13:28:44.439 SingleUserLabApp websocket_server:134] Received AWARENESS message from endpoint: JupyterLab:globalAwareness
[D 2023-01-30 13:28:44.439 SingleUserLabApp websocket_server:140] Sending Y awareness from client with endpoint JupyterLab:globalAwareness to client with endpoint: JupyterLab:globalAwareness
[D 2023-01-30 13:28:44.439 SingleUserLabApp websocket_server:140] Sending Y awareness from client with endpoint JupyterLab:globalAwareness to client with endpoint: JupyterLab:globalAwareness
[D 2023-01-30 13:28:44.445 SingleUserLabApp websocket_server:134] Received AWARENESS message from endpoint: JupyterLab:globalAwareness
[D 2023-01-30 13:28:44.445 SingleUserLabApp websocket_server:140] Sending Y awareness from client with endpoint JupyterLab:globalAwareness to client with endpoint: JupyterLab:globalAwareness
[D 2023-01-30 13:28:44.445 SingleUserLabApp websocket_server:140] Sending Y awareness from client with endpoint JupyterLab:globalAwareness to client with endpoint: JupyterLab:globalAwareness
</pre>
</details>

Browser Output
```
react_devtools_backend.js:4012 Cannot execute key binding 'Ctrl S': command 'docmanager:save' is not enabled.
```

**Comment by hbcarlos** [comment]
Hi @akhmerov. The save command is disabled in RTC on purpose. When RTC is activated, the backend saves the content of the file automatically every time the content changes. You don't need to save the file manually.

Can you check the dirty indicator on the title of the document:

https://user-images.githubusercontent.com/26092748/215830359-b2455c8e-4007-4153-b3dc-54a159cfa86e.mov

**Comment by akhmerov** [comment]
@hbcarlos ah, I forgot to also add that the document contents were not updated and the dirty indicator was on :worried:

**Comment by krassowski** [comment]
Reopening for further discussion. @akhmerov can you reproduce this reliably?

**Comment by akhmerov** [comment]
I was unable to reproduce this with rc1 and jupyter-server 2.2.0, so hopefully this is gone for good. Phew.

**Comment by fcollonval** [comment]
Thanks for the feedback @akhmerov

**Comment by akhmerov** [comment]
I've reopened because we see the issue resurfaced in 3.6.1. It seems that the problem appears with files that were edited across `y-*` upgrades. I see the following in the logs
```python
 [D 2023-02-07 13:49:34.859 SingleUserLabApp websocket_server:140] Sending Y awareness from client with endpoint text:file:a238d0e7-5377-4d7c-ac4d-3972c5aa96e0 to client with endpoint: text:file:a238d0e7-5377-4d7c-ac4d-3972c5aa96e0
2023-02-07 13:49:34,970 - SingleUserLabApp - ERROR - Uncaught exception GET <username>/api/yjs/json:notebook:a238d0e7-5377-4d7c-ac4d-3972c5aa96e0 (<IP>)
HTTPServerRequest(protocol='http', host='<host>', method='GET', uri='<username>/api/yjs/json:notebook:a238d0e7-5377-4d7c-ac4d-3972c5aa96e0', version='HTTP/1.1', remote_ip='<IP>')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/tornado/websocket.py", line 944, in _accept_connection
    await open_result
  File "/opt/conda/lib/python3.10/site-packages/jupyter_server_ydoc/handlers.py", line 222, in open
    if self.room.document.source != model["content"]:
  File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 26, in source
    return self.get()
  File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 166, in get
    metadata=meta["metadata"],
KeyError: 'metadata'
[E 2023-02-07 13:49:34.970 SingleUserLabApp web:1798] Uncaught exception GET <username>/api/yjs/json:notebook:a238d0e7-5377-4d7c-ac4d-3972c5aa96e0 (<IP>)
    HTTPServerRequest(protocol='http', host='<host>', method='GET', uri='<username>/api/yjs/json:notebook:a238d0e7-5377-4d7c-ac4d-3972c5aa96e0', version='HTTP/1.1', remote_ip='<IP>')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/opt/conda/lib/python3.10/site-packages/jupyter_server_ydoc/handlers.py", line 222, in open
        if self.room.document.source != model["content"]:
      File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 26, in source
        return self.get()
      File "/opt/conda/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 166, in get
        metadata=meta["metadata"],
    KeyError: 'metadata'
[D 2023-02-07 13:49:34.993 SingleUserLabApp handlers:204] Opening Y document from disk: <filename>
[D 2023-02-07 13:49:35.147 SingleUserLabApp yutils:134] Sending SYNC_STEP1 message to endpoint: json:notebook:a238d0e7-5377-4d7c-ac4d-3972c5aa96e0
```

**Comment by davidbrochart** [comment]
There has been a change in the shared document structure, but it should be fine in v3.6.1.
Until we implement [versioning](https://github.com/jupyter-server/jupyter_ydoc/issues/138), could you remove the `.jupyter_ystore.db` file in the directory where you launched JupyterLab, and see it that helps?

**Comment by akhmerov** [comment]
Ah, I'm confused; we're seeing #13930, and not this problem. I'll continue there, and close this issue.
