### ISSUE TITLE
When running multiple jupyter labs on a local machine - they should have maintain session information

### ISSUE THREAD

**Issue by Abhishek-P** [jupyterlab/jupyterlab#13900]
Raising this as a new feature request, assuming this was an existing feature causing the bug.

### Problem

* If  **multiple** jupyterlab servers (instances) are running on a local machine, they share session information such as about which notebooks are open. 

### Proposed Solution

They should **instead** provide separate isolated sessions.
What files are open in one instance, should be independent of the other.

### Additional context

In my case, I am using Jupyterlab for one course (which uses Scala) and one for OCaml for another course. 
In order to organize my work and being able to resume them, I run two different instances. But since session information is shared this is not possible. 

Running them on separate machines, should be work around but that doesn't solve it for local usage. 

This would probably be supported by maintain separate information (something akin to multi-tenancy), I suspect this would mean changes on the jupyterlab server backend side and not the web interface.

**Comment by krassowski** [comment]
You may want to define separate `JUPYTERLAB_WORKSPACES_DIR` variable per each course ([documentation](https://jupyterlab.readthedocs.io/en/stable/user/directories.html#jupyterlab-workspaces-directory)).

Also, next version of JupyterLab Desktop should enable that (work in progress: https://github.com/jupyterlab/jupyterlab-desktop/pull/556).

**Comment by Abhishek-P** [comment]
Thanks. Let me check that out and see if it is sufficiently supportive (the documentation didn't completely communicate the  nuances between `workspace` `profile` and `workspaces directory`. I will see if I can make it so 😄 
 
Feel feel to close the issue if you deem it so.

**Comment by JasonWeill** [comment]
Closing per requester — thanks @krassowski for your help!

If the existing options don't suit your needs, please reopen this or open another issue. Thanks.

**Comment by Abhishek-P** [comment]
I tried it out. 
Workspaces worked out for my needs for now. 
I think there is a small quality of life change that could be done. 
The `workspace` info or even just `id` could be displayed in the `title` for navigation
Additionally displaying it in the lab nav bars would be great. 

I will check out the community standards and request the feature. 

Thanks for the help.
