### ISSUE TITLE
Add button closing dangling kernels

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#13916]
> The "dangling" kernel is actually a real live kernel session that still exists but had no visibility before.

It was visible before too (and is on 3.x and 2.x). This is the where users refer to when they run low on memory (killing old kernels from closed notebooks that were previously closed). Maybe we even should have a button for "Kill all kernels which do not have any notebook/console".

On this use-case we could have something like this:

![Screenshot from 2023-01-24 19-53-59](https://user-images.githubusercontent.com/5832902/214395002-c1fbba37-d280-49d3-a28d-d233cd922843.png)

> Note: the numbers in circles on the graphic are irrelevant; those were from an exploration suggesting how to show the number of documents/widgets connected to the kernel.

_Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab/issues/13779#issuecomment-1402523525_

**Comment by afshin** [comment]
Will the definition of "dangling" include kernels that come from external sources and may have active users in another application?

**Comment by krassowski** [comment]
Good question. I think it should not.

And we probably should find a better word than "dangling" but "disconnected" would be too overloaded to be useful; "unused" feels like the right direction.

**Comment by cherieliu** [comment]
Hi @krassowski, this is my first time contributing to open source, and I want to work on this issue. Do you have any guidance?

**Comment by HarryDoan1** [comment]
Hello @krassowski, is this a frontend issue? This is my first time, and I would love to contribute. Can you let me know what I need to do?

**Comment by krassowski** [comment]
Sure you are welcome to open a draft pull request as soon as you got something working!

We have a [contributing guide](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html) which should answer some basic questions about setup, but if you cannot find the answer in there you can reach out on [JupyterLab gitter](https://gitter.im/jupyterlab/jupyterlab).

Changes would likely be contained to:

https://github.com/jupyterlab/jupyterlab/blob/86c9d5d2bc546fac2de1433f9497a3a6f2b80069/packages/running/src/index.tsx#L347-L398

as a final step, ideally we would also update the documentation:

https://github.com/jupyterlab/jupyterlab/blob/86c9d5d2bc546fac2de1433f9497a3a6f2b80069/docs/source/user/running.rst?plain=1#L46-L50

**Comment by krassowski** [comment]
Maybe the user-facing label should be "Closed Unused" rather than "Close dangling".
