### ISSUE TITLE
Remove the Python version pin for the `js-debugger` tests on CI?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#13946]
Opening a new issue to track follow-up improvements to https://github.com/jupyterlab/jupyterlab/pull/13941:

---

The alternative would be changing the environment variable as in the last commit of https://github.com/krassowski/jupyterlab/pull/19. I think we should report this upstream, AFAIK the team has not yet shipped this version in a new release of their IDE and may not be aware of implications of this change.

_Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab/issues/13941#issuecomment-1420522288_

**Comment by krassowski** [comment]
Upstream issue: https://github.com/microsoft/debugpy/issues/1208
