### ISSUE TITLE
Login to JupyterLab by credentials from PHPbb board

### ISSUE THREAD

**Issue by ManPython** [jupyterlab/jupyterlab#13955]
### Problem

There is often projects boards on engine as PHPbb and users can work with Jupyter, but there is problem with login to omit the registration, etc.
Also important are the ACL chmods to the dirs related to PHPbb groups that can allow eg. read file, save file, export.. move, execute.

### Proposed Solution
Can be used some python API as for PHPbb board
https://pypi.org/project/phpbb-python/

### Additional context

Can be other type login
https://github.com/googleapis/google-api-python-client

**Comment by JasonWeill** [comment]
Jupyter Server 2.0 introduced a new Identity API and a new authorization API to make custom providers like this one possible. See the blog announcement: https://blog.jupyter.org/jupyter-server-2-0-is-released-121ac99e909a (thanks @krassowski )

This wouldn't be a JupyterLab enhancement, but rather a custom plugin you'd need to write to interact with the new Jupyter Server APIs. See the [Jupyter Server repo](https://github.com/jupyter-server/jupyter_server/) and the [Jupyter Community Forum](https://discourse.jupyter.org/) for more resources.
