### ISSUE TITLE
File browser - wastes precious space

### ISSUE THREAD

**Issue by stefansimik** [jupyterlab/jupyterlab#13958]
Hi,
File Browser in JupyterLab wastes precious space. 
One screenshot says it all. The 2nd column should be definitely smaller.

<img width="2012" alt="Screenshot 2023-02-10 at 00 16 38" src="https://user-images.githubusercontent.com/6208056/217961038-7cd3d5b4-39ff-4deb-8f97-d7a2ccd13723.png">

**Comment by JasonWeill** [comment]
Closing as a duplicate of #3875.
