### ISSUE TITLE
Disable news prompt

### ISSUE THREAD

**Issue by domoritz** [jupyterlab/jupyterlab#13969]
The new prompt is breaking my visual regression tests. Is there an option to disable it in Galata automatically?

<img width="687" alt="Screenshot 2023-02-12 at 12 59 02" src="https://user-images.githubusercontent.com/589034/218328398-4f9b01db-8552-43a0-9766-9d2893e69362.png">

**Comment by krassowski** [comment]
Yes, just update galata to the latest version (4.5.0) and refresh lock files, and these will be disabled. Yesterday I went over this for ui-profiler (https://github.com/jupyterlab/ui-profiler/pull/32). While at it I recommend to bump `@jupyterlab/testutils` to 3.6.0 to reduce number of false positive dependabot updates.

**Comment by domoritz** [comment]
Sweet. I also found `jupyter labextension disable "@jupyterlab/apputils-extension:announcements"` disables it but it's even better that it's done automatically.

**Comment by domoritz** [comment]
Hmm, is there a changeling somewhere? I am on 3.0.11-2 and updating the dev breaks (`galata: command not found`)?

**Comment by fcollonval** [comment]
@domoritz galata has been integrated to `jupyterlab` repository in August 2021 (see https://github.com/jupyterlab/galata/issues/81).
You can look either at the project extension template : https://github.com/jupyterlab/extension-cookiecutter-ts/tree/3.0/%7B%7Bcookiecutter.python_name%7D%7D/ui-tests
Or update to @jupyterlab/galata@^4.5.0
