### ISSUE TITLE
Cannot open notebooks in jupyter lab

### ISSUE THREAD

**Issue by PashaM999** [jupyterlab/jupyterlab#13966]
## Description

I am using jupyter lab on a server. I have recently reinstalled it using pip-autoremove and got a new issue: some .ipynb files which were created prior to the reinstall are not opening, they just display a blank page (as if there are no cells) and I am unable to run the code. At the same time jupyter logs just spam the following:

```
[E 2023-02-11 10:01:18.559 ServerApp] Uncaught exception GET /api/yjs/json:notebook:47dee2d6-9ed3-42b0-b765-dd14ef0d9928 (188.132.162.66)
    HTTPServerRequest(protocol='http', host='35.188.218.231:8888', method='GET', uri='/api/yjs/json:notebook:47dee2d6-9ed3-42b0-b765-dd14ef0d9928', version='HTTP/1.1', remote_ip='188.132.162.66')
    Traceback (most recent call last):
      File "/home/jeff/.local/lib/python3.10/site-packages/tornado/websocket.py", line 944, in _accept_connection
        await open_result
      File "/home/jeff/.local/lib/python3.10/site-packages/jupyter_server_ydoc/handlers.py", line 222, in open
        if self.room.document.source != model["content"]:
      File "/home/jeff/.local/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 26, in source
        return self.get()
      File "/home/jeff/.local/lib/python3.10/site-packages/jupyter_ydoc/ydoc.py", line 166, in get
        metadata=meta["metadata"],
    KeyError: 'metadata'
```

I have installed jupyterlab with pip install jupyterlab which should make it the most recent version, but just in case here is the jupyter -version output:

```
Selected Jupyter core packages...
IPython          : 8.10.0
ipykernel        : 6.21.1
ipywidgets       : 8.0.4
jupyter_client   : 8.0.2
jupyter_core     : 5.2.0
jupyter_server   : 2.2.1
jupyterlab       : 3.6.1
nbclient         : 0.7.2
nbconvert        : 7.2.9
nbformat         : 5.7.3
notebook         : 6.5.2
qtconsole        : not installed
traitlets        : 5.9.0
```

I am not sure what could be causing this issue, because making a duplicate of the notebook fixes it entirely, but inspecting the code and permissions of the two resulting files reveals that they are absolutely the same. What could be causing this?

## Reproduce

I am launching jupyterlab using `jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --collaborative` to ensure that it is always on the port which is accessible and that I can use the notebook with other people.

## Expected behavior

Opens a file

## Context

- Operating System and version: Debian GNU/Linux 11 (bullseye)
- Browser and version: 110.0.5481.77 (Official Build) (64-bit) (cohort: M110_Stable) 
- JupyterLab version: 3.6.1

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /home/youwbfacts/.local/bin
        /usr/local/bin
        /usr/bin
        /bin
        /usr/local/games
        /usr/games

sys.path:
        /home/youwbfacts/.local/bin
        /usr/local/lib/python310.zip
        /usr/local/lib/python3.10
        /usr/local/lib/python3.10/lib-dynload
        /home/youwbfacts/.local/lib/python3.10/site-packages
        /usr/local/lib/python3.10/site-packages

sys.executable:
        /usr/local/bin/python3.10

sys.version:
        3.10.8 (main, Nov  8 2022, 08:51:34) [GCC 10.2.1 20210110]

platform.platform():
        Linux-5.10.0-19-cloud-amd64-x86_64-with-glibc2.31

which -a jupyter:
        /home/youwbfacts/.local/bin/jupyter

pip list:
        Package                      Version
        ---------------------------- -----------
        absl-py                      1.4.0
        aiofiles                     22.1.0
        aiosqlite                    0.18.0
        anyio                        3.6.2
        argon2-cffi                  21.3.0
        argon2-cffi-bindings         21.2.0
        arrow                        1.2.3
        asttokens                    2.1.0
        astunparse                   1.6.3
        attrs                        22.2.0
        Babel                        2.11.0
        backcall                     0.2.0
        beautifulsoup4               4.11.1
        bleach                       6.0.0
        bs4                          0.0.1
        cachetools                   5.3.0
        certifi                      2022.9.24
        cffi                         1.15.1
        charset-normalizer           2.1.1
        comm                         0.1.2
        cssselect                    1.2.0
        debugpy                      1.6.6
        decorator                    5.1.1
        defusedxml                   0.7.1
        et-xmlfile                   1.1.0
        executing                    1.2.0
        fastjsonschema               2.16.2
        flatbuffers                  23.1.21
        fqdn                         1.5.1
        gast                         0.4.0
        google-auth                  2.16.0
        google-auth-oauthlib         0.4.6
        google-pasta                 0.2.0
        grpcio                       1.51.1
        h5py                         3.8.0
        idna                         3.4
        import-ipynb                 0.1.4
        ipykernel                    6.21.1
        ipython                      8.10.0
        ipython-genutils             0.2.0
        ipywidgets                   8.0.4
        isoduration                  20.11.0
        jedi                         0.18.2
        Jinja2                       3.1.2
        joblib                       1.2.0
        json5                        0.9.10
        jsonpointer                  2.3
        jsonschema                   4.17.3
        jupyter_client               8.0.2
        jupyter_core                 5.2.0
        jupyter-events               0.5.0
        jupyter-resource-usage       0.7.0
        jupyter_server               2.2.1
        jupyter_server_fileid        0.6.0
        jupyter_server_terminals     0.4.4
        jupyter_server_ydoc          0.6.1
        jupyter-ydoc                 0.2.2
        jupyterlab                   3.6.1
        jupyterlab-pygments          0.2.2
        jupyterlab_server            2.19.0
        keras                        2.11.0
        Keras-Preprocessing          1.1.2
        libclang                     15.0.6.1
        lxml                         4.9.2
        Markdown                     3.4.1
        MarkupSafe                   2.1.2
        matplotlib-inline            0.1.6
        mistune                      2.0.5
        mysql-connector-python       8.0.32
        nbclassic                    0.4.8
        nbclient                     0.7.2
        nbconvert                    7.2.9
        nbformat                     5.7.3
        nest-asyncio                 1.5.6
        nodejs                       0.1.1
        notebook                     6.5.2
        notebook_shim                0.2.2
        numpy                        1.24.1
        oauthlib                     3.2.2
        openpyxl                     3.1.0
        opt-einsum                   3.3.0
        optional-django              0.1.0
        packaging                    23.0
        pandas                       1.5.3
        pandocfilters                1.5.0
        parsel                       1.7.0
        parso                        0.8.3
        pexpect                      4.8.0
        pickleshare                  0.7.5
        pip                          23.0
        pip-autoremove               0.10.0
        platformdirs                 3.0.0
        prometheus-client            0.16.0
        prompt-toolkit               3.0.36
        protobuf                     3.19.6
        psutil                       5.9.4
        ptyprocess                   0.7.0
        pure-eval                    0.2.2
        pyasn1                       0.4.8
        pyasn1-modules               0.2.8
        pycparser                    2.21
        Pygments                     2.14.0
        pyrsistent                   0.19.3
        pyTelegramBotAPI             4.10.0
        python-dateutil              2.8.2
        python-json-logger           2.0.4
        pytz                         2022.6
        pytz-deprecation-shim        0.1.0.post0
        PyYAML                       6.0
        pyzmq                        25.0.0
        QtPy                         2.3.0
        requests                     2.28.1
        requests-oauthlib            1.3.1
        rfc3339-validator            0.1.4
        rfc3986-validator            0.1.1
        rpy2                         3.5.7
        rsa                          4.9
        scikit-learn                 1.2.1
        scipy                        1.10.0
        Send2Trash                   1.8.0
        setuptools                   63.2.0
        six                          1.16.0
        sniffio                      1.3.0
        soupsieve                    2.3.2.post1
        stack-data                   0.6.0
        tensorboard                  2.11.2
        tensorboard-data-server      0.6.1
        tensorboard-plugin-wit       1.8.1
        tensorflow                   2.11.0
        tensorflow-estimator         2.11.0
        tensorflow-io-gcs-filesystem 0.30.0
        termcolor                    2.2.0
        terminado                    0.17.1
        threadpoolctl                3.1.0
        tinycss2                     1.2.1
        tomli                        2.0.1
        tornado                      6.2
        tqdm                         4.64.1
        traitlets                    5.9.0
        typing_extensions            4.4.0
        tzdata                       2022.7
        tzlocal                      4.2
        uri-template                 1.2.0
        urllib3                      1.26.12
        w3lib                        2.1.1
        wcwidth                      0.2.6
        webcolors                    1.12
        webencodings                 0.5.1
        websocket-client             1.4.2
        Werkzeug                     2.2.2
        wheel                        0.38.4
        widgetsnbextension           4.0.5
        wrapt                        1.14.1
        y-py                         0.5.5
        ypy-websocket                0.8.2
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 2023-02-11 15:23:54.574 ServerApp] Searching ['/home/youwbfacts/.jupyter', '/home/youwbfacts/.local/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2023-02-11 15:23:54.574 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2023-02-11 15:23:54.574 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2023-02-11 15:23:54.575 ServerApp] Looking for jupyter_config in /home/youwbfacts/.local/etc/jupyter
[D 2023-02-11 15:23:54.576 ServerApp] Looking for jupyter_config in /home/youwbfacts/.jupyter
[D 2023-02-11 15:23:54.577 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2023-02-11 15:23:54.577 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2023-02-11 15:23:54.578 ServerApp] Looking for jupyter_server_config in /home/youwbfacts/.local/etc/jupyter
[D 2023-02-11 15:23:54.578 ServerApp] Looking for jupyter_server_config in /home/youwbfacts/.jupyter
[D 2023-02-11 15:23:54.583 ServerApp] Paths used for configuration of jupyter_server_config: 
        /etc/jupyter/jupyter_server_config.json
[D 2023-02-11 15:23:54.584 ServerApp] Paths used for configuration of jupyter_server_config: 
        /usr/local/etc/jupyter/jupyter_server_config.d/jupyter_resource_usage.json
        /usr/local/etc/jupyter/jupyter_server_config.d/jupyterlab.json
        /usr/local/etc/jupyter/jupyter_server_config.d/nbclassic.json
        /usr/local/etc/jupyter/jupyter_server_config.d/notebook_shim.json
        /usr/local/etc/jupyter/jupyter_server_config.json
[D 2023-02-11 15:23:54.588 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/youwbfacts/.local/etc/jupyter/jupyter_server_config.d/jupyter_server_fileid.json
        /home/youwbfacts/.local/etc/jupyter/jupyter_server_config.d/jupyter_server_terminals.json
        /home/youwbfacts/.local/etc/jupyter/jupyter_server_config.d/jupyter_server_ydoc.json
        /home/youwbfacts/.local/etc/jupyter/jupyter_server_config.d/jupyterlab.json
        /home/youwbfacts/.local/etc/jupyter/jupyter_server_config.json
[D 2023-02-11 15:23:54.595 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/youwbfacts/.jupyter/jupyter_server_config.json
[I 2023-02-11 15:23:54.599 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-02-11 15:23:54.620 ServerApp] Package jupyter_resource_usage took 0.0205s to import
[I 2023-02-11 15:23:54.627 ServerApp] Package jupyter_server_fileid took 0.0063s to import
[I 2023-02-11 15:23:54.643 ServerApp] Package jupyter_server_terminals took 0.0151s to import
[I 2023-02-11 15:23:54.712 ServerApp] Package jupyter_server_ydoc took 0.0682s to import
[I 2023-02-11 15:23:54.713 ServerApp] Package nbclassic took 0.0000s to import
[W 2023-02-11 15:23:54.719 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-02-11 15:23:54.720 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-02-11 15:23:54.720 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-02-11 15:23:54.722 ServerApp] jupyter_resource_usage | extension was successfully linked.
[D 2023-02-11 15:23:54.728 FileIdExtension] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue {'update': {'jupyter_resource_usage': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2023-02-11 15:23:54.729 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_resource_usage': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-02-11 15:23:54.730 ServerApp] jupyter_server_fileid | extension was successfully linked.
[D 2023-02-11 15:23:54.735 TerminalsExtensionApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_resource_usage': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2023-02-11 15:23:54.736 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_resource_usage': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-02-11 15:23:54.737 ServerApp] jupyter_server_terminals | extension was successfully linked.
[D 2023-02-11 15:23:54.741 YDocExtension] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_resource_usage': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2023-02-11 15:23:54.742 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_resource_usage': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-02-11 15:23:54.743 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[D 2023-02-11 15:23:54.749 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_resource_usage': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-02-11 15:23:54.750 ServerApp] jupyterlab | extension was successfully linked.
[D 2023-02-11 15:23:54.754 NotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_resource_usage': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-02-11 15:23:54.755 ServerApp] nbclassic | extension was successfully linked.
[D 2023-02-11 15:23:55.094 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/youwbfacts/.jupyter/jupyter_notebook_config.json
[D 2023-02-11 15:23:55.095 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /etc/jupyter/jupyter_notebook_config.json
[D 2023-02-11 15:23:55.096 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /usr/local/etc/jupyter/jupyter_notebook_config.d/jupyter_resource_usage.json
        /usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
        /usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2023-02-11 15:23:55.098 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/youwbfacts/.local/etc/jupyter/jupyter_notebook_config.d/jupyter_server_ydoc.json
        /home/youwbfacts/.local/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
        /home/youwbfacts/.local/etc/jupyter/jupyter_notebook_config.json
[D 2023-02-11 15:23:55.099 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/youwbfacts/.jupyter/jupyter_notebook_config.json
[I 2023-02-11 15:23:55.099 ServerApp] notebook_shim | extension was successfully linked.
[D 2023-02-11 15:23:55.101 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_resource_usage': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook_shim': True}>}}
[I 2023-02-11 15:23:55.415 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-02-11 15:23:55.416 ServerApp] jupyter_resource_usage | extension was successfully loaded.
[I 2023-02-11 15:23:55.417 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-02-11 15:23:55.417 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /home/youwbfacts/Earnings Call_
[I 2023-02-11 15:23:55.417 FileIdExtension] ArbitraryFileIdManager : Configured database path: /home/youwbfacts/.local/share/jupyter/file_id_manager.db
[I 2023-02-11 15:23:55.418 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-02-11 15:23:55.418 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices.
[I 2023-02-11 15:23:55.423 FileIdExtension] Attached event listeners.
[I 2023-02-11 15:23:55.423 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-02-11 15:23:55.424 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-02-11 15:23:55.425 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2023-02-11 15:23:55.425 LabApp] JupyterLab extension loaded from /home/youwbfacts/.local/lib/python3.10/site-packages/jupyterlab
[I 2023-02-11 15:23:55.425 LabApp] JupyterLab application directory is /home/youwbfacts/.local/share/jupyter/lab
[I 2023-02-11 15:23:55.429 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-02-11 15:23:55.440 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-02-11 15:23:55.441 ServerApp] The port 8888 is already in use, trying another port.
[I 2023-02-11 15:23:55.441 ServerApp] Serving notebooks from local directory: /home/youwbfacts/Earnings Call_
[I 2023-02-11 15:23:55.441 ServerApp] Jupyter Server 2.2.1 is running at:
[I 2023-02-11 15:23:55.441 ServerApp] http://localhost:8889/lab?token=b9b4aa010deb61b4601741c6e6c731b6a499112b46c2d0f8
[I 2023-02-11 15:23:55.442 ServerApp]     http://127.0.0.1:8889/lab?token=b9b4aa010deb61b4601741c6e6c731b6a499112b46c2d0f8
[I 2023-02-11 15:23:55.442 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2023-02-11 15:23:55.447 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2023-02-11 15:23:55.447 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/youwbfacts/.local/share/jupyter/runtime/jpserver-40464-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/lab?token=b9b4aa010deb61b4601741c6e6c731b6a499112b46c2d0f8
        http://127.0.0.1:8889/lab?token=b9b4aa010deb61b4601741c6e6c731b6a499112b46c2d0f8
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
ContentDispatcherService: no listeners for an event TAB_STATE__GET_NAVIGATION_METHOD
2content.js:665 ContentDispatcherService: no listeners for an event TAB_STATE__GET_NAVIGATION_METHOD
content.js:716 ContentDispatcherService: no listeners for an event TAB_STATE__GET_NAVIGATION_METHOD

</pre>
</details>

**Comment by krassowski** [comment]
This appears to be related to the issue seen in #13930 (https://github.com/jupyterlab/jupyterlab/issues/13930#issuecomment-1424247367) - maybe one of the workarounds discussed there helps?

**Comment by PashaM999** [comment]
@krassowski deleting `.jupyter-ystore.db` and restarting jupyter like mentioned in the other issue does fix the problem, but after some time the problem reappears anyway. Also, I have found that after jupyter spams the keyerror and you close the broken file it outputs:
```
[I 2023-02-12 10:54:23.307 ServerApp] Processed 100 Y patches in one minute
[I 2023-02-12 10:54:23.308 ServerApp] Connected Y users: 107
```
It seems to me that each error generates a new user, which can't be good :)

**Comment by JasonWeill** [comment]
@PashaM999 Thank you for opening this! It looks like there's an open discussion about this issue in #13930, so let's continue it there.
