### ISSUE TITLE
Interconnecting documentation

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#13984]
Since the introduction of recent RTC changes the core data structures used by JupyterLab live outside of JupyterLab codebase and no longer show up in the typedoc reference. We previously had this problem in lumino/jupyterlab separation but now it is worse. We should ensure that the API for:
- [@jupyter/ydoc](https://github.com/jupyter-server/jupyter_ydoc) (should be interconnected with JupyterLab)
- [@jupyterlab/collaboration](https://github.com/jupyterlab/jupyterlab_collaboration) (maybe should have a simple link from JupyterLab and back?)
- lumino (should be accessible from JupyterLab reference)

are all inter-connected and easily navigable, and have links from the extension migration guide page

For example, today when we navigate to [`Cell` class API](https://jupyterlab.readthedocs.io/en/stable/api/classes/cells.cell-1.html) it references `Widget` as a parent but there is no clickable link to `@lumino/widgets`' `Widget`:

![Screenshot from 2023-02-13 19-32-52](https://user-images.githubusercontent.com/5832902/218555990-c2520e9b-f866-48d0-9391-ddbc07e48cde.png)

and the Cells' [`sharedModel`](https://jupyterlab.readthedocs.io/en/stable/api/interfaces/cells.icellmodel.html#sharedmodel) is defined as:

```
sharedModel: (ISharedCodeCell & ISharedText) | (ISharedRawCell & ISharedText) | (ISharedMarkdownCell & ISharedText) | (ISharedUnrecognizedCell & ISharedText)
```

which is just a wall of interfaces names which cannot be clicked (navigated to) nor googled as the other packages have fresh documentation (which will have a low page rank as it is not linked from other places!)

![Screenshot from 2023-02-13 19-32-11](https://user-images.githubusercontent.com/5832902/218555845-e0dd7a9c-cbc0-42c1-b9a0-501229882da9.png)

@bollwyvl highlighted on gitter that typedoc does support interlinking: [third-party-symbols.md](
https://github.com/TypeStrong/typedoc/blob/c565bc618e4e56d7ea3e73cd0099bf3de9bf76c2/internal-docs/third-party-symbols.md), and as an alternative we could merge the API reference with sphinx using sphinx-js and then just rely on intersphinx.

**Comment by bollwyvl** [comment]
> `third-party-symbols.md`

This would be fine, especially if it resulted in an easily-installable package which downstreams/siblings could use.

>  using sphinx-js and then just rely on intersphinx.

There may be some opportunities to collaborate with the pyodide folks on this path forward:

https://github.com/pyodide/pyodide/issues/3549

An advantage to sticking on the `obejcts.inv` bus: like it or lump it, it's a big enough player that it has implementations for other docs toolchains, such as [mkdocs](https://mkdocstrings.github.io/reference/inventory/).

Being able to reference python classes from typescript and vice versa would be lovely indeed, especially considering other mixed-language docs suites such as `ipywidgets`. But then maybe @krassowski's work on 

A significant disadvantage, of course, is `autodoc` expects`.rst`, which even the myst boffins [haven't solved yet](https://github.com/executablebooks/MyST-Parser/issues/163).
