### ISSUE TITLE
Handle embedded attachments within markdown cells on notebook component

### ISSUE THREAD

**Issue by Analect** [jupyterlab/jupyterlab#1398]
I was trying to get markdown cell attachments (an embedded image) working over [here](https://github.com/jupyter/nbformat/issues/66#issuecomment-262204474), but it turns out it hasn't yet been implemented in the notebook within jupyterlab. Perhaps this is partly covered by #1308 and #902, in which case, feel free to remove this.

Suggested labels: cat:Feature Parity, component:Notebook

**Comment by blink1073** [comment]
This deserves its own issue, thanks!

**Comment by vidartf** [comment]
This will likely depend on jupyterlab/services#288.

**Comment by fuglede** [comment]
The situation is somewhat worse than this, in that JupyterLab actually removes any image attachments from existing Jupyter notebooks. If you fail to notice this before saving such a notebook in JupyterLab, you end up losing data.

**Comment by vidartf** [comment]
I'm currently working on this, just as a heads up.

**Comment by vidartf** [comment]
A fix for the removal attachments, and rendering of attachments is implemented in #4373. Editing attachments (adding and removing unused attachments) will be in another PR after that one is merged.
