### ISSUE TITLE
Emoji used for "enter" in pulldown menu keyboard shortcuts

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#13986]
## Description

In the "Run" menu, an emoji ↩️ is used for the <kbd>ENTER</kbd> or <kbd>RETURN</kbd> key. Other menus use Unicode characters without the emoji indicator codepoint U+FE0F. Other menus use strictly non-emoji Unicode character presentations to render accelerator or other non-alphanumeric keys.

![image](https://user-images.githubusercontent.com/93281816/218588667-4d22c5d5-3a7a-4512-a08f-28ab6218eedc.png)

![image](https://user-images.githubusercontent.com/93281816/218588692-f3c6c2cd-ccb5-4128-a353-70b30a78138b.png)

## Reproduce

1. Open JupyterLab 4.
2. Click the Run pulldown menu.

## Expected behavior

"Enter" appears as a non-emoji character, such as [U+21A9](https://www.cogsci.ed.ac.uk/~richard/utf-8.cgi?input=21A9&mode=hex).

## Context

- Operating System and version: macOS 12.6.3
- Browser and version: Firefox 102.7.0esr
- JupyterLab version: 4.0.0a33

**Comment by krassowski** [comment]
Two quick points:
- I think the code for this lives in lumino
- no need to change character we just need to add `U+FE0E` variant selector
- we may want to use OS-specific characters if those exist

**Comment by andrii-i** [comment]
Curiously, in [binder](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/75ab1750f37b27db8e135c2c4f2139da6b641609?urlpath=lab/tree/demo) linked from jupyterlab/jupyterlab master, I see `Enter` instead of a symbol (I do see emoji locally at head-of-master):

![screen](https://user-images.githubusercontent.com/26686070/218826186-5416edbc-0df3-440f-8ebc-b541974ba83f.png)

**Comment by JasonWeill** [comment]
In Lumino, `Enter` maps to `↩` (which looks like an emoji in the default presentation style on Mac) when the server is running on macOS. See line below.

https://github.com/jupyterlab/lumino/blob/d08b6f71828438dd7bf1ba7f59ea706a95680822/packages/commands/src/index.ts#L1464

**Comment by JasonWeill** [comment]
Closing in favor of https://github.com/jupyterlab/lumino/issues/540.
