### ISSUE TITLE
Shortcut to comment (on international keyboards)

### ISSUE THREAD

**Issue by trueToastedCode** [jupyterlab/jupyterlab#13997]
In the help page it says `⌘ + /`, but this key does not exist on my keyboard (there is of course a shortcut, but it actually writes the dash character):

<img width="567" alt="Bildschirm­foto 2023-02-14 um 11 25 57" src="https://user-images.githubusercontent.com/44642574/218708855-f450a9f6-a374-4fbd-8951-cc8893ffb7ff.png">

So I went down the rabbit hole of testing all kinds of other short cuts that people claimed to have success with... including:
- `⌘ + '`
- `⌘ + #`
- `⌘ + 7`
- `⌘ + ⇧ + 7`
- Tried to edit it in the Edit Shortcut menu (no option for commenting)
- ...

None have worked (except for connecting an external Keyboard that actually has this stupid key). There are like e.g. ~746400000 people in Europe who use this or similar keyboards... how can there not be an option to edit the shortcut. Or is there in option... well I can't find one.

**Comment by krassowski** [comment]
+1 This looks related to https://github.com/jupyterlab/jupyterlab/issues/4778.

**Comment by JasonWeill** [comment]
Closing as duplicate of #4778.
