### ISSUE TITLE
Python icons in Launcher panel are different

### ISSUE THREAD

**Issue by dlqqq** [jupyterlab/jupyterlab#13991]
## Description

The buttons for launching a notebook with the Python kernel and for creating a new Python file both use a Python icon, but they look different. It is best to stick to one or the other to preserve consistency in the UI. This is of special significance given that this is what most users see first when launching JL.

<img width="653" alt="Screen Shot 2023-02-13 at 2 27 59 PM" src="https://user-images.githubusercontent.com/44106031/218595352-d0546d95-4134-4030-8741-0b68fc627f35.png">

## Reproduce

1. Open JupyterLab
2. Observe the Python icons are different

## Expected behavior

The icons should be the same.

## Context

- Operating System and version: OS X Monterey
- Browser and version: Chrome 109.0.5414.119 (Official Build) (x86_64)
- JupyterLab version: [4.0.0a33 binder](https://gist.github.com/jtpio/4e9a3d435d7c3950dc4150c10abbb1d7)

I believe I had discussed this earlier when working on my [CSS PR](https://github.com/jupyterlab/jupyterlab/pull/12673) (now sadly abandoned). If I recall, the Python icons used at the top are actually coming from the kernel and are not hard-coded in the JL frontend. Would appreciate additional context from anybody knowledgable on this.

**Comment by krassowski** [comment]
We were given a green light to use the one shown under "Other" (https://github.com/jupyterlab/jupyterlab/pull/13035#issuecomment-1233626987) so we could update the one in ipykernel for consistency (it was changed to use SVG vs PNG recently but no one notice that this is a different SVG).

**Comment by GabrielaVives** [comment]
Yes the icon under "Other" is best, having drop shadows under icons is not necessary and quite old-fashioned.

**Comment by krassowski** [comment]
@dlqqq if you agree with the suggestion to keep the one from under "Other", shall we close this issue and open one on https://github.com/ipython/ipykernel? If not, shall we bump this issue to 4.2 milestone?

**Comment by dlqqq** [comment]
@krassowski Thanks for checking on this. I agree with the sentiment that the flat icon under "Other" looks the best.

Can you open the issue on `ipython/ipykernel`, and link to it here via a comment? I'll close this issue after you reply with the link of the new issue here.

**Comment by krassowski** [comment]
https://github.com/ipython/ipykernel/issues/1183
