### ISSUE TITLE
strange styling in "Notifications" popup

### ISSUE THREAD

**Issue by dlqqq** [jupyterlab/jupyterlab#13992]
## Description

When clicking the "Notifications" bell on the bottom right, the resultant popup lacks a border and shadow to distinguish it from the background. This hinders usability of the popup as it is not immediately obvious where the popup ends.

<img width="442" alt="Screen Shot 2023-02-13 at 2 41 45 PM" src="https://user-images.githubusercontent.com/44106031/218596436-a6163f2b-2f89-4ede-9c1d-fa1f64876152.png">

## Reproduce

1. Open JupyterLab and click on the bottom right notifications icon.

## Expected behavior

The notifications popup should have a border and shadow to distinguish it from the background.

## Context

- Operating System and version: OS X Monterey
- Browser and version: Chrome 109.0.5414.119 (Official Build) (x86_64)
- JupyterLab version: [4.0.0a33 binder](https://gist.github.com/jtpio/4e9a3d435d7c3950dc4150c10abbb1d7)

**Comment by krassowski** [comment]
I did saw some styling issues (in the dark mode mostly) but what I see in your screenshot is not reproducible for me:

![Screenshot from 2023-02-15 20-49-48](https://user-images.githubusercontent.com/5832902/219154758-489ba190-d875-410b-b8eb-2d21c8c4a41d.png)

We both use the same major version of Chrome (but I use it on Linux). There is something extremely interesting (for a CSS nerds) happening there:

It looks like in your case the background colour gets inherited from body (`background: var(--jp-layout-color3);`), but it should not - it should be greyed out in inspector indicating that it is not actually inherited (as background-color is not an inheritable property):

![Screenshot from 2023-02-15 20-53-17](https://user-images.githubusercontent.com/5832902/219156280-1245987c-806a-4498-8173-fc5f271d629a.png)

**Comment by andrii-i** [comment]
@GabrielaVives would love to hear your opinion on how we could improve notification (center) UIUX.
