### ISSUE TITLE
strange styling of "Jupyter news" notification

### ISSUE THREAD

**Issue by dlqqq** [jupyterlab/jupyterlab#13993]
## Description

The "official Jupyter news" notification styling is strange; link feels like it should belong in the notification body rather than as a separate action button, and the "Please read privacy policy" sentence is preceded by a line break that causes the notification to occupy more vertical space than necessary. Finally, there is a noticeable lack of margin between the notification body and the action buttons below.

<img width="442" alt="Screen Shot 2023-02-13 at 2 41 45 PM" src="https://user-images.githubusercontent.com/44106031/218597113-ca4e9f57-95f7-4902-9e78-f49e24c0c8db.png">

## Reproduce

1. Open JupyterLab and click on the bottom right notifications icon.

## Expected behavior

1. "Please read the [privacy policy](google.com)." should not be preceded by a newline, and should include a direct link to the privacy policy as shown in the rendered markdown.
2. Remove the "Open privacy policy" action button.
3. Add more margin between notification body and its action buttons. 

## Context

- Operating System and version: OS X Monterey
- Browser and version: Chrome 109.0.5414.119 (Official Build) (x86_64)
- JupyterLab version: [4.0.0a33 binder](https://gist.github.com/jtpio/4e9a3d435d7c3950dc4150c10abbb1d7)

**Comment by JasonWeill** [comment]
This only happens when clicking on the notification UI in the bottom-right corner; on initial load, only the inner notification is visible.

**Comment by fcollonval** [comment]
FYI Links cannot be part of the notification text as for security reasons, it was decided notification will be displayed as plain text. Link styled button are common in UI framework, it is used here to highlight that the button will take you to an external URL.

This was implemented in https://github.com/jupyterlab/jupyterlab/pull/13510

**Comment by JasonWeill** [comment]
I also find the "1 notification" styling to be unusual; the outer container has no outer border, while the notification inside the container has a drop shadow.

**Comment by JasonWeill** [comment]
My comment above is already reflected in #13992.

**Comment by JasonWeill** [comment]
There is now a bit of vertical space between the message and the action buttons:

<img width="334" alt="Screenshot 2024-04-24 at 3 58 11 PM" src="https://github.com/jupyterlab/jupyterlab/assets/93281816/ff0d428c-417b-456e-ac1c-d71094826913">

**Comment by JasonWeill** [comment]
Fixed by #16236.
