### ISSUE TITLE
 Maximum call stack size exceeded in dialog/index.js

### ISSUE THREAD

**Issue by dhuebner** [jupyterlab/jupyterlab#1399]
I'm getting "index.js:229Uncaught RangeError: Maximum call stack size exceeded." when working with JL:

index.js:229 Uncaught RangeError: Maximum call stack size exceeded.
Dialog.handleEvent	@	index.js:229
Dialog.handleEvent	@	index.js:229
Dialog.handleEvent	@	index.js:229

...

Unfortunately, I don't know how to reproduce.

**Comment by blink1073** [comment]
Hi @dhuebner, that should have been fixed by https://github.com/jupyterlab/jupyterlab/pull/1271, which was released in version 0.11.2.  You can check your current version as `jupyter lab  --version`.

**Comment by blink1073** [comment]
I'm calling this one fixed, but please feel free to reopen if you disagree.

**Comment by dhuebner** [comment]
@blink1073 Oh, sorry, I was searching for similar issue, but found any. I'm working with 0.11.1. Thanks for the info.
