### ISSUE TITLE
Safari: Can't see the cursor in the empty code cell

### ISSUE THREAD

**Issue by 3coins** [jupyterlab/jupyterlab#14001]
## Description
There is no cursor present in the empty code cell in a notebook. This causes confusion as the cell may be interpreted as not ready for input.

<img width="953" alt="Screen Shot 2023-02-13 at 2 20 43 PM" src="https://user-images.githubusercontent.com/289369/218825463-417501ce-f7a6-428e-b6fe-4a79378c8ce2.png">

## Reproduce
1. Create a new notebook in JupyterLab 
2. Focus on the first code cell with no content 
3. Notice that there is no cursor present
4. Cursor returns when some content is added
5. Deleting the content removes the cursor again

## Expected behavior
Cursor should be seen even when the cell is empty.

## Context
- Operating System and version: macOS 12.6.3
- Browser and version: Safari Version 16.3
- JupyterLab version: [4.0.0a33](https://gist.github.com/jtpio/4e9a3d435d7c3950dc4150c10abbb1d7)

**Comment by JasonWeill** [comment]
Doesn't repro in Firefox.

**Comment by JasonWeill** [comment]
Also doesn't repro in Chrome.

**Comment by JasonWeill** [comment]
Check again on Safari 16.4?

**Comment by JasonWeill** [comment]
Another cursor issue in Firefox: #14271

**Comment by krassowski** [comment]
@3coins can you check again on Safari with beta1? We merged a new extension to display cursors so it could be already fixed.

**Comment by 3coins** [comment]
@krassowski 
Thanks for keeping track of this. Verified on Safari, this issue is not present with beta1. Closing the issue.
