### ISSUE TITLE
click on code cell scrolls to top of cell in v3.4.5

### ISSUE THREAD

**Issue by blazespinnaker** [jupyterlab/jupyterlab#14016]
## Reproduce
When I click on a code cell it will *sometimes* auto scroll to the top of the cell.  This is very inconsistent and disruptive. I notice this behavior happens more when I have longer notebooks opened in jupyterlab.  

It can take a minute or two before it will finally work, though as a workaround I can use the up/down keys to get it to where I want it to go.

## Expected behavior

Cursor should go to where I mouse click.

## Context

Chromebook / Version 109.0.5414.94 (Official Build) (64-bit)
- JupyterLab version: 3.4.5

<details><summary>Troubleshoot Output</summary>

I really wanted to do this, but it outputs waaaay too much info that I'm comfortable with sharing on the public web.   
<pre>

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

Nothing showing up in console.
<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
@blazespinnaker Thanks for opening this issue! JupyterLab 3.4.5 is an older minor version; are you able to upgrade to JupyterLab 3.6.1, and if so, do you still see this behavior?

Also, are you running any content blocker or content manipulation extensions (e.g., ad blockers)? Do you see the same behavior with those extensions disabled?

**Comment by blazespinnaker** [comment]
Thanks! I've upgraded, will report back.

**Comment by blazespinnaker** [comment]
Happy to report the issue has gone away with the upgrade.   Thanks!

**Comment by JasonWeill** [comment]
Thank you for the update!
