### ISSUE TITLE
Clicking CodeMirror tile or accordion in Settings Editor breaks rightmost section of Settings Editor

### ISSUE THREAD

**Issue by andrii-i** [jupyterlab/jupyterlab#14011]
## Description

Clicking CodeMirror tile or accordion in Settings Editor breaks rightmost section of Settings Editor: white screen instead of rightmost section of Settings Editor (where accordions usually are) for CodeMirror or for other sections

## Reproduce

1. Open Settings Editor
2. Click on CodeMirror tile or accordion

![CodeMirror](https://user-images.githubusercontent.com/26686070/218912771-6b256463-068f-4015-b768-50e35bd55dcb.gif)

## Expected behavior

Click on CodeMirror tile or accordion doesn't break things

## Context

Operating System and version: MacOS 12.6.3
Browser and version: Chrome version 109.0.5414.87 (Official Build) (arm64)
JupyterLab version: head-of-master (WIP 4.0.0)

**Comment by JasonWeill** [comment]
I couldn't repro; try clearing your custom settings in the JSON settings editor, or try in a clean version of JupyterLab

**Comment by krassowski** [comment]
I am able to repro this reliably on tip of the master and on `4.0.0a34`. This will be fixed by #13639
