### ISSUE TITLE
ssh remote connection still shows notebook

### ISSUE THREAD

**Issue by ggrrll** [jupyterlab/jupyterlab#14013]
## Description

I am trying to run the lab remotely, but it still shows the notebook GUI

## Reproduce

locally
`ssh  -L localhost:8888:localhost:8890  user@hostIP`

remotely
`jupyter lab --no-browser --port=8890 &`

## Expected behavior

lab GUI

## Context

- Operating System and version:  Ubuntu 20.04 
- JupyterLab version: 3.6.1

**Comment by JasonWeill** [comment]
This was fixed in an older version of Jupyter Server in #9575.

What Jupyter Server version are you running? You can find out by running `jupyter --version` on the command line where you run `jupyter lab`.

**Comment by JasonWeill** [comment]
What URL are you hitting to access this JupyterLab instance? If you go to `/tree`, you will go to the Jupyter Notebook UI, but if you go to `/lab`, you will go to JupyterLab. (Both UIs are available inside JupyterLab.)
