### ISSUE TITLE
How to change environments in jupyter-lab GUI (GCP)

### ISSUE THREAD

**Issue by innat** [jupyterlab/jupyterlab#14014]
This is more like similar to this https://stackoverflow.com/questions/69529374/conda-environment-not-showing-in-jupyterlab-desktop

Env can be changed from terminal as usual but openning a notebook, it opens with base environment.

**Comment by JasonWeill** [comment]
@innat Thank you for your issue! Are you using JupyterLab or [JupyterLab Desktop](https://github.com/jupyterlab/jupyterlab-desktop/) to connect to your GCP instance? The StackOverflow thread you linked refers to JupyterLab Desktop.

**Comment by innat** [comment]
I'm using jupyter lab from GCP (no desktop), from notebook API.

**Comment by innat** [comment]
Some context.

no gui/options to select conda environment.
<img src="https://user-images.githubusercontent.com/17668390/219476059-d18bbfcd-75ef-42e7-a6e9-15f0cf51d351.png"  width="300" height="100"> <img src="https://user-images.githubusercontent.com/17668390/219476149-e42b1dc2-425e-437b-bdd7-4587c9fcc224.png"  width="300" height="100">

but, it can be viewed and changed from terminal.
 <img src="https://user-images.githubusercontent.com/17668390/219476296-66fe5c99-bea0-4894-8b47-61c3e49c98a5.png"  width="300" height="100">

So, I can run a script from terimial with target environment, but if I create any notebook, it starts from base.

**Comment by fcollonval** [comment]
@innat you can give a try at https://github.com/Anaconda-Platform/nb_conda_kernels

**Comment by innat** [comment]
install the following two command and reset the notebook api but doesn't find any changes. (Please note, I'm using jupyter-lab in GCP.)

```
# running from base env.
conda install -n tf_2_11 nb_conda_kernels # tf_2_11 is the name of conda env
conda install -n tf_2_11 ipykernel
```

**Comment by JasonWeill** [comment]
@innat This project manages the open source JupyterLab code. It looks like the GCP UI you're using is maintained by Google. You might want to follow up with GCP support or your admin to get this added.

(Disclosure: I work for AWS, a competitor of GCP.)

**Comment by innat** [comment]
Does jupyter-lab have the UI interface to interact with available conda environments? If it has, then the issue is not about GCP but otherwise.

**Comment by JasonWeill** [comment]
@innat Try using these two projects to add a conda environment selector to JupyterLab:

* https://github.com/Anaconda-Platform/nb_conda_kernels
* https://github.com/Quansight/conda-store

**Comment by innat** [comment]
I tried nb_conda_kernel, suggested by @fcollonval, unfortunately didn't see any effect. I will check conda-store. However, it would be inconvinient if such UI selection doesn't come by default.

**Comment by innat** [comment]
I think it is not issue in GCP side. The same issue was asked https://discourse.jupyter.org/t/how-to-change-a-virtual-environment-while-using-jupyter-lab/11470/8

I like to know, Does jupyter-lab have interface within UI to interact the available conda environment? And I don't see any effect with the above two git resource, would you please elaborate (if you try in your side) and share the screenshot for visual understanding. Thanks.

**Comment by krassowski** [comment]
> Does jupyter-lab have the UI interface to interact with available conda environments.

No. JupyterLab Desktop has. Extensions as listed above add such UI. Core JupyterLab does not.

However JupyterLab does have a way to interact with kernels from arbitrary environments if those are registered using [kernel specs](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs).

**Comment by krassowski** [comment]
> However JupyterLab does have a way to interact with kernels from arbitrary environments if those are registered using [kernel specs](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs).

If you expect to see your environment in the kernel list that you show on this screenshot:

![image](https://user-images.githubusercontent.com/5832902/221364731-dbd5c349-1f3e-4c85-a0cf-3a3653ea1ebf.png)

You need to register the kernel spec. As JupyterLab does not know about your environments it has to be implemented either by yourself or in GCP.

**Comment by fcollonval** [comment]
@innat `nb_conda_kernels` needs to be install in the environment from which you are executing JupyterLab; not in each Python environment.
