### ISSUE TITLE
More granular `notifyCommandChanged` in the debugger extension

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14023]
# Description

Follow-up to https://github.com/jupyterlab/jupyterlab/pull/13915

This logic seems to be triggering commands regardless whether the plugin is available or activated on the page.

Spotted downstream in Notebook 7, which does not include the command to inspect variables (`@jupyterlab/debugger-extension:variables`):

![image](https://user-images.githubusercontent.com/591645/219375471-e127e33d-544f-46c1-9556-ee11db35d712.png)

# Expected Behavior

Each plugin should probably be responsible for notifying its own set of commands, since some plugins can be deactivated or simply not available in other applications (for example Notebook 7).

# Additional Context
_Originally posted by @jtpio in https://github.com/jupyterlab/jupyterlab/pull/13915#discussion_r1108463072_

**Comment by bollwyvl** [comment]
It would also be _frigging rad_ if it the debugger didn't take the default "hard reload" keyboard shortcut until it was activated.
