### ISSUE TITLE
Tab complete is duplicating text 

### ISSUE THREAD

**Issue by LinuxIsCool** [jupyterlab/jupyterlab#14054]
## Description
![image](https://user-images.githubusercontent.com/31582215/220209692-1d9138a1-7650-478e-9f28-8c411ded59a1.png)

When I tab complete, then the text I have already written is duplicated.

In the above screenshot, I used tab complete at `pm.O` after typing the `O`. 

## Reproduce
Run jupyterlab 3.6.1 and tab complete suggestions using tab.

## Expected behavior

Normal tab complete.

## Context

- Operating System and version: OS: Pop!_OS 22.04 LTS
- Browser and version: Mozilla Firefox 110.0
- JupyterLab version: 3.6.1

**Comment by LinuxIsCool** [comment]
I tried on version 3.6.0 and everything works fine.

**Comment by krassowski** [comment]
This looks like: https://github.com/ipython/ipython/issues/13935 which was already fixed but new version was not released yet.
Did you downgrade to 3.6.1 or did you check in a different environment?

**Comment by LinuxIsCool** [comment]
I downgraded to 3.6.0.

**Comment by krassowski** [comment]
What is your IPython version? Do you have jedi disabled?

**Comment by LinuxIsCool** [comment]
I downgraded to 3.6.0.

**Comment by LinuxIsCool** [comment]
ipython==8.10.0

I don't know anything about disabling jedi.

**Comment by JasonWeill** [comment]
You can disable jedi by running `%config IPCompleter.use_jedi = False` inside a cell. With IPython 8.8.0 and jedi disabled, I see this bug. With IPython 8.8.0 and jedi enabled, the bug is not present.

If you disable jedi, does the behavior change?

**Comment by JasonWeill** [comment]
@LinuxIsCool Any update on whether the behavior recurs if you disable jedi? Thanks!

**Comment by krassowski** [comment]
I believe this was fixed in IPython 8.11. if the issue persists please open a new report in the IPython repository.
