### ISSUE TITLE
User facing changelog for 4.0

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14060]
### Problem

When JupyterLab 4.0 final (or beta) will be release, end users might want to know about the new features and fixes in this version.

However reading the whole changelog page can be really daunting and sometimes PR titles do not always describe changes well.

Currently the Changelog page in the docs doesn't mention higher level items and user facing changes for `4.0`:

![image](https://user-images.githubusercontent.com/591645/220301392-c7e330a9-a81c-4249-8017-2944f39f1752.png)

As a comparison the `3.0` release had a summary of user and developer facing changes at the top of the changelog:

![image](https://user-images.githubusercontent.com/591645/220301528-899d3158-1d76-4c54-a4b5-deec05beebfa.png)

### Proposed Solution

We should manually compile a changelog of user and developer facing changes that landed in 4.0 at the top of the changelog under the `v4.0` heading. Some items to mention:

- Link to the extension migration guide: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#jupyterlab-3-x-to-4-x
- RTC
- CodeMirror 6
- Accessibility improvements
- Performance improvements
- PyPI extension manager
- Improvements to some existing components (Table of contents, file browser, debugger...)
- Possibly add screenshots of some changes
- Notebook 7 and the classic notebook

### Additional context

This is relevant for https://github.com/jupyterlab/jupyterlab/issues/9647

**Comment by jtpio** [comment]
As a follow-up to https://github.com/jupyterlab/jupyterlab/issues/12115 and https://github.com/jupyterlab/jupyterlab/pull/14070 we should also add a section about the Classic Notebook not being installed with JupyterLab by default anymore.

There should be a link to https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html where we could expand on the documentation.

**Comment by fcollonval** [comment]
A document has been started there: https://hackmd.io/MRJvGbyRTyKvqNAdoLCA-w

**Comment by jtpio** [comment]
> A document has been started there: https://hackmd.io/MRJvGbyRTyKvqNAdoLCA-w

Oh nice! How about opening a PR so it can already be visible in the documentation?

**Comment by JasonWeill** [comment]
I can help copy edit the doc linked above.

**Comment by jtpio** [comment]
> Oh nice! How about opening a PR so it can already be visible in the documentation?

I'm putting up a PR
