### ISSUE TITLE
"Would you like to receive official Jupyter news?"

### ISSUE THREAD

**Issue by vgoklani** [jupyterlab/jupyterlab#14065]
How do I stop this message from showing up?

Already asked on Stackoverflow, but no one is responding:

https://stackoverflow.com/questions/75511508/how-to-stop-this-message-would-you-like-to-receive-official-jupyter-news

**Comment by JasonWeill** [comment]
Per [this comment](https://github.com/jupyterlab/jupyterlab/issues/13969#issuecomment-1427096102), you can disable the announcement extension by running:

```
jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
```

**Comment by sisrfeng** [comment]
> jupyter labextension disable "@jupyterlab/apputils-extension:announcements"

permission denied.

If I add `sudo` , it seems to use the root's /bin/jupyter.
