### ISSUE TITLE
Allow single-click navigation in the file browser

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14071]
### Problem

Users coming from the Classic Notebook might be used to browsing files using single click actions instead of what JupyterLab currently provides with the double-click.

### Proposed Solution

There could be a new setting in the file browser extension to allow browsing files with a single click.

This would be disabled by default so the current JupyterLab behavior does not change.

But the setting would allow end users and downstream applications reusing the file browser like Notebook 7 to turn that option on by default if they want to.

### Additional context

This would also help with https://github.com/jupyter/notebook/issues/6397.

This was originally brought by @fperez in https://github.com/jupyter/notebook/issues/6396

Posting the content of the original issue here for reference:

> 
> As I mentioned in #6397, I _think_ that for users who come from Classic to the Lab-based toolchain but are looking for a similar experience, the switch from single- to double-click behavior in the file manager is going to be jarring.
> 
> So I would like to have this issue for discussion of the problem, though I know this is a tricky one. Other aspects of UX parity I think are straightforward and simply a matter of implementation.
> 
> The pro argument is consistency with transition from Classic, the con one is that this really would be a big break with the behavior of Lab... I just checked what VSCode does, and it has an interesting behavior that I actually think works well (though it has an annoying inconsistency): single click opens files in a quick preview mode, but you need to double-click to leave it permanently open for editing.
> 
> The inconsistency in vscode is that _some_ file types (like PDFs) do stay open on single click, I think the distinction is whether the file is editable or not.
> 
> I'm leaning towards the view that a more consistent version of the vscode behavior could be a good solution across Retro and Lab:
> 
>     * single click does something useful immediately:
>       
>       * in Retro it fires a new tab (like Classic)
>       * in Lab it opens the file in a quick preview mode (i.e. no kernel for notebooks, no render for markdown, etc). If the user clicks on a different file, it previews that one in the same tab, so the single-click action can be used to quickly "scan" a folder with many files.  A file opened for preview with a single click becomes "fully active" if the user edits it while they had it open in the preview tab.
> 
>     * Double-click works like it does today in Lab, no change there, and can also work the same for Retro, to help with consistency.
> 
> 
> A bit controversial perhaps, and would need discussion in Lab as well, obviously, but I'm warming up to this as both a good transition option for Classic -> Retro in a critical part of the UX, and actually an improvement to the Lab UX (to this day I still don't like the double-click behavior of Lab, TBH).
> 
> Obviously something could be implemented here independent of Lab, but I think we should consider these decisions holistically to provide as smooth as possible an experience from classic to retro to lab.
> 
> This is also relevant to our work in [berkeley-dsep-infra/datahub#2422](https://github.com/berkeley-dsep-infra/datahub/issues/2422).

**Comment by jtpio** [comment]
Adding to `4.0` and tagging as "Help Wanted" in case someone has time to look into this. Thanks!

**Comment by jtpio** [comment]
The double-click logic seems to be handled here: 

https://github.com/jupyterlab/jupyterlab/blob/3ecf75ac8eda5f11e55f318658577bba227ecdf6/packages/filebrowser/src/listing.ts#L1148-L1187

Maybe this would require handling some of the logic in `_evtMousedown` if that setting is enabled:

https://github.com/jupyterlab/jupyterlab/blob/3ecf75ac8eda5f11e55f318658577bba227ecdf6/packages/filebrowser/src/listing.ts#L962-L1010

**Comment by ellisonbg** [comment]
I can see how this will be challenging for users coming from notebook 6, but equally challenging to address. The challenge is that in Lab the file browser has other interactions that rely on single click (selection, multiple selection, drag/drop). Let's explore though and see what we can come up with.

**Comment by jtpio** [comment]
cc @trungleduc in case you would be interested in porting the feature from Voila here: https://github.com/voila-dashboards/voila/pull/1374

Thanks!

**Comment by trungleduc** [comment]
> cc @trungleduc in case you would be interested in porting the feature from Voila here: [voila-dashboards/voila#1374](https://github.com/voila-dashboards/voila/pull/1374)
> 
> Thanks!

Yes, it's on my plan.

**Comment by krassowski** [comment]
Closing as this was implemented in https://github.com/jupyterlab/jupyterlab/pull/16598
