### ISSUE TITLE
Dialogs have unreadable colour of links in dark mode

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14084]
## Description

1. This link is unreadable for me:

![Screenshot from 2023-02-25 18-53-46](https://user-images.githubusercontent.com/5832902/221374734-076d44ce-aae4-49fb-8d14-647b868a7d39.png)

2. This link is funny on hover:

![Screenshot from 2023-02-25 18-58-11](https://user-images.githubusercontent.com/5832902/221374848-3264285f-d7a9-445e-a2a2-409e174ec440.png)

Relevant code parts were touched in #11827

The problem here is that `.jp-Dialog-content a:hover` has higher precedence. 

## Reproduce

1. Open command palette in a notebook
2. Select "trust notebook"
3. See the unreadable link in popup

for the other  one go to Help menu → About

## Expected behavior

1. The links in dialog are readable in dark mode and use `var(--jp-content-link-color)` by default
2. The flat orange button white colour on `:hover`

## Context

- JupyterLab version: 4.0.0a30

**Comment by AdityaGirdhar** [comment]
@krassowski Hi! I have a university break starting from next week and I'd love to contribute. When can I get started, and what exactly do I have to do?

**Comment by krassowski** [comment]
@AdityaGirdhar no need to ask for permission - feel free to start right away (we do not assign "good first issues") - please just read our [contributing documentation](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html) and open a draft PR when ready.

**Comment by JasonWeill** [comment]
Even in light mode, the red background of links on hover is very jarring and low contrast:

![image](https://user-images.githubusercontent.com/93281816/226422312-ad805280-7916-4ac5-856f-7ac0660c17cb.png)
