### ISSUE TITLE
Switching pages in extension manager "Discover" section resets its size

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14088]
## Description

When switching pages in extension manager "Discover" section, the "Discover" section height gets reset:

![extension-panel-jumps-discover](https://user-images.githubusercontent.com/5832902/221425113-5f165cc8-ad87-44ed-9e36-ea2f5e86e95d.gif)

## Reproduce

As on the gif above

## Expected behavior

The height remains as set by the user.

## Context

- JupyterLab version: 4.0.0a34

**Comment by FoSuCloud** [comment]
When updating data, it is necessary to maintain the height set by the user. Does it need to maintain the height set by the user after the browser is refreshed?

**Comment by FoSuCloud** [comment]
For this bug, I think it is only necessary to maintain the height set by the user when updating the data.
Don't need to keep user set height after browser refresh right

**Comment by krassowski** [comment]
> For this bug, I think it is only necessary to maintain the height set by the user when updating the data.
> Don't need to keep user set height after browser refresh right

Yes.
