### ISSUE TITLE
Highlighting on search shows the searched match twice

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14089]
## Description

When `Search Selected Cell(s)` is enabled and we progressively select cells the search phrase in markdown cells ends up rendered twice

## Reproduce

1. Create a markdown cell with:
  ```markdown
  # The Lorenz Differential Equations
  ```
2. Render it
3. Follow steps from gif below

![duplicated-highlight-bug](https://user-images.githubusercontent.com/5832902/221437847-03accd1d-1645-4694-b5f0-5bf5b6790c85.gif)

See incorrect "LoreLorenz" text which also persists in some other buggy code paths:

![Screenshot from 2023-02-26 21-19-18](https://user-images.githubusercontent.com/5832902/221437907-1ef9eec4-445a-4fa5-9054-3b95b8100843.png)

## Expected behavior

Does not duplicate

## Context

- JupyterLab version: 4.0.0a34 probably dating back to the search refactor before windowed notebooks were introduced

**Comment by krassowski** [comment]
Also reproducible when:
- changing lettercase case to lowercase
- changing from heading to ordinary text
- moving `Lorenz` to separate line

However quoting does help (`# The "Lorenz" Differential Equations` works).

**Comment by JasonWeill** [comment]
@krassowski Can you still reproduce this on Lab 4.1.1? I just tried to search in 1 selected cell, then 2 selected cells, then render an unrendered markdown cell, and I don't see duplicate rendering when I rerender the markdown cell with SHIFT+ENTER.

**Comment by JasonWeill** [comment]
Still not seeing this on tip of `main` after trying again. Closing this issue.
