### ISSUE TITLE
Jupyter Conda Tab Missing on Raspbian/RPI3

### ISSUE THREAD

**Issue by roryw10** [jupyterlab/jupyterlab#1409]
Hi - ok so i understand that conda / miniconda packages are not fully supported on the RPI. Im running an RPI3 and ive managed to get 90% of what i need on here however when i run a jupyter notebook i don't get the conda tab which is making it tricky to set my environment.

I have come across a couple of others on google who had a missing conda tab however non of the suggested fixes work. Is this something i'm going to have to live with or am i missing a trick here?

Thanks

**Comment by blink1073** [comment]
Hi @roryw10, the Conda tab only appears when running the "classic" notebook (as `jupyter notebook`).  We do not yet have support for it in JupyterLab.  Are you also not seeing it when running the classic notebook?  If so, you can try `conda install nb_conda_kernels`?

**Comment by roryw10** [comment]
Hi @blink1073 thanks for getting back to me - i won't have access to my hardware for a week due to personal commitments but i will get on this as soon as i'm back!

I did try and install the kernels but i was having some issues getting it to work - again i can investigate more next week. 

Thanks again
