### ISSUE TITLE
Feedback: Using same minHeight & maxHeight in HoverBox.setGeometry

### ISSUE THREAD

**Issue by nishikantparmariam** [jupyterlab/jupyterlab#14093]
### Problem

I am building a JupyterLab extension where I wanted to render a fixed height widget. While using [HoverBox.setGeometry](https://github.com/jupyterlab/jupyterlab/blob/69437aa3a14d6f7e2dda41ee767eff13e86c1557/packages/apputils/src/hoverbox.ts#L122) method to set geometry of my widget, I noticed that my widget was not rendered even after calling `.show()` and [HoverBox.setGeometry](https://github.com/jupyterlab/jupyterlab/blob/69437aa3a14d6f7e2dda41ee767eff13e86c1557/packages/apputils/src/hoverbox.ts#L122) method - so I started debugging and looking into this method's source code.

I realised that I was passing the same value for [`minHeight`](https://jupyterlab.readthedocs.io/en/stable/api/interfaces/apputils.hoverbox.ioptions.html#minheight) and [`maxHeight`](https://jupyterlab.readthedocs.io/en/stable/api/interfaces/apputils.hoverbox.ioptions.html#maxheight) and below code assumed that the widget is not within bounds because of the **strict greater than check** :

https://github.com/jupyterlab/jupyterlab/blob/69437aa3a14d6f7e2dda41ee767eff13e86c1557/packages/apputils/src/hoverbox.ts#L166-L174

### Proposed Solution

We should:
- Allow for `minHeight` being equal to `maxHeight`
- Or, update the documentation to reflect that `maxHeight` must be strictly greater than `minHeight` for setGeometry to work.
- Or, throw an error if `minHeight` is greater than or equal to `maxHeight`, so that developer knows.

Open for thoughts! Would be happy to open a PR.

### Workaround

I have worked around in this case by passing a strictly lesser value for `minHeight`, so this is not a blocker for me. Creating this issue as a feedback so anyone else does not run into this in future.

**Lab version: 3.6.1** (but this is true in master as well)

**Comment by JasonWeill** [comment]
@nishikantparmariam Thank you for filing this enhancement! This issue has passed our triage process. Please feel free to file a pull request if you have a fix for this. Please also reach out (either here, or in our [other community channels](https://jupyter.org/community)) if you need help.
