### ISSUE TITLE
File unreferencable，please help

### ISSUE THREAD

**Issue by greyhat2022** [jupyterlab/jupyterlab#14108]
When I use pygmt to reference txt text in the jupyter lab, the files appear to be occupied by temp files. I tried to close the temp file, but it showed that it had already been opened by python. It's no use restarting the computer. What should I do next to solve this problem?
The temp file name is pygmt-jui09nuv.csv and appears to be created by Microsoft Excel.

**Comment by greyhat2022** [comment]
Recently I have updated office2019 to 2021, and I think this should have something to do with it.

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\21268\\AppData\\Local\\Temp\\pygmt-jui09nuv.csv'

**Comment by davidbrochart** [comment]
@greyhat2022 You haven't filled the issue template, but it's useful to try and reproduce the issue.

**Comment by davidbrochart** [comment]
Did you fix your issue?
