### ISSUE TITLE
Jupyter Lab v3.2.1 not compatible with Edge v110.0.1587.57 (x64)

### ISSUE THREAD

**Issue by hyjforesight** [jupyterlab/jupyterlab#14103]
## Description

Hello Jupyter,
Recently, Microsoft pushed updates for Edge. Since then, when I run Jupyter Lab v3.2.1 on Edge v110.0.1587.57, I found that every move became very slow. For example, it took around 10s for typing one letter in the code cells. Scrolling the page got a big lag. I submitted this issue to Microsoft and they told me it was because Jupyter Lab was not compatible with this version of Edge.
BTW, I tried Chrome. Jupyter Lab works fine on it.
Thanks!
Best,
Yuanjian  

## Reproduce

1. Run Jupyter Lab v3.2.1 on Edge v110.0.1587.57
2. Type in your codes.

## Expected behavior

should be very smooth

## Context

- Operating System and version: Win11 22h2 x64
- Browser and version: Edge v110.0.1587.57 (x64)
- JupyterLab version: v3.2.1

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
This is an older version of JupyterLab; the newest officially supported versions are in the 3.6.x range. Can you upgrade to a newer JupyterLab version and try again, please?

**Comment by JasonWeill** [comment]
@hyjforesight Can you try a newer version of JupyterLab and report back, please? Thanks!

**Comment by hyjforesight** [comment]
Hello @JasonWeill 
Sorry for the late response. Yes, it works.
Thanks!
