### ISSUE TITLE
Undo is broken with JupyterLab `4.0.0a35`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14113]
## Description

Undo is broken with JupyterLab `4.0.0a35`. This is also the case on the latest `master`: d4a9710eb102ce3a44c2bd4209035f1d504b0f92

Meaning it's not possible to undo any changes.

Using stock JupyterLab in normal mode without extensions, no RTC.

## Reproduce

- Open the latest `4.0.0a35` pre-release on Binder: https://gist.github.com/jtpio/4e9a3d435d7c3950dc4150c10abbb1d7
- Create a notebook
- Make some changes
- Try to undo (Ctrl - Z or via the menu entry)

![image](https://user-images.githubusercontent.com/591645/222529778-bc31f074-c391-43cd-a8b5-468ce10191f9.png)

## Expected behavior

Undoing changes should work in both RTC and non-RTC modes.

**Comment by jtpio** [comment]
cc @fcollonval @hbcarlos who might if this will be fixed by https://github.com/jupyterlab/jupyterlab/pull/14063

**Comment by JasonWeill** [comment]
I also saw this yesterday.
