### ISSUE TITLE
Non-executable files with shebangs

### ISSUE THREAD

**Issue by frenzymadness** [jupyterlab/jupyterlab#14131]
This "problem" has been uncovered by linters for RPM packages during the packaging of Jupyterlab for Fedora Linux.

The reported problem is that `jupyterlab/staging/yarn.js` and `jupyterlab/node-version-check.js` both have shebang lines `#!/usr/bin/env node` but they are not executable.

Should we remove the shebangs or make the scripts executable?

**Comment by JasonWeill** [comment]
@jtpio @fcollonval Any suggestions on whether to remove the shebang lines or to make these files executable?

**Comment by fcollonval** [comment]
> in https://github.com/jupyterlab/jupyterlab/pull/13875 yarn.js rights have been updated to 755.
