### ISSUE TITLE
"This action is restricted" Internet Explorer dialog when starting JupyterLab in Windows with no default browser

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#14142]
## Description

On a Windows 10 computer with Firefox set as the default browser, running `jupyter lab` causes a dialog box to appear: "Internet Explorer / This action is restricted. For more information, please contact your system administrator."

![ie-popup](https://user-images.githubusercontent.com/93281816/223282642-4bfef503-efaf-4720-9eec-f38a4ddd89b1.png)

After I dismiss the dialog, Microsoft Edge pops up with the JupyterLab URL specified in the terminal.

On this Windows machine, there is no default browser set.

![image (4)](https://user-images.githubusercontent.com/93281816/223282666-4c25c01c-2404-4eb4-8623-dd61cf1678ba.png)

## Reproduce

1. Set up a new Windows 10 machine with no default browser.
2. Install JupyterLab via Conda (`conda install jupyterlab`).
3. Run JupyterLab from the terminal (`jupyter lab`)
4. See behavior shown above.

## Expected behavior

If no default browser is selected, the `jupyter` executable does not attempt to launch any browser, but instead displays the URL to load with no further action. This would be similar behavior to when the user runs `jupyter lab` with the `--no-browser` parameter.

## Context

- Operating System and version: Windows 10 Enterprise version 21H2 (19044.2486)
- Browser and version: Edge and Firefox installed; none set as default
- JupyterLab version: 3.5.3

**Comment by krassowski** [comment]
Opening browser is not handled by JupyterLab codebase but implemented in jupyter-server via `open_browser` traitlet/[`launch_browser` method](https://github.com/jupyter-server/jupyter_server/blob/45135278e895fec454e8bad7006f51b82b53a7b3/jupyter_server/serverapp.py#L2751-L2772) which basically uses built-in `webbrowser` package. What does the following snippet return in your Windows environment:

```python
import webbrowser
webbrowser.get()
```

?

**Comment by krassowski** [comment]
So this looks like a genuine "bug" in cPython - it only checks [whether the executable is available](https://github.com/python/cpython/blob/54060ae91da2df44b3f6e6c698694d40284687e9/Lib/webbrowser.py#L550), not whether it has permissions to execute. I guess you could report that in Python bug tracker.

**Comment by JasonWeill** [comment]
Closing in favor of CPython issue linked above.
