### ISSUE TITLE
Inject cell renderers (instead of creation in the constructor)

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#1414]
It would be better if cell renderers passed from outside, e.g [here](https://github.com/jupyterlab/jupyterlab/blob/master/src/notebook/notebook/widget.ts#L566). Otherwise one does not have any way to replace them except providing a completely new Renderer.

We used to compose existing renderers, now we have to have our own renderers just to replace cell renderers.

**Comment by blink1073** [comment]
Sounds fair.

**Comment by ellisonbg** [comment]
Is this the same `Renderer` stuff we are going to rename in #905 ? If so we should do all that cleanup at once.

**Comment by blink1073** [comment]
Yep, sounds good.
