### ISSUE TITLE
CI does not run after update snapshots push from jupyter bot

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14154]
As seen in https://github.com/jupyterlab/jupyterlab/pull/13861 the GitHub Actions CI jobs do not run after commit pushed by the bot:

![Screenshot from 2023-03-07 17-54-01](https://user-images.githubusercontent.com/5832902/223507891-2de40471-67f1-48d7-a02c-c6d061e1e0e4.png)

whereas the expected numbers of jobs is ~80:

![Screenshot from 2023-03-08 17-40-23](https://user-images.githubusercontent.com/5832902/223789859-eb564a51-705a-4645-87eb-eb2612c86ac7.png)

this is a permission issue on technical side and an issue which causes a maintenance problem on the other.

As discussed on today's meeting we will enable branch protection rule requiring the lint job to pass to mitigate this.

**Comment by jtpio** [comment]
Yeah this has been the case for quite a while indeed, also reported in https://github.com/jupyterlab/jupyterlab/issues/13505. Happy to close https://github.com/jupyterlab/jupyterlab/issues/13505 in favor of this one btw.

And it's also the case on other repos using the update snapshot workflow, for example: https://github.com/jupyter/notebook

**Comment by krassowski** [comment]
Closing in favour of older #13505 which has a bit more context on previous attempts to fix it.
