### ISSUE TITLE
Jupyterlab Desktop Application doesn't launch

### ISSUE THREAD

**Issue by RJ15293** [jupyterlab/jupyterlab#14164]
When trying to open Jupyterlab desktop app. It doesn't open at all. It crashes right away. I checked event logs and nothing is there. It acts like it does nothing when trying to open. I have reinstalled multiple times and tried conda navigator. I have tried launching from the command line as well and nothing happens. Please advise. This started when I got the latest update and others I work with are experiencing the same issue.

**Comment by JasonWeill** [comment]
@RJ15293 Thanks for your contribution! JupyterLab Desktop has its own repo on GitHub. Can you please check the list of issues here — https://github.com/jupyterlab/jupyterlab-desktop/issues/ — and, if you don't find an existing issue, open a new one there?
