### ISSUE TITLE
Show Line Numbers or Auto Closing Brackets do not work

### ISSUE THREAD

**Issue by ML-Mr-J** [jupyterlab/jupyterlab#14179]
## Description

Show Line Numbers or Auto Closing Brackets and so on in jupyterlab toolbar <settings> do not work.
It may cause from ：
Could not destroy zmq context for <jupyter_client.asynchronous.client.AsyncKernelClient object at 0x7f91c67e3310>

Because when I operate toolbar like 'Show Line Numbers', jupyterlab log shows this problme.

**Comment by ML-Mr-J** [comment]
![WX20230313-210040](https://user-images.githubusercontent.com/40787239/224709164-bc642152-cfbe-4b64-a26a-2a8e9477651a.png)

**Comment by ML-Mr-J** [comment]
![WX20230313-210144](https://user-images.githubusercontent.com/40787239/224709341-b2b628f6-44dc-4f9a-92e9-0859f129ec31.png)
![WX20230313-210214](https://user-images.githubusercontent.com/40787239/224709432-088dce68-4281-4eb3-b492-c7d91ddefaa6.png)

**Comment by krassowski** [comment]
You are editing Code Console settings but looking at notebook. You should change Notebook settings instead. Similarly for file editor.

`Could not destroy zmq context` is irrelevant.

**Comment by ML-Mr-J** [comment]
Thanks a lot！
