### ISSUE TITLE
Jupyter ipynb file with embedded cell Matplotlib output plots doesn't view these plots when opening it on the other computer

### ISSUE THREAD

**Issue by dan31** [jupyterlab/jupyterlab#14174]
## Description

I store a group of .ipynb files on Google Drive. Now I've synced with another machine and find out that the stored Matplotlib plots in MOST of these various Notebooks aren't rendered anymore after being opened in Jupyter Lab. I can see that the plots are inside the notebooks in their json markup, but when I open the notebook, this sort of text is displayed instead of a saved graphical output of a cell:

![image](https://user-images.githubusercontent.com/7162535/224573217-587ea9b8-4f5c-4302-bb44-82921e4316ae.png)

Moreover, when I re-run this notebook and hit "Save", after restarting the kernel and re-opening this file again, the images aren't displayed either, though one can see they are saved inside the notebooks by looking at the date of these images as one of the json fields.

Only after removing some parts of the notebook, not directly related to the cells with outputs, I can get it to save these new outputs AND show them on re-opening the notebook. There is no regularity in which parts of the notebook I need to remove to let these stored images start to render.

To add, I've never managed to bring the original saved outputs to the screen on notebook opening.

## Reproduce

Unfortunately, there is no clear way to reproduce this issue. I'd like to understand under which circumstances this could happen by your judgement and get to resolve the issue for me. There is nothing technically special inside the ipynb files, though I can't share them as they all contain proprietary code.

There are no praticular error outputs as per opening these notebooks in browser console.

By just looking at the ipynb files text, there's nothing errorneous like missing parts or anything like that.

## Context

- Operating System and version: Microsoft Windows [Version 10.0.19044.2604]
- Browser and version: Chrome Version 111.0.5563.65 (Official Build) (64-bit)
- JupyterLab version: Version 3.4.4

**Comment by andrii-i** [comment]
@dan31 Thank you for reporting this. I'll try reproducing this on my end. Could you please try upgrading your jupyterlab to latest stable release v3.6.2? Is this happens every time you upload this particular notebooks to google drive? If yes, please try uploading the same notebooks to google drive in v3.6.2 and see if problem persists?

**Comment by JasonWeill** [comment]
@dan31 In addition to trying a newer JupyterLab version, does the problem still occur if you either disable your Google Drive sync program or copy your .ipynb file to a directory that isn't being synced with Google Drive? I'm wondering whether the sync program itself is interfering with JupyterLab's operation.

**Comment by JasonWeill** [comment]
@dan31 Without answers to the questions that @andrii-i and I asked over the past 2 weeks, we can't diagnose this issue. Please reopen with the info requested. Thanks!

**Comment by dan31** [comment]
Hi @JasonWeill, thanks for the feedback!
I will now try jupyterlab 3.6.2 (was using 3.5.3) and outside of gdrive, and report back.

**Comment by dan31** [comment]
Managed to get this behaviour outside of google drive.

I'm running the following environment:

```
(base) C:\Users\x1>jupyter --version
Selected Jupyter core packages...
IPython          : 8.12.0
ipykernel        : 6.19.2
ipywidgets       : 8.0.4
jupyter_client   : 7.3.4
jupyter_core     : 5.3.0
jupyter_server   : 1.23.4
jupyterlab       : 3.6.3
nbclient         : 0.5.13
nbconvert        : 6.5.4
nbformat         : 5.7.0
notebook         : 6.5.3
qtconsole        : 5.4.0
traitlets        : 5.7.1
```

I can't share the entire notebook, but this is what that looks like (I've just cut out pieces of code):

![image](https://user-images.githubusercontent.com/7162535/230770196-b74a3f14-07aa-4b6d-ad2e-341aeddf03cd.png)

So, the image data is clearly in the notebook, but it isn't rendered. When I re-run the cell, it is rendered. When I re-run and save, it is still rendered. But in a while, after working with the notebook for some time, it is no longer rendered, as this. Need to re-run the cell again.

**Comment by krassowski** [comment]
Is your notebook trusted when it happens? Could you then try opening command palette (ctrl shift c) and choosing "trust notebook"?

**Comment by dan31** [comment]
> Is your notebook trusted when it happens? Could you then try opening command palette (ctrl shift c) and choosing "trust notebook"?

Alright, this is it! After trust is chosen, images appear 👍
But this state isn't preserved. Saving and closing the notebook, opening again — images aren't visible.
Is there a way to "save" trust? I have to say that no one of my addresees who were supposed to receive my notebook and view it knew there's anything like that feature with trust to view images.

**Comment by krassowski** [comment]
>  Saving and closing the notebook, opening again — images aren't visible. Is there a way to "save" trust? 

Trust on notebooks _should_ be preserved (but under some circumstances it is not). We are fixing this in https://github.com/jupyterlab/jupyterlab/pull/14345 (mostly, there are still some issues in RTC mode - https://github.com/jupyterlab/jupyterlab/issues/14347 - but trust in RTC is an entire new world) after a long journey of understanding how undocumented internals of trust are handled by nbformat (https://github.com/jupyter/nbformat/issues/349).

I also opened https://github.com/jupyterlab/jupyterlab/issues/14348 to discuss how to make it easier for users to learn about output being sanitised out due to notebook not being trusted - please feel welcome to chime in with ideas.
