### ISSUE TITLE
Development workflow with RTC

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#14170]
## Description

I just tried to set up a development workflow with RTC enabled, and I can't get it working.

## Reproduce

1. In a conda environment with `python` and `nodejs` installed: `pip install -e .`
2. `pip install jupyter_collaboration`
3. `jupyter lab --ServerApp.token='' --ServerApp.password='' --no-browser --dev-mode --extensions-in-dev-mode --collaborative`
4. Open two browser windows at `http://127.0.0.1:8888`
5. Open the same notebook in both windows
6. See that changes are not synchronized

## Expected behavior

RTC should work.

## Context

- Operating System and version: Ubuntu 22.04
- Browser and version: Google Chrome 110.0.5481.177
- JupyterLab version: 4.0.0a35 (`master`)

**Comment by jtpio** [comment]
> 3\. jupyter lab --ServerApp.token='' --ServerApp.password='' --no-browser --dev-mode --extensions-in-dev-mode --collaborative

Normally the `--collaborative` flag should not be needed anymore. But unlikely to be cause of the issue here.

**Comment by davidbrochart** [comment]
I've noticed that the issue appears when you had a notebook open in your workspace and you upgraded JupyterLab to a version where RTC uses YDrives.
Before YDrives, notebooks were referenced differently, causing them to not load properly with YDrives. I think @hbcarlos knows the issue.
