### ISSUE TITLE
It should be possible to disable individual plugins from the UI

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14175]
### Problem

Many optional features of core JupyterLab or of JupyterLab extensions can be disabled from command line by disabling individual plugins, for example:
- `jupyter labextension disable @jupyterlab/docmanager-extension:download` will disable download buttons
- `jupyter labextension disable @jupyter-server/resource-usage:kernel-panel-item` will disable the kernel panel in resource usage extension

However there is no way to perform this operations from the UI - currently users can only enable/disable entire extensions (groups of plugins) and there is not even a way to show all the individual plugins (https://github.com/jupyterlab/jupyterlab/issues/13750); moreover there is no way to disable built-in plugins from UI at all.

Enabling users to easily disable plugins they don't need would also alleviate some of the performance headaches for users on slower computers.

### Proposed Solution

I would like to add a dedicated main area widget with a table listing plugins - as proposed in https://github.com/jupyterlab/jupyterlab/issues/13750#issuecomment-1382440585 - but additionally allowing to enable/disable individual plugins via check-box.

This new table would be accessible from settings and implemented as a separate plugin and server extension, enabling system administrators to disable the UI (and server endpoint) should they decide to prohibit user from customising the plugin configuration.

### Additional context

The proposed implementation is not dissimilar to flags/advanced config system used by many applications, including internet browsers.

**Comment by fcollonval** [comment]
Thanks for the proposal.

I got a question about administered system. Should the user disabled/enabled status be separated to the existing CLI approach. The idea behind is: administrators may disable a set of extensions and still allow the users to dis/enable the rest of the plugins without rights of changing the administrator choice.

**Comment by krassowski** [comment]
> administrators may disable a set of extensions and still allow the users to dis/enable the rest of the plugins without rights of changing the administrator choice

that is a good point.

I am not sure if it would be better to have two sets of enabled/disabled statuses. Instead I think we should probably have an extra "locked" flag that would prevent users from disabling/enabling a plugin that was modified by admin. This could come as two extra commands:

```
jupyter labextension lock extension:plugin
jupyter labextension unlock extension:plugin
```

### Migration from 4.0

In order to add this feature in 4.x we could:
- a) add `lock` status to anything that gets disabled/enabled by `jupyter labextension disable/enable`, and on first startup add `lock` to anything that was manually disabled/enabled prior to the upgrade, or
- b) require users to first execute a CLI command, e.g.
  ```
   jupyter server extension enable jupyterlab-plugin-manager
   ```
   which would enable modification of endpoints

The listing of plugins could be opt-out (always accessible unless disabled from CLI).

### Overview

To summarisie structure I am thinking of:
- backend extensions
  - `jupyterlab-plugin-list` - provides listing of plugins, enabled by default
  - `jupyterlab-plugin-manager` - backend extension implementing APIs to enable/disable plugins **disabled** by default
- frontend plugin
  - `extensionmanager:plugin-list` - provides just a list, enabled by default
  - `extensionmanager:plugin-manager` - extends the list with enable/disable feature, enabled by default (but non-functional until `jupyterlab-plugin-manager` gets enabled)

### UI considerations

- it could be useful to display the plugin list for a given extension. Maybe we could have a button in the extension manager in sidebar that would open up the plugin list filtered down to plugins in this extension
- it could be useful to list the size of the plugin and time it takes to load it, and to sort by these parameters (also suggested in https://github.com/jupyterlab/jupyterlab/issues/13750#issuecomment-1382440585) 
- what happens if a plugin is depended by another? We should probably prevent users from disabling non-leaf plugins and display a nice message showing that other plugins depend on it.
- listing whether a plugin provides a token (with its description) could be useful for extension developers, but no for majority of users.
- icons are only available for a small subset of plugins with settings and not easily accessible from code
- should we prompt user to reload page? probably yes; we could use plugin unload machinery if a plugin supports it for hot unloading/loading, but most do not.
  - should we prompt user to confirm after reload within 60 seconds? that would ensure that if user disables a core plugin that the environment would automatically rollback. Or it could be annoying for advanced users. This could be implemented at the backend (awaiting for API call with confirmation token).

**Comment by krassowski** [comment]
Any preferences on whether it should be a part of `extensionmanager`, or a separate package, e.g. `pluginmanager`?

**Comment by fcollonval** [comment]
I would vote to get everything under the extension manager if possible to limit confusion and UI elements. On particular this will allow to remove the dis/enable button that is flaky if the plugin names do not match the extension name.

Regarding listing all plugins provided by an extension, I wonder how complex this will be.

**Comment by krassowski** [comment]
Thank you for sharing your thoughts and pointing out the limitation of enable/disable button - we can fix this by disabling all plugins from the extension. I would not agree with the argument on keeping it in a single package due to UI elements - if we want to disable plugins which are shipped with JupyterLab rather than from extensions, these should be in a separate main area widget. Having a separate widget with a disclaimer like

> This is a panel for advanced users; jupyterlab extensions are composed of multiple plugins; disabling individual plugins may help with performance butay also render certain functionalities unusable

may actually improve the awareness about the system. But plugins toggle could still be included in extension manager view.

**Comment by krassowski** [comment]
For awareness this is the current WIP:

![Screenshot from 2023-05-13 16-50-41](https://github.com/jupyterlab/jupyterlab/assets/5832902/7f902a7f-71d2-44e8-b74b-5e7aff1c3c3d)

The changes I am working on will enable us to create extension name => list of plugin names mapping (the screenshot includes an example of sos extension having a discrepancy between these)
