### ISSUE TITLE
Embedded JupyterLab movie will not play (standard online suggestions DO NOT work)

### ISSUE THREAD

**Issue by scottwsides** [jupyterlab/jupyterlab#14186]
## Description

I have an mp4 file that I can download to my local machine and it works. However all of the suggestions for playing video inside a jupyterlab notebook are failing eg. None of the IPython or %%HTML or moviepy suggestions work. Can 

<img width="1447" alt="Screen Shot 2023-03-13 at 4 42 17 PM" src="https://user-images.githubusercontent.com/13578795/224848901-dd4d391e-69b2-4486-becb-ef8c7f51ed92.png">

I can make the mp4 file (attached) fine... just cant play it. This is Jupyterlab 3.4.7. Older versions of jupyterlab the IPython solution seemed to work. Is this fixed in later JL versions?

https://user-images.githubusercontent.com/13578795/224849258-db99b43c-b32c-48f4-8e43-258168dfab57.mp4

**Comment by JasonWeill** [comment]
Thanks for opening this issue! Can you share which browser and OS you're using, and what the MIME type of the movie is?

**Comment by scottwsides** [comment]
Thanks for the reply, its a chrome browser embedded in a pyqt app on macos. The MIME type is mp4 (?)... mpeg's dont work either. NOTE: embedded %%HTML cell of youtube movie does display. Very weird...

**Comment by andrii-i** [comment]
@scottwsides based on topical search and [this](https://github.com/maartenbreddels/ipywebrtc/issues/46) post , it seems like other people are having similar issues when trying to use `ipywidgets` extension. Could you please advise which extension (if any) are you using to try playing the video (you can use `jupyter labextension list` in the terminal to print the list of all installed extensions)?

**Comment by JasonWeill** [comment]
@scottwsides I'm still not sure how best to proceed with this issue. Do you see the same problem when running a standalone Chrome/Chromium browser as well?

**Comment by scottwsides** [comment]
Ok... well standalone browser DOES work.  So

from IPython.display import Video
Video("test.mp4", embed=True) 

Works. So something about recent embedding in pyqt is *not* working. Any tips?

**Comment by JasonWeill** [comment]
@scottwsides From what you've said, it's not clear whether this is a bug in JupyterLab or a bug in pyqt. Have you asked the pyqt maintainers about embedding videos in applications?

**Comment by JasonWeill** [comment]
Any update from the pyqt team?

**Comment by JasonWeill** [comment]
Is the notebook trusted inside your web view? Sometimes, choosing to "trust" the notebook enables some functionality.

**Comment by scottwsides** [comment]
Jason, sorry no update from the pyqt team. I've been extremely busy of late... and have not contacted them yet.  Not sure what you mean by webview. But the jupyterlab session is embedded in the pyqt app. There's no 'trust' button to choose.

**Comment by andrii-i** [comment]
@scottwsides Hi! If notebook contains javascript code that was not created or ran by you, it's output would be blocked for security reasons (please see more on security [here](https://jupyter-notebook.readthedocs.io/en/stable/security.html#notebook-security). "Trusting" a notebook would make all the code executable and might help with your problem. 

To trust a notebook, open a notebook in jupyterlab, call up a command palette (Command/Ctrl + Shift + C), type/choose "Trust notebook" and press enter.

**Comment by scottwsides** [comment]
andril, thanks for reply... but selecting "Trust notebook" didnt work

**Comment by JasonWeill** [comment]
Any updates from the pyqt team? It seems like this issue is likely with them, since none of our supported browsers seem to be affected.

**Comment by scottwsides** [comment]
Sorry, I havent contacted them and dont have time right now. I have a workaround where i construct an animated gif and play that. Its just frustrating.

**Comment by JasonWeill** [comment]
@scottwsides Thanks for your patience working through this issue. We haven't found that this is a JupyterLab issue, but more likely an issue with the pyqt environment where you're embedding a video. If you can reproduce this using a supported browser, please reopen; otherwise, you should pursue this with the pyqt maintainers.
