### ISSUE TITLE
Open from URL: Failed to open some jupyter notebooks url on github

### ISSUE THREAD

**Issue by oeway** [jupyterlab/jupyterlab#14194]
## Description

It appears that the open from url feature doesn't work for some url, for example this one didn't work: https://raw.githubusercontent.com/InsightSoftwareConsortium/itkwidgets/00a7ae180f3abf3f90222ce514ad17a8e5ba0402/docs/jupyterlite/files/Hello3DWorld.ipynb

However, this one worked: https://gist.githubusercontent.com/oeway/391b4352ea57b5682366ce3dc2fa9174/raw/5edaefef8e755df9fc4b572d9a76764bbc6a41d9/zarr-virtual-store-jupyterlite-imjoy.ipynb

## Reproduce
 1. Go to: https://jupyter.org/try-jupyter/lab/
 2. In the menu, select "File > Open from URL..."
 3. Paste https://raw.githubusercontent.com/InsightSoftwareConsortium/itkwidgets/00a7ae180f3abf3f90222ce514ad17a8e5ba0402/docs/jupyterlite/files/Hello3DWorld.ipynb and click OK. It will show an "Upload Error: Unterminated string in JSON at position 1048576" 
 4. But if you try https://gist.githubusercontent.com/oeway/391b4352ea57b5682366ce3dc2fa9174/raw/5edaefef8e755df9fc4b572d9a76764bbc6a41d9/zarr-virtual-store-jupyterlite-imjoy.ipynb it works.

## Expected behavior
Both should work!

**Comment by JasonWeill** [comment]
Using JupyterLab 4.0.0a35 installed locally, I can successfully open https://raw.githubusercontent.com/InsightSoftwareConsortium/itkwidgets/00a7ae180f3abf3f90222ce514ad17a8e5ba0402/docs/jupyterlite/files/Hello3DWorld.ipynb and https://gist.githubusercontent.com/oeway/391b4352ea57b5682366ce3dc2fa9174/raw/5edaefef8e755df9fc4b572d9a76764bbc6a41d9/zarr-virtual-store-jupyterlite-imjoy.ipynb using File > Open from URL….

When you try unsuccessfully to open the first file in JupyterLite (at https://jupyter.org/try-jupyter/lab/ ), do you see any errors in the browser console or in the browser's developer tools' Network pane?

If so, please include details about the browser version you're running and any errors you see. Thanks!

**Comment by JasonWeill** [comment]
Opening https://raw.githubusercontent.com/InsightSoftwareConsortium/itkwidgets/00a7ae180f3abf3f90222ce514ad17a8e5ba0402/docs/jupyterlite/files/Hello3DWorld.ipynb in JupyterLite, I see:

> Upload Error
> JSON.parse: unterminated string at line 48 column 470833 of the JSON data

**Comment by JasonWeill** [comment]
Closing in favor of https://github.com/jupyterlite/jupyterlite/issues/1011.
