### ISSUE TITLE
CodeMirror packages which one should be singleton

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#14190]
In https://github.com/jupyterlab/jupyterlab/issues/14183, `@codemirror/state` and `@codemirror/view` have been added as singleton exports.

Nick rose the very good following point:

New codemirror, same old problems: are there any additional CM packages that should be hoisted?

We also historically re-exported some of the actual members so they could be [consumed downstream](https://github.com/MarketSquare/jupyterlab_robotmode/blob/main/src/mode.ts#L791) without relying on webpack tricks: is that worth doing for the new stuff?

Additionally: noted elsewhere, a lot of the CM modes are loaded at startup in a manner that blocks the app loading.... the python mode in particular is quite heavy. Perhaps we can we get back to lazy mode loading?

Maybe all of the non-mode packages?

```yaml
    "@codemirror/autocomplete": "^6.4.0",
    "@codemirror/commands": "^6.1.0",
    "@codemirror/language": "^6.4.0",
    "@codemirror/legacy-modes": "^6.3.0",
    "@codemirror/search": "^6.2.0",
```

And, potentially, the `lezer` stuff:

```yaml
    "@lezer/common": "^1.0.0",
    "@lezer/generator": "^1.0.0",
    "@lezer/highlight": "^1.0.0",
```

_Originally posted by @bollwyvl in https://github.com/jupyterlab/jupyterlab/issues/14183#issuecomment-1466974565_

**Comment by fcollonval** [comment]
Related discussion on CM forum: https://discuss.codemirror.net/t/troubleshooting-article-for-cm6/2803

For the reader, issues may arise due to `instanceof` check within CM that will end up being falsey if multiple versions of codemirror are loaded.

Searching for that operator on [codemirror](https://github.com/search?q=org%3Acodemirror+instanceof&type=code) and [lezer](https://github.com/search?q=org%253Alezer-parser+instanceof&type=code) organizations and from the discussion, we should add 
- `@lezer/common` and `@lezer/highlight` (the generator is a converter tool so it should not matter)
- On the codemirror side, `@codemirror/language` seems needed. But the others should not as the new extension and commands for CM6 receive the state and/or the view from the editor they need to act upon. So there should be fine even in case they come from different versions. For the legacy-modes I don't see a problem with that one.

**Comment by fcollonval** [comment]
cc @JohanMabille would you see other constraints?

**Comment by JohanMabille** [comment]
No (but it's been a while that I haven't worked on that).
