### ISSUE TITLE
Markdown table of contents doesn't handle YAML frontmatter

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab#14200]
## Description

When editing a Markdown document with YAML front-matter, the Table of Contents shows only the last item of frontmatter.

![image](https://user-images.githubusercontent.com/45380/225308684-610f7bd4-d47e-4c5f-b760-d2db2dd736f8.png)

## Reproduce

- Open the _Launcher_
- Click on _Markdown File_
- Open the _Table of Contents_ sidebar 
- Add a header
  ```md
  # Hello World
  ```
- See _Hello World_ in the _Table of Contents_
- Add some _YAML front matter_ before the header

  ```md
  ---
  foo: bar
  boo: baz
  ---

  # Hello World
  ```

- See only `boo: baz` in the Table of Contents

> This was found while working on a [JEP](https://github.com/jupyter/enhancement-proposals/pull/101) in JupyterLab.

By adding a newline above the second `---`, the problem _also_ goes away, so presumably it's treating that last item as an `h2` which counterfeits everything below it.

## Expected behavior

- Definitely see all the headers
- _Maybe_ see a collapsible table above/below the rest of the items
  - but definitely _not_ worth adding/faking a YAML parser
  - maybe just a chunk of YAML-formatted code (e.g. if the first line starts with `[^:]+:`

## Context

- Operating System and version: Linux Ubuntu 21.04 
- Browser and version: Chromium 110
- JupyterLab version: 4.0.0a39 (+ #14102)

**Comment by JasonWeill** [comment]
Does this happen with 3.6.x or older versions of JupyterLab? Is this a regression?

**Comment by bollwyvl** [comment]
Cheers. I never shook this down in 3.*, but I'd wager it exhibits the
condition there was all.
