### ISSUE TITLE
A new cell created below the viewport is not focused immediately

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#14220]
## Description

A new cell created below the bottom of the viewport is not visible immediately after it is created and focused.

cc @andrii-i @ellisonbg 

## Reproduce

1. Create a new notebook.
2. Create cells to fill the entirety of the browser viewport:

![image](https://user-images.githubusercontent.com/93281816/226058826-8b6b902d-f944-4d78-a491-da4525990490.png)

3. Press SHIFT+RETURN to run the bottommost cell.

Actual behavior (4.0.0a36): the bottommost cell runs and a new cell is created and focused, but is not visible.
![image](https://user-images.githubusercontent.com/93281816/226058909-9b8300dd-5dc4-4db5-a934-e206f1e7024b.png)

## Expected behavior

Expected behavior (3.6.1): the bottommost cell runs and a new cell is created, focused, and made visible by scrolling the viewport.
![image](https://user-images.githubusercontent.com/93281816/226059523-34bafc2b-f922-48db-b3b0-c0640d487faa.png)

## Context

- Operating System and version: macOS 12.6.3 "Monterey"
- Browser and version: 102.8.0esr (64-bit)
- JupyterLab version: 4.0.0a36

**Comment by andrii-i** [comment]
New cell viewport bug is present in 4.0.0a33, not present in 3.6.1

**Comment by andrii-i** [comment]
Is not in [v4.0.0a28](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0a28), present in [v4.0.0a29](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0a29)

**Comment by andrii-i** [comment]
The problem was introduced in the merge https://github.com/jupyterlab/jupyterlab/commit/1d19ababaa004247a5566f585f701a4537169c1b / PR #12554. 

CC @fcollonval
