### ISSUE TITLE
Universal selector (`*`) should not be used for LSP form

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14236]
## Description

While I am not a  fan of current LSP UI setting in 4.0 alpha (of course I would prefer something like https://github.com/jupyter-lsp/jupyterlab-lsp/pull/778), there is a critical CSS issue in implementation - this line uses universal selector for no good reason:

https://github.com/jupyterlab/jupyterlab/blob/8230a1a41d48207ae05394607e368b196670cd6a/packages/lsp-extension/style/base.css#L6-L8

This should be removed/replaced before we release 4.0 to avoid affecting style calculation performance.

**Comment by vidartf** [comment]
Tagged as release blocker due to comment in OP.
