### ISSUE TITLE
/lab/api/update not found

### ISSUE THREAD

**Issue by sorenwacker** [jupyterlab/jupyterlab#14233]
Whenever I connect to a running JupyterLab, I get the folllowing popup:

![image](https://user-images.githubusercontent.com/3391614/226440846-b4175334-44da-476d-be5a-a3e2163e08f6.png)

Do you know what that means, and how I can fix it?

**Comment by JasonWeill** [comment]
This is likely because at some point, your client (browser) made a request to `/lab/api/update`, and JupyterLab did not find this path. This issue is already captured in #12768, which is still open.
