### ISSUE TITLE
Expand docs on the switch to yarn 3

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14231]
Follow-up to #13875 

Currently the migration guide only briefly mention the update of `jlpm` to yarn 3: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#jupyterlab-3-x-to-4-x

![image](https://user-images.githubusercontent.com/591645/226345364-07b3eabe-7c5e-45af-8408-618d0b19701b.png)

This section should be more detailed and should tell extension authors using `jlpm` to develop their extensions what they basically need to do (change of `yarn.lock`, do they need a `.yarnrc.yml`...).

**Comment by jtpio** [comment]
It might be also be worth pointing to example PRs that could be used as reference. For example: https://github.com/jupyterlab/extension-cookiecutter-ts/pull/293

cc @brichet

**Comment by martinRenou** [comment]
It may be important to specify that yarn 3 will create a `.yarn` cache folder at the location where yarn is invoked. This was the reason for the huge wheel reported in https://github.com/jupyterlab/jupyterlab/issues/14241

This may be a yarn bug, but adding a mention to add `.yarn` in the `.gitignore` could be good.

**Comment by martinRenou** [comment]
> change of yarn.lock

I've seen cases where removing the old `yarn.lock` was needed for the extension to build. Otherwise it fails with cryptic errors.

So we should suggest, in the migration guide, to remove the `yarn.lock` file and re-generate it.
