### ISSUE TITLE
Clarification of conda envrionment used for steps on JupyterLab Extension Tutorial

### ISSUE THREAD

**Issue by TidbitSoftware** [jupyterlab/jupyterlab#14247]
## Description

In the [JupyterLab Extension Tutorial](https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html#extension-tutorial`), in the 'Install NodeJS, JupyterLab, etc. in a conda environment' step, we are instructed to activate the newly-created `conda` environment. In the 'Build and install the extension for development' step, it is not clear that the commands should be run in the base `conda` environment, which can be assumed because in the next step we are instructed, "After the install completes, open a second terminal. Run these commands to activate the jupyterlab-ext environment [...]".

**Comment by TidbitSoftware** [comment]
It appears that the 'Build and install the extension for development' step should still be run with the `jupyterlab-ext conda` environment active, but the language about "open[ing] a second terminal" is still sort of confusing.

**Comment by jtpio** [comment]
Thanks @TidbitSoftware for the report.

Which part exactly do you find confusing? It looks like the instructions should be correct normally?

![image](https://user-images.githubusercontent.com/591645/228265737-15d8dd42-4292-4d14-9b84-ea5634616e92.png)

**Comment by JasonWeill** [comment]
I agree with with @jtpio : The `base` environment is one that I typically leave unused, instead using my named `conda` environments for all my development and JupyterLab running needs.
