### ISSUE TITLE
"Filter files" search icon is not vertically centered

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#14249]
In the file browser, the search icon beside "filter files by name" is aligned closer to the top of the containing box. It should be centered within the box.

<img width="228" alt="Screen Shot 2023-03-20 at 3 07 27 PM" src="https://user-images.githubusercontent.com/93281816/226766264-fa8da1b7-dbf5-48a6-8db5-0211bf006c04.png">

## Context

- Operating System and version: Chrome Version 110.0.5481.177 (Official Build) (x86_64)
- Browser and version: macOS
- JupyterLab version: 4.0.0a37

**Comment by JasonWeill** [comment]
Found by @dlqqq during a bug bash.

**Comment by Peterjyc** [comment]
Hello, I would like to try to work on this issue. Could you assign it to me?

**Comment by JasonWeill** [comment]
I may not be able to assign this issue to someone outside the `jupyterlab` org, but any contributor (including a first-time contributor) is welcome to submit a pull request for our consideration.

**Comment by bikash30851** [comment]
I will be happy to work on it.

**Comment by JasonWeill** [comment]
@williamcaoliver Welcome! This issue is still open, and we'd love to review a pull request for it. Please let us know if you have questions.

**Comment by bikash30851** [comment]
I have been trying to figure it out but could not find the specific CSS file to work on. @JasonWeill Also, I am working on Windows, is that okay?

**Comment by andrii-i** [comment]
@bikash30851 We can't provide step-by-step instruction but here's a tip: you can use chrome or firefox developer tools to inspect an element, then see which CSS files have className of the element in question (use search). As long as your environment works, there is nothing wrong with working on Windows.

**Comment by bikash30851** [comment]
@andrii-i thank you for your response. I asked about the OS since it was mentioned in the context of the original issue. I will try to follow the steps that you outlined to find the className.
