### ISSUE TITLE
cpp file disappeared

### ISSUE THREAD

**Issue by MohaaBdr** [jupyterlab/jupyterlab#14246]
Hi, I was coding on a file named read.cpp and it suddenly disappeared after I got disconnected from the server, is there a way to recover it ?

**Comment by JasonWeill** [comment]
Had you saved the file? If so, it should be present wherever it was saved. If not, check in the `.ipynb_checkpoints` folder, under the same directory where you had that file, to see if JupyterLab saved a checkpoint.

**Comment by MohaaBdr** [comment]
Yes I did multiple times to compile it but i only old copies of it. The folder where the file used to be in isn't here anymore, only the compiled file is still in the folder. 
There is no checkpoints folder in the same directory 


De: "Jason Weill" ***@***.***> 
À: "jupyterlab/jupyterlab" ***@***.***> 
Cc: "MohaaBdr" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mercredi 22 Mars 2023 00:39:15 
Objet: Re: [jupyterlab/jupyterlab] cpp file disappeared (Issue #14246) 





Had you saved the file? If so, it should be present wherever it was saved. If not, check in the .ipynb_checkpoints folder, under the same directory where you had that file, to see if JupyterLab saved a checkpoint.

**Comment by JasonWeill** [comment]
From what you've said, it's not clear whether JupyterLab caused the cpp file to disappear. JupyterLab also doesn't clean up directories on its own. I recommend following up with your server administrator, for example to see if they can recover your file from a backup, or trying to reproduce with JupyterLab installed locally. Sorry that I can't provide more specific guidance here.
