### ISSUE TITLE
Output prompt area is a large button

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#14252]
## Description

The entire output prompt area is a button that is clickable to toggle output scrolling. This makes it very difficult to drag and drop cells. This should probably be reverted until a different UI can be designed.

![image](https://user-images.githubusercontent.com/93281816/226767714-efb71462-fd3f-487b-b41a-de6575ab6c66.png)

Found by @ellisonbg during a bug bash.

## Reproduce

1. Run a cell that generates a lot of output
2. Hover over the area to the left of the output
3. Observe that the entire area to the left of the output and to the right of the blue cell bar is a clickable button

## Expected behavior

The blank area should be used as a drag handle, not entirely as a "toggle output scrolling" button

## Context

- Operating System and version: macOS
- Browser and version: Firefox
- JupyterLab version: 4.0.0a37

**Comment by krassowski** [comment]
This was implemented in https://github.com/jupyterlab/jupyterlab/pull/14072 as feature parity with classic notebook and was one of the most requested features in JupyterLab issue tracker ever, with multiple users mentioning this as a blocker for their transition to JupyterLab. Saying that this does be reverted is a bit harsh. We could make it configurable with opt out setting. Also, dragging cella is still possible using the area to left.

**Comment by krassowski** [comment]
Also there were 4 years for someone to make an alternative UI proposal ;)

**Comment by JasonWeill** [comment]
We could use the `resize-ns` cursor to communicate that the button expands or collapses the output:

https://user-images.githubusercontent.com/93281816/227047739-6d68ba86-eaf2-4b32-b036-18849b28917a.mov

**Comment by JasonWeill** [comment]
Or we could use the `zoom-in` and `zoom-out` cursors for a similar effect:

https://user-images.githubusercontent.com/93281816/227047847-e9a64ee0-ab85-4f54-9c24-583b40b1f6a1.mov

**Comment by jtpio** [comment]
Agree with @krassowski this is a very valuable and useful feature to keep by default :+1: Thanks again for implementing it!

And also helpful for Notebook 7 (it works there out of the box).

For dragging cells there is already the input prompt which seems to be working fine.

**Comment by JasonWeill** [comment]
Updated #14266 with the zoom cursors.
