### ISSUE TITLE
[W 2023-03-27 10:32:48.587 ServerApp] 404 GET /api/me?1679884368211 (::1) 13.00ms referer=http://localhost:8888/lab

### ISSUE THREAD

**Issue by Allen-Cee** [jupyterlab/jupyterlab#14276]
The Jupyter Lab application runs well but I get this never ending stream of 404 GET errors like #12904:

![image](https://user-images.githubusercontent.com/25904336/227828002-ea14e79b-02b4-489d-bbad-91ec915b82b1.png)

Environment: 
1. Win 10
2. jupyter --version
Selected Jupyter core packages...
IPython          : 7.34.0
ipykernel        : 6.16.2
ipywidgets       : 7.6.5
jupyter_client   : 7.4.9
jupyter_core     : 4.12.0
jupyter_server   : 1.23.6
jupyterlab       : 3.6.1
nbclient         : 0.7.2
nbconvert        : 7.2.10
nbformat         : 5.7.3
notebook         : 6.5.3
qtconsole        : not installed
traitlets        : 5.9.0

Note: 
I have already uninstalled & reinstalled the jupyter lab package completely and reset all the configurations, but the "404 GET" errors keep showing.

**Comment by Allen-Cee** [comment]
I have already uninstalled & reinstalled the jupyter lab package completely and reset all the configurations

**Comment by hbcarlos** [comment]
Hi @Allen-Cee. JupyterLab v3.6 needs jupyter-server v2. 
I can see you are using jupyter-server v1.
```
jupyter_server : 1.23.6
jupyterlab : 3.6.1
```

Could you update the server? That should fix it. The `/api/me` endpoint was introduced in jupyter-server v2.

**Comment by Allen-Cee** [comment]
Thanks a lot! It seems jupyter-server >= 2.0 need Python >= 3.8, but my version is 3.7. So I downgrade jupyterlab to 3.5.3 and the problem is solved.

**Comment by wendychou2023** [comment]
Hi @hbcarlos, I also encounter the same 404 GET errors. Following is the installed package version:
IPython          : 8.15.0
ipykernel        : 6.25.0
ipywidgets       : 8.1.1
jupyter_client   : 8.6.0
jupyter_core     : 5.5.0
jupyter_server   : 1.23.4
jupyterlab       : 3.3.2
nbclient         : 0.8.0
nbconvert        : 7.10.0
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : 5.4.4
traitlets        : 5.7.1
![image](https://github.com/jupyterlab/jupyterlab/assets/101310447/6af47ffb-bba7-462b-9a22-6c2df32fdf41)

**Comment by krassowski** [comment]
@wendychou2023 you have pretty outdated versions of most packages installed. The solution for you is to upgrade to latest versions.

**Comment by yanghou2000** [comment]
In my case, it is the problem of web browser, Safari from mac. After switching to Edge, it works fine.
