### ISSUE TITLE
When I select a Chinese file, the name of the page becomes unintelligible codes

### ISSUE THREAD

**Issue by a512884335** [jupyterlab/jupyterlab#14274]
![image](https://user-images.githubusercontent.com/46161457/227703266-4c985dc3-574b-48e6-8428-e4233fff3197.png)

**Comment by JasonWeill** [comment]
It looks like the filename is being expanded into its constituent UTF-8 or UTF-16 bytes, then each byte is HTML-encoded (URL-encoded) in the tab title. This is not the right behavior.

**Comment by fcollonval** [comment]
I think that https://github.com/jupyterlab/jupyterlab/pull/14178 should fix it.

@a512884335 would you mind trying the pre-release version of JupyterLab?

You can install it with:

```sh
pip install --pre -U "jupyterlab==4.0.0b0"
```

**Comment by a512884335** [comment]
> I think that #14178 should fix it.
> 
> @a512884335 would you mind trying the pre-release version of JupyterLab?
> 
> You can install it with:
> 
> ```shell
> pip install --pre -U "jupyterlab==4.0.0b0"
> ```

Thank you very much! It worked!

**Comment by JasonWeill** [comment]
Fixed by #14178.
