### ISSUE TITLE
Document how to use the Command Linker

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14284]
### Problem

JupyterLab supports using commands in Markdown files with the following syntax:

However it does not seem to be mentioned in the documentation.

https://user-images.githubusercontent.com/591645/228168101-8940bf0f-c647-4baf-a253-c8333f918627.mp4

### Proposed Solution

This is a useful feature and it should be documented.

### Additional context

Here is one of the PRs that implemented this feature: https://github.com/jupyterlab/jupyterlab/pull/9937

**Comment by bikash30851** [comment]
I can do the documentation. Should it go on `ReadMe.md`? Where can I find more information on creating documentation? Thank you.

**Comment by jtpio** [comment]
Thanks @bikash30851!

Probably this could go in the main user documentation. Maybe as part of the "Commands" page? https://jupyterlab.readthedocs.io/en/latest/user/commands.html

**Comment by bikash30851** [comment]
@jtpio I can write a short description of the feature with a section heading in the `.rst` file. Do you think that's good enough?

**Comment by bikash30851** [comment]
@jtpio I have written the documentation and raised a pull request. 

It looks like I committed my previous CSS code for issue #14249 along with it. 

I have made it right as @fcollonval suggested. Apologies for any confusion this might create.
