### ISSUE TITLE
Notebook jitter when scrolling a long notebook

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14285]
## Description

While using JupyterLab `4.0.0b0` with long notebooks recently I noticed quite a bit of "jittering" which makes navigating the notebook unpleasant.

## Reproduce

- open `4.0.0b0` on Binder: https://gist.github.com/jtpio/4e9a3d435d7c3950dc4150c10abbb1d7
- create a long notebook
- grab the scrollbar and move the mouse down

https://user-images.githubusercontent.com/591645/228187180-a065c14e-7177-41b0-bba4-3af42d331da6.mp4

Also this might be more apparent when the notebook has many markdown cells and images.

## Expected behavior

It should be possible to drag the scrollbar all the way to the bottom without jitter.

For reference with 3.6.2 the scrollbar follows the mouse more accurately:

https://user-images.githubusercontent.com/591645/228187782-33fab1c0-d78b-4b8d-b2fd-23027f8f3f81.mp4

## Context

cc @fcollonval as this might be related to the virtual notebook implementation?

**Comment by krassowski** [comment]
It seems related to https://github.com/jupyterlab/jupyterlab/issues/13343, do you think this is a duplicate or a separate issue?

**Comment by jtpio** [comment]
Thanks @krassowski for the link. I think it does yes.

Let's close this issue then. I'll copy the top message with the screecasts there.
