### ISSUE TITLE
Search "in selected" sometimes reverts to edit mode preventing cell selection

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14308]
## Description

When searching "in selection" (https://github.com/jupyterlab/jupyterlab/pull/14090), switching to `command` mode and attempting to select multiple cells the mode switches back to  `edit` mode putting cursor back in the cell and preventing selecting more cells.

This appears somewhat similar to seemingly unrelated issue https://github.com/jupyterlab/jupyterlab/issues/14271 (could be unrelated or could have to do with recent cursors work)

## Reproduce

![switches-to-edit-mode](https://user-images.githubusercontent.com/5832902/229264108-b7c87af5-112a-4d37-a6fb-3f4d8ffcaa97.gif)

## Expected behavior

When <kbd>Shift</kbd> + <kbd>Up</kbd>/<kbd>Shift</kbd> + <kbd>Down</kbd> is pressed the cell selection extends and the command mode remains unchanged.

## Context

- JupyterLab version: 4.0.0b

**Comment by krassowski** [comment]
This looks hard, and originate from CodeMirror focusing the editor back when decorations get updated. Question upstream: https://discuss.codemirror.net/t/how-to-add-decoration-without-focusing-the-editor-on-dispatch/6283

It is still not clear to me why CodeMirror only focuses editor back on some but not all updates to decorations.

**Comment by fcollonval** [comment]
I tagged this as release blocker as the associated PR changes the API; just to be sure we merge it before the final release.
