### ISSUE TITLE
4.0.0b0: impor<tab> -> importimport

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#14329]
Completion has this issue:

```
impor<tab><tab><tab><tab><tab><tab>
```
Lead to `importimport`

See https://github.com/jupyter/notebook/issues/6818 (found in notebook v7)

**Comment by krassowski** [comment]
Confirmed, confirmed not present in 3.6 tagging as regression.

**Comment by davidbrochart** [comment]
It looks similar to https://github.com/jupyterlite/jupyterlite/issues/961.

**Comment by Carreau** [comment]
I think this one is triggered when you reach the end of the completer list in jupyterLab in it loops over back to the top, so it might be different.

**Comment by afshin** [comment]
I'm still working on this issue, but I've removed the `Release Blocker` label.
