### ISSUE TITLE
Wrong mouse cursor when hovering a kernel in the Running tab

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14326]
## Description

Hovering on kernel entries in the `Running`tab shows a "wrong" mouse cursor

## Reproduce

1. Open JupyterLab 4.0.0b0
2. Create a notebook
3. Open the Running tab
4. Hover on the kernels

https://user-images.githubusercontent.com/591645/229863722-a48cb99a-d2e1-4ffd-99ae-f21581f63afb.mp4

## Expected behavior

The mouse cursor should not be a text insertion-point `cursor`.

## Context

JupyterLab `4.0.0b0` on Firefox 111.

**Comment by jtpio** [comment]
This also leads to the following behavior of selecting text when clicking quickly on the dropdown icon:

https://user-images.githubusercontent.com/591645/230617666-eed3b409-1fb1-4fbc-b71b-a3ebf1bb57fd.mp4

**Comment by krassowski** [comment]
I was thinking about asking for `user-select: none` in review but then though that users may want to copy the name of the notebook; though yes, the collapser and maybe even kernel name should be non-selectable.

**Comment by yumyumqing** [comment]
I have created a PR: https://github.com/jupyterlab/jupyterlab/pull/14369 to address this issue and I tried to include all the above suggestions.
I have attached a video in the PR. If some other cursor type is needed, please let me know and I will update the PR.
Thanks!
