### ISSUE TITLE
For notebook v7: tree view should be able to sort notebook ahead of other files.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#14332]
See upstream issue https://github.com/jupyter/notebook/issues/6819

### Problem

Notebook V6 tree view sorts `folders > notebook > other files`, reason being in notebook users are way less likely to access other files. 

As V7 uses JupyterLab Components notebook get sorted as they are in JupyterLab, and thus we lost having notebooks at the top of the tree view. 

### Proposed Solution

Add an option for the file browser to sort notebooks preferentially. Folder are already on top, so it should not be too hard.

**Comment by jtpio** [comment]
Thanks @Carreau for reporting the issue in the JupyterLab repo.

Adding it to the `4.0` milestone. It's not a blocker for JupyterLab but might be for Notebook 7.

**Comment by krassowski** [comment]
Relevant parts of the codebase:

https://github.com/jupyterlab/jupyterlab/blob/a3dd6af90a011854305b83ff5f64a0f474567e4b/packages/filebrowser/src/listing.ts#L325-L329

https://github.com/jupyterlab/jupyterlab/blob/a3dd6af90a011854305b83ff5f64a0f474567e4b/packages/filebrowser/src/listing.ts#L2771-L2807

**Comment by JasonWeill** [comment]
@Carreau The `sort()` method is public, as @krassowski described above, so we should be able to override it in notebook for 7.0.0, if it blocks Notebook 7.0.0.
