### ISSUE TITLE
Document the breaking changes policy in JupyterLab for extension authors (and users?)

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14333]
### Problem

Currently it might not be clear to contributors, extension authors or users what the backward compatibility policy of the JupyterLab (or even Jupyter?) ecosystem is.

Some questions that were raised during previous Notebook weekly calls: https://github.com/jupyter/notebook-team-compass/issues/21:

- What does a "breaking change" mean?
- What should extension authors do when there is a new major version of JupyterLab and Notebook?
- Does JupyterLab always introduce new breaking changes in major versions?
- Does JupyterLab follow semver?

### Proposed Solution

For reference there is already the migration guide for extension authors: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html

Also JupyterLab has been following `semver` since the beginning of the project: https://semver.org/

 Most of the other Jupyter projects also follow semver.

Maybe there should be more details about all this? Or document this policy so it's more visible in the JupyterLab docs?

There could also be a section in the Notebook 7 documentation with the same content, or a link to the JupyterLab documentation.

### Additional context

This was brought by @ericsnekbytes during the Notebook Weekly Meeting yesterday: https://github.com/jupyter/notebook-team-compass/issues/21#issuecomment-1497831866

@ericsnekbytes would you be able to start a draft PR to improve the documentation while JupyterLab 4 and Notebook 7 are in beta? Thanks!

**Comment by jtpio** [comment]
Also @ericsnekbytes feel free to post more information and questions here, as I don't remember exactly everything that was said during the calls (and the meeting notes might have not captured everything).

**Comment by ericsnekbytes** [comment]
I have changes ready for this, but I can't commit now because `No module named pre_commit` :| They live on my stash right now, once I work through this I'll submit a PR :)

**Comment by ericsnekbytes** [comment]
PR is here: https://github.com/jupyterlab/jupyterlab/pull/14355

**Comment by ericsnekbytes** [comment]
I've asked @RRosio and @echarles to chime in with any suggestions as well.
