### ISSUE TITLE
Add icon to expander/collapser button for cell output

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#14341]
### Problem

This is a follow-up to #14266 based on conversations with @andrii-i , @GabrielaVives , @krassowski , and others.

The large gray button to the left of cell output does not immediately read as an expander or a collapser. Add an icon to indicate its function.

(Image courtesy @GabrielaVives)

<img width="778" alt="Screen Shot 2023-04-07 at 2 21 51 PM" src="https://user-images.githubusercontent.com/93281816/230680599-12714f6f-be79-43a7-ba2c-b488afe61489.png">

### Proposed Solution

Options include:

* Add an expander or collapser icon that appears only when the user hovers over or focuses the expander/collapser button
* Add an expander or collapser icon that always appears, suggesting that the user can click on the expander/collapser area

### Additional context

Mockups by @GabrielaVives : https://www.figma.com/proto/dbL69ZMe27IgCFrh9AbykH/Issues?page-id=20%3A33&node-id=20-34&viewport=740%2C395%2C0.6&scaling=min-zoom&starting-point-node-id=20%3A34 (icon appears on hover)

**Comment by brijsiyag** [comment]
@JasonWeill , Can you assign it to me if it is open to work on.

**Comment by JasonWeill** [comment]
@brijsiyag Assigned. Thanks for your interest!

**Comment by brijsiyag** [comment]
@JasonWeill , I gave it a try, blockers - 
* Where can I find these icons ?
* When output is of one line then logo doesn't fit in, what is the plan for that ?

**Comment by krassowski** [comment]
@GabrielaVives may have the icons in standalone files, if not an svg would need to be created manually (I usually use Inkscape and then export with minimization options and then clean by hand).

> When output is of one line then logo doesn't fit in, what is the plan for that ?

I think we could not display the icon in that case? Or if it is easier scale it down?

**Comment by brijsiyag** [comment]
![expand](https://github.com/jupyterlab/jupyterlab/assets/71015892/c2ca2fca-f7ac-46a4-aec7-43bb2d100ceb)
![collapse](https://github.com/jupyterlab/jupyterlab/assets/71015892/89eb5bb9-fa4f-4e02-bd25-4f05f8fc319f)

I tried to create these two in Inkscape, take a look.

**Comment by brijsiyag** [comment]
I think in small size icon looks good in single line. Current property `height: min(3em,75%)`

<img width="506" alt="Screenshot 2023-06-05 at 6 40 08 AM" src="https://github.com/jupyterlab/jupyterlab/assets/71015892/c6ddc1ad-22b3-432a-9bc5-19d14e7a5429">
<img width="388" alt="Screenshot 2023-06-05 at 6 40 20 AM" src="https://github.com/jupyterlab/jupyterlab/assets/71015892/bbeef51e-cd82-4a09-baa6-2d079b267786">
<img width="521" alt="Screenshot 2023-06-05 at 6 40 36 AM" src="https://github.com/jupyterlab/jupyterlab/assets/71015892/b0eb20f7-5f6b-46b8-9a28-74f637c8ec69">

**Comment by GabrielaVives** [comment]
I don't have the icons but I can create the SVGs, what you did @brijsiyag looks good. Would you like me to re-create them or have you managed?

**Comment by brijsiyag** [comment]
No @GabrielaVives, I managed to draw them in Inkscape. If you have any suggestion to improve, let me know. 
Thank you !!

**Comment by andrii-i** [comment]
Thank you for working on this @brijsiyag, it looks nice. I'd say the icon should be of the constant size / should not change size with change of containers height. Please feel free to open a PR when you're ready.

**Comment by brijsiyag** [comment]
Hey, I already opened a PR, #14640. 
If we use constant size of icon, than we have to hide the icon if the containers's size is small than icon's.

**Comment by andrii-i** [comment]
@brijsiyag Oh nice, thank you! I haven't noticed the existing PR because it is not linked to the issue (already linked it manually). Linking a PR to the issue manually or through use of keyword in the PR description increases PRs visibility and ensures that issue is closed when PR gets merged. 

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
