### ISSUE TITLE
Filtering files by name doesn't work for Chinese file names.

### ISSUE THREAD

**Issue by klwb** [jupyterlab/jupyterlab#14340]
hi,
When there are Chinese file names in my file browser list, I am unable to use the file name filtering function. And I noticed that it cannot be filtered if it starts with Chinese characters only, but it can be filtered and searched if it starts with letters, numbers, underscores, and then adds Chinese characters.

My context is as follows:

step1:
docker images jupyter/base-notebook
REPOSITORY              TAG       IMAGE ID       CREATED      SIZE
jupyter/base-notebook   latest    91d725edce1e   4 days ago   976MB

step2:
Start JupyterLab in a clean environment.
docker run -d -p 10000:8888 --name=jupyter-search-test -e RESTARTABLE=yes -v /etc/localtime:/etc/localtime -v /etc/timezone:/etc/timezone -e RESTARTABLE=yes -e JUPYTER_ENABLE_LAB=yes jupyter/base-notebook

I recorded the problem. Please take a look at the video, it's about 1 minute and 30 seconds long.

中文文件名：
测试1.ipynb
测试2第二个.ipynb
2测试.ipynb

When I typed "测试", "2测试.ipynb" can be filtered out, but "测试1.ipynb" and "测试2第二个.ipynb" cannot be filtered out.

thku！

https://user-images.githubusercontent.com/1202440/230634460-4f5037be-02ad-4fb0-9d32-a7b5396231b5.mp4

**Comment by JasonWeill** [comment]
@klwb Thank you for your issue! Can you share which browser (program and version number), which OS, and which JupyterLab version you're using? That will help us to diagnose this issue. Thanks.

**Comment by klwb** [comment]
> @klwb Thank you for your issue! Can you share which browser (program and version number), which OS, and which JupyterLab version you're using? That will help us to diagnose this issue. Thanks.

Thank you for your reply. I apologize for the late response to your email!

Browser and version: 
`Chrome version 112.0.5615.49 (Official Build) (x86_64)、Microsoft Edge version 112.0.1722.34 (Official Build) (x86_64)`

OS:
`macOS Monterey`

JupyterLab version:
`3.6.3`

The following information may also be helpful:
I am running JupyterLab with Docker on the host machine, and then using nginx to forward the requests. I am accessing the server through a browser on my work computer. Here is the configuration:

jupyter:

`docker run -d -p 10000:8888 --name=jupyter -e RESTARTABLE=yes -v /etc/localtime:/etc/localtime -v /etc/timezone:/etc/timezone -e RESTARTABLE=yes -e JUPYTER_ENABLE_LAB=yes -v /opt/my_notebook:/home/jovyan jupyter/base-notebook`

nginx:
```
server { 
    listen 80; 
    index index.php index.htm index.html; 
    root /home; 
    return 301 https://note.*****.com$request_uri;
} 

server {
    listen       80;
    server_name  note.*****.com;    
    listen 443 ssl;
    ssl_certificate /etc/nginx/ca/****_note.*****.com.pem;
    ssl_certificate_key /etc/nginx/ca/****_note.*****.com.key;
    ssl_session_timeout 5m;
    ssl_ciphers *********************************************************;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://127.0.0.1:10000/; 
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
    }
}
```
My host server:
```
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core) 
Release:        7.4.1708
Codename:       Core
```
Access:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/1202440/231989202-1ac227b5-45b6-45b5-bb6a-b4ead826f2c6.png">

Thanks

**Comment by FoSuCloud** [comment]
This problem occurs because word boundary matching only considers English, and does not perform multilingual matching, resulting in the starting index error when using the indexOf function.
![image](https://user-images.githubusercontent.com/49218295/232205659-4ed704b6-916a-4560-b41f-42019fb0f598.png)
![image](https://user-images.githubusercontent.com/49218295/232206121-eb59725c-15de-4112-94b0-1fbf09958a32.png)
![image](https://user-images.githubusercontent.com/49218295/232205679-851ce7b3-1f35-40ed-9c5f-ceaaff3af25e.png)
But I don't have a good solution to this problem, how can the request be compatible with multiple languages? Maybe it's time to rewrite the search function? @JasonWeill

**Comment by klwb** [comment]
> This problem occurs because word boundary matching only considers English, and does not perform multilingual matching, resulting in the starting index error when using the indexOf function. ![image](https://user-images.githubusercontent.com/49218295/232205659-4ed704b6-916a-4560-b41f-42019fb0f598.png) ![image](https://user-images.githubusercontent.com/49218295/232206121-eb59725c-15de-4112-94b0-1fbf09958a32.png) ![image](https://user-images.githubusercontent.com/49218295/232205679-851ce7b3-1f35-40ed-9c5f-ceaaff3af25e.png) But I don't have a good solution to this problem, how can the request be compatible with multiple languages? Maybe it's time to rewrite the search function? @JasonWeill

可以暂时把所有ipynb文件改名加数字前缀，这样中文就可以检索到
`find /path/your/JupyterLab/root/directory  -type f -not -path "*/.ipynb_checkpoints/*" -name "*.ipynb" -execdir sh -c  'mv "$1" "$(dirname "$1")/0$(basename "$1")"' _ {} \;`
即`未命名.ipynb`to`0未命名.ipynb`
![image](https://user-images.githubusercontent.com/1202440/232233323-ad7da75c-953c-4330-821d-99126abe34ba.png)

**Comment by FoSuCloud** [comment]
> 

This or maybe not a good solution, this solution will destroy the original filename published

**Comment by klwb** [comment]
> > 
> 
> This or maybe not a good solution, this solution will destroy the original filename published

Yes,It doesn't matter if you're not using Git. After the official bug fix, you can change it back if necessary.I have over a hundred notebooks, so I have no choice but to do it this way.

**Comment by mozi-lu** [comment]
I can't wait for an official fix. I fixed the bug myself, just replace `/\b\w/g` with `/(\b\w)|(^\B\W)/g`.
Here is the  shell script:
`sed -i 's/\/\\b\\w\/g/\/(\\b\\w)|(^\\B\\W)\/g/g' /opt/conda/share/jupyter/lab/static/jlab_core.*.js`

**Comment by klwb** [comment]
> I can't wait for an official fix. I fixed the bug myself, just replace `/\b\w/g` with `/(\b\w)|(^\B\W)/g`. Here is the shell script: `sed -i 's/\/\\b\\w\/g/\/(\\b\\w)|(^\\B\\W)\/g/g' /opt/conda/share/jupyter/lab/static/jlab_core.*.js`

Brilliant solution!

**Comment by JasonWeill** [comment]
@mozi-lu Thank you for your contribution! We welcome pull requests in JupyterLab. Would you be able to open a PR to add this fix to the codebase, so you don't have to make this patch after building or installing locally?
