### ISSUE TITLE
Announcements from custom ATOM feed are not displayed in front-end

### ISSUE THREAD

**Issue by suganya-sk** [jupyterlab/jupyterlab#14358]
## Description
I'm looking to show custom announcements in Jupyterlab using a custom ATOM feed.

I start a lab instance (3.6.2) using the command - 

`jupyter lab --LabApp.news_url="<foo>"`

where foo is the url to a xml file containing a ATOM feed generated through [feedgen](https://feedgen.kiesow.be/).

However, I do not see the custom announcements show up in the UI - 

![image](https://user-images.githubusercontent.com/19615498/231121622-c5ccfa36-41af-47c4-b817-fe92eaf10a2b.png)

My notification settings look like this - 

![image](https://user-images.githubusercontent.com/19615498/231122519-0a6d9687-c5a0-41c7-9034-8818ce9a7fbf.png)

Note - I **do not want** to have official Jupyter news, I'm looking to use the Announcements framework to provide custom announcements. I toggled the options related to official Jupyter news to check if they have any effect and they did not.

## Context

- Browser and version: Chrome 102
- JupyterLab version: 3.6.2

**Comment by andrewfulton9** [comment]
@suganya-sk, do each of your entries have the following tags: id, title, summary, published, updated, and linked?

Also is the file being provided by a web server, or are you pointing directly to file path?

**Comment by suganya-sk** [comment]
And am running a simple HTTP server from the dir containing the feed file and using this url in `--LabApp.news_url`

**Comment by andrewfulton9** [comment]
Yeah, it is mandatory for this handler to work. It currently requires all of the fields I mentioned above to be in an entry. I suggest that the NewsHandler be updated to allow any valid entry as defined by [RFC 4287](https://datatracker.ietf.org/doc/html/rfc4287#section-4.1.2) to trigger an announcement though. 

@fcollonval, any thoughts on this? I'm happy to make this change.

**Comment by fcollonval** [comment]
> FYI I have a PR drafting adding a post to the official news URL that produces the assets as job artifact: https://github.com/fcollonval/assets/actions/runs/4680232235 You can download it and looks at the content of `feed.xml` for comparison.

@andrewfulton9 thanks for providing support. Indeed you are correct the current code extracts the following attribute:

https://github.com/jupyterlab/jupyterlab/blob/53c31d48218d86de6b7586e1ac318bc52c35e73a/jupyterlab/handlers/announcements.py#L229-L252

From the resource pointed by Andrew

```
   atomEntry =
      element atom:entry {
         atomCommonAttributes,
         (atomAuthor*
          & atomCategory*
          & atomContent?
          & atomContributor*
          & atomId
          & atomLink*
          & atomPublished?
          & atomRights?
          & atomSource?
          & atomSummary?
          & atomTitle
          & atomUpdated
          & extensionElement*)
      }
```

The code should handle:
- Missing `summary`
- Missing `published`
- Multiple `links`

Thanks for proposing to help fixing this; don't hesitate to ping me on the PR.
