### ISSUE TITLE
Initial query for search should be set based on output selection and rendered markdown selection too

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14352]
## Description

Currently the initial search query in notebook is set based on selection in cell editor, but not based on selection of:
- rendered markdown text, or
- selection of outputs

This is not consistent as depending on where the selected text is, it the initial query in the search dialog will be pre-populated or not.

## Reproduce

1. Open notebook with a cell with output/markdown cell
2. Select text in output/rendered markdown cell
3. Press <kbd>Ctrl</kbd> + <kbd>F</kbd>
4. See search field was not pre-populated

Issue examplified on rendered Markdown:

![markdown](https://user-images.githubusercontent.com/5832902/230897154-f3fcb891-a431-4ea5-a201-11387337d6a4.gif)

Initial query being properly set for code cell selection but not for output:

![initial query not set for output selection](https://user-images.githubusercontent.com/5832902/230897159-3fedd179-ee6c-4f9a-8dfe-6e35dfb41c72.gif)

## Expected behavior

Initial query is set for the active selection, regardless of the element type.

## Context

- JupyterLab version: 3.6.1 and 4.0.0b1

**Comment by JasonWeill** [comment]
Still an issue in Lab 4.1.
