### ISSUE TITLE
Multi-line select does not work in 3.6.2; works in 3.6.1

### ISSUE THREAD

**Issue by suganya-sk** [jupyterlab/jupyterlab#14359]
## Description

Multi-line select  - `Alt` + mouse-click + drag up/down to cover multiple lines - works in 3.6.1 but not in 3.6.2.

## Context

- Browser and version: Chrome 102
- JupyterLab version: Jupyterlab 3.6.2

**Comment by krassowski** [comment]
Testing:
-  JupyterLab 3.6.2: ok
-  JupyterLab 4.0.0b1: NOT OK

Do you happen to have jupyterlab-lsp installed? If so, please see https://github.com/jupyter-lsp/jupyterlab-lsp/issues/823

I think it works as expected on JupyterLab 3.6.2 but not on 4.0.0b1:

| 3.6.2 | 4.0.0b1 |
|---|---|
| ![works-ok](https://user-images.githubusercontent.com/5832902/231362431-2e58ef8b-3559-4365-8043-6c8b274532e5.gif) | ![4-0-b1-no-selection](https://user-images.githubusercontent.com/5832902/231363637-2e69b229-41b8-4b71-82ce-f25b852943c1.gif) |

Multi-cursor selection works well on both JupyterLab 3.6.2 and 4.0.0b1:

| 3.6.2 | 4.0.0b1 |
|---|---|
| ![multiple cursors-3 6 2](https://user-images.githubusercontent.com/5832902/231363388-cd4c86a3-5cbb-45ef-b1ae-651819273039.gif) | ![4-0b1-multi-cursors-ok](https://user-images.githubusercontent.com/5832902/231363806-8a3ebd84-0993-4079-a21f-3dde5bd1305a.gif) |

**Comment by krassowski** [comment]
Adding support for block selection in JupyterLab 4.0 is fairly straightforwad as we would just need to enable built-in CodeMirror 6 [rectangularSelection](https://codemirror.net/docs/ref/#view.rectangularSelection) extension.
