### ISSUE TITLE
I can't run a new notebook from JupyterLab

### ISSUE THREAD

**Issue by adonese** [jupyterlab/jupyterlab#1435]
This just happened when I updated jupyter-lab. I got this error `'_xsrf' argument missing from POST` whenever I tried to open a new notebook (it works fine if I try to open an existing one).

**Comment by blink1073** [comment]
Hi @adonese, thank you for the report.  What is the output of `jupyter notebook --version`?  I suspect this is a result of the `4.3.1` release.

**Comment by adonese** [comment]
Yes it's `4.3.1`.

**Comment by blink1073** [comment]
@minrk, is this a matter of making sure all of the `POST` requests in services have a JSON body?

**Comment by minrk** [comment]
@blink1073 the the xsrf token needs to be in the header, or the request needs to be authenticated with an API token. See [here](https://github.com/jupyter/notebook/blob/4.x/notebook/static/base/js/utils.js#L702) for how the legacy js notebook does it.

**Comment by minrk** [comment]
https://github.com/jupyterlab/services/pull/290 should add the xsrf token header. I'm *pretty sure* that I was able to test this and confirm it works, but it's hard to be sure that I'm getting the right version of services in jupyterlab.

**Comment by blink1073** [comment]
Thanks!  I confirmed that the patch works locally.  Now is a good time to cut a 0.12 release of Jlab anyway.

**Comment by blink1073** [comment]
Version 0.12.1 of JupyterLab has the fix.

**Comment by minrk** [comment]
Awesome, thanks for the quick turnaround, @blink1073!

**Comment by ellisonbg** [comment]
Looks like this can be closed (re-open if I didn't interpret thigns correctly)

**Comment by adonese** [comment]
It works! Thank you so much!

**Comment by ellisonbg** [comment]
Great!

**Comment by DSLituiev** [comment]
I am having this very error in version `5.0.0` on all notebooks (Scala, R, Python2.7 etc) other Python3.5, on which jupyter runs. Any practical tips how to handle it? Any chance to fix it other than manually re-installing all the kernels?

**Comment by blink1073** [comment]
Hi @DSLituiev, do you mean you see this error only when running JupyterLab after upgrading the notebook?  As in you can still run the kernels when running `jupyter notebook`?  Also, which version of JupyterLab are you running `jupyter lab --version`?

**Comment by DSLituiev** [comment]
I beg pardon, wrong place. it is jupyter pure.

**Comment by blink1073** [comment]
No worries!  I believe this is the repo you're looking for: https://github.com/jupyter/notebook.

**Comment by ebraminio** [comment]
On a say complicated (behind a remote proxy) jupyter-lab 0.26.5 jupyter-notebook 5.0.0 setup I have I constantly have the same mentioned issue which lab works fine with a currently created notebook but fails on creating a new one, JUST on Safari. I don't see any issue when I use Safari with lab locally, Safari with the remote notebook or Chrome with that remote lab. Feels like the fix somehow is not suitable for Safari or something, is there anything I can do to test my setup or temporarily fix it? Thanks.

**Comment by ebraminio** [comment]
With some logout/login/cleaning cookies tries it is finally fixed for me. Also there is disable xsrf on configs, `c.NotebookApp.disable_check_xsrf = False` but I didn't find that needed to be enabled. Thanks.

**Comment by SushanAlmighty** [comment]
It maybe because you have disabled the cookies....Just allow cookies on the _localhost_ site which gets opened after launching jupyter notebook...
