### ISSUE TITLE
Notification is not displayed but only added to the status bar

### ISSUE THREAD

**Issue by suganya-sk** [jupyterlab/jupyterlab#14357]
## Description

I'm writing a front-end plugin that sends custom notifs to the UI using the [Notifications](https://jupyterlab.readthedocs.io/en/stable/extension/ui_helpers.html#notifications) interface introduced in 3.6.1. I'm noticing that the notifications I send are added to the status bar (count increases near the bell icon) but the notification does not open on its own. Under @krassowski's advice, I've also ensured that `Silence all notifications` is not checked.

How do I ensure a notification is displayed to the user and not just added to the status bar?

I tried setting various values to autoClose (exact code below) but they all resulted in the same effect - the notification did not show up; it was added to the status bar and when I clicked on the bell icon, it opens up as expected but does not close automatically.

```
Notification.emit("This is notif type - error", "error", {autoClose: false});
Notification.emit("This is notif type - warning", "warning");
Notification.emit("This is notif type - default", "default", {autoClose: 10});
```

Original discourse question - [here](https://discourse.jupyter.org/t/how-do-i-ensure-a-notification-is-displayed-to-the-user-and-not-just-added-to-the-status-bar/18869)

I’m using `Jupyterlab 3.6.2` and `@jupyterlab/apputils 3.6.3`. From docs, I dont see this behavior depending on a specific versuion of any other plugins/libraries. 

Could I be using this incorrectly? Thanks in advance!

## Reproduce

1. Build a front-end plugin with the following content - 
```
import {JupyterFrontEnd, JupyterFrontEndPlugin} from '@jupyterlab/application';
import {NotificationManager, Notification} from '@jupyterlab/apputils';

const plugin: JupyterFrontEndPlugin<void> = {
    id: 'send-notifications',
    autoStart: true,
    activate: (app: JupyterFrontEnd) => {
        Notification.emit("This is notif type - error", "error", {autoClose: false});
        Notification.emit("This is notif type - warning", "warning");
        Notification.emit("This is notif type - default", "default", {autoClose: 10});        
    }
};

export default plugin;
```
2. Ensure `@jupyterlab/apputils` is at 3.6.3
3. Install this plugin and start an instance of lab
4. Ensure 'Silence all notifications` is not checked
5. The notifications show up as below -

![image](https://user-images.githubusercontent.com/19615498/231090179-e2a0c5ea-39e8-4949-afc9-ca15ecec1122.png)
`

## Expected behavior

The custom notification opens automatically.

## Context

- Browser and version: Chrome 102
- JupyterLab version: 3.6.2
- @jupyterlab/apputils - 3.6.3

**Comment by suganya-sk** [comment]
I just noticed that the custom notifications are more prominent in the status bar (highlighted in blue) when I set `Check for JupyterLab updates` and `Fetch official Jupyter news` to True in Advanced Settings, like so -

![image](https://user-images.githubusercontent.com/19615498/231097816-f23ae8bf-1139-420e-96d3-ae548f653b6f.png)


Note that I have 6 custom notifs from my plugin. The 7th one is about the availability of 3.6.3. 

I'm not looking to switch on official Jupyter news; I only want to use custom notifications. Is there a way to decouple these?

**Comment by fcollonval** [comment]
@suganya-sk could you trigger the notifications after some delays?

As your code is emitting notifications at plugin activation, there is a high chance the notifications UI is not yet activated.

> I want to highlight that autoClose is in milliseconds. So 10 is a very small time.

**Comment by suganya-sk** [comment]
Thank you, adding a delay helped the issue.

**Comment by andrii-i** [comment]
Closing as solved. Thank you @suganya-sk, @fcollonval
