### ISSUE TITLE
Upgrade popper.js in @jupyterlab/application

### ISSUE THREAD

**Issue by virendray** [jupyterlab/jupyterlab#14361]
@jupyterlab/application using deprecated popper.js. As per our firm's security policy we are not allowed to use this package to build custom extensions. 

popper.js@1.16.1:
    Deprecation notice: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
    Dependency path (1 of 92): @jupyterlab/application@3.6.2 ‣ @jupyterlab/ui-components@3.6.2 ‣ @blueprintjs/core@3.54.0 ‣ popper.js@1.16.1

**Comment by JasonWeill** [comment]
I don't see a reference to this package in the 4.0.0 code; 4.0.0 is currently in beta, but will be ready for general availability soon.

**Comment by fcollonval** [comment]
Unfortunately this is a dependency of dependency (aka @blueprintjs/core) and the latest version of BluePrintJS for 3.x is 3.54.0 (the currently provided version). So it is unlikely that we will update BluePrintJS to the next major version in the 3.x branch of JupyterLab as it will be a API breaking changes.

**Comment by fcollonval** [comment]
> JupyterLab 4.0.0 is planned for mid May. It will drop those dependencies.
