### ISSUE TITLE
Codecellconfig.fontfamily is ignored in Jupyterlab on AWS sagemaker

### ISSUE THREAD

**Issue by lowejohn** [jupyterlab/jupyterlab#14377]
## Description

In Sagemaker on AWS, Jupterlab (3.6.1) is not respecting the settings defined in Advanced Settings Editor --> Notebook --> codeCellConfig --> fontFamily. They appear to be getting overridden or replaced so that the code editing font is always set to be Amazon Ember, which is a non-monospace font.

I have tested this in multiple browsers and on multiple separate computers. 

## Reproduce

Default behaviour when logging in for the first time:

![image](https://user-images.githubusercontent.com/58014136/231904493-fb00d2cb-23e7-40ca-916d-0fe96c6fc989.png)

Changing font size and line height is respected:

![image](https://user-images.githubusercontent.com/58014136/231904728-7fdf425d-f711-44b9-98f1-61e2c9a31b87.png)

![image](https://user-images.githubusercontent.com/58014136/231904571-b4ad8a39-cc62-4a45-ae2c-9f0c98681900.png)

Changing font family is not respected:
![image](https://user-images.githubusercontent.com/58014136/231904766-9480c63f-1529-467f-9666-3d6b6d807420.png)
![image](https://user-images.githubusercontent.com/58014136/231904777-b049e1f1-09cc-4f6d-8452-695bc017ce8a.png)

I don't know enough CSS to fully diagnose the issue. I can see that there is a codemirror font being set correctly at one point in the CSS

![image](https://user-images.githubusercontent.com/58014136/231904980-fcbdd331-009e-4eb7-8882-3cd4f3990e03.png)

The codemirror css seems to be setting the right font:

![image](https://user-images.githubusercontent.com/58014136/231905210-c856738f-a8f4-4b66-9b64-e48e54d7416d.png)

But then everything from codemirror-scroll and below (which includes the codemirror lines) has font-family set to Amazon Ember:

![image](https://user-images.githubusercontent.com/58014136/231905386-2cc2a454-fa58-4ba9-9a1e-8d8f0b82de5e.png)

Changing this fixes the issue - but also changes the font of other parts of the UI (like the tabs at the top visible here):

![image](https://user-images.githubusercontent.com/58014136/231905457-1d379e08-e5c4-46e6-8f44-38093a6c06a3.png)

**Comment by JasonWeill** [comment]
@lowejohn Thanks for opening this issue! The custom theme that SageMaker uses is not part of this open source JupyterLab repository. I am a developer in the AWS SageMaker organization, although I don't personally maintain this theme, and we will need to follow up on this using internal systems.

Thanks again for your interest in improving JupyterLab in SageMaker Studio.

**Comment by dfd** [comment]
This also seems to impact the Text Editor font family setting too, FYI.  Line height and font size seem to work, but not font family.
