### ISSUE TITLE
Install error jupyterlab on Mac 

### ISSUE THREAD

**Issue by youngtackpark** [jupyterlab/jupyterlab#1438]
Hi

I am trying yo upgrade jupyter lab but failed due to the following errors.
I was trying to uninstall first using "conda uninstall jupyterlab" but failed
Any help would be appreciated

---
Linking packages ...

CondaOSError: OS error: failed to link (src=u'//anaconda/pkgs/setuptools-32.1.0-py27_0/lib/python2.7/site-packages/pkg_resources/__init__.py', dst='//anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py', type=1, error=OSError(17, 'File exists'))

**Comment by blink1073** [comment]
Hi @youngtackpark, can you please try updating conda itself `conda update conda` and then try again?  I think this might be related to https://github.com/conda/conda/issues/3494.

**Comment by jasongrout** [comment]
Closed since the OP didn't reply. @youngtackpark, feel free to post a comment if you still need help.
