### ISSUE TITLE
"Click to add a cell" is flaky on CI

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14385]
> `jupyterlab/galata/test/jupyterlab/notebook-create.test.ts-snapshots/run-cells-jupyterlab-linux.png` needs to be fixed as the expectation is incorrect/"click to add a cell is" problematic here:

![run-cells-expected](https://user-images.githubusercontent.com/5832902/232229420-243b2987-f964-4de7-80f3-22ffe3b45848.png)

_Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab/issues/14344#issuecomment-1509848101_

**Comment by krassowski** [comment]
There are actually two similar test cases one in galata project and one in jupyterlab, both are flaky:

![Screenshot from 2023-04-23 20-44-14](https://user-images.githubusercontent.com/5832902/233861930-a8c4c324-caba-42f6-99f5-4e4bd7eef591.png)

The other one is `galata/test/galata/notebook.spec.ts-snapshots/run-cells-galata-linux.png`

This is leading to many failures and is high burden, sometimes we need to restart the CI 4 times delaying a merge by ~4 hours.

**Comment by JasonWeill** [comment]
Possible mitigation for this: apply masks to the screen shot to avoid failures on just the "click to add a cell" UI component

**Comment by krassowski** [comment]
This is due to a difference in `.jp-WindowedPanel-inner` height.

Good snapshot:

![good](https://user-images.githubusercontent.com/5832902/234998105-87fc70a7-55de-4cbd-b4d3-d519653eadee.png)

Bad snapshot:

![bad](https://user-images.githubusercontent.com/5832902/234998182-e34efce4-a001-4529-82e5-5b0076928852.png)

The height is too short - it does not include output:

![Screenshot from 2023-04-27 22-47-17](https://user-images.githubusercontent.com/5832902/234998380-8e95cafb-3185-4e64-948e-229c4d3301f4.png)

HTML files for ease of inspection:

[good-snapshot.html.zip](https://github.com/jupyterlab/jupyterlab/files/11348226/good-snapshot.html.zip)
[problematic-snapshot.html.zip](https://github.com/jupyterlab/jupyterlab/files/11348227/problematic-snapshot.html.zip)

**Comment by gabalafou** [comment]
Steps to reproduce the "height is too short" bug in latest JupyterLab:

1. Simulate an iPad or other touch device using browser dev tools
2. Create a new notebook
3. Create a cell, any kind of cell, add some text
4. Add a markdown cell above the cell you just created
5. Edit the text in the markdown cell so that it's an h1, for example: `# foo`
6. Either run the markdown cell by pressing the arrow ▶︎ button in the toolbar, or by selecting "Run Selected Cell" from the top menu bar, or by running "Run Selected Cell" from the command palette **but not by** using the keyboard shortcut

**Comment by gabalafou** [comment]
Here's a screen recording of me doing the steps to reproduce (I omitted the first step of simulating a tablet device from the dev tools):

 

https://user-images.githubusercontent.com/317883/235062075-03704ab0-e532-4e8c-a7ad-39a051aba879.mov

**Comment by gabalafou** [comment]
As far as I can tell, the culprit seems to be about the difference between lines 539 and 604 of [actions.tsx](https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook/src/actions.tsx#539)

Line 539 is in the `run` action:

```ts
Private.handleRunState(notebook, state, false);
```

Line 604 is in the `runAndAdvance` action:

```ts
Private.handleState(notebook, state, true);
```

They each call different function but those functions are very similar and the real culprit seems to lie in the third argument passed, which determines whether `notebook.scrollToItem` will be called after the cell action.

I'm not exactly sure why that results in the different UI behavior. That's as far as I was able to get today.

**Comment by krassowski** [comment]
Thank you for reproducible example @gabalafou. It appears that the height is only set in private `_update()` method:

https://github.com/jupyterlab/jupyterlab/blob/ec07704ef0196e4298692d347c8e32124bc33dfa/packages/ui-components/src/components/windowedlist.ts#L986-L989

which is only called `onUpdateRequest` (with a delay):

https://github.com/jupyterlab/jupyterlab/blob/ec07704ef0196e4298692d347c8e32124bc33dfa/packages/ui-components/src/components/windowedlist.ts#L904-L916

What we need to improve is to ensure that height gets updated when cell size changes (whether because it was rendered, it had an output appear, etc). I imagine that `onUpdateRequest` is not guaranteed to run on all such cases, and I think that all `handleState` argument changes is whether update request is emitting, masking the problem rather than addressing the core issue.

We could use resize observer on cells - but we would need to benchmark if this does not introduce too much overhead for large notebook. @fcollonval thoughts?

**Comment by fcollonval** [comment]
Thanks both for the investigation.

> We could use resize observer on cells - but we would need to benchmark if this does not introduce too much overhead for large notebook. @fcollonval thoughts?

In fact there is already a resize observer (to cover case of new outputs e.g.): 

https://github.com/jupyterlab/jupyterlab/blob/acb87d51ed0c489fb5a8f6781059024cf62f255b/packages/ui-components/src/components/windowedlist.ts#L920

I'll try to have a look.

**Comment by gabalafou** [comment]
Awesome. I think I can also explain why the tests were flakey. The tests use the "run all" command. So I played around with the "run all" command, and I found that when there were multiple cells, the "run all" command would sometimes reproduce the visual bug, sometimes not (I could only get it to reproduce the bug on the first call to "run all"; subsequent calls wouldn't reproduce unless I deleted all of the cells). Whereas when I only had one cell—a markdown cell with an H1—it would always recreate the visual bug.

**Comment by gabalafou** [comment]
I think the "run all" command essentially sets up a race condition between the code that clears the private variable `WindowedList._scrollToItem` and the widget resize handlers. See https://github.com/jupyterlab/jupyterlab/pull/14459#pullrequestreview-1406367617 for context. 

When you only run one cell—the H1 markdown—the widget resize handler always gets called before the `_scrollToItem` has been cleared, resulting in a reproducible bug, whereas when you run several cells, `_scrollToItem` may get cleared before the widget resize handler for the H1 markdown gets called and you won't see any visual bug.
