### ISSUE TITLE
Add accessibility-focused documentation to the developer documetation

### ISSUE THREAD

**Issue by steff456** [jupyterlab/jupyterlab#14399]
### Problem/Proposed Solution

We can expand the information that is present in the current developer documentation with some information about how to develop and contribute to the project having some accessibility best practices in mind. 

Initially, we plan to add the following information:

- Best practices and useful tools for development 
- Link to [accessibility documentation](https://jupyter-accessibility.readthedocs.io/en/latest/)
- Link to [testing repo](https://github.com/Quansight-Labs/jupyter-a11y-testing)

**Comment by JasonWeill** [comment]
Related to #14396 (same author)
