### ISSUE TITLE
Action buttons are not completely right-aligned in Notifications popup 

### ISSUE THREAD

**Issue by andrii-i** [jupyterlab/jupyterlab#14398]
## Description

In JupyterLab, action buttons in dialogs are usually right-aligned. In Notifications popup/toast they are not completely right-aligned, are much closer to the center of the popup:  

![Screenshot 2023-04-17 at 9 58 45 AM](https://user-images.githubusercontent.com/26686070/232557525-7ca408c7-e165-4597-919a-41fda851bbb3.png)
![Screenshot 2023-04-17 at 8 45 19 AM](https://user-images.githubusercontent.com/26686070/232557537-f1fd603e-0884-4cf7-b82b-403b3d57295a.png)

## Reproduce

1. Click bell icon in the bottom right corner of the screen to see a notification
2. Try deleting a notebook to see a dialog
3. Note action buttons alignment differences

## Expected behavior

Action buttons in notification popup are styled consistently with action buttons in other dialogs. 

It looks like buttons in notification popup are right-aligned within their component but there is another area blocked by the "close" icon on the right.  

![Screenshot 2023-04-17 at 10 12 32 AM](https://user-images.githubusercontent.com/26686070/232560088-8b39d104-dc6c-409d-b10e-7cee3accae93.png)
![Screenshot 2023-04-17 at 8 45 30 AM](https://user-images.githubusercontent.com/26686070/232559847-5ca81c6d-1e7e-46ff-a18d-56d5d498478a.png)

**Comment by JasonWeill** [comment]
Related notification styling bugs: #13993, #13992
