### ISSUE TITLE
Feature Request: When undo or redo is executed within a cell, it only works for the code within this cell

### ISSUE THREAD

**Issue by jiahe224** [jupyterlab/jupyterlab#14390]
This allows for consistent operation with classic notebooks and is more conducive to seamless upgrades.

**Comment by krassowski** [comment]
@jiahe224 do you think that https://github.com/jupyterlab/jupyterlab/issues/10791 addresses your request?

**Comment by fcollonval** [comment]
Could you try JupyterLab [3.6.2]9https://github.com/jupyterlab/jupyterlab/releases/tag/v3.6.2) or above that contains the fix mention by Mike?

**Comment by jiahe224** [comment]
> @jiahe224 do you think that #10791 addresses your request?

@krassowski It seems so. First of all, I propose a possible consensus, that is, notebooks are more suitable for building and testing codes in the early stage. In this case, each cell is a small module used to realize corresponding functions. Then, for the cell When the code is modified, the cursor is blinking in the cell, Ctrl-Z and Ctrl-Y should only take effect on the historical editing in this cell, not the entire notebook, otherwise some finalized cells may be deleted. When the cursor is not in a specific cell, that is, in the command mode of the classic notebook, the Z key will restore the deleted cell, but the order of the cells will be disordered when the classic notebook restores the deleted cell. I hope that notebook 7 based on jupyter lab can improve. In fact, I gave up jupyter lab and continued to use classic notebooks because Ctrl-Z acts on the entire notebook.

**Comment by jiahe224** [comment]
> Could you try JupyterLab [3.6.2]9https://github.com/jupyterlab/jupyterlab/releases/tag/v3.6.2) or above that contains the fix mention by Mike?

Thanks, I'll test it when jupyter notebook 7 comes out, it's based on jupyter lab.
