### ISSUE TITLE
Console history cell has unexpected cursor

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#14409]
## Description

![cursor-console-bug](https://user-images.githubusercontent.com/8435071/233399509-bce81c5d-724f-4108-98cd-9ac1a909ea35.gif)

## Reproduce

1. Type the code
2. Press Shift+Enter to execute the cell

## Expected behavior

No cursor in console history cell

## Context

- Operating System and version:  Debian
- Browser and version:  Firefox
- JupyterLab version:  master (~4.0.0b1)

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
This looks related to https://github.com/jupyterlab/jupyterlab/issues/14271.

**Comment by fcollonval** [comment]
Thanks for linking the issue - I was looking for it but did not find it.
