### ISSUE TITLE
Initial replace with empty text inserts "undefined"

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14419]
## Description

In notebook and file editor when replacing search matches the replace text defaults to `undefined` which is then inserted (instead of empty string).

It works correctly if you type something in the search field and remove later.

## Reproduce

![replace-with-empty-gives-undefined](https://user-images.githubusercontent.com/5832902/233845166-d1d25507-4684-4178-aa7e-8bdd1ed45f3c.gif)

## Expected behavior

Matched strings are replaced with empty strings (=removed)

## Context

4.0.0b1

**Comment by andrii-i** [comment]
@krassowski wanted to ask if you are already working on this?
