### ISSUE TITLE
Docs fail to build on the latest commit on CI

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14422]
## Description

Looks like the docs fail to build on CI on the latest commit: 85c3032bfbb40bcab4404a0142210fbdb570de39

![image](https://user-images.githubusercontent.com/591645/233978495-60a435a1-51ec-4d0c-80de-8bea85c55262.png)

## Reproduce

Example run: https://github.com/jupyterlab/jupyterlab/actions/runs/4783980467/jobs/8507860349

This happens after re-running the check

## Expected behavior

The check should pass.

## Context

Maybe one of the latest PRs broke it?

**Comment by krassowski** [comment]
> Maybe one of the latest PRs broke it?

I think that it fails because we are running with `-W` (treat warnings as errors) and there is a new deprecation warning:

> WARNING: The pre-Sphinx 1.0 'intersphinx_mapping' format is deprecated and will be removed in Sphinx 8. Update to the current format as described in the documentation. Hint: "intersphinx_mapping = {'<name>': ('https://docs.python.org/', None)}".https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping

I think we just need to update (or remove):

https://github.com/jupyterlab/jupyterlab/blob/85c3032bfbb40bcab4404a0142210fbdb570de39/docs/source/conf.py#L381-L382

It seems it now should be:

```python
intersphinx_mapping = {'python': ('https://docs.python.org/3', None)}
```

**Comment by jtpio** [comment]
Thanks @krassowski for the hint!

Just opened https://github.com/jupyterlab/jupyterlab/pull/14423 to see if that fixes it.
