### ISSUE TITLE
jlab 4.0.0b2 breaks jupytext

### ISSUE THREAD

**Issue by parmentelat** [jupyterlab/jupyterlab#14438]
## Description

Cannot open a text-based notebook under 4.0.0b2

![image](https://user-images.githubusercontent.com/4519227/234606692-6ee85fd0-fb3a-4a2c-a45c-7c3157f4745d.png)

## Reproduce

1. Go to the binder
2. run `%pip install jupytext` in a notebook
3. restart kernel
4. git clone any repo with e.g. md:myst notebook
5. open with ... jupytext notebook

I am getting this screenshot

![image](https://user-images.githubusercontent.com/4519227/234606402-a0883928-8dfb-48da-afa9-166030fff21d.png)

as an aside the js console has complaints like  
`t.currentWidget.context.model.metadata.has is not a function`

## Expected behavior

I take it there has been a breaking change in the extension API, but it is crucial to be able to open text-based notebooks !

Please instruct if another version of jupytext is required and if so which version would that be ?

---

ps. I came across this in the context of 
https://discourse.jupyter.org/t/how-to-subscribe-to-changes-in-cells-metadata/19068

is there a place where I can find the description of the changes in the metadata APIs ?

thanks !

**Comment by krassowski** [comment]
Thank you for reporting! Your reproduction instructions do not include "reload JupyterLab" step. Restarting kernel is not enough to load newly installed extension. This works fine for me when testing on Binder ([gist](https://gist.github.com/krassowski/847732eb6c16e168fb4c0b16d9706142)):

![works-ok](https://user-images.githubusercontent.com/5832902/234632098-296fa65b-e449-49f9-9367-1eaca26dcbf1.gif)

Regarding `t.currentWidget.context.model.metadata.has is not a function` error: this is reproducible, and will probably require changes in jupytext to make it compatible with JupyterLab 4. In JupyterLab 4 [`NotebookModel.metadata`](https://jupyterlab.readthedocs.io/en/latest/api/classes/notebook.NotebookModel-1.html#metadata) is a read-only copy of the metdata implemented as a JSON object. I think that you can use standard `in` operator to check for key presence.
