### ISSUE TITLE
Run python/markdown file

### ISSUE THREAD

**Issue by Firestar-Reimu** [jupyterlab/jupyterlab#14436]
Now jupyterlab cannot run a python `.py` file nor render a markdown `.md` file. It just need a `Run` triangle button.

**Comment by krassowski** [comment]
Thank you for opening the issue.

> Now jupyterlab cannot run a python `.py` file

It looks like a duplicate of https://github.com/jupyterlab/jupyterlab/issues/12172

> nor render a markdown `.md` file.

This is incorrect. You can right-click on file to render Markdown preview:

![Screenshot from 2023-04-26 17-22-30](https://user-images.githubusercontent.com/5832902/234640086-a2d2c086-123d-4310-87e9-9943319fef1e.png)

or

![Screenshot from 2023-04-26 17-22-38](https://user-images.githubusercontent.com/5832902/234640092-0e850d25-272a-4b71-8522-3ac133065f06.png)

resulting in

![Screenshot from 2023-04-26 17-23-11](https://user-images.githubusercontent.com/5832902/234640097-0bd7d481-e297-46d3-aa26-332fa5a18761.png)

**Comment by Firestar-Reimu** [comment]
Thanks!
