### ISSUE TITLE
IPython 8 autocomplete not working for nested lookup

### ISSUE THREAD

**Issue by Hoxbro** [jupyterlab/jupyterlab#14457]
## Description

Auto-compete without Jedi seems to be broken with IPython >=8 for nested lookup. 

## Reproduce

If I run this code:

``` python 
import numpy as np
import IPython
%config IPCompleter.use_jedi = False

IPython.__version__
```

And then create a new cell and type `np.` it will give a autocomplete. But if I try to autocomplete again, it does not give me anything.  This seems to be happen for IPython >= 8

![image](https://user-images.githubusercontent.com/19758978/235108149-31f4f2a8-c729-49be-adbb-c72b5e8668ea.png)

For IPython < 8 the nested autocomplete is working:

![image](https://user-images.githubusercontent.com/19758978/235108248-6bf8a0ab-f141-43bf-980f-1d81ff10b9ec.png)

## Expected behavior

I would expect autocomplete to work also for nested lookups. 

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 3.6.3

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
@Hoxbro since this is an IPytohn-specific issue, it would have been better reported in IPython repository where you could find https://github.com/ipython/ipython/issues/14028 which was already fixed by https://github.com/ipython/ipython/pull/14029. Please upgrade IPython :)

**Comment by Hoxbro** [comment]
I tried running it in IPython but did not know that it also used Jedi. So assumed it was a Jupyterlab issue. Sorry about the noise. 

I will upgrade my IPython when it is live on `conda-forge`. Thank you for the great project!
