### ISSUE TITLE
Advanced Settings Editor is empty

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14454]
## Description

Advanced Settings Editor is empty.

## Reproduce

Using `4.0.0rc0` on Binder and opening the Advanced Settings Editor :

https://user-images.githubusercontent.com/591645/235082892-71e03cc8-43a3-48d4-b7a2-e9e9313643ed.mp4

## Expected behavior

The Advanced Settings Editor should show the settings.

## Context

This was discovered in https://github.com/jupyter/notebook/issues/6854 first.

**Comment by andrii-i** [comment]
Thank you for opening this issue. Looks like a duplicate of #14440.

**Comment by jtpio** [comment]
It does, thanks!

I searched for "Advanced Settings Editor" before opening the issue and https://github.com/jupyterlab/jupyterlab/issues/14440 mentions "JSON Settings".

Closing in favor of https://github.com/jupyterlab/jupyterlab/issues/14440
