### ISSUE TITLE
Default the Notebook Windowing mode to `none` or `defer`?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14455]
### Problem

After using the betas and `4.0.0rc0`, the default notebook experience still feels off and sometimes frustrating to work with.

It sometimes feels like a "regression" compared to `3.5.x` or `3.6.x` especially when working with rather small notebooks.

### Proposed Solution

Default `windowingMode` to `none` here:

https://github.com/jupyterlab/jupyterlab/blob/ec07704ef0196e4298692d347c8e32124bc33dfa/packages/notebook-extension/schema/tracker.json#L799-L804

Document how to improve performance by using the other modes (opt-in).

### Additional context

Some of the issues with the default notebook windowing mode that might be related:
- https://github.com/jupyterlab/jupyterlab/issues/13343
- https://github.com/jupyterlab/jupyterlab/issues/14379

This is based on the observation that most notebooks will probably not benefit from the advanced notebook rendering mode. But will instead inherit the issues mentioned above.

This study on millions of notebooks shows the distribution of the number of code cells in a notebook: 

![image](https://user-images.githubusercontent.com/591645/235086198-5e7882a3-5bd1-438b-9cf4-ae8c8a34ca3a.png)

https://blog.jetbrains.com/datalore/2020/12/17/we-downloaded-10-000-000-jupyter-notebooks-from-github-this-is-what-we-learned/

**Comment by jtpio** [comment]
Defaulting `windowingMode` to `none` for 4.0 to make performance an opt-in feature.

Then maybe consider switching back to `full` in 4.1 or 4.x?

**Comment by jtpio** [comment]
Adding to the 4.0 milestone so it can at least be discussed.

**Comment by jtpio** [comment]
I had a quick call with @fcollonval today to discuss more the implications of switching the default.

Some arguments for **not** using `none` as the default:

- if windowing is not the default anymore, it will be more difficult to test and improve it over time since contributors will be paying less attention to it, and maybe less users will be using it
- other editors like VS Code and CoCalc have telemetry in place, and they have also implemented virtual notebook rendering to improve performances. This might suggest many users benefit from that feature if they have it by default (just a guess). And invalidate the claim made in https://github.com/jupyterlab/jupyterlab/issues/14455#issue-1688068628 that most notebooks are small notebooks.

A middle-ground could be to default to `defer` instead. Maybe worth trying in a PR and see what people think. It could also be a more appropriate default for Notebook 7 since Notebook 7 only has 1 notebook on the page at a time (no tab switching): https://github.com/jupyter/notebook/pull/6855

In any case the docs added in https://github.com/jupyterlab/jupyterlab/pull/14444 will already help provide answers to these questions, and let users switch the setting as they wish.

**Comment by krassowski** [comment]
> A middle-ground could be to default to `defer` instead

This the behaviour that we have in 3.x with `renderCellOnIdle` and `numberCellsToRenderDirectly` (but with a different implementation).

**Comment by jtpio** [comment]
This is issue was mentioned during the meeting yesterday, but I don't think it was discussed: https://github.com/jupyterlab/team-compass/issues/170#issuecomment-1533413649

Since JupyterLab 4 final release is expected next week before JupyterCon, should we close this issue, or change the default to `defer`?

**Comment by fcollonval** [comment]
Thanks for the ping @jtpio - indeed it was not discussed. As we lean toward releasing the final before JupyterCon (aka in a week), I'll open a PR to change the default to `defer` and merge it before cutting a new RC (that is likely to be the last one). So that more people will be able to test with that rendering method.

**Comment by krassowski** [comment]
> if windowing is not the default anymore, it will be more difficult to test and improve it over time since contributors will be paying less attention to it, and maybe less users will be using it

If we switch to `defer` for 4.0, I would think that we should announce plan for switching to `full` in 4.1. This should give users enough time to test it and we would isolate the changes due to this from other changes in 4.0

**Comment by fcollonval** [comment]
I like that idea.
