### ISSUE TITLE
"Add new cell" button is off after switching the notebook windowing mode to `none`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14453]
## Description

"Add new cell" button is off after switching the notebook windowing mode to `none`.

## Reproduce

With JupyterLab 4.0.0rc0 on Binder: https://gist.github.com/jtpio/4e9a3d435d7c3950dc4150c10abbb1d7

https://user-images.githubusercontent.com/591645/234995054-16a09ec3-3324-4edc-a5d6-eee263d80c4f.mp4

## Expected behavior

The button should still be at the bottom below the last cell.

## Context

- Browser and version: Firefox 112
- JupyterLab version: `4.0.0rc0`

**Comment by krassowski** [comment]
Good find! It is also off when the mode is `full` under some circumstances which we discuss in detail in https://github.com/jupyterlab/jupyterlab/issues/14385. We probably could address both by moving the location of the button in the DOM tree, but I am not sure if this would be goodchoice maintenance-wise.
