### ISSUE TITLE
Invoking completer make notebook to scoll and put completer in wrong position

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1446]
See attached screenshot.

- Cell need to be long
- in the given screenshot I type "o","s","<tab>", speed does nto matter. 
- 'pos' get autofilled to "positional" (off screen)
   - it seem to happen only when there is a common prefix that get completed.
- the 4,3,2,1 is just to distinguish the beginning from the end of the gif.

![jump](https://cloud.githubusercontent.com/assets/335567/21562264/f2101a14-ce77-11e6-8385-646a4e5d217c.gif)

A second press of tab put the completer in the right position, at the bottom of the screen where the cursor is now.

**Comment by afshin** [comment]
Whoa, that's a good one. Thanks, I'll take a look at it in the coming week!

**Comment by ellisonbg** [comment]
May only show up with code cells that are larger than the notebook panel. Good catch!

**Comment by ellisonbg** [comment]
@afshin do I remember that you fixed this one?
