### ISSUE TITLE
Windowing makes changing notebooks distracting

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#14461]
## Description

Given a notebook with many cells, switching to it renders it cell by cell instead of all at once. This is very distracting.

## Reproduce
My windowing mode is set to "Full":
![Windowing](https://user-images.githubusercontent.com/1813603/235181708-94168361-2a71-4515-88c9-c0053ab6ee35.gif)

## Expected behavior

Load of all cells all at once and keep tab switching fast.

## Context
Lab@4.0.0b2

CC @jtpio @fcollonval

**Comment by fcollonval** [comment]
Thanks @mlucool for reporting. Would you mind
- providing the browser you were using
- clarifying the screencast - did you refresh the browser with the two notebooks loaded initially then switching to the first tab?

**Comment by fcollonval** [comment]
Thanks @mlucool for the clarification
