### ISSUE TITLE
Add version info to help

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#1447]
I just had a confusing issue whereby I wasn't running the version of jupyterlab I thought I was. It would have been helpful if I could quickly check from the ui the exact version that it was running.

**Comment by blink1073** [comment]
Good call, thanks!  Dev note, here is what `Help > About` looks like in Jupyter Notebook:

<img width="631" alt="screen shot 2017-01-03 at 11 00 14 am" src="https://cloud.githubusercontent.com/assets/2096628/21615622/e8401b72-d1a3-11e6-9090-fab8ed95ffe9.png">

**Comment by ellisonbg** [comment]
Probably better to implement this as a widget in the main area rather than a dialog as users may want to do other stuff (debug) while looking at it.

**Comment by afshin** [comment]
cf. https://github.com/jupyterlab/jupyterlab/pull/1518

**Comment by damianavila** [comment]
#1518 was merged, so I guess this can be closed :wink:

**Comment by dhirschfeld** [comment]
Yep, closed!
