### ISSUE TITLE
For the life of me I cant figure out why I cannot install jupyter lab on mingw python 3.10 with pip

### ISSUE THREAD

**Issue by Kreijstal** [jupyterlab/jupyterlab#14476]
## Description

it fails because it somehow uses a dependency (ring 0.16) that does not compile under mingw. jupyter is installed python is 3.10 on mingw shell
## Reproduce

1. "install" rustup (because you need cargo for jupyterlab now?), since we do not have admin access we configure it to use the x86-64-w64-mingw32-gcc toolchain
2. install [scoop](https://scoop.sh/)
3. scoop install msys2
4. get on mingw
5. pacman -S --needed base-devel mingw-w64-x86_64-toolchain
6. pacman -S mingw-w64-x86_64-python
7. pacman -S mingw-w64-x86_64-python-pip

type `pip install jupyterlab` on mingw

## Expected behavior
should install

## Context

<details><summary>Command Line Output</summary>
2&>1 >debug.txt didnt work in windows powershell for some reason
<pre>
pip install -vvv jupyterlab 
</pre>

[kre.txt](https://github.com/jupyterlab/jupyterlab/files/11373870/kre.txt)
</details>

Essentially a package depends on maturin, which is a rust package which  contains an [obscene](https://crates.live/maturin/0.12.11) amount of dependencies   from crates.io, some of those dependencies contain the [infamous](https://github.com/libp2p/rust-libp2p/issues/1396) ring dependency, which is not even written in Rust. Anyways, the point is, I can not get jupyter lab to work.

**Comment by JasonWeill** [comment]
Thanks for your report! Are you able to install JupyterLab in any other way on Windows, such as via WSL2, conda, mamba, or with the [JupyterLab Desktop](https://github.com/jupyterlab/jupyterlab-desktop) installer?

**Comment by Kreijstal** [comment]
> Thanks for your report! Are you able to install JupyterLab in any other way on Windows, such as via WSL2, conda, mamba, or with the [JupyterLab Desktop](https://github.com/jupyterlab/jupyterlab-desktop) installer?

No, as these require administrative access, which I do not have.

**Comment by fcollonval** [comment]
@Kreijstal you can use the pre release of JupyterLab 4 (we are at the release candidate phase). We externalize the rust dependency in a separate extension.

To install a pre release version:

```sh
pip install --pre jupyterlab
```

**Comment by Kreijstal** [comment]
> ```shell
> pip install --pre jupyterlab
> ```

I'll just leave this here.
![grafik](https://user-images.githubusercontent.com/2415206/235872973-22c7117c-b7cb-4782-ba6d-ae706b267141.png)

**Comment by andrii-i** [comment]
Closing as solved
