### ISSUE TITLE
Error requiring the IEditorTracker

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyterlab#14474]
Error requiring the IEditorTracker

## Description

```
node_modules/@jupyterlab/fileeditor/lib/toc/factory.d.ts:24:5 - error TS2416: Property 'createNew' in type 'EditorTableOfContentsFactory' is not assignable to the same property in base type 'TableOfContentsFactory<IDocumentWidget<FileEditor, IModel>>'.
  Type '(widget: IDocumentWidget<FileEditor, IModel>, configuration?: IConfig | undefined) => TableOfContentsModel<IEditorHeading, IDocumentWidget<...>>' is not assignable to type '(widget: IDocumentWidget<FileEditor, IModel>, configuration?: IConfig | undefined) => TableOfContentsModel<IHeading, IDocumentWidget<FileEditor, IModel>>'.
    Call signature return types 'TableOfContentsModel<IEditorHeading, IDocumentWidget<FileEditor, IModel>>' and 'TableOfContentsModel<IHeading, IDocumentWidget<FileEditor, IModel>>' are incompatible.
      The types of 'activeHeadingChanged' are incompatible between these types.
        Type 'ISignal<IModel<IEditorHeading>, IEditorHeading | null>' is not assignable to type 'ISignal<IModel<IHeading>, IHeading | null>'.
          Type 'IModel<IEditorHeading>' is not assignable to type 'IModel<IHeading>'.
            Types of property 'toggleCollapse' are incompatible.
              Type '(options: { heading?: IEditorHeading | undefined; collapsed?: boolean | undefined; }) => void' is not assignable to type '(options: { heading?: IHeading | undefined; collapsed?: boolean | undefined; }) => void'.
                Types of parameters 'options' and 'options' are incompatible.
                  Type '{ heading?: IHeading | undefined; collapsed?: boolean | undefined; }' is not assignable to type '{ heading?: IEditorHeading | undefined; collapsed?: boolean | undefined; }'.
                    Types of property 'heading' are incompatible.
                      Type 'IHeading | undefined' is not assignable to type 'IEditorHeading | undefined'.
                        Type 'IHeading' is not assignable to type 'IEditorHeading'.

24     createNew(widget: IDocumentWidget<FileEditor, DocumentRegistry.IModel>, configuration?: TableOfContents.IConfig): TableOfContentsModel<IEditorHeading, IDocumentWidget<FileEditor, DocumentRegistry.IModel>>;
```
I think the error comes from these lines:

- [ISignal\<TableOfContents.IModel\<H>, H | null>](https://github.com/jupyterlab/jupyterlab/blob/acb87d51ed0c489fb5a8f6781059024cf62f255b/packages/toc/src/model.ts#L54)
- [ISignal\<TableOfContents.IModel\<H>, H | null>](https://github.com/jupyterlab/jupyterlab/blob/acb87d51ed0c489fb5a8f6781059024cf62f255b/packages/toc/src/model.ts#L61)
- [ISignal\<TableOfContents.IModel\<H>, void>](https://github.com/jupyterlab/jupyterlab/blob/acb87d51ed0c489fb5a8f6781059024cf62f255b/packages/toc/src/model.ts#L93)

The public API uses `TableOfContents.IModel<H>` while each property uses `TableOfContentsModel<H, T>`. See:

- https://github.com/jupyterlab/jupyterlab/blob/acb87d51ed0c489fb5a8f6781059024cf62f255b/packages/toc/src/model.ts#L248
- https://github.com/jupyterlab/jupyterlab/blob/acb87d51ed0c489fb5a8f6781059024cf62f255b/packages/toc/src/model.ts#L245
- https://github.com/jupyterlab/jupyterlab/blob/acb87d51ed0c489fb5a8f6781059024cf62f255b/packages/toc/src/model.ts#LL244C41-L244C67
- https://github.com/jupyterlab/jupyterlab/blob/acb87d51ed0c489fb5a8f6781059024cf62f255b/packages/toc/src/model.ts#L29-L36

## Reproduce
Create a new extension for lab 4 from the [cookiecutter](https://github.com/jupyterlab/extension-cookiecutter-ts/tree/4.0) and use the following sniped to create a plugin that requires the IEditorTracker.
```
import { IEditorTracker } from '@jupyterlab/fileeditor';
const plugin: JupyterFrontEndPlugin<void> = {
  id: 'test_ext:plugin',
  description: 'x',
  autoStart: true,
  requires: [IEditorTracker],
  activate: (app: JupyterFrontEnd, tracker: IEditorTracker) => {
    console.log('JupyterLab extension test_ext is activated!');

    tracker.currentChanged.connect(() => console.debug("Doc changed"));
  }
};
```

## Context

JupyterLab version: 4.0.0rc0

cc @fcollonval

**Comment by fcollonval** [comment]
I tagged this as release blocker for 4.0.0 as it requires to change the API.
