### ISSUE TITLE
Completer widget not hiding when TabBar is clicked to change notebooks

### ISSUE THREAD

**Issue by nishikantparmariam** [jupyterlab/jupyterlab#14496]
## Description

When completer is active and tab bars are clicked to change notebook tabs then the completer widget is still visible. Ideally, it should hide after clicking anywhere on the screen including tab bars. See this GIF:

![completer-not-hiding](https://user-images.githubusercontent.com/7736252/236382728-a33347f6-6259-46b8-82e5-49201d9e82f1.gif)

## Details

I dig deeper into the codebase and found that the completer widget attaches a `mousedown` event to `document`:

https://github.com/jupyterlab/jupyterlab/blob/fb3832e96d2f8051763d58d05b021e31204c7c7b/packages/completer/src/widget.ts#L243

[The logic here should ideally work to hide this widget](https://github.com/jupyterlab/jupyterlab/blob/fb3832e96d2f8051763d58d05b021e31204c7c7b/packages/completer/src/widget.ts#L636) when a click is made anywhere on the screen except the widget. This works well for everything except tab bar.

Then, I looked into the TabBar widget's codebase and found that - we attach a `pointerdown` event to it with `stopPropagation` and `preventDefault`:

**See [here](https://github.com/jupyterlab/lumino/blob/7e2515606f5afe76a5005ba291266a713a5b548e/packages/widgets/src/tabbar.ts#L616) & [here](https://github.com/jupyterlab/lumino/blob/7e2515606f5afe76a5005ba291266a713a5b548e/packages/widgets/src/tabbar.ts#L755-L757)** 

This surprisingly does not let the `mousedown` event even trigger on `document`, which leads to completer widget being still visible.

**Reproduced this in a minimal JS fiddle - See https://jsfiddle.net/0kz3f5cs** 

(Open console, click on green div, then uncomment line 15 & 16 and see the difference)

## Solution

Changing the `mousedown` event to `pointerdown` in the completer widget should fix the problem. WIll be happy to raise a PR if this sounds good! Open for other solutions.

## Context

- Operating System and version: Windows 11
- Browser and version: Chrome 111.0.5563.112
- JupyterLab version: 3.6.3

## Reproduce

1. Open two notebooks.
2. Write `from ` in one notebook and hit `Tab` key.
3. Click on above Tab bar to change notebook tabs and notice that the completer is still visible.

## Expected behavior

The completer widget should hide when a click is made anywhere (except the widget itself) on the screen including the tab bars on top.

**Comment by krassowski** [comment]
This sounds good to me. If we ever want to guard some of the logic to only respond to mouse rather than any pointer (I am not sure if this is needed for completer) then we still would be able to check for `pointerType` of the events, so it should be safe to migrate.

**Comment by fcollonval** [comment]
One trouble with the proposal here is the support of notebook 7 for which the completer should not hide (single document paradigm). So a fix linked to the current active widget signal could be another approach.

**Comment by nishikantparmariam** [comment]
Thanks both for the replies here! I was able to change `mousedown` to `pointerdown` locally and tested that it fixes the issue. 

> One trouble with the proposal here is the support of notebook 7 for which the completer should not hide (single document paradigm)

As far as I tried notebook 7, I think we cannot open two notebooks in a single **browser tab** and changing browser tabs should not trigger `pointerdown` event. Let me know if I am completely missing something or misunderstood your concern. It will be helpful if you can provide some pointers in this direction.

> So a fix linked to the current active widget signal could be another approach.

Do you mean to attach a callback to hide the complete widget when the active widget changed signal is emitted?

**Comment by nishikantparmariam** [comment]
Hey @fcollonval, can you please comment on above. Thanks!!
