### ISSUE TITLE
Provide option to start notebooks in Read-only mode

### ISSUE THREAD

**Issue by sorenwacker** [jupyterlab/jupyterlab#14501]
What bothers me sometimes is that even if I open a notebook to just view it, I am asked if I want to safe it, when closing it. I appreciate  viewing mode, that allows me to view old notebooks, without the risk of changing it by accident. A simple toggle somewhere in the navigation menu would do the trick.

**Comment by krassowski** [comment]
@sorenwacker out of curiosity since I see you are closing many issues - do you believe this are fixed/no longer valid, or just clean up your own issues? Some of them may be still valuable to keep open as enhancement ideas.
