### ISSUE TITLE
Jupyterlab websocket:invalid frame header

### ISSUE THREAD

**Issue by wkinglin** [jupyterlab/jupyterlab#14524]
When I use jupyterlab in my website, it will give me an error: invalid frame header.
![1683785544659](https://github.com/jupyterlab/jupyterlab/assets/57982672/058f865d-d551-48d6-bea2-d89f3965a606)
![db891f96e8a33d88310e17b9505da94](https://github.com/jupyterlab/jupyterlab/assets/57982672/1294df26-06eb-49a0-8bdc-1d8c003f62e2)

I put the jupyterlab into the iframe and here is my vue.config.js code:

`module.exports = {
  productionSourceMap: false,
  devServer: {
    sockHost: 'http://192.168.31.189:30080/',
    proxy: {
      '/api': {
        target: 'http://192.168.31.189:30080',
        ws: true,
        changeOrigin: true
      },
      '/media': {
        target: 'http://192.168.31.189:30080',
        ws: true,
        changeOrigin: true
      },
      '/tensorboard': {
        target: 'http://192.168.31.189:30080',
        ws: true,
        changeOrigin: true
      },
      '/gitea': {
        target: 'http://192.168.31.189:30080',
        ws: true,
        changeOrigin: true
      },
      '/jupyter': {
        target: 'http://192.168.31.189:30080',
        ws: true,
        changeOrigin: true,
      }
    },
    disableHostCheck: true
  }
}
`

My nginx default.conf is ：
`location ~* /jupyter/([0-9\.]+)(.*) {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods 'GET,POST,PUT,DELETE,OPTIONS';
        add_header Access-Control-Allow-Headers *;

        set $service_ip $1;
        set $real_request_uri $2;
        proxy_pass http://$service_ip:30030/jupyter/$service_ip$real_request_uri?$args;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        
        proxy_connect_timeout 4s; 
        proxy_read_timeout 60s; 
        proxy_send_timeout 12s; 

        proxy_buffering off;
        gzip off;

    }`

how to fix it？

**Comment by JasonWeill** [comment]
Closing due to a lack of response. Please reopen (or open an issue in JupyterLite) if you've tried JupyterLite unsuccessfully.
