### ISSUE TITLE
IDocumentRegistry: Support file extensions containing periods

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#1453]
I'm working on a JSON Table Schema extension that will support both outputs with `application/table-schema+json` mime type and documents with `.table.json` file extension. However, setting the plugin's file extension to `.table.json` doesn't work (if I used `['.table.json', '.json']`, it does work for `.json`).

**Comment by ellisonbg** [comment]
Yep, we have also seen filename extensions like this with other packages (`.vega.json`)

**Comment by gnestor** [comment]
@blink1073 Thanks! I'm noticing that `.table.json` is not being matched by jupyterlab_json which is the renderer for `.json` files. I think that a `file.table.json` should be matched as both `.table.json` and `.json`. What do you think?

**Comment by blink1073** [comment]
We're going to have to match the "whole" extension first, then try the "real" extension.

**Comment by gnestor** [comment]
@blink1073 Sorry but it looks like a file with the extension `.geojson.json` causes an uncaught exception because `factories` at https://github.com/jupyterlab/jupyterlab/blob/d90cec25143d8fc6f85326e9a4bc4c1be43ac378/src/docregistry/registry.ts#L376 contains an entry whose value is `undefined`. You may not be able to reproduce unless you have jupyterlab_geojson installed, but `ipynb.json` will also reproduce it.

**Comment by blink1073** [comment]
Whoops, I see the logic error there, updating.
