### ISSUE TITLE
4.0.0 download from context menu no longer working in Safari

### ISSUE THREAD

**Issue by phish108** [jupyterlab/jupyterlab#14554]
## Description

The new context menu in the file finder has no plain download option. When clicking on the new `download as archive` there is no response and no error message. 

## Reproduce

1. Go to the file finder
2. Click on any notebook
3. right click/menu click on the selected file. 
4. select `download as archive` from the context menu. 
5. see the context menu disappear and nothing else happening. 

## Expected behavior

Some file is downloaded to the client. 

## Context

- Operating System and version: jupyter/base-notebook:2023-05-15
- Browser and version: Safari 16.4 (18615.1.26.110.1)
- JupyterLab version: 4.0.0

**Comment by krassowski** [comment]
As explained in https://github.com/jupyterlab/jupyterlab/issues/14553#issuecomment-1549684226, this is not a JupyterLab issue as JupyterLab does not have `download as archive` command. Please file an issue in https://github.com/jupyterlab-contrib/jupyter-archive or whichever extension you have installed which provides this command :)
