### ISSUE TITLE
Deleting brackets with auto-close-brackets enabled only deletes one of the brackets (jupyterlab 4.0)

### ISSUE THREAD

**Issue by BartoszBartmanski** [jupyterlab/jupyterlab#14559]
## Description

As in the title, deleting brackets with auto-close-brackets enabled in jupyterlab 4.0, only deletes one of the brackets. In previous verions deleting brackets/parenthesis/braces deleted both. 

## Reproduce

Deleting brackets/braces/parethesis in jupyterlab 4.0.

## Expected behavior

Deleting one of the brackets with auto-close-brackets enabled should delete both as in previous versions of jupyterlab.

## Context

- Operating System and version: Linux mint 21.1
- Browser and version: firefox 113
- JupyterLab version: 4.0.0

**Comment by nowinseason** [comment]
hi, I am currently struggling with this issue,

could you share the solution for this?

**Comment by johncthomas** [comment]
Is this a problem with codemirror directly? Can it be fixed in Jupyter? Or is the source obscure? This is annoying enough that I'm probably going to revert back to the previous version again, so maybe I could spend my weekend trying to figure it out if I know where to start.

**Comment by nowinseason** [comment]
> i finally just downgrade jupyter lab version and find a peace

**Comment by fcollonval** [comment]
For people willing to contribute, I guess we are missing adding the keyboard shortcut: `closeBracketsKeymap` as set up in that codemirror example:

https://github.com/codemirror/basic-setup/blob/b3be7cd30496ee578005bd11b1fa6a8b21fcbece/src/codemirror.ts#L69

**Comment by krassowski** [comment]
Note from call: we may want to double check if we need to add any other extensions from basic setup.

**Comment by williamstein** [comment]
> Deleting one of the brackets with auto-close-brackets enabled should delete both as in previous versions of jupyterlab.

This might be a little ambiguous. Put cursor where | is and hit backspace:

```
(|)  <-- this deletes both

()|  <--- this doesn't delete both?
```

**Comment by fcollonval** [comment]
For people that want to contribute a fix for this one, the fix is likely to replace the following line

https://github.com/jupyterlab/jupyterlab/blob/1692817b23ce35a31d02889c4af83df732c00a17/packages/codemirror/src/extension.ts#L718

by 

```ts
factory: () => createConditionalExtension([bracketMatching(), keymap.of(closeBracketsKeymap)]), 
```

You will need to add the following import:

```ts
import { closeBracketsKeymap } from "@codemirror/autocomplete"
```

**Comment by VivekGuruduttK28** [comment]
Hi @BartoszBartmanski 
I would love to work on this issue. Can it be assigned to me

**Comment by fcollonval** [comment]
@VivekGuruduttK28 thanks for proposing your help. FYI as soon as you add a comment on an issue you can assign yourself to it :wink:
