### ISSUE TITLE
Forbidden code points in minified JS files

### ISSUE THREAD

**Issue by frenzymadness** [jupyterlab/jupyterlab#14567]
RPM inspect tool in Fedora found some strange Unicode characters in minified JS files. The report follows:

- A forbidden code point, 0x202D, was found in the jupyterlab-4.0.0/jupyterlab/static/4986.a497cdda4b7152902568.js source file on line 2 at column 102049. This source file is used by jupyterlab.spec.
- A forbidden code point, 0x202E, was found in the jupyterlab-4.0.0/jupyterlab/static/4986.a497cdda4b7152902568.js source file on line 2 at column 102050. This source file is used by jupyterlab.spec.
- A forbidden code point, 0x2066, was found in the jupyterlab-4.0.0/jupyterlab/static/4986.a497cdda4b7152902568.js source file on line 2 at column 102051. This source file is used by jupyterlab.spec.
- A forbidden code point, 0x2067, was found in the jupyterlab-4.0.0/jupyterlab/static/4986.a497cdda4b7152902568.js source file on line 2 at column 102052. This source file is used by jupyterlab.spec.
- A forbidden code point, 0x2069, was found in the jupyterlab-4.0.0/jupyterlab/static/4986.a497cdda4b7152902568.js source file on line 2 at column 102053. This source file is used by jupyterlab.spec.

The mentioned code points represent these special characters:

- U+202D Left-To-Right Override
- U+202E Right-To-Left Override
- U+2066 Left-To-Right Isolate
- U+2067 Right-To-Left Isolate
- U+2069 Pop Directional Isolate

The strange is, that I cannot find them in the source code (tag v4.0.0) but they are present in the code I have from PyPI. This fact makes it really hard to understand why are the special characters there.

Is there any sensible reason for that? Why would minification of the JS files add those characters to the source code?

**Comment by krassowski** [comment]
This is coming from CodeMirror and is a legitimate use, see the [code here](https://github.com/codemirror/view/blob/fb2d59c5e727d5e85447d3265b12db2d8b20c539/src/special-chars.ts#L7-L55).

**Comment by frenzymadness** [comment]
Thank you very much for the quick reply and explanation. I'll fix it on our side.
