### ISSUE TITLE
Syntax highlighting for Python built-in functions does not work with JupyterLab 4.0.0

### ISSUE THREAD

**Issue by sestras** [jupyterlab/jupyterlab#14589]
## Description

Syntax highlighting for Python built-in functions does not work with JupyterLab 4.0.0. It worked in previous versions as seen here:

![image](https://github.com/jupyterlab/jupyterlab/assets/9025982/dce0b985-a461-4fcf-8c77-5d1a628ad0b0)

@krassowski noted in https://github.com/jupyterlab/jupyterlab/issues/14584#issuecomment-1561783918 that this was likely caused by the migration from CodeMirror5 to CodeMirror6 and that a custom solution is necessary since upstream is not interested in supporting built-in functions as per https://github.com/lezer-parser/python/issues/9 and https://github.com/lezer-parser/python/pull/13.

## Reproduce

Open any notebook with JupyterLab 4.0.0 and type any [Python built-in functions](https://docs.python.org/3/library/functions.html), such as print(), len(), list(), or int(), into a code block.

## Expected behavior

Python built-in functions are highlighted in some way similar to previous JupyterLab versions.

## Context

- Operating System and version: Windows 11 22H2
- Browser and version: Microsoft Edge 113.0.1774.35
- JupyterLab version: 4.0.0

**Comment by Burn1n9m4n** [comment]
I was having this issue as well on the latest version of Jupyter Lab (4.02 I believe...). I had to downgrade to 3.6 to get syntax highlights to reappear.

**Comment by krassowski** [comment]
For anyone willing to drive this forward, and alternative to forking the lazer grammar for Python is to use regex based `MatchDecorator` which was recommended by CodeMirror author [here](https://discuss.codemirror.net/t/best-way-to-highlight-specific-keywords/3771/2). Something along the lines of:

```ts
import { basicSetup, EditorView } from "codemirror"
import { MatchDecorator, Decoration, ViewPlugin, ViewUpdate } from "@codemirror/view"

const mark = Decoration.mark({class: "cm-builtin"})

const pythonBuiltinMatcher = new MatchDecorator({
  regexp: /print/g,  // TODO: add all the other builtins and word boundaries
  decoration: mark
})

class PythonHighlightsPlugin {
  constructor(view) {
    this.highlights = pythonBuiltinMatcher.createDeco(view);
  }
  update(update) {
    this.highlights = pythonBuiltinMatcher.updateDeco(update, this.highlights);
  }
}

const highlights = ViewPlugin.fromClass(PythonHighlightsPlugin, {
  decorations: instance => instance.highlights
})

new EditorView({
  doc: "a\nb\nc\n",
  extensions: [
    highlights,
    basicSetup
  ],
  parent: document.body
})
```

This would need to be added to our default Python mode, possibly as a configurable extension. And ideally be performance tested so we know how much of a penalty there is by using this approach.

**Comment by fcollonval** [comment]
A more robust solution could be to look at expanding the python lezer programmatically. After spending sometimes on the markdown lezer, there seems to be a way: https://github.com/codemirror/lang-markdown/blob/6c7daa5a53ea83dd89af5308c6d8d0d06a7c5880/src/markdown.ts#L10

But that path requires more investigation to check it actually can solve the issue.

**Comment by krassowski** [comment]
Alternatively, we could use `semanticTokens` request from LSP (which would require a running LSP server that supports it but I don't know of any open-source server which does it.

**Comment by krassowski** [comment]
There is a draft PR for semantic tokens for jedi-language-server: https://github.com/pappasam/jedi-language-server/pull/231 and an issue on pylsp: https://github.com/python-lsp/python-lsp-server/issues/33

**Comment by krassowski** [comment]
discussion on JupyterLab call
- semantic tokens approach could be slower, but provide more valuable suggestions
- extending parser could be maintainable enough

**Comment by pyloki** [comment]
> be

Yeah, downgrade is the easiest solution

**Comment by zzhengnan** [comment]
Does JupyterLab use a different mechanism for syntax highlighting than IPython (which doesn't appear to be affected by this issue)?

**Comment by AllanChain** [comment]
> Does JupyterLab use a different mechanism for syntax highlighting than IPython (which doesn't appear to be affected by this issue)?

Yes. JupyterLab uses CodeMirror for syntax highlighting, which is a in-browser code editor.

**Comment by zzhengnan** [comment]
Based on the following commit, would we get the desired behavior if we add a new `styleTags` and include the built-ins we want to highlight?
https://github.com/codemirror/lang-python/commit/4fc7033ebfc712abbdcfcdf0817c326d85419cee#diff-08b76b1156c14219681dc54823e0b39fd0e2e719ead10a5ebda8aeeb312fdf4aL58

**Comment by krassowski** [comment]
> Based on the following commit, would we get the desired behavior if we add a new styleTags and include the built-ins we want to highlight?

I don't think so. It is not about exposing the styling, it is about the parser not parsing the builtins as custom variables (so there is no nodes to apply the styles to). As mentioned in the earlier discussion https://github.com/lezer-parser/python/pull/13 demonstrates which changes would need to be made in lazer parser for Python.

**Comment by zzhengnan** [comment]
Taking a step back, what changed in CodeMirror from version 5 to 6 that caused built-ins to stop being highlighted? Were built-ins correctly identified (and highlighted) as custom variables in the lazer parser in version 5, and somehow that special treatment was revoked in version 6?

**Comment by krassowski** [comment]
> what changed in CodeMirror from version 5 to 6 that caused built-ins to stop being highlighted?

V6 was a complete rewrite, the highlighting for builtins has never been implemented by the CodeMirror author in this version of the codebase. I appreciate your analytical approach but I don't feel there is much more to explore. There are 3 solutions on our side we could purse which are listed above and if is now down to someone (contributions welcome!) finding free time to implement one or more of them (or someone sponsoring such work).

**Comment by pya** [comment]
Any news? The missing highlighting of built-ins really limits the use for teaching. The green color is important to explain the concept of built-ins. Some interesting, new extensions work only with JupyterLab version 4.x. So I am in a dilemma here. :(

**Comment by AllanChain** [comment]
I got it working with a syntax-aware `ViewPlugin`, based on https://github.com/codemirror/language/blob/3c9ad8ffee32e158512d252fee9457a0e6469e2e/src/highlight.ts#L155

Since it's just a modified syntax highlighter, I believe the performance impact is small.

I'll enhance the implementation in the next couple of weeks if I have time. But in case I don't, I'm posting the patch below as a starting point for anyone who wants to try:

```diff
diff --git a/packages/codemirror/src/theme.ts b/packages/codemirror/src/theme.ts
index eec13b0..b052ee9 100644
--- a/packages/codemirror/src/theme.ts
+++ b/packages/codemirror/src/theme.ts
@@ -4,13 +4,15 @@
 import {
   defaultHighlightStyle,
   HighlightStyle,
-  syntaxHighlighting
+  syntaxHighlighting,
+  syntaxTree
 } from '@codemirror/language';
-import { Extension } from '@codemirror/state';
-import { EditorView } from '@codemirror/view';
+import { Extension, RangeSetBuilder } from '@codemirror/state';
+import { Decoration, DecorationSet, EditorView, ViewPlugin, ViewUpdate } from '@codemirror/view';
 import { ITranslator, nullTranslator } from '@jupyterlab/translation';
 import { tags as t } from '@lezer/highlight';
 import { IEditorTheme, IEditorThemeRegistry } from './token';
+import { Tree } from '@lezer/common';
 
 export const jupyterEditorTheme = EditorView.theme({
   /**
@@ -151,12 +153,63 @@ export const jupyterHighlightStyle = HighlightStyle.define([
   }
 ]);
 
+class TreeHighlighter {
+  decorations: DecorationSet
+  decoratedTo: number
+  tree: Tree
+  markCache: { [cls: string]: Decoration } = Object.create(null)
+
+  constructor(view: EditorView) {
+    this.tree = syntaxTree(view.state)
+    this.decorations = this.buildDeco(view)
+    this.decoratedTo = view.viewport.to
+  }
+
+  update(update: ViewUpdate) {
+    let tree = syntaxTree(update.state)
+    let { viewport } = update.view, decoratedToMapped = update.changes.mapPos(this.decoratedTo, 1)
+    if (tree.length < viewport.to && tree.type == this.tree.type && decoratedToMapped >= viewport.to) {
+      this.decorations = this.decorations.map(update.changes)
+      this.decoratedTo = decoratedToMapped
+    } else if (tree != this.tree || update.viewportChanged) {
+      this.tree = tree
+      this.decorations = this.buildDeco(update.view)
+      this.decoratedTo = viewport.to
+    }
+  }
+
+  buildDeco(view: EditorView) {
+    if (!this.tree.length) return Decoration.none
+
+    let builder = new RangeSetBuilder<Decoration>()
+    for (let { from, to } of view.visibleRanges) {
+      this.tree.iterate({
+        enter(node) {
+          if (node.name !== "VariableName") return
+          const variableName = view.state.sliceDoc(node.from, node.to)
+          console.log(variableName)
+          console.log(node.node)
+          if (variableName === "str") { // TODO: include all builtin
+            builder.add(node.from, node.to, Decoration.mark({ class: "cm-builtin" }))
+          }
+        },
+        from, to
+      })
+    }
+    return builder.finish()
+  }
+}
+
+const treeHighlighter = ViewPlugin.fromClass(TreeHighlighter, {
+  decorations: v => v.decorations
+})
 /**
  * JupyterLab CodeMirror 6 theme
  */
 export const jupyterTheme: Extension = [
   jupyterEditorTheme,
-  syntaxHighlighting(jupyterHighlightStyle)
+  syntaxHighlighting(jupyterHighlightStyle),
+  treeHighlighter
 ];
 
 /**
```

**Comment by Jeromekem** [comment]
@AllanChain GIven that I'm running JupyterLab 4.0.x in a docker container. How could I approach solving the issue?

**Comment by AllanChain** [comment]
@Jeromekem The first release containing the fix seems to be https://github.com/jupyterlab/jupyterlab/releases/tag/v4.2.0a0. Maybe you should wait until patch releases on `4.0.x` got released.

**Comment by pya** [comment]
Looks like 4.1.3 fixes this problem.

**Comment by Jeromekem** [comment]
Thank you all. Glad to see it is resolved. Succesfully installed 4.1.3.

**Comment by efigb** [comment]
for the begginers (dummies), can anyone explain how to upgrade it if I have previous version 4.0.11 of jupyter lab and I installed it as a conda env in base terminal? is there any upgrade command to do it (i.e. conda update jupyterlab version...)? thanks!!

**Comment by zzhengnan** [comment]
@efigb You can upgrade JupyterLab with this command `conda upgrade jupyterlab`.

**Comment by efigb** [comment]
> @efigb You can upgrade JupyterLab with this command `conda upgrade jupyterlab`.

thanks zzhengnan but then it upgrades to 4.0.11 version, not 4.1.3, which is the current version I had. And when opening jupyterlab the problem of syntax highlighting persists... could you provide further solutions? thanks!

**Comment by krassowski** [comment]
@efigb it looks like you are using ([non-free](https://www.anaconda.com/blog/is-conda-free)) Anaconda `default` channel: https://anaconda.org/anaconda/jupyterlab.
This is something we do not officially support because we do not have control over publishing to the `default` channel and sometimes even critical releases took a bit of convincing to land there. The official JupyterLab publication channels are:
- PyPI: https://pypi.org/project/jupyterlab/ and
- `conda-forge` channel: https://anaconda.org/conda-forge/jupyterlab

The supported ways of installing jupyterlab are documented in the documentation: https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html and for JupyterLab Desktop in: https://github.com/jupyterlab/jupyterlab-desktop#installation

**Comment by krassowski** [comment]
I should have mentioned, try `conda upgrade -c conda-forge jupyterlab`

**Comment by efigb** [comment]
> I should have mentioned, try `conda upgrade -c conda-forge jupyterlab`

thanks a lot for the feedback! I finally could upgrade it to the new version and syntax highlighting works superfine! :)
