### ISSUE TITLE
Spaces are not rendered correctly in the HTML page title of notebooks

### ISSUE THREAD

**Issue by dimdal** [jupyterlab/jupyterlab#14587]
## Description

The page title does not render spaces correctly in Jupyter Lab if the filename has spaces in it.

## Reproduce

1. Run Jupyter Lab
2. Create a notebook with spaces in the filename (e.g. "My new notebook.ipynb")
3. Look at how the page title is rendered in the tab / window top. Spaces are rendered with URL encoding (%20).
4. Close Jupyter Lab, run Jupyter Notebook.
5. Open the same file you created in step 2.
6. Look at how the page title is rendered in the tab / window top. Spaces are rendered correctly. 

## Expected behavior

The notebook title should render spaces correctly in the HTML title of the document, like in Jupyter Notebook.

Jupyter Lab:
![image](https://github.com/jupyterlab/jupyterlab/assets/13454398/2b2a2495-738b-456c-957d-af69f0ac96d6)

Jupyter Notebook:
![image](https://github.com/jupyterlab/jupyterlab/assets/13454398/e9fdeb59-dd38-4514-bdca-d6397dbc93c1)

## Context

- Operating System and version: maCOS 13.3 (22E252)
- Browser and version: 1.51.114 Chromium: 113.0.5672.92 (Official Build) (arm64) and Chrome Version 113.0.5672.126 (Official Build) (arm64)
- JupyterLab version: 3.4.4

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
> JupyterLab version: 3.4.4

This was fixed by https://github.com/jupyterlab/jupyterlab/pull/14178 and backported to 3.6.x in https://github.com/jupyterlab/jupyterlab/pull/14338. Please upgrade JupyterLab to receive bug fixes.
