### ISSUE TITLE
The backslash symbol is replaced by the Korean won(₩‎) symbol.

### ISSUE THREAD

**Issue by youngwoos** [jupyterlab/jupyterlab#14592]
In JupyterLab 3.6, the backslash symbol appears correctly.
![image](https://github.com/jupyterlab/jupyterlab/assets/29052303/aac3306c-90c6-4346-891d-acab88822366)

In JupyterLab 4.0, the backslash symbol is replaced with the Korean won(₩‎) symbol.
![image](https://github.com/jupyterlab/jupyterlab/assets/29052303/55280243-53a6-4c15-a8a1-e0d398b96507)

Is there a way to make the backslash symbol appear as it should?

I use Korean Windows. I tested it on Python 3.9, 3.11 and it was the same. It doesn't seem to be a python version issue.

**Comment by krassowski** [comment]
I cannot reproduce this on Ubuntu, but I see where it is likely be coming from (i.e. from a different default monospace font with ligatures).

![Screenshot from 2023-05-27 10-30-39](https://github.com/jupyterlab/jupyterlab/assets/5832902/116d3971-07d2-4767-a4d5-42013bd37738)

On 3.x the font-family is set to `var(--jp-code-font-family)` for `.CodeMirror` (and then inherited by `.CodeMirror pre.CodeMirror-line` rule) but on JupyterLab 4.0 it is `monospace` from `.cm-scroller` which overrides our variable set on `.cm-editor`:

| 3.x | 4.0 |
|--|--|
| ![Screenshot from 2023-05-27 10-40-25](https://github.com/jupyterlab/jupyterlab/assets/5832902/58afe7d2-d3d4-483b-929b-0a12539161ea) | ![Screenshot from 2023-05-27 10-39-21](https://github.com/jupyterlab/jupyterlab/assets/5832902/9f4abba4-d71a-47dd-9b77-df59ec90eacc) |

This results in different resolution of fonts:

| 3.x | 4.0 |
|--|--|
| ![Screenshot from 2023-05-27 10-41-35](https://github.com/jupyterlab/jupyterlab/assets/5832902/6546ddb7-f837-426a-a776-cfe2ed6f6cb2) | ![Screenshot from 2023-05-27 10-33-57](https://github.com/jupyterlab/jupyterlab/assets/5832902/5f5c7ff8-4996-4717-91e5-94a558e251db) |

**Comment by youngwoos** [comment]
Thanks for the hint, but is there a way to change the font of a notebook cell?
In the Settings Editor, I can only change the font of the Markdown Viewer and Terminal, but there doesn't seem to be a way to change the font of a Jupyter notebook cell.

<img width="804" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/29052303/282413b0-920b-49f9-a394-07cf2f1bde65">

**Comment by pwsandoval** [comment]
> I cannot reproduce this on Ubuntu, but I see where it is likely be coming from (i.e. from a different default monospace font with ligatures).
> 
> ![Screenshot from 2023-05-27 10-30-39](https://private-user-images.githubusercontent.com/5832902/241376442-116d3971-07d2-4767-a4d5-42013bd37738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDM2NjksIm5iZiI6MTcwNDQwMzM2OSwicGF0aCI6Ii81ODMyOTAyLzI0MTM3NjQ0Mi0xMTZkMzk3MS0wN2QyLTQ3NjctYTRkNS00MjAxM2JkMzc3MzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMjEyMjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2U0ZDk4ZjVkMDk4NzlhY2MyMjNhMDVhZmQwMWY4N2ZlOWQzODg5ZjIyMGFlZGI2NmVkNTIwNzUwNmRkMmM4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jEUO4Lc1muZ2q645iyawfJveizMPyx3q5F7Gjh-SYoE)
> 
> On 3.x the font-family is set to `var(--jp-code-font-family)` for `.CodeMirror` (and then inherited by `.CodeMirror pre.CodeMirror-line` rule) but on JupyterLab 4.0 it is `monospace` from `.cm-scroller` which overrides our variable set on `.cm-editor`:
> 
> 3.x	4.0
> ![Screenshot from 2023-05-27 10-40-25](https://private-user-images.githubusercontent.com/5832902/241376871-58afe7d2-d3d4-483b-929b-0a12539161ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDM2NjksIm5iZiI6MTcwNDQwMzM2OSwicGF0aCI6Ii81ODMyOTAyLzI0MTM3Njg3MS01OGFmZTdkMi1kM2Q0LTQ4M2ItOTI5Yi0wYTEyNTM5MTYxZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMjEyMjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGM4MzdhN2RmNDMxYmEwZThiMDU2MTA1MzE0NWY5MTY4ZjFkNjAxZjA1ZDRjZDA2MGU0OWQ1NzdiM2ZlZTgxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._26EhKJvgs6ztjAq2ACNPwHbLlENycAwQ_cYLxRvO_o)	![Screenshot from 2023-05-27 10-39-21](https://private-user-images.githubusercontent.com/5832902/241376845-9f4abba4-d71a-47dd-9b77-df59ec90eacc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDM2NjksIm5iZiI6MTcwNDQwMzM2OSwicGF0aCI6Ii81ODMyOTAyLzI0MTM3Njg0NS05ZjRhYmJhNC1kNzFhLTQ3ZGQtOWI3Ny1kZjU5ZWM5MGVhY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMjEyMjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ5NGE0ODljOTYwYjMxNTBmOWNmZWQ5NjA2MGM1YzE1Nzg3MjU1NWQ1MTFmOTFhMzllZWE4ZjdmNzMxNjUzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oOTmX63U-069Z7kL1zYF1wrgyH_r_NWRV0x2v3f0HTg)
> This results in different resolution of fonts:
> 
> 3.x	4.0
> ![Screenshot from 2023-05-27 10-41-35](https://private-user-images.githubusercontent.com/5832902/241376944-6546ddb7-f837-426a-a776-cfe2ed6f6cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDM2NjksIm5iZiI6MTcwNDQwMzM2OSwicGF0aCI6Ii81ODMyOTAyLzI0MTM3Njk0NC02NTQ2ZGRiNy1mODM3LTQyNmEtYTc3Ni1jZmUyZWQ2ZjZjYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMjEyMjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODdkNTA5N2NkMmEzNzFjMTdhZDJmNjBmYjNmNzRjNjg2NDBlYjhjOTMxZjBjZTZlMjdjZmIzOWJlN2FjODlhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yCUA2NoirV-cInULM3rLDvKDHyqCudG_fK5XYauMXZU)	![Screenshot from 2023-05-27 10-33-57](https://private-user-images.githubusercontent.com/5832902/241376614-5f5c7ff8-4996-4717-91e5-94a558e251db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MDM2NjksIm5iZiI6MTcwNDQwMzM2OSwicGF0aCI6Ii81ODMyOTAyLzI0MTM3NjYxNC01ZjVjN2ZmOC00OTk2LTQ3MTctOTFlNS05NGE1NThlMjUxZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMjEyMjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWIxYWU2MzExYWVkN2M0MjljMzQ5ZjdkNjMxZDBlYWY5MDEzYjI4N2FjNjFiNTgzMzhiZDg2N2Q2ZjhmNDQyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eG0YFE9rAK7J_voCLHkRWaOPVOGk_ifw4XU7CBI4Jc8)

And how to assign a different font to ```a .ͼ1 .cm-scroller```?
