### ISSUE TITLE
Table of Contents: selecting heading only scrolls to position the first time

### ISSUE THREAD

**Issue by minerharry** [jupyterlab/jupyterlab#14591]
## Description

When you select a heading in the table of contents, it automatically starts editing the cell. This is not preferred behavior for me, but I can live with it. More problematic, however, is that once the cell is in edit mode, clicking the header again in the ToC will not scroll to the cell. This happens even if you have currently selected/are editing another code or markdown cell, and can be true for multiple headers at the same time. Effectively, you could have an entire table of contents and none of the headers work!

## Reproduce

In the example notebook below: scroll up so that the heading h1 is offscreen. Click h1 in the table of contents, you get scrolled down to it and the cell enters edit mode. Scroll up and optionally select one of the filler cells; clicking the heading again in the table of contents does nothing. Only fixed when the markdown cell is run again.

## Expected behavior

When you click a heading cell in the table of contents, you should always be scrolled to it. In my opinion, it also shouldn't automatically start editing markdown cells, but that's of a secondary concern.

## Context

example notebook contents:
```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1733768e-510c-4fef-b5b9-b086fd969d44",
   "metadata": {},
   "outputs": [],
   "source": [
    "filler = 4"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9d81f6ec-cbd8-49e7-908f-f315b26de2d3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "262057a5-f605-4e23-bf26-f0035189fd8c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2f2d07fc-3bb6-4464-8dda-453d74d5766c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "f37c6c3a-204c-4b92-87d2-db1b28810597",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "cfe35aec-32c0-4d84-82c9-5324a66eab13",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f81f92a1-da97-430a-b785-d85024a600d5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "5c0f0966-852c-4c36-ab8e-fe37262c6826",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "b79cc1dd-a477-4049-8167-3ecd257377b7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "4eb14bda-aa6a-4e9a-83a7-c4829abba2fb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "f996f5ec-5786-4225-bfc7-69f0a2f18c87",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "f07f2ffe-d486-47c0-a63c-5ec454ed9054",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "ab6f22c7-573b-4dd8-a15e-c188433e09f5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "2dc45e1b-c960-47cc-9c14-fe4b950e0810",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "filler"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cc9db4bb-e736-410e-835b-bef8a971b4b5",
   "metadata": {},
   "source": [
    "## h1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "da7b7248-b994-410c-9b3a-ff3c7591a3be",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
@minerharry Which version of JupyterLab are you using? The TOC extension was completely redone in JupyterLab 4. If you've tried both versions 3 and 4, does the problem occur in one or both of these versions? Thanks!

**Comment by andrii-i** [comment]
This problem is reproducible in 4.0.
![Table_of_contents](https://github.com/jupyterlab/jupyterlab/assets/26686070/30cea6dd-44e2-4246-95f2-751624eeb54c)

@minerharry Thank you for reporting this problem. If you feel like "When you select a heading in the table of contents, it automatically starts editing the cell. This is not preferred behavior for me."  is an issue, it might make sense to create a separate issue / enhancement request for visibility and to consolidate discussion.

**Comment by andrii-i** [comment]
Can't reproduce on 3.6.x

**Comment by minerharry** [comment]
Upon further investigation the behavior of starting editing seems like a bug. It doesn't happen at all in 3.6.2, and if the currently selected cell (of any type) is under the heading cell, it neither starts editing nor scrolls when you select the cell in the TOC (possibly because the TOC sees it as already "selected"; the header is highlighted in blue). In 3.6, even when the header or any of its cells are selected (the header in the TOC is still highlighted in blue, which I like), clicking the name always scrolls the cell into view and never starts editing, which is much more consistent behavior.

**Comment by lukelbd** [comment]
I also encountered this bug. Just confirming it is still present in the recent `4.0.2` release.

**Comment by dakoop** [comment]
Also ran into this and can confirm it still exists in 4.0.5. Also, while in edit mode, any cell you select in the TOC also will switch to edit mode which, in my opinion, is not desired. This issue also seems to affect links from other notebooks, e.g., `[link](other-notebook.ipynb#Heading)` won't always scroll to that heading. When investigating the issue (and outside of edit mode), I found a situation where three headings reacted and the fourth does not, but I have been unable to figure out how to reproduce this.

**Comment by dixr** [comment]
I can confirm that both these issues are still present for me in 4.0.6.

A solution would be very much appreciated.

**Comment by LunarLanding** [comment]
I am on  4.0.6.
The current behavior of [ click on TOC -> scroll then start edit] is a change from previous behavior that completely breaks the navigation functionality for me.
I have many code cells inbetween heading cells. So my main intention when clicking a heading is to scroll to the start of such a section. 
It's worse when I don't notice that the cell I scrolled to was edited (again, because the behavior was changed), and keep going through my normal usage only for then having to find the cell that was left in edit mode and put it back into display mode so that proper navigation is restored.

**Comment by krassowski** [comment]
Reopening as #15184 did not solve the issue for scrolling to the same heading again.

To reproduce:
1. Click on a heading in the ToC
2. Scroll down
3. Click on the same heading again

**Comment by parmentelat** [comment]
for the record, this also has been mentioned in 
https://github.com/jupyterlab/jupyterlab/pull/15184#issuecomment-1750240132 
with a plausible explanation as to why #15184 does not solve the issue

namely that this scenario does not change the active toc heading, and so `onActiveHeadingChanged` does not trigger at all

**Comment by nonquit** [comment]
I've been having the same issue since updating earlier this month from 3.5.3 to 4.0.6.

**Comment by jpcaram** [comment]
Still present on 4.0.7.

**Comment by m-beau** [comment]
The issue is that it makes the markdown cell active when clicking the first time; the second time, it becomes non-reactive because the markdown cell then remains active. The solution is to execute the markdown cell to make it inactive again, and responsive to  TOC clicks.

But that is a very annoying behaviour: the fix would be to make markdown cells remain inactive when being navigated to from the TOC.

**Comment by 0xnurl** [comment]
So happy to find this thread, I thought I was going crazy. I can confirm that this still happens on 4.0.9. Downgrading to `jupyterlab==3.6.6` solved it for me.

**Comment by 0xnurl** [comment]
I can confirm that this still happens on 4.0.9. Downgrading to jupyterlab==3.6.6 solved it for me.

**Comment by krassowski** [comment]
If you still experience issues with scrolling when selecting headings in the TOC it might be due to https://github.com/jupyterlab/jupyterlab/issues/15613; switching to full windowing mode may help.
