### ISSUE TITLE
Option to selectively hide code in cell

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1459]
Is there an option to hide the code in a code cell, but not the output? 

Would be a useful feature. I'm thinking of making a cell with ipywidget to modify some variables using widgets and don't want a reader to see the code for it

**Comment by blink1073** [comment]
Hi @AbdealiJK, this is a planned feature for version 1.0 and is being discussed in https://github.com/jupyterlab/jupyterlab/issues/713.  Cheers!

**Comment by AbdealiJK** [comment]
Awesome, sorry about the noise
