### ISSUE TITLE
Benchmark UI test fails since switching to `defer` mode

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14608]
Follow up to #14550 - I see this test to fail frequently:

`test/benchmark/notebook.spec.ts:94:9 › Benchmark › measure large_code_notebook.ipynb`

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/56ff6fbe-d1de-4672-8398-6a365fcc6e79)

Here the notebook is clearly not fully rendered yet:

| Expected | Actual |
|--|--|
| ![large-code-notebook-ipynb-expected](https://github.com/jupyterlab/jupyterlab/assets/5832902/08f12423-c476-4ac6-9fe6-3ba8dbac68fb) | ![large-code-notebook-ipynb-actual](https://github.com/jupyterlab/jupyterlab/assets/5832902/e827ec7d-c4de-43fc-a455-b4fcaceadfd0) |

It seem to stem from the spinner being hidden before the deferred cells are shown. This is expected, but then I am not sure how we want to update the test to account for that. The relevant lines are:

https://github.com/jupyterlab/jupyterlab/blob/3fd8c726a22c636a447133345b1c1c27fc8a5674/galata/test/benchmark/notebook.spec.ts#L111-L131

**Comment by krassowski** [comment]
I guess we may want to have logic checking if cells are not placeholders exposed for testing:

https://github.com/jupyterlab/jupyterlab/blob/bfc79b7a690e52c29d46c1d3bacd79eaeb5c9ead/packages/notebook/src/searchprovider.ts#L499-L505

but then what we end up measuring will depend on the windowing mode (in full windowing mode we may get stuck).

Ideally we would have a way to check that the cells which would fit on screen are rendered (regardless of windowing mode).

**Comment by krassowski** [comment]
Or maybe `defer` should never defer cells which are in viewport?

**Comment by fcollonval** [comment]
> Or maybe `defer` should never defer cells which are in viewport?

From user experience point of view this seems like the best solution. But it is gonna be tricky as we don't know how many cells need to be rendered to fill the viewport.
