### ISSUE TITLE
cross-domain websockets requests (terminal/kernel) get 403 on chrome

### ISSUE THREAD

**Issue by itaynvn** [jupyterlab/jupyterlab#14606]
## Description

i am running jupyterlab on domain `foo.com`, and embedding it within an iframe in domain `bar.com`.
i am browsing `bar.com` using google chrome.

whenever i open a new terminal, or connect to python kernel, it hangs forever. 

for example these are the web console logs on google chrome when i open a new terminal:
![image](https://github.com/jupyterlab/jupyterlab/assets/61652839/c92fa6e2-2bea-47b4-8290-27410b4b7b22)

and in the jupyter logs:
```
[W 2023-05-28 13:53:43.443 TerminalsExtensionApp] 403 GET /terminals/websocket/1 (@127.0.0.1) 6.39ms referer=None
```

at this point its important to stress 2 things:

1. i have these in my configuration file:
```
c.NotebookApp.allow_origin = 'bar.com'
c.NotebookApp.tornado_settings = { 'headers': { 'Content-Security-Policy': "frame-ancestors 'self' bar.com ", 'Access-Control-Allow-Origin': 'bar.com' , 'Referer': 'bar.com' }, 'debug': True  }
```
2. **this issue didn't reproduce** when both the iframe and the embedding site are on the same domain (i.e both are on `bar.com`).

moving on: i then checked the same on firefox & opera, and voila, the **issue didn't reproduce!**

after some research, it appeared that google chrome doesn't send the `Referer` header on cross-domain websocket requests.
for now this seems like the most reasonable "culprit", as the websocket request is indeed made from the client (browser), and the browser is in full control of the headers sent. plus its generally known that chrome is a tad more "restrictive" and security-leaning browser. https://www.rfc-editor.org/rfc/rfc2616#section-15.1.3

plus, here is a comparision of the terminal websocket request between chrome and firefox:
```
[D 2023-05-28 13:53:43.132 TerminalsExtensionApp] 200 GET /api/terminals?1685282022893 (57b312a1272b4f899303b05596fff308@127.0.0.1) 0.78ms
[W 2023-05-28 13:53:43.443 TerminalsExtensionApp] 403 GET /terminals/websocket/1 (@127.0.0.1) 6.39ms referer=None
```
and firefox:
```
[D 2023-05-28 14:46:49.594 TerminalsExtensionApp] 200 POST /api/terminals?1685285208998 (6054bee466804a5993ff9520dde75b57@127.0.0.1) 311.34ms
[D 2023-05-28 14:46:50.107 TerminalsExtensionApp] 101 GET /terminals/websocket/1 (6054bee466804a5993ff9520dde75b57@127.0.0.1) 0.73ms
[D 2023-05-28 14:46:50.107 TerminalsExtensionApp] Opening websocket /terminals/websocket/1
```

notice the missing token prefix in chrome `(@127.0.0.1)`, compared to firefox `(6054bee466804a5993ff9520dde75b57@127.0.0.1)`

so to sum it up: this only happens when the embedding domain and the jupyterlab domain are different, and the embedding domain is browsed with google chrome. 

## Reproduce

1. run jupyterlab and expose its UI on domain `foo.com`
2. embed the jupyter UI in an iframe on domain `bar.com`
3. open `bar.com` in google chrome, and click on "new terminal"
4. connection will hang forever, and terminal command line won't appear

## Expected behavior

i would like to be able to use terminal and python kernel cross-domain

## Context

- Operating System and version: **MacBook Pro, OS Ventura 13.3.1 (a)**
- Browser and version: **Chrome 113.0.5672.126 (Official Build) (x86_64)**
- Browser and version: **Firefox 113.0.2 (64-bit)**
- Browser and version: **Opera 68.0.3618.125**
- JupyterLab version: 4.0.0
- Jupyter is served from linux server on Azure

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/usr/local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/usr/local/bin
	/usr/local/lib/python310.zip
	/usr/local/lib/python3.10
	/usr/local/lib/python3.10/lib-dynload
	/usr/local/lib/python3.10/site-packages

sys.executable:
	/usr/local/bin/python

sys.version:
	3.10.11 (main, May  4 2023, 06:08:16) [GCC 10.2.1 20210110]

platform.platform():
	Linux-5.4.0-1107-azure-x86_64-with-glibc2.31

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter

pip list:
	Package                    Version
	-------------------------- ---------
	absl-py                    1.4.0
	aniso8601                  9.0.1
	anyio                      3.6.2
	argon2-cffi                21.3.0
	argon2-cffi-bindings       21.2.0
	arrow                      1.2.3
	asn1crypto                 1.5.1
	asttokens                  2.2.1
	async-lru                  2.0.2
	attrs                      22.1.0
	azure-core                 1.10.0
	azure-storage-blob         12.6.0
	Babel                      2.12.1
	backcall                   0.2.0
	beautifulsoup4             4.12.2
	bleach                     6.0.0
	blinker                    1.6.2
	boto3                      1.19.12
	botocore                   1.22.12
	cachetools                 4.2.4
	certifi                    2022.6.15
	cffi                       1.15.1
	chardet                    3.0.4
	charset-normalizer         2.1.1
	click                      8.1.3
	cnvrg                      0.7.54
	cnvrgv2                    1.0.40
	colorama                   0.4.6
	comm                       0.1.3
	croniter                   1.3.15
	cryptography               40.0.2
	debugpy                    1.6.7
	decorator                  5.1.1
	defusedxml                 0.7.1
	dill                       0.3.6
	executing                  1.2.0
	fastjsonschema             2.16.3
	filelock                   3.12.0
	Flask                      2.3.2
	Flask-RESTful              0.3.9
	Flask-SQLAlchemy           3.0.3
	fqdn                       1.5.1
	gitdb                      4.0.10
	GitPython                  3.1.31
	google-api-core            2.11.0
	google-auth                2.19.0
	google-auth-oauthlib       1.0.0
	google-cloud-core          2.3.2
	google-cloud-storage       2.9.0
	google-crc32c              1.5.0
	google-resumable-media     2.5.0
	googleapis-common-protos   1.59.0
	greenlet                   2.0.2
	grpcio                     1.54.2
	gunicorn                   20.1.0
	idna                       2.10
	importlib-metadata         4.8.3
	iniconfig                  1.1.1
	ipykernel                  6.23.1
	ipython                    8.13.2
	isodate                    0.6.1
	isoduration                20.11.0
	itsdangerous               2.1.2
	jedi                       0.18.2
	Jinja2                     3.1.2
	jmespath                   0.10.0
	json5                      0.9.14
	jsonpointer                2.3
	jsonschema                 4.17.3
	jupyter_client             8.2.0
	jupyter_core               5.3.0
	jupyter-events             0.6.3
	jupyter-lsp                2.1.0
	jupyter_server             2.5.0
	jupyter-server-mathjax     0.2.6
	jupyter_server_terminals   0.4.4
	jupyterlab                 4.0.0
	jupyterlab-git             0.37.1
	jupyterlab-pygments        0.2.2
	jupyterlab_server          2.22.1
	Markdown                   3.4.3
	MarkupSafe                 2.1.2
	matplotlib-inline          0.1.6
	mistune                    2.0.5
	msrest                     0.6.21
	nbclient                   0.7.4
	nbconvert                  7.4.0
	nbdime                     3.2.1
	nbformat                   5.8.0
	nest-asyncio               1.5.6
	notebook_shim              0.2.3
	numpy                      1.24.3
	oauthlib                   3.2.0
	oscrypto                   1.3.0
	packaging                  21.3
	pandas                     2.0.1
	pandocfilters              1.5.0
	parso                      0.8.3
	pathspec                   0.9.0
	pexpect                    4.8.0
	pickleshare                0.7.5
	pip                        23.1.2
	platformdirs               3.5.1
	pluggy                     1.0.0
	prettytable                2.5.0
	progress                   1.5
	prometheus-client          0.16.0
	prompt-toolkit             3.0.38
	protobuf                   4.23.2
	psutil                     5.9.5
	ptyprocess                 0.7.0
	pure-eval                  0.2.2
	py                         1.11.0
	pyaml                      21.10.1
	pyarrow                    12.0.0
	pyasn1                     0.4.8
	pyasn1-modules             0.2.8
	pycparser                  2.21
	pycryptodome               3.14.1
	pycryptodomex              3.17
	Pygments                   2.15.1
	PyJWT                      2.7.0
	pyOpenSSL                  23.1.1
	pyparsing                  3.0.9
	pyrsistent                 0.19.3
	pytest                     7.0.1
	pytest-mock                3.6.1
	python-dateutil            2.8.2
	python-json-logger         2.0.7
	pytz                       2022.2.1
	PyYAML                     6.0
	pyzmq                      25.0.2
	requests                   2.31.0
	requests-oauthlib          1.3.0
	rfc3339-validator          0.1.4
	rfc3986-validator          0.1.1
	rsa                        4.9
	s3transfer                 0.5.2
	Send2Trash                 1.8.2
	setuptools                 65.5.1
	six                        1.16.0
	smmap                      5.0.0
	sniffio                    1.3.0
	snowflake-connector-python 3.0.3
	soupsieve                  2.4.1
	SQLAlchemy                 2.0.13
	stack-data                 0.6.2
	tensorboard                2.13.0
	tensorboard-data-server    0.7.0
	terminado                  0.17.1
	tinycss2                   1.2.1
	tinynetrc                  1.3.1
	tomli                      1.2.3
	tornado                    6.3.2
	tqdm                       4.65.0
	traitlets                  5.9.0
	typing_extensions          4.5.0
	tzdata                     2023.3
	uri-template               1.2.0
	urllib3                    1.25.11
	wcwidth                    0.2.5
	webcolors                  1.13
	webencodings               0.5.1
	websocket-client           1.5.1
	Werkzeug                   2.3.4
	wheel                      0.40.0
	zipp                       3.6.0</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 2023-05-28 13:53:43.132 TerminalsExtensionApp] 200 GET /api/terminals?1685282022893 (57b312a1272b4f899303b05596fff308@127.0.0.1) 0.78ms
[D 2023-05-28 13:53:43.323 ServerApp] Path 2320.04abae549b19363c2fdd.js served from /usr/local/share/jupyter/lab/static/2320.04abae549b19363c2fdd.js
[D 2023-05-28 13:53:43.324 ServerApp] 200 GET /static/lab/2320.04abae549b19363c2fdd.js?v=04abae549b19363c2fdd (@127.0.0.1) 1.17ms
[D 2023-05-28 13:53:43.325 ServerApp] Path 2617.9c299e26785f7646cb39.js served from /usr/local/share/jupyter/lab/static/2617.9c299e26785f7646cb39.js
[D 2023-05-28 13:53:43.326 ServerApp] 200 GET /static/lab/2617.9c299e26785f7646cb39.js?v=9c299e26785f7646cb39 (@127.0.0.1) 1.17ms
[D 2023-05-28 13:53:43.326 ServerApp] Path 7511.b381a696cf806983c654.js served from /usr/local/share/jupyter/lab/static/7511.b381a696cf806983c654.js
[D 2023-05-28 13:53:43.327 ServerApp] 200 GET /static/lab/7511.b381a696cf806983c654.js?v=b381a696cf806983c654 (@127.0.0.1) 1.56ms
[D 2023-05-28 13:53:43.327 ServerApp] Path 292.3f7844a129f16ec1ffbc.js served from /usr/local/share/jupyter/lab/static/292.3f7844a129f16ec1ffbc.js
[D 2023-05-28 13:53:43.327 ServerApp] 200 GET /static/lab/292.3f7844a129f16ec1ffbc.js?v=3f7844a129f16ec1ffbc (@127.0.0.1) 1.96ms
[D 2023-05-28 13:53:43.437 TerminalsExtensionApp] Using contents: services/contents
[D 2023-05-28 13:53:43.437 TerminalsExtensionApp] Using contents: services/contents
[E 2023-05-28 13:53:43.441 ServerApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1294, in send_error
        self.write_error(status_code, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 707, in write_error
        html = self.render_template("error.html", **ns)
      File "/usr/local/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 633, in render_template
        return template.render(**ns)
      File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
        self.environment.handle_exception()
      File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/usr/local/lib/python3.10/site-packages/jupyter_server/templates/error.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/usr/local/lib/python3.10/site-packages/jupyter_server/templates/page.html", line 9, in top-level template code
        {% block favicon %}<link id="favicon" rel="shortcut icon" type="image/x-icon" href="{{ static_url("favicon.ico") }}">
      File "/usr/local/lib/python3.10/site-packages/jupyter_server/templates/page.html", line 9, in block 'favicon'
        {% block favicon %}<link id="favicon" rel="shortcut icon" type="image/x-icon" href="{{ static_url("favicon.ico") }}">
      File "/usr/local/lib/python3.10/site-packages/jupyter_server/extension/handler.py", line 107, in static_url
        raise Exception(msg) from None
    Exception: This extension doesn't have any static paths listed. Check that the extension's `static_paths` trait is set.
[W 2023-05-28 13:53:43.443 TerminalsExtensionApp] 403 GET /terminals/websocket/1 (@127.0.0.1) 6.39ms referer=None
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.
i've included the relevant web console error in the 1st screenshot
</pre>
</details>

**Comment by krassowski** [comment]
1) `NotebookApp` → `ServerApp`?
2) This may be better answered in `jupyter-server` repository on [Jupyter Discourse](http://discourse.jupyter.org/) where a number of discussion about embedding in iframe took place in the past.

**Comment by itaynvn** [comment]
@krassowski thanks for the swift response! appreciate it. i will browse jupyter discourse as well.
Is `NotebookApp` obsolete? i simply followed common conventions found online, and the tornado configuration for example are being passed properly. i'd be happy to be refered to the best practice if available

**Comment by krassowski** [comment]
Yes it is, sorry it would have been useful if I provided a reference: [Migrating from Notebook Server](https://jupyter-server.readthedocs.io/en/latest/operators/migrate-from-nbserver.html), [Jupyter Notebook 6.5.0 Release Candidate](https://blog.jupyter.org/jupyter-notebook-6-5-0-release-candidate-4c229c6dab55), [this SO answer](https://stackoverflow.com/a/67804732/6646912).

**Comment by JasonWeill** [comment]
[JupyterLite](https://jupyterlite.readthedocs.io/en/latest/) is more explicitly designed for embedding than JupyterLab is. Have you tried embedding JupyterLite instead? Curious about whether this would meet your needs.
