### ISSUE TITLE
command jupyter-lab did not work

### ISSUE THREAD

**Issue by donhuvy** [jupyterlab/jupyterlab#14602]
![image](https://github.com/jupyterlab/jupyterlab/assets/1328316/83a17377-d240-4bac-b9d1-f3b5f260ddbb)

![image](https://github.com/jupyterlab/jupyterlab/assets/1328316/fcfcbe51-ffe4-46a8-84a2-282b8f002a63)

```bash
Microsoft Windows [Version 10.0.22621.1702]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>jupyter-lab
'jupyter-lab' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32>python -version
Unknown option: -e
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

C:\Windows\System32>python --version
Python 3.11.3

C:\Windows\System32>
```

![image](https://github.com/jupyterlab/jupyterlab/assets/1328316/669dcdea-5351-405d-917b-441418b54684)

**Comment by krassowski** [comment]
It is likely that your pip installation path is not in path, see answers on https://stackoverflow.com/questions/41034866/running-jupyter-via-command-line-on-windows.

At the level of this repository this is mostly outside of our control (this is a general pip/Python/Windows installation interaction depending on many factors). Installing JupyterLab using other channels may not have this limitation, for example [JupyterLab Desktop](https://github.com/jupyterlab/jupyterlab-desktop) could be of your interest.
