### ISSUE TITLE
Kernel has died issue when loading a 7gb h5ad file into robjects

### ISSUE THREAD

**Issue by ngvananh2508** [jupyterlab/jupyterlab#14611]
When I run these code: 
import scanpy as sp
import rpy2
import rpy2.robjects as ro

adata = sc.read(filename = "s4d8_normalization.h5ad")
ro.globalenv["adata"] = adata

adata is 7gb h5ad file.
And it appeared this error: Kernel Restarting
The kernel for Feature selection.ipynb appears to have died. It will restart automatically.

I tried to reallocate the memory to 16gb and 32gb in jupyter_lab_config.py but it did not work. Now I am running jupyter-lab on a computer which has configuration: AMD 5950X, 32GB Ram.

I am using Linux 22.04.2 LTS, Jupyter-lab version: 4.0.0, rpy2 version: 3.5.12, scanpy version: 1.9.3

Can anyone please help me?

Thank you very much!

**Comment by JasonWeill** [comment]
Do you see any errors in the console? Do you see the same error when running your Python code in IPython on the command line? Do you see similar problems if you load a partial version of the same file (e.g., by loading only the first 1 GB of it)?

**Comment by ngvananh2508** [comment]
> Do you see any errors in the console? Do you see the same error when running your Python code in IPython on the command line? Do you see similar problems if you load a partial version of the same file (e.g., by loading only the first 1 GB of it)?
I did not see any errors on terminal, just the notification: the kernel has died. When I ran these codes on terminal, it appeared this error: NotImplementedError: Conversion 'py2rpy' not defined for objects of type '<class 'anndata._core.anndata.AnnData'>'. May be this error emits from the compatibility between python kernel and package. When I loaded a small part of it (4.5 GB), it sometimes has died, too.

**Comment by krassowski** [comment]
This is almost certainly a memory limitation. rpy2 needs more memory for conversion than the file size itself. The important question for us is: does it happen when you run the same code _outside_ of JupyterLab, e.g. in Python terminal or IPython terminal. This will confirm that JupyterLab is not at fault here but you are simply running out of memory.

There are ways to be more memory efficient (and performant) with rpy2 (e.g. using arrow) but this is not a good place to discuss it.

**Comment by ngvananh2508** [comment]
I ran this code on terminal and it appeared the NotImplementedError. I will follow your suggestion.

Thank you very much for your suggestions!
