### ISSUE TITLE
Code cell input coloring with ijavascript Kernel not working

### ISSUE THREAD

**Issue by Rmarieta** [jupyterlab/jupyterlab#14627]
## Description

I have been trying to migrate my previous extension to JupyterLab 4.0.1 from JupyterLab 3.x, and I observe that the code cell input coloring is gone when using the JavaScript kernel (`ijavascript`) as compared to using the default Python one.

![image](https://github.com/jupyterlab/jupyterlab/assets/33026272/edb753a8-6371-4556-bea9-3c6e77d6187a)

In addition to this, I also observe an error in my browser developer tools console when I switch to that kernel (`JavaScript (Node.js)`) from the `Select Kernel` window and press `Select` : 
```
TypeError: Cannot read properties of undefined (reading 'widget')
    at isReady (jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00:1:1054549)
    at jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00:1:872986
    at b (jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00:1:873080)
    at P.onKernelChanged (jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00:1:1053706)
    at m (jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00:1:1646566)
    at Object.l [as emit] (jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00:1:1646242)
    at a.emit (jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00:1:1644079)
    at b._onKernelChanged (jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00:1:132174)
    at m (jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00:1:1646566)
    at Object.l [as emit] (jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00:1:1646242)
```

This `reading 'widget'` error also occurs if I switch from two default JupyterLab kernels, for example if I change Kernel to another notebook's kernel with the option `Use a Kernel From Preferred Session`.

I am aware that this could potentially be a problem with the JavaScript Kernel in itself, but since it was working fine in JupyterLab 3, it might still be worth reporting this issue to have a look at what is going wrong.

## Reproduce

1. Build the JupyterLab environment and install the javascript kernel : 
```
conda create -n tmp --override-channels --strict-channel-priority -c conda-forge -c nodefaults jupyterlab=4
conda activate tmp
npm install -g ijavascript
ijsinstall
```
2. Create a notebook and add a code cell with JavaScript code such as : 
```
const func = () => {
    console.log("Hello");
}
func()
``` 
3. Swith to the JavaScript Kernel
4. Wait and observe that the code cell input does not pick up the right colors and that the error mentioned in the Description is printed to the console. 

## Expected behavior

I would expect the code to display JavaScript code with colors following the JavaScript syntax but it's displayed in black and white instead.

## Context

- Operating System and version: Windows 11
- Browser and version: Chrome, version 112.0.5615.139
- JupyterLab version: 4.0.1

**Comment by jans-code** [comment]
> I am aware that this could potentially be a problem with the JavaScript Kernel in itself, but since it was working fine in JupyterLab 3, it might still be worth reporting this issue to have a look at what is going wrong.

This is a jupyterlab issue, javascript/typescript syntax highlighting does not work on tslab and I also cannot get it to work with a custom ipykernel.

**Comment by krassowski** [comment]
@Rmarieta the issue of highlighting in JavaScript kernel should be fixed by https://github.com/jupyterlab/jupyterlab/pull/15101 - please feel welcome to test it out. @jans-code from the description of "custom ipykernel notebooks" your issue might be unrelated I am afraid.
