### ISSUE TITLE
Settings get unselected when I select another one

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14637]
## Description

In CodeMirror settings checking all:
- Code Folding
- Highlight the active line
- Highlight trailing white spaces
- Highlight white spaces
is not possible as one get unselectedd when selecting another. Also switching tabs unselect somes of the checked positions.

## Reproduce

![what-is-going-on](https://github.com/jupyterlab/jupyterlab/assets/5832902/0a2f593c-4145-4d94-babc-0b1dd9ed5395)

Sadly, this belongs with https://twitter.com/volodarik/status/1657755496852475906

## Expected behavior

I can check all checkboxes.

## Context

- Browser and version: Edge 113.0.1774.57
- JupyterLab version: 4.0.1

**Comment by andrii-i** [comment]
Also present in JupyterLab 3.6.3

**Comment by brijsiyag** [comment]
I am able to re-produce. I want to give it a try, assign me if someone is not already working on this. Thanks !!

**Comment by andrii-i** [comment]
Thank you for volunteering @brijsiyag
