### ISSUE TITLE
Upgrade script is broken following copier 8.0.0 release

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#14643]
## Description

Error [seen on CI](https://github.com/jupyterlab/jupyterlab/actions/runs/5174471636/jobs/9320833877) when executing `python -m jupyterlab.upgrade_extension`

```
    copier.run_auto(template, output_dir, vcs_ref=vcs_ref, data=extra_context, defaults=True)
    ^^^^^^^^^^^^^^^
AttributeError: module 'copier' has no attribute 'run_auto'
```

## Expected behavior

no error

**Comment by dturaev** [comment]
Also, the documentation needs to be updated, e.g. https://jupyterlab.readthedocs.io/en/latest/extension/extension_tutorial.html, line `copier https://github.com/jupyterlab/extension-template .` -> `copier copy https://github.com/jupyterlab/extension-template .`

**Comment by fcollonval** [comment]
Good catch @dturaev
