### ISSUE TITLE
Cell toolbar overlaps horizontal rule in markdown cell

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#14646]
## Description

When the first line of a markdown cell is a horizontal rule (horizontal line), and the markdown cell is rendered, and the markdown cell becomes focused, the horizontal rule overlaps the cell toolbar. Screenshot by @3coins in https://github.com/jupyterlab/jupyter-ai/pull/170#issuecomment-1577666751:

<img width="782" alt="Screen Shot 2023-06-05 at 1 58 23 PM" src="https://github.com/jupyterlab/jupyter-ai/assets/289369/d939c99c-3511-41ab-8abf-9b550e6a5fe8">

## Reproduce

1. Create a code cell and a markdown cell.
2. In the markdown cell, enter some  markdown starting with a horizontal rule.
3. Render the markdown cell.
4. Run the code cell.

## Expected behavior

Horizontal rule does not overlap cell toolbar.

## Context

- Operating System and version: macOS
- Browser and version: 
- JupyterLab version: 4.0.1 (tip of `main`)

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
What if the toolbar had semi transparent background? In contrast to the case of text, the horizontal line is purely decorative and when toolbar overlaps it just can infer what is underneath. There is also a utility of having the cell toolbar, and we potentially lower code complexity.

**Comment by JasonWeill** [comment]
Oops, this was already filed as #12652. Resolves as duplicate.
