### ISSUE TITLE
New cells created with "b" hotkey in command mode are not scrolled into view

### ISSUE THREAD

**Issue by aakhmetz** [jupyterlab/jupyterlab#14641]
When I create a new cell by pushing "b" on my keyboard, the focus moves to the next (existent) cell. If the latter is long, the shift completely hides a newly created one from the display. In this case, I need to scroll up. I think it could be more convenient to keep a newly created cell selected and keep focus on it.

**Comment by andrii-i** [comment]
Hi @aakhmetz! Thank you for creating this issue. Am I correct that you would prefer new cell created by pressing "b" to be always focused and scrolled into view?

**Comment by JasonWeill** [comment]
Which version of JupyterLab are you running? We found an issue #14220 concerning this in the 4.0 alpha, but it was fixed by @fcollonval in #14407, and it should be fixed in 4.0.0 or 4.0.1.

**Comment by andrii-i** [comment]
I can replicate in 4.0.1 that new cells created with "b" hotkey (in command mode) are not scrolled into view. Tested and in 3.6.3 they are getting scrolled into view so I would imagine it has to do with notebook virtualization.

![cells_not_focused](https://github.com/jupyterlab/jupyterlab/assets/26686070/63c6c5a9-0ca0-49ee-b477-bebb44bed4cc)

**Comment by aakhmetz** [comment]
just to add one more: when I execute the cell "Shift-Enter", the focus does not move to the output, but jumps to the next cell hiding the output completely (similarly, I had to scroll up every time)

**Comment by f0uriest** [comment]
I've also been having this issue, it's super annoying. It's present in at least v4.0.5, I had to downgrade to v3.6.5 to undo it.

**Comment by hversteegzepp** [comment]
I've run into the first item mentioned here as well with a recent install. Same with the issue of running a cell and the output being skipped if the next cell is large enough (where the logic seems to be that as much of the newly selected cell should be shown as possible, even if it means scrolling right past the output of the cell you just executed). Though that second part seems like a different issue(?)

**Comment by krassowski** [comment]
> Same with the issue of running a cell and the output being skipped if the next cell is large enough

@hversteegzepp with which exact JupyterLab version? There are separate issues tracking this and they were closed because a fix was released in 4.0.9. See https://github.com/jupyterlab/jupyterlab/pull/15288

**Comment by aakhmetz** [comment]
It works with the latest update (4.1.6) - Many thanks!
