### ISSUE TITLE
Start jupyter server in the middle of python code

### ISSUE THREAD

**Issue by mghmgh1281375** [jupyterlab/jupyterlab#14657]
### Problem

I want to start the Jupyter server in the middle of the Python code and pass the context (`locals()` and `globals()`) to it.

### Proposed Solution

A Python interface to start Jupyter server

### Additional context

It's like putting `breakpoint()` in the middle of the code.

**Comment by krassowski** [comment]
It sounds that you want to spawn a JupyterLab instance with a Python kernel from another application, is this correct?

Spawning a jupyter server should be easy, starting an ipython kernel with preloaded variables may be doable (easier if those can be serialised, possibly harder if you want to share them from a running process).

However it is not clear to me what you already tried, what are your constraints, and wherever this should be discussed in this repository or maybe better suited for Jupyter Forum (discourse) discussion. Can you provide more context?

**Comment by mghmgh1281375** [comment]
Yes, It is correct.
I want to debug and analyze my processed data in the middle of the code. Normally, I dump data at certain points and then load them into Jupyter notebooks using `pickle`. But I'm looking for a command that freezes the program at a particular line and then opens Jupyter notebooks. Similar to `breakpoint()`.

You are right, perhaps this isn't the right place for such a question.
