### ISSUE TITLE
Firefox doesn't show horizontal scrollbar for pandas dataframe

### ISSUE THREAD

**Issue by janfrederik** [jupyterlab/jupyterlab#14656]
## Description

The output of a pandas dataframe with many columns doesn't show a horizontal scrollbar, so I can't see all columns.

## Reproduce

1. Start the most recent jupyter lab docker image:
    ```shell
    docker run -it --rm -p 10000:8888 jupyter/base-notebook jupyter lab --debug
    ```
2. Browse with Firefox to the jupyter lab: http://localhost:10000
3. Open a terminal to `pip install pandas`
4. Create a new Python 3 notebook and execute the following cell content:
    ```python
    import pandas as pd
    pd.read_csv('https://raw.githubusercontent.com/ma-ji/RICF/v2015.1.0/2015/2015_financial_activities.tsv', sep='\t', header=1).head(3)
    ```
5. This displays the dataframe but there is no horizontal scrollbar
![image](https://github.com/jupyterlab/jupyterlab/assets/18148910/cf4d5e55-35d1-4620-af24-7b871f41c527)

## Expected behavior

Horizontal scrollbar appears so I can scroll :-)

The scrollbar is there in MS Edge:
![image](https://github.com/jupyterlab/jupyterlab/assets/18148910/104e35e8-7be1-424c-ab61-8e7b67cf4311)

## Context

- Operating System and version: Windows 11
- Browser and version: Firefox 113.0.2
- JupyterLab version: 4.0.1

<details><summary>Troubleshoot Output</summary>
<pre>
(base) jovyan@23718e2f95fc:~$ jupyter troubleshoot
$PATH:
        /opt/conda/bin
        /opt/conda/condabin
        /opt/conda/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /opt/conda/bin
        /opt/conda/lib/python311.zip
        /opt/conda/lib/python3.11
        /opt/conda/lib/python3.11/lib-dynload
        /opt/conda/lib/python3.11/site-packages

sys.executable:
        /opt/conda/bin/python

sys.version:
        3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]

platform.platform():
        Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

which -a jupyter:
        /opt/conda/bin/jupyter
        /opt/conda/bin/jupyter

pip list:
        Package                       Version
        ----------------------------- -----------
        alembic                       1.11.1
        anyio                         3.7.0
        argon2-cffi                   21.3.0
        argon2-cffi-bindings          21.2.0
        asttokens                     2.2.1
        async-generator               1.10
        async-lru                     2.0.2
        attrs                         23.1.0
        Babel                         2.12.1
        backcall                      0.2.0
        backports.functools-lru-cache 1.6.4
        beautifulsoup4                4.12.2
        bleach                        6.0.0
        blinker                       1.6.2
        boltons                       23.0.0
        certifi                       2023.5.7
        certipy                       0.1.3
        cffi                          1.15.1
        charset-normalizer            3.1.0
        colorama                      0.4.6
        comm                          0.1.3
        conda                         23.3.1
        conda-package-handling        2.0.2
        conda_package_streaming       0.8.0
        cryptography                  41.0.1
        debugpy                       1.6.7
        decorator                     5.1.1
        defusedxml                    0.7.1
        entrypoints                   0.4
        exceptiongroup                1.1.1
        executing                     1.2.0
        fastjsonschema                2.17.1
        flit_core                     3.9.0
        greenlet                      2.0.2
        idna                          3.4
        importlib-metadata            6.6.0
        importlib-resources           5.12.0
        ipykernel                     6.23.1
        ipython                       8.14.0
        ipython-genutils              0.2.0
        jedi                          0.18.2
        Jinja2                        3.1.2
        json5                         0.9.5
        jsonpatch                     1.32
        jsonpointer                   2.0
        jsonschema                    4.17.3
        jupyter_client                8.2.0
        jupyter_core                  5.3.0
        jupyter-events                0.6.3
        jupyter-lsp                   2.2.0
        jupyter_server                2.6.0
        jupyter_server_terminals      0.4.4
        jupyter-telemetry             0.1.0
        jupyterhub                    4.0.0
        jupyterlab                    4.0.1
        jupyterlab-pygments           0.2.2
        jupyterlab_server             2.22.1
        libmambapy                    1.4.2
        Mako                          1.2.4
        mamba                         1.4.2
        MarkupSafe                    2.1.3
        matplotlib-inline             0.1.6
        mistune                       2.0.5
        nbclassic                     1.0.0
        nbclient                      0.8.0
        nbconvert                     7.4.0
        nbformat                      5.9.0
        nest-asyncio                  1.5.6
        notebook                      6.5.4
        notebook_shim                 0.2.3
        numpy                         1.24.3
        oauthlib                      3.2.2
        overrides                     7.3.1
        packaging                     23.1
        pamela                        1.0.0
        pandas                        2.0.2
        pandocfilters                 1.5.0
        parso                         0.8.3
        pexpect                       4.8.0
        pickleshare                   0.7.5
        pip                           23.1.2
        pkgutil_resolve_name          1.3.10
        platformdirs                  3.5.1
        pluggy                        1.0.0
        prometheus-client             0.17.0
        prompt-toolkit                3.0.38
        psutil                        5.9.5
        ptyprocess                    0.7.0
        pure-eval                     0.2.2
        pycosat                       0.6.4
        pycparser                     2.21
        pycurl                        7.45.1
        Pygments                      2.15.1
        PyJWT                         2.7.0
        pyOpenSSL                     23.2.0
        pyrsistent                    0.19.3
        PySocks                       1.7.1
        python-dateutil               2.8.2
        python-json-logger            2.0.7
        pytz                          2023.3
        PyYAML                        6.0
        pyzmq                         25.1.0
        requests                      2.31.0
        rfc3339-validator             0.1.4
        rfc3986-validator             0.1.1
        ruamel.yaml                   0.17.31
        ruamel.yaml.clib              0.2.7
        Send2Trash                    1.8.2
        setuptools                    67.7.2
        six                           1.16.0
        sniffio                       1.3.0
        soupsieve                     2.3.2.post1
        SQLAlchemy                    2.0.15
        stack-data                    0.6.2
        terminado                     0.17.1
        tinycss2                      1.2.1
        tomli                         2.0.1
        toolz                         0.12.0
        tornado                       6.3.2
        tqdm                          4.65.0
        traitlets                     5.9.0
        typing_extensions             4.6.3
        typing-utils                  0.1.0
        tzdata                        2023.3
        urllib3                       2.0.2
        wcwidth                       0.2.6
        webencodings                  0.5.1
        websocket-client              1.5.2
        wheel                         0.40.0
        zipp                          3.15.0
        zstandard                     0.19.0

conda list:
        # packages in environment at /opt/conda:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       2_gnu    conda-forge
        alembic                   1.11.1             pyhd8ed1ab_0    conda-forge
        anyio                     3.7.0              pyhd8ed1ab_1    conda-forge
        argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
        argon2-cffi-bindings      21.2.0          py311hd4cff14_3    conda-forge
        asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
        async-lru                 2.0.2              pyhd8ed1ab_0    conda-forge
        async_generator           1.10                       py_0    conda-forge
        attrs                     23.1.0             pyh71513ae_1    conda-forge
        babel                     2.12.1             pyhd8ed1ab_1    conda-forge
        backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
        backports                 1.0                pyhd8ed1ab_3    conda-forge
        backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
        beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
        bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
        blinker                   1.6.2              pyhd8ed1ab_0    conda-forge
        boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
        brotli                    1.0.9                h166bdaf_8    conda-forge
        brotli-bin                1.0.9                h166bdaf_8    conda-forge
        bzip2                     1.0.8                h7f98852_4    conda-forge
        c-ares                    1.19.1               hd590300_0    conda-forge
        ca-certificates           2023.5.7             hbcca054_0    conda-forge
        certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
        certipy                   0.1.3                      py_0    conda-forge
        cffi                      1.15.1          py311h409f033_3    conda-forge
        charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
        colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
        comm                      0.1.3              pyhd8ed1ab_0    conda-forge
        conda                     23.3.1          py311h38be061_0    conda-forge
        conda-package-handling    2.0.2              pyh38be061_0    conda-forge
        conda-package-streaming   0.8.0              pyhd8ed1ab_0    conda-forge
        configurable-http-proxy   4.5.4                he2f69ee_2    conda-forge
        cryptography              41.0.1          py311h63ff55d_0    conda-forge
        debugpy                   1.6.7           py311hcafe171_0    conda-forge
        decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
        defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
        entrypoints               0.4                pyhd8ed1ab_0    conda-forge
        exceptiongroup            1.1.1              pyhd8ed1ab_0    conda-forge
        executing                 1.2.0              pyhd8ed1ab_0    conda-forge
        flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
        fmt                       9.1.0                h924138e_0    conda-forge
        greenlet                  2.0.2           py311hb755f60_1    conda-forge
        icu                       72.1                 hcb278e6_0    conda-forge
        idna                      3.4                pyhd8ed1ab_0    conda-forge
        importlib-metadata        6.6.0              pyha770c72_0    conda-forge
        importlib_metadata        6.6.0                hd8ed1ab_0    conda-forge
        importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
        ipykernel                 6.23.1             pyh210e3f2_0    conda-forge
        ipython                   8.14.0             pyh41d4057_0    conda-forge
        ipython_genutils          0.2.0                      py_1    conda-forge
        jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
        jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
        json5                     0.9.5              pyh9f0ad1d_0    conda-forge
        jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
        jsonpointer               2.0                        py_0    conda-forge
        jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
        jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
        jupyter_client            8.2.0              pyhd8ed1ab_0    conda-forge
        jupyter_core              5.3.0           py311h38be061_0    conda-forge
        jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
        jupyter_server            2.6.0              pyhd8ed1ab_0    conda-forge
        jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
        jupyter_telemetry         0.1.0              pyhd8ed1ab_1    conda-forge
        jupyterhub                4.0.0              pyh2a2186d_0    conda-forge
        jupyterhub-base           4.0.0              pyh2a2186d_0    conda-forge
        jupyterlab                4.0.1              pyhd8ed1ab_0    conda-forge
        jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
        jupyterlab_server         2.22.1             pyhd8ed1ab_0    conda-forge
        keyutils                  1.6.1                h166bdaf_0    conda-forge
        krb5                      1.20.1               h81ceb04_0    conda-forge
        ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
        libarchive                3.6.2                h039dbb9_1    conda-forge
        libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
        libbrotlidec              1.0.9                h166bdaf_8    conda-forge
        libbrotlienc              1.0.9                h166bdaf_8    conda-forge
        libcurl                   8.1.2                h409715c_0    conda-forge
        libedit                   3.1.20191231         he28a2e2_2    conda-forge
        libev                     4.33                 h516909a_1    conda-forge
        libexpat                  2.5.0                hcb278e6_1    conda-forge
        libffi                    3.4.2                h7f98852_5    conda-forge
        libgcc-ng                 13.1.0               he5830b7_0    conda-forge
        libgomp                   13.1.0               he5830b7_0    conda-forge
        libiconv                  1.17                 h166bdaf_0    conda-forge
        libmamba                  1.4.2                hcea66bb_0    conda-forge
        libmambapy                1.4.2           py311h1f88262_0    conda-forge
        libnghttp2                1.52.0               h61bc06f_0    conda-forge
        libnsl                    2.0.0                h7f98852_0    conda-forge
        libsodium                 1.0.18               h36c2ea0_1    conda-forge
        libsolv                   0.7.24               h3eb15da_0    conda-forge
        libsqlite                 3.42.0               h2797004_0    conda-forge
        libssh2                   1.11.0               h0841786_0    conda-forge
        libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
        libuuid                   2.38.1               h0b41bf4_0    conda-forge
        libuv                     1.44.2               h166bdaf_0    conda-forge
        libxml2                   2.11.4               h0d562d8_0    conda-forge
        libzlib                   1.2.13               h166bdaf_4    conda-forge
        lz4-c                     1.9.4                hcb278e6_0    conda-forge
        lzo                       2.10              h516909a_1000    conda-forge
        mako                      1.2.4              pyhd8ed1ab_0    conda-forge
        mamba                     1.4.2           py311h3072747_0    conda-forge
        markupsafe                2.1.3           py311h459d7ec_0    conda-forge
        matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
        mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
        nbclassic                 1.0.0              pyhb4ecaf3_1    conda-forge
        nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
        nbconvert                 7.4.0              pyhd8ed1ab_0    conda-forge
        nbconvert-core            7.4.0              pyhd8ed1ab_0    conda-forge
        nbconvert-pandoc          7.4.0              pyhd8ed1ab_0    conda-forge
        nbformat                  5.9.0              pyhd8ed1ab_0    conda-forge
        ncurses                   6.3                  h27087fc_1    conda-forge
        nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
        nodejs                    18.15.0              h4abf6b9_1    conda-forge
        notebook                  6.5.4              pyha770c72_0    conda-forge
        notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
        numpy                     1.24.3                   pypi_0    pypi
        oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
        openssl                   3.1.1                hd590300_1    conda-forge
        overrides                 7.3.1              pyhd8ed1ab_0    conda-forge
        packaging                 23.1               pyhd8ed1ab_0    conda-forge
        pamela                    1.0.0                      py_0    conda-forge
        pandas                    2.0.2                    pypi_0    pypi
        pandoc                    2.19.2               h32600fe_2    conda-forge
        pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
        parso                     0.8.3              pyhd8ed1ab_0    conda-forge
        pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
        pickleshare               0.7.5                   py_1003    conda-forge
        pip                       23.1.2             pyhd8ed1ab_0    conda-forge
        pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
        platformdirs              3.5.1              pyhd8ed1ab_0    conda-forge
        pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
        prometheus_client         0.17.0             pyhd8ed1ab_0    conda-forge
        prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
        prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
        psutil                    5.9.5           py311h2582759_0    conda-forge
        ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
        pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
        pybind11-abi              4                    hd8ed1ab_3    conda-forge
        pycosat                   0.6.4           py311hd4cff14_1    conda-forge
        pycparser                 2.21               pyhd8ed1ab_0    conda-forge
        pycurl                    7.45.1          py311hae980a4_3    conda-forge
        pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
        pyjwt                     2.7.0              pyhd8ed1ab_0    conda-forge
        pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
        pyrsistent                0.19.3          py311h2582759_0    conda-forge
        pysocks                   1.7.1              pyha2e5f31_6    conda-forge
        python                    3.11.3          h2755cc3_0_cpython    conda-forge
        python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
        python-fastjsonschema     2.17.1             pyhd8ed1ab_0    conda-forge
        python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
        python_abi                3.11                    3_cp311    conda-forge
        pytz                      2023.3             pyhd8ed1ab_0    conda-forge
        pyyaml                    6.0             py311hd4cff14_5    conda-forge
        pyzmq                     25.1.0          py311h75c88c4_0    conda-forge
        readline                  8.2                  h8228510_1    conda-forge
        reproc                    14.2.4               h0b41bf4_0    conda-forge
        reproc-cpp                14.2.4               hcb278e6_0    conda-forge
        requests                  2.31.0             pyhd8ed1ab_0    conda-forge
        rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
        rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
        ruamel.yaml               0.17.31         py311h459d7ec_0    conda-forge
        ruamel.yaml.clib          0.2.7           py311h2582759_1    conda-forge
        send2trash                1.8.2              pyh41d4057_0    conda-forge
        setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
        six                       1.16.0             pyh6c4a22f_0    conda-forge
        sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
        soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
        sqlalchemy                2.0.15          py311h459d7ec_0    conda-forge
        stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
        terminado                 0.17.1             pyh41d4057_0    conda-forge
        tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
        tk                        8.6.12               h27826a3_0    conda-forge
        tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
        toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
        tornado                   6.3.2           py311h459d7ec_0    conda-forge
        tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
        traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
        typing-extensions         4.6.3                hd8ed1ab_0    conda-forge
        typing_extensions         4.6.3              pyha770c72_0    conda-forge
        typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
        tzdata                    2023.3                   pypi_0    pypi
        urllib3                   2.0.2              pyhd8ed1ab_0    conda-forge
        wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
        webencodings              0.5.1                      py_1    conda-forge
        websocket-client          1.5.2              pyhd8ed1ab_0    conda-forge
        wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
        xz                        5.2.6                h166bdaf_0    conda-forge
        yaml                      0.2.5                h7f98852_2    conda-forge
        yaml-cpp                  0.7.0                h27087fc_2    conda-forge
        zeromq                    4.3.4                h9c3ff4c_1    conda-forge
        zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
        zlib                      1.2.13               h166bdaf_4    conda-forge
        zstandard                 0.19.0          py311hbe0fcd7_1    conda-forge
        zstd                      1.5.2                h3eb15da_6    conda-forge

conda env:
        name: base
        channels:
          - conda-forge
        dependencies:
          - _libgcc_mutex=0.1=conda_forge
          - _openmp_mutex=4.5=2_gnu
          - alembic=1.11.1=pyhd8ed1ab_0
          - anyio=3.7.0=pyhd8ed1ab_1
          - argon2-cffi=21.3.0=pyhd8ed1ab_0
          - argon2-cffi-bindings=21.2.0=py311hd4cff14_3
          - asttokens=2.2.1=pyhd8ed1ab_0
          - async-lru=2.0.2=pyhd8ed1ab_0
          - async_generator=1.10=py_0
          - attrs=23.1.0=pyh71513ae_1
          - babel=2.12.1=pyhd8ed1ab_1
          - backcall=0.2.0=pyh9f0ad1d_0
          - backports=1.0=pyhd8ed1ab_3
          - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
          - beautifulsoup4=4.12.2=pyha770c72_0
          - bleach=6.0.0=pyhd8ed1ab_0
          - blinker=1.6.2=pyhd8ed1ab_0
          - boltons=23.0.0=pyhd8ed1ab_0
          - brotli=1.0.9=h166bdaf_8
          - brotli-bin=1.0.9=h166bdaf_8
          - bzip2=1.0.8=h7f98852_4
          - c-ares=1.19.1=hd590300_0
          - ca-certificates=2023.5.7=hbcca054_0
          - certifi=2023.5.7=pyhd8ed1ab_0
          - certipy=0.1.3=py_0
          - cffi=1.15.1=py311h409f033_3
          - charset-normalizer=3.1.0=pyhd8ed1ab_0
          - colorama=0.4.6=pyhd8ed1ab_0
          - comm=0.1.3=pyhd8ed1ab_0
          - conda=23.3.1=py311h38be061_0
          - conda-package-handling=2.0.2=pyh38be061_0
          - conda-package-streaming=0.8.0=pyhd8ed1ab_0
          - configurable-http-proxy=4.5.4=he2f69ee_2
          - cryptography=41.0.1=py311h63ff55d_0
          - debugpy=1.6.7=py311hcafe171_0
          - decorator=5.1.1=pyhd8ed1ab_0
          - defusedxml=0.7.1=pyhd8ed1ab_0
          - entrypoints=0.4=pyhd8ed1ab_0
          - exceptiongroup=1.1.1=pyhd8ed1ab_0
          - executing=1.2.0=pyhd8ed1ab_0
          - flit-core=3.9.0=pyhd8ed1ab_0
          - fmt=9.1.0=h924138e_0
          - greenlet=2.0.2=py311hb755f60_1
          - icu=72.1=hcb278e6_0
          - idna=3.4=pyhd8ed1ab_0
          - importlib-metadata=6.6.0=pyha770c72_0
          - importlib_metadata=6.6.0=hd8ed1ab_0
          - importlib_resources=5.12.0=pyhd8ed1ab_0
          - ipykernel=6.23.1=pyh210e3f2_0
          - ipython=8.14.0=pyh41d4057_0
          - ipython_genutils=0.2.0=py_1
          - jedi=0.18.2=pyhd8ed1ab_0
          - jinja2=3.1.2=pyhd8ed1ab_1
          - json5=0.9.5=pyh9f0ad1d_0
          - jsonpatch=1.32=pyhd8ed1ab_0
          - jsonpointer=2.0=py_0
          - jsonschema=4.17.3=pyhd8ed1ab_0
          - jupyter-lsp=2.2.0=pyhd8ed1ab_0
          - jupyter_client=8.2.0=pyhd8ed1ab_0
          - jupyter_core=5.3.0=py311h38be061_0
          - jupyter_events=0.6.3=pyhd8ed1ab_0
          - jupyter_server=2.6.0=pyhd8ed1ab_0
          - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
          - jupyter_telemetry=0.1.0=pyhd8ed1ab_1
          - jupyterhub=4.0.0=pyh2a2186d_0
          - jupyterhub-base=4.0.0=pyh2a2186d_0
          - jupyterlab=4.0.1=pyhd8ed1ab_0
          - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
          - jupyterlab_server=2.22.1=pyhd8ed1ab_0
          - keyutils=1.6.1=h166bdaf_0
          - krb5=1.20.1=h81ceb04_0
          - ld_impl_linux-64=2.40=h41732ed_0
          - libarchive=3.6.2=h039dbb9_1
          - libbrotlicommon=1.0.9=h166bdaf_8
          - libbrotlidec=1.0.9=h166bdaf_8
          - libbrotlienc=1.0.9=h166bdaf_8
          - libcurl=8.1.2=h409715c_0
          - libedit=3.1.20191231=he28a2e2_2
          - libev=4.33=h516909a_1
          - libexpat=2.5.0=hcb278e6_1
          - libffi=3.4.2=h7f98852_5
          - libgcc-ng=13.1.0=he5830b7_0
          - libgomp=13.1.0=he5830b7_0
          - libiconv=1.17=h166bdaf_0
          - libmamba=1.4.2=hcea66bb_0
          - libmambapy=1.4.2=py311h1f88262_0
          - libnghttp2=1.52.0=h61bc06f_0
          - libnsl=2.0.0=h7f98852_0
          - libsodium=1.0.18=h36c2ea0_1
          - libsolv=0.7.24=h3eb15da_0
          - libsqlite=3.42.0=h2797004_0
          - libssh2=1.11.0=h0841786_0
          - libstdcxx-ng=13.1.0=hfd8a6a1_0
          - libuuid=2.38.1=h0b41bf4_0
          - libuv=1.44.2=h166bdaf_0
          - libxml2=2.11.4=h0d562d8_0
          - libzlib=1.2.13=h166bdaf_4
          - lz4-c=1.9.4=hcb278e6_0
          - lzo=2.10=h516909a_1000
          - mako=1.2.4=pyhd8ed1ab_0
          - mamba=1.4.2=py311h3072747_0
          - markupsafe=2.1.3=py311h459d7ec_0
          - matplotlib-inline=0.1.6=pyhd8ed1ab_0
          - mistune=2.0.5=pyhd8ed1ab_0
          - nbclassic=1.0.0=pyhb4ecaf3_1
          - nbclient=0.8.0=pyhd8ed1ab_0
          - nbconvert=7.4.0=pyhd8ed1ab_0
          - nbconvert-core=7.4.0=pyhd8ed1ab_0
          - nbconvert-pandoc=7.4.0=pyhd8ed1ab_0
          - nbformat=5.9.0=pyhd8ed1ab_0
          - ncurses=6.3=h27087fc_1
          - nest-asyncio=1.5.6=pyhd8ed1ab_0
          - nodejs=18.15.0=h4abf6b9_1
          - notebook=6.5.4=pyha770c72_0
          - notebook-shim=0.2.3=pyhd8ed1ab_0
          - oauthlib=3.2.2=pyhd8ed1ab_0
          - openssl=3.1.1=hd590300_1
          - overrides=7.3.1=pyhd8ed1ab_0
          - packaging=23.1=pyhd8ed1ab_0
          - pamela=1.0.0=py_0
          - pandoc=2.19.2=h32600fe_2
          - pandocfilters=1.5.0=pyhd8ed1ab_0
          - parso=0.8.3=pyhd8ed1ab_0
          - pexpect=4.8.0=pyh1a96a4e_2
          - pickleshare=0.7.5=py_1003
          - pip=23.1.2=pyhd8ed1ab_0
          - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
          - platformdirs=3.5.1=pyhd8ed1ab_0
          - pluggy=1.0.0=pyhd8ed1ab_5
          - prometheus_client=0.17.0=pyhd8ed1ab_0
          - prompt-toolkit=3.0.38=pyha770c72_0
          - prompt_toolkit=3.0.38=hd8ed1ab_0
          - psutil=5.9.5=py311h2582759_0
          - ptyprocess=0.7.0=pyhd3deb0d_0
          - pure_eval=0.2.2=pyhd8ed1ab_0
          - pybind11-abi=4=hd8ed1ab_3
          - pycosat=0.6.4=py311hd4cff14_1
          - pycparser=2.21=pyhd8ed1ab_0
          - pycurl=7.45.1=py311hae980a4_3
          - pygments=2.15.1=pyhd8ed1ab_0
          - pyjwt=2.7.0=pyhd8ed1ab_0
          - pyopenssl=23.2.0=pyhd8ed1ab_1
          - pyrsistent=0.19.3=py311h2582759_0
          - pysocks=1.7.1=pyha2e5f31_6
          - python=3.11.3=h2755cc3_0_cpython
          - python-dateutil=2.8.2=pyhd8ed1ab_0
          - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
          - python-json-logger=2.0.7=pyhd8ed1ab_0
          - python_abi=3.11=3_cp311
          - pytz=2023.3=pyhd8ed1ab_0
          - pyyaml=6.0=py311hd4cff14_5
          - pyzmq=25.1.0=py311h75c88c4_0
          - readline=8.2=h8228510_1
          - reproc=14.2.4=h0b41bf4_0
          - reproc-cpp=14.2.4=hcb278e6_0
          - requests=2.31.0=pyhd8ed1ab_0
          - rfc3339-validator=0.1.4=pyhd8ed1ab_0
          - rfc3986-validator=0.1.1=pyh9f0ad1d_0
          - ruamel.yaml=0.17.31=py311h459d7ec_0
          - ruamel.yaml.clib=0.2.7=py311h2582759_1
          - send2trash=1.8.2=pyh41d4057_0
          - setuptools=67.7.2=pyhd8ed1ab_0
          - six=1.16.0=pyh6c4a22f_0
          - sniffio=1.3.0=pyhd8ed1ab_0
          - soupsieve=2.3.2.post1=pyhd8ed1ab_0
          - sqlalchemy=2.0.15=py311h459d7ec_0
          - stack_data=0.6.2=pyhd8ed1ab_0
          - terminado=0.17.1=pyh41d4057_0
          - tinycss2=1.2.1=pyhd8ed1ab_0
          - tk=8.6.12=h27826a3_0
          - tomli=2.0.1=pyhd8ed1ab_0
          - toolz=0.12.0=pyhd8ed1ab_0
          - tornado=6.3.2=py311h459d7ec_0
          - tqdm=4.65.0=pyhd8ed1ab_1
          - traitlets=5.9.0=pyhd8ed1ab_0
          - typing-extensions=4.6.3=hd8ed1ab_0
          - typing_extensions=4.6.3=pyha770c72_0
          - typing_utils=0.1.0=pyhd8ed1ab_0
          - urllib3=2.0.2=pyhd8ed1ab_0
          - wcwidth=0.2.6=pyhd8ed1ab_0
          - webencodings=0.5.1=py_1
          - websocket-client=1.5.2=pyhd8ed1ab_0
          - wheel=0.40.0=pyhd8ed1ab_0
          - xz=5.2.6=h166bdaf_0
          - yaml=0.2.5=h7f98852_2
          - yaml-cpp=0.7.0=h27087fc_2
          - zeromq=4.3.4=h9c3ff4c_1
          - zipp=3.15.0=pyhd8ed1ab_0
          - zlib=1.2.13=h166bdaf_4
          - zstandard=0.19.0=py311hbe0fcd7_1
          - zstd=1.5.2=h3eb15da_6
          - pip:
              - numpy==1.24.3
              - pandas==2.0.2
              - tzdata==2023.3
        prefix: /opt/conda
</pre>
</details>

**Comment by janfrederik** [comment]
<details><summary>Browser Output</summary>

<pre>
Starting WebSocket: ws://localhost:10000/api/kernels/821d183b-a796-4fa9-afb3-26662b50d02e [jlab_core.b473ae48d19e9025bb00.js:1:1221354](http://localhost:10000/static/lab/jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00)
Language pack 'en_US' not installed! [jlab_core.b473ae48d19e9025bb00.js:1:1441334](http://localhost:10000/static/lab/jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00)
Starting application in workspace: "default" [jlab_core.b473ae48d19e9025bb00.js:1:7693](http://localhost:10000/static/lab/jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00)
Starting WebSocket: ws://localhost:10000/api/kernels/821d183b-a796-4fa9-afb3-26662b50d02e [jlab_core.b473ae48d19e9025bb00.js:1:1221354](http://localhost:10000/static/lab/jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00)
Starting WebSocket: ws://localhost:10000/api/kernels/821d183b-a796-4fa9-afb3-26662b50d02e [jlab_core.b473ae48d19e9025bb00.js:1:1221354](http://localhost:10000/static/lab/jlab_core.b473ae48d19e9025bb00.js?v=b473ae48d19e9025bb00)
</pre>
</details>

**Comment by krassowski** [comment]
This looks like a duplicate of #14625

**Comment by janfrederik** [comment]
@krassowski Yes, a duplicate indeed.  
Strange, I should have been able to find this issue.

**Comment by janfrederik** [comment]
Duplicate of #14625
