### ISSUE TITLE
Jupyter* won't work with %matplotlib osx.

### ISSUE THREAD

**Issue by ubaldot** [jupyterlab/jupyterlab#14653]
I found this issue when working with jupyter console, but it looks to be a general problem in jupyter ecosystem, therefore I thought it may be a good idea to signal it here.
Please, refer to https://github.com/jupyter/jupyter_console/issues/294 for more info.

**Comment by krassowski** [comment]
Well, jupyter-console repository was too specific but JupyterLab may be too broad - there is no code for IPython specific magic in here. IPython might be the sweet spot if you can reproduce this in IPython terminal.

This might be a problem with the build system and more details about your installation (conda channel e.g. conda forge, conda list, conda doctor, etc) may be useful to whoever will investigate it.

**Comment by ubaldot** [comment]
Thanks for your reply. 
In pure ipython console things work well.
The problem appears only in jupyter*. 
I installed all the related packages through conda-forge.

**Comment by Carreau** [comment]
I've opened https://github.com/ipython/ipykernel/issues/1124 on ipykernel repo. Closing here.
