### ISSUE TITLE
"Run Code" button become unclickable when a console has been opened

### ISSUE THREAD

**Issue by pikakolendo02** [jupyterlab/jupyterlab#14658]
## Description
![图片](https://github.com/jupyterlab/jupyterlab/assets/15796641/3518a1c9-c4bb-4665-9e83-7fd7b0de0506)
"Run Code" button become unclickable when a console has been opened.
I can only run the code cell by ctrl+enter or shift+enter.
Close the console and the "Run Code" button could be available again, but I want to click it with a console.
Is it on purposed?

## Reproduce
1. Run some code cells;
2. Right click the ipynb tab, "New Console for Notebook";
3. Return to ipynb tab and sometimes the "Run Code" button is unavailable.

## Expected behavior

The "Run Code" button is available when a console is opened.

## Context

- Operating System and version: Arch Linux
- Browser and version: Firefox 113.0.2
- JupyterLab version: 4.0.1

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by fcollonval** [comment]
I can reproduce the bug. Thanks @pikakolendo02 for reporting it.

**Comment by fcollonval** [comment]
Hey @brijsiyag thanks for proposing your help. I have already started to fix this - it is a bit tricky. But feel free to contribute to other issues.

**Comment by ctopfel** [comment]
This issue has a side-effect: When a console is open (such as original issuer has described), one cannot shift-enter through the notebook (that is linked to the console) anymore. Javascript Console shows the follow error message:
`Cannot execute key binding 'Shift Enter': command 'runmenu:run' is not enabled.`

**Comment by quctex** [comment]
There are also "Run all code" and "Restart kernel and run all code" menu items under Run and Kernel main menus grayed-out, when attached to notebook console is open.
