### ISSUE TITLE
Binder Not Working: Dockerfile build step fail. 

### ISSUE THREAD

**Issue by startakovsky** [jupyterlab/jupyterlab#14651]
The error: `Unknown Syntax Error: Unsupported option name ("--ignore-scripts")`, which comes from [this line on the Dockerfile](https://github.com/jupyterlab/jupyterlab/blob/79e7d2f36edc8a2f8ca4cab83ca91556f87f47fe/Dockerfile#L18).

Here is a snippet from the [build log](https://github.com/jupyterlab/jupyterlab/files/11671689/4a3b9441-2f3c-48c1-8a6b-1e3e5aeef4df.pdf) from binder. 

See attached for the whole thing. Also, it might be related to this: https://github.com/yarnpkg/yarn/issues/7338.

I assume `yarn` alone would be sufficient. 

```sh
Step 45/52 : USER ${NB_USER}
 ---> Running in 92d482b37b0d
Removing intermediate container 92d482b37b0d
 ---> 2743768abcc8
Step 46/52 : RUN chmod +x binder/postBuild
 ---> Running in d4ed2637ce99
Removing intermediate container d4ed2637ce99
 ---> e8d949625fb0
Step 47/52 : RUN ./binder/postBuild
 ---> Running in ef840cf7fbdb
[91m+ mkdir _reports_
[0m[91m+ tee _reports_/00_yarn.txt
[0m+ yarn --ignore-scripts --ignore-optional
Unknown Syntax Error: Unsupported option name ("--ignore-scripts").
```

**Comment by startakovsky** [comment]
[4a3b9441-2f3c-48c1-8a6b-1e3e5aeef4df.pdf](https://github.com/jupyterlab/jupyterlab/files/11671714/4a3b9441-2f3c-48c1-8a6b-1e3e5aeef4df.pdf)

**Comment by krassowski** [comment]
There is no `--ignore-scripts` in yarn 3 anymore. Does removing this flag make it work for you? Would you like to open a PR?

**Comment by startakovsky** [comment]
@krassowski it fails when I remove it.

The way I have been testing this is that I have run `scripts/build_docker.sh`.

The build steps run successfully and then the `yarn install` errors out on the install of 3 packages.

What is the purpose of the Dockerfile beyond binder? Just that it seems the error have existed for a bit.

Let me know what is best. Is the goal to have this work for Binder?

**Comment by krassowski** [comment]
Closing as that docker file has been removed and replaced by:

https://github.com/jupyterlab/jupyterlab/blob/144a5e84a3af41caa31d206e4aaef5fd9ff1e330/docker/Dockerfile#L1-L61

which does not include `--ignore-scripts`. `build_docker.sh` script does not exist too.

For the current docker setup instructions please see: https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#setup-using-docker - note this is tested on CI and no issues are known as of today.
