### ISSUE TITLE
indentation problem after multi-line Python function definition

### ISSUE THREAD

**Issue by mbakker7** [jupyterlab/jupyterlab#14668]
When I create a multi-line function definition in JupyterLab 4 (4.0.0), the indentation is messed up. So when I do a return, the cursor doesn't go to the right place, but always at about 13 spaces or something. This problems occurs on both Chrome and Safari on a Mac.
The simple example below shows what I mean. I wonder if others see the same problem.

Example:
```
def test(x,
         y): # after giving return here, the cursor doesn't go to the correct 4 spaces indentation
    print(x) # even after manually positioning the cursor in the right place, it goes to the wrong place after every return
    print(y) # still have a problem and had to manually position the cursor
```

The problem goes away when the function definition is on one line. For this case that would make sense, of course, but I ran into this for a function with a long argument list. The problem goes away when you finish the function by manually positioning the cursor back to position 0, even when omitting the `return` at the end of the function. But inside the function (when editing the function for example), the problem remains. Feels like a CodeMirror problem to me. Or is there something in Settings that I can adjust?

**Comment by krassowski** [comment]
I can reproduce this in [CodeMirror 6 playground](https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge3B5dGhvbn0gZnJvbSAiQGNvZGVtaXJyb3IvbGFuZy1weXRob24iCgpuZXcgRWRpdG9yVmlldyh7CiAgZG9jOiAiZGVmIHRlc3QoeCxcbiAgICAgICAgIHkpOlxuIiwKICBleHRlbnNpb25zOiBbYmFzaWNTZXR1cCwgcHl0aG9uKCldLAogIHBhcmVudDogZG9jdW1lbnQuYm9keQp9KQo=).

This also affects `if` and other statements:

```python
if (x
    and y):  # after pressing enter the indent will be deeper than expected.
```

I will open an issue on CodeMirror repo.

**Comment by krassowski** [comment]
Upstream issue: https://github.com/codemirror/dev/issues/1182.

If someone has more time to contribute upstream, the code for indentation is here: https://github.com/codemirror/lang-python/blob/main/src/python.ts

**Comment by mbakker7** [comment]
Thanks for submitting the issue in the right place. 
Not something I have any knowledge about, so unfortunately I cannot help.

**Comment by mbakker7** [comment]
This was quickly fixed in CodeMirror (one word fix): https://github.com/codemirror/lang-python/commit/b9203eec74b8f4cd877b7fbf2a024b7a4b761727
What is the process to get this included in JupyterLab?

**Comment by fcollonval** [comment]
We need to bump `codemirror/lang-python` to the latest version there:

https://github.com/jupyterlab/jupyterlab/blob/f699d32d19e1687bf27e4c83318f50062adb0c5a/packages/codemirror/package.json#L51

Would you be willing to open a PR @mbakker7 ?

Basically, you need to:
- bump the version in the package.json file
- execute jlpm at the project root to update the yarn.lock
- commit both the package.json and yarn.lock

**Comment by mbakker7** [comment]
I can surely give it a try as this sounds doable.
Just not sure what "execute jlpm' means Any hint or link with instructions of how to do that and what that means?

**Comment by krassowski** [comment]
jlpm is our wrapper around yarn, a package manager for JavaScript/Node.js ecosystem. To install it follow https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html (the local development path).

**Comment by FoSuCloud** [comment]
> We need to bump `codemirror/lang-python` to the latest version there:
> 
> https://github.com/jupyterlab/jupyterlab/blob/f699d32d19e1687bf27e4c83318f50062adb0c5a/packages/codemirror/package.json#L51
> 
> Would you be willing to open a PR @mbakker7 ?
> 
> Basically, you need to:
> 
> * bump the version in the package.json file
> * execute jlpm at the project root to update the yarn.lock
> * commit both the package.json and yarn.lock

"bump the version in the package.json file" Does it mean adding '@ codemirror/lang Python' in resolutions: '^ 6.1.2'?

**Comment by mbakker7** [comment]
Latest version of "@codemirror/lang-python" seems to be 6.1..3
Sorry I haven't made a PR yet. Still haven't had time to figure out how to "execute jlpm at the project root to update the yarn.lock". Will try again on Tuesday if nobody beats me to it.

**Comment by FoSuCloud** [comment]
> Latest version of "@codemirror/lang-python" seems to be 6.1..3 Sorry I haven't made a PR yet. Still haven't had time to figure out how to "execute jlpm at the project root to update the yarn.lock". Will try again on Tuesday if nobody beats me to it.

I can try to solve this problem
