### ISSUE TITLE
No module named jupyterlab

### ISSUE THREAD

**Issue by Assassintears** [jupyterlab/jupyterlab#14662]
I upgraded the jupyter lab into version 4.0.2, then I cannot launch jupyter lab and receive the error message like this:
![image](https://github.com/jupyterlab/jupyterlab/assets/18465107/01eff66e-145d-4b0e-932f-8afee635585f)

I list all packages and the jupyter is really installed,
![image](https://github.com/jupyterlab/jupyterlab/assets/18465107/a3f30292-a978-4ed2-a458-7ee0ef377257)

please help me how to fix the problem.

**Comment by JasonWeill** [comment]
@Assassintears Thanks for opening this issue! Have you tried creating a new environment with `conda` and installing JupyterLab 4.0.2 in there? If you are able to launch JupyterLab this way, there may be a problem with your current `conda` environment.

**Comment by JasonWeill** [comment]
@Assassintears Any update after trying the `conda` commands above? Thanks!
