### ISSUE TITLE
File load error issue when opening files in a shared folder

### ISSUE THREAD

**Issue by eliasdabbas** [jupyterlab/jupyterlab#14672]
## Expected behavior

Normal users should be able to edit and view files in the shared folders, but a `File Load Error` is raised by JupyterLab.

## Context

In a TLJH installation ([available here if you want to create an account and check](http://172.104.249.145)), I followed [instructions to create a shared folder](https://tljh.jupyter.org/en/latest/howto/content/share-data.html#option-3-create-a-directory-for-users-to-share-notebooks-and-other-files) for users to publish files in.

A regular user is able to create, edit, and `cat` files, but they cannot be loaded with JupyterLab.

- Operating System and version: Linux Ubuntu 22.10
- Browser and version: Chrome 114 and Firefox 113
- JupyterLab version: 3.6 and 4.0.2

#### Works fine from the command line:
<img width="1048" alt="Screen Shot 2023-06-12 at 5 18 43 PM" src="https://github.com/jupyterlab/jupyterlab/assets/15708966/0ba95419-f796-4bb9-9ff4-502c8803fb83">

#### Double clicking the file raises the issue (no issue with files in other folders)

<img width="1125" alt="Screen Shot 2023-06-12 at 5 18 59 PM" src="https://github.com/jupyterlab/jupyterlab/assets/15708966/16f9a479-f7b9-4065-ba9e-723d6f3eaafc">

#### No issues with classic notebook interface, editing and saving also works

<img width="964" alt="Screen Shot 2023-06-12 at 5 33 46 PM" src="https://github.com/jupyterlab/jupyterlab/assets/15708966/c4f44f22-bfda-4220-9fd5-aa6db53740a2">

<details><summary>Troubleshoot Output</summary>
<pre>
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(143): Could not remove or rename /opt/tljh/user/conda-meta/requests-2.26.0-pyhd8ed1ab_0.json.  Please remove this file manually (you may need to reboot to free file handles)

CondaEnvException: Unable to determine environment

Please re-run this command with one of the following options:

* Provide an environment name via --name or -n
* Re-run this command inside an activated conda environment.

$PATH:
        /opt/tljh/user/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /snap/bin

sys.path:
        /opt/tljh/user/bin
        /opt/tljh/user/lib/python39.zip
        /opt/tljh/user/lib/python3.9
        /opt/tljh/user/lib/python3.9/lib-dynload
        /opt/tljh/user/lib/python3.9/site-packages

sys.executable:
        /opt/tljh/user/bin/python

sys.version:
        3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
        [GCC 9.4.0]

platform.platform():
        Linux-5.19.0-43-generic-x86_64-with-glibc2.36

which -a jupyter:
        /opt/tljh/user/bin/jupyter

pip list:
        Package                   Version
        ------------------------- --------
        advertools                0.13.2
        adviz                     0.0.11
        aiofiles                  22.1.0
        aiosqlite                 0.19.0
        alembic                   1.11.1
        ansi2html                 1.8.0
        anyio                     3.7.0
        argon2-cffi               21.3.0
        argon2-cffi-bindings      21.2.0
        arrow                     1.2.3
        asttokens                 2.2.1
        async-generator           1.10
        async-lru                 2.0.2
        attrs                     23.1.0
        Automat                   22.10.0
        Babel                     2.12.1
        backcall                  0.2.0
        beautifulsoup4            4.12.2
        bleach                    6.0.0
        brotlipy                  0.7.0
        certifi                   2023.5.7
        certipy                   0.1.3
        cffi                      1.14.6
        chardet                   4.0.0
        charset-normalizer        2.0.0
        click                     8.1.3
        colorama                  0.4.4
        comm                      0.1.3
        conda                     4.10.3
        conda-package-handling    1.7.3
        constantly                15.1.0
        contourpy                 1.0.7
        cryptography              3.4.8
        cssselect                 1.2.0
        cycler                    0.11.0
        dash                      2.10.2
        dash-bootstrap-components 1.4.1
        dash-core-components      2.0.0
        dash-html-components      2.0.0
        dash-table                5.0.0
        debugpy                   1.6.7
        decorator                 5.1.1
        defusedxml                0.7.1
        entrypoints               0.4
        exceptiongroup            1.1.1
        executing                 1.2.0
        fastjsonschema            2.17.1
        filelock                  3.12.1
        Flask                     2.2.5
        fonttools                 4.39.4
        fqdn                      1.5.1
        greenlet                  2.0.2
        hyperlink                 21.0.0
        idna                      3.1
        importlib-metadata        6.6.0
        importlib-resources       5.12.0
        incremental               22.10.0
        ipykernel                 6.23.1
        ipython                   8.14.0
        ipython-genutils          0.2.0
        ipywidgets                7.7.5
        isoduration               20.11.0
        itemadapter               0.8.0
        itemloaders               1.1.0
        itsdangerous              2.1.2
        jedi                      0.18.2
        Jinja2                    3.1.2
        jmespath                  1.0.1
        json5                     0.9.14
        jsonpointer               2.3
        jsonschema                4.17.3
        jupyter_client            8.2.0
        jupyter_core              5.3.0
        jupyter-dash              0.4.2
        jupyter-events            0.6.3
        jupyter-lsp               2.2.0
        jupyter-resource-usage    0.6.4
        jupyter_server            2.6.0
        jupyter_server_fileid     0.9.0
        jupyter_server_terminals  0.4.4
        jupyter_server_ydoc       0.8.0
        jupyter-telemetry         0.1.0
        jupyter-ydoc              0.2.4
        jupyterhub                1.5.1
        jupyterlab                4.0.2
        jupyterlab-pygments       0.2.2
        jupyterlab_server         2.22.1
        jupyterlab-widgets        1.1.4
        kaleido                   0.2.1
        kiwisolver                1.4.4
        lxml                      4.9.2
        Mako                      1.2.4
        mamba                     0.16.0
        MarkupSafe                2.1.3
        matplotlib                3.7.1
        matplotlib-inline         0.1.6
        mistune                   2.0.5
        nbclassic                 1.0.0
        nbclient                  0.8.0
        nbconvert                 7.4.0
        nbformat                  5.9.0
        nbgitpuller               1.1.1
        nest-asyncio              1.5.6
        notebook                  6.5.4
        notebook_shim             0.2.3
        nteract-on-jupyter        2.1.3
        numpy                     1.24.3
        oauthlib                  3.2.2
        overrides                 7.3.1
        packaging                 23.1
        pamela                    1.1.0
        pandas                    2.0.2
        pandocfilters             1.5.0
        parsel                    1.8.1
        parso                     0.8.3
        pexpect                   4.8.0
        pickleshare               0.7.5
        Pillow                    9.5.0
        pip                       21.3
        platformdirs              3.5.3
        plotly                    5.15.0
        prometheus-client         0.17.0
        prompt-toolkit            3.0.38
        Protego                   0.2.1
        psutil                    5.9.5
        ptyprocess                0.7.0
        pure-eval                 0.2.2
        pyarrow                   12.0.0
        pyasn1                    0.5.0
        pyasn1-modules            0.3.0
        pycosat                   0.6.3
        pycparser                 2.20
        PyDispatcher              2.0.7
        Pygments                  2.15.1
        pyOpenSSL                 21.0.0
        pyparsing                 3.0.9
        pyrsistent                0.19.3
        PySocks                   1.7.1
        python-dateutil           2.8.2
        python-json-logger        2.0.7
        pytz                      2023.3
        PyYAML                    6.0
        pyzmq                     25.1.0
        queuelib                  1.6.2
        requests                  2.31.0
        requests-file             1.5.1
        requests-oauthlib         1.3.1
        retrying                  1.3.4
        rfc3339-validator         0.1.4
        rfc3986-validator         0.1.1
        ruamel.yaml               0.17.31
        ruamel.yaml.clib          0.2.7
        ruamel-yaml-conda         0.15.80
        Scrapy                    2.9.0
        Send2Trash                1.8.2
        service-identity          21.1.0
        setuptools                58.2.0
        six                       1.16.0
        sniffio                   1.3.0
        soupsieve                 2.4.1
        SQLAlchemy                1.4.48
        stack-data                0.6.2
        tenacity                  8.2.2
        terminado                 0.17.1
        tinycss2                  1.2.1
        tldextract                3.4.4
        tomli                     2.0.1
        tornado                   6.3.2
        tqdm                      4.62.3
        traitlets                 5.9.0
        Twisted                   22.10.0
        twython                   3.9.1
        typing_extensions         4.6.3
        tzdata                    2023.3
        uri-template              1.2.0
        urllib3                   1.26.7
        w3lib                     2.1.1
        wcwidth                   0.2.6
        webcolors                 1.13
        webencodings              0.5.1
        websocket-client          1.5.3
        Werkzeug                  2.2.3
        wheel                     0.37.0
        widgetsnbextension        3.6.4
        y-py                      0.5.9
        ypy-websocket             0.8.2
        zipp                      3.15.0
        zope.interface            6.0

conda list:
        # packages in environment at /opt/tljh/user:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       1_gnu    conda-forge
        advertools                0.13.2                   pypi_0    pypi
        adviz                     0.0.11                   pypi_0    pypi
        aiofiles                  22.1.0                   pypi_0    pypi
        aiosqlite                 0.19.0                   pypi_0    pypi
        alembic                   1.11.1                   pypi_0    pypi
        ansi2html                 1.8.0                    pypi_0    pypi
        anyio                     3.7.0                    pypi_0    pypi
        argon2-cffi               21.3.0                   pypi_0    pypi
        argon2-cffi-bindings      21.2.0                   pypi_0    pypi
        arrow                     1.2.3                    pypi_0    pypi
        asttokens                 2.2.1                    pypi_0    pypi
        async-generator           1.10                     pypi_0    pypi
        async-lru                 2.0.2                    pypi_0    pypi
        attrs                     23.1.0                   pypi_0    pypi
        automat                   22.10.0                  pypi_0    pypi
        babel                     2.12.1                   pypi_0    pypi
        backcall                  0.2.0                    pypi_0    pypi
        beautifulsoup4            4.12.2                   pypi_0    pypi
        bleach                    6.0.0                    pypi_0    pypi
        brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
        bzip2                     1.0.8                h7f98852_4    conda-forge
        c-ares                    1.17.2               h7f98852_0    conda-forge
        ca-certificates           2023.5.7             hbcca054_0    conda-forge
        certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
        certipy                   0.1.3                    pypi_0    pypi
        cffi                      1.14.6           py39h4bc2ebd_1    conda-forge
        chardet                   4.0.0            py39hf3d152e_1    conda-forge
        charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
        click                     8.1.3                    pypi_0    pypi
        colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
        comm                      0.1.3                    pypi_0    pypi
        conda                     4.10.3           py39hf3d152e_2    conda-forge
        conda-package-handling    1.7.3            py39h3811e60_0    conda-forge
        constantly                15.1.0                   pypi_0    pypi
        contourpy                 1.0.7                    pypi_0    pypi
        cryptography              3.4.8            py39hbca0aa6_0    conda-forge
        cssselect                 1.2.0                    pypi_0    pypi
        cycler                    0.11.0                   pypi_0    pypi
        dash                      2.10.2                   pypi_0    pypi
        dash-bootstrap-components 1.4.1                    pypi_0    pypi
        dash-core-components      2.0.0                    pypi_0    pypi
        dash-html-components      2.0.0                    pypi_0    pypi
        dash-table                5.0.0                    pypi_0    pypi
        debugpy                   1.6.7                    pypi_0    pypi
        decorator                 5.1.1                    pypi_0    pypi
        defusedxml                0.7.1                    pypi_0    pypi
        entrypoints               0.4                      pypi_0    pypi
        exceptiongroup            1.1.1                    pypi_0    pypi
        executing                 1.2.0                    pypi_0    pypi
        fastjsonschema            2.17.1                   pypi_0    pypi
        filelock                  3.12.1                   pypi_0    pypi
        flask                     2.2.5                    pypi_0    pypi
        fonttools                 4.39.4                   pypi_0    pypi
        fqdn                      1.5.1                    pypi_0    pypi
        greenlet                  2.0.2                    pypi_0    pypi
        hyperlink                 21.0.0                   pypi_0    pypi
        icu                       68.1                 h58526e2_0    conda-forge
        idna                      3.1                pyhd3deb0d_0    conda-forge
        importlib-metadata        6.6.0                    pypi_0    pypi
        importlib-resources       5.12.0                   pypi_0    pypi
        incremental               22.10.0                  pypi_0    pypi
        ipykernel                 6.23.1                   pypi_0    pypi
        ipython                   8.14.0                   pypi_0    pypi
        ipython-genutils          0.2.0                    pypi_0    pypi
        ipywidgets                7.7.5                    pypi_0    pypi
        isoduration               20.11.0                  pypi_0    pypi
        itemadapter               0.8.0                    pypi_0    pypi
        itemloaders               1.1.0                    pypi_0    pypi
        itsdangerous              2.1.2                    pypi_0    pypi
        jedi                      0.18.2                   pypi_0    pypi
        jinja2                    3.1.2                    pypi_0    pypi
        jmespath                  1.0.1                    pypi_0    pypi
        json5                     0.9.14                   pypi_0    pypi
        jsonpointer               2.3                      pypi_0    pypi
        jsonschema                4.17.3                   pypi_0    pypi
        jupyter-client            8.2.0                    pypi_0    pypi
        jupyter-core              5.3.0                    pypi_0    pypi
        jupyter-dash              0.4.2                    pypi_0    pypi
        jupyter-events            0.6.3                    pypi_0    pypi
        jupyter-lsp               2.2.0                    pypi_0    pypi
        jupyter-resource-usage    0.6.4                    pypi_0    pypi
        jupyter-server            2.6.0                    pypi_0    pypi
        jupyter-server-fileid     0.9.0                    pypi_0    pypi
        jupyter-server-terminals  0.4.4                    pypi_0    pypi
        jupyter-server-ydoc       0.8.0                    pypi_0    pypi
        jupyter-telemetry         0.1.0                    pypi_0    pypi
        jupyter-ydoc              0.2.4                    pypi_0    pypi
        jupyterhub                1.5.1                    pypi_0    pypi
        jupyterlab                4.0.2                    pypi_0    pypi
        jupyterlab-pygments       0.2.2                    pypi_0    pypi
        jupyterlab-server         2.22.1                   pypi_0    pypi
        jupyterlab-widgets        1.1.4                    pypi_0    pypi
        kaleido                   0.2.1                    pypi_0    pypi
        kiwisolver                1.4.4                    pypi_0    pypi
        krb5                      1.19.2               hcc1bbae_2    conda-forge
        ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
        libarchive                3.5.2                hccf745f_1    conda-forge
        libcurl                   7.79.1               h2574ce0_1    conda-forge
        libedit                   3.1.20191231         he28a2e2_2    conda-forge
        libev                     4.33                 h516909a_1    conda-forge
        libffi                    3.4.2                h9c3ff4c_4    conda-forge
        libgcc-ng                 13.1.0               he5830b7_0    conda-forge
        libgomp                   13.1.0               he5830b7_0    conda-forge
        libiconv                  1.16                 h516909a_0    conda-forge
        libnghttp2                1.43.0               h812cca2_1    conda-forge
        libsolv                   0.7.19               h780b84a_5    conda-forge
        libssh2                   1.10.0               ha56f1ee_2    conda-forge
        libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
        libxml2                   2.9.12               h72842e0_0    conda-forge
        libzlib                   1.2.11            h36c2ea0_1013    conda-forge
        lxml                      4.9.2                    pypi_0    pypi
        lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
        lzo                       2.10              h516909a_1000    conda-forge
        mako                      1.2.4                    pypi_0    pypi
        mamba                     0.16.0           py39h951de11_0    conda-forge
        markupsafe                2.1.3                    pypi_0    pypi
        matplotlib                3.7.1                    pypi_0    pypi
        matplotlib-inline         0.1.6                    pypi_0    pypi
        mistune                   2.0.5                    pypi_0    pypi
        nbclassic                 1.0.0                    pypi_0    pypi
        nbclient                  0.8.0                    pypi_0    pypi
        nbconvert                 7.4.0                    pypi_0    pypi
        nbformat                  5.9.0                    pypi_0    pypi
        nbgitpuller               1.1.1                    pypi_0    pypi
        ncurses                   6.2                  h58526e2_4    conda-forge
        nest-asyncio              1.5.6                    pypi_0    pypi
        notebook                  6.5.4                    pypi_0    pypi
        notebook-shim             0.2.3                    pypi_0    pypi
        nteract-on-jupyter        2.1.3                    pypi_0    pypi
        numpy                     1.24.3                   pypi_0    pypi
        oauthlib                  3.2.2                    pypi_0    pypi
        openssl                   1.1.1u               hd590300_0    conda-forge
        overrides                 7.3.1                    pypi_0    pypi
        packaging                 23.1                     pypi_0    pypi
        pamela                    1.1.0                    pypi_0    pypi
        pandas                    2.0.2                    pypi_0    pypi
        pandocfilters             1.5.0                    pypi_0    pypi
        parsel                    1.8.1                    pypi_0    pypi
        parso                     0.8.3                    pypi_0    pypi
        pexpect                   4.8.0                    pypi_0    pypi
        pickleshare               0.7.5                    pypi_0    pypi
        pillow                    9.5.0                    pypi_0    pypi
        pip                       21.3               pyhd8ed1ab_0    conda-forge
        platformdirs              3.5.3                    pypi_0    pypi
        plotly                    5.15.0                   pypi_0    pypi
        prometheus-client         0.17.0                   pypi_0    pypi
        prompt-toolkit            3.0.38                   pypi_0    pypi
        protego                   0.2.1                    pypi_0    pypi
        psutil                    5.9.5                    pypi_0    pypi
        ptyprocess                0.7.0                    pypi_0    pypi
        pure-eval                 0.2.2                    pypi_0    pypi
        pyarrow                   12.0.0                   pypi_0    pypi
        pyasn1                    0.5.0                    pypi_0    pypi
        pyasn1-modules            0.3.0                    pypi_0    pypi
        pycosat                   0.6.3           py39h3811e60_1006    conda-forge
        pycparser                 2.20               pyh9f0ad1d_2    conda-forge
        pydispatcher              2.0.7                    pypi_0    pypi
        pygments                  2.15.1                   pypi_0    pypi
        pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
        pyparsing                 3.0.9                    pypi_0    pypi
        pyrsistent                0.19.3                   pypi_0    pypi
        pysocks                   1.7.1            py39hf3d152e_3    conda-forge
        python                    3.9.7           hb7a2778_3_cpython    conda-forge
        python-dateutil           2.8.2                    pypi_0    pypi
        python-json-logger        2.0.7                    pypi_0    pypi
        python_abi                3.9                      2_cp39    conda-forge
        pytz                      2023.3                   pypi_0    pypi
        pyyaml                    6.0                      pypi_0    pypi
        pyzmq                     25.1.0                   pypi_0    pypi
        queuelib                  1.6.2                    pypi_0    pypi
        readline                  8.1                  h46c0cb4_0    conda-forge
        reproc                    14.2.3               h7f98852_0    conda-forge
        reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
        requests                  2.31.0                   pypi_0    pypi
        requests-file             1.5.1                    pypi_0    pypi
        requests-oauthlib         1.3.1                    pypi_0    pypi
        retrying                  1.3.4                    pypi_0    pypi
        rfc3339-validator         0.1.4                    pypi_0    pypi
        rfc3986-validator         0.1.1                    pypi_0    pypi
        ruamel-yaml               0.17.31                  pypi_0    pypi
        ruamel-yaml-clib          0.2.7                    pypi_0    pypi
        ruamel_yaml               0.15.80         py39h3811e60_1004    conda-forge
        scrapy                    2.9.0                    pypi_0    pypi
        send2trash                1.8.2                    pypi_0    pypi
        service-identity          21.1.0                   pypi_0    pypi
        setuptools                58.2.0           py39hf3d152e_0    conda-forge
        six                       1.16.0             pyh6c4a22f_0    conda-forge
        sniffio                   1.3.0                    pypi_0    pypi
        soupsieve                 2.4.1                    pypi_0    pypi
        sqlalchemy                1.4.48                   pypi_0    pypi
        sqlite                    3.36.0               h9cd32fc_2    conda-forge
        stack-data                0.6.2                    pypi_0    pypi
        tenacity                  8.2.2                    pypi_0    pypi
        terminado                 0.17.1                   pypi_0    pypi
        tinycss2                  1.2.1                    pypi_0    pypi
        tk                        8.6.11               h27826a3_1    conda-forge
        tldextract                3.4.4                    pypi_0    pypi
        tomli                     2.0.1                    pypi_0    pypi
        tornado                   6.3.2                    pypi_0    pypi
        tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
        traitlets                 5.9.0                    pypi_0    pypi
        twisted                   22.10.0                  pypi_0    pypi
        twython                   3.9.1                    pypi_0    pypi
        typing-extensions         4.6.3                    pypi_0    pypi
        tzdata                    2023.3                   pypi_0    pypi
        uri-template              1.2.0                    pypi_0    pypi
        urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
        w3lib                     2.1.1                    pypi_0    pypi
        wcwidth                   0.2.6                    pypi_0    pypi
        webcolors                 1.13                     pypi_0    pypi
        webencodings              0.5.1                    pypi_0    pypi
        websocket-client          1.5.3                    pypi_0    pypi
        werkzeug                  2.2.3                    pypi_0    pypi
        wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
        widgetsnbextension        3.6.4                    pypi_0    pypi
        xz                        5.2.5                h516909a_1    conda-forge
        y-py                      0.5.9                    pypi_0    pypi
        yaml                      0.2.5                h516909a_0    conda-forge
        ypy-websocket             0.8.2                    pypi_0    pypi
        zipp                      3.15.0                   pypi_0    pypi
        zlib                      1.2.11            h36c2ea0_1013    conda-forge
        zope-interface            6.0                      pypi_0    pypi
        zstd                      1.5.0                ha95c52a_0    conda-forge

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>

D 2023-06-12 15:54:57.698 ServerApp] Searching ['/home/jupyter-elias/.jupyter', '/home/jupyter-elias/.local/etc/jupyter', '/opt/tljh/user/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2023-06-12 15:54:57.698 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2023-06-12 15:54:57.698 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2023-06-12 15:54:57.698 ServerApp] Looking for jupyter_config in /opt/tljh/user/etc/jupyter
[D 2023-06-12 15:54:57.698 ServerApp] Looking for jupyter_config in /home/jupyter-elias/.local/etc/jupyter
[D 2023-06-12 15:54:57.698 ServerApp] Looking for jupyter_config in /home/jupyter-elias/.jupyter
[D 2023-06-12 15:54:57.699 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2023-06-12 15:54:57.699 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2023-06-12 15:54:57.699 ServerApp] Looking for jupyter_server_config in /opt/tljh/user/etc/jupyter
[D 2023-06-12 15:54:57.699 ServerApp] Looking for jupyter_server_config in /home/jupyter-elias/.local/etc/jupyter
[D 2023-06-12 15:54:57.699 ServerApp] Looking for jupyter_server_config in /home/jupyter-elias/.jupyter
[D 2023-06-12 15:54:57.701 ServerApp] Paths used for configuration of jupyter_server_config: 
        /etc/jupyter/jupyter_server_config.json
[D 2023-06-12 15:54:57.701 ServerApp] Paths used for configuration of jupyter_server_config: 
        /usr/local/etc/jupyter/jupyter_server_config.json
[D 2023-06-12 15:54:57.701 ServerApp] Paths used for configuration of jupyter_server_config: 
        /opt/tljh/user/etc/jupyter/jupyter_server_config.d/jupyter-lsp-jupyter-server.json
        /opt/tljh/user/etc/jupyter/jupyter_server_config.d/jupyter_resource_usage.json
        /opt/tljh/user/etc/jupyter/jupyter_server_config.d/jupyter_server_fileid.json
        /opt/tljh/user/etc/jupyter/jupyter_server_config.d/jupyter_server_terminals.json
        /opt/tljh/user/etc/jupyter/jupyter_server_config.d/jupyter_server_ydoc.json
        /opt/tljh/user/etc/jupyter/jupyter_server_config.d/jupyterlab.json
        /opt/tljh/user/etc/jupyter/jupyter_server_config.d/nbclassic.json
        /opt/tljh/user/etc/jupyter/jupyter_server_config.d/nbgitpuller.json
        /opt/tljh/user/etc/jupyter/jupyter_server_config.d/notebook_shim.json
        /opt/tljh/user/etc/jupyter/jupyter_server_config.json
[D 2023-06-12 15:54:57.702 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/jupyter-elias/.local/etc/jupyter/jupyter_server_config.json
[D 2023-06-12 15:54:57.702 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/jupyter-elias/.jupyter/jupyter_server_config.json
[I 2023-06-12 15:54:57.706 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-06-12 15:54:57.714 ServerApp] Package jupyter_lsp took 0.0079s to import
[W 2023-06-12 15:54:57.714 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.

</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
Thanks for filing this issue @eliasdabbas ! If you have your browser's console open, and you try to open the shared file, do you see any errors or other messages in the console when the error dialog pops up in the browser?

**Comment by eliasdabbas** [comment]
Thanks @JasonWeill !

Yes, it seems there is an error immediately when I open the file browser, as well as after I click to create a new file: 


### Before
<img width="776" alt="Screen Shot 2023-06-13 at 7 30 58 PM" src="https://github.com/jupyterlab/jupyterlab/assets/15708966/de13bcf3-0e78-42f0-bdba-14a484bf4f94">

### After

<img width="958" alt="Screen Shot 2023-06-13 at 7 34 25 PM" src="https://github.com/jupyterlab/jupyterlab/assets/15708966/bc616aee-fbf1-4858-a10f-2f452393bb6f">

"permission denied", yet, I'm able to create a file through the interface, but can't access it.


I also noticed a strangely high number of 503 status codes in the logs: 

```bash
sudo journalctl -u jupyterhub | egrep '[0-9]{3} [A-Z]+ ' -o | sort | uniq -c | sort -n
```
<img width="175" alt="Screen Shot 2023-06-13 at 7 39 15 PM" src="https://github.com/jupyterlab/jupyterlab/assets/15708966/6f2eb835-5a81-45d3-90c6-c3e175e21148">


#### Top error URLs (query params removed):

```bash
sudo journalctl -u jupyterhub | egrep '503' | egrep '/hub/[^?]+'  -o | sort | uniq -c | sort -n 
```
<img width="659" alt="Screen Shot 2023-06-13 at 7 43 08 PM" src="https://github.com/jupyterlab/jupyterlab/assets/15708966/d77cd42e-d3f9-48c9-9533-1554f378d007">

Hope this helps, happy to provide any further information if needed. 

Thanks!

**Comment by JasonWeill** [comment]
Looks like the error comes in when JupyterLab tries to create a checkpoint for autosaving.

I don't believe you can disable checkpointing, but you can change where checkpoints get saved; see [this StackOverflow question](https://stackoverflow.com/questions/51887758/is-there-a-way-to-disable-saving-to-checkpoints-for-jupyter-notebooks) for more info.

**Comment by eliasdabbas** [comment]
That solves it!

Not by changing the location, but by allowing users to edit this folder.

Using the same instructions for creating the `/shared/` folder, I also allowed users to edit the `/shared/.ipynb_checkpoints/` folder. 

Full code for anyone else having the same issue:

```bash
$ sudo chown  root:jupyterhub-users /srv/shared/.ipynb_checkpoints/
$ sudo chmod 777 /srv/shared/.ipynb_checkpoints/
$ sudo chmod g+s /srv/shared/.ipynb_checkpoints/
$ sudo ln -s /srv/scratch /etc/skel/shared/.ipynb_checkpoints/
```

**Comment by JasonWeill** [comment]
Glad I could help!

As this isn't a bug in JupyterLab, I'm going to close this issue out for now. Please reopen or open a new issue if you find any other issues.
