### ISSUE TITLE
Scroll header cell into top of view upon TOC click

### ISSUE THREAD

**Issue by pinealan** [jupyterlab/jupyterlab#14684]
The old onClick behaviour of header items in the TOC extension was to scroll the header element into the top of the view. In the recent 4.0 release (amazing update by the way), where the TOC extension has been redone, it now scrolls the element into the center of the viewport. Personally I find having the element in the middle to be an odd UX, though I do suppose there may be others who perfer the new behaviour.

I believe the only required code change would be to set on `block: 'center'` at [`packages/notebook/src/toc.ts`](https://github.com/jupyterlab/jupyterlab/blob/f699d32d19e1687bf27e4c83318f50062adb0c5a/packages/notebook/src/toc.ts#L531) to `block: 'start'`. The best of both worlds would be for this to be configurable though.

**Comment by JasonWeill** [comment]
Another 4.0 TOC issue: #14591

**Comment by krassowski** [comment]
It is worse than described originally. When scrolling down to a heading after clicking in ToC, it is not even centred but barely shown at the bottom. When scrolling up it is centred. Quite bad UX IMO.
