### ISSUE TITLE
Menu "Show line number" does not show its corresponding shortcut

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#14689]
## Description

Though the shortcut (`Shift L`) works.

## Reproduce

Latest JupyterLab 4 release or JupyterLab `main` on 1971abfe473a386244efee810ccd286de08ec655

![image](https://github.com/jupyter/notebook/assets/591645/c5049c4e-55e4-4723-be8d-0a79afa7f3db)

## Expected behavior

It should show the shortcut in the menu entry.

## Context

This was originally reported in https://github.com/jupyter/notebook/issues/6824 by @Carreau

**Comment by andrewfulton9** [comment]
It looks like this issue has been solved. Can it be closed?

**Comment by krassowski** [comment]
Closing as per above.
