### ISSUE TITLE
How to enable default notebook toolbar with all default buttons in the notebook 4.0.0

### ISSUE THREAD

**Issue by ShilpaShivaji** [jupyterlab/jupyterlab#14695]
As now in 4.0.0 default notebook toolbar is empty, how to get all the default buttons in the toolbar?
https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#deprecated-code-removed

We are using notebook example ( https://github.com/jupyterlab/jupyterlab/tree/main/examples/notebook ) in our application.
Is there any option to get the default toolbar with all the default buttons ?

**Comment by JasonWeill** [comment]
In JupyterLab 4, we changed the notebook toolbar from hardcoded to schema-based. We might need to improve our documentation to better indicate how to add buttons to this toolbar. Are there any particular buttons that you need for your use case?

Adding @fcollonval , who may have more context about this.

**Comment by ShilpaShivaji** [comment]
@JasonWeill , We need all the buttons which was there by default earlier.
Save, add, copy, paste,run,interrupt the kernel, restart the kernel,select the cell type,kernel switch,etc......

[](![image](https://github.com/jupyterlab/jupyterlab/assets/41981923/f9d462b8-bd00-41e9-b127-bf2db9571544)
)

**Comment by fcollonval** [comment]
@ShilpaShivaji you can find a solution in #14726
