### ISSUE TITLE
How to get `WidgetLSPAdapter`/`VirtualDocument` from CodeMirror event?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14710]
## Description

In original implementation of LSP the features were receiving sufficient context connecting `CellCodeEditor` to the `WidgetAdapter`/`VirtualDocument` via `EditorAdapter`. The version merged into the core does **not** have the concepts of `EditorIntegration` nor `EditorAdapter` thus:
- features have to assume the editor is CodeMirror6 (cannot provide integration for other editors) - this was intentional, though maybe short-sighted
- when an event is triggered in a code cell editor there is no obvious way to associate it with the corresponding `WidgetLSPAdapter` nor `VirtualDocument`; this prevents reimplementation of many LSP features, with the solutions varying from error-prone to duplicating the adapter pattern which is not great maintenance-wise.

I would love to get some opinions on the preferred solution among the few proposed below, or learn about other solutions you may think of.

### Previous

```mermaid
flowchart TD
    B
    B[LSP feature, e.g. highlights] -->|provides EditorIntegration factory| C[WidgetAdapter]
    B -->|provides capabilities information| CON[ConnectionManager]
    C --> |manages| MA[Cell <=> VirtualDocument]
    C -->|for each cell creates| EI[EditorAdapter with one or more EditorIntegration]
    EI -->|registers handlers on| D[CodeMirror cell editor]
    D -->|user event, e.g. moves cursor| E[Event]
    EI --> |knows about WidgetAdapter| H[EventHandler]
    E --> |does not know about WidgetAdapter| H
    H --> X(clears highlight on other cells using adapter)
    H --> Y(adds highlight on current cell)  
```

<details>

```typescript
class WidgetAdapter {
  connect_adapter(
    virtual_document: VirtualDocument,
    connection: LSPConnection,
    features: IFeature[] | null = null
  ): EditorAdapter<any> {
    let adapter = this.create_adapter(virtual_document, connection, features);
    this.adapters.set(virtual_document.id_path, adapter);
    return adapter;
  }
  private create_adapter(
    virtual_document: VirtualDocument,
    connection: LSPConnection,
    features: IFeature[]
  ): EditorAdapter<IVirtualEditor<IEditor>> {
    let adapter_features = new Array<
      IFeatureEditorIntegration<IVirtualEditor<IEditor>>
    >();

    for (let feature of features) {
      let featureEditorIntegrationConstructor =
        feature.editorIntegrationFactory.get(this.virtual_editor.editor_name)!;
      let integration = new featureEditorIntegrationConstructor({
        feature: feature,
        virtual_editor: this.virtual_editor,
        virtual_document: virtual_document,
        connection: connection,
        adapter: this,
      });
      adapter_features.push(integration);
    }

    let adapter = new EditorAdapter(
      this.virtual_editor,
      virtual_document,
      adapter_features
    );
    connection.sendOpenWhenReady(virtual_document.document_info);
    return adapter;
  }
}
```

</details>

### Current

```mermaid
flowchart TD
    C[WidgetAdapter] --> |manages| MA[Cell <=> VirtualDocument]
    C --> |registers on| CON
    B -->|registers handlers on CodeMirror factory| D[CodeMirror cell editor]
    B[LSP feature, e.g. highlights] -->|provides LSP capabilities information| CON[ConnectionManager]
    B --> |does NOT know about WidgetAdapter| H[EventHandler]
    D -->|user event, e.g. moves cursor| E[Event]
    E --> |does NOT know about WidgetAdapter| H
    H --> X(cannot clears highlight on other cells using adapter)
    H --> Y(adds highlight on current cell)
  ```

<details>

https://github.com/jupyterlab/jupyterlab/blob/4a267dfc1e3241ed936da6c60f80d11422ab1e55/packages/lsp/src/connection_manager.ts#L207-L218

</details>

The reason it worked for completer which was the feature demonstrated when merging into core is that completer has its own bindings for file editor and notebook. Doing this for each feature will be prohibitive maintenance-wise and is currently impossible as explained in *Do not register event handlers on CodeMirror level* section.

### "Just query by path, this is the new API"

This does not work: we do not know the path for the current editor.

```mermaid
flowchart TD
    C[WidgetAdapter] --> |manages| MA[Cell <=> VirtualDocument]
    B -->|registers handlers on CodeMirror factory| D[CodeMirror cell editor]
    B[LSP feature, e.g. highlights] -->|provides LSP capabilities information| CON[ConnectionManager]
    B --> |does NOT know about WidgetAdapter| H[EventHandler]
    D -->|user event, e.g. moves cursor| E[Event]
    E --> |does NOT know about WidgetAdapter| H
    C --> |registers on| CON
    CON --> FA
    H --> |Problem: path not known| FA["adapter = connectionManager.adapters.get(path)"]
```

### "Just find the adapter by current widget"

This does not work:
- in multi-pane layout when multiple features are active in background (but only one widget is current)
- when user switches current widget we would get race conditions

```mermaid
flowchart TD
    C[WidgetAdapter] --> |manages| MA[Cell <=> VirtualDocument]
    B -->|registers handlers on CodeMirror factory| D[CodeMirror cell editor]
    B[LSP feature, e.g. highlights] -->|provides LSP capabilities information| CON[ConnectionManager]
    B --> |does NOT know about WidgetAdapter| H[EventHandler]
    D -->|user event, e.g. moves cursor| E[Event]
    E --> |does NOT know about WidgetAdapter| H
    C --> |registers on| CON
    CON --> FA
    H --> FA["adapter = findAdapter(Shell.currentWidget, connectionManager.adapters)"]
    FA --> Ops[clears WRONG editors if user switched widgets in the meantime]
```

### "Do not register event handlers on CodeMirror level"

Indeed, if we register event handlers going top-down: on each cell and each file editor, we do know the path (hooray). The problems are:
- A) each feature needs to know about notebook and editor leading to a lot of boilerplate and maintenance burden
- B) AFAIK there is no API to register CodeMirror handlers on Notebook/Editor level (modify their editor factory) at this point (there is either `injectExtension` which happens after factory was called (so features would need to call it on each cell/keep track of every cell), or `editorExtensionRegistry.addExtension` which is global)

```mermaid
flowchart TD
    B[LSP feature, e.g. highlights] -->|provides LSP capabilities information| CON[ConnectionManager]
    C[WidgetAdapter] --> |manages| MA[Cell <=> VirtualDocument]
    EditorTracker --> EditorAdapter
    NotebookTracker --> EditorAdapter
    EditorAdapter --> CellCreatedEvent
    CellCreatedEvent --> |handler knows about WidgetAdapter| H[EventHandler]
    B -->|"implements (problem A)"| EditorAdapter
    CellCreatedEvent -->|"registers handlers on cell CodeMirror (problem B)"| D[CodeMirror cell editor]
    D -->|user event, e.g. moves cursor| E[Event]
    E --> |event does NOT know about widget| H
    C --> |registers on| CON
    CON --> WA
    H --> |knows about widget| WA["adapter = findAdapter(connectionManager.adapters, widget)"]
```

### "Maintain a (WeakRef)Map from CM editor to WidgetAdapter"

This would work but requires implementation in core: each `WidgetAdapter` should add to the map when they become aware of new editor instance. The question is where would the editor ⇒ adapter mapping reside? 

```mermaid
flowchart TD
    C[WidgetAdapter] --> |manages| MA[Cell <=> VirtualDocument]
    C --> |on cell creation update| MAP["mapping = Map(CodeMirror, Adapter)"]
    B -->|registers handlers on CodeMirror factory| D[CodeMirror cell editor]
    B[LSP feature, e.g. highlights] -->|provides LSP capabilities information| CON[ConnectionManager]
    B --> |does NOT know about WidgetAdapter| H[EventHandler]
    D -->|user event, e.g. moves cursor| E[Event]
    E --> |does NOT know about WidgetAdapter| H
    C --> |registers on| CON
    CON --> FA
    H --> |knows emitter editor| FA["adapter = mapping.get(editor)"]
```

## Context

- JupyterLab version: 4.0.2

**Comment by krassowski** [comment]
One clean way to implement the last solution (WeakRefMap) would be having a signal emitted each time a `DocumentWidget` calls a `codeEditorFactory`. This it would not require using trackers which add substantial boilerplate and lots of spurious logic.

**Comment by krassowski** [comment]
Another useful thing is the options passed to `addExtension` factory; these currently provide editor `model` which is what enables `ybinding` to work. A "simple" solution would be to pass optional `documentWidget` in the options too. This would enable finding the correct adapter. However, exposing the widget in options breaks separation of concerns. Maybe we should have a `WeakRefMap` from model to adapters?

```ts
editorExtensionRegistry.addExtension({
  name: 'lsp:feature',
  factory: (options) => {
    adapter = connectionManager.adapterByModel.get(options.model);
  }
)
```

**Comment by krassowski** [comment]
I am experimenting with the approach described in my last comment (`adapterByModel`) while porting the LSP extension for lab 4.0 and will report back on whether it is good or not.

**Comment by krassowski** [comment]
Note to self: it is impossible to provide a working subclass `DocumentConnectionManager` to test it out in extension because `solveUri` method from namespace depends on `Private` and `@jupyterlab/lsp` does not get deduplicated for some reason with `jupyterlab.sharedPackages`. This leads to:

```ts
TypeError: Cannot read properties of undefined (reading 'getMatchingServers')
    at e.solveUris (connection_manager.ts:560:15)
    at get uri [as uri] (document.ts:132:44)
    at L._sendChange (jlab_core.f68a597bc4700114bad4.js?v=f68a597bc4700114bad4:1:882335)
    at L.sendFullTextChange (jlab_core.f68a597bc4700114bad4.js?v=f68a597bc4700114bad4:1:879862)
```

**Comment by fcollonval** [comment]
Hey @krassowski we discuss about this.

Some preliminary considerations of our discussions:
- CodeMirror extension: [registering extensions](https://github.com/jupyterlab/jupyterlab/blob/8cd09882635c7407dd56fd016b905796d89d1b79/packages/codemirror/src/extension.ts#L403) through factory in `IEditorExtensionFactory` was designed for CodeMirror extension without side effect at the document level. So I would recommend using of [`injectExtension`](https://github.com/jupyterlab/jupyterlab/blob/8cd09882635c7407dd56fd016b905796d89d1b79/packages/codemirror/src/editor.ts#L230-L230).
- WidgetAdapter / Feature / Editor relationship: the _previous_ architecture in which _EditorAdapter_ are part of the `WidgetLSPAdapter` is better from an architecture point of view.
- the current debugger as a similar pattern to the _previous_ architecture using [EditorHandler](https://github.com/jupyterlab/jupyterlab/blob/8cd09882635c7407dd56fd016b905796d89d1b79/packages/debugger/src/handlers/editor.ts#L48). It is responsible to [add CodeMirror extensions](https://github.com/jupyterlab/jupyterlab/blob/8cd09882635c7407dd56fd016b905796d89d1b79/packages/debugger/src/handlers/editor.ts#L186). These editor handlers are used in document handler (// with `WidgetLSPAdapter`) like: [NotebookHandler](https://github.com/jupyterlab/jupyterlab/blob/8cd09882635c7407dd56fd016b905796d89d1b79/packages/debugger/src/handlers/notebook.ts#L19).

So what I would like to propose is to generalize the debugger code to restore the _EditorAdapter_. The features themself will have to provide a CodeMirror extension factory to be handled by those adapters. This will imply keeping some interface like `IFeatureEditorIntegration` (with adaptation for CM6).

What do you think?
