### ISSUE TITLE
All comm messages contain empty DataView in buffers

### ISSUE THREAD

**Issue by philippjfr** [jupyterlab/jupyterlab#14720]
Since https://github.com/jupyterlab/jupyterlab/pull/11841 all Comm messages that are received inside JupyterLab seem to have an empty `DataView` appended to the `buffers`:

<img width="1330" alt="Screen Shot 2023-06-20 at 09 59 12" src="https://github.com/jupyterlab/jupyterlab/assets/1550771/e0d4a2f9-d901-47e0-9d90-37dd5f3a387f">

Sadly my minimal example isn't so minimal and relies on our `pyviz_comms` library to create a proxy for the `CommManager`:

```python
import uuid

from pyviz_comms import JupyterCommManager

class BidirectionalComm:

    manager = JupyterCommManager()
    
    _EXEC_MIME_TYPE = 'application/vnd.holoviews_exec.v0+json'
    
    _loaded = False

    def __init__(self, msg_handler=None):
        self._received = []
        self._uuid = uuid.uuid4().hex
        if not self._loaded:
            # Initialize the window.PyViz.comm_manager
            display({'application/javascript': self.manager.js_manager}, raw=True)
            BidirectionalComm._loaded = True
            
        # Initialize the server and client comms
        # server: Sends messages Python -> JS
        # client: Sends messages JS -> Python (and then receives ACK message when server completes processing)
        self._server_comm = self.manager.get_server_comm()
        self._client_comm = self.manager.get_client_comm(
            on_msg=msg_handler
        )
        
    def send(self, msg, metadata=None, buffers=[]):
        """
        Sends message to JS including metadata and bytes buffers
        """
        self._server_comm.send(msg)
    
    def _repr_mimebundle_(self, include=None, exclude=None):
        """
        Basic example of connecting to comm_manager, rendering received output and sending button events to Python. 
        """
        html = f"""
        <script>
        window.PyViz.comm_manager.register_target(
            {self._uuid!r}, {self._server_comm.id!r}, (msg) => {{
              console.log(msg)
              document.getElementById({self._server_comm.id!r}).textContent += msg.content.data
            }}
        )

        var client_comm = window.PyViz.comm_manager.get_client_comm(
            {self._uuid!r}, {self._client_comm.id!r}, (msg) => console.log('Server ACK')
        );
        
        var clicks = 0
        function send_click() {{
          clicks += 1
          client_comm.send({{'clicks': clicks}})
        }}
        </script>
        
        <button onclick="send_click()">Click me!</button>
        <div id="{self._server_comm.id}"></div>
        """
        mime_bundle = {
            self._EXEC_MIME_TYPE: '', # This allows the Jupyter(Lab) renderers to intercept this message
            'text/html': html
        }
        metadata = {self._EXEC_MIME_TYPE: {'id': self._uuid}}
        return mime_bundle, metadata

test = []
comm = BidirectionalComm(msg_handler=test.append)

comm.send('Foo')
```

Ping @davidbrochart since you were the last to touch that code.

**Comment by davidbrochart** [comment]
Thanks for reporting @philippjfr.
Since your message is JSON and not binary, this means you're not using the `v1.kernel.websocket.jupyter.org` protocol. Any reason for this?

**Comment by philippjfr** [comment]
Thanks for the quick responses!

>Since your message is JSON and not binary, this means you're not using the v1.kernel.websocket.jupyter.org protocol. Any reason for this?

Pretty sure I'm just printing the message after it has already been translated back from binary to JSON. I just stepped through the code and here is what I see on deserialize:

<img width="1412" alt="Screen Shot 2023-06-20 at 11 29 07" src="https://github.com/jupyterlab/jupyterlab/assets/1550771/ec0fe59c-4617-4912-9ad6-43f4bb111641">

Looks like there's one offset at the end that results in the creation of the empty `DataView`.

**Comment by echarles** [comment]
> setting that option does not seem like a great solution for them

Absolutely, that option is IMHO just to be able to understand what is going on and not meant to be a requirement moving forward

**Comment by echarles** [comment]
> We've heard from many users that the JLab 4 upgrade broke comms for them, so this is definitely not isolated to myself.

This is an important aspect of a needed backwards-compatibility strategy that is sadly not always taken into account enough. I had stressed (just one of my many feedbacks on various aspects) in e.g. https://github.com/jupyter-server/jupyter_server/pull/657#issuecomment-1013661886 for this specific change.

**Comment by JohanMabille** [comment]
> This a good example showing the need of centralized documentation on the kernel protocol and how it is used in the major cases (like jlab<->server<->kernel). This would help 3rd parties (like holoviz and others) building on the protocol to follow the changes. I knew that trait because I was part of the discussion, but I guess many developers don't get it, even searching on https://github.com/jupyter-server/jupyter_server/issues?q=kernel_ws_protocol
> 
> cc/ @JohanMabille

Agreed, and that is the direction the Jupyter Project is  taking. The kernel protocol documentation has been moved to its [dedicated repo](https://github.com/jupyter-standards/kernel-protocol) out of the jupyter_client project (for now it is living aside but the former one will be deprecated soon); the different schemas for specifying protocols and files used by the different components of Jupyter will live in the same repo. Then we need to continue our efforts to improve the documentation, any help is welcome!

**Comment by davidbrochart** [comment]
My bad @philippjfr, you were right, I opened #14721.
