### ISSUE TITLE
Releasing JupyterLab from 3.6.x

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#14757]
I had a few issues this weekend while cutting a new release from 3.6.x. branch.

I have contacted @jtpio and @fcollonval about that.

@fcollonval helped me to solve the first issue `requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/jupyterlab/jupyterlab/commits/v3.6.4`

Then I have hit a recent change in the GitHub ghapi API change https://github.com/jupyter-server/jupyter_releaser/issues/516, to finally pin to `ghapi<1.0.4` and work around that.

I had one more issue where my secret was not correctly named, hence a failure to upload to pypi. I have rerun  and now I am failing with `ValueError: Invalid file jupyterlab-3.6.6-py3-none-any.whl` on https://github.com/echarles/jupyter_releaser/actions/runs/5376859097/jobs/9754579811

I guess the consecutive commits of the releaser in the 3.6.x branch may confuse the releaser, as well as the reader.

<img width="1253" alt="Screenshot 2023-06-26 at 12 27 27" src="https://github.com/jupyterlab/jupyterlab/assets/226720/7aea58a8-841e-4b50-b934-16b94e6deade">

Any chance to rewrite the history and remove the 5 latest commits? Any other idea?

**Comment by echarles** [comment]
I am not sure if reverting the history is a right approach, as the tags have already been done https://github.com/jupyterlab/jupyterlab/tags There are a lot of those, I don't know what would be the correct approach for that.

**Comment by fcollonval** [comment]
@echarles it would indeed be good if you could update the branch to remove the unwanted commits and tags.

**Comment by echarles** [comment]
Removed unwanted and made the release.
