### ISSUE TITLE
There is no sufficient access to LSP adapters (`WidgetLSPAdapter`) from widgets

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14783]
### Problem

This is similar to https://github.com/jupyterlab/jupyterlab/issues/14710 which describes the need to access adapters from editors.

Access to adapter from widget is needed to integrate some features, e.g.:
- executing actions from context menu
- updating diagnostics panel when switching editors

Currently:
- there is no mapping from widget adapter
- there is no signal emitted when new adapter gets added

This leads to suboptimal workaround like below:

```ts
app.shell.currentChanged.connect((shell) => {
    const adapter = [...connectionManager.adapters.values()].find(adapter =>
        adapter.widget == shell.currentWidget
    );

    if (!adapter) {
      this.console.debug('No adapter found');
    } else {
      diagnosticsFeature.switchDiagnosticsPanelSource(adapter);
    }
});
// now the problem is that if user switches widget but adapter activates
// after the `app.shell.currentChanged` signal fired we have no way to know.
```

or

```ts
app.shell.currentChanged.connect((shell) => {
    if (!shell.currentWidget) {
      this.console.debug('No current widet');
      return;
    }

    const context = (shell.currentWidget as IDocumentWidget).context;
    if (!context) {
      this.console.debug('Not a document widget');
      return;
    }
    // the problem here is that renaming file will break this - adapters in connectionManager would need to listen to path changes and update mapping.
    // also, what happens if there are multiple views for the same document? It would not work!
    const adapter = connectionManager.adapters.get(context.path);

    if (!adapter) {
      this.console.debug('No adapter found');
    } else {
      diagnosticsFeature.switchDiagnosticsPanelSource(adapter);
    }
});
```

### Proposed solution

One could argue that `AdapterManager` which was removed among comments about too many _managers_ was actually needed, but if we just want to keep adding things to `connectionManager`, we could add:
- `adapterChanged` signal which emits when widget is changed or new adapter is registered on current widget (and thus current adapter changes)

### Additional context

The old LSP extension had the following [`ILSPAdapterManager` interface](https://github.com/jupyter-lsp/jupyterlab-lsp/blob/ff8b6c44d5a81a7bc051604ea37a5bc4da6ec94a/packages/jupyterlab-lsp/src/tokens.ts#L141):

```ts
export interface ILSPAdapterManager {
  adapterTypeAdded: Signal<
    ILSPAdapterManager,
    IAdapterTypeOptions<IDocumentWidget>
  >;
  adapterChanged: Signal<ILSPAdapterManager, WidgetAdapter<IDocumentWidget>>;
  adapterDisposed: Signal<ILSPAdapterManager, WidgetAdapter<IDocumentWidget>>;
  currentAdapter: WidgetAdapter<IDocumentWidget>;
  isAnyActive: () => boolean;
  registerExtension(extension: LSPExtension): void;
  registerAdapterType(options: IAdapterTypeOptions<IDocumentWidget>): void;
  readonly types: IAdapterTypeOptions<IDocumentWidget>[];
}
```

**Comment by fcollonval** [comment]
After exchanging with @hbcarlos, I agree with the above proposal that an interface like `adapterChanged` and `currentAdapter` should be provided.

Where do you think it would make sense to place those?

**Comment by krassowski** [comment]
After looking at the PR I am thinking that it should **not** be a responsibility of connection manager. We do have a `Tracker` interface, maybe we should reuse it and create a new token? Then connection manager would depend on said tracker token and add new adapters to the tracker. The interface would just not include the `add()` method. Does it sound ok?

**Comment by krassowski** [comment]
Yes, I was thinking about something similar to `IWidgetTracker` pattern but maybe we should create a new similar interface (but without the restore method, and possibly with adjusted method naming so it is `currentAdapter` not `currentWidget`).

**Comment by hbcarlos** [comment]
> Then connection manager would depend on said tracker token and add new adapters to the tracker. The interface would just not include the add() method. Does it sound ok?

Instead of registering adapters in the connection manager, why don't we add them to the new tracker, and the connection manager listens for `adapterAdded` on the tracker?

**Comment by hbcarlos** [comment]
Also, now that we have an adapter tracker, do you know if we need the adapter map in the connection manager?

**Comment by krassowski** [comment]
> Also, now that we have an adapter tracker, do you know if we need the adapter map in the connection manager?

I think we do not, as long as it is available elsewhere. But to unblock downstream LSP extension we need to do either:
- merge the changes ASAP and release in 4.0.x
- re-implement the property using the tracker and mark as deprecated to not break LSP extension if we are aiming with the changes for 4.1
