### ISSUE TITLE
Should completer providers be able to advertise suggested default rank?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#14790]
### Problem

When adding a toolbar item or a menu item extensions can define a rank which determines positioning. There are some reserved ranges but the assumption is that everyone will play nice. The manager of `CompleterProvider` also uses ranks but it makes the default ranks up from the list of available providers (for third-party providers). This means that any provider added by extension always has a rank lower than the default providers, and in consequence the model nor renderer from extension is never used (unless user goes to settings and manually changes ranks).

https://github.com/jupyterlab/jupyterlab/blob/e04293eb2ff13b93a0ba8aedbd17e0d591adece7/packages/completer-extension/src/index.ts#L85-L89

### Proposed Solution

Allow extensions to set the preferred rank by adding `defafultRank` or `rank` or to `CompleterProvider` API and use this as default if user has not set a different value.

### Additional context

An alternative (for extensions) is to programatically modify `completer` settings to inject their defaults which is error-prone and deviates from how rank is used in other extendable components (menus, toolbars, context menus).

A short term solution that would unlock release of jupyterlab-lsp would be to put auto-generated extension ranks higher than those of built-in providers.

CC @trungleduc for opinions.

**Comment by trungleduc** [comment]
Hi @krassowski 

> A short term solution that would unlock release of jupyterlab-lsp would be to put auto-generated extension ranks higher than > those of built-in providers.

I agree with this, when users install a custom provider, they expect to have the result of this provider and not the default one.

> Allow extensions to set the preferred rank by adding defafultRank or rank or to CompleterProvider API and use this as default > if user has not set a different value.

I think this would not solve the issue with multiple providers since the provider author may not know about the rank of the built-in or other custom providers, they will end up putting 1 or a random number, then users still have the issue with the provider ordering.

**Comment by hbcarlos** [comment]
> I think this would not solve the issue with multiple providers since the provider author may not know about the rank of the built-in or other custom providers, they will end up putting 1 or a random number, then users still have the issue with the provider ordering.

I think it is a good idea. We could document it properly, saying the rank of the default providers. We could put the default providers a rank of `500`, leave `1000` or above to extension authors, and `0` for deactivating the provider.
