### ISSUE TITLE
Syntax highlighting breaks with format block quotes

### ISSUE THREAD

**Issue by 2xB** [jupyterlab/jupyterlab#14807]
## Description

The code `f""" "{x}" """, 3` is syntax highlighted as if the ending block quotes did not exist.

## Reproduce

1. Open a new notebook
2. Type `f""" "{x}" """, 3`

Result: <img width="82" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/31772910/a3043d64-4e0a-41b6-9f84-5359d0427ba7">

## Expected behavior

The trailing `, 3` should not be red.

## Context

- Operating System and version: Fedora 36 in Docker container
- Browser and version: Microsoft Edge 114.0.1823.67
- JupyterLab version: 4.0.2

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/kasper/install/bin
	/kasper/install/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/usr/local/bin
	/kasper/install/lib64/python
	/home/b/b_bier05/libplist
	/usr/lib64/python310.zip
	/usr/lib64/python3.10
	/usr/lib64/python3.10/lib-dynload
	/kasper/install/python/lib/python3.10/site-packages
	/kasper/install/python/lib/python3.10/site-packages/KaFigure-2.4.2+g7919579-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/tqdm-4.65.0-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/tables-3.8.0-py3.10-linux-x86_64.egg
	/kasper/install/python/lib/python3.10/site-packages/uncertainties-3.1.7-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/natsort-8.4.0-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/awkward-2.2.4-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/uproot3-3.14.4-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/h5py-3.9.0-py3.10-linux-x86_64.egg
	/kasper/install/python/lib/python3.10/site-packages/ChainConsumer-0.34.0-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/emcee-3.1.4-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/PyQt5-5.15.9-py3.10-linux-x86_64.egg
	/kasper/install/python/lib/python3.10/site-packages/tabulate-0.9.0-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/termcolor-2.3.0-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/py_cpuinfo-9.0.0-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/Cython-3.0.0b3-py3.10-linux-x86_64.egg
	/kasper/install/python/lib/python3.10/site-packages/blosc2-2.0.0-py3.10-linux-x86_64.egg
	/kasper/install/python/lib/python3.10/site-packages/future-0.18.3-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/typing_extensions-4.7.0rc1-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/awkward_cpp-17-py3.10-linux-x86_64.egg
	/kasper/install/python/lib/python3.10/site-packages/uproot3_methods-0.10.1-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/cachetools-5.3.1-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/awkward0-0.15.5-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/statsmodels-0.14.0-py3.10-linux-x86_64.egg
	/kasper/install/python/lib/python3.10/site-packages/PyQt5_sip-12.12.1-py3.10-linux-x86_64.egg
	/kasper/install/python/lib/python3.10/site-packages/PyQt5_Qt5-5.15.2-py3.10-linux-x86_64.egg
	/kasper/install/python/lib/python3.10/site-packages/msgpack-1.0.5-py3.10-linux-x86_64.egg
	/kasper/install/python/lib/python3.10/site-packages/patsy-0.5.3-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/KaFitParameterDoc-2.4.2+g7919579-py3.10.egg
	/kasper/install/python/lib/python3.10/site-packages/KaFitSlowControlAnalysis-2.4.2+g7919579-py3.10.egg
	/usr/local/lib64/python3.10/site-packages
	/usr/local/lib/python3.10/site-packages
	/usr/lib64/python3.10/site-packages
	/usr/lib/python3.10/site-packages

sys.executable:
	/usr/bin/python3

sys.version:
	4.10.11 (main, Apr  5 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]

platform.platform():
	Linux-5.15.113-234125.x86_64-x86_64-with-glibc2.35

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/bin/jupyter
	/bin/jupyter

pip list:
	Package                  Version
	------------------------ --------------
	aiohttp                  3.8.4
	aiosignal                1.3.1
	alembic                  1.11.1
	anyio                    3.7.0
	appdirs                  1.4.4
	argon2-cffi              21.1.0
	arrow                    1.2.3
	asttokens                2.0.5
	async-generator          1.10
	async-lru                2.0.2
	async-timeout            4.0.2
	attrs                    21.4.0
	awkward                  2.2.4
	awkward-cpp              17
	awkward0                 0.15.5
	Babel                    2.12.1
	backcall                 0.1.0
	beautifulsoup4           4.12.2
	bleach                   4.0.0
	blosc2                   2.0.0
	Bottleneck               1.3.2
	Brotli                   1.0.9
	cachetools               5.3.1
	certifi                  2023.5.7
	certipy                  0.1.3
	cffi                     1.15.0
	ChainConsumer            0.34.0
	charset-normalizer       2.0.11
	cryptography             41.0.1
	cycler                   0.11.0
	Cython                   3.0.0b3
	decorator                5.1.1
	defusedxml               0.7.1
	Deprecated               1.2.13
	emcee                    3.1.4
	entrypoints              0.3
	exceptiongroup           1.1.1
	executing                0.8.2
	fastjsonschema           2.17.1
	fonttools                4.29.1
	fqdn                     1.5.1
	frozenlist               1.3.3
	fs                       2.4.11
	future                   0.18.3
	gpg                      1.17.0
	greenlet                 2.0.2
	h5py                     3.9.0
	html5lib                 1.1
	idna                     3.3
	ipykernel                6.6.1
	ipython                  8.3.0
	ipython_genutils         0.2.0
	isoduration              20.11.0
	jedi                     0.18.1
	Jinja2                   3.0.3
	json5                    0.9.14
	jsonpointer              2.4
	jsonschema               4.17.3
	jupyter_client           7.4.9
	jupyter_core             5.3.1
	jupyter-events           0.6.3
	jupyter-lsp              2.2.0
	jupyter_server           2.6.0
	jupyter_server_proxy     4.0.0
	jupyter_server_terminals 0.4.4
	jupyter-telemetry        0.1.0
	jupyterhub               4.0.1
	jupyterlab               4.0.2
	jupyterlab-pygments      0.1.2
	jupyterlab_server        2.23.0
	jwcrypto                 0.9.1
	KaFigure                 2.4.2+g7919579
	KaFitParameterDoc        2.4.2+g7919579
	KaFitSlowControlAnalysis 2.4.2+g7919579
	kiwisolver               1.4.1
	libcomps                 0.1.18
	lxml                     4.7.1
	Mako                     1.2.4
	MarkupSafe               2.1.1
	matplotlib               3.5.3
	matplotlib-inline        0.1.2
	mistune                  3.0.1
	msgpack                  1.0.5
	multidict                6.0.4
	munkres                  1.1.2
	natsort                  8.4.0
	nbclient                 0.5.10
	nbconvert                7.6.0
	nbformat                 5.9.0
	nest-asyncio             1.5.4
	notebook                 6.4.12
	notebook_shim            0.2.3
	numexpr                  2.8.4
	numpy                    1.22.0
	oauthlib                 3.2.2
	olefile                  0.46
	overrides                7.3.1
	packaging                21.3
	pamela                   1.1.0
	pandas                   1.3.5
	pandocfilters            1.5.0
	parso                    0.8.2
	patsy                    0.5.3
	pexpect                  4.8.0
	pickleshare              0.7.5
	Pillow                   9.1.0
	pip                      21.3.1
	platformdirs             3.6.0
	ply                      3.11
	prometheus-client        0.13.1
	prompt-toolkit           3.0.24
	ptyprocess               0.6.0
	pure-eval                0.2.2
	py-cpuinfo               9.0.0
	pycairo                  1.21.0
	pycparser                2.20
	Pygments                 2.11.2
	pyOpenSSL                23.2.0
	pyparsing                2.4.7
	PyQt5                    5.15.9
	PyQt5-Qt5                5.15.2
	PyQt5-sip                12.12.1
	pyrsistent               0.18.1
	PySocks                  1.7.1
	python-dateutil          2.8.2
	python-json-logger       2.0.7
	pytz                     2023.3
	pyxdg                    0.27
	PyYAML                   6.0
	pyzmq                    25.1.0
	redis                    3.5.3
	requests                 2.31.0
	rfc3339-validator        0.1.4
	rfc3986-validator        0.1.1
	ROOT                     6.28.2
	rpm                      4.17.1
	ruamel.yaml              0.17.32
	ruamel.yaml.clib         0.2.7
	scipy                    1.8.1
	Send2Trash               1.8.0
	setuptools               59.6.0
	simpervisor              1.0.0
	simplejson               3.17.6
	six                      1.16.0
	sniffio                  1.3.0
	soupsieve                2.4.1
	SQLAlchemy               2.0.16
	stack-data               0.1.4
	statsmodels              0.14.0
	tables                   3.8.0
	tabulate                 0.9.0
	termcolor                2.3.0
	terminado                0.12.1
	testpath                 0.5.0
	tinycss2                 1.2.1
	tomli                    2.0.1
	tornado                  6.3.2
	tqdm                     4.65.0
	traitlets                5.9.0
	typing_extensions        4.7.0rc1
	uncertainties            3.1.7
	uproot3                  3.14.4
	uproot3-methods          0.10.1
	uri-template             1.2.0
	urllib3                  1.26.12
	wcwidth                  0.2.5
	webcolors                1.13
	webencodings             0.5.1
	websocket-client         1.6.0
	websockify               0.11.0
	wrapt                    1.14.0
	yarl                     1.9.2

</pre>
</details>

**Comment by krassowski** [comment]
I can reproduce in a code cell in 4.0.2. It works correctly in latest [CodeMirror 6](https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge3B5dGhvbn0gZnJvbSAiQGNvZGVtaXJyb3IvbGFuZy1weXRob24iCgpuZXcgRWRpdG9yVmlldyh7CiAgZG9jOiBgZiIiIiAie3h9IiAiIiIsIDNgLAogIGV4dGVuc2lvbnM6IFsKICAgIGJhc2ljU2V0dXAsCiAgICBweXRob24oKQogIF0sCiAgcGFyZW50OiBkb2N1bWVudC5ib2R5Cn0pCg==). It also appears to work well on `main` branch:

![Screenshot from 2023-07-09 11-55-21](https://github.com/jupyterlab/jupyterlab/assets/5832902/9f52a85f-a6d3-4650-be12-a4f3fad375c1)

I think it was fixed upstream in `@lezer/python` [1.1.7](https://github.com/lezer-parser/python/blob/main/CHANGELOG.md#117-2023-05-27) last month, here is the relevant issue: https://github.com/codemirror/dev/issues/1166. On our side https://github.com/jupyterlab/jupyterlab/pull/14748 bumped `@lezer/python` to 1.1.7 which is why it works on `main` branch and should work in 4.0.3 to be released this week.

**Comment by 2xB** [comment]
That's great, looking forward to 4.0.3 then!
