### ISSUE TITLE
terminal error (no text, all rainbow colors)

### ISSUE THREAD

**Issue by xikronz** [jupyterlab/jupyterlab#14815]
## Description

Cmd runs fine on its own but the terminal in my jupyter lab doesn't show any text. Instead, its all a block of rainbow colors where the text is supposed to be. I can type new lines in the terminal, its just those lines are also just blocks of color and the lab recognizes these commands. Not sure how to fix this because I've never had smth like this happen before. 
Link to ss: https://imgur.com/a/XmEWUpm

## Reproduce

Can't exactly reproduce this because its just opening my terminal but starting from cmd: 
jupyter lab 
open terminal 
weird colors 

## Expected behavior

regular terminal texts

## Context
First time downloading jupyter lab on my new computer, tried running the lab from admin but it still gives me the weird color bars. 

- Operating System and version: windows 11 64-bit operating system, x64-based processor
- Browser and version: librewolf
- JupyterLab version: 4.0.2

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.
isActive resource:///modules/UrlbarProviderInterventions.sys.mjs:523
    tryMethod resource:///modules/UrlbarUtils.sys.mjs:2130
    start resource:///modules/UrlbarProvidersManager.sys.mjs:422
    startQuery resource:///modules/UrlbarProvidersManager.sys.mjs:288
[UrlbarUtils.sys.mjs:2132:15](resource:///modules/UrlbarUtils.sys.mjs)
TypeError: topDocScore is undefined
    isActive resource:///modules/UrlbarProviderInterventions.sys.mjs:523
    tryMethod resource:///modules/UrlbarUtils.sys.mjs:2130
    start resource:///modules/UrlbarProvidersManager.sys.mjs:422
</pre>
</details>

**Comment by tuncbkose** [comment]
I remember encountering a similar issue (if not the same) on Firefox, which I attributed to me messing with some privacy-oriented settings. Not sure what restored proper functionality though.

**Comment by JasonWeill** [comment]
@xikronz Any update on testing with another browser with default settings? It could be that your browser is unable to load the font being used for the terminal.

**Comment by ASGusev** [comment]
I have encountered this today and found this issue. My problem was solved by allowing html 5 canvas for localhost
