### ISSUE TITLE
The command run in jupyter kernels doesn't match the env.

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [jupyterlab/jupyterlab#14824]
I have separately configured cuda for this conda environment：cuda11.6 in conda env MindSpore.
![image](https://github.com/jupyterlab/jupyterlab/assets/84905965/0ff51fca-34de-4431-b529-1a4bd13e43a0)

However when run in jupyterlab 
![image](https://github.com/jupyterlab/jupyterlab/assets/84905965/7c318c95-8a82-4532-9ae5-a43ae3be7462)

I found that the command mismatches the env.

**Comment by FireCulex** [comment]
I came across this as well on Windows. pip list on 2 different notebooks assigned to the same kernel show different results...

**Comment by krassowski** [comment]
You should use `%pip` in ipykernel to access the `pip` in appropriate environment (not `!pip`). This is not a jupyterlab issue in any case but possibly a question about ipykernel/IPython.

**Comment by Ethan-Chen-plus** [comment]
> You should use `%pip` in ipykernel to access the `pip` in appropriate environment (not `!pip`). This is not a jupyterlab issue in any case but possibly a question about ipykernel/IPython.

That works! Thanks a lot!
