### ISSUE TITLE
Bug in calculation in `HoverBox.setGeometry`

### ISSUE THREAD

**Issue by nishikantparmariam** [jupyterlab/jupyterlab#14845]
## Description

I am using [`HoverBox.setGeometry`](https://github.com/jupyterlab/jupyterlab/blob/3e45cb9e3038b8e40274ac7cb4d03c1be9439768/packages/ui-components/src/hoverbox.ts#L131) to position a widget in an extension, and want to pass `stick-inside` for all options in [`outOfViewDisplay`](https://github.com/jupyterlab/jupyterlab/blob/3e45cb9e3038b8e40274ac7cb4d03c1be9439768/packages/ui-components/src/hoverbox.ts#L109). However, it does not seem to function as expected for the `right` option. After lot of debugging, I've found an issue in the calculation.

## Reproducer & Bug

https://github.com/jupyterlab/jupyterlab/blob/3e45cb9e3038b8e40274ac7cb4d03c1be9439768/packages/ui-components/src/hoverbox.ts#L226-L237

Consider the above code, and a case when `anchor.left` is located on the very right of the screen. At line `228`, we update the `node`'s left to `anchor`'s left (assume `offsetHorizontal` to be zero for simplicity). Suppose `node` has some width, then virtually, at this point the right edge of the `node` is out of window, and the condition at line `234` will be true. Here, `left` is correctly adjusted so that the right edge of `node` touches  right edge of window. 

**The bug lies here in re-calculation of width** - 
https://github.com/jupyterlab/jupyterlab/blob/3e45cb9e3038b8e40274ac7cb4d03c1be9439768/packages/ui-components/src/hoverbox.ts#L270

Since, we reduced `right - window.innerWidth` from `left`, the new `right` now is actually just `window.innerWidth`. Because the original `right` is out of the window, `width` calculated here is actually greater than original.

`width` is re-used in below code, which finally leads to wrong re-setting of `left` ,and node is placed wrongly horizontally - 

https://github.com/jupyterlab/jupyterlab/blob/3e45cb9e3038b8e40274ac7cb4d03c1be9439768/packages/ui-components/src/hoverbox.ts#L374-L378

Cases when bug can be noticed - When `anchor.left` is less than node's `width` away from right edge of the window.

## Proposed Solution

One solution could be to adjust `right` correctly if `left` was adjusted before re-calculation of width as explained above.

## Context

- Operating System and version: Linux RHEL8
- Browser and version: Chrome 114.0.5735.199 
- JupyterLab version: 4.0.0

**Comment by krassowski** [comment]
Thank you @nishikantparmariam for detailed reproduction instructions!
