### ISSUE TITLE
File menu disappeared

### ISSUE THREAD

**Issue by aakhmetz** [jupyterlab/jupyterlab#14879]
Hello, I have got the file menu disappeared recently:
![image](https://github.com/jupyterlab/jupyterlab/assets/2173206/8021d0be-27b9-490b-9966-2aa0d47b8253)
For example, I can't select the New view for the notebook. I wonder what could be the reason.

I cannot also do ```jupyter lab build```, it gives me an error, but I wonder if it could be connected to my issue above.

I have the latest update, and my system is manjaro (ArchLinux)

**Comment by krassowski** [comment]
This is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/14850.

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/issues/14850 since https://github.com/jupyterlab/jupyterlab/issues/14850 is a bit older and has a few more messages.

I copied the screenshot to the top comment in https://github.com/jupyterlab/jupyterlab/issues/14850.

**Comment by aakhmetz** [comment]
Thanks!
