### ISSUE TITLE
Unable to scroll when cells are selected 

### ISSUE THREAD

**Issue by sorenwacker** [jupyterlab/jupyterlab#14881]
I used to be able to scroll with two fingers while having some cells selected. This way, i could select cells and scroll to the place where I needed them and drop them. Now, in Jupyter 4.0.3 this does not work anymore. Scrolling seems to be disabled when cells are selected and the mouse button is held. Not sure if this is intentional. IMO it leads to a drop in productivity. Because now I have to select the cells and cut them, and then paste them somewhere else, which requires comparatively much more actions and time.

**Comment by krassowski** [comment]
Reproduced. Scrolling with selection does not work with mouse wheel, but it works by moving the cursor with the dragged cells to the edge of the viewport:

![scrolling-with-windowing-mode](https://github.com/jupyterlab/jupyterlab/assets/5832902/38306201-bf50-4b9e-ae7f-0b4657916901)

> Note: the mouse icon shows when I use the mouse wheel with small arrow icons.

It suggests that this might be a simple issue with event binding, possibly during mouse > pointer event transition?
