### ISSUE TITLE
Today I upgrade jupyter and jupyterlab, and I can't use "show in file browser"

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [jupyterlab/jupyterlab#14889]
as title.
![image](https://github.com/jupyterlab/jupyterlab/assets/84905965/5dddc08f-6059-49cb-bb14-59dbc56cbde6)
version:
![image](https://github.com/jupyterlab/jupyterlab/assets/84905965/8c745758-bc56-40dc-8eab-47e67f35b89a)

**Comment by krassowski** [comment]
Closing as a duplicate of a duplicate https://github.com/jupyterlab/jupyterlab/issues/14879 https://github.com/jupyterlab/jupyterlab/issues/14850
