### ISSUE TITLE
navigating from the TOC outline is broken

### ISSUE THREAD

**Issue by parmentelat** [jupyterlab/jupyterlab#14897]
## Description

when editing a notebook with the table of contents active; then double-clicking an entry in the TOC should - at least that's my understanding:

* make the corresponding cell active - the one that contains the corresponding (sub)-title
* and if needed, scroll the notebook so that cell becomes visible in the viewport

in most of my attempts, the second action is not performed, which ruins the purpose of the TOC pane

![navigation-toc-broken](https://github.com/jupyterlab/jupyterlab/assets/4519227/4e76ce78-4092-4f1a-b5ff-92952b8e4f4d)

## Reproduce

1. Open a non-trivial notebook, with headers that show outside of the viewport
2. make sure the table of contents is active
3. double-click in the TOC on a title that is not visible
4. the corresponding cell becomes active all right, but it is still non-visible in the viewport

## Expected behavior

I expect the notebook to scroll so that the target cell becomes visible in the viewport

## Context

I am on Chrome/MacOS
other folks have seen the same, see also https://discourse.jupyter.org/t/navigating-from-the-toc-is-it-broken/20719/2

**Comment by krassowski** [comment]
Is this a duplicate of https://github.com/jupyterlab/jupyterlab/issues/14574 fixed by https://github.com/jupyterlab/jupyterlab/pull/14753 and also reported in https://github.com/jupyterlab/jupyterlab/issues/14877?

**Comment by parmentelat** [comment]
at first sight this is different; the notebook in the video capture does not have its first title out of order in terms of hierarchy
plus IIUC #14574 is about having the TOC outline amputated prematurely, in my case the TOC is complete
it's just that double-clicking does not ensure the target cell gets visible in the viewport

**Comment by krassowski** [comment]
Whoops sorry, my mistake I meant to point to https://github.com/jupyterlab/jupyterlab/pull/14884 and https://github.com/jupyterlab/jupyterlab/issues/14591

**Comment by christran16** [comment]
I am also having this issue, though I've also noticed that this occurs when I click from a code cell to a TOC entry. If I am in a markdown cell and click on a TOC entry this doesn't happen. Additionally, in my case, it will change the markdown cell of the TOC entry to edit mode, which may be what is causing it not to scroll to the cell.

**Comment by parmentelat** [comment]
@krassowski 
I have been trying to investigate this one a little further, and here's what I found out

- my production env relies on 4.05 and I experiment the faulty behaviour that I described in the initial post, namely clicking in the TOC does not focus on the target header
- trying again on the very same notebook but within a fresh jupyterlab repo cloned from the current tip of jupyterlab at commit jupyterlab/jupyterlab@26e5f9533c does not

so my next move was to try on my production env running in safe mode, i.e. with all extensions turned off
however, I am struggling to implement this
I [did find a reference to a `--safe-mode` option](https://saturncloud.io/blog/how-to-troubleshoot-jupyter-lab-failing-to-launch/#step-4-run-jupyter-lab-in-safe-mode)  but that does not seem to be available any longer (has it ever been ?)
So I'll proceed along these lines

In the meanwhile I'd appreciate any insight about the expected date for the next release of jupyter lab, since my issue might be just solved at this point already

**Comment by parmentelat** [comment]
following-up:

my original issue is not with jupyterlab per se, it has to see with the `jupyterlab-myst` extension
so I will log a new issue in there and close this one

see https://github.com/executablebooks/jupyterlab-myst/issues/184

**Comment by jpcaram** [comment]
I'm experiencing quite erratic behavior with the TOC, and I don't have ```jupyterlab-myst```. Clicking on a TOC item sometimes doesn't scroll the document at all, other times it scrolls but not to the right place, and sometimes it does scroll correctly to the given heading but switches it to edit mode. I'm on JupyterLab 4.0.7 and Firefox 118.0.2 on Ubuntu. I couldn't find an issue for this. Did I miss it?

**Comment by 0xnurl** [comment]
So happy to find this thread, I thought I was going crazy. I can confirm that this still happens on 4.0.9. Downgrading to `jupyterlab==3.6.6` solved it for me.
