### ISSUE TITLE
Font Increase/Decrease Not Working in JupyterLite

### ISSUE THREAD

**Issue by jmr54** [jupyterlab/jupyterlab#14909]
## Description
Found a possible issue with JupyterLite. Does not increase or decrease font size once clicked. 

## Reproduce

1. Go to 'Setting' on top of Navbar
2. Click on 'Increase Text Editor Font Size'  or 'Decrease Text Editor Font Size'
3. No response to once clicked

## Expected behavior

I believe that the font size should increase or decrease depending which button is clicked. 

## Context

- Operating System and version: Windows 1122H2
- Browser and version: Firefox 22621.1992 and Version 115.0.5790.110 
- JupyterLab version: Jupyterlite Version 0.1.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by jtpio** [comment]
Thanks @jmr54 for reporting.

Would you mind re-opening the issue on the JupyterLite repo? https://github.com/jupyterlite/jupyterlite

**Comment by jmr54** [comment]
Sorry, added to JupyterLite repo. Thanks

**Comment by jtpio** [comment]
Thanks!

Actually just checking to be sure if it's not an issue in JupyterLab: do you expect the font size of the notebook cells to increase / decrease? Or only the text editors?

Here is what happens after quickly trying it, first with JupyterLab 4, then with JupyterLite (currently based on JupyterLab 3):


https://github.com/jupyterlab/jupyterlab/assets/591645/86f63ebd-9025-4d60-be43-247b7e20e523

**Comment by jmr54** [comment]
That is my bad. I thought the font size would increase for the notebook cells.
