### ISSUE TITLE
Copy paste from a rendered pandas dataframe not working as expected.

### ISSUE THREAD

**Issue by sorenwacker** [jupyterlab/jupyterlab#14918]
![image](https://github.com/jupyterlab/jupyterlab/assets/3391614/1ed1707a-ac4a-4d10-b02d-a40ae47eaf3a)

When selecting the cell content and CTRL+c 

pasting it here:
```
<html>
<body>
<!--StartFragment-->

(S)-mevalonic acid(1-)
--


<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

It should simply return:

```
(S)-mevalonic acid(1-)
```

Windows 11
JupyterLab Version 4.0.4
Chrome Version 115.0.5790.110 (Official Build) (64-bit)

**Comment by JasonWeill** [comment]
@sorenwacker Thank you for contributing this! A couple of questions:

1. Does this also occur with JupyterLab 3 or with Jupyter Notebook?
2. If you press `CTRL+SHIFT+V` to paste (or the "paste as plain text" shortcut for you), do you see only the text value of what you copied?

**Comment by krassowski** [comment]
This is Chromium-specific bug. I see it too, on various websites. It would be good to get a reliable reproducer and report it upstream in Chrome.
