### ISSUE TITLE
Wrong yarn.lock in released 4.0.4

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#14924]
## Description

Since the release of 4.0.4, integration tests are failing; see for examples: 
- https://github.com/jupyterlab/extension-template/actions/runs/5777728638/job/15658220778?pr=39
- https://github.com/jupyterlab-contrib/jupyter-archive/actions/runs/5777706952/job/15658204740?pr=118

The reason is that the galata xpath selector to check for the _Launcher_ tab is not valid any longer as a consequence of https://github.com/jupyterlab/lumino/pull/606 (the selector was using `jp-Activity` class that is now gone).

---

The underlying painful bug is that the yarn.lock got modify to pull the latest version of @lumino instead of keeping the one in the dev yarn.lock. This is the reason the CI is green and we did not capture that bug :cry:

**Comment by fcollonval** [comment]
The upgrade in the staging yarn.lock occurred in the publication commit: https://github.com/jupyterlab/jupyterlab/commit/de28aca9ca8a60b25d28efdf359bb2c69d58c634

We have now quite some discrepancies with the dev yarn.lock.

**Comment by fcollonval** [comment]
Similar to https://github.com/jupyterlab/jupyterlab/issues/11429 but it is gonna be more tricky to solve due to the new yarn version algorithm.

**Comment by jtpio** [comment]
> The upgrade in the staging yarn.lock occurred in the publication commit: [de28aca](https://github.com/jupyterlab/jupyterlab/commit/de28aca9ca8a60b25d28efdf359bb2c69d58c634)

Isn't is the expected behavior that `staging/yarn.lock` should be replaced by `yarn.lock` on release?

If we look at the release commit for `4.0.3`, `staging/yarn.lock` was also updated with newer versions of packages: https://github.com/jupyterlab/jupyterlab/commit/f8226e7e4efd8fadebc1eee7b003fad33615fa5c#diff-285db1844b4ca4d4bd926aba6bd1b9e430857f11840b33a5fed086354d0978c8

**Comment by fcollonval** [comment]
Yes it is expected to be replaced by the one in dev-mode. But since we change the application top package and pin the `@jupyterlab/*` packages (to the one we have just released), we are executing `jlpm install` (and deduplicating the lock file), after copying the file. That call is the culprit as now `jlpm install` will bump any packages of the yarn.lock as long as their version spec is respected. This breaks the control we should have on the released yarn.lock as basically any uncontrolled bump of dependencies may occur.

For 4.0.4 in particular, that lead to bumping to the latest version of Lumino.

**Comment by jtpio** [comment]
> `jlpm install` will bump any packages of the yarn.lock as long as their version spec is respected

Ah indeed this is / was not expected.

**Comment by fcollonval** [comment]
For posterity, here is an example of unwanted update that occurred through:

dev_mode:
https://github.com/jupyterlab/jupyterlab/blob/de28aca9ca8a60b25d28efdf359bb2c69d58c634/yarn.lock#L5214-L5215

staging (release):
https://github.com/jupyterlab/jupyterlab/blob/de28aca9ca8a60b25d28efdf359bb2c69d58c634/jupyterlab/staging/yarn.lock#L2545-L2546
