### ISSUE TITLE
Cannot run Jupyter after Installation

### ISSUE THREAD

**Issue by SteffQing** [jupyterlab/jupyterlab#14922]
Hi. I installed jupyterlabs but I can't for the life of myself, seem to run the jupyter lab command
I get an error that says `'jupyter' is not recognized as an internal or external command,
operable program or batch file.`
I don't know what else to do. Please help

**Comment by fcollonval** [comment]
Hey @SteffQing 

How did you install JupyterLab? We strongly advice to use python environments.

> That error usually means (if the installation was successful) that you don't have your command line properly configure to load installed binaries.

**Comment by SteffQing** [comment]
> Hey @SteffQing 
> 
> How did you install JupyterLab? We strongly advice to use python environments; like conda.
> 
> > That error usually means (if the installation was successful) that you don't have your command line properly configure to load installed binaries.

I used pip install jupyterlab command
And I did it in, what should be my root folder of the PC?
In the command line, the folder was at C:/Users/HP
