### ISSUE TITLE
add tolerance for network unstability 

### ISSUE THREAD

**Issue by linlol** [jupyterlab/jupyterlab#14932]
### Problem

Hi team,

We are using JupyterLab via JupyterHub and k8s.

As you may be aware of that, when running, JupyterLab would keep tracking status of session, kernel, kernel specs and live metrics.

For example, it would keep tracking live sessions at https://github.com/jupyterlab/jupyterlab/blob/main/packages/services/src/session/restapi.ts

and pop-up a window notify user that server has died if request failed with response 503 or networking issue like DNS resolve error via logic here https://github.com/jupyterlab/jupyterlab/blob/main/packages/hub-extension/src/index.ts

the case is that, when user is using JupyterLab with backend running on a half of earth (for example, our frontend browser may run at APAC or north America while jupyter server is running at Europe), it is possible to have a few request unavailable, hence a greater tolerance might be requested.

### Proposed Solution

One possible solution is add some configurable retry workflow, for example, if we failed to get running sessions 3 times in a row from backend, it pops up server died warning, I wonder that if ther is similar thing, if not, we may try to make a version internally and share PR.

What if the above proposal is not applicable, is it possible to write an extension by our own to override the built-in hub-extension, in this case, I may build one hub-extension internally and override the hub-extension

Thanks a lot for your help, sorry that I am not eligible to share related screenshot since it is internal application

**Comment by JasonWeill** [comment]
Another issue regarding JupyterLab's behavior on JupyterHub with an unstable connection: #7081

**Comment by linlol** [comment]
thanks a lot, have a further look at extension override.

is it correct that what if I create another extension with same token name jupyter would use my customised extension to override built-in hub-extension

**Comment by linlol** [comment]
here is a quick updated

As inspired from community, actially we can customise lab
 extension that overrides token IConnectionLost to customise the behaviour
