### ISSUE TITLE
Links are broken in Notebooks documentation 

### ISSUE THREAD

**Issue by throwable-one** [jupyterlab/jupyterlab#14934]
In this document https://jupyterlab.readthedocs.io/en/stable/extension/notebook.html
almost all links like [NotebookModel](https://jupyterlab.readthedocs.io/en/stable/api/classes/notebook.notebookmodel-1.html) and https://jupyterlab.readthedocs.io/en/stable/api/classes/cells.cellmodel-1.html point to 404

**Comment by krassowski** [comment]
Closing as I checked that all the links in https://jupyterlab.readthedocs.io/en/stable/extension/notebook.html and all of these work ok; please reopen if there is a broken link I missed.
