### ISSUE TITLE
Need an option to clear the output of the Cell

### ISSUE THREAD

**Issue by whaozl** [jupyterlab/jupyterlab#1494]

**Comment by blink1073** [comment]
Hi @whaozl, thank you for the prompt.  We are trying to limit what goes into the toolbar itself because they need to exist side-by-side instead of spanning the whole browser window as in the classic notebook.  We are in fact missing this option from our menu and command palette though.

**Comment by whaozl** [comment]
Thank you, I want the clear the output of the cell because I or many people don't like the output so long. and , thekeyboard shortcuts about the output of the cell is not provided.

**Comment by blink1073** [comment]
I'm going to leave this open as a reminder to implement the menu and palette item.

**Comment by blink1073** [comment]
Ah, this already exists as a palette item.  @ellisonbg is going to be taking a pass at what goes in to the menu as part of #1443.

<img width="238" alt="screen shot 2017-01-17 at 1 42 11 pm" src="https://cloud.githubusercontent.com/assets/2096628/22036946/ebf44258-dcba-11e6-9974-c365cfbb4f7c.png">
