### ISSUE TITLE
Integration tests for extensions fail with JupyterLab 4.0.4

### ISSUE THREAD

**Issue by ihuicatl** [jupyterlab/jupyterlab#14960]
## Description

When executing the integration tests (created by default with the extension template), the test fails with the following error:

```sh
1) tests/tst_widget_extension.spec.ts:9:5 › should emit an activation console message ────────────

    Test timeout of 60000ms exceeded.

    Error: page.$: Target page, context or browser has been closed

        at ActivityHelper.getTab (/home/runner/work/tst-widget-extension/tst-widget-extension/ui-tests/node_modules/@jupyterlab/galata/src/helpers/activity.ts:58:17)
        at ActivityHelper.isTabActive (/home/runner/work/tst-widget-extension/tst-widget-extension/ui-tests/node_modules/@jupyterlab/galata/src/helpers/activity.ts:37:28)
        at /home/runner/work/tst-widget-extension/tst-widget-extension/ui-tests/node_modules/@jupyterlab/galata/src/fixtures.ts:328:33
        at Timeout.check (/home/runner/work/tst-widget-extension/tst-widget-extension/ui-tests/node_modules/@jupyterlab/galata/src/utils.ts:166:33)

    attachment #1: video (video/webm) ──────────────────────────────────────────────────────────────
    test-results/tests-tst_widget_extension-should-emit-an-activation-console-message/video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────

  1 failed
    tests/tst_widget_extension.spec.ts:9:5 › should emit an activation console message ─────────────
Error:   1) tests/tst_widget_extension.spec.ts:9:5 › should emit an activation console message ────────────
    Test timeout of 60000ms exceeded.
Error:   1) tests/tst_widget_extension.spec.ts:9:5 › should emit an activation console message ────────────
    Error: page.$: Target page, context or browser has been closed

```

This only happens with JupyterLab 4.0.4. The versions 4.0.2 and 4.0.3 work as expected. 

## Reproduce

For simplicity, I created a fresh front-end extension from the extension template (https://github.com/jupyterlab/extension-template) and pinned `jupyterlab=4.0.4` in the "Integration Tests" section of *build.yml*

1. Go to https://github.com/ihuicatl/tst-widget-extension/pull/1
2. Click on details of `Build / Integration Tests`
3. Scroll down to `Execute integration tests`
4. See error above

## Expected behavior

The integration test should pass before the timeout. 

## Context

- Operating System and version:  Ubuntu 22.04.3
- Browser and version:  Chromium 116.0.5845.82
- JupyterLab version:  4.0.4

<details><summary>Troubleshoot Output</summary>
<pre>

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 2023-08-11 17:09:05.095 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-08-11 17:09:05.101 ServerApp] Package jupyter_lsp took 0.0060s to import
[W 2023-08-11 17:09:05.101 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-11 17:09:05.104 ServerApp] Package jupyter_server_terminals took 0.0023s to import
[I 2023-08-11 17:09:05.104 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-08-11 17:09:05.104 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-11 17:09:05.104 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-08-11 17:09:05.106 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-08-11 17:09:05.108 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-08-11 17:09:05.217 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-08-11 17:09:05.228 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-08-11 17:09:05.229 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-08-11 17:09:05.230 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-08-11 17:09:05.230 LabApp] JupyterLab extension loaded from /home/user/micromamba/envs/tst/lib/python3.11/site-packages/jupyterlab
[I 2023-08-11 17:09:05.230 LabApp] JupyterLab application directory is /home/user/micromamba/envs/tst/share/jupyter/lab
[I 2023-08-11 17:09:05.231 LabApp] Extension Manager is 'pypi'.
[I 2023-08-11 17:09:05.232 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-08-11 17:09:05.232 ServerApp] Serving notebooks from local directory: /home/user/Repos/Jupyter/tst/tst-widget-extension
[I 2023-08-11 17:09:05.232 ServerApp] Jupyter Server 2.7.0 is running at:
[I 2023-08-11 17:09:05.232 ServerApp] http://localhost:8888/lab?token=
[I 2023-08-11 17:09:05.232 ServerApp]     http://127.0.0.1:8888/lab?token=
[I 2023-08-11 17:09:05.232 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-08-11 17:09:05.241 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/user/.local/share/jupyter/runtime/jpserver-9844-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=
        http://127.0.0.1:8888/lab?token=
[I 2023-08-11 17:09:05.623 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2023-08-11 17:09:08.836 LabApp] Build is up to date

</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
JupyterLab extension tst-widget-extension is activated! [index.ts:14:12](webpack://tst-widget-extension/src/index.ts)

Language pack 'en_US' not installed! [jlab_core.feb2c01f1991a78e718d.js:1:1443099](http://localhost:8888/static/lab/jlab_core.feb2c01f1991a78e718d.js?v=feb2c01f1991a78e718d)

Starting application in workspace: "default"

</pre>
</details>

**Comment by JasonWeill** [comment]
@fcollonval just released JupyterLab 4.0.5, which fixes this issue. Thank you for your contribution!
