### ISSUE TITLE
Running kernels not listed in the "Kernels" panel

### ISSUE THREAD

**Issue by paolocarinci** [jupyterlab/jupyterlab#14962]
## Description

The running kernels related to notebooks and terminals are not listed in the "Kernels" panel on the left side when kernels without icon are installed.

## Reproduce

1. Install a kernel *without* a provided icon (e.g. https://pypi.org/project/allthekernels/)
2. Open a notebook or terminal
3. Execute some code

## Expected behavior

The running kernels related to notebooks or terminals should be  listed in the "Kernels" left-side panel. 

## Context

- Operating System and version: Alpine Linux 3.18 (server)/Arch Linux (browser)
- Browser and version: Mozilla Firefox 116.0.1, Chromium 115
- JupyterLab version: 4.0.4
- IPython  version: 8.14.0
ipykernel version: 6.25.1
ipywidgets version: 8.1.0
jupyter_client version: 8.3.0
jupyter_core version: 5.3.1
jupyter_server version: 2.7.0
nbclient  version: 0.8.0
nbconvert version: 7.7.3
nbformat version: 5.9.2
notebook version: 7.0.2
traitlets  version: 5.9.0

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /opt/jupyterhub/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /opt/jupyterhub/bin
        /usr/lib/python311.zip
        /usr/lib/python3.11
        /usr/lib/python3.11/lib-dynload
        /opt/jupyterhub/lib/python3.11/site-packages

sys.executable:
        /opt/jupyterhub/bin/python3

sys.version:
        3.11.4 (main, Jun  9 2023, 02:29:05) [GCC 12.2.1 20220924]

platform.platform():
        Linux-6.1.43-0-lts-x86_64-with

which -a jupyter:
        /opt/jupyterhub/bin/jupyter

pip list:
        Package                        Version
        ------------------------------ -----------
        aiofiles                       22.1.0
        aiosqlite                      0.19.0
        alembic                        1.11.2
        allthekernels                  1.2.0
        anyio                          4.0.0rc1
        argon2-cffi                    21.3.0
        argon2-cffi-bindings           21.2.0
        arrow                          1.2.3
        asttokens                      2.2.1
        async-generator                1.10
        async-lru                      2.0.4
        attrs                          23.1.0
        Babel                          2.12.1
        backcall                       0.2.0
        bash_kernel                    0.9.1
        bcrypt                         4.0.1
        beautifulsoup4                 4.12.2
        bleach                         6.0.0
        certifi                        2023.7.22
        certipy                        0.1.3
        cffi                           1.15.1
        charset-normalizer             3.2.0
        comm                           0.1.4
        cryptography                   41.0.3
        debugpy                        1.6.7.post1
        decorator                      5.1.1
        defusedxml                     0.7.1
        entrypoints                    0.4
        executing                      1.2.0
        fastjsonschema                 2.18.0
        fqdn                           1.5.1
        greenlet                       3.0.0a1
        idna                           3.4
        ipykernel                      6.25.1
        ipython                        8.14.0
        ipython-genutils               0.2.0
        ipywidgets                     8.1.0
        isoduration                    20.11.0
        jedi                           0.19.0
        Jinja2                         3.1.2
        json5                          0.9.14
        jsonpointer                    2.4
        jsonschema                     4.19.0
        jsonschema-specifications      2023.7.1
        jupyter-c-kernel               1.2.2
        jupyter_client                 8.3.0
        jupyter_core                   5.3.1
        jupyter-events                 0.7.0
        jupyter-lsp                    2.2.0
        jupyter_server                 2.7.0
        jupyter_server_fileid          0.9.0
        jupyter_server_terminals       0.4.4
        jupyter_server_ydoc            0.8.0
        jupyter-telemetry              0.1.0
        jupyter-ydoc                   0.3.4
        jupyterhub                     4.0.2
        jupyterhub-idle-culler         1.2.1
        jupyterhub-nativeauthenticator 1.2.0
        jupyterlab                     4.0.4
        jupyterlab-language-pack-it-IT 4.0.post1
        jupyterlab-pygments            0.2.2
        jupyterlab_server              2.24.0
        jupyterlab-widgets             3.0.8
        Mako                           1.2.4
        MarkupSafe                     2.1.3
        matplotlib-inline              0.1.6
        mistune                        3.0.1
        nbclassic                      1.0.0
        nbclient                       0.8.0
        nbconvert                      7.7.3
        nbformat                       5.9.2
        nest-asyncio                   1.5.7
        notebook                       7.0.2
        notebook_shim                  0.2.3
        oauthlib                       3.2.2
        onetimepass                    1.0.1
        overrides                      7.4.0
        packaging                      23.1
        pamela                         1.1.0
        pandocfilters                  1.5.0
        parso                          0.8.3
        pexpect                        4.8.0
        pickleshare                    0.7.5
        pip                            23.2.1
        platformdirs                   3.10.0
        prometheus-client              0.17.1
        prompt-toolkit                 3.0.39
        psutil                         5.9.5
        ptyprocess                     0.7.0
        pure-eval                      0.2.2
        pycparser                      2.21
        pycurl                         7.45.2
        Pygments                       2.16.1
        pyOpenSSL                      23.2.0
        python-dateutil                2.8.2
        python-json-logger             2.0.7
        PyYAML                         6.0.1
        pyzmq                          25.1.1
        referencing                    0.30.2
        requests                       2.31.0
        rfc3339-validator              0.1.4
        rfc3986-validator              0.1.1
        rpds-py                        0.9.2
        ruamel.yaml                    0.17.32
        ruamel.yaml.clib               0.2.7
        Send2Trash                     1.8.2
        setuptools                     65.5.0
        six                            1.16.0
        sniffio                        1.3.0
        soupsieve                      2.4.1
        SQLAlchemy                     2.0.19
        stack-data                     0.6.2
        sudospawner                    0.5.2
        terminado                      0.17.1
        tinycss2                       1.2.1
        tornado                        6.3.3
        traitlets                      5.9.0
        typing_extensions              4.7.1
        uri-template                   1.3.0
        urllib3                        2.0.4
        wcwidth                        0.2.6
        webcolors                      1.13
        webencodings                   0.5.1
        websocket-client               1.6.1
        wheel                          0.41.0
        widgetsnbextension             4.0.8
        y-py                           0.6.0
        ypy-websocket                  0.8.4
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 2023-08-11 20:10:39.857 ServerApp] Searching ['/root/.jupyter', '/opt/jupyterhub/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2023-08-11 20:10:39.858 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2023-08-11 20:10:39.858 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2023-08-11 20:10:39.858 ServerApp] Looking for jupyter_config in /opt/jupyterhub/etc/jupyter
[D 2023-08-11 20:10:39.858 ServerApp] Looking for jupyter_config in /root/.jupyter
[D 2023-08-11 20:10:39.859 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2023-08-11 20:10:39.860 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2023-08-11 20:10:39.860 ServerApp] Looking for jupyter_server_config in /opt/jupyterhub/etc/jupyter
[D 2023-08-11 20:10:39.860 ServerApp] Looking for jupyter_server_config in /root/.jupyter
[D 2023-08-11 20:10:39.864 ServerApp] Paths used for configuration of jupyter_server_config: 
        /etc/jupyter/jupyter_server_config.json
[D 2023-08-11 20:10:39.864 ServerApp] Paths used for configuration of jupyter_server_config: 
        /usr/local/etc/jupyter/jupyter_server_config.json
[D 2023-08-11 20:10:39.865 ServerApp] Paths used for configuration of jupyter_server_config: 
        /opt/jupyterhub/etc/jupyter/jupyter_server_config.d/jupyter-lsp-jupyter-server.json
        /opt/jupyterhub/etc/jupyter/jupyter_server_config.d/jupyter_server_fileid.json
        /opt/jupyterhub/etc/jupyter/jupyter_server_config.d/jupyter_server_terminals.json
        /opt/jupyterhub/etc/jupyter/jupyter_server_config.d/jupyter_server_ydoc.json
        /opt/jupyterhub/etc/jupyter/jupyter_server_config.d/jupyterlab.json
        /opt/jupyterhub/etc/jupyter/jupyter_server_config.d/nbclassic.json
        /opt/jupyterhub/etc/jupyter/jupyter_server_config.d/notebook.json
        /opt/jupyterhub/etc/jupyter/jupyter_server_config.d/notebook_shim.json
        /opt/jupyterhub/etc/jupyter/jupyter_server_config.json
[D 2023-08-11 20:10:39.865 ServerApp] Paths used for configuration of jupyter_server_config: 
        /root/.jupyter/jupyter_server_config.json
[I 2023-08-11 20:10:39.879 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-08-11 20:10:39.897 ServerApp] Package jupyter_lsp took 0.0171s to import
[W 2023-08-11 20:10:39.897 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-11 20:10:39.902 ServerApp] Package jupyter_server_fileid took 0.0034s to import
[I 2023-08-11 20:10:39.908 ServerApp] Package jupyter_server_terminals took 0.0060s to import
[I 2023-08-11 20:10:39.934 ServerApp] Package jupyter_server_ydoc took 0.0252s to import
[I 2023-08-11 20:10:39.937 ServerApp] Package nbclassic took 0.0024s to import
[W 2023-08-11 20:10:39.940 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-11 20:10:39.940 ServerApp] Package notebook took 0.0000s to import
[I 2023-08-11 20:10:39.943 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-08-11 20:10:39.943 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-11 20:10:39.944 ServerApp] jupyter_lsp | extension was successfully linked.
[D 2023-08-11 20:10:39.949 FileIdExtension] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue {'update': {'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook': True, 'notebook_shim': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2023-08-11 20:10:39.950 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-08-11 20:10:39.951 ServerApp] jupyter_server_fileid | extension was successfully linked.
[D 2023-08-11 20:10:39.956 TerminalsExtensionApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2023-08-11 20:10:39.957 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-08-11 20:10:39.958 ServerApp] jupyter_server_terminals | extension was successfully linked.
[D 2023-08-11 20:10:39.963 YDocExtension] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2023-08-11 20:10:39.964 ServerApp] Config changed: {'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-08-11 20:10:39.965 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[D 2023-08-11 20:10:39.971 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-08-11 20:10:39.972 ServerApp] jupyterlab | extension was successfully linked.
[D 2023-08-11 20:10:39.977 NotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-08-11 20:10:39.978 ServerApp] nbclassic | extension was successfully linked.
[D 2023-08-11 20:10:39.984 JupyterNotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook': True, 'notebook_shim': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2023-08-11 20:10:39.985 ServerApp] notebook | extension was successfully linked.
[I 2023-08-11 20:10:39.988 ServerApp] Writing Jupyter server cookie secret to /root/.local/share/jupyter/runtime/jupyter_cookie_secret
[D 2023-08-11 20:10:40.273 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /root/.jupyter/jupyter_notebook_config.json
[D 2023-08-11 20:10:40.274 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /etc/jupyter/jupyter_notebook_config.json
[D 2023-08-11 20:10:40.274 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2023-08-11 20:10:40.275 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /opt/jupyterhub/etc/jupyter/jupyter_notebook_config.d/jupyter-lsp-notebook.json
        /opt/jupyterhub/etc/jupyter/jupyter_notebook_config.d/jupyter_server_ydoc.json
        /opt/jupyterhub/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
        /opt/jupyterhub/etc/jupyter/jupyter_notebook_config.json
[D 2023-08-11 20:10:40.275 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /root/.jupyter/jupyter_notebook_config.json
[I 2023-08-11 20:10:40.275 ServerApp] notebook_shim | extension was successfully linked.
[D 2023-08-11 20:10:40.277 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'jupyter_lsp': True, 'jupyter_server_fileid': True, 'jupyter_server_terminals': True, 'jupyter_server_ydoc': True, 'nbclassic': True, 'notebook': True, 'notebook_shim': True}>}}
[D 2023-08-11 20:10:40.277 ServerApp] Raising open file limit: soft 1024->4096; hard 4096->4096
[I 2023-08-11 20:10:40.299 ServerApp] notebook_shim | extension was successfully loaded.
[D 2023-08-11 20:10:40.301 ServerApp] [lsp] rootUri will be file:///home/prova
[D 2023-08-11 20:10:40.301 ServerApp] [lsp] virtualDocumentsUri will be file:///home/prova/.virtual_documents
[I 2023-08-11 20:10:40.302 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-08-11 20:10:40.302 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-08-11 20:10:40.302 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /home/prova
[I 2023-08-11 20:10:40.303 FileIdExtension] ArbitraryFileIdManager : Configured database path: /root/.local/share/jupyter/file_id_manager.db
[I 2023-08-11 20:10:40.303 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-08-11 20:10:40.303 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2023-08-11 20:10:41.424 FileIdExtension] Attached event listeners.
[I 2023-08-11 20:10:41.424 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-08-11 20:10:41.425 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-08-11 20:10:41.426 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2023-08-11 20:10:41.428 LabApp] JupyterLab extension loaded from /opt/jupyterhub/lib/python3.11/site-packages/jupyterlab
[I 2023-08-11 20:10:41.428 LabApp] JupyterLab application directory is /opt/jupyterhub/share/jupyter/lab
[I 2023-08-11 20:10:41.428 LabApp] Extension Manager is 'pypi'.
[D 2023-08-11 20:10:41.429 LabApp] Extensions list will be fetched from https://pypi.org/pypi.
[I 2023-08-11 20:10:41.432 ServerApp] jupyterlab | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2023-08-11 20:10:41.436 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-08-11 20:10:41.439 ServerApp] notebook | extension was successfully loaded.
[C 2023-08-11 20:10:41.439 ServerApp] Running as root is not recommended. Use --allow-root to bypass.
[D 2023-08-11 20:10:41.439 ServerApp] Exiting application: jupyter-server
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Uncaught (in promise) TypeError: e is undefined
    Ie toc.js:486
    s toc.js:394
    s toc.js:392
    c toc.js:453
    m index.es6.js:555
    l index.es6.js:513
    emit index.es6.js:112
    _onCellInViewportChanged widget.js:647
    m index.es6.js:555
    l index.es6.js:513
    emit index.es6.js:112
    set inViewport widget.js:164
    attachWidget windowing.js:187
    insertWidget index.es6.js:2516
    _updateForDeferMode widget.js:753
    _runOnIdleTime widget.js:722
    _runOnIdleTime widget.js:738
toc.js:486:8

TypeError: l is undefined
    k index.js:123
    React 7
    S scheduler.production.min.js:13
    P scheduler.production.min.js:14
react-dom.production.min.js:189:29
Uncaught TypeError: l is undefined
    k index.js:123
    React 7
        $u
        rc
        $s
        Qs
        Ws
        Ls
        Ts
    S scheduler.production.min.js:13
    P scheduler.production.min.js:14
index.js:123:52

![Istantanea_2023-08-11_20-16-00](https://github.com/jupyterlab/jupyterlab/assets/99129760/20d3f359-316d-4a46-9ed4-95c595dcd34f)

</pre>
</details>

**Comment by jtpio** [comment]
cc @afshin as this may be related to https://github.com/jupyterlab/jupyterlab/pull/13792?

**Comment by josemvas** [comment]
This bug is also present in JupyterLab 4.0.5

**Comment by afshin** [comment]
This sounds like a rendering issue where perhaps there is no fallback if there's no icon. Thanks for the reproducibility instructions.

**Comment by paolocarinci** [comment]
@jtpio take a look at this one, I wrote it after looking at my browser's console. I was unable to test it (it seems that the eidt I did to the TSX file isn't served to the browser), but I hope it helps (at least to mitigate the issue).
Let us know please

``` --- packages/running/src/index.tsx      2023-09-14 14:54:50.000000000 +0200
+++ packages/running/src/index.tsx.mod  2023-09-16 12:04:39.180027989 +0200
@@ -192,7 +192,7 @@
             ) : (
               <caretDownIcon.react tag="span" stylesheet="runningItem" />
             ))}
-          {typeof icon === 'string' ? (
+          {(icon && typeof icon === 'string') ? (
             icon ? (
               <img src={icon} />
             ) : undefined
```

**Comment by potoo0** [comment]
still present in JupyterLab 4.0.10 if no icon.

**Comment by paolocarinci** [comment]
This should do the trick. Check it out and let me know if it fixes the issue
```
diff --git a/packages/running/src/index.tsx b/packages/running/src/index.tsx
index 376d97a072..5a036fd106 100644
--- a/packages/running/src/index.tsx
+++ b/packages/running/src/index.tsx
@@ -192,13 +192,13 @@ function Item(props: {
             ) : (
               <caretDownIcon.react tag="span" stylesheet="runningItem" />
             ))}
-          {typeof icon === 'string' ? (
-            icon ? (
+          {icon ? (
+            typeof icon === 'string' ? (
               <img src={icon} />
-            ) : undefined
-          ) : (
-            <icon.react tag="span" stylesheet="runningItem" />
-          )}
+            ) : (
+              <icon.react tag="span" stylesheet="runningItem" />
+            ) 
+          ) : undefined}
           <span
             className={ITEM_LABEL_CLASS}
             title={title}
```
