### ISSUE TITLE
Jupyterlab (>=4.0.0) cannot connect to remote kernels (via a kernel gateway).

### ISSUE THREAD

**Issue by ojarjur** [jupyterlab/jupyterlab#14977]
## Description

The 4.0 release branch for the `jupyterlab` project breaks the usage of remote kernels via a kernel gateway.

The remote kernels will be visible in the Jupyterlab launcher and new notebooks can be created using them, but the kernel status showas as "Unknown" forever and no code cells can be run.

![image](https://github.com/jupyterlab/jupyterlab/assets/3039877/387f5252-6d63-4215-ae95-6f2ae028a27a)

## Reproduce

To make these reproduction steps as simple as possible, we run a local instance of `jupyter server` and use it as if it were a kernel gateway server:

1. Setup the clean test environment following the issue reporting guide:
    ```sh
    conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c nodefaults jupyterlab
    conda activate jlab-test
    ```
2. Start a `jupyter server` instance to act as the backend (e.g. as a kernel gateway):
    ```sh
    export JUPYTER_TOKEN=$(uuidgen)
    jupyter server --port=12345 --port-retries=0 --ServerApp.token=${JUPYTER_TOKEN} &
    ```
3. Run the frontend Jupyter instance connected to that backend:
    ```sh
    jupyter lab --GatewayClient.url=http://localhost:12345 --GatewayClient.auth_token="${JUPYTER_TOKEN}"
    ```
4. Open the web UI for that newly launched server and create new new notebook.
5. Observe that the newly created notebook cannot execute any code and the kernel status is reported as "Unknown":
![image](https://github.com/jupyterlab/jupyterlab/assets/3039877/387f5252-6d63-4215-ae95-6f2ae028a27a)
6. Downgrade the `jupyterlab` package to `3.6.0`:
    ```sh
    pip install jupyterlab==3.6.0
    ```
7. Try steps 3-5 again and observe that this time it works (The kernel status is `Idle` and code cells can be executed).

## Expected behavior

The notebook status should show as `Idle` and code cells should be able to be executed.

## Context

- Operating System and version: ChromeOS
- Browser and version: Google Chrome Version 115.0.5790.160
- JupyterLab version: 4.0+

**Comment by krassowski** [comment]
My first guess (possibly incorrect) would be that this is down to jupyter-server version, not JupyterLab itself. Can you check which version jupyter-server version gets installed in JupyterLab 4 and 3.x scenarios and if that could be the culprit?

**Comment by ojarjur** [comment]
I found the root cause; it's an instance of https://github.com/jupyter-server/jupyter_server/issues/1310

More specifically, adding the `--GatewayWebSocketConnection.kernel_ws_protocol=""` flag to the `jupyter lab` command fixes the problem.

**Comment by ojarjur** [comment]
Since this is already reported in the jupyter_server project and is arguably a bug in that codebase rather than this one, I'll close this.

**Comment by krassowski** [comment]
Thank you for listing the workaround and linking to the upstream issue!
