### ISSUE TITLE
Multiline input in Console

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#1497]
Expecting the typical iPython behaviour, I tried typing a multiline statement
```
if 1 == 2:
    print("bad")
else:
    print("good")
```
But,
1. It tried to execute the very first line, and
2. It wouldn't indent the second line

Note that `ctrl+enter` works though.

**Comment by blink1073** [comment]
Hi @rsinha25, thank you, it looks like we need to check for code [completeness](https://github.com/jupyterlab/services/blob/782b9170d3e60524ac8459b6cc8db43b222f9053/src/kernel/default.ts#L510) prior to sending an execution request in the console.

**Comment by blink1073** [comment]
Hi @rsinha25, I'm seeing the correct behavior in v0.12.1 and current master, can you please give more information about your setup?  `jupyter lab --version`, Operating System, and browser version.  I'm guessing that our 250ms delay for checking the code completeness may be too short, and the connection to your server is slower than mine (perhaps not a local server)?

**Comment by rsinha25** [comment]
I don't think its a completeness problem. I am running it on my local machine with 0.12.1 on a mac with chrome.

Here's what I'm seeing in python console:
 - When I open a python console and in the cell at the bottom, I type `if 1==2: <enter>` Then it does not run and it correctly goes to the next line with four spaces.
 - When I open a python console and in the cell at the bottom, I type `if 1==2: <shift+enter>` Then it tries to run the code (and throws EOF error).

Now, comparing it with the ipython terminal:
 - When I open the terminal and run `ipython` in the bash shell and type there `if 1==2: <enter>` Then it does not run and it correctly goes to the next line with four spaces (Same as python console)
 - When I open the terminal and run `ipython` in the bash shell and type there `if 1==2: <shift+enter>` Then it still does not run and goes to the next line with four spaces (Different from python console)

I was wondering if this was expected behaviour, because some ipython users are normally used to typing <shift+enter> to move to next line and this may be inconvenient.

**Comment by blink1073** [comment]
I would say this is the intended behavior.  `Shift-Enter` shows a different intent than `Enter`, and this is consistent with the `QtConsole` behavior:

![image](https://cloud.githubusercontent.com/assets/2096628/22076285/0e070cee-dd75-11e6-984b-a4c7c49e5e18.png)

**Comment by rsinha25** [comment]
Ah, thanks. Sorry for the confusion.
