### ISSUE TITLE
How to change the jupyter lab host in Pytorch:23.07 image

### ISSUE THREAD

**Issue by ElinLiu0** [jupyterlab/jupyterlab#14976]
## Reproduce

- Pull the Pytorch:23.07 image from NGC （NVIDIA GPU Container）
- run bellow docker command to launch jupyter lab:
```bash
docker run --rm -it --gpus 1 pytorch jupyter lab --allow-root --ip=* --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.allow_origin='*' --notebook-dir=/workspace
```
- check out the output log

## Expected behavior

The jupyter lab URL should be spawn like `http://localhost:8888`,but got `http://hostname:8888`

## Context

- Operating System and version: Uknown from container
- Browser and version: 115.0.5790.171(Chrome)
- JupyterLab version: 2.3.2 (from jupyterlab.__version__)

<details><summary>Troubleshoot Output</summary>
<pre>
None,this container's jupyter lab is fine
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
=============
== PyTorch ==
=============

NVIDIA Release 23.07 (build 63867923)
PyTorch Version 2.1.0a0+b5021ba

Container image Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Copyright (c) 2014-2023 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for PyTorch.  NVIDIA recommends the use of the following flags:
   docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 ...

[I 13:54:07.793 LabApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 13:54:08.278 LabApp] jupyter_tensorboard extension loaded.
[I 13:54:08.282 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.10/dist-packages/jupyterlab
[I 13:54:08.282 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 13:54:08.284 LabApp] [Jupytext Server Extension] NotebookApp.contents_manager_class is (a subclass of) jupytext.TextFileContentsManager already - OK
[I 13:54:08.287 LabApp] Serving notebooks from local directory: /workspace
[I 13:54:08.287 LabApp] Jupyter Notebook 6.4.10 is running at:
[I 13:54:08.287 LabApp] http://hostname:8888/?token=2a586a1d1fa6102d0576507d2201f5dc5ab6edf53a1a5836
[I 13:54:08.287 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:54:08.289 LabApp]

    To access the notebook, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/nbserver-1-open.html
    Or copy and paste this URL:
        http://`hostname`:8888/?token=2a586a1d1fa6102d0576507d2201f5dc5ab6edf53a1a5836

</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
None,on server side.

</pre>
</details>

**Comment by JasonWeill** [comment]
@ElinLiu0 Thanks for your contribution! This repository is for the JupyterLab project. We do not maintain the Nvidia Docker image that you're using, and JupyterLab version 2 is no longer maintained. You will need to contact the maintainers of that Docker image to get help with it. I do not have this contact information, but it may be present in the README or other documentation of the Docker image you used.
