### ISSUE TITLE
Remove timeout during settings transformation

### ISSUE THREAD

**Issue by brichet** [jupyterlab/jupyterlab#14988]
When Jupyterlab starts up, nothing seems to happen for a second.

![image](https://github.com/jupyterlab/jupyterlab/assets/32258950/466d302b-bff9-43a8-b57f-7ac6d2917b7f)

This delay is due to plugin transform (thanks to @fcollonval for discovering this), which contains a 1s timeout waiting for an available transform function.

https://github.com/jupyterlab/jupyterlab/blob/1441c45888b91840a02a489557743e866329477b/packages/settingregistry/src/settingregistry.ts#L685-L693

with a `timeout` value set to 1000ms:

https://github.com/jupyterlab/jupyterlab/blob/1441c45888b91840a02a489557743e866329477b/packages/settingregistry/src/settingregistry.ts#L46

### Problem

This delay occurs during the preloading of the plugins:

https://github.com/jupyterlab/jupyterlab/blob/1441c45888b91840a02a489557743e866329477b/packages/settingregistry/src/settingregistry.ts#L606

At this stage, none of the transform functions are registered, and it seems that all plugins are waiting for the `settingsRegistry` to be "preloaded" before registering the transform functions.
The consequence is that the deadline is always reached for every plugin containing a transform function, at least for the core plugins.

### Proposed Solution

I think we can do away the timeout concept (and the associated loop). In practice, it is never used except during preloading (where the timeout is reached).

- if the transform function is already registered during preloading, this function will be played as expected.
- if the transform function is not registered during preload, the plugin will remain in the `_unloadedPlugins` map, and the transform function will be played the next time `load()` is called, after registration (see <a href=https://github.com/jupyterlab/jupyterlab/blob/1441c45888b91840a02a489557743e866329477b/packages/settingregistry/src/settingregistry.ts#L394-L403>settingregistry.ts#L394-L403</a>).

### Additional context

Here is the performance chart after applying the proposed solution (no more gap), with no consequence as far as I know:

![image](https://github.com/jupyterlab/jupyterlab/assets/32258950/6d75ce38-3754-4ec0-b144-b3e0f0df7cb7)

cc. @fcollonval, @afshin, @mlucool

**Comment by fcollonval** [comment]
Thanks @brichet for investigating - yes dropping it sounds reasonable.

**Comment by krassowski** [comment]
Long time ago it used to be 7 seconds in 1.0 era (https://github.com/jupyterlab/jupyterlab/pull/5470). I was hitting this timeout in the LSP extension when implementing [settings UI](https://github.com/jupyter-lsp/jupyterlab-lsp/pull/778#issue-1174573331) with result ofplugin randomly not activating which is why LSP extension manually transforms its settings later, see https://github.com/jupyter-lsp/jupyterlab-lsp/pull/778/commits/00375bacca2bfdd1cc5ed9ecfc437d362fa601d3. This might no longer be a problem with https://github.com/jupyterlab/jupyterlab/pull/14610 in. I think I am in favour of removing the timeout, but just want to stress that it is not that it is never reached.

A closely related bug is the issue of the validation cache being sticky:
- https://github.com/jupyterlab/jupyterlab/issues/12978

Just for context, LSP really does have a lot of settings, so this taking over 1 second is not unexpected:

![demo](https://user-images.githubusercontent.com/5832902/175795085-a642e04c-2473-4245-b992-4b0c909e2477.gif)

**Comment by brichet** [comment]
Thanks @krassowski for your feedback.
Maybe I did not understand correctly your comment, but this timeout is not about the time to load the settings itself, but about the time to wait for the transform function to be registered.
Removing it should not affect the time to execute the transform function.

For the LSP extension (for example), the process should be:
- loading of `settingsRegistry`, the LSP extension is known as containing transform function, and is appended to the `_unloadedPlugins` map (<a href=https://github.com/jupyterlab/jupyterlab/blob/1441c45888b91840a02a489557743e866329477b/packages/settingregistry/src/settingregistry.ts#L289-L291>settingregistry.ts#L289-L291</a>). It will not wait anymore for the transform function to be registered at that stage.
- the LSP transform functions are registered (<a href=https://github.com/jupyterlab/jupyterlab/blob/1441c45888b91840a02a489557743e866329477b/packages/lsp-extension/src/index.ts#L156>lsp-extension/src/index.ts#L156</a>) and the settings are loaded (<a href=https://github.com/jupyterlab/jupyterlab/blob/1441c45888b91840a02a489557743e866329477b/packages/lsp-extension/src/index.ts#L201-L202>lsp-extension/src/index.ts#L201-L202</a>)
- loading the settings of an unloaded plugin will run the registered transform functions (<a href=https://github.com/jupyterlab/jupyterlab/blob/1441c45888b91840a02a489557743e866329477b/packages/settingregistry/src/settingregistry.ts#L394>settingregistry.ts#L394</a>)

**Comment by krassowski** [comment]
> Maybe I did not understand correctly your comment, but this timeout is not about the time to load the settings itself, but about the time to wait for the transform function to be registered.

Yes, this is exactly what I was referring to. The issue with LSP is that after it fetches the settings schema it has to pull the defaults from it (i.e. transform it) and then use these defaults to establish connection with servers.

> Removing it should not affect the time to execute the transform function.

Yes. In fact what I was saying was that having the timeout was problematic and I needed a workaround.

**Comment by krassowski** [comment]
Also, FYI what `packages/lsp-extension` does (your bullet points) is much simpler than the LSP extension I am referring to (https://github.com/jupyter-lsp/jupyterlab-lsp) does.
