### ISSUE TITLE
Incomplete tracebacks for ExceptionGroup

### ISSUE THREAD

**Issue by jacobj45** [jupyterlab/jupyterlab#14998]
## Description

Tracebacks for `ExceptionGroup`s are incomplete and different from when these exceptions are raised within a script.

## Reproduce

1. Run the following in a Jupyter cell:
```python
eg = ExceptionGroup(
    "one",
    [
        ValueError(111),
        TypeError(333),
    ],
)
raise eg
```

## Observed behavior

Full traceback is not present when running the above snippet from JupyterLab:

```bash
. . .
----> 8 raise eg

ExceptionGroup: one (2 sub-exceptions)
```

## Expected behavior

You get the expected behaviour when running the same snippet from a Python script:

```bash
. . .
|     raise eg
  | ExceptionGroup: one (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | ValueError: 111
    +---------------- 2 ----------------
    | TypeError: 333
    +------------------------------------
```

## Context

- JupyterLab version: 4.0.5
- Python version: 3.11.4

**Comment by krassowski** [comment]
The tracebacks are generated by the kernel, in this case probably ipykernel/IPython. There was an issue about this in IPython (https://github.com/ipython/ipython/issues/13753) which was fixed but not yet released. You can try installing the latest development version of IPython if you like, but I believe this is not an issue in JupyterLab.
