### ISSUE TITLE
Extension Tutorial Bug: Copier Broken

### ISSUE THREAD

**Issue by ericsnekbytes** [jupyterlab/jupyterlab#14994]
## Description

Copier command is broken in the extension tutorial.

## Reproduce

Follow the JupyterLab Extension Tutorial, up to and including the copier command.

## Expected behavior

Copier command succeeds, no error.

## Context

- Operating System and version: MacOS 12.4

<details><summary>Troubleshoot Output</summary>
<pre>
(compat_s4) egentry@erics-mbp:~/workspace_ana/compat_sample4$ jupyter troubleshoot
$PATH:
	/opt/homebrew/bin
	/opt/homebrew/bin
	/opt/homebrew/sbin
	/Users/egentry/.cargo/bin
	/opt/homebrew/bin
	/Users/egentry/workspace_ana/armconda/envs/compat_s4/bin
	/Users/egentry/workspace_ana/armconda/condabin
	/usr/bin
	/bin
	/usr/sbin
	/sbin

sys.path:
	/Users/egentry/workspace_ana/armconda/envs/compat_s4/bin
	/Users/egentry/workspace_ana/armconda/envs/compat_s4/lib/python311.zip
	/Users/egentry/workspace_ana/armconda/envs/compat_s4/lib/python3.11
	/Users/egentry/workspace_ana/armconda/envs/compat_s4/lib/python3.11/lib-dynload
	/Users/egentry/workspace_ana/armconda/envs/compat_s4/lib/python3.11/site-packages

sys.executable:
	/Users/egentry/workspace_ana/armconda/envs/compat_s4/bin/python

sys.version:
	3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 18:08:41) [Clang 15.0.7 ]

platform.platform():
	macOS-12.4-arm64-arm-64bit

which -a jupyter:
	/Users/egentry/workspace_ana/armconda/envs/compat_s4/bin/jupyter

pip list:
	Package                       Version
	----------------------------- -----------
	anyio                         3.7.1
	appnope                       0.1.3
	argon2-cffi                   21.3.0
	argon2-cffi-bindings          21.2.0
	arrow                         1.2.3
	asttokens                     2.2.1
	async-lru                     2.0.4
	attrs                         23.1.0
	Babel                         2.12.1
	backcall                      0.2.0
	backports.functools-lru-cache 1.6.5
	bcrypt                        3.2.2
	beautifulsoup4                4.12.2
	bleach                        6.0.0
	Brotli                        1.0.9
	cached-property               1.5.2
	certifi                       2023.7.22
	cffi                          1.15.1
	charset-normalizer            3.2.0
	colorama                      0.4.6
	comm                          0.1.4
	copier                        7.2.0
	cryptography                  41.0.3
	debugpy                       1.6.8
	decorator                     5.1.1
	defusedxml                    0.7.1
	dunamai                       1.18.0
	entrypoints                   0.4
	exceptiongroup                1.1.3
	executing                     1.2.0
	fastjsonschema                2.18.0
	flit_core                     3.9.0
	fqdn                          1.5.1
	funcy                         2.0
	idna                          3.4
	importlib-metadata            6.8.0
	importlib-resources           6.0.1
	ipykernel                     6.25.1
	ipython                       8.14.0
	isoduration                   20.11.0
	jedi                          0.19.0
	Jinja2                        3.1.2
	jinja2-ansible-filters        1.3.2
	jinja2-time                   0.2.0
	json5                         0.9.14
	jsonpointer                   2.0
	jsonschema                    4.19.0
	jsonschema-specifications     2023.7.1
	jupyter_client                8.3.0
	jupyter_core                  5.3.1
	jupyter-events                0.7.0
	jupyter-lsp                   2.2.0
	jupyter_server                2.7.1
	jupyter_server_terminals      0.4.4
	jupyterlab                    4.0.5
	jupyterlab-pygments           0.2.2
	jupyterlab_server             2.24.0
	MarkupSafe                    2.1.3
	matplotlib-inline             0.1.6
	mistune                       3.0.1
	nbclient                      0.8.0
	nbconvert                     7.7.4
	nbformat                      5.9.2
	nest-asyncio                  1.5.6
	notebook_shim                 0.2.3
	overrides                     7.4.0
	packaging                     23.1
	pandocfilters                 1.5.0
	paramiko                      3.3.1
	parso                         0.8.3
	pathspec                      0.11.2
	pexpect                       4.8.0
	pickleshare                   0.7.5
	pip                           23.2.1
	pkgutil_resolve_name          1.3.10
	platformdirs                  3.10.0
	plumbum                       1.8.2
	prometheus-client             0.17.1
	prompt-toolkit                3.0.39
	psutil                        5.9.5
	ptyprocess                    0.7.0
	pure-eval                     0.2.2
	pycparser                     2.21
	pydantic                      1.10.12
	Pygments                      2.16.1
	PyNaCl                        1.5.0
	pyobjc-core                   9.2
	pyobjc-framework-Cocoa        9.2
	PySocks                       1.7.1
	python-dateutil               2.8.2
	python-json-logger            2.0.7
	pytz                          2023.3
	PyYAML                        6.0
	pyyaml-include                1.3
	pyzmq                         25.1.1
	questionary                   2.0.0
	referencing                   0.30.2
	requests                      2.31.0
	rfc3339-validator             0.1.4
	rfc3986-validator             0.1.1
	rpds-py                       0.9.2
	Send2Trash                    1.8.2
	setuptools                    68.0.0
	six                           1.16.0
	sniffio                       1.3.0
	soupsieve                     2.3.2.post1
	stack-data                    0.6.2
	terminado                     0.17.1
	tinycss2                      1.2.1
	tomli                         2.0.1
	tornado                       6.3.3
	traitlets                     5.9.0
	typing_extensions             4.7.1
	typing-utils                  0.1.0
	uri-template                  1.3.0
	urllib3                       2.0.4
	wcwidth                       0.2.6
	webcolors                     1.13
	webencodings                  0.5.1
	websocket-client              1.6.1
	wheel                         0.41.1
	zipp                          3.16.2

conda list:
	# packages in environment at /Users/egentry/workspace_ana/armconda/envs/compat_s4:
	#
	# Name                    Version                   Build  Channel
	anyio                     3.7.1              pyhd8ed1ab_0    conda-forge
	appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
	argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
	argon2-cffi-bindings      21.2.0          py311he2be06e_3    conda-forge
	arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
	asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
	async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
	attrs                     23.1.0             pyh71513ae_1    conda-forge
	babel                     2.12.1             pyhd8ed1ab_1    conda-forge
	backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
	backports                 1.0                pyhd8ed1ab_3    conda-forge
	backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
	bcrypt                    3.2.2           py311he2be06e_1    conda-forge
	beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
	bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
	brotli-python             1.0.9           py311ha397e9f_9    conda-forge
	bzip2                     1.0.8                h3422bc3_4    conda-forge
	c-ares                    1.19.1               hb547adb_0    conda-forge
	ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
	cached-property           1.5.2                hd8ed1ab_1    conda-forge
	cached_property           1.5.2              pyha770c72_1    conda-forge
	certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
	cffi                      1.15.1          py311hae827db_3    conda-forge
	charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
	colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
	comm                      0.1.4              pyhd8ed1ab_0    conda-forge
	copier                    7.2.0              pyhd8ed1ab_0    conda-forge
	cryptography              41.0.3          py311h5fb2c35_0    conda-forge
	curl                      8.2.1                hc52a3a8_0    conda-forge
	debugpy                   1.6.8           py311ha891d26_0    conda-forge
	decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
	defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
	dunamai                   1.18.0             pyhd8ed1ab_0    conda-forge
	entrypoints               0.4                pyhd8ed1ab_0    conda-forge
	exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
	executing                 1.2.0              pyhd8ed1ab_0    conda-forge
	flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
	fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
	funcy                     2.0                pyhd8ed1ab_0    conda-forge
	gettext                   0.21.1               h0186832_0    conda-forge
	git                       2.41.0          pl5321h46e2b6d_0    conda-forge
	icu                       72.1                 he12128b_0    conda-forge
	idna                      3.4                pyhd8ed1ab_0    conda-forge
	importlib-metadata        6.8.0              pyha770c72_0    conda-forge
	importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
	importlib_resources       6.0.1              pyhd8ed1ab_0    conda-forge
	ipykernel                 6.25.1             pyh5fb750a_0    conda-forge
	ipython                   8.14.0             pyhd1c38e8_0    conda-forge
	isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
	jedi                      0.19.0             pyhd8ed1ab_0    conda-forge
	jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
	jinja2-ansible-filters    1.3.2              pyhd8ed1ab_0    conda-forge
	jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
	json5                     0.9.14             pyhd8ed1ab_0    conda-forge
	jsonpointer               2.0                        py_0    conda-forge
	jsonschema                4.19.0             pyhd8ed1ab_1    conda-forge
	jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
	jsonschema-with-format-nongpl 4.19.0             pyhd8ed1ab_1    conda-forge
	jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
	jupyter_client            8.3.0              pyhd8ed1ab_0    conda-forge
	jupyter_core              5.3.1           py311h267d04e_0    conda-forge
	jupyter_events            0.7.0              pyhd8ed1ab_2    conda-forge
	jupyter_server            2.7.1              pyhd8ed1ab_0    conda-forge
	jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
	jupyterlab                4.0.5              pyhd8ed1ab_0    conda-forge
	jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
	jupyterlab_server         2.24.0             pyhd8ed1ab_0    conda-forge
	krb5                      1.21.2               h92f50d5_0    conda-forge
	libcurl                   8.2.1                hc52a3a8_0    conda-forge
	libcxx                    16.0.6               h4653b0c_0    conda-forge
	libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
	libev                     4.33                 h642e427_1    conda-forge
	libexpat                  2.5.0                hb7217d7_1    conda-forge
	libffi                    3.4.2                h3422bc3_5    conda-forge
	libiconv                  1.17                 he4db4b2_0    conda-forge
	libnghttp2                1.52.0               hae82a92_0    conda-forge
	libsodium                 1.0.18               h27ca646_1    conda-forge
	libsqlite                 3.42.0               hb31c410_0    conda-forge
	libssh2                   1.11.0               h7a5bd25_0    conda-forge
	libuv                     1.44.2               hb547adb_1    conda-forge
	libzlib                   1.2.13               h53f4e23_5    conda-forge
	markupsafe                2.1.3           py311heffc1b2_0    conda-forge
	matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
	mistune                   3.0.1              pyhd8ed1ab_0    conda-forge
	nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
	nbconvert-core            7.7.4              pyhd8ed1ab_0    conda-forge
	nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
	ncurses                   6.4                  h7ea286d_0    conda-forge
	nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
	nodejs                    18.16.1              ha2ed473_0    conda-forge
	notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
	openssl                   3.1.2                h53f4e23_0    conda-forge
	overrides                 7.4.0              pyhd8ed1ab_0    conda-forge
	packaging                 23.1               pyhd8ed1ab_0    conda-forge
	pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
	paramiko                  3.3.1              pyhd8ed1ab_0    conda-forge
	parso                     0.8.3              pyhd8ed1ab_0    conda-forge
	pathspec                  0.11.2             pyhd8ed1ab_0    conda-forge
	pcre2                     10.40                hb34f9b4_0    conda-forge
	perl                      5.32.1          4_hf2054a2_perl5    conda-forge
	pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
	pickleshare               0.7.5                   py_1003    conda-forge
	pip                       23.2.1             pyhd8ed1ab_0    conda-forge
	pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
	platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
	plumbum                   1.8.2              pyhd8ed1ab_0    conda-forge
	prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
	prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
	prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
	psutil                    5.9.5           py311he2be06e_0    conda-forge
	ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
	pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
	pycparser                 2.21               pyhd8ed1ab_0    conda-forge
	pydantic                  1.10.12         py311heffc1b2_1    conda-forge
	pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
	pynacl                    1.5.0           py311he2be06e_2    conda-forge
	pyobjc-core               9.2             py311hb702dc4_0    conda-forge
	pyobjc-framework-cocoa    9.2             py311hb702dc4_0    conda-forge
	pysocks                   1.7.1              pyha2e5f31_6    conda-forge
	python                    3.11.4          h47c9636_0_cpython    conda-forge
	python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
	python-fastjsonschema     2.18.0             pyhd8ed1ab_0    conda-forge
	python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
	python_abi                3.11                    3_cp311    conda-forge
	pytz                      2023.3             pyhd8ed1ab_0    conda-forge
	pywin32-on-windows        0.1.0              pyh1179c8e_3    conda-forge
	pyyaml                    6.0             py311he2be06e_5    conda-forge
	pyyaml-include            1.3                pyhd8ed1ab_0    conda-forge
	pyzmq                     25.1.1          py311hb1af645_0    conda-forge
	questionary               2.0.0              pyhd8ed1ab_0    conda-forge
	readline                  8.2                  h92ec313_1    conda-forge
	referencing               0.30.2             pyhd8ed1ab_0    conda-forge
	requests                  2.31.0             pyhd8ed1ab_0    conda-forge
	rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
	rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
	rpds-py                   0.9.2           py311h0563b04_0    conda-forge
	send2trash                1.8.2              pyhd1c38e8_0    conda-forge
	setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
	six                       1.16.0             pyh6c4a22f_0    conda-forge
	sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
	soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
	sqlite                    3.42.0               h203b68d_0    conda-forge
	stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
	terminado                 0.17.1             pyhd1c38e8_0    conda-forge
	tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
	tk                        8.6.12               he1e0b03_0    conda-forge
	tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
	tornado                   6.3.3           py311heffc1b2_0    conda-forge
	traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
	typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
	typing_extensions         4.7.1              pyha770c72_0    conda-forge
	typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
	tzdata                    2023c                h71feb2d_0    conda-forge
	uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
	urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
	wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
	webcolors                 1.13               pyhd8ed1ab_0    conda-forge
	webencodings              0.5.1                      py_1    conda-forge
	websocket-client          1.6.1              pyhd8ed1ab_0    conda-forge
	wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
	xz                        5.2.6                h57fd34a_0    conda-forge
	yaml                      0.2.5                h3422bc3_2    conda-forge
	zeromq                    4.3.4                hbdafb3b_1    conda-forge
	zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
	zlib                      1.2.13               h53f4e23_5    conda-forge
	zstd                      1.5.2                h4f39d0f_7    conda-forge

conda env:
	name: compat_s4
	channels:
	  - conda-forge
	  - defaults
	dependencies:
	  - anyio=3.7.1=pyhd8ed1ab_0
	  - appnope=0.1.3=pyhd8ed1ab_0
	  - argon2-cffi=21.3.0=pyhd8ed1ab_0
	  - argon2-cffi-bindings=21.2.0=py311he2be06e_3
	  - arrow=1.2.3=pyhd8ed1ab_0
	  - asttokens=2.2.1=pyhd8ed1ab_0
	  - async-lru=2.0.4=pyhd8ed1ab_0
	  - attrs=23.1.0=pyh71513ae_1
	  - babel=2.12.1=pyhd8ed1ab_1
	  - backcall=0.2.0=pyh9f0ad1d_0
	  - backports=1.0=pyhd8ed1ab_3
	  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
	  - bcrypt=3.2.2=py311he2be06e_1
	  - beautifulsoup4=4.12.2=pyha770c72_0
	  - bleach=6.0.0=pyhd8ed1ab_0
	  - brotli-python=1.0.9=py311ha397e9f_9
	  - bzip2=1.0.8=h3422bc3_4
	  - c-ares=1.19.1=hb547adb_0
	  - ca-certificates=2023.7.22=hf0a4a13_0
	  - cached-property=1.5.2=hd8ed1ab_1
	  - cached_property=1.5.2=pyha770c72_1
	  - certifi=2023.7.22=pyhd8ed1ab_0
	  - cffi=1.15.1=py311hae827db_3
	  - charset-normalizer=3.2.0=pyhd8ed1ab_0
	  - colorama=0.4.6=pyhd8ed1ab_0
	  - comm=0.1.4=pyhd8ed1ab_0
	  - copier=7.2.0=pyhd8ed1ab_0
	  - cryptography=41.0.3=py311h5fb2c35_0
	  - curl=8.2.1=hc52a3a8_0
	  - debugpy=1.6.8=py311ha891d26_0
	  - decorator=5.1.1=pyhd8ed1ab_0
	  - defusedxml=0.7.1=pyhd8ed1ab_0
	  - dunamai=1.18.0=pyhd8ed1ab_0
	  - entrypoints=0.4=pyhd8ed1ab_0
	  - exceptiongroup=1.1.3=pyhd8ed1ab_0
	  - executing=1.2.0=pyhd8ed1ab_0
	  - flit-core=3.9.0=pyhd8ed1ab_0
	  - fqdn=1.5.1=pyhd8ed1ab_0
	  - funcy=2.0=pyhd8ed1ab_0
	  - gettext=0.21.1=h0186832_0
	  - git=2.41.0=pl5321h46e2b6d_0
	  - icu=72.1=he12128b_0
	  - idna=3.4=pyhd8ed1ab_0
	  - importlib-metadata=6.8.0=pyha770c72_0
	  - importlib_metadata=6.8.0=hd8ed1ab_0
	  - importlib_resources=6.0.1=pyhd8ed1ab_0
	  - ipykernel=6.25.1=pyh5fb750a_0
	  - ipython=8.14.0=pyhd1c38e8_0
	  - isoduration=20.11.0=pyhd8ed1ab_0
	  - jedi=0.19.0=pyhd8ed1ab_0
	  - jinja2=3.1.2=pyhd8ed1ab_1
	  - jinja2-ansible-filters=1.3.2=pyhd8ed1ab_0
	  - jinja2-time=0.2.0=pyhd8ed1ab_3
	  - json5=0.9.14=pyhd8ed1ab_0
	  - jsonpointer=2.0=py_0
	  - jsonschema=4.19.0=pyhd8ed1ab_1
	  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
	  - jsonschema-with-format-nongpl=4.19.0=pyhd8ed1ab_1
	  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
	  - jupyter_client=8.3.0=pyhd8ed1ab_0
	  - jupyter_core=5.3.1=py311h267d04e_0
	  - jupyter_events=0.7.0=pyhd8ed1ab_2
	  - jupyter_server=2.7.1=pyhd8ed1ab_0
	  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
	  - jupyterlab=4.0.5=pyhd8ed1ab_0
	  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
	  - jupyterlab_server=2.24.0=pyhd8ed1ab_0
	  - krb5=1.21.2=h92f50d5_0
	  - libcurl=8.2.1=hc52a3a8_0
	  - libcxx=16.0.6=h4653b0c_0
	  - libedit=3.1.20191231=hc8eb9b7_2
	  - libev=4.33=h642e427_1
	  - libexpat=2.5.0=hb7217d7_1
	  - libffi=3.4.2=h3422bc3_5
	  - libiconv=1.17=he4db4b2_0
	  - libnghttp2=1.52.0=hae82a92_0
	  - libsodium=1.0.18=h27ca646_1
	  - libsqlite=3.42.0=hb31c410_0
	  - libssh2=1.11.0=h7a5bd25_0
	  - libuv=1.44.2=hb547adb_1
	  - libzlib=1.2.13=h53f4e23_5
	  - markupsafe=2.1.3=py311heffc1b2_0
	  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
	  - mistune=3.0.1=pyhd8ed1ab_0
	  - nbclient=0.8.0=pyhd8ed1ab_0
	  - nbconvert-core=7.7.4=pyhd8ed1ab_0
	  - nbformat=5.9.2=pyhd8ed1ab_0
	  - ncurses=6.4=h7ea286d_0
	  - nest-asyncio=1.5.6=pyhd8ed1ab_0
	  - nodejs=18.16.1=ha2ed473_0
	  - notebook-shim=0.2.3=pyhd8ed1ab_0
	  - openssl=3.1.2=h53f4e23_0
	  - overrides=7.4.0=pyhd8ed1ab_0
	  - packaging=23.1=pyhd8ed1ab_0
	  - pandocfilters=1.5.0=pyhd8ed1ab_0
	  - paramiko=3.3.1=pyhd8ed1ab_0
	  - parso=0.8.3=pyhd8ed1ab_0
	  - pathspec=0.11.2=pyhd8ed1ab_0
	  - pcre2=10.40=hb34f9b4_0
	  - perl=5.32.1=4_hf2054a2_perl5
	  - pexpect=4.8.0=pyh1a96a4e_2
	  - pickleshare=0.7.5=py_1003
	  - pip=23.2.1=pyhd8ed1ab_0
	  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
	  - platformdirs=3.10.0=pyhd8ed1ab_0
	  - plumbum=1.8.2=pyhd8ed1ab_0
	  - prometheus_client=0.17.1=pyhd8ed1ab_0
	  - prompt-toolkit=3.0.39=pyha770c72_0
	  - prompt_toolkit=3.0.39=hd8ed1ab_0
	  - psutil=5.9.5=py311he2be06e_0
	  - ptyprocess=0.7.0=pyhd3deb0d_0
	  - pure_eval=0.2.2=pyhd8ed1ab_0
	  - pycparser=2.21=pyhd8ed1ab_0
	  - pydantic=1.10.12=py311heffc1b2_1
	  - pygments=2.16.1=pyhd8ed1ab_0
	  - pynacl=1.5.0=py311he2be06e_2
	  - pyobjc-core=9.2=py311hb702dc4_0
	  - pyobjc-framework-cocoa=9.2=py311hb702dc4_0
	  - pysocks=1.7.1=pyha2e5f31_6
	  - python=3.11.4=h47c9636_0_cpython
	  - python-dateutil=2.8.2=pyhd8ed1ab_0
	  - python-fastjsonschema=2.18.0=pyhd8ed1ab_0
	  - python-json-logger=2.0.7=pyhd8ed1ab_0
	  - python_abi=3.11=3_cp311
	  - pytz=2023.3=pyhd8ed1ab_0
	  - pywin32-on-windows=0.1.0=pyh1179c8e_3
	  - pyyaml=6.0=py311he2be06e_5
	  - pyyaml-include=1.3=pyhd8ed1ab_0
	  - pyzmq=25.1.1=py311hb1af645_0
	  - questionary=2.0.0=pyhd8ed1ab_0
	  - readline=8.2=h92ec313_1
	  - referencing=0.30.2=pyhd8ed1ab_0
	  - requests=2.31.0=pyhd8ed1ab_0
	  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
	  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
	  - rpds-py=0.9.2=py311h0563b04_0
	  - send2trash=1.8.2=pyhd1c38e8_0
	  - setuptools=68.0.0=pyhd8ed1ab_0
	  - six=1.16.0=pyh6c4a22f_0
	  - sniffio=1.3.0=pyhd8ed1ab_0
	  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
	  - sqlite=3.42.0=h203b68d_0
	  - stack_data=0.6.2=pyhd8ed1ab_0
	  - terminado=0.17.1=pyhd1c38e8_0
	  - tinycss2=1.2.1=pyhd8ed1ab_0
	  - tk=8.6.12=he1e0b03_0
	  - tomli=2.0.1=pyhd8ed1ab_0
	  - tornado=6.3.3=py311heffc1b2_0
	  - traitlets=5.9.0=pyhd8ed1ab_0
	  - typing-extensions=4.7.1=hd8ed1ab_0
	  - typing_extensions=4.7.1=pyha770c72_0
	  - typing_utils=0.1.0=pyhd8ed1ab_0
	  - tzdata=2023c=h71feb2d_0
	  - uri-template=1.3.0=pyhd8ed1ab_0
	  - urllib3=2.0.4=pyhd8ed1ab_0
	  - wcwidth=0.2.6=pyhd8ed1ab_0
	  - webcolors=1.13=pyhd8ed1ab_0
	  - webencodings=0.5.1=py_1
	  - websocket-client=1.6.1=pyhd8ed1ab_0
	  - wheel=0.41.1=pyhd8ed1ab_0
	  - xz=5.2.6=h57fd34a_0
	  - yaml=0.2.5=h3422bc3_2
	  - zeromq=4.3.4=hbdafb3b_1
	  - zipp=3.16.2=pyhd8ed1ab_0
	  - zlib=1.2.13=h53f4e23_5
	  - zstd=1.5.2=h4f39d0f_7
	prefix: /Users/egentry/workspace_ana/armconda/envs/compat_s4
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
(compat_s4) egentry@erics-mbp:~/workspace_ana/compat_sample4$ copier copy --UNSAFE https://github.com/jupyterlab/extension-template .
Error: Unknown switch --UNSAFE
------
copier copy 7.2.0

Copy from a template source to a destination.

Usage:
    copier copy [SWITCHES] args...

Hidden-switches:
    -h, --help            Prints this help message and quits
    --help-all            Prints help messages of all sub-commands and quits
    -v, --version         Prints the program's version and quits

Switches:
    -C, --no-cleanup      On error, do not delete destination if it was created by Copier.
</pre>
</details>

**Comment by krassowski** [comment]
Copier v8 or newer is needed to use `--UNSAFE`, and in v8.1 one can use `--trust` instead. The pin in the tutorial probably needs updating.

**Comment by krassowski** [comment]
It looks like the pin was downgraded in #14899. If we want to stick with v7 for now we should remove `--UNSAFE`.

**Comment by krassowski** [comment]
Would you like to open a PR?
