### ISSUE TITLE
`OutputArea` update error

### ISSUE THREAD

**Issue by trungleduc** [jupyterlab/jupyterlab#15004]
## Description

Due to the change in https://github.com/jupyterlab/jupyterlab/pull/14911, the logic to detect the renderer of the output panel is bugged. Since `panel.widgets` is not undefined anymore but is an array of one element, `panel.widgets[1]` is `undefined` and it triggers the below exception.

https://github.com/jupyterlab/jupyterlab/blob/0a711dc37dd9771ed094270798f7e39b8bdd8949/packages/outputarea/src/widget.ts#L484-L491
![output](https://github.com/jupyterlab/jupyterlab/assets/4451292/7ab9749a-e86a-4d20-853d-c9518d91dad3)

## Reproduce

1. Add a cell with the following code:
```python
print('hello')
sleep(1)
print('world')
```
3. Execute the cell
4. Create a new view for the output cell 
5. Clear cell output and re-execute the code cell, 

## Expected behavior

Both `hello` and `world` are printed in the linked output view and no error message in the JS console.

## Context

- JupyterLab version: current main

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
Pinging @krassowski , who opened #14911.

**Comment by krassowski** [comment]
(well, I did not open it)

@trungleduc how do you think we should fix it? Just check for `panel.widgets[0][1]`? It feels odd that the renderer is being discovered this way.

**Comment by trungleduc** [comment]
I think a safer bet is to search for the first renderer in the `panel.widgets` list.

**Comment by krassowski** [comment]
I think this was fixed by https://github.com/jupyterlab/jupyterlab/pull/15642 but please reopen if this persists in 4.1.0+
