### ISSUE TITLE
terminals websocket connection lost

### ISSUE THREAD

**Issue by sumumont** [jupyterlab/jupyterlab#15000]
## Reproduce

1. This bug sometimes appears when opening a terminal
2. But after clearing the cache, you can fix the problem

<img width="1721" alt="16926961149659" src="https://github.com/jupyterlab/jupyterlab/assets/82426139/817880c4-12da-4eb8-a4ff-1e2d9990b3fa">

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 
jupyter --version
Selected Jupyter core packages...
IPython          : 7.29.0
ipykernel        : 6.5.0
ipywidgets       : not installed
jupyter_client   : 7.0.6
jupyter_core     : 4.9.1
jupyter_server   : 1.11.2
jupyterlab       : 3.2.3
nbclient         : 0.5.8
nbconvert        : 6.3.0
nbformat         : 5.1.3
notebook         : 6.4.6
qtconsole        : not installed
traitlets        : 5.1.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
@sumumont Thanks for your response! Please let us know whether the problem recurs with 3.6.x or 4.0.x.

**Comment by JasonWeill** [comment]
@sumumont Any update about whether this problem recurs in 3.6.x or 4.0.x?
