### ISSUE TITLE
Completion providers list is not refreshed dynamically

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15016]
## Description

The list of applicable completion providers is materialized at the time when `updateCompleter` is called. If a provider implements `isApplicable` method dynamically, e.g. it returns true if an LSP adapter is found (or if connection to LSP server is open), it may initially return false while the setup is ongoing. Problematically, this will not be updated until user swtiches back and forth between another editor of the same type triggering `updateCompleter()` code path.

## Reproduce

Relevant code:

https://github.com/jupyterlab/jupyterlab/blob/ac8f9e2f47b271785127757541a6fd8aa10c4d31/packages/completer/src/manager.ts#L176-L188

## Expected behavior

We could move the check to `ProviderReconciliator` which could call it each time (e.g. in a getter). My assumption is that `isApplicable` method is always (or should be) cheap.

Any other ideas?

## Context

- JupyterLab version: 4.0.5

**Comment by fcollonval** [comment]
:+1: on the proposed solution
