### ISSUE TITLE
Completer documentation panel is showing documentation for wrong item

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15018]
## Description

The optional completer documentation panel shows documentation for incorrect item when the completer model is filtered down.

## Reproduce

1. Enable "Show the documentation panel." in code completion settings
2. Invoke compelter in notebook
3. Type a few characters to trigger filtering down
4. Go down to an item with docs from kernel
5. See mismatched docs (here `dict` docs for `delattr`)

![Screenshot from 2023-08-25 01-35-51](https://github.com/jupyterlab/jupyterlab/assets/5832902/acb47aba-24bf-43f9-8918-d14f171b1a66)

## Expected behavior

- Correct docs is shown in documentation panel.

## Context

- JupyterLab version: 4.0.5

Again, first seen in LSP extension but the issue is in core.

**Comment by krassowski** [comment]
This is because the active index is relative to "displayed items":

https://github.com/jupyterlab/jupyterlab/blob/ac8f9e2f47b271785127757541a6fd8aa10c4d31/packages/completer/src/widget.ts#L329

But it is used as if it was relative to all completion items:

https://github.com/jupyterlab/jupyterlab/blob/ac8f9e2f47b271785127757541a6fd8aa10c4d31/packages/completer/src/widget.ts#L340

**Comment by krassowski** [comment]
One way to solve it would be using `this.completionItems()` method in place of `this._completionItems` in the default `resolveItem` implementation, but this still could also lead to some (edge case) errors because resolution is async.

It might be much better to ensure correctness by modifying the signature of `resolveItem` so that it accepts `number | ICompletionItem` (and deprecate the `number` usage).

Any thoughts?

**Comment by fcollonval** [comment]
I see that when selection changes the signal has an argument:

https://github.com/jupyterlab/jupyterlab/blob/ac8f9e2f47b271785127757541a6fd8aa10c4d31/packages/completer/src/widget.ts#L234

Would that `data-value` be enough to resolve the item? - using the argument sounds like a good solution as it will make the API more consistent.

---

Another solution would be to hook a listener to all list items that will open a doc panel if the item becomes active (using React snippet for easiness):

```jsx
function Item(props) {
  return (
    <li
      onClick={() => {
        // Trigger callback from the parent to open the doc panel if needed
        props.activate(props.completionItem)
      }
      {// and other relevant events}
    >
    {// ...}
    </li>
  );
}
```

**Comment by krassowski** [comment]
data-value by itself is insufficient, unless we dump the entire completion object as serialised JSON which does not sound great. This is because LSP server may send arbitrary data to be preserved between completion response and resolution request.

For context, downstream I trigger resolution as soon as an item is in view to prefetch the results and cache them using intersection observer.

But assuming data-value is unique maybe we could have value-completion item map. Not sure if that is needed.
