### ISSUE TITLE
Enable Labextensions through JupyterHub

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#1502]
I am trying to spawn jupyterlab through jupyterhub and have been able to do that successfully, but my labextensions don't seem to be working when I start lab through hub. 

The labextensions work fine when I start lab directly. Could you tell me how can I enable labextensions through hub?

**Comment by blink1073** [comment]
Hi @rsinha25, yes, we had noticed this problem yesterday, working on a fix in #1503.

**Comment by AbdealiJK** [comment]
@blink1073 I'm facing the same issue. Is it possible to make a bug fix 0.12.2 which has this fix ?

**Comment by blink1073** [comment]
Hi @AbdealiJK, we're going to cut a 0.13 release today.

**Comment by AbdealiJK** [comment]
Awesome
