### ISSUE TITLE
Allow a way to disable default keybindings

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [jupyterlab/jupyterlab#15038]
### Problem

I am trying to get jupyterlab-vim into a usable state. And a major pain point is the "Enter Cell", I believe from a vim standpoint it should be `I` and not `Enter` as a shortcut. I'm able to bind `I` but there is the `I, I` binding conflict, which forces me to wait a full second before I can enter a cell which essentially renders `jupyterlab` useless to me. In the settings I remapped `interrupt-kernel` to something else but it keeps adding back `I, I` as a secondary key binding. I tried the "disabled" attribute but I don't want to disable `interrupt-kernel` just the **default** keybinding

### Proposed Solution

Do not insert back the default keybinding once a user has provided a custom binding for it

**Comment by krassowski** [comment]
> I tried the "disabled" attribute but I don't want to disable interrupt-kernel just the _default_ keybinding

The disabled attribute does exactly that - it disables the default keybinding.
