### ISSUE TITLE
Search box wraps text but it should grow

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15049]
## Description

The search box wraps long text, which is undesirable because it is very confusing when multi-line search is used.

## Reproduce

Search for:
```
this_is_a_very_very_very_very_long_variable
this_is_a_new_line
```

![repro](https://github.com/jupyterlab/jupyterlab/assets/5832902/fc8ad7ee-e237-4e4d-8852-ed74c9fb1815)

## Expected behavior

1. The search input grows up until reaching the full width of the container
2. Once full width is reached, it overflows
3. It never wraps

## Context

- Browser and version: Firefox
- JupyterLab version: 4.0.5

**Comment by krassowski** [comment]
This function needs to be modified to enable auto-growth (by increasing width as needed):

https://github.com/jupyterlab/jupyterlab/blob/272e390120d8c2c0e680f7c370d77e4868136bb6/packages/documentsearch/src/searchview.tsx#L67-L117

This CSS class needs to be modified to disable word wrapping:

https://github.com/jupyterlab/jupyterlab/blob/272e390120d8c2c0e680f7c370d77e4868136bb6/packages/documentsearch/style/base.css#L5-L14

**Comment by eliaslma** [comment]
Hey, I'm new to the open source community, can I work on this issue? @krassowski

**Comment by krassowski** [comment]
Of course! Please feel welcome to open an early pull request to enable early feedback. You can refer to our [contributing documentation here](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html) but if you find the the setup difficult feel welcome to reach out with questions via [gitter](https://gitter.im/jupyterlab/jupyterlab).

**Comment by sinistersnare** [comment]
Hi, I took a quick stab at this and improved upon the good work done in #15080. Ill be opening a PR soon. Hope no one minds!

**Comment by krassowski** [comment]
Please do!
