### ISSUE TITLE
Add a tokenizer to the `IMimeTypeService`

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1504]
Add a function to the `IMimeTypeService` that gives an array of unique tokens given a `CodeEditor.IModel`.  It would use the `mimeType` and the `value` to get tokens.  This function can be used by a completer widget to show token-based completions.

**Comment by blink1073** [comment]
Alternatively, this could be a method on `CodeEditor.IModel` itself.

**Comment by sccolbert** [comment]
Related to #1276

**Comment by ian-r-rose** [comment]
A tokenizer service was added to the `CodeEditor.IEditor` in #5049. If we want to move it to the `IMimeTypeService`, that would be fairly straightforward, but for now I think this is resolved.
