### ISSUE TITLE
Environments/kernels are ignored with running !some_exe

### ISSUE THREAD

**Issue by eusebiu** [jupyterlab/jupyterlab#15069]
### Bug description

Running some_exe using !some_exe syntax is not considering the kernel associated with that session.

#### Expected behaviour

Running some_exe using !some_exe syntax must consider the kernel associated with that session and any tools, env variables that are present in that environment.

#### Actual behaviour

The some_exe is not found or is not the correct version (depending on the installation).

### How to reproduce

1. Open hub/lab, login
2. Create a terminal session and create a python environment (with other version of python, e.g. 3.7)
3. Install that environment in hub
4. Create a notebook and change the kernel in for the notebook to use that environment
5. Execute: ```!which python``` in a node which will display the OS python and not the one in the environment

### Your personal set up

Installed JupyterHub using on Docker:
```
RUN python3 -m pip install jupyterhub jupyter notebook
```

 - OS:
ubuntu 22.04
 - Version(s):
 jupyterhub, latest, python 3.10

**Comment by krassowski** [comment]
The bang execution is not implemented in JupyterLab itself but in IPython. Please search for relevant discussion in the IPython repository (there were many) and if it does not answer your question open an issue over there: https://github.com/ipython/ipython/

**Comment by eusebiu** [comment]
Ok. Thanks!
