### ISSUE TITLE
Broken benchmark check on CI

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#15089]
## Description

The "Benchmark Tests" CI check fails consistently when PRs are approved:

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/8ded0d8c-72f4-45a0-b320-f5e238f38e77)

## Reproduce

Example run: https://github.com/jupyterlab/jupyterlab/actions/runs/6043794173/job/16401409899?pr=15042

## Expected behavior

The benchmark check should pass most of the time.

## Context

Do we still need to run the "Benchmark Tests" on PR approval? This triggers a 1h long CI job which adds CI fatigue on maintainers who might not be sure whether this check is important or not.

Also it looks like maintainers are now ignoring this check when merging PRs (since it's consistently failing), so this raises the question about it is really useful.

**Comment by jtpio** [comment]
Looks like this may be fixable if the only issue is about publishing the report: 

```
Warning: "cml publish" is deprecated since "cml comment" now supports "![inline](./asset.png)"
```

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/590e8162-68e9-4c37-bcdc-7fe1deeae5f6)

**Comment by krassowski** [comment]
We could just use GitHub actions instead of cml, as in https://github.com/jupyterlab/benchmarks/pull/144. That supports markdown so if we generate a PNG we can bease64 encode it.
