### ISSUE TITLE
Change the shared "auto save documents " option by an "autosave status" specific to each noteboook 

### ISSUE THREAD

**Issue by athelopuce** [jupyterlab/jupyterlab#15081]
### Problem
On notebook, I’m not completely happy with the way _“Autosave documents”_ currently works, on or off.

When I work on a notebook I want it to be saved automatically (as the _“Autosave documents”_ option allows).
**But at the same time**, I have other notebooks just open for reference that I don’t edit. I don’t want them to be automatically re-registered so as not to lose their registration date.

I’d like a solution that doesn’t require me to permanently activate/deactivate _“Autosave documents”_ or to have to inject code into my notebooks.

### Proposed Solution

The best for me will be to have an _"auto save status"_ attached to each noteboook and a button that I can click to change it. So when my work with a notebook is finished I will be able to put its _"autosave status"_ on OFF whereas the default _"autosave status"_ for notebook will be ON.

**Comment by athelopuce** [comment]
**Precision for a  solution**
A solution will be to keep the actual global "autosave documents" switch, but to attached to each notebook an option to apply or not this default autosave  choice.

**Comment by athelopuce** [comment]
Another approach to solving my problem would be to be able to open a notebook for "consultation only" (no need to run a kernel) and not apply "autosave documents" to it.

**Comment by JasonWeill** [comment]
@athelopuce Thank you for your contribution! Looks like we already have an issue about disabling autosave for one notebook. See #6481. Additional commentary and contributions are welcome on this issue.
