### ISSUE TITLE
Export Notebook doesn't work

### ISSUE THREAD

**Issue by rolfn** [jupyterlab/jupyterlab#15097]
## Description

I have installed “Jupyter Lab” on a Linux system in a Python virtual environment. It worked as expected, except I can't select the "Save and Export Notebook As..." menu item. PDF export would be particularly important to me.  I have now seen that on the test site

https://jupyter.org/try-jupyter/lab/

this menu item also doesn't work. What can I do to fix the problem?

## Context

- Operating System and version: Linux "openSUSE Leap 15.5", Python 3.11 or 3.9
- Browser and version: Firefox 117.0 or Chromium 116.0
- JupyterLab version:  4.0.5

**Comment by krassowski** [comment]
Hello! Your installation may be missing dependencies required for export, in particular `nbconvert` and its optional dependencies (https://nbconvert.readthedocs.io/en/latest/install.html - there are two ways to get a PDF out either via TeX or via webpdf, see the linked docs). If after installation of all dependencies and restart the problem recurs, please provide full context information that is asked about in the [bug report form](https://github.com/jupyterlab/jupyterlab/issues/new/choose).

**Comment by rolfn** [comment]
Thank you for that information. I will test and report.

**Comment by JasonWeill** [comment]
@rolfn Have you tried installing `nbconvert`, and if so did that fix this issue? Thanks!

**Comment by rolfn** [comment]
Sorry for the delay. I was able to solve the problem after installing `nbconvert`. It worked, but only after a system update (openSUSE 15.4 --> 15.5). Thank you for all the tips.
