### ISSUE TITLE
Deprecate old npm repos

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#151]
We should deprecate these on npm and put a note in the package.json description that they have been superseded by the jupyterlab package:
- jupyter-js-notebook
- jupyter-js-docmanager
- jupyter-js-domutils
- jupyter-js-terminal
- jupyter-js-filebrowser
- jupyter-js-ui
- jupyter-js-plugins

We should also note in the github repos that the repos have been superseded by the jupyterlab repo. We should probably move the repos to some jupyter-attic github org.

**Comment by jasongrout** [comment]
I think this covers all of the bases:

- [ ] move the repo to the jupyter-attic org
- [ ] Update each one-line repo description on github to say "Deprecated"
- [ ] Update the readme files to point to the new repo
- [ ] update the package.json description so the deprecation shows up in npm
- [ ] update the package.json repo to point to the jupyter-attic location
- [ ] use the npm deprecation command to officially deprecate the repo

**Comment by jasongrout** [comment]
This is done!

**Comment by jasongrout** [comment]
Nope, not done! The npm package needs to be deprecated...

**Comment by ellisonbg** [comment]
@jasongrout is this still relevant - did you finish it?

**Comment by jasongrout** [comment]
Not yet. Probably still relevant - just need some time for the woodcutting, as @SylvainCorlay would say.

**Comment by jasongrout** [comment]
(some of it is done...)

**Comment by ellisonbg** [comment]
ping...

**Comment by ellisonbg** [comment]
still relevant...

**Comment by blink1073** [comment]
I deprecated all of the listed packages.
