### ISSUE TITLE
lags in response to some actions

### ISSUE THREAD

**Issue by aakhmetz** [jupyterlab/jupyterlab#15108]
Hello everyone, 

I am wondering if some of you experienced some lagging in response from JupyterLab. For example, I have noticed many lags: starting from double clicking (I select the word only after few attempts), then changing the cells, the layout. Everything seems lagged and my impression, it appeared just with latest updates. 

I am using Manjaro arch linux.

-Andrei

**Comment by krassowski** [comment]
Using which JupyterLab version, and which browser and version? What is a minimal reproducer?

**Comment by aakhmetz** [comment]
For example, if I scroll, it takes some time for the contents to appear 

![image](https://github.com/jupyterlab/jupyterlab/assets/2173206/6581c787-77ba-4b1e-ad74-56494a4fb623)

the JupyterLab was 4.0.5, browser is Firefox (minimal reproducer?)

**Comment by aakhmetz** [comment]
I have also noticed that the following message pops up in my terminal sometimes
```
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

**Comment by aakhmetz** [comment]
Finally, I installed 3.6.5, and it works much smoothly, also it does not have that message about freezing (I don't know if it is actually related)

**Comment by krassowski** [comment]
The terminal message is unrelated.

In JupyterLab 4, what is your setting for Settings → Notebook → Windowing mode, and what is for Settings → JupyterLab Shell → Hidden mode?

![Screenshot from 2023-09-12 11-55-14](https://github.com/jupyterlab/jupyterlab/assets/5832902/ee8d2ff7-1d99-4211-bba7-d38db7d31a96)

![Screenshot from 2023-09-12 11-56-09](https://github.com/jupyterlab/jupyterlab/assets/5832902/e9866de0-3916-47de-bde3-cb4d6cd3286f)

How big is the notebook which manifests this behaviour? Is it something that you could potentially share for us to reproduce?

**Comment by aakhmetz** [comment]
Thank you! I could see where you were heading.

Actually, you were correct - my notebook contained a large chunk of the output from external program (which included warnings). It was so big that I would not look at its end. However, it was hidden from the view in the notebook. I thought it would be sufficient, but it looks like it was still in the memory and made the whole notebook less responsive. One way would be to clean the output, I think

**Comment by krassowski** [comment]
What kind of output was this? If this was a long run of logs, JupyterLab should collapse them, unless these were a result of a single action. It would help if you could provide the notebook in question, or a similar one if you need to remove sensitive content.

**Comment by aakhmetz** [comment]
It looks like it's been improved and I can't reproduce the problem anymore. Sorry for disturbing and thanks for trying to help!
