### ISSUE TITLE
jupyterlab.browser_check fails because browser are not installed

### ISSUE THREAD

**Issue by brichet** [jupyterlab/jupyterlab#15116]
Playwright `v1.38.0` does not download the browser at installation anymore.

https://github.com/microsoft/playwright/releases/tag/v1.38.0

## Description

The tests using `jupyterlab.browser_check` fail because the playwright browser is not installed.

## Example

https://github.com/jupyterlab/jupyterlab/actions/runs/6185715676/job/16791841488?pr=15021
https://github.com/jupyterlab/jupyterlab/actions/runs/6185543001/job/16791342970?pr=15111
https://github.com/jupyterlab/jupyterlab/actions/runs/6185131606/job/16790138548?pr=15106

## Expected behavior

The tests to pass

**Comment by krassowski** [comment]
For anyone following, there was another hiccup with release test failing due to https://github.com/babel/babel/issues/15967 which appears to be fixed upstream.
