### ISSUE TITLE
JupyterLab / Jupyter server freeze when a script reaches the memory limit

### ISSUE THREAD

**Issue by jtrancas-ti** [jupyterlab/jupyterlab#15115]
## Description

When a script executes and reaches the available memory limit in the machine, the system freezes.

## Reproduce
1. Run it in as a docker container:
```docker run -it --rm -p 8888:8888 --cpus="2" --memory="500m" jupyter/tensorflow-notebook:x86_64-2023-07-07```

2. Run the following code to allocate 1G of memory:
```python
bytearray(1024*1024*1000)
```
It consumes all the 500MB available to the container, and when running without limits freezes the entire system (CPU and disk I/O goes up to 100% utilization).

The logs are the following:
```
[I 2023-09-14 08:06:19.137 ServerApp] Saving file at /Untitled.ipynb
[I 2023-09-14 08:08:01.200 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2023-09-14 08:08:01.209 ServerApp] kernel d1c9f101-7669-4063-9aa3-efddaec3e6e0 restarted
[I 2023-09-14 08:08:01.239 ServerApp] Starting buffering for d1c9f101-7669-4063-9aa3-efddaec3e6e0:cf87cb2a-08b7-4500-ac68-a0e64e5034ed
[I 2023-09-14 08:08:01.301 ServerApp] Connecting to kernel d1c9f101-7669-4063-9aa3-efddaec3e6e0.
[I 2023-09-14 08:08:01.301 ServerApp] Restoring connection for d1c9f101-7669-4063-9aa3-efddaec3e6e0:cf87cb2a-08b7-4500-ac68-a0e64e5034ed
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

## Expected behavior

The kernel gets killed and restarts.

## Context

- Operating System and version: Linux Ubuntu 20.04
- Browser and version: Google Chrome Version 116.0.5845.140 (Official Build) (64-bit)
- JupyterLab version: 4.0.2

**Comment by JasonWeill** [comment]
@jtrancas-ti After discussing this with the team, this is something that is not related to JupyterLab. Allocating more memory than you have available will likely cause problems with any application. I'm going to close this issue, but please open other issues if you notice any other bugs in JupyterLab. Thanks for your contribution!
