### ISSUE TITLE
Inconsistent commands, Open versus Show 

### ISSUE THREAD

**Issue by sgornick** [jupyterlab/jupyterlab#1513]
For Command, It looks like "Open" is for opening a target in the main area.    e.g., the command "Open Inspector" "launches" a tab titled "Inspector". 

OK, but then there's no "Open Launcher" .  There's "Show Launcher" but that opens the Launcher tab on the side.  Hmmm ... and then "Show Landing" ... opens a tab in the main area that does not say "Landing" as I might have expected but instead it reads "Launcher".  Lots of inconsistencies there.

Then, under Help there is:
Frequently Asked Question ... but not "Open FAQ" or "Show FAQ". 
OK. and then 
About ... but not "Open About" or "Show About".   
But there is "Open Classic Notebook"  -- which (correctly) opens a new browser tab.  So not all "Open" operations will put the target in the main area.

While I'm describing inconsistencies, ... in Commands the Help subsection shows its entries alphabetically.  On the Help (drop downmenu), the order of the items is different.  I can see having About and FAQ at the top, but the order of the rest (reference notes, lecture notes, tutorial) should probably be in the same order (alphabetically).

**Comment by blink1073** [comment]
Hi @sgornick, thank you for the detailed audit.
