### ISSUE TITLE
Option to disable input placeholder text

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#15138]
### Problem

#13797 added a placeholder text string for `input()` calls. Developers would like the option to disable this.

### Proposed Solution

Add an option to disable the placeholder on inputs.

### Additional context

See also https://github.com/jupyter/notebook/issues/7063.

**Comment by gianoddone** [comment]
Thanks for checking it out.  I have used notebook to make some interactive math games and enjoy the simplicity of input().  I guess there are other ways that afford more control with widgets, but I got stuck looking for a setting to disable the placeholder--which is impressive by the way--just not what I needed in this case.

Not sure I am qualified to contribute just yet, but certainly appreciate the work you all are doing on this project!

**Comment by gigoiy** [comment]
I can contribute by adding this feature! I'll get working on this soon and open a PR.

**Comment by JasonWeill** [comment]
@gigoiy Thank you! Please leave a comment on this issue, or chat with us on Discourse or Gitter, if you need help. You can find our community resources here: https://jupyter.org/community

**Comment by krassowski** [comment]
For reference for anyone wishing to contribute, here is a related pull request which disabled placeholder for password prompts: https://github.com/jupyterlab/jupyterlab/pull/16128

**Comment by nitesh2920** [comment]
Is this still open? I would love to work on it. @krassowski @JasonWeill

**Comment by JasonWeill** [comment]
@nitesh2920 Thank you for your interest! It looks like #16713 would fix this. I just pinged @krassowski to ask about merging this PR in for Lab 4.4.0, after 4.3.0 is released.
