### ISSUE TITLE
Not required packages but installed with jupyterlab

### ISSUE THREAD

**Issue by MrMarvel** [jupyterlab/jupyterlab#15140]
## Description

I want to install, use, and uninstall after that jupyterlab.
But I have problem with uninstalling.
The required packages by jupyterlab doesn't show all packages installed directly.
After installing ONLY jupyterlab package pip3-autoremove shows(leafs in packages tree):
```
pip3-autoremove -yf
setuptools==65.5.0
pip==23.2.1
isoduration==20.11.0
jupyterlab==4.0.6
jsonpointer==2.4
webcolors==1.13
fqdn==1.5.1
uri-template==1.3.0
pip3-autoremove==0.10.2
```
but pip shows that jupyterlab doesn't use them (no packages use them actually):
```
D:\Users\Sergey> pip show jupyterlab
Name: jupyterlab
Version: 4.0.6
...
...
Location: F:\Utilities\Python\Python311\Lib\site-packages
Requires: async-lru, ipykernel, jinja2, jupyter-core, jupyter-lsp, jupyter-server, jupyterlab-server, notebook-shim, packaging, tornado, traitlets
Required-by:
```
It force me to remove packages manually:
```
isoduration==20.11.0
jsonpointer==2.4
webcolors==1.13
fqdn==1.5.1
uri-template==1.3.0
```
## Reproduce

1. pip install jupyterlab
2. Remove packages recursively by requirements 
3. There are packages that left - a problem

## Expected behavior

No packages left

## Context

- Operating System and version: Windows 10 Pro 10.0.19045
- Browser and version: Chrome 116.0.5845.188
- JupyterLab version: 4.0.6

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        C:\Program Files\PowerShell\7
        F:\Utilities\Poetry\bin
        F:\Utilities\Python\Python311\Scripts\
        F:\Utilities\Python\Python311\
        F:\Utilities\Python\Python38\Scripts\
        F:\Utilities\Python\Python38\
        F:\IDE\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin
        F:\Utilities\LxRunOffline
        E:\Oculus\Support\oculus-runtime
        C:\Program Files (x86)\ImageMagick-7.0.10-Q8
        C:\Gradle\gradle-6.9.2\bin
        C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler
        C:\Program Files\Common Files\Oracle\Java\javapath
        C:\Program Files (x86)\Common Files\Oracle\Java\javapath
        C:\Windows\system32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0\
        C:\Windows\System32\OpenSSH\
        C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
        C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
        C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
        E:\Program Files\Mosquitto
        C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
        C:\Program Files\Microsoft SQL Server\150\Tools\Binn\
        C:\Program Files\dotnet\
        E:\Program Files\PuTTY\
        E:\Program Files (x86)\Rational\common
        E:\Program Files\OpenSSL-Win64\bin
        E:\Program Files\apache-maven-3.8.6\bin
        C:\Program Files\Common Files\Autodesk Shared\
        E:\Program Files\PMD\pmd-bin-6.50.0\bin
        D:\Program Files\nodejs\
        C:\WINDOWS\System32\OpenSSH\
        C:\Program Files (x86)\ZeroTier\One\
        C:\Program Files\NVIDIA\CUDNN\v8.9\bin
        E:\Utilities\MinGW\bin
        E:\Utilities\MinGW\msys\1.0\bin
        F:\Utilities\Git\cmd
        C:\Program Files\PowerShell\7\
        E:\Utilities\Windows Kits\10\Windows Performance Toolkit\
        C:\ProgramData\chocolatey\bin
        C:\Program Files\Docker\Docker\resources\bin
        D:\Users\Sergey\AppData\Local\Programs\Python\Launcher\
        D:\Users\Sergey\AppData\Local\Programs\Python\Python310\Scripts\
        D:\Users\Sergey\AppData\Local\Programs\Python\Python310\
        D:\Users\Sergey\AppData\Local\Programs\Python\Python39\
        C:\Windows\System32
        D:\Users\Sergey\AppData\Local\Microsoft\WindowsApps
        D:\Users\Sergey\AppData\Local\Programs\Fiddler
        D:\Users\Sergey\AppData\Local\GitHubDesktop\bin
        D:\Users\Sergey\AppData\Local\Microsoft\WindowsApps
        D:\Program Files (x86)\heroku\bin
        E:\altera\13.1\modelsim_ase\win32aloem
        E:\altera\13.1\modelsim_ae\win32aloem
        D:\Program Files (x86)\ffmpeg\bin
        E:\steamcmd
        D:\Users\Sergey\AppData\Local\JetBrains\Toolbox\scripts
        D:\Users\Sergey\AppData\Roaming\npm
        F:\Utilities\Miniconda3\Scripts

sys.path:
        F:\Utilities\Python\Python311\Scripts\jupyter-troubleshoot.EXE
        F:\Utilities\Python\Python311\python311.zip
        F:\Utilities\Python\Python311\DLLs
        F:\Utilities\Python\Python311\Lib
        F:\Utilities\Python\Python311
        F:\Utilities\Python\Python311\Lib\site-packages
        F:\Utilities\Python\Python311\Lib\site-packages\win32
        F:\Utilities\Python\Python311\Lib\site-packages\win32\lib
        F:\Utilities\Python\Python311\Lib\site-packages\Pythonwin

sys.executable:
        F:\Utilities\Python\Python311\python.exe

sys.version:
        3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.19045-SP0

where jupyter:
        F:\Utilities\Python\Python311\Scripts\jupyter.exe

pip list:
        Package                   Version
        ------------------------- ---------
        anyio                     4.0.0
        argon2-cffi               23.1.0
        argon2-cffi-bindings      21.2.0
        arrow                     1.2.3
        asttokens                 2.4.0
        async-lru                 2.0.4
        attrs                     23.1.0
        Babel                     2.12.1
        backcall                  0.2.0
        beautifulsoup4            4.12.2
        bleach                    6.0.0
        certifi                   2023.7.22
        cffi                      1.15.1
        charset-normalizer        3.2.0
        colorama                  0.4.6
        comm                      0.1.4
        debugpy                   1.8.0
        decorator                 5.1.1
        defusedxml                0.7.1
        executing                 1.2.0
        fastjsonschema            2.18.0
        fqdn                      1.5.1
        idna                      3.4
        ipykernel                 6.25.2
        ipython                   8.15.0
        isoduration               20.11.0
        jedi                      0.19.0
        Jinja2                    3.1.2
        json5                     0.9.14
        jsonpointer               2.4
        jsonschema                4.19.0
        jsonschema-specifications 2023.7.1
        jupyter_client            8.3.1
        jupyter_core              5.3.1
        jupyter-events            0.7.0
        jupyter-lsp               2.2.0
        jupyter_server            2.7.3
        jupyter_server_terminals  0.4.4
        jupyterlab                4.0.6
        jupyterlab-pygments       0.2.2
        jupyterlab_server         2.25.0
        MarkupSafe                2.1.3
        matplotlib-inline         0.1.6
        mistune                   3.0.1
        nbclient                  0.8.0
        nbconvert                 7.8.0
        nbformat                  5.9.2
        nest-asyncio              1.5.8
        notebook_shim             0.2.3
        overrides                 7.4.0
        packaging                 23.1
        pandocfilters             1.5.0
        parso                     0.8.3
        pickleshare               0.7.5
        pip                       23.2.1
        pip3-autoremove           0.10.2
        platformdirs              3.10.0
        prometheus-client         0.17.1
        prompt-toolkit            3.0.39
        psutil                    5.9.5
        pure-eval                 0.2.2
        pycparser                 2.21
        Pygments                  2.16.1
        python-dateutil           2.8.2
        python-json-logger        2.0.7
        pywin32                   306
        pywinpty                  2.0.11
        PyYAML                    6.0.1
        pyzmq                     25.1.1
        referencing               0.30.2
        requests                  2.31.0
        rfc3339-validator         0.1.4
        rfc3986-validator         0.1.1
        rpds-py                   0.10.3
        Send2Trash                1.8.2
        setuptools                65.5.0
        six                       1.16.0
        sniffio                   1.3.0
        soupsieve                 2.5
        stack-data                0.6.2
        terminado                 0.17.1
        tinycss2                  1.2.1
        tornado                   6.3.3
        traitlets                 5.10.0
        uri-template              1.3.0
        urllib3                   2.0.4
        wcwidth                   0.2.6
        webcolors                 1.13
        webencodings              0.5.1
        websocket-client          1.6.3

conda list:
        # packages in environment at F:\Utilities\Miniconda3:
        #
        # Name                    Version                   Build  Channel
        boltons                   23.0.0          py310haa95532_0
        brotlipy                  0.7.0           py310h2bbff1b_1002
        bzip2                     1.0.8                he774522_0
        ca-certificates           2023.01.10           haa95532_0
        certifi                   2022.12.7       py310haa95532_0
        cffi                      1.15.1          py310h2bbff1b_3
        charset-normalizer        2.0.4              pyhd3eb1b0_0
        colorama                  0.4.6           py310haa95532_0
        conda                     23.3.1          py310haa95532_0
        conda-content-trust       0.1.3           py310haa95532_0
        conda-package-handling    2.0.2           py310haa95532_0
        conda-package-streaming   0.7.0           py310haa95532_0
        console_shortcut_miniconda 0.1.1                haa95532_1
        cryptography              39.0.1          py310h21b164f_0
        idna                      3.4             py310haa95532_0
        jsonpatch                 1.32               pyhd3eb1b0_0
        jsonpointer               2.1                pyhd3eb1b0_0
        libffi                    3.4.2                hd77b12b_6
        menuinst                  1.4.19          py310h59b6b97_0
        openssl                   1.1.1t               h2bbff1b_0
        packaging                 23.0            py310haa95532_0
        pip                       23.0.1          py310haa95532_0
        pluggy                    1.0.0           py310haa95532_1
        powershell_shortcut_miniconda 0.0.1                haa95532_1
        pycosat                   0.6.4           py310h2bbff1b_0
        pycparser                 2.21               pyhd3eb1b0_0
        pyopenssl                 23.0.0          py310haa95532_0
        pysocks                   1.7.1           py310haa95532_0
        python                    3.10.10              h966fe2a_2
        requests                  2.28.1          py310haa95532_1
        ruamel.yaml               0.17.21         py310h2bbff1b_0
        ruamel.yaml.clib          0.2.6           py310h2bbff1b_1
        setuptools                65.6.3          py310haa95532_0
        six                       1.16.0             pyhd3eb1b0_1
        sqlite                    3.41.1               h2bbff1b_0
        tk                        8.6.12               h2bbff1b_0
        toolz                     0.12.0          py310haa95532_0
        tqdm                      4.65.0          py310h9909e9c_0
        tzdata                    2023c                h04d1e81_0
        urllib3                   1.26.15         py310haa95532_0
        vc                        14.2                 h21ff451_1
        vs2015_runtime            14.27.29016          h5e58377_2
        wheel                     0.38.4          py310haa95532_0
        win_inet_pton             1.1.0           py310haa95532_0
        wincertstore              0.2             py310haa95532_2
        xz                        5.2.10               h8cc25b3_1
        zlib                      1.2.13               h8cc25b3_0
        zstandard                 0.19.0          py310h2bbff1b_0

conda env:
        name: base
        channels:
          - defaults
        dependencies:
          - boltons=23.0.0=py310haa95532_0
          - brotlipy=0.7.0=py310h2bbff1b_1002
          - bzip2=1.0.8=he774522_0
          - ca-certificates=2023.01.10=haa95532_0
          - certifi=2022.12.7=py310haa95532_0
          - cffi=1.15.1=py310h2bbff1b_3
          - charset-normalizer=2.0.4=pyhd3eb1b0_0
          - colorama=0.4.6=py310haa95532_0
          - conda=23.3.1=py310haa95532_0
          - conda-content-trust=0.1.3=py310haa95532_0
          - conda-package-handling=2.0.2=py310haa95532_0
          - conda-package-streaming=0.7.0=py310haa95532_0
          - console_shortcut_miniconda=0.1.1=haa95532_1
          - cryptography=39.0.1=py310h21b164f_0
          - idna=3.4=py310haa95532_0
          - jsonpatch=1.32=pyhd3eb1b0_0
          - jsonpointer=2.1=pyhd3eb1b0_0
          - libffi=3.4.2=hd77b12b_6
          - menuinst=1.4.19=py310h59b6b97_0
          - openssl=1.1.1t=h2bbff1b_0
          - packaging=23.0=py310haa95532_0
          - pip=23.0.1=py310haa95532_0
          - pluggy=1.0.0=py310haa95532_1
          - powershell_shortcut_miniconda=0.0.1=haa95532_1
          - pycosat=0.6.4=py310h2bbff1b_0
          - pycparser=2.21=pyhd3eb1b0_0
          - pyopenssl=23.0.0=py310haa95532_0
          - pysocks=1.7.1=py310haa95532_0
          - python=3.10.10=h966fe2a_2
          - requests=2.28.1=py310haa95532_1
          - ruamel.yaml=0.17.21=py310h2bbff1b_0
          - ruamel.yaml.clib=0.2.6=py310h2bbff1b_1
          - setuptools=65.6.3=py310haa95532_0
          - six=1.16.0=pyhd3eb1b0_1
          - sqlite=3.41.1=h2bbff1b_0
          - tk=8.6.12=h2bbff1b_0
          - toolz=0.12.0=py310haa95532_0
          - tqdm=4.65.0=py310h9909e9c_0
          - tzdata=2023c=h04d1e81_0
          - urllib3=1.26.15=py310haa95532_0
          - vc=14.2=h21ff451_1
          - vs2015_runtime=14.27.29016=h5e58377_2
          - wheel=0.38.4=py310haa95532_0
          - win_inet_pton=1.1.0=py310haa95532_0
          - wincertstore=0.2=py310haa95532_2
          - xz=5.2.10=h8cc25b3_1
          - zlib=1.2.13=h8cc25b3_0
          - zstandard=0.19.0=py310h2bbff1b_0
        prefix: F:\Utilities\Miniconda3
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
D:\Users\Sergey> pip install jupyterlab
Requirement already satisfied: jupyterlab in f:\utilities\python\python311\lib\site-packages (4.0.6)
Collecting async-lru>=1.0.0 (from jupyterlab)
  Obtaining dependency information for async-lru>=1.0.0 from https://files.pythonhosted.org/packages/fa/9f/3c3503693386c4b0f245eaf5ca6198e3b28879ca0a40bde6b0e319793453/async_lru-2.0.4-py3-none-any.whl.metadata
  Using cached async_lru-2.0.4-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: ipykernel in f:\utilities\python\python311\lib\site-packages (from jupyterlab) (6.25.2)
Requirement already satisfied: jinja2>=3.0.3 in f:\utilities\python\python311\lib\site-packages (from jupyterlab) (3.1.2)
Requirement already satisfied: jupyter-core in f:\utilities\python\python311\lib\site-packages (from jupyterlab) (5.3.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in f:\utilities\python\python311\lib\site-packages (from jupyterlab) (2.2.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in f:\utilities\python\python311\lib\site-packages (from jupyterlab) (2.7.3)
Collecting jupyterlab-server<3,>=2.19.0 (from jupyterlab)
  Obtaining dependency information for jupyterlab-server<3,>=2.19.0 from https://files.pythonhosted.org/packages/96/cd/cdabe44549d60e0967904f0bdd9e3756b521112317612a3997eb2fda9181/jupyterlab_server-2.25.0-py3-none-any.whl.metadata
  Using cached jupyterlab_server-2.25.0-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: notebook-shim>=0.2 in f:\utilities\python\python311\lib\site-packages (from jupyterlab) (0.2.3)
Requirement already satisfied: packaging in f:\utilities\python\python311\lib\site-packages (from jupyterlab) (23.1)
Requirement already satisfied: tornado>=6.2.0 in f:\utilities\python\python311\lib\site-packages (from jupyterlab) (6.3.3)
Requirement already satisfied: traitlets in f:\utilities\python\python311\lib\site-packages (from jupyterlab) (5.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in f:\utilities\python\python311\lib\site-packages (from jinja2>=3.0.3->jupyterlab) (2.1.3)
Requirement already satisfied: anyio>=3.1.0 in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (4.0.0)
Requirement already satisfied: argon2-cffi in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (23.1.0)
Requirement already satisfied: jupyter-client>=7.4.4 in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (8.3.1)
Requirement already satisfied: jupyter-events>=0.6.0 in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.7.0)
Requirement already satisfied: jupyter-server-terminals in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.4.4)
Requirement already satisfied: nbconvert>=6.4.4 in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.8.0)
Requirement already satisfied: nbformat>=5.3.0 in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (5.9.2)
Requirement already satisfied: overrides in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.4.0)
Requirement already satisfied: prometheus-client in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.17.1)
Collecting pywinpty (from jupyter-server<3,>=2.4.0->jupyterlab)
  Obtaining dependency information for pywinpty from https://files.pythonhosted.org/packages/5b/b8/46e4a4ed16fbf496bdb912739450177b7cbb5fec4fda99385dae091bf0ec/pywinpty-2.0.11-cp311-none-win_amd64.whl.metadata
  Using cached pywinpty-2.0.11-cp311-none-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: pyzmq>=24 in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (25.1.1)
Requirement already satisfied: send2trash>=1.8.2 in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.17.1)
Requirement already satisfied: websocket-client in f:\utilities\python\python311\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.6.3)
Requirement already satisfied: platformdirs>=2.5 in f:\utilities\python\python311\lib\site-packages (from jupyter-core->jupyterlab) (3.10.0)
Collecting pywin32>=300 (from jupyter-core->jupyterlab)
  Using cached pywin32-306-cp311-cp311-win_amd64.whl (9.2 MB)
Requirement already satisfied: babel>=2.10 in f:\utilities\python\python311\lib\site-packages (from jupyterlab-server<3,>=2.19.0->jupyterlab) (2.12.1)
Requirement already satisfied: json5>=0.9.0 in f:\utilities\python\python311\lib\site-packages (from jupyterlab-server<3,>=2.19.0->jupyterlab) (0.9.14)
Requirement already satisfied: jsonschema>=4.18.0 in f:\utilities\python\python311\lib\site-packages (from jupyterlab-server<3,>=2.19.0->jupyterlab) (4.19.0)
Requirement already satisfied: requests>=2.31 in f:\utilities\python\python311\lib\site-packages (from jupyterlab-server<3,>=2.19.0->jupyterlab) (2.31.0)
Requirement already satisfied: comm>=0.1.1 in f:\utilities\python\python311\lib\site-packages (from ipykernel->jupyterlab) (0.1.4)
Requirement already satisfied: debugpy>=1.6.5 in f:\utilities\python\python311\lib\site-packages (from ipykernel->jupyterlab) (1.8.0)
Requirement already satisfied: ipython>=7.23.1 in f:\utilities\python\python311\lib\site-packages (from ipykernel->jupyterlab) (8.15.0)
Collecting matplotlib-inline>=0.1 (from ipykernel->jupyterlab)
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Requirement already satisfied: nest-asyncio in f:\utilities\python\python311\lib\site-packages (from ipykernel->jupyterlab) (1.5.8)
Requirement already satisfied: psutil in f:\utilities\python\python311\lib\site-packages (from ipykernel->jupyterlab) (5.9.5)
Requirement already satisfied: idna>=2.8 in f:\utilities\python\python311\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->jupyterlab) (3.4)
Requirement already satisfied: sniffio>=1.1 in f:\utilities\python\python311\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->jupyterlab) (1.3.0)
Requirement already satisfied: backcall in f:\utilities\python\python311\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyterlab) (0.2.0)
Requirement already satisfied: decorator in f:\utilities\python\python311\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyterlab) (5.1.1)
Requirement already satisfied: jedi>=0.16 in f:\utilities\python\python311\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyterlab) (0.19.0)
Requirement already satisfied: pickleshare in f:\utilities\python\python311\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyterlab) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in f:\utilities\python\python311\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyterlab) (3.0.39)
Requirement already satisfied: pygments>=2.4.0 in f:\utilities\python\python311\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyterlab) (2.16.1)
Requirement already satisfied: stack-data in f:\utilities\python\python311\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyterlab) (0.6.2)
Requirement already satisfied: colorama in f:\utilities\python\python311\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyterlab) (0.4.6)
Requirement already satisfied: attrs>=22.2.0 in f:\utilities\python\python311\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in f:\utilities\python\python311\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in f:\utilities\python\python311\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in f:\utilities\python\python311\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab) (0.10.3)
Requirement already satisfied: python-dateutil>=2.8.2 in f:\utilities\python\python311\lib\site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (2.8.2)
Requirement already satisfied: python-json-logger>=2.0.4 in f:\utilities\python\python311\lib\site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->jupyterlab) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in f:\utilities\python\python311\lib\site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->jupyterlab) (6.0.1)
Requirement already satisfied: rfc3339-validator in f:\utilities\python\python311\lib\site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in f:\utilities\python\python311\lib\site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.1)
Requirement already satisfied: beautifulsoup4 in f:\utilities\python\python311\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (4.12.2)
Requirement already satisfied: bleach!=5.0.0 in f:\utilities\python\python311\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (6.0.0)
Requirement already satisfied: defusedxml in f:\utilities\python\python311\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in f:\utilities\python\python311\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.2.2)
Requirement already satisfied: mistune<4,>=2.0.3 in f:\utilities\python\python311\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (3.0.1)
Requirement already satisfied: nbclient>=0.5.0 in f:\utilities\python\python311\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.8.0)
Requirement already satisfied: pandocfilters>=1.4.1 in f:\utilities\python\python311\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.5.0)
Collecting tinycss2 (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab)
  Using cached tinycss2-1.2.1-py3-none-any.whl (21 kB)
Requirement already satisfied: fastjsonschema in f:\utilities\python\python311\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab) (2.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\utilities\python\python311\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.19.0->jupyterlab) (3.2.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\utilities\python\python311\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.19.0->jupyterlab) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in f:\utilities\python\python311\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.19.0->jupyterlab) (2023.7.22)
Requirement already satisfied: argon2-cffi-bindings in f:\utilities\python\python311\lib\site-packages (from argon2-cffi->jupyter-server<3,>=2.4.0->jupyterlab) (21.2.0)
Requirement already satisfied: six>=1.9.0 in f:\utilities\python\python311\lib\site-packages (from bleach!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.16.0)
Requirement already satisfied: webencodings in f:\utilities\python\python311\lib\site-packages (from bleach!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in f:\utilities\python\python311\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyterlab) (0.8.3)
Collecting fqdn (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab)
  Using cached fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Collecting isoduration (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab)
  Using cached isoduration-20.11.0-py3-none-any.whl (11 kB)
Collecting jsonpointer>1.13 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab)
  Obtaining dependency information for jsonpointer>1.13 from https://files.pythonhosted.org/packages/12/f6/0232cc0c617e195f06f810534d00b74d2f348fe71b2118009ad8ad31f878/jsonpointer-2.4-py2.py3-none-any.whl.metadata
  Using cached jsonpointer-2.4-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting uri-template (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab)
  Obtaining dependency information for uri-template from https://files.pythonhosted.org/packages/e7/00/3fca040d7cf8a32776d3d81a00c8ee7457e00f80c649f1e4a863c8321ae9/uri_template-1.3.0-py3-none-any.whl.metadata
  Using cached uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=1.11 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab)
  Using cached webcolors-1.13-py3-none-any.whl (14 kB)
Requirement already satisfied: wcwidth in f:\utilities\python\python311\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=7.23.1->ipykernel->jupyterlab) (0.2.6)
Requirement already satisfied: cffi>=1.0.1 in f:\utilities\python\python311\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->jupyterlab) (1.15.1)
Requirement already satisfied: soupsieve>1.2 in f:\utilities\python\python311\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (2.5)
Requirement already satisfied: executing>=1.2.0 in f:\utilities\python\python311\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyterlab) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in f:\utilities\python\python311\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyterlab) (2.4.0)
Requirement already satisfied: pure-eval in f:\utilities\python\python311\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyterlab) (0.2.2)
Requirement already satisfied: pycparser in f:\utilities\python\python311\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->jupyterlab) (2.21)
Collecting arrow>=0.15.0 (from isoduration->jsonschema>=4.18.0->jupyterlab-server<3,>=2.19.0->jupyterlab)
  Using cached arrow-1.2.3-py3-none-any.whl (66 kB)
Using cached async_lru-2.0.4-py3-none-any.whl (6.1 kB)
Using cached jupyterlab_server-2.25.0-py3-none-any.whl (57 kB)
Using cached pywinpty-2.0.11-cp311-none-win_amd64.whl (1.4 MB)
Using cached jsonpointer-2.4-py2.py3-none-any.whl (7.8 kB)
Using cached uri_template-1.3.0-py3-none-any.whl (11 kB)
Installing collected packages: pywin32, webcolors, uri-template, tinycss2, pywinpty, matplotlib-inline, jsonpointer, fqdn, async-lru, arrow, isoduration, jupyterlab-server
Successfully installed arrow-1.2.3 async-lru-2.0.4 fqdn-1.5.1 isoduration-20.11.0 jsonpointer-2.4 jupyterlab-server-2.25.0 matplotlib-inline-0.1.6 pywin32-306 pywinpty-2.0.11 tinycss2-1.2.1 uri-template-1.3.0 webcolors-1.13
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
From a quick look these are all `jsonschema` dependencies. Are you sure that you uninstalled both jupyterlab-server and its dependencies (i.e. `jsonschema`) correctly?

| package | dependency chain |
|--|--|
| isoduration | jsonschema>=4.17.3->jupyterlab-server<3,>=2.19.0->jupyterlab
| jsonpointer>1.13 | jsonschema>=4.17.3->jupyterlab-server<3,>=2.19.0->jupyterlab
| webcolors>=1.11 | jsonschema>=4.17.3->jupyterlab-server<3,>=2.19.0->jupyterlab
| fqdn | jsonschema>=4.17.3->jupyterlab-server<3,>=2.19.0->jupyterlab
| uri-template | jsonschema>=4.17.3->jupyterlab-server<3,>=2.19.0->jupyterlab |

**Comment by krassowski** [comment]
I guess this is because those are optional dependencies of `jsonschema` and do not show up in `pip show`.

```
pip show jsonschema
Name: jsonschema
Version: 4.18.4
Summary: An implementation of JSON Schema validation for Python
Home-page: 
Author: Julian Berman
Author-email: Julian+jsonschema@GrayVines.com
License: MIT
Location: ../site-packages
Requires: attrs, jsonschema-specifications, referencing, rpds-py
Required-by: jupyter-events, jupyterlab_server, nbformat
```

It seems that this is not a problem with `jupyterlab`, and probably not even with https://github.com/python-jsonschema/jsonschema (but maybe you can consult the authors) but with this uninstallation approach not picking up optional deps.

**Comment by MrMarvel** [comment]
Yep. it's problem that installed optional dependencies. Any way to disable that while installing jupyterlab?

**Comment by krassowski** [comment]
Again, the problem is not with JupyterLab, so I am afraid this is not something we can solve here. Simply put, pip does not remember parents of optional dependencies after install; it can be argued that this is a bug in pip, and pip maintainers are aware of it, but the solution appears to be to go through standardisation of optional dependencies (extras) via PEP first, see discussion in: https://github.com/pypa/pip/issues/10595

**Comment by krassowski** [comment]
Another option for you could be implementing a workaround in pip-autoremove package.

**Comment by MrMarvel** [comment]
Thanks for information. I will try to find a workaround for now.
