### ISSUE TITLE
Document the `bubbling_keydown` page config option?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#15158]
Follow-up to https://github.com/jupyterlab/jupyterlab/pull/15142

https://github.com/jupyterlab/jupyterlab/pull/15142#issuecomment-1735928336 raises the question of whether the new `bubbling_keydown` page config option should be documented.

https://github.com/jupyterlab/jupyterlab/pull/15142#issuecomment-1735938622 says it's not clear yet, but could be decided before releasing 4.1 final.

So opening this issue to keep track of it for 4.1.

**Comment by fcollonval** [comment]
Closing as it was removed

Xref https://github.com/jupyterlab/jupyterlab/pull/15405#issuecomment-1810351505

**Comment by jtpio** [comment]
ok thanks for the update :+1:
