### ISSUE TITLE
Error message related to ExpansionStates when refreshing a notebook

### ISSUE THREAD

**Issue by HaudinFlorence** [jupyterlab/jupyterlab#15163]
## Description
When working in dev mode and watch mode, with necessity to frequently update the view of the notebook, it has appeared that when making a change and refreshing, it may happen that operation takes time or not succeed. The following error message appears in the console:

![Screenshot from 2023-09-27 10-42-16](https://github.com/jupyterlab/jupyterlab/assets/99649086/e431b141-7079-454b-aa34-37694ff38d31)

After clicking on `Clear workspace` and refreshing another time, normally the notebook correctly restarts without error message.

## Reproduce

1. Open a notebook in dev mode and watch mode
2. Make some change in the code and wait that compilation is finished
3. Refresh the notebook
4. See that it freezes, or lead to a dialog proposing to clean the workspace. In the console, the error message is:
```
shell.ts:2072 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'expansionStates')
    at shell.ts:2072:40
    at Array.forEach (<anonymous>)
    at shell.ts:2071:31
    at Array.forEach (<anonymous>)
    at SideBarHandler.rehydrate (shell.ts:2068:36)
    at LabShell.restoreLayout (shell.ts:1205:25)
```

**Comment by krassowski** [comment]
Thank you for opening the issue. Appears related to #14901 CC @DenisaCG.

**Comment by DenisaCG** [comment]
Thanks for opening the issue @HaudinFlorence and @krassowski for pointing us towards the PR it is related to. I will investigate the behavior to figure out what seems to be the problem.

**Comment by fcollonval** [comment]
i think the fix is to replace that line:

https://github.com/jupyterlab/jupyterlab/blob/1692817b23ce35a31d02889c4af83df732c00a17/packages/application/src/shell.ts#L2070

by

```ts
const state = data.widgetStates[w.id] ?? {}; 
```

You should be able to try it by removing the widgetStates content in `$HOME/.jupyter/lab/workspaces/default-####.jupyterlab-workspace`

> The file has a hash after default that varies
