### ISSUE TITLE
Labextensions not working on starting notebook

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#1516]
Hi, 

So when I start jupyter lab with `jupyter lab` , labextensions seem to work perfectly fine, but they don't work when I start notebook : `jupyter notebook` and redirect to /lab.

**Comment by blink1073** [comment]
Hi @rsinha25, I am not seeing this behavior, are you using the latest version?   `jupyter lab --version` should be `0.13.1`.

**Comment by rsinha25** [comment]
Hi, yes I am using the latest version. So I have a config file in which I have enabled labextensions as well as a server extension that I have, and done a couple of other things. In the global Jupyter config I have set labextensions as well as that server extensions as disabled. This is because I dont want the labextensions to be enabled unless I start lab or notebook with my config. You could try doing this to reproduce the behaviour.

**Comment by rsinha25** [comment]
Thanks for the fix.

**Comment by rsinha25** [comment]
@blink1073 So, this fix about using initialize() instead of load_config_file() seems to work when I do `jupyter notebook` now.
i.e. when I do `jupyter notebook` all the labextensions work correctly also.
So, this is a valid fix for that.

But when I try to run jupyterhub with the default `jupyterhub-singleuser` it has (which uses NoteBookApp by default) I get some errors. I think this is because jupyterhub-singleuser is passing some additional things like `--user=rsinha25` and `--cookie-name`.

The command it tries to run is:

`jupyterhub-singleuser '--user="rsinha25"' '--cookie-name="jupyter-hub-token-rsinha25"' '--base-url="/user/rsinha25"' '--hub-host=""' '--hub-prefix="/hub/"' '--hub-api-url="http://127.0.0.1:8081/hub/api"' '--ip="127.0.0.1"' --port=57181`

And it errors out with the help message from jupyterlab and:

```
[C 18:58:45.281 LabApp] Bad config encountered during initialization:
[C 18:58:45.281 LabApp] Invalid argument: '--cookie-name="jupyter-hub-token-rsinha25"'
[W 2017-01-20 18:58:52.376 JupyterHub web:1545] 500 POST /hub/login?next= (::ffff:127.0.0.1): Spawner failed to start [status=1]
```

Could you suggest what is the correct way to do this ?

**Comment by blink1073** [comment]
This is going to take some thought, as it is the default behavior of a `JupyterApp`, reopening.

**Comment by rsinha25** [comment]
Hey,

Thanks a ton for the fix!
