### ISSUE TITLE
Mermaid JS context menu label is not translated

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15174]
## Description

There is no translation in:

https://github.com/jupyterlab/jupyterlab/blob/1692817b23ce35a31d02889c4af83df732c00a17/packages/mermaid-extension/src/index.ts#L74

To add translation wrappers see https://jupyterlab.readthedocs.io/en/stable/extension/internationalization.html#

## Context

- JupyterLab version: 4.1.0alpha0

**Comment by Deepali1211** [comment]
I would like to work on this issue.

**Comment by krassowski** [comment]
Please do! We have a contributing guide [here](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html) and if you need to ask a quick question about contributing/dev setup there is a [gitter channel](https://gitter.im/jupyterlab/jupyterlab). Otherwise please do open a PR.

**Comment by krassowski** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/15178
