### ISSUE TITLE
Support to override the serializer used in kernel.

### ISSUE THREAD

**Issue by DonJayamanne** [jupyterlab/jupyterlab#15198]
### Problem

I'm one of the maintainers of the Jupyter extension for VS Code.

**Context:** 

* Not really a problem, but more of a feature request.
* The Jupyter extension in VS Code makes use of the @jupyterlab/services packages and a few others extensively.
Thanks for these packages, I have mentioned to @jasongrout in the past how great and flexible they are
* Today we use these pacakges even in the cases where we start kernels locally.
* We start the kernels, use zmq to communicate and then create a fake socket that is passed via the `ServerConnection.ISettings`, brilliant design (thanks)
* However we have slightly modified version of the `default.js` file at our end, we override the serializer.

**Problem:** 

As the messages are already serialized/deseirliazed, we do not need these serializers.
Today we tweek the code slightly to ensure nothing gets serialized/deserialized in the KernelConnection class (default.ts).

I was hoping there would be a way to pass the serializer into the constructor of `KernelConnection` that would allow us (Jupyter extension in VSC) to bypass the built in serializer/deserializer, just as we can pass in a custom WebSocket class today.

This would make it possible to use the Jupyterlab package without any changes at our end.
Basically I would like to remove these little hacks/work arounds if possible.

Once again, thanks for publishing these great packages and documenting them.

### Proposed Solution

* Add an optional property to `ServerConnection.ISettings` that would contain the serializer as follows:
```typescript
export interface ISerializer { 
    /**
     * Serialize a kernel message for transport.
     */
    serialize(
      msg: KernelMessage.IMessage,
      protocol: string = ''
    ): string | ArrayBuffer ;
    /**
     * Deserialize and return the unpacked message.
     */
    deserialize(
      data: ArrayBuffer,
      protocol: string = ''
    ): KernelMessage.IMessage;
}

export interface ISettings {
.....
    serializer?: ISerializer;
....
}

// The `ServerConnection.makeSettings` would then return create the default serializer in there.
```

### Additional context

* Applies to Jupyter extension in VS Code.

**Comment by krassowski** [comment]
Please feel welcome to submit a pull request, I can help with review.

**Comment by DonJayamanne** [comment]
@krassowski 
Here's the draft PR for review/discussion https://github.com/jupyterlab/jupyterlab/pull/15254

**Comment by echarles** [comment]
@DonJayamanne Out of curiosity, why are you passing a custom serializer? (any link to the vscode python extension which does that).

This being asked, I am +1 for your feature request.

**Comment by DonJayamanne** [comment]
Sure thing, here's the use case  https://github.com/jupyterlab/jupyterlab/issues/15198#issue-1921291762

& here's the code https://github.com/microsoft/vscode-jupyter/blob/a7273447d758f170917c58b80503d308c0381c93/src/kernels/raw/session/rawKernelConnection.node.ts#L563C12-L563C12

Basically the messages are already de-serialized as a kernel JSON message

**Comment by DonJayamanne** [comment]
@krassowski Thank you for adding the test & merging this PR,
 I'm so very sorry I couldn't get to adding the tests.
