### ISSUE TITLE
Highlight parenthesis character only and not the entire block

### ISSUE THREAD

**Issue by joelostblom** [jupyterlab/jupyterlab#15196]
### Problem

Currently, matching parenthesis are indicated by highlighting the entire block the parenthesis is in, rather than just the parenthesis character itself. This makes it difficult to tell apart the cursor from the highlighted parenthesis as they melt into each other as you can see in this short clip:

https://github.com/jupyterlab/jupyterlab/assets/4560057/a0d39266-fed4-415d-a1df-b646cccb6573

a block cursor from a highlight parenthesis and is confusing when moving through text quickly.

### Proposed Solution

I think it is much easier to keep track of the cursor position if just the parenthesis character is highlighted, rather than the entire block. This is how things look in vim for me:

https://github.com/jupyterlab/jupyterlab/assets/4560057/c7322fea-935e-4a26-854e-dbd98749d0d1

### Additional context

I believe this is a recent change, possibly new in 4.0, because I recently upgraded from 3.6 and immediately reacted to how hard it was to tell where my cursor is. Note that I do use vim mode for the cursor to be a block, but I believe this is a general issue for any block cursor.

Any CSS workaround that can be applied right away until there is a fix forthis would be much appreciated. I think this also affect non-block cursors to a lesser extent because the block highlight generally introduces more visual noise

**Comment by krassowski** [comment]
A css workaround would be something like:

```css
.cm-matchingBracket {
    background-color: unset!important;
    text-decoration: underline;
}
```

Slightly related, an extension that hooks in https://github.com/eriknewland/rainbowbrackets would be a real pleasure (it would be really just a few lines of code).

**Comment by krassowski** [comment]
It looks this is coming from CodeMirro6 itself, we only adjust the colour in dark theme to:

https://github.com/jupyterlab/jupyterlab/blob/76496c553c757ce7955293f444392e79888b23f4/packages/codemirror/test/onedarktheme.ts#L86-L89

**Comment by krassowski** [comment]
My instinct would be to suggest that CSS could be adjusted in codemirror-vim when block cursor is in use, with a setting to opt-out from the adjustment.

**Comment by joelostblom** [comment]
Great, thank you for the quick response and the workaround! I opened this same issue in the jupyterlab-vim repo since you mentioned it is more suitable to fix there. https://github.com/jupyterlab-contrib/jupyterlab-vim/issues/118
