### ISSUE TITLE
Table of contents should not enter the edit mode of markdown cells

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15228]
At least <s>three</s> four users reported that they strongly prefer the previous behaviour of table of contents navigation. In 3.x clicking on heading in ToC would scroll to the appropriate position. In 4.x it scrolls (when it works) and then enters the edit mode (unrenders the markdown cell).

> I am on  4.0.6.
> The current behavior of [ click on TOC -> scroll then start edit] is a change from previous behavior;
> the current behavior degrades the navigation experience for me, for no gain.
> I have many code cells inbetween heading cells. So my main intention when clicking a heading is to scroll to the start of such a section.  Almost never do I want to edit the cell I click on the TOC.
> It's worse when I don't notice that the cell I scrolled to was edited (again, because the behavior was changed), and keep going through my normal usage only for then having to find the cell that was left in edit mode and put it back into display mode so that proper navigation is restored.
> _Originally posted by @LunarLanding in https://github.com/jupyterlab/jupyterlab/issues/14591#issuecomment-1740461474_
            

> This would also solve the problem that appears some times when the hyperlinks of the TOC don't work and makes the navigation through the notebook cumbersome (I guess that is why the "Run all markdown cells" option exist)
> _Originally posted by @rodrigo-j-goncalves in https://github.com/jupyterlab/jupyterlab/issues/15165#issue-1915060209_

> When you select a heading in the table of contents, it automatically starts editing the cell. This is not preferred behavior for me, but I can live with it.
> _Originally posted by @minerharry in https://github.com/jupyterlab/jupyterlab/issues/14591#issue-1724821913_

Fourth user is the author of this issue :)

**Comment by jpcaram** [comment]
Is there a workaround we can apply in the meantime, like running some JS in a notebook that will improve this behavior?
