### ISSUE TITLE
Option to disable "Click to add cell."

### ISSUE THREAD

**Issue by davlondev** [jupyterlab/jupyterlab#15224]
Is there any current method to disable the button that appears under cells that says "Click to add cell"
I'm using jupyterlab-vim and my cursor keeps focusing on the button

Thanks

**Comment by davlondev** [comment]
downgraded to jupyterlab 3.5.0 to fix

**Comment by weibeld** [comment]
This button also breaks normal command mode. When navigating through the cells with `J` and passing the last cell, the focus sticks on the "Click to add cell" button and no key can get it off from there. One must click with the mouse on a cell to be able to navigate again.

This is very bad UX and certainly should be fixed.

@davlondev Did you consider reopening the issue?

**Comment by krassowski** [comment]
@weibel this was fixed by https://github.com/jupyterlab/jupyterlab/pull/14796 which was released in [v4.0.7](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.7) over a week ago. I suspect that you are using an older version, is this correct?

**Comment by krassowski** [comment]
Based on https://github.com/jupyter/notebook/issues/7118#issue-1954724231 I see that you were using 4.0.5.

**Comment by weibeld** [comment]
Perfectly fixed in JuypterLab 4.0.7, thanks
