### ISSUE TITLE
can't use scrollbars when print dataframe in R kernel.

### ISSUE THREAD

**Issue by li1311139481** [jupyterlab/jupyterlab#15235]
## Description

When I print 1:12column of dataframe in R kernel
i get 
![image](https://github.com/jupyterlab/jupyterlab/assets/109973822/6d7240c4-2c1f-454c-a25a-a70d7d751415)
It works well.
But when i print 1:13column or more of dataframe in R kernel
i get:
![image](https://github.com/jupyterlab/jupyterlab/assets/109973822/57df4770-e204-496a-9ec4-2b4945ad7305)
In previous versions of jupyterlab, if the data box had too many columns, we could see more information through the scroll bar at the bottom of the data box. But jupyterlab 4.0.6 does not have scrollbars

- Operating System and version: `Linux version 3.10.0-514.21.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Thu May 25 17:04:51 UTC 2017`
- Browser and version: ` Firefox 118.0.1`
- JupyterLab version: `4.0.6`

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
I believe this is a duplicate of #14625 (a Firefox-specific rather than R-specific issues) which has a fix in works. Do you agree?

**Comment by li1311139481** [comment]
> I believe this is a duplicate of #14625 (a Firefox-specific rather than R-specific issues) which has a fix in works. Do you agree?

Thanks for your response, I will close this issue and then track #14625
