### ISSUE TITLE
Disable existing plugins through labextension

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#1523]
Is it possible to disable certain existing plugins of JLab through extensions? Eg: If I wish to disable the launcher plugin on the left panel, so that I only see files,commands,running etc.

**Comment by blink1073** [comment]
This is not currently possible but certainly something we can offer for 1.0.

**Comment by rsinha25** [comment]
@blink1073 I'd like to contribute this as it's a higher priority for me. Can you give me some pointers on what to look at to do this ?

**Comment by blink1073** [comment]
We are going to be completely changing the way extensions are built and loaded as part of #1011, specifically https://github.com/jupyterlab/jupyterlab/issues/1011#issuecomment-272961881.  I'll leave this open as a beta issue so we are reminded to reengage with you when we finish that effort.

**Comment by rsinha25** [comment]
@blink1073 I see, I haven't followed the issue 1011 completely. But I have one question which could impact me at the moment - if I have some existing plugin written on JupyterLab 0.13.1, would I need to change it because of Issue 1011 ?

**Comment by blink1073** [comment]
Yes, any of our `0.x` releases are considered breaking changes from an API standpoint.

**Comment by AbdealiJK** [comment]
@blink1073 Now that the python loader is being thought of in https://github.com/jupyterlab/jupyterlab/issues/1011 I think the config can even disable the builtin plugins if needed and create the final bundle without the plugin marked as disable ?

**Comment by blink1073** [comment]
Yep, this will be straightforward once we have the python bundler in place.

**Comment by blink1073** [comment]
This can be implemented by adding support for [ignorePlugins](https://github.com/phosphorjs/phosphor/blob/d8d934df798dd64a6e84461d02efc789e076d759/packages/application/src/index.ts#L580) in `labconfig`.  We would read the value from `labconfig`, provide it as [config data](https://github.com/jupyterlab/jupyterlab/blob/3068306797df8bf03f1cc809e0863db193a7d794/jupyterlab/extension.py#L83), and give it to [lab.start()](https://github.com/jupyterlab/jupyterlab/blob/3068306797df8bf03f1cc809e0863db193a7d794/jupyterlab/lab.html#L72).

**Comment by blink1073** [comment]
I don't think it is feasible to do this at the build step because it does not have the context about which JavaScript modules correspond to which plugins, and a JavaScript module can contain more than one plugin.   cf #1973.

**Comment by blink1073** [comment]
@rsinha25, I don't consider this blocked anymore if you want to implement the `labconfig` approach above.
