### ISSUE TITLE
I want know how to make a production environment and release the jupyter lab

### ISSUE THREAD

**Issue by JHC000abc** [jupyterlab/jupyterlab#15247]
how to make a self production version for jupyterlab when I change some css file under /packages file

**Comment by JasonWeill** [comment]
@JHC000abc Thanks for reaching out! You can find information about setting up a local development environment here: https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#setting-up-a-local-development-environment

If you only want to change CSS for your local environment, you can find instructions on creating a custom theme here: https://jupyterlab.readthedocs.io/en/latest/extension/extension_dev.html#theme-plugins

If you have other questions about setting up a development environment, I recommend opening a thread on [Discourse](https://discourse.jupyter.org/) or [Gitter](https://gitter.im/jupyterlab/jupyterlab#). Thanks for your interest in JupyterLab!
