### ISSUE TITLE
Request for a feature to permanently disable automatic scrolling for outputs

### ISSUE THREAD

**Issue by jedreky** [jupyterlab/jupyterlab#15249]
### Problem

I often create cells that produce a reasonably long output, usually a mix of figures and text. Currently, every time I execute such a cell the output is collapsed to just a few lines (where I basically cannot see anything) and in order to see it I have to manually click on "disable scrolling for outputs". Given that I usually make many small tweaks to the cell, I tend to spend a lot of time on "right-click + disable scrolling for outputs", which is extremely frustrating.

### Proposed Solution

* Add an option so that scrolling is disabled for all output cells for the entire notebook
or
* Add an option so that a cell for which scrolling has been disabled remains in that state even after a new execution

**Comment by JasonWeill** [comment]
Info on the setting to enable scrolling by default: #4028.

There are a few other issues concerning output scrolling: https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aissue+is%3Aopen+output+scrolling .

**Comment by JasonWeill** [comment]
@jedreky To clarify, are you using JupyterLab or Jupyter Notebook? Which version are you running? You can run `jupyter --version` and share the output in a comment.

**Comment by jedreky** [comment]
Hey @krassowski and @JasonWeill, thanks a lot for taking interest in this issue and sorry for slow reply... Based on the info you provided, I dug a little deeper into this and I realised this doesn't happen if I'm just printing text. However, it does happen when I display a mix of text and figures, so it might be an issue at the intersection of jupyter and matplotlib.

Minimal reproducible example:
```
import matplotlib.pyplot as plt
for _ in range(3):
    fig, _ = plt.subplots()
    display(fig)
```

A short video of this can be found here: https://filetransfer.io/data-package/PTcAhFe8#link

Relevant part of pip freeze:
```
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.8.0
jupyter-lsp==2.2.0
jupyter_client==8.4.0
jupyter_core==5.4.0
jupyter_server==2.8.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.7
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.9
jupyterlab_server==2.25.0
kiwisolver==1.4.5
MarkupSafe==2.1.3
matplotlib==3.8.0
matplotlib-inline==0.1.6
```

jupyter --version
```
Selected Jupyter core packages...
IPython          : 8.16.1
ipykernel        : 6.25.2
ipywidgets       : 8.1.1
jupyter_client   : 8.4.0
jupyter_core     : 5.4.0
jupyter_server   : 2.8.0
jupyterlab       : 4.0.7
nbclient         : 0.8.0
nbconvert        : 7.9.2
nbformat         : 5.9.2
notebook         : 7.0.5
qtconsole        : 5.4.4
traitlets        : 5.11.2
```

Finally, I seem to have a found a working solution. Basically, if I add `plt.close()` immediately after `display(fig)` the problem goes away and also the figures aren't listed at the end of the output, which is good.

So perhaps this is all my fault and I just don't know what the correct way of displaying figs + text in the same output is :) If you have any suggestions which are better than what I have above, I'd appreciate them :)

**Comment by krassowski** [comment]
Your video shows Jupyter Notebook, not JupyterLab, which has an issue tracker here: https://github.com/jupyter/notebook/issues.

**Comment by krassowski** [comment]
(again, there is no logic for automatically enabling scrolling of outputs in JupyterLab, what you see is the Jupyter Notebook behaviour)

**Comment by krassowski** [comment]
It's a bit like with web browsers:
- There is Chrome and Edge, both use Chromium underneath, both allow to display and interact with HTML files (websites), both have features that the other does not have (e.g. Google account integration vs Microsoft integration)
- We have Jupyter Notebook and JupyterLab, both use the same core packages underneath, both allow to display and interact with ipynb files (Jupyter notebooks), both have features that the other does not have (e.g. auto-scroll vs multi-panel view)

When you report a bug in the Edge repository but you are really using Chrome, and the problem you report is so specific to Chrome that it does not exist in Edge (say Google account integration), the Edge maintainers just cannot address your issue because it is not in the browser they maintain. Same here.

**Comment by jedreky** [comment]
Ok, I get it now, thanks for the explanation, sorry for having wasted some of your time, I'll try to be more careful in the future

**Comment by ryukinix** [comment]
There is no config like `Disable Scrolling for Outputs` to add in `~/.jupyter/jupyter_lab_config.py`?
