### ISSUE TITLE
complate problems

### ISSUE THREAD

**Issue by JHC000abc** [jupyterlab/jupyterlab#15253]
I used command  to complate the project such as under,but it failed.
1. git clone https://github.com/jupyterlab/jupyterlab.git
2. cd jupyterlab
3. git checkout v4.0.6
4. In this , I change some style in /jupyterlab/packages/application/style/core.css 
5. pip install -ve .
6. jupyter lab build 
7. when it complate finished ,I used "jupyter lab --port=9999 --ip=0.0.0.0 --allow-root --dev-mode" to run the jupyterlab ,I change in core.css show success .but when I did not used --dev-mode to start jupyterlab it failed

I want to know how to solve my problem ?

I already read all docs about this project.

**Comment by JHC000abc** [comment]
my base environment is:

ubuntu
docker
python 3.10
nodejs 18

**Comment by krassowski** [comment]
If you want to modify the assets for deployment you need to follow the optional commands listed in https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#installing-jupyterlab

**Comment by JasonWeill** [comment]
Closing per @krassowski 's comment; please try rebuilding your assets.
