### ISSUE TITLE
Full windowed mode for notebooks enabled by default

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15258]
### Problem

Full windowing mode brings performance enhancements for users with long notebooks. This mode being disabled by default means that users do not benefit from it, and means that it may not be fully tested/may regress over time.

### Proposed Solution

Enable the mode by default.

### Additional context

It was disabled in the run-up to 4.0 release by https://github.com/jupyterlab/jupyterlab/pull/14490 because of a number of regressions, as noted in the discussion in https://github.com/jupyterlab/jupyterlab/issues/14455

Work is ongoing on an additional UI element which will enhance the user awareness and navigation in the `full` mode:
- https://github.com/jupyterlab/jupyterlab/pull/15533

### Blockers

There is a number of issues which we need to address before we enable `full` windowing mode, most related to scrolling:
- https://github.com/jupyterlab/jupyterlab/issues/13343
- https://github.com/jupyterlab/jupyterlab/issues/14092
- https://github.com/jupyterlab/jupyterlab/issues/14878
- https://github.com/jupyterlab/jupyterlab/issues/14881
- https://github.com/jupyterlab/jupyterlab/issues/15073
- https://github.com/jupyterlab/jupyterlab/issues/15330
- https://github.com/jupyterlab/jupyterlab/issues/15352
- https://github.com/jupyterlab/jupyterlab/issues/15407
- https://github.com/jupyterlab/jupyterlab/issues/15415
- https://github.com/jupyterlab/jupyterlab/issues/15465
- https://github.com/jupyterlab/jupyterlab/issues/15594
- https://github.com/jupyter/notebook/issues/7231

### Nice to have

- https://github.com/jupyterlab/jupyterlab/issues/13172
- https://github.com/jupyterlab/jupyterlab/issues/16007
- https://github.com/jupyterlab/jupyterlab/issues/14728

Related meta-issues:
- https://github.com/jupyterlab/jupyterlab/issues/14106

**Comment by fcollonval** [comment]
@krassowski I have time to work on those issues. Could you please list the one you are currently working on to avoid overlap?

**Comment by krassowski** [comment]
I self-assigned to #14881 #14878 and #15073. It is a pity GitHub paused onboarding to [task lists](https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/creating-a-tasklist) which we used in nbdime.

**Comment by fcollonval** [comment]
> I self-assigned to https://github.com/jupyterlab/jupyterlab/issues/14881 https://github.com/jupyterlab/jupyterlab/issues/14878 and https://github.com/jupyterlab/jupyterlab/issues/15073.

Thanks, I'll assign myself too. I'll focus first on improving the cell height estimator (#13343) and #14092.

> It is a pity GitHub paused onboarding to [task lists](https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/creating-a-tasklist) which we used in nbdime.

Indeed

**Comment by jtpio** [comment]
Is there an issue to track the remaining open issues listed in the top comment?

So we don't lose track of them, and have the outstanding items more visible for the `4.2.0` release.

For example https://github.com/jupyter/notebook/issues/7231 is still present and might require temporarily defaulting to `defer` until it's fixed.

And we might also want to have a place to collect feedback from users testing the beta with the `full` windowing mode.

**Comment by krassowski** [comment]
I

**Comment by krassowski** [comment]
Closing as JupyterLab 4.2.0 was released.
