### ISSUE TITLE
Galata's `setCell` helper does not work reliably

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15252]
## Description

As seen in https://github.com/jupyterlab/jupyterlab/pull/15171 galata's `setCell` helper does not always set cell content correctly. This was also seen in other, older pull requests. A temporary workaround of calling it twice was introduced in fb079b71d06faea5e46ca4a61926617de7e8059a which works but is hinting at some problem.

The problematic runs locally exhibited an odd behaviour of switching the `code` cell type to `raw` even though this was never requested. It might be that the problem is not in `setCell` but in `setCellType` which is the first call of the former:

https://github.com/jupyterlab/jupyterlab/blob/2ff689965169cb5df6d1860e5b5c40952ed668ba/galata/src/helpers/notebook.ts#L1053-L1094

Further, from debugging with playwright it seemed that it could have been due to the notebook in panel not being returned at the first attempt leading to incorrect result of cell type `null` on `getCellType` check:

https://github.com/jupyterlab/jupyterlab/blob/2ff689965169cb5df6d1860e5b5c40952ed668ba/galata/src/helpers/notebook.ts#L1103-L1112

https://github.com/jupyterlab/jupyterlab/blob/2ff689965169cb5df6d1860e5b5c40952ed668ba/galata/src/helpers/notebook.ts#L1147-L1151

but I am not sure if the runs with instrumentation were representative of what is happening without it.

JupyterLab main head 4.1.0a1

**Comment by fcollonval** [comment]
Thanks for digging this one up Mike. I agree on your conclusion that unfortunately instrumentation introduces biases.

**Comment by krassowski** [comment]
I think this is no longer a problem after recent refactors.
