### ISSUE TITLE
Cell collapsing results in half-width preview cells

### ISSUE THREAD

**Issue by andmis** [jupyterlab/jupyterlab#15269]
## Description

4.0.7:
<img width="836" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/5308024/91648740-471e-4cdd-946c-c45450ea9b4f">

4.0.5:
<img width="790" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/5308024/2d5c1af0-8b5f-4bdf-abb0-8ab996a74c81">

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: macOS latest
- Browser and version: Chrome latest
- JupyterLab version: 4.0.7

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by fcollonval** [comment]
This is a consequence of https://github.com/jupyterlab/jupyterlab/pull/15171
