### ISSUE TITLE
notebook not automatically jumping to the end of the output

### ISSUE THREAD

**Issue by hnykda** [jupyterlab/jupyterlab#1526]
Hi,

I just started using jupyter lab instead of notebook and I am astonished how awesome, functional and beautiful it is!

I found one thing which is odd to me (and not consistent with previous behaviour). I am not sure if this is a bug though, maybe it is on purpose and in that case just close the issue please. When I have to splits one on top of another (I use portrait oriented monitor) and I execute something which produce outputs in the top split, e.g here:
![image](https://cloud.githubusercontent.com/assets/2741256/22156414/6b86fa4a-df33-11e6-861d-423228fc7a3f.png)

the output won't scroll to the end of it nor is "squashed" under smaller scrollable window as it does in Jupyter Notebook. It just displays "under the bottom split":
![image](https://cloud.githubusercontent.com/assets/2741256/22156403/61119b6a-df33-11e6-9388-57e8d2663c47.png)

Or maybe is the scrollable window to big to have a reason to do this? IMHO it could be a bit smaller as it is in the old notebook.

**Comment by blink1073** [comment]
Yep, both of these are feature parity issues.

**Comment by hnykda** [comment]
Maybe this is relevant and can give you more information. Consider this layout (hope you don't mind in this case that it is not a minimal example - I believe you can derive it yourself):
![image](https://cloud.githubusercontent.com/assets/2741256/22173265/7f609596-dfbd-11e6-81ac-077fc7131dea.png)
Now I press SHIFT+ENTER to execute cell `24`:
![image](https://cloud.githubusercontent.com/assets/2741256/22173268/93151184-dfbd-11e6-9c9b-8548d984b46f.png)

So it automatically jumps to the next cell hiding all input from the executed cell, I have to manually scroll up to see it:
![image](https://cloud.githubusercontent.com/assets/2741256/22173269/a7dfbefc-dfbd-11e6-8c6e-820ff723e2de.png)

**Comment by blink1073** [comment]
Thank you for the further clarification, there are two differences here from the classic notebook:  

- We are not (yet) constraining large text outputs - tracked in #1309
- The classic notebook would not scroll to the next cell until you hit "Enter" and then started typing in the next cell (Assuming Shift+Enter), or executed said cell.

@ellisonbg, @cameronoelsen, what do you think the behavior should be for the latter?

**Comment by jasongrout** [comment]
From the JLab meeting:

* Implement the heuristic that shift-enter selects the next cell, but doesn't focus, and scrolls the top of the executed output halfway up the page.
* On enter (to switch from command to edit mode), scroll the focused cell to halfway up the page. 

Maybe we should only do the focus scrolling if the focused cell is off the page, or very close to the edge?

**Comment by jorisvandenbossche** [comment]
I also just wanted to report an issue about this (executing a cell jumps to the next, potentially hiding the new output of the just executed cell if the next cell is long), but then found this issue. Posting the gifs I made anyway:

Current jupyter notebook:
![peek 2017-02-19 22-32](https://cloud.githubusercontent.com/assets/1020496/23106864/3e27775e-f6f4-11e6-8e82-8aa50f7927bc.gif)

With jupyterlab:
![peek 2017-02-19 22-34](https://cloud.githubusercontent.com/assets/1020496/23106865/3fb7c8da-f6f4-11e6-984e-f9cba76ab61a.gif)

**Comment by blink1073** [comment]
Related report from @jorisvandenbossche in https://github.com/jupyterlab/jupyterlab/issues/1810.
