### ISSUE TITLE
Installing plugin results in jupyterlab version change after restart

### ISSUE THREAD

**Issue by russellsmithies** [jupyterlab/jupyterlab#15277]
I'm not sure what category this falls under - it was certainly unexpected.
We're running the latest 4.0.7 and have plugins enabled for users.  A user searched for the "[jupyterlab-snippets](https://github.com/QuantStack/jupyterlab-snippets)" plugin and installed it - we'd used it on older 3.x releases. After restarting jupyterlab it appeared we'd downgraded to v3.6. This was totally unexpected!!
Now I guess I have to block this plugin, but I'm not sure why an incompatable plugin was displayed in the search results?   Is restricting plugins to just "@jupyterlab/*" going to solve this or am I going to have to disable all plugins so a user doesn't accidently downgrade jupyterlab?
Ideally the search would _only_ bring back plugins that are compatable with the currently installed jupyterlab version, or is there a way of configuring this already that I've overlooked?

thanx  :-)

**Comment by russellsmithies** [comment]
I did see the warnings on the "[Extensions](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#)" page but I (wrongly) assumed that it would just mean the plugin woudln't work.

**Comment by krassowski** [comment]
I think that it would make sense to force-pin the version of jupyterlab in the default (pip) plugin manager implementation, so that it is never changed. That would involve updating:

https://github.com/jupyterlab/jupyterlab/blob/9d360bb373af7075e23511685fde152891a83eeb/jupyterlab/extensions/pypi.py#L280-L293

In addition we should have `requires` info for packages (but not their dependencies, at least not on a first request!) and should be able to reject installation of incompatible packages, but many will not pin to any version of jupyterlab so it will just not be very reliable.

**Comment by russellsmithies** [comment]
Thanx, I'm glad it made sense  :-)
We run JupyterLab in a conda env as a service so I wasn't sure if it was something from our setup that was weird and causing problems.  For now I've installed some useful plugins for our users but disabled the extension manager plugin so it's harder (but probably not impossible) for them to add more.

**Comment by Sarthug99** [comment]
Hi @krassowski, I am eager to make my first open source contribution. Could you assign this issue to me and provide some guidance on how I can resolve the issue?

**Comment by fcollonval** [comment]
Thanks for proposing your help @Sarthug99 (as soon as you have commented on an issue you can self assign to it :wink: - we don't have a policy of assigning people to issue).

To provide you with some guidance, a way to solve this would be to add a constrain when executing the `pip install` command at

https://github.com/jupyterlab/jupyterlab/blob/9d360bb373af7075e23511685fde152891a83eeb/jupyterlab/extensions/pypi.py#L280-L293

What I would suggest to do is:

1. wrap the lines 280 to 363 within a context that provide you with a temporary named file:

```py
with tempfile.NamedTemporaryFile() as fconstraint:
    cmd_line = [
```

2. Write the jupyterlab version constrain in that temporary file:

```py
with tempfile.NamedTemporaryFile() as fconstraint:
    fconstraint.write(f"jupyterlab=={__version__}")
    cmd_line = [
```

You can import `__version__` from `jupyterlab._version`

3. Add the following additional CLI options at the end of the `cmd_line` list:

```py
with tempfile.NamedTemporaryFile() as fconstraint:
    fconstraint.write(f"jupyterlab=={__version__}")
    cmd_line = [
        # ...
        "--constraint",
        fconstraint.name
    ]
```

**Comment by russellsmithies** [comment]
Damn, got caught out again - blimmin arcgis downgraded me to 3.6.
I might have to give up on 4.x until this is sorted as it's making our server unusable  :-(

**Comment by pipilacha** [comment]
I would like to assist in solving this issue

**Comment by Sarthug99** [comment]
Hi pipilacha! I'm already working on this issue and am almost done with the implementation...
