### ISSUE TITLE
[Debugger] float variable equal to math.inf displayed as NaN

### ISSUE THREAD

**Issue by pierre-haessig** [jupyterlab/jupyterlab#15273]
## Description

In JupyterLab Debugger, when debugging a code with a `float` variable having infinity value (i.e. from `math.inf`, `numpy.inf` or `float('inf')`), the variable is displayed as `NaN` in the Variables panel, see screenshot:

![screenshot JLab_debugger_inf_NaN](https://github.com/jupyterlab/jupyterlab/assets/1010404/f8319040-dba0-40d5-a71b-b5754a714983)

## Reproduce

Create new notebook in JupyterLab using a Python kernel ("classical" kernel, not xeus-python which I didn't tested.

Add cell with code:

```python
import math
a = math.inf
b = -a
print(a)
```

Run the cell and enable JupyterLab debugger → see the Variables panel.

## Expected behavior

Variables having a +inf or -inf value should be displayed as such.

## Context

- Operating System and version: Linux Ubuntu 22.04
- Browser and version: tested with
  - Firefox 118.0.2 (64 bits)
  - Chromium Version 118.0.5993.70 (Build officiel) snap (64 bits)
- JupyterLab version: 4.0.6

**Comment by andrewfulton9** [comment]
I was able to reproduce this as well.

**Comment by pierre-haessig** [comment]
is it easy to fix? I have no experience with JLab's codebase. Is it a problem in Javascript?

**Comment by ashna1jain** [comment]
Hey can someone assign this issue to me? I have fixed this.
