### ISSUE TITLE
The notebook renderer has XSS risks.

### ISSUE THREAD

**Issue by WangChangsongGit** [jupyterlab/jupyterlab#15275]
## Description

1. If the cell execution result is HTML and the HTML contains a JavaScript script, the script is executed after the ipynb file is opened, causing XSS attacks.
2. When a PDF file containing a JavaScript attack script is uploaded and opened, the JavaScript is executed, causing XSS attacks.

## Reproduce

1. Open a blank ipynb.
2. Enter the following code in the cell:
    ```
    %%html
    <img src onError=alert('abc')>
    ```
3. After the execution is complete, the execution result is displayed. The JavaScript in the HTML file is executed, and abc is displayed in the dialog box.

When a PDF file containing a JavaScript attack script is uploaded and opened, the JavaScript is executed, causing XSS attacks.
packages/pdf-extension/src/index.ts

Check the jupyterlab source code packages/pdf-extension/src/index.ts,
The sandbox attribute is not added to the iframe of the PDF file, which may cause XSS injection attacks.

```
    // We put the object in an iframe, which seems to have a better chance
    // of retaining its scroll position upon tab focusing, moving around etc.
    const iframe = document.createElement('iframe');
    this.node.appendChild(iframe);
```

## Expected behavior

Add the sandbox attribute to the container to prevent XSS attacks.

## Context

- Operating System and version: windows
- Browser and version: Google Chrome 118.0.5993.71
- JupyterLab version: 3.6.5

**Comment by krassowski** [comment]
@WangChangsongGit please do not report security vulnerabilities via GitHub issues but instead follow the responsible disclosure practices by sending an email as requested in https://github.com/jupyterlab/jupyterlab/security.

Addressing your concerns:
1. When HTML is embedded in cell output, it is only executed when the notebook is trusted. This prevents a risk of accidental leaks when a third party sends a maliciously prepared notebook. When notebook gets modified outside of user's Jupyter application, the signature no longer matches and sanitizer removes any insecure tags, in your example:
   ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/130dd399-4280-489c-87d5-c29fe8c19748)
   A user would need to manually trust the notebook at which point they take the responsibility. Please see about [Jupyter Notebook security model here](https://jupyter-notebook.readthedocs.io/en/6.2.0/security.html) and if you have improvements to propose feel welcome to open specific issues :)
2. The JavaScript in PDF files is highly constrained and **does not** allow access to `document`, `window`, or `app.cookies` so it appears unlikely to be an XSS vulnerable, that said if believe it is please send an email with the details as per our security policy. We can certainly add a sandbox guard for PDFs the same way we initially open all HTML documents as non-trusted, but this has a downside of disabling certain accessibility features by default.

**Comment by JasonWeill** [comment]
@WangChangsongGit Thank you for your contribution! As @krassowski said, this is not the appropriate forum for reporting security issues; please send email, as requested in https://github.com/jupyterlab/jupyterlab/security.
