### ISSUE TITLE
Ruler lines are at wrong places in a text editor

### ISSUE THREAD

**Issue by hanhua** [jupyterlab/jupyterlab#15292]
## Description

The vertical ruler lines are at incorrect columns, at least in the case when line numbers are shown. 

For example,
- If line numbers have two digits, the ruler lines are 2 to 3 characters to the left of the place where they are supposed to be.
- If line numbers have three digits, the ruler lines are 3 to 4 characters to the left.

## Reproduce

Just set the one or more rulers and open an text file. 

## Context

- Operating System and version: Server: Debian 11, Ubuntu 22.04, Client: Windows 11
- Browser and version: Edge 118.0.2088.57, Chrome 118.0.5993.89, Firefox 118.0.2.
- JupyterLab version: 4.0.7

## Screenshot 

![image](https://github.com/jupyterlab/jupyterlab/assets/54213262/f0f745c7-8c4c-4082-8cd3-d98ca27d05da)

User preference.
```
{
    "scrollPastEnd": true,
    "toolbar": [],
    "editorConfig": {
        "cursorBlinkRate": 530,
        "lineWrap": "on",
        "rulers": [
            10,
            20,
            80,
            96
        ],
        "fontFamily": null,
        "fontSize": null,
        "insertSpaces": true,
        "lineHeight": null,
        "readOnly": false,
        "showTrailingSpace": true,
        "wordWrapColumn": 80
    }
}
```

**Comment by krassowski** [comment]
From a quick glance it looks that hard-coded padding in:

https://github.com/jupyterlab/jupyterlab/blob/897418f0f25ffbbee3aa06a62770a53246823f85/packages/codemirror/src/extensions/rulers.ts#L42-L90

may need replacing with the padding of the line/total width of the gutter (which includes the line numbers but can also include the debugger marks and other markers which make it wider)
