### ISSUE TITLE
The use of space in kernel/tab hierarchy should be improved

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15294]
### Problem

I often use the "Kernels" panel of the "Running Terminals and Kernels" sidebar to re-open notebooks/consoles for kernels which are running in the background after closing the tab. This used to be rather straightforward in JupyterLab 3.x but got quite less convenient in JupyterLab 4.0:

| JupyterLab <4 | JupyterLab 4.0 |
|---|---|
|![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/8cb91289-078d-4c80-a5c0-79787eb6d63f) | ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/e2feb88f-0982-48a8-82d9-bd4d5c1ec545) |

In both cases I closed the tab with `Unititled6.ipynb`; previously I could just click on it again in the "Kernels" section but now I need to:
- close the remaining two panels (and then)
- scroll back and forth to find it amid the repetitive "Python 3 (ipykernel)" grouping.

### Proposed Solution

Steps:
1. It could help if the kernels hierarchy auto-collapsed when a kernel has only one child. However, currently, when the hierarchy gets manually collapsed it is of little use
2. It could be handy to show both the kernel name and the notebook name in such cases
3. The repetitive part "Python 3 (ipykernel)" could be moved up to a new hierarchy level, so that each kernel group nests 1 or more kernels, and each kernel nests one or more tabs (main area widgets) attached to that kernel

| Step 1 | Step 2 | Step 3* |
|--|--|--|
| ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/72ae253b-394e-48bf-b0af-493a4b64a594) | ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/9b9b1ba5-069f-4402-8ec8-e05a8b3cfe03) | ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/47aa9f88-8076-41d4-8cd4-bda01e6924b8) |

\* Step 3 shows a slightly different but more representative situation where there are kernels of two different types, and where there are two notebooks attached to the same kernel.

### Additional context

- https://github.com/jupyterlab/jupyterlab/pull/13851
- https://github.com/jupyterlab/jupyterlab/issues/13779

**Comment by mlucool** [comment]
I liked opening the old notebooks with a single click but now I still think I would still need to expand then click?

Also, for many users most kernels are python 3, so it is distracting to that as the first characters (it's harder to scan). Can we use some light boarder (like dotted lines) to group and go back towards the old ui? Is the kernel name useful here? If so, can it come second instead of first?

Something like this (without the resizing squares paint added):
![image](https://github.com/jupyterlab/jupyterlab/assets/1813603/f2ea17fd-a686-41e0-807f-c042956f8ecf)

**Comment by ColinConwell** [comment]
+1 for something that allows the user to either revert to JupyterLab <4 style single line entries, or an option to organize by "kind" of kernel. This would amount to adding a setting that basically reorders the underlying JSON, perhaps?

At the moment, the Dropdown style does not seem to be adding much in terms of readability / usability. Most of my kernel instances (for example) are launched from the same kernel, and are being used by only notebook. So I in essence get a bunch of DropDowns with only one entry and the same exact header.

On that note, perhaps adding some sort of readable (unique) KernelID would make this more intuitive?

<img width="420" alt="Screenshot 2023-10-25 at 12 24 21 PM" src="https://github.com/jupyterlab/jupyterlab/assets/23064382/a0465740-41c0-4354-b839-48cbd0cf6455">
``

**Comment by GabrielaVives** [comment]
@krassowski I'm working on several suggestions for a kernel and tab side panel refactor, brining together all the issues that have been opened on this subject. 

I have a question about your idea in step 3. What does the second level of drop-downs represent? What is the use case behind it? 

<img width="422" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/105775162/e48a713d-2d90-4b6f-9603-1540ffa0350b">

I'm not familiar enough with how kernels are used and what for.

**Comment by krassowski** [comment]
Answering @GabrielaVives question, my proposal includes the three levels:

### 1) Kernelspecs
The top level corresponds to `kernelspec`s which are not processes, but "recipe"s for how to make kernels.

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/88289a2f-bf3d-450c-9684-15d4248a193a)

While kernelspecs do not have a process associated directly, they may have a pool of pending kernels (kernels which were not yet requested but were spawned ahead of time to reduce wait time). Things such as the pool of pending kernels for a given kernelspec, nor the details of kernelspec are not currently exposed (but could be shown on hover with my proposal).

On implementation level the kernelspec is a folder, you can find such folders with:

```
jupyter kernelspec list
```

and includes an icon (e.g. the Python logo) and a `kernel.json` file like:

```json
{
 "argv": [
  "python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3 (ipykernel)",
 "language": "python",
 "metadata": {
  "debugger": true
 }
}
```

### 2) Kernels
What you highlighted in blue corresponds to kernel processes (which importantly can use up RAM memory).

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/884e0b81-185f-435c-9a2c-6ff23e5efd66)

We already use the icon that I proposed to represent kernel on the status bar, which nota bene opens the "Running" sidebar:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/10dc61fb-43a0-4ef2-9424-c9822d3227ff)


Importantly (I use screenshots from existing UI rather than proposed; take it that all of them should apply on the second level though):
- a) user may want to kill a kernel without closing the notebook (and without navigating to the notebook first; this is especially important when your calculations in another notebook are close to finish after a long time but your memory is running out and you want to free as much as possible ASAP to prevent deadlock/swapping/crash); this is why they should a "close" icon when you hover over them (like it is currently when you hover over `Python 3 (ipykernel)`)
   ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/8e9c7572-6c18-4b9c-9474-8bf2f2b3d530)
- b) user may potentially want to perform other kernel-specific actions such as sending interrupt or soft restart requests. 
- c) users may want to use an existing kernel to create a new notebook or console (also see https://github.com/jupyterlab/jupyterlab/issues/15255)
   ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/af3754d9-e63e-40db-b8b6-2bb5a3d35e18)
- d) kernels have a unique identifier (KID) like `e19ebb44-361b-450e-858c-8837b0f3c094` (which Colin suggested to use) and some additional technical details (see below), most of which are not very relevant to user why wants them to "just work". We already expose the kernel ID on hover but I believe it is more useful to refer to kernel by the documents they are attached to and only if they are not attached to anything, then fallback to KID.
    ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/fade5eb5-ef09-426a-9bf2-8881fa0ca958)

<details>

These details might be:

```
{
  "shell_port": 46535,
  "iopub_port": 58313,
  "stdin_port": 45659,
  "control_port": 47417,
  "hb_port": 38079,
  "ip": "127.0.0.1",
  "key": "2476c0fd-68e8736c0bdfdd1e123437b4",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": ""
}
```

If you have a `jupyter` installed you will find the kernels runtime files on disk (see `runtime` from `jupyter --paths`, e.g. `~/.local/share/ju pyter/runtime`).

</details>

### 3) Documents attached to kernels

These allow to find widgets attached to a kernel, or re-open them if they were closed:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/5244eb28-a310-4655-b7b1-c5ade29414c0)

**Comment by krassowski** [comment]
>  I'm working on several suggestions for a kernel and tab side panel refactor, brining together all the issues that have been opened on this subject.

@GabrielaVives in https://github.com/jupyterlab/jupyterlab/issues/15293 I also suggested adding a new "Recently closed" section.

**Comment by krassowski** [comment]
An argument for hierarchical grouping was also presented by @dhirschfeld in https://github.com/jupyterlab/jupyterlab/issues/5286:

> Currently the Running Sidebar displays Consoles/Notebooks under the heading Kernel Sessions however notebooks and consoles are just font-ends to a particular kernel so it would be more useful if the kernel was shown as the top-level element which could be expanded to show what front-ends (also editors?) were attached.
> **This bit me when I closed a console tab and then shutdown it's kernel. Unfortunately there was a notebook also attached which I wanted to keep open but with no indication in the Running Sidebar that they were linked I accidentally also killed my notebook session.**

**Comment by dhirschfeld** [comment]
I'm not sure using the notebook name (and X more) is a great UX for the kernel name. I get that it exposes useful information without having to drill down but that could also be done with an "expand all" button and/or a filtering searchbox.

Maybe just the PID and 1st 8 characters of the uuid. Bonus points to allow the user to override the kernel name - that could make connecting to an existing kernel a lot easier if you could assign them meaningful names like `EXPERIMENT-01` or `DO_NOT_KILL`! 😅

**Comment by dhirschfeld** [comment]
I think to the PID is particularly useful/relevant information to expose.

**Comment by ericsnekbytes** [comment]
Mike's proposal, especially step 3 where kernels are grouped by type/spec, is excellent as it clearly communicates what kernels are available by type, and concisely shows the case when a kernel is connected to multiple notebooks/console.

If identifying kernels by their ID is important, we can show a few digits of the ID colorized (as git does with short hash segments) in front of the notebooks they're attached to for clarity, mockup below. I would recommend expanding all by default (so users don't have to go through extra clicks), the mockup below also shows buttons for expanding and collapsing all:

![kernels1](https://github.com/jupyterlab/jupyterlab/assets/104786633/bcbb1c25-ec37-48bb-ad9a-8dfa1005825f)

**Comment by mlucool** [comment]
Any reason to show Untitled2 as the only child of Untitled 2? It would seem cleaner to have the case where a kernel only has one connection without a child to me.

**Comment by krassowski** [comment]
> Any reason to show Untitled2 as the only child of Untitled 2? It would seem cleaner to have the case where a kernel only has one connection without a child to me.

There are different context-command options available for notebook and kernel entry. Merging them into one when there is only one child is a trade-off:
- (-) more complex codebase and thus higher maintenance cost
- (-) more confusing for new users because different concepts (kernel vs document) are getting mashed up into a single UI element; for example as a user I would not know what clicking on such combined entry would do, and what clicking the "X" button used for killing kernels would do to the document
- (+) uses less space

> Also, in the current proposed design, I _think_ I'd have to expand the node then click the notebook to open it vs. in lab3, it was just one click away in a list.

It appears reasonable to enforce that by default all kernel nodes with up to two (or three?) documents attached stay expanded but get automatically collapsed when we have three (or four?) or more children.

Worth noting that over in the sub-shells JEP there is a proposal to visualise dependent kernels as children of the parent kernel (https://github.com/jupyter/enhancement-proposals/pull/91#issuecomment-1936089820). This would potentially add more children to the kernel node in the tree (depending on the number of running dependent kernels).

**Comment by krassowski** [comment]
I presented the work in progress on https://github.com/jupyterlab/jupyterlab/pull/15845 during the the lab call today.

@bollwyvl suggested that we could have a toggle between flat and tree view. I like this idea a lot. What do you all think?

**Comment by mlucool** [comment]
Works for me, so long as a setting can set the default. I suspect most users would prefer flat view

**Comment by krassowski** [comment]
> long as a setting can set the default

We can preserve the toggle state so that it stays the same on refresh/when reloading workspace, but a dedicated setting would be somewhat complex to implement without special casing kernels section.

> I suspect most users would prefer flat view

We can evaluate this after we land the improved tree view.
