### ISSUE TITLE
Should we improve cell toolbar logic or disable cell toolbar in tests?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15305]
## Description

A bottleneck in the PR review are often the visual test failures. In addition to a few existing test cases which are flaky, a very common problem is the cell toolbar randomly showing up when it should not or randomly hiding when it should be visible for a split second. It is not a problem in normal usage when it is mostly unnoticeable, but it leads to many spurious failed tests, wasting hundreds of hours in CI time and in the time of maintainers, for example:

| Actual | Expected | Diff |
|--|--|--|
| ![reexpand-headers-03a-actual](https://github.com/jupyterlab/jupyterlab/assets/5832902/5f095d94-ed4d-45f6-8a93-ac1555faf1b7) | ![reexpand-headers-03a-expected](https://github.com/jupyterlab/jupyterlab/assets/5832902/69f27c42-64e3-4fc7-a574-962020e6f2c7) | ![reexpand-headers-03a-diff](https://github.com/jupyterlab/jupyterlab/assets/5832902/490d7f84-d360-4f92-bb83-72a99cae1635) |

| Actual | Expected | Diff |
|--|--|--|
| ![notebook-panel-1-actual](https://github.com/jupyterlab/jupyterlab/assets/5832902/da3dc8ef-e9a5-44ea-abe1-6aacc5410b3e) | ![notebook-panel-1-expected](https://github.com/jupyterlab/jupyterlab/assets/5832902/df5b733d-6a93-4222-aeee-46a207ec0324) | ![notebook-panel-1-diff](https://github.com/jupyterlab/jupyterlab/assets/5832902/603dd81b-86e1-4942-9c57-d6f28dea1d1b) |

## Reproduce

Screenshots taken from https://github.com/jupyterlab/jupyterlab/actions/runs/6640451043/job/18051878571?pr=15296 but every other PR has this issue. If you seen green status it likely means that one of the maintainers manually restarted the job after checking the failures manually (so they did that instead of improving the codebase or merging a PR).

**Comment by JasonWeill** [comment]
This may be related to known bugs #13115 and #13857 regarding the cell toolbar's display. In addition, there's #12223, an enhancement request to make the cell toolbar visible all the time, perhaps in collapsed form.

**Comment by krassowski** [comment]
Also, there is https://github.com/jupyterlab/jupyterlab/pull/15314 which might help with things.

**Comment by krassowski** [comment]
It continues to be a drag on maintenance and development (for example see incorrect snapshot updates in https://github.com/jupyterlab/jupyterlab/commit/154944240e4433a3b96a45884004d34530fe02a5).

**Comment by krassowski** [comment]
In discussion on https://github.com/jupyterlab/jupyterlab/pull/15422 with @brichet we note that after refreshing the page the toolbar often does not hide even though it should. I can reliably reproduce this on `main`:

![should-hide](https://github.com/jupyterlab/jupyterlab/assets/5832902/11139270-14ec-41e4-9a7d-36c2fa42bcb7)

This looks like a bug in the logic which has implications on the maintainers ability to move forward because these tests are always flaky and often fail the run, adding about 15 to 30 minutes wasted to each PR review (we need to download the artifact, unpack, analyze, re-run a few times).

**Comment by krassowski** [comment]
This is also a hurdle for new contributors as seen in #16284.
