### ISSUE TITLE
Extension manager "Update to" button does not update extensions

### ISSUE THREAD

**Issue by nbowditch-einblick** [jupyterlab/jupyterlab#15316]
## Description

Clicking the "Update to #.#.#" button in the extension manager does not properly update the extension. 

<img width="510" alt="Screenshot 2023-10-27 at 12 41 09 PM" src="https://github.com/jupyterlab/jupyterlab/assets/111072326/55878139-01a6-43d1-89d4-736da059d608">

**Note:** I've tested this on multiple extensions. In this description I'll be using the `jupyterlab-atp-extension` but it seems arbitrary. 

## Reproduce

1. Create a new conda test environment per [guidelines](https://jupyterlab.readthedocs.io/en/latest/getting_started/issue.html)

```bash
conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c nodefaults jupyterlab
```

2. Activate the conda environment

```bash
conda activate jlab-test
```

3. Before starting jupyterlab, install an extension via pip at a version earlier than the extension's latest version on pypi. In my example, I used `jupyerlab-atp-extension==1.0.2` ([pypi link](https://pypi.org/project/jupyterlab_atp_extension/#history)):

```bash
pip install jupyterlab-atp-extension==1.0.2
```

4. Start jupyterlab:

```bash
jupyter lab
```

5. In Jupyterlab, open the Extension Manager via the sidebar:

<img width="283" alt="Screenshot 2023-10-27 at 3 07 04 PM" src="https://github.com/jupyterlab/jupyterlab/assets/111072326/1599b2c9-a853-4462-9ac1-fe8f17288c8c">

6. Confirm that the extension is installed and that the extension manager is aware of a more recent version by observing the "Update to #.#.#" button:

<img width="510" alt="Screenshot 2023-10-27 at 12 41 09 PM" src="https://github.com/jupyterlab/jupyterlab/assets/111072326/a687fb50-280e-427d-8d77-a7b9c30d4985">

7. Click the "Update to #.#.#" button. Accept the Dialog that appears, then refresh as per instructions on the dialog. Notice that the extension has not been upgraded after refresh.

https://github.com/jupyterlab/jupyterlab/assets/111072326/5db1a235-eaa1-47ac-93f2-b2e3ea672a14

## Investigation

When the "Update to" button is clicked, a request is made to server to update: `POST http://localhost:8888/lab/api/extensions?<id>`. The body of the request is:

```json
{
    "cmd": "install",
    "extension_name": "jupyterlab-atp-extension"
}
```

The request is successful and returns 200. However, it seems that the request does not have the desired effect, and the extension stays at the same version. 

I think the issue is that the request's body should include a `"extension_version": "..."`. In [the logic for the handler](https://github.com/jupyterlab/jupyterlab/blob/79a4e38213969a60f74b998330b034fad1598ffc/jupyterlab/handlers/extension_manager_handler.py#L99), it looks for an `"extension_version"` property in the body. If that property exists, the `PyPIExtensionManager` uses it in the underlying `pip install` command it makes (see [here](https://github.com/jupyterlab/jupyterlab/blob/79a4e38213969a60f74b998330b034fad1598ffc/jupyterlab/extensions/pypi.py#L290)). Note how in the jupyterlab logs, we see this command instead, which doesn't include any version:

```bash
[D 2023-10-27 15:19:35.432 LabApp] Executing '/Users/nbowditch/miniconda3/envs/jlab-test/bin/python3.12 -m pip install --no-input --quiet --progress-bar off jupyterlab-atp-extension'
``` 

If I run that pip command in my terminal, it won't upgrade the package since there is no `--upgrade` flag or version specified. But if I change the pip command to include the version (which would be executed if there was an `extension_version` property):

```bash
/Users/nbowditch/miniconda3/envs/jlab-test/bin/python3.12 -m pip install --no-input --quiet --progress-bar off jupyterlab-atp-extension==1.0.3
```

The upgrade occurs as desired. 

Tracing the call from the front-end:

- [Extension manager widget --> ListEntry Button onClick](https://github.com/jupyterlab/jupyterlab/blob/79a4e38213969a60f74b998330b034fad1598ffc/packages/extensionmanager/src/widget.tsx#L132)
- [Extension manager widget --> ListView onAction method](https://github.com/jupyterlab/jupyterlab/blob/79a4e38213969a60f74b998330b034fad1598ffc/packages/extensionmanager/src/widget.tsx#L502).
- [ListView model --> install method](https://github.com/jupyterlab/jupyterlab/blob/main/packages/extensionmanager/src/model.ts#L347)
- [ListView model --> performAction](https://github.com/jupyterlab/jupyterlab/blob/main/packages/extensionmanager/src/model.ts#L484) <-- This is what builds the request

It seems that for both "install" and "update", the logic uses an "install" action. Perhaps there should be an entirely separate "upgrade" action, since the underlying manager (in this case pypi extension manager) might need separate logic paths. However, I think a simple/quick way of fixing this would be to allow an optional `version` parameter in some of these methods. That way the logic can continue to use the same "install" action, just opt to include a "version" (which would be used for updates).

## Expected behavior

The call made to Jupyterlab's server by the Extension Manager should properly upgrade the extension to the appropriate version.

## Context

- Operating System and version: macOS Ventura 13.4
- Browser and version: Chrome Version 118.0.5993.88 (Official Build) (arm64)
- JupyterLab version: 4.0.7

<details><summary>Troubleshoot Output</summary>
<pre>
[jupyter-troubleshoot.log](https://github.com/jupyterlab/jupyterlab/files/13192885/jupyter-troubleshoot.log)
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[jupyter-lab-debug.log](https://github.com/jupyterlab/jupyterlab/files/13192887/jupyter-lab-debug.log)
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
 Didn't seem relevant
</pre>
</details>

**Comment by krassowski** [comment]
Thank you for the detailed report @nbowditch-einblick. Would you be interested in contributing a pull request for this issue?

**Comment by nbowditch-einblick** [comment]
> Thank you for the detailed report @nbowditch-einblick. Would you be interested in contributing a pull request for this issue?

Sure thing! Thanks for getting back so quickly. I'll work on a fix
