### ISSUE TITLE
[DISCUSS] CSS in the body

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#15320]
I open this issue to discuss why JupyterLab sets CSS ruli in the `body`. This impacts downstream libraries as reported on https://github.com/datalayer/jupyter-ui/issues/110

<img width="326" alt="Screenshot 2023-10-29 at 07 24 21" src="https://github.com/jupyterlab/jupyterlab/assets/226720/877c9205-29ac-4f9b-9f4c-d01d73d8fbe1">

**Comment by krassowski** [comment]
This is related to https://github.com/jupyterlab/jupyterlab/issues/13493. I agree that rules on `body` are best kept to minimum (resets of margin/padding plus overflow/background as needed) and only defined in packages which are opt-in in downstreams. Is your issue with a specific rule, or with where it is defined?

**Comment by echarles** [comment]
Thx @krassowski for pointing to https://github.com/jupyterlab/jupyterlab/issues/13493, which confirms this is an issue to be discussed/fixed.

>  I agree that rules on body are best kept to minimum (resets of margin/padding plus overflow/background as needed) 

What logic would tell which rule is acceptable or not. I tend to prefer avoiding any rule, and have a top div, with an id or a classname, and move the body rules there.

>  Is your issue with a specific rule, or with where it is defined?

The issue is that the rule of the body interfer wit the downstream webapp. My above suggestion (move from body to an inner div) would solve that. There would still be the questions around global css as discussed in https://github.com/jupyterlab/jupyterlab/issues/13493

**Comment by krassowski** [comment]
> What logic would tell which rule is acceptable or not. I tend to prefer avoiding any rule, and have a top div, with an id or a classname, and move the body rules there.

Theoretically is should be possible if the top div is absolutely positioned. My thinking was that there might be implications of not resetting body margin/padding to zero, but I am not confident on this one.

> The issue is that the rule of the body interfer wit the downstream webapp

Are you embedding the full JupyterLab instance with all the plugins donwstream? My suggestion is as in https://github.com/jupyterlab/jupyterlab/issues/13493 to move such styles from plugins which are consumed downstream to plugins which are only active when standalone JupyterLab instance is being used (rather than embedded).

**Comment by krassowski** [comment]
Also background on body is useful to avoid white flash when loading the UI, again not something that cannot be solved, just needs a carefully crafted and tested solution.

**Comment by echarles** [comment]
> Are you embedding the full JupyterLab instance with all the plugins donwstream?

We embed any combination of plugins (with or without theme), the issue is that the plugins add those rules (have not looked which one(s))

> Also background on body is useful to avoid white flash when loading the UI, again not something that cannot be solved, just needs a carefully crafted and tested solution.

I will try joining a jupyterlab meeting to get more feedback on this question. The ideal would be to have a PR to discuss, I won't be able to do that very soon.
