### ISSUE TITLE
JupyterLab 4.x: Builtin Python keywords are no longer syntax highlighted

### ISSUE THREAD

**Issue by bergkvist** [jupyterlab/jupyterlab#15325]
## Description

JupyterLab 3.x
<img width="203" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/410028/54cf3aa1-e299-4148-bad8-51458f192fed">

JupyterLab 4.x
<img width="203" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/410028/819ca33d-1675-4bd8-a918-6d714a7df6c8">

JupyterLab 4.x
<img width="196" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/410028/526ea7ea-f7c3-4b05-b966-a26dfabb000a">

Note that we get syntax highlighting for print if we remove the parenthesis, indicating that it understands Python 2 syntax, but not Python 3 syntax.

## Expected behavior

Syntax highlighting for builtin Python keywords should work as it did in JupyterLab 3.x

## Context

- Operating System and version: Manjaro Linux
- Browser and version: Google Chrome
- JupyterLab version: 4.0.0a0, 4.0.0a1, 4.0.0a3, 4.0.0a4, 4.0.0a6, 4.0.0a7, 4.0.0a8, 4.0.0a9, 4.0.0a10, 4.0.0a11, 4.0.0a12, 4.0.0a13, 4.0.0a14, 4.0.0a15, 4.0.0a16, 4.0.0a17, 4.0.0a18, 4.0.0a19, 4.0.0a20, 4.0.0a21, 4.0.0a22, 4.0.0a23, 4.0.0a24, 4.0.0a25, 4.0.0a26, 4.0.0a27, 4.0.0a28, 4.0.0a29, 4.0.0a30, 4.0.0a31, 4.0.0a32, 4.0.0a33, 4.0.0a34, 4.0.0a35, 4.0.0a36, 4.0.0a37, 4.0.0b0, 4.0.0b1, 4.0.0b2, 4.0.0rc0, 4.0.0rc1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.1.0a1, 4.1.0a2

**Comment by krassowski** [comment]
Thank you for engaging! I believe that this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/14589, should we close this issue?

**Comment by bergkvist** [comment]
Yes, you are right
