### ISSUE TITLE
Defer loading of iframes to accelerate JupyterLab start

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15334]
### Problem

JupyterLab opens HTML/PDF/help documents using `iframe`s. If those are open in the background like:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/7abeed1f-62e3-471a-8e2f-4ebb30a13de0)

they are still loaded immediately when JupyterLab opens.

### Proposed Solution

Using [lazy](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#lazy) loading of iframes can cut the loading time for the active tab as the browser will defer loading/populating the iframe.

Benchmarking would be beneficial to establish how much it can help with loading time.

### Additional context

This was supported by Chrome for a long time but is only rolling out in Firefox in v120 (upcoming version).
https://caniuse.com/loading-lazy-attr

**Comment by DcWire** [comment]
Hey @krassowski , I was able to set the attribute of lazy loading to pdf/document/html type iframes to true. How do I verify if the lazy loading is working?

**Comment by sash9696** [comment]
hi @krassowski . Could you please assign this issue to me.

**Comment by krassowski** [comment]
Please just send a PR we do not use the assign function for issues. For contributing hints see: https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html

**Comment by sash9696** [comment]
Okay thank you for the reply. I am working on it.

**Comment by hnben** [comment]
My team is going to be working on this

**Comment by nayanpaa** [comment]
My team is looking into this issue as well
