### ISSUE TITLE
CSS nesting rules not working on jupyterlab

### ISSUE THREAD

**Issue by ghost** [jupyterlab/jupyterlab#15350]
Hi, the problem is modern native CSS supports nesting rules in browsers. but it doesn't work on jupyterlab or jupyter notebooks and I dont know why. Because nested css is included in bundled code, still not working tho. What can be the issue and how can I fix it? (I want to use native CSS rather than SASS, so please do not suggest to use SASS instead. I would rather love to solve the issue)

i've tried nesting rules on jupyterlab local dev, jupyterlab online, jupyter notebook online, jupyterlite online. None worked :((

![image](https://github.com/jupyter/notebook/assets/138553763/0d3a6a4c-9fa3-43c3-ba29-d362b574f3af)
![image](https://github.com/jupyter/notebook/assets/138553763/9ab87efd-e368-445e-805a-e645954664be)

**Comment by krassowski** [comment]
It appears that your issue is not with JupyterLab but with CSS nesting specification. Based on the screenshots it seems that you assume that:

```css
body {
   * {
      // rule
   }
}
```

is equivalent to:

```css
body * {
   // rule
}
```

(which applies to all descendants of the `<body>` tag) - but it is **not**. As per the [CSS nesting specification](https://www.w3.org/TR/css-nesting-1/), it is instead equivalent to:

```css
body > * {
   // rule
}
```

which exclusively applies to direct children of the `<body>` tag and nothing else. In case of JupyterLab there are few direct children of the `<body>` tag.

**Comment by krassowski** [comment]
Deleted my comment as I think it was misleading.

**Comment by andrii-i** [comment]
Thank you for creating this issue @terlan4. Could you please advise which JupyterLab version are you using?

**Comment by krassowski** [comment]
I just tested a slightly different nested CSS rule and it just works:

```css
body {
  & div {
    background: red
  }
}
```

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/6155df31-4474-4b36-8e15-ce6aebb43567)

**Comment by JasonWeill** [comment]
@terlan4 Were you able to add a more specific rule, as @krassowski did above? Is it working for you? If not, which version of JupyterLab and which browser (including version) are you using? Thanks!

**Comment by krassowski** [comment]
To be specific, the CSS specificity in the native CSS nesting is different from Sass, see:
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Nesting_and_specificity
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting

Quoting from MDN documentation (the link above):

> CSS nesting is different from CSS preprocessors such as [Sass](https://sass-lang.com/) in that it is parsed by the browser rather than being pre-compiled by a CSS preprocessor. Also, in CSS nesting, the [specificity of the & nesting selector](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Nesting_and_specificity) is similar to the [:is()](https://developer.mozilla.org/en-US/docs/Web/CSS/:is) function; it is calculated using the highest specificity in the associated selector list.


> Note: Early versions of the specification did not allow nesting of [type selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Type_selectors) without the [& nesting selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector). This has been updated so the & nesting selector is no longer needed. At the time of writing (Aug. 2023) Firefox supports the new version of the specification while Chrome and Safari support the old version of the specification and must use the & nesting selector for type selector nesting.
