### ISSUE TITLE
it seems like "Show Header" should be renamed "Toggle Header"

### ISSUE THREAD

**Issue by parmentelat** [jupyterlab/jupyterlab#15354]
typing "Header" in the palette brings to a command named "Show Header"

but what this command does actually is toggling the header, as can be seen here 
https://github.com/jupyterlab/jupyterlab/blob/c106f0a19110efad7c5e1b136144985819e21100/packages/application-extension/src/index.tsx#L288

so how about we change the Label to read "Toggle Header" instead ?
however I do not know the impact in terms of translations...

**Comment by krassowski** [comment]
This is indeed unfortunate how the labels diverge from the underlying functionality. I think there are some places in the codebase the labels for toggle commands are conditional (Show/Hide - depending on the state), but in this case there is a reason for keeping it as-is: when you open the "View → Appearance" menu you will see that the ticks are what actually indicates the toggle status.

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/c6dfb9da-0859-42f1-9700-e09c0f76e27f)

I think in that context keeping "Show ..." makes sense. If we really want to change it elsewhere, we can have conditional labels (e.g. different for menus and different for command palette)

**Comment by krassowski** [comment]
What is your use case/is it bothering you in a particular situation?

Translations-wise we can modify strings in minor versions, only already-released patch versions are frozen.

**Comment by parmentelat** [comment]
well what's bothering is I am using this command to hide the header, and so this gives me
```js
    // hide the header
    app.commands.execute('application:toggle-header')
```
so I thought it was just a mistake, but if you say this is a deliberate choice I can live with that ;-)
