### ISSUE TITLE
Invalid token being used in @jupyterlab/codemirror-extension:services plugin.

### ISSUE THREAD

**Issue by paulkim3151** [jupyterlab/jupyterlab#15360]
I was reading the code in the codemirror-extension and found that token was being misused in the following code.

https://github.com/jupyterlab/jupyterlab/blob/2c9dff7e8343400b5d7d65839cd2f48e8d5ddb69/packages/codemirror-extension/src/services.tsx#L235-L264

The plugin uses four tokens (`IEditorLanguageRegistry`, `IEditorExtensionRegistry`, `IEditorThemeRegistry`, `ITranslator` (optional)), but `activate` function only receives three tokens as parameters (`IEditorLanguageRegistry`, `IEditorExtensionRegistry`, `ITranslator`).

I think the `IEditorThemeRegistry` token is being misused.

Is this the part that needs improvement?

**Comment by andrii-i** [comment]
Thank you for creating this issue @paulkim3151. It looks relevant. Would you like to open a PR to address it? It seems that removing `IEditorThemeRegistry` from the list of `required` dependencies would solve the correct solution but this needs validation.
