### ISSUE TITLE
Releasing a new 4.0.x _breaks_ the staging/yarn.lock file

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#15368]
## Description

When releasing a 4.0.x version, the staging/yarn.lock file is _broken_ (semver packages are not order properly).

> I did not found the culprit. So for now, I opened a transient fix: https://github.com/jupyterlab/jupyterlab/pull/15367

## Reproduce

See PRs:
- https://github.com/jupyterlab/jupyterlab/pull/15366
- https://github.com/jupyterlab/jupyterlab/pull/15364

## Expected behavior

Releasing a version does not break the yarn.lock.

**Comment by fcollonval** [comment]
Ok I think I found the root cause.

In 4.0.x we have:

https://github.com/jupyterlab/jupyterlab/blob/2c9dff7e8343400b5d7d65839cd2f48e8d5ddb69/buildutils/src/update-core-mode.ts#L67-L74

In main we have:

https://github.com/jupyterlab/jupyterlab/blob/279cc2ea0fef89c2919f5405fb1b7d56bb124e36/buildutils/src/update-core-mode.ts#L67-L74

> The last `jlpm install` is the one cleaning the reorganization induced when deduplicating the lock file.

**Comment by krassowski** [comment]
Huh, not sure why GitHub did not auto-close this one.
