### ISSUE TITLE
Jitter in the file browser when refreshed

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15365]
## Description
I am noticing a jitter in the file browser on refreshing it. Please see the attached gif.
![jitter2](https://github.com/jupyterlab/jupyterlab/assets/30082866/90686aeb-b24a-4ba6-87d2-c39393f18e2a)

## Reproduce
Click on the refresh button in the filebrowser.
This is more easily reproducible when there is a large number of items in a directory.

## Context
I'm using  -  jupyterlab==4.0.6

**Comment by krassowski** [comment]
I cannot reproduce this in plain JupyterLab 4.x but I see that you have [jupyterlab-favorites](https://github.com/jupyterlab-contrib/jupyterlab-favorites) installed. I am able to reproduce the issue in jupterlab-favourites. I will copy this issue over to jupterlab-favourites.
