### ISSUE TITLE
Jupyterlab uses up all my free space to write error txt

### ISSUE THREAD

**Issue by C-JLee** [jupyterlab/jupyterlab#15363]
## Description

Every week, at a random time after closing JupyterLab, I receive a notification that there is no free space on my disk, and I have to manually delete these error logs that take up all the space on my disk from JupyterLab. Whenever this happens, it sometimes crashes my other programs.

I couldn’t find any discussion threads on Reddit, GitHub, or other forums that are related to this problem. Additionally, when I check the task manager, I can see that there are nine or more instances of Python running in the background. When I try to delete these error logs, I got notified that “jupyter-lab.exe” is using them.

![Capture](https://github.com/jupyterlab/jupyterlab/assets/75051893/b4728aa7-b743-4caf-bf2d-69e2fccb2ba9)

## Reproduce

It happens randomly after closing JupyterLab
1. click close button to close JupyterLab
2. click close button to close Anaconda Navigator
3. Sometimes the programs are still showing up in my task manager (Python.exe, Jupyter-lab.exe, etc.)
4. Then this happens sometime randomly

## Expected behavior
Has anyone else encountered this issue? Does anyone know what might have caused this? Is it a bug, and will it be fixed in future updates?

## Context

- Operating System and version: Windows 10 Pro, Version 22H2
- Browser and version: Microsoft Edge 119.0.2151.44 (64-bit)
- JupyterLab version: 3.6.3

</pre>
</details>

**Comment by krassowski** [comment]
These error files are not created by JupyterLab but seemingly by Anaconda Navigator. The issue is most likely with Anaconda Navigator, not JupyterLab. You may wish to contact Anaconda as we (JupyterLab team) cannot help here, especially since the Anaconda Navigator appears to be closed-source as per https://github.com/ContinuumIO/anaconda-issues/issues/750 (please correct me if I am wrong).

**Comment by krassowski** [comment]
What I could recommend is trying to install and use JupyterLab from official JupterLab distribution channels (PyPI/conda-forge/[JupyterLab Desktop](https://github.com/jupyterlab/jupyterlab-desktop)); if the problem appears with application installed via these channels feel free to re-open.
