### ISSUE TITLE
Clean up the common folder

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1539]
Since `@jupyterlab/common` is going to be a package, we should only import from the top level.  If things need to be grouped, they should be grouped by namespace.

This is a follow-on to #1364.

**Comment by blink1073** [comment]
Once #1432, we should add an `observable` directory with observable string, list, map, and undoable list.

**Comment by ian-r-rose** [comment]
Would it be helpful to break out the `ObservableMap` stuff into a separate PR?

**Comment by blink1073** [comment]
I've got other stuff I can work on, I'd prefer to leave you to your own devices for now ;).

**Comment by blink1073** [comment]
@meeseeksdev close

**Comment by blink1073** [comment]
@meeseeksdev open
