### ISSUE TITLE
How to display the cell tag names in Jupyter Lab 4?

### ISSUE THREAD

**Issue by virgilus** [jupyterlab/jupyterlab#15397]
## Description

I use a lot the cell tagging system in my notebooks. With Jupyter Lab 3, I could use the extension jlab-enhanced-cell-toolbar which allowed me to visualize the cell tags names for each cell on the upper right corner. But it's not yet supported for JL 4.

Is there a way to achieve this behavior without using an extension? Or maybe with an other extension?

**Comment by JasonWeill** [comment]
@virgilus Thank you for opening this! The cell-toolbar package supports extensions that add more controls to the toolbar. The enhanced cell toolbar is likely the best place for this feature, but until it supports JupyterLab 4, you won't be able to use it.

Linking https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar/issues/67, the issue to add Lab 4 support to the enhanced cell toolbar.

**Comment by mengyanw** [comment]
Hi, I would like to work on adding Jupyterlab 4 support to the extension and will try to make a pull request this week :)
