### ISSUE TITLE
Visited link are invisible in light theme

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#15403]
## Description

The color `--jp-content-link-visited-color` used for the light theme makes it invisible

![image](https://github.com/jupyterlab/jupyterlab/assets/8435071/8457838c-a650-407b-91e4-0fd5fa242363)

## Reproduce
1. Go to the extension manager
2. Click on a link to open a extension home page
3. Come back to jupyterlab

## Expected behavior

The text is visible also in light theme

## Context

Main branch
Tested on Firefox and Chrome

That color was introduced by https://github.com/jupyterlab/jupyterlab/pull/15181

---

For reference this is how it looks with the dark theme:

![image](https://github.com/jupyterlab/jupyterlab/assets/8435071/3e82dc5c-5c78-4115-9317-d7cc4cbdbf3b)

**Comment by fcollonval** [comment]
@m158261 by any chance do you have time to solve this issue?

**Comment by m158261** [comment]
Hey @fcollonval. Yeah, I'll try and get that fixed today.

**Comment by m158261** [comment]
Hi @fcollonval. I've raised a PR. https://github.com/jupyterlab/jupyterlab/pull/15406
