### ISSUE TITLE
No Java jernel

### ISSUE THREAD

**Issue by mollyhall05** [jupyterlab/jupyterlab#15410]
There is no longer an option to run a Jupyter notebook in Java on JupyterLab.

**Comment by ivanov** [comment]
Hi @mollyhall05 , Jupyter (notebook and lab) do not ship by default with a Java kernel. Only the original Python kernel (ipykernel) gets installed. If you want to use Java with Jupyter, you will have to install one of the Java kernels.

Read more about [kernels](https://docs.jupyter.org/en/latest/projects/kernels.html), and some of the available kernels (inlcuding Java ones) are listed [on this wiki page](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) - though I am not sure which one of those is up to date and still maintained. 

closing this, as it is not a jupyterlab issue, best of luck!
