### ISSUE TITLE
jupyterlab (version 4.0.8 ) can't treat markdown properly

### ISSUE THREAD

**Issue by vivisol** [jupyterlab/jupyterlab#15411]
## Description
jupyterlab (version 4.0.8 ) can't treat markdown properly.
here is the bug:
jupyterlab version is ：
![image](https://github.com/jupyterlab/jupyterlab/assets/22468237/3d14761d-9d36-4d2c-b0ac-bc443d17a770)

browser version：
![image](https://github.com/jupyterlab/jupyterlab/assets/22468237/96afe6f1-4bef-4df4-8b1e-831b2a90be2c)

markdown is as follows:
![image](https://github.com/jupyterlab/jupyterlab/assets/22468237/210e4dd1-2b3c-44f7-a5cc-f6d7e214fb8f)

but render result is :
![image](https://github.com/jupyterlab/jupyterlab/assets/22468237/b837086a-7096-41ba-b39f-71ebde5faf6a)

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: win11 for home 22621.2428
- Browser and version: Google Chrome Version 119.0.6045.124 (Official Build) (64-bit)
- JupyterLab version: 4.0.8

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
Can you paste the full markdown text to make it easy to reproduce?

**Comment by vivisol** [comment]
> Can you paste the full markdown text to make it easy to reproduce?

Sure,  something like this :

```shell

File D:\ProgramData\miniconda3\envs\pyautogen\lib\site-packages\requests\models.py:975, in Response.json(self, **kwargs)
    971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by magitz** [comment]
I am having a similar issue in 4.0.6. It is most noticeable with the quoted text syntax ">".

Here's an example Markdown cell. This is the only cell in the notebook:

![image](https://github.com/jupyterlab/jupyterlab/assets/732302/a709e73e-1178-4ce1-b708-ef514a8adbad)

This is rendered as:

![image](https://github.com/jupyterlab/jupyterlab/assets/732302/77bfd1fa-e58f-419d-b249-afc0df764e01)

- Characters that are not there are added (the "a." at the end). 
- Some lines that should be part of the quoted text block are not ("Maecenas maximus...")
- The issues are not consistent or always there, unfortunately.

Here's another example:
![image](https://github.com/jupyterlab/jupyterlab/assets/732302/19450c07-dc5b-4d76-b810-ec315a6bcd50)

Rendered as:

![image](https://github.com/jupyterlab/jupyterlab/assets/732302/f023e412-9d0e-4644-8ac4-f39fe080b32e)

In this case, only the "a." at the end is there.

I tried pasting text into a text editor to look for special characters and could not find anything. 

From my testing, it seems like this only impacts Markdown edited on Jupyter 4+. When the notebook is opened in Jupyter 3.6.6, the actual Markdown corresponds to what 4+ displayed--ie. the Markdown is broken in the render process and changed to the incorrect text. But viewing it in 4+ looks correct.

**Comment by krassowski** [comment]
@magitz do you use Windows? If so, I have a strong suspicion that is different and it is down to line endings not being normalized on paste in Chrome. But this is just guessing without knowing your OS/browser and having a notebook to test it.

**Comment by magitz** [comment]
Ah...I do use Windows and Chrome...Is that a different issue? Any suggested work around (other than different browser/OS). I'll test in Edge/Firefox in a sec.

**Comment by magitz** [comment]
It does seem to work better in Firefox.
