### ISSUE TITLE
User input clobbered by Keyboard Shortcuts in Lab

### ISSUE THREAD

**Issue by mcrutch** [jupyterlab/jupyterlab#15429]
## Description

When attempting to get user input in a notebook cell in Jupyter Lab 4.0.7 or Notebook 7.0.6, if the keyboard input matches any keyboard shortcut, the keyboard shortcut is triggered instead.  For instance: Shift+L to toggle line numbers.  The only way to enter a capital L is to turn on caps lock, press L and turn off caps lock. This works properly at least in Jupyter Lab 4.0.4 but I haven't tested 4.0.5 or 4.0.6

## Reproduce

- create a cell containing: `input()` (or getpass.getpass())
- Run the cell
- Attempt to enter a capital L by pressing Shift+L
- Jupyter will trigger the SHIFT+L keyboard shortcut that toggles line numbers off/on rather than entering a capital L in the input field

![image](https://github.com/jupyterlab/jupyterlab/assets/51446717/9b28b530-9d17-4324-85f8-461fe61e179d)

## Expected behavior

The input field receives the value of Capital L

## Context
Using jupyter/base-notebook:848a82674792 container
Google Chrome 119.0.6045.160 to access it
No Browser Console Output

**Comment by mcrutch** [comment]
Did more investigation. 
- Jupyter Lab 4.0.4 - Works as intended
- Jupyter Lab 4.0.5 - Does not work

Tested using jupyter/base-notebook:lab-4.0.4 and jupyter/base-notebook:lab-4.0.5

**Comment by mcrutch** [comment]
Still happening in 4.1.0a3
![image](https://github.com/jupyterlab/jupyterlab/assets/51446717/f683f852-d411-401d-8bbe-e8ec01fbde39)

**Comment by krassowski** [comment]
4.1.0a3 does not include the fix yet, I will publish a new pre-release (hopefully beta) which does this week. I will also backport the relevant change to 4.0.x.

**Comment by tleonhardt** [comment]
I can confirm that JupyterLab 4.1.0a4 fixes this bug.
