### ISSUE TITLE
Navigation through outline is broken

### ISSUE THREAD

**Issue by armandfavrot** [jupyterlab/jupyterlab#15428]
The navigation through outline does not work. When I click on some header in the outline on the left bar, nothing happen.

I'am using jupyter-lab 4.0.9 (I just upgraded from 4.0.8). The bug was already there in 4.0.8 version (I recently upgraded to 4.0.8 and there was no bug with the previous version I had).

My OS is Ubuntu 22.04.3 LTS and I use firefox in kiosk mode as web-navigator.

**Comment by krassowski** [comment]
That is probably a duplicate of https://github.com/jupyterlab/jupyterlab/issues/14591 which is getting fixed by https://github.com/jupyterlab/jupyterlab/pull/15386.
