### ISSUE TITLE
Improve sidebar accessibility test coverage  

### ISSUE THREAD

**Issue by e218736** [jupyterlab/jupyterlab#15437]
### Problem

Tests for side bar tabs do not exist for keyboard navigation. It is important that tests exist to test the functionality of sidebar items using tabbing and arrow keys to ensure accessibility for keyboard users.  

### Proposed Solution

Add tests which follow a users navigation to the left and right side bar and verify that they can be opened 

### Additional context

Working on a ticket for this issue.

**Comment by krassowski** [comment]
Closing as resolved by https://github.com/jupyterlab/jupyterlab/pull/15438.
