### ISSUE TITLE
What happened to CTRL+D multi selection in the text editor?

### ISSUE THREAD

**Issue by lpuglia** [jupyterlab/jupyterlab#15432]
## Description

For jupyterlab <4.0.0 i never had problems with CTRL+D multi-selection tool in the text editor after selecting Sublime keymap, for sure it never worked in the notebook editor tabs, but at least it was working in the text editor. 

It seems that the situation is now reversed with 4.0.9: CTRL+D is doing multi-selection in the notebook editor (even though the shortcut is not listed in the keyboard shortcut tab) but not in the text editor. Pressing CTRL+D in the text editor always pop up the browser window to add a bookmark.

## Reproduce

clean install of jupyterlab 4.0.9

## Expected behavior

CTRL+D multiselection to work in the text editor as well

## Context

- Operating System and version: 22.04 
- Browser and version: tested on Chrome, Edge
- JupyterLab version: 4.0.9

**Comment by krassowski** [comment]
> after selecting Sublime keymap

This may be the cue - CodeMirror 6 removed Sublime keymap, see https://github.com/jupyterlab/jupyterlab/issues/14599#issuecomment-1565335250. Last time I checked no one created a sublime keymap for CM6 yet but maybe this changed.

**Comment by lpuglia** [comment]
> @lpuglia can you described the desired behaviour? Can you provide detailed reproduction instructions?
> 
> > Linking related issue: #14548
> 
> But that one was requesting ctrl + d to act as delete, while this one does not mention deletion/removal, just multi-selection (which is supported) so I am confused.

this is the expected behavior: https://forum.sublimetext.com/uploads/default/original/3X/0/3/03c4c40bf354deb892001a204204b9190ab9d131.png
(VSCode has the same key mapping for ctrl+d)

it now works flawlessly in the notebook tab by default, but it cannot be enforced in the text editor
