### ISSUE TITLE
CodeMirror built-in search shows up on cells upon ctrl+f

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15442]
## Description

On main branch pressing ctrl + f causes both JupyterLab search box and CM6 built-in to pop up:

## Reproduce

- Open notebook
- Focus a cell
- Press ctrl + f

See:
![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/4e08ef03-4f9a-4d3d-a8ad-c2f9d10fa393)

## Expected behavior

Only JupyterLab search box shows up

## Context

4.1.0a3 is clean so I guess this is a regression from https://github.com/jupyterlab/jupyterlab/pull/14115

**Comment by fcollonval** [comment]
:cry: I guess this is a consequence of the bubbling change for the keyboard shortcut (what is good).

I'll try to have a look. I guess it should be possible to avoid loading the associated extension/command in CM6.

**Comment by fcollonval** [comment]
As per [CM6 author comment](https://discuss.codemirror.net/t/disable-search-dialog-cm6/4061) :wink: 

> [marijn](https://discuss.codemirror.net/u/marijn)
> Don’t add the extension for it to your configuration, and it won’t appear.

**Comment by fcollonval** [comment]
The line to blame is https://github.com/jupyterlab/jupyterlab/blob/main/packages/codemirror/src/factory.ts#L48

**Comment by fcollonval** [comment]
Ok the question to solve this is what to do with editor that not part of documents; like the metadata editor or the _old_ settings editor.

I guess we can keep search for them by passing the CM search only on those.

**Comment by fcollonval** [comment]
Thanks @krassowski for diving into the feature brought by the search key map extension.
