### ISSUE TITLE
File dialog loads slowly when using `defaultPath`

### ISSUE THREAD

**Issue by mmichilot** [jupyterlab/jupyterlab#15453]
## Description
When using `FileDialog.getOpenFiles` with the `defaultPath` option, it takes a while (~10 seconds) to load the file list. However, when it's manually refreshed, the file list loads immediately.
![OpenDialogBug](https://github.com/jupyterlab/jupyterlab/assets/22762462/26bf55a5-4a2c-497a-ac88-211af6520e9e)

When `defaultPath` is not given, the file list is loaded immediately, however this limits the file dialog to starting from the root folder.

## Reproduce

Create a file dialog with `FileDialog.getOpenFiles` and pass a `defaultPath` option.

## Expected behavior
I would've expected the file list the to load once the dialog opened, especially since manually refreshing works immediately.

## Context

- Browser and version:  Firefox 119
- JupyterLab version: 4.1.0a3

**Comment by krassowski** [comment]
It sounds like it could be that it does not take 10s but you see it auto-refresh every 10s. So maybe the initial reply is not handled correctly to populate the contents or maybe there is just a missing `update` after the initial response was received.
