### ISSUE TITLE
Auto-completion clears cell

### ISSUE THREAD

**Issue by imaluengo** [jupyterlab/jupyterlab#1546]
I don't know if it is my own issue (some dependency missing or wrong installacion), but it surprised me that I couldn't find this bug already reported.

After opening a Notebook and writting in a cell a few lines, if I trigger code autocompletion using <TAB>, the cell gets compeltely erased, e.g.:

    import numpy as np
    np.<TAB>

The cell's content is replaced by:

    np.np.

And a popup with all the methods of numpy is displayed. The popup is working as expected, but I wonder why the cell's content is cleared.

**Comment by blink1073** [comment]
Hi @imaluengo, this was a bug, fixed in #1535.  We'll be making a new release this week.

**Comment by imaluengo** [comment]
Ops! Thanks for the reference. Glad to see it is already fixed. Waiting for the release!

**Comment by blink1073** [comment]
Fixed in `v0.13.2`.
