### ISSUE TITLE
Navigating many cells in notebook is slow/crashes browser

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15465]
## Description

The experience of switching cells in command mode in notebook has regressed in pre-releases.

## Reproduce

2. Open a notebook with 100 cells
3. Select a cell in **command** mode
4. Press down arrow and keep it down
5. See that active cell jumps by 10 or 20 cells at a time - not the greatest experience "nothing happens"
6. Press up arrow and keep it down
7. See that nothing happens and browser crashes; it does take about 45 seconds of pressing the arrow up key to crash it.

![crash-on-arrow-up](https://github.com/jupyterlab/jupyterlab/assets/5832902/059c8dc5-dcb8-43cc-934e-3225f1ec3374)

I was able to crash browser in both `full` windowed and `none` modes. Crashing may be due to some unstable feature I use so it is not "that bad" until confirmed but there is something wrong.

```
windowedlist.ts:1002 [Violation] 'requestAnimationFrame' handler took 77ms
windowedlist.ts:1002 [Violation] 'requestAnimationFrame' handler took 158ms
bridge.js:61 [Violation] 'setTimeout' handler took 58ms
windowedlist.ts:1002 [Violation] 'requestAnimationFrame' handler took 99ms
42[Violation] 'keydown' handler took <N>ms
bridge.js:61 [Violation] 'setTimeout' handler took 50ms
````

## Expected behavior

I expect to see the cells switching as I keep the arrow keys pressed so that I know when I arrived at my destination cell.

## Context

- Operating System and version: Ubuntu
- Browser and version: Edge 120.0.2210.22
- JupyterLab version: 4.0.0a4 and earlier (to be checked)

**Comment by krassowski** [comment]
Latest stable Chrome is good in `none` and laggy in `full` windowing mode. It does not seem to crash, but maybe I did not hit the right condition there.

**Comment by krassowski** [comment]
In windowing mode too much time is spend in scripting:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/049eb45a-e957-4e12-baa6-72c0bc2cd410)

Zoom in:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/dec22df8-dd28-4f21-b793-13ca10df327e)

We get stuck in `requestIdleCallback()`:

https://github.com/jupyterlab/jupyterlab/blob/aa845bf2a7d0c92acf49b7bed7d07a2cb748448c/packages/ui-components/src/components/vdom.ts#L73-L95

but there is no idle period for browser when user keeps the key pressed down. So I guess that every keydown event emitted adds a new callback and the browser gets overwhelmed. MDN recommends:

> Note: A timeout option is strongly recommended for required work, as otherwise it's possible multiple seconds will elapse before the callback is fired.

I think this could be the solution here.

**Comment by krassowski** [comment]
Possibly, using `setTimeout(callback, 0);` could be better because it should be sufficient to achieve the goal as per https://github.com/reactwg/react-18/discussions/5#discussioncomment-809064.

**Comment by JasonWeill** [comment]
@afshin @ericsnekbytes Are you planning to work on a fix for this issue? Thanks!

**Comment by JasonWeill** [comment]
As with #15594, given that we have a workaround for this bug (disable windowing for the notebook) I've removed the release blocker tag. This bug still needs to be fixed before we make windowing mode the default.

**Comment by krassowski** [comment]
Ok, so after disabling the cell toolbar plugin (which saves 35 ms on every cell by not calling `_removeToolbar` alone which halves the time to switch a cell) there are additional issues visible:

1) Switching a cell does a lot of things which may or may not be immediately needed; these are low impact because the total time spent here - ignoring the toolbar issue - is just 35ms, but still we may improve:
    - updating the command palette search results (rather not needed?) - 6 ms to win
    - updating the completer (needed, but not if jumping quickly over multiple cells)
      - calling `clearGhosts` force refreshes the editor; it should not be needed (5-6ms to win)
    
    ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/ea659bbd-15f3-4068-8169-37f60475c5af)
2) After switching a cell the filebrowser listing updates which can be a long task; here it took 500ms after just a single cell switch.
    ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/97d09455-82e3-4387-855d-cca09512edfd)
    
    I initially thought this would be related to "Show active file in file browser option" but it is also the case with it disabled:
    
    ![Screenshot from 2024-03-11 17-07-48](https://github.com/jupyterlab/jupyterlab/assets/5832902/5ff33a4d-53df-4a98-950a-326dd3434e29)
    
    Instead it either comes because:
    - `selectItemByName` is called [on every file change](https://github.com/jupyterlab/jupyterlab/blob/cdca0a20ba84af21922c390c46e086e50120d4cc/packages/filebrowser/src/listing.ts#L2010-L2027) and [on every `ActivateRequest`](https://github.com/jupyterlab/jupyterlab/blob/cdca0a20ba84af21922c390c46e086e50120d4cc/packages/filebrowser/src/listing.ts#L2032-L2041); the `activate` request is emitted on every execution of select cell below/above and by every other notebook command which calls `getCurrent()` :
    
    ![Screenshot from 2024-03-11 17-14-02](https://github.com/jupyterlab/jupyterlab/assets/5832902/3a3d4bb0-5be5-4030-8cb6-f6d983e55481)
    
3) When multiple cells are switched the filebrowser listing can end up in a deadly spiral of updates as the tasks from point (2) accumulate into long task groups; the subsequent DOM updates seem to further aggravate the situation; my theory for now is that this is what hangs the browser:

    ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/9ff67377-03a2-47dc-bfe1-bafa40c52161)

**Comment by krassowski** [comment]
So it seems that we have two implementations for marking the active item in file browser listing:
- the problematic one using `ActivateRequest` added in https://github.com/jupyterlab/jupyterlab/pull/1784 which only works for file in the same directory as opened in the browser
- the other one which is behind a setting which changes current directory when switching widgets (`navigateToCurrentDirectory` option); because this uses `labShell.currentChanged` signal it is not invoked on every activate request but only when a widget actually changes.

**Comment by krassowski** [comment]
I believe https://github.com/jupyterlab/jupyterlab/pull/15970 solves the issue. I do not see a consistent improvement when using `setTimeout` over `requestIdleCallback` (except for it being easier to understand the profiles).

I opened follow-up issues on further performance improvements:
- https://github.com/jupyterlab/jupyterlab/issues/15971
- https://github.com/jupyterlab/jupyterlab/issues/15972
