### ISSUE TITLE
Plugin manager doesn't allow users to enable an extension

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15486]
## Description
To disable extensions, the plugin manager seems to be writing the `page_config` to the `sys_prefix` location and not a location in the user directory. Whenever I try to disable a plugin it throws the following error  in the UI - 
```
Error when performing an action.
Reason given:
Error: PermissionError(13, 'Permission denied')

```

and the following error in the console - 
```
ERROR 16:11:53 500 POST /lab/api/plugins?1701686512826 (choudhdi@10.240.172.120) 382.22ms referer=http://localhost:8888/lab/workspaces/auto-n
```

## Reproduce

Try to disable any extension using the plugin manager.

## Expected behavior

It shouldn't throw a permission denied error.

## Context
jupyterlab==4.1.0a4

**Comment by krassowski** [comment]
Yes, `sys_prefix` as a non-configurable default was inherited from the extension manager. I think we should make it configurable, it should be rather straightforward (and the CLI commands already have a flag to configure it).
