### ISSUE TITLE
Update "jlpm config set registry" command in documentation

### ISSUE THREAD

**Issue by robinsonmhj** [jupyterlab/jupyterlab#15481]
when I try to setup registry, I get the following error

Usage Error: Couldn't find a configuration settings named "registry"

$ yarn config set [--json] [-H,--home] <name> <value>

Command is jlpm config set registry https://jfrog.io/artifactory/api/

Environment
python 3.11.4
jupyterlab 4.0.9

**Comment by krassowski** [comment]
Thanks for reporting @robinsonmhj. Could you try:

```
jlpm config set npmRegistryServer https://jfrog.io/artifactory/api/
```

It looks like the documentation was not updated after transition from yarn 1.x to 3.x:

https://github.com/jupyterlab/jupyterlab/blob/603b109abdd41517126d76654b9895d9cbe94967/docs/source/getting_started/installation.rst?plain=1#L192

**Comment by DcWire** [comment]
Hey @krassowski  , its my first contribution to a repository and I am eager to take this up. Can I be assigned for this task? Also, please correct me if I am wrong, I have to correct the line you've given 
Line 192 in /docs/source/getting_started/installation.rst to 
jlpm config set npmRegistryServer https://jfrog.io/artifactory/api/
Thank you.
