### ISSUE TITLE
JupyterLab interactive widgets

### ISSUE THREAD

**Issue by cornhundred** [jupyterlab/jupyterlab#1548]
Hi, 

I am getting the following error when I try to use an interactive widget

`Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"
`

I have run this command already and I am able to get the widget working in Jupyter Notebook. Do I need to run a different command for JupyterLab?

-Nick

**Comment by blink1073** [comment]
Hi @cornhundred, support for ipywidgets in JupyterLab is still a work in progress.  Development is in https://github.com/ipython/ipywidgets/tree/master/jupyterlab_widgets.

**Comment by jasongrout** [comment]
You'll need to install the jupyterlab_widgets package and enable the lab extension:

```
pip install jupyterlab_widgets
jupyter labextension install --sys-prefix --py jupyterlab_widgets
jupyter labextension enable --sys-prefix --py jupyterlab_widgets
```
I think the current release supports JLab 0.13.2, so if you've already upgraded to 0.14.0, you'll need to either wait until we update, or we welcome a PR.

**Comment by jasongrout** [comment]
@cornhundred - did that answer your question?

**Comment by cornhundred** [comment]
I tried those commands (to install and jupyterlab_widgets) and downgraded to Jupyter Lab 0.13.2, but I am still seeing the error 

`Widget Javascript not detected. It may not be installed or enabled properly.`

**Comment by cornhundred** [comment]
I'm also seeing the following errors from pip

`
>> jupyter labextension install --sys-prefix --py jupyterlab_widgets

`
Installing /Users/nickfernandez/anaconda/lib/python2.7/site-packages/jupyterlab_widgets/static -> jupyterlab_widgets
Up to date: /Users/nickfernandez/anaconda/share/jupyter/labextensions/jupyterlab_widgets/jupyterlab_widgets.bundle.js
Up to date: /Users/nickfernandez/anaconda/share/jupyter/labextensions/jupyterlab_widgets/jupyterlab_widgets.bundle.js.manifest
Up to date: /Users/nickfernandez/anaconda/share/jupyter/labextensions/jupyterlab_widgets/jupyterlab_widgets.css
        X is not version compatible with installed JupyterLab version 0.13.1
            Expects JupyterLab version ^0.13.1 from packaged module @jupyterlab/nbwidgets@0.6.6/lib/output.js
            Expects JupyterLab version ^0.13.1 from packaged module @jupyterlab/nbwidgets@0.6.6/lib/plugin.js

    To enable this labextension in the browser every time JupyterLab loads:
    
          jupyter labextension enable jupyterlab_widgets --py --sys-prefix

`
>> jupyter labextension enable --sys-prefix --py jupyterlab_widgets

Enabling extension jupyterlab_widgets...
Enabling: jupyterlab_widgets
- Writing config: /Users/nickfernandez/anaconda/etc/jupyter
        X is not version compatible with installed JupyterLab version 0.13.1
            Expects JupyterLab version ^0.13.1 from packaged module @jupyterlab/nbwidgets@0.6.6/lib/output.js
            Expects JupyterLab version ^0.13.1 from packaged module @jupyterlab/nbwidgets@0.6.6/lib/plugin.js `

**Comment by rsinha25** [comment]
Hi, so looks like we need to be on 0.13.2 for ipywidgets to work in JLab, is it?

**Comment by jasongrout** [comment]
We're trying to keep up to date. 0.6.8 now requires JLab 0.15.0: https://github.com/ipython/ipywidgets/commit/c2b20063a831a602f5d4948924ae74f2b73f2302

**Comment by infiniteNumber** [comment]
Hi, 
I got the same error. In this video, widget seems working with jupyterlab.
https://www.youtube.com/watch?v=CoGCuliGNos&feature=youtu.be&t=14m

Do you know which version it is? 
I tried jupyterlab(0.17.4 and 0.16.2) and jupyterlab-widgets(0.6.15) but not working.

**Comment by roseknob** [comment]
@jasongrout @infiniteNumber I second the note above that it doesn't seem to work in the released version? My JLab is build on top of JHub, not sure if there is any JLab that's meant to be separated used, and if that would be a different environment.

**Comment by jasongrout** [comment]
jupyterlab_widgets 0.6.15 should work with jupyterlab 0.16.2: https://github.com/ipython/ipywidgets/blob/master/jupyterlab_widgets/package.json#L9

We're working on upgrading to 0.17.4 in https://github.com/ipython/ipywidgets/pull/1122

**Comment by jasongrout** [comment]
(likely jupyterlab 0.18 will be released before we're done with ipython/ipywidgets#1122, so we may just skip jlab 0.17, and go straight to being compatible with jlab 0.18)

**Comment by roseknob** [comment]
thanks @jasongrout I found widget compatibility is important to use jlab productively, because we edit and play interactively. Looking forward for the releases.

**Comment by infiniteNumber** [comment]
thanks @jasongrout

**Comment by jasongrout** [comment]
Thanks. Since lab is still alpha, it's a fast moving target. It'll settle down before too long.

**Comment by jasongrout** [comment]
Closing this question as answered - please feel free continue discussing (or even better, open an issue in ipywidgets) if the versions mentioned above don't work for you.

**Comment by JuanKRod** [comment]
Has this issue been solved? Im still having having an error while running this command : 

bash-3.2$ jupyter labextension enable --sys-prefix --py jupyterlab_widgets

Error MSG 

UnboundLocalError: local variable 'proc' referenced before assignment

any alternative solutions to visualize widgets ?

**Comment by vidartf** [comment]
@JuanKRod That is an outdated package. See the ipywidgets documentation for up to date instructions: https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension

**Comment by JuanKRod** [comment]
I have followed all the instructions & still does not work

**Comment by JuanKRod** [comment]
Im getting this error : ValueError:
"@jupyter-widgets/jupyterlab-manager@0.33.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.10.0-0 <0.11.0-0    >=0.15.0-0 <0.16.0-0 @jupyterlab/application
>=0.10.0-0 <0.11.0-0    >=1.0.1-0 <2.0.0-0   @jupyterlab/coreutils
>=0.10.0-0 <0.11.0-0    >=0.15.0-0 <0.16.0-0 @jupyterlab/notebook
>=0.10.0-0 <0.11.0-0    >=0.15.0-0 <0.16.0-0 @jupyterlab/rendermime
>=0.49.0-0 <0.50.0-0    >=1.0.1-0 <2.0.0-0   @jupyterlab/services

**Comment by vidartf** [comment]
That is another issue, with a suggested solution in #3608. For now, I would recommend you to update JupyterLab itself using whichever package manager you initially used to install it (e.g. `conda` or `pip`).

**Comment by JuanKRod** [comment]
Im not quite sure what I did to be honest, but I managed to make it to work, so it's up and running iwidgets with jupyterlab =) - thank you for the support & quick reply! 

you guys are building a freaking powerful & useful tool - kudos 

@vidartf

**Comment by vidartf** [comment]
🎉
