### ISSUE TITLE
Code block inside markdown works in Jupyter Notebook, but Fails in Jupyter Lab

### ISSUE THREAD

**Issue by brettforbes** [jupyterlab/jupyterlab#15492]
## Description

The objective is to be able to format TypeQL, the query language from [Vaticle Typedb](https://typedb.com/docs/typeql/overview) as a code block inside a markdown cell. An example query is below:
```
match
   $a isa identity,
      has stix-id "identity--27c2fdc0-bf9c-46d8-aab1-658948cd2ed6",
      has $b;
   $c isa stix-sub-object,
      has $d;
   $e (owner:$a, pointed-to:$c) isa embedded;
   $f isa stix-sub-object, 
      has $g;
   $h (owner:$c, pointed-to:$f) isa embedded;
   $l (owner:$f, pointed-to:$j) isa embedded;
   get;
```
This seems to work perfectly in Jupyter Notebook using the Perl code block, as shown in the image below
![image](https://github.com/jupyterlab/jupyterlab/assets/24556510/bbc3996b-85f1-4b8c-acc6-2e1dd13878ba)

but if I try to do the same in  Jupyter Lab (latest version, fresh install), then my raw looks like the image below
![image](https://github.com/jupyterlab/jupyterlab/assets/24556510/6c20d05d-38e3-485c-9f52-d690a2358ca9)

which seems correct, but when the cell is played and the rendering happens, some errors clearly arise

![image](https://github.com/jupyterlab/jupyterlab/assets/24556510/892c9d70-b723-420d-af8b-771c40319089)

The errors are:

1. Looking closely one can see the triple backtick is now at the end of the second last line in the code block, above the 'get;'
2.  The code colouring is no longer evident, unlike the Jupyter Notebook (compare images), e.g.the id should be in red between the quotes
3. The 'get;" code line is now clearly outside of the code block
4. The following image link, no longer appears as a link (compare raw to rendered)
5. The following text is all green

Why does the rendering work on Jupyter Notebook, yet not on Jupyter Lab??? Is this a user error, or is there soem subtle problem here?? 

Can you help please?

**Comment by JasonWeill** [comment]
@brettforbes Thanks for opening this issue! When you're running JupyterLab, what OS and browser are you running? We've seen issues with markdown parsing, related to line endings, on Chrome and Windows: see #14752. Please take a look at that older issue; does it match what you're seeing here?

**Comment by brettforbes** [comment]
Genius, 
1. it is on Windows v11
2. it is cut and paste
3. it is on JupyterLab not on Jupyter

however it is on Windows Edge, not Chrom, but i believe they use the same rendering engine, true?
