### ISSUE TITLE
Word wrapping in webpdf export

### ISSUE THREAD

**Issue by PetteriAimonen** [jupyterlab/jupyterlab#15500]
## Description

When exporting to webpdf or using File->Print, IPython cells are not word wrapped.
Whether or not word wrapping is enabled in jupyterlab settings doesn't affect print output.
Word wrapping works ok in the editor view

## Reproduce

1. Add IPython cell in a notebook and write a long line of text.
2. Select File -> Print.
3. Observe that the long line is not word-wrapped. Instead it is cut off at the edge.

![Screenshot from editor](https://github.com/jupyterlab/jupyterlab/assets/922265/3a579ac9-de2f-42b7-a943-55bf5fbd05cd)

![Screenshot from print preview](https://github.com/jupyterlab/jupyterlab/assets/922265/2a3cd60e-e12a-4134-bdcb-6874786333b6)

## Expected behavior

I think webpdf and print output should always word-wrap, regardless of editor settings.
There is no way to scroll the output in PDF or paper, so cutting it off loses information.

## Context

- Operating System and version: Ubuntu 22.04
- Browser and version: Firefox 120.0.1
- JupyterLab version: 3.6.6

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/petteri/bin
	/home/petteri/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/home/petteri/.local/bin
	/usr/lib/python310.zip
	/usr/lib/python3.10
	/usr/lib/python3.10/lib-dynload
	/home/petteri/.local/lib/python3.10/site-packages
	/usr/local/lib/python3.10/dist-packages
	/usr/lib/python3/dist-packages
	/usr/lib/python3.10/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

platform.platform():
	Linux-6.2.0-36-generic-x86_64-with-glibc2.35

which -a jupyter:
	/home/petteri/bin/jupyter
	/home/petteri/bin/jupyter

pip list:
	Package                           Version
	--------------------------------- ------------------------------------
	aiofiles                          22.1.0
	aiohttp                           3.8.1
	aiosignal                         1.2.0
	aiosqlite                         0.19.0
	alabaster                         0.7.12
	altgraph                          0.17.4
	anyio                             4.1.0
	apiclient                         1.0.4
	appdirs                           1.4.4
	argon2-cffi                       23.1.0
	argon2-cffi-bindings              21.2.0
	arrow                             1.3.0
	astroid                           2.9.3
	astropy                           5.0.2
	async-lru                         2.0.4
	async-timeout                     4.0.1
	attrs                             23.1.0
	Automat                           20.2.0
	av                                8.1.0
	Babel                             2.13.1
	backcall                          0.2.0
	bashlex                           0.18
	bcc                               0.18.0
	bcrypt                            3.2.0
	beautifulsoup4                    4.10.0
	beniget                           0.4.1
	bidict                            0.21.3
	binwalk                           2.3.3
	bleach                            6.1.0
	blinker                           1.4
	Brlapi                            0.8.3
	Brotli                            1.0.9
	capstone                          4.0.2
	certifi                           2020.6.20
	cffi                              1.15.1
	chardet                           4.0.0
	charset-normalizer                2.0.6
	chrome-gnome-shell                0.0.0
	click                             8.0.3
	click-plugins                     1.1.1
	cmsis-pack-manager                0.5.2
	colorama                          0.4.4
	colorlog                          6.6.0
	comm                              0.2.0
	command-not-found                 0.3
	commentjson                       0.9.0
	compiledb                         0.10.1
	configobj                         5.0.6
	constantly                        15.1.0
	cov-core                          1.15.0
	coverage                          6.2
	cryptography                      3.4.8
	cupshelpers                       1.0
	cycler                            0.11.0
	Cython                            3.0.0
	dbus-python                       1.2.18
	debugpy                           1.8.0
	decorator                         4.4.2
	defer                             1.0.6
	defusedxml                        0.7.1
	devscripts                        2.22.1ubuntu1
	distlib                           0.3.4
	distro                            1.7.0
	distro-info                       1.1+ubuntu0.1
	dnspython                         2.1.0
	docutils                          0.17.1
	dpkt                              1.9.2
	ds1054z                           0.4.0
	duplicity                         0.8.21
	easy-scpi                         0.1.4
	entrypoints                       0.4
	et-xmlfile                        1.0.1
	euclid3                           0.1
	exceptiongroup                    1.2.0
	ExifRead                          2.3.2
	fasteners                         0.14.1
	fastjsonschema                    2.19.0
	ffmpeg                            1.4
	filelock                          3.6.0
	Flask                             2.0.1
	Flask-WTF                         0.14.3
	fonttools                         4.29.1
	fqdn                              1.5.1
	frozenlist                        1.2.0
	fs                                2.4.12
	future                            0.18.2
	galternatives                     1.0.8
	gast                              0.5.2
	GDAL                              3.4.1
	Genshi                            0.7.6
	gevent                            21.8.0
	git-filter-repo                   2.38.0
	gpg                               1.16.0
	greenlet                          3.0.1
	grpcio                            1.59.0
	grpcio-tools                      1.59.0
	gyp                               0.1
	hidapi                            0.14.0
	html5lib                          1.1
	httplib2                          0.20.2
	hyperlink                         21.0.0
	hypothesis                        6.36.0
	idna                              3.3
	imagesize                         1.3.0
	importlib-metadata                4.6.4
	importlib-resources               6.0.1
	incremental                       21.3.0
	iniconfig                         1.1.1
	intelhex                          2.3.0
	intervaltree                      3.1.0
	iotop                             0.6
	ipykernel                         6.27.1
	ipympl                            0.9.3
	ipython                           7.31.1
	ipython_genutils                  0.2.0
	ipywidgets                        8.1.1
	isoduration                       20.11.0
	isort                             5.6.4
	itsdangerous                      2.1.0
	jdcal                             1.0
	jds6600                           1.1.1
	jedi                              0.18.0
	jeepney                           0.7.1
	Jinja2                            3.0.3
	json5                             0.9.14
	jsonpointer                       2.4
	jsonschema                        4.20.0
	jsonschema-specifications         2023.11.2
	jupyter                           1.0.0
	jupyter_client                    7.4.9
	jupyter-console                   6.6.3
	jupyter-contrib-core              0.4.2
	jupyter_core                      5.5.0
	jupyter-events                    0.9.0
	jupyter-highlight-selected-word   0.2.0
	jupyter-lsp                       2.2.1
	jupyter-nbextensions-configurator 0.6.3
	jupyter_server                    2.11.1
	jupyter_server_fileid             0.9.0
	jupyter_server_terminals          0.4.4
	jupyter_server_ydoc               0.8.0
	jupyter-ydoc                      0.2.5
	jupyterlab                        3.6.6
	jupyterlab_pygments               0.3.0
	jupyterlab_server                 2.25.2
	jupyterlab-snippets               0.4.1
	jupyterlab-widgets                3.0.9
	keyring                           23.5.0
	KiKit                             1.4.0
	kiwisolver                        1.3.2
	language-selector                 0.1
	lark                              1.1.7
	lark-parser                       0.7.8
	launchpadlib                      1.10.16
	lazr.restfulclient                0.14.4
	lazr.uri                          1.0.6
	lazy-object-proxy                 0.0.0
	libusb-package                    1.0.26.2
	libusb1                           2.0.1
	libvirt-python                    8.0.0
	llvmlite                          0.38.0
	lockfile                          0.12.2
	logilab-common                    1.8.2
	louis                             3.20.0
	lxml                              4.8.0
	lz4                               3.1.3+dfsg
	macaroonbakery                    1.3.1
	magpylib                          4.4.0
	Mako                              1.1.3
	Markdown                          3.3.6
	markdown2                         2.4.10
	Markups                           3.1.3
	MarkupSafe                        2.0.1
	matplotlib                        3.5.1
	matplotlib-inline                 0.1.3
	mccabe                            0.6.1
	mistune                           3.0.2
	mock                              4.0.3
	monotonic                         1.6
	more-itertools                    8.10.0
	mpld3                             0.5.9
	mpmath                            0.0.0
	multidict                         5.1.0
	mypy-extensions                   0.4.3
	natsort                           8.4.0
	nbclassic                         1.0.0
	nbclient                          0.9.0
	nbconvert                         7.11.0
	nbformat                          5.9.2
	nest-asyncio                      1.5.4
	netaddr                           0.8.0
	netifaces                         0.11.0
	networkx                          2.4
	nose2                             0.9.2
	notebook                          6.5.6
	notebook_shim                     0.2.3
	numba                             0.55.1
	numericalunits                    1.25
	numexpr                           2.8.1
	numpy                             1.21.5
	oauthlib                          3.2.0
	olefile                           0.46
	openpyxl                          3.0.9
	overrides                         7.4.0
	OWSLib                            0.25.0
	packaging                         21.3
	paho-mqtt                         1.5.1
	pandas                            1.3.5
	pandocfilters                     1.5.0
	paramiko                          2.9.3
	parso                             0.8.1
	pathspec                          0.9.0
	pbr                               5.8.0
	pcbnewTransition                  0.3.4
	pexpect                           4.8.0
	PhysicalQuantities                1.1.1
	pickleshare                       0.7.5
	Pillow                            9.0.1
	pip                               22.0.2
	platformdirs                      2.5.1
	playwright                        1.40.0
	plotly                            5.4.0
	pluggy                            0.13.0
	ply                               3.11
	pooch                             1.7.0
	prettytable                       0.7.2
	prometheus-client                 0.19.0
	prompt-toolkit                    3.0.41
	protobuf                          4.24.4
	psutil                            5.9.0
	psycopg2                          2.9.2
	ptyprocess                        0.7.0
	py                                1.10.0
	pyasn1                            0.4.8
	pyasn1-modules                    0.2.1
	PyAudio                           0.2.11
	pybars3                           0.9.7
	pycairo                           1.20.1
	pycparser                         2.21
	pycryptodomex                     3.11.0
	pycups                            2.0.1
	pyedbglib                         2.22.0.7
	pyee                              11.0.1
	pyelftools                        0.29
	pyenchant                         3.2.0
	pyerfa                            2.0.0.1
	pyftdi                            0.55.0
	pygccxml                          2.2.1
	Pygments                          2.11.2
	PyGObject                         3.42.1
	PyHamcrest                        2.0.2
	pyinotify                         0.9.6
	pyinstaller                       6.0.0
	pyinstaller-hooks-contrib         2023.9
	PyJWT                             2.3.0
	pylink-square                     1.2.0
	pylint                            2.12.2
	pymacaroons                       0.13.0
	pymcuprog                         3.14.2.9
	PyMeta3                           0.5.1
	PyNaCl                            1.5.0
	pyocd                             0.35.1
	PyOpenGL                          3.1.5
	pyOpenSSL                         21.0.0
	pyparsing                         2.4.7
	pypng                             0.0.19
	pyproj                            3.3.0
	PyQt5                             5.15.6
	PyQt5-sip                         12.9.1
	pyqtgraph                         0.12.4
	PyQtWebEngine                     5.15.5
	pyRFC3339                         1.1
	pyrsistent                        0.18.1
	pyserial                          3.5
	pytest                            6.2.5
	pytest-arraydiff                  0.5.0
	pytest-astropy                    0.9.0
	pytest-astropy-header             0.2.0
	pytest-cov                        3.0.0
	pytest-doctestplus                0.11.2
	pytest-filter-subpackage          0.1.1
	pytest-mock                       3.6.1
	pytest-openfiles                  0.5.0
	pytest-remotedata                 0.3.3
	python-apt                        2.4.0+ubuntu2
	python-dateutil                   2.8.2
	python-debian                     0.1.43+ubuntu1.1
	python-engineio                   4.0.0
	python-json-logger                2.0.7
	python-magic                      0.4.24
	python-markdown-math              0.8
	python-rtmidi                     1.4.7
	python-socketio                   5.0.3
	python-vxi11                      0.9
	python-xlib                       0.29
	pythran                           0.10.0
	pytz                              2022.1
	pyudev                            0.22.0
	pyusb                             1.2.1.post1
	PyVISA                            1.11.3
	PyVISA-py                         0.5.1
	pyvista                           0.42.2
	pyxattr                           0.7.2
	pyxdg                             0.27
	PyYAML                            6.0.1
	pyzmq                             24.0.1
	qrtools                           2.1
	QScintilla                        2.11.6
	qtconsole                         5.5.1
	QtPy                              2.4.1
	quantiphy                         2.19
	referencing                       0.31.1
	regex                             2021.11.10
	reportlab                         3.6.8
	requests                          2.31.0
	rfc3339-validator                 0.1.4
	rfc3986-validator                 0.1.1
	roman                             3.3
	rpds-py                           0.13.2
	scipy                             1.8.0
	SCons                             4.0.1
	scooby                            0.7.3
	scour                             0.38.2
	SecretStorage                     3.3.1
	Send2Trash                        1.8.2
	service-identity                  18.1.0
	setuptools                        59.6.0
	Shapely                           1.8.5.post1
	Shredder                          2.9.0.Odd.Olm
	shutilwhich                       1.1.0
	simplejson                        3.17.6
	six                               1.16.0
	sniffio                           1.3.0
	snowballstemmer                   2.2.0
	solidpython                       1.1.3
	sortedcontainers                  2.1.0
	soupsieve                         2.3.1
	Sphinx                            4.3.2
	sphinx-rtd-theme                  1.0.0
	ssh-import-id                     5.11
	sympy                             1.9
	syncthing-gtk                     v0.9.4.4-ds-git20220108-9023143f8b93
	systemd-python                    234
	tables                            3.7.0
	tenacity                          6.3.1
	terminado                         0.18.0
	textile                           4.0.2
	thrift                            0.16.0
	tinycss2                          1.2.1
	toml                              0.10.2
	tomli                             2.0.1
	tornado                           6.4
	traitlets                         5.14.0
	Twisted                           22.1.0
	types-python-dateutil             2.8.19.14
	typing_extensions                 4.7.1
	ubuntu-advantage-tools            8001
	ubuntu-drivers-common             0.0.0
	ufoLib2                           0.13.1
	ufw                               0.36.1
	unattended-upgrades               0.1
	unicodedata2                      14.0.0
	unidiff                           0.5.5
	uri-template                      1.3.0
	urllib3                           1.26.5
	usb-creator                       0.3.7
	vboxapi                           1.0
	vtk                               9.2.6
	wadllib                           1.3.6
	wcwidth                           0.2.5
	webcolors                         1.13
	webencodings                      0.5.1
	websocket-client                  1.7.0
	Werkzeug                          2.0.2
	wheel                             0.37.1
	widgetsnbextension                4.0.9
	wrapt                             1.13.3
	WTForms                           2.2.1
	wxPython                          4.2.0
	xdg                               5
	xdot                              1.2
	xkit                              0.0.0
	xlrd                              1.2.0
	xlwt                              1.3.0
	xprintidle                        0.2
	y-py                              0.6.2
	yamllint                          1.26.3
	Yapps2                            2.2.1
	yarl                              1.7.2
	youtube-dl                        2021.12.17
	ypy-websocket                     0.8.4
	zipp                              1.0.0
	zope.event                        4.4
	zope.interface                    5.4.0

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Dec 07 12:14:45 raichu systemd[2017]: Started Jupyter.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.415 ServerApp] Package jupyterlab took 0.0000s to import
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.428 ServerApp] Package jupyter_lsp took 0.0120s to import
Dec 07 12:14:46 raichu jupyter[2860194]: [W 2023-12-07 12:14:46.428 ServerApp] A `_jupyter_server_extension_points` function was not found in jupy>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.431 ServerApp] Package jupyter_server_fileid took 0.0026s to import
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.436 ServerApp] Package jupyter_server_terminals took 0.0050s to import
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.481 ServerApp] Package jupyter_server_ydoc took 0.0439s to import
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.483 ServerApp] Package jupyterlab_snippets took 0.0016s to import
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.484 ServerApp] Package nbclassic took 0.0000s to import
Dec 07 12:14:46 raichu jupyter[2860194]: [W 2023-12-07 12:14:46.485 ServerApp] A `_jupyter_server_extension_points` function was not found in nbcl>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.486 ServerApp] Package notebook_shim took 0.0000s to import
Dec 07 12:14:46 raichu jupyter[2860194]: [W 2023-12-07 12:14:46.486 ServerApp] A `_jupyter_server_extension_points` function was not found in note>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.487 ServerApp] jupyter_lsp | extension was successfully linked.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.491 ServerApp] jupyter_server_fileid | extension was successfully linked.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.496 ServerApp] jupyter_server_terminals | extension was successfully linked.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.500 ServerApp] jupyter_server_ydoc | extension was successfully linked.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.505 ServerApp] jupyterlab | extension was successfully linked.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.505 ServerApp] jupyterlab_snippets | extension was successfully linked.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.511 ServerApp] nbclassic | extension was successfully linked.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.728 ServerApp] Package jupyter_nbextensions_configurator took 0.0047s to import
Dec 07 12:14:46 raichu jupyter[2860194]: [W 2023-12-07 12:14:46.728 ServerApp] A `_jupyter_server_extension_points` function was not found in jupy>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.728 ServerApp] jupyter_nbextensions_configurator | extension was found and enabled>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.728 ServerApp] jupyter_nbextensions_configurator | extension was successfully link>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.728 ServerApp] notebook_shim | extension was successfully linked.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.751 ServerApp] notebook_shim | extension was successfully loaded.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.753 ServerApp] jupyter_lsp | extension was successfully loaded.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.754 ServerApp] [jupyter_nbextensions_configurator] enabled 0.6.3
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.754 ServerApp] jupyter_nbextensions_configurator | extension was successfully load>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.754 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.754 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /home/petteri/g>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.754 FileIdExtension] ArbitraryFileIdManager : Configured database path: /home/pett>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.754 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database f>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.755 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices >
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.755 FileIdExtension] Attached event listeners.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.755 ServerApp] jupyter_server_fileid | extension was successfully loaded.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.756 ServerApp] jupyter_server_terminals | extension was successfully loaded.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.756 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.760 LabApp] JupyterLab extension loaded from /home/petteri/.local/lib/python3.10/s>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.760 LabApp] JupyterLab application directory is /home/petteri/.local/share/jupyter>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.762 ServerApp] jupyterlab | extension was successfully loaded.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.763 ServerApp] jupyterlab_snippets | extension was successfully loaded.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.767 ServerApp] nbclassic | extension was successfully loaded.
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.768 ServerApp] Serving notebooks from local directory: ...>
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.768 ServerApp] Jupyter Server 2.11.1 is running at:
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.769 ServerApp] http://...removed...
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.769 ServerApp]     http://...removed...
Dec 07 12:14:46 raichu jupyter[2860194]: [I 2023-12-07 12:14:46.769 ServerApp] Use Control-C to stop this server and shut down all kernels (twice >
Dec 07 12:14:46 raichu jupyter[2860194]: [C 2023-12-07 12:14:46.772 ServerApp]
</pre>
</details>

**Comment by davidbrochart** [comment]
Thanks for opening an issue @PetteriAimonen.
[Nbconvert](https://github.com/jupyter/nbconvert) is used when exporting a notebook, maybe the issue should be opened there?

**Comment by PetteriAimonen** [comment]
@davidbrochart Indeed, you are correct. I have added report there: https://github.com/jupyter/nbconvert/issues/2078

As a workaround for anyone else with this issue, add these lines to `share/jupyter/nbconvert/templates/lab/index.html.j2`:

```
pre {
  white-space: pre-wrap;
  word-wrap: break-word;
}
```
