### ISSUE TITLE
py ipynb   icon difference

### ISSUE THREAD

**Issue by xgdgsc** [jupyterlab/jupyterlab#15507]
### Problem

In file explorer, `py` and `ipynb` files have no difference in prepending icon.

<img width="172" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/1189869/e6e4f22a-898a-40b2-8034-efaa38b394bc">

### Proposed Solution

Different icon to make them more distinguished.

**Comment by krassowski** [comment]
This is not how I see them:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/7dc79b35-53dc-442e-84b0-91be0b8d281b)

Do you happen to have `jupytext` extension installed? Or another extension which provides alternative viewers for notebooks?

**Comment by xgdgsc** [comment]
Yes. I have jupytext

**Comment by krassowski** [comment]
jupytext changes filetype for `.py` files to "notebook" so you see a notebook icon; it is not a bug in JupyterLab. See https://github.com/mwouts/jupytext/issues/398.

**Comment by xgdgsc** [comment]
Thanks
