### ISSUE TITLE
Kernel execution_state becomes idle post long running cell

### ISSUE THREAD

**Issue by divyabiyani** [jupyterlab/jupyterlab#15529]
## Description

Post a long running cell, the kernel changes its execution_state to idle despite the consequent cells in queue for execution.

The UI cells ends up getting stuck in (*). 

## Reproduce

![Screenshot 2023-12-14 at 2 02 09 PM](https://github.com/jupyterlab/jupyterlab/assets/8852007/e09d3aa7-69db-4883-919c-a12b9d9c24aa)

## Expected behavior

All the cells should finish execution and then the kernel's execution_state should become idle.

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

This has been reproducible in multiple JupyterLab and notebook versions.

**Comment by krassowski** [comment]
Can you fill in the latest JupyterLab version in which you were able to reproduce this? Would you be open to testing the latest jupyterlab pre-release [4.1.0a4](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.1.0a4) too?

**Comment by divyabiyani** [comment]
@krassowski , I have tested in on 4.0.9, 4.0.6 and 3.6.3. Sure, I can give it a try.

**Comment by JasonWeill** [comment]
Do you see any errors in the terminal from which you started JupyterLab at a time when the kernel execution stops? Do you see any errors in your browser's developer tools' console?

**Comment by JasonWeill** [comment]
@divyabiyani What errors are you seeing in the terminal or console when kernel execution appears to stop?

@krassowski points out an issue related to real-time collaboration (RTC) with a similar effect: https://github.com/jupyterlab/jupyter-collaboration/issues/230 . Are you using RTC? (Based on your comment in #15527, which doesn't show `jupyter-collaboration` installed, this may not be the case.)

**Comment by krassowski** [comment]
Upon second reading I think the connection between these issues is unlikely, but it would still be good to confirm if you happen to use RTC.
