### ISSUE TITLE
ContentsManager.untitled_notebook sometime ignored. 

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1552]
Lab does not seem to respect `FileContentsManager.untitled_notebook`. Let say, – For example:

```
$ cat ~/.jupyter/jupyter_notebook_config.py
c.FileContentsManager.untitled_notebook='A Notebook has No Name - '
```

Classic notebook will create (`A Notebook has No Name - 1.ipynb` ...). Lab (still) create `Untilted1.ipynb`.

Arguably not such a used feature. Astonishingly if you start with `jupyter lab` and manually access `/tree` notebook also does not respect it...

**Comment by blink1073** [comment]
JupyterLab has its own config, similarly to how `JupyterHub` handles it, so anything in `jupyter_notebook_config.py` is not picked up.  cf https://github.com/jupyterhub/jupyterhub/blob/c7d7dec40da074ce3a5e86b38bea6f731b3493e3/jupyterhub/app.py#L237

**Comment by blink1073** [comment]
Ugh, sorry, I was thinking of the `.json` files.  Not sure what we should do about the `.py` files.

**Comment by blink1073** [comment]
It looks like those get handled the same way by JupyterHub - it loads the `.json` and `.py` files of its own type.

**Comment by blink1073** [comment]
Ah, it is `jupyterlab_config.py` by default: https://github.com/jupyter/jupyter_core/blob/616447137a99f2437f7270dd3d8382091fb3df97/jupyter_core/application.py#L112.

**Comment by blink1073** [comment]
Confirmed:

![image](https://cloud.githubusercontent.com/assets/2096628/22305587/b03083a6-e301-11e6-9304-2e5d2322c3b7.png)

**Comment by blink1073** [comment]
@jasongrout and I talked about this just now and we are going to do the following:

- JupyterLab will subclass `NotebookApp` and *only* change the `default_url`.
- The server extension will use its own configuration management but use the same `config_dir` as the notebook app.

As we move toward a `Jupyter Server` and the notebook becoming a server extension itself, we may want to revise the semantics of what a server extension is.  The `JupyterServerApp` could manage the config of each of the registered server extensions, including cli arguments, and provide the server app and a configuration object to the server extension entry point.

cc @SylvainCorlay

**Comment by Carreau** [comment]
Ha ! Thanks !

Take this issue as a config transition should be a bit more seamless then :-)
