### ISSUE TITLE
[Inline Completion] Notebook level completion (across different cells)

### ISSUE THREAD

**Issue by YongcaiHuang** [jupyterlab/jupyterlab#15532]
Hi,

I am glad to experience the upcoming inline completion provided by **jupyterlab-transformers-completer**, in the 4.1 pre-release.

It seems completion is within the cell level, meaning that completion will not consider what has been written in preceding cells. from my experience, it would be great if completion could consider all we have written to provide more accurate suggestions.

Or are there any settings for this?

Best.

**Comment by krassowski** [comment]
So this one is a decision by `jupyterlab-transformers-completer`, not a JupyterLab constraint. A similar approach is taken in the default draft implementation of inline provider for `jupyter-ai`. There is nothing stopping completion providers from using the full notebook (except that for long notebooks it will impact the inference time).

For example, the draft `jupyter-ai` implementation also sends the notebook name, notebook path and cell ID to the backend and then the model handler can use these information to extract more data from the notebook (or just embed the notebook name in the prompt for minimal additional context).

**Comment by jtpio** [comment]
Wouldn't it be possible for an inline completer implemented in an extension to make use of the `context` (a `IInlineCompletionContext`), check if it's a `NotebookPanel` and if so access its underlying model to get the content from other cells?
