### ISSUE TITLE
Heading indentation incorrect in table of contents when heading level is 6

### ISSUE THREAD

**Issue by raghunb05** [jupyterlab/jupyterlab#15538]
## Description

I have 6 levels of headings in my Jupyterlab notebook. The headings for each level are indented one within the other except for headings at level 6. This can be seen in the screenshot attached.

## Reproduce

1. Add 6 levels of headings in the markdown cells
2. Open Table of Contents left sidebar to observe the headings
3. The 6th level of headings are not properly indented within the 5th level.

## Expected behavior

Expected behaviour is that the 6th level of headings should be indented relative to the 5th level.

## Context

The version information is as below:
JupyterLab Version 3.6.3
Google Chrome Version 120.0.6099.109 (Official Build) (64-bit)
Windows 11, Version 10.0.22621

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>
<img width="514" alt="Screenshot 2023-12-17 153612" src="https://github.com/jupyterlab/jupyterlab/assets/154053784/08ed1c44-bf38-409d-b91c-0488bad4dee8">

**Comment by JasonWeill** [comment]
@raghunb05 Thank you for opening this issue! I noticed that you're using JupyterLab 3.6. The TOC (table of contents) extension was completely rewritten in JupyterLab 4. Do you still see this behavior in JupyterLab 4.0 or 4.1?

**Comment by JasonWeill** [comment]
In JupyterLab 4.x, when I increase the TOC's maximum depth to 6 heading levels, I see an appropriate level of indentation all the way to H6.

<img width="811" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/93281816/97f468e8-f80c-4398-bd66-292eccea4a09">


<img width="775" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/93281816/23f91388-97e0-4e5e-a383-ddf0fd96b6d7">

**Comment by raghunb05** [comment]
Yes, I am on JupyterLab 3.6.3. That's because that's the version packaged with the latest version of the Anaconda distribution. In any case, if the issue is resolved in JupyterLab 4.x, it can be closed. Thanks for the prompt response.

**Comment by JasonWeill** [comment]
If you can use conda-forge (e.g., `conda install -c conda-forge jupyterlab`) you should be able to get JupyterLab 4: https://anaconda.org/conda-forge/jupyterlab

Closing since this is fixed in Lab 4. Thank you for your contribution!
