### ISSUE TITLE
shift-tab tooltip should be hidden on any key press

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#1553]
Right now closing the tooltip requires either a mouse-click or another shift-tab. While by itself it isn't a disruptive behavior, if the user continues typing after using the tooltip, it will obstruct the text and very quickly become obsolete (if the user types an extra word).

Observed in v0.14

**Comment by blink1073** [comment]
Agreed (and this is the behavior of the classic notebook).
