### ISSUE TITLE
Cells intermittently being duplicated at the bottom of notebook

### ISSUE THREAD

**Issue by EZBUTD** [jupyterlab/jupyterlab#15544]
## Description

About once a day, I notice that my notebook has duplicated all it's cells at the bottom of the notebook, doubling the number of cells. The issue I see is very similar to the one described in https://github.com/jupyterlab/jupyterlab/issues/10852 although I can not confirm if RTC is causing the issue.
## Reproduce

I can't replicate this issue consistently but will try to document what behaviors I've seen lead up to it
1. Start Jupyter lab service with RTC enabled
2. Work from Mac for a while
3. Other users can join and edit/run 
4. After I close the browser or leave and come back after a few hours, I will see that the cells have been duplicated. This does not happen to notebooks which are not actively worked on or seen by other users so I think RTC may be linked to the issue.

## Expected behavior

Cells should not be duplicating

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
$ jupyter troubleshoot

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
$PATH:
        /usr/local/bin
        /usr/bin
        /bin
        /usr/local/games
        /usr/games

sys.path:
        /usr/local/bin
        /usr/local/lib/python311.zip
        /usr/local/lib/python3.11
        /usr/local/lib/python3.11/lib-dynload
        /home/jovyan/.local/lib/python3.11/site-packages
        /usr/local/lib/python3.11/site-packages

sys.executable:
        /usr/local/bin/python

sys.version:
        3.11.7 (main, Dec  5 2023, 19:21:52) [GCC 10.2.1 20210110]

platform.platform():
        Linux-5.15.97-x86_64-with-glibc2.31

which -a jupyter:
        /usr/local/bin/jupyter

pip list:
        Package                   Version
        ------------------------- ------------
        aiohttp                   3.9.1
        aiosignal                 1.3.1
        aiosqlite                 0.19.0
        alembic                   1.12.1
        ansi2html                 1.9.1
        anyio                     4.1.0
        argon2-cffi               23.1.0
        argon2-cffi-bindings      21.2.0
        arrow                     1.3.0
        asttokens                 2.4.1
        async-generator           1.10
        async-lru                 2.0.4
        attrs                     23.1.0
        awswrangler               3.4.2
        Babel                     2.13.1
        beautifulsoup4            4.12.2
        bleach                    6.1.0
        blinker                   1.7.0
        boto3                     1.33.13
        botocore                  1.33.13
        certifi                   2023.11.17
        certipy                   0.1.3
        cffi                      1.16.0
        charset-normalizer        3.3.2
        click                     8.1.7
        comm                      0.2.0
        contourpy                 1.2.0
        cryptography              41.0.6
        cycler                    0.12.1
        dash                      2.14.2
        dash-core-components      2.0.0
        dash-html-components      2.0.0
        dash-table                5.0.0
        debugpy                   1.8.0
        decorator                 5.1.1
        defusedxml                0.7.1
        executing                 2.0.1
        fastjsonschema            2.19.0
        Flask                     3.0.0
        fonttools                 4.46.0
        fqdn                      1.5.1
        frozenlist                1.4.0
        greenlet                  3.0.1
        idna                      3.6
        importlib-metadata        7.0.0
        ipykernel                 6.26.0
        ipython                   8.18.1
        ipython-genutils          0.2.0
        ipywidgets                8.1.1
        isoduration               20.11.0
        itsdangerous              2.1.2
        jedi                      0.19.1
        Jinja2                    3.1.2
        jmespath                  1.0.1
        json5                     0.9.14
        jsonpointer               2.4
        jsonschema                4.20.0
        jsonschema-specifications 2023.11.1
        jupyter_client            8.6.0
        jupyter_collaboration     2.0.0
        jupyter_core              5.5.0
        jupyter-dash              0.4.2
        jupyter-events            0.9.0
        jupyter-lsp               2.2.1
        jupyter_server            2.11.2
        jupyter_server_fileid     0.9.0
        jupyter_server_proxy      4.1.0
        jupyter_server_terminals  0.4.4
        jupyter-telemetry         0.1.0
        jupyter-ydoc              2.0.0
        jupyterhub                4.0.2
        jupyterlab                4.0.9
        jupyterlab_pygments       0.3.0
        jupyterlab_server         2.25.2
        jupyterlab-widgets        3.0.9
        kiwisolver                1.4.5
        Mako                      1.3.0
        MarkupSafe                2.1.3
        matplotlib                3.8.2
        matplotlib-inline         0.1.6
        mistune                   3.0.2
        multidict                 6.0.4
        nbclassic                 1.0.0
        nbclient                  0.9.0
        nbconvert                 7.11.0
        nbformat                  5.9.2
        nbgitpuller               1.2.0
        nest-asyncio              1.5.8
        notebook_shim             0.2.3
        numpy                     1.26.2
        oauthlib                  3.2.2
        overrides                 7.4.0
        packaging                 23.2
        pamela                    1.1.0
        pandas                    2.1.4
        pandocfilters             1.5.0
        parso                     0.8.3
        pexpect                   4.9.0
        Pillow                    10.1.0
        pip                       23.2.1
        platformdirs              4.0.0
        plotly                    5.18.0
        prometheus-client         0.19.0
        prompt-toolkit            3.0.41
        psutil                    5.9.6
        ptyprocess                0.7.0
        pure-eval                 0.2.2
        pyarrow                   14.0.1
        pycparser                 2.21
        pycrdt                    0.7.1
        pycrdt-websocket          0.12.5
        Pygments                  2.17.2
        pyOpenSSL                 23.3.0
        pyparsing                 3.1.1
        python-dateutil           2.8.2
        python-json-logger        2.0.7
        pytz                      2023.3.post1
        PyYAML                    6.0.1
        pyzmq                     25.1.1
        referencing               0.31.0
        requests                  2.31.0
        retrying                  1.3.4
        rfc3339-validator         0.1.4
        rfc3986-validator         0.1.1
        rpds-py                   0.13.1
        ruamel.yaml               0.18.5
        ruamel.yaml.clib          0.2.8
        s3transfer                0.8.2
        scipy                     1.11.4
        seaborn                   0.13.0
        Send2Trash                1.8.2
        setuptools                65.5.1
        simpervisor               1.0.0
        six                       1.16.0
        sniffio                   1.3.0
        soupsieve                 2.5
        SQLAlchemy                2.0.23
        stack-data                0.6.3
        tenacity                  8.2.3
        terminado                 0.18.0
        tinycss2                  1.2.1
        tornado                   6.3.3
        traitlets                 5.13.0
        types-python-dateutil     2.8.19.14
        typing_extensions         4.8.0
        tzdata                    2023.3
        uri-template              1.3.0
        urllib3                   2.0.7
        wcwidth                   0.2.12
        webcolors                 1.13
        webencodings              0.5.1
        websocket-client          1.6.4
        Werkzeug                  3.0.1
        wheel                     0.42.0
        widgetsnbextension        4.0.9
        yarl                      1.9.4
        zipp                      3.17.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
@EZBUTD Thank you for opening this issue! We're tracking RTC issues in the `jupyter-collaboration` repo. We have an issue that mentions duplicated cells in that repo: https://github.com/jupyterlab/jupyter-collaboration/issues/197

I'm going to close this issue in favor of the one on Jupyter Collaboration. Thanks again for your contribution!
