### ISSUE TITLE
ModuleNotFoundError: No module named 'notebook.notebookapp'

### ISSUE THREAD

**Issue by HeiKoBas** [jupyterlab/jupyterlab#15545]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
@HeiKoBas Thanks for opening this issue! Can you please provide the information requested in the issue template, including what you were doing when you found this error, and the version of JupyterLab you're using? Thanks!

**Comment by JasonWeill** [comment]
We don't have enough information to reproduce or identify the source of this error, so I'm closing this issue.
