### ISSUE TITLE
Default/Custom keyboard shortcuts initial state confusing within settings editor

### ISSUE THREAD

**Issue by e218736** [jupyterlab/jupyterlab#15557]
### Problem

On initial render of keyboard shortcuts within settings editor all shortcuts show as 'custom' with the ability to reset although the specified keyboard shortcuts are the default.
![Capture](https://github.com/jupyterlab/jupyterlab/assets/147728997/99dcd748-3343-429d-bf4f-30b1d0f9a887)

Selecting reset for each alters the UI to state that these are the 'default' keyboard shortcuts.

When the keyboard shortcuts have been edited or a new shortcut added, the UI reflects this and again shows as 'custom' with the ability to reset.

I think that it would make more sense for the keyboard shortcuts that are initially rendered to be displayed as 'Default' rather than 'Custom'. 

### Proposed Solution

The initial state of page does not render custom/ reset link. These are only rendered once the user has edited or added any keyboard shortcuts on a row by row basis.

**Comment by krassowski** [comment]
Related to https://github.com/jupyterlab/jupyterlab/issues/15326

**Comment by krassowski** [comment]
This is no longer happening as of 4.1.5, closing.
