### ISSUE TITLE
When searching for 'foo' and replacing with 'foo bar', replacing does not skip to the next occurrence of 'foo'

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#15572]
## Description

When I search for a string X, then replace it with a string Y that includes X as a substring, clicking "Replace" on the first occurrence causes the first occurrence to be selected again.

![repeat-replace](https://github.com/jupyterlab/jupyterlab/assets/93281816/a59e649a-8475-4ee8-af78-a3cfec98b1a2)

## Reproduce

1. Enter `foo bar foo bar foo bar` in a cell.
2. Search for `foo` and choose to replace with `foo baz`.
3. Click "Replace" on the first occurrence of `foo`.
4. The first occurrence of `foo`, which is now followed by `baz`, remains selected.

## Expected behavior

The second occurrence of `foo` is selected.

## Context

- Operating System and version: macOS 13.6.3 "Ventura"
- Browser and version: Firefox 115.5.0esr (64-bit)
- JupyterLab version: 4.0.3

**Comment by krassowski** [comment]
Confirmed as still present in 4.1.0b0 and affecting both notebook and file editor. This worked well in 3.6.x.

**Comment by krassowski** [comment]
Related to https://github.com/jupyterlab/jupyterlab/issues/13968

**Comment by JasonWeill** [comment]
Still an issue in tip of `main`.
