### ISSUE TITLE
Page up/page down partially scrolls notebook back

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15594]
## Description

Pressing Pg up/pg down in a cell scrolls notebook in unexpected way.

## Reproduce

1. Switch windowing mode to full
2. Open a notebook with more cells than fit in the viewport
3. Press pg down in the cell once
4. See that it navigates to top/bottom of the cell (ok)
5. Press pg down in the cell again
6. See that it scrolls notebook (ok)
7. Press pg down in the cell again and again
8. See that notebook scrolls in chaotic way jumping back to the active cell (not ok)

![unexpected-scroll](https://github.com/jupyterlab/jupyterlab/assets/5832902/bd5e9145-cd83-4131-a8ff-237a927e10fa)

## Expected behavior

Scrolling in full windowing mode behaves predictably.

## Context

- Browser: Chrome
- JupyterLab version: 4.1.0b0

**Comment by JasonWeill** [comment]
Because windowed notebooks are not the default in 4.1.0, this bug, while noticeable and annoying, should not block a 4.1.0 release.

**Comment by krassowski** [comment]
This is interesting, so `keydown` is invoked in both `full` and `none`/`defer` mode; the difference comes down to `activeCell.inViewport` property evaluating to `false` in `full` mode (correctly) and to `true` in `none`/`defer` modes (incorrectly?).

https://github.com/jupyterlab/jupyterlab/blob/4df55ca002fdd83773aaacc7f390b2051a3d7e0f/packages/notebook/src/widget.ts#L2212-L2217

`inViewport` is just a boolean flag:

https://github.com/jupyterlab/jupyterlab/blob/4df55ca002fdd83773aaacc7f390b2051a3d7e0f/packages/cells/src/widget.ts#L240-L251

which gets set when windowing is active:

https://github.com/jupyterlab/jupyterlab/blob/4df55ca002fdd83773aaacc7f390b2051a3d7e0f/packages/notebook/src/windowing.ts#L238

It might be that we do not need to call `focus` if the cell is out of viewport, but it needs more investigation. The condition above was recently modified in https://github.com/jupyterlab/jupyterlab/pull/15286.

**Comment by krassowski** [comment]
It feels like we should rely on the internal heuristics of CodeMirror to decide when to scroll. These unfortunately are not exposed via a public API and just invoke a very clever scroll implementation, which however cannot succeed when in a virtualized list as it does not know about the offset which is hidden. I opened https://github.com/codemirror/dev/issues/1355 to ask if a public entrypoint could be added but it may be a big ask.

**Comment by erkin98** [comment]
i'm getting similar issue which, i have 50 line of code inside one cell, so when i try to add cell it scrols the notebook whole the way down
