### ISSUE TITLE
Kernel-related shortcuts (e.g. restart, interrupt) do not work anymore

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15599]
## Description

Shortcuts such as <kbd>I</kbd> <kbd>I</kbd> (interrupt) or <kbd>0</kbd> <kbd>0</kbd> do not work in 4.1.0b0. Manually selecting the command from menu or command palette works. My custom shortcut (<kbd>ctrl</kbd> + <kbd>R</kbd>) for "restart and run up to selected cell" does not work anymore either.

This is likely  an issue with the selector (`[data-jp-kernel-user]:focus`) due to changes introduced in https://github.com/jupyterlab/jupyterlab/pull/14115 (CC @gabalafou @brichet).

## Reproduce

![shortcuts-brokendoes-not-work](https://github.com/jupyterlab/jupyterlab/assets/5832902/5a7c8335-b1a1-46ce-93c3-368bc873f503)

## Expected behavior

- Default shortcuts for kernel actions work
  - possibly adding a space before `:focus` would be sufficient to fix this
- Shortcuts configured by users are ported over automatically or there should be a user-facing entry in the changelog documenting how/which shortcuts will need to be reconfigured (e.g. by updating selectors)

## Context

- JupyterLab version: 4.1.0b0

**Comment by krassowski** [comment]
Also, it is worth checking if there are any other selectors with `:focus` touching the notebook node selected by data attributes. This will potentially affect extensions too; for known selectors we could indeed swap them in settings transparently but for shortcuts added in extensions it would be harder; so two other things we should do:
- [ ] check the extensions in `jupyterlab` and `jupyterlab-contrib` for `:focus` containing selectors in schema
- [ ] ensure there is an entry in extension migration guide explaining the changes which extension authors may be needed to make

**Comment by brichet** [comment]
> * possibly adding a space before `:focus` would be sufficient to fix this

This would make some characters unusable in the cell input (like "i" in this case).
The selector `"[data-jp-kernel-user] :focus:not(:read-write)"` should avoid it.

**Comment by brichet** [comment]
> * check the extensions in `jupyterlab`

Looking for `:focus` selector in jupyterlab, I found that https://github.com/jupyterlab/jupyterlab/blob/main/examples/notebook/src/commands.ts has not been updated with the correct selectors.

For example: 
https://github.com/jupyterlab/jupyterlab/blob/eff7d42d5437a1f7eef6ab88d96406c5eb5ec2c5/examples/notebook/src/commands.ts#L433-L437

Except for this file and the one you mentioned, I did not find any other `:focus` selector touching the notebook node in the schema of `jupyterlab` core extensions (searching for `:focus` in all non-CSS files).

**Comment by krassowski** [comment]
In jupyterlab-contrib there is:
- 6 `.jp-Notebook:focus` bindings in `rise` in [plugin.json](https://github.com/jupyterlab-contrib/rise/blob/fb838ba8f26e04223b35d916b01a9489069a190c/packages/lab/schema/plugin.json)
- 20 `.jp-Notebook:focus` bindings in [plugin.json](https://github.com/jupyterlab-contrib/jupyterlab-vim/blob/b7eb0e2657c82c5942fa84349955794efff311a1/schema/plugin.json)

Looking broader beyond repos maintained by Jupyter community, I see a few extensions, many personal configuration files and a few downstreams using old selectors e.g. https://github.com/datalayer/jupyter-ui CC @echarles

So I think there is a case for some automatic substitution of the old for new to make the transition smooth.
