### ISSUE TITLE
In windowed notebook cells are sometimes rendered out of order

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15610]
## Description

In windowed notebook cells are sometimes rendered out of order. The order of navigation is thus broken in cells, affects both edge navigation and command mode navigation with arrows. Dragging the affected cells does not change their position.

It looks like a problem with the soft hiding of cells; it looks like a soft-hidden cell stuck around, but maybe this is just a symptom of another problem. Cutting and pasting the affected cell solves the problem.

It is likely related to #15286

## Reproduce

I don't know yet but it only happens in long notebooks with full windowing mode enabled. It likely involves scrolling the cell in/out view and possibly some edge cases on modifications

## Expected behavior

Cells are rendered in correct order.

## Context

- Browser and version: Chrome
- JupyterLab version: 4.1.0b0

**Comment by JasonWeill** [comment]
@krassowski Just to be sure, do you see this behavior in 4.0.x?

**Comment by krassowski** [comment]
No, it is 4.1.0b0 specific. As mentioned, likely related to https://github.com/jupyterlab/jupyterlab/pull/15286.

**Comment by DenisaCG** [comment]
I'm currently looking into this issue and will keep you posted on the progress. Feel free to jump in if you have any insights or suggestions. Thanks!

**Comment by DenisaCG** [comment]
I'm having some trouble reproducing the issue. So far I've tired running notebooks of around 200-300 cells and navigating the cells in both edge or command mode using the arrows, but the rendering order of the cells doesn't seem to change. I've also tried selecting cells or their outputs and moving them in and out of view, same results. In all cases, I have change the settings to `full` windowing mode, and I am using version `4.1.0b0`.

Is there anything more you have done or noticed when encountering this issue? @krassowski

**Comment by krassowski** [comment]
I will try to reproduce again tomorrow morning. I suspect a combination of cutting/pasting cells or maybe changing their types when the active cell is out of view could be the key.

**Comment by krassowski** [comment]
I put quite some effort into reproducing it but I could not find any sequence to reproduce it in a clean environment (but I had seen it a few times since reporting it initially in my work environment which has a number of extensions and often complex workspaces making my computer slow down significantly).

**Comment by krassowski** [comment]
This is how the DOM looks like when it happens:

![Screenshot from 2023-12-25 21-30-43](https://github.com/jupyterlab/jupyterlab/assets/5832902/e72f896f-9150-4584-84e2-a61754ef56d8)

Notice two code cells with 262 index with a markdown cell with index 261 in between

**Comment by krassowski** [comment]
We discussed this on the weekly JuypterLab call today: we will still attempt to fix it before the final release, but it is not deemed blocking because it happens in the windowing mode which is not used by default; instead we will add a recommendation in the release notes for users who use the `full` windowing mode to either postpone upgrading to 4.1 or help with testing that mode in the new version (thanks @jtpio for the suggestion!)

**Comment by JasonWeill** [comment]
Closing per #16013.
