### ISSUE TITLE
Tab close warning shown unconditionally

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#1563]
When the user tries to close the lab tab, right now lab unconditionally shows a dialog warning about unsaved data, regardless whether there is any unsaved data. Observed on 0.14.0, chrome and firefox.

**Comment by blink1073** [comment]
Yep, we need a mechanism for plugins to indicate whether they have "dirty" content so we know whether to show this warning.

**Comment by blink1073** [comment]
Fixed by #2766.
