### ISSUE TITLE
When using find and replace, the next string is selected, but the previous is replaced

### ISSUE THREAD

**Issue by speleos** [jupyterlab/jupyterlab#15657]
## Description
When I use find and replace, as one string is replaced, the next occurrence is highlighted.
However, if I press replace again, the previous occurrence is replaced, not the one highlighted.

I've confirmed this issue with a clean install and in incognito mode on chrome.

## Reproduce

Open "Find and replace".
Type the string to be found.
Type the replacement string.
Use the up and down buttons to select the first occurrence you want to replace.
Press replace. The string is replaced as expected and the highlight moves to the next occurence.
Press replace again. The highlight moves again, but the replaced occurrence is the one **before** the first replacement.
This will happen every time I press replace.

![image](https://github.com/jupyterlab/jupyterlab/assets/43036625/ea18e722-75ab-4534-8cc2-03fae35264e0)

## Expected behavior

The highlighted string is replaced.

## Context
- Operating System and version: Linux Ubuntu 20.04
- Browser and version: Chrome 120
- JupyterLab version: 4.0.7

**Comment by JasonWeill** [comment]
#15572 concerns a similar issue when the 'find' string is a substring of the 'replace' string, but this is a different issue. @speleos thanks for opening this!

**Comment by krassowski** [comment]
Related to https://github.com/jupyterlab/jupyterlab/issues/13968

**Comment by JasonWeill** [comment]
Reproduced this with Lab 4.1.1.

**Comment by JasonWeill** [comment]
@krassowski I started working on this issue yesterday afternoon.
