### ISSUE TITLE
Jupyter Extension Simultaneously Installed and Enabled But Not Working

### ISSUE THREAD

**Issue by Padamire** [jupyterlab/jupyterlab#15658]
Hey Guys

I've recently ran into an issue with a Jupyter Lab Extension (Jupyter Scheduler). I've tried installing it with 'mamba install', 'pip install' and through Pypi on the Lab Extension section, all of which require the simultaneous installation of croniter, pytz, fsspec and sqlachlemy. However, when that's complete, I get the following popup on Jupyter Lab.

![image](https://github.com/jupyterlab/jupyterlab/assets/105001309/36c4dd76-8399-451d-846c-55f91259960c)

I've followed the instructions, installing the server extension through either command prompt or anaconda prompt (which always states the requirement has already been satisified). A quick run of 'mamba list' shows that jupyter scheduler is installed at v 2.4.0. When I run Jupyter Server Extension List, I get the following output:

![image](https://github.com/jupyterlab/jupyterlab/assets/105001309/a26d5b48-0817-4441-8c16-5d7afbda9d6d)

It shows that the extension is installed and enabled. The issue mimics a similar GitHub Issue: https://github.com/jupyterlab/jupyterlab/issues/8122. However, the main solution is to delete the build-config.json file in the settings folder of Jupyter Lab, but mine remains empty.

The only discrepancy I can think of is in Jupyter Labs Extension Manager, where Jupyter_Scheduler is shown both to be installed and not installed at the same time:
![image](https://github.com/jupyterlab/jupyterlab/assets/105001309/6e79b75b-70c2-472c-8f72-6aad7c79e712)
![image](https://github.com/jupyterlab/jupyterlab/assets/105001309/c11f571b-ef29-4854-985f-90571f787951)
However, when I try to install the uninstalled version, I get a notification saying to refresh the page to apply the changes, but when I do that nothing happens.

I've run Jupyter Lab Build, updated Jupyter Lab to 4.0.8, tried every workaround but nothing seems to work.

I would really appreciate some help on this as I've already burned countless hours trying to fix it.

**Comment by krassowski** [comment]
@Padamire there are two separate extensions: [jupyter-scheduler](https://github.com/jupyter-server/jupyter-scheduler) maintained within official jupyter-server organization and a third-party [jupyter**lab**-scheduler](https://github.com/tiburon-security/jupyterlab_scheduler). I do not know which one you intended to install, but probably not both. Beside this confusion your issue is most likely either (a) that the extension was installed in a different virtual environment or (b) that you need to restart jupyterlab for server to pickup the newly installed extension.

**Comment by Padamire** [comment]
@krassowski I've restarted Jupyterlab multiple times (closing anaconda navigator, opening it again and launching the app) but I always get the same popup. I've even uninstalled and reinstalled Jupyterlab but got no results. 

I checked which environment I was working in and it confirmed I was in the base environment

![image](https://github.com/jupyterlab/jupyterlab/assets/105001309/cdf68408-6156-489a-8c3e-446694e48572)

After running mamba list on that specific environment, it confirmed that jupyter_scheduler was installed.

![image](https://github.com/jupyterlab/jupyterlab/assets/105001309/9d9e8d66-732b-4821-a363-029cf13f4778)

![image](https://github.com/jupyterlab/jupyterlab/assets/105001309/b274252f-94e7-447b-8868-6ba3ed448f96)

So I'm not quite sure what the issue is. The only discrepancy I can note (if it is one at all) is that the scheduler extension always seems to be found in two separate directories: 
![image](https://github.com/jupyterlab/jupyterlab/assets/105001309/515ad1ba-4705-4af7-8ad1-9d4de1c72930)
Here it's found in the .jupyter folder.

![image](https://github.com/jupyterlab/jupyterlab/assets/105001309/563e1050-f4e9-44fb-81a2-952f445af6ab)

and here it is in the anaconda3/etc/jupyter folder. This may just be normal practice but it may provide a clue to the issue at hand.

**Comment by JasonWeill** [comment]
Let's keep the conversation going about this in https://github.com/jupyter-server/jupyter-scheduler/issues/473, which you also opened. This seems to be an issue with installing Jupyter Scheduler, not in JupyterLab's handling of extensions.
