### ISSUE TITLE
4.1 Beta - Jupyter Labs Failed To Start in Clean Conda Environment on Windows 10 Pro

### ISSUE THREAD

**Issue by marcusobrien** [jupyterlab/jupyterlab#15675]
## Description
Executing the new 4.1 Jupyter Labs Beta in a clean new Conda environment fails. 

My other conda environments work fine, in both command line and with the existing jupyter labs - so the problem hasn't showed itself on any other, existing environments (so not a system issue).

I run this command to start labs
**U:\Miniconda3\condabin\conda.BAT activate CONDA_TEST_LABS**
**jupyter_lab** 

See the crash/traceback below for the output

## Reproduce

Create a new conda environment with this in Windows 10

call conda create -n %1 python=3.6 --yes
call conda activate %1
call conda install -c conda-forge tensorflow --yes
call conda install statsmodels --yes
call conda install tensorflow-hub --yes
call conda install matplotlib --yes
call conda install scikit-learn --yes
call conda install pandas-datareader --yes
call conda install -c conda-forge/label/jupyterlab_beta -c conda-forge jupyterlab --yes
call conda install yfinance --yes

Activate the conda env
**U:\Miniconda3\condabin\conda.BAT activate CONDA_TEST_LABS**

Run jupyter-lab
**jupyter_lab** 

Stack trace - failed to startup.

## Expected behavior

Browser page load without any exception, and see JL running in browser.

## Context

- Operating System and version: Windows Pro 10
- Browser and version: MS Edge Version 120.0.2210.133 (Official build) (64-bit)
- JupyterLab version: 4.1 Beta

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>

$PATH:
  2     U:\Miniconda3\envs\CONDA_TEST_LABS
  3     U:\Miniconda3\envs\CONDA_TEST_LABS\Library\mingw-w64\bin
  4     U:\Miniconda3\envs\CONDA_TEST_LABS\Library\usr\bin
  5     U:\Miniconda3\envs\CONDA_TEST_LABS\Library\bin
  6     U:\Miniconda3\envs\CONDA_TEST_LABS\Scripts
  7     U:\Miniconda3\envs\CONDA_TEST_LABS\bin
  8     U:\Miniconda3\condabin

I redacted the rest

sys.path:
    U:\Miniconda3\envs\CONDA_TEST_LABS\Scripts
    U:\Miniconda3\envs\CONDA_TEST_LABS\python36.zip
    U:\Miniconda3\envs\CONDA_TEST_LABS\DLLs
    U:\Miniconda3\envs\CONDA_TEST_LABS\lib
    U:\Miniconda3\envs\CONDA_TEST_LABS
    U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages
    U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\frozendict-2.3.0-py3.10.egg
    U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\win32
    U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\win32\lib
    U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\Pythonwin

sys.executable:
    U:\Miniconda3\envs\CONDA_TEST_LABS\python.exe

sys.version:
    3.6.15 (default, Dec  3 2021, 18:25:24) [MSC v.1916 64 bit (AMD64)]

platform.platform():
    Windows-10-10.0.19041-SP0

where jupyter:
    U:\Miniconda3\envs\CONDA_TEST_LABS\Scripts\jupyter.exe

pip list:
    Package                       Version^M
    ----------------------------- ------------^M
    absl-py                       2.0.0^M
    anyio                         3.3.2^M
    appdirs                       1.4.4^M
    argon2-cffi                   21.1.0^M
    astor                         0.8.1^M
    async-generator               1.10^M
    attrs                         22.2.0^M
    Babel                         2.11.0^M
    backcall                      0.2.0^M
    backports.functools-lru-cache 2.0.0^M
    beautifulsoup4                4.12.3^M
    bleach                        6.1.0^M
    brotlipy                      0.7.0^M
    cached-property               1.5.2^M
    certifi                       2021.5.30^M
    cffi                          1.14.6^M
    charset-normalizer            2.1.1^M
    colorama                      0.4.5^M
    contextvars                   2.4^M
    cryptography                  35.0.0^M
    cycler                        0.11.0^M
    dataclasses                   0.8^M
    decorator                     5.1.1^M
    defusedxml                    0.7.1^M
    entrypoints                   0.4^M
    frozendict                    2.3.0^M
    gast                          0.5.4^M
    google-pasta                  0.2.0^M
    grpcio                        1.38.1^M
    h5py                          3.1.0^M
    html5lib                      1.1^M
    idna                          3.6^M
    immutables                    0.16^M
    importlib-metadata            4.8.1^M
    ipykernel                     5.5.5^M
    ipython                       7.16.1^M
ipython-genutils              0.2.0^M
    jedi                          0.17.2^M
    Jinja2                        3.0.3^M
    joblib                        1.2.0^M
    json5                         0.9.5^M
    jsonschema                    4.1.2^M
    jupyter-client                7.1.2^M
    jupyter-core                  4.8.1^M
    jupyter-server                1.13.2^M
    jupyterlab                    3.3.0b0^M
    jupyterlab-pygments           0.1.2^M
    jupyterlab-server             2.10.3^M
    Keras-Applications            1.0.8^M
    Keras-Preprocessing           1.1.2^M
    kiwisolver                    1.3.1^M
    lxml                          4.6.3^M
    Markdown                      3.5.2^M
    MarkupSafe                    2.0.1^M
    matplotlib                    3.3.4^M
    mistune                       0.8.4^M
    multitasking                  0.0.9^M
    nbclassic                     0.3.5^M
    nbclient                      0.5.9^M
    nbconvert                     6.0.7^M
    nbformat                      5.1.3^M
    nest_asyncio                  1.5.9^M
    notebook                      6.3.0^M
    numpy                         1.19.5^M
    olefile                       0.46^M
    packaging                     21.3^M
    pandas                        1.1.5^M
    pandas-datareader             0.10.0^M
    pandocfilters                 1.5.0^M
    parso                         0.7.1^M
    patsy                         0.5.6^M
    pickleshare                   0.7.5^M
    Pillow                        8.3.2^M
    pip                           21.3.1^M
    prometheus-client             0.17.1^M
    prompt-toolkit                3.0.36^M
    protobuf                      3.18.0^M
    pycparser                     2.21^M
    Pygments                      2.14.0^M
    pyOpenSSL                     22.0.0^M
    pyparsing                     3.1.1^M
    PyQt5                         5.12.3^M
    PyQt5_sip                     4.19.18^M
    PyQtChart                     5.12^M
    PyQtWebEngine                 5.12.1^M
    pyreadline                    2.1^M
    pyrsistent                    0.17.3^M
    PySocks                       1.7.1^M
    python-dateutil               2.8.2^M
    pytz                          2023.3.post1^M
    pywin32                       301^M
    pywinpty                      1.1.4^M
    pyzmq                         22.3.0^M
    requests                      2.28.1^M
    scikit-learn                  0.24.2^M
    scipy                         1.5.3^M
    Send2Trash                    1.8.2^M
    setuptools                    58.0.4^M
    six                           1.16.0^M
    sniffio                       1.2.0^M
    soupsieve                     2.3.2.post1^M
    statsmodels                   0.12.2^M
    tensorboard                   1.14.0^M
    tensorflow                    1.14.0^M
    tensorflow-estimator          1.14.0^M
 tensorflow-hub                0.12.0^M
    termcolor                     1.1.0^M
    terminado                     0.12.1^M
    testpath                      0.6.0^M
    threadpoolctl                 3.1.0^M
    tornado                       6.1^M
    traitlets                     4.3.3^M
    typing_extensions             4.1.1^M
    urllib3                       1.26.15^M
    wcwidth                       0.2.10^M
    webencodings                  0.5.1^M
    websocket-client              1.3.1^M
    Werkzeug                      2.0.2^M
    wheel                         0.37.1^M
    win-inet-pton                 1.1.0^M
    wrapt                         1.13.1^M
    yfinance                      0.2.18^M
    zipp                          3.6.0

</details>

<details><summary>Command Line Output</summary>
<pre>
Starts the CONDA_TEST_LABS Conda Env with Labs
Start the passed in folder D:\mldev\experiment\ml_stockmarket
Traceback (most recent call last):
  File "U:\Miniconda3\envs\CONDA_TEST_LABS\Scripts\jupyter-lab-script.py", line 5, in <module>
    from jupyterlab.labapp import main
  File "U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\jupyterlab\labapp.py", line 13, in <module>
    from jupyter_server.serverapp import flags
  File "U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\jupyter_server\serverapp.py", line 83, in <module>
    from jupyter_server.services.sessions.sessionmanager import SessionManager
  File "U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\jupyter_server\services\sessions\sessionmanager.py", line 22, in <module>
    from jupyter_server.traittypes import InstanceFromClasses
  File "U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\jupyter_server\traittypes.py", line 7, in <module>
    from traitlets.utils.descriptions import describe
ModuleNotFoundError: No module named 'traitlets.utils.descriptions'

</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by marcusobrien** [comment]
Actually I did find something on this ticket for this same symptom (not sure if same root cause)
https://github.com/jupyterlab/jupyterlab/issues/12094

Anyway it led to this commit, to rpevent the Jupyter labs being installed with 3.6 in the first place - seems its not compat with python 3.6 ? 
https://github.com/AlgoCompSynth/AlgoCompSynth-One/commit/3f335e4e02d7ae6dc6a1227b28b80458bcb719db

**Comment by krassowski** [comment]
Thank you for opening the issue. Indeed, JupyterLab 4.0 requires Python 3.8 or newer:

https://github.com/jupyterlab/jupyterlab/blob/18b83678695a9b66cb25adf495c441e7704aee77/pyproject.toml#L13

I am not sure why conda let you install it, maybe there is a packaging mistake to be rectified.

**Comment by krassowski** [comment]
For visibility;

```
Starts the CONDA_TEST_LABS Conda Env with Labs
Start the passed in folder D:\mldev\experiment\ml_stockmarket
Traceback (most recent call last):
  File "U:\Miniconda3\envs\CONDA_TEST_LABS\Scripts\jupyter-lab-script.py", line 5, in 
    from jupyterlab.labapp import main
  File "U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\jupyterlab\labapp.py", line 13, in 
    from jupyter_server.serverapp import flags
  File "U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\jupyter_server\serverapp.py", line 83, in 
    from jupyter_server.services.sessions.sessionmanager import SessionManager
  File "U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\jupyter_server\services\sessions\sessionmanager.py", line 22, in 
    from jupyter_server.traittypes import InstanceFromClasses
  File "U:\Miniconda3\envs\CONDA_TEST_LABS\lib\site-packages\jupyter_server\traittypes.py", line 7, in 
    from traitlets.utils.descriptions import describe
ModuleNotFoundError: No module named 'traitlets.utils.descriptions'
```

The commit that you are referencing is relevant because it pins jupyter-server (from which this issue originates) to older version v1 (rather than v2). However, JupyterLab 4+ itself do not support Python 3.6 either (as mentioned above), so it may not work even with the older server version.

**Comment by krassowski** [comment]
Our 4.x beta recipe for conda-forge doe require Python 3.8 (see [here](https://github.com/conda-forge/jupyterlab-feedstock/blob/c1f2ea9b148562f4eb437f7ab67ecb6a10e3a91e/recipe/meta.yaml#L41)) so I am not sure if there is anything we can (or should do).

**Comment by JasonWeill** [comment]
Python 3.6 has reached end of life, so it's not supported by new JupyterLab versions anymore. Please upgrade to Python 3.8 or newer to use these newer versions. Thanks!
