### ISSUE TITLE
Resizing notebook panel affects the order of icons in the toolbar

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15676]
## Description
Resizing the notebook panel affects the order of icons in the toolbar. Here's an example - 

![resize](https://github.com/jupyterlab/jupyterlab/assets/30082866/f1894494-b364-42fe-b5be-01ccc3a4f940)

## Reproduce

Follow the steps in the above gif.

## Expected behavior

The kernel should remain right aligned.

## Context

JupyterLab version: 4.1.0b2

**Comment by krassowski** [comment]
I can reproduce this when having buttons contributed by extensions (with native buttons only it seems less common occurrence):

![reprod](https://github.com/jupyterlab/jupyterlab/assets/5832902/6e5f45e1-a201-4b8c-8a53-9ad31d59f6c4)

CC @brichet

**Comment by JasonWeill** [comment]
We saw this previously in #15509, which was closed, but this seems to be a regression now.
