### ISSUE TITLE
Cell toolbar gets stuck when using collapse cell feature

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15671]
## Description

Cell toolbar does not hide when switching away after using collapse cell feature

## Reproduce

1. Click on cell collapser
2. Switch to another cell
3. Uncollapse the collapsed cell
4. Switch to another cell
5. See the cell toolbar remains stuck

(Ignore notebook name on the gif, happens with both modes)

![toolbar-gets-stuck](https://github.com/jupyterlab/jupyterlab/assets/5832902/895b4b03-8ff5-430b-b45d-9f0565c483b8)

## Expected behavior

Cell toolbar gets hidden

## Context

- Browser and version: tested on Chromium but probably all
- JupyterLab version: 4.0.9, 4.1.0b2 and all in between; works well in 4.0.8 and 3.6.x

Likely introduced by https://github.com/jupyterlab/jupyterlab/pull/15314 ?

No errors in the console.

**Comment by FoSuCloud** [comment]
I want to try to solve this problem
