### ISSUE TITLE
Keyboard shortcuts settings page breaks on search

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15687]
## Description
Searching anything in the keyboard shortcuts settings page doesn't work. Here's a gif - 

![settings](https://github.com/jupyterlab/jupyterlab/assets/30082866/0bc8db4a-2636-4c7f-a724-150926f026b0)

## Reproduce

Go to the keyboard shortcuts settings page and search something.

**Comment by krassowski** [comment]
Thank you for the report @divyansshhh. What browser are you using? Is there an error log in the JS console? I cannot reproduce this in a clean install on Chrome:

![cannot-repro-chrome](https://github.com/jupyterlab/jupyterlab/assets/5832902/957b414f-417f-44af-869a-dfb6c6234464)

Nor on Firefox:

![cannot-repro-firefox](https://github.com/jupyterlab/jupyterlab/assets/5832902/4b5edc84-0a16-46de-aafa-d3741c891c50)

I suspect that this might be coming from an extension or some specific shortcuts configuration - can you share the list of these?

**Comment by krassowski** [comment]
Also, does it happen with a specific key or any?

For completeness, from the list of shortcuts on screencast and other reports I infer this is 4.1.0b2.

**Comment by divyansshhh** [comment]
This is because of - https://github.com/jupyterlab-contrib/jupyterlab-vim/blob/main/schema/plugin.json#L141.
