### ISSUE TITLE
colored HTML text black in light theme

### ISSUE THREAD

**Issue by jgunstone** [jupyterlab/jupyterlab#15683]
...  but correctly colored in dark theme

## Description

colored HTML text black in light theme but correctly colored in dark theme

light
![image](https://github.com/jupyterlab/jupyterlab/assets/21370980/f0a51a09-d2d5-4558-9044-1b94aedad4db)

dark
![image](https://github.com/jupyterlab/jupyterlab/assets/21370980/045211a1-4253-4843-a285-e886a5ae5a88)

## Reproduce

run
```py
from IPython.display import HTML
import ipywidgets as w
html = '<b>LT-1E</b> - <i><FONT COLOR="#00054A">[abbreviation]<FONT COLOR="</FONT>">-<FONT COLOR="#143277">[type_reference]<FONT COLOR="</FONT>"><FONT COLOR="#2F5A96">[function_reference]<FONT COLOR="</FONT>"></i>'
display(HTML(html))
display(w.HTML(html))
```

## Expected behavior

html text correctly colored in both themes

## Context

- Linux Ubuntu 22.04 
- Browser and version: Version 120.0.6099.225 (Official Build) (64-bit)
- JupyterLab version: 4.0.11

**Comment by krassowski** [comment]
It looks correctly coloured in both light and dark theme to me. `<FONT COLOR="</FONT>">` is invalid syntax, so this may not be the best example, but it would not matter. Maybe you need to change colours for more contrastive?

**Comment by JasonWeill** [comment]
Do you still see this behavior when using modern HTML5 syntax, such as `<span style="color: #abc123">foo</span>`?

**Comment by jgunstone** [comment]
hi both, 

the HTML5 syntax does work, and testing on a different screen the colors are clearer in light mode. 
thanks for your help
![image](https://github.com/jupyterlab/jupyterlab/assets/21370980/fbed1a44-414b-41cb-8706-cf3aaa32f075)
