### ISSUE TITLE
Search highlights don't get removed when removing the search query

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15688]
## Description
The search queries remain highlighted after removing the search query. Here's a gif - 
![search](https://github.com/jupyterlab/jupyterlab/assets/30082866/301e6371-0647-4efa-905e-a99bfae4d57c)

## Context

- JupyterLab version: 4.1.0b2

**Comment by krassowski** [comment]
I can reproduce this, thank you!

**Comment by krassowski** [comment]
Notes: It works in 3.6.x but not in 4.0.10; it works when closing the searchbox using <kbd>Esc</kbd> but not when removing text
