### ISSUE TITLE
Visual Regression Documentation tests action uses Node.js 16, which is deprecated

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#15698]
## Description

In the run details for visual regression tests, I see an error:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4, actions/cache@v3, actions/setup-node@v3, ifaxity/wait-on-action@v1, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

## Expected behavior

We need to upgrade these actions to Node 20, which is still supported until late 2024, with maintenance continuing until Q2 2026. NodeJS [ended support on September 11, 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol/).

**Comment by krassowski** [comment]
I the above is referring to `4.0.x` branch; on `main` there is only one of these (`ifaxity/wait-on-action@v1`):

> The following actions uses node12 which is deprecated and will be forced to run on node16: ifaxity/wait-on-action@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Of note there might be even older versions on 3.6.x branch.

**Comment by krassowski** [comment]
Depends on https://github.com/iFaxity/wait-on-action/issues/12

**Comment by krassowski** [comment]
A few remain:

> actions/setup-python@v4, actions/cache@v3, actions/setup-node@v3

but these are not defined in https://github.com/jupyterlab/jupyterlab/blob/main/.github/workflows/galata.yml but from dependencies too.

**Comment by krassowski** [comment]
Will be fixed by https://github.com/jupyterlab/maintainer-tools/pull/235
