### ISSUE TITLE
Markdown table with empty cell not rendering

### ISSUE THREAD

**Issue by devmcp** [jupyterlab/jupyterlab#15696]
## Description

Markdown tables are not rendered at all if they contain an empty cell.

## Reproduce

This in a markdown cell renders correctly:

```
| a | b | c |
|---|---|---|
| 1 | 2 | 3 |
```

This when rendered displays nothing:

```
| a | b | c |
|---|---|---|
| 1 | 2 |   |
```

## Expected behavior

The table renders with an empty cell.

## Context

- Operating System and version: Windows 11
- Browser and version: Chrome 117
- JupyterLab version: 4.0.11

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
I just tried to reproduce this in JupyterLab 4.0.11 and I see the table render with and without the empty cell, including when an empty cell is in the middle of a row:

![image](https://github.com/jupyterlab/jupyterlab/assets/93281816/858f919f-ae03-4ffc-bb38-30b1f9d96c4f)

**Comment by devmcp** [comment]
Hmm. I'm unable to reproduce it in another of my other Python environments also. I wonder if it could be caused by one of the extensions I have?

I'll do a bit more digging.
