### ISSUE TITLE
Issues renaming notebooks

### ISSUE THREAD

**Issue by o2carr68** [jupyterlab/jupyterlab#1570]
First things first: thanks for your awesome work!

My apologies if this has been reported before.  I run into the
following issues involving notebook renaming (see the attached gif):

1. When a notebook is created with a given name (FirstName.ipynb) the
   filemanager doesn't update that info and continues showing the
   initial default name (Untitled.ipynb).

2. Renaming the notebook (FirstName.ipynb -> SecondName.ipynb) does
   not update the name shown in the notebook tab nor in the tooltip
   shown when the mouse pointer hovers over the tab.

3. Saving the notebook generates a new notebook with the old name
   (FirstName.ipynb) as shown by refreshing the file list. It seems
   that both notebooks (FirstName.ipynb) and (SecondName.ipynb) share
   the same kernel. Both notebooks seem to be running but note that
   the icon of FirstName.ipynb is not shown in green.

![jl_renamefile](https://cloud.githubusercontent.com/assets/24479423/22385408/c9d1fe2a-e4d2-11e6-9271-2357c3486592.gif)
.

**Comment by blink1073** [comment]
Hi @o2carr68, thank you for the detailed report.

**Comment by hadim** [comment]
I confirm this bug.
