### ISSUE TITLE
Docker run fails to build image

### ISSUE THREAD

**Issue by ryanswilson59** [jupyterlab/jupyterlab#15709]
## Description
I run `docker/starth.sh dev` as suggest in the docks I get the following error
`COPY failed: forbidden path outside the build context: ../binder/environment.yml ()`

## Reproduce
Theoretically the description is enough, its probably some config error. 

## Expected behavior
The image builds and runs

## Context
Operating system: Manjaro linux
Docker Version: 24.0.7
Jupyter Lab commit hash: 558c60f069a33201ab7b2ba

**Comment by trungleduc** [comment]
Hi, could you retry with this PR https://github.com/jupyterlab/jupyterlab/pull/15699 ?

**Comment by ryanswilson59** [comment]
That fixed the `yml` issue, I now get 
```
Cleaning tarballs..
Cleaning packages..
Removing intermediate container b60ec830da29
 ---> 6b8047a7935c
Step 16/21 : COPY --chown=$MAMBA_USER:$MAMBA_USER . .
 ---> 645bc5b944ae
Step 17/21 : RUN micromamba run jlpm install
 ---> Running in 286be2b80c43
Success
The command '/usr/local/bin/_dockerfile_shell.sh micromamba run jlpm install' returned a non-zero code: 1
```

**Comment by trungleduc** [comment]
Thanks for trying it out, it should be fixed with the last commit
