### ISSUE TITLE
Bugs with Mermaid support

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#15726]
I'm testing the new Mermaid fenced-blocks on 4.1.0rc0 and have observed some issues:

- [ ] After an error the error output doesn't clear when you do "Clear Cell Output" or "Restart Kernel and Clear Outputs of All Cells"
- [ ] After an error, the content of the cell doesn't (necessarily?) reflect what you see in JupyterLab - i.e. the error text seems to hang around even though you can no longer see it in the JupyterLab UI

NB: I'm accessing a JupyterLab instance running on an Ubuntu VM via SSH from a Windows VDI.

**Comment by dhirschfeld** [comment]
what I'm observing seems related to:
- https://github.com/jupyterlab/jupyterlab/issues/15660

**Comment by bollwyvl** [comment]
Concrete screenshots, and, ideally, a reproducer notebook gist would be helpful.

**Comment by dhirschfeld** [comment]
Only enough time to post. Will try to create a reproducer this weekend...

**Comment by dhirschfeld** [comment]
After a sleep / reboot I can't seem to reproduce what I was seeing :/

**Comment by dhirschfeld** [comment]
PEBCAK
