### ISSUE TITLE
Add `display_mermaid` function

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#15725]
### Problem

I'm testing the new Mermaid fenced-blocks on 4.1.0rc0 and it's pretty great! :heart::rocket:

What I'd like to do is to display programmatically generated Mermaid  diagrams in JupyterLab.

In the same way I can pass an HTML string to `display_html` and have it be rendered, I'd like to be able to pass a string representing a Mermaid diagram to `display_mermaid` and have it be rendered.

### Proposed Solution

Add a `display_mermaid(diagram: str)` function which rendered the provided `diagram` as a Mermaid diagram

### Additional context

All the `display_*` functions are in `IPython.display` so if the IPython repo is a better location for this I'm happy to transfer it there.

I opened it here as I suspect the `display` function (potentially `display.DisplayObject` class) might need support in JupyterLab to work properly.

**Comment by krassowski** [comment]
Sounds like a good idea, though yes, this is very much IPython enhancement request. Feel free to open a PR against IPython and I will happily review it.

**Comment by afonit** [comment]
@dhirschfeld,
I noticed this had not been created yet in the ipython issue tracker, so I went ahead and setup an issue to get the ball rolling:
https://github.com/ipython/ipython/issues/14319

**Comment by JasonWeill** [comment]
Closing in favor of https://github.com/ipython/ipython/issues/14319.
