### ISSUE TITLE
Menu button `Console > Switch Kernel` produces nothing

### ISSUE THREAD

**Issue by hadim** [jupyterlab/jupyterlab#1573]
Tested on v0.14 and also last master commit of today.

I am using an updated Anaconda distribution.

**Comment by hadim** [comment]
I see no error in the terminal running Jupyter as well as in the JS browser console. I use chromium.

**Comment by blink1073** [comment]
As in, the select kernel dialog does not pop up?

**Comment by hadim** [comment]
Exactly. Nothing happen.

**Comment by blink1073** [comment]
Do any of the other commands in the Console menu work?

**Comment by hadim** [comment]
Only `Start a New Console` works. All the other commands produce nothing.

**Comment by blink1073** [comment]
Does the console tab have a blue border at the top?

![image](https://cloud.githubusercontent.com/assets/2096628/22397743/174be434-e53e-11e6-9652-9924df0733f4.png)

**Comment by hadim** [comment]
Yes.

**Comment by jasongrout** [comment]
It works for me on master, FYI. Can you try in incognito mode? If that doesn't work, can you try cleaning out all extra files (`git clean -dfx` from the jupyterlab repo root, which will delete all files not in the repo), pull fresh from master, and `pip install -e` again?

**Comment by hadim** [comment]
Nothing of the above work for me...

**Comment by blink1073** [comment]
Which OS and browser?

**Comment by hadim** [comment]
Linux Mint and Chromium 56 (also tested with Firefox).

```
 $ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.2
         python version : 3.5.3.final.0
       requests version : 2.12.5
       root environment : /home/hadim/local/conda  (writable)
    default environment : /home/hadim/local/conda/envs/test
       envs directories : /home/hadim/local/conda/envs
          package cache : /home/hadim/local/conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/hadim/.condarc
           offline mode : False
```

Tested on both Python 3.5 and 3.6.

**Comment by blink1073** [comment]
I just tried on Ubuntu with Chrome and Firefox and it is working.    You can try and debug by opening `main.bundle.js` in `Sources`, searching for "index_1.CommandIDs.switchKernel", and setting a debug point here:

![image](https://cloud.githubusercontent.com/assets/2096628/22399143/72228412-e55c-11e6-8873-042afe8d331e.png)

Then, run `Console -> Switch Kernel`.  That point should be hit and the `current` variable should be set.

**Comment by hadim** [comment]
The point is hit and `current` is set to `null`.

**Comment by hadim** [comment]
(using jupyterlab on master at the moment)

**Comment by blink1073** [comment]
What is the value of `tracker.size` in the console at that breakpoint?

**Comment by hadim** [comment]
0

**Comment by blink1073** [comment]
Searching for "Add the console panel to the tracker", and setting a breakpoint here, does this point get hit when you create a new console?

![image](https://cloud.githubusercontent.com/assets/2096628/22399210/a3f06134-e55d-11e6-8f74-b5a226b6e6c8.png)

**Comment by hadim** [comment]
Yes after I click on "Select". Then a new console tab is created.

**Comment by hadim** [comment]
But this command does not require a non null `tracker.currentWidget` that is why it's working and not the other one I guess (because they need `current` to be set).

**Comment by blink1073** [comment]
Does the string "add the console panel to the tracker" appear more than once in your bundle?

**Comment by hadim** [comment]
Nope

**Comment by blink1073** [comment]
Wowzers, I am really confused.  We add the console to the tracker, and it gets focus, which means `tracker.size` should be > 0 and `tracker.currentWidget` should have gotten set.  The only time it should get removed is when the widget it closed (you hit the "X" in the dock panel).

**Comment by blink1073** [comment]
@afshin, any thoughts on what could be causing this?

**Comment by hadim** [comment]
Oh I found something.

When I start a new console, go back to the notebook then the command works.

**Comment by hadim** [comment]
oh that is weird because the dialog window that open when I click with a notebook focused ask me to switch kernel for "Console 1" and not for the notebook.

**Comment by blink1073** [comment]
The console commands work on the "most recently used" console.  That still doesn't explain why it doesn't get set as the `currentWidget` immediately...

**Comment by hadim** [comment]
I am not sure it is useful but I found another `Switch Kernel` string far from the previous one : 

```
commands.addCommand(_1.CommandIDs.switchKernel, {
	        label: 'Switch Kernel',
	        execute: function () {
	            var current = tracker.currentWidget;
	            if (current) {
	                var context = current.context;
	                var node = current.node;
	                docregistry_1.selectKernelForContext(context, services.sessions, node).then(function () {
	                    current.activate();
	                });
	            }
	        }
	    });
```

**Comment by blink1073** [comment]
Yep, that one is specifically for notebooks.

**Comment by afshin** [comment]
Hm, I'll take a look!

**Comment by hadim** [comment]
I still have the issue with 0.15

**Comment by hadim** [comment]
I still have the issue with 0.16. Can someone reproduce the issue or am I alone ?

**Comment by blink1073** [comment]
Whoops, this should have been marked as beta, I can reproduce the problem.  Thanks for the heads up, @hadim!

**Comment by blink1073** [comment]
I spoke too soon.  I was able to reproduce only because I didn't have an active console open.

**Comment by hadim** [comment]
I also see the window with a console open.

**Comment by hadim** [comment]
Does someone is able to reproduce my bug ? If no one can, that is possibly a bug from my system ... but I have no clue why (all my Python code is running with Anaconda).

**Comment by thomasaarholt** [comment]
Yes. Running jupyterlab installed from conda here on Mac, happens on python 3.5 and 3.6.

**Comment by hadim** [comment]
I keep having the same error with last Jupyterlab release (0.18).

**Comment by blink1073** [comment]
Tried and failed again to reproduce with JupyterLab 0.18 on Ubuntu 16.04 with Firefox 51.0.1.  I tried opening a console, selecting a notebook, then refreshing the page, and then chose `Console -> Switch Kernel` from the menu.  I also tried with a fresh session and a console launched from the browser.  

@hadim, if you could make a screencast using something like [licecap](http://www.cockos.com/licecap/) that would be of great help. 

@thomasaarholt, `Enter` here acts like it does in the QtConsole, where it gives the kernel a chance to say whether the code is "complete" before sending the code for execution.  `Shift Enter` unambiguously sends the code for execution.

**Comment by hadim** [comment]
Thank you @blink1073 for looking into that. Here is the screencast.

![out-1](https://cloud.githubusercontent.com/assets/528003/24431033/b31f1278-13e7-11e7-932c-a7f52e59d270.gif)

Tell me if you need more information.

**Comment by blink1073** [comment]
@hadim, in the screencast you created a notebook instead of a console.  We should be disabling the console menu items when there are no consoles to avoid this confusion.

**Comment by hadim** [comment]
@blink1073 I think you are going to hate me :-)

I just discovered `Notebook > Switch Kernel`.... I don't know why but I was focusing so much on the `Console` menu that I thought it was the action for everything (python console and notebook).

Sorry for the noise !

As @thomasaarholt said, duplicate entries for the same action in `Console` and `Notebook` could be confusing for the user.

**Comment by hadim** [comment]
(and of course `Notebook > Switch Kernel` works like a charm)

**Comment by sccolbert** [comment]
Despite things technically working as designed, this is great feedback for us to improve our UX. Thanks @hadim and @thomasaarholt !
