### ISSUE TITLE
Cell outputs lost after splitting a cell

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15748]
## Description
Cell outputs are lost after a cell is split

## Reproduce
Write a multiline cell and split the cell using the context menu option

## Expected behavior
I would expect the cell outputs to be retained similar to lab3

## Context

- JupyterLab v4.1.0rc1

**Comment by krassowski** [comment]
This appears to be a regression introduced by removal of modeldb during RTC work https://github.com/jupyterlab/jupyterlab/pull/12695.
