### ISSUE TITLE
Shortcuts with same command but different arguments amiss in shortcuts UI

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15759]
## Description

> Are the 20 different bindings all for one action intended? Or a bug? (If not a bug: why has this behaviour been chosen??). Ok, I see from the json settings and the PR discussion that the different bindings are for selecting different objects in the sidebar — but I’ll note that this isn’t reflected at all in the GUI settings editor. 

_Originally posted by @defjaf in https://github.com/jupyterlab/jupyterlab/issues/15744#issuecomment-1930741245_

## Reproduce

1. Open "Settings Editor"
2. Choose "Keyboard shortcuts"
3. See that all 20 keybindings for "Show Left Activity Bar" are shown as a single shortcut, even though each of these has a different set of arguments
4. See that you cannot modify these shortcuts (edits are not saved)

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/e7700b1b-1006-4139-988c-bf2214ec6d54)

## Expected behavior

1. Shortcuts with different arguments are displayed separately
2. Shortcuts with different arguments can be modified independently
3. The arguments are displayed or even modifiable from shortcuts UI

## Context

- JupyterLab version: 4.1.0 but also affects other shortcuts with arguments in 4.0.x and possibly older

**Comment by defjaf** [comment]
(Thanks for translating my comment to a proper issue!)

**Comment by Lawiss** [comment]
It's annoying as the shortcut prevents me to type `[` as when I hit Maj+Option+5, it toggles the left Activity Bar instead.
I'm on jupyterlab version 4.1.0, python 3.11.5, MacOS 14.2.1.

**Comment by JasonWeill** [comment]
@Lawiss Which keyboard are you using? The issue with the `[` shortcut on an Italian keyboard was reported in #15744.

**Comment by Lawiss** [comment]
I use the French AZERTY (numerical) keyboard, I think this is the same issue than in https://github.com/jupyterlab/jupyterlab/issues/15744.

**Comment by Lawiss** [comment]
I tested with release 4.1.1 and the problem seems solved!
