### ISSUE TITLE
Use old Notebook meeting slot for open "Office Hours" with the community + each other (maintainers)

### ISSUE THREAD

**Issue by ericsnekbytes** [jupyterlab/jupyterlab#15766]
We should use the old Notebook meeting slot (830am PST every Wednesday) to host a weekly "Office Hours", where we can provide help and support for community members and each other (core devs/maintainers), and do other work that benefits the community.

Everyone (from Jupyter novice to core dev) should feel welcome and participate as they like: You can simply listen in and offer your expertise when it's relevant, bring a problem or PR with you for feedback, or bring some other tasks and questions to the table. Some examples of activities we can do in this meeting:

- I need PR feedback (as a core dev)
- There's a bug I'm struggling with (as a user) that prevents me from doing my work
- There's a release coming up, let's take some time to run and test it!
- I'm writing a Jupyter Extension, how do I add a button to the cell toolbar?

Many people are already going to be attending the Lab meeting just after this slot, which should make it easier for maintainers and users to join.

**Comment by jtpio** [comment]
Thanks @ericsnekbytes for opening the issue.

Maybe this could be moved to the team compass repo? https://github.com/jupyterlab/team-compass

For reference, there were some plans to do something like this for the Notebook 6 to 7 transition, although we never got to officially do it in the end: https://github.com/jupyter/notebook-team-compass/issues/13

**Comment by ericsnekbytes** [comment]
Thanks for sharing that, I'm moving/closing this issue and making [a new one over at the Lab Team Compass.](https://github.com/jupyterlab/team-compass/issues/237), continue reading there!

**Comment by jtpio** [comment]
Ah ok thanks, we could have used the "Transfer issue" button too:

![image](https://github.com/jupyterlab/jupyterlab/assets/591645/d32e2609-751c-4c67-85b7-79705f3bbc03)

**Comment by ericsnekbytes** [comment]
I didn't see the team compass repo in the list/search when I tried to transfer, maybe it's a permissions issue 🤷
