### ISSUE TITLE
Jupyter lab problem with inputing brackets German keyboard layout

### ISSUE THREAD

**Issue by hannovonbergen** [jupyterlab/jupyterlab#15778]
When trying to type "[", "]", "{", "}" in a jupyter lab environment with a german keyboard layout sometimes the character does not appear. 

This issue appears both in safari and in chrome. In safari it is possible to input one character from the "[]{}" set but no more while in chrome it is not possible to input any of these characters. 

This does not happen in version 3.6.3 but upgrading to version 4.1.0 caused this bug. I use macOS 13.4. 

This might be related to the problem discussed in issue 2379 of jupyter notebook, where some of the hotkeys used by jupyter notebook caused problems with keyboard layouts different from the English layout. Inputing "[" on a German keyboard with apple keyboard layout for example requires "option 5" which is a shortcut used by jupyter lab.

**Comment by jtpio** [comment]
Thanks @hannovonbergen for the report.

Looks like this may be the same issue as https://github.com/jupyterlab/jupyterlab/issues/15744? If so a fix has already been merged, but not yet released.

**Comment by hannovonbergen** [comment]
You are correct, thank you!
