### ISSUE TITLE
Pressing "Enter" in the console inserts two new lines

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15771]
## Description
Pressing "Enter" while in the console inserts two new lines in the input box. Here's a gif - 
![extra-new-line](https://github.com/jupyterlab/jupyterlab/assets/30082866/0248770c-b68e-4a88-a79e-4d4b36ad4987)

## Reproduce

Open the console, type something, press enter.

## Context

- JupyterLab v4.1.0rc1

**Comment by lstngr** [comment]
I had the same issue and I can confirm that resetting keyboard shortcuts resolved the issue for me (they were all showing up as “Custom” for some reason). Thank you @krassowski !

**Comment by divyansshhh** [comment]
> they were all showing up as “Custom” for some reason

I see this as well. Not sure why this happened.

> I had the same issue and I can confirm that resetting keyboard shortcuts resolved the issue for me

It resolved the issue for me too, surprisingly, copying all the shortcuts to custom doesn't reproduce this issue for me.

**Comment by krassowski** [comment]
One possibility is that this was fixed in 4.1.0beta1 by https://github.com/jupyterlab/jupyterlab/pull/15639 and only occurred for users who tried 4.1.0beta0 or earlier (or even some version of 4.0.x) but even after upgrading manual cleaning of user shortcuts was required.
