### ISSUE TITLE
Console input has unexpected undo behavior

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15773]
## Description
Pressing Ctrl+Z for undo in a console input block has unexpected undo behavior. Here's a gif - 
![weird-undo-bug](https://github.com/jupyterlab/jupyterlab/assets/30082866/bf6530b5-7388-4b0e-b331-0c9e8eed38af)

## Reproduce

Type something in the console input box and use Ctrl+Z for undo.

## Context

- JupyterLab version: 4.1.0rc1

**Comment by krassowski** [comment]
I can reproduce this in 4.1.0 and 4.0.12 but not in 3.6.7.

**Comment by krassowski** [comment]
Loosely related to undo not working at all in JSON Settings Editor: https://github.com/jupyterlab/jupyterlab/issues/15232 - in both cases `undoManager`/`ybindings` setup is either off or missing (e.g. something amiss with `sharedModel`).

**Comment by krassowski** [comment]
The problem is that `undo` from jupyter-ydoc is never invoked and yjs `undoManager` is not being used, despite tracking the changes. A PR is on the way.
