### ISSUE TITLE
Theme color is not applied to jp-button in 4.1.0

### ISSUE THREAD

**Issue by AllanChain** [jupyterlab/jupyterlab#15786]
## Description

After upgrading from v4.0.x to v4.1.0 (maybe related to #15021), the button style was changed. The color of the button is hard-coded as `var(--neutral-foreground-rest)`, and it takes precedence over the rule `.jp-Toolbar { var(--jp-ui-font-color1) }`.

As a result, for example in solarized dark theme, the button is in bright white instead of gray (like the debugger icon):

![image](https://github.com/jupyterlab/jupyterlab/assets/36528777/f3c448b0-c6ef-4ce8-bfcf-39e77d76bc51)

## Reproduce

1. Install JupyterLab v4.1.0
2. Install a JupyterLab theme, for example
    ```shell
	pip install jupyterlab_theme_solarized_dark
	```
3. Open a notebook, `Python 3 (ipykernel)` is bright white

## Expected behavior

The color of `Python 3 (ipykernel)` is gray

## Context

- Operating System and version: Linux EndeavourOS (Arch-based distro) 
- Browser and version: Firefox 122 
- JupyterLab version: 4.1.0 

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/ac/temp/.venv/bin
	/home/ac/.asdf/shims
	/home/ac/.asdf/bin
	/opt/android-sdk/tools/bin
	/home/ac/.local/share/pnpm
	/usr/local/sbin
	/usr/local/bin
	/usr/bin
	/home/ac/.local/bin
	/opt/android-sdk/platform-tools
	/opt/android-sdk/tools
	/usr/lib/jvm/default/bin
	/usr/bin/site_perl
	/usr/bin/vendor_perl
	/usr/bin/core_perl

sys.path:
	/home/ac/temp/.venv/bin
	/usr/lib/python311.zip
	/usr/lib/python3.11
	/usr/lib/python3.11/lib-dynload
	/home/ac/temp/.venv/lib/python3.11/site-packages

sys.executable:
	/home/ac/temp/.venv/bin/python

sys.version:
	3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801]

platform.platform():
	Linux-6.7.4-arch1-1-x86_64-with-glibc2.39

which -a jupyter:
	/home/ac/temp/.venv/bin/jupyter
	/usr/bin/jupyter
	/home/ac/Projects/GitHub/jupyterlab-wakatime/.venv/bin/jupyter

pip list:
	Package                         Version
	------------------------------- ---------------
	anyio                           4.2.0
	argon2-cffi                     23.1.0
	argon2-cffi-bindings            21.2.0
	arrow                           1.3.0
	asttokens                       2.4.1
	async-lru                       2.0.4
	attrs                           23.2.0
	Babel                           2.14.0
	beautifulsoup4                  4.12.3
	bleach                          6.1.0
	certifi                         2024.2.2
	cffi                            1.16.0
	charset-normalizer              3.3.2
	comm                            0.2.1
	debugpy                         1.8.1
	decorator                       5.1.1
	defusedxml                      0.7.1
	executing                       2.0.1
	fastjsonschema                  2.19.1
	fqdn                            1.5.1
	h11                             0.14.0
	httpcore                        1.0.2
	httpx                           0.26.0
	idna                            3.6
	ipykernel                       6.29.2
	ipython                         8.21.0
	isoduration                     20.11.0
	jedi                            0.19.1
	Jinja2                          3.1.3
	json5                           0.9.14
	jsonpointer                     2.4
	jsonschema                      4.21.1
	jsonschema-specifications       2023.12.1
	jupyter_client                  8.6.0
	jupyter_core                    5.7.1
	jupyter-events                  0.9.0
	jupyter-lsp                     2.2.2
	jupyter_server                  2.12.5
	jupyter_server_terminals        0.5.2
	jupyterlab                      4.1.0
	jupyterlab_pygments             0.3.0
	jupyterlab_server               2.25.2
	jupyterlab_theme_solarized_dark 3.0.1
	MarkupSafe                      2.1.5
	matplotlib-inline               0.1.6
	mistune                         3.0.2
	nbclient                        0.9.0
	nbconvert                       7.16.0
	nbformat                        5.9.2
	nest-asyncio                    1.6.0
	notebook_shim                   0.2.3
	overrides                       7.7.0
	packaging                       23.2
	pandocfilters                   1.5.1
	parso                           0.8.3
	pexpect                         4.9.0
	pip                             23.2.1
	platformdirs                    4.2.0
	prometheus-client               0.19.0
	prompt-toolkit                  3.0.43
	psutil                          5.9.8
	ptyprocess                      0.7.0
	pure-eval                       0.2.2
	pycparser                       2.21
	Pygments                        2.17.2
	python-dateutil                 2.8.2
	python-json-logger              2.0.7
	PyYAML                          6.0.1
	pyzmq                           25.1.2
	referencing                     0.33.0
	requests                        2.31.0
	rfc3339-validator               0.1.4
	rfc3986-validator               0.1.1
	rpds-py                         0.17.1
	Send2Trash                      1.8.2
	setuptools                      65.5.0
	six                             1.16.0
	sniffio                         1.3.0
	soupsieve                       2.5
	stack-data                      0.6.3
	terminado                       0.18.0
	theme-darcula                   4.0.0
	tinycss2                        1.2.1
	tornado                         6.4
	traitlets                       5.14.1
	types-python-dateutil           2.8.19.20240106
	uri-template                    1.3.0
	urllib3                         2.2.0
	wcwidth                         0.2.13
	webcolors                       1.13
	webencodings                    0.5.1
	websocket-client                1.7.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 2024-02-11 15:31:09.092 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-02-11 15:31:09.094 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-02-11 15:31:09.096 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-02-11 15:31:09.199 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-02-11 15:31:09.232 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-02-11 15:31:09.234 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-02-11 15:31:09.234 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-02-11 15:31:09.235 LabApp] JupyterLab extension loaded from /home/ac/temp/.venv/lib/python3.11/site-packages/jupyterlab
[I 2024-02-11 15:31:09.235 LabApp] JupyterLab application directory is /home/ac/temp/.venv/share/jupyter/lab
[I 2024-02-11 15:31:09.236 LabApp] Extension Manager is 'pypi'.
[I 2024-02-11 15:31:09.242 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-02-11 15:31:09.243 ServerApp] Serving notebooks from local directory: /home/ac/temp
[I 2024-02-11 15:31:09.243 ServerApp] Jupyter Server 2.12.5 is running at:
[I 2024-02-11 15:31:09.243 ServerApp] http://localhost:8888/lab?token=10921098ea6d04ed83967cdb22d8372228a97eaec5ee9e59
[I 2024-02-11 15:31:09.243 ServerApp]     http://127.0.0.1:8888/lab?token=10921098ea6d04ed83967cdb22d8372228a97eaec5ee9e59
[I 2024-02-11 15:31:09.243 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-02-11 15:31:09.278 ServerApp]

    To access the server, open this file in a browser:
        file:///home/ac/.local/share/jupyter/runtime/jpserver-16456-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=10921098ea6d04ed83967cdb22d8372228a97eaec5ee9e59
        http://127.0.0.1:8888/lab?token=10921098ea6d04ed83967cdb22d8372228a97eaec5ee9e59
[I 2024-02-11 15:31:09.671 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-02-11 15:31:11.849 LabApp] Build is up to date
[I 2024-02-11 15:31:12.000 ServerApp] Kernel started: b8987f0e-9734-49f0-a10d-073a151e033e
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-02-11 15:31:12.360 ServerApp] Connecting to kernel b8987f0e-9734-49f0-a10d-073a151e033e.
[I 2024-02-11 15:31:12.376 ServerApp] Connecting to kernel b8987f0e-9734-49f0-a10d-073a151e033e.
[I 2024-02-11 15:31:12.386 ServerApp] Connecting to kernel b8987f0e-9734-49f0-a10d-073a151e033e.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Not relevant
</pre>
</details>

**Comment by FoSuCloud** [comment]
I want to solve this problem

**Comment by AllanChain** [comment]
Sorry for the lack of information. I didn't mention that some other buttons also have this issue, for example:

![settings-page](https://github.com/jupyterlab/jupyterlab/assets/36528777/75505eb0-21c0-4fe9-8752-c6aa50dae460)

@FoSuCloud Is there a reason why you closed #15915 and created #15924 instead?

**Comment by FoSuCloud** [comment]
@AllanChain   Yes, the impact scope of the previous PR is not just the Toolbar, and will cause other UI tests to fail.
I would like to confirm with you whether the impact scope of this problem is jp-button under `.jp-NotebookPanel-toolbar`?

**Comment by AllanChain** [comment]
> whether the impact scope of this problem is jp-button under `.jp-NotebookPanel-toolbar`

No. For the settings page, the toolbar only have the class `lm-Widget jp-Toolbar`.

Currently, I don't have time to look into the UI tests, but I think a simple
```css
.jp-Toolbar jp-button { var(--jp-ui-font-color1) }
```
will work. Because original rule `.jp-Toolbar { var(--jp-ui-font-color1) }` is applied to the whole toolbar, and `jp-button` is only added to toolbars:

https://github.com/jupyterlab/jupyterlab/blob/ff90432f3d80395909ad9b1fbf101f8a1b250561/docs/source/extension/extension_migration.rst?plain=1#L30-L54

**Comment by FoSuCloud** [comment]
We cannot use .jp-Toolbar directly because jp-toolbar is also used elsewhere.
![截屏2024-03-10 20 07 24](https://github.com/jupyterlab/jupyterlab/assets/49218295/a81ae3f3-e157-4df5-a3c2-235e81331367)

**Comment by FoSuCloud** [comment]
> 您关闭#15915
![截屏2024-03-10 20 52 36](https://github.com/jupyterlab/jupyterlab/assets/49218295/11c9da92-41eb-440b-a2f5-602b4acd5baa)

It seems that what you said is right, we can use `.jp-Toolbar .jp-ToolbarButtonComponent` directly, and this weight is smaller than other customized toolbar weights.
I will perform ui tests
