### ISSUE TITLE
Typing an open parenthesis puts cursor behind the parenthesis character

### ISSUE THREAD

**Issue by ByThePowerOfScience** [jupyterlab/jupyterlab#15798]
## Description

Whenever I type an open-parenthesis in a code cell, the cursor gets placed _behind_ the open-paren instead of in front of it.  This also occurs with the Matched Brackets setting enabled, placing it behind the matched parentheses instead of between them.

However, this only occurs when typing statements on the **top level**; inside other parentheses, the cursor gets placed as normal.

See recording for example:

https://github.com/jupyterlab/jupyterlab/assets/16433721/852e0b6e-261f-4315-a604-7677ab9d8280

## Reproduce

1. Type an open parenthesis ('(') character.

## Expected behavior

Cursor should be placed after the parenthesis character.

## Context

See #15797.

## Logs

JS Console, `troubleshoot`, etc. do not have any notable output.

**Comment by JasonWeill** [comment]
Do you have the "auto close brackets" setting enabled? Without it enabled, as is the default, I just see `(` when I press `(`, and with it on, I see `()` with the cursor inside the parentheses when I press `(`.

The related item suggests you're using Firefox on macOS, which I am as well, although I'm using the ESR version. Do you still see the problem in any other browsers, or if you disable extensions in Firefox?

**Comment by ByThePowerOfScience** [comment]
> Do you have the "auto close brackets" setting enabled? Without it enabled, as is the default, I just see `(` when I press `(`, and with it on, I see `()` with the cursor inside the parentheses when I press `(`.
I currently have it on, yes.  Without it enabled, as is default, it does the same thing just with a singular `(` character instead of both parentheses.

> The related item suggests you're using Firefox on macOS, which I am as well, although I'm using the ESR version. Do you still see the problem in any other browsers, or if you disable extensions in Firefox?
Huh.  Yeah, looks like it was caused by the Word Replacer extension I just started using.  Looking at the reviews, it seems it has problems with things using React, which would also explain the awful errors I've been getting with Outlook lately.  Guess I'll be uninstalling that, which stinks because now I have to sift through the wall of course numbers my college gives me again.  Can't be helped, I suppose.

Thank you so much for the help!

Issue closed.
