### ISSUE TITLE
4.2 Release Plan

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15801]
## Current Status

`4.1.0` was released two weeks ago. A first [`4.1.1`](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.1.1) patch version was released on Monday.

This is an issue to track the features for the `4.2` release.

## Features

There are currently 85 items in the `4.2.0` milestone: https://github.com/jupyterlab/jupyterlab/milestone/76.

We can document major planned features for coordination. PR ready by the feature freeze date will be reviewed, but please aim to share things you plan to contribute to 4.2.0 ahead (by commenting in this issue, or editing this list if you have access) to allow time for discussion.

**Feel free to edit this list or comment below to add more items**:
- [ ] https://github.com/jupyterlab/jupyterlab/pull/15448 (implemented in `jupyter-collaboration` extension)
- [ ] https://github.com/jupyterlab/jupyterlab/pull/15157 (deferred to 4.3)
- [x] https://github.com/jupyterlab/jupyterlab/pull/15483
- [x] https://github.com/jupyterlab/jupyterlab/pull/15946
- [x] https://github.com/jupyterlab/jupyterlab/pull/15964
- [x] https://github.com/jupyterlab/jupyterlab/pull/15962
- [x] https://github.com/jupyterlab/jupyterlab/pull/15845
- [x] https://github.com/jupyterlab/jupyterlab/pull/15623
- [ ] https://github.com/jupyterlab/jupyterlab/pull/15155 (deferred)

## Timeline (provisional)

- feature freeze: 27 March (beta0 release; no additional pull requests adding new features would be considered past this date)
- first release candidate: 17 April (rc0 release if no release blockers identified)
- final release: <s>1 May</s> 3 May  (at a minimum one week after RC)

**Comment by krassowski** [comment]
The first alpha of 4.2.0 is out (https://github.com/jupyterlab/jupyterlab/releases/tag/v4.2.0a0, https://pypi.org/project/jupyterlab/4.2.0a0/). As a remainder, by the timeline above there are three more weeks to prepare pull requests that would go into 4.2.0 release.

**Comment by jtpio** [comment]
For reference the first Notebook `7.2.0a0` is out: https://github.com/jupyter/notebook/releases/tag/v7.2.0a0

**Comment by krassowski** [comment]
The first beta for 4.2.0 is out:
- https://github.com/jupyterlab/jupyterlab/releases/tag/v4.2.0b0
- https://pypi.org/project/jupyterlab/4.2.0b0/

**Comment by fcollonval** [comment]
I don't know if we should investigate - more to share the information. The wheel size on PyPi between 4.1.5 and 4.2.0b0 as increased by 0.2Mo (from 11,4Mo to 11,6Mo). And the conda package size increase is of 0.5Mo :confused: 

![image](https://github.com/jupyterlab/jupyterlab/assets/8435071/7b865c7a-2eae-41e1-bc7c-3e594fe73ed9)

**Comment by krassowski** [comment]
PyPI wheel sizes:
- jupyterlab 4.1.5: 11.4 MB
- 4.2.0a0: 11.5 MB
- 4.2.0a1: 11.5 MB
- 4.2.0a2: 11.6 MB (workspaces UI - a new package, CodeMirror upgrade?)
- 4.2.0b0: 11.6 MB

Does not seem to be a rapid increase due to any particular version. No idea why conda is swelling faster though.

**Comment by jtpio** [comment]
FYI Notebook `7.2.0b0` was just published: https://github.com/jupyter/notebook/releases/tag/v7.2.0b0

But there are still some issues w.r.t the `full` notebook windowing mode. So Notebook currently defaults to `defer`. This is currently being investigated in:

- https://github.com/jupyter/notebook/pull/7321
- https://github.com/jupyter/notebook/issues/7231
- https://github.com/jupyter/notebook/issues/7318

Any help on this welcome!

**Comment by krassowski** [comment]
JupyterLab 4.2.0rc0 is out! You can test it on [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gist/krassowski/d0362b2c1ac4e153079b8a6e0c181597/HEAD?urlpath=lab)

- https://pypi.org/project/jupyterlab/4.2.0rc0/
- https://github.com/jupyterlab/jupyterlab/releases/tag/v4.2.0rc0

**Comment by krassowski** [comment]
Closing as JupyterLab 4.2.0 was released yesterday :tada:

**Comment by krassowski** [comment]
4.3 release plan: https://github.com/jupyterlab/jupyterlab/issues/16315
