### ISSUE TITLE
No tooltip when hovering on the notebook tab

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15806]
## Description
I don't see a tooltip when I hover on a notebook tab. Earlier it would show a tooltip with the full name of the notebook.

## Reproduce

Open a notebook and hover on the tab.

## Context

- JupyterLab version: 4.1.0rc1

**Comment by krassowski** [comment]
I cannot reproduce on either Firefox 122 nor Chrome 121

![chrome-works](https://github.com/jupyterlab/jupyterlab/assets/5832902/69a14870-30f0-4423-acfc-87bd75687f03)
![firefox-works](https://github.com/jupyterlab/jupyterlab/assets/5832902/e150b102-b937-4e03-a657-8e7a136ef515)

**Comment by krassowski** [comment]
@divyansshhh are you able to reproduce this issue reliably? Can you provide more details about your environment (browser/OS?

**Comment by divyansshhh** [comment]
I am able to reproduce this reliably, if it's not reproducible for you then it must be happening due to some extension. I'll figure that out and get back on this.

**Comment by JasonWeill** [comment]
I'm not able to repro on Firefox ESR on macOS.

**Comment by JasonWeill** [comment]
@divyansshhh Which browser are you using, and which extensions do you have installed? If you run the same browser without these extensions (Safe Mode, Incognito Mode, alternate profile, etc) do you still see this bug?
