### ISSUE TITLE
Unable to recreate a yarn.lock

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#15829]
## Description

I thought it would be possible to recreate a `yarn.lock`, by removing it and invoking `jlpm`, but I get this error at `jlpm run build`:
```
> @jupyterlab/buildutils@4.1.2 build
> tsc && cd template && npm run build

../node_modules/@yarnpkg/fslib/lib/ZipFS.d.ts:208:5 - error TS2416: Property 'readdirPromise' in type 'ZipFS' is not assignable to the same property in base type 'BasePortableFakeFS'.
  Type '{ (p: import("/home/david/tmp/jupyterlab/node_modules/@yarnpkg/fslib/lib/path").PortablePath): Promise<import("/home/david/tmp/jupyterlab/node_modules/@yarnpkg/fslib/lib/path").Filename[]>; (p: import("/home/david/tmp/jupyterlab/node_modules/@yarnpkg/fslib/lib/path").PortablePath, opts: { ...; } | null): Promise<......' is not assignable to type '{ (p: import("/home/david/tmp/jupyterlab/node_modules/@yarnpkg/fslib/lib/path").PortablePath): Promise<import("/home/david/tmp/jupyterlab/node_modules/@yarnpkg/fslib/lib/path").Filename[]>; (p: import("/home/david/tmp/jupyterlab/node_modules/@yarnpkg/fslib/lib/path").PortablePath, opts: { ...; } | null): Promise<......'. Two different types with this name exist, but they are unrelated.
    Type 'Promise<Filename[]>' is not assignable to type 'Promise<Dirent[]>'.
      Type 'Filename[]' is not assignable to type 'Dirent[]'.
        Type 'Filename' is not assignable to type 'Dirent'.
          Type 'String & { __pathType: PathType.File; }' is missing the following properties from type 'Dirent': isFile, isDirectory, isBlockDevice, isCharacterDevice, and 5 more.

208     readdirPromise(p: PortablePath): Promise<Array<Filename>>;
        ~~~~~~~~~~~~~~
```

## Reproduce

1. `git clone https://github.com/jupyterlab/jupyterlab.git`
2. `cd jupyterlab`
3. `pixi init`
4. `pixi add pip nodejs`
5. `pixi shell`
6. `pip install hatch`
7. `pip install -e .`
8. `rm yarn.lock`
9. `jlpm`
10. `jlpm run build`

This [issue](https://github.com/yarnpkg/berry/issues/5728) suggests that this issue has been fixed in later version of `yarn`, but it seems that JupyterLab vendors `yarn` v3.5.0.

## Expected behavior

We should be able to recreate a `yarn.lock`.

## Context

- Operating System and version: Linux Ubuntu 22.04
- Browser and version: N/A
- JupyterLab version: main branch

**Comment by krassowski** [comment]
I think this can be closed since https://github.com/jupyterlab/jupyterlab/pull/15996 bumped the yarn version used in buildutils to fix this issue, see comments https://github.com/jupyterlab/jupyterlab/pull/15996#issuecomment-2009795027 and https://github.com/jupyterlab/jupyterlab/pull/15996#discussion_r1532342864.
