### ISSUE TITLE
shift+tab documentation affects the indentation

### ISSUE THREAD

**Issue by EricHUANG970823** [jupyterlab/jupyterlab#15827]
## Description
shift+tab documentation affects the indentation

## Reproduce
![Untitled](https://github.com/jupyterlab/jupyterlab/assets/97007177/039b735a-ac22-474f-9653-f04f6ea76cfd)

## Context
- Operating System and version: MacOS Sonoma 14.2.1
- Browser and version: Edge 121.0.2277.128
- JupyterLab version: 4.1.2

**Comment by krassowski** [comment]
Thank you @EricHUANG970823, I believe this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/15821.

**Comment by FoSuCloud** [comment]
But I compared other development tools and found that `dedent` is correct after executing the `shift+tab` shortcut key.Maybe the solution is to change the prompt shortcut key to something else

**Comment by JasonWeill** [comment]
However we handle the SHIFT+TAB behavior, let's keep the conversation going in #15821. @FoSuCloud thanks!
