### ISSUE TITLE
Jupyterlab 4.1 dedent broken

### ISSUE THREAD

**Issue by harper357** [jupyterlab/jupyterlab#15821]
## Description

With JupyterLab <4.1, Shift+Tab would open object introspection, tab-completion if I was in a function or if I highlight part of the line it would just dedent it. However after upgrading to 4.1, it now will dedent the current line withought highlighting, so now it will open object introspection and dedent everytime I press Shift+Tab and there is no clear way to change this short cut.

I tried reverting to Jupyterlab 4.0.12 and this fixes it, so I think it might be a bug, but no one else has reported it so maybe it is just something with my setup?

I asked this on the Discourse, but have not received any reply.

## Reproduce

In a code cell, indent a line. Now hit `Shift+Tab` to bring up the object introspection. The line gets dedented and object introspection comes up. 

I created a new python3.11 virtualenv, installed Jupyterlab 4.1.1 and did the above steps.

## Expected behavior

Dedents should only happen if part of the line is hightlighted like in Jupyterlab < 4.1

## Context
macOS 12.3 (M1)
Chrome 121.0.6167.184 
JupyterLab version: 4.1.1

**Comment by krassowski** [comment]
This is quite likely another side-effect of https://github.com/jupyterlab/jupyterlab/pull/14115; that pull request included mitigation for tab completion and indentation but not for dedentation.
