### ISSUE TITLE
Workspace.json issue in Lab 4.1?

### ISSUE THREAD

**Issue by banson-aiq** [jupyterlab/jupyterlab#15841]
Hi I think this might be an issue as side-by-side workspace config in the json file worked in lab 3.x 

## Description

Creating a workspace json file that has the Launch page side-by-side with another Launch page, or even a notebook, does not appear to work. Only one page is displayed.

Example of side-by-side layout
![image](https://github.com/jupyterlab/jupyterlab/assets/143988136/c2fb70d3-4afd-4654-a238-7dfbfc604c65)

## Reproduce

I create the below workspace file, by creating two Launcher tabs side-by-side (as per the example image above) and clicking `File -> Save Current Workspace As`
However if I change the current workspace then reload that file the layout is not reset… I do not see the two Launcher windows side by side.
How can I specify a workspace.json file that sets the layout of the Launcher page?

```json
{
  "data": {
    "layout-restorer:data": {
      "main": {
        "dock": {
          "type": "split-area",
          "orientation": "horizontal",
          "sizes": [
            0.5,
            0.5
          ],
          "children": [
            {
              "type": "tab-area",
              "currentIndex": 0,
              "widgets": []
            },
            {
              "type": "tab-area",
              "currentIndex": 0,
              "widgets": []
            }
          ]
        }
      },
      "down": {
        "size": 0,
        "widgets": []
      },
      "left": {
        "collapsed": false,
        "visible": true,
        "current": "filebrowser",
        "widgets": [
          "filebrowser",
          "running-sessions",
          "@jupyterlab/toc:plugin"
        ],
        "widgetStates": {
          "jp-running-sessions": {
            "sizes": [
              0.25,
              0.25,
              0.25,
              0.25
            ],
            "expansionStates": [
              false,
              false,
              false,
              false
            ]
          }
        }
      },
      "right": {
        "collapsed": true,
        "visible": true,
        "widgets": [
          "jp-property-inspector",
          "debugger-sidebar"
        ],
        "widgetStates": {
          "jp-debugger-sidebar": {
            "sizes": [
              0.2,
              0.2,
              0.2,
              0.2,
              0.2
            ],
            "expansionStates": [
              false,
              false,
              false,
              false,
              false
            ]
          }
        }
      },
      "relativeSizes": [
        0.21255664935076815,
        0.7874433506492319,
        0
      ],
      "top": {
        "simpleVisibility": true
      }
    },
    "file-browser-filebrowser:cwd": {
      "path": "~"
    },
    "workspace-ui:lastSave": "example1.jupyterlab-workspace"
  },
  "metadata": {
    "id": "example1",
    "last_modified": "2024-02-21T07:04:21+00:00",
    "created": "2024-02-21T07:04:21+00:00"
  }
}
```

## Expected behavior

side-by-side workspace layout should be shown

## Context

- Operating System and version: Linux Ubuntu 22.04
- Browser and version: Chrome 121.0.6167.139
- JupyterLab version: 4.1.0

Cross posted issue as requested
https://discourse.jupyter.org/t/workspace-json-issue-in-lab-4-1/24054

**Comment by krassowski** [comment]
I can confirm that workspace loader does not work correctly on either 4.0.12 nor on 4.1.2. This needs an integration test.

![workspace-loader-does-not-work](https://github.com/jupyterlab/jupyterlab/assets/5832902/bc3258fd-d22e-404f-9181-7bd4a662e80b)

I think I know what the problem is..

**Comment by krassowski** [comment]
I think 3.6.7 would be broken too.
