### ISSUE TITLE
Displaying rich html inside completer documentation panel

### ISSUE THREAD

**Issue by yogevyuval** [jupyterlab/jupyterlab#15863]
Hi,
I'm building a `JupyterFrontEndPlugin` that registers a ICompletionProvider to autocomplete a custom language. I'm able to to get autocompletions and have each item define a `documentation` property that shows up as a documentation panel when completing.

How can I put rich html (colors, fonts, sizes) inside the documentation panel and not only plain strings? It looks like other completers are able to do it, but following the code it looks like the string is sanitized and only displayed as a raw string.

For example, I would want to have an item that looks like:
```
{
label: "some_function"
type: "function")
documenation: "This <i> function </i> uses <b>x</b> to do y"
}
```

**Comment by krassowski** [comment]
Hi @yogevyuval, you can define a [`renderer`](https://jupyterlab.readthedocs.io/en/latest/api/interfaces/completer.ICompletionProvider.html#renderer) on your `ICompletionProvider` and it can define a custom [`createDocumentationNode()`](https://jupyterlab.readthedocs.io/en/latest/api/interfaces/completer.Completer.IRenderer.html) implementation. To get you started you can inherit from the default renderer ([`Completer.Renderer`](https://jupyterlab.readthedocs.io/en/latest/api/classes/completer.Completer.Renderer-1.html)).

I would still recommend sanitizing the documentation string in your custom renderer though. You can re-use our `renderHTML`, `renderMarkdown`, etc functions which take a sanitizer and can handle it.

**Comment by krassowski** [comment]
Looking at it again, there is an existing issue tracking improvements to this API (https://github.com/jupyterlab/jupyterlab/issues/15127):
- currently the renderer from the provider with the highest rank is used, but ideally it would be decided on per-item basis
- currently the default is plain text, but JupyterLab should allow to pass a MIME bundle and take care of rendering

Contributions towards https://github.com/jupyterlab/jupyterlab/issues/15127 are welcome (we do not need to implement both ideas at once).

**Comment by yogevyuval** [comment]
> ICompletionProvider

Thanks @krassowski , I understand what you mean but the API is a bit complicated, is there any example you can think of I can start with?

**Comment by JasonWeill** [comment]
Accepting this as a documentation issue; it would be great to have better documentation in the JupyterLab docs about displaying rich HTML as described above.
