### ISSUE TITLE
Partial rendering of notebooks

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#1587]
## Overview
Out of the discussions for a [simple heuristic to decide when to use a full editor instance versus statically rendering it](https://github.com/jupyterlab/jupyterlab/issues/1128), we hit upon a different but related tactic of only rendering the content that is on the screen. The two candidates for doing this are:
* **Virtual scrolling:** using a visually familiar but custom-written scrollbar functionality that allows us to know where we are in a document and only rendering the content that is required there.
* **Real scrolling:** adopting the same approach but simply using a large container for the document (with most of it as empty space) and taking advantage of native scrollbars.

## Real scrolling
Since even the largest notebooks are on the order of hundreds of cells, a native element should be able to hold an entire notebook, so taking advantage of the native scrollbar seems like an easy win because:
* We won't need to reimplement gestures.
* When we want to support other devices, we'll get the benefit of the native scrolling semantics that come with those devices.
* Our codebase will be smaller.
* Performance will be better.

## Virtual scrolling
The primary benefit of building a virtual scrolling capability is arbitrary (effectively infinite) size. We don't need this, but if we ever do, virtual scrolling will be the only way.

## Concerns
* When building something like a spreadsheet component or a grid, it's easier to calculate the height of the invisible cells. Most implementations have a fixed height. @sccolbert has built grids with arbitrarily sized rows, so his input will be helpful here. One of our problems is knowing how tall every cell in a notebook is without incurring the cost of rendering it before hiding it.

(Please feel free to add other concerns that you think of.)

cf. https://github.com/jupyterlab/jupyterlab/issues/1128

**Comment by blink1073** [comment]
I suspect we'll have to render everything to start, and then re-render it when it comes back on screen.  Things that are off-screen producing additional outputs would not affect the scroll bar until they get rendered again.

**Comment by jasongrout** [comment]
> Things that are off-screen producing additional outputs would not affect the scroll bar until they get rendered again.

I think that's a feature. If I have some output above me, off the screen, that is growing, I don't want my current viewport to keep shifting down.

**Comment by blink1073** [comment]
Agreed!

**Comment by jasongrout** [comment]
In the issue @blink1073 references, they mention the https://github.com/NeXTs/Clusterize.js library, which looks like it might do something like what @afshin mentions in his Real Scrolling option.

**Comment by sccolbert** [comment]
This is an extremely complicated topic with lots of trade-offs and edge cases. I don't think we should block 1.0 on this. We need to discuss the trade-offs in detail before we move forward.

**Comment by sccolbert** [comment]
I can *potentially* make a Phosphor layout which helps with this.

**Comment by ellisonbg** [comment]
The performance issues with large notebooks will be addressed in #2540 which may make this issue not relevant any more.

**Comment by mlucool** [comment]
Interesting idea [maybe coming to react](https://reactjs.org/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.html#offscreen):
> Offscreen introduces a third option: hide the UI visually, but deprioritize its content. The idea is similar in spirit to the content-visibility CSS property: when content is hidden, it doesn’t need to stay in sync with the rest of the UI. React can defer the rendering work until the rest of the app is idle, or until the content becomes visible again.

CC @fcollonval
