### ISSUE TITLE
Right click opens both Firefox and JupyterLab context menus

### ISSUE THREAD

**Issue by SolverMax** [jupyterlab/jupyterlab#15900]
When I right click within the JupyterLab file browser or a notebook, the Firefox and JupyterLab context menus both open, with the Firefox menu on top. Pressing Esc removes the Firefox menu, leaving the JupyterLab context menu open and usable.

This issue started when I installed JupyterLab Version 4.1.2.

The behaviour is very similar to https://github.com/jupyterlab/jupyterlab/issues/11722

Operating system: Occurs on both Windows 10 and Windows 11 machines.  Firefox v123.0.

**Comment by krassowski** [comment]
> This issue started when I installed JupyterLab Version 4.1.2.

As compared to 4.1.1, 4.0.x or 3.6.x? Or was 4.1.2 the first version you installed?

**Comment by SolverMax** [comment]
The Windows 10 PC has been using JupyterLab for several years. The upgrade was from a recent version, probably something like 4.1.1 or 4.1.0. The Windows 11 PC is a new install on a new PC. Both PCs have the same behaviour.

**Comment by krassowski** [comment]
Could you temporarily downgrade one step at a time to confirm which version was working wel?

**Comment by SolverMax** [comment]
I went back to v3.6.7. All versions show the same behaviour.
I just noticed that Discord also has the same behaviour. So I assume it is something the Firefox did recently.

**Comment by JasonWeill** [comment]
I use Firefox ESR 123 as well, and I don't see this behavior. I'm on macOS, though. Typically, the browser's context menu shows when you hold SHIFT and right-click. Can you try disabling any extensions you're running in Firefox and try again?

**Comment by SolverMax** [comment]
Shift+right click shows only the Firefox context menu. Right click shows both the Firefox and JupyterLab context menus. Disabling all extensions makes no difference.

**Comment by JasonWeill** [comment]
In Windows, I don't see this behavior with JupyterLab 4.1.3 and Firefox ESR 115.8.

**Comment by SolverMax** [comment]
I just updated Firefox to 123.0.1 and JupyterLab to 4.1.3. Same behaviour.

**Comment by SolverMax** [comment]
Both Edge and Chrome behave correctly, while Firefox does not.

**Comment by JasonWeill** [comment]
This exceptionally old (22 years!) Mozilla bug may be related: https://bugzilla.mozilla.org/show_bug.cgi?id=186356

**Comment by krassowski** [comment]
@SolverMax does it persist with the latest version of Firefox (125.0.1)? Do you have any browser extensions installed which could interfere?

**Comment by SolverMax** [comment]
The issue has been fixed. I don't know what caused it, but the fix was to set dom.event.contextmenu.enabled to True in Firefox's about:config

**Comment by JasonWeill** [comment]
@SolverMax Thanks for the update! I see that this setting defaults to true in Firefox config (at least for me, on Firefox 124.0.2) so I'll close this issue. I appreciate your contributions.
