### ISSUE TITLE
shift-tab tooltip line wrap missing

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#1591]
On ubuntu chrome + jupyterlab 0.15 I observe that long docstrings or call signatures in the tooltip are not wrapped, and it does not seem possible to scroll to read the ends of the lines.

**Comment by blink1073** [comment]
Thanks for the feedback, keep it coming!

**Comment by ellisonbg** [comment]
Great find! I think I would add scrolling rather than wrapping.
