### ISSUE TITLE
`Ctrl + S` triggle browser's "save page", not save notebook in `4.1.3`

### ISSUE THREAD

**Issue by lf-shaw** [jupyterlab/jupyterlab#15912]
similar #306，tested with `Edge` and `firefox`.

it's ok in `4.1.2`.

**Comment by Deeperand** [comment]
I use Jupyter Lab 4.1.3 on macOS 13.6.3 with Chrome 122.0.6261.94, also found this problem. Besides, other key-combination looks also meet the similar problem. e.g. Option-w will print ∑ instead of close current Jupyter tab.

**Comment by mikewilkerson-solas** [comment]
This regression also affects the ability to use `CMD-SHIFT-c` (MacOS, Chrome/Brave/etc) to open the command menu (it _does_ open the menu, but a split second later the Chrome dev tools window pops up

**Comment by krassowski** [comment]
Thank you all! I opened https://github.com/jupyterlab/jupyterlab/pull/15913 and added workarounds for `Ctrl + S` and `CMD-SHIFT-c` (I would appreciate if you could confirm that it works by testing out the PR [on Binder](https://mybinder.org/v2/gh/krassowski/jupyterlab/fix-ctrl-s?urlpath=lab) - please be patient with Binder when it builds, it might need reloading at some time). If you see any other problematic command please let me know.

> other key-combination looks also meet the similar problem. e.g. Option-w will print ∑ instead of close current Jupyter tab

This is an interesting case, so previously users complained than certain key combinations should type a very specific character but did something else. In JupyterLab 4.1.3 PR https://github.com/jupyterlab/jupyterlab/pull/15790 ensures that user input is never overruled, but this is turning out to be problematic too. I think we need to implement https://github.com/jupyterlab/lumino/issues/688 soon and allow users to tune it on per-command binding basis.

**Comment by krassowski** [comment]
Before we solve it with fine-grained per-shortcut option, we could add a setting for toggling between "prevent default action by default" (JupyterLab 4.1.2 style) and "do not prevent default action by default" (JupyterLab 4.1.3 style) so that everyone would be happy.

**Comment by krassowski** [comment]
Long-term solution PR in https://github.com/jupyterlab/jupyterlab/pull/15927
