### ISSUE TITLE
Cannot scroll away from current cell 

### ISSUE THREAD

**Issue by VanWieren** [jupyterlab/jupyterlab#15922]
## Description

When scrolling in a jupyter lab environment I immediately get stuck on the same cell and am forced to use the scroll bar on side of browser

## Reproduce

open a notebook and scroll

## Expected behavior

scrolling as normal

## Context

- Operating System and version: Mac OSX 14.3.1
- Browser and version: Chrome 122.0.6261.94
- JupyterLab version: 4.1.3

**Comment by krassowski** [comment]
Thank you for reporting! Can you please provide as much detail as possible, ideally including a reoccurring and whether this happens with an empty notebook or just with specific notebooks, as a comment in https://github.com/jupyterlab/jupyterlab/issues/15795?

**Comment by krassowski** [comment]
Closing as a duplicate.
