### ISSUE TITLE
Automatic anchors for markdown headings

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#1592]
Compared to the classic notebook, where markdown headings automatically had anchors and had clickable links that produced the URL for accessing the anchor, jupyterlab does not allow to refer to a single heading. This is an extremely useful feature for longer notebooks that often even contain a table of contents.

**Comment by blink1073** [comment]
Thanks again!

**Comment by michaelpacer** [comment]
Keep in mind, that the mechanism to autogenerate header ids may change in the classic notebook (for the better, to be more like [pandoc's automatic id generation scheme](http://pandoc.org/MANUAL.html#extension-auto_identifiers)). I'm likely to be the one leading the charge on this, so I'm happy to do what I can to help. 

I'm new to typescript but implementing a way to assign ids to headers using the old mechanism shouldn't be too hard. All it requires is taking the header content and then converting the spaces to hyphens (`-`). If someone wants to point me in the right direction, I can try to make a PR that accomplishes this.

**Comment by jasongrout** [comment]
> I'm new to typescript but implementing a way to assign ids to headers using the old mechanism shouldn't be too hard

Does it make sense to implement this now, or hold off until we figure out how things will change going forward?

**Comment by michaelpacer** [comment]
I figured implementing a really simple version is going to be a better first contribution than trying to get all the pieces of the more complicated system working. Also, it helps meet parity of the notebook today until I manage to get everything in place for the improved regime.

**Comment by blink1073** [comment]
If you want to have a go at adding anchor tags to the markdown output, here are the matching points in code in jlab: https://github.com/jupyterlab/jupyterlab/blob/9b5462aa2ebbbef8e06b587327fde5598b6c79b7/src/renderers/widget.ts#L191 and notebook: https://github.com/jupyter/notebook/blob/666ecbf35c3310335a3c8c182e8f53441c991c14/notebook/static/notebook/js/textcell.js#L392

**Comment by michaelpacer** [comment]
I looked at this yesterday to with @ian-r-rose and @Carreau. We have some progress toward what was happening and the beginning of a solution. 

Briefly, it seems that automatic anchors are being applied, but are being stripped by the sanitisation code. Simply allowing ids in the sanitisation steps is unsafe, so I'll need to think of something more nuanced. We discovered this after we saw that manually applied ids to header tags (written in HTML) also are stripped (as are all other attributes (e.g., colour)).

I didn't trace down (yet) where the auto-ids are coming from. To know and control the algorithm for generating those ids will require figuring that out but before that will be easy to debug I want and need to figure out how to fix sanitisation step.

**Comment by blink1073** [comment]
Ah, I think this comes down to whether we can "trust" the output of a markdown cell.  Markdown cells are never considered trusted, see https://github.com/jupyter/notebook/pull/1126.  We have to manually handle the anchor tags and id ourselves, adding them after the sanitize step [here](https://github.com/jupyterlab/jupyterlab/blob/c5fbf2537edd17e37d39411ce1fc5961b6432003/src/renderers/widget.ts#L198).

**Comment by michaelpacer** [comment]
Looked at the marked source and found where ids were generated: https://github.com/chjj/marked/blob/master/lib/marked.js#L795

For modifying that we may need to overwrite that function .

**Comment by blink1073** [comment]
That step precedes the sanitization step, so it would be removed.

**Comment by michaelpacer** [comment]
Ah ok that approach makes sense, still it will require some finagling.  Sanitisation on Jupiter lab is structer than in the notebook.

**Comment by michaelpacer** [comment]
Won't be able to look at this much more until the beginning of next week.

**Comment by blink1073** [comment]
No excuses Michael.  :wink:
