### ISSUE TITLE
Shorter "Last Modified" display in narrow columns

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#15947]
### Problem

The "Last Modified" column takes up a lot of horizontal space in a narrow container. In English, a relative date like "11 months ago" is likely longer than the filename it describes:

<img width="416" alt="long-date" src="https://github.com/jupyterlab/jupyterlab/assets/93281816/11be204d-d2a4-483f-a9af-bbc323d88b03">

The absolute date appears on hover, in a tooltip.

### Proposed Solution

We use an [Intl.RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat) object to make human-readable dates in an internationalizable format. When changing that to use the "short" format, units like "months" shorten, but "days" does not, and "ago" remains, even though we can be reasonably certain that almost all files will have been created in the past.

<img width="315" alt="short-date" src="https://github.com/jupyterlab/jupyterlab/assets/93281816/18fc33d1-af86-4856-8426-cc5a89ed46d2">

As a more extreme alternative, we could reduce this to "#u", with a number and a very short unit. This pattern is already used by mobile apps and mobile web sites, and may require additional manual internationalization. We can also shorten "Last Modified" to "Mod", to allow for the column to be shortened.

<img width="307" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/93281816/de22fda1-fba3-43af-ae23-09679124f373">

Note that Asian languages already have single characters for most time units, 

In the rare case that a file's time stamp in the future, we can put a `+` before the number; the normal expectation is that a date is in the past.

### Additional context

See also #14237, #3875, and #8497 for other issues about columns in the filebrowser.

**Comment by GabrielaVives** [comment]
I agree that even the "ago" could be removed, like you showed in your 2nd suggestion.
