### ISSUE TITLE
Update @jupyter/ydoc v2.0.1

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#15951]
### Problem

I see we currently pin `"@jupyter/ydoc": "^1.1.1"`, but latest version is `2.0.1`.

### Proposed Solution

Pin  `"@jupyter/ydoc": "^2.0.1"`.

**Comment by jtpio** [comment]
Thanks @davidbrochart.

Any particular change (breaking?) to expect from this upgrade?

**Comment by davidbrochart** [comment]
The difference from v1 to v2 was about switching to `pycrdt`, so it was only concerning the Python code. They should be no change in the JavaScript code, but I think we should upgrade anyway.

**Comment by jtpio** [comment]
OK thanks.

Just opened https://github.com/jupyterlab/jupyterlab/pull/15982 to see if CI passes.
