### ISSUE TITLE
Unable to click on notebook-related things

### ISSUE THREAD

**Issue by arudhir** [jupyterlab/jupyterlab#1596]
Using Chrome and Jupyter version 4.2.0

I apologize if this is too general, but I am not sure these are related problems/just not implemented yet/something else, and I didn't want to spam the issues page.

The ones I have noticed so far are:

1. "Take a tour" on Landing doesn't do anything 
2. In the launcher tab, clicking on "Notebook" doesn't open the prompt for me to type in a name and pick a kernel (everything else does)
3. Picking a theme for a notebook doesn't do anything (works for text editor)

Jupyter Lab is extremely smooth so far though :)

**Comment by blink1073** [comment]
Hi @arudhir, thank you for the feedback.  1) and 2) are confirmed bugs.  The editor settings are indeed only targeted for the text editor.  We don't (yet) have a way to theme the notebook dynamically.

**Comment by blink1073** [comment]
Dev note: this should be released in a 0.15.1.  Here are the console logs:

![image](https://cloud.githubusercontent.com/assets/2096628/22528625/bb84faaa-e899-11e6-8021-343983f4b82b.png)
