### ISSUE TITLE
"Last Modified" is covered at first, then returns to normal

### ISSUE THREAD

**Issue by FoSuCloud** [jupyterlab/jupyterlab#15979]
## Description
"Last Modified" is covered at first, then returns to normal

![word-move](https://github.com/jupyterlab/jupyterlab/assets/49218295/666b2a84-ebc7-4b46-a9e0-be3d79cf8c3f)

## Reproduce

1. Resize FileBrower sidebar to minimum width
2. You can see it by refreshing the page

## Expected behavior
"Last Modified" should not be blocked by default

## Context

- Operating System and version: macOS 12.2
- Browser and version: Chrome 122
- JupyterLab version: 4.1.2

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
@FoSuCloud Thank you for opening this! If you check out the code for #15948, which changes the widths of columns to allow them to flex, do you still see this behavior?

**Comment by FoSuCloud** [comment]
Thanks, I can see that the "last modified" is no longer overwritten in the code branch environment of #15948.
I will close this issue after the PR is merged
