### ISSUE TITLE
Accidentally converting a %debug cell to a raw cell blocks the kernel permanently

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#15981]
## Description
If a cell is in %debug mode, accidently pressing "R" can convert it into a raw cell which leaves the kernel in an unrecoverable state. 

## Reproduce
1. In cell 1, run the following: 
```python
def fn():
    raise ValueError()

fn()
```
2. In cell 2, run - 
```
%debug
```
3. Now convert the cell into a raw cell.

## Expected behavior
Converting such a cell to a raw cell shouldn't be allowed or should throw a warning. 

## Context
- JupyterLab version: 4.1.2

**Comment by krassowski** [comment]
Some context:
- JupyterLab implements a guard which prevents running any cell from being when there is a pending input request (such as that created by `%debug` but more general example includes `input()`) to prevent kernel deadlock (https://github.com/jupyterlab/jupyterlab/pull/10792)
- Changing cell type was also reported as problematic when a cell is read-only as it should not be possible but currently is (https://github.com/jupyterlab/jupyterlab/issues/11165)

Given repeated reports it appears warranted to introduce a conditional block on cell type change which would be active when the input guard is active (and when the cell is read-only).

Currently the input guard is a property of the `sessionContext`:

https://github.com/jupyterlab/jupyterlab/blob/910a16229bd75553baaa5c2a545e3fa798234c75/packages/notebook/src/actions.tsx#L2502-L2511

but to implement the guard for individual cells we will need some indicator of `pendingInput` on the cell level. This might be already possible by listening to `cell.outputArea.inputRequested`:

https://github.com/jupyterlab/jupyterlab/blob/910a16229bd75553baaa5c2a545e3fa798234c75/packages/notebook/src/widget.ts#L696-L708

and locking cell type change when input is requested; we could unlock it on `stdin.value` promise resolving and when `stdin.disposed` emits.
