### ISSUE TITLE
Isolate directionality of a string from surrounding

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1598]
cf https://github.com/jupyter/notebook/pull/2114

https://github.com/jupyterlab/jupyterlab/blob/9b5462aa2ebbbef8e06b587327fde5598b6c79b7/src/codemirror/index.css#L89

**Comment by ebraminio** [comment]
This project looks very fantastic, I wasn't familiar with it. But about the patch, I later found out my patch there had a minor and it was breaking the editing experience so a correct fix will be a little more complicated :(

**Comment by blink1073** [comment]
Thanks, @ebraminio, I'll keep an eye out for updates.
