### ISSUE TITLE
workspaces confusion problem

### ISSUE THREAD

**Issue by rickmody** [jupyterlab/jupyterlab#15989]
Hello, Jupyter developer. I'm currently facing an issue. I'm launching N Jupyter containers, all of which mount directories from the home directory of the same user. This has caused confusion with workspaces. The default location for JupyterLab workspaces directory is $HOME/.jupyter/lab/workspaces/. How can I isolate this directory? Are there any parameters for configuration?

**Comment by krassowski** [comment]
You can set different `JUPYTERLAB_WORKSPACES_DIR` for different users see https://jupyterlab.readthedocs.io/en/latest/user/directories.html#jupyterlab-workspaces-directory
