### ISSUE TITLE
Display kernel ID in the list view of kernels in the sidebar

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#15991]
> about the table view; should we display the kernel id in a second column (a bit like last modified in the file browser)? Otherwise the kernels section does not bring lots of information compare to the open tabs.

_Originally posted by @fcollonval in https://github.com/jupyterlab/jupyterlab/pull/15845#pullrequestreview-1933776385_
            

Quick first mockup (probably should be aligned more to the right and maybe does not need the parentheses, but just to give the idea what this is about):

![mockup](https://github.com/jupyterlab/jupyterlab/assets/5832902/2115904f-0963-45a4-af9e-ebf191100aba)

**Comment by RyanWilson20** [comment]
Great. I'd love to work on solving this. Thank you!

**Comment by Rob-P-Smith** [comment]
I'm working on this.

**Comment by Kunalpal216** [comment]
Is this issue open ? I would like to work on this.

**Comment by fcollonval** [comment]
@Kunalpal216 yes the issue is still opened. Feel free to start a PR on it.

For your information, an attempt has been made: https://github.com/jupyterlab/jupyterlab/pull/16228 Don't hesitate to borrow the changes from them.
