### ISSUE TITLE
`Kernel Busy` and cell status running (`[*]`) on Windows, after closing TK dialog a second time

### ISSUE THREAD

**Issue by RRosio** [jupyterlab/jupyterlab#16001]
## Description

In Windows, after opening and closing a TK dialog for the second time the kernel status remains busy. The cell status symbol `[ ]:` remains in running mode `[*]`.
This issue is not present when running this code on an M1 Mac. 

https://github.com/jupyterlab/jupyterlab/assets/12378147/ccb61c2d-b838-4d5e-ad66-ea10228fea5d

## Reproduce

1). Run the code below.
2).  A TK dialog will appear with a 'Test' button on it.
4). Close the dialog box.
5). The kernel is now idle as expected
6). Try the same thing again - now the kernel stays in busy state and does not go back to 'idle' state.

## Expected behavior
Expect the kernel to update to 'idle' state and the cell status to update indicating it has finished running after closing the dialog box.

## Context

- Operating System and version: Windows 11 
- Browser and version: Microsoft Edge
- JupyterLab version: Version 4.1.4

<details><summary>Code to Reproduce</summary>

```
import tkinter as tk
from tkinter import *
from tkinter import ttk
from tkinter import filedialog as fd
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('TkAgg')
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import (FigureCanvasTkAgg)
from matplotlib.backends.backend_tkagg import (NavigationToolbar2Tk)

def fileopen():
    print('Working on Busy Kernel issue')

root = Tk()
root.geometry("280x100")
root.title("Test_03/12/24")

mainframe = ttk.Frame(root, padding='0.25i')
mainframe.grid(column=0, row=0, sticky=(N, W, E, S))
root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)

# GUI Content
ttk.Button(mainframe, text ="Test", command = fileopen).grid(column=2, row=0, sticky=E)

for child in mainframe.winfo_children():
    child.grid_configure(padx=5, pady=5)

root.mainloop()
```

</details>

<details><summary>Command Line Output</summary>
No command line error message
</details>

<details><summary>Browser Output</summary>
No browser error message
</pre>
</details>

**Comment by sfweller84** [comment]
Hello Carlos,

Adding the above statement - %gui tk -  doesn't help - kernel still remains in a busy state.
Can you try to repro the problem on your end?

Thank you!

**Comment by JasonWeill** [comment]
Does this happen in Jupyter Console as well? This may be a bug in ipykernel rather than JupyterLab if so.

**Comment by JasonWeill** [comment]
Still need feedback about whether this happens in Jupyter Console.
