### ISSUE TITLE
Kernel (Python3) dies more or less immediately on 0.15.1

### ISSUE THREAD

**Issue by jtkiley** [jupyterlab/jupyterlab#1601]
I just updated to 0.15.1, and the kernel is dying on me more or less immediately (kicking off the retry process immediately). I tried with a relatively simple notebook that I had been using and I also tried creating a new blank notebook.

~~~
[I 13:50:49.236 LabApp] KernelRestarter: restarting kernel (1/5) 
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5: Error while finding spec for
 'ipykernel.__main__' (<class 'ImportError'>: cannot import name 'StdinInput'); 'ipykernel' is a package
 and cannot be directly executed
~~~

**Comment by blink1073** [comment]
Hi @jtkiley, can you please try running `jupyter notebook` and starting a new notebook with that kernel to make see if this is related to JupyterLab itself?

**Comment by jtkiley** [comment]
Same issue, but `pip3 install --upgrade jupyter` fixed it. In case it helps, only one package was updated (below). Sorry, I should have chased it down a little more before filing an issue.

~~~
Collecting prompt-toolkit<2.0.0,>=1.0.0 (from jupyter-console->jupyter)
  Downloading prompt_toolkit-1.0.13-py3-none-any.whl (247kB)
    100% |████████████████████████████████| 256kB 2.2MB/s
~~~

**Comment by blink1073** [comment]
Glad you got sorted!
