### ISSUE TITLE
Use ellipses consistently in menu items and commands

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#16025]
This is a spin-off from #15946.

[Apple's Human Interface Guidelines for menus](https://developer.apple.com/design/human-interface-guidelines/menus) suggest, "Append an ellipsis to a menu item’s label when people need to provide additional information before the action can complete." A cascading menu, like File > Save and Export Notebook As, should not have an ellipsis, as it does now.

Audit commands in pull-down menus; for each one that pops up a dialog box to accept additional information, ensure that there is an ellipsis in the menu item. For each menu item that takes immediate action, there should be no ellipsis. Cascading menus should never have an ellipsis, but submenu items that require additional information should have one.

Update the JupyterLab documentation to mention this style improvement.

**Comment by BiniyamDS** [comment]
I am beginner to open source so could I take this issue

**Comment by krassowski** [comment]
Please do!

**Comment by Rob-P-Smith** [comment]
Working on this now.
