### ISSUE TITLE
`js-documentsearch` started failing on CI

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16023]
## Description

`js-documentsearch` started failing a few hours ago, as seen in a few recent PRs:
- https://github.com/jupyterlab/jupyterlab/pull/16022
- https://github.com/jupyterlab/jupyterlab/pull/16017
- https://github.com/jupyterlab/jupyterlab/pull/16018

with related actions:
- https://github.com/jupyterlab/jupyterlab/actions/runs/8344172540/job/22836019508?pr=16022
- https://github.com/jupyterlab/jupyterlab/actions/runs/8339946870/job/22822897980?pr=16017
- https://github.com/jupyterlab/jupyterlab/actions/runs/8341070539/job/22826382472?pr=16018

It was passing 8 hours ago on `main`: https://github.com/jupyterlab/jupyterlab/actions/runs/8339928987/job/22822850268

```js
  ● documentsearch/searchmodel › SearchDocumentModel › #parsingError › should set informative string message on invalid regex

    expect(received).toEqual(expected) // deep equality

    Expected: "SyntaxError: Invalid regular expression: /query\\/: \\ at end of pattern"
    Received: "SyntaxError: Invalid regular expression: /query\\/gim: \\ at end of pattern"

      88 |         model.searchExpression = 'query\\';
      89 |         await signalToPromise(model.stateChanged);
    > 90 |         expect(model.parsingError).toEqual(
         |                                    ^
      91 |           'SyntaxError: Invalid regular expression: /query\\/: \\ at end of pattern'
      92 |         );
      93 |       });

      at Object.<anonymous> (test/searchmodel.spec.ts:90:36)


Error: expect(received).toEqual(expected) // deep equality

Expected: "SyntaxError: Invalid regular expression: /query\\/: \\ at end of pattern"
Received: "SyntaxError: Invalid regular expression: /query\\/gim: \\ at end of pattern"
```

**Comment by krassowski** [comment]
The difference appears to come from a different node version being used. It was passing with `NODE_VERSION=18.x` and is failing with `NODE_VERSION=20.x`. The timing also matches the release of https://github.com/jupyterlab/maintainer-tools/releases/tag/v0.25.0

**Comment by jtpio** [comment]
Maybe we can pin `node-version` to `18.x` for this particular test for now?

**Comment by krassowski** [comment]
I will adjust the test to work on either node version.
