### ISSUE TITLE
Sorting shortcuts in language other than English does not work

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16039]
## Description

We should not mix up sort keys and translated labels, compase:

https://github.com/jupyterlab/jupyterlab/blob/b318b57d3e5e15ade52c493d264c7818ffcd9381/packages/shortcuts-extension/src/components/ShortcutTitleItem.tsx#L24

https://github.com/jupyterlab/jupyterlab/blob/b318b57d3e5e15ade52c493d264c7818ffcd9381/packages/shortcuts-extension/src/components/ShortcutInput.tsx#L64-L76

## Reproduce

![error](https://github.com/jupyterlab/jupyterlab/assets/5832902/3fb0a88a-85a2-435a-9e74-edd17c84596a)

## Expected behavior

Works

## Context

- JupyterLab version: 4.1.5

**Comment by JasonWeill** [comment]
We should also be sorting using a sort algorithm suitable to the language in question.
