### ISSUE TITLE
Line wrap does not work

### ISSUE THREAD

**Issue by catmoez** [jupyterlab/jupyterlab#16030]
Hello, 

In Jupyter Notebook and Jupyter Lab (Version 4.0.12), turning on line wrap either via the checkboxes in Settings (in Jupyter Lab) or adding JSON code for setting 'configCodeCell' to wrap text in Advanced Settings/Settings Editor under Text editor does not work.

The issue is discussed here but the answers do not work:
https://stackoverflow.com/questions/48202340/enable-word-wrap-in-jupyterlab-code-editor
https://github.com/jupyterlab/jupyterlab/issues/15579 (an official and closed answer; the code provided currently does not work)
https://discourse.jupyter.org/t/my-jupyter-linewrap-doenst-work/24297

The closest I have gotten is the following in the Settings > Settings Editor > Notebook > Json(...) panel, i.e. there is no immediate error message and I can save the following settings. However, it still does not apply, even when restarting the entire Jupyter Lab program. If I enter 'codeCellConfig' (...) instead of 'editorConfig' as suggested in some answers, this is not recognized as a valid property.
```

   {
        "scrollPastEnd": true,
        "toolbar": [],
        "editorConfig": {},
        "editorConfig": {"lineWrap": "on"}
    }

```
Could you please provide official and full documentation of how to change this in Settings, or other steps that do work?

Thank you!

**Comment by JasonWeill** [comment]
@catmoez Thank you for opening this issue! Issue #15579 is still open concerning the menu item not working as expected. Let's keep the conversation going there.
