### ISSUE TITLE
Jupyter lab terminals do not remember history

### ISSUE THREAD

**Issue by fzyzcjy** [jupyterlab/jupyterlab#16045]
## Description

Hi thanks for the tool! However, the terminal does not seem to remember command history.
For example, open terminal 1 and input command A, then open terminal 2 and the history of "command A" will not be found. The terminal 1 needs to be closed in order to let later terminals see its history.

By the way, as a side question, where is the command history file stored? I am using jupyter's official docker stack, thus would be great to know that folder and mount to host to avoid losing history between restarts.

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
> For example, open terminal 1 and input command A, then open terminal 2 and the history of "command A" will not be found. The terminal 1 needs to be closed in order to let later terminals see its history.

This is down to specific terminal shell that you use. This is a typical behaviour of a bash shell history, nothing to do with JupyterLab itself.

> By the way, as a side question, where is the command history file stored? I am using jupyter's official docker stack, thus would be great to know that folder and mount to host to avoid losing history between restarts.

This is a question best answered by https://github.com/jupyter/docker-stacks but the answer will likely depend on whether you use the default terminal shell, or customize it, and have little to do with Jupyter itself but more with the shell of choice.

**Comment by fzyzcjy** [comment]
I see: Now there is .bash_history. Originally I got confused because I started a brand new container, and since the terminal does not write to bash history before closing, there is no such file...

So to confirm, do I understand correctly: JupyterLab does nothing special, but just uses the system's normal shell?

**Comment by JasonWeill** [comment]
@fzyzcjy On Linux, this is generally true; JupyterLab uses whichever shell you've chosen to use.

**Comment by fzyzcjy** [comment]
Thank you!
