### ISSUE TITLE
Underscore in LaTeX markdown causes error

### ISSUE THREAD

**Issue by cnydw** [jupyterlab/jupyterlab#16051]
## Description

In the latest (4.1.5) jupyterlab, the following LaTeX code in markdown causes error

`$\textit{hello_world}$`

![image](https://github.com/jupyterlab/jupyterlab/assets/10969537/14e1c0b1-4fa1-4122-9055-dab39f116de4)

However, in jupyterlab v3+, the same code can be rendered successfully.

![image](https://github.com/jupyterlab/jupyterlab/assets/10969537/c4208bb7-0b4d-4f06-ab9f-39bb0a3bc56b)

If I render the same code in https://mathjax.org/#demo, it also renders successfully.
![image](https://github.com/jupyterlab/jupyterlab/assets/10969537/bbaad0c2-da0d-4b44-a823-4ee9244f05e4)

## Reproduce

1. Open a notebook in jupyterlab==4.1.5
2. Create a markdown cell and type `$\textit{hello_world}$`
3. Shift + Enter
4. The markdown cell doesn't render correctly

## Expected behavior

The LaTeX code would render successfully, like jupyterlab v3+ or the mathjax official demo.

**Comment by krassowski** [comment]
It looks like escaping the underscore is needed, like this: `$\textbf{hello\_world}$`. It is intriguing while it does work without escape on the demo page, I guess it has different extensions loaded, possibly something to do with `textmacros`?

**Comment by cnydw** [comment]
@krassowski I think `textmacros` is playing a role here indeed. If I remove `textmacros` from `AllPackages` in https://github.com/jupyterlab/jupyterlab/blob/e1ee2d4d2bd9eb93d25d9c7447e9cfe833e96c7a/packages/mathjax-extension/src/index.ts#L162C9-L162C17 my code snippet renders successfully.

Do you know if it's possible to dynamically remove this package from the `ILatexTypesetter`? From https://docs.mathjax.org/en/latest/input/tex/extensions.html#loading-tex-extensions I see that it's possible to run 

```js
window.MathJax = {
  tex: {packages: {'[-]': ['package_to_remove']}}
};
```
to remove certain packages from MathJax, but it seems it doesn't work for jupyterlab.

**Comment by cnydw** [comment]
@krassowski Thanks, I think escaping underscores is indeed necessary in this case, I would update my old code instead.
