### ISSUE TITLE
When typing in a new shortcuts in shortcut UI, existing shortcuts get triggered

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16066]
## Description

> When testing, I hit the following issue: if you press an existing shortcut when editing the shortcut, the shortcut is actually executed. The most pathological case is setting a shortcut matching the command close tab or activate next/previous tab. I guess we should deactivate the shortcut handling when editing a shortcut.
>
> _Originally posted by @fcollonval in https://github.com/jupyterlab/jupyterlab/pull/16043#pullrequestreview-1961153534_

> I can reproduce this on `main` and in released versions. Yes, that's annoying. Maybe we can create a new issue to track this separately as this is a pre-existing issue?
>
> _Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab/issues/16043#issuecomment-2021007148_
            

## Reproduce

Try to set a shortcut in Setting Editor to Ctrl + B, see that sidebar gets toggled.

## Expected behavior

- Existing shortcuts are muted while user is typing in the shortcut.
   This can be done by adding `data-lm-suppress-shortcuts="true"`
- An integration test case for this is added (because this is a regression which we did not catch for some time).

## Context

In fact, `data-p-suppress-shortcuts` was added for the very purpose in lumino: https://github.com/jupyterlab/lumino/issues/10, however this was never actually used - neither:
- https://github.com/jupyterlab/jupyterlab/pull/5309 (closed), nor
-https://github.com/jupyterlab/jupyterlab/pull/11079

included `data-p-suppress-shortcuts` nor `data-lm-suppress-shortcuts`

- JupyterLab version: 4.1.x

**Comment by krassowski** [comment]
The `data-lm-suppress-shortcuts` attribute should be set somewhere in the `ShortcutInput` component:

https://github.com/jupyterlab/jupyterlab/blob/5af2cc9346a49bc1354448a547413937ab754b56/packages/shortcuts-extension/src/components/ShortcutInput.tsx#L51-L54

**Comment by janengcodes** [comment]
Hi, I'm a student seeing if I claim this issue!

**Comment by milinm** [comment]
Hi, I'm also a student looking to claim this issue if possible

**Comment by krassowski** [comment]
@janengcodes feel welcome to contribute! If needed please ask for help, but most basic things should be covered in https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html

@milinm feel welcome to help with review once @janengcodes opens a PR or to work on other issues. No need to ask for permission if no one is already assigned, and you should be able to self-assign after leaving a comment (ideally please make the comment relevant to the issue by describing how you plan to tackle it, confirming that you are able to reproduce, or asking relevant questions).

**Comment by milinm** [comment]
> Hi, I'm a student seeing if I claim this issue!

Hey @janengcodes I see you are also a student. If you need any help working on this issue, I would love to help. My personal email is milinm@umich.edu and an open to talk through it with you

**Comment by Susilkessav** [comment]
It has been three days, and no pull request has been submitted. I would like to contribute to resolving this issue.

**Comment by krassowski** [comment]
Closing as resolved by https://github.com/jupyterlab/jupyterlab/pull/16126.
