### ISSUE TITLE
Dirty dot goes away after moving a modified cell

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#16060]
## Description

The dirty dot, which appears to the left of a cell that has been modified since it was last executed, disappears when a cell is moved.

## Reproduce

First, create three code cells, and run all of them.

![image](https://github.com/jupyterlab/jupyterlab/assets/93281816/0d9a2cf0-ca29-400c-b138-0fd280c4ec49)

Now, select the second cell, and modify it. Do not run it.

![image](https://github.com/jupyterlab/jupyterlab/assets/93281816/79ae4f3c-5c22-44cc-b2f7-45a9985b25bf)

Use drag and drop to move the second cell below the third cell. Note that the dirty dot and orange color disappear.

![image](https://github.com/jupyterlab/jupyterlab/assets/93281816/51b54db9-2ea5-4258-abfb-c43c159b2081)

## Expected behavior

The second cell, modified, still has the orange color and dirty dot to indicate that it has been modified since it was last run.

## Context

- Operating System and version: macOS 13.6.4 "Ventura"
- Browser and version: Firefox ESR 123.0.1
- JupyterLab version: 4.1.5

**Comment by fcollonval** [comment]
To provide some background, the dirty indicator is a in-memory state comparing the last executed snippet with the current cell content. When moving a cell, we actually delete the old cell and insert a new one (limitation of YJs the [move feature is WIP](https://github.com/yjs/yjs/pull/357) - stuck?). So the in-memory state is lost, hence the current behavior.

**Comment by kguptas** [comment]
Hello - I'm a student trying to contribute. I was looking into this and trying to recreate the issue; however, I don't see a dirty dot when editing even before moving. Is this the expected behavior?

**Comment by krassowski** [comment]
@kguptas no, its not. What version of JupyterLab do you have installed?

**Comment by kguptas** [comment]
@krassowski 4.2.0b0 after running jupyter lab --version. I tried again and it seem to work. For some reason initially it wasn't working for me. Which file should I look to to begin debugging this?

**Comment by krassowski** [comment]
My hunch is that this method may require modification to preserve the dirty state:

https://github.com/jupyterlab/jupyterlab/blob/9aca629a98a1518edcfbca886b0ba7d78e49261a/packages/notebook/src/widget.ts#L378-L422

For reference the dirty state of a cell is defined here:

https://github.com/jupyterlab/jupyterlab/blob/9aca629a98a1518edcfbca886b0ba7d78e49261a/packages/cells/src/model.ts#L640-L650

Of note this is defined on code cell model, not widget so you may need to modify the model (differently to how `rendered` and `headingCollapsed` are defined on the widget level).

**Comment by Alanhou1222** [comment]
I can reproduce the bug, may I work on it? I'll follow what @krassowski suggested to preserve the dirty state.

**Comment by kguptas** [comment]
Oh I've been working a bit on the issue. Let me know if you make progress and we can communicate more about it

**Comment by kguptas** [comment]
I believe I fixed the issue. Are there any existing test we can run to make sure this implementation is sound?

**Comment by kguptas** [comment]
@krassowski thanks for giving us feedback on our PR! Looks like someone else has fixed some of the style issues and provided tests. We can provide more tests if that would still be useful. If there is anything else we can do to resolve this issue, we would be happy to contribute.

**Comment by krassowski** [comment]
Thank you for your contributions @kguptas and @Alanhou1222!
