### ISSUE TITLE
Consider adding additional shortcut for accepting inline completions

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16065]
### Problem

Currently inline completions are accepted using <kbd>Alt</kbd> + <kbd>End</kbd>.

Problems:
- this shortcut is not very convenient to use (<kbd>Alt</kbd> and <kbd>End</kbd> are far away on most keyboards)
- other applications use a different shortcut

Design constraints:
-  using just <kbd>End</kbd> or just <kbd>→</kbd> is not desirable as these would interfere with the native cursor movement behaviour
- ideally there would be a natural variant of the shortcut for partial acceptance (https://github.com/jupyterlab/jupyterlab/issues/15531); for example if the "accept all" is <kbd>Ctrl</kbd>+<kbd>→</kbd>, we could use <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>→</kbd> for word-by-word acceptance (there are also line-by-line and character-by-character options)
- the shortcut should be intuitive to the users coming from other applications:
   - fish uses:
      - <kbd>End</kbd> or <kbd>→</kbd> for full acceptance
      - <kbd>Alt</kbd>+<kbd>→</kbd> or <kbd>Alt</kbd>+<kbd>F</kbd> for word-by-word
   - IPython uses:
       - <kbd>End</kbd> or <kbd>Ctrl</kbd>+<kbd>F</kbd> for full acceptance
       - <kbd>Alt</kbd>+<kbd>F</kbd> for word-by-word
       - <kbd>Ctrl</kbd>+<kbd>→</kbd> for token-by-token (word-by-word but with a better implementation)
       - <kbd>Alt</kbd>+<kbd>→</kbd> for character-by-character
    - Copilot uses:
       - <kbd>Tab</kbd> for full acceptance
       - <kbd>Ctrl</kbd>+<kbd>→</kbd> for word-by-word
- using <kbd>Tab</kbd> might be surprising because we use it to invoke completer
- the shortcut should ideally not interfere with any browser or OS shortcuts

### Proposed Solution

Add a default shortcut other than <kbd>Alt</kbd> + <kbd>End</kbd> for accepting the inline suggestion.

### Additional context

We can keep <kbd>Alt</kbd> + <kbd>End</kbd> to avoid breaking the experience of users that got used to it (we can have multiple shortcuts here).

**Comment by JasonWeill** [comment]
Using any non-alphanumeric character in a shortcut will require us to test with a variety of keyboards, including small keyboards (such as laptop keyboards) and layouts used in Europe and Asia. Not all keyboards include an `End` key, or require chording with a `Fn` key to have the effect of pressing one, for example.
