### ISSUE TITLE
Shortcuts sort does not use locale-specific sort order

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16073]
We should also be sorting using a sort algorithm suitable to the language in question.

_Originally posted by @JasonWeill in https://github.com/jupyterlab/jupyterlab/issues/16039#issuecomment-2020901578_

In particular:

https://github.com/jupyterlab/jupyterlab/blob/5af2cc9346a49bc1354448a547413937ab754b56/packages/shortcuts-extension/src/components/ShortcutUI.tsx#L426-L450

does not use [`String.prototype.localeCompare()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) for string values.

**Comment by krassowski** [comment]
As bonus point, a test for sorting could be added in:

https://github.com/jupyterlab/jupyterlab/blob/5af2cc9346a49bc1354448a547413937ab754b56/packages/shortcuts-extension/test/components/ShortcutUI.spec.ts#L47

but it would not be required of a first-time contributor.

**Comment by UntitledError-09** [comment]
@krassowski, I'd like to pick up this as my first issue. Can you assign this issue to me?

**Comment by krassowski** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/16077
