### ISSUE TITLE
Shortcuts sorting needs a test

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16079]
A test for sorting of shortcuts in the shortcuts table UI:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/18a0b51c-c073-4cb6-a750-f210fbaa129c)

could be added in:

https://github.com/jupyterlab/jupyterlab/blob/5af2cc9346a49bc1354448a547413937ab754b56/packages/shortcuts-extension/test/components/ShortcutUI.spec.ts#L47

it would be good to test sorting by each of the sortable columns (category, column, source, selectors).

**Comment by milinm** [comment]
Hello, I am a student looking to contribute to my first open source project. May I have this issue assigned to me?

**Comment by krassowski** [comment]
Closing as solved by #16098.

@milinm if you would like to work on other [good first issues](https://github.com/jupyterlab/jupyterlab/labels/good%20first%20issue) feel welcome to just open a draft PR, or comment with your plan and self-assign (you can assign yourself after leaving a comment).
