### ISSUE TITLE
Create New Notebook-dialog: file name area cropped

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyterlab/jupyterlab#1609]
The file name text is cropped both at top and bottom of text area:

![screenshot from 2017-02-05 13-24-23](https://cloud.githubusercontent.com/assets/1020496/22626124/c2e4fbaa-eba6-11e6-9ee6-ededd33c80f6.png)

Using latest jupyterlab from conda-forge (v0.15.0), on ubuntu (16.04)

**Comment by blink1073** [comment]
Hi @jorisvandenbossche, thanks for the heads up!  
It looks like this is a Firefox bug: I tried Chrome on Ubuntu and that worked, but Firefox did not.  Much to my surprise, Firefox looks the same on OSX!

**Comment by jorisvandenbossche** [comment]
Yes, indeed using firefox. Forgot to mention that in my bug report :-)
