### ISSUE TITLE
Improve the "Running" sidebar item

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#161]
From today's JupyterLab meeting.

Add a "Running" sidebar item that mimics the "Running" tab in the existing Notebook interface:

<img width="798" alt="screen shot 2016-06-24 at 1 36 57 pm" src="https://cloud.githubusercontent.com/assets/2096628/16347146/c7e8809c-3a10-11e6-84e0-9a42a583f74c.png">

- [x] List open Consoles.
- [ ] List open text editors.
- [ ] Allow third-party types to be added (name, icon, click handler)

**Comment by fperez** [comment]
I've created a ["0.99"](https://github.com/jupyter/jupyterlab/milestone/1) milestone so we can start using that to target the key feature set and bugs we should really focus on right now, vs other stuff that can come later.

I think this fits in that category.  We can discuss further what to call it, and I deliberately didn't call it "1.0" as I think that should come with a higher level of polish.  But I want a triage target that's low enough to be possible to meet in reasonably short order, yet serious enough that at that point we'll have a largely usable system.

I also made a [1.0 milestone](https://github.com/jupyter/jupyterlab/milestone/2), this should indicate much more API stability and nearly zero (ideally zero) regressions or missing features, as well as a proven path for extension porting.

Having both of this will hopefully let us triage stuff more effectively, I feel we're reaching the point where open issues are starting to pile up...

**Comment by fperez** [comment]
This is already looking great, thanks! 

I just wanted to note that ideally, I think it should (feel free to move this list up to the issue description so we can use it to track the completeness if you agree):

- [ ] Allow opening of all listed activities by clicking on them.
- [ ] List open Consoles.
- [ ] List open text editors.

**Comment by fperez** [comment]
Also, shouldn't it be on the same side as the `Commands` and `Files` tabs? Now it's on the other side which looks a bit odd and also uses extra real estate...

**Comment by blink1073** [comment]
I have no opinion on the location, I put it on the right to show diversity in the application for now.

**Comment by jasongrout** [comment]
The only feature parity thing left here is "Allow opening of all listed activities by clicking on them.". All the rest are enhancements.

**Comment by blink1073** [comment]
Thanks @jasongrout, I updated the title and description.

**Comment by dhirschfeld** [comment]
I was just about to open an issue requesting that the Running tab allow you to double click a notebook to open it but came across this issue, so consider this a :+1:!

**Comment by ellisonbg** [comment]
We now have the "Tabs" tab that lists all open documents and activities. The main things we want to add to running now are to open the console when you click on it.

**Comment by blink1073** [comment]
Fixed by #2298.
