### ISSUE TITLE
An extension disabled at the sys-prefix level can't be enabled at the user level

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#16101]
## Description
If an extension is enabled at the sys-prefix level, it can't be enabled at the user level. 

## Reproduce

Disable an extension at the sys-prefix level and try to enable it at the user level. 

## Expected behavior
Users should be able to opt into using extensions that have been disabled at the sys-prefix level

## Context

- JupyterLab version: v4.1.5

**Comment by krassowski** [comment]
Reopening as #16102 did not actually fix this.

**Comment by brichet** [comment]
Duplicate of https://github.com/jupyterlab/jupyterlab/issues/15574

**Comment by brichet** [comment]
Thanks for working on this issue.
I still can't enable an extension at `user` level if it has been disabled at `sys_prefix` level.

For example with the following commands:
```bash
jupyter labextension disable --level=sys_prefix @jupyterlab/notebook-extension
jupyter labextension unlock --level=sys_prefix @jupyterlab/notebook-extension
jupyter labextension enable --level=user @jupyterlab/notebook-extension
```

The respective `page_config.json` files are correctly populated, but the extension is still not enabled:
- **sys_prefix level:**
```bash
$ cat ~/mambaforge/envs/jupyterlab/etc/jupyter/labconfig/page_config.json 
{
  "disabledExtensions": {
    "@jupyterlab/notebook-extension": true
  },
  "lockedExtensions": {
    "@jupyterlab/notebook-extension": false
  }
}
```
- **user level:**
```bash
$ cat ~/.jupyter/labconfig/page_config.json 
{
  "disabledExtensions": {
    "@jupyterlab/notebook-extension": false
  }
}
```

Did I missed something ?

**Comment by brichet** [comment]
IIUC the `page_config.json` files are loaded with *jupyterlab_server* in [config.py -> get_static_page_config](https://github.com/jupyterlab/jupyterlab_server/blob/1e0367f5daf66c8c4a9fdccd66320b3006830770/jupyterlab_server/config.py#L76).
It uses the `ConfigManager` from *jupyter_server*, which read the config files from ['back to front' of the list](https://github.com/jupyter-server/jupyter_server/blob/af1342df16963b952374b9cb110db2121423f24f/jupyter_server/services/config/manager.py#L27).
This means that the `sys_prefix` one is the latest to be read, and overwrite the `user` one.

If it is correct and unexpected, we could add an option in the `ConfigManager` to allow the file list to be read in reverse order.

**Comment by divyansshhh** [comment]
Are you using this in a venv? What’s the output of `jupyter —paths`?

**Comment by divyansshhh** [comment]
It seems this is because the venv  config path gets higher priority than the local path. I've experienced this too and to work around it, I launch jupyterlab by passing the `--config` flag. Something like this should work for you -

```bash 
jupyter-lab --config=/home/brichet/.jupyter
```

I'm not sure if this order for reading the configs is by design or a regression.

**Comment by brichet** [comment]
> It seems this is because the venv config path gets higher priority than the local path.

Not sure to understand what you mean by "venv config path" VS "local path".
For what I understand, the `sys_prefix` path has higher priority than the `user` path, which would mean that there is no way to enable an extension at user level if it has been disabled at sys_prefix level.

It is probably expected if "lock" is `true` at a higher level, but otherwise we should be able to enable an extension at user level.
I believe that the "lock" flag should not be used only to enable writing or not the lower level config file, but also to allow overwriting higher config with lower config at run time.

BTW thanks for the workaround, but it doesn't work for me either.

**Comment by divyansshhh** [comment]
>Not sure to understand what you mean by "venv config path" VS "local path".

I meant `venv config path=sys_prefix` and `local path=user`.  I think this can be another issue to debug this.
