### ISSUE TITLE
Items in main menu bar slightly too low

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#16108]
In Notebook 7.1 and Lab 4.2 beta, items in main menu bar are 1–2 pixels below the center.

In JupyterLab (top) and Jupyter Notebook (bottom) you can see that the pulldown menus have a very similar appearance.

![image](https://github.com/jupyter/notebook/assets/93281816/bf9c62f7-c37f-427a-b4c3-824a57c63979)

The code seems to be imported from the `@jupyterlab/application` package:

https://github.com/jupyterlab/jupyterlab/blob/41be86d5142a793ab9cb8b9eb99f92a33c8dc441/packages/application/style/menus.css#L33-L39

This was originally found by @ellisonbg during a bug bash for Notebook 7.0.0a17, and reported in https://github.com/jupyter/notebook/issues/6786 .

**Comment by krassowski** [comment]
So this is because the `.lm-MenuBar-item` should be 27px tall, not 28px. It should be 27px tall because the menubar has 1px used up by the border-bottom as defined here:

https://github.com/jupyterlab/jupyterlab/blob/9aca629a98a1518edcfbca886b0ba7d78e49261a/packages/application/style/core.css#L46-L51

So I think we need to change:

```diff
-   line-height: calc(var(--jp-private-menubar-height) - var(--jp-border-width)); 
+   line-height: calc(var(--jp-private-menubar-height) - var(--jp-border-width) * 2); 
```

**Comment by JasonWeill** [comment]
I had been planning to remove the `border-top` from `lm-MenuBar-item`, which would take the menu bar from this:

![image](https://github.com/jupyterlab/jupyterlab/assets/93281816/7edeefcb-d73a-4306-ab87-52104bd1914e)

… to this, which is as centered as text could be in an odd-sized container without resorting to half-pixel rendering:

![image](https://github.com/jupyterlab/jupyterlab/assets/93281816/11ea385c-f56e-4f4f-98a7-f64490c457df)

**Comment by smbrett** [comment]
Hi I am a student looking to work on a good first issue. Is it possible for you to assign this to me?

**Comment by JasonWeill** [comment]
@smbrett Sure, I can assign this to you! Please `@`-mention me in a comment if you have any questions.

**Comment by smbrett** [comment]
@JasonWeill Thank you very much! Is there a discord or other channel of communication I could use?

**Comment by JasonWeill** [comment]
You can find a list of community resources here: https://jupyter.org/community

We don't have an official Discord, but you can find an official chat room for JupyterLab here: https://gitter.im/jupyterlab/jupyterlab
