### ISSUE TITLE
The workspaces context menu test keeps failing more often than not

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16106]
Recurring failure:

```
Notice:   1 failed
    [documentation] › test/documentation/workspaces.test.ts:35:7 › Workspaces sidebar › Workspaces context menu 
```

https://github.com/jupyterlab/jupyterlab/pull/16072 was meant to fix that but it was clearly not sufficient.

| Actual | Expected |
|--|--|
| ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/b246e126-604d-4508-9f16-a80b6162a6b7) | ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/d1a4ac75-5f5d-477d-8f22-2b522028ed87) |

**Comment by milinm** [comment]
Hello, I'm a student looking for my first issue. Is is possible to have this issue assigned to me?

**Comment by krassowski** [comment]
This may be a harder one, but if you have some experience with playwright sure go for it. You should be able to self-assign after commenting.
