### ISSUE TITLE
Test Minimal version fails

### ISSUE THREAD

**Issue by brichet** [jupyterlab/jupyterlab#16115]
Probably related to https://github.com/jupyterlab/jupyterlab/pull/16105

## Description

The minimal version test seems to be broken for resolution conflict (which seems not conflicting AFAIK):

```
INFO: pip is looking at multiple versions of jupyterlab to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install None because these package versions have conflicting dependencies.

The conflict is caused by:
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
    jupyterlab 4.2.0b0 depends on traitlets>=3.0
    The user requested (constraint) traitlets==3.0
```

## Context

Some failures:
- https://github.com/jupyterlab/jupyterlab/actions/runs/8566306777/job/23475831875?pr=15422
- https://github.com/jupyterlab/jupyterlab/actions/runs/8566932012/job/23479393846?pr=16111

**Comment by krassowski** [comment]
Yeah, now everything fails. The changes in maintainer tools were reverted after discussion in https://github.com/jupyterlab/maintainer-tools/issues/230. Let's try reverting https://github.com/jupyterlab/jupyterlab/pull/16105.
