### ISSUE TITLE
linux test: js-coreutils Process completed with exit code 139

### ISSUE THREAD

**Issue by FoSuCloud** [jupyterlab/jupyterlab#16125]
## Description

linux test: js-coreutils 
The failure occurred during the base setup phase, with the message: "Process completed with exit code 139."
[job](https://github.com/jupyterlab/jupyterlab/actions/runs/8578237170/job/23511843429?pr=16124)
## Context

</details>

**Comment by krassowski** [comment]
It passes [after restarting it](https://github.com/jupyterlab/jupyterlab/actions/runs/8578237170/job/23515751689?pr=16124),

I noticed a similar behaviour across other jobs, randomly failing in the `Base Setup` step, for example:
- `js-rendermime` failing [here](https://github.com/jupyterlab/jupyterlab/actions/runs/8572417334/job/23494920240) but passing [after restart](https://github.com/jupyterlab/jupyterlab/actions/runs/8572417334)
- `js-services` failing [here](https://github.com/jupyterlab/jupyterlab/actions/runs/8573997073/job/23499899144) but passing [after restart](https://github.com/jupyterlab/jupyterlab/actions/runs/8573997073)

I think it started very recently, maybe yesterday, definitely not more than a few days ago. I wonder if this is related to the latest set of maintainer-tools releases.

**Comment by FoSuCloud** [comment]
> It passes [after restarting it](https://github.com/jupyterlab/jupyterlab/actions/runs/8578237170/job/23515751689?pr=16124),
> 
> I noticed a similar behaviour across other jobs, randomly failing in the `Base Setup` step, for example:
> 
> * `js-rendermime` failing [here](https://github.com/jupyterlab/jupyterlab/actions/runs/8572417334/job/23494920240) but passing [after restart](https://github.com/jupyterlab/jupyterlab/actions/runs/8572417334)
> * `js-services` failing [here](https://github.com/jupyterlab/jupyterlab/actions/runs/8573997073/job/23499899144) but passing [after restart](https://github.com/jupyterlab/jupyterlab/actions/runs/8573997073)
> 
> I think it started very recently, maybe yesterday, definitely not more than a few days ago. I wonder if this is related to the latest set of maintainer-tools releases.

Thanks, it works after restarting
