### ISSUE TITLE
Check links job started failing on CI

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16133]
It seems a service that was used to upload some GIFs is no longer there:

```
_ /home/runner/work/jupyterlab/jupyterlab/packages/vega5-extension/README.md: http://g.recordit.co/USoTkuCOfR.gif _
http://g.recordit.co/USoTkuCOfR.gif: 404: Not Found
_ /home/runner/work/jupyterlab/jupyterlab/packages/json-extension/README.md: http://g.recordit.co/mqve0QPqyM.gif _
http://g.recordit.co/mqve0QPqyM.gif: 404: Not Found
_ /home/runner/work/jupyterlab/jupyterlab/packages/statusbar-extension/README.md: http://g.recordit.co/OndGalRjws.gif _
http://g.recordit.co/OndGalRjws.gif: 404: Not Found
_ /home/runner/work/jupyterlab/jupyterlab/packages/statusbar-extension/README.md: http://g.recordit.co/jT0NA6D9c9.gif _
http://g.recordit.co/jT0NA6D9c9.gif: 404: Not Found
```

One would need to check webarchive to see if these can be recovered and either upload them on GitHub, or include in the repo if we do want to keep these GIFs, and then change the links in the files listed above.

**Comment by amitduaaa** [comment]
Hi this looks like a good first issue. I would like to take this up. Thanks.

**Comment by kainzc** [comment]
Hi @krassowski,

I'll look into this. Will keep you posted!

**Comment by krassowski** [comment]
@amitduaaa did you look into this?

**Comment by amitduaaa** [comment]
@krassowski Apologies! I thought it will be assigned to me first. I did check the provided links on Wayback Machine to see if there's an older version available but looks like none of the link's is archived there.

**Comment by MartiPresa** [comment]
is this issue still available?

**Comment by krassowski** [comment]
No one opened a PR so far so I would say yes. Since it looks the files cannot be recovered, I would suggest to remove links to these gifs.

**Comment by Tanmay-Deshmukh** [comment]
I removed the links and submitted a pull request, please take a look at it whenever you can!

**Comment by krassowski** [comment]
Closing as resolved by https://github.com/jupyterlab/jupyterlab/pull/16151
