### ISSUE TITLE
one-line execute occur memory leak

### ISSUE THREAD

**Issue by TeusEE** [jupyterlab/jupyterlab#16139]
## Description

https://github.com/numpy/numpy/issues/26225
while i testing numpy c interface

i found that if some python func generate data in function, and eexecute it with one-line execute
```python
import numpy as np
import gc
cnt = 100000000
dt1 = np.ones(cnt, dtype = np.int32)
dt2 = np.ones(cnt, dtype = np.int32)



def np_gen(_a, _b):
    _ret = np.ones(100000000, dtype = np.int32)    
    try:
        return _ret
    finally:
        while gc.collect():
            print("collect gcing...")   


def list_gen(_a, _b):
    _ret = [i for i in range(cnt)]
    try:
        return _ret
    finally:
        while gc.collect():
            print("collect gcing...")
```
execute with one-line like below
![image](https://github.com/jupyterlab/jupyterlab/assets/79349894/1f967965-ea74-4b88-8837-084e4bb9ff83)

after that, increased memory usage never decrease after that
![image](https://github.com/jupyterlab/jupyterlab/assets/79349894/de949ab1-1ffc-4ec0-a6bb-f135c2461dd3)
first, i think this is about numpy issue, but make python in func also same issue happen

i think python can't garbage collect the returned Array if i execute in jupyterlab one-line execute.

it this intended..?

please review.

## Reproduce

1. open new ipynb file
2. execute below code
```python
import numpy as np
import gc
cnt = 100000000
dt1 = np.ones(cnt, dtype = np.int32)
dt2 = np.ones(cnt, dtype = np.int32)



def np_gen(_a, _b):
    _ret = np.ones(100000000, dtype = np.int32)    
    try:
        return _ret
    finally:
        while gc.collect():
            print("collect gcing...")   


def list_gen(_a, _b):
    _ret = [i for i in range(cnt)]
    try:
        return _ret
    finally:
        while gc.collect():
            print("collect gcing...")
```
3. execute `np_gen(dt1, dt2)` with one line Repeatedly
4. python interpreter occur memory leak!

## Context

- Operating System and version:  windows 10 enterprise LTSC(1809. 17763.4851)
- Browser and version:  Edge 123.0.2420.81
- JupyterLab version:   4.0.10

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by TeusEE** [comment]
if i execute like `np_gen(dt1, dt2);print(1)` or `display(np_gen(dt1, dt2))`, python GC act correctly

and if i execute with for-loop, also never happen memory leak.
```python
import numpy as np
import gc
cnt = 100000000
dt1 = np.ones(cnt, dtype = np.int32)
dt2 = np.ones(cnt, dtype = np.int32)



def np_gen(_a, _b):
    _ret = np.ones(100000000, dtype = np.int32)    
    try:
        return _ret
    finally:
        while gc.collect():
            print("collect gcing...") 

for _ in range(10)
    np_gen(dt1, dt2)
```

**Comment by seberg** [comment]
@TeusEE it is a feature of IPython, that it remembers results from cells as `_1`, etc.  (I am not sure if there is a mechanism to not remember it forever).

**Comment by krassowski** [comment]
Exactly as @seberg says. You can use the [%reset](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-reset) and [%xdel](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-xdel) magics to clear output.

Also, did you try to see if you get the same behaviour in IPython when started from terminal? If yes, I would suggest to close this issue (and if you have further questions/suggestions - open one in IPython) because to me it seems unrelated to JupyterLab itself.

**Comment by TeusEE** [comment]
@seberg @krassowski 
thanks. as you suggest, i test same code in IPython Shell in command prompt. same issue occur😮. 
magic command %reset can reset varaible memory, but remove all variable.
%xdel can not remove this issue because there are any varable for returned array.
i will open Issue in IPython repo.
Thank you

**Comment by TeusEE** [comment]
.
