### ISSUE TITLE
cell created in wrong location (above VS below, and vic.)

### ISSUE THREAD

**Issue by ggrrll** [jupyterlab/jupyterlab#16148]
## Description

when creating a new cell above cell 'x' (below) , sometimes it does the opposite, creating it below (above) , both with key. shortcut and click on cell-toolbar button
(and when moving with arrows, it skips the reference cell 'x')

## Context

- Operating System and version: macOS 14.1.2 (23B92)
- Browser and version: [Version 1.64.116 Chromium: 123.0.6312.105 (Official Build) (x86_64)](https://brave.com/latest/)
- JupyterLab version: 4.1.4
- notebook: 7.1.1

## console errors

I have many errors, here are a couple -- not sure if relevant

![image](https://github.com/jupyterlab/jupyterlab/assets/15370425/9b26c68d-b692-4cc0-b87f-ecdb64c66fa0)

thanks!

**Comment by krassowski** [comment]
I think this may have been fixed as a side effect of `&& widget !== this._willBeRemoved)` addition in https://github.com/jupyterlab/jupyterlab/pull/16013.

Would you be able to test the latest 4.2.0 beta?

**Comment by ggrrll** [comment]
thanks
it's a bit difficult, as we work with a specific env, which we do not update often ...anyway, looking forward to see that fix in the main release :)

**Comment by FoSuCloud** [comment]
@ggrrll Can you provide a reproduction video?
I did not find this problem in version 4.2.0b1

**Comment by JasonWeill** [comment]
@ggrrll Could you please provide a video if you can still reproduce this? If you could try with a 4.2.0 beta version, that would help as well. I appreciate your help!

**Comment by ggrrll** [comment]
Hi, 

sorry, busy days a work -- don't worry, if you understood the problem and you fixed it in the new v., then I will update it
(I will have to push the new v. internally, in our working env.)
