### ISSUE TITLE
Launcher has unused optional `factory` dependency

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16165]
https://github.com/jupyterlab/jupyterlab/blob/62dcce81e6cb3466b9e75a2b93f266ad6982e99d/packages/launcher-extension/src/index.ts#L65

Is not used in the activate function. I think it should have been removed in #13786 which refactored the extension to use the default browser instead.

**Comment by milinm** [comment]
Hi, I am a student looking to work on a good first issue. May I have this issue assigned to me?
