### ISSUE TITLE
Custom.js file not executed

### ISSUE THREAD

**Issue by jeano888** [jupyterlab/jupyterlab#16175]
## Description

I am running jupyterlab in a docker container, here is the docker-compose file :
```
version:  '3'
services:
  datascience-notebook:
      image: jupyter/datascience-notebook
      container_name: jupyter_notebook
      volumes:
        - /home/user/docker_volumes/jupyterlab/work:/home/jovyan/work
        - /home/user/docker_volumes/jupyterlab/.jupyter/custom:/home/jovyan/.jupyter/custom
      ports:
        - 8888:8888
      command: "start-notebook.sh \
        --ServerApp.token='' \
        --ServerApp.password='' \
        --ServerApp.disable_check_xsrf=True \
        --ServerApp.allow_remote_access=True \
        --ServerApp.port=8888 \
        --ServerApp.open_browser=False \
        --ServerApp.allow_origin='*' \
        --ServerApp.tornado_settings='{\"headers\":{\"Content-Security-Policy\":\"frame-ancestors \'self\' *\"}}'"
```

 /home/jovyan/.jupyter/custom/custom.js :
```
alert("hi from custom.js")
console.log("hi from custom.js")
```

For some reason, this file is not executed when jupyter is loaded in my browser (nothing the browser’s console, and no alert) both when directly opening jupyter lab’s page and when loaded into an iframe on another page.

I tried reloading the webpage and restarting the container, both didn’t work.
Tried on both firefox and chrome.

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
https://pastebin.com/DjyZyU2a
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
https://pastebin.com/68HV3q9M
</pre>
</details>

**Comment by erkin98** [comment]
did you introduce custom.js via extension?

**Comment by jeano888** [comment]
> did you introduce custom.js via extension?

I just created it in `/home/jovyan/.jupyter/custom/` manually

**Comment by erkin98** [comment]
> > did you introduce custom.js via extension?
> 
> I just created it in `/home/jovyan/.jupyter/custom/` manually

you should create custom extension and serve via it, otherwise that is not going to work

**Comment by erkin98** [comment]
what is your end goal?

**Comment by jeano888** [comment]
> what is your end goal?

I embedded jupyterlab into an iframe on a webpage, and would like to send data from the webpage and add it into a cell of the current notebook

**Comment by erkin98** [comment]
> is there some documentation about this ? how should I go about "serving it" via a custom extension ? also, from forum posts, it seemed to be possible to use it without a custom extension, just like on this post : https://sorse.github.io/blog/embedding-a-jupyter-notebook/

this blog post is outdated since this post there is lots of breaking and api changes
https://jupyter-server.readthedocs.io/en/stable/developers/contents.html

**Comment by erkin98** [comment]
https://github.com/jupyterlab/extension-examples
