### ISSUE TITLE
Incorrect disposal of LSP connection due to access to undefined `serverRequests`

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16185]
## Description

Sometimes when switching kernels I see an uncaught error:

```ts
connection.ts:271 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at LSPConnection.dispose (connection.ts:271:12)
    at DocumentConnectionManager.unregisterDocument (connection_manager.ts:428:20)
    at NotebookAdapter.disconnect (adapter.ts:304:30)
    at NotebookAdapter.reloadConnection (adapter.ts:397:10)
    at NotebookAdapter.onKernelChanged (notebooklspadapter.ts:209:12)
```

This is raised from:

https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/lsp/src/connection.ts#L267-L273

and happens because `serverRequests` have no initializer in constructor nor in class definition: 

https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/lsp/src/connection.ts#L229-L232

These are only initialized after server initialization in `afterInitialized`:
 
https://github.com/jupyterlab/jupyterlab/blob/2ceabd8c7b98e7b2c305be406ade799f387a90eb/packages/lsp/src/connection.ts#L481-L483

## Expected behavior

- Disposal of connections which have not yet initialized does not raise an error.
- There is a unit test case for this scenario

## Context

- JupyterLab version: 4.1.5

**Comment by AnanthaKrishnan63** [comment]
Is this issue still open? If so, I would like to open a PR with my solution to it.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/16834, thanks!
