### ISSUE TITLE
Search/filter boxes do not update when typing

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16193]
## Description

Testing locally after merge of https://github.com/jupyterlab/jupyterlab/pull/16046 - the search/filter boxes only take effect after `onblur`.

From a quick look there is `<Search onChange=` and previously there was `<InputGroup onChange=`

My guess is that this the `Search` component does not call the callback on every keystroke compared to the `<input` that we used previously?

> Unlike the [input](https://developer.mozilla.org/en-US/docs/Web/API/Element/input_event) event, the change event is not necessarily fired for each alteration to an element's value.

CC @fcollonval @Mehak261124 

## Reproduce

![search-boxes-take-too-long](https://github.com/jupyterlab/jupyterlab/assets/5832902/fa55a218-006e-4aeb-a992-585c2c4b4cb2)

## Expected behavior

Search filter boxes take effect as user types as in 3.x and 4.0 and 4.1

## Context

- JupyterLab version: 4.2.0b2

**Comment by fcollonval** [comment]
Thanks @krassowski 

I forgot about that but indeed we need to also bind the onInput event like in search-replace extension:

https://github.com/jupyterlab-contrib/search-replace/blob/main/src/view.tsx#L722

I'll try to open a PR this afternoon/evening
