### ISSUE TITLE
Changing a second shortcut changes the first one in shortcuts editor

### ISSUE THREAD

**Issue by kolibril13** [jupyterlab/jupyterlab#16211]
After `pip install -U --pre jupyterlab` on a Mac, adding a second shortcut does not work:

https://github.com/jupyterlab/jupyterlab/assets/44469195/06516d55-18ea-481c-aa3b-9a1ed89b579e

this was first reported in https://github.com/jupyterlab/jupyterlab/issues/16186#issuecomment-2067649537 and confirmed by @krassowski :

> I can reproduce this, it is a bug. I think it deserves its own issue as it is not Mac specific.

**Comment by krassowski** [comment]
My comment saying that I can reproduce was on:

> changing the second shortcut does not work: it changes the first shortcut instead

There was no mention of adding a second shortcut, just editing. So I will edit the title to reflect it. I assume by shortcuts menu you meant shortcuts editor?

**Comment by kolibril13** [comment]
yep, thanks for the clarification!

**Comment by krassowski** [comment]
@kolibril13 this should be fixed by https://github.com/jupyterlab/jupyterlab/pull/16214. Can you test this on Binder and leave a review on the PR? https://mybinder.org/v2/gh/krassowski/jupyterlab/fix-changing-second-default-shortcut?urlpath=lab
