### ISSUE TITLE
Search highlight does not move to next cell when replacing `a` with `aa`

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16242]
## Description

Even after https://github.com/jupyterlab/jupyterlab/pull/15881

## Reproduce

![tricky](https://github.com/jupyterlab/jupyterlab/assets/5832902/f719cbc7-f659-46fe-af13-749c23b5ee3f)

## Expected behavior

Moves between cells

## Context

- JupyterLab version: 4.2.0rc0

**Comment by JasonWeill** [comment]
I can reproduce this. #15881 fixed the issue where the replacement text matches the source text, but not where the replacement text matches the source text _twice_. 🤦
