### ISSUE TITLE
Duplicated content when pressing enter in markdown cell

### ISSUE THREAD

**Issue by EricHUANG970823** [jupyterlab/jupyterlab#16266]
Duplicated content when pressing enter in markdown cell. this seems to be the problem with the latest version V4.1.8

https://github.com/jupyterlab/jupyterlab/assets/97007177/539d125d-f653-41cf-a9ec-4d088af2249d

**Comment by JasonWeill** [comment]
@EricHUANG970823 Thanks for opening this issue! Are you using an input method editor (IME) with JupyterLab? If so, which IME (language, etc) are you using? In addition, could you please share info about which operating system and browser (including versions) you're using? I just tried this with a tip-of-`main` build and a Japanese IME on Firefox for macOS, and I couldn't reproduce it.

**Comment by EricHUANG970823** [comment]
Hi there, yes I use Chinese IME (sogou). However, I think IME is not the problem. When I changed to the Mac default English editor, the problem remained.

Edge 124.0.2478.67
macOS Sonoma 14.4.1

**Comment by JasonWeill** [comment]
Thanks! Does this happen with any other browsers on your system? If you have any content-modifying extensions installed, does the problem persist if you use Edge without extensions, such as in a private window?

**Comment by EricHUANG970823** [comment]
thank you for your suggestion! I create a new env without any extension. problem is resolved. no problem with Jupyterlab itself.
