### ISSUE TITLE
Unable to import numpy package after Ubuntu upgrade

### ISSUE THREAD

**Issue by UriBarkan** [jupyterlab/jupyterlab#16267]
Hi, 

**Description:**
Last week I upgraded to Ubuntu 24.04. After the upgrade, when trying to import numpy (for example) in JupyterLab, I get the following message:
`ModuleNotFoundError: No module named 'numpy'`

![Screenshot Jupyterlab debug](https://github.com/jupyterlab/jupyterlab/assets/127536620/06be039a-1a5f-4934-ba0a-2d4f1f07e6d4)

When I run Python from terminal or when I try importing the same package on Jupyter notebook, even on the same browser, import is successful. Also, if I open terminal within jupyter-lab (from the launcher) import is also successful. So import fails only when importing from notebooks (tried from different ones).

Disabled all plugins. Also, tried to reinstall jupyter-lab (“pipx reinstall jupyterlab”), to no avail.

**Reproduce:**
1. Install Jupyterlab and numpy on Ubuntu 23.10 machine.
2. Upgrade to Ubuntu 24.04.
3. Launch Jupyterlab from terminal.
4. type "import numpy as np" in jupyterlab and run the cell.

Expected behavior: 
numpy to load successfully.

**Context:**
OS: Linux Ubuntu 24.04.
Brwoser: Chromium Version 124.0.6367.60 (Official Build) snap (64-bit)
Also tested on Firefox 125.0.3 (64-bit) and got the same error
Jupyterlab 4.1.8 
Jupyter-notebook 6.4.12 (the error is not reproducible in Jupyter-notebook, only in Jupyterlab)
Python 3.12.3

**Troubleshoot output:**
bash: /x/y/.local/bin/jupyter-troubleshoot: cannot execute: required file not found
For 'jupyter-lab --debug' please see attached text file:
[jupyter lab debug.txt](https://github.com/jupyterlab/jupyterlab/files/15168739/jupyter.lab.debug.txt)
For browser output see the screenshot:
![Screenshot Jupyterlab debug browser](https://github.com/jupyterlab/jupyterlab/assets/127536620/580a9699-e327-48f0-b3b5-2cde0e84bd8d)

Thanks!

**Comment by UriBarkan** [comment]
Hi @JasonWeill,

Thanks for your reply! I can import numpy also in ipython (e.g. in Spyder IDE w/ ipython console). Up to now I've encountered this problem only in Jupyterlab.

**Comment by JasonWeill** [comment]
If you run `%pip install numpy` from within your notebook, what output do you see? After you run this command, can you successfully import `numpy`?

**Comment by UriBarkan** [comment]
From within jupyterlab:

```
!pipx install numpy
⡿ installing numpy environment⚠️  Note: f2py was already on your PATH at /usr/bin/f2py
  installed package numpy 1.26.4, installed using Python 3.12.3
  These apps are now globally available
    - f2py
done! ✨ 🌟 ✨

import numpy as np
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[4], line 1
----> 1 import numpy as np

ModuleNotFoundError: No module named 'numpy'
```

**Comment by JasonWeill** [comment]
Thanks for your reply! After installing the module, can you try restarting the kernel? After that kernel is restarted, does the `import numpy as np` line work as intended?

**Comment by UriBarkan** [comment]
Unfortunately no, nympy cannot be imported also after kernel restart.

**Comment by UriBarkan** [comment]
I was able to overcome the issue by redefining the virtual environment. I guess in the upgrade process of Ubuntu something broke. 

A fix for future users:

1. Define a new virtual environment: python3 -m venv /my/venv/directory
2. Activate: source /my/venv/directory/bin/activate
3. Install: pip install jupyterlab
4. Install other packages required: pip install <numpy>/<scipy>/etc.
