### ISSUE TITLE
Inquiry: Disabling Automatic Cell Selection in Notebook

### ISSUE THREAD

**Issue by lokashrinav** [jupyterlab/jupyterlab#16279]
### Problem

I'm always frustrated when I run my cell code block because the focus automatically goes to the next cell unnecessarily
I would like it if there was a feature such that when I run a cell block, the focus doesn't shift because it makes things more convenient

### Proposed Solution

Add an option in settings so that when I run my cell block, the focus stays on that

**Comment by JasonWeill** [comment]
@lokashrinav Thank you for opening this issue! You can run a cell and _not_ advance in a few ways, notably by pressing <kbd>CTRL+ENTER</kbd>. You can also customize your shortcuts in the settings editor.
