### ISSUE TITLE
Resolve Inconsistency: "Shutdown" Kernel vs. "Halt"

### ISSUE THREAD

**Issue by sgornick** [jupyterlab/jupyterlab#1628]
A menu option under the Notebook pull-down menu is:   "Notebook -> Close and Halt"
There is also a command "Close and Halt".

However if you are in the filebrowser and right click on a Notebook, there is the option to Shutdown Kernel.

Are these two ("Halt" and "Shutdown kernel") not the same thing?

If so, then the presentation is inconsistent.

I became aware of this inconsistency when I went to the command console but didn't find anything for "Shutdown".

(Incidentally, the "Close and Halt" command and menu option was added recently -- see Issue #1290)

**Comment by ellisonbg** [comment]
+1 on Close and Shutdown
