### ISSUE TITLE
Close and Halt command makes unexpected guess when no notebook tab selected

### ISSUE THREAD

**Issue by sgornick** [jupyterlab/jupyterlab#1629]
The Close and Halt command (or menu option) will close the currently selected Notebook in the landing.   But if the selected tab in the landing is not a notebook, then Close and Halt appears to choose the last Notebook instance shown in "Running" console.

This may not always be what the user was expecting.

Close and Halt only functions against a Notebook, so even if a Code Console or Terminal tab is open in the landing area, it is only a Notebook that gets closed.

Shouldn't the "Close and Halt" command then only work if a Notebook is selected in the Landing?     (i.e., it shouldn't try to guess which notebook the user had wanted to close.)

I found this to be a problem when trying to shutown my Terminal.  I had the target Terminal tab selected, but after entering the Close and Halt command what got closed and halted was my notebook -- something I hadn't expected nor wanted.   In hindsight, the "Close and Halt" command did show under the "Notebook Operations" subheading, so I should then have realized this wasn't how to close a Terminal, but since "Close and Halt" can be a destructive action, it's behavior probably shouldn't remain seemingly ambiguous.

**Comment by blink1073** [comment]
We've been applying actions to the most recently used of a given widget.  In this case, we should focus the notebook in question and provide a dialog since it is a destructive action.

**Comment by ellisonbg** [comment]
+1 on focus and dialog confirmation...
