### ISSUE TITLE
InlineCompleter only runs when  cursor is at the end of a line

### ISSUE THREAD

**Issue by ajbozarth** [jupyterlab/jupyterlab#16295]
## Description

The inline completer will only be invoked when run from the end of a non-empty line. This is caused by the following chunk of code:

https://github.com/jupyterlab/jupyterlab/blob/f14c89145d697974ecbd02872643b530381d90b6/packages/completer/src/handler.ts#L462-L465

Based on the inline comment, that chunk of code should only run when `trigger` is `Automatic`, not when it's `Invoke`

## Reproduce

1. Enable an inline completer
2. Invoke the inline completer on a notebook cell or file when the cursor is not at the end of a line
3. Note that nothing happens
4. Compare to running at end of line

## Expected behavior

The inline completer should run when the command is executed, no matter where the cursor is

## Solution

Add a check for `trigger === Automatic` in the if statement

**Comment by krassowski** [comment]
Sounds good 👍
