### ISSUE TITLE
Ignore Keypress for input in custom HTML elements

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#1630]
Hi, 

I have created an HTML form element in lab, but I'm not able to enter anything in the text boxes without triggering a shortcut key. Is there a way to ignore shortcuts when pressing the key while entering text in a custom element?

**Comment by sccolbert** [comment]
You can trap the `keydown` events and call `stopPropagation` on the event object so they do not get handled by anything else on the page.

**Comment by sccolbert** [comment]
Another option would be for us to change the keymap to ignore `keydown` events generated by `input` fields, but I think that would be a short-sighted solution.

@blink1073 @afshin

**Comment by blink1073** [comment]
We are doing the trapping in output areas: https://github.com/jupyterlab/jupyterlab/blob/4a225e43f7025c34b88faa9fcf00d593f5a217de/src/outputarea/widget.ts#L868.

ipywidgets is using a similar approach: https://github.com/ipython/ipywidgets/blob/e345086b95dc04e71adb5170f8699df4b23a7f50/jupyter-js-widgets/src/widget_string.ts#L182

**Comment by sccolbert** [comment]
Yep. The problem with "assuming" that input elements should be ingored by the keymap is that it makes it impossible for inputs who want shortcuts, to have them.

**Comment by rsinha25** [comment]
Thanks! I shall try this.

**Comment by blink1073** [comment]
@rsinha25, this behavior is fixed by #1729, which prevents the notebook from stealing any of these events.

**Comment by rsinha25** [comment]
I tried stopPropogation but it does not work.
I have `event.stopPropogation()` for any keydown element on the div which has my form, input, etc. I also have a console.log for debugging. The log is printed if I type something in an `input` tag. But it does not work if I click on the div and press a key. It seems like the capturing is happening at the notebook level and the event never reaches the div itself.

I can check this using the `document.activeElement`. When I am not focusing on any input tag, the focus is directly moved to the jp-Notebook. Hence my div never gets any keydown.

I even tried it with the `:focus` fix but that didn't work either.

**Comment by blink1073** [comment]
Hi @rsinha25, in order for your div to take focus, it needs to have its `tabIndex` property set (to -1 if you don't want it to be considered for tab cycling).

**Comment by blink1073** [comment]
This is fixed in master and will be released in 0.17 (you won't use `event.stopPropagation` at all).

**Comment by rsinha25** [comment]
@blink1073 could you point the commit which fixes this ? Wanted to check how this was happening

**Comment by blink1073** [comment]
Here it is: https://github.com/jupyterlab/jupyterlab/commit/0071245600c6dac1c84cde3488485e40f679c2af#diff-652e554adf3b192d0c87e3a49033ced8.
