### ISSUE TITLE
JupyterLab 4.2.0: ImportError: cannot import name 'get_allowed_levels' from 'jupyterlab_server.config'

### ISSUE THREAD

**Issue by trenton3983** [jupyterlab/jupyterlab#16317]
## Description

Opened JupyterLab and was notified of a newer version 4.2.0, so I exited Jupyter, and used `conda install jupyterlab=4.2.0` at the (base) conda prompt.

Typing `jupyter lab` at (base) to launch, results in the following error:

```lang-none
(base) D:\users\trent\Dropbox\PythonProjects>jupyter lab

Traceback (most recent call last):
  File "C:\Users\trent\anaconda3\Scripts\jupyter-lab-script.py", line 5, in <module>
    from jupyterlab.labapp import main
  File "C:\Users\trent\anaconda3\Lib\site-packages\jupyterlab\labapp.py", line 26, in <module>
    from .commands import (
  File "C:\Users\trent\anaconda3\Lib\site-packages\jupyterlab\commands.py", line 32, in <module>
    from jupyterlab_server.config import (
ImportError: cannot import name 'get_allowed_levels' from 'jupyterlab_server.config' (C:\Users\trent\anaconda3\Lib\site-packages\jupyterlab_server\config.py)
```

`jupyterlab_server         2.25.1          py311haa95532_0` is being used.

## Reproduce

Launch `jupyter lab` at the (base) conda prompt

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Expected behavior

I expect jupyterlab to launch

## Context

- Operating System and version: Windows 11
- Browser and version: Microsoft Edge Version 124.0.2478.80 (Official build) (64-bit)
- JupyterLab version: 4.2.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
JupyterLab 4.2.0 requires `jupyterlab_server>=2.27.1,<3` but you have `2.25.1` installed:

https://github.com/jupyterlab/jupyterlab/blob/66bc3b0a9473aa3164105333053016965bbfaded/pyproject.toml#L47

Most likely you installed some packages using `pip` and some using `conda` which leads to incorrect resolution of dependencies.

**Comment by trenton3983** [comment]
I was able to do `conda search -f jupyterlab_server` to get the current version and install it.

This was a new Anaconda installation, and I know better than to use `pip` in my Anaconda distribution.

**Comment by krassowski** [comment]
Thanks for the reply and for confirmation it is not pip/conda issue. It looks like the dependency pin on conda-forge was wrong, even though it was correct in RC. New builds generated after https://github.com/conda-forge/jupyterlab-feedstock/pull/434 was merged should fix this.
