### ISSUE TITLE
jupyter lab build ==4.2.0 unable to get issuer certificate

### ISSUE THREAD

**Issue by mouatez25** [jupyterlab/jupyterlab#16316]
i'm not able to rebuild jupyterlab.

os : redhat
node : v20.11.1
npm : 10.7.0

 YN0001: │ RequestError: unable to get issuer certificate
    at ClientRequest.<anonymous> (/openprog/VirtualPython/lib/python3.11/site-packages/jupyterlab/staging/yarn.js:195:14340)
    at Object.onceWrapper (node:events:633:26)
    at ClientRequest.emit (node:events:530:35)
    at o.emit (/openprog/VirtualPython/lib/python3.11/site-packages/jupyterlab/staging/yarn.js:190:90286)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)

**Comment by mouatez25** [comment]
1 - after installing for exemple some labextension such as the scheduler..... you may think it's related with those labextensions but not , even having only jupyterlab installed on the virtual env i could not run jupyter lab build so it's probably not related with labextension.

2- jupyter lab build 
3- we don't

thanks you so much for your quick reply .

**Comment by krassowski** [comment]
1. In JupyterLab 3+ you should not need to rebuild JupyterLab after installing an extension and you should not use `jupyter labextension install` which is deprecated for installing extensions since JupyterLab 4. Instead you should install extensions using `pip install` or `conda install`. If you mean https://github.com/jupyter-server/jupyter-scheduler, please note that it lists `pip install jupyter_scheduler` in installation instructions.

**Comment by mouatez25** [comment]
we use jupyterlab-scheduler which is cron based.
https://pypi.org/project/jupyterlab-scheduler/

![image](https://github.com/jupyterlab/jupyterlab/assets/57817066/94d67cf9-72a2-4141-bdba-1909127e7dba)

i'm trying to upgrade jupyterlab from 3.6.4 to 4.2.0 which means soof the extension are already installed with jupyter labextension install.

so even jupyter server extension enable --user --py jupyter_scheduler does not resolve my issue

![image](https://github.com/jupyterlab/jupyterlab/assets/57817066/369ca8af-ca2e-4ac6-950a-78791c6a88f5)

is there any cron scheduler similar to jupyterlab-scheduler ?

thanks

**Comment by mouatez25** [comment]
difference between https://github.com/jupyter-server/jupyter-scheduler,  and https://pypi.org/project/jupyterlab-scheduler/ is that jupyter-scheduler depends on your jupyterlab session it does not run in the background , but jupyterlab-scheduler does uisng papermill or nbconvert , so even if a user end or logout from his session his jobs/notebooks will run as expected .

that's why I'm looking for anything similar to it ?

**Comment by krassowski** [comment]
It is not clear to me if the extension you are trying to use even works with JupyterLab 4.x as per https://github.com/tiburon-security/jupyterlab_scheduler/issues/25

`jupyter-scheduler` allows to swap out the scheduling engine which is for example what [argo-jupyter-scheduler](https://github.com/nebari-dev/argo-jupyter-scheduler) does so I imagine that you can also swap it for cron a scheduler too.

> that's why I'm looking for anything similar to it ?

https://github.com/nebari-dev/argo-jupyter-scheduler that I mentioned can run tasks in the background the same way as cron would, but it has a dependency on [argo](https://github.com/argoproj/argo-workflows), [conda-store](https://github.com/conda-incubator/conda-store) (for environment management) and I do not think it was tested outside of [nebari](https://github.com/nebari-dev/nebari) so it may or may not be good fit for you -depending on what your deployment is.

**Comment by mouatez25** [comment]
thank you for you answers!!

before i was able to change some line of codes( setup.py + package.json)to make it work with jupyterlab 3.6.4,i'm trying to do the same with jupyterlab4 .

even using pip only to install the package does not work and give me the error message mentioned before.

![image](https://github.com/jupyterlab/jupyterlab/assets/57817066/2d9f4cd9-db7a-402f-b539-8004cfb48068)

**Comment by mouatez25** [comment]
so now the question is:
do we have a scheduler which does not depend on jupyerlab session to install in linux ( no argo , no container ...)

thanks
