### ISSUE TITLE
Console not working with Interaction mode set to Terminal

### ISSUE THREAD

**Issue by jans-code** [jupyterlab/jupyterlab#16339]
## Description

I cannot use any Code Console when I've set the Interaction Mode to Terminal in the Code Console Settings tab.
Problems:
1. I cannot send any command.
2. Code completer does not work properly, does not accept Enter.

## Reproduce

1. Go to 'Settings'
2. Click on 'Code Console' on the left
3. Change Interaction Mode to 'Terminal'
4. Start a any Console i.e. 'Python 3 (ipykernel)'
5. Try to send anything i.e. '1+1'

## Expected behavior

A working Code Console.

## Context

- Operating System and version: Archlinux
- Browser and version: Chrome
- JupyterLab version: 4.2.0

**Comment by krassowski** [comment]
Reproduced, looks like another bug introduced by https://github.com/jupyterlab/lumino/pull/662. Working on adding a test and a fix right now.
