### ISSUE TITLE
Explore better options for styling the File Browser buttons

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1634]
We have long been trying to figure out a better way of styling the top buttons in the file browser. This is an issue to track ideas for that.

![screen shot 2017-02-06 at 1 49 55 pm](https://cloud.githubusercontent.com/assets/27600/22667798/28e826a8-ec73-11e6-8c14-c145d30091d6.png)

**Comment by cameronoelsen** [comment]
One concept I made is referenced in issue #1662

**Comment by ellisonbg** [comment]
I think we are good on master for this one.

![screen shot 2017-08-16 at 5 55 14 pm](https://user-images.githubusercontent.com/27600/29391408-121d63e6-82ac-11e7-92c2-232cc4496f62.png)
