### ISSUE TITLE
overrides.json slows down jupyterlab page load

### ISSUE THREAD

**Issue by singharpit94** [jupyterlab/jupyterlab#16355]
Hi,

I am using jupyterlab 4.2.0 and noticed that when I have bunch of extensions installed and have an overrides.json file located in **share/jupyter/lab/settings**, the network calls to load these extensions on page load is affected significantly.
 
Below is the list of extensions I have installed

```
async-lru>=2.0.4
jupyterlab-limit-output>=2.0.0
jupyterlab-pyflyby>=5.0.0
jupyterlab-notify>=2.0.0
jupyterlab-skip-traceback>=5.0.0
jupyterlab-execute-time>=3.0.0
jupyterlab-code-formatter>=2.2.1
jupyterlab_theme_solarized_dark>=3.0.0
jupyterlab_vim>=4.0.3
jupyter-resource-usage>=1.0.1
pyviz_comms>=3.0.0
jupyterlab-spellchecker>=0.8.4
jupyterlab-lsp>=5.0.0
jupyterlab-favorites>=3.2.0
jupyterlab-git>=0.50.0a0
bqplot 
jupytext
nbdime
```

and below is the overrides.json file I have

```
 "@jupyterlab/notebook-extension:tracker": {
    codeCellConfig: {
      lineNumbers: true,
      autoClosingBrackets: true,
      fontFamily: null,
      fontSize: null,
      lineHeight: null,
      lineWrap: false,
      matchBrackets: true,
      readOnly: false,
      insertSpaces: true,
      tabSize: 4,
      wordWrapColumn: 80,
      rulers: [],
      codeFolding: false,
      lineWiseCopyCut: true,
    },
    recordTiming: true,
  },
  "@jupyterlab/git:plugin": {
    simpleStaging: true,
    displayStatus: false,
  },
  "@jupyterlab/shortcuts-extension:shortcuts": {
    shortcuts: [
      {
        command: "documentsearch:start",
        keys: ["Accel Shift F"],
        selector: ".jp-mod-searchable",
      },
      {
        command: "documentsearch:startWithReplace",
        keys: ["Accel Shift H"],
        selector: ".jp-mod-searchable",
      },
      {
        "args": {},
        "command": "documentsearch:start",
        "keys": [
            "Accel F"
        ],
        "disabled": true,
        "selector": ".jp-mod-searchable"
      },
      {
        "command": "run-tidy-imports",
        "keys": [
            "Alt I"
        ],
        selector: ".jp-NotebookPanel-notebook"
      },
    ],
  },
  "@jupyterlab/mainmenu-extension:plugin": {
    menus: [
      {
        id: "jp-mainmenu-file",
        items: [
          {
        
            command: "filebrowser:open-path",
            disabled: true,
          },
        ],
      },
    ],
  },
  "@jupyterlab/application-extension:context-menu": {
    "contextMenu": [
      {
     
        "command": "filebrowser:share-main",
        "selector": ".jp-DirListing-item[data-isdir]",
        "disabled": true
      }
    ]
  },
  "@axlair/jupyterlab_vim:plugin": {
    enabled: false,
    "extraKeybindings": [
        {
            "context": "normal",
            "mapfn": "map",
            "enabled": true,
            "command": "\\",
            "keys": ":noh<CR>"
        }
    ]
  },
  "jupyterlab-limit-output:settings": {
    enabled: true,
    head: 500,
    tail: 500
  },
  "@jupyter-widgets/jupyterlab-manager:plugin": {
    saveState: true,
  },
  "@jupyterlab/toc-extension:plugin": {
    includeOutput: false,
    syncCollapseState: true,
  },
  "@jupyterlab-contrib/spellchecker:plugin": {
    theme: "dotted-underline",
    mimeTypes: [
        "text/plain",
        "text/x-ipythongfm",
        "text/x-rst",
        "text/x-latex",
        "text/x-rsrc"
    ]
  },

  "@jupyter-lsp/jupyterlab-lsp:completion": {
  
    disable: true,
  },
  "@jupyter-lsp/jupyterlab-lsp:highlights": {

    disable: true
  },
  "@jupyter-lsp/jupyterlab-lsp:signature": {
   
    disable: true,
  },
  "@jupyter-lsp/jupyterlab-lsp:diagnostics": {

    disable: true,
  },

  "@jupyter-lsp/jupyterlab-lsp:plugin": {
    language_servers: {
      pylsp: {
        priority: 100,
        serverSettings: {
          pylsp: {
            plugins: {
              pycodestyle: {
                enabled: false,
              },
              pydocstyle: {
                enabled: false,
              },
              pyflakes: {
                enabled: false,
              },
              flake8: {
                enabled: false,
              },
            },
          },
        },
      },
      pyright: {

        priority: 200,
        serverSettings: {
          pyright: {
            plugins: {
              pycodestyle: {
                enabled: false,
              },
              pydocstyle: {
                enabled: false,
              },
              pyflakes: {
                enabled: false,
              },
              flake8: {
                enabled: false,
              },
            },
          },
        },
      },
    },
  },
  "@ryantam626/jupyterlab_code_formatter:settings": {
  
    cacheFormatters: true,
  }
}
```

I am also attaching the snapshots of the network tab showing load times for some of the extensions

Without overrides.json

![without-overrides](https://github.com/jupyterlab/jupyterlab/assets/7591673/3ea06fe2-d492-40e2-b569-354f757b0af4)

With overrides,json

![with-overrides](https://github.com/jupyterlab/jupyterlab/assets/7591673/b0dbf370-50d5-458a-a984-76fe1166482d)

You can see that there are significant differences in the load times when we use a overrides.json file. 

On looking a bit more in the codebase, I found that the method [_get_overrides](https://github.com/jupyterlab/jupyterlab_server/blob/1e0367f5daf66c8c4a9fdccd66320b3006830770/jupyterlab_server/settings_utils.py#L303) seems to be called multiple times and the timings of them are significantly higher when a overrides.json file is present (approx 2 ms versus 40 ms)

Can we optimize this, may be read only once the overrides.json file or something better which can bring down the load times of the extensions?

**Comment by krassowski** [comment]
I attempted to reproduce on binder:

| [4.2.0 without overrides](https://gist.github.com/krassowski/cfe3e175d7bf29ca65d8bfaeef87ece1) | [4.2.0 with overrides](https://gist.github.com/krassowski/66833d6e680ab27ab56e02cbced17386) |
|---|---|
| ![Screenshot from 2024-05-22 09-10-49](https://github.com/jupyterlab/jupyterlab/assets/5832902/08569adb-4d7f-4736-80c8-99661b4489a2) | ![Screenshot from 2024-05-22 09-11-49](https://github.com/jupyterlab/jupyterlab/assets/5832902/95c34723-1e5d-4c70-a01b-32daca8cc213) |

I do not see a consistent increase in loading time on the second load. I will try to reproduce with an initial load.

> `/formatters` is a useful sanity check as without overrides the formatters are not cached and take 1.83s and without only 53 ms.

**Comment by krassowski** [comment]
Just to double-check are you using `overrides.json` or `overrides.json5`?

**Comment by krassowski** [comment]
On initial load timings indeed appear to be higher with overrides (up to two times):

| Without overrides | With overrides |
|--|--|
| ![Screenshot from 2024-05-22 09-24-46](https://github.com/jupyterlab/jupyterlab/assets/5832902/acaba9d3-14c2-4ca8-a0ba-a49837177965) | ![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/735ecaa9-0c17-4821-9ac1-2d71f26113a3) |

My hypothesis is that each instance of the handler loads the overrides the first time it is called and caches them.

**Comment by krassowski** [comment]
We will need to pre-load the `overrides.json` and pass it in config to handler initializer, somewhere around [here](https://github.com/jupyterlab/jupyterlab_server/blob/1e0367f5daf66c8c4a9fdccd66320b3006830770/jupyterlab_server/handlers.py#L241-L243).

**Comment by singharpit94** [comment]
> Just to double-check are you using `overrides.json` or `overrides.json5`?

We are using overrides.json5

**Comment by krassowski** [comment]
@singharpit94 does upgrading `jupyterlab-server` to v`2.27.2` help?

**Comment by singharpit94** [comment]
Hi, yes. I tested with the new version and it is working great now and timings of loading the extensions have decreased significantly. Thanks a lot @krassowski for the changes.
