### ISSUE TITLE
table of contents won't show async function

### ISSUE THREAD

**Issue by j-carson** [jupyterlab/jupyterlab#16352]
## Description

When opening the table of contents widget for  a .py file, only the non-async functions are bookmarked
## Reproduce

1. Create a .py file with an async function
2. Open the table of contents widget
3. Function is not there 
![screenshot](https://github.com/jupyterlab/jupyterlab/assets/44308120/8c7263b2-2002-408b-8489-3858048d3cb0)
## Expected behavior

Table of contents shows all my functions 

## Context

- Operating System and version:  Linux Ubuntu 20.04 
- Browser and version: Firefox 126
- JupyterLab version: 4.2.0 

Let me know if you really need all those details and I will try again

 - I tried to save them and github would not accept them because there were too many characters

<details><summary>Browser Output</summary>
<pre>
TypeError: i is undefined
    getHover hover.ts:321
    factory jlab_core.b91074b1e57242ddcd31.js:1
    _execute jlab_core.b91074b1e57242ddcd31.js:1
    o jlab_core.b91074b1e57242ddcd31.js:1
</pre>
</details>

**Comment by krassowski** [comment]
Thank you for reporting! To solve it this regular expression needs to be updated:

https://github.com/jupyterlab/jupyterlab/blob/3079730eb95ccce3c735e045bcc8a39d64639ce1/packages/fileeditor/src/toc/python.ts#L20-L22

and we will also need a new test case (or a few) in:

https://github.com/jupyterlab/jupyterlab/blob/3079730eb95ccce3c735e045bcc8a39d64639ce1/packages/fileeditor/test/python.spec.ts#L14-L27

**Comment by Kunalpal216** [comment]
Is this issue open ? I would like to work on this.

**Comment by krassowski** [comment]
@Kunalpal216 please do!

**Comment by fcollonval** [comment]
Fixed by #16443
