### ISSUE TITLE
Explore per-cell buttons for super common actions

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1635]
There are a very small number of actions on cells that you end up doing many many times:

* New code cell
* New markdown cell
* Delete cell

We already have drag-n-drop for moving cells now. I would like us to explore some sort of per cell UI (buttons?) for these common things. They should only show on the active/selected cell.

**Comment by eskirk** [comment]
Status on this? I'm interested in helping with implementation.

**Comment by blink1073** [comment]
AFAIK we are waiting for design input from Cameron.

**Comment by AbdealiJK** [comment]
I created a very similar issue https://github.com/jupyterlab/jupyterlab/issues/1825 before I saw this.

I'm interested in helping this too if the design is done

**Comment by ellisonbg** [comment]
After design work with @cameronoelsen we are thinking of the following:

* The most common cell actions are (create new, type code, run the code). Based on this we are adding new UI elements on a per cell basis for creating new cells and running code (see #2109) and 
* The next most common action without cell-local is delete cell. We are planning on putting a small trashcan icon in the upper right area of the cell for deleting it (see #2108)
* Hide input/output will be combined with cell selectors (see design in #1742)
* Other actions are probably an order of magnitude less common. Because of the need to keep the per cell UI minimal, our plan is to put those actions in context menus (see #2054)

**Comment by JasonWeill** [comment]
Closing this because the cell toolbar was added last year

**Comment by krassowski** [comment]
Specifically, it was added in this PR: https://github.com/jupyterlab/jupyterlab/pull/12028 and backported to3.4.x.
