### ISSUE TITLE
Jupyter Notebook missing Restart Kernel and Run up to Selected Cell option

### ISSUE THREAD

**Issue by iainjclark** [jupyterlab/jupyterlab#16366]
Jupyter Labview has the menu option Kernel -> Restart Kernel and Run up to Selected Cell
![image](https://github.com/jupyterlab/jupyterlab/assets/20824309/e0633a12-ec12-46e2-a086-d25bf433f067)
However this option is not available in the equivalent menu in the older style Jupyter Notebook.
![image](https://github.com/jupyterlab/jupyterlab/assets/20824309/80c299d6-4696-457a-873c-11756c3f29a7)
Can we please have it?

**Comment by JasonWeill** [comment]
@iainjclark The classic Jupyter Notebook is now maintained as part of the `nbclassic` package. I opened an issue in this package to cover this enhancement request: https://github.com/jupyter/nbclassic/issues/281 . Let's keep the conversation going in that issue. Thank you for your contribution!
