### ISSUE TITLE
Shift+tab is no longer displaying contextual help in code cell

### ISSUE THREAD

**Issue by horsto** [jupyterlab/jupyterlab#16375]
## Description

When writing out a function call (for example `np.zeros(...`) and clicking **shift+tab**, usually a contextual help window would pop up,  but this seems to have gotten lost in the most recent jupyter lab update(s). 
Is there a way to re-enable this feature? 

## Reproduce

Write any function / class out and after opening the first bracket, click shift+tab. Usually help would pop up at this point, showing the docstring. 

## Context

- Operating System and version: MacOS Sonoma 14.4.1
- Browser and version: Brave v1.65
- JupyterLab version: v4.2

</details>

**Comment by krassowski** [comment]
@horsto this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/16319, which was fixed in JupyterLab 4.2.1. You will need to upgrade from 4.2.0.

**Comment by horsto** [comment]
Thank you! Worked.
