### ISSUE TITLE
Jupyter Lab 4 - Provide custom HTTP header to allow advanced WASM widgets

### ISSUE THREAD

**Issue by jourdain** [jupyterlab/jupyterlab#16382]
### Problem

For enabling [`SharedArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer) on the web side, the server needs to provide the following set of HTTP headers:

```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
Access-Control-Allow-Origin: *
Cache-Control: no-store
```

I've initially tried to add those only in my extension that serve my iframe content, but it seems that we need a more global setup.

Having access to `SharedArrayBuffer` is key for enabling better performance when dealing with web worked and in my usecase with VTK/WASM.

### Proposed Solution

Allow admin/user to provide add-on HTTP headers for a Jupyter Lab instance. Ideally via CLI and config file.
Jupyter Hub should also be consider to fully support real deployment as well.

### Additional context

A way to test if "my problem" is solved, if you were to enable those headers listed above, you should have access in the web console to a `SharedArrayBuffer` class. While that class will be missing if those http headers are missing.

**Comment by krassowski** [comment]
You can do this by setting `server_app.web_app.settings["headers"]` in the server extension, as is done by [jupyterlab-transformers-completer](https://github.com/krassowski/jupyterlab-transformers-completer) for the very same purpose of enabling `SharedArrayBuffer` [here](https://github.com/krassowski/jupyterlab-transformers-completer/blob/87861e72efa84163f99ed7a5c44ac13d72adbf2f/jupyterlab_transformers_completer/__init__.py#L32-L38).

Only the first two headers need to be added. By warned that this currently breaks fetching images from remote URLs, for for example in the Extension Manager sidebar the icons of extensions fetched from GitHub will not display correctly. We should be able to fix this by adding `crossorigin="anonymous"` to the image elements (I am not sure if this already works with all browsers).

**Comment by jourdain** [comment]
Working like a charm, thanks for the pointer.
