### ISSUE TITLE
Incomplete context menu on old Firefox versions due to use of the `:has()` selector

### ISSUE THREAD

**Issue by carneytyler** [jupyterlab/jupyterlab#16391]
## Description

When using JupyterLab 4.2.0 the workspace extension attempts to update the right-click context menu and I get the error below in the console. This causes a lot of the normal context options to not appear (screenshot).

`Failed to load context menu items from settings registry. Error: Invalid selector: .jp-RunningSessions:has(.jp-mod-workspace)`

I traced this back to what I think are the culprit(s) [here](https://github.com/jupyterlab/jupyterlab/blob/main/packages/workspaces-extension/schema/sidebar.json#L38) and [here](https://github.com/jupyterlab/jupyterlab/blob/main/packages/workspaces-extension/schema/sidebar.json#L43). This is due to Firefox starting support for [:has()](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility) in v121, but ESR is still based on v115.

I'm not sure of the project's protocols for browser support, but since my company only uses ESR we are forced to sit at 4.1.x until the next ESR release in a few months, which isn't the end of the world, but would still like to be on the newest if at all possible.

Thanks for everything this package does!

![image](https://github.com/jupyterlab/jupyterlab/assets/61724217/a24f3d52-0ccd-4650-b344-1214936ee244)

## Reproduce

1. Load 4.2.x in Firefox versions <121 and attempt to right click open context menus

## Expected behavior

Full context menu options like in 4.1.x

![image](https://github.com/jupyterlab/jupyterlab/assets/61724217/5a669e7b-3b49-4f09-b96c-23128f89326c)

## Context

- Operating System and version: Windows 11
- Browser and version: Firefox ESR 115
- JupyterLab version: 4.2.0

<details><summary>Browser Output</summary>

<pre>
Failed to load context menu items from settings registry. Error: Invalid selector: .jp-RunningSessions:has(.jp-mod-workspace)

</pre>
</details>

**Comment by krassowski** [comment]
Thank you for opening the issue! In Firefox ESR you can toggle the `layout.css.has-selector.enabled` flag in the `about:config` page - this works since Firefox v103.

**Comment by JasonWeill** [comment]
JupyterLab's [browser support page](https://jupyterlab.readthedocs.io/en/latest/getting_started/installation.html#supported-browsers) mentions that we support the most recent version of Firefox, without specifying a release channel. Given Firefox ESR's popularity in managed environments, we would consider a pull request that addresses problems in ESR, but we don't actively test features (for example, in continuous integration tests) against the ESR channel.

**Comment by aurelgriesser** [comment]
Watching this because I've been stumped by the weirdly truncated context menus - and yes I am on Firefox 115.14 (says it's the latest available, MacOS 10.13.6) with Jupyter lab 4.2.4. Finally found this Issue so keenly awaiting resolution.

Thanks Jupyter team, you've made a fabulous tool!

**Comment by krassowski** [comment]
Just to note that Firefox ESR is now at 128.1.0 hence this issue is no longer a problem for ESR users. https://www.mozilla.org/en-US/firefox/128.1.0/releasenotes/

**Comment by JasonWeill** [comment]
@aurelgriesser We don't explicitly say which OS versions we support, but macOS 10.13 received its last security update in November 2020, nearly 4 years ago. I don't expect browser vendors to continue to support it, even for security-related fixes. Jupyter supports the latest versions of Firefox, Chrome, Safari, and Edge ([source](https://jupyterlab.readthedocs.io/en/latest/getting_started/installation.html#supported-browsers)).
