### ISSUE TITLE
`Linux Tests / Linux (usage, 3.12)` is failing on CI (missing the `setup.py` file)

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16404]
## Description

`Linux Tests / Linux (usage, 3.12)`  started failing, as it seems due to a change in packaging tooling:

```py
Traceback (most recent call last):
  File "/home/runner/work/jupyterlab/jupyterlab/jupyterlab/tests/mock_packages/extension/setup.py", line 13, in <module>
    from setuptools import setup  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'setuptools'
Traceback (most recent call last):

  File "/home/runner/work/jupyterlab/jupyterlab/jupyterlab/debuglog.py", line 45, in debug_logging
    yield

  File "/home/runner/work/jupyterlab/jupyterlab/jupyterlab/labextensions.py", line 169, in start
    ans = self.run_task()
          ^^^^^^^^^^^^^^^

  File "/home/runner/work/jupyterlab/jupyterlab/jupyterlab/labextensions.py", line 258, in run_task
    develop_labextension_py(

  File "/home/runner/work/jupyterlab/jupyterlab/jupyterlab/federated_labextensions.py", line 168, in develop_labextension_py
    m, labexts = _get_labextension_metadata(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/runner/work/jupyterlab/jupyterlab/jupyterlab/federated_labextensions.py", line 455, in _get_labextension_metadata
    raise FileNotFoundError(msg) from None

FileNotFoundError: The Python package `extension` is not a valid package, it is missing the `setup.py` file.

/home/runner/work/jupyterlab/jupyterlab/jupyterlab/debuglog.py:54: UserWarning: An error occurred.
  warnings.warn("An error occurred.")
/home/runner/work/jupyterlab/jupyterlab/jupyterlab/debuglog.py:55: UserWarning: FileNotFoundError: The Python package `extension` is not a valid package, it is missing the `setup.py` file.
  warnings.warn(msg[-1].strip())
/home/runner/work/jupyterlab/jupyterlab/jupyterlab/debuglog.py:56: UserWarning: See the log file for details: /tmp/jupyterlab-debug-3wxs8p7n.log
  warnings.warn(f"See the log file for details: {log_path!s}")
Exiting application: lab
```

## Reproduce

See https://github.com/jupyterlab/jupyterlab/actions/runs/9299335778/job/25593065172?pr=16397

## Expected behavior

Tests pass

## Context

- It was still passing on May 28th (b2ff3fbbe60e1d08d23f6a4738d4f2d76f175152)
- It started failing on May 29th (https://github.com/jupyterlab/jupyterlab/pull/16392)

**Comment by jtpio** [comment]
Also seeing the same error after creating a new extension from the template: https://github.com/jupyterlab/extension-template

And running `jupyter labextension develop . --overwrite`

**Comment by fcollonval** [comment]
I had to install explicitly setuptools in the template repo. But I cannot find any longer a reference of what dependency stack has changed making setuptools undefined - although it is the path forward that no assumption of default build library should be made.

For reference with the template repo, I was not hitting this issue but it was failing when executing the following local import:

https://github.com/jupyterlab/jupyterlab/blob/21ffea9749637633b4a4d82b3f277b55f80afb3d/jupyterlab/federated_labextensions.py#L464

**Comment by jtpio** [comment]
If `setuptools` is actually used and needed for the `jupyter labextension develop` command, maybe it should be added to the list of dependencies?

https://github.com/jupyterlab/jupyterlab/blob/0c13a5b75784190141f151a4b8a2ca32bd3f8559/pyproject.toml#L37-L53

**Comment by krassowski** [comment]
If we end up adding pin we should make it `>=40.1.0` as this is when `find_namespace_packages` was added.
