### ISSUE TITLE
Sorting the file browser by "Last Modified" keeps notebooks sorted above files

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#16425]
In JupyterLab 4.1.1, I created a markdown file "chat_history-2024-06-03-14-29.md" in the root of my JupyterLab instance. I sorted the file browser in ascending order of Last Modified, expecting to find it:

![image](https://github.com/jupyterlab/jupyterlab/assets/93281816/f81b26d1-4b99-4842-915a-5e9841aeb6ab)

… but instead, I saw my Markdown file sorted in a group by itself, below the list of notebooks.

![image](https://github.com/jupyterlab/jupyterlab/assets/93281816/d3740b88-fe35-4e2d-a92d-89a9e546b95e)

When the user sorts in modified date order, results should not be grouped by file type.

If I right-click on the file browser, I see an option "Sort Notebooks Above Files", which is enabled by default; unchecking this option restores sort behavior that I expected. I didn't know that this option existed, or that it was enabled by default. I expected that sorting files by modified date would cause the "notebooks above files" option to be disabled automatically.

**Comment by JasonWeill** [comment]
This was added for feature parity with Notebook 6, per #14332. I am still surprised that the "Sort Notebooks Above Files" option remains enabled at all times, but if that's expected, I can close this issue.

**Comment by krassowski** [comment]
Duplicate of https://github.com/jupyterlab/jupyterlab/issues/3237

It looks like the behaviour changed a few times from "sort notebooks first" to "do not sort notebooks first" (https://github.com/jupyterlab/jupyterlab/issues/6994) back to "sort notebooks first" (https://github.com/jupyterlab/jupyterlab/issues/14332). I view this issue as a natural part of the cycle as it proposes to change it to "do not sort notebooks first". I think a more comprehensive documentation for this behaviour is warranted.
