### ISSUE TITLE
Show line numbers by default

### ISSUE THREAD

**Issue by hyperkai** [jupyterlab/jupyterlab#16426]
### Problem

By default, line numbers are not shown and the cases which we use more than 10 lines are a lot. So, if there is error, we cannot easily find the line where the error occurs even though the error is described with the line number.

### Proposed Solution

So, line numbers should be shown by default.

**Comment by JasonWeill** [comment]
There is a setting under Notebook to show line numbers, which reportedly defaults to "true", but the default is in fact false. We should either report the default as false or make the true setting work as expected. We already have a bug concerning this issue: #15267 (thanks @krassowski ).

![image](https://github.com/jupyterlab/jupyterlab/assets/93281816/d906be75-9ea1-430f-bf02-f627a424a2e0)
