### ISSUE TITLE
Code comments in tilde (`~`) fences incorrectly shown as headings in TOC

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16422]
## Description

Code comments in tilde (`~`) fences incorrectly shown as headings in TOC. Code fences using `~` are part of GFM spec, and we are using GFM in Markdown cells https://github.github.com/gfm/#fenced-code-blocks

Similar to https://github.com/jupyterlab/jupyterlab/issues/16403

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/fd04bbb2-bb2e-41c8-a497-be785263560b)

## Reproduce

Paste:

```
~~~
# test
~~~
```

into a Markdown cell

open TOC

## Expected behavior

no heading in TOC

## Context

- JupyterLab version: 4.2.1

**Comment by itsmevichu** [comment]
@krassowski I will pick this issue.
