### ISSUE TITLE
Add __file__ variable supported by traditional Python scripts to Notebook env.

### ISSUE THREAD

**Issue by palewire** [jupyterlab/jupyterlab#1643]
It would be cool, if the ``__file__`` variable present in traditional Python scripts also existed with a notebook. This could be especially helpful when generating dynamic paths. 

Other Python double underscore methods, such as ``__doc__`` and ``__name__``, are already present. Why not add this one?

**Comment by blink1073** [comment]
Hi @palewire, this would be implemented in https://github.com/ipython/ipykernel, do you mind filing the issue there?

**Comment by palewire** [comment]
No problem. Thanks for the tip.
