### ISSUE TITLE
Table of contents only displays headings up to level 4

### ISSUE THREAD

**Issue by danpal96** [jupyterlab/jupyterlab#16442]
## Description

In jupyterlab 4.2.1  the table of contents only displays headings up to level 4 but in jupyterlab 3..6.7 it displayed levels 5 and 6
 jupyterlab 4.2.1:
![image](https://github.com/jupyterlab/jupyterlab/assets/37080389/1333cbbb-0bc7-4acf-9887-c8cba49d3cb4)
 jupyterlab 3..6.7:
![image](https://github.com/jupyterlab/jupyterlab/assets/37080389/4c46ad6b-47e1-4d08-8614-aadc81d55aa3)

## Reproduce

Create a notebook with markdown cells including all 6 heading levels

## Expected behavior

The table of contents should show the 6  heading levels

## Context

- Operating System and version: Ubuntu 22.04.3 LTS x86_64
- Browser and version: Firefox 126.0.2 (64-bit)
- JupyterLab version: 4.2.1

**Comment by krassowski** [comment]
@danpal96 you can change that in settings:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/074a9c4b-f867-43f9-b07b-fffc2bb1b348)

I have no opinion on what the default value should be, it would be useful to search for the past discussions to understand why 4 was chosen.

**Comment by danpal96** [comment]
Great, I didn't know that, thanks

**Comment by danpal96** [comment]
Yes, it is solved, thnks
