### ISSUE TITLE
Fix typo - Remove prefixed single quote to Jupyter

### ISSUE THREAD

**Issue by achhina** [jupyterlab/jupyterlab#16457]
Hi folks, while reading the FAQ - Tips & Tricks in regards to clearing the workspace, I noticed that there was a single quote prefixed to the Jupyter server config setting suggestion.

https://github.com/jupyterlab/jupyterlab/blob/6143d29918d0d3686646e22716293f288c659667/docs/source/getting_started/faq.rst?plain=1#L48

I believe this is a typo, but wanted to confirm before creating a PR.

**Comment by krassowski** [comment]
Yes, it is - thank you for spotting it and offering to open a PR - please feel welcome to go ahead!
