### ISSUE TITLE
Huge waster of space in FileBrowser

### ISSUE THREAD

**Issue by stefansimik** [jupyterlab/jupyterlab#16455]
## Description

When you make FileBrowser bigger, to see longer filenames, 
we get to extreme waste of space, because of non-resizeable fixed percentage columns

![CleanShot 2024-06-07 at 23 50 34@2x](https://github.com/jupyterlab/jupyterlab/assets/6208056/a3057a26-6c7c-44ec-b98a-54013e4160f3)

This is really very bad design and needs to be fixed.
Second column should be significantly smaller.

## Reproduce

Just change width of the FileBrowser - so it is bigger, to see longer filenames inside.

## Expected behavior

1st column Name - should change its width.
2nd colum Modified - should have fixed size and should be significantly smaller.

**Comment by JasonWeill** [comment]
@stefansimik Thanks for opening this issue! We're tracking the file browser columns' width in #3875, which would also allow users to resize columns to their liking. Closing this issue as a duplicate.
