### ISSUE TITLE
BUG: Multi-line text with a `>>>` starting the second line remove the `>>>` on all lines if the text is the first item assigned in a cell.  

### ISSUE THREAD

**Issue by bmwoodruff** [jupyterlab/jupyterlab#16483]
## Description

Save a multiline text with either `"""` or `'''` and the second line starts with `>>>`, then odd behavior occurs based on whether the text is the first thing being assigned in the cell or not. If the text is the first thing assigned, then the `>>>` is stripped from ALL lines in the text."  If there is a comment above the text, or some other command first, then the text is appropriately stored. 

This is a problem because I'm working with docstring examples in a programmatic way. Stripping the `>>>` of every command from an example interactive python session is problematic. In addition, the fact that the cell behaves differently whether or not there is a comment above something seem like a bug. 

## Reproduce

Open a new `.ipynb` notebook. Type the following in the first cell.
```
txt = """
>>> Hi world!"""
print(txt)
```
Evaluate the cell and notice that the `>>>` is gone. Now open a second cell and type:
```
#
txt = """
>>> Hi world!"""
print(txt)
```
Evaluate the cell and notice that the `>>>` is preserved. 

Here is a screenshot from the online JupyterNotebook of a minimal reproduction:
![Screenshot from 2024-06-12 18-37-02](https://github.com/jupyterlab/jupyterlab/assets/1594818/286dc225-5bd1-4f1f-b098-79f39fa4e18f)

Here is another lengthier screenshot showing several ways to trigger, or not trigger, the bug. In particular, white space in front of the first `>>>` prevents the bug. I hope this is sufficient to identify the problem
![Screenshot from 2024-06-12 18-41-24](https://github.com/jupyterlab/jupyterlab/assets/1594818/239c92a5-bd35-43b5-87fa-c0b2d27fe5c8)

I've reproduced this on all the options at https://jupyter.org/try.  I've also reproduced it on my personal machines and a custom installation on Nebari at OpenTeams.   

Here is the actual relevant file contents, and you can see that the `>>>` is definitely removed.
```
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Hi world!\n"      <------------------------------------------ Error here
     ]
    }
   ],
   "source": [
    "txt = \"\"\"\n",
    ">>> Hi world!\"\"\"\n",   <------------------------------------------ Stemmed from this line.
    "print(txt)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      ">>> Hi world!\n"  <------------------------------------------ Correct output
     ]
    }
   ],
   "source": [
    "# Any comment or another command enables correct processing and preserves >>>\n",
    "txt = \"\"\"\n",
    ">>> Hi world!\"\"\"\n",  <-------------- Same exact line as above. The comment stops the issue.
    "print(txt)"
   ]
  }
 ]
```

## Expected behavior

I would expect the string to preserve the `>>>` regardless of whether or not a comment is placed above it. This is the behavior in an interactive shell or running it as a script. Only JupyterLab removes the `>>>` and only if assigning the text is the first thing happening in the cell. 

## Context

- Operating System and version: Ubuntu 22.02, https://jupyter.org/try, Windows 11, etc.
- Browser and version: Chrome Version 125.0.6422.141 (Official Build) (64-bit) on Ubuntu, Also both Chrome and Edge on Windows.
- JupyterLab version: Those on https://jupyter.org/try have the issue, as well as any other I open.

**Comment by bmwoodruff** [comment]
I'm guessing my use case is pretty obscure, but figured I'd point out the issue (after having spent a few hours today narrowing it down to a minimal example). I know how to prevent it (just add a comment). It does make me wonder if it's connected to anything else.

**Comment by JasonWeill** [comment]
@bmwoodruff Thank you for your contribution! I also see this strange behavior in IPython 8.24.0, run from the command line. I also see it in Python 3.12.2. This definitely seems unexpected, but you might want to investigate further upstream, including in Python itself, which your kernel is using. It doesn't appear that JupyterLab is doing anything specific to influence this, so this doesn't appear to be a JupyterLab bug.

**Comment by jasongrout** [comment]
This is a bug in IPython. Basically, IPython automatically strips leading `>>>` off so that you can paste in docstrings and run them. However, since it does a regex-based transform, it doesn't see the `>>>` is inside a string and it should not strip those characters.

The prompt stripping transform in ipython is created here: https://github.com/ipython/ipython/blob/128bd582b9894b8ae9ff577aafe13f5fdb39c3cb/IPython/core/inputtransformer2.py#L91-L94

and registered here: https://github.com/ipython/ipython/blob/128bd582b9894b8ae9ff577aafe13f5fdb39c3cb/IPython/core/inputtransformer2.py#L600

You can check this is issue by deleting that transformer. For me, this solves the issue:

```
ip = get_ipython()
del ip.input_transformer_manager.cleanup_transforms[2]
```
