### ISSUE TITLE
Issue patching SessionConnection class in extension after moving to pip based install

### ISSUE THREAD

**Issue by snehasaharawat** [jupyterlab/jupyterlab#16513]
Hi,
I have a requirement where I am creating jupyterlab extension to accept kernel parameters from user whenever user starts a new kernel or change a kernel. Once I receive the input kernel parameters from user, I want to pass it to the backend api POST /api/sessions and PATCH /api/session. 

For my usecase, I will have to patch some of the methods of Jupyterlab to change the behaviour and pass these parameters to backend api. I am able to successfully patch SessionContext's [changeKernel](https://github.com/jupyterlab/jupyterlab/blob/main/packages/apputils/src/sessioncontext.tsx#L736) method but I am facing issues while patching SessionConnection class [changeKernel method](https://github.com/jupyterlab/jupyterlab/blob/main/packages/services/src/session/default.ts#L276)

this is how I am doing the patching in my extension
```
        const originalChangeKernel = SessionConnection.prototype.changeKernel;
        SessionConnection.prototype.changeKernel = async function (
          options: Partial<Kernel.IModel>
        ): Promise<Kernel.IKernelConnection | null> {
        }
 ```
 
 The patching isnt working because SessionConnection is not an exported service (@jupyterlab/services) : https://github.com/jupyterlab/jupyterlab/blob/main/packages/services/src/session/index.ts
 
 I am installing my extension using pip install. This used to work earlier when installation was done using jupyter lab install

**Comment by krassowski** [comment]
First, let me say that this is not exactly a supported way of extending the functionality/manipulating the API.

With that out of the way, I think you may be patching a copy of the `SessionConnection` which ships with your extension, rather than the one that is used by core JupyterLab. To change this behaviour you will need to mark the `services` package as `singleton` in `jupyterlab.sharedPackages` entry in `package.json` - see https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#deduplication-of-dependencies (see "Requiring a service" and "Optionally using a service" examples). Let me know if this helps!

**Comment by JasonWeill** [comment]
@krassowski Does this issue represent work that could be done in JupyterLab?

**Comment by krassowski** [comment]
No, I don't think so. I also believe the documentation here is comprehensive and includes examples. As for supporting the use case of swapping core services this will be addressed by the ongoing work on https://github.com/jupyterlab/jupyterlab/issues/15329.

**Comment by snehasaharawat** [comment]
Hi @krassowski 
Added the following
```
   "sharedPackages": {
      "@jupyterlab/services": {
        "bundled": false,
        "singleton": true
      }
    }
    
```
But the patching of SessionConnection is still not working. Am I missing anything?

**Comment by krassowski** [comment]
Not sure, again modifying the `prototype` is not a supported practice.

> accept kernel parameters from user whenever user starts a new kernel or change a kernel

This should be solvable without monkey-patching the services. You may also be interested in:
- https://github.com/jupyter/enhancement-proposals/pull/87
- https://github.com/jupyterlab/jupyterlab/pull/16487

**Comment by JasonWeill** [comment]
Per @krassowski , I'm closing this issue, because it does not represent a bug or unique feature enhancement request in JupyterLab. Let's continue the discussion on the related items that Mike shared.
