### ISSUE TITLE
Release check is failing on CI due to twine/importlib interaction (KeyError: 'home-page')

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16524]
FYI for anyone else submitting PRs. It likely does not require any action unless it is not fixed upstream soon in which case we may want to pin importlib for now:
- first seen in https://github.com/jupyterlab/jupyterlab/pull/16523
- upstream issue https://github.com/pypa/twine/issues/1125
- upstream PR https://github.com/pypa/twine/pull/1124

**Comment by jtpio** [comment]
Looks like the check now passes on the latest PRs, and https://github.com/pypa/twine/issues/1125 is now closed.

Should we close this issue as fixed?

**Comment by krassowski** [comment]
Yes, we can close it - thanks!
