### ISSUE TITLE
Change the background color of the New Launcher button when hovering over it

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/jupyterlab#16549]
Hi! 👋 

### Problem

Currently, the New Launcher primary button (the + button in the top-left corner of the interface) has no visual cues when a user hovers over it (except for the cursor), a behavior inconsistent with other buttons.

### New Launcher primary button

https://github.com/jupyterlab/jupyterlab/assets/17132927/cd19f019-6c71-4fcd-9a0c-94eed6faba32

### Other buttons

<img width="1582" alt="Screenshot 2024-07-03 at 07 44 15" src="https://github.com/jupyterlab/jupyterlab/assets/17132927/1f5ff853-70ea-4a30-82c6-9cd1aee5fe7b">

<img width="1582" alt="Screenshot 2024-07-03 at 07 45 00" src="https://github.com/jupyterlab/jupyterlab/assets/17132927/b37fd047-2a9e-4454-a69a-8b456ca442bb">

### Proposed Solution

Change the background color for the `:hover` state in a similar way to the New Launcher button's `:focus-visible` state: https://github.com/jupyterlab/jupyterlab/blob/841b339771d15a5ae0f0f63455eb7ed66b56d921/packages/launcher-extension/style/base.css#L12-L15

... as well as to the other buttons: https://github.com/jupyterlab/jupyterlab/blob/841b339771d15a5ae0f0f63455eb7ed66b56d921/packages/application/style/buttons.css#L35-L37

### Additional context

- Operating System and version: macOS Sonoma 14.5
- Browser and version: Chrome 126.0.6478.127
- JupyterLab version: 4.3.0a1
- Python version: 3.10.13

Let me know what you think and if I can open a PR. Thanks!

**Comment by krassowski** [comment]
Absolutely, a PR would be welcome here! We can likely backport it to 4.2.x as this would be a bug fix in my eyes

**Comment by joaopalmeiro** [comment]
Nice, thanks! I will work on it, then.
