### ISSUE TITLE
Unexpected CSS variable for notebook cell shadows

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/jupyterlab#16543]
Hi! 👋 

## Description

There are some CSS variables to style notebook cells from themes, such as the `--jp-cell-editor-box-shadow` variable: https://github.com/jupyterlab/jupyterlab/blob/841b339771d15a5ae0f0f63455eb7ed66b56d921/packages/theme-light-extension/style/variables.css#L248

However, the CSS variable used for the `box-shadow` property responsible for the slight blue shading around a notebook cell being used is the `--jp-input-box-shadow` variable, that is, the [variable for generic input fields](https://github.com/jupyterlab/jupyterlab/blob/841b339771d15a5ae0f0f63455eb7ed66b56d921/packages/theme-light-extension/style/variables.css#L320): https://github.com/jupyterlab/jupyterlab/blob/ae0ba1db9ea6ab0037270df842cea747305b8153/packages/notebook/style/base.css#L153-L157

<img width="1582" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/17132927/38376743-77b4-4145-9cba-103ec4c9fde4">

For this particular case, given that there is a CSS variable that, from my perspective, exists for notebook cells, I think that the variable currently being used is unexpected, and could lead to erroneous customizations in new themes.

## Expected behavior

The `--jp-cell-editor-box-shadow` variable is used instead of the `--jp-input-box-shadow` variable to customize the shadow of notebook cells.

## Context

- Operating System and version: macOS Sonoma 14.5
- Browser and version: Chrome 126.0.6478.127
- JupyterLab version: 4.2.3
- Python version: 3.10.13

Let me know what you think and if I can open a PR. Thanks!

**Comment by JasonWeill** [comment]
@joaopalmeiro Thank you again! We accepted this issue at triage; please feel free to send us a PR if you have a fix for it.

**Comment by joaopalmeiro** [comment]
Thanks! I will work on it.
