### ISSUE TITLE
Include source in npm package for sourcemaps

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#1655]
Currently, source maps are built and included in the jupyterlab npm package. Unfortunately, as the source itself is not included, the source maps do not actually point anywhere. E.g. when webpacking an app that depends on jupyterlab, I get:

```npm
WARNING in ./~/jupyterlab/lib/rendermime/index.js
Cannot find source file '../../src/rendermime/index.ts': Error: Cannot resolve 'file' or 'directory' ../../src/rendermime/index.ts in <myapp>\node_modules\jupyterlab\lib\rendermime
```

Some possible solutions (there might be more):
 - Include the `src` folder in the npm package.
 - Add the `inlineSources` compiler option, which will embed the relevant source into the built sourcemaps.
 - Remove sourcemaps from package.

The two first options should be equivalent from the perspective of consuming source maps, but there might be other concerns that would give one an advantage. The third option would be the least preferable for me.

**Comment by blink1073** [comment]
Option 1 sounds good to me.
