### ISSUE TITLE
Galata helper to create a notebook for a specified kernel. 

### ISSUE THREAD

**Issue by pauldruce** [jupyterlab/jupyterlab#16553]
### Problem
I want to leverage the Playwright helpers that Galata provides to interact with notebooks. However, we want to start a notebook with a different kernel specified from the normal. 

I would like the method page.notebook.createNew to have an optional field to specify the name of the kernel to use.
Alternatively, I'd like to be able to switch the kernel a notebook is using more easily. 

### Proposed Solution

My proposed solution would be to update the createNew function to have a second optional argument called `options` which is a json structure which contains a field called `kernel` which specifies the name of the kernel you want to open.

I've got a rough working prototype with the code changes at the end of this issue.
Which I've tested with a custom kernel locally - not sure of the best way to update the tests in the repo to validate this new behaviour.

Some guidance on whether this is an appropriate change would be appreciated. 

For file: `galata/src/helpers/notebook.ts`
```ts
  /**
   * Create a new notebook
   *
   * @param name Name of the notebook (optional)
   * @param options Options for creating the notebook (optional)
   * @param options.kernel Name of the kernel to use for the notebook (optional)
   * @returns Name of the created notebook or null if it failed
   */
  async createNew(name?: string, options?: { kernel?: string }): Promise<string | null> {
    await this.menu.clickMenuItem('File>New>Notebook');

    const page = this.page;
    await page.locator('.jp-Dialog').waitFor();

    /************ New code *******************/
    if (options?.kernel) {
      await page.getByRole('dialog').getByRole('combobox').selectOption(`{"name":"${options.kernel}"}`);
    }
   /*****************************************/

    await page.click('.jp-Dialog .jp-mod-accept');

    const activeTab = this.activity.getTabLocator();
    if (!(await activeTab.count())) {
      return null;
    }

    const label = activeTab.locator('div.lm-TabBar-tabLabel');
    if (!(await label.count())) {
      return null;
    }

    const assignedName = await label.textContent();

    if (!name) {
      return assignedName;
    }

    const currentDir = await this.filebrowser.getCurrentDirectory();
    await this.contents.renameFile(
      `${currentDir}/${assignedName}`,
      `${currentDir}/${name}`
    );
    const renamedTab = this.activity.getTabLocator(name);

    return (await renamedTab.count()) ? name : null;
  }
```

**Comment by krassowski** [comment]
I think this would be useful. Note there will be changes to the selection combobox in https://github.com/jupyterlab/jupyterlab/pull/16475 (which even more highlights how useful it could be to have this in galata)

**Comment by pauldruce** [comment]
I'll put up a PR - is there a simple way to mock the list of kernels that is installed somehow? I am just thinking about how to write tests for this. I know Galata has some state mocking abilities - I am just not familiar with them yet.
