### ISSUE TITLE
How to change the JupyterLab logo icon.

### ISSUE THREAD

**Issue by linmeimei0512** [jupyterlab/jupyterlab#16569]
### Problem
I need to change the JupyterLab logo icon from left top.  
![image](https://github.com/jupyterlab/jupyterlab/assets/14798636/047b7582-1e39-48d3-9237-97a8916364ca)  

But I don't found the solution for issues.  
Please who can give me some solution?  
Thank you!

### Additional context

- JupyterLab version : 4.2.3

**Comment by krassowski** [comment]
For an example see https://github.com/nebari-dev/jupyterlab-nebari-mode

Also, pretty sure this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/10409 and https://github.com/jupyterlab/jupyterlab/issues/10409 or both.

**Comment by JasonWeill** [comment]
Closing as a duplicate of #10409. Thanks for your contribution, and thanks @krassowski for finding the duplicate!
