### ISSUE TITLE
Standardize the button type and label for Dismiss/Close buttons in dialogs

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/jupyterlab#16578]
Hi! 👋 

### Problem

Currently, similar buttons for closing dialogs have different button types and labels:

<img width="1582" alt="Screenshot 2024-07-12 at 13 45 52" src="https://github.com/user-attachments/assets/451f2682-61c7-4219-919c-ae92dc9d1c72">
<img width="1582" alt="Screenshot 2024-07-12 at 13 45 59" src="https://github.com/user-attachments/assets/4f73b08b-e371-43d9-9055-55942524be7a">
<img width="1582" alt="Screenshot 2024-07-12 at 13 49 42" src="https://github.com/user-attachments/assets/5f03d073-4ff3-450f-8f7d-6e26cbde070a">
<img width="1582" alt="Screenshot 2024-07-12 at 14 01 39" src="https://github.com/user-attachments/assets/063a1b17-293e-420b-90da-788616758438">
<img width="1582" alt="Screenshot 2024-07-12 at 14 14 36" src="https://github.com/user-attachments/assets/990c65be-0114-47a7-9310-45f005b3c733">
<img width="1582" alt="image" src="https://github.com/user-attachments/assets/27654f63-4f0c-4667-b8f2-d7923133f5c7">

These examples present two button types and two labels:

- Button types: `Dialog.cancelButton()` and `Dialog.okButton()`
- Labels: `Dismiss` and `Close`

Assuming there is no historical or functional reason for such differences, I think it would be beneficial to standardize the button type and label for the button to close dialogs.

### Proposed Solution

Personally, I don't have a strong opinion about the button type and label to follow. I would say a combination of `Dialog.cancelButton()` and `Close` (I feel like _Dismiss_ is more typical of JupyterLab, but _Close_ is simpler) works.

Nevertheless, a possible solution would be to go to the following files and change the button type and/or label:

- https://github.com/jupyterlab/jupyterlab/blob/804398451328f39a3705cdc2ecf0593651ebf218/packages/filebrowser/src/listing.ts#L1488
- https://github.com/jupyterlab/jupyterlab/blob/804398451328f39a3705cdc2ecf0593651ebf218/packages/apputils-extension/src/shortcuts.tsx#L197
- https://github.com/search?q=repo%3Ajupyterlab%2Fjupyterlab+trans.__%28%27Dismiss%27%29&type=code

### Additional context

- Operating System and version: macOS Sonoma 14.5
- Browser and version: Chrome 126.0.6478.127
- JupyterLab version: 4.3.0a2
- Python version: 3.10.13

Let me know what you think and if I can open a PR. Thanks!

**Comment by JasonWeill** [comment]
@joaopalmeiro As part of standardizing this behavior, I would also recommend adding a section to the contributor documentation of JupyterLab providing guidance to developers about dialog buttons, inspired by existing practices such as the [Apple Human Interface Guidelines (HIG)](https://developer.apple.com/design/human-interface-guidelines/buttons).
