### ISSUE TITLE
Standardize the "go-to-line" input field using theme CSS variables

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/jupyterlab#16577]
Hi! 👋 

### Problem

Right now, the ["go-to-line"/_Go to line number_ input field](https://github.com/jupyterlab/jupyterlab/blob/7bae8e3238967a0a776028150b49a4903759bc90/packages/codeeditor/src/lineCol.tsx#L72), accessible from the JupyterLab bottom toolbar, is inconsistent with other similar input fields. This input field is styled via _hard coded_ values ​​(instead of certain CSS variables), for example, and its value is not properly centered:

https://github.com/jupyterlab/jupyterlab/blob/7bae8e3238967a0a776028150b49a4903759bc90/packages/codeeditor/style/linecol.css#L66-L69

<img width="1582" alt="image" src="https://github.com/user-attachments/assets/1ce55835-18f0-4457-ab09-af6605df7596">

### Proposed Solution

Following recent standardization efforts (e.g., https://github.com/jupyterlab/jupyterlab/pull/16548), the "go-to-line"/_Go to line number_ input field styles could be updated to adopt the border radius defined in one of the CSS variables (`--jp-border-radius`), as well as other CSS variables (including one adjustment to center the value within the field):

```diff
.jp-baseLineForm {
  /* ... */
+ border-top-right-radius: var(--jp-border-radius);
+ border-bottom-right-radius: var(--jp-border-radius);
}
```

```diff
.jp-lineFormWrapper {
  /* ... */
+ border-top-left-radius: var(--jp-border-radius);
+ border-bottom-left-radius: var(--jp-border-radius);
}
```

```diff
.jp-lineFormWrapperFocusWithin {
- border: var(--jp-border-width) solid var(--md-blue-500, #2196f3);
- box-shadow: inset 0 0 4px var(--md-blue-300, #64b5f6);
+ border: var(--jp-border-width) solid var(--jp-input-active-border-color);
+ box-shadow: var(--jp-input-box-shadow);
}
```

```diff
.jp-lineFormInput {
  /* ... */
- line-height: 28px;
+ padding: 0;
+ /* or */
+ padding-top: 0;
+ padding-bottom: 0;
+ /* or */
+ box-sizing: border-box;
}
```

Therefore, this input field could look like this:

<img width="1582" alt="image" src="https://github.com/user-attachments/assets/ec063a50-70b2-41d0-b0ae-cdbfee70c284">

### Additional context

- Operating System and version: macOS Sonoma 14.5
- Browser and version: Chrome 126.0.6478.127
- JupyterLab version: 4.3.0a1
- Python version: 3.10.13

Let me know what you think and if I can open a PR. Thanks!

**Comment by JasonWeill** [comment]
@joaopalmeiro Thank you so much for your interest in improving JupyterLab's CSS! Tagging @Mehak261124, who has been working on additional CSS-related improvements as part of a Google Summer of Code (GSoC) project. I want to make sure that you two coordinate your changes, so that you don't have inadvertent conflicts.

**Comment by joaopalmeiro** [comment]
Thank you very much for the feedback, @JasonWeill!

In terms of changes regarding this issue, what I had in mind is just what I've already documented above. 

@Mehak261124, what do you think? Where is the best place to check your work to see if there are any conflicts? Thanks!

**Comment by Mehak261124** [comment]
Thank you so much,  @JasonWeill, for tagging me in this issue. 
Hey @joaopalmeiro , I'm currently working on my GSOC project titled "Improve user experience using the Jupyter toolkit." This project is focused on enhancing the user interface of JupyterLab by incorporating the Jupyter UI Toolkit into its core components. This will replace the various types of interface elements with the toolkit's unified components, resulting in a more consistent interface that is easier to maintain. You can check out the changes on my task PRs: https://github.com/jupyterlab/jupyterlab/pull/16488 and https://github.com/jupyterlab/jupyterlab/pull/16438. Although we are not updating this component right now, moving forward, adopting a standard component library will be crucial for proper standardization.

**Comment by joaopalmeiro** [comment]
Thanks for sharing these PRs with me, @Mehak261124. Tremendous work! Looking forward to seeing these improvements in JupyterLab!

> Although we are not updating this component right now, moving forward, adopting a standard component library will be crucial for proper standardization.

I agree! Here's my suggestion: although the suggestions in this issue are not enough to guarantee standardization, I think they are a good small step forward, as the various implementations of input fields become more similar to each other. So, I would implement these changes in JupyterLab (or similar, depending on the feedback), given that they are low-hanging fruit (whether implementing or validating) and a relevant step towards standardizing this type of component.

What do you think?

**Comment by Mehak261124** [comment]
Thank you so much @joaopalmeiro 
Your suggestion makes a lot of sense. While the proposed changes might not fully guarantee standardization, they represent a positive step towards making various implementations of input fields more consistent. Implementing these changes in JupyterLab ( based on feedback) is a practical approach, especially since they are relatively straightforward to implement and validate. This makes it a relevant step towards the broader goal of standardizing these components.

I think it's a good idea and worth pursuing.
