### ISSUE TITLE
Add untitled files to the root `.gitignore` file

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/jupyterlab#16579]
Hi! 👋 

### Problem

When working on a PR, for example, and creating _disposable_ files via the Launcher for testing purposes, these files are not ignored by Git. Since these files are not ignored, extra care is needed when committing. 

The files in question are the files that start with `Untitled` or `untitled`:

- `Untitled.ipynb`
- `untitled.md`
- `untitled.py`
- `untitled.txt`

### Proposed Solution

Add the following entries to the [root `.gitignore` file](https://github.com/jupyterlab/jupyterlab/blob/main/.gitignore):

```plain
Untitled*.ipynb
untitled*.md
untitled*.py
untitled*.txt
```

### Additional context

- Operating System and version: macOS Sonoma 14.5
- Browser and version: Chrome 126.0.6478.127
- JupyterLab version: 4.3.0a2
- Python version: 3.10.13

Let me know what you think and if I can open a PR. Thanks!

**Comment by JasonWeill** [comment]
I typically run my dev-mode servers from a separate "playground" directory on my PC, to avoid modifying the source repo at all, but I think this is a pretty low-risk change.
