### ISSUE TITLE
Add a command to quickly serve documentation files locally

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/jupyterlab#16573]
Hi! 👋 

### Problem

When contributing to the documentation, https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#writing-documentation, no commands are documented to quickly serve the generated files and browse the documentation website locally.

#### First Alternative

Add the command to launch an HTTP server via Python, along with the `cd docs` and `make html` commands, similar to the [Visual Regression and UI Tests section](https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#visual-regression-and-ui-tests):

```bash
python -m http.server --directory build/html
```

#### Second Alternative

Update the Sphinx documentation [Makefile](https://github.com/jupyterlab/jupyterlab/blob/main/docs/Makefile) and [batch file](https://github.com/jupyterlab/jupyterlab/blob/main/docs/make.bat) to include a command to `serve` the website, as well as add a reference to this command alongside the `cd docs` and `make html` commands.

### Additional context

- Operating System and version: macOS Sonoma 14.5
- Browser and version: Chrome 126.0.6478.127
- JupyterLab version: 4.3.0a1
- Python version: 3.10.13

Let me know what you think and if I can open a PR. Thanks!

**Comment by JasonWeill** [comment]
@joaopalmeiro Thanks for opening this! I usually open the generated docs' `index.html` file in a web browser locally, but I agree that adding a command and documenting it would make documentation development easier.
