### ISSUE TITLE
Convert `@jupyterlab/completer` type colors to theme CSS variables

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/jupyterlab#16589]
Hi! 👋 

### Problem

The type annotation colors for the [code completer](https://github.com/jupyterlab/jupyterlab/tree/main/packages/completer) are _hard-coded_ in a stylesheet: https://github.com/jupyterlab/jupyterlab/blob/7bae8e3238967a0a776028150b49a4903759bc90/packages/completer/style/base.css#L139-L181

<img width="1582" alt="Screenshot 2024-07-15 at 18 38 58" src="https://github.com/user-attachments/assets/2c0bfb5e-e89d-42af-b6fc-d0a69a512269">

<img width="1582" alt="Screenshot 2024-07-15 at 18 39 07" src="https://github.com/user-attachments/assets/d9588a8b-0970-4b91-b8ce-4c7b51dd856b">

Therefore, these colors are not customizable from a JupyterLab theme similar to CodeMirror/syntax highlighting colors, for example: https://github.com/jupyterlab/jupyterlab/blob/7bae8e3238967a0a776028150b49a4903759bc90/packages/theme-light-extension/style/variables.css#L334-L359

### Proposed Solution

Convert [_hard-coded_ colors](https://github.com/jupyterlab/jupyterlab/blob/7bae8e3238967a0a776028150b49a4903759bc90/packages/completer/style/base.css#L139-L181) to CSS variables defined in JupyterLab themes. To facilitate their association with indexes, the names of these variables could include their known types:

https://github.com/jupyterlab/jupyterlab/blob/7bae8e3238967a0a776028150b49a4903759bc90/packages/completer/src/model.ts#L587

https://github.com/jupyterlab/jupyterlab/blob/7bae8e3238967a0a776028150b49a4903759bc90/packages/completer/src/widget.ts#L1290-L1311

### Additional context

- Operating System and version: macOS Sonoma 14.5
- Browser and version: Chrome 126.0.6478.127
- JupyterLab version: 4.3.0a2
- Python version: 3.10.13

Let me know what you think and if I can open a PR. Thanks!

**Comment by krassowski** [comment]
Some thoughts:

> Therefore, these colors are not customizable from a JupyterLab theme

Themes should be able to override this by repeating the CSS rules, right?

If were to keep the colors based on order the categories came in, then having a set of variables is not so clearly advantageous because there will be many of them and each will be used only once.

I like the idea of including the types. I am not sure if these should be included in a generated class name or in a `data-` attribute. I am coming from the perspective of having the completer highly optimized for performance even when JupyterLab is displaying millions of objects, so I would prefer whichever is faster (my guess is it would be the class approach but it would require benchmarking).

**Comment by joaopalmeiro** [comment]
> Themes should be able to override this by repeating the CSS rules, right?

Yes, of course! I should have emphasized that this suggestion is more about making the "Theming API" more powerful and consistent with a single place, as far as possible, with all the customizable style variables.

> If were to keep the colors based on order the categories came in, then having a set of variables is not so clearly advantageous because there will be many of them and each will be used only once.

I'm not sure I understand your point, sorry. As the set of possible colors is currently finite, I'm assuming it should stay that way and that it is sufficient. 

Anyway, about including the type names, I'm not completely convinced, but I thought it would be interesting to leave the idea up for discussion. Initially, I was just thinking about CSS variable names for Developer Experience, given that the set of known types is finite and has a pre-determined order, but your last paragraph got me thinking that what I'm really suggesting is a non-negligible refactoring to make everything consistent, where performance is fundamental. So, I think keeping this simple and converting the colors to CSS variables based on the indexes would be enough of an improvement.

**Comment by joaopalmeiro** [comment]
My revised proposed solution, based on @krassowski's thoughts, is to add the following snippet to each of JupyterLab's default themes (`variables.css` file):

```css
/* Completer specific styles */

--jp-completer-type-background0: transparent;
--jp-completer-type-background1: #1f77b4;
--jp-completer-type-background2: #ff7f0e;
--jp-completer-type-background3: #2ca02c;
--jp-completer-type-background4: #d62728;
--jp-completer-type-background5: #9467bd;
--jp-completer-type-background6: #8c564b;
--jp-completer-type-background7: #e377c2;
--jp-completer-type-background8: #7f7f7f;
--jp-completer-type-background9: #bcbd22;
--jp-completer-type-background10: #17becf;
```

This snippet follows the `--jp-mirror-editor-*` and `--jp-collaborator-*` CSS variable sets.
