### ISSUE TITLE
hubServerName not used when restarting JupyterHub after network disconnetion

### ISSUE THREAD

**Issue by NisTa24** [jupyterlab/jupyterlab#16603]
Hello all, I am using JupyterHub on a k8s environment and whenever my network disconnects, clicking on the `restart` button in the popup is supposed to restart the same JupyterHub instance but instead, a new instance of the JupyterHub without the servername is created. For e.g., if I am working on a lab with the url `https://.../user/my-user-id/servername`, then clicking on the restart button creates a new JupyterHub instance without the servername `https://.../user/my-user-id/servername`.
Looking at the `hub-extension` code, the `hubExtension` uses the `paths.urls.hubServerName` to get the servername and looking more deeper, the servername is fetched from the DOM element with the id `jupyter-config-data`. This works fine and as expected when launching the JupyterHub at the start but if the network disconnects and reconnects back after some time, clicking on the `Restart` button starts a new one without a servername and I would like to avoid this.

![test](https://github.com/user-attachments/assets/52d009d0-44a7-42a3-972b-d0962ddd360f)

**Comment by krassowski** [comment]
Are you by any chance using JupyterLab v4.2.2 or older? I think this was fixed in https://github.com/jupyterlab/jupyterlab/pull/16471 which was included in v4.2.3 and higher.

**Comment by NisTa24** [comment]
> Are you by any chance using JupyterLab v4.2.2 or older? I think this was fixed in #16471 which was included in v4.2.3 and higher.

@krassowski thank you for the response. I am using v4.1.5. I will update the JL version and if it works as expected I will close this issue.

**Comment by NisTa24** [comment]
I just tested it out with version 4.2.4 and it works now.
