### ISSUE TITLE
"Shortcut already in use" warning remains even after pressing "Cancel" when overriding shortcuts

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab#16612]
## Description

The "Shortcut already in use" warning remains even when "Cancel" is pressed on the UI. Here's a gif - 

![shortcut-already-exists](https://github.com/user-attachments/assets/9af8b4cf-422f-434d-99ac-1782df716bb2)

## Reproduce
Reproducer is in the above GIF

## Expected behavior

The warning should disappear once the Cancel button is pressed.

## Context

- JupyterLab version - 4.2.3

**Comment by krassowski** [comment]
Thank you! I can reproduce without extensions on the `main` branch:

![cancel-does-nothing](https://github.com/user-attachments/assets/d9d4b448-efe7-4b8a-be5e-27ac1700e298)
