### ISSUE TITLE
JupyterLab context menu appears when right-clicking in an interactive plot

### ISSUE THREAD

**Issue by EdsterG** [jupyterlab/jupyterlab#16619]
## Description
Right clicking in an interactive plot should not open a JupyterLab context menu. This seems to happen with all interactive plots, even from other libraries, e.g. Panel.

https://private-user-images.githubusercontent.com/3106867/352610421-ffc72f84-e572-4426-b5a4-a7403e242452.mov

## Reproduce

Plot any interactive plots and right click on it.

## Expected behavior

No context menu when right clicking in an interactive plot.

## Context

- Operating System and version: MacOS
- Browser and version: Brave and Firefox
- JupyterLab version: 4.2.4

**Comment by JasonWeill** [comment]
There is an `data-lm-suppress-shortcuts="true"` attribute that suppresses Lumino keyboard shortcuts in elements in JupyterLab. It seems like we could use another attribute to suppress the right-click mouse event.

Fixing this bug may require changes to both JupyterLab, Lumino, and potentially your third-party visualization library as well.

**Comment by EdsterG** [comment]
@JasonWeill thanks for the follow up. Looking forward to the new right-click mouse event suppression attribute.

Regarding `data-lm-suppress-shortcuts="true"` is it supposed to enable capturing of `control` and `super`? I recently added it to fix shortcut suppression in Makie, but `control` and `super` still don't seem to be captured. Is this known or should I open another issue for it?

**Comment by JasonWeill** [comment]
@EdsterG It looks like this code lives in Lumino (`lm`), so you might want to open an issue in that project: https://github.com/jupyterlab/lumino/issues

**Comment by fcollonval** [comment]
There is a similar trick for the context menu with the attribute `data-jp-suppress-context-menu`.

Note it is unclear if this should be solved in core JupyterLab as we don't control the renderer used for a given output. It should be up to the mime renderer to decide what is the best behavior regarding the context menu.

**Comment by krassowski** [comment]
Thanks @fcollonval! And it is already documented in Extension Points section: https://jupyterlab.readthedocs.io/en/latest/extension/extension_points.html#context-menu.

Maybe we should have a dedicated section of widget authors/MIME renderers who are likely to use this feature. I think we can close this issue as this is down to specific output libraries to decide if they want to suppress JupyterLab menu or not.

**Comment by EdsterG** [comment]
Nice, adding `data-jp-suppress-context-menu` solves the problem.
