### ISSUE TITLE
Error rendering .ipynb file with array value in a "text/plain" cell output data field

### ISSUE THREAD

**Issue by box-turtle** [jupyterlab/jupyterlab#16623]
## Description

I am re-using the notebook component outside of JupyterLab. While trying to load an .ipynb file with the following structure, I receive an unhandled exception and the page does not load. The relevant part of the structure is that the output data contains a string[] and not a string.

```
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Success: 0 rows affected"
      ]
     }
      ...
    }
```

## Reproduce

load an .ipynb file with an array instead of a string in the ouput.data["text/plain"] field

Debugging in the browser led me to [the code here](https://github.com/jupyterlab/jupyterlab/blob/main/packages/notebook/src/windowing.ts#L64):

```
  estimateWidgetSize = (index: number): number => {
    const model = this.cells[index].model;
    const height = this.cellsEstimatedHeight.get(model.id);
    if (typeof height === 'number') {
      return height;
    }

    const nLines = model.sharedModel.getSource().split('\n').length;
    let outputsLines = 0;
    if (model instanceof CodeCellModel) {
      for (let outputIdx = 0; outputIdx < model.outputs.length; outputIdx++) {
        const output = model.outputs.get(outputIdx);
        outputsLines = ((output.data['text/plain'] as string) ?? '').split(        // <--- error occurs here
          '\n'
        ).length;
      }
    }
    return (
      NotebookViewModel.DEFAULT_EDITOR_LINE_HEIGHT * (nLines + outputsLines) +
      NotebookViewModel.DEFAULT_CELL_MARGIN
    );
  };
```

I believe the issue is that simply casting an array to string `output.data['text/plain'] as string` results in undefined rather than a string, so the call to `split` fails. I think we need to check whether the value is a string or string[] and handle accordingly.

## Expected behavior

the notebook file renders

## Context

- Operating System and version: Mac Sonomo 14.5
- Browser and version: Chrome Version 126.0.6478.185
- JupyterLab version: 4.2.3

**Comment by krassowski** [comment]
I saw a related error in review of #16498 too, this is why the code should never use `as` casts unless in type guards or tests. A PR  here (with a fix, or unit test, or both) would be very welcome!

**Comment by JasonWeill** [comment]
Although I think that the linked PR will improve performance, I'm not sure that the output data's use of a string array is the root cause of your issue. I created a notebook with one cell, and I noticed that its output is an array of strings. JupyterLab 4.3 alpha renders it as expected. Here's the source of my notebook:

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0e0f77a1-4d9b-41df-b080-cb9b028b8dbe",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "2+2"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

**Comment by krassowski** [comment]
@JasonWeill the referenced logic may only kick in in larger notebooks, once windowing is active. I would test with much larger notebook (50 or 100 cells) and ensure you have windowing mode set to `full`.

**Comment by krassowski** [comment]
So this looks like `text/plain` is not the only key in use, but we also have:
- `application/vnd.jupyter.stderr` for tracebacks
- `text/plain` for return values e.g. `1 + 1`
- `application/vnd.jupyter.stdout` for printed output

It looks like JupyterLab in general does concatenate the list into a single string for all of these, even if they are stored on disk as a list. Still, we should fix this to full fill the API contract.

**Comment by jasongrout** [comment]
> It looks like JupyterLab in general does concatenate the list into a single string for all of these, even if they are stored on disk as a list.

It's actually nbformat doing the multiline string <-> array of strings conversion when it reads/writes the file on disk. Quoting from the [format spec](https://nbformat.readthedocs.io/en/latest/format_description.html#top-level-structure)

> Some fields, such as code input and text output, are characteristically multi-line strings. When these fields are written to disk, they may be written as a list of strings, which should be joined with '' when reading back into memory. In programmatic APIs for working with notebooks (Python, Javascript), these are always re-joined into the original multi-line string. If you intend to work with notebook files directly, you must allow multi-line string fields to be either a string or list of strings.
