### ISSUE TITLE
Standardize dialogs to shut down all kernels

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/jupyterlab#16624]
Hi! 👋 

### Problem

The dialogs to confirm or cancel the action of shutting down all kernels are different depending on whether this action is triggered from the sidebar or the command palette:

<img width="1582" alt="Screenshot 2024-07-29 at 17 59 32" src="https://github.com/user-attachments/assets/445f0986-fe0e-474c-af2f-13e4910a1d89">

<img width="1582" alt="Screenshot 2024-07-29 at 17 59 42" src="https://github.com/user-attachments/assets/562ec158-f24b-4268-b5d8-fd20672445d4">

The body text and the cancel button label are not standardized.

### Proposed Solution

Adopt the body text and the cancel button label of the dialog when the action of shutting down all kernels is triggered from the sidebar: https://github.com/jupyterlab/jupyterlab/blob/78cd6b60e5eb43b1278d825290ac81fd378faed6/packages/running-extension/src/kernels.tsx#L88-L97

... in the equivalent dialog when the same action is triggered from the command palette: https://github.com/jupyterlab/jupyterlab/blob/78cd6b60e5eb43b1278d825290ac81fd378faed6/packages/mainmenu-extension/src/index.ts#L535-L555

### Additional context

- Operating System and version: macOS Sonoma 14.5
- Browser and version: Chrome 127.0.6533.72
- JupyterLab version: 4.3.0a2
- Python version: 3.10.13

Let me know what you think and if I can open a PR. Thanks!

**Comment by krassowski** [comment]
Good catch! I think it's pretty clear cut that standardising it would be welcome. As to wording I wonder if it should mention the  number of kernels that will be shut down.
