### ISSUE TITLE
JupyterLab suppresses left mouse up while holding shift.

### ISSUE THREAD

**Issue by EdsterG** [jupyterlab/jupyterlab#16633]
## Description

When left clicking in an interactive plot, JupyterLab suppresses the mouse up event while `shift` is held. This only applies to left clicks, right clicks are correctly forwarded to the plot even if `shift` is held. This only happens in JupyterLab, I ran the interactive plot outside of JupyterLab and left mouse up events were properly forwarded to the plot.

https://github.com/user-attachments/assets/6a39d729-16cd-4cca-8d27-b1ec848f2263

## Reproduce

Display an interactive plot and `shift` + `left click` in the plot.

## Expected behavior

Left mouse up events should be forwarded regardless if the `shift` key state.

## Context

- Operating System and version: MacOS
- Browser and version: Brave
- JupyterLab version: 4.2.4

The plot element has `data-lm-suppress-shortcuts=true` and `data-jp-suppress-context-menu` set.

**Comment by JasonWeill** [comment]
@EdsterG Thanks for opening this issue! Do you know what is capturing the `mouseup` event when <kbd>SHIFT</kbd> is being held? You can find some tips here: https://stackoverflow.com/questions/10213703/how-do-i-view-events-fired-on-an-element-in-chrome-devtools

**Comment by EdsterG** [comment]
I was able to recreate this without the plot. Just print anything to the output, e.g. `println("")`, and click in the output box. This also happens in multiple browsers, Brave and Firefox. Since I'm not a frontend dev, hard to tell what information is useful for this issue. Here's what I have from Brave:
![Screenshot 2024-08-06 at 11 08 00 AM](https://github.com/user-attachments/assets/8a6b440f-6100-4e12-a058-6c90946de696)
and here's what I have from Firefox:
![Screenshot 2024-08-06 at 11 08 30 AM](https://github.com/user-attachments/assets/c2d54f3c-6cf3-430f-8069-5c767232cd24)

Something swallows `mouseup` but can't tell what it is.

**Comment by EdsterG** [comment]
After a little brute force disabling of event handlers in Firefox, here's the one that needs to be disabled to fix the issue:

![Screenshot 2024-08-06 at 11 44 16 AM](https://github.com/user-attachments/assets/42026a49-9eb2-4e50-8ecc-2ff24408972d)

Please let me know how else I can contribute to help find the root cause.

**Comment by EdsterG** [comment]
Zooming in on that switch statement:
```
    case "contextmenu":
      if (e.eventPhase === Event.CAPTURING_PHASE) {
        this._evtContextMenuCapture(e)
      }
      break;
    case "mousedown":
      if (e.eventPhase === Event.CAPTURING_PHASE) {
        this._evtMouseDownCapture(e)
      } else {
        if (!e.defaultPrevented) {
          this._evtMouseDown(e)
        }
      }
      break;
    case "mouseup":
      if (e.currentTarget === document) {
        this._evtDocumentMouseup(e)
      }
      break;
    case "mousemove":
      if (e.currentTarget === document) {
        this._evtDocumentMousemove(e)
      }
      break;
    case "keydown":
      this._ensureFocus(true);
      break;
```
Could it be that mouseup is missing a condition? Or was there a different side effect from disabling this event handler?

**Comment by krassowski** [comment]
Thanks for narrowing it down @EdsterG! Looking at the code I think it could be due to the preceding `mousedown` handler as it has some logic which interprets shift + click specially:

https://github.com/jupyterlab/jupyterlab/blob/653c22621f996249862093d0bb0f23b1279b0f52/packages/notebook/src/widget.ts#L2671-L2695

This is used to select multiple cells with shift + click. I think there should be a check added so that if the selected cell == current cell then it short-circuits and does nothing. Would you be willing to open a PR for this one?
