### ISSUE TITLE
Upgrade to ydoc stable before JupyterLab 4.3 release

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16649]
Small note, if we start using alpha here we should create an issue in jupyterlab that forces us to wait for stable 3.0.0 prior to 4.3.0 release.

_Originally posted by @fcollonval in https://github.com/jupyterlab/jupyterlab/pull/16498#discussion_r1667337588_

**Comment by jtpio** [comment]
In the last [weekly call](https://github.com/jupyterlab/frontends-team-compass/issues/251#issuecomment-2434488012) there were some discussions about addressing https://github.com/jupyter-server/jupyter_ydoc/issues/269 later, to not block the `4.3.0` final release.
