### ISSUE TITLE
Shutdown item in running panel is broken

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#16645]
## Description

Currently the click on the shutdown button of an running panel item is broken.
This is a consequence of the tree view PR.

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Expected behavior

Shutdown buttons work

## Context

- Operating System and version:debian
- Browser and version: chrome
- JupyterLab version: current master

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
@fcollonval Are you working on this issue? I was able to reproduce it myself.

**Comment by fcollonval** [comment]
I'll work on a fix for this this coming week.
