### ISSUE TITLE
Cannot use the default "accept" keyboard shortcut for code completions on Mac

### ISSUE THREAD

**Issue by ctcjab** [jupyterlab/jupyterlab#16662]
## Description

The default "accept" keyboard shortcut for code completions is "Option + End". I am using a MacBook, where there is no dedicated "End" key. To input an "End" keystroke on all Apple keyboards with no dedicated "End" key, you have to press Cmd+Right arrow. But pressing "Option+Cmd+Right arrow" to accept the current code completion does not work. 

Perhaps Windows or Linux users with keyboards with no "End" key experience a similar issue.

Can you change the default keyboard shortcut to "Tab", to match the default "accept completion" shortcut in other common environments (e.g. VSCode + GitHub Copilot)? Or else, some other shortcut that works out-of-the-box in common Mac environments?

## Reproduce

1. On a Mac, open a new notebook in JupyterLab with the latest jupyter-ai extension (2.20.0) installed and configured
2. Type a prompt like `def foo():` and wait for your configured model to provide a completion
3. Try accepting the completion via the default Option+End keyboard shortcut without hitting the "End" key

## Expected behavior

Mac users can accept the current completion using the default keyboard shortcut

## Context

Reproduced in a JupyterHub environment as well as with a jupyterlab server running locally.

**Comment by krassowski** [comment]
Thanks for reporting the Mac keyboard problem, and thanks Jason for transferring the issue!

Issue https://github.com/jupyterlab/jupyterlab/issues/16065 already discussed change of the default keyboard shortcut and there is a draft PR so we may want to consolidate the discussion there.

Also, I will note that we do have an option to set keyboard shortcuts different for specific operating systems.

**Comment by JasonWeill** [comment]
Good catch! I thought this looked familiar, but didn't find #16065. Let's continue the conversation there.
