### ISSUE TITLE
Optimize SVG icons from `@jupyterlab/ui-components` and update SVGO config

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/jupyterlab#16672]
Hi! 👋 

### Problem

While there have been efforts in the past to clean up the SVG icons available in [`@jupyterlab/ui-components`](https://github.com/jupyterlab/jupyterlab/tree/67cb8f8347f13d52dc100f33fb532acbf36b3b23/packages/ui-components/style/icons) and keep them as small as possible, it is still possible to further optimize them (as well as keep them consistent in terms of indentation, attribute order, etc.).

By doing so, either by minifying the SVG icons or pretty printing them via SVGO, as well as via some manual adjustments, it is possible to reduce the size of most icons (there are some cases where this reduction is to about half of the original size). This reduction also affects the respective packaged JS file served by JupyterLab (since SVG files are _stringified_ and included in the bundle):

<img width="1582" alt="Screenshot 2024-08-13 at 13 18 33" src="https://github.com/user-attachments/assets/fbac5da9-50d8-4ded-87b5-204fee2bd4f9">

### Proposed Solution

To optimize the SVG icons, I think there are three tasks that can be done:

1. Update the SVGO configuration and the respective command in the `package.json` file (see the snippet below). The YAML format is no longer supported since [SVGO 2.0.0](https://github.com/svg/svgo/releases/tag/v2.0.0).
2. Run SVGO to optimize the current icons. I would suggest minifying them as much as possible by removing [`js2svg` from the configuration](https://github.com/jupyterlab/jupyterlab/blob/67cb8f8347f13d52dc100f33fb532acbf36b3b23/packages/ui-components/svgo.yaml#L70-L76), but pretty printing them works too.
3. Remove attribute values ​​and unnecessary SVG elements manually from some icons:
    - Some icons, like the [`yaml.svg` icon](https://github.com/jupyterlab/jupyterlab/blob/67cb8f8347f13d52dc100f33fb532acbf36b3b23/packages/ui-components/style/icons/filetype/yaml.svg), have Adobe Illustrator classes (`st*` classes) that can be removed, if I'm correct.
    - Some icons, like the [`error.svg` icon](https://github.com/jupyterlab/jupyterlab/blob/67cb8f8347f13d52dc100f33fb532acbf36b3b23/packages/ui-components/style/icons/error.svg), have an invisible placeholder element (`<path fill="none" ... />`) to define, I believe, the desired frame/size for the final icon. This element can also be removed as the desired frame for the icon is maintained. This result can also be obtained via an SVGO plugin: `{ name: "removeUselessStrokeAndFill", params: { stroke: true, fill: true, removeNone: true } }`.

```json
"scripts": {
  "cleansvg": "svgo --folder style/icons --recursive"
}
```

### Additional context

- Operating System and version: macOS Sonoma 14.5
- Browser and version: Chrome 127.0.6533.89
- JupyterLab version: 4.3.0a2
- Python version: 3.10.13
- Related issues/PRs:
    - https://github.com/jupyterlab/jupyterlab/issues/16673
    - https://github.com/jupyterlab/jupyterlab/pull/16666

Let me know what you think and if I can open a PR. Thanks!

**Comment by krassowski** [comment]
Some previous related discussions:
- https://github.com/jupyterlab/jupyterlab/issues/8932
- https://github.com/jupyterlab/jupyterlab/issues/14402

**Comment by krassowski** [comment]
I am of opinion that minification by removing whitespace should be done at the webpack level rather than in the assets as stored on disk. Not a strong opinion though.

**Comment by joaopalmeiro** [comment]
> I am of opinion that minification by removing whitespace should be done at the webpack level rather than in the assets as stored on disk. Not a strong opinion though.

I had in mind to make as few changes as possible and reduce the size of the SVG files since this repo is already large as well. In any case, I don't have strong opinions.

So, is your idea to modify the Webpack configuration ([this one?](https://github.com/jupyterlab/jupyterlab/blob/main/jupyterlab/staging/webpack.config.js)) and use the [SVGO loader](https://github.com/svg/svgo-loader), so that the SVGs are only minified when the JS bundle is generated?

**Comment by joaopalmeiro** [comment]
> Some previous related discussions:
> 
> * [Remove xmlns from lab icons? #8932](https://github.com/jupyterlab/jupyterlab/issues/8932)
> * [Accessible (and higher-performance) icons #14402](https://github.com/jupyterlab/jupyterlab/issues/14402)

Thanks for sharing those issues, @krassowski! I left some comments there. Let me know what you think of the proposal implemented in the https://github.com/jupyterlab/jupyterlab/pull/16678 PR, please.

**Comment by krassowski** [comment]
> Webpack configuration ([this one?](https://github.com/jupyterlab/jupyterlab/blob/main/jupyterlab/staging/webpack.config.js))

So currently we use terser but with very lenient options here, I think the addition would also go the the file where terser plugin is defined:

https://github.com/jupyterlab/jupyterlab/blob/3d925e3a6cb2c5a3c1c4267406cad785e6fa2542/jupyterlab/staging/webpack.prod.minimize.config.js#L20-L36

And we use the raw string loader for SVG here:

https://github.com/jupyterlab/jupyterlab/blob/3d925e3a6cb2c5a3c1c4267406cad785e6fa2542/packages/ui-components/src/svg.d.ts#L4-L13

Instead of raw string loader we could use svgo loader or similar. The point is that I think there is some value in manually reviewing the code of SVGs in the repo so having them nicely indented is nice.

I think https://github.com/jupyterlab/jupyterlab/pull/16678 is fine and would be happy to merge straightaway if not for the removal of indentation which again I think we should still do but not directly on the files but in flight during compilation. Otherwise we can wait and see what other folks think about removing indentation and if there is a consensus then merge without changes.

**Comment by joaopalmeiro** [comment]
Got it, thanks!

Based on your perspective, I think we can do this in steps, changing the scope of the open PR to "Clean up" rather than "Optimize". In fact, there are other related issues open (https://github.com/jupyterlab/jupyterlab/issues/8932, https://github.com/jupyterlab/jupyterlab/issues/14402, and https://github.com/jupyterlab/jupyterlab/issues/16673) and we could also have one to "optimize SVGs in the final bundle". What do you think?

**Comment by krassowski** [comment]
Yes, that sounds like a great plan!
