### ISSUE TITLE
Debugger setup instructions are out of date

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#16675]
## Description

The debugger instructions include a `conda` command that installs JupyterLab version 3, not version 4:

https://github.com/jupyterlab/jupyterlab/blob/67cb8f8347f13d52dc100f33fb532acbf36b3b23/docs/source/user/debugger.rst?plain=1#L33-L36

These instructions need to be updated to remove reference to JupyterLab 3.

**Comment by jtpio** [comment]
This is likely a leftover from when the debugger was added to core JupyterLab, to make sure users would install the latest JupyterLab which at the time was version 3.

I opened https://github.com/jupyterlab/jupyterlab/pull/16683 to fix this.
