### ISSUE TITLE
Advanced editor usage

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#1670]
Currently [nbdime](http://github.com/jupyter/nbdime) uses the old/deprecated `CodeMirrorWidget` as the base of its editors. This gives styling/behavior of the editor similar to that of jupyterlab (ease of maintenance, uniform visual profile etc.), while allowing nbdime to add some more advanced features to the CodeMirror instances. With the recent abstraction of the editor in jupyterlab, this has become more convoluted to achieve, as the raw CM editors are behind some extra layers.

I'd prefer to continue using JupyterLab's CodeMirror widgets, but by bringing this up I want to:
 1. Ensure that it will remain possible to ask jupyterlab for a specific implementation of the editor (i.e. "give me something similar to the old `CodeMirrorWidget`"), without too much hassle. I.e. when the abstraction doesn't give all the features wanted, it would be nice to have direct access to the underlying machinery.
 2. If at all possible, it would be nice to have (some/all) of the needed functionality added to the abstract interface.

Some of the things that nbdime uses from the raw CodeMirror editor, that are currently not available in the abstract interface:
 - Highlighting of text (whole lines and/or character range).
 - Adding clickable gutter entries (e.g. for conflict markers).
 - Line alignments across two or more editors (e.g. aligning similar lines in a diff when lines were added/removed). E.g. by adding spacer elements between lines (current implementation).
 - Collapsing parts of the content (i.e. hiding parts of the content and replacing them with an ellipsis (...) button, which can be clicked to again show said content). This is to hide large sections of unchanged text.
 - Synchronized scrolling between two editors (not critical).

In addition, it listens to CM's `change` events for editing/updating, but this can likely be replaced by the observable strings of jupyterlab.

**Comment by blink1073** [comment]
Thinking out loud, what if we allowed `CodeEditor.Factory` to be generically typed.  Then it would look like the following:

```typescript
  /**
   * A factory for creating notebook content.
   */
  export
  interface IContentFactory<T> {
    /**
     * The editor factory.
     */
    readonly editorFactory: CodeEditor.Factory<T>;
...
```

**Comment by akosyakov** [comment]
@vidartf You can down cast `CodeEditor.IEditor` to `CodeMirrorEditor` and use `editor` property to get the underlying code mirror editor.

**Comment by vidartf** [comment]
Having just switched the code base, I can think of two concrete suggestion to make this smoother w.r.t. working directly against CodeMirror: 
 - Have `CodeMirrorEditorFactory` have a constructor that takes CM config options and stores it for use when creating new editors.
 - Have `CodeEditor.Model` have a constructor that takes an initial value of the observable string.

If these seem like reasonable features, I can PR them.

**Comment by blink1073** [comment]
That sounds perfect, please do.

**Comment by blink1073** [comment]
@vidartf, can we close this or do you think more is required?
