### ISSUE TITLE
File browser columns are not consistently positioned

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#16712]
## Description

In the screen shot below, note that filenames which end in ellipses (…) have inconsistently positioned horizontal starting points.

![image](https://github.com/user-attachments/assets/75790c94-1ba1-483e-a53e-b2705c7e27f9)

## Expected behavior

All columns should have a consistent starting point on the X axis.

## Context

- Browser and version: Firefox 129.0.1
- JupyterLab version: 4.3.0b0

**Comment by JasonWeill** [comment]
This GIF shows the effect of resizing the left panel. Note that if there's enough space to display the first column without overlapping the second column, even if the first column ends in an ellipsis, the icons line up.

![resize](https://github.com/user-attachments/assets/8d77902e-0c0f-474a-9664-d88da7de99d3)

**Comment by JasonWeill** [comment]
@srdas confirms that this is not present in Lab 4.2.4.

**Comment by JasonWeill** [comment]
After rebasing to the tip of `main`, I don't see the icons out of alignment anymore, but I do see elided filenames pushing the modified time out of its column:

![image](https://github.com/user-attachments/assets/90349cf7-73f9-44ef-b80a-d3b95819d253)

**Comment by JasonWeill** [comment]
Resizing the side panel sufficiently widely seems to fix this:

![resize](https://github.com/user-attachments/assets/5c3b3084-4caf-4ab2-ad2d-f7175e7344ff)

**Comment by JasonWeill** [comment]
In Chrome 127.0.6533.122, I don't see the inconsistent icon placement shown above, but I do see the file name column being unusually narrow by default.

![image](https://github.com/user-attachments/assets/cc9c984b-9efe-41cb-bdba-f3203c9d312e)

**Comment by krassowski** [comment]
This is because we are using flex layout. We need to swich to grid to fix this. I left it out of the PR implementing column resize to keep the changes to minimal but if you see this as a blocker for release we can make the change.

I think the problem before was not visible because you just could not resize the column down this much.

**Comment by JasonWeill** [comment]
I noticed as well that, in Firefox, selecting different filenames causes the columns to change in position.

![cols-change](https://github.com/user-attachments/assets/fdbe118b-90e7-4465-827a-466795dd2aa7)
