### ISSUE TITLE
Fix bug

### ISSUE THREAD

**Issue by AkieDamien** [jupyterlab/jupyterlab#16735]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by JasonWeill** [comment]
@AkieDamien It doesn't look like you've provided any info about what bug you've found in JupyterLab. Please open a new issue if you find any bugs, and provide the info requested. Thanks!
