### ISSUE TITLE
Rename "File Size" column in file browser to "Size"

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#16734]
## Description

It is possible to read file sizes when the file size column in the filebrowser is very narrow, so much so that the word "Size" isn't visible in the column header:

![image](https://github.com/user-attachments/assets/b7ecf8a0-31e4-4601-8dae-4e04b0a78396)

Shorten this column name to "Size" — there is no ambiguity here. 

For comparison, "Size" is used as a column header in macOS's Finder:

![image](https://github.com/user-attachments/assets/63fa713b-64ec-4697-a524-e13c1caf3d1d)

## Context

- Operating System and version: macOS Sonoma 14.6.1
- Browser and version: Firefox ESR 129.0.1
- JupyterLab version: 4.3.0beta1

**Comment by ChairBorn** [comment]
hey, @JasonWeill, I'm looking to contribute, if it's available, can you assign this?

**Comment by asli-nobita** [comment]
Hi @JasonWeill I'm completely new to open-source contributions and I think this issue is a good one for me to start with. If available, can I work on this?

**Comment by krassowski** [comment]
^ https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html#contribute

As for the issue in question, some thoughts:
- the "File Size" column currently does not show the size of the directory; it is fine as it is not a "Directory Size" column, but if we rename it to just "Size" then I think it is a reasonable ask to open a follow-up issue for showing size of the directory (in number of items or space usage)
- we could make it responsive as is the "Last modified"/"Modified" column but ideally we would generalise the logic used for "Last modified" column

**Comment by JasonWeill** [comment]
@krassowski I've never seen a file browser that displays a "Directory Size" column; instead, the lack of value in the "Size" column is another cue that a particular row represents something other than a file. We should discuss displaying directories' sizes in another issue.

I agree that making the column title names responsive would be good to have.

**Comment by JasonWeill** [comment]
@ChairBorn Thank you for your interest! I assigned this issue to you. Please leave a comment here if you have any questions or if you'd like us to review a pull request.

**Comment by krassowski** [comment]
Does "Folder size" count?

![image](https://github.com/user-attachments/assets/5d4596d4-7472-4aa1-a4a7-c0e81ffa4bf9)

**Comment by krassowski** [comment]
> We should discuss displaying directories' sizes in another issue.

https://github.com/jupyterlab/jupyterlab/issues/16743

**Comment by ChairBorn** [comment]
On it, will get back on that shortly

**Comment by ChairBorn** [comment]
Hey, @JasonWeill, I changed the file browser column name from "File Size" to "Size" as defined on line 2811 of packages/filebrowser/src/listing.ts. Now, it is also defined in overlay of Browser Menu (packages/filebrowser-extension/src/index.ts) as well as commandList docs. I'm not sure which way you would like it. Let me know
![Screenshot 2024-09-05 110521](https://github.com/user-attachments/assets/26dd85c6-9f85-4a36-802e-e2977388eacc)

**Comment by ChairBorn** [comment]
Ok, so I almost finished writing a helper function to adjust the text according to the space available and then realized that I can't get the Modified to change to Last Modified... It only changes when the layout for that tab is extremely wide 
![LastModified](https://github.com/user-attachments/assets/9bc6be5a-7e71-4168-982e-6315d0b71b90)
![Modified](https://github.com/user-attachments/assets/16932b2f-3b0a-4470-9a6d-e619171442ff)
I'll fix the spacing for both of those.
