### ISSUE TITLE
The running session icons on the left side of the status bar are misaligned

### ISSUE THREAD

**Issue by joaopalmeiro** [jupyterlab/jupyterlab#16747]
Hi! 👋 

## Description

Right now, the running session icons on the left side of the status bar at the bottom of the interface appear misaligned:

<img width="1582" alt="Screenshot 2024-09-05 at 11 32 49" src="https://github.com/user-attachments/assets/40b0c2d9-6a41-4d3e-9395-80cd21f1a9ee">

<img width="1582" alt="Screenshot 2024-09-05 at 11 32 57" src="https://github.com/user-attachments/assets/8c314d96-2401-465d-8082-913bab36ee93">

Additionally, the cursor, when overlaying this group, is the default one instead of the `pointer` cursor to further highlight that this element is clickable.

## Reproduce

1. Open JupyterLab.
2. Check the left side of the status bar at the bottom of the interface.

## Expected behavior

The icons are aligned (optically) and the cursor is the `pointer` one to further highlight that this group is clickable. So, I would like to suggest the following change to the [`RunningSessionsComponent` component](https://github.com/jupyterlab/jupyterlab/blob/06c5b357b59ffdd272b3ec71b8444c0a51f5146b/packages/apputils/src/runningSessions.tsx#L37-L57): 

```diff
function RunningSessionsComponent(
  props: RunningSessionsComponent.IProps
): React.ReactElement<RunningSessionsComponent.IProps> {
  return (
    <GroupItem
      tabIndex={0}
      spacing={HALF_SPACING}
      onClick={props.handleClick}
      onKeyDown={props.handleKeyDown}
+     style={{ cursor: 'pointer' }}
    >
      <GroupItem spacing={HALF_SPACING}>
        <TextItem source={props.terminals} />
-       <terminalIcon.react left={'1px'} top={'3px'} stylesheet={'statusBar'} />
+       <terminalIcon.react verticalAlign="middle" stylesheet="statusBar" />
      </GroupItem>
      <GroupItem spacing={HALF_SPACING}>
        <TextItem source={props.sessions} />
-       <kernelIcon.react top={'2px'} stylesheet={'statusBar'} />
+       <kernelIcon.react verticalAlign="middle" stylesheet="statusBar" />
      </GroupItem>
    </GroupItem>
  );
}
```

The final result woud look like this:

<img width="1582" alt="image" src="https://github.com/user-attachments/assets/b80c6609-6cc4-4731-9d03-497c6e3587e9">

|Before|After|
|-|-|
|<img width="1582" alt="Screenshot 2024-09-05 at 11 32 57" src="https://github.com/user-attachments/assets/50391836-cba2-464f-ad09-4111d61c3ded">|<img width="1582" alt="Screenshot 2024-09-05 at 11 49 16" src="https://github.com/user-attachments/assets/16dcb0d3-f826-44b1-8b95-a63312da51bb">|

## Context

- Operating System and version: macOS Sonoma 14.5
- Browser and version: Chrome 127.0.6533.120
- JupyterLab version: 4.3.0b1
- Python version: 3.10.13

Let me know what you think and if I can open a PR. Thanks!

**Comment by krassowski** [comment]
Makes sense!
