### ISSUE TITLE
Update to typedoc 0.26.*

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab#16768]
### Problem

`typedoc 0.26` would likely provide a better documentation reading experience, as it treats all comments as markdown more consistently.

It also changes out its markdown parser from an old, known-ReDoS-susceptible version `marked` to `markdown-it`. This adds a new set of dependencies, but hosting two version of `marked` isn't free, either.

### Proposed Solution

- [x] Update to `typedoc 0.26`
- [x] accept new dependencies
- [x] handle existing broken links, probably with a plugin
  - e.g. the link to _notebook_ on
    - https://jupyterlab.readthedocs.io/en/latest/api/modules/outputarea.html point to
    - https://jupyterlab.readthedocs.io/en/latest/api/notebook  (which doesn't exist)
  - this will likely require a plugin, or pointing to a concrete file (e.g. `../notebook/src/index.ts`)
- [ ] start treating docs warnings as errors with either `--treatWarningsAsErrors` or  `--treatValidationWarningsAsErrors` (if our namespace/interface puns can't be worked around)

### Additional context

Noted on #15733.

**Comment by bollwyvl** [comment]
Also looking at adding [`eslint-plugin-tsdoc`](https://tsdoc.org/pages/packages/eslint-plugin-tsdoc/), using the `typedoc/tsdoc.json` as a baseline. This _does_ mean every `tsconfig.json` needs a neighboring `typedoc.json`, but that doesn't seem like a huge hit.

**Comment by bollwyvl** [comment]
As discussed today, the ReadTheDocs approach will be changing in early October from injecting framework-specific things (e.g. `sphinx-*`) to runtime injection of features (and "features" like ads). Provided this doesn't cause any serious performance, privacy, or accessibility issues it seems like a net win:

https://about.readthedocs.com/blog/2024/04/enable-beta-addons/

_DocDiff_, _Search as you Type_, etc. actually sound _great_.

**Comment by bollwyvl** [comment]
Looks like `0.27.0` dropped. Will take a look.

**Comment by bollwyvl** [comment]
Bah:
```
> @jupyterlab/repo-top@0.0.1 docs
> typedoc --options typedoc.js

[info] Converting project at ./packages/application
TypeDoc exiting with unexpected error:
TypeError: Cannot read properties of undefined (reading 'TypeParameter')
    at ReferenceType.createSymbolReference (~/jupyterlab/node_modules/typedoc/dist/lib/models/types.js:782:70)
    at Object.convertType (~/jupyterlab/node_modules/typedoc/dist/lib/converter/types.js:475:35)
    at convertType (~/jupyterlab/node_modules/typedoc/dist/lib/converter/types.js:111:34)
    at Converter.convertType (~/jupyterlab/node_modules/typedoc/dist/lib/converter/converter.js:330:20)
    at ~/jupyterlab/node_modules/typedoc/dist/lib/converter/factories/signature.js:121:48
    at Array.map (<anonymous>)
    at convertParameters (~/jupyterlab/node_modules/typedoc/dist/lib/converter/factories/signature.js:96:23)
    at createSignature (~/jupyterlab/node_modules/typedoc/dist/lib/converter/factories/signature.js:41:25)
    at convertVariableAsFunction (~/jupyterlab/node_modules/typedoc/dist/lib/converter/symbols.js:593:9)
    at Object.convertVariable (~/jupyterlab/node_modules/typedoc/dist/lib/converter/symbols.js:526:16)

```

**Comment by bollwyvl** [comment]
As per discussion today with @krassowski @andrii-i et al, today: pushed the smallest change that would unblock #15733 is up on #17006 .

I lost the link to the issue about the API dropping off RTD's search... there may be some new knobs we can turn on `.readthedocs.yml` to force behavior.

**Comment by krassowski** [comment]
> I lost the link to the issue about the API dropping off RTD's search... there may be some new knobs we can turn on .readthedocs.yml to force behavior.

It was https://github.com/jupyterlab/jupyterlab/issues/16887
