### ISSUE TITLE
Lab won't load in browser

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1677]
Just pulled from master, did complete git clean, reinstall and saw this in the JS console:

<img width="807" alt="screen shot 2017-02-09 at 2 52 02 pm" src="https://cloud.githubusercontent.com/assets/27600/22806582/b50e9c6e-eed7-11e6-94af-ee1741a1a03d.png">

**Comment by jasongrout** [comment]
Looks like one of your extensions is not updated for 0.16.0 yet?

**Comment by jasongrout** [comment]
Can you disable all of your lab extensions?

**Comment by blink1073** [comment]
That was it, we had sorted it our on gitter.
