### ISSUE TITLE
Clean Jupyterlab  (4.2.5 )install on OSX (13.2.1) fails to enable Lab extensions 

### ISSUE THREAD

**Issue by jbabbin** [jupyterlab/jupyterlab#16796]
## Description

Attempting to run 'jupyter lab' from a user (not root) on OS X 13.2.1 with the latest Jupyterlab build (4.2.5). 
However the paths are showing a Read-Only  warning like below. 
```
[I 2024-09-19 14:55:01.786 LabApp] `sys_prefix` level settings are read-only, using `user` level for migration to `lockedExtensions`
```
This prevents the Extension manager from installing any of the Jupyterlab extensions. 

```
jupyter --paths
config:
    /Users/jbabbin/.jupyter
    /Users/jbabbin/Library/Python/3.12/etc/jupyter
    /Library/Frameworks/Python.framework/Versions/3.12/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/jbabbin/Library/Jupyter
    /Users/jbabbin/Library/Python/3.12/share/jupyter
    /Library/Frameworks/Python.framework/Versions/3.12/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/jbabbin/Library/Jupyter/runtime
```

## Expected behavior

Be able to install Jupyterlab Extensions 

## Context

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>
jupyter troubleshoot
$PATH:
	/Users/jbabbin/.local/bin
	/usr/local/bin
	/System/Cryptexes/App/usr/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/Applications/VMware Fusion.app/Contents/Public
	/usr/local/go/bin
	/opt/X11/bin
	/opt/puppetlabs/bin
	/Library/Apple/usr/bin
	/Users/jbabbin/.fzf/bin

sys.path:
	/usr/local/bin
	/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python39.zip
	/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9
	/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/lib-dynload
	/Users/jbabbin/Library/Python/3.9/lib/python/site-packages
	/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages
	/Library/Python/3.9/site-packages

sys.executable:
	/Applications/Xcode.app/Contents/Developer/usr/bin/python

sys.version:
	3.9.6 (default, May  7 2023, 23:32:44)
	[Clang 14.0.3 (clang-1403.0.22.14.1)]

platform.platform():
	macOS-13.2.1-arm64-arm-64bit

which -a jupyter:
	/usr/local/bin/jupyter

pip list:
	Package                     Version
	--------------------------- --------------
	310-notebook                0.1.0
	abirami-hide-code           4.0.5
	aiofiles                    22.1.0
	aiosqlite                   0.20.0
	alembic                     1.13.2
	altgraph                    0.17.2
	annotated-types             0.7.0
	ansible                     8.7.0
	ansible-core                2.15.12
	ansicolors                  1.1.8
	anyio                       4.4.0
	appdirs                     1.4.4
	appnope                     0.1.4
	argcomplete                 3.3.0
	argon2-cffi                 23.1.0
	argon2-cffi-bindings        21.2.0
	arrow                       1.3.0
	asgiref                     3.5.2
	asphalt                     4.12.0
	asphalt-web                 1.3.1
	asttokens                   2.4.1
	async-generator             1.10
	async-lru                   2.0.4
	async-timeout               4.0.3
	asyncclick                  8.1.3.4
	asyncio-extras              1.3.2
	attrs                       24.2.0
	babel                       2.16.0
	backcall                    0.2.0
	basemap                     1.4.1
	basemap-data                1.3.2
	basemap-data-hires          1.3.2
	bcrypt                      4.1.2
	beautifulsoup4              4.12.3
	bleach                      6.1.0
	blinker                     1.6.2
	branca                      0.7.2
	Brotli                      1.0.9
	certifi                     2024.8.30
	certipy                     0.2.0
	cffi                        1.17.1
	charset-normalizer          3.3.2
	click                       8.1.6
	colorlover                  0.3.0
	comm                        0.2.2
	contourpy                   1.3.0
	cryptography                38.0.4
	cufflinks                   0.17.3
	cycler                      0.11.0
	Cython                      3.0.0
	dash                        2.17.1
	dash_auth                   2.3.0
	dash-core-components        2.0.0
	dash-html-components        2.0.0
	dash-table                  5.0.0
	debugpy                     1.8.5
	decorator                   5.1.1
	defusedxml                  0.7.1
	distlib                     0.3.7
	dnspython                   2.6.1
	email_validator             2.1.2
	entrypoints                 0.4
	exceptiongroup              1.2.2
	executing                   2.1.0
	fastapi                     0.114.2
	fastapi-users               13.0.0
	fastapi-users-db-sqlalchemy 6.0.1
	fastjsonschema              2.20.0
	filelock                    3.12.2
	Flask                       2.2.5
	FlightRadarAPI              1.3.33
	folium                      0.17.0
	fonttools                   4.41.1
	fps_auth                    0.6.2
	fps_contents                0.6.2
	fps_frontend                0.6.2
	fps_kernels                 0.6.2
	fps_lab                     0.6.2
	fps_login                   0.6.2
	fps_terminals               0.6.2
	fps_yjs                     0.6.2
	fqdn                        1.5.1
	frozendict                  2.4.4
	future                      0.18.2
	geodatasets                 2024.8.0
	geopandas                   1.0.1
	geos                        0.2.2
	greenlet                    2.0.2
	h11                         0.14.0
	h2                          4.1.0
	hpack                       4.0.0
	html5lib                    1.1
	httpcore                    1.0.5
	httpx                       0.27.2
	httpx-oauth                 0.15.1
	hyperframe                  6.0.1
	idna                        3.10
	importlib_metadata          8.5.0
	importlib-resources         5.0.7
	ipaddress                   1.0.23
	ipykernel                   6.29.5
	ipyleaflet                  0.19.2
	ipython                     8.18.1
	ipywidgets                  8.1.5
	isoduration                 20.11.0
	itables                     2.1.4
	itsdangerous                2.1.2
	jedi                        0.19.1
	Jinja2                      3.1.4
	json5                       0.9.25
	jsonpointer                 3.0.0
	jsonschema                  4.23.0
	jsonschema-specifications   2023.12.1
	jupyter_client              8.6.3
	jupyter_core                5.7.2
	jupyter-events              0.10.0
	jupyter-leaflet             0.19.2
	jupyter-lsp                 2.2.5
	jupyter_server              2.14.2
	jupyter_server_terminals    0.5.3
	jupyterlab                  4.2.5
	jupyterlab_myst             2.4.2
	jupyterlab_pygments         0.3.0
	jupyterlab_server           2.27.3
	jupyterlab_widgets          3.0.13
	JupyterQuiz                 2.6.3
	jupyverse                   0.6.2
	jupyverse_api               0.6.2
	kaitaistruct                0.10
	kiwisolver                  1.4.4
	ldap3                       2.9.1
	lesscpy                     0.15.1
	lxml                        4.9.3
	macholib                    1.15.2
	makefun                     1.15.4
	Mako                        1.3.5
	markdown-it-py              3.0.0
	MarkupSafe                  2.1.5
	mathplot                    0.1
	matplotlib                  3.8.4
	matplotlib-inline           0.1.7
	mdurl                       0.1.2
	mistune                     3.0.2
	mitmproxy                   9.0.1
	mitmproxy_wireguard         0.1.23
	msgpack                     1.0.5
	multitasking                0.0.11
	nbclient                    0.10.0
	nbconvert                   7.16.4
	nbformat                    5.10.4
	neovim                      0.3.1
	nest-asyncio                1.6.0
	networkx                    3.2.1
	nodejs                      0.1.1
	notebook_shim               0.2.4
	numpy                       1.24.4
	oauthlib                    3.2.2
	optional-django             0.1.0
	overrides                   7.7.0
	packaging                   24.1
	pamela                      1.2.0
	pandas                      2.2.2
	pandas-datareader           0.10.0
	pandasql                    0.7.3
	pandocfilters               1.5.1
	papermill                   2.6.0
	parso                       0.8.4
	passlib                     1.7.4
	peewee                      3.17.6
	pexpect                     4.9.0
	pickleshare                 0.7.5
	Pillow                      10.0.0
	pip                         24.2
	pip-autoremove              0.10.0
	pipx                        1.5.0
	platformdirs                4.3.6
	plotly                      5.24.0
	ply                         3.11
	pooch                       1.8.2
	prometheus_client           0.20.0
	prompt_toolkit              3.0.47
	protobuf                    4.23.4
	psutil                      6.0.0
	ptyprocess                  0.7.0
	publicsuffix2               2.20191221
	pure_eval                   0.2.3
	pwdlib                      0.2.0
	pyasn1                      0.5.0
	pycparser                   2.22
	pycrdt                      0.9.11
	pydantic                    2.9.1
	pydantic_core               2.23.3
	pyee                        8.2.2
	Pygments                    2.18.0
	PyJWT                       2.8.0
	pynvim                      0.4.3
	pyogrio                     0.9.0
	pyOpenSSL                   22.1.0
	pypalettes                  0.1.3
	pyparsing                   3.0.9
	pyperclip                   1.8.2
	pyppeteer                   1.0.2
	pyproj                      3.5.0
	pyshp                       2.3.1
	python-dateutil             2.9.0.post0
	python-json-logger          2.0.7
	python-kasa                 0.5.3
	python-multipart            0.0.9
	pytz                        2023.3
	PyYAML                      6.0.2
	pyzmq                       26.2.0
	QtPy                        2.3.1
	referencing                 0.35.1
	requests                    2.32.3
	resolvelib                  1.0.1
	retrying                    1.3.4
	rfc3339-validator           0.1.4
	rfc3986-validator           0.1.1
	rich                        13.8.1
	rich-click                  1.8.3
	rpds-py                     0.20.0
	ruamel.yaml                 0.17.32
	ruamel.yaml.clib            0.2.7
	scapy                       2.5.0
	seaborn                     0.13.2
	Send2Trash                  1.8.3
	setuptools                  75.1.0
	shapely                     2.0.6
	six                         1.16.0
	sniffio                     1.3.1
	sortedcontainers            2.4.0
	soupsieve                   2.6
	splunk-sdk                  1.7.4
	SQLAlchemy                  2.0.19
	stack-data                  0.6.3
	starlette                   0.38.5
	tenacity                    8.2.2
	terminado                   0.18.1
	tinycss2                    1.3.0
	tomli                       2.0.1
	tornado                     6.4.1
	tqdm                        4.65.0
	traitlets                   5.14.3
	traittypes                  0.2.1
	types-python-dateutil       2.9.0.20240906
	typing_extensions           4.12.2
	tzdata                      2023.3
	uri-template                1.3.0
	urllib3                     2.2.3
	urwid                       2.1.2
	userpath                    1.9.2
	uvicorn                     0.30.6
	virtualenv                  20.24.3
	watchfiles                  0.24.0
	wcwidth                     0.2.13
	webcolors                   24.8.0
	webencodings                0.5.1
	websocket-client            1.8.0
	websockets                  10.4
	Werkzeug                    2.3.6
	wheel                       0.37.0
	widgetsnbextension          4.0.13
	wsproto                     1.2.0
	xyzservices                 2024.6.0
	y-py                        0.6.2
	yfinance                    0.2.43
	ypy-websocket               0.8.4
	zipp                        3.20.2
	zstandard                   0.19.0

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>
jupyter lab
/Users/jbabbin/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[I 2024-09-19 14:54:57.450 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-09-19 14:54:57.470 LabApp] JupyterLab extension loaded from /Library/Python/3.9/site-packages/jupyterlab
[I 2024-09-19 14:54:57.470 LabApp] JupyterLab application directory is /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/share/jupyter/lab
[I 2024-09-19 14:54:57.470 LabApp] Extension Manager is 'pypi'.
[I 2024-09-19 14:54:57.478 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-09-19 14:54:57.479 ServerApp] Serving notebooks from local directory: /opt/JupyterNotebooks
[I 2024-09-19 14:54:57.479 ServerApp] Jupyter Server 2.14.2 is running at:
[I 2024-09-19 14:54:57.479 ServerApp] http://localhost:8888/lab?token=56a1d1c20e580234ba2b705d6d1790321dc2925e84dcd003
[I 2024-09-19 14:54:57.479 ServerApp]     http://127.0.0.1:8888/lab?token=56a1d1c20e580234ba2b705d6d1790321dc2925e84dcd003
[I 2024-09-19 14:54:57.479 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-09-19 14:54:57.485 ServerApp]

    To access the server, open this file in a browser:
        file:///Users/jbabbin/Library/Jupyter/runtime/jpserver-1566-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=56a1d1c20e580234ba2b705d6d1790321dc2925e84dcd003
        http://127.0.0.1:8888/lab?token=56a1d1c20e580234ba2b705d6d1790321dc2925e84dcd003
[W 2024-09-19 14:55:01.113 ServerApp] 404 GET /lsp/status?1726772101053 (35cd7f3da37340398c1c57f0e33c5f84@::1) 57.39ms referer=http://localhost:8888/lab/workspaces/auto-m?reset
[W 2024-09-19 14:55:01.436 ServerApp] 404 GET /lsp/status?1726772101392 (35cd7f3da37340398c1c57f0e33c5f84@::1) 7.45ms referer=http://localhost:8888/lab/workspaces/auto-h?reset
[I 2024-09-19 14:55:01.786 LabApp] `sys_prefix` level settings are read-only, using `user` level for migration to `lockedExtensions`
[I 2024-09-19 14:55:01.789 LabApp] Build is up to date
[I 2024-09-19 14:55:01.920 LabApp] `sys_prefix` level settings are read-only, using `user` level for migration to `lockedExtensions`

**Comment by jbabbin** [comment]
*Update*: 
I think I was able to circumvent the **sys_prefix** issue and none of the jupyter lab extensions being installed. 

1. Upgraded to the latest stable Python (3.12) 
2. Replaced the Python interpreter line in each of my jupyter* files in '/usr/local/bin' 
      From : 
  `jupyter:#!/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12`
      To: 
`jupyter:#!/usr/local/bin/python3
jupyter-dejavu:#!/usr/local/bin/python3
jupyter-events:#!/usr/local/bin/python3
jupyter-execute:#!/usr/local/bin/python3
jupyter-kernel:#!/usr/local/bin/python3
jupyter-kernelspec:#!/usr/local/bin/python3
`

**Comment by JasonWeill** [comment]
@jbabbin Thank you for opening this issue! It looks like the issue regarding extensions on macOS is already covered in #14965. Let's keep the conversation going in this existing issue.
