### ISSUE TITLE
Same `id` can be used for different headings

### ISSUE THREAD

**Issue by HaudinFlorence** [jupyterlab/jupyterlab#16795]
## Description

The same `id` can be used for differents headers if they have the same text content because the `id` is built from the text of the headings, with spaces replaced by `-`.
This possibility of duplicated `id`s was observed when working on this PR in nbconvert: https://github.com/jupyter/nbconvert/pull/2178. For building a table of contents with links to some DOM elements, it is important to have unique identifiers.

## Reproduce

1. Create a notebook containing markdowns with headings of the same level and containing the same text, like the following one for instance
![Screenshot from 2024-09-19 16-19-14](https://github.com/user-attachments/assets/37d116df-385e-4177-8f1f-57ade89a3a44)

3. If you inspect the `Section 1` elements with the dev tools, you can see that their `id`, generated from their text content, is exactly the same (`Section-1`)

![Screenshot from 2024-09-19 16-17-22](https://github.com/user-attachments/assets/7ffef030-48a2-4132-9de4-a2dfa38ec329)

![Screenshot from 2024-09-19 16-17-52](https://github.com/user-attachments/assets/af289f09-4d1b-4e25-a4e8-68dc842d4554)

## Expected behavior

In case there are duplicated headings, a suffix could be added to the `id`.

## Context

- JupyterLab version: 4

**Comment by onursercanyilmaz** [comment]
Hi @HaudinFlorence , if it is available can you assign me this? I handled in renderers.tsx like

```
function getRandomLetters(length: number): string {
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
    let result = '';
    for (let i = 0; i < length; i++) {
        const randomIndex = Math.floor(Math.random() * characters.length);
        result += characters[randomIndex];
    }
    return result;
}

async function hashString(str: string): Promise<string> {
    // Simple hash function using SHA-1
    const encoder = new TextEncoder();
    const date = new Date();
    const randomLetters = getRandomLetters(5); // Generate 5 random letters
    const text = str + randomLetters + date.toString();
    
    const data = encoder.encode(text);
    const buffer = await crypto.subtle.digest('SHA-1', data);
    return Array.from(new Uint8Array(buffer))
        .map(b => ('00' + b.toString(16)).slice(-2)) // Ensures each byte is represented by 2 characters
        .join('');
}

```

**Comment by onursercanyilmaz** [comment]
Hi @HaudinFlorence, if this task is available, could you please assign it to me? I’ve already made some changes in renderers.tsx, as shown below.

```
  export function createHeaderId(header: Element, index: number): string {
    return (`${header.textContent} ${index}` ?? '').replace(/ /g, '-');
  }
```

**Comment by onursercanyilmaz** [comment]
Hi @HaudinFlorence, if this task is available, could you please assign it to me? I’ve already made some changes in renderers.tsx, as shown below.

```
  export function headerAnchors(node: HTMLElement): void {
    const headerNames = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'];
    for (const headerType of headerNames) {
      const headers = node.getElementsByTagName(headerType);
      for (let i = 0; i < headers.length; i++) {
        const header = headers[i];
        const parentElement = header.closest(
          '.lm-Widget.jp-Cell.jp-MarkdownCell.jp-Notebook-cell.jp-mod-rendered'
        );
        const parentIndex =
          parentElement?.getAttribute('data-windowed-list-index') ?? '0';
        header.id = renderMarkdown.createHeaderId(header, i, parentIndex);
        const anchor = document.createElement('a');
        anchor.target = '_self';
        anchor.textContent = '¶';
        anchor.href = '#' + header.id;
        anchor.classList.add('jp-InternalAnchorLink');
        header.appendChild(anchor);
      }
    }
  }
  
   export function createHeaderId(header: Element, index: number, parentIndex: string): string {
    return (`${header.textContent} ${index} ${parentIndex}` ?? '').replace(/ /g, '-');
  }
```

If a cell includes more than 1 header it adds 'i' (index) to id and after that adds the parent div's index info as header-{innerIndex}-{parentIndex}. Issue is about parentIndex problem but there was another problem on inner headers that solved too.

![image](https://github.com/user-attachments/assets/d6a745ba-5760-4f1c-9699-5a2e5a94e3ce)

But still there was an issue that for example - if user adds #Part 1 as h1 and ##Part 1 as h2 - it creates same id.
So i added headerType parameter too

```
  export function createHeaderId(
    header: Element,
    index: number,
    parentIndex: string,
    headerType: string,
  ): string {
    return (`${header.textContent} ${index} ${parentIndex} ${headerType}` ?? '').replace(
      / /g,
      '-'
    );
  }
  
   export function headerAnchors(node: HTMLElement): void {
    const headerNames = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'];
    for (const headerType of headerNames) {
      const headers = node.getElementsByTagName(headerType);
      for (let i = 0; i < headers.length; i++) {
        const header = headers[i];
        const parentElement = header.closest(
          '.lm-Widget.jp-Cell.jp-MarkdownCell.jp-Notebook-cell.jp-mod-rendered'
        );
        const parentIndex =
          parentElement?.getAttribute('data-windowed-list-index') ?? '0';
        header.id = renderMarkdown.createHeaderId(header, i, parentIndex, headerType);
        const anchor = document.createElement('a');
        anchor.target = '_self';
        anchor.textContent = '¶';
        anchor.href = '#' + header.id;
        anchor.classList.add('jp-InternalAnchorLink');
        header.appendChild(anchor);
      }
    }
  }
```

**Comment by JasonWeill** [comment]
Thanks to @krassowski for finding #1932 (!), the original occurrence of this issue. I can associate #16800 with this much older issue. @onursercanyilmaz thank you for opening your pull request!

**Comment by HaudinFlorence** [comment]
Hello. Thanks @onursercanyilmaz for proposing to solve this issue. @krassowski @JasonWeill I should have checked that the issue was not already identified. Happy that is now solved.
