### ISSUE TITLE
Deleting a keyboard shortcut in the Settings Editor removes other user-set shortcut settings

### ISSUE THREAD

**Issue by stanwest** [jupyterlab/jupyterlab#16809]
## Description

When I used the Settings Editor to delete a keyboard shortcut, *JupyterLab* rewrote the entire "shortcuts.jupyterlab-settings" file to contain only boilerplate comments and the one deleted shortcut, thereby removing any shortcuts and comments previously contained in the file.

## Reproduce

1. Optionally, back up the "shortcuts.jupyterlab-settings" file.

2. Within *JupyterLab*, open the Settings Editor (menu item "Settings > Settings Editor"). In the "Settings" tab, within its left pane, click "Keyboard Shortcuts".

3. In the "Settings" tab, at the upper right, click "JSON Settings Editor". In the "Advanced Settings Editor" tab, within its left pane, click "Keyboard Shortcuts". Ensure that the "User Preferences" pane shows non-trivial valid content, such as:

    ``` json
    {
        "shortcuts": [
            {
                "command": "mainmenu:open-first",
                "keys": ["Alt F10"],
                "selector": "body"
            }
        ]
    }
    ```

4. In the "Settings" tab, within its main pane, in the "Shortcut" column, right-click a shortcut and select the "Delete Keybinding" menu item.

5. In the "Advanced Settings Editor" tab, observe that the JSON object in the "User Preferences" pane now contains the comments shown in the "System Defaults" pane followed by only the deleted shortcut:

    ``` json
    {
        // Keyboard Shortcuts
        // ...
        // List of keyboard shortcuts:
        "shortcuts": [
            {
                "command": "application:toggle-sidebar-widget",
                "selector": "body",
                "disabled": true,
                "keys": [
                    "Alt 1"
                ]
            }
        ]
    }
    ```

Moreover, one may return to the "Settings" tab, delete a different shortcut, and find that the user preferences now show only the newly deleted shortcut.

## Expected behavior

I expect that deleting a shortcut in the "Settings" tab would modify the user preferences no more than necessary, leaving prior shortcuts and comments in place.

## Context

- Operating System and version: Windows 11 21H2
- Browser and version: Firefox 130.0, Chrome 129.0.6668.59
- JupyterLab version: 4.2.5

**Comment by krassowski** [comment]
I just worked on fixing this logic yesterday in https://github.com/jupyterlab/jupyterlab/pull/16721 - it might be fixed by that PR, see the test cases added. In particular see https://github.com/jupyterlab/jupyterlab/pull/16721/commits/fe0c076a19ca83b79cce330e5e19b471f2055858.
