### ISSUE TITLE
Ability to add custom shortcuts to the launcher.

### ISSUE THREAD

**Issue by jerrywoo96** [jupyterlab/jupyterlab#16819]
### Problem

Ability to define a configuration file and read the configuration file to create new shortcuts on the launcher.
One of the features required of the shortcut is to define a command to be ran in a terminal with options and arguments.
An example or use case would be a ssh command that open a ssh session in a new tab with the username, password/private key, port and hostname defined as arguments stored in the configuration file.

### Proposed Solution

1. Create a configuration file like yaml that stores defined shortcuts to be created on the launcher.
2. Jupyter will read this configuration file and create the shortcuts on the launcher.

### Additional context

I have tried https://github.com/trungleduc/jupyter_app_launcher but it does not provide the functionality to create a ssh shortcut on the launcher.

**Comment by JasonWeill** [comment]
@jerrywoo96 Thank you for opening this issue! There is already an enhancement in Jupyter App Launcher for adding a custom command: https://github.com/trungleduc/jupyter_app_launcher/issues/56

Additional PRs about launcher improvement: #12190, #10203 

@krassowski points out that #9789 looks like what you're looking for. We've already accepted that issue, and would consider a pull request to implement it. Let's keep the conversation going in #9789. Thanks again!

**Comment by trungleduc** [comment]
This feature is added to Jupyter App Launcher 0.3.0
