### ISSUE TITLE
DONE: Debian package for jupyterlab

### ISSUE THREAD

**Issue by farhi** [jupyterlab/jupyterlab#16813]
Hello,

Our team at Synchrotron SOLEIL has actually, after 1.5 years work, managed to push Jupyterlab as an officiel package for Debian/Ubuntu/Mint/etc. This adds a complementary distribution channel aside conda/pip, which ensures the full availability of all system-level python libraries. 

The pushed version is not the latest (4.0.11), but this constitutes for us a major leap forward. The packages are currently available at:
- https://packages.debian.org/unstable/jupyterlab
- https://tracker.debian.org/pkg/jupyterlab

We intend to push a more recent version when the many dependencies (mainly NodeJS) will get stabilized. BTW, we have pushed JupyterHub 2 years ago. So we keep on track.

Cheers, Emmanuel.

**Comment by JasonWeill** [comment]
@farhi Thank you for letting us know about this! I appreciate having an alternate channel for installing JupyterLab. Please open additional issues if you notice anything else that needs to be done in JupyterLab.
