### ISSUE TITLE
shift-tab tooltip tweaks

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#1682]
I observed the following minor issues with the shift-tab tooltip in 0.16:
* Attempting to trigger a tooltip on an object not present in the namespace results in a blank misformatted tooltip appearing in the top left corner:
![image](https://cloud.githubusercontent.com/assets/2069677/22808810/3da44154-ef2e-11e6-8cf7-c08333ef3403.png)
* Tooltip linewidth calculation doesn't include the scrollbar width, resulting in last symbols being partially hidden:
![image](https://cloud.githubusercontent.com/assets/2069677/22808837/7689ac5c-ef2e-11e6-8c79-ab48d3b7c7b7.png)
* Perhaps now tooltip is overzealous to disappear: it is already gone on keydown event of a modifier key (took me a bit of thinking how to make these screenshots).

**Comment by blink1073** [comment]
Thanks for finding these :bug:!

**Comment by ellisonbg** [comment]
@blink1073 the horizontal scrollbar is on the wrong element too ;-)

**Comment by ellisonbg** [comment]
It might be a good idea of keep the tooltip open and allow the user to type until:

* They press ESC to dismiss.
* They press return or `)`
