### ISSUE TITLE
Autosave on editor focus change

### ISSUE THREAD

**Issue by lahwaacz** [jupyterlab/jupyterlab#16830]
JupyterLab has only a timeout-based autosave feature. This is nice, but can be made more flexible - for example, [VSCode](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save) has multiple options:

- off - to disable auto save.
- afterDelay - to save files after a configured delay (default 1000 ms).
- onFocusChange - to save files when focus moves out of the editor of the dirty file.
- onWindowChange - to save files when the focus moves out of the VS Code window.

In the context of JupyterLab, `onFocusChange` might relate to Jupyter widgets and `onWindowChange` to the web browser window/tab.

**Comment by JasonWeill** [comment]
This is already covered in #4344. Let's keep the conversation going there. Thank you for your contribution!
