### ISSUE TITLE
paste cells may result in lost focus

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#1683]
Observed in v0.16. To reproduce:
1. Open a notebook to edit.
2. Using the icons in the notebook toolbar cut a cell:
![image](https://cloud.githubusercontent.com/assets/2069677/22808959/4ffffbc6-ef2f-11e6-9e7d-0ddfd6728386.png)
3. Click on paste cell icon in the same toolbar.
4. Observe that the notebook does not respond to keypresses until a mouse click event inside the notebook area. Expected behavior would be that the notebook stays in focus and is in command mode.

**Comment by blink1073** [comment]
Good call!  We should call `activate()` at the end of each of the synchronous notebook actions.
