### ISSUE TITLE
Cell raw_mimetype persists when changing cell type.

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#1684]
Not sure if intended, but specifying a cell raw nbconvert format via cell tools widget, and then changing the cell type to e.g. code from raw nbconvert doesn't remove the corresponding cell metadata entry.

**Comment by blink1073** [comment]
I just verified this is the behavior of the classic notebook as well.  I'd say that is fine to keep because if you toggle between cell types it will carry across and will be a no-op in non raw cells.

**Comment by blink1073** [comment]
Closing as answered, please feel free to reopen if you disagree.
