### ISSUE TITLE
Bracket highlighting not working for multiple-line Python string literal concatenation

### ISSUE THREAD

**Issue by Nagidrop** [jupyterlab/jupyterlab#16865]
## Description
When you have strings on multiple lines with 1 f-string not on the last line, bracket highlighting doesn't work although it's valid syntax. 
It only works properly if the f-string is on the last line.

https://github.com/user-attachments/assets/2e24db2f-5637-4af5-bcb9-38dfb243de58

I reported this issue upstream at https://github.com/codemirror/dev/issues/1454 and found upgrading @lezer/python dependency resolved this.

## Reproduce
1. Type any pair of brackets `()` `[]` `{}`
2. Type strings on multiple lines with 1 f-string not on the last line

## Expected behavior
Bracket highlighting works properly

## Context
- Operating System and version: Windows 11
- Browser and version: JupyterLab Desktop 4.2.5-1 (latest)
- JupyterLab version: 4.2.5 (latest)

**Comment by krassowski** [comment]
This works in CodeMirror playground:

![image](https://github.com/user-attachments/assets/9c0c8df2-e0a3-4760-8e31-a2aeba2ed484)

https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge3B5dGhvbn0gZnJvbSAiQGNvZGVtaXJyb3IvbGFuZy1weXRob24iCgpuZXcgRWRpdG9yVmlldyh7CiAgZG9jOiAicHJpbnQoXG4gICAgZid0ZXN0JyxcbiAgICBmJ3Rlc3QnXG4pXG4iLAogIGV4dGVuc2lvbnM6IFtiYXNpY1NldHVwLCBweXRob24oKV0sCiAgcGFyZW50OiBkb2N1bWVudC5ib2R5Cn0pCg==

We updated the codemirror packages in 4.3, maybe it is already solved.

**Comment by krassowski** [comment]
I can still reproduce this in JupyterLab version 4.3.0b3.

**Comment by Nagidrop** [comment]
> This works in CodeMirror playground:
> 
> ![image](https://private-user-images.githubusercontent.com/5832902/376578400-9c0c8df2-e0a3-4760-8e31-a2aeba2ed484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTAwNDYsIm5iZiI6MTcyODk4OTc0NiwicGF0aCI6Ii81ODMyOTAyLzM3NjU3ODQwMC05YzBjOGRmMi1lMGEzLTQ3NjAtOGUzMS1hMmFlYmEyZWQ0ODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMTA1NTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmQ5YzA3YTRjMzJlMjhhMzcyYWZiZTJjYWVkY2JjZTc5ZGRmYzI5ODM2MjVlYWQwNjlmMmNiN2Y1MDhkYWJmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.jGlqic2_4YdZOOiuMY0X6uj0xJBgYtYBvgzL3Fdmp_8)
> 
> https://codemirror.net/try/?c=aW1wb3J0IHtiYXNpY1NldHVwLCBFZGl0b3JWaWV3fSBmcm9tICJjb2RlbWlycm9yIgppbXBvcnQge3B5dGhvbn0gZnJvbSAiQGNvZGVtaXJyb3IvbGFuZy1weXRob24iCgpuZXcgRWRpdG9yVmlldyh7CiAgZG9jOiAicHJpbnQoXG4gICAgZid0ZXN0JyxcbiAgICBmJ3Rlc3QnXG4pXG4iLAogIGV4dGVuc2lvbnM6IFtiYXNpY1NldHVwLCBweXRob24oKV0sCiAgcGFyZW50OiBkb2N1bWVudC5ib2R5Cn0pCg==
> 
> We updated the codemirror packages in 4.3, maybe it is already solved.

Yesterday when I reported upstream the error was still there, but after the maintainer replied the issue has gone. It seemed that they upgraded @lezer/python and resolved the issue.

**Comment by krassowski** [comment]
It looks like we just need to update the lock file? We do not depend on `@lezer/python` directly, only on `@codemirror/lang-python` and it is in the latest version. We could force a specific `@lezer/python` resolution if we need to.

**Comment by krassowski** [comment]
Indeed our lockfile resolves to `@lezer/python` 1.1.7:

https://github.com/jupyterlab/jupyterlab/blob/c321c27b50431fc0414b20a3b61375af7ccb6c2e/yarn.lock#L5204-L5209

but the latest is 1.1.14: https://www.npmjs.com/package/@lezer/python?activeTab=versions

**Comment by krassowski** [comment]
Also `@lezer/highlight` is at `1.2.0` but latest is `1.2.1`:

https://github.com/jupyterlab/jupyterlab/blob/c321c27b50431fc0414b20a3b61375af7ccb6c2e/yarn.lock#L5125-L5127

**Comment by Nagidrop** [comment]
I was about to create a PR with the specific resolution, but wasn't sure if it could break other dependencies because I wasn't familiar with the yarn.lock.

**Comment by krassowski** [comment]
Please feel welcome to go ahead - we can see if tests pass on CI after you opened the PR. It might require bumping some other dependencies - we will see
