### ISSUE TITLE
404 errors when exporting to PDF with LaTeX packages not installed

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#16862]
### Problem

When either `nbconvert` or the related $\LaTeX$ packages are not installed, exporting to PDF results in a 404 error.

### Proposed Solution

Disable export commands and menu items when dependent packages are not installed.

### Additional context

* See also #16861, about making `nbconvert` a hard dependency of JupyterLab.

**Comment by krassowski** [comment]
Duplicate of https://github.com/jupyterlab/jupyterlab/issues/11687?

**Comment by JasonWeill** [comment]
Resolving as duplicate of #11687 — thanks @krassowski
