### ISSUE TITLE
`%rm` doesn't work to remove a file on JupyterLab on Windows

### ISSUE THREAD

**Issue by hyperkai** [jupyterlab/jupyterlab#16876]
`%rm` doesn't work to remove a file on JupyterLab on Windows as shown below. *I installed [Git](https://git-scm.com/):

```python
%rm file1
```

> UsageError: Line magic function `%rm` not found.

**Comment by JasonWeill** [comment]
@hyperkai I'm looking at the [IPython docs about built-in magic commands](https://ipython.readthedocs.io/en/stable/interactive/magics.html#line-magics) and I don't see a `%rm` command. Where did you see this command listed? Sometimes, documentation will suggest that you run a command as a less-privileged user as `% rm file1` and as root as `# rm file1`, but in these cases, the first character is intended to be read as part of your shell prompt, not as something to run.

**Comment by JasonWeill** [comment]
You can also use `!rm` to run the `rm` command inside a cell. This works with any command that you can run. (Thanks @krassowski )

**Comment by JasonWeill** [comment]
@hyperkai Please try `!rm` in lieu of `%rm` in your notebook. There is no standard magic command called `%rm`. If you find a problem with a built-in magic command, please open an issue in IPython here: https://github.com/ipython/ipython/issues . Thank you!
