### ISSUE TITLE
`json`  FileFormat raise Must specify format of file contents as 'text' or 'base64' error 400 

### ISSUE THREAD

**Issue by cmarmo** [jupyterlab/jupyterlab#16924]
## Description
I am creating a new untitled file then renaming it with
```typescript
const contents = new ContentsManager();
const model = await contents.newUntitled({
  path: '',
  type: 'file',
  ext: 'json'
});
contents.rename(model.path, 'myfile.json');
```

When trying to save new content in it with 
```typescript
 contents.save('myfile.json', {
   content: '{ "some": "text", "string": "json" }',
   format: 'json',
   type: 'file'
 });
```

a bad request error is thrown:
"Must specify format of file contents as 'text' or 'base64'"

This is not a bug as the expected behaviour is correctly described in the [Jupyter Server content](https://jupyter-server.readthedocs.io/en/latest/developers/contents.html#filesystem-entities) documentation.

If I understand correctly the format "json" is only compatible with the type "directory": I wonder if the maintainers would accept a pull request with a more detailed description of [FileFormat](https://jupyterlab.readthedocs.io/en/latest/api/types/services.Contents.FileFormat.html) linking to jupyter server specifications.

**Comment by JasonWeill** [comment]
@cmarmo Thank you for opening this issue! The format "json" is compatible with the model types "notebook" and "directory", but not "file". If you have an arbitrary file in JSON format, and that is not a Jupyter notebook, you should use type "text" for it.

We would accept a pull request to update the documentation to be clearer about this. Thank you!
