### ISSUE TITLE
Missed first keystroke on Ctrl+F when switching between notebook tabs

### ISSUE THREAD

**Issue by miloaissatu** [jupyterlab/jupyterlab#16928]
## Description

The first keystroke is missed when typing in an existing/previously opened search box after switching focus to it via keyboard shortcut Ctrl+F.

Examples:
1. When switching between notebook tabs and using Ctrl+F to bring up or switch focus to the search bo
[jupyter_troubleshoot.txt](https://github.com/user-attachments/files/17639963/jupyter_troubleshoot.txt)
x, the first keystroke is often missed (easy to reproduce).
2. Within the same notebook tab where an existing searchbox is open, switching focus between cells and search box via Ctrl+F shortcut, sometimes the first keystroke is missed. (inconsistent, harder to reproduce)

## Reproduce

1. Have multiple notebook tabs open
2. Use Ctrl+F to bring up search box and start typing. This should work fine with no missed keystrokes
3. Repeat step 2 for each open notebook tab to open the search box for the first time
4. Once all notebook tabs have a search box open, switch tabs and use Ctrl+F to switch focus to the search box, start typing and the first keystroke should be missed

![missed_keystroke](https://github.com/user-attachments/assets/261d87ae-7e2e-4d43-b183-176cee579d64)

In the gif above I'm typing 'test' every time I switch focus to the search box via keyboard shortcut Ctrl+F. You can see that after the first pass of opening the search box on each tab, the subsequent tab cycles show 'est' in the search box because the first 't' keystroke was missed.

## Expected behavior

First keystroke is not missed when switching focus to existing search box using Ctrl+F keyboard shortcut.

## Context

- Image: quay.io/jupyter/base-notebook:2024-11-04
- Operating System and version: Image runs Ubuntu 24.04
- Browser and version: Reproducible in Firefox 132.0.1, Edge 130.0.2849.68, Chrome 130.0.6723.92
- JupyterLab version: 4.2.5, but also reproducible on 4.2.1, 4.0.5, 4.3.0 etc

<details><summary>Troubleshoot Output</summary>
[jupyter_troubleshoot.txt](https://github.com/user-attachments/files/17640014/jupyter_troubleshoot.txt)

</details>

<details><summary>Command Line Output</summary>
[jupyter_debug.txt](https://github.com/user-attachments/files/17639954/jupyter_debug.txt)
</details>

<details><summary>Browser Output</summary>

<pre>
Nothing printed on browser JavaScript console
</pre>
</details>

**Comment by miloaissatu** [comment]
I've also tried with different search debounce time settings, doesn't make a difference.

**Comment by krassowski** [comment]
The code for the input box is here:

https://github.com/jupyterlab/jupyterlab/blob/e0db5da7884f1fdcd8d2c0a79f8b0c66aa8b862e/packages/documentsearch/src/searchview.tsx#L113-L133
