### ISSUE TITLE
”Run Selected Code" default shortcut "Shift + Enter" not working in text editor with vim mode enabled

### ISSUE THREAD

**Issue by HereticSK** [jupyterlab/jupyterlab#16939]
## Description

When trying to run selected code in a text editor with vim mode enabled, the default keyboard shortcut "Shift + Enter" not does not work, the selected code is not sent to the console and run.

The following manual tests are done:

- Enable vim mode, hit "Shift + Enter", fail
- Enable vim mode, click "Run Selected Code" in run menu with mouse, succeed
- Enable vim mode, change keyboard shortcut to "Ctrl + Enter", succeed
- Disable vim mode, both keyboard shortcut and run menu succeed

## Reproduce

1. Open a python file with text editor, enable vim mode
2. Create a console for this editor
3. Try running selected code by hitting "Shift + Enter"

## Context

- Operating System and version: Arch Linux
- Browser and version: Chrome Version 130.0.6723.70 (Official Build) (64-bit)
- JupyterLab version: 4.3.0

This keyboard issue may have occurred as early as Jupyterlab version 4.2.0, when I had just upgraded to 4.2.0. But I did not try disabling vim mode and changing to a different shortcut at that time. I simply rolled back to versions < 4.2.0 to work around. Until recently 4.3.0 released, I upgraded and found the issue still not fixed. I tried disabling vim mode and changing to a different to do further investigation.

**Comment by krassowski** [comment]
I think the better place to report this is in https://github.com/jupyterlab-contrib/jupyterlab-vim as this is where the code for vim mode is. Also, I would double check what version of jupyterlab-vim you have installed, this issue may have been fixed in an update of the extension.

**Comment by JasonWeill** [comment]
@HereticSK As @krassowski mentioned, please open an issue in https://github.com/jupyterlab-contrib/jupyterlab-vim if this still occurs in the most recent version of this extension. Thanks!
