### ISSUE TITLE
Not Scrolling menu, i can't shutting down jupyter lab

### ISSUE THREAD

**Issue by SaifMahmud366** [jupyterlab/jupyterlab#16944]
## Description

i can not shut down my jupyter lab after updating **4.3.0** version. my screen size is "**1366x768**".  i can not scroll it 
![Image](https://i.ibb.co.com/pxyLnw0/lab.png)

## Reproduce

use any **1366x768** monitor

## Expected behavior

Scrolling this section
![Image](https://i.ibb.co.com/pxyLnw0/lab.png)

## Context

- Operating System and version: Windows 11 23H2
- Browser and version: Google Chrome 130.0.6723.117
- JupyterLab version: 4.3.0

## Troubleshooting
i have tried different browsers. but the problem is the same.

**Comment by Darshan808** [comment]
@SaifMahmud366 
Thanks for bringing this up! 
I've submitted a PR to address it—hopefully, this will be resolved soon!

**Comment by krassowski** [comment]
Separately, I wonder if we should be showing menu entries relating to documents (save/revert/download) when no documents are open. Any quick thoughts on this?

**Comment by Darshan808** [comment]
> Separately, I wonder if we should be showing menu entries relating to documents (save/revert/download) when no documents are open. Any quick thoughts on this?

Yes, rather than graying out these unnecessary menu items, it might be better to remove them altogether. I'll see about implementing this.

**Comment by SaifMahmud366** [comment]
when will be next updated version release?

**Comment by krassowski** [comment]
I'm hoping to cut a patch release on 4.3.x branch this week (Wednesday or Thursday).

**Comment by JasonWeill** [comment]
Thanks for submitting a PR to add scrolling! I think it would be better to have a separate issue concerning removing greyed out menu items. Users may be thrown off by having menu items change position when they're not available.

**Comment by krassowski** [comment]
@SaifMahmud366 JupyterLab 4.3.1 is now available

**Comment by SaifMahmud366** [comment]
> @SaifMahmud366 JupyterLab 4.3.1 is now available

Yeah..i have already updated this, and its working fine. 
Thank You all❤️
