### ISSUE TITLE
Autocomplete for dictionary keys failing for second or later paramater in function calls

### ISSUE THREAD

**Issue by MaxPelly** [jupyterlab/jupyterlab#16949]
## Description
Using tab complete to autofill the key in a dictionary or pandas data frame seems to fail if using it for the second or later paramater in a function call. For example:
```
foo(data[""])
```
will offer the keys of tab is hit with the cursor between the "" but
```
foo(data["bar"], data[""])
foo(bar, data[""])
```
will not.

## Reproduce

1. Create a dictionary or pandas object with named keys
2. attempt to autofill key names with dictionary variable bare on a cell line, should work
3. attempt to autofill key names with dictionary as the first paramater of a function, should work
4. attempt to autofill key names with dictionary as the second or later paramater of a function, does not work

## Context

- Operating System and version: Windows 11 23H2
- Browser and version: Firefox 132.0.1 64 bit
- JupyterLab version: 4.3.0

**Comment by krassowski** [comment]
JupyterLab does not implement the completion logic for language-specific constructs - it comes from individual kernels (unless you have `jupyterlab-lsp` installed, then it also comes from language servers). You should check if this is related to your IPython setup. Of note, disabling jedi in IPython (`%config IPCompleter.use_jedi=False`) changes the completer implementation. Tuning [`Completer.evaluation`](https://ipython.readthedocs.io/en/stable/config/options/terminal.html#configtrait-Completer.evaluation) might allow for richer experience (with some trade-offs).

If you think the default behaviour in IPython should be improved please open an issue over on: https://github.com/ipython/ipython/ (after verifying there is not one already). If you use a Python kernel other than ipykernel then the issue should most likely go to its repository.

**Comment by JasonWeill** [comment]
@MaxPelly Thank you for opening the issue! Because, as @krassowski noted, the autocomplete logic is not in JupyterLab but in IPython or another package. Please open an issue if you can reproduce in the command-line `ipython` environment as well. Thanks!
