### ISSUE TITLE
Can't drag and drop files within the file browser in 4.3.0

### ISSUE THREAD

**Issue by tgourdel** [jupyterlab/jupyterlab#16958]
## Description

Before 4.3.0, we use to be able to drag and drop files into folders within the file browser. It seems it's not possible in 4.3.0.
<details><summary>Browser Console when attempting to drag a file</summary>
<pre>
jlab_core.30ac71af4f…c71af4fabafb542d8:1 Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at t.createDragImage (jlab_core.30ac71af4f…abafb542d8:1:798327)
    at ce._startDrag (jlab_core.30ac71af4f…abafb542d8:1:786589)
    at ce._evtMousemove (jlab_core.30ac71af4f…abafb542d8:1:781297)
    at ce.handleEvent (jlab_core.30ac71af4f…abafb542d8:1:770417)
</pre>
</details>

## Reproduce

Try to move a file into a folder in the file browser.

## Expected behavior

Previous behavior is to being able to drag and drop files in other folders.

## Context

- Operating System and version: MacOS Sonoma 14.6.1
- Browser and version: Version 1.71.121 Chromium: 130.0.6723.91 (Official Build) (arm64)](https://brave.com/latest/)
- JupyterLab version: 4.3.0

**Comment by tgourdel** [comment]
Correct, I always hide the `Modified` column and haven't thought about it. I should have added a screenshot. Thanks for looking into it.

**Comment by krassowski** [comment]
There is a PR waiting for review here: https://github.com/jupyterlab/jupyterlab/pull/16962 - feel welcome to review. 

Otherwise I think @JasonWeill mentioned some time ago that they had a report of a similar issue and wanted to look into this.
