### ISSUE TITLE
"Unexpected end of JSON input" when you interrupt a Galata test using v5.3.0

### ISSUE THREAD

**Issue by pauldruce** [jupyterlab/jupyterlab#16954]
## Description

I tried updating to the latest version of JupyterLab and Galata in a project I work on. In this project we have a test that interrupts  the kernel whilst running some code, and then checks that everything works as expected for our kernel. However, with the new version (5.3.0 of @jupyterlab/galata), when you interrupt running code in a Galata test you get the following error
```
SyntaxError: Unexpected end of JSON input
    at node_modules/@jupyterlab/galata/src/galata.ts:971:26
```
and the tests exit. 

The interrupt is triggered via the Kernel menu. I've created an example test point below which reproduces this issue. 

## Reproduce

In a clean Playwright+Galata project, create a test file and paste the following code in it:
```ts
import { expect, test } from '@jupyterlab/galata';

test.describe('Interrupt Kernel Tests', () => {
    test('Interrupt simple Python code', async ({ page, tmpPath }) => {
        // Create Python Notebook
        const fileName = 'create_test.ipynb';
        await page.notebook.createNew(fileName);

        // Assert Notebook has been created
        expect(
            await page.waitForSelector(`[role="main"] >> text=${fileName}`)
        ).toBeTruthy();
        expect(await page.contents.fileExists(`${tmpPath}/${fileName}`)).toEqual(
            true
        );
        const pythonCode = `
import time

y=5
y=y+1

time.sleep(15)
print(y)
`
        // Add and run long running Python code
        await page.notebook.setCell(0, 'code', pythonCode);
        page.notebook.runCell(0); // Awaiting this waits for cell to finish executing

        // Interrupt the kernel execution
        await page.menu.clickMenuItem('Kernel > Interrupt Kernel');

        // Assert the output of cell is not displayed
        const cellOutput = await page.notebook.getCellTextOutput(0);
        expect(cellOutput).toBeNull();
    });
});

```

<details><summary>Full Reproduction steps are here:</summary>

1. Create a new directory, and run `npm init` and follow the steps to create a new blank NodeJS project
2. Install playwright and "@jupyterlab/galata": `npm install playwright @jupyterlab/galata`
3. Create a Python venv, install JupyterLab in it. A onliner to do this is here: 
   ```
   python -m venv .venv && source .venv/bin/activate && python -m pip install --upgrade pip && python -m pip install jupyterlab
   ```
4. Create a file called `playwright.config.js` with the following line in it: `
    ```
    module.exports = require('@jupyterlab/galata/lib/playwright-config');
    ```
5. Create a file called `jupyter_server_test_config.py` with the following contents:
    ```python
    from jupyterlab.galata import configure_jupyter_server

    configure_jupyter_server(c)
    ```
6. Create a test file `foo.spec.ts` and copy the test contents from above in to it.
7. Start a JupyterLab instance with the above config: `jupyter lab -c jupyter_server_test_config.py`
8. Run the tests with `npx playwright test`

</details>

## Expected behavior
 
I expect that interupting the kernel execution shouldn't cause the above test to fail. I expect that Galata should continue to operate correctly, and I expect there to be no errors thrown by Galata when you try to interrupt running code. 

## Context

- Operating System and version: Linux Debian 12
- Browser and version:  Chromium 130.0.6723.31
- JupyterLab version: 4.3.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
$PATH:
	/home/pdruce/Desktop/jlab-4.3-test/.venv/bin
	/home/pdruce/go/bin
	/home/pdruce/act/bin
	/home/pdruce/.pyenv/shims
	/home/pdruce/.pyenv/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/local/games
	/usr/games
	/usr/local/sbin
	/usr/sbin
	/sbin
	/usr/local/netbin

sys.path:
	/home/pdruce/Desktop/jlab-4.3-test/.venv/bin
	/home/pdruce/.pyenv/versions/3.11.10/lib/python311.zip
	/home/pdruce/.pyenv/versions/3.11.10/lib/python3.11
	/home/pdruce/.pyenv/versions/3.11.10/lib/python3.11/lib-dynload
	/home/pdruce/Desktop/jlab-4.3-test/.venv/lib/python3.11/site-packages

sys.executable:
	/home/pdruce/Desktop/jlab-4.3-test/.venv/bin/python

sys.version:
	6.11.10 (main, Oct  1 2024, 17:46:39) [GCC 12.2.0]

platform.platform():
	Linux-6.1.0-27-amd64-x86_64-with-glibc2.36

which -a jupyter:
	/home/pdruce/Desktop/jlab-4.3-test/.venv/bin/jupyter
	/home/pdruce/.pyenv/shims/jupyter

pip list:
	Package                   Version
	------------------------- --------------
	anyio                     4.6.2.post1
	argon2-cffi               23.1.0
	argon2-cffi-bindings      21.2.0
	arrow                     1.3.0
	asttokens                 2.4.1
	async-lru                 2.0.4
	attrs                     24.2.0
	babel                     2.16.0
	beautifulsoup4            4.12.3
	bleach                    6.2.0
	certifi                   2024.8.30
	cffi                      1.17.1
	charset-normalizer        3.4.0
	comm                      0.2.2
	debugpy                   1.8.8
	decorator                 5.1.1
	defusedxml                0.7.1
	executing                 2.1.0
	fastjsonschema            2.20.0
	fqdn                      1.5.1
	h11                       0.14.0
	httpcore                  1.0.6
	httpx                     0.27.2
	idna                      3.10
	ipykernel                 6.29.5
	ipython                   8.29.0
	isoduration               20.11.0
	jedi                      0.19.2
	Jinja2                    3.1.4
	json5                     0.9.27
	jsonpointer               3.0.0
	jsonschema                4.23.0
	jsonschema-specifications 2024.10.1
	jupyter_client            8.6.3
	jupyter_core              5.7.2
	jupyter-events            0.10.0
	jupyter-lsp               2.2.5
	jupyter_server            2.14.2
	jupyter_server_terminals  0.5.3
	jupyterlab                4.3.0
	jupyterlab_pygments       0.3.0
	jupyterlab_server         2.27.3
	MarkupSafe                3.0.2
	matplotlib-inline         0.1.7
	mistune                   3.0.2
	nbclient                  0.10.0
	nbconvert                 7.16.4
	nbformat                  5.10.4
	nest-asyncio              1.6.0
	notebook_shim             0.2.4
	overrides                 7.7.0
	packaging                 24.2
	pandocfilters             1.5.1
	parso                     0.8.4
	pexpect                   4.9.0
	pip                       24.3.1
	platformdirs              4.3.6
	prometheus_client         0.21.0
	prompt_toolkit            3.0.48
	psutil                    6.1.0
	ptyprocess                0.7.0
	pure_eval                 0.2.3
	pycparser                 2.22
	Pygments                  2.18.0
	python-dateutil           2.9.0.post0
	python-json-logger        2.0.7
	PyYAML                    6.0.2
	pyzmq                     26.2.0
	referencing               0.35.1
	requests                  2.32.3
	rfc3339-validator         0.1.4
	rfc3986-validator         0.1.1
	rpds-py                   0.21.0
	Send2Trash                1.8.3
	setuptools                65.5.0
	six                       1.16.0
	sniffio                   1.3.1
	soupsieve                 2.6
	stack-data                0.6.3
	terminado                 0.18.1
	tinycss2                  1.4.0
	tornado                   6.4.1
	traitlets                 5.14.3
	types-python-dateutil     2.9.0.20241003
	typing_extensions         4.12.2
	uri-template              1.3.0
	urllib3                   2.2.3
	wcwidth                   0.2.13
	webcolors                 24.11.1
	webencodings              0.5.1
	websocket-client          1.8.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.

Don't think this will be super useful. Let me know if you want it. 
</pre>

</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

Don't think this is super useful. Let me know if you need it
</pre>
</details>

**Comment by pauldruce** [comment]
Here are the playwright html test results with a trace. 
[playwright-report.zip](https://github.com/user-attachments/files/17715030/playwright-report.zip)

**Comment by pauldruce** [comment]
Actually, the issue was interrupting the kernel tool quickly after running the cell. This is resolved by adding a small wait statement between running the cell and interrupting. 

Closing this issue now.

**Comment by pauldruce** [comment]
I thought I'd fixed this, but the symptom persists, I've updated the test point to this new scenario and updated the playwright-report.

**Comment by pauldruce** [comment]
Any news on the cause of this and whether it can be addressed?

**Comment by jtpio** [comment]
According to the error above, it seems to be coming from this line:

https://github.com/jupyterlab/jupyterlab/blob/4a6bc6c573e0b3a10b1b23edcf0894aff42aa9c0/galata/src/galata.ts#L971

So maybe Galata needs to be fixed to handle the case of interrupts as part of its `mockRunners` function?
