### ISSUE TITLE
intermittently notebooks are taking long time to load after installing jupyter-server-nbmodel extensions.

### ISSUE THREAD

**Issue by abhijeetgurle-dream11** [jupyterlab/jupyterlab#16974]
## Description
I have recently installed [jupyter-server-nbmodel](https://github.com/datalayer/jupyter-server-nbmodel) extension on my jupyterlab setup. After installing it, notebooks are taking long time to load even on my local. It took around 4.5min to load a simple notebook with 6KB data. I have observed that the issue happens with older notebooks and not the notebooks which are created after the extension is installed.

<img width="1724" alt="Screenshot 2024-11-19 at 5 23 54 PM" src="https://github.com/user-attachments/assets/e09c3fe7-1053-4510-85c8-fc9ffedee648">

<img width="1728" alt="Screenshot 2024-11-19 at 5 39 18 PM" src="https://github.com/user-attachments/assets/affbbfa5-80df-4ecb-8b21-ebb1c73e374e">

## Reproduce

1. Install [jupyter-server-nbmodel](https://github.com/datalayer/jupyter-server-nbmodel)
2. Open multiple notebooks and see how much time it takes to load the notebook

## Expected behavior

The notebook should open normally as it would open without the extension.

## Context

- Operating System and version: MacOS Sonoma
- Browser and version: Chrome 131
- JupyterLab version: 4.3.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by abhijeetgurle-dream11** [comment]
sure @echarles

**Comment by fcollonval** [comment]
Closing as transferred: https://github.com/datalayer/jupyter-server-nbmodel/issues/28
