### ISSUE TITLE
Unable to see the "+" sign on the blue "New Launcher" button in the filebrowser.

### ISSUE THREAD

**Issue by thick-as-thieves** [jupyterlab/jupyterlab#16971]
## Description

 I am using a custom launcher extension in Jupyter Lab 4.2.5. 
 Similar to [this](https://github.com/jupyterlab/jupyterlab/issues/14810) issue, I was unable to see the "New Launcher" button once I disable the default @jupyterlab/launcher-extension and replace it with my custom extension. After creating a [schema/plugin.json](https://github.com/jupyterlab/jupyterlab/blob/130089eddb330a44f7f9d496b1e64eddcb497d6b/packages/launcher-extension/schema/plugin.json) file as suggested in the issue's discussion, I can now see the blue button but the plus sign is still missing. 
 
<img width="348" alt="Screenshot 2024-11-18 at 4 46 07 PM" src="https://github.com/user-attachments/assets/82ab55f1-eb28-4a09-9245-9e0332ede23b">

## Context

- Operating System and version: Mac
- Browser and version: Chrome latest
- JupyterLab version: 4.2.5

**Comment by JasonWeill** [comment]
@thick-as-thieves Have you also modified `@jupyterlab/ui-components`? That's where the SVG for the plus icon lives: https://github.com/jupyterlab/jupyterlab/blob/main/packages/ui-components/style/icons/toolbar/add.svg

In your page source, when you inspect this element, do you see the `<svg>` element in the SVG source file above? If not, does your custom extension depend on `@jupyterlab/ui-components`?

**Comment by krassowski** [comment]
To add to the above, it might be that the button you are adding has both label and the svg + icon. Is you schema 1-1 with the upstream one/with one in https://github.com/nebari-dev/jupyterlab-launchpad ?

**Comment by thick-as-thieves** [comment]
I am now testing in a fresh venv and I am unable to see the New Launcher button entirely. 
Yes, my extension depends on @jupyterlab/ui-components and I am directly using the LauncherIcon without any modification.
Earlier this was my [schema/plugin.json](https://github.com/jupyterlab/jupyterlab/blob/130089eddb330a44f7f9d496b1e64eddcb497d6b/packages/launcher-extension/schema/plugin.json) . Now, I changed, making it one on one with https://github.com/nebari-dev/jupyterlab-launchpad

**Comment by krassowski** [comment]
It's hard to help without seeing your code and what changes you made. There must be something that you are doing differently if it is not working for you but it is working fine in [jupyterlab-launchpad](https://github.com/nebari-dev/jupyterlab-launchpad).

**Comment by thick-as-thieves** [comment]
Thank you for taking the time to help with this issue. It’s resolved now! It turns out the repository had the launcherIcon but was missing the addIcon. Interestingly, the button displayed perfectly in JupyterLab 3, but it went missing after migrating to 4.x. Because of this, I didn’t realize the addIcon was missing right away.

Thanks again for your support!
