### ISSUE TITLE
`Debugger Variables Copy` visual regression tests do not pass with Python 3.12

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16982]
```
Notice:   3 failed
    [jupyterlab] › test/jupyterlab/debugger.test.ts:192:7 › Debugger Variables › Copy to globals should work only for local variables 
    [jupyterlab] › test/jupyterlab/debugger.test.ts:252:7 › Debugger Variables › Copy to globals not available from kernel 
    [jupyterlab] › test/jupyterlab/debugger.test.ts:289:7 › Debugger Variables › Copy to clipboard ─
```

**Comment by krassowski** [comment]
This is evidenced by these tests failing in unrelated PRs:
- https://github.com/jupyterlab/jupyterlab/pull/16975
- https://github.com/jupyterlab/jupyterlab/pull/16979

These tests were passing on Wed, 20 Nov 2024 09:34:33 GMT and failing on Wed, 20 Nov 2024 13:46:10 GMT

**Comment by krassowski** [comment]
Of note `maintainer-tools` [0.26.0](https://github.com/jupyterlab/maintainer-tools/releases/tag/v0.26.0) was released on Wed, 20 Nov 2024 12:48 GMT. It included the bump of the standard Python version to 3.12.

**Comment by krassowski** [comment]
I updated the titled to reflect that the tests are now passing on `main` but we still need to figure out what component in Python 3.12 causes them to fail and report to appropriate upstream.

**Comment by jtpio** [comment]
Thanks for hot-fixing this! Yeah it would be great to know more about what is happening with 3.12.
