### ISSUE TITLE
notebook with same name replace issue

### ISSUE THREAD

**Issue by xiansch** [jupyterlab/jupyterlab#16990]
## Description

I have discovered a weird bug I think.  I created a notebook 2 months ago in the folder that I'm doing those operations in (let's call it "datainput_prep.ipynb".  My friend gave me a directory to do something different but which contains one notebook that has the same name as one of the notebooks in the (totally unrelated directory) that I had saved other things in.  I found that when I tried to re-use my old "datainput_prep" I found that it had been entirely overwritten by the one my friend gave me and there is no way to revert it to the last checkpoint.  I'm very sad because there was a lot of work I lost in that notebook.  The two notebooks are not related at all and saved in two different directories, how could this happen?

## Reproduce

1. Create working directory with "a.ipynb"
2. Create a different working directory with a different "a.ipynb"
3. open jupyterlab and run the new "a.ipynb"
4. try to run the old "a.ipynb" -> it is replaced????

I expected to find my old notebook but I found it had been replaced with a new notebook with the same name saved in a different directory.  All I did was run them both in jupyterlab.

I didn't realize my friend gave me a notebook with the same name and wouldn't have expected them to be overwritten.  Especially since the last checkpoint that Jupyterlab gave me for my original "datainput_prep" is the same as every other notebook in that same folder, meaning that nothing should have been touched.

OS macOS Sonoma 14.1.1
Browser = Safari
- JupyterLab version: Jupyterlab Desktop 4.2.5-1

<details><summary>Troubleshoot Output</summary>
<pre>
N/A
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by andrii-i** [comment]
Thank you for creating this issue @xiansch. Could you please advise if you have jupyter-collaboration (real time collaboration) enabled?

**Comment by JasonWeill** [comment]
@xiansch If possible, could you try reproducing this issue with JupyterLab 4.3.x?

**Comment by JasonWeill** [comment]
@xiansch We haven't been able to reproduce this, and we didn't get the information that we requested from you. If you find any other bugs in JupyterLab, please open another issue here. Thank you for your contribution!
