### ISSUE TITLE
Printing carriage return (\r) from external (c++) python module screws text-out

### ISSUE THREAD

**Issue by peter-urban** [jupyterlab/jupyterlab#17039]
## Description

This is a followup of https://github.com/jupyterlab/jupyterlab/issues/16995.
While https://github.com/jupyterlab/jupyterlab/pull/16999 fixed the carriage return for the python print statement, I still get issues with \r based progressbars created in a c++ module (exposed via pybind11). 

Printing \r from a pybind11 module seems to screw up consecutive printing calls in the respective cell. The python print statement itself is not affected and seems to work fine since  https://github.com/jupyterlab/jupyterlab/pull/16999. Still, I believe that this is a regression related to https://github.com/jupyterlab/jupyterlab/pull/16999 and not to pybind11, because a) this worked fine in 4.2.6 and b) I can use e.g. xeus-cling without pybind11 to reproduce this issue

## Reproduce

Here I xeus-cling to to run the following code cells (e.g. mamba install -c conda-forge jupyterlab xeus-cling). Compiling a pybind11 module and calling the exposed function from jupyterlab produces the exact same results. 

Here are 2 code examples to explain the problem:

## Example 1: progress loop

```
#import <iostream>
#import <string>
using namespace std;

cout << "-- begin --" << endl;
for (size_t i=0; i <100; ++i){
    cout << "Progress: " << i << "\r" << flush;
}
cout << endl;
cout << "-- end --" << endl;
```

### Expected result (and result when using jupyterlab==4.2.6
```
-- begin --
Progress: 99
-- end --
```

### Result for jupyterlab==4.3.1
```
-- begin --
Progress: 0Progress: 1Progress: 2Progress: 3Progress: 4Progress: 5Progress: 6Progress: 7Progress: 8Progress: 9Progress: 10Progress: 11Progress: 12Progress: 13Progress: 14Progress: 15Progress: 16Progress: 17Progress: 18Progress: 19Progress: 20Progress: 21Progress: 22Progress: 23Progress: 24Progress: 25Progress: 26Progress: 27Progress: 28Progress: 29Progress: 30Progress: 31Progress: 32Progress: 33Progress: 34Progress: 35Progress: 36Progress: 37Progress: 38Progress: 39Progress: 40Progress: 41Progress: 42Progress: 43Progress: 44Progress: 45Progress: 46Progress: 47Progress: 48Progress: 49Progress: 50Progress: 51Progress: 52Progress: 53Progress: 54Progress: 55Progress: 56Progress: 57Progress: 58Progress: 59Progress: 60Progress: 61Progress: 62Progress: 63Progress: 64Progress: 65Progress: 66Progress: 67Progress: 68Progress: 69Progress: 70Progress: 71Progress: 72Progress: 73Progress: 74Progress: 75Progress: 76Progress: 77Progress: 78Progress: 79Progress: 80Progress: 81Progress: 82Progress: 83Progress: 84Progress: 85Progress: 86Progress: 87Progress: 88Progress: 89Progress: 90Progress: 91Progress: 92Progress: 93Progress: 94Progress: 95Progress: 96Progress: 97Progress: 98Progress: 99
-- end --
```

### Result for jupyterlab==4.3.2
```
-- begin --

-- end --
9
```

## Example 2: consecutive print statements

It seems that this error is related to the cursor position handling in v4.3.2.
Before  calling "cout << endl" the code actually produces "Progress: 99" in jupyterlab 4.3.2. However, calling cout << endl; deletes the current line and than copies part of the line to the end of the cell. Take the following code block

```
#import <iostream>
using namespace std;

cerr << "--0123456789-ABCDEFGHIJKLMNOP--\r" << flush;
cerr << endl;
cerr << "Second" << endl;
```

### Expected result (jupyterlab 4.2.6 AND 4.3.1)
```
--0123456789-ABCDEFGHIJKLMNOP--
Second
```

### Result jupyterlab 4.3.2
```

Second
6789-ABCDEFGHIJKLMNOP--
```

(Notice the empty line at the beginning of the 4.3.2 output)
The behavior that part of the '\r' text is copied to the end of the cell is carried forth with consecutive print statements. Take the following code:

```
#import <iostream>
using namespace std;

cerr << "--0123456789-ABCDEFGHIJKLMNOP--\r" << flush;
cerr << endl;
cerr << "Second" << endl;
cerr << "third" << endl;
```

### Result Jupyterlab 4.3.2

```

Second
third
BCDEFGHIJKLMNOP--
```

The behavior that part of the \r line is moved to the end of the cell continues even when calling \r from a pybind11 module and then calling print() from within python.

## Example 3: using python loop only
For completenes, the following loop produces the correct results in jupyterlab 4.2.6 and 4.3.2

```
print("-- begin --")
for i in range(100):
    print('Progress:',i,end='\r')
print()
print("-- end --")
```

The python print statement is thus not affected.

## Context

- Operating System and version: Linux Ubuntu 24.04 (Likely operation system independent)
- JupyterLab version: e.g. 4.3.2
- See also this bug: https://github.com/jupyterlab/jupyterlab/issues/16995

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
The failure can be also reproduced in Python if you also flush, the same way as you do in your C++ code:

```python
import sys

print("-- begin --")
for i in range(100):
    print('Progress:',i,end='\r')
    sys.stdout.flush()
print()
print("-- end --")
```

```
-- begin --

-- end --
9
```

**Comment by krassowski** [comment]
It looks like this is the minimal reproducer

```python
import sys
sys.stdout.write('abc\r')
sys.stdout.flush()
sys.stdout.write('\n-');
```

Actual: 

```

-c
```

Expected same as `print('abc\r\n-')`:

```
abc
-
```

**Comment by krassowski** [comment]
CC @davidbrochart

**Comment by peter-urban** [comment]
Thanks a lot for dealing with this so fast! Looking forward to trying the next version.
It is a pleasure to report bugs here :-)
