### ISSUE TITLE
Wrong file name order

### ISSUE THREAD

**Issue by Nriver** [jupyterlab/jupyterlab#17037]
## Description

File order is wrong. Numbers are not placed in correct order.

## Reproduce

![ksnip_20241204-164821](https://github.com/user-attachments/assets/55c00fca-cc66-449e-955e-bf8dff0b091b)

## Expected behavior

like this

![ksnip_20241204-164745](https://github.com/user-attachments/assets/a275d2fc-7ab9-41d9-b34c-192363a7c836)

**Comment by krassowski** [comment]
Is this the same as https://github.com/jupyterlab/jupyterlab/issues/14392?

**Comment by Nriver** [comment]
No, I thought it was the same. But it's not. That issue is the difference of `ASCII` order and natural sort order.
