### ISSUE TITLE
Split notebook cells horizontally

### ISSUE THREAD

**Issue by frmdstryr** [jupyterlab/jupyterlab#1704]
It would be nice if multiple notebook cells could be "embedded" into one cell so the output could be rendered horizontally like a flexbox.  

Could be used for putting text beside a chart output instead of above / below.

Awesome work so far!!

**Comment by ddavidebor** [comment]
Interesting idea! It would fit more content to a screen than a standard notebook, considering the proportion of a 16:9 screen.

In #1640 there's a good discussion about dashboarding, somewhat related.

**Comment by blink1073** [comment]
Hi @frmdstryr, sorry, I missed this issue.  That seems like a good candidate for a third party plugin that provides an alternative notebook view.
