### ISSUE TITLE
File browser column resize prevents drag and drop  

### ISSUE THREAD

**Issue by DrNickBailey** [jupyterlab/jupyterlab#17042]
## Description

When first loaded the files in the side browser can be click and dragged and dropped in a folder etc. 

But after once adjusting the left-right split of the name/size columns, the whole side browser if clicked and dragged continues to adjust the split rather than clicking and dragging a file. 

1. View file browser (ctrl+b)
2. Validate one can click-and-drag a file
3. Then click to adjust the name/size column width 
4. Then try and click+drag a file
5. Column will automatically re-adjust width and no file can be dragged.

## Expected behavior

Column adjustment should only happen when the column header is selected

## Context

- Operating System and version: Mac Sequoia 15.1.1
- Chrome Version 131.0.6778.109 (Official Build) (arm64) & Safari Version 18.1.1 (20619.2.8.11.12)
- JupyterLab version: 4.3.1_1 and 4.3.2_1

**Comment by DrNickBailey** [comment]
It was there but I'd accidentally deleted only the `-->` from the opening comment lines leaving that initial `<!--` present and thus rendering the whole description commented out. 🤦‍♂️

**Comment by Darshan808** [comment]
Working on this!

**Comment by DrNickBailey** [comment]
Oh brilliant to hear :)  Sorry to be a pain !

**Comment by Darshan808** [comment]
Thank you for reporting the bug!
