### ISSUE TITLE
Help tooltip (shift-tab) does not allow to copy content

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyterlab/jupyterlab#1705]
Copying some text (eg an example) out of a help tooltip can be useful, and is also possible in the classic notebook. 
In jupyterlab, this is not possible because the tooltip disappears the moment I press 'ctrl' for doing 'crtl+c' to copy.

Using latest jupyterlab from conda-forge (0.16), with Firefox on Ubuntu 16.04.

**Comment by alexandercbooth** [comment]
Good catch @jorisvandenbossche!

I think this might be OK to close since it appears to be fixed with #1727.

**Comment by blink1073** [comment]
Indeed, thanks!
