### ISSUE TITLE
Selected cell "moves out of sight" when adding a new cell below

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyterlab/jupyterlab#1706]
The title is maybe not the best description, but a gif is probably clearer. What I do here in the gif, is simply pressing a few times 'b' to add new cells below the existing one (and scrolling down at the end):

![peek 2017-02-13 14-39](https://cloud.githubusercontent.com/assets/1020496/22885636/8cc4b4ac-f1fa-11e6-9927-3bbd48ac3414.gif)

As you can see, the selected cell (the new cell that is added below) moves out of sight, as the view does not update and does not scroll down automatically with the selected cell. 
In the classic notebook, the selected cell keeps being focused and the view is updated on each 'b' stroke.

Reported with latest jupyterlab from conda-forge (0.16.0), using Firefox on Ubuntu 16.04.

**Comment by blink1073** [comment]
Thanks for the report, @jorisvandenbossche.  I'll clean this up as part of #1695.
