### ISSUE TITLE
open markdown like readme.md automatically when open a folder?

### ISSUE THREAD

**Issue by linlol** [jupyterlab/jupyterlab#17075]
### Problem

We deliver jupyterlab as internal common analytics solutions by leveraging jupyterhub and k8s. 

Hence, I wonder that is there any approach to open markdown by default, when open folder with specific pattern? 

In this case, we can setup some introductive markdown, and make it opened automatically when users open the folder.

### Proposed Solution

We can write lab extension to add/override fileTypes , can we bind an action on folder to open some specific file?

**Comment by UdayMalviya** [comment]
you can create custom jupyterlab extension to achieve the desired behavior.

**Comment by krassowski** [comment]
Indeed it sounds like this could be implemented in an extension listening to [`FileBrowserModel.pathChanged`](https://jupyterlab.readthedocs.io/en/latest/api/classes/filebrowser.FileBrowserModel-1.html#pathChanged) signal.

**Comment by UdayMalviya** [comment]
Yes that's a good idea

**Comment by linlol** [comment]
> Yes that's a good idea

haha thanks, it's implemented
