### ISSUE TITLE
Downstream browser check tests are failing since 4.3.3 release

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#17079]
## Description

Browser check tests are failing in extensions due to:

```
Parsed an error from text content: undefined RangeError: Incorrect locale information provided
```

most likely introduced by https://github.com/jupyterlab/jupyterlab/pull/17038

## Reproduce

See https://github.com/nebari-dev/jupyterlab-launchpad/pull/71 or https://github.com/jupyterlab/jupyter-collaboration/issues/416

## Expected behavior

No errors on CI

## Context

- JupyterLab version: 4.3.3

**Comment by mahendrapaipuri** [comment]
We noticed the failures for [jupytext](https://github.com/mwouts/jupytext/actions/runs/12341034946/job/34439227541?pr=1297) as well. Seems like empty `LANG` is causing the error which is the case on GH runners, I guess. 

I could reproduce the error in a container and by setting `LANG=en_IN.utf8` passed the test.

**Comment by krassowski** [comment]
Interestingly this works fine with the `main` branch.

**Comment by krassowski** [comment]
^ was incorrect. But after some more digging I extracted the values for `translator.languageCode` and `navigator.language` from CI when this is failing:

- `translator.languageCode`: `undefined`
- `navigator.language`: `en-US@posix`

This is quite... surprising? Something is wrong:
- either `en-US@posix` is not a valid BCP 47 tag and should not be reported by [`navigator.language`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language) in this form, or
- it is a valid BCP 47 tag and should be accepted by [`String.prototype.localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#locales)

as specification says that the former should return BCP 47 and later should accept BCP 47. And here is my evening...

Apparently, Google team run into this issue too as it was breaking printing of footers and headers in Chrome https://issues.chromium.org/issues/337047877 but their solution was to just ignore anything after and including `@`, rather than to fix the discrepancy...

**Comment by krassowski** [comment]
Also reported in:
- https://github.com/microsoft/playwright/issues/34046
