### ISSUE TITLE
Notebook toolbar popup background color

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#17096]
## Description

The notebook toolbar responsive popup seems to have a different background color than the visible part of the toolbar.

Not sure if this was changed on purpose, but it looks a bit odd with the light theme.

## Reproduce

With JupyterLab 4.3.3:

[jupyterlab-unstyled-toolbar.webm](https://github.com/user-attachments/assets/73c52d0b-19ab-4338-8380-492bdeb2cd1d)

## Expected behavior

Keep the same background color?

## Context

JupyterLab 4.3.3

**Comment by jtpio** [comment]
This is also visible with the dark theme:

![image](https://github.com/user-attachments/assets/2edf3ee6-5557-4929-94e5-3fdd1ce53855)

**Comment by jtpio** [comment]
Quickly looking at the styles, this seems to be caused by the `.jp-ThemeContainer` rule taking precedence on `.jp-Toolbar-responsive-popup`:

![image](https://github.com/user-attachments/assets/aa97ec47-354e-4d70-a71a-51f777510bc9)

**Comment by krassowski** [comment]
This was not intended, it must be a side effect of `.jp-ThemeContainer` addition.
