### ISSUE TITLE
Show pop up to login again if cookies are expired

### ISSUE THREAD

**Issue by CarlosDominguezBecerril** [jupyterlab/jupyterlab#17103]
### Problem

Jupyter Hub allows authentication of users.  If you log in to your server and afterwards your cookies expire or are deleted you can still run code. Is this expected? Could we make this optional?

### Proposed Solution

Show a prompt to the user telling them to log in again. While the user doesn't have valid cookies the server should not be executing more code (or at least don't add more code to the queue)

### Additional context
A video might be more clear

https://github.com/user-attachments/assets/0f197bc0-c39d-4336-a5f4-477b27990b8e

**Comment by krassowski** [comment]
It is expected in the sense that in absence of cookies JupyterLab is using auth token to authorize the requests with jupyter-server. You would need to expire the token, not only the cookie. I recall there is an option to expire these tokens in JupyterHub.

In general, there is no auth logic in JupyterLab (this repository). Your question is better suited for https://github.com/jupyterhub/jupyterhub (or if you were not using JupyterHub, then https://github.com/jupyter-server/jupyter_server).

**Comment by CarlosDominguezBecerril** [comment]
Thanks!

**Comment by xgdgsc** [comment]
I only use jupyterlab with passwords set. I get annoying file fail to save becasue I need to re-login issues sometimes. Can it be never expire when there's kernel running ? I get code lost because I cannot save when the need to relogin happens.
