### ISSUE TITLE
Extension manager always falls back to read-only when proxy is used with httpx<0,28

### ISSUE THREAD

**Issue by AmberArr** [jupyterlab/jupyterlab#17110]
## Description

It seems that we cannot pass an `AsyncHTTPTransport` to `proxies`.

https://github.com/jupyterlab/jupyterlab/blob/ecb67ec0d7066b8e6019e158a9d411635575eb22/jupyterlab/extensions/pypi.py#L77-L78

Since [`httpx` cares about the proxy environment variables](https://github.com/encode/httpx/blob/26d48e0634e6ee9cdc0533996db289ce4b430177/docs/environment_variables.md#proxies) [all the time](https://github.com/encode/httpx/commit/b0fa0859a8954edf7aaa5e4d64d85bd16765cd23), I suggest that we can just let `httpx` do its work.

<details><summary>Console output</summary>
<pre>
[W 2024-12-20 14:53:44.931 LabApp] Failed to instantiate the extension manager pypi. Falling back to read-only manager.
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/jupyterlab/labapp.py", line 835, in initialize_handlers
        ext_manager = manager_factory(app_options, listings_config, self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/jupyterlab/extensions/__init__.py", line 46, in get_pypi_manager
        return PyPIExtensionManager(app_options, ext_options, parent)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/jupyterlab/extensions/pypi.py", line 143, in __init__
        self._httpx_client = httpx.AsyncClient(**_httpx_client_args)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1456, in __init__
        else self._init_proxy_transport(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1509, in _init_proxy_transport
        return AsyncHTTPTransport(
               ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 296, in __init__
        elif proxy.url.scheme in ("http", "https"):
             ^^^^^^^^^
    AttributeError: 'AsyncHTTPTransport' object has no attribute 'url'
</pre>
</details>

## Reproduce

1. Open the extension manager tab
2. See the bug

## Expected behavior

No more warning or read-only manager

## Context

- jupyterlab version 4.3.4
- httpx version 0.27.2

**Comment by krassowski** [comment]
> Since [httpx cares about the proxy environment variables](https://github.com/encode/httpx/blob/26d48e0634e6ee9cdc0533996db289ce4b430177/docs/environment_variables.md#proxies) [all the time](https://github.com/encode/httpx/commit/b0fa0859a8954edf7aaa5e4d64d85bd16765cd23)

I think it does not handle lowercase variables, which for one reason or another was desirable: https://github.com/jupyterlab/jupyterlab/pull/16287.

Previously `HTTPTransport` was used instead of `AsyncHTTPTransport`. Maybe <0.28 needs `HTTPTransport`?

**Comment by krassowski** [comment]
And even before that bares strings were used:

https://github.com/jupyterlab/jupyterlab/blob/6c6852e436207229af7846275367e080cd7bd1b9/jupyterlab/extensions/pypi.py#L63-L66

**Comment by AmberArr** [comment]
https://github.com/encode/httpx/blob/26d48e0634e6ee9cdc0533996db289ce4b430177/httpx/_utils.py#L30

It uses `urllib.request.getproxies()` which handles lowercase variables. I tested httpx with lowercase vars and it works.

It seems like <0.28 should also use `AsyncHTTPTransport`. So I think `proxies` and plain string for <0.28 and `mounts` and `AsyncHTTPTransport` for >=0.28 should be ok.

**Comment by krassowski** [comment]
Thanks for looking into this more! Would you like to open a PR?

**Comment by krassowski** [comment]
> Should I just do this

I think these could be two separate PRs. I see your point but would feel more comfortable only backporting the minimal fix necessary to the stable version.
