### ISSUE TITLE
Using File Browser in my plugin

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#1713]
I wanted to directly use the file browser object loaded in the side bar in shell. How can I access the object which has already been created and loaded in that side bar.

I initially tried importing the class and using `new` to create an object:
```
let fbModel = new FileBrowserModel({ manager });
```
but realized that I am creating a new FileBrowser and the actions and other variables won't be the same as the existing FileBrowser in the side bar. Hence, how do I get the FileBrowser in the shell ?

In Javascript I can see the FileBrowser object with `jupyter.lab.shell._leftHandler._stackedPanel.widgets._array[0]` but this won't work in TypeScript because they're private members

Note: I am using JupyterLab 0.13.x with Google Chrome on Mac

**Comment by blink1073** [comment]
Hi @rsinha25, we intentionally limited the global API of the application, preferring to keep things encapsulated.  Are you writing an extension that wants to use the file browser model directly?  If so, we are going to make it a published token in #1653.

**Comment by blink1073** [comment]
I am going to close this as answered, please feel free to reopen if you disagree.
