### ISSUE TITLE
Dragging multiple cells to its original location inverts order of selected cells

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyterlab/jupyterlab#1715]
When you want to move multiple selected cells using the 'drag' functionality, but in the end decide not to move them, and so release the mouse-down at the original location, the order of the selected cells gets inverted:

![peek 2017-02-14 17-01](https://cloud.githubusercontent.com/assets/1020496/22937051/a57fa726-f2d7-11e6-8bc3-c7822407a071.gif)

Latest JupyterLab from conda-forge (0.16.0) using Chrome/Firefox on Ubuntu 16.04

**Comment by blink1073** [comment]
Ha, that wasn't what you wanted?  Thanks for the report!

**Comment by sccolbert** [comment]
@jorisvandenbossche as an FYI you can also press `Escape` to cancel a drag.

**Comment by jorisvandenbossche** [comment]
Yep, I know. But what I tried first is something a lot of people will try I think 
(I personally find a keyboard press to undo a mouse action a bit unintuitive, although that is probably just a question of habit. As I also noticed this when dragging cells but by accident clicking on the output, which lets you put the output area in its own panel. But as I didn't want to do that (I wanted to drag the cell), I needed to 'undo' this mouse action, but only after some time figured I could use Escape)

**Comment by sccolbert** [comment]
Cool, was just a tidbit in case you didn't know. Escape-to-cancel-drag is a common interaction on Windows and supported by nearly everything (not sure about Mac).

**Comment by blink1073** [comment]
(Confirmed on Mac).

**Comment by jorisvandenbossche** [comment]
> Escape-to-cancel-drag is a common interaction

OK! Just not in my muscle-memory. Probably because in the classic notebook there was no drag :-)
