### ISSUE TITLE
Keyboard shortcut for command palette (cmd-shift-P) not working with Firefox

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyterlab/jupyterlab#1718]
At least on Linux/Windows, the shortcut to get the command palette is Ctrl-Shift-P, and this shortcut is already used by Firefox to open a new private window. 

I suppose https://github.com/jupyterlab/jupyterlab/issues/893 will be a solution, so the user can edit this shortcut, but it would be nice if there is a default that works for getting the command palette.

Tested with jupyterlab from conda-forge (0.16.0), using Firefox on Ubuntu 16.04. Also tested that it *does* work correctly using Chrome on same machine.

**Comment by sccolbert** [comment]
Thanks for the report!

Maybe we need to update keymap to also support browser-specific shortcuts in addition to OS-specific shortcuts. 

Browser keyboard handling it ridiculous...

**Comment by ian-r-rose** [comment]
This is no longer relevant, as the default for the command palette keyboard shortcut has been changed to `Ctrl-Shift-C`.

**Comment by dlukes** [comment]
Just a note here, maybe for my future self: `Ctrl/Cmd-Shift-C` actually also is a Firefox shortcut, it opens the Developer Tools by default. AFAICS, JupyterLab is able to override it (v1.0.4), but one confusing thing might still happen: **if you have JupyterLab open in Firefox and its tab is focused but the page itself is not focused** (e.g. the address bar is focused instead), **then `Ctrl/Cmd-Shift-C` will revert to opening Developer Tools**, which might look as if the shortcut is not working. It is, you just need to click anywhere inside the page to give JupyterLab a chance to capture the keyboard event :)
