### ISSUE TITLE
Standardize widget names

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1722]
Some of our widget names have `Widget` in them, some have `Panel` in them, and some have no suffix at all.  Also, our CSS class names sometimes do not contain the `Widget` suffix when the class name does.

**Comment by sccolbert** [comment]
For reference, I use the "Panel" suffix in Phosphor when the widget is designed to hold and layout other widgets. Not *just* when a widget is a subclass of `Panel`. For example, `DockPanel` is not a `Panel` subclass, but it contains and lays out other widgets.

**Comment by blink1073** [comment]
Outcome of discussions today with @afshin and @sccolbert:

In JupyterLab, any `Widget` subclass should take the suffix `Widget` or `Panel` to differentiate it from other classes.  The widget may define an `IModel`, which as an associated `Model`-suffixed implementation.  CSS class names should include the `Widget` suffix so they are 1-1.

For notebook-related classes, the raw model is defined in `nbformat`.  Each widget has a live model that can be created from and serialized to the raw model.

```
NotebookPanel
  ToolbarWidget
  NotebookWidget
NotebookWidget
 IModel extends StaticNotebookWidget.IModel
StaticNotebookWidget
 IModel

CellWidget - base class for NotebookWidget children
RawCellWidget
  IModel
...
ICellModel - any one of the cell IModels
RawCellModel
...

OutputAreaWidget
 IModel

OutputWidget - Base class for OutputAreaWidget children
DisplayDataWidget
 IModel
...
IOutputModel - any one of the cell IModels
DisplayDataModel
...
```
...
```

We would also have:

```
ConsolePanel
    ToolbarWidget
    ConsoleWidget
```

**Comment by blink1073** [comment]
Note to self: also bring the `attachments` to the cell model when that gets refactored.

**Comment by blink1073** [comment]
Closing in favor of #2090.
