### ISSUE TITLE
jQuery related: Uncaught TypeError: Cannot set property 'plugin' of undefined

### ISSUE THREAD

**Issue by hainm** [jupyterlab/jupyterlab#1723]
hi,

so I've trying [nglview](https://github.com/arose/nglview) labextension but getting above error.
I also tried with regular `notebook` and this works for me.

Any idea how to make it work in lab?

<img width="1279" alt="screen shot 2017-02-15 at 10 46 55 am" src="https://cloud.githubusercontent.com/assets/4451957/22982215/78c4e54e-f36c-11e6-8205-bfceab900124.png">

**Comment by hainm** [comment]
The header for our file that uses `jQuerry ui` is something like this

```
var widgets = require("jupyter-js-widgets");
var NGL = require('ngl');
var $ = require('jquery');
require('jquery-ui');
require('jquery-ui/ui/widgets/draggable');
require('jquery-ui/ui/widgets/slider');
require('jquery-ui/ui/widgets/dialog');
```

thanks.

Hai

**Comment by sccolbert** [comment]
Are you running the most recent JLab? You might need to rebuild your bundle. 13 days is a long time in JLab alpha world :)

**Comment by blink1073** [comment]
It looks like nbwidgets was updated 6 days ago, that'd be my guess.

**Comment by hainm** [comment]
I installed `jupyterlab` from `conda-forge`, `v0.16.2`. 

installed `ipywidgets` from master branch today (did `git clean -fdx .` too).
I've also tried to rebuild my bundle and will try again. thanks.

**Comment by hainm** [comment]
rebuilding my bundle does not help. :D

**Comment by blink1073** [comment]
@jasongrout, any ideas?

**Comment by jasongrout** [comment]
jupyterlab_widgets should work with 0.16.2.

It looks like this is a problem in using jquery-ui. I've run into issues like this where the `$` I got by importing jquery was not the same jquery instance as what jquery-ui attached itself to. I debugged it by setting breakpoints in jquery-ui and in my file and confirming that there were two different jquery objects, one which was modified by jquery-ui to add the `.ui`, and another which I got by doing the import.

**Comment by jasongrout** [comment]
You should probably also upgrade the extension builder: https://github.com/arose/nglview/blob/master/js/package.json#L33

**Comment by hainm** [comment]
thanks. I am using lab v0.16.2, so which version I should change below

```bash
 "@jupyterlab/extension-builder": "^0.8.1",
```

**Comment by hainm** [comment]
nvm, I just look at versions in the `bqplot`

https://github.com/jasongrout/bqplot/blob/784c9ac6c6391d64acd518a348809e59b9a7a85b/js/package.json#L32

**Comment by hainm** [comment]
doesn't help solving the issue.

**Comment by jasongrout** [comment]
> installed ipywidgets from master branch today (did git clean -fdx . too).
> I've also tried to rebuild my bundle and will try again. thanks.

(depending on when you pulled from master, you may have already had the most recent changes in 0.6.13...)

**Comment by ellisonbg** [comment]
Looks like this is working: https://github.com/arose/nglview/blob/master/examples/jupyterlab.md

**Comment by yuri-sakharov** [comment]
Hi, @hainm.
How do you solve the problem? I got similar issue in another project:
`return $.ui.plugin = {
                   ^

TypeError: Cannot set property 'plugin' of undefined
    at /Users/yuri/repos/v3/node_modules/jquery-ui/ui/plugin.js:14:20
    at $.ui.plugin.add.proto (/Users/yuri/repos/v3/node_modules/jquery-ui/ui/plugin.js:9:3)
    at Object.<anonymous> (/Users/yuri/repos/v3/node_modules/jquery-ui/ui/plugin.js:11:3)
    at Module._compile (module.js:641:30)
    at Module._compile (/Users/yuri/repos/v3/node_modules/pirates/lib/index.js:88:24)
    at Module._extensions..js (module.js:652:10)
    at Object.newLoader [as .js] (/Users/yuri/repos/v3/node_modules/pirates/lib/index.js:93:7)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)`

**Comment by hainm** [comment]
@yuri-sakharov I think you need to explicitly import jquerry and related ui to your code. Example from nglview is here: https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js#L3
https://github.com/arose/nglview/blob/7554eece38989e41fbc6d84efa54f8e6d94f808d/js/package.json#L44

Hope this help.

**Comment by yuri-sakharov** [comment]
Thanks, I will try.
