### ISSUE TITLE
0.16.2: "Error: No provider for: jupyter.services.rendermime" or "jupyter.services.doc-registry"

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#1732]
What changed in 0.16.2 that would cause this?

```
Uncaught (in promise) Error: No provider for: jupyter.services.rendermime.
    at JupyterLab.Application.resolveService (http://localhost:8888/lab/main.bundle.js:13145:36)
    at Array.map (native)
    at JupyterLab.Application.activatePlugin (http://localhost:8888/lab/main.bundle.js:13107:39)
    at Array.map (native)
    at JupyterLab.Application.start (http://localhost:8888/lab/main.bundle.js:13193:34)
    at JupyterLab.start (http://localhost:8888/lab/main.bundle.js:1523:40)
    at http://localhost:8888/lab:88:7
```

**Comment by blink1073** [comment]
Do you have a link to something I can build against?

**Comment by gnestor** [comment]
You can just clone and install https://github.com/jupyterlab/jupyterlab_json using the `install.sh` script. I'm running lab from latest on master.

**Comment by gnestor** [comment]
Upon further investigation, it looks like upgrading from `@jupyterlab/services@0.34` to `@jupyterlab/services@0.38` is causing the above error. Downgrading it results in a new error:

```
Uncaught (in promise) Error: Widget is not contained in the dock panel.
    at DockPanel.activateWidget (main.bundle.js:19924)
    at ApplicationShell.activateMain (main.bundle.js:17606)
    at main.bundle.js:17697
```

Here are the `npm ls` of a working extension and a broken one:

Working:

```
├── @jupyterlab/extension-builder@0.10.1
├── @jupyterlab/services@0.38.0
├── jupyterlab@0.16.0
├── phosphor@0.7.1
```

Not working:

```
├── @jupyterlab/extension-builder@0.10.0
├── @jupyterlab/services@0.34.3
├── jupyterlab@0.16.0
├── phosphor@0.7.0
```

**Comment by blink1073** [comment]
Haven't forgotten about this, will look at it this weekend.

**Comment by blink1073** [comment]
I ran `jupyterlab_json` against the `v0.16.2` tag of the JupyterLab  repo and it works fine.  I suspect it didn't work against master because I mishandled the bugfix release.  Also, #1709 makes some changes to the way rendermimes are handled.

**Comment by gnestor** [comment]
It looks like a `git clean -xfd` resolved this.

**Comment by blink1073** [comment]
👍

**Comment by ian-r-rose** [comment]
I am installing an extension with @ellisonbg and @cameronoelsen, and running into a very similar issue to this one. It appears on both of their machines, but not mine. I am sure it is an issue with how I have set up the dependencies, but don't really know how to go about resolving it. Any suggestions would be appreciated.

**Comment by blink1073** [comment]
I suspect this is a result of incompatible dependencies, and can be fixed by disabling all of them.

**Comment by blink1073** [comment]
Also, 0.17.0 is now tolerant of plugins that fail to load.

**Comment by gnestor** [comment]
@ian-r-rose The extension's jupyerlab dependency version and the installed version of jupyerlab must match, so if the extension depends on `^0.16` and you're running the latest on jupyterlab master, you will see this. Additionally, there are some breaking API changes in jupyterlab `0.17.0` that affect renderers and rendermime.
