### ISSUE TITLE
Insert mode is lost when switching tabs in Chrome

### ISSUE THREAD

**Issue by blahster** [jupyterlab/jupyterlab#1737]
Say I'm editing a code cell and I Control+Tab to another browser and back, it's not in edit mode anymore.
If I type 'x' it'll just cut the cell.
I have to hit <enter> to first enter edit mode.

Haven't checked in other browsers.
I'm on Mac OSX Sierra with Chrome 56.0.2924.87

**Comment by blink1073** [comment]
Good catch, thanks!  The classic notebook preserves the mode in this case.  

Broader question: should mode be preserved when switching between tabs *within* JupyterLab?

@ellisonbg, thoughts?
