### ISSUE TITLE
Pasting multiline comments into ipython 5 in the web terminal only pastes the first line

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#1738]
Following up on @williamstein's [message to sage-devel](https://groups.google.com/forum/#!topic/sage-devel/t2QucyHLQXg), we found that pasting a multi-line comment into ipython in the JupyterLab terminal only pastes the first line. Starting IPython with `--simple-prompt` allows us to paste multiline comments.

![ipython2](https://cloud.githubusercontent.com/assets/192614/23095281/32cfff68-f5d5-11e6-9427-1b453b7bc1e5.gif)

Pasting multi-line code blocks seems to work fine. 

We also see this issue in the Jupyter Notebook (4.4.1) terminal and in SageMathCloud terminal.

CC @takluyver - any idea on what might be going on? (or any clue off the top of your head about where we might look to find the problem?)

**Comment by williamstein** [comment]
We both use term.js, so that may be relevant...

**Comment by blink1073** [comment]
I just fired up the demo included in xterm.js repo and the same behavior exists there.

**Comment by takluyver** [comment]
I can also reproduce it in the notebook terminal. Looking at the source, I don't think xtermjs implements bracketed paste yet, whereas most desktop terminal emulators do, I believe. So I'd guess that it gets the first line, then the newline sends that to be executed, and the other lines arrive before the new prompt is ready to pick them up, so they're discarded.

It doesn't seem to be specific to comments; I see the same thing pasting:

```python
a = 1
b = 2
```

**Comment by jasongrout** [comment]
I just checked, and this works now. Likely an xterm upgrade, maybe?
