### ISSUE TITLE
[console] Prevent default actions on the editor focus

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#1744]
The console handles on a key down event by focusing an editor if it is not focused and a new line was inserted. It leads to inserting a new line in the prompt with Monaco editor when a user provides input.
![2cc7ccc2-d758-11e6-836e-fb6c6f79614b](https://cloud.githubusercontent.com/assets/3082655/23119116/27516a18-f757-11e6-97eb-2ecb335c4857.gif)

Would it be possible to prevent defaults after focusing the editor:
https://github.com/jupyterlab/jupyterlab/blob/master/src/console/widget.ts#L446

**Comment by blink1073** [comment]
Good call, thanks!
