### ISSUE TITLE
Syntax highlighting of IHaskell does not work

### ISSUE THREAD

**Issue by arsenal9971** [jupyterlab/jupyterlab#1752]
The syntax highlighting of the IHaskell (https://github.com/gibiansky/IHaskell) kernel that I got in my Jupyter notebook does not work in Jupyter lab, here a screenshot
![bug haskell](https://cloud.githubusercontent.com/assets/9786736/23131807/ba8c0a3e-f78b-11e6-9000-5bcc080db74f.png)

**Comment by blink1073** [comment]
Thanks for the report, we'll have to install `IHaskell` and investigate.

**Comment by MMesch** [comment]
[E 16:51:22.890 LabApp] Notebook JSON is invalid: Additional properties are not allowed ('source' was unexpected)
    
    Failed validating 'additionalProperties' in display_data:
    
    On instance['cells'][0]['outputs'][0]:
    {'data': {'text/html': '<style>/* Styles used for the Hoogle display in the '
                           'pager */\n'
                           '.ho...',
              'text/plain': '[] :: forall a. [a]'},
     'metadata': {},
     'output_type': 'display_data',
     'source': 'haskell'}

**Comment by MMesch** [comment]
what would be the best way to adapt this @blink1073 ? Should there be an Extension that activates when the Haskell kernel is loaded ? I'll also check how the syntax highlighting is done ...

**Comment by MMesch** [comment]
The IHaskell kernel currently defines the codemirror mode 'ihaskell' that doesn't exist on standard jupyterlab. It works fine if it is changed in the kernel to 'Haskell'.

It would be useful to define a new codemirror mode however that is specific for IHaskell ...

**Comment by MMesch** [comment]
the haskell kernel now comes with a labextension that defines its own `ihaskell` codemirro mode. So I think this issue can be closed

**Comment by blink1073** [comment]
Great!
