### ISSUE TITLE
Syntax highlighting of C++-cling does not work 

### ISSUE THREAD

**Issue by arsenal9971** [jupyterlab/jupyterlab#1753]
The syntax highlighting of the C++-cling (https://github.com/vgvassilev/cling/tree/master/tools/Jupyter) kernel that I got in my Jupyter notebook does not work in Jupyter lab, here a screenshot
![bug_cling](https://cloud.githubusercontent.com/assets/9786736/23131884/033b1c3e-f78c-11e6-9136-6ed266eadfca.png)

**Comment by sccolbert** [comment]
Probably has something to do with the code mirror highlighting modes we are including in our default bundle.

**Comment by blink1073** [comment]
My initial thought was that the kernel info data we are getting is not getting mapped to the proper CodeMirror mode.

**Comment by blink1073** [comment]
It looks like https://github.com/root-project/cling/pull/132 has the fix.

**Comment by DiegoAlbertoTorres** [comment]
https://github.com/root-project/cling/pull/132 was merged, I think this can be closed now.

**Comment by ellisonbg** [comment]
Thanks!
