### ISSUE TITLE
Anchor tags not working for internal links 

### ISSUE THREAD

**Issue by prathamatic** [jupyterlab/jupyterlab#1759]
I want to make a link to another section in the lab notebook. I used `[Link to the destination](#num)` and it works in jupyter notebook but not in lab. The link redirects to http://localhost:8890/files/%23num in jupyterlab but scrolls to section called `num` in notebook.

**Comment by blink1073** [comment]
Hi @prathamatic, this is being discussed in #1592, and an implementation is in progress in #1736.
