### ISSUE TITLE
Documentation of new renderer interface

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#1763]
https://github.com/jupyterlab/jupyterlab/issues/1709 introduces a new interface for renderers. I've browsed through this PR but I haven't been able to adapt the mimerender extensions to work with this new interface (if an incompatible extension is enabled, I see `Unable to render data` in all of the output areas). Can we document the breaking changes here or can someone submit a PR to https://github.com/jupyterlab/jupyterlab_json to demonstrate how to use the new interface?

**Comment by blink1073** [comment]
Sure, I can do both after we get #1762 done.

**Comment by blink1073** [comment]
cf https://github.com/jupyterlab/jupyterlab_json/pull/19

Summary of changes: 

- `mimetype` was changed `mimeType`
- Renderers always get a sanitizer, so we replace `isSanitizable` and `isSafe` with `canRender` with the richer [IRenderOptions](http://jupyterlab.github.io/jupyterlab/interfaces/_rendermime_rendermime_.rendermime.irenderoptions.html
- The `render` method takes that options object as well
- The `addRenderer` method signature has changed slightly to use [IRendererItem](http://jupyterlab.github.io/jupyterlab/interfaces/_rendermime_rendermime_.rendermime.irendereritem.html), which make it easier to add items in the constructor of `RenderMime`.

**Comment by blink1073** [comment]
Also note how much easier it is to create the default [rendermime](https://github.com/jupyterlab/jupyterlab/blob/ac78dd7998b9075dde0789eecd707820258ab65c/examples/console/src/index.ts#L82).

**Comment by gnestor** [comment]
@blink1073 Thanks so much! I got all of that except for the new `addRenderer` signature (which explains the `Unable to render data` error that I was seeing). Is there a way to specify a renderer's index anymore? Or is that no longer necessary?

**Comment by blink1073** [comment]
You can, it is the optional second argument:  https://github.com/jupyterlab/jupyterlab_json/pull/19/files#diff-49b07e579145aaeac1709d8ff398662cR29

**Comment by blink1073** [comment]
Closing as answered, please feel free to reopen if you disagree.
