### ISSUE TITLE
Use new `optional` plugin parameter

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1771]
Use it for at least: `menu`, `commandpalette`, and `launcher`.

**Comment by AbdealiJK** [comment]
What's the use case when `optional` would be used ?
Does this mean that jupyterlab will ignore if there was an error when loading that module ?

**Comment by blink1073** [comment]
It means if the plugin is not available, our plugin can still load.  If it is there, we can use it's services (for example, by adding an item to the main menu).
