### ISSUE TITLE
Switching kernels for console does not work

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#1792]
[Here](https://github.com/jupyterlab/jupyterlab/blob/master/src/console/plugin.ts#L415) `newName` should be used as a key, not `name`, which is a previous display name.

**Comment by akosyakov** [comment]
And [this line](https://github.com/jupyterlab/jupyterlab/blob/master/src/console/plugin.ts#L416) is apparently also bogus.

**Comment by blink1073** [comment]
Thanks for the heads up!
