### ISSUE TITLE
Modify rendered html/markdown table display

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1805]
Some really nice modifications of the HTML tables in this issue (and in notebook 5.0):

https://github.com/jupyter/notebook/issues/2209#issuecomment-282341408

We should port these over to lab.

**Comment by AbdealiJK** [comment]
Closed with https://github.com/jupyterlab/jupyterlab/pull/1885

**Comment by blink1073** [comment]
Thanks!
