### ISSUE TITLE
Create Console for Editor seems to be broken

### ISSUE THREAD

**Issue by danielballan** [jupyterlab/jupyterlab#1807]
Commands to reproduce:
1. File Operations > New Text File
2. Editor > Create Console for Editor

In debugging console:
```
main.bundle.js:104596 Uncaught (in promise) TypeError: Cannot read property 'activate' of null
    at execute (main.bundle.js:104596)
    at CommandRegistry.execute (main.bundle.js:2321)
    at CommandPalette._execute (main.bundle.js:12633)
    at CommandPalette._evtClick (main.bundle.js:12546)
    at CommandPalette.handleEvent (main.bundle.js:12427)
```

A breakpoint shows that `args` is `null` in [this line](https://github.com/jupyterlab/jupyterlab/blob/master/src/editorwidget/plugin.ts#L165).

I'll poke around and see if I can push a fix, but I'm posting this now so it can be fixed (or confirmed as some local problem of mine) before 0.17.0 is tagged.

**Comment by danielballan** [comment]
Seems likely it was broken three days ago in https://github.com/jupyterlab/jupyterlab/commit/e8d6ef334448643e187e2d560208a97ca751970d.

**Comment by danielballan** [comment]
I bet this is a duplicate of #1796.

**Comment by blink1073** [comment]
Yep, it is.  Thanks for spotting though!
