### ISSUE TITLE
Document auto-save

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#1809]
It would be nice:
- to provide a way to disable auto-saving
- to be notified about document save events with source/reason of saving

**Comment by blink1073** [comment]
Hi @akosyakov, the current behavior implements https://github.com/ipython/ipython/wiki/IPEP-15:-Autosaving-the-IPython-Notebook.  Disabling auto-saving will come when we implement https://github.com/jupyterlab/jupyterlab/issues/515.  Notifications are tracked in https://github.com/jupyterlab/jupyterlab/issues/689.  Let's keep this open as a specific use case for both.

**Comment by ian-r-rose** [comment]
I would also add that the semantics of auto-saving will be different for a collaborative notebook. Save events can be initiated from multiple sessions, so it is not a problem when there is a timing conflict. Ultimately a completely different `SaveHandler` is likely appropriate for that case.

**Comment by jasongrout** [comment]
Autosave is now an option in the settings. I'll add a comment to #689 about notification of save, and let's close this. Thanks!
