### ISSUE TITLE
Interrupting or Restarting the kernel should clear the pending execution asterisks

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1813]
cf https://github.com/jupyter/notebook/issues/2216.

**Comment by ellisonbg** [comment]
Might be related to work in #2540

**Comment by blink1073** [comment]
Looking at this again, I don't think we can clear the state for `interrupt`, because all we know is that we attempted to interrupt the process.  For `restarting`, the client side kernel explicitly sets its state to `restarting`, so if we add an `executing` property to the cell store in the notebook refactor, we can clear that from the notebook panel when we get the `restarting` state.

**Comment by Madhu94** [comment]
@blink1073 @ellisonbg I'll take this.

**Comment by blink1073** [comment]
Hi @Madhu94, note that we are refactoring the notebook models and views (cf #2540), and this is blocked on that work.

**Comment by Madhu94** [comment]
Oh-  Thanks for letting me know @blink1073
