### ISSUE TITLE
favicon path doesn't respect base_url argument?

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#1814]
I don't get a favicon with jupyterlab whereas I do with the notebook.  In my config I have `c.NotebookApp.base_url = '/Jupyter'`

In the logs I see the below errors:
```
[W 16:46:14.751 LabApp] 404 GET /static/base/images/favicon.ico (10.200.18.81) 0.00ms referer=http://server:8888/Jupyter/lab?
```
I can see the icon image if I manually navigate to `Jupyter/static/base/images/favicon.ico`

**Comment by blink1073** [comment]
Hi @dhirschfeld, this was fixed in https://github.com/jupyterlab/jupyterlab/pull/1803, which will be in the next release.
