### ISSUE TITLE
Support for RMarkdown / pystitch / knitpy?

### ISSUE THREAD

**Issue by grst** [jupyterlab/jupyterlab#1815]
I have been using jupyter since it was still called ipython notebook and use it almost on a daily basis. 

For a recent project I was forced to use R instead of python and tried out [RMarkdown](http://rmarkdown.rstudio.com/). This is a similar concept to jupyter notebooks, however the document is authored in plain markdown with 'code chunks' instead of using a json-based format. 

Although being sceptical at the beginning, by now I am convinced that this format is superior over the jupyter notebook format for the following reasons: 
* **version control**: since results are separated from code, it can be easliy handled through git
* **readability of the documents**: RMarkdown can be read and edited in text-only editors like vim
* **publication-ready output**: The chunks allow additional options, such as hiding code from the output, adding figure captions etc., which allows rendering high-quality reports. 

This is also being discussed [here](http://danielphadley.com/Jupyter-to-Rmarkdown/) and [here](https://www.reddit.com/r/rstats/comments/51tzcb/why_i_switched_from_jupyter_notebooks_to_r/). 

**I would love seeing this concept being integrated into jupyterlab, tying together a cleaner notebook format with the power of the jupyter.**

I am aware of two active github projects developing a command-line renderer for **Py**Markdown: 
* [stitch](https://github.com/pystitch/stitch)
* [knitpy](https://github.com/janschulz/knitpy)

Moreover, there is the [ipymd](https://github.com/rossant/ipymd) project working towards this direction, implementing a bridge between jupyter notebooks and Python Markdown.

**Comment by blink1073** [comment]
Hi @grst, I think this would be a great candidate for a third party extension.

**Comment by izahn** [comment]
See also https://github.com/aaren/notedown

**Comment by grst** [comment]
Thanks for the link! 
I found also https://github.com/rossant/ipymd.

**Comment by grst** [comment]
For the record:
I created a fork of ipymd which allows to edit R Notebook documents in jupyter: 
https://github.com/grst/ipymd

Haven't tried it with jupyterlab, but it works well in 'classical' jupyter notebooks.

**Comment by jasongrout** [comment]
See also #4924

**Comment by grst** [comment]
Closing this issue, as it is now essentially possible to author (Py)Markdown documents in jupyterlab: 
* opening text as notebooks is possible with extensions such as [jupytext](https://github.com/mwouts/jupytext)
* the 'attach kernel' function allows to open and edit (Py)Markdown natively in jupyterlab.
