### ISSUE TITLE
Downloading a folder

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1816]
I can right click on a folder and I can see the `download` option there. But when I click on it, nothing seems to happen.

Not sure what the intended behaviour is. I was expecting a zip file to be created which would be download

**Comment by blink1073** [comment]
Thanks for the report!

**Comment by AbdealiJK** [comment]
What's the expected behaviour ? Create a zip and download that ? Or this button should not be there for folders ?

**Comment by blink1073** [comment]
AFAIK there is no server support for generating a zip file, so the short term solution is to not show the option in the context menu.

**Comment by jtpio** [comment]
Wanted to look at this issue but it looks like the problem doesn't exist anymore (master branch):

Folder (no download option):

![image](https://user-images.githubusercontent.com/591645/36622541-0553057e-18fe-11e8-9a2f-6bfaf271c6a9.png)

File (download option):

![image](https://user-images.githubusercontent.com/591645/36622558-1ddbf880-18fe-11e8-88fe-7f7337563caa.png)

**Comment by akhmerov** [comment]
I think this issue has partially returned:

![image](https://user-images.githubusercontent.com/2069677/48201895-bacc0380-e363-11e8-8e25-0bd48328ff58.png)

The download link that the form suggests to copy isn't functioning for folders.

**Comment by ian-r-rose** [comment]
Thanks for the heads up @akhmerov! I am going to reopen this and mark it as a good first issue.

We should go to this context menu item : https://github.com/jupyterlab/jupyterlab/blob/b8b7b56550a6ba1365a48cf8a2465c6281bb0a7d/packages/filebrowser-extension/src/index.ts#L786
and change the selector to `selectorNotDir` so that it doesn't get added to the context menu when the user clicks on a directory.

**Comment by bobhilt** [comment]
Never mind on my commit--working with JohnJohnsonIII and got wires crossed.

**Comment by hadim** [comment]
FYI: I really would like to be able to download a folder directly from the interface without having to compress it first. I have opened an issue on the notebook repo: https://github.com/jupyter/notebook/issues/4781

**Comment by jasongrout** [comment]
> I have opened an issue on the notebook repo: [jupyter/notebook#4781](https://github.com/jupyter/notebook/issues/4781)

I think that's the right first step: implement it in the server, then implement it in jlab.

Alternatively, you could probably write an extension for jlab that included a server component to do the zipping, if you wanted to have this before the next notebook release.

**Comment by hadim** [comment]
Good idea. So I first create a JLab extension with the server component and then ask for integration in `jupyter/notebook` and JLab.

**Comment by jasongrout** [comment]
> then ask for integration

(or submit a PR :).

Creating an extension lets you have the feature immediately, even while PRs are being reviewed and before releases are done.
