### ISSUE TITLE
`id` for Headers in Markdown

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1817]
The `id` attribute for headers - h1, h2, h3, h4 ... does not get populated.

I wanted to make a link from one of my cells to another section of my notebook and it does not seem to work. I realized that JupyterLab does not populate the `id` of the header tags when creating the HTML from markdown.

Notebook does create the `id` of the header tags

**Comment by ian-r-rose** [comment]
Thanks for the report, @AbdealiJK. This issue is currently being tracked in #1592, with an implementation in progress in #1736.

**Comment by AbdealiJK** [comment]
Woops. Sorry. Closing this then
