### ISSUE TITLE
IPython Javascript display class assumes JQuery

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#1818]
The `IPython.core.display.Javascript` repr class assumes that jQuery is loaded for loading external libraries. I know we have been working hard to not require jQuery, but this also seems like a feature parity issue to me.

**Comment by ellisonbg** [comment]
...crazy idea... I have been thinking about us removing JavaScript output entirely in JupyterLab...

@rgbkrk 

With our new MIME based output approach, getting rid of user JavaScript would simplify certain things...

**Comment by rgbkrk** [comment]
How does the `JavaScript` repr class assume jQuery? The way people use output tends to involve assumptions about the frontend, yet there is no JS manipulation in the `IPython.core.display.JavaScript` class.

What I do see though is something we should remove from the documentation:

```
In the Notebook, the containing element will be available as `element`,
and jQuery will be available.  Content appended to `element` will be
visible in the output area.
```

Making `element` available is a good thing, which we can document in `jupyter_client` as a standard for that mimetype.

**Comment by rgbkrk** [comment]
Oh wait, I see it... https://github.com/ipython/ipython/blob/d8d81d99d1c2b849c4cbcb33ad946c40bf15c171/IPython/core/display.py#L672-L682

```python
css_t = """$("head").append($("<link/>").attr({
  rel:  "stylesheet",
  type: "text/css",
  href: "%s"
}));
"""

lib_t1 = """$.getScript("%s", function () {
"""
lib_t2 = """});
"""
```

**Comment by rgbkrk** [comment]
The CSS code is easy enough to add in without jQuery based on our currently supported browsers:

```js
var link = document.createElement('link');
link.rel = "stylesheet"; link.type = "text/css";
link.href = "wherever.css"; // Where the string replacement would happen
document.querySelector('head').appendChild(link);
```

Fetching a script and including it can be done several different ways.

------------------------

However, these are not friendly to usage inside of Atom or Visual Studio Code. Additionally, it would be best for outputs themselves to not expect to have a global context on a page -- including if they were ever in null origin iframes.

/cc @craigcitro

**Comment by blink1073** [comment]
I agree, if a specific library is needed by an output, it should be provided as part of a mime renderer.

**Comment by craigcitro** [comment]
+1 on dropping "jQuery is available for user JS" as a documented requirement. @peteblois would be happy to see that happen (and may have more thoughts?).

@ellisonbg I'm obviously mostly out of the loop -- but what's the "new MIME-based output approach"?

**Comment by jasongrout** [comment]
@craigcitro - good to see you! I think @ellisonbg is referring to our renewed emphasis on using mimetypes in display_data messages to convey enough data to render output client-side, and providing a mechanism for extending the output renderer on the client side with custom renderers understanding these mimetypes.

For example, to render ipywidgets in jupyterlab, we now send a display_data output message with a special mimetype with the widget data. On the client side, we install an extension to the output rendering framework that understands this mimetype and takes responsibility for rendering these messages.

**Comment by ian-r-rose** [comment]
I also agree with what seems to be the consensus here. At the very least, IPython should not assume any libraries on the client side (and this issue may be more appropriate on that repo). Not sure what should be done in the short-term though.

**Comment by peteblois** [comment]
If I'm understanding it correctly, the intention is to migrate to display_data being being raw data which is interpreted by a client-side extension?

If so, I'm curious how something like [nbviewer](https://nbviewer.jupyter.org/) would work.

**Comment by jasongrout** [comment]
A few possibilities: (a) have nbviewer have a set of rendering extensions installed, (b) display_data types have a backup rendered html version, (c) have a renderer render and insert backup rendering in html.

**Comment by asford** [comment]
Blast from the past, but with the release of #4515 in 0.33 (which was *great*) this issue is going to become slightly more pressing. Jupyterlab, at the moment, is unable to support many custom javascript display components that rely on the documented behavior of `IPython.display.Javascript`.

@gnestor Would you be open to a patch to the javascript extension that makes JQuery available in the javascript display context?

**Comment by jasongrout** [comment]
I am currently against distributing jQuery in core jupyterlab.

**Comment by asford** [comment]
I'm context-free here, as I'm coming from outside the project. Would you mind elaborating on why you're opposed and/or off-linking me to any relevant discussion?

**Comment by asford** [comment]
@gnestor The use case you mention (`lib` & `css` argument support) is the most relevant component for my use case, though I do agree that it _seems_ that many uses combine jquery with downstream manipulation of the (legacy) notebook object model.

A few possible options:

1. Add jQuery to the javascript extension component, enabling use of the jQuery in user-provided Javascript and fixing the current `lib` & `css` args in `IPython.display.Javascript`, which currently depend on jQuery. (This has opposition from, at least, @jasongrout.)

https://github.com/ipython/ipython/blob/a086805d6d556188089fb0580d2fc698ec5c77ab/IPython/core/display.py#L855-L865

2. Shim a subset of the jQuery api in the extension, enabling the current `lib` & `css` implementations in `IPython.display.Javascript` but not including the full jQuery library. (This seems *very fragile*.)

3. Update `IPython.display.Javascript` to enable these api components without depending on jQuery and update the documentation to explicitly state what elements are available in both classic & jupyterlab notebooks.

4. Explicitly drop support for `css` & `lib` from `IPython.display.Javascript` in Jupyterlab. Ideally, this would involve a documentation update to describe the supported api subset and a some from of warning.

**Comment by gnestor** [comment]
@Carreau @takluyver What are your thoughts about supporting the `lib` and `css` arguments of `IPython.display.Javascript` in lab? 

Currently, `Javascript` will inject the following code when a `lib` argument is provided:

```js
$.getScript("OUR_JS_URL", function () {
    OUR_JAVASCRIPT_CODE
});

And this when a `css` argument is provided:

```js
$("head").append($("<link/>").attr({ rel:  "stylesheet", type: "text/css", href: "OUR_CSS_URL" }));
OUR_JAVASCRIPT_CODE
```

We could provide jquery in the context that `@jupyterlab/javascript-extension` evaluates JS, or we could provide a `$` function that only adds JS/CSS to the page, or we can update `IPython.display.Javascript` to not rely on jquery.

**Comment by rgbkrk** [comment]
Updating `IPython.display.Javascript` to not rely on jQuery (using modern DOM APIs instead) would be the best course of action.

**Comment by Carreau** [comment]
> Updating IPython.display.Javascript to not rely on jQuery (using modern DOM APIs instead) would be the best course of action.

Agreed.

**Comment by rgbkrk** [comment]
Code for adding in the CSS:

```js
var link = document.createElement('link');
link.rel = "stylesheet"; link.type = "text/css";
link.href = "wherever.css";
document.querySelector('head').appendChild(link);
```

**Comment by gnestor** [comment]
Thanks @rgbkrk! This is how I've been adding external js and css in JupyterLab using `@jupyterlab/javascript-extension`:

```py
# To add a js script
%%javascript
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = '//cdnjs.cloudflare.com/ajax/libs/d3/4.13.0/d3.js';
    document.head.appendChild(script);

# To add css
%%javascript
    # To add css
%%javascript
    var link = document.createElement('link');
    link.ref = 'stylesheet';
    link.type = 'text/css';
    link.href = 'whatever.css';
    document.head.appendChild(link);
```


I'll submit a PR to ipython soon!

**Comment by asford** [comment]
This might be betraying my ignorance of dom manipulation semantics, but doesn't that code snippet introduce a race condition between execution of the loaded script and the rest of the javascript body? 

For example:

```javascript
var script = document.createElement('script');
script.type = 'text/javascript';
script.src = '//cdnjs.cloudflare.com/ajax/libs/d3/4.13.0/d3.js';
script.onload = script.onreadystatechange = function( _, isAbort ) { console.log("onload") }

console.log("append")
document.head.appendChild(script);
console.log("d3: ", d3)
console.log("post_append")
```

**Comment by blois** [comment]
@asford- in your example the inline code will always be executed before the loaded script since they are in the same script block.

In Google Colaboratory we try to maintain the HTML script execution order when displaying HTML and block execution of subsequent scripts until previous ones have loaded. 

The goal there is to support code such as:
```
%%html
  <script src="/static/components/requirejs/require.js"></script>
  <script>
    requirejs.config({
      paths: {
        base: '/static/base',
        plotly: 'https://cdn.plot.ly/plotly-1.5.1.min.js?noext',
      },
    });
  </script>
```

I put together an basic example in https://colab.research.google.com/gist/blois/90f000e49015c1bdf1ecd9b202f3678d/script_execution.ipynb

This is basically built on top of a mechanism that allows pausing the display of outputs until a Javascript Promise has been resolved: https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb#scrollTo=7EDBBkAz2USP

**Comment by asford** [comment]
@blois Yes, so the script load code generated in `iPython.core.display` likely needs to include a minimal re-implementation of the async callback behavior of `$.getScript` to preserve javascript semantics across the various front-ends?

**Comment by gnestor** [comment]
I just submitted a PR that drops ipython's dependency on jquery and should resolve this async loading issue by injecting the `data` argument into the body of the `script.onload` callback.
