### ISSUE TITLE
Investigate Lerna for subpackage management

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1819]
I think the `--independent` option would suit our workflow well.

https://lernajs.io/ .

Thanks to @akosyakov for the suggestion.

**Comment by gnestor** [comment]
@rgbkrk and nteract team have been doing a lot of lerna lately...

**Comment by rgbkrk** [comment]
Independent mode is good, I'm really happy with it now that I understand it.

**Comment by sccolbert** [comment]
Last I looked at Lerna, it didn't have independent mode. This could be good :)

**Comment by blink1073** [comment]
Looking good so far, cf https://github.com/phosphorjs/phosphor/issues/213

**Comment by blink1073** [comment]
Update: this is definitely the path forward.  Thanks again, @akosyakov!

cf https://github.com/phosphorjs/phosphor/pull/216

**Comment by blink1073** [comment]
Closing, since #1773 is tracking the migration.
