### ISSUE TITLE
Provide a syntax highlight service

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#1820]
Follow up from https://github.com/jupyterlab/jupyterlab_json/issues/20#issuecomment-283180179

I would like to offer syntax highlighting in an extension (when rendering errors) but jupyterlab doesn't currently provide a syntax highlight service although CodeMirror provides this feature as seen [here](https://github.com/jupyterlab/jupyterlab/blob/4564240df87748225dc4149bed3974bc43363adb/src/renderers/widget.ts#L118-L119). I was thinking that jupyterlab could expose this as `codemirror/highlight` or to renderers via render options as @blink1073 suggested.

**Comment by ellisonbg** [comment]
I think this type of thing could be in a general language extensions API that allow a registry of programming language extensions that would include things like syntax highlighting, completion logic, etc.

**Comment by blink1073** [comment]
Yep, cf https://github.com/jupyterlab/jupyterlab/issues/1504.
