### ISSUE TITLE
Save timestamp when cell was run in notebook

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1826]
It would be useful to save the timestamp a cell was run within a notebook in the metadata.
This could be shown when a user hovers on the left `In[1]` text or maybe below it.

When "Clear output" is used, this should also be cleared.

Sometimes when running big data tasks, it is useful to identify the time when a cell was run. If we can do both: When a cell was run, and when the cell finished running it would be awesome as it would help in basic profiling too.

Possibly this should be an external plugin and not in Jupyterlab code base ?

**Comment by blink1073** [comment]
I think it would be fair to add something like this to master.

**Comment by moble** [comment]
I think this is the same idea that is discussed more fully in #3320.

**Comment by jasongrout** [comment]
Let's move this discussion to #3320, which at this point has a lot more discussion on the topic.
