### ISSUE TITLE
Bug in 0.17: Markdown cells collapsing 

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1827]
I just upgraded to 0.17 today and found that there seems to be an issue in the Markdown cell.

When I:
 - Double click a markdown cell for editing
 - Run a markdown cell with Shift+Enter to render the HTML

I've found that the markdown cell collapses and there is no input area nor output area:
<img width="905" alt="screen shot 2017-03-02 at 7 22 59 pm" src="https://cloud.githubusercontent.com/assets/2200743/23511453/1b537f92-ff83-11e6-924f-351eb34f5035.png">

I checked the HTML code for some hint and found that there was no code mirror div and no renderedHTML div:
<img width="725" alt="screen shot 2017-03-02 at 7 23 19 pm" src="https://cloud.githubusercontent.com/assets/2200743/23511469/25d3ca1c-ff83-11e6-9935-a06343a3d2a3.png">

It doesn't happen all the time, but happens frequently - Happened about 10 times when I performed those actions about 50 times over 60 minutes of editing maybe.

Using: Chrome (latest) + Mac OS Sierra

**Comment by blink1073** [comment]
Confirmed, thanks for the heads up!

**Comment by blink1073** [comment]
This was most likely introduced by https://github.com/jupyterlab/jupyterlab/pull/1789/commits/24b8962428a067680617567799dd5e8ad7d6b25f.

**Comment by blink1073** [comment]
Released as JupyterLab 0.17.1.
