### ISSUE TITLE
Multiple cursor + undo

### ISSUE THREAD

**Issue by albop** [jupyterlab/jupyterlab#1828]
I was positively surprised to see multiple cursor support in the notebook cells. However, if you edit text at different places, then undo the modifications, the cell seems to be left in a wrong state which does not correspond to what is on screen.

Example: type in a python cell
```
a = 12
b = 12
```
then press ctrl and click immediately before each equal sign. Hit delete to remove both equal signs, then ctrl+z to cancel the edit. On screen, the cell is now exactly as before. Now executing it produces:

```
true
``` 

but it's clearly untrue, right ?

**Comment by ian-r-rose** [comment]
Hi @albop, thanks for the report. This is indeed a bug, which was fixed by #1791. If you update to master you should get the expected result.

**Comment by blink1073** [comment]
Closing as fixed in the lasted release (0.17).  Please feel free to reopen if you still see it after upgrading.
