### ISSUE TITLE
\( in code block breaks markdown syntax highlighting

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1834]
I was typing something in Markdown and happened to type `\(` in the code block. This breaks the syntax highlighting in the markdown cell.

Without `\(`:
<img width="104" alt="screen shot 2017-03-03 at 5 17 51 pm" src="https://cloud.githubusercontent.com/assets/2200743/23550120/74d94ea4-0035-11e7-8473-1aac7186df22.png">

With `\(`:
<img width="105" alt="screen shot 2017-03-03 at 5 17 59 pm" src="https://cloud.githubusercontent.com/assets/2200743/23550121/74dc29a8-0035-11e7-8474-473deae7735f.png">

This happens if I use the triple backtick code block (From GFM) or the indented code block from most markdown implementations.

**Comment by blink1073** [comment]
There is discussion about how to handle this, let's see how this plays out: https://github.com/jupyter/notebook/pull/2220.
