### ISSUE TITLE
Can't start kernel after stopping it

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1835]
Steps to reproduce:
 - Open a notebook ensure the kernel is running
 - Right click on the file in file manager and select on "Shutdown Kernel"
 - Check that the kernel has died and it says "No Kernel!"

What Happens:
 - The restart kernel option does nothing

Expectation:
 - The restart kernel option should start this kernel again

Currently, the ways to start a kernel again after this is:
 - Do a "switch kernel" and select the kernel you want
 - Close the tab of the notebook and open the notebook again

**Comment by blink1073** [comment]
Ha, that seems rather rude on our part ;).

**Comment by AbdealiJK** [comment]
Seems like this is blocked by https://github.com/jupyterlab/jupyterlab/issues/1856

**Comment by blink1073** [comment]
Yep.
