### ISSUE TITLE
Screencast for beta release

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#1842]
@willingc suggested we do a couple of screencasts when we release the demo. We could do the standard demo that we've been giving (or break that up into several parts).

**Comment by blink1073** [comment]
Note: this should wait until the launcher refactor.

**Comment by ddavidebor** [comment]
I've really loved this one https://channel9.msdn.com/Events/PyData/Seattle2017/BRK11

**Comment by jasongrout** [comment]
@jzf2101 - if you want to take a shot at coming up with a script or if you want to take this on, that would be awesome.

**Comment by jzf2101** [comment]
Let me start putting together markdown in the demo as user-directed notes and we can use that to start a script.

**Comment by ellisonbg** [comment]
The user guide that I am working on in #3534 will have *many* screencasts mixed in with narrative text. Creating those will take a lot of work, not sure we want to do a separate screencast as well. Are folks ok with me closing this one in favor of the ongoing work on the documentation? After my initial PR is in, our plan is to split up the work in creating the many short screencasts - we will create issues for that process when we get there.
