### ISSUE TITLE
Mac OS hot key switches tabs 

### ISSUE THREAD

**Issue by bestxolodec** [jupyterlab/jupyterlab#1845]
In Mac OS it is usual and very common among standard and various non standard applications to use 
`CMD + left_arrow`  as a hotkey to move cursor to the beginning of the line. 
However in recent versions of jupyter lab (unlike the more old ones) this combination switches between open tabs. This is _very_ annoying and distracting. And this is the only issue which makes me still use old classic jupyter interface, keeping jupyter lab open for a purpose of a file manager.
Could you please tell me how to switch off this key binding? Is it possible? 
It would be really awesome to stay with this default, habitual and very useful key binding in Mac OS unchanged.

**Comment by blink1073** [comment]
Hi @bestxolodec, we are tracking this in #1681.
