### ISSUE TITLE
Close tabs with middle button click

### ISSUE THREAD

**Issue by ddavidebor** [jupyterlab/jupyterlab#1851]
On Chrome, atom and I suppose other apps a middle button mouse click closes the tab.

It would be a nice addition to Jupyterlab too.

**Comment by sccolbert** [comment]
If there is consensus on this, the right place to add it would be to the Phosphor `TabBar` class to emit the `tabCloseRequested` on middle-click in addition to clicking on the close icon.

**Comment by blink1073** [comment]
Seems reasonable to me if it is the cross platform behavior of the host environment.

**Comment by sccolbert** [comment]
Confirmed on IE, Edge, Chrome and Sublime on Windows. I'll add this to Phosphor real quick.

**Comment by sccolbert** [comment]
Fixed in https://github.com/phosphorjs/phosphor/pull/221
