### ISSUE TITLE
Completer Style: hover vs keyboard selection

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1858]
<img width="333" alt="screen shot 2017-03-06 at 19 13 19" src="https://cloud.githubusercontent.com/assets/335567/23640217/102943ec-02a1-11e7-9913-f8d0b23c128b.png">

When typing the completer hite the cursor, though still styles things on `:hover`,  the `:hovered`  and keyboard-selected completion have the same style, which looked like a bug (until I realized it was the hidden cursor). 

in above screenshot `r.issuperset` is hovered by (invisible) cursor `instersection_update`, is keyboard selected.

**Comment by ellisonbg** [comment]
This is still relevant - saw it today :)

**Comment by akhmerov** [comment]
I believe this issue is closed by the completer restyling in v0.31

**Comment by ian-r-rose** [comment]
Confirmed, thanks.
