### ISSUE TITLE
output does not handle `\r`

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#1860]
The following snippet:

```
import time
for i in range(10):
    time.sleep(0.1)
    print('\r',i, end='')
```

Should appear as an increasing counter as `\r` erase current line.
It is used in many tools to display progress bar, and currently handled by classic notebook. 

Jlab seem to not support it leading to long lines of input.

**Comment by blink1073** [comment]
Thanks, this is tracked in https://github.com/jupyterlab/jupyterlab/issues/1104.

**Comment by Carreau** [comment]
Ah, thanks, sorry I did not found it by searching. I had the occasion to
work a bit in the notebook, which I didn't had in a long time. I hope to
have more time to redo this soon, and fill in more improvement requests.

Thanks.
