### ISSUE TITLE
Tab key in completer should insert whitespace

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#1865]
Behavior in JupyterLab:

<img width="350" alt="screen shot 2017-03-07 at 7 03 54 am" src="https://cloud.githubusercontent.com/assets/2096628/23664682/d5951af0-031b-11e7-9655-0870903eed52.png">

Behavior in Notebook:

<img width="405" alt="screen shot 2017-03-07 at 9 53 47 am" src="https://cloud.githubusercontent.com/assets/2096628/23664724/fbde096a-031b-11e7-9a27-d7a7e78c4f2c.png">

**Comment by jasongrout** [comment]
Changing to beta since this makes working with any code that needs indentation very frustrating...

**Comment by blink1073** [comment]
I am not seeing this behavior in master, closing.
