### ISSUE TITLE
Fault tolerance against mime renderers throwing errors

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#1866]
In my migration of the ipywidgets renderer, my renderer `canRender` function threw an error. That stopped the rendering of the entire notebook at that point, which then looks like it has been truncated at the cell causing the render. At first I thought it was some serious data loss, but the console revealed the renderer error.

I think we should be more fault-tolerant of errors in the rendering plugins. We could put the rendering loop in a try/except block, display an error message in the page (not just in the console) that a renderer was throwing an error, and then move on to processing the next output.

**Comment by AbdealiJK** [comment]
Not sure whether the error should be displayed in the page. For example, if the html mimetype is broken, the text mimetype would be the fallback mime for this. Which is an acceptable render - correct ?
