### ISSUE TITLE
Expose some of jupyterlab components

### ISSUE THREAD

**Issue by CoaPsyFactor** [jupyterlab/jupyterlab#1877]
It would be nice to have some of jupyterlab components exposed, for example Context menu for filebrowser or commands disposers for menubar, and things like those.

I would love to have ability to use Jupyterlab and just remove/add items I do or I don't need, e.g ability to remove button "Duplicate" from file browser context menu.

**Comment by blink1073** [comment]
Hi @CoaPsyFactor, I think the best we could do here is make the file browser context menu content itself a plugin.

**Comment by sccolbert** [comment]
The general philosophy of the JupyterLab architecture is that plugins contribute content to the application, they don't remove content contributed by other plugins. If you don't like the content provided by one plugin, you simply don't include that plugin in the application.

Steve's suggestion would allow the file browser context menu to be populated by plugins, and you could remove the plugin you don't like from the application.

However, I think the general solution to context menus will come in the form of:
https://github.com/phosphorjs/phosphor/issues/139

**Comment by CoaPsyFactor** [comment]
Thanks for response people 👍
