### ISSUE TITLE
Command Palette should only show commands that can be executed right now

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1893]
When I am focused on a Notebook, it is very confusing that the command palette shows me "Restart Kernel", "Switch Kernel", and "Interrupt Kernel" for both Console as well as notebook.

Many times I've spent time clicking the "Switch Kernel" for Console (because it appears above Notebook) and wondering what's wrong.

It should be either hidden or greyed out.

**Comment by AbdealiJK** [comment]
More examples:
 - The command pallete has "Markdown header" when I'm in a code cell
 - Merge selected cells should not be shown if only 1 cell is selected
 - Paste should be disabled when nothing has been copied
 - Editor commands are only applicable when an editor is open

**Comment by blink1073** [comment]
This is a tricky one to get right.  Our concept of a `current` widget of a given type is the last one that had focus.  If you are currently on a notebook, and then click on the command palette, that notebook no longer has focus, but we still want commands to act on it.  I think the right answer here is to add an `isVisible` to the commands and tie it to whether `shell.currentWidget` is one that we care about.  We can also use `isEnabled` more judiciously to show that an action exists but it not currently valid (like "Markdown header").  Disabled commands show up in the command palette but are grayed out and prioritized last in the fuzzy search algorithm.

**Comment by jasongrout** [comment]
The situation is much better now:

1. Console commands are now disabled when in a notebook
2. There is no "Markdown header" command
3. "Merge selected cells" is consistent with other "selected cells" commands - it works across all selected cells, including just one.
4. Editor commands are disabled when in a notebook

It looks like the only one left from your list is "Paste should be disabled when nothing has been copied".

**Comment by tgeorgeux** [comment]
As this conversation has dropped off, I'm going to close this in favor of #7039 where we are exploring a new experience entirely.
