### ISSUE TITLE
Undo/redo cell operations are buggy.

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#1895]
Undo/redo for cell serializes them at the time of undo/redo. If there are some intervening edits to the cell content, these can be lost, as shown here:
![output](https://cloud.githubusercontent.com/assets/5728311/23814713/63e410a2-0599-11e7-8527-a6ff59442673.gif)
This is straightforward effect of the specific implementation of the undo stack, but surprised me today.

A notebook implementation using the "cell uuid + vector of uuid ordering" can allow alternative implementation of cell undo/redo. In this case the undo stack just keeps track of uuids, and cell content is only cleared when a cell uuid is cleared from the stack.

**Comment by blink1073** [comment]
I think the real problem here is that our undo is confusing.  We need a unified history of the document that we can step through.   What if we switch to the classic notebook behavior of having an "undelete" stack instead of undo/redo in the interim?

**Comment by ian-r-rose** [comment]
"Undelete" would certainly be simpler in the short term. I agree that a unified history is probably best in the long term.

**Comment by ian-r-rose** [comment]
Renaming this issue as I am seeing some other problems with undo/redo.

**Comment by ian-r-rose** [comment]
If a cell is deleted, and it is the last cell in the notebook, this cannot be undone. This is because a new cell is automatically inserted, which always becomes first on the undo stack.
![lost-cell](https://cloud.githubusercontent.com/assets/5728311/23868558/1689dfbc-07dd-11e7-9f91-c4cffce5a23f.gif)

**Comment by ian-r-rose** [comment]
Moving cells within a notebook via a drag-drop operation does not work as expected. Dragging and dropping is represented as a remove operation, plus an insert operation. Undoing that only undos half of the operation:
![move-cell](https://cloud.githubusercontent.com/assets/5728311/23868647/6edcaf0a-07dd-11e7-853f-d2f4befc2d2c.gif)

(please excuse the lousy gifs -- my screencapturing software is not doing a great job).

**Comment by blink1073** [comment]
Yeah, yeah, my code is bad and I should feel bad... :smile:

**Comment by ian-r-rose** [comment]
:smile:

**Comment by ian-r-rose** [comment]
On the third point, this behavior occurs even if the drag operation does not move the cell anywhere (that is, if it stays in place).

**Comment by ian-r-rose** [comment]
The second two points are fixed by #1911 and #1913. The first has one potential solution in #1908.

**Comment by blink1073** [comment]
Fixed by #1911, #1913, and #1908.  Thanks!

**Comment by ian-r-rose** [comment]
:tada:
