### ISSUE TITLE
Switching a browser tab disables edit-mode

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1897]
I'm using jupyterlab and typing some stuff in a cell (so, it's green). Now, when I quickly go to another tab to check wikipedia or open a word doc to refer something and come back, the cell has become blue (active, but not editable).

In Jupyter Notebook, the cell remains green if I come back to the tab - which makes it easier to refer to another window/tab and write something from there.

FeatureParity and Beta?

**Comment by blink1073** [comment]
This should be fixed in master, are you using a released version?

**Comment by blink1073** [comment]
cf https://github.com/jupyterlab/jupyterlab/pull/1850

**Comment by AbdealiJK** [comment]
Yep - was using 0.17.4 - sorry for the noise
