### ISSUE TITLE
Tab at beginning of line opens autocomplete

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1900]
When I press a tab at the beginning of a line in a cell, it opens the autocomplete dropdown. In Jupyter notebook, it used to indent with 4 spaces.

In Jupyter Notebook if there is no text to the left side (only whitespace) it indents the line rather than opening the autocomplete dropdown.

I'm using current master 7ec5eced4328aa8a284c7357485c09994936767d

**Comment by AbdealiJK** [comment]
This works in current master - https://github.com/jupyterlab/jupyterlab/commit/8b3f4c3d8edb519d02758264bf03f2eff5ff9145 ... no idea which commit fixed it.

**Comment by AbdealiJK** [comment]
Seems like I was mistaken :\ still happens.

**Comment by blink1073** [comment]
Fixed by #1985.

**Comment by ssanderson** [comment]
I'm seeing this behavior on jupyterlab 0.27.  Seems like it may have been re-introduced?

My current environment, in case it's helpful:
```bash
$ pip freeze | grep jupyter
jupyter-client==5.1.0
jupyter-console==5.1.0
jupyter-contrib-core==0.3.1
jupyter-contrib-nbextensions==0.2.8
jupyter-core==4.3.0
jupyter-highlight-selected-word==0.0.11
jupyter-latex-envs==1.3.8.4
jupyterlab==0.27.0
jupyterlab-launcher==0.4.2
```

**Comment by aldanor** [comment]
Seems like it was reintroduced somewhere? Pressing tab 4 times at the beginning of a line containing `a` results in `%%!%%!a`.
