### ISSUE TITLE
Clicking on cell after focusing on Command Palette does not work

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1902]
**Steps to Reproduce**:
After using the command palette, I tried clicking on a cell to make it active (clicked the `In[]` area, not the editor) and tried deleting a cell using keyboard shortcuts (`dd`)

**Expected**:
The cell would be deleted

**Actual**:
The command palette's search got the text "dd"

Here's a demo:
![untitled2](https://cloud.githubusercontent.com/assets/2200743/23838898/18e7156c-07c0-11e7-8300-eadb04a704e3.gif)

**Comment by jasongrout** [comment]
Thanks. I also notice that in your screencast, the tab didn't get highlighted, indicating the notebook was never activated.
