### ISSUE TITLE
Wrong output size for retina matplotlib plots

### ISSUE THREAD

**Issue by himbeles** [jupyterlab/jupyterlab#1903]
The figure_format='retina' attribute for the inline backend does not produce the desired output. 
The plot has twice the resolution, but also twice the output size. 

Code to reproduce the issue:
```
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format='retina'
plt.plot([1,2])
```

**Comment by jasongrout** [comment]
Thanks for reporting this. It looks like we are ignoring the image size metadata sent in the message `content.metadata` dict.

**Comment by jasongrout** [comment]
(We should insert code at https://github.com/jupyterlab/jupyterlab/blob/6f407d08cfa4b616710704cd744938ac48be959f/src/renderers/widget.ts#L269 to check for size information in the `content.metadata` field)
