### ISSUE TITLE
Renaming iPython notebook results in it being deleted!

### ISSUE THREAD

**Issue by burkesquires** [jupyterlab/jupyterlab#1905]
Hello,
I renamed a notebook file to simply make the first letter lowercase and the notebook was deleted. Please see the terminal output below...

[ squiresrb L01891689  ~ ]$ jupyter lab
[I 09:35:47.632 LabApp] JupyterLab alpha preview extension loaded from /Users/squiresrb/anaconda/lib/python3.6/site-packages/jupyterlab
[I 09:35:47.644 LabApp] Serving notebooks from local directory: /Users/squiresrb
[I 09:35:47.644 LabApp] 0 active kernels 
[I 09:35:47.644 LabApp] The Jupyter Notebook is running at: http://localhost:8888/?token=7c82b8d47ead5de91379c1db9416bac51ecb21286c939ec1
[I 09:35:47.644 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:35:47.650 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=7c82b8d47ead5de91379c1db9416bac51ecb21286c939ec1
[I 09:35:48.038 LabApp] Accepting one-time-token-authenticated connection from ::1
[W 09:37:01.542 LabApp] File already exists: Documents/BCBB/Seminars/2017/python_biologists/06_bioinfo_python/bioinformatics_python.ipynb
[W 09:37:01.543 LabApp] 409 PATCH /api/contents/Documents/BCBB/Seminars/2017/python_biologists/06_bioinfo_python/Bioinformatics_python.ipynb?1489412221537 (::1) 2.35ms referer=http://localhost:8888/lab
[W 09:37:03.865 LabApp] delete /Documents/BCBB/Seminars/2017/python_biologists/06_bioinfo_python/bioinformatics_python.ipynb
[W 09:37:03.880 LabApp] Unknown error renaming file: Documents/BCBB/Seminars/2017/python_biologists/06_bioinfo_python/Bioinformatics_python.ipynb [Errno 2] No such file or directory: '/Users/squiresrb/Documents/BCBB/Seminars/2017/python_biologists/06_bioinfo_python/Bioinformatics_python.ipynb'
[E 09:37:03.881 LabApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "X-Xsrftoken": "2|d05d67bb|96de4192323912f4225bd149a3c2b534|1489412148",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-us",
      "Content-Type": "application/json",
      "Origin": "http://localhost:8888",
      "Content-Length": "103",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8",
      "Referer": "http://localhost:8888/lab",
      "Dnt": "1",
      "Connection": "keep-alive",
      "Cookie": "_xsrf=2|d05d67bb|96de4192323912f4225bd149a3c2b534|1489412148; username-localhost-8888=\"2|1:0|10:1489412148|23:username-localhost-8888|44:ODY0MjRkNDc4YThjNGRmMDliNmU0NTQ0ZThiYWJjMWQ=|bd9751225c6a8f4fdcafa46a6eac11f8f1d49a916523408e971e5d686246f571\"; username-localhost-8889=\"2|1:0|10:1488989626|23:username-localhost-8889|44:Yzk4ZmQ0NDQyYjcxNGE3NmE3NzQ4YzNmNDQzZTVjNzY=|a624ba02fc9a44bbb64647507a5a1ea3c033aaff3848680ae11e9dffb5803218\"; username-localhost-8890=\"2|1:0|10:1488917678|23:username-localhost-8890|44:MTIyYjUxODJmZmRiNGNkZGFkMzFjNTgxZTZlYWI5ZDU=|0347266ddb590e2e8d97e2d7ba704e6fe40c5462005f56f791c81e8ee9ff0ef5\"; username-localhost-8891=\"2|1:0|10:1488923016|23:username-localhost-8891|44:ODI2ZjQ3MmExOGIxNDMwZDg1YmE2NmM1ODIwNjFiM2I=|2638578e56269f9296ce26a9bb378119492b2a197ec3231d5746ef6d5fc9842e\""
    }
[E 09:37:03.881 LabApp] 500 PATCH /api/contents/Documents/BCBB/Seminars/2017/python_biologists/06_bioinfo_python/Bioinformatics_python.ipynb?1489412223876 (::1) 1.39ms referer=http://localhost:8888/lab

**Comment by blink1073** [comment]
Oh no!  Thank you for catching that, I hope you did not lose any data.

**Comment by burkesquires** [comment]
Thanks Steven...how nice to be asked but no it was a copy...but it is a lot scary...unless I did something wrong but I do not think so. I have been using JupyterLab for a while without issues.

**Comment by blink1073** [comment]
Thanks @burkesquires, @afshin was able to reproduce because his file system is case insensitive.  We have a fix in mind and will be making a patch release to 0.17 today.

**Comment by blink1073** [comment]
This [logic](https://github.com/jupyterlab/jupyterlab/blob/6f407d08cfa4b616710704cd744938ac48be959f/src/filebrowser/dialogs.ts#L121) needs to be updated to: create a temp file, delete the target file with fault tolerance, and rename the temp file to the target path.

**Comment by burkesquires** [comment]
Wow...that is great! Thanks!

**Comment by blink1073** [comment]
Released as 0.17.5.
