### ISSUE TITLE
display.max_colwidth option does not appear to work

### ISSUE THREAD

**Issue by palewire** [jupyterlab/jupyterlab#1910]
See screenshot. My second column is still truncated.

![screenshot from 2017-03-13 14-50-21](https://cloud.githubusercontent.com/assets/9993/23876806/648d0878-07fc-11e7-8d59-e480401fd641.png)

**Comment by blink1073** [comment]
Hi @palewire, https://github.com/jupyterlab/jupyterlab/pull/1885 fixed this, but we have not yet made a release for it.

**Comment by palewire** [comment]
Glad to hear!
