### ISSUE TITLE
Minor UI/UX design process changes

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#1938]
There are a number of design/style regressions in master. When I went to look through recent merged PRs to understand the background and origin of the changes, it was extremely difficult to find anything. Based on this, I would like to propose the following changes:

* Any PR that changes visual design is tagged with the UI/UX Design label.
* Myself (@ellisonbg) and Cameron (@cameronoelsen) are @mentioned on the PR so we have an opportunity to review.
* Any PR with visual design changes are accompanied by before and after screenshots so reviewer can see the changes without a local build.

@jasongrout @sccolbert @blink1073 @afshin @AbdealiJK 

If Cameron and/or myself are unable to review design changes promptly, I am fine with things moving forward without our review. But being @mentioned and using the label will help us when we get back and catch up with things.

**Comment by blink1073** [comment]
Sounds fair.

**Comment by blink1073** [comment]
This PR consolidated button/input/select styling: https://github.com/jupyterlab/jupyterlab/pull/1862.
This PR consolidated and cleaned up the SVG and icons: https://github.com/jupyterlab/jupyterlab/pull/1896.

**Comment by jasongrout** [comment]
Noted. Closing this as resolved, filed as reference.
