### ISSUE TITLE
Markdown cell renders style and script if it was a code cell before

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1941]
Expected behaviour:
 1. Create a cell
 2. Convert it to a markdown cell
 3. Put in html code (with style tags) and it gets cleaned

Unexpected behaviour:
 1. Create a cell
 1. Run something in it
 1. Convert it to a markdown cell
 1. Put in html code (with style tags) and it **does not** get cleaned

![untitled2](https://cloud.githubusercontent.com/assets/2200743/24050572/3c40b6c4-0b55-11e7-9031-6924d9bb9cfd.gif)

**Comment by blink1073** [comment]
Yikes!  Nice catch.  We need to explicitly set it to untrusted when switching to something other than a code cell.

**Comment by AbdealiJK** [comment]
This is interesting. When I have a code cell with HTML in the same page with a style, the style in the code cell is removed when I refresh:
![untitled](https://cloud.githubusercontent.com/assets/2200743/24051139/28752d12-0b57-11e7-94d7-8bfcdc16910a.gif)

**Comment by blink1073** [comment]
Right, because when it is pulled from disk the cell is not trusted because it is markdown.  We only temporarily trusted it in the client.

**Comment by AbdealiJK** [comment]
But the first cell - the one with html output should still be trusted right ?

**Comment by blink1073** [comment]
Oh, that one I'm not sure about, what is the behavior in classic notebook?

**Comment by blink1073** [comment]
Hmm, I just tried this in master and the code cell is preserving the trust on a page refresh.

**Comment by blink1073** [comment]
I'm calling the core issue fixed by #1943 (thanks!).
