### ISSUE TITLE
Cell with input field never finished executing

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#1944]
Was trying to use the `input()` function in python, and JupyterLab changes the `In [*]` to `In[1]`. And running the cell again gives a blank output area

![untitled3](https://cloud.githubusercontent.com/assets/2200743/24057130/5590c940-0b6c-11e7-8865-d5793cccd488.gif)

**Comment by blink1073** [comment]
Hi @AbdealiJK, is this on master?  Had you hit "enter" after typing the 1?  Here's what I'm seeing locally:

![input_test](https://cloud.githubusercontent.com/assets/2096628/24070565/21f3964a-0b8e-11e7-9a82-213b3c56c25c.gif)

**Comment by AbdealiJK** [comment]
Ah - I can reproduce your behaviour.

I was hitting Shift + Enter for some reason (out of habit I guess).
Is this the expected behaviour for Shift + Enter ?

Also, note that after I press Shift+Enter, I can't run any other code after that - so, that's definitely a bug

**Comment by blink1073** [comment]
You can't run code because the kernel is blocked awaiting a response.  Looking at the classic notebook behavior, we should be catching Shift+Enter and sending the response.

**Comment by blink1073** [comment]
D'oh, these should have a `:focus` specifier: https://github.com/jupyterlab/jupyterlab/blob/134d500fe070adcca4333b3eac440ad34e5a74a9/packages/shortcuts-extension/src/index.ts#L133-L147
