### ISSUE TITLE
Problem starting jupyter lab

### ISSUE THREAD

**Issue by marberi** [jupyterlab/jupyterlab#1967]
Using commit e1a0381ae666d1f7e82db36d7add3e07d80a6002 I managed to
install (using python setup.py develop), but then ended up having an error. The
message [1] and some other output is included at the end.

Not being familiar with the code, it looks like there is two errors. One when
trying todo

GET /lab?token=a0e9d101eb563891943d99e0d676b100a601be5e99080ddf  (::1)

where it seems to want to use IPv6. Not completely sure how how that will work
on my machine... [2] [3] I can ping (ping6) localhost, but IPv6 over the network
does not work. I basically did not configure this myself, just plugged an iMac
into the local network..

The network does not route while another comes when wanting to display an error 
page. I have the file here:

ekorn:jupyterlab marberi$ ls /Users/marberi/source/jupyterlab/jupyterlab/error.html 
/Users/marberi/source/jupyterlab/jupyterlab/error.html

[1]
ekorn:~ marberi$ jupyter lab
[I 13:01:42.361 LabApp] JupyterLab alpha preview extension loaded from /Users/marberi/anaconda2/lib/python2.7/site-packages/jupyterlab
[I 13:01:42.420 LabApp] Serving notebooks from local directory: /Users/marberi
[I 13:01:42.420 LabApp] 0 active kernels 
[I 13:01:42.420 LabApp] The Jupyter Notebook is running at: http://localhost:8888/?token=80eeefabe99bec31a1ef9b266875deb7f4e9839a987f3bf5
[I 13:01:42.420 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:01:42.421 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=80eeefabe99bec31a1ef9b266875deb7f4e9839a987f3bf5
[I 13:01:43.624 LabApp] Accepting one-time-token-authenticated connection from ::1
[E 13:01:43.625 LabApp] JupyterLab build artifacts not detected, please see CONTRIBUTING.md for build instructions.
[E 13:01:43.625 LabApp] Uncaught exception GET /lab?token=9d62c15a5055ae2979c70624f4aa362ff6d44c330d55e103 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab?token=9d62c15a5055ae2979c70624f4aa362ff6d44c330d55e103', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.8,es;q=0.6,nb;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': '_xsrf=2|f2830af5|b9ff03d70e97729e1c945565bad28a3e|1489070997; username-localhost-8888="2|1:0|10:1489416671|23:username-localhost-8888|44:NTAxMmU1YzExMDAzNDZkZmE1M2M5ZTQ3Mzg4ODRhMjE=|c0547ae9ab6af08eab6aaefd3a335d2e3ed3d2ddf13061132f8d42ad0041be71"', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 2829, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/jupyterlab/extension.py", line 62, in get
        message=msg))
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 343, in render_template
        template = self.get_template(name)
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/jupyterlab/extension.py", line 127, in get_template
        return FILE_LOADER.load(self.settings['jinja2_env'], name)
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
        raise TemplateNotFound(template)
    TemplateNotFound: error.html
[E 13:01:43.688 LabApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 994, in send_error
        self.write_error(status_code, **kwargs)
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 413, in write_error
        html = self.render_template('error.html', **ns)
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 343, in render_template
        template = self.get_template(name)
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/jupyterlab/extension.py", line 127, in get_template
        return FILE_LOADER.load(self.settings['jinja2_env'], name)
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/Users/marberi/anaconda2/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
        raise TemplateNotFound(template)
    TemplateNotFound: error.html
[E 13:01:43.689 LabApp] {
      "Accept-Language": "en-US,en;q=0.8,es;q=0.6,nb;q=0.4", 
      "Accept-Encoding": "gzip, deflate, sdch, br", 
      "Host": "localhost:8888", 
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36", 
      "Connection": "keep-alive", 
      "Cookie": "_xsrf=2|f2830af5|b9ff03d70e97729e1c945565bad28a3e|1489070997; username-localhost-8888=\"2|1:0|10:1489416671|23:username-localhost-8888|44:NTAxMmU1YzExMDAzNDZkZmE1M2M5ZTQ3Mzg4ODRhMjE=|c0547ae9ab6af08eab6aaefd3a335d2e3ed3d2ddf13061132f8d42ad0041be71\"", 
      "Upgrade-Insecure-Requests": "1"
    }
[E 13:01:43.689 LabApp] 500 GET /lab?token=9d62c15a5055ae2979c70624f4aa362ff6d44c330d55e103 (::1) 65.95ms referer=None

[2]
ekorn:~ marberi$ ifconfig -a
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
fw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 4078
	lladdr d4:9a:20:ff:fe:c9:12:2e 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect <full-duplex>
	status: inactive
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether d4:9a:20:5d:3e:23 
	inet6 fe80::189d:95c2:ad05:5479%en1 prefixlen 64 secured scopeid 0x5 
	inet 10.109.160.164 netmask 0xffffe000 broadcast 10.109.191.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 06:9a:20:5d:3e:23 
	media: autoselect
	status: active
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=b<RXCSUM,TXCSUM,VLAN_HWTAGGING>
	ether d4:9a:20:d1:7c:7a 
	inet6 fe80::c7c:b2f6:40c6:35eb%en0 prefixlen 64 secured scopeid 0x7 
	inet 10.50.2.71 netmask 0xfffffc00 broadcast 10.50.3.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::4d5f:9706:953d:4f51%utun0 prefixlen 64 scopeid 0x8 
	nd6 options=201<PERFORMNUD,DAD>

[3]
ekorn:~ marberi$ ping6 ::1
PING6(56=40+8+8 bytes) ::1 --> ::1
16 bytes from ::1, icmp_seq=0 hlim=64 time=0.105 ms
16 bytes from ::1, icmp_seq=1 hlim=64 time=0.078 ms
16 bytes from ::1, icmp_seq=2 hlim=64 time=0.089 ms
16 bytes from ::1, icmp_seq=3 hlim=64 time=0.142 ms
16 bytes from ::1, icmp_seq=4 hlim=64 time=0.116 ms
16 bytes from ::1, icmp_seq=5 hlim=64 time=0.095 ms
16 bytes from ::1, icmp_seq=6 hlim=64 time=0.114 ms
16 bytes from ::1, icmp_seq=7 hlim=64 time=0.112 ms
16 bytes from ::1, icmp_seq=8 hlim=64 time=0.108 ms

**Comment by blink1073** [comment]
Hi @marberi, based on the traceback it looks like `python setup.py develop` did not properly build the JavaScript artifacts.  Can you please run `npm install && npm run build` from the root of the repo and paste the output?

**Comment by marberi** [comment]
Closing this issue. I never got this working on the Mac, but has
since left for another institution. By now I install jupyterlab on
linux using conda-forge packages and things are working fine.
