### ISSUE TITLE
tooltip line wrap

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#1976]
A picture is worth a thousand words:

![image](https://cloud.githubusercontent.com/assets/2069677/24203281/9518b256-0f15-11e7-8ff0-19f23c8c748d.png)

Right now the tooltip wraps lines cutting the words halfway. I suggest several improvements:
* Ensure that the tooltip can accommodate lines with at least 79 characters
* break lines by word, not by symbol
* potentially use a horizontal scroll-bar instead of line breaks.

**Comment by afshin** [comment]
Thanks for reporting it and the screenshot.

**Comment by ellisonbg** [comment]
I think the tooltip should scroll not wrap as it contains formatted monospaced text. Wrapping makes sense for paragraphs of narrative text, but for formatted stuff like this, it makes it less readable.
