### ISSUE TITLE
Open a new view into a file

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#1977]
If you want to view both the top and bottom of a file, common idioms include either opening the file twice, dragging a splitter bar that exposes two views of the file, or having an option to create a new view of the file.

I think the third option, a command to create a new view of the file, may be the best in our case, though as Paul points out, it's not extremely intuitive. Perhaps a right-click option on the filename to open a new view would also help.

CC @pganssle who brought up this issue.

**Comment by sccolbert** [comment]
:+1: for a right-click option on the file's content body, tab, or both.

**Comment by sccolbert** [comment]
In general, all we need is a command to open a new view into a file, then we can plug that into the universal context menu anywhere.

**Comment by ellisonbg** [comment]
We now have the context menu, just need a way to open another view...

**Comment by ian-r-rose** [comment]
Resolved by #2829.
