### ISSUE TITLE
Lab extensions linking to local dev branches

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#1995]
Getting this down in words so that I don't forget (and in case others find it useful).

One packaging use case that is still challenging is developing labextensions against a development branch of JupyterLab. If you `npm link` the relevant packages, you can get nested dependencies (especially with things like phosphor widgets) that cause the Typescript compiler to fail with messages like:
```
src/plugin.ts(141,27): error TS2345: Argument of type '{ commands: CommandRegistry; }' is not assignable to parameter of type 'IOptions'.
  Types of property 'commands' are incompatible.
    Type 'CommandRegistry' is not assignable to type 'CommandRegistry'. Two different types with this name exist, but they are unrelated.
src/plugin.ts(177,23): error TS2345: Argument of type '{ commands: CommandRegistry; }' is not assignable to parameter of type 'IOptions'.
  Types of property 'commands' are incompatible.
    Type 'CommandRegistry' is not assignable to type 'CommandRegistry'. Two different types with this name exist, but they are unrelated.
      Types of property 'commandChanged' are incompatible.
        Type 'ISignal<CommandRegistry, ICommandChangedArgs>' is not assignable to type 'ISignal<CommandRegistry, ICommandChangedArgs>'. Two different types with this name exist, but they are unrelated.
          Types of property 'connect' are incompatible.
            Type '(slot: Slot<CommandRegistry, ICommandChangedArgs>, thisArg?: any) => boolean' is not assignable to type '(slot: Slot<CommandRegistry, ICommandChangedArgs>, thisArg?: any) => boolean'. Two different types with this name exist, but they are unrelated.
              Types of parameters 'slot' and 'slot' are incompatible.
                Type 'Slot<CommandRegistry, ICommandChangedArgs>' is not assignable to type 'Slot<CommandRegistry, ICommandChangedArgs>'. Two different types with this name exist, but they are unrelated.
                  Types of parameters 'sender' and 'sender' are incompatible.
                    Type 'CommandRegistry' is not assignable to type 'CommandRegistry'. Two different types with this name exist, but they are unrelated.
```

One potential solution can be found in the discussion [here](https://github.com/Microsoft/TypeScript/issues/6496). Essentially, you can add explicit paths to the conflicting packages for `tsc` to use. For instance, I have an extension which can be fixed by adding 
```
    "baseUrl": ".",
    "paths": {
      "@phosphor/widgets": ["../node_modules/@phosphor/widgets"],
      "@phosphor/signaling": ["../node_modules/@phosphor/signaling"],
      "@phosphor/coreutils": ["../node_modules/@phosphor/coreutils"],
      "@phosphor/application": ["../node_modules/@phosphor/application"],
      "@phosphor/commands": ["../node_modules/@phosphor/commands"],
      "@phosphor/algorithm": ["../node_modules/@phosphor/algorithm"]
    }
```
to `tsconfig.json`.

CC @blink1073 @gnestor @danielballan

**Comment by danielballan** [comment]
It's nice to know there is a workable solution, even if it's not ideal. I haven't come across any better ideas yet.

**Comment by blink1073** [comment]
Thanks, @ian-r-rose!  Here is a shorthand, similar to what we use in the main [config](https://github.com/jupyterlab/jupyterlab/blob/74e39e55e8d1796ede3b1e6d5006a865307c97cc/jupyterlab/tsconfig.json#L15):

```json
    "baseUrl": ".",
    "paths": {
      "@phosphor/*": ["../node_modules/@phosphor/*"]
    },
```

**Comment by ian-r-rose** [comment]
Ah! I guess you are already aware of the basic fix, then!  This is not really a bug or issue per se, but I wonder whether it would be appropriate as a note somewhere in the extension building docs.

**Comment by blink1073** [comment]
Yep, this would be a good note in an `npm link` workflow demo.

**Comment by blink1073** [comment]
As mentioned [here](https://github.com/jupyterlab/jupyterlab/pull/2038#issuecomment-295030237), the preferred workflow will now be to build against released JupyterLab packages, which is what the built JupyterLab application will use.  Building against master should only be needed if making simultaneous changes to JupyterLab itself, in which case you would temporarily add the package to the `lerna` build.  This workflow still needs to be proven out/documented.

**Comment by ian-r-rose** [comment]
Sounds good. Feel free to close.

**Comment by blink1073** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/issues/2064.
