### ISSUE TITLE
Extensions: "Uncaught Error: Widget is not contained in the dock panel"

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#2003]
I'm trying to release 0.18 of the mimerender extensions (to work with jupyterlab@0.18) but I'm running into the following error when attempting to open a file with the extension:

```
Uncaught Error: Widget is not contained in the dock panel. (main.bundle.js:17797 )
    at DockPanel.selectWidget (main.bundle.js:17797)
    at DockPanel.activateWidget (main.bundle.js:17811)
    at ApplicationShell.activateById (main.bundle.js:23853)
    at Object.open (main.bundle.js:108566)
    at DocumentManager._createOrOpenDocument (main.bundle.js:108948)
    at DocumentManager.openOrReveal (main.bundle.js:108720)
    at DirListing._evtDblClick (main.bundle.js:106576)
    at DirListing.handleEvent (main.bundle.js:106253)
```

I've seen this error in the past (https://github.com/jupyterlab/jupyterlab/issues/1732#issuecomment-280683864) which seemed to be caused by conflicting dependency versions. However, I'm running jupyterlab@0.18.0 and depending on @jupyterlab/docregistry@0.1.3 (which is the same version that jupyterlab depends on) and @phosphor/widgets@0.3.1 (which is the same version that @jupyterlab/docregistry@0.1.3 depends on).

`DockPanel.selectWidget` looks like:

```js
selectWidget(widget: Widget): void {
    // Find the tab bar which contains the widget.
    let tabBar = find(this.tabBars(), bar => {
      return bar.titles.indexOf(widget.title) !== -1;
    });

    // Throw an error if no tab bar is found.
    if (!tabBar) {
      throw new Error('Widget is not contained in the dock panel.');
    }

    // Ensure the widget is the current widget.
    tabBar.currentTitle = widget.title;
  }
```

https://github.com/phosphorjs/phosphor/blob/51d5c7bc48ba6789a4f15aa3942aed070938c4bd/packages/widgets/src/dockpanel.ts#L256.

I inspected the values of `titles` in `this.tabBars()` and it contains a title that matches`widget.title`, but apparently they don't share the same identity. This implies to me that my extension is using a different version of docregistry than jupyterlab... 🤔

I've created a branch of jupyterlab_geojson that can be used to reproduce: https://github.com/gnestor/jupyterlab_geojson/tree/develop

cc @blink1073 @sccolbert

**Comment by ian-r-rose** [comment]
I saw this error yesterday as well. Unfortunately I don't have a branch to point to, as I rolled back my version.

**Comment by blink1073** [comment]
@gnestor, here's where the other Phosphor is coming from: https://github.com/gnestor/jupyterlab_geojson/blob/a61251cdafdc0673062a3bfda0759d5bef17ea7b/labextension/package.json#L29.  Note that this will be caught at build time once we sort that out.

**Comment by gnestor** [comment]
Yep, that was the culprit. I guess that I had tried `npm install @phosphor/widgets@^0.3.0` without the `--save` and then I must've lost that version when trying other stuff.

@ian-r-rose The takeaway: When targeting a specific version of jupyterlab, look at a `package.json` of a similar package at that commit ([csvwidget at v0.18.0 tag](https://github.com/jupyterlab/jupyterlab/blob/a703d1f03c02178855f292ca8cd7f6cded492479/packages/csvwidget/package.json)) and use the dependency versions that are used there.
