### ISSUE TITLE
Default editor factories

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2009]
As of right now, creating a cell widget or a notebook widget requires providing a `contentFactory`, which requires an `editorFactory`.  We can make this simpler by using a default editor factory from `@jupyterlab/codemirror` internally, making the `contentFactory` an optional parameter.

cf
https://github.com/jupyterlab/jupyterlab/blob/89cc86ebe892f184e3c1d10055f46c6d7ffc5b37/packages/cells/src/widget.ts#L276
https://github.com/jupyterlab/jupyterlab/blob/89cc86ebe892f184e3c1d10055f46c6d7ffc5b37/packages/cells/src/widget.ts#L287
https://github.com/jupyterlab/jupyterlab/blob/89cc86ebe892f184e3c1d10055f46c6d7ffc5b37/examples/notebook/src/index.ts#L105-L107

**Comment by ellisonbg** [comment]
Fixed in master!
