### ISSUE TITLE
Plan for Extension Handling

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2011]
After several attempts, we have finally come to the conclusion that it is not feasible to handle extensions without using node to build the assets on the server.  Our latest attempt, #1973, was to use a WebPack extension to build individual bundles, and then assemble the bundles on the server, using semver to deduplicate packages.  What we soon realized is it is impossible to know for sure which modules from an upstream npm package will be consumed, so we cannot effectively deduplicate packages at the package level without having the entire package.

The proposed solution is to bundle the entire `node_modules` tree with an extension, and then merge the trees and build the final WebPack bundle on the server.  We rely on `npm` to deduplicate the packages in their entirety, and WebPack to bundle the assets.  

Note that the above are only required to add new extensions to the system.  Bundles can be distributed that contain a preconfigured set of extensions, and the user can be given the opportunity to enable or disable individual extensions in the bundle (cf #1523).

The requirement to have `node` installed on the user's machine can be alleviated by using the `node` package from `conda`, or we could use a standalone node executable builder such as [nexe](https://github.com/nexe/nexe) that could be distributed as a Python wheel.

**Comment by jasongrout** [comment]
As part of this, we may also expand what extensions are distributed with the default jupyterlab package. For example, we may distribute the jupyter widgets extension, a table-viewer extension, etc., so that the vast majority of users can use jupyterlab right out of the box without node on their system.

If the cost of having node available at runtime is too high, other communities may choose to distribute their own collection of plugins as a jupyterlab variant. For example, the astronomy community may distribute a pre-built jupyterlab bundled with plugins for viewing astronomical images.

This would be mitigated, of course, if it turns out to be easy to make a python package for our node-based build tool.

**Comment by dhirschfeld** [comment]
Just thought I'd pipe-up to say that as a Windows/conda user, if node is available as a conda package then having a dependency on it is a non-issue for me.

I can imagine it might be a different story for non-conda users, but I think the vast majority of Windows users are using conda these days.

**Comment by sccolbert** [comment]
If you're using conda, we can make the whole process completely
transparent: 'conda install some_lab_extension'

We could see about bundling a node exe in a pip package if there's time and
strong demand.

The first step is making it work assuming node is available. After that we
can solve the packaging node issue :)

**Comment by blink1073** [comment]
As suggested by @ddavidebor, there is also https://github.com/igorklopov/enclose.

**Comment by blink1073** [comment]
@SylvainCorlay, @gnestor, before proceeding I want to make sure we have a plan for handling loaders at the top level.

Loaders are applied in the order they appear in the WebPack config, so for example we can apply `babel` to some `.js` files using a similar rule to [this](https://github.com/jupyterlab/jupyterlab_geojson/blob/0342d541b9c33c559a6f26c372358211a28bbeca/labextension/build_extension.js#L38), which would be added before any JupyterLab rules related to JS.  It looks like [ipywidgets](https://github.com/jupyter-widgets/ipywidgets/blob/adce7cb43d8c805bace4740fcbb8e58ceb179667/jupyterlab_widgets/scripts/buildExtension.js) and [bqplot](https://github.com/bloomberg/bqplot/blob/d2f115dba34125e0250c488d745461ccc89c3d7c/js/webpack.config.js) are already using the standard JupyterLab loaders.

We'd have to make sure that loaders were added in a stable order, say alphabetically by extension name and then add the core ones last.

Extensions would have to have their required loaders as `dependencies` so they'd be picked up in the zipped `node_modules`.

**Comment by blink1073** [comment]
Note that babel is no longer required when using Webpack 2.0, it was given as an example.

**Comment by blink1073** [comment]
Wait, no, I see that bqplot is not using the default loaders, is that only because of `less`?

**Comment by jasongrout** [comment]
@blink1073 - here is the relevant issue: https://github.com/jupyterlab/extension-builder/issues/42

Basically, we already had a set of loaders in bqplot for the non-lab case, and wanted to re-use it, so it was simplest to just use the loaders we already defined. Now, I imagine we'll just go with the default loaders + less to avoid confusion with other lab plugins.

**Comment by blink1073** [comment]
Hmm, it looks like we need to de-dupe the loaders as well.

**Comment by blink1073** [comment]
I looked at `npm pack` but it does not handle symlinks, so we need a script that walks the dependencies of the top level `package.json` (we have this part), and runs `npm pack` in each folder, then combines all of these files.

**Comment by blink1073** [comment]
I tried to copy an existing node modules into our main entry point, add it to the top level `package.json`, and run `npm install`, but it got confused by our hoisted dependencies.  However, some experimentation shows that it should be possible to run `npm install` programmatically rather than shelling out, enabling us to make our standalone bundler executable.

**Comment by blink1073** [comment]
Next step is to generate some node_module thunks and combine them.

**Comment by gnestor** [comment]
@blink1073 Regarding loaders, the only reason that the mimerender extensions haven't been using the default loaders is because the React branch depends on babel-loader. If babel-loader is no longer required in webpack 2, then great!

**Comment by gnestor** [comment]
This will solve another edge case that I've run into: Both labextension and nbextension depend on module X to do the rendering. Including module X in the `package.json` of the labextension (e.g. `"module-x": "file:../module-x"`) would break the build because extension-builder is looking for a valid semver where the local path is. As a result, I've had to add a npm preinstall scripts that does `npm install ../module-x` in order to include module X in the labextension bundle.

**Comment by bollwyvl** [comment]
Throwing a few things out:

After using it in anger for a while, I would _always_ want to use `yarnpkg` instead of `npm` for doing this kind of thing at runtime. The time savings is really, really intense, _especially_ with a 100mb+ `babel` stack. Humorously, yarn actually has a standalone javascript installation file, which uses webpack to build a CLI app distributed as a single js file! Indeed, we actually packaged up yarnpkg up this way with conda, and it works great! It also supports a `--flat` mode, but I am not sure if we can actually use it that way, yet, as it would be hard to automate away the multiple-versions-of-things-needed problem.

Somewhat orthogonal to this, instead of node, one could also imagine using [pyminiracer](https://github.com/sqreen/PyMiniRacer), which claims:
> MiniRacer can be easily used by Django or Flask projects to minify assets, run babel or compile CoffeeScript.

**Comment by blink1073** [comment]
Thanks for the pointers, @bollwyvl!

**Comment by blink1073** [comment]
@sccolbert, @bollwyvl, and I chatted a bit about how to handle WebPack loaders.  Since we cannot guarantee that loaders provided by extensions will not interfere with each other, JupyterLab itself must use a set of loaders and extension authors must provide assets that are consumable by those loaders.  This would mean that `less` files would need to be transpiled, and if a dependency used ES6 syntax it would have to be moved to a `devDependency`, transpiled, and absorbed into the extension.

**Comment by gnestor** [comment]
Oooh, one other thing to consider: Some libraries (like React) will choke if multiple instances of different versions are being used at the same time. Would this deduping of extension dependencies solve this problem?

**Comment by blink1073** [comment]
Going to look at React next as I attempt to port `jupyterlab_geojson`.

**Comment by gnestor** [comment]
I'm a little behind on upgrading the mimerender extensions, but I have a PR for jupyterlab_geojson 0.18.0: https://github.com/gnestor/jupyterlab_geojson/pull/1 (0.19.0 coming soon!)

**Comment by blink1073** [comment]
@gnestor, already in progress: https://github.com/jupyterlab/jupyterlab_geojson/pull/33

**Comment by blink1073** [comment]
`npm dedupe` takes care of the multiple versions, as long as they can be hoisted.

**Comment by gnestor** [comment]
Cool. Even if they're different versions?

**Comment by blink1073** [comment]
As long as the semver ranges overlap.

**Comment by blink1073** [comment]
Updated plan based on lessons learned in #2023 and discussion today with @sccolbert, @jasongrout, @afshin, @ivanov, and myself:

JupyterLab configuration and extensions will use standard node workflows as much as possible.

We will use `/share/jupyterlab` in the user’s Python environment to host the JupyterLab application, which will consist of a `package.json` file that has a `jupyterlab` key with the enabled extensions as well as the extra configuration to add to the application.

We will provide the following scripts:

- `jupyterlab install <foo>` will use the standard `npm install` semantics in `/share/jupyterlab` folder.  An extension could be identified using package.json metadata.
- `jupyterlab enable/disable <foo>` will enable/disable extensions in the application, to include the “core” plugins themselves.
- `jupyterlab list` will list the extensions and whether they are enabled
- `jupyterlab build` will create an updated templated entry point file and build the application artifacts.

We will ship a standard built application, which will be preserved as a fallback (and may be accessible directly through a separate URL).  This will include all core plugins as well as ipywidgets and any other extensions that are deemed "invaluable".

For extension authors building against a released JupyterLab, we provide a `jupyterlab link <foo>` that will use the standard `npm link` from the `/share/jupyterlab` folder.   

The core JupyterLab development workflow will continue to use the internal application and no external extensions or config for now.  We will need to address this workflow next.

We are focusing right now on making the online extension install process as easy as possible. Fully offline installs can be accomplished with a local or corporate npm mirror, and we can improve on this in the future.

This shift simplifies the concept of a JupyterLab extension to that of an npm package. For complex extensions which require extra server-side customization, that functionality shall be written as a formal server extension, similar to [jupyterhub](https://github.com/jupyterhub/jupyterhub-labextension/blob/0b030896235ccfbcea7e5decfe26876bc9ad76ae/jupyterhub_labextension/singleuser.py#L11).

**Comment by blink1073** [comment]
More thoughts:

- We will use `jupyterlab` as our command line namespace, but use the existing `jupyter` file system locations to avoid cluttering the user's machine.  
- We keep `labconfig.json` in `/etc` in the user's environment, which is used to populate the page configuration.  This data includes `ignorePlugin` [config](https://github.com/phosphorjs/phosphor/blob/master/packages/application/src/index.ts#L580) that can be used to ignore specific plugins.  We can provide a UI that allows the user to select which plugins to enable/disable (ignore).  
- `jupyterlab install` will install the specified package to a temporary cache location, and then verify in it's `package.json` whether it has the appropriate `jupyterlab` config data.  It will reject if the package is not designated as `jupyterlab` extension.  Note that we can't actually import the file from node to verify its extension points without first having to WebPack the entry point because some code will use the DOM during import.

This approach allows `jupyterlab link` to use the standard `npm link` semantics, and avoids having to use our own internal cache that we have to preserve (we only use a temporary one to extract the initial package.json data).
