### ISSUE TITLE
UX - Clearing cells in a notebook

### ISSUE THREAD

**Issue by willingc** [jupyterlab/jupyterlab#2012]
This isn't a bug, but simply feedback from moving from the classic notebook to jupyterlab. The multiple menu options (notebook, terminal, console) caused me some temporary confusion when trying to clear all cells in a notebook. I've included a GIF, but I thought I had cleared the cells yet the notebook didn't have cleared cells. After a minute or so, I realized that I had clicked clear cells in the **console** menu not the **notebook** menu. If possible, it would be helpful for the user to have some feedback if they have selected the wrong menu and option. [Part of the issue was muscle memory from using the classic notebook since the console menu is roughly in the same place as the menu for clearing cells in the classic notebook.

![clear-cells](https://cloud.githubusercontent.com/assets/2680980/24472346/3ba441da-147a-11e7-9431-36172f735bd4.gif)

**Comment by willingc** [comment]
@ellisonbg @cameronoelsen fyi

**Comment by sccolbert** [comment]
related to #1573
