### ISSUE TITLE
Code doesn't display completely on paste

### ISSUE THREAD

**Issue by dmadeka** [jupyterlab/jupyterlab#2013]
If I paste a large amount of code (causes scroll basically) into a notebook cell, only the tail of the code appears until I click inside the cell. Not sure why this is happening

On Paste:

![image](https://cloud.githubusercontent.com/assets/7892382/24484910/cbc2ffe6-14ce-11e7-8fcd-20a27d3eafd5.png)

After Clicking inside the cell:

![image](https://cloud.githubusercontent.com/assets/7892382/24484914/d454f902-14ce-11e7-9eb1-5205c4b4d543.png)

**Comment by sccolbert** [comment]
What OS/browser? Does this happen on other browsers as well?

**Comment by dmadeka** [comment]
Version 56.0.2924.87 (64-bit). I dont have any others installed. I can check at work tomorrow

**Comment by sccolbert** [comment]
Is that version number for Chrome on Windows?

**Comment by AbdealiJK** [comment]
I can reproduce for chrome on Mac

**Comment by dmadeka** [comment]
@sccolbert No clue, i dont have a great way to check that

**Comment by sccolbert** [comment]
@AbdealiJK thanks. I was just trying to rule out a browser rendering bug. We'll take a look.

**Comment by willingc** [comment]
@sccolbert I'm able to reproduce on Mac 10.12.4 and Chrome. Here are screenshots of before and after:

![screenshot 2017-03-29 22 32 49](https://cloud.githubusercontent.com/assets/2680980/24489079/2be8bc34-14d0-11e7-85ca-2d1e5c282739.png)
![screenshot 2017-03-29 22 33 10](https://cloud.githubusercontent.com/assets/2680980/24489080/2be8f122-14d0-11e7-9968-a408740ad456.png)

**Comment by sccolbert** [comment]
Thanks @willingc !

**Comment by blink1073** [comment]
I tried to reproduce this on master and in the 0.20.3 release, using 10.12.4 and Chrome 58, but it looks to be working.  Is anyone able to reproduce in the 0.20.3 release?

<image src="https://cloud.githubusercontent.com/assets/2096628/25590540/9815a6b4-2e76-11e7-8559-95d90923a836.png" width=400>

**Comment by ellisonbg** [comment]
I tested on Chrome 58 and FF 53 on Mac, no observations of it - all is well. @willingc could you test master on Chrome 58 latest when you get a chance?

**Comment by willingc** [comment]
Found this last night on current master with Chrome:

<img width="918" alt="screen shot 2017-05-11 at 7 55 48 pm" src="https://cloud.githubusercontent.com/assets/2680980/26003188/d7841876-36e6-11e7-9a40-447a9f2d76cc.png">

What is the best process to do a completely clean install for JupyterLab so I can be sure that there is no cruft from js or npm? Thx.

**Comment by blink1073** [comment]
`git clean -dfx && pip install -e . && npm install && npm run build && jupyter lab --core-mode` is the surest bet.

**Comment by willingc** [comment]
@blink1073 :cake: Thanks!
![woohoo](https://cloud.githubusercontent.com/assets/2680980/26713101/affd92b6-471f-11e7-9b09-3ffb402c41f2.gif)
