### ISSUE TITLE
Disable or adjust auto-scroll to selected cell

### ISSUE THREAD

**Issue by StevenCHowell** [jupyterlab/jupyterlab#2016]
I get thrown off by how JupyterLab will scroll the screen to center on the cell I click on, even if the cell is completely on the screen. I get especially frustrated when I double click to go directly to editing the cell, but now I've scrolled twice, as the each click moves the cell I select to the center. 

Consider turning this off, though maybe it could be an optional setting people could enable in preference.  Currently it seems to only occur for about the bottom and top thirds of my screen. This seem excessive. 
 It it is kept as an optional setting, consider adjusting to narrower limits, maybe the the top and bottom sixth, or eighth.

To illustrate, if I click on the cell labeled `In [49]:` in this notebook (note that the cell is already positioned nicely for editing in my opinion)
![image](https://cloud.githubusercontent.com/assets/9484229/24560961/e76cdb64-1612-11e7-8e08-3a474f2a5d0f.png)

it moves the cell down to here
![image](https://cloud.githubusercontent.com/assets/9484229/24561020/2ea9fc50-1613-11e7-9e3d-0cb3b52e32c2.png)

**Comment by tdaff** [comment]
Yes, please disable! The autoscroll keeps putting half my cell and the output off the bottom of the screen after I've just scrolled them to where I want them! This is especially annoying as I like to have the top of the cell at the top of the screen when I edit.
