### ISSUE TITLE
Drag and drop files into file browser

### ISSUE THREAD

**Issue by eskirk** [jupyterlab/jupyterlab#202]
I think it would be really intuitive if we could drag and drop files into the file browser directly from your computer, I would try to hack this together and submit a PR but am not really too sure where to start (and I'm not sure if this was intentionally left out [security reasons?])

Thoughts?

**Comment by blink1073** [comment]
We have an internal drag-drop system right now because browsers all implement the drag-drop spec differently (especially wrt the mime types supported), and we have not gotten around to adding support for external drag-drop.

**Comment by jasongrout** [comment]
We have uploading as drag and drop in the current notebook - I use it often.
