### ISSUE TITLE
bash: update_terminal_cwd: command not found

### ISSUE THREAD

**Issue by gatagat** [jupyterlab/jupyterlab#2027]
When running jupyterlab's terminal, there is an error message before each command prompt:

    bash: update_terminal_cwd: command not found

This bug is specific to OSX, where `/etc/bashrc_Apple_Terminal` is sourced if `TERM_PROGRAM` is "AppleTerminal", but it might indicate some trouble with jupyterlab not properly initializing the environment in general.

jupyterlab: 0.19
OSX: 10.11.6

**Comment by blink1073** [comment]
Hi @gatagat, do you see the same behavior when launching a terminal from the classic notebook?  You can create a new one dynamically by replacing `/lab` with `/terminals/1` in the url.

**Comment by gatagat** [comment]
Yes, i see it also when i go directly to `/terminals/1`. Though now i have tried to get rid of all the relevant dot files in my home and then there is no error message. I will try to find out what triggers it.

**Comment by gatagat** [comment]
The bug is triggered by changing the environment variable `PROMPT_COMMAND`. Its default value on OSX `update_terminal_cwd` gets deleted when starting the terminal. Any non-default value (my case) is left unchanged causing the error.

No error:

    PROMPT_COMMAND="update_terminal_cwd" jupyter-lab
Error:

    PROMPT_COMMAND="true;update_terminal_cwd" jupyter-lab

**Comment by blink1073** [comment]
Hmm, I'm not sure where that could be getting reset.  I did a search in thehttps://github.com/sourcelair/xterm.js, https://github.com/takluyver/terminado, and https://github.com/jupyter/notebook repos (and this one) for `prompt_command` and came up empty.   Will need some more investigation.

**Comment by gatagat** [comment]
Ooops, it's been my error with the bash dot files.  Setting `PROMPT_COMMAND` in `.bash_profile` instead of `.bashrc` does not seem to be a good idea. Sorry for wasting your time.

When I set the `PROMPT_COMMAND` in `.bashrc`, everything works as expected (the `update_terminal_cwd` gets stripped from the end of the variable, so there is no error output).

**Comment by blink1073** [comment]
Glad you got sorted. 👍
