### ISSUE TITLE
Markdown cells are calling the kernelcompleter

### ISSUE THREAD

**Issue by mpacer** [jupyterlab/jupyterlab#2032]
I was attempting to test some of the ambiguous pieces of the markdown spec and was trying to tab over a list (`|` is where the cursor was positioned):

```markdown
- list item 1
- list item 2

|- list item 3
- list item 4
```

And it brought up a ValueError in the notebook server that was hitting (in the middle of the stack)

`File "~/jupyter/ipython/IPython/core/completer.py", line 1774, in complete
    return self._complete(line_buffer=line_buffer, cursor_pos=cursor_pos, text=text, cursor_line=0)[:2]`

…which shouldn't have happened since it was a markdown cell.

cc @ian-r-rose @Carreau

**Comment by blink1073** [comment]
cc @afshin
