### ISSUE TITLE
Terminal option not available 

### ISSUE THREAD

**Issue by pradeepisro** [jupyterlab/jupyterlab#2033]
I am unable to get the terminal option in the menu bar in jupyter lab.
![issues](https://cloud.githubusercontent.com/assets/14920956/24830798/7582cc4a-1caa-11e7-966e-972688e6389f.PNG)

**Comment by jasongrout** [comment]
What operating system are you running the server on?

**Comment by pradeepisro** [comment]
Windows 10 64 bit

**Comment by blink1073** [comment]
Hi @pradeepisro, unfortunately we do not yet support terminals on Windows.  Original discussion: https://github.com/jupyter/notebook/issues/172.

**Comment by pradeepisro** [comment]
Hey could you support using Windows Subsystem for Linux. Is that possible?
I don't  understand what TTY, please provide me insight into it.

**Comment by blink1073** [comment]
It should be technically possible to support the WSL.  TTY is described [here](http://stackoverflow.com/a/4426291).  We rely on a TTY-like interface for the terminal, which was not feasible before WSL.  
The library we are using for the terminal communication is [terminado](https://github.com/takluyver/terminado).  
Options include patching that library to use WSL or switching to [node-pty](https://github.com/Tyriar/node-pty), which recently got Windows support (and it is what is used in Visual Studio Code on Windows.  I believe both options would require a fair bit of work.

**Comment by pradeepisro** [comment]
So Windows CMD is a terminal emulator and what about Powershell. Is it TTY  interface

**Comment by blink1073** [comment]
Unfortunately it uses a different (non-TTY) protocol, which is why terminado has not supported Windows to date.

**Comment by pradeepisro** [comment]
Thanks for all the information

**Comment by blink1073** [comment]
👍

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyter/notebook/pull/3087, will be available in Notebook 5.3

**Comment by andreaschandra** [comment]
Cool

**Comment by andreaschandra** [comment]
Cool

**Comment by IndianaGlen** [comment]
So I get that Terminals are not available for windows 10 right now.  When I Launch Jupyterlab (JLab) or Notebooks from Anaconda, it throws the "Terminals not available" error.  I have a few questions: 
Will I need to uninstall JLab to keep it from throwing the error?
Any harm in ignoring the error and using other features of JLab?  
Thoughts?
