### ISSUE TITLE
Matplotlib plotting continually crashes after reverting to stable jupyter lab

### ISSUE THREAD

**Issue by thomasaarholt** [jupyterlab/jupyterlab#2034]
**FIXED: Solved by `conda install ipykernel=4.5.2`**

I upgraded from v0.17 of jupyterlab to the current master by `pip install github...master.zip` to see if there were any major new changes coming up. Unfortunately, along the way plotting matplotlib with any backend other than inline is now broken in all jupyter environments (qtconsole, notebook, lab). A minimal example of it breaking is the following:
```python
%matplotlib qt4 # or `qt5` with pyqt5, or `notebook`
import matplotlib.pyplot as plt
plt.figure()
```
![capture](https://cloud.githubusercontent.com/assets/2721423/24836192/5d8ec7b8-1d15-11e7-8de4-65f6ff31ea33.PNG)
Trying to close the window results in a "python is not responding" standard windows error, and the kernel crashes. If I ignore the plot window but continue with my cells in lab, **they successfully run**, correctly doing calculations. Further plot calls show figure windows, but contain the same as the screenshot above.

I've reverted to the original lab by `pip uninstall jupyterlab` and `conda install jupyterlab`, and even uninstalled the entire python distribution and reinstalled it, and still it crashes. I have also deleted `~/.matplotlib` and the `~/.jupyter` and `~/.ipython` directories.

Could there be a cache somewhere that I haven't cleared?

Does anyone have any suggestions? I realise this isn't the ideal place for such an issue, but since even on a reinstall it didn't fix itself I am worried I will not be able to fix this.

**Comment by ccordoba12** [comment]
Do you have ipykernel 4.6.0 installed?

**Comment by thomasaarholt** [comment]
Yes. 4.6.0 installed.

**Comment by ccordoba12** [comment]
Could you downgrade to ipykernel 4.5.2 and try again?

**Comment by thomasaarholt** [comment]
You have made my day. Problem solved. Is this an issue I should be reporting?

**Comment by ccordoba12** [comment]
The problem seems to be this one

https://github.com/ipython/ipykernel/issues/240

Please close this bug and continue the discussion there.
