### ISSUE TITLE
Prevent XSS on file save dialog

### ISSUE THREAD

**Issue by CoaPsyFactor** [jupyterlab/jupyterlab#2041]
There is possibility to do XSS in save file dialog if filename contains javascript tag in it.

**Comment by sccolbert** [comment]
Do you have any more info on this? I've traced through the code path, and I'm not seeing where that would be possible?

**Comment by willingc** [comment]
@CoaPsyFactor Please report details as describe [here](https://jupyter-notebook.readthedocs.io/en/latest/security.html#reporting-security-issues) to security@ipython.org.

@sccolbert Thanks for reviewing. :cake:

**Comment by jasongrout** [comment]
@CoaPsyFactor - following up on this. Can you report the issues you see as @willingc described above?

**Comment by jasongrout** [comment]
Closing as unreproducible. @CoaPsyFactor, please let us know more details and we can reopen this.
