### ISSUE TITLE
Feedback on SDI mode in #2037

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#2046]
This is some feedback on #2037, which implements the fantastic single document mode (thanks!!).

1. The current document is not always selected when changing to single document mode. It seems that when a document is active in the top-left tabpanel, it is correctly selected when switching to single-document mode. However, if the current tab is in another tab panel, it is not current when changing to single-document mode.
![jlabsdi](https://cloud.githubusercontent.com/assets/192614/25092933/fd67d2a4-235d-11e7-8c6f-edeb3f52a2cd.gif)

2. The command should probably be called "Toggle .." instead of "Enter", since it really toggles the mode.

3. Is restoring the layout (i.e., the splitters and various tab panels) somewhere in the todo list?

**Comment by willingc** [comment]
Nice @afshin!

When you enter single-document mode it looks like the Code dropdown is running over the notebook navbar (i.e. it's blank instead of a line).
<img width="573" alt="screen shot 2017-04-18 at 7 03 47 am" src="https://cloud.githubusercontent.com/assets/2680980/25134742/3e2017f0-2405-11e7-8d1f-876996d9d2ed.png">

**Comment by afshin** [comment]
@willingc What browser/OS combination are you using? On Chrome Version 57.0.2987.133 (64-bit) macOS 10.12.4, I see this:

<img width="442" alt="screen shot 2017-04-18 at 3 05 29 pm" src="https://cloud.githubusercontent.com/assets/159529/25134835/8ef6449a-2448-11e7-9112-9e2b78e98795.png">

**Comment by jasongrout** [comment]
It also doesn't do that in my screencast above. Are you zoomed in the page at 100%?

**Comment by willingc** [comment]
Same as you @afshin Sierra and 57.0.2987.133 (64-bit). Setting to Actual Size made it look fine and I can't reproduce now. Web browsers 🤷‍♀️
