### ISSUE TITLE
Running clear in Code Console does not clear display

### ISSUE THREAD

**Issue by rgbkrk** [jupyterlab/jupyterlab#2048]
Actual:

![screen shot 2017-04-17 at 5 11 19 pm](https://cloud.githubusercontent.com/assets/836375/25109363/eb0a03ce-2390-11e7-85ad-15df6aefa9af.png)

Expected:

![clear](https://cloud.githubusercontent.com/assets/836375/25109434/49fb9424-2391-11e7-8407-5ecdd2a4a6c2.gif)

**Comment by sccolbert** [comment]
Is that supposed to work for notebooks/consoles? I thought `clear` was specific to the terminal?

**Comment by rgbkrk** [comment]
It doesn't work for notebook. I was hoping for a console experience here.

**Comment by sccolbert** [comment]
The web console is intended as a QtConsole-ish clone, not as a terminal clone. IIUC the `clear` magic is implemented as an OS level call to `cls` or `clear`, so we'd have to do something special here to support this.

**Comment by jasongrout** [comment]
It looks like `clear` in ipython is an alias for the system shell `clear` command (you see this by executing `%alias`). It does work if you run `ipython` from the jlab terminal.

The qtconsole does seem to also implement `clear`, which I imagine they did by hand since I don't think that is using the system terminal.  I suppose it is something that we could figure out how to support, but we'd have to do it by hand.

**Comment by rgbkrk** [comment]
Ah ok, thanks for clearing that up.

**Comment by jasongrout** [comment]
In the qtconsole, `clear??` is not an alias to the system clear command, but gives:

```
clear??
Source:
    @line_magic
    def clear(self, arg_s):
        """Clear the terminal."""
        if os.name == 'posix':
            self.shell.system("clear")
        else:
            self.shell.system("cls")
File:   ~/anaconda/lib/python3.5/site-packages/ipykernel/zmqshell.py
```

**Comment by sccolbert** [comment]
I wonder if we should make some sort of "frontend magics" that could be implemented/registered by jlab plugins, and invoked by a kernel? That would be kinda cool...

**Comment by ian-r-rose** [comment]
In a sense, the `%javascript` and `%html` magics are a kind of clumsy frontend magic that can be invoked by the kernel. It would certainly be cool to make those a bit richer.

**Comment by ellisonbg** [comment]
Yeah, the regular ipython clear is tied to the terminal. We could hack it to work in the frontend, but then a user would be frustrated if they have a variable named clear...in IPython that namespace ambiguity is handled automatically I think, but in the frontend, it is more difficult. I agree it would be nice to have.

**Comment by ellisonbg** [comment]
@rgbkrk what about a better UI for clearing the cells? We do now have a R click context menu on the console that has that as an option...

**Comment by rgbkrk** [comment]
I want terminal access, since I was treating it the same as using the qtconsole or the ipython console. I think this can be closed as wontfix if you don't want this plugin to handle it clientside.

**Comment by ellisonbg** [comment]
Are there other terminal-ish things you or others would want in this context?

**Comment by rgbkrk** [comment]
Not that I'm aware of, all else seems natural.
