### ISSUE TITLE
need a variable window(like matlab) to visualize global variables, np.array, pd.dataframe or tf.tensor

### ISSUE THREAD

**Issue by cailiang9** [jupyterlab/jupyterlab#2050]
the window shows simple glance(type, shape and top values) of these variables.
Specifficially for pd.dataframe, a column is also needed to show pd.dataframe.describe() info. (a click would be required for very big dataframes to save CPU)

**Comment by blink1073** [comment]
Hi @cailiang9, this is captured by https://github.com/jupyterlab/jupyterlab/issues/443.
