### ISSUE TITLE
Border rendering issue in input cells

### ISSUE THREAD

**Issue by eskirk** [jupyterlab/jupyterlab#2053]
Looking through an old notebook, I noticed some borders that were being clipped/not rendered correctly. Not too sure what the cause here might be, but I felt like this was worth taking a look at. 

Issue in question:
<img width="933" alt="screen shot 2017-04-18 at 12 21 37 pm" src="https://cloud.githubusercontent.com/assets/7052378/25149062/f56f4d8c-2431-11e7-9d65-21188993b573.png">

Inspected: 
<img width="959" alt="screen shot 2017-04-18 at 12 22 42 pm" src="https://cloud.githubusercontent.com/assets/7052378/25149073/fde53756-2431-11e7-9b2a-df543c16d33f.png">

**Comment by jasongrout** [comment]
Can you share your browser/version and OS, and can you double-check to make sure your zoom level is 100% (or actual size)?

**Comment by sccolbert** [comment]
I see this issue on chrome quite often with 1px borders. It has to do with how chrome handles sub-pixel rendering when some internal value is computed as a fraction of a pixel.

**Comment by sccolbert** [comment]
I would see if it happens on Firefox, which handles this subpixel rendering better. If Firefox is okay, I'd recommend not wasting any time trying to fix this for now.

**Comment by eskirk** [comment]
@jasongrout oh wow... my zoom was at 90% for some reason. Looking at it again with 100% zoom and it renders perfectly normally.

**Comment by sccolbert** [comment]
@eskirk Just to humor me, can you check on Firefox with 90% zoom and see what happens?

**Comment by eskirk** [comment]
@sccolbert renders perfectly at all zoom levels 
<img width="710" alt="screen shot 2017-04-18 at 4 32 25 pm" src="https://cloud.githubusercontent.com/assets/7052378/25157210/a4062ef2-2454-11e7-868c-c7dfa43fce0b.png">
<img width="727" alt="screen shot 2017-04-18 at 4 32 05 pm" src="https://cloud.githubusercontent.com/assets/7052378/25157206/a0cbca58-2454-11e7-8c63-03221bb923aa.png">
<img width="529" alt="screen shot 2017-04-18 at 4 32 11 pm" src="https://cloud.githubusercontent.com/assets/7052378/25157209/a2ddf4ce-2454-11e7-9868-6f833c393f5d.png">

**Comment by sccolbert** [comment]
Cool. Thanks. Seems like this *is* the chrome sub-pixel issue. Just happens to be due to zoom in this case. I'm going close this since it's not really something we have control over.

**Comment by jasongrout** [comment]
If this isn't fixed in Chrome already, [this upcoming change](https://chromestatus.com/feature/4651561863610368) which deals with rounding of border widths in Chrome may help.
