### ISSUE TITLE
List of context menus to add to JupyterLab

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2054]
We now have universal context menus and it is really easy to add them to different parts of the UI. This issue is to list what commands/selectors should we add context menus for and to discuss the criteria for doing so. @eskirk is going to work on this...

Let's edit this issue to 

* Notebook
    * Undo Cell Operation
    * Redo Cell Operation
* Notebook+Cell
    * Clear Output
* File editor
* Terminal
* Console

**Comment by eskirk** [comment]
* Console
  * Clear Cells 
  * Restart Kernel
* Terminal
  * New Terminal
  * Refresh Terminal

**Comment by ellisonbg** [comment]
I think we are covered on this front, closing.
