### ISSUE TITLE
Appveyor builds are failing due to Tornado 4.5

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2057]
"No supported color terminal library"

https://ci.appveyor.com/project/jupyterlab/jupyterlab/build/1.0.1719#L253

**Comment by blink1073** [comment]
cf https://github.com/tornadoweb/tornado/issues/2013

**Comment by bdarnell** [comment]
There's a fix for this in the master branch of https://github.com/tornadoweb/tornado; I'm planning to release it as Tornado 4.5.1 tomorrow.

**Comment by blink1073** [comment]
Thanks!  We'll put the pitchforks down for now ;).

**Comment by blink1073** [comment]
Verified that the error is gone, thanks!
