### ISSUE TITLE
Refactor the main menu plugin

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2059]
We need to update the main menu to allow plugins to contribute content to the same menu.  Plugins should own all of the content that they add (we aren't trying to join sub-menus).

**Comment by ellisonbg** [comment]
Not sure we want to add this as a generic feature of menus. My initial thought is that a given extension could provide an API for extending its menu if it chooses. But I suppose even then we would want such APIs to be consistent across plugins. Thoughts?

**Comment by blink1073** [comment]
Let's wait and talk about this at the meeting tomorrow.

**Comment by blink1073** [comment]
Closing in favor using the existing approach for menus and letting plugins expose an entry point as they see fit.
