### ISSUE TITLE
Add a View top-level menu

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#2062]
This menu could include:

1. Hiding/displaying certain elements like the sidebar
2. Toggling single document mode
3. an option to tile all the tabs into separate tabpanels
4. an option to condense all tabs into a single tabpanel

**Comment by blink1073** [comment]
Predicated on #2059.

**Comment by blink1073** [comment]
Actually, all of the above could be provided by the `application-extension`.

**Comment by jasongrout** [comment]
Closing in deference to the broader discussion at #3103
