### ISSUE TITLE
Tries to write system files

### ISSUE THREAD

**Issue by flying-sheep** [jupyterlab/jupyterlab#2063]
[`_get_config`](https://github.com/jupyterlab/jupyterlab/blob/f3c9838676eb7276069d04d4745d606d17307538/jupyterlab/commands.py#L222-L223) tries to write to [`_get_config_dir()`](https://github.com/jupyterlab/jupyterlab/blob/f3c9838676eb7276069d04d4745d606d17307538/jupyterlab/commands.py#L251-L252), which uses [`ENV_CONFIG_PATH`](https://github.com/jupyter/jupyter_core/blob/ebba39caec9e743f99d3ba8f6eb21c743dda99e0/jupyter_core/paths.py#L177), which isn’t a writable location.

why don’t you use <code>[jupyter_config_path](https://github.com/jupyter/jupyter_core/blob/ebba39caec9e743f99d3ba8f6eb21c743dda99e0/jupyter_core/paths.py#L180)()[0]</code>?

**Comment by blink1073** [comment]
We specifically want the config and install for JupyterLab to be scoped to an environment.  What we could do is fall back on the `user` if `sys-prefix` is not available.  

@jasongrout, thoughts?

**Comment by jasongrout** [comment]
CCing @minrk and @takluyver, who might have more to say about how a config system should work.

I think it makes sense to fall back to user, but that also introduces a world of pain when you have shadowing, as we've seen with the notebook extension mechanism.

**Comment by blink1073** [comment]
Proposed solution:

- Add a `lab_config_dir` trait and alias (e.g. `jupyter lab --lab-config-dir=foo`) to all of the lab application entry points
- Use only this directory for configuration (no merging)

**Comment by flying-sheep** [comment]
how can that be set globally once?

every linux distribution will eventually want to install jupyterlab in a way that just works.

**Comment by blink1073** [comment]
Because it is using traitlets to get the value, it can be specified in `jupyter_notebook_config.json` under `LabApp: lab_config_dir`, e.g.:

```
$ cat ~/.jupyter/jupyter_notebook_config.json
{
  "LabApp": {
    "lab_config_dir": "foo/bar"
  },
  ...
}
``

**Comment by blink1073** [comment]
Drat, the above doesn't cover the lab extension apps...

**Comment by sccolbert** [comment]
It does if they subclass `LabApp`, or they can set their own...

**Comment by blink1073** [comment]
no, I mean literally `LabExtensionInstall`, etc.

**Comment by sccolbert** [comment]
what about a traitlets configurable class named `JLabConfig`, that you instantiate when you need it?

**Comment by blink1073** [comment]
We previously had a `LabConfig` class

**Comment by blink1073** [comment]
And we could offer an alias for the individual apps so `--lab-config-dir=` would map to `LabConfig.lab_config_dir`.  Sweet, thanks.

**Comment by minrk** [comment]
> i’ve never seen /usr/env/* (which is jupyterlab’s default)

It doesn't use this. It uses `sys.prefix`.

> We specifically want the config and install for JupyterLab to be scoped to an environment.

This is okay for environments, but it's generally not when conda and/or virtualenv aren't being used. Detecting that is hard to do rigorously (`VIRTUAL_ENV`, `CONDA_DEFAULT_ENV` env give you a 'probably in an env' answer).

> What we could do is fall back on user if sys-prefix is not writable.

This is initially appealing, but one doesn't generally want behavior to change based on permissions. e.g. if a user forgot to `sudo`, you wouldn't want it to succeed in a different task than requested, it should probably fail (perhaps with a `did you mean --user?` error.

@blink1073 it's one thing to have env-preferring defaults, but are all of the system-wide and user-specific paths still *read*?

One use case question: If I'm a non-admin user on a system with system-wide JupyterLab with a few installed extensions (to which I don't have write access). How would I go about adding one extension to the existing set for just me?

**Comment by flying-sheep** [comment]
> It doesn't use this. It uses `sys.prefix`.

which is `/usr`, not `/`. `/usr/share` is correct, `/usr/etc` is either incorrect or a weird thing that nobody does.

> If I'm a non-admin user on a system with system-wide JupyterLab with a few installed extensions (to which I don't have write access). How would I go about adding one extension to the existing set for just me?

that and similar questions are usually answered by:

* have defaults
* have an (optional) system/environment-wide config falling back to the defaults
* have a (optional) user config falling back to the system/environment config (in a smart way, e.g. extension lists get merged, and each extension has an `enabled` config key that can be overridden.

a running application should never try to access its system configuration (i.e. if you change a setting via GUI, `/etc/` may not be touched). there may be specific configuration scripts that can edit it (e.g. like `jupyter nbextension enable`)

**Comment by minrk** [comment]
> which is /usr, not /. /usr/share is correct, /usr/etc is either incorrect or a weird thing that nobody does.

Yup, sys.prefix is rarely, if ever, the right thing to use for system-wide Python (it can have a variety values on macOS, ~all of which are wrong, for instance). In some cases, it should even be avoided for a system-wide anaconda install.

Making sys-prefix the default behavior is still an okay choice, though. It solves common headaches for conda/virtualenv users with the current setup. But care must be taken to ensure that non-env installs do still work sensibly.

> i’d propose that jupyterlab should know if it’s in a development/environment directory or a global/system install

This would be ideal, but it's ~impossible to rigorously establish this fact in all cases, so the user must be able to state it somehow.

For instance:

```python
def in_env():
    """Am I in a conda or virtual env?"""
    for key in ('CONDA_PREFIX', 'VIRTUAL_ENV'):
        # Compare env with sys.prefix because env may be active while another
        # Python is instantiated explicitly.
        if os.getenv(key) == sys.prefix:
            return True
    return False
```

would detect *explicitly activated envs*. It wouldn't catch the common case of the conda root env on PATH, but not activated explicitly via `source activate root`. It would also fail to identify [pyenv](https://github.com/pyenv/pyenv), where sys.prefix is also logically the right thing to use. One or two of these cases may also get explicit checks (e.g. if `sys.prefix.startswith($HOME)` is a pretty good indicator of a prefix install, but might not always be right)

So one option is:

1. if an env is detected, use sys.prefix
2. otherwise, do system/user behavior (similar to other Jupyter applications)
3. provide a `--sys-prefix` or `--env` flag for cases where there is an env that is not detected for whatever reason
4. possibly also `--user` and `--system` flags for explicit deviations from default

**Comment by flying-sheep** [comment]
`if sys.base_prefix == sys.prefix`?

**Comment by blink1073** [comment]
JupyterLab is fundamentally different from the other Jupyter applications now in that there is only one set of config/runtime that makes sense for a given environment, because it is a compiled application.  Therefore I think it is imperative that we use `sys.prefix` by default.  I think it is important enough that an environment variable should be used to override the behavior.

**Comment by blink1073** [comment]
fwiw, there is no `sys.base_prefix` in my root Mac environment (`sys.prefix` is `/System/Library/Frameworks/Python.framework/Versions/2.7`).

**Comment by blink1073** [comment]
To clarify, before there was a root application that was in the user's Python environment, and other artifacts could be combined with it at run time.  Now there is a separate compiled application that includes the artifacts, which are determined by the config.  We need all of the commands `build/clean/install/link` to deterministically affect the same runtime directory, which should be shared with any other environments.

**Comment by blink1073** [comment]
(edited the above comment for those following along by email)

**Comment by minrk** [comment]
@blink1073 makes sense. I'm okay with env-preferring defaults, I just want to make sure the other cases are reasonably covered. For instance:

1. how to do system-wide installation where `sys.prefix` is `/System/...` or `/usr`, but installation goes in the 'normal' system-wide user-managed location, such as `/usr/local`?
2. how to do a user installation of an extension when JupyterLab is installed system-wide and not user-writable?

What I think probably isn't okay is if an environment variable is required to *load* a system-wide install of JupyterLab where sys.prefix is not the appropriate place to put these things. If the path is recorded somewhere that will be looked up, that should be covered. But like the files themselves, that lookup needs to not be in sys.prefix.

**Comment by blink1073** [comment]
There is a fall-back mode where if it doesn't find a compiled app it will use the base install, so if the user only uses `jupyter lab` and not any of the other commands, they will always be using the core install.  It is only when they run `build/clean/install` etc. that write-ability becomes a concern.  In that case the environment variable would be used point to the appropriate config location if `sys.prefix` is not the correct one.

**Comment by blink1073** [comment]
And this would provide a clean, straightforward directive to users: if not using a virtual env or conda env, use the `JUPYTERLAB_CONFIG_DIR`, for which a recommended location is `~/.jupyter/lab`

**Comment by flying-sheep** [comment]
> It is only when they run build/clean/install etc. that write-ability becomes a concern.

idk if i understand you correctly, but running `jupyter lab` will cause write attempts to the config file (see links in the initial comment)

**Comment by flying-sheep** [comment]
> fwiw, there is no sys.base_prefix in my root Mac python install (sys.prefix is /System/Library/Frameworks/Python.framework/Versions/2.7).

oh, jupyterlab still has python 2 support. how unfortunate.

**Comment by blink1073** [comment]
Writing on `jupyter lab` is unintended, that is a bug.  Fair point about Python 2 support, the notebook is scheduled to drop it in its next major release, care to open an issue suggesting that we release beta with Python 3 support only?

**Comment by minrk** [comment]
The write-on-start should be fixed by #2075, I think.

@blink1073 Given that JupyterLab's first 'stable' release is still a bit off, I think being Python 3-only by the time it's stable is quite reasonable.

**Comment by jasongrout** [comment]
>> fwiw, there is no sys.base_prefix in my root Mac python install (sys.prefix is /System/Library/Frameworks/Python.framework/Versions/2.7).

> oh, jupyterlab still has python 2 support. how unfortunate.

Would it be possible to make this compatible with python 2? For example, https://github.com/roynielsen17/pyinstaller-snapshot/blob/master/PyInstaller/compat.py#L147

**Comment by blink1073** [comment]
Agreed with the write-on-start fix, thanks Min!

The pyinstaller check returns `False` for my conda env that is set by prepending `PATH`.

**Comment by flying-sheep** [comment]
> Would it be possible to make this compatible with python 2? For example, https://github.com/roynielsen17/pyinstaller-snapshot/blob/master/PyInstaller/compat.py#L147

ah nice, in this case there’s no reason not to do this. except if the maintainers here want to sunset python 2 support anyway (but all of this is beyond the scope of this issue)

**Comment by blink1073** [comment]
I'm starting to think that the is_venv check is good enough, defaulting to user otherwise, and still allowing for an environment variable override.  If the env is added to PATH instead of activated, it is not unreasonable for that to be the user level.

**Comment by blink1073** [comment]
@minrk, how do you feel about the following:

Add a `JUPYTER_IN_ENV` flag that overrides the default preference to `user` in [jupyter_core](https://github.com/jupyter/jupyter_core/blob/master/jupyter_core/paths.py) in favor of `sys-prefix`, without clobbering any other JUPYTER environment variables that were explicitly set. 

We explicitly set this when activating the `jupyter_core` conda package:  https://conda.io/docs/using/envs.html#saved-environment-variables

This would mean that the only use case that isn't doing a sensible thing by default is an explicitly activated virtual environment, which could be handled using something like [autoenv](https://github.com/kennethreitz/autoenv).

**Comment by minrk** [comment]
It seems reasonable, especially if you have the `in_env` detection for installation above, and allow this env variable to override it. Are you proposing that anything change in jupyter_core, though? Core doesn't have anything about installation locations, just where to find each category of file.

**Comment by blink1073** [comment]
Yes, I meant that the logic in `jupyter_core.paths` should take into account the above when determining the order of the paths.  For example, `jupyter_config_dir()` would start with `sys-prefix` instead of `user` level config unless `JUPYTER_CONFIG_DIR` were set.

**Comment by blink1073** [comment]
Actually, we can use the `is_venv` check above in `jupyter_core.paths` since that is already the de facto set of env variables.

**Comment by minrk** [comment]
Ah, so switching Jupyter's own load priority when in an env. In that case, what I would probably do is slightly different: add a dedicated flag/env (e.g. `JUPYTER_NO_USER_CONFIG`) for disabling `--user` files, rather than still loading them, but with different priority. Keeping the same files in a different priority sounds like it might be trouble.

**Comment by blink1073** [comment]
And that flag would be set using the conda environment variables approach above?

**Comment by minrk** [comment]
I'm torn. For me, disabling user config is something I would ~never want, regardless of envs.  It's exclusively this extension stuff that I want to be per-env because it's tied to installation. None of the rest of my config is env-specific. But I also know there are people who feel the opposite - that creating an env should ignore the entire world outside the env and be pristine. I'm really not sure what the best combination of defaults and overrides would be.

**Comment by blink1073** [comment]
I think we should discuss in person at the dev meeting.  I'm going to mark this as 1.0 since we have a workable solution for now.

**Comment by blink1073** [comment]
I'm calling this closed as JupyterLab detects when it is installed as `--user` and we have environment variable overrides.
