### ISSUE TITLE
Application doesn't build in dev mode without -e option

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2082]
`pip install .` (without `-e`) doesn't run our npm build wrappers (we're missing something in our cmdclass).   The contributing guide specifies using the `-e` flag for local installs, but we should support this use case as well.

**Comment by jasongrout** [comment]
I think this means that the conda-forge package will also be broken.

**Comment by jasongrout** [comment]
Actually, never mind. The pip package should hopefully have the build artifacts already.

**Comment by vidartf** [comment]
We had/have the same problems with nbdime. Is it maybe related to the fact that the work is being done in a different (temporary) directory?

**Comment by blink1073** [comment]
As part of #2098, we are going to separate the npm and python workflows, since there will be distinct "dev" and "release" modes of operation.
