### ISSUE TITLE
Cursor position in Markdown cell lost if at the end of the cell

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2091]
To reproduce:

1. Create a markdown cell and type into it
2. Leave the cursor at the end of the cell
3. Render the cell using shift+enter
4. Double click on the cell the edit it again
5. The entire text is highlighted

Now repeat this process, but before rendering the markdown, move the cursor to a location in the middle of the text. When you re-edit the cell, that position is remembered.

Expected behavior:

* Cursor position should be remembered always
* If, for some reason, there isn't a cursor position, put the cursor at the beginning or end.

**Comment by blink1073** [comment]
I tried following the outlined steps, but I wasn't able to reproduce.  I double clicked on the cell and then hit "Enter" to trigger edit mode:

![markdown_cell_position](https://cloud.githubusercontent.com/assets/2096628/25582788/98f9831a-2e54-11e7-88fc-dfea46c76f7f.gif)

**Comment by blink1073** [comment]
To be safe, I'll add a check in `InputAreaWidget.showEditor` in a forthcoming PR.

**Comment by blink1073** [comment]
Closing based on discussion in #2130.
