### ISSUE TITLE
Ability to create a console which shares the kernel with a notebook

### ISSUE THREAD

**Issue by joonro** [jupyterlab/jupyterlab#2092]
Hi,

I'm not sure if this is already possible (please let me know if it is), but I think it would be great if it is possible to create a console which shares its kernel with existing notebook. 

That is, just like `%qtconsole`, but instead of having a dedicated window for the qtconsole, it would be great if jupyterlab opens a new console, so we can put the notebook and the console side-by-side.

In writing code, I always have a qtconsole open with `%qtconsole`, and go back and forth between the notebook and qtconsole so I can quickly check my code. I think it will be very convenient to be able to do this.

**Comment by blink1073** [comment]
Hi @joonro, this was supposed to be available as a command palette command, but there is a bug in the current release.  #2097 has the fix.

**Comment by joonro** [comment]
Thank you so much for the quick fix. Looking forward to trying it out!

**Comment by joonro** [comment]
Hi - 

I just tried this (installed  `jupyterlab 0.20.2-py35_0 conda-forge`), and I have a couple of things:

1. I was actually talking about a console which shares its kernel with a notebook, not editor. That is, a `%qtconsole` equivalent, but the console showing up as a new tab. I think this will be very useful for quickly trying out things.
2. Also, with the editor and `Create Console for Editor`, I got the new console, but it seems `Run Code (Shift+Enter)` does not do anything - I assumed that it will run the code on the cursor line in the console.

Thank you so much!

(I wanted to re-open the issue but it seems I cannot do this - please let me know if you want me to open a new issue.)

**Comment by blink1073** [comment]
Ah, apologies for mis-reading.  We do not yet have a `%qtconsole` equivalent.  The `Run Code` command currently only uses selected text.

**Comment by ellisonbg** [comment]
I think the way to implement this is through a context menu item on the notebook div that is titled "Open Console for this Kernel"

**Comment by ellisonbg** [comment]
Fixed in master by #2189

**Comment by joonro** [comment]
Thank you so much for implementing this so quickly. I think this will be very useful for both writing code and teaching Python to students. I'm looking forward to trying it out!
