### ISSUE TITLE
Launching a code console is broken on master

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#2099]
When I click on `Code Console` in the launcher side panel, it errors with `TypeError: Can't add property basePath, object is not extensible.`.

Creating a code console from the landing works as expected.

**Comment by ian-r-rose** [comment]
The problem here is that the default `args` object from the phosphor command registry is the singleton `JSONExt.emptyObject`, which cannot be edited. Either phosphor should return an extensible `Object`, or recipients of `args` from the command registry should make a copy before extending them.

cc @sccolbert

**Comment by sccolbert** [comment]
Command args should be treated as immutable. Code that is editing `args` is wrong. This assumption is not currently documented in Phosphor, but it should be..

**Comment by sccolbert** [comment]
Here's the offending line:
https://github.com/jupyterlab/jupyterlab/blob/master/packages/console-extension/src/index.ts#L215

cc @afshin

**Comment by afshin** [comment]
Sorry about that!
