### ISSUE TITLE
404 plot jupyterlab

### ISSUE THREAD

**Issue by Lawiet** [jupyterlab/jupyterlab#2101]
Good, 
I´m try plot graphics from data frame but trow error

This log
> [15:46:42.904 jupyter kernelmanager:222] activity on 460d73ea-00ba-482b-bb10-94e1cb88f044: status
> [15:46:42.910 jupyter auth:286] Allowing whitelisted Hub user jupyter
> [15:46:42.913 jupyter log:47] 200 GET /user/jupyter/api/contents/?content=1&1493064977371 (106.31.79.40) 3.65ms
> [15:46:42.914 jupyter kernelmanager:222] activity on 460d73ea-00ba-482b-bb10-94e1cb88f044: execute_input
> [15:46:42.983 jupyter kernelmanager:222] activity on 460d73ea-00ba-482b-bb10-94e1cb88f044: stream
> [15:46:44.555 jupyter log:47] 200 GET /user/jupyter/static/components/MathJax/jax/output/HTML-CSS/fonts/STIX-Web/fontdata.js?rev=2.6.0 (106.31.79.40) 2.16ms
> [15:46:44.566 jupyter auth:286] Allowing whitelisted Hub user jupyter
> [15:46:44.566 jupyter handlers:210] Using contents: services/contents
> [W 2017-04-24 15:46:44.569 jupyter log:47] 404 GET /user/jupyter/yourfile.html (106.31.79.40) 4.10ms referer=https://106.33.101.86/user/jupyter/lab?
> [15:46:44.587 jupyter log:47] 200 GET /user/jupyter/static/components/MathJax/extensions/Safe.js?rev=2.6.0 (106.31.79.40) 1.71ms
> [15:46:44.653 jupyter log:47] 200 GET /user/jupyter/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=9b2c8d3489227115310662a343fce11c (106.31.79.40) 1.91ms
> [15:46:44.658 jupyter log:47] 200 GET /user/jupyter/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=7afb461de36accb1aa133a1710f5bc56 (106.31.79.40) 0.74ms
> [15:46:44.661 jupyter log:47] 200 GET /user/jupyter/static/style/style.min.css?v=29c09309dd70e7fe93378815e5f022ae (106.31.79.40) 2.07ms
> [15:46:44.671 jupyter log:47] 200 GET /user/jupyter/static/components/proptypes/index.js?v=c40890eb04df9811fcc4d47e53a29604 (106.31.79.40) 1.03ms
> [15:46:44.672 jupyter log:47] 200 GET /user/jupyter/static/components/preact-compat/index.js?v=d376eb109a00b9b2e8c0d30782eb6df7 (106.31.79.40) 0.94ms
> [15:46:44.678 jupyter log:47] 200 GET /user/jupyter/custom/custom.css (106.31.79.40) 1.08ms
> [15:46:44.680 jupyter log:47] 200 GET /user/jupyter/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe (106.31.79.40) 1.08ms
> [15:46:44.683 jupyter log:47] 200 GET /user/jupyter/static/components/preact/index.js?v=5b98fce8b86ce059de89f9e728e16957 (106.31.79.40) 1.06ms
> [15:46:44.685 jupyter log:47] 200 GET /user/jupyter/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce (106.31.79.40) 1.22ms
> [15:46:44.940 jupyter log:47] 200 GET /user/jupyter/static/components/jquery/jquery.min.js?v=20170424154224 (106.31.79.40) 2.52ms

Image 404 Error
![sin titulo](https://cloud.githubusercontent.com/assets/11633133/25356896/f776ee32-2909-11e7-95b3-fea753bc7ff2.png)

Config notebook json

> {
>   "load_extensions": {
>     "jupyter-spark/extension": true,
>     "jupyter-js-widgets/extension": true
>   }
> }

Config jupyter notebook json

> {
>   "NotebookApp": {
>     "nbserver_extensions": {
>       "nb_anacondacloud": true,
>       "jupyter_spark": true,
>       "jupyter_nbextensions_configurator": true,
>       "nbpresent": true,
>       "nb_conda": true,
>       "jupyterlab": true
>     }
>   }
> }

Config jupyter notebook py

> c.NotebookApp.base_url = '/lab'
> c.NotebookApp.file_to_run = '/Data/jupyter/{username}/notebook'

Config jupyterhub py

> c.Spawner.default_url = '/user/{username}/lab'
> c.Spawner.notebook_dir = '/Data/jupyter/notebook/{username}/notebook/'

Please help me! Thanks

**Comment by blink1073** [comment]
Hi @Lawiet, it looks like that is a plotly renderer for the the R kernel?   I suspect it will require https://github.com/gnestor/jupyterlab_plotly, but it has not yet been updated to be compatible with the new JupyterLab extension system (released last week).

**Comment by blink1073** [comment]
Original discussion in https://github.com/jupyterlab/jupyterlab/issues/1188.

**Comment by jasongrout** [comment]
Closing as answered since there was no response. Please add a new comment if you still need help.
