### ISSUE TITLE
Code Refactoring facilities

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2104]
Migrated from https://github.com/jupyter/notebook/issues/163.

@InonS writes:

One of the most significant features still missing, for example: Rename (context-sensitive 'replace all').
Other, less used facilities, such as Generate (getters and setters, etc.)

I've been using Jupyter, as it came with my IPython installation, but I whole-heartedly support the decision to separate the projects. Until Jupyter is able to keep up, and hopefully lead, I'm tempted to IDEs with IPython notebook integration such as Spyder, Ninja-IDE, or PyCharm (Community edition).

**Comment by InonS** [comment]
Context-sensitive rename may be hard, but generating a @property should be as simple as key-binding and a couple of templates (only getter, getter & setter, etc.). Low hanging fruit...

**Comment by ellisonbg** [comment]
Also related to #2163

**Comment by blink1073** [comment]
This work is being undertaken in https://github.com/krassowski/jupyterlab-lsp
