### ISSUE TITLE
How to trigger notebook level actions within cell widget

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2113]
I am working on adding the notion of a cell header and footer. These are places for optional UI such as buttons that perform per-cell actions. I talked to @blink1073 today about how to build this and there are two main questions:

* How to allow folks (including ourselves) to customize these areas. For this, it seems pretty clear to use the `IContentFactory` pattern that we have been using so others can pass in custom factories for the header/footer.
* How to wire up interactions with the header/footer to non-cell actions. Example of non-cell actions would be a button to delete the cell or a button to run on the cell. These are actions that the cell itself doesn't know about.

These non-cell actions are typically going to need some context. For many of these things, it would need a handle on the notebook or the session above it. I started to implement this in a manner that saved that context in the header/footer Widget. However, I ran into a difficulty. If the cell changes that context, we would need a way to change the context. For the actions we are going to use, that context is the parent notebook/panel, however it isn't limited to this - other actions may have other context required. The difficulty is that this means the cell is holding its parent notebook/panel through the header/footer. I don't think we want that type of dependency.

The other approach would be to have a signal the cell could fire that would be watched by the notebook.

The reason we need this customizability is that many of these actions are not appropriate all the time. For example, a delete cell button doesn't make sense in the Code Console. Nor does a run cell button on a static view.

Any thoughts on how to trigger these actions in a clean manner?

@blink1073 @sccolbert

**Comment by ellisonbg** [comment]
Just to update folks on the discussions we have been having:

* Use a factory pattern to allow the user of a class to pass in children widget content.
* Have those optional children widgets hold state that allows them to call the higher-level actions.

This was preferred to signal pattern as we would have to decide up front what signal could be fired and the goal with this is complete extensibility.

**Comment by ellisonbg** [comment]
Closing as I think we have answered it.

**Comment by ibqn** [comment]
Can someone please point me to the minimal example (or to the general procedure)  in which is shown how to add something like a button to the header/footer part of the code cell widget and how to trigger actions on that cell? @ellisonbg perhaps?
