### ISSUE TITLE
Invalid name: "@jupyterlab/all-packages" at ensureValidName     when build jupyterlab

### ISSUE THREAD

**Issue by rydeng** [jupyterlab/jupyterlab#2119]
> @ build /home/dry/src/jupyterlab
    > cd packages/all-packages && npm run build
    
    npm ERR! Error: Invalid name: "@jupyterlab/all-packages"
    npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
    npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
    npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
    npm ERR!     at Array.forEach (native)
    npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
    npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:310:33)
    npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:124:33)
    npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:284:48
    npm ERR!     at fs.js:207:20
    npm ERR!     at OpenReq.Req.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:135:5)
    npm ERR! If you need help, you may report this log at:
    npm ERR!     <http://github.com/isaacs/npm/issues>
    npm ERR! or email it to:
    npm ERR!     <npm-@googlegroups.com>
    
    npm ERR! System Linux 3.16.0-30-generic
    npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
    npm ERR! cwd /home/dry/src/jupyterlab/packages/all-packages
    npm ERR! node -v v0.10.25
    npm ERR! npm -v 1.3.10
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/dry/src/jupyterlab/packages/all-packages/npm-debug.log
    npm ERR! not ok code 0
    npm ERR! weird error 1
    npm WARN This failure might be due to the use of legacy binary "node"
    npm WARN For further explanations, please read
    /usr/share/doc/nodejs/README.Debian
    
    npm ERR! not ok code 0
    
    npm ERR! Linux 3.16.0-30-generic
    npm ERR! argv "node" "/usr/local/bin/npm" "run" "build:main"
    npm ERR! node v0.10.25
    npm ERR! npm  v3.8.9
    npm ERR! code ELIFECYCLE
    npm ERR! @ build:main: `npm run build && cd jupyterlab && npm run build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the @ build:main script 'npm run build && cd jupyterlab && npm run build'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the  package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run build && cd jupyterlab && npm run build
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/dry/src/jupyterlab/npm-debug.log
    rebuilding js and css failed
    missing files: ['/home/dry/src/jupyterlab/jupyterlab/build/main.css', '/home/dry/src/jupyterlab/jupyterlab/build/main.bundle.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/dry/src/jupyterlab/setup.py", line 146, in <module>
        setup(**setup_args)
      File "/usr/local/python36/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/python36/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/python36/lib/python3.6/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/usr/local/python36/lib/python3.6/site-packages/setuptools/command/develop.py", line 119, in install_for_development
        self.run_command('build_ext')
      File "/usr/local/python36/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/dry/src/jupyterlab/setupbase.py", line 89, in run
        raise e
      File "/home/dry/src/jupyterlab/setupbase.py", line 82, in run
        self.distribution.run_command('jsdeps')
      File "/usr/local/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/dry/src/jupyterlab/setupbase.py", line 134, in run
        run(['npm', 'run', 'build:main'], cwd=here)
      File "/home/dry/src/jupyterlab/setupbase.py", line 37, in run
        return check_call(cmd, *args, **kwargs)
      File "/usr/local/python36/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['npm', 'run', 'build:main']' returned non-zero exit status 1.

**Comment by rydeng** [comment]
when I build jupyterlab, I get back this error Invalid name: "@jupyterlab/all-packages"

**Comment by blink1073** [comment]
Hi @rydeng, can you please run `npm install` and then `npm run build:main` from the repo root directory and give that output?

**Comment by rydeng** [comment]
Hi @blink1073 when I run the command as you give, I get output as follows:
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'build:main' ]
2 info using npm@3.8.9
3 info using node@v0.10.25
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prebuild:main', 'build:main', 'postbuild:main' ]
6 info lifecycle @~prebuild:main: @
7 silly lifecycle @~prebuild:main: no script for prebuild:main, continuing
8 info lifecycle @~build:main: @
9 verbose lifecycle @~build:main: unsafe-perm in lifecycle true
10 verbose lifecycle @~build:main: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/dry/src/jupyterlab/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
11 verbose lifecycle @~build:main: CWD: /home/dry/src/jupyterlab
12 silly lifecycle @~build:main: Args: [ '-c', 'npm run build && cd jupyterlab && npm run build' ]
13 silly lifecycle @~build:main: Returned: code: 1  signal: null
14 info lifecycle @~build:main: Failed to exec build:main script
15 verbose stack Error: @ build:main: `npm run build && cd jupyterlab && npm run build`
15 verbose stack Exit status 1
15 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
15 verbose stack     at EventEmitter.emit (events.js:98:17)
15 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
15 verbose stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
15 verbose stack     at maybeClose (child_process.js:743:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
16 verbose pkgid @
17 verbose cwd /home/dry/src/jupyterlab
18 error Linux 3.16.0-30-generic
19 error argv "node" "/usr/local/bin/npm" "run" "build:main"
20 error node v0.10.25
21 error npm  v3.8.9
22 error code ELIFECYCLE
23 error @ build:main: `npm run build && cd jupyterlab && npm run build`
23 error Exit status 1
24 error Failed at the @ build:main script 'npm run build && cd jupyterlab && npm run build'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the  package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run build && cd jupyterlab && npm run build
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by blink1073** [comment]
It looks `npm` is complaining that `@jupyterlab/all-packages` itself is an invalid package name.  This could be due to `npm` being < 4.0.  Are you able to upgrade to a newer version?

**Comment by rydeng** [comment]
Hi @blink1073  Thanks I will try it.

**Comment by jasongrout** [comment]
@rydeng - did that resolve the issue?

**Comment by jasongrout** [comment]
Closing since the author did not follow up.
