### ISSUE TITLE
Allow a selection of text in an editor to be run in a kernel or console

### ISSUE THREAD

**Issue by Alcampopiano** [jupyterlab/jupyterlab#2120]
Hello,

Shift+Enter to run a selection from the editor in the console is not working for me. I have linked the editor to the console using "Create Console for Editor". I'm not getting any errors, it's just that nothing happens when I highlight and click Shift+Enter.

I'm on Windows 7 with JupyterLab 0.20.3. 

Would anyone have an idea why this is not working?

**Comment by ellisonbg** [comment]
Hmm, we will need to look at this. IIRC, there was a bug in master with this stuff. @blink1073 will know more

**Comment by Alcampopiano** [comment]
Thanks for having a look. Very excited about the Jupyter Lab project.

**Comment by blink1073** [comment]
I am seeing this as well in the 0.20.3 release.
