### ISSUE TITLE
Right click on the working directory path to copy

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#2122]
It's nice to pop a menu when right clicking on the working directory that allows user to copy the path of the working directory.

**Comment by ellisonbg** [comment]
+1, but we may need to deal with clipboard issues...

**Comment by stephenholtz** [comment]
This is a great idea! Just to be clear would this pop up for both folders and files? Copying the path to a file or to a directory is one of the more obnoxious things to do in both OSX and windows (where an autohotkey script can at least be written).

**Comment by jasongrout** [comment]
The context menu in the file browser now lets us copy sharable links, a download link, or just the path. Please add a comment if that's not enough.
