### ISSUE TITLE
Filebrowser Enhancements

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#213]
- [ ] When sorting, scroll to the most recently selected item.
- [ ] When creating a new item, select the new item and scroll to it.
- [ ] The rename timer should reset when we mouse out of the item node
- [ ] Support type-select - searches for the character typed, strings characters together with a timeout

Migrated from https://github.com/jupyter-attic/jupyter-js-filebrowser/issues/133

**Comment by jasongrout** [comment]
Confirmed this is still an issue.

**Comment by sccolbert** [comment]
Added the sprint friendly tag. This should be a pretty simple call to `scrollIntoViewIfNeeded` on the most recent selected item after sort.

**Comment by rnetro** [comment]
working on this :)

**Comment by rnetro** [comment]
I'm trying to add it to sort in `src\filebrowser\listing.ts`... does that seem right?
https://github.com/jupyter/jupyterlab/blob/941b0b1249f59db7e2e6e9c60b03c17d432540fb/src/filebrowser/listing.ts#L293


Also, that file has `scrollIfNeeded` defined at the bottom... It seems to be doing the same thing as `scrollIntoViewIfNeeded`
Does it matter which one I use?

https://github.com/jupyter/jupyterlab/blob/941b0b1249f59db7e2e6e9c60b03c17d432540fb/src/utils.ts#L89
https://github.com/jupyter/jupyterlab/blob/941b0b1249f59db7e2e6e9c60b03c17d432540fb/src/filebrowser/listing.ts#L1616

**Comment by blink1073** [comment]
Yep!  And `scrollIntoViewIfNeeded` is the new and improved version.

**Comment by rnetro** [comment]
okey dokey
Should I remove `scrollIfNeeded` ?

**Comment by blink1073** [comment]
That would be appreciated ;).

**Comment by rnetro** [comment]
just noticed `scrollIfNeeded` is used in a couple of places with `Private.`
https://github.com/jupyter/jupyterlab/search?utf8=%E2%9C%93&q=scrollIfNeeded

is it okay to switch those over to `scrollIntoViewIfNeeded` ?

**Comment by blink1073** [comment]
Yep!

**Comment by rnetro** [comment]
👍  💯  👍

**Comment by rnetro** [comment]
Still having trouble.. 
It executes (console shows message), but doesn't scrollIntoView when needed... :/

This is what I have in `onUpdateRequest`
![screen shot 2016-07-29 at 11 56 11 am](https://cloud.githubusercontent.com/assets/18707693/17260169/c54ba402-5583-11e6-8a9a-2c17bdbcbd9d.png)

(also, am I supposed to make the whole thing a function?)

Thanks!!

**Comment by blink1073** [comment]
Line 667 should use `this.contentNode` as the scroll node, and line 666 should be looking for `SELECTED_CLASS`.  I'd say leave it inline here.

**Comment by rnetro** [comment]
Okay, I had it as `this.contentNode` before and it still wasn't working but I'll try again

**Comment by blink1073** [comment]
You also might need to use `this.contentNode` as the first argument to `findElement`.

**Comment by blink1073** [comment]
Otherwise you're getting the `this.node` itself.

**Comment by rnetro** [comment]
right. I've tried every variation lol..
It's been a long couple days haha
But I'll switch it back now

**Comment by blink1073** [comment]
You can open `bundle.js` in your Sources in the Chrome Developer Tools, set a debug point on that line, and inspect what nodes you are picking up.

**Comment by rnetro** [comment]
Okay.
When everything is `.contentNode` I'm running into the same issue I saw yesterday.. It does scroll, but it changes which item is selected with every re-sort

so that's why I changed back to `this.node` -- it was less broken because it wasn't doing anything haha

**Comment by rnetro** [comment]
Hm. okay. I have another task I can focus on for now 
Thank you *again* for all your help. 🎆

**Comment by blink1073** [comment]
We needed a guard for when the sort state actually changes, because update gets called for various reasons:

```diff
diff --git a/src/filebrowser/listing.ts b/src/filebrowser/listing.ts
index d3c30db..7fbda96 100644
--- a/src/filebrowser/listing.ts
+++ b/src/filebrowser/listing.ts
@@ -297,6 +297,10 @@ class DirListing extends Widget {
    */
   sort(state: DirListing.ISortState): void {
     this._sortedModels = Private.sort(this.model.items, state);
+    if (this._sortState.key !== state.key ||
+        this._sortState.direction !== state.direction) {
+      this._sortChanged = true;
+    }
     this._sortState = state;
     this.update();
   }
@@ -654,6 +658,15 @@ class DirListing extends Widget {
       this.addClass(SELECTED_CLASS);
     }

+    // If there was a sort, scroll the first selected item into view.
+    if (this._sortChanged) {
+      // Find the first selected item.
+      let node = utils.findElement(this.contentNode, SELECTED_CLASS);
+      Private.scrollIfNeeded(this.contentNode, node);
+      this._sortChanged = false;
+    }
+
+
     // Handle notebook session statuses.
     let paths = items.map(item => item.path);
     let specs = this._model.kernelspecs;
@@ -1259,6 +1272,7 @@ class DirListing extends Widget {
   private _inContext = false;
   private _selection: { [key: string]: boolean; } = Object.create(null);
   private _renderer: DirListing.IRenderer = null;
+  private _sortChanged = false;
 }
```

**Comment by ellisonbg** [comment]
Closing as stale. The file browser has evolved a lot from this point. Let's open new issues as we find them.
