### ISSUE TITLE
Annoying cell auto center

### ISSUE THREAD

**Issue by bigquant** [jupyterlab/jupyterlab#2131]
When click on some cell (with long code block), the page auto scrolls (seems to put the code in the center of the page). It's very very annoying.

I'm trying to disable this. Could you tell me which code file to modify? Thanks,

**Comment by blink1073** [comment]
Hi @bigquant, we're tracking this in https://github.com/jupyterlab/jupyterlab/issues/2016.

**Comment by blink1073** [comment]
It is a bug that we intend to fix for the beta release.

**Comment by bigquant** [comment]
Thanks. When will we get the beta release?
