### ISSUE TITLE
Add support for bookmarks

### ISSUE THREAD

**Issue by hadim** [jupyterlab/jupyterlab#2138]
It would be nice to have such a feature. Or at least being able to specify the folder path in the URL ? (maybe it's already possible)

**Comment by blink1073** [comment]
Hi @hadim, what do you mean by the folder path in the URL?  As in, the starting folder of the file browser, the path to an open document, etc.?

**Comment by hadim** [comment]
I was thinking about a way to specify a folder or file directly in the URL path. For example with Jupyter notebook you bookmark this kind of URL http://127.0.0.1:8888/tree/Code/notebooks/Sandbox.

It's very convenient when you a lot of different folders containing notebooks. Maybe such a path could be passed in the URL such as : http://127.0.0.1:8888/lab?path=Code/notebooks/Sandbox. What do you think ?

Of course it's relative to the path where you started jupyter.

**Comment by blink1073** [comment]
We're discussing the launch URL part in https://github.com/jupyterlab/jupyterlab/issues/1075.

**Comment by hadim** [comment]
Perfect. Thanks.

**Comment by InonS** [comment]
@hadim maybe you should close this issue, then?
