### ISSUE TITLE
Feature Request: Notebook navigation bookmarks

### ISSUE THREAD

**Issue by InonS** [jupyterlab/jupyterlab#2145]
Something along the lines of PDF bookmarks, which will allow me to jump to given "anchor" locations in the notebook. This is already done in Markdown documents, for example.

**Comment by blink1073** [comment]
Hi @InonS, there is work underway to accomplish this in https://github.com/jupyterlab/jupyterlab/pull/1945, tracked as an issue in https://github.com/jupyterlab/jupyterlab/issues/1932.
