### ISSUE TITLE
Improve warning message when attempting to delete directory

### ISSUE THREAD

**Issue by sgornick** [jupyterlab/jupyterlab#2146]
If you try to delete a directory the error message is:

"File Delete file"

Would there be a more informative message that could go here?

There is a related issue, #835, which requests that this delete should successfully complete the task if the directory was empty.    So if that gets implemented, this issue is only regarding the error message if the directory was not empty.

**Comment by blink1073** [comment]
Ha, seems like a reasonable message to me :wink:
