### ISSUE TITLE
Different behaviour in in folder, notebook and text file creation

### ISSUE THREAD

**Issue by prathamatic** [jupyterlab/jupyterlab#2149]
I am using Jupyter Lab version - 0.16.2.

1. Opne Jupyterlab notebook 
2. Click on create folder - it will create folder without any prompt 
3. Click on create notebook - it will open pop up to take filename
4. Click on create text file - it will open pop up to take filename 

Expected Behaviour: 

1. When user clicks on create folder, open pop up to take folder name

**Comment by prathamatic** [comment]
Am in alone here? No one responding?

**Comment by ellisonbg** [comment]
Nope you are not alone, a number of us are traveling this week so our development time is limited. I probably agree with you the we should provide a way to rename the folder on creation. Remember, jupyterlab is not yet released, so patience is appreciated :-)

**Comment by prathamatic** [comment]
Apologies!!  I didn't know about your travel plan!! 
Thanks for your response. I am all Yoda when it come to patience :-)

**Comment by ellisonbg** [comment]
We have refactored all of this and are mostly settled on the design of it. Please test out the latest behavior and open a new issue if you find anything related to this.
