### ISSUE TITLE
tricky $PATH issue

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#2158]
It seems to me that the $PATH env variable is messed up when the CentOS image is used.
```
/bin:/sbin:/bin:/usr/sbin:/usr/bin
```
1. The $PATH is correct when the Ubuntu image is used.
2. The $PATH is correct when Jupyter Notebook is used.

**Comment by blink1073** [comment]
Hi @dclong, was this intended for jupyterhub or docker-images?  If not, can you provide more context?

**Comment by dclong** [comment]
@blink1073 
I don't think it's an issue of the docker image. The env variable $PATH looks good in a shell created by `docker exec -it contain_name /bin/bash`. I verified that this issues happens in Jupyter Notebook too, so it's probably a issue inherited from Jupyter Notebook.

**Comment by blink1073** [comment]
Agreed, closing in favor of https://github.com/jupyter/notebook/issues/2495.
