### ISSUE TITLE
Split default-theme into multiple packages

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2165]
We have a `default-theme` that contains the theme assets (icons, images), and light/dark theme CSS variables. This layout is going to make is really difficult to build custom themes. We should split it into packages:

* `theme-assets` = everything but the variables.css
* `theme-light` = the light theme
* `theme-dark` = the dark theme

@blink1073 I am thinking we should also have each individual package throw its CSS on the page separately?

**Comment by blink1073** [comment]
That sounds good.  We can adopt the convention that an extension in JupyterLab core imports its own style.
