### ISSUE TITLE
Session shutdown fails if running behind proxy (code 400 bad request)

### ISSUE THREAD

**Issue by AlexTugarev** [jupyterlab/jupyterlab#2182]
If running behind a proxy like nginx, shutdown of sessions fails because DELETE request contains payload. I'm not sure about when this change was introduced, but in earlier versions DELETE requests for session shutdown did not contain payload.

I seems like it depends on protocol implementation, but google search reveals that other servers also reject DELETE with payload. Cf. https://tools.ietf.org/html/rfc7231#section-4.3.5

> A payload within a DELETE request message has no defined semantics;
   sending a payload body on a DELETE request might cause some existing
   implementations to reject the request.

**Comment by blink1073** [comment]
Thanks for the report!  It looks like we need to be more selective in forcing there to be a body.  I am in the midst of refactoring services and will take this into account.

**Comment by AlexTugarev** [comment]
Oops! I should have refreshed browser. 

I see, as `ServerConnection` will replace `ajaxRequest`. I'll try to close my PR.
