### ISSUE TITLE
tour page: fast scrolling behaviour 

### ISSUE THREAD

**Issue by lincolnfrias** [jupyterlab/jupyterlab#2186]
Scrolling in the about page is a bit awkward in the about page (v0.21.0).

It is a very minor issue, just to let you know. Feel free to close this.
I am happily using jupyperlab the whole morning.

**Comment by blink1073** [comment]
Thanks for the report, happy you are enjoying it!

**Comment by ellisonbg** [comment]
Closing as we have deleted the About page in favor of a unified FAQ/About

**Comment by ellisonbg** [comment]
See #1621
