### ISSUE TITLE
Cannot run Jupyter lab subcommands from root

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2208]
This is due to https://github.com/jupyter/notebook/issues/2375, which is fixed in Notebook master in https://github.com/jupyter/notebook/pull/2421.

**Comment by blink1073** [comment]
@gnestor, is it feasible to backport that fix to 4.3 and 5.0?

**Comment by blink1073** [comment]
Otherwise we'd have to override `start()` and call `JupyterApp.start(self)`, then `NotebookApp.start(self)`, or move our subcommands to another namespace.

**Comment by gnestor** [comment]
@blink1073 Sorry for the silence on this one! Sure, we can backport https://github.com/jupyter/notebook/pull/2421. Is this still needed?

**Comment by blink1073** [comment]
Perhaps just for 4.x since 5.1 is coming soon?

**Comment by gnestor** [comment]
This involved applying a couple different patches:

* https://github.com/jupyter/notebook/pull/1115
* https://github.com/jupyter/notebook/pull/1128
* https://github.com/jupyter/notebook/pull/2421

Check out https://github.com/jupyter/notebook/commit/2c96ad2d42b65d233afb60ed004b5bd787199d85 and please confirm that it's working as expected :+1:

**Comment by blink1073** [comment]
The error was reported on gitter, I don't have a Linux setup to test against, but the commit looks good to me.

**Comment by gnestor** [comment]
I re-ran the build and it passed :+1:

**Comment by blink1073** [comment]
This was fixed in Notebook 5.1.
