### ISSUE TITLE
in version 0.21.0, I can not find file lab.html, where is it?

### ISSUE THREAD

**Issue by rydeng** [jupyterlab/jupyterlab#2219]
in version 0.21.0, I can not find file lab.html, where is it? why?

**Comment by jasongrout** [comment]
The actual template is now in jupyterlab_launcher. https://github.com/jupyterlab/jupyterlab_launcher/blob/master/jupyterlab_launcher/index.html

**Comment by jasongrout** [comment]
We separated it so that it would be easier to roll a custom JLab with a custom list of plugins.

**Comment by rydeng** [comment]
@jasongrout  thanks very much.

**Comment by rydeng** [comment]
@jasongrout  so now, how can I run the jupyterlab?

**Comment by rydeng** [comment]
@jasongrout  thanks I run it successfully.
