### ISSUE TITLE
How can I get widgets in notebook toolbar?

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#2227]
Hi, 
I am trying to write a function which removes certain items from the notebook toolbar. I want to use the toolbar.removeItem function but it expects a widget. How can I get all widgets (ToolbarButtons) in the toolbar so that I can remove the one I want from it?
The toolbar.names() function only returns the names of the items.

Regards,
Rishika.

**Comment by sccolbert** [comment]
All classes which are subclasses of `Widget` have a `children()` method which returns a Phosphor iterator over its child widgets. You can use that iterator to find the widget you care about, then set its `parent` to `null` to remove it (which is the proper way to remove *any* widget from the hierarchy):

```typescript
let myWidget = find(toolBar.children(), child => {
  return isTargetChild(child) ? true : false;
});

if (myWidget) {
  myWidget.parent = null;
}
```

**Comment by rsinha25** [comment]
Thanks a lot!

**Comment by sccolbert** [comment]
If you're never-ever going to use that button again, instead of setting `.parent = null`, it's probably better to call `.dispose()` on the button. It will have the same effect, but will additionally free up any resources it may be using.
