### ISSUE TITLE
404s on API calls when username includes @ symbol

### ISSUE THREAD

**Issue by jdavidheiser** [jupyterlab/jupyterlab#2238]
I'm running Jupyterhub with DockerSpawner and an image derived from the most recent Jupyter scipy Docker stacks.  I wanted to play around with Jupyter Lab a bit in my existing environment, but when I try to load the lab interface, ie:
`https://mydomain/user/user@domain.com/lab`
I get the following error message
```
Server Connection Error
File Server Connection Error
```
When I use `docker logs` to inspect what's happening in that user's Docker container, I see 404s on API calls, ie:
`404 GET /user/user%40domain.com/api/contents/?content=...`
If I try to GET the same URL with an @ symbol instead of the encoded version, it works, so
`/user/user@domain.com/api/contents/?content=...`
returns data.  

I'm not sure if this is a lab bug or a hub bug, but filing here since I don't see any of these sorts of problems when working with the normal notebook interface.

**Comment by blink1073** [comment]
Confirmed locally, working on a fix now, thanks!

**Comment by blink1073** [comment]
@jdavidheiser, if you run `pip install jupyterlab_launcher==0.2.9` it should pick up the fix.

**Comment by jdavidheiser** [comment]
I also had to update to the latest version of jupyterlab, but this fix worked!  Very cool!
```
pip install jupyterlab
jupyter serverextension enable --py jupyterlab --sys-prefix
```

**Comment by blink1073** [comment]
Great!
