### ISSUE TITLE
JupyterLab landing page throws javascript error 

### ISSUE THREAD

**Issue by jharonfe** [jupyterlab/jupyterlab#2239]
This issue relates to JupyterLab version 0.21.0. I encounter this error after starting the jupyter lab service and providing my login. The subsequent page fails to render. When I open chrome's (58.0.3029.110) developer tools I see the following error message in the console.

![image](https://cloud.githubusercontent.com/assets/10131212/26212447/71d9fca2-3baa-11e7-8f7b-7698b49b136f.png)

I navigated through the referenced files. I am not sure what "Unexpected token p" this error is referring to. Help on this issue would be appreciated. Thanks.

**Comment by blink1073** [comment]
Hi @jharonfe, can you please click on the `lab:2` link and past here the contents of that html file that the browser loaded?

**Comment by jharonfe** [comment]
@blink1073 Sure. See attached. (Github does not appear to support attaching html files so I labeled this a txt. file.)

[lab.txt](https://github.com/jupyterlab/jupyterlab/files/1011720/lab.txt)

**Comment by blink1073** [comment]
@jharonfe, that didn't seem to work.  You can paste the contents here directly or use pastebin.

**Comment by jharonfe** [comment]
See below. Note that since this is html the markdown interpretation seems to omit line breaks and also omit some nodes.

<!DOCTYPE html>

<html>

<head>
  <meta charset="utf-8">

  <title>JupyterLab Alpha Preview</title>

  
    
      <link href="/lab/main.css" rel="stylesheet">
    
  

  <script id="jupyter-config-data" type="application/json">{
    "ignorePlugins": "[]",
    "appNamespace": "",
    "assetsDir": "c:\program files (x86)\python35-32\lib\site-packages\jupyterlab\build",
    "appName": "JupyterLab",
    "appVersion": "0.21.0",
    "settingsDir": "c:\program files (x86)\python35-32\share\jupyter\lab\settings",
    "terminalsAvailable": "False",
    "devMode": "False",
    "baseUrl": "/",
    "wsUrl": ""
  }</script>

  <link rel="shortcut icon" type="image/x-icon" href="/static/base/images/favicon.ico">

  
  <script src="/lab/main.bundle.js" type="text/javascript" charset="utf-8"></script>
  

  
  <script type="text/javascript" src="/static/components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full,Safe&amp;delayStartupUntil=configured" charset="utf-8"></script>
  
</head>

<body>

<script type="text/javascript">
  function _remove_token_from_url() {
    if (window.location.search.length <= 1) {
      return;
    }
    var search_parameters = window.location.search.slice(1).split('&');
    for (var i = 0; i < search_parameters.length; i++) {
      if (search_parameters[i].split('=')[0] === 'token') {
        // remote token from search parameters
        search_parameters.splice(i, 1);
        var new_search = '';
        if (search_parameters.length) {
          new_search = '?' + search_parameters.join('&');
        }
        var new_url = window.location.origin +
                      window.location.pathname +
                      new_search +
                      window.location.hash;
        window.history.replaceState({}, "", new_url);
        return;
      }
    }
  }
  _remove_token_from_url();
</script>

</body>

</html>

**Comment by blink1073** [comment]
Ah, the issue is the Windows file paths in there.  Can you please try running `pip install jupyterlab_launcher===0.2.9`, which should have a fix for that?

**Comment by jharonfe** [comment]
Thanks. That resolved the issue.

**Comment by blink1073** [comment]
Great, cheers!
