### ISSUE TITLE
Cell tools metadata style fix

### ISSUE THREAD

**Issue by cameronoelsen** [jupyterlab/jupyterlab#2242]
Right now, when making changes in the textarea in the "edit metadata" section in cell tools, the controls should be displaying inline with the "edit metadata" header. I would make this quick change but it seems like to make the desired effect below, it involves changing implementation:

### Current state
![screen shot 2017-05-18 at 10 52 09 am](https://cloud.githubusercontent.com/assets/6437976/26216493/2d7aacdc-3bb9-11e7-8959-493990e9b28c.png)

### Desired
![screen shot 2017-05-18 at 10 54 04 am](https://cloud.githubusercontent.com/assets/6437976/26216501/36f096a0-3bb9-11e7-9890-97b285b03d64.png)

**Comment by blink1073** [comment]
That involves adding a title renderer option to the json editor: https://github.com/jupyterlab/jupyterlab/blob/088e90593e49c78af6031c8387b6ab4d80da0de5/packages/codeeditor/src/jsoneditor.ts#L63

**Comment by blink1073** [comment]
I am working on this now.
