### ISSUE TITLE
"light" terminal theme should show cursor

### ISSUE THREAD

**Issue by stephenholtz** [jupyterlab/jupyterlab#2247]
In the light terminal theme it is not possible to see where the cursor is located, while in the dark theme there is a blinking cursor, and the outline of the cursor shows up when clicking within the window (see cowsays).

![screen shot 2017-05-19 at 2 04 21 pm](https://cloud.githubusercontent.com/assets/1022515/26260678/13411944-3c9c-11e7-891c-5fb16bd82210.png)

![screen shot 2017-05-19 at 2 05 04 pm](https://cloud.githubusercontent.com/assets/1022515/26260697/28c4377e-3c9c-11e7-84a2-fbadd86d05ef.png)

**Comment by blink1073** [comment]
Thanks for the report!

**Comment by ellisonbg** [comment]
Marking as beta, as it makes the light mode essentially not usage.

**Comment by ellisonbg** [comment]
Working on this now...
