### ISSUE TITLE
Markdown rendered next to the cell

### ISSUE THREAD

**Issue by o2carr68** [jupyterlab/jupyterlab#2252]
Running a reedited markdown cell shows the rendered markdown next to the cell.
   - Jupyterlab: 0.22.0
   - Browsers: Firefox 53.0.2 and Chromium 57.0.2987.98

Steps to reproduce :
1. Create a markdown cell
2. Edit the cell 
3. Run the cell
4. Reedit the cell
5. Run the cell again

![test](https://cloud.githubusercontent.com/assets/24479423/26278541/30ff0534-3d9d-11e7-8fa7-f694c55c8ec9.gif)

**Comment by sccolbert** [comment]
Thanks for the report!
