### ISSUE TITLE
Markdown cell rendering causes page to scroll to inappropriate place

### ISSUE THREAD

**Issue by krvkir** [jupyterlab/jupyterlab#2253]
I'm running Jupyterlab 22.0 on anaconda on Windows 10.

Here is the screencast:

![2017-05-22-jupyterlab-bug-with-jumping-markdown-cell](https://cloud.githubusercontent.com/assets/4031219/26305802/792ba12a-3ef9-11e7-8de9-d40ef6e0195e.gif)

Seems like a bug (and is very annoying :) )

**Comment by blink1073** [comment]
Hi @krvkir, this was an intentional behavior.  We are currently scrolling the cell that was run to the center to optimize viewing of its outputs.  Let's leave this open for discuss about whether it is a good idea ;).

**Comment by jasongrout** [comment]
I noticed this too. Steve, it looks like it is scrolling the previous cell to the center when a markdown cell is run.

**Comment by krvkir** [comment]
Hi, thanks for quick response. 

Maybe it is not very clear from my demo, but this last markdown cell from the demo doesn't appear in the center when it is run. Instead the screen is scrolled to the place above it so that markdown cell becomes invisible (it is the last frame of the demo).

I can reproduce it on different browsers on windows. I'll also try to test it on my linux box in the evening.

**Comment by blink1073** [comment]
The issue was that we were using the editor widget geometry for scrolling, but it is hidden in the case of a markdown cell.  Switched to using the input area geometry in #2256.
