### ISSUE TITLE
"Run all above" and "Run all below" buttons.

### ISSUE THREAD

**Issue by krvkir** [jupyterlab/jupyterlab#2254]
Couldn't find these Jupyter commands in Jupyterlab (neither commands nor an issue). Do you plan to implement them? I really miss these features.

**Comment by blink1073** [comment]
We weren't tracking them specifically, #1306 is tracking the actions as a whole.

**Comment by majkelx** [comment]
I do not know how many actions are still missing, but lack of "Run all above" and "Run all below" is specifically painful...

**Comment by blink1073** [comment]
Moving this to beta, after the notebook refactor (cf. #2540).

**Comment by ian-r-rose** [comment]
This is now in `master` after #3182

**Comment by BlkPingu** [comment]
Since nobody bothered to ask since this was implemented: What combination is suitable to use that does not interfere with anything else, yet good to reach?
Cmd - a , Cmd - b would be the obvious choices, but we can't use these for system reasons. Any suggestions?
