### ISSUE TITLE
Error Starting Kernel on Windows 7 using Julia-Pro-0.5.0.5

### ISSUE THREAD

**Issue by Iscalc** [jupyterlab/jupyterlab#2258]
I am trying to start the Julia kernel on Windows 7 (with JuliaPro-0.5.0.5) and got the following Error Starting Kernel message reporting a missing file:

`` Traceback (most recent call last):``

``  File "C:\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 503, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))``
``  File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()``
 `` File "C:\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)``
 `` File "<string>", line 3, in raise_exc_info``
 `` File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)``
 `` File "C:\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 75, in post
    type=mtype))``
 ``File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()``
  ``File "C:\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)``
 `` File "<string>", line 3, in raise_exc_info``
 `` File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)``
 `` File "C:\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)``
 `` File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()``
  ``File "C:\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    r aise_exc_info(self._exc_info)``
 `` File "<string>", line 3, in raise_exc_info``
  `` File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)``
  `` File "C:\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)``
  `` File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()``
  `` File "C:\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)``
  `` File "<string>", line 3, in raise_exc_info``
  `` File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 285, in wrapper
    yielded = next(result)``
  ``File "C:\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)``
  ``File "C:\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)``
 `` File "C:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
    **kw)``
 `` File "C:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)``
  `` File "C:\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)``
 `` File "C:\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)``
 `` File "C:\Anaconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)``

`` FileNotFoundError: [WinError 2] The system cannot find the file specified``

**Comment by blink1073** [comment]
Hi @Iscalc, does the same happen when launching the kernel from the classic notebook (as `jupyter notebook`)?

**Comment by Iscalc** [comment]
Hi @blink1073 

Indeed there was some kind of "heisenproblem" with my jupyter install. Re-installed Anaconda and Julia and now all works fine.

**Comment by blink1073** [comment]
Glad to hear you got sorted, happy computing!
