### ISSUE TITLE
Options to hide markdown source for rendered markdown cells

### ISSUE THREAD

**Issue by joonro** [jupyterlab/jupyterlab#2259]
Hi,

It seems in notebooks, when I run a markdown cell, jupyter lab splits the cell vertically and the markdown is rendered on the right split: 

![2017-05-22 10_36_53-jupyterlab alpha preview - opera](https://cloud.githubusercontent.com/assets/1063143/26321186/b418388a-3eda-11e7-8dfa-2f96c93a3de5.png)

This is very useful when I'm writing, but I hope there is an option (a notebook setting, for instance) which will allow me to just show the rendered markdown when I run a markdown cell, just like Jupyter notebook. Please let me know if this is already possible - thank you!

**Comment by blink1073** [comment]
Hi @joonro, this was a bug in 0.22.0, which should be fixed in 0.22.1.

**Comment by blink1073** [comment]
(which was released this morning).

**Comment by joonro** [comment]
Thank you for the quick reply - yes I just installed 0.22.1, and it seems to be fixed.

**Comment by blink1073** [comment]
Great!
