### ISSUE TITLE
Restructure Apputils

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2263]
Right now `apputils` depends on `application`, meaning that any code using for example a dialog is also depending on `application`.  If we move `statedb` to `coreutils` and move `instancetracker` and `layoutrestorer` to `application` we can break this dependency.

**Comment by ellisonbg** [comment]
Is this one still relevant?

**Comment by blink1073** [comment]
Yes, we still want to break this dependency.

**Comment by blink1073** [comment]
The plan for this is to: 

- Move `layoutrestorer` to `application`
- Move `layoutrestorer` plugin to `application-extension`
- Remove the `setLayoutDB` method from `application` and replace it with a `restore` method
- Remove the `restored` promise from the application shell
- Use `restorer.restored` in the plugins

This is should wait for #2380.
