### ISSUE TITLE
How do I run this from within ijavascript?

### ISSUE THREAD

**Issue by briancullinan** [jupyterlab/jupyterlab#2269]
I am trying to get a cells contents from within ijavascript:

https://stackoverflow.com/questions/42773092/javascript-jupyter-notebook-how-to-get-code-cell-content

**Comment by blink1073** [comment]
Hi @megamindbrian, in JupyterLab you would create a plugin that requires the notebook panel tracker, and accesses the current cell text as `tracker.currentWidget.notebook.activeCell.model.value.text`.    The [tooltip extension](https://github.com/jupyterlab/jupyterlab/blob/d3ff7d71f88da5969c429998868321c38f55ea43/packages/tooltip-extension/src/index.ts#L115) is an example of requiring a notebook tracker.  
This [tutorial](https://github.com/jupyterlab/jupyterlab/blob/master/docs/notebook.md#adding-a-button-to-the-toolbar) demonstrates how to create a simple plugin using the cookiecutter.

**Comment by megamindbrian** [comment]
I assume this would allow me to do something like run all the cells in
another notebook from within a notebook cell?

**Comment by blink1073** [comment]
For that you can use `NotebookActions.runAll(otherNotebookPanel.notebook, otherNotebookPanel.context.session)` located [here](https://github.com/jupyterlab/jupyterlab/blob/eac4623a67db3fc1c33f7179be13092bd15e1c30/packages/notebook/src/actions.ts#L438).

**Comment by megamindbrian** [comment]
This is going to be awesome.  I want to apply DevOps to every discipline.

**Comment by blink1073** [comment]
👍
