### ISSUE TITLE
Improve notebook toolbar design

### ISSUE THREAD

**Issue by faricacarroll** [jupyterlab/jupyterlab#227]
## Summary
- Style cell type and kernel dropdowns
- Clean up vertical height and line-height
- Possibly add separators
## Original comment

We (@spoorthyv @charnpreetsingh185 @katiewhite360) have created a mockup of the updated notebook toolbar and would like some feedback. 

We replaced the icons with google's material icons because not only are they more visually appealing, but they are also more intuitive than some of the current icons. 

We also added sections to the toolbar to add visual separation between the icons. We placed run kernel, interrupt kernel, and restart kernel in one section. Cut cells, copy cells, and paste cells are placed in another section. 

We moved the kernel functions (run kernel, intterupt kernel, etc.) to after the add new cell icon because they will be used more often than the cut, copy, paste icons. We placed them closer to the left because of their higher importance.

During our user tests of we noticed that when multiple users would try to change kernels, they would click the top right kernel label in the toolbar multiple times because they thought it was a dropdown. We decided to change it to actually be a dropdown where you can change kernels.

We also want to add an indicator of when the file has been saved so there is some kind of reaction when the save button is clicked. We placed that indicator after the "Markdown" dropdown.

Let us know what you think!

Original notebook toolbar:
![screen shot 2016-07-05 at 9 55 42 am](https://cloud.githubusercontent.com/assets/19479586/16593978/dd355a94-429c-11e6-85d3-119ee48a6022.png)

Our mockup:
![artboard 6 2x](https://cloud.githubusercontent.com/assets/19479586/16594059/58a49294-429d-11e6-849a-5b1eacb9f2cd.png)

**Comment by bliker** [comment]
I think the circles around ► and ■ make them a bit too small :)

**Comment by faricacarroll** [comment]
Thanks!

Here's a mockup of the new version:
![artboard 9 2x](https://cloud.githubusercontent.com/assets/19479586/16597040/b3827e48-42ab-11e6-87de-b7489679b31a.png)

**Comment by ellisonbg** [comment]
Very much like this design. Clean, simple, good usage of basic design elements. A few questions:

* What icon set are you using?
* What font size are the icons?

Cheers, Brian

**Comment by faricacarroll** [comment]
Thanks!
We're using google's [material icons](https://design.google.com/icons/). 
The size of the icons are all 20px.

**Comment by jasongrout** [comment]
What is the status of this?

**Comment by spoorthyv** [comment]
We still need to implement material icons and change the kernel indicator on the right to a kernel selector.

**Comment by spoorthyv** [comment]
Wait actually i think issue #320 covers all of this.

**Comment by jasongrout** [comment]
That's too broad of an issue to really focus. I'd rather keep track of these specific items here.

**Comment by ellisonbg** [comment]
Some of this is done in master. I am going to open another issue to track the dropdown styling in the toolbar - basically want to re-style all dropdowns across JLab rather than just the toolbar.
