### ISSUE TITLE
Scrolling bug and out-of-order input prompt in console

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab#228]
I can't seem to replicate it after trying multiple times, but at one point I ended up with the console not scrolling correctly. More interestingly, right after I got the next input prompt _in between_ the old output, and now anything new that I type is in the middle area, with the old output now appearing at the bottom. 

Here's an image, the `1+1` block is the new input, and the `hist` call is older and yet below it:

![image](https://cloud.githubusercontent.com/assets/57394/16596491/0bf3c940-42a9-11e6-9f43-febe26d36d5f.png)

Note that the prompt numbers are still correct, obviously, as they come from the kernel.

@michaelpacer

**Comment by fperez** [comment]
I just want to add that this has happened again more than once.  I still don't know how to *reliably* reproduce it, but I have seen it over time (across updates and restarts), so it wasn't a one-off thing.

**Comment by jasongrout** [comment]
CC @afshin.

**Comment by fperez** [comment]
OK, I've been able to reproduce it reliably in master 8c1f1c1, and *on the notebook!* 

Here's what I did: 
* create several cells that produce plots, calling `plot(rand(100))`.
* once I get to the bottom of the page, scroll with my wheel mouse to reveal the bottom-most cell.
* run one more cell.
* Boom! That new cell gets popped up in the wrong location.

Here's a recording:

![cell-jumping](https://cloud.githubusercontent.com/assets/57394/18025327/90e242f2-6bdb-11e6-8bf2-140a2e2eb5eb.gif)

Furthermore, once this notebook has this problem, new cells are always inserted in the wrong order (I deleted all cells and simply tried to run a single cell, you can see the next one being inserted in the wrong location):

![Uploading cell-jumping2.gif…]()

I hope others can now reproduce it, as it's pretty serious :)

**Comment by afshin** [comment]
@jasongrout @blink1073 I tried reproducing this over the weekend and couldn't. I just did a fresh build (https://github.com/jupyter/jupyterlab/commit/6a6f16777f70b4b7f96e3bf8b6be7fadac42ba5d) and still cannot. Could you two please see if you can make this happen? I'll keep trying.

**Comment by blink1073** [comment]
I was not able to reproduce either.  I even tried a scroll-mouse.

**Comment by fperez** [comment]
Thanks for trying guys, I don't know what to say, other than "it happens here" :)  I'll keep updating this if I find new ways of making it happen, eventually I'm sure we'll nail it (or it will stop happening!)

**Comment by jasongrout** [comment]
@fperez, what browser and os are you using? I also couldn't reproduce it (Chrome 52, OS X 10.10.5).

**Comment by afshin** [comment]
FYI, I'm running:
Chrome version 52.0.2743.116 (64-bit)
OS X version 10.11.6 (15G31)

**Comment by fperez** [comment]
Same exact as @afshin :)

**Comment by fperez** [comment]
This is @blink1073 on Fernando's machine.  I was able to reproduce the issue and tracked it down to Chromium Wheel Smooth Scroller 1.4.2 adding DOM elements to the page that interfere with the Phosphor Panel Layout's ability to add a node in the proper location.

![screen shot 2016-11-10 at 15 23 22](https://cloud.githubusercontent.com/assets/57394/20198528/0636080e-a75a-11e6-8eb3-aafea8fcf5a6.png)

**Comment by sccolbert** [comment]
So, is this invalid then? I don't think it's feasible to defensively code against other libraries or browser extensions that arbitrarily change the DOM underneath us.

**Comment by jasongrout** [comment]
> I don't think it's feasible to defensively code against other libraries or browser extensions that arbitrarily change the DOM underneath us.

Not in general, no. However, @blink1073 and I have what we think is a simple change to the phosphor layout code that makes it more robust against something like this. @blink1073, can you paste the diff?

Of course we can't solve every situation, and this extension should definitely go on an incompatibility list. However, we think our change to phosphor will defend against this specific situation without making the code smell or introducing performance degradations.

**Comment by blink1073** [comment]
Here it is:

```diff
diff --git a/src/ui/panel.ts b/src/ui/panel.ts
index 34a9a6c..6857f92 100644
--- a/src/ui/panel.ts
+++ b/src/ui/panel.ts
@@ -304,7 +304,7 @@ class PanelLayout extends Layout {
    */
   protected attachWidget(index: number, widget: Widget): void {
     // Look up the next sibling reference node.
-    let ref = this.parent.node.children[index];
+    let ref = this._widget.at(index).node;

     // Insert the widget's node before the sibling.
     this.parent.node.insertBefore(widget.node, ref);
@@ -344,7 +344,7 @@ class PanelLayout extends Layout {
     this.parent.node.removeChild(widget.node);

     // Look up the next sibling reference node.
-    let ref = this.parent.node.children[toIndex];
+    let ref = this._widgets.at(toIndex).node;

     // Insert the widget's node before the sibling.
     this.parent.node.insertBefore(widget.node, ref);
```

**Comment by sccolbert** [comment]
I feel like there's a reason I didn't do it that way to begin with. Lemme see if I can recall what it was.

**Comment by sccolbert** [comment]
In the larger scheme of things though, we can't add defensive code in every single place we create DOM nodes, to protect against some other library forcibly modifying something it neither created nor owns.

If the suggested solution works, I'm fine making that change. But I don't want to start down the path of hacking phosphor to support the evil behavior of other libraries.

**Comment by sccolbert** [comment]
Right okay, now I remember. The pasted code is not equivalent. The widget being inserted already exists in the `_widgets` vector at the specified index. We want the node which comes *after* that one, so that we can insert *before* it. That's why I use the parent node's children list, because it hasn't yet been changed, so the index points to the correct reference node.

Using the `_widgets` vector can be made to work, but not as easily as the listed patch.

**Comment by sccolbert** [comment]
For example, the behavior of this chrome extension will *completely* break the virtual DOM algorithm, which assumes that nothing externally modifies the actual rendered DOM tree.

**Comment by jasongrout** [comment]
> But I don't want to start down the path of hacking phosphor to support the evil behavior of other libraries.

Totally +1.



> Right okay, now I remember. The pasted code is not equivalent. The widget being inserted already exists in the _widgets vector at the specified index. We want the node which comes after that one, so that we can insert before it. That's why I use the parent node's children list, because it hasn't yet been changed, so the index points to the correct reference node.

Ah. I didn't realize the widgets list and the DOM were out of sync at that point. And Steve and I thought that it might be even better performance to set a variable to `this.parent.node` since it's used several places in the function.

Okay, if it clutters up the code, then +1 on not changing it and putting the extension on an incompatibility list.

> For example, the behavior of this chrome extension will completely break the virtual DOM algorithm, which assumes that nothing externally modifies the actual rendered DOM tree.

Yep, not saying we're trying to accommodate this extension - just looking to see where we can code more defensively against situations.

**Comment by fperez** [comment]
@blink1073, given the limits of what we can do here, I think we can also close this one, no?

**Comment by blink1073** [comment]
Agreed.
