### ISSUE TITLE
Extend autocomplete to support parameters and documentation

### ISSUE THREAD

**Issue by scottdraves** [jupyterlab/jupyterlab#2285]
this probably requires a new protocol to the kernel so maybe doesn't belong here,
but i am not sure where to file an issue against all the kernels, and there definitely is a UI component, so here it is.  please help me redirect it as appropriate.

**Comment by blink1073** [comment]
Related to https://github.com/jupyter/jupyter_client/issues/51.

**Comment by elgalu** [comment]
Some inspiration could come from https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/hinterland

**Comment by krassowski** [comment]
Closing as  documentation panel is now available in JupyterLab 4.0:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/b0a45de6-4df9-4094-922c-0b55b8242535)

It is opt-in:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/34a00208-0cf1-4be8-a712-598d98b52ed1)

Note: even more features are available in https://github.com/jupyter-lsp/jupyterlab-lsp.
