### ISSUE TITLE
Master broken

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2291]
Some combination of merges broken master. Working on a fix now...

Looks like it was a conflict between the chatbox and observable vector stuff.

**Comment by ian-r-rose** [comment]
Yes, the chatbox was using the old observable API.
If you are already working on a fix, great. If not, I am happy to patch it up.

**Comment by ellisonbg** [comment]
I think I have it fixed, but it you could help review it in a few minutes that would be swell 👍
