### ISSUE TITLE
Make beforeunload event configurable

### ISSUE THREAD

**Issue by charnpreetsingh** [jupyterlab/jupyterlab#2301]
Currently the application extension is adding the `beforeunload` event listener. This is preventing the Electron app from closing. If we could make this configurable in JupyterLab's `index.js` so that any other application could use JupyterLab but add their own `beforeunload` event handler that would be great.  

https://github.com/jupyterlab/jupyterlab/blob/5c7acdea3510d078f7a12daa5be38e52a0c6810d/packages/application-extension/src/index.ts#L118

Cf: https://github.com/jupyterlab/jupyterlab_app/issues/8

**Comment by blink1073** [comment]
I'd argue that the application extension should be replaced in this case, which may include other electron-specific application modifications.

**Comment by charnpreetsingh** [comment]
That's interesting. making our own application extension would allow Electron specific actions for adding new Menu items and having our own dialog box. I'll add it to ignore plugins and see if that works.

**Comment by charnpreetsingh** [comment]
Confirmed I was able to close the app by not including the application extension.

**Comment by blink1073** [comment]
Great, closing this one.
