### ISSUE TITLE
New launcher from tab

### ISSUE THREAD

**Issue by cameronoelsen** [jupyterlab/jupyterlab#2307]
@ellisonbg brought up that we are hoping to implement a quick control to create a new launcher window from the docpanel. Here are a few mockups of the possible avenues that we could take for this:

### New tab left aligned
![tab-left](https://cloud.githubusercontent.com/assets/6437976/26513845/abbc82cc-4222-11e7-9756-b1b5b288b531.jpg)

### New tab floating left disconnected
![tab-floating-left](https://cloud.githubusercontent.com/assets/6437976/26513849/b28b614a-4222-11e7-960a-372a6e25f57e.jpg)

### New tab floating right disconnected
![tab-floating-right](https://cloud.githubusercontent.com/assets/6437976/26513852/b6410c7c-4222-11e7-897d-65c451bf97b2.jpg)

My personal favorite is the floating left disconnected, but @ellisonbg brought up the point that it may take some time to implement (not in time for the beta). So, maybe for the time being we could go with the floating right one?

**Comment by ellisonbg** [comment]
New launcher design in master addresses this UX.
