### ISSUE TITLE
Launcher restructure

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2330]
- Remove the launcher side item.
- Add a `File -> New` and a single button in the file browser that brings up a launcher tab.
- Remove other `New` items in the `File` menu.
- Show launcher items for each combination of notebook/console and kernel name.
  -- The order will be updated based on most recently used.
- Replace the launcher tab with the selected item with no additional dialog.
- Add a `File -> Rename`.
- Merge the landing page as a launcher with additional information displayed.

**Comment by blink1073** [comment]
API sketch:

```typescript

function registerActivity(options: IOptions) {

interface IOptions {

    callback: (cwd: path, name: string) => Promise<Widget>;
    
    iconClass: string;
    
    iconLabel: string;
    
    displayName: string;
    
    name: string;
    
    section: string;
    
    rank: number;
}

}
```

**Comment by ellisonbg** [comment]
Deleting the landing GH label as that extension will be deleted.

**Comment by ellisonbg** [comment]
Also, remove the `New Text File` and `New Notebook` items from the `File Operations` section of the command palette.
