### ISSUE TITLE
Jupyterlab 0.23.1 installed to run on jupyterhub (0.72) is not loading properly

### ISSUE THREAD

**Issue by Analect** [jupyterlab/jupyterlab#2347]
I've installed jupyterlab 0.23.1 and the following extensions.

```
$ jupyter labextension list                                                                              
@jupyterlab/google-drive                                                                                                           
@jupyterlab/nbwidgets                                                                                                              
jupyterlab-hub  
```
However, the browser isn't loading ...  I just get a blank grey screen with a single `Commands` tab along the left edge.  These are some of the errors showing up in the browser.

`Plugin 'jupyter.extensions.main' failed to activate.`
`Error: No provider for: jupyter.services.commandpalette.`
`Plugin 'jupyter.services.rendermime' failed to activate.`
`Error: No provider for: jupyter.services.command-linker`
`Plugin 'jupyter.extensions.chatbox' failed to activate.`

I use a Dockerfile to generate an image that loads jupyterlab and all its dependencies and it has been working fine up to this point.  It leverages the conda-forge feedstock for install jupyterlab.

**Comment by blink1073** [comment]
Nbwidgets and hub are not yet compatible with 23, but the app should still have loaded.  This was a fresh docker environment or one where you had a previous version of JupyterLab that was upgraded?

**Comment by Analect** [comment]
It was a fresh environment.  I can remove the hub / nbwidget installation and see if that changes anything.

**Comment by Analect** [comment]
@blink1073 ... removing the hub/nbwidgets labextensions installation appears to have resolved the problem.  Sorry for the noise.  Will close this. Thanks.

**Comment by jasongrout** [comment]
Fyi, I'm updating widgets momentarily.
