### ISSUE TITLE
No syntax highlighting for Dockerfile, Makefile, etc

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/jupyterlab#2351]
If I create a file with an extension such as "main.c" or "main.py" or 'main.rb' I get syntax highlighting for it.

However, if I create a 'Dockerfile' or 'Makefile', I do not get syntax highlighting.

Poking around, it looks like the mode is being detected properly (in `mode.ts`) but somehow this isn't set or loaded in CodeMirror?

**Comment by ellisonbg** [comment]
Looks like we bundle some common modes:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/mode.ts#L14

But relatively few all things considered. I am fine with us adding Dockerfile and making sure that works. However, I don't see a Makefile mode in the CM repo here:

https://github.com/codemirror/CodeMirror/tree/master/mode

But there is this issue:

https://github.com/notepadqq/notepadqq/issues/42

The other aspect is that we don't have a way of setting tabs or spaces to work with a Makefile. These are pretty significant usability things we will want to fix :-)

**Comment by yuvipanda** [comment]
I submitted https://github.com/jupyterlab/jupyterlab/pull/2352 which bundles SQL + shell by default. Adding Dockerfile there didn't seem to work, however.

Can extensions just add more codemirror modes? Also was the patch to use monaco instead of codemirror merged?

**Comment by blink1073** [comment]
The other core CodeMirror modes are available, they are just loaded in a separate bundle.  We have not yet included Monaco because it uses `window.requirejs`.

**Comment by blink1073** [comment]
We are currently basing the mode on the file extension, but it looks like we could also check based on filename, since that is how CodeMirror handles `Dockerfile`: https://github.com/codemirror/CodeMirror/blob/c4d8e10db32776e6d4aa7b2f9d38fd92b14a68a4/mode/meta.js#L39.

**Comment by ellisonbg** [comment]
Marking as beta, but we can possible back off that depending on how things go in the next few days...
