### ISSUE TITLE
Jupyter is unable to find JupyterLAB when installed at local-user site-package level.

### ISSUE THREAD

**Issue by alecuba16** [jupyterlab/jupyterlab#2353]
Hello,

I'm using Gentoo linux as my primary distribution.  I'm able to install all required packages for jupyter ,ipython, and jupyterlab with the required version of jupyter notebook (4.4.1)

I have installed jupyterlab and enabled at user level (~/.local/lib64/python3.5/site-packages/) but jupyter is giving a error about cannot found lab when I invoke  jupyter lab.

The jupyterlab and its dependencies are installed on (~/.local/lib64/python3.5/site-packages/) locally :
> jupyter_console
> jupyter_console-5.1.0.dist-info
> jupyter_contrib_core
> jupyter_contrib_core-0.3.1.dist-info
> jupyter_nbextensions_configurator
> jupyter_nbextensions_configurator-0.2.5.dist-info
> jupyterlab
> jupyterlab-0.23.1.dist-info
> jupyterlab_launcher
> jupyterlab_launcher-0.2.9.dist-info

I'm able to import jupyterlab from python console:
> 
> import jupyterlab_launcher
> import jupyterlab
> jupyterlab
> <module 'jupyterlab' from '/home/alex/.local/lib64/python3.5/site-packages/jupyterlab/__init__.py'>

But I'm unable to launch jupyter lab:
> ~ $ jupyter lab
> Error executing Jupyter command 'lab': [Errno 2] No such file or directory

Server extension is enabled:

> ~ $ jupyter serverextension list
> config dir: /home/alex/.jupyter
>     jupyterlab  enabled 
>     - Validating...
>       jupyterlab  OK

Few tests about loading it manually:
> ~ $ jupyter notebook --NotebookApp.nbserver_extensions="{'jupyterlab':True}"
> [I 11:01:18.116 NotebookApp] The port 8888 is already in use, trying another port.
> [I 11:01:18.124 NotebookApp] JupyterLab alpha preview extension loaded from /home/alex/.local/lib64/python3.5/site-packages/jupyterlab
> [I 11:01:18.124 NotebookApp] Running the core application with no additional extensions or settings

Manually loads well I'm able to run the regular notebook webui at /tree and the jupyterlab on the url 127.0.0.1:8888/lab

Or just jupyter notebook and then go to url http://localhost:8888/lab

I suspect the problem is about jupyter is not looking my local-user site-package, I'm trying to find in the jupyter documentation if there is some launcher flag for specify the site-package path.

I have tested set the PYTHONPATH on the bash environment and in my user profile but only works at the python console, not for jupyter. I'm able to work with any jupyter notebook without any problem.

thanks in advance.

**Comment by blink1073** [comment]
Hi @alecuba16, what are the outputs of `which jupyter-notebook` and `which jupyter-lab`?

**Comment by alecuba16** [comment]
Hello @blink1073 

> ~ $ which jupyter-notebook
>/usr/bin/jupyter-notebook
> ~ $ which jupyter-lab
> which: no jupyter-lab in (/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/6.3.0:/usr/lib/llvm/4/bin)

**Comment by blink1073** [comment]
Glad you found it, and thanks for the pointer, fixed in #2353.
