### ISSUE TITLE
Pasting large amounts of text into cells requires click to force refresh

### ISSUE THREAD

**Issue by stephenholtz** [jupyterlab/jupyterlab#2381]
This is not a critical bug, but I didn't see another issue here noting it. 

![twgrla4akq](https://user-images.githubusercontent.com/1022515/26855059-09b2ff88-4ae7-11e7-9c81-c92200e4c5da.gif)

I need to click before the text in the cell becomes visible. Same for all types of cells.

**Comment by blink1073** [comment]
Hi @stephenholtz, which version of JupyterLab is this?  It should have been fixed in 0.23 by #2339.

**Comment by stephenholtz** [comment]
from conda-forge:
`jupyterlab                0.23.1                   py36_0`

**Comment by blink1073** [comment]
Just to be absolutely sure, is this what you see on the Landing page (available as `Open Landing` in the command palette):

<image src="https://user-images.githubusercontent.com/2096628/26898474-c197d3a8-4b91-11e7-8f5c-b04d135aacfa.png" width=200>

**Comment by blink1073** [comment]
(modulo a patch version)

**Comment by stephenholtz** [comment]
I am using the JupyterLab electron app, and now realize this behavior may be specific to the app. **In Chrome the issue is nonexistent.**  Here is the information anyways, maybe I should post it in the other repo:

`Open Landing` with `0.23.1`:
![image](https://user-images.githubusercontent.com/1022515/26898740-fa5320ea-4b9a-11e7-8904-f5442e140f3a.png)

I updated to `0.23.2` and got this:
![image](https://user-images.githubusercontent.com/1022515/26899212-78eb9eae-4b9c-11e7-8a96-529c2fd00df1.png)

Still in `0.23.2` in the About page I see this:
![screen shot 2017-06-07 at 4 20 48 pm](https://user-images.githubusercontent.com/1022515/26899501-4bb584f8-4b9d-11e7-82cf-0657a257834b.png)
So the version _is_ getting updated etc.,

**Comment by blink1073** [comment]
Ah, the electron app is separately versioned, and right now is using the 0.22 JavaScript packages.   I'm going to close this as solved in the core JupyterLab.
