### ISSUE TITLE
Classic notebook doesn't work if lab console is running

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2389]
Looks like the code console is creating a session that the classic notebook doesn't like. Same error as before in classic notebook:

<img width="864" alt="screen shot 2017-06-07 at 10 20 29 am" src="https://user-images.githubusercontent.com/27600/26891752-f429f8fe-4b6a-11e7-87df-2866ba168239.png">

**Comment by blink1073** [comment]
Ah, that one is a bug in the classic notebook.  It needs to be able to handle other session types.

**Comment by ellisonbg** [comment]
Fixed in this PR on classic notebook: https://github.com/jupyter/notebook/pull/2559

**Comment by ellisonbg** [comment]
Closing, will be released in notebook 5.1
