### ISSUE TITLE
Review keyboard shortcuts for beta

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2390]
As one of the last steps before the beta, we should review the keyboard shortcuts for everything. We are using a number of shortcuts that override the browser defaults which is something we have usually tried to avoid in the classic notebook. But, we are not doing those overrides in a consistent manner. Minimally, we should survey our design patterns and make sure it is all consistent. We may also want to keep in mind that in the electron app, we have more flexibility in picking shortcuts.

**Comment by blink1073** [comment]
Here are the ones that conflict with browser shortcuts as listed in https://support.google.com/chrome/answer/157179?hl=en.

```
accel s             - save on all platforms
ctrl shift q        - quit on Windows and Linux
accel shift H    - open your home page in the previous tab on OSX
```

The gmail client prevents default on Accel S and cloud9 uses it to save, so I think we should keep that one.
We can safely change to `ctrl q` and `ctrl shift h` for the other two.

**Comment by ian-r-rose** [comment]
In Firefox, using `[accel shift P]` also toggles a private browsing window instead of the command palette, as discussed in #1718.
