### ISSUE TITLE
Focus console input area immediately upon creation

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2391]
A code console is focusing its input CM element for typing upon activation, but this doesn't happen the first time it is opened. We should focus the CM input element immediately upon creation, even before the kernel starts, so the user can immediately begin typing code. Part of what makes the current experience frustrating is that in many cases, when a console first opens, even a manual click on the CM element doesn't work - I often have to trick activate to get called for it to work.

**Comment by ellisonbg** [comment]
I will try to fix this now...

**Comment by ellisonbg** [comment]
Ahh, may I will wait - would conflict with ongoing launcher work

**Comment by blink1073** [comment]
It shouldn't conflict.
