### ISSUE TITLE
Do not wrap code cells ? 

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#2394]
Code cells appear to be wrapped in lab, which may make determining wether code is wrapped extremely hard: 
![screen shot 2017-06-07 at 14 09 43](https://user-images.githubusercontent.com/335567/26901541-118a406e-4b8b-11e7-899e-a66aaffc6f5b.png)

Especially since the default is to not have line numbers. It's better with Line Numbers:

![screen shot 2017-06-07 at 14 09 57](https://user-images.githubusercontent.com/335567/26901570-323f2bb2-4b8b-11e7-8c18-ee39310ea3f0.png)

But I believe we do not wrap (at least by default) in Classic. I don't thing we should in lab either. I haven't found a global setting for the notebook.

**Comment by ellisonbg** [comment]
Yep, should definitely not be wrapped! Thanks! Tagging as beta.

**Comment by ellisonbg** [comment]
Here is a description of this particular bug:

The bug in #2394 is coming from a single instantiation to `CodeMirrorEditor` *mutating* the config object it is passed into the constructor with defaults that the class sets. That is here:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/editor.ts#L96

The config object there is managed by the `CodeMirrorEditorFactory` here:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/factory.ts#L26

Each creation of a new CME mutates that config object further, propagating defaults in one call to the others.

**Comment by ellisonbg** [comment]
@blink1073 @afshin let's chat about this and #2402 tomorrow

**Comment by aymaliev** [comment]
And if someone wants their code wrapped, how can they do that?

**Comment by blink1073** [comment]
Hi @aymaliev, in JupyterLab 0.31 (it can be done using `Settings -> Advanced Settings Editor`):

<img width="675" alt="image" src="https://user-images.githubusercontent.com/2096628/34817491-c4e55a3e-f67d-11e7-9960-97633129ddb7.png">

**Comment by asishm** [comment]
```json
{
    "codeCellConfig": {
        "lineWrap": true
    }
}
```
making it copy paste-able in case anyone else comes across this.

**Comment by nmvega** [comment]
Is it possible to have cell output not wrap, as well? (For example, formatted tabular output commands don't render well when wrapped).

I looked at the `Advanced Settings Editor`, but couldn't identify if there was a option for that. Thank you.

**Comment by JasonMDSI** [comment]
For jupyterlab 0.35.4, the code should be
```
{
    "codeCellConfig": {
        "lineWrap": "on"
    }
}
```
