### ISSUE TITLE
Shift-L to show/hide all line numbers in notebook. 

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#2395]
In classic notebook Shift-L toggle line numbers for all the cells. Lab seem to not do that.

**Comment by ellisonbg** [comment]
Yep, tagging as beta!

**Comment by Carreau** [comment]
Thanks !

**Comment by iamtodor** [comment]
@ellisonbg @Carreau is there any way to set such behavior by default? I want to see line number in every notebook and in every kernel that I have. Is it possible?

**Comment by jasongrout** [comment]
Look in the Settings, Advanced Settings, under the Notebook option. You can set there options for the notebook editors.

**Comment by jasongrout** [comment]
I'm a little surprised that the View > Line numbers menu option doesn't set the setting. Would you open a new issue for making the view menu option set the setting so it can be remembered across sessions?

**Comment by iamtodor** [comment]
@jasongrout `View -> Line numbers` works only for the current file (notebook) and I want to make it works on every notebook and every kernel. I not sure if I know how to add correctly `line numbers` to `Settings -> Advanced Settings, under the Notebook option`

**Comment by jasongrout** [comment]
Go to the notebook panel of the advanced settings, and paste this into the user settings pane on the right:

```json
{
    "codeCellConfig": {
        "lineNumbers": true
    },
    "markdownCellConfig": {
        "lineNumbers": true
    },
    "rawCellConfig": {
        "lineNumbers": true
    }
}
```

**Comment by jasongrout** [comment]
That overrides the configuration values for those things.

**Comment by iamtodor** [comment]
@jasongrout Thank you, works fine
