### ISSUE TITLE
inspector updates

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#2398]
I've just discovered the inspector, and I found it super cool! I have two remarks for your consideration:
* When it is initially opened, it's completely blank and non-interactive, and it took me some time to figure out how to use it. Perhaps use the time when it's blank to show a brief hint describing what it should do.
* As far as I could tell, inspector is only updated on key press events. This may be inferior to updating it whenever user moves the cursor. Alternatively one could reuse the shortcut for firing up the inspector also for refreshing its state. Or yet another option would be to invoke/update the inspector upon consecutive pressed of shift-tab, similar to the classic notebook.

**Comment by AbdealiJK** [comment]
Noob question: how do I get it to work? I do that know what to do with the blank screen :|

**Comment by blink1073** [comment]
It responds to typing in a cell and shows the documentation automatically.  

Type `print(` and it will show the docstring.

**Comment by akhmerov** [comment]
Hehe, @AbdealiJK I had exactly the same problem. That's why I suggested to make the default status not blank. I even checked developer console and updated jlab because the inspector looked like it was missing.

**Comment by giladgressel** [comment]
Just gonna chime in that I literally spent like 10 minutes searching the docs trying to understand what it did. Finally just googled and got here.
It's pretty cool.  Does what shift-tab x4 does from reg notebook.

**Comment by jasongrout** [comment]
Definitely +1 to some help text when it initially opens.

**Comment by jasongrout** [comment]
Adding "good first issue" - the initial help page should be pretty straightforward to add. The inspector panel is at https://github.com/jupyterlab/jupyterlab/blob/master/packages/inspector/src/inspector.ts. Perhaps a constructor argument should take some initial help text?

**Comment by jasongrout** [comment]
Fixed by #6476 (and someone else fixed it so that it responded to cursor movements, not just keyboard movements).
