### ISSUE TITLE
Rethink defaults, settings, object creation, factories

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2402]
I was chasing down the bug reported in #2394 and found a bit of a mess that I think we will need to untangle. Maybe not for the beta, but soon thereafter.

Some of the contributing factors:

 * We have defaults spread over multiple different places in the code base.
* For the codemirror, editor stuff, we have two different sets of config/options that each have their own defaults in multiple places and which get merged in unpredictable ways.

See #2394 for a description of its particular bug. The take homes for me are these:

* We need the ability to declare defaults in a single place.
* There should be a clear pattern for overriding of those defaults.
* config/options objects should be treated as immutable data.
* The dual options/config stuff going on in the codemirror/editor stuff needs to be refactored so the two approaches never mix in the same API. A higher level API that doesn't know about CM should use generic editor options, and the lower CM layer should translate those to CM options.

This set of things is mostly/partially what `traitlets.config` solves. While there are design issues with it, the approach has been extremely robust for an incredible complex code base. Not saying we write traitlets.js, but at least learn from our lessons there.

Marking for beta to make sure we discuss temporary fixes, but the real work won't be for the beta.

**Comment by ellisonbg** [comment]
I think we have enough of this solved for the beta, marking this as 1.0.

**Comment by ellisonbg** [comment]
@afshin @blink1073 I think this will mostly be worked out with the new settings system and any refactoring we are doing in the document system. Can I close?

**Comment by blink1073** [comment]
Yep, closing.
