### ISSUE TITLE
Reimplement old (folders, then files) variant of file browser sorting

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2403]
Has the default sort order of the file browser changed. It used to put the directories at the top and other files at the bottom. But now everything is mixed by type. I can't figure out what changed though.

**Comment by dhirschfeld** [comment]
I'm not quite sure the behaviour you're describing but see also #1993 and #2167 for some other sorting issues.

**Comment by blink1073** [comment]
I am still seeing the folder, notebook, other order on both master and the 0.23 release.  It could be that related to the server-side ContentsManager.

**Comment by blink1073** [comment]
The `/tree` page would show the same problem if is a server side error.

**Comment by ellisonbg** [comment]
The server did change, but we should add our own sorting back to the old approach (by file type, then by name).
