### ISSUE TITLE
Allow raises-exception to continue

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2412]
cf https://github.com/jupyter/notebook/pull/2549.  Allows for code execution to continue if a tag “raises-exception” is encountered.

**Comment by mgeier** [comment]
:+1: This would be a great feature, but please don't make the same mistake that `notebook` (https://github.com/jupyter/notebook/issues/4198) and `nbconvert` (https://github.com/jupyter/nbconvert/issues/730) made:

If an exception is raised in a cell tagged with `raises-exception`, the execution of the following cells should continue. So far, so obvious. However, if such a cell does *not* raise an exception, this should itself be an error (and probably itself raise an exception mentioning the `raises-exception` tag) and stop further cells from executing.

**Comment by paugier** [comment]
"raises-exception" is really a must-have feature for pedagogical notebooks. It would **really** be good to be able to use this tag in jupyter-lab.

**Comment by blink1073** [comment]
Thanks for the prompt, @paugier, I'll take this one for 1.0.

**Comment by blink1073** [comment]
I am going to implement the same behavior as notebook.  If it changes there, we will follow suit.
