### ISSUE TITLE
Editor's command line hidden when in vim mode

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#2420]
Compare the two following scrennshot of JupyterLab Editor and Raw-Codemirror both in "vim" keymap, and both in command mode, where I did `<esc>:i'm typing here`, you see that the linebuffer where I am typing is not visible in JupyterLab's editor, but you can guess its location by the blue glow at the bottom of the screenshot of JupyterLab.

<img width="184" alt="screen shot 2017-06-09 at 14 29 45" src="https://user-images.githubusercontent.com/335567/26995226-46cef486-4d20-11e7-92e7-959552a4187a.png">
<img width="628" alt="screen shot 2017-06-09 at 14 30 49" src="https://user-images.githubusercontent.com/335567/26995225-46cdea28-4d20-11e7-94d4-0d33e2d09c25.png">

**Comment by blink1073** [comment]
Fixed by #2788.

**Comment by Carreau** [comment]
Thanks !
