### ISSUE TITLE
Add phosphor/datagrid support to csvviewer

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2421]
When the news phosphor datagrid is released, let's add support to the csvviewer. We probably want to spend a little time thinking about theming it for lab and trying to detect data types so we can do conditional formatting based on the field type.

Marking as 1.0, but I may get too excited and try to do this for the beta... :)

**Comment by sccolbert** [comment]
Fixed in #2433 ?

**Comment by blink1073** [comment]
Yep, apparently I was the one who got too excited.
