### ISSUE TITLE
Stream carriage returns not handled properly

### ISSUE THREAD

**Issue by parente** [jupyterlab/jupyterlab#2425]
The `ansi_up.ansi_to_html` function in the `rendermime.RenderedText` widget strips `\r` characters. Even if it didn't, the widget does not currently have logic to reset the text insertion position to the beginning of the current line when a carriage return is encountered and instead always appends stream output. This behavior causes libraries like [tqdm](https://pypi.python.org/pypi/tqdm) to render incorrectly. 

![screen shot 2017-06-10 at 11 14 25 pm](https://user-images.githubusercontent.com/153745/27007947-9ae4c07e-4e32-11e7-8984-893f3f75797e.png)

I'm happy to poke at the problem and submit a PR. A brief overview of how to tackle the problem  "the JupyterLab way" would be much appreciated and point me in the right direction. The original notebook [outputarea.js has quite a bit of code to handle this case](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/outputarea.js#L513), and I suspect porting it across as-designed is probably the wrong thing to do.

**Comment by blink1073** [comment]
I'd say the logic will be fairly identical and would go [here](https://github.com/jupyterlab/jupyterlab/blob/3bb3253d6c86d6cf5c7c8795bc1676268d6de668/packages/outputarea/src/model.ts#L318).  See also https://github.com/jupyterlab/jupyterlab/issues/1104.

**Comment by parente** [comment]
Sorry for opening the dupe. Whatever I did to search didn't match "\r" in the title!

**Comment by parente** [comment]
I'll still try to a PR to fix.

**Comment by blink1073** [comment]
:+1:
