### ISSUE TITLE
Host volumes mounted in a Windows NanoServer Container aren't recognised by JupyterLab

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#2426]
I'm running JupyterLab in a Windows NanoServer container. To ensure peoples notebooks/data are available outside the container I would like to run JupyterLab from a mounted host directory however I'm running into some problems.

If I try to start JLab from the mounted directory I get a `Server Connection Error` in the browser
![image](https://user-images.githubusercontent.com/881019/27009443-106b235c-4ed2-11e7-8bff-d3d1751fd6ce.png)
...and repeated `No such file or directory` errors in the terminal where I started the container:
```
[W 18:16:08.498 LabApp] 404 GET /api/contents/?content=1&1497168968492 (172.29.208.1) 1.99ms referer=http://c93b32ea4918:8888/lab?
[W 18:16:19.495 LabApp] No such file or directory:
```
If instead I create a `jupyter` directory in the container and start JLab in there and mount the host volume into a `jupyter/data` subdirectory the JLab app seems to work fine, but there's no sign of the mounted host volume in the File Browser. If I open a notebook and enter `ls` I can see the mounted host volume and even `cd` to it but there's no way to get to it from the File Browser.

![image](https://user-images.githubusercontent.com/881019/27009543-8bc03e78-4ed4-11e7-9768-64f37dada58f.png)

In the terminal where the container was started I see repeated `C:\jupyter\data doesn't exist` messages suggesting that something knows the directory is actually there but another component can't read it / is unaware of it
![image](https://user-images.githubusercontent.com/881019/27009584-3ccfaf82-4ed5-11e7-878b-046a2744ac8b.png)

**Comment by dhirschfeld** [comment]
I believe that there may be a bug in one of the libraries JLab is using to list the directory contents whereby it doesn't recognize host mounted volumes from inside a Windows container. Not the easiest to debug unfortunately :|

As a further data point, if I create a directory and a directory symlink to it both show up in the File Browser so it's specific to host mounted directories from within a Windows Container.
![image](https://user-images.githubusercontent.com/881019/27009614-e69e01d0-4ed5-11e7-9194-dd6640d6a5e3.png)

**Comment by dhirschfeld** [comment]
In case anyone with Win10 or Windows Server 2016 wants to take a look the image I'm building is available on Docker Hub:
```
docker pull dhirschfeld/quantdev
```

**Comment by blink1073** [comment]
Are you able to see the folder from the `/tree` page?

**Comment by dhirschfeld** [comment]
In the `/tree` page no directories or files get listed at all - i.e. the existence of the host mapped folder breaks the `/tree` listing entirely. In JupyterLab by contrast all other folders and directories show up and it's just the host mapped folder which is missing.

The terminal running the container regularly throws a warning  every few seconds saying the folder doesn't exist:
```
[W 08:31:14.763 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:31:24.764 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:31:35.763 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:31:46.763 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:31:57.764 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:32:07.765 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:32:18.764 LabApp] C:\jupyter\notebooks doesn't exist
[I 08:32:21.508 LabApp] Saving file at /Untitled.ipynb
[W 08:32:21.540 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:32:31.764 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:32:41.765 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:32:52.765 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:33:02.766 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:33:13.766 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:33:24.766 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:33:34.766 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:33:45.767 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:33:56.767 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:34:07.766 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:34:17.767 LabApp] C:\jupyter\notebooks doesn't exist
[W 08:34:28.768 LabApp] C:\jupyter\notebooks doesn't exist
```

**Comment by dhirschfeld** [comment]
Not sure if this is a JS issue or a Windows Continers issue :/

I'd be happy to open an issue  under Windows Containers but I'm stuck figuring out how I'd even begin to create a minimal repro.

https://github.com/moby/moby/issues?q=is%3Aissue+is%3Aopen+label%3Aplatform%2Fwindows

**Comment by dhirschfeld** [comment]
...happy to try anything else if you have any suggestions?

NB: The JS console doesn't show any problems - the only indication of the problem is in the terminal logging output. And of course the fact that the folder is missing from the File Browser. 

NBB:  `os.listdir` and `os.chdir` do work in the notebook which is why I think it's a JS issue

**Comment by blink1073** [comment]
We have an issue where the `/tree` view breaks when there are sessions running in JupyterLab, pending https://github.com/jupyterlab/jupyterlab/pull/2365 and https://github.com/jupyterlab/jupyterlab/issues/2389, you might want to try running `jupyter notebook` directly.  I suspect it is related to the `ContentsManager` used on the server, and seeing what the `/tree` view does would give us the clearest indication.

**Comment by blink1073** [comment]
Here's how you can test the contents manager directly (assuming you start ipython from the `C:/jupyter` directory):

```
import os
from notebook.services.contents.filemanager import FileContentsManager
cm = LargeFileManager(root_dir=os.getcwd())
cm.get('data')
```

**Comment by dhirschfeld** [comment]
```
C:\jupyter>dir
 Volume in drive C has no label.
 Volume Serial Number is 06CB-0B8C

 Directory of C:\jupyter

06/13/2017  12:35 PM    <DIR>          .
06/13/2017  12:35 PM    <DIR>          ..
06/13/2017  12:35 PM    <SYMLINKD>     notebooks [\\?\ContainerMappedDirectories\A533213C-4AEA-4628-9498-477A3EA40B9B]
               0 File(s)              0 bytes
               3 Dir(s)  21,246,435,328 bytes free

C:\jupyter>ipython
```
```python
Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os

In [3]: from notebook.services.contents.filemanager import FileContentsManager

In [5]: cm = FileContentsManager(root_dir=os.getcwd())

In [6]: cm
Out[6]: <notebook.services.contents.filemanager.FileContentsManager at 0x2a0078c4630>

In [7]: cm.get('data')
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-7-14c139ebf76f> in <module>()
----> 1 cm.get('data')

C:\Miniconda3\lib\site-packages\notebook\services\contents\filemanager.py in get(self, path, content, type, format)
    373
    374         if not self.exists(path):
--> 375             raise web.HTTPError(404, u'No such file or directory: %s' % path)
    376
    377         os_path = self._get_os_path(path)

HTTPError: HTTP 404: Not Found (No such file or directory: data)

In [8]:
```

**Comment by dhirschfeld** [comment]
```python
In [19]: os.path.exists(r'C:\jupyter')
Out[19]: True

In [20]: os.path.exists(r'C:\jupyter\notebooks')
Out[20]: False
```
hmmm...

**Comment by dhirschfeld** [comment]
So it seems that it's a python error with `os.stat`?
```python
In [6]: os.stat(r'C:\jupyter\notebooks')
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-da4f2f48104b> in <module>()
----> 1 os.stat(r'C:\jupyter\notebooks')

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\jupyter\\notebooks'

In [7]: os.stat??
Signature: os.stat(path, *, dir_fd=None, follow_symlinks=True)
Docstring:
Perform a stat system call on the given path.

  path
    Path to be examined; can be string, bytes, path-like object or
    open-file-descriptor int.
  dir_fd
    If not None, it should be a file descriptor open to a directory,
    and path should be a relative string; path will then be relative to
    that directory.
  follow_symlinks
    If False, and the last element of the path is a symbolic link,
    stat will examine the symbolic link itself instead of the file
    the link points to.

dir_fd and follow_symlinks may not be implemented
  on your platform.  If they are unavailable, using them will raise a
  NotImplementedError.

It's an error to use dir_fd or follow_symlinks when specifying path as
  an open file descriptor.
Type:      builtin_function_or_method

In [8]: os.stat(r'C:\jupyter\notebooks', follow_symlinks=1)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-3f2af8c2d20e> in <module>()
----> 1 os.stat(r'C:\jupyter\notebooks', follow_symlinks=1)

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\jupyter\\notebooks'

In [9]: os.stat(r'C:\jupyter\notebooks', follow_symlinks=0)
Out[9]: os.stat_result(st_mode=41471, st_ino=281474976710693, st_dev=113970060, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1497321316, st_mtime=1497321316, st_ctime=1497321316)
```
Curiously, if I set `follow_symlinks` to False it recognises the directory... even though it's a symlink!

**Comment by dhirschfeld** [comment]
Since the issue appears to be in the notebook I'll close this and continue the discussion in my PR linked above.

Thanks for your help tracking it down @blink1073!

**Comment by blink1073** [comment]
Cheers!
