### ISSUE TITLE
Class notebook file list fails to render when lab 0.23.2 starts a notebook session

### ISSUE THREAD

**Issue by parente** [jupyterlab/jupyterlab#2440]
With notebook 5.0.0 and lab 0.23.2:

1. Open lab
2. Open a notebook / start a kernel
3. Switch to classic
4. Files list fails to render
5. Following appears in the console:

```
Uncaught TypeError: Cannot read property 'path' of undefined
    at SesssionList.sessions_loaded (main.min.js:16187)
    at Object.i [as success] (main.min.js:4)
    at l (main.min.js:4)
    at Object.fireWith [as resolveWith] (main.min.js:4)
    at k (main.min.js:6)
    at XMLHttpRequest.<anonymous> (main.min.js:6)
```

Shutting down all notebooks started from Lab puts things back in working order in classic.

**Comment by blink1073** [comment]
This was fixed in https://github.com/jupyter/notebook/pull/2559 and will be in the Notebook 5.1 release.

**Comment by parente** [comment]
Sorry for the noise again. I knew I saw something about this problem but couldn't locate the issue days later.
