### ISSUE TITLE
ipywidgets in 0.23/0.24?

### ISSUE THREAD

**Issue by OliverEvans96** [jupyterlab/jupyterlab#2446]
I know that a lot is changing quickly around here, which is awesome. I appreciate the great work! But it's hard for the documentation to keep up. I couldn't quite find any currently relevant instructions.

Is jlab master compatible with ipywidgets? If so, what's the installation procedure?

@blink1073 
@jasongrout 

Thanks,
Oliver

**Comment by blink1073** [comment]
Hi @OliverEvans96, the following should work:

pip install jupyterlab==0.23
pip install ipywidgets==7.0.0a4
jupyter labextension install @jupyterlab/nbwidgets@0.20.2

**Comment by OliverEvans96** [comment]
Awesome, thank you! That works with jupyterlab 0.23 as well as jupyterlab master.

**Comment by OliverEvans96** [comment]
Could you explain the last command? Does @jupyterlab/nbwidgets refer to a github repository?

**Comment by blink1073** [comment]
It is an npm package: https://www.npmjs.com/package/@jupyterlab/nbwidgets

**Comment by OliverEvans96** [comment]
Ah, thanks! Much appreciated!

**Comment by blink1073** [comment]
Cheers!

**Comment by OliverEvans96** [comment]
Works with JupyterLab 0.24.1 :)

**Comment by blink1073** [comment]
I would have expected a compatibility warning, that's what I'm getting: 

```
$ jupyter labextension list
JupyterLab v0.24.0
Known labextensions:
   app dir: /Users/ssilvester/anaconda/envs/lab-test/share/jupyter/lab
        @jupyterlab/google-drive  enabled  OK
        @jupyterlab/nbwidgets  enabled   X

"@jupyterlab/nbwidgets@0.20.2" is not compatible with the current JupyterLab
Conflicting Dependencies:
Required	Actual	Package
^0.7.0  	^0.6.0	@jupyterlab/application
^0.7.0  	^0.6.0	@jupyterlab/notebook
^0.7.0  	^0.6.0	@jupyterlab/rendermime
```

**Comment by OliverEvans96** [comment]
Ah! Yes, you're correct. I'm getting the same now. I did `git pull`, but not `jupyter lab build`, so I was actually still using v0.23.2. It seems like nbwidgets needs to be updated, then?

**Comment by blink1073** [comment]
Correct, but @jasongrout is traveling, so most likely not until early next week.

**Comment by OliverEvans96** [comment]
Cool, thank you!

**Comment by dhirschfeld** [comment]
See also jupyter-widgets/ipywidgets#1421
