### ISSUE TITLE
jupyterlab 0.17.5 Keymap

### ISSUE THREAD

**Issue by CoaPsyFactor** [jupyterlab/jupyterlab#2447]
I'm missing "keymap" property of application. Now when trying to create new instance of Menu I'm unable to access keymap, is there any workaround?

**Comment by blink1073** [comment]
Hi @CoaPsyFactor, a menu shouldn't need a keymap, only `commands`, can you give a code snippet or an error message?

**Comment by jasongrout** [comment]
Closing since there was no answer from the OP. @CoaPsyFactor, feel free to post a comment to continue the discussion if there is still a need.
