### ISSUE TITLE
Ensure all packages are public on publish

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2463]
By default scoped packages are private, and lerna does not support passing `--access=public` to the publish [command](https://github.com/lerna/lerna/issues/590), but we can run `npm access public <foo>` on each package in our `publish` script as a work-around, to avoid needing to manually figure out which packages are new and should be made public.

**Comment by saulshanabrook** [comment]
@blink1073 Is this still an issue?

**Comment by blink1073** [comment]
Yep, but can easily be solved now: https://github.com/lerna/lerna/issues/590#issuecomment-324748883
