### ISSUE TITLE
Dialog design

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2471]
A few quick things I talked about with @cameronoelsen before the beta related to the dialog design:

* Make buttons have min width or have larger L/R padding, as some buttons with a small amount of text `OK` are too narrow.
* Use a fixed border width in all states to get rid of jumps.
* Audit the typography of the different dialogs.

**Comment by cameronoelsen** [comment]
The button fixes were made to PR #2476.
