### ISSUE TITLE
Version document models

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#2475]
Currently in the `IModelDB` interface, we create model strings, lists, etc using path-based specifiers. These paths are mostly just the names of the variables on the document model (`value` for a text document, `selections` for cursors, etc.) These name choices are mostly private, but they leak out in the case of a collaborative document. In that case, two collaborators need to have the same name for a value in order to know they are collaborating on the same data structure.

If we ever want to change or extend the document models, they will become incompatible when collaborating with others (independent of which `nbformat` they are using). We should attach some sort of version to document models and disallow editing of documents that use other models.

Thoughts?

**Comment by blink1073** [comment]
Sounds reasonable to me.

**Comment by dmonad** [comment]
This ticket seems out of date. We just merged our RTC model implementation: https://github.com/jupyterlab/jupyterlab/pull/10118

Selections are now handled in Yjs' [Awareness CRDT](https://docs.yjs.dev/api/about-awareness), not in modeldb anymore.

**Comment by goanpeca** [comment]
Closing 🙃 ?

**Comment by dmonad** [comment]
Sorry, I only read the first part and was focusing on the selections. Of course, also the new shared model implementation `YNotebook` could become incompatible with newer versions (for other reasons than shared cursors). For that reason, it makes sense to introduce a version for shared models.

We can introduce a `shared_model: 1` property (similarly to the version `nbformat: 4` in the JSON representation). When a YNotebook loads a Yjs document that defines an unknown version, we can show an error message.

**Comment by fcollonval** [comment]
The issue was closed as now the document lived in @jupyter/ydoc. The mirrored issue has be opened: https://github.com/jupyter-server/jupyter_ydoc/issues/138
