### ISSUE TITLE
Output cells should horizontal scroll if necessary

### ISSUE THREAD

**Issue by theocean154** [jupyterlab/jupyterlab#2495]
They will horizontal scroll for text output, but not for certain images, i.e.: https://gist.github.com/theocean154/1d3052834e2a82e268f87f6e264d0871

**Comment by blink1073** [comment]
The classic notebook scales images using these rules (unless unconstrained).  It has `overflow-x: auto` on the parent `div.output_subarea` div.

```
div.output_area img, div.output_area svg {
    max-width: 100%;
    height: auto;
}
```

**Comment by blink1073** [comment]
Updating this now.
