### ISSUE TITLE
Make notebook have only one active editor at a time

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#25]
Currently there are massive slowdowns (see #15) which could be mitigated by having only one active editor in a notebook.

- [ ] When an editor receives focus in a notebook in edit mode, a codemirror widget is constructed and displayed with the current content (or maybe a single codemirror is kept around and reused...)
- [ ] When the editor blurs, the codemirror editor is replaced with a rendered version of the editor contents.

**Comment by blink1073** [comment]
I think we'll want to keep the `CodeMirror.Doc` around at the very least for its history.

**Comment by jasongrout** [comment]
oh, right, thanks.  Good point!

**Comment by jasongrout** [comment]
Then as a first pass, I'll probably do something like the markdown cell - toggle between a rendered version of the input and an editable version of the input...

**Comment by jasongrout** [comment]
I put up a very early work-in-progress experiment at https://github.com/jasongrout/jupyterlab/commit/e296cb7a6c3a4cc122df08e9689e0ce5db3c635f

**Comment by ellisonbg** [comment]
But the current notebook doesn't have this problem and has all active code mirrors. I agree we should move to having only one active editor, but is an underlying bug we need to fix regardless

**Comment by sccolbert** [comment]
the comment by @ellisonbg seems to be directed at bug #168. This issue is for the actual enhancement.

**Comment by ellisonbg** [comment]
I agree we should do this - will help a lot.

**Comment by jasongrout** [comment]
Definitely not 1.0, though. We fixed the underlying problem of sluggish cells a different way (by not rerendering codemirror so aggressively).
