### ISSUE TITLE
Shortcut for closing the sidebar

### ISSUE THREAD

**Issue by sccolbert** [jupyterlab/jupyterlab#2505]
It would be nice to have a command/shortcut for closing the sidebar. Something like `Escape` which only applies if nothing else more specific should happen on `Escape`.

**Comment by stephenholtz** [comment]
@sccolbert what about something like `⌘ + Esc` Both in the editors with Vim and in the notebooks I tend to use `Esc` quite a bit. It could get kind of obnoxious if this flipped the sidebar down unintentionally, e.g. if I didn't know what was in focus.

**Comment by ellisonbg** [comment]
Closing as duplicate of #3393
