### ISSUE TITLE
Provide a parameter in the JupyterLab class constructor to modify configuration data

### ISSUE THREAD

**Issue by lucbouchard1** [jupyterlab/jupyterlab#2515]
I need a means of starting the JupyterLab frontend with jupyter-config-data that is not stored as a node in the DOM. A possible implementation is adding a parameter to the constructor of the JupyterLab class that allows manually setting configuration values, overriding the configuration that is stored in the jupyter-config-data DOM node.

This issue is motivated by the [JupyterLab electron app](https://github.com/jupyterlab/jupyterlab_app), in which the render process does not know the Jupyter Server authentication token until the main process has spawned the server and sent the token over the message layer. In the current implementation, JupyterLab immediately pulls the config data from the DOM and I have no way to change it. This means I cannot set the authentication token value, so JupyterLab can't connect to the server.

I implemented a workaround where the main process injects the token into the html before starting the render process, which Brian and I agreed is not ideal.

**Comment by blink1073** [comment]
I think this could be handled by adding a `setOption` method to [PageConfig](https://github.com/jupyterlab/jupyterlab/blob/ae0d140c404500cf77ff0b1a61021aa81a7b9497/packages/coreutils/src/pageconfig.ts#L27).

**Comment by ellisonbg** [comment]
Sounds good, with the beta being delayed a bit, marking this as beta as it would dramatically help that @lucbouchard1 and @nproctor get the electron app going after the beta.

**Comment by lucbouchard1** [comment]
@ellisonbg I just made the change to jupyterlab and tested it on the electron app. Works great. I'll submit a pull request shortly.

**Comment by ellisonbg** [comment]
Great! I will review the PR now...

**Comment by blink1073** [comment]
Fixed by #2524, thanks @lucbouchard1!
