### ISSUE TITLE
Launcher design

### ISSUE THREAD

**Issue by rgbkrk** [jupyterlab/jupyterlab#2518]
I remember this being talked about during the jupyter dev meetings though I'm not sure I posted the mock I was talking about. Here's where I hope the launcher would head, slightly in more of a google docs / Netflix LoLoMo (list of list of movies) style banner:

![](https://media.githubusercontent.com/media/nteract/design/master/nteract-web/nteract%20search%20Dashboard.png)

Otherwise, with lots of kernels, it looks like this:

![screen shot 2017-06-22 at 8 28 03 am](https://user-images.githubusercontent.com/836375/27442490-333c9590-5725-11e7-82dd-96aff18519b7.png)

I imagine you wouldn't have the recently or currently open sections from the mockup since that's incorporated in other parts of the UI.

**Comment by rgbkrk** [comment]
![jupyterlablolono](https://user-images.githubusercontent.com/836375/27444478-58d0e9f4-572b-11e7-8b08-67cdbe101894.png)

**Comment by ellisonbg** [comment]
Nice! Thanks for posting the mockups. This is more-or-less exactly where we are headed - although maybe not quite as flat of a visual design - but I really like the flat look of your mockups - will play with it. Did you see the mockups at the bottom of this issue?

https://github.com/jupyterlab/jupyterlab/issues/2468

I am working on this today and will post updates soon. But I am strongly +1 on:

* Having activity based sections (Notebooks, Consoles).
* Using cards with kernel logos to indicate the kernel.

This type of UI presents users with a single decision and effectively uses different visual encodings (color/shape of logos, position in sections) so users don't have to read or think (about this).

**Comment by rgbkrk** [comment]
> This type of UI presents users with a single decision and effectively uses different visual encodings (color/shape of logos, position in sections) so users don't have to read or think (about this).

Definitely! Thank you.

**Comment by blink1073** [comment]
Thanks Kyle!  Moving discussion to #2468.
