### ISSUE TITLE
Launcher: kernels with varying lenth name gives wobbly effect

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyterlab/jupyterlab#2537]
When you have a bunch of kernels with potentially longer names, the icons in the launcher are no longer aligned, which gives a bit a 'wobbly' untidy effect:

![screenshot from 2017-06-27 09-17-09](https://user-images.githubusercontent.com/1020496/27575363-d12b515e-5b19-11e7-8e02-ca25a7ef68cd.png)

It is not the most important issue, but since this is the first thing you see when starting Jupyter Lab, it gives a bit an unprofessional look IMO.

**Comment by blink1073** [comment]
Thanks for the feedback, @jorisvandenbossche!  We are currently redesigning the launcher, with discussion in https://github.com/jupyterlab/jupyterlab/issues/2468.   The vertical alignment was addressed in https://github.com/jupyterlab/jupyterlab/pull/2506, but has not yet been released.

**Comment by jorisvandenbossche** [comment]
Ah, somehow I thought the redesign already happened. Mockups are looking much better!
