### ISSUE TITLE
Reopen launcher when all tabs are closed

### ISSUE THREAD

**Issue by lucbouchard1** [jupyterlab/jupyterlab#2538]
I talked to @cameronoelsen about this today. Right now, when all the tabs are closed you are left with a blank grey screen:
![issue](https://user-images.githubusercontent.com/10227519/27602308-3238a408-5b27-11e7-84e0-32f4a2ad3fff.gif)
We thought the launcher window should be reopened instead.

**Comment by cameronoelsen** [comment]
+1 on this as well.  I believe the behavior of opening a new launcher when nothing else is there is better than the grey blank space. Pinging @ellisonbg to see what he thinks of this!

**Comment by dhirschfeld** [comment]
Case in point: I have been asked by a noob how to get the launcher back.

**Comment by ian-r-rose** [comment]
The application now reopens a launcher when there are no activities. Closing as fixed.
