### ISSUE TITLE
Converting notebook to pdf

### ISSUE THREAD

**Issue by marberi** [jupyterlab/jupyterlab#2541]
I managed to solved this issues by installing the right packages. The error
message was a bit cryptic, since it failed for an earlier problem than what
it could seem in the error message. It seems like the code should include
a test of what is installed to catch this problem.

When trying to run 
http://localhost:8888/nbconvert/pdf/Untitled.ipynb?download=true

it displays the error message [1]. By looking in the code and copying
the temporary latex directory, I traced the problem back to:

eriksen@bever:~/tmp/tmp/tmpK586Zu$ mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ectt1095
mktexpk: don't know how to create bitmap font for ectt1095.
mktexpk: perhaps ectt1095 is missing from the map file.

which could be solved by:
sudo apt install texlive-full

[1]
nbconvert failed: PDF creating failed, captured latex output:
This is BibTeX, Version 0.99d (TeX Live 2016)
The top-level auxiliary file: notebook.aux
I found no \citation commands---while reading file notebook.aux
I found no \bibdata command---while reading file notebook.aux
I found no \bibstyle command---while reading file notebook.aux
(There were 3 error messages)

**Comment by blink1073** [comment]
Thanks for the report!  Migrated to https://github.com/jupyter/nbconvert/issues/613.
