### ISSUE TITLE
Download doesn't work with Firefox

### ISSUE THREAD

**Issue by alanhdu** [jupyterlab/jupyterlab#2542]
In the file navigator, there's an option to download files when you right-click:
![image](https://user-images.githubusercontent.com/1914111/27612954-fb55f3ba-5b66-11e7-840a-2af65a3902d8.png)

On Firefox, the download button doesn't seem to do anything. Chrome lets you download things just fine though.

I'm using Firefox 55 beta (Developer Edition) on Ubuntu 16.04. This is a server running on `localhost:8888`, so there shouldn't be any weird firewalls or network things in the way.

**Comment by blink1073** [comment]
Thanks for the report!  #2544 has the fix.
