### ISSUE TITLE
Rendering notebook very slow in Firefox

### ISSUE THREAD

**Issue by alanhdu** [jupyterlab/jupyterlab#2543]
When opening large-ish notebooks (~50 code cells with lots of graphs) in Firefox, JupyterLab locks up for tens of seconds (it's so bad that Firefox always gives me a "unresponsive script"!). Switching notebook tabs does the same thing.

Opening the same notebook with the classic `jupyter notebook` is almost instantaneous. Opening the notebook in JupyterLab and Chrome has a noticeable stutter (maybe 1 second?) but *much* faster than Firefox.

I'm running Firefox Developer Edition (Firefox 55.0) on Ubuntu 16.04. This is super unfortunate -- the rest of JupyterLab is nice enough that I'm seriously considering just switching to Chrome or eating the constant 10-20 second delay just to get the rest of the goodies...

**Comment by sccolbert** [comment]
Thanks! We're actively working on this issue. We know what causes it and it's our current top priority.

**Comment by sccolbert** [comment]
c.f. #1639 and #2540

**Comment by blink1073** [comment]
Closing in favor of #1639.  Thanks again, @alanhdu!
