### ISSUE TITLE
Collapser does not collapse in Firefox

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#2545]
CC @ellisonbg 
![nocollapse](https://user-images.githubusercontent.com/5728311/27647885-9eca6f7e-5be1-11e7-8807-770e9b4cd917.png)

**Comment by ian-r-rose** [comment]
I suppose this CSS will be refactored due to #1639.

**Comment by blink1073** [comment]
I wasn't able to repro in Firefox 54.0 on OSX 10.12.5:

<image src="https://user-images.githubusercontent.com/2096628/27930719-41911024-625d-11e7-8fd6-c8dc6d00b8c6.png" width=300>

**Comment by ian-r-rose** [comment]
Hmm, I can no longer reproduce this either.
