### ISSUE TITLE
Make opening a comm accept buffers

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#2556]
Right now when we open a comm, we can set the data and metadata of the message, but we can't send buffers. It should be straightforward to add the buffers optional argument to the open call at https://github.com/jupyterlab/jupyterlab/blob/080a21f5a4d8e7a90f5b15572baa4add7776c3d1/packages/services/src/kernel/comm.ts#L105

**Comment by vidartf** [comment]
I opened a similar issue on the notebook repo jupyter/notebook#2730.
