### ISSUE TITLE
Jupyterlab 0.24.1 does not work on jupyterhub

### ISSUE THREAD

**Issue by DevMui** [jupyterlab/jupyterlab#2565]
![image](https://user-images.githubusercontent.com/19495980/27798472-5f0f5532-5fdf-11e7-86e9-420844049da9.png)

It worked without any problem on `0.22.1` however stopped working after the upgrade to `0.24.1`.
I am not using `jupyter-labhub` extension and any other `labextensions`.

Below is `anaconda` environment package list for `jupyter`-related ones. I rolled back it to `0.22` and it works again. Let me know if you have any question.
![image](https://user-images.githubusercontent.com/19495980/27798542-a4ac9708-5fdf-11e7-8227-5e963894577a.png)
![image](https://user-images.githubusercontent.com/19495980/27798558-b608ac3a-5fdf-11e7-87e7-16d4108a5fbc.png)

**Comment by blink1073** [comment]
Hi @DevMui, does it work if you remove `/opt/anaconda3/share/jupyter/lab`?

**Comment by DevMui** [comment]
Surprisingly it works now. Thank you!

**Comment by blink1073** [comment]
Great!  I suspected it was due to incompatible files in that directory (our directory layout has changed).

**Comment by DevMui** [comment]
Just some additional question - when I install some `labextensions` such as `labhub` or `google-drive`, it stops working with the same error that I described above. Is this possibly related?

Deleting `/opt/anaconda3/share/jupyter/lab` also deletes all `labextensions` so the error can't be solved with the solution.

**Comment by blink1073** [comment]
It looks like you need to specify a different `JUPYTERLAB_DIR` environment variable to a writable location, such as `~/.jupyter/lab`.  See also https://github.com/jupyterlab/jupyterlab/blob/master/docs/extensions_user.md#advanced-usage.
