### ISSUE TITLE
Scroll with j/k keys

### ISSUE THREAD

**Issue by mrocklin** [jupyterlab/jupyterlab#2566]
When scrolling around the notebook with vim-style j and k keys I find that while the active cell moves around the scroll bar does not.  I have not yet found a way to scroll the notebook without making use of the mouse.

I did quick scan through open issues and didn't see this.  My apologies if this was already reported or addressed.

**Comment by blink1073** [comment]
Confirmed the bug, thanks!

**Comment by ellisonbg** [comment]
We will have to fix this in a subtle manner as the simple way of doing it is to focus the new selected/active cell. However, that has caused a lot of pain with jumps in the notebook. We may need to distinguish between keyboard based selection and mouse based selection. Marking as beta.

**Comment by mrocklin** [comment]
Thanks for the fast turnaround.  I'll have to raise more issues ... :-)
