### ISSUE TITLE
where is the property '_cwd' in docmanager ?

### ISSUE THREAD

**Issue by rydeng** [jupyterlab/jupyterlab#2575]
/**
   * The current working directory of the document manager.
   *
   * #### Notes
   * This attribute is DEPRECATED. It is intended for use as a stopgap measure
   * to create some notion of an application-level working directory for
   * launching activities that need a sensible starting directory. It will be
   * replaced with another concept in later releases.
   */
  get cwd(): string {
    return this._cwd;
  }
  set cwd(cwd: string) {
    this._cwd = cwd;
  }

Hi, does someone know the '_cwd' replaced by what?

**Comment by blink1073** [comment]
The document manager will not have a working directory, only the file browser(s) that use the document manager.  The [IFileBrowserFactory](https://github.com/jupyterlab/jupyterlab/blob/master/packages/filebrowser-extension/src/index.ts#L108) plugin can be used to get the cwd of the current file browser as `factory.tracker.currentWidget.model.path`.

**Comment by ellisonbg** [comment]
We are going to need the `cwd` for the git extension we are building too.
