### ISSUE TITLE
ipywidgets compatibility

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#2577]
Hi, 

I just installed the latest master of JLab and tried using ipywidgets but I am getting the following error:
`Jupyter notebooks: [IPKernelApp] WARNING | Widget Javascript not detected. It may not be installed properly.`

even though I have enabled them using the following steps in a conda environment
`pip install ipywidgets`
`jupyter nbextension install widgetsnbextension --py --sys-prefix`
`jupyter nbextension enable --py --sys-prefix widgetsnbextension`

Any reason why? If, this version is not compatible with ipywidgets, then can you help me with the version of JLab that is compatible with them?

**Comment by sccolbert** [comment]
Distributed extensions are compiled against a particular released version of JLab. They aren't guaranteed to run against master. I'd suggest running the JLab version which is currently supported by widgets.

**Comment by jasongrout** [comment]
With JLab 0.24.1 (not tested against master), do:

```
pip install ipywidgets --pre
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

It should be using ipywidgets 7.0.0 alpha 8.

**Comment by rsinha25** [comment]
Thanks for that! It worked in master.

So I checked out to v0.24.0 and did the following:
`npm install`
`npm run clean && npm run build:main`

Get the following error

`
../apputils/src/clientsession.ts(601,5): error TS2322: Type 'Promise<void | IKernelConnection>' is not assignable to type 'Promise<IKernelConnection>'.
  Type 'void | IKernelConnection' is not assignable to type 'IKernelConnection'.
    Type 'void' is not assignable to type 'IKernelConnection'.
../codeeditor/src/editor.ts(197,9): error TS2322: Type 'ModelDB' is not assignable to type 'IModelDB'.
  Types of property 'createList' are incompatible.
    Type '(path: string) => IObservableUndoableList<JSONValue>' is not assignable to type '<T extends JSONValue>(path: string) => IObservableUndoableList<T>'.
../console-extension/src/index.ts(264,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
  Index signatures are incompatible.
    Type 'ReadonlyJSONValue' is not assignable to type 'JSONValue'.
      Type 'ReadonlyJSONObject' is not assignable to type 'JSONValue'.
        Type 'ReadonlyJSONObject' is not assignable to type 'JSONArray'.
          Property 'length' is missing in type 'ReadonlyJSONObject'.
../console-extension/src/index.ts(278,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../console-extension/src/index.ts(292,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../console-extension/src/index.ts(306,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../console-extension/src/index.ts(320,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../console-extension/src/index.ts(337,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../console-extension/src/index.ts(351,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../console-extension/src/index.ts(393,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../coreutils/src/modeldb.ts(307,5): error TS2322: Type 'Signal<ObservableValue, IChangedArgs>' is not assignable to type 'ISignal<this, IChangedArgs>'.
  Types of property 'connect' are incompatible.
    Type '(slot: Slot<ObservableValue, IChangedArgs>, thisArg?: any) => boolean' is not assignable to type '(slot: Slot<this, IChangedArgs>, thisArg?: any) => boolean'.
      Types of parameters 'slot' and 'slot' are incompatible.
        Types of parameters 'sender' and 'sender' are incompatible.
          Type 'ObservableValue' is not assignable to type 'this'.
../coreutils/src/modeldb.ts(374,7): error TS2420: Class 'ModelDB' incorrectly implements interface 'IModelDB'.
  Types of property 'createList' are incompatible.
    Type '(path: string) => IObservableUndoableList<JSONValue>' is not assignable to type '<T extends JSONValue>(path: string) => IObservableUndoableList<T>'.
      Type 'IObservableUndoableList<JSONValue>' is not assignable to type 'IObservableUndoableList<T>'.
        Type 'JSONValue' is not assignable to type 'T'.
          Type 'string' is not assignable to type 'T'.
../coreutils/src/settingregistry.ts(212,5): error TS2322: Type 'IDatastore<IPlugin, IPlugin> | StateDB' is not assignable to type 'IDatastore<IPlugin, IPlugin>'.
  Type 'StateDB' is not assignable to type 'IDatastore<IPlugin, IPlugin>'.
    Types of property 'fetch' are incompatible.
      Type '(id: string) => Promise<JSONObject>' is not assignable to type '(id: string) => Promise<IPlugin>'.
        Type 'Promise<JSONObject>' is not assignable to type 'Promise<IPlugin>'.
          Type 'JSONObject' is not assignable to type 'IPlugin'.
            Property 'id' is missing in type 'JSONObject'.
../docmanager/src/dialogs.ts(74,3): error TS2322: Type 'Promise<Widget>' is not assignable to type 'Promise<IModel>'.
  Type 'Widget' has no properties in common with type 'IModel'.
../docmanager/src/dialogs.ts(159,5): error TS2322: Type 'Promise<IModel>' is not assignable to type 'Promise<Widget>'.
  Type 'IModel' is not assignable to type 'Widget'.
    Property 'dispose' is missing in type 'IModel'.
../docmanager/src/widgetmanager.ts(266,5): error TS2322: Type 'Promise<boolean | void>' is not assignable to type 'Promise<boolean>'.
  Type 'boolean | void' is not assignable to type 'boolean'.
    Type 'void' is not assignable to type 'boolean'.
../docregistry/src/context.ts(298,5): error TS2322: Type 'Promise<IModel>' is not assignable to type 'Promise<ICheckpointModel>'.
../filebrowser/src/listing.ts(376,5): error TS2322: Type 'Promise<void | IModel[]>' is not assignable to type 'Promise<void>'.
  Type 'void | IModel[]' is not assignable to type 'void'.
    Type 'IModel[]' is not assignable to type 'void'.
../filebrowser/src/listing.ts(426,5): error TS2322: Type 'Promise<void | IModel[]>' is not assignable to type 'Promise<void>'.
../filebrowser/src/listing.ts(458,5): error TS2322: Type 'Promise<void | void[]>' is not assignable to type 'Promise<void>'.
  Type 'void | void[]' is not assignable to type 'void'.
    Type 'void[]' is not assignable to type 'void'.
../notebook-extension/src/index.ts(483,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(495,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(506,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(519,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(530,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(541,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(565,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(581,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(610,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(623,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(636,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(647,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(658,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(672,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(683,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(694,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(705,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(716,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(727,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(738,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(749,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(760,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(771,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(782,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(793,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(804,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(815,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(826,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(837,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(848,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(859,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(870,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(881,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(892,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(903,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(914,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(925,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(936,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(944,11): error TS2322: Type '{ path: string; preferredLanguage: string; activate: ReadonlyJSONValue; }' is not assignable to type 'JSONObject'.
../notebook-extension/src/index.ts(944,11): error TS2322: Type '{ path: string; preferredLanguage: string; activate: ReadonlyJSONValue; }' is not assignable to type 'JSONObject'.
  Property 'activate' is incompatible with index signature.
    Type 'ReadonlyJSONValue' is not assignable to type 'JSONValue'.
      Type 'ReadonlyJSONObject' is not assignable to type 'JSONValue'.
        Type 'ReadonlyJSONObject' is not assignable to type 'JSONArray'.
../notebook-extension/src/index.ts(956,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(967,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(978,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(989,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(1000,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook-extension/src/index.ts(1011,32): error TS2345: Argument of type 'ReadonlyJSONObject' is not assignable to parameter of type 'JSONObject'.
../notebook/src/actions.ts(926,50): error TS2345: Argument of type 'ICell' is not assignable to parameter of type 'IOptions'.
  Type 'IRawCell' has no properties in common with type 'IOptions'.
../notebook/src/actions.ts(928,54): error TS2345: Argument of type 'ICell' is not assignable to parameter of type 'IOptions'.
  Type 'IRawCell' has no properties in common with type 'IOptions'.
../notebook/src/actions.ts(930,49): error TS2345: Argument of type 'ICell' is not assignable to parameter of type 'IOptions'.
  Type 'IRawCell' has no properties in common with type 'IOptions'.
../outputarea/src/widget.ts(472,5): error TS2322: Type 'Promise<IShellMessage>' is not assignable to type 'Promise<IExecuteReplyMsg>'.
  Type 'IShellMessage' is not assignable to type 'IExecuteReplyMsg'.
    Types of property 'content' are incompatible.
      Type 'JSONObject' is not assignable to type 'IExecuteReply'.
        Property 'status' is missing in type 'JSONObject'.
../services/src/contents/index.ts(721,5): error TS2322: Type 'Promise<IModel>' is not assignable to type 'Promise<ICheckpointModel>'.
  Type 'IModel' is not assignable to type 'ICheckpointModel'.
    Property 'id' is missing in type 'IModel'.
../services/src/kernel/default.ts(398,5): error TS2322: Type 'Promise<IShellMessage>' is not assignable to type 'Promise<IInfoReplyMsg>'.
  Type 'IShellMessage' is not assignable to type 'IInfoReplyMsg'.
    Types of property 'content' are incompatible.
      Type 'JSONObject' is not assignable to type 'IInfoReply'.
        Property 'protocol_version' is missing in type 'JSONObject'.
../services/src/kernel/default.ts(421,5): error TS2322: Type 'Promise<IShellMessage>' is not assignable to type 'Promise<ICompleteReplyMsg>'.
  Type 'IShellMessage' is not assignable to type 'ICompleteReplyMsg'.
    Types of property 'content' are incompatible.
      Type 'JSONObject' is not assignable to type '{ matches: string[]; cursor_start: number; cursor_end: number; metadata: JSONObject; status: "err...'.
        Property 'matches' is missing in type 'JSONObject'.
../services/src/kernel/default.ts(441,5): error TS2322: Type 'Promise<IShellMessage>' is not assignable to type 'Promise<IInspectReplyMsg>'.
  Type 'IShellMessage' is not assignable to type 'IInspectReplyMsg'.
    Types of property 'content' are incompatible.
      Type 'JSONObject' is not assignable to type '{ status: "error" | "ok"; found: boolean; data: JSONObject; metadata: JSONObject; }'.
        Property 'status' is missing in type 'JSONObject'.
../services/src/kernel/default.ts(461,5): error TS2322: Type 'Promise<IShellMessage>' is not assignable to type 'Promise<IHistoryReplyMsg>'.
  Type 'IShellMessage' is not assignable to type 'IHistoryReplyMsg'.
    Types of property 'content' are incompatible.
      Type 'JSONObject' is not assignable to type '{ history: JSONValue[]; }'.
        Property 'history' is missing in type 'JSONObject'.
../services/src/kernel/default.ts(515,5): error TS2322: Type 'Promise<IShellMessage>' is not assignable to type 'Promise<IIsCompleteReplyMsg>'.
  Type 'IShellMessage' is not assignable to type 'IIsCompleteReplyMsg'.
    Types of property 'content' are incompatible.
      Type 'JSONObject' is not assignable to type '{ status: string; indent: string; }'.
        Property 'status' is missing in type 'JSONObject'.
../services/src/kernel/default.ts(533,5): error TS2322: Type 'Promise<IShellMessage>' is not assignable to type 'Promise<ICommInfoReplyMsg>'.
  Type 'IShellMessage' is not assignable to type 'ICommInfoReplyMsg'.
    Types of property 'content' are incompatible.
      Type 'JSONObject' is not assignable to type '{ comms: { [id: string]: string; }; }'.
        Property 'comms' is missing in type 'JSONObject'.
../services/src/manager.ts(46,49): error TS2559: Type 'IOptions' has no properties in common with type 'IOptions'.
../services/src/serverconnection.ts(358,5): error TS2322: Type 'Promise<{}>' is not assignable to type 'Promise<IResponse>'.
  Type '{}' is not assignable to type 'IResponse'.
    Property 'event' is missing in type '{}'.
../services/src/session/default.ts(44,7): error TS2420: Class 'DefaultSession' incorrectly implements interface 'ISession'.
  Types of property 'terminated' are incompatible.
    Type 'Signal<this, void>' is not assignable to type 'ISignal<ISession, void>'.
      Types of property 'connect' are incompatible.
        Type '(slot: Slot<this, void>, thisArg?: any) => boolean' is not assignable to type '(slot: Slot<ISession, void>, thisArg?: any) => boolean'.
          Types of parameters 'slot' and 'slot' are incompatible.
            Types of parameters 'sender' and 'sender' are incompatible.
              Type 'this' is not assignable to type 'ISession'.
                Type 'DefaultSession' is not assignable to type 'ISession'.
                  Types of property 'iopubMessage' are incompatible.
                    Type 'ISignal<this, IMessage>' is not assignable to type 'ISignal<ISession, IIOPubMessage>'.
                      Type 'IMessage' is not assignable to type 'IIOPubMessage'.
                        Types of property 'channel' are incompatible.
                          Type 'Channel' is not assignable to type '"iopub"'.
                            Type '"shell"' is not assignable to type '"iopub"'.
../services/src/session/default.ts(179,5): error TS2322: Type 'Promise<DefaultSession>' is not assignable to type 'Promise<ISession>'.
  Type 'DefaultSession' is not assignable to type 'ISession'.
    Types of property 'iopubMessage' are incompatible.
      Type 'ISignal<DefaultSession, IMessage>' is not assignable to type 'ISignal<ISession, IIOPubMessage>'.
        Type 'IMessage' is not assignable to type 'IIOPubMessage'.
../services/src/session/default.ts(497,35): error TS2559: Type 'ISettings' has no properties in common with type 'IOptions'.
../services/src/session/default.ts(694,5): error TS2322: Type 'Promise<DefaultSession>' is not assignable to type 'Promise<ISession>'.

npm ERR! Darwin 15.6.0
npm ERR! argv "/../.nvm/versions/node/v7.4.0/bin/node" "/../.nvm/versions/node/v7.4.0/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @jupyterlab/all-packages@0.7.1 build: `tsc && node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @jupyterlab/all-packages@0.7.1 build script 'tsc && node build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @jupyterlab/all-packages package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && node build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @jupyterlab/all-packages
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @jupyterlab/all-packages
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /../../jupyterlab/packages/all-packages/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/../.nvm/versions/node/v7.4.0/bin/node" "/../.nvm/versions/node/v7.4.0/bin/npm" "run" "build:packages"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ build:packages: `cd packages/all-packages && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:packages script 'cd packages/all-packages && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd packages/all-packages && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /../../jupyterlab/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/../.nvm/versions/node/v7.4.0/bin/node" "/../.nvm/versions/node/v7.4.0/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ build: `npm run build:packages && cd jupyterlab && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script 'npm run build:packages && cd jupyterlab && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:packages && cd jupyterlab && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /../../jupyterlab/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/../.nvm/versions/node/v7.4.0/bin/node" "/../.nvm/versions/node/v7.4.0/bin/npm" "run" "build:main"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! @ build:main: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:main script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /../../jupyterlab/npm-debug.log`


What am I missing?

**Comment by rsinha25** [comment]
The current master builds successfully.

**Comment by blink1073** [comment]
Closing as fixed, feel free to reopen if you disagree.

**Comment by rsinha25** [comment]
Hi, 
Im on release 0.25.0 
Tried to install ipywidgets as below.

`pip install ipywidgets --pre
jupyter labextension install @jupyter-widgets/jupyterlab-manager`

Get the following error for labextension install:

>npm pack @jupyter-widgets/jupyterlab-manager
Traceback (most recent call last):
  File "/../bin/jupyter-labextension", line 11, in <module>
    load_entry_point('jupyterlab', 'console_scripts', 'jupyter-labextension')()
  File "/../lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/../lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/../jlab_0.25/jupyterlab/labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "/../lib/python3.5/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/../jlab_0.25/jupyterlab/labextensions.py", line 57, in start
    for arg in self.extra_args]
  File "/../jlab_0.25/jupyterlab/labextensions.py", line 57, in <listcomp>
    for arg in self.extra_args]
  File "/../jlab_0.25/jupyterlab/commands.py", line 116, in install_extension
    raise ValueError(msg)
ValueError:
"@jupyter-widgets/jupyterlab-manager@0.23.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
Required	Actual	Package
^0.8.0  	^0.7.0	@jupyterlab/application
^0.8.0  	^0.7.0	@jupyterlab/notebook
^0.8.0  	^0.7.0	@jupyterlab/rendermime
