### ISSUE TITLE
Vega file does not render

### ISSUE THREAD

**Issue by hadim** [jupyterlab/jupyterlab#2579]
Using last `master` (7e16646799114213dc1f85818761f57fc296c02d), Vega files (v2 ) does not render. The Vega window opens correctly but stay blank.

Using Altair (https://github.com/altair-viz/altair/pull/216), I can plot in a notebook with:

```python
import pandas as pd
from altair import Chart

from altair import enable_mime_rendering
enable_mime_rendering()

data = pd.DataFrame({'x': [1, 2, 3], 'y': [2, 1, 2]})
chart = Chart(data).mark_line().encode(x='x', y='y')
chart
```

Note that Vega lite files are ok.

**Comment by sccolbert** [comment]
Master is not necessarily stable at all times. We are working through some active churn with the rendermime code at the moment. If there is a problem with a *released* version, please let use know!

**Comment by hadim** [comment]
Ok. No problem.

**Comment by ellisonbg** [comment]
I worked with this person on gitter and asked them to open this as a reminder to me to fix this. In spite of the ongoing refactor, this should work in master and I am a bit puzzled as to why it doesn't. Reopening for me to track this down.
