### ISSUE TITLE
Bundle renderer extensions with jupyterlab

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#2587]
As discussed at the Spring Team Meeting, JupyterLab should ship with default renderers for common data types such as JSON, GeoJSON, Plotly, etc. 

I have created a branch where this is implemented in the jupyterlab repo (because the @jupyterlab/rendermime-interfaces package has not been published yet) and it's working: https://github.com/gnestor/jupyterlab/tree/renderers

I am working on the jupyter-renderers repo that will be the home for these renderers: https://github.com/jupyterlab/jupyter-renderers/tree/rendermime-refactor

@blink1073 Given the latest rendermime refactor, what is the plan for installing renderer extensions? Will there be a separate command? I tested and `jupyter labextension link` isn't working for renderers as is.

Lastly, what is the plan for bundling these renderers with distributions of jupyterlab while keeping them in their own repo? I think this will largely depend on the answer above.

**Comment by blink1073** [comment]
`jupyter labextension link` should work with renderer extensions after 0.25.0 is published.

I think we still need some more discussion about which extensions should be included by default, and whether the ones included by default should in in this repo.

The workflow for "external core" packages could look like the following, but requires too many steps and coordinations to make a release in my opinion:
- Use the `addsibling` method with CI to keep the external package in sync as in [here](https://github.com/jupyterlab/jupyterlab-google-drive/blob/998296a1ac668cba74d6f0e34bddd5610698487f/.travis.yml#L14)
- Publish the JupyterLab npm packages
- Publish the external npm packages
- Create the JupyterLab core bundle by adding the external core packages temporarily to `package.json`, and then removing them
- Publish the JupyterLab python package

**Comment by ellisonbg** [comment]
Here is how I am thinking:

* Once a version of jupyterlab is released that has the needed rendermime interfaces and they are stable.
* Then we can create versions of the renderer extensions that target that API.
* The following version of jupyterlab can include those external packages in the shipped build.

But this will require the rendermime APIs to stabilize a bit more. For now, let's plan on having these packages be external jupyterlab extensions/packages. We plan on cutting a new lab release tomorrow, so you can then release versions of them.

**Comment by gnestor** [comment]
Ok, so once 0.25.0 is published (and e.g. @jupyterlab/jsonviewer is published), users should be able to do `jupyter labextension install @jupyterlab/jsonviewer`?

Regarding naming, it looks like we have `csvviewer` and `csvviewer-extension` and we have `vega`. Should we adopt a naming convention? I think "viewer" is fine, or "renderer". Additionally, the use of `mimeRenderer` in package.json and `MimeRenderer` and `MimeRendererFactory` is a bit incorrect because they create document renderers as well, so perhaps we should use `renderer` instead?

**Comment by blink1073** [comment]
Yes, `jupyter labextension install @jupyterlab/jsonviewer` should work after we publish.

`MimeRenderer` and `MimeRendererFactory` are only named that because `DocumentMimeRenderer` would be too long and they're in `docregistry` already.  

My vote is rename it to `vega-mimeRenderer` and keep the `mimeRenderer` metadata.

**Comment by gnestor** [comment]
Now that https://github.com/jupyterlab/jupyterlab/pull/3133 is merged (thank you @blink1073), we can now proceed with moving over some renderer extensions from jupyter-renderers. 

I will submit a WIP PR for this...
