### ISSUE TITLE
Uniform API for getting icons for file types

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2594]
We now have a set of icons for different type extensions/types. However, we are hardcoding the icons and file types in a few places (file browser and some dock panel tabs). There are other places these icons should show up (Tabs extension, running) but don't always. We should create an API that provides the icons to the rest of the system.

**Comment by blink1073** [comment]
This is what the [filetype](https://github.com/jupyterlab/jupyterlab/blob/master/packages/docregistry/src/registry.ts#L866) on the `DocumentRegistry` was intended to do.  We can add the known file types and icons when we create the `DocumentRegisry` [here](https://github.com/jupyterlab/jupyterlab/blob/23e4d5a24e4f0931207ca1ee5a913e52e03875ec/packages/application/src/index.ts#L72).

**Comment by dhirschfeld** [comment]
Somewhat related to #2472?  As I mentioned there a pluggable system similar to vscode would be a nice-to-have. It sounds like the document registry might allow that?
