### ISSUE TITLE
Make Consoles File-Backed

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#260]
This would allow consoles to be treated like any other kernel-backed object, and allow them to be used in the Document Registry.
- Create a file extension for consoles (`.jpcon`?)
- Save in notebook format but add a kernel id field to the metadata
- Saved to disk after each execution
- The console content is tied to a kernel session

**Comment by blink1073** [comment]
@afshin  and I talked about this and believe that we should use the checkpoint system for consoles, and not attempt to create a file.  We would create a checkpoint either periodically or after each execute, and there would be no visible file associated with the console.  We can internally use a file extension like `.jpconsole` to differentiate it from notebooks.  A user can export to a console session as a notebook or a static file.

cc @jasongrout @ellisonbg

**Comment by damianavila** [comment]
I really like the idea, in particular the possibility to export it to a notebook... because when you start a console session, you don't know ahead of time that the content could be useful as a notebook itself...

**Comment by fperez** [comment]
This ties into #391, and would also help with session restore (how do you get back to where you were if your *browser* crashes or if you reconnect from a different computer?).
