### ISSUE TITLE
Missing expand button after collapsing cells in Firefox

### ISSUE THREAD

**Issue by o2carr68** [jupyterlab/jupyterlab#2604]
In current master and using Firefox, expanding a cell after collapsing
**both** the input and the output leaves the output cell without the
"expand" icon, as can be seen in the following image:

![ff](https://user-images.githubusercontent.com/24479423/27933417-99558300-62a1-11e7-9ea7-6a365bc9313e.png)

For comparison, here is the result with Chromium:

![chromium](https://user-images.githubusercontent.com/24479423/27933430-a8d48cf4-62a1-11e7-8985-44560f10439e.png)

Note: Some actions in FF bring back the expand icon. For instance,
using the browser zoom, or hiding the notebook by going to another JL tab
and then switching back.

**Comment by blink1073** [comment]
Thanks for the report, @o2carr68! 

@ellisonbg, I was able to fix this by removing this rule, does that sound reasonable?

```css
.jp-Cell:not(.jp-mod-noOutputs) .jp-Cell-outputCollapser {
    min-height: 20px;
}
```

**Comment by ellisonbg** [comment]
This particular one doesn't seem to be relevant any longer as the collapser styling has changed. We have other issues with the collapser that need fixing though. I will open a separate issue for that.
