### ISSUE TITLE
Can not horizontally scroll wide dataframes in the notebook

### ISSUE THREAD

**Issue by mrocklin** [jupyterlab/jupyterlab#2614]
When viewing a wide Pandas dataframe in the JupyterLab notebook the user is unable to scroll horizontally to see columns that are out of view.

**Comment by blink1073** [comment]
I believe this is fixed in 0.25:

<image src="https://user-images.githubusercontent.com/2096628/27974294-fbcc6676-6322-11e7-93fd-f702663eb4f2.png" width=500>

**Comment by blink1073** [comment]
Closing as fixed, please feel free to reopen if you see it in 0.25 or later.
