### ISSUE TITLE
Latex markdown jiggle on toolbar click

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#2622]
I'll let a screen capture show what I mean (click highlighting was unfortunately off): 

![jlab-latex-jiggle](https://user-images.githubusercontent.com/510760/27958021-6f6f757a-6321-11e7-8325-c52b2ec58a3d.gif)

You can see that the everything below the start of the latex markdown jumps up and down one (or more) pixel(s) every time I click the toolbar. If the mouse button is held down, the offset is kept until the mouse button is released. Note that this does *not* happen if an editor is focused.

**Comment by RaphaelArkadyMeyer** [comment]
Hey, I'm having issues reproducing your bug. Could you tell me the jupyterlab version you're running, the browser you're recording and potentially a minimal notebook document that causes this bug?

**Comment by vidartf** [comment]
This was on master at the date of the original post, and happened in both Firefox and Chrome (latest stable). I'll have a look later if I can find the notebook used in the recording. If I can still reproduce it on current master I'll share the notebook in question.

**Comment by vidartf** [comment]
I looked this up again (the notebook used was examples/notebook/test.ipynb), and I was not able to reproduce this on 0.27. Closing for now.
