### ISSUE TITLE
Add clear output button to notebook

### ISSUE THREAD

**Issue by mrocklin** [jupyterlab/jupyterlab#2623]
I frequently used the "Restart and clear output" option in the Jupyter notebook.  I'm happy to see the restart button on the jlab notebook.  Perhaps add a clear output button just to the right?

This is a design decision and pretty subjective.  Feel free to close.  Is there a better place to express opinions like this?

**Comment by blink1073** [comment]
We have a "Restart & Clear Outputs" in the command palette.  We have purposely kept the toolbar as slim as possible since they can be tiled horizontally.  The notebook top-level menu is already quite large.  My vote is to keep it as a command only.

**Comment by vidartf** [comment]
Suggestion: With #2582 it is possible to add commands to toolbars. Maybe an interface could be exposed to allow the user to add the commands of their choice to the toolbar?

**Comment by ellisonbg** [comment]
We already have a "Clear Output" action in the context menu of a given cell. Maybe a "Clear All Outputs" below that in the notebook section?

**Comment by mrocklin** [comment]
I've grown quite fond of the command palette, so I'm personally fine now.  Happy to close.
