### ISSUE TITLE
Pdb in notebook doesn't interleave commands and output

### ISSUE THREAD

**Issue by mrocklin** [jupyterlab/jupyterlab#2624]
![image](https://user-images.githubusercontent.com/306380/27965075-7abac524-6308-11e7-9c81-a6db5e7cdc63.png)

**Comment by nkabram** [comment]
Still happening as of 8/8/18.

**Comment by blink1073** [comment]
Hi @nkabram, which version of JupyterLab do you have (and what OS/browser)?  It is working for me locally on 0.33.6, MacOS 10.13, FireFox 61:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/2096628/43830022-fc827c3c-9ac5-11e8-9f82-d57776cc65f4.png">

**Comment by blink1073** [comment]
Should have been fixed in https://github.com/jupyterlab/jupyterlab/pull/4848.

**Comment by blink1073** [comment]
Closing as fixed, let us know if you see otherwise
