### ISSUE TITLE
cythonmagic html loses interactivity

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#2634]
To reproduce, create a notebook with
```
import cython
cython.load_ipython_extension(get_ipython())
```
in one cell
and e.g.
```
%%cython -a
def g():
    a = 0
    for i in range(10):
        a += i
    return a
```
in another.
Observe that that the output of the second cell is interactive html (expands to C-code upon clicking every line) in the classic notebook, but it is not interactive in jupyterlab.

js console shows `Uncaught ReferenceError: toggleDiv is not defined at HTMLPreElement.onclick (lab:1)`.

**Comment by akhmerov** [comment]
Probably related to the javascript being disabled, and rather belongs to the cython side since they are maintaining the `%%cython` magic. Would they need to implement their own jlab extension for providing interactive html?

**Comment by blink1073** [comment]
It looks like the magic is using `jQuery`, which is not globally defined in JupyterLab (but was in the notebook).  Yes, this would be a case that required a jlab extension.

**Comment by akhmerov** [comment]
I opened a corresponding issue on the cython side.

**Comment by scoder** [comment]
I'd be happy to see a pull request for Cython by someone who understands (a bit) how jupyterlab wants these things to work. The code isn't complex, it's not using jQuery, and it's right here:

https://github.com/cython/cython/blob/ac4cbf0265735979ea17cedf051652f8603b7034/Cython/Compiler/Annotate.py#L82
