### ISSUE TITLE
Make all shortcuts discoverable

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#2637]
I believe right now there's no way to find out e.g. command palette (ctrl+shift+C) and file browser (ctrl+shift+f).

**Comment by akhmerov** [comment]
The settings editor exposes all shortcuts in v0.31. I am however unsure if this is the optimal way (the user needs to read a lot of json).

**Comment by ian-r-rose** [comment]
There are also a lot of commands that could be mapped to shortcuts but are not by default.  The ids for those commands are not discoverable from the UI, or even from the shortcuts JSON file.

**Comment by basnijholt** [comment]
I would like to completely disable the search bar that shows up when pressing `Command + F`:

![screen shot 2018-06-05 at 11 23 32](https://user-images.githubusercontent.com/6897215/41129190-cbd83fa8-6a65-11e8-9872-9397d818f482.png)

However this doesn't seem to be possible.

**Comment by jasongrout** [comment]
See #5268 for a fix for the shortcuts for the sidebar tabs.

**Comment by jasongrout** [comment]
Setting back to Future since the title request was about finding *all* keyboard shortcuts.

**Comment by akhmerov** [comment]
`@jupyterlab/shortcutui` gets close to achieving this goal, but it also doesn't list command palette, and probably some other shortcuts.

**Comment by cocoaaa** [comment]
"New View for Notebook" is also not visible. It is missing in [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook-extension/src/index.ts) as well.  @jasongrout, could you tell me what is the command ID for this?

**Comment by jtpio** [comment]
Linking to https://github.com/jupyterlab/jupyterlab/pull/11960, which explores displaying shortcuts based on the current active element.
