### ISSUE TITLE
split cell from notebook menu

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#2638]
I find the "split cell" option in the notebook menu counter-intuitive for the following reasons:

* It's the only edit mode command currently present in the notebook menu.
* If the user is in the command mode, and one cell is selected, this cell will be split according to the cursor position currently invisible to the user.

These are both minor issues, so maybe status quo is preferable.

**Comment by ellisonbg** [comment]
We have refactored the menus, and there is now a split cell item in the context menu for a cell and a split cell item in the edit menu. Closing.
