### ISSUE TITLE
performance: slow toggling to a large notebook

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#2639]
I observed this in chrome in 0.25.1, so it's probably not related to the firefox performance issue.

Toggling from a different tab to a large-ish notebook causes a noticeable lag (1-2 seconds in my case). Same happens when moving a large notebook to a new window.

**Comment by Juanlu001** [comment]
I still see this with the latest version, for instance using these notebooks:

https://github.com/jakevdp/PythonDataScienceHandbook

**Comment by jasongrout** [comment]
For cross-referencing, this likely is related or the same issue as #1639 (i.e., the general problem is probably not just firefox).
