### ISSUE TITLE
Multiple launcher instances

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#2641]
Right now repeated clicking on "+" in the file browser or selecting "new file" in the file menu will create multiple instances of launcher. Consider instead switching focus to an already existing launcher if there is one.

**Comment by blink1073** [comment]
We intentionally did this so you could create a couple of launchers, move them to the appropriate locations, in the main area, and then select the activities to launch.

**Comment by akhmerov** [comment]
I see. Seems a bit counter-intuitive to me, but feel free to close.

**Comment by ellisonbg** [comment]
As @blink1073 mentioned, it was intentional, so let's keep it as is for now and see what feedback we get.
