### ISSUE TITLE
running javascript in notebooks v0.25.0

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#2645]
Hi,
I am trying to execute a script using %%html in JLab 0.25.0, but it doesn't seem to be working. Should I try something else to be able to execute JS in the notebook?

Here's what used to work before:
`%%html`
`<script> console.log("hello")</script>`

**Comment by blink1073** [comment]
We have disabled the execution of scripts in 0.25.0, preferring the extension system for client side execution.
