### ISSUE TITLE
why is function ’reconnect‘ not used?

### ISSUE THREAD

**Issue by rydeng** [jupyterlab/jupyterlab#2648]
/**
   * Reconnect to a disconnected kernel.
   *
   * #### Notes
   * Used when the websocket connection to the kernel is lost.
   */
  reconnect(): Promise<void> {
    this._isReady = false;
    if (this._ws !== null) {
      // Clear the websocket event handlers and the socket itself.
      this._ws.onopen = null;
      this._ws.onclose = null;
      this._ws.onerror = null;
      this._ws.onmessage = null;
      this._ws.close();
      this._ws = null;
    }
    this._updateStatus('reconnecting');
    this._createSocket();
    return this._connectionPromise.promise;
  }

**Comment by blink1073** [comment]
Hi @rydeng, we are tracking this in https://github.com/jupyterlab/jupyterlab/issues/2526.
