### ISSUE TITLE
How to link to other notebooks within jupyterlab?

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#2649]
In the current notebooks structure, if I link to a notebook like:

`[mylink](./ntbks/my_notebook.ipynb)`, it'll automatically open the link within the notebook UI (in another tab).

What's the best way to do this with jupyter lab? If I click on a link such as above, it opens the file in raw text in another tab, rather than from within the jupyterlab UI.

**Comment by ellisonbg** [comment]
It *should* work the same as the classic notebook. If it doesn't it is a bug. Marking for Beta...

**Comment by blink1073** [comment]
I just confirmed this, working on a fix now.

**Comment by choldgraf** [comment]
nice, thanks @blink1073 !

one thought: it might be good to capture right-clicks for these links, since many users (e.g. myself) have gotten used to doing this for clicking open new notebooks, and if it isn't captured it'll try to open a new tab which isn't what jlab wants I assume!

**Comment by blink1073** [comment]
Right clicking brings up our own context menu, which can be overridden by holding down the SHIFT key.

**Comment by choldgraf** [comment]
oops - I meant to say "third click", which some people map onto "open a new tab w/ this link". But now I feel like we're getting into the territory of "too much of an edge case to make an exception for this" :-)

**Comment by blink1073** [comment]
Ah, I don't have a clear sense of whether that should open a new tab in JupyterLab or the browser.

**Comment by choldgraf** [comment]
ya that's why I'm thinking this may not be a necessary fix...maybe somebody else can weigh in? Otherwise I'll close this issue

**Comment by scottwsides** [comment]
Sorry to revisit this issue... but I can't get jupyterlab notebooks to open from a command (or link) in a separate jupyterlab notebook. Can someone explain exactly how this is done? (or point to the appropriate documentation. I've looked but I can't find it)

**Comment by jasongrout** [comment]
(just to follow up here - we resolved @scottwsides issue over in #6136)
