### ISSUE TITLE
nbconvert - xetex-def could not be installed

### ISSUE THREAD

**Issue by Alcampopiano** [jupyterlab/jupyterlab#2657]
Hello,

When converting notebook to pdf via command line with:
jupyter nbconvert --to pdf mynotebook.ipynb

or when using the notebook GUI,

I get lots of output with an error:
xetex-def could not be found

I have these dependencies installed with conda (4.3.22):
miktex version is 2.9.5987
pandoc version is 1.19.2
jupyterlab version is 0.24.1

In my miktex package manager, I can see that xetex.def is there but perhaps conda doesn't see it.

However, I do have xetex according to the output:
xetex --version is 3.14159265-2.6-0.99996

Any ideas how to fix this so I can use nbconvert to make pdfs?

Allan

Full Output:
nbconvert failed: PDF creating failed, captured latex output:
This is XeTeX, Version 3.14159265-2.6-0.99996 (MiKTeX 2.9.6100)
entering extended mode
(notebook.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 75 language(s) loaded.

(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\base\article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class

(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\base\size11.clo))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\base\fontenc.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\base\t1enc.def))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\psnfss\mathpazo.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\graphics\graphicx.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\graphics\keyval.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\graphics\graphics.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\graphics\trig.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\graphics-cfg\graphics.cfg)
======================================================================
starting package maintenance...
installation directory: C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9
package repository: ftp://ftp.muug.ca/mirror/ctan/systems/win32/miktex/tm/packages/
visiting repository ftp://ftp.muug.ca/mirror/ctan/systems/win32/miktex/tm/packages/...
repository type: remote package repository
loading lightweight database...
downloading ftp://ftp.muug.ca/mirror/ctan/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...

Unfortunately, the package xetex-def could not be installed.Please check the log file:
C:/Users/campopianoal/AppData/Local/MiKTeX/2.9/miktex/log/xelatex.log
======================================================================

(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\graphics-def\xetex.def)))
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\caption\caption.sty

(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\caption\caption3.st
y))
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\adjustbox\adjustbox
.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\xkeyval\xkeyval.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\xkeyval\xkeyval.tex
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\xkeyval\xkvutils.tex)))
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\adjustbox\adjcalc.s
ty)
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\adjustbox\trimclip.
sty
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\collectbox\collectb
ox.sty)
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\adjustbox\tc-xetex.
def))
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\ifoddpage\ifoddpage
.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\ltxmisc\varwidth.sty))
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\xcolor\xcolor.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\graphics-cfg\color.cfg))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\tools\enumerate.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\geometry\geometry.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\ifpdf.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\ifvtex.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\ifxetex\ifxetex.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\xelatex\xetexconfig\geometry.cfg))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\amsmath\amsmath.sty
For additional information on amsmath, use the `?' option.

(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\amsmath\amstext.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\amsmath\amsgen.sty))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\amsmath\amsbsy.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\amsmath\amsopn.sty))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\amsfonts\amssymb.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\amsfonts\amsfonts.sty))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\base\textcomp.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\base\ts1enc.def))
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\upquote\upquote.sty
)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\eurosym\eurosym.sty)
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\ucs\ucs.sty
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\ucs\uni-global.def)
)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\base\inputenc.sty

Package inputenc Warning: inputenc package ignored with utf8 based engines.

)
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\fancyvrb\fancyvrb.s
ty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\oberdiek\grffile.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\oberdiek\kvoptions.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\ltxcmds.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\kvsetkeys.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\infwarerr.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\etexcmds.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\ifluatex.sty))))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\pdftexcmds.sty))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\hyperref\hyperref.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\hobsub-hyperref.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\hobsub-generic.sty))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\oberdiek\auxhook.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\hyperref\pd1enc.def)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\00miktex\hyperref.cfg)
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\url\url.sty))

Package hyperref Message: Driver (autodetected): hxetex.

(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\hyperref\hxetex.def
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\hyperref\puenc.def)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\stringenc.sty)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\oberdiek\rerunfilecheck.sty))
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\tools\longtable.sty)
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\booktabs\booktabs.s
ty)
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\enumitem\enumitem.s
ty) (C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\ulem\ulem.sty)
No file notebook.aux.

(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\base\ts1cmr.fd)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\psnfss\t1ppl.fd)
(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\caption\ltcaption.s
ty)
*geometry* detected driver: pdftex
*geometry* verbose mode - [ preamble ] result:
* driver: pdftex
* paper: <default>
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes: 
* h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
* v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
* \paperwidth=614.295pt
* \paperheight=794.96999pt
* \textwidth=469.75502pt
* \textheight=650.43001pt
* \oddsidemargin=0.0pt
* \evensidemargin=0.0pt
* \topmargin=-37.0pt
* \headheight=12.0pt
* \headsep=25.0pt
* \topskip=11.0pt
* \footskip=30.0pt
* \marginparwidth=59.0pt
* \marginparsep=10.0pt
* \columnsep=10.0pt
* \skip\footins=10.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumnfalse
* \@twosidefalse
* \@mparswitchfalse
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)

(C:\Users\campopianoal\AppData\Roaming\MiKTeX\2.9\tex\latex\ucs\ucsencs.def)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\hyperref\nameref.sty
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\generic\oberdiek\gettitlestring.sty))

Package hyperref Warning: Rerun to get /PageLabels entry.

(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\psnfss\ot1ppl.fd)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\psnfss\omlzplm.fd)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\psnfss\omszplm.fd)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\psnfss\omxzplm.fd)
(C:\Users\campopianoal\AppData\Local\Continuum\Anaconda3\Library\miktex\texmfs\
install\tex\latex\psnfss\ot1zplm.fd)

LaTeX Warning: No \author given.

! Missing } inserted.
<inserted text> 
                }
l.281     $
           ('div.input').hide()
? 
! Emergency stop.
<inserted text> 
                }
l.281     $
           ('div.input').hide()
No pages of output.
Transcript written on notebook.log.

**Comment by blink1073** [comment]
Hi @Alcampopiano, I've migrated the issue to https://github.com/jupyter/nbconvert/issues/627.
