### ISSUE TITLE
File sidebar folder navigation 

### ISSUE THREAD

**Issue by danpf** [jupyterlab/jupyterlab#2692]
I was wondering if it would be possible to change the file explorer navigation sidebar to be similar to the one i screenshotted below. When I'm working on multiple projects, and each one has multiple sub-projects, I'd like to organize them in different notebooks. So it would be helpful to quickly open/change notebooks that are organized in different folders by project.  
It would be nice to be able to see ~3 levels of hierarchy.

![screenshot_20170712_110108](https://user-images.githubusercontent.com/16297104/28234462-ac3b90a4-68b4-11e7-8c10-7ab82387de20.png)

**Comment by hadim** [comment]
Nice UI but in my opinion it should be added as an option similar to windows/linux/mac file browsers.

**Comment by mocquin** [comment]
I second that proposition.

I've been trying jlab for web development, and it is a real pain to have to go back on and on between the differents folders.
A (activable) more general view, as proposed with a (customizable) number of folder hierarchy would be great. 
Or maybe this would make another extension apart from the current file explorer ?

**Comment by bollwyvl** [comment]
Yeah, I think an extension would be a good place to play around with
concepts, as file browsers are notoriously subjective. Having a
discoverable way to get said view is important, though, as right click is
brutal, so there might be value in having the default viewer be
undockable/copyable.

the smalltalk/Miller columns approach would be great for many kinds of
activities, which could basically stack n file viewers next to each other,
maybe even with a preview panel. But you'd probably have to commit to it
being the full width of the screen to be valuable.

The overlay fuzzy finder on GitHub and most text editors is wonderful, but
not compatible with all contents managers for performance reasons...

The breadcrumbs as drop-downs used by e.g. pycharm bother me, but some
folks like them. It could be okay, even if full width, as it's one line...
Especially if in the bottom area.

And king of them all, the command line,  might be really great, but also
might be a bit heavy for most folks. Perhaps the command palette or a
subclass could grow some knowledge of files.

**Comment by timkpaine** [comment]
FYI https://github.com/youngthejames/jupyterlab_filetree

**Comment by danpf** [comment]
that's awesome! thank you for the ping! I guess this is solved then!
