### ISSUE TITLE
UX when server connection is lost

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#270]
So I killed my jupyterlab server to see how the UI responded :-P 

The "Server connection lost" on faded background in the file browser is neat !
I think it deserves to be full-screen. 

First this will leave us more space to write a more ample error messages, like "check your internet connection", or "this screen will disappear as soon as connection is re-established", or a "retry" button, and secondly, it will prevent user from doing potential harmful action like closing a tab without being able to save. 

Second, if the file browser is not visible, users could not notice the connection is down. Which is a good thing, it show that the UI is resilient to server disconnection, but a few things might be off, like the console showing and infinitely busy kernel. 

BTW I realized that with sever down one cannot close or open a `console` tab, but it's possible to do so with terminals. I totally understand that it's far from being a priority to have either, just pointing out an inconsistency in case it has deeper consequences.

**Comment by tgeorgeux** [comment]
This is full screen now, I am closing this issue.
