### ISSUE TITLE
Feature Request: Shortcut to collapse the entire work space into a single area with tabs

### ISSUE THREAD

**Issue by tobsecret** [jupyterlab/jupyterlab#2706]
After arranging my different documents in the interface (for example a notebook on the left and a shell on the top right and a console on the bottom right) how do I revert that interface to just a browser-style interface with a bunch of tabs?
See picture:
![github issue jupyterlab collapse all areas in workspace into single area with tabs](https://user-images.githubusercontent.com/10303623/28340021-4a95f17a-6bdc-11e7-8964-5d43508ca73e.png)
Convert the state on the right to the state on the left with a single command.

**Comment by ellisonbg** [comment]
We now have single document mode for this usage case.
