### ISSUE TITLE
Bokeh.JS does not load in Jupyter lab while working fine in Jupyter notebook

### ISSUE THREAD

**Issue by tobsecret** [jupyterlab/jupyterlab#2710]
I have encountered a problem where Bokeh JS does not load in Jupyter lab when using output_notebook()
One can still execute cells with Bokeh code just fine, just that nothing will be displayed.
When running the same notebook with a Jupyter notebook server, Bokeh.js loads just fine.

I have attached my environment.txt:
[environment.txt](https://github.com/jupyterlab/jupyterlab/files/1159525/environment.txt)

And the Console output:
[console_output](https://github.com/jupyterlab/jupyterlab/files/1159544/Jupyterlab_console_output_BokehJS_not_working.txt)

**Comment by blink1073** [comment]
Hi @tobsecret, does anything print to the JavaScript console in the browser when you execute the cell?

**Comment by tobsecret** [comment]
Loading BokehJS ...

**Comment by tobsecret** [comment]
The code of that cell is below:
```python3
output_notebook()
temp_df = pd.DataFrame(df['qName'].value_counts()).join(df[['qSize', 'qName', 'sample']].set_index('qName')).sort_values(by='qName', ascending=False)
fig = figure()
colormapper = CategoricalColorMapper(factors=temp_df['sample'].unique().tolist(), palette=Category10_6)
for name, group in temp_df.groupby(by='sample'):
    fig.scatter(source=ColumnDataSource(group), 
                x='qName', y='qSize', 
                color={'field':'sample', 
                       'transform':colormapper}, 
                legend=name)
fig.legend.click_policy = 'hide'
show(fig)```

**Comment by sccolbert** [comment]
Does anything show up in the cell output area at all? Can you take a screenshot of the DOM inspector with the cell output area fully expanded?

**Comment by tobsecret** [comment]
This is a subpart of the DOM element with the Loading BokehJS... text
```html
<div class="p-Widget p-Panel jp-OutputArea-child"><div class="p-Widget jp-OutputPrompt jp-OutputArea-prompt"></div><div class="p-Widget jp-RenderedHTMLCommon jp-RenderedHTML jp-mod-trusted jp-OutputArea-output" data-mime-type="text/html">
    <div class="bk-root">
        <a href="http://bokeh.pydata.org" target="_blank" class="bk-logo bk-logo-small bk-logo-notebook"></a>
        <span id="c2dc339a-4847-40aa-ace4-83f5b5f0ccdc">Loading BokehJS ...</span>
    </div></div></div>
```
Below is the full output html (too big to just comment here)
[full_output_cell_DOM.txt](https://github.com/jupyterlab/jupyterlab/files/1160069/Jupyterlab_console_output_BokehJS_not_working_DOM.txt)

**Comment by sccolbert** [comment]
Ah okay. Bokeh is inlining a `<script>` tag in its HTML output. We disallow arbitrary script execution in outputs in JLab because it's a huge security risk and the JLab extension system makes it easier to build Javascript viewers for things in a safer fashion.

That said, this should have been logging a warning to the console to state that we are not executing the script. Which version of JLab are you running? Maybe that warning code hasnt made it to a released jlab yet...

**Comment by tobsecret** [comment]
I conda -c conda-forge installed it.
jupyterlab=0.25.2=py35_0

**Comment by sccolbert** [comment]
Here's the PR that added the warning. It was only merged 2 days ago, so it wouldn't be in a release yet:
https://github.com/jupyterlab/jupyterlab/pull/2690

**Comment by tobsecret** [comment]
Thanks!

**Comment by dclong** [comment]
@sccolbert 

Is there anyway for users to allow JS script execution for a single notebook? I switched back to Jupyter Notebook because I cannot use Bokeh in JupyterLab. I'm really excited to see new features coming out in JupyterLab but Bokeh is the blocker on the road.

**Comment by jasongrout** [comment]
Often the script that works in the classic notebook wouldn't work anyway in jupyterlab. I think the right solution here is for bokeh to release a JLab extension you can install to enable it.

**Comment by hedata** [comment]
dont like it.. breaks soo much visual code

**Comment by jasongrout** [comment]
The Bokeh team just opened an issue for supporting JupyterLab: https://github.com/bokeh/bokeh/issues/6700

**Comment by jasongrout** [comment]
Closing, since discussion should be moved to the bokeh repo: bokeh/bokeh#6700
