### ISSUE TITLE
jupyter lab build stuck to build new package if failed to build previous package

### ISSUE THREAD

**Issue by hainm** [jupyterlab/jupyterlab#2711]
Hi,

saying I failed to build `nglview` for lab. I go to `bqplot` to try to build it for comparison.
#2707 

However, I got error related to `nglview` build.
```bash
ERROR in ./~/nglview-js-widgets/src/widget_ngl.js
Module not found: Error: Can't resolve 'ngl' in
```

Sounds like this is a bug in lab build.

**Comment by hainm** [comment]
```bash
bqplot (master) $ jupyter lab build jslab
```

**Comment by blink1073** [comment]
All of the extensions are built together into the bundle, so if one of them is causing an error it has to be uninstalled.

**Comment by hainm** [comment]
Uhm. But as a user perspective, failed build mean the install never happen, why they need to 'uninstall' :D

**Comment by blink1073** [comment]
This is a tough one.  By default, `jupyter labextension install` also runs `jupyter lab build` unless the `--no-build` flag is set, but installing is distinct from building.  Installing puts a tarball in `<app_dir>/extensions`.  I think the best we can do is take the stance that if we are building while installing, and the build fails, we remove the newly installed extensions.
