### ISSUE TITLE
Is it really mandatory required npm to install lab extension?

### ISSUE THREAD

**Issue by hainm** [jupyterlab/jupyterlab#2712]
Original from this thread: https://github.com/jupyterlab/jupyterlab/pull/2038#issuecomment-299618742

Saying I would like to distribute `nglview` lab extension via conda.
Can a user just need to 
```bash
conda install nglview -c bioconda
```

Requiring handle `npm`, `yarn`, ... is too much for a regular user who does not really care much 
about programing. My impression is that we only need to build a tarfile, copy to correct lab location, update some configs (?) and thing just works.

**Comment by jasongrout** [comment]
Yes, it really is mandatory. When you install an extension, we have to rebuild all of jupyterlab's javascript, which involves installing with npm, deduping, and webpacking.

We have some ideas about how to make distributing npm easier, but it's not a worry with conda - conda packages npm, so npm is just a conda install away already.

**Comment by blink1073** [comment]
cf https://github.com/jupyterlab/jupyterlab/issues/2065 and https://github.com/jupyterlab/jupyterlab/pull/2162

**Comment by jasongrout** [comment]
Closing as answered. Thanks for asking so we could document this.
