### ISSUE TITLE
Problem  using JupLab in AWS without internet connection

### ISSUE THREAD

**Issue by lucianoviola** [jupyterlab/jupyterlab#2717]
I'm trying to use jupyter lab in an AWS instance without internet connection (squid only allows connections through pip or apt); The layout looks very weird, lots of things seem to be missing. I checked the network and the problem seems to be with google fonts api. Since it requires outside connection it fails. 

![juplab_example](https://user-images.githubusercontent.com/17896221/28470219-729f6f36-6e0f-11e7-92f1-037f8d20a133.png)
 
Could it be other things as well?

**Comment by blink1073** [comment]
There's definitely some core CSS that isn't loading aside from the fonts, I'm not sure why that would be.

**Comment by mborysow** [comment]
I work in an airgapped environment, so this always a concern and I'm always sad when some people make extensions that make use of external resources.  I get the following error in 0.27:

GET https://fonts.googleapis.com/css?family=Roboto+Mono net::ERR_NAME_NOT_RESOLVED

Seems like this one is just referenced in the theme's css:
ib/python3.5/site-packages/jupyterlab/themes/jupyterlab-theme-light-extension/variables.css:@import url('https://fonts.googleapis.com/css?             family=Roboto+Mono');

**Comment by lucianoviola** [comment]
Any advances?

**Comment by blink1073** [comment]
We optionally load that external CSS in JupyterLab 0.30, mind trying again?  cf https://github.com/jupyterlab/jupyterlab/pull/3298

**Comment by saulshanabrook** [comment]
When I load JupyterLab now it doesn't seem to be making any external requests like this. Please comment if you are still seeing that as an issue and we can reopen this.
