### ISSUE TITLE
Accessing Lab through JupyterHub causing 404 Errors when loading schemas

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#2721]
I was trying to access JupyterLab through a JupyterHub instance, and the server-side schemas were failing to load onto the client side. The dev console gave the following errors: 
```
GET http://localhost:8000/user/ian/lab/api/settings/jupyter.extensions.shortcuts?1500669668919 404 (Not Found)
Loading shortcut settings failed. Error accessing jupyter.extensions.shortcuts HTTP 404 Not Found
GET http://localhost:8000/user/ian/lab/api/settings/jupyter.services.editor-tracker?1500669668971 404 (Not Found)
Error accessing jupyter.services.editor-tracker HTTP 404 Not Found
GET http://localhost:8000/user/ian/lab/api/settings/jupyter.services.codemirror-commands?1500669669048 404 (Not Found)
Error accessing jupyter.services.codemirror-commands HTTP 404 Not Found
```
I am not sure if this is a problem with my setup, but it is a fairly serious problem, since without the schemas none of the keyboard shortcuts work.

**Comment by ian-r-rose** [comment]
Possibly related to #2716

**Comment by ian-r-rose** [comment]
This is still broken for me on 0.26.2. So far as I can tell, the `SettingsHandler` in the serverextension is not being called at all in a hub setting. It works just fine with a local server.

**Comment by blink1073** [comment]
Sounds like the labhubapp needs updating, will do tomorrow.

**Comment by ian-r-rose** [comment]
No rush, have your weekend, etc!

**Comment by ian-r-rose** [comment]
Works great, thanks!
