### ISSUE TITLE
When leave jupyterLab, it always pops an alert to let me make sure that I have saved file, how can I get rid of this

### ISSUE THREAD

**Issue by rydeng** [jupyterlab/jupyterlab#2723]
Every time I leave jupyterLab，it pops this：

> Are you sure you want to exit JupyterLab?
> Any unsaved changes will be lost.
> 
> Are you sure you want to leave this page?

How can I get rid of it？ Where is the bound event？
Thanks

**Comment by blink1073** [comment]
@afshin and I talked about this, and we think it makes sense to have an API on the application object to handle dirty state for the application, namely a `setDirty(): IDisposable` method and an `isDirty` property that could be used to determine whether to show the alert on page unload.  The application could internally have a counter that is incremented on `setDirty` and decremented when the returned disposable is disposed, and `isDirty` would be `true` iff the counter is 0.
