### ISSUE TITLE
Put "Create Console for Notebook" on the notebook context menu

### ISSUE THREAD

**Issue by joonro** [jupyterlab/jupyterlab#2726]
Hi,

Thanks again for the great `Create Console for Notebook` feature.

Currently the way to create a console for notebook is from the cell context menu. However, all other items on the menu are specific cell related. Since the console belongs to the whole notebook, not a single cell, I think it makes more sense to have the menu item on the notebook context menu (currently it only has the `Rename` item).

**Comment by ellisonbg** [comment]
It is on the entire notebook already, do you mean the tab? Honestly, not sure we want to have separate context menu for the tabs. Maybe move "Rename" to the main notebook div?

**Comment by joonro** [comment]
To me it makes sense to have separate context menu items that applies to the whole notebook (instead of certain cells) on the tab. I find it more intuitive but I can see others might see it confusing.

**Comment by ellisonbg** [comment]
All of the context menus are dynamically assembled based on CSS selectors. Thus the context menu you are seeing on the "cells" does have items that apply to the whole notebook as well - those are separated by a horizontal line.

My current feeling is that the context menus make sense, but I don't have a strong sense of why or if users will find it this way (possible some observational user tests). I would like to close this issue for now and see what happens with the upcoming releases. I don't think this is the final word on the matter though and think your question is a very good one. What do others think?

**Comment by blink1073** [comment]
Sounds fair to me.

**Comment by joonro** [comment]
Agreed! Thanks you.
