### ISSUE TITLE
Is one notebook APIHandler‘s http request going to block other APIHandler's requests?

### ISSUE THREAD

**Issue by rydeng** [jupyterlab/jupyterlab#2728]
I write a new handler to request another systems for some infos, but I found that this request blocked other APIHandler's requests untill this request is done.

**Comment by blink1073** [comment]
Hi @rydeng, the `ioloop` used by the server is single-threaded.  If your handler needs to do some work, it should be wrapped in a future and do work in a thread.  Here is an example of using a future in a handler: https://github.com/jupyter/notebook/blob/05979d9a4bc023f1693767343905b689905badc9/notebook/services/kernels/handlers.py.

**Comment by rydeng** [comment]
Hi @blink1073  thanks a lot.
