### ISSUE TITLE
How to access sqllite tables with sqllite

### ISSUE THREAD

**Issue by kc1** [jupyterlab/jupyterlab#2739]
Hello, my question is here:

https://stackoverflow.com/questions/45119619/access-sqllite-with-jupyterlab

Thank you

**Comment by ddavidebor** [comment]
You can do anything with any of the languages supported by Jupyter

**Comment by blink1073** [comment]
Hi @kc1, we don't have direct support for interacting with sqllite files in JupyterLab, as far as I know the only way to interact with them is through another language, or using a `%sql` magic for the ipython kernel: https://github.com/catherinedevlin/ipython-sql.

**Comment by rgbkrk** [comment]
A jupyterlab plugin that uses https://github.com/kripken/sql.js could be pretty neat. (No I'm not signing up to do this).
