### ISSUE TITLE
Markdown bullet point highlighting

### ISSUE THREAD

**Issue by kohlkopf** [jupyterlab/jupyterlab#2741]
In jupyter lab the highlighting by indentation level seems to be malfunctioning. There is no coloring for the first two levels. The third level is highlighted green.
<img width="595" alt="screen shot 2017-07-25 at 10 24 31 am" src="https://user-images.githubusercontent.com/28633777/28584971-83a8caae-7123-11e7-9684-22fad65d5428.png">

**Comment by blink1073** [comment]
Confirmed this is a regression from the classic notebook, thanks for the report!
