### ISSUE TITLE
Recognize .tsv files as tables

### ISSUE THREAD

**Issue by apcamargo** [jupyterlab/jupyterlab#2746]
Currently, only .csv files can be viewed as tables in JupyterLab. However, it's verry common to use the .tsv extension for files that use a `\t` separator.

**Comment by dhimmel** [comment]
This would be an excellent addition. Currently, GitHub recognizes `.tsv` extensions and renders TSVs in tabular view.

As someone who prefers TSV to CSV for many data science applications, I'm always worried that lack of TSV support by major projects can hold back the growth of TSV.

I assume most of the same machinery used to render CSVs can be used to render TSVs.

**Comment by jasongrout** [comment]
Exactly the same machinery can be used. This is probably an advanced good first issue.

**Comment by jasongrout** [comment]
See also #4226

**Comment by jasongrout** [comment]
Fixed by #4684
