### ISSUE TITLE
Feature Request: Support Terminals on Windows

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#2753]
I've opened this is a feature request issue to consolidate and keep track of any discussions around what would be involved in supporting terminals on Windows. Some previous discussions are available in the below issues:
 * #2033 - Terminal option not available 
 * #172 - Terminal unavailable in Jupyter Notebook
 * #473 - Display error message when opening terminal on Windows

**Comment by dhirschfeld** [comment]
Since JupyterLab depends on [`terminado`](http://terminado.readthedocs.io/en/latest/) for it's terminal support I've opened a feature request issue there - takluyver/terminado#35

**Comment by stonebig** [comment]
Spyder-Terminal uses https://github.com/rprichard/winpty 

I've no idea if it's technically an option, but if we revert the table and say spyder is the jupyterlab, then we have editor, notebook, and terminal.

**Comment by dhirschfeld** [comment]
Rather than supporting Windows in `terminado` directly it has been decided that the easiest way forward is to port the spyder terminal. Work on this will be done in the [`win-tornado-terminals`](https://github.com/jupyter/win-tornado-terminals) project under the jupyter umbrella.

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyter/notebook/pull/3087, will be available in Notebook 5.3
