### ISSUE TITLE
Horizontal scrollbars in codemirror are overlapping text

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2754]
This is a result of the `-webkit-scrollbar` styling in https://github.com/jupyterlab/jupyterlab/pull/2737.

![image](https://user-images.githubusercontent.com/2096628/28669986-447702ea-729c-11e7-8150-6ffbb3824985.png)

**Comment by blink1073** [comment]
cc @cameronoelsen

**Comment by ellisonbg** [comment]
We should use the d fault scroll bar styling me thinks

**Comment by blink1073** [comment]
Fixed by #2830.
