### ISSUE TITLE
Support image/gif mimetype

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#2760]
I submitted PRs to ipython (https://github.com/ipython/ipython/pull/10716), ipykernel (https://github.com/ipython/ipykernel/pull/254), and notebook (https://github.com/jupyter/notebook/pull/2702) to support `image/gif` mimetype, specifically use with ipython: 

```py
IPython.display.Image("filename.gif", format="gif")
```

**Comment by gnestor** [comment]
Looks like it's already supported!

https://github.com/jupyterlab/jupyterlab/blob/master/packages/rendermime/src/factories.ts#L30

**Comment by ian-r-rose** [comment]
![](https://media.giphy.com/media/ZXD5JEmd2VFxC/source.gif)

**Comment by blink1073** [comment]
Nicely done Ian.
