### ISSUE TITLE
No UI to view notebook in multiple panes

### ISSUE THREAD

**Issue by stsievert** [jupyterlab/jupyterlab#2769]
What I'd like:

<img width="1276" alt="screen shot 2017-08-01 at 4 00 14 pm" src="https://user-images.githubusercontent.com/1320475/28846861-a810f8e4-76d2-11e7-93da-68a9de56ce64.png">

I ran into this when trying to edit/view different parts of the notebook.

What I've tried:

* dragging a cell; no area highlights, and release does nothing.
* dragging from notebook title from {notebook list, tab bar} into new area. Area highlights, but when mouse released nothing happens.
* control-clicking on entry in notebook list and clicking "Open". Highlights the open pane.

This is the similar issue to dragging the output to different parts of the screen. @jasongrout said at scipy he wasn't sure about the UI for dragging cells to view the output.

**Comment by sccolbert** [comment]
A couple points:

- Dragging a cell into a separate panel is currently disabled while we work through the UX to distinguish between dragging a cell to a new panel, and drag/drop cells *within* a notebook.

- Dragging a tab doesn't duplicate the tab content, it *moves* the tab to a new location. If there is only  a single tab open, there is nowhere to "move" it, so the drop action is a no-op.

- I think we need something like "new view into file" which allows you to open a duplicate view of a file. This sounds like it would solve your problem.

**Comment by stsievert** [comment]
Thanks @sccolbert. Another view into the file would solve my problem.

I would like to see separate panels different views of the same notebook, not separate panels for cells. What if I want to see some information that's in the cell below a cell in a panel? Or what if I drag a markdown cell and want to split it into two cells (e.g., to always view some rendered latex in one cell)?

**Comment by sccolbert** [comment]
Yep, new-view-into-file is what you want.
