### ISSUE TITLE
Labextension link . raise error when installing  jupyterlab-hub 

### ISSUE THREAD

**Issue by wispyoureyes** [jupyterlab/jupyterlab#2770]
I‘m trying to install jupyterlab-hub on jupyterlab v0.26.0 :

`jupyter labextension link .`

and the following is the error:

```
npm pack /Users/adminastor/jupyterworkspace/extensions/jupyterlab-hub
node node-version-check.js
Uninstalling jupyterlab-hub from /Users/adminastor/anaconda/share/jupyter/lab/extensions

Traceback (most recent call last):
  File "/Users/adminastor/anaconda/bin/jupyter-labextension", line 11, in <module>
    load_entry_point('jupyterlab', 'console_scripts', 'jupyter-labextension')()
  File "/Users/adminastor/anaconda/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/adminastor/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "/Users/adminastor/anaconda/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/labextensions.py", line 89, in start
    raise e
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/labextensions.py", line 85, in start
    build(self.app_dir, logger=self.log)
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/commands.py", line 488, in build
    _ensure_package(app_dir, name=name, version=version, logger=logger)
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/commands.py", line 744, in _ensure_package
    data = _get_package_template(app_dir, logger)
  File "/Users/adminastor/jupyterworkspace/jupyterlab-0.26.0/jupyterlab/commands.py", line 801, in _get_package_template
    data['jupyterlab']['mimeExtensions'].remove(item)

ValueError: list.remove(x): x not in list
```

And when I try to install another extension jupyterlab-google-drive , the same error raised.

**Comment by blink1073** [comment]
Hi @wispyoureyes, it looks like there is an error in uninstalled core extensions.  What does `jupyter labextension list` give?  Also, in the application directory given by `jupyter lab paths`, what is the content of `settings/build_config.json` in that folder?

**Comment by wispyoureyes** [comment]
Thanks，I found an uninstalled_core_extensions  in `settings/build_config.json` named dashboard-extension，it used to be installed on my jupyterlab, but later I reinstalled my jupyterlab. So I delete this line of build_config，and it works.

```
{
    "uninstalled_core_extensions": {
        "dashboard-extension": "/Users/adminastor/jupyterworkspace/jupyterlab/extensions/dashboard-extension"
    }
}
```

**Comment by wispyoureyes** [comment]
Sorry, I got another problem when link labextension.
This time I succeed running `jupyter labextension link .` in the jupyterlab-hub repo, and the labextension list also includes  jupyterlab-hub. While the jupyterlab-hub was not build into `jupyterlab/build/main.bundle.js`.
Here is `lab/setting/build_config.json`
```
{
    "linked_packages": {
        "jupyterlab-hub": "/Users/adminastor/jupyterworkspace/jupyterlab/extensions/jupyterlab-hub"
    }
}
```
And the extension tar file is also copied to `lab/extensions`directory.
And I've tried link other extensions in clear evn, the same .
I've no idea.

**Comment by blink1073** [comment]
Did `jupyter lab build` succeed without errors?

**Comment by wispyoureyes** [comment]
Yes，every command was ran without any error，and I can also run `jupyter lab --dev-mode `successful.Everything seems succeed，but i just can not find any code of the extension build into my dev jupyterlab's `build/main.bundle.js`.
I just found some regist code in my `app_dir/lab/staging/build/main.bundle.js`:
```
try {
        if (disabled.indexOf('jupyterlab-hub') === -1) {
            lab.registerPluginModule(__webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"jupyterlab-hub\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())));
        }
    } catch (e) {
        console.error(e);
}
```
and in stagin/build/package.json:
```
"dependencies": {
jupyterlab-hub": "/anaconda/share/jupyter/lab/extensions/jupyterlab-hub-0.4.0.tgz"
},
"jupyterlab": {
    "extensions": [
            "jupyterlab-hub"
        ]
}
```
and when i run `jupyter lab` directly, there still nothing related to jupyterlab-hub in the main.bundle.js of the source code in browser.

**Comment by blink1073** [comment]
Can you please try a `jupyter lab clean && jupyter lab build`?

**Comment by wispyoureyes** [comment]
`jupyter lab clean && jupyter lab build` with no error
```
anderweltdeMacBook-Pro:jupyterlab-0.26.0 administrator$ jupyter lab clean 
anderweltdeMacBook-Pro:jupyterlab-0.26.0 administrator$ jupyter lab build
> node node-version-check.js
> npm pack /Users/administrator/jupyterworkspace/jupyterlab/extensions/jupyterlab-hub
> npm install
> npm run build
```

**Comment by blink1073** [comment]
And still no hub plugin when running `jupyter lab`?

**Comment by wispyoureyes** [comment]
Yes,still no hub plugin.

**Comment by wispyoureyes** [comment]
I firstly clone hub's repo from github, and then 
```
cd jupyterlab-hub
npm install
jupyter labextension link .
```

**Comment by blink1073** [comment]
I'm trying the same locally now

**Comment by blink1073** [comment]
Hmm, that works for me, here is the snippet in `main.bundle.js` in the browser:

![image](https://user-images.githubusercontent.com/2096628/28986388-651377ea-792c-11e7-8fa8-fc04f1d6d6f7.png)

And the console notice that we aren't running jupyterhub:

![image](https://user-images.githubusercontent.com/2096628/28986417-841dce56-792c-11e7-9626-d745def532b7.png)

And when served using a local hub instance:

![image](https://user-images.githubusercontent.com/2096628/28986440-a003bb30-792c-11e7-8dd6-344cbe8997d9.png)

**Comment by blink1073** [comment]
Is the hub config there in `app_dir/static/package.json`?

**Comment by wispyoureyes** [comment]
Yes, there is, the same to staging/package.json.

**Comment by blink1073** [comment]
Does `app_dir/staging/node_modules/jupyterlab-hub/lib` exist?

**Comment by blink1073** [comment]
I suspect `app_dir/staging/node_modules/jupyterlab-hub/` is there but no `lib/`, which would mean you need to manually run `npm run build` in from the repo root.   Some versions of npm do not automatically run the `prepublish` script on `npm install`.

**Comment by wispyoureyes** [comment]
@blink1073 I'm sorry to bother you again.  The hub plugin worked after I reinstall my anaconda and jupyterlab. But it was still not installed in my development branch of JupyterLab.
Can I use `jupyter labextension link <path>` to add the hub plugin to my **development branch of JupyterLab** ?
Or it is the only way to add plugin to development branch of JupyterLab using `npm run addsibling <path-or-url>`?

**Comment by blink1073** [comment]
Unfortunately because of the interaction between symlinks and node module resolution, we are forced to use the `addsibling` script for development against JupyterLab master.  The `jupyter labextension` workflow only works for released JupyterLab assets.

**Comment by wispyoureyes** [comment]
I got it. Thanks a ton for your patience！

**Comment by wispyoureyes** [comment]
I got it. Thanks a ton for your patience！
