### ISSUE TITLE
JupyterLab ignoring the IPython {profile_name}/startup directory?

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#2771]
As it says in the title, JupyterLab seems to be ignoring this folder.

Is this a bug, missing feature or a design decision? If the latter, what is the recommended way for a user to customise their starting IPython (notebook/console) namespace?

**Comment by blink1073** [comment]
As in the namespace of `ipykernel` itself, or to do mean things like `custom.js/css`?

**Comment by dhirschfeld** [comment]
Namespace of ipykernel. In Spyder,  qtconsole and I'm pretty sure the notebook it runs any *.py file in the startup folder of the profile it's running under do you can pre-populate the namespace and have different startup environments for different profiles.

**Comment by blink1073** [comment]
I just tried the following and the config was passed to the kernel.  Are you trying to use the special-named `ipython_notebook_config.py`?

```bash
$ cat ~/.ipython/profile_default/startup/ipython_config.py
c = get_config()
c.InteractiveShellApp.exec_lines = [
    'import numpy',
    'import scipy'
]
```

<image src="https://user-images.githubusercontent.com/2096628/28893404-f21cef6e-7796-11e7-9e24-e4cb16bb76a1.png" width=300>

**Comment by blink1073** [comment]
I also added a `test.py` file with `a = 10`, and added

```
c.InteractiveShellApp.exec_files = [
    'test.py'
]
```

And the variable was immediately available.

**Comment by dhirschfeld** [comment]
IPython will load *any* `.py` file in the `{profile_name}/startup` folder *without* it having to be specified in `c.InteractiveShellApp.exec_files` in the `ipython_notebook_config.py` file.

...however, testing locally, it seems both the notebook and jupyterlab ***do*** do that:

![image](https://user-images.githubusercontent.com/881019/28898312-9c6428f2-7828-11e7-95b5-ecca3e36bfea.png)

Sorry for the noise - it's obviously something wrong with my container deployment and not with jupyterlab :|

**Comment by dhirschfeld** [comment]
What I'm wanting to do is give users the ability to customise their own jupyterlab container environment.

Your comment above made me realise I can just add a standard filename to `exec_files ` and deploy the custom `ipython_notebook_config.py` to the container. The user can then just create/modify that file to customise their environment...

**Comment by blink1073** [comment]
Glad you got sorted!
