### ISSUE TITLE
Editor menu is disabled

### ISSUE THREAD

**Issue by megamindbrian** [jupyterlab/jupyterlab#2776]
Not sure what is causing this but my editor menu is completely disabled:

![image](https://user-images.githubusercontent.com/25057134/28933597-7b5195fa-7832-11e7-89b7-f567c4dfdc39.png)

**Comment by blink1073** [comment]
This is the case even when you have one or more editors open?

**Comment by megamindbrian** [comment]
Yes in the picture you can see there is a least one tab open.



On Aug 3, 2017 12:07 PM, "Steven Silvester" <notifications@github.com>
wrote:

This is the case even when you have one or more editors open?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jupyterlab/jupyterlab/issues/2776#issuecomment-320061914>,
or mute the thread

**Comment by blink1073** [comment]
From the picture it looks like both documents are notebooks, which are distinct from the file editor plugin.

**Comment by megamindbrian** [comment]
Ohhh, that makes sense.  So this is the most current resource for changing
themes?

https://github.com/jupyterlab/jupyterlab/issues/1084

**Comment by blink1073** [comment]
Changing themes today can be accomplished as `jupyter labextension uninstall @jupyterlab/theme-light-extension` and `jupyter labextension install @jupyterlab/theme-dark-extension`.  We are currently working on making application theme switching dynamic: https://github.com/jupyterlab/jupyterlab/pull/2759.

**Comment by blink1073** [comment]
Closing this one as answered, feel free to reopen if you disagree.

**Comment by megamindbrian** [comment]
That answers it, haven't seen that
https://github.com/jupyterlab/jupyterlab/pull/2759 link until now.

**Comment by megamindbrian** [comment]
I tried installing and it looks like only a few tab and features are styled. Is this because you were working on layout I saw in another thread and haven't updated dark? This is something I would be good at being a UX engineer. Want me to PR? I was thinking to get a little close to the webstorm dark/ Solaris type theme if you aren't set on the off-black colors?

**Comment by blink1073** [comment]
Hi @megamindbrian, the dark theme was overhauled in https://github.com/jupyterlab/jupyterlab/pull/2737, but has not yet been released.  Note that https://github.com/jupyterlab/jupyterlab/pull/2759 updated the way we handle themes in the application.  If you'd like to discuss the colors used in the dark theme, please feel free to open a new issue.

**Comment by megamindbrian** [comment]
Ok, I'll try grabbing from repo instead of NPM.
