### ISSUE TITLE
Improve the right-click menu of the editor

### ISSUE THREAD

**Issue by apcamargo** [jupyterlab/jupyterlab#2778]
Currently, when you right-click inside the editor, the only option in the menu is "Create Console for Editor". People expect some other basic functions to be available in this menu as well, such as copy, paste, cut, select all, undo/redo etc.

**Comment by karlaspuldaro** [comment]
Hello :) I would like to start working on this issue if no one's assigned to it yet

**Comment by lresende** [comment]
I don't believe we have anyone working on it @karlaspuldaro, so I am assigning it to you. Let us know if you have any questions.

**Comment by jasongrout** [comment]
Note that shift-right-clicking will give you the browser menu, which has copy/paste, etc.

**Comment by karlaspuldaro** [comment]
@jasongrout thx. So are there any other commands we want to add other than 
- select all
- cut
- copy
- paste
- save?
- undo?
- redo?

**Comment by jasongrout** [comment]
Do you want to do a quick survey of other popular code editors and see what is in their right-click menus? VS Code, sublime, spyder, atom, etc.?

**Comment by karlaspuldaro** [comment]
Looks like they all have **cut/copy/paste**
Some also have **select all/undo/redo** which are helpful.
We can get started with those basic functions. Suggestions are welcome :)

**Comment by karlaspuldaro** [comment]
@jasongrout I believe this issue can be closed since the merge of #8425 is complete

**Comment by JasonWeill** [comment]
Closing as fixed by #8425
