### ISSUE TITLE
Undefined token will be appended to wsUrl using DefaultKernel

### ISSUE THREAD

**Issue by alexeckert** [jupyterlab/jupyterlab#2782]
The `token` can be `undefined` and will be appended wrongly to the `wsUrl`. This can lead to a failing web socket connection (this was the result in my case).

https://github.com/jupyterlab/jupyterlab/blob/aff36a139524cf91bfdd408e8f689fb104659fe3/packages/services/src/kernel/default.ts#L646

The token needs and additional check, e.g.
`if (typeof token !== 'undefined' && token !== '')`

Affects pkg:services

**Comment by blink1073** [comment]
Hi @alexeckert, I'm confused about how the token ended up as `undefined` instead of an empty string, can you share some code that led to this behavior?  Or was this from running `JupyterLab` as an application?

**Comment by alexeckert** [comment]
We're using only the services package (https://www.npmjs.com/package/@jupyterlab/services).

The default.js looks like this:
```var DefaultKernel = (function () {
    /**
     * Construct a kernel object.
     */
    function DefaultKernel(options, id) {
        this._id = '';
        this._token = '';
        this._name = '';
        this._baseUrl = '';
        this._wsUrl = '';
        this._status = 'unknown';
        this._clientId = '';
        this._ws = null;
        this._username = '';
        this._ajaxSettings = '{}';
        this._reconnectLimit = 7;
        this._reconnectAttempt = 0;
        this._isReady = false;
        this._futures = null;
        this._commPromises = null;
        this._comms = null;
        this._targetRegistry = Object.create(null);
        this._info = null;
        this._pendingMessages = [];
        this._connectionPromise = null;
        this._specPromise = null;
        this._statusChanged = new signaling_1.Signal(this);
        this._iopubMessage = new signaling_1.Signal(this);
        this._unhandledMessage = new signaling_1.Signal(this);
        this._name = options.name;
        this._id = id;
        this._baseUrl = options.baseUrl || utils.getBaseUrl();
        this._wsUrl = options.wsUrl || utils.getWsUrl(this._baseUrl);
        this._ajaxSettings = JSON.stringify(utils.ajaxSettingsWithToken(options.ajaxSettings, options.token));
        this._token = options.token || utils.getConfigOption('token');
        this._clientId = options.clientId || utils.uuid();
        this._username = options.username || '';
        this._futures = new Map();
        this._commPromises = new Map();
        this._comms = new Map();
        this._createSocket();
        this.terminated = new signaling_1.Signal(this);
        Private.runningKernels.push(this);
    }
``` 

And `utils.getConfigOption('token')` returns undefined if token is not somehow contained in the config.

**Comment by blink1073** [comment]
That is what confuses me, it should always return a string: 

https://github.com/jupyterlab/jupyterlab/blob/fea2cf52ea980712af61e79262c35017e59bb712/packages/coreutils/src/pageconfig.ts#L47
https://github.com/jupyterlab/jupyterlab/blob/fea2cf52ea980712af61e79262c35017e59bb712/packages/coreutils/src/pageconfig.ts#L83

What version of `coretutils` are you using?  `npm ls @jupyterlab/coreutils`.

**Comment by alexeckert** [comment]
Sorry an old `services` version was used (0.40.3) where `@jupyterlab/coreutils` wasn't a dependency, yet. The utils.getConfigOptions of `@phosphor/coreutils` returned the undefined value.

**Comment by blink1073** [comment]
I published a 0.40.4 with the update.

**Comment by blink1073** [comment]
@alexeckert, can you confirm whether your code works with the `0.40.4` release?

**Comment by alexeckert** [comment]
@blink1073 Tested it today with v `0.40.4` and the code works. Many thanks!

**Comment by blink1073** [comment]
Cheers!
