### ISSUE TITLE
FileBrowser icons to show git status

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#2789]
It would be nice if the FileBrowser were "git aware" and could display the git status with the icons.

Coming from Windows I'm thinking of something similar to the TortoiseGit overlay icons for Windows Explorer:
![](https://tortoisegit.org/docs/tortoisegit/images/Overlays.png)

**Comment by ellisonbg** [comment]
We have a separate Git plugin in the works that may address some of this:

https://github.com/jupyterlab/jupyterlab-git

**Comment by dhirschfeld** [comment]
I'll close this in favour of jupyterlab/jupyterlab-git#124.

If there's anything which needs changing in jupyterlab to support this, then this issue can always be reopened...
