### ISSUE TITLE
Usability of (double) mouse clicks on command palette

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#279]
That's definitively a user bug (PEBKAC), so I'm to blame. But I guess I won't be the only one. 

I **think** that this might be because for **selected** item, the appearance is not different on `:hover`, and that having an extra-highlight or underline on hover will partly help my brain adjust and click only once. 
Still I might (often) keep trigger the action twice, which might be undesirable.

Do you think it could be a good idea to also bind double-click as well, to prevent this kind of things ?

**Comment by ellisonbg** [comment]
To clarify, right now command palette actions are triggered on single clicks. The way it works currently, a double click then triggers the actions twice which is not usually what the user wanted. We should look at UI/UX changes to better indicate that it is single, not double click to trigger the action.

**Comment by tgeorgeux** [comment]
@Carreau Do you think if we incorporated the suggested solution to #1095 it would prevent this type of mistake? For reference I suggested that we give visual indication when a command palette item is pressed by changing from UI color 2 to UI color 3 on active. Same like we do for buttons.

**Comment by Carreau** [comment]
It will likely help, but is probably more complicated than just having a style change with CSS. (or maybe you can do it with CSS ? )

Also we should consider how this will affect users of keyboard.

**Comment by tgeorgeux** [comment]
Keyboard focus is UI color 3 as well,  if we use ui color 3 on activate, it would already be present for focus, might need to 'blink' the background on activate to give the same active signal to keyboard users.

**Comment by tgeorgeux** [comment]
I think we should merge and iterate on the above idea. @saulshanabrook do you have time to help me execute this?

**Comment by ellisonbg** [comment]
From @blink1073 - maybe we need to debounce to the double click does have the negative side effect.
