### ISSUE TITLE
Pass custom config options to labextensions frontend

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#2790]
Hi,

I used to do this in the earlier labextension using the steps mentioned in the tutorial:

```
# Jupyter Lab Extension config data.
def _jupyter_labextension_config():
  """Get a dictionary of configuration data to provide to the JupyterLab frontend.

  This is called at each launch of the `/lab` page, and makes data available 
  through the `getConfigOption` [function](http://jupyterlab.github.io/services/globals.html#getconfigoption).

  Example in ES6 JavaScript:
  import { utils } from '@jupyterlab/services';
  let myVar = utils.getConfigOption('my_fancy_module_variable');
  """
  return dict(my_fancy_module_variable=1)
```
However, this doesn't work in the latest version as there is no python package anymore. How can I now pass custom config options and use them in labextension frontend?

**Comment by blink1073** [comment]
We decided that front end and back end extensions should remain separate. An extension that wants to affect the backend must also provide a server extension. They can affect the front end using page_config, an example of which is [here](https://github.com/jupyterlab/jupyterlab/blob/fea2cf52ea980712af61e79262c35017e59bb712/jupyterlab/labhubapp.py#L13).

**Comment by blink1073** [comment]
Closing as answered, please feel free to reopen if you disagree.
