### ISSUE TITLE
Uncaught (in promise) Module nglview-js-widgets, semver range 0.5.4-dev.8 is not registered as a widget module

### ISSUE THREAD

**Issue by hainm** [jupyterlab/jupyterlab#2791]
Hi,

any idea how to fix this? (I search " is not registered as a widget module" but getting no clue). thanks.

```
lab: version: 0.26.4
ipywidgets: '7.0.0b7'
```

<img width="1280" alt="screen shot 2017-08-06 at 11 42 48 pm" src="https://user-images.githubusercontent.com/4451957/29011431-006a8fdc-7b01-11e7-9510-523172d423d4.png">

**Comment by blink1073** [comment]
Hi @hainm, I saw the same and fixed it by getting a new version of the lab extension as `jupyter labextension install @jupyter-widgets/jupyterlab-manager`.

**Comment by hainm** [comment]
thanks I will try and report later.

**Comment by hainm** [comment]
hi @blink1073 

unfortunately the issue is not resolved

```bash
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
> npm pack @jupyter-widgets/jupyterlab-manager
> node node-version-check.js
> npm install
> npm run build
```

```
$ jupyter labextension install jslab/
> npm pack /Users/haichit/programs/3d/nglview/jslab
> node node-version-check.js
> npm install
> npm run build
```

After two above steps, I am still getting similar error.

<img width="1278" alt="screen shot 2017-08-07 at 8 46 25 pm" src="https://user-images.githubusercontent.com/4451957/29051538-8804bfa2-7bb1-11e7-9af4-22f9c5f40eaa.png">

**Comment by blink1073** [comment]
@jasongrout, any advice for the above?

**Comment by hainm** [comment]
@blink1073 I think I know why now.

That's because nglview specify `"@jupyter-widgets/jupyterlab-manager": "^0.24.0"` in its
`jslab/package.json`. Change it to `"@jupyter-widgets/jupyterlab-manager": "^0.25.11"` would help (with jupyterlab `v0.26.5`).

**Comment by blink1073** [comment]
Okay, closing this in favor of #2831.
