### ISSUE TITLE
can not resize filebrowser

### ISSUE THREAD

**Issue by rydeng** [jupyterlab/jupyterlab#2807]
In the latest jupyterlab, I can not resize the left filebrowser

**Comment by sccolbert** [comment]
@rydeng Which version (exactly) of JLab? Can you make a gif showing the issue?

**Comment by rydeng** [comment]
@sccolbert  Hi the version is 0.26.4

**Comment by rydeng** [comment]
<div class="p-SplitPanel-handle p-mod-hidden" style="position: absolute; top: 0px; left: 1503px; width: 1px; height: 307px;"></div>

I don't know why the class is set to p-mod-hidden without a stop

**Comment by blink1073** [comment]
The filebrowser has a minimum width that allows it to show a reasonable amount of content when opened, it should be able to expand outward.

**Comment by rydeng** [comment]
Hi @blink1073 , but when I pull down the lastest jupyterlab from master, I get this problem that the filebrowser is not able to expand outward.

**Comment by rydeng** [comment]
Hi @blink1073  the jp-NotebookPanel can resize, but filebrowser can not. It is weird.

**Comment by sccolbert** [comment]
@rydeng Can you please post a gif of the behavior?

**Comment by sccolbert** [comment]
I use LiceCap for making gifs: https://www.cockos.com/licecap/

**Comment by rydeng** [comment]
`<div class="p-SplitPanel-handle p-mod-hidden" style="position: absolute; top: 0px; left: 1503px; width: 1px; height: 366px;"></div>`

I find that the class 'p-SplitPanel-handle p-mod-hidden' is changing without a stop.

**Comment by rydeng** [comment]
Hi @sccolbert  
![cannotresize](https://user-images.githubusercontent.com/9131195/29153255-15fb75da-7dbf-11e7-9fdc-7b2e06cb1dd6.gif)

**Comment by sccolbert** [comment]
Thanks! Do you have any content open in the main area?

What OS/Browser are you running?

**Comment by rydeng** [comment]
I run this on win10 and browser is chrome64(60.0.3112.90), and the change is like this.
![changing](https://user-images.githubusercontent.com/9131195/29153311-7e3da12c-7dbf-11e7-87f7-bc98e52beeef.gif)

**Comment by sccolbert** [comment]
That's very odd. The `p-mod-hidden` class should be setting `display: none` on that `p-SplitPanel-handle` node. Can you check the computed style and see if something is overriding the Phosphor css rule which sets `display: none` for the handle?

**Comment by sccolbert** [comment]
I also run Windows 10 on Chrome 60, and JLab master from last week works fine for me.

**Comment by rydeng** [comment]
Hi @sccolbert , thanks, I will check it.

**Comment by rydeng** [comment]
Hi @sccolbert, the css look normal.  I feel that something is refreshing the class without a stop, but I don't find it.
![changing](https://user-images.githubusercontent.com/9131195/29153594-eb8a99a0-7dc0-11e7-9269-0a906ab8a1f5.gif)

**Comment by sccolbert** [comment]
Is that flickering on the check boxes present in real life, even when you're not moving the mouse?

**Comment by sccolbert** [comment]
Also, are seeing any warnings or errors in the console?

**Comment by rydeng** [comment]
Hi @sccolbert . Right, even when I  am not moving.  And I am not seeing any warnings or errors.

**Comment by sccolbert** [comment]
Okay, yeah. That's weird. Since it's easily reproducible for you, would mind running one more diagnostic? While is doing the refreshing thing, can you record a JS profile, or a timeline profile, in the dev tools, and post the output here? That should show us what is causing the refresh.

**Comment by rydeng** [comment]
Hi @sccolbert , I found the code refresh class 'p-SplitPanel-handle'. It is in `packages/application/src/shell.ts`，as follows:
`  /**
   * Handle `fit` messages for the application shell.
   */
  protected onFitRequest(msg: Message) {
    this._dockPanel.fit();
  }`
when I annotate this block of code, It can expand now.

**Comment by sccolbert** [comment]
It's fine for that method to be called, but the fact that it's been called in an endless loop is a bug we need to find.
