### ISSUE TITLE
Text clipping of long tab titles.

### ISSUE THREAD

**Issue by Usama23** [jupyterlab/jupyterlab#2809]
Anaconda Enterprise Notebook 4.1.3

**Actual Result:**

   Under JupyterLab application long notebook/terminal name not properly appear on header.(only in Chrome).

![screenshot_93](https://user-images.githubusercontent.com/21064099/29122919-6e67849e-7d2d-11e7-8827-8da64ad59c55.png)

Expected Result:
Complete name should properly appear on tabs.

**Comment by blink1073** [comment]
Perhaps the active tab should show the full file name (or at least be wider)?

**Comment by sccolbert** [comment]
Or use ellipsis for eliding and a tooltip which shows the full title.

**Comment by zyxue** [comment]
Or show the open tabs to the bottom instead of left

**Comment by ian-r-rose** [comment]
The tab width has been increased, and if the name is still too long for that, then it can be seen by the tooltip when hovering over the tab. Closing as resolved, please let us know if this is not sufficient.
