### ISSUE TITLE
Data under "Slide Type" drop down is not visible in FireFox.

### ISSUE THREAD

**Issue by RidaZubair** [jupyterlab/jupyterlab#2810]
**Browser : FireFox
Anaconda Enterprise Notebook 4.1.3**

**Steps to Reproduce:**
- Login to AEN.
- Create project and then start that project.
- Under project go to Jupterlab.
- Create the Notebook.
- Go to Cell tool tab and check the drop down of "Slide Type"

**Actual Result:**
![11](https://user-images.githubusercontent.com/27444898/29123569-9d887a10-7d2f-11e7-9c3a-a2be7b6cfc01.png)

**Comment by blink1073** [comment]
It looks like Firefox does not render an option's `label` property: https://codepen.io/anon/pen/WEjyPW.

**Comment by sccolbert** [comment]
The option text should be the text content of the node. The `label` attribute is metadata:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option
