### ISSUE TITLE
should embed.css be a part of  light-theme-extension?

### ISSUE THREAD

**Issue by ivanov** [jupyterlab/jupyterlab#2813]
'@jupyterlab/theme-light-extension/style/embed.css' still appears to be referenced in the examples...

however, the npm published version of `light-theme-extension` (0.9.0) does not have this file.

```
2:20@theme-light-extension(bloomberg)$ pwd
/Users/pivanov5/tmp/2017-08-09/node_modules/@jupyterlab/theme-light-extension
12:20@theme-light-extension(bloomberg)$ tree
.
├── lib
│   ├── index.d.ts
│   └── index.js
└── package.json

1 directory, 3 files
```

@blink1073 - was this a packaging/publishing mistake? The lerna hoisted version of theme-light-extension has `style` directory, but the published version only has the three files listed above.

**Comment by blink1073** [comment]
The version in this repo has not yet been published to npm.

**Comment by ivanov** [comment]
oh man... I guess that's unfortunate that packages point to the last released version in between releases. I was trying to move forward on the example that was removed in #2795... I'll go further back and try to work off of the release tags instead.
