### ISSUE TITLE
please bring back app example

### ISSUE THREAD

**Issue by ivanov** [jupyterlab/jupyterlab#2816]
It was removed in #2795... and I think it worked in the commit that Steve pointed to in a comment on that PR, but it does not work with the last published version of the packages on npm.

I know there are server-side settings which weren't working with this example, but all of those should be optional.

**Comment by blink1073** [comment]
This brings to question whether JupyterLab as an app is meant to work without a settings backend.  As it stands, it will work, but print console errors and the settings editor will be empty.

**Comment by blink1073** [comment]
I think what makes the most sense here is to make a new example that uses the `jupyterlab` [build](https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/commands.py#L523) function to create a local application directory and `jupyterlab_launcher` to serve it.  This would serve as a custom spin example.

**Comment by ivanov** [comment]
I think that it should be possible to combine the components of JupyterLab without needing all of them. So to me, a settings backend should be optional. One of the things that was nice about the app example was how simple it was: specify which extensions I want, build em, with the minimal amount of python code to serve the page. The only dependencies for running and building that app example were the notebook and npm.

**Comment by blink1073** [comment]
I don't think we can meaningfully move forward on JupyterLab without assuming a backend settings system.  More and more of the functionality will rely on it.

**Comment by jasongrout** [comment]
One of our original goals was to make the settings storage pluggable, and have a *reference* settings storage implemented by the notebook server. For example, you could imagine in JupyterHub having a settings plugin that stores the user settings with the user metadata that JupyterHub enables.

So - we could bring back the simple app with a very simple settings plugin, which makes it easy to see how someone could override where settings should be stored.

CC @afshin - is there an easy way to include a plugin which is responsible for saving/fetching settings which does not use the services settings api?

**Comment by blink1073** [comment]
My concern is how the schema data itself can be accessed from the packages.  We could theoretically pull it out of `node_modules` using a script.

**Comment by blink1073** [comment]
If we had the schema data, then we could use the settings handler (which is moving to `jupyterlab_launcher`).

**Comment by blink1073** [comment]
Here's a script that uses [read-package-tree](https://github.com/npm/read-package-tree) from `npm` to extract schema and theme files:

```javascript
var rpt = require('read-package-tree');
var data = require('./package.json');
var path = require('path');
var glob = require('glob');
var fs = require('fs-extra');

var seen = {};

var schemaDir = path.resolve('./schemas');
fs.removeSync(schemaDir);
fs.ensureDirSync(schemaDir);

var themesDir = path.resolve('./themes');
fs.removeSync(themesDir);
fs.ensureDirSync(themesDir);


rpt('.', function (er, data) {
  data.children.forEach(function(child) {
    if (seen[child.package.name]) {
      return;
    }
    seen[child.package.name] = true;
    var jlab = child.package.jupyterlab
    if (!jlab) {
      return;
    }

    // Handle schemas.
    var schemaDir = jlab['schemaDir'];
    if (schemaDir) {
      debugger;
      schemaDir = path.join(child.realpath, schemaDir);
      var schemas = glob.sync(path.join(schemaDir, '*'));
      schemas.forEach(function(schemaPath) {
        var file = path.basename(schemaPath);
        var to = path.join('schemas', file);
        fs.copySync(schemaPath, to);
      });
    }

    // Handle themes.
    var themeDir = jlab['themeDir'];
    if (themeDir) {
      var name = child.package.name.replace('@', '');
      name = name.replace('/', '-');
      var from = path.join(child.realpath, themeDir);
      var to = path.join('themes', name);
      fs.copySync(from, to);
    }
  })
})
```
