### ISSUE TITLE
Error opening notebook in read-only folder

### ISSUE THREAD

**Issue by jedoe** [jupyterlab/jupyterlab#2819]
We have a JupyterHub-based training environment where notebooks are stored in personal, public (i.e., writable by everyone), and read-only folders. A typical workflow would allow a user to copy selected notebooks from the read-only folder into their personal folder (or a shared folder), so that they can be modified. We opted against copying all notebooks into the users’ personal folders during startup since not all users require to have all notebooks of all trainings in the their folders, and -- more importantly -- users have always access to the original notebooks if their want to start over again.

While copying the notebooks works fine, it is important to be able to open a notebook in the read-only folder to see its contents. Unfortunately, this leads to an error message in Jupyter Lab:

![screen shot 2017-08-10 at 10 09 36](https://user-images.githubusercontent.com/4791396/29183579-0f3fcd10-7db8-11e7-9afd-47f436ac479a.png)
(Jupyter tries to create a .ipynb_checkpoints file, but this fails since the directory is read-only.) 

In Jupyter Notebook (as opposed to JupyterLab), the behavior is much better: There is no error message; instead the user is informed that the Notebook is read-only:

![screen shot 2017-08-10 at 10 08 39](https://user-images.githubusercontent.com/4791396/29183604-289b9834-7db8-11e7-9daa-22ab5035e60b.png)

Would it be possible to mimic the Jupyter Notebook behavior in JupyterLab?

**Comment by blink1073** [comment]
Yep, we shouldn't be auto-saving or creating checkpoints if the file is read-only.
