### ISSUE TITLE
Bug in services: onDone handler?

### ISSUE THREAD

**Issue by cmoscardi** [jupyterlab/jupyterlab#2827]
Hi, I'm working on some [load test code](https://github.com/yuvipanda/jupyterhub-loadtest) for JupyterHub, and noticed that the `onDone` handler doesn't seem to be firing. I'm expecting `onDone` to fire once the code I've sent in has been executed successfully.

**NOTE**: I'm using 0.47.1 currently.

I've been using the following workaround via the `onIOPub` handler:
```
function(msg){
  if (msg.msg_type == "status" && msg.content.execution_state == "idle") {
    // do what I'd like to do in onDone
  }
```

Just for sanity, my `onIOPub` listener also has error message handling - I've managed to validate that the code I'm sending is successfully running, but `onDone` is still not firing.

(please pardon the potentially very antiquated JS)

**Comment by blink1073** [comment]
Hi @cmoscardi, done is tied to receiving both an idle message and a shell reply for the execute request message.  Can you verify with an `onReply` handler whether that message is getting back?

**Comment by ian-r-rose** [comment]
Closing due to lack of information. If this is still an issue, feel free to comment here and we can reopen.
