### ISSUE TITLE
Add functions and bindings for common notebook functions

### ISSUE THREAD

**Issue by oersted** [jupyterlab/jupyterlab#2832]
This is just a quality-of-life feature request.

I miss the following functionalities, they should be trivial to implement by combining other functions:

* Clean all output
* Run All
* Restart & Clean all output
* Restart & Run All
* Run all above
* Run all below

It would be lovely to include these in the menus, command palette and keyboard shortcuts. It was annoying not to have shortcuts for them in the notebooks.

EDIT: I now see that some of them are in the command palette, but it would be very nice to include them to the keyboard shortcut settings.

**Comment by ian-r-rose** [comment]
These are all available as menu items, and with the keyboard shortcut editor you can assign your own shortcuts to the commands. There has been some back and forth on whether to assign some of these shortcuts by default, and for right now the recommendation is for users to select their own shortcuts.

Closing as resolved, please let us know if this is not sufficent.
