### ISSUE TITLE
Finalize collapser design for beta

### ISSUE THREAD

**Issue by janmichiel** [jupyterlab/jupyterlab#2844]
This issue is being used to track work on the collapser for the beta release. For longer term work on the collapser, see #2636 

## Original post

Not sure where to post this, but this showed up at least in the latest 0.26.5 version of Jupyter lab.

The blue lint takes up a lot of space (including extra white space), and is not very pretty. I really hope this is not yet the final design? In my opinion people value jupyter for the clean design and look. A simple [+]/[-] icon near the In / Out would do the trick as well.

**Comment by janmichiel** [comment]
![capture](https://user-images.githubusercontent.com/23038495/29380425-004cde66-82c6-11e7-8f1b-d033cae95112.PNG)

**Comment by ellisonbg** [comment]
We are not done with the design of this. Although, that element is not just for collapsing input/output, it also is the primary indicator for which cell is selected/active. Thus, it needs to span the entire cell. But we do agree that the current design still needs improving.

**Comment by vidartf** [comment]
From a usability point of view, I would say that the collapse button (mouse click target) should always be visible, no matter if you are at the bottom, middle or top of the output. Then you can save some wear on the scroll wheel :)

**Comment by janmichiel** [comment]
Thanks for the reply, I now see what you're trying to do there.
Just checked the classic notebook just for reference, and must say that how cell selection is implemented there seems perfectly fine and very clear.
I don't directly see why collapse/expand should be integrated in the cell selection mechanism.

**Comment by ellisonbg** [comment]
There is a second thing we are trying to accomplish with these changes. We are also trying to modernize the design a bit. The classic notebook has lots of borders, which add visual complexity. We are seeing if we can move away from cells having multiple borders, hence moving away from using a border to indicate cell selection. Other frontends such as nteract and colaboratory have also gone in this direction. We fully agree we haven't arrived at the end point, but will continue to iterate and explore the options. Marking this as 0.27 will have another iteration to consider.

**Comment by ellisonbg** [comment]
I am going to use this issue to track the improvements to the collapser UI design I am going to make for the 0.27 release.

**Comment by janmichiel** [comment]
Hi Brian,
Nice improvement, the design looks a lot cleaner already! Below some feedback points that may help you to iterate further.

From my perspective the collapsing of cells is mainly for providing a better overview of the notebook to the user, and releasing screen real estate for things that do not need to be accessed right now. It is however useful to be quickly able to find and expand collapsed cells when you need it. From that perspective I would propose:

**Always show 1 line of code when the cell is collapsed.**
* Always show the the In [x] / Out [x] identifier. Easier to find the cell you're looking for.
* Show the first line of code/comment of the collapsed block. Easier to find what you're looking for.
* The one line of code/comment that is show can be greyed out so the user sees the cell is collapsed/not active.

Example for one cell: 
* Expanded /active cell
![expanded](https://user-images.githubusercontent.com/23038495/29636970-d954b210-8852-11e7-9d89-0a2dce58bc06.PNG)
* The same cell being collapsed
![collapsed_alt](https://user-images.githubusercontent.com/23038495/29636969-d94ba7f6-8852-11e7-9725-df2af5734883.PNG)

This prevents situations like this where it's very hard to find the information/ cell you're looking for.
![notveryclear](https://user-images.githubusercontent.com/23038495/29637012-0295bf16-8853-11e7-9f01-8046f335a904.PNG)


**Widening of cell highlight bar (blue bar)**
The cell highlight bar (blue bar) currently widens when hovering over it. I assume this is primarily a visual indicator that the area can be clicked for expanding/collapsing the cell? And possibly also for providing a bigger click surface.

I think this is useful for users at first as a visual cue, but after a while it loses it's value and is more of a nuisance. In this case I'd suggest implementing something like the 'Help >> User Interface Tour' option that can be found in the classic notebook. And keeping the blue cell highlight bar static width, clicking on or just to the right of the bar triggers the expand/collapse functionality.

**Collapse only at the cell level, not In/Out separately?**
So, I can understand that there might be some use cases here that make this desirable.
Then again, it also complicates the users interface somewhat fro my point of view. I always found the cell based design in the classic notebook (the 'cell' is the smallest building block) very nice. This design reduces complexity in the notebook and provides a great overview of what is going on. 
One option could be to only collapse at the cell level (In and Out are either both expanded OR both collapsed.
Don't know how other feel about this?

---
Hope the feedback allows you to iterate further. Cheers!

**Comment by janmichiel** [comment]
@ellisonbg Don't know how to open this one again. Or do you prefer to leave it closed, or create a new bug?

**Comment by akhmerov** [comment]
> Collapse only at the cell level, not In/Out separately?
> Don't know how others feel about this?

I believe hiding the input has a crucial application because it makes it possible to use the notebook as a live reporting tool. There the code in the cell would load the data and generate the plots, and the output would be the said plots. When presenting the results the boilerplate telling how exactly the plots were produced is often distracting and occupies a lot of space. On the other hand, being able to quickly modify the parameters/load a different dataset/etc. is very valuable. From this perspective a filtering tool like nbviewer would be much worse than input hiding in the notebook.

**Comment by akhmerov** [comment]
> This prevents situations like this where it's very hard to find the information/ cell you're looking for.

An alternative option (considered by @cameronoelsen IIRC) was to only leave a single UI element for a complete sequence of collapsed cells and indicate the number of cells being collapsed.

**Comment by akhmerov** [comment]
Additional suggestions about the collapser UI:
* Change the actions `hide code`, `hide output`, `show code`, `show output` to "hide **selected** code" etc. This would simplify collapsing/uncollapsing groups of cells
* Add keyboard shortcuts for these actions. As far as I can tell, leftarrow and rightarrow keys aren't used anywhere. Wouldn't these be good candidates?

**Comment by ellisonbg** [comment]
We definitely need to improve the input collapsing for the purpose of "reporting". +1

**Comment by ellisonbg** [comment]
I will review the UX of the collapser for the beta.

**Comment by ellisonbg** [comment]
List of things to check:

- [ ] Behavior with no outputs
- [ ] Firefox/Chrome consistency
- [ ] Make sure old styling is removed
- [ ] Decide what to do about collapser in non-notebook contexts (console, new view for cell, etc).
- [ ] Final visual design

**Comment by ellisonbg** [comment]
I am calling the collapser design final for the beta. We may make more changes over time, but we need to focus on other work.
