### ISSUE TITLE
Sorting of file names in file explorer

### ISSUE THREAD

**Issue by janmichiel** [jupyterlab/jupyterlab#2845]
Minor sorting issues based on file names
I would expect 'exercise 10' to be sorted below no. 9. etc

![capture](https://user-images.githubusercontent.com/23038495/29380306-905f11a0-82c5-11e7-8086-58e069a87850.PNG)

**Comment by ellisonbg** [comment]
This is the usual way filesystems sort files, which is why many notebooks on GitHub are numbers as 01, 02, 03, etc.

**Comment by janmichiel** [comment]
Ok, good suggestions, I'll try that
Below is btw how my OS sort the titles, which seems more intuitive from my point of view. Don't know if this is different on Linux/MacOS?
![capture](https://user-images.githubusercontent.com/23038495/29413474-c985926e-835c-11e7-89de-c99b4b8a7e06.PNG)

**Comment by blink1073** [comment]
It looks like JavaScript has support for this:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare has a `numeric` option.

**Comment by blink1073** [comment]
OSX Finder also sorts this way, I think we should too.

```javascript
'a10'.localeCompare('a9', navigator.language, { numeric: true })
1
'a10'.localeCompare('a9')
-1
```

**Comment by FreddieV4** [comment]
Hi there. I'd like to work on this if possible. Is there some place within the jupyterlab code I should be looking at in particular?

**Comment by blink1073** [comment]
Hi @FreddieV4, I'm in favor of this change, and welcome your contribution.  The sorting takes place [here](https://github.com/jupyterlab/jupyterlab/blob/fea3386321b86c776dc43b81903f63f0e4cae301/packages/filebrowser/src/listing.ts#L1811).

**Comment by blink1073** [comment]
It turns out that sorting numerically is crazy slow (1.45s vs 35ms without).  I had to revert this behavior in https://github.com/jupyterlab/jupyterlab/pull/2986.
