### ISSUE TITLE
Inconsistent link colors in notebook versus elsewhere

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2849]
Look like we are using MD blue 500 for links in the notebook and MD blue 600 elsewhere. The ones in the notebook look too bright. We should create a CSS variable in the themes and set this color across the board using that variable. For the light theme, I think MD blue 600 is probably about right.

**Comment by ellisonbg** [comment]
The FAQ is using `--jp-brand-color1`.

**Comment by ellisonbg** [comment]
Moving this to beta - want to take my time and get the CSS variables right on this one.

**Comment by jasongrout** [comment]
https://github.com/jupyterlab/jupyterlab/pull/3259 adds a semantic link color.

**Comment by blink1073** [comment]
Fixed by #3430.
