### ISSUE TITLE
Add API to pass initial command to terminal

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2855]
We are running into a lot of places where we want to be able to open a terminal and send it an initial command to run such as:

* `cd foo`
* `cd foo && pdflatex`
* etc.

We should add an API to the terminal extension that allows a string to be passed to the terminal that will be run once it comes up. We are already hacking around this in the Git extension.

**Comment by blink1073** [comment]
Working on this now.
