### ISSUE TITLE
Release date/time for 0.27

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2856]
Opening this issue as a place to discuss the release plans for 0.27. I have done a big issue triage pass and targeted a bunch of things to 0.27. I will start to dig into this stuff - thinking that maybe Monday is probably a good target.

@jzf2101 - can you open issues for any documentation work you think needs to be done?

**Comment by jzf2101** [comment]
I'm working on pulling details from the tutorial into the website

**Comment by ellisonbg** [comment]
Looks like many of the 0.27 issues have PRs open for them. Flying today, but I tomorrow I will blast through and review those and finish up a few more.

**Comment by ellisonbg** [comment]
Hi all, I am working on issues for 0.27. Unfortunately, there are a many regressions related to design, theming, design. I understand how these have crept in with all the theme refactoring, getting the dark theme going, etc. But it doesn't feel like we are very close to a JupyterCon level release at this point. Let's touch base in the morning - I will keep pushing hard and see where we can get.

**Comment by ellisonbg** [comment]
I just submitted a PR that fixes many of the design issues. It ain't pretty (especially the CSS and variables), but it will do for this release. 

The other ones that I think we should try to tackle for the release are:

* #2844 (significant redesign of the collapser we need to get in front of folks)
* #2881 (splash screen, even a minor improvement will help)
* #2850 (scrollbars are a mess on a Mac)

I can tackle these early tomorrow and get Cameron's help.

**Comment by ellisonbg** [comment]
OK we are close!!! I am working with @cameronoelsen on #2850 

We will be back at the hotel in a bit an can work with @blink1073 and others to cut the release

**Comment by blink1073** [comment]
Release notes:

- Added support for dynamic theme loading.  https://github.com/jupyterlab/jupyterlab/pull/2759
- Added an application splash screen.  https://github.com/jupyterlab/jupyterlab/pull/2899
- Enhancements to the settings editor.   https://github.com/jupyterlab/jupyterlab/pull/2784
- Added a PDF viewer.  #2867
- Numerous bug fixes and style improvements.

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/releases/tag/v0.27.0.
