### ISSUE TITLE
Mirrored output

### ISSUE THREAD

**Issue by pfajer** [jupyterlab/jupyterlab#2857]
Hi, I found number of references to mirrored cells or output but cannot find how to do it.  For me that's the major attraction of Jupyterlab.
thanks
peter

**Comment by ellisonbg** [comment]
@jasongrout what is the status of the mirrored cell which will replace mirrored output?

**Comment by pfajer** [comment]
Mirrored output would be good enough,  anything that shows functionality you have in the presentations.


On Aug 16, 2017, at 11:35 PM, Brian E. Granger <notifications@github.com<mailto:notifications@github.com>> wrote:


@jasongrout<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jasongrout&d=DwMCaQ&c=HPMtquzZjKY31rtkyGRFnQ&r=8waEScVAJus7pLy7oGBweQ&m=lNV0luDChM8AdIfZw-H5sDuF6qsEzH-qtrFAQe0_-zc&s=Mu1QHQJZeh71sLidOOCU8e06lUFMCw7mPSuGvoWPiMY&e=> what is the status of the mirrored cell which will replace mirrored output?

**Comment by blink1073** [comment]
Closing in favor of existing #2073.
