### ISSUE TITLE
MathJax rendering broken in 0.26.4?

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#2859]
If I open a notebook in JupyterLab the latex doesn't render correctly. Compare the below equation rendered in JupyterLab
![image](https://user-images.githubusercontent.com/881019/29399747-c98ff7f2-836d-11e7-917f-83085044615c.png)
...with the same equation rendered in the classic Notebook using the same server (i.e. opened from `/tree` rather than `/lab`)
![image](https://user-images.githubusercontent.com/881019/29399715-ad49d4be-836d-11e7-91d2-eedd044d618e.png)

In the JS console the error is apparent in that JupyterLab can't find a local MathJax under `static`:
![image](https://user-images.githubusercontent.com/881019/29399695-9199adac-836d-11e7-8183-bfdbfc19382e.png)

In the Notebook however it seems to also be looking for local MathJax under `static` but the request seems to succeed:
![image](https://user-images.githubusercontent.com/881019/29400135-697bcb64-836f-11e7-8ee6-a4c043125b2d.png)

Are there any known issues with MathJax and JupyterLab? Does this ring a bell for anyone?

**Comment by dhirschfeld** [comment]
Test Case:
```latex
\begin{align*}
    w_t &=
    \begin{cases} 
        \frac{1}{|T|} & t\in T\\
        0 & \text{otherwise}
    \end{cases}
\end{align*}
```

**Comment by blink1073** [comment]
What is your MathJax script tag in the JupyterLab page?  Here is what it says for me (and it renders fine in JupyterLab 0.26.5 with Notebook 5.0 and not JS console errors):

`<script type="text/javascript" src="/static/components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full,Safe&amp;delayStartupUntil=configured" charset="utf-8"></script>`

**Comment by dhirschfeld** [comment]
Hmmm, updating my environment including jupyterlab to 0.26.5 seems to have fixed it so will close...
