### ISSUE TITLE
Review extension documentation for the beta

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyterlab/jupyterlab#2860]
I read the docs at two locations:

* http://jupyterlab.readthedocs.io/en/latest/labextensions.html#example
* https://jupyterlab-tutorial.readthedocs.io/en/latest/extensions_dev.html#

To me it does not become clear whether those extensions are "front end extensions" like in Jupyter Notebook (or some equivalent term) or something else or why this schema of distinguishing between "server extension" "kernel" and "front end extension" has been changed. After reading https://jupyterlab-tutorial.readthedocs.io/en/latest/extensions_dev.html# I felt, that I did not fully understand what the extension landscape looks like.

What I understand so far is, that there are Plugins and that those are NPM packages. However, then the other documentation seems to be wrong giving an example, where an extension (not plugin?) is wrapped in a Python package.

There are also now multiple steps involved, it seems, in getting an extensions (or plugin?) running:

* build
* link
* install

While previously in Jupyter Notebook there was only:

* install
* enable

That raises questions:

* Do I write my extension in Typescript or JavaScript or Python?
* Is writing in Typescript the reason for having a _build_ step? So that the typescript gets compiled to JavaScript?
* (side question as a not so frequent NPM user: Can I make NPM packages from Typescript code or only for ECMA Script X?)
* Don't we still need to enable extensions? (or is it plugins?)
* What does the _link_ step do?

In example code I found the following content inside a `package.json` (of [filebrowser](https://github.com/jupyterlab/jupyterlab/blob/master/examples/filebrowser/package.json)):

    {
      "private": true,
      "name": "@jupyterlab/example-filebrowser",
      "scripts": {
        "build": "tsc && webpack",
        "clean": "rimraf build"
      },
      "dependencies": {
        "@jupyterlab/apputils": "^0.9.0",
        "@jupyterlab/codemirror": "^0.9.0",
        "@jupyterlab/docmanager": "^0.9.0",
        "@jupyterlab/docregistry": "^0.9.0",
        "@jupyterlab/filebrowser": "^0.9.0",
        "@jupyterlab/fileeditor": "^0.9.0",
        "@jupyterlab/services": "^0.48.0",
        "@jupyterlab/theme-light-extension": "^0.9.0",
        "@phosphor/algorithm": "^1.1.1",
        "@phosphor/commands": "^1.3.0",
        "@phosphor/widgets": "^1.3.0",
        "es6-promise": "^4.1.0"
      },
      "devDependencies": {
        "css-loader": "^0.27.3",
        "file-loader": "^0.10.1",
        "json-loader": "^0.5.4",
        "rimraf": "^2.5.2",
        "style-loader": "^0.13.1",
        "typescript": "~2.4.1",
        "url-loader": "^0.5.7",
        "watch": "^1.0.2",
        "webpack": "^2.2.1"
      },
      "version": "0.9.0"
    }

However, the docs state that:

> An Extension is a valid npm package that meets the following criteria:
>
> * Exports one or more JupyterLab plugins as the default export in its main file.
> * Has a jupyterlab key in its package.json which has "extension" metadata. The value can be true to use the main module of the package, or a string path to a specific module (e.g. "lib/foo").

Here the problem is, that I cannot find any `jupyterlab` key at all in this `package.json`. It is also unclear, whether that `package.json` is a proper `json` file, which uses strings as keys or can also use symbols without quotes, because the docs say:

> Has a jupyterlab key in its package.json [...]

… where the quotes are missing, but then later says that it must have metadata `"extension"`, where the quotes appear. Now the reader does not know, if that is on purpose or not.

It is also unclear, whether one needs to wrap that key `"extension"` inside another object called `"metadata"` or if that is only informing about the nature of the data. Examples:

    {
        "jupyterlab": {
            "metadata": {
                "extension": true
            }
        }
    }

or

    {
        "jupyterlab": {
            "extension": true
        }
    }

The docs look very principled and aiming for good coverage, which is great, but I feel, that too much NPM related knowledge is assumed on the reader side and that important details are missing. Developing extensions (or is it plugins?!) for JupyterLab is already more sophisticated than it has been before, because of the additional things one needs to learn (npm basics, typescript, new extensions structure inside the extensions themselves, new classifications of extensions(?)), so we need a really good documentation, which describes the process of writing extensions/plugins. Code examples are really missing, especially for the `package.json`, which seems to be more complex than simply writing `jupyterlab: {"extension":true}` in it.

I think this issue can simply be taken as feedback for the current status of documentation for developing extensions. I feel a bit bad about not being able to provide improvements for the docs, but that is, because I don't understand what is in there and did not take any part in developing JupyterLab or its code related to extensions.

If someone could provide more detailed description of the parts involved in writing extensions and post in this issue, that would be appreciated too.

**Comment by blink1073** [comment]
Thank you for the feedback, @ZelphirKaltstahl!  You have definitely uncovered some areas that can be improved upon.    Here are some direct answers to your questions:

- These are "front end extensions", in a different form than the notebook.  An extension is a now an npm package.
- The examples in the `examples/` folder are not of extensions but of using portions of the JupyterLab code base in other websites (as a component).
- Install is now equivalent to enable, unless explicitly disabled.
- Linking means that the source folder is re-installed during every build, assuring that the latest code in that folder is used.
- The extension can be written in either TypeScript or JavaScript.  TypeScript code is converted to JavaScript code by the TypeScript compiler.
- All of our packages use a `/src` folder that has the TypeScript code, and ship a `/lib` folder that has the compiled JavaScript code for external use.   The TypeScript code is meant as a developer aid.
- The proper format for an extension's package.json is

```json
{
    <name, version, dependencies, etc.>
    "jupyterlab": {
        "extension": true
    }
}
```

**Comment by ZelphirKaltstahl** [comment]
@blink1073 Thanks for clearing it up and posting!

I also managed to get a hello world plugin running and put it into a repository: https://github.com/ZelphirKaltstahl/jupyterlab-plugin-hello-world

**Comment by blink1073** [comment]
Nice!

**Comment by ZelphirKaltstahl** [comment]
@blink1073 @others

I've got an idea for making the documentation easier to understand and more applicable for totally new devs (of plugins or other parts). One example plugin for JupyterLab is the `file browser`. It consists of several parts like:

* the actual `FileBrowser` class, which is a PhosphorJS `Widget`
* the model `FileBrowserModel`
* the factory _interface_ `IFileBrowserFactory`
* `index.ts`
* and more files in <https://github.com/jupyterlab/jupyterlab/tree/master/packages/filebrowser/src>

Some of the parts are described at: <https://jupyterlab-tutorial.readthedocs.io/en/latest/patterns.html> (for example models are partially described there).

To make things easier to understand, it would help greatly to state for each of files and contained _class_ or _interface_ what its _responsibility_ is. For example for the model, one could think of something like:

> The `FileBrowserModel` is used to manage any kind of state, which is ultimately what the widget will work with. Models can be replaced (I got this from the docs) <insert what happens when a model is replaced here + how an example implementation of that whatever then happens looks like>. In case of the `FileBrowserModel`, the class takes care of (some state A), (some state b) and (some state C). For example if the user wants to delete a file through the file browser (widget), the widget needs to tell the `FileBrowserModel` about this intention, which will in turn take care of deleting the file, if possible.

If we had such text for the factory and the interfaces as well, it would help writing ones own plugins in the same style / manner. Currently there is a lot one has to figure out oneself. For example there is `IFileBrowserFactory` so it is an interface. There seems to be no implementing class however. My guess is, that implementations of the interface are created on the fly. So the question for a person wanting to develop a plugin arises, whether they should use such kind of interface, or simply go with some classes, as long as there is no reason for having an interface. A reason for example could be, that other classes want to implement the same methods, so that extracting them into an interface makes sense.

An explanation of the idea behind such a design would be helpful in many cases. Developers need to know what part of their plugin logic should go into which files or classes and interfaces, if they want to follow the logic, which is used currently in the plugins already available. This is best done with a description and examples in natural language.

Currently I am having a bit of trouble transforming the file browser plugin into another plugin, which is in the TabBar (side bar, left area), because I don't really know what logic I should put where. Especially how the factory is used is not so clear to me. I know it gets some initialization options (`IOptions`) for example, and that it calls a method `createFileBrowser` and I have a vague picture in my mind after watching the video about JupyterLab (https://www.youtube.com/watch?v=4Qm6oD_Rlw8) about the `DocumentRegistry` using the factory to actually create the `Widget`s, but I also still feel, that my idea about how this works and when exactly the factory is used from where is not so clear yet. The video is from last year and there might have been a lot of changes in the meantime. It also takes some times to watch the whole video, without a video index, so it's not very dev friendly ; ) Currently I am trying to figure these things out.

A general reference to the applied pattern might be missing, if it has a name. I am guessing it is some kind of MVC pattern (or MVP even?), but it is not mentioned in the [docs about Design Patterns](https://jupyterlab-tutorial.readthedocs.io/en/latest/patterns.html).

The file browser plugin is already quite a good example and it shows a lot of functionality. We would not need a detailed description for _every_ plugin out there, but a few essential ones would be great, trying to cover as much functionality one can have in plugins with as few as possible elaborate descriptions of existing plugins like file browser.

Would it be possible (knowledge and time constraints taken into account) for someone of the core development team to write desriptions for existing plugins in such style? Is there a hesitation to write this way, because of possible changes in how plugins are designed (because of alpha state)?

**Comment by blink1073** [comment]
Hi @ZelphirKaltstahl, thank you for expanding on this.  Agreed that we need to take a pass at expanding each of these points in the documentation and how the pieces link together.

**Comment by ellisonbg** [comment]
I am closing this one as the work on documentation has move along and will require a number of follow up issues. See #3534 for the initial burst of work.
