### ISSUE TITLE
Building plugin: Class 'ModelDB' incorrectly implements interface 'IModelDB'

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyterlab/jupyterlab#2861]
According to the guide at https://github.com/jupyterlab/jupyterlab/blob/master/docs/notebook.md , I have to install dependencies separately, when writing a plugin:

> Install the dependencies. Note that extensions are built against the released npm packages, not the development versions.

My `package.json` is:

    {
      "name": "hello-world",
      "version": "0.1.0",
      "description": "Hello World plugin",
      "main": "lib/index.js",
      "scripts": {
        "build": "tsc && webpack",
        "test": "echo \"Error: no test specified\" && exit 1",
        "prepublish": "npm run build"
      },
      "keywords": [
        "jupyter",
        "jupyterlab",
        "extension"
      ],
      "files": [
        "lib/*.d.ts",
        "lib/*.js"
      ],
      "author": "",
      "license": "UNLICENSED",
      "dependencies": {
        "@jupyterlab/application": "^0.9.0",
        "@jupyterlab/apputils": "^0.9.0",
        "@jupyterlab/coreutils": "^0.9.0",
        "@jupyterlab/docregistry": "^0.9.0",
        "@jupyterlab/notebook": "^0.7.0",
        "@phosphor/disposable": "^1.1.2"
      },
      "devDependencies": {
        "typescript": "^2.4.2",
        "webpack": "^2.2.1"
      },
      "jupyterlab": {
        "extension": true
      }
    }

I ran the following command to install the dependencies:

    npm install --save @jupyterlab/notebook @jupyterlab/application @jupyterlab/apputils @jupyterlab/docregistry @jupyterlab/coreutils @phosphor/disposable

(It is the same as in the md file, but I added `@jupyterlab/coreutils`.)

When I then run:

    npm run build

I get the followiing error:

    node_modules/@jupyterlab/cells/node_modules/@jupyterlab/coreutils/lib/modeldb.d.ts(265,22): error TS2420: Class 'ModelDB' incorrectly implements interface 'IModelDB'.ipynb_checkpoints/
      Types of property 'createList' are incompatible.
        Type '(path: string) => IObservableUndoableList<JSONValue>' is not assignable to type '<T extends JSONValue>(path: string) => IObservableUndoableList<T>'.
          Type 'IObservableUndoableList<JSONValue>' is not assignable to type 'IObservableUndoableList<T>'.
            Type 'JSONValue' is not assignable to type 'T'.
              Type 'string' is not assignable to type 'T'.
    node_modules/@jupyterlab/notebook/node_modules/@jupyterlab/coreutils/lib/modeldb.d.ts(265,22): error TS2420: Class 'ModelDB' incorrectly implements interface 'IModelDB'.
      Types of property 'createList' are incompatible.
        Type '(path: string) => IObservableUndoableList<JSONValue>' is not assignable to type '<T extends JSONValue>(path: string) => IObservableUndoableList<T>'.
          Type 'IObservableUndoableList<JSONValue>' is not assignable to type 'IObservableUndoableList<T>'.
            Type 'JSONValue' is not assignable to type 'T'.
              Type 'string' is not assignable to type 'T'.
    node_modules/@jupyterlab/outputarea/node_modules/@jupyterlab/coreutils/lib/modeldb.d.ts(265,22): error TS2420: Class 'ModelDB' incorrectly implements interface 'IModelDB'.
      Types of property 'createList' are incompatible.
        Type '(path: string) => IObservableUndoableList<JSONValue>' is not assignable to type '<T extends JSONValue>(path: string) => IObservableUndoableList<T>'.
          Type 'IObservableUndoableList<JSONValue>' is not assignable to type 'IObservableUndoableList<T>'.
            Type 'JSONValue' is not assignable to type 'T'.
              Type 'string' is not assignable to type 'T'.
    src/index.ts(6,15): error TS6133: 'NotebookActions' is declared but never used.

Since I did not touch `ModelDB` or `IModelDB`, I am now thinking, that the released modules on npm are not working correctly and do not implement the interface correctly. This prevents me from building my hello world plugin, which has the following source code:

    import {
        JupyterLab, JupyterLabPlugin
    } from '@jupyterlab/application';

    import {
        Notebook, NotebookActions
    } from '@jupyterlab/notebook';

    // Activate the jupyterhub extension.
    function activateExtension(app: JupyterLab): void {
        console.log('Hello World!');
        console.log(app);
        do_something_with_cells();
    }

    function do_something_with_cells(): void {
        let widget: Notebook;
        let nbModel = widget.model;

        // Make the changes while preserving history.
        let cells = nbModel.cells;
        console.log('cells:', cells);
    }

    /*************
      * FINALIZE *
      *************/
    // Initialization data for the jupyterlab_hub extension.
    const plugin: JupyterLabPlugin<void> = {
        // specify the init function
        activate: activateExtension,
        // give an id
        id: 'jupyter.extensions.jupyterlab-hello-world',
        // specify parts which are required for this extension to be able to run properly
        // (dependencies!)
        requires: [],
        // specify if the extension should be run automatically when all requirements are met
        autoStart: true,
    };

    // export the extension, which has the type JupyterLabPlugin
    export default plugin;

For now I am trying to get a handle on cells inside the notebook and simply log them to console, to see if I can actually access them that way.

I am not sure what I can do about the `ModelDB` or `IModelDB` issue. The issue only started to come up, when I installed the dependencies and started using them in the code. Before that I only logged `'Hello World!'` to console and it ran fine.

**Comment by ian-r-rose** [comment]
Hi @ZelphirKaltstahl, it looks like the version of `@jupyterlab/notebook` that you have installed is older (`0.7.0` vs `0.9.0`). That is likely bringing in an older version of `@jupyterlab/coreutils` (in which `IModelDB` resides), and can cause conflicts. Can you try again with a `package.json` with all `0.9.x` versions of the packages?

**Comment by ZelphirKaltstahl** [comment]
@ian-r-rose Thanks! I change the `package.json` to contain:

    "@jupyterlab/notebook": "^0.9.0",

instead of

    "@jupyterlab/notebook": "^0.7.0",

Then I ran `npm install` and `npm run build` and it worked!

I copied the notebook version from somewhere. What is a good practice to find the version one needs? Is it always the same second digit as for other packages, which a package depends on?

**Comment by ian-r-rose** [comment]
In practice the versions of the subpackages have been moving at the same rate, so are all the same number. They may start to drift a bit as development stabilizes; I don't think we have established much of a convention there.

**Comment by blink1073** [comment]
The [docs](https://github.com/jupyterlab/jupyterlab/blob/c6c60419c3ad43dbdf769c6173f3ab50fd5b8c0c/docs/extensions_dev.md#extension-authoring) have the following note:

Note that the application is built against released versions of the core JupyterLab extensions. If your extension depends on JupyterLab packages, it should be compatible with the dependencies in the `jupyterlab/package.app.json` file. 

Closing as answered, please feel free to reopen if you disagree, @ZelphirKaltstahl.
