### ISSUE TITLE
How to get current notebook inside a jupyterlab plugin?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyterlab/jupyterlab#2872]
I am trying to write a JupyterLab plugin, which interacts with a currently opened notebook or all currently opened notebooks.

In: 

https://github.com/jupyterlab/jupyterlab/blob/master/examples/notebook/src/index.ts

I found:

    let NOTEBOOK = 'test.ipynb';

and then later:

    let nbWidget = docManager.open(NOTEBOOK) as NotebookPanel;

and:

    const editor = nbWidget.notebook.activeCell && nbWidget.notebook.activeCell.editor;

Which seems to access a cells CodeMirror editor. From that point on, I guess the interface is the same as it was with plain Jupyter Notebooks.

However, in my plugin, I'd like to get the current notebook and do things with cells, for example getting the input of a code cell. In other functions I saw in JupyterLab's code, the notebook widget is usually a given parameter and I could not figure out a generally applicable way to get the notebook inside the plugin yet.

There are some functions in Juypter notebook, some like `selectedCells()`, which I used to use to implement front end extensions for Jupyter Notebooks.

I am not sure these kind of functions still exist or whether they are a good way to write plugins. If they are still the way to go, I'd like to know how to access them and if plugins are not developed in such a way, I'd like to know what the best approach is to interact with the notebook and its cells inside JupyterLab plugins.

**Comment by blink1073** [comment]
Hi @ZelphirKaltstahl, the interfaces are not the same between JupyterLab and Jupyter Notebooks.  Assuming `nbWidget` is the current `NotebookPanel`, you can get the text of the selected cells as follows (in ES6 format):

```javascript
  let selected = nbWidget.notebook.widgets.filter(cell => {
    return nbWidget.notebook.isSelected(cell);
  });
  let contents = selected.map(cell => {
    return cell.model.value.text;
  });
  console.log(contents);
```

**Comment by ZelphirKaltstahl** [comment]
How would I access such a `nbWidget` inside a plugin? I am looking for something like:

    nbWidget = getCurrentNotebook();

or:

    nbWidgets = getCurrentNotebookPanels();

**Comment by ian-r-rose** [comment]
Hi @ZelphirKaltstahl, you can get an `INotebookTracker` when registering your plugin, which has information about the currently focused notebook and its active cells. The interface can be found in 
`packages/notebook/src/tracker.ts`.

You can get the current widget using
```typescript
tracker.currentWidget
```

**Comment by ZelphirKaltstahl** [comment]
Thanks, I had a chance to look at the code and I have some questions about the `packages/notebook/src/tracker.ts`.

* Isn't an interface something, which defines what signatures of methods look like? It seems to me that the `INotebookTracker` is more than that, containing even some state. Is an interface in Typescript something else, than in for example Java?
* There are two exports with exactly the same name. One is:

      export
      const INotebookTracker = new Token<INotebookTracker>('jupyter.services.notebooks');

  and the other is:

      export
      interface INotebookTracker extends IInstanceTracker<NotebookPanel>

  How can this work? Does Typescript "know" that they are two different things and not care about the identifier? And which one am I getting, when I get a `INotebookTracker` inside a plugin? (Sorry I am totally new to Typescript and its type system ; )

**Comment by ZelphirKaltstahl** [comment]
I've tried getting an `INotebookTracker` in my extension, but I am having some trouble with it:

    import {
        JupyterLab, JupyterLabPlugin
    } from '@jupyterlab/application';

    import {
        INotebookTracker
    } from '@jupyterlab/notebook';

    // Activate the jupyterhub extension.
    function activateExtension(app: JupyterLab, notebooks: INotebookTracker): void {
        const nbWidget = notebooks.currentWidget;

        let selected_cells = nbWidget.notebook.widgets.filter(
            cell => nbWidget.notebook.isSelected(cell)
        );
        let contents = selected_cells.map(
            cell => cell.model.value.text
        );
        console.log(contents);
        console.log('Hello World!');
    }

    /*************
      * FINALIZE *
      *************/
    // Initialization data for the jupyterlab_hub extension.
    const plugin: JupyterLabPlugin<void> = {
        // specify the init function
        activate: activateExtension,
        // give an id
        id: 'jupyter.extensions.jupyterlab-hello-world',
        // specify parts which are required for this extension to be able to run properly
        // (dependencies!)
        requires: [INotebookTracker],
        // specify if the extension should be run automatically when all requirements are met
        autoStart: true,
    };

    // export the extension, which has the type JupyterLabPlugin
    export default plugin;

Screenshot when JupyterLab starts and opens the notebook (automatically):

![jupyterlab-error-plugins](https://user-images.githubusercontent.com/11130348/29511730-489749f2-8660-11e7-853b-048314962425.png)

Maybe I still need to react on some event, to let JupyterLab finish loading, so that the widget is not `null`?

**Comment by blink1073** [comment]
Hi @ZelphirKaltstahl, the notebook tracker has a [currentChanged](https://github.com/jupyterlab/jupyterlab/blob/474c0fb30011983ed3b5e1f1a182441e929d0a2a/packages/apputils/src/instancetracker.ts#L48) signal.  You can hook up to it in your extension as:

```typescript
notebooks.currentChanged.connect(() => { console.log('changed'); })`

**Comment by ZelphirKaltstahl** [comment]
@blink1073 `tsc` tells me that:

    Property 'notebooks' does not exist on type 'NotebookPanel'. Did you mean 'notebook'?

and if I change it back to `notebook` then:

    Property 'currentChanged' does not exist on type 'Notebook'.

Anyway, does this deal with `nbWidget` being `null`? My problem is, that I don*t understand, why it is `null`. If it is `null`, I cannot do anything with it. It's as if the widget is not ready yet for usage or not available when my extension runs. But that is only a guess.

**Comment by ian-r-rose** [comment]
Hi @ZelphirKaltstahl, the `currentChanged` signal is on the `INotebookTracker`, not on the `NotebookPanel` (which hosts individual notebooks).

The `tracker.currentNotebook` property may be null (if, for instance, you do not have any notebooks open), so you need to check for that case before performing any operations on it.

**Comment by ZelphirKaltstahl** [comment]
Thanks, I got it now!

I am using the `currentChanged` `ISignal` of the `INotebookTracker` (http://jupyterlab.github.io/jupyterlab/classes/_notebook_src_tracker_.notebooktracker.html) to call a function, which then uses the `ISignal` `activeCellChanged` of the `Notebook` (http://jupyterlab.github.io/jupyterlab/classes/_notebook_src_widget_.notebook.html) which is contained by the `NotebookPanel` (http://jupyterlab.github.io/jupyterlab/classes/_notebook_src_panel_.notebookpanel.html).

**Comment by hsjlxx** [comment]
Hi @blink1073 I have a question： 
There are some functions in Juypter notebook, some like `Jupyter.notebook.base_url` , `Jupyter.keyboard_manager`。 In jupyterlab, how to find them?

**Comment by blink1073** [comment]
Hi @hsjlxx, we don't expose that information in JupyterLab.  You can get the baseUrl from `PageConfig.getBaseUrl` in your plugin [1].  We are in the process of making keyboard shortcuts easier to add to the application in https://github.com/jupyterlab/jupyterlab/pull/5470.

[1] https://github.com/jupyterlab/jupyterlab/blob/3bd09cde3e723b7531c7e3d9fc5c3645ce2e268f/packages/coreutils/src/pageconfig.ts#L121

**Comment by hsjlxx** [comment]
@blink1073 ,thanks, I got it !

**Comment by ian-r-rose** [comment]
Closing as answered.
