### ISSUE TITLE
Duplicate module with same version numer

### ISSUE THREAD

**Issue by maartenbreddels** [jupyterlab/jupyterlab#2877]
I had `@jupyter-widgets/jupyterlab-manager@0.25.12` installed, then installed `jupyterlab-volume@0.4.0-alpha.4`, which depended on `@jupyter-widgets/jupyterlab-manager@0.26.0`, so I installed that as well. Now ipyvolume didn't work, so I checked:
```bash
$ npm ls @jupyter-widgets/jupyterlab-manager
@jupyterlab/application-top@0.9.0 /Users/maartenbreddels/anaconda3/share/jupyter/lab/staging
├── @jupyter-widgets/jupyterlab-manager@0.26.0 
├── UNMET PEER DEPENDENCY @types/three@*
├─┬ bqplot-jupyterlab@0.4.1
│ └── @jupyter-widgets/jupyterlab-manager@0.25.12 
├─┬ jupyterlab-volume@0.4.0-alpha.4
│ └── @jupyter-widgets/jupyterlab-manager@0.26.0 
└─┬ jupyterlab-webrtc@0.2.1
  └── @jupyter-widgets/jupyterlab-manager@0.25.12 
```
Reinstalling `jupyterlab-volume@0.4.0-alpha.4` fixed that, it gave me:
```bash
$ npm ls @jupyter-widgets/jupyterlab-manager
@jupyterlab/application-top@0.9.0 /Users/maartenbreddels/anaconda3/share/jupyter/lab/staging
├── @jupyter-widgets/jupyterlab-manager@0.26.0 
├── UNMET PEER DEPENDENCY @types/three@*
├─┬ bqplot-jupyterlab@0.4.1
│ └── @jupyter-widgets/jupyterlab-manager@0.25.12 
└─┬ jupyterlab-webrtc@0.2.1
  └── @jupyter-widgets/jupyterlab-manager@0.25.12 
```
That may not be so intuitive.

**Comment by sccolbert** [comment]
There's not much we can do about this. This is just how npm works.

**Comment by sccolbert** [comment]
In semver `0.25.x` and `0.26.x` are considered a major version apart

**Comment by sccolbert** [comment]
Although I'm not sure why `@jupyter-widgets/jupyterlab-manager@0.25.12` is not being deduplicated. Which version of `npm` are you using?

**Comment by maartenbreddels** [comment]
The `@jupyter-widgets/jupyterlab-manager@0.26.0` being there twice is an npm thing? 
Versions:
```bash
$ npm -v
3.10.10
$ node -v
v6.11.0
```

**Comment by maartenbreddels** [comment]
That 0.25.x are 0.26.x are there I understand, but I expected `jupyterlab-volume@0.4.0-alpha.4` to share the top `@jupyter-widgets/jupyterlab-manager@0.26.0` module, not have it's own copy.

**Comment by sccolbert** [comment]
Npm 3 should be deduplicating things. I can only imagine this is the result of some sequence of install/uninstall of various packages which has caused deduplication to not work. What happens if you do all of it from a fresh env?

**Comment by sccolbert** [comment]
In an event, we don't do deduplication ourselves, we rely on npm to do it.

**Comment by maartenbreddels** [comment]
Indeed, it's:
```bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.25.10
jupyter labextension install jupyterlab-volume@0.4.0-alpha.4
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.26
```
And then fixed by running again:
```bash
jupyter labextension install jupyterlab-volume@0.4.0-alpha.4
```
If it's out of your hands, too bad, but it will be a bad UX when upgrading things.

**Comment by sccolbert** [comment]
Given the all the things that NPM  5 broke, we're thinking of switching to Yarn. Maybe yarn handles this better as well.

**Comment by blink1073** [comment]
This is one of those times where we'd recommend `jupyter lab clean && jupyter lab build`.  I don't think we want to completely clear `node_modules` after every command, but it is certainly needed in some cases.

**Comment by jasongrout** [comment]
Closing as resolved, given Steve's comment.
