### ISSUE TITLE
Create VDOM based UI Controls

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#2880]
In JupyterLab, we currently end up doing a lot or work to implement basic UI controls, such as buttons, dropdowns, etc. We have plans to implement a consistent set of UI controls based on pure-functional VDOM (virtual-DOM) components that include our default styles. This is semi-blocked until we figure out what VDOM library we will use.

Previous PR that started some of this work:

#2209

Two older issues that were closed in favor of this one:

#804
#694

**Comment by saulshanabrook** [comment]
@gnestor has started some work on creating a UI component library based on React https://github.com/jupyterlab/jupyterlab/issues/5170, so I am closing this issue. Feel free to reopen if you would like!
