### ISSUE TITLE
Requirement that settings have to be valid JSON is not clear

### ISSUE THREAD

**Issue by stsievert** [jupyterlab/jupyterlab#2901]
After I change the settings in 0.27, I only see an option to revert the changes I made. I do not see an option to save the changes.

![screen shot 2017-08-23 at 10 26 40 am](https://user-images.githubusercontent.com/1320475/29623997-a718c850-87ed-11e7-8158-8ee4c5aa58ca.png)

If I click away from that file, I see this message:

<img width="933" alt="screen shot 2017-08-23 at 10 29 45 am" src="https://user-images.githubusercontent.com/1320475/29624165-036207e8-87ee-11e7-9b96-5906f5b2754c.png">

I have not seen an option to save the notebook (though I have at one point while playing around, and it was a check mark to the right of the undo arrow).

This is on latest pip release of jupyterlab, 0.27.

**Comment by blink1073** [comment]
Hi @stsievert, the editor only lets you save when it has valid JSON.   An empty string is not valid JSON.  We could perhaps special case an empty string and convert it to `{}` after saving.

**Comment by stsievert** [comment]
Ah, I see. That wasn't obvious – I assumed an empty cell would not override anything.

That special case would be useful, but it'd also be nice to have a JSON linter or a message on why it can't save.

**Comment by blink1073** [comment]
This is fixed by #3167.
