### ISSUE TITLE
PDF viewer not working in Safari

### ISSUE THREAD

**Issue by davidchall** [jupyterlab/jupyterlab#2902]
The PDF viewer added in v0.27 (#2867) is such a great idea, and I have tested that it works in Chrome on my Mac. However, it doesn't render the PDF in Safari.

<img width="1440" alt="screen shot 2017-08-23 at 1 01 34 pm" src="https://user-images.githubusercontent.com/1804856/29628364-3cf7b02e-8803-11e7-9ef1-c68db1f99ac1.png">

**Comment by davidchall** [comment]
The issue remains in macOS 10.13. 

However, I just noticed that Safari does render PDFs if you:
 1. Open the PDF file in JupyterLab
 2. Change the focus to an alternative tab
 3. Change the focus back to the PDF file tab

**Comment by ian-r-rose** [comment]
Thanks for the report @davidchall. I don't currently have access to a computer with Safari on it, but I will try to track one down to check it out.

**Comment by blink1073** [comment]
I can confirm this behavior in macOS 10.13 and Safari 11.0.

**Comment by snovaisg** [comment]
This issue remains. I'm using Mac 10.14 and Safari 12.0. I can't display any pdf files.

**Comment by jasongrout** [comment]
This is fixed in #6255.
