### ISSUE TITLE
Add proper Shift+tab indentation behaviour

### ISSUE THREAD

**Issue by artefom** [jupyterlab/jupyterlab#2906]
`Shift+tab` does not remove indentation level in .py files editor as supposed to.

If you select this code while editing .py (important! works fine in notebook) and press `shift+tab`

```python
def longest_common_substring(s1, s2):
    m = [[0] * (1 + len(s2)) for i in range(1 + len(s1))]
    longest, x_longest = 0, 0
    for x in range(1, 1 + len(s1)):
        for y in range(1, 1 + len(s2)):
            if s1[x - 1] == s2[y - 1]:
                m[x][y] = m[x - 1][y - 1] + 1
                if m[x][y] > longest:
                    longest = m[x][y]
                    x_longest = x
            else:
                m[x][y] = 0
    return s1[x_longest - longest: x_longest]
```
It turns into:

```python
def longest_common_substring(s1, s2):
    m = [[0] * (1 + len(s2)) for i in range(1 + len(s1))]
    longest, x_longest = 0, 0
    for x in range(1, 1 + len(s1)):
        for y in range(1, 1 + len(s2)):
            if s1[x - 1] == s2[y - 1]:
                m[x][y] = m[x - 1][y - 1] + 1
                if m[x][y] > longest:
                    longest = m[x][y]
                    x_longest = x
                    else:
                        m[x][y] = 0
                        return s1[x_longest - longest: x_longest]
```
While supposed to turn into:

```python
def longest_common_substring(s1, s2):
m = [[0] * (1 + len(s2)) for i in range(1 + len(s1))]
longest, x_longest = 0, 0
for x in range(1, 1 + len(s1)):
    for y in range(1, 1 + len(s2)):
        if s1[x - 1] == s2[y - 1]:
            m[x][y] = m[x - 1][y - 1] + 1
            if m[x][y] > longest:
                longest = m[x][y]
                x_longest = x
        else:
            m[x][y] = 0
return s1[x_longest - longest: x_longest]
```
As in any other code editor (including jupyter notebook)

**Comment by blink1073** [comment]
Hi @artefom, which version of JupyterLab is this?  I tried with 0.27 and got the expected `shift+tab` behavior.

**Comment by artefom** [comment]
I've checked it once again, the version is 0.27, bug is still here. Maybe it's because i've installed jupyter-lab for python3 with pip3. [Here is short video](https://www.youtube.com/watch?v=V5RQ58c987o&feature=youtu.be) about reproducing the bug

**Comment by blink1073** [comment]
Oddly, the behavior differs between Ubuntu and OSX.  https://github.com/jupyterlab/jupyterlab/pull/2969 forces `Shift-Tab` to `indentLess`.

**Comment by JustinGirard** [comment]
Was this ever fixed?

**Comment by jasongrout** [comment]
Are you seeing this issue in the latest jlab?

**Comment by JustinGirard** [comment]
I can check my version - 1.0.2. I'll update and see if that resolves the issue!

But, I will do that later, because I can't risk any slow down today :). I'll update this thread when I do, IF I have an issue.

**Comment by jasongrout** [comment]
Since this issue is closed from a long time ago, it would be better to open a new issue if you are seeing a problem.
