### ISSUE TITLE
Tabs broken in notebook cells

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#2909]
For both @sccolbert and I, inserting whitespace with tab seems to be broken in notebook cells.
Possibly related to #2868.

**Comment by blink1073** [comment]
Confirmed that it isn't related to #2868, because reverting that change has no effect.

**Comment by blink1073** [comment]
This appears to be a conflict between tab completion and tab-to-insert-space.  The behavior seems to be the same as in classic notebook.

**Comment by dhirschfeld** [comment]
Also seeing this - just hadn't had time to open an issue!

**Comment by ian-r-rose** [comment]
Closing, since this is the intended behavior. We *may* want to consider turning off tab-completion for non-code mimetypes in the future.
