### ISSUE TITLE
Markdown images in hidden folders

### ISSUE THREAD

**Issue by danpf** [jupyterlab/jupyterlab#2910]
basically:
Would it be possible to allow markdown to access hidden folders?

So I guess this is mildly related to this pr from a long time ago
https://github.com/ipython/ipython/issues/5157
But I was hoping that there would be a workaround by now, or some option to help me with this.
basically:
I often need to paste pictures into my jupyter notebook, I work with protein structures, and sometimes the best way to refer back to things is a picture. I think I have 2 options for this:

1. encode the image into my notebook
  a. I remember this working a while ago in notebook, but it doesn't seem to work for me now, i'm assuming similar functionality will eventually be in lab, but obviously not high priority.
  b. Also i'd rather not balloon the size of my .ipynb files w/ high res images.
2. load the image from the filesystem via markdown

so, since I like num2 the most I would prefer to have a .images folder because otherwise i can end up with 20+ jpgs clogging up my file explorer.  Obviously an 'images' folder would work, but then I would have hundreds of 'images' folders in my filesystem.  This isn't a bad thing, but annoying when essentially every directory I work in will have it's own images folder.

Therefore i'd like to store my images as files in hidden folders like '.images', this keeps all of my data in one place for me to reference, and doesn't annoy me when it clogs up my tab completion when i'm moving around in the filesystem. 

Currently when you try to use a hidden folder you get this
![jupyter_hidden_folder_img](https://user-images.githubusercontent.com/16297104/29733745-91e6efea-89a3-11e7-985f-afc31bbbd653.png)
and
![jupyter_hidden_folder_term](https://user-images.githubusercontent.com/16297104/29677711-d5ec6754-88b0-11e7-8f79-b38871e1361d.png)

I'm not super sure, but I was under the impression that markdown didn't have the ability to edit files in the first place, so it doesn't seem very unsafe (referencing the ipython issue) at first glance.

**Comment by blink1073** [comment]
Hi @danpf, this is a current limitation of the notebook server (which we are using from JupyterLab).  There is an open issue here: https://github.com/jupyter/notebook/issues/2659.

**Comment by danpf** [comment]
Okay i'll dig into the notebook deeper then! thanks! closing!
