### ISSUE TITLE
Jupyterlab 0.27.0 UI broken on Jupyterhub

### ISSUE THREAD

**Issue by DevMui** [jupyterlab/jupyterlab#2912]
Hello,

It seems like I have been coming back repeatedly after updating Jupyterlab on Hub. :sob: I understand that Lab does not officially support Hub but I think their combination provides great value.

The UI has been broken as the following.
![image](https://user-images.githubusercontent.com/19495980/29698679-60e1709c-8925-11e7-884d-a63812595d6f.png)

Output from shell:
![image](https://user-images.githubusercontent.com/19495980/29698757-f1f338ea-8925-11e7-9202-83b7bf7abcd0.png)

From Chrome console:

![image](https://user-images.githubusercontent.com/19495980/29699265-584e5446-8929-11e7-81b5-74161da671a7.png)

Unfortunately rolling back to 0.26 didn't solve the problem. It still remains broken.

**Comment by apcamargo** [comment]
Did you try it in a different browser? I'm using Firefox and everything is normal here.

**Comment by blink1073** [comment]
Hi @apcamargo, how did you install JupyterLab?  Can you describe the environment where your hub instance is running?

**Comment by joonro** [comment]
I'm having this issue as well - I had to reinstall anaconda to fix this, but another device of mine has the same issue when I updated jupyterlab from `0.26.5` to `0.27.0`.

**Comment by DevMui** [comment]
@apcamargo I have tried Chrome, IE and Firefox and none of them worked.
@blink1073 I installed Anaconda 3 with Python 3.6.2. Below is the jupyter-related conda packages I installed. Please let me know if you have other question.
![image](https://user-images.githubusercontent.com/19495980/29746492-20abdf22-8aaa-11e7-944f-8d75717361d6.png)

**Comment by joonro** [comment]
I removed `jupyterlab` via conda and installed it with `pip` and now it works fine, so maybe it is a conda related issue. I'm not sure if this is helpful to you.

**Comment by DevMui** [comment]
@joonro It solved my issue :+1: The only thing different is that the version of `jupyterlab_launcher`. `conda` didn't update it to 0.4.0 which likely to be an issue for this case.. Thank you!

![image](https://user-images.githubusercontent.com/19495980/29746536-3ab4b12c-8aab-11e7-8815-7b52941c701c.png)

**Comment by joonro** [comment]
Great!
