### ISSUE TITLE
Progress bar refresh bug

### ISSUE THREAD

**Issue by fonnesbeck** [jupyterlab/jupyterlab#2913]
We are using the `tqdm` packages to implement progress bars in PyMC3. However, JupyterLab does not seem to be able to update the progress bar, as it prints a new line instead of replacing the current line. The result is this:

![](http://d.pr/i/2n5TZZ+)

The progress bar works in Jupyter notebooks; this only occurs in JupyterLab.

Running 0.26.5 on Safari.

**Comment by blink1073** [comment]
Hi @fonnesbeck, we're tracking this in https://github.com/jupyterlab/jupyterlab/issues/1104.
