### ISSUE TITLE
Cell collapse bar not showing in Safari

### ISSUE THREAD

**Issue by stsievert** [jupyterlab/jupyterlab#2914]
Chrome:
<img width="1280" alt="screen shot 2017-08-25 at 10 37 00 am" src="https://user-images.githubusercontent.com/1320475/29721145-a8bedd62-8981-11e7-9f28-11819eb5b566.png">

Safari:
<img width="1280" alt="screen shot 2017-08-25 at 10 38 23 am" src="https://user-images.githubusercontent.com/1320475/29721134-9f81e122-8981-11e7-8841-d8db7569ec99.png">

In Safari, clicking where the bar is supposed to be does nothing.

**Comment by joshjob42** [comment]
It's actually present in Safari 11 beta, so once High Sierra roles out this will be fixed.

**Comment by stsievert** [comment]
Safari 11 is available for updates too. I'm on Safari 11 and OS X 10.12.6 Sierra (not High Sierra) and do see these bars.

**Comment by blink1073** [comment]
I confirmed as well, thanks for the heads up, @joshjob42!
