### ISSUE TITLE
Visual style of the dataframes is inconsistent between different kernels

### ISSUE THREAD

**Issue by apcamargo** [jupyterlab/jupyterlab#2915]
In version 0.27, the visual style of the dataframes is different when using the python and R kernels

**Comment by blink1073** [comment]
Hi @apcamargo, I think this may be a result of how the kernels are choosing to represent their data.  Do you see the same behavior in the classic notebook (`jupyter notebook`).

**Comment by apcamargo** [comment]
They look the same in the classic notebook. In the new version of JupyterLab, the visual style of the R's dataframes continued the same, the change occurred in Python notebooks

**Comment by jzf2101** [comment]
@apcamargo screenshots?

**Comment by apcamargo** [comment]
![screenshot from 2017-09-05 13 01 33](https://user-images.githubusercontent.com/22940964/30070632-72a30b42-923a-11e7-82b3-aeb9a1d91a44.png)
![screenshot from 2017-09-05 13 01 21](https://user-images.githubusercontent.com/22940964/30070635-737e1c5a-923a-11e7-8f84-c2c3091fae65.png)

**Comment by ellisonbg** [comment]
I will look into this for the beta...
