### ISSUE TITLE
Is it possible to connect a console to editors launched from the terminal?

### ISSUE THREAD

**Issue by choct155** [jupyterlab/jupyterlab#2924]
While it is great that codemirror offers vim bindings, it doesn't seem possible to configure a codemirror instance to reflect what might be contained in a .vimrc.  I am a novice in this area, but it seems like it's the same editor underneath with only bindings changed to given presets as desired.  

It is possible, however, to launch my native vim editor with my desired configuration from within the terminal.  The cost seems to be losing the ability to connect a console to the code contained in whatever file I am editing.

Have I missed a really obvious way of doing this?  Is it possible to provide this functionality?  In general, these seems aligned downstream with this is issue: https://github.com/jupyterlab/jupyterlab/issues/752  It just attacks it from a different side.

**Comment by ian-r-rose** [comment]
Hi @choct155 , you are right that the CodeMirror vim bindings are only a different keymap, and provide a very limited subset of the full vim functionality (including fancy `.vimrc`s and plugins).

The vim editor that you can launch from the terminal does not currently have any way of communicating with the other components to JupyterLab.

So unfortunately, you are right that there is no immediate way to have the vim integration that you are looking for.

**Comment by choct155** [comment]
Thanks for the quick feedback @ian-r-rose! A couple follow ups:

1. I saw chatter in another issue about a possible switch to [monaco](https://microsoft.github.io/monaco-editor/).  Would that resolve this issue by allowing for user-specific configuration?
2. One workaround would be to just continue to use an editor that sits outside of JupyterLab, and then just refresh the file I am working on.  However, the files don't refresh automatically inside JupyterLab, and it isn't clear to me how one might do this manually (short of closing and reopening the file).  Is there another method to refresh a file, or a setting that will get files to do it automatically?

**Comment by ian-r-rose** [comment]
Hi @choct155,
1. Yes, we have been discussing switching to Monaco, though we are currently blocked from doing that by a packaging issue specific to Monaco. We also are still discussing how to handle the difference between user-specific configuration and server-specific configuration.
2. We don't currently have a command for reloading a file from disk (other than what you described). It would, however, be fairly straightforward to implement a new command that does that.

(As a fellow vim user, I am also interested in improving the vim-ish experience)

**Comment by choct155** [comment]
Hello @ian-r-rose,

Thanks for the info on both fronts, and your role in developing this great project.  This has been helpful!
