### ISSUE TITLE
Starting with url "/lab/" breaks icons 

### ISSUE THREAD

**Issue by bsdz** [jupyterlab/jupyterlab#2931]
I was starting jupyter lab using a url along the lines of "https://localhost:8888/lab/", note the trailing slash. I'm not sure why I'd inserted the slash, perhaps out of habit. This led to most svg icons missing from interface. This is because the svgs are defined relative to the website root in "urls.css". Logging in console produced the following:

`[D 09:35:44.334 LabApp] Using contents: services/contents
[W 09:35:44.338 LabApp] 404 GET /lab/lab/api/themes/jupyterlab-theme-light-extension/icons/jupyter/image.svg (127.0.0.1) 5.72ms referer=https://localhost:8889/lab/
[D 09:35:44.340 LabApp] Using contents: services/contents
[W 09:35:44.343 LabApp] 404 GET /lab/lab/api/themes/jupyterlab-theme-light-extension/icons/jupyter/book.svg (127.0.0.1) 3.41ms referer=https://localhost:8889/lab/
[D 09:35:44.347 LabApp] Using contents: services/contents
[W 09:35:44.351 LabApp] 404 GET /lab/lab/api/themes/jupyterlab-theme-light-extension/icons/jupyter/directory.svg (127.0.0.1) 5.91ms referer=https://localhost:8889/lab/
[D 09:35:46.555 LabApp] Using contents: services/contents
...`

The simple fix was to remove trailing slash from url in the web browser, eg use "https://localhost:8888/lab" (this wasn't obvious without some investigating).

Not a big issue but perhaps might be wise to add a redirect so other (less tech savvy) users don't have to worry about it.

**Comment by dhirschfeld** [comment]
Will check if that was my problem too - #2907

**Comment by dhirschfeld** [comment]
Apparently my problem was different - neither with or without a trailing slash fixed the problem, but upgrading chrome *did* seem to work for me.

**Comment by blink1073** [comment]
This can be fixed by upgrading JupyterLab launcher `pip install jupyterlab_launcher==0.4.2`.  A conda release is in progress.
