### ISSUE TITLE
CSVs with Duplicate Column_Names, PhosphorJS Table viewer displaying wrong data

### ISSUE THREAD

**Issue by mlwohls** [jupyterlab/jupyterlab#2937]
When viewing/pre-viewing a csv with the "table" view, if the headers have duplicate column names, the "table" view is displaying the wrong data in the first instance of "column_name".  For example, if the csv had 2 columns with "A" as the header like:
[['A', 'b', 'c', 'A'],
[1,2,3,4],
[1,2,3,4],
...]
The viewer is showing rows of 4's in both columns instead of 1's in the first column and 4's in the last column.

*Screenshot of "test_cols.csv" opened in Ubuntu LibreOffice Calc:*
![image](https://user-images.githubusercontent.com/1048371/29793285-4f052ff0-8c11-11e7-9c44-dc2a043138e9.png)

*Screenshot of "test_cols.csv" opened in Jupyter Lab "Table" view:*
![image](https://user-images.githubusercontent.com/1048371/29793323-6c7cde5c-8c11-11e7-86bb-a381d2f7a4c8.png)

**Comment by sccolbert** [comment]
Thanks!

Looks like internally, the CSVViewer is using the `JSONModel` and generating a JSON table schema on-the-fly for the CSV data. In JSON table schema, the column names are assumed to be unique. Looks like we'll need to implement a custom data model for this.

https://github.com/jupyterlab/jupyterlab/blob/master/packages/csvviewer/src/widget.ts#L150

**Comment by mlwohls** [comment]
sccolbert - The json/dict model was my guess on the culprit (with the "key" being overwritten when writing the headers).  I should have dug-in before submitting.  If you can point me to where this is handled, I'd be happy to try and pull together a PR if that's helpful.

**Comment by sccolbert** [comment]
This should be fixed now. Turns out the D3 dsv parser didn't handle duplicate column names by default either, so I had to provide it with a custom transform.
