### ISSUE TITLE
Markdown Reference browsing not working

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab#2938]
v0.27.0

In the Commands Tab, when clicking on Help->Markdown Reference, a browser tab appears, showing Github Help page for Markdown, but none of the displayed links are clickable, despite the cursor changing to the hand when hovering over the hyperlink.

Using Chrome 60.0 on macOS 10.12.6

**Comment by blink1073** [comment]
Hi @michaelaye, I'm not sure what could be happening here.  I wasn't able to reproduce on my machine (Chrome 60.0 and macOS 10.12.16 as well).

**Comment by michaelaye** [comment]
I guess it's this:

![screenshot 2017-08-29 10 23 31](https://user-images.githubusercontent.com/69774/29832040-27f695e6-8ca4-11e7-9917-58c15f952c0c.png)

**Comment by blink1073** [comment]
Ah, I can reproduce this when launching an `https` version of JupyterLab.  For some reason the links within the `iframe` are being treated as mixed content even though they are `https` urls.

**Comment by michaelaye** [comment]
yes, i always use https versions for using it as a remote server.

**Comment by nickschurch** [comment]
Bump. I'm also having this issue.

**Comment by ian-r-rose** [comment]
These links now seem to be using `https`, so the issue appears to be resolved.
