### ISSUE TITLE
CodeMirror findByFileName should use the base file name

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#2943]
Otherwise files like `foo/bar/Dockerfile` are not properly identified as a `Dockerfile`.

**Comment by FreddieV4** [comment]
Hey @blink1073 I was wondering where this lives. I found this https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/mode.ts and am thinking that's what you're referencing

**Comment by blink1073** [comment]
Yep, this [function](https://github.com/jupyterlab/jupyterlab/blob/0aa76c6520566684beed831add96ae81405c0fd0/packages/codemirror/src/mode.ts#L127).
