### ISSUE TITLE
If Jupyter Lab freezes and you shut down server, it re-opens in frozen state

### ISSUE THREAD

**Issue by mlwohls** [jupyterlab/jupyterlab#2945]
For example, if you try to view a large JSON file in "editor" and it freezes (due to the size of the file), shutting down the process running Jupyter Labs (killing it in terminal) doesn't fix the issue.  When you try to restart Jupyter Labs, it tries to start back in the prior state (once again causing it to freeze while opening that large file).

I'm guessing the "re-open in prior state" functionality is a new feature.  If what I'm seeing is happening to others, a way to manage "what is re-opened" may need to be considered.  Happy to help dive in if you can point me to this section (assuming the saving and re-loading of state).

**Comment by blink1073** [comment]
Hi @mlwohls, the manual way to clear this is to open the browser JavaScript console from the frozen page and type `localStorage.clear()`, and then reload the page.  

We should support a command line flag that resets this state as well.  This would involve updating the [LabApp](https://github.com/jupyterlab/jupyterlab/blob/4f32a2708f21e3ebdfacd5721f5991d087add68d/jupyterlab/labapp.py#L98) to accept this flag, setting [page_config_data](https://github.com/jupyterlab/jupyterlab/blob/4f32a2708f21e3ebdfacd5721f5991d087add68d/jupyterlab/extension.py#L77) for this new flag, and then using it from the [statedb](https://github.com/jupyterlab/jupyterlab/blob/4f32a2708f21e3ebdfacd5721f5991d087add68d/packages/apputils-extension/src/index.ts#L197) to clear the state if the value is set using [PageConfig.getOption](https://github.com/jupyterlab/jupyterlab/blob/4f32a2708f21e3ebdfacd5721f5991d087add68d/packages/coreutils/src/pageconfig.ts#L45).

**Comment by ellisonbg** [comment]
+1
