### ISSUE TITLE
Duplicate File not implemented?

### ISSUE THREAD

**Issue by Dr-Irv** [jupyterlab/jupyterlab#2949]
Using Jupyterlab 0.12.1, I tried to duplicate a file by right-clicking on the file in the File Browser, and selecting "Duplicate".  A dialog came up that said:

Duplicate File
File Duplicate File

and then a Dismiss button

Only way to duplicate the file was to do a copy/paste.

**Comment by sccolbert** [comment]
The current version of JupyterLab is 0.27.x

That version has a "new view into file" option when you right click a tab.

**Comment by Dr-Irv** [comment]
@sccolbert Turns out that I installed JupyterLab into a python 3.4 environment from conda-forge, and that explains why I had the old version.  I'll close out the issue.
