### ISSUE TITLE
ENH: Design / CSS: small screen mode

### ISSUE THREAD

**Issue by GaelVaroquaux** [jupyterlab/jupyterlab#2953]
When giving tutorials in a room with a small screen (not small DPI, but small physical size), presenters need to blow up the fonts a lot for people in the back to see. With large fonts on small screen, the usability of the notebook suffers a lot.

@minrk suggested to open an issue here for Jupyterlab to consider a theming specific to such situation.

**Comment by ian-r-rose** [comment]
We now have a "Presentation Mode", as well as the ability to change notebook cell font sizes. Hopefully this goes a long way to improve the experience of presenting on a small screen. Closing as resolved, but please comment here if this is not sufficient and we can reopen.
