### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ghost** [jupyterlab/jupyterlab#2962]
Hello,
  After giving JupyterLab a 2 week trial, below are my pieces of compliments and criticisms about the app:

* No spreadsheet function (spreadsheets are useful for quick calculations displaying data. They're also quicker to create and use than jupyter notebooks
* No terminal in windows (in windows, there is no cmd / bash terminal. You could consider using the platform's native terminal, or creating your own)
* No shortcuts (i'm used to using shortcuts for about everything, and it's annoying when your shortcuts don't work or close the jupyter lab window
* Great UI (the UI in JupyterLab is very feature - packed, yet lightweight. I used spyder before, but now switched to jupyter lab)
* Great editor (JupyterLab's editor is actually better than github's own editor for most languages!)

Overall, JupyterLab proved to be very useful, but also inconvenient because of the bugs mentioned above.

**Comment by sccolbert** [comment]
Hi @ndrewxie and thanks for the feedback! 

- Spreadsheets are indeed great tools for certain workflows. There also require lot's of effort to implement. This sort of control is in our long-term plans, but we have many other things to get to first.
- Getting terminals to work on Windows is a medium-term goal for us. I'm a Windows user, and it's an important detail for me too.
- Can you elaborate a bit more about your issue with shortcuts? JLab *does* have a fairly advanced shortcuts system, but the browser prevents us from overriding some of its own built-in shortcuts. So the shortcuts themselves might be a bit different than what you'd expect, but JLab definitely treats shortcuts as a first-class citizen.

**Comment by ndrewxie** [comment]
If you use JS, couldn't you use e.preventDefault() and e.stopPropagation() to override it (inside of the keydown event handler)? That way, native shortcuts can be added.

**Comment by ndrewxie** [comment]
Installing additional kernels is also very difficult - many kernels only work on 1 or 2 OS's, and take quite a bit of effort and time to install properly.

**Comment by sccolbert** [comment]
@ndrewxie That wont work because the browser doesn't emit a key event when a builtin browser shortcut is pressed.

**Comment by sccolbert** [comment]
Installing kernels is outside the purview of JupyterLab. JupyterLab is simple another frontend on top of the existing Jupyter infrastructure.
