### ISSUE TITLE
Stretch factor of left column of settings panel.

### ISSUE THREAD

**Issue by sccolbert** [jupyterlab/jupyterlab#2971]
I think we should set the stretch factor of the left column of the settings panel to `0`, and the right column to `1`, so that the left panel *does not* resize when expanding the outer panel as shown in the gif below:
![browser](https://user-images.githubusercontent.com/137289/30090713-d4c1f60e-927a-11e7-80e5-aaddb943e085.gif)

**Comment by sccolbert** [comment]
This is also an easy fix for a new contributor. Just adjust the stretch factors in the settings panel constructor.

**Comment by sat28** [comment]
Hey @sccolbert  I would like to work on this issue. Can you guide where to look into first hand as I am a new contributor  ? Thanks

**Comment by eayoungs** [comment]
Hey there @sat28 , @sccolbert ! I thought I'd take a stab at this to get oriented to the codebase.

I followed up on Shaleen's insight into the _settingeditor.ts_ and found that the constructor is instantiating a `SplitPanel` object, which is subclassed from *@phosphorjs >* _splitpanel.d.ts_, where there are (2) methods.
- `function getStretch(widget: Widget): number;`
- `function setStretch(widget: Widget): number;`

I'm trying to call these methods on the panel object, passing in the widget for the sub-panel (_settingeditor.ts_ ln 150, 151) but I'm not sure what the widgets are called and I'm getting this error on build:

`error TS2339: Property 'setStretch' does not exist on type 'SplitPanel'`

### Can you confirm I'm on the right track and if so, how do I access those methods on the right object?

#### Thanks!

<img width="1230" alt="screen shot 2017-12-07 at 10 42 59 am" src="https://user-images.githubusercontent.com/4471418/33732596-e3e1cdee-db3b-11e7-8925-fdceaa36e3a4.png">

**Comment by sccolbert** [comment]
You are on the right track, however those are not methods on split panel instance, they are free functions in the `SplitPanel` namespace. You would invoke them like so:

```typescript
SplitPanel.setStretch(myWidget, value);
```

**Comment by eayoungs** [comment]
Awesome; thanks!

**Comment by ian-r-rose** [comment]
Fixed by #4772
