### ISSUE TITLE
Question: could neovim be embedded as an editor?

### ISSUE THREAD

**Issue by Alok** [jupyterlab/jupyterlab#2977]
One of the goals of the neovim project is embeddability, and it'd be interesting to see if someone could integrate it as a plugin into jupyterlab. It would work well for editing inside the cells.

**Comment by jasongrout** [comment]
Unfortunately for this, Neovim is not a javascript project, so you will not be able to embed it in JupyterLab. JupyterLab is a javascript application running in a web browser, so the plugins must run in a web browser.

If there was a javascript port of neovim, it would be a possibility.

**Comment by Alok** [comment]
Would these help?

- https://github.com/rhysd/NyaoVim
- https://github.com/rhysd/neovim-component

**Comment by stsievert** [comment]
It looks like https://github.com/rhysd/neovim-component is JS interaction with Neovim. Their minimal example from their README is

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <script src="/path/to/webcomponents-lite.js"></script>
    <link rel="import" href="/path/to/polymer.html" />
    <link rel="import" href="/path/to/neovim-editor.html" />
  </head>
  <body>
    <neovim-editor></neovim-editor>
  </body>
</html>
```

A neovim plugin would be rendering a file, so I think this would have to be a mime renderer extension (see https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html). A template of the mim renderer extension is at https://github.com/jupyterlab/mimerender-cookiecutter

I'd be happy to see this if it's implemented!

**Comment by FlyingWombat** [comment]
Is there an API for making a plugin that would do this?  
Embedding neovim (or other editors) seems out of scope for Jupyter itself, but would be great as a plugin.  
There is [jupyterlab-vim](https://github.com/jwkvam/jupyterlab-vim), but it's not nearly as powerful as full neovim integration would be. And it's not quite finished yet.

**Comment by robertocarta** [comment]
Any news on this?

**Comment by darribas** [comment]
+1 on this idea, it'd be fantastic to have NeoVim as option for an editor within JupyterLab
