### ISSUE TITLE
Working Directory

### ISSUE THREAD

**Issue by Magnus512** [jupyterlab/jupyterlab#2980]
Someone know how to change the default work folder in jupyter lab?, I know I can go to the folder and open a console there and then rin jupiter lab, but theres a way to change the default start folder?

**Comment by blink1073** [comment]
Hi @Magnus512, the working directory can be set when launching as `jupyter lab --NotebookApp.notebook_dir=<directory_name>`, or using Jupyter config.   You can run `jupyter notebook --generate-config` and then set the `notebook_dir` in `~/.jupyter/jupyter_notebook_config.py` by uncommenting that configuration option.

**Comment by aloosley** [comment]
So the --notebook-dir configuration key sets the notebook-dir.  However, opening terminal still defaults to the directory where jupyter lab was loaded (from cmd).  Is there any way to set the default terminal directory without loading jupyter lab in a different directory?

For example, if I run `jupyter lab` from root but want my default direct to be `/Users/bob/cool_repo` for some reason.  Is that possible?

**Comment by blink1073** [comment]
Hi @aloosley, that is not yet possible.  We are tracking that issue in https://github.com/jupyterlab/jupyterlab/issues/1366.

**Comment by kasrad** [comment]
Hi @blink1073, I tried to set the directory as ` jupyter lab --NotebookApp.notebook_dir=<directory_name>`. This command launched jupyter lab, however, when I tried the command `cd`, it did not return the directory I have set - it returned the default directory. Any tip on what should I do differently? Thanks!

**Comment by zeluspudding** [comment]
All, a temporary workaround is to follow these instructions from this [stackoverflow post](https://stackoverflow.com/a/40514875/3491991). :

> Use the jupyter notebook config file:
> 
> Open cmd (or Anaconda Prompt) and run jupyter notebook --generate-config.
> 
> This writes a file to C:\Users\username\.jupyter\jupyter_notebook_config.py.
> 
> Browse to the file location and open it in an Editor
> 
> Search for the following line in the file: #c.NotebookApp.notebook_dir = ''
> 
> Replace by c.NotebookApp.notebook_dir = '/the/path/to/home/folder/'
> 
> Make sure you use forward slashes in your path and use /home/user/ instead of ~/ for your home directory, backslashes could be used if placed in double quotes even if folder name contains spaces as such : "D:\yourUserName\Any Folder\More Folders\"
