### ISSUE TITLE
Rendering markdown cell block scrolling for ~600ms

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#2981]
On 4cc633e6670cc13e1724f5c666376aba2364458e, 
In train, so really bad network (is it relevant ? I have not seen it on good network...). Local server. OSX/Chrome 60 latest stable.

Everytime I shift-enter a markdown cell, the notebook can't scroll (or at least does not respond to finger scrolling) for ~600 ms.
The only thing I can correlate with is the following in the profiler.

<img width="831" alt="screen shot 2017-09-10 at 19 47 26" src="https://user-images.githubusercontent.com/335567/30256623-004a88c4-9661-11e7-906f-0814fc614192.png">

**Comment by Carreau** [comment]
I might be imagining things, but I even have lag when I move a round in command mode with the arrow keys, and even jump around after being stuck. You can't see the lag with my finger pressing down, but here is my screen after pressing "down" 6 times:

![lag move](https://user-images.githubusercontent.com/335567/30257786-4bfe6620-9669-11e7-80a0-d50a92b491d6.gif)

The Jump from 2 to 6 is not due to the Gif framerate.

**Comment by blink1073** [comment]
How many files are in your Downloads folder?  A large folder is both slow to fetch and render.

**Comment by Carreau** [comment]
> How many files are in your Downloads folder?

Quite a bit, though I'm astonished it slowdown or is fetched as every markdown cell rendering. Technically with what I am rendering it should not need to fetch anything from the filesystem.

**Comment by blink1073** [comment]
Ah, I had thought that this happened to coincide with a refresh of the file browser.

**Comment by Carreau** [comment]
Ah, no, all of this is during a session. I see the long lag every time I shift enter a markdown cell, even when there was no change to the cell content and it's already rendered and in command mode. 

The lag with the keypress to select next/previous cell as well. The filebrowser is not even visible during this.

Sorry if I was unclear.

**Comment by jasongrout** [comment]
All the same, can you try duplicating this without being in the downloads directory? The profiler output above seems to implicate the Downloads directory as a major issue.

**Comment by Carreau** [comment]
So yes, if I either move the current folder which is shown in the file browser to another directory, or move the notebook in another directory it works better. Though that's annoying as the folder where I usually have my notebooks is as big as `~/Downloads`. And it does not answer why it triggers this API call when I'm just stepping through a notebook and changing nothing, not even running code. 

Note that the file browser is hidden when this appears, which make things even weirder if this depend on the sate of a hidden component.
