### ISSUE TITLE
Merging tabs after they have been separated

### ISSUE THREAD

**Issue by Dr-Irv** [jupyterlab/jupyterlab#2989]
I'm using JupyterLab 0.27.

I Like the drag-and-drop feature, where I have two open notebooks, and can split the screen and see both at the same time.  But after doing that, I want to merge the tabs back so that I have the full window for one notebook.  I can't figure out how to do it.  When I try, it simply keeps the two notebooks in separate panes within the browser window.

Am I missing some trick, or is this yet to be supported?

**Comment by blink1073** [comment]
Hi @Dr-Irv, you should be able to combine them by dragging one to the center of the other (as opposed to the tab as in Chrome).

**Comment by Dr-Irv** [comment]
@blink1073 I have tried that.  I take the tab of one notebook and put it right on top of the tab of another notebook, and the panes remain split.  This is using Chrome.

**Comment by sccolbert** [comment]
Here's a gif of the action being discussed. For posterity:
![tabify](https://user-images.githubusercontent.com/137289/30349218-c5c08492-97d7-11e7-889e-956def21b5ef.gif)

**Comment by krassowski** [comment]
I struggled with this as well. I think that this is a valid UX issue - it would be much more intuitive if there was a half-transparent tab appearing in the tab-bar.

**Comment by andersrmr** [comment]
It worked for me.  Thx!

**Comment by jasongrout** [comment]
> I struggled with this as well. I think that this is a valid UX issue - it would be much more intuitive if there was a half-transparent tab appearing in the tab-bar.

CC @tgeorgeux.

@krassowski - @tgeorgeux is working with a few other people in exploring and testing a more intuitive drag and drop UX.

**Comment by benlindsay** [comment]
> I struggled with this as well. I think that this is a valid UX issue - it would be much more intuitive if there was a half-transparent tab appearing in the tab-bar.

I did too. I expected that dragging a tab A next to/on top of tab B would add tab A next to tab B on release.

> @krassowski - @tgeorgeux is working with a few other people in exploring and testing a more intuitive drag and drop UX.

I'm excited to see how this turns out!
