### ISSUE TITLE
Terminal Plugin not displaying

### ISSUE THREAD

**Issue by meidata** [jupyterlab/jupyterlab#2994]
Just install jupyter lab but there is no terminal tab in the bar, has anyone encounter the same problem?

**Comment by blink1073** [comment]
Hi @meidata, are you using Windows?  We don't yet have support for terminals on Windows, but it is a work in progress: https://github.com/jupyter/win-tornado-terminals.

**Comment by meidata** [comment]
Yes I am using windows, since I looked through many tutorials online which have the terminal tab on it, I thought there is something wrong with my installation. 

Thanks for the reply!

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyter/notebook/pull/3087, will be available in Notebook 5.3
