### ISSUE TITLE
Cannot change cell type (Firefox)

### ISSUE THREAD

**Issue by flesser** [jupyterlab/jupyterlab#2995]
The dropdown to select cell type seems to be broken in my browser (`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0`), I can't change a cell to Markdown or Raw.

![spectacle k11162](https://user-images.githubusercontent.com/510681/30430359-4605eb68-995b-11e7-941f-8e404df14f87.png)

As soon as I start to move the mouse, the dropdown disappears and I can't click anything.
As a workaround, I can use the arrow keys to navigate the dropdown and select an option by pressing Enter.

I can reproduce this issue both with the latest release (`pip install jupyterlab`) as well as with the current master (86b568d519706c7530f7150c11a2e1d4d0dac37f) installed according to `CONTRIBUTING.md`.

**Comment by blink1073** [comment]
Hmm, I just tried with Ubuntnu 16.04 and Firefox 55.0.2, and wasn't able to reproduce.  It disappears as you mouse down toward the options?

**Comment by Gusser93** [comment]
Can confirm. Using Ubuntu 17.04 and Firefox 55.0.2 64-bit. After clicking on the dropdown and moving the mouse to hover "Markdown" the menu disappears (I can hover "Code"). I can still use the arrow keys to select  "Markdown" and "Raw" with no problems and press enter to select them.

**Comment by flesser** [comment]
Hmm, doesn't seem to be very deterministic. Glad to have someone else confirm!
On my Laptop it worked as intended.

I tried again today on the PC and suddenly it worked. :confused:

The only thing I changed since the last try was to remove some old addons that prevented Firefox from running in "Multiprocess mode" (see http://www.omgubuntu.co.uk/2017/05/ubuntu-firefox-multiprocess-enable).

Actually I am now able to reproduce the bug, it seems to depend on Firefox Multiprocess Mode to be disabled, but don't ask me why... (See https://www.reddit.com/r/firefox/comments/5ezkak/how_to_disable_e10s_multiprocess_windows/ on how to enable/disable multiprocessing manually.)

### How to reproduce
* Open `about:config`, set `browser.tabs.remote.autostart = false`, restart Firefox
  - `about:support` should list "Multiprocess Windows" as disabled
  - JupyterLab's cell type selection broken, as soon as the mouse starts moving, the dropdown disappears

* Open `about:config`, set `browser.tabs.remote.autostart = true`, restart Firefox
  - `about:support` should list "Multiprocess Windows" as enabled
  - JupyterLab's cell type selection works!

@Gusser93, @blink1073:
Could you look into your `about:support` what your configuration of "Multiprocess Windows" is?

**Comment by Gusser93** [comment]
Had the same config. After switching to Multiprocess Windows I can select other cell types.
As an additional information, if i disable multiprocess the dropdown uses a standard small white theme. After enabling multiprocess it uses my bigger dark theme with gnome3.

**Comment by flesser** [comment]
Yup, same here (but using KDE/Plasma). With multiprocess the dropdown has a light gray background, without it was white (see screenshot in first post).

**Comment by blink1073** [comment]
I confirmed the behavior noted by @flesser [above](https://github.com/jupyterlab/jupyterlab/issues/2995#issuecomment-330209714).

**Comment by krassowski** [comment]
A note from the future: the issue re-appeared in times of JupyterLab 3.x and Firefox 89; the cause is not yet established, but given a proliferation of duplicate issues I am here to leave a note that we are tracking this in https://github.com/jupyterlab/jupyterlab/issues/10189.
