### ISSUE TITLE
Request: Use https links where available in help-extensions dropdown

### ISSUE THREAD

**Issue by canavandl** [jupyterlab/jupyterlab#2996]
Use https links where available in help-extensions dropdown. Currently:
* http://ipython.readthedocs.io/en/stable/ (IPython) 
* http://matplotlib.org/contents.html?v=20160707164940 (Matplotlib)
* http://pandas.pydata.org/pandas-docs/stable/?v=20160707164940 (Pandas)
are http links though https versions of the site are available.

Sympy (http://docs.sympy.org/latest/index.html?v=20160707164940) is the only http link that isn't available via https. Here's an issue to track that: https://github.com/sympy/sympy/issues/13313

**Comment by ian-r-rose** [comment]
Fixed by #2997.
