### ISSUE TITLE
UI for reloading an open notebook

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#2998]
Sometimes you want to reload a notebook because it's been changed without you explicitly typing in these changes. The easy way to this before was just refreshing the browser window, but it's not clear to me how to do this now. Maybe worth adding a "refresh notebook" menu option to the right-click menu?

**Comment by RafalSkolasinski** [comment]
Is refreshing page reloading notebook in jupyterlab now?

**Comment by ian-r-rose** [comment]
This command is now available from #4615, thanks @kcramer!
