### ISSUE TITLE
What icon font to use in JupyterLab?

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#30]
## Updated status
- We are currently using FontAwesome for the icon set in JupyterLab
- However, the @jupyter/designers feel the FA set is too heavy and complex for JupyterLab
- There is agreement from the @jupyter/designers that moving the the Material Design icons is a good idea.
- The MD icons are optimized for 24/18 px display, but in our UI a size of 16px is best for the MD icons.
- If we display the MD icons at 16px, users on low resolutions screens will see aliasing effects.

There is a PR here that implements the MD icons in the notebook toolbar: #686
## Original comment

As discussed in #29 with @ellisonbg, font-based icons are generally designed to be "pixel" perfect at specific font sizes. This is especially important on non-retina displays and font-engines that force font-hinting on the user. 

Both FontAwesome and Material icons are pixel perfect with a `font-size` that is a multiple of 14px, and the current font-size for the toolbar is 13px.

Here are some screenshots of the current toolbar with 13 and 14 px sizes:

13px:
![13](https://cloud.githubusercontent.com/assets/2397974/15951953/d1c7bed4-2e8a-11e6-958b-fbc35cd0c24e.png)

14px:
![14](https://cloud.githubusercontent.com/assets/2397974/15951962/e2d669d2-2e8a-11e6-96d0-a89ea5b122c1.png)

Now, zoomed-in versions:

13px
![13-large](https://cloud.githubusercontent.com/assets/2397974/15952085/02c89fac-2e8c-11e6-8629-2165d409bede.png)

14px
![14-large](https://cloud.githubusercontent.com/assets/2397974/15952126/50013f90-2e8c-11e6-8954-5eae26a1e589.png)

The latter is pixel perfect and much more crisp, and we can already see the difference in the original size. It become even clearer with the older font rendering engines of windows which does all kinds of ugly font hinting which cannot be disabled.

Hence we should
-  always use multiples of 14px for iconic fonts
- design new icons on the same grid size for all the glyphs, and preferably the one of FontAwesome which is 1792x1792. It is also important to pay attention to not have too large font bearings.

**Comment by SylvainCorlay** [comment]
cc @cameronoelsen

**Comment by ellisonbg** [comment]
I think this is important. I will submit a PR to start using 14px icons
from FA...

On Thu, Jun 9, 2016 at 7:05 PM, Sylvain Corlay <notifications@github.com>
wrote:

> cc @cameronoelsen <https://github.com/cameronoelsen>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/30#issuecomment-225076687>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0N2CzBI8pRRrOd1FHzzVfubOC2bKks5qKMZ0gaJpZM4IykKg>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
I think that many website are now moving toward svg icons instead of font that (were) a hack. 
See https://github.com/blog/2112-delivering-octicons-with-svg for example.

If you are redesigning icons, you should at least consider this options, which will give us some extra flexibility,

**Comment by ellisonbg** [comment]
Fantastic - I would love to get this working. I have been playing more with
our design and was feeling like being stuck at 14px was too limiting - in
many cases it was too big, in others too small. I think we should keep the
existing sized and investigate this

On Thu, Jun 9, 2016 at 9:36 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> I think that many website are now moving toward svg icons instead of font
> that (were) a hack.
> See https://github.com/blog/2112-delivering-octicons-with-svg for example.
>
> If you are redesigning icons, you should at least consider this options,
> which will give us some extra flexibility,
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/30#issuecomment-225091276>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0FvLNtL_s7Gnh3ECI9Dtnb4WcQmwks5qKOnmgaJpZM4IykKg>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by SylvainCorlay** [comment]
So having personally played with both, I would like to add it would still be required to have sizes for which icons are pixel perfect (so you would still be stuck with multiples of a certain size). There is nothing magic here: vector graphics scale *up*, not *down*!

The points raised in this github article are independent of this discussion and mostly concern
 - ease of authoring
 - absence of font-hinting on svg that can mess up the shape.

But pixel-perfect design for specified sizes remains necessary for rendering correctly at small sizes.

**Comment by SylvainCorlay** [comment]
Besides, in the debate of SVG vs font icons, there are still some advantages of fonts:

 - front-end framework are very good at rendering text and font faces. Performance-wise it is much faster to render a paragraph with thousands of small vector glyphs than 20 complex SVG images.
 - svg support is not equal among all browsers.

**Comment by Carreau** [comment]
css [support media queries](http://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/) so it's likely possible to have a (slightly) different appearance depending on width.

**Comment by Carreau** [comment]
I ment Svg support media queries, (fixed my comment).

**Comment by SylvainCorlay** [comment]
> I ment Svg support media queries, (fixed my comment).

Yeah, although it still means that we need to design icons for these sides.

**Comment by SylvainCorlay** [comment]
In terms of work flow for icon design

 - I generally use an authoring software like inkscape to devise a 1792x1792 grid SVG with major grid lines every 128px
 - Convert all items on the svg to paths.
 - Prevent intersecting and self-intersecting paths. All points and control points for bezier curves must have integral coordinates on the 1792x1792 grid.

Then I use FontForge to create the font.

**Comment by SylvainCorlay** [comment]
@ellisonbg finally, there is a standard convention in terms of icon naming that has been specified here:
https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

Entire desktop environments like kde use this convention.

If we adopt this convention, people will be able to integrate other themes like Plama NEXT

**Comment by ellisonbg** [comment]
Thanks for the links...

On Fri, Jun 10, 2016 at 10:06 AM, Sylvain Corlay <notifications@github.com>
wrote:

> @ellisonbg <https://github.com/ellisonbg> finally, there is a standard
> convention in terms of icon naming that has been specified here:
>
> https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
>
> Entire desktop environments like kde use this convention.
>
> If we adopt this convention, people will be able to integrate other themes
> like Plama NEXT
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyterlab/issues/30#issuecomment-225239491>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0PS6EH1A5BSJvp5drWqNxJl8ztHaks5qKZl4gaJpZM4IykKg>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by sccolbert** [comment]
Media queries are a less-than-half baked solution, because they only consider device/window width, not arbitrary node with. In the context of JLab, that's of little benefit to us.

A benefit of font icons, is that they can be styled and specified from CSS, unlike SVG icons where the url/nodes must be specified in Javascript.

**Comment by ellisonbg** [comment]
@SylvainCorlay could you have a look at this icon set:

http://zavoloklom.github.io/material-design-iconic-font/

It is Material Design based but they claim to be optimized @ 14px...

**Comment by SylvainCorlay** [comment]
Cool, this is good news! This is much better than 24px.

**Comment by SylvainCorlay** [comment]
I have an open issue in font-awesome asking to adopt the freedesktop naming convention, but it got little attention.
For jupyterlab, it could be a good idea if we want it to be also used outside of the browser and we want to adopt the theme of the desktop environment...

**Comment by ellisonbg** [comment]
We are now using svg icons in master. Closing this for now. If we want to change things further, let's open up new issues...
