### ISSUE TITLE
writing loop code over multiple lines

### ISSUE THREAD

**Issue by sirajpresswala** [jupyterlab/jupyterlab#3002]
currently all code inside a loop (eg: {if, else}, {Try, Except}) has to be contained in a single line for execution. It is possible to write the code over multiple lines? That functionality will allow to discretely run individual statements/variables of the loop without tiggering the whole loop itself. It would be a great enhancement and practical functionality. (You can do something like this with Spyder IDE -executing just the active line of code even if inside a loop)

**Comment by sccolbert** [comment]
@sirajpresswala I'm not sure what you mean. Both the notebook and the console allow you to have multi-line input.

**Comment by sccolbert** [comment]
Oh I think I get it. You mean rather than executing an entire input (which may be multiline) all at once, you want to be able to step through that execution, line-by-line?

**Comment by sirajpresswala** [comment]
yes, exactly. This is what i mean. Right now in jupyterlab the entire code within a loop has to be written in a single line and thus the whole code needs to be executed. If the same can somehow be done over multiple lines. than it will be possible to execute single line of code within the bigger loop. This can be very beneficial in testing/prototyping smaller portions of the loop without running the entire thing everytime.

**Comment by jasongrout** [comment]
In a text (python, markdown, etc.) file, you can highlight just one line and execute it. In the notebook, we've recently incorporated a command that lets you execute just a single line of code (or selected block) in an attached console. The command is "Notebook: Run selected text or current line in console". You can bind it to a keystroke for convenience. See https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#command-palette-items for more details.

**Comment by jasongrout** [comment]
Closing as resolved. @sirajpresswala - feel free to comment below if there is something more.

**Comment by vidartf** [comment]
@jasongrout Did you forget to close it, or are you waiting for a response?

**Comment by sirajpresswala** [comment]
thanks all. I have no more comments. the issue can be closed.

**Comment by blink1073** [comment]
Closing, cheers!
