### ISSUE TITLE
Keyboard shortcut table

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3005]
As @willingc suggested in https://github.com/jupyterlab/jupyterlab/issues/2976#issuecomment-330133858, it would be great to have a nice rendering of keyboard shortcuts that a person could, say, print out.

**Comment by amueller** [comment]
Or like, look at ;) I was a bit bummed when pressing "h" didn't do anything and I couldn't find a relevant entry in the "help" menu. I guess using the command palette is the standard way to find keyboard shortcuts now?

**Comment by amueller** [comment]
At least in my version the command palette only shows the "command mode" version of the shortcut, not the insert mode version. Having a rendering of the keyboard shortcuts would make that easy to do.
Right now I couldn't find that "ctrl + m + b" still inserts a cell below (but I tried and it worked ;)).

**Comment by choldgraf** [comment]
+1000 to this, I still haven't figured out a way to use a keyboard shortcut to open the commands tab, and I just found out from #2976 that the keyboard shortcuts customization is available at all.

BTW, when I hit the "table" view of the keyboard shortcuts, I get the following, which seems incorrect.

![image](https://user-images.githubusercontent.com/1839645/34152960-a319e0e8-e4b0-11e7-9014-cd51d76aab61.png)

I would expect the "key" field to contain things like `ctrl+shift+c`, not `docmanager:close`.

IMO at the very least, there should be a PR that adds a "keyboard shortcuts" item under `help`, and as a stop-gap measure this could open a page that says "we are working on a UI to display all keyboard shortcuts. In the meantime, see `File -> Settings -> Keyboard Shortcuts` for a list of all keyboard shortcuts." It is unlikely most people will organically think to go to file/settings/keyboard shortcuts on their own if all they wanna do is look up how to perform some action.

**Comment by jasongrout** [comment]
Closing in deference to the original issue: #2976.
