### ISSUE TITLE
can not use codeMirror's search or replace

### ISSUE THREAD

**Issue by rydeng** [jupyterlab/jupyterlab#3009]
ctrl + F or ctrl + shift + R， they can not be used . I can not input, it is like this: 
![1505809083 1](https://user-images.githubusercontent.com/9131195/30582519-8ddc55cc-9d56-11e7-82d0-e3b50256068a.png)

**Comment by blink1073** [comment]
Hi @rydeng, which OS/browser is this?

**Comment by TheIdealis** [comment]
I have the same error under:
- Arch Linux 4.12.13-1
- JupyterLab v0.27.0
with firefox and chrome.

**Comment by rydeng** [comment]
Hi @blink1073 ,

-OS: Linux ubuntu 4.4.0-96-generic
-browser: chrome

**Comment by blink1073** [comment]
Hmm, I tried with Ubuntu 16.04, with Chrome 61.0.3163.100 and Firefox 55.0.2, using the released JupyterLab 0.27.0, and both find and replace are working.

**Comment by blink1073** [comment]
@rydeng, @TheIdealis, was this in a notebook or a standalone text file?  I had assumed a text file but this is definitely broken in the notebook.

**Comment by rydeng** [comment]
@blink1073  hi it is in a notebook.

**Comment by blink1073** [comment]
Ah, okay, we are going to disable find/replace altogether until we have a solution that works for both standalone editors and the notebook.  cf #3032.
