### ISSUE TITLE
Improve multiple cells merging.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#301]
I think there might be a miss-handling of multiple cell merging where the cell that ends up selected in the wrong one post-merge. 

Example:
- create notebook with 6 cells containing each number 1 to 6. Select the first 3 (shift up/dom in command mode) 
- Merge them (shift-M)

Expected:
- Cell 1 - containing "1","2","3" is selected (behavior of current jupyter/notebook) 
- or
- Cell 2 - containing "4" get selected.

Observed:
- Cell 3 - containing "5" get selected. 

This is likely because we deselect post-merge the cell with the same indice as the head of the selection  before merge.

**Comment by ellisonbg** [comment]
@roshancvp any update on this?

**Comment by jasongrout** [comment]
FYI, this still happens for me on current master (3999f2b4b3ef8820e363c4cd0d31eeffd4ce5560).

**Comment by roshancvp** [comment]
@ellisonbg can we meet in person to discuss this?

**Comment by ellisonbg** [comment]
I just verified that this still happens in master as of today...
