### ISSUE TITLE
Add Copy/Paste to the terminal right-click menu

### ISSUE THREAD

**Issue by apcamargo** [jupyterlab/jupyterlab#3011]
Currently, we need to use shift to get the system right-click menu in order to copy/paste in the terminal. This functionality is hidden, so it would be interesting if copy and paste were added to the JupyterLab's right click menu.

**Comment by sccolbert** [comment]
Browser security policy does not allow us read from the clipboard outside of a native paste event. So unfortunately we can't have a paste option in a custom context menu. We could do something like google docs and open a separate dialog which then tells you do press `Ctrl+V` into a text field, but that's the best we can do.

**Comment by stephenakearns** [comment]
Hi @sccolbert - if it's not possible to add copy/paste to the right-click menu, would the team consider adding behavior like PuTTY where highlighted text is automatically copied to the clipboard?

**Comment by CptanPanic** [comment]
Yes this is true.  If you look at the terminal in chromeos, or on google's online terminal for cloud.  They utilize the putty method, whereas when you highlight text, it automatically gets copied, and a copy symbol appears overlayed on terminal.  And then it is a right click paste's it.

**Comment by dhirschfeld** [comment]
Wow. Glad I found this - I had no idea how to copy or paste!

I'm happy enough using shift-right-click however it's not very discoverable. Maybe the default context menu could have a not to that effect?

I'd like to give +:100: to @stephenakearns' suggestion to copy any selected text by default, or at least to have an option for such.

**Comment by gsemet** [comment]
+1

**Comment by consideRatio** [comment]
Like @dhirschfeld I had no idea you could shift+rightclick in order to get the normal rightclick context menu available and paste that way.

If that is the way to paste, making that option discoverable is important.

**Comment by CleoQc** [comment]
took me a while to figure out why I couldn't paste. Firefox does not offer the paste option when using shift-right click, but Chrome does.

**Comment by jasongrout** [comment]
> If that is the way to paste, making that option discoverable is important.

What would you suggest? What would *you* have discovered?

**Comment by consideRatio** [comment]
@jasongrout good question I respect the complexity of designing a good UI.

These are ideas on how I would had discovered it, if they are suitable is another question.
- If there was something written about it when right clicking
- If there was a paste button with a tooltip about the shortcut
- If there was some hint showing when CTRL+V was entered

**Comment by dhirschfeld** [comment]
> *What would you suggest? What would you have discovered?*

A description in the context menu itself. As it is it just has the `Refresh Terminal` option so there would be plenty of space to put a horizontal rule and then a suggestion to `Shift-Right-Click` to get the cut/copy/paste commands one would normally expect to see in a context menu - e.g.

![image](https://user-images.githubusercontent.com/881019/38527337-8cfe4714-3c9d-11e8-9964-847d4eb06b39.png)

**Comment by oxinabox** [comment]
Refresh Terminal does't seem as useful as copy-paste.
Maybe disable to custom right click menu when over the Terminal Pane,
and use the Native Menu.
and add the Refresh Terminal button to a tool-bar

**Comment by zuoxingdong** [comment]
It could be nice to add keyboard shortcut for copy selected block in terminal

**Comment by okTahvo** [comment]
Okay, so If I understand this correctly, JupyterLab terminal doesn't let you paste text in in Firefox and this has been an issue for a year now? Atleast I don't know how to paste text in Firefox Jupyter labs.

**Comment by steverweber** [comment]
I like @dhirschfeld direction with including some hints in the context menu.

But think we should go one more step and have the item in the context menu to open a popup with more details...

```
 - Refresh Terminal
 - Copy/Past - hints
```

[Copy/Past - hints popup]
```
The terminal passes Ctrl + C and other commands directly to the shell.
We do this so a running program can be closed using the unix 'ctrl + c`

To copy and past try:

(context menu) shift + mouse right click
(past) shift + insert
(copy) ctrl + insert
```

**Comment by kfox1111** [comment]
I was playing around with the newest kubernetes-dashboard and was able to shift-ctrl-c and shift-ctrl-v copy and paste in/out of the terminal. Getting the equivalent into jupyter's terminal would be awesome.

**Comment by arjuns2020** [comment]
Shift + ctrl + V
