### ISSUE TITLE
Is there any way to configure `jupyterlab` to *not* reopen every tab?

### ISSUE THREAD

**Issue by zoof** [jupyterlab/jupyterlab#3014]
I would prefer to only open notebooks that I specifically open rather than reopening every tab from the prior session.

**Comment by blink1073** [comment]
@zoof, currently there is no option for this.

**Comment by mcaudy** [comment]
If you click on the Command tab at the left and search for Close, there is a Close All command (no shortcut yet) which will close all of the tabs, except the currently selected tab

**Comment by ian-r-rose** [comment]
There is now a url option for clearing the state database: go to `/lab?reset` to wipe the previous session and start fresh. You could also set this as the default starting url for the notebook server if you never want to restore your previous session.

Closing this as answered, but if this is not sufficent, feel free to comment here and we can reopen.
