### ISSUE TITLE
saveAs() needs to work more like duplicate() + rename() than save()

### ISSUE THREAD

**Issue by timkpaine** [jupyterlab/jupyterlab#3015]
There seems to be a race condition between saveAs [completing](https://github.com/jupyterlab/jupyterlab/blob/07d7b32d1b1900bbb74f7b11a611371a27714d67/packages/docregistry/src/context.ts#L255), and the checkpoint being [created](https://github.com/jupyterlab/jupyterlab/blob/bd1f88d3935f7aaa96b48d350793f59cc4f04bfa/packages/docmanager-extension/src/index.ts#L234).

**Comment by timkpaine** [comment]
I can get around it by modifying my contents manager to return an empty model if the file doesn't exist, which is a bit of a strange interaction. Basically the save() completes after the get() is performed

**Comment by blink1073** [comment]
We need to check for the existence of a file before trying to save as the new file name (in case of overwrite), so I think the empty get() will still be needed in the contents manager.

**Comment by timkpaine** [comment]
What are you supposed to return from the check point manager for a file that doesn’t exist? You can’t return none, and it seems like anything else then triggers a get on the contents manager for a file that doesn’t exist. I get around this by returning an empty model from the contents manager, but that’s not a solution.

**Comment by timkpaine** [comment]
What are you supposed to return from the check point manager for a file that doesn’t exist? You can’t return none, and it seems like anything else then triggers a get on the contents manager for a file that doesn’t exist. I get around this by returning an empty model from the contents manager, but that’s not a solution.

**Comment by blink1073** [comment]
Ah, apologies, I was thinking of the file existence check, not the checkpoint existence check.  The file manager should return an empty array if there are no checkpoints, cf https://github.com/jupyter/notebook/blob/aa58dcbca4e0d64ae2343b2e72f90c1191fa5aa4/notebook/services/contents/filecheckpoints.py#L98
