### ISSUE TITLE
How to use IClientSession in plugin?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyterlab/jupyterlab#3018]
I want to write a plugin which, for testing purposes, executes a `CodeCell`.

On http://jupyterlab.github.io/jupyterlab/classes/_cells_src_widget_.codecell.html#execute I found, that I need a `IClientSession` to do that. So next I imported `IClientSession` in my plugin:

    import {
        IClientSession
    } from '@jupyterlab/apputils';
    ...

And then I require it later:

    const factoryPlugin: JupyterLabPlugin<IMyWidgetFactory> = {
        activate: activateFactory,
        id: 'jupyter.services.mywidget',
        provides: IMyWidgetFactory,
        requires: [
            INotebookTracker,
            IClientSession
        ],
        autoStart: true
    };

However, when I try to use it like:

    function activateFactory(app: JupyterLab,
                             notebookTracker: INotebookTracker,
                             clientSession: IClientSession): IMyWidgetFactory {
        const myWidgetTracker = new InstanceTracker<MyWidget>({namespace});
        const createMyWidget = (id: string, options: IMyWidgetFactory.IOptions = {}) => {
            const widget = new MyWidget({id: id,
                                         notebookTracker: notebookTracker,
                                         clientSession: clientSession});
            myWidgetTracker.add(widget);  // track the newly created widget
            return widget;  // return the widget
        };
        let defaultMyWidget = createMyWidget('mywidget-default-id');
        return {createMyWidget, defaultMyWidget, myWidgetTracker};
    }

I get an error from `tsc`:

    src/index.ts(99,9): error TS2708: Cannot use namespace 'IClientSession' as a value.

I checked what the difference between `INotebookTracker` and `IClientSession` is. The difference seemed to be, that in https://github.com/jupyterlab/jupyterlab/blob/b073429f009b524b79f7583214bdfa863b001516/packages/apputils/src/clientsession.ts also a `namespace` is exported and not only the `interface` as in https://github.com/jupyterlab/jupyterlab/blob/bdcb2049e39eb502968ec468f345854704b64dd6/packages/notebook/src/tracker.ts . Now my guess is, that my plugin gets confused and tries to use the `namespace`, instead of the `interface`.
I could not find how to tell typescript to not do that, so I am unsure how to make progress with this.

Here is the whole `index.ts`:

    import {
        JupyterLab, JupyterLabPlugin
    } from '@jupyterlab/application';

    import {
        InstanceTracker
    } from '@jupyterlab/apputils';

    import {
        MyWidget
    } from './mywidget';

    import {
        IMyWidgetFactory
    } from './factory';

    // import {
    //     MyWidgetModel
    // } from './model';

    import {
        INotebookTracker
    } from '@jupyterlab/notebook';

    import {
        IClientSession
    } from '@jupyterlab/apputils';

    /**
     * The MyWidget my_namespace token.
     * (This constant named "my_namespace" is later used as a parameter.)
     */
    const namespace = 'mywidget';

    // ==================
    // ACTIVATE FUNCTIONS
    // ==================
    function activateFactory(app: JupyterLab,
                             notebookTracker: INotebookTracker,
                             clientSession: IClientSession): IMyWidgetFactory {
        console.log("activating MyWidgetFactory (creating an implementation of IMyWidgetFactory)");
        // create a new instance tracker, which has knowledge about added widgets
        const myWidgetTracker = new InstanceTracker<MyWidget>({namespace});

        // createMyWidget is a function assigned to the constant createMyWidget.
        // It gets a hopefully unique id and IOptions.
        // The IOptions default to being empty.
        const createMyWidget = (id: string, options: IMyWidgetFactory.IOptions = {}) => {
            const widget = new MyWidget({id: id,
                                         notebookTracker: notebookTracker,
                                         clientSession: clientSession});

            myWidgetTracker.add(widget);  // track the newly created widget
            return widget;  // return the widget
        };
        let defaultMyWidget = createMyWidget('mywidget-default-id');
        return {createMyWidget, defaultMyWidget, myWidgetTracker};
    }

    function activateMyWidget(app: JupyterLab, factory: IMyWidgetFactory): void {
        // get the default browser
        const myWidget = factory.defaultMyWidget;

        // set a label which will be displayed in the sidebar for this widget
        myWidget.title.label = 'MyWidget';

        // add the widget to the left area in the application shell
        app.shell.addToLeftArea(
            myWidget,
            {rank: 600}  // should be lowest or highest
        );

        // Create a launcher if there are no open items.
        app.shell.layoutModified.connect(() => {
            if (app.shell.isEmpty('main')) {
                console.log('main area was empty!');
            }
        });
    }

    // =======
    // PLUGINS
    // =======
    const myWidgetPlugin: JupyterLabPlugin<void> = {
        activate: activateMyWidget,
        id: 'jupyter.extensions.mywidget',
        requires: [
            IMyWidgetFactory
        ],
        autoStart: true
    };

    const factoryPlugin: JupyterLabPlugin<IMyWidgetFactory> = {
        activate: activateFactory,
        id: 'jupyter.services.mywidget',
        provides: IMyWidgetFactory,
        requires: [
            INotebookTracker,
            IClientSession
        ],
        autoStart: true
    };
    // ========
    // FINALIZE
    // ========
    const plugins: JupyterLabPlugin<any>[] = [factoryPlugin, myWidgetPlugin];
    export default plugins;

**Comment by blink1073** [comment]
Hi @ZelphirKaltstahl, `IClientSession` is the `session` of the notebook panel, found by `notebookTracker.currentWidget.session`.

**Comment by blink1073** [comment]
That is, you don't include it in your `requires` in the application.

**Comment by ZelphirKaltstahl** [comment]
@blink1073 : Thanks, I got it :+1: ! Here is how I used it:

    CodeCell.execute(this.notebookTracker.activeCell, this.clientSession);

The `notebookTracker` is given in some `IOptions`, which are given in the `Widgets` activation function. Before the activation function is run, `INotebookTracker` is required and imported.

Note that it seems to be necessary to wrap the call to `CodeCell.execute` inside an `if` as follows:

    if (this.notebookTracker.activeCell instanceof CodeCell) {
        console.log(this.LOGTAG, 'Running Cell!')
        CodeCell.execute(this.notebookTracker.activeCell, this.clientSession);
    } else {
        console.log(this.LOGTAG, "selected / active cell is not a code cell!");
    }

Otherwise the TypeScript compiler `tsc` will complain, because it does not know whether the active cell is a `CodeCell` or another type of cell, which might not be executable.
You also cannot move the call to `CodeCell.execute` to another function, because the TypeScript compiler is unable to figure that out as well, even if it is the only thing you do in that other function. Weird.

**Comment by blink1073** [comment]
Great!  Yep, that is contextual typing: https://www.typescriptlang.org/docs/handbook/type-inference.html.

**Comment by ZelphirKaltstahl** [comment]
@blink1073 I find it weird, that it cannot infer the type when I put it into another function. I literally only cut and pasted the if-else thing into a function, which I wanted to call, but `tsc` says no. It seems like something that in this specific case could easily be added to the compiler. Maybe not in the general case though.

**Comment by blink1073** [comment]
Hard to say for sure without seeing the code.
