### ISSUE TITLE
Unable to copy link from markdown cell in notebook

### ISSUE THREAD

**Issue by mrocklin** [jupyterlab/jupyterlab#3023]
When clicking on a markdown link in the notebook I don't get any response.  When right clicking on it I'm unable to copy the address.  

![image](https://user-images.githubusercontent.com/306380/30786422-3490bfbc-a143-11e7-87d1-bc029c19df3c.png)

My guess is that this is non-trivial to resolve or has been discussed elsewhere.  If so then you have my apologies.

**Comment by sccolbert** [comment]
Hold shift when right clicking to get the native context menu.
