### ISSUE TITLE
Ctrl+/ does not comment out selected block of code

### ISSUE THREAD

**Issue by artefom** [jupyterlab/jupyterlab#3024]
Selecting block of code and pressing ctrl+/ does not work while editing .py file
Ubuntu 16.04 LTS. Python3. Jupyter-lab 0.27.0

**Comment by blink1073** [comment]
Thanks for the report!  Dev note: should be using the same `extraKeys` as the [classic notebook](https://github.com/jupyter/notebook/blob/11ba6be4328ca48f9c88cecbf023d0d8fb0dd4ff/notebook/static/edit/js/editor.js#L79).

**Comment by hypercodex** [comment]
+ 1

**Comment by lstodd** [comment]
+ 1

**Comment by lukesmurray** [comment]
+1
