### ISSUE TITLE
Clean up mimerender cookie cutters

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3026]
Hi all, I got a question from someone about the status of this cookie cutter:

https://github.com/jupyterlab/mimerender-cookiecutter

I don't think this uses our current APIs. Do we want to update it? Remove the classic notebook part of it? Deprecate it? It also has links to other deprecated instances of it. Thoughts?

**Comment by jasongrout** [comment]
CC @gnestor

**Comment by blink1073** [comment]
My understanding was that Grant was going to take a pass at updating it to work for both classic notebook and JupyterLab again.

**Comment by gnestor** [comment]
Like with https://github.com/jupyterlab/jupyterlab_geojson, we should add a deprecation notice to the repo description and redirect to https://github.com/jupyterlab/jupyter-renderers. 

We should also do the same for https://github.com/jupyterlab/jupyterlab_json.

I can add a section to the README or a `CONTRIBUTING.md` to jupyter-renderer instructing users how to add new renderers/extensions to the repo.

**Comment by blink1073** [comment]
I think we should still keep the `mimerender-cookiecutter` repo, even if it only has support for lab extensions, to make it easier to make third party mime renderers.  I updated the description of the `jupyterlab_json` repo.

**Comment by ian-r-rose** [comment]
Keeping as 1.0 for discussion. The `mimerender-cookiecutter` is pretty stale, and it may be too much work to maintain a cookiecutter that works for both lab and classic notebook. The `mimerender-cookiecutter-ts` is up to date and relatively simple.

**Comment by gnestor** [comment]
I agree that it may be too much work to maintain mimerender-cookiecutter. We can add a deprecation message or move it to the jupyter_attic org...

In a meeting a couple weeks ago, I proposed that we create a [react-scripts](https://www.npmjs.com/package/react-scripts)-like library that extension authors can add as a dependency and get dependencies/scripts for typescript, prettier, eslint/tslint, etc. This _jupyterlab-scripts_ library would provide a couple scripts to do things like build, clean, watch, format, lint, manage extension (install/uninstall/link/enable/disable), upgrade jupyterlab dependencies to be compatible with jupyterlab version, etc. This doesn't solve all of the problems that cookiecutters solve but it does take care of the templating for dependencies, scripts, and project config.

**Comment by jasongrout** [comment]
> I agree that it may be too much work to maintain mimerender-cookiecutter. We can add a deprecation message or move it to the jupyter_attic org...

Agreed.

**Comment by gnestor** [comment]
@jasongrout Would you mind moving the repo to the jupyter_attic org and adding a deprecation message reading?

```
DEPRECATED: Moved to https://github.com/jupyterlab/mimerender-cookiecutter-ts. A cookiecutter for rendering MIME type based output
```

I don't have adequate permissions...

**Comment by jasongrout** [comment]
Let's let the call for maintainers sit a bit first, then archive it if no one volunteers.
