### ISSUE TITLE
Find and Replace Error

### ISSUE THREAD

**Issue by dswalter** [jupyterlab/jupyterlab#3027]
I was using Find and Replace in JupyterLab 0.27.0, 
Chrome Version 60.0.3112.113 (Official Build) (64-bit) on a Macbook Pro running MacOS 10.12.6, and I ran into the following error: **a version of a search bar is 'stuck' to the cell.** Refreshing does not fix the issue.

![image](https://user-images.githubusercontent.com/7560282/30824466-b0b58e00-a1fd-11e7-8980-bd062388b6e4.png)

**Comment by blink1073** [comment]
We've disabled Find and Replace in notebooks, closing this in favor of https://github.com/jupyterlab/jupyterlab/issues/1074.
