### ISSUE TITLE
Should split cell strip empty newline at cursor ?

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#303]
This is arguable, I'm just filling it as this is a difference in behavior with the old notebook:

Create a cell with the following content (pipe `|`) represent the cursor

```
a
|
b
```

Split the cell using the split-cell shortcut.

Observed: first cell contain `a` and an empty line:

```
a

```

second cell just `b`:

```
b
```

Expected:

First cell does not contain empty line:

```
a
```

The reasoning being that split/merge should be inverse functions, and that merge does append a newline.

**Comment by jasongrout** [comment]
Just confirmed this still happens, and the current notebook does what @Carreau says.

**Comment by ellisonbg** [comment]
I agree we should follow the classic notebook on this.
