### ISSUE TITLE
Open with... menu for rst

### ISSUE THREAD

**Issue by DanielLenz** [jupyterlab/jupyterlab#3035]
First of all thank you for creating jupyter lab, I think it's great work and I've been using it a lot in the past few weeks.
I noticed that it's possible to open markdown files in preview mode with right-click and 'open with...', that does however not work for other formats such as rst.
If I rename the file to .rst instead of .md after opening the preview, it is correctly rendered as well.

**Comment by sccolbert** [comment]
The markdown preview functionality is provided by a plugin (as are most things in JLab). We would need a new plugin which knows how to render rst (which is much more complicated than markdown). This would be a good candidate for a 3rd party extension.

**Comment by DanielLenz** [comment]
Thanks for the clarification, I was indeed wrong when saying that rst rendering worked. Closing this and looking forward to the corresponding plugin, might look into it myself.
