### ISSUE TITLE
Jupyterlab Help

### ISSUE THREAD

**Issue by mcaudy** [jupyterlab/jupyterlab#3036]
Please add a JupyterLab Reference to the Help menu. All I see is iPython and Notebook.

**Comment by jzf2101** [comment]
See proposed changes

![screen shot 2017-09-28 at 11 45 48](https://user-images.githubusercontent.com/1373035/30976447-cedcae9e-a442-11e7-8734-df2eeb1fb91b.png)
![screen shot 2017-09-28 at 11 45 57](https://user-images.githubusercontent.com/1373035/30976453-d043f1a2-a442-11e7-9e67-10400da723ae.png)

**Comment by mcaudy** [comment]
I think these two mockups are a big improvement, which have added the JupyterLab Reference link, which was missing before.

However, I would also remove most of the other References, because they are not helpful to new JupyterLab users. In fact, they are confusing in this Help context. 

I discussed this at length with @jzf2101 and @jasongrout last week at Strata.  I think we agreed that for users who are not previously iPython users, it is not helpful to suggest to them to read the iPython docs, which in my experience are more of a confusion than a help for new JupyterLab users.

In addition, the link to the Notebook Reference can also be confusing because it links to the docs for the Jupyter Notebook, not for the JupyterLab Notebook, which are somewhat different.

Also, the link to the References for Numpy, SymPy, etc could be helpful in some cases, but should be moved to the sidebar only, and/or marked clearly as Additional Documentation, or something.

I will be happy to help with with creating the **_Jupyterlab Reference_** documentation, once I know JupyterLab better.
