### ISSUE TITLE
JupyterLab Help for new Jupyter users. 

### ISSUE THREAD

**Issue by mcaudy** [jupyterlab/jupyterlab#3037]
I have been using JupyterLab regularly, but I still find the JupyterLab documentation confusing.

**Comment by jzf2101** [comment]
@ellisonbg we were discussing adding user-facing documentation

**Comment by ellisonbg** [comment]
@mcaudy hi, thanks for opening this issue. As @jzf2101 mentioned, we are starting to think about user focused documentation. We fully acknowledge that our existing docs don't really target users.

What types of content would you find useful to have in user focused docs?

**Comment by jzf2101** [comment]
@sccolbert spoke with @mcaudy at the jupytercon sprint and answered a few of his questions @mcaudy could you describe what you found useful?

**Comment by mcaudy** [comment]
I also took the jupytercon half-day tutorial, where it was stated that **_dashboards_** are a major next step for jupyterlab, and custom dashboards are my major need for my genomics research, in addition to the IDE.  

The discussion with @sccolbert at the sprint evolved over time: at first it seemed that **dockpanel** is the tool for creating dashboards, but later it became clearer that dockpanel  is really for creating **_layouts_** in the IDE.  A different mechanism is planned for actual Dashboards. 

In @ch_doigs talk about Anaconda Project - which uses jupyterlab as it's default IDE - she showed a Dashboard that had been created with Bokeh. 

My understanding from both @sccolbert and @ch_doig is that at present, and going forward, **Bokeh** is likely to be a major way to create dashboards in jupyterlab.

One of my goals is to create both at **_tutorial_** and _**written documentation**_ that shows new Jupyter users who are not previous ipython users how to use Jupyterlab as an IDE, and also how create their own _**custom dashboards.**__

**Comment by jzf2101** [comment]
@mcaudy, who is @ch_doig?

**Comment by blink1073** [comment]
@jzf2101, Christine Doig: https://github.com/chdoig

**Comment by blink1073** [comment]
We are discussing dashboarding in JupyterLab in https://github.com/jupyterlab/jupyterlab/issues/1640

**Comment by jzf2101** [comment]
Since dashboarding is still being handled in #1640, the best route would be to focus on documentation for new users to jupyterlab

**Comment by mcaudy** [comment]
Sorry for the delay in responding.

I will focus on documentation for new users of JupyterLab here: #3037

I will focus on Dashboarding in #1404, as suggested.

@J Forde, Christine Doig works for Continuum (now Anaconda) on an Open
Source product called *"Anaconda Project"*, which uses *JupyterLab* as the
default IDE.

Christine has presented on this work at the recent JupyterCon and Strata
conferences.

She and others at Anaconda have also created substantial *documentation*
for *JupyterLab* , which should be merged with the Jupyter
Project documentation for JupyterLab, in order to avoid confusion to users
and duplication of effort.

I am willing to take the lead on doing that merging.

**Comment by jasongrout** [comment]
We're planning on focusing more on documentation between beta and 1.0 as well.

**Comment by jzf2101** [comment]
With #3794 we're almost done, I'm going to declare this closed
