### ISSUE TITLE
Saving a figure from a JupyterLab notebook

### ISSUE THREAD

**Issue by joaonatali** [jupyterlab/jupyterlab#3043]
I'm trying JupyterLab and am having trouble saving figures. Using vanilla Jupyter notebooks, I can two-fingers click (using macOS, either Safari or Chrome) and I get a browser menu that allows me to copy or save the figure.

In JupyterLab, this browser menu is replaced by notebook specific one with cell-related functions, as seen in the screenshot below.
<img width="480" alt="jupyterlab1" src="https://user-images.githubusercontent.com/2481376/31019366-18a18268-a4f5-11e7-90c1-012c725348fb.png">

Is there a way I can save a figure directly from the notebook in JupyterLab?

**Comment by jasongrout** [comment]
Yes. Shift-right-click gives you the normal browser window (so for a mac, hold down shift while doing the two-finger click).

**Comment by joaonatali** [comment]
This works perfectly, thank you.

**Comment by jasongrout** [comment]
Great!
