### ISSUE TITLE
Dashboarding in JupyterLab

### ISSUE THREAD

**Issue by orpheus92** [jupyterlab/jupyterlab#3050]
There have been some discussions on adding dashboarding in Jupyterlab. 
I just wonder whether there has been an update on this. 
Is that something that's gonna happen soon or are people working on it right now?

**Comment by orpheus92** [comment]
One other question is that will ipywidgets extension be released for NB in jupyterlab

**Comment by jasongrout** [comment]
> There have been some discussions on adding dashboarding in Jupyterlab.
> I just wonder whether there has been an update on this.
> Is that something that's gonna happen soon or are people working on it right now?

We're tracking dashboarding at #1640.



> One other question is that will ipywidgets extension be released for NB in jupyterlab

ipywidgets works great in the latest JupyterLab. Install the extension with:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

**Comment by jasongrout** [comment]
(Closing as answered - but feel free to continue dashboarding discussion on #1640 or to ask more questions here or on Gitter.)

**Comment by jasongrout** [comment]
> Is that something that's gonna happen soon or are people working on it right now?

More specifically, we're targeting post-1.0, so hopefully starting sometime next year.

**Comment by orpheus92** [comment]
basically I did the following:
pip install jupyterlab_widgets --user
jupyter labextension install @jupyter-widgets/jupyterlab-manager
When I typed: 
jupyter labextension list
@jupyter-widgets/jupyterlab-manager@0.27.1  enabled  OK shows up.
However, when I open jupyter lab and try to use ipywidget, it says 
[IPKernelApp] WARNING | Widget Javascript not detected.  It may not be installed or enabled properly.
Do you know why this happens. 
I am using the latest release of jupyterlab 

@jasongrout

**Comment by jasongrout** [comment]
You're using old instructions (pip install jupyterlab_widgets). You need to follow the instructions I listed above:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

You also need to be using ipywidgets 7 or later in python (it looks like you have ipywidgets 6 or earlier).

**Comment by orpheus92** [comment]
Thanks! It's working!

**Comment by orpheus92** [comment]
By the way, what might be the best way or respository to install ipywidgets to jupyterlab from source. 
For example, after git clone a repository, I could do npm install, npm run build, and then jupyter labextension install. 
Is that supported? @jasongrout

**Comment by blink1073** [comment]
Hi @orpheus92, the dev install instructions for the ipywidgets JupyterLab extension are [here](https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager#source-build).

**Comment by orpheus92** [comment]
Hi @blink1073 
I have the following issue when I run npm install. 
error TS2688: Cannot find type definition file for 'mathjax'.
Do you know why this happens?

**Comment by blink1073** [comment]
It is because of a declared `type` that shouldn't be there, cf https://github.com/jupyter-widgets/ipywidgets/pull/1739#issuecomment-334231206
