### ISSUE TITLE
How do I build the chat box and collaboration feature?

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [jupyterlab/jupyterlab#3051]
I want to test out the chat box and real time collaboration, but when I tried to build the master branch, I can't see how to enable the chat.

I am building like in a virtual environment like,
```
../experimental-python/bin/pip install -e . && \
npm install && npm run build:main && \
../experimental-python/bin/jupyter serverextension enable --py --sys-prefix jupyterlab
```

But when I run the server,
```
$ bin/jupyter lab --dev-mode
[I 12:08:31.512 LabApp] JupyterLab alpha preview extension loaded from /Users/macaidan/pkg/jupyterlab/jupyterlab
JupyterLab v0.28.0.dev0
Known labextensions:
```

I can't find a chat-box feature and the realtime collaboration appears to not work,
<img width="860" alt="screen shot 2017-10-03 at 12 10 21 pm" src="https://user-images.githubusercontent.com/6690599/31144014-2b9ab168-a834-11e7-854d-6263ed1a573c.png">

**Comment by sccolbert** [comment]
The collaboration features are part of this extension, which is not included in the core distribution (you must install it yourself):
https://github.com/jupyterlab/jupyterlab-google-drive

**Comment by blink1073** [comment]
@aidan-plenert-macdonald, extensions are also not used when running in `--dev-mode`.
