### ISSUE TITLE
File browser panel blinks under Safari

### ISSUE THREAD

**Issue by athornton** [jupyterlab/jupyterlab#3053]
I don't know if the change is High Sierra's Safari, or something that changed in the last few weeks in JupyterLab, but the page refresh makes the file browser blink very obviously under Safari.

It still looks fine under Chrome, which is where I do most of my work.  I'm not sure exactly at what point it changed.

**Comment by sccolbert** [comment]
Are you able to capture it in a gif?

**Comment by athornton** [comment]
![blinky](https://user-images.githubusercontent.com/2453165/31153545-9b7a04d0-a856-11e7-8810-59bab267ce3e.gif)

(The actual frequency is, AFAICT, 0.1 Hz, not 0.3ish Hz like the gif)

**Comment by blink1073** [comment]
I'm using Safari 11.0 (but not yet on High Sierra), and I don't see this behavior.

**Comment by athornton** [comment]
Safari: Version 11.0 (13604.1.38.1.6)
MacOS: 10.13 (17A365)

**Comment by sccolbert** [comment]
@blink1073 is the file browser listing using vdom?

**Comment by blink1073** [comment]
No, direct DOM manipulation with node re-use.
