### ISSUE TITLE
Frontend UI for listing installed extensions and their versions

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#3054]
It would be very useful to be able from JupyterLab itself to list all the installed extensions, their versions and if they are enabled or not.

The next logical step would then be to allow enabling/disabling from the UI and after that, to allow installing/uninstalling.

Even just being able to list the installed extensions and their versions would be useful for debugging purposes.

**Comment by blink1073** [comment]
I think we can do the listing of installed extensions and their versions for beta, and defer the UI until after that.

**Comment by dhirschfeld** [comment]
...perhaps as an addition to the about page

**Comment by ian-r-rose** [comment]
This has been implemented in the new extension manager. Thanks @vidartf!
