### ISSUE TITLE
BeakerX with Jupyterlab

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#3057]
Hi,
Is there a labextension existing for using BeakerX with JLab? I did some preliminary search but didn't find anything relevant. There exists a notebook extension for the same, but it doesn't work on Lab.

%%javascript
var plot = new beakerx.Plot({
    title: 'Title',
    xLabel: "Horizontal", 
    yLabel: "Vertical",
    initWidth: 800,
    initHeight: 500
})
plot.display(this);

**Comment by blink1073** [comment]
Hi @rsinha25, we don't support direct JavaScript output in JupyterLab.  It looks like a lab extension for beakerx is planned: https://github.com/twosigma/beakerx/issues/5268.

**Comment by rsinha25** [comment]
That's right, I was just wondering if there's already a labextension for beakerx, like there is for bokeh. (which is awesome!)

Also, I tried the following:
```
from beakerx import *
import pandas as pd

tableRows = pd.read_csv('data.csv', header=None)

Plot(title="Title",
     xLabel="Horizontal",
     yLabel="Vertical",
     initWidth=500,
     initHeight=200)
```

And get, 
Error displaying widget

Errors on the console are:

> Uncaught (in promise) Module beakerx, semver range 1.0.0 is not registered as a widget module
> Could not instantiate widget
> Error: Could not create a model.

Are these also related to labextension not being available, or is this expected to work and I am missing something?

**Comment by blink1073** [comment]
Yes, the beakerx lab extension would register a widget module similar to what [bqplot](https://github.com/bloomberg/bqplot/blob/b13e59b750fca55a240517c272206915836cd2e5/jslab/index.js#L28) does.

**Comment by rsinha25** [comment]
Cool, Thanks!
