### ISSUE TITLE
MimeDocument should delegate activate requests

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#3058]
We should be calling `activate()` on the wrapped renderer for `MimeDocuments`.  https://github.com/jupyterlab/jupyterlab/blob/d788d6e883a2462027b2a8dcbe319167fb34500a/packages/docregistry/src/default.ts#L485

**Comment by ian-r-rose** [comment]
Is there any chance this is related to #2902 ?

**Comment by blink1073** [comment]
Not sure, I'll check when I make the change.

**Comment by sccolbert** [comment]
We'll need to update the existing renderers to take focus, or perhaps *after* delegating the message, if they *haven't* taken focus, then we focus ourselves?

**Comment by blink1073** [comment]
Something like this could work:

```typescript

**Comment by blink1073** [comment]
@ian-r-rose, the PDF problem persists.

**Comment by ian-r-rose** [comment]
I should know better than to hope for free fixes.
