### ISSUE TITLE
Ctrl-S  regularly trigger browser "save page" instead of saving notebook

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#306]
I can get it pretty reliably, only when in command mode. 
I'm not sure of the sequence of action that triggers this, but I was able to get it "on camera" after triggering it by mistake. 

Here is me pressing Cmd-S on a notebook page:

![cmd-s](https://cloud.githubusercontent.com/assets/335567/16754104/18a17366-47b5-11e6-8d1f-b1f6fdd277f7.gif)

**Comment by willingc** [comment]
I think that if the user does not have focus on the notebook in command mode then the browser save pops up.

Trying this out, I found it difficult to determine whether I was in Command mode or Edit mode. I finally realized that green left edge of the cell is Edit mode. While, a blue edge is Command mode.

**Comment by Carreau** [comment]
> Trying this out, I found it difficult to determine whether I was in Command mode or Edit mode. I finally realized that green left edge of the cell is Edit mode. While, a blue edge is Command mode.

Good point, the edit mode should also show a pen in the upper-right corner.

**Comment by jasongrout** [comment]
When I click on command palette or file browser and press the save shortcut

**Comment by ellisonbg** [comment]
Marking as beta, we just need to ignore default for Accel+S on the body.
