### ISSUE TITLE
Server connection error display regression in master

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#3067]
It is currently showing the following as a result of #3052.  We should ensure a `.message` for the error or rethink how `showErrorMessage` is implemented.

<image src="https://user-images.githubusercontent.com/2096628/31299458-230615ba-aab4-11e7-829b-23464d296236.png" width=400>

**Comment by ian-r-rose** [comment]
Oops, my mistake. Will fix this weekend.
