### ISSUE TITLE
ctrl+dragging files to file pane shows a "Move" icon instead of "Copy" 

### ISSUE THREAD

**Issue by rmaurer-sfly** [jupyterlab/jupyterlab#3072]
A minor bug. 
ctrl+dragging files from windows file explorer to the file pane of Jupiterlab actually does copy and not move, but the icon shows "move", which is misleading

**Comment by kaszklar** [comment]
Hello @rmaurer-sfly could you elaborate on this? 
When trying to replicate this on a mac and with opera browser, when dragging the file, all that I see is a dashed line around the file pane.

**Comment by ian-r-rose** [comment]
A special CSS class is added when a native dragover event happens here:
https://github.com/jupyterlab/jupyterlab/blob/6185bda1b29967bfdcce3d320774e8534a51ac1c/packages/filebrowser/src/listing.ts#L621-L622

The CSS class for this is defined here: https://github.com/jupyterlab/jupyterlab/blob/6185bda1b29967bfdcce3d320774e8534a51ac1c/packages/filebrowser/style/index.css#L162-L165

I think we should be able to hint to the browser which cursor to use using the CSS `cursor` property.
