### ISSUE TITLE
Drag&drop does not work in notebook tabs of Jupyterlab 0.27.0

### ISSUE THREAD

**Issue by rmaurer-sfly** [jupyterlab/jupyterlab#3073]
Unlike classical notebook, text drag and drop does not work in notebook tabs in Jupyterlab 0.27.0.
Yet in editor tabs, drag and drop does work. Seems more like a bug rather than a needed enhancement

**Comment by ian-r-rose** [comment]
This seems to be working for me in 0.34. @rmaurer-sfly, can you check if this is still a problem?

**Comment by jasongrout** [comment]
Closing since the author did not follow up.
