### ISSUE TITLE
Struggling with extension installation with external npm packages

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#3082]
I'm trying to cut my teeth writing an extension but I have been running into issues. I am following through the xkcd tutorial. However, when I make an addition where I include an external npm package within my package.json file and call it within my index.ts when I either jupyter labextension link, or install, or build I get "Module not found" errors. It appears as if my package.json dependencies aren't being carried through into the jupyterlab staging installation.

Any ideas? I'm more than happy to provide more info.

**Comment by blink1073** [comment]
Hi @SimonBiggs, can you give the contents of your `dependencies` and `devDependencies`, or link to the extension itself if possible?

**Comment by SimonBiggs** [comment]
Hi @blink1073 thanks for such a quick response. I have made up a minimal example that causes this issue:
> https://github.com/SimonBiggs/jupyterlab-extension-attempt

When going through the link, build steps for an extension under development one of the errors I get is the following:

```
ERROR in ./~/jupyterlab-attempt/lib/index.js
Module not found: Error: Can't resolve 'rxjs/Observable' in '/home/simon/.pyenv/versions/3.5.3/share/jupyter/lab/staging/node_modules/jupyterlab-attempt/lib'
 @ ./~/jupyterlab-attempt/lib/index.js 4:19-45
 @ ./build/index.out.js
```

Please let me know if you need any more info.


I was looking at the build code within jupyterlab:
https://github.com/jupyterlab/jupyterlab/blob/2aa818d59c50bf84ab40d9327f83a9a78f179735/jupyterlab/commands.py#L552-L564

It made me wonder if there should be an explicit npm install for each extension around line 557. But I don't really understand much of the big picture around that code, so I'm not really sure...

**Comment by sccolbert** [comment]
It looks like there are different packages for rxjs that you should install, based on what toolset you are going to use it from:
https://github.com/ReactiveX/rxjs/tree/74ff4630770e330567cd8bd81ea2e22eb1876df2#all-module-types-cjses6amdtypescript-via-npm

My initial guess here is that the rxjs build systems is generating package layouts for a variety of tools, and you need to use the right package for the tools that you are using. It may be that Typescript is able to find the module for the package you've installed, but Webpack can't (because it's looking in a different place).

**Comment by SimonBiggs** [comment]
Thanks @sccolbert to simplify things a bit I have changed to importing bokehjs instead. It appears any external package that I include that is not already included within jupyterlab proper I get these errors. Here is the error when try to import bokehjs:

```
ERROR in ./~/jupyterlab-attempt/lib/index.js
Module not found: Error: Can't resolve 'bokehjs' in '/home/simon/.pyenv/versions/3.5.3/share/jupyter/lab/staging/node_modules/jupyterlab-attempt/lib'
 @ ./~/jupyterlab-attempt/lib/index.js 3:0-18
 @ ./build/index.out.js
```

Now I don't use rxjs at all. The only difference to cookiecutter is the "import 'bokehjs'" and bokehjs included within package.json:
https://github.com/SimonBiggs/jupyterlab-extension-attempt/blob/abbab90914348188d65e5985240eff1c0acfdf98/lib/index.d.ts

It's really got me stumped... Been trying to solve this for a few days.

**Comment by blink1073** [comment]
It looks like bokeh requires some specialized Webpack [config](https://github.com/bokeh/bokeh/blob/545a3145ef1d8497326bc44b45e2042e2df13fc8/bokehjs/webpack.config.js).  I don't see a way this could work even if we allowed extra WebPack config, due to non-relative imports like `var color_1 = require("core/util/color");` which are meant to be mapped to another part of the bokeh file structure.

**Comment by blink1073** [comment]
Here the [line](https://github.com/bokeh/bokeh/blob/545a3145ef1d8497326bc44b45e2042e2df13fc8/bokehjs/src/coffee/models/glyphs/webgl/line.coffee#L3) with the absolute import that gets transpiled to the import I mentioned above.

**Comment by SimonBiggs** [comment]
Hi @blink1073 what's an external package that you guys know works so I can try that?

**Comment by blink1073** [comment]
I swapped in backbone in your repo and it worked:

```diff
$ git diff
diff --git a/lib/index.d.ts b/lib/index.d.ts
index 1f5ba22..1a47358 100644
--- a/lib/index.d.ts
+++ b/lib/index.d.ts
@@ -1,5 +1,4 @@
 import { JupyterLabPlugin } from '@jupyterlab/application';
-import 'bokehjs';
 /**
  * Initialization data for the jupyterlab-attempt extension.
  */
diff --git a/lib/index.js b/lib/index.js
index 8dbdf44..95bb81f 100644
--- a/lib/index.js
+++ b/lib/index.js
@@ -1,6 +1,6 @@
 "use strict";
 Object.defineProperty(exports, "__esModule", { value: true });
-require("bokehjs");
+var backbone = require("backbone");
 /**
  * Initialization data for the jupyterlab-attempt extension.
  */
@@ -8,6 +8,7 @@ var extension = {
     id: 'jupyterlab-attempt',
     autoStart: true,
     activate: function (app) {
+        console.log(backbone);
         console.log('JupyterLab extension jupyterlab-attempt is activated!');
     }
 };
diff --git a/package.json b/package.json
index 9d9af1a..21ba224 100644
--- a/package.json
+++ b/package.json
@@ -21,6 +21,8 @@
   },
   "dependencies": {
     "@jupyterlab/application": "^0.10.0",
+    "@types/backbone": "^1.3.37",
+    "backbone": "^1.3.3",
     "bokehjs": "^0.12.9",
     "rxjs": "^5.4.3"
   },
diff --git a/src/index.ts b/src/index.ts
index 0d46ca8..23a3530 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -2,7 +2,7 @@ import {
   JupyterLabPlugin
 } from '@jupyterlab/application';

-import 'bokehjs';
+import * as backbone from 'backbone';


 /**
@@ -12,6 +12,7 @@ const extension: JupyterLabPlugin<void> = {
   id: 'jupyterlab-attempt',
   autoStart: true,
   activate: (app) => {
+    console.log(backbone);
     console.log('JupyterLab extension jupyterlab-attempt is activated!');
   }
 };
diff --git a/tsconfig.json b/tsconfig.json
index 3077d87..ac67e59 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -8,8 +8,7 @@
     "moduleResolution": "node",
     "target": "ES5",
     "outDir": "./lib",
-    "lib": ["ES5", "ES2015.Promise", "DOM"],
-    "types": []
+    "lib": ["ES5", "ES2015.Promise", "DOM", "ES2015.Iterable"]
   },
   "include": ["src/*"]
 }

ssilvester: ~/workspace/jupyter/test/jupyterlab-extension-attempt (HEAD (no branch)) 5
```

**Comment by SimonBiggs** [comment]
Thanks for that. There must be something weird with my setup. I've just swapped over to backbone. I've updated the repo. When I run `jupyter lab build` I get the following error:

```
ERROR in ./~/jupyterlab-attempt/lib/index.js
Module not found: Error: Can't resolve 'backbone' in '/home/simon/.pyenv/versions/3.5.3/share/jupyter/lab/staging/node_modules/jupyterlab-attempt/lib'
 @ ./~/jupyterlab-attempt/lib/index.js 4:15-34
 @ ./build/index.out.js
```

**Comment by SimonBiggs** [comment]
So, I was able to get both rxjs and backbone working, but only by manually installing the dependencies into staging during the jupyter build process:

```diff
diff --git a/jupyterlab/commands.py b/jupyterlab/commands.py
index eb866ba..df26982 100644
--- a/jupyterlab/commands.py
+++ b/jupyterlab/commands.py
@@ -561,6 +561,7 @@ def build_async(app_dir=None, name=None, version=None, logger=None, abort_callba
     npm = get_npm_name()
 
     # Make sure packages are installed.
+    yield run([npm, 'install', 'rxjs', 'backbone', 'jquery', '--save'], cwd=staging, logger=logger, abort_callback=abort_callback)
     yield run([npm, 'install', '--no-optional'], cwd=staging, logger=logger, abort_callback=abort_callback)
 
     # Build the app.
```

BokehJS had its own problems so lets ignore that for now. Essentially it appears that the dependencies of my extensions are not being installed. I can't work out what is going wrong. For now, just so that I can keep on working I can hack away at the jupyterlab repo to manually insert the missing packages. I'm not sure what else I can do...

**Comment by SimonBiggs** [comment]
The actual extension I am working on is the following:
https://github.com/SimonBiggs/jupyterlab-form

I have managed to get it up and running by forcing the installation of the following within `jupyter lab build`:

```diff
diff --git a/jupyterlab/commands.py b/jupyterlab/commands.py
index eb866ba..6fb877f 100644
--- a/jupyterlab/commands.py
+++ b/jupyterlab/commands.py
@@ -562,6 +562,12 @@ def build_async(app_dir=None, name=None, version=None, logger=None, abort_callba
 
     # Make sure packages are installed.
     yield run([npm, 'install', '--no-optional'], cwd=staging, logger=logger, abort_callback=abort_callback)
+    yield run([
+        npm, 'install', 'rxjs', 
+        '@angular/common', '@angular/core', 
+        '@angular/platform-browser', 'core-js', 'zone.js',
+        '@angular/platform-browser-dynamic', '@angular/compiler',
+        '--save'], cwd=staging, logger=logger, abort_callback=abort_callback)
 
     # Build the app.
     yield run([npm, 'run', 'build'], cwd=staging, logger=logger, abort_callback= abort_callback)
```

**Comment by blink1073** [comment]
@SimonBiggs, I was able to install using JupyterLab 0.27.1 with these steps.

```bash
git clone https://github.com/SimonBiggs/jupyterlab-form
cd jupyterlab-form
npm install
jupyter labextension install
jupyter lab
```
I was then able to open a form from the command palette.

What is `npm --version` for you?  I have `4.6.1`.

**Comment by SimonBiggs** [comment]
My npm version is 5.0.3. I'll install your versions of things and see how I
go.

**Comment by SimonBiggs** [comment]
Is jupyterlab 0.27.1 on pip?

**Comment by blink1073** [comment]
Ha, no it isn't.  I'm not sure how I ended up with that (I might have made a hand edit to the `_version.py` in my environment).  

I just tried from a freshly installed 0.27.0 and it works there as well with `npm 4.6.1`. 

 I then installed `npm 5.4.2`, and ran `jupyter lab clean && jupyter lab build && jupyter lab` and that works for me as well.

**Comment by SimonBiggs** [comment]
So I've just checked npm 4.6.1 and jupyterlab 0.27.0. It works! Okay, I'm going to reinstall 5.0.3 and see if that was the problem.

**Comment by blink1073** [comment]
It could be a combination of 5.x and installing without a `clean`.

**Comment by blink1073** [comment]
(As in, there is an existing `node_modules` folder that doesn't get properly updated)

**Comment by SimonBiggs** [comment]
So I installed 5.0.3, then made sure to link the extension. The act of linking the extension reproduced the errors once more. However, if I run clean, and then build, it works.

I think you're right. A clean is needed. Since 'link' doesn't do a clean, that means a link will cause every build to fail unless a clean is done first.

**Comment by SimonBiggs** [comment]
A stab in the dark guess, does it have anything to do with this:

`As of npm@5, `prepublish` scripts will run only for `npm publish`.`

**Comment by SimonBiggs** [comment]
So I'll stick with npm version 4.6.1 for now. And I can then go back to using the public release of jupyterlab. Thanks heaps for your help @blink1073 :)

Also I am exceptionally happy that this pull request is due for 0.28.0 :) brilliant work :) https://github.com/jupyterlab/jupyterlab/pull/3077

**Comment by blink1073** [comment]
We are thinking of switching to a pinned version of `yarn` that we provide rather than relying on a moving target of package managers.   Cheers!

**Comment by SimonBiggs** [comment]
@blink1073 that does sound like a necessary move. Thanks again for all your help :).

**Comment by SimonBiggs** [comment]
Work around for npm@5 was implemented and works in 0.28.0rc2

**Comment by towicode** [comment]
I'm still having the same module error as above.

jupyter lab --version
`0.32.1`
npm -v
`5.5.1`

1. cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts
2. npm install
3. npm run build
4. npm install --save-dev @types/backbone
5. npm install --save backbone

in index.ts
```import * as backbone from 'backbone';```

I've tried running npm run clean and jlpm cache clean.

**Comment by towicode** [comment]
yup it's in there although I did just notice something strange. My error is actually about jquery. Maybe there is something _strange_ going in my current node environment. Gonna try removing this version of node and retrying it.

Module not found: Error: Can't resolve 'jquery' in '/Users/todd/miniconda/envs/jupyterlab-ext/share/jupyter/lab/staging/node_modules/backbone'

**Comment by towicode** [comment]
I created a new conda environment with a fresh nodejs and it worked fine. Who knows what was happening

**Comment by ian-r-rose** [comment]
Hm, well, glad it is working. Chalk it up to npm gremlins, I guess.
