### ISSUE TITLE
Running session names are not displayed correctly due to `direction: rtl`

### ISSUE THREAD

**Issue by madx** [jupyterlab/jupyterlab#3084]
Hi,

We encountered a bug in the `Running sessions` display where notebooks starting with a digit and a dash would not have their names displayed correctly. Please see the screenshot below to see the bug:

![Display issue](http://drop.madx.me/2017-10-11-14:29:03.png)

The bug disappears when removing the `direction: rtl` CSS property that is set on `.jp-RunningSessions-itemLabel`.

Is there any reason why the property is set like this?

**Comment by blink1073** [comment]
It looks like I did that based on git blame, though I don't know why.

**Comment by blink1073** [comment]
Marking as help wanted if you'd like to submit a PR ;).

**Comment by madx** [comment]
Sure, that was some really low hanging fruit :D 

Maybe itemLabels where composed of other nodes that you wanted to reorder? (also, blame might have bitten you because you created the packages folder when the new architecture was made)

**Comment by blink1073** [comment]
Looking at the commit, it was intentional, but I suspect I meant to have `ltr` if anything.  We're looking at wider `ltr`/`rtl` support in #3046, so I think removing the rule for now is the right thing.

**Comment by madx** [comment]
Great 👍
