### ISSUE TITLE
Splash page bug on tall screens

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#3087]
On a tall-ish screen I noticed this splash page glitch:

![splash](https://user-images.githubusercontent.com/1839645/31460818-63651b6c-ae7c-11e7-8aa0-b8560585cd7b.gif)

I didn't see this on a shorter screen (maybe because the glitch occurs off-screen?)

**Comment by blink1073** [comment]
Hi @choldgraf, which browser/OS is this?

**Comment by choldgraf** [comment]
W10 on chrome - I tested with edge and it doesn't happen there.

**Comment by blink1073** [comment]
I don't have a tall display to use for replication...

**Comment by ian-r-rose** [comment]
I can reproduce this intermittently (maybe one out of ten refreshes?) on a tall display with Windows/Chrome.

**Comment by jasongrout** [comment]
I don't have a tall screen to reproduce this on. @choldgraf or anyone else here - is this still a problem with 3.0?

**Comment by choldgraf** [comment]
I don't see anything and haven't noticed in a while! I will close this and someone else can re-open if it surfaces again
