### ISSUE TITLE
Bundle a static version of the tutorial ?

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#309]
Right now the tutorial open an iframe to nbviewer; Though :
    - Nbviewer can be down
    - internet connection can be down/unavailable. 
    - Online version of tutorial and Local version of JupyterLab might get out of sync.

**Comment by willingc** [comment]
Good suggestion @Carreau.

**Comment by eskirk** [comment]
Seems like #311 has a decent solution to this

**Comment by jasongrout** [comment]
Is this done now, @ellisonbg, @roshancvp?

**Comment by jasongrout** [comment]
Oh, I see. The Help menu lists a Notebook basics tutorial, which pulls from nbviewer.

I think we should drastically edit the notebook basics tutorial from the menu - much of it isn't much help in JupyterLab.

**Comment by ellisonbg** [comment]
I think we should have a nice static tutorial within JupyterLab that is independent of nbviewer.

**Comment by ellisonbg** [comment]
I think the best way of hosting notebook based tutorials with with a lab-enabled binder. OK to close @Carreau in favor of that approach? There is a broader question of shipping lab with notebooks, but that is really a separate concern.
