### ISSUE TITLE
Cursors are not showing in CodeMirror

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#3097]
Observations:
- I can only reproduce using Chrome 61.0.3163.100 on macOS 0.13.  It happens when setting the zoom to 90%.  In the classic notebook, it also happens when the zoom is set to 80%.
- It does not happen when using Firefox and Safari on macOS, and or Chrome 61 on Windows 10.

**Comment by ian-r-rose** [comment]
Do you have a screenshot? I am still seeing them in 0.28rc1.

**Comment by blink1073** [comment]
![image](https://user-images.githubusercontent.com/2096628/31568325-4d95b38c-b039-11e7-9181-7587cb2c5d20.png)
![image](https://user-images.githubusercontent.com/2096628/31568333-5cbd0b26-b039-11e7-88d9-b93b3c83f8ec.png)

**Comment by SimonBiggs** [comment]
Hi @blink1073, I just wanted to let you know that cursors are working for me in rc2. Also I tested npm v 5 with mutliple rebuilds and no clean, I tested `jupyter lab --watch`, everything worked for me in rc2.

I did get an issue the first time I ran `jupyter lab --watch`. However, something I subsequently did made it go away... Not sure. The issue was in the browser window, instead of jupyter lab opening in the browser it said:
```
500 : JupyterLab Error

The error was:

JupyterLab assets not detected in "/home/simon/.pyenv/versions/3.5.3/share/jupyter/lab/staging/build"
```

**Comment by sw1sh** [comment]
It happens in Chrome for me and simply resizing browser window helps.

**Comment by blink1073** [comment]
@SimonBiggs, thanks for the checking those things.  We need to work on the UX of watch startup.  The WebPack build kills the `staging/build` folder and re-populates it, and then does the incremental builds.

@sw1sh, I can confirm that it happens in Chrome and not Firefox.  I also tried with JupyterLab 0.27 so it appears to be a regression in Chrome.  Resizing the window had no effect for me though.

**Comment by blink1073** [comment]
Oh, sorry, I misread.  Yes, changing the browser zoom does make the cursor appear.

**Comment by SimonBiggs** [comment]
I was doing my testing in chromium on Linux. No cursor issue for me.

**Comment by blink1073** [comment]
Updated the comment with observations.  Bumping to the 1.0 milestone.
