### ISSUE TITLE
Question regarding extension authoring best practices

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#3101]
Hi,

I am currently authoring the following extension:

https://github.com/SimonBiggs/jupyterlab-form

I wanted to be able to add an item to the jupyterlab launcher. But I wanted it to open two documents, the fileeditor, and my form widget. And I wanted it to open them side by side. Then finally I wanted to fill the editor with some default contents to get the user started.

I achieved these aims, but it didn't seem like I was doing it the right way. This is how I did it:

https://github.com/SimonBiggs/jupyterlab-form/blob/7b732216ae3afa1ab68409ef6fd820a1c0c1a6ac/src/index.ts#L99-L136

My question is, is there a standard way of achieving these aims?

Thank you :),
Simon

**Comment by blink1073** [comment]
Hi @SimonBiggs, ideally you would be able to do the following:

```typescript
app.shell.addToMainArea(editor, mode: 'split-left');
return editor.ready.then(() => {
  editor.value.text = defaultFormContents;
})
```

However, we need to update [addToMainArea](https://github.com/jupyterlab/jupyterlab/blob/20f3fe993107f1c81e045597d24298d494df41f9/packages/application/src/shell.ts#L358) to accept a `mode` override.  For now, you can update the editor handling and remove the `panel.layout.removeWidget(editor)` line since `DockPanel.addWidget` already handles re-parenting.

**Comment by SimonBiggs** [comment]
Thanks @blink1073 :). Also if you get a chance after the jupyterlab 0.28.0 release I would be keen if you could have a look at the extension. I'm keen for any feedback you might have.

**Comment by blink1073** [comment]
Aside from needing a launcher icon ;), I'd say it is coming along nicely.

**Comment by SimonBiggs** [comment]
Thanks Steven :). I feel like I'm starting to understand a bit more how
jupyterlab works. My next hurdle is trying to get my head around
"DocumentModel". So that I can actually save the results that are input
into the forms into a separate file. I was very tempted to just plug into
the kernel and save the file with python..... But then that won't make use
of all of the interactions within jupyterlab.

I'll get there :).
