### ISSUE TITLE
JupyterLab assets not detected in "/usr/share/jupyter/lab/static"

### ISSUE THREAD

**Issue by CptanPanic** [jupyterlab/jupyterlab#3105]
I just upgraded to latest version using pip, and now I cant use, and just get this error, whether I start with 'jupyter notebook' or 'jupyter lab'  This directory does not exist.  Any ideas?

**Comment by cyberwillis** [comment]
Hey Guys, I have a docker process that installs jupyterlab inside of it. It was working until the new release 0.28.0. Then this message as mentioned by CptainPanic.

![screenshot from 2017-10-17 09-57-09](https://user-images.githubusercontent.com/2855438/31663718-d2089af4-b321-11e7-8198-96bc0f9f2106.png)

**Comment by blink1073** [comment]
I suspect this might be relating to installing into the root python.  I just verified that it works with a conda environment on Ubuntu 16.04.  Looking into it now, but in the mean time you can run `jupyter lab --core-mode`.

**Comment by CptanPanic** [comment]
Yes I do install into root python.

**Comment by blink1073** [comment]
Confirmed, the files are sent to `/usr/local/share/jupyter/lab/static` but we are looking for them in `/usr/share/jupyter/lab/static`

**Comment by blink1073** [comment]
Released 0.28.1 and verified on Ubuntu 16.04.

**Comment by cyberwillis** [comment]
Thank you blink1073 , 

Earlier your suggested work  around "--core-mode" it worked nice and later I get the git repository after your fix. Thank you so much!

**Comment by CptanPanic** [comment]
@blink1073 when you say "Released 0.28.1", I do not see this release, and pip did not show anything.  When will this go live?

**Comment by blink1073** [comment]
JupyterLab 0.28.4 is the latest release: https://pypi.python.org/pypi/jupyterlab/0.28.4

**Comment by CptanPanic** [comment]
Thanks, I was looking at the gitlab releases.  Yes the new version fixes this issue.  Thanks.

**Comment by blink1073** [comment]
Cheers!

**Comment by poquirion** [comment]
Hello,
The bug is back in 0.28.13... I do not know when it came back, but reverted to 0.28,4 and it worked fined.

**Comment by blink1073** [comment]
Thanks!  I keep playing whack-a-mole with this.  Fix is in #3197.

**Comment by eric-burel** [comment]
Hi, I seem to have this issue in Jupyter lab 0.30.6. I am new to Python so the install process is still a bit blurry to me, but I simply use `pip2.7 install jupyterlab`, no sudo.
I seem to jave some trouble between python 3 and python 2... I'll be glad to help debugging if you provide me a few hint about how to do so :)

**Comment by blink1073** [comment]
Hi @eric-burel, these outputs would help:

```bash
uname -a
which python
which pip2.7
which jupyter
which jupyter-lab
```

**Comment by eric-burel** [comment]
Could not repro actually, now it works. What I have done:
- I installed jupyter lab vim extension
- It does not work on 0.27, so I upgraded jupyterlab (using pip2.7 I think)
- Had this issue
- I reinstalled the jupyter lab vim extension

Then all worked fine, so I am not sure what happened.

Here are the logs you asked: 
```
uname -a
Linux ericburel-ThinkPad-T450s 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
which python
/usr/local/miniconda3/bin/python
which jupyter
/usr/local/bin/jupyter
which jupyter-lab
/usr/local/bin/jupyter-lab
```
`which pip2.7` won't answer though it is installed. It is all a mess, I don't even know why I use the miniconda version...
I tend to think that properly installing python is the hardest part of the language, after that everything seems trivial ^^

**Comment by blink1073** [comment]
It looks like you have `/usr/local/miniconda3/bin/python` added to your `$PATH`, but `pip2.7` is using the system python.  If you want to use the `miniconda` version, I'd suggest using `pip` instead of `pip2.7`, and then `pip install jupyterlab`.  If you don't want to use the `miniconda` `python`, I'd suggest removing it from your `$PATH`.  Most likely there is an entry in `~/.bashrc` that is adding it.

**Comment by blink1073** [comment]
(and I agree, getting things set up is always the hardest part :wink:)
