### ISSUE TITLE
Feature request: Tab completion and Shift-Tab tooltip for Text editor

### ISSUE THREAD

**Issue by zuoxingdong** [jupyterlab/jupyterlab#3108]
Sometimes we like to write prototype code in Notebook cells and then move the well-tested code block to `.py` file, then we might need to change some code, it can be very helpful if the text editor opening `.py` file also supports tab completion and shift-tab tooltip.

**Comment by dhirschfeld** [comment]
Thanks @zuoxingdong. To minimise issue noise I'd recommend this be close as a dup as it helps focus efforts esp in regards to user demand for a particular feature.

**Comment by ian-r-rose** [comment]
Fixed by #5049.
