### ISSUE TITLE
docmanager:new-untitled not respecting compound extensions

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#3113]
Document registry allows for compound file extensions:

https://github.com/jupyterlab/jupyterlab/blob/7d9ac1cb06f2fcb41f5ed95964a87ab7779ef8ff/packages/docregistry/src/registry.ts#L998-L1002

For the jupyterlab extension I am writing I am using the compound extension "[name].form.md":
https://github.com/SimonBiggs/jupyterlab-form

If docmanager:new-untitled is called twice in succession, say by pressing the 'form' item within the launcher twice docmanager adds a "1", however the second file is named "[name].form1.md". This results in this second file no longer being associated as being a form document any longer.

**Comment by SimonBiggs** [comment]
The code which creates the new file in my extension is the following:
https://github.com/SimonBiggs/jupyterlab-form/blob/066a65f625436daf30a5298ac6ff32577b7d3a6b/src/index.ts#L128&L130

**Comment by blink1073** [comment]
It looks like this is a bug in notebook:

```python
In [7]: from notebook.services.contents.filemanager import FileContentsManager

In [8]: f = FileContentsManager()

In [9]: f.new_untitled(ext='.form.md')
Out[9]:
{'content': None,
 'created': datetime.datetime(2017, 10, 18, 12, 20, 40, 214130, tzinfo=<notebook._tz.tzUTC object at 0x1107bdb70>),
 'format': None,
 'last_modified': datetime.datetime(2017, 10, 18, 12, 20, 40, 214130, tzinfo=<notebook._tz.tzUTC object at 0x1107bdb70>),
 'mimetype': None,
 'name': 'untitled.form.md',
 'path': 'untitled.form.md',
 'type': 'file',
 'writable': True}

In [10]: f.new_untitled(ext='.form.md')
Out[10]:
{'content': None,
 'created': datetime.datetime(2017, 10, 18, 12, 20, 43, 197294, tzinfo=<notebook._tz.tzUTC object at 0x1107bdb70>),
 'format': None,
 'last_modified': datetime.datetime(2017, 10, 18, 12, 20, 43, 197294, tzinfo=<notebook._tz.tzUTC object at 0x1107bdb70>),
 'mimetype': None,
 'name': 'untitled.form1.md',
 'path': 'untitled.form1.md',
 'type': 'file',
 'writable': True}
```

**Comment by blink1073** [comment]
PR submitted: https://github.com/jupyter/notebook/pull/2949

**Comment by SimonBiggs** [comment]
Thanks @blink1073  :)

**Comment by SimonBiggs** [comment]
Also thanks for the organisation invite. Made me feel quite honoured. Thank you.

**Comment by blink1073** [comment]
Glad to have you!

**Comment by SimonBiggs** [comment]
Just wanted to let you know this is now fixed in the latest notebook release.

Thanks @blink1073  :) :)
