### ISSUE TITLE
JupyterLab assets not detected in "/usr/local/share/jupyter/lab/static"

### ISSUE THREAD

**Issue by dialvarezs** [jupyterlab/jupyterlab#3114]
Related to #3105.
In my case, I install jupyter (and jupyter-lab) in my user directory, not system-wide. It works using the flag --core-mode.

In ENV_JUPYTER_PATH I get this:
`['/usr/share/jupyter']`

If I use jupyter_path() I get this instead:
`['/home/darkxhunter/.local/share/jupyter',
 '/usr/local/share/jupyter',
 '/usr/share/jupyter']`

So **jupyter_path()[0]** would work for me (and I guess it should work in other cases too). Is there any reason for not using this?

Thanks!

**Comment by blink1073** [comment]
Hi @dialvarezs, thanks for the report.  The reason we don't want to default to `jupyter_path()[0]` is that it gives the user level path for conda and virtual environments.   #3115 catches the unique cases of a user-level install and a Posix system-level install, matching the locations of where the `data_files` are placed on installation.
