### ISSUE TITLE
Possibility to export the FACTORY constants

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#3119]
I'm wanting to reference an editor factory within my code. Instead of me hard writing in 'Editor' into my code like so:
https://github.com/SimonBiggs/jupyterlab-form/blob/master/src/index.ts#L61

Would it be a better idea if I could import the assigned factory name from somewhere on the factory itself? Just a thought I had, not sure if it's helpful.

**Comment by sccolbert** [comment]
If we exported those names, then you would import them in your code, which would create hard dependency on a *specific implementation* of an object. The whole point of the plugin system is that you don't know which plugin is implementing a specific type, only that *some* plugin has implemented it. This allows users to customize aspects of the system by using plugins which implement things differently. Importing information directly from other plugins would break that system.

**Comment by SimonBiggs** [comment]
Makes sense :).
