### ISSUE TITLE
Idea to boot a minimal jupyterlab via address bar parameters

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#3130]
Would it be a good idea to be able to open a minimal jupyterlab session with address bar parameters?

A use case, jupyterlab console. Within chrome I can use the following flag:
"path\to\chrome\chrome.exe" --app=http://localhost:8888/lab?widget=console

This would then boot up a standalone "app" with just the console, mimicking the current qtconsole. This can then be saved as a shortcut for quick standalone console access.

I'm creating a forms extension, it would be nice within our centre to be able to have links within our internal documentation which will link directory to just that particular extension widget.

**Comment by blink1073** [comment]
Yep, we're discussing what that would look like in https://github.com/jupyterlab/jupyterlab/issues/1075.

**Comment by SimonBiggs** [comment]
Awesome thanks. I tried searching for a relevant issue but didn't manage to find it. Thanks :).
