### ISSUE TITLE
in run in commands.py else instead of finally ? 

### ISSUE THREAD

**Issue by SylvainGuieu** [jupyterlab/jupyterlab#3134]
Line 85 in the definition of run in commands.py 

The exception statement finish by a 
    
    finally:
          proc.wait()

However the proc is not defined when the exception is raised . `finally` should be a `else` I guess ?

**Comment by SylvainGuieu** [comment]
Sorry, it was not clear. 

      proc = Popen(cmd, **kwargs)

     >>> FileNotFoundError: [Errno 2] No such file or directory: 'npm'

`cmd` looks like      

    cmd == ['npm', 'pack', 'jupyterlab_bokeh']

But I do not have `npm` on Mac OS-x 10.12.4 maybe it is just only from bokeh side.
But at least an explicit Error can be fixed.

**Comment by blink1073** [comment]
Hi @SylvainGuieu, which version of JupyterLab is this (`jupyter lab --version`).  That problem should be corrected in 0.28.

**Comment by SylvainGuieu** [comment]
Indeed it was the 0.27 version. 
The error now when doing 
    jupyter labextension install jupyterlab_bokeh
is indeed 
    FileNotFoundError: [Errno 2] No such file or directory: 'npm'

**Comment by blink1073** [comment]
Great, thanks for following up!
