### ISSUE TITLE
 JupyterLab assets not detected on master

### ISSUE THREAD

**Issue by ivanov** [jupyterlab/jupyterlab#3136]
I am following the direction in CONTRIBUTING.md to install jupyterlab to work on it.

```
    pip install -e . # will take a long time to build everything
    npm install
    npm run build:main
    jupyter serverextension enable --py jupyterlab
```

I am seeing essentially the same issue as #3123, but that was a problem with the released version (0.28.5), and I want to know how the instructions need to be updated so it works for the development cycle.

The server log error line is: 
```
[E 13:05:27.893 NotebookApp] JupyterLab assets not detected in "/Users/pi/.virtualenvs/jlab/share/jupyter/lab/static"
```
and trying to go to the website, the error users will see is:
```
500 : JupyterLab Error

The error was:

JupyterLab assets not detected in "/Users/pi/.virtualenvs/jlab/share/jupyter/lab/static"
```

(I have also tried `jupyter serverextension enable --py --sys-prefix jupyterlab` with no luck).

**Comment by ivanov** [comment]
This may be similar to #3114 that got fixed in #3115 - but there the `--user` flag was specified to the pip command, so maybe that's the issue?

**Comment by blink1073** [comment]
`npm run build:main` builds the dev version of the JupyterLab (`jupyter lab --dev-mode`).  We need to update the instructions to be more clear about what is going on here.  Short term answer is you can either run in `--dev-mode` or `jupyter lab build` to populate your virtualenv app directory (`jupyter lab`).

**Comment by jwhendy** [comment]
For what it's worth, I have things installed via `pip install --user`, and while `--dev-mode` let me open `jupyterlab` again, I was having various errors with some of the `javascript` plotting libraries out there (`bokeh`, 'nvd3`, 'plotly`).

I tried the other suggestion above, which was to do `jupyter lab build --app-dir=~/.local/share/jupyter/lab` and from then on launching with `jupyter lab --app-dir=`~/.local/share/jupyter/lab`. This resolved these issues for me.

I tried `--dev-mode --app-dir=foo`, but the issues persisted. Adding this comment for others in the event it's helpful to differentiate the two methods suggested above. I may have done one incorrectly, but be sure to try both if you're having issues!

**Comment by blink1073** [comment]
Thanks for the report, @jwhendy, this should be fixed by upgrading: `pip install jupyterlab==0.28.13`.

**Comment by jwhendy** [comment]
Thanks for the quick work! For clarification, "fixed" means:

- no longer need `--dev-mode` or `--core-mode`?
- don't need to do `jupyter lab build` anymore?
- my local `app-dir` will be picked up automatically
- multiple of the above? :)

Just looking to understand what the process should be to maintain `jupyterlab` and extensions on my system moving forward (which I do via `pip install --user`). Thanks!

**Comment by blink1073** [comment]
- Correct, no extra flags needed
- No build required unless adding or removing extensions
- If you install as `--user` then the app dir will be picked up as `~/.local/share/jupyter/lab` in your case, and any python package that ships a lab extension would also end up there if installed as `--user`.  You still have to `jupyter lab build` after installing the python package to rebuild the front end assets

**Comment by jwhendy** [comment]
Perfecto -- thanks! I just updated and all looks good to me, no flags required. The `jupyter lab build` thing was completely new to me, so I wasn't sure on why I needed it at all. Doing that fixed a mess of issues I was having with various `js` based plotting libraries though. I'll continue to do that in the future (and added looking into that to my mental todo list).
