### ISSUE TITLE
Split cell keybinding quicksand (C-_, then Cmd-Z)

### ISSUE THREAD

**Issue by histed** [jupyterlab/jupyterlab#3143]
The normal Emacs keybinding for Undo is 'C-_'   -- the same as the Split Cell keybinding.  So I often make a mistake, hit C-_ undo without thinking, and then the cell splits.  Then my instinct is often to hit Cmd-Z, the usual browser Undo, which deletes all the text in the newly split cell without a way to get it back.

Perhaps possible to change the split cell keybinding, or see if the Cmd-Z behavior after split is unexpected?

(This is on Mac, not sure how Windows behaves w/ Ctrl-Z)

**Comment by vidartf** [comment]
> the usual browser Undo, which deletes all the text in the newly split cell without a way to get it back.

Note: The shortcuts for "redo" are (according to codemirror manual): Ctrl-Y (PC), Shift-Cmd-Z (Mac), Cmd-Y (Mac). This should at least help you get back any lost text.

**Comment by sccolbert** [comment]
We'll be adding the ability for the user to customize their own keybindings, so this should be a non-issue in the future.

**Comment by saulshanabrook** [comment]
You should be able to change this now in the [Keyboard Shortcuts editor under settings]https://jupyterlab.readthedocs.io/en/stable/user/interface.html#keyboard-shortcuts).

Feel free to reopen if you aren't able to customize to your liking.
