### ISSUE TITLE
Local Lab Extension Workflow

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#3145]
A couple of things I have seen in practice with using local extensions:

- Forgetting to `npm install` before `jupyter labextension install .`.  
- Forgetting to `npm run build` before `jupyter labextension install .`.  This one can result in the cryptic error of the form:

```javascript
WARNING in ./build/index.out.js
Module not found: Error: Can't resolve '@jupyterlab/github/' in '/usr/share/jupyter/lab/staging/build'
 @ ./build/index.out.js 639:25-55
```

We should run `npm install` in a local folder if it doesn't have a `node_modules`, and encourage the use of a `prepack` script.  The `prepack` script is run on `npm pack` and `yarn pack`.  

I will add the `prepack` script to the cookie cutter.  The command is also run on `npm publish` and `yarn publish`, so it can be used instead of the `prepublish`/`prepare`/`prepublishOnly` scripts if appropriate.

cc @ian-r-rose @jasongrout

**Comment by ian-r-rose** [comment]
Makes sense to me. I have also run into this, and even though I know the reason it can take a beat to remember. Thanks!
