### ISSUE TITLE
Cursor disappeared while typing and did not reappear.

### ISSUE THREAD

**Issue by dswalter** [jupyterlab/jupyterlab#3147]
When typing in a cell, I've noticed the vertical bar typing cursor disappears entirely (as thought it were blinking and happened to remain stuck in the 'blink off' position. It remains off even if I move to a different notebook.

Discovered while using JupyterLab 0.27.0,
Chrome Version 61.0.3163.100 (Official Build) (64-bit) on a Macbook Pro running MacOS 10.12.6. 

It turns out l miss that cursor.

**Comment by blink1073** [comment]
Hi @dswalter, by chance are you zoomed in on the page?  I believe this is the same issue as #3097.

**Comment by dswalter** [comment]
Indeed. I'm closing this.
