### ISSUE TITLE
Unable to display from within button on_click function

### ISSUE THREAD

**Issue by scubahub** [jupyterlab/jupyterlab#3151]
Hi,

I recently started working with jupyter and decided to jump to jupyter lab.  I am seeing a big difference in behavior regarding output (IPython output) from within an ipywidgets button's on_click function.

Here is a snippet from the jupyter notebook that works as expected:
```
master_selection_widget = widgets.SelectMultiple(
    options=Salt.available_masters(),  # just returns a list of host names
    description='Salt Master(s)',
    value=Salt.available_masters()[0],
    disabled=False
)
def select_masters(selection):
    return selection
salt_master_selector = interactive(select_masters, selection=master_selection_widget)

run_widget = widgets.Button(
    description='run',
    tooltip='check for nonresponsive minions'
)

def on_run_widget_clicked(b):
    # in case button is pressed multiple times, clear output and redisplay widgets
    clear_output()
    display(salt_master_selector)
    display(run_widget)
    # change button text to running
    b.description = "running"
    try:
        import json
        global result
        result = {}
        for master in salt_master_selector.result:
            ssh = SSH(master)
            out, err, retcode = ssh.execute('salt-run manage.down --out=json -l quiet')
            display("out=" + out)
            print("err=",err)
            print("retcode=",retcode)
            result[master] = json.loads(out)
        display(result)
    except Exception as ex:
        display(ex)
    # reset button description
    b.description = "run"
run_widget.on_click(on_run_widget_clicked)

display(salt_master_selector)
display(run_widget)
```
In the jupyter notebook executing the cell displays the widgets.  Clicking on the "run" button executes the call back which results in lots of output (from the print and display calls in `on_run_widget_clicked`).

The same code in jupyter lab appears to work fine from a python level, but no output is produced from the print and display calls in `on_run_widget_clicked`.  I changed the code a bit to put all the data in global variables and, in a new input cell, I can print them so the code is executing and getting the results as expected, it's just the display/print functions do not produce output from within the `on_run_widget_clicked` function.

**Comment by scubahub** [comment]
Here is a simple and complete example

In [1]:
```
from IPython import display
from ipywidgets import widgets

text = widgets.Text()
display.display(text)

def on_text_submit(textWidget):
    print("submitted: " + textWidget.value)

def on_text_change(change):
    print("change: " + change['new'])

text.on_submit(on_text_submit)
text.observe(on_text_change, 'value')
```

In jupyter notebook if you type 'asdf' and hit return the output shows
```
change: a
change: as
change: asd
change: asdf
submitted: asdf
```

In jupyter lab if you type the same there is no output at all.

**Comment by blink1073** [comment]
@jasongrout, I'm seeing this as well.  Is it a known limitation?

**Comment by jasongrout** [comment]
Yes, this is a known thing (https://github.com/jupyterlab/jupyterlab/issues/1254). We kludged a backwards-compatibility workaround in the classic notebook, but we didn't in jupyterlab. Part of the reason is that it is much harder to write kludgy workarounds in jlab :).

Essentially, the technical issue is that a widget comm message from the browser to the client would need to set the output callback to append output to the current output area - but IIRC it's hard from a mime renderer to get a handle on the output area that contains it.

A cleaner (but more tedious) way to do things is to explicitly create an Output widget, and capture output and send it there:

```python
from IPython import display
from ipywidgets import widgets

text = widgets.Text()
display.display(text)

out = widgets.Output()

def on_text_submit(textWidget):
    with out:
        print("submitted: " + textWidget.value)

def on_text_change(change):
    with out:
        print("change: " + change['new'])

text.on_submit(on_text_submit)
text.observe(on_text_change, 'value')
```
and then display `out` in another cell, or wherever you want.

Another way to cleanly do this is to implement the log of iopub messages that haven't been claimed, as noted in https://github.com/jupyterlab/jupyterlab/issues/1254.

**Comment by blink1073** [comment]
Okay, closing this one in favor of #1254.  Thanks for the report, @scubahub!
