### ISSUE TITLE
%run in nested notebooks always evaluated based on directory of including notebook

### ISSUE THREAD

**Issue by scubahub** [jupyterlab/jupyterlab#3160]
Im new (this week) to the jupyter(lab) ecosystem so apologies if this should be filed against IPython instead...

Im experimenting with notebooks where most of the code lives in other files so the main notebook primarily has markdown and output with short code snippets based on imports and finding issues with nested notebooks.  As a simple example here is a directory structure:

```
.
|-- main.ipynb  # does a %run ./lib/foo.py
`-- lib
    |-- __init__.py
    |-- foo.py  # does an import utils.bar
    `-- utils
        |-- __init__.py
        `-- bar.py
```

If main.ipynb does a `%run ./lib/foo.py` and foo.py does `import utils.bar` there are no issues.  However if we change `foo.py` to a notebook `foo.ipynb` (and change foo.ipynb do do `%run ./utils/bar.py`) to add some documentation and examples, things break down.

```
.
|-- main.ipynb  # does a %run ./lib/foo.py
`-- lib
    |-- __init__.py
    |-- foo.ipynb  # does a %run ./utils/bar.py
    `-- utils
        |-- __init__.py
        `-- bar.py
```

The foo notebook works just fine in the editor, you can execute all the cells without error.  But the main notebook does not work because when main does a `%run` of lib/foo, the `%run` inside foo is executed based on the directory of main notebook not the directory the foo notebook lives in.  Changing the foo notebook to use `%run ./lib/utils/bar.py` fixes the main notebook, but now the foo notebook itself does not work in the editor.  Catch 22.

**Comment by scubahub** [comment]
FYI, same behavior in classic jupyter notebook.

**Comment by blink1073** [comment]
Hi @scubahub, yes, this behavior is governed by IPython, do you mind [opening the issue there](https://github.com/ipython/ipython/issues/new)?

**Comment by scubahub** [comment]
Done.  https://github.com/ipython/ipython/issues/10884

**Comment by blink1073** [comment]
:+1:
