### ISSUE TITLE
get list of all variables from active notebook(s)

### ISSUE THREAD

**Issue by sirajpresswala** [jupyterlab/jupyterlab#3161]
is it possible to get a list of all active variables in the notebook? this functionality can allow better memory management by discarding/reassigning variables that are no longer in use.

**Comment by rowanc1** [comment]
In talking with some of my PhD colleagues, they also found that this was a major feature that they could not initially do without in making the switch from Matlab to Python (and Jupyter notebooks). Being able to [visualize the current workspace](https://www.mathworks.com/help/matlab/ref/property_inspector_surface1.png) in the notebook was really important. It seems as this would be better as a plug in to Jupyter Lab?

It is possible in IPython to just call `whos`:

https://stackoverflow.com/a/634581

**Comment by jasongrout** [comment]
Thanks for your comments! We're tracking this at https://github.com/jupyterlab/jupyterlab/issues/443. Please join the discussion there.

**Comment by cyberwillis** [comment]
Mean while some can use this one

[varInspector](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/varInspector)
