### ISSUE TITLE
Single quotes not rendered properly.

### ISSUE THREAD

**Issue by scubahub** [jupyterlab/jupyterlab#3169]
In a markdown cell there appears to be no way to get a single quote to render properly.  For example, entering ```it\'s``` renders showing the escaping backslash.

**Comment by scubahub** [comment]
surrounding the single quote with tripple back ticks does the trick, not sure if that should be required based on the markdown spec.

**Comment by blink1073** [comment]
Hi @scubahub, what is `jupyter lab --version`?  Also, which OS and browser?  I just tried with `0.28.12` on macOS 10.13 and Chrome 62.0:

![image](https://user-images.githubusercontent.com/2096628/32350813-6c9f70dc-bfe9-11e7-84ce-aba4a66e5dc9.png)

**Comment by scubahub** [comment]
```
jupyter lab --version
0.28.8
```
Mac OS 10.12.6
Chrome 61.0.3163.100

And I think im being stupid, trying to recreate it I think I was initially typing in a bash input, not a markdown input.  Works fine.
