### ISSUE TITLE
Save JuptyerLab session and re-use in Binder

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3176]
Hi all, mybinder now supports JupyterLab. It would be nice if it were possible to arrange JupyterLab in a particular layout, and then save that session and put it somewhere that binder can see it. Binder and repo2docker now support a `postBuild` bash script that could install the session in the appropriate place. Questions:

* Is the jupyterlab session store on disk anywhere?
* How can that state be saved/exported and then re-installed?

This would allow more complex opening states for lab+binder than just an open file, and might not require any changes.

@yuvipanda @willingc @minrk @choldgraf @blink1073

**Comment by blink1073** [comment]
The state is JSON, but currently only stored in the browser. We just need a server backed data connector.

**Comment by ian-r-rose** [comment]
This is now possible with workspaces. Keeping it open for now since the CLI for managing workspaces still needs some work (#5166), but we should be able to close this in a matter of days.

**Comment by ian-r-rose** [comment]
This is now doable with a bit of work. See https://github.com/dask/dask-examples/blob/d1a374bbe093d4145b9f8fe16582b6a8167ad764/binder/start#L1-L12 for an example that uses a pre-seeded workspace for a binder session.
