### ISSUE TITLE
"Help -> Python Reference" documentation should point to notebook's python version

### ISSUE THREAD

**Issue by achimgaedke** [jupyterlab/jupyterlab#3177]
I'm running condo-forge's jupyterlab distribution on python 3.6. When I select the python reference, it points to python 3.5.2 - great to have the quick access!

Would it be easily possible to determine the python version of the Notebook (if a python notebook or the server) and select the documentation version accordingly?

This might even happen on the npm compile time, using the default python version of the Jupiter server.

Thanks.

**Comment by blink1073** [comment]
Hi @achimgaedke, we could pass the version info to the front end from the server using [page config](https://github.com/jupyterlab/jupyterlab/blob/ab3494204e1c9ed36c2e6cc664aad7983d05b324/jupyterlab/extension.py#L77) and use it in the [help extension](https://github.com/jupyterlab/jupyterlab/blob/ab3494204e1c9ed36c2e6cc664aad7983d05b324/packages/help-extension/src/index.ts#L97).

**Comment by AbdealiJK** [comment]
Wy not just point to the latest documentation at https://docs.python.org/3/
similar to how pandas, numpy, matplotlib's latest version documentation are shown.

**Comment by achimgaedke** [comment]
Hey @blink1073 - sounds great.

Hey @AbdealiJK - yeah, that would be an improvement for me. But depending on the user, others might get 3.6 docs while using 3.5. - Looking at conda-forge and other distributions the versions 3.5 and 3.6 are on the same page/level of visibility; hence there is still a significant portion of 3.5 projects out there.

And sorry, don't have the time/knowledge to do it myself.
