### ISSUE TITLE
Allow for toolbar cusomization

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#3178]
Continuation from https://github.com/jupyter/notebook/pull/2965#issuecomment-341312687

It would be nice if users could customize the notebook toolbar from within JupyterLab. Ideally, users would be able to drag actions in/out of the toolbar (e.g. macOS-style toolbar customization). A much more achievable alternative would be a menu item/command that would open an editor with the toolbar settings JSON and allow users to edit it. This is a UX pattern used in Atom editor (and Sublime Text and others) that's not perfect but it's easy and it works.

**Comment by crowdy** [comment]
I need this badly. I am doing this now.
```
$('li.p-TabBar-tab').eq(0).hide();
```

**Comment by gnestor** [comment]
@crowdy That code snippet won't work in JupyterLab, only the classic notebook. 

In JupyterLab, it's possible for an extension to add and remove items from the toolbar. Here's where JupyterLab create the default notebook toolbar: https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook/src/default-toolbar.ts#L190-L209

**Comment by oxinabox** [comment]
In particular this is the subject of a extension making tutorial/example

http://jupyterlab.readthedocs.io/en/stable/developer/notebook.html#how-to-extend-the-notebook-plugin

Still would be nice to have it easier via setting edittor

**Comment by krassowski** [comment]
This was implemented in https://github.com/jupyterlab/jupyterlab/pull/10469 which was backported to JupyterLab 3.3 (and this issue was not previously closed because of duplicate issue  https://github.com/jupyterlab/jupyterlab/issues/10419).
