### ISSUE TITLE
Table alignment in Markdown cells is ignored.

### ISSUE THREAD

**Issue by scubahub** [jupyterlab/jupyterlab#3180]
Table column alignment directives (colons) are ignored.  For example, the following renders with every column right aligned.

```
left | center | right
:--- | :---| | ---:
a | b | c
1 | 2 | 3
```

**Comment by blink1073** [comment]
I see the same behavior in the classic notebook as well.  The DOM nodes created by marked don't have any style or class applied.  We are setting the `gfm` and `table` [properties](https://github.com/jupyterlab/jupyterlab/blob/ab3494204e1c9ed36c2e6cc664aad7983d05b324/packages/rendermime/src/renderers.ts#L782), so I'm not sure why that is.

**Comment by AbdealiJK** [comment]
This seems to be a reproducible bug with `marked`:
```javascript
var marked = require('marked');
marked.setOptions({
    renderer: new marked.Renderer(),
    gfm: true,
    tables: true
});

console.log(marked('I am using __markdown__.'));
console.log(marked('left | center | right\n'
+ ':--- | :---| | ---:\n'
+ 'a | b | c\n'
+ '1 | 2 | 3'))
```
Gives:
```html
<p>I am using <strong>markdown</strong>.</p>

<table>
<thead>
<tr>
<th style="text-align:left">left</th>
<th style="text-align:left">center</th>
<th>right</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">a</td>
<td style="text-align:left">b</td>
<td>c</td>
</tr>
<tr>
<td style="text-align:left">1</td>
<td style="text-align:left">2</td>
<td>3</td>
</tr>
</tbody>
</table>
```

**Comment by blink1073** [comment]
Great catch @AbdealiJK!   This is blocked by https://github.com/jupyterlab/jupyterlab/issues/1812.

**Comment by jasongrout** [comment]
This may work already in master now that #1812 is fixed.
