### ISSUE TITLE
Terminal width incorrect after page refresh?

### ISSUE THREAD

**Issue by dillonplunkett** [jupyterlab/jupyterlab#3181]
After a page refresh, terminals appears to be registered as about a third wider than they are (e.g., `tput cols` returns 104 when a terminal is 80 columns wide). 

Moving, resizing, or refreshing a terminal doesn't correct the issue, but closing it and reopening it from the Running tab does. 

Animation below (current Chrome, but seen with current Firefox as well). 

![term_width](https://user-images.githubusercontent.com/5193326/32339258-9ec7a8a2-bfcd-11e7-9f0e-ba7890fd050d.gif)

**Comment by blink1073** [comment]
Hi @dillonplunkett, I confirmed the bug, thanks!
