### ISSUE TITLE
Extremely slow to connect to JupyterLab

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#3187]
It's extremely slowly to connect to a JupyterLab server (compared to classic notebook server). I suggest some effort into tuning the performance of JupyterLab.

**Comment by blink1073** [comment]
Agreed that we can do better on the loading.  We plan to split the bundle into chunks and minify it.

**Comment by ellisonbg** [comment]
@blink1073 do you think we should still try to get this into the beta. @jasongrout and I wonder if this can wait until post-beta.

**Comment by blink1073** [comment]
I have a few things I'd like to address on this front for beta.

**Comment by ellisonbg** [comment]
Sounds good.
