### ISSUE TITLE
File browser tasks

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#319]
The following are tasks related to the file browser plugin tasks we aim to complete by SciPy 2016.
- [x] Drag/drop styling ( @rnetro )
- [x] File browser selected item border radius to 0-1px ( @rnetro )
- [ ] Add file browser menu ( @rnetro ) [Needs description: @ellisonbg]
- [x] 13px UI font ( @rnetro )

**Comment by jasongrout** [comment]
What's the status on this?

**Comment by jasongrout** [comment]
@rnetro - could you comment on each of the items? (done, won't fix, etc.?)

**Comment by blink1073** [comment]
Closing, as we have a functioning file browser menu.
