### ISSUE TITLE
Absorb the Jupyter Widgets manager

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#3196]
Now that `@jupyter-widgets/base` exports the token to be used by third party widgets, the `@jupyter-widgets/jupyterlab-manager` is largely independent of the `@jupyter-widgets` org.

I propose that we bring it in to the core repository.  The barrier to inclusion is that the bundle size increases by `~1MB`.  However, this appears to be largely from the import of `@jupyter-widgets/controls` which includes `jquery-ui`.  If we lazily load `jupyter-widgets/controls` in `renderModel`, then we only ever incur that cost when specifically using `ipywidgets`.

A short term way to accomplish this is to use the `require.ensure` syntax supported by `Webpack` to lazily load the module, an approach demonstrated [here](https://gist.github.com/blink1073/fa5385530e7199b5485c1ee95344406d) using `ipyleaflet`.  

A longer term approach is to use ES6 module syntax in our modules with ES5 syntax otherwise, an approach demonstrated [here](https://gist.github.com/blink1073/590367109779d537d781f9d739002836).
The TypeScript compiler is more efficient than Babel at transpiling to ES5.
This allows us to use [dynamic imports](tc39/proposal-dynamic-import) (supported by Webpack 2+) and enable
[tree shaking](https://webpack.js.org/guides/tree-shaking/) in WebPack.

We could us the `import()` syntax in our `vega2` renderer as well, and recommend that approach to others.

**Comment by blink1073** [comment]
Note that `coreutls` and `services` would be distributed with `commonjs` module syntax because they are intended to be used from `node`.

**Comment by blink1073** [comment]
cc @ellisonbg

**Comment by jasongrout** [comment]
We bundle the controls in with the manager, but that's not absolutely necessary, and the controls will change at a far faster rate than the manager and base package. Perhaps in the short term we can:

(a) move the manager over to jlab, but don't bundle the controls in by default
(b) distribute the controls as a separate 3rd party package. Perhaps we could put the jlab controls package in the widgetsnbextension package, which is already pulled in by default by ipywidgets.

**Comment by blink1073** [comment]
That would mean that the default widgets wouldn't be available without a build.

**Comment by jasongrout** [comment]
Right - it would mean that you'd still have to install something to see the default widgets.

**Comment by jasongrout** [comment]
> default widgets wouldn't be available without a build.

Oh, that means that the user needs node installed. Hmm... For me, that swings the pendulum back towards including controls.

**Comment by blink1073** [comment]
Ayup.

**Comment by jasongrout** [comment]
> A longer term approach is to use ES6 module syntax in our modules with ES5 syntax otherwise, an approach demonstrated here.

Any reason not to use this approach right now?

**Comment by blink1073** [comment]
I was waiting to here from you and Brian on that subject ;).

**Comment by blink1073** [comment]
The code would still be consumable in ES6 browsers, as well as using tools like WebPack, Rollup, etc.

**Comment by jasongrout** [comment]
I'm working on a PR right now to enable modules to be lazily loaded in jlab. I'll go ahead and use the es6 syntax in the jlab plugin.

**Comment by blink1073** [comment]
Note that the [metapackage](https://github.com/jupyterlab/jupyterlab/blob/f7a13f6a05aafca1ecaa4e41babc57b6ec385a52/packages/metapackage/tsconfig.json) will need the same config as the [gist](https://gist.github.com/blink1073/590367109779d537d781f9d739002836).

**Comment by blink1073** [comment]
Also note that WebPack uses "magic comments" to designate the split points:  https://webpack.js.org/guides/code-splitting/#dynamic-imports.

**Comment by blink1073** [comment]
(Which are safely ignored by other tools).

**Comment by jasongrout** [comment]
> I was waiting to hear from you and Brian on that subject ;).

The relevant point being: jupyterlab modules are then no longer just commonjs modules, but may also be esnext modules? (Shifting from up to now, where we've said jupyterlab modules are commonjs modules?)

@ellisonbg - thoughts?

**Comment by blink1073** [comment]
We could be conservative and only use ES6 modules when we need async imports but we would lose tree shaking and might as well use require.ensure at that point.

**Comment by jasongrout** [comment]
Can we have tree shaking with both commonjs modules and es6 modules? I think we probably can't insist on all modules (including 3rd party extensions) being es6.

**Comment by jasongrout** [comment]
I think with my PRs to ipywidgets over the last day, we are in a position where we could move the jupyterlab manager into jupyterlab. The lazy loading saves around 280K which can be loaded later when the controls are used.

**Comment by blink1073** [comment]
Below is snapshot of our bundle including `jupyterlab-manager` using [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer).  `lodash` and `jquery` are part of `@jupyter-widgets/base`.  `jquery` is also used by the `output` widget.  We could lazily load `base` and `output`, but only if there were a separate module for the base version, similar to the controls version.  Also: crazy how big the `vim` mode for `CodeMirror` is.

<img width="868" alt="screen shot 2017-11-07 at 3 56 23 am" src="https://user-images.githubusercontent.com/2096628/32488073-133f47b6-c371-11e7-80d7-40393afa4df0.png">

**Comment by blink1073** [comment]
It looks like we'll save ~800Kb when we lazily load vega.  Switching to production React in our shipped bundle and using the uglify plugin will also help, as well as splitting out a vendor bundle.

**Comment by jasongrout** [comment]
We only use 3 functions from lodash - so we can either just include those three functions and their dependencies directly (https://github.com/jupyter-widgets/ipywidgets/blob/952f0266dbc28d1caef43aaa8d9d2ba0eb755acc/packages/base/src/utils.ts#L4), or I think there is a way to just import just those three functions from lodash. I'll look into it.

I'll also split out the versions into a separate file so we can lazily load the base package.

Thoughts on whether we should put that version information into package.json? It seems like a natural place for it, and makes it easier to import it without reaching deep into the package. On the other hand, it feels a little like polluting the package.json file. However, I'm inclined to just make it part of package.json.

**Comment by ian-r-rose** [comment]
![image](https://user-images.githubusercontent.com/5728311/32501502-cc0e44aa-c39d-11e7-9903-1ca87974edb8.png)

**Comment by jasongrout** [comment]
> Also: crazy how big the vim mode for CodeMirror is.

The irony is how big the emacs mode is in comparison!

**Comment by jasongrout** [comment]
> I'll also split out the versions into a separate file so we can lazily load the base package.

Thinking more about this - the notebook instantiates the widget manager eagerly every time a notebook is loaded, from the base package, so I don't know that lazily loading the base package is going to help a ton (unless lots of people are using jlab without using notebooks). We could push the laziness further by having a comm target that lazily instantiates the widget manager - the question is it worth it.

However, we can definitely cut most of lodash out.

**Comment by blink1073** [comment]
I suppose `jquery` was going to show up at some point...

**Comment by jasongrout** [comment]
yeah, sorry, we need that for backwards compatibility with backbone. I got rid of it everywhere else, though.

**Comment by jasongrout** [comment]
Much better after https://github.com/jupyter-widgets/ipywidgets/pull/1805

<img width="1336" alt="screen shot 2017-11-07 at 3 36 58 pm" src="https://user-images.githubusercontent.com/192614/32523765-9c4ea050-c3d1-11e7-8f30-a5121e707170.png">

**Comment by jasongrout** [comment]
> yeah, sorry, we need that for backwards compatibility with backbone.

If/when we switch away from backbone, we'll get rid of the last traces of jquery.

**Comment by jasongrout** [comment]
Any other thoughts before attempting a move into jlab core?

**Comment by blink1073** [comment]
I think we're good!

**Comment by jasongrout** [comment]
I may keep another plugin in the ipywidgets source tree that installs the current version of controls, since we can overwrite the core widgets in the registry. That way if someone *does* want the latest and greatest beyond what is in core jlab, they can still install the plugin.

**Comment by blink1073** [comment]
Yeah that sounds reasonable.

**Comment by ellisonbg** [comment]
Talked with @jasongrout about moving this to 1.0.

**Comment by blink1073** [comment]
Closing this since with the extension system refactor it will be much easier to add widgets to a deployment.
