### ISSUE TITLE
Recovering an accidently deleted ipython notebook

### ISSUE THREAD

**Issue by alexandrehuat** [jupyterlab/jupyterlab#3205]
Hello,
I accidently deleted a big, important, ipython notebook via the jupyter lab interface. How can I recover it? I didn't find such function in jupyter lab. I'm using Safari on MacOS.
It's not in the trash. It's not in the `.ipynb_checkpoints` dir. I've seen solutions using the cache, for Chromium and jupyter notebook only.
Thank you for your help.

**Comment by blink1073** [comment]
I'm sorry to hear that @alexandrehuat.  I don't believe there is a way to recover that file.  The next release of the Notebook server will send files to the system trash by default https://github.com/jupyter/notebook/pull/1968.

**Comment by alexandrehuat** [comment]
Okay.
Thanks. We surely need such an update.

**Comment by fairf4x** [comment]
When I right click on **the file which I want to delete** in the file list and select "_remove_" in the drop down menu, jupyter lab deletes **currently selected** file. I think that the right click should **select the clicked file**. This should be an easy solution which would prevent many accidents like this.

**Comment by blink1073** [comment]
Hi @fairf4x, that behavior was fixed in #3234 and will be in the next release.

**Comment by kidanam** [comment]
hello is this problem fixed, can we recover accidentally deleted files?

**Comment by mmcguffi** [comment]
> hello is this problem fixed, can we recover accidentally deleted files?

yes, it can be found in the trash.

**Comment by itmaster90** [comment]
Look at your project folder you might find the checkpoint ipynb file : " .~FileName.ipynb ".
Remove .~ and you have your file again. This happened to me when I ran a big fat data that froze my OS.

**Comment by skhub12** [comment]
It is found in recycle bin. And can be recovered.
