### ISSUE TITLE
jupyterlab release 0.28.15 GUI issue

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jupyterlab/jupyterlab#3213]
I've just installed the latest jupyterlab release 0.28.15 on my OSX High Sierra with 
Not sure where the problem is, but the browser appearance has changed.

For example, now the cells border doesn't show up correctly etc.

Maybe something went wrong during the npm re-build?

I tried to re-install jupyterlab (and rebuild) but I got same error.

Do you have any suggestion on things to try?

**Comment by blink1073** [comment]
Hi @smartinsightsfromdata, I think this should be cleared up now by running `jupyter lab build`.  I had made new patch releases of our theme packages that should have been minor releases.

**Comment by smartinsightsfromdata** [comment]
It works!

**Comment by blink1073** [comment]
Packaging is hard...  :smile:

**Comment by smartinsightsfromdata** [comment]
You are doing a super job!

I've a minor issue but i'll create another issue.
