### ISSUE TITLE
Conflicting Dependencies for @jupyter-widgets/jupyterlab-manager@0.28.0

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jupyterlab/jupyterlab#3215]
I've just installed jupyterlab 0.29 and everything looks fine, but I get the error message below at launch time:
```
[...]
[I 18:35:10.059 LabApp] Accepting one-time-token-authenticated connection from ::1

"@jupyter-widgets/jupyterlab-manager@0.28.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.12.0-0 <0.13.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/application
>=0.12.0-0 <0.13.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/notebook
>=0.12.0-0 <0.13.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/rendermime
```
Is it expected?

**Comment by blink1073** [comment]
Yes, Jason is working on a new compatible release of the `jupyterlab-manager`.

**Comment by scottdraves** [comment]
I am getting an error like this again, but at install time:
```
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
> /usr/local/bin/npm pack @jupyter-widgets/jupyterlab-manager
jupyter-widgets-jupyterlab-manager-0.32.3.tgz

"@jupyter-widgets/jupyterlab-manager@0.32.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab                        Extension            Package
>=0.13.1-0 <0.14.0-0              >=0.14.1-0 <0.15.0-0 @jupyterlab/application
>=0.13.0-0 <0.14.0-0              >=1.0.1-0 <2.0.0-0   @jupyterlab/coreutils
>=0.13.0-0 <0.14.0-0              >=0.14.1-0 <0.15.0-0 @jupyterlab/notebook
>=0.13.0-0 <0.14.0-0              >=0.14.1-0 <0.15.0-0 @jupyterlab/rendermime
>=0.4.3-0 <0.5.0-0                >=1.0.1-0 <2.0.0-0   @jupyterlab/rendermime-interfaces
>=0.52.0-0 <0.53.0-0              >=1.0.1-0 <2.0.0-0   @jupyterlab/services
```
this is with jupyterlab 0.30.6 (current on conda-forge).
previously we worked around this version locking on jupyterlab 0.29.2,
but that doesn't work anymore.  is this a known problem?
any way to workaround it (eg, request a particular jupyterlab-manager)?
is there a better issue to track this?

**Comment by blink1073** [comment]
The current version of `@jupyter-widgets/jupyterlab-manager` is compatible with JupyterLab 0.31.0rc1 which can be installed as `pip install --pre jupyterlab`.  To install a version compatible with 0.30.x, you can `jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.31`, which is the previous version of the widgets manager.

**Comment by scottdraves** [comment]
Thanks I opted for manager 0.31 and it worked great.

**Comment by johnjihong** [comment]
i got the same issue and the above instruments doesn't seem to fix the issue at all. 

still got below error:
ValueError:
"@jupyter-widgets/jupyterlab-manager@0.31.3" is not compatible with the current
JupyterLab
Conflicting Dependencies:
JupyterLab                        Extension            Package
>=0.14.1-0 <0.15.0-0              >=0.13.0-0 <0.14.0-0 @jupyterlab/application
>=1.0.1-0 <2.0.0-0                >=0.13.0-0 <0.14.0-0 @jupyterlab/coreutils
>=0.14.1-0 <0.15.0-0              >=0.13.0-0 <0.14.0-0 @jupyterlab/notebook
>=0.14.1-0 <0.15.0-0              >=0.13.0-0 <0.14.0-0 @jupyterlab/rendermime
>=1.0.1-0 <2.0.0-0                >=0.4.2-0 <0.5.0-0   @jupyterlab/rendermime-in
terfaces
>=1.0.1-0 <2.0.0-0                >=0.52.0-0 <0.53.0-0 @jupyterlab/services

**Comment by blink1073** [comment]
Hi @johnjihong, it looks like you have JupyterLab 0.31 installed.   `jupyter labextension install @jupyter-widgets/jupyterlab-manager` will get you the compatible version.

**Comment by mrocklin** [comment]
I also ran into this and was happy to find this issue with a fix

**Comment by jasongrout** [comment]
Sounds like we should put up a table of versions and what they are compatible with: https://github.com/jupyter-widgets/ipywidgets/issues/1893

**Comment by vidartf** [comment]
Is it feasible to put a compatibility map into the package.json metadata, such that `jupyter labextension install` will be able to find the correct version of the package to use for the lab version that is installed?

**Comment by vidartf** [comment]
For examples:
```json
jupyterlab: {
  "extension": "lib/plugin",
  "compatibility": {
    "0.14.0 - 0.27": "^1.0.0",
    "0.28 - 0.32": "^2.0.0"
  }
}
```
where the semver range on the left matches the lab version, and the semver range on the right matches the extension version. Or possibly a more general system (although I suspect that can quickly grow unwieldy).

**Comment by jasongrout** [comment]
I think it would be great if jlab could automatically find the right compatible version of a plugin.

**Comment by blink1073** [comment]
We could do something like "engine" compatibility that is used for node and atom, at the expense of more fine-grained compatibility of the JS packages.  I think this would make more sense once all of the packages reach 1.0.

**Comment by vidartf** [comment]
The advantages of a lookup table vs. an "engine" field would be that installation commands would be able to install the correct package version with a maximum of two package downloads:
 1. Download the latest version of the package. Then either:
   a. Check the compatibility table directly to figure out if another version of the package is needed.
   b. or, simply try to install the latest version, and only consult the table if installation fails.
 2. If another version was needed, download and install that.

I'm not sure what you would do if you were on lab version X, and tried to install a package that said it needed lab version Y.

**Comment by vidartf** [comment]
Actually, using the "engines" field should work, since that field is part of the package metadata in the registry API: https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md

**Comment by vidartf** [comment]
Actually, we could probably just process the "dependencies" field in that metadata directly, without having to specify engines.

**Comment by vidartf** [comment]
I'll try to write this up for a PR. o/

**Comment by jasongrout** [comment]
Let's close this issue as resolved, and open a new one (or just a PR) for the broader compatibility issue.

**Comment by jasongrout** [comment]
(I also put a small table in the widget manager readme: https://github.com/jupyter-widgets/ipywidgets/tree/67a088aa06e4f1200db034a1f39bd59217aa51a8/packages/jupyterlab-manager#version-compatibility )

**Comment by JuanKRod** [comment]
I have followed all the steps in here - https://github.com/jupyter-widgets/ipywidgets/tree/67a088aa06e4f1200db034a1f39bd59217aa51a8/packages/jupyterlab-manager#version-compatibility & in all the other hundreds of threads but still not able to make this widgets work.
This is nonsense!
