### ISSUE TITLE
Jupyterlab conflicting dependencies - googledrive extension

### ISSUE THREAD

**Issue by felipelbhering** [jupyterlab/jupyterlab#3226]
Tried to install google drive extension and got conflicting dependencies. Tryed to update package jupyterlab didn't work either , also tryed to reinstall and get from .git and also same error.

Tried in Windows 7 & Windows Server with Anaconda.
How can i solve it?
Thank you.

(C:\Users\xxx\Anaconda2) C:\Users\xxx>jupyter
labextension install @jupyterlab/google-drive
> npm.cmd pack @jupyterlab/google-drive
jupyterlab-google-drive-0.7.0.tgz
Traceback (most recent call last):
  File "C:\Users\xxx\Anaconda2\Scripts\jupyter-labextension-scr
ipt.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\xxx\Anaconda2\lib\site-packages\jupyter_core\a
pplication.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\xxx\Anaconda2\lib\site-packages\traitlets\conf
ig\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\xxx\Anaconda2\lib\site-packages\jupyterlab\lab
extensions.py", line 168, in start
    super(LabExtensionApp, self).start()
  File "C:\Users\xxx\Anaconda2\lib\site-packages\jupyter_core\a
pplication.py", line 256, in start
    self.subapp.start()
  File "C:\Users\digital_intelligence\Anaconda2\lib\site-packages\jupyterlab\lab
extensions.py", line 58, in start
    for arg in self.extra_args]
  File "C:\Users\xxx\Anaconda2\lib\site-packages\jupyterlab\com
mands.py", line 100, in install_extension
    return IOLoop.instance().run_sync(func)
  File "C:\Users\xxx\Anaconda2\lib\site-packages\tornado\ioloop
.py", line 458, in run_sync
    return future_cell[0].result()
  File "C:\Users\xxxx\Anaconda2\lib\site-packages\tornado\concur
rent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\Users\xxxx\Anaconda2\lib\site-packages\tornado\gen.py
", line 1069, in run
    yielded = self.gen.send(value)
  File "C:\Users\xxxx\Anaconda2\lib\site-packages\jupyterlab\com
mands.py", line 158, in install_extension_async
    raise ValueError(msg)
ValueError:
"@jupyterlab/google-drive@0.7.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.10.0-0 <0.11.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/rendermime
>=0.49.0-0 <0.50.0-0    >=0.50.0-0 <0.51.0-0 @jupyterlab/services
>=0.10.0-0 <0.11.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/filebrowser
>=0.10.0-0 <0.11.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/coreutils
>=0.10.0-0 <0.11.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/application
>=0.10.0-0 <0.11.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/docmanager
>=0.10.0-0 <0.11.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/apputils

**Comment by ian-r-rose** [comment]
Hi @felipelbhering , we have not yet published the version for JupyterLab v0.29. We are tracking this in jupyterlab/jupyterlab-google-drive#101.

**Comment by jasongrout** [comment]
For now, @felipelbhering, you can install jupyterlab 0.28 and use the google drive extension with that.

**Comment by jasongrout** [comment]
@felipelbhering - are you using the jupyterlab that comes with Anaconda, version 0.27?

**Comment by felipelbhering** [comment]
i tried both, same error

**Comment by ian-r-rose** [comment]
Hi @felipelbhering , I have just published `v0.8.0`, which works with JupyterLab v0.29, give it a spin!
