### ISSUE TITLE
labextension uninstall does not work on incompatible extensions

### ISSUE THREAD

**Issue by mpacer** [jupyterlab/jupyterlab#3227]
I am trying to work on an extension, and after upgrading jupyterlab I've discovered that another extension [@jupyterlab/github](https://github.com/jupyterlab/jupyterlab-github)  is now out of date and its dependencies do not resolve properly. 

I discovered that disabling this extension still doesn't allow jupyterlab to run. 

So, I attempted to uninstall it with 

```bash
jupyter labextension uninstall @jupyterlab/github
```

And that raised an error finishing with: 

```
JupyterLab              Extension            Package
>=0.12.0-0 <0.13.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/application
>=0.12.4-0 <0.13.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/apputils
>=0.12.0-0 <0.13.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/coreutils
>=0.12.0-0 <0.13.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/docmanager
>=0.12.0-0 <0.13.0-0    >=0.11.0-0 <0.12.0-0 @jupyterlab/filebrowser
>=0.51.0-0 <0.52.0-0    >=0.50.0-0 <0.51.0-0 @jupyterlab/services
```

…the incompatibility of which is exactly why I wanted to uninstall the extension.

Is there any way around this? @ian-r-rose happens to be awesome and has already released a version with upgraded dependencies. But it should be possible to get back to a state where you can have a working version of jupyterlab even if one of your extensions is out-of-date. I'm sure there's a way to do that, but I can't easily figure it out…

**Comment by blink1073** [comment]
Hi @mpacer, sorry I lost the bubble on issues.  You can manually remove the extension for now.  The path can be found using `jupyter lab paths` and going to the `<app_dir>/extensions` directory.
