### ISSUE TITLE
Tab key doesn't indent on left side

### ISSUE THREAD

**Issue by mrinalraghupathi** [jupyterlab/jupyterlab#3232]
At the beginning of an already indented line and try to indent it to the next stop (4 more spaces) I get the autocomplete menu instead of indentation. The only way to indent a block is to backspace the line onto previous line and then hit enter. This is different from the behavior in jupyter notebook.

Using Chrome [Version 61.0.3163.100] on a Mac Sierra OS [10.12.5]

**Comment by caffeine-potent** [comment]
I'd like to confirm that this is not only specific to your setup. I can't indent with `tab` either.

**Comment by JohnHadish** [comment]
I also confirm

**Comment by mnvl** [comment]
I confirm as well

**Comment by jasongrout** [comment]
Are you trying with JupyterLab 0.32.1? What language are you editing? For me, the above behavior works in JupyterLab 0.32.1 with python (tab and shift-tab at the beginning of a line, and indeed anywhere in the beginning whitespace, indents/dedents the line).

**Comment by jasongrout** [comment]
Great, thanks! If anyone can reproduce this with 0.32.1, please comment below. Closing as fixed for now.
