### ISSUE TITLE
Interaction between keyboard navigation and collapsed cells

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#3233]
jupyterlab: v0.29.1

To reproduce:
1. Create two cells with some input. Switch to edit mode, and verify that pressing downarrow moves the cursor from one cell to another and moves the current cell indicator on the left margin.
2. Collapse the lower cell, try to navigate from the uncollapsed cell to the collapsed one using downarrow. Observe that the current cell indicator moves to the collapsed cell, but the cursor stays in the uncollapsed cell. Observe that further arrow navigation and further edits modify the first cell, and not the collapsed one.

I'm unsure what the correct behavior should be here, but the current behavior seems inconsistent.

**Comment by jasongrout** [comment]
I reproduced this with 0.34.

**Comment by tgeorgeux** [comment]
@jasongrout I had a chance to play around with this a bit. I wanted to flag a couple of things:

- If you have multiple cells collapsed in a row, the cursor will stay in the last uncollapsed cell, but the blue 'cell selected' indicator cycles through collapsed cells. 
- Indicator and cursor both advance past a 'group' of collapsed cells.

I think we can go with one of two options. 

1. Collapsed cells are ignored when navigating with arrow keys.
2. Collapsed cells can be focussed when navigating with arrow keys, but cell input is disabled until an expanded cell is focussed. I don't like this option as much unless we have a keyboard shortcut to expand/collapse cells (which to my knowledge we don't). 

For simplicity's sake I suggest option 1 for now.

**Comment by vidartf** [comment]
My 2 cents: Option 2, but where a focused, collapsed cell is expanded by hitting space/enter (maybe space keeps you in command mode and enter puts you in edit mode?).

**Comment by jasongrout** [comment]
I like option 1. If you have a lot of collapsed cells in a row, but no way to execute them, I think just skipping them may be a better ux (i.e., option 1) (so shift-enter also just skips them, etc.).

**Comment by jasongrout** [comment]
On the other hand, if I select a bunch of cells including collapsed cells, and then execute selected cells, should those collapsed cells be executed?

**Comment by tgeorgeux** [comment]
I know we're looking at the concept of 'hiding' versus 'collapsing' with regard to cells. This context comes up from the new new controls associated with the ToC extension. 

I think #1 has the least implications for future design decisions.

**Comment by tgeorgeux** [comment]
I think we should move forward with skipping collapsed cells when scrolling with the keyboard for now. We can always address this further if that's causing trouble.

**Comment by saulshanabrook** [comment]
I will have a go at this. My understanding is that if I am in this state here:

<img width="957" alt="Screen Shot 2019-05-15 at 12 58 08 PM" src="https://user-images.githubusercontent.com/1186124/57794204-21feb200-7711-11e9-81ca-bb04072f0166.png">


And I press the down arrow, it should focus on cell [6] with the content `B` and when I type after hitting down, it should end up in that cell. Is that right?

**Comment by akhmerov** [comment]
Either that, or nothing happens, or cell expands—not sure what's the best here.
