### ISSUE TITLE
:w should save file in vim editing mode

### ISSUE THREAD

**Issue by jllanfranchi** [jupyterlab/jupyterlab#3239]
Coming from using VIM extensively, it is my habit to type <esc>:w to save a file. That command does not say it _doesn't_ save the file, but after a long session of edits, when I go to close the file, turns out I needed to do <ctl>-s to save the doc as I was editing.

This is counter-intuitive at least for VIM users, and could lead to loss of edits to a file.

**Comment by ian-r-rose** [comment]
This should be possible. CodeMirror allows a save hook to be set on an editor (cf https://codemirror.net/demo/vim.html).

It doesn't, however, look like `:wq` will work.

**Comment by davidrthorn** [comment]
I've just started learning vim and am new to opensource, but I'll take a look at this. No idea if it lies within my programming abilities, but here goes nothing...

**Comment by ian-r-rose** [comment]
Great! Feel free to open any work-in-progress pull requests for comments and help.

**Comment by davidrthorn** [comment]
Is there any chance of being assigned this issue officially?

**Comment by blink1073** [comment]
As in, you'd like it to be assigned to you?

**Comment by davidrthorn** [comment]
If possible, yes (see 4 comments back)

**Comment by blink1073** [comment]
I can assign you once you become a member of the org (check your email please).

**Comment by blink1073** [comment]
The UI won't let me add you otherwise.

**Comment by davidrthorn** [comment]
@blink1073 Done. Thanks for your help and patience with this and other issues. It's all new to me at the moment!

**Comment by blink1073** [comment]
Assigned!  Welcome aboard!

**Comment by jwkvam** [comment]
I solved this in jupyterlab_vim for notebooks [1]. I imagine it would be similar for the file editor?

[1] https://github.com/jwkvam/jupyterlab_vim/blob/master/src/index.ts#L58

**Comment by davidrthorn** [comment]
@jwkvam you're probably right. Am I OK to just port this over? (first time contributor to open source, so I don't really know the protocols).

**Comment by jwkvam** [comment]
@davidanthoff Yea fine with me, give it a shot!

**Comment by davidanthoff** [comment]
@jwkvam You probably wanted to send this message to someone else?

**Comment by jwkvam** [comment]
yea sorry

**Comment by ian-r-rose** [comment]
@davidrthorn If you want any pointers about how to go about making your PR, feel free to ask.

**Comment by davidrthorn** [comment]
@ian-r-rose Thanks! I'm about to submit the pull request. It would be good to know what details I should include in my comments. At the moment, I have described the changes and raised a concern that the code, although functional, might be in the wrong place from an organisation point of view. Should I add anything else?

**Comment by ian-r-rose** [comment]
No, that sounds fine. If there are more questions we can ask them during review.

**Comment by ian-r-rose** [comment]
Closed via #3698. Thanks, @davidrthorn!
