### ISSUE TITLE
Launch JupyterLab with a notebook already open

### ISSUE THREAD

**Issue by leonsp** [jupyterlab/jupyterlab#3241]
I'd like to teach several classes using JupyterLab. This would work best if I could launch Jupyter Lab with a notebook already open so that my students could get started right away without navigating the file tree.

It's possible to do it with vanilla Jupyter by opening a URL like `/notebooks/example/example.ipynb`. Unfortunately, this is missing all the great things in the Jupyter Lab interface.

It would be great if I could launch JupyterLab with a URL like `/lab/example/example.ipynb` or `lab#!/example/example.ipynb` or `lab?notebook=/example/example.ipynb` so that JupyterLab has a specific notebook open in a tab.

There's a related proposal in #1075, but I think this use case is different.

**Comment by ian-r-rose** [comment]
This can now be done with the `/tree` handler, and more complex layouts can be opened with the `/workspaces` handler. Closing as fixed, thanks for the feedback @leonsp!
