### ISSUE TITLE
Cannot copy to clipboard from vim editor mode

### ISSUE THREAD

**Issue by philippeller** [jupyterlab/jupyterlab#3248]
When setting the editor mode to `vim`, the usual yank command works but only for pasting in vim, not paste sth. to e.g. a notebook. Also `ctrl`+`c` does not work in `vim` mode (it works in other modes though).

**Comment by ggada** [comment]
+1, facing the same issue.

**Comment by dvincentwest** [comment]
Same here, any plans to get this working?  Would be a big help

**Comment by jasongrout** [comment]
We use codemirror as our editor. Does it work in codemirror in vim mode? You can test it at https://codemirror.net/demo/vim.html

**Comment by dvincentwest** [comment]
It seems to work the same as in JupyterLab: Ctrl + V will paste in text from the clipboard, but there is no way to Yank text out to the clipboard that I can see from the keyboard (Ctrl-C doesn't work and (" + `+` + y) doesn't work.  However, right clicking on the text will bring up an option to copy the selected text which in turn is added to the clipboard (see the screenshot).  Even this would be super helpful.  I also see in the screenshot that no one is maintaining Vim Emulation for this :-(

Lastly, this issue:
https://github.com/codemirror/CodeMirror/issues/3075

references this issue: 
https://github.com/LightTable/LightTable/issues/688

which says you can re-bind Ctrl-C to perform a copy operation by modifying the user keymap with this: 

```:editor.keys.vim {"ctrl-c" [:editor.copy]}```

Is something like that possible in JupyterLab?

![image](https://user-images.githubusercontent.com/9872343/62898936-46702780-bd1c-11e9-88a0-831e6b1b8920.png)

**Comment by jasongrout** [comment]
Thank you for researching this so thoroughly. A couple of thoughts:

1. You should be able to get the browser menu (with its cut/copy/paste) with shift-right-click in JupyterLab. I think the bottom entry of the JupyterLab context menu mentions this?
2. Glancing at the codemirror issue, it sounds like enabling Ctrl+C for copy would be overriding one of the vi keystrokes. Would this be a problem for other vim users?
3. The lighttable issue above mentions how to configure light table for this keystroke. It is much harder to configure something in the browser to copy/paste programmatically. The browser APIs make it difficult (see, for example, https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand and https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API). So it may be easiest to just use the native browser menu with shift-right-click (or the browser Edit menu).

**Comment by dvincentwest** [comment]
Thank you for researching this so thoroughly. A couple of thoughts:

1. *You should be able to get the browser menu (with its cut/copy/paste) with shift-right-click in JupyterLab. I think the bottom entry of the JupyterLab context menu mentions this*?

sweet, this works as expected

2. *Glancing at the codemirror issue, it sounds like enabling Ctrl+C for copy would be overriding one of the vi keystrokes. Would this be a problem for other vim *

Yes, Ctrl-C also functions as the `ESC` key to exit out of insert mode, so changing the default behavior would be pretty bad

3. The lighttable issue above mentions how to configure light table for this keystroke. It is much harder to configure something in the browser to copy/paste programmatically. The browser APIs make it difficult (see, for example, https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand and https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API). So it may be easiest to just use the native browser menu with shift-right-click (or the browser Edit menu).

I am happy to have a working solution with <S-C-right click> thanks very much

**Comment by jasongrout** [comment]
Great! I think we can close this now with the above discussion.
