### ISSUE TITLE
Download menu option not working in the file browser

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#3250]
Observed in v0.29.1, chrome and firefox, ubuntu. To reproduce right-click on any item within a file browser and click on the "download" menu item. Observe that download does not start despite js console shows no exceptions.

**Comment by blink1073** [comment]
Hmm, I'm not sure why that would be.  I just tried with Firefox 55 on Ubuntu 16.04.  You could try setting a debug point on [this line](https://github.com/jupyterlab/jupyterlab/blob/78887b75718da0cf4c8b65ae2b4661a162ddd9cc/packages/filebrowser/src/listing.ts#L423).

**Comment by akhmerov** [comment]
Seemingly a broken installation; I cannot reproduce it on a fresh install neither.
