### ISSUE TITLE
More helpful error message if node isn't installed

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#3253]
I tried installing a labextension without having node installed, and got this error message:

`FileNotFoundError: [Errno 2] No such file or directory: 'node'`

I think it'd be more helpful for users (especially those not familiar with the node/npm world, which is probably most users) if we added a check for the existence of node, and a helpful error message pointing people in the rigt direction if it doesn't exist.

**Comment by ian-r-rose** [comment]
@choldgraf when I try this, I get the error that you show, but after that I also see the intended (more informative) error message:
```
ValueError: `node` version 5+ is required, see extensions in README
```

**Comment by choldgraf** [comment]
ack - you are right! I scrolled up too much in my error output. I the language there could be improved a bit. E.g., most people would get this error in the context of a specific extension they're installing. The error message is ambiguous with respect to the README file. Is it the one for the extension? For JupyterLab? How about instead, it says "see <url-to-jupyterlab-node-instructions> for more information"

**Comment by blink1073** [comment]
When https://github.com/jupyterlab/jupyterlab/pull/3168 the message will be "Please install nodejs using conda or the nodejs website".

**Comment by choldgraf** [comment]
Sounds great! Feel free to close this now, or whenever that's merged
