### ISSUE TITLE
Can we now keep notebook running (and its live outputs) after the browser tab closed ?

### ISSUE THREAD

**Issue by phizaz** [jupyterlab/jupyterlab#3254]
_From https://github.com/jupyter/notebook/issues/1647_

I tested it and it didn't work (as before). 
Is there a better chance for this to be implemented in **jupyterlab** ?

**Comment by blink1073** [comment]
This is an intended outcome of the notebook model [refactor](https://github.com/jupyterlab/jupyterlab/issues/2540#issuecomment-339467751).

**Comment by JasonWeill** [comment]
[Jupyter Scheduler](https://github.com/jupyter-server/jupyter-scheduler/) allows for one-off notebook runs while unattended, although you do need to keep your Jupyter Server instance running even if you close your web browser.

**Comment by krassowski** [comment]
The notebook is running after the browser tab closes (as long as the server keeps running). The restoration of outputs is tracked in https://github.com/jupyterlab/jupyterlab/issues/2833 and there is a pull request for it (https://github.com/jupyterlab/jupyterlab/pull/15448), so I will go ahead and close this issue.
