### ISSUE TITLE
Request header field X-XSRFToken is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by krokha72** [jupyterlab/jupyterlab#3261]
I am using following tutorial to build sample jupyterlab extension
_http://jupyterlab-tutorial.readthedocs.io/en/latest/xkcd_extension_tutorial.html_
and run into run-time error on step 'Show a comic in the panel'
_lab:1 Failed to load https://egszlpbmle.execute-api.us-east-1.amazonaws.com/prod?1511122136445: Request header field X-XSRFToken is not allowed by Access-Control-Allow-Headers in preflight response._
my web client is windows chrome and the https request run fine if I manually run above url
I have attached zip with  jupyterlab_xkcd/src/index.ts 
[index.zip](https://github.com/jupyterlab/jupyterlab/files/1485950/index.zip)

Here is my local versions:
npm v 5.5.1
nodejs v 8.9.1
jupyterlab v 0.29.2
Could you advise what I might be doing wrong or suggest work around please
Thanks
Alex

**Comment by blink1073** [comment]
Hi @krokha72, the `serverConnection` is an opinionated wrapper around the [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest) that is tailored to interact with the notebook server.  We could add a check for whether the request is being sent to the notebook server before adding the headers [here](https://github.com/jupyterlab/jupyterlab/blob/ad7b99e6bc0364d81127ab84d0be8d598bbb25c5/packages/services/src/serverconnection.ts#L292).  In the mean time, you can use the raw `XMLHttpRequest` or the new [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).

**Comment by krokha72** [comment]
Hi @blink1073 Steven, 
Apologies as I'm new to the project and need a little more guidance to workaround. I tried to use XMLHttpRequest without lock, npm build comes with compile errors.  Could you possibly to reference to relevant prototype/src using  XMLHttpRequest  or help me to modify index.cs lines - see attached in my initial note.   Thanks in advance. Alex

**Comment by blink1073** [comment]
This [stub](https://www.typescriptlang.org/play/#src=%0A%0Avar%20xhr%20%3D%20new%20XMLHttpRequest()%3B%0A%0Alet%20img%20%3D%20document.createElement('img')%3B%0A%20%0Axhr.onload%20%3D%20(event%3A%20ProgressEvent)%20%3D%3E%20%7B%0A%20%20%20%20let%20data%20%3D%20JSON.parse(xhr.responseText)%3B%0A%20%20%20%20img.src%20%3D%20data.img%3B%0A%20%20%20%20img.alt%20%3D%20data.title%3B%0A%20%20%20%20img.title%20%3D%20data.alt%3B%0A%0A%7D%3B%0Axhr.open(%22GET%22%2C%20%22https%3A%2F%2F%2F%2Fegszlpbmle.execute-api.us-east-1.amazonaws.com%2Fprod%22)%3B%0Axhr.send()%3B) should work.

**Comment by krokha72** [comment]
Steven, I have replaced ServerConnection  section with  XMLHttpRequest  stub per your suggestion, and getting same error
Failed to load https://egszlpbmle.execute-api.us-east-1.amazonaws.com/prod?1511199848874: Request header field X-XSRFToken is not allowed by Access-Control-Allow-Headers in preflight response.
I have attached updated index.ts and snip of windows chrome client console error message
could you advise please  
[index.zip](https://github.com/jupyterlab/jupyterlab/files/1488672/index.zip)
![err-capture](https://user-images.githubusercontent.com/33524926/33034087-b187dcde-cdf4-11e7-8311-02d4f61ecbe4.JPG)

**Comment by blink1073** [comment]
Can you post the updated code?

**Comment by krokha72** [comment]
/*
import {
  ServerConnection
} from '@jupyterlab/services';
*/
import {
  Widget
} from '@phosphor/widgets';

import {
  ICommandPalette
} from '@jupyterlab/apputils';

import {
  JupyterLabPlugin
} from '@jupyterlab/application';

import '../style/index.css';


/**
 * Initialization data for the jupyterlab_xkcd extension.
 */
const extension: JupyterLabPlugin<void> = {
  id: 'jupyterlab_xkcd',
  autoStart: true,
  requires: [ICommandPalette],
  activate: (app, palette: ICommandPalette) => {
    console.log('JupyterLab extension jupyterlab_xkcd is activated!');

    // Create a single widget
    let widget: Widget = new Widget();
    widget.id = 'xkcd-jupyterlab';
    widget.title.label = 'xkcd.com';
    widget.title.closable = true;
    
    // Add an image element to the panel
    let img = document.createElement('img');
    widget.node.appendChild(img);

    /**
    // Fetch info about a random comic
    let settings = ServerConnection.makeSettings();
    ServerConnection.makeRequest({url: 'https:////egszlpbmle.execute-api.us-east-1.amazonaws.com/prod'}, settings).then(response => {
      img.src = response.data.img;
      img.alt = response.data.title;
      img.title = response.data.alt;
    });
    **/
    // XMLHttpRequest stub
    var xhr = new XMLHttpRequest();
    //let img = document.createElement('img');
    xhr.onload = (event: ProgressEvent) => {
      let data = JSON.parse(xhr.responseText);
      img.src = data.img;
      img.alt = data.title;
      img.title = data.alt;
    };
    xhr.open("GET", "https:////egszlpbmle.execute-api.us-east-1.amazonaws.com/prod");
    xhr.send();

    // Add an application command
    const command: string = 'xkcd:open';
    app.commands.addCommand(command, {
      label: 'Random xkcd comic',
      execute: () => {
        if (!widget.isAttached) {
          // Attach the widget to the main area if it's not there
          app.shell.addToMainArea(widget);
        }
        // Activate the widget
        app.shell.activateById(widget.id);
      }
    });

    // Add the command to the palette.
    palette.addItem({command, category: 'Tutorial'});
  }
};

export default extension;

**Comment by blink1073** [comment]
The error is coming from the `serverConnection` block, you can remove that section.

**Comment by blink1073** [comment]
Oh wait, I see that it is commented out, looking again.

**Comment by blink1073** [comment]
I suspect the updated TS code isn't in the bundle, have your rebuilt your extension and either `jupyter lab build` or run `jupyter lab --watch`?

**Comment by krokha72** [comment]
nope, did only> npm run build, lemme do it now

**Comment by krokha72** [comment]
new error
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by krokha72** [comment]
hold on pls, will do clean and rebuild

**Comment by blink1073** [comment]
I'm not sure what extra authentication is required, but you can play with it in the JavaScript console:

```javascript
var xhr = new XMLHttpRequest();
    //let img = document.createElement('img');
    xhr.onload = () => {
      let data = JSON.parse(xhr.responseText);
      img.src = data.img;
      img.alt = data.title;
      img.title = data.alt;
    };
    xhr.open("GET", "https:////egszlpbmle.execute-api.us-east-1.amazonaws.com/prod");
    xhr.send();
VM60:10 Refused to connect to 'https://egszlpbmle.execute-api.us-east-1.amazonaws.com/prod' because it violates the following Content Security Policy directive: "connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com".
```

**Comment by krokha72** [comment]
Steven, clean&& build did it!! 
Thanks a lot for your time and prompt help
Should I close this issue now?

**Comment by blink1073** [comment]
Cheers!  Let's leave it open until we make the fix the auto-header-adding when we aren't trying to talk to the notebook server.

**Comment by krokha72** [comment]
Steve, no problem
My 2c for the xkcd_extension_tutorial doc. it may be worth mentioning that it needs latest npm and NodeJS. My ubuntu came with npm v 3.10 - it did not work, updated v 5.5 - compiled ok

And also could you point me to the tutorial (if any) describing how to compile and install new jupyterlab-theme extension, similar to http://jupyterlab-tutorial.readthedocs.io/en/latest/xkcd_extension_tutorial.html
I started with pre-compiled  JupyterLab Light/Dark , but many files seems to be auto generated and tutorial will be great help to start with new theme.
Thanks
Alex

**Comment by blink1073** [comment]
We don't yet have a theme tutorial, here is the documentation: http://jupyterlab-tutorial.readthedocs.io/en/latest/extensions_dev.html#themes.
