### ISSUE TITLE
Icon text too short to recognize kernel

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab#3262]
As one can see from this screenshot, the current icon text is too short to see with icon represents which kernel.
This might only be the case when using `nb_conda_kernels`, but I could not live without that! ;)

![screenshot 2017-11-19 20 12 18](https://user-images.githubusercontent.com/69774/33000567-2fbaee78-cd66-11e7-8ca6-1ee26c5fb87b.png)

Running 0.29.2, Python 3.6 via conda-forge, on macOSX 10.12.6

**Comment by jasongrout** [comment]
Let's move the discussion over to #3795, which is the same issue, but has more discussion. Thanks!
