### ISSUE TITLE
Widgets not showing in v0.29.2

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab#3263]
With a simple

```python
from ipywidgets import Text
Text("hello")
```
I get the error
> Error displaying widget

and a weird log entry talking about jupyter-matplotlib, don't know what that is:

```bash
[W 23:43:34.124 LabApp] 404 GET /nullnbextensions/jupyter-matplotlib/1.bundle.js (10.247.18.92) 40.17ms referer=https://macd2860:8901/lab?
```
Also other widgets don't work, like IntProgress (that's how I found this issue).

I cross-checked with `jupyter notebook` and all works fine there.

I have created a test Python 3.6 conda env for this with:
```bash
conda create -n testing python=3 jupyterlab nb_conda_kernels ipywidgets
```
using `conda-forge`.

Here are the resulting versions:
```bash
(testing) └─( 2 ) ❱❱❱ conda list jupyter                                       +8696 23:48 ❰─┘
# packages in environment at /Users/klay6683/miniconda3/envs/testing:
#
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.29.2                   py36_0    conda-forge
jupyterlab_launcher       0.5.5                    py36_0    conda-forge
```
```bash
(testing) └─❱❱❱ conda list widgets                                             +8680 23:56 ❰─┘
# packages in environment at /Users/klay6683/miniconda3/envs/testing:
#
ipywidgets                7.0.5                    py36_0    conda-forge
widgetsnbextension        3.0.8                    py36_0    conda-forge
```
and here's IPython.sys_info():
```bash
(testing) └─( 2 ) ❱❱❱ python -c "import IPython; print(IPython.sys_info())"    +8697 23:49 ❰─┘
{'commit_hash': 'ca5443062',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/klay6683/miniconda3/envs/testing/lib/python3.6/site-packages/IPython',
 'ipython_version': '6.2.1',
 'os_name': 'posix',
 'platform': 'Darwin-16.7.0-x86_64-i386-64bit',
 'sys_executable': '/Users/klay6683/miniconda3/envs/testing/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.6.3 | packaged by conda-forge | (default, Nov  4 2017, '
                '10:13:32) \n'
                '[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]'}
```

**Comment by blink1073** [comment]
HI @michaelaye, widgets are not included in the core JupyterLab bundle.  You can install them as `jupyter labextension install @jupyter-widgets/jupyterlab-manager`.

**Comment by michaelaye** [comment]
They are installed:
```bash
(stable) └─❱❱❱ jupyter labextension list                                     +8729 6:36 ❰─┘
JupyterLab v0.29.2
Known labextensions:
   app dir: /Users/klay6683/miniconda3/envs/stable/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.30.0  enabled  OK
jupyter-matplotlib
        jupyter-matplotlib v0.2.2  enabled  OK
```

**Comment by blink1073** [comment]
Ah, it looks like `jupyter-matplotlib` is at fault here.  If I run `jupyter labextension disable jupyter-matplotlib` then the core widgets work fine.

**Comment by blink1073** [comment]
@vidartf saw something similar in `pythreejs`, what was the fix?

**Comment by vidartf** [comment]
Yup, that's the one :)

**Comment by vidartf** [comment]
I didn't commit it yet, but the fix I settled for was to change it to:
```js
var dataBaseUrl = document.querySelector('body').getAttribute('data-base-url');
if (dataBaseUrl !== null) {
    __webpack_public_path__ = dataBaseUrl + 'nbextensions/jupyter-threejs/';
}
```

**Comment by blink1073** [comment]
I think the right solution is to isolate the two extensions: https://github.com/matplotlib/jupyter-matplotlib/pull/31.

**Comment by blink1073** [comment]
Fixed in `ipympl@0.1.0`.

**Comment by pwuertz** [comment]
I'm seeing an error like this, despite having installed `ipympl-0.1.0`. Trying to use matplotlib in jupyterlab just returns the text
```
Error displaying widget
```
The line `from ipywidgets import IntSlider; IntSlider()` gives the same error, but additionally shows
```
[W 13:10:02.614 LabApp] 404 GET /nullnbextensions/jupyter-matplotlib/0.bundle.js (127.0.0.1)
```
in the console running jupyter lab.

After using the command `jupyter labextension disable jupyter-matplotlib` you mentioned, the IntSlider starts working, but a `%matplotlib ipympl` cell still returns `Error displaying widget` with no further error.

**Comment by blink1073** [comment]
Hi @pwuertz, what does `jupyter labextension list` show?

**Comment by pwuertz** [comment]
```
$ jupyter labextension list
JupyterLab v0.30.6
Known labextensions:
   app dir: /home/pwuertz/.local/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.31.3  enabled  OK
jupyter-matplotlib
        jupyter-matplotlib v0.2.2  enabled  OK
```

**Comment by blink1073** [comment]
Ah, that is not the current version of the JavaScript, can you you please try `pip uninstall -y ipympl; pip install ipympl`?  Then `jupyter labextension list` should show `v0.3.0` and you can run `jupyter lab build`.

**Comment by pwuertz** [comment]
Ok, here is what happened to `jupyter-matplotlib` reported by the labextension list command:

Uninstalling `ipympl`: no change.
Reinstalling `ipympl`: no change.
Deleting the whole .local/share/jupyter folder: gone
Reinstalling `ipympl`: `jupyter-matplotlib v0.3.0  enabled  OK`, yay

Then I ran `jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib`, (which I'm still supposed to do, right?) and the version went back to `jupyter-matplotlib v0.2.2`.

**Comment by pwuertz** [comment]
I now deleted `.local/share/jupyter/lab/extensions/jupyter-matplotlib-0.2.2.tgz` + `jupyter lab build`. Reinstalled `ipympl`, `jupyter-matplotlib-0.3.0.tgz` shows up in the extensions folder, then after `jupyter lab build` matplotlib works.

**Comment by blink1073** [comment]
The problem was that I had forgotten to publish `jupyter-matplotlib@0.3.0` to `npm`, now done.
