### ISSUE TITLE
Automated Testing?

### ISSUE THREAD

**Issue by OliverEvans96** [jupyterlab/jupyterlab#3265]
Hi all,

I was asking the ipywidgets folks if they have any general automated testing practices for widgets in jupyter-widgets/ipywidgets#1814, and was sent here.

So I'm curious: what kind of automated testing do you employ in JupyterLab? Do you use Selenium or some similar tool to make sure the interface is layed out properly and that all button clicks are working, etc.? Anything I should read up on?

Thanks!
Oliver

**Comment by blink1073** [comment]
We don't check layout per se.  Most of our tests use [karma](https://github.com/jupyterlab/jupyterlab/blob/master/test/karma.conf.js) and are unit tests that make sure elements are added to the page, respond to events properly, etc.  We have a [selenium test](https://github.com/jupyterlab/jupyterlab/blob/ad7b99e6bc0364d81127ab84d0be8d598bbb25c5/jupyterlab/selenium_check.py) that make sure the application starts properly and doesn't emit any errors at startup, and can be used in [CI](https://github.com/jupyterlab/jupyter-renderers/blob/7d8df71e56da78cb41cd155b8278ffe38ff78a94/.travis.yml#L34).  It currently doesn't capture `console.error`, but that will be there in the next release.

**Comment by blink1073** [comment]
Example generating a [key event](https://github.com/jupyterlab/jupyterlab/blob/0abee37a187eaeaf5525efed67cce56633f7f80a/test/src/codemirror/editor.spec.ts#L373).

**Comment by OliverEvans96** [comment]
Thanks Steven!

**Comment by blink1073** [comment]
Cheers!
