### ISSUE TITLE
Theme SVGs don't load when opening new notebooks

### ISSUE THREAD

**Issue by sunny-g** [jupyterlab/jupyterlab#3267]
Running `jupyter lab` with some custom extensions and trying to open a blank notebook yields some 404 errors trying to fetch some `.svg` files.

I think for the bundled light and dark themes `activate` functions, this:

<img width="498" alt="screen shot 2017-11-20 at 2 29 23 pm" src="https://user-images.githubusercontent.com/2055636/33044812-42bc66a2-cdff-11e7-9425-dd69f657391a.png">

should be `'@jupyterlab/theme-dark-extension/style/index.css'` (note the changed file path that includes the `style` directory).

**Comment by sunny-g** [comment]
Not getting the errors anymore, not sure what happened. Closing!

**Comment by blink1073** [comment]
The path is different because we extract from the `style/` directory to the top level theme directory.
