### ISSUE TITLE
Console UI shows collapsers

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#3269]
Cells in the console currently show the old style of input/output collapsers. We should probably
1. decide whether consoles should show collapsers at all, and
2. if so, update the styling to be consistent with the notebook.

In either case, the top banner and input cells should not have collapsers at all (as they currently do).

**Comment by jasongrout** [comment]
I like the collapsers there!

**Comment by jasongrout** [comment]
We took a short consensus in the dev meeting today, and decided that having collapsers in the console is great.
