### ISSUE TITLE
PInch to Zoom + Scoll on terminal have issues on mac with inertial scrolling. 

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#327]
Showin in person hard to record as you need a really high frame rate to see the things bouncing back and forth, but anyway here is the gif: 

![pinch-to-zoom](https://cloud.githubusercontent.com/assets/335567/16772424/d8bfce90-4819-11e6-9cfc-d7ae51bbe05b.gif)

**Comment by jasongrout** [comment]
To reproduce, (for me on OS X using Chrome), open a terminal, pinch to zoom into the page, put your cursor over the terminal, and try to scroll horizontally (or vertically) with a two-finger gesture. Scrolling with your cursor over another part of the application seems to work fine.

**Comment by jasongrout** [comment]
I can't reproduce this now with current FF 62 or Chrome 68. @Carreau - do you see this happening with the current JupyterLab?

**Comment by vidartf** [comment]
Closing due to lack of input, and @jasongrout no longer being able to reproduce.
