### ISSUE TITLE
Enable normal left click behaviour on output images 

### ISSUE THREAD

**Issue by Fenton-Fenton** [jupyterlab/jupyterlab#3280]
When running jupyter lab on OSX and using Safari (although I believe this issue will likely effect all browsers and os's although I have not had time to check yet) I'm unable to right click on output images as you are able to do in jupyter notebooks. 

Images attached for clarity:

<img width="617" alt="screen shot 2017-11-25 at 14 05 18" src="https://user-images.githubusercontent.com/33982951/33231261-f246ebb8-d1e9-11e7-9c09-18db02ef6320.png">
<img width="524" alt="screen shot 2017-11-25 at 14 05 33" src="https://user-images.githubusercontent.com/33982951/33231262-f26086a4-d1e9-11e7-87d3-884c49fd180d.png">

**Comment by sccolbert** [comment]
Hold shift when right clicking to get the default browser context menu.
