### ISSUE TITLE
Theme extension documentation needs clarification

### ISSUE THREAD

**Issue by krokha72** [jupyterlab/jupyterlab#3282]
Hi,
I am aiming to create new jupyterlab theme extension and to this end did following steps
- copied and modified existing theme extension, JupyterLab Light Theme
- removed existing ./node_modules folder
- from within extension folder (theme-new-extension) run following
  $ npm install # runs OK
  $ jupyter labextension link . // generates following missing directory /style
Could you advise what I might be doing wrong or workaround
for the note, npm --version 5.4.2
Thanks in advance 
-Alex

> @jupyterlab/application-top@0.12.0 clean ~anaconda3/envs/jupyterlab-theme/share/jupyter/lab/staging
> rimraf build
> npm run build:prod
> @jupyterlab/application-top@0.12.0 build:prod ~anaconda3/envs/jupyterlab-theme/share/jupyter/lab/staging
> webpack --define process.env.NODE_ENV="'production'"
fs.js:950
  binding.stat(pathModule._makeLong(path));
          ^
Error: ENOENT: no such file or directory, stat '~/anaconda3/envs/jupyterlab-theme/share/jupyter/lab/staging/node_modules/@jupyterlab/theme-new-extension/style'

**Comment by blink1073** [comment]
Hi @krokha72, it looks like the files metadata in package.json may be the culprit, can you link to your extension work in progress?

**Comment by krokha72** [comment]
Steven,
Many apologies, Im new your jupyterlab development. Could you be a little
bit more specific. Were you referring to element "files":[..] in
package.json ?

On Sun, Nov 26, 2017 at 10:17 PM, Steven Silvester <notifications@github.com

**Comment by blink1073** [comment]
Yep

**Comment by krokha72** [comment]
I have "files" element same as in source (existing) theme-light-extension
could you advise for the change please

"files": [
    "lib/*.d.ts",
    "lib/*.js.map",
    "lib/*.js",
    "style/*.css",
    "style/images/*.*",
    "style/icons/*.*",
    "style/icons/**/*.*"
  ]

On Sun, Nov 26, 2017 at 10:47 PM, Steven Silvester <notifications@github.com

**Comment by blink1073** [comment]
It is hard to say without seeing your file structure.  Can you please try removing the `files` specifier from your `package.json`?

**Comment by krokha72** [comment]
my files structure is same as theme-light-extension, no changes. I just
replaced few icons (csv-file) to make sure I can compile my own theme
I will remove files element and let you know

On Mon, Nov 27, 2017 at 11:31 AM, Steven Silvester <notifications@github.com

**Comment by krokha72** [comment]
same error when running $ jupyter labextension link .

**Comment by blink1073** [comment]
Hmm, I ran these steps and it worked as expected.  I was able to switch the theme to "JupyterLab Foo" in the settings editor.  Which OS are you using?  And what is `npm -v`?

```bash
cd
cp -r ~/workspace/jupyter/lab/packages/theme-light-extension theme-foo-extension
cd theme-foo-extension
rm -rf node_modules
# edit src/index.ts to replace `light` with `foo`
npm run build
jupyter labextension link .
jupyter lab
```

**Comment by krokha72** [comment]
OS: Ubuntu 16.04.3 LTS
npm --version 5.5.1
I have followed your steps above and still have same error
btw, there is no src/index.ts file existed in source - should I create one manually?

**Comment by krokha72** [comment]
and I am using conda environments, so my source for theme-light-extension
was ~anaconda3/envs/jupyterlab-theme/share/jupyter/lab/themes/@jupyterlab/theme-light-extension
did I use wrong theme-light-extension folder as source in my environment?

**Comment by blink1073** [comment]
Ahh, that makes sense.  Yes, you need to copy the folder from the repo: `packages/theme-light-extension`.

**Comment by krokha72** [comment]
Steven, 
Unfortunately I have installed jupyterlab using conda, and file structure is seemingly different what you have, ie I cannot locate folder jupyter/lab/packages/theme-light-extension
For my purpose ( copy and modify) would you recommend to download theme-light-extension from latest branch https://github.com/jupyterlab/jupyterlab/tree/0.29.x/packages/theme-light-extension ?

**Comment by blink1073** [comment]
Yes, that should do it.

**Comment by krokha72** [comment]
Steven, I followed your instructions and got another errors , although different from where I have started
**ValueError: Cannot link a core extension**
see full trace below
Could you advise work around please
Thanks
Alex

 File "~/anaconda3/bin/jupyter-labextension", line 6, in <module>
    sys.exit(jupyterlab.labextensions.main())
  File "~/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/fincad/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/fincad/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 174, in start
    super(LabExtensionApp, self).start()
  File "/home/fincad/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/fincad/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 89, in start
    for arg in self.extra_args]
  File "/home/fincad/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 89, in <listcomp>
    for arg in self.extra_args]
  File "/home/fincad/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 236, in link_package
    return IOLoop.instance().run_sync(func)
  File "/home/fincad/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/home/fincad/anaconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/fincad/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/fincad/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 263, in link_package_async
    raise ValueError('Cannot link a core extension')
ValueError: Cannot link a core extension

**Comment by blink1073** [comment]
You have to move the folder to a different location not in the git repo checkout folder.

**Comment by krokha72** [comment]
Steven, could you possibly be more specific, What location to move to?  
I did move the folder around. Same error indeed.

**Comment by blink1073** [comment]
Have you changed the name of the extension in the `package.json` file?  I had forgotten to put that step in the instructions above.

**Comment by krokha72** [comment]
Steven, I have changed 'name' in package.json and edited urls.css - and it did the magic)!
New theme was linked in no-errors and working. 
Thanks a lot for your time and help
Last question: I would like to edit jupyterlab system defaults file to point to new theme
Where in jupyterlab system defaults file?

**Comment by blink1073** [comment]
The file should be `~anaconda3/envs/jupyterlab-theme/share/jupyter/lab/schemas/@jupyterlab/apputils-extension/themes.json`

**Comment by krokha72** [comment]
Steven, it worked
I took liberty to compile list of steps I had to run in order to create new new jupyterlab theme, see below
Do you want me to close this issue?
Thanks again for your input and help
-Alex

minimum steps needed to create new theme by cloning and modifying existing theme
1. clone existing theme to create new theme folder, use Jupyter Light as prototype
   ex. https://github.com/jupyterlab/jupyterlab/tree/0.29.x/packages/theme-light-extension
2. modify new folder name and contents as needed
    also its critical to modify the following files
    2.a. package.json - to edit 'name' and other data from 'light' to 'new'
    2.b. edit src/index.ts to replace `light` with `new`  
    2.c. edit style/urls.css to edit url path to point to new image folders
3. update npm, my OS ubuntu came with npm --version 3.10 - it did not work 
    update to latest,  $ npm install -g npm
	version 5.5.1 worked for me
4. cd 'new theme folder'
5. run following commands
   $ rm -rf node_modules
   $ npm install
   $ npm run build
   $ jupyter labextension link .
   $ jupyter labextension list // check new theme registered
   $ jupyter lab

**Comment by blink1073** [comment]
Great!  Let's leave this open until a version of those steps is in  the documentation ;).

**Comment by jasongrout** [comment]
Or write up a cookiecutter for a new theme.

**Comment by cocoaaa** [comment]
@krokha72 and @blink1073, I followed @krokha72 's steps and was able to link the new theme, but I'm not sure how I can start using the new theme (that is, the path to this new theme appears as an installed package in the output of `jupyter labextension list`. Could you tell me what values in the theme.json file I need to change? Thank you.

**Comment by rubenfanjulestrada** [comment]
For me after npm install I try to build and I get 

`jupyterlab/application/tsconfig.json' not found`
