### ISSUE TITLE
Colors in markdown

### ISSUE THREAD

**Issue by samrudh** [jupyterlab/jupyterlab#3283]
Jupyter notebook allows adding color similar to HTML.  `<font color='color'> text </font>.` 
This however does not work in jupyterlab.

**Comment by blink1073** [comment]
Hi @samrudh, this is related to https://github.com/jupyterlab/jupyterlab/issues/1812.  There isn't a currently maintained CSS sanitizer that we are aware of.  Closing in favor of that issue.  Cheers!
