### ISSUE TITLE
toggle output cell vertical scrolling

### ISSUE THREAD

**Issue by daeh** [jupyterlab/jupyterlab#3285]
will there be (or is there currently) a way to toggle whether an output cell expands vertically to fit the contents or imposes a limit on the maximum cell height? It looks like notebooks had this features so I imagine it's in the pipeline somewhere, but it would be great to have here too.

Thanks!

**Comment by blink1073** [comment]
The UI/UX of the cell is still an active area of design.  cf https://github.com/jupyterlab/jupyterlab/issues/1742.  Also related: https://github.com/jupyterlab/jupyterlab/issues/3268

**Comment by ellisonbg** [comment]
Closing in favor of #1309.
