### ISSUE TITLE
Jupyterlab formatting disappears after activating Python 3 (anaconda)

### ISSUE THREAD

**Issue by lukeolson13** [jupyterlab/jupyterlab#3293]
Jupyterlab works just fine opening via '$ Jupyter lab' where my default python is version 2.7.13:
![screenshot from 2017-11-30 12-33-15](https://user-images.githubusercontent.com/28520294/33451069-f7855116-d5ca-11e7-89ff-7948d073db14.png)

However, when I '$ source activate py3' (python version 3.6.2) and open Jupyterlab, i get this:
![screenshot from 2017-11-30 12-33-34](https://user-images.githubusercontent.com/28520294/33451136-4c293584-d5cb-11e7-8978-1b14bc91f0d0.png)

This is what a new notebook looks like:
![screenshot from 2017-11-30 12-39-45](https://user-images.githubusercontent.com/28520294/33451218-95a8e70e-d5cb-11e7-9d66-be4e276f0ce0.png)

**Comment by blink1073** [comment]
Hi @lukeolson13, what does `pip list |  grep jupyterlab` show in the Python 3 environment?

**Comment by lukeolson13** [comment]
Looks like python 3 is showing

**Comment by blink1073** [comment]
Specifically, what is the output of running the command `pip list | grep jupyterlab` in the terminal?

**Comment by lukeolson13** [comment]
Sorry, I accidentally posted that last one before I added in the details. See above.

**Comment by blink1073** [comment]
I'd recommend the following:

```bash
source activate py3
pip install jupyterlab==0.29.2 jupyterlab-launcher==0.5.5
```

**Comment by lukeolson13** [comment]
Thanks! Will I always need to update both each time I update Jupyterlab?

**Comment by blink1073** [comment]
No, I was just being cautious ;).

**Comment by lukeolson13** [comment]
Awesome. Keep up the good work!

**Comment by blink1073** [comment]
Cheers!
