### ISSUE TITLE
Beta milestone date keeps sliding back month by month

### ISSUE THREAD

**Issue by codypiersall** [jupyterlab/jupyterlab#3308]
Since about June (at least that's when I noticed), the beta milestone keeps getting moved back on a month-by-month basis.  So when June was missed, the new milestone target was July; when that was missed, the new date was August; etc. etc.  It would be helpful to people watching the project to have a more firm idea about the target beta release date.  Could someone who understands the work that is yet to be done provide an estimate?  What seems to be happening to me was that every time a target date is missed, the target date gets pushed back a month instead of trying to decide how much time it would actually take.

**Comment by blink1073** [comment]
Hi @codypiersall, we opened #3299 to address this concern.
