### ISSUE TITLE
Dragging into the main area does not add widget to the shell main area focus tracker

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3309]
From https://github.com/jupyter-widgets/ipywidgets/pull/1848#issuecomment-348749386

When a widget is added to the main area, that widget is not added to the shell's _tracker (as happens, for example, in https://github.com/jupyterlab/jupyterlab/blob/9f5f0ac2a4620e7e8b4432ed311566d8b547e0ae/packages/application/src/shell.ts#L372 for the right-click cell mirroring). I suppose it's not getting added to the shell's _tracker because the drop action is an action at the phosphor dockpanel level (i.e., it doesn't know about the shell's tracker), not the application shell level.

The reason dragging from the file listing works is that the drop callback at https://github.com/jupyterlab/jupyterlab/blob/9f5f0ac2a4620e7e8b4432ed311566d8b547e0ae/packages/filebrowser/src/listing.ts#L1159 invokes DocumentManager.open, calling DocumentManager._createOrOpenDocument, which calls the opener at https://github.com/jupyterlab/jupyterlab/blob/9f5f0ac2a4620e7e8b4432ed311566d8b547e0ae/packages/docmanager-extension/src/index.ts#L89, which adds it to the main area using addToMainArea (which then registers the widget with the application shell focus tracker).

From this chain, it appears that a drop callback must add a widget to the main area using the shell addToMainArea? That seems awkward - it's probably better to have the shell's main area dockpanel's drop overridden to add the new widget to the focus tracker if it's not already there? Or maybe even better, override onChildAdded/Removed (https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/dockpanel.ts#L427) to automatically add the new widget to the focus tracker.

Are there situations where a widget should be added to the main area *without* adding it to the main area's focustracker?

**Comment by jasongrout** [comment]
CC @sccolbert as well

**Comment by blink1073** [comment]
👍 to using `onChildAdded/Removed`.  I can't think of a reason not to track a widget in the dock panel.

**Comment by jasongrout** [comment]
Rather than subclassing the dockpanel, perhaps it's even better to just have a child added/removed signal we can connect to. I mean, for now we can install a message filter, but a signal would probably be more natural.

**Comment by jasongrout** [comment]
I guess we're already installing a message hook - I'll extend that.

**Comment by blink1073** [comment]
Ah, right, good call.

**Comment by sccolbert** [comment]
:-1: on subclassing the dockpanel, since that means we're customizes the core app for the benefit of a particular plugin.

I'd be open to adding a signal to the dockpanel if needed, but I'd need to understand the use case more than I could glean from the issue description.

**Comment by jasongrout** [comment]
@sccolbert - I think we're good for now, other than it feels a little weird to install a message filter to listen for child add/remove events. The usecase was that we have some bookkeeping to do when we add/remove children in a dockpanel (in this case, add a CSS class and add the widget to a relevant focus tracker, or remove if removing the child).

I agree on :-1: to subclassing the dockpanel.
