### ISSUE TITLE
New notebooks gets created in wrong directory

### ISSUE THREAD

**Issue by diazgilberto** [jupyterlab/jupyterlab#3312]
Jupyterlab: version: 0.27.0
Mac: 10.13.1
Anaconda Navigator: 1.6.9

What is happening?
After I fire Jupyterlab from the Navigator, I navigate to the working dir utilizing the Jupyterlab file-tree. Then I click the Python3 icon to create a new notebook. The new notebook opens to start working but the file is living in a different directory. I had to search for the file and manually move it to the working directory.

**Comment by blink1073** [comment]
Hi @diazgilberto, that behavior was fixed in 0.28.0, and will get picked up when Anaconda is next updated.  In the mean time you can install newer versions on `conda-forge`.  `conda install -c conda-forge jupyterlab`.

**Comment by diazgilberto** [comment]
Thank you @blink1073! 
I ran `conda update -c conda-forge jupyterlab` and did it for me. Closing the issue...
