### ISSUE TITLE
Using cell collapser results in a react error

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#3322]
I am not sure how important this is, but using a cell collapser gives the following error on the console: 
```
Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
```
cc @ellisonbg

**Comment by blink1073** [comment]
These need to have `key` attributes: https://github.com/jupyterlab/jupyterlab/blob/master/packages/cells/src/placeholder.tsx#L90, https://github.com/jupyterlab/jupyterlab/blob/master/packages/cells/src/placeholder.tsx#L120.

**Comment by blink1073** [comment]
cf https://github.com/jupyterlab/jupyterlab/blob/9ff3bef2df6ce7615f552c1fd08fa4d514afeef1/packages/launcher/src/index.tsx#L310

**Comment by ellisonbg** [comment]
I think a recent react release addressed this wonky key stuff.
