### ISSUE TITLE
"Directory not found" dialogue blocks jupyterlab

### ISSUE THREAD

**Issue by achimgaedke** [jupyterlab/jupyterlab#3324]
Excited to be on 0.30.2 (conda distribution) - Keep up the good stuff!

I've navigated into a subdirectory `a/b` with the file browser in jupyterlab. Then I used the terminal to rename `a` to `c` (accidentally initially, but it reproduces smoothly!).

A modal dialogue pops up saying "Server Connection Error", Directory not found: "a/b".
The modal reappears when clicking "OK".

If I rename `b` (the sub-subdirectory), jupyterlab shows a similar dialogue and resorts to going back to the parent directory. But not in the case renaming `a`, it renders the application unusable.

I use another terminal (via ssh) to undo the rename and jupyterlab recovers.

It would be great if jupyterlab wouldn't freeze. (Also I doubt it is actually a "Server Connection Error".)

**Comment by blink1073** [comment]
Thanks for the report!
