### ISSUE TITLE
Allow safely close the notebook on "Sever Connection Error"

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#3327]
I have a notebook opened and then move a directory (which contains the notebook) in the terminal, then I got the following error message. 

Server Connection Error
Directory not found : ...

I'm not able to close the message box as it appears again I close it. This prevent me from shutting down the opened notebook. I had to go back to the terminal and move the directory back so that I can close the message box, shut down the notebook and the do the directory moving again. I think message box should add a button that allows user to **safely close the opened notebook**.

**Comment by blink1073** [comment]
Hi @dclong, I believe this is the same as #3324, which should be fixed pending #3326.

**Comment by blink1073** [comment]
I'll double check the behavior of that PR when you end up with an orphaned open notebook.

**Comment by blink1073** [comment]
Yep, you choose `File -> Save As` and save it to the new location after that fix.

**Comment by dclong** [comment]
@blink1073 
I'm so glad that the issue is already been noticed and a PR is ready.
