### ISSUE TITLE
Pyspark

### ISSUE THREAD

**Issue by sburke15** [jupyterlab/jupyterlab#3334]
Hello,

Any advice on how to get pyspark running with Jupyter Lab? Using Jupyter notebooks, i have to launch by running "IPYTHON_OPTS="notebook" $SPARK_HOME/bin/pyspark". I have a virtual environment setup with pyspark 1.6.2 being installed on our network. when i run jupyter lab (or notebook without that command), spark is not found

**Comment by blink1073** [comment]
Hi @sburke15, looking at the pyspark [source](https://github.com/apache/spark/blob/d03aebbe6508ba441dc87f9546f27aeb27553d77/bin/pyspark#L36), it looks like that command results in "ipython notebook", which is deprecated:

```
$ ipython notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
```

I think the proper way moving forward would be to use `PYSPARK_DRIVER_PYTHON="jupyter" PYSPARK_DRIVER_PYTHON_OPTS="lab"`

**Comment by blink1073** [comment]
cc @rgbkrk

**Comment by sburke15** [comment]
no luck. when i try to import pyspark, it says it cant be found. no errors messages in my terminal

**Comment by blink1073** [comment]
I'd recommend asking on the PySpark community if they have any recommendations or can point you to a way to extract more debugging information: https://spark.apache.org/community.html

**Comment by sburke15** [comment]
sounds good. appreciate the insight

**Comment by blink1073** [comment]
Cheers!  And don't hesitate to raise the issue further armed with more debug info.  :)

**Comment by rgbkrk** [comment]
pyspark is now pip installable and can just be imported as is as a library. The only special things that the “pyspark notebook” were doing were setting up the spark session and acquiring a sqlContext. At least at Netflix I set folks up with a special kernel that does this for them — it’s highly specialized to our environment. Roughly speaking (and I’m typing from memory on mobile):

1. Configure environment variables for CLASSPATH, HADOOP, etc., make sure those are set either by the kernel manager, a sub process, or as part of the kernelspec
2. when it starts up, have it import pyspark and set up a spark session

**Comment by blink1073** [comment]
Thanks, @rgbkrk!
