### ISSUE TITLE
Math not rendering until after pressing Run twice

### ISSUE THREAD

**Issue by drscotthawley** [jupyterlab/jupyterlab#3336]
In Jupyter Notebook, one could put Latex code in a Markdown cell and expect it to render immediately upon pressing Run, e.g. the sample code from the Jupyter Notebook docs:

$$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$$

But in Jupyter Lab, running a cell with such an equation after entering it will simply result in the un-rendered plaintext appearing -- the first time.  In order to get the proper rendering of the formula, one must go back to the cell and press Run a second time before it will render.

Steps to reproduce:
1. In  Jupyter Lab, press New, select the engine of your choice.
2. Create a new cell, and change its style to Markdown
3. Enter a formula, e.g. paste in the Latex code above.
4. Press Run, observe the non-rendered plaintext.
5. Double-click on the Markdown cell to expose the Latex code.
6. Press Run, and observe the properly rendered image of the equation.

Editing a cell will produce the same behavior -- i.e. if you edit the equation, pressing Run the first time will only produce non-rendered plaintext; you must double-click the cell to expose the source and then press Run a second time in order for the math to render.

Details:
JupyterLab version 0.30.4 (pip, anaconda3)
Node version v6.11.0 (Homebrew) 
Mac OS 10.12.6

**Comment by blink1073** [comment]
Confirmed locally, thanks for the report!

**Comment by ellisonbg** [comment]
Sounds similar to an issue I have seen as well

**Comment by blink1073** [comment]
I'm going to take a look at this one tomorrow morning.

**Comment by blink1073** [comment]
I am able to reliably reproduce this in 0.30.4 but not in master.  @ellisonbg, can you please check this in master as well?

**Comment by ellisonbg** [comment]
I don't see this in master either, let's close for now and re-open if it shows up again. @drscotthawley please keep us posted as the beta release candidate comes out this week. I have certainly observed this before, and want to make sure we catch it.

**Comment by drscotthawley** [comment]
Hi @ellisonbg, I just pulled a new version from pip and what I observe is that, the first time you type an equation it *does* now render correctly. 
However, if you edit the equation at all and then press run, it gives only plaintext the first time.  Pressing run a second time for an edited equation still seems to be required.

**Comment by ellisonbg** [comment]
I just tested it again using your described steps and still couldn't get it to trigger. I am going to reopen so we can keep a close eye on this. Installing from github might not work right now but we should be releasing tomorrow.

**Comment by blink1073** [comment]
Yep, only `--dev-mode` works on master until we release the JS packages.

**Comment by jasongrout** [comment]
I confirm that the code renders properly the first time on current master following the steps outlined in the issue description.

**Comment by jasongrout** [comment]
@drscotthawley - can you test this in the current prerelease? You can install it in a new fresh environment with `pip install --pre jupyterlab`.

**Comment by jasongrout** [comment]
I also confirmed that with current master, editing an equation and then pressing run will correctly render the equation.

**Comment by drscotthawley** [comment]
@jasongrout   Confirmed.  Math now renders immediately for me, both when entered the first time as well as after editing.  
Closing with this comment.

**Comment by dpsanders** [comment]
I can't seem to render equations at all in version 0.35.3.
