### ISSUE TITLE
source code block enhancement within markdown 

### ISSUE THREAD

**Issue by shelper** [jupyterlab/jupyterlab#3340]
I saw syntax color highlighting for the source code block in the markdown (not the preview) in [https://www.youtube.com/watch?v=w7jq4XgwLJQ](https://www.youtube.com/watch?v=w7jq4XgwLJQ) but I could not get it work on my latest jupyterlab from conda-forge...

Another very desirable feature to me is to enable auto-completion in the source code block, cannot miss it these days...

**Comment by blink1073** [comment]
Hi @shelper, I tried the following and it rendered, can you provide an example where the highlighting does not work?

```
    ```python
    def foo(1):
        pass
    ```
```

<img width="128" alt="image" src="https://user-images.githubusercontent.com/2096628/33828055-1f542560-de30-11e7-9a67-0735ea4db8c6.png">

**Comment by shelper** [comment]
it renders in preview, but it does not render syntax highlighting in the markdown source code....

**Comment by blink1073** [comment]
Ah, I see what you mean.  That would take some added parsing of the text buffer to switch syntax highlighting modes in those blocks.  

Dev note: tere's the file that has our markdown parsing for CodeMirror: https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/codemirror-ipythongfm.ts.

**Comment by drunkwcodes** [comment]
While playing around _Lorenz Differential Equations_ demo, I noticed that those mathjax expressions only got  parsed at the first time file loaded.

If I switch markdown cells to other types and switch back, it's mathjax will not be parsed anymore.

**Comment by ian-r-rose** [comment]
Hi @drunkwcodes, I tried what you describe, and it seems to be working properly (after pressing shift-enter to rerender the markdown). In any event, your issue seems to be distinct from this one: can you open a new issue if it persists?

Note for this issue: the syntax highlighting issue seems to have been fixed by #3905

**Comment by drunkwcodes** [comment]
oops, I've seldom used markdown cell. I just found it works like that now.

The performance is very promising!

**Comment by ian-r-rose** [comment]
Glad it's working for you!
