### ISSUE TITLE
Launch terminal command gone from the palette

### ISSUE THREAD

**Issue by jochym** [jupyterlab/jupyterlab#3343]
After upgrade to 0.30 the launch terminal command is gone. Is that intentional?

**Comment by ian-r-rose** [comment]
Hi @jochym, this was removed as part of the ongoing work on revamping the menu system (which is also touching a lot of commands). It should be back after the next round of changes.

**Comment by jochym** [comment]
Ok. Thanks. It was very much missed by one of my users ;)

**Comment by ian-r-rose** [comment]
This is fixed in #3344

**Comment by ian-r-rose** [comment]
Fixed by #3344
