### ISSUE TITLE
Shutdown terminal doesn't work sometimes

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#3355]
The SHUTDOWN button in the TERMINAL SESSIONS doesn't work sometimes. After clicking on a SHUTDOWN button, the corresponding terminal disappears and appears again.

**Comment by blink1073** [comment]
Hi @dclong, it reappears in the "Running" tab?  Does it make a difference whether you have the terminal open in the main panel or not?  Is it happening right away or after a longer period of time?

**Comment by blink1073** [comment]
Thanks!  I wasn't able to reproduce this locally, but it sounds like a race condition.

**Comment by dclong** [comment]
@blink1073 

Likely. I'm a very heavy user of JupyterLab. It common for me to have more than 10 notebooks and 5 terminals opened.

**Comment by jasongrout** [comment]
@dclong - is this still an issue for you?

**Comment by dclong** [comment]
@jasongrout As I mentioned that this typically happens when I use JupyterLab heavily (with many notebooks and terminals opened at the same time). I've just started using JLab 0.34.8 for a few days and hasn't seen this happen. Maybe we should observe it for a longer time before closing this issue?

**Comment by t-makaro** [comment]
I have a similar issue #5061. Except the issue of shutting down a terminal is every single time. I have a gif over at #5061 that shows the problem.

**Comment by jasongrout** [comment]
@dclong - is this on windows? Does it look like the same issue as #5061?

**Comment by dclong** [comment]
@jasongrout This happens on JupyterLab/Hub servers installed on a Ubuntu server. It looks similar to the issue #5061. We can close this one in favor of #5061 as it has more detailed information.

**Comment by jasongrout** [comment]
Thanks!
