### ISSUE TITLE
The `autoClosingBrackets` behavior can't be turned off in Jupyterlab notebook

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#3358]
I might be missing something, but it seems like it's currently impossible to turn off the auto bracket/quote closing behavior when editing notebook in Jupyterlab. The `autoClosingBrackets` option in the Text Editor settings seems to only apply when I open a plain text file, but doesn't change anything for notebooks.

**Comment by telamonian** [comment]
I hacked around in the code for a little bit trying to find an easy solution, but it turned out to be sort of complicated.

Ultimately, the problem seems to be twofold:
- There's no notebook equivalent to the `autoClosingBrackets` option.
- At the lowest level, auto closing is controlled by the `CodeMirror.autoCloseBrackets` option. However, regardless of what this option is initially set to, auto closing is always turned on in notebook cells by the following lines in `codemirror/src/editor.ts`:

```
    let isCode = (mime !== 'text/plain') && (mime !== 'text/x-ipythongfm');
    editor.setOption('matchBrackets', isCode);
    editor.setOption('autoCloseBrackets', isCode);
```
The mime type for a python cell is `text/x-ipython`, so `isCode` is always true.

**Comment by ellisonbg** [comment]
Marking as a beta as this would help us to work out menu structure @ian-r-rose @jasongrout

**Comment by jasongrout** [comment]
@ian-r-rose - assigning to you as this may impact the menu structure.

**Comment by ian-r-rose** [comment]
The main issue here is that we need to think about editor settings for the notebook overall. Unresolved questions:
1. Should the notebook and the text editor share settings? I think that they use sufficiently different editing modes that we may want to have separate settings for them.
1. How should we handle per-view and overall settings? I suspect we may want to have the notebook/text editor draw their settings from the registry upon creation, but then allow those to be overridden on a per-widget basis using the menu UI.
1. Should there be separate settings for code an markdown cells? Probably...

**Comment by chbrown** [comment]
FWIW (this might be documented better elsewhere by now), you can do this by adding the following to `~/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings` (or in JupyterLab → "Settings" menu → "Advanced Settings Editor" → "Notebook" → "User Preferences" tab):

```json
{
  "codeCellConfig": {
    "autoClosingBrackets": false
  }
}
```
