### ISSUE TITLE
Cannot browse directory that has colon in its name

### ISSUE THREAD

**Issue by j-min** [jupyterlab/jupyterlab#3362]
![image](https://user-images.githubusercontent.com/18069263/33844235-01863c68-dee3-11e7-94a3-0b4be1c22103.png)

I cannot go into directories that have colons in their name (both double click and right click+open).

* Environments
  - Client: Mac OSX High Sierra / Server: Ubuntu 16.04
  - Anaconda Python 3.6
  - jupyterlab 0.30.6
  - jupyterlab-launcher 0.6.0

**Comment by blink1073** [comment]
Hi @j-min, this is being addressed in #3363.
