### ISSUE TITLE
Duplicated entries in tab-completion list

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#3365]
Not sure if this is a `jupyterlab` or a `notebook` issue:

![image](https://user-images.githubusercontent.com/881019/33923263-dfca4170-e01b-11e7-90b3-e0c2f9e474da.png)

![image](https://user-images.githubusercontent.com/881019/33923254-c77d08be-e01b-11e7-924e-b5e14b87efee.png)

**Comment by blink1073** [comment]
Confirmed that is specific to JupyterLab, thanks!

**Comment by akhmerov** [comment]
Interestingly after upgrading to 0.31 I now observe the reverse: the entries are duplicated in the classic notebook! (luckily I've been using jupyterlab for some time)
