### ISSUE TITLE
Missing package data

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#3375]
We need staging/templates here: https://github.com/jupyterlab/jupyterlab/blob/master/setup.py#L39

**Comment by stonebig** [comment]
hi, just a check, is this  problem I have on Jupyterlab-0.30.6 solved by this #3382 ?

![jupyterlabindex](https://user-images.githubusercontent.com/4312421/34053385-f2840376-e1c6-11e7-8611-598bef962de8.PNG)

**Comment by blink1073** [comment]
Yep, this should fix that problem.
