### ISSUE TITLE
Support for Notebook Metadata and Persistence

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyterlab/jupyterlab#3379]
Versions:

```
jupyter                   1.0.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.30.6           py36h2f9c1c0_0  
jupyterlab_launcher       0.6.0                    py36_0
```

I am fumbling with notebook metadata in Jupyter Lab.

I have a notebook file (`ipynb`) with the following metadata:

```
...
 "metadata": {
  "checkpoint_variable_names": [
   "check_00",
   "check_01",
   "check_02"
  ],
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
...
```

When the extension I develop is activated it does:

```
function activate_variable_inspect(app: JupyterLab, notebook_tracker: INotebookTracker) {
    // react on notebook tracker changes
    notebook_tracker.currentChanged.connect(() => {
        let context = new StatePattern.Context();  // my own stuff
        context.client_session = notebook_tracker.currentWidget.session;

        context.checkpoint_variable_names = notebook_tracker
            .currentWidget.notebook.model.metadata.get("checkpoint_variable_names") as string[];

        if (context.checkpoint_variable_names === undefined ||
            typeof context.checkpoint_variable_names === undefined) {
            console.log("WARNING: no checkpoint_variable_names set in notebook metadata");
        }
        ...
```

The warning message is logged to console when the extension starts.
However, I can set the metadata in code when I do the following:

```
function activate_variable_inspect(app: JupyterLab, notebook_tracker: INotebookTracker) {
    // react on notebook tracker changes
    notebook_tracker.currentChanged.connect(() => {
        let context = new StatePattern.Context();  // my own stuff
        context.client_session = notebook_tracker.currentWidget.session;
        notebook_tracker.currentWidget.notebook.model.metadata.set(
            "checkpoint_variable_names",
            [
                "check_00",
                "check_01",
                "check_02"
            ]
        );

        context.checkpoint_variable_names = notebook_tracker
            .currentWidget.notebook.model.metadata.get("checkpoint_variable_names") as string[];

        if (context.checkpoint_variable_names === undefined ||
            typeof context.checkpoint_variable_names === undefined) {
            console.log("WARNING: no checkpoint_variable_names set in notebook metadata");
        }
```

Then the warning is not logged to console. So it seems internally, inside the model metadata already works.

This seems to mean, that currently metadata from the notebook file is ignored, but the model supports setting it in code. I also checked, if the stuff I set in code is available in the JSON of the notebook file, by opening the notebook in Jupyter Lab with right click open with editor or open with JSON.

If this is correct, I guess this issue would be a feature request to add support for _metadata from the notebook file itself_.

Jupyter Lab already seems to support _cell metadata_, in the GUI, when a cell is selected (in the tab for the cell in the left area of app shell).

**Comment by blink1073** [comment]
Hi @ZelphirKaltstahl, I verified that the metadata is getting into the file after saving:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/2096628/34040421-3c34e1de-e159-11e7-8abb-f2a82c68ac65.png">

We're tracking the UI for editing notebook metadata in #1308.

Note: you may want to add:

```typescript
      if (!notebook_tracker.currentWidget) {
        return;
      }
```

**Comment by ZelphirKaltstahl** [comment]
Oh that might be it. Maybe my extension is reacting too early on some state change of notebook tracker and then the metadata is _not yet_ available, but later would be. I'll try soon, thanks for the suggestion.

**Comment by ZelphirKaltstahl** [comment]
@blink1073 I could not get it to work yet. Here is the code I am using, maybe I am still overlooking something:

    // =======
    // IMPORTS
    // =======
    import {
        JupyterLab,
        JupyterLabPlugin
    } from '@jupyterlab/application';

    import {
        IClientSession
    } from '@jupyterlab/apputils';

    import {
        INotebookTracker
    } from '@jupyterlab/notebook';

    import {
        StatePattern
    } from "./state";

    import {
        KernelMessage
    } from '@jupyterlab/services';

    // ======
    // PLUGIN
    // ======
    function activate_variable_inspect(app: JupyterLab, notebook_tracker: INotebookTracker) {
        // react on notebook tracker changes
        notebook_tracker.currentChanged.connect(() => {
            if (!notebook_tracker.currentWidget) {
                return;
            }

            let context = new StatePattern.Context();
            // set the session when the notebook changes (always up to date session)
            context.client_session = notebook_tracker.currentWidget.session;

            // setting test values for metadata
            notebook_tracker
                .currentWidget.notebook.model.metadata.set("checkpoint_variable_names", [
                    "check_00",
                    "check_01",
                    "check_02",
                    "check_03"
                ]);

            context.checkpoint_variable_names = notebook_tracker
                .currentWidget
                .notebook
                .model
                .metadata
                .get("checkpoint_variable_names") as string[];

            if (context.checkpoint_variable_names === undefined ||
                typeof context.checkpoint_variable_names === undefined) {
                console.log("WARNING: no checkpoint_variable_names set in notebook metadata");
            }

            context.client_session.iopubMessage.connect(
                (session: IClientSession, msg: KernelMessage.IMessage) => {
                    console.log("===================================================");
                    console.log("MESSAGE:", msg);

                    // Request an update to the state and all run all the actions which the states define.
                    // These actions might be none, if the message is not one we want to react to.
                    context.request(msg);
                }
            );
        });
    }

    const variable_inspect_plugin: JupyterLabPlugin<void> = {
        activate: activate_variable_inspect,
        id: "jupyter.extensions.variable-inspect-extension",
        requires: [
            INotebookTracker
        ],
        autoStart: true
    };

    // ========
    // FINALIZE
    // ========
    const plugins: JupyterLabPlugin<any>[] = [variable_inspect_plugin];
    export default plugins;

When I run it (`jupyter labextension install . && jupyter lab`) and then open the notebook file with "JSON", I still cannot see the variables being set.

Do I need more dependencies in the `requires` array? Maybe the extension is loaded too early?

**Comment by ZelphirKaltstahl** [comment]
Or maybe you can share the code with which you tested this and I can try to learn from that?

**Comment by blink1073** [comment]
I didn't save the code.  It was the same as the most recent one you posted but without the use of the `context` variable.  Your `requires` looks fine.  When you say that you cannot see the variables being set, do you mean the `check_00` etc. names in the notebook metadata?

**Comment by ZelphirKaltstahl** [comment]
The steps I do to see any changes:

1. I have a notebook, which has already some variables in its metadata when it is opened:

       "metadata": {
           "checkpoint_variable_names": [
               "check_00",
               "check_01",
               "check_02"
           ],
           ...
       }

2. I install the extension and start Jupyter Lab:

    jupyter labextension install . && jupyter lab

3. Jupyter Lab opens in a new tab in the browser
4. The notebook will be shown, because it was opened the last time I ran the extension.
5. The extension runs (I see many console outputs which can only happen when the extension runs).
6. I right click the notebook file in the file browser in Jupyter Lab (in the app.shell left area) and choose either open with JSON or open with editor.
7. In the newly opened JSON viewer or editor I do not see the variables, which my extension set in the code I posted above using:

       notebook_tracker
           .currentWidget.notebook.model.metadata.set("checkpoint_variable_names", [
               "check_000",
               "check_001",
               "check_002",
               "check_003"
           ]
       );

I can also comment out the `context` thingy, but it does not matter, as no other part in the code ever does any setting of notebook metadata. It is the entry point of the functionality that uses the values read from the metadata.

**Comment by blink1073** [comment]
Hi @ZelphirKaltstahl, the issue was that the `context` was not yet ready.  Note that we will be fixing this in the future so that the widget will not be created until the context is done loading (it won't have a `ready` Promise).  Here's the working code (I spliced it into the notebook extension for testing):

```diff
diff --git a/packages/notebook-extension/src/index.ts b/packages/notebook-extension/src/index.ts
index 9bd5519..ff8ae33 100644
--- a/packages/notebook-extension/src/index.ts
+++ b/packages/notebook-extension/src/index.ts
@@ -317,10 +317,40 @@ const tools: JupyterLabPlugin<ICellTools> = {
 };


+function activate_variable_inspect(app: JupyterLab, notebook_tracker: INotebookTracker) {
+    // react on notebook tracker changes
+    notebook_tracker.currentChanged.connect(() => {
+        if (!notebook_tracker.currentWidget) {
+            return;
+        }
+
+        // setting test values for metadata
+        notebook_tracker.currentWidget.context.ready.then(() => {
+          notebook_tracker
+              .currentWidget.notebook.model.metadata.set("checkpoint_variable_names", [
+                  "check_00",
+                  "check_01",
+                  "check_02",
+                  "check_03"
+              ]);

silvester: ~/workspace/jupyter/lab (zelphir-example) 4
$ gd
diff --git a/packages/notebook-extension/src/index.ts b/packages/notebook-extension/src/index.ts
index 9bd5519..ff8ae33 100644
--- a/packages/notebook-extension/src/index.ts
+++ b/packages/notebook-extension/src/index.ts
@@ -317,10 +317,40 @@ const tools: JupyterLabPlugin<ICellTools> = {
 };


+function activate_variable_inspect(app: JupyterLab, notebook_tracker: INotebookTracker) {
+    // react on notebook tracker changes
+    notebook_tracker.currentChanged.connect(() => {
+        if (!notebook_tracker.currentWidget) {
+            return;
+        }
+
+        // setting test values for metadata
+        notebook_tracker.currentWidget.context.ready.then(() => {
+          notebook_tracker
+              .currentWidget.notebook.model.metadata.set("checkpoint_variable_names", [
+                  "check_00",
+                  "check_01",
+                  "check_02",
+                  "check_03"
+              ]);
+        });
+    });
+}
+
+const variable_inspect_plugin: JupyterLabPlugin<void> = {
+    activate: activate_variable_inspect,
+    id: "jupyter.extensions.variable-inspect-extension",
+    requires: [
+        INotebookTracker
+    ],
+    autoStart: true
+};
+
+
 /**
  * Export the plugins as default.
  */
-const plugins: JupyterLabPlugin<any>[] = [factory, tracker, tools];
+const plugins: JupyterLabPlugin<any>[] = [factory, tracker, tools, variable_inspect_plugin];
 export default plugins;
```

**Comment by ZelphirKaltstahl** [comment]
Thank you for helping out on yet another thing that came up!
Also good to know that in this matter there will be a change in the future and that the `.ready` `Promise` might/will be gone, so that I can prepare for that change or already have a clue what could be wrong in my code, when I update to the next version.
Outstanding!
