### ISSUE TITLE
jupyterlab: after working for ~1 hour:  No such file or directory:

### ISSUE THREAD

**Issue by Casyfill** [jupyterlab/jupyterlab#3381]
I am working in jupyterlab, and after 1 to 2 hours of working seamlessly it throws "can't find the directory" in the browser

<img width="1336" alt="screen shot 2017-12-14 at 15 53 41" src="https://user-images.githubusercontent.com/2675621/34013828-00dfc8f0-e0e7-11e7-90ce-682134b2916f.png">

and warnings
```
[W 15:46:53.611 LabApp] No such file or directory:
[W 15:46:53.612 LabApp] 404 GET /api/contents/?content=1&1513284413582 (::1) 2.97ms referer=http://localhost:8888/lab
[W 15:46:53.614 LabApp] 404 GET /api/con
```
on the terminal.

after halting the server, I keep getting `fatal: Unable to read current working directory: No such file or directory` for every operation in the same git repo. 

That message disappears after `cd ..; cd my_folder; `.

Note: I have no idea if that is relevant, but this whole folder is connected to the google drive file Stream service.

**Comment by Casyfill** [comment]
jupyter-client            5.1.0                     <pip>
jupyter-core              4.4.0                     <pip>
jupyterlab                0.30.1                    <pip>
jupyterlab-launcher       0.6.0                     <pip>

**Comment by blink1073** [comment]
Hi @Casyfill, I'm not sure what could be causing this one.  Have you used the previous Jupyter Notebook before with the same Google Stream service?

**Comment by Casyfill** [comment]
No, unfortunately

 I had to switch both to jupyterlab and GD same week.

**Comment by jasongrout** [comment]
Assigning to @afshin and @ian-r-rose since they have more experience with Google things.

**Comment by afshin** [comment]
I experienced a related issue when I had an open session using the Google realtime API and after some time (which if I recall, was also ~1 hour) the Google API would start generating errors about not finding the document/directory I had browsed to in Google Drive. I suspect this is a limitation (whether intentional or unintentional, I'm not sure) of the Google APIs.

**Comment by jasongrout** [comment]
@Casyfill - is this still an issue for you?

**Comment by jasongrout** [comment]
Okay, thanks!
