### ISSUE TITLE
JupyterLab builds and runs in dev-mode but generates extension errors in production mode.

### ISSUE THREAD

**Issue by athornton** [jupyterlab/jupyterlab#3386]
Installing jupyterlab works OK: `pip3 install https://github.com/jupyterlab/jupyterlab/zipball/master`

However, at runtime, CSS is not correctly loaded (what text appears, appears unstyled, and window decorations, such as the "OK" button in dialogs, do not appear), and there is the following message in the Javascript console: `thememanager.js:166 Stylesheet failed to load: /lab/api/themes/@jupyterlab/theme-light-extension/index.css`

This suggests to me that the themes are not being correctly packed into the zipball, which in turn suggests that they're being left out during the build process at some point.

`pip install -e .` in the checked-out source directory is reported to work fine by @afshin .

**Comment by afshin** [comment]
I looked more into this: it seems `--dev-mode` works fine, but production mode is exhibiting broken extensions at runtime irrespective of how I install.
