### ISSUE TITLE
Visual indicator when uploading file by dragging onto file browser

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3390]
We should have a visual indicator on the file browser (probably the typical thick blue border) when you drag a file there to upload.

**Comment by ellisonbg** [comment]
@blink1073 I can do the visual styling for this, but the drag logic for the filebrowser is a bit subtle. Can you write the code that adds a CSS class when a user drops a file onto the filebrowser to upload and I can style it?

**Comment by blink1073** [comment]
Will do

**Comment by blink1073** [comment]
Fixed by #3426.
