### ISSUE TITLE
Missing tab border for text editor documents

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3394]
Text editor is missing the usual top tab border:

this also shows a grey border at the bottom of the tab too:

![screen shot 2017-12-15 at 5 56 45 pm](https://user-images.githubusercontent.com/27600/34065657-6a747c72-e1c1-11e7-828c-5876d44174f6.png)

**Comment by ian-r-rose** [comment]
I think this was changed because the `:before` element was causing lots of CodeMirror's sizing calculations to be incorrect (cf. #2993, #3188). The fix was in #3219, and can probably be changed to better match the other tab styling.
