### ISSUE TITLE
Watch for dev mode doesn't pickup changes to the themes

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3405]
I am doing development on the themes and CSS using `jupyter lab --dev-mode --watch`. Changes to most files are picked up, but changes to the theme are not picked up. I am not sure if this is a lack of a rebuild or related to something else like browser caching.

**Comment by blink1073** [comment]
As in, a refresh of the page gives stale files even when clearing the browser cache?

**Comment by blink1073** [comment]
I'm not sure we can do anything about the browser caching those files because they are specified as relative CSS paths in the static CSS files.   I am pretty sure that in watch mode we are telling the server not to cache those files, unless I messed something up there.

**Comment by ian-r-rose** [comment]
I have also seen flakiness in watch mode, unrelated to any browser caching. Sometimes the watcher just doesn't seem to pick up changes in the TS source files. Triggering a manual rebuild in the relevant subpackage will then trigger webpack correctly.

This has been hard to reproduce, though, so I have been ubable to put a finger on why the watcher fails. Restarting the watch-mode server seems to reset things.

**Comment by ellisonbg** [comment]
OK, closing...
