### ISSUE TITLE
holoviews showing nothing in JupyterLab

### ISSUE THREAD

**Issue by maajdl** [jupyterlab/jupyterlab#3409]
Hello,

I have been using Holoviews/Bokeh since several months in Jupyter notebooks.
I just tried JupyterLab and observed that the Holoviews pictures never show up in JupyterLab.

Would you have a suggestion?
Should I consider that a JupyterLab issue or an Holoviews issue?
Should anything running well in Jupyter Notebooks also work well in JupyterLab?

Thanks,

Michel

**Comment by ellisonbg** [comment]
IIRC, there was a separate Bokeh extension for JupyterLab you would need to install and enable:

https://github.com/bokeh/jupyterlab_bokeh

**Comment by ellisonbg** [comment]
I would follow up over there, closing as question - but feel free to ping us again if you need further help.
