### ISSUE TITLE
UI: Raw cell usage

### ISSUE THREAD

**Issue by AbdealiLoKo** [jupyterlab/jupyterlab#3419]
I had created an issue a while back about Creating new cell types. I was told I should create a new file format for more cell types as other systems like nbviewer, nbpresent, etc won't be able to handle new cell types. 

Currently there is a code, markdown and raw cell type. 
My question is what exactly is raw used for - I have not seen anyone use it.

If raw is not as often used as markdown and code, why keep it here in the same UI space? It should be in commands if it is rarely used

My aim here is mainly that the UI can maybe be simplified if we remove Raw cell type from the main tab bar.

**Comment by blink1073** [comment]
Hi @AbdealiJK, the raw cell intent is described [here](https://nbformat.readthedocs.io/en/latest/format_description.html#raw-nbconvert-cells).  I see that we are missing the [unrecognized](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/cell.js#L725) cell type from the classic notebook.  I opened #3420 to track that.
