### ISSUE TITLE
@jupyterlab/rendermime has no export member RenderMimeRegistry

### ISSUE THREAD

**Issue by fridgerator** [jupyterlab/jupyterlab#3440]
Trying to run the examples notebook folder and getting the following errors:

```
src/index.ts(42,3): error TS2305: Module '"/jupyterlab/examples/notebook/node_modules/@jupyterlab/rendermime/lib/index"' has no exported member 'RenderMimeRegistry'.
src/index.ts(42,23): error TS2305: Module '"/jupyterlab/examples/notebook/node_modules/@jupyterlab/rendermime/lib/index"' has no exported member 'standardRendererFactories'.
```

Python 3.6.3
Node 8.9.0

Any ideas?

**Comment by blink1073** [comment]
Hi @fridgerator, have you copied the directory to another location on your system?  That only works on tagged versions of JupyterLab because we haven't yet published the JavaScript packages.  E.g. `git checkout v0.30.6` and then copy the folder.  This will be less of a problem when our APIs settle down.

**Comment by fridgerator** [comment]
thanks @blink1073 

I am able to follow the example by checking out commit 8921437 (when npm packages were tagged with 0.13.0)

**Comment by fridgerator** [comment]
FWIW - At LI-COR Biosciences we have built ecosystem data analysis software, and I am looking into jupyter notebook integration:  https://www.licor.com/alexandria_project/

I see that the jupyterlab API isn't yet stable, however it seems to have all of the pieces that I need so far.

Forgive me if this question has already been asked a million times, but is a beta release expected soon?

**Comment by blink1073** [comment]
Good timing, we're releasing [tomorrow](https://github.com/jupyterlab/jupyterlab/issues/3299) :smile:

**Comment by ian-r-rose** [comment]
We've been through several releases since then, so this issue is probably resolved. Please let us know if it is not @fridgerator and we can reopen.
