### ISSUE TITLE
Cannot quit pdb

### ISSUE THREAD

**Issue by alanhdu** [jupyterlab/jupyterlab#3443]
With `jupyterlab==0.30.6` and Python 3.6, I cannot figure out how to quit the `%pdb` magic when an exception happens. When I type `quit` or `exit`, I just see an `<IPython.core.autocall.ZMQExitAutocall object at 0x7fc10a5c2668>` printed out instead of the debugger actually quitting:

![image](https://user-images.githubusercontent.com/1914111/34232971-e0b8bd2e-e5b0-11e7-818e-b3e1edb6198f.png)

**Comment by blink1073** [comment]
Hi @alanhdu, does the above happen when using the classic notebook as well for you?  I just tried on my local machine and it works as expected.  

<img width="844" alt="image" src="https://user-images.githubusercontent.com/2096628/34248269-fcd8f056-e5fa-11e7-930a-8a0d3927ec4a.png">

**Comment by alanhdu** [comment]
Hm.. you're right. I think this is actually a bug with a separate package I'm using. Closing in favor of https://github.com/antocuni/pdb/issues/76.

**Comment by blink1073** [comment]
No worries, cheers!
