### ISSUE TITLE
Scratch pad in side panel for line-by-line execution

### ISSUE THREAD

**Issue by BoPeng** [jupyterlab/jupyterlab#3453]
This topic is split from #2815

The basic execution units of Jupyter are cells so there is no easy way to execute, tweak, and re-execute pieces of the code for debugging purposes ([StackOverflow Question](https://stackoverflow.com/questions/38320837/how-can-i-execute-the-code-line-by-line-in-jupyter-notebook), [Jupyter Issue 1094](https://github.com/jupyter/notebook/issues/1094)). The problem here is not how to execute parts of the cell content (which is almost trivial to implement), but where to execute the code and display the output. There is a [scratchpad](https://github.com/minrk/nbextension-scratchpad) extension to execute scratch cells but this is still less convenient than the line-by-line execution mode in other IDEs.

Given that JupyterLab already has a side panel, I would propose that we integrate a scratchpad to the side panel and provide a shortcut for line by line execution. The following figure demonstrates how this feature works in [SoS Notebook](https://vatlab.github.io/sos-docs/):

![line by line execution](https://vatlab.github.io/sos-docs/doc/media/step_through.gif)

This feature should work for other kernels because no kernel-level change is needed. SoS Notebook uses [shortcut Ctrl-Shift-Enter](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/kernel.js#L1281) to send current line or selected text to side panel for execution although [its implementation](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/kernel.js#L1424) has multi-kernel and auto-preview support.

**Comment by ellisonbg** [comment]
Yes, this type of usage case is important. The way we are handling it in JupyterLab right now is through the Code Console, which is essentially this type of transient scratchpad or playground. You can either start a Code Console using the Launcher:

![jan-05-2018 07-17-04](https://user-images.githubusercontent.com/27600/34615170-c52a0376-f1e8-11e7-94fd-b1de388cc3fd.gif)


 or using the kernel of a notebook:

![jan-05-2018 07-18-26](https://user-images.githubusercontent.com/27600/34615176-ca6f0aac-f1e8-11e7-9e07-3b0f41d3528f.gif)

**Comment by dongbosong** [comment]
But the Code Consoles are not linked to the main notebook, right? I mean, in the [scratchpad extension](https://github.com/minrk/nbextension-scratchpad) and in SoS Notebook, the scratch cell shares the kernel with the notebook so that it can execute statements from the main notebook. When the main notebook has

```
# main notebook
a = 'long_statement'
```
the Code Console has to repeat the statement to inspect a
```
a = 'long_statement'
a
```
while the scratch cell can simply run
```
a
```
This makes a big difference in the usability of Code Consoles without even consider the trouble to copy/paste code from notebook to Code Consoles.

**Comment by BoPeng** [comment]
But the Code Consoles are not linked to the main notebook, right? I mean, in the [scratchpad extension](https://github.com/minrk/nbextension-scratchpad) and in SoS Notebook, the scratch cell shares the kernel with the notebook so that it can execute statements from the main notebook. When the main notebook has

```
# main notebook
a = 'long_statement'
```
the Code Console has to repeat the statement to inspect a
```
a = 'long_statement'
a
```
while the scratch cell can simply run
```
a
```
This makes a big difference in the usability of Code Consoles without even consider the trouble to copy/paste code from notebook to Code Consoles.

**Comment by ellisonbg** [comment]
The Code Console can share the kernel with the Notebook. The change kernel dialog in JupyterLab for any document or activity allows you to pick kernels from any other document or activity:

![screen shot 2018-01-05 at 10 00 48 am](https://user-images.githubusercontent.com/27600/34621788-5cae86de-f1ff-11e7-9d9b-116f9e15b75a.png)

When you use the "Create Console for Notebook" it automatically sets up a shared kernel.

**Comment by BoPeng** [comment]
I see. Then a shortcut is the only missing part. How about a shortcut for

1. Creating a code console with shared kernel if not already exist. 
2. Display code console if hidden (side by side with notebook?)
3. Sending current line or selected text to code console for evaluation.

**Comment by idoDavid** [comment]
@BoPeng @ellisonbg  A shortcut that will do the 1,2,3 above would be great!

**Comment by BoPeng** [comment]
Already implemented.
