### ISSUE TITLE
Theme implementation discussion for 1.0

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3458]
We are shipping the beta soon, but there are number of ideas that have come up for the theming implementation that we want to consider for 1.0. This issue is designed as a starting point for that discussion. Here are some of the ideas (please add more):

* Exposing some of the theme CSS variables as JupyterLab settings. There are some CSS variables that users might want to change often enough that we don't want to have them go create a new theme. This would include: content/ui/code font sizes and font families.
* Add a variable that different parts of the code base can use to see if the current theme is dark or light. There are some extensions and renderers that can't style using CSS variables (GeoJSON map sets, some react components). Individual themes would need to be able to set this variable and then other parts of the code base would need to be able to read that value.
* Integrate or better separate the JupyterLab theme from the CodeMirror theme. CodeMirror has its own theme that includes things like syntax highlighting and other UI elements (background, border, gutter, etc). At the same time, we often need to change things like the border and background dynamically using Jupyter theme variables. We need to figure out which things are styled which way and clean that up.

See also older and vague issues #2886 #2888 as well.

**Comment by dlukes** [comment]
If I may add to this: I think it would be nice if the Text Editor Theme setting also affected the CodeMirror instances representing Notebook and Console cells :)
