### ISSUE TITLE
Tooltip text is not present for new Launcher button.

### ISSUE THREAD

**Issue by apsknight** [jupyterlab/jupyterlab#3459]
In Files tab, New Folder, Upload File(s) and Refresh File List button are showing tooltip text on hovering over them but New Launcher is not showing any tooltip text.

![peek 2017-12-21 21-08](https://user-images.githubusercontent.com/19551774/34288299-658e4796-e712-11e7-86d5-5cea32911757.gif)

On inspecting the interface, I found content of `title` attribute in New Launcher's button tag is missing. 

![screenshot from 2017-12-22 12-25-15](https://user-images.githubusercontent.com/19551774/34288986-44cb6d00-e716-11e7-8525-ed8091b7c502.png)

Similarly tooltip text for Home button below New Launcher button is also missing.

**Comment by apsknight** [comment]
@blink1073 Can you please point to the file where I have to make changes for fixing this issue.

**Comment by blink1073** [comment]
The launcher button is added [here](https://github.com/jupyterlab/jupyterlab/blob/584e755589920350f3a64bffded0596b47bdb783/packages/filebrowser-extension/src/index.ts#L143), and the home crumb title should be set [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/filebrowser/src/crumbs.ts#L337).
