### ISSUE TITLE
info fsevents@1.1.3: The platform "win32" is incompatible with this module.

### ISSUE THREAD

**Issue by stonebig** [jupyterlab/jupyterlab#3462]
Hi dear jupyterlab,

I have some messages, that I'm not sure how to handle.
As it's pre-beta, maybe it's resolved or not a problem. just making you aware

````
node C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.0\python-3.6.4.amd64\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
[1/2] ⠠ canvas: gyp info using node@6.11.5 | win32 | x64
[2/2] ⠠ jupyter-matplotlib
[-/2] ⠐ waiting...
[-/2] ⠐ waiting...
warning Error running install script for optional dependency: "C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\share\\jupyter\\lab\\staging\\node_modules\\canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\share\\jupyter\\lab\\staging\\node_modules\\canvas
Output:
C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\share\\jupyter\\lab\\staging\\node_modules\\canvas>if not defined npm_config_node_gyp (node \"C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\tools\\n\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.11.5 | win32 | x64
gyp ERR! configure error 
gyp ERR! stack Error: Python executable \"C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\python-3.6.4.amd64\\python.EXE\" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\tools\\n\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:454:14)
gyp ERR! stack     at C:\\WinPython\\basedir36\\buildQt5\\winpython-64bit-3.6.x.0\\tools\\n\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:189:7)
gyp ERR! stack     at emitTwo (events.js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command \"C:\\\\WinPython\\\\basedir36\\\\buildQt5\\\\winpython-64bit-3.6.x.0\\\\python-3.6.4.amd64\\\\..\\\\tools\\\\n\\\\node.exe\" \"C:\\\\WinPython\\\\basedir36\\\\buildQt5\\\\winpython-64bit-3.6.x.0\\\\tools\\\\n\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuisuccess Saved lockfile.
````

**Comment by blink1073** [comment]
Hi @stonebig, this is expected and can be ignored.  We can't yet ignore optional packages (in this case `canvas`) because of https://github.com/yarnpkg/yarn/issues/4876.

**Comment by stonebig** [comment]
with latest jupyterlab-0.31.1, node-gyp still needs to get implied, and is not python-3 compatible.

It's shots in the dark for me to figure out how to resolve this, without using Python-2.7.

https://github.com/ellisonbg/ipyleaflet/issues/93#issuecomment-357513473

**Comment by stonebig** [comment]
ok, I can get ipyleaflet and altair and ipympl (beta) working in jupyterlab, so case closed.

**Comment by vaish3737** [comment]
Hi ,
I am still facing this issue,please help me out.
C:\Users\vaish\Desktop\React\React-Native>yarn global add expo-cli
yarn global v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info @expo/traveling-fastlane-darwin@1.5.0: The platform "win32" is incompatible with this module.
info "@expo/traveling-fastlane-darwin@1.5.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-freebsd-ia32@2.2.8: The platform "win32" is incompatible with this module.
info "@expo/ngrok-bin-freebsd-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-freebsd-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-darwin-ia32@2.2.8: The platform "win32" is incompatible with this module.
info "@expo/ngrok-bin-darwin-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-darwin-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-freebsd-x64@2.2.8: The platform "win32" is incompatible with this module.
info "@expo/ngrok-bin-freebsd-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm64@2.2.8: The platform "win32" is incompatible with this module.
info "@expo/ngrok-bin-linux-arm64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm64@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-linux-x64@2.2.8: The platform "win32" is incompatible with this module.
info "@expo/ngrok-bin-linux-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm@2.2.8: The platform "win32" is incompatible with this module.
info "@expo/ngrok-bin-linux-arm@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-darwin-x64@2.2.8: The platform "win32" is incompatible with this module.
info "@expo/ngrok-bin-darwin-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-sunos-x64@2.2.8: The platform "win32" is incompatible with this module.
info "@expo/ngrok-bin-sunos-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: The CPU architecture "x64" is incompatible with this module.
info "@expo/ngrok-bin-win32-ia32@2.2.8-beta.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-ia32@2.2.8: The platform "win32" is incompatible with this module.
info "@expo/ngrok-bin-linux-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
[3/4] Linking dependencies...
[######################################--------------------------------------------------------------------] 6504/18263[######################################--------------------------------------------------------------------] 6605/18263[#[###########################################[#############[4/4] Building fresh packages...
success Installed "expo-cli@2.2.4" with binaries:
      - expo
      - expo-cli
Done in 73.31s.

C:\Users\vaish\Desktop\React\React-Native>expo init hel
'expo' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\vaish\Desktop\React\React-Native>expo -v
'expo' is not recognized as an internal or external command,
operable program or batch file.

**Comment by JosephBlackWn** [comment]
Hi
I was also bothered by this issue。
I am learning how to use the React，and I install the python2.7、yarn、nvm(manage the node with different version) 、andriod studio.
when I use command 'react-native init XXX', it also show this issue.

D:\reactProject>react-native init AwesomeProject
prompt: Directory AwesomeProject already exists. Continue?:  (no) yes
This will walk you through creating a new React Native project in D:\reactProjec
t\AwesomeProject
Using yarn v1.12.1
Installing react-native...
yarn add v1.12.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check.
Excluding it from installation.
error react-native@0.57.4: The engine "node" is incompatible with this module. E
xpected version ">=8.3". Got "6.14.4"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this comm
and.
{ Error: Command failed: yarn add react-native --exact
    at checkExecSyncError (child_process.js:473:13)
    at execSync (child_process.js:513:13)
    at run (D:\nvm\v6.14.4\node_modules\react-native-cli\index.js:294:5)
    at createProject (D:\nvm\v6.14.4\node_modules\react-native-cli\index.js:249:
3)
    at D:\nvm\v6.14.4\node_modules\react-native-cli\index.js:217:7
    at D:\nvm\v6.14.4\node_modules\react-native-cli\node_modules\prompt\lib\prom
pt.js:316:32
    at D:\nvm\v6.14.4\node_modules\react-native-cli\node_modules\async\lib\async
.js:142:25
    at assembler (D:\nvm\v6.14.4\node_modules\react-native-cli\node_modules\prom
pt\lib\prompt.js:313:9)
    at D:\nvm\v6.14.4\node_modules\react-native-cli\node_modules\prompt\lib\prom
pt.js:322:32
    at D:\nvm\v6.14.4\node_modules\react-native-cli\node_modules\prompt\lib\prom
pt.js:597:5
  error: null,
  cmd: 'yarn add react-native --exact',
  file: 'C:\\Windows\\system32\\cmd.exe',
  args:
   [ 'C:\\Windows\\system32\\cmd.exe',
     '/s',
     '/c',
     '"yarn add react-native --exact"' ],
  options:
   { stdio: [ [Object], [Object], [Object] ],
     shell: true,
     windowsVerbatimArguments: true,
     file: 'C:\\Windows\\system32\\cmd.exe',
     args:
      [ 'C:\\Windows\\system32\\cmd.exe',
        '/s',
        '/c',
        '"yarn add react-native --exact"' ],
     envPairs:
      [ 'ALLUSERSPROFILE=C:\\ProgramData',
        'ANDROID_HOME=D:\\Andriod\\Sdk',
        'APPDATA=C:\\Users\\Administrator\\AppData\\Roaming',
        'CommonProgramFiles=C:\\Program Files\\Common Files',
        'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
        'CommonProgramW6432=C:\\Program Files\\Common Files',
        'COMPUTERNAME=USER-20180915BD',
        'ComSpec=C:\\Windows\\system32\\cmd.exe',
        'FP_NO_HOST_CHECK=NO',
        'HOMEDRIVE=C:',
        'HOMEPATH=\\Users\\Administrator',
        'LOCALAPPDATA=C:\\Users\\Administrator\\AppData\\Local',
        'LOGONSERVER=\\\\USER-20180915BD',
        'NUMBER_OF_PROCESSORS=4',
        'NVM_HOME=D:\\nvm',
        'NVM_SYMLINK=d:\\nodejs',
        'OS=Windows_NT',
        'Path=D:\\Python27\\;D:\\Python27\\Scripts;C:\\Program Files (x86)\\NVID
IA Corporation\\PhysX\\Common;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\Sys
tem32\\Wbem;d:\\composer;D:\\HashiCorp\\Vagrant\\bin;d:\\Program Files\\Git\\cmd
;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\Windows
PowerShell\\v1.0\\;d:\\wamp\\bin\\php\\php7;D:\\nvm;d:\\nodejs;C:\\Users\\Admini
strator\\AppData\\Roaming\\Composer\\vendor\\bin;C:\\bin>echo @php "%~dp0compose
r.phar" %*>composer.bat;D:\\nvm;d:\\nodejs;D:\\Andriod\\Sdk;',
        'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
        'PROCESSOR_ARCHITECTURE=AMD64',
        'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 37 Stepping 5, GenuineIntel
',
        'PROCESSOR_LEVEL=6',
        'PROCESSOR_REVISION=2505',
        'ProgramData=C:\\ProgramData',
        'ProgramFiles=C:\\Program Files',
        'ProgramFiles(x86)=C:\\Program Files (x86)',
        'ProgramW6432=C:\\Program Files',
        'PROMPT=$P$G',
        'PSModulePath=C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\'
,
        'PUBLIC=C:\\Users\\Public',
        'SESSIONNAME=Console',
        'SystemDrive=C:',
        'SystemRoot=C:\\Windows',
        'TEMP=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
        'TMP=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
        'USERDOMAIN=USER-20180915BD',
        'USERNAME=Administrator',
        'USERPROFILE=C:\\Users\\Administrator',
        'VBOX_MSI_INSTALL_PATH=D:\\Program Files\\Oracle\\VirtualBox\\',
        'windir=C:\\Windows',
        'windows_tracing_flags=3',
        'windows_tracing_logfile=C:\\BVTBin\\Tests\\installpackage\\csilogfile.l
og',
        '_DFX_INSTALL_UNSIGNED_DRIVER=1' ] },
  envPairs:
   [ 'ALLUSERSPROFILE=C:\\ProgramData',
     'ANDROID_HOME=D:\\Andriod\\Sdk',
     'APPDATA=C:\\Users\\Administrator\\AppData\\Roaming',
     'CommonProgramFiles=C:\\Program Files\\Common Files',
     'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files',
     'CommonProgramW6432=C:\\Program Files\\Common Files',
     'COMPUTERNAME=USER-20180915BD',
     'ComSpec=C:\\Windows\\system32\\cmd.exe',
     'FP_NO_HOST_CHECK=NO',
     'HOMEDRIVE=C:',
     'HOMEPATH=\\Users\\Administrator',
     'LOCALAPPDATA=C:\\Users\\Administrator\\AppData\\Local',
     'LOGONSERVER=\\\\USER-20180915BD',
     'NUMBER_OF_PROCESSORS=4',
     'NVM_HOME=D:\\nvm',
     'NVM_SYMLINK=d:\\nodejs',
     'OS=Windows_NT',
     'Path=D:\\Python27\\;D:\\Python27\\Scripts;C:\\Program Files (x86)\\NVIDIA
Corporation\\PhysX\\Common;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System
32\\Wbem;d:\\composer;D:\\HashiCorp\\Vagrant\\bin;d:\\Program Files\\Git\\cmd;C:
\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\WindowsPow
erShell\\v1.0\\;d:\\wamp\\bin\\php\\php7;D:\\nvm;d:\\nodejs;C:\\Users\\Administr
ator\\AppData\\Roaming\\Composer\\vendor\\bin;C:\\bin>echo @php "%~dp0composer.p
har" %*>composer.bat;D:\\nvm;d:\\nodejs;D:\\Andriod\\Sdk;',
     'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
     'PROCESSOR_ARCHITECTURE=AMD64',
     'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 37 Stepping 5, GenuineIntel',
     'PROCESSOR_LEVEL=6',
     'PROCESSOR_REVISION=2505',
     'ProgramData=C:\\ProgramData',
     'ProgramFiles=C:\\Program Files',
     'ProgramFiles(x86)=C:\\Program Files (x86)',
     'ProgramW6432=C:\\Program Files',
     'PROMPT=$P$G',
     'PSModulePath=C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
     'PUBLIC=C:\\Users\\Public',
     'SESSIONNAME=Console',
     'SystemDrive=C:',
     'SystemRoot=C:\\Windows',
     'TEMP=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
     'TMP=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
     'USERDOMAIN=USER-20180915BD',
     'USERNAME=Administrator',
     'USERPROFILE=C:\\Users\\Administrator',
     'VBOX_MSI_INSTALL_PATH=D:\\Program Files\\Oracle\\VirtualBox\\',
     'windir=C:\\Windows',
     'windows_tracing_flags=3',
     'windows_tracing_logfile=C:\\BVTBin\\Tests\\installpackage\\csilogfile.log'
,
     '_DFX_INSTALL_UNSIGNED_DRIVER=1' ],
  stderr: null,
  stdout: null,
  pid: 8156,
  output: [ null, null, null ],
  signal: null,
  status: 1 }
Command `yarn add react-native --exact` failed.

Please help me to resolve this issue, Thank you very much

**Comment by blink1073** [comment]
Hi @JosephBlackWn, it looks like you need to update your version of node.  The relevant line is `error react-native@0.57.4: The engine "node" is incompatible with this module. E
xpected version ">=8.3". Got "6.14.4"`.

**Comment by vidartf** [comment]
I would also update to python3 for working with jupyterlab!

**Comment by stonebig** [comment]
node-gyp , supposed to be retired, requires python-2.7, so it's a pain to have it as a need, and a triple pain on windows

**Comment by stonebig** [comment]
is there a  hope not to need nodejs for rebuilding jupyterlab in the future ? or at least not to need nod-gyp ?

**Comment by blink1073** [comment]
For now we are stuck with nodejs as a build time requirement, cf https://github.com/jupyterlab/jupyterlab/issues/4439.  node-gyp is moving toward python3 compatibility: https://github.com/nodejs/node-gyp/pull/1571

**Comment by JosephBlackWn** [comment]
Yeah， I found this problem。but in the last of the question，Command 'yarn add react-native --exact' failed. I have tried my best to resolve it，but it still hint me。

I come from China, my English is not good, guys

在 2018-11-08 00:30:15，"Steven Silvester" <notifications@github.com> 写道：


Hi @JosephBlackWn, it looks like you need to update your version of node. The relevant line is error react-native@0.57.4: The engine "node" is incompatible with this module. E xpected version ">=8.3". Got "6.14.4".

**Comment by blink1073** [comment]
node 8+ download: https://nodejs.org

**Comment by JosephBlackWn** [comment]
Thanks guys

在 2018-11-09 23:01:18，"Steven Silvester" <notifications@github.com> 写道：


node 8+ download: https://nodejs.org

**Comment by eirnym** [comment]
@blink1073 it's not because nobody was interested

**Comment by youfoundkris** [comment]
It is the other way around. The module is not compatible with win32.

**Comment by JosephBlackWn** [comment]
Thanks，buddy

在 2018-11-26 23:42:45，"Kris Kater" <notifications@github.com> 写道：


It is the other way around. The module is not compatible with win32.

**Comment by nbaua** [comment]
P>yarn add @nestjs/graphql apollo-server-express graphql-tools graphql
yarn add v1.13.0
[1/4] Resolving packages...
warning @nestjs/graphql > ts-simple-ast@21.0.4: NOTICE: ts-simple-ast has been renamed to ts-morph and version reset to 1.0.0. Switch at your leisure...
[2/4] Fetching packages...
**info fsevents@1.2.7: The platform "win32" is incompatible with this module.**
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.

**Adding package always fails for fsevents with YARN** however works with NPM, what's the work around. I Love YARN but this kind of issues make me mad.
