### ISSUE TITLE
Add "Shutdown all Kernels" command and UI

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3467]
A common use case for the Running panel is to shutdown all kernels. We should provide a command to shutdown all kernels and:

* A "Shutdown all Kernel" menu item in the "Kernel Menu"
* A command palette entry
* A button to shutdown all kernels in the Running tab

**Comment by blink1073** [comment]
In light of #3470 making it easier to shut down sessions quickly and the need for design of the button in the running tab, I'd say we defer this until after the RC.
