### ISSUE TITLE
Make sure dialog buttons have tab order and 1 is focused

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3473]
I am finding that some of our dialogs don't have a tab order for the buttons and a default button isn't focused. We want to make sure that one button (the default or confirmation one) has focus when the dialog opens and that there is a sensible tab order.

**Comment by jasongrout** [comment]
Which dialogs? I looked at the code, and it seems that the default button should be getting focus unless the dialog options specify a different initial focus using `focusNodeSelector`:
https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/dialog.ts#L99
https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/dialog.ts#L215
https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/dialog.ts#L387

It does seem we don't explicitly handle the tab order, though we do implement a tab wraparound that wraps to the first input element: https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/dialog.ts#L273

**Comment by ellisonbg** [comment]
Moving to 1.0.

**Comment by ellisonbg** [comment]
Adding back to 1.0 as it may get fixed as I work on #6230.

**Comment by ellisonbg** [comment]
As far as I can tell, this is fixed now. It may have just been that we didn't have an indicator. Closing as fixed.
