### ISSUE TITLE
Run Selected Code menu item active even in a text file with no kernel

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3474]
On the current master, the Run Selected Code menu item is enabled even when I'm in a plain text file in the editor, with no kernel attached:

<img width="958" alt="screen shot 2017-12-23 at 7 53 44 am" src="https://user-images.githubusercontent.com/192614/34320385-84aeb3d2-e7b6-11e7-85d1-8c205b3066b3.png">

This is confusing if there is no way to run the code.

**Comment by jasongrout** [comment]
CC @ian-r-rose

**Comment by jasongrout** [comment]
I think it should be enabled only when a console is associated with the file.

This may require some changes to the menu framework, as it is about enabling/disabling a menu item on a per-document basis, rather than a per-document-type basis.

**Comment by jasongrout** [comment]
I don't think this is a blocker for the RC.

**Comment by ellisonbg** [comment]
Good catch, I agree that the RC can go out without this, but getting it into the final beta would be good.

**Comment by ian-r-rose** [comment]
I am on a plane right now, but can try to address this on the flight.
