### ISSUE TITLE
use console for editor autocompletion

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#3483]
I really enjoyed combining the editor with an associated console for a development workflow. In my view in combines the interactivity and the execution granularity of a notebook with a reproducibility of a script.

However the interactivity can be improved by a tighter integration between the two: auto-completion and help don't work at all from the code editor. Would it make sense to hook them to the same kernel?

**Comment by jasongrout** [comment]
From @ellisonbg at #3510:

> When an editor has a connected console, it should be  possible to enable tab completion in the file editor. I have a PR  working, but I ran into issues with the services/sessions/client session  APIs that made it more difficult than needed.

**Comment by jasongrout** [comment]
I can also imagine an editor *not* hooked up to a console using something like the Microsoft language server to provide static completion. Perhaps we offer two distinct modes for completion.

The console-based one is certainly easier to implement right now.
