### ISSUE TITLE
Cannot find template: "index.html" 304 GET /lab?

### ISSUE THREAD

**Issue by melihozbek** [jupyterlab/jupyterlab#3487]
When I run jupyter lab 0.30.6 with jupyter lab --debug,

Cannot find template: "index.html" 
In ""

displays in my Chrome browser (I'm using Chrome 62.0.3202.75), I can't run jupyter lab at all (jupyter notebook, on the other hand, runs fine). The terminal gives me this:

304 GET /lab? (IP ADDRESS) ...

Jupyterlab works absolutely fine with jupyterlab-launcher 0.6.0. When I upgrade it to 0.7, 0.8 or 0.9.1, I get the above error. What should I do?

Happy holidays!

**Comment by jasongrout** [comment]
JupyterLab 0.30.x is only compatible with jupyterlab_launcher 0.6.0 (see https://github.com/jupyterlab/jupyterlab/blob/0.30.x/setup.py#L117), so you're seeing the correct behavior - just downgrade to jupyterlab_launcher 0.6.0.

Or you can upgrade to the new JupyterLab 0.31RC with `pip install --pre jupyterlab`, which requires the latest jupyterlab_launcher.

**Comment by melihozbek** [comment]
Thanks Jason, that clarifies!

**Comment by black-snow** [comment]
`pip install --pre jupyterlab` did nothing for me.

**Comment by nicwolff** [comment]
Same, I'm getting this error 
```
Cannot find template: "index.html"

In "/Volumes/Data/Users/nwolff/Library/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/share/jupyter/lab/static"
```

**Comment by blink1073** [comment]
Hi @nicwolff, what does  `jupyter lab paths` show for the application directory?

**Comment by nicwolff** [comment]
Hmm,
```
/Volumes/Data/Users/nwolff/Library/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/share/jupyter/lab
```
so it appears to have installed it for the system Python, but then it looks for it in the current Python's tree? Symlinking the `jupyter` dir over into the 3.6.5_1 tree fixes it for me.

**Comment by blink1073** [comment]
Does `which pip` point to the 2.7 version?

**Comment by pmav99** [comment]
I am also getting this problem on ubuntu 18.04. 

- I create a virtualenv using `python -mvenv venv`
- I activate it with `source venv/bin/activate`
- I install jupyterlab ` pip install jupyterlab`

``` bash
$ python --version
Python 3.6.7

$ which python
/home/pmav99/venv/bin/python

$ pip --version
pip 9.0.1 from /home/pmav99/venv/lib/python3.6/site-packages (python 3.6)

$ which pip
/home/pmav99/venv/bin/pip

$ which jupyter
/home/pmav99/venv/bin/jupyter

$ jupyter --version
4.4.0

$ jupyter lab --version
0.35.4

$ jupyter lab paths
Application directory:   /home/pmav99/.config/jupyter/lab
User Settings directory: /home/pmav99/.config/jupyter/lab/user-settings
Workspaces directory: /home/pmav99/.config/jupyter/lab/workspaces

# these are from my ~/.zshrc
export IPYTHONDIR=${XDG_CONFIG_HOME:-$HOME/.config}/ipython
export JUPYTER_CONFIG_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/jupyter
export JUPYTERLAB_DIR=${JUPYTER_CONFIG_DIR}/lab/

$ tree -a ~/.config/jupyter
/home/pmav99/.config/jupyter
|-- lab
`-- migrated

1 directory, 1 file

```

The exact error is:
```
Cannot find template: "index.html"

In "/home/pmav99/.config/jupyter/lab/static"
```

**Comment by pmav99** [comment]
I just repeated the procedure on Archlinux and the problem is there too. To be more precise, I remove `~/.config/jupyter/lab` and I did use the exact same setup (i.e. virtualenv + pip install + same env variables). The only difference is the python version which is 3.7.2

Could it be that setting JUPYTERLAB_DIR is causing the issues?
