### ISSUE TITLE
Add saving of png image in the vega2 renderer

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3501]
The vega2 renderer in the classic notebook saves a png of the visualization in the notebook MIME bundle after it renders. This allows Altair/vegalite to show up on GitHub/nbviewer as png images. The code is already in the module, just commented out:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/vega2-extension/src/index.ts#L107

Just need to grab the png data and set it in the MIME bundle.

**Comment by ellisonbg** [comment]
@blink1073 what is the API for updating the MIME bundle without triggering rendering?

**Comment by blink1073** [comment]
IIRC changing the mime bundle has no effect on the cell until it is rerendered.
