### ISSUE TITLE
notebook cell aggressive focus prevents codemirror dialog focus

### ISSUE THREAD

**Issue by jwkvam** [jupyterlab/jupyterlab#3503]
With [jupyterlab_vim](https://github.com/jwkvam/jupyterlab_vim), code mirror dialogs never get focused. The dialogs appear when searching `/` or entering command line mode `:`. I appreciate the UX reason for disabling dialogs with default codemirror instances. I think they are expected in vim mode. For example searching is useful for navigating code and command line mode can be used for many things like search and replace and saving notebooks.

I don't think this issue affects vanilla JupyterLab.

Maybe I can try disabling some `_ensureFocus` calls in https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook/src/widget.ts#L1123?

**Comment by blink1073** [comment]
Thanks for raising this!  It may take a combination of scoping when to call that method and a better check of what to focus in that method.
