### ISSUE TITLE
Add completer support to the file editor

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3510]
When an editor has a connected console, it should be possible to enable tab completion in the file editor. I have a PR working, but I ran into issues with the services/sessions/client session APIs that made it more difficult than needed. 

@blink1073 @afshin

**Comment by ellisonbg** [comment]
The actual code was really simple, but we may want to refactor some of the underlying session/client session APIs before we land it.

**Comment by akhmerov** [comment]
Related (duplicate) issue with fewer technical details: #3483.

**Comment by jasongrout** [comment]
Closing as a duplicate of #3483.
