### ISSUE TITLE
Add data connector to complete based on tokens in a text editor

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3511]
Right now our completer uses a data connector to connect to a kernel to perform all completions. This approach should be combined with another data connector that grabs all the tokens from the editor itself. This would enable completion to work within the text editor even with a kernel isn't connected. Also, the classic notebook does this.

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/5049
