### ISSUE TITLE
Rogue intransigent extension 

### ISSUE THREAD

**Issue by mpacer** [jupyterlab/jupyterlab#3522]
#I was working with @ian-r-rose on the jupyterlab-latex extension, and in the course of attempting to debug it, we attempted to link to the extension in a number of ways.

Most notably, we used a number of methods including 
- `jlpm install && jlpm run build && jupyterlab labextension install`
- `jupyterlab labextension link`
- `jlpm run add:sibling ../jupyterlab-latex` (from inside the jupyterlab repo)

We were running `jupyterlab` both with the public packages (`jupyter lab --watch` with `jlpm run watch` in `jupyterlab-latex`) and (`jupyter lab --dev-mode --watch` after running `jlpm run add:sibling ../jupyterlab-latex`).

Unfortunately, I've not been able to make the extension go away after many attempts in a variety of methods:
- `jlpm run clean` (in both jupyterlab-latex and jupyterlab)
- `jlpm run clean:slate` (in jupyterlab)
- `git clean -xfd` (in jupyterlab-latex)
- `git clean -xfd && jlpm install && jlpm run build` (in jupyterlab)
- `jupyterlab labextension uninstall @jupyterlab/latex`
- `jupyterlab labextension unlink @jupyterlab/latex`
- `jupyter_conf_search latex` → leading to me removing the `"jupyterlab_latex": true,` line

Even after all this I'm still getting the claim `@jupyterlab/latex` exists when I run `jupyter labextension list`

```
Build recommended:
    @jupyterlab/latex needs to be removed
    @jupyterlab/latex needs to be removed
```

and with `import ipdb; ipdb.set_trace()` inside the `jupyterlab/commands.py` `build_check`  I'm still seeing both

```
 'extensions': {'@jupyterlab/application-extension': '',
                ⋮
                '@jupyterlab/latex': 'lib/latex',
                ⋮
```

```
 'linkedPackages': {'@jupyterlab/latex': '/Users/mpacer/jupyter/jupyterlab-latex'},
```

and 
```
 'mimeExtensions': {'@jupyterlab/json-extension': '',
                    '@jupyterlab/latex': 'lib/pdf',
                    '@jupyterlab/pdf-extension': '',
                    ⋮
```

I'm going to keep trying to debug this but this is still way too complicated in order to figure this out. Happy to help figure out how to make this nicer.

**Comment by mpacer** [comment]
NB: the internal memory object inside the list thinks its still linked, even though it is no longer linked.

**Comment by mpacer** [comment]
@ian-r-rose just pointed out `jupyter lab build` and that worked.

I think that these steps and the nomenclature can be clarified though. At the least it would be good to be able to handle everything through a single command line interface (in this case probably `jlpm`) even if that just is an alias to `jupyter lab build`.

**Comment by blink1073** [comment]
Hi @mpacer, sorry about the confusion.  We can't use `jlpm` for both because it really is an alias to the `yarn` command and `jupyter lab build` is doing quite a bit more than calling `yarn build` (copying template files, etc.).  I think what we need here is a more explicit output than `Build Recommended`, perhaps ("Please run `jupyter lab build`")?

**Comment by ellisonbg** [comment]
@blink1073 do you think there are any beta related tasks on this one?

**Comment by blink1073** [comment]
We could update the output of `build_check` to include the language above.
