### ISSUE TITLE
Confusing naming of output/outputs

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3525]
From a technical perspective each cell has a list of outputs. but from the user's perspective, the cell has *output*. This confusion between the implementation and the user model is present in our menus/items.

I propose:

* The action to clear the outputs of a single cell be called "Clear Cell Output" (singular) in the context menu, command palette, and edit menu.
* The action to clear all the outputs of a notebook be called "Clear All Notebook Outputs" or "Clear All Cell Outputs" (plural) in all locations. I probably prefer the first of these as it is more that is operates on the entire notebook.

This proposed naming is consistent with the existing "Create New View for Output" (singular).

**Comment by jasongrout** [comment]
Makes sense to me.

**Comment by rgbkrk** [comment]
Great, I’ve been wondering the same thing! The individual “outputs” are more like the records of output.

**Comment by ian-r-rose** [comment]
There was a rationale behind the current naming, based on discussions with @jasongrout, @ellisonbg, and the Bloomberg UX team.
1. The pluralization for `Clear Cell Outputs` was due to the fact that it applies to the current cell selection (which may be multiple cells). Bonnie and Paddy indicated to us that users are generally comfortable with pluralized menu items being possibly only applicable to single items.
2. The `Clear Something`/`Clear All Something` is intended to be consistent with that same pattern that exists in several other places in the `File`, `Edit`, and `View` menus.

These things can be made more consistent between the command palette, menu, and context menus.

@rgbkrk I am not sure I fully understand your point. Can you elaborate?

**Comment by ian-r-rose** [comment]
An alternative would be to specify `Selected Cells` for most of the items in the `Edit` menu.

**Comment by rgbkrk** [comment]
I was ruminating on the format and what users experience. No action is necessary, as I was just delighted to see the issue (in a general sense, across Jupyter)

**Comment by ian-r-rose** [comment]
Ah, right. I agree that from the user's experience, there is no real need to refer to a list-of-outputs rather than a single output area.

In this case the pluralization was intended to refer to (possibly) multiple cells, though that has clearly been a bit confusing.

**Comment by ellisonbg** [comment]
@ian-r-rose yes, you make a good point about pluralization being used when 1 or more things can be affected. However, in this case, there is a sort of double pluralization ("cells outputs") conceptually.

Right now the Edit menu is "Clear Cell Outputs" (outputs is pluralized, implying multiple of those, but one cell) and the context menu item is "Clear Outputs" (sort of an abbreviation of that). The other items in the Edit menu are "? Cells" (cell itself is pluralized). 

Some possible resolutions:

* "Clear Cells Output" (pluralize cells to be consistent with rest of edit menu items)
* "Clear Selected Cells Output" (a more verbose form)

We do use the "Selected" prefix a lot in the Run and View menus, so maybe that is best? Although most of the Edit menu items are clear without it.

**Comment by ellisonbg** [comment]
We had a quick chat on appear.in and came up with the following plan:

Take the phrase "websites' URLs" - it is analogous to the situation we have. Website have one URL. In this type of construction website is plural possesive (websites') and URLs is plural as well.

Based on this we are going to go with "Clear Cells' Outputs" and "Clear All Cells' Outputs" in the menu items. We could add the "Selected" adjective to the first case, but we don't feel it is needed as the rest of the edit menu doesn't use it and the two items are adjacent in the menu so the difference is clear.

**Comment by ian-r-rose** [comment]
There are a bunch of other places where `Outputs` are referred to, such as the collapse/expand section in the `View` menu. This change would be somewhat inconsistent with those.

**Comment by jasongrout** [comment]
Thanks @ian-r-rose for reminding us of why the language is what it is. Brian, I think you're technically correct on using plural possessives to disambiguate between `Clear (Cell) (Outputs)` and `Clear (Cell Outputs)`, but I don't think I've seen possessives in any menu ever. Especially plural possessives.

Do we ever expose to the user that notion that there are multiple outputs in a single output area? I think we've tried to be fairly consistent about the idea that a code cell has a single "input" and a single "output" in our language.

**Comment by ian-r-rose** [comment]
Yeah, I am coming back around to using something more similar to the current language. A proliferation of plural possessives feels off...
