### ISSUE TITLE
Notebook context menu doesn't work on multiple selected cells

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3530]
Previously, you could select mutiple cells, and then right click to get a context menu that applies to all selected cells. You could use this to clear the outputs of a set of cells. This is no longer possible as the right click clear the selection.

There is at least some precedence in other UIs that context menus can be triggered and applied to selections. Excel is a good example of this.

@jasongrout @ian-r-rose maybe run this by the Bloomberg Design folks?

**Comment by ellisonbg** [comment]
Moving to 1.0.

**Comment by ellisonbg** [comment]
We have decided to do this, but its implementation is complex enough that we are going to do it after the beta.

**Comment by blink1073** [comment]
We're already adding a class to the notebook when there is more than one cell [selected](https://github.com/jupyterlab/jupyterlab/blob/837df44d210f30c36dcaaf837d1e7cc5979070e9/packages/notebook/src/widget.ts#L1225).  What I think it should be safe to simple remove this [lines](https://github.com/jupyterlab/jupyterlab/blob/837df44d210f30c36dcaaf837d1e7cc5979070e9/packages/notebook/src/widget.ts#L1384-L1391).

**Comment by ian-r-rose** [comment]
I agree. I almost removed them in #3540, but decided it was a bit out of scope.
