### ISSUE TITLE
Multiple active codemirror cells

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#3531]
Ran into a bug with codemirror focus this morning. Steps to reproduce:

1. Focus a cell (cell A).
2. Right-click on a *different* cell (cell B) to open a context menu.
3. Left click on that cell (cell B) to remove the context menu and focus it.

Both cell A and cell B will now have blinking cursors. With a bit of clicking around, I was able to get a third cell blinking as well.

![cursors](https://user-images.githubusercontent.com/5728311/34575864-fb598b82-f130-11e7-89c8-e00dba6e961f.gif)

**Comment by ian-r-rose** [comment]
This appears to be an issue with Firefox. Investigating further...

**Comment by ian-r-rose** [comment]
Okay, I could use the eyes of somebody who is a bit more familiar with the notebook focusing logic. 

It appears to me that, based on differences in how the native context menus behave, CodeMirror swallows right click events on Firefox, but not on Chrome: https://github.com/codemirror/CodeMirror/blob/2c741bd6742678f67e812307b2f78db4f4566d9d/src/input/TextareaInput.js#L330

This means that our mousedown handler in the notebook, `evtMouseDown`, is not being called for right-clicks within the cell CodeMirror widgets, and `_ensureFocus()` is not being called. This function is responsible for manually `blur`ing codemirror widgets, and so we can get multiple active cursors.

One solution may be to *also* call `_ensureFocus` on `focus`/`blur` events, which are not swallowed by CodeMirror. Some more eyes on this would be useful, though.

**Comment by blink1073** [comment]
We could instead manually blur the previous cell's editor when the active cell changes.  I'm not sure whether the blur event would be sufficient.  I seem to recall having problems with the event target on either Chrome or Firefox.

**Comment by ian-r-rose** [comment]
Yeah, that might work. I'll give it a shot.
The link I gave has an explicit difference in event propagation between Chrome and Firefox.

**Comment by ellisonbg** [comment]
We faced this issue in the classic notebook at some point and at the time, did observe differences in Firefox and Chrome. One that I would like to understand is if this problem has recently showed up, and if so, what was the underlying change that introduced it. I do think that we will end up with some sort of explicit blur, but it is likely more complicated than that.
