### ISSUE TITLE
Issues with cell context menus

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3539]
A recent PR turned off our own context menu when a user clicks in the CodeMirror element in a cell. For cells without output, this means it is really hard to get the per cell context menu (you have to click on the prompt area. However, right now, a right click on the prompt area (most of the time) also selects the text of the prompt, making the interaction awkward. I think we have two options:

* Re-enable the context menu on the CodeMirror part of cells.
* Disable user selectable text on the prompt.

I am a bit worried about not showing our own context menus on the CM element from the usability perspective. The mental model is that the context menu applies to the entire cell - I don't think users will distinguish between the input area and the rest of it.

**Comment by jasongrout** [comment]
We tentatively decided to *both* of the above points.

**Comment by blink1073** [comment]
I need to wait for #3540 to work on this since I'll be using the same events for adding/removing the classes.
