### ISSUE TITLE
Completer issues

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3543]
Great work on the completer!

I saw two issues using it in firefox on OS X:

![completer](https://user-images.githubusercontent.com/192614/34624558-a032489a-f20a-11e7-8d7d-f6164ed6a6d6.gif)

1. The metadata only shows up for the first few functions (the first time, only the first 5-6 items had the type metadata, for example). In the demo, you see about 2/3 way down, the metadata is missing. I also saw this in Chrome.

2. There is some problem with the horizontal scrollbar appearing, obscuring the last item in the box (which is often the selected item if you are scrolling down). This doesn't happen in Chrome. I did check my zoom level and it's at 100%.

**Comment by jasongrout** [comment]
> The metadata only shows up for the first few functions 

As I kept trying it over and over, it seemed more and more rows would have metadata.

**Comment by ellisonbg** [comment]
The first thing you are seeing is an issue on the kernel side. My understanding is that these completions are handled through jedi and that they make take a long time. I think this is handled through some sort of timeout on the kernel side, that it tries to compute the types for as many matches as possible within a certain interval. The ones that don't have the types listed are those. If you complete the same thing again though, more items will have the type information. So I don't know that there is anything to do on our side.

@Carreau can you confirm or clarify how the kernel handles these things?

For 2, that is a bug we someone should fix it. I can do it, but am working on the cell output scrolling right now. If someone else wants to tackle the horizontal scrollbar issue, please feel free :)

**Comment by ellisonbg** [comment]
Also, the width of the colors squares isn't right on FF - they should be squares

**Comment by jasongrout** [comment]
> If someone else wants to tackle the horizontal scrollbar issue, please feel free :)

I'll take a look right after trying workspaces...

**Comment by Carreau** [comment]
Yes Brian is right (partially). Some completion sources do not have
metadata, those will be forever blank. And as type inference is super slow
in Jedi (and lazy computed), we fetch as many as possible in 500ms. Jedi
caches what has been computed and this finds more on subsequent calls.

I have a plan to speed up inference (not super easy), and have a "compile
ahead of time" command for large libraries.

**Comment by ellisonbg** [comment]
Thanks @Carreau !!!

**Comment by jasongrout** [comment]
The rows of a completer are set to `display: table-row` and items are `display: table-cell`. From https://www.w3.org/TR/CSS2/tables.html#height-layout, it seems that setting the height shouldn't affect the actual height: 

> In CSS 2.1, the height of a cell box is the minimum height required by the content. The table cell's 'height' property can influence the height of the row (see above), but it does not increase the height of the cell box.

It may be best for us to use either min-height and min-width for sizes of the boxes, or to not try to use the table display model.

**Comment by jasongrout** [comment]
I just noticed in the code that we set `.innerHTML` with content from the server. Presumably that content is trusted because it's supposed to come from the kernel, but I think a defense-in-depth approach would still sanitize the content to make sure it only includes the noted `<mark>` tags, for example. c.f. https://github.com/jupyterlab/jupyterlab/blob/9dace8cea647cb2448e02dabd06e47040843370b/packages/completer/src/widget.ts#L709

**Comment by jasongrout** [comment]
At least part of the problem with firefox, the horizontal scroll bar, is illustrated by https://codepen.io/anon/pen/JMOGNL - 

```html
<div id='outer'>
  <div id='inner'>
a b c d e f g h i j k l m n 
a b c d e f g h i j k l m n 
a b c d e f g h i j k l m n 
a b c d e f g h i j k l m n 
a b c d e f g h i j k l m n 
  </div>
</div>
```

```css
#outer {
  border: 1px solid gray;
  width: auto;
  height: 100px;
  overflow: auto;
  position: fixed;
}

#inner {
  border: 3px solid red;
  width: 100px;
  height: 200px;
}
```
Here is Chrome:

<img width="139" alt="screen shot 2018-01-05 at 3 55 55 pm" src="https://user-images.githubusercontent.com/192614/34633411-f307ec2a-f230-11e7-84dc-19e3cfd7e8d3.png">

Here is Firefox:

<img width="123" alt="screen shot 2018-01-05 at 3 57 01 pm" src="https://user-images.githubusercontent.com/192614/34633456-1c55ca20-f231-11e7-82cd-b18548e4f28a.png">

Notice that in firefox the vertical scroll bar takes up horizontal space inside the outer box, so there is also a horizontal scrollbar, whereas in Chrome the vertical scroll bar is added outside the box so that the inner box still fits in the outer box.

**Comment by jasongrout** [comment]
If we change to `overflow-y: scroll`, then firefox matches chrome: https://codepen.io/anon/pen/goXPqO

**Comment by jasongrout** [comment]
Note that the above screenshots are on OS X with the OS system settings set so that scrollbars *always* show.

**Comment by Carreau** [comment]
> I just noticed in the code that we set .innerHTML with content from the server. Presumably that content is trusted because it's supposed to come from the kernel, but I think a defense-in-depth approach would still sanitize the content to make sure it only includes the noted <mark> tags, for example. c.f.

No the kernel should not be trusted. It could perfectly send non-escaped html if you are completing html/jsx..., so it should at least be escaped !

**Comment by ellisonbg** [comment]
Reopening to fix the trust issue in how we write the match to the DOM. Thanks for the note @Carreau

**Comment by Carreau** [comment]
> Reopening to fix the trust issue in how we write the match to the DOM. Thanks for the note @Carreau

Good point. Also the result sent by the completer does not assume the frontend is written in HTML is another way of seeing that.
