### ISSUE TITLE
Can't insert tab in code cell

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3544]
On master I am unable to insert a tab (by hitting tab) in the code cell editor. It works fine in markdown cells and the file editor.

**Comment by blink1073** [comment]
I'm not able to reproduce this locally.  We might need to screen share later.

**Comment by blink1073** [comment]
We narrowed this down to the fact that the nested config for cell editors is not being properly applied.

**Comment by ian-r-rose** [comment]
Ack, if you point me in the right direction I can try to make a fix.

**Comment by blink1073** [comment]
It could be that this needs to check for `undefined` as well as `null`: https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook-extension/src/index.ts#L453

**Comment by blink1073** [comment]
It looked like the values were getting set to `undefined`.

**Comment by ian-r-rose** [comment]
You are correct, that fixes it on my machine. We can't test for falsy values as some of the config options can be `false` here.

PR incoming.
