### ISSUE TITLE
Multiple selection using CM editor

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3563]
Question:

If someone is trying to do multiple selection, what should happen if they happen to click on the DM editor of the second cell that want to define the selection range?

In master, it will be treated as a regular click and focus the CM editor and put the cell into edit mode. Not sure if this is desired or not.

**Comment by blink1073** [comment]
Can we move this to Beta2?  I don't want to keep piling on issues for Beta1: we'll never get it out the door.

**Comment by ellisonbg** [comment]
Yep, that is fine, I just wanted to write it down so we can track it.
