### ISSUE TITLE
Finish "Getting Started" section of documentation

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3574]
This is an issue to track the final work on the "Getting Started" section of the documentation for the Beta 1 release. The following tasks remain:

- [ ] Proofread and make sure the text is in good shape.
- [ ] Create relevant screenshots and animations.
- [x] Cross link internally to other parts of documentation.
- [x] Add any additional external links that are appropriate.

For information about our documentation writing approach please see the `documentation.md` file in `docs/source/developer` (PR version [here](https://github.com/ellisonbg/jupyterlab/blob/f1dd1caa1ab812dd9177ad7420dfd40fca450170/docs/source/developer/documentation.md).)

**Comment by jzf2101** [comment]
See #3600

**Comment by jzf2101** [comment]
We should be clear on https://github.com/jupyterlab/jupyterlab/issues/3646 as well

**Comment by jzf2101** [comment]
Do we want screencaps in `starting.rst`?

**Comment by jzf2101** [comment]
Looks like we're basically done on this section.
