### ISSUE TITLE
Finish "The Interface" section of documentation

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3575]
This is an issue to track the final work on the "The Interface" section of the documentation for the Beta 1 release. The following tasks remain:

- [x] Proofread and make sure the text is in good shape.
- [x] Create relevant screenshots and animations.
- [x] Cross link internally to other parts of documentation.
- [x] Add any additional external links that are appropriate.

For information about our documentation writing approach please see the `documentation.md` file in `docs/source/developer` (PR version [here](https://github.com/ellisonbg/jupyterlab/blob/f1dd1caa1ab812dd9177ad7420dfd40fca450170/docs/source/developer/documentation.md).)

**Comment by jzf2101** [comment]
@jasongrout is this a good place for us to discuss cross-referencing in reference to your pr #3601

**Comment by jasongrout** [comment]
Sure. I would have probably made a new issue since it cuts across more than just the interface section, but here is fine too.

**Comment by jzf2101** [comment]
oh we can do that then

**Comment by jzf2101** [comment]
I would suggest that whatever naming convention we use, when we first mention a location in the UI,  we should reference its appropriate section in this document.  We could alternatively link every time.

**Comment by jzf2101** [comment]
I'm willing to declare this done and focus on adding the screencaps for the shortcuts

**Comment by ian-r-rose** [comment]
I added a a single screenshot for the shortcut last night. Feel free to update or add more.

**Comment by jzf2101** [comment]
If you want to reopen, could you reference the PR?
