### ISSUE TITLE
Finish "Working with files" section of documentation

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3576]
This is an issue to track the final work on the "Working with files" section of the documentation for the Beta 1 release. The following tasks remain:

- [x] Proofread and make sure the text is in good shape.
- [x] Create relevant screenshots and animations.
- [x] Cross link internally to other parts of documentation.
- [x] Add any additional external links that are appropriate.

For information about our documentation writing approach please see the `documentation.md` file in `docs/source/developer` (PR version [here](https://github.com/ellisonbg/jupyterlab/blob/f1dd1caa1ab812dd9177ad7420dfd40fca450170/docs/source/developer/documentation.md).)

**Comment by jzf2101** [comment]
Perhaps the working with files section should have a different name?

**Comment by jzf2101** [comment]
The title of this section "Working with Files" is vague given the fact that we have a separate pages for file formats and the file editor.  In fact, it may be more useful to combine the file editor and the working with files documents.

**Comment by jzf2101** [comment]
This is now done thanks @ian-r-rose @choldgraf
