### ISSUE TITLE
No red stripe in dev mode

### ISSUE THREAD

**Issue by davidrthorn** [jupyterlab/jupyterlab#3588]
From CONTRIBUTING.md:

> When running from source in development mode, the page will have a red stripe at the top to indicate it is an unreleased version.

I do not see any red stripe running JL in dev mode (--dev-mode --watch) on xubuntu with Chrome

Perhaps the fault lies with the contribution document. The above quoted sentence is ambiguous between:

1. When running in dev mode, a red stripe will always appear; this is because you are running an unreleased version.
2. When running in dev mode, a red stripe will appear if and only if the version you are running is unreleased.

**Comment by blink1073** [comment]
Hi @davidrthorn, what does `jupyter lab --version` print for you?

**Comment by blink1073** [comment]
Actually, I just confirmed that I'm not seeing it in master right now...
