### ISSUE TITLE
Tab Complete doesn't work if object not instantiated yet

### ISSUE THREAD

**Issue by jolespin** [jupyterlab/jupyterlab#3592]
In Jupyter Notebooks you can tab complete on objects that have not been instantiated (e.g. above in the current cell).  Jupyter Lab lacks this functionality currently.

**Comment by jasongrout** [comment]
This seems to work for me on master with the recent completer PR: #3570.

What release are you running? What version of ipykernel do you have?

**Comment by ellisonbg** [comment]
Also, it would be helpful if you can provide a simple example of an object we can try to complete on in our attempts to reproduce this. Thanks!

**Comment by jolespin** [comment]
![image](https://user-images.githubusercontent.com/9061708/35072467-91686cc0-fb99-11e7-9266-b3f700811bf1.png)

```bash
jupyter lab --version
0.30.6
```

In this case, I haven't instantiated the `X_data` object yet and I cannot tabcomplete when I have typed in `X_da`

**Comment by jasongrout** [comment]
I'm running ipykernel 4.7 and jupyterlab 0.31.1. Can you try updating your packages and see if that works? Just to be sure you're using the exact same kernel in both lab and the classic notebook, can you try it in the Jupyter notebook launched from the Help menu item in Lab?

**Comment by smacke** [comment]
Hi there, I'd like to confirm that I have the same issue on ipykernel 4.8.2, jupyterlab 0.31.12 -- I get the expected tab behavior on old notebooks (even those launched from jupyterlab help menu), but the broken behavior (identical to that of jolespin afaict) on jupyterlab.

**Comment by Carreau** [comment]
Here `X_Data2` is likely inferred from the javascript side. Codemirror has a tiny python completer that complete local names.  That may not have been integrated into JLab.

**Comment by oholimoli** [comment]
I have also a problem with Tab complete with a cython class (see below).
Tab complete works only on the first level:

```
A1  = A()
A1. <= Tab shows now optimizer 
A1.optimizer. <= Tab shows nothing :(
```

What is missing in my Cython class below, that Tab complete works? Is this also the case with regular Python classes?


```
cdef class optimizer():
    
    cdef:
        uint32_t u32_error
    
    def __init__(self):
        pass
    
    def __cinit__(self):
        self.u32_error = 0
        
    def __dealloc__(self):
        pass

    cdef uint32_t u32_calc_error(self, bool_t* x, bool_t* ref, uint32_t N):
        
        return 42
    
    cpdef uint32_t optimize(self):
        #self.u32_calc_error
        self.u32_error += 1
        return self.u32_error
        
    @property
    def error(self):
        return self.u32_error
    
cdef class A(B):
    """
    File: A.pxd
    'Optimizer' 
    cdef class A(B):
        ...
        ...
    
    """

    cdef:
        public optimizer optimizer
    
    def __cinit__(self, int N = 1):
        self.optimizer = optimizer()
        
    def __dealloc__(self):
        pass
    
    def __init__(self, int N = 1):
        super().__init__(N = N)


```

**Comment by nscozzaro** [comment]
I can confirm that the `load_iris` example autocompletes correctly in the current version of JupyterLab. Jedi (which the completer relies on) has also been updated, so it's possible that that helps.

**Comment by jasongrout** [comment]
Thanks!
