### ISSUE TITLE
Support vega 3 and vega-lite 2

### ISSUE THREAD

**Issue by davidanthoff** [jupyterlab/jupyterlab#3599]
I believe the vega2-extension package is all vega 2 and vegalite 1 right now.

**Comment by gnestor** [comment]
Until the vega3-extension is moved to JupyterLab, you can install the extension from the jupyter-renderers repo which supports vega 3 and vega lite 2: https://github.com/jupyterlab/jupyter-renderers#install

**Comment by domoritz** [comment]
There is an issue for moving the Vega 3 extension over here as well: https://github.com/jupyterlab/jupyter-renderers/issues/82. I tried to use both extensions in parallel and it works well.

**Comment by davidanthoff** [comment]
Hurray, this is awesome!
