### ISSUE TITLE
Moving the terminal or the console in the tab area causes it to not render fully

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#36]
Typing anything in it makes it render as expected.

**Comment by SylvainCorlay** [comment]
@afshin

**Comment by ellisonbg** [comment]
I don't see this, but I did witness this on @SylvainCorlay computer. Sylvain, could you give details of what OS/Browser combinations you see this on?

**Comment by ellisonbg** [comment]
@SylvainCorlay are you still seeing this in master?

**Comment by blink1073** [comment]
I had seen it in earlier released of xterm, but no longer.
