### ISSUE TITLE
Can't select and copy the html output contents

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#3603]
I went to select and copy the nice html styled table output and outputs are unable to be selected and therefore unable to be copied:

![image](https://user-images.githubusercontent.com/6559099/34808316-3d9046e2-f6e2-11e7-8738-e24fe32a728a.png)

**Comment by jasongrout** [comment]
Can you try this with the latest release candidate, 0.31rc2? You can install it with `pip install jupyterlab --pre`.

**Comment by SimonBiggs** [comment]
@jasongrout all good. I thought I was on rc2 but I wasn't :). It works on rc2.

Cheers,
Simon
