### ISSUE TITLE
/lab/tree not working in 0.30.6

### ISSUE THREAD

**Issue by leonsp** [jupyterlab/jupyterlab#3607]
If I understand these PRs correctly, I should be able to automatically open a file named `Untitled.ipynb` in my copy of Jupyterlab 0.30.6 by opening `/lab/tree/Untitled.ipynb`:

https://github.com/jupyterlab/jupyterlab/pull/3396
https://github.com/jupyterlab/jupyterlab-demo/pull/53

However, I get a 404 when I try, whether it's a notebook file, a csv file, or a directory.

**Comment by ian-r-rose** [comment]
Hi @leonsp the `tree` handler is available in `v0.31`, which was released this morning.
