### ISSUE TITLE
 Completer keyboard navigation

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#3609]
I have several suggestions about the completer UI.

* In classic notebook completer catches page up/page down key presses, whereas in jupyterlab v0.31 these are still caught by the cell, preventing fast navigation through long completion lists
* Completer closes on left arrow (logical behavior), but unlike classic notebook does not close on right arrow (relevant if the cursor is not at the very end of the cell)
* When the user activates the completer, then types enough letters for the completion to be unique, this unique completion is substituted without any input from the user and the completer closes. While I do believe that the automatic substitution is nice, it may potentially be better to keep the completer open in case the user notices they have chosen an incorrect completion option. If the user keeps on typing, the completer would of course close.

PS Really cool completer rewrite in v0.31!

**Comment by akhmerov** [comment]
Apologies for duplicates, the bullet point 1 and partially 3 were previously mentioned in #2360.

**Comment by jasongrout** [comment]
>  * In classic notebook completer catches page up/page down key presses, whereas in jupyterlab v0.31 these are still caught by the cell, preventing fast navigation through long completion lists

This seems to work now in JLab 2.1.4

> * Completer closes on left arrow (logical behavior), but unlike classic notebook does not close on right arrow (relevant if the cursor is not at the very end of the cell)

This seems to work now in JLab 2.1.4

> * When the user activates the completer, then types enough letters for the completion to be unique, this unique completion is substituted without any input from the user and the completer closes. While I do believe that the automatic substitution is nice, it may potentially be better to keep the completer open in case the user notices they have chosen an incorrect completion option. If the user keeps on typing, the completer would of course close.

This seems to have been fixed in JLab 2.1.4.

Thanks!
