### ISSUE TITLE
JSON mimetype inconsistency

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3611]
We have a json viewer registered using the `application/json` mimetype (correct) in one place: https://github.com/jupyterlab/jupyterlab/blob/38ca5f9b9b0f9930de46e8f14966b0f8f376a3c8/packages/json-extension/src/index.tsx#L73, but also with the `application/x-json` mimetype in another place: https://github.com/jupyterlab/jupyterlab/blob/38ca5f9b9b0f9930de46e8f14966b0f8f376a3c8/packages/docregistry/src/registry.ts#L1116. Is there a reason for the extra `application/x-json` mimetype registration?

**Comment by blink1073** [comment]
I seem to remember using a reference list of mime types, but I didn't document it in the PR so I'm not sure.  Happy to remove `x-json`.

**Comment by jasongrout** [comment]
This is fixed in #3601 (still under review).
