### ISSUE TITLE
Inserted cell created with "Alt Enter" is not put in edit mode

### ISSUE THREAD

**Issue by jwkvam** [jupyterlab/jupyterlab#3634]
I noticed this with v0.31.0, I have disabled jupyterlab_vim and pressing "Alt Enter" inserts a new cell but I remain in command mode. I think this is a broader issue because I see this happen with other commands with jupyterlab_vim, because I try to aggressively stay in edit mode.

**Comment by jasongrout** [comment]
Thanks for the report! I just checked, and it looks like it is fixed in master (probably https://github.com/jupyterlab/jupyterlab/pull/3624 or https://github.com/jupyterlab/jupyterlab/pull/3617 fixed it). We'll be releasing a patch release with these fixes soon.
