### ISSUE TITLE
Specify what we mean by "latest version" in documentation?

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#3646]
Do we want to specify what we mean by latest version lest we find out some updates don't work on master or the release? @jasongrout @ian-r-rose @blink1073 @afshin @ellisonbg feel free to chime in

**Comment by jasongrout** [comment]
it's a balance between saying "latest release", and constantly updating. I think it's fine to say "latest release", because if lab doesn't work, we'll have to fix it.
