### ISSUE TITLE
Starting a terminal fails (Windows 7)

### ISSUE THREAD

**Issue by dalito** [jupyterlab/jupyterlab#3647]
When trying to launch a terminal, an error message pops up "Launcher Errror - Launcher callbacks must resolve with a widget"

Output shown in the jupyter console:
```
[E 13:41:18.148 LabApp] Uncaught exception POST /api/terminals?1516020077981 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/terminals?1516020077981', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\dev_src\_pyve\stable_py36\lib\site-packages\tornado\web.py", line 1534, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "c:\dev_src\_pyve\stable_py36\lib\site-packages\tornado\web.py", line 2929, in wrapper
        return method(self, *args, **kwargs)
      File "c:\dev_src\_pyve\stable_py36\lib\site-packages\notebook\terminal\api_handlers.py", line 16, in post
        name, _ = self.terminal_manager.new_named_terminal()
      File "c:\dev_src\_pyve\stable_py36\lib\site-packages\terminado\management.py", line 319, in new_named_terminal

        term = self.new_terminal()
      File "c:\dev_src\_pyve\stable_py36\lib\site-packages\terminado\management.py", line 171, in new_terminal
        pty = PtyProcessUnicode.spawn(argv, env=env, cwd=options.get('cwd', None))
      File "c:\dev_src\_pyve\stable_py36\lib\site-packages\winpty\ptyprocess.py", line 113, in spawn
        inst = cls(proc)
      File "c:\dev_src\_pyve\stable_py36\lib\site-packages\winpty\ptyprocess.py", line 47, in __init__
        self._server.bind(address)
    OSError: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden
[W 13:41:18.156 LabApp] Unhandled error
[E 13:41:18.157 LabApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0",
      "Accept": "*/*",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab",
      "Authorization": "token ab7e515e947d83986eaa3028440db56372c20effdf3d22ab",
      "Content-Type": "application/json",
      "Origin": "http://localhost:8888",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1516020071|23:username-localhost-8888|44:N2VmNzQ5Zjg5OGJkNDI5NGE0MTNmZjY2M2ZjNzlkMjc=|68a2e15edf6189c9f674fdd5a97655ffcefe64abf0c38e9ba889a4794516efcf\"; _xsrf=2|65f62544|8c2ce7dc2b1a40ce7c9ef04647a01b1f|1515664264",
      "Connection": "keep-alive",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache",
      "Content-Length": "0"
    }
[E 13:41:18.162 LabApp] 500 POST /api/terminals?1516020077981 (::1) 163.01ms referer=http://localhost:8888/lab
```
The german text for the WinError 10048 means: Each socket address may only be used once.

Versions: 
 * jupyterlab 0.31.1 beta
 * Python 3.6.4, 64bit
 * Win7 Pro (german)

**Comment by gfyoung** [comment]
How did you get a terminal in Windows?  As far as I knew, there wasn't support for that feature yet.

**Comment by dalito** [comment]
Starting a terminal is one of the options in the Launcher window. So if you are correct, it should not be offered on Windows.

**Comment by gfyoung** [comment]
@dalito : https://github.com/jupyter/notebook/issues/172

I know is for Jupyter (not JupyterLab), but I can't imagine at this point that that kind of support would have changed from one environment to the next.

**Comment by blink1073** [comment]
Hi @dalito, what is the output of `jupyter notebook --version`?

**Comment by dalito** [comment]
5.3.0rc1

**Comment by blink1073** [comment]
I verified that it worked for me using the same configuration (aside from being the English version of Windows).  What is the output of `python -c "import winpty; print(winpty.__version__)"`?

**Comment by SimonBiggs** [comment]
I also got that error with 5.3.0rc1 version of notebook. Running `pip install --upgrade notebook` (receiving notebook 5.3.1) didn't fix the issue.

Running `pip install --upgrade jupyterlab`  going from 0.31.0 --> 0.31.1 also didn't fix the issue.

Running `python -c "import winpty; print(winpty.__version__)"` gives 0.5.1. Attempting `pip install --upgrade pywinpty` returns that I already have the latest version.

This is happening on a Windows 7 machine, english version. Not sure if it's relevant, but the recent Meltdown patches have been applied. The following is the output after booting jupyterlab after a freshly cleaned workspace then clicking `File > New > Terminal`.

```batch
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\sbiggs>jupyter lab
[I 08:14:35.327 LabApp] JupyterLab beta preview extension loaded from c:\users\sbiggs\appdata\local\continuum\miniconda3
\lib\site-packages\jupyterlab
[I 08:14:35.328 LabApp] JupyterLab application directory is c:\users\sbiggs\appdata\local\continuum\miniconda3\share\jup
yter\lab
[I 08:14:35.490 LabApp] Serving notebooks from local directory: C:\Users\sbiggs
[I 08:14:35.491 LabApp] 0 active kernels
[I 08:14:35.491 LabApp] The Jupyter Notebook is running at:
[I 08:14:35.491 LabApp] http://localhost:8888/?token=52b08651944af40ba495825623a107a93439be4309db7dfe
[I 08:14:35.491 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:14:35.493 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=52b08651944af40ba495825623a107a93439be4309db7dfe
[I 08:14:35.547 LabApp] Accepting one-time-token-authenticated connection from ::1
[I 08:14:36.002 LabApp] Build is up to date
[I 08:14:40.727 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
Exception in thread Thread-3:
Traceback (most recent call last):
  File "c:\users\sbiggs\appdata\local\continuum\miniconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "c:\users\sbiggs\appdata\local\continuum\miniconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\sbiggs\appdata\local\continuum\miniconda3\lib\site-packages\winpty\ptyprocess.py", line 337, in _read_i
n_thread
    data = pty.read(4096)
  File "c:\users\sbiggs\appdata\local\continuum\miniconda3\lib\site-packages\winpty\winpty_wrapper.py", line 73, in read

    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x0000000000000000

[I 08:14:40.756 LabApp] EOF on FD 1016; stopping reading
[I 08:14:40.957 LabApp] Terminal 1 closed
[E 08:14:40.962 LabApp] Uncaught exception in /terminals/websocket/1
    Traceback (most recent call last):
      File "c:\users\sbiggs\appdata\local\continuum\miniconda3\lib\site-packages\tornado\websocket.py", line 494, in _ru
n_callback
        result = callback(*args, **kwargs)
      File "c:\users\sbiggs\appdata\local\continuum\miniconda3\lib\site-packages\notebook\terminal\handlers.py", line 37
, in on_message
        super(TermSocket, self).on_message(message)
      File "c:\users\sbiggs\appdata\local\continuum\miniconda3\lib\site-packages\terminado\websocket.py", line 84, in on
_message
        self.terminal.resize_to_smallest()
      File "c:\users\sbiggs\appdata\local\continuum\miniconda3\lib\site-packages\terminado\management.py", line 63, in r
esize_to_smallest
        self.ptyproc.setwinsize(minrows, mincols)
      File "c:\users\sbiggs\appdata\local\continuum\miniconda3\lib\site-packages\winpty\ptyprocess.py", line 327, in set
winsize
        self.pty.set_size(cols, rows)
    AttributeError: 'NoneType' object has no attribute 'set_size'
Websocket closed
```

A screenshot of the terminal window is the following:

![image](https://user-images.githubusercontent.com/6559099/35012751-fbb28aba-fb5e-11e7-85dd-902fb868ba16.png)

**Comment by dalito** [comment]
Running python -c "import winpty; print(winpty.__version__)" gives 0.5.1. I have everything up to date. "pip list -o" lists nothing as outdated.

Today I also saw the error that @SimonBiggs reported. If I try to open a terminal from the launcher again and again, I get sometimes the error that I reported and sometimes the one that Simon reported.

**Comment by SimonBiggs** [comment]
I should also say I am running Python 3.5

**Comment by dalito** [comment]
I observed the error on a Win7 Pro intranet machine without direct access to internet (not Win10 Pro as I wrote originally). At home on a Win10 Pro machine I can open a terminal without any problem (same Python version, same versions of all installed libraries).

**Comment by SimonBiggs** [comment]
My Windows is Win7 Professional 64-bit service pack 1. It has internet access with minimal limitations. Not sure if it is relevant but Symantec Endpoint Protection version 12.1.4100.4126 is also running.

**Comment by blink1073** [comment]
@dalito, @SimonBiggs, does this simplified code work in Python for you?

```python
from winpty import PtyProcess

proc = PtyProcess.spawn('python')
proc.write('print("hello, world!")\r\n')
proc.write('exit()\r\n')
while proc.isalive():
	print(proc.readline())
```

**Comment by SimonBiggs** [comment]
Thanks @blink1073 :)
That simplified code does not work:

```python
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\sbiggs>python
Python 3.5.4 | packaged by conda-forge | (default, Aug 10 2017, 01:38:47) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from winpty import PtyProcess
>>>
>>> proc = PtyProcess.spawn('python')
>>> proc.write('print("hello, world!")\r\n')
24
>>> proc.write('exit()\r\n')
8
>>> while proc.isalive():
...     print(proc.readline())Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\sbiggs\AppData\Local\Continuum\Miniconda3\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\sbiggs\AppData\Local\Continuum\Miniconda3\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\sbiggs\AppData\Local\Continuum\Miniconda3\lib\site-packages\winpty\ptyprocess.py", line 337, in _read_i
n_thread
    data = pty.read(4096)
  File "C:\Users\sbiggs\AppData\Local\Continuum\Miniconda3\lib\site-packages\winpty\winpty_wrapper.py", line 73, in read

    ReadFile(self.conout_pipe, data, length, None, None)
OSError: exception: access violation writing 0x0000000000000000
```

**Comment by dalito** [comment]
I get sometimes the same error as Simon and somtimes the other error on Python 3.6.4 (from python.org).
```
(stable_py36) λ py
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from winpty import PtyProcess
>>>
>>> proc = PtyProcess.spawn('python')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\dev_src\_pyve\stable_py36\lib\site-packages\winpty\ptyprocess.py", line 113, in spawn
    inst = cls(proc)
  File "c:\dev_src\_pyve\stable_py36\lib\site-packages\winpty\ptyprocess.py", line 47, in __init__
    self._server.bind(address)
OSError: [WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden
>
```
So your simple example reproduces the problem exactly.

**Comment by blink1073** [comment]
Okay, it seems this was a known issue: cf https://github.com/spyder-ide/pywinpty/issues/59.  It is not clear to me how to address it.

**Comment by blink1073** [comment]
Barring a full fix, we should catch this in the notebook server and identify that terminals are not available [here](https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L1339).

**Comment by SimonBiggs** [comment]
They mention that it was python binary dependent. I'll spin up a python 3.4
environment and see if the error goes away. Will report back after I get a
chance to give that a shot.

**Comment by dalito** [comment]
I also tried different Python-Versions on Win7: Python-3.6.3-64bit, Python-3.6.4-64bit, Python-3.6-32bit. - All give the same errors. 

On the other hand the terminal does work on Win10 (Python-3.6.4-64bit and Python-3.6-32bit). Rarely the shell version number is "wrapped", see upper terminal in screenshot.

![jupyterlab-win10](https://user-images.githubusercontent.com/2648874/35123831-1abca7a6-fca4-11e7-9b1d-41b961acdeb6.PNG)

**Comment by SimonBiggs** [comment]
Of interest, I'm trying to uninstall and reinstall pywinpty with pip and I'm getting errors saying 'Microsoft Visual C++ 10.0 is required'. I actually already have it installed, but it can't seem to find it.

I can solve this, I just can't spend anymore work time chasing this rabbit hole.

It seems like a similar problem to the following:
https://stackoverflow.com/questions/28251314/error-microsoft-visual-c-10-0-is-required-unable-to-find-vcvarsall-bat

**Comment by dhirschfeld** [comment]
Terminals appear to be working for me:

![image](https://user-images.githubusercontent.com/881019/35315284-531406ea-0117-11e8-8f1b-1bc3df13e010.png)


...and they're ***awesome!!!***

Running python 3.6.4, jupyterlab 0.31.1, notebook 5.3.1, pywinpty 0.5, terminado 0.8.1 in a Windows Container.

**Comment by dalito** [comment]
@dhirschfeld is this on Win7? Did you configure anything to get a Power Shell terminal?

**Comment by dhirschfeld** [comment]
It's in a Windows Server Core 1709 container running on Windows Server 1709.

The default terminal is Powershell IIUC - https://github.com/jupyter/notebook/pull/3087/commits/2bd8f0375169df3ecb4e6f99945019c469038c27

**Comment by jasongrout** [comment]
Ping on this - any progress?

**Comment by dhirschfeld** [comment]
I *think* the problem is terminals (winpty) dosn't work on win7 and I *think* they may have been disabled on that platform. @blink1073 would probably the one to actually know...

**Comment by blink1073** [comment]
We weren't able to determine exactly why it fails on some Windows 7 machines, but not on Appveyor (which is running Windows 7).

**Comment by SimonBiggs** [comment]
I'm happy to do more testing if it is desired. But maybe I'll just ask work
to upgrade me to Windows 10 :)

**Comment by jasongrout** [comment]
Moving to future until we can reproduce the issue.

**Comment by dalito** [comment]
Is Appveyor really using Win7? According to https://www.appveyor.com/docs/build-environment/#pre-installed-software it uses Windows Server 2012 R2 or Windows Server 2016.

I can still reproduce this bug on Win7 even after the latest VC runtime upgrades (to 14.13.26020.0).

**Comment by sleeplessme** [comment]
It seems like problem on WIndows 7. Im using windows seven too and get problem about Violation Wtiting 0x00000

**Comment by axil** [comment]
Looks as if it is solved now with the patch from https://github.com/spyder-ide/pywinpty/issues/108

**Comment by cheTesta** [comment]
Same for me here:
Win7 Enterprise SP1
jupyter notebook --version: 5.5.0

**Comment by dhirschfeld** [comment]
This can probably be closed as resolved?

**Comment by ccordoba12** [comment]
I think so, yes.

**Comment by dalito** [comment]
I will check tomorrow if the problem is gone on the Win7 machine where I originally observed the problem.

**Comment by dalito** [comment]
Updating to pywinpty version 0.5.4 fixed the issue for me, too. Thanks!
