### ISSUE TITLE
Medium Post

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#3651]
We need to finish reviewing the medium post and then publishing

**Comment by jasongrout** [comment]
We'll probably need to note the screenshot of the zurich data is made from CC-BY-NC data.

**Comment by jasongrout** [comment]
> We'll probably need to note the screenshot of the zurich data is made from CC-BY-NC data.

Done

**Comment by jasongrout** [comment]
Looking at the current draft - wow, it'd be nice if we could pull that screenshot of the Lorenz notebook up to the top, right under the tl;dr. Or perhaps we could use the more advanced Lorenz screenshot at the top, the one at https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/images/jupyterlab.png

**Comment by jasongrout** [comment]
CC @ellisonbg

**Comment by jasongrout** [comment]
@ellisonbg is adding dropshadows on the screenshots. Other than that, I think we're done, so closing.

**Comment by jzf2101** [comment]
@ellisonbg I don't see the shadows?
