### ISSUE TITLE
File Dirty status indication

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3652]
I thought at one time there was some visible difference in a tab of a document that was dirty (i.e., not saved). It seems that the visible difference is gone now - I can't tell how to see if a file needs to be saved.

For example, we could prefix the document name with `*`, or VS Code changes the close `X` to a filled circle.

**Comment by ian-r-rose** [comment]
It looks like this is currently broken for text files. I still see the filled circle for notebooks with unsaved changes, though.

**Comment by jasongrout** [comment]
I didn't realize it was working for notebooks. I can look into this...

**Comment by jasongrout** [comment]
I'm diving down - as best as I can tell, the file title changed signal has no listeners, but the notebook title changed signal has the tab bar as a listener. Diving deeper...

**Comment by jasongrout** [comment]
heh, looks like you fixed it...

**Comment by ian-r-rose** [comment]
Yeah, sorry to step on your toes! A refactor put the `jp-mod-dirty` css class on the wrong div.

**Comment by jasongrout** [comment]
oh, that easy!
