### ISSUE TITLE
Markdown code can not be converted into LaTeX code properly.

### ISSUE THREAD

**Issue by szsdk** [jupyterlab/jupyterlab#3664]
I wrote a list with markdown in JLab. But when I convert it into LaTeX, it seems that JLab just pastes the original code.

**Comment by jasongrout** [comment]
Was this a markdown cell in a notebook, then converting the notebook to latex? If not - how did you convert to latex?

**Comment by szsdk** [comment]
Yes, it is a markdown cell.
![image](https://user-images.githubusercontent.com/6657200/35129760-0f7db23c-fcf8-11e7-915a-7edb0e664d74.png)

**Comment by jasongrout** [comment]
Does it work in the classic notebook? (You can launch the classic notebook from the Help menu). This may be a problem with nbconvert.

**Comment by szsdk** [comment]
No. Even in classic notebook, it still does not render. But in my own laptop, everything works as expected. But the version of jupyter are same.

**Comment by jfbercher** [comment]
Is there a newline before the list items? If not can you try to add one?

**Comment by t-makaro** [comment]
I don't think that this is directly a problem with nbconvert, but with pandoc. Pandoc is fairly picky about how some things are formatted when converting. As an example, a list should be formatted like:

```
This is a test list:

1. item 1
   - subitem 1
   - subitem 2
2. item 2
3. item 3
```
Note the extra empty line before the first item in the list. This will render property in notebook, jlab, and in an nbconvert to latex.
