### ISSUE TITLE
Duplicate Kernel objects

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3669]
In JLab 0.31.1, it appears that we get *two* kernel websocket connections for the same kernel when creating a new notebook. For example, I see these two connections with just one notebook and a fresh clean startup:

* ws://localhost:8888/api/kernels/2d563af6-e33c-498a-8f5d-70afb093fb21/channels?session_id=a6939dfb9e4b5953c9424dfac68cec84&token=...
* ws://localhost:8888/api/kernels/2d563af6-e33c-498a-8f5d-70afb093fb21/channels?session_id=41f72a9b3935bcc60d5ff637faa7dd35&token=...

Notice that the kernel ids are the same, but the session ids are not. I also see two different Kernel objects being created. There are at least a few messages that are being sent to both kernels.

This seems to be causing errors with ipywidgets in a notebook - the comm handler is registered in one kernel, but not the other, so there are errors when the comm open messages are sent to both kernels.

Digging deeper...

**Comment by jasongrout** [comment]
The same thing appears to happen on master. To see this, start a fresh jupyterlab session, with no kernels, and no saved notebooks opening kernels. Then open a new notebook. Look in the Networks tab in Chrome, for example, and you should see two websocket connections, similar to the above, to the same kernel, but with different session ids.

**Comment by blink1073** [comment]
Yes, this was an intentional behavior of `.connectTo()`.

**Comment by jasongrout** [comment]
Hmm, okay. Can you elaborate? Why are we connecting to the same kernel with two sessions?

**Comment by blink1073** [comment]
Session is an overloaded term here, it is a new client id because we had decided that the level of client id was not at the "front end session" level, but at a specific kernel user level.

**Comment by jasongrout** [comment]
(For my notes, it appears that the two kernel objects are created, one from this line: https://github.com/jupyterlab/jupyterlab/blob/4beab1365ba91b6ee665f6af52abb6fcbcae53d9/packages/services/src/session/manager.ts#L162 and the other from this line: https://github.com/jupyterlab/jupyterlab/blob/4beab1365ba91b6ee665f6af52abb6fcbcae53d9/packages/services/src/session/manager.ts#L163)

**Comment by blink1073** [comment]
As two why two are immediately created, that does sound like a bug.

**Comment by jasongrout** [comment]
> but at a specific kernel user level.

but there's only one notebook open, so it seems there should only be one kernel thing registered.

**Comment by jasongrout** [comment]
> As two why two are immediately created, that does sound like a bug.

Okay, thanks - I'll keep digging.

**Comment by jasongrout** [comment]
I just checked, and this doesn't seem to happen on 0.30.6.

**Comment by jasongrout** [comment]
It looks like the duplicate session for the same kernel is coming from https://github.com/jupyterlab/jupyterlab/pull/3311, which adds the line https://github.com/jupyterlab/jupyterlab/blob/a91be6096774fac66e0750296807889deadf5609/packages/help-extension/src/index.ts#L218 to make a new session to get the kernel help links if it doesn't have them in its cache. So it looks like it's one extra session connection per kernel.

On the one hand, this is the design, right? Each new session id connecting to a kernel gets its own websocket? I can see how you can consider the help plugin and the notebook plugin as needing two different sessions with the same kernel. The help plugin should probably shut down its session after it gets the info it wants, but of course not shut down the kernel.

On the other hand, we may need to rethink how we interact with kernels and sessions in widgets to make sure we are keeping things straight.

**Comment by jasongrout** [comment]
CC @ian-r-rose
