### ISSUE TITLE
Auto-complete within strings doesn't only show file paths

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#3672]
99% of the time when I'm using auto-complete within a string, I'm using it to navigate a file system. In Jupyer Lab, hitting `<tab>` within a string brings up all of the variables in the global namespace, which makes using `<tab>` for navigating folders really cumbersome. Is there a way to change this behavior in configuration? (e.g. order the autocomplete menu so that file paths are at the top?)

For example, here's what I currently see:

![image](https://user-images.githubusercontent.com/1839645/35064315-72eea7a2-fb7e-11e7-81f2-9ff7be180fe0.png)

I tried searching "auto-complete" and "autocomplete" in the docs but it didn't return anything...

**Comment by jasongrout** [comment]
Does this happen in the classic notebook as well? My guess is that the problem lies in the completer on the python side, not in JLab.

(And thanks for bringing it up - let's try to figure out where the fix should go...)

**Comment by choldgraf** [comment]
you are correct! I didn't consider that. What would have changed under-the-hood, IPython? @Carreau any thoughts?

@jasongrout LMK if you'd like me to close this and open elsewhere

**Comment by Carreau** [comment]
Summoned by @choldgraf 

Likely IPython bug, might be fixed in master.  It's confused as it may not "see" it's in a string.

**Comment by choldgraf** [comment]
hmm - is this kind of behavior highly OS-specific? Otherwise I'm surprised more people haven't reported this...it makes autocomplete kind of impossible to use because it never narrows down the list of options by type inference

**Comment by Carreau** [comment]
Pretty sure it has been reported. But you know os paths are so 20th century, now all is in the cloud.

**Comment by choldgraf** [comment]
heh oh so you're saying I should run `kubectl give me my data`?

**Comment by Carreau** [comment]
Yeah, or use https://quiltdata.com/.

Honestly improving autocompletions would be great, but that may require funding some actual work to go in Jedi, and we could integrate other engines as well. cleaning up (understand rewriting completions from scratch), has been on my TODO list for quite some time, I hope to be able to start this task at some point.

**Comment by rth** [comment]
This was also one of first things I noticed when trying Jupyter Lab. I was under impression that it worked better in Jupyter notebook, but your are right the results are similar, in IPython as well. I couldn't find [a relevant issue in ipython repo](https://github.com/ipython/ipython/search?q=auto+complete+path&state=open&type=Issues&utf8=%E2%9C%93) (unless the tab competition is actually done in prompt_toolkit ?)

There is a difference however. IPython and Jupyter Notebook will put public methods first,
```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: '/tmp/<TAB>
              abs()                                    ascii()                                   
              all()                                    AssertionError                            
              any()                                    AttributeError                           >
              ArithmeticError                          BaseException                             
```
while JupyterLab (0.31.2 installed from conda-forge) will put private methods first (as illustrated in the [original post above](https://github.com/jupyterlab/jupyterlab/issues/3672#issue-289395584) maybe hence the incorrect impression that it works less well...

**Comment by rth** [comment]
Also, sometimes, the path will be the first suggestion,

<img width="561" alt="image1" src="https://user-images.githubusercontent.com/630936/35924207-b0fb671a-0c22-11e8-8f59-8dff967072cb.png">

I'm confused now. Which part of the code does the auto-complete?

**Comment by Carreau** [comment]
You need to understand the history of thing for this behavior, IPython used to (and still have compatibility for) readline. When using readline you unfortunately do not  have the choice to get the full line while completing. Readline have a notion of "delimiters" and if you have a line like func(`'/tmp/v<TAB>')` readline would "split" this a `'`, `/`, sending only `v` to IPython for completion.

We built _a lot_ of heuristics on this, including path completions

Jump forward 15 years, and now we _can_ get the full line, often the full cell and be smarter.  Though we still haven't updated all the heuristics and function to act on the full text. So some completions source still go through the "shim" layer that split the string on `'` and `/`, and (for example) return builtins like `ValueError`. There are many sourced, including Jedi, and a couple of custom ones (in `IPython/core/completer.py`)

One "simple" fix would be to not trigger these completions source when we are inside a string.
While we technically have this information we also found that completion was used to write code examples in docstring, insert unicode (`\alpha<tab>`)... etc.

So now we just need to find the time, and refine these heuristics, update APIs... 
There are [many issues](https://github.com/ipython/ipython/labels/tab-completion) open about completions.

**Comment by choldgraf** [comment]
that's a super informative post, @Carreau - thanks! There should be a jupyter tech blog where this kind of thing can live :-)

**Comment by choldgraf** [comment]
@Carreau regarding your "simple fix" - another option would be to do alphabetic sorts _within line type_. So first you'd get the functions, then the classes, etc...and within those groups you'd have alphabetic sorting. Then if you're in a string you could just put the paths first. Don't need to the other stuff out, just make it less visually-apparent

**Comment by rth** [comment]
Thanks for the detailed explanations @Carreau !

**Comment by sirotenko** [comment]
This significantly slows down my everyday workflow as I'm relying on path autocompletion a lot. If anyone comes up with **any** solution please publish it.

**Comment by sathappanspm** [comment]
installing ipykernel==4.6.1 seems to fix this problem for me. Check here for more info - https://github.com/jupyter/notebook/issues/3333

**Comment by jolespin** [comment]
What if starting a string with "." will indicate that it's a filepath and to not include the methods and objects? For example, 

(1) `path = "./`
(2) `[tab]`
(3) Shows only files in the directory

(1) strobject = "atcg`
(2) `[tab]`
(3) New behavior

**Comment by sirotenko** [comment]
@jolespin, unfortunately this doesn't work for me:
![image](https://user-images.githubusercontent.com/483348/36690673-0f729eca-1b01-11e8-84ba-1fc6fd496d02.png)

**Comment by jolespin** [comment]
Yea it doesn't work for me either but I think it would be an easy conditional to fix the problem in the backend.  However, the Jupyter Lab and ipykernel is WAY out of my league in coding abilities.

**Comment by Kim-Seonghyeon** [comment]
pip install ipython==6.2.0 fixed it for me. Even with ipykernel 4.8.2

**Comment by joelostblom** [comment]
Upgrading to ipython >= 6.3.0 also fixes this issue (as per [this comment](https://github.com/ipython/ipython/issues/10961#issuecomment-378498693)). Since it seems to be an ipython problem, can this issue be closed @choldgraf ?

**Comment by choldgraf** [comment]
yarp

**Comment by YubinXie** [comment]
ipython 7.3 shows this problem, while it was ok before.

**Comment by RuRo** [comment]
Same here with `ipython 7.4.0` and `ipykernel 4.9.0`

**Comment by mytrjp** [comment]
adding 
$ '/../path/' 
another '/' also helped for me: 
$ '/../path//'
and then press Tab for completion

**Comment by YubinXie** [comment]
@mytrjp Great tip. Thank you.
