### ISSUE TITLE
Autocomplete in command palette misses "and"

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#3674]
Just a minor UX issue - in the command palette, the "restart & run all" command uses "&" not "and". This means that autocomplete won't catch it if you write "restart and". This feels like a more common way for people to write this (pretty common) command. Is there a way to get autocomplete to make "and" resolve to "&"?

**Comment by choldgraf** [comment]
I'm +1 on that - I assumed "&" was used for some kind of UI purpose but I think "and" works just fine

**Comment by jasongrout** [comment]
We probably should use the same text as the menu items: 

<img width="327" alt="screen shot 2018-01-17 at 7 22 20 pm" src="https://user-images.githubusercontent.com/192614/35079371-cac339c4-fbbb-11e7-87ef-3e7ee6b83e62.png">

**Comment by jasongrout** [comment]
CC @ian-r-rose
