### ISSUE TITLE
Empty view for a widget

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlab/jupyterlab#3683]
Hi,

I tried to create a new view for a widget output but it is empty. Is it supported?
Here is how to reproduce the issue:
```
git clone https://github.com/davidbrochart/ipyearth.git
mkdir ipyearth_env
cd ipyearth_env
pipenv install jupyterlab
pipenv shell
pipenv install numpy
pipenv install matplotlib
pipenv install -e ../ipyearth
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install ../ipyearth/js
jupyter lab ../ipyearth/examples/demo.ipynb
```

Then right-click on cell 2 and select "Create New View for Output".

**Comment by jasongrout** [comment]
It should work. We're seeing some issues with widgets on jlab 0.31.1 that we're still tracking down.

**Comment by davidbrochart** [comment]
I just tried with 0.31.2 and I'm still seeing this behavior.

**Comment by davidbrochart** [comment]
No, it still doesn't work with jlab 0.34.9.

**Comment by davidbrochart** [comment]
That said, I'm not sure it is worth the effort of investigating, it might come from IPyEarth itself, which was my first implementation of an IPyWidget and was probably not well coded.
So feel free to close this issue, I will open another one if/when I work on it again and I am sure it doesn't come from my side.
