### ISSUE TITLE
Restart & Run All option

### ISSUE THREAD

**Issue by rgerkin** [jupyterlab/jupyterlab#3684]
Unless I am missing something, the "Restart & Run All Cells" option from the notebook is not in lab.  Is this an explicit design choice?  Because I use it all the time in the notebook and would like to have access to it in Lab as well.

**Comment by jasongrout** [comment]
It is available. Are you running version 0.31.1? We redesigned the menu so that things like that would be easier to find. It's now under the Run menu when a notebook is active.

**Comment by rgerkin** [comment]
No, I had a slightly older version and did not see that.  Thanks!

**Comment by jasongrout** [comment]
Great.  Enjoy!

**Comment by michaelzeagler** [comment]
This is how I prefer to run most of my notebooks. Is there a reason it's not given its own specific shortcut or button in the menu bar?
