### ISSUE TITLE
Thoughts on the JupyterLab Documentation

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#3690]
@jzf2101 asked for a few thoughts on the documentation, so I'll take a look through it and will add them here:

- [x] (d363a34778767fa73125a28a0765955dad509bac) Main landing page: we should add a short bit of text explaining what JupyterLab is and what to expect from these docs, maybe with a small snapshot or logo as well.
- [x] (d363a34778767fa73125a28a0765955dad509bac) Would be good to link early on to some user examples (maybe binder repos?)
- [x] Installation page: isn't the `serverextension enable` bit unnecessary now? I had heard this on twitter so I may be wrong.
- [x] [Menu bar section](http://jupyterlab-tutorial.readthedocs.io/en/latest/user/interface.html#menu-bar): the first word of each bullet point should be in bold
- [X] (bf70399588d22c67fce4fa98ecc25e39fff6bcd2) Just a note that in some places you have mac-specific keys listed, e.g. the last point on [this page](http://jupyterlab-tutorial.readthedocs.io/en/latest/user/commands.html)
- [X] (992ad5a19bf165c49175ae106db40900f1c099f2) Double-check your links here: http://jupyterlab-tutorial.readthedocs.io/en/latest/developer/notebook.html#model

* General - have you thought about putting the "developer guide" into a separate repository like `jupyterlab-dev`? It might help the docs stay user-focused and be less-cluttered. You don't want to scare away skittish users.
* To that extent, it's a bit hard to figure out in the "developer guide" when you're talking about "people that want to develop things with JupyterLab" (e.g., extensions) vs. "people that want to develop JupyterLab itself" (e.g., the [documentation guidelines](http://jupyterlab-tutorial.readthedocs.io/en/latest/developer/documentation.html). Might be worth separating them out.

That's it for now, but I can take another look later!

**Comment by jasongrout** [comment]
Thanks!

**Comment by jzf2101** [comment]
@choldgraf I'll take that into acct thx !

**Comment by jasongrout** [comment]
I fixed most things here. I left the larger docs restructuring for another day, though. I'll close this and open a new scoped PR about the structure of the docs.

**Comment by choldgraf** [comment]
👍

**Comment by jasongrout** [comment]
Thanks again for the feedback!
