### ISSUE TITLE
Unreachable link in docs

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyterlab/jupyterlab#3694]
Just a minor issue: Today I noticed some link in the docs is not working any longer:

<https://jupyterlab-tutorial.readthedocs.io/en/latest/extensions_dev.html> does not exist any more (redirects me to the "maze"), it is linked to from: <https://libraries.io/github/jupyterlab/jupyterlab>.

**Comment by jzf2101** [comment]
I think we're not using that page anymore? @ian-r-rose @blink1073

**Comment by blink1073** [comment]
The latest https://libraries.io/github/jupyterlab/jupyterlab has the correct updated link from our readme.  Cheers!
