### ISSUE TITLE
Single document mode default shortcut choice

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#3695]
This is just a discussion point about the default keyboard shortcut for single document mode.

I have found when I was finding my feet with JupyterLab that every so often "the tabs would disappear". For quite a while this was quite confusing.

I worked out that this was the "single document mode". The reason that it would "sometimes happen" would be a slip of keys. Ctrl + Enter, and Shift + Enter are so commonly used by myself within the Notebook that sometimes, accidently, I would press Ctrl + Shift + Enter (fat fingers).

For a new user having the tabs disappear can be hard to solve. I wonder if it might be worth changing the default single document shortcut key to `Ctrl + Alt + Enter` for the sole purpose of making it less likely to disorient a new user with the same mistake I made.

Just a discussion point.

Cheers,
Simon

**Comment by timkpaine** [comment]
My users all say this. It's so annoying, and it's not a substitute for dashboards, I'm not sure why it exists 

Tim

**Comment by ellisonbg** [comment]
What I am hearing here is that there are two separate points of feedback (both of which we appreciate):

1) The keyboard shortcut for single document mode is easy to hit accidentally and a user can quickly become confused and not know what happened.
2) It is unclear what the purpose of single document mode is, and if it should exist. 

For 1), I think we should fix it without delay. Even a few users hitting that is a really painful situation.

For 2), I can explain the purpose we have envisioned for single document mode. Whether that pans out for users is another story. With a flexible layout system such as we have in the main work area of JupyterLab, we *hypothesize* that users will sometimes want to work on, view or present a single document, but without closing all of their other documents. Single document mode is designed to enable a user to quickly switch between these two states, without loosing their original multi-document layout. Single document mode was not ever intended to be a substitute and if we have mis-communicated that, I apologize.

Whether or not this hypothesis matches up with actual usage of JupyterLab is a question that we will be able to answer over time, with feedback from users (such as this) along with usage data. To help us answer UX questions, we are building a telemetry system that will enable us to collect usage data covering cases such as this. As with all things in JupyterLab the telemetry system will be an extension that can be installed/uninstalled based on a particular deployments needs.

Many thanks for the feedback!

**Comment by SimonBiggs** [comment]
You're welcome :) Thanks for all the hard work. JupyterLab is brilliant.

**Comment by sccolbert** [comment]
Thanks for the feedback @SimonBiggs One of the things we'd like to build is a nice UI to allow the user to easily modify their keyboard shortcuts. Since the various browsers reserve *so many* shortcuts for their own use, it's a pretty crowded space from which to pick defaults :)

**Comment by SimonBiggs** [comment]
@sccolbert I don't mind the shortcut personally now. The comment was more on user experience for new users.

**Comment by fperez** [comment]
I want to +1 the SD mode - while I haven't dared fully switching to JLab in teaching (too many students to handle the beta with right now), I think the SD mode will be perfect for lecturing. It will be great to be able to 'zoom in' to the main notebook being used in discussion, while still maintaining the rest of the JLab state relevant to the lecture.

I can see the issues with the shortcut (absolutely worth addressing), but overall I think SD mode will have some great use cases, and I'm glad we have it.

**Comment by jasongrout** [comment]
+1 on switching the keyboard shortcut, and *definitely* +1 on keeping the mode. I find it extremely useful, especially on a small screen, to be able to quickly zoom in and out of a single activity.
