### ISSUE TITLE
Double clicking within filename text while renaming a file

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#3697]
A discussion point.

Double clicking within text can be used elsewhere to select just a single word. When I want to change just a part of a file name, it is helpful to be able to double click on just the relevant section.

The filebrowser renaming user interface reacts to the double click by cancelling the renaming request. Personally I would prefer that double on selected text during renaming would not cancel the renaming. Up for discussion though.

Cheers,
Simon

**Comment by blink1073** [comment]
Sounds reasonable, thanks for the feedback!

**Comment by SimonBiggs** [comment]
You're welcome :). How's everything going on your end?

**Comment by blink1073** [comment]
All is well, thanks for asking!

**Comment by SimonBiggs** [comment]
Glad to hear it.

**Comment by blink1073** [comment]
Fixed by #5101
