### ISSUE TITLE
Broken kernel creates a broken application state 

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#3700]
Steps to reproduce:

* Open a notebook that uses a broken kernel
* "Error starting kernel" error prompt

![image](https://user-images.githubusercontent.com/512354/35290388-f68d8782-001e-11e8-8bd6-44a556f03e91.png)

* Notebook tab stuck in loading state and user can't close it
* Refresh the browser tab

![image](https://user-images.githubusercontent.com/512354/35290466-2ea34206-001f-11e8-98ba-e99d1bded40f.png)

The "Clear application restore state" item is missing from the menu now (but still available in the Commands pane), so most users will probably not know how to get themselves out of this broken app state. 

Better yet, we should prevent this app state from happening by adding a "close" button to the notebook tab before attempting to connect to the kernel, render the notebook, etc.

**Comment by ian-r-rose** [comment]
`Clear application restore state` got lost in the shuffle of the menu refactor, but we should probably add it back. What do you think, File menu? Help menu?

Agreed re: close button. I have also seen this before in the case where a mime-renderer fails.

**Comment by gnestor** [comment]
Maybe Settings menu?

**Comment by blink1073** [comment]
This is partially addressed by #3572.

**Comment by jasongrout** [comment]
> This is partially addressed by #4087.

Any comments on what else needs to be done for beta 2?

**Comment by jasongrout** [comment]
Closing as resolved - @gnestor, please reopen or comment here if we should do more here.
