### ISSUE TITLE
Jupyter now Trademarked

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#3701]
Based on the meeting today, we should mention of the Jupyter should likely have (tm) symbols of mention it is trademarked in the docs.

**Comment by davidrthorn** [comment]
Happy to update the documentation. So basically, every single time "Jupyter" appears, it should be replaced with Jupyter™?

**Comment by jzf2101** [comment]
@Carreau can you confirm?

**Comment by Carreau** [comment]
There is no need to add it everywhere (and actually I believe it's (R), not (TM)

TL:DR (quoting, and stripping irrelevant informations):
> Our lawyer recommend the following language be added to usages of the logo:
>  1) We need to start to use a "notice of registration" - we have to
tell people it is trademarks by using  "®" or "Reg. U.S. Pat. & TM
Off." or "Registered in U.S. Patent & Trademark Office."

My guess is that for website it is enough to have this notice in footers as we did on the Jupyter.org website:

> The Jupyter Trademark is registered with the U.S. Patent & Trademark Office.

**Comment by jzf2101** [comment]
See https://github.com/jupyter/governance/issues/42 for more details

**Comment by davidrthorn** [comment]
OK, I'll look at adding this to the footer for the docs

**Comment by blink1073** [comment]
Fixed by #3755, thanks @davidrthorn!
