### ISSUE TITLE
Julia kernels: unicode characters (autocomplete) not working.

### ISSUE THREAD

**Issue by mgiugliano** [jupyterlab/jupyterlab#3705]
While in any cell of a conventional Notebook, typing (e.g.)  ```\alpha``` followed by TAB replaces it with the unicode characters, this appears to be currently broken in Jupyter Lab.

**Comment by ian-r-rose** [comment]
Hi @mgiugliano , it looks like the completion reply coming from the IJulia kernel is missing the `metadata` field (new as of jupyter-client v 5.0, cf https://jupyter-client.readthedocs.io/en/latest/messaging.html#completion)

We previously were not reading that field, so the fact that it was missing was not causing any troubles. However, we just added experimental type annotations for the completer in #3508, which makes use of the `metadata` field. Reading from it is triggering an error, causing an early exit from completion requests.

**Comment by xiaoweiz** [comment]
I find that the tab-autocompletion doesn't work at all (not just for the unicode characters). Does the patch fix this issue as well?

**Comment by ian-r-rose** [comment]
I think this should fix the issue, @xiaoweiz.

**Comment by bicycle1885** [comment]
Maybe related: #2768.

**Comment by mgiugliano** [comment]
In version 0.31.8 autocomplete still does not work.

**Comment by ian-r-rose** [comment]
This fix has not been in a release yet. It should be in the next beta release of JupyterLab.

**Comment by MasonProtter** [comment]
Does not appear to be fixed in 0.31.9 either.

Will we have to wait for 0.32 ?

**Comment by ian-r-rose** [comment]
The fix for this (#3888) was not backported to 0.31.9, so it will likely need to wait for v0.32. Glad to see that a fix is also underway on the IJulia side in JuliaLang/IJulia.jl#632 .

**Comment by blink1073** [comment]
I just cut 0.31.10 with the fix.

**Comment by ptanure** [comment]
I'm using version 0.31.14 and it's still not working.

**Comment by ian-r-rose** [comment]
Can you check again what version you are using @ptanure? We are currently on 0.32.1, and as far as I know, 0.31.14 doesn't exist: https://pypi.org/project/jupyterlab/#history

It also appears that the fix to IJulia has been merged, though I am not sure if that has been released.

**Comment by ptanure** [comment]
That's weird. Here is a screenshot.

[image: image.png]

**Comment by ian-r-rose** [comment]
I don't see your screenshot?

**Comment by ptanure** [comment]
Sorry, @ian-r-rose, I just noticed it didn't show up in my reply. I hope this one does.

![unnamed](https://user-images.githubusercontent.com/23425381/40337171-9e706b60-5d33-11e8-8ccc-abdf4c3d5151.png)

Even so, I just updated it to 0.32.1 and the lack of autocomplete is still there. Do I have to tweak something in the settings?
