### ISSUE TITLE
Jupyterlab electron app startup issues after upgrading to 0.31.x

### ISSUE THREAD

**Issue by declanvk** [jupyterlab/jupyterlab#3716]
Hello,

I've been working on upgrading the Jupyterlab electron app to the 0.31.x release, and I've run into an issue that occurs during the startup of the app.

During the start of the electron app, it loads an `index.html` file that contains jupyter config data and requires the `index.js` script to setup and run the application. The issue arises because this all occurs in the `<head>` section of the file, before the body has been loaded.

As part of loading the jupyterlab application (`@jupyterlab/application`) the utility `PageConfig` is used in the `ServerConnection` namespace, specifically in this snippet: 
```
  // jupyterlab/packages/services/src/serverconnection.ts, lines 182-193
  /**
   * The default settings.
   */
  export
  const defaultSettings: ServerConnection.ISettings = {
    baseUrl: PageConfig.getBaseUrl(),
    pageUrl: PageConfig.getOption('pageUrl'),
    wsUrl: PageConfig.getWsUrl(),
    token: PageConfig.getToken(),
    init: { 'cache': 'no-store', 'credentials': 'same-origin' },
    fetch: FETCH,
    Headers: HEADERS,
    Request: REQUEST,
    WebSocket: WEBSOCKET
  };
```

As I referenced before, the `PageConfig` then tries to access the body of the document which hasn't been loaded yet, and a error occurs.

I attempted to move the module loading into the `onload` function, but I had a different set of issues relating to Typescript and importing things inside functions. @afshin @blink1073, I asked Brian and he suggested I tag you, if you have any insight on this I would really appreciate it. Also, if either of you are available for general questions about the upgrade, please let me know.

Thank you,
Declan Kelly

**Comment by blink1073** [comment]
Hi @declanvk, we can make it more robust to the absence of a document body [here](https://github.com/jupyterlab/jupyterlab/blob/b69d3b7bda788cbc4b228c9ac4e0292c86324695/packages/coreutils/src/pageconfig.ts#L180).  We are both in a workshop this week in Paris, but happy to answer questions asynchronously unless you want to wait until early next week.

**Comment by declanvk** [comment]
Thank you @blink1073 , if I have any further questions I'll catch you later on email or gitter?
