### ISSUE TITLE
Subprocess stdout with `\r\n` (DOS/Windows line endings) in it is silently not displayed

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab#3718]
I just ran into this weird bug that took me a while to figure out. I was working with data files that have been encoded in Windows, and have `\r\n` line endings instead of Unix-style just `\n`. If try to print their content from a subprocess like `cat` or `head` on a Mac, I get an empty output block:

![image](https://user-images.githubusercontent.com/57394/35375106-a147fc52-015a-11e8-90b3-84e89ee9168b.png)

Here's the code for convenience:

```python
a = "foo\r\nbar\r\n"*5
with open('foo.txt', 'w') as f:
    f.write(a)
    
!cat foo.txt
```

For reference, this works fine in classic, though interestingly, as I *open* that notebook in classic, there's still no output. But if I *run* the same code in classic, it's fine:

![image](https://user-images.githubusercontent.com/57394/35375173-ef7203be-015a-11e8-9fe6-f3e663da1edb.png)

But in Lab, the output gets emptied out, as is clear from the raw JSON:

```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "a = \"foo\\r\\nbar\\r\\n\"*5\n",
    "with open('foo.txt', 'w') as f:\n",
    "    f.write(a)\n",
    "    \n",
    "!cat foo.txt"
   ]
  },
```

Anyway, not a huge show-stopper, but it took me for a loop while preparing lecture :)

**Comment by jasongrout** [comment]
Here are the character codes in the first two lines of text in the display message sent over that we're displaying: [102, 111, 111, 13, 13, 10, 98, 97, 114, 13, 13, 10]. You'll notice that each line ends with `\r\r\n`, i.e., *two* `\r` characters, which the display machinery then correctly interprets as 'erase the line, then do a `\r\n` newline'.

I don't know why the file is getting translated to have `\r\r\n` as the line ending when displaying it.

**Comment by vidartf** [comment]
Python does "magic" with newlines when reading/writing in text format, c.f. (https://docs.python.org/2/library/functions.html#open). Maybe try to write in binary mode to test properly.

**Comment by jasongrout** [comment]
The interesting thing is that the file itself only has `\r\n`, but for some reason it seems that the `!cat` is transmitting `\r\r\n`.

Perhaps we should change the regex to test for `\r*\n` -> `\n`, since on a physical machine, doing a carriage return multiple time presumably is a no-op. Thoughts?

**Comment by jasongrout** [comment]
@fperez - you can print the contents of the file to not introduce the extra `\r`:

```python
with open('foo.txt', 'rb') as f:
    x=f.read()
print(x.decode('utf8'))
```

**Comment by jasongrout** [comment]
(In particular, we *are* processing `\r\n` correctly. This issue is something more than that...)

**Comment by ian-r-rose** [comment]
After doing some debugger spelunking, it looks like the issue is with [this](https://github.com/jupyterlab/jupyterlab/blob/master/packages/outputarea/src/model.ts#L383) function. I don't know what the fix should be just yet.

**Comment by ian-r-rose** [comment]
Specifically, the problem happens with [this] line. The function was introduced in #2761.

**Comment by jasongrout** [comment]
@ian-r-rose, I looked it at a while, and think that line is correct. It is processing `\r\n` correctly. What *isn't* working is that it is getting `\r\r\n` for some reason (see my comments above).

**Comment by fperez** [comment]
@jasongrout, yup :)

But we still need to fix this, running `!head file` is a super-common task, and right now for some bizarre reason it's not working right in lab under these particular conditions... In fact I ran into this with an [actual class example](http://www.ds100.org/sp18/assets/lectures/lec03/03-live-datatables-indexes-pandas.html), which as you can see, is still displaying the problem:

![image](https://user-images.githubusercontent.com/57394/35422071-9e7bed70-01fb-11e8-9c77-a5d16fbf4dde.png)

As you can see, in fact I was showing them both the python way and the OS one... I didn't notice that my last edits to this particular nb were done on Lab, and I ended up uploading to the public class site this one with the problem. I'll need to fix that now :)

In any case, this isn't a huge problem, but we should fix it, it's a real-world regression.  Happy to test further, but I think it's pretty straightforward to reproduce (if not to fix :)

Thanks for looking into it, guys!

**Comment by fperez** [comment]
Some extra info that I think may be related... I was working on a very simplistic progress bar for a class utility, which uses `\r` to overwrite the line without having to resort to `clear_output`. This code works at the terminal:

![image](https://user-images.githubusercontent.com/57394/35849846-d92ef536-0ad7-11e8-8a55-19d7a5c9f914.png)

and classic:

![image](https://user-images.githubusercontent.com/57394/35849858-e41523ee-0ad7-11e8-8f8c-832c0c6955b0.png)

But in Lab (v. 0.31.2) produces a bunch of blank vertical space:

![image](https://user-images.githubusercontent.com/57394/35849872-f0fe1b4c-0ad7-11e8-80b0-3a6e4e9aa0e7.png)

For testing convenience, the self-contained code:

```python
def pbar():
    from time import sleep
    step = 40
    while step > 0:
        step -= 1
        print('[' + '#'*(41 - step) + (step)*' ' + ']\r', end='')
        sleep(0.05)
```

I suspect these are related...
