### ISSUE TITLE
Changing "Text Editor Theme" / "Text Editor Keymap" seems to have no effect

### ISSUE THREAD

**Issue by aldanor** [jupyterlab/jupyterlab#3723]
While changing the global theme works right off the bat, changing `Text Editor Theme` or `Text Editor Keymap` (whether via menu or directly via CodeMirror JSON settings) seems to have no effect, whether visual or functional.

(Chrome / Firefox Nightly, OS X, jupyterlab v0.31.1 from conda-forge)

Wondering if there is anything specific that needs to be done or tweaked for it to work?

**Comment by ian-r-rose** [comment]
Hi @aldanor, they seem to work fine for me. Can you try on `v0.31.1`? Note that these settings only apply to the text editor, not notebooks.

**Comment by aldanor** [comment]
@ian-r-rose It's actually `v0.31.1`, I've just checked. Nope, weirdly enough it doesn't seem to do anything. (I've just checked Safari as well, so it doesn't look like a browser issue)

**Comment by ian-r-rose** [comment]
Are there any errors in the Javascript console when you try to switch them?

**Comment by aldanor** [comment]
Nope, doesn't look like it.

![jlab-theme](https://user-images.githubusercontent.com/2418513/35418147-94ad018a-0228-11e8-9884-47fbdeba55a0.gif)

**Comment by ian-r-rose** [comment]
It looks like you are using a notebook. Those settings only apply to the plain text editor. We would like the notebook to be more easily theme-able and have more flexibility in keymaps, but those are more subtle use-cases and we have not done them yet.

**Comment by aldanor** [comment]
Oh - gotcha... It's a bit confusing, I guess (as in not entirely obvious that 'text editor' doesn't apply to 'codemirror cell code editor'. Closing for now then.

Thanks!
