### ISSUE TITLE
Tab completion for magics? (% and %%)

### ISSUE THREAD

**Issue by aldanor** [jupyterlab/jupyterlab#3725]
It would be nice if typing `%` or `%%` and pressing `<Tab>` would complete magics (it currently just inserts a tab character). 

It currently works if you also type the first letter, e.g. `%r`, and then press tab, but would be great if you could get the whole list (even more so since there's a fuzzy completer).

**Comment by blink1073** [comment]
Thanks, @aldanor!  This is a regression from the classic notebook.
