### ISSUE TITLE
Feature Request: Notebook Find and Replace

### ISSUE THREAD

**Issue by ckaros** [jupyterlab/jupyterlab#3745]
In the classic notebook I am able to do a find and replace across all code cells. It appears that find and replace is only available in the text editor plugin on jupyter lab. Is this  the case?  

I can do a find within a single cell but not across a whole notebook (unless it is on the browser level, in which case I end up find things outside of the notebook), and cannot do a replace at all.

Is this feature planned for the 1.0 release?

**Comment by blink1073** [comment]
Hi @ckaros, this is a planned feature, and is covered by https://github.com/jupyterlab/jupyterlab/issues/1074.  Cheers!
