### ISSUE TITLE
Can't set the first button as default one for Dialog

### ISSUE THREAD

**Issue by mjurowicz-xsolve** [jupyterlab/jupyterlab#3746]
When creating new Dialog and passing the `defaultButton: 0` option the Dialog sets the default button to `buttons.length - 1` . The faulty code is:
```
defaultButton: options.defaultButton || buttons.length - 1,
```
It should allow the `0` number as well.

**Comment by scottdraves** [comment]
https://github.com/jupyterlab/jupyterlab/blob/0e0df143d50e1bdac676b5f1d157b116bdc765fc/packages/apputils/src/dialog.ts#L758
