### ISSUE TITLE
Files not sorting correctly by modification

### ISSUE THREAD

**Issue by stefanv** [jupyterlab/jupyterlab#3761]
After clicking on the "Last Modified" column heading in the file browser:

![last_modified](https://user-images.githubusercontent.com/45071/35644723-9f4ac55a-067e-11e8-908d-7d99ebc0eb92.png)

**Comment by blink1073** [comment]
Hi @stefanv, the sorting is done by: folder, notebooks, and then by other files, so what you are seeing is expected.  Whether that is desired is another question.

**Comment by stefanv** [comment]
I see; yes, I find that quite confusing.  Feel free to close as you see fit.

**Comment by blink1073** [comment]
Let's leave this open as reference.  Cheers!

**Comment by stefanv** [comment]
Thank you!
