### ISSUE TITLE
Gonna take a shot at "files.html" animations

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#3777]
@ian-r-rose @Carreau I still don't think I have youtube access. I'm going to upload them to my own account and then we can swap the links whenever we get that figured out.

http://jupyterlab-tutorial.readthedocs.io/en/latest/user/files.html is the page I'm working on. Just giving a note here so that we don't duplicate efforts

**Comment by ian-r-rose** [comment]
Sounds good! Would you mind making a PR to the `jupyterlab-media` repo so that we have the animations under version control?

**Comment by ian-r-rose** [comment]
I will take a crack at `file_formats.html`

**Comment by choldgraf** [comment]
@ian-r-rose what kind of PR are you imagining? uploading the videos themselves, but still linking in the docs from the youtube channel?

**Comment by ian-r-rose** [comment]
I am thinking of uploading the `.mp4` videos to the `jupyterlab-media` repo, but still linking to the versions on the YouTube channel.

**Comment by Carreau** [comment]
@choldgraf I did invite you, did you not receive invites ? Try heading to https://plus.google.com.

I can't re-send an invite, google tell me you are already invited.

**Comment by Carreau** [comment]
> I can't re-send an invite, google tell me you are already invited.

I removed and re-added you, maybe that will work.

**Comment by choldgraf** [comment]
@Carreau no emails from google - want to figure this out on gitter? I have a feeling I'm doing something stupid

**Comment by Carreau** [comment]
ok

**Comment by Carreau** [comment]
PEBKAC: https://myaccount.google.com/brandaccounts and @choldgraf  notifications were all disabled.
