### ISSUE TITLE
Can't create a view for cell output for the last cell in a notebook

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#3782]
This works for all other cells, but not the last cell.

Since I'm making videos anyway :-)  :  

![2018-02-01_11-45-15](https://user-images.githubusercontent.com/1839645/35699600-68556c04-0745-11e8-8197-a15eab9cf8a4.gif)

**Comment by blink1073** [comment]
Great catch!  Working on a fix now.
