### ISSUE TITLE
Add ability to view HTML files in Tab

### ISSUE THREAD

**Issue by mflevine** [jupyterlab/jupyterlab#3789]
In Jupyter Notebook, we are able to open .html files as a webpage with the View button and edit the raw with the Edit button. Jupyter Lab only has edit raw currently. Can we have a preview with HTML option?

**Comment by ian-r-rose** [comment]
Hi @mflevine, thanks for the thought! This is currently being tracked #2369, and there is some early work on an extension [here](https://github.com/canavandl/jupyterlab_sandbox). I will close this in favor of those issues, but please continue the discussion there.
