### ISSUE TITLE
Delete Files from JupyterLab UI

### ISSUE THREAD

**Issue by rsubra13** [jupyterlab/jupyterlab#3792]
Hi,
When I try to delete the files from jupyterLab, I get an error "Delete Failed
Invalid response: 500 Internal Server Error"

**Version:**
Beta 1 Release
Version 0.31.2

**Comment by blink1073** [comment]
Hi @rsubra13, can you please run `jupyter lab` from a terminal, and see if there is any log output associated with the file you are deleting?

**Comment by wkvolkman** [comment]
Hello, this is a duplicate of https://github.com/jupyterlab/jupyterlab/issues/3793 for which I provided the log information.
