### ISSUE TITLE
Icons loading on demand slows their rendering

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#3798]
I confirmed what @ian-r-rose observed this morning that our SVG icons are being loaded from the server on demand. When working on remote JupyterLab instances, this can take a long enough that various icons being to be glitchy.

Is there a way to ship these inline?

**Comment by ian-r-rose** [comment]
I took a closer look at this: by default small SVGs are already inlined, with an important exception: icons and CSS in themes are outside of the normal webpack build, and those SVGs are therefore not bundled in the same way.

I don't see a simple way around this at the moment. The theme manager loads the CSS with urls for the icons on to the page, and short of preprocessing that CSS with data URIs, it seems too dynamic.

**Comment by saulshanabrook** [comment]
So we could add webpack to both of the theme plugins to compile their CSS to one file with inlined SVGs.

**Comment by ian-r-rose** [comment]
Yeah, I think that is the most likely solution to this.
