### ISSUE TITLE
Overhaul README

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3832]
@jzf2101 said she is revamping the README to pull out content and point to the docs as the canonical source. This is to keep track of the issue until a PR is submitted.

**Comment by jasongrout** [comment]
I just read through the readme, and it actually doesn't look bad to me. It's about on par with the FAQ being in JupyterLab. I think we can wait until beta 2 to overhaul the readme more significantly.

@jzf2101 - feel free to set this back to beta 1 if you want

**Comment by jzf2101** [comment]
@jasongrout @ellisonbg I'm inclined to believe most people get their installation instructions from the README and other things from the actual docs.  Do we want to move the team to the docs?

**Comment by jasongrout** [comment]
> Do we want to move the team to the docs?

the team?

I think it's fine to have the installation instructions repeated in both the readme and the docs.

**Comment by jzf2101** [comment]
Team section I mean

**Comment by jzf2101** [comment]
Will move contributing.md to other issue
