### ISSUE TITLE
Beta: Update repo description string

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#3839]
Once the beta is out, the repo description string should probably be updated as well. It currently says: "JupyterLab computational environment. This is a very early preview, and is not suitable for general usage yet."

**Comment by vidartf** [comment]
I noticed this, because it is also in the `<title>` of the main repo page.

**Comment by taion** [comment]
It looks like the beta is out now.

Given that the README says:
>The beta releases are suitable for general usage.

The description should say the same.

cc @jasongrout

**Comment by blink1073** [comment]
Fixed, thanks!
