### ISSUE TITLE
Keyword for denoting a JupyterLab extension

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3841]
@vidartf and I are discussing on https://github.com/jupyterlab/extension-cookiecutter-js/pull/21 a standardized keyword for denoting a jlab extension. I propose we use `jupyterlab-extension`:

* includes both jupyterlab and extension
* uses a hyphen instead of a space, so it's easier to specify and search for in systems and on the command line.

We could use this across GitHub (already in use as a topic), npm, pypi, conda, etc.

Does conda have keywords? I didn't find a mention of them.

**Comment by ian-r-rose** [comment]
I like the idea of using a dash.

**Comment by vidartf** [comment]
:+1:

**Comment by vidartf** [comment]
I'll do the legwork tomorrow for spreading it to those extensions that currently use a space (<10), unless somebody has any counter arguments bu then.

**Comment by afshin** [comment]
👍

**Comment by blink1073** [comment]
:+1:

**Comment by dhirschfeld** [comment]
How about the npm install command - some are prefixed (namespaced?) with `@jupyterlab` whilst others aren't. Some from my dockerfile:
```
jupyter labextension install @jupyterlab/geojson-extension
jupyter labextension install @jupyterlab/plotly-extension
jupyter labextension install @jupyterlab/vega3-extension
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install @jupyterlab/hub-extension
jupyter labextension install @jupyterlab/github
jupyter labextension install jupyterlab_bokeh
jupyter labextension install qgrid
```

Might be nice to have a consistent namespacing there too? Or maybe `@jupyterlab` is reserved for (semi-)official extensions?

e.g. I always have to look up the ipywidgets one - `@jupyterlab/widget-extension` would be more consistent and hence memorable.

**Comment by vidartf** [comment]
I've committed or suggested changes to the packages I could find, so I'll consider this as completed, though I assume it will take some time until the changes propagate out to releases on the npm registry.

**Comment by vidartf** [comment]
@scottdraves (I didn't bother to go through the CLA process for beakerx-jupyterlab, so I'm pinging you here).

**Comment by jasongrout** [comment]
The @jupyterlab namespace is the official namespace we use on npm. As for
the widget extension, we do plan to migrate that to core jupyterlab,
actually.

**Comment by vidartf** [comment]
Feel free to close this, as any further tasks happen in other repositories.

**Comment by scottdraves** [comment]
so our extension should be named "jupyterlab-beakerx" instead of "beakerx-jupyterlab" like it currently is?

**Comment by vidartf** [comment]
@scottdraves much simpler 😄  This is about having the following in the `package.json`:
```json
"keywords: [
  "jupyterlab-extension"
]
```

**Comment by scottdraves** [comment]
ah ok.  is this OK or you really mean exactly one keyword:
```
"keywords": [
    "ipywidgets",
    "jupyterlab",
    "jupyterlab-extension"
  ],
```

**Comment by vidartf** [comment]
Precisely, the version with the dash ("jupyterlab-extension").

**Comment by vidartf** [comment]
That is, have whichever keywords you want, but have it include the standardized one.

**Comment by scottdraves** [comment]
thx that should do it

**Comment by jasongrout** [comment]
Okay, sounds like the decision is made, and is already being pushed out (thanks @vidartf!), so I'm closing this as answered.
