### ISSUE TITLE
[Question] How to start directory tree from cwd with no previous notebooks open

### ISSUE THREAD

**Issue by jolespin** [jupyterlab/jupyterlab#3843]
With `Jupyter Notebooks` I grew accustomed to opening my `Jupyter` instance in a particular directory and navigating everything from there.  With `Jupyter Lab`, I noticed that it keeps open all of the notebooks I had open last time I was using it (even if the terminal was closed) and starts from that last directory I was using.  **Is there a way to change this in the preferences so I can start with a clean slate from my current working directory?**

**Comment by blink1073** [comment]
Hi @jolespin, this will be available in the next beta release (0.32) pending #3687.
