### ISSUE TITLE
Text editor cursor invisible when JupyterLab theme "dark" and text editor theme "default" or "xq-light"

### ISSUE THREAD

**Issue by elehcim** [jupyterlab/jupyterlab#3847]
Hello,
I'm using jupyterlab, 0.31.4, py36_0  installed with conda.
The text editor cursor is invisible when JupyterLab theme is dark and the text editor theme is either default or xq-light.
It is visible instead when JupyterLab theme is light and for any text editor theme.

**Comment by cancan101** [comment]
I am using OS X + Chrome and the default themes and I do not see the cursor. I tried changing the theme and still do not see the cursor.

**Comment by akshay-raj-dhamija** [comment]
I am facing the same issue in the following version
``jupyter lab --version 0.31.8``

**Comment by ian-r-rose** [comment]
Hi @akshay-raj-dhamija, this has been fixed in #3962, and will be available in the next release.

**Comment by cosmicBboy** [comment]
I'm using jupyter lab 0.31.10, python 2.7 and am unable to see the cursor in the text editor, regardless of the theme
