### ISSUE TITLE
`tarfile.ReadError: empty file` after BSOD

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#3849]
I was installing a labextension (`jupyterlab-drawio`) and in the middle of it windows crashed with a BSOD. Now I can't do any lab-related things, as they all return an error like:

`tarfile.EmptyHeaderError: empty header`

and 

`tarfile.ReadError: empty file`

is there a way to "clean" jupyterlab in these circumstances?

**Comment by jasongrout** [comment]
`jupyter lab clean` doesn't work?

**Comment by ian-r-rose** [comment]
@jasongrout I don't think that will clear the cached state database in `localStorage`.

@choldgraf Try going to `lab/workspaces/blah`

This also relates to #3687.

**Comment by choldgraf** [comment]
it returns the "empty file" error :-)

**Comment by choldgraf** [comment]
@ian-r-rose I'm not sure what you mean...I can't start jupyterlab at all

**Comment by ian-r-rose** [comment]
Ah, I misunderstood, I thought it was a dead splash screen/invalid state db.

**Comment by ian-r-rose** [comment]
You can try removing the offending tarball by going to the `extensions` directory in the directory given by `jupyter lab path`

**Comment by choldgraf** [comment]
lol, `jupyter lab path` also raises the error

**Comment by ian-r-rose** [comment]
ouch

**Comment by ian-r-rose** [comment]
How about go to `<sys-prefix>/share/jupyter/lab` and blast everything away?

**Comment by choldgraf** [comment]
![](https://media.giphy.com/media/XUFPGrX5Zis6Y/giphy.gif)

that seemed to fix it

**Comment by choldgraf** [comment]
I wonder if it's worth having a `clean` command that exists separately from `jupyter lab` such that if the whole `lab` shebang gets corrupted you can still run it?

**Comment by ian-r-rose** [comment]
Quite possibly.

**Comment by choldgraf** [comment]
I'm gonna close this as fixed! Thanks for the help :-)
