### ISSUE TITLE
jupyter lab freezes when reloading after opening a not supported file. 

### ISSUE THREAD

**Issue by piperod** [jupyterlab/jupyterlab#3859]
By mistake I open a .mp4 file, so it  showed a bad format error, however It created a new tab that was not possible to close until I wen to close all widgets. Then if I keep it open and serve again the lab it doesn't open and get's stuck with the bad format error. 

I am using jupyter 4.4.0 and google chrome.

**Comment by jasongrout** [comment]
Thanks for the report! We should investigate what is happening with that bad tab, but we should also make a plugin that understands basic audio and video formats too. Understanding the bad tab is probably more involved, but a plugin that understands basic audio and video formats is probably a "good first issue", so I'll open a new issue for that.
