### ISSUE TITLE
Drag and drop multiple files

### ISSUE THREAD

**Issue by mocquin** [jupyterlab/jupyterlab#3863]
In the file explorer tab, I can drag and drop one file or one folder onto another sub-folder to move it in the said sub-folder, but when I select multiple files/folder, the drag and drop just doesn't work.

It seems like the drag on multiple files isn't allowed.

**Comment by ian-r-rose** [comment]
Hi @mocquin, what version of JupyterLab are you using. This should have been fixed in #3729. Can you try updating your install?

**Comment by mocquin** [comment]
Hi @ian-r-rose, thanks for your response. Indeed I was using v0.27.0. I installed it via Anaconda but did't thought to check the version.
A pip install jupyterlab --upgrade did the trick and now with version 0.31.5 it works like a charm ;)
