### ISSUE TITLE
%debug broken in 0.31.5?

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#3866]
Trying to print a variable drops you out of the debugger. After a few times you can't even get back into the debugger. Hopefully the gif explains it better!

![debug](https://user-images.githubusercontent.com/881019/36181028-9feaf64c-116e-11e8-9f5c-f33c86b22f71.gif)

Is anyone else seeing this?

**Comment by vidartf** [comment]
`n` is a pdb shortcut for "execute next statement". I think you need to use e.g. `pp n` (pretty-print variable n), or maybe `!n`, consult the pdb docs.

**Comment by dhirschfeld** [comment]
Even that being the case, `print(n)` also fails as did the original problem where I came across this bug.

If you would like to repro it yourself you could confirm that it is indeed a bug. It's *definitely* a bug with my setup but maybe it's something specific to my platform / packages so a concrete confirmation or otherwise on your platform would be useful...

For ref, I'm on:
```
win64/py36

jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.2                    py36_0  
jupyter_console           5.2.0            py36h6d89b47_1  
jupyter_core              4.4.0            py36h56e9d50_0  
notebook                  5.4.0                    py36_0 
ipykernel                 4.8.1                    py36_0    conda-forge
ipython                   6.2.1            py36h9cf0123_1  
```

**Comment by dhirschfeld** [comment]
Seems to work fine in the classic notebook (using the `/tree` handler so the exact same setup otherwise)

**Comment by jasongrout** [comment]
`%debug` does let me print, but the order of the output seems a little off. This is in a clean environment: `conda create -n debug jupyterlab` with jlab 0.31.5.

![debug](https://user-images.githubusercontent.com/192614/36234140-4ef3c482-119e-11e8-8b6c-bfc73ddbcc70.gif)

**Comment by jasongrout** [comment]
(I'm using all packages from conda-forge, if it makes a difference)

```
name: debug
channels:
  - conda-forge
dependencies:
  - appnope=0.1.0=py36_0
  - bleach=2.0.0=py_1
  - ca-certificates=2018.1.18=0
  - certifi=2018.1.18=py36_0
  - decorator=4.1.2=py36_0
  - entrypoints=0.2.3=py36_1
  - html5lib=1.0.1=py_0
  - ipykernel=4.8.1=py36_0
  - ipython=6.2.1=py36_1
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.11.1=py36_0
  - jinja2=2.10=py36_0
  - jsonschema=2.6.0=py36_1
  - jupyter_client=5.2.2=py36_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=0.31.5=py36_1
  - jupyterlab_launcher=0.10.4=py36_0
  - libsodium=1.0.15=1
  - markupsafe=1.0=py36_0
  - mistune=0.8.3=py_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - ncurses=5.9=10
  - notebook=5.4.0=py36_0
  - openssl=1.0.2n=0
  - pandoc=2.1.1=0
  - pandocfilters=1.4.1=py36_0
  - parso=0.1.1=py_0
  - pexpect=4.4.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pip=9.0.1=py36_1
  - prompt_toolkit=1.0.15=py36_0
  - ptyprocess=0.5.2=py36_0
  - pygments=2.2.0=py36_0
  - python=3.6.4=0
  - python-dateutil=2.6.1=py36_0
  - pyzmq=17.0.0=py36_3
  - readline=7.0=0
  - send2trash=1.4.2=py_0
  - setuptools=38.5.1=py36_0
  - simplegeneric=0.8.1=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.20.1=2
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - tk=8.6.7=0
  - tornado=4.5.3=py36_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5=py36_0
  - wheel=0.30.0=py36_2
  - xz=5.2.3=0
  - zeromq=4.2.3=2
  - zlib=1.2.11=0
```

**Comment by dhirschfeld** [comment]
That's unfortunate (for me) if it is something specific to my setup :/
It's definitely not working for me:

![debug](https://user-images.githubusercontent.com/881019/36234323-1762bddc-1236-11e8-887a-e21b531d62f1.gif)

**Comment by dhirschfeld** [comment]
Ok, may have found the culprit....

**Comment by dhirschfeld** [comment]
If you press `Shift-Enter` in the debug prompt (instead of just `Enter`) is appears to drop you out and hang your kernel.

I guess I was just pressing `Shift-Enter` because of muscle-memory from the notebook.

**Comment by jasongrout** [comment]
I was pressing enter.

**Comment by jasongrout** [comment]
What does the classic notebook do? Does shift-enter work there?

**Comment by ian-r-rose** [comment]
What is the intended behavior upon pressing shift-enter when the debugger is running? I am seeing the same hanging behavior. It seems like maybe ipdb is getting stuck, with no possibility for exiting?

**Comment by dhirschfeld** [comment]
NB: Pressing `Shift-Enter` at the debug prompt in the classic notebook has the same effect as `Enter` and doesn't throw you out / hang

**Comment by ian-r-rose** [comment]
That seems like a fairly serious failure mode to me. I was unable to get anything to run without restarting the kernel.

**Comment by dhirschfeld** [comment]
Not as serious as you can't debug at all, but pretty serious because if you accidentally hold down shift while pressing enter your kernel will hang.

**Comment by jasongrout** [comment]
Looks like the stdin is only listening for Enter: https://github.com/jupyterlab/jupyterlab/blob/master/packages/outputarea/src/widget.ts#L649

**Comment by jasongrout** [comment]
Oh, but probably its more subtle than that. Shift Enter is being trapped on the capture phase earlier than that, right? Is there an accepted way to preempt the keyboard handling of the notebook? Or maybe better is to register a keyboard shortcut for stdin handling with the actual keyboard shortcut system.

**Comment by ian-r-rose** [comment]
What makes you think that it is being captured earlier? I don't see that here: https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook/src/widget.ts#L1181

**Comment by jasongrout** [comment]
I was thinking that the keyboard shortcut system worked in the capture phase, so the shift-enter keyboard shortcut would be triggered first from that.

**Comment by ian-r-rose** [comment]
Hmm, if that's the case, then you are probably right. We may need to register a stdin keyboard shortcut.
