### ISSUE TITLE
Delegating main menu creation for native app

### ISSUE THREAD

**Issue by declanvk** [jupyterlab/jupyterlab#3873]
Hello (@blink1073),

In attempting to bring main menu functionality to the Electron app, I need to duplicate the same process of adding all the file, edit, view, kernel menus to my own particular menu implementation. Currently the methods that populate each individual menu are not visible to consumers of the module. The file in particular would be [`packages/mainmenu-extension/src/index`](https://github.com/jupyterlab/jupyterlab/blob/master/packages/mainmenu-extension/src/index.ts) and the methods I need are:
- `createFileMenu`
- `createFileMenu`
- `createKernelMenu`
- `createRunMenu`
- `createSettingsMenu`
- `createViewMenu`
- `createTabsMenu`

Thanks,
Declan

**Comment by ian-r-rose** [comment]
It breaks some of the encapsulation of the `mainmenu-extension`, but I think that you are right @declanvk: it's better to expose those methods in the module than ask you to duplicate the functionality.

**Comment by declanvk** [comment]
Thanks!
