### ISSUE TITLE
Resize columns of file browser

### ISSUE THREAD

**Issue by mocquin** [jupyterlab/jupyterlab#3875]
In the file browser, say I have long filenames and that I'm not interested in the "last modified" information of my files.

It seems like I can't resize the "columns" of the file browser, in order for instance to display all my long filenames and hide the last-modified-information.

**Comment by hoishing** [comment]
+1 for this feature request, it does help saving the real estate,  especially on small screen

**Comment by westurner** [comment]
- [ ] Where in the source is this [widget, ui control]? [URL]
- [ ] Does the existing widget support resizing a column?
  - [ ] If so, can we just add that attribute for that column of the ~datagrid?
  - [ ] If not, what widget do we need in order to be able to resize a column?
    - [ ] There's like a CSV viewer that's maybe built-in now? Does *that* have resizeable columns either yet? It may be easy to ENH the UBY usability of the {CSV Viewer, File browser, and [...]} with this upgrade that might as well test this consistently if it's not something that there's already a test for in the widget library
      - [ ] Which other components could *reuse* new widget column resizing column?
        - [ ] CSV viewer
        - [ ] File browser {last modified, }
      - [ ] Is there already a test for column width modification in the widget library?
      - [ ] Is there already functionality to store e.g. the "last modified" column width setting at least for the File browser column(s)?

**Comment by stefansimik** [comment]
I wanted to report the same issue. 
It is very uncomfortable, that Last modified column takes so much space and content is often half-empty.

It should be resize-able, because most of the time, people are not ACTIVELY interested in watching LastModified column and
many would prefer to use precious screen space by open notebooks.
