### ISSUE TITLE
Uninstallation of JupyterLab and share/jupyter/lab directory content

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#3877]
The uninstallation of the jupyterlab package leaves the `share/jupyter/lab` content.

There is not an obvious way to fix this but it actually bit me as I had some extensions in `staging` etc.. Maybe the conda package could have a post-unlink script removing the relevant content from this directory.

**Comment by blink1073** [comment]
I'm wary of doing anything in the post-unlink script since it only works with conda-forge packages.

**Comment by SylvainCorlay** [comment]
A hack in the case of wheels:

With `data_files`, if you specify an *empty list* of files for a given path, the entire directory is deleted upon uninstallation!

```
    data_files=[
        ('some_path', []),
    ],
)
```

But I think that it should be considered a bug in pip, since it could be used to delete the entire content of any subdirectory of the sys prefix...

**Comment by SylvainCorlay** [comment]
Closing as I don't think this should change.
