### ISSUE TITLE
Table of content (toc) for notebooks

### ISSUE THREAD

**Issue by mocquin** [jupyterlab/jupyterlab#3878]
So far I've been using jupyter notebooks with a great nb-extension called [toc2](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/toc2). Examples can be found in the [doc](http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html).

Everything is detailed on the dedicated page, but basically, here is what it does:
- based on the markdown content of the notebook, it automatically adds number or letter to header lines (which makes the first level 1 header "1", the second level 1 header "2", the second level 2 header in the second level 1 header "2.2", and so on)
- then creates a table of content in an HTML cell at the top of the notebook, with links to the corresponding headers of the notebook
- allows you to display a tab (dragable, sizeable, dockable) with the same table of content, that you can click to go to any header in your notebook
- there is also a "navigate" menu at the top of the notebook, which once again allows you to browse your notebook based on the markdown header content.

There is already [an issue on the jupyter-notebook project](https://github.com/jupyter/notebook/issues/1498), but the solution is simply to use the notebook extension...

From what I understood (correct me if I'm wrong), not all the nb-extensions can be used with jupyterlab, and I would love to have this kind of "table of content" in the notebook within jupyterlab.

I'm not saying I would like to have the exact same functionalities, but for me the automatical-numbered header and at least one way to browse the notebook with the headers are some really powerful tools for UX.

**Comment by vidartf** [comment]
Duplicate of #723?

**Comment by mocquin** [comment]
Yes indeed. I coudn't find it with a "table of content" search, didn't thought to try "table of contentS"...

**Comment by ebeisaac** [comment]
This link worked for me: 
https://www.npmjs.com/package/jupyterlab-toc

**Comment by WenbinFei** [comment]
@ian-r-rose I got the following error when installing jupyterlab-toc on windows, do you have any idear?
Many thanks

Errored, use --debug for full output:
ValueError:
"jupyterlab-toc@0.2.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.15.4-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/application
>=0.15.4-0 <0.16.0-0    >=0.16.2-0 <0.17.0-0 @jupyterlab/apputils
>=0.15.4-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/docmanager
>=0.15.4-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/fileeditor
>=0.15.4-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/notebook
>=0.15.4-0 <0.16.0-0    >=0.16.0-0 <0.17.0-0 @jupyterlab/rendermime
