### ISSUE TITLE
bug: printing '\b' at start of new line causes a hard freeze

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#3881]
Printing the backspace escape character `\b` in certain places, such as at the start of a new line, causes a hard freeze. In a jupyterlab python notebook, if I run a cell with the code:

    print('foo')
    print('\b')

all of jupyterlab freezes and has to be reloaded. You get the same freeze if you try to backspace past an initial character on the first line:

    print('a\b\b')

On the other hand, this works:

    print('\b', end='')

though it does print a line of white space, which I'm not sure is the correct behavior.

**Comment by ian-r-rose** [comment]
I can reproduce this. Investigating futher...

**Comment by telamonian** [comment]
There seems to be some other, probably related, problems with the implementation of `\b`. For example, printing an odd number of `\b`'s in a row always removes exactly one character:

    print('foobar\b\b\b\b\b\b\b')
    >>> fooba

but I figured the hard freeze would be the priority

**Comment by ian-r-rose** [comment]
Infinite loop [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/outputarea/src/model.ts#L391)

**Comment by telamonian** [comment]
Maybe move the `^\x08+` replacement line into the loop? That would fix the infinite loop, but not the weird behavior with multiple `\b`'s canceling each other out. Does the

    tmp = tmp.replace(/.\x08/gm, '');

line search the string in reverse order? That would explain that

**Comment by jasongrout** [comment]
I wonder how fast a simple stepping through the string would be, performing the operations as necessary.
