### ISSUE TITLE
Out-of-order kernel message handling

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#3884]
I *think* that the way comm objects are processed, we can have two comm messages come in from the kernel and they will be handled out of order. Take a look: https://github.com/jupyterlab/jupyterlab/blob/1bb59caa1e87db76f0ae31ee93453fc6d0eaab98/packages/services/src/kernel/default.ts#L839-L868

(I think this is true - I haven't verified it for sure, but the code seems to make it possible...)

If comms A and B are opened, but A returns a promise to a comm object, and B immediately returns, then the logic above says that B's messages will be handled immediately, while A's messages will be handled at some undetermined time in the future. This means that if a message for A comes over the wire, then a message for B, it's very possible that B's handler will run first, since A's handler is deferred. This can be problematic if, for example, B's handler depends on A's handler being run. For example, in ipywidgets we can have multiple comm objects that depend on each other, so preserving the order of execution is crucial.

In the classic notebook kernel, we took care that *every* kernel message handling function could return a promise all the way up the chain to the basic kernel message handling loop, and the kernel would not start handling the next message until the previous message was handled.

**Comment by jasongrout** [comment]
@blink1073 points out on gitter that a simple trick is to remove https://github.com/jupyterlab/jupyterlab/blob/1bb59caa1e87db76f0ae31ee93453fc6d0eaab98/packages/services/src/kernel/default.ts#L797 (and maybe the line after as well?), which basically just ensures that the promise is always used. This doesn't solve the out-of-order problem entirely, but may make it less prevelant.

**Comment by blink1073** [comment]
I don't think we should change anything here for beta1 considering the fix in ipywidgets is working and I still the the logic is equivalent to the classic notebook here for comms.

**Comment by blink1073** [comment]
On second thought, let's be safe and remove the synchronous code paths for beta2.

**Comment by jasongrout** [comment]
I opened an issue for the continued work on async processing in #4188.
