### ISSUE TITLE
Text editor writes LF vs CRLF line endings on Windows?

### ISSUE THREAD

**Issue by wkzhu** [jupyterlab/jupyterlab#3901]
I'm using Windows 7 Professional and observe the following:

* if I open a .py file in Jupyterlab (say `constants.py`) it immediately opens with "unsaved changes" without any edits.

![constants](https://user-images.githubusercontent.com/4811862/36441516-eab8bbf6-1640-11e8-95d5-56cd09c7ecf0.PNG)
* if I then save the file, `git status` will note that the file was modified. `git diff` will give this 
warning:

```warning: LF will be replaced by CRLF in constants.py```

Could it be that Jupyterlab text editor is writing the wrong line endings for Windows?

More context on LF vs CRLF:
https://stackoverflow.com/questions/5834014/lf-will-be-replaced-by-crlf-in-git-what-is-that-and-is-it-important

**Comment by blink1073** [comment]
Hi @wkzhu, we are using LF for all line endings, so what you are seeing is expected.  We could guess the line endings of the file and set it accordingly.

**Comment by wkzhu** [comment]
That functionality would be welcomed! Thank you...

**Comment by sccolbert** [comment]
I'm not sure how I feel about trying to guess line endings automatically, particularly in a browser environment. I'd prefer to just make it a user setting.

**Comment by vidartf** [comment]
>  I'd prefer to just make it a user setting.

+1, but with one option being "automatically detect" :)

**Comment by t-makaro** [comment]
I'd just like to point out vscode's solution is to have an option on the status bar.
![image](https://user-images.githubusercontent.com/18018386/47106838-7fbf3000-d1fc-11e8-8ec5-3754e6f23fb0.png)

Makes it very transparent.
