### ISSUE TITLE
tornado.websocket.WebSocketClosedError

### ISSUE THREAD

**Issue by garyzhalo** [jupyterlab/jupyterlab#3902]
Training models and outputting progress with progress bar and printing work well before 0.31.2. After upgrading to 0.31.5-0.31.8, the whole jupyterlab page freezes. Kernel is still running and the training works well. After downgrading to 0.31.2, everything works well again.

**Comment by blink1073** [comment]
Hi @garyzhalo, can you share some code that triggers this behavior?

**Comment by garyzhalo** [comment]
I was using fastai lib, which is keras-like lib for PyTorch. The function is 

> `fit()`

I assume behind the scene it uses tqdm and print out temporary results. Following is the screenshot for outputs when the page stoped responding.

<img width="531" alt="screen shot 2018-02-20 at 1 00 48 pm" src="https://user-images.githubusercontent.com/10591164/36443534-aba64f20-163e-11e8-9b07-4323010a53ca.png">

**Comment by blink1073** [comment]
Hi @garyzhalo, does the same code work when run in the classic notebook?

**Comment by garyzhalo** [comment]
@blink1073 Yes. If I launch classic notebook from jupyterlab, it will work.

**Comment by blink1073** [comment]
I haven't been able to get a `fastai` example to work on my machine due to the large number of dependencies.  I'm wondering if https://github.com/jupyterlab/jupyterlab/pull/3882 is what caused your issue.  Can you please verify whether your function works with version 0.31.6?  That change was released in 0.31.8.

**Comment by garyzhalo** [comment]
I've been testing this function using different versions. However, 0.31.5, 0.31.6, and 0.31.8 all have the same issue.
