### ISSUE TITLE
Cell copy/paste from Console to Notebook

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab#391]
This isn't something we can do quite yet, but that would be extremely cool down the road: being able to select _whole cells_ in the web console, including their outputs (as structured mime bundles) and pasting them wholesale into a notebook.

I often use a Qt Console via the `%qtconsole` magic as "scratch paper" next to a real notebook, and will now use the Lab Console for the same.  It would be awesome to be able to grab something that happens to work and that I want to keep from the "scratch paper" and put it back into the main document verbatim, without having to do any extra computation.

These are the kinds of things that start to become viable with this architecture... Fun :)

**Comment by fcollonval** [comment]
Closing as the boot did not.
