### ISSUE TITLE
readonly notebook file

### ISSUE THREAD

**Issue by clkao** [jupyterlab/jupyterlab#3915]
If the notebook file is readonly on the file system, we should have the readonly mode enabled when opening.

The File menu should also disable "Save Notebook" item to prevent 403 error.  Ditto for the save button on the toolbar.

somewhat related to #3251

**Comment by jasongrout** [comment]
Fixed in #5376.

**Comment by clkao** [comment]
This seems re-opened by https://github.com/jupyterlab/jupyterlab/pull/5475
