### ISSUE TITLE
Dragging/Arranging Windows

### ISSUE THREAD

**Issue by pgensler** [jupyterlab/jupyterlab#3918]
It might be worth noting to put a section in the docs around that you can drag and move the windows around to customize your session.

Going directly into the launcher at first made it feel like I was only able to view the current document, and not really escape it to see everything at once, and be able to arrange the windows. Maybe having the equivalent of OS X's/Window Gather Windows in the Menu's above as a master reset too?

**Comment by pgensler** [comment]
FYI, to enable multiple panes, you can go to View->Single Document Mode to turn on or off. Maybe adding this to the launcher could help?

**Comment by pgensler** [comment]
Yeah, except I think it would be nice to default the view when you open something from the launcher to not go into single document mode, as you normally want a text file with a console open to run commands on, similar to RStudio.

I understand the Launcher is not fully developed, but it seems like maybe not as integrated as it could be with other features? Maybe making the Launcher always dedicate to Single Document Mode, and then when you select something, going into multi-pane mode?

**Comment by pgensler** [comment]
I see the docs, now, sorry I should have been more clear. I knew the launcher was a feature of Jupyter Labs, but when I first started it, it seemed like it was a little harder to find than what I expected.

**Comment by saulshanabrook** [comment]
I am unsure what the next actionable steps are for this. Please comment if there are things that should be added to the docs or changed to make it more intuitive!

**Comment by saulshanabrook** [comment]
When I open a notebook from the launcher it doesn't seem to go into single document mode:

![](https://media.giphy.com/media/55iRX7aG4JPG8qZdMf/giphy.gif)]
