### ISSUE TITLE
Error executing Jupyter command 'lab': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by sanjivsoni17** [jupyterlab/jupyterlab#3921]
I have installed jupyter lab using `$pip install jupyterlab` command. After running `$jupyter lab` I am getting this error `Error executing Jupyter command 'lab': [Errno 2] No such file or directory`. 

It seems jupyterlab is installed but the path is not linked. Any pointers on what to do ?

`pip show jupyterlab`
Name: jupyterlab
Version: 0.31.8
Summary: The JupyterLab notebook server extension.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /Library/Python/2.7/site-packages
Requires: futures, notebook, jupyterlab-launcher, subprocess32, ipython-genutils

**Comment by blink1073** [comment]
Hi @sanjivsoni17, what does `which jupyter` show?  Also, does `jupyter-lab` work (with a hyphen).

**Comment by sanjivsoni17** [comment]
Hey @blink1073, thanks for responding. This is what the output of which is.

$which jupyter - /usr/local/bin/jupyter
$ jupyter-lab - zsh: command not found: jupyter-lab

**Comment by vidartf** [comment]
What does `which pip` show?

**Comment by sanjivsoni17** [comment]
`which pip` - /usr/local/bin/pip

**Comment by blink1073** [comment]
I'm not sure why it would install but not add the script.  Can you please try `pip uninstall -y jupyterlab && pip install jupyterlab`?

**Comment by sanjivsoni** [comment]
I could make to work in virtual env.

**Comment by HardoScherz** [comment]
Thank you @blink1073. On my Computer helped:
> sudo -H pip3 uninstall -y jupyterlab && sudo -H pip3 install jupyterlab

**Comment by garciparedes** [comment]
Hi! I'm getting the same error. I reinstalled `jupyterlab` of many ways and the problem continues. Can anybody help me? I think the problem is that `jupyterlab` isn't registering the `jupyter lab`command or something like that because when I perform `jupyter serverextension list` `jupyterlab`appears as enabled.

**Comment by zzploveyou** [comment]
`jupyter-lab` can work in my enviroment. But it failed to start when using supervisor.

Strange problem.

I soved it by using absolute exec path.
`/home/user/.local/bin/jupyter-lab`

**Comment by danbri** [comment]
FWIW I ran into this error after adding '--user' to address permissions problem installing globally. Running 

> ./.local/bin/jupyter-labhub

... seems to work

**Comment by andrejberg** [comment]
I had the problem after installation with pip. Solved it by adding 
`/home/username/.local/bin`
to PATH.

**Comment by otayeby** [comment]
> Thank you @blink1073. On my Computer helped:
> 
> > sudo -H pip3 uninstall -y jupyterlab && sudo -H pip3 install jupyterlab

Nice tip! It didn't work without the home (-H) flag, thanks!
Now I can see jupyter installed on Mac under `/usr/local/bin/`

**Comment by CreationTribe** [comment]
> I had the problem after installation with pip. Solved it by adding
> `/home/username/.local/bin`
> to PATH.

Perfect, thank you. That fixed mine as well.

**Comment by lydnguyen** [comment]
> I had the problem after installation with pip. Solved it by adding
> `/home/username/.local/bin`
> to PATH.

I opened the bash file by typing this line in terminal:
`gedit ~/.bashrc`
and added at the end of the file:
`PATH=$PATH:home/username/.local/bin`
This makes sure that the path is added permanently in the variable $PATH.
Afterward, I can just open Jupyterlab by command line:
`jupyter-lab`

**Comment by jasongrout** [comment]
Thanks everyone for sharing how you resolved this. Closing as answered.
