### ISSUE TITLE
Dark Theme Covers up Black Color Letters

### ISSUE THREAD

**Issue by shadowdmg** [jupyterlab/jupyterlab#3922]
If I switch to the dark theme then the letters in black color will not show up.  The dark fonts should be automatically switched to a lighter color?

**Comment by ian-r-rose** [comment]
Hi @shadowdmg, can you be specific about where there is black lettering? We intend to have it all switch to a light color, but we have likely missed a spot or two.

**Comment by shadowdmg** [comment]
I'm attaching the notebook file for reference.  Take a look at cell 12 in the light theme:

![image](https://user-images.githubusercontent.com/17693321/36519945-2357ad3e-1743-11e8-85d4-f8855a992de0.png)

Switched to the dark theme, note the dark fonts don't appear.  Hopefully that clears things up!

![image](https://user-images.githubusercontent.com/17693321/36519987-61bdeaca-1743-11e8-9b65-3a2c805ccffb.png)


[lesson1.ipynb.zip](https://github.com/jupyterlab/jupyterlab/files/1746605/lesson1.ipynb.zip)

**Comment by ian-r-rose** [comment]
Thanks @shadowdmg, this clarifies the problem. This problem is already being discussed in #3886 and #3855. Can we continue the discussion there?
