### ISSUE TITLE
 Kernel links problem

### ISSUE THREAD

**Issue by Jisung-Yoon** [jupyterlab/jupyterlab#3924]
I just install jupyter lab on my server.
There is kernel problem in jupyter lab.
I select the python3(python version 3.5) kernel, but jupyter lab links to another kernel (python version 2.7.10)

There is no problem on jupyter notebook, so there is no problem in notebook or ipython.

How can i fix this problem?

**Comment by ian-r-rose** [comment]
Hi @Jisung-Yoon, I can't reproduce this. Can you show a screenshot of the help menu with the problem? What does it show when you have no kernel active?

**Comment by Jisung-Yoon** [comment]
There are 3 kernels in my gitlab, and I want to use python3
![1](https://user-images.githubusercontent.com/35335944/36512623-933057bc-17ae-11e8-8173-47df11646636.PNG)

But, when I click python3 kernel, another interpreter which is python2 comes out.
![default](https://user-images.githubusercontent.com/35335944/36512630-98999998-17ae-11e8-98d9-acd0a6b07d6b.PNG)

Here is my jupyter's kernel list, and there is no problem when using only jupyter notebook
![3](https://user-images.githubusercontent.com/35335944/36512633-99acd700-17ae-11e8-9d04-eaa3e0fb95e5.PNG)

What should i do? 
Thank you

**Comment by Jisung-Yoon** [comment]
Problem solved!
Problem is jupyeter's kernel.json.
It is okay on the jupyter notebook, but there are some problems in jupyter lab.
I modified kernel.json, and it works well.
Thank you!

**Comment by jasongrout** [comment]
Would you mind posting the kernel.json that didn't work and the modified one that did? It's still a bit troubling if things worked in the classic notebook, but didn't in JupyterLab.

**Comment by Jisung-Yoon** [comment]
![default](https://user-images.githubusercontent.com/35335944/36575524-bab671b4-188e-11e8-87f2-846579a37d31.PNG)
It may be interpreter recognization problem
It is original kernel.json, and it works well on jupyter notebook, and modified version is 'usr/bin/python3
After modification, jupter lab works well. 
I do not know why it is works on notebook, but lab is not.

Thank you!

**Comment by ctivanovich** [comment]
I'm having this problem now, and can't pinpoint the cause. I run anaconda3 on Linux subsystem in windows, and I have only one kernel.json file in the anaconda jupyter library, which matches the one posted. I've checked for conflicting kernel files in the base distributions of py27 and py35, but these don't even have ipykernel or jupyter installed, so I have no idea. I also tried the rm nbsignatures.db idea, but that hasn't helped anything. The error still reads as "malformed database". Any suggestions? I can not use jupyter at this point at all, and I've also downgraded jupyter lab to the previous version to no avail. Some version info:
jupyter_client            5.2.3                    py36_0
jupyter_core              4.4.0                    py36_0
jupyterlab                0.34.3                   py36_0
jupyterlab_launcher 0.13.1                  py36_0
ipykernel                 4.9.0                    py36_0

**Comment by koenlek** [comment]
Same problem here, using jupyterlab 0.34.12 with python 3.5.2 on Ubuntu Xenial.

Jupyterlab 0.34 uses python3 to run jupyter lab, but now I cannot run python2 kernels anymore. Python2 kernels turn out to actually use python3 too. I found a workaround: patching kernel.json of the python2 kernel.

```
koenlek@wepods_dev:~/wepods_ws$ jupyter kernelspec list
Available kernels:
  python2    /usr/local/share/jupyter/kernels/python2
  python3    /usr/local/share/jupyter/kernels/python3
```

The contents of those specs:

`/usr/local/share/jupyter/kernels/python3/kernel.json`:
```
{
 "argv": [
  "python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
```

`/usr/local/share/jupyter/kernels/python2/kernel.json`:
```
{
 "display_name": "Python 2", 
 "language": "python", 
 "argv": [
  "python", 
  "-m", 
  "ipykernel_launcher", 
  "-f", 
  "{connection_file}"
 ]
}
```

Patched `/usr/local/share/jupyter/kernels/python2/kernel.json`:

```
{
 "display_name": "Python 2", 
 "language": "python", 
 "argv": [
  "python2", 
  "-m", 
  "ipykernel_launcher", 
  "-f", 
  "{connection_file}"
 ]
}
```
