### ISSUE TITLE
404 : Not Found You are requesting a page that does not exist!

### ISSUE THREAD

**Issue by ghost** [jupyterlab/jupyterlab#3926]
Please help.
![image](https://user-images.githubusercontent.com/24543786/36470673-4ac18d10-171e-11e8-99e1-3b8cf4bba8be.png)

**Comment by Coconuthack** [comment]
I had the same  issue on  a clean install, to solve it i checked the log file error response... and mine basically said to install ''nodejs", which i did on the base root environment through the anaconda navigator

**Comment by suherminovri** [comment]
I just installed nodejs and it's finally working. Thanks.
![image](https://user-images.githubusercontent.com/24543786/36471898-ae008440-1722-11e8-8d3c-f54848be60d9.png)

**Comment by gurpreetshanky** [comment]
@Coconuthack Thanks it worked.

**Comment by shubhangipatil12** [comment]
Please can you explain the node.js and log file in detail. I am new to this. Thank you @Coconuthack
