### ISSUE TITLE
File Load Error when opening xls

### ISSUE THREAD

**Issue by timhoffm** [jupyterlab/jupyterlab#3927]
The file browser highlights xls files with a special icon:
![grafik](https://user-images.githubusercontent.com/2836374/36475826-41fb094e-16fc-11e8-8467-e8623609205d.png)

I therefore assumed that I can at least view the contents of the file. However, when trying to open it, I receive:

![grafik](https://user-images.githubusercontent.com/2836374/36475775-1006d4ae-16fc-11e8-8bc8-68774bf0a1ea.png)

This is either a bug, or alternatively if JupiterLab cannot do anything with xls files, there should be a better error message along the lines of ".xls files cannot be opened in JupyterLab". "Bad format" suggests that the file is corrupted, which is not the case as far as I can tell.

**Comment by ian-r-rose** [comment]
Hi, @timhoffm, we currently don't have any viewers for Excel spreadsheets (though there has been some interest in creating one). You are right, I think we should not be showing a special icon for `.xls` files.

**Comment by timhoffm** [comment]
@ian-r-rose Thanks. I'd even be ok with the icon. More important is a reasonable message when trying to open the file.

**Comment by jasongrout** [comment]
This is a message from the notebook server, and comes from us by default requesting to open the file as a text file (because our default opener is the text editor). We request the file as a text file, and the notebook server complains that the file is not actually a text file.

Perhaps the error message should just say something like "Error opening the file. This file type may not be supported, or the file may be corrupt." Would that be sufficient? We do want to handle the case of, for example, a corrupt text file.

**Comment by timhoffm** [comment]
I'd like to have an even clearer error message. "This file type may not be supported, or the file may be corrupt."  leaves me wondering if my file is broken or if JupiterLab cannot handle it.

Probably the simplest way would be to have a blacklist of file extensions, that we are not trying to open as text. Instead display a message "JupiterLab does not support viewing [type] files." Formats that I've encountered include MS Office formats, .gz, .hdf5.

If you want to be a little less restrictive, you could still request all files as text. If the server responds with  "Invalid response: 400 bad format" and the extension is on the blacklist. Display the above message. This would allow users to name their text files test.xls. But I don't know if that's worth the extra effort.

**Comment by jasongrout** [comment]
Since opening a binary file is way more common than opening a corrupt text file, maybe the error should just be "JupyterLab did not recognize this file type." If someone complains that JLab is saying that about a text file, we can investigate a corrupted text file.

**Comment by jasongrout** [comment]
Or perhaps if we have an explicit registered filetype in jlab for that file, we can confidently say the file is corrupted. However, if we are using the *default* file viewer, we say "did not recognize this file type."
