### ISSUE TITLE
Idea: Theme editor

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#3928]
Given the number of issues with theming, and the wish of many users to fully customize their look and feel, it would make sense to make it easier to make theme extensions. The most streamlined way to do this would be to make a "Theme editor" directly in lab. The design would of course be left to whoever implements this, but here are some aspects that I imagine:

- The editor would be a lab-extension, so that the theme can be edited directly from jupyterlab.
- Installed themes are read-only, but can be used as a basis for editing your own.
- Maybe use existing settings UI as a base for editing the theme?
- Edited theme is kept in-memory, but with an option to save it out as an extension.

If anyone wants to take this on, it would probably be best to create it as a third-party extension, which could then be considered for inclusion in the core later on.

**Comment by vidartf** [comment]
> it would probably be best to create it as a third-party extension

That being said, there might be a need for a feature in the core for "hot-loading" a theme? I'm not familiar enough with the underpinnings of the theme system.

**Comment by zkghost** [comment]
What is the current method for developing your own theme? I've spent an hour without luck trying to manually add folders in different spots and failing to run the `jlpm run create:theme` command.

**Comment by jasongrout** [comment]
@zkghost - I would copy a current theme (like https://github.com/jupyterlab/jupyterlab/tree/master/packages/theme-light-extension) to a directory, then modify it to suit your needs. The current themes should be essentially self-contained, and would be good starting points for other themes.

**Comment by jtpio** [comment]
Closing as this has now been implemented in https://github.com/jupyterlab-contrib/jupyterlab-theme-editor.

There is also a blog post about the extension: https://blog.jupyter.org/a-theme-editor-for-jupyterlab-8f08ab62894d

Thanks @HaudinFlorence for working on this!
