### ISSUE TITLE
Changelog / release notes?

### ISSUE THREAD

**Issue by aldanor** [jupyterlab/jupyterlab#3930]
This is a minor thing really, but would it make sense to maintain a sort of a `CHANGELOG.md` somewhere? I was very surprised to find none in a project as a big as this. Especially now that the project entered the 'beta' stage.

The only way to track changes, unless I'm missing something, is to manually scan through 2004 git tags in GH's 'Releases', which is next to impossible.

Thanks!

**Comment by blink1073** [comment]
This is a great idea, we should be able to auto-create this from the existing release notes, and I agree we should switch to a `CHANGELOG.md`.
