### ISSUE TITLE
Improve readability of highlighted matching brackets

### ISSUE THREAD

**Issue by dlukes** [jupyterlab/jupyterlab#3932]
Since CodeMirror 5.32, the readability of highlighted matching brackets has been improved thanks to a switch to a darker shade of green (see [this issue](https://github.com/codemirror/CodeMirror/issues/5063) and [this commit](https://github.com/codemirror/CodeMirror/commit/f02225b9ca000ddb098053b21acf3165d1e34beb)). Would it be possible to switch the codemirror package to a newer version of this dependency?

https://github.com/jupyterlab/jupyterlab/blob/2e613b5ca067c6353a4917fc25cb1112195ce1cd/packages/codemirror/package.json#L41

In my experience teaching with Jupyter Notebooks (which use the same default CodeMirror theme), the original shade of green is all but invisible on a projector :)

**Comment by ian-r-rose** [comment]
Thanks for the feedback, @dlukes. Fixing this would be another side effect of #3905.

**Comment by dlukes** [comment]
Oh, perfect! Sorry for only searching issues for "codemirror" and not pull requests, I wouldn't have opened this had I found out about #3905 :)

**Comment by saulshanabrook** [comment]
Closing this since #3905 has been merged. Feel free to comment if this is still an issue.
