### ISSUE TITLE
environment not correct

### ISSUE THREAD

**Issue by noklam** [jupyterlab/jupyterlab#3933]
I start my jupyter lab in custom envrionment but seems jupyter lab is reading library from my root environment.

I further confirm it by doing "source activate root" and install the library that it I am warned, and the error go away.

**Comment by saulshanabrook** [comment]
Hm, do you mean with virtual environments? Does jupyterlab start up, but just using the wrong path?

**Comment by saulshanabrook** [comment]
Please comment with more info and we can reopen this
