### ISSUE TITLE
Images don't show up in lab

### ISSUE THREAD

**Issue by thwee-alchemist** [jupyterlab/jupyterlab#3935]
I saved some images in jupyter notebook, and they are displayed correctly. Does Jupyter Lab allow for image attachments?

**Comment by ian-r-rose** [comment]
Hi @thwee-alchemist, how have they been saved? Are they plots the result of some computation, embedded images in markdown documents, or something else?

**Comment by thwee-alchemist** [comment]
They were saved as an attachment.

**Comment by thwee-alchemist** [comment]
Simply linking to uploaded images works, but the "insert image" option
disappeared, and images saved using this option aren't displayed.

**Comment by jasongrout** [comment]
Ah, then let's move the conversation to the existing issue for this: https://github.com/jupyterlab/jupyterlab/issues/1398

Indeed, that hasn't been implemented yet.
