### ISSUE TITLE
Markdown Preview: Weird URLs

### ISSUE THREAD

**Issue by ax3l** [jupyterlab/jupyterlab#3937]
When I am using urls with `()` in them, such as some weird but valid DOIs, the Markdown link preview breaks.

### Example DOI
```
DOI:10.1016/S0010-4655(00)00228-9
```

### Example URI
```
https://dx.doi.org/10.1016/S0010-4655(00)00228-9
```

### Markdown
```
[*Esirkepov*](https://dx.doi.org/10.1016/S0010-4655(00)00228-9)
```

### GitHub Preview

[Esirkepov](https://dx.doi.org/10.1016/S0010-4655(00)00228-9)

### Jupyter Lab 0.31.8

![markdown_doi](https://user-images.githubusercontent.com/1353258/36489232-cce92fb2-1725-11e8-80b5-1e0ae6aff1ed.png)

**Comment by saulshanabrook** [comment]
I notice this happens in Jupyter Notebook as well.

**Comment by jasongrout** [comment]
As a workaround, you can use `%28` for `(` and `%29` for `)`.

**Comment by jasongrout** [comment]
See also https://meta.stackexchange.com/questions/13501/links-to-urls-containing-parentheses for some alternative ways of using parens in markdown links.

**Comment by jasongrout** [comment]
See also https://github.com/markedjs/marked/issues/690, the relevant issue in the markdown renderer we are using.

**Comment by ax3l** [comment]
Thanks for the cross link. It's indeed funny it's allowed in DOI in the first place in even more funny that Markdown CommonMark allows *balanced* brackets in the URI as well. Anyway, upstream issue so I will close it here :)
