### ISSUE TITLE
Machine learning workflow feedback

### ISSUE THREAD

**Issue by jhartford** [jupyterlab/jupyterlab#3943]
I've been using jupyterlab for a week since seeing @fperez's talk at UBC. At @jzf2101 's suggestion, I thought I'd share some feedback so far. Context: I work on designing new deep learning architectures so primarily work with tensorflow + pytorch + numpy and a little pandas for loading test data... 
 
My old workflow was: 
- jupyter notebook via ssh to my desktop (with a GPU) for small tests / interactive debugging of tensor multiplication / visualization of results / etc...
 - visual studio code on my laptop for actual coding + vim via ssh on my desktop if I needed to modify any of my scripts remotely (occasionally I'd mount my desktop and use VSCode for that too, but I often found it easier to just use vim).

Jupyter lab gets 90% of the way to replacing the VSCode + vim part of that equation and letting me just work on my remote machine. I really like the new layout, updated notebooks, integrated terminal, and the text editor replaces vim for me. 

The only thing I'm still missing is python integration into the text editor: the reason I use VSCode over vim is I like the python code completion / function definition / etc... it's also part of the reason that I like experimenting in notebooks. So if you guys figured out python integration into the editor, I'd probably switch my entire workflow to jupyter lab.... Overall though - it's really nice.

Finally, one little usability bug - I find it really tricky to drag a window to attach to a new tab. It always wants to snap to split screen rather than join one of the tabs. I'm probably just doing something wrong though?

**Comment by jasongrout** [comment]
> I find it really tricky to drag a window to attach to a new tab. It always wants to snap to split screen rather than join one of the tabs. I'm probably just doing something wrong though?

Just a guess at a helpful hint: drag a tab to the *center* of a panel to add the tab to the panel.

We're exploring some other UI actions because we know this is confusing, but it is also very natural and quick once you get used to it.

**Comment by jhartford** [comment]
> Just a guess at a helpful hint: drag a tab to the center of a panel to add the tab to the panel.

That was it - thanks! You're right - it's natural once you figure it out.

**Comment by fperez** [comment]
On Wed, Feb 21, 2018 at 10:17 AM, Jason Hartford <notifications@github.com>
wrote:

> I've been using jupyterlab for a week since seeing @fperez
> <https://github.com/fperez>'s talk at UBC. At @jzf2101
> <https://github.com/jzf2101> 's suggestion, I thought I'd share some
> feedback so far. Context: I work on designing new deep learning
> architectures so primarily work with tensorflow + pytorch + numpy and a
> little pandas for loading test data...
>
Glad to see the talk helped bring new users on board!


> My old workflow was:
>
>    - jupyter notebook via ssh to my desktop (with a GPU) for small tests
>    / interactive debugging of tensor multiplication / visualization of results
>    / etc...
>    - visual studio code on my laptop for actual coding + vim via ssh on
>    my desktop if I needed to modify any of my scripts remotely (occasionally
>    I'd mount my desktop and use VSCode for that too, but I often found it
>    easier to just use vim).
>
> Jupyter lab gets 90% of the way to replacing the VSCode + vim part of that
> equation and letting me just work on my remote machine. I really like the
> new layout, updated notebooks, integrated terminal, and the text editor
> replaces vim for me.
>
> The only thing I'm still missing is python integration into the text
> editor: the reason I use VSCode over vim is I like the python code
> completion / function definition / etc... it's also part of the reason that
> I like experimenting in notebooks. So if you guys figured out python
> integration into the editor, I'd probably switch my entire workflow to
> jupyter lab.... Overall though - it's really nice.
>

Note that there's been discussions about integrating Monaco (the VSCode
editor component): https://github.com/jupyterlab/jupyterlab/issues/135

I'm not up to speed on the state of that, but I see issues like this one (
https://github.com/jupyterlab/jupyterlab/issues/2014) that refer to
successful use of it... Perhaps others can comment on more recent news on
that front, since my info is a bit out of date?

Cheers,

f

**Comment by jhartford** [comment]
Awesome - thanks! I'll look into that.
