### ISSUE TITLE
Unsaved changes indicator inconsistent

### ISSUE THREAD

**Issue by knightman** [jupyterlab/jupyterlab#3946]
The dot indicator on the open file tab shows inconsistent behavior. The dot remains after file has been saved. Happens infrequently. Version 0.31.8
![capture1](https://user-images.githubusercontent.com/7648214/36503637-6a138552-1713-11e8-94aa-c2db6b3119f2.PNG)

**Comment by saulshanabrook** [comment]
Is it possible to describe how to reproduce this bug? Any sense of when this comes up?
