### ISSUE TITLE
Tab completion for greek characters not working...

### ISSUE THREAD

**Issue by gajomi** [jupyterlab/jupyterlab#3947]
I have seen that there are a bunch of open tab completion issues, but couldn't quite tell if this was superceded by any one of them, so I am making a new issue.

In the jupyter console or the jupyter notebook I can get greek characters by pressing tab at the end of their latex equivalent. E.g.:
```
In [1]: \lambda [TAB]
```
yields
```
In [1]: λ
```
This behavior doesn't seem to work yet in any flavor of jupyter notebook tabs on my freshly installed jupyter instance, Chrome as the browser.

```
$ jupyter lab -V
0.31.8
```

**Comment by ian-r-rose** [comment]
Hi @gajomi, are you by any chance using Julia? If so, this was fixed in #3705 .

**Comment by gajomi** [comment]
Yeah, this was Julia. I just confirmed that the Python kernels worked as expected, so probably can close if it makes sense.

**Comment by ian-r-rose** [comment]
Sounds good. The fix will be available in the next release.
