### ISSUE TITLE
Subtle behavior difference between vanilla notebook and lab notebook tab tooltips

### ISSUE THREAD

**Issue by hexatheon** [jupyterlab/jupyterlab#3954]
I run the following code: (requiring pytorch)

```
from torchvision import models
m = models.vgg11(pretrained=False)
m.features.
 ```
and try to use tab tooltip for potential parameters that start with _ (Basically hidden params)
using these exact incremental steps

//Action sequence 1:
m.features.
(tab)
// regular params that do not start with _ are displayed. Correct.
// now directly add the underscore _ 
m.features._
(tab)
// Here among the tooltips there are no hidden params. This diverges from vanilla notebook.

//Action sequence 2:
m.features._
(tab)
// In this case all the hidden params are shown, though there is a strange double-shadowing font effect beneath the displayed params.

**Comment by saulshanabrook** [comment]
Thanks for this feedback. If you open to the most recent version of Jupyterlab doe the issue persist? Completing `_` properties works for me locally.

**Comment by hexatheon** [comment]
It is resolved in the new version.
