### ISSUE TITLE
Installation error for JuypterLab in conda

### ISSUE THREAD

**Issue by fretchen** [jupyterlab/jupyterlab#3955]
To test juypterlab on MacOS 10.13 I created a new environment

`conda create -n JLenv python=3.6`

Afterwards I ran within the environment 

`conda install -c conda-forge jupyterlab`

This fails with the following error:

> LinkError: Link error: Error: post-link failed for: conda-forge::jupyterlab-0.31.8-py36_1

**Comment by blink1073** [comment]
Hi @fretchen, are you not able to run `jupyter lab` (i.e. did it truly fail to install)?

**Comment by jasongrout** [comment]
Also, what version of conda do you have? `conda --version`

Some packages on conda-forge these days require conda version 3 or greater to work correctly.

**Comment by rsb00** [comment]
I had the same exact issue trying to install JuypterLab via conda-forge yesterday. I have conda version 4.2.12. The install (truly) failed both in an existing and a new environment. I was able to install JupyterLab using pip.

**Comment by rsb00** [comment]
Just to add to my prior comment, updating conda (`conda update conda`) appears to resolve the issue. I am now on conda version 4.3.30.

**Comment by fretchen** [comment]
The update to the newest version of conda also fixed the issue for me.

**Comment by mondfuchs** [comment]
I get the same error, I have conda version 4.3.34 and also tried to downgrade to 4.3.30.. but nope, still not working
