### ISSUE TITLE
Error not being displayed correctly on opening a notebook

### ISSUE THREAD

**Issue by AbdealiLoKo** [jupyterlab/jupyterlab#3956]
I have the same issue as https://github.com/ipython/ipython/issues/9003

But in Jupyterlab the error does not seem to be popping up. I can see a 500 error in the JavaScript Console but when i click on create notebook it shows nothing and is completely unresponsive.

In Notebook it looks like it showed that an error was occuring in a dialog box.

**Comment by saulshanabrook** [comment]
So we should make sure that if the server returns a 500 when opening a file that we display this in a popup.

**Comment by JasonWeill** [comment]
Other server errors now appear in popups. Jupyter Server has been updated to version 2 since this issue was opened. Closing this issue.

If you continue to see unexpected behavior, please reopen this issue or open another one. Thanks!
