### ISSUE TITLE
jupyter notebook <filename.ipynb> starts jupyter lab, want classic notebook instead

### ISSUE THREAD

**Issue by ischurov** [jupyterlab/jupyterlab#3966]
Is it possible to restore the default behaviour of `jupyter notebook <filename.ipynb>` command, i.e. starting classic jupyter notebook, not jupyter lab?

**Comment by blink1073** [comment]
Hi @ischurov, does running just `jupyter notebook` also run the classic notebook on your machine?

**Comment by ian-r-rose** [comment]
I can reproduce this: running `jupyter notebook <filename>` launches it in lab, using the tree handler, while `jupyter notebook` launches the classic notebook, as expected.

**Comment by blink1073** [comment]
Ah, I see what is the problem: we need to make sure it is an instance of `LabApp` [here](https://github.com/jupyterlab/jupyterlab/blob/466969c3114e5a89ab15796ed3582a9a6b70e4b4/jupyterlab/extension.py#L90).

**Comment by prateeks92** [comment]
i am taking this up for HackIllinois

**Comment by ischurov** [comment]
@blink1073 `jupyter notebook` launches classic tree view, `jupyter notebook <filename>` launches notebook in a tab of Lab.

**Comment by blink1073** [comment]
Fixed by #4111, released as `0.31.11`.
