### ISSUE TITLE
bash: __git_ps1: command not found

### ISSUE THREAD

**Issue by GClunies** [jupyterlab/jupyterlab#3967]
When running terminal in jupyterlab I get the Git prompt:

`bash: __git_ps1: command not found`

![git_ps1_error](https://user-images.githubusercontent.com/28986302/36565153-794efd82-17d4-11e8-9b06-59d6afe18085.png)

I am able to use git functionality in the jupyterlab terminal, as `git status` does work, but I don't see any branch information when used in jupyterlab

My .bash_profile is below. Full disclosure, most of the settings in my .bash_profile were from directions in a Udacity course I have taken. I suspect there is something wrong in this file, but honestly I have no idea. 

```
# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH

# added by Anaconda3 5.0.1 installer
export PATH="/Users/GregoryClunies/anaconda3/bin:$PATH"

# Enable tab completion
source ~/.udacity-terminal-config/git-completion.bash

# Change command prompt
source ~/.udacity-terminal-config/git-prompt.sh

# colors!
red="\[\033[38;5;203m\]"
green="\[\033[38;05;38m\]"
blue="\[\033[0;34m\]"
reset="\[\033[0m\]"

export GIT_PS1_SHOWDIRTYSTATE=1

# '\u' adds the name of the current user to the prompt
# '\$(__git_ps1)' adds git-related stuff
# '\W' adds the name of the current directory
## export PS1='[\u@mbp \w$(__git_ps1)]\$ '
export PS1="$red\u$green\$(__git_ps1)$blue \W
$ $reset"
```

**Comment by blink1073** [comment]
Hi @GClunies, can you verify in the terminal in JupyterLab that `~/.udacity-terminal-config/git-completion.bash` exists?

**Comment by GClunies** [comment]
Hi @blink1073, thanks for the quick response. After running in the JupyterLab terminal, it appears to exist.

```
bash: __git_ps1: command not found
GregoryClunies ~
$ if [ -f ~/.udacity-terminal-config/git-completion.bash ]
> then
>     echo file exists
> else
>     echo file does not exist
> fi
file exists
```

**Comment by vidartf** [comment]
Is this the same as #3094 ?

**Comment by willylee** [comment]
I'm fairly certain #3094 would fix it. One could test this with

`source ~/.udacity-terminal-config/git-prompt.sh`

If it starts working after doing this, then using an interactive shell should do that for you "automatically"

**Comment by GClunies** [comment]
@willylee and @vidartf, #3094 fixed it. Did not have a .bashrc file so interactive shell would not find 

`source ~/.udacity-terminal-config/git-prompt.sh`

Thanks to all for the help!
