### ISSUE TITLE
Console Section using with vim

### ISSUE THREAD

**Issue by Davidnet** [jupyterlab/jupyterlab#3973]
Hi just a quick overview, whenever I initialize a console pane on jupyterlab  and try to use vim I am encountering the following error: 

![image](https://user-images.githubusercontent.com/3343006/36576099-63c71fd8-1803-11e8-9a86-2bb9e3b811c1.png)
Kernel logs include:
```
[I 18:57:57.331 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
```
The current output:
`
]50;CursorShape=0;BlinkingCursorEnabled=0]]50;CursorShape=1;BlinkingCursorEnabled=0]

Is there any guidelines to contribute to issues?

**Comment by ian-r-rose** [comment]
Hi @Davidnet, can you describe further the issue you are seeing, and how to reproduce it? I can open files using `vim` in the terminal without issue.

**Comment by Davidnet** [comment]
I stand corrected, I'm using nvim 0.2.2 with omnicompletions. The error seems to be triggered with omnicompletions either from Vim or NVim. Seems also to be something with the javascript connecting to the terminal.

Jupyterlab 4.4.0

**Comment by Davidnet** [comment]
Any logs or config files that I could share ?

**Comment by jasongrout** [comment]
What is `jupyter lab --version` give?

**Comment by Davidnet** [comment]
```
0.31.8
```

**Comment by jasongrout** [comment]
Does it work in the classic notebook? My hunch is that it may be a problem
with the terminal is library we are using?

**Comment by saulshanabrook** [comment]
If you would like this reopened, please comment to help us reproduce it and see if it differs from notebook behavior.
