### ISSUE TITLE
Always got wrong timestamp when I saved file

### ISSUE THREAD

**Issue by OnlyBelter** [jupyterlab/jupyterlab#3976]
I am using JupyterLab, and every time when I saved my `.ipynb` file, I always got a timestamp that was 13 minutes ago. If I missed something???

**Comment by blink1073** [comment]
Hi @OnlyBelter, does the same happen when running `jupyter notebook`?

**Comment by OnlyBelter** [comment]
Same problem,

![fiwq2fgvv7iu sx 0x 0qu6](https://user-images.githubusercontent.com/16537617/37889118-7a8dd0be-30fd-11e8-994d-31f112e7d9de.png)

**Comment by saulshanabrook** [comment]
Please comment if you have a way to replicate this behavior
