### ISSUE TITLE
Tab-completion Labels Instance Object as Module

### ISSUE THREAD

**Issue by navneethc** [jupyterlab/jupyterlab#3977]
**OS**: Windows 10 64-bit
**Python**: 3.6.4
**IPython/Jupyter versions:**
```
ipykernel                 4.8.0                    py36_0
ipython                   6.2.1            py36h9cf0123_1
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.1.1                    py36_0
jedi                      0.11.1                   py36_0
jupyter                   1.0.0            py36h422fd7e_2
jupyter_client            5.2.2                    py36_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.4.0            py36h56e9d50_0
jupyterlab                0.31.8                   py36_0

```

`page_data` is an instance of `defaultdict` (from `collections`), however the pop-up shows otherwise. Am I missing something here? Do let me know if you require any other information.

![image](https://user-images.githubusercontent.com/4192839/36590946-55c7ae26-18b6-11e8-869e-c3e48f5a0c14.png)

![image](https://user-images.githubusercontent.com/4192839/36591266-7956e950-18b7-11e8-9c42-75b535bb5b20.png)

**[Update] Another example:**

Function is shown as a class.

![image](https://user-images.githubusercontent.com/4192839/36592321-3a01b358-18bb-11e8-9d49-13281a3d9fc9.png)

**Comment by ian-r-rose** [comment]
Hi @navneethc, the logic for the Python type annotations is in [IPython](https://github.com/ipython/ipython). Would you mind opening this issue there?

**Comment by navneethc** [comment]
Done. Should I close this issue?
