### ISSUE TITLE
VS Code - Debugger for Chrome instructions 

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#3979]
I was able to get the [VS Code Chrome debugger](https://github.com/Microsoft/vscode-chrome-debug) working for developing JupyterLab. Now I can set a breakpoint in VS Code, start jupyterlab in a chrome browser, and be able to debug on that breakpoint staying in VS Code:

<img width="2139" alt="screen shot 2018-02-23 at 10 04 42 am" src="https://user-images.githubusercontent.com/1186124/36600855-70027c92-1881-11e8-883f-bfef78eab6bb.png">

However, I had to modify the `./vscode/launch.json` script to override the source map paths, so that it could match the filesystem to the source maps:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8888/",
            "webRoot": "${workspaceFolder}",
            "sourceMapPathOverrides": {
                "webpack:///../../../../*": "${webRoot}/packages/*"
            }
        }
    ]
}
```

I wanted to document this here in case anyone else wants to use this setup.

**Comment by saulshanabrook** [comment]
If this should live in the documentation, `CONTRIBUTING.md` or if I should check in the `./vscode/launch.json` file, let me know.

**Comment by dhirschfeld** [comment]
Thanks - this is very useful! I'm just getting started with TypeScript and for me, it's not the language which is difficult to adjust to, it's more the different tooling which I don't know how to configure/use properly (yet!) :/

**Comment by lstillwe** [comment]
This is great! I am new to TypeScript and Jupyterlab extensions too. Does jupyter lab --watch need to be run in a terminal before Launching chrome against localhost?
Thanks!
