### ISSUE TITLE
Tried to open a Jupyter Notebook but it shows an error.

### ISSUE THREAD

**Issue by wvict** [jupyterlab/jupyterlab#3984]
I installed Jupyter Notebook via Anaconda. When I tried to open one notebook, this is what shows up:

(base) C:\Users\wvict\Documents\Data Analisys>jupyter notebook ipython_notebook_tutorial.ipynb
[I 17:54:51.032 NotebookApp] The port 8888 is already in use, trying another port.
[I 17:54:51.032 NotebookApp] The port 8889 is already in use, trying another port.
[I 17:54:52.141 NotebookApp] JupyterLab beta preview extension loaded from C:\Users\wvict\Anaconda3\lib\site-packages\jupyterlab
[I 17:54:52.157 NotebookApp] JupyterLab application directory is C:\Users\wvict\Anaconda3\share\jupyter\lab
[W 17:54:52.282 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "C:\Users\wvict\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 321, in __init__
        self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
      File "C:\Users\wvict\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1165, in _run
        proc = Process(cmd, **kwargs)
      File "C:\Users\wvict\Anaconda3\lib\site-packages\jupyterlab\process.py", line 73, in __init__
        self.proc = self._create_process(cwd=cwd, env=env)
      File "C:\Users\wvict\Anaconda3\lib\site-packages\jupyterlab\process.py", line 131, in _create_process
        cmd[0] = which(cmd[0], kwargs.get('env'))
      File "C:\Users\wvict\Anaconda3\lib\site-packages\jupyterlab\jlpmapp.py", line 59, in which
        raise ValueError(msg)
    ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\wvict\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1454, in init_server_extensions
        func(self)
      File "C:\Users\wvict\Anaconda3\lib\site-packages\jupyterlab\extension.py", line 111, in load_jupyter_server_extension
        info = get_app_info(app_dir)
      File "C:\Users\wvict\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 244, in get_app_info
        handler = _AppHandler(app_dir, logger)
      File "C:\Users\wvict\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 324, in __init__
        raise ValueError(msg)
    ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

[I 17:54:53.235 NotebookApp] Serving notebooks from local directory: C:\Users\wvict\Documents\Data Analisys
[I 17:54:53.235 NotebookApp] 0 active kernels
[I 17:54:53.235 NotebookApp] The Jupyter Notebook is running at:
[I 17:54:53.251 NotebookApp] http://localhost:8890/?token=80cb4642d672b65536e5789fc58d6d898c55e54ce17bfe5c
[I 17:54:53.251 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:54:53.282 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8890/?token=80cb4642d672b65536e5789fc58d6d898c55e54ce17bfe5c

It goes to the web browser but it doesn't load anything. Do you guys know what's going on? Thank you in advance.

**Comment by ian-r-rose** [comment]
Hi @Wvictor07, what version of JupyterLab are you running. There was a similar bug to what you are describing, but it should have been patched.

**Comment by Wvictor07** [comment]
Hey @ian-r-rose , thanks for the quick reply. Acording to the Anaconda Navigator, the version of the Jupyter Notebook I have installed is 5.4.0.

**Comment by ian-r-rose** [comment]
What about JupyterLab? You can check this by running `jupyter lab --version`

**Comment by Wvictor07** [comment]
It is the version 0.31.4.

**Comment by ian-r-rose** [comment]
I think upgrading to the current version (0.31.8) should fix the problem.

**Comment by Wvictor07** [comment]
All right. How can I update to the latest version? It can be done in the command prompt?

**Comment by sccolbert** [comment]
`conda update jupyterlab`

**Comment by ian-r-rose** [comment]
`conda upgrade -c conda-forge jupyterlab` should work.

**Comment by ian-r-rose** [comment]
@Wvictor07 Did you get this fixed?

**Comment by Wvictor07** [comment]
@ian-r-rose  I managed to open one file ipynb in the command prompt and this is what happens:

[I 21:47:17.606 NotebookApp] Serving notebooks from local directory: C:\Users\wvict\Documents\Data Analisys
[I 21:47:17.608 NotebookApp] 0 active kernels
[I 21:47:17.610 NotebookApp] The Jupyter Notebook is running at:
[I 21:47:17.612 NotebookApp] http://localhost:8888/?token=f34bdea9bc4191a629305c7721fc9be93c812de46cc1e6d1
[I 21:47:17.613 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:47:17.626 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=f34bdea9bc4191a629305c7721fc9be93c812de46cc1e6d1
[I 21:47:21.321 NotebookApp] Accepting one-time-token-authenticated connection from ::1

The browser shows the local host (8888) and the URL(localhost:8888/notebooks/ipython_notebook_tutorial.ipynb?token=5742d55603d9b9f45bebc3ca551cf9c2b972ba86dd94ddd1) but it doesn't load at all. It's like this for 10 minutes or more. Do you know what it could be?

**Comment by ian-r-rose** [comment]
What happens when you launch `jupyter lab` from the command line?

**Comment by Wvictor07** [comment]
C:\Users\wvict>jupyter lab
[W 22:06:35.905 LabApp] JupyterLab server extension not enabled, manually loading...
[I 22:06:36.273 LabApp] JupyterLab beta preview extension loaded from C:\Users\wvict\Anaconda3\lib\site-packages\jupyterlab
[I 22:06:36.289 LabApp] JupyterLab application directory is C:\Users\wvict\Anaconda3\share\jupyter\lab
[I 22:06:37.251 LabApp] Serving notebooks from local directory: C:\Users\wvict
[I 22:06:37.276 LabApp] 0 active kernels
[I 22:06:37.277 LabApp] The Jupyter Notebook is running at:
[I 22:06:37.277 LabApp] http://localhost:8888/?token=cdca99284b64f0de8007aa988adb3c5b1f1fdfd46ee53881
[I 22:06:37.278 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:06:37.294 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=cdca99284b64f0de8007aa988adb3c5b1f1fdfd46ee53881

Nothing happens. The browser doesn't pop up or anything.

**Comment by ian-r-rose** [comment]
That's odd. Does it work when you open a browser and navigate to `http://localhost:8888/lab`?

**Comment by Wvictor07** [comment]
@ian-r-rose No. Nothing. That's pretty weird - I couldn't find not a single one situation that hardely resemble what's happening.

**Comment by Wvictor07** [comment]
And sometimes it opens the browser, others it doesn't. But it never loaded the Jupyter Notebook app.

**Comment by wvict** [comment]
Hey everyone. Today when I tried to launch a jupyter notebook via command prompt it opened a server and it's now working fine. Guess it was becouse I updated jupyter labs to the latest version. Thank you for the answers.

**Comment by wvict** [comment]
@ian-r-rose Thank you again for the help.

**Comment by ian-r-rose** [comment]
Glad you got it working. Closing as fixed.

**Comment by BrahmaniBharatam** [comment]
I get this update even after i install the lastest Jy Notebook . 

[I 00:52:06.164 NotebookApp] The port 8888 is already in use, trying another port.
[I 00:52:06.165 NotebookApp] The port 8889 is already in use, trying another port.
[I 00:52:06.165 NotebookApp] The port 8890 is already in use, trying another port.
[I 00:52:06.165 NotebookApp] The port 8891 is already in use, trying another port.
[I 00:52:06.167 NotebookApp] The port 8892 is already in use, trying another port.
[I 00:52:06.266 NotebookApp] JupyterLab beta preview extension loaded from C:\Users\brahm\Anaconda3\lib\site-packages\jupyterlab
[I 00:52:06.266 NotebookApp] JupyterLab application directory is C:\Users\brahm\Anaconda3\share\jupyter\lab
[W 00:52:06.291 NotebookApp] Error loading server extension jupyterlab
Traceback (most recent call last):
File "C:\Users\brahm\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 321, in __init__
self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
File "C:\Users\brahm\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1165, in _run
proc = Process(cmd, **kwargs)
File "C:\Users\brahm\Anaconda3\lib\site-packages\jupyterlab\process.py", line 73, in __init__
self.proc = self._create_process(cwd=cwd, env=env)
File "C:\Users\brahm\Anaconda3\lib\site-packages\jupyterlab\process.py", line 131, in _create_process
cmd[0] = which(cmd[0], kwargs.get('env'))
File "C:\Users\brahm\Anaconda3\lib\site-packages\jupyterlab\jlpmapp.py", line 59, in which
raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\brahm\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1549, in init_server_extensions
func(self)
File "C:\Users\brahm\Anaconda3\lib\site-packages\jupyterlab\extension.py", line 111, in load_jupyter_server_extension
info = get_app_info(app_dir)
File "C:\Users\brahm\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 244, in get_app_info
handler = _AppHandler(app_dir, logger)
File "C:\Users\brahm\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 324, in __init__
raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
[I 00:52:06.296 NotebookApp] Serving notebooks from local directory: C:\Users\brahm
[I 00:52:06.296 NotebookApp] The Jupyter Notebook is running at:
[I 00:52:06.296 NotebookApp] http://localhost:8951/?token=4481aa072957144452f7afeb9cb3b3bec4b8388e96606497
[I 00:52:06.296 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:52:06.309 NotebookApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8951/?token=4481aa072957144452f7afeb9cb3b3bec4b8388e96606497
[I 00:52:07.083 NotebookApp] Accepting one-time-token-authenticated connection from ::1


Also, basic Pandas and numpy imports take forever. 

Any leads ? What am I missing? Help Please

**Comment by moazmagdy** [comment]
I've encountered the same issue when I updated to Jupyter 5.7.6.

The issue disappeared when I installed earlier version (5.7.4)

**Comment by nick-brady** [comment]
I encountered this issue when I installed _only_ node onto my ubuntu image. I also had to install npm, which was pretty clear when I looked at the stack trace.

i.e.

`sudo apt install nodejs npm`

**Comment by jasongrout** [comment]
Thanks for posting about that. Usually node comes with npm, but perhaps not on ubuntu.
