### ISSUE TITLE
Terminal scrollback increase?

### ISSUE THREAD

**Issue by bubthegreat** [jupyterlab/jupyterlab#3985]
Using jupyterlab as a development environment for log analysis scripting, I'm running into an issue with the terminal where it doesn't have a settings tab, so I'd have to manually go into the code (if possible) and change it there.

**Comment by saulshanabrook** [comment]
So this could be added to the terminal widget options: https://github.com/jupyterlab/jupyterlab/blob/master/packages/terminal/src/widget.ts and used to set the xterm option.

And either add a command to change the scrollback size or [create settings](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#extension-settings) for the terminal extension and use those

**Comment by jasongrout** [comment]
+1 to settings, -1 to a command. This is something I imagine people will set once, rather than keep changing.

**Comment by DevOpsChris** [comment]
I'll take a stab at this for SciPy2018 Sprint.
