### ISSUE TITLE
Interactive cell items have no cursor entry point

### ISSUE THREAD

**Issue by bubthegreat** [jupyterlab/jupyterlab#3988]
Calls that function in a normal jupyter notebook that enter into an interactive command line within the cell aren't all working properly.  For example:
```
from IPython.core.debugger import Tracer; Tracer()()
from IPython import embed; embed()
```
It will show the ipdb, or the ipython prompt, but there's no cursor location that lets me type in that box, and it immediately moves me to the next cell.

**Comment by bubthegreat** [comment]
Digging more into this, now that I've installed jupyterlab extensions, my normal jupyter notebooks no longer have this functionality either.  Will keep digging to see if I can figure out why/where the break was introduced.

**Comment by jasongrout** [comment]
> It will show the ipdb, or the ipython prompt, but there's no cursor location that lets me type in that box, and it immediately moves me to the next cell.

For me, it moves to the next cell, but you can click in the box to type in it. Is that what you are seeing?

In the classic notebook, I see that the notebook focuses the box by default, instead of moving to the next cell. That indeed does look like a bit of focus handling that JLab is missing.

**Comment by bubthegreat** [comment]
I'm looking into versions - I downgraded to ipython 5.5 and all is well in the world again, but this was on ipython 6.2.1.  Trying to see if I can repro - and if not, I'll close it out as a fluke.

**Comment by bubthegreat** [comment]
Allright, it looks like I've found where the discrepancy is:

It looks like running the commands via bash in the cell (i.e. calling the script from bash rather than by importing directly in python) has issues reintering into the shell.  This looks like it's by design and I just haven't used it this way often.  It works correctly when running them directly from a python command (i.e. invoking a method directly rather than through bash).

[bash command not reintrant](https://user-images.githubusercontent.com/12198817/36614900-7abe59ac-189b-11e8-84ff-d49cf275cf49.PNG)

I could have sworn this worked before, but I might just be going crazy, so I'll leave it closed unless someone can sanity check me and I'm not going crazy that it used to work that way.

**Comment by jasongrout** [comment]
Thanks for tracking this down and posting your results. I'll still open an issue about the focus handling discrepancy.

**Comment by jasongrout** [comment]
Actually, focus is handled correctly when just doing `input('hi')`, for example.
