### ISSUE TITLE
find next occurrence in jupyter lab's text editor

### ISSUE THREAD

**Issue by mzhng** [jupyterlab/jupyterlab#3993]
Using either the default or sublime text key map, to search something in jupyter lab's text editor I press `ctrl+F`, type something, press `Enter` and my cursor goes to the first occurrence. The problem is after that, the search bar disappears and I can't figure out an easy way to jump to the next occurrence. Is there a faster way to jump to the next occurrence other than pressing `ctrl+F` and `Enter` again? In many editors, including sublime text, one can just press `Enter` to go to the next occurrence, but that doesn't work even using the sublime text key map.

**Comment by dustinmichels** [comment]
Great! Is there a way to go to previous occurrence?

**Comment by fomightez** [comment]
@dustinmichels It seems to go to the previous occurence  if you add in the `shift` key. 

On Macs the combinations are `command key + g key` to go to next and `command key +shift key +g key` to go to previous.

Only learned by looking in Sublime text. I would have expected it to be listed in the command palette. Or maybe when you hover on the search bar in the text editor?

**Comment by saulshanabrook** [comment]
This should somehow be visually documented

**Comment by agent-jay** [comment]
cmd+g and cmd+shift+g on Mac work for cycling through occurrences, even without the Sublime Text keymap. Good find, thanks!

**Comment by jasongrout** [comment]
We now have a more comprehensive search functionality which allows you to jump to previous next matches using the keyboard, thanks to #5795.
