### ISSUE TITLE
Output cleared on Clicking "Restart Kernel and Clear All Outputs" from the Kernel context menu

### ISSUE THREAD

**Issue by prateeks92** [jupyterlab/jupyterlab#3999]
When I click "Restart Kernel and Clear All Outputs" from the Kernel context menu, the outputs are cleared before the "Restart Kernel" dialog opens. Although the kernel doesn't restart just yet.

The dialog after clicking "Restart Kernel and Clear All Outputs" should also be able to stop clearing of outputs as well.

**Comment by jtpio** [comment]
Could this be related to #3696 and #3703?

**Comment by prateeks92** [comment]
Yes. I was actually trying to fix #3696 when i encountered this error.

would making changes [here](https://github.com/jupyterlab/jupyterlab/blob/517b167f8a1705f11fb9da09dea7bde36a36840f/packages/apputils/src/clientsession.ts#L814) fix these issues?

**Comment by saulshanabrook** [comment]
I think this is working now (possible from https://github.com/jupyterlab/jupyterlab/pull/3703 ?) When I click "Restart and Clear All Outputs" and then click cancel, my outputs remain intact.

Feel free to reopen if you aren't seeing this behavior
