### ISSUE TITLE
Notebook with output in another panel?

### ISSUE THREAD

**Issue by gkvoelkl** [jupyterlab/jupyterlab#4003]
Is it posible to have a notebook that draws in an other panel?

I want to do some 3d stuff.

On the left panel should be a notebook. On the right panel the 3d world.
You can work with the notebook  in python and see the figures life in another panel.

Any suggestions?

<img width="1346" alt="two" src="https://user-images.githubusercontent.com/16986218/36644759-4d0f0d10-1a5f-11e8-87b8-e7653eaf91bd.png">

Regards

Gerhard

**Comment by saulshanabrook** [comment]
You can right click on any output and click "Create New VIew for Output" which should open a new panel with just the output of that cell. Then, when that output changes, that panel will update.

**Comment by gkvoelkl** [comment]
Is it possible to do that with Python within the notebook?
Is there an Python API for Jupyterlab? Planned?

Thanks

**Comment by saulshanabrook** [comment]
@gkvoelkl Not at the moment. I am closing this issue since I think https://github.com/jupyterlab/jupyterlab/issues/4021 covers what you are asking. If it doesn't, feel free to .re-open this.
