### ISSUE TITLE
Help > 'Keyboard Shortcuts'

### ISSUE THREAD

**Issue by westurner** [jupyterlab/jupyterlab#4004]
In Jupyter Notebook, I can go to Help > 'Keyboard Shortcuts'. This seems to be missing in JupyterLab.

- [ ] JupyterLab: Add Help > 'Keyboard Shortcuts' 
- [ ] Jupyter Notebook docs: Include a table of (default) keyboard shortcuts (that I can find by searching for 'keyboard' or 'keyboard shortcuts')

I was able to find my Keyboard Shortcuts with:
-  Help > Launch classic notebook |> Help > Keyboard Shortcuts.

**Comment by saulshanabrook** [comment]
Adding a menu item (as suggested here https://github.com/jupyterlab/jupyterlab/issues/2976#issuecomment-331064686) makes sense to me!

**Comment by breckuh** [comment]
Not sure if someone else is working on this, but I just took a first pass.

Working code and a screenshot is here: https://github.com/breckuh/jupyterlab/commit/dfdc6f2220a93c954a8936051f5c7cb3151d6935

**Comment by saulshanabrook** [comment]
@breckuh That looks great! Could you [open a PR](https://help.github.com/articles/creating-a-pull-request/) for that branch so we can continue discussion there?

**Comment by westurner** [comment]
That looks nice. From reading the other linked issues, other
features/criteria mentioned include:

- A thematic organization
  - This would need to be updated for every new command; whereas listing
all bound commands is simpler but maybe not as useful

- Printable
  - Can this list be opened in a new JupyterLab tab, browser tab/window?
And printed?
  - Maybe a toggle between single and multiple columns would be most usable
and printable?

**Comment by breckuh** [comment]
> @breckuh That looks great! Could you [open a PR](https://help.github.com/articles/creating-a-pull-request/) for that branch so we can continue discussion there?

As you mentioned in the other thread #2976 https://github.com/jupyterlab/jupyterlab-shortcutui seems to cover this!

**Comment by BrenBarn** [comment]
Was this ever resolved?  The last comment I see is apparently about an extension that lets you look up shortcuts.

The old Jupyter had a button you could press to see a list of keyboard shortcuts.  If Jupyterlab doesn't have one, that's a regression from a user's perspective.  Having to install an extension or look through raw JSON in "advanced settings" is not reasonable for someone who is just trying to learn keyboard shortcuts.

**Comment by jasongrout** [comment]
IIRC, someone is working on integrating a more graphical keyboard shortcut editor. A much simpler project would be to make a table of existing keyboard shortcuts. We welcome contributions toward this!

**Comment by krassowski** [comment]
Given the discussions towards the end of the today's meeting: while this issue is important for feature parity/Notebook 7.0, this is an additive change (and https://github.com/jupyterlab/jupyterlab/pull/11960 has no breaking changes) which means that it could be included in 4.1 or in Notebook directly and should not block 4.0 release.

If anyone is interested in including it in 4.0, you are welcome to pick up work on https://github.com/jupyterlab/jupyterlab/pull/11960 (assuming you can finalise it by the end of February).
