### ISSUE TITLE
Add file extensions to language from "Settings"

### ISSUE THREAD

**Issue by scimax** [jupyterlab/jupyterlab#4005]
I think it would be a nice option to add custom file extensions to the association of languages from the "Settings" menu. I'm not used to the code base but @ian-r-rose suggested `jupyterlab_settings` and `jupyterlab_workspaces` for this purpose in #3858.

**Comment by saulshanabrook** [comment]
I think https://github.com/jupyterlab/jupyterlab/issues/4223 is about the same thing, so closing this in favor of that.
