### ISSUE TITLE
Kernel stdout/stderr goes to wrong cell after interrupt

### ISSUE THREAD

**Issue by Krastanov** [jupyterlab/jupyterlab#4006]
On the current beta of jupiterlab.

I use tools like `tqdm` or simple `python('\r',message,end='',flush=True)` to make custom progress bars for my calculation. `tqdm` in particular uses `stderr`.

The following happens:

- Start a computation that prints frequently to stderr/stdout in cell [1]
- Interrupt the computation
- Quickly start a computation in cell [2]
- The message that should have been sent to the output of cell [1] appears in the output of cell [2]

I do not have code that consistently reproduces this as it requires a lot of fast manual interruptions and code executions.

**Comment by saulshanabrook** [comment]
Thanks for opening this. I think this is likely the same issue as #3936. Closing for now to keep discussion there, but if that gets resolved and this isn't fixed, we can reopen it. Or if you know that it is in fact a different issue, feel free to reopen.
