### ISSUE TITLE
Add a button to the views to reload its cell

### ISSUE THREAD

**Issue by lucfr** [jupyterlab/jupyterlab#4011]
As soon as you change something in the code or the input variables that would change the output of some cells you currently have to scroll back to the cell to reload and and update the view on it. 

It would be very convenient to be able to reload each output producing cell directly from eachs view, saving you a lot of scrolling around large code files or notebooks.

**Comment by saulshanabrook** [comment]
Does "Run All" address this for you, or are you looking for more granular dependency tracking? 

Functionality that tracks the dependencies between cells and automatically reloads based on this graph is, I think, out of scope for jupyterlab core at the moment. It sounds like a good thing to experiment with in a third party extension.

**Comment by sccolbert** [comment]
It's generally intractable to infer the dependency graph of generic Python code. You could have a restricted subset of Python that would make it feasible, but as Saul said, that would be a good case for a third party extension.

**Comment by lucfr** [comment]
@saulshanabrook "Run All" would not work for me as I usually mix heavy computing code with quick data overviews and analysis. But my idea came from notebook cells, which I assumed would be still linked with its view in jupyterlab. But I can see that it might be too specific for a core functionality.

**Comment by saulshanabrook** [comment]
> "Run All" would not work for me as I usually mix heavy computing code with quick data overviews and analysis.

That makes sense. 

> But my idea came from notebook cells, which I assumed would be still linked with its view in jupyterlab. But I can see that it might be too specific for a core functionality.

What do you mean linked with their view? Like that each output cell has a corresponding input cell?

**Comment by saulshanabrook** [comment]
Ah, do you mean when you click "Create new view for output" on an output cell and get a popped out view of that output? Does #3941 cover your request?

**Comment by lucfr** [comment]
Yes, exactly!

**Comment by saulshanabrook** [comment]
Great! I am gonna close this issue then in favor of that one.

This would make a good first contribution, if you are interested in trying to tackle it!
