### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by arbelelad** [jupyterlab/jupyterlab#4014]
Hi,
Some missing features which were useful to me:
There is no option so restart Kernel and clear output with one click. Also - there is no indication when the process in some tab is running.

**Comment by drunkwcodes** [comment]
@arbelelad The running tabs are all listed in the running panel.

**Comment by arbelelad** [comment]
Thanks for the response. I wasn't making myself clear. I meant that there is no notification when a process of a cell is completed. In older version there used to be asterisk on the tab, but it doesn't exist anymore.

**Comment by AbdealiJK** [comment]
The restart and clear output option is available in the Kernel similar to the Kernel in jupyter notebook:
<img width="348" alt="screen shot 2018-03-25 at 5 13 01 pm" src="https://user-images.githubusercontent.com/2200743/37874607-d82aaa70-304f-11e8-91ad-9dd36dd629b5.png">
Is this what you were talking about ?


I assume the indicator for when the process in a tab is running is the icon of the browser tab ?
<img width="158" alt="screen shot 2018-03-25 at 5 14 01 pm" src="https://user-images.githubusercontent.com/2200743/37874618-f731f2fc-304f-11e8-9ebc-845684cf8a54.png"> -> Running a cell in the notebook
<img width="161" alt="screen shot 2018-03-25 at 5 14 07 pm" src="https://user-images.githubusercontent.com/2200743/37874620-f76c7486-304f-11e8-83d2-fcec2c6d90bd.png"> -> No cell running in the notebook

**Comment by saulshanabrook** [comment]
We added a busy favicon in https://github.com/jupyterlab/jupyterlab/pull/4361
