### ISSUE TITLE
"File Load Error" "allocation size overflow" while opening large csv on firefox

### ISSUE THREAD

**Issue by zemravi** [jupyterlab/jupyterlab#4015]
Hi,
I just started using jupyterlab, installed yesterday via pip on ubuntu 16.04 using "conda install jupyterlab". Whenever I try to open a large csv file (100s of mb) I get the following error.
"File Load Error for file xxxx.csv
allocation size overflow"
Is this meant to happen? If not, kindly let me know how I can fix it.
Thanks
Ravi

**Comment by AbdealiJK** [comment]
The current max size supported is around 700MB in Chrome and is browser dependent.
Refer: http://jupyterlab.readthedocs.io/en/latest/user/file_formats.html#delimiter-separated-values
