### ISSUE TITLE
notebook.tex not removed after creation of PDF document

### ISSUE THREAD

**Issue by Naereen** [jupyterlab/jupyterlab#4018]
Hi,
I just tested the latest version of JupyterLab (v0.31.8, very impressive work! :clap: !)
When experimenting the conversion to PDF, I noticed the the *temporary* file `notebook.tex` is not correctly removed (it is in `jupyter`).
Regards

**Comment by saulshanabrook** [comment]
Hmm, when I try downloading a notebook as a PDF in Jupyter Notebook, it also leaves the `notebook.tex` file. Looking at [the nbconvert pdf exporter](https://github.com/jupyter/nbconvert/blob/master/nbconvert/exporters/pdf.py), I don't see any options for removing cleaning up that file.

**Comment by saulshanabrook** [comment]
I didn't have much luck with that, so I opened an issue upstream https://github.com/jupyter/nbconvert/issues/767

**Comment by Naereen** [comment]
You're right, it should be in nbconvert and not here. I don't have time to test right now, sorry

**Comment by saulshanabrook** [comment]
@Naereen no worries. I opened https://github.com/jupyter/nbconvert/pull/768 which should fix this in nbconvert.

**Comment by jasongrout** [comment]
Closing this, then. Thanks @saulshanabrook!
