### ISSUE TITLE
Find and Replace not working

### ISSUE THREAD

**Issue by lucfr** [jupyterlab/jupyterlab#4019]
Might be a bug, or a feature missing specifically for Jupyter Notebook files.

**Comment by saulshanabrook** [comment]
@lucfr Yeah currently find and replace is only implemented in the text editor, not in the notebooks. https://github.com/jupyterlab/jupyterlab/issues/1074 is tracking this issue.

**Comment by saulshanabrook** [comment]
I am closing this in favor of that other issue.
