### ISSUE TITLE
Saving figure outputs with SVG format

### ISSUE THREAD

**Issue by sballin** [jupyterlab/jupyterlab#4022]
I like using the SVG format to view the matplotlib figures I create. But I find it difficult to save them to my computer, because they can't be dragged/right-click saved in Chrome on mac. The closest thing I can do is right-click and "Create new view into output." It would be great if there was an option in this right-click menu to save the SVG file as a download.

**Comment by saulshanabrook** [comment]
If you hold down shift as you right-click the browser's context menu should appear with "Save Image As..." in it. Is this what you wanted to do?

**Comment by sballin** [comment]
I did see that, but it only gives the option "Save As..." for me and that tries to save the entire web page as an HTML file.

**Comment by saulshanabrook** [comment]
Interesting, when I use `%matplotlib inline` I get the option to save it as a PNG.

<img width="1026" alt="screen shot 2018-02-26 at 11 47 10 am" src="https://user-images.githubusercontent.com/1186124/36683163-df67e9bc-1aea-11e8-8e5b-4d0f8ed14ffe.png">

**Comment by sballin** [comment]
Looks like it's possible to put the svg code inside an img tag: https://codepen.io/anon/pen/YeRzjb (modified from another pen, not my original work). Right-click save and drag-and-drop both work for these!

**Comment by saulshanabrook** [comment]
If we wanted to change the default SVG renderer to use this inline img method instead of the `svg` element, we would have to change [the `renderSVG` function](https://github.com/saulshanabrook/jupyterlab/blob/987702e76cb17265fa249ba67775e35804a69077/packages/rendermime/src/renderers.ts#L448). However, it also currently does some extra URL relation and latex typesetting on the rendered SVG elements and I am not sure how those would work if it was all inline data.

**Comment by sballin** [comment]
I would be very happy to see either of those options, they both address the issue well. The first seems more consistent with the existing interface (e.g. inline pngs, at least with chrome/mac), although the second might be easier to implement.

**Comment by saulshanabrook** [comment]
After [talking to @jasongrout](https://gitter.im/jupyterlab/jupyterlab?at=5a95da0c35dd17022e00f4c8), I will try to implement the first option of embedding in an `img`.

**Comment by sballin** [comment]
Awesome, thanks for doing this!
