### ISSUE TITLE
Make Browser's Native Context Menu More Discoverable

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#4023]
Right now the fact that SHIFT right-click brings up the browser's context menu is not obvious. It wasn't until I read I comment about it that I realized it was possible. Others have had the same confusion (https://github.com/jupyterlab/jupyterlab/issues/3011#issuecomment-360021201, https://github.com/jupyterlab/jupyterlab/issues/3911#issuecomment-367498164).

It [is explained](https://jupyterlab.readthedocs.io/en/stable/user/interface.html#context-menus) in the JupyterLab docs already, so it might make sense to describe the functionality in the interface somehow. One option would be to include some text in the existing JupyterLab context menu that says something like "Use SHIFT right-click to access the system context menu..."

**Comment by jasongrout** [comment]
This is coming up somewhat frequently, so triaging to beta 3 for at least starting a design discussion.

**Comment by mangecoeur** [comment]
Perhaps its worth thinking about what people are needing the shift-click for. I suspect its mostly people looking for the 'save image as' menu. I think it would be good to add a 'save image' option to the context menu where appropriate, since that's probably what people actually want.

**Comment by fperez** [comment]
+1 to @mangecoeur's point - even if there's better discoverability for shift-click in general, I suspect a direct 'save image' entry will cover the _vast_ majority of needs.

**Comment by dhirschfeld** [comment]
I want the native browser context menu to copy/paste text in the terminal. I want to copy and paste stuff in the terminal *all the time* but have never (yet) wanted to save an image.

While I'm here I'll put in a plug for @stephenakearns' [feature request](https://github.com/jupyterlab/jupyterlab/issues/3011#issuecomment-344646455) to make selecting text in the terminal also copy the text - or at least a setting to enable such.

**Comment by jasongrout** [comment]
In #4660, @stefanv also wants copying of a URL as a common operation.

**Comment by ian-r-rose** [comment]
I think that should be pretty doable using the `jp-RenderedHTML` selector.

**Comment by tgeorgeux** [comment]
Just to revive this conversation, it seems if we add 'save image' and 'Copy/paste' to notebook output and terminal context menus (respectively) this would solve the lion's portion of this issue. Does anybody have any other examples of times they were trying to surface the browser context menu?

**Comment by jasongrout** [comment]
Save Link as..., Copy Link location, open the developer tools inspecting an element are several other menu items I use.

**Comment by tgeorgeux** [comment]
@jasongrout I also use those frequently, but primarily in the context of developing Jupyter Lab, not using it. I think adding useful tools for 'doing data science' ought to be a separate discussion from tools for 'developing jupyterlab'. 

As long as the shift-right-click is documented clearly in the developer documentation I think it's covered for the "I'm developing JupyterLab" crowd.
