### ISSUE TITLE
Add "Save Image As" to context menu

### ISSUE THREAD

**Issue by PeterMitrano** [jupyterlab/jupyterlab#4024]
When I plot with matplotlib (or show any image) in Jupyter Notebook, I was able to right-click and do "save image as...". This no long exists in Jupyter Lab, and I'd really like it to come back!

Right now my work around is to use the chrome element-inspector tool which is very clumsy and time consuming.

**Comment by vidartf** [comment]
Ref. https://github.com/jupyterlab/jupyterlab/issues/4023

**Comment by jasongrout** [comment]
@PeterMitrano - any other questions? We've noted this in the docs under the section talking about context menus: http://jupyterlab.readthedocs.io/en/stable/user/interface.html#context-menus

Is there anywhere else you would have found it earlier?

**Comment by PeterMitrano** [comment]
Great, this solved my issue! I was only looking within the Jupy

**Comment by AbdealiJK** [comment]
I think this is a feature a lot of people may want ... I've seen a few people selecting text and right-clicking to copy-paste the text from the output-area.

These users would rarely read the documentation present in another location.

Not sure how, but a better UX for this would be great.

**Comment by jasongrout** [comment]
Great! Let's move discussion of a better ux over to #4023.
