### ISSUE TITLE
[Issue] "Tab Complete" of directory now shows all objects and methods

### ISSUE THREAD

**Issue by jolespin** [jupyterlab/jupyterlab#4025]
In previous versions and `Jupyter Notebook` one was able to "tab complete" and navigate through a directory.  For example, 

(1) `pd.read_table`("./
(2) press `[tab]`
(3) list of available items within the `current directory`

![image](https://user-images.githubusercontent.com/9061708/36687163-a43c87f6-1add-11e8-97bf-d5607b2527d4.png)

Now it appears to show all of the methods associated with the `string object` and also `objects` that are loaded into the working environment.   Below shows custom functions and those loaded from packages like `keras`. 

![image](https://user-images.githubusercontent.com/9061708/36687270-f1aefaf0-1add-11e8-9946-beb832d7d8a8.png)

**Comment by saulshanabrook** [comment]
This is fixed for me after I installed `ipykernel==4.6.1`, as described in https://github.com/jupyterlab/jupyterlab/issues/3672#issuecomment-368384535

**Comment by jasongrout** [comment]
Thanks for the report! It looks like the problem is possibly in ipykernel. Let's move the conversation to #3672, where the problem was first reported.
