### ISSUE TITLE
Invisible text Cursor when editing python text files in Dark mode theme

### ISSUE THREAD

**Issue by schwab** [jupyterlab/jupyterlab#4030]
I don't know if this is because the dark theme actually has a light/white background (maybe the cursor is supposed to be white and the background is supposed to be black).  Anyway when set to jupyter lab dark theme the text cursor is invisible.  The select coloring works (light cyan), but it's impossible to see the text cursor.

**Comment by gerardo** [comment]
Might be unrelated, but the text gets invisible (read: white text on white background) when you try to edit the filename:

<img width="375" alt="screen shot 2018-02-27 at 6 04 21 pm" src="https://user-images.githubusercontent.com/327424/36715097-d9e45b34-1be8-11e8-8375-982730ea9de5.png">

This happens on both the light and dark themes.

**Comment by saulshanabrook** [comment]
RIght now in master, I can see the cursor, but the text editor background is light:

<img width="1125" alt="screen shot 2018-02-27 at 11 51 25 am" src="https://user-images.githubusercontent.com/1186124/36742037-a349d1dc-1bb4-11e8-8840-1170cb5fb5f1.png">

Is this the same behavior you are seeing @schwab? It may have been affected by a recent upgrade of the codemirror package (https://github.com/jupyterlab/jupyterlab/pull/3905)

**Comment by saulshanabrook** [comment]
@gerardo On master, the rename coloring seems to be working:

<img width="333" alt="screen shot 2018-02-27 at 11 54 14 am" src="https://user-images.githubusercontent.com/1186124/36742170-01483184-1bb5-11e8-81a5-80618d4e0153.png">

**Comment by jtpio** [comment]
Same here on master (1e8a3659ea687faaba9ae948789d8483185c09de), cursor not visible when using the `jupyter` text edit theme with the JupyterLab Dark Theme:

![image](https://user-images.githubusercontent.com/591645/36761745-d4a93b34-1c20-11e8-9f6e-8b0bbad21362.png)

When switching to `base16-dark` the cursor becomes visible.

**Comment by ian-r-rose** [comment]
Hi all, the text cursor in the dark theme has been fixed in #3962, and will be available in the next release.

**Comment by jasongrout** [comment]
Closing as resolved. Please comment if there is still an issue and we need to reopen this. Thanks!
