### ISSUE TITLE
HTML style attribute not rendering

### ISSUE THREAD

**Issue by gerdm** [jupyterlab/jupyterlab#4035]
There seems to be a problem regarding html attributes. Whereas the classical notebook seems to render the *style* attribute for an h2 tag just fine, JupyterLab seems not to take it into account.

<img width="339" alt="jupyter_lab" src="https://user-images.githubusercontent.com/4108759/36732789-5b976c48-1b94-11e8-923d-f416b14f24cb.png">

<img width="413" alt="jupyter_notebook" src="https://user-images.githubusercontent.com/4108759/36732842-7e24263e-1b94-11e8-8af0-c589a95b8829.png">

**Comment by ian-r-rose** [comment]
Hi @gerdm, by default both JupyterLab and the classic notebook sanitize rendered HTML for security reasons. Unfortunately, the list of tags/attributes that are sanitized is not identical between the two, so there are some differences in rendering things that would be sanitized in one and not the other.

I am not sure what the security ramifications are for allowing all `style` attributes at the moment, but in general we should be careful here.

**Comment by gerdm** [comment]
Thank you @ian-r-rose !
Any way we can help in bringing the style attribute to JupyterLab? I used it frequently for my notebooks, so it would be nice to have.

**Comment by blink1073** [comment]
This is being tracked in #1812, I'll post an update there.  Thanks!
