### ISSUE TITLE
Shift-tab tooptip does not pop out

### ISSUE THREAD

**Issue by swyoon** [jupyterlab/jupyterlab#4036]
One of my favorite features in jupyter notebook was "popping-out" of the shift-tab tooltip, by hitting shift-tab four times, so that I can continue coding while glancing over the doctring.

In the Jupyter lab notebook, the tooltip appears when shift-tab is hit, but hitting multiple times of shift-tab does not make the tooltip pop out. However, my (classic) jupyter notebook still has this feature.

Is it intended? or is it not implemented yet?

The attached is the screenshot of what I called a pop-out shift-tab tooltip in the classic jupyter notebook.

![image](https://user-images.githubusercontent.com/10072033/36735122-c5de533a-1c18-11e8-98c8-327546805adf.png)

Version info:
python 3.6.3 (not anaconda)
```
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.31.8
jupyterlab-launcher==0.10.5
```

**Comment by ian-r-rose** [comment]
Hi @swyoon, you may be interested in trying out the inspector, which provides similar information. Open the command palette and select `Open Inspector`.

**Comment by swyoon** [comment]
@ian-r-rose Thanks for kind reply. With the inspector, it seems like pop-out tooltip is not necessary!
