### ISSUE TITLE
404 : Not Found You are requesting a page that does not exist!

### ISSUE THREAD

**Issue by ktuluv** [jupyterlab/jupyterlab#4037]
As requested on issue #1346, I tried the following, but with no success.

`jupyter serverextension enable --py jupyterlab --user`

![image](https://user-images.githubusercontent.com/36892176/36736835-87d22434-1ba7-11e8-9dc9-489f63022138.png)

This is what I get when I run the --debug
![image](https://user-images.githubusercontent.com/36892176/36737347-d8eaaa34-1ba8-11e8-8d97-7e13044c5c40.png)

**Comment by blink1073** [comment]
Hi @ktuluv, can you please run `conda update jupyterlab` to pick up the latest and try again?

**Comment by ktuluv** [comment]
@blink1073 Thank you, that worked!!

**Comment by jasongrout** [comment]
Great!
