### ISSUE TITLE
Changing bash terminal type to interactive + login

### ISSUE THREAD

**Issue by mj-harvey** [jupyterlab/jupyterlab#4042]
Hi,

For my environment I need the bash shell started within the terminal to be an interactive login shell,
so that /etc/profile gets sourced.
Seems the default behaviour is an interactive non-login shell.

How can I change this?

**Comment by blink1073** [comment]
Hi @mj-harvey, you can set the environment variable `SHELL=bash` or run `jupyter notebook --generate-config` and set `c.NotebookApp.terminado_settings = { 'shell_command': 'bash' }` in the created `jupyter_notebook_config.py`.

**Comment by mj-harvey** [comment]
And I can add bash flags there too?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Steven SilvesterSent: Tuesday, 27 February 2018 18:46To: jupyterlab/jupyterlabReply To: jupyterlab/jupyterlabCc: M J Harvey; MentionSubject: Re: [jupyterlab/jupyterlab] Changing bash terminal type to interactive + login (#4042)Hi @mj-harvey, you can set the environment variable SHELL=bash or run jupyter notebook --generate-config and set c.NotebookApp.terminado_settings = { 'shell_command': 'bash' } in the created jupyter_notebook_config.py.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jupyterlab/jupyterlab","title":"jupyterlab/jupyterlab","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jupyterlab/jupyterlab"}},"updates":{"snippets":[{"icon":"PERSON","message":"@blink1073 in #4042: Hi @mj-harvey, you can set the environment variable `SHELL=bash` or run `jupyter notebook --generate-config` and set `c.NotebookApp.terminado_settings = { 'shell_command': 'bash' }` in the created `jupyter_notebook_config.py`."}],"action":{"name":"View Issue","url":"https://github.com/jupyterlab/jupyterlab/issues/4042#issuecomment-368983501"}}}

**Comment by blink1073** [comment]
No, those are not supported.

**Comment by mj-harvey** [comment]
Ok, I can wrapper bash. Thanks!

**Comment by mj-harvey** [comment]
@blink1073 
I added:
c.NotebookApp.terminado_settings = { 'shell_command': '/apps/jupyterhub/2018-02-19/bin/bash_wrapper' }
and restarted the jupyterlab session (didn't restart the owning jupyterhub).
The setting isn't being honoured, the original default /bin/bash is being used.

**Comment by blink1073** [comment]
Ah, sorry, that takes a list, so you can pass in arguments: `c.NotebookApp.terminado_settings = { 'shell_command': ['/bin/bash', '--foo'] }`.

**Comment by mj-harvey** [comment]
Ok, thanks, that simplifies things!
I just need to work out now how to configure the jupyterhub with the location of a central jupyter_notebook_config.py..

**Comment by blink1073** [comment]
cf http://jupyterhub.readthedocs.io/en/latest/getting-started/spawners-basics.html

**Comment by mj-harvey** [comment]
That's got it. 
http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html told me about 'jupyter --paths', which gave the location for the central config files.

Thank you very much for your help @blink1073
