### ISSUE TITLE
Cannot access '@jupyterlab/application-extension' CommandIds for use in native theme switching

### ISSUE THREAD

**Issue by declanvk** [jupyterlab/jupyterlab#4046]
Hello (@blink1073),

As part of implementing native theme switching for the electron app, I would like access to the `CommandIds` namespace inside the `@jupyterlab/application-extension`. Specifically the CommandId I need is `changeTheme = 'apputils:change-theme'`.

Thank you,
Declan Kelly

**Comment by ian-r-rose** [comment]
Can you execute the command using the id string directly?
```typescript
commands.execute('apputils:change-theme', args)
```

**Comment by declanvk** [comment]
Definitely, but would the changing of that string be an issue in the future? If it is set in stone, then there is definitely no need to export.

**Comment by ian-r-rose** [comment]
Yes, changing the string in the future would be an issue there. However, there are many places in the codebase where we are directly using the string IDs, so at least you would be following precedent :)

**Comment by declanvk** [comment]
Alright, I'll hold off then. Thank you for the feedback!
