### ISSUE TITLE
/bin/bash: jupyter: command not found

### ISSUE THREAD

**Issue by Alcampopiano** [jupyterlab/jupyterlab#4047]
Hi guys,

Just curious if you could point me in the right direction here.

I am running nbconvert in a loop from within an IDE (PyCharm), and although it used to work fine a few months ago, not whenever I call nbconvert from within a python script, the system can't seem to find it. I have tried this using both the os and subprocess module. When I use the Linux terminal directly, or even when I open one in PyCharm, the commands work fine. Example,

```
from subprocess import call
import os

call('jupyter nbconvert --to notebook --execute mynotebook.ipynb --output mynotebook.ipynb', shell=True, executable='/bin/bash')
/bin/bash: jupyter: command not found

```
```
os.system('jupyter nbconvert --to notebook --execute mynotebook.ipynb --output mynotebook.ipynb')
/bin/sh: 1: jupyter: not found
```
Any ideas what I'm doing wrong?

**Comment by blink1073** [comment]
Most likely you have the path to jupyter on your PATH environment variable.   Does it work if you using `env=os.environ` in the `subprocess` `call`?

**Comment by Alcampopiano** [comment]
Still not working unfortunately. I tried the following:

```
subprocess.Popen('jupyter nbconvert --to notebook --execute mynotebook.ipynb --output `mynotebook.ipynb',` shell=True, env=os.environ)

/bin/sh: 1: jupyter: not found
```

**Comment by blink1073** [comment]
From a terminal, `which jupyter` will give you the full path to use.

**Comment by Alcampopiano** [comment]
Yep, if I add the full path to jupyter, it works in the system call. Thanks very much. Not sure what got messed up there.

**Comment by Alcampopiano** [comment]
One more quick question about this. What is the best way of making it so that jupyter is always on the path when I make a system call? I have installed everything using conda, and so jlab is in `/home/allan/anaconda3/bin/jupyter` which is where PyCharm is looking for its console and terminal. Well, at least when I open them up from PyCharm, they all seem to know where jupyterlab is.

**Comment by blink1073** [comment]
You can add `/home/allan/anaconda3/bin/` to your PATH variable in your `~/.bashrc` file: `export PATH=/home/allan/anaconda3/bin/:$PATH`, and then `env=os.environ` should work with `call`.

**Comment by Alcampopiano** [comment]
Thanks very much
