### ISSUE TITLE
Allow changing default file opener

### ISSUE THREAD

**Issue by CleoQc** [jupyterlab/jupyterlab#4048]
It would be nice if there was a configuration setting that would allow us to get an .md file to open in the viewer mode directly instead of in editor mode. 

Our users are new to jupyter notebooks and our documentation is in markdown. Yet beginner users do not know about viewer mode so they're not getting easy access to the documentation.

Thanks!

**Comment by jasongrout** [comment]
Or more generally, it would be great if there was a user setting for the default widget used for any particular file extension.

**Comment by saulshanabrook** [comment]
I changed the name of this issue to reflect the more general.

**Comment by saulshanabrook** [comment]
Closing this in favor of https://github.com/jupyterlab/jupyterlab/issues/4223 since I think that is the same issue

**Comment by ian-r-rose** [comment]
I think these are different issues. This one is about customizing the default opener, rather than the default CodeMirror mode.

**Comment by saulshanabrook** [comment]
Thanks @ian-r-rose, good point.
