### ISSUE TITLE
Missing settings option in menu bar

### ISSUE THREAD

**Issue by zaeemnalla** [jupyterlab/jupyterlab#4050]
I've just installed JupyterLab on macOS but for some reason I'm missing the settings option in the menu bar. Is there something else that I needed to do?
![jupyterlab](https://user-images.githubusercontent.com/20092821/36755754-da97ba26-1c15-11e8-95f5-8ae162e0b688.png)

**Comment by ian-r-rose** [comment]
Hit @zaeemnalla, it looks like you are running an older version of JupyterLab. Try upgrading to v0.31.8.

**Comment by cata0309** [comment]
I have jupyter lab v 3.0.8 and I still do not see any settings menu

**Comment by cata0309** [comment]
What is the difference between `jupyter-lab` and `jupyter lab`?

**Comment by jasongrout** [comment]
@cata0309 - can you open a new issue? This is 3 years old.

`jupyter lab` calls the `jupyter-lab` program.
