### ISSUE TITLE
Jupyterlab crashes when CPU usage is full

### ISSUE THREAD

**Issue by r-luo** [jupyterlab/jupyterlab#4051]
I was running something that takes 100% of my cpu:
![image](https://user-images.githubusercontent.com/3460073/36755934-a72394ec-1bdb-11e8-8e76-a62b2da802a2.png)

And JupyterLab crashed:
![image](https://user-images.githubusercontent.com/3460073/36755945-ae9b2b90-1bdb-11e8-82db-0b1cc3213fa0.png)

The same job never crashed Jupyter Notebook... It was something ran with `dask.multiprocessing`

**Comment by jasongrout** [comment]
Can you post code to reproduce this?

**Comment by madcarrot** [comment]
I'll try to get the code... I forgot where I saved it. But basically the code below is what can cause Jupyter Lab to freeze:

![image](https://user-images.githubusercontent.com/3460073/36758186-b429eeb0-1be1-11e8-950c-5dad6d394657.png)

**Comment by blink1073** [comment]
I think this will be fixed by https://github.com/jupyterlab/jupyterlab/pull/4045.

**Comment by madcarrot** [comment]
@blink1073 I'll try it later, thanks!

**Comment by madcarrot** [comment]
The code:
```python
from dask import delayed
import dask
import pandas as pd
import numpy as np
from dask.diagnostics import ProgressBar
import dask.multiprocessing

data = pd.DataFrame({'id': np.array([i for i in range(100)] * 1000), 'val': np.random.randint(low=1, high=10, size=100000)}).sort_values('id').set_index('id')

def some_ops(df):
    return df.groupby('id').diff(1)

x = [delayed(some_ops)(data) for i in range(1000)]
for j in range(10):
    x = [delayed(some_ops)(df) for df in x]
res = delayed(pd.concat)(x)

with ProgressBar():
    res.compute(get=dask.multiprocessing.get)
```

**Comment by helenakristina** [comment]
I got this same error when I tried to find and replace on a tilde-separated file so I could use the csv table-viewer.

**Comment by saulshanabrook** [comment]
Please comment with how to reproduce on a recent version of JupyterLab.
