### ISSUE TITLE
Can't right-click the space underneath files in file menu

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#4055]
If I'm copying/pasting between folders using JupyterLab, my intuition is to right-click the space _underneath_ the list of files in a given folder in order to paste. However, right now right-clicking this space does nothing. You need to right click one of the files/folders and then you'll be able to click "paste". This feels clunky as a part of me wonders whether I'm actually _overwriting_ the file I just right clicked (which is actually not what's happening)

**Comment by ian-r-rose** [comment]
This is a duplicate of #3602, and we should really get around to fixing it :)

**Comment by choldgraf** [comment]
cool - closing :-)
