### ISSUE TITLE
Send commands from txt file to Console

### ISSUE THREAD

**Issue by pgensler** [jupyterlab/jupyterlab#4059]
I think it would make sense to have the ability to link the text editor with the Console or Notebook, so you could easily send your commands interactively.  Similar to an IDE, if that makes sense?

**Comment by ian-r-rose** [comment]
Hi @pgensler, this already exists: in the File menu, select "New Console For Text File".

**Comment by jasongrout** [comment]
See the documentation for it at http://jupyterlab.readthedocs.io/en/stable/user/documents_kernels.html.

If this isn't what you were looking for, please comment to continue the discussion.

**Comment by pgensler** [comment]
This is nice, I just wouldn't think to right click and create a console for the document without reading the docs first. I think it would be nice to sync up a txt file with a terminal, although that would bypass the notebook. Does that make sense?
