### ISSUE TITLE
Check for coherence between command names between console and notebook

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#406]

**Comment by ellisonbg** [comment]
Also, when we do this, we shoudl cross check command names with the existing notebook. Last fall, when I was in NYC, we sat with the JLab team and made sure the existing command names were consistent. We spent a full day on this and should re-use those patterns.

**Comment by blink1073** [comment]
I'm not so sure that they should have the same names, running a notebook cell is fundamentally different from a console prompt, which always executes code.  
What prompted this originally was that I tried to type `execute` in the palette to execute a code cell in the notebook.  If the console command were also called `run`, it would still have been sorted first.

**Comment by ellisonbg** [comment]
There are two sets of names we need to audit:

* The actual command ids
* The variables in the `CommandID` object that refer to those ids.

In recent work I have noticed that in some cases we include nouns (`restartKernel`) but in other cases we don't (`interrupt`). I think in general I prefer to always include the nouns as we hae done in the classic notebook commands.

**Comment by blink1073** [comment]
For reference from classic notebook:

<image src="https://cloud.githubusercontent.com/assets/2096628/25595289/d81cd530-2e89-11e7-8c18-b646690f143d.png" width=200>

<image src="https://cloud.githubusercontent.com/assets/2096628/25595305/e2d004a2-2e89-11e7-8072-4a55a2b022ab.png" width=200>

<image src="https://cloud.githubusercontent.com/assets/2096628/25595316/ea97f82a-2e89-11e7-9aa8-df1d40cf62ac.png" width=200>

<image src="https://cloud.githubusercontent.com/assets/2096628/25595373/2fea7ed4-2e8a-11e7-9e59-0053511da408.png" width=200>

**Comment by blink1073** [comment]
This one should wait for #2123 since that is affecting a lot of the notebook APIs.
