### ISSUE TITLE
Update Jupyter website with JupyterLab header on home page

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#4066]
Here is Cameron's branch with a separate page:

https://github.com/cameronoelsen/jupyter.github.io/tree/lab-page

We probably want to adapt that material (in highly condensed form) to the home page.

@jzf2101 @tgeorgeux

**Comment by jzf2101** [comment]
See https://github.com/jupyter/jupyter.github.io/pull/266

**Comment by JasonWeill** [comment]
Closing because website issues are now tracked at https://github.com/jupyter/jupyter.github.io/issues.
