### ISSUE TITLE
Download as reveal.js slides results in a single page

### ISSUE THREAD

**Issue by SimonEnsemble** [jupyterlab/jupyterlab#4067]
When I download [my Jupyter Lab Notebook](https://github.com/SimonEnsemble/scratch/blob/master/slide_test.ipynb) as a Reveal.js slideshow, I get just a single page instead of slides. Do I need to signal for a new slide somehow in a way that is different than how `nbconvert` works? For each cell, I go into "Cell Tools", "Slide type", and select "Slide".

**Comment by blink1073** [comment]
Hi @SimonEnsemble, running the slides right now requires a server, which can be run as `python -m nbconvert.postprocessors.serve foo.slides.html`, where `foo` was the name of the original notebook.
  
Note that you can configure this or wait until the next release of `nbconvert` for it to work without a server. cf https://github.com/jupyter/nbconvert/pull/732, where the default will be `https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.5.0`.

To configure using the current release, use `SlidesExporter.reveal_url_prefix`, cf http://nbconvert.readthedocs.io/en/latest/config_options.html

**Comment by SimonEnsemble** [comment]
@blink1073 Thanks!

I found easiest to not even use Jupyter Lab to download as Reveal.js slides but instead use:
`jupyter nbconvert FreqResp.ipynb --to slides --post serve --SlidesExporter.reveal_theme=sky `

It will be great when we can serve from Jupyter Lab itself. Awesome work.

**Comment by yoonghm** [comment]
I tried the command. `/custom.css` was missing and it did not move to other pages.

**Comment by xigrug** [comment]
So how to solve this problem?
