### ISSUE TITLE
Questions post webinar.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#4068]
Just sharing questions I got after a webinar as a datapoint, with short answers.

Q.  I heard that JupyterLab is gonna release the 1.0 version and it seems that JupyterLab and Jupyter are gonna converge to one? 

A: Classic notebooks will be retiring in a few years.  We will maintain both for the time being.  JupyterLab ultimately will have new features that won’t be available in the classic notebooks.  

Q. How will JupyterLab and CoCalc evolve together?

A: CoCalc is a for-profit company, so it will be up to them. The Jupyter team has occasional conversations with them, but it is not the same project. 

Q. In Jupyterlab, is there an option to have matplotlib plots pop-up in a separate window within the Jupyterlab interface (instead of being inlined in a notebook) ?

A: Part of future development, as far as I remember you can “drag” outputs into a separate window already. 

Q: Have you considered to include some of the features from Spyder into JupyterLab, such as the variable view window, which resembles Matlab and I think it’s very convenient?

A: Part of future development. One of the challenge is  to make that multi-language aware. Making it for a single language can make assumption that Jupyter cannot. 

Q:Are there API changes that will require kernel maintainers to update their kernels that currently run in Jupyter Notebooks to allow them to run in Jupyter Lab?

A: No you don’t need to change anything.

Feel free to close

**Comment by jasongrout** [comment]
Great answers!

> A: Part of future development, as far as I remember you can “drag” outputs into a separate window already.

Right-click on an output and select Create new view of output.

Closing as resolved. Thanks for posting here for reference.
