### ISSUE TITLE
Make link anchors to each video in docs

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4069]
Often I try to link to a specific video in the docs to illustrate how to do a specific task. This would be much easier if each video (or sentence above the video) had separate link anchors.

**Comment by anhqle** [comment]
I was trying to make this my first PR, but it looks like the videos already got link anchors (at least in files.rst and notebook.rst).

Do we just add link as needed, or you have have specific sections of the docs that need improvements?

**Comment by ian-r-rose** [comment]
Hi @anhqle, sorry, this "good first issue" has already been done, and we forgot to close the issue. Thanks for checking, and feel free to ask about any of the other ones!
