### ISSUE TITLE
Automatically build releases from travis

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#407]
@sccolbert suggested we build releases automatically from travis when a tag. Maybe only tags of the form vX.Y.X or something. That would _great_.

**Comment by damianavila** [comment]
:+1:

**Comment by blink1073** [comment]
Jason and I discussed this in person, and realized it might actually be a security risk to produce and release the binaries using an untrusted server.

**Comment by sccolbert** [comment]
That's a good point. Do any of the Travis auth tokens have repo-write permissions? If they do, then our current setup is already open to that vulnerability. If the tokens are read-only, then it might be a good idea to leave it that way.

**Comment by blink1073** [comment]
We are authorizing the documentation to be pushed, but not releasing a binary.

**Comment by jasongrout** [comment]
Well, repo-write permissions is more easily caught because we all have a good copy of the repo, so it's not the same thing as inserting an unknown player between the repo and pypi/npm.

**Comment by ellisonbg** [comment]
We decided to not go in this direction for now...

**Comment by damianavila** [comment]
Sorry to raise this again, but given that the whole conda-forge effort is backed on systems like TravisCI, do you really thing that we can not do release in the same way we are producing and delivering packages with conda-forge?

**Comment by jasongrout** [comment]
We're re-evaluating this now that we see how tedious and error-prone the release process is. Here is a relevant lerna issue: https://github.com/lerna/lerna/issues/653

**Comment by krassowski** [comment]
Should this one be closed in favour of using jupyter-releaser?

**Comment by blink1073** [comment]
Agreed, thanks!  Closing in favor of #10340.
