### ISSUE TITLE
ipdb command output is all concatenated instead of being between calls

### ISSUE THREAD

**Issue by bubthegreat** [jupyterlab/jupyterlab#4071]
When in the interactive ipdb terminal, the output for the command is being concatenated at the top instead of in the order that the terminal should actually show it - example below, ctlr = 'CT1' and fields = ['els_notify'].  Currently looks like:

```
'CT1'
['els_notify']
ipdb> ctlr
ipdb> fields
```
Expectation is:
```
ipdb> ctlr
'CT1'
ipdb> fields
['els_notify']
```

**Comment by saulshanabrook** [comment]
Is this in the notebook or console?

**Comment by Omegastick** [comment]
@saulshanabrook It happens in notebooks for me.
