### ISSUE TITLE
Cannot reconnect to kernel in Jupyterlab and keep receiving new output

### ISSUE THREAD

**Issue by madcarrot** [jupyterlab/jupyterlab#4072]
Jupyter Notebook had the ability to "reconnect to kernel" if I need to disconnect from my internet for a while, and can continuously receive new outputs. However, with the exact same settings, if I disconnect from the internet and reconnect, I will forever lose all future output. I am running `jupyterlab==0.31.9` and here's the kernel menu:
![image](https://user-images.githubusercontent.com/3460073/36823872-523bf0da-1ccd-11e8-86aa-7b27e6a83cf6.png)

I believe that this is different from #2526 and #2648 because the "reconnect" menu item is still not available after the corresponding PR, and I still cannot receive new outputs after I disconnect and reconnect. It's different from #2833 because the functionality to reconnect to Jupyter Notebook and keep receiving outputs is already there, just not in Jupyterlab.

**Comment by blink1073** [comment]
Hi @madcarrot, this option is available in the command palette:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/2096628/36860059-f822703c-1d45-11e8-808a-3df351132b36.png">

**Comment by madcarrot** [comment]
Got it! Thanks for pointing me to it!
