### ISSUE TITLE
Output cut in the middle -- limit to the amount of printed output for a set of Python 3 statements.

### ISSUE THREAD

**Issue by shyamalschandra** [jupyterlab/jupyterlab#4076]
Will this be fixed or is there a short-term solution to fix this problem?

![screen shot 2018-03-01 at 7 40 43 am](https://user-images.githubusercontent.com/9545735/36847430-dfd95cba-1d23-11e8-82fa-119c8d468410.png)

**Comment by ian-r-rose** [comment]
Hi @shyamalschandra, this is being discussed in #4028. Can we continue this there?
