### ISSUE TITLE
.sgv icons are not showing up

### ISSUE THREAD

**Issue by dvm-shlee** [jupyterlab/jupyterlab#4077]
Hi All,

I have an issue on icon as below, my operating system is based on minimally installed Centos 7
![screenshot from 2018-03-01 09-16-30](https://user-images.githubusercontent.com/7221078/36849197-5cf5a17e-1d31-11e8-9cfd-a2a58d9d7580.png)

I've done some research to solve this issue, and it seems mime.types are not sufficiently sets
![screenshot from 2018-03-01 09-18-54](https://user-images.githubusercontent.com/7221078/36849287-a1239450-1d31-11e8-95f7-bf91308bf5c1.png)

I'm just wondering if there is any way to solve this issue.
It not just related with Chrome version as someone posted here, because it also happen on remote
client.. (I'm running jupyterlab on server)

Currently, I even don't know what information need to be provided to solve this issue,
So I will be really appreciate if you gen provide me any advice or solution.

Thank you!

**Comment by blink1073** [comment]
Hi @dvm-shlee, this issue is resolved by https://github.com/jupyterlab/jupyterlab/pull/3914 and will be fixed in the 0.32 release.

**Comment by dvm-shlee** [comment]
Thank you so much about your fast reply and resolving it! I will close this issue then.
