### ISSUE TITLE
Can you map all (or multiple) cells to a single output view?

### ISSUE THREAD

**Issue by ian-whitestone** [jupyterlab/jupyterlab#4078]
This may end up being a feature request rather than a question.

I find notebooks get really messy without active maintenance. Lots of the time I just want to print out a variable or dataframe, and then I don't need to look at it again. This is one of the things I really like about the R-studio workflow.

I know you can link a notebook to a console, but then it still prints the output in both places. Maybe it would be easier to suppress the output in the notebook?

**Comment by jasongrout** [comment]
If you link the notebook to a console, then print out the dataframe in the console, it won't show up in the notebook. It only shows up in both places if you print it in the notebook.

**Comment by ian-whitestone** [comment]
Thanks for the quick response. That makes more sense.
