### ISSUE TITLE
IRkernel Notebook Syntax Highlighting not Working

### ISSUE THREAD

**Issue by ctm22396** [jupyterlab/jupyterlab#4081]
Hello,

The syntax highlighting seems to be broken in then jupyterlab notebook running IRkenel. However, when the notebook is exported, the highlighting works just fine. Here are some screenshots: 
![image](https://user-images.githubusercontent.com/16002036/36860045-4d94375a-1d4e-11e8-8664-f7eec7a573a5.png)

![image](https://user-images.githubusercontent.com/16002036/36860062-5be2ac06-1d4e-11e8-87ea-6e2d17126157.png)

**Comment by blink1073** [comment]
I see the same behavior in the classic notebook.  I think this is a matter of `nbconvert` using `pygments` while the front-ends are using `CodeMirror` for syntax highlighting.

**Comment by ctm22396** [comment]
Ah okay, so would this be something that would have to be fixed in the IRkernel repo?

**Comment by ctm22396** [comment]
Ah okay, thanks you. Luckily it’s not too hard to customize.
