### ISSUE TITLE
[Feature Request] Launching multiple jupyterlab instances that don't interfere

### ISSUE THREAD

**Issue by madcarrot** [jupyterlab/jupyterlab#4088]
I usually work on multiple projects at once and don't want the tabs of different group of files mixed together... Also it's hard to manage when I have like 20 tabs open in the same window about different things lol

Is there a way to get a different set of tabs in each browser window (instance) of jupyterlab?

**Comment by blink1073** [comment]
Hi @madcarrot, this will be addressed by #4041.

**Comment by madcarrot** [comment]
Verified that it's working in v0.31.22 !
