### ISSUE TITLE
Some keyboard shortcuts are missing in Keyboard Shortcuts Setting

### ISSUE THREAD

**Issue by pharrellyhy** [jupyterlab/jupyterlab#4089]
I found some shortcuts that defined in Commands in left area are missing when I tried to modify them in shortcut setting, e.g., toggle cell output, clear cell output. Is it a way to add those shortcuts? Enlighten me if I miss something. Thanks.

**Comment by ian-r-rose** [comment]
Hi @pharrellyhy, I'm unsure which keyboard shortcuts you are referring to (I don't see `Toggle Cell Output` or `Clear Cell Output` in the command palette, with or without keyboard shortcuts). Can you be more specific?

**Comment by pharrellyhy** [comment]
Hi @ian-r-rose, I'd like to know how to add shortcuts for below commands.
<img width="297" alt="screen shot 2018-03-03 at 12 47 19 am" src="https://user-images.githubusercontent.com/16664753/36910789-a89b41be-1e7c-11e8-8d53-56d7752e28b9.png">
By the way, is there a way to edit the shortcuts for Text Editor Key Map? Thanks.

**Comment by ian-r-rose** [comment]
You will need to follow the same pattern that is used for the other keyboard shortcuts, but use the string command ID for those specific commands. These IDs can be found in the `notebook-extension` package [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook-extension/src/index.ts#L224)

**Comment by pharrellyhy** [comment]
I see...  Thank you. I will close this thread.

**Comment by pharrellyhy** [comment]
Hi @ian-r-rose, I used the below code to try to hide/show cell **outputs**. 
<img width="351" alt="screen shot 2018-03-04 at 3 04 10 pm" src="https://user-images.githubusercontent.com/16664753/36943075-855b3d20-1fbd-11e8-85df-577e608c218b.png">
But these commands hide/show cell **code** instead of the output.

**Comment by pharrellyhy** [comment]
Hi @ian-r-rose, it seems working. Thank you.
