### ISSUE TITLE
No UI Indication of Button Press

### ISSUE THREAD

**Issue by cancan101** [jupyterlab/jupyterlab#4094]
e.g. here on tool bar:
![image](https://user-images.githubusercontent.com/51059/36922749-09ec96c0-1e37-11e8-9b10-31518b312b87.png)
and here on reset button:
![image](https://user-images.githubusercontent.com/51059/36922784-22e21ea2-1e37-11e8-937b-e54be8aad92e.png)

**Comment by jasongrout** [comment]
This has bothered me as well. Thanks for filing an issue!
