### ISSUE TITLE
Edit meta-data to suppress code input and cell numbers for reveal.js

### ISSUE THREAD

**Issue by SimonEnsemble** [jupyterlab/jupyterlab#4100]
Would be great to edit the cell meta-data to control, for each individual cell, whether upon generation of reveal.js slides:
* cell numbers are shown
* input code to generate the output is shown. (Collapse selected code does not hide input code in the presentation)

For example, I want to embed a YouTube video in my presentation but it has to show this code to do so:
```
from IPython.display import YouTubeVideo
# a talk about IPython at Sage Days at U. Washington, Seattle.
# Video credit: William Stein.
YouTubeVideo('1j_HxD4iLn8')
```

**Comment by saulshanabrook** [comment]
You can edit the cell metadata in the Cell Tools inspector:
<img width="839" alt="screen shot 2018-03-06 at 12 44 18 pm" src="https://user-images.githubusercontent.com/1186124/37048553-3525e028-213c-11e8-83e7-2760446eab95.png">

Does this suffice?

**Comment by SimonEnsemble** [comment]
@saulshanabrook could you please point me to documentation of what kind of attributes I can add? Particularly, how to suppress the input code and show only the output of the code, and to hide the numbers? Thanks.

**Comment by saulshanabrook** [comment]
@SimonEnsemble I don't think that's possible at the moment. AFAIK, we use nbconvert to produce the reveal.js slides. [Their slide template](https://github.com/jupyter/nbconvert/blob/master/nbconvert/templates/html/slides_reveal.tpl#L1:14) and [their base template](https://github.com/jupyter/nbconvert/blob/master/nbconvert/templates/html/basic.tpl) don't seem to include any options for hiding output based on the metadata or toggling line numbers.

**Comment by mpacer** [comment]
The options to do so are not based in the specific templates, but are based in the exporters and the skeleton template. That said, looking at the templates is a bad approach to finding nbconvert features, as there may be many layers that you need to search to find these features. 

Right now, you would need to add tags to your cells, and then update your jupyter_nbconvert_config to include whatever those tags are in `TagRemovePreprocessor.remove_input_tags` so that they woudl be removed. You can read more about it in [nbconvert 5.3.0 — now with tag-based element filtering!](https://groups.google.com/forum/#!topic/jupyter/W2M_nLbboj4). 

There currently is no way to hide the prompt numbers for only some cells (no one had actually asked for that feature), and so you would need to disable them globally for your nbconvert call with the `--no-prompt` flag. In a configuration file you be able to separately set input and output prompt hiding, with either `TemplateExporter.exclude_input_prompt=True` or `TemplateExporter.exclude_output_prompt=True`. 

However, if you're going to be converting through the notebook interface, there's currently no way to pass this kind of configuration through to nbconvert, so you'll need to run it via the terminal.  https://github.com/jupyter/notebook/pull/2413 fixes that issue, by adding a way to pass a JSON config file to the nbconvert call, but that will require a jupyterlab implementation after that PR has been merged. If you want to see this happen, please get on that PR and say so to demonstrate that this feature is in demand.

**Comment by SimonEnsemble** [comment]
@mpacer 
Awesome! `--no-prompt` should be default behavior IMO!

In Jupyter Lab, I change meta-data to:
```
{
    "slideshow": {
        "slide_type": "fragment"
    },
    "tags": [
        "to_remove"
    ]
}
```
which I presume adds the tag?
Then, unfortunately, 
```
jupyter nbconvert presentation.ipynb --to slides --no-prompt RemoveElements --TagRemovePreprocessor.remove_single_output_tags={\"to_remove\"} --post serve --SlidesExporter.reveal_theme=simple
```
does not remove the output. :frowning_face:

**Comment by mpacer** [comment]
You can't do that for `remove_single_ouptut_tags` you would need to do it on `remove_all_outputs`. 

The `remove_single_output_tags` as it is not able to be set at the cell level, it's more complicated. To do that you need to attach tags and the value to your the display object metadata level. If you aren't attaching metadata to your outputs, you won't be able to use the `remove_single_ouptut_tags` feature.

For an example you can look at that post on how to add single output metadata:

> jupyter nbconvert RemoveElements --to markdown && cat RemoveElements.md
> we'd see 
> ```python
> display("hello", metadata={"tags":["to_remove"]})
> display("goodbye", metadata={})
> ```
>     'hello'
>
>
>
>     'goodbye'
>
> versus 
> 
> `jupyter nbconvert RemoveElements --to markdown --TagRemovePreprocessor.remove_single_output_tags={\"to_remove\"} && cat RemoveElements.md`
> ```python
> display("hello", metadata={"tags":["to_remove"]})
> display("goodbye", metadata={})
> ```
>     'goodbye'

Note the calls to display. 


But, in any case, i thought you wanted to hide input. so you can use the `remove_input_tags` value like I gave in my above response and that will work with cell level tags.

**Comment by SimonEnsemble** [comment]
:fireworks:
Thank you!

For others, in summary, to hide the input code and show only the output for *particular* cells in the reveal.js slides:
change the meta-data for the particular cell in Jupyter Lab in the "Cell Tools" tab to:
```
{
    "tags": [
        "to_remove"
    ],
    "slideshow": {
        "slide_type": "fragment"
    }
}
```
then run `nbconvert` in the terminal with:
```
jupyter nbconvert presentation.ipynb --to slides --no-prompt RemoveElements --TagRemovePreprocessor.remove_input_tags={\"to_remove\"} --post serve --SlidesExporter.reveal_theme=simple
```
emphasis on `RemoveElements --TagRemovePreprocessor.remove_input_tags={\"to_remove\"}` to look at cells with `"to_remove"` in their meta-data and hide its input code in the presentation.

And `--no-prompt` flag removes numbers on cells, making for a clean presentation!

**Comment by mpacer** [comment]
@SimonEnsemble Why did you add `RemoveElements`? that isn't doing anything as far as I can tell. `--no-prompt is a flag and I'd have thought it would err if you tried to pass arguments to it…

**Comment by SimonEnsemble** [comment]
@mpacer woops, removed in my post. Thanks.

**Comment by mpacer** [comment]
Also @SimonEnsemble I would create a static config file rather than using command line arguments, it's much cleaner syntax, enables more features and 

so in this case it'd be a python file `my_slide_config.py` with the value

```python
# `my_slide_config.py` 
c.TagRemovePreprocessor.remove_input_tags.append("to_remove")
c.SlidesExporter.reveal_theme="simple"

# the following does the equivalent of --to slides and --post serve, see here: https://github.com/jupyter/nbconvert/blob/master/setup.py#L220 + https://github.com/jupyter/nbconvert/blob/master/nbconvert/nbconvertapp.py#L482 and here https://github.com/jupyter/nbconvert/blob/master/nbconvert/nbconvertapp.py#L238
app_settings = {"postprocessor_class": "nbconvert.postprocessors.serve.ServePostProcessor",
                           "export_format": "slides"}
c.NbConvertApp.update(app_settings)

# the following does the equivalent of --no-prompt, see here: https://github.com/jupyter/nbconvert/blob/master/nbconvert/nbconvertapp.py#L109-L114
exporter_settings = {
            'exclude_input_prompt' : True,
            'exclude_output_prompt' : True,
            }
c.TemplateExporter.update(exporter_settings)
```

and then you could run a much simpler command

```
jupyter nbconvert presentation.ipynb --config my_slide_config.py
```

And you wouldn't need to type that out every time.

**Comment by mpacer** [comment]
Or, @SimonEnsemble if you wanted to have it as a json config file (so it's slightly more portable and safer to use, but less feature rich) you could have `my_slide_config.json`

```json
{
  "TagRemovePreprocessor": {"remove_input_tags": "to_remove"},
  "SlidesExporter": {"reveal_theme": "simple"},
  "NbConvertApp": {
     "postprocessor_class": "nbconvert.postprocessors.serve.ServePostProcessor",
     "export_format": "slides"
  },
  "TemplateExporter":{
    "exclude_input_prompt": true,
    "exclude_output_prompt": true
  }
}
```

**Comment by damianavila** [comment]
Great stuff people, we should try to document this in nbconvert (in the slide section), maybe?

**Comment by kuchaale** [comment]
I received the following error (see the figure attached). I followed the approach suggested adobe.
![image](https://user-images.githubusercontent.com/6815953/37210685-e625c680-23a9-11e8-9e20-fb69b3dc1b5e.png)

**Comment by rajeshgautamphd** [comment]
I also got the same error, what's the resolution?
traitlets.traitlets.TraitError: The 'remove_input_tags' trait of a TagRemovePreprocessor instance must be a set, but a value of type 'unicode' (i.e. u'to_remove') was specified.

**Comment by rafarui** [comment]
I know this is old, but...

@mpacer, I do not know if something has changed, but to be able to make it work I used

`c.TagRemovePreprocessor.remove_input_tags.add("to_remove")` instead of `c.TagRemovePreprocessor.remove_input_tags.append("to_remove")`


```python
# `my_slide_config.py` 
c.TagRemovePreprocessor.remove_input_tags.add("to_remove")
c.SlidesExporter.reveal_theme="simple"

# the following does the equivalent of --to slides and --post serve, see here: https://github.com/jupyter/nbconvert/blob/master/setup.py#L220 + https://github.com/jupyter/nbconvert/blob/master/nbconvert/nbconvertapp.py#L482 and here https://github.com/jupyter/nbconvert/blob/master/nbconvert/nbconvertapp.py#L238
app_settings = {
    "postprocessor_class": "nbconvert.postprocessors.serve.ServePostProcessor",
    "export_format": "slides"
}
c.NbConvertApp.update(app_settings)

# the following does the equivalent of --no-prompt, see here: https://github.com/jupyter/nbconvert/blob/master/nbconvert/nbconvertapp.py#L109-L114
exporter_settings = {
    'exclude_input_prompt' : True,
    'exclude_output_prompt' : True,
}
c.TemplateExporter.update(exporter_settings)
```

**Comment by shriv** [comment]
@SimonEnsemble and others! 
Thanks for the solution - however, I'm finding that the exported slides are blanks for the removed cells. I should add that I'm trying to couple of things together:
- Remove certain cells from the presentation
- Remove code cells (from [here](http://www.damian.oquanta.info/posts/hide-the-input-cells-from-your-ipython-slides.html) )

My config file
`{
    "TagRemovePreprocessor": {"remove_input_tags": ["tech"],
			      "remove_all_outputs_tags": ["tech"]},
    "template": "slides_template.tpl",
    "NbConvertApp": {
	"postprocessor_class": "nbconvert.postprocessors.serve.ServePostProcessor",
	"export_format": "slides"
  },
    "TemplateExporter":{
	"exclude_input_prompt": true,
	"exclude_output_prompt": true
  }
}
`
My slides_template.tpl is:
`
{%- extends 'slides_reveal.tpl' -%}
{%- block header -%}
    {{ super() }}
    <style type="text/css">
    //div.output_wrapper {
    //  margin-top: 0px;
    //}
    .input_hidden {
    display: none;
    //  margin-top: 5px;
    }   
    </style>
{%- endblock header -%}
`

**Comment by WingTillDie** [comment]
If you want to keep same naming convention as [nbextensions.tpl](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/exporting.html#nbextensions-tpl), refer following configuration:
  
In ~/.jupyter/jupyter_nbconvert_config.py:
```python
c=get_config()
c.TagRemovePreprocessor.remove_input_tags={"hide_input"}
c.TagRemovePreprocessor.remove_all_outputs_tags={"hide_output"}
c.TagRemovePreprocessor.remove_cell_tags={"hidden"}
```
