### ISSUE TITLE
Editor config overrides cause cursor to disappear

### ISSUE THREAD

**Issue by black-puppydog** [jupyterlab/jupyterlab#4101]
This seems to be different from #4030, which only concernt dark theme problems.
I installed the conda-forge version of jupyterlab when the beta went public (or rather when I read of it on HN) so that would be like 2 weeks ago(?).

It worked really great, until one day the cursor disappeared, regardless of theme, browser, machine and (client) OS.

I just updated a few minutes ago to verify that this wasn't fixed with #4030 for me.

`jupyterlab: 0.31.8-py36_1 conda-forge --> 0.31.10-py36_1 conda-forge`

Are there any chaches I could clear or such?

Edit
to clarify: the text editor *does* work, both with vim and default keybindings.
But **the cursor is invisible, except for when selecting text** (by mouse or via visual mode for vim).
The notebooks are perfectly fine (with default keymap).

**Comment by klonuo** [comment]
Same here with both 0.31.8 and same issue again with 0.31.10

**Comment by klonuo** [comment]
This happens in Chrome, but not in Firefox - in Firefox I can see the cursor.
Running latest versions of both browsers.

**Comment by black-puppydog** [comment]
For me it seems to be every browser.
So far, I've tried:

* Firefox `58.0.2 (64-bit)` **Ubuntu 16.04**
* Firefox (unknown version, will look up when back at home) **Debian**
* Chrome `Version 64.0.3282.186 (Official Build) (64-bit)` **Ubuntu 16.04**
* Chrome (unknown but recent version) **MacOS**
* qutebrowser (just for fun, really) latest git **Ubuntu 16.04**
* Chromium `Version 64.0.3282.167 (Official Build)  (64-bit)` **Ubuntu 16.04**

**Comment by klonuo** [comment]
I'm on Windows 10
Firefox 58.0.2
Chrome 64.0.3282.186

This happens on my laptop, but not on my desktop (same OS and version of browsers and jupyterlab), only difference I can think of (thou it does not make sense for this issue) is that I run Python 3.6 on laptop and Python 3.5 on desktop.

**Comment by ian-r-rose** [comment]
@black-puppydog, @klonuo Does this happen at every zoom level? That is, if you experiment with zooming in and out, does the cursor ever appear?

**Comment by klonuo** [comment]
I launched now jupyterlab to test at different zoom levels, but now I can see the cursor, for the first time, for whatever reason, great :)

Between yesterday and today, I installed github extension, if that could have changed anything...

**Comment by ian-r-rose** [comment]
Glad to hear it @klonuo. It's possible that the extension install pulled in a patched version of a JupyterLab package that was missing in your previous build.

**Comment by klonuo** [comment]
I did check that. File `c:\Python36\share\jupyter\lab\staging\node_modules\@jupyterlab\codemirror\style\index.css` is w/o your patch.
I applied the patch yesterday w/o success.

**Comment by black-puppydog** [comment]
No luck for me, neither chrome nor firefox nor chromium.
I did a Ctrl-F5 refresh after resetting the zoom level in each, that should have done it, no?

**Comment by dlukes** [comment]
I think it may be connected to settings customization. Or at least in my case it is. If I open the advanced settings editor (`Ctrl-,`) and put the following in *User Overrides* under *Text Editor*...

```json
{
    "editorConfig": {
        
    }
}
```

... my cursor disappears. This happens irrespective of keymap, i.e. even Vim mode's fat cursor disappears.

**Comment by black-puppydog** [comment]
wow, indeed. I had overwritten my editor config like this:

```json
{    
    "editorConfig": {
      "tabSize": 2
    }
}
```

simply replacing it with the empty `{}` solved the issue.
I'm renaming this issue to a more informative title...

**Comment by black-puppydog** [comment]
So now I have...

* reset the editorConfig
* opened a file in the editor
* select `Settings > Text Editor Indentation > Spaces: 2`
* restarted then lab

This left me with this config override:

```json
{"editorConfig":{"lineNumbers":true,"lineWrap":true,"readOnly":false,"tabSize":2,"insertSpaces":true,"matchBrackets":true,"autoClosingBrackets":true}}
```

and the cursor is still there.

**Comment by black-puppydog** [comment]
wow, that was quick! thanks so much! :tada:

**Comment by slowkow** [comment]
For me, the cursor is invisible in the file editor.

I'm using macOS 10.13.3 and Chrome 65.0.3325.181

Python3 packages:

```
ipython-6.3.1 jupyterlab-0.31.12 tornado-5.0.2
```

My `editorConfig` is empty `{}`.

Could I ask if anyone has any advice to get the cursor displayed? It is very difficult to edit files when I can't see the cursor.

**Comment by jasongrout** [comment]
FYI, we are trying to release a new version this week

**Comment by yalaudah** [comment]
Hey guys, I'm on the latest version 0.32.1 and I still have the same problem with the cursor not visible in the dark mode. Did #4158 make it into the latest release?

**Comment by ian-r-rose** [comment]
Hi @yalaudah , looks like we had a style regression here. I just opened #4699 to fix it. Thanks for the report!
