### ISSUE TITLE
Add wordwrapping in the Inspector

### ISSUE THREAD

**Issue by s-weigand** [jupyterlab/jupyterlab#4102]
Hi folks,

I discovered today that the Inspector lacks a wordwrapping, which results in the Signature being a single line.
So normally one would see only a part for long Sinatures:
![inspector_small](https://user-images.githubusercontent.com/9513634/36948034-b9518d20-1fd4-11e8-9667-d78ca4ee3fc5.jpg)

To see the whole Signature, one could expand the Inpector pane if the monitor is big enought:
![inspector_big](https://user-images.githubusercontent.com/9513634/36948038-c7685e20-1fd4-11e8-9e0a-7df7ff018d46.jpg)

Or use the horizontal scrollbar:
![inspector_scroll](https://user-images.githubusercontent.com/9513634/36948086-a83f3748-1fd5-11e8-8239-75105085ff2a.jpg)

Which both isn't pretty.

By adding ``white-space: pre-wrap;`` to `packages/inspector/style/index.css` for ``.jp-InspectorItem pre``, one would get this result:
![inspector_fix](https://user-images.githubusercontent.com/9513634/36948113-e8e9290c-1fd5-11e8-91cd-b8e9f7d97fe0.jpg)

If you are fine with this fix, I could do a PR for that.

Jupyterlab version: 0.31.10

**Comment by ian-r-rose** [comment]
Hi @s-weigand, PRs welcome!

**Comment by vidartf** [comment]
Closed by #4105?

**Comment by blink1073** [comment]
Yep!
