### ISSUE TITLE
Informative collapsed code block

### ISSUE THREAD

**Issue by klonuo** [jupyterlab/jupyterlab#4103]
Hi,

can we please have first line in code block printed next to `...` when code block is collapsed?

Thanks

**Comment by ellisonbg** [comment]
We have another issue related to this, but I can't find it right now.

The usage case the current UI is optimized for is when you want to completely hide an input cell (think of presenting a notebook to non-technical users, showing just the markdown + plots). You bring up another, equally important, usage case. My current thought right now is that the two usage cases are different enough we would probably design them separately. But your point is a good one and we will need to figure out how to address both of these things.

**Comment by JasonWeill** [comment]
Fixed by @marthacryan in #14141.
