### ISSUE TITLE
pipe operator (%>%) shortcut doesn't work in jupyterlab

### ISSUE THREAD

**Issue by jeonghyunwoo** [jupyterlab/jupyterlab#4109]
pipe operator(%>%) works when 'ctrl + shift + M' in **jupyter notebook**
But, in **jupyterlab**, 'ctrl + shift + M' invokes chrome 'login' popup

**Comment by flying-sheep** [comment]
I implemented that in [IRkernel’s kernel.js](https://github.com/IRkernel/IRkernel/blob/dfa7f4ef2c855d289df451cb8af18b3fd0c96fda/inst/kernelspec/kernel.js)

With the new JS API it needs to be done in a different way. I’d be glad about pointers in that direction!

**Comment by stevenveenma** [comment]
This behaviour still occurs both on chrome and MS Edge. This is quite annoying. Apparantly no solution until so far. Is a workaround available (besides just typing the characters?)

**Comment by jasongrout** [comment]
See https://github.com/jupyterlab/jupyterlab/issues/4519 for a way to do this (and a simple change to jlab that needs to happen to make this easy - PRs welcome!).

**Comment by smartinsightsfromdata** [comment]
@jasongrout it would be nice see this fixed in a stable & sensible way. 

All IDEs allow to customise *easily* keyboard shortcuts.

The absence of a customiseable shortcut for `<-` and %>% is a put off for R users.

In my humple view a way to achieve this `should be offered in jpyterlab`, not pushed down to be add-ons implementers responsibility.

**Comment by jasongrout** [comment]
I think maybe there is a misunderstanding. I'm proposing what we offer in core JupyterLab (see https://github.com/jupyterlab/jupyterlab/issues/4519) is a way for any user to customize a keyboard shortcut to insert any text they want.

**Comment by smartinsightsfromdata** [comment]
Apologies for any misunderstanding from my part!

**Comment by jasongrout** [comment]
JLab 2 offers a way for a user to customize the keyboard shortcuts to insert any text they like into editors: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#user-facing-changes
