### ISSUE TITLE
Jupyterlab kills opencv

### ISSUE THREAD

**Issue by mhechthz** [jupyterlab/jupyterlab#4112]
Hi,

I run anaconda python 3 64-bit with menpo opencv.

After installing jupyterlab, opencv is missing it's main dll. Uninstalling jupyterlab doesn't repair this. Reinstalling opencv neither. So I have to clean install anaconda!!!

What's wrong?

**Comment by blink1073** [comment]
Hi @mhechthz, I don't know how this package could interfere with another package's dlls.  We don't touch the system library.  Perhaps try asking on https://github.com/ContinuumIO/anaconda-issues?

**Comment by mhechthz** [comment]
Hmmm ... but it is definitely reproducible with jupyter-lab ... there is a lot of packages installed for jupyter-lab, so maybe one (or more) is not compatible with opencv ...

By the way, I don't mean a "system library" but the library for opencv,or a path or something like this ...

**Comment by blink1073** [comment]
Ah, I see what you mean about dependencies possibly being an issue.  Does installing `notebook` cause the same issue?

**Comment by mhechthz** [comment]
It seems that the issue is solved for me. I installed now opencv via conda-forge. This was ok, i.e. without any problems. The package from menpo, that was installed before, seems to be buggy. 

So yes, it is not a problem of jupyterlab :-) 

Thank you for this "hint".

**Comment by blink1073** [comment]
Cheers!
