### ISSUE TITLE
Conda Env Kernels Can't Be Read 

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#4118]
I'm guessing ipykenrels parses all the conda environments as named `Python [conda env:foo]` but this means I can't read the name of the kernel
![screen shot 2018-03-05 at 12 25 44](https://user-images.githubusercontent.com/1373035/36989699-73f56d2c-2070-11e8-86b1-0d64cdb907cd.png)

**Comment by jzf2101** [comment]
@damianavila says this is a  https://github.com/Anaconda-Platform/nb_conda_kernels issue

**Comment by damianavila** [comment]
Well technically it is not (although that can be discussed) :wink: but I thought jupyterlab was able to show large names in the icons... am I missing something @blink1073?

**Comment by blink1073** [comment]
We display only one line but offer the rest as a tooltip.  Closing to move conversation to https://github.com/jupyterlab/jupyterlab/issues/3795.
