### ISSUE TITLE
Click Notebook Name to Rename Notebook?

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#4119]
The classic notebook has it and we currently don't

**Comment by jasongrout** [comment]
> we double-click the name in the file explorer.

At one point, we had this, but it seemed to be triggered by accident way too often, so now it is a right-click menu on a filename. VSCode has it where you can press enter to rename the file, which also seems like a nice way to do it.


> double-click the tab name

I would like to have this as well. It may be not quite straightforward with our current system (we already have to do some extra things to get a correct context menu on the tab).

**Comment by jtpio** [comment]
For reference renaming is possible in Simple Mode:

https://user-images.githubusercontent.com/591645/157901919-5b8af30c-332a-48a8-8838-432ec35bfd3f.mp4

**Comment by afshin** [comment]
Since the analogue of this behavior in JupyterLab is simple mode, I think we can consider this feature parity bug resolved. Please feel free to re-open if there is more to discuss.
