### ISSUE TITLE
Rendering of Plots is Blurry?

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#4120]
Screenshot example:

![screen shot 2018-03-05 at 14 46 33](https://user-images.githubusercontent.com/1373035/36996202-2d8a7ddc-2084-11e8-8a68-ded33ed0a4ed.png)

**Comment by TariqAHassan** [comment]
I know something like `%config InlineBackend.figure_format = 'retina'` will fix this problem, as you are no doubt aware. However, it would be be nice if this was enabled by default.

**Comment by dbk123** [comment]
I think so.
