### ISSUE TITLE
Running jupyterlab from a docker container in a remote server

### ISSUE THREAD

**Issue by seansaito** [jupyterlab/jupyterlab#4122]
I'm trying to run jupyterlab from a docker container on a remote server. The following command works fine:

```
root@5ddade68a5f2:/# jupyter lab --no-browser --ip=0.0.0.0 --allow-root
```

```
[I 09:53:40.629 LabApp] JupyterLab beta preview extension loaded from /usr/local/lib/python2.7/dist-packages/jupyterlab
[I 09:53:40.629 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 09:53:40.634 LabApp] Serving notebooks from local directory: /
[I 09:53:40.634 LabApp] 0 active kernels
[I 09:53:40.634 LabApp] The Jupyter Notebook is running at:
```

Port 8888 in the container is exposed to the server, which I'm forwarding to my local machine. However, when I point to the local port I see the old jupyter notebook UI, not that of jupyterlab. Not sure what's wrong here.

**Comment by blink1073** [comment]
As in, when you load the base url, it goes to `/tree`?  Does it work if you manually change `/tree` to `/lab`?

**Comment by seansaito** [comment]
Ah, pointing to `/lab` directs me to the Lab UI.
