### ISSUE TITLE
Install and run Jupyter Lab from a corporate proxy 

### ISSUE THREAD

**Issue by zizzipupp** [jupyterlab/jupyterlab#4123]
I can't get Jupyter Lab to launch in my Windows 10 Enterprise 64-bit Company laptop. I believe they use a corporate proxy. I am looking for the equivalent of:

`pip install --trusted-host pypi.python.org JupyterLab`

for `conda`.

If I run:

`conda install -c conda-forge jupyterlab` from the Anaconda prompt, I get:
```
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/pro/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.continuum.io\', port=443): Max retries exceeded with url: /pkgs/pro/win-64/repodata.json.bz2 (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')],)",),))',),)
```

**Comment by blink1073** [comment]
Hi @zizzipupp, I believe this guide should work: https://conda.io/docs/user-guide/configuration/use-winxp-with-proxy.html.

**Comment by saulshanabrook** [comment]
Closing this for now. Feel free to comment if you have further issues after following that guide.

**Comment by shinta4ever** [comment]
Page doesn't exist anymore.

**Comment by saulshanabrook** [comment]
@shinta4ever I think this is the same page: https://github.com/conda/site/blob/d4629b6de5b98a5e95245f10d0e801a71b382407/source/winxp-proxy.rst
