### ISSUE TITLE
Close tabs to the right/others

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterlab/jupyterlab#4124]
Thanks everyone for your awesome work on this project!

It would be great to be able to right click on a tab and choose options to bulk close other tabs like "close tabs to the right" and "close others". 

I am used to this functionality in other tab based applications like Chrome, Firefox, VS Code, Atom, etc and it feels a little frustrating to not have it in JupyterLab.

**Comment by AK-ayush** [comment]
Hi @jacobtomlinson I would like to work on this issue. Please provide me any additional details required to complete this task since I am new here.

**Comment by agoose77** [comment]
Just chiming in here, I think this would be a useful feature. 

In terms of user requirements, I think formally the following features are useful:

1. Close other tabs
2. Close tabs to the right

These should be seen when right-clicking any tab (not just the active tab)

Option 1. should close every tab but for the tab which was right-clicked upon. 
Option 2. should close all tabs to the right of the tab which was right-clicked upon.

**Comment by jacobtomlinson** [comment]
Yup that's what I'm after!

**Comment by ian-r-rose** [comment]
Fixed by #677
