### ISSUE TITLE
Latex in markdown cells sometimes rendered as markdown

### ISSUE THREAD

**Issue by lucainnocenti** [jupyterlab/jupyterlab#4128]
This is similar to https://github.com/ipython/ipython/issues/1275/. The issue has been solved for the classical notebook but seems to have somewhat returned in jupyter lab.

Sometimes writing latex code triggers markdown parsing. See the following example:

![screenshot from 2018-03-06 18-54-30](https://user-images.githubusercontent.com/10957113/37052092-29e3ecd0-2170-11e8-8982-be1dc1a57729.png)

The same string works fine in the classical notebook. Also the problem doesn't occur if using inline math ($) instead of display math ($$). 

On a related note, latex highlighting is also not triggered when using $$ wrappers. `\\[` and `\\]` work fine.

**Comment by saulshanabrook** [comment]
This works for me now on master. 

![screen shot 2018-05-08 at 10 40 33 am](https://user-images.githubusercontent.com/1186124/39763858-3f2bb362-52ac-11e8-961c-c849fb4dae2c.png)


Feel free to comment if there are still issues.
