### ISSUE TITLE
Plotly extension error

### ISSUE THREAD

**Issue by bluprince13** [jupyterlab/jupyterlab#4131]
`jupyter labextension install @jupyterlab/plotly-extension`

fails with the following error

```
warning @jupyterlab/plotly-extension > plotly.js > ndarray-fill > cwise > static-module > through2 > xtend > object-keys@0.4.0:
error Couldn't find match for "83b1a3e5837d785af582efd5ed1a212f2df6a4ae" in "_c for "https://github.com/mapbox/mapbox-gl-style-spec.git".
```

**Comment by blink1073** [comment]
Hi @bluprince13, do you have `git` installed locally?  I believe the plotly extension indirectly requires it.

**Comment by bluprince13** [comment]
Yes, I do have git installed on my computer.

**Comment by bluprince13** [comment]
However, since you mentioned that git could be causing the issue, I thought I'd investigate...

I tried git clone a github repository and got this error:
`fatal: unable to access 'https://github.com/repository.git/': Couldn't connect to server`

Turns out my company's proxy was blocking git, so I tried:
`git config --global http.proxy http://proxy.mycompany:80` 
which is some advice I got from [here](https://stackoverflow.com/questions/128035/how-do-i-pull-from-a-git-repository-through-an-http-proxy).

I then tried installing the labextension again and it worked!! So, thanks for pointing me in the right direction.

**Comment by blink1073** [comment]
Cheers!
