### ISSUE TITLE
Having matplotlib figure create their own tab in Jupyterlab

### ISSUE THREAD

**Issue by RemiLehe** [jupyterlab/jupyterlab#4134]
Hi,

Would it be in theory possible to create a matplotlib backend such that matplotlib figure would appear in a separate tab (within the jupyterlab interface) instead of appearing inline in the notebook?

I'm thinking something like this:
<img width="1177" alt="screen shot 2018-03-06 at 8 23 04 pm" src="https://user-images.githubusercontent.com/6685781/37074365-48d92f40-2181-11e8-9c54-408bb96683f2.png">

This would be very useful e.g. in cases where a user wants to scroll from one part of the code in the notebook to another, but still wants to be able to see the plots at the same time.

Thanks!

**Comment by johncolby** [comment]
I would also appreciate this feature, for design reference similar to matlab or RStudio, et al.

![image](https://user-images.githubusercontent.com/473295/47946535-2fb5be00-deca-11e8-8dd7-85b150070e6a.png)
![image](https://user-images.githubusercontent.com/473295/47946537-36dccc00-deca-11e8-9560-6a9cc0acebc3.png)

**Comment by ian-r-rose** [comment]
Creating a new view for the figure output does something like this (you can find this by right-clicking on the output area). The notebook won't open it automatically, but once you open it, it should keep up to date when you re-run the cell. Or do you mean something different?

**Comment by johncolby** [comment]
nice I'll have to play with that when I have a chance. Is this issue already closed then?

**Comment by ian-r-rose** [comment]
I think so. @RemiLehe, if you meant something different, feel free to comment and we can reopen. Happy coding!
