### ISSUE TITLE
Open In Browser Option

### ISSUE THREAD

**Issue by cancan101** [jupyterlab/jupyterlab#4137]
I have an HTML page that I would like to open in a new browser tab. Right now the only options are to download or to view in lab:
![image](https://user-images.githubusercontent.com/51059/37108170-503bce36-2204-11e8-9f41-cc9ce80f8aa4.png)

Would be great to have an option to open in a new browser tab as:
`http://<host>/files/path/to/content.html`

**Comment by jtpio** [comment]
Something like this?

![new-tab](https://user-images.githubusercontent.com/591645/37437612-705bf1b0-27ee-11e8-9ad3-5c4bc2df19d2.gif)

The add icon (`jp-AddIcon`) is just a placeholder. It would probably be better to use something similar to the [font-awesome external-link-alt icon](https://fontawesome.com/icons/external-link-alt?style=solid)

**Comment by cancan101** [comment]
Yea that looks good!

**Comment by blink1073** [comment]
Fixed by #4315, thanks @jtpio!
