### ISSUE TITLE
Add setting to increase editor font size

### ISSUE THREAD

**Issue by adamjorr** [jupyterlab/jupyterlab#4139]
A text editor setting to increase the editor's font size without zooming the whole window or entering presentation mode would help reduce the strain on my eyes. Zooming the window works for now, but then the rest of the UI elements are huge. The current way theming works, creating a new theme just for editor font size seems like overkill for the average user.

**Comment by gsemet** [comment]
I agree. We can already increase the terminal font size, but not the text editor without using browser zoom

**Comment by OscarSouth** [comment]
Also here came looking for this

**Comment by jasongrout** [comment]
Bumping to beta 3 to see if we can tackle this before 1.0.

**Comment by ian-r-rose** [comment]
Fixed by #4673, thanks @AlbertHilb!
