### ISSUE TITLE
[Bug] Right click in the files tab doesn't work in the blank region

### ISSUE THREAD

**Issue by madcarrot** [jupyterlab/jupyterlab#4141]
It usually doesn't affect anything, but it made it impossible to paste file into an empty folder:
![image](https://user-images.githubusercontent.com/3460073/37127024-d2f42674-2241-11e8-9331-640360777462.png)

**Comment by jasongrout** [comment]
Thanks for reporting this. We're tracking this issue at https://github.com/jupyterlab/jupyterlab/issues/3602 - let's carry on the conversation over there.

**Comment by madcarrot** [comment]
Ah sorry I didn't see that issue earlier. Thanks!
