### ISSUE TITLE
Display math missing syntax highlighting

### ISSUE THREAD

**Issue by neighthan** [jupyterlab/jupyterlab#4142]
In a Markdown cell, when I use inline math, I get syntax highlighting, but this is missing when I use display math. Here's an example to reproduce:

```latex
$\max_i x_i$

$$\max_i x_i$$
```

Below is how this looks in my notebook in Jupyter Lab; note that `\max` is green in the inline math section but not in the display math one. This isn't a major concern for me, but if it's a small fix somewhere, it would be nice; not having the highlighting makes me worry that I've missed a $ somewhere.

![image](https://user-images.githubusercontent.com/12573501/37131781-209193f6-2258-11e8-900b-b5814f98fa3c.png)

**Comment by AlbertHilb** [comment]
This has been fixed by #4388.

**Comment by jasongrout** [comment]
Thanks!
