### ISSUE TITLE
Describe terminal copy/paste operation to windows user

### ISSUE THREAD

**Issue by gsemet** [jupyterlab/jupyterlab#4143]
Using the terminal under linux is pretty confortable, since copy/paste occurs moste of the time on text selection on double mouse.

I would suggest to indicate to users the generic copy/paste hotkey that nobody use but will work under windows:
- Cut: Shift + Delete
- Copy : Ctrl + Insert
- Paste: Shift + Insert

Ctrl+C for instance is reserved under linux for sigkill. Some browser extentions override Ctrl+Shift+C for instance.

**Comment by dhirschfeld** [comment]
xref: https://github.com/jupyterlab/jupyterlab/issues/3011#issuecomment-344646455

**Comment by cooknl** [comment]
@gsemet You just saved my bacon! That's exactly what I was looking for!

**Comment by saadkattan** [comment]
We are on it. 
@stefanwaterval @amyipliu @tamuish0506 @carl-mrhouse
