### ISSUE TITLE
Do not create .ipynb_checkpoints on text editor open

### ISSUE THREAD

**Issue by gsemet** [jupyterlab/jupyterlab#4147]
When the text editor file is opened on a text file in a folder for example, an `.ipynb_checkpoints` folder is sometime automatically created. Can we reduce the cases when this folder iscreated to only when a new notebook is created

**Comment by blink1073** [comment]
Hi @gsemet, we are creating a checkpoint for text files in that folder as well.

**Comment by gsemet** [comment]
Why is it needed? It can mess gitignore file for some project we only want to quickly edit from within the jupyter server.

**Comment by blink1073** [comment]
The checkpoints folder is used because we are auto-saving the file from the front end.  Explicit checkpoints allow you to roll back changes.  This is the same behavior as the classic notebook for notebooks, we extended it to all open files.

**Comment by thwee-alchemist** [comment]
Can you save the checkpoints in a central directory? Or provide an option to specify where checkpoints are stored, instead of littering working directories...

**Comment by JiaweiZhuang** [comment]
+1 on this...

**Comment by yaronha** [comment]
+1

**Comment by dsholes** [comment]
> Can you save the checkpoints in a central directory? Or provide an option to specify where checkpoints are stored, instead of littering working directories...

Or provide a way for users to select the file extensions for which they actually want to create checkpoints? I imagine the majority of users would prefer to use git to version control `.txt` and `.py` files.

**Comment by dsholes** [comment]
[Issue 5809](https://github.com/jupyterlab/jupyterlab/issues/5809) helped me with this issue.

It uses the central directory solution that @thwee-alchemist suggested.

From @ian-r-rose [answer](https://github.com/jupyterlab/jupyterlab/issues/5809#issuecomment-464510294):
> @SleepSux If you are adding it in your `jupyter_notebook_config.py`, you will need to dot into the config object, so I think you will want something like
> `c.FileCheckpoints.checkpoint_dir='/home/computer/Documents/myProjects/notebookCheckpoints'`

**Comment by gsemet** [comment]
#5809 did the job!

**Comment by jasongrout** [comment]
Nice solution. Thanks for following up here.
