### ISSUE TITLE
Make NPM registry configurable

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#4149]
Follow-up to #3608. The `_AppHandler.registry` should be configurable. This should allow for offline / firewalled deployments of JupyterLab by having it work against a local repository (at least it will be a step in the right direction), or simply allow people to use an alternative repo to `npmjs.org`.

**Comment by vidartf** [comment]
I think we should be getting this from the [yarn.rc](https://github.com/jupyterlab/jupyterlab/blob/3a77ad822b875fca569d6fc419378148ad561fe9/.yarnrc#L3)? See #3168.

Also c.f. #2065.

**Comment by fcollonval** [comment]
This is closed by #7109. The registry is overwritten by the registry specified in the yarn configuration.
