### ISSUE TITLE
optional "sidecar" phosphor panel display  for ipywidgets

### ISSUE THREAD

**Issue by paul-shannon** [jupyterlab/jupyterlab#4151]
I propose (that is, I request) a jupyterlab enhancement: the option to render an ipywidget into a new and separate phosphorjs panel. Notebooks currently render the ipywidget only into the output cell right below and associated with the originating code cell.  

phosphor apparently supports deferred movement to a new panel ([see stackoverflow discussion from 9/16](https://stackoverflow.com/questions/39676933/create-a-popup-widget-in-ipython)). 

But for user-friendly operation - some of my users are not coders at all - immediate display in a separate panel would be a real boon.   The new panel could be resized and positioned, perhaps into a central position,  for subsequent interaction, both programmatic (from subsequent code cells) and via mouse and keyboard.   Perhaps this option could be exposed by an extra, optional argument to the widget's constructor.

I predict that the ability to create widgets in their own phosphor panels will open up a variety of UX design possibilities, perhaps including dashboards and greater freedom to create "good enough" web apps.

A motivating use case for the ipywidget sidecar panel  is our work in genomics with [igv.js](https://github.com/igvteam/igv.js/tree/master), as pictured below.   igv enables interactive exploration of genome annotations and a wide variety of experimental data: copy number counts, mutations, sequence reads, transcription factor binding sites.   We build models, filter data, create and remove tracks,  change genomic locations - mostly with with the genome view at the center of our attention.  jupyterlab, with ipywidget sidecar panels, will be a fine way to deliver this capability to interested biologists.  A second image is included below, another candidate for a sidecar panel, illustrating the use of [cytoscape.js](http://js.cytoscape.org/) to explore the gene regulatory model constructed from the experimental data assembled in the igv widget.  Putative transcription factors (red) and suppressors (green), their binding sites, and the target gene are displayed.   Many models, based upon different assumptions, can be viewed in succession.

![image](https://user-images.githubusercontent.com/2480712/37166249-7195cb04-22b3-11e8-93df-af59f6d242dc.png)

![image](https://user-images.githubusercontent.com/2480712/37166764-d7b66410-22b4-11e8-978e-3a737c90300c.png)

**Comment by saulshanabrook** [comment]
The sidecar extension can help with this use case: https://github.com/jupyter-widgets/jupyterlab-sidecar. ALso see https://github.com/jupyterlab/jupyterlab/issues/3692 for more discussion on providing some functionality like this by default.
