### ISSUE TITLE
Setting to set output size default

### ISSUE THREAD

**Issue by JohnOmernik** [jupyterlab/jupyterlab#4152]
So on the output of a cell, there is collapsed, truncated, or full.  Right now, when I run something that displays a large Pandas Data frame etc, it seems to always default to full output.  What I would love to see is an option (maybe one already exists?) where the default output could be set to truncated, it would save me tons of scrolling on larger data sets.  Is this possible?

**Comment by siddharthasahu** [comment]
I think this is being discussed on https://github.com/jupyterlab/jupyterlab/issues/4028.

**Comment by saulshanabrook** [comment]
Closing this in favor of #4028
