### ISSUE TITLE
Ability to Reload Editor Contents from Disk

### ISSUE THREAD

**Issue by cancan101** [jupyterlab/jupyterlab#4154]
If the user knows that the contents of a file have changed externally and wants to cause the editor to reload contents from disk. Right now this can be accomplished by trying to save a modified buffer and choosing "revert".

**Comment by gsemet** [comment]
That would be cool indeed !

**Comment by ian-r-rose** [comment]
I think this is a good idea (and not just for editors). It should be possible to add a new command in `docmanager-extension` that calls `docmanager.revert()`, and add that to the file menu and the command palette.

Marking this as a good first issue.

**Comment by kcramer** [comment]
This enhancement looked straightforward so I made the change and submitted a PR for it: #4615.  There is an existing menu item Revert which is similar but calls restoreCheckpoint() and not just revert().  Is there any concern these two menu items could be confusing?

**Comment by ian-r-rose** [comment]
Fixed by #4615
