### ISSUE TITLE
Switching from external monitor to laptop screen produces incorrectly sized cells

### ISSUE THREAD

**Issue by mikeyford** [jupyterlab/jupyterlab#4156]
<img width="717" alt="screen shot 2018-03-08 at 20 31 18" src="https://user-images.githubusercontent.com/8105141/37174948-ee4274ac-230f-11e8-9673-0da5c2ca05ab.png">

Jupyter Lab Version 0.31.12
Browser: Chrome Version 64.0.3282.186 (64-bit) 
Mac OS 10.13.3
15" Macbook Pro 2017

Steps to reproduce:
Working on external monitor connected via HDMI and USB-C adapter, all cells are correctly sized and viewable. Pulling out the USB-C cable switches browser window with Jupyter Lab to laptop screen and produces wrongly sized cells in image above.

Plugging the monitor back in and viewing on the external screen, everything looks OK again. Keeping the monitor plugged in and switching the browser to the laptop screen by dragging it there produces the same issue.

Reopening the .ipynb file resolves the issue.

**Comment by saulshanabrook** [comment]
I can't reproduce this. 

Browser: Version 68.0.3418.2 (Official Build) dev (64-bit)
macOS 10.13.4
15" Macbook Pro 2016
Jupyterlab: master, after 0.32.0

Could you try to reproduce with 0.32.0?

**Comment by mikeyford** [comment]
This appears not to be happening anymore with the latest updates (of Chrome, OS and Jupyter Lab). Will close the issue.

**Comment by syuja** [comment]
Still an issue
Jupyterlab version: Version 0.35.6
Mac OS: 10.14.5
Chrome: 75.0.3770.100 (Official Build) (64-bit)
15" Macbook Pro 2014

Refreshing the page fixes the issue

**Comment by jasongrout** [comment]
The current version is 1.0.2 - can you try with that?

Likely this is not fixed yet. I think the big question is how to get a notification of this event in the browser.
