### ISSUE TITLE
Markdown not working

### ISSUE THREAD

**Issue by ramav87** [jupyterlab/jupyterlab#4160]
I am trying to do something very simple on jupyter lab, with markdown. I type

`Hi<sup>1,2,3</sup>` in the first cell and select it as "Markdown". But no superscript is generated upon cell execution. The same code works in the standard jupyter notebook. Here is what I see before execution

![sup code](https://user-images.githubusercontent.com/14301205/37223076-63ca2e44-239d-11e8-8228-3aeff02b665c.PNG)

and what I see after
![sup run](https://user-images.githubusercontent.com/14301205/37223080-66d8f3c2-239d-11e8-8d98-2c5f4c0a44a0.PNG)

and here is what I get with jupyter notebook in the same browser with the same code

![sup run notebook](https://user-images.githubusercontent.com/14301205/37223132-8de55d16-239d-11e8-9802-ded86b6c1a69.PNG)

**Comment by danpf** [comment]
see issue #1812 
markdown html is sanitized in jupyterlab :/

**Comment by ian-r-rose** [comment]
Fixed by #4618
