### ISSUE TITLE
Issue with JupyterLab Dark theme

### ISSUE THREAD

**Issue by hthummar30** [jupyterlab/jupyterlab#4163]
The dark theme of JupyterLab doesn't show axes and other details.
<img width="1045" alt="screen shot 2018-03-09 at 8 00 15 pm" src="https://user-images.githubusercontent.com/37233159/37238138-c5fab336-23d4-11e8-9085-5b286ee622e1.png">
<img width="1039" alt="screen shot 2018-03-09 at 8 00 02 pm" src="https://user-images.githubusercontent.com/37233159/37238139-c615791e-23d4-11e8-851c-a0fe34d7d8a8.png">

**Comment by timkpaine** [comment]
duplicate of #3912  #3922 #3855 #3886

**Comment by ian-r-rose** [comment]
Thanks for the report @hthummar30, as @timkpaine, can we continue the discussion for this issue on #3886?
