### ISSUE TITLE
PDF icon in filebrowser

### ISSUE THREAD

**Issue by timhoffm** [jupyterlab/jupyterlab#4175]
Since pdf is among the formats, for which we have an internal viewer. PDFs should get a distinct icon in the filebrowser. Currently, the generic file icon is used for pdfs:

![grafik](https://user-images.githubusercontent.com/2836374/37284335-713b07dc-25fb-11e8-8057-1b5f8cd0f8b6.png)

**Comment by ian-r-rose** [comment]
Yep, agreed. I think the pdf viewer was added after the last pass on icons. @ellisonbg are any of the interns still doing design work around this area?

**Comment by ellisonbg** [comment]
@tgeorgeux

**Comment by ellisonbg** [comment]
@faricacarroll - could you have a go at designing an icon for pdf files?

On Mon, Mar 12, 2018 at 8:37 AM, Ian Rose <notifications@github.com> wrote:
>
> Yep, agreed. I think the pdf viewer was added after the last pass on
icons. @ellisonbg are any of the interns still doing design work around
this area?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.




--
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ianhi** [comment]
This image is quite literally a little rough on the edges but how is this as a basic design?:
![image](https://user-images.githubusercontent.com/10111092/88869647-514bf280-d1e1-11ea-8c36-b9a11915a609.png)

I think this would be an improvement over the current no-icon status of pdfs. 

Alternatively would it be ok to lift an appropriately licensed pdf icon from a desktop environment icon pack?


My design is directly inspired by the PopOs filebrowser icon: 
![image](https://user-images.githubusercontent.com/10111092/88869668-61fc6880-d1e1-11ea-912f-ebde21c65bbe.png)
