### ISSUE TITLE
Indentation not auto applied on Console

### ISSUE THREAD

**Issue by whiletruelearn** [jupyterlab/jupyterlab#4176]
Ipython consoles generally take care of indentation automatically. This doesn't seem to be the case with
jupyter lab consoles, one have to manually indent which is bad user experience.

**Comment by ian-r-rose** [comment]
Hi @whiletruelearn, thanks for the report. This should be fixed by #4070, and will be available in the next release.

**Comment by whiletruelearn** [comment]
@ian-r-rose Thanks for the update.
