### ISSUE TITLE
Feature Request: Rulers in text editor with CodeMirror's display/rulers.js addon

### ISSUE THREAD

**Issue by dillonplunkett** [jupyterlab/jupyterlab#4179]
A possible future enhancement for the text editor: support for vertical rulers through [CodeMirror's display/rulers.js addon](https://codemirror.net/doc/manual.html#addon_rulers).

**Comment by ian-r-rose** [comment]
This is a nice idea for the editor options. I think it's a good project for a new contributor.

**Comment by timhoffm** [comment]
Additional thoughts: One could make the ruler always visible, or only if the cell has focus. Not sure which is better or if it's worth to make that configurable.

**Comment by matrs** [comment]
I see this is merged, but I didn't found any documentation. How do I enable this?

**Comment by jtpio** [comment]
@matrs be sure to install the latest alpha release:

```
pip install --pre jupyterlab
```

Then you can modify the notebook settings under `Settings > Advanced Settings > Notebook` to add the following:

```json
{
    "codeCellConfig": {
        "rulers": [
            80
        ]
    }
}
```

**Comment by jiafengkevinchen** [comment]
Adding the ruler makes cell slightly scroll-able
(JupyterLab 1.0.1)

![image](https://user-images.githubusercontent.com/24930289/61065698-0e8e6100-a3b9-11e9-96d6-ddb8cb5cb70a.png)

![image](https://user-images.githubusercontent.com/24930289/61065768-34b40100-a3b9-11e9-8943-d4b796d207d5.png)

**Comment by v-iashin** [comment]
I can verify that
> Adding the ruler makes cell slightly scroll-able
on 1.0.0 as well. 
Chrome 75.0.3770.142; macOS Mojave 10.14.6

**Comment by jtpio** [comment]
@v-iashin the issue is being tracked in https://github.com/jupyterlab/jupyterlab/issues/6836

And it looks like a fix is coming soon too! https://github.com/jupyterlab/jupyterlab/issues/6836#issuecomment-516054071
