### ISSUE TITLE
File navigation to sibling directories

### ISSUE THREAD

**Issue by sho-87** [jupyterlab/jupyterlab#4180]
It seems that right now jupyter lab's file list will only show you files/directories in the directory from which jupyter lab was launched

It is possible to add a way to navigate to a higher/previous directory, or a sibling directory, from the file explorer? Something like:

```
C:\
| -- Notebooks   <-- launched jupyter lab here
| -- Sibling_dir
D:\
| -- Other_drive
```

I want to be able to access files contained in `Sibling_dir` and `Other_drive`. Is that possible?

**Comment by AbdealiJK** [comment]
For the sibling directory - that is the current expected behaviour
For the D:\ drive, that is a quirk in the way Windows handles file systems which seems difficult to overcome.

Refer https://github.com/jupyter/notebook/issues/1334

**Comment by saulshanabrook** [comment]
Closing this in favor of the upstream issue
