### ISSUE TITLE
deleting multiple cells results in focused cell too far down

### ISSUE THREAD

**Issue by jwkvam** [jupyterlab/jupyterlab#4182]
When I delete multiple selected cells, the focused cell isn't the one I expect. It appears the focused cell jumps down by the length of the selection give or take 1. In the gif, I'd expect the focus to be on the cell with the `4`.

![jlab-delete](https://user-images.githubusercontent.com/86304/37432193-c5a59a4a-2794-11e8-875e-d490e1c343d5.gif)

**Comment by ian-r-rose** [comment]
Thanks for the report @jwkvam!
