### ISSUE TITLE
Real-time collaboration on the same notebook

### ISSUE THREAD

**Issue by elgalu** [jupyterlab/jupyterlab#4187]
What's the plan, JupyterLab-side to support real-time collaboration on the same notebook?

I know the google drive real-time API is deprecated (plus vendor lock) so that's out of discussion.

Rather by integrating with JupyterHub multi-user support for example.

![image](https://user-images.githubusercontent.com/111569/37479895-150a26c0-287e-11e8-8564-dbc26443d513.png)

**Comment by sccolbert** [comment]
It's actively being worked on. I believe there is already another issue which goes into more detail.

**Comment by elgalu** [comment]
Can someone point into the issue so I can subscribe to it?

**Comment by ian-r-rose** [comment]
@elgalu You can find a discussion of the changes we are planning in #2540.
