### ISSUE TITLE
Links between notebooks don't scroll to section given by fragment identifier

### ISSUE THREAD

**Issue by mgeier** [jupyterlab/jupyterlab#4190]
I'm talking about using links that contain a hash character and the name of a section, e.g.

    [my link](my-notebook.ipynb#My-Section)

In the classic Notebook, if I have a notebook called `my-notebook.ipynb` that contains

    ## My Section

... in a Markdown cell, the above link from another notebook works.
That is, if I click on the link, `my-notebook.ipynb` is opened and the browser scrolls to the section "My Section".

In JupyterLab, only the first part works, i.e. the notebook is opened as expected. However, the browser doesn't scroll to the section.

This is needed for feature parity with the classic Notebook.

Note, however, that JupyterLab fixes a bug in the classic Notebook, which is great:
When clicking on a link (as the one mentioned above) several times, the classic Notebook app opens a new tab with a copy of the same notebook each time.
JupyterLab knows that the notebook is already open and (correctly) just switches to the existing view, when clicking the link.

**Comment by ian-r-rose** [comment]
Fixed by #5630
