### ISSUE TITLE
Not possible to delete to beginning/end of line with vim bindings

### ISSUE THREAD

**Issue by fuglede** [jupyterlab/jupyterlab#4193]
While in command mode with the Text Editor Key Map set to "vim", I would expect <kbd>d</kbd><kbd>^</kbd> and <kbd>d</kbd><kbd>$</kbd> to delete everything between the cursor position and the beginning/end of the line respectively. Instead, the key combinations only cause navigation.

**Comment by ian-r-rose** [comment]
I just tried those shortcuts, and they worked as expected for me. Is there anything unusual about your setup?

Note that the vim emulation is provided by CodeMirror, the text editor that we use, and we have very little control over their actual behavior.

**Comment by fuglede** [comment]
Curious. For me, this is reproducible on both Firefox 59.0 and Chromium 66.0.3332.0, both running on Windows 8 with jupyterlab 0.31.12.

**Comment by fuglede** [comment]
Hm, switching keyboard input settings from Danish (in which $ is <kbd>Alt gr</kbd>+<kbd>4</kbd>) to English (in which $ is <kbd>Shift</kbd>+<kbd>4</kbd>) makes it possible

**Comment by jasongrout** [comment]
Browser limitations and bugs can make it very difficult to have keyboard shortcuts work across different keyboard layouts. We have a system for dealing with this for JupyterLab keyboard shortcuts (essentially phosphor has a way to switch a keyboard layout in JupyterLab to match the system keyboard layout you have), but we haven't exposed it yet.

However, if these shortcuts are provided by CodeMirror (the editor we use), that's a different story - I'm not sure how or if CodeMirror handles different keyboard layouts.

**Comment by saulshanabrook** [comment]
I am closing this since I am not sure what we should do on our end here. It looks like this might be a code mirror issue. Please comment if you would like it reopened
