### ISSUE TITLE
Problem with refreshing imagefiles in markdown preview

### ISSUE THREAD

**Issue by jbusecke** [jupyterlab/jupyterlab#4197]
First of all a big compliment on the new version of jupyterlab beta. I LOVE it!

One thing I noticed is that while the text gets updated reasonably fast (although some might disagree #3940), the pictures get 'stuck'.

A typical workflow for me looks like this:

- run a noteboook and produce some plots
- Start a markdown 'report' file and describe some of the findings while linking the figures
- Notice something is not right with one of the figures (let's say I want to adjust a colorbar)
- Reproduce the figure in the notebook tab

The files do not get refreshed (e.g. I see the same old colorbar). The only way I found to show the updated files is to either reload the browser window or close and reopen the markdown viewer. Both of which seems cumbersome.

Is there a way to force a complete update of the markdown preview that I missed? Otherwise, would it be possible to add that option?

I am using Version 0.31.12

**Comment by ian-r-rose** [comment]
Hi @jbusecke,thanks for the report! This behavior is due to overaggressive caching by the browser, and was fixed in #3851. It should be in the next release.

**Comment by jbusecke** [comment]
Oh sweet. 
Sorry that I didnt find that issue.

**Comment by ian-r-rose** [comment]
No problem, glad you're enjoying the beta!
