### ISSUE TITLE
Ctrl-c received signal 2, stopping

### ISSUE THREAD

**Issue by hainm** [jupyterlab/jupyterlab#4203]
hi,

I've been trying to use the latest lab version (0.31).
Open the lab, getting below error (caused by me), so trying to cancel the lab in the terminal (Ctrl-C).
Lab never exits. The only way to really cancel it is to close the bash terminal. :(

<img width="591" alt="screen shot 2018-03-18 at 6 45 53 pm" src="https://user-images.githubusercontent.com/4451957/37572119-c9438662-2adc-11e8-83d2-a57f377c3d24.png">

error message
```
miniconda3/envs/jupyterlab_0_31/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-2'.
```

**Comment by saulshanabrook** [comment]
Please comment if this can be reproduced on the latest jupyter lab
