### ISSUE TITLE
unable to open the lab after installing extension

### ISSUE THREAD

**Issue by hainm** [jupyterlab/jupyterlab#4204]
Hi,

I am using jupyterlab v0.31.12. I was trying to install nglview-jupyterlab extension (my build: https://github.com/arose/nglview/blob/master/jslab/package.json). However,
there is error below that prevents the lab open

<img width="1276" alt="screen shot 2018-03-18 at 8 25 44 pm" src="https://user-images.githubusercontent.com/4451957/37573126-ca3ccc1e-2aea-11e8-9b30-e29e5f9ab898.png">

If I uninstall the extension `jupyter-labextension uninstall nglview-jupyterlab`, then everything is back to normal (e.g: able to open the lab,  able to use ipywidgets).

Any idea how to fix that? 
thanks.

**Comment by jasongrout** [comment]
As a next step, I would put a breakpoint where that first TypeError is happening, and try to figure out why it's trying to read the `name` property of something that is undefined, and why that thing is undefined.

**Comment by vidartf** [comment]
I think it would be appropriate for Jupyterlab to not die completely if one extension fails to load, though.

**Comment by hainm** [comment]
> As a next step, I would put a breakpoint where that first TypeError is happening, and try to figure out why it's trying to read the name property of something that is undefined, and why that thing is undefined.

I will do this and update later. thanks.

**Comment by hainm** [comment]
> As a next step, I would put a breakpoint where that first TypeError is happening, and try to figure out why it's trying to read the name property of something that is undefined, and why that thing is undefined.

hi @jasongrout, what are the specific steps to put the breakpoint, I am kind of naive in JS world.

btw, if you want to try yourself, you can `jupyter-labextension install nglview-jupyterlab`, then issue `jupyter-lab` to reproduce the error.

**Comment by jasongrout** [comment]
See that "index.js:182" in your screenshot, on the first line of the error? Click on that and it should bring you to the line where that error happened. Put a breakpoint there by clicking on the line number (like in https://developers.google.com/web/tools/chrome-devtools/javascript/breakpoints). Then reload the page and it should stop right there and give you a chance to look at the code at that point in time.

**Comment by hainm** [comment]
yeah, thanks Jason. The error says token is unidentified.  Not sure if that's helpful. 

<img width="629" alt="screen shot 2018-03-22 at 9 03 07 am" src="https://user-images.githubusercontent.com/4451957/37772186-3ec79876-2db0-11e8-9a7b-1f0349fbcc9e.png">

**Comment by vidartf** [comment]
@hainm You can also look at the call stack in your dev tools and have a look at the state in the calling function, to see where the undefined token is coming from.

**Comment by sccolbert** [comment]
> I think it would be appropriate for Jupyterlab to not die completely if one extension fails to load, though.

I thought we had some logic to not completely fall over if an extension fails to activate because of missing dependencies. May @afshin recalls?

In general however, we can't prevent an extension from doing something flatly wrong and breaking JupyterLab.

**Comment by jasongrout** [comment]
@hainm - an error there indicates there is some problem loading a dependency of a plugin. I would look at the callstack in your dev tools and try to determine (a) what service was being asked for, and (b) who was doing the asking. My guess is that was your extension asking for possibly an out-of-date dependency - it may be as easy as making sure your dependencies in your extension match up with the version of jupyterlab that you are using.

**Comment by hainm** [comment]
thanks Jason,

I will do further investigation.

**Comment by hainm** [comment]
> My guess is that was your extension asking for possibly an out-of-date dependency - it may be as easy as making sure your dependencies in your extension match up with the version of jupyterlab that you are using.

I am not sure about this. I've checked the version compatibility

```
$ jupyter-labextension list
JupyterLab v0.31.12
Known labextensions:
   app dir: /Users/haichit/miniconda3/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.33.2  enabled  OK
nglview-jupyterlab
        nglview-jupyterlab v1.1.0  enabled  OK
```

According to this page: https://www.npmjs.com/package/@jupyter-widgets/jupyterlab-manager, the versions I have seems ok.
`
For JupyterLab 0.31.x, use jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.33
`

Our `package.json` is quite simple: https://github.com/arose/nglview/blob/master/jslab/package.json

**Comment by jasongrout** [comment]
You probably need also the Jupyter widget manager in your dependencies if you are importing it.

**Comment by hainm** [comment]
uhm, It does not help either.

Quick question: Does extension like `nglview` need [@jupyterlab/nbwidgets](https://www.npmjs.com/package/@jupyterlab/nbwidgets)
I've trying below and getting the error:
```
$ jupyter labextension install @jupyterlab/nbwidgets
> /usr/local/bin/npm pack @jupyterlab/nbwidgets
jupyterlab-nbwidgets-0.21.0.tgz

Errored, use --debug for full output:
ValueError: 
"@jupyterlab/nbwidgets@0.21.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.15.4-0 <0.16.0-0    >=0.7.0-0 <0.8.0-0   @jupyterlab/application
>=0.15.7-0 <0.16.0-0    >=0.7.0-0 <0.8.0-0   @jupyterlab/notebook
>=0.15.4-0 <0.16.0-0    >=0.7.0-0 <0.8.0-0   @jupyterlab/rendermime
```

**Comment by jasongrout** [comment]
You'll need the jupyter-widgets base package, like bqplot: https://github.com/bloomberg/bqplot/blob/bc1fb383cf4c0c4679fc10a294065c5a7d282826/js/package.json#L32

Then your plugin will look something like: https://github.com/bloomberg/bqplot/blob/bc1fb383cf4c0c4679fc10a294065c5a7d282826/js/src/jupyterlab-plugin.js

**Comment by hainm** [comment]
I see that having separated `jslab` is not a good practice anymore. I will follow bqplot example and report later. Thanks.

**Comment by hainm** [comment]
wow, it works if I follow bqplot example. Thanks @jasongrout  very much for always helping me.

**Comment by hainm** [comment]
<img width="1146" alt="screen shot 2018-03-23 at 5 29 37 pm" src="https://user-images.githubusercontent.com/4451957/37854128-fb4d73ac-2ebf-11e8-82af-01a3408fc89c.png">

**Comment by jasongrout** [comment]
Nice!
