### ISSUE TITLE
"collapse selected outputs" collapses the code but not output

### ISSUE THREAD

**Issue by ma-ji** [jupyterlab/jupyterlab#4207]
Select the "collapse selected outputs" from menu actually collapses the code but not output.

**Comment by ian-r-rose** [comment]
Hi @ma-ji, thanks for the report. This bug was fixed in #3895 and a patch has been released. Can you try upgrading your JupyterLab and trying again?

**Comment by ma-ji** [comment]
Yes, it works well, thanks!
