### ISSUE TITLE
Allow MIME based output renderers to be used as default file viewers

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#421]
As it kind-of make sens that Output should not be modified [despite widgets], 
Would it  possible/sensible to define a convenience API that allow to register a "renderer" for a mime type, as well as a "file extension to mime type" association, so that the same plugin could be used to both view a file and used to render an output ?

The viewer would explicitly be limited to pure rendering and get a read-only model ?

Or is it already the case ?

Discussed with @jasongrout

**Comment by ellisonbg** [comment]
I also talked with @Carreau about this at SciPy and think it is a great idea. I renamed the title here to better describe the intention.

**Comment by gnestor** [comment]
I think that this was implemented in https://github.com/jupyterlab/jupyterlab/pull/2555 👍

**Comment by blink1073** [comment]
Yep!
