### ISSUE TITLE
Markdown checkboxes/task lists

### ISSUE THREAD

**Issue by danpf** [jupyterlab/jupyterlab#4211]
Is it intended to show github style checkboxes via the markdown preview?

https://help.github.com/articles/basic-writing-and-formatting-syntax/#task-lists

![image](https://user-images.githubusercontent.com/16297104/37629718-9caa287e-2b9d-11e8-99a4-7d044840379c.png)
for reference github:
```
- [ ] test
- [x] test2
```
- [ ] test
- [x] test2

currently the markdown coloring does suggest they should render differently, but currently it looks like they are just rendered to be bullets.

**Comment by AbdealiJK** [comment]
Note that the `codemirror` library understands taskLists and shows syntax highlighting for taskLists, but the [marked](https://github.com/markedjs/marked) library which is used for rendering the markdown does not seem to support taskLists.

Also, for a good implementation the taskLists would need to support editing the markdown itself - i.e. the markdown cells would be editable by clicking on the rendered text's checkbox. Which will be custom for jupyterlab.
