### ISSUE TITLE
nodejs required for installing labextensions?

### ISSUE THREAD

**Issue by jakevdp** [jupyterlab/jupyterlab#4215]
I've had reports from users of altair that they can't install lab extensions unless they have nodejs installed: https://github.com/altair-viz/altair/issues/617

I've not been able to reproduce these errors myself.

Should I be listing nodejs as a dependency when the instructions involve installing lab extensions?

**Comment by ian-r-rose** [comment]
Yes, users need to have nodejs installed to install labextensions (this is so that we can run npm/yarn/webpack and friends). More documentation [here](http://jupyterlab.readthedocs.io/en/stable/user/extensions.html#extensions).

**Comment by jasongrout** [comment]
Closing as answered, but feel free to post another comment to continue the discussion. Thanks!
