### ISSUE TITLE
Renaming an open file can crash the server (500 Internal Server Error)

### ISSUE THREAD

**Issue by QuentinAndre** [jupyterlab/jupyterlab#4216]
It appears that file names are not validated when renaming a notebook. As a consequence, using an invalid file name (e.g. "foo/bar.ipynb") crashes the server.

Step to reproduce (latest build of JupyterLab, 0.31.12):
1. Open JupyterLab
2. Create a new notebook (will generate an "Untitled.ipynb" file)
3. Rename the file (right click -> rename in Jupyter Lab) to "foo/bar.ipynb" or "foo\bar.ipynb"
4. The server will crash (Error 500) : 500 PATCH /api/contents/Untitled.ipynb?1521641832396 (::1) 0.00ms referer=http://localhost:8889/lab

I think a simple fix would be to validate the new file name on the client side (and raise an error if the validation detects invalid characters), but I am not familiar at all with the code base...

**Comment by ian-r-rose** [comment]
Thanks for the report @QuentinAndre, confirmed!

**Comment by QuentinAndre** [comment]
I should be the one thanking you and the other contributors: I could not work without the Jupyter ecosystem :). I hope I'll find the time to dig into the codebase one day and help you guys push this amazing project forward.
