### ISSUE TITLE
kernel-dependent extension?

### ISSUE THREAD

**Issue by BoPeng** [jupyterlab/jupyterlab#4218]
I am porting the frontend of the [SoS kernel](https://vatlab.github.io/sos-docs/) to JupyterLab. Because the frontend features (e.g. language-selection dropdown box) are only applicable to notebooks with a SoS kernel, I will need to somehow link the [sos extension](https://github.com/vatlab/sos-extension) to the sos kernel so that the extension is only activated (or be effective) when the kernel is loaded. Is there any way to do this? As far as I can tell, Widgets added through `app.docRegistry.addWidgetExtension` are available to all notebooks. Note that this was done in Jupyter through a [customized JS file](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/kernel.js) installed with the kernel, but I do not see a similar mechanism for JupyterLab.

**Comment by ian-r-rose** [comment]
You can try checking the kernel name for each widget (`notebook.context.session.kernelPreference.name`), then only add the additional UI elements if it matches the SoS kernel name.

**Comment by BoPeng** [comment]
But when? The [add button example](http://jupyterlab.readthedocs.io/en/stable/developer/notebook.html) adds the button through `app.docRegistry.addWidgetExtension` when the extension is loaded with no no open notebook, and I have not figured out a way to set up a [`Comm`](http://jupyter-notebook.readthedocs.io/en/stable/comms.html) between the kernel and the extension so that the extension would "respond" to kernel requests...

**Comment by timkpaine** [comment]
kernel side: https://github.com/timkpaine/lantern/blob/master/lantern/live/hosts/comm.py#L29

**Comment by timkpaine** [comment]
client side: https://github.com/jpmorganchase/perspective/blob/master/packages/perspective-jupyterlab/src/ts/index.ts#L91

**Comment by timkpaine** [comment]
this was the only way I was able to get it working. The kernel sends the session information to the client, and registers a target. When the client gets that information, it connects to the comm and the kernel can send data to the front end.

**Comment by ian-r-rose** [comment]
The `ButtonExtension.createNew` function is called with every notebook widget. You can use that opportunity to set up your Comms.

**Comment by BoPeng** [comment]
Great. I will have a further look at the code, but back to a very basic question. in Jupyter, the [customized kernel JS](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/kernel.js) is loaded when the kernel is loaded and it has access to `window` etc and the [`onload` event](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/kernel.js#L2005) can do many things to the notebook. What would be equivalence of `onload` (of particular kernel) in JupyterLab extension?

**Comment by ian-r-rose** [comment]
The client session object (`notebook.context.session`) has a ready promise on it that can be used to wait for the kernel. You would have something like
```typescript
notebook.context.session.ready.then(() => {
  // Do comm stuff
});
```

**Comment by jasongrout** [comment]
Be careful that you also check on kernel change.

**Comment by jasongrout** [comment]
You might look at the ipywidgets extension. It also has to do things on kernel load, kernel restart, and kernel change.

**Comment by BoPeng** [comment]
> You can try checking the kernel name for each widget (`notebook.context.session.kernelPreference.name`), then only add the additional UI elements if it matches the SoS kernel name.

@ian-r-rose I tried to check the name of the kernel when the widget is created (`createNew`) and found that `notebook.context.session.kernelPreference.name` is only available when creating a new notebook. What can be used to check the name of the kernel of an existing notebook? I tried to use `panel.notebook.model.metadata.get('kernelspec')` but it seems that JupyterLab only populate this metadata when the kernel is ready.

**Comment by BoPeng** [comment]
Thank everyone for the help, I am able to get the button and `comm` working, but there are still some basic questions for porting the Jupyter code over.

1. I used `window` to hold global notebook variables. What it the recommended JupyterLab/TypeScript way for this?
2. I used `IPython.notebook` to obtain the current notebook in Jupyter, what is the JupyterLab equivalence for this? More specifically, I need to get the current notebook from the `comm.onMsg` callback.

**Comment by jasongrout** [comment]
Great questions. The design of extensions is a bit different in jlab compared to the classic notebook. You shouldn't use window or global variables - remember there can be multiple notebooks open on the same page. Your createNew function can create an object that is specific to that notebook - store your notebook-specific state in that object (again, that's what we do in the ipywidgets extension, for example: https://github.com/jupyter-widgets/ipywidgets/blob/f8f4d3122b1ea584dc75751874e049e9b9039390/packages/jupyterlab-manager/src/plugin.ts#L56). Also, your createNew function is given the notebook panel as its first argument - that's how you get the handle on it (again, see the ipywidgets code for an example).
