### ISSUE TITLE
Can't embed Insert Image in Notebook

### ISSUE THREAD

**Issue by D3f0** [jupyterlab/jupyterlab#4221]
Firstly let me thank you for all the wonderful work you're doing. I'm using Jupyter Lab with my students for the submissions.
Some of them use images in their Notebooks and we've found that a common Jupyter Notebook feature that allows you to embed an image is not present in Lab.

The feature is about embeding images in the notebook, through the Edit Menu.
<img width="267" alt="insert image" src="https://user-images.githubusercontent.com/46064/37788054-3a5e1772-2ddf-11e8-8fba-55f4ae955b89.png">

I also recorded this short gif to illustrate how it's used:
![insert image jupyter](https://user-images.githubusercontent.com/46064/37788081-4ea7fd6a-2ddf-11e8-9859-9b618e39ec1f.gif)

My Jupyter Lab version is: 0.31.8.

Thank you!

**Comment by vidartf** [comment]
This is tracked in #1398.

**Comment by Gbemileke** [comment]
Thanks for this useful video.
