### ISSUE TITLE
New activity widget remains visible after single-document mode toggled

### ISSUE THREAD

**Issue by madx** [jupyterlab/jupyterlab#4228]
There's a weird glitch that happens when using single-document mode on the new activity widget.

### Steps to reproduce

* Create a New activity tab
* Enter single-document mode
* Select an activity, such as Terminal
* Exit single-document mode
* Enjoy

### Capture

![](http://drop.madx.me/2018-03-23T15:44:35.gif)

**Comment by jasongrout** [comment]
I confirmed that I'm seeing glitches doing the above steps, though they are different than your screenshot. I'm seeing this in master as well.

**Comment by jasongrout** [comment]
Actually, I'm also seeing the weird overlapping launcher/notebook when launching a new notebook, in master.

**Comment by madx** [comment]
Yes, sometimes the widget somehow goes into the background layer and only the top remains and is visible beyond the tabs

**Comment by jasongrout** [comment]
CC @fperez, who also saw this.
