### ISSUE TITLE
Method in Notebook to scroll to a Cell

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyterlab/jupyterlab#4229]
Using Phosphor's [domutils](http://phosphorjs.github.io/phosphor/api/domutils/modules/elementext.html#scrollintoviewifneeded) it is possible to scroll to a widget which is contained inside another widget. It would be useful to have a method inside the `Notebook`, which takes a `Cell` to scroll to that `Cell`. Here is some example (untested) code for this:

``` typescript
// inside Notebook
export
function selectCell(cell: Cell): void {
    this.deselectAll();
    this.select(cell);
}
export
function scrollCellIntoView(cell: Cell): void {
    // use Phosphor to scroll
    ElementExt.scrollIntoViewIfNeeded(this.node, cell.node);
    // optionally change selection and active cell:
    this.selectCell(cell);
    cell.activate();
}
```

**Comment by dharmaquark** [comment]
going to take a pass at this one, if it's unclaimed!

**Comment by jasongrout** [comment]
It looks like this is done over in #6818. Thanks!
