### ISSUE TITLE
Jupyter Logo Not Working for all Latest RTD

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#4232]
Homepage:

![screen shot 2018-03-23 at 17 13 08](https://user-images.githubusercontent.com/1373035/37858062-853ba230-2ebd-11e8-944f-454f1fb45417.png)

versus other page:

![screen shot 2018-03-23 at 17 13 17](https://user-images.githubusercontent.com/1373035/37858063-8554b0d6-2ebd-11e8-9f82-12d8546c0d58.png)

**Comment by jzf2101** [comment]
https://github.com/jupyterlab/jupyterlab/pull/3838

**Comment by afshin** [comment]
Fixes https://github.com/jupyterlab/jupyterlab/issues/3769
