### ISSUE TITLE
79 Character indication in notebook

### ISSUE THREAD

**Issue by rutgerhofste** [jupyterlab/jupyterlab#4235]
It would be great to have an indication of the 79 character limit for PEP8 and other docstring standards. I find the implementation of this in Google Colab very useful and elegant. 

https://drive.google.com/file/d/1hqth9FAFQjwr0stEyijhg2iVuX3zifCg/view?usp=sharing

**Comment by jwkvam** [comment]
Both colab and jupyterlab use codemirror so the same thing can be done in jupyterlab.

https://codemirror.net/demo/rulers.html

**Comment by ian-r-rose** [comment]
Thanks for the suggestion @rutgerhofste. I think it's a good idea. Can we continue the discussion on #4179?

**Comment by mimischi** [comment]
On a slightly related note: are there any plans to include some type of code formatter into JupyterLab, i.e. [`yapf`](https://github.com/google/yapf) or [`black`](https://github.com/ambv/black)? Or any other issue to follow in regards to this?

**Comment by rutgerhofste** [comment]
lets continue the conversation on [#4179 ](https://github.com/jupyterlab/jupyterlab/issues/4179)
