### ISSUE TITLE
Terminal option/alt as meta key?

### ISSUE THREAD

**Issue by haberdashPI** [jupyterlab/jupyterlab#4236]
Hi there, I've just been looking at this project and it looks really cool! Great work!

I'm wondering if there is an option, or any plans for an option, to use Alt or Option as the Meta key in a terminal. 

Most terminal programs I've interacted with have such an option (e.g. iTerm, and Terminal on Mac OS X). This is useful for many of the commands available within terminals, but it's essential for the use of emacs within JupyterLab. (Without meta a lot of standard keybindings require the use of ESC, making them ergonomically useless). I'm open to alternative solutions if someone has a setup that works well for using emacs in JupyterLab, but I haven't figured one out and this solution works well in other environments.

**Comment by haberdashPI** [comment]
I did a little digging and it does appear this is possible with the Xterm.js library that it looks like JupyterLab uses. See https://github.com/xtermjs/xterm.js/pull/1225

I know very little about the code in this repository yet, but this looks like it would be an easy change to make, and I'd be happy to take a stab at trying to implement it, if the dev's are amenable.

**Comment by Carreau** [comment]
I'm not super familiar either, but is seem that xterm is so far [pinned on ~2.8](https://github.com/jupyterlab/jupyterlab/blob/master/packages/terminal/package.json#L39), while this option is only available on 3.10+ of xterm.js the first step would be to upgrade xterm.js and make sure everything works. 

Then we can add the relevant hooks.

**Comment by Madhu94** [comment]
@haberdashPI Looks like the linked tickets are done.

**Comment by Madhu94** [comment]
@haberdashPI The PR you linked seems to be for MAC OSX only? Is that what you wanted ?

**Comment by gnilrets** [comment]
I'd be interested in having this work too.
