### ISSUE TITLE
Where to put static extensions like facets-dist?

### ISSUE THREAD

**Issue by cottrell** [jupyterlab/jupyterlab#4238]
For notebooks you just put or symlink facets-dist in (see jupyter --path)

    share/jupyter/nbextensions

In jupyter lab I have looked at`jupyter lab path` output and tried putting this all over the place but it is not yet found: 

```
$ find .  -name facets-dist
./share/jupyter/lab/static/nbextensions/facets-dist
./share/jupyter/lab/static/facets-dist
./share/jupyter/lab/facets-dist
./share/jupyter/nbextensions/facets-dist

```

**Comment by jameswex** [comment]
Related issue: #3118

**Comment by jasongrout** [comment]
See https://gitter.im/jupyterlab/jupyterlab?at=5ad78f46270d7d3708df17fb for lots of discussion with @jameswex on extensions and facets in particular.

**Comment by jasongrout** [comment]
Basically, the extension system is completely different in JupyterLab, so it's not as easy as just putting a file in a new place. For facets, I think an initial prototype using a mimerender extension might be a good thing to explore:

https://github.com/jupyterlab/mimerender-cookiecutter-ts

http://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#mime-renderer-extensions

**Comment by jasongrout** [comment]
(keep in mind there may be a much better way to load that js on the page these days than just loading a single html file.)

**Comment by jasongrout** [comment]
Closing as answered - but feel free to ask questions below or on gitter if needed!
