### ISSUE TITLE
Large CSV causing Aw Snap in chrome

### ISSUE THREAD

**Issue by AbdealiJK** [jupyterlab/jupyterlab#4239]
Was testing https://github.com/jupyterlab/jupyterlab/pull/4192 as I was looking at some CSV files

When I open my chrome and open a ~800MB file, it started loading that jupyterlab file and then chrome gave me a "Aw Snap" error.

Now ... when I tried to refresh that google-chrome tab, it tries to load jupyterlab (gives me the jlab loading animation) and then keeps giving me an Aw Snap.

When I tried to kill my jupyterlab server and restart it, it told me "this is taking a long time. Do you want to clear your workspace"
 - When I didnt tell it to clear, it again gave "Aw Snap"
 - When I click on "clear workspace" it still gave me an Aw Snap. Had to refresh again and then it worked

Note: I can see the "Google Chrome Helper" using upto 2.2GB of RAM before the "Aw snap"

Just reporting this in case it can be made more robust ... looks like there are some race conditions at play

**Comment by saulshanabrook** [comment]
So I think the issue here is that if the file is too big JupyterLab should warn that it won't be able to open?

**Comment by jasongrout** [comment]
1. It should work much better now, now that we've rewritten the CSV parser. In particular, I don't think you'll hit this out of memory limit anymore.
2. The file size limits are documented in docs, and depend on the browser: https://jupyterlab.readthedocs.io/en/stable/user/file_formats.html#delimiter-separated-values

**Comment by jasongrout** [comment]
If you see this error anymore, please comment below.
