### ISSUE TITLE
undo delete (DD) in jupyterlab

### ISSUE THREAD

**Issue by sirajpresswala** [jupyterlab/jupyterlab#4241]
i frequently find myself in a situation where i have deleted cells with valid code by pressing key 'D'>>'D'  inadvertently when the cell is active. It would be helpful feature if, there is a way to undo the delete and retrieve the cell contents.

**Comment by AbdealiJK** [comment]
Try `Z` - the undo command.
Or search for "Undo cell operation" in the "commands"

**Comment by mgeier** [comment]
See also #4765.
