### ISSUE TITLE
console does not preserve the order of printed output and input

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#4242]
Console shows all `input`s in a separate sequence from all printed output.

To reproduce execute:
```python
print('test')
input('a')
print('test2')
input('b')
```
and observe the output like this:
![image](https://user-images.githubusercontent.com/2069677/37875678-21f80ee8-3043-11e8-883c-33ef95bb5186.png)
in the classic notebook the ordering is correct (therefore this is a feature parity issue):
![image](https://user-images.githubusercontent.com/2069677/37875688-30432e7e-3043-11e8-9519-23de884913fc.png)

Jupyterlab version: 0.31.12

**Comment by jasongrout** [comment]
In JLab 2.1.4, this appears to behave correctly:

<img width="347" alt="Screen Shot 2020-06-04 at 9 27 41 AM" src="https://user-images.githubusercontent.com/192614/83785109-adf9b980-a645-11ea-877e-f3aec8f67888.png">
