### ISSUE TITLE
timeline to major release and teaching in JupyterLab

### ISSUE THREAD

**Issue by smsaladi** [jupyterlab/jupyterlab#4243]
Sorry if this information is available elsewhere, but is there a projected timeline to the first major release (i.e. v1.0.0)?

Should we expect large user-facing/gui/frontend changes between now and then? 

Those may be potentially difficult questions to answer.

What I'd like to know is this ... for an [introductory programming course](http://justinbois.github.io/bootcamp/2017/) (taught by @justinbois), we have planned to have students work in Jupyter notebook sessions for part of the time.

However, for our own work, we've switched over to JupyterLab. Lots of new, convenient features.

Would you suggest teaching students in JupyterLab over Jupyter notebook sessions? Since the course will be held in June, I am concerned that changes between then and v1.0.0 release will result in students having a difficult time adapting when they fire up JupyterLab, months after the course is finished.

We appreciate all the input!

**Comment by jasongrout** [comment]
CC @ellisonbg - he is already teaching students using JupyterLab

**Comment by consideRatio** [comment]
I can't really add insight into the beta JupyterLab -> JupyterLab 1.0 situation, but I think utilizing JupyterLab is the way to go.

* Drag and drop file handling for you and students
* Only JupyterLab in active use, and not classic + jupyterlab, reducing complexity
* Less learning for students, never needing to learn about the soon to be outdated classic mode

I'm a teacher in Sweden for high school students, they stumbled a lot on the file management in the classic notebooks so I'm really happy about the JupyterLab experience.

**Comment by jasongrout** [comment]
Closing as answered.
