### ISSUE TITLE
Shift-Tab completion gives function signature on a single line

### ISSUE THREAD

**Issue by Zulko** [jupyterlab/jupyterlab#4244]
Hi there and thanks for JupyterLab,

When getting a function help with Shift Tab the function signature is on one line, forcing me to scroll horizontally to read it all.

Issue #2384 already pointed that out, with screenshots, and showed how it is better with the Jupyter notebook (which auto-wraps the lines), but it seems that the issue was closed after part of it (the color scheme issue) was fixed. As a result the single-line problem is still there (I am using a Jupyter lab installed 1 week ago).

**Comment by AbdealiJK** [comment]
I think you have linked the wrong issue

**Comment by Zulko** [comment]
Ouch, thanks for this ! I fixed it.

**Comment by ian-r-rose** [comment]
This is a good point. I think the fix would be similar to the one added recently in #4105. Marking as a good first issue.

**Comment by ian-r-rose** [comment]
Closed by #4248
