### ISSUE TITLE
Query contents without getting exception 

### ISSUE THREAD

**Issue by timkpaine** [jupyterlab/jupyterlab#4247]
Raising this again now that [this](https://github.com/jupyterlab/jupyterlab/pull/3741) was merged. The goal for this is to do autocomplete on paths, but unfortunately I haven't been able to call get on the contents manager and not get a 404, so there are two strategies we can try:

1. change the contents manager for the client to be able to handle the 404 exception/modify server side to support returning partials
2. Move that logic to the client, I.e. call get up to the last directory (e.g. /path/to/\<partial\> would call get on /path/to with contents=True) and then filter for matches client side. 

Any thoughts? Seems like 2 is much easier.

**Comment by ian-r-rose** [comment]
I agree that option two is easier. It also has the benefit of not requiring changes in the contents manager or server, with which we generally want to be more conservative.
