### ISSUE TITLE
Char limit indicator

### ISSUE THREAD

**Issue by timhoffm** [jupyterlab/jupyterlab#4249]
## Feature Request

Add an option to draw a vertical line after 79 chars in code cells. This helps writing PEP-8 conforming code (useful if you later copy code from the notebook to another application). But probably more importantly, conforming to a character limit ensures that generated output has all code visible (e.g. the PDF converter just writes out the code, which then gets clipped at the page border after some 80ish characters).

Some additional thoughts:

- This can probably be implemented using the display/rulers.js [CodeMirror addon](https://codemirror.net/doc/manual.html#addons). 
- The width could be configurable in codeCellConfig.
- One could make the ruler always visible, or only if the cell has focus. Not sure which is better or if it's worth to make that configurable either.

**Comment by mocquin** [comment]
Duplicate of #4235 and #4179 ;)

**Comment by timhoffm** [comment]
Discussion runs in #4179.
