### ISSUE TITLE
Changes to typescript code is not taking effect after building Jupyterlab locally

### ISSUE THREAD

**Issue by bharatl** [jupyterlab/jupyterlab#4251]
I have added some customized code in __packages/cells/src/widget.ts__ file, after building the code the changes are not being reflected. Below are the steps that I followed for building the source code after modifying __packages/cells/src/widget.ts__

pip install -e .
jlpm install
jlpm run build
jlpm run build:core
jupyter lab build

My changes are visible and works when I start server as __jupyter lab --dev-mode__  but the same won't work when I run the server as __jupyter lab__. 

So my changes are only visible when running in dev mode. 

I need help in building the source code and test the same after starting the server in production mode __jupyter lab__ .

**Comment by ian-r-rose** [comment]
The sources shown when you run `jupyter lab` are the *published* packages, whereas those shown when you run `jupyter lab --dev-mode` are the local ones. What are you trying to accomplish such that `--dev-mode` is not sufficient?

**Comment by bharatl** [comment]
Thanks Ian Rose for replying,
Actually I am trying to develop a feature internally for my company, that feature only works when I run in dev-mode. I want to deploy the feature in production thats the reason of not running the server in dev-mode.

**Comment by ian-r-rose** [comment]
Our recommended way of extending/modifying JupyterLab is to write a third-party extension and then install it into your JupyterLab. Can you try that approach? Or, if that does not work, can you describe more what you are trying to do?

**Comment by bharatl** [comment]
Thanks Ian Rose, will try to write an extension

**Comment by saulshanabrook** [comment]
Closing this for now. Feel free to comment if you have more questions
