### ISSUE TITLE
New view for file in separate panel

### ISSUE THREAD

**Issue by mocquin** [jupyterlab/jupyterlab#4256]
When I create a new view for a file, it adds a new view tab for the file in the same panel. I then always have to move it to create a separate panel, because if I want 2 view for my file, I always want to see both view at the same time.

I would expect that when I create a new view for a file, it creates a new panel for this second view (splitting horizontally the main work area for e.g), and not add it on top of the first view.

**Comment by ian-r-rose** [comment]
This is a good idea, @mocquin. I think it's a good candidate for a first contribution.

**Comment by jasongrout** [comment]
FYI, here is the line that splits the panel for a new view for an output: https://github.com/jupyterlab/jupyterlab/blob/629f7b2fecc32fe0c4791ffa8826923ba47fd990/packages/notebook-extension/src/index.ts#L1296
