### ISSUE TITLE
Bug in handling of relative URLS in vega3 extension

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#4260]
See here for more details...

**Comment by ellisonbg** [comment]
@gnestor @domoritz

**Comment by ellisonbg** [comment]
https://github.com/altair-viz/altair/issues/611

**Comment by ellisonbg** [comment]
The Vega loader API is here:

https://github.com/vega/vega-loader#vega-loader

**Comment by ellisonbg** [comment]
@gnestor we talked about this at the dev meeting today and @ian-r-rose is going to have a look

**Comment by gnestor** [comment]
Ok, I'm on vacation this week but @ian-r-rose let me know if you have any questions, I have my computer with me.

**Comment by vidartf** [comment]
Fixed by #4265?

**Comment by ian-r-rose** [comment]
Yep, thanks @vidartf
