### ISSUE TITLE
Why two copies of assets?

### ISSUE THREAD

**Issue by mdeff** [jupyterlab/jupyterlab#4267]
Why is it that if we install with `python setup.py install` we end up with two copies of the assets in `share/jupyter/lab/{static,schemas,themes}` and `lib/python3.6/site-packages/jupyterlab/{static,schemas,themes}`? Those are present in the conda package too.

**Comment by mdeff** [comment]
I just realized it may be because of the below (from the [documentation](http://jupyterlab.readthedocs.io/en/stable/user/extensions.html)):
> Note that building will always use the latest JavaScript packages that meet the dependency requirements of JupyterLab itself and any installed extensions. If you wish to run JupyterLab with the set of pinned requirements that was shipped with the Python package, you can launch as jupyter lab –core-mode.

Then does `share/jupyter/lab/{static,schemas,themes}` contain the latest JavaScript packages, while `lib/python3.6/site-packages/jupyterlab/{static,schemas,themes}` contains the ones pinned during packaging?

In which case I guess it's preferable for a package manager (see e.g. Arch Linux [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jupyterlab)) to not build jupyterlab and symlink `share/jupyter/lab/{static,schemas,themes}` to `lib/python3.6/site-packages/jupyterlab/{static,schemas,themes}`. I think it's better because i) the versions have been tested and ii) we don't end up with two copies. What do people think? Shouldn't the [conda recipe](https://github.com/conda-forge/jupyterlab-feedstock/blob/master/recipe/meta.yaml) do the same by installing with `python setup.py install --skip-build`? Users shall only need to build later on if they want to install extensions.

**Comment by saulshanabrook** [comment]
@mdeff we have some explanation about the directories in the Extensions > Advanced Usage documentation: https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#advanced-usage

Python package is meant to be immutable, so all the built files, installed themes, installed extensions, and settings live in the shared directory. 

Yes I would agree that arch linux should not symlink those.
