### ISSUE TITLE
When I open Jupyter Lab, it shows the animation with the two crescents and three dots, then blank white page

### ISSUE THREAD

**Issue by johnmarktaylor91** [jupyterlab/jupyterlab#4268]
The installation seems to have gone successfully, but when I type "jupyter lab" into the terminal, the browser window just opens, shows the animation with the two crescents and three dots, then just turns white. Any idea what the problem might be? I'm using Firefox 24.6.0, running on CentOS (Release 6.5, Kernel Linux 2.6.32-642-.6.2.el6.x86_64, GNOME 2.28.2). Thanks for any help. I have already seen a similar problem elsewhere (https://github.com/jupyterlab/jupyterlab/issues/408), but this one didn't mention the animation showing up. I've attached a picture of the terminal display when I call the command. Much obliged for any help.

<img width="1190" alt="screen shot 2018-03-28 at 8 17 25 pm" src="https://user-images.githubusercontent.com/16569815/38063026-16ce8680-32c5-11e8-946f-4c391d357fdb.png">

**Comment by jasongrout** [comment]
Do you see any errors in the browser's javascript console?

**Comment by johnmarktaylor91** [comment]
Yup. The error at the bottom ("expected declaration...") repeats many more times. 

<img width="1290" alt="screen shot 2018-03-28 at 10 11 45 pm" src="https://user-images.githubusercontent.com/16569815/38066208-073ec120-32d5-11e8-9722-2adb76a49bc6.png">

**Comment by vidartf** [comment]
> Firefox 24.6.0

Firefox 24 does not support CSS variables, and I think other lab features also require a reasonably up to date browser.
