### ISSUE TITLE
Crash after open notebook

### ISSUE THREAD

**Issue by lejabque** [jupyterlab/jupyterlab#4269]
When I try to open my notebook, RAM usage of browser is going to 4gb. And then it giving an Aw Snap
There is no problem with that notebook in good old Jupyter. Also I haven't got any problems with other notebook

Checked this on Google Chrome (last version), Opera (last version too) and Microsoft Edge.
That notebook - https://colab.research.google.com/drive/1q2vURq2Z5QCcTeFCK17hVmjsItOYy5JQ

**Comment by lejabque** [comment]
And often I get this error in Anaconda Prompt
![image](https://user-images.githubusercontent.com/30625073/38079173-94a66de2-333e-11e8-9421-d0cd20ee6b6d.png)

**Comment by lejabque** [comment]
Now jupyter lab just can't start in browser. It shows the animation, while RAM usage is going to 2gb. And then I get 'Aw Snap'
![image](https://user-images.githubusercontent.com/30625073/38079249-bcb973d8-333e-11e8-83b6-1c69757f1c7c.png)

**Comment by lejabque** [comment]
Removed my notebook from PC. Now Jupyter Lab started without any problems

**Comment by lejabque** [comment]
Cleared output in notebook in old Jupyter.
Now it runs in Jupyter Lab.

**Comment by xappppp** [comment]
I encounter the same issue when open the notebook in Jupyter Lab, not a problem in Jupyter Notebook
