### ISSUE TITLE
jupyterhub requirement in jupyterlabcontainer

### ISSUE THREAD

**Issue by davidbath** [jupyterlab/jupyterlab#4272]
Apologies if this is the wrong place to ask this question, but have I correctly understood that when using a containerised spawning system (e.g. docker or k8s), the container with the single-user server (in my case jupyterlab) also needs to have the jupyterhub package installed? 

It seems that the labhubapp.py, which seems to be the file that's triggered when using jupyterlab in single user mode requires it as an import.

My questions:

(1) Is my understanding correct?
(2) Why is this? Is there a better way to connect a single-user instance of jupyterlab to jupyterhub without requiring the whole package in every single-user container?

Thanks!
David

**Comment by consideRatio** [comment]
In [my dockerfile](https://github.com/consideRatio/z2jh-extended/blob/master/images/singleuser/Dockerfile) I have written this comment after asking a similar question, but I certainly don't grasp the details. But it makes sense to me that some setup is required for the singleuser server to know that it is spawned by a jupyterhub, it might need to reply "I'm alive" or something for example.

```Dockerfile
# kubespawner requires the singleuser image to be started with a script
# provided by the jupyterhub package, and will hence override the CMD with 
# ["jupyterhub-singleuser"] instead of the jupyter/docker-stacks images CMD
# of ["start-notebook.sh"]
ARG JUPYTERHUB_VERSION=0.8.*
RUN pip install --no-cache jupyterhub==$JUPYTERHUB_VERSION
```

The script referenced can be found [here](https://github.com/jupyterhub/jupyterhub/tree/master/scripts).

**Comment by davidbath** [comment]
Hi @consideRatio - thanks for the reply. I think the point about which command is actually used to launch jupyter inside the container is a slightly different point. For example, the DockerSpawner inspects the CMD of the docker image specified to be spawned, and then tries to call that at launch.

So, in my model, I wanted the notebook(jupyterlab) docker images to be useful on individual machines. I have therefore set the command in the dockerfile to `CMD jupyter lab --port=8080 --no-browser --ip=0.0.0.0`. This way if you just run the dockerfile on a standalone machine you can still get a working jupyterlab installation. The side effect of this is that in the spawner configuration, I have to make sure that the spawner calls the single user server, e.g. `c.Spawner.cmd = ['jupyter-labhub']`

It's this last point that prompted me to ask the question - this shorthand at the shell level expands to calling `jupyterlab.labhubapp:main`, which gets you to `https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/labhubapp.py`. And here we need to be able to import jupyterhub.

As far as I can tell, this then uses `jupyterhub/singleuser.py,` who's primary job is to subclass the normal notebookapp, add some hub-related parameter passing (hub URIs, IPs etc), and then add the client-end of authentication towards the hub.

So my observation is that the "client-side" part of registering with the jupyterhub code is actually stored inside the jupyterhub code tree, forcing a notebook(jupyterlab) installation to also install a complete jupyterhub tree even though it only uses a couple of files from it.

Have I got that flow right? And if so is there a lighterweight way of providing the "client-side" part of connecting a notebook(jupyterlab) in my single-user server container?

Any insights, corrections and suggestions gratefully received!

**Comment by consideRatio** [comment]
@davidbath Oh thank you for providing me with a better insight on this!!! Great summary!

Perhaps this already exist in or could end up in for example the JupyterHub docs.

**Comment by saulshanabrook** [comment]
Closing this since I think this question could be better answered in the JupyterHub repo.

**Comment by jasongrout** [comment]
> Closing this since I think this question could be better answered in the JupyterHub repo.

Is there a corresponding issue in the jupyterhub repo you could reference? Or are you asking @davidbath to open an issue in the jupyterhub repo if this is still an issue?

**Comment by saulshanabrook** [comment]
I am asking @davidbath to open an issue there if they are still having an issue.
