### ISSUE TITLE
webpack --config webpack.prod.config.js hanging 

### ISSUE THREAD

**Issue by StephaneKazmierczak** [jupyterlab/jupyterlab#4276]
Hello, 

I have noticed that everytime that I am trying to install an extension then
$ webpack --config webpack.prod.config.js seems to stay stuck indefinitely 

having --dev at the end of the install command seems to make it work 
but I am then getting other errors later with the extension 

I am using:
jupyterlab 0.31.12
nodejs 9.10

**Comment by cemulate** [comment]
I'm having the same issue with the same version(s).

Even with no extensions installed, `jupyter lab build` tries to run `webpack --config webpack.prod.config.js` and hangs for a very long time, while `jupyter lab build --dev` just runs `webpack` and finishes in a few seconds.

So it seems to be the production config that's causing a problem.

**Comment by jasongrout** [comment]
We just released jlab 0.32.0. Do you see the same problem with 0.32.0?

**Comment by cemulate** [comment]
Nope, this time it finished in 28.34s! Great work!

**Comment by cemulate** [comment]
Although upon installing `@jupyter-widgets/jupyterlab-manager`, it appears to be taking a very long time again. `--dev` still works though. I'll let it run tonight and see if it ever finishes

**Comment by jasongrout** [comment]
I've installed widgets several times without it hanging. Are you using conda? If so, can you reproduce it in a clean environment and tell me what packages you installed? I'd like to try to reproduce it.

**Comment by cemulate** [comment]
Yep, I'll try and find some time to play around with this and be a better issue reporter! I'm running all this in WSL, so who knows if some strange issues are lurking there. 

It seems that webpack always reports a ~30 second run time but the _actual_ time it takes the command to run is far longer...

Like I said, I'll see what I can determine.

**Comment by TiemenSch** [comment]
^ I can confirm this. Also on WSL. I included my log here:  https://github.com/jupyterlab/jupyterlab-monaco/issues/5.

**Comment by cemulate** [comment]
I've tried to reproduce this in docker containers and the like and I can't seem to do it. I have to believe then that it's some strange quirk in WSL. I'll see if I can get it to happen there again.

**Comment by jasongrout** [comment]
Great. I don't have WSL, so it would be great if someone like you can dig into this further.

**Comment by TiemenSch** [comment]
Would anyone be willing to explain the key (or exact) differences between running prod or dev-mode? Perhaps that would shed some light on what the culprit might be.

**Comment by jasongrout** [comment]
running in dev mode runs with this webpack config: https://github.com/jupyterlab/jupyterlab/blob/0.32.x/jupyterlab/staging/webpack.config.js

Running in prod mode runs this webpack config, which basically takes the above config and modifies it to use uglify and adds the npm production variable: https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/staging/webpack.prod.config.js

**Comment by jasongrout** [comment]
At least, that's my current understanding of the build system :).

**Comment by jasongrout** [comment]
So to diagnose, perhaps you could go to the prod webpack config installed in your site-packages/jupyterlab/, modify it, then do a `jupyter lab clean` and `jupyter lab build`. It *should* copy the webpack config from the site-packages/jupyterlab/staging directory over to the actual build directory in `sys-prefix/share/jupyterlab/`, then build there (I would include some sentinel in the webpack config, like a console.log, just to make sure that it's actually running the webpack config you modified).

**Comment by vidartf** [comment]
> At least, that's my current understanding of the build system :).

I agree. Though as an aside, it is quite confusing that there is both a `--dev` flag, and a `--dev-mode` flag.

**Comment by jasongrout** [comment]
yes, the name choice is unfortunate. `--dev` just does things like not minify the js, and is about making it easier to develop your own extensions. `--dev-mode` builds from the source repo instead of published packages, which makes it possible to test changes to the jlab source repo itself. They are actually orthogonal to each other.

Thoughts on better naming?

**Comment by vidartf** [comment]
> Thoughts on better naming?

Not really, but maybe the help string for `--dev` should be a little more clear what it means. Currently it only says "Build in Development mode", which is even more similar (includes "mode").

**Comment by vidartf** [comment]
To come back to the main topic, there are several things that make the production build run slower:
- Dead code elimination: Webpack tries to analyze the code to see if it can optimize away parts of the code. This might be a heavy job for big projects like this (but also very useful to reduce the bundle size).
- Better source maps: The source maps for the production build are more specific, but subsequently take longer to compile.

See webpack docs for more details.

**Comment by jasongrout** [comment]
> Not really, but maybe the help string for --dev should be a little more clear what it means. Currently it only says "Build in Development mode", which is even more similar (includes "mode").

Can you open an issue about this? I agree the help string should be better.

**Comment by choldgraf** [comment]
I can also confirm that `jupyter lab build` hangs on WSL, while `jupyter lab build --dev` runs fine

**Comment by TiemenSch** [comment]
Perhaps it's trivial, but I just tried to remove the UglifyJS bits from **webpack.prod.config.js** to isolate the issue. 

## Uglify identified as culprit

**C:\miniconda3\envs\monaco\lib\python3.6\site-packages\jupyterlab\staging\webpack.prod.config.js**
```
// var UglifyJSPlugin = require('uglifyjs-webpack-plugin');
var merge = require('webpack-merge');
var webpack = require('webpack');
var common = require('./webpack.config');

module.exports = merge(common, {
  devtool: 'source-map',
  plugins: [
    //   new UglifyJSPlugin({
    //     sourceMap: true,
    //     parallel: true,
    //     uglifyOptions: {
    //       beautify: false,
    //       ecma: 6,
    //       mangle: true,
    //       compress: false,
    //       comments: false,
    //     }
    //   }),
    new webpack.DefinePlugin({
      "process.env": {
        NODE_ENV: JSON.stringify("production")
      }
    })
  ]
});
```

## Finding the cause

So heading into the uglifyjs-webpack-plugin repo, I quickly found this issue: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/118 . 

It seems that Windows does not like the way the parallel workers work, so even WSL, although being close to Linux, still suffers from this Windows caveat. They patched the platform specific issue in https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/173, but not (yet) for WSL. 

I tried to work around this by turning off **parallel** and it works when I try to link an extension I'm fiddling with. 
<details>
 <summary>Terminal output</summary>

```
jupyter labextension link .
> /mnt/c/miniconda3/envs/monaco/bin/npm pack /mnt/d/jupyterlab/jupyterlab-monaco
jupyterlab-monaco-0.1.0.tgz
> /mnt/c/miniconda3/envs/monaco/bin/npm pack /mnt/d/jupyterlab/jupyterlab-monaco
jupyterlab-monaco-0.1.0.tgz
> /mnt/c/miniconda3/envs/monaco/bin/npm pack /mnt/d/jupyterlab/jupyterlab-monaco
jupyterlab-monaco-0.1.0.tgz
> node /mnt/c/miniconda3/envs/monaco/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has incorrect peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has incorrect peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile '/home/tiemen/.cache/yarn/v1/npm-d3-format-1.3.0-a3ac44269a2011cdb87c7b5693040c18cddfff11/locale/en-GB.json' -> '/mnt/c/miniconda3/envs/monaco/share/jupyter/lab/staging/node_modules/d3-format/locale/en-GB.json'".
info If you think this is a bug, please open a bug report with the information provided in "/mnt/c/miniconda3/envs/monaco/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> node /mnt/c/miniconda3/envs/monaco/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.5.1
$ webpack --config webpack.prod.config.js
Hash: 1a1c6c33b734dc813001
Version: webpack 2.7.0
Time: 91776ms
                                 Asset       Size  Chunks                    Chunk Names
            43.3701c3b427885cfefa8e.js    3.66 kB      43  [emitted]
  912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  [big]
   6a679d196dfae198da9e99beed29fb92.js    8.23 MB          [emitted]  [big]
   19c2058b2714a3d47e8596a1dfeb80a2.js     767 kB          [emitted]  [big]
...
        44.f680c953567442170aa4.js.map    5.03 kB      44  [emitted]
      main.b38582c6c14e64033680.js.map      17 MB      45  [emitted]         main
    vendor.d22f7ef9b29d404303e7.js.map    5.69 MB      46  [emitted]         vendor
  manifest.1484211aa67218974bca.js.map    10.4 kB      47  [emitted]         manifest
                            index.html    1.53 kB          [emitted]
[/sZe] ./~/@phosphor/commands/lib/index.js 33.3 kB {46} [built]
[2Kj9] ./~/@phosphor/widgets/lib/index.js 1.38 kB {46} [built]
[6nap] ./~/ajv/lib/ajv.js 15.2 kB {46} [built]
[Vszx] ./~/@phosphor/domutils/lib/index.js 636 bytes {46} [built]
[b/Hx] ./~/ansi_up/ansi_up.js 13.6 kB {46} [built]
[cYMN] ./~/@phosphor/virtualdom/lib/index.js 21 kB {46} [built]
[dyOy] ./~/url-parse/index.js 11.4 kB {46} [built]
[hKoQ] ./~/es6-promise/dist/es6-promise.js 28.6 kB {46} [built]
[q1RZ] ./~/@phosphor/datagrid/lib/index.js 793 bytes {46} [built]
[ug+F] ./~/xterm/lib/xterm.js 52.7 kB {46} [built]
   [8] multi @phosphor/algorithm @phosphor/application @phosphor/commands @phosphor/coreutils @phosphor/datagrid @phosphor/disposable @phosphor/domutils @phosphor/dragdrop @phosphor/messaging @phosphor/properties @phosphor/signaling @phosphor/virtualdom @phosphor/widgets ajv ansi_up codemirror comment-json es6-promise marked moment path-posix react react-dom sanitize-html url-parse xterm 328 bytes {46} [built]
   [9] multi whatwg-fetch ./build/index.out.js 40 bytes {45} [built]
[wr2+] ./~/@phosphor/properties/lib/index.js 6.58 kB {46} [built]
[wuIn] ./~/comment-json/index.js 103 bytes {46} [built]
[y7VK] ./~/@phosphor/algorithm/lib/index.js 1.03 kB {46} [built]
    + 2890 hidden modules

WARNING in ./~/monaco-editor/esm/vs/language/typescript/lib/typescriptServices.js
Module not found: Error: Can't resolve 'source-map-support' in '/mnt/c/miniconda3/envs/monaco/share/jupyter/lab/staging/node_modules/monaco-editor/esm/vs/language/typescript/lib'
 @ ./~/monaco-editor/esm/vs/language/typescript/lib/typescriptServices.js 4940:24-53
 @ ./~/monaco-editor/esm/vs/language/typescript/languageFeatures.js
 @ ./~/monaco-editor/esm/vs/language/typescript/tsMode.js
 @ ./~/monaco-editor/esm/vs/language/typescript/monaco.contribution.js
 @ ./~/monaco-editor/esm/vs/editor/editor.main.js
 @ ./~/jupyterlab-monaco/lib/index.js
 @ ./build/index.out.js
 @ multi whatwg-fetch ./build/index.out.js

WARNING in ./~/monaco-editor/esm/vs/editor/common/services/editorSimpleWorker.js
378:12-387:17 Critical dependency: the request of a dependency is an expression
Child html-webpack-plugin for "index.html":
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [GTAU] ./~/html-loader!./templates/partial.html 420 bytes {0} [built]
    [M4fF] ./~/lodash/lodash.js 540 kB {0} [built]
    [vxCX] ./~/html-webpack-plugin/lib/loader.js!./templates/template.html 1.41 kB {0} [built]
Done in 94.40s.
```
</details>

Done in 94.40s.

Slow, but it works!

## WSL workaround

WSL workaround would be to turn off **parallel** by manually editing the file in your Jupyterlab package folder at **jupyterlab\staging\webpack.prod.config.js**. This may be slower, but works until the platform fix is patched in the uglifyjs-webpack-plugin. 

```
var UglifyJSPlugin = require('uglifyjs-webpack-plugin');
var merge = require('webpack-merge');
var webpack = require('webpack');
var common = require('./webpack.config');

module.exports = merge(common, {
  devtool: 'source-map',
  plugins: [
    new UglifyJSPlugin({
      sourceMap: true,
      parallel: false,
      uglifyOptions: {
        beautify: false,
        ecma: 6,
        mangle: true,
        compress: false,
        comments: false,
      }
    }),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('production')
    })
  ]
});
```

**Comment by TiemenSch** [comment]
I opened an issue at the uglifyjs-webpack-plugin repo and someone was willing to look into it. Some quick stabs at it did not yet solve the issue right away, though. 

Also, completely turning off parallel seems too rigorous as most users can probably run it in parallel just fine. I would say keeping this open gives WSL users an easy, temporary workaround, albeit a bit slower.

**Comment by choldgraf** [comment]
FWIW I don't see anything in that issue that suggests they'll prioritize WSL at the moment. I'd be +1 to a hacky workaround here mixed with a small note in the docs saying what we're doing.

**Comment by jasongrout** [comment]
> Also, completely turning off parallel seems too rigorous as most users can probably run it in parallel just fine.

I think the workaround just turns it off for windows, right?

**Comment by TiemenSch** [comment]
@choldgraf I mean this issue: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/302

@jasongrout I just edited my webpack.prod.config.js directly in my miniconda installation's site-packages. That isn't really a platform specific workaround to include in "general" distributions, right?

In uglifyjs-webpack-plugin, there should already be a fix in place for the "win32" platform, but WSL presents itself as "linux" with "Microsoft" mentioned in the release version number. Also, I could not get it to work directly by merely changing the said file in /node_modules/uglifyjs-webpack-plugin of the extension I was trying to link.

**Comment by choldgraf** [comment]
ah I was thinking check whether `/mnt/c/` was present or something like this (it's annoying that WSL pretends it's "just linux" from a sys.platform perspective)

**Comment by choldgraf** [comment]
a suggestion from twitter was to use `subprocess.Popen("wsl.exe ls")` and see if it exits successfully. If not, you're probably not on WSL.

**Comment by choldgraf** [comment]
oooh an even better suggestion from twitter:

>  cat /proc/sys/kernel/osrelease

should return a string with "microsoft" in it

**Comment by vidartf** [comment]
> cat /proc/sys/kernel/osrelease

Instead of interacting with the shell, you should be able to get the same info from `platform.release()`, or alternatively `platform.version()`. E.g.:

```python
import platform

on_wsl = platform.system() == 'Linux' and 'microsoft' in platform.release().lower()
# OR
on_wsl = platform.system() == 'Linux' and 'microsoft' in platform.version().lower() 
```

**Comment by TiemenSch** [comment]
better take the same ``.lower()`` precaution in ``platform.system()`` right? In node it's in lowercase, for example.
```node
> process.platform
'linux'
> os.release()
'4.4.0-17134-Microsoft'
> os.platform()
'linux'
```

**Comment by TiemenSch** [comment]
When I kill the build, this is my traceback by the way:

```
  File "/home/tiemen/miniconda3/envs/monaco/bin/jupyter-labextension", line 11, in <module>
    sys.exit(main())
  File "/home/tiemen/miniconda3/envs/monaco/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/tiemen/miniconda3/envs/monaco/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/tiemen/miniconda3/envs/monaco/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 213, in start    super(LabExtensionApp, self).start()
  File "/home/tiemen/miniconda3/envs/monaco/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start    self.subapp.start()
  File "/home/tiemen/miniconda3/envs/monaco/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 75, in start
    logger=self.log, command=command)
  File "/home/tiemen/miniconda3/envs/monaco/lib/python3.6/site-packages/jupyterlab/commands.py", line 259, in build
    command=command, clean_staging=clean_staging)
  File "/home/tiemen/miniconda3/envs/monaco/lib/python3.6/site-packages/jupyterlab/commands.py", line 403, in build
    self._run(['node', YARN_PATH, 'run', command], cwd=staging)
  File "/home/tiemen/miniconda3/envs/monaco/lib/python3.6/site-packages/jupyterlab/commands.py", line 1278, in _run
    return proc.wait()
  File "/home/tiemen/miniconda3/envs/monaco/lib/python3.6/site-packages/jupyterlab/process.py", line 108, in wait
    time.sleep(1.)
KeyboardInterrupt
```

**Comment by SeaDude** [comment]
Where are we with this? 
I'm using Azure Data Scienct VM and hitting this issue when trying to run `jupyter labextensions install xyz`. https://github.com/MicrosoftDocs/azure-docs/issues/25148. Am I missing something or are these directly related (8+months later)

**Comment by mindon** [comment]
the `jupyter lab build` just hangs at
 ```
yarn run v1.9.4
$webpack
```
with 100% CPU occupied.

And its output is the same as [#issuecomment-394529813](#issuecomment-394529813) described if the hanging killed.

env ( using [jupyterhub docker](https://hub.docker.com/r/jupyterhub/jupyterhub/) and `conda install juypterlab`)
```
$python --version
Python 3.6.7

$node --version
v8.10.0

$jupyter --version
4.4.0

$jupyter lab --version
0.35.4
```

attched log file is the output from `conda list`
[conda-list.log](https://github.com/jupyterlab/jupyterlab/files/3083028/conda-list.log)

**Comment by nendonerd** [comment]
I'm using MacOS and ```jupyter labextension install @jupyter-widgets/jupyterlab-manager``` stucked forever. But running it in dev mode, ```jupyter labextension install --dev-build=True @jupyter-widgets/jupyterlab-manager``` works well. Jupyter Lab version: 1.2.4, MacOS version: 10.14

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/124787851-6b5a8d00-df7b-11eb-99c4-5e70b1166b9a.png)

stuck an hour.

**Comment by vidartf** [comment]
@GF-Huang Which version of JupyterLab? (and which version of nodejs?)

**Comment by GF-Huang** [comment]
Latest version of 21 days ago.
