### ISSUE TITLE
jupyterlab yarn doesn t find react

### ISSUE THREAD

**Issue by StephaneKazmierczak** [jupyterlab/jupyterlab#4278]
Hello, 
I am getting some warning trying to install extension:

warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".

So I installed react using 'npm install react' but I am still getting the warnings? 

I am using ubuntu lts 
node 9.1 
jupyterlab 0.31.12

**Comment by saulshanabrook** [comment]
Does the extension finish installing and work? If it does, then I would just ignore the warnings.

**Comment by StephaneKazmierczak** [comment]
Thank you for the help Saul, The extension doesn't finish normally I have to add --dev in the command line to get it to complete, so that is why I was curious about those warnings.

**Comment by saulshanabrook** [comment]
Sorry, I dropped the discussion here! If you have the same issue with a recent version of JupyterLab, could you please post the trace of trying to install the extension and I will try to help.
