### ISSUE TITLE
Add "create new directory", "create new file" to filebrowser context menu

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#4280]
See https://github.com/jupyterlab/jupyterlab/issues/3602#issuecomment-377406408

**Comment by jasongrout** [comment]
I think they should probably be there even if clicking on a file. Otherwise how do you do it if your file list fills up the screen?

**Comment by dhirschfeld** [comment]
I just found myself wanting this exact functionality!

**Comment by dhirschfeld** [comment]
Also, `Copy Path` and `Open in Terminal`

**Comment by Jose24San** [comment]
I can take a stab at this during DISC2018

**Comment by ian-r-rose** [comment]
It looks like this issue has already been done in #5447. Or were you thinking of going after some of the other suggestions in this issue?

**Comment by ian-r-rose** [comment]
Thanks @Jose24San! Sorry for any confusion. Closing as fixed.

**Comment by krassowski** [comment]
@ian-r-rose this was not resolved fully in #5447 as it only addressed the "create new directory" part (and not "Ccreate file", "Copy path" and "Open in Terminal") . Should this be re-opened or should we create a new issue for each item proposed?

**Comment by ian-r-rose** [comment]
Ah, my mistake. I think we can re-open, with apologies to @Jose24San!
