### ISSUE TITLE
Add line breaks to improve the readability of function signatures in the object inspector

### ISSUE THREAD

**Issue by joelostblom** [jupyterlab/jupyterlab#4285]
Docstrings are often limited to around 70-80 char width. This makes them easy to view in the object inspector. I suggest to word wrap the function signature to a similar width as what is commonly used for docstrings (i.e. fixed at around 70-80 chars, not adaptable depending on docstring width) in order to improve readability.

In my opinion, it is more useful to be able to see all the parameters in the signature without scrolling horizontally because I can then leave the object inspector open on the side and when I need to check the name of a paramater I can just glance at it without moving my hands. With the current behavior, I need to move the mouse to the object inspector and scroll horizontally to the right to find the parameter I am looking for and then scroll back to the left to return to the docstring. This is slower and causes more of an interruption than just glancing at the inspector window.

Signature wrapping is used in the Jupyter Notebook tooltip, so I will use one of those to illustrate my point. I think it is more helpful to see this:

![image](https://user-images.githubusercontent.com/4560057/38144371-74a9a0c0-3412-11e8-89d9-2c08ea732440.png)

than this:

![image](https://user-images.githubusercontent.com/4560057/38144454-bf025fb8-3412-11e8-9ac9-9d3df66e16c9.png)

I agree with the point @ellisonbg made in #1976 regarding that wrapping makes more sense for narrative text than for formatted text, such as already hard wrapped docstrings, and I think the current behavior of leaving docstrings intact and instead adapting the width of the object inspector or popup tooltip is great. However, function signatures are rarely written as one long line in the source, and often word wrapped to improve readability (as for [`sns.pairplot`](https://github.com/mwaskom/seaborn/blob/71a807b6bfa1605d46046a287614818de8662bf3/seaborn/axisgrid.py#L1877)). I think word wrapping function signatures will display similarly to their original formatting, which improves readability over having to scroll through one long line.

Lack of signature wrapping also make the pop up tooltip less useful (again, because you have to use the mouse to see the parameters), which is already reported in #3109.

**Comment by ian-r-rose** [comment]
Hi @joelostblom, thanks for the thoughts. Word-wrapping for the tooltip and inspector was added recently in #4248 and #4105. They should be available in the next release.

**Comment by joelostblom** [comment]
@ian-r-rose That's great! Thanks for letting me know and sorry for not finding those PRs.
