### ISSUE TITLE
Application launch error!

### ISSUE THREAD

**Issue by javeeddanyal** [jupyterlab/jupyterlab#4295]
[I 14:49:38.308 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 14:49:38.703 NotebookApp] JupyterLab beta preview extension loaded from /home/danyal/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 14:49:38.703 NotebookApp] JupyterLab application directory is /home/danyal/anaconda3/share/jupyter/lab
[I 14:49:38.713 NotebookApp] Serving notebooks from local directory: /home/danyal
[I 14:49:38.713 NotebookApp] 0 active kernels
[I 14:49:38.713 NotebookApp] The Jupyter Notebook is running at:
[I 14:49:38.713 NotebookApp] http://localhost:8888/?token=d70bddf090220624e97b20f67c694b1e005e57c950b9e3db
[I 14:49:38.713 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:49:38.715 NotebookApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=d70bddf090220624e97b20f67c694b1e005e57c950b9e3db
[I 14:49:39.104 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[22398:22437:0401/144939.155362:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.

**Comment by ian-r-rose** [comment]
@javeeddanyal That looks like a browser error. What browser/OS are you using? Is it consistent across different browsers?

**Comment by jasongrout** [comment]
Closing since there was no follow-up from the submitter. @javeeddanyal - if you are still having problems, please open another issue.
