### ISSUE TITLE
better error message when server is stopped

### ISSUE THREAD

**Issue by clkao** [jupyterlab/jupyterlab#4298]
If the singleuser server is stopped in another browser tab, which is usually the case because the menu item for control panel opens a new tab, user gets rather confusing message:

```
Server Connection Error
Unexpected token < in JSON at position 3
```

**Comment by ian-r-rose** [comment]
@clkao Can you describe in more detail the issue you are seeing, and whether you still see it in more recent releases? I don't quite understand how to reproduce it.

**Comment by clkao** [comment]
Just tested on 0.34.7.  Stopped server worked fine for standalone lab, but would cause jupyterhub-based lab errors:

<img width="476" alt="2018-09-07 10 26 58" src="https://user-images.githubusercontent.com/69736/45195162-e873ce00-b288-11e8-9681-42ca02a8d7f7.png">

I think it's because jupyterhub's configurable http proxy redirects lab api requests to the hub itself, causing jupyterlab client not handling this gracefully.

Steps to reproduce:

1. in a jupyterhub environment, launch a jupyterlab-enabled notebook server
2. when the user wants to stop the server, menu -> hub -> control panel
3. this opens a new tab for the user to click "stop server"
4. now back to the original jupyterlab browser tab, you get the "Unexpected token in json" error message,

This is also the same behaviour when user server is forcibly stopped by admin.

If the user dismiss the dialog and continue using lab, more error messages as the responses to api calls are now processed by hub:

<img width="457" alt="2018-09-07 10 30 55" src="https://user-images.githubusercontent.com/69736/45197326-2d9cfd80-b293-11e8-99e8-22dd9d05e9ea.png">

**Comment by consideRatio** [comment]
Thank you @clkao for addressing and investigating this issue, it is a very cumbersome user experience that I'm very familiar with! :heart:

**Comment by minrk** [comment]
JupyterHub recently got [this patch](https://github.com/jupyterhub/jupyterhub/pull/2001/files) which should cause a JSON 404 message when requests are sent to stopped servers. This is in 0.9.1. Are you seeing this error with JupyterHub more recent than that?

**Comment by minrk** [comment]
Thanks! I'll need to investigate why the logic I expect isn't triggering. Do you have the Hub logs when this happens?

**Comment by clkao** [comment]
ok here are the logs after hub is stopped. from the popup message i'd expect to see something redirected to an endpoint that generates html, but it seems the 302 ones get to json repsonses with `{ message: "randomuser is not running" }`

```

[I 2018-09-14 01:27:30.378 JupyterHub proxy:264] Removing user randomuser from proxy (/user/randomuser/)
[D 2018-09-14 01:27:30.378 JupyterHub proxy:686] Proxy: Fetching DELETE http://10.233.9.58:8001/api/routes/user/randomuser
[I 2018-09-14 01:27:30.388 JupyterHub spawner:1770] Deleting pod jupyter-randomuser
[I 2018-09-14 01:27:32.040 JupyterHub log:158] 302 GET /user/randomuser/api/kernels/3cac4b15-7d3d-45bb-a955-5cdef6474725/channels?session_id=e519a772-b10a-4e7e-9b50-7db1fe8ed687&token=[secret] -> /hub/user/randomuser/api/kernels/3cac4b15-7d3d-45bb-a955-5cdef6474725/channels?session_id=e519a772-b10a-4e7e-9b50-7db1fe8ed687&token=[secret] (@127.0.0.1) 1.09ms
[I 2018-09-14 01:27:34.136 JupyterHub log:158] 302 GET /user/randomuser/api/kernels/3cac4b15-7d3d-45bb-a955-5cdef6474725/channels?session_id=e519a772-b10a-4e7e-9b50-7db1fe8ed687&token=[secret] -> /hub/user/randomuser/api/kernels/3cac4b15-7d3d-45bb-a955-5cdef6474725/channels?session_id=e519a772-b10a-4e7e-9b50-7db1fe8ed687&token=[secret] (@127.0.0.1) 1.07ms
[I 2018-09-14 01:27:34.616 JupyterHub log:158] 302 GET /user/randomuser/api/contents/?content=1&1536888454450 -> /hub/user/randomuser/api/contents/?content=1&1536888454450 (randomuser@X.X.X.X) 0.99ms
[I 2018-09-14 01:27:34.671 JupyterHub base:1018] randomuser is pending stop
[I 2018-09-14 01:27:34.672 JupyterHub log:158] 200 GET /hub/user/randomuser/api/contents/?content=1&1536888454450 (randomuser@X.X.X.X) 54.18ms
[I 2018-09-14 01:27:38.345 JupyterHub log:158] 302 GET /user/randomuser/api/kernels/3cac4b15-7d3d-45bb-a955-5cdef6474725/channels?session_id=e519a772-b10a-4e7e-9b50-7db1fe8ed687&token=[secret] -> /hub/user/randomuser/api/kernels/3cac4b15-7d3d-45bb-a955-5cdef6474725/channels?session_id=e519a772-b10a-4e7e-9b50-7db1fe8ed687&token=[secret] (@X.X.X.X) 1.06ms



[W 2018-09-14 01:27:40.379 JupyterHub base:786] User randomuser: server is slow to stop
[I 2018-09-14 01:27:40.380 JupyterHub log:158] 202 DELETE /hub/api/users/randomuser/server (randomuser@X.X.X.X) 10072.02ms
[I 2018-09-14 01:27:44.163 JupyterHub log:158] 302 GET /user/randomuser/api/sessions?1536888463903 -> /hub/user/randomuser/api/sessions?1536888463903 (randomuser@X.X.X.X) 1.05ms```

**Comment by clkao** [comment]
I do see 404s for /hub/user/randomuser/api/{sessions,terminals,kernel/...} afterwards. but the client error happened before the `slow to stop` hub log.

**Comment by aar0nTw** [comment]
> If the user dismiss the dialog and continue using lab, more error messages as the responses to api calls are now processed by hub:
> 
> <img alt="2018-09-07 10 30 55" width="457" src="https://user-images.githubusercontent.com/69736/45197326-2d9cfd80-b293-11e8-99e8-22dd9d05e9ea.png">

After switch auto_login flag to False, the JL will not show File Save Error with pure html source code in msg body anymore.

**Comment by JasonWeill** [comment]
This no longer happens in Lab 4.1.0; the web client displays a more logical modal dialog.

![image](https://github.com/jupyterlab/jupyterlab/assets/93281816/8680de5b-9870-409d-aec1-d372ff6211f7)
