### ISSUE TITLE
user request: csv viewer:: double click to select column header

### ISSUE THREAD

**Issue by pleabargain** [jupyterlab/jupyterlab#4299]
When I click on the header of a csv column in the viewer, the string does not get highlighted.
It would be very nice if users could select column headers for copying and pasting into notebook.
![double click col head to select peek 2018-04-02 15-29](https://user-images.githubusercontent.com/640846/38196258-aa287d82-368a-11e8-8150-aa263f030e2b.gif)

thank you,
Dennis

**Comment by saulshanabrook** [comment]
Thanks for this report. This is because the datagrid does not support copying: https://github.com/phosphorjs/phosphor/issues/285
