### ISSUE TITLE
process.env is always empty in my jupyter_extension.

### ISSUE THREAD

**Issue by HongSeokHwan** [jupyterlab/jupyterlab#4300]
Hi, Thanks for great open source. 

I want to get some env variables in my jupyter_extension but I don't know how to pass it. 
I always got empty process.env in my extension.
Is there any way to access?

**Comment by saulshanabrook** [comment]
We don't pass the environmental variables to the frontend, so you won't be able to access them in JupyterLab extension. We only expose a few select things to the page config from the backend to the frontend: https://github.com/jupyterlab/jupyterlab/blob/64384fca62f4515810132064f41c14db10b28bd1/jupyterlab/extension.py#L91
