### ISSUE TITLE
Paste images from clipboard / screenshots

### ISSUE THREAD

**Issue by leemengtaiwan** [jupyterlab/jupyterlab#4306]
Hi, I wonder if there is a way to paste images into (MarkDown) cells directly from clipboard? This will be a lot of help because I frequently take screenshots and incorporate them into Markdown cells in my notebooks.

The Pycharm equivalent plugin of this feature is [Paste Image To Markdown](https://github.com/holgerbrandl/pasteimages).

Any comments is appreciated, thanks in advance!

**Comment by Bamieh** [comment]
Any news on this? I have become very familiar with the code base and writing plugins lately so I want to take on this task and write it as a plugin if no one has done this already.

**Comment by leemengtaiwan** [comment]
@Bamieh I don't know any existing plugin for doing this from the time I posted this isse, but I think many people including me will be very appreciated if there is a working one!

**Comment by Bamieh** [comment]
@leemengtaiwan I am almost done with the basic implementation, i'll share the results soon 😄

**Comment by jasongrout** [comment]
I think this is important to be in core. I'm excited to see your implementation!

**Comment by vidartf** [comment]
The existing mechanism for this in classic notebook is using *attachments*, but the user interface for adding attachments has not yet been added to lab. See also #4333. If you want to work on it, the best place to add the code is likely in the attachments package. Hope this helps :+1:

**Comment by vidartf** [comment]
See also #4828.

**Comment by Bamieh** [comment]
@vidartf thank you, I am done with the implementation (as a separate plugin for now called clipboard). But just before I publish I started getting this error that im still stuck on:

> Error: No provider for: @jupyterlab/filebrowser:IFileBrowserFactory.

Any clue?

**Comment by jasongrout** [comment]
Sometimes this happens if you accidentally have two packages that aren't deduped. One thing you can try is to clean out your node_modules and do `jupyter lab clean`, then build again. Check to make sure your jupyterlab dependency versions match up with the jupyterlab versions too.

**Comment by Bamieh** [comment]
@jasongrout thanks you.

here is a link to the extension: https://github.com/Bamieh/jupyterlab-clipboard
It can be also found on npm: https://www.npmjs.com/package/jupyterlab-clipboard

What it does on pasting clipboard image:
1. save image as
2. links image as markdown in the text.

Current Limitations:
- inserts markdown image tag for all kinds of cells, it should only do so with markdown for now at least.
- assumes png image type (super easy fix to accommodate all browser types)
- the save as needs a small preview image (easy)
- listens to paste event only
- not sure about browser support.

CC @leemengtaiwan @vidartf

**Comment by Will-So** [comment]
@Bamieh, tried it out and it works quite well. Thanks!

**Comment by Bamieh** [comment]
@Will-So awesome! i'll improve the implementation gradually within these few days (currently pasting anything opens the save as dialog which is a little annoying)

**Comment by agoose77** [comment]
I've created an extension to restore the original UI for attachments [here](https://github.com/agoose77/jupyterlab-attachments). I've also added the ability to add from the File Browser Tree context menu. I'm going to look into adding the clipboard paste feature too, but I could use some input on this, as I'm not sure where it is appropriate to add the event handler (as it seems one must handle this through native JS code rather than any JupyterLab API?)

**Comment by ZedTDean** [comment]
You can copy and paste images and screenshots  in normal Jupyter bit not jupyter lab, i use OneNote or snip & sketch  that comes with windows 10 to capture some screen areas.

1) take screenshot using Prtscn or any of the mentioned toots above
2) convert the cell to markdown 
3) Ctrl-V in teh cell you will see the following line "![image.png](attachment:image.png)"
4) run the sell 
5) the screenshot will appear in the cell 

Not sure why it does not work in Jupyter lab 

I am not sure why it does not

**Comment by llinfeng** [comment]
@ZedTDean Try pasting OneNote-clipped screenshot into JupyterLab: it works. The image file is saved in some binary format, directly to the `*.ipynb` file.  This is with Version 1.1.4 for Jupyter Lab.

Caveats: Github does not render screenshots in Markdown cells, nor does [colab](colab.research.google.com/).

**Comment by ianhi** [comment]
@llinfeng as of version 2.1 you can paste multiple images into the same cell and they won't overwrite.

**Comment by anna-anisienia** [comment]
could you add requirements.txt?

ValueError: The extension "jupyterlab-clipboard" does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.1.2 <2.2.0          >=0.19.1 <0.20.0@jupyterlab/application
>=4.1.0 <4.2.0          >=2.2.1 <3.0.0 @jupyterlab/coreutils
>=2.1.2 <2.2.0          >=0.19.3 <0.20.0@jupyterlab/filebrowser
>=2.1.2 <2.2.0          >=0.19.2 <0.20.0@jupyterlab/notebook
>=5.1.0 <5.2.0          >=3.2.1 <4.0.0 @jupyterlab/services

**Comment by jasongrout** [comment]
I just tested this as well, and in the latest version, I can paste multiple images into a markdown cell successfully.

Closing as fixed. Thanks everyone!
