### ISSUE TITLE
Key Map (Sublime Text) does not work

### ISSUE THREAD

**Issue by jGsch** [jupyterlab/jupyterlab#4310]
For exemple, 'Ctrl+D' still delete the line instead of just selecting a word.

Even after selected 'Sublime Text' in the Settings like that:
![screenshot from 2018-04-03 15-15-48](https://user-images.githubusercontent.com/22634019/38251557-1128b71e-3752-11e8-9fa1-067c0b2276b5.png)

And it appears correctly in the CodeMirror Settings:
![screenshot from 2018-04-03 15-16-22](https://user-images.githubusercontent.com/22634019/38251559-11783d70-3752-11e8-8c1b-7424bfcd429b.png)

Maybe it's my keyboard (swiss french layout) ?

**Comment by ian-r-rose** [comment]
Hi @jGsch, can you confirm that you are using the text editor? Custom keyboard bindings are not currently implemented for the notebook.

**Comment by jGsch** [comment]
I misunderstood, I was thinking keyboard binding worked for notebook too. By the way, it works perfectly for the text editor.

**Comment by csaid** [comment]
Thanks developers for all your work on Jupyter! I would just like to add that having Sublime key bindings in the notebook is by far my top request as well.

**Comment by ryantam626** [comment]
Hello :wave: ! (And sorry for reviving this) I started something to get it going, it's not perfect but it does scratch the itch of multiple cursors (well at least for me :grinning: ). https://github.com/ryantam626/jupyterlab_sublime
