### ISSUE TITLE
[Feature request] Multiple files downloading

### ISSUE THREAD

**Issue by yevtu** [jupyterlab/jupyterlab#4311]
It would be nice to have an ability to select many files in File Explorer and then download all of them at once instead of doing this one by one.

**Comment by dclong** [comment]
It's definitely a useful feature!

**Comment by timkpaine** [comment]
@youngthejames

**Comment by timkpaine** [comment]
This is supported already by the filetree extension: https://github.com/youngthejames/jupyterlab_filetree/commit/4653b174ec5f41f93256520e4ef741b5f4fa82dc

**Comment by JasonWeill** [comment]
This now works in Lab 4.1.0.
