### ISSUE TITLE
Dark Theme with STDIN 

### ISSUE THREAD

**Issue by betteridiot** [jupyterlab/jupyterlab#4312]
When using the dark theme and requesting an `input()`, the element `jp-Stdin-prompt` does not change color for the theme and shows up black (shown below). I don't know enough about your CSS framework to suggest a PR, but I am thinking that assigning `--jp-ui-font-color0` to the color attribute of  `jp-Stdin-prompt` should fix it. (seen bottom)

Existing:
![image](https://user-images.githubusercontent.com/25447319/38252583-8e547cd0-3722-11e8-87c1-13bf8667b8a7.png)

With new CSS rule:
![image](https://user-images.githubusercontent.com/25447319/38253246-297bc442-3724-11e8-9336-4791a20f07e4.png)

**Comment by ian-r-rose** [comment]
Thanks for the report @betteridiot!

**Comment by betteridiot** [comment]
In bug testing, I found that just setting the color of `jp-Stdin-prompt` changes the color for the whole line, to include the `jp-Stdin-input` element. This means that the white box has white text. Just setting `#text.jp-Stdin-input` to `--jp-ui-font-color0` should correct this.

A different alternative is to still change the color of `jp-Stdin-prompt`, but also change `jp-Stdin-input` color to black (or whatever). Again...not a CSS expert here.
