### ISSUE TITLE
IPyWidget output context manager not respected

### ISSUE THREAD

**Issue by mrocklin** [jupyterlab/jupyterlab#4319]
There appears to be a difference in how `ipywidget.Output` objects are handled between the classic notebook and JupyterLab notebook

### Classic Notebook

![image](https://user-images.githubusercontent.com/306380/38327609-a38c1370-3816-11e8-82be-fb35f98fc622.png)

### JupyterLab Notebook

![image](https://user-images.githubusercontent.com/306380/38327577-927cef0a-3816-11e8-8de3-b1cf2e5948fe.png)

**Comment by bhammer-os** [comment]
I experienced the same problem with 
jupyterlab '0.32.1'
ipywidgets '7.2.1'

I was able to correct the behavior by installing ipywidgets '7.1.1'

**Comment by jasongrout** [comment]
What version of the widgets jlab extension do you have? `jupyter labextension list`

**Comment by PierreMarion23** [comment]
Hi! I'm bouncing back on the issue as I have similar problems to the bug listed above, although not exactly the same thing.

First, the `output.append_stdout` does not work in JupyterLab while it works in the classic notebook.

Second, the following commands don't print anything when the slider value changes, again this bug only appears in JupyterLab, not in the classic notebook.

```python
int_range = widgets.IntSlider()
display(int_range)

def on_value_change(change):
    print(change['new'])
   
int_range.observe(on_value_change, names='value')
```

But then, the following commands do actually work, and increment the counter:

```python
int_range = widgets.IntSlider()
x = [0]
display(int_range)

def on_value_change(change):
    x[0] += 1
  
int_range.observe(on_value_change, names='value')
```
So this problem seems really to be linked to the display of what happens inside the callback `on_value_change`.

I don't know if the two issues could somehow be related? 

I have jupyterlab 0.32.1, ipywidgets 7.2.1, and jupyterlab extension 0.35.0

**Comment by oscar6echo** [comment]
I can reproduce the problem described by @PierreMarion23, have a possible explanation - to be confirmed by core dev - and a suggestion (as the current situation is a bit painful):

Python code:
```python
import ipywidgets as widgets

int_range = widgets.IntSlider()
label = widgets.Label(value='My label')
output = widgets.Output()
a = 0

def on_value_change(change):
    print(change['new'])
    label.value = 'label:  a={}, change={}'.format(a, change)
    with output:
        print('ouput:  a={}, change={}'.format(a, change))
    # a += 1
    
int_range.observe(on_value_change, names='value')

display(int_range, label, output)
```

The first print does not show up.
The widgets label and output get updated properly and it shows.
If I uncomment `a += 1` or modify `print(change['new'])` to `print(change2['new'])` then nothing shows up.

So my understanding is that the 'default output' is lost or hidden - **on purpose ?**
But if there is no way to channel it, at least the error traceback, to regular output, then **debbuging becomes really difficult as the callback silently fails**... (I have already experienced it in a project)

Please advise !

---------

To reproduce:

My JupyterLab setup is:
```bash
$ jupyter labextension list
JupyterLab v0.32.1
Known labextensions:
   app dir: /usr/local/anaconda3/envs/bug-lab/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.35.0  enabled  OK
```
The ipywidgets versions are:
```bash
$ conda list widg
# packages in environment at /usr/local/anaconda3/envs/bug-lab:
#
# Name                    Version                   Build  Channel
ipywidgets                7.2.1                    py36_0  
widgetsnbextension        3.2.1                    py36_0  
```

**Comment by jasongrout** [comment]
I would do it like this:

```python
from ipywidgets import IntSlider, Output

int_range = IntSlider()
output = Output()

display(int_range)

@output.capture()
def on_value_change(change):
    print(change['new'])
   
int_range.observe(on_value_change, names='value')
display(output)
```

**Comment by jasongrout** [comment]
Or you could do `@output.capture(clear_output=True)` to have more of an interact-like feel.

**Comment by oscar6echo** [comment]
All right !!  
Excellent ! Solves my problem perfectly.  
@jasongrout  Thank you !

I can debug with the decorator `@output.capture(clear_output=True/False)` and remove it when it works. In addition I can always log the changes. Here is the example - if it may help others:  

```python 
from ipywidgets import IntSlider, Output

import logging
logging.basicConfig(
    format="%(asctime)s [%(threadName)-12.12s] [%(levelname)-5.5s]  %(message)s",
    level=logging.DEBUG,
    handlers=[logging.FileHandler('debug.log'), logging.StreamHandler()]
)
logger = logging.getLogger()

int_range = IntSlider()
out = Output()
display(int_range, out)

@out.capture(clear_output=True)
def on_value_change(change):
    logger.info('new={}'.format(change['new']))
    print(change['new'])
    
int_range.observe(on_value_change, names='value')
```

**Comment by jasongrout** [comment]
We also have an open issue to add logging support for the output widget: https://github.com/jupyter-widgets/ipywidgets/issues/1936

See also the docs: http://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html#Integrating-output-widgets-with-the-logging-module

**Comment by jasongrout** [comment]
Though I think that the current JupyterLab output widget may not support the things necessary for the logging recipe above to work (see https://github.com/jupyter-widgets/ipywidgets/issues/1810). It should work in the classic notebook, though...

**Comment by oscar6echo** [comment]
Ok, valuable info !   
I'll leave below an example of a logger that has 3 handlers to pick from: stream, file, widget output (with a scroll bar).   
As @jasongrout  mentions the 3 outputs do work fine in the classic notebook, but the widget output handler does not (yet I suppose) in JupyterLab.

```python
import logging
import ipywidgets as wg

class OutputWidgetHandler(logging.Handler):
    """ logging handler sending logs to an output widget """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        layout = {
            'width': '100%',
            'height': '160px',
            'border': '1px solid gray',
            'overflow_y': 'scroll'
        }
        self.out = wg.Output(layout=layout)

    def emit(self, record):
        """ Overload of logging.Handler method """
        formatted_record = self.format(record)
        new_output = {
            'name': 'stdout',
            'output_type': 'stream',
            'text': formatted_record+'\n'
        }
        # order: latest first
        self.out.outputs = (new_output, ) + self.out.outputs
        # order: oldest first
        # self.out.outputs = self.out.outputs + (new_output, )

    def show(self):
        """ Show logs """
        display(self.out)

    def clear(self):
        """ Clear logs """
        self.out.clear_output()


stream_handler = logging.StreamHandler()
file_handler = logging.FileHandler('debug.log')
widget_output_handler = OutputWidgetHandler()

logging.basicConfig(
    format="%(asctime)s [%(threadName)-12.12s] [%(levelname)-5.5s]  %(message)s",
    level=logging.DEBUG,
    handlers=[stream_handler, file_handler, widget_output_handler]
)
logger = logging.getLogger()

int_range = wg.IntSlider()
out = wg.Output()
display(int_range, out)

@out.capture(clear_output=False)
def on_value_change(change):
    logger.info('new={}'.format(change['new']))
    print('capture:', change['new'])
    
int_range.observe(on_value_change, names='value')
```

**Comment by PierreMarion23** [comment]
Ok great, it also solves my problem! Thanks @jasongrout!

**Comment by fcollonval** [comment]
Here is a workaround to display the log in JupyterLab.

```python
class OutputWidgetHandler(logging.Handler):
    """ Custom logging handler sending logs to an output widget """

    def __init__(self, *args, **kwargs):
        super(OutputWidgetHandler, self).__init__(*args, **kwargs)
        layout = {
            'width': '100%',
            'height': '160px',
            'border': '1px solid black'
        }
        self.out = widgets.Output(layout=layout)

    def emit(self, record):
        """ Overload of logging.Handler method """
        formatted_record = self.format(record)
#         self.out.append_stdout(formatted_record+'\n')
        with self.out:
            print(formatted_record)

    def show_logs(self):
        """ Show the logs """
        display(self.out)

    def clear_logs(self):
        """ Clear the current logs """
        self.out.clear_output()
```

**Comment by saulshanabrook** [comment]
@jasongrout Do we need any additional fixes here?

**Comment by jasongrout** [comment]
We can close this. First, it's an ipywidgets issue, not a JLab issue. Second, we've fixed it in ipywidgets anyway. Thanks!
