### ISSUE TITLE
Could not determine jupyterlab build status without nodejs

### ISSUE THREAD

**Issue by pleabargain** [jupyterlab/jupyterlab#4327]
I'm seeing this error in the terminal
Could not determine jupyterlab build status without nodejs

but nodejs (0.1.1)
 is installed
![image](https://user-images.githubusercontent.com/640846/38415524-7532f6e4-399a-11e8-98de-89bd918a9f56.png)

from pip3 list:
jupyter (1.0.0)
jupyter-client (5.2.3)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
jupyterlab (0.31.12)
jupyterlab-discovery (4.0.0)
jupyterlab-launcher (0.10.5)

**Comment by pesho-ivanov** [comment]
Try restarting the browser. It worked for me (Chromium).

**Comment by pleabargain** [comment]
@vidartf   pip3 install --user nodejs 

And I agree, that version is really old... 
I installed nodejs manually and the error went away.

Thanks.

**Comment by ZnoorZ** [comment]
Facing same issue: "Could not determine jupyterlab build status without nodejs". Even though latest version of nodejs is installed.

**Comment by rpgoldman** [comment]
As of today, pip is *still* giving me `nodejs` at version 0.1.1 per https://pypi.org/project/nodejs/

It seems wrong that jupyterlab should require nodejs at a version that is beyond what pip provides.  And the github homepage indicates that `python-nodejs` is `[UNMAINTAINED]`, so maybe it is altogether a bad dependency to have.

**Comment by vidartf** [comment]
@rpgoldman Note that nodejs and *the python package* you mention are two different things. The latter is an abandoned attempt at distributing nodejs via pip. As such, you cannot currently use pip to install nodejs. Working alternatives include:
- manually downloading from the web and installing
- using conda
- using other package managers

**Comment by rpgoldman** [comment]
@vidartf I suppose that's true, but having a python system (jupyterlab) that can't be installed with pip seems suboptimal.  I don't know what the alternatives are, though.

**Comment by vidartf** [comment]
Anyone can volunteer to maintain a PyPI distribution of nodejs :)
