### ISSUE TITLE
Allow extensions to add webpack loaders

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#4328]
I'm currently working on an extension that includes webgl shaders (`require(./myshader.glsl)`). When trying to build this for jupyterlab, it fails as the webpack build does not bundle these shaders.

When bundling for a classic notebook extension using webpack, I use the npm package `webpack-glsl-loader`. This differs from a raw loader in that it handles nested imports (`@import ...`).

One solution to this problem would be to allow extension to specify its loader config, i.e. in package.json:

```json
{
 "jupyterlab": {
  "webpack-rules": [
   { "test": "/module_name\\/.*\\.glsl$/", "loader": "webpack-glsl-loader" },
   { "test": "/dependencyA\\/.*\\.glsl$/", "loader": "webpack-glsl-loader" }
  ]
 }
}
```

(The documentation should strongly encourage extension authors to include their module name in the test to avoid one configuration from affecting that of other extensions.)

See also: #2835 and #3743.

**Comment by vidartf** [comment]
PS: jupyterlab would need to add any loaders specified to dev-dependencies, and add the rules to the webpack config.

**Comment by saulshanabrook** [comment]
One way to do this without modifying jupyterlab core would be to build your extension with webpack before publishing it. Do you think this would work?

If you think it would, maybe having an example of this in one of the starter repos might be helpful.

**Comment by vidartf** [comment]
Pre-building prevents dependency de-depulication, which is core to the jupyterlab build process, as I understand it.

**Comment by saulshanabrook** [comment]
Using the [`externals`](https://webpack.js.org/guides/author-libraries/#externalize-lodash) keyword in Webpack allows you to keep some imports as imports and not inline them in the build.

I am also experimenting with [rollup](https://github.com/rollup/rollup) for one extension, that takes the opposite approach of not inlining anything unless it is included.

**Comment by saulshanabrook** [comment]
Another solution to try would be to [be explicit about what loader you want in the require/import statement](https://webpack.js.org/concepts/loaders/#inline). I think if you include the loader in your regular dependency, then the jupyterlab build should be able to use this loader. If you are using typescript, the other trick is you need to manually type the module that is returned from the loader, [like we did with the file loader](https://github.com/jupyterlab/jupyterlab-monaco/pull/3/files#diff-9f428373eb898929e3cbf3cd2cf5c8cb).


We recently switched jupyterlab-monaco to use this approach and it seems to be working in my preliminary tests. I am curious to see if this approach would work for you as well.

**Comment by jasongrout** [comment]
@saulshanabrook's solution comes with the huge bold disclaimer that webpack is considered an implementation detail for the jlab packaging process, not part of our official api, so we might change to use another bundler at any time, and it's up to you to update your code.

**Comment by vidartf** [comment]
> Another solution to try would be to be explicit about what loader you want in the require/import statement. 

Again, this doesn't work if a third-party dependency requires loaders in order to integrate with lab. C.f. vtk.js case mentioned above.

> webpack is considered an implementation detail for the jlab packaging process

Which would be fine if JS import/bundling wasn't as fragmented/complicated as it is. I'd rather have an escape hatch with a big warning that it is likely to change on major releases.

**Comment by jasongrout** [comment]
> Which would be fine if JS import/bundling wasn't as fragmented/complicated as it is. I'd rather have an escape hatch with a big warning that it is likely to change on major releases.

Sure, I understand. I realize it's a bit of a fine line we're walking here, and may need to be reevaluated as our understanding increases.

**Comment by saulshanabrook** [comment]
> Again, this doesn't work if a third-party dependency requires loaders in order to integrate with lab. C.f. vtk.js case mentioned above.

Ah yes, very true!

**Comment by SimonBiggs** [comment]
This is definitely a hard problem. I'd be interested to hear how the rollup experiments went. I imagine as time goes on this extension authoring process will become quite polished. I personally am very happy to be playing around in the extension author alpha of jupyterlab. Full well knowing that all bets are off until 1.0.0.

**Comment by vidartf** [comment]
For unray, I've solved this using `webpack-node-externals`: https://github.com/vidartf/unray/pull/42/files#diff-69efad4a1399d8cd8a26a3771ae156df

For cases when dependencies require loaders (like vtk.js), this can then be solved by whitelisting it for inclusion. This will however prevent jupyterlab from de-duping the included dependency, so I still do not think this solution is ideal.

**Comment by thewtex** [comment]
I also am developing [an extension based on vtk.js](https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets), and I have been looking for a way to use the required custom webpack rules and plugins for JupyterLab.

I will try the `webpack-node-externals` workaround suggested by @vidartf ...

**Comment by thewtex** [comment]
The approach suggested by @vidartf and @saulshanabrook worked! :clap: 

I ran into another issue, though. For the Jupyter Notebook widget, I used the webpack copy plugin to copy static assets (WebAssembly files and web workers), which are loaded dynamically, when needed. As WebAssembly becomes more pervasive in scientific applications, the need for this will increase. While WebAssembly and web workers can technically be bundled with webpack, often I don't think it is desirable. And there are likely other similar cases where it is desirable not to bundles static assets. So, another need is the ability to specify static assets that get copied into the JupyterLab application `static` folder. Is this supported or planned to be supported?

**Comment by saulshanabrook** [comment]
> So, another need is the ability to specify static assets that get copied into the JupyterLab application static folder. Is this supported or planned to be supported?

Sounds like this could be a job for [`file-loader`](https://github.com/webpack-contrib/file-loader)? With that, I believe you would pre-generate any static files you wanted. Then, you would import them with that loader and get back a URL to their location when the application is built. Then you could do whatever you want with that URL (like fetch it). Have you tried that?

**Comment by thewtex** [comment]
@saulshanabrook Maybe file-loader could work in some cases, but it would require undesirable hacking -- they are not 'static' build time paths.

**Comment by saulshanabrook** [comment]
Could you elaborate a bit on your use case? What kinds of paths are they? The monaco editor uses the `file-loader` strategy to get links to load files in a webwork: https://github.com/jupyterlab/jupyterlab-monaco/blob/4f4554f8c8f175a248549485988a3143f7bd0689/src/index.ts#L56:45

It pre-builds those file with webpack.

**Comment by jtpio** [comment]
FYI, rc7 is now out and make it possible for extension authors to specify a custom webpack config for their federated extension:

- https://github.com/jupyterlab/jupyterlab/pull/9224
- https://github.com/jupyterlab/jupyterlab/issues/9175

Even though this only applies to federated extensions, maybe this is enough to address what is mentioned in this issue?

Also for reference here is an example of a federated extension using a custom webpack config: https://github.com/jtpio/jupyterlab-wasm-example
