### ISSUE TITLE
Extend Jupyterlab FileBrowser Context Menu

### ISSUE THREAD

**Issue by BrentDorsey** [jupyterlab/jupyterlab#4332]
Business Requirement:
* Ability to extend the default jupyterlab file browser right click context menu adding custom items to the menu: `menu.addItem`
* Right click selected files/directories in the jupyterlab file browser and select a custom action from the context menu.  Example:  POST files to an external REST API

**Comment by ian-r-rose** [comment]
Hi @BrentDorsey, this is a duplicate of #3994. Can we continue the discussion there?

**Comment by BrentDorsey** [comment]
yes of course.  thanks for the pointer.
