### ISSUE TITLE
Enable extensions based on Angular and using Angular templates to build

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#4336]
Angular has a few specific requirements for its webpack configuration. To be able to allow plugins that make use of Angular some additions to the staging webpack would be required.

**Comment by saulshanabrook** [comment]
#4328 raises a similar need to add a loader.

**Comment by saulshanabrook** [comment]
Closing this since we now link to https://github.com/SimonBiggs/scriptedforms/blob/master/scriptedforms/docs/create-your-own-angular-jupyterlab-extension.md#create-your-own-angular-jupyerlab-extension in the docs to show how to build an angular extension. Please comment if you would like this to stay open

**Comment by SimonBiggs** [comment]
For the most recent version of JupyterLab I haven't managed to get ScriptedForms to work as an extension unfortunately. It appears Angular doesn't like having its target set to es6. I haven't dived too much further into it for now.

**Comment by SimonBiggs** [comment]
I think until the JupyterLab extension method stabilises I might make ScriptedForms not be an extension proper and just keep it in standalone mode.

I'll let you know if that's the path I go down and I'll submit a pull request removing the link to ScriptedForms within the JupyterLab docs.

**Comment by saulshanabrook** [comment]
Sounds good.

**Comment by jasongrout** [comment]
Note that es6 is not a requirement for extensions. We've set the core extensions to generate es6, but other extensions can still be es5.

**Comment by SimonBiggs** [comment]
Oh? Okay, O was getting an error when inside JupyterLab when I wasn't
setting to es6. Struggling to remember now, but it was something like
"referencing self".

**Comment by ian-r-rose** [comment]
@jasongrout That's not strictly true. If extensions derive from any of our classes, they must be ES6. Otherwise it runs afoul of the difference between old-style JS classes and new-style JS classes.
