### ISSUE TITLE
Feature discussion: Ability to link relative to `/` instead of `/files/`?

### ISSUE THREAD

**Issue by consideRatio** [jupyterlab/jupyterlab#4341]
It might make sense to support links relative to `/` as compared to `/files/` somehow, I don't know how we can go about that though...

> [...] I imagine there might be a way to embed command invocation as links - but just like before, that would be very specific about running in the jlab interface (before, that link was very specific and would only work in the notebook interface by accident...)
> // @jasongrout on Gitter 

### Link behavior

Link | JupyterHub @ https://jupyter.se | No-hub @ localhost
-|-|-
__Classic__ | | 
`/terminals/1` | `https://jupyter.se/terminals/1` | `https://localhost/terminals/1`
`/hub/admin` | `https://jupyter.se/hub/admin` | `https://localhost/hub/admin`
__Lab__ | | 
`/terminals/1` | `https://jupyter.se/user/erik/files/terminals/1` | `https://localhost/files/terminals/1`
`/hub/admin` | `https://jupyter.se/user/erik/files/hub/admin` | `https://localhost/files/hub/admin`

---

**Comment by jasongrout** [comment]
There's a lot of discussion about this at #5211. Let's move this discussion over there to consolidate.
