### ISSUE TITLE
Kernel restarts no matter if I click 'restart' or 'cancel'

### ISSUE THREAD

**Issue by madcarrot** [jupyterlab/jupyterlab#4343]
This only happens when I use **`Restart Kernel and Run All Cells`**. **`Restart Kernel`** works fine.

![image](https://user-images.githubusercontent.com/3460073/38519328-85aedbe4-3c0d-11e8-94d9-c7eb08ff2287.png)

Jupyter Lab restarts the kernel and runs all the cells no matter if I click cancel or restart... Not sure if it's something specific to my set up.

I'm running `jupyterlab 0.31.12` on Chrome.

**Comment by manuhortet** [comment]
Same problem here. Using same version on Firefox.

Moreover, this happens using **both** `Restart Kernel and Run All Cells` and `Restart Kernel and Clear All Outputs` (the confirmation dialog appears but is useless)

**Comment by manuhortet** [comment]
It's true that #3703 takes #3999 as solved, but I'm still getting the error running on #3703 (which btw is already merged with master), so I guess this is a current a problem. Maybe @ian-r-rose can confirm this?

**Comment by ian-r-rose** [comment]
This is not in any released packages, but if you run in `--dev-mode`, which serves on the unreleased packages, it has the correct behavior.

**Comment by ian-r-rose** [comment]
We have released v0.32rc0 and will cut the final release tomorrow. Closing as fixed, but feel free to comment if it is not resolved for you.
