### ISSUE TITLE
Failed to compile (tsc) notebook-extension

### ISSUE THREAD

**Issue by BoPeng** [jupyterlab/jupyterlab#4358]
Not sure if this is a real bug but when I try to modify [notebook-extension](https://github.com/jupyterlab/jupyterlab/tree/master/packages/notebook-extension), `tsc` shows

```
~/jupyterlab-dev/jupyterlab/packages/notebook-extension (master)]$ tsc
src/index.ts(1716,36): error TS2352: Type '{ tracker: INotebookTracker; noun: string; run: (current: NotebookPanel) => Promise<any>; runAll:...' cannot be converted to type 'ICodeRunner<NotebookPanel>'.
  Types of property 'restartAndRunAll' are incompatible.
    Type '(current: NotebookPanel) => Promise<IKernelConnection>' is not comparable to type '(widget: NotebookPanel) => Promise<void>'.
      Type 'Promise<IKernelConnection>' is not comparable to type 'Promise<void>'.
        Type 'IKernelConnection' is not comparable to type 'void'.
```
The error seems to be caused by the `      .then(() => void 0);` statement [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook-extension/src/index.ts#L1722).

BTW, do I need to `npm install` and `jupyter labextension install` after I modify a jupyterlab system package? I tried `jlpm install` but it did not work.

**Comment by BoPeng** [comment]
Yes, I followed the instructions and compiled jupyterlab with `jlpm` etc and jupyterlab runs, this is why I do not understand why `tsc` under `notebook-extension` fails.

I am working on this [runInConsole pull request](https://github.com/jupyterlab/jupyterlab/pull/4330) and I will try `--dev-mode --watch` option.

**Comment by ian-r-rose** [comment]
@BoPeng Sorry to let this languish, did you ever figure this out?

**Comment by BoPeng** [comment]
I was trying to run `tsc` on an individual package and it did not work. I was able to compile JupyterLab from the top directory and use `--dev-mode` to debug my module later. So I guess compiling individual package was not supposed to work.

**Comment by ian-r-rose** [comment]
They *should* all be individually compile-able, but the dependencies need to be pointing to the versions of the packages in the lerna tree (rather than the published ones). Is it possible you had run `jlpm install` on the individual package, which then pulled in the old versions of its dependencies?

**Comment by BoPeng** [comment]
I was learning and tried all sort of things, including `jlpm install` so it is quite possible that the dependencies were wrong. I closed the ticket because there is no real need to compile individual packages and we have more important things to work on.
