### ISSUE TITLE
Detect memory leaks

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#4359]
I recently talked to one of the researchers behind the [BLeak: Automatically Debugging Memory Leaks in Web Applications](https://github.com/plasma-umass/BLeak) project. It let's you define some state transitions for a web application and detect what memory was allocated that hasn't been reclaimed when you go back to the starting state.

For example, repeatedly opening a notebook, then closing it and stopping the server shouldn't grow the memory consumption. Same with creating and deleting a cell.

With this project, we could write tests for those things and see if we have memory leaks and try to find where they are coming from.

As a very simple first test, I just opened the Memory tab of the chrome debugger and saw that it went from 20MB up to like 60MB, increasing after I opened and closed the same notebook multiple times.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/cripplingly-slow-ui-am-i-the-only-one/5351/6

**Comment by fcollonval** [comment]
Works started at https://github.com/jupyterlab/benchmarks/pull/100
