### ISSUE TITLE
Enable scrolling for Output View tabs

### ISSUE THREAD

**Issue by stephenholtz** [jupyterlab/jupyterlab#4360]
For long printed outputs (e.g. printing on every iteration of a process) the view tab is not particularly useful. Would it be straightforward to add scrolling to these views similarly to how enabling and disabling scrolling is possible in the main notebook? 

Even better, when the output view is created I think it should automatically add scrolling behavior if required.

**Comment by waio1990** [comment]
Apparently this was already fixed in a merged PR, however there has not been any releases in a month. Once that releases I'd guess itll be fixed.

**Comment by stephenholtz** [comment]
@waio1990 thank you for the note, I just missed that. Closing now

**Comment by jasongrout** [comment]
FYI, we just released the RC for the next beta.
