### ISSUE TITLE
Command window should sort by length

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#4362]
I think the command window should sort its commands by length (shortest to longest). This would mean that for commands that share some of the same starting text (e.g. "Run All Cells" and "Run All Above Selected Cell"), the more generic one is favored.

Right now, if I open the command window and type "Run all", two different behaviors happen:

1. If I'm in the first cell, the first option is "Run All Cells".
2. If I'm in anything other than the first cell, the first option is "Run All Above Selected Cell".

I think sorting by length would solve this!

**Comment by sccolbert** [comment]
Search results are sorted by the strength of the fuzzy match. We spent quite a long time trying to come up with an algorithm that worked across a wide variety of cases. Simply sorting by length might work well for this one particular case, but not well for other cases.

**Comment by sccolbert** [comment]
Since the match is fuzzy, you can type `ruac` to get `run all cells`:

![capture](https://user-images.githubusercontent.com/137289/38632303-ee95830e-3d81-11e8-848a-f8f03e7bf629.PNG)

**Comment by sccolbert** [comment]
At one point, we also favored early-character matches in separate words, but that didn't work well for a number of cases I can't recall, so we landed on what we have now. 

I'm certainly willing to improve the fuzzy scoring logic, but it will take some thought to make it all-around better than what we have.

**Comment by sccolbert** [comment]
Here's the current fuzzy search logic:
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/commandpalette.ts#L1137

**Comment by choldgraf** [comment]
@sccolbert that's a fair point...I guess that "fuzzy" things in general will never be 100% satisfying all of the time, so I am OK to keep it as-is. Shall I close this? (or feel free to close yourself)

**Comment by sccolbert** [comment]
If you think the issue is not glaring enough to warrant improving the fuzzy search, then I'd say close it. Otherwise, we can re-title it to something more appropriate.

**Comment by choldgraf** [comment]
I think we can close it - in my mind this was a "worth doing if it's an easy win" issue, but not a glaring problem. Thanks for following up :-)
