### ISSUE TITLE
Release Feedback and Possible Automation for Reproducibility

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#4368]
@ian-r-rose @afshin @jasongrout 

Let's use this issue to discuss how we can improve our release process based on the latest release

**Comment by jzf2101** [comment]
In the `RELEASE.md` you mean? @jasongrout

**Comment by jasongrout** [comment]
Yes, I remember us talking about adding instructions to the release md file about either cleaning a repo, or about cloning a fresh repo before starting the process.

**Comment by jzf2101** [comment]
I agree, you have similar instructions in the ipywidgets release process correct?

**Comment by jzf2101** [comment]
See #4377
