### ISSUE TITLE
jupyter lab starting with an error !!! what to do ?

### ISSUE THREAD

**Issue by anirbanhdesk** [jupyterlab/jupyterlab#4369]
[I 09:20:54.015 LabApp] The port 8888 is already in use, trying another port.
[I 09:20:54.016 LabApp] The port 8889 is already in use, trying another port.
[I 09:20:54.017 LabApp] The port 8890 is already in use, trying another port.
[I 09:20:54.018 LabApp] The port 8891 is already in use, trying another port.
[W 09:20:54.289 LabApp] Terminals not available (error was DLL load failed: %1 is not a valid Win32 application.)
[I 09:20:54.308 LabApp] JupyterLab beta preview extension loaded from C:\Users\jones\Anaconda3\lib\site-packages\jupyterlab
[I 09:20:54.308 LabApp] JupyterLab application directory is C:\Users\jones\Anaconda3\share\jupyter\lab
[I 09:20:54.480 LabApp] Serving notebooks from local directory: C:\Users\jones
[I 09:20:54.481 LabApp] 0 active kernels
[I 09:20:54.481 LabApp] The Jupyter Notebook is running at:
[I 09:20:54.481 LabApp] http://localhost:8892/?token=be5554ba97e4d20efc40907305f1ce62622657252b972e8e
[I 09:20:54.481 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:20:54.484 LabApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8892/?token=be5554ba97e4d20efc40907305f1ce62622657252b972e8e
[I 09:20:54.624 LabApp] Accepting one-time-token-authenticated connection from ::1
[I 09:20:56.666 LabApp] Build is up to date

**Comment by jasongrout** [comment]
What is the error? The terminal not being available? IIRC, that's expected on Windows.

**Comment by anirbanhdesk** [comment]
Thanks for adding, I figured it out, the Cuda toolkit v9.1 for windows I guess is buggy, after updating from v9.0 jupyter labs, tensorflow env was not working, tried everything, at last, worked after I rolled back to v9.0 again. The Navigator version 1.8.2 is a mess too!

**Comment by jasongrout** [comment]
Great, thanks for following up here too.
