### ISSUE TITLE
Type annotations in autocomplete not working in v0.32.0rc0

### ISSUE THREAD

**Issue by cfriedline** [jupyterlab/jupyterlab#4371]
Notced this today. Spoke with @ian-r-rose on gitter, who suggested opening this issue.

<img width="267" alt="autocomplete" src="https://user-images.githubusercontent.com/3664445/38690424-1377c93c-3e4c-11e8-99ea-7c62dee80a54.png">

appnope==0.1.0
backcall==0.1.0
bleach==2.1.3
certifi==2018.1.18
decorator==4.2.1
entrypoints==0.2.3
html5lib==1.0.1
ipykernel==4.8.2
ipython==6.3.1
ipython-genutils==0.2.0
ipywidgets==7.2.0
jedi==0.11.1
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.32.0rc0
jupyterlab-launcher==0.10.5
MarkupSafe==1.0
mistune==0.8.3
mkl-fft==1.0.0
mkl-random==1.0.1
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.4.1
numpy==1.14.2
pandas==0.22.0
pandocfilters==1.4.2
parso==0.1.1
pexpect==4.4.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
python-dateutil==2.7.2
pytz==2018.3
pyzmq==17.0.0
qtconsole==4.3.1
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
terminado==0.8.1
testpath==0.3.1
tornado==5.0.2
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.2.0

**Comment by cfriedline** [comment]
Seems to be failing in 0.31.12, as well.

**Comment by saulshanabrook** [comment]
@cfriedline Can you try upgrading `ipykernel` to see if that helps?

**Comment by jasongrout** [comment]
It looks like they have the latest ipykernel, 4.8.2.

**Comment by ian-r-rose** [comment]
I think it might actually be on the IPython side. I can now reproduce this. I am getting the experimental types map in the completion response, but it is empty. Not sure what is going on, but it's not ipykernel.

**Comment by ian-r-rose** [comment]
I wonder if it is a regression in IPython. I used to have working typemaps, and now I don't.

**Comment by ian-r-rose** [comment]
It looks like this is a change to IPython. In ipython/ipython#11076 Jedi, which provides the type annotations for IPython, was disabled by default due to other regressions. I think the plan is to re-enable it once those things are fixed, but in the meantime, if you want to enable type annotations, you can set `c.Completer.use_jedi = True` in an [`ipython_config.py`](http://ipython.readthedocs.io/en/stable/development/config.html) file.

Keeping this open until we can document it in the JupyterLab docs.

**Comment by stonebig** [comment]
the updated jedi-0.120 version has been released 16 days ago.
