### ISSUE TITLE
Release plans for 0.32

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4377]
This is to coordinate any release work.

Updates for extension repos:
- [x]    https://github.com/jupyterlab/extension-cookiecutter-js - no update needed
- [x]    https://github.com/jupyterlab/extension-cookiecutter-ts https://github.com/jupyterlab/extension-cookiecutter-ts/pull/35
- [x]    https://github.com/jupyterlab/mimerender-cookiecutter - no update needed
- [x]    https://github.com/jupyterlab/mimerender-cookiecutter-ts - no update needed
- [x]    https://github.com/jupyterlab/jupyter-renderers https://github.com/jupyterlab/jupyter-renderers/pull/126
- [x]    https://github.com/jupyterhub/jupyterlab-hub https://github.com/jupyterhub/jupyterlab-hub/pull/53

Examples to check:
- [x] check https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/notebook.rst#adding-a-button-to-the-toolbar
- [x] check xkcd tutorial: https://github.com/jupyterlab/jupyterlab_xkcd/tree/0.32 #4391
  - clone repo
  - checkout new 0.32 branch
  - update tutorial to involve adding packages to package.json
  - fix the commits at the bottom of the branch, rebase to create the new 0.32 branch
  - tag each level appropriately

- [ ] Mailing list announcement
- [x] Update binder

**Comment by jasongrout** [comment]
I'm seeing a bit of an issue with ipywidgets because of this deletion: https://github.com/jupyterlab/jupyterlab/commit/d6b859ad13c3cd719eacbdc7020c5c5fed48ddc8#diff-e88b12e4decee829241977f3adeb539dL57

screenshot:

<img width="411" alt="screen shot 2018-04-12 at 6 13 02 pm" src="https://user-images.githubusercontent.com/192614/38711884-36fa3a94-3e7d-11e8-824c-f7654fcdcdcf.png">

Arguably it's the widget's fault. However, since before the output area stretched across the notebook, but now only fills the space taken, that may affect other things too.

**Comment by jasongrout** [comment]
(I think for the same reason, tabs are also small, etc:
<img width="651" alt="screen shot 2018-04-12 at 6 15 37 pm" src="https://user-images.githubusercontent.com/192614/38711969-9aea97ce-3e7d-11e8-87b8-710578fce05e.png">

**Comment by robmarkcole** [comment]
After attempting install on my windows machine I run into an error:
```
      File "c:\programdata\anaconda3\lib\subprocess.py", line 291, in check_call

        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\program files\\nodejs\\node.ex
e', 'C:\\Users\\RCole\\Python\\jupyterlab-master\\jupyterlab\\staging\\yarn.js']
' returned non-zero exit status 1.

    ----------------------------------------
  Rolling back uninstall of jupyterlab
```
On then attempting to run my (rolled back) jupyterlab I get the error:
```
  File "c:\programdata\anaconda3\lib\site-packages\jupyterlab\commands.py", line
 1389, in _get_core_data
    with open(pjoin(HERE, 'staging', 'package.json')) as fid:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\programdata\\anacon
da3\\lib\\site-packages\\jupyterlab\\staging\\package.json'
```
And I am unable to use jupyterab. My colleague @OxygenLithium has the same problem I believe.

**Comment by jasongrout** [comment]
@robmarkcole - the first time, were you just upgrading jupyterlab using pip?

**Comment by robmarkcole** [comment]
@jasongrout no, I was using `python setup.py` install with the .zip files, our firewall means pip often fails even when using a proxy

**Comment by jasongrout** [comment]
ah, okay - just checking to see if we needed to do something about your error.

**Comment by jasongrout** [comment]
I think in general, the advice these days is to use `pip install` with the zip files, not `python setup.py` directly.

**Comment by jasongrout** [comment]
After #4376, we need to release a new RC with codeeditor bumped appropriately. I'll do that now.

**Comment by jasongrout** [comment]
I just published all of the npm packages for 0.32.0rc1, including bumping codeeditor to 0.16.0.

**Comment by jasongrout** [comment]
I just published a patch bump for apputils after #4386.

**Comment by jasongrout** [comment]
Okay, I *think* we are ready to publish, once my two open PRs are merged. Can one or two people confirm? @ian-r-rose, @afshin, @ellisonbg, or any others that have been testing?

**Comment by jasongrout** [comment]
I released 0.32.0 to pypi: https://github.com/jupyterlab/jupyterlab/releases/tag/v0.32.0. The conda-forge PR is https://github.com/conda-forge/jupyterlab-feedstock/pull/107.

**Comment by ian-r-rose** [comment]
* Add release notes and update the changelog.

**Comment by ellisonbg** [comment]
+1
