### ISSUE TITLE
Custom welcome message

### ISSUE THREAD

**Issue by gsemet** [jupyterlab/jupyterlab#4382]
Can jupyterlab (or is it possible through a plugin) display a custom spash screen / welcome message upon startup, to give user some advices about how to use jupyterlab. I am thinking of a way to tell newbie:
- dear windows user, do not use Ctrl+C/Ctrl+V for copy paste, use Ctrl+Insert, Shift+Insert 
- do not use Ctrl+W on the terminal. your browser will close the whole page.

I am thinking of a centererd dialog box with only a "close button" (maybe a "do not show again") and a Markdown content.

Thanks

**Comment by ian-r-rose** [comment]
Hi @gsemet, this should be fairly straightforward for a third-party-plugin. You can create a new dialog, and show it in a callback for the `app.restored` promise.

**Comment by fcollonval** [comment]
You will find an example there:
https://gitlab.com/ENKI-portal/jupyterlab_enkiintro

**Comment by ian-r-rose** [comment]
Closing as answered, feel free to let us know if this isn't enough to get you started @gsemet, and thanks for the example @fcollonval
