### ISSUE TITLE
Jupyterlab creates and runs an event loop in the main thread, thus preventing running notebooks with async functions

### ISSUE THREAD

**Issue by roman-kh** [jupyterlab/jupyterlab#4399]
Jupyterlab creates and runs an event loop in the main thread, thus preventing running notebooks with ``async`` functions.

A minimal example to run in a cell:
```python
import asyncio

async def an_async_fn():
    await asyncio.sleep(1)
    
loop = asyncio.get_event_loop()

loop.run_until_complete(an_async_fn())
```
It throws an exception
```sh
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-884c113962ed> in <module>()
      6 loop = asyncio.get_event_loop()
      7 
----> 8 loop.run_until_complete(an_async_fn())

/usr/lib/python3.5/asyncio/base_events.py in run_until_complete(self, future)
    373         future.add_done_callback(_run_until_complete_cb)
    374         try:
--> 375             self.run_forever()
    376         except:
    377             if new_task and future.done() and not future.cancelled():

/usr/lib/python3.5/asyncio/base_events.py in run_forever(self)
    338         self._check_closed()
    339         if self.is_running():
--> 340             raise RuntimeError('Event loop is running.')
    341         self._set_coroutine_wrapper(self._debug)
    342         self._thread_id = threading.get_ident()

RuntimeError: Event loop is running.
```
It works perfectly in 0.31.2, but breaks in 0.31.12 (haven't checked the intermediate versions).

**Comment by timkpaine** [comment]
You need to attach things to the loop, or create a new instance.

**Comment by roman-kh** [comment]
Could you please elaborate more on this?

The example shown above works perfectly in pure Python, in Jupyter Notebook and Jupyter Lab 0.31.2.

It also complies with the official Python documentation. You might want to try and run the code from [https://docs.python.org/3](https://docs.python.org/3/library/asyncio-eventloop.html#hello-world-with-call-soon):
```python
import asyncio

def hello_world(loop):
    print('Hello World')
    loop.stop()

loop = asyncio.get_event_loop()

# Schedule a call to hello_world()
loop.call_soon(hello_world, loop)

# Blocking call interrupted by loop.stop()
loop.run_forever()
loop.close()
```
And you will bump into the very same ``RuntimeError: Event loop is running``.

So it seems like a bug in JupyterLab, doesn't it?

**Comment by timkpaine** [comment]
Jupyterlab is front end only, any change would be in ipykernel. Will look in a bit when I get to a computer

**Comment by roman-kh** [comment]
Thank for pointing that out. I think the problem is related to ipython/ipython#11030.

**Comment by timkpaine** [comment]
@roman-kh yeah their workarounds are what I would suggest as well

**Comment by timkpaine** [comment]
@roman-kh feel free to close this issue and follow up on that IPython thread
