### ISSUE TITLE
Overflow of tab completion tips in Jupyter Lab

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4400]
See https://github.com/JuliaLang/IJulia.jl/issues/646

**Comment by Carreau** [comment]
That seem to not be our fault,  though, `A = \gamma<tab>e +`, then pressing `tab`, `space` has this weird effect:

<img width="274" alt="screen shot 2018-04-16 at 14 46 55" src="https://user-images.githubusercontent.com/335567/38836958-0f82cf8e-4185-11e8-8a33-5d4aa121d64c.png">

Not sure why.
