### ISSUE TITLE
some text not going to white in jupyterlab

### ISSUE THREAD

**Issue by afonit** [jupyterlab/jupyterlab#4404]
When I was working on:
https://github.com/jupyterlab/jupyterlab/issues/4384

I noticed that when using the dark theme for jupyterlab the output of:
```
%%javascript
CodeMirror.defaults.cursorBlinkRate=0
```

which returns:
```
JavaScript output is disabled in JupyterLab
```
*Has the text in black* - instead of white.

This is the first inconsistency I have found in the theme with text in jupyterlab - so I thought I would report it as I believe this font should be rendered `white`.

(I call it inconsistent as the outputs come out white as well as the  In[]/Out[] test in the left margin for jupyterlab's dark theme.

**Comment by jtpio** [comment]
This should have been fixed in https://github.com/jupyterlab/jupyterlab/pull/3910 and be part of the `0.32.0` release.

Have you tried to updated JupyterLab to the latest version?
`conda install -c conda-forge jupyterlab`

**Comment by afonit** [comment]
@jtpio ,
thanks, I have been waiting for the windows build since yesterday.
I will test this out once it shows up on:
https://anaconda.org/conda-forge/jupyterlab

**Comment by afonit** [comment]
@jtpio The windows packages are now working.  The text does indeed show up as white now - thank you.

Since jupyterlab is in such early betas I will see if there is a way to build from master and test on there first next time I see an issue.

Thanks again.
