### ISSUE TITLE
confusion about installation using conda

### ISSUE THREAD

**Issue by qingpeng** [jupyterlab/jupyterlab#4412]
About the installation using conda, on the README page , it says using "jupyter serverextension enable.....". https://github.com/jupyterlab/jupyterlab/blob/master/README.md

But on the installation page in the documentation, it says using "conda install -c conda-forge jupyterlab"
http://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html

So which way is preferred? Thanks!

**Comment by jasongrout** [comment]
The readme is wrong. Thanks for noting this!

**Comment by jasongrout** [comment]
In fact, this section in the docs is wrong too: http://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#installing-with-previous-versions-of-notebook - that should note the `serverextension enable` step.

**Comment by jasongrout** [comment]
If you have a current notebook (5.3 or later), you can just do:

`conda install -c conda-forge jupyterlab`

**Comment by jasongrout** [comment]
Fixed by #4420.

**Comment by jasongrout** [comment]
This fix was backported to 0.32, so putting to beta 3 now.
