### ISSUE TITLE
No logout button

### ISSUE THREAD

**Issue by lwshang** [jupyterlab/jupyterlab#4414]
I cannot find a logout button on jupyterlab.
I run a jupyter lab server and set password login. After I log in the lab from another computer's browser, I cannot log out. Even if I quit the browser application. Anyone using the computer can restart the browser and using the lab without entering password. This is a fatal secure issue!

As a reference, in original jupyter notebook, there __is__ a logout button.

**Comment by jasongrout** [comment]
Note that this isn't with JupyterHub, but with the stock jupyterlab.

Here is the logout button in the classic notebook, in the upper right:

<img width="192" alt="screen shot 2018-04-18 at 11 08 19 am" src="https://user-images.githubusercontent.com/192614/38949934-d95068a2-42f8-11e8-84d5-e9b7263a6ffd.png">

**Comment by jasongrout** [comment]
@ian-r-rose - perhaps we should add a new abstract item in the File menu, so jupyerhub can register a 'logout' handler, or we could have a generic logout handler doing whatever the classic notebook does.

**Comment by ian-r-rose** [comment]
Isn't this what the `labhub` extension does?

**Comment by jasongrout** [comment]
This isn't about Hub. This is about the stock notebook or lab. The stock notebook has the notion of authentication, and if you look in the upper right, you'll see that logout button.

**Comment by ian-r-rose** [comment]
Ah, I misunderstood.

**Comment by zgqallen** [comment]
Just development extension to add logout button for Jupyterlab - https://github.com/zgqallen/jupyterlab-logout.

**Comment by jasongrout** [comment]
@zgqallen - thanks!

I think this is an important feature compatibility issue, so should be implemented in JupyterLab core. Would you consider submitting a PR to add a `Logout` item to the File menu?

The code for the File menu entries is here: https://github.com/jupyterlab/jupyterlab/blob/67a6e94a620eb7c3e3198a89a5ec3c3b7d3782fa/packages/mainmenu-extension/src/index.ts#L197

I think basically what is needed is (1) adding a Logout command to the command registry (not sure where this command should go - thoughts @ian-r-rose or others?), and adding a menu item in the above File menu code.

**Comment by ian-r-rose** [comment]
I think it's reasonable to have the command in `@jupyterlab/application-extension`. I am agnostic as to whether it should be a button in the top area or an item in the File menu.

**Comment by jasongrout** [comment]
I would definitely prefer a file menu item over a button - most people I know don't use the button, so I'd rather no have it take up constant space in the UI. We'll probably need to put it in the File menu anyway too.

**Comment by jasongrout** [comment]
I would also put it in the command palette.

**Comment by fperez** [comment]
Quick ping on the status of this? I'm considering deploying Lab more widely to one of my courses, but I'd rather not have the students do manual URL manipulations... I think this issue is actually worth raising in priority if we want to start pushing Lab to Hub-base deployments (in addition to self-installed local users).

Anything I can do to help here?

**Comment by blink1073** [comment]
We merged this today: https://github.com/jupyterlab/jupyterlab/pull/5226.

**Comment by blink1073** [comment]
Fixed by #5226

**Comment by blink1073** [comment]
@fperez, I can do a patch release if you need this asap.

**Comment by blink1073** [comment]
Yeah, it is self contained enough and changes no APIs, I'll release it tomorrow.

**Comment by blink1073** [comment]
Released!

**Comment by fperez** [comment]
Very cool, thanks so much @blink1073!!

**Comment by blink1073** [comment]
Happy to help?

**Comment by itcarroll** [comment]
The File -> Quit entry introduced in #5266 does not appear when using JupyterHub. Is that on purpose? I know the labhub extension exists, but don't want to duplicate a "Quit" button if it is supposed to also come from this addition.

**Comment by blink1073** [comment]
Hi @itcarroll, which version of the notebook package are you using in your JupyterHub environment?  cf https://github.com/jupyterlab/jupyterlab/pull/5280

**Comment by itcarroll** [comment]
jupyter --version => 4.4.0
jupyter lab --version => 0.34.11
jupyter notebook --version => 5.7.0
jupyterhub --version => 0.9.3

**Comment by blink1073** [comment]
And that is the version you see in the launched JupyterLab under help > about?

**Comment by itcarroll** [comment]
That is the version I see under Help > About JupyterLab.
I have not set any configuration (other than jupyterhub_config.py needing `c.Spawner.cmd = ['jupyter-labhub']`). Given that the notebook behind the hub shows a "Control Panel" rather than a "Quit" button, perhaps something about the hub does disable the quit button?

**Comment by vykozlov** [comment]
> Fixed by #5226

Sorry, got lost:
#5226 - is "Quit" functionality, ie. jupyterlab shutdown, how is it related to "logout", when I do *not* want to shutdown?

Do I get this right that "Logout" button is *not* in the core, but only as extension from zgqallen / jupyterlab-logout ?

BTW, I install jupyterlab as 
pip install jupyter jupyterlab
ver. 0.35.4
I have no "Quit" button in the file menu either.

**Comment by nils-werner** [comment]
> I have no "Quit" button in the file menu either.

[You need to start JupyterLab using `jupyter lab --LabApp.quit_button=True`](https://github.com/jupyterlab/jupyterlab/issues/5965#issuecomment-461858815) for the button to appear.
