### ISSUE TITLE
random kernel restart

### ISSUE THREAD

**Issue by jsevo** [jupyterlab/jupyterlab#4415]
during a join of two pandas data frames like so:

`d1.join(d2.set_index('someindex').somecolumn, on='sharedfeature', how='left')`

the kernel restarts. no error shown in notebook. terminal print:

`KernelRestarter: restarting kernel (1/5), keep random ports
kernel 1231233-12-4bf2-9ad3-3333312 restarted`

**Comment by jasongrout** [comment]
Does this exact same case work in the classic notebook? A kernel restart like this indicates it may be a backend problem, for example running out of memory or something.

**Comment by jsevo** [comment]
I will check right now.

**Comment by jasongrout** [comment]
Could be - or maybe the way things are done, you're running out of memory? I'd suggest posting to the pandas mailing list or creating an issue there. I'll close this issue as resolved
