### ISSUE TITLE
Kernel Message Log widget

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4423]
Right now, in order to debug kernel messages, you have to go to developer tools and click through a lot of windows to get a not-very-nicely formatted version of a message. It would be great if there was a widget that could connect to an existing kernel and log all messages from the kernel (bonus if it could also log messages *to* the kernel). This message log could be a highly-customized display that makes it easy to see the messages at a high level (e.g., prominently displaying the message type for each message), while still being able to drill down to see the full content of a specific message. Also, this message log could handle messages that were sent as binary messages (which are close to impossible to sort out in the websocket frame inspector in the browser dev tools).

CC @ivanov

**Comment by vidartf** [comment]
I have some similar code for this in python, so I'll give this a go. If I don't report anything for more than a week, consider this claim as expired 😅

**Comment by jasongrout** [comment]
Such a widget would likely use a message hook to listen in on all iopub messages: https://github.com/jupyterlab/jupyterlab/blob/a1274a8d50c0e17a953d4eb8ef965b586d245054/packages/services/src/kernel/kernel.ts#L347

**Comment by vidartf** [comment]
Initial work here: https://github.com/vidartf/jupyterlab-kernelspy
A bit of a hack now as I [monkey patch on some new Signals](https://github.com/vidartf/jupyterlab-kernelspy/blob/f5ab7ce2d4127b11de2df078ece3cb45335c8cd0/src/model.ts#L61-L78), but the plan is to make a PR to lab to add those signals (minor release of `@jupyterlab/services`).

**Comment by jasongrout** [comment]
What about shell message replies, like execute_reply? Or input replies?

Or perhaps a kernel should have both an iopub message hook, and an *all* message hook, that triggers on *all* messages in and out.

**Comment by vidartf** [comment]
As far as I can tell that extension captures all communication on all channels?

**Comment by vidartf** [comment]
> an all message hook, that triggers on all messages in and out.

That's probably the best low-level hook. There are a few relevant questions:
- At what time should the event fire?
- Should it allow for modification of message content (i.e. should it pass original message, or copy)?

I'll implement it after the pattern of the iopub message signal:
- After synchronous handling, but not waiting for async handling to complete.
- Original message is passed. Behavior is undefined if message is modified during signal handling.

**Comment by vidartf** [comment]
Proposed implementation in #4437.

**Comment by vidartf** [comment]
Released a working concept as `jupyterlab-kernelspy` on npm. It currently doesn't handle restarting/changing kernels, due to its monkey-patching for #4437, but otherwise it seems to work. It's currently missing the option to inspect the actual content of a binary buffer, but at least it shows the presence of the buffers.

**Comment by jasongrout** [comment]
> I'll implement it after the pattern of the iopub message signal:
> 
>     After synchronous handling, but not waiting for async handling to complete.

Be aware that we are going to do an audit of message handling, and all message handling will be asynchronous (since if any message handling is asynchronous, it forces all message handling to be asynchronous to maintain the order of message processing).

See #4188.

**Comment by ian-r-rose** [comment]
Since #4437 has been merged, and @vidartf has published `jupyter-kernelspy`, I think this can be closed. Thanks @vidartf!
