### ISSUE TITLE
Keyboard shortcuts for headings have wrong command names

### ISSUE THREAD

**Issue by logstar** [jupyterlab/jupyterlab#4428]
In `jupyterlab/packages/shortcuts-extension/schema/plugin.json`, keyboard shortcut `1-6` are registered with commands `change-`**`to-cell`**`-heading-X`, whereas the commands in `jupyterlab/packages/notebook-extension/src/index.ts` are named `change-`**`cell-to`**`-heading-X`. As a result, the keyboard shortcuts are not working. Correcting the keyboard shortcut command names would fix this problem. 

I have jupyter lab version 0.31.12. I added custom keyboard shortcuts with correct command names, and the shortcuts worked.

Following are the overrides I added in `Settings -> Advanced Settings Editor -> Keyboard Shortcuts -> User Overrides`:

```
{
    "notebook:change-to-cell-heading-1": {
      "command": "notebook:change-cell-to-heading-1",
      "keys": [
        "1"
      ],
      "selector": ".jp-Notebook:focus"
    },

    "notebook:change-to-cell-heading-2": {
      "command": "notebook:change-cell-to-heading-2",
      "keys": [
        "2"
      ],
      "selector": ".jp-Notebook:focus"
    },

    "notebook:change-to-cell-heading-3": {
      "command": "notebook:change-cell-to-heading-3",
      "keys": [
        "3"
      ],
      "selector": ".jp-Notebook:focus"
    },

    "notebook:change-to-cell-heading-4": {
      "command": "notebook:change-cell-to-heading-4",
      "keys": [
        "4"
      ],
      "selector": ".jp-Notebook:focus"
    },

    "notebook:change-to-cell-heading-5": {
      "command": "notebook:change-cell-to-heading-5",
      "keys": [
        "5"
      ],
      "selector": ".jp-Notebook:focus"
    },

    "notebook:change-to-cell-heading-6": {
      "command": "notebook:change-cell-to-heading-6",
      "keys": [
        "6"
      ],
      "selector": ".jp-Notebook:focus"
    }
}
```

Some other overrides I am using:

```
{
    // In view mode, use `ctrl-r` to run cell without selecting
    // the next cell.
    "notebook:run-cell-1": {
      "command": "notebook:run-cell",
      "keys": [
        "Ctrl R"
      ],
      "selector": ".jp-Notebook:focus"
    },
    // In view mode, use `r` to run cell and select
    // the next cell.
    "notebook:run-cell-and-select-next": {
      "command": "notebook:run-cell-and-select-next",
      "keys": [
        "R"
      ],
      "selector": ".jp-Notebook:focus"
    },
    // Remove default `r` mapping.
    "notebook:change-cell-to-raw": {
      "command": "notebook:change-cell-to-raw",
      "keys": [
      ],
      "selector": ".jp-Notebook:focus"
    },
    // In view mode, use `i` to edit selected cell.
    "notebook:enter-edit-mode": {
      "command": "notebook:enter-edit-mode",
      "keys": [
        "I"
      ],
      "selector": ".jp-Notebook:focus"
    },
    // Remove `i-i` mapping to interrupt kernel.
    // Not sure if this really removes the mapping,
    // but the previous one works.
    "kernelmenu:interrupt": {
      "command": "kernelmenu:interrupt",
      "keys": [
      ],
      "selector": "[data-jp-kernel-user]:focus"
    },
    // Remove `0-0` mapping to restart kernel.
    // This works, but not sure how exactly. 
    "kernelmenu:restart": {
      "command": "kernelmenu:restart",
      "keys": [
      ],
      "selector": "[data-jp-kernel-user]:focus"
    },
    //
    "notebook:insert-cell-above": {
      "command": "notebook:insert-cell-above",
      "keys": [
        "Shift O"
      ],
      "selector": ".jp-Notebook:focus"
    },
    //
    "notebook:insert-cell-below": {
      "command": "notebook:insert-cell-below",
      "keys": [
        "O"
      ],
      "selector": ".jp-Notebook:focus"
    }
}
```

**Comment by jasongrout** [comment]
Thanks! Would you mind submitting a PR for this? It sounds like you've tracked the problem down completely.

**Comment by jasongrout** [comment]
For now, I would change the names of the commands, and then add new commands with the old names pointing to the new commands (so we have both the new commands and the old commands). That way, it's not a breaking change for now, and in 0.33 we delete the old command names and note it in the release notes.

**Comment by jasongrout** [comment]
I misunderstood. Actually, changing the command names in the shortcuts should just fix things and not cause other problems. We should probably also change the shortcut names as well, but we can do that when we release 0.33, since that is possibly a backwards-incompatible change if someone had overridden those particular shortcut names.

**Comment by logstar** [comment]
Thank you for paying attention to this issue. I am looking forward to the later versions of jupyter lab!

**Comment by jasongrout** [comment]
Would you like to do the PR?



> I am still not sure whether simply changing the shortcut command names would have other side effects

That should be fine - just change the command names used in the shortcut definitions.

**Comment by logstar** [comment]
Thank you for the chance. 

Sure. I would like to do the PR accordingly to change the command names in the shortcut definitions.

**Comment by ian-r-rose** [comment]
@jasongrout Is this safe to close, or do you want to keep it open as a backport reminder?

**Comment by jasongrout** [comment]
It's backported now, so closing.
