### ISSUE TITLE
customizable scrolling

### ISSUE THREAD

**Issue by smsaladi** [jupyterlab/jupyterlab#4429]
Jupyter lab scrolls past the end of the text document (all the way through a blank screen) by default, as suggested here #813

I understand the preference to view code at eye level, but I actually really dislike this as default. Often, I through to the end of a document to look for a block from the bottom up (when I know it's near the end) and then end up with a complete blank screen.

For reference, Atom doesn't scroll past through the last bit of text.

Is there a way to have a customization setting to change one's own installation? I don't mind the current setting being default, but it would be great to modify my own install. Happy to try contributing a fix (if someone can point me in the right direction)

**Comment by jasongrout** [comment]
Here is the line that causes that behavior:

https://github.com/jupyterlab/jupyterlab/blob/6033b4a31a216b2c88713ed64e2077e83c397d2c/packages/codemirror/src/factory.ts#L43

I don't think it is exposed as an editor setting to JupyterLab, though it would make sense to expose it. @ian-r-rose knows a lot about exposing editor settings.
