### ISSUE TITLE
Reloading editable packages

### ISSUE THREAD

**Issue by sho-87** [jupyterlab/jupyterlab#4433]
Im developing a package and have it installed in editable mode (`pip install -e .`)

It seems that jupyter lab does not pick up changes to the package. It only works with a kernel restart, whereas other IDEs (e.g. spyder) detect the changes and reload the module upon any code execution

Intended behaviour or bug?

**Comment by jasongrout** [comment]
Intended behavior. And this is not part of Jupyter lab, rather it's part of
the Jupyter kernel framework. I believe there is a %reload magic in ipython
that reloads a module, but if I remember right, there are caveats with
reloading modules in Python, so I never personally use it.

Jason

**Comment by jasongrout** [comment]
It looks like ipython supports autoreloading: http://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html

Again, this is a function of the ipython kernel, and doesn't have anything to do with JupyterLab itself.

Closing as answered, but please post here again if you still have questions.
