### ISSUE TITLE
Scrolling on output doesnt work

### ISSUE THREAD

**Issue by harveyslash** [jupyterlab/jupyterlab#4434]
If I have a long output like this:

<img width="1363" alt="screen shot 2018-04-22 at 2 15 19 pm" src="https://user-images.githubusercontent.com/7107410/39098357-9e390e1c-4637-11e8-80c9-98f8c1351866.png">

I am unable to scroll at all. 

The only way I am able to see the output is when i disable scrolling. In this case, the entire output is displayed without any scroll bars. 

I have tried this on Mac OS 10.13.4 on safari and chrome. 

about jupyter lab lists this version: 

Beta Release Series
Version 0.32.0

**Comment by jasongrout** [comment]
This is caused by https://github.com/jupyterlab/jupyterlab/pull/3730/files#diff-e88b12e4decee829241977f3adeb539dR23
