### ISSUE TITLE
Document Angular Extension

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#4438]
@SimonBiggs recently had success creating an extension that included an Angular app. It would be helpful to have this documented, because it wasn't a straightforward process. It would probably make sense to do this in the ["Extension Developer Guide" maybe under "Extension Authoring"](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/extension_dev.rst#extension-authoring).

We could also make a boilerplate repo for this, but that's a bit more work and then we have to maintain it.

**Comment by SimonBiggs** [comment]
Just let me know what is desired and I'd be happy to do it :).

**Comment by saulshanabrook** [comment]
Would it be possible to document what changes are necessary from creating a new app with angular cli to including it in the jupyterlab build? Like the changes of the html imports and such. 

Or do you is that too broad?

**Comment by SimonBiggs** [comment]
There is also the need to do custom bootstrapping of the angular app, which
means you can't actually use angular CLI...

It might actually be easier to make a boilerplate app and then you can see
what is required and see what you want documented. The app can be included
or not... My best method of learning personally is examples though...

**Comment by saulshanabrook** [comment]
> There is also the need to do custom bootstrapping of the angular app, which
means you can't actually use angular CLI...

Awe, thats too bad.

> It might actually be easier to make a boilerplate app and then you can see
what is required and see what you want documented. The app can be included
or not... My best method of learning personally is examples though...

Yeah that might be best. Or we could point people to `scriptedforms`, so then we don't have to spend energy keeping another cookiecutter up to date. 

If we did that, maybe we could include it in a broader list of reference extensions, to give show people examples of different things you can do? Like creating a new file manager, etc.

**Comment by saulshanabrook** [comment]
That would be great. Then we can figure out where to link to that in the JupyterLab docs. That way it's easier for you to keep it up to date.

**Comment by SimonBiggs** [comment]
Heya @saulshanabrook,

I have done up a guide. It's over at:
https://github.com/SimonBiggs/scriptedforms/blob/master/scriptedforms/docs/create-your-own-angular-jupyterlab-extension.md

Let me know what you think / what feedback you have.

Cheers,
Simon

**Comment by saulshanabrook** [comment]
@SimonBiggs That looks really good. Thanks again for putting this together, I imagine it took a while to figure all that out. I opened a PR to add a link to this in our docs. 

@sccolbert maybe you are interested in seeing the Phosphorjs part: https://github.com/SimonBiggs/scriptedforms/blob/a2365fef3cffb5bfe8762263048f07b63ae27acd/scriptedforms/src/app/phosphor-angular-loader.ts#L42

**Comment by SimonBiggs** [comment]
Thanks Saul :)

**Comment by SimonBiggs** [comment]
I should actually correct a comment of mine from before. The Angular CLI could actually still be used when creating a jupyterlab extension. The relevant files can be changed to manual bootstrapping without messing up the CLI.

The only reason I had to eject from the Angular CLI was I needed custom webpack for my standalone version. But the jlab extension doesn't need webpack at all. So a standard Angular jlab extension should be able to use Angular CLI.

**Comment by SimonBiggs** [comment]
@jzf2101 gitter doesn't seem to be working, but I saw your comment wrt a CERN talk,

 I don't know if this would be the sort of thing the folks at CERN would be interested in, but as an example of what can be made with the JupyterLab tools there is https://github.com/SimonBiggs/scriptedforms

Of course they also might find the extension itself useful.

To make it work within JupyterLab install with `pip install scriptedforms` copy the following file into your JupyterLab directory, then go open with ScriptedForms inside JupyterLab.

https://raw.githubusercontent.com/SimonBiggs/scriptedforms/master/example/example/detailed.md
