### ISSUE TITLE
Extension bundling growing pains

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#4439]
I want to continue a discussion on gitter around some pains with bundling large javascript libraries.  @jasongrout [posted a link an article called "Designing very large (JavaScript) applications"](https://gitter.im/jupyterlab/jupyterlab?at=5ada675f7c3a01610d03d0e3)

One part that resonated was:

> Another example of this anti-pattern is the webpack.config.js file, where you have this one thing that is assumed to build your entire application. That might go fine for a while, but eventually needing to know about every aspect of what some other team did somewhere in the app just doesn’t scale. Once again, we need a pattern to emerge how to decentralize the configuration of our build process.

We have been running up against this problem when extension authors wanted to bundle Angular applications or use other webpack loaders.

@SimonBiggs suggested on gitter maybe we could isolate extensions from each other. So that each used it's own environment in some way.

We might be able to mitigate these extension issues on a case by case basis, providing a way for them to either precompile their code in some way or change how it is authored to work with our build system. It might be helpful to, at some point, to be explicit about what our build system can support and what it can't support. So that extension authors have an understanding of how their compiled extension has to work before it can be built properly. For example, if they have a typescript extension, they have to first compile that to JS. We don't process their TS in our webpack build. Also, we should be clear about what ES version we support extensions to be compiled in.

**EDIT**: We don't currently process their TS in our build now, I was confused about how this worked.

**Comment by SimonBiggs** [comment]
It is already explicit in the docs that standard JavaScript is required for extensions. So that part is covered.

**Comment by sccolbert** [comment]
The "isolation" idea breaks down when extensions need to start sharing objects across module boundaries. I good example is a Phosphor `Widget` (or subclass thereof). Extensions create widgets which are then dropped onto the `DockPanel`, internally the `DockPanel` does an `instanceof` check to make sure the thing you are telling it to drop is indeed a `Widget` (since the mime data is loosely typed). If the extension has it's own separate copy of Phosphor, the `instanceof` check will fail because the prototypes are different.

**Comment by SimonBiggs** [comment]
Can that be overcome by have a maintained list of packages which are kept as global?

https://gitter.im/jupyterlab/jupyterlab?at=5adb4a1727c509a77436b4f3

It is however back at a centralised solution.

**Comment by SimonBiggs** [comment]
Not to mention whether or not it's possible even...

**Comment by saulshanabrook** [comment]
[This yarn blog post](https://yarnpkg.com/blog/2018/04/18/dependencies-done-right/) makes the case that packages like `react`, which should only be installed once, should be `peerDependencies`. It seems like most of our packages should be like this.

Has this been attempted? To change all our internal references to peer dependencies? And recommend extensions do this as well? So that we can be sure that we only have one of each phosphor library?

**Comment by SimonBiggs** [comment]
Definitely an interesting read. Thanks Saul.

**Comment by saulshanabrook** [comment]
There is also some great work happening in Typescript around building multiple projects at once: https://github.com/Microsoft/TypeScript/issues/3469#issuecomment-400439520 and then https://github.com/Microsoft/TypeScript/issues/25600

I was gonna wait for them to add support for automatically inferring project dependencies before trying this out on jupyterlab core (https://github.com/Microsoft/TypeScript/issues/25376), but I might try before then.

As I been seeing issues come up, a lot of them are around versioning. Especially since releases are happening rather quickly, it can be confusing when people are trying to develop against them. My hope is that by using a combination of peerDependencies on all jupyterlab core packages and phosphor packages, as well as making the installed jupyterlab folder more explicitly just a npm package, so that users can go in and root though their local package.json/yarn.lock file tot understand why multiple versions of something is installed. Overview is let's try to hide less from end users about how NPM/javascript packaging works because the abstractions are too leaky. How that works in practice will have to be determined.

**Comment by SimonBiggs** [comment]
Great ideas. In those issues they do seem to be encouraging people to try it out. If you do give it a shot, I imagine any issues you have would be ironed out relatively quickly on their end. Benefit of that is jupyterlab lerna usage support would land in typescript stable more quickly.

**Comment by SimonBiggs** [comment]
Looks like projects made it into typescript 3.0 https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/

**Comment by blink1073** [comment]
Thanks for the heads up @SimonBiggs, I'm going to try that out this week!

**Comment by blink1073** [comment]
Update: it was easy as heck to convert `metapackage` over.  I had to add one compiler flag to our base tsconfig and add the `references` field to `metapackage`.  Everything Just Works :tm: in that each folder gets its own `lib/` as if it were built directly, huzzah!  However, because the output of `metpackage` itself has changed, I need to update the way we build our API docs are built.  We need to build docs in each folder and make our own index page.   No code has to change, and Typedoc uses its own TypeScript compiler version, so we're good to go.  This will actually be an improvement since our current API landing page is awkward.

**Comment by blink1073** [comment]
cf https://github.com/jupyterlab/jupyterlab/pull/5030

**Comment by saulshanabrook** [comment]
I recently had to take an existing web app that built with Webpack and embed part of it in a JupyterLab extension. At first, I tried just including it in the WebPack build (how most extensions are built now AFAIK). After hitting a couple of issues with not having the right WebPack setup, I decided to switch strategies and build it separately with webpack. 

WebPack has [some docs](https://webpack.js.org/guides/author-libraries/) on using it to author a library. I was able to just set `output.libraryTarget` to `"commonjs2"`. Then I was able to use the ES2015 module imports (as laid out in the docs) to access it.

It ended up being easier for me to inline all of that libraries dependencies (not adding anything to `externals` in webpack), but if you were bundling an extension that depended on phosphor libraries/JL core libraries you would probably want them to be inline.


It makes me wonder what it would look like if we didn't process any of the extensions with webpack while jupyterlab is building. So if they include anything that isn't regular JS (like different import loaders, etc) then they wouldn't work. They would have to be pre-built.

**Comment by blink1073** [comment]
We had at one point written a custom WebPack plugin that would create modules that we could load dynamically using a custom loader.  This was working well until we realized that in order to dedupe libraries on the client, we needed to be able to *fully* dedupe them, which means that every single file would have had to have been transpiled as part of the build process.  For libraries like CodeMirror and Mathjax that have tonnes of optional files that we end up never using, building and distributing those transpiled files is prohibitive.

**Comment by saulshanabrook** [comment]
Yeah I can definitely see why some de-duping is nice (and necessary when you have shared objects).

The advantage of running your extension through webpack is that it let's you be selective about what you wanna bundle. Also it can help you remove any of the crazy transpolation stuff needed for frameworks like Angular. It takes the effort off of core to do anything special with the JS modules you provide, so the compiled extensions end up not depending on webpack. Would let us experiment more with things browser based loading.

**Comment by blink1073** [comment]
Deduping is key to making dependency injection work, not just shared state.  We'd need a way to manage that.

**Comment by blink1073** [comment]
This article [1] is a good snapshot of the current status of ES Modules in the browser.  tldr; they can't be used until http2 is more widely supported [2] because we'd have a cascade of requests.

[1] https://www.sitepoint.com/using-es-modules/
[2] https://github.com/tornadoweb/tornado/issues/1438

**Comment by SimonBiggs** [comment]
Looks like http/2 is fully supported on all but IE:

https://caniuse.com/#feat=http2

**Comment by blink1073** [comment]
On the browser side, yeah, I meant the server side.

**Comment by blink1073** [comment]
Wow, that seems like a glaring oversight by the browser vendors...

**Comment by SimonBiggs** [comment]
Yeah :(. So does that mean that this pathway is essentially a complete no-op?

**Comment by blink1073** [comment]
It seems that way, asking folks to set up a local https certificate and handling trust at the system level seems like too much of a burden.

**Comment by SimonBiggs** [comment]
I agree :(

**Comment by saulshanabrook** [comment]
Create React App has decided not to parse `node_modules` with JSX or other non valid JavaScript:

https://twitter.com/dan_abramov/status/1045686784536051712

https://github.com/facebook/create-react-app/issues/5103#issuecomment-425459196

> 
> We only compile valid JavaScript syntax in node_modules. JSX is not valid JavaScript. You are using JSX there.
> 
> The reason we've taken this stance is because compiling non-standard syntax tightly couples libraries to build tools. For example, if JSX changes and Babel 8 comes out with those changes, suddenly all libraries using JSX internally wouldn't work anymore. You can fix your code but fixing dependencies takes a lot more coordinated effort. And people using Babel 7 (in this example) wouldn't appreciate their code breaking either. So every library would be forced to release a new major version, and possibly maintain both for a long time.
> 
> It's also hard to draw a line once you allow experimental things. Most people will want to use not just JSX, but also experimental transforms like class properties. Or decorators. Now we have to argue with every library maintainer about which transforms we want to support, and which we don't. But all of these transforms tend to change until standardized. It already happened many times, e.g. Babel 7 changed the semantics of class properties a little bit. It will happen again.
> 
> So say Babel 8 comes out with different class properties behavior. Now you have to vet all libraries you depend on to check if they expect old or new behavior. Nobody can upgrade to the next CRA/Babel because they're locked into the experimental syntax their dependencies (including transitive ones) assume. You can see how this exact situation played out with Babel 7 upgrade in the React Native community. It caused months of pain for RN users, and it's still an ongoing problem.
> 
> This is why we don't compile non-standard syntax in node_modules.

Makes me wonder if we could take the same perspective about extensions. What are the ways we process node_modules that isn't standard?

* allow webpack loaders in require statements. This is to support things like file-loader so that users can get the URL to files.
* All other custom loaders we support: https://github.com/jupyterlab/jupyterlab/blob/4845c45a38637f06f5208ae25fc4e38122d0aab6/dev_mode/webpack.config.js#L117-L154

Anything else?

**Comment by blink1073** [comment]
We also allow `require.ensure` which is unique to WebPack: https://github.com/jupyterlab/jupyterlab/blob/8a141cadf904150b01886f189a10a3143676a1eb/packages/vega4-extension/src/index.ts#L192. 

I think we can stop doing that in favor of dynamic `import()`, since we switched to ES6 output.

**Comment by saulshanabrook** [comment]
In relation to ["Using JavaScript modules on the web"](https://developers.google.com/web/fundamentals/primers/modules#package-name-maps), what would we need from web modules?

One way we could use them would be if we could ship all our JupyterLab core packages and their dependencies to the browser in a minified file and load extensions as separate files that could require modules from that bundle. So this requires decoupling the modules from files, in the sense that we should be able to send a bunch of modules in one file. There are likely a bunch of other edge cases here around dependency resolution and static asset loading that we would have to figure out, if extensions could be loaded client side. (this would move us towards https://github.com/jupyterlab/jupyterlab/issues/5672)

cc @blink1073 @jasongrout

**Comment by saulshanabrook** [comment]
Goals:

* Add ability to install extension without rebundling whole app with webpack


Here are some use cases and how they work ideally:

> If extension has only dependencies on modules already included in global build and are happy with versions and is a single version:

* We download one large file that has all the core dependencies.
* We import the file on the browser and get it in a separate request, since it isn't in this bundle. the bare import specifiers should correspond to the already loaded modules in the core.

> If the extension has dependencies that conflict with the core package:

* we install the extra dependencies on the server.
* We somehow bundle those dependencies or server them up individually
* When we import, it either gets the whole bundle or recursively gets the files it needs.


Seems like need something like this subresource bundling: https://wicg.github.io/webpackage/draft-yasskin-webpackage-use-cases.html#rfc.section.2.2.9

**Comment by saulshanabrook** [comment]
Summary of meeting with Matthias Bynens:

There is a bundling proposal in the works to take a bunch of assets (CSS, JS modules, etc) and combine them into a zip file. Then they could be shipped to the browser as one file and it would know how to parse these. Webpack or other bundlers would output these.

**Comment by saulshanabrook** [comment]
Yeah that's what `dependencies` are for, I believe. If you set your version to very permissive, like `*`, then it will use reuse any version previously required by the parent or install it's own if it isn't.

**Comment by wolfv** [comment]
just regarding this

> It seems that way, asking folks to set up a local https certificate and handling trust at the system level seems like too much of a burden.

There seem to be ways to set up localhost with https although it requires to generate a self-signed certificate and to make the computer + browser trust it. It's definitely not the best way to go. But in that case the user wouldn't be greeted with the warning.

https://dev.to/rhymes/really-easy-way-to-use-https-on-localhost-341m

**Comment by bollwyvl** [comment]
On the http/2 piece: not sure why that's never really caught on in tornado-land, but the landscape is certainly broader than it was a few years ago. For my money, come [2020](https://devguide.python.org/#status-of-python-branches), I'd look at going to the ASGI stack. My personal preference would be to go 3.6+ in September, as [FastAPI](https://github.com/tiangolo/fastapi) on [hypercorn](https://gitlab.com/pgjones/hypercorn) would be fully type-checkable, free OpenAPI, interactive docs, etc... but no doubt there are other paths.

Even _without_ http/2, busting up lab into more files could be good. Last month i tried a little experiment with webpack settings (and templates) and got this:

https://gist.github.com/bollwyvl/043ab34c4eaf36c27680a8e48346c07c

![Screenshot from 2019-08-30 00-01-39](https://user-images.githubusercontent.com/45380/63993477-ab6aa200-cabe-11e9-9d95-c6b2bef920ec.png)

It's pretty much the same size on the wire, and vendor~main is still pretty big, but this is without changing any code. Getting some more heavy hitters off the bottom line, by demonstrating/promoting `await import`, measuring performance, and being agressive on watching for regressions is the best we can hope for now.

**Comment by jtpio** [comment]
> Add ability to install extension without rebundling whole app with webpack

Looks like this issue can now be closed now that the prebuilt extension system is available in JupyterLab 3: https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#prebuilt-extensions

Thanks all!
