### ISSUE TITLE
Console restoration

### ISSUE THREAD

**Issue by SimonBiggs** [jupyterlab/jupyterlab#4444]
Currently JupyterLab does not restore consoles.

## Steps to reproduce

Start the JupyterLab server then:

* Create a new notebook.
* Create a new console attached to the kernel of the notebook
* Go to URL http://localhost:8888/lab/workspaces/a-workspace

Close the JupyterLab server, then restart the JupyterLab server

* go to http://localhost:8888/lab/workspaces/a-workspace

The console has not been restored.

**Comment by jtpio** [comment]
Thanks @SimonBiggs for the report.

Consoles should now be restored with the recent JupyterLab releases.

Just tested with `3.1.10` and it seems to be the case:

https://user-images.githubusercontent.com/591645/131810534-879f6ba5-ee52-4de6-95a8-9edba81f4f6a.mp4

**Comment by SimonBiggs** [comment]
Thanks @jtpio :slightly_smiling_face:
