### ISSUE TITLE
figure's ticks are missing

### ISSUE THREAD

**Issue by echosori** [jupyterlab/jupyterlab#4456]
In lab mode, jupyter doesn't show chart's ticks.

**Comment by ian-r-rose** [comment]
Hi @echosori, can you post a screenshot? What theme are you using?

**Comment by jasongrout** [comment]
Also, what charting library are you using? Can you post code to reproduce what you are seeing?

**Comment by echosori** [comment]
Thank you for asking, It was a mistake, there is nothing wrong with the lab mode.

I set lab's theme as DARK, and  didn't change ticks' color, so the black ticks couldn't be seen in dark background.

If I change ticks' color , or make the theme of lab LIGHT, They are visible again.
