### ISSUE TITLE
Params not placed at the front when Tab in the function brackets

### ISSUE THREAD

**Issue by Evan1987** [jupyterlab/jupyterlab#4457]
In **jupyter notebook**, params are placed at the front when Tab.(see pic below)
![image](https://user-images.githubusercontent.com/22452707/39241073-4be56db2-48b8-11e8-8f7c-513824bded3a.png)

But in **jupyterlab**, the order is just ascending by letters. (see pic below)
![image](https://user-images.githubusercontent.com/22452707/39241530-d93fa000-48b9-11e8-850f-dd523c2b093a.png)

It's not very friendly especially when I forgot some param name and don't want to check help doc.

**Comment by jasongrout** [comment]
In the current Jupyter Notebook (6.0.3), parameters are listed in alphabetical order for me:

<img width="723" alt="Screen Shot 2020-06-04 at 9 43 32 AM" src="https://user-images.githubusercontent.com/192614/83786986-f7e39f00-a647-11ea-9310-6a933d83a5a5.png">

**Comment by krassowski** [comment]
Closing as this is an upstream issue in IPython https://github.com/ipython/ipython/issues/12344. There is a related issue tracking sort order being lost on typing https://github.com/jupyterlab/jupyterlab/issues/14622.
