### ISSUE TITLE
Switch TS to output es2015 code

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4461]
According to https://kangax.github.io/compat-table/es6/, current browser versions (chrome, firefox, safari, edge) support nearly all es2015 features. I think we should experiment with switching our typescript to output es2015 code. We should probably also upgrade to TS 2.8 while we're at it.

One huge advantage this gives us is *much* more readable async/await compiled code, since the compiled code can natively use generators.

**Comment by jasongrout** [comment]
CC @sccolbert

**Comment by sccolbert** [comment]
Cool! I'm still supporting IE11 in Phosphor, but maybe it's time to drop that.

I'd be interested to do a perf test between ES5 and ES6 output, just to know how well the current JITs are optimizing the builtin ES6 classes.
