### ISSUE TITLE
Text Editor Removes Linefeeds

### ISSUE THREAD

**Issue by twoodhouse** [jupyterlab/jupyterlab#4464]
I am running Jupyter lab 0.31.4 on Windows 7.

Today I realized that the jupyter lab text editor (not the notebook editor) is removing line feeds from all of my files. The files still display correctly in jupyter lab and vim, but when I open them in notepad, they are all displayed in one line.

I verified this by writing/saving a new text file in notepad, opening it in Jupyter lab, changing one character, then saving.
When I open it in notepad again, it has been compressed into one line.

I will not have time to really follow up on this issue. Just wanted to let the project know since it is not apparent from within the editor.

**Comment by vidartf** [comment]
This is probably due to lab/notebook normalizing the line endings. Notepad famously does not understand non-Windows line endings (Wordpad does). Whether lab should be doing this is an open debate I think.

**Comment by jasongrout** [comment]
I wonder if this is a problem with the notebook server, which is the thing that actually writes the files to disk. What happens if you open, edit, and save these files in the classic notebook?

**Comment by afonit** [comment]
I just tried this in classic.
The behavior is as mentioned in the original post.

As @vidartf said the files look fine in wordpad, it is just notepad where they are put in a single line.

**Comment by ian-r-rose** [comment]
Yes, the `DocumentRegistry` package [normalizes](https://github.com/jupyterlab/jupyterlab/blob/master/packages/docregistry/src/context.ts#L508) line endings to `\n`. We were having problems with model-view synchronization in CodeMirror when documents had `\r\n` line endings, which prompted the change.

Now that I look at that code path, I wonder if it also might be responsible for the spurious "dirty" state that some people were seeing (I can't find the issue right now)?

**Comment by jasongrout** [comment]
> Yes, the DocumentRegistry package normalizes line endings to \n.

Oh, interesting. Yes, we should definitely be smarter about maintaining the CRLF status of the file.

**Comment by ian-r-rose** [comment]
I don't think anyone was particularly happy about this solution, but it was the lesser of two evils at the time (the alternative was inserting text to the wrong location in the buffer).
