### ISSUE TITLE
Github Triaging

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#4471]
I am starting to go through and triage old and new issues. I want to be explicit about my process, so that I can get suggestions on improvement and so it can help others if they are starting to triage. Some guidelines I am trying to follow are:

* Hear what people are saying so that they are encouraged to continue to participate. i.e. be encouraging and appreciative of their time
* Help them solve their problem (answer questions, submit PR) or give them tools to solve it themselves (create an extension, encourage a PR)
* Allow maintainers to more easily sift through issues by tagging and closing issues

Maybe these points could be helpful in creating an issue/PR template? @jzf2101 you were gonna take a look at this? At least encouraging people to do a search first to see if their issue is a duplicate, and creating separate issues for separate problems would be helpful things to include.

**Comment by jzf2101** [comment]
Yes, me set that up

**Comment by saulshanabrook** [comment]
I would like to create a policy for how we deal with PRs. Having lot's of open PRs feels overwhelming, because it's hard to know which are actively moving forward and which are not. Maybe this could be helped by using Projects to triage PRs? Right now, I feel inclined to try to close PRs that haven't seen work in a while (like https://github.com/jupyterlab/jupyterlab/pull/4294), because doing so would help reduce the mental load when looking at the list of open ones. However, it's unclear to me what closing a PR really means. People can still push changes to it and we can still comment on it. I guess the biggest change is that isn't as visible in the project, although can still be found through search.

**Comment by afshin** [comment]
I think that's a good idea. Perhaps we should have some language that we use for this class of PRs. Something like: "This PR is being closed because it has been inactive. Feel free to re-open it if and when you wish to continue working on it."

**Comment by saulshanabrook** [comment]
Do we have a place now to document this kind of process? It seems like `CONTRIBUTING.md` is focused on the coding, not the social part, of contributing.

Also, if we close a PR, can the author still re-open it later or does it require a core contributor to re-open?

**Comment by afshin** [comment]
I am not sure if a non-owner of a repo can re-open a PR, but even if not, we'd always encourage a new PR when it's appropriate. I'm not sure, but perhaps this sort of thing belongs in the contributing guide.

**Comment by JasonWeill** [comment]
Closing in favor of the current triage process documented at https://github.com/jupyterlab/team-compass/issues/228.
