### ISSUE TITLE
'Show in file browser'

### ISSUE THREAD

**Issue by rando128** [jupyterlab/jupyterlab#4472]
When I'm using JupyterLab with many files opened from different projects, I tend to struggle to remember which file tab corresponds to which project (as some of the notebooks are not well documented). Is there any way to be able to identify the path/directory of a specific open notebook via the file manager or 'open tabs' view of the left sidebar?

**Comment by ian-r-rose** [comment]
I think this is a nice candidate for a good first issue. It would involve getting the path of the document, taking the dirname of the path, and then navigating the filebrowser to that path. We could then add that to the context menu for the tab of the file.

**Comment by rando128** [comment]
This corresponds to what I had in mind. Thx for considering this enhancement.

**Comment by telamonian** [comment]
I've wanted this feature for a while too. It sounded like it would be fun to figure out how to do, so I've gone ahead and submitted a pull request (#4500) with an implementation of it.

The "Show in file browser" menu item that it adds seems to work well. The only problem is that it only works on the currently open document, even if you right click on another tab. However, this seems to be a problem with the context menu itself, since selecting "Rename..." has the same focus problem.

**Comment by ian-r-rose** [comment]
Ooh, thanks for flagging that, that's a real problem!

@sccolbert what do you think about this? Like the issue with the filebrowser listing we talked about a few weeks ago, this is a place where the CSS selector doesn't give enough information for the context menu item to work correctly. In this case, we don't know which tab was clicked upon, and using the currently active one is not correct in general. We could put the path in the DOM node dataset, but perhaps there is another way forward?

**Comment by jasongrout** [comment]
Maybe the right click could change the active widget (this would require a change probably in the phosphor tab bar).

**Comment by ian-r-rose** [comment]
I was just playing with this in Firefox and Chrome: neither of them change the tab upon right-clicking an inactive one.

**Comment by jasongrout** [comment]
Phosphor ignores mousedown events that are not primary or auxiliary (usually left and middle) clicks: https://github.com/phosphorjs/phosphor/blob/4d787b32136861adae4ebadc6c877a130d0cb216/packages/widgets/src/tabbar.ts#L567-L570

**Comment by ian-r-rose** [comment]
Fixed by #4500. Thanks @telamonian!
