### ISSUE TITLE
Various autocomplete bugs

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#4476]
As I have been going through issues people have left, I am seeing quite a few autocomplete bugs https://github.com/jupyterlab/jupyterlab/labels/pkg%3Acompleter

I am often not sure how to help people diagnose these. Besides upgrading Jupyterlab could upgrading jupyter-notebook also help? Are there other ways to debug where the autocomplete is failing?

**Comment by saulshanabrook** [comment]
ref #4371

**Comment by jasongrout** [comment]
Sometimes an autocomplete bug can be a bug in the kernel, so upgrading ipykernel can help.

**Comment by saulshanabrook** [comment]
@jasongrout thanks, I remembered there was something else we could upgrade, but forgot what package it was.
