### ISSUE TITLE
Jupyterlab hanging 

### ISSUE THREAD

**Issue by maverik-akagami** [jupyterlab/jupyterlab#4478]
on google chrome windows browser
I have cleared cache, It was working about 2 weeks ago. with the latest download from anaconda, this hangs. 

Please check this issue. It works fine on my Firefox browser though

**Comment by jasongrout** [comment]
What version of JupyterLab? Can you try from an incognito window?

**Comment by uzi0espil** [comment]
I am facing same issue.. Running two scripts in split mode on Chrome browser v. 67.0.3396.99, After 1 minute of running both scripts, the browser hangs and ask for killing the page. I tried also with icognite and still same problem

Jupyterlab version: 0.32.1
OS: Ubuntu 16.04

**Comment by uzi0espil** [comment]
This issue for me is at least related to this problem [#4202](https://github.com/jupyterlab/jupyterlab/issues/4478)
