### ISSUE TITLE
Notification a-la toastr (with reactjs)

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#4484]
I have tried to integrate toastr-like notification.

1. With `react-redux-toastr`, I face https://github.com/diegoddox/react-redux-toastr/issues/156
2. With `react-toastify`, nothing is shown (no toastr, no error in the console).
3. Is there any link with a working react / toastr integration?
4. In a more general way, is there a existing mechanism in the current JupyterLab architecture to notify the user.

(PS: The same code and dependencies (without the jupyterlab components) were working fine with `react-redux-toastr`).

**Comment by jasongrout** [comment]
We don't have a good notification system yet. We'd really like one, though! @ellisonbg may have some more thoughts on it - it was a possible project for his students this summer.

It would be great if someone worked on it!

**Comment by echarles** [comment]
@ellisonbg have you someone to tackle notifications this summer? Happy to further help on this.

**Comment by fcollonval** [comment]
#689

**Comment by fcollonval** [comment]
I prototyped an extension https://github.com/fcollonval/jupyterlab_toastify. Don't hesitate to comment or fork for improvement.

**Comment by echarles** [comment]
Closing this in favor of #689
