### ISSUE TITLE
Autocompletion in editor

### ISSUE THREAD

**Issue by mrinalraghupathi** [jupyterlab/jupyterlab#4487]
Is it possible to autocomplete python code in the editor (it works in the notebook and console)? If not is there a plan to introduce this feature?

**Comment by jasongrout** [comment]
There is no autocompletion yet. We hope to develop it in the future, and would love if someone would experiment or help with it.

**Comment by saulshanabrook** [comment]
There is some discussion of this in #2972 as well

**Comment by schlichtanders** [comment]
jupyterlab can already link a jupyter console to the current text editor

isn't it simple to just plug and play the notebook autocompletion feature to the text editor?
All should be there already in the running jupyter console linked to the text editor.

**Comment by schlichtanders** [comment]
it blew my mind! It is already there!
I don't know how I could miss it when I first tried out the text+console linkage, however autocompletion just works like I suggested.

All notebook-like-autocompletions are also there in the text-file if you execute things accordingly in the respective linked console.

Thanks jupyterlab-team for having created this lovely feature!

**Comment by ian-r-rose** [comment]
Yep, this was added in #5049. Glad you are enjoying it!

**Comment by mrinalraghupathi** [comment]
Thanks for this explanation and feature. It's made things a lot easier! Jupyterlab is great!

**Comment by hougrammer** [comment]
Sorry I'm dumb.  How do I link a text file to a console such that I can use tab to autocomplete in the text editor?

**Comment by hougrammer** [comment]
Thanks for the response.  I am able to get autocompletions to work in the console, but pressing tab in the text editor itself still just inserts a tab.  Are we talking about autocompletions in the console or the editor?

**Comment by ian-r-rose** [comment]
We are talking about completions for the text editor, @hougrammer. What version of JupyterLab are you using? It may be prior to the addition of this feature.

**Comment by hougrammer** [comment]
Man I'm an idiot.  I was using the beta release.  After upgrading to 0.35.4 the autocomplete works as expected.

**Comment by blink1073** [comment]
Glad you're back up and running!

**Comment by alex-delacruz** [comment]
Where is the "Create Console For Editor" option?  I just have "New console for notebook". Someone please help.

**Comment by ian-r-rose** [comment]
Hi @alex-delacruz, you can find it by right-clicking on the text editor.

**Comment by alex-delacruz** [comment]
Hi @ian-r-rose I have this context menu. 
![img_gt](https://user-images.githubusercontent.com/26086789/51950908-6b482180-2400-11e9-8308-63a933676476.JPG)

**Comment by ian-r-rose** [comment]
This issue is regarding the text editor, not the notebook. Here, you would select "New Console For Notebook"

**Comment by nealmcb** [comment]
Just to clarify the status and link issues together a bit more:

This issue was resolved via #5049 as called for earlier in "use console for editor autocompletion" #3483.

So the links from this issue to issues calling for a more general and useful, but more difficult approach to completion, e.g. via e.g. #2163 Language Server Protocol, still make sense.

**Comment by jasongrout** [comment]
Thanks, @nealmcb!

**Comment by steve7an** [comment]
Awesome, so glad that I've spent the time to google this up.
Rather than keeping typing up everything word for word :

**Comment by wesinator** [comment]
Is there a plan to have full autocomplete (vars, function names, etc.) in all edit cells without requiring a console ?

This is a fundamental feature for code editing that does not appear to be present in 1.0.4

**Comment by jasongrout** [comment]
We would love to have better autocomplete eventually. To do static autocompletion (without a kernel running), we'll probably need something like jedi or Language Server Protocol integration, along with a backend component to do the source analysis.

**Comment by jasongrout** [comment]
And as always, help is welcome in implementing this!

**Comment by wesinator** [comment]
> We would love to have better autocomplete eventually. To do static autocompletion (without a kernel running), we'll probably need something like jedi or Language Server Protocol integration, along with a backend component to do the source analysis.

Hmm, I'm not seeing variable name autocomplete with a running kernel .
<img width="340" alt="image" src="https://user-images.githubusercontent.com/5124946/62319035-121e8080-b46b-11e9-8cca-d85d7c7f66ed.png">


client: Firefox 68.0.1 on macOS
python 3

**Comment by jasongrout** [comment]
Please see the discussion above for how to use the current autocompletion that uses a console kernel.

**Comment by wesinator** [comment]
Ah, thanks. Seems to be working for me now anyway 🤷‍♂
