### ISSUE TITLE
Shift-Enter does not work in Firefox 45 and 49 on Linux

### ISSUE THREAD

**Issue by benfischer1** [jupyterlab/jupyterlab#4488]
Using a kind-of old version of Firefox on Linux (45, from 2016 I think), Shift-Enter does not consistently execute the current cell.  It usually just adds a line, like Enter would. If I arrow-down to a cell, the background is light and shift-enter would work, but after typing in a cell, the background is a slightly darker color and shift-enter simply adds another line to the cell.   

This all works correctly in Jupyter Notebook.  I also tried Jupyter Lab on my Windows box and Firefox seemed a little more flakey than Chrome, but i'm kind of stuck with Firefox on the linux host.

**Comment by jasongrout** [comment]
(That said, I looked up a bit about what FF 45 supports, and didn't see anything that jumped out to me as causing such a problem.)

**Comment by benfischer1** [comment]
Thanks for the reply

I'm using the latest version, 0.32.  
I'm still kind of new to Jupyter, so I'm not sure if I have all the terminology right.
When I open the jupyter notebook (with http:/localhost:8888/notebook in the url) I can enter text into a cell and hit shift-enter and it will run the cell and move to the next cell.

However, if I'm in jupyterlab (with http:.../lab in the url), if I type text into a cell and hit Shift-Enter I just get a new line in the cell.  However, if I click on a cell and hit a down-arrow or up arrow to go to a different cell, then I guess I'm in a different mode because the cell background changes to white and I can hit Shift-Enter and the cell will be executed.

I'm asking around to see if I can get a more up to date Firefox or Chromium installed.

**Comment by jasongrout** [comment]
Just FYI, I downloaded FF 45 and I'm seeing the same thing you describe. Actually, sometimes it seems when I edit a cell, shift-enter *does* work. It seems to not work if I am editing and I backspace, though. Still digging a bit.

**Comment by jasongrout** [comment]
Something definitely weird is going on. It seems that the notebook is not realizing that you are editing, i.e., it doesn't switch from command mode to edit mode.

Can you see about upgrading before we go any further?

**Comment by arvoelke** [comment]
The same thing happens for me with FF 49.0.2 and jupyterlab 0.34.7. Works fine in Chrome.

**Comment by jasongrout** [comment]
Great, thanks for the update. I've updated the title to note the versions of Firefox this affects.

**Comment by benfischer1** [comment]
I can confirm Firefox 52.6 works. Jupyterlab 0.34.6

**Comment by jasongrout** [comment]
We're up to Firefox 68 now as the current release, and JupyterLab 1.0.5. Since we officially support the latest Firefox (https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#supported-browsers), and it looks like this has been working for many recent releases, I'll close this.

**Comment by cibic89** [comment]
This is now back... jupyterlab v1.0.2 on firefox 68.0.2 x64 on windows server 2016
