### ISSUE TITLE
[Question] Lab equivalent of jupyter_notebook_config.py's extra_nbextensions_path

### ISSUE THREAD

**Issue by Madhu94** [jupyterlab/jupyterlab#4491]
Hi,

Forgive me if this is already documented somewhere, but is there a way to specify what the app dir ``JUPYTERLAB_DIR`` should be, via config ? The notebook had c.NotebookApp.extra_nbextensions_path. 

On a slightly related note, is https://github.com/jupyterlab/jupyterlab/issues/4064#issuecomment-377694281 open for someone to work on ?

**Comment by cyberwillis** [comment]
I just start my jupyterlab using this parameter:

--NotebookApp.notebook_dir=/projects

may be you can find this attribute in the config file.

**Comment by Madhu94** [comment]
To clarify, I asked what is the equivalent of extra_nbextensions_path for
labextensions, not nbextensions or server extensions. Right now, we can set
the JUPYTERLAB_DIR environment variable and the lab extensions will be
picked up from JUPYTERLAB_DIR/extensions. I wondered if it was possible to
set this via a config file.

**Comment by cyberwillis** [comment]
In your first post you said:

> The notebook had c.NotebookApp.extra_nbextensions_path.

It still has this on config file in: `~/.jupyter/jupyter_notebook_config.py` 

Also jupyterlab is just a web-based interface the product continue to be the same.

**Comment by jasongrout** [comment]
Thanks for discussing this. The extension system in JupyterLab is totally separate and different than the classic notebook, so none of the nbextension settings apply.

From http://jupyterlab.readthedocs.io/en/stable/user/extensions.html#advanced-usage, we can see that the `--app-dir` option in the command line sets this directory. Looking at the output of `jupyter lab -h`, we see the entry for `app-dir` gives the config option to set it:

```
--app-dir=<Unicode> (LabApp.app_dir)
    Default: '/[snip]/share/jupyter/lab'
    The app directory to launch JupyterLab from.
```
So it looks like setting the `LabApp.app_dir` config option is what you'd need to do. Does that answer your question?

**Comment by jasongrout** [comment]
> On a slightly related note, is #4064 (comment) open for someone to work on ?

I don't know of anyone working on this.

**Comment by Madhu94** [comment]
Yes, the LabApp.app_dir traitlet is what I was looking for. Thanks a lot.

@cyberwillis, thanks for trying to help, I'm sorry if I wasn't very clear.

**Comment by jasongrout** [comment]
Great! And thanks again for discussing this, @cyberwillis. We really appreciate the help in engaging and trouble-shooting things!
