### ISSUE TITLE
This matplotlib animation example works in notebook but not in lab

### ISSUE THREAD

**Issue by fm75** [jupyterlab/jupyterlab#4492]
```
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

from matplotlib import animation, rc
from IPython.display import HTML

# First set up the figure, the axis, and the plot element we want to animate
fig, ax = plt.subplots()

ax.set_xlim(( 0, 2))
ax.set_ylim((-2, 2))

line, = ax.plot([], [], lw=2)

# initialization function: plot the background of each frame
def init():
    line.set_data([], [])
    return (line,)

# animation function. This is called sequentially
def animate(i):
    x = np.linspace(0, 2, 1000)
    y = np.sin(2 * np.pi * (x - 0.01 * i))
    line.set_data(x, y)
    return (line,)

### call the animator. blit=True means only re-draw the parts that have changed.

anim = animation.FuncAnimation(fig, animate, init_func=init,
                               frames=100, interval=20, blit=True)

# equivalent to rcParams['animation.html'] = 'html5'
rc('animation', html='jshtml')
rc

HTML(anim.to_jshtml())
```

[Original source](http://tiao.io/posts/notebooks/embedding-matplotlib-animations-in-jupyter-as-interactive-javascript-widgets/)

Using `jupyterlab 0.32.0` release on `Mac OSX 10.13.3`
Example works when run in `jupyter notebook`, but not in `jupyter lab`

**Comment by arinbasu** [comment]
Hi Fred,

I found that it also does not work with Nteract.

What error messages did you get? When I tried running in Jupyterlab, it showed the sine curve and the bells and whistles aka the controls, the sliders, but they did not work with it. But I did not get any error message.


Arin

**Comment by fm75** [comment]
It showed the control, but no curve. Showed a "broken image icon"

**Comment by dopplershift** [comment]
See #3118 .

**Comment by jasongrout** [comment]
The underlying issue here is twofold: (a) the matplotlib javascript enabling this has not been ported to JupyterLab, and (b) JupyterLab is preventing the current matplotlib js from running (which assumes the classic notebook environment). (b) is discussed extensively in #3118.

**Comment by saulshanabrook** [comment]
Would https://github.com/matplotlib/jupyter-matplotlib be the right place to open an issue for (a)?

**Comment by dopplershift** [comment]
Not really, since that’s focused on the Jupyter backend for matplotlib. The animation stuff is done just through `_repr_html()`. Based on the conversation in #3118, what’s needed is [an animated image stack mimetype](https://github.com/jupyterlab/jupyterlab/issues/3118#issuecomment-362155896); once that’s a thing in jupyterlab, then we can update matplotlib’s animation handling.

**Comment by saulshanabrook** [comment]
Thanks for the pointer. https://github.com/jupyterlab/jupyterlab/issues/3894 is the issue for image stack animation mimetype. Also #4515 is a PR that adds javascript execution, that was just opened. Maybe that would cover this use case?

**Comment by jasongrout** [comment]
In JLab 2.1.4, I now get what appears to be the same output and functionality as Jupyter Notebook:

<img width="434" alt="Screen Shot 2020-06-04 at 9 25 30 AM" src="https://user-images.githubusercontent.com/192614/83784731-67a45a80-a645-11ea-8691-987b04f6de9b.png">
