### ISSUE TITLE
How to download and install jupyterlab extension offline

### ISSUE THREAD

**Issue by matanc1** [jupyterlab/jupyterlab#4494]
I've installed Jupyterlab on a work computer offsite.
I've wanted to run some plotly code but I also need the plotly-extension which I can't seem to install.

It seems the `jupyter labextension install` command requires an internet connection.

Is there a way for an offline installation?

**Comment by Tych0n** [comment]
I managed to get rid of "build" notification. My steps:

1. On machine with internet access i installed packages through conda and some extensions ([plotly](https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/plotly-extension), [toc](https://github.com/ian-r-rose/jupyterlab-toc), [git](https://github.com/jupyterlab/jupyterlab-git), [formatter](https://github.com/ryantam626/jupyterlab_code_formatter)).
2. Copied to offline machine:
packages from .../envs/name/pkgs
.npm and .yarn from home folder
.../envs/name/share/jupyter/lab folder
.txt with packages list
3. On offline machine recreated env from .txt.
4. Replaced lab folder inside env.
5. Replaced .npm and .yarn in home.
6. Launched jupyterhub and clicked rebuild.

**Comment by saulshanabrook** [comment]
I am closing this in  favor of this older issue https://github.com/jupyterlab/jupyterlab/issues/2065, which we could make progress on by changing our build process as laid out here  https://github.com/jupyterlab/jupyterlab/issues/5672#issuecomment-526278264
