### ISSUE TITLE
Froze when installing jupyterlab-manager

### ISSUE THREAD

**Issue by ktc312** [jupyterlab/jupyterlab#4495]
Hi,

I was trying to install a jupyter lab extension - beakerx
everything else is fine, but when I run 
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`
my terminal stuck at this step:
```
[1/4] Resolving packages...
⠁ @jupyter-widgets/jupyterlab-manager@file:../extensions/jupyter-widgets-jupyterlab-manager-0.35.0.tgz
```

I'm using a virtual environment with python3.6 and
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
beakerx==0.15.2 

how can I solve this?
thanks

**Comment by jasongrout** [comment]
This sounds like the issue we are trying to diagnose over at https://github.com/jupyter-widgets/ipywidgets/issues/2061 - can we move the conversation over there?

**Comment by ktc312** [comment]
Thanks for redirection
