### ISSUE TITLE
Add "Robust Run All Cells" command

### ISSUE THREAD

**Issue by JarnoRFB** [jupyterlab/jupyterlab#4496]
The "run all cells" command is great if you want to clean up a notebook. However, it stops once it hits an exception or error. Especially, if you use the notebook for educational purposes as a replacement for slides you sometimes want to have exceptions in your code to show the students what kind of code triggers them. Therefore, it would be great if there could be a "robust" version of the "run all cells" command, that just continues executing the next cells even if it hits an exception in between.

**Comment by jasongrout** [comment]
Thanks. FYI, we chose this behavior because it is what the classic notebook does, and often is the desired behavior. I see your point, though! Another way is we could have metadata on a cell saying "don't stop a run-all on this cell if there is an error"?

**Comment by ian-r-rose** [comment]
I believe that `nbconvert` has such a mode as well.

**Comment by JarnoRFB** [comment]
@jasongrout I thought more about a separate command, so you can choose which behavior you need. But explicitly white listing cells would have the advantage of not accidentally running over cells that do not execute correctly. Either would be fine for me.

**Comment by jasongrout** [comment]
> That basically solves my problem. Not sure if it would still be nice to have this feature directly available in jupyter lab.

Great. I think it makes sense to close this issue, then, and open a new one if people have a strong need to have this directly available in JupyterLab. Please comment if you disagree, of course.

**Comment by vidartf** [comment]
Note that the behavior of classic notebook currently is slightly different: It will stop on the first cell with an error, except cells marked with the "raises-exception" cell tag, see https://github.com/jupyter/notebook/pull/2549. This behavior should be replicated for feature parity.

**Comment by jasongrout** [comment]
Ah. thanks! Reopening then

**Comment by saulshanabrook** [comment]
Adding the `raises-exception` cell tag support is being tracked already in #2412. 

We also have #4026 which asks for another command to run all cells unconditionally of any failures. 

Closing this in favor of those. Comment/reopen if there is something not tracked in those issues that should be addressed here.

**Comment by Mahluza** [comment]
Hi, so has this feature been created yet?

**Comment by Mahluza** [comment]
Hi, sorry, I'm a bit of a novice at all of this. But how would I use this code if I wanted to run all the cells in the IBM CC labs development environment? Would I run it in the first cell? And what would the syntax look like. I copied and pasted that cell and changed 'mynotebook' to the file name, but I got an invalid syntax error.

**Comment by vidartf** [comment]
@Mahluza This feature is being tracked in https://github.com/jupyterlab/jupyterlab/issues/4026.

**Comment by JarnoRFB** [comment]
@Mahluza regarding the use of nbconvert. I have no experience with IBM CC labs, but this code is supposed to be run in a console, not directly in the notebook. So would need to get a handle on a terminal in your environment if that is possible.

**Comment by Mahluza** [comment]
@JarnoRFB okay, thanks

**Comment by dlukes** [comment]
I would argue this is a very useful feature in teaching settings and as such, it deserves a better UI than "google around for a nbconvert command and/or a tag you need to manually add to cell metadata", it's not really discoverable :)

Personally, I prefer the `raises-exception` tag solution (once #2412 is implemented) because it allows for more fine-grained control -- if an unexpected exception is raised in an untagged cell, I'd rather hear about it because it's likely something I need to fix (whereas "Robust Run All Cells" would just ignore all exceptions). But I think it needs a more prominent dedicated toggle in the UI, e.g. in the Cell Inspector sidebar.
