### ISSUE TITLE
Allow a selection of text in an editor to be run in a kernel or console

### ISSUE THREAD

**Issue by drussellmrichie** [jupyterlab/jupyterlab#450]
RStudio and its Python clones (Spyder, Rodeo) usually have this capability, and it's super handy. I know I can do magic like `%run <filename.py>` in an ipython console, but I don't know of a way to use magic to run a selection, and anyway, using keyboard shortcuts from within the editor is more convenient.

Any plans to implement something like this?

Loving what I'm seeing in my exploration of the alpha so far. Great work, devs!

**Comment by jasongrout** [comment]
Definitely from a text file. There are some tricky UI issues, like if you're in a python file and select some text, which kernel should your text go to? Should we associate a kernel with the python file? Or is it better to allow you to send text to different kernels fluidly?

**Comment by jasongrout** [comment]
If you can brainstorm with us how to make this a good experience, it would be really helpful.

**Comment by jasongrout** [comment]
As far as I know, Spyder et. al. punt the issue of multiple kernels by making it so that there is only one (obvious) kernel in the UI. We're more general than that, so our UI issues can be trickier to solve.

**Comment by drussellmrichie** [comment]
Happy to give my input, such as it is!

Ahhh, I see the UI issues. Hmm, well, I think either of the options you suggested (associating a .py file with a kernel vs allowing you to send text to different kernels fluidly) would be fine with me. For my use case, I probably wouldn't need to have more than one kernel open at a time, anyway.

But maybe there's a third option, taking a cue from Spyder -- you choose a particular kernel as the 'active' one, and then any (selections of) scripts automatically get sent to that one?

**Comment by danielballan** [comment]
Would the execution target a kernel *spec* (e.g., Python 3) or a running kernel (e.g., a kernel that already has some variables defined by, say, a notebook)?

**Comment by blink1073** [comment]
In general it could be either.

**Comment by jasongrout** [comment]
> allowing you to send text to different kernels fluidly

I don't know what a good ui for this would be.

> you choose a particular kernel as the 'active' one, and then any (selections of) scripts automatically get sent to that one?

That's an interesting idea. I really like it - have some shortcut keys that would send code to a global default kernel, which you can set and easily change.

Another idea we've had is instead of a text file sending code to a kernel, you could have a text file sending code to a *console* (i.e., same as copy and pasting on the front end). The difference is that if the code is sent to the kernel, it makes a round trip to the server before showing in the console via the stdin message. If the code is sent to a console, then it goes directly into the console and is executed as if the code was originally typed into the console.

**Comment by sccolbert** [comment]
send-to-console seems like a better idea to me at first read

**Comment by jasongrout** [comment]
Yeah, I'm leaning towards the send-to-console too. That's even closer to the matlab/spyder way of doing things as well. 

If there are multiple consoles for the same kernel, then the other consoles will get the input after the roundtrip to the server. That's an argument for sending it straight to the kernel - so every console is on equal footing.

**Comment by drussellmrichie** [comment]
FWIW, Rodeo also sends selections to console. And I think at least in a previous version (I'm not sure that it's doing this now), the keyboard shortcut for running an entire script just entered `%run <filename.py>` at the console.

**Comment by svenefftinge** [comment]
> If there are multiple consoles for the same kernel, then the other consoles will get the input after the roundtrip to the server. That's an argument for sending it straight to the kernel - so every console is on equal footing.
That sounds like a good reason to send the commands to the kernel. Also for the user it shouldn't make a big difference as the input notification is send out immediately by the kernel, no?

Regarding choosing the right kernel. It would be good to have an association per editor, that matches the language of the kernel, picking the most recently used kernel by default and starting one if there is no running kernel of that language.

**Comment by mpastell** [comment]
This would a very nice feature to have. 

I think the default should be to start a new kernel if the user doesn't select one.

It would also be useful to allow associating a kernel with any file type to enable running code from markdown, .tex etc.  files.

**Comment by dhirschfeld** [comment]
This would be a super useful feature! My suggestion regarding the UI would be to have a console associated with the file. If no console is set then the send to console function would pop up a dialog allowing you to select a console to set. The same dialog could then be used to change the default console in future.

One usecase that I envisage is that you could could have py27 and py35 consoles open and quickly select between them to test that your script works in both.

To be explicit, my suggestion is for the following functionality:
* Popup console select dialog and run script in selected console
* Run script in default console, if default is not set, popup console select dialog and run script in selected console
* Popup console select dialog and run selected lines in selected console
* Run selected lines in default console, if default is not set, popup console select dialog  and run selected lines in selected console

The console select dialog could have a checkbox which would make the selected console the default for future runs

**Comment by jasongrout** [comment]
I think this should be in the 1.0 roadmap since it would be a major incentive to moving to JupyterLab from the notebook.

**Comment by fperez** [comment]
If we can pull it off, I fully agree: it would be a very, very valuable enhancement.  Let's keep it tagged 1.0 for now, and we'll see how realistic that is to meet when the time comes.  I wouldn't make it a blocker for 1.0 release, but definitely a desired target.

**Comment by dhirschfeld** [comment]
Testing out the 0.10.0 release and this is probably one of my biggest pain-points. I'm so used to pressing F9 on a selection in spyder that I really notice its absence in JupyterLab. 

As mentioned in the description, people coming from Spyder, or Matlab or RStudio will expect this functionality so it would be an *extremely* valuable addition IMHO.

**Comment by fperez** [comment]
Note @dhirschfeld that this now works, once you attach a console to an editor (search for 'console' in the cmd palette).  Once that's done, any higlighted block of text in the editor will be sent to the console on `Shift-Enter`:

![console-editor](https://cloud.githubusercontent.com/assets/57394/20745608/fc130600-b696-11e6-9505-3d54c12e5055.gif)

Does this fit the use case you had in mind?

One thing  @jasongrout and I discussed recently that would be very nice usability-wise would be auto-detection of boundaries, so you can skip the highlighting step in some cases, like triple-backtick-delimited blocks in markdown.  Agreeing on a boundary marker for regular scripts might be harder (esp. given the language variability), but at least for md it sounds doable and useful.

**Comment by dhirschfeld** [comment]
Thanks @fperez - that  sounds perfect! Looking forward to trying it out with the next release :)

IIUC matlab and spyder have a concept of executable (delimited) cells but I've never found it that useful myself - I'm happy to highlight the relevant lines myself! I think the notebook/nteract cover that usecase pretty well so am personally agnostic to that feature in the console.

I haven't used the current run-selection feature but one very nice thing about the spyder implementation is the pressing F9 will move the cursor automatically to the next line so you can execute your script one line at a time by just repeatedly pressing F9 - see gif below:
![f9](https://cloud.githubusercontent.com/assets/881019/20790598/c6090c0c-b804-11e6-9cf1-72d4499cda7b.gif)

**Comment by fperez** [comment]
@dhirschfeld, we're almost there then! `Shift-enter` already does single-line execution in the editor even without a highlight, the one thing it doesn't do is advance the cursor. That sounds indeed like the most natural behavior.

Technically I think this issue can now be closed, though refinements like advance-on-Shift-enter (easy, I think) and automatic boundary detection in md code blocks (probably less easy) would obviously be nice to have eventually.

@blink1073, would you prefer to close this and open a new one for refinements, or just keep tracking the whole thing here?

**Comment by blink1073** [comment]
I opened #1356 and #1357.  I'm closing this one as having a basic implementation.  Please feel free to reopen if you disagree @drussellmrichie.

**Comment by xappppp** [comment]
Is this in JupyterLab or Notebook? Is there are detailed instruction how to implement this in Jupyter Notebook?
