### ISSUE TITLE
`/lab/tree/nb.ipynb` no longer opens notebook

### ISSUE THREAD

**Issue by consideRatio** [jupyterlab/jupyterlab#4502]
I noticed that in between `0.31.12` and `0.32.0` somewhere, the ability for jupyterhub to open a view of a notebook file by visiting `lab/tree/nb.ipynb` for example vanished.

#### Using 0.32.0 (does not work)
https://mybinder.org/v2/gh/consideratio/jupyter-se-math-teacher/master?urlpath=lab%2Ftree%2Fsource%2Fgradient-descent%2Fgradient-descent.ipynb

#### Using 0.31.12 (works)
https://mybinder.org/v2/gh/consideratio/jupyter-se-math-teacher/mybinder-testing?urlpath=lab%2Ftree%2Fsource%2Fgradient-descent%2Fgradient-descent.ipynb

---

I looked through the [`0.32.0` release notes](https://github.com/jupyterlab/jupyterlab/releases/tag/v0.32.0), perhaps a PR like #4087 could have influenced this unintentionally?

**Comment by jzf2101** [comment]
FWIW I've observed this behavior as well on binder

**Comment by consideRatio** [comment]
I'm new to this code base, but have attempted to figure out what might have happened. So far my best guess is that the changes in #3687 did something, they seem to affect the `/tree` routing.

Is there another routing except `/lab/tree` that should start up something? In the classic notebook, you could write `/terminals/1` to open a terminal, is there something similar in jupyterlab? That way I'd be able to test if this was related only to the `/lab/tree` routing.

**Comment by jasongrout** [comment]
CC @afshin

**Comment by zieherf** [comment]
I see the same behaviour on beta 2 (v0.32.1). When running jupyter-lab and pasting a url into the browser bar, the notebook opens. When launching jupyter-labhub within jupyterhub the notebook does not open. Any thoughts about where those differences may come from?

**Comment by bollwyvl** [comment]
Also as an aside: if there was an alternate URL path rather than the /
mechanism, e.g. "#lab/tree/notebook.ipynb" or "?tree=notebook.ipynb" that
would be cool.

**Comment by consideRatio** [comment]
@FCoulombeau do you open up into jupyterlab if you do that? I didn't.

**Comment by FCoulombeau** [comment]
@consideRatio I removed my comment when I realised that I was mistaking with bug #3966 which has been fixed. Sorry for the noise.

[Issue #3966](https://github.com/jupyterlab/jupyterlab/issues/3966)

**Comment by ckbhatt** [comment]
Reporting same while upgrading from 0.31.8 to 0.32.1

**Comment by ckbhatt** [comment]
This is also reproducible by clicking on Try Jupyter Lab card on http://jupyter.org/try
Earlier it used to open sample Lorenz.ipynb notebook in Jupyter lab as of today it does not though URL is pointing to Lorenz.ipynb

**Comment by zieherf** [comment]
Any update on this unintended behavior? Even some workaround would be appriciated.
Thanks, Franz

**Comment by afshin** [comment]
Thanks for the report. The combination of workspaces and tree paths is an unresolved problem. This is a regression that happened independent of that complexity. We will resolve this for the next release, but the URLs may end up looking different from the current ones because of the additional routing constraints we have.

**Comment by afshin** [comment]
cc @zieherf

**Comment by jzf2101** [comment]
Docs are in #4780
