### ISSUE TITLE
Hash in token prevents opening terminal window

### ISSUE THREAD

**Issue by daanbeverdam** [jupyterlab/jupyterlab#4504]
Opening a terminal window from within JupyterLab didn't seem to work for me. Upon inspecting this issue I found the following error in the javascript console:

```
Uncaught (in promise) DOMException: Failed to construct 'WebSocket': The URL contains a fragment identifier ('fragment'). Fragment identifiers are not allowed in WebSocket URLs.
```

It seems that if your Jupyter token contains a hash (`#`), construction of websocket URLs goes wrong. To reproduce this error, boot up a Jupyter notebook and set the token to `token-with#fragment` (or similar).

For now, my workaround is to just use a token without a hash. Proposed solution: either update the token requirements or somehow fix the websocket URL construction.

**Comment by jasongrout** [comment]
It sounds like somewhere there needs to be a URL encoding step?

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/4516, thanks again!
