### ISSUE TITLE
Cannot run Javascript in Jupyter lab, but works in Jupyter notebook

### ISSUE THREAD

**Issue by vatodorov** [jupyterlab/jupyterlab#4508]
Hi,

The code below works fine in Jupyter Notebook, but in Jupyter Lab I get the error:
"Visualization omitted, Javascript library not loaded! Visualization omitted, Javascript library not loaded! Have you run `initjs()` in this notebook? If this notebook was from another user you must also trust this notebook (File -> Trust notebook). If you are viewing this notebook on github the Javascript has been stripped for security."

Clicking "Trust notebook" doesn't fix the issue, and I get the same error.

Here is the code to replicate the error:
```
import xgboost
import shap

shap.initjs()

X, y = shap.datasets.boston()
model = xgboost.train({"learning_rate": 0.01}, xgboost.DMatrix(X, label = y), 100)

shap_values = shap.TreeExplainer(model).shap_values(X)

shap.force_plot(shap_values[0,:], X.iloc[0,:])
```

**Comment by dopplershift** [comment]
I think this is related to #3118. tldr; Unlike the notebook, JupyterLab does not run arbitrary javascript code--instead a custom extension is needed.

**Comment by jasongrout** [comment]
It looks like shap relies on the iml library (https://github.com/interpretable-ml/iml), which has not been ported to work with JupyterLab. It looks like IML should make a JupyterLab extension containing its rendering logic, and then shap can send information to the IML Javascript to render it.

The next step is probably opening an issue in the IML repo about making a JupyterLab extension.

**Comment by jasongrout** [comment]
Closing as resolved from our perspective - the issue of porting to work in JLab should be over in the iml library (and we're happy to help devs get started in that!)
