### ISSUE TITLE
Add a json editor

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#451]
This looks promising: https://github.com/josdejong/jsoneditor

**Comment by eskirk** [comment]
@jasongrout I'm gunna check this out, seems simple enough

**Comment by jasongrout** [comment]
I'm not sure if the typing file still works, though it shouldn't depend on the repo location.

I'd say this is probably lower priority than https://github.com/jupyter/jupyterlab/issues/472, though.

**Comment by xtrntr** [comment]
This looks interesting, but i'm not quite entirely sure how and where a JSON editor is going to fit in.

**Comment by jasongrout** [comment]
I think @gnestor worked on this. Grant, can you comment?

**Comment by gnestor** [comment]
https://github.com/jupyterlab/jupyterlab_json is currently working for viewing JSON (not editing). I've managed to integrate https://github.com/gnestor/notebook_json into the same Python package, so after I publish to PyPI, a user should be able to `pip install jupyterlab_json` (or `pip install jupyter_json`?) and install extensionsfor both notebook and lab. I like the idea of a JSON editor but I'd like to hear more about how it might be used vs. using a text editor.

**Comment by cocoaaa** [comment]
Currently, it seems .geojson files are not recognized as json-like format in the editor. It would be nice if the editor does so:
![image](https://user-images.githubusercontent.com/8037983/57551557-29434b80-731e-11e9-939a-75d90bb8165e.png)

**Comment by gnestor** [comment]
Good catch @cocoaaa! It's an easy fix. I'll submit a PR 👍

**Comment by gnestor** [comment]
https://github.com/jupyterlab/jupyterlab/pull/6349
