### ISSUE TITLE
JupyterLab with sublime text keymap

### ISSUE THREAD

**Issue by aghoshpub** [jupyterlab/jupyterlab#4511]
This blog discusses how to add sublime text keymap to jupyter notebook. How can we do the same for jupyter lab?

http://blog.rtwilson.com/how-to-get-sublime-text-style-editing-in-the-ipythonjupyter-notebook/

**Comment by ian-r-rose** [comment]
Hi @aghoshpub, non-default keymaps are not currently supported in the notebook (though extensions can provide them). See discussions on #3992, #1362

**Comment by ryantam626** [comment]
Hello :wave: ! (And sorry for reviving this) I started something to get it going, it's not perfect but it does scratch the itch of multiple cursors (well at least for me :grinning: ). https://github.com/ryantam626/jupyterlab_sublime

**Comment by aghoshpub** [comment]
Great! "opinionated" is just fine :)
