### ISSUE TITLE
Keyboard shortcut to add commonly used character sequences. 

### ISSUE THREAD

**Issue by TariqAHassan** [jupyterlab/jupyterlab#4519]
In R-Studio, it is possible to enter `cmd + shift + m` to inset a 'pipe' (`%>%`) into the editor (and console for that matter).

The pipe operator has been implemented in Python in a few places such as [dfply](https://github.com/kieferk/dfply) -- its pipe operator is `>>`.

Is it possible to do something similar (i.e., `cmd + shift + m` = `>>`) in JupyterLab?
I have looked at the available keyboard shortcuts and did not see a clear way to do so, but perhaps I missed something.

**Comment by jasongrout** [comment]
(Thinking about how to do this technically...)

Perhaps we should define a new editor command that is 'Insert text' with args of the text it should insert. Then a user could assign a keyboard shortcut to that command with the args specifying whatever text they wanted

For example, with this diff applied:

```diff
diff --git a/packages/codemirror-extension/src/index.ts b/packages/codemirror-extension/src/index.ts
index c88094327..cc716c766 100644
--- a/packages/codemirror-extension/src/index.ts
+++ b/packages/codemirror-extension/src/index.ts
@@ -51,6 +51,9 @@ namespace CommandIDs {
 
   export
   const findAndReplace = 'codemirror:find-and-replace';
+
+  export
+  const insertText = 'codemirror:insert-text';
 }
 
 
@@ -233,6 +236,20 @@ function activateEditorCommands(app: JupyterLab, tracker: IEditorTracker, mainMe
     isEnabled
   });
 
+  commands.addCommand(CommandIDs.insertText, {
+    label: 'Insert Text',
+    execute: args => {
+      let widget = tracker.currentWidget;
+      if (!widget) {
+        return;
+      }
+      const text: string = args['text'] as string || '';
+      let editor = widget.editor as CodeMirrorEditor;
+      editor.doc.replaceSelection(text);
+    },
+    isEnabled
+  });
+
   commands.addCommand(CommandIDs.changeMode, {
     label: args => args['name'] as string,
     execute: args => {
```
and then this user-defined keyboard shortcut:
```
    "pipeshortcut": {
      "command": "codemirror:insert-text",
          "args": {
              "text": ">>"
          },
      "keys": [
        "Accel Shift M"
      ],
      "selector": "body"
    }
```
we can insert `>>` in the text editor with `cmd + shift + m`.

**Comment by jasongrout** [comment]
That said, I think it makes sense to define a command to insert/replace a selection at the editor level, that would work in any notebook or text file using the editor. Perhaps it should even be scoped to the editor language, if possible.

**Comment by TariqAHassan** [comment]
@jasongrout 

Very cool! Yes, that would be great to add.

It would also help make the transition from R-Studio to JupyterLab smoother (i.e., users could add  a `%>%` shortcut, making JupyterLab feel more familiar).

**Comment by TariqAHassan** [comment]
@jasongrout 

Hello again. 

I know you and the team are very busy people with limited time, but I was wondering if even a rough version of this feature (based on your first post above) has any chance of being implemented in a future version of JupyterLab? 

Cheers

**Comment by jasongrout** [comment]
> I was wondering if even a rough version of this feature (based on your first post above) has any chance of being implemented in a future version of JupyterLab?

I think it would be great to have in! A PR is especially welcome, if you'd like to give it a go.

CC @ian-r-rose - do you think this would be a `good first issue` issue?

**Comment by ian-r-rose** [comment]
Yeah, I think it makes sense for a good first issue. I like your idea for the implementation as well.

**Comment by ian-r-rose** [comment]
Also, I agree that this is a command that could exist at the editor services level. Practically speaking, that would mean it would go in the `codemirror-extension` package.

**Comment by jirivrany** [comment]
Hi, sorry for dumb question. I would like to help with this. But I'm not sure what needs to be done? The implementation of insertText command by @jasongrout seems to be complete. What's next?

**Comment by TariqAHassan** [comment]
@jirivrany 

I won't have enough free time to take a crack at this until next week at the earliest so by all means go for it!

**Comment by jasongrout** [comment]
> What's next?

I didn't actually make a PR, I just changed my local install. I wasn't sure where the change should properly go (that's what @ian-r-rose's comment was about). So what's next is:

1. Understanding Ian's comment about where such a change should live.
2. Make a PR.

**Comment by jirivrany** [comment]
Thanks @jasongrout I will put it to the codemirror-extension package as @ian-r-rose suggested. Is there a way how to test the commands please? I can't see test suite for this package, only for codemirror.

**Comment by ian-r-rose** [comment]
We don't currently have a good setup for testing commands in the command registry (though perhaps we should).

**Comment by jirivrany** [comment]
OK. I just did manual test and it works in text editor as expected. But it's not working in the console or notebook. Are they using different editor widget? @TariqAHassan mentioned that it would be good to have this feature in the console too.

**Comment by ian-r-rose** [comment]
Ooh, right. We don't actually have an instance tracker for the inline editors that are used in notebooks and consoles. Maybe this is trickier than we had first thought.

We *could* register a command for each of the file editor, notebook, and console extensions that insert a string into the currently-used activity. There would be some duplication of code in registering those commands, but they could all read from the same settings key to get to get the to-be-inserted text.

**Comment by jirivrany** [comment]
@ian-r-rose from the user perspective it is quite confusing when the command works in one editor and don't in another one. 

If you can advice what widgets are used as file editor etc. I can try to prepare and test the commands.

**Comment by sperezconesa** [comment]
Hello,
I have add the following short-cut:
```
{   
    "pipeshortcut": {
      "command": "codemirror:insert-text",
          "args": {
              "text": ">>"
          },
      "keys": [
        "Ctrl A"
      ],
      "selector": "body"
    }
}
```
I have just updated jupyter-lab. I have tried the shortcut in regular cells, markdown cells and in a markdown file I am editting and it does not do anything. Am I missing something? Is this change not available yet?
Thank you very much,
Sergio

**Comment by jasongrout** [comment]
This `insert-text` command needs to be added to JuptyerLab for this keyboard shortcut to work.

**Comment by robsalasco** [comment]
any news about this issue?

**Comment by jasongrout** [comment]
I think adding the insert-text command as noted above is the thing needed, and why this is a good first issue. So I think right now a pull request is welcome. Would you like to submit one adding that command?

**Comment by randy3k** [comment]
For future users, there is [jupyterext-text-shortcuts](https://github.com/ryanhomer/jupyterext-text-shortcuts)

**Comment by dLamSlo8** [comment]
I started working on this issue, and have the commands made for the notebook, text editor, and console, and the only issue I see currently is the fact that, as they are different commands, they must be mapped to different shortcuts for each. I was wondering if there was a way to map multiple commands to different selectors, but with the same keyboard shortcut?

I checked out issue #7138 regarding multiple commands, but since the notebook, text editor, and console require different selectors, it seems like a different approach would be necessary. Any thoughts?

**Comment by jasongrout** [comment]
> I was wondering if there was a way to map multiple commands to different selectors, but with the same keyboard shortcut

No. Even if they had the same command, each shortcut/selector pair is a separate entry in the shortcut database.

Perhaps we can introduce a new selector that works for all the places we want a given text shortcut to work? For example, a class that could be applied on the editors in all three places. Then you could have a single shortcut/selector pair, but that would also mean a single command invoked, so you'd have to find a way to do the insertion from a single command.

**Comment by jasongrout** [comment]
> For future users, there is [jupyterext-text-shortcuts](https://github.com/ryanhomer/jupyterext-text-shortcuts)

Nice!

**Comment by dLamSlo8** [comment]
@jasongrout Where would such a command live, given each command already belongs in their own context (i.e. notebook command in notebook-extension, console in console-extension etc.)?

**Comment by jasongrout** [comment]
I think the editor for each is provided by the single package: https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror-extension/src/index.ts. Perhaps that is the appropriate place?

**Comment by dLamSlo8** [comment]
@jasongrout I think the commands defined in that file only work in the context of a full document editor as opposed to all inline editors, so I'm unsure of how to approach it there.

**Comment by jasongrout** [comment]
The full document editor is in this extension: https://github.com/jupyterlab/jupyterlab/tree/master/packages/fileeditor-extension

The file editor extension uses the codemirror extension, but so does the notebook, etc.

**Comment by dLamSlo8** [comment]
Okay, so I managed to create a single command that would insert text depending on the context, using the various trackers associated with file editors, notebooks, and consoles. They all depend on the same editor's function to insert text. Is this an appropriate approach to take? 

And in this case, would I still need the individual commands for each of the editor, notebook, and console, if they are all being handled within a single command? I was thinking it could be useful to keep in case someone wanted, say, a notebook-specific insert text command.

**Comment by jasongrout** [comment]
This is now possible (thanks to #7908), and mentioned in the release notes for JupyterLab 2.1.0: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#id164
