### ISSUE TITLE
IDE advice for authoring Jupyter Lab Extensions

### ISSUE THREAD

**Issue by habemus-papadum** [jupyterlab/jupyterlab#4526]
Hi - I'm interested in developing a Lab Extension, and, as I don't currently have a TypeScript dev flow, and Jupyter Lab is a somewhat large Typescript project, I was wondering if the existing developers could provide some advice on what IDE's provide a good experience.    I would be open to VS Code, WebStorm/PyCharm, emacs, or vim, and I would hope for :
- good semantic code completion and navigation across the internal typescript packages and also w.r.t. 3rd party node packages
- easy debug flow for running the examples (I'll do this first) 
- easy debug flow for a plugin developed out of tree -- still  would hope for good navigation and completion with w.r.t the main code base -- or should I just develop "in tree"  using  a  (`.gitignore`d)  symlink to my out of tree code -- for a lot of big code bases this seems to be the path of least resistance for plugin development....

- reasonably simple upfront setup complexity

I'm not really looking for detailed instructions, but rather an "existence proof" e.g. "vscode will work flawlessly out the box" and I'm happy to take it from there

thanks! nehal

**Comment by jasongrout** [comment]
I use vscode and it works great.

**Comment by habemus-papadum** [comment]
thanks! -- I'll try that and close this in a day or so

**Comment by jtpio** [comment]
@saulshanabrook documented his VS Code setup in https://github.com/jupyterlab/jupyterlab/issues/3979, so you can have a look at that too (the debugger part is particularly useful).
