### ISSUE TITLE
pyldavis.display() not displaying in Jupyterlab 0.32.0

### ISSUE THREAD

**Issue by cwrather** [jupyterlab/jupyterlab#4531]
pyldavis.display() creates an interactive graphic. It works fine in Jupyter Notebook 5.0.0. In Jupyterlab 0.32.0 it does not give an error, but it also does NOT display the graphic. pyLDAvis version 2.1.1.

**Comment by jasongrout** [comment]
I looked into the pyldavis codebase a bit. It looks like it is using custom Javascript that is very specific to the classic Notebook environment, and it will need to be ported over to be a JupyterLab (probably as a JupyterLab extension). Can you open an issue over on the pyldavis repo about porting to JupyterLab?

**Comment by cwrather** [comment]
Sure will!

**Comment by jasongrout** [comment]
Great. Let's close this and move the discussion over there, then.
