### ISSUE TITLE
Build examples in isolation - theme-light-extension not publishing style folder

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#4535]
I have copied the examples folder out of the src tree and tried to build them.

e.g. in the cell folder, I run `yarn build` and get `Module not found: Error: Can't resolve '@jupyterlab/theme-light-extension/style/embed.css' in...`

The workaround is  `cp -r JLAB_SRC/packages/theme-light-extension/style node_modules/@jupyterlab/theme-light-extension/`, Then `python main.py` correctly renders the notebook.

Should the `theme-light-extension` be updated to publish the `style` folder?

**Comment by jasongrout** [comment]
CC @saulshanabrook - he recently changed things to do a preprocessing step.

**Comment by echarles** [comment]
mmh I see #2813 nearly 1 year ago describes the same issue, but can not find anything on the preprocessing step - @saulshanabrook any help on this? Thx in advance. Eric

**Comment by saulshanabrook** [comment]
Yep, it's the same issue as you pointed to. The problem is that the theme extensions don't include the `embed.css` when packaging. i.e. it's not in their `files` in the `package.json`.

So I think we have two options:

1. Ship the theme extensions with the `./style/embed.css`
2. Compile the `./style/embed.css` as the `./style/index.css` in the extensions, so that both can be reference from the shipped `./static` directory.

Do we only use these embed styles for the examples?

**Comment by echarles** [comment]
Option 1 will also need to ship all subcontent of the `./style` folder (cfr. css variables).
I would go for Option 2 (we would a bigger css file, but I guess this is negligible).

Not sure embed styles are used somewhere else, but I will do on my side at some point in time (I hope sooner than later) - I have also seen other potential usage (maybe #1862 ?)

**Comment by saulshanabrook** [comment]
Sounds good. I implemented that in #4541. If you want to try that branch, that would be helpful. However, you will have change the examples to install the local version of the theme after building it `yarn/npm run build`.

**Comment by echarles** [comment]
I see the change you made to the example, but I don't see any change on the `theme-light-extension` itself.

To build a new version of the them, from the `SRC/packages/theme-light-extension`, I run yarn build. I guess this is what you mean but the package definition didn't change, so the style folder will not be published.

```
 "files": [
    "lib/*.d.ts",
    "lib/*.js.map",
    "lib/*.js",
    "static/index.css",
    "static/*.ttf"
  ],
```

Shouldn't the package.json be updated to include the style folder?

**Comment by echarles** [comment]
OK got it (I didn't scroll enough on the diff page).

I have applied the patch, built JLab, copied the new them artifcats to the node_modules folder of the example, change the path for the css in the source example, complied, run and it works great.

+1
