### ISSUE TITLE
Terminal in Win10 causes high CPU usage

### ISSUE THREAD

**Issue by DaymondLing** [jupyterlab/jupyterlab#4539]
I'm running JupyterLab 0.31.12 on Win10 Home 1803 update. When I open the terminal window which runs Powershell, CPU usage jumps up significantly. Tested on a few machines, it happens consistently. 

Using "exit" to terminate Powershell brings machine back down to idle. Console shows the following:
[I 10:41:43.021 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
[I 10:41:50.059 LabApp] EOF on FD 1556; stopping reading
[I 10:41:50.161 LabApp] Terminal 1 closed
Websocket closed

Closing the tab using the "X" on mark does not shutdown the terminal session, CPU usage remain high until JupyterLab console is shutdown. The console does not receive the EOF message and keeps the socket open even though the tab is already gone.

This is not a showstopper as machine, JupyterLab and terminal continue to work, but the fan will kick in shortly and is annoying. Went back a few versions of JupyterLab and it is persistently there.

**Comment by vidartf** [comment]
This would be easier to hunt down if you could answer the following questions:

1. Does this happen for the latest release of jupyterlab as well?
2. Which process is using the CPU? The browser? python? both? something else?
3. If you open up the browser console, are there any error messages when the CPU use is high? What about the server logs? Try launching lab with `jupyter lab --debug` (sets the log threshold lower, so more information is included).

**Comment by DaymondLing** [comment]
1. Yes, 0.31.12 is the current release of JupyterLab
2. Win10 task manager shows 6 processes running, it's Python that's spinning. The other processes, Console Window Host, Windows Powershell, jupyter-lab.exe, winpty-agent.exe are all idle.

![image](https://user-images.githubusercontent.com/25850001/39765793-aaff3164-52b0-11e8-84c1-cb7ba1676bc2.png)

3. I will look at the console and report back if I see something

**Comment by vidartf** [comment]
FYI: The latest version released is 0.32.1.

**Comment by ccordoba12** [comment]
This is a problem in [pywinpty](https://github.com/spyder-ide/pywinpty). It'll be solved once we release a new version of it (hopefully in a couple of weeks).

**Comment by jasongrout** [comment]
Thanks for letting us know, @ccordoba12

**Comment by DaymondLing** [comment]
pywinpty-0.5.3 addressed this issue. Thanks everyone, @ccordoba12.
