### ISSUE TITLE
Incorrectly automatching single quote ' in Scala cells

### ISSUE THREAD

**Issue by parente** [jupyterlab/jupyterlab#4544]
Incorrect (or less than ideal?) automatching of single quotes in a Scala code cell seems to have started in Lab 0.32.

![lab](https://user-images.githubusercontent.com/153745/39818759-a45f64ae-536f-11e8-9d01-7ef53c9d58a7.gif)

In contrast, a Scala cell editor for the same kernel in classic notebook 5.4.x does the right thing by not automatching single quotes.

![classic](https://user-images.githubusercontent.com/153745/39818615-51962870-536f-11e8-8209-2f2932e27b38.gif)

**Comment by ian-r-rose** [comment]
@parente, is this a new behavior as of 0.32? As far as I know we don't have any mode-specific auto-matching setting. You can, however, turn off auto-matching for code cells in the advanced settings editor (admittedly annoying if you only want to do this for certain kernels).

**Comment by parente** [comment]
@ian-r-rose Yep, it was new behavior in 0.32 and continues in 0.33. I haven't checked 0.34 yet. Our Scala + JLab users are aware of turning off auto-matching as a workaround or switch back to classic.

**Comment by parente** [comment]
Correction: I *think* it was new in 0.32, but I'm second guessing myself now as I'm trying to recall the conversation with the engineer who pointed it out to me. I can't remember if he was using Lab before we moved to 0.31 or not. I'm still leaning toward, yes, he was, since we've been deploying it for quite some time now.

**Comment by jasongrout** [comment]
It's also a problem in the current codemirror: https://codemirror.net/mode/clike/scala.html

**Comment by jasongrout** [comment]
Wait: single quotes aren't strings in scala, right? http://www.java2s.com/Tutorials/Java/Scala/0150__Scala_Literal_Values.htm

a single quote is the way to quote a symbol, like `'x`, right?

(I know almost nothing about scala...)

**Comment by jasongrout** [comment]
Oh wait, the problem here is that when you insert a single quote, the "closing" single quote is input as well, even though it shouldn't be? (Sorry, a bit slow here on scala...)

**Comment by jasongrout** [comment]
From https://codemirror.net/doc/manual.html#addons, the docs of the close brackets extension says:

> Defines an option autoCloseBrackets that will auto-close brackets and quotes when typed. By default, it'll auto-close ()[]{}''"", but you can pass it a string similar to that (containing pairs of matching characters), or an object with pairs and optionally explode properties to customize it. explode should be a similar string that gives the pairs of characters that, when enter is pressed between them, should have the second character also moved to its own line. By default, if the active mode has a closeBrackets property, that overrides the configuration given in the option.

Sounds like the scala mode should have a closeBrackets property to override the configuration. It looks like it has *something*: https://github.com/codemirror/CodeMirror/blob/90f484740e6fa692ef2d760fcf68527c900d06d9/mode/clike/clike.js#L576

**Comment by jasongrout** [comment]
Looks like we can make a PR to the scala mode to add the pairs option override for closeBrackets: https://github.com/codemirror/CodeMirror/blob/90f484740e6fa692ef2d760fcf68527c900d06d9/addon/edit/closebrackets.js#L13

**Comment by ian-r-rose** [comment]
It may be that we are inadvertently overriding the behavior of the mode. Maybe we should not apply `autoCloseBrackets` if the mode has a `closeBrackets` property?

**Comment by jasongrout** [comment]
No, it looks to me like the mode's closeBrackets property is about making the autoCloseBrackets option work. closeBrackets doesn't do anything by itself.

**Comment by parente** [comment]
@jasongrout A bit late but to answer your question:

> The problem here is that when you insert a single quote, the "closing" single quote is input as well, even though it shouldn't be? (Sorry, a bit slow here on scala...)

Yes. A single quote leading a name is a [Symbol literal](https://www.scala-lang.org/files/archive/spec/2.11/01-lexical-syntax.html#symbol-literals) in Scala (e.g., `'x`)

**Comment by jasongrout** [comment]
PR submitted: https://github.com/codemirror/CodeMirror/pull/5568

**Comment by blink1073** [comment]
Open source FTW!

**Comment by ian-r-rose** [comment]
Nice!

**Comment by ian-r-rose** [comment]
This is fixed now. Thanks @jasongrout!
