### ISSUE TITLE
JupyterLab editor does not recognize f95 file extension

### ISSUE THREAD

**Issue by mdekstrand** [jupyterlab/jupyterlab#4553]
I am using the `.f95` file extension for Fortran 95 code, to ensure `R CMD SHLIB` and the underlying Fortran compiler automatically compile it as Fortran 95.

The JupyterLab editor does not recognize this file extension as containing Fortran code. If I rename the file to use `.f`, the editor highlights it as Fortran, but then R does not know to compile it with the correct Fortran version.

**Comment by jasongrout** [comment]
Do you mean that the syntax highlighting is not correct when opening an `.f95` file?

**Comment by jasongrout** [comment]
It looks like codemirror (the editor we use) does not recognize `.f95` as a fortran suffix: https://github.com/codemirror/CodeMirror/blob/32f3d3e95b15e2403684bd75b13a6315a84b4ce9/mode/meta.js#L54

**Comment by jasongrout** [comment]
We do modify the codemirror modeinfo things at https://github.com/jupyterlab/jupyterlab/blob/53a60f7016a96787765ba40851a4200d8cd5a463/packages/codemirror/src/codemirror-ipython.ts#L30 for example. Perhaps we can add `.f95` as a suffix for the fotran mode?

**Comment by jasongrout** [comment]
(though we probably ought to be careful, if the highlighter is written for f90, is there new syntax in f95 that would cause it to mess up?)

**Comment by ian-r-rose** [comment]
This PR could also be made to CodeMirror itself. In my experience Marijn is pretty liberal about adding file extensions to modes.

**Comment by jasongrout** [comment]
Very good point, and a much more natural place to make the PR. Thanks!

**Comment by ian-r-rose** [comment]
@mdekstrand As it stands you should be able to select the Fortran mode manually in the "View" menu. It is much more annoying than correct auto-detection, but it should work.

**Comment by wdouglashall** [comment]
Submitted a pull request to CodeMirror.

**Comment by ian-r-rose** [comment]
This has now been merged into CodeMirror, and has been published as 5.42. Thanks @wdouglashall! I'll leave this open until we can bump versions.

**Comment by ian-r-rose** [comment]
This is now in JupyterLab master. Thanks again @wdouglashall!
