### ISSUE TITLE
Closed kernel session appears again

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#4556]
I encounter the issue that some closed kernel session show up again later. I'm using the latest version (0.32.1) of JupyterLab together with JupyterHub.

**Comment by ian-r-rose** [comment]
Hi @dclong, sorry for the slow response. Can you check whether you still see this issue with 0.34, and if so, do you have a way to reproduce it?

**Comment by ayushgupta2959** [comment]
I am facing a similar issue. After closing a kernel from kernel session it restarts immediately again.

**Comment by dclong** [comment]
@ian-r-rose I haven't see this issue for a really long time. I assume it has been fixed. Although I still see the issue of closed terminal show up again frequently.

**Comment by dclong** [comment]
@ian-r-rose I haven't see this issue for a really long time. I assume it has been fixed. Although I still see the issue of closed terminal show up again frequently which is tracked in the issue https://github.com/jupyterlab/jupyterlab/issues/5061.
