### ISSUE TITLE
"Go to definition" with ctrl+click - a feature request

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#4562]
Many IDEs have some sort of "go-to-definition" function, notably PyCharm. It is often activated with "ctrl + click" when clicking on a function or variable name.

When my notebook exceeds two screens in length I would often very like to use such functions in jupyter lab.  

Is such a feature in scope for JupyterLab? Or maybe it was already proposed or maybe it is already available but I could not find it?

Technically it seems feasible to detect the ctr+click on objects classed "cm-variable" and similar, but I guess that finding the definition might require some advanced parsing/interpreting of the code.
But wait it's not really needed! Having it activating document-wide search for occurrences of the same variable would be enough. By the way I find it difficult to search occurrences across the whole notebook as ctrl+f activates in-cell search by default.

Edit: and if someone was to implement such feature (again if it is not buried somewhere already), should it be developed as an extension or in the jupyterlab core?

**Comment by saulshanabrook** [comment]
I think implementing it as an extension is a good way to start. That way, you can get people trying it out quickly and iterating on how it works.

Another option, although I don't know how feasible this is, is to build off the existing [monaco editor support](https://github.com/jupyterlab/jupyterlab/issues/135) and [add language server support](https://typefox.io/teaching-the-language-server-protocol-to-microsofts-monaco-editor). That would have to tie into a backend service that provides the smarts.

**Comment by krassowski** [comment]
Ok, I went crazy today and implemented a nasty workaround in jquery:

![ctrl-click](https://user-images.githubusercontent.com/5832902/47955459-47577a00-df90-11e8-87e4-471c238b9d07.gif)

It goes like this:
```html
%%html
<script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
```

and:

```js
%%javascript
// $('body').unbind() // useful for detaching the old handler
$('body').on('click', '.cm-variable', function(event){
    if(event.ctrlKey)
    {
        let variable = $(this)
        let top = variable.offset().top
        let all_variables = $('.cm-variable').filter(
            function(){
                let next_sibling = $(this).next()
                return next_sibling && (
                    $(this).text() == variable.text()
                    &&
                    next_sibling.hasClass('cm-operator')
                    &&
                    next_sibling.text() == '='
                    // To match += too:
                    // next_sibling.text().indexOf('=') !== -1
                )
            }
        ).sort(function(a, b){
            return Math.abs($(a).offset().top - top) > Math.abs($(b).offset().top - top) ? 1: -1
        })
        let definition = all_variables.first()
        let highlight_class = 'cm-animate-fat-cursor'
        
        let line = definition.parent()
        let textarea = line.closest('.CodeMirror').find('textarea')
        textarea.focus()
        line.addClass(highlight_class)
        
        setTimeout(function(){
            line.removeClass(highlight_class)
        }, 2000)
    }
    event.preventDefault();
    return false;
})
```

I know that the code above looks silly in 2018, but if it is stupid and works then it's not too stupid.

I've found that CodeMirror has a demo for [tern integration here](https://codemirror.net/demo/tern.html), which shows how to implement jumping around using CodeMirror interface. I hope that someone who can comprahend the jupyterlab internals (I know - the docs are great, though it is still a lot to go through) may use this to implement this feature properly.

I am really excited about the monaco support, I hope that @gnestor will decide to publish it sometime soon :)

**Comment by krassowski** [comment]
I've published an extension: [jupyterlab-go-to-definition](https://github.com/krassowski/jupyterlab-go-to-definition) today.

It supports both notebook and text editor, has a keybord shortcut (with commands in palette) and a setting to change action key (modifier) from default <kbd>Alt</kbd> + <kbd>click</kbd>. It's written with the possibility that CodeMirror editor might no longer be the only editor in mind. Supports primarly Python for now, but I plan to add some R support soon.

PS. I would love to hear some feedback as this is my first experience with TypeScript.

**Comment by gnestor** [comment]
@krassowski Excellent!! I will give it a try now. Thanks for working on this 👍👍
