### ISSUE TITLE
Correct keymap to customize "restart kernel and run all cells"?

### ISSUE THREAD

**Issue by concretevitamin** [jupyterlab/jupyterlab#4568]
I want to customize.  Looking into the default keymap I see only one runmenu-related key:
```
    // [missing schema title]
    // [missing schema description]
    "runmenu:run": {
      "command": "runmenu:run",
      "keys": [
        "Shift Enter"
      ],
      "selector": "[data-jp-code-runner]"
    }
```
What's the right way to adapt this to "restart kernel and run all cells"?

I tried putting the following into `User Overrides` to no avail:
```
{
    // [missing schema title]
    // [missing schema description]
    "runmenu:restart-kernel-and-run-all-cells": {
      "command": "runmenu:restart-kernel-and-run-all-cells",
      "keys": [
        "Ctrl Shift Enter"
      ],
      "selector": "[data-jp-code-runner]"
    }
}
```

**Comment by ian-r-rose** [comment]
Hi @concretevitamin, @GindaChen, we should do a better job of documenting the commands that are available to override. At the moment, you have to look at where they are defined to know the name of the command (see `packages/mainmenu-extension/src/index.ts`).

For this particular command, try `"runmenu:restart-and-run-all"`

**Comment by concretevitamin** [comment]
Works for me, thanks.
