### ISSUE TITLE
Server Connection Error - Invalid Response: 401 Unauthorized

### ISSUE THREAD

**Issue by Koushik95** [jupyterlab/jupyterlab#4578]
Hi, I'm working with jupyterlabs and I keep getting the above title mentioned error after every say half an hour or so, but when i click on the 'OK' button in the pop-up, everything seems to return back to normal and I'm able to continue working again. Any reason as to why this error keeps popping up?

**Comment by saulshanabrook** [comment]
I am not sure. Do the logs say anything?

**Comment by jasongrout** [comment]
Closing as no response. @Koushik95 - please comment below if you'd like to continue the discussion.

**Comment by cg1008syf** [comment]
hi, i am experiencing similar issue, when accessing jupyterlab from anaconda enterprise.  It's like every hour, on the clock, i get the pop up ... clicking 'ok' does not resolve it, for executing another command gives rise to the pop up again.  The only thing that works is if I refresh the browser.  The same behavior is not seen in jupyter notebook on Anaconda Enterprise.  Any suggestions will be much appreciated.  If you need more information, please let me know, and i will provide.  I will be monitoring this thread....
