### ISSUE TITLE
Use phosphor's uuid function

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4579]
We have our own UUID function: https://github.com/jupyterlab/jupyterlab/blob/610a2806bb883c8f150633bbe1e647a4c207e457/packages/coreutils/src/uuid.ts

We should instead use Phosphor's, which is more secure, more correct, and probably faster: https://github.com/phosphorjs/phosphor/blob/cdb412e9dfb9a987b99143e4be79d477e5136832/packages/coreutils/src/uuid.ts

This issue involves deleting our UUID function and switching where ever we use it to use phosphor's instead.

**Comment by jasongrout** [comment]
CC @sccolbert

**Comment by ian-r-rose** [comment]
There was some chatter on the Gitter channel where a user started working on this. I am not sure if it was completed, so feel free to take it on.

**Comment by jirivrany** [comment]
Thanks, I will start right now.

**Comment by jasongrout** [comment]
Great! Thanks!

**Comment by jirivrany** [comment]
I have one question. My understanding is, that the functions differ in return type. What should I do? Change the existing function and rewrite it as the wrapper around the Phosphor's one with correct return type. Or change the type of all the ids created by existing uuid function?

**Comment by jasongrout** [comment]
Both functions return a string, right? Phosphor's `UUID.uuid4()` returns a string, just like the jlab `uuid()` function does.

**Comment by jirivrany** [comment]
You are right, I'm sorry. I was doing the import wrongly and TS was showing me an error.
