### ISSUE TITLE
LATEST UPDATE CRASH

### ISSUE THREAD

**Issue by wxprofessor** [jupyterlab/jupyterlab#4581]
I performed a conda update --all yesterday, and today when working on sqlite lessons, jupyter lab consistently crashes when attempting to convert a pandas dataframe to sql. Specifically a few seconds after initiating:

adult_data_df .to_sql('sqladb', engine, if_exists='replace')

from this notebook:
https://github.com/wxprofessor/acadgild.assignment.13.1/blob/master/assignment.13.1.ipynb

Since the same notebook worked last week multiple times (I'm actually working on the next assignment today using the same DB) , I'm not sure if changes in jupyter lab (I noticed the update), sqlite, or something else is causing the issue. 

Chrome is my default browser, but I tried a jupyter-lab --no-browser and then used vivaldi, and that browser crashed as well :/

**Comment by saulshanabrook** [comment]
If you run that same code in a python interpreter, does the interpreter crash? What if you run it with jupyter notebook?

**Comment by jasongrout** [comment]
Closing since the author did not follow up.
