### ISSUE TITLE
Simplify FAQ given that it's Now In the Docs

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#4584]
See https://github.com/jupyterlab/jupyterlab/issues/3835 and https://github.com/jupyterlab/jupyterlab/pull/4573 as a reference

Also, stability caveats should be emphasized re API instead of daily use now that people are using Jab

**Comment by jasongrout** [comment]
The faq is at https://github.com/jupyterlab/jupyterlab/tree/master/packages/faq-extension
