### ISSUE TITLE
Build fails with Node 10

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#4585]
Our build currently fails when using Node.js >= 10. 

This is related to an issue with yarn: https://github.com/yarnpkg/yarn/issues/5727

A temporary workaround would be to add the following to our `.yarnrc`:

```
--ignore-engines true
```

Related: https://github.com/jupyterlab/jupyter-renderers/issues/132

**Comment by cphyc** [comment]
This is related to the recently merged PR on the yarn repository (see https://github.com/yarnpkg/yarn/pull/5769). 
A workaround is to replace the jupyter-provided version of yarn (v1.5.0) by the updated one. For example on Linux you can do, assuming you use a virtualenvs called `foo`
```bash
wget https://15920-49970642-gh.circle-artifacts.com/0/yarnpkg/yarn-1.6.0.js -O $HOME/.virtualenvs/foo/lib/python3.6/site-packages/jupyterlab/staging/yarn.js
```
In the long term, jupyter should include an updated version of yarn (or use a system-wide installation).

**Comment by vidartf** [comment]
Still relevant after https://github.com/jupyterlab/jupyterlab/pull/4804

**Comment by vidartf** [comment]
Xref #4901, #4986.

**Comment by vidartf** [comment]
TBH I don't know if this is the same issue as that about build hanging with node 10, but I couldn't find a better issue. If somebody else has a better overview, feel free to correct me!

**Comment by vidartf** [comment]
Xref #4877.

**Comment by jasongrout** [comment]
For those reading this: #4804 gives the rationale for staying with yarn 1.6.0 until a [bug](https://github.com/yarnpkg/yarn/issues/5935) is fixed in yarn, allowing us to upgrade to a yarn that supports node 10.

**Comment by bollwyvl** [comment]
Hey, folks! Looks like `yarn@1.9.4` (and `.3`, but whatever) has solved the BIG BAD PATH SMASH under most circumstances.

However, I also see that @jasongrout is keeping the dream alive of solving it Once And For All on https://github.com/yarnpkg/yarn/pull/6213 . :tophat: :ok_hand: keep up the good work. Bummer about that `yarn.lock` issue... i have scars from `--pure-lockfile`, but one can see why it is good, especially if you want to offline mirror.

Eagerly awaiting a stable, predictable release which we can accept forever into the repo (buh, sorry about that) and get on with having an [LTS good for another couple years](https://github.com/nodejs/Release#release-schedule).

**Comment by jasongrout** [comment]
Good catch!

Yes, I think the PR that was merged only partially handles the problem (though I think it probably handles the most egregious part of it). If we set `scriptsPrependNodePath` to false, we avoid the most of the remaining problems. 

If my PR is merged, then we'd need to stop setting `scriptsPrependNodePath` to false.

**Comment by jasongrout** [comment]
In short: I think we can update to 1.9.4 and set `scriptsPrependNodePath` to false. However, if it's not too much pain, I'd like to see if yarnpkg/yarn#6213 can be merged to give us a better fix, and we only update once.

**Comment by bollwyvl** [comment]
Yeah, lets let it ride over the weekend perhaps? Do we have a minimal case demonstrating the problem and/or need to add one?

**Comment by jasongrout** [comment]
if I could get it to build, I could illustrate the case more clearly. Basically, it's prepending the path in *two* places. I elaborate more in my original issue.

**Comment by jasongrout** [comment]
(i.e., in the original issue I filed, I give steps 1(a), 1(b), and 2 needed to really solve this issue. The merged PR essentially does roughly 1(a)...)

**Comment by blink1073** [comment]
We're coming up on a release, okay to switch to 1.9.4?

**Comment by blink1073** [comment]
We can also reinstate `--ignore-optional`: https://github.com/yarnpkg/yarn/pull/5059

**Comment by blink1073** [comment]
(Which would get rid of the nasty looking `canvas` build errors that are really warnings)

**Comment by bollwyvl** [comment]
Well, 1.9.4 has held for a week without a patch release, so is likely
suitable for use. We've had no complaints on the conda-forge side.
Unfortunately don't have bandwidth to open the PR myself today...

I'd say it's worth it for node 10, and the optional flag would be great for
reducing build noise and duration. Best of all in that regard would be
getting back to keeping the yarn.lock around between builds.... But I
haven't tested to find out if that would fix the duplicate entries we were
seeing.

**Comment by blink1073** [comment]
Agreed on all counts, I'll make a PR for 1.9.4 and we can try and pick up Jason's change and look into keeping yarn.lock for 0.35.
