### ISSUE TITLE
OutputAreaWidget has unused method

### ISSUE THREAD

**Issue by sccolbert** [jupyterlab/jupyterlab#459]
This method appears to do nothing, and is never called. Can it be removed?

https://github.com/jupyter/jupyterlab/blob/master/src/notebook/output-area/widget.ts#L348

cc @danielballan @blink1073

**Comment by danielballan** [comment]
I was patterning after this line: https://github.com/jupyter/jupyterlab/blob/master/src/notebook/output-area/widget.ts#L314

Would you like me to remove both?

**Comment by sccolbert** [comment]
The difference is that the protected `onModelChanged` is being invoked here:
https://github.com/jupyter/jupyterlab/blob/master/src/notebook/output-area/widget.ts#L190

I think `onModelDisposed` can be removed, because if the subclass cares about it, they can connect to the signal themselves.

**Comment by sccolbert** [comment]
cc @jasongrout about the need for the protected `onModelChanged`. He'd no more about the reason for that.

**Comment by blink1073** [comment]
We've been using that pattern in general, where if we connect to a signal internally, we call a private method, then a protected method, and then possibly emit a signal.

**Comment by blink1073** [comment]
But we could rely on the fact that signal connections are handled in order and get rid of the protected step.

**Comment by sccolbert** [comment]
or just make the private signal handler protected.

**Comment by blink1073** [comment]
This was fixed in https://github.com/jupyterlab/jupyterlab/pull/1709 (the model is given in the constructor now and is not modifiable.
