### ISSUE TITLE
Default Notebook and Keyboard Shortcut settings contain invalid json

### ISSUE THREAD

**Issue by goerz** [jupyterlab/jupyterlab#4591]
This was already mentioned in #3643, but that issue was closed without resolving the problem.

In the "Advanced Settings Editor", "Notebook", if I copy the content of "System Defaults" and paste it into "User Overrides", I get a syntax error. The reason is that the commas between the different configuration blocks are missing.

The same thing happens for "Keyboard Shortcuts"

**Comment by ian-r-rose** [comment]
Thanks for the report!

**Comment by ian-r-rose** [comment]
It seems this is not just for the notebook, but all settings. The individual entries of the JSON-schema are not separated by a `","`, and as such the default schemas are invalid. cc @afshin
