### ISSUE TITLE
Markdown syntax coloring for block-quote inside a list

### ISSUE THREAD

**Issue by aquirdTurtle** [jupyterlab/jupyterlab#4597]
Hello, I think I found a (small, not very important) bug in the pre-rendered coloring of a markdown block-quote inside a list. It looks like after a block-quote everything changes to the block-quote until a paragraph spacing, which makes sense normally, but not inside a list. This occurs in both light and dark themes.

![image](https://user-images.githubusercontent.com/4393192/40194713-99291d14-59c8-11e8-8b1d-0a3a148bd978.png)

And rendered:
![image](https://user-images.githubusercontent.com/4393192/40194741-adfbaed2-59c8-11e8-9cd6-c1a58f6cf666.png)

**Comment by jtpio** [comment]
Hi @aquirdTurtle,

Running JupyterLab from master this is what I get:

![image](https://user-images.githubusercontent.com/591645/42777327-f77fec8a-8939-11e8-949c-55833f0e9192.png)

Similar output with `JupyterLab 0.33.0rc1`, so it might just have been fixed recently. 

Maybe you could try installing the `0.33.0rc1` pre-release (if possible), or wait for the `0.33` to see if the issue has been fixed.

### Plain text example for reference:

```
TODO:
- start stuff
    - start query
        - start nested
            > start quote
            - still part of the quote
        - end nested
    - end query
- end stuff
```

**Comment by jasongrout** [comment]
Thanks for following up on this, @jtpio.

**Comment by aquirdTurtle** [comment]
hi @jtpio, yes this looks fixed on my machine as well. Thanks.
