### ISSUE TITLE
JupyterLab doesn't work with new conda paradigm 

### ISSUE THREAD

**Issue by jmeppley** [jupyterlab/jupyterlab#4598]
The latest version of conda no longer uses a `conda` binary so the old way of installing conda where you put the install path in your PATH is dropped for sourcing a conda.sh script that defines a `conda` function instead. 

This lets you use `conda activate $ENV` instead of `source activate $ENV` which is a minor change, but makes a lot more sense to users who didn't come from virtualenv.

Unfortunately, this breaks the conda integration for jupyterlab:

```
(jupyter) [jmeppley@hostname ~]$ jupyter lab
[E 23:38:24.242 LabApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda'
[I 23:38:24.243 LabApp] [nb_conda_kernels] enabled, 0 kernels found
```
This has been [addressed before](https://github.com/Anaconda-Platform/nb_conda_kernels/issues/60), but the answer is just a workaround:

If I add conda to my path, it works:
```
(jupyter) [jmeppley@hostname ~]$ export PATH=/opt/miniconda/bin:$PATH
(jupyter) [jmeppley@hostname ~]$ jupyter lab
[I 23:40:35.162 LabApp] [nb_conda_kernels] enabled, 5 kernels found
[I 23:40:35.406 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.0
```

The solution in #3951 does not work for me either.

I'm running jupyterlab 0.32.1:
```
(jupyter) [jmeppley@glutamate ~]$ conda list | grep jupy
# packages in environment at /opt/miniconda/envs/jupyter:
jupyter                   1.0.0                    py35_4  []
jupyter_client            5.2.3                    py35_0  []
jupyter_console           5.2.0            py35h4044a63_1  []
jupyter_contrib_core      0.3.3                    py35_1  []  conda-forge
jupyter_contrib_nbextensions 0.5.0                    py35_0  []  conda-forge
jupyter_core              4.4.0            py35ha89e94b_0  []
jupyter_highlight_selected_word 0.2.0                    py35_0  []  conda-forge
jupyter_latex_envs        1.4.4                    py35_0  []  conda-forge
jupyter_nbextensions_configurator 0.4.0                    py35_0  []  conda-forge
jupyterhub                0.8.1                    py35_0  []  conda-forge
jupyterlab                0.32.1                   py35_0  []  conda-forge
jupyterlab_launcher       0.10.5                   py35_0  []  conda-forge
```

Are there plans to fix this?

**Comment by jasongrout** [comment]
Thanks @benbovy. This issue is with the nb_conda_kernels package, not JupyterLab, so let's move the discussion to the issue that @benbovy pointed out: Anaconda-Platform/nb_conda_kernels#73.
