### ISSUE TITLE
Jupyter labextension doesn't use linked local package

### ISSUE THREAD

**Issue by yarden-livnat** [jupyterlab/jupyterlab#4599]
I have an extension (sqleditor-extension) that depends on a non-extension package (sqleditor)
Using `jupyter labextension link` and `jupyter lab --watch` during development works fine. When I make changes and run `tsc` jupyter reinstall the extension.

The same does not work for the non-extension package and jupyterlab extension builder seems to insist on taking the package from the public repository rather than my local one. I tried to locally bump the npm version of the non-extension package but then jupyterlab says it can't find the required version (0.4.1) even though it shows in `jupyter labextension list`.

```
(trails) view:~/software/projects/trails/packages/sqleditor-extension>jupyter labextension list
JupyterLab v0.32.1
No installed extensions

   linked packages:
        @vatrails/sqleditor: /Users/yarden/software/projects/trails/packages/sqleditor
(trails) view:~/software/projects/trails/packages/sqleditor-extension>jupyter labextension link
> /Users/yarden/miniconda3/envs/trails/bin/npm pack /Users/yarden/software/projects/trails/packages/sqleditor-extension
vatrails-sqleditor-extension-0.4.3.tgz
> /Users/yarden/miniconda3/envs/trails/bin/npm pack /Users/yarden/software/projects/trails/packages/sqleditor-extension
vatrails-sqleditor-extension-0.4.3.tgz
> /Users/yarden/miniconda3/envs/trails/bin/npm pack /Users/yarden/software/projects/trails/packages/sqleditor-extension
vatrails-sqleditor-extension-0.4.3.tgz
> /Users/yarden/miniconda3/envs/trails/bin/npm pack /Users/yarden/software/projects/trails/packages/sqleditor
vatrails-sqleditor-0.4.1.tgz
> node /Users/yarden/miniconda3/envs/trails/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "@vatrails/sqleditor" that matches "^0.4.1"
? Please choose a version of "@vatrails/sqleditor" from this list: (Use arrow keys)
❯ 0.4.0 
  0.3.5 
  0.3.4 
  0.3.3 
  0.3.2 
  0.3.1 
  0.3.0 
```

What am I missing here?

**Comment by jasongrout** [comment]
When JupyterLab builds, it pulls packages from NPM except for extensions it is building locally. What you can do is in your extension, make it depend on the explicit absolute path to your non-extension, in the package.json:

```
dependencies: {
"@vatrails/sqleditor": "file:/Absolute/path/to/dev/version/of/package"
}
```
See https://docs.npmjs.com/files/package.json#local-paths

**Comment by jasongrout** [comment]
I'm excited to see a sql editor extension! Feel free to put the `jupyter-labextension` topic on your repo when you're ready so other people can find it easier.

**Comment by vidartf** [comment]
I think will be resolved by #4543?

**Comment by saulshanabrook** [comment]
@yarden-livnat Would it be possible for you to test this PR to see if it fixes your problem? https://github.com/jupyterlab/jupyterlab/pull/4543 or point me to your extension so I can test it myself?

**Comment by jasongrout** [comment]
Closing as resolved. Please comment below if there is still an issue.
