### ISSUE TITLE
Clicking and dragging a non-active cell only selects it, but does not allow the drag

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4603]
Notice that the first time I try to drag the non-active cell, it becomes active but doesn't drag. I have to try dragging it a second time (after it has become active) to have the drag recognized.

![debug](https://user-images.githubusercontent.com/192614/40219121-f7654d34-5a28-11e8-9909-5b80c35931c6.gif)

I think the proper behavior would allow dragging a non-active cell by simply dragging, without having to click to make it active first.

**Comment by siryog90** [comment]
I'd like to take this opportunity to get more familiar with the codebase if nobody is assigned to the issue yet.

**Comment by jasongrout** [comment]
Go for it!

**Comment by jasongrout** [comment]
The event and mouse handling for the notebook is here: https://github.com/jupyterlab/jupyterlab/blob/077a1df13a1d69da88380184e6e040140d34c7e9/packages/notebook/src/widget.ts#L1114

It's a bit tricky because of supporting drag and drop.

**Comment by MrQubo** [comment]
Seems like it's not possible to assign myself to the issue, so I just left a comment to note that I'm working on it right now.
