### ISSUE TITLE
Double-clicking filename in file browser enables renaming instead of opening

### ISSUE THREAD

**Issue by bstemper** [jupyterlab/jupyterlab#4605]
Having worked with Jupyterlab for a few days, I have to say I find it very counter-intuitive that double-clicking on a filename in the file browser does not open the file but instead selects the filename for easy renaming. To open the file, I have to double-click the tiny icon or right-click and then select open. 

From a UX POV, I think double-clicking should open the file as this is the more common action. Renaming occurs very rarely and should be available through the context menu.

**Comment by jasongrout** [comment]
Definitely +1. I thought we had an issue for this.

Also related: #3697

**Comment by jasongrout** [comment]
I just tried in master, and double-clicking on a file now *just* opens it (no renaming). However, clicking three or more times on a filename, then waiting for about a second, starts the renaming. I think we should take that behavior out too, and just have rename be a context menu action.

@bstemper - are you using 0.32.1?

**Comment by bstemper** [comment]
@jasongrout Yes, i am on 0.32.1. Thanks for checking it out.

**Comment by fonnesbeck** [comment]
I'm still getting double-click rename in 0.32.1

**Comment by Aylr** [comment]
+1 open should be the default behavior
