### ISSUE TITLE
Unable to disable jupyterlab extensions

### ISSUE THREAD

**Issue by llinfeng** [jupyterlab/jupyterlab#4611]
## Updated issues
`jupyter labextension disable <my-extension>` does not work.

## Original Post  (mostly solved)
I am using Windows 10 OS, with Anaconda.  What follows are my installation details (mostly forked from `conda-forge` or so).
```
$ conda list jup*
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
jupyter                   1.0.0                    py36_4
jupyter-contrib-core      0.3.3                     <pip>
jupyter-nbextensions-configurator 0.4.0                     <pip>
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.4.0            py36h56e9d50_0
jupyterlab                0.32.1                   py36_0    conda-forge
jupyterlab_launcher       0.10.5                   py36_0    conda-forge
```

So far, I can only save the notebook at most once, right after opening the notebook. Here goes the "error message" that I got when closing the browser. (Nothing shows up however hard I press on the Save button, before closing the browser)
![with_vim_no_saving_after_edit](https://user-images.githubusercontent.com/5890407/40315063-5b0858a6-5ce8-11e8-9a81-912a75f4ccc7.jpg)

As I was fumbling with the Jupyterlab-Vim extension, I tried to disable it, uninstall it, rebuild Jupyter Lab and even rebuild Jupyter + Jupyter Lab. Nothing helps. (A side note, `jupyter labextension disable jupyterlab-vim` does not help disable my local-built extension.)

Per the saving method, pressing `Ctrl + S` does not help. The once-only saving is done by either pressing the "save icon", or summoning the Save Notebook option from "Command Palette".

**Comment by llinfeng** [comment]
## Solved problems:
1. It turns out to be an awkward *hardware/operating-system issue*. Rebooting my laptop several times gets me to **save** the notebooks. The shortcut `Ctrl + S` also starts to work again.

2. Those `404 GET` errors are muted by including the following line into `~/.jupyter/jupyter_notebook_config.py`.

> ```
> c.NotebookApp.allow_origin = '*'
> ```
> 

#Remaining problem
1. `jupyter labextension disable <my-extension>` does not seem to work: it does take admin privilege to execute the command, but nothing changes. I have tried to disable the following:
* `jupyterlab-toc`, installed through `jupyter labextension install jupyterlab-toc`;
* `jupyterlab-vim`, locally built through:
    ```
    npm run build
    jupyter labextension link .
```

**Comment by jasongrout** [comment]
What happens when you do `jupyter labextension disable <my-extension>`? What is `jupyter labextension list` after it?

**Comment by saulshanabrook** [comment]
If you could make a Dockerfile that would reproduce the bug you are seeing, that would be helpful for debugging. Although if it's windows specific, than that won't help.

**Comment by jasongrout** [comment]
Closing as no response. Please comment below if you would like to continue the discussion.
