### ISSUE TITLE
<kbd> tag in markdown cells

### ISSUE THREAD

**Issue by sputnik62** [jupyterlab/jupyterlab#4612]
We (http://CognitiveClass.ai) use JupyterLab as a teaching tool. So writing good looking easy to follow instructions is very important and we find ourselves quite often in a situation where we need to use html markup like this `<kbd>Shift</kbd>+<kbd>Enter</kbd>` which JupyterLab does not seem to render very well.

Would it be possible to have this fixed?

**Comment by jasongrout** [comment]
Thanks. We're tracking this issue at #4374 - let's move the discussion there.
