### ISSUE TITLE
Regression in current folder behavior.

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#4620]
1. When the file browser's directory is changed, the "current folder" is **not** where newly created notebooks / text files are saved *if they are created from an already open launcher*. If the "+" button is clicked and a new launcher is opened, the behavior is correct. This is a big regression.
1. When the file browser's directory is changed, the launcher does not show the current directory. But if the page is refreshed, the launcher shows the directory:

![launcher bug](https://user-images.githubusercontent.com/159529/40419114-36f17fca-5e7c-11e8-9b61-3b9f17de805d.gif)

**Comment by gnestor** [comment]
I did some investigating and what I've found is:

* Although `Launcher` is a subclass of `VDomRenderer`, `Launcher.update` does not call [`VDomRenderer.onUpdateRequest`](https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/vdom.ts#L77).

https://github.com/jupyterlab/jupyterlab/blob/f8b8f0d67f4a7b1c86ab9e9c9fdf755bd03fffc3/packages/launcher/src/index.tsx#L241-L244

* When I set a breakpoint inside `set cwd`, it's not pausing when I change cwd although `launcher.cwd = model.path` is being called

https://github.com/jupyterlab/jupyterlab/blob/f8b8f0d67f4a7b1c86ab9e9c9fdf755bd03fffc3/packages/filebrowser-extension/src/index.ts#L520-L528
