### ISSUE TITLE
Revealing a large file takes a long time

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4621]
(I saw this while doing #4453, so the first thing is probably to test with master to make sure it's an issue there too).

I noticed that loading a file that was several megabytes into the editor (such as jlab's built main js file), switching to another tab which hides the big file, then double-clicking in the file browser to reveal the big file tab has a seconds-long delay before showing the file.

This might be because codemirror is refreshing, etc. I just wanted to note it as an issue. This may be the same issue with a long notebook taking a long time to reveal.

**Comment by vidartf** [comment]
Did you figure out what it was?
