### ISSUE TITLE
Use typescript helpers

### ISSUE THREAD

**Issue by domoritz** [jupyterlab/jupyterlab#4624]
https://github.com/Microsoft/tslib leads to smaller files and lower runtime overhead in large ptojects like JupyterLab. Are there any reasons against it?

**Comment by jasongrout** [comment]
I haven't heard of it before. I think it sounds good to use.

Jason

**Comment by domoritz** [comment]
The necessary change is to 

1. Add `tslib` as a dependency to the right `package.json`
2. Add `"compilerOptions": { "importHelpers": true }` to the right `tsconfig.json`. I'm not whether with the JupyterLab setup it is necessary to add this option to all Typescript config files. 

I don't feel that I understand the build system enough to decide where these go but for someone who does this should take only a few minutes.

**Comment by jasongrout** [comment]
Likely it will need to be added to all package.json files that import typescript, and all tsconfig files.

**Comment by domoritz** [comment]
The compiler option has to be added to all `tsconfig.json` files that get used by Typescript. However, the `tslib` dependency only needs to be added to the `package.json` that produce an actual bundle. As far as I see it, that means it doesn't need to be in all jupyterlab packages but only the metapackage.

**Comment by jasongrout** [comment]
I thought what was emitted required the tslib dependency. That would mean that anything emitted that imported that dependency needs that as a dependency (i.e., probably just about every package).

**Comment by jasongrout** [comment]
(each extension is a completely separate npm package that is published separately)

**Comment by domoritz** [comment]
Every extension would depend on the tslib package but (if I understand it correctly) would do so with `require('tslib')`. When the actual JupyterLab bundle (assuming there is one big one that will be loaded into the browser) is produced, the tslib dependency would be included once.

**Comment by jasongrout** [comment]
Every extension would need the tslib dependency in its package.json. When the big bundle is built for jupyterlab, these will be deduped, so only one copy will be included in the bundle.

**Comment by domoritz** [comment]
Oh, I see. Thanks for the clarification. Then yes, tslib needs to be added to all extensions. However, the benefit will be that all typescript helpers are only included once in the bundle, which will reduce the file size of the bundle.

**Comment by jasongrout** [comment]
Right. I am curious how much it will actually save.

**Comment by domoritz** [comment]
A quick scan through the JupyterLab bundle shows these code duplications:

81x
```
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
```

29x
```
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
```

**Comment by jasongrout** [comment]
So that's about `81*493+29*279 = 48k` in code. So nontrivial, but fairly small compared to the megabytes-big bundle. Still, I suppose it doesn't hurt, so I'm still +1 on the change.

**Comment by domoritz** [comment]
I tried it in #4629 but it doesn't really make a difference unless I look at the numbers the wrong way.
