### ISSUE TITLE
buttons to move cells up and down

### ISSUE THREAD

**Issue by daviddoji** [jupyterlab/jupyterlab#4643]
First of all, I would like to thank you but the great job you're doing in the Jupyter project.

Would it be possible to add a couple of buttons (like in Jupyter-notebook) to move cells up and down?
There are some of them in Jupyterlab but those two are missing.

Best,
David

**Comment by leogout** [comment]
There is actually something similar in jupyterlab: you can drag and drop your cells from the left side. Is that what you mean ? Or do you specifically want buttons to perform this action ?

**Comment by daviddoji** [comment]
Thanks for your fast reply!
I was not aware of this feature. That works for me :)
