### ISSUE TITLE
Jupyter Lab Window Not Showing Properly

### ISSUE THREAD

**Issue by eljirg** [jupyterlab/jupyterlab#4649]
I just installed Jupyter Lab and tried it, however it doesn't showup properly. I tried reinstalling and installing but it show the same bug.

I am using dell xps 13, I tried installing it using:

'pip install jupyterlab', and
'conda install -c conda-forge jupyterlab'
Both gave same error. Is there a solution to this? The Jupyter Notebook is working just fine.

<img width="960" alt="jupyter lab" src="https://user-images.githubusercontent.com/29477795/40596877-bdbe551e-6278-11e8-9989-96cf94a52ebb.PNG">

**Comment by blink1073** [comment]
Hi @eljirg, there could have been a problem with that particular release.  Do you still seeing this with JupyterLab 0.34?

**Comment by jasongrout** [comment]
Closing since the author did not follow up.
