### ISSUE TITLE
[Question] How can we share code between extensions?

### ISSUE THREAD

**Issue by Madhu94** [jupyterlab/jupyterlab#4650]
Let's say I have a mimerender extension and a widget extension that share a library, and I'd like them to use the same version of the library. 

At the moment though, I get 2 copies of the shared libraries in the lab's main bundle. One solution I could think of, is to make the shared libraries an extension themselves and then the widget and mimerenderer would depend on that extension. However, mimerenderers can't depend on other extensions (I think).

Is there any other way of doing this ?

Thanks.

**Comment by saulshanabrook** [comment]
Extensions are installed as NPM packages. So if you publish an NPM package with some shared code, you should be able to use that from both extensions. Does that make sense?

**Comment by jasongrout** [comment]
And to clarify, that npm package does not have to be an extension. Just a regular npm package imported by both extensions should be deduped to only be included in the bundle once.

**Comment by Madhu94** [comment]
>> extensions should be deduped to only be included in the bundle once.


Thanks, this isn't what's happening though. Likely something wrong on my
end, let me check again.


Thanks !!
Hide quoted text

**Comment by saulshanabrook** [comment]
Ah ok. The yarn package de-duplicating can be finicky in some cases. If you run `yarn why <package name>` in the `staging` jupyterlab global directory, you can see what versions yarn wants of the package and why.

**Comment by Madhu94** [comment]
@saulshanabrook Thanks for all your help, I tracked down my bug (a mistake in my webpack setup).

> Extensions are installed as NPM packages. So if you publish an NPM package with some shared code, you should be able to use that from both extensions. Does that make sense?  

This should work for anyone
