### ISSUE TITLE
Extend core extension

### ISSUE THREAD

**Issue by leogout** [jupyterlab/jupyterlab#4651]
Hi, I am currently working on a project to visualize jupyterLab apps without being able to edit them.

At first I tried out the [notebook example](https://github.com/jupyterlab/jupyterlab/tree/master/examples/notebook) which was promising. Sadly I wasn't able from there to load extensions like `@jupyterlab/mathjax2-extension` or `@jupyter-widgets/jupyterlab-manager`. It seemed simpler to me to load a full app and disable extensions one by one, and maybe create a custom notebook one.

I then took for starting point [this app](https://github.com/jupyterlab/jupyterlab/tree/master/examples/app) from the examples.
I've disabled all the non inter-dependant packages from the [index.js](https://github.com/jupyterlab/jupyterlab/blob/master/examples/app/index.js) and I am now trying figure out how to extend or overwrite the notebook-extension in order to provide a read-only experience to the user.

To do so, I tried to clone and edit the notebook-extension to then replace the original one with mine in the app's plugin modules. Unfortunately, the app behaves like it can't resolve my custom module's dependencies:
![image](https://user-images.githubusercontent.com/9843962/40609715-cd6cdf0c-626f-11e8-90c9-a9cf844770d6.png)
Do you have any ideas why it behaves like that ? Is there a simpler solution that I didn't saw ?
Sorry for the long post about a personnal problem more than a real issue with juputerLab. I would love to share the app I'm working on when it is working though.
Cheers !

**Comment by blink1073** [comment]
Hi @leogout, it sounds like you have two versions of `@jupyterlab/codeeditor` in your `node_modules`.  You can verify with `npm ls @jupyterlab/codeeditor`.

**Comment by leogout** [comment]
Closed this as I figured something out but I can't recall what... It's been too long, sorry.
