### ISSUE TITLE
Failed to display Jupyter Widget of type Map

### ISSUE THREAD

**Issue by eRajsh** [jupyterlab/jupyterlab#4654]
Recently installed Anaconda 3.5.1 on mac, and trying to write a simple map thingy in the notebook.
 
Ran the commands (pip install ipyleaflet) successfully
 
Extensions seem to be properly installed:
<img width="489" alt="screen shot 2018-05-29 at 9 39 23 am" src="https://user-images.githubusercontent.com/1895122/40637836-33059402-6325-11e8-9190-4a9c706a0c74.png">

 
Here is the code in the notebook:
***************************************
!jupyter nbextension enable --py widgetsnbextension --sys-prefix
!jupyter nbextension enable --py --sys-prefix ipyleaflet
 
import pandas as pd
from ipyleaflet import Map
 
Map(center=[ 37.7749, -112.4194], zoom = 10)
***************************************
 
 
When I run the notebook, I get the following issue:
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Enabling notebook extension jupyter-leaflet/extension...
      - Validating: OK
Failed to display Jupyter Widget of type Map.

**Comment by blink1073** [comment]
Hi @eRajsh, notebook extensions only work in the classic notebook front end.  To install leaflet for `jupyterlab` please follow the `jupyter labextension install` instructions [here](https://github.com/jupyter-widgets/ipyleaflet#installation)
