### ISSUE TITLE
Include diagram cell in notebook

### ISSUE THREAD

**Issue by mocquin** [jupyterlab/jupyterlab#4656]
Hi,

I've been testing the [Draw.io](https://github.com/QuantStack/jupyterlab-drawio) extension lately and I think it is really cool. It is easy to use to create a diagram, export it into a .png for example, that can latter be included in a markdown cell in a notebook.

In order to shorten this workflow, would it be possible to add a new type of cell in a notebook, lets call it a "diagram" type of cell ? 
When active, it would allow you to create, move and play around with your diagram as you would in the draw.io extension, but when the cell is computed, it would render the diagram (the same way it would render into a png when exporting from the extension).

This way you wouldn't have to have 2 tabs open, one notebook with the code, text, and equations, and one with the diagram that is being edited. It would all be done in the same tab (making it a lot easier to have a coherent content between the text and the diagram).

You could see a "diagram" cell kind like a mathjax-latex object, that you can edit when in Edit mode, and that is pretty-displayed when the cell is rendered.

I don't if that is doable, but I think it would be awesome !

Hope that's clear !

**Comment by arinbasu** [comment]
Hi Mocquin/Gurus of Jupyter, 

I can create diagrams in draw.io but cannot export it to PNG. As a result, I  use graphviz, save it as .gv and use dot -Tpng command to save it to PNG. This is still too many steps but I second the idea of a diagram cell, will keep things tidy.   

Best, 
Arin

⁣Sent from BlueMail ​

**Comment by Freddibiri** [comment]
i want this

**Comment by krassowski** [comment]
With JupyterLab 4.1 (currently in alpha) mermaidjs diagrams are now supported in Markdown cells, please see: https://github.com/jupyterlab/jupyterlab/pull/14102 for details. You can install the pre-release with `pip install --pre jupyterlab` to help testing this out.

**Comment by arazdow** [comment]
Thanks, I can’t use alphas for this project.  Looking forward to general release.
