### ISSUE TITLE
Completion vs indentation when cursor is before any non-whitespace character on a line

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#466]
The interaction between when a line indents and when the tab completer pops up is getting better, but is still confusing. For example, when I'm trying to indent a line, so my cursor is before any non-whitespace character on the line, often the tab completer pops up instead. Can we make it so that in this case, we get indent/dedent by tab/shift-tab?

CC @afshin

**Comment by blink1073** [comment]
Fixed by #476.
