### ISSUE TITLE
Right clicking URL in notebook should give option to copy to clipboard

### ISSUE THREAD

**Issue by stefanv** [jupyterlab/jupyterlab#4660]
In most browsers, right-clicking on a URL gives you the option to copy that URL to the clipboard.  Jupyter grabs that interaction, but only has cell-level interactions listed.  I imagine URL copying is a fairly common usage pattern that may be worth retaining.

**Comment by jasongrout** [comment]
FYI, shift-right click pulls up the browser context menu.

**Comment by stefanv** [comment]
Aha!  Somewhat unexpected, but that will do as a workaround.  Thanks, @jasongrout.

**Comment by stefanv** [comment]
Was there ever a decision made on this?  I don't think the workaround is discoverable by most users, since Ctrl-click isn't typically done on, e.g., Linux.

**Comment by jzf2101** [comment]
We can document that?

**Comment by jasongrout** [comment]
We're tracking the issue of making it more discoverable at #4023

**Comment by stefanv** [comment]
Thanks!
