### ISSUE TITLE
Autoclose parantheses

### ISSUE THREAD

**Issue by psinger** [jupyterlab/jupyterlab#4663]
I am trying to disable autoclosing of parantheses and brackets etc.

In default jupyter notebook this works fine with:

```
from notebook.services.config import ConfigManager
c = ConfigManager()
c.update('notebook', {"CodeCell": {"cm_config": {"autoCloseBrackets": False}}})
```

However, it does not work in jupyterlab, any ideas?

**Comment by joelostblom** [comment]
@psinger You can turn this off in the settings menu. Go to `Settings --> Advanced Settings Editor` and add the following in the `User Overrides` section:

```json
{
  "codeCellConfig": {
    "autoClosingBrackets": false}
}
```
Screenshot
![image](https://user-images.githubusercontent.com/4560057/41356471-f877e6ae-6ef1-11e8-8f6e-d8e72926b1b0.png)

**Comment by joelostblom** [comment]
I think this issue can be closed.

**Comment by ian-r-rose** [comment]
Thanks @joelostblom
