### ISSUE TITLE
Is it possible to disable token / password auth?

### ISSUE THREAD

**Issue by iwinux** [jupyterlab/jupyterlab#4667]
Problem: I've already set up client certificate auth at the frontend Nginx server, so there's no need to add another auth step.

What I've tried: setting `c.NotebookApp.token = None` results in `jupyter lab` crashing at startup....

Expect: Be able to disable token / password auth entirely.

Package Versions:

* jupyter-client: 5.2.3
* jupyter-core: 4.4.0
* jupyterlab: 0.32.1
* jupyterlab-launcher: 0.10.5

**Comment by timkpaine** [comment]
@iwinux did you try setting it to empty string?

**Comment by iwinux** [comment]
How come I didn't try that 😅 `c.NotebookApp.token = ''` works!

**Comment by metal3d** [comment]
Just one note, you can launch jupyter with `--LabApp.token=''` also
