### ISSUE TITLE
PYTHONPATH not honoured when JupyterLab executed through Anaconda Launcher

### ISSUE THREAD

**Issue by paddyh087** [jupyterlab/jupyterlab#4672]
PYTHONPATH variables set in .bash_profile are not loaded to the kernel when lab is executed from Anaconda Navigator (1.8.7). 

However, the PYTHONPATH variables are set when jupyter lab is executed through the terminal.

This problem is also described [here.](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jupyter/wFo4Aw77Omk/BS8A3q84AAAJ)

**Comment by blink1073** [comment]
Hi @paddyh087, we're tracking this in #3094.
