### ISSUE TITLE
user pod not releasing PVC after termination

### ISSUE THREAD

**Issue by miramar-labs** [jupyterlab/jupyterlab#4678]
I'm using the profile selection mechanism to allow me to select instances of the singleuser pod with various sizes of storage: 
`hub:
  extraEnv:
    JUPYTER_ENABLE_LAB: 1
  extraConfig:
    00-jlab: |
        c.KubeSpawner.cmd = ['jupyter-labhub']
    02-profiles: |
        c.KubeSpawner.profile_list = [
            {
                'display_name': 'DataScience - CPU Only (small instance)',
                'kubespawner_override': {
                    'singleuser_image_spec': 'registry.lan.aaroncody.com:5000/jupyter/jlab-user-all:12518b8b1039eb29',
                    'cpu_limit': 2,
                    'mem_limit': '4G',
                    'user_storage_capacity': '2Gi'
                }
            },
            {
                'display_name': 'DataScience - CPU Only (medium instance)',
                'kubespawner_override': {
                    'singleuser_image_spec': 'registry.lan.aaroncody.com:5000/jupyter/jlab-user-all:12518b8b1039eb29',
                    'cpu_limit': 4,
                    'mem_limit': '8G',
                    'user_storage_capacity': '4Gi'
                }
            },
            {
                'display_name': 'DataScience - CPU Only (large instance)',
                'kubespawner_override': {
                    'singleuser_image_spec': 'registry.lan.aaroncody.com:5000/jupyter/jlab-user-all:12518b8b1039eb29',
                    'cpu_limit': 6,
                    'mem_limit': '16G',
                    'user_storage_capacity': '8Gi'
                }
            },
            {
                'display_name': 'DataScience - CPU + GPU (NVIDIA TitanX PASCAL) (large instance)',
                'kubespawner_override': {
                    'singleuser_image_spec': 'registry.lan.aaroncody.com:5000/jupyter-nvidia/jlab-user-all:12518b8b1039eb29',
                    'cpu_limit': 6,
                    'mem_limit': '16G',
                    'extra_resource_guarantees': {"nvidia.com/gpu": "1"},
                    'user_storage_capacity': '32Gi'
                }
            }
        ]`

i'm noticing that if I select an 8Gi option for example, a PV/PVC claim is created for my pod as expected. Then when I go to Control Panel and kill server, to terminate the user pod, the PV/PVC hangs around (probably by design I know) ... but then when I go back in and select the 32Gi option, it reuses the existing PVC for my user pod (8Gi) ... whereas I would expect it to see that a new PVC is needed.... 

is this a bug?

**Comment by jasongrout** [comment]
Did you mean to post this to one of the JupyterHub repos? This is the JupyterLab repo.

**Comment by miramar-labs** [comment]
ugh .. yes i guess so ....
