### ISSUE TITLE
Deleting Cells - Defaults to first cell

### ISSUE THREAD

**Issue by jzf2101** [jupyterlab/jupyterlab#4688]
If I try to delete a cell from the menu I have to be super careful that the cell stays selected lest it defaults to the first cell. I've had to rewrite my import statements like 5x for a notebook.  Other maintainers haven't seen this issue but I'd like to see if there's a way we can confirm that a cell stays selected when using delete from the menu bar. @tgeorgeux

**Comment by ian-r-rose** [comment]
@jzf2101 I'm not sure how to reproduce this behavior, can you add a gif to illustrate it?

**Comment by jasongrout** [comment]
I can confirm that for me, with jlab 0.34, deleting a cell from the menu deletes the selected cell, not always the first cell. Closing as no response. Please comment below if you'd like to continue the discussion. Thanks!
