### ISSUE TITLE
RAM memory

### ISSUE THREAD

**Issue by mriosopi** [jupyterlab/jupyterlab#4693]
Does any one have problems with their RAM when JL its open? 

I have started to notice that Jupter Lab consume a lot of my memory...

**Comment by blink1073** [comment]
Hi @mriosopi, can you describe what you are doing when you see the memory spike?  See also https://github.com/jupyterlab/jupyterlab/issues/5171.

**Comment by jasongrout** [comment]
Closing since the author did not follow up.
