### ISSUE TITLE
Be on the lookout for yarn 2.0...

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab#4705]
https://github.com/yarnpkg/yarn/issues/5773

Key among the proposed vectors:
> - Change the lockfile syntax to a YAML-like file format (YAML-like because we would just slightly tweak our parser to emit something YAML-compatible, but we wouldn't support any advanced YAML feature)

I for one would welcome this as it might make the logistics around #2065 more tractable...

**Comment by bollwyvl** [comment]
Note that they're down to 8 issues:

https://github.com/yarnpkg/yarn/milestone/4

If the timing works out for `1.0.0`, it would be fantastic to get on this bus: the yaml subset lockfile would be enough for me.

**Comment by vidartf** [comment]
How about for 4.0? https://yarnpkg.com/getting-started/migration

**Comment by krassowski** [comment]
Closing as we are using yarn 3 alerady as of JupyterLab 4.0.
