### ISSUE TITLE
Investigate turning on caching for the minify step in the production webpack build

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4716]
See https://github.com/jupyterlab/jupyterlab/pull/4702/commits/0a136fe7b614223fc3c04f256711619f98f1fbf8 and https://github.com/jupyterlab/jupyterlab/pull/4702#issuecomment-396628474.

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/5099.
