### ISSUE TITLE
cannot paste a code in the cell??

### ISSUE THREAD

**Issue by isalirezag** [jupyterlab/jupyterlab#4718]
So lets say i wanna copy and paste some lines of code to a cell?
I can use ctr+c and ctr+v, but I cannot right click and do this stuff. in other words, we dont have copy and paste option?
I just copy a line of code from somewhere and I need to do ctr+v to paste in inside jupyterlab's cell.
is it a bug or there is some reasons behind it....

**Comment by ian-r-rose** [comment]
Do `Ctrl-C` and `Ctrl-V` not work? If you want the browser-native right-click menu you can use `Shift`-right-click to bring it up.

**Comment by isalirezag** [comment]
Ctrl-C and Ctrl-V works!
I just used to mouse right click more i guess.
if i use `shift-` right click inside the cell it does not work

**Comment by ian-r-rose** [comment]
Hm, I can't reproduce this problem: Shift+Right-Click brings up the normal context menu for me. What browser/OS are you using?

**Comment by isalirezag** [comment]
you are doing that in jupterlab cell and it works?
im using ubuntu 16.04 and chromium

**Comment by ian-r-rose** [comment]
Interesting. This does not happen in Firefox, but I can reproduce this in Chrome/Chromium (also with Ubuntu).

**Comment by ian-r-rose** [comment]
Thanks for the report @isalirezag. I have opened #4720 in an effort to fix this. Can you check whether you see the same issue in Firefox?
