### ISSUE TITLE
Update testing infrastructure

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4727]
- [x] Update karma and related packages
- [x] Try using headless browsers
- [ ] Add chai and start using it, instead of plain expect.js?

We may bump this to after beta 3 if it is taking too long.

CC @saulshanabrook who has been experimenting with other testing frameworks. Note that this PR is about more of an incremental (i.e., hopefully easier) change than completely changing our entire test suite.

**Comment by saulshanabrook** [comment]
Does anyone know why the `services` package it's tests defined in `./packages/services/test` whereas the rest of the packages have their tests defined in `./tests/...`? It would be nice to make these the same style so it's easier to comprehend and change the testing flow.

**Comment by blink1073** [comment]
The original reason is that the services tests don't require a browser, but no reason they can't be combined.

**Comment by saulshanabrook** [comment]
Ah that makes sense. Thanks @blink1073.

I have https://github.com/jupyterlab/jupyterlab/pull/4735 in an OK state (as long as tests pass), which addresses switching to headless chrome and updating karma.

**Comment by blink1073** [comment]
We are using `chai` for some tests; I don't think it is worth it to convert them all to `chai` as a short term goal.

**Comment by blink1073** [comment]
Test Update Checklist:

- [ ] `import expect = require('expect.js');` -> `import { expect } from 'chai';`
- [ ] `to.be()` -> `to.equal()`
- [ ] `to.eql()` -> `to.deep.equal()`
- [ ] `to.be.ok()` -> `to.be.ok`
- [ ] `to.be.a()` -> `to.be.an.instanceof()`
- [ ] Instead of returning promises, use `it('should ...', async () =>`
- [ ] Convert `let` -> `const` where possible

**Comment by blink1073** [comment]
I'm going to write a script that automates most of the above, leaving us to concentrate on `async` and `const`.

**Comment by saulshanabrook** [comment]
Nice, that'll be great!

**Comment by blink1073** [comment]
We have to manually change [ok](http://www.chaijs.com/api/bdd/#method_ok), since it causes a `tslint` error without `()` and it isn't recommend.

**Comment by blink1073** [comment]
I changed the `tslint` error instead, since we use [noUnusedLocals](https://github.com/jupyterlab/jupyterlab/blob/c5de61d7d4a0eeeedfbea809de6146a07e36d258/tsconfigbase.json#L6).

**Comment by blink1073** [comment]
The only times we can't use `async` are if there is a `Signal` or if one promise needs to be resolved in the middle of another promise chain.

**Comment by jasongrout** [comment]
> The only times we can't use async are if there is a Signal or if one promise needs to be resolved in the middle of another promise chain.

Can you give examples of both of these situations?

**Comment by blink1073** [comment]
Use of `signal.connect()`: https://github.com/jupyterlab/jupyterlab/blob/f6c8e8c56625ac2c4272e2c3e1b7b2985358845c/tests/test-apputils/src/instancetracker.spec.ts#L64

Use of a promise within a chain:
https://github.com/jupyterlab/jupyterlab/blob/f6c8e8c56625ac2c4272e2c3e1b7b2985358845c/tests/test-coreutils/src/statedb.spec.ts#L67

**Comment by jasongrout** [comment]
if the signal is triggered synchronously, we've had the slot set a variable value. Then we do the thing triggering the signal, then check the value. That makes sure that the signal was emitted synchronously. An example: https://github.com/jupyterlab/jupyterlab/blob/ab95c4ef041234b61729ee2f4b20a896bae5d2cf/packages/services/test/src/kernel/ikernel.spec.ts#L62

**Comment by blink1073** [comment]
Thanks for the pointers, I'll try and update those two tests in the next PR.

**Comment by jasongrout** [comment]
Bumping to 0.33.x since @blink1073 seems to be on a roll doing the last remaining item.
