### ISSUE TITLE
Indicator for read-only files, improved save experience

### ISSUE THREAD

**Issue by martindurant** [jupyterlab/jupyterlab#4729]
When opening a read-only notebook, things load and run without problem. Unlike the classic notebook, there is no indication that the notebook is read-only - request some icon or perhaps `(read-only)` text in the tab title or elsewhere. 

When trying to save, you get `File Save Error for <file>.ipynb` - suggest improving this message to say that the user should Save Notebook As...

xref: https://github.com/pangeo-data/pangeo/issues/242

**Comment by krassowski** [comment]
Thank you for opening this one a while back. The read-only indicator feature is now tracked in #7980 and there is a draft PR implementing it (#12826). I will close this one in favour of #7980 which received more discussion.
