### ISSUE TITLE
Display error message when opening terminal on Windows

### ISSUE THREAD

**Issue by fran6w** [jupyterlab/jupyterlab#473]
Launching "terminal" opens a new tab which is not working. The console shows a 404 message: [W 09:05:50.853 LabApp] 404 POST /api/terminals?1468998350820 (::1) 2.00ms referer=http://localhost:8888/lab

**Comment by blink1073** [comment]
Hi @fran6w, unfortunately, the terminal emulator we are using on the server side relies on a pseudo-terminal (pty), which is not available on Windows.  We can certainly give a better error message than just showing something in the terminal though ;).

**Comment by jasongrout** [comment]
Fortunately, it appears that the upcoming Windows 10 linux support may include support for tty (see, for example, this news item: http://mspoweruser.com/windows-10-build-14361-includes-huge-improvements-bash-ubuntu-windows/)

**Comment by jmssmth** [comment]
Though I'm on Windows (8.1) I'm seeing nothing in the terminal windows at all. Just a blinking cursor -- nothing happens in it at all. An error/information dialogue would be helpful.

**Comment by jasongrout** [comment]
+1 to an error message. That sounds like a great actionable item for this issue.

**Comment by blink1073** [comment]
Follow-up: Windows Subsystem for Linux now includes a pty: https://blogs.msdn.microsoft.com/commandline/2016/06/08/tmux-support-arrives-for-bash-on-ubuntu-on-windows/

**Comment by dhirschfeld** [comment]
Is jupyterlab using terminado? I was able to get that up and running on WSL - takluyver/terminado#32

**Comment by blink1073** [comment]
Awesome!  Yes, it does.

**Comment by jasongrout** [comment]
As pointed out on the [mailing list](https://groups.google.com/d/msg/jupyter/d8CuOqbkI4A/ukzWANqwBgAJ), we should disable the terminal plugin if the server doesn't support it.

**Comment by blink1073** [comment]
The current behavior on master is to respect the `supports_terminals` data from the server and not add anything relating to terminals to the page.

**Comment by Carreau** [comment]
> As pointed out on the mailing list, we should disable the terminal plugin if the server doesn't support it.

More precisely I think the request was to hide any terminal related element if they are not available to not  have people try to use (or remind people they can't use) a specific feature. 

It's a double edge sword, as not showing any UI might be extremely confusing to users, that can wonder "I'm sure I've seen a terminal somewhere where is this button already", while a greyed-out UI can convey in a better way that something is available under certain conditions.

**Comment by blink1073** [comment]
The classic notebook manifests as follows:

![image](https://cloud.githubusercontent.com/assets/2096628/20756333/ef4385e4-b6d7-11e6-89b8-2fbdf27bd670.png)


![image](https://cloud.githubusercontent.com/assets/2096628/20756352/ffb331ae-b6d7-11e6-80d3-94ef72367889.png)

I support keeping the "Running" behavior, but am not sure how else to manifest in JupyterLab.
We could add a top-level Terminal -> Terminals Unavailable menu, but that seems mean.
We could add it to launcher with grayed out text.

**Comment by ellisonbg** [comment]
The terminal now works on Windows, closing.
