### ISSUE TITLE
Can't disable built-in Find bar

### ISSUE THREAD

**Issue by basnijholt** [jupyterlab/jupyterlab#4730]
I would like to completely disable the search bar that shows up when pressing `Command + F`:

I mean this one:
![41129190-cbd83fa8-6a65-11e8-9872-9397d818f482](https://user-images.githubusercontent.com/6897215/41438524-5f7dd760-6fdc-11e8-9d5a-091358d80781.png)

However, this doesn't seem to be possible from the shortcuts menu.

Is there a way to do this?

There is this related issue https://github.com/jupyterlab/jupyterlab/issues/2637

**Comment by basnijholt** [comment]
I just learned that if you press ctrl-F twice, then it goes to the browser.

**Comment by jasongrout** [comment]
Cool, I didn't know that! Let's change this issue to documenting this.

**Comment by basnijholt** [comment]
I think that should be another issue. It should still be possible to disable/change this behavior.

**Comment by jasongrout** [comment]
Okay, switching the title back, then.

**Comment by jasongrout** [comment]
To disable this, I think we'd need to (a) figure out the way to disable the searching in CodeMirror and (b) expose an option to the user to turn off searching.

At the very least, I think we should document the ctrl F twice way of getting past the codemirror search.

**Comment by aschlaep** [comment]
@cquah has pointed out that this can probably be closed now that #5795 and subsequent ctrl+f PRs have merged!

**Comment by ian-r-rose** [comment]
Fixed by #5795 and friends. Thanks @aschlaep!
