### ISSUE TITLE
Scroll bar for code inside a cell

### ISSUE THREAD

**Issue by aditsanghvi94** [jupyterlab/jupyterlab#4745]
Large cells with / without output have a scroll bar INSIDE the cell, making it very difficult to code and scroll.
I have tried multiple browsers and still have the same problem.

![scroll_bar](https://user-images.githubusercontent.com/14086839/41557590-26a366de-730c-11e8-8722-630824e4d7a4.png)

How do I fix this? It's been happening recently, a week or so. 
I am using jupyterlab 0.32.

**Comment by aditsanghvi94** [comment]
Any update? :(

**Comment by ian-r-rose** [comment]
I tested a code cell with ~3K lines, and I cannot reproduce this in Firefox or Chrome.

**Comment by aditsanghvi94** [comment]
Did you try it in jupyterlab?
When i do jupyterlab -> launch classic notebook, the same code cell is fine if i use only the jupyter notebook. 
But if i view it in jupyter lab, the same code cell has these annoying scroll bars - it starts after my 50th line of code

**Comment by ian-r-rose** [comment]
Yes, I tried it in JupyterLab. What OS/browser have you tried?

**Comment by aditsanghvi94** [comment]
Both firefox and chrome, and os = ubuntu and OSX

**Comment by jasongrout** [comment]
Do you have any browser extensions loaded? Can you try in incognito/private mode (with no browser extensions loaded) to try to narrow this down?

**Comment by jasongrout** [comment]
I can't reproduce this either on current firefox in macOS with JupyterLab 0.32.1. Are you using 0.32.1?

**Comment by jasongrout** [comment]
Moving back to beta 4 while we try to reproduce this.

**Comment by aditsanghvi94** [comment]
Tried on chrome incognito and all extensions stopped, firefox and safari. Still having the same issues

Jupyter lab version 0.32.1.  
Also using jupyterhub, on version 0.8.1 if that helps?

**Comment by keithcallenberg** [comment]
After upgrading to Jupyterlab version 0.33.4 this is resolved. @aditsanghvi94 can you confirm?

**Comment by aditsanghvi94** [comment]
Resolved,thanks!

**Comment by abalter** [comment]
Are you currently supposed to be able to set jupyterlab cells to scroll output?
