### ISSUE TITLE
if kernel died because of memory, jupyter lab is stuck

### ISSUE THREAD

**Issue by lxkarthi** [jupyterlab/jupyterlab#4748]
### Problem:
If the kernel died in jupyter-lab, it does not show any warning or error. It is just stuck. 
But when I use jupyter notebook, I get the following error properly
```
Kernel Restarting
The kernel appears to have died. It will restart automatically.
```
Jupyter lab does not give any warning or message; the cell appears to be in running state. 
### Method to reproduce:
Allocate very large numpy array more than the memory of the machine.

**Comment by jasongrout** [comment]
We may need to bump this to Future to handle in the work in #4724.

**Comment by jasongrout** [comment]
Closing as a duplicate of #4273 - let's move the conversation over there.
