### ISSUE TITLE
Plot.ly configuration not passed to diagram output

### ISSUE THREAD

**Issue by rw72777** [jupyterlab/jupyterlab#4749]
It's possible to modify the plotly configuration based on https://plot.ly/python/configuration-options/. This will work for the classic notebook but unfortunately not for the lab. Please take a look at the attached screen shots, wher screen_01 shows the lab and screen_02 the classic notebook where the configured buttons are correctly removed ...

![screen_01](https://user-images.githubusercontent.com/18148054/41596460-ba8c48f2-73ca-11e8-857e-d738f9ac2429.png)
![screen_02](https://user-images.githubusercontent.com/18148054/41596464-bd603e94-73ca-11e8-880a-2e5a4af07836.png)

**Comment by timkpaine** [comment]
This seems like more of an issue on the jupyter renderers repo, as plotly is an extension

**Comment by rw72777** [comment]
Thanks for your reply. For easier reproducing, please open the attached notebook in jupyterlab and also via the classic mode ...

[plotly_sample.zip](https://github.com/jupyterlab/jupyterlab/files/2116099/plotly_sample.zip)

**Comment by timkpaine** [comment]
This is the wrong place for this issue. Please close and open a new one over [here](https://github.com/jupyterlab/jupyter-renderers)
