### ISSUE TITLE
[question] Can I run Jupiter without npm?

### ISSUE THREAD

**Issue by yurivict** [jupyterlab/jupyterlab#4753]
I would like to create FreeBSD ports for Jupiter, but the presence of node has always been a problem, because npm downloads unpredictable file set which can't be fingerprinted as required by the FreeBSD ports policy.

Perhaps the new version can be run without npm?

**Comment by jasongrout** [comment]
JupyterLab does not require npm to run. It only requires npm to install new extensions.

**Comment by jasongrout** [comment]
That means that the JupyterLab package does not depend on npm. You can install and run JupyterLab without having npm on your system. We pre-build the Javascript bundle in the package at packaging time, and ship that Javascript bundle in the pip package.

If you are trying to build JupyterLab from scratch, or if you want to install extensions, you will need npm to rebuild the Javascript.

**Comment by yurivict** [comment]
Thanks.
Can I build JupyterLab using the pre-downloaded Javascript bundle? (running npm during the port build would download files, which is a problem.) For example, I can download the pip package and take the Javascript bundle from it. Can this be done?

**Comment by jasongrout** [comment]
Could you just download the pip package and extract it and install those files (which includes the js bundle)? How are python packages usually installed in port packages?

**Comment by jasongrout** [comment]
Note that because we use a yarn.lock file, the npm packages downloaded to build the base distribution are verified to match a particular hash. See https://github.com/jupyterlab/jupyterlab/blob/master/yarn.lock

**Comment by yurivict** [comment]
> How are python packages usually installed in port packages?

Python packages are built from source. However, they can't be downloading anything else. They have to use the set of pre-downloaded files.

**Comment by jasongrout** [comment]
So two things you could do:

1. "cheat" by downloading the pip package and copying the prebuilt js and relevant files instead of building them
2. Generate the list of npm packge files to download from the yarn.lock file, which should be a comprehensive list of all npm packages needed. Install from these local files - that should not involve any external downloads.
