### ISSUE TITLE
Double-clicking the tabs should toggle fullscreen for the widget

### ISSUE THREAD

**Issue by TK-21st** [jupyterlab/jupyterlab#4756]
Came up with this while looking at this issue #4185 

> Double-clicking the dark-grey empty space next to tabs should create a Launch screen #4185

Would be useful if we have several widgets on the screen simultaneously and would like to zoom in to one temporarily (like double clicking on title of a iTerm2 pane)

**Comment by jasongrout** [comment]
You can use "Single Document Mode" in the View menu to do this, which is bound to Ctrl/Cmd Shift D.

Closing as resolved.

Feel free to comment below if you know about this, and are specifically proposing the double-click on tab behavior.
