### ISSUE TITLE
Hardcoding port in ws url

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4761]
In https://github.com/jupyterlab/jupyterlab/blob/4310ef3e2594fd451e50c921d50d346926dbb64b/packages/services/src/serverconnection.ts#L206-L220, we hardcode in a reference to port 8888. That doesn't seem good. Also, should we be checking that baseurl is an absolute url?

**Comment by vidartf** [comment]
When will `location === undefined`?

**Comment by blink1073** [comment]
The use of the fallback url is ported from the classic notebook code.

@vidartf, `location` is `undefined` when run from `node` (which this package supports).

**Comment by blink1073** [comment]
How about the following:

If `wsUrl` is not given `baseUrl` must start with `http` or `//`, otherwise throw.

- If `baseUrl` starts with `http`, replace that with `ws`
- If `baseurl` starts with `//`, use `location.origin` to get `http` vs `https`.  If `location.origin` is not given, throw.

**Comment by jasongrout** [comment]
> use location.origin

`location.protocol`?

**Comment by blink1073** [comment]
Ah, yep
