### ISSUE TITLE
Hotkey for running marked code in console 

### ISSUE THREAD

**Issue by YoavEtzioni** [jupyterlab/jupyterlab#4769]
Hi

Maybe what I am asking for already exit? I could not find it, so:

It would be very handy if one can run marked code using a hotkey in the console.

This would be similar to matlab's F9. The same is also possible in Pycharm by "Execute Selection in Consolue" . Where defining a hotkey for this is possible. 

Thanks

**Comment by saulshanabrook** [comment]
I think https://github.com/jupyterlab/jupyterlab/pull/4330 addresses this, which should be merged soon. It won't have a default keyboard shortcut, but you will be able to set one.

I am closing this now, since I think that PR covers it, but feel free to comment if you believe it doesn't.

**Comment by jasongrout** [comment]
This has also been possible from text files for a long time. What the new PR adds is a way to do it from the notebook.
