### ISSUE TITLE
Files pane to show directory of the currently activated file

### ISSUE THREAD

**Issue by joonro** [jupyterlab/jupyterlab#4771]
Hi,

I think it would be great if the files pane can dynamically update its path depending on the currently opened file's directory. 

I'm requesting this because I find myself frequently end up with multiple notebooks from different directories open in the lab. Sometimes I want to open another notebook which is in the same directory as the currently activated notebook or I want to glance other files in the directory, but because files pane is showing another directory, I have to switch the directory manually, which quickly becomes cumbersome. 

Thank you!

**Comment by ian-r-rose** [comment]
Hi @joonro, thanks for the feedback! I am not sure if we would want to make that behavior default: it seems to me like it might be kind of annoying if the directory were changing all the time, and might make it difficult to perform some copy/paste and move operations to/from different directories.

There is a command `Show in File Browser` to navigate to a file's directory. You can find that by right-clicking a file's tab.

**Comment by joonro** [comment]
Hi - thanks for the reply. I currently do not see `Show in File Browser` in the command list -- is it a new command implemented in a version that has not been released yet? (I'm using Version 0.32.1)

**Comment by ian-r-rose** [comment]
Ah, you are right, that is a new command. It should be in the next version we release (in a couple of days).

**Comment by mocquin** [comment]
See also #4258

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/4593.
