### ISSUE TITLE
Can a JupyterLab notebook programmatically halt itself?

### ISSUE THREAD

**Issue by zambon** [jupyterlab/jupyterlab#4775]
Is it possible to programmatically shutdown a kernel in JupyterLab?

I tried the solution proposed for Jupyter in [jupyter/notebook#1880](https://github.com/jupyter/notebook/issues/1880), but it doesn't work for JupyterLab, as it requires JavaScript.

![](https://i.imgur.com/Y3yRO9G.png)

**Comment by jasongrout** [comment]
How about just exiting from python (or whatever language kernel you have):
```python
exit()
```
or
```python
quit
```

**Comment by zambon** [comment]
Thanks for replying, @jasongrout!

I actually tried that! While both commands run successfully (i.e.: no errors are raised), the kernel session remains active.

**Comment by jasongrout** [comment]
Ah, it actually causes a restart (you can see that from the new execution numbers).

**Comment by smith558** [comment]
Is there any solution to this?

**Comment by davidbrochart** [comment]
This should do the trick, but it's Python-specific:
```py
import os
import signal
import threading
import time

def stop():
    time.sleep(5)
    os.kill(os.getpid(), signal.SIGINT)

t = threading.Thread(target=stop)
t.start()

# simulate long-running cell
time.sleep(1000)
```

**Comment by smith558** [comment]
I'm currently using this. Somewhat specific to the SLURM workload manager.

```python
from time import sleep
from ipylab import JupyterFrontEnd

# cleanly terminate the notebook session (terminates slurm job too)
def save_terminate():
    app = JupyterFrontEnd()
    app.commands.execute('docmanager:save')
    
    print("saved and will terminate Jupyter soon")

    sleep(5)

    exit()
    !scancel <SLURM_JOB_ID>
save_terminate()
```
