### ISSUE TITLE
SVG not rendering in Firefox

### ISSUE THREAD

**Issue by biermeester** [jupyterlab/jupyterlab#4779]
While playing around with Graphviz, I noticed that the SVG images it produced would render in Chrome, but not in Firefox. At first I thought it was an issue with the Graphviz Python wrapper, but it turned out that the images do render nicely in Jupyter  but _not_ in Jupyterlab.

The problem is that Jupyterlab embeds the `svg+xml` that Graphviz generates into the `src` attribute of an `img` tag, __without__ url-encoding the `#` characters it contains. (Where Jupyter just embeds the `<svg>` tag into the DOM).

**Comment by louisponet** [comment]
I noticed the same while trying to display plots using IJulia.

**Comment by biermeester** [comment]
I'll be happy to fix it, if someone can tell me the preferred fix: url-encode the `#` character or move from `<img>` to `<svg>`.

**Comment by louisponet** [comment]
I haven't tried the latter, the former worked perfectly in getting the image rendered.

**Comment by minexew** [comment]
A possible workaround is to replace 
```
display(IPython.display.SVG(fn))
```
with
```
display(IPython.display.Image(url=fn))
```
in your code

**Comment by jasongrout** [comment]
> I'll be happy to fix it, if someone can tell me the preferred fix: url-encode the # character or move from <img> to <svg>.

Move to img.

**Comment by jasongrout** [comment]
That wasn't very helpful. I think we should keep it an img tag, so encode the #.

**Comment by jasongrout** [comment]
@biermeester - are you planning on doing the encoding with `encodeURIComponent` used at https://github.com/jupyterlab/jupyterlab/blob/289fd7410f063c26962964ab138fd47c297ead1b/packages/rendermime/src/renderers.ts#L461 ?

**Comment by jasongrout** [comment]
Putting as 0.34 since we are releasing 0.33 right now, but I also think this should be backported to 0.33.x.

**Comment by biermeester** [comment]
I'm expecting to have pull request ready today.

**Comment by jasongrout** [comment]
Cool. We're planning to do a 0.33.1 release tomorrow to fix some bugs we're seeing, so we can include it there if we can review it by tomorrow.

**Comment by biermeester** [comment]
Aye!
