### ISSUE TITLE
ValueError: "@jupyterlab/completer" is not a valid extension: No 'jupyterlab' key

### ISSUE THREAD

**Issue by Skipper9000** [jupyterlab/jupyterlab#4784]
Hello, I really want check out the code completer functionality in JupyterLab. I'm moving from Jupyter Notebooks over to JupyterLab for this very reason. I'm using conda and have run the following successfully up to this point:

conda install -c conda-forge nodejs 
conda install -c conda-forge jupyterlab
npm i @jupyterlab/completer
jupyter labextension install @jupyterlab/completer

Can anyone steer me in the right direction please?

**Comment by afshin** [comment]
The code completer is one of the core extensions that ships with JupyterLab. You don't need to install it separately. Once you have JupyterLab, you can simply launch it (by running the command: `jupyter lab`) and open a new or existing notebook. It will have the completer built in, the same way that the classic notebook does.

**Comment by afshin** [comment]
(I'm closing the issue. If you still have questions, please feel free to re-open it.)

**Comment by Skipper9000** [comment]
Okay...? Is there something I have to do inside the JupyterLab application to enable it? I'm not seeing the advertised functionality...

![capture](https://user-images.githubusercontent.com/19862089/41925569-9238d09c-7932-11e8-9b25-af22a0952473.PNG)

**Comment by Skipper9000** [comment]
I would like to re-open this issue, but I cannot re-open my issue if a repo collaborator closed it. I have added another question/comment to the issue.

 

Thank you for you help,

Jacob

**Comment by afshin** [comment]
The completer is invoked by hitting the <tab> key. It should behave like this:
![completer](https://user-images.githubusercontent.com/159529/41926169-804b70b8-7966-11e8-8f7a-387989d987f4.gif)
Does it not work for you?

**Comment by Skipper9000** [comment]
That exactly what I'm trying to achieve. Thank you! What key are you pressing to invoke it?

**Comment by afshin** [comment]
Ha! I'm sorry. I actually *typed* `<tab>` but without the backticks and it didn't show up!

**Comment by Skipper9000** [comment]
YES!!! Thank you, thank you, thank you!

![capture](https://user-images.githubusercontent.com/19862089/41926659-979dd066-7935-11e8-96f4-c76c0f9234e2.PNG)

**Comment by preynoldssco** [comment]
This is a little off topic (and I'll open a new issue if it's not a simple answer) - but how do we turn on the colour coded completer? I get the same plain one as Skipper9000

**Comment by afshin** [comment]
@preynoldssco I don't remember which version of `ipykernel` started shipping the experimental completer metadata, but if you upgrade your installed `ipykernel` package to the latest, you should get the new completer. Keep in mind, this is just for the IPython kernel. Each individual kernel author will need to implement the experimental completer metadata for you to see it in JupyterLab.

**Comment by ian-r-rose** [comment]
You may also need to turn on `use_jedi` as described in the note [here](http://jupyterlab.readthedocs.io/en/latest/user/notebook.html).
