### ISSUE TITLE
Shareable link loads to whatever the most recent state of Jupyter Lab's window configuration was

### ISSUE THREAD

**Issue by jdavidheiser** [jupyterlab/jupyterlab#4786]
When right clicking and choosing "Copy Shareable Link" in the file explorer, it produces a link like:

`https://jupyter/user/lab/tree/file`

But navigating to this link just opens the Lab interface in whatever state it was in the last time the user was accessing Jupyterlab, without that file open unless it happened to be open last time.

jupyterlab.__version__ = '0.32.1'
jupyterhub.__version__ = '0.8.1'

**Comment by afshin** [comment]
The tree functionality has been refactored here: https://github.com/jupyterlab/jupyterlab/pull/4708 so it should work in the next release (we will be pre-releasing Beta 3 soon, and hopefully releasing it in the next week or two).

**Comment by saulshanabrook** [comment]
I tried this locally on the master branch and it seems to open the file when I go to the link, even if it wasn't open before.

**Comment by stephenpascoe** [comment]
The "Copy Sharable Link" menu copies a link of the form `https://notebooks/user/<username>/lab/tree/...` but In https://github.com/jupyterhub/jupyterhub/issues/2017 it's explained that it should be `https://notebooks/hub/user-redirect/...`.  Also `https://notebooks/user/...` seems to work.  Does #4708 fix this?

**Comment by afshin** [comment]
@stephenpascoe I think the comments in that thread are discussing links to classic notebook, not the lab URLs. The fix in #4708 should be compatible with the way JupyterHub builds URLs, but lab and classic have different URLs.
