### ISSUE TITLE
Plot Issue: Failed to display Jupyter Widget of type FigureCanvasNbAgg

### ISSUE THREAD

**Issue by rtadewald** [jupyterlab/jupyterlab#4787]
I'm trying to create interactive plots. My JupyterLab server is running in the cloud, in a Google Compute Engine Instance.

When I try to plot some data, i got this:
![1](https://user-images.githubusercontent.com/22618324/41950377-4788a594-799c-11e8-8c7b-8bcf455490f4.png)

**Comment by saulshanabrook** [comment]
I think this issue is more appropriate for https://github.com/jupyter-widgets/ipywidgets Maybe look through their documentation on installing the jupyterlab extension? https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension
