### ISSUE TITLE
Problems with installation (yarn.js)

### ISSUE THREAD

**Issue by marberi** [jupyterlab/jupyterlab#4791]
Trying to install JupyterLab on another machine, I got the error in the file
attached file:

[error_stdout.txt](https://github.com/jupyterlab/jupyterlab/files/2142785/error_stdout.txt)

The important errors appears to be:

    /tmp/pip-req-build-bvy2fiwy/jupyterlab/staging/yarn.js:137
    class MessageError extends Error {
    ^^^^^
    SyntaxError: Unexpected reserved word
        at Module._compile (module.js:437:25)
        at Object.Module._extensions..js (module.js:467:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.runMain (module.js:492:10)
        at process.startup.processNextTick.process._tickCallback (node.js:244:9)

when running "pip install ." Please let me know if more information is needed.

ps. I am actually using Jupyterlab, just returning here at times when getting
installation issues.

**Comment by jasongrout** [comment]
What version of JupyterLab, and what version of node? Are you trying to install from the repo? If so, what commit?

**Comment by marberi** [comment]
Just pulled and installed node with conda, so

commit 1e6551e716465d1b03533fefa71d27409b79603c

(pz3) [eriksen@data ~]$ node --version
v0.8.7

**Comment by bollwyvl** [comment]
That'll do it! I can't even find when the 0.8 line was sunsetted.

https://github.com/nodejs/Release/blob/master/schedule.json

You _might_ get by with nodejs 4 (no guarantees), but we're currently
targeting the current node LTS 8 (EOL 2019-12-31) and, as of jupyterlab
0.33, LTS 10 (EOL 2021-04-01)...

Sorry for the inconvenience!

**Comment by marberi** [comment]
thanks, that was the issue. I installed the package "node" from conda. 
Installing "nodejs" gave 
> (pz3) [eriksen@data ~]$ node --version
v9.11.1

which is kind of weird. It looks almost like the package changed name.

**Comment by jasongrout** [comment]
> as of jupyterlab 0.33, LTS 10 (EOL 2021-04-01)

FYI, we might roll that back to pre-10 (see #4793).

**Comment by bollwyvl** [comment]
Brutal!
