### ISSUE TITLE
Downgrade yarn to 1.6.0

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4793]
Yarn 1.7 (and yarn 1.8) gives us node 10 support, but unfortunately also has a serious bug: https://github.com/yarnpkg/yarn/issues/5935

We discussed this today, and decided to downgrade back to yarn 1.6 until the bug is fixed.

**Comment by gnestor** [comment]
What's the plan for supporting node 10? According to @tiagopereira at https://github.com/jupyterlab/jupyter-renderers/issues/132#issuecomment-406305839, conda is shipping node 10 now. If that's the case, supporting node 10 seems like a high priority.

**Comment by jasongrout** [comment]
We plan to support node 10 when yarn fixes their major bug, or we decide that the bug doesn't really affect us. See the yarn issue noted above: yarnpkg/yarn#5935

**Comment by jasongrout** [comment]
Or if we contribute the fix to yarn...
