### ISSUE TITLE
Table View renders CSV file incorrectly

### ISSUE THREAD

**Issue by groutr** [jupyterlab/jupyterlab#4795]
The table view in jupyterlab 0.32.1 seems to render the csv generated here incorrectly.
```python
import csv
with open('test.csv', 'w') as writefile:
    writer = csv.DictWriter(writefile, ['a', 'b', 'c'])
    writer.writeheader()
```
Opening test.csv in table view produces 
[![bad_csv.png](https://s22.postimg.cc/f3kc0atv5/bad_csv.png)](https://postimg.cc/image/nyl6atinh/)

**Comment by jasongrout** [comment]
What is the text that outputs?

**Comment by jasongrout** [comment]
I get an error

```
Python 3.6.3 | packaged by conda-forge | (default, Dec  9 2017, 16:20:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import csv
   ...: with open('test.csv', 'w') as writefile:
   ...:     writer = csv.DictWriter(writefile, ['a', 'b', 'c'])
   ...:     writer.write_header()
   ...:     
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-8b6b60f8a73a> in <module>()
      2 with open('test.csv', 'w') as writefile:
      3     writer = csv.DictWriter(writefile, ['a', 'b', 'c'])
----> 4     writer.write_header()
      5 

AttributeError: 'DictWriter' object has no attribute 'write_header'
```

**Comment by jasongrout** [comment]
Ah, it's `writeheader`, not `write_header`. Here is the contents of the file: `b'a,b,c\r\n'`. And yes, I see the same issue.

**Comment by groutr** [comment]
My bad, write_header() should be writeheader(). I was typing it from memory.  I fixed it above.

**Comment by groutr** [comment]
It doesn't like seem to like one line CSV files at all.
`b'a,b,c'`, `b'a,b,c\n'` give the same result.  Using a different delimiter (in this case `\t`) also yielded the same result

**Comment by jasongrout** [comment]
Thanks. I think that's hopefully enough to track down the issue (feel free to take a crack at it, the code is in https://github.com/jupyterlab/jupyterlab/tree/master/packages/csvviewer).

The model is constructed with basically default args: https://github.com/jupyterlab/jupyterlab/blob/2e10c6816d8bc5bc23afb3d5358d58400f0d4e21/packages/csvviewer/src/widget.ts#L138
That means that 'header' is true: https://github.com/jupyterlab/jupyterlab/blob/master/packages/csvviewer/src/model.ts#L62
That means we should be caching the header row: https://github.com/jupyterlab/jupyterlab/blob/master/packages/csvviewer/src/model.ts#L94-L100

So question 1: is that header it is computing correct? question 2: 

We should add a single-line csv as a test too: https://github.com/jupyterlab/jupyterlab/blob/master/tests/test-csvviewer/src/model.spec.ts (perhaps also in the parsing tests for both the no-quotes and quoted parser).

**Comment by jasongrout** [comment]
This issue should be self-contained enough to be an advanced good first issue.
