### ISSUE TITLE
Shift-click to extend text selection does not work in cell output area

### ISSUE THREAD

**Issue by jjpr-mit** [jupyterlab/jupyterlab#4800]
When I select some subset of the text in the output area of a cell, then move the mouse pointer to a spot inside the same output area but outside the already-selected text, hold the shift key, and click, I expect the highlighted area indicating selected text to expand to where the mouse pointer is.  Instead, nothing happens in response to the shift-click.  

Shift-click for selection expansion is a default behavior in Chrome (and works in the input area), so I assume Jupyter is intercepting or overriding that behavior inside the output area.  

This makes it unreasonably difficult to put large amounts of text from a cell's output area into the clipboard, since you can't start a selection, then use the scroll bar to traverse thousands of lines of text, then finish the selection with shift-click.  The only way to select large amounts of text is to click and drag off the edge of the window, and then wait while the browser scrolls.  

Is there a way to fix this?  

(Using Chrome 67, Jupyter Lab 0.32.0, macOS 10.13.5)

**Comment by jasongrout** [comment]
Thanks.

It looks like we are explicitly disabling that behavior in https://github.com/jupyterlab/jupyterlab/blob/ac745a39b071b800e46464013703d41e54f380c4/packages/notebook/src/widget.ts#L1488-L1489. I think the reasoning is that shift-click was supposed to be for selecting multiple cells. You have a very good point, though. I think the thing to do is to see if there is a happy medium between the shift-click-to-extend-cell-selection and the shift-click-to-extend-output-selection.

**Comment by tgeorgeux** [comment]
I think it makes sense to set it up that if you start with focus within the cell output, you can select more within that output using shift-click. In the case that your initial selection is a whole cell (input and output) the existing behavior continues.

@jasongrout Thoughts?

**Comment by jasongrout** [comment]
It looks like we can determine if text is selected using the selection api: https://developer.mozilla.org/en-US/docs/Web/API/Selection

**Comment by tgeorgeux** [comment]
I'd love to hear what come of this. It's a little outside my wheel-house. @jjpr-mit do you have any interest in taking a look at this? 😺

**Comment by tgeorgeux** [comment]
@jasongrout what if we just treated this behavior as command mode behavior vs edit mode behavior. I was doing some work on Command vs Edit mode today and it reminded me of the discussion here. Would it be difficult treat in cell shift-clicks during edit mode differently than command mode? That way you can start with a blinking cursor and select text as you please.
