### ISSUE TITLE
Shift-Tab  to unindent works differently than in the Jupyter Notebook

### ISSUE THREAD

**Issue by basnijholt** [jupyterlab/jupyterlab#4803]
In the classic Jupyter notebook when unindenting a line it was enough to have your text cursor somewhere in the empty space before the code.

So anywhere the arrows are
```
↓↓↓↓
    some_code
```

With Jupyterlab you need to select at least one charactar in that line when clicking Shift + Tab.

I wouldn't be surprised if there is another open issue about it, but I couldn't find one. This https://github.com/jupyterlab/jupyterlab/issues/3232 seems somehow related though.

I am using Jupyterlab 0.32.1.

**Comment by jtpio** [comment]
Looks like the keybindings for the `tooltip:launch-console` and `tooltip:launch-notebook` are taking precedence over the CodeMirror `indentLess` setting.

### shortcuts-extension

https://github.com/jupyterlab/jupyterlab/blob/1aff4190084fd5993d3f7e3ae10b467264df1cd0/packages/shortcuts-extension/schema/plugin.json#L690-L694

and

https://github.com/jupyterlab/jupyterlab/blob/1aff4190084fd5993d3f7e3ae10b467264df1cd0/packages/shortcuts-extension/schema/plugin.json#L702-L706

### codemirror

https://github.com/jupyterlab/jupyterlab/blob/1aff4190084fd5993d3f7e3ae10b467264df1cd0/packages/codemirror/src/factory.ts#L23

Remapping the keybings for `tooltip:launch-console` and `tooltip:launch-notebook` to another keybinding (`Accel Shift X` for example) makes both bindings work. But it doesn't feel right to drop the `Shift Tab` binding which currently works in the classic notebook...

**Comment by telamonian** [comment]
So let's see... the correct behavior would be: 

- action: "Shift Tab" is pressed within the leading whitespace of any line in a cell
- reaction: the codemirror `'indentLess'` command fires

I'll look into making that happen

**Comment by telamonian** [comment]
@jtpio @afshin Okay, I think #5060 fixes the issue. Let me know if the PR needs any fixes/changes
