### ISSUE TITLE
CI tests fail for unpublished packages

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#4809]
Currently, there doesn't seem to be a way for the CI tests to pass when you add a new package, that isn't published in NPM. This presents a certain chicken and egg situation, where you don't want to publish before tests pass, but you can't get tests pass till you publish. The most recent example of this was in changing the vega package name (https://github.com/jupyterlab/jupyterlab/pull/4661). See that the integrity tests fail https://travis-ci.org/jupyterlab/jupyterlab/jobs/392485712.

AFAIK there is no reason why CI tests should depend on any published versions of jupyterlab packages. They should only use the local versions in that commit.

**Comment by vidartf** [comment]
But https://github.com/jupyterlab/jupyterlab/pull/4682 seems to pass, and I don't think those are published yet?

**Comment by saulshanabrook** [comment]
Hm, good point. I am not sure then. I remember this came up before https://github.com/jupyterlab/jupyterlab/pull/4085#issuecomment-370439605

**Comment by ian-r-rose** [comment]
I solved this in #4806 by specifically *not* changing the `package.json` and `yarn.lock` for core mode (the bundle found in `jupyterlab/staging` and `jupyterlab/statiic`. Those operate off of published packages.

**Comment by saulshanabrook** [comment]
Closing this then, since we seem to be able to do it.
