### ISSUE TITLE
 error when duplicate the tab in chrome

### ISSUE THREAD

**Issue by isalirezag** [jupyterlab/jupyterlab#4814]
Im using jupyter lab 
My system is ubuntu 16.04 and my browser is chromium.
When i duplicate the my jupyter tab after liske 10 min it stops working and i had to restart the jupyter and also when im trying to save something using it, it shows this errror:
import numpy as np
![image](https://user-images.githubusercontent.com/12434910/42103419-04a3b460-7b97-11e8-97fb-b0e79ac8d897.png)

also when im trying to open a *.py file and save it in jupyter it again shows that error

**Comment by isalirezag** [comment]
i dont know what was the reason but it disappeared!

**Comment by jasongrout** [comment]
The next release of jupyterlab supports opening jlab in two different tabs.
