### ISSUE TITLE
open an ipynb by inserting its address

### ISSUE THREAD

**Issue by isalirezag** [jupyterlab/jupyterlab#4815]
it would be nice if you guys can add the capability of opening a notebook by using its address. meaning that i can copy its address and paste  it and open it.

**Comment by jasongrout** [comment]
Can you give an example of an address for a notebook. I'm not sure what you mean.

**Comment by jasongrout** [comment]
You can do this now by right-clicking on a notebook and choosing "Copy shareable link" in the context menu. Paste that link into a new browser window to open the notebook. Or in general, you can use urls to open notebooks as described in https://jupyterlab.readthedocs.io/en/stable/user/urls.html. Thanks!

**Comment by jasongrout** [comment]
Feel free to comment below if you'd like to continue the discussion, or if the above is not what you were wanting.
