### ISSUE TITLE
Manage user expectations around third-party extensions and the extension manager

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4820]
From the dev meeting 18 Jul 2018:

- [ ] See if we can easily include a warning in the comment above the setting without the wrapping looking horrible.
- [ ] Pop up a dialog box when the extension setting switches from false to true #4925
- [ ] Distinguish jupyter packages (color? badge? something else?) #4925
- ~~Have a small warning in the extension search interface~~ The branding in the previous item seems sufficient, in connection with the dialog that pops up when you enable the manager.

---
Original text:

We should have a huge red bold disclaimer at the top of the extension manager results that says that these are third party packages with no guarantees and you install at your own risk!

Or we need to curate a very carefully chosen set of "approved" extensions (such as the ipywidgets one?), with a button to search for additional third party ones or something? Or just put a URL field that people can paste a package name into.

**Comment by jasongrout** [comment]
Great question. Many of them have their own curated extension stores, which we would not have the resources to maintain. Here are a few examples off the top of my head:

1. FF extensions: https://addons.mozilla.org/en-US/firefox/extensions/
2. Chrome extensions: https://chrome.google.com/webstore/category/extensions?hl=en
3. MS VSCode: https://marketplace.visualstudio.com/
4. Eclipse: https://marketplace.eclipse.org/
5. Atom: https://atom.io/packages
6. Mobile app stores

In each of these cases, it seems that some level of curation happens, or at least there is some level of accountability so that if a problem is discovered, an extension can be removed and account banned.

Android is interesting - it has a curated store, but also allows you to install packages from arbitrary sources. Perhaps that it a good model - we have a very small list of curated packages (like widgets, and the renderer extensions we personally maintain), and provide a freeform text field for people to paste in a package name. We then point to https://www.npmjs.com/search?q=keywords:jupyterlab-extension for a list of packages. The key thing here is that people are seeing the list of packages on a different website, so it looks much less like a list that is curated by us.

**Comment by dsblank** [comment]
An extension list (ranging from highly suggested to experimental), and API (including versioning, updating, automatic disabling because wrong version, dependencies, etc) should be carefully designed. I suggest you take a look at WordPress plugins to see how they handle these issues: https://wordpress.org/plugins/ 

This is a very healthy ecosystem with many people/companies making money off of their sales of WordPress plugins. Of course, there are free and open source projects there too.

**Comment by vidartf** [comment]
Xref https://github.com/jupyterlab/jupyterlab/issues/3759.

**Comment by jasongrout** [comment]
We talked about this a bit in the dev meeting today, and have a few other possible directions we could go. 

1. Initially, we don't provide *any* discovery services. Instead, we just have a text box where the user can paste in an npm package name, and the automatic version checking and automatic installation happens. We put a big warning in the extension plugins as part of the description for the 'enable' setting.
2. We make a whitelist of extensions in a new repo, and somehow host a data service from that repo (for example, as a static page on readthedocs, generated from that repo). The extension manager lists the extensions from this whitelist. We need this to be dynamic, rather than a static list distributed with JupyterLab, in case we need to make changes to the list (e.g., add a new package, or remove a problematic package) after release.

Having a whitelist and relying on npm to host the packages essentially is a cheap way to have an 'extension store'. It does not help for extensions that need a server- or kernel-side counterpart, of course.

If we do a whitelist, we'd have to somehow communicate very clearly to users what it means to be on the whitelist, and have very clear criteria for getting on it.

I think we tentatively decided in the very near term that we should change the extension manager to implement (1), and we'll have to think and design (2) more carefully, but we also want to get some more feedback. @vidartf? Others?

**Comment by vidartf** [comment]
Suggestion (1) seems rather hobbled and unintuitive, so I'd like to have a better solution if at all possible.

Regarding (2), if we want to actually have a whitelist:
- We should make it easy and clear for extension developers to get new extensions on that list. Otherwise, we can end up scaring away contributors. A simple web form ideally?
- We should make it as low-burden as possible for maintainers to accept new suggestions (a full code review should be out of the question).
- We should make a recipe to follow for how to report bad/insecure packages, and how it should be processed.

Regarding a blacklist for bad actors, I think any malicious activity should be reported to npm as well to ensure it is fully removed. That said, an own list is probably faster to react.

**Comment by saulshanabrook** [comment]
Could we use npm `keywords` to serve as the package list? Like any package that has `jupyterlab` as a keyword? Or `jupyterlab extension`?

**Comment by vidartf** [comment]
@saulshanabrook We're currently using the standardized keyword `jupyterlab-extension`, but anyone can add that keyword, and the fear is that it can be used to maliciously add packages.

**Comment by jasongrout** [comment]
From our discussion in our dev meeting:

1. See if we can easily include a warning in the comment above the setting.
2. Pop up a dialog box when the extension setting switches from false to true
3. Have a small warning in the extension search interface
4. Distinguish jupyter packages (color? badge? something else?)

**Comment by jasongrout** [comment]
CC @tgeorgeux for the UX portion (distinguishing Jupyter packages in the listing)

**Comment by jasongrout** [comment]
Looks like #4925 addresses two of the points above. @ian-r-rose - did you decide against the other two points, or just not implement them for now:

- [ ] See if we can easily include a warning in the comment above the setting without the wrapping looking horrible.
- [ ]  Have a small warning in the extension search interface
