### ISSUE TITLE
'\r' character returns empty string

### ISSUE THREAD

**Issue by gerdm** [jupyterlab/jupyterlab#4822]
Hello, everyone

Whenever trying to type the `\r` character, jupyterlab does not show any result in the console.
<img width="228" alt="screen shot 2018-06-30 at 12 09 44 pm" src="https://user-images.githubusercontent.com/4108759/42127448-83509ffe-7c5e-11e8-8f30-d82e019756a7.png">
This, of course, in contrast to what I would expect if I were to run this exact same code in a jupyter notebook.
<img width="244" alt="screen shot 2018-06-30 at 12 10 36 pm" src="https://user-images.githubusercontent.com/4108759/42127457-bc4d8f2e-7c5e-11e8-9510-51d7095fb764.png">

What might be the cause of this and how can we fix it?
Thanks!

**Comment by jasongrout** [comment]
see also https://github.com/jupyterlab/jupyterlab/pull/3882

**Comment by jasongrout** [comment]
It appears that the classic notebook actually does the correct thing mentioned in https://github.com/jupyterlab/jupyterlab/pull/3882#discussion_r168646065
