### ISSUE TITLE
JupyterLab 0.33 release plans

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4827]
This issue is to coordinate the 0.33 release.

- [x] Publish js packages
- [x] Publish release
- [ ] Conda-forge: https://github.com/conda-forge/jupyterlab-feedstock/pull/112
- [ ] Publish blog post
- [ ] Update binder

The current plan is to release after Scipy (i.e., after July 13), so that we still have the more stable 0.32 release current during Scipy.

**Comment by jasongrout** [comment]
Scipy is next week. It seems that lots of people will probably demo things in JupyterLab, so I'm thinking at this point that it is too late to release before scipy and have all the extensions that people will be using updated by Scipy, especially 3rd party extensions. I'd like to propose that we release 0.33 perhaps at the end of scipy or the week after scipy.

**Comment by hainm** [comment]
Can you please also update version compatibility for upyterlab-manager too?

https://www.npmjs.com/package/@jupyter-widgets/jupyterlab-manager

**Comment by jasongrout** [comment]
> Can you please also update version compatibility for upyterlab-manager too?

Definitely. That's one of the extensions for the "update various extensions" point above.

**Comment by jasongrout** [comment]
Just released 0.33.0rc1 with some updates to the services package, removing the uuid() function in preference to phosphor's, and a few other bugfixes.

**Comment by jasongrout** [comment]
The js packages have been released by @blink1073.

We should check the examples for errors - we think there might be an error from this code assuming there is a link element for the shortcut icon on the page: https://github.com/jupyterlab/jupyterlab/blob/1aff4190084fd5993d3f7e3ae10b467264df1cd0/packages/application-extension/src/index.tsx#L282-L285

**Comment by blink1073** [comment]
We need patch releases for services and application-extension.

**Comment by blink1073** [comment]
Need patch release for codemirror.

**Comment by blink1073** [comment]
Done in https://github.com/jupyterlab/jupyterlab/pull/4968.
