### ISSUE TITLE
Fail to render embedded image in markdown cells

### ISSUE THREAD

**Issue by BoPeng** [jupyterlab/jupyterlab#4828]
I have notebooks with embedded images, created by pasting images from clipboard to classic Jupyter. JupyterLab fails to render these images and just display `image.png`:

![image](https://user-images.githubusercontent.com/9889312/42198338-0da70de2-7e4d-11e8-9814-488026a484c8.png)

This is [a test notebook with embedded image](https://github.com/jupyterlab/jupyterlab/files/2157621/test_embedded_image.ipynb.zip)

**Comment by jasongrout** [comment]
I think the attachment work in 0.33 might take care of this. Can you try in the 0.33 prerelease?

**Comment by BoPeng** [comment]
I can confirm that JLab trunk (0.33rc0) can display the images correctly, but pasting image to markdown cell does not work. Is this a to-be-implemented feature, a bug, or is there a different way (shortcut) to do this?

**Comment by jasongrout** [comment]
CC @ian-r-rose

**Comment by vidartf** [comment]
Xref https://github.com/jupyterlab/jupyterlab/pull/4373. Support for adding/removing attachments is still missing.

**Comment by vidartf** [comment]
I think #4373 closed this. We now have #5744 to track outstanding features.
