### ISSUE TITLE
Execute code with shift+enter does not work in editor when it's a .py file

### ISSUE THREAD

**Issue by tbenschop** [jupyterlab/jupyterlab#4829]
Shift+enter works when it's a .txt file but when the filename is changed to .py it's not executed anymore.

**Comment by jasongrout** [comment]
What version of JupyterLab are you using? How are you creating the console? Does it work if you open up a .py file fresh (without changing the name)? Does it only stop working if you change the name of the file?

**Comment by gnestor** [comment]
I'm finding the opposite: If the file is a .py file, SHIFT+ENTER is executing the file in its respective console.

**Comment by jasongrout** [comment]
Closing since the author did not follow up.
