### ISSUE TITLE
Is there any plan to display full name of notebook?

### ISSUE THREAD

**Issue by EnboYang** [jupyterlab/jupyterlab#4830]
Just as displayed in the pic, I am working with two notebooks, they have similar name. If jupyterlab can display the full name of the current notebook, that will be good.
![_012](https://user-images.githubusercontent.com/6906305/42211046-20bc3ef0-7ee5-11e8-899e-669fc6229943.png)

**Comment by ian-r-rose** [comment]
Hi @EnboYang, #4801 increased the tab width so that more of the name will display. Even then, long names can be clipped by the tab width. In that case, you can hover your mouse over the tab to see the full name, as well as some additional information.
