### ISSUE TITLE
Document `terminalsAvailable` in the user docs.

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#4831]
The `page_config.json` settings should document `terminalsAvailable` here: https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/extensions.rst

**Comment by chalmerlowe** [comment]
Gonna take a look at refining the verbiage in the documentation for this [https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/extensions.rst](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/extensions.rst) document.
