### ISSUE TITLE
Console run keystroke setting strips formatting from keyboard shortcuts

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4836]
I had some nice custom keyboard shortcuts, nicely formatted. Changing the Settings | Console run keystroke rewrites the settings so that all my formatting and comments are now gone.

**Comment by jasongrout** [comment]
CC @ian-r-rose.

**Comment by jasongrout** [comment]
This may be something we want to address in beta 4, rather than holding up beta 3, unless someone wants to work on it in the next week.

**Comment by ian-r-rose** [comment]
This happens with any programmatic setting of the JupyterLab settings (for instance, changing the autosave behavior also has this effect). It is a consequence of setting a key in the setting registry via an extension: the setting registry only outputs the raw JSON of the settings, without any comments or formatting.

I think it should be relatively straightforwards to add linebreaks, as well as the default comment annotations. I am not sure how we could straightforwardly preserve custom comments. What do you think @afshin?
