### ISSUE TITLE
Console input 

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4837]
I noticed on at least one computer that now, when changing the Settings | Console run keystroke setting to "Enter", after executing code in the console the input box is not focused anymore, which may be a fallout of #4330.

**Comment by jasongrout** [comment]
Can someone confirm if this is happening or not?

**Comment by blink1073** [comment]
I don't see this locally.  I used the following overrides:

```json
{
        "console:linebreak": {
      "command": "console:linebreak",
      "keys": [
        "Shift Enter"
      ],
      "selector": ".jp-CodeConsole-promptCell"
    },
    
        "console:run-forced": {
      "command": "console:run-forced",
      "keys": [
        "Enter"
      ],
      "selector": ".jp-CodeConsole-promptCell"
    }
}
```

**Comment by ian-r-rose** [comment]
I can reproduce this. I'll look into a fix today.
