### ISSUE TITLE
Adding a signal for application dirty status state changes

### ISSUE THREAD

**Issue by dharmaquark** [jupyterlab/jupyterlab#4840]
I would like to add a dirtySignal, similar to busySignal, that returns a signal for when the application changes it’s dirty status. This would be useful for extensions that would like to show a visual indication of the dirty state- in the chrome tab, for example, similar to what the application-extension does with the favicon here: https://github.com/jupyterlab/jupyterlab/blob/master/packages/application-extension/src/index.tsx#L280

Proposed modification:
https://github.com/jupyterlab/jupyterlab/compare/master...dharmaquark:0718-dirtysignal?expand=1

Since, in theory, any extension could update the dirty status via setDirty, down the line, it might useful to add something like callback logic to ‘reset’ the dirty status. Currently, the dirty state reflects unsaved documents, and that state can only be cleared when documents are saved. It might be useful to introduce an API that allows an extension to actively clear the dirty state from the app level- each extension that sets dirty state would have the option of connecting to something like a callback that gets triggered when the dirty state is reset at the app level (eg. in the doc manager, that could trigger a ‘save all’ command)

**Comment by ian-r-rose** [comment]
Fixed by #4844. Thanks @dharmaquark!
