### ISSUE TITLE
[Feature Request] Console "Run File" option

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#4850]
In a text file linked to a console you can execute highlighted lines with `Shift-Enter`. It would be good if there were also options to run the entire file and also to restart the kernel and run the entire file.

These options could be available in the Run/Kernel menus respectively when a python file with an attached console has focus.

**Comment by mnmelo** [comment]
I would also find this requested feature very useful.

**Comment by JasonWeill** [comment]
Run > Restart Kernel and Run All Cells … now does this.
