### ISSUE TITLE
Command Palette

### ISSUE THREAD

**Issue by t-makaro** [jupyterlab/jupyterlab#4851]
Jupyter Notebook has a command palette (spelt wrong in the notebook but it's there) opened with the keyboard shortcut ```ctrl+shift+p```, and so does vs code. I can't seem to find one in jupyter lab (```ctrl+shift+p``` just opens an in-private tab in MS edge and the print menu in chrome).

![image](https://user-images.githubusercontent.com/18018386/42423078-e6ed2e06-82a8-11e8-8fa6-b23108e44ef5.png)

**Comment by blink1073** [comment]
Hi @t-makaro, the command palette is one of the left tab items (`Commands`), and is available as Ctrl/Cmd + Shift + C.  We chose that combination to avoid conflicting with the private browser tab shortcut.

**Comment by t-makaro** [comment]
Ah. Thank you. I was expecting something that looks more like the notebook/vs code command palette. No wonder I didn't find it. I actually didn't know that the notebook had a command palette until I went looking for it after using vs code despite having used the notebook for a couple years. Mouse hovering over the tab to display the shortcut might be a good way to make that shortcut more discoverable.

**Comment by dhirschfeld** [comment]
On the topic of dicoverability it might be useful when no tabs are open to display some of the most useful shortcuts similar to how VSCode does it:

![image](https://user-images.githubusercontent.com/881019/42482124-6c95f606-8429-11e8-918f-3a136a1a5b4d.png)
