### ISSUE TITLE
MS Edge Support

### ISSUE THREAD

**Issue by t-makaro** [jupyterlab/jupyterlab#4852]
I know that the docs say that the Edge browser is unsupported because Edge 14 did not have CSS variables, but Edge 15 added support for CSS variables in April of 2017, and the latest release of Edge is version 17.

For the most part Jupyter lab works in Edge, but I have 2 main issues:
1. Performance. Scrolling and typing in the text editor lags. If I click on a menu, it opens, then I hover the mouse cursor over an adjacent menu and it lags between switching.
2. The pdf viewer does not work. It opens and displays nothing. jupyterlab-latex uses its own pdf viewer which does work.

**Comment by ian-r-rose** [comment]
Thanks for the report @t-makaro! Hopefully some of the performance issues will be improved by further development of Edge. I can also take a look at the PDF behavior to try to see what is going wrong...

**Comment by t-makaro** [comment]
I suppose that this will take care of itself because of [Edge embracing Chromium](https://www.theverge.com/2018/12/6/18128648/microsoft-edge-chrome-chromium-browser-changes).

**Comment by t-makaro** [comment]
Closing now that the chromium edge beta is out.
