### ISSUE TITLE
UI issue: indentation mess up in .py code editor when a instruction is too long

### ISSUE THREAD

**Issue by therealarty** [jupyterlab/jupyterlab#4853]
As a graphical / UI issue is alway clearer with pictures, 
here are screenshot illustrating the issue.

Basically, when a line is too long to be displayed, the line wrapping messes up with the indentation..

I am running chrome if it is relevant.
Let me know if you need more information

![screen shot 2018-07-09 at 11 20 41](https://user-images.githubusercontent.com/9209293/42442173-49479ed0-836a-11e8-8aae-523317401ae9.png)
![screen shot 2018-07-09 at 11 20 22](https://user-images.githubusercontent.com/9209293/42442174-495f421a-836a-11e8-9562-34f054d858f7.png)

**Comment by jasongrout** [comment]
Can you disable word wrap from the View menu?

**Comment by therealarty** [comment]
Hi Jason.
Disabling word wrap solves this strange indentation display issue indeed.
So it has to do with word wrap..

Le lun. 9 juil. 2018 à 19:36, Jason Grout <notifications@github.com> a
écrit :

**Comment by jasongrout** [comment]
Great, glad that solved the issue!
