### ISSUE TITLE
Error: Object 'jupyter.widget' not found in registry

### ISSUE THREAD

**Issue by MariuszJurowicz** [jupyterlab/jupyterlab#4855]
The error is thrown when more than one notebook panel is opened when Lab launch.
There are more than one kernel started and only one at the beginning has the eg. jupyter.widgets extension registered.
The error is thrown even when no 3rd party extension is used and the simple ipywidgets widget has to be rendered.

The error is thrown even when we try to send msg to comm, targeting the custom `com_target` that has been registered during the custom extension registration step.

Please see https://github.com/twosigma/beakerx/issues/7520

**Comment by saulshanabrook** [comment]
How can we reproduce this?

**Comment by double-u-a** [comment]
Same for me, `Error: Object 'jupyter.widget' not found in registry` is thrown when I have more than one notebook panel open at launch.

Restarting with only one tab returns no errors.

**Comment by jasongrout** [comment]
I can't reproduce this either. I start up Lab with a workspace with three notebooks, and I see each kernel being connected to twice, and no error messages.

What versions of jupyter lab, ipywidgets, and the jlab widget manager do you have installed?

**Comment by double-u-a** [comment]
I performed the conda install jupyter lab and widgets installations this week, so what ever is currently on the conda channels, using Windows 10. I can confirm exact versions on Monday.

**Comment by double-u-a** [comment]
```
jupyter lab 0.34.9
ipywidgets 7.4.2

Known labextensions:
   app dir: C:\Apps\Anaconda\envs\ium\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v0.37.4 enabled  ok
```

NB Running on Firefox 62 with UBlock Origin

**Comment by leogout** [comment]
Hello, same here:
```bash
$ jupyter labextension list
JupyterLab v0.34.0
Known labextensions:
   app dir: /root/miniconda3/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.37.4  enabled  OK
@jupyterlab/plotly-extension
        @jupyterlab/plotly-extension v0.17.2  enabled  OK
plotlywidget
        plotlywidget v0.3.0  enabled  OK
```
```bash
$ pip list # curated a bit this one, ask for the full list if needed
Package             Version
------------------- ---------
conda               4.5.4
html5lib            1.0.1
ipykernel           4.8.2
ipython             6.4.0
ipython-genutils    0.2.0
ipywidgets          7.2.1
jsonschema          2.6.0
jupyter-client      5.2.3
jupyter-core        4.4.0
jupyterlab          0.34.0
jupyterlab-launcher 0.13.1
matplotlib          2.2.2
notebook            5.5.0
numpy               1.14.5
pandas              0.22.0
pip                 10.0.1
plotly              3.2.1
scipy               1.1.0
setuptools          39.2.0
widgetsnbextension  3.2.1
```

**Comment by ugg0t** [comment]
After googling for a while without hope, I realized that I need
```python
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

**Comment by mtkilic** [comment]
I am getting same error and I have jupyterlab- manager install

Result jupyter labextension list:
@jupyter-widgets/jupyterlab-manager v0.38.1 enabled  ok
        @jupyterlab/plotly-extension v0.18.2 enabled  ok
        bqplot v0.4.5 enabled  ok
        jupyter-matplotlib v0.3.0 enabled  ok
        jupyterlab-chart-editor v1.1.0 enabled  ok
        plotlywidget v0.10.0 enabled  ok
Result pip list:
ipykernel          5.1.0
ipython            7.5.0
ipython-genutils   0.2.0
ipywidgets         7.4.2
jupyter-client     5.2.4
jupyter-core       4.4.0
jupyterlab         0.35.4
jupyterlab-server  0.2.0
plotly             3.9.0

**Comment by remborg** [comment]
I have jupyterlab-manager (1.0.2) installed on Jupyter Lab (1.0.2) but still the issue.
I think I've managed to reproduce the bug though:

1. In a new notebook, create an ipywidget component :
```
from ipywidgets import Button
Button(description = 'Test')
```
2. Save the notebook and open it again in another tab with 'Editor'
3. Open the notebook and run the first cell, the bug should show on the debugger

**Comment by remborg** [comment]
I've just tried the v1.1.0rc0 and it works perfectly :)
Thank you @jasongrout !

**Comment by jasongrout** [comment]
Great!

**Comment by creative-resort** [comment]
I'm experiencing the issue again with JupyterLab 1.0.2
Is there a regression?

**Comment by jasongrout** [comment]
No, there shouldn't be a regression. Can you update to 1.1.1?

This error is a very generic error with any number of causes, usually I think having to do with an installation issue. So it would be best to open a new issue (please follow the reporting diagnosis guide at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to get a reproducible scenario and gather relevant information)

**Comment by grisaitis** [comment]
To recap, is the solution to this issue to...
1. use jupyterlab >= 1.1
2. `jupyter labextension install @jupyter-widgets/jupyterlab-manager`

?

Or is the widgets manager not required?

Without `manager`, I saw this error with jupyterlab `1.1.1`.

![image](https://user-images.githubusercontent.com/908970/64359363-2a3b6f80-cfd6-11e9-8b44-a9c03e572db2.png)
