### ISSUE TITLE
no quit and logout button for lab web page

### ISSUE THREAD

**Issue by zgqallen** [jupyterlab/jupyterlab#4859]
I known we can have these two buttons by switching to classic mode, but this is very ease-to-use. Just wonder if the lab has the plan to enable these two buttons in the lab web page by default.

**Comment by ian-r-rose** [comment]
Hi @zgqallen, as far as I can tell this is a duplicate of #4414. Can we continue the discussion there?

**Comment by zgqallen** [comment]
@ian-r-rose  Thanks for your response, i will check status of the #4414.
