### ISSUE TITLE
System Defaults Keyboard Shorcuts are missing a comma separator

### ISSUE THREAD

**Issue by pxm162** [jupyterlab/jupyterlab#4863]
When trying to customize Keyboard Shorcuts, by copying and pasting from the System Default raises an error for the missing separator.
![imagen](https://user-images.githubusercontent.com/40879419/42519310-c33c3f8a-8431-11e8-9086-9723429669ab.png)

**Comment by ian-r-rose** [comment]
Hi @pxm162, thanks for the report! This should have been fixed in #4591, which should be available in the next release.

**Comment by blink1073** [comment]
Closing as fixed, please comment here if you still see the problem in 0.34.
