### ISSUE TITLE
Dark theme printing python string still rendering in light theme style

### ISSUE THREAD

**Issue by stephanie-howson** [jupyterlab/jupyterlab#4865]
Dark theme isn't rendering output correctly from a simple print statement in python. (White text on white background). See image:
<img width="646" alt="screen shot 2018-07-10 at 10 13 37 am" src="https://user-images.githubusercontent.com/41071250/42520314-90008f14-842b-11e8-847e-8539fd2fdc01.png">

**Comment by ian-r-rose** [comment]
Hi @stephanie-howson, what version of JupyterLab are you using? I can't reproduce this on my installation.

**Comment by stephanie-howson** [comment]
0.31.5 ... updating my version now.

**Comment by stephanie-howson** [comment]
looks like 0.32.1 also has the issue.

**Comment by ian-r-rose** [comment]
I suspect something is broken with your install (specifically with the theme bundling). If you have `node` installed, can you run `jupyter lab build`? If not, can you attempt a fresh reinstall of JupyterLab?

**Comment by stephanie-howson** [comment]
Rebuild fixed. Thanks @ian-r-rose 
<img width="491" alt="screen shot 2018-07-10 at 10 42 51 am" src="https://user-images.githubusercontent.com/41071250/42521288-0b63e640-842e-11e8-8fe1-2751b87490dc.png">

**Comment by ian-r-rose** [comment]
Glad to hear it's fixed.
