### ISSUE TITLE
Double plots in Jupyterlab (Linux)

### ISSUE THREAD

**Issue by marmot2019** [jupyterlab/jupyterlab#4868]
I was plotting some graphs using matplotlib.  When I run the notebook in Linux (Ubuntu 16.04 LTS), I get a duplicate pair of graphs, but when I run in Windows 10, I get only one pair of graphs (what I want).  I have attached a screenshot of both outputs.  Note for the Linux, I restarted the kernel (Python 3) and cleared the output before running all the cells.

**Windows 10**
![windows10-output-correct](https://user-images.githubusercontent.com/20498374/42525216-d74adfc4-842f-11e8-8005-edea30b63b11.png)

**Linux**
![linux-output-wrong](https://user-images.githubusercontent.com/20498374/42525260-ed84af86-842f-11e8-94b8-a5df3d5aa23c.png)

**Comment by danieltomasz** [comment]
This may be caused by the plot function both plotting the graph AND returning the results which then  causes IPython Notebook to plot the results again. If instead you  assign  the results to a variable, then you could  get only a single plot.
