### ISSUE TITLE
[Bug] JupyterLab always starts with opening the same files that I haven't opened in months

### ISSUE THREAD

**Issue by jolespin** [jupyterlab/jupyterlab#4869]
I have uninstalled and installed: `jupyterlab-0.32.1` with `pip`.

Everytime I open `jupyterlab` it opens several files that I haven't touched in a while.  Each time I open `jupyterlab` I have to manually close those notebooks. 

Is there a start file where I can delete this option?  Ideally, I would like a fresh slate each time I open `jupyterlab`.

**Comment by hadim** [comment]
I am actually seeing the same thing.

**Comment by afshin** [comment]
@jolespin @hadim Could you try adding `?reset` to your URL? If your URL already has query params, add `&reset`, like this:

```
http://localhost:8888/lab?reset
```

or:

```
http://localhost:8888/lab?foo=bar&reset
```

**Comment by afshin** [comment]
It should not be necessary to repeatedly reset the URL, but I'm not sure what you mean by startup profile.

**Comment by ian-r-rose** [comment]
You can set the default url for launching JupyterLab to always reset the workspace. In your `jupyter_notebook_config.py` file, enter `c.LabApp.default_url = '/lab?reset'`

**Comment by jolespin** [comment]
Awesome, Where is the default location for this file?

**Comment by ian-r-rose** [comment]
@jolespin Did that fix things for you?

**Comment by jolespin** [comment]
Unfortunately it didn't work.  I've tried it on 2 computers.

**Comment by ian-r-rose** [comment]
What is reset equal to in your screenshot? It should just be the string `reset`. Is the configuration correctly launching lab with the url that you specify, or is it not picking up the configuration?

**Comment by amangarg96** [comment]
Hi, I am facing the exact same issue which jolespin faced above. 

I have set --LabApp.default_url='/lab?reset', but the browser has a trailing '=' at the end.
When I remove the trailing '=' from the browser, the reset workspace works. 

What can be the issue for this? 

I'm using JupyterLab 0.33.11 on Python 2.7, with Chrome Version 74.0.3729.169 (Official Build) (64-bit) on a MacOS Mojave Version 10.14.5

**Comment by jolespin** [comment]
Any settings I can adjust to fix this?

**Comment by jolespin** [comment]
This definitely fixed it.  Is there an option in the settings to set this as the default?

**Comment by amangarg96** [comment]
Yes. You can make the above configs part of a config file, which would get
loaded everytime you launch jupyterlab.

Generate the config file by running
`jupyter-lab --generate-config`
It will create a config file in your home directory (For Mac users ->
`/home/<user>/.jupyter/jupyter_notebook_config.py`)

In this file, uncomment and set the relevant configs.

**Comment by jolespin** [comment]
Here's the beginning of my config that I had previously which I thought would have had the desired effect. 

Do  I need to add `--NotebookApp.token=''` to it somehwere as well? 

```
# Configuration file for jupyter-notebook.

#------------------------------------------------------------------------------
# Application(SingletonConfigurable) configuration
#------------------------------------------------------------------------------

## This is an application.

## The date format used by logging formatters for %(asctime)s
#c.Application.log_datefmt = '%Y-%m-%d %H:%M:%S'

## The Logging format template
#c.Application.log_format = '[%(name)s]%(highlevel)s %(message)s'

## Set the log level by value or name.
#c.Application.log_level = 30

#------------------------------------------------------------------------------
# JupyterApp(Application) configuration
#------------------------------------------------------------------------------

## Base class for Jupyter applications

c.LabApp.default_url = '/lab?reset'

## Answer yes to any prompts.
#c.JupyterApp.answer_yes = False

## Full path of a config file.
#c.JupyterApp.config_file = ''

## Specify a config file to load.
#c.JupyterApp.config_file_name = ''

## Generate default config file.
#c.JupyterApp.generate_config = False
```

**Comment by amangarg96** [comment]
Just like you have `c.LabApp.default_url='/lab?reset' `,
You can add the line `c.NotebookApp.token='' `
