### ISSUE TITLE
Jupyter labextension install hangs on "Resolving packages..." on os x 

### ISSUE THREAD

**Issue by timkpaine** [jupyterlab/jupyterlab#4877]
There are some issues right now with yarn/node compatibility, if anyone is unable to install lab extensions on os x high sierra with latest node via home-brew, try downgrading to node8

`brew install node@8`

**Comment by Will-So** [comment]
I get this problem on Ubuntu as well. It took me awhile to figure out how to downgrade Node in Ubuntu. I had to use sudo for some reason for both commands.

```
 npm install -g n
n 8
node -v
```

**Comment by BoPeng** [comment]
I had the same problem and was wondering what happened.

**Comment by jasongrout** [comment]
Our version of yarn (1.6) won't work with node 10. The latest version of yarn (1.8) fixes this, but unfortunately introduces another serious bug, so we are waiting to upgrade yarn when yarn 1.9 comes out soon. See #4793 for more details.
