### ISSUE TITLE
Add a screen of empty space at the bottom of notebooks and consoles

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#488]
It's really nice to be able to scroll so that the last input in a notebook or console is actually at the top of the screen. This is extremely useful in presentations, and also is good so that you don't have to look at the bottom of your screen all the time.

There are standard ways to do this with CSS, IIRC.

**Comment by jasongrout** [comment]
For example, adding a padding of 100% on the jp-Notebook-container div seems to do it for the notebook. I'm sure there are other ways to do it as well.

**Comment by sccolbert** [comment]
At some point, this should be a user setting.

**Comment by jasongrout** [comment]
Agreed. Many IDEs have a "Scroll past end" setting.

**Comment by ellisonbg** [comment]
For the console, I think the cell being typed into should not be in the scrollable div at all, but should be fixed to the bottom of the whole console area. This would make it much clearer that the console is a whole different beast than the notebook.

**Comment by rsinha25** [comment]
Hi, this looks like a good start for me. Can I work on this?

**Comment by jasongrout** [comment]
> Hi, this looks like a good start for me. Can I work on this?

Please! Thanks!

**Comment by rsinha25** [comment]
Hi, on adding the padding  to the notebook, it does work for certain screen sizes. But since it's a percentage, the height of the div changes accordingly on resizing causing the CSS to break. I can't think of a way around this. I tried it with a fixed padding of 200px as well, and it works fine on decreasing the width of the screen but again causes the CSS to break when you decrease the height.

**Comment by ellisonbg** [comment]
Running into this again myself in using JupyterLab. Marking as beta...

**Comment by scwolof** [comment]
Could someone please copy-paste the snippet I need to add to user overrides for this?
I can't get "scrollPastEnd" to work.

**Comment by jasongrout** [comment]
Just checking, what version of JLab do you have?

**Comment by scwolof** [comment]
I have the latest pypi release, 0.35.4, which I now see was released on 3 November 2018.
