### ISSUE TITLE
Styling of raw input fields

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#4880]
Right now (v0.32) a raw input field looks like this:

![image](https://user-images.githubusercontent.com/2069677/42632650-29870286-85de-11e8-9ef1-cd524b0180c8.png)

Firstly, this is quite a bit smaller than in the classic notebook:

![image](https://user-images.githubusercontent.com/2069677/42632707-5ab24938-85de-11e8-9482-4bef96e635e2.png)

Secondly, within the shell console app the situation is much better anyway:

![image](https://user-images.githubusercontent.com/2069677/42632744-83067c9c-85de-11e8-84d1-91f097da215f.png)

I think if the input field would increase with the size of the input, or at least would have a larger default size, the user experience would be better.

**Comment by jasongrout** [comment]
Thanks for bringing this up!
