### ISSUE TITLE
 PDF viewer not working in Firefox

### ISSUE THREAD

**Issue by djangoliv** [jupyterlab/jupyterlab#4892]
I have jupyterlab 0.32.1 and firefox 61.0.1 (64 bits).

When I open a pdf in jupyterlab I only have a blank page. I tested on chrome with the same jupyterlab and the 
same pdf file and it works fine.

Regards

**Comment by blink1073** [comment]
Hi @djangoliv, what operating system are you using?  I just tried with 0.32.1 and firefox 61.0.1 on MacOS 10.13.5 and it is rendering PDFs for me.  Does the pdf sample [here](http://unec.edu.az/application/uploads/2014/12/pdf-sample.pdf) work for you?  If it does, are you able to share the PDF that does not work?

**Comment by ian-r-rose** [comment]
I can also not reproduce this on Firefox 60.0.1 with Ubuntu 18.04.

**Comment by t-makaro** [comment]
I cannot reproduce on Firefox 61.0.1 on Windows 10 Version 1803. I can however reproduce this on MS Edge 42.17134.1.0 / EdgeHTML 17.17134. The jupyterlab-latex extension uses it's own pdf viewer which does work on MS Edge.

**Comment by djangoliv** [comment]
Hi @blink1073 

I am on debian stretch. Your pdf sample doesn't  work for me.

Thanks

**Comment by blink1073** [comment]
Thanks for the follow up @djangoliv.  It looks like we need to port the pdf viewer from https://github.com/jupyterlab/jupyterlab-latex to JupyterLab core.

**Comment by blink1073** [comment]
And thank you for the report as well @t-makaro.

**Comment by jasongrout** [comment]
The latex extension bundles pdf.js, right? How big is it? FYI, that may be a heavy dependency, and may need to be lazily loaded, like the @bollwyvl's recent work to lazily load vega.

**Comment by blink1073** [comment]
I installed `pdf-dist` into a simple webpack test app and it added ~1.2MB to the bundle.

**Comment by jasongrout** [comment]
That's definitely above the 'lazy load' threshold @bollwyvl suggested, especially for a renderer for a specific type of file. For whoever works on this, his work on lazy loading vega is at #4706.

**Comment by ian-r-rose** [comment]
Yeah, PDFJS is an *extremely* heavy dependency, so we would definitely want to make it lazy-loaded.

It should be relatively straightforward to port the PDFJS viewer from `@jupyterlab/latex` to the core of JupyterLab. A couple of extra thoughts:
* It relies fairly heavily on web-workers. Have we established best-practices for how to incorporate those into the build? In the extension I found it kind of fussy, and just stopped touching it once I got it working.
* For many (most?) people, the browser-native PDF viewer works fine. Should we make a setting that decides whether to use that vs. PDFJS?
* On the other hand, PDFJS has an actual API, so extension authors can actually interact with PDFs if they so desire (this is the reason we went with it in the LaTeX extension). That API, however, is extremely not-documented and not particularly stable, and the PDFJS project doesn't really follow semver.

**Comment by bollwyvl** [comment]
>
>
>
>    - It relies fairly heavily on web-workers. Have we established
>    best-practices for how to incorporate those into the build? In the
>    extension I found it kind of fussy, and just stopped touching it once I got
>    it working.
>
> Using  https://github.com/webpack-contrib/worker-loader ?

>
>    - For many (most?) people, the browser-native PDF viewer works fine.
>    Should we make a setting that decides whether to use that vs. PDFJS?
>
>
More settings for renderers sounds great. Similar I'd love to have
remarkable for markdown, as it supports source line numbers for synced
scrolling. Or try native, then opt in. Or just two renderer entries.


>    - On the other hand, PDFJS has an actual API, so extension authors can
>    actually interact with PDFs if they so desire (this is the reason we went
>    with it in the LaTeX extension). That API, however, is extremely
>    not-documented and not particularly stable, and the PDFJS project doesn't
>    really follow semver.
>
> Annotations would be amazing.

>
>    -
>
>

**Comment by ibeatty** [comment]
I'm seeing the same behavior — PDF files open up as blank tabs — on Mac OS X 10.14.1, in both Firefox (63.0.1) and Safari (12.0.1). They display correctly in Chrome (69.0.3497.81).

**Comment by vit1-irk** [comment]
Still doesn't work in all latest Firefox versions under both Linux and MacOS

This is a view from developer console:

```
Warning: Invalid absolute docBaseUrl: "blob:http://localhost:8881/dafd64f5-5c84-4e6f-923a-fd4f850401da". pdf.worker.js:984:13
PDF 2557297811f4d2c8626bbd3d6554e67e [1.4 Matplotlib pdf backend v3.7.1 / Matplotlib v3.7.1, https://matplotlib.org] (PDF.js: 3.6.13 [df5fb71ca]) viewer.js:1470:13
```

PDF displaying in Chromium-based browsers works as expected.

**Comment by JasonWeill** [comment]
Now working in Firefox on macOS in Lab 4.1.0.
