### ISSUE TITLE
Finalize Vega view when the cell is replaced

### ISSUE THREAD

**Issue by domoritz** [jupyterlab/jupyterlab#4897]
In https://github.com/altair-viz/altair/issues/1007, we found that we crash the browser when we execute a cell over and over. To resolve this, we need to call `view.finalize()` before the cell gets overwritten. Is there an event handler that we can attach to?

**Comment by domoritz** [comment]
Bonus points if you can tell me how to do this in Jupyter Notebook.

**Comment by ian-r-rose** [comment]
If I understand you correctly, you want to free some resources when the cell is re-rendered? I recommend adding a `dispose()` method to the `RenderedVega` class. I think you would want to keep a reference to the current view as a private member on the class, i.e.
```typescript
this._result = await vega.default(el, spec, {
...
```
Then you would add a method like
```typescript
dispose(): void {
  if (this._result) {
    this._result.view.finalize();
  }
  super.dispose();
}
```
This should be called automatically when the old cell output is removed.

I am not sure the best way to proceed with the classic notebook.
