### ISSUE TITLE
Remove the "Beta" release label?

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4898]
I think we are being somewhat ineffective in communicating to users that JupyterLab is ready for use. I propose that we drop the "Beta" label on releases, but still keep the pre-1.0 version number. We've had discussions and disagreements about whether we want to release 1.0 or not, and I think this strikes a nice balance of communicating what we want to the different audiences we are addressing.

As a huge generalization, users seem to pay attention to the words, while developers seem to pay attention to the more precise and semantically meaningful version numbers. If we want to communicate to users that JLab is ready for use, I think we should drop the "Beta" label. If we want to communicate to developers that we are still stabilizing the extension api, and breaking changes are coming every 4-6 weeks with a new 0.x release, we should keep the pre-1.0 version numbers. I think we want to do both, so I propose we call the next release just JupyterLab 0.33.

I think we have done a lot of polishing since February, so I think it was still valuable to have a "beta" release period up to this point.

What do you think? Are there some important polish issues to address before dropping the beta label?

**Comment by blink1073** [comment]
My preference would be for 0.34 to also include 1.0+ releases of all of the JavaScript packages.   That gives us more semver space to make additive changes across the board while making it less painful for extension authors.  The top level message is still that that overall application is not yet 1.0.

**Comment by afshin** [comment]
> I think we should drop the "Beta" label.

I am 👍 on this.

> My preference would be for 0.34 to also include 1.0+ releases of all of the JavaScript packages.

I am 👍 on this.

> The top level message is still that that overall application is not yet 1.0.

I am 👎 on this.

**Comment by jasongrout** [comment]
>> The top level message is still that that overall application is not yet 1.0.
> 
> I am 👎 on this.

Just to clarify, are you 👍 on making the overall application 1.0?

**Comment by afshin** [comment]
Sorry, I was being a little facetious here. I agree with removing the beta wording in the codebase, the docs, and the way we talk about JupyterLab. I don't believe our actual version number should change.

**Comment by ian-r-rose** [comment]
I agree that we can remove the "Beta" branding. I am agnostic about whether we should go to 1.0 in all of the packages. I practice we will be doing semver-major version bumps for a while yet, but I don't think it matters much to us or to extension authors whether they are pre or post 1.0.

**Comment by ellisonbg** [comment]
I am +1 on removing the beta branding. On the versioning side, I don't know that it makes a huge difference either way as long as we follow semver. However, there may be specific reasons that individuals or organizations have for wanting or not wanting to call a particular release 1.0.

**Comment by SimonBiggs** [comment]
https://github.com/jupyterlab/jupyterlab/issues/4898#issuecomment-405018112

> My preference would be for 0.34 to also include 1.0+ releases of all of the JavaScript packages. That gives us more semver space to make additive changes across the board while making it less painful for extension authors. The top level message is still that that overall application is not yet 1.0.

I know that I would personally appreciate a semver signal within the JavaScript libraries that a breaking change has occured. It would mean, should a JavaScript dependency bump a major version then I need to go and track down the breaking changes for that particular version. That's far better than what I do currently which is avoid upgrading until I have a lot of time available...
