### ISSUE TITLE
Switching to the "File" tab in sidebar not displaying the file browser

### ISSUE THREAD

**Issue by mrakitin** [jupyterlab/jupyterlab#4907]
I observe an issue with displaying the file browser when switching to the "File" tab:
![image](https://user-images.githubusercontent.com/13209176/42739284-3702aec8-885a-11e8-8c3a-f2ea486ff258.png)
Page reload helps to get back the file browser, but the issue happens again when switching between the tabs in the sidebar.

Jupyterlab version: 0.33.0rc1 (installed in the development mode). I'd be happy to learn how to fix this kind of issues.

**Comment by ian-r-rose** [comment]
I saw this a couple of days ago and thought I was imagining it. Thanks for the info!
