### ISSUE TITLE
Impossible to interrupt console waiting for input after a refresh

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#4911]
To reproduce on jupyterlab v0.33rc1:

1. Open a Py3 console
2. Execute `input()`
3. Refresh jupyterlab
4. Try to interrupt console from e.g. the kernel menu.
5. Observe that it is impossible to restore the console to working state other than by restarting the kernel.

By comparison, jupyterlab's notebook component gracefully handles a similar situation.

**Comment by blink1073** [comment]
Hi @akhmerov, I tried the above steps, and was able to subsequently run `print('hi')` in the console after the interrupt, is there something I'm missing?  I am using Firefox 61.01 on MacOS 10.13.5.

**Comment by akhmerov** [comment]
Turns out I wasn't sufficiently thorough in investigating what is happening.

If you try to execute something before interrupting the kernel, that command shows as being executed forever. However that behavior is the same without page refresh and waiting for input.

I guess the only thing one could improve here is giving a clearer visual cue that the kernel is busy.

**Comment by blink1073** [comment]
Agreed it is awkward, mind opening an issue?
