### ISSUE TITLE
"Open" broken for nested directories in file browser context menu

### ISSUE THREAD

**Issue by dmarth** [jupyterlab/jupyterlab#4913]
When right-clicking on the file browser, the context menu opens. For directories a click on the "Open" button should enter the directory and list its files in the file browser. This works fine on the first level but fails with nested paths.

To reproduce create a directory "a" in the workspace root directory via the file browser. Inside "a" create another directory "b". When choosing "Open" in the context menu for "a", the following endpoint is used:
`/api/contents/a`
When doing the same thing for "b", one would expect the following endpoint:
`/api/contents/a/b`
However, actually the following endpoint is used:
`/api/contents/a/a/b`
The paths are incorrectly combined and the frontend shows an error message:
> Invalid response: 404 Not Found

The simplest solution would probably be to pass only the directory name (instead of the path) from the context menu.

Note that double-clicking the directories works fine in all cases.

**Comment by blink1073** [comment]
Confirmed, thanks!

**Comment by blink1073** [comment]
I marked this as "good first issue" if anyone wants to tackle it, the call site is [here](https://github.com/jupyterlab/jupyterlab/blob/15de899eafdf37d158e0109a156c60a663d29c25/packages/filebrowser-extension/src/index.ts), which calls [this](https://github.com/jupyterlab/jupyterlab/blob/15de899eafdf37d158e0109a156c60a663d29c25/packages/filebrowser/src/model.ts#L231).
