### ISSUE TITLE
Better indication of console busy state

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#4915]
Follow-up from #4911.

When kernel is blocked, the console doesn't give any indication that it's busy, which may lead to a confusing user experience after refreshing the page or starting a new session.

Copying the free/busy icon from the notebook would be a possible solution.

**Comment by tgeorgeux** [comment]
We are incorporating a status bar that was designed over the summer. It will have a Kernel status indicator for consoles.

**Comment by tgeorgeux** [comment]
Status bar is now in JupyterLab core. I'm going to close this issue as solved for now. 

@akhmerov feel free to give it a test drive and let us know what you think! (Kernel/Console status is located in the bottom left corner).
