### ISSUE TITLE
Console: incorrect cell status update on interrupt

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#4916]
Interrupting the console's kernel will result in all cells except for the one that's being interrupted being shown as "running" forever:

![image](https://user-images.githubusercontent.com/2069677/42812947-81fb19a4-89bf-11e8-8279-786f16039ed3.png)

**Comment by jasongrout** [comment]
This might be the same issue as #5366.

**Comment by jasongrout** [comment]
This was not solved by #5423. Perhaps there is a similar solution in the console code, though?

**Comment by askerry** [comment]
@jasongrout are you still able to reproduce this? I'm not reproducing the problem on master (the "*" is properly cleared for all subsequent cells when I interrupt kernel).
