### ISSUE TITLE
need help with importing a library geopy [jupyterlab]:

### ISSUE THREAD

**Issue by AmulPatil** [jupyterlab/jupyterlab#4917]
hi Team,

Im loving jupyterlab.
got small issue with using geopy library in jupyterlab.
```
console input: !pip install geopy
console output:
Requirement already satisfied: geopy in c:\users\demons\appdata\local\programs\python\python36-32\lib\site-packages (1.15.0)
Requirement already satisfied: geographiclib<2,>=1.49 in c:\users\demons\appdata\local\programs\python\python36-32\lib\site-packages (from geopy) (1.49)

console input:import geopy
console output:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-8940c3473e3c> in <module>()
----> 1 import geopy

ModuleNotFoundError: No module named 'geopy'
```

Appreciate the help

**Comment by AmulPatil** [comment]
the same commands works in jupyter notebook

**Comment by jleni** [comment]
I am having the exact some problem with pytorch + conda

**Comment by jasongrout** [comment]
Is the pip command perhaps not affecting whatever kernel you are running? Can you do `import sys; sys.prefix` to make sure your kernel's python directory is where your pip is installing things?

Same for @jleni with conda - does sys.prefix match with where conda is putting things?

**Comment by jleni** [comment]
Thanks @jasongrout 

If I run the following
```
import sys
import os
print(sys.prefix)
print(os.environ['CONDA_DEFAULT_ENV'])
```

**jupyter**
> /home/my_user/anaconda3/envs/test
> test

**jupyter-lab**
> /home/my_user/anaconda3
> test

**Comment by jleni** [comment]
mm... more interesting is that:

```
import os
print(os.__file__)
```

**jupyter**
> /home/my_user/anaconda3/envs/test/lib/python3.6/os.py

**jupyter-lab**
> /home/my_user/anaconda3/lib/python3.6/os.py

clearly jupyter-lab is not using the conda environment.. although it did install both in the same environment and started both from within.. 

Am I missing some specific diffference?

**Comment by jasongrout** [comment]
It looks to me like you are executing two different kernels. First, I would make sure you are using jlab and notebook from the *same* notebook server (in the jlab help menu, click "Launch classic notebook").

**Comment by jasongrout** [comment]
Then I would make *sure* you are choosing the console with the right kernel - you can use "Change Kernel" from the run menu to change the kernel if you need.

**Comment by jleni** [comment]
Yes, it is definitely different kernels.. running classic notebook from jlab also fails.

works:
> source activate test
> jupyter notebook

fails:
> source activate test
> jupyter-lab

I guess that jlab kernels do not inherit / considers the environment configuration where it is launched but jupyter notebook does?

**Comment by jasongrout** [comment]
No, jlab doesn't do anything with deciding kernels, that's all in the notebook server. I would double and triple check that you are actually launching jlab from within the conda environment, and that the actual jlab launched is actually installed in the conda environment.

**Comment by jasongrout** [comment]
(so doing `which jupyter-lab` to see where it is being launched from, then launching it inside the environment)

**Comment by jasongrout** [comment]
Also, typically we launch jlab with `jupyter lab` (space, not dash). The `jupyter` executable makes sure that `jupyter-lab` is called correctly.

**Comment by jleni** [comment]
Thank you very much.
The problem was that jupyter-lab was installed in the base environment but jupyter was in both the base and test environment. Somehow, while in the test environment was possible still reach jlab using `jupyter lab` 
I have uninstalled everything from the base environment.

**Comment by jasongrout** [comment]
Personally, I install a small miniconda, then make the base environment read-only so it's impossible to install more stuff in it. This problem has bitten me more than once.

```
cd path/to/miniconda
chmod -R u-w bin/ etc/ include/ lib/ share/ ssl/
```

**Comment by jleni** [comment]
excellent tip! Thanks again!

**Comment by jasongrout** [comment]
and I don't activate the base environment by default in my shell profile.

**Comment by jasongrout** [comment]
@AmulPatil - how are you doing on resolving the issue?

**Comment by AmulPatil** [comment]
issue is been resolved. when i ran jupyter lab (updated version)from anaconda prompt.
geopy is importing successfully.
Thanks with the assistance.

**Comment by AmulPatil** [comment]
in default base directory(anaconda prompt) ran jupyterlab importing geopy was successful.
if i change the directory of(anaconda prompt) ran jupyternotebook.console throughs error.[ex:pandas,scipy other packages works fine in this case]

**Comment by ghazalghorbani** [comment]
hi
would you please help me?i really
tiered of this error and done most the things that here says but .........
