### ISSUE TITLE
Extension manager not querying

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#4923]
The extension manager seems to not be searching the NPM registry properly in my install (it is finding nothing). It used to, so I am not sure what could be wrong. Can anyone else reproduce this?

**Comment by blink1073** [comment]
I just tried against master, I am seeing the following 3 packages:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/2096628/42934885-e8097d5e-8b0d-11e8-97a4-d00b6c2d6b0f.png">

**Comment by jasongrout** [comment]
I saw this last week, where no packages showed by default, but searching for space (' ') yielded the normal list of packages.

**Comment by ian-r-rose** [comment]
I see those same three packages, but a week or two ago got the full list. I can reproduce it on the keyword search in npm's site. It seems something might be wrong with their keyword search ability?

**Comment by jasongrout** [comment]
Looks like npm is having search issues for the past two weeks: https://status.npmjs.org/incidents/frcp18csxlks

**Comment by ian-r-rose** [comment]
I suppose we can close this as not our problem. It will take the air out of the new extension manager until it is resolved though :)

**Comment by jasongrout** [comment]
We could switch to npms.io, as mentioned in the status message?

**Comment by jasongrout** [comment]
Or it's probably not worth it, hopefully they finish rebuilding the index before we release!

**Comment by ian-r-rose** [comment]
I think (hope?) it's not worth it.
