### ISSUE TITLE
Notebooks with extension other than ipynb are displayed as text

### ISSUE THREAD

**Issue by mwouts** [jupyterlab/jupyterlab#4924]
Alternative contents manager allow to open notebooks from files with other extensions that ipynb, and that work very well in jupyter notebook.

However, this does not appear to work in jupyter lab (see also #3896).

In the below I have isolated a very simple content manager, that does nothing else than opening files with extension `.ipynb2` as notebooks. That content manager works fine in jupyter notebook, but not in jupyter lab, where the notebook with extension `.ipynb2` (a copy of a valid notebook), is displayed as text:

![image](https://user-images.githubusercontent.com/29915202/42913141-6fb3f2ae-8af3-11e8-9178-e116252f0ffb.png)

For that test my jupyter config was
```
import notebook.transutils
from notebook.services.contents.filemanager import FileContentsManager


class SampleFileContentsManager(FileContentsManager):
    def get(self, path, content=True, type=None, format=None):
        """ Takes a path for an entity and returns its model"""
        path = path.strip('/')

        if self.exists(path) and \
                (type == 'notebook' or
                 (type is None and (
                         path.endswith('.ipynb') or path.endswith(
                     '.ipynb2')))):
            return self._notebook_model(path, content=content)
        else:
            return super(SampleFileContentsManager, self) \
                .get(path, content, type, format)


c.NotebookApp.contents_manager_class = SampleFileContentsManager
```

**Comment by grst** [comment]
**Setting the notebook icon** is implemented in 
https://github.com/jupyterlab/jupyterlab/blob/3d7a43c3b00a23f3cdcae3410bbcaa7730a10258/packages/filebrowser/src/listing.ts#L742
and uses `getFileTypeForModel`
https://github.com/jupyterlab/jupyterlab/blob/6d58acf2b7ecb749d1b1deb0fefae9cde25b7507/packages/docregistry/src/registry.ts#L536
which correctly identifies `ipynb2` as notebook.

----

Whereas **opening files** is implemented in https://github.com/jupyterlab/jupyterlab/blob/3d7a43c3b00a23f3cdcae3410bbcaa7730a10258/packages/filebrowser-extension/src/index.ts#L485
and uses `getFileTypeForPath`
https://github.com/jupyterlab/jupyterlab/blob/6d58acf2b7ecb749d1b1deb0fefae9cde25b7507/packages/docregistry/src/registry.ts#L570
which relies on the extension only and therefore does not get the notebook type. 

----
@jasongrout is there a design rationale behind this or is that something that should be changed for consistency?

**Comment by jasongrout** [comment]
The status quo, like you point out, is that we have multiple viewers, and the viewer is chosen before the file is opened (with `Open with`, or simply as the default viewer). Right now, the default viewers and options for the `Open with` menu are all made from file extensions, not from the types returned from the contents manager.

I like your implicit suggestion: we have a specific override for the notebook file type, like in the icon code you point out, so we don't look at the file extension registry unless the file contents model declares it as of type file.

The one disadvantage to that is that it won't be possible to open notebook files as text anymore. Actually, that may good right now, since we have a problem with opening a file with both text and notebook models, in that the views will not sync, which is surprising to many people. Perhaps we just suggest that in this case, you rename the file to another file extension, open the file in the text editor and do whatever you want, then rename back to a notebook file extension.

**Comment by jasongrout** [comment]
Another approach would be to prefer a default `notebook` file type viewer if the contents model indicates it is a notebook, but also merge in the `Open with` menu options coming from the file extension.

**Comment by jasongrout** [comment]
Assigning to the next milestone so we can look at this soon.

If you'd like to submit a PR, that would be great!

**Comment by jasongrout** [comment]
Or perhaps a simpler PR would be to edit https://github.com/jupyterlab/jupyterlab/blob/3d7a43c3b00a23f3cdcae3410bbcaa7730a10258/packages/filebrowser-extension/src/index.ts#L484 to do a check for the notebook type.

I think you've investigated the codebase well enough to see a few ways to fix this. Can you submit a PR?

**Comment by blink1073** [comment]
Note: we should have some other way to edit notebook metadata if we don't allow opening as a text file.

**Comment by grst** [comment]
@blink1073, should I open a separate issue for that? I believe that a separate metadata editor like in jupyter notebook is more user-friendly anyway. 

@jasongrout, the simplest PR you propose sounds pretty straightforward. I can try that. 
But I have hardly any experience with TypeScript nor did I work with the jupyterlab code base before.

**Comment by blink1073** [comment]
We have an issue for it [here](https://github.com/jupyterlab/jupyterlab/issues/1308), I was on my phone when I typed the previous comment :wink:.

**Comment by jasongrout** [comment]
@grst, that is why we are particularly excited to help you make a pr :).

**Comment by grst** [comment]
I'm afraid I won't have time looking into this until September.
