### ISSUE TITLE
Scrolling in large cells

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#4926]
Mouse wheel scrolling in notebooks where code cells are long enough to toggle to scrolled mode can be now a really frustrating experience.

To reproduce create a notebook with sufficiently large cells, or use [this one](http://nbviewer.jupyter.org/url/antonakhmerov.org/misc/long_cells.ipynb).

When a long cell is selected and one starts scrolling when having the mouse cursor within the cell, the browser will prioritize scrolling the cell first and the notebook afterwards. This results in a non-monotonous scrolling speed, delays in scrolling, and some times the scrolling even gets stuck.

I am not sure what the best solution would be, short of disabling scrolling on cells (but that has other downsides).

**Comment by keithcallenberg** [comment]
I was seeing this in Jupyterlab 0.32.x, but after upgrading to 0.33.4 I am no longer seeing this. Could you try upgrading?

**Comment by akhmerov** [comment]
Indeed, it was fixed, thanks for letting me know.

**Comment by jasongrout** [comment]
see also #4745, which seems similar.
