### ISSUE TITLE
How to test example apps?

### ISSUE THREAD

**Issue by kouohhashi** [jupyterlab/jupyterlab#4933]
Hi I'm new to webpack.

How can I test example code?

I downloaded repository by
```git clone https://github.com/jupyterlab/jupyterlab.git```

but
```npm install```  which I usually do
show error like
```sh: tsc: command not found```

and when I try at examples/app
```npm install```
It worked without any errors but I don't know what to do next.

Could you give me instruction to check all example codes one by one?

My node version is v8.9.1

Thanks in advance.

**Comment by blink1073** [comment]
Hi @kouohhashi, the example build/run instructions are [here](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#build-and-run-the-stand-alone-examples).

**Comment by kouohhashi** [comment]
Thanks!
