### ISSUE TITLE
Should "pip" be "pip3" in README?

### ISSUE THREAD

**Issue by david-a-wheeler** [jupyterlab/jupyterlab#4940]
The current installation documentation notes pip as an install option in the README.  However, shouldn't that recommend "pip3", or note that you can use either "pip3" (for Python3) or "pip" (for python2)?  Also, a hint or link of how to install pip if you haven't done that would be helpful (e.g., on Debian/Ubuntu it's "sudo apt-get install python3-pip" to install pip3).

All of the install instructions seem to assume that the reader knows what conda/pip/etc. are, but I don't think they should make that assumption at all.  At least a hint of how to install one of those installers (and other necessary programs) would probably be a good idea.

Thanks so much for JupyterLab!  I'm already using Jupyter notebook, and I'm looking to using JupyterLab in the future.

**Comment by david-a-wheeler** [comment]
Does pip (Python2) work? Or is it only pip3? I have never tried it with straight pip.

**Comment by vidartf** [comment]
Note, `pip3` is a plattform specific command, that makes no sense on e.g. Windows, so any text would need to reflect this.

**Comment by david-a-wheeler** [comment]
pip3 isn't platform-specific, it's Python-specific.  pip3 is available on Windows.

**Comment by david-a-wheeler** [comment]
I plan to create a PR, but I'm hoping someone will tell me if `pip` actually works.  Otherwise I'll just change `pip` to `pip3`.

**Comment by dsblank** [comment]
`pip` can indeed work, if it is associated with Python3.

**Comment by david-a-wheeler** [comment]
No. On many systems, probably most systems, python means python2, and pip is the one for python2. It is safer and more portable to say "pip3" and "python3" if only python3 is intended.

**Comment by blink1073** [comment]
I would argue that most people have `python` (and  usually `pip`) aliased to the one they use most frequently, and that is the shorthand taken by almost every install instruction I've seen for Python libraries.

**Comment by dsblank** [comment]
I agree with @blink1073 

However, many people that use Jupyter are coming from different worlds (Java, Matlab, Octave, R, etc,) and so the details of pip/anaconda may be very unfamiliar. Even Python programmers can be confused over these details. Perhaps we can link to a page (or write one) that has a good summary of the technical details of these issues and suggestions of what to try, and where to go for help.

**Comment by blink1073** [comment]
Thanks for that perspective, @dsblank, I concur.

**Comment by david-a-wheeler** [comment]
A lot of people are going to have whatever the platform they're on does. On many systems, pip means python2. Or even worse, it varies. It would be better to have instructions that simply work every time.

I think you have answered my key question, running jupyter lab requires python3, so instructions that imply the use of python2 are incorrect.

**Comment by blink1073** [comment]
We support python 2.  I don't think we should attempt to cover every install situation here, but point to an authoritative doc on pip.

**Comment by jasongrout** [comment]
I think it's fine to have a note that points out that on some systems, pip3 is used for python 3, and then link to a pip document that has more details.

**Comment by david-a-wheeler** [comment]
I know that JupyterLab supports R, Python2, Python3, and many other languages, but my question was about the install instructions.  I think I've found the answer.  Based on other issues and PRs, JupyerLab *does* currently run on both Python2 and Python3 (per [issue 2096](https://github.com/jupyterlab/jupyterlab/issues/2096)), [and there's been effort to keep this working](https://github.com/jupyterlab/jupyterlab/pull/2486).  That said, I think it's clear that *new* installs should be encouraged to install JupyterLab on top of Python3 instead of Python2, *even* if JupyterLab will be used to run Python2 code.  So my draft PR will encourage people to use Python3 when installing JupyterLab using pip (e.g., invoking pip as "pip3" is a useful way to ensure it).

@jasongrout: Yes, completely agree that the install docs should link to other docs with more details.  There's obviously no need to rewrite everything.  Just make it easy for people to find the information they need.

**Comment by david-a-wheeler** [comment]
I've made PR to add more information to the installation directions.  The PR adds a little info about the options (for those who haven't heard of them), adds hyperlinks to more detailed install instructions (if someone doesn't have it), and recommends using pip3/Python3 (yes, Python2 works, but it's going to be deprecated, so encourage new users to install JupyterLab on Python3 instead).
