### ISSUE TITLE
NotebookApp.default_url appears to have ceased working at v0.31.12 

### ISSUE THREAD

**Issue by ChuckRIHead** [jupyterlab/jupyterlab#4947]
I had been using NotebookApp.default_url to specify the opening folder for my users when they started up Jupyterlab in a docker container. I'd been writing the desired path into jupyter_notebook_config.py

It was working as expected until >0.31.12, afterwhich the NotebookApp.default_url doesn't seem to have any effect.

**Comment by blink1073** [comment]
Hi @ChuckRIHead, does `jupyter lab --NotebookApp.default_url="/tree"` not take you to the classic tree page?  It does for me with latest master.

**Comment by jasongrout** [comment]
Closing as no response. Please comment below if you'd like to the continue the discussion. Thanks!
