### ISSUE TITLE
[Feature] Send highlighted code from editor to attached console

### ISSUE THREAD

**Issue by idoDavid** [jupyterlab/jupyterlab#4949]
Hi,
Would love the capability to send highlighted code from the editor to the console via keyboard shortcut. It's useful for debugging cell with few code lines without running the entire cell. 

WDYT?

**Comment by blink1073** [comment]
Hi @idoDavid, do you mean the cell editor in a notebook, or the text editor?  If you mean the text editor, that is available by selecting "Create Console For Editor", selecting text, and then hitting "Shift+Enter".

**Comment by idoDavid** [comment]
@blink1073 I mean from the cell editor in a notebook, so it would be easy to check snippets of code inside a cell. for example let's say I have a code cell with some code:

![image](https://user-images.githubusercontent.com/35657989/43129878-00236b78-8f3e-11e8-86cd-b5557fea5d1f.png)

I now want to send a few lines to the console by highlighting and press a key:

![image](https://user-images.githubusercontent.com/35657989/43129935-26d8f9ae-8f3e-11e8-8c17-4d75b915e7db.png)

**Comment by ian-r-rose** [comment]
This feature was added in #4330, if I understand what you are describing correctly. There is not any default keybinding for it, but that can be added in the keyboard shortcuts settings.

We plan to release the next version of JupyterLab with this feature today.

**Comment by idoDavid** [comment]
@ian-r-rose great news, waiting for several features already :)

**Comment by idoDavid** [comment]
@ian-r-rose sorry for the little off topic, but how do I know if a release was made?  The releases tab is full of non jupyterlab releases it seems..

**Comment by jasongrout** [comment]
The release isn't made yet. We're wrapping up the last few issues: https://github.com/jupyterlab/jupyterlab/milestone/12

**Comment by blink1073** [comment]
Fixed!
