### ISSUE TITLE
Kernel Gateway returns Messed up Traceback

### ISSUE THREAD

**Issue by bashterm** [jupyterlab/jupyterlab#4950]
I've been working on a standalone angular app that utilizes the @jupyterlab/services package in order to interact with the kernel gateway.

Connection works and execution works, but when an error occurs the traceback array comes through very messed up. I'm not sure what the problem is. The result looks like this:

```json
{
  "header": {
    "version": "5.3",
    "date": "2018-07-24T15:06:22.625374Z",
    "session": "3a132ba9-ab67351385c53eaa6514b2c0",
    "username": "username",
    "msg_type": "error",
    "msg_id": "2908ae80-2cf2947f3bff2e2d516214bf"
  },
  "msg_id": "2908ae80-2cf2947f3bff2e2d516214bf",
  "msg_type": "error",
  "parent_header": {
    "username": "",
    "version": "5.2",
    "session": "f3a98c1a6e48718af1764a104628b4ab",
    "msg_id": "398575ac5c19294b161d67da44ef00ac",
    "msg_type": "execute_request",
    "date": "2018-07-24T15:06:22.621538Z"
  },
  "metadata": {},
  "content": {
    "traceback": [
      "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-1-8dc86dcd4f82>\"\u001b[0;36m, line \u001b[0;32m7\u001b[0m\n\u001b[0;31m    print(y)\u001b[0m\n\u001b[0m        ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
    ],
    "ename": "SyntaxError",
    "evalue": "invalid syntax (<ipython-input-1-8dc86dcd4f82>, line 7)"
  },
  "buffers": [],
  "channel": "iopub"
}
```

It seems to be an encoding issue, but I can't figure out how to fix it.

Thanks for any help

**Comment by blink1073** [comment]
Hi @bashterm, do you mean the `\u001b[0;36m` in the traceback itself?  Those are ANSI escape codes added by the ipython kernel to enable formatted output of the traceback.

**Comment by jasongrout** [comment]
Closing as no response. Please comment below if you'd like to the continue the discussion. Thanks!
