### ISSUE TITLE
(Dumb) question: how to use Javascript modules from base Notebook in Lab extension development?

### ISSUE THREAD

**Issue by krinsman** [jupyterlab/jupyterlab#4953]
Caveat lector: I am not a Javascript developer, or at the very least extremely inexperienced with Javascript, and this will probably be painfully obvious based on the following question.

**Background:** I want to somehow use the [`ajax`](https://github.com/jupyter/notebook/blob/58752355b99289319121d845679b97f56bbb78ad/notebook/static/base/js/utils.js#L788) function from Jupyter _Notebook_'s (that is not a typo) `/base/utils` Javascript module ([`/notebook/static/base/js/utils.js`](https://github.com/jupyter/notebook/blob/58752355b99289319121d845679b97f56bbb78ad/notebook/static/base/js/utils.js)) so I can pass along the XRSF token in request headers automatically. (I think [that is the purpose of the function](https://gitter.im/jupyter/notebook?at=5b52a7ebf10ffa0b48a0ab2d).)

**Question:** How can this be done?

**Context:** If I want to use code from the Jupyter Lab "base", I think that's done using something like the following at the beginning of the TypeScript file:

```
import {
  JupyterLab
} from '@jupyterlab/application';
```

It is unclear to me however what type of import statement is required to use JavaScript code from the core Jupyter Notebook application (if such a thing is even possible).

Maybe it is possible to set the XRSF token in the header more directly using something like:

```
      let xhttp = new XMLHttpRequest();
      xhttp.open("POST", "test", true);
      xhttp.setRequestHeader("Authorization", "token "+token);
      xhttp.send();
```
which would be analogous to [how one does it in Python](https://github.com/jupyter/help/issues/172#issuecomment-303717476)?

I can get the requests to work right now if I do them manually with `curl` from the command line, but obviously that's not a user-friendly solution since the extension is supposed to be GUI only.

E.g. 
```curl -X PATCH -H "Authorization: token <token>" -d "ID=13798406" http://localhost:8888/patchurl```

**Comment by blink1073** [comment]
Hi @krinsman, there are definitely no dumb questions in software :smile:.  Even the "easy" stuff is only obvious after doing it a few times.

The classic Notebook's code was not intended to be used as a library (it never had a public API).   The new (easier) way to handle requests in browsers is to use the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).   We provide a utility in JupyterLab for interacting with the Jupyter server if that's what you're trying to do, [ServerConnection](https://github.com/jupyterlab/jupyterlab/blob/ecb76879e8cece4e704cd035e0b1a7d235c40716/packages/services/src/serverconnection.ts#L47).  You could use it as follows:

```typescript
import { ServerConnection } from '@jupyterlab/services';

const settings = ServerConnection.makeSettings();  // uses default settings
const url = 'myurl';
const init = {};  // fetch settings (see fetch API link above)
ServerConnection.makeRequest(url, init, settings).then(response => { console.log('got', response); });
```

**Comment by krinsman** [comment]
I will try to make this work and get back to you; thank you so much for taking the time out of your day to help!

**Comment by krinsman** [comment]
@blink1073 I was able to get this to work using the information provided above, but not the specific method. Namely, analyzing the code for `ServerConnection`, it seems to be the case that the `makeSettings` function [gets the value of the token](https://github.com/jupyterlab/jupyterlab/blob/ecb76879e8cece4e704cd035e0b1a7d235c40716/packages/services/src/serverconnection.ts#L183) from a function called [`getToken`](https://github.com/jupyterlab/jupyterlab/blob/1aff4190084fd5993d3f7e3ae10b467264df1cd0/packages/coreutils/src/pageconfig.ts#L165) from an interface (module? namespace? whatever the correct EC6 term is) called [`PageConfig`](https://github.com/jupyterlab/jupyterlab/blob/1aff4190084fd5993d3f7e3ae10b467264df1cd0/packages/coreutils/src/pageconfig.ts) in [`'@jupyterlab/coreutils'`](https://github.com/jupyterlab/jupyterlab/tree/1aff4190084fd5993d3f7e3ae10b467264df1cd0/packages/coreutils). So utilizing that function directly (i.e. not through `makeSettings`) I was able to get the HTTP requests working within the xhttp framework:

```
import { PageConfig } from '@jupyterlab/coreutils';
...
       let xhttp = new XMLHttpRequest();
       xhttp.open("POST", "test", true);
       xhttp.setRequestHeader("Authorization", "token " + PageConfig.getToken());
       xhttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded")
       xhttp.send("body");
```
(Setting the content type header explicitly was to prevent a bug with Tornado failing to parse the body arguments correctly for the default plain-text/UTF-8 MIME type.)

Ideally in the future though a solution with `fetch` would probably be better.

**Failed attempt at using fetch API:**

Right now the extension doesn't seem to be sending any requests at all. At least, when I open JupyterLab in debug mode and click the buttons that send the requests, nothing happens (whereas with the old code the requests were sent, just rejected for lacking an XRSF token).

What I tried but ***didn't*** work (every time `import { ServerConnection } from '@jupyterlab/services';` was at the beginning of the file, but omitted for brevity, and url was defined earlier):

```
      // let xhttp = new XMLHttpRequest();
      // xhttp.open("POST", "test", true);
      // xhttp.setRequestHeader("Authorization", "token "+ token);
      // xhttp.send();

   const settings = ServerConnection.makeSettings();
      const init = {};
      ServerConnection.makeRequest(url, init, settings).then(response => { console.log('got', response);});
```

```
import { PageConfig } from '@jupyterlab/coreutils';

      // let xhttp = new XMLHttpRequest();
      // xhttp.open("POST", "test", true);
      // xhttp.setRequestHeader("Authorization", "token "+ token);
      // xhttp.send();

   const settings = ServerConnection.makeSettings();
      const init = {};
      ServerConnection.makeRequest(url, init, settings).then(response => { console.log('got', response);});

   const settings = ServerConnection.makeSettings();
      const init = {method: requestType,
                    headers: {
                      "Authorization: token " + PageConfig.getToken(),
                    },};
      ServerConnection.makeRequest(url, init, settings).then(response => { console.log('got', response);});
```

**Comment by krinsman** [comment]
@blink1073 Is this (now commented-out) code an example of how to authorize the HTTP requests without using the outdated XMLHTTP library?

https://github.com/garri1105/jupyterlab_globus/blob/master/src/index.ts#L21

It isn't clear to me if it is using fetch or not.

**Comment by blink1073** [comment]
The `serviceManager` uses `ServerConnection` (which in turn uses `fetch`), so yes!
