### ISSUE TITLE
How about playing wav/mp3 files?

### ISSUE THREAD

**Issue by arogozhnikov** [jupyterlab/jupyterlab#4956]
(sorry for initially posting blank issue)

When I click on the mp3/wav file in the folder, jupyterlab tries to open it, then fails with 
```
File Load Error for 1.wav
JupyterLab is unable to open this file type.
```
or something like 
```
File Load Error for wave.mp3
Invalid response: 400 bad format
```

I think this would be as useful as showing images

**Comment by jtpio** [comment]
Hi @arogozhnikov,

If you can wait a few more days until Beta 3 is released, there will be a new "Open in New Browser Tab" option to the file browser that can open such files in a new tab, and let the browser handle it.

More details in the related PR if you are interested: https://github.com/jupyterlab/jupyterlab/pull/4315

Hope it helps!
