### ISSUE TITLE
Delete extraneous lines

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4958]
These lines are left over from debug log messages, and should be deleted:

https://github.com/jupyterlab/jupyterlab/blob/b83d8856aa075f2a5ec05929ca9b24343e940f1c/packages/services/src/kernel/default.ts#L276-L279

**Comment by sendmebiscuits** [comment]
Hello! I'll look into this one.

**Comment by jasongrout** [comment]
Thanks!
