### ISSUE TITLE
Updating output of cell after end of execution

### ISSUE THREAD

**Issue by pberba** [jupyterlab/jupyterlab#4963]
I'm trying to implement some interactive components on notebooks through ipywidgets. 

Here's an example that works properly in jupyterbook. I make a button that clears the cell output on_click, and prints out  'Done'
```python
from ipywidgets import widgets, interact
from IPython.display import clear_output, display

button = widgets.Button(description='Clear')

def action(b):
    clear_output()
    print('Done!')

button.on_click(action)
display(button)
```

This doesn't seem to work on jupyterlab. I used the current version on [binder](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo). 

I can't seem to modify the display of the output of a cell after the execution of the its code cell is done.

**Comment by jasongrout** [comment]
You'll need to use the output widget to capture the printed output. See the solution at https://github.com/jupyter-widgets/ipywidgets/issues/2148#issuecomment-407789399 for an example.

**Comment by pberba** [comment]
Thanks! 

I got it to work with the following code.

```python
from ipywidgets import widgets, Output
from IPython.display import clear_output, display

out = Output()
button = widgets.Button(description='Clear')

@out.capture()
def action(b):
    clear_output()
    print('Done!')

button.on_click(action)

with out:
    display(button)
    
display(out)
```
