### ISSUE TITLE
Make it possible to override the application.servicemanager.contents.defaultDrive in a plugin

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4972]
A question came up on gitter about overriding the resolver to, for example, not point to `/files/path/to/file` when resolving a download url. One way of doing this is to provide your own rendermime registry and give it a custom resolver. However, if you want to use the existing resolver logic, which asks the appropriate drive to construct a download url, you'll need to go down a deeper path. Basically, you'll need to give a defaultDrive option to the service manager when it is constructed at app startup - but it's not possible to give that option. It's also not possible to set the default drive after the fact (or remove drives after they are added).

It would be great if we could supply a defaultDrive object to the service manager through a plugin, which could then influence the url resolver. It also would be nice if it were easy to, say, have a jupyterlab that was *just* a github browser using the github drive as the default drive.

Diving into the code:

the url resolver could be given when the rendermime registry is created: https://github.com/jupyterlab/jupyterlab/blob/289fd7410f063c26962964ab138fd47c297ead1b/packages/rendermime/src/registry.ts#L61, and: https://github.com/jupyterlab/jupyterlab/blob/289fd7410f063c26962964ab138fd47c297ead1b/packages/rendermime-extension/src/index.ts#L84

the default resolver is here: https://github.com/jupyterlab/jupyterlab/blob/289fd7410f063c26962964ab138fd47c297ead1b/packages/rendermime/src/registry.ts#L354

the default resolver just asks the services contents object for the download path: https://github.com/jupyterlab/jupyterlab/blob/e33fcb9238230696e782c6d734888a71fac09d02/packages/services/src/contents/index.ts#L666, which in turn defers to the drive function: https://github.com/jupyterlab/jupyterlab/blob/e33fcb9238230696e782c6d734888a71fac09d02/packages/services/src/contents/index.ts#L1017, and that function is the one that actually constructs the /files URL
so to use the stock plugins as much as possible, you would just need to either (a) supply your own rendermime registry with your own resolver, or (b) supply your own drive object for the contents manager

The default drive is constructed at https://github.com/jupyterlab/jupyterlab/blob/e33fcb9238230696e782c6d734888a71fac09d02/packages/services/src/contents/index.ts#L531
and that defaultDrive option can be passed down in the ServiceManager: https://github.com/jupyterlab/jupyterlab/blob/e33fcb9238230696e782c6d734888a71fac09d02/packages/services/src/manager.ts#L27, https://github.com/jupyterlab/jupyterlab/blob/e33fcb9238230696e782c6d734888a71fac09d02/packages/services/src/manager.ts#L218

aaaand here's the brick wall at the end: the service manager is constructed at app startup: https://github.com/jupyterlab/jupyterlab/blob/e33fcb9238230696e782c6d734888a71fac09d02/packages/application/src/index.ts#L52

CC @ian-r-rose

**Comment by jasongrout** [comment]
At the very minimum, we should make it possible to pass in a service manager and document registry as options to the JupyterLab application.

**Comment by ian-r-rose** [comment]
Fixed by #5291. Thanks @adobs!
