### ISSUE TITLE
Selenium Check Broken for Consumers

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#4984]
cf https://travis-ci.org/jupyterlab/extension-cookiecutter-ts/builds/408922606#L1217, "Error: Cannot find module 'puppeteer'"

cc @saulshanabrook

**Comment by blink1073** [comment]
We could create a temp dir, run `jlpm install puppeteer`, and then run the tests from that directory.

**Comment by blink1073** [comment]
(or we do it in folder in the application directory to avoid having to re-download every time)

**Comment by gnestor** [comment]
I think the latter makes more sense. Would puppeteer be a dependency of @jupyterlab/application-top?
