### ISSUE TITLE
mention nodejs < 10 in extension docs

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#4986]
http://jupyterlab.readthedocs.io/en/stable/user/extensions.html should mention that we need node < 10.

**Comment by dclong** [comment]
Which one is the recommended nodejs version?

**Comment by blink1073** [comment]
Either 6.x or 8.x are fine

**Comment by jasongrout** [comment]
Node LTS is currently 8.x, so that's recommended.

**Comment by vidartf** [comment]
Xref #4901.

**Comment by ian-r-rose** [comment]
We now support node 10 as of 0.34.
