### ISSUE TITLE
Documentation Links 404

### ISSUE THREAD

**Issue by anthonytec2** [jupyterlab/jupyterlab#4987]
I recently went through some of the documentation and found the bellow errors with links not resolving. Additionally, I found that there are a few blank pages that have no real content in them, I was wondering should there be something in these pages(see Blank Pages)?

**Link Errors**
- build/html/developer/adding_content.html
  *  External link https://github.com/jupyterlab/jupyterlab/blob/master/packages/terminal/typings/xterm/xterm.d.ts failed: 404 No error
- build/html/developer/xkcd_extension_tutorial.html
  *  internally linking to README.html#getting-help, which does not exist (line 406)
     <a class="reference external" href="README.html#getting-help">reach
out</a>
- build/html/developer/notebook.html
  *  External link http://jupyterlab.github.io/jupyterlab/modules/_notebook_src_actions_.notebookactions.html failed: 404 No error
- build/html/developer/documents.html
  *  External link http://jupyterlab.github.io/jupyterlab/interfaces/_docregistry_src_registry_.documentregistry.ireadywidget.html failed: 404 No error

**Blank Pages**
- build/html/genindex.html
  *  External link https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/genindex failed: 404 No error
- build/html/index.html
  *  internally linking to py-modindex.html, which does not exist (line 250)
     <a class="reference internal" href="py-modindex.html"><span class="std std-ref">Module Index</span></a>
- build/html/search.html
  *  External link https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/search failed: 404 No error
  *  script is empty and has no src attribute (line 271)

**Comment by anthonytec2** [comment]
In regards to the blank pages do we want to remove these from the TOC or put index elements in each RST element to populate these pages?

**Comment by anthonytec2** [comment]
I was able to writeup a quick script to extract keywords from the docs, see [here](https://github.com/anthonytec2/jupyterlab/blob/fix-index-docs/docs/keywords.csv). If we want to insert them into the index all we have to do is use the index keyword at the top of the rst files, like done [here](https://github.com/ethereum/solidity/blob/v0.4.24/docs/julia.rst). Would you like me to make a commit using some of the above keywords and the index vars populated?

**Comment by blink1073** [comment]
I'm not sure we'd want to auto-generate that list, the one Julia uses looks hand-curated.
