### ISSUE TITLE
UI should indicate keyboard focus

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#5]
Like for example creating a new notebook:

<img width="470" alt="screen shot 2016-06-04 at 11 08 00" src="https://cloud.githubusercontent.com/assets/335567/15801260/9e88e420-2a44-11e6-9bb0-39c4872a25dd.png">

I have no clue if I have focus to rename, chose the kernel, if enter will cancel or validate.
And `Tab`/`shift-tab` key should cycle through these.

**Comment by blink1073** [comment]
@cameronoelsen, thoughts on this one?

**Comment by Carreau** [comment]
Note that in the long term if we deploy widely on unviersity we might be required to think about accessibility. So keyboard navigation is likely a must have.

Side note, I tend to open these issue with short description, and tend to have authoritative phrasing, 
I should likely turn that more into suggestions.

**Comment by jasongrout** [comment]
@Carreau - we really appreciate you opening these issues! Thanks for trying things out!

**Comment by ellisonbg** [comment]
@ellisonbg will do some research on this one...
