### ISSUE TITLE
Persistent editor settings for the user

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#5001]
I set up the editor to use vim for key mapping and mbo for theme, however the settings are lots every time I fresh or switch to a new browser. It is extremely annoying. It definitely make user experience better by persisting settings for users.
```
{"keyMap":"vim","theme":"mbo"}
```

**Comment by dclong** [comment]
@jasongrout I still encounter this issue with the latest version of JLab. Below are detailed information.

JupyterLab: 0.34.8
JupyterHub: 0.9.2 (I'm using JupyterLab with JupyterHub)

Computer 1:
OS: Win 10
Firefox: 61.0.2

Computer 2:
OS: MacOS High Sierra
Firefox: 61.02

**Comment by ian-r-rose** [comment]
Do you see any errors on either the Javascript console in the browser or the notebook server logs?

**Comment by vidartf** [comment]
@dclong I'm not sure where to find the server logs while in JupyterHub, but for the JS console it depends on your browser. A simple guide for most browsers is here: https://kb.mailster.co/how-can-i-open-the-browsers-console/

**Comment by dclong** [comment]
I finally figured out that it's due a permission issue. Setting the right permissions for the directories and the configuration file fixes the issue.
