### ISSUE TITLE
View Custom Documentation

### ISSUE THREAD

**Issue by WesleyTheGeolien** [jupyterlab/jupyterlab#5003]
Hello,

Thanks for all the hard work on creating the platform!

I am rather new to JupyterLab and recently I saw that you can click help JupyterLab Reference, or any other reference for that matter. This opens the documentation in a new tab. I was wondering if it is possible or if there is a package to link custom documentation that would render in the same manner? For example html documentation generated by Sphinx? 

I was able to navigate through the html source to the window in question and change the source for the JupyterLab Reference documentation but this feels rather 'hacky'

Cheers,

Wesley

**Comment by jasongrout** [comment]
Are you asking how to add your own documentation link in the help menu? The code to add those reference links is here:

https://github.com/jupyterlab/jupyterlab/blob/2e7bdd6889f3da978f361a4b4f3ab8ff011228a8/packages/help-extension/src/index.tsx#L66-L81

https://github.com/jupyterlab/jupyterlab/blob/2e7bdd6889f3da978f361a4b4f3ab8ff011228a8/packages/help-extension/src/index.tsx#L156-L160

You can write an extension to do the same thing - get the help menu, and use `addGroup` to add your own menu items.

**Comment by jasongrout** [comment]
So you'd do something like:

```
 const helpMenu = mainMenu.helpMenu;
const group = [
{ command: 'help:open', args: {text: 'Some title', url: 'https://my.doc.url/'},
{ command: 'help:open', args: {text: 'Another title', url: 'https://my.doc2.url/'}
];
helpMenu.addGroup(group, 10);
```

in your extension. Your extension would need to import and require IMainMenu like https://github.com/jupyterlab/jupyterlab/blob/2e7bdd6889f3da978f361a4b4f3ab8ff011228a8/packages/help-extension/src/index.tsx#L93

**Comment by WesleyTheGeolien** [comment]
Thanks @jasongrout I saw something along those lines when I was looking through the source code, just wondering if anything had already been done, seems like a good place to start for creating an extension :)

**Comment by jasongrout** [comment]
> seems like a good place to start for creating an extension :)

Yep! And definitely a good place for a short tutorial or blog post about the process too.
