### ISSUE TITLE
Network connection issues when installing from Source

### ISSUE THREAD

**Issue by WesleyTheGeolien** [jupyterlab/jupyterlab#5010]
I am trying to run jupyterlab from source, I followed the [doc](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md) and installed the necessary packages. (I have had jupyterlab working in this conda enviroment using `conda install jupyterlab`)

I then clone the jupyterlab repo and run : 
`pip install -e .`

and receive the following log : 

Obtaining file:///D:/Repos/jupyterlab
Requirement already satisfied: notebook>=4.3.1 in c:\programdata\miniconda3\lib\site-packages (from jupyterlab==0.33.4) (5.6.0)
Requirement already satisfied: jupyterlab_launcher<0.12.0,>=0.11.2 in c:\programdata\miniconda3\lib\site-packages (from jupyterlab==0.33.4) (0.11.2)
Requirement already satisfied: ipython_genutils in c:\programdata\miniconda3\lib\site-packages (from jupyterlab==0.33.4) (0.2.0)
Requirement already satisfied: jinja2 in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (2.10)
Requirement already satisfied: tornado>=4 in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (5.0.2)
Requirement already satisfied: pyzmq>=17 in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (17.0.0)
Requirement already satisfied: traitlets>=4.2.1 in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (4.3.2)
Requirement already satisfied: jupyter_core>=4.4.0 in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (4.4.0)
Requirement already satisfied: jupyter_client>=5.2.0 in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (5.2.3)
Requirement already satisfied: nbformat in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (4.4.0)
Requirement already satisfied: nbconvert in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (5.3.1)
Requirement already satisfied: ipykernel in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (4.8.2)
Requirement already satisfied: Send2Trash in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (1.5.0)
Requirement already satisfied: terminado>=0.8.1 in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (0.8.1)
Requirement already satisfied: prometheus_client in c:\programdata\miniconda3\lib\site-packages (from notebook>=4.3.1->jupyterlab==0.33.4) (0.3.0)
Requirement already satisfied: jsonschema>=2.6.0 in c:\programdata\miniconda3\lib\site-packages (from jupyterlab_launcher<0.12.0,>=0.11.2->jupyterlab==0.33.4) (2.6.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\miniconda3\lib\site-packages (from jinja2->notebook>=4.3.1->jupyterlab==0.33.4) (1.0)
Requirement already satisfied: six in c:\programdata\miniconda3\lib\site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab==0.33.4) (1.11.0)
Requirement already satisfied: decorator in c:\programdata\miniconda3\lib\site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab==0.33.4) (4.3.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\programdata\miniconda3\lib\site-packages (from jupyter_client>=5.2.0->notebook>=4.3.1->jupyterlab==0.33.4) (2.7.3)
Requirement already satisfied: mistune>=0.7.4 in c:\programdata\miniconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyterlab==0.33.4) (0.8.3)
Requirement already satisfied: pygments in c:\programdata\miniconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyterlab==0.33.4) (2.2.0)
Requirement already satisfied: entrypoints>=0.2.2 in c:\programdata\miniconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyterlab==0.33.4) (0.2.3)
Requirement already satisfied: bleach in c:\programdata\miniconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyterlab==0.33.4) (2.1.3)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\programdata\miniconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyterlab==0.33.4) (1.4.2)
Requirement already satisfied: testpath in c:\programdata\miniconda3\lib\site-packages (from nbconvert->notebook>=4.3.1->jupyterlab==0.33.4) (0.3.1)
Requirement already satisfied: ipython>=4.0.0 in c:\programdata\miniconda3\lib\site-packages (from ipykernel->notebook>=4.3.1->jupyterlab==0.33.4) (6.4.0)
Requirement already satisfied: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in c:\programdata\miniconda3\lib\site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyterlab==0.33.4) (1.0.1)
Requirement already satisfied: jedi>=0.10 in c:\programdata\miniconda3\lib\site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab==0.33.4) (0.12.0)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\programdata\miniconda3\lib\site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab==0.33.4) (0.3.9)
Requirement already satisfied: setuptools>=18.5 in c:\programdata\miniconda3\lib\site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab==0.33.4) (38.4.0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.15 in c:\programdata\miniconda3\lib\site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab==0.33.4) (1.0.15)
Requirement already satisfied: backcall in c:\programdata\miniconda3\lib\site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab==0.33.4) (0.1.0)
Requirement already satisfied: pickleshare in c:\programdata\miniconda3\lib\site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab==0.33.4) (0.7.4)
Requirement already satisfied: simplegeneric>0.8 in c:\programdata\miniconda3\lib\site-packages (from ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab==0.33.4) (0.8.1)
Requirement already satisfied: webencodings in c:\programdata\miniconda3\lib\site-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach->nbconvert->notebook>=4.3.1->jupyterlab==0.33.4) (0.5.1)
Requirement already satisfied: parso>=0.2.0 in c:\programdata\miniconda3\lib\site-packages (from jedi>=0.10->ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab==0.33.4) (0.2.1)
Requirement already satisfied: wcwidth in c:\programdata\miniconda3\lib\site-packages (from prompt-toolkit<2.0.0,>=1.0.15->ipython>=4.0.0->ipykernel->notebook>=4.3.1->jupyterlab==0.33.4) (0.1.7)
Installing collected packages: jupyterlab
  Running setup.py develop for jupyterlab
    Complete output from command c:\programdata\miniconda3\python.exe -c "import setuptools, tokenize;__file__='D:\\Repos\\jupyterlab\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    > node D:\Repos\jupyterlab\jupyterlab\staging\yarn.js
    yarn install v1.6.0
    (node:200) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    error An unexpected error occurred: "https://registry.npmjs.org/rxjs/-/rxjs-6.2.0.tgz: ESOCKETTIMEDOUT".
    info If you think this is a bug, please open a bug report with the information provided in "D:\\Repos\\jupyterlab\\yarn-error.log".
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\Repos\jupyterlab\setup.py", line 166, in <module>
        setup(**setup_args)
      File "c:\programdata\miniconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\programdata\miniconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\programdata\miniconda3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\programdata\miniconda3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:\Repos\jupyterlab\setup.py", line 95, in run
        run(npm, cwd=HERE)
      File "D:\Repos\jupyterlab\setupbase.py", line 216, in run
        return subprocess.check_call(cmd, **kwargs)
      File "c:\programdata\miniconda3\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\programdata\\miniconda3\\node.exe', 'D:\\Repos\\jupyterlab\\jupyterlab\\staging\\yarn.js']' returned non-zero exit status 1.

    ----------------------------------------
Command "c:\programdata\miniconda3\python.exe -c "import setuptools, tokenize;__file__='D:\\Repos\\jupyterlab\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in D:\Repos\jupyterlab\

I have also attached the [yarn-error.log](https://github.com/jupyterlab/jupyterlab/files/2243203/yarn-error.log).

If I understand this correctly it looks like there is a timeout when retrieving : https://registry.npmjs.org/rxjs/-/rxjs-6.2.0.tgz , I have gone to this page in a browser and it sets of the download for the package .... 

I have also spun up a Ubuntu and tried the same steps and the installation worked without any hickups. I am on a Windows 10 64bit machine.

Recently I have also been experiencing problems installing @jupyterlab/plotly-extension with a similar timeout error but have managed to install other packages without a problem.

I was wondering if someone could point me in the right direction.

Cheers

**Comment by jasongrout** [comment]
I haven't seen this before.

**Comment by WesleyTheGeolien** [comment]
A fresh reinstall of conda lets me install JupyterLab without any hiccups, I still have a "broken" conda if any further testing is desired

**Comment by jasongrout** [comment]
I think it's probably best to close as resolved. I'm glad it's working now!
