### ISSUE TITLE
Install dev_mode changes in system

### ISSUE THREAD

**Issue by HelderGualberto** [jupyterlab/jupyterlab#5016]
How can i install all my changes (including extensions and some customizations in a few core package) on system, like a prod mode?

PS. jupyterlab --dev-mode works, but I want to run it lake a prod mode, installed in the system and not using 'dev_mode' directory.

**Comment by blink1073** [comment]
Hi @HelderGualberto, please see the notes about `addsibling` [here](http://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#extension-authoring).

**Comment by HelderGualberto** [comment]
Hi @blink1073, we tried the addsibling but it didn't work as expected. When we start the application it still doesn't show the changes made on extensions, running without the flag --dev-mode.

We Solved the problem by installing all packages from 'packages' directory in JupyterLab repository.
The commando to install all packages on system is (executing from main repo dir):

jupyter labextension install packages/*-extension/.

I hope it helps!

**Comment by jasongrout** [comment]
> We Solved the problem by installing all packages from 'packages' directory in JupyterLab repository.
> The command to install all packages on system is (executing from main repo dir):

Be careful - that only works now because the package sources in the repo match up to the published packages. Once the repo changes significantly from the published packages, that probably won't work (i.e., in the repo, the -extension packages will depend on the other packages in the repo, but when you install that way, it will actually pull in the released packages).

**Comment by jasongrout** [comment]
Do you need this custom spin to be able to install new packages at runtime (i.e., does `jupyter labextension install` need to work after your initial build? Or is it a single jlab app that you are distributing that will not need to modified by the user?

**Comment by HelderGualberto** [comment]
I need to install the jLab in the system, and its supposed to do not be modified while installed in the system, just in development mode.

The achievement is to install all changes in the system, including new extensions and changes in current extensions. And using the command mentioned it worked for me.

Is there some better way to do that? something like jlpm build:system

**Comment by CandleSense** [comment]
HI， @HelderGualberto ， Have you solved this problem? I have the same problem...

**Comment by CandleSense** [comment]
I had copy `dev_mode/*`  to lab static path `share/jupyter/lab`   and run  `jupyter lab` , but when I open it, the following dialog box will appear
![image](https://user-images.githubusercontent.com/28781481/56952601-41bca480-6b6d-11e9-9a00-c310f49f2f40.png)

**Comment by HelderGualberto** [comment]
I install all the extensions one by one manually. like this (Example for packages theme and apputils)
jupyter labextension install packages/theme*-extension packages/apputils-extension

I suggest you to store all your local/custom extensions on the same root directory, and use some kind of iteration to install them all. 
An example is, storing your local extensions in a directory named "local-extension"

for path in $(ls | grep local-extension); do cd $path && npm install && npm run build && cd .. ; done

then install all the compiled sources
jupyter labextension install ***local-extension/**.

NOTE: All the local extensions directory names end with the regex 'local-extension'
