### ISSUE TITLE
Workflow to create a slide presentation?

### ISSUE THREAD

**Issue by temok-mx** [jupyterlab/jupyterlab#5018]
Dear All, 
What is the current workflow to create a slide presentation out of a **JupyterLab** notebook?

I understand that in the [classic] Jupyter Notebook the workflow is:
1. View → Cell Toolbar → Slideshow
2. Then each cell will have a menu to choose from Slide, Sub-slide, etc., ...
3. On the terminal: 
$ jupyter nbconvert foo.ipynb --to slides --post serve

Thanks,
Temok

**Comment by blink1073** [comment]
Hi @temok-mx!  The way to do this natively in JupyterLab is to:

1. Open a notebook
2. Select `Cell Tools` on the left side bar
3. Select the `Slide Type`
4. Activate another cell
5. Repeat 3 and 4
6. `$ jupyter nbconvert foo.ipynb --to slides --post serve`

**Comment by sandys** [comment]
hi guys,
we are trying to get schools in India to adopt jupyter to create presentations and assignments in math. 
The slides feature is a killer usecase - it would be great if you guys can create a video to explain this.

**Comment by fm75** [comment]
I think the existing workflow documented by @blink1073 should be considered a **bug**. The workflow in classic notebooks described by @temok-mx is much simpler to use. I was about to create a bug report on this issue. The classic notebook sets up each cell for quickly labeling the slide type. This behavior should carry over to the **JupyterLab** experience even if it has to appear on the left side of the cell instead of conveniently at the top.

I would be happy, separately, to create a new issue as a bug if that would be preferred.

**Comment by blink1073** [comment]
@fm75, the above workflow is simplified with the https://github.com/jupyterlab/jupyterlab-celltags extension.

**Comment by fm75** [comment]
Perhaps it is simplified. But it is much simpler in the classic notebook, IMO, to just click a dropdown and select slide type than in the jupyterlab version to click in a "left area", then move the mouse left to click on a slide type dropdown.

Maybe it needs some UX investigation. But for me, with a choice still, I would revert back to `/tree` if/when I want to create a slideshow.

**Comment by enricorotundo** [comment]
> Hi @temok-mx! The way to do this natively in JupyterLab is to:
> ...
> 6. `$ jupyter nbconvert foo.ipynb --to slides --post serve`

Would be quite nice to have a `Export Slides` button somewhere in the UI.

**Comment by jasongrout** [comment]
> To be more clear, even after selecting `-` as a Slide Type, the **Edit Metada** field is still cluttered with a `slideshow` property.

FYI, this is fixed in JupyterLab 1.0a3.

**Comment by jasongrout** [comment]
> Would be quite nice to have a `Export Slides` button somewhere in the UI.

In the File menu, the "Export Notebook as" submenu has a slides option. Is that what you are looking for?
<img width="645" alt="Screen Shot 2019-04-23 at 5 07 48 AM" src="https://user-images.githubusercontent.com/192614/56579745-7609f100-65c0-11e9-8c7c-610c5d6f4b5f.png">

**Comment by enricorotundo** [comment]
> > Would be quite nice to have a `Export Slides` button somewhere in the UI.
> 
> In the File menu, the "Export Notebook as" submenu has a slides option. Is that what you are looking for?
> <img alt="Screen Shot 2019-04-23 at 5 07 48 AM" width="645" src="https://user-images.githubusercontent.com/192614/56579745-7609f100-65c0-11e9-8c7c-610c5d6f4b5f.png">

Exactly 🚀🤠🍻. 

I did a quick search in https://jupyterlab.readthedocs.io, couldn't find anything about this. If it's really not there I'd be glad to add it if you point me to the most appropriate section. Otherwise, I guess this issue also serves as a user guide, to some extent 😀

**Comment by duarteocarmo** [comment]
This should be better documented I think. Browsed for documentation on this for a long time..

**Comment by jasongrout** [comment]
Would you consider submitting a PR to add a paragraph to the place in the documentation where you would find it most naturally? The documentation source is at https://github.com/jupyterlab/jupyterlab/tree/master/docs/source

**Comment by duarteocarmo** [comment]
Hey @jasongrout , sure thing. Will do that this week!

**Comment by jasongrout** [comment]
Great, thanks! We appreciate you using your experience to make the world better for others!

https://www.poetryfoundation.org/poems/52702/the-bridge-builder

**Comment by fm75** [comment]
FWIW, [here is an example RISE-Demo](https://github.com/fm75/RISE-Demo/blob/master/README.md) with `binder badges` for both notebook and lab. Saving as a `reveal.js` html file loses the interactivity that notebook has. The notebook has a "play" icon in the toolbar. That allows one to execute code or even change the presentation during the presentation.

Perhaps this can be fixed by invoking a lab extension. If so, a PR for the demo would be appreciated.

**Comment by duarteocarmo** [comment]
@jasongrout and @blink1073  created a documentation section with a subsection that addresses this.

**Comment by fm75** [comment]
I am doing a short talk at a python meetup Monday 6-10. I would like to be able to describe how to use RISE in jupyterlab. I can see how to create it, but at the moment I can only **run** the slide show (interactively) in notebook. See the link in my previous comment.

**Comment by blink1073** [comment]
Right, RISE has not yet been been fully ported: https://github.com/damianavila/RISE/issues/270

**Comment by jasongrout** [comment]
Moving to 1.1 since we moved the PR to 1.1. However, if it is merged before 1.0, we'll set it back.
