### ISSUE TITLE
Any way to stop rendering of matplotlib (without restarting the kernel)

### ISSUE THREAD

**Issue by arogozhnikov** [jupyterlab/jupyterlab#5020]
Sometimes I'm just leaving too large matrix to plot and it takes minutes to render it. (plt.plot is not called, so this happens after executing the code). Something like:
```python
plt.imshow(numpy.random.randn(50000, 50000))
```

Is there a way to interrupt rendering?

**Comment by blink1073** [comment]
Hi @arogozhnikov, it looks like that function is not interrupt-able (doesn't respond to a SIGINT).  I also tried in an `ipython` prompt, pressing Ctrl+C, and it had no effect.
