### ISSUE TITLE
Audit Ctrl/Accel for keyboard shortcuts

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#5023]
The default shortcuts schema file has about 10 shortcuts that use `Ctrl` rather than `Accel`. Some may be deliberate, but I think many are not. We should go through and determine which ones should be changed to `Accel`.

**Comment by ian-r-rose** [comment]
cc @NoahStapp @jennalandy

**Comment by saulshanabrook** [comment]
Notes from meeting:

Ctrl maps to command on a mac more naturally. So we should switch the shortcut so that it is more natural on a mac.

**Comment by ian-r-rose** [comment]
Here are the shortcuts that use `Ctrl`, as well as a proposal for how to handle them:

|  Command  | Old |  New  | Reason | 
|---|---|---|---|
|  `application:activate-next-tab` | `Ctrl Shift ]`  | Unchanged   |  Avoid collision with browser shortcuts on Mac+Chrome (#1681) |
|  `application:activate-previous-tab` |  `Ctrl Shift [` |  Unchanged | Avoid collision with browser shortcuts on Mac+Chrome (#1681)  |
|   `editmenu:redo` | `Ctrl Shift Z`   | `Accel Shift Z`   | Better for Mac users   |
|   `editmenu:undo` | `Ctrl  Z`   | `Accel  Z`   | Better for Mac users   |
|   `filemenu:close-and-cleanup` | `Ctrl Shift Q`   | `Accel  Shift Q`   | Better for Mac users ? |
| `helpmenu:toggle` | `Ctrl Shit H` | Removed | Unused shortcut
| `console:linebreak` | `Ctrl Enter` | `Accel Enter` | Better for mac users, notebook uses `Ctrl Enter` to do something different |
| `notebook:enter-command-mode` | `Ctrl M` (??) | Unchanged | Feature parity with classic |
| `notebook:run-cell` | `Ctrl Enter` | Unchanged | Feature parity with classic |
| `notebook:split-cell-at-cursor` | `Ctrl Shift -` | Unchanged | Feature parity with classic |

If somebody with a Mac is able to test whether `Cmd Shift [/]` for activating next/previous tab conflicts with them (as suggested in #1681), I'd appreciate knowing about it.

**Comment by jasongrout** [comment]
On my mac, `Cmd Shift [` and `Cmd Shift ]` switch firefox tabs.

**Comment by ian-r-rose** [comment]
@jasongrout So that would mean that keeping our shortcut unchanged is probably a good idea. Do you know if those shortcuts are overridable?

**Comment by jasongrout** [comment]
> `filemenu:close-and-cleanup` 	`Ctrl Shift Q` 	`Accel Shift Q` 	Better for Mac users ?

On a mac/firefox, `Cmd W` closes the tab, `Shift Cmd W` closes the window, and `Cmd Q` closes the application. `Accel Shift Q` seems open, though it probably is more in line with closing all of JupyterLab than closing a single tab. But I'm not sure there is a better choice.

By the way, filemenu:close-and-cleanup is disabled in the launcher tab, so if you're just used to using one shortcut, it messes you up. You can use Ctrl W (JLab close tab) to close the tab.

**Comment by jasongrout** [comment]
> Do you know if those shortcuts are overridable?

I tried, and it doesn't seem I can override them in firefox.

**Comment by ian-r-rose** [comment]
> On a mac/firefox, `Cmd W` closes the tab, `Shift Cmd W` closes the window, and `Cmd Q` closes the application. `Accel Shift Q` seems open, though it probably is more in line with closing all of JupyterLab than closing a single tab. But I'm not sure there is a better choice.

Sounds good. I'd prefer to keep the churn here on the minimal side, since keyboard shortcuts can be pretty ingrained.

> By the way, filemenu:close-and-cleanup is disabled in the launcher tab, so if you're just used to using one shortcut, it messes you up. You can use Ctrl W (JLab close tab) to close the tab.

Interesting, I suppose we could have the `close-and-cleanup` delegator itself call `close` if there is nothing that has registered itself for close-and-cleanup.

> > Do you know if those shortcuts are overridable?
> 
> I tried, and it doesn't seem I can override them in firefox.

Okay, let's keep those as is, then. Thanks for checking.

**Comment by jasongrout** [comment]
+1 to everything else in your list.

**Comment by ian-r-rose** [comment]
@jasongrout is there anything you disagree with?

**Comment by jasongrout** [comment]
Nope, all looks good to me. I verified some of your statements about how things work in classic notebook on mac as well.

The only note I have at this point is about the filemenu:close-and-cleanup command not working for things like launchers.

**Comment by ian-r-rose** [comment]
I'll see if I can come up with something clever for that case.

**Comment by ian-r-rose** [comment]
@jasongrout #6447 is ready, with some cleanup of `close-and-cleanup`.
