### ISSUE TITLE
ModuleNotFoundError: No module named 'torchtext'

### ISSUE THREAD

**Issue by trtm** [jupyterlab/jupyterlab#5025]
Hello 👋

this is a cross post/issue from [torchtext](https://github.com/pytorch/text/issues/360).

I narrowed it down to being caused by Jupyter (Notebook & Lab), since importing the same library form the terminal within the Python prompt works (in the same env).

The message bellow is the same as posted in the torchtext issues section.

---

I get the following error message, when I want to `import torchtext`:

> ----> 1 import torchtext
> 
> ModuleNotFoundError: No module named 'torchtext'

The issue is the same as already asked on [Stackoverflow](https://stackoverflow.com/questions/51452412/cant-import-torchtext-module-in-jupyter-notebook-while-using-pytorch) by another torchtext user! 

I run `torch==0.4.0` with `python==3.6.5`.

This error occurs while importing the library from within Jupyter (Notebook & Lab), with `jupyter==1.0.0` and `jupyterlab==0.33.4`.

I tried the following options and got the same error message:
1.  with [Anaconda3](https://anaconda.org/) and this command `conda install -c derickl torchtext`
2. with my own Python3 [virtualenv](https://virtualenv.pypa.io/en/stable/) and several options like `pip install https://github.com/pytorch/text/archive/master.zip` for resulting torchtext version **0.3.0**, with `pip install torchtext` for torchtext version **0.2.3** and all other versions up until **0.2.1**.

After each run I completely reset the env I worked in, so there I exclude this as an possible error.

Can someone replicate this issue?
How should I proceed?
Is this maybe caused by Jupyter itself?

All the best! ✌️

**Comment by blink1073** [comment]
Hi @trtm, it sounds like you have two different Python environments.  From within a notebook, can you please try `!which python` and compare that to `which python` in a terminal?  (If you are on Windows, use `!where python`).

**Comment by trtm** [comment]
Thank you for the reply @blink1073 !

Yes, I tried that also and in both cases (from Terminal as well as from within the Jupyter-Lab) it is the same Python version `/home/trtm/torch_dev/bin/python`

**Comment by trtm** [comment]
If I do `pip freeze` I can see that torchtext and jupyterlab is installed in the same env, but still get the error as initially stated.

**Comment by jasongrout** [comment]
Try this in both your working ipython and your jupyter notebook/lab session that doesn't work:

```
import sys
print(sys.prefix)
```
Do they give exactly the same values?

**Comment by jasongrout** [comment]
(and `sys.path` as well to be extra sure...)

**Comment by trtm** [comment]
Thank you @jasongrout !

This is different: In ipython I get `/home/trtm/torch_dev` while in the jupyterlab `/usr`

What should I do to make them equal?

**Comment by blink1073** [comment]
What does ``cat `which jupyter-lab` `` show?

**Comment by trtm** [comment]
In the terminal as well as from within the Jupyter-Lab I get the following:

```
#!/home/trtm/torch_dev/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from jupyterlab.labapp import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

How and what should I change?
Is should be `sys.prefix` and/or `sys.path`, right?

**Comment by blink1073** [comment]
And if you explicitly run `jupyter-lab` are you able to make the import?

**Comment by trtm** [comment]
Thank you @blink1073, your help is highly appreciated.

What do you mean by **explicitly** running?

In the terminal within my dev env, I tested the command in the Python prompt and I run them after starting `jupyter-lab --port=8899 --no-browser` in the browser.

Note:
I can import the other torch libraries, namely `torch` itself and `torchvision`.

```
!pip freeze | grep torch

torch==0.4.1
torchtext==0.3.0
torchvision==0.2.1
```

**Comment by blink1073** [comment]
I meant as opposed to `jupyter lab` (with a space), or some other way of launching like a graphical launcher.  One more check, how about if you run the same but with `jupyter-notebook`?

**Comment by blink1073** [comment]
Sorry for the wild goose chases, I'm not entirely sure what's going on here.  How about `python -c "import jupyterlab; print(jupyterlab.__path__)"` and `python -c "import torchtext; print(torchtext.__path__)"`

**Comment by trtm** [comment]
I think I finally got it!

I needed to adapt the `sys.path` (after checking @jasongrout recommendation) and to include my own `torch_dev` env, which is this one `/home/trtm/torch_dev/lib64/python3.6`

Thank you @blink1073, for your last recommendation I see the **jupyterlab** and **torchtext** libraries now in the same path under `/home/trtm/torch_dev/lib/python3.6/site-packages/`

This issue can be closed!
Highly appreciate the help from you!

**Comment by blink1073** [comment]
Cheers!

**Comment by GeoPapang** [comment]
@trtm Sorry, but I am not quite sure how you solved it. Can you please tell what did you do it? Did you install the libraries before adding the path? How did you change the path?
