### ISSUE TITLE
500 error when opening notebook in JupyterLab copied to shared directory

### ISSUE THREAD

**Issue by bobmyhill** [jupyterlab/jupyterlab#5027]
Several of us working on the enki-portal JupyterLab have found the following problem:
- User copies a working notebook from a private directory to a shared directory
- The same user tries to open that notebook in the shared directory gets a `Invalid response: 500 Internal Server Error`
- Everyone else can open and edit the notebook without error.

**Comment by bobmyhill** [comment]
Maybe similar to Issue #4750

**Comment by ian-r-rose** [comment]
I wonder if this is a problem with the notebook [signature checking](http://jupyter-notebook.readthedocs.io/en/stable/security.html#the-details-of-trust) on your system. Depending on the user that is trying to open the file in the shared directory, the security codepath should be different. If there is a bug in the signature-check for the notebook author, then it might result in the error you are describing.

A couple of questions:
1. Does this also happen if you try to open the notebook with the classic notebook interface?
2. Is this shared directory using normal POSIX file permissions?
3. Do you have access to the server logs? If so, do they give any more detailed error messages?

(Also, hi Bob!)

**Comment by ian-r-rose** [comment]
If my suspicions are right (they might not be!), [this](http://jupyter-notebook.readthedocs.io/en/stable/security.html#collaboration) may also be a useful read.

**Comment by bobmyhill** [comment]
Hi Ian! Ok, I've asked the server admin, and will let you know what we find!

**Comment by jasongrout** [comment]
Closing since the author did not follow up.
