### ISSUE TITLE
New Console for Notebook 

### ISSUE THREAD

**Issue by benphua** [jupyterlab/jupyterlab#5028]
Hi There,

Sorry to disturb but I've been trying desperately to get the New Console for Notebook feature to work on my Mac, I've attempted to uninstall Python, Anaconda, etc.

But for some reason actions done in the notebook are not appearing on the console.

![screen shot 2018-08-02 at 6 31 53 pm](https://user-images.githubusercontent.com/23288841/43572240-5a051182-9682-11e8-8d97-8ef79b83422f.png)

**Comment by blink1073** [comment]
Hi @benphua, I believe you want to toggle `Show all other kernel activity`, cf https://github.com/jupyterlab/jupyterlab/pull/4503

**Comment by jasongrout** [comment]
See also the release notes for 0.34, which mentions this behavior change: https://github.com/jupyterlab/jupyterlab/blob/master/CHANGELOG.md

**Comment by benphua** [comment]
Thank you very much guys, I apologise for the hassle as a novice.
