### ISSUE TITLE
Release 0.33.5 wheel: multiple outdated `vendors~main` in the static directory

### ISSUE THREAD

**Issue by mprogram** [jupyterlab/jupyterlab#5036]
I've just unpacked the JLab 0.33.5 python wheel to investigate its sudden size increase, and found outdated (and heavy) files. inside the `static` directory

**Comment by blink1073** [comment]
Ah, good catch, thank you.  I will push a 0.33.6 with a clean `build` folder.

**Comment by blink1073** [comment]
Released and updated our `RELEASE.md` accordingly, thank!
