### ISSUE TITLE
Scrollbar is not drag-and-movable

### ISSUE THREAD

**Issue by mprogram** [jupyterlab/jupyterlab#5040]
I've upgraded to JLab 0.33.6 and noticed I cannot hold a scrollbar with a mouse click and move it up-down. It scrolls with the mouse wheel, however. You may close the issue if it's only pertains to my configuration.

**Comment by jasongrout** [comment]
Which scrollbar are you seeing this on?

**Comment by mprogram** [comment]
It was a typical vertical scrollbar in opened sized notebooks (*.ipynb), tested on the Chrome browser/Linux v69.0.3497.23. However, I'm going to close my issue since I've just upgraded the extensions/jupyter-notebook, and it no longer manifest itself, if it was, indeed, my issue  - in which case my apologies for making this particular noise.
