### ISSUE TITLE
Extension Manager doesn't recognise when an install failed

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#5042]
As it says in the title. In my particular case the install failed with `JavaScript heap out of memory` but in the UI there was no indication of failure and the blue bar kept moving across.

Not sure if that's the case with all install errors or just with the particular one I observed.

**Comment by jasongrout** [comment]
CC @vidartf

**Comment by vidartf** [comment]
I'll have a look at this tomorrow!

**Comment by vidartf** [comment]
Can you confirm that the install failure triggers an exception on the JS side? If so, a fix should be available in #5147. If not, I'd appreciate a stack trace from the python side if available!

**Comment by vidartf** [comment]
@dhirschfeld ^

**Comment by dhirschfeld** [comment]
@vidartf - the `JavaScript heap out of memory` was a JS exception.

I'm not sure what you mean by stack trace from the python side? JupyterLab extensions are npm/JS packages so where would a python exception be thrown?

**Comment by vidartf** [comment]
@dhirschfeld I meant on the browser side, sorry for the confusion. The error on the server side should have cause an exception to be thrown in the browser as well (which should now be handled).

**Comment by dhirschfeld** [comment]
There wasn't anything visible but I didn't check the console.

I haven't checked since but I'll assume it was fixed in #5147. If it does still happen I can always open a new issue for it and I'll make sure to capture more useful info next time!
