### ISSUE TITLE
Check if comm target already exists on client side

### ISSUE THREAD

**Issue by TK-21st** [jupyterlab/jupyterlab#5044]
## Problem 
As stated in title. Registered comm target then open comm in server. Connect `kernelchanged` signal to re-registration of comm and re-opening of comm in server, but gives error of object not found in registry.

### Suspected reason
Comm target already exists with the given name and cannot be re-registered on client side

### Question
How to check if comm target already exists on client side and either 1) remove and recreate it, or 2) do nothing and proceed with kernel comm opening.

## Scenario
A comm handling callback is registered on client side (in `.ts`) with target name of, say, `mycommtarget`. At the same time the kernel is asked to open a comm with this target `mycommtarget` as shown in the example https://github.com/jupyterlab/jupyterlab/tree/master/packages/services.

```typescript
registerComm(): Promise<void> {
      this.session.kernel.registerCommTarget("mycommtarget",(comm, commMsg)=>{
        if (commMsg.content.target_name !=="mycommtarget") {
          return;
        }
        comm.onMsg = (msg) => {
          //blahblah
        };
        comm.onClose = (msg) => {
          //blahblah
        };
      });
    }
    let code = [
      'from ipykernel.comm import Comm',
      '_newComm= Comm(target_name="mycommtarget")',
    ].join('\n');
    return this.session.kernel.requestExecute({ code: code });
  }

```

Since I want any new kernel generated by this extension to connect to this comm target, I connect `kernel.KernelChanged` signal to this comm registration routine
```
    this.session.kernelChanged.connect(this.registerComm, this);
```

But it gives me this error:
```
default.js:928 Exception opening new comm
(anonymous) @ default.js:928
rejected @ default.js:7
Promise.then (async)
step @ default.js:8
(anonymous) @ default.js:9
push.YC29.__awaiter @ default.js:5
_handleCommOpen @ default.js:913
(anonymous) @ default.js:1020
(anonymous) @ default.js:9
push.YC29.__awaiter @ default.js:5
_handleMessage @ default.js:977
_msgChain._msgChain.then @ default.js:124
Promise.then (async)
DefaultKernel._onWSMessage @ default.js:121
default.js:129 Error: Object 'mycommtarget' not found in registry
    at Promise (default.js:1476)
    at new Promise (<anonymous>)
    at Object.loadObject (default.js:1455)
    at DefaultKernel.<anonymous> (default.js:921)
    at Generator.next (<anonymous>)
    at default.js:9
    at new Promise (<anonymous>)
    at push.YC29.__awaiter (default.js:5)
    at DefaultKernel._handleCommOpen (default.js:913)
    at DefaultKernel.<anonymous> (default.js:1020)
_msgChain._msgChain.then.catch.error @ default.js:129
Promise.catch (async)
DefaultKernel._onWSMessage @ default.js:126
```

**Comment by TK-21st** [comment]
@blink1073 v0.33.6

**Comment by blink1073** [comment]
Do you have a repo you can point me to that uses the code above?

**Comment by jasongrout** [comment]
Closing as no response. Please comment below if you'd like to the continue the discussion. Thanks!
