### ISSUE TITLE
Could one move all of the launcher functions into the cell type dropdown?

### ISSUE THREAD

**Issue by thwee-alchemist** [jupyterlab/jupyterlab#5047]
Markdown, code, consoles in a cell, each. Maybe even jupyter notebooks and webbrowsers for completeness. Nice job, by the way.

**Comment by jasongrout** [comment]
Thanks! Could you elaborate a bit more? Perhaps even if possible post a screenshot explaining what you mean?

**Comment by thwee-alchemist** [comment]
I hope this explains what I mean. I'll update this with a cell example if needed.

**Comment by jasongrout** [comment]
Ah, I see. You are suggesting us having a dropdown to select what thing to launch. Let's move this conversation over to https://github.com/jupyterlab/jupyterlab/issues/3795, where we've been discussing better UIs for the Launcher. Would you read through those comments and post your own thoughts there?

**Comment by jasongrout** [comment]
Did I understand you correctly?

**Comment by thwee-alchemist** [comment]
Almost. You know how right now you have the launcher for creating notebooks and repls? I'm suggesting that you move this functionality into a notebook's cells, like org-mode in emacs. Instead of having the kernel as a notebook property, maybe it could be a cell property. That would result in the modified dropdown I suggested.
