### ISSUE TITLE
Make `Open File` an option under the File menu

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#5050]
To me it's a fundamental option which I would always expect to find under the File menu.

It can be found in the Command Palette as `Open from Path`. I'd recommend that to be renamed to simply `Open File` as that's what it's commonly called. Also the dialog it brings up is called Open File:
![image](https://user-images.githubusercontent.com/881019/43682656-a5839d70-98be-11e8-9340-100c1d0e74af.png)

**Comment by jasongrout** [comment]
That makes sense to me: +1. Since it brings up a dialog box, it should also have an ellipsis after it: `Open File...`

**Comment by jasongrout** [comment]
I tagged this as a good first issue. The command name is at https://github.com/jupyterlab/jupyterlab/blob/44f33c68fcc8e37f722fb8d86c7d1f027b0643c8/packages/docmanager-extension/src/index.ts#L378-L379

The file menu is created here: https://github.com/jupyterlab/jupyterlab/blob/f87028deb9c9fee0591f95ddc81a5ed1fea2ab45/packages/mainmenu-extension/src/index.ts#L197
