### ISSUE TITLE
Cannot upload .ipynb file > 15 MB with JupyterLab 0.33.6 whereas it works with Jupyter 5.6.0

### ISSUE THREAD

**Issue by MichaelVasseurBE** [jupyterlab/jupyterlab#5059]
Dear Team,

Our users warned us on a limitation related to .ipynb file uploads : they can't upload .ipynb files larger than 15 MB.

![screenshot from 2018-08-06 17-30-27](https://user-images.githubusercontent.com/25905977/43726185-babeaf14-999e-11e8-87e4-bedd0d8d54df.png)

We did some tests on our side and we discovered that : 
- JupyterLab **0.33.6** supports upload of files (not .ipynb) > **15 MB**
- Jupyter **5.6.0** supports upload of all files (including .ipynb) > **15 MB**

It seems that the limitation is caused by the code below : 
https://github.com/jupyterlab/jupyterlab/blob/f87028deb9c9fee0591f95ddc81a5ed1fea2ab45/packages/filebrowser/src/model.ts#L380

Can you help sorting out this issue ?

Best Regards,
Mike

**Comment by jasongrout** [comment]
It looks like there is a specific test in the code that excludes notebooks: https://github.com/jupyterlab/jupyterlab/blob/453497701df537e858e255b6dca3e786c781d126/packages/filebrowser/src/model.ts#L378

@saulshanabrook - do you know why there is a specific code disallowing large notebooks?

**Comment by saulshanabrook** [comment]
@jasongrout the notebook server doesn't support large file uploads with notebooks: https://github.com/jupyter/notebook/pull/2162/files#diff-35286fb845f23a207fa846d99bb6a937R61

**Comment by saulshanabrook** [comment]
We upload notebooks as `notebook` types and files as `file` types: https://github.com/jupyterlab/jupyterlab/blob/453497701df537e858e255b6dca3e786c781d126/packages/filebrowser/src/model.ts#L429-L442. I am not sure why we don't upload notebooks the same as other files. I preserved this behavior when adding large file upload.

**Comment by saulshanabrook** [comment]
I am going to look at the notebook code to see how they support this.

**Comment by blink1073** [comment]
I see no reason to make a distinction, other than the fact that we currently have a performance problem with large notebooks.

**Comment by MichaelVasseurBE** [comment]
Any update ? Do you have any time frame for the resolution ?

**Comment by saulshanabrook** [comment]
I'll have a look at this by monday, to try switching notebooks to be uploaded as regular files.

**Comment by MichaelVasseurBE** [comment]
Great ! :+1:

**Comment by MichaelVasseurBE** [comment]
Any update ? This is a blocking issue.

**Comment by saulshanabrook** [comment]
I will take a look at this soon, I was busy.

**Comment by saulshanabrook** [comment]
@MichaelVasseurBE Feel free to test https://github.com/jupyterlab/jupyterlab/pull/5135, which works for me to fix this.
