### ISSUE TITLE
Link compiled webpack code back to typescript sources

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#506]
From #455:

> AFAIK there is a way to link it again back to the original TypeScript source, we just have not done it yet.

**Comment by vidartf** [comment]
Is this relevant? https://www.typescriptlang.org/docs/handbook/react-&-webpack.html

**Comment by blink1073** [comment]
Yep, that looks promising.

**Comment by vidartf** [comment]
I got it set up nicely on a different project using that guide, except I had to use an alternate TS loader since this issue of `ts-loader` on windows: TypeStrong/ts-loader#185 .

**Comment by saulshanabrook** [comment]
I'm gonna start working on this one.
