### ISSUE TITLE
ipywidgets Button widget not printing text

### ISSUE THREAD

**Issue by scottdotjs** [jupyterlab/jupyterlab#5063]
When the following code is run in JupyterLab 0.32.1 with ipywidgets 7.3.1 and @jupyter-widgets/jupyterlab-manager 0.36.1, nothing happens when the button is clicked. The word "Test" should be printed. It works in the classic Notebook.

```python
from IPython.display import display
from ipywidgets import widgets
    
def test(b):
    print('Test')

button = widgets.Button(description='Test')
button.on_click(test)
    
display(button)
```

**Comment by blink1073** [comment]
Hi @scottdotjs, I believe you have to use an (OutputWidget)[http://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html].  Jupyter Notebook had a hack that allowed output to be displayed from a widget directly.  cc @jasongrout, the [Widget Events](http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Events.html) tutorial should be updated to use an output widget.

**Comment by scottdotjs** [comment]
@blink1073 Perfect! Thanks very much.

**Comment by jasongrout** [comment]
See https://github.com/jupyter-widgets/ipywidgets/issues/2148 for an example.
