### ISSUE TITLE
Make change of syntax highlighting scheme global and permanent

### ISSUE THREAD

**Issue by remi-nd** [jupyterlab/jupyterlab#5064]
*.m file is treated as Mathematica file by default in editor. I'd like to change the syntax highlight scheme of a mfile to Matlab (Octave) by setting via View menu option, which is however not applied to other mfiles. Is there any option available to fix this?

**Comment by jasongrout** [comment]
Great question. I think the recognized file types are not exposed currently to the user.

Perhaps we should have a new settings section for file types, with the registered file types as the system defaults, which would allow user overrides.

**Comment by saulshanabrook** [comment]
I think this is the same as https://github.com/jupyterlab/jupyterlab/issues/4223
