### ISSUE TITLE
Kernel restart after closed notebook shutdown

### ISSUE THREAD

**Issue by AlbertWigmore** [jupyterlab/jupyterlab#5065]
If you close a notebook tab then go to 'Running' and click shutdown. This causes the notebook to be opened just after the kernel is shutdown and the kernel then restarts. Same issue also occurs with the terminal as well.

Tested on 0.33 on both Chrome 67.0 and Firefox 60.0.1.

Issues appears to be caused by stacked onClick handlers in *packages/running/src/index.tsx*.

```js
function Item<M>(props: SessionProps<M> & { model: M }) {
  const { model } = props;
  return (
    <li className={ITEM_CLASS} onClick={() => props.openRequested.emit(model)}>
      <span className={`${ITEM_ICON_CLASS} ${props.iconClass(model)}`} />
      <span
        className={ITEM_LABEL_CLASS}
        title={props.labelTitle ? props.labelTitle(model) : ''}
      >
        {props.label(model)}
      </span>
      <button
        className={`${SHUTDOWN_BUTTON_CLASS} jp-mod-styled`}
        onClick={() => props.shutdown(model)}
      >
        SHUTDOWN
      </button>
    </li>
  );
}
```

**Comment by jasongrout** [comment]
Good catch, thanks!

**Comment by jasongrout** [comment]
Is it as easy as moving the li onClick down to the span elements?

**Comment by jasongrout** [comment]
Or even better, perhaps the shutdown onClick should be something like: `(e) => {props.shutdown(model); e.stopPropagation();}`

**Comment by AlbertWigmore** [comment]
Hi @jasongrout 
So both solutions would work in this case.

I think it makes more sense from a UI point of view to move the onClick to the span element containing the title. The item shows a grey area when hovered so it makes sense that it should be clickable.

Going to submit a PR shortly with the fix.
