### ISSUE TITLE
Changing-tab while in terminal adds completion

### ISSUE THREAD

**Issue by mocquin** [jupyterlab/jupyterlab#5076]
When in a terminal in jlab, and I hit (CTRL+TAB) to change web-browser tab, it adds a completion to the terminal because of the tab - although I'm hitting and holding CTRL before TAB.

For exemple, it creates a "Display all XXX possibilities? (y or n)" invite.

Hope it's clear.
(Jlab 0.32.1, Firefox 60.0.2)

**Comment by liffiton** [comment]
FWIW, this issue does not occur for me in Jupyterlab 0.33.4, Firefox 61.0.1 64-bit Windows.

**Comment by Liberus** [comment]
same, not reproduciable on my side, jlab 0.33.11, Chrome, 64-bit Windows

**Comment by saulshanabrook** [comment]
Closing this since we could not be reproduced
