### ISSUE TITLE
Local Environment Console?

### ISSUE THREAD

**Issue by chartsengrafs** [jupyterlab/jupyterlab#5093]
Is it possible to purpose one of the console screens to view metadata regarding all local variables/functions/tables created in a given kernel session? It is really helpful for memory management, among other things. I am thinking of how Rodeo or RStudio does this.

**Comment by jasongrout** [comment]
Let's move this discussion over to #443 (please see https://github.com/jupyterlab/jupyterlab/issues/443#issuecomment-403362416 particularly). Would you add your comments over there?
