### ISSUE TITLE
Text editor should have toolbar for per-editor settings, like line wrap, syntax highlighting, etc.

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#511]
I think the editor should have per-editor indicators for things like line wrap, highlighting, maybe theme?, etc. Basically the stuff in the existing Editor menu that apply on a per-editor basis. This will give important visual indication of the appropriate settings in an individual editor, and provide an easy visual way to see what the current setting is.

**Comment by ellisonbg** [comment]
Yes, I think we want to have a toolbar for the editor that provides these things.

**Comment by ellisonbg** [comment]
We are looking at what file editor settings other text editors allow to be set on a per file basis. We find the following:

* Tab/spaces
* Line wrapping
* Line numbers
* VIM Mode
* Match brackets

I think we should keep the theme global across all editors...

**Comment by ellisonbg** [comment]
We are thinking of implementing these for now using a file editor toolbar, but later in a global status bar similar to VS Code.

**Comment by yuvipanda** [comment]
Any progress on this? I can't seem to set the syntax highlighting language for files either, so things like bash scripts and Dockerfiles don't get any syntax highlighting at all...

**Comment by blink1073** [comment]
No progress yet.  Agreed that syntax highlighting for the editor is needed.

**Comment by ellisonbg** [comment]
Closing in favor of unified #2382
