### ISSUE TITLE
Add pipe delimiter for table view of CSV

### ISSUE THREAD

**Issue by citizenrich** [jupyterlab/jupyterlab#5112]
The current delimiters supported in the dropdown for table view of CSV are commas, semicolons, and tab. Is there interest in supporting pipe (|) delimitation?

**Comment by blink1073** [comment]
Hi @citizenrich, good suggestion!  I'm going to mark this as a good first issue:

https://github.com/jupyterlab/jupyterlab/blob/1aff4190084fd5993d3f7e3ae10b467264df1cd0/packages/csvviewer/src/toolbar.ts#L17

https://github.com/jupyterlab/jupyterlab/blob/1aff4190084fd5993d3f7e3ae10b467264df1cd0/packages/csvviewer/src/toolbar.ts#L22
