### ISSUE TITLE
Have a single status area at the bottom for per-activity settings

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#512]
Having a toolbar per editor (like suggested in #511) seems like an unfortunate waste of space, so perhaps in the future we can have a single status display at the bottom that changes every time a new activity is focused. This would be similar to common conventions for text editors.

**Comment by jasongrout** [comment]
Here's an example from Visual Studio Code showing how they have extensions updating the status bar: https://code.visualstudio.com/docs/extensions/example-word-count

**Comment by jasongrout** [comment]
One disadvantage of having a status bar at the bottom is that it is visually disconnected from an editor window if there is a horizontal splitter and the editor window is in the top half. VS Code windows (almost always) extend to the bottom, so there is a visual connection between document and status bar.

Sublime still has a status bar, but can split things so the document doesn't sit flush with the status bar, so I'm not sure how much that would be an issue in practice.

**Comment by jasongrout** [comment]
Search https://www.sublimetext.com/docs/3/api_reference.html for "status" to see the api Sublime provides for updating a status bar.

**Comment by jasongrout** [comment]
I think this is the atom status bar: https://github.com/atom/status-bar

**Comment by jasongrout** [comment]
Emacs mode lines don't seem to be as customizable: https://www.gnu.org/software/emacs/manual/html_node/emacs/Mode-Line.html

**Comment by jasongrout** [comment]
Customizing vim's status line: http://stackoverflow.com/questions/5375240/a-more-useful-statusline-in-vim

**Comment by jasongrout** [comment]
Let's take line wrapping as an example:

VS Code has a menu item to toggle line wrapping in the current editing buffer. Status is not displayed, and you can't do it in the status bar. It seems that in general, the toggling options are in menus, whereas commands with arguments (like changing the indentation settings) are status bar items that invoke commands when clicked. The commands then walk you through the command arguments in successive command palettes.

Sublime also has a menu item to toggle line wrapping in the current buffer, but also has a checkmark next to the menu item to indicate the setting for the current buffer (which changes if you focus a different buffer). The status bar items in sublime (like changing indentation settings) pop up an in-place menu allowing you to select various options for that setting.

Atom, like VSCode, offers a per-buffer toggle line wrap menu option that does not display the current status. Status bar items (like syntax mode) can be clicked and pull up the command palette dialog with options. Setting the indent size is considerably more complicated: http://stackoverflow.com/questions/22608160/atom-change-indentation-mode

**Comment by dhirschfeld** [comment]
It would be useful to have a status bar - in particular I'd really like to have a column number indicator for the current cursor.

**Comment by dhirschfeld** [comment]
Ha! I was just looking for an issue where I could request a column number indicator...

**Comment by ian-r-rose** [comment]
:laughing: Slowly but surely, we will get there.

**Comment by jasongrout** [comment]
Closing this, as work on this is in the https://github.com/jupyterlab/jupyterlab-statusbar repo.
