### ISSUE TITLE
Jupyter Lab starts wrong kernel

### ISSUE THREAD

**Issue by gonglinyuan** [jupyterlab/jupyterlab#5120]
I installed jupyter lab from anaconda and created an environment called "deep_learning". I added the bin path of this environment to the environment variable "PATH". But Jupyter lab starts the wrong kernel for a python3 notebook / terminal. The output of 'sys.path' is:
`['',
 '/home/dihe/anaconda3/lib/python36.zip',
 '/home/dihe/anaconda3/lib/python3.6',
 '/home/dihe/anaconda3/lib/python3.6/lib-dynload',
 '/home/dihe/anaconda3/lib/python3.6/site-packages',
 '/home/dihe/fairseq',
 '/home/dihe/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg',
 '/home/dihe/anaconda3/lib/python3.6/site-packages/IPython/extensions',
 '/home/dihe/.ipython']`

However, when I am using jupyter notebook, it starts the correct kernel as expected. The output of sys.path is:

`['',
 '/home/dihe/anaconda3/envs/deep_learning/lib/python36.zip',
 '/home/dihe/anaconda3/envs/deep_learning/lib/python3.6',
 '/home/dihe/anaconda3/envs/deep_learning/lib/python3.6/lib-dynload',
 '/home/dihe/anaconda3/envs/deep_learning/lib/python3.6/site-packages',
 '/home/dihe/anaconda3/envs/deep_learning/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg',
 '/home/dihe/anaconda3/envs/deep_learning/lib/python3.6/site-packages/IPython/extensions',
 '/home/dihe/.ipython']`

This is the output of jupyter troubleshoot:

[a.txt](https://github.com/jupyterlab/jupyterlab/files/2282675/a.txt)

**Comment by blink1073** [comment]
Hi @gonglinyuan, what are `which jupyter-lab` and `which jupyter-notebook`?

**Comment by gonglinyuan** [comment]
@blink1073 
`dihe@msraml-tesla03:~$ which jupyter-lab
/home/dihe/anaconda3/bin/jupyter-lab
dihe@msraml-tesla03:~$ which jupyter-notebook
/home/dihe/anaconda3/envs/deep_learning/bin/jupyter-notebook
`
Yes, this is the problem. Thank you!
Why does this happen? I have executed "conda install -n deep_learning jupyter" to install jupyter. What is the correct way to install jupyter-lab ?

**Comment by gonglinyuan** [comment]
I am sorry. I made a mistake. I installed jupyter-lab again with "conda install -c conda-forge jupyterlab" and now it works. Thanks @blink1073

**Comment by blink1073** [comment]
👍

**Comment by jandot** [comment]
Thank you! That got it working for me as well.
