### ISSUE TITLE
Markdown problem

### ISSUE THREAD

**Issue by ShuvenduBikash** [jupyterlab/jupyterlab#5124]
Breaks the mathematical formula on documentation view which pops up with `shift+tab`

**Comment by ian-r-rose** [comment]
Can you provide an example of a function docstring that renders incorrectly?

**Comment by ShuvenduBikash** [comment]
torch.nn.LSTM() or GRU()

**Comment by ian-r-rose** [comment]
It looks to me like those docstrings are written in rST (as are many python docstrings). We currently don't have any way of rendering that format on the frontend. If I open the same documentation with `Shift Tab` in classic notebook, it also doesn't render the math. Is there some context other than the HTML produced by sphinx where you see the rendered LaTeX?

**Comment by ShuvenduBikash** [comment]
Well, it renders with spyder in the help section. And in pycharm editor, it works well in a popup
