### ISSUE TITLE
Difficulty with laying out interactive widgets horizontally

### ISSUE THREAD

**Issue by scottdotjs** [jupyterlab/jupyterlab#5134]
I've been struggling to build a simple horizontal layout using `interactive` widgets, presumably because they're a subclass of `VBox`. Here's an example of what I mean:

```python
test_style = { 'description_width' : '25%' }
test_layout = Layout( width = '50%' )

def nothing(x): pass

text1 = widgets.Text(
    description = 'text1',
    value = 'using widgets.Text()',
    layout = test_layout,
    style = test_style
)

text2 = interactive(
    nothing,
    x = widgets.Text(
        description = 'text2',
        value = 'using widgets.interactive()',
        layout = test_layout,
        style = test_style
    )
)

test_button = widgets.Button(description='button')

box1 = box(children = [text1, test_button])
box2 = box(children = [text2, test_button])
display(box1)
display(box2)

```
![image](https://user-images.githubusercontent.com/32358661/44145087-12320cd4-a082-11e8-9fa6-021007c51e99.png)

I made some attempts to modify `box2.children[0].layout` and `box2.children[0].style` but wasn't able to make that work.

Is there a way that I can retain the convenience of `interactive()` and build a layout this way, or will I need to manually create a widget and observer? Please forgive any lack of clarity in this issue, I'm relatively new to Python.

**Comment by blink1073** [comment]
Hi @scottdotjs, do you mind posting this to https://github.com/jupyter-widgets/ipywidgets?

**Comment by jasongrout** [comment]
Closing, since this is really an ipywidgets issue and should be posted there. @scottdotjs - feel free to post in the ipywidgets repo.
