### ISSUE TITLE
Cannot move cell to end of notebook

### ISSUE THREAD

**Issue by elcombato** [jupyterlab/jupyterlab#5136]
It is impossible to move a cell per drag and drop to the last position of a notebook. You can only move it to the second last position and move the last cell one up.

**Comment by ian-r-rose** [comment]
Hi @elcombato, I can drag a cell to the end of a notebook without issue. What version of JupyterLab are you using, and can you perhaps attach a video showing what you are describing?
![drag-to-end](https://user-images.githubusercontent.com/5728311/44152552-b12af8a0-a05a-11e8-9ad1-5817a559838a.gif)
