### ISSUE TITLE
DOM ids shouldn't start with digits e.g. 62.5% of uuids

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab#5139]
Just ran into a problem that only surfaced 10/16th of the time, which is a really infuriating ratio... works enough to know you're not crazy, not enough to give up.

So `jp-NotebookPanel` `id`s used to basically always be of the form `notebook-123`, but as of 0.33 (with MainAreaWidget), they always already have an id, and it's a `uuid`. Turns out, the browsers don't like selecting them, as is... which sorta makes sense, given that they end up being in all kinds of places (css, js, etc). 

It had been some time since I ran into this, and ran up on [this writeup](http://code.fitness/post/2016/04/bad-idea-guid-as-html5-id.html) which sums it up.

Anyhow, I did the poor fix of `.jp-NotebookPanel[id='${id}']` for my selector, and it works, but it seems like deciding on a prefix for the [various spots](https://github.com/jupyterlab/jupyterlab/search?q=id+uuid+widget&unscoped_q=id+uuid+widget) where these are used as `id`s would be helpful, such as `id-${guid}`.

**Comment by jasongrout** [comment]
Good catch!

Bumping to 1.0 as a small but important fix.

**Comment by afshin** [comment]
Hint: search the source for the `UUID` import and audit all instances of uuid use.
