### ISSUE TITLE
Settings system

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#515]
Implement a system where settings for each plugin can be saved and restored. Problems to solve:
- Where to store the settings
- An api for plugins to require to save or read settings

Likely the document manager will expose it's own settings api for default settings for specific document types, built on top of this application settings infrastructure. Document type default settings could include editor options like line numbers, indentation, line wrapping, etc.

**Comment by ellisonbg** [comment]
1. I think we should have a pretty generic TS interface.
2. The default implementation can use our frontend config

**Comment by sccolbert** [comment]
I think this should be a union-esque settings system similar to Sublime, where settings files/configs can be layered on top one another according to defaults/system/user/filetype/plugin etc...

**Comment by ellisonbg** [comment]
This is done in master. We can refine it, but the foundation is in place.
