### ISSUE TITLE
Revise semantics of text editor settings

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#516]
## Current scope of the issue

Added by @ellisonbg

The purpose of this issue is to track the semantics of how we manage editor settings. There are a couple of different design aspects to this:
- [ ] Some menu items should be inactive if there isn't an editor that is active or open.
- [ ] Some setting should only apply to a single (active) editor - those should be in a separate UI location, maybe a toolbar for the editor.
- [ ] Other settings should apply to all editors.
- [ ] Settings that apply to all editors should be applied to new editors that have not yet been opened.
## Original comment

Right now, they apply to the last focused editor. I think they should instead only work if an editor is actively focused to avoid confusion if the user has moved away from an editor for a while.

I think this has to wait until we move to the monorepo so we can have something where we can look up the active widget.

**Comment by charnpreetsingh185** [comment]
The other issue is that if you apply a theme, change keybindings, toggle line numbers, etc it only applies to that instance of the editor and not others.

**Comment by jasongrout** [comment]
I think it makes sense to toggle line numbers on only the current editor - this was a change I made today. I just checked and keybindings and themes apply across all editors.

**Comment by charnpreetsingh185** [comment]
Sorry, what I meant was applying themes/keybindings/etc.. across new instances of editors. The terminal plugin currently does this by saving and passing in an options JSON object into the constructor. Maybe the editor can get the same treatment?

**Comment by jasongrout** [comment]
Oh yeah, good idea. I think that's part of the functionality we'd like in #515.

**Comment by blink1073** [comment]
We now have a focus tracker, but it explicitly provides the most recently focused editor.  We could expose the `currentWidget` on the app shell as `currentMainWidget`, and then see if it is an editor.

**Comment by ellisonbg** [comment]
Soft targeting as beta now as I am about to open another issue related to this - that other issue may resolve some of these things.

**Comment by blink1073** [comment]
Moving this to 1.0, since we have a partial solution in #2134 and the rest depends on the settings system.

**Comment by ellisonbg** [comment]
We now have the settings system in place, and I am not sure how to think about which things are per editor and which things are global or per language. I am going to close this issue as it is a bit stale and we can open new ones as we find things with the new settings in place.
