### ISSUE TITLE
It is not possible to see the dropdown menu options of the cell when you use the "dark mode"

### ISSUE THREAD

**Issue by xicopetry** [jupyterlab/jupyterlab#5168]
Hi there!

I found a issue when using the JupyterLab dark theme.
It is not possible to see the dropdown options of the cell when you use the "dark mode".

To reproduce the issue, you do:
- Change the jupyterlab to dark mode: Settings > JupyterLab Theme > JupyterLab Dark;
- Open a new notebook;
- Left click on the first cell, just for select it;
![download](https://user-images.githubusercontent.com/6098725/44363193-d4168f80-a499-11e8-9e13-22b3f7cc38c5.png)
- Left click on the dropdown that modify the cell in the top of the notebook;
![image](https://user-images.githubusercontent.com/6098725/44363285-2952a100-a49a-11e8-8c6a-7abf15fb22c8.png)
-----------------------------
The curious thing, is that if you click somewhere off the cell, and then click on the dropdown menu, the problem does not happen.

- Clicking off the cell:
![image](https://user-images.githubusercontent.com/6098725/44363560-e7762a80-a49a-11e8-8b66-25101c5bee81.png)
- The problem not happen:
![image](https://user-images.githubusercontent.com/6098725/44363605-02e13580-a49b-11e8-952c-770c5971fb18.png)
-----------------------------
I'm using JupyterLab Version 0.33.11

JupyterLab is GREAT! I hope to help improve him by reporting this issue, thanks!

**Comment by blink1073** [comment]
Thanks for the update, @fm75!  @xicopetry, can you please try 0.34 and see if the problem is resolved?

**Comment by xicopetry** [comment]
@blink1073 I updated my jupyterlab and made the same process to see if the problem still persists.
![image](https://user-images.githubusercontent.com/6098725/44422669-2dde8e80-a55a-11e8-9cfd-358bb6f52601.png)

And, the problem still happen! :(
![image](https://user-images.githubusercontent.com/6098725/44422747-641c0e00-a55a-11e8-88a5-017108ca03ce.png)

Do you need more information about my environment?

**Comment by xicopetry** [comment]
@blink1073  I'm running this jupyterlab on a container in CodeAnywhere and access the lab via Chrome (v 68.0.3440.106) and Windows 7 Ultimate, SP1.

The OS is:
Distributor ID: Ubuntu
Description: Ubuntu 14.04 LTS
Release: 14.04
Codename: trusty

I run the JupyterLab via:
`jupyter lab --ip=0.0.0.0`

**Comment by blink1073** [comment]
Thanks @xicopetry, I'm at JupyterCON this week but will get back into dev mode starting next week.

**Comment by blink1073** [comment]
I confirmed the behavior using Chrome in a Windows 10 VM.  It does not happen when using Chrome on MacOS.  I'm not entirely sure how to fix the issue, however...
