### ISSUE TITLE
working on remote jupyterlab uses lot of ram when writing images

### ISSUE THREAD

**Issue by JaspervDalen** [jupyterlab/jupyterlab#5171]
I work on a remote machine on which the jupyter lab server is running (I use jupyter lab --no-browser --port=8889  to start the server and  ssh -N -f -L localhost:8888:localhost:8889 remote_user@remote_host to work on it remotely). However when a cell is creating lots of files (images in my case) the memory of my local machine is somehow used even though the files are written on the remote machine on which the server is running. When running it as jupyter notebook this does not happen. I also have a colleague who stopped using lab because of its memory usage.

**Comment by jasongrout** [comment]
I realize you filed this issue a long time ago, and it's possible this has been fixed since then. Do you still see this problem? If so, can you give us a code sample reproducing this problem?
