### ISSUE TITLE
Kernel names cut off in kernel selector dialog

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5181]
See https://gitter.im/jupyterlab/jupyterlab?at=5b7b2baac53ee54c187bcf78

I think we should do any cutting off of the kernel names - just let people see the full name.

**Comment by jasongrout** [comment]
See https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/clientsession.tsx#L1058

**Comment by sharonwoo** [comment]
Hi, I'd like to work on this. Am new to JupyterLab development, pls bear with me.
