### ISSUE TITLE
Continuous "JupyterLab build is suggested" after all rebuilds - cannot understand why rebuilding is needed

### ISSUE THREAD

**Issue by belonesox** [jupyterlab/jupyterlab#5189]
I have jupyterhub (0.9.2) + jupyterlab (0.33.0) and serveral labextensions installed. 

But constantly get warning in UI:

```
JupyterLab build is suggested:
@jupyterlab/application-extension changed from ^0.17.4 to ^0.17.3
@jupyterlab/coreutils changed from ^2.0.3 to ^2.0.2
@jupyterlab/docmanager-extension changed from ^0.17.4 to ^0.17.2
@jupyterlab/filebrowser changed from ^0.17.3 to ^0.17.2
@jupyterlab/filebrowser-extension changed from ^0.17.4 to ^0.17.2
@jupyterlab/outputarea changed from ^0.17.3 to ^0.17.2
@jupyterlab/rendermime changed from ^0.17.3 to ^0.17.2
@jupyterlab/running changed from ^0.17.3 to ^0.17.2
@jupyterlab/shortcuts-extension changed from ^0.17.3 to ^0.17.2
url-parse changed from ~1.4.3 to ~1.1.9
«Build failed with 500, please run 'jupyter lab build' on the server for full output»
```

(So on REST API GET http://xxxx/user/yyyy/lab/api/build also get
```	
  status	"needed"
  message	"@jupyterlab/application-extension changed from ^0.17.4 to ^0.17.3...."
```  
)

«Build failed» IMO OK, because I am running jupyterhub, so users should not rebuild extensions, 
only admins/deploy scripts.

But I cannot understand why rebuilding is needed:
* I run 100500 times as root: «jupyter lab build» — it takes a lot of times, all builded without problems
* On «jupyter labextension list» I got this (without "rebuild" warnings!)

```
JupyterLab v0.33.12
Known labextensions:
   app dir: /usr/share/jupyter/lab
@jupyterlab/git
        @jupyterlab/git v0.1.3  enabled  OK
@jupyterlab/latex
        @jupyterlab/latex v0.4.0  enabled  OK
@mflevine/jupyterlab_html
        @mflevine/jupyterlab_html v0.1.4  enabled  OK
jupyterlab-drawio
        jupyterlab-drawio v0.3.0  enabled  OK
nbdime-jupyterlab
        nbdime-jupyterlab v0.4.0  enabled  OK
pylantern
        pylantern v0.0.6  enabled  OK
```

So, 
* Why? Where stored checksums etc, why UI decided need rebuilding but console utilities — not to rebuild.
* How reliable check in console that rebuilding needed?
* How to force rebuild all (may be «jupyter lab build» by default too lazy to rebuild all?)
* What else can be not Ok?

```
pip3.6 list | grep jupyter 
jupyter-client (5.2.3)
jupyter-core (4.4.0)
jupyterhub (0.9.2)
jupyterhub-ldapauthenticator (1.2.2)
jupyterlab (0.33.0)
jupyterlab-git (0.2.0)
jupyterlab-latex (0.4.0)
jupyterlab-launcher (0.11.2)
```

**Comment by blink1073** [comment]
Hi @belonesox, that is a strange one.  Can you please try `jupyter lab clean && jupyter lab build` and see if that rectifies it?

**Comment by belonesox** [comment]
Yes, I tried «jupyter lab clean && jupyter lab build», it finished OK does not help.

I found a cause:
* I have installed jupyterlab package both under python2 and python3.
* Of course, jupyterlab runned under python3.6, and I cannot understand how jupyterlab on python2 interfere with jupyterlab on python3.
* After I uninstall jupyterlab from python2 adn python3 and reinstall jupyterlab on python3 + «jupyter lab clean && jupyter lab build» — this  problem gone.

But I still cannot understand how jupyterlab on python2 interfere with jupyterhub running on python3.

**Comment by blink1073** [comment]
Hmm, without having it in that state it is hard to debug further.  I don't understand how that could happen either, but I've seen plenty of weird things happen when more than one python is available on your PATH.  Glad it is working now though!
