### ISSUE TITLE
Unknown system error -122 (while running jupyter lab build)

### ISSUE THREAD

**Issue by santoshamohan** [jupyterlab/jupyterlab#5195]
I am getting following error when I try to run `jupyter lab build`:
_`$ /foo/miniconda3/bin/jupyter lab build`
`[LabBuildApp] > node /foo/miniconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install`
`yarn install v1.6.0`
`info No lockfile found.`
`[1/4] Resolving packages...`
`warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.`
`warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.`
`warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.`
`[2/4] Fetching packages...`
`error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyterlab/application/-/application-0.17.2.tgz: Unknown system error -122: Unknown system error -122, write".`
`info If you think this is a bug, please open a bug report.`
`info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`
`[LabBuildApp] > node /foo/miniconda3/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod`
`yarn run v1.6.0`
`$ webpack --config webpack.prod.config.js`
`/bin/sh: webpack: command not found`
`error Command failed with exit code 127.`
`info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`_

### Steps to reproduce on the CentOs terminal:
1) `curl -o "$TMPDIR/miniconda.sh" https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh`
2) `chmod +x "$TMPDIR/miniconda.sh"`
3) `cd "$TMPDIR" || exit`
4) `./miniconda.sh -b -f -u -p /foo/miniconda3`
5) `/foo/miniconda3/bin/conda update -y -n base --all`
6) `/foo/miniconda3/bin/conda install -y --override-channels -c conda-forge nodejs jupyterlab`
7) `/foo/miniconda3/bin/jupyter lab build`

Response to this issue is much appreciated. Thank you!

**Comment by blink1073** [comment]
Hi @santoshamohan, it looks like you are using JupyterLab 0.32, which used an older version of yarn.   Are you able to update to 0.34?

**Comment by santoshamohan** [comment]
Issue no longer seen with JupyterLab v0.34.2.
