### ISSUE TITLE
Can the launcher show python 2 notebook or terminal option?

### ISSUE THREAD

**Issue by minertom** [jupyterlab/jupyterlab#5201]
I have jupyter notebook installed and python 3.6 is an option as shown in the launcher.
When I open the launcher, I see icons for opening notebooks and terminals but all are in python3. I have installed packages as shown here:

conda create -n py2 python=2 anaconda
# register py2 kernel
activate py2
ipython kernel install
pip install jupyterhub

When I open a new launcher I still see no option for opening a python2 terminal or notebook, only python3.

Also, when I open a particular notebook that I have, I see options for changing the kernel but only see the option for python3 or pythonV (which I don't know what that is).

I know that the code from the notebook that I am importing "wants" python 2.7. It is in the documentation and also it is obvious because of how the "print" command is used.

Thank You
Tom

**Comment by blink1073** [comment]
Hi @minertom, to see kernels from other conda environments, you can run `conda install nb_conda_kernels`, and then launch JupyterLab again.

**Comment by minertom** [comment]
Thank You! Is there a way to upvote you on this forum?

Tom

**Comment by blink1073** [comment]
You are welcome!  I'm not aware of such a global upvote feature in GitHub, but that would be an interesting one.
