### ISSUE TITLE
 Kernel name shortened when searching - hovering not working

### ISSUE THREAD

**Issue by ncclementi** [jupyterlab/jupyterlab#5205]
OS: Ubuntu 14.04 
Installation: Followed the instructions on https://github.com/jupyterlab/jupytercon-jupyterlab-tutorial

When trying to connect kernels, when it gets to choose, the options on the display menu are incomplete and hovering doesn't work. 

![screenshot from 2018-08-24 11 44 17](https://user-images.githubusercontent.com/7526622/44594083-38379d00-a793-11e8-97ec-7e952195ea01.png)

**Comment by blink1073** [comment]
Hi @ncclementi, thanks for the report!

**Comment by blink1073** [comment]
Fixed by#5181
