### ISSUE TITLE
Slow starting kernel has problems with timeouts

### ISSUE THREAD

**Issue by drmeister** [jupyterlab/jupyterlab#5208]
Could any kind jupyterlab developer give me an overview of what time-outs are important in the jupyter communication protocol?

We have developed a Common Lisp kernel that uses jupyter widgets including a few custom jupyterlab extensions (nglview and bqplot).
Our kernel normally takes about 30 seconds to start up because it invokes its slow, llvm-based compiler a few times at startup (we are working on starting up from images - so this will improve).
This slow startup appears to cause timing problems with the jupyter protocol that are very hard to debug.
It seems the jupyter protocol makes assumptions about how fast kernels can respond at startup and that might cause problems for other kernel developers - it cost me several weeks to figure this out.
The problems go away now that I wrote a fork-server that warms up our kernel and then forks children to service notebooks.

**Comment by drmeister** [comment]
To give an example...

The first kernel_info_request from the Python middleware (what is it called officially?) to the kernel times out after a while if the kernel doesn't send a kernel_info_reply fast enough.   

After the timeout we see a lot of kernel_info_requests come in to the kernel that appear (I'm not sure about this) to be sourced from the browser!  

These kernel_info_requests appear to be malformed - they have version 5.2 but they were missing the 'date' field.   This may have been corrected in recent versions of the jupyterlab Javascript.   I'm sorry if this sounds vague - but it's tough to figure out what is going on here.   I've been inserting a lot of print statements into the jupyterlab python code and the Javascript code.

Any clarity from the jupyterlab developers on what we are seeing here would be most welcome.

**Comment by blink1073** [comment]
Hi @drmeister, the kernel info timeout is a configurable item: https://github.com/jupyter/notebook/blob/master/notebook/services/kernels/kernelmanager.py#L97.  You can define it in `juptyer_notebook_config.py` as `c.MappingKernelManager.kernel_info_timeout`.    https://jupyter-notebook.readthedocs.io/en/stable/config_overview.html.

The kernel_info_request has no payload: https://jupyter-client.readthedocs.io/en/stable/messaging.html#kernel-info.

**Comment by drmeister** [comment]
Alright!  Thank you very much!

So is this the only timeout I need to worry about?
Hmm, I think I can answer my own question here - our kernel responds quickly except at startup (until we get that fixed) - so it should be the only timeout that we need to worry about.

**Comment by blink1073** [comment]
No problem!  Yes, I believe that should be the only timeout of concern.
