### ISSUE TITLE
Using fluent TSX (typescript + JSX) in a component

### ISSUE THREAD

**Issue by davclark** [jupyterlab/jupyterlab#5215]
*This is a Docs issue for developing extensions*

I looked at the [docs on using VDOM in a widget](https://jupyterlab.readthedocs.io/en/stable/developer/virtualdom.html) and that led me to a fairly complex example that frankly overwhelmed me.

I then wrote what is (I think) a fairly idiomatic React Widget that can go into a Phosphor widget. I'll post a docs PR after we get something more interactive working, but I wanted to drop a placeholder here for now. Basically, here's a widget that we add to the left panel (`app.shell.addToLeftArea()`):

```
// This is Typescript / JSX
// Note that tsconfig.json needs to include compilerOptions.jsx = "react"
// for tsc (and thus jlpm) to work by default

import { Panel } from '@phosphor/widgets';
// These libs don't have default exports, so this grabs everything
import * as React from 'react';
import * as ReactDOM from 'react-dom';

class ContextWidget extends Panel {

  constructor(client_url="https://localhost:10000") {
    super();

    // Set some basic styling
    this.title.iconClass = 'jp-some-icon jp-SideBar-tabIcon';
    this.title.caption = 'Info';
    this.id = 'jp-ContextWidget';
    this.addClass('jp-ContextWidget');

    ReactDOM.render(<ContextInfo client_url={client_url} />, this.node);
  }
}

type InfoProps {
  client_url: string
};

class ContextInfo extends React.Component {
  props: InfoProps;
  // Once we have state, we should also specify types here

  constructor(props: InfoProps) {
    super(props);
    // this.state = { };
  }

  render(): React.ReactElement<any> {
    return(
      <div>
        <h1>Context</h1>
        <p><a href={this.props.client_url}>Open client</a></p>
      </div>
    );
  }
}

export default ContextWidget;
```

**Comment by sccolbert** [comment]
You should extend Widget instead of Panel. A Panel is intended to hold
other Phosphor widgets as children.

**Comment by saulshanabrook** [comment]
Yeah I agree it would be nice to document how to properly render a react component in a widget. Ideally, we could have some shim code that would map relevent widget lifecycle methods to react lifecycle methods. I was thinking we could also add the lifecycle callbacks to the react context. But yeah, just to get something working you can extend from Widget just render to the node. This is how I did it for the running side bar: https://github.com/jupyterlab/jupyterlab/blob/3201e4714ae85f3c21f0218261826595d55af518/packages/running/src/index.tsx#L282-L332

**Comment by davclark** [comment]
Nice. I barely know what I'm doing here, but I guess you don't need to inherit from `React.Component` because you already have some lifecycle hooks and so you can get away with just putting `ReactDOM.render` in your `onUpdateRequest`?

I see that you're not using React state there, which I expect WOULD require me to inherit from `React.Component`. I'm working in a React team, so I want things to be as idiomatic as possible for those developers. In that case, does my nested `React.Component` inside of a `Widget` make sense? I know I have `Panel` above, but I'll change that.

**Comment by ellisonbg** [comment]
Hi Dav, here is a basic react component in JLab:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/toolbar.tsx#L375

Along with a simple class that wraps it into a phosphor widget:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/toolbar.tsx#L401

In this particular case, I have setup the phosphor widget to take the same props as the react component.

For really simple usage, you can just pass your react component to the constructor 
 as in `ReactElementWidget(<MyComponent {...props}/>)`

**Comment by davclark** [comment]
Cool. I'ts on my backlog to actually clean up a working version of our widget and share it. Right now there's an issue where jlpm doesn't work from the command line, but npm does... BUT then `jupyter lab --watch` wants to run the full jlpm build every time I make a file change.

But again, it seems like this wrapper is also just handling props and not state, right? But in any case, it's pointing me towards a cleaner way to integrate Reach and Phosophor - thanks!

**Comment by ellisonbg** [comment]
Could you open another issues asking the question about jlpm/npm? I have a feeling that would get lost here.

But yes, this wrapper would allow you to pass in props, but any state of the react component would be internal to it and hidden from the widget. I suppose if you need to work with state from the phosphor widget, you could expose an API on your react component for working with the state. In my experience, it is easiest to have a clean boundary between phosphor in which the only interface is what the widget passes to the component as props.

**Comment by davclark** [comment]
Sorry to be so slow in getting back to this!

Regarding the initial question, I think at this point, there's a really nice example project for what I was asking: the [celltags widget](https://github.com/jupyterlab/jupyterlab-celltags).

Regarding the jlpm / npm issue, I have found known bugs around yarn + react + typescript, and I'm guessing that this was causing the issue. If we continue to hit problems, we'll open up another issue!

**Comment by davclark** [comment]
Actually, it looks like this has been converted to a docs issue, and it's probably not my place to close. re-opening, but if it SHOULD be closed, that's fine. Also happy to help with the docs once I fully understand this myself.
