### ISSUE TITLE
Error when opening jupyter notebook from anaconda navigator

### ISSUE THREAD

**Issue by ikramansari77** [jupyterlab/jupyterlab#5218]
This is error message:

[I 02:13:45.966 NotebookApp] JupyterLab beta preview extension loaded from C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab
[I 02:13:45.967 NotebookApp] JupyterLab application directory is C:\ProgramData\Anaconda3\share\jupyter\lab
[I 02:13:46.119 NotebookApp] Serving notebooks from local directory: C:\Users\Ikram
[I 02:13:46.119 NotebookApp] 0 active kernels
[I 02:13:46.119 NotebookApp] The Jupyter Notebook is running at:
[I 02:13:46.119 NotebookApp] http://localhost:8888/?token=0222161362eba75290fa231361c8e58e40fbfaea6e21c7c8
[I 02:13:46.119 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 02:13:46.127 NotebookApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=0222161362eba75290fa231361c8e58e40fbfaea6e21c7c8&token=0222161362eba75290fa231361c8e58e40fbfaea6e21c7c8
[I 02:13:46.219 NotebookApp] Shutting down 0 kernels
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 10, in 
sys.exit(main())
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
app.start()
File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1670, in start
self.io_loop.start()
File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
self.asyncio_loop.run_forever()
File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
self._run_once()
File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1396, in _run_once
event_list = self._selector.select(timeout)
File "C:\ProgramData\Anaconda3\lib\selectors.py", line 323, in select
r, w, _ = self._select(self._readers, self._writers, [], timeout)
File "C:\ProgramData\Anaconda3\lib\selectors.py", line 314, in _select
r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

**Comment by blink1073** [comment]
Hi @ikramansari77, does the same happen when running `jupyter notebook`?

What is the output of `jupyter troubleshoot` (you may want to cleanse the output if there is anything sensitive about your $PATH variable or environment setup)?

**Comment by NBRTS** [comment]
[I 12:25:27.623 NotebookApp] The port 8888 is already in use, trying another port. [I 12:25:27.676 NotebookApp] JupyterLab extension loaded from D:\anaconda\envs\basic\lib\site-packages\jupyterlab [I 12:25:27.676 NotebookApp] JupyterLab application directory is D:\anaconda\envs\basic\share\jupyter\lab [I 12:25:27.678 NotebookApp] Serving notebooks from local directory: C:\Users\Admin [I 12:25:27.679 NotebookApp] The Jupyter Notebook is running at: [I 12:25:27.679 NotebookApp] http://localhost:8889/?token=466e75b1e6eb40ba34bb079ed72a3d991ce437fc04aea209 [I 12:25:27.679 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation). [C 12:25:27.737 NotebookApp] To access the notebook, open this file in a browser: file:///C:/Users/Admin/AppData/Roaming/jupyter/runtime/nbserver-11184-open.html Or copy and paste one of these URLs: http://localhost:8889/?token=466e75b1e6eb40ba34bb079ed72a3d991ce437fc04aea209 [I 12:25:37.681 NotebookApp] Kernel started: e650716d-4f79-44bb-807d-c42f668ed922 Traceback (most recent call last): File "D:\anaconda\envs\basic\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "D:\anaconda\envs\basic\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "D:\anaconda\envs\basic\lib\site-packages\ipykernel_launcher.py", line 15, in from ipykernel import kernelapp as app File "D:\anaconda\envs\basic\lib\site-packages\ipykernel\__init__.py", line 2, in from .connect import * File "D:\anaconda\envs\basic\lib\site-packages\ipykernel\connect.py", line 13, in from IPython.core.profiledir import ProfileDir File "D:\anaconda\envs\basic\lib\site-packages\IPython\__init__.py", line 55, in from .terminal.embed import embed File "D:\anaconda\envs\basic\lib\site-packages\IPython\terminal\embed.py", line 15, in from IPython.core.interactiveshell import DummyMod, InteractiveShell File "D:\anaconda\envs\basic\lib\site-packages\IPython\core\interactiveshell.py", line 16, in import asyncio File "D:\anaconda\envs\basic\lib\asyncio\__init__.py", line 8, in from .base_events import * File "D:\anaconda\envs\basic\lib\asyncio\base_events.py", line 23, in import socket File "D:\anaconda\envs\basic\lib\socket.py", line 52, in import os, sys, io, selectors File "D:\anaconda\envs\basic\lib\selectors.py", line 12, in import select File "C:\Users\Admin\Desktop\python\select.py", line 12, in print(view()) File "C:\Users\Admin\Desktop\python\select.py", line 6, in view cur.execute('SELECT * FROM store') sqlite3.OperationalError: no such table: store

**Comment by jasongrout** [comment]
Is this still an issue @ikramansari77?

**Comment by TianCal** [comment]
> Is this still an issue @ikramansari77?

I am getting the same issue. What should I do?

**Comment by jasongrout** [comment]
This looks like an installation issue, possibly bugs in old versions of software. Please comment below if this is still an issue with up-to-date packages.
