### ISSUE TITLE
Oscillating performance of remotely launched JupyterLab...

### ISSUE THREAD

**Issue by itarec1988** [jupyterlab/jupyterlab#5223]
Hello,

For some time I have been working with JupyterLab connected remotely to a cluster via ssh. This has worked quite well until a week or so. I haven't done any recent updates and I get the following errors when I launch and the Jlab notebook:

[I 18:58:01.902 LabApp] 302 GET /?token=17c9d4a74940e10ce8eafa6c73ce504cdd94e54c9280388d (127.0.0.1) 2.57ms
[W 18:58:02.837 LabApp] Could not determine jupyterlab build status without nodejs
[W 18:58:04.451 LabApp] 404 GET /lab/api/themes/@jupyterlab/theme-light-extension/43bb4cbf1d0ecfdb1309e4cb67264f35.ttf (127.0.0.1) 301.93ms referer=http://localhost:8886/lab/api/themes/@jupyterlab/theme-light-extension/index.css
[W 18:58:04.497 LabApp] 404 GET /lab/api/themes/@jupyterlab/theme-light-extension/5a0856eb52623ae94b09dbbf31a27b95.ttf (127.0.0.1) 3.54ms referer=http://localhost:8886/lab/api/themes/@jupyterlab/theme-light-extension/index.css
[I 18:58:15.911 LabApp] Kernel started: 9a92592d-0316-4cbe-ab9e-e570fd594e40
[I 18:58:16.004 LabApp] Kernel started: 99cb1ae3-3ccf-439b-901f-c36a1253ee40
[W 18:59:59.551 LabApp] Timeout waiting for kernel_info reply from 9a92592d-0316-4cbe-ab9e-e570fd594e40
[I 18:59:59.556 LabApp] 302 GET /?token=17c9d4a74940e10ce8eafa6c73ce504cdd94e54c9280388d (127.0.0.1) 0.43ms
[W 19:00:02.325 LabApp] Could not determine jupyterlab build status without nodejs
[W 19:00:23.998 LabApp] 404 GET /lab/api/themes/@jupyterlab/theme-light-extension/43bb4cbf1d0ecfdb1309e4cb67264f35.ttf (127.0.0.1) 1.41ms referer=http://localhost:8886/lab/api/themes/@jupyterlab/theme-light-extension/index.css
[W 19:00:24.906 LabApp] 404 GET /lab/api/themes/@jupyterlab/theme-light-extension/5a0856eb52623ae94b09dbbf31a27b95.ttf (127.0.0.1) 3.38ms referer=http://localhost:8886/lab/api/themes/@jupyterlab/theme-light-extension/index.css
[W 19:00:26.620 LabApp] Could not determine jupyterlab build status without nodejs
[W 19:00:36.446 LabApp] 404 GET /lab/api/themes/@jupyterlab/theme-light-extension/43bb4cbf1d0ecfdb1309e4cb67264f35.ttf (127.0.0.1) 1.27ms referer=http://localhost:8886/lab/api/themes/@jupyterlab/theme-light-extension/index.css
[W 19:00:36.919 LabApp] 404 GET /lab/api/themes/@jupyterlab/theme-light-extension/5a0856eb52623ae94b09dbbf31a27b95.ttf (127.0.0.1) 3.37ms referer=http://localhost:8886/lab/api/themes/@jupyterlab/theme-light-extension/index.css

Besides this, sometimes I have a very slow (a couple of minutes) start of Jlab on the browser (google chrome) and when it works, importing packages take also several minutes. However, at random cases, it works ok and these delays are not present. But I have to say this has become more frequent in the last two weeks. 

Versions of jupyter related packages:
jupyter                       1.0.0                    py36_3  
jupyter_client            4.4.0                    py36_0  
jupyter_console        5.0.0                    py36_0  
jupyter_core              4.2.1                    py36_0  
jupyterlab                  0.31.12                py36_1    conda-forge
jupyterlab_launcher  0.10.5                 py36_0    conda-forge

Could someone give a hint on how to proceed to overcome this problem?

Thanks a lot..,

**Comment by blink1073** [comment]
Hi @itarec1988, is it possible for you to update to JupyterLab 0.34 and see if it is still causing issues?

**Comment by blink1073** [comment]
You'll need nodejs in order to install any extensions.  That check is determining whether to rebuild JupyterLab in light of new extensions.  You can get nodejs from conda.

If you have variables that take up a lot of memory, and then send that data to the notebook for display, that can cause performance issues.  It depends on your browser and the type of display (table, image, etc).

**Comment by itarec1988** [comment]
Ok I'll take this into account. 
Thanks a lot

**Comment by blink1073** [comment]
No problem!
