### ISSUE TITLE
jupyter lab build  fails in webpack install

### ISSUE THREAD

**Issue by joequant** [jupyterlab/jupyterlab#5225]
I'm trying to install jupyter lab extensions in a clean linux box.  I'm getting install errors which appear to occur because jupyter lab build is calling webpack and not webpack --dev so that the devdependencies are not getting installed

warning ipysheet > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
[###########################----------------------------------------] 419/1051[LabBuildApp] > node /usr/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build
yarn run v1.9.4
$ webpack
✖ ｢config｣: An error occurred while trying to find a config file
              Did you forget to specify a --require?
/usr/lib/node_modules/webpack-command/node_modules/@webpack-contrib/config-loader/lib/load.js:85
    throw new LoadConfigError(e, configPath);
    ^

LoadConfigError: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (/usr/lib/node_modules/webpack-command/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/usr/share/jupyter/lab/staging/webpack.config.js:7:10)
    at Module._compile (/usr/lib/node_modules/webpack-command/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by blink1073** [comment]
Hi @joequant, it looks like something may have gone wrong in the `yarn` phase.   Can you please try the following?

- `jupyter lab paths`
- Change directory to the "application" directory
- `cd staging`
- `ls node_modules/fs-extra`  # <-- this should be there

If `fs-extra` is not there, can you please run `jlpm` from the staging directory and give the output?

**Comment by vidartf** [comment]
I've been having the same issue, but with an additional line about the registry:
```
yarn install v1.9.4
info No lockfile found.
[1/4] Resolving packages...
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[LabBuildApp] > node C:\cleanconda\envs\ipycolordev\lib\site-packages\jupyterlab\staging\yarn.js run build
yarn run v1.9.4
$ webpack
module.js:538
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    [...]
```

**Comment by vidartf** [comment]
My issue go resolved by uninstalling all extensions, running `jupyter lab clean`, `jupyter lab build`. Afterwards, I could install all my extensions again.

**Comment by ian-r-rose** [comment]
I also saw the same issue last week @vidartf. I couldn't figure out the problem, but it was also fixed by having a completely fresh start.

**Comment by pwrose** [comment]
@blink1073 I've installed the latest version of JupyterLab (0.34.6) and the install of the jupyterlab_3dmol extension works.

I think the problem was that I have Node v10.4.1 which was not compatible with earlier versions of JupyterLab (#5121).

**Comment by blink1073** [comment]
Glad you got sorted @pwrose!

**Comment by blink1073** [comment]
Thanks for the feedback, @thecristen!  I think we can solve a lot of problems by making the build phase run "clean" if it falls and then try to build again.

**Comment by blink1073** [comment]
I also think we can do a better job of surfacing the original error and point people toward the appropriate npm config.

**Comment by krstp** [comment]
Generally, the magic formula is here:
https://github.com/plotly/plotly.py#jupyterlab-support-python-35
and here:
https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/plotly-extension
mind, no need to download the git.

If does not work, do not worry. The `jlpm` command is JupyterLab's pinned version of `yarn` that is installed with JupyterLab. You may use `yarn` or `npm` in lieu of `jlpm`. This means, whenever a package is missing try to install with one of the other installers. Then return back and finally invoke: `jupyter lab build`. 

Other than that while installing some of the packages `npm` requires:
`npm set strict-ssl false`  

Similar thing applies to `yarn` which requires in your home folder `.yarnrc` file with following line:
`strict-ssl false`

With those steps you should be good to go.
