### ISSUE TITLE
Unable to click to make cell output scrollable

### ISSUE THREAD

**Issue by shavakagrawal** [jupyterlab/jupyterlab#5239]
I was just porting my environment from the classic Notebooks to Lab and a major issue that seems to persist is being unable to click next to the cell output to make it scrollable. Also, in classic Notebooks, if I convert the cell output to scrollable once, it stays that way. But in Lab I have had to convert it to scrollable each time.

Thanks!

**Comment by saulshanabrook** [comment]
> a major issue that seems to persist is being unable to click next to the cell output to make it scrollable

I am sorry, I don't quite follow. Could you give a little more detail here about what you would like the behavior to be?

> Also, in classic Notebooks, if I convert the cell output to scrollable once, it stays that way. But in Lab I have had to convert it to scrollable each time.

In JL you have to do File -> "Save Notebook with View State" and then the collapsed/scrolling status of each cell is saved to the file. Does this help?

**Comment by shavakagrawal** [comment]
1. ![image](https://user-images.githubusercontent.com/18590845/45012601-7e171f80-b035-11e8-9742-a706b3ef4640.png)
This experience within the classic notebooks, wherein on hovering next to the output, we have the option of making the output scrollable.
2. I am referring to the behaviour of the same cell, wherein, upon executing the same cell twice, even if we make the cell scrollable the first time around, the output won't be scrollable the next time around.

**Comment by saulshanabrook** [comment]
Thanks @shavakagrawal for those clarifications.

**Comment by gabalafou** [comment]
I need some clarification on this issue. After poking around, it looks to me that all of the points in this issue around persisting the scrollable state of a cell have been taken care of, leaving just the point about the clickable left area—meaning, has this issue collapsed to one that is strictly about porting the "click to scroll/unscroll output" from Classic Notebook to Lab?

**Comment by JasonWeill** [comment]
Closing this in favor of #5897, which has much more discussion and is about the same issue.
