### ISSUE TITLE
Right click to open terminal

### ISSUE THREAD

**Issue by zdog234** [jupyterlab/jupyterlab#5242]
I couldn't find any requests for something like this. It would be nice if the "File Explorer" right click menu had an "Open terminal here" option.

p.s. Jupyter Lab is awesome, and I love that so many other related projects (like jupyterlab-git) have been taken under the wing.

**Comment by dhirschfeld** [comment]
***xref:*** https://github.com/jupyterlab/jupyterlab/issues/4280#issuecomment-414559093
