### ISSUE TITLE
Advanced Settings Editor - User Overrides for text editor breaks notebook

### ISSUE THREAD

**Issue by clayms** [jupyterlab/jupyterlab#5243]
When adding the setting below to the "User Overrides" file of the "Advanced Settings Editor" works as expected and runs the highlighted code or line where the cursor is when pressing <kbd>CTRL</kbd>+<kbd>Enter</kbd> in a text editor linked to a Console.

However, the setting below breaks the behavior of <kbd>Shift</kbd>+<kbd>Enter</kbd> in a notebook.  It only works when the cell is in edit mode, and will not work otherwise.  So after a single cell advance, <kbd>Shift</kbd>+<kbd>Enter</kbd> stops working.

The work-around is to press <kbd>Enter</kbd> after each advance to put the next cell into edit mode, then press <kbd>Shift</kbd>+<kbd>Enter</kbd> to run and advance.  This gets tedious. 

Is there a way to get the desired behavior in in a text editor linked to a Console and not change the behavior in a notebook?

```
{
    // [missing schema title]
    // [missing schema description]
    "runmenu:run": {
      "command": "runmenu:run",
      "keys": [
        "Ctrl Enter"
      ],
      "selector": "[data-jp-code-runner]",
      "title": "Run",
      "category": "Run Menu"
    }
}
```

**Comment by ian-r-rose** [comment]
Hi @clayms, the `'runmenu:run'` command is a sort-of meta-command that targes notebooks, consoles, and text files, so this override is having the expected effect. If you want to specifically override the run command for text files, try something like
```json
    "fileeditor:run-code": {
      "command": "fileeditor:run-code",
      "keys": [
        "Ctrl Enter"
      ],
      "selector": ".jp-FileEditor",
      "title": "Run Code",
      "category": "File Editor"
    }
```

**Comment by clayms** [comment]
@ian-r-rose  Perfect. Thanks!
