### ISSUE TITLE
Notebook Freezes Tab Icon

### ISSUE THREAD

**Issue by MarkMazel** [jupyterlab/jupyterlab#5244]
If a notebook is opened and then a command is executed and while the command is executing the notebook is closed, the icon of the JupyterLab will be stuck as the _hourglass_ forever.

Test by creating a new notebook and running something like this (and closing the notebook before the execution ends):

```python
import time
time.sleep(5)
```

**Comment by ian-r-rose** [comment]
Fixed by #5853. Thanks for the report @MarkMazel!
