### ISSUE TITLE
Extract MathJaxTypesetter into library

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#5257]
It would be nice to be able to import/use the `MathJaxTypesetter` without getting a dependency on `@jupyterlab/application`. This could be achieved if the class definition was extracted out from the extension package, into a separate library package.

On a similar note, would it be reasonable to move `materialcolors.css` from `@jupyterlab/application` to `@jupyterlab/apputils`? As far as I can tell from the dependency map at https://jlab.readthedocs.io/en/debug-rtd/extensions_dev.html, this should not add any additional dependencies.

**Comment by vidartf** [comment]
PS: If there is consensus for this, I'd be happy to do the legwork in a PR.

**Comment by blink1073** [comment]
Sounds good Vidar, yes, please!

**Comment by vidartf** [comment]
@blink1073 On both counts (typesetter and materialcolors)?

**Comment by blink1073** [comment]
Yup!

**Comment by vidartf** [comment]
Actually it should be both, otherwise apputils has an implicit dependency on application (otherwise there will be missing CSS vars, as e.g. `commandpalette.css` uses md vars).
