### ISSUE TITLE
Can't run Jupyterlab on Firefox (mac)

### ISSUE THREAD

**Issue by babyhands11** [jupyterlab/jupyterlab#5258]
Oddly, this issue persists specifically when it comes to Firefox while it runs perfectly fine in Safari. I have been all over any forums where the same issue was described but I haven't been able to find a solution.

OS: Mac OS Sierra 10.12.6
Firefox : 61.0.2(64-bit)

Please help if you can.

Cheers

**Comment by saulshanabrook** [comment]
Could you please attach a screenshot or some more information on what isn't working in firefox?

**Comment by saulshanabrook** [comment]
Interesting. What if you restart the kernel explicitly in firfox and then try to run the cell?

**Comment by jasongrout** [comment]
Can you try it in private mode in firefox, just to make sure it's not a caching issue?

**Comment by babyhands11** [comment]
That's what I thought in the beginning, unfortunately it didn't work :(

**Comment by jasongrout** [comment]
@babyhands11 - is this still an issue?

**Comment by babyhandzzz** [comment]
Hi, thanks for getting back to this issue.
I didn't manage to get it working on my old macbook air but since than I switched to macbook pro
and there are no issues, everything runs very smoothly in firefox.
