### ISSUE TITLE
Launcher kernel names are truncated

### ISSUE THREAD

**Issue by dsblank** [jupyterlab/jupyterlab#5263]
(I thought I had made an issue on this but couldn't find it).

The launcher will truncate kernel names. This is especially important to prevent kernel providers from duplicating the names of the language they implement. For example, there may be many kernels implementing Scheme, Java, or even Python, and allowing an adjective (or branding) to differentiate is important.

Consider my current launcher:

![screenshot from 2018-09-04 07-00-41](https://user-images.githubusercontent.com/168568/45027747-4b0e6500-b010-11e8-9a86-7f445a7aaefc.png)

See also:

1. https://github.com/jupyterlab/jupyterlab/issues/5205
2. https://github.com/jupyterlab/jupyterlab/pull/5260

**Comment by blink1073** [comment]
Yep, it is in #3262. Hi Doug!

**Comment by dsblank** [comment]
Thanks Steven!
