### ISSUE TITLE
Jupyterlab Terminal text spacing broken

### ISSUE THREAD

**Issue by alexforever86** [jupyterlab/jupyterlab#5264]
How can I change the font settings of Jupyterlab terminal. Currently, the line spacing is broken and I'm having a hard time fixing it. 

![lab-terminal](https://user-images.githubusercontent.com/11927055/45043032-24fdba80-b03a-11e8-8395-db2cc655aa99.png)

**Comment by blink1073** [comment]
Hi @alexforever86, this is an upstream issue: https://github.com/xtermjs/xterm.js/issues/1170

**Comment by saulshanabrook** [comment]
Closing this since I think https://github.com/jupyterlab/jupyterlab/issues/4013 covers the font size question.
