### ISSUE TITLE
UX: Sidebar icons improvements

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#5269]
The change to using icons for labeling the sidebar in #5117 makes sense, but the icons can be a bit confusing, especially for those that do not have English as a native language:
- The [palette icon](https://github.com/ellisonbg/jupyterlab/blob/f7e0d69363b288bea6c97e8884897ad5892b93fa/packages/theme-dark-extension/style/icons/md/ic_palette_24px.svg) strikes me as more related to themeing. Without knowing what a palette is, it can be very confusing. A replacement icon would preferably be more tied up to the *command* concept.
- The ["running" icon](https://github.com/ellisonbg/jupyterlab/blob/35df45add8437e888003de1bad2cf3fdb518844e/packages/theme-light-extension/style/icons/md/ic_directions_run_24px.svg) is based on a homonym (moving fast, and an process under execution). This concept does not necessarily translate to other languages. A possible suggestion is multiple cogwheels (multiple, since a single cogwheel indicates settings, by convention).

cc @ellisonbg

**Comment by timhoffm** [comment]
Possible alternatives:

- Commands: Something resembling an expanded menu. (Motivation: *command* is quite an abstract concept and hard to visualize. However, most commands are accessible via the menu bar.)
- Running: A play button

**Comment by gnestor** [comment]
How about these:

* Commands
  * A [command line prompt icon](https://material.io/tools/icons/?search=arrow&icon=arrow_forward_ios&style=baseline)
* Running: 
  * A [play icon](https://material.io/tools/icons/?search=play&icon=play_arrow&style=baseline) icon
  * A [fast-forward icon](https://material.io/tools/icons/?search=forward&icon=fast_forward&style=baseline)
  * A [power (on/off icon)](https://material.io/tools/icons/?search=on&icon=power_settings_new&style=baseline)
* Cell inspector: 
  * A [dials icon](https://material.io/tools/icons/?icon=tune&style=baseline) 
  * A [settings icon](https://material.io/tools/icons/?search=setting&icon=settings&style=baseline)

**Comment by t-makaro** [comment]
I like the power icon for the running section.

Also, I'd vote against the settings icon for the cell tools. A settings icon feels like it should go to jlab settings. I like the current wrench for cell tools, but I would not complain about the dials/tune icon.

**Comment by vidartf** [comment]
As an addition: The kernel icon in the statusbar now shows a piece of corn (a corn kernel). Again, this origin of the word kernel as applied to computers is not necessarily apparent to non-native English speakers. Most translations would be likely to use a translation of the synonym "core" than to refer to grains.

**Comment by jasongrout** [comment]
> The kernel icon in the statusbar now shows a piece of corn (a corn kernel).

+1 to changing the admittedly cute and clever, but not very obvious, referenced icon.

**Comment by ian-r-rose** [comment]
I agree with changing it as well.

**Comment by bollwyvl** [comment]
On Thu, Feb 14, 2019, 05:29 Vidar Tonaas Fauske <notifications@github.com>
wrote:

> As an addition: The kernel icon in the statusbar now shows a piece of corn
> (a corn kernel).
>
Personally, not a huge fan of the 🌽. Kernels in general need an overhaul
in branding and marketing, and need to be consistent. Adding Session to the
mix (a kernel plus a path, really... Maybe 🍿?) doesn't help things. Some
of the other UIs have adopted "runtime", but I'm not sure _that_ makes it
any clearer, as we're can't really change the term at this point.

> Againn, this origin of the word kernel as applied to computers is not
> necessarily apparent to non-native English speakers. Most translations
> would be likely to use a translation of the synonym "core" than to refer to
> grains.
>
The power riff is good. The circuit diagram symbols for DC and AC current
source are internationally recognized, and writeable:

(~)
(+-)
-| |+

This would only confuse a user that was building a circuit diagram.

State machine diagrams have start and stop states and are also
internationally recognized:
(•)
(X)

Same thing here with a domain user, but if lab becomes something that such
people use every day, we've done a helluva good job.

**Comment by gnestor** [comment]
@vidartf Ha! Where is this corn icon? I don't see it on master...

**Comment by jasongrout** [comment]
The corn icon is in the status bar.

**Comment by jasongrout** [comment]
<img width="222" alt="screen shot 2019-02-15 at 1 26 51 pm" src="https://user-images.githubusercontent.com/192614/52885222-633cf100-3125-11e9-86aa-cd64f8d299b6.png">

**Comment by vidartf** [comment]
PS: I'm not trying to make fun of it (it is actually quite clever if the users are native English speakers), just pointing out that it doesn't necessarily translate well.
