### ISSUE TITLE
Triage plans for 1.0

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#5270]
Here is a short summary of our plans for managing issues related to the 1.0 release:

Milestones:

* Future: our backlog.
* 1.0: actual issues we want to target for the 1.0 release.
* 0.35 issues will get moved to 1.0.

Process:

- [X] Remove the Future and 1.0 Milestone from all **open** issues that have them to indicate the need for us to do a triage pass on all of those issues.
- [X] Retarget all of the issues with the 0.35 Milestone to the 1.0 Milestone **open and closed**.
- [X] Delete the 0.35 milestone.
- [ ] Do a triage pass on all issues with no Milestone.

**Comment by ellisonbg** [comment]
During triage pass:

* Add 1.0, Future or Reference Milestone
* Add labels

**Comment by saulshanabrook** [comment]
Our Github tags:

* pkg: npm package that it applies to
* Tag: choose many
* Type: choose one

TODO:

- [ ] Update package tags to make sure they are up to date

**Comment by jasongrout** [comment]
Each person is going to do an individual triage of the issues with no milestone (plus whatever issues people may have moved to the 1.0/Future milestones). We'll meet again next Wednesday to discuss what we've triaged into 1.0.

**Comment by jasongrout** [comment]
My thoughts on the triage process is that anyone can move an issue into the 1.0 milestone for discussion next week (including issues that I may have put in the Future milestone). The issues is Future are the issues that everyone agrees should be in Future. The issues in 1.0 are issues that at least one person thinks should be in 1.0.

**Comment by blink1073** [comment]
Note: I attempted to make a script that would auto-milestone closed PRs and Issues, but it was far more complicated than I thought, so I am abandoning that task...

**Comment by jasongrout** [comment]
We did this triage at this point.
