### ISSUE TITLE
Extension development: Retrieve full path of notebook

### ISSUE THREAD

**Issue by nsriram13** [jupyterlab/jupyterlab#5273]
I am trying to add a button to the notebook panel (next to the save button) that copies the currently open notebook into another directory. The functionality I am trying to achieve is this - I want to give users ability to move a notebook to a mapped drive on the network so that other team members can download and work on that notebook.

I have a Python function that copies the notebook and I have set it up as an API. It takes the source path as input. The destination path is set to the network location. Something like:
```python
def copy(notebook_path):
    """
    Copy the current notebook into the publish folder
    """
    source_notebook_path = notebook_path
    destination_notebook_path = 'network location'

    copy(source_notebook_path, destination_notebook_path)
    return "Success!"
```

The `moveFile` function referenced below calls the API from the JupyterLab app. Now, I am trying to pass `notebook_path` from within there - but all paths seems to refer to the path of the notebook wrt the top directory where JupyterLab is being run.

```typescript
createNew(panel: NotebookPanel, context: DocumentRegistry.IContext<INotebookModel>): IDisposable {
	let callback = () => {
	  /** I am trying various ways of getting the absolute path here*/
	  let notebook_path = panel.context.contentsModel.path
	  let a = context.path
	  let b = context.localPath
	  console.log(notebook_path)
	  console.log(a)
	  console.log(b)
	  this.moveFile(notebook_path)
	};
	let button = new ToolbarButton({
	  className: TOOLBAR_PUBLISH_CLASS,
	  iconClassName: 'fa fa-upload',
	  onClick: callback,
	  tooltip: 'Publish this notebook'
	});

	panel.toolbar.insertItem(0, 'runAll', button);
	return new DisposableDelegate(() => {
	  button.dispose();
	});
	}
```
For example, if jupyter lab is launched from `\home\user\project`. 
My notebooks is in this location `\home\user\project\project1\my_experiment.ipynb`.
The paths seem to come out as `project1\my_experiment.ipynb`. 
Is there a way to retrieve full path?

**Comment by jasongrout** [comment]
The only thing Jupyter knows is the path the server gives it, which is relative to the root directory the server is serving. I think you'll have to figure out the full path on the filesystem in python - there you should have access to the server object (so you should be able to get the directory being served), and you have the relative path for the file.

**Comment by blink1073** [comment]
You can use `PageConfig.getOption('serverRoot')` to get the root.

**Comment by nsriram13** [comment]
Thanks @blink1073. I was able to implement the desired functionality using the `PageConfig` module.

**Comment by blink1073** [comment]
Great!
