### ISSUE TITLE
Default cells are several lines long

### ISSUE THREAD

**Issue by asafarevich** [jupyterlab/jupyterlab#5279]
![image](https://user-images.githubusercontent.com/30283914/45249733-159c9c80-b2da-11e8-927b-35d84c1b3dc6.png)
 Is there a way to reduce the size? I did not see a setting that created this default behavior, thought it might be a bug.

**Comment by Anton-Velikodnyy** [comment]
Sorry for the late response
Ubuntu 16.04.3 LTS
Mozilla Firefox 58.0.2
Here is the conda list of jupyter stuff
jupyter_client                  5.2.2                        py36_0  
jupyter_core                    4.4.0                        py36h7c827e3_0  
jupyterlab                         0.33.4                     py36_0                          conda-forge
jupyterlab_launcher       0.11.2                     py_0                              conda-forge

**Comment by ian-r-rose** [comment]
@Anton-Velikodnyy I have seen something like this when using large monitors with the browser zoomed out. In that case the CodeMirror CSS can get messed up. What happens when you play with the browser zoom?

**Comment by Anton-Velikodnyy** [comment]
First image at 70% and Second image at 160%. 
![image](https://user-images.githubusercontent.com/30283914/45602001-04831800-b9cb-11e8-825d-e446c90b841f.png)
![image](https://user-images.githubusercontent.com/30283914/45602017-4a3fe080-b9cb-11e8-95e1-dfe7458b7f28.png)

**Comment by Anton-Velikodnyy** [comment]
Looks like, I was at 70% before. As for monitor, I am using 2008 MacBook Laptop which is only 1080p in resolution and 13inch screen.

**Comment by Anton-Velikodnyy** [comment]
@ian-r-rose  thank you for looking into it
