### ISSUE TITLE
tab groups

### ISSUE THREAD

**Issue by paulthebaker** [jupyterlab/jupyterlab#5281]
I'm not sure how best to explain this.  I hope this makes sense.

When a new tab is opened it opens into a default group.  I would like to move a subset of tabs into a new group in the split screen.

For example in the screenshot below, I can split off individual tabs (`Terminal 2`, `Console 1`) from the default group.  I would like to combine `Terminal 2` and `Console 1` into a single group that shares the lower screen, like the four tabs that share the upper screen.

<img width="862" alt="screen shot 2018-09-08 at 12 04 47 pm" src="https://user-images.githubusercontent.com/7785231/45256111-c731e100-b35f-11e8-8358-1018ec96260a.png">

**Comment by paulthebaker** [comment]
I don't think I'm allowed to add labels, but I suggest: `Design and UX`, `feature request`.

**Comment by blink1073** [comment]
Hi @paulthebaker, I think you can achieve what you are asking by dragging the Terminal 2 tab to the center of the Console 1 pane.  cf https://jupyterlab.readthedocs.io/en/stable/user/interface.html#main-work-area

**Comment by paulthebaker** [comment]
You are correct.  I tried dragging it all sorts of places, but I must have never got it just right.

I'm closing.
