### ISSUE TITLE
CSV Viewer does not refresh data when new file written

### ISSUE THREAD

**Issue by DFuller134** [jupyterlab/jupyterlab#5284]
Overwriting a CSV file with new data and column headers does not refresh. I even deleted the file from the command line, saw that all files had disappeared from the Jupyter Lab Files view, and executed my process again to generate the file. The previous file contents displayed while I can see the updated file contents using less at the command line.

Appears to be a caching issue.

**Comment by fm75** [comment]
You have two options.
- Refresh the browser
- Use an entry that was added recently in the File menu to refresh the view of the file from disk.
This is an issue that was recently closed.

**Comment by fm75** [comment]
In Chrome, the browser refresh icon is the same as the icon used for "Refresh file list" in the Files view. The one in the files view only refreshes the files *listed* in the view. The browser refresh will work, though it is arguably non-intuitive to use it.

I am not not sure which issues mentioned this behavior or when it was fixed, but it was added somewhere in the 0.33 to 0.34.7 release.

[File, Open from path](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html?highlight=changelog)? It looks like 0.34.0 has it.

I know I checked on this one yesterday.

**Comment by DFuller134** [comment]
This is not the same issue as https://github.com/jupyterlab/jupyterlab/pull/5048. 

The file listing refreshes successfully, but the contents of the file does not change. Even after I deleted the offending file and my process recreated new files. I had to choose a new name for the file in order to see the update in Jupyter Lab when I could see the contents of the file from the command line just fine.

**Comment by fm75** [comment]
#5108 

Yes, it is a caching issue. 

AFAICT, it looks like the team is satisfied with the solution added to 0.34.

File, Reload file from disk. I just opened it on my laptop. It is in 0.34.7.

It worked when I tried it. I can't say that it made me super-happy, because you have to know that it works this way.

**Comment by jasongrout** [comment]
A more complete solution here involves changes beyond JupyterLab in the way the Jupyter Notebook server works in the back end, including watching for file changes and an ability to push messages from the server to the frontend about files. Those changes will come in time as we work on real-time collaboration and work on the Jupyter Server project.

**Comment by jasongrout** [comment]
@DFuller134 - I think in your version of JupyterLab, it's the "Revert File to Saved" File menu entry we are referring to. In more recent versions of JupyterLab, it may have been changed to "Reload ..." like @fm75 pointed out.

(Thanks @fm75 for your answers here on this issue!)

**Comment by DFuller134** [comment]
I'm on 0.32.1. I'll update.

**Comment by DFuller134** [comment]
UPDATE: I am starting to notice the issue in another application. Might be a filesystem issue. Thanks for your time.
