### ISSUE TITLE
Running Tab Enhancements

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#5286]
Moved over from https://github.com/jupyterlab/jupyterlab/issues/4858#issuecomment-403710676:

Currently the Running Sidebar displays Consoles/Notebooks under the heading Kernel Sessions however notebooks and consoles are just font-ends to a particular kernel so it would be more useful if the kernel was shown as the top-level element which could be expanded to show what front-ends (also editors?) were attached.

**Comment by dhirschfeld** [comment]
This bit me when I closed a console tab and then shutdown it's kernel. Unfortunately there was a notebook also attached which I wanted to keep open but with no indication in the Running Sidebar that they were linked I accidentally also killed my notebook session.

**Comment by dhirschfeld** [comment]
It would also be great to be able to see how much CPU/RAM each kernel was using

**Comment by krassowski** [comment]
This was implemented by #13851. A follow-up discussion on further improvements takes place in #15294.
