### ISSUE TITLE
jupyter notebook not working

### ISSUE THREAD

**Issue by emgrace1233** [jupyterlab/jupyterlab#5294]
HI! I dont know what I did to my file but now it looks like this:
<img width="872" alt="screen shot 2018-09-11 at 8 11 51 pm" src="https://user-images.githubusercontent.com/43193698/45399082-0aac7980-b604-11e8-8bc8-6cc449a024b4.png">

I dont know how to fix it!!!! how do I get it back to normal??? please please help!!

**Comment by dkleissa** [comment]
@emgrace1233 - The .ipynb file type is a JSON document...what you're seeing here is that document open in the **text editor**, not the notebook view. To fix, you should really just have to double click on the file in the jupyterlab file browser widget. 

If for some reason that doesn't work, you can right click on the file and select "notebook" to force it to open in the notebook view.

![image](https://user-images.githubusercontent.com/6224509/45401663-b3b49d80-b61f-11e8-9d79-136357449001.png)

**Comment by jasongrout** [comment]
Closing as answered.
