### ISSUE TITLE
Cannot open notebooks

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#5295]
I'm trying the latest version (0.34.9) of JupyterLab. I fails to open notebooks sometimes (no matter double click, right click -> Open/Open With or File -> Open from path...) on both Firefox (61.02) and Opera (55.0). Text files can be open normally. Refreshing the URL makes it work again for a while but then the same issue arise again. 

This is a critical issue that basically stops user from using JupyterLab.

**Comment by jasongrout** [comment]
Can you post one of these notebooks? Just checking, the same exact notebook runs in the classic notebook?

**Comment by jasongrout** [comment]
Are we talking about specific notebooks, or does the problem seen to randomly happen with different notebooks? Are there any errors in the js console or the server log?

**Comment by dclong** [comment]
@jasongrout The issue is random instead of on a specific notebook. 
1. If I don't use the JupyterLab/Hub server for a while, it works again. After I work in JupyterLab/Hub for about 5-10 minutes, the issue arises. 
2. If I refresh the URL, it works again but the same issue arises after 5-10 minutes. 
The same notebooks work in classic notebook.
I'll see whether I can post a notebook without any sense information later.

**Comment by dclong** [comment]
@jasongrout Sorry that the issue is probably due to holoviews library I'm using which has issues with the latest version of JupyterLab.

**Comment by jasongrout** [comment]
Thanks for following up. I'll close this then. Feel free to comment below or open a new issue if you still see an issue that you think is from jlab.
