### ISSUE TITLE
sidebar - separate default width from minimum width

### ISSUE THREAD

**Issue by ivanov** [jupyterlab/jupyterlab#5314]
For sidebar extensions, like the File browser, the minimum width also ends up the default width. We changed that to a variable and shrank it over in #5245, but it would be nice to have a default width be different from the minimum.

**Comment by jasongrout** [comment]
@ellisonbg - are you planning on working on this for 0.35? 

I dug into it a bit, and as far as I could tell in the time I had, we can't do this with the split panel we are using for the main area with the current Phosphor.

CC @sccolbert

**Comment by ellisonbg** [comment]
PR on the way.
