### ISSUE TITLE
Opening JupyterLab in the browser app mode

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5317]
In order to open JupyterLab (or the Jupyter Notebook) using a browser's application mode (i.e., without the address bar, etc.), you can do something like this on OS X (on different systems, you'll have to set that environment variable to the appropriate path).

```
BROWSER='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --app=%s' jupyter lab
```
You may also be able to, in your config file, register a new browser with that `--app` switch with the python webbrowser module.

**Comment by jasongrout** [comment]
Closing as answered. Feel free to post comments below if you have other tips for doing this.

**Comment by magesstrus** [comment]
The below link actually has a self-contained guide to  doing this. I have JupyterLab up & running now, with the exact same feel as a standalone application.
https://yoursdata.net/installing-and-configuring-jupyter-lab-on-windows/

**Comment by oscar6echo** [comment]
You can also add an `-incognito` flag if you want to isolate your JupyterLab thereby avoid making all your browser's state (cookies, local storage, etc) available to JupyterLab+extensions.

```
# macOS
c.LabApp.browser = '/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome -incognito --app=%s'

# Windows
c.LabApp.browser = '"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" -incognito --app=%s'
```
