### ISSUE TITLE
Widgets cannot be displayed in 0.34.10

### ISSUE THREAD

**Issue by w-hc** [jupyterlab/jupyterlab#5322]
Python 3.6.6 :: Anaconda, Inc
Jupyter-lab:  0.34.10
ipywidgets  '7.4.1'
```python
from ipywidgets import widgets
w = widgets.IntSlider()
display(w)
```
The very simple script above would not work. The output is 
![screen shot 2018-09-15 at 13 39 34](https://user-images.githubusercontent.com/17956191/45589527-d0392a00-b8ec-11e8-80ee-952b1a5c8789.png)

**Comment by ian-r-rose** [comment]
Do you have the `@jupyter-widgets/jupyterlab-manager` labextension installed?
```bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

**Comment by w-hc** [comment]
Thank you so much for the speedy reply.
I was unaware that the lab extension system needs to be separately updated.
I thought that by running 
```bash
conda update --all
```
The extensions will be updated together.
You may close the issue.

**Comment by ian-r-rose** [comment]
Glad you got it working!
