### ISSUE TITLE
Printing with carriage return is not working as expected

### ISSUE THREAD

**Issue by tin-trong-nguyen** [jupyterlab/jupyterlab#5326]
Printing with carriage return in JupyterLab returns nothing
![lab](https://user-images.githubusercontent.com/20536852/45605643-9725c480-ba68-11e8-9c84-40e8ae5c2f80.png)

While it works as expected in Notebook
![notebook](https://user-images.githubusercontent.com/20536852/45605645-9725c480-ba68-11e8-8f29-3eff4b9938c8.png)

```
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
jupyterlab==0.34.8
jupyterlab-launcher==0.13.1
```

**Comment by opersvik** [comment]
A simple workaround that gives the expected behavior is `print("\r%d" % i, end='')`.

It appears that \r always clears the output in Jupyter Lab.

**Comment by gahaalt** [comment]
Unluckily such method does not produce equivalent results.

For example I used to print small trainings report with end='\r', and then I wanted the bigger report to cover it. With your solution, not only the last small report stays untouched, but also the big report is covered by first small.

Is there any workaround? I read about someone that used some source code from Jupyter Notebook and it worked, unluckily I don't know how to do such a thing. I would like to use Jupyter Lab on daily basis and carriage return is important for me.

**Comment by jasongrout** [comment]
Previous issues/discussion about this: https://github.com/jupyterlab/jupyterlab/issues/1104, https://github.com/jupyterlab/jupyterlab/pull/2761, https://github.com/jupyterlab/jupyterlab/issues/3718, https://github.com/jupyterlab/jupyterlab/pull/3882, https://github.com/jupyterlab/jupyterlab/pull/4045

**Comment by shijianjian** [comment]
@jasongrout  Thanks for these. But none of the discussions has fixed the problem. The problem occurs when I was calling a written package outside the Jupyter, which means I do not want to alter the outside codes. Is there anything I can do within the range of the notebook?

Something like ```%matplotlib inline``` is appreciated.

**Comment by jasongrout** [comment]
@shijianjian - some of those tickets I referenced above were about fixing the jlab behavior. Can you see if things are fixed for you in the latest prerelease, version 1.0alpha1?

**Comment by jasongrout** [comment]
JupyterLab 1.0a1 has now fixed the problem in the original description:
<img width="264" alt="screen shot 2019-02-19 at 7 30 48 am" src="https://user-images.githubusercontent.com/192614/53026736-56b3e380-3418-11e9-8a87-0c789e26b0ea.png">

I think this issue can be closed as resolved. @shijianjian, can you test your issue in JupyterLab 1.0a1 (the latest prerelease), which can be installed in a new environment with `pip install jupyterlab --pre`, or you can test it in a [live binder](https://mybinder.org/v2/gh/jupyterlab/jupyterlab/master?urlpath=lab-dev/) in your browser.

**Comment by jasongrout** [comment]
@shijianjian - if you still see the issue in 1.0a1, can you open a new issue describing exactly what is happening, with a small code snippet reproducing the problem so we can track it down?
