### ISSUE TITLE
Jupyter lab file browser is terrible.

### ISSUE THREAD

**Issue by matthewdeancooper** [jupyterlab/jupyterlab#5329]
This has to be the slowest way to look for files that i have seen. What the project needs is a fuzzy file finder, a fuzzy go-to, and a fuzzy project searcher that renders .ipy files as something readable.

**Comment by dsblank** [comment]
Not a very useful issue title, or description. Suggest editing title to "Suggestions for making file browser better" and then actually making some suggestions, without snarky comments (which research shows doesn't seem to inspire volunteers from open source projects).

**Comment by afshin** [comment]
We appreciate feedback. Please refer to the [Project Jupyter Code of Conduct](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md) to re-file this issue.

**Comment by matthewdeancooper** [comment]
Thanks dsblank and afshin.  It was something typed up and sent quickly without much consideration.  I will try to rephrase the issue in a more productive way.

**Comment by jasongrout** [comment]
Thanks!
