### ISSUE TITLE
Upon initialization, JupyterLab terminal fails to execute standard commands

### ISSUE THREAD

**Issue by jimcost** [jupyterlab/jupyterlab#5332]
<img width="889" alt="screen shot 2018-09-17 at 1 13 02 pm" src="https://user-images.githubusercontent.com/6710629/45644632-6d29cd80-ba7b-11e8-96d2-064aa5f611e6.png">

I'm on a Mac (High Sierra, Version 10.13.6). I installed JupyterLab through `conda`.

To solve it, I followed the advice given [https://stackoverflow.com/questions/12338233/shell-init-issue-when-click-tab-whats-wrong-with-getcwd](url); stating my directory doesn't exist anymore, therefore change to an existing one via `cd; cd -`

That solved my issue.

The directory I point to is on a network attached storage. Any thoughts? Does JupyterLab create temporary directories?

(Thank you all for your efforts!)

**Comment by blink1073** [comment]
Hi @jimcost, I think this is related to https://github.com/jupyterlab/jupyterlab/issues/3094.  We are not creating any empty directories afaik.  Here's the code that's used by the server to spawn [terminals](https://github.com/jupyter/notebook/blob/master/notebook/terminal/__init__.py#L17), and the [code]( https://github.com/jupyter/terminado/blob/master/terminado/management.py#L164) that is calling.
