### ISSUE TITLE
Allow text highlighting in Markdown

### ISSUE THREAD

**Issue by kenjioman** [jupyterlab/jupyterlab#5337]
Allow text highlighting in Markdown cells, such as is described in [this SO post](https://stackoverflow.com/a/36039773).

Currently, I try it and it doesn't seem to do anything.

And sorry if I missed it in the list of issues! (I searched, but didn't see it mentioned).

Running jupyterlab 34.9

**Comment by jasongrout** [comment]
Thanks for filing the issue!

This is fixed in master (presumably similar to #1812):

```
This is marked: <mark>marked text</mark>
```
gives 
<img width="214" alt="screen shot 2018-09-18 at 1 37 33 pm" src="https://user-images.githubusercontent.com/192614/45715000-058d8400-bb48-11e8-9573-aedc53a975ed.png">

**Comment by kenjioman** [comment]
Ok, glad to hear it's fixed, and I look forward to when it's rolled out as a release!  And, thanks for letting me know!
