### ISSUE TITLE
Copyright year needs update to 2018 in jupyterlab splash screen

### ISSUE THREAD

**Issue by mabayona** [jupyterlab/jupyterlab#5346]
![copyright-2015](https://user-images.githubusercontent.com/17231/45826396-b6d11d00-bcf4-11e8-93d8-b82a4b881f1e.JPG)

**Comment by mabayona** [comment]
Ok with conventions. But leaving it as is makes it look and somehow abandonware. :(

**Comment by ian-r-rose** [comment]
Our copyright notices in the source files don't contain years. Are there some guidelines documented somewhere @jasongrout?

**Comment by jasongrout** [comment]
I'll post a link when I'm near a computer. The relevant links might be in the commit message for that text.

**Comment by jasongrout** [comment]
See the commit note that made this change for further justification: https://github.com/jupyterlab/jupyterlab/commit/30c5ff152a8a641910374ee358a09c2cc5019eaa

**Comment by jasongrout** [comment]
(Closing as resolved, since I made the updates based on project-wide discussion. However, if there are still strong feelings about this, feel free to keep commenting, and we should probably raise the issue again at a project level.)

**Comment by jasongrout** [comment]
(In particular, on the copyright years, I followed the consensus linked in the governance issue linked in the commit noted above, namely https://github.com/ipython/ipython/pull/1644)
