### ISSUE TITLE
Dark scheme: Improve code completion dropbox selector contrast

### ISSUE THREAD

**Issue by alexveden** [jupyterlab/jupyterlab#5349]
**Describe the bug**
Could you please make more contrast selection row in code completion dropbox (at TAB press)?

![image](https://user-images.githubusercontent.com/18488560/45863794-d2860300-bd88-11e8-8888-841a2765435f.png)

- OS: Ubuntu LTS 16.04
- Browser Chrome Version 69.0.3497.100
- JupyterLab 0.34.11

**Comment by blink1073** [comment]
Thanks for the report!

**Comment by tgeorgeux** [comment]
If on select we change the font color on focus to "--jp-ui-inverse-font-color1" it will show up more clearly.

**Comment by jasongrout** [comment]
Would you mind adding this comment to the PR as a review comment: #5364 ?
