### ISSUE TITLE
Close Tab Command

### ISSUE THREAD

**Issue by krlng** [jupyterlab/jupyterlab#5362]
I miss a command to close the active tab, I only find options to close other tabs:
![image](https://user-images.githubusercontent.com/1107509/45917508-f0329580-be78-11e8-9a92-ca112445804f.png)

Of course, you can close every tab using the x, but a command would be helpful to assign a shortcut on it afterwards.

**Comment by Songyu-Wang** [comment]
This should be whatever command that is currently mapped to `ctrl+Q` (Depends on the tab type)

**Comment by blink1073** [comment]
Hi @krlng, it is available, as "Close <name>", where name depends on the current widget, cf https://github.com/jupyterlab/jupyterlab/blob/426c7fe6c7c0f3914e6201f29a806118ffdab34b/packages/docmanager-extension/src/index.ts#L265.

<img width="303" alt="image" src="https://user-images.githubusercontent.com/2096628/45927035-6fb07b00-bef2-11e8-834e-f43e1b13d1c7.png">

I think a problem with calling the current document a "tab" is that you might be in single document mode.  Similarly, we have "Close all Widgets" which applies in both single document mode and across tab groups in the main area.

**Comment by krlng** [comment]
Ah okay, I understand . I still find it confusing from the user's point of view to have different commands for just closing the active Tab, Window or how ever you want to name it. As a user I don't really think about what type of document I have in front of me, I just want to close whatever I want to see. 

Still, since there is a shortcut which is the same for all types I am fine :)
