### ISSUE TITLE
NotebookWidgetFactory can set default toolbar

### ISSUE THREAD

**Issue by futurist** [jupyterlab/jupyterlab#5363]
I want to set my own toolbars when init a notebook widget, looked into the source and found it's [hard coded](https://github.com/jupyterlab/jupyterlab/blob/562f485a6f03ed75004acbb9c2e73a81d1cc0f0b/packages/notebook/src/widgetfactory.ts#L86) in `NotebookWidgetFactory`.

Is there any way to do this right? or it's should be a feature?

**Comment by jasongrout** [comment]
It looks like (a) you can't remove toolbar items with the toolbar api and (b) you're right that the default buttons are hardcoded in the notebook panel. Perhaps the default buttons should be abstracted out to a plugin? Would you like to help with a PR to do that?

**Comment by futurist** [comment]
Besides a plugin, I think the toolbar can be set:

#### 1. add `toolbar` option in `NotebookWidgetFactory.IOptions`, like below code: 

```js
interface ToolbarItem {
    [name: string]: Widget;
}
let myToolbar: ToolbarItem[] = CreateMyToolbar();
let wFactory = new NotebookWidgetFactory({
    name: 'Notebook',
    toolbar: myToolbar,  // fallback to DefaultToolbar
    ... ...
});
```

#### 2. add `toolbar` option in `DocumentRegistry.IContext`, like below definition:
```js
readonly toolbar?: ToolbarItem[];
```
This enables different registry can have different toolbar, like in markdown context the toolbar will have `h1`, `h2`, `bold` buttons etc.

The 1 and the 2 can also be combined, the 1 mostly as fixed buttons like `save`, `run` etc, and the 2 is mostly dynamic.

**Comment by bollwyvl** [comment]
> you can't remove toolbar items with the toolbar api

Putting my Evil Hat on:
```ts
    let children = [...(panel.toolbar.children() as any)._source];
    for (let i = 0; i < children.length; i++) {
      panel.toolbar.layout.removeWidget(children[i]);
    }
    panel.toolbar.insertItem(666, '', evilButton);
``` 

problem is, you aren't guaranteed to "win" (other plugins can come along after you), so yeah, something a bit more structured might make sense.

**Comment by jasongrout** [comment]
> Putting my Evil Hat on:

Yep. I carefully chose my words: "toolbar api" :).

**Comment by jasongrout** [comment]
> It looks like (a) you can't remove toolbar items with the toolbar api

I was wrong. See https://github.com/jupyterlab/jupyterlab/pull/5395#issuecomment-425333368
