### ISSUE TITLE
UI: cell [*] asterisk is not reset if exception was thrown before

### ISSUE THREAD

**Issue by alexveden** [jupyterlab/jupyterlab#5366]
I've noticed a pretty annoying bug, especially for long notebooks.

When we run long-running cells or entire notebook the [*] marks at the left side of cells are not reset if it was an exception somewhere in prior cells.

![image](https://user-images.githubusercontent.com/18488560/45927517-38b78500-bf45-11e8-88f5-f132317bcca1.png)

**Desktop (please complete the following information):**

- OS: Linux Mint 18.3
- Browser chrome 69.0
- JupyterLab 0.34.11

**Comment by blink1073** [comment]
Thanks for the report, @alexveden!

This could be handled by catching an error in run promise and clearing the `executionCount` in the selected cells that don't have a numerical `executionCount`:

https://github.com/jupyterlab/jupyterlab/blob/3ea6a39264f44694febc9357578ffcb43b4f1780/packages/notebook/src/actions.tsx#L1411

**Comment by jasongrout** [comment]
This was not solved by #5423. Perhaps there is a similar solution in the console code, though?

**Comment by jasongrout** [comment]
No, my mistake. #5423 *did* solve this. It didn't solve #4916.
