### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ankitsharma07** [jupyterlab/jupyterlab#5367]
How to update jupyterlab to latest build number??

**Comment by blink1073** [comment]
Hi @ankitsharma07, do you mean the latest stable release or the current master?

For latest stable, you can run `pip install -U jupyterlab` (or `conda install jupyterlab`), and optionally run `jupyter lab build` if you have extensions.

For building against master, see https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#setting-up-a-development-environment.
