### ISSUE TITLE
Expose Run Selected Cell and All Below handle for keyboard shortcut creation

### ISSUE THREAD

**Issue by discdiver** [jupyterlab/jupyterlab#5371]
_Run Menu_ has _Run Selected Cell and All Below_ as an option. But it doesn't have a keyboard shortcut and I don't see a way to create one because the handle is not listed in _Settings-> System Defaults_ -> _Keyboard Shortcuts_ . 

Kindly suggest the name of the handle be included and/or a default keyboard shortcut created.

Thank you for all your work on jupyterlab!

**Comment by discdiver** [comment]
Thanks @ian-r-rose. Here's what the full working code looks like if anyone find this:

` 
{
   "notebook:run-all-below": {
      "command": "notebook:run-all-below",
      "keys": [
        "Shift D"
      ],
      "selector": ".jp-Notebook:focus",
      "title": "Run All Below",
      "category": "Notebook Cell Operations"
    }
}
`

**Comment by ian-r-rose** [comment]
Glad you got it working @discdiver! Closing as answered.
