### ISSUE TITLE
Old matplotlib ipympl figures not getting released at cell refresh

### ISSUE THREAD

**Issue by jkrumbiegel** [jupyterlab/jupyterlab#5373]
If I create a figure like

`fig = plt.figure()`

using

`%matplotlib notebook`

and execute the cell 20 times, I get a warning that twenty figures have been opened. Obviously the old figures hang around in the background, even though there is no reference to them anymore. This can get quite memory demanding if the figures have a lot of content and I iteratively refine them.

I've been using a workaround with

    if 'fig' in locals():
        plt.close(fig)
    fig = plt.figure()

But this is pretty annoying if there are many cells like that. Is this a matplotlib problem because of their caching in the background or a jupyter lab problem because it doesn't release?

Thanks for any input :)

**Comment by jasongrout** [comment]
`%matplotlib notebook` doesn't work in JupyterLab, right? I get `Javascript Error: IPython is not defined`

**Comment by jasongrout** [comment]
```python
%matplotlib notebook
from matplotlib import pyplot as plt
fig = plt.figure()
```
gives an error for me in JupyterLab.

**Comment by jasongrout** [comment]
(it sounds like the error you are mentioning is a kernel error, which would mean it has nothing to do with JupyterLab and has to do with matplotlib or whoever is providing the rendering backend for matplotlib.)

**Comment by jkrumbiegel** [comment]
Oh I'm sorry, I typed notebook from old muscle memory, I meant
`%matplotlib ipympl`

**Comment by jkrumbiegel** [comment]
And this is the warning

RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

**Comment by jasongrout** [comment]
Thanks, that makes more sense. This is a warning from ipympl. The discussion about it is over at https://github.com/matplotlib/jupyter-matplotlib/issues/4. It looks like the discussion there has stalled - perhaps you'd like to start it up again, or at least post your workaround?

**Comment by jasongrout** [comment]
(Closing here so we can move the discussion over to https://github.com/matplotlib/jupyter-matplotlib/issues/4)
