### ISSUE TITLE
JupyterLab cannot save notebook named "SuperStats"

### ISSUE THREAD

**Issue by i-am-david-fernandez** [jupyterlab/jupyterlab#5386]
I have a notebook that I renamed to `SuperStats` (with the obligatory `.ipynb` extension). JupyterLab accepts this name, but thereafter refuses to save the notebook, producing an alert/messagebox with the following:

```
File Save Error for SuperStats.ipynb
NetworkError when attempting to fetch resource.
```

I've tried the names `Super`, `SuperS`, `SuperSt`, `SuperStat` and `SuperStatsy`, which are all fine. In addition to not being able to save, other operations (such as attempts to rename via JupyterLab) also fail with the same message. After renaming outside of Jupyter (e.g., via a file manager), things are ok, so it doesn't appear to be anything to do with the notebook itself. Indeed, I tried with a new/empty notebook and the same behaviour is exhibited.

There may be other names that cause issues, but I've not come across any others yet. If there are limitations on what names JupyterLab accepts (though I can't think of a good reason for not accepting anything that is valid within the underlying filesystem), then in the least JupyterLab should reject the name when it is entered via the GUI, not allow it then fail. It's especially bad if, as I did, one renames, continues working and only later discovers that saving/renaming is not possible. Fortunately, my changes were small so I could reproduce them later, but this is certainly not good behaviour.

I'm running JupyterLab on Windows 10 via anaconda.

**Comment by blink1073** [comment]
Hi @i-am-david-fernandez, does the same notebook save properly in the classic notebook interface?

**Comment by i-am-david-fernandez** [comment]
Thanks for the rapid response, @blink1073 .

The issue exists in the classic notebook also, but it turns out this is all at my end. I was using Firefox initially, so tried first in a private tab, then in Edge and in a private Chrome tab. The issue only occurred in Firefox, and I narrowed it down to the `uBlock Origin` ad-blocking add-on, specifically an entry in the `EasyPrivacy` blacklist: `/superstats.` So, the issue can be resolved by disabling `uBlock` for the local Jupyter site.

Apologies for not digging deeper before posting. :(

**Comment by blink1073** [comment]
No worries, glad you got sorted!
