### ISSUE TITLE
Move the `share` command into its own plugin to allow it to be overridden.

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#5388]
In order to allow custom building of URLs in the file browsers "Copy Shareable Link" functionality, we should move the `'filebrowser:share-main'` command's implementation and addition to the command registry into a small plugin that can be disabled in specialized environments.

cf. https://gitter.im/jupyterlab/jupyterlab?at=5bacc22e56877c463a90c648
cc: @minrk

**Comment by minrk** [comment]
Thanks! cross-ref https://github.com/jupyterhub/jupyterhub/issues/2017 where it would be handy to make 'shareable link' copy the `/hub/user-redirect` link instead of the local-only url

**Comment by vidartf** [comment]
Would it be best to have this as a separate extension, or a separate plugin only (keeping it in the original extension)?

**Comment by afshin** [comment]
Sorry for being imprecise @vidartf, I meant a `JupyterLabPlugin` and should have called it a plugin. I updated the issue.
