### ISSUE TITLE
React error in Extension Manager

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#5392]
React currently throws a warning for rendering the extension manager because the `<CollapsibleSection>` component is missing a `key` prop. We should fix this.

Marking as a good first issue. The react documentation describes the fix [here](https://reactjs.org/docs/lists-and-keys.html#keys), and the component in question can be found [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/extensionmanager/src/widget.tsx#L353).

```
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <CollapsibleSection>. See https://fb.me/react-warning-keys for more information.
    in ListView warning.js:33
```

**Comment by nycuni** [comment]
I'll try to work on this (10/2018 Sprint)

**Comment by Keyairra-S-Wright** [comment]
I am going to begin working on this as well.
