### ISSUE TITLE
Test label application

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#5394]
cc @Carreau

**Comment by blink1073** [comment]
@meeseeksdev tag "good first issue"

**Comment by blink1073** [comment]
@meeseeksdev tag "status:Work in Progress"

**Comment by blink1073** [comment]
@meeseeksdev tag status:Work in Progress

**Comment by blink1073** [comment]
Success, thanks @Carreau!

**Comment by Carreau** [comment]
Yeah, I could improve the heuristic to detect tags, like stipign quotes and using difflib to find the closest.

PR welcome.

Code is [here](https://github.com/MeeseeksBox/MeeseeksDev/blob/master/meeseeksdev/meeseeksbox/commands.py#L695-L705)

**Comment by blink1073** [comment]
I'd like to add handling quotes, probably won't delve into difflib ;).
