### ISSUE TITLE
display(Javascript("""...""")) in jupyterlab notebook does not match behaviour in classic notebook.

### ISSUE THREAD

**Issue by jcoady** [jupyterlab/jupyterlab#5404]
In jupyterlab when I execute the following in a notebook cell

display(Javascript("""var a=1"""));

I get the following in the output cell

<IPython.core.display.Javascript object>

However if I execute
display(Javascript("""var a=1"""));

in a classic notebook cell then there is nothing in the output cell. It just executes the javascript and doesn't display anything. Is it possible to get the jupyterlab notebook to also display nothing for display(Javascript("""var a=1""")) just like in the classic notebook case?

Here is a link to the code lines causing this.

https://github.com/jupyterlab/jupyterlab/blob/39e4b6747803ca681a417c57a8c2f99c3eab442c/packages/javascript-extension/src/index.ts#L26-L32

My setup is 

Windows 10
Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Jupyterlab 0.34.11

**Comment by jasongrout** [comment]
CC @gnestor, who wrote the javascript extension initially. Grant, what was the reasoning for putting the text/plain on the page if there was no output?

**Comment by jasongrout** [comment]
Grant said he would revert the behavior back to the classic notebook behavior.
