### ISSUE TITLE
Change Phosphor tab dragging behavior

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#5406]
I wanted to bring attention to the issue I opened on the Phosphor repo about tab docking.

https://github.com/phosphorjs/phosphor/issues/360

I am not 100% sure where the line is drawn between phosphor's and jupyterLab's execution of these so if I need to duplicate parts of this let me know please.
@Zsailer @jasongrout @afshin @blink1073 @saulshanabrook @ian-r-rose @sccolbert 

Thanks everybody have a great weekend!

**Comment by ellisonbg** [comment]
Thank you @tgeorgeux and @Zsailer for working on this. We went over the main results this afternoon and it looks like there are some actions we will be able to take based on this. One though - maybe @tgeorgeux you can present this at the team meeting next Wednesday to bring other folks up to speed?

That would be a good way to get into the question of implementation.

**Comment by ian-r-rose** [comment]
I've had an open PR for this on phosphor for a while.

**Comment by jasongrout** [comment]
For reference, the open PR in phosphor is https://github.com/phosphorjs/phosphor/pull/365

I commented there on several ways to move forward with pushing these changes to a jlab prerelease.

I think we really need to have a prerelease with these changes so that we can test them out a bit before a final 1.0 release.

**Comment by saulshanabrook** [comment]
This is blocked on merging the PR into phosphor and and putting out a release. We also added a comment to ask for a few changes on that PR before it is merged: https://github.com/phosphorjs/phosphor/pull/365#issuecomment-494896649
