### ISSUE TITLE
Reload read-only files from disk if they have changed

### ISSUE THREAD

**Issue by TheDataLeek** [jupyterlab/jupyterlab#541]
## Summary

For 1.0 we could implement this as a refresh button or command.
## Original comment

Feature request:

When a file changes on disk reload it? Currently any file (if changed on disk) remains the same, for instance if I pull up an image in a pane, and then change the image, it doesn't update.

**Comment by willzfarmer** [comment]
Discussion is probably warranted around this (if not already done), as possibly with text(/editable) files you'd want to prompt the user if they wanted to reload or overwrite.

**Comment by blink1073** [comment]
Hi @willzfarmer, thank you for the suggestion.  Notes from a technical perspective: we can periodically fetch just the metadata about each open file, and compare `last_modified` timestamps to determine if it has changed on disk.

**Comment by ellisonbg** [comment]
Right now this works for files that are saving (text files, notebooks), but doesn't work for read-only viewers. Getting this to work for read-only viewer would be a new feature.
