### ISSUE TITLE
Within cell search leads to confusion and accidental code deletion.

### ISSUE THREAD

**Issue by mikemac8888** [jupyterlab/jupyterlab#5411]
**Describe the bug**
The new within cell search changes default search behaviour existing in most document based programs including Jupyter Notebook. Now searching for multiple instances of the same symbol leads to accidental code deletion.

**To Reproduce**

1. Press Apple + F to search for a symbol. For example "def".

2. Press Enter first time. This finds the first instance of "def".

3. Press Enter second time expecting to find next instance of "def". This deletes the first instance of "def" and adds a newline.

**Additional notes**

Most computer editing programs work from a document search perspective. I can't think of any that force search within a small section of a document. Thus the average user will be confused by this behaviour.

The option to press Apple + F twice is not an acceptable alternative. After months of using Jupyter Lab I still make this error daily.

Please provide an option to disable this within cell search mode.

Thanks

**Comment by blink1073** [comment]
Hi @mikemac8888, we're tracking this in https://github.com/jupyterlab/jupyterlab/issues/1074, which I've just moved to the 1.0 milestone.
