### ISSUE TITLE
Rendermime plugins created from rendermime extensions don't work

### ISSUE THREAD

**Issue by AlbertHilb** [jupyterlab/jupyterlab#5418]
Trying to open a mime document from the file browser (for example a PDF file or a markdown file preview), nothing happens except for console showing:

```
TypeError: option.toolbarFactory is not a function
```

The problem is in [createRendermimePlugin](https://github.com/jupyterlab/jupyterlab/blob/ef3f3e9158738ae50184ec465c1db826e9513ca3/packages/application/src/mimerenderers.ts#L143) function.

Cheers

**Comment by ian-r-rose** [comment]
Thanks for the report @AlbertHilb. Is this on current `master`, or with a released version? If the former, I wonder if it could be related to #5398.

**Comment by AlbertHilb** [comment]
It is on current `master`.

**Comment by jasongrout** [comment]
Thanks, I'm seeing it too.

**Comment by jasongrout** [comment]
Looks like https://github.com/jupyterlab/jupyterlab/blob/ef3f3e9158738ae50184ec465c1db826e9513ca3/packages/application/src/mimerenderers.ts#L144 needs to handle the case where option.toolbarFactory is undefined.
