### ISSUE TITLE
Variable Inspector

### ISSUE THREAD

**Issue by ankitsharma07** [jupyterlab/jupyterlab#5421]
I love working in Jupyter Lab. Is there a way where I can see what data my variables are storing? As it is quite necessary to see the variable's content while coding.

**Comment by ian-r-rose** [comment]
Hi @ankitsharma07, you can open an inspector panel by selecting "Open Inspector" from the command palette, or using the keyboard shortcut `Cmd/Ctrl I`.

**Comment by jasongrout** [comment]
For a *variable* inspector, you can try out the variable inspector someone developed, mentioned at #443.

**Comment by jasongrout** [comment]
A third-party extension may be interesting to you: https://github.com/lckr/jupyterlab-variableInspector

**Comment by ian-r-rose** [comment]
Ah, thanks @jasongrout, I misunderstood the question.

**Comment by dhirschfeld** [comment]
@ian-r-rose - you're not the first person to make that mistake. IME "inspector" is ~always used to mean a variable inspector. The actual inspector as implemented in JupyterLab would be more commonly referred to as a help browser.

I'd actually recommend renaming the current inspector to Help Browser to avoid this confusion in future.

**Comment by ccordoba12** [comment]
@dhirschfeld, that's what we did in Spyder 3 with our *Object Inspector*.

**Comment by jasongrout** [comment]
Closing as answered.
