### ISSUE TITLE
Check for yarn duplicates

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5434]
Using yarn-tools, we can see we have some redundancy in the yarn.lock file:

```
% yarn-tools list-duplicates yarn.lock
Package "@babel/code-frame" wants ^7.0.0-beta.35 and could get 7.0.0-beta.51, but got 7.0.0-beta.46
Package "invariant" wants ^2.2.2 and could get 2.2.4, but got 2.2.3
Package "istanbul-lib-coverage" wants ^1.2.0 and could get 1.2.1, but got 1.2.0
Package "istanbul-lib-instrument" wants ^1.7.3 and could get 1.10.1, but got 1.9.2
Package "node-fetch" wants ^2.1.2 and could get 2.2.0, but got 2.1.2
Package "vega-typings" wants * and could get 0.3.46, but got 0.3.40
Package "vega-typings" wants ^0.3.4 and could get 0.3.46, but got 0.3.40
```
We can fix these with `yarn-tools fix-duplicates`, but we should really make this a continuous test. One problem is that `yarn-tools list-duplicates` doesn't exit with an error code when there are duplicates, so it's not easy to just put in a test as a failure somewhere.

**Comment by jasongrout** [comment]
I took care of these specific duplicates over in #5433. However, I'm leaving this issue open as an issue for adding the duplicate check to at least travis, if not the linting command.

**Comment by blink1073** [comment]
Created a new `tag:Dev Ops` label because it deserves its own label :wink:

**Comment by blink1073** [comment]
> I think we could improve yarn-tools a lot, for example not requiring a temporary file, and exiting with an  > error code when it detects duplicates so we can use it in automated testing.

cf https://github.com/jupyterlab/jupyterlab/pull/5431#issuecomment-426930352

**Comment by blink1073** [comment]
Existing workflow:

```
git clean -dfx
yarn install
yarn check
yarn-tools fix-duplicates yarn.lock > a
mv a yarn.lock
git clean -dfx
yarn install
```

**Comment by krassowski** [comment]
I think this can be closed because as of https://github.com/jupyterlab/jupyterlab/pull/14498 we are using `yarn-berry-deduplicate` on CI - please reopen if needed.
