### ISSUE TITLE
Add user tagging to Contributors Guide

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#5435]
Users without commit rights to the repo can now use `@meeseeksdev tag foo "fizz buzz"` to apply labels to issues.  We should mention this in contributing.md.

**Comment by blink1073** [comment]
See https://groups.google.com/forum/#!topic/jupyter/F8rQhU1Tzrc, where @Carreau unveiled the feature.  Thanks Matthias!

**Comment by blink1073** [comment]
@meeseeksdev tag type:Enhancement

**Comment by Carreau** [comment]
You need to add a .meeseeksdev config file to the repo for this to be possible. :-)

**Comment by blink1073** [comment]
Ah, cf https://github.com/ipython/ipython/blob/master/.meeseeksdev.yml.  Thanks for the pointer!

**Comment by Carreau** [comment]
or https://github.com/meeseeksmachine/test1/blob/master/.meeseeksdev.yml

you can set extra permissions on a per-user basis (like closing, reopening issues)...

**Comment by krassowski** [comment]
Could we get an example showing how to add the `tag:x`, `documentation:y` tags?
Should these go with or without quotation marks?

I just got [awwed byt the bot](https://github.com/jupyterlab/jupyterlab/pull/5586#issuecomment-435710162) for doing something wrong, though I am not sure what was wrong exactly...

Here is another example of the bot expressing it's difficulty in understanding the user: https://github.com/jupyterlab/jupyterlab/issues/5583#issuecomment-435661843.

**Comment by blink1073** [comment]
Ah, there's something wrong with the parsing of quoted labels.  We end up with an extra empty label that tries to get applied.  The bug was introduced here: https://github.com/MeeseeksBox/MeeseeksDev/pull/31.

**Comment by krassowski** [comment]
Can we also untag the issues?

**Comment by blink1073** [comment]
Yep, you should be able to use the untag command: https://github.com/jupyterlab/jupyterlab/blob/master/.meeseeksdev.yml#L6
