### ISSUE TITLE
Cancel button when creating a new console

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#5446]
What do you think about adding a Cancel button the "Select Kernel" popup that is created in at least two situations:  

### Create Console for Editor

![cancel_console](https://user-images.githubusercontent.com/591645/46559751-8c38b400-c8f1-11e8-8104-bb4488cbddee.gif)

### File > New  > Console

![cancel_console_2](https://user-images.githubusercontent.com/591645/46560044-914a3300-c8f2-11e8-8fd2-252c7ae868b0.gif)

It happens from time to time as a mistake, for example with third-party extensions that add an entry to the context menu right below "Create Console for Editor".

The workaround is to click on "Select" and create the console, then go to the Running tab to shut it down.

But since the cancel option is available in other contexts (when switching kernels for example), maybe that's something that can be reused with low effort?

**Comment by blink1073** [comment]
Hi @jtpio, I think that sounds fair, here is where the dialog is defined:

https://github.com/jupyterlab/jupyterlab/blob/40b379aa73e73a70d649fc86637d7533a95693e5/packages/apputils/src/clientsession.tsx#L592

**Comment by blink1073** [comment]
Should I assign this to you :wink:?

**Comment by jtpio** [comment]
Yes please, I would like to tackle this one!

**Comment by ian-r-rose** [comment]
The `CANCEL` button was actually removed deliberately in #4596, for reasons similar to what you state here @jtpio. That dialog is for kernel selection, and canceling it doesn't cancel console creation, but merely the selection of the kernel. So if you cancel you still get a console, but with no active kernel.

People were finding that confusing (and they were not wrong!), so we removed the initial cancel button as a relatively simple way to paper over this. I took a crack at a different approach that disposes of a console/notebook if no kernel is selected (#4440), but we abandoned it at the time as too complicated.

I would have some interest in helping resurrect #4440 if you are interested @jtpio, but I think re-adding the initial `CANCEL` will not do what you are looking for. Also pinging @ellisonbg who was involved in these previous discussions.

**Comment by jtpio** [comment]
Thanks @ian-r-rose for the context and the pointers.

In this case what we would expect from a cancel button is the cancellation of the whole console creation flow, meaning the console itself and the kernel selection. This would also apply when creating a new notebook. I agree it is confusing when only the kernel selection is canceled.

In the end it is more of a "nice to have" and we can surely stick with the current behavior if the implementation details are too involved or complicated.

**Comment by jtpio** [comment]
> The workaround is to click on "Select" and create the console, then go to the Running tab to shut it down.

Closing as there is now a "No Kernel" button to not start a kernel. So a Cancel button might not really be needed: 

![image](https://user-images.githubusercontent.com/591645/109469264-18714600-7a6e-11eb-83b4-ce5a71a1477f.png)
