### ISSUE TITLE
Does Jupyterlab 0.35 require python>=3.7?

### ISSUE THREAD

**Issue by mabayona** [jupyterlab/jupyterlab#5448]
When installing jupytelab 0.35 with conda:

conda install -c conda-forge jupyterlab=0.35

results in:

UnsatisfiableError: The following specifications were found to be in conflict:
  - jupyterlab=0.35 -> python[version='>=3.7,<3.8.0a0']
  - python=3.6
Use "conda info <package>" to see the dependencies for each package.

**Comment by blink1073** [comment]
Hi @mabayona, it takes a while for all of the packages to be available on conda-forge.  For instance, both the py36 and py37 packages for windows just showed up 30 minutes ago. 

https://anaconda.org/conda-forge/jupyterlab/files

**Comment by jasongrout** [comment]
Note that those are JLab 0.34 windows packages that showed up. JLab 0.35 packages are on their way still.

**Comment by ian-r-rose** [comment]
Python 3.6 builds are now available on conda-forge.
