### ISSUE TITLE
Is there some way to set a CDN url to host the static fiels

### ISSUE THREAD

**Issue by eoinmurray** [jupyterlab/jupyterlab#5449]
I've asked a few times on gitter but didn't get an answer. 

I can see that the jupyterlab_server can take a public_url which can be a CDN url [1], but I can't for the life of me figure out how to set it, in jupyter_notebook_config.py, or other.

Is there some straight forward way to get jupyterlab to host the javascript, css and images files from  a CDN, its for speed as I deploy lab servers for a lot of users?

[1] https://github.com/jupyterlab/jupyterlab_server/blob/master/jupyterlab_server/handlers.py#L113

**Comment by blink1073** [comment]
Hi @eoinmurray, it looks like this was an oversight on our part.  We had intended for those to be used by custom "spins" of JupyterLab, and hadn't thought about how they could be used by stock JupyterLab deployments.  I think there should be a way for us to expose `LabApp.lab_config` as a configurable object, but my traits-foo isn't super great.  I can take a look at this this week if no other core devs have any better insight.

**Comment by blink1073** [comment]
Alternatively, we could surface that one setting as `LabApp.public_url` and thread it through...

**Comment by eoinmurray** [comment]
I personally just need the public_url, but seems better for others to all
that config through?
