### ISSUE TITLE
Extensions does not work after upgrading to `v.0.34.12`

### ISSUE THREAD

**Issue by ruslanrf** [jupyterlab/jupyterlab#5450]
Hello,

Extensions extending Jupyter Lab's toolbar do not work after upgrading to `v.0.34.12`. Furthermore, example presented in ["How to extend the Notebook plugin"](https://jupyterlab.readthedocs.io/en/stable/developer/notebook.html#how-to-extend-the-notebook-plugin) does not work as well. It simply does not have any effect and is not visible in the UI.

**Comment by jasongrout** [comment]
We just released JupyterLab 0.35, so it may be that when you are installing packages in that example, it's pulling in the 0.35 version of the package. Can you try the example with the new JupyterLab 0.35?

**Comment by ruslanrf** [comment]
JupyterLab 0.35 is not in the conda repository yet. Regarding `v.0.34.12` I use only those packages in `package.json` files, which are used in `v.0.34.12`.

**Comment by ruslanrf** [comment]
Will you update conda's repository with a new version of JupyterLab?

Thx.

**Comment by blink1073** [comment]
We resolved the issue with our conda recipe, packages are available on conda-forge: https://anaconda.org/conda-forge/jupyterlab/files
