### ISSUE TITLE
"Open With > Vega" removes line breaks and indentation

### ISSUE THREAD

**Issue by masonlr** [jupyterlab/jupyterlab#5452]
**Describe the bug**

The "Open With > Vega" feature removes line breaks and indentation from the source json file (making it difficult to develop vega json files using jupyter lab).

**To Reproduce**

1. Create a file called `vega.json` with example vega source:

    ```
    curl https://vega.github.io/vega/examples/bar-chart.vg.json > vega.json
    ```

2. Right click on the file in the jupyterlab file browser and go to "Open With > Vega" .

3. Line breaks and indentation will be removed.

**Expected behavior**
Original file formatting to be retained.

**Screenshots**

![vega](https://user-images.githubusercontent.com/5828176/46586041-946b2d80-ca70-11e8-932a-ebe575f9aac1.gif)

**Desktop (please complete the following information):**

- OS: macOS 10.12.6
- Browser: chrome 69.0
- JupyterLab: 0.34.10

**Comment by jasongrout** [comment]
Confirmed. Thanks for the easy and explicit instructions to reproduce!

My first question: why is the vega viewer saving the json? Shouldn't it be basically opening the file read-only?

**Comment by jasongrout** [comment]
I've also noticed sometimes opening csv files, it seems that the file shows as being dirty. Perhaps this is related? The CSV viewer also should be read-only.

**Comment by jasongrout** [comment]
Setting as a 1.0 issue so we can track down why the file is being saved - that seems really odd.

**Comment by JohnJohnsonIII** [comment]
Identified issue as being with the _changeCallback function in docregistry package's mimedocument.ts file. About to do a PR for the fix...
