### ISSUE TITLE
Can't close kernal

### ISSUE THREAD

**Issue by paris0120** [jupyterlab/jupyterlab#5459]
Even I close the file and shut down the kernels in terminals and kernels tab, after a while they come back in terminals and kernels tab.

**Comment by jasongrout** [comment]
Can you give some more information like: operating system, browser, jupyterlab version? Does this happen all the time or only some of the time? If some of the time, can you narrow down how to reproduce it?

**Comment by jasongrout** [comment]
Does this sound like the same issue as #5464?

**Comment by jasongrout** [comment]
We're tracking this at #5061. If that doesn't seem to be the same issue, please comment here so we can reopen this issue.

**Comment by paris0120** [comment]
yes thank you
