### ISSUE TITLE
Zombie terminals

### ISSUE THREAD

**Issue by npyoung** [jupyterlab/jupyterlab#5464]
Sometimes closing terminals in JupyterLab by clicking "SHUTDOWN" in the "Running" tab or by clicking the X to shutdown all terminals leaves some terminals active. They are removed from the list of running terminals initially, but refreshing the list brings them back. Opening these terminals gives a blank terminal with no prompt, which does not respond to keystrokes (ctrl+x etc). Restarting JupyterLab removes the zombie terminals.

Unfortunately this bug appears inconsistently. I have a JupyterLab session I leave running on a server for weeks at a time, and maybe the 10th or 11th terminal I attempt to close will become a zombie. Eventually my "running" list gets cluttered with dead terminals and I need to restart JupyterLab.

- Windows 10, Ubuntu 14.04, Ubuntu 16.04
- Chrome 69
- JupyterLab 0.34.9

**Comment by jasongrout** [comment]
We're tracking this at #5061. If that doesn't seem to be the same issue, please comment here so we can reopen this issue.
