### ISSUE TITLE
Improve the performance of vim in terminal

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#5482]
With the latest releases, the performance of vim in terminal drops significant. Responses to key strokes are extremely slow. This is a very bad experience for heavy vim users.

**Comment by jasongrout** [comment]
I don't notice extreme slowness using vim in the terminal. Just checking: are you comparing with the same browser, OS, etc.? When you say "latest releases" - what's the earliest version you see the slowdown?

**Comment by dclong** [comment]
Perhaps it's because I'm using a lot of vim plugins. I cannot remember exactly from which version there's performance deterioration on vim, but I definitely experience this in 0.34 and 0.35. I'm using Firefox 62.

**Comment by dclong** [comment]
@jasongrout I confirm that the vim plugins that I used contributes to slowing down of vim plugins in terminal. Disabling these plugins makes vim in terminal more responsive.

**Comment by yelled1** [comment]
Could b nice to use mosh's SSP (State Synchronization Protocol) with Speculation adapted to Jupyterlab, which should solve the problem once & for all.
https://mosh.org/
```Mosh is a command-line program, like ssh. You can use it inside xterm, gnome-terminal, urxvt, Terminal.app, iTerm, emacs, screen, or tmux. But mosh was designed from scratch and supports just one character set: UTF-8. It fixes Unicode bugs in other terminals and in SSH.```

**Comment by yelled1** [comment]
Found a git project something really interesting, but this project seems to be Debian only.
https://github.com/rpwoodbu/mosh-chrome

**Mosh for Chrome**
Main author: Richard Woodbury (rpwoodbu@mybox.org)
This is a Mosh client port for the Chrome web browser using Native Client. It is particularly useful with Chrome OS.

**Comment by ashwinvis** [comment]
@dclong I am glad you brought this up and I confirm this issue. It has been annoying me for a few months. Recently I managed to track down the issue. The main culprit (at least for me) was the colorscheme. As a workaround I have this in my `~/.vimrc` which checks for an environment variable

```vim
if $TERM == "xterm"
    colorscheme default
else
    colorscheme solarized8
endif
```

It should work, because usual terminals would export `TERM=xterm-256color` or `TERM=xterm-color`, with the exception of xterm and xterm.js. Let me know if it helps.

**Comment by dclong** [comment]
@ashwinvis 
Thank you so much ashwinvis! It works like a charm!
