### ISSUE TITLE
workspace window name detection is not taking NotebookApp.base_url into account.

### ISSUE THREAD

**Issue by houqp** [jupyterlab/jupyterlab#5486]
**Describe the bug**
It's not possible to use the default workspace from two separate jupyterlab instances at the same time when they are hosted under the same domain (with different base_url).

This means hosting multiple jupyterlab instances under the same domain with different base_url won't work because you can only use one of them at any given time.

**To Reproduce**

1. Spin up and host jupyterlab instance under www.example.com/foo
2. Spin up and host another jupyterlab instance under www.example.com/bar
3. Open www.example.com/foo in browser
4. Open www.example.com/bar in browser
5. You will get "Please use a different workspace." prompt from www.example.com/bar. In the console, you will get a warning: `Window resolution failed: Window name candidate "" already exists`.

**Expected behavior**
The default workspace in the second jupyterlab (www.example.com/bar) should work without issue.

**Screenshots**
![screen shot 2018-10-11 at 11 16 52 am](https://user-images.githubusercontent.com/670302/46824943-2dd36180-cd47-11e8-983b-790510f26ab3.png)

**Desktop (please complete the following information):**

- OS: OSX 10.13.4
- Browser Chrome 68
- JupyterLab 0.33.8

**Additional context**
All jupyterlab instances ran with argument `--NotebookApp.base_url=`

<details><summary>Browser Output</summary>
<pre>
index.js:194 Window resolution failed: Window name candidate "" already exists
r.resolve.catch.e @ index.js:194
Promise.catch (async)
activate @ index.js:193
(anonymous) @ index.js:147
Promise.then (async)
e.activatePlugin @ index.js:146
e.resolveRequiredService @ index.js:190
(anonymous) @ index.js:140
e.activatePlugin @ index.js:140
e.resolveRequiredService @ index.js:190
(anonymous) @ index.js:140
e.activatePlugin @ index.js:140
e.resolveRequiredService @ index.js:190
(anonymous) @ index.js:140
e.activatePlugin @ index.js:140
(anonymous) @ index.js:266
e.start @ index.js:265
a @ index.out.js:1269
load (async)
ANye @ index.out.js:1296
n @ bootstrap:83
6 @ bootstrap:218
n @ bootstrap:83
r @ bootstrap:45
0 @ bootstrap:218
(anonymous) @ bootstrap:218
</pre>
</details>

**Comment by afshin** [comment]
I can't reproduce this issue. Here is what happened when I set up a reverse proxy and created two lab instances sharing the same host and port:

![base-urls](https://user-images.githubusercontent.com/159529/50647935-cefe3c80-0f71-11e9-99b0-2bcaadd8ed4b.gif)

Could you please check if this is happening to you in the newest published version of JupyterLab? It might be an issue we have resolved since the last release. If the issue persists, please feel free to re-open this issue!

**Comment by houqp** [comment]
@afshin see my comment at https://github.com/jupyterlab/jupyterlab/issues/5486#issuecomment-429068110. To reproduce this, you need to open two instances/tabs from the same browser window.

**Comment by damienrj** [comment]
I am also having this issue, should I open a new ticket? Or have you found a workaround?

**Comment by houqp** [comment]
I don't have a workaround, this is still an issue.
