### ISSUE TITLE
Unreadable Environment Names in the Launcher

### ISSUE THREAD

**Issue by adrianbayer** [jupyterlab/jupyterlab#5487]
**Describe the bug**
On the Launcher page I have to hover over all my Python environments to see the full name. Would be more convenient to see the whole thing, or at least the important part.

**Screenshots**
![image](https://user-images.githubusercontent.com/44034544/46834658-d93ce000-cd60-11e8-97a0-cf8459702daa.png)

**Desktop (please complete the following information):**

- OS: Mac Mojave
- Browser Google Chrome 69.0.3497.100 
- JupyterLab 0.34.12

**Comment by GoogleDownload** [comment]
You might want to update your JupyterLab... version 0.34.9 is out. There might be a fix.

**Comment by jasongrout** [comment]
Thanks for a great clear and comprehensive explanation. This issue is being tracked at #3795. Let's move the conversation there to consolidate the discussion.
