### ISSUE TITLE
Links in terminal output are no longer turned into anchors

### ISSUE THREAD

**Issue by vanpelt** [jupyterlab/jupyterlab#5489]
**Describe the bug**

Versions < 0.32.1 would autolink urls in the terminal, new versions no longer creates hyperlinks.  I understand that xterm.js is the underlying terminal library, but I'm hoping someone has a sense for why this functionality regressed.  Potentially it needs to be [activated](https://github.com/xtermjs/xterm.js#addons) now?  I'm hoping it's possible to activate from my own extension.  Otherwise is it possible to override the terminal widget?

**Expected behavior**
Links in the terminal should turn into anchors/

**Desktop (please complete the following information):**

- OS: [MacOS High Sierra]
- Browser [Chrome 69.0]
- JupyterLab [0.35.1]

**Comment by kapilkd13** [comment]
@jasongrout  Hi, I am getting the same issue with cell outputs too. I have recently migrated from good old Notebook to jupyterlab. One of the feature that I miss is to print clickable links in cell output.
Is it also because the xterm.js or is there some other reason behind it.
Also is there a way to attain the previous behaviour.  
Thanks

**Comment by jasongrout** [comment]
> @jasongrout Hi, I am getting the same issue with cell outputs too. I have recently migrated from good old Notebook to jupyterlab. One of the feature that I miss is to print clickable links in cell output.

Can you open a new issue? A cell output link would be a very different thing from this issue. When you open an issue for this, can you include the things listed in the issue template, such as a working code example illustrating the issue, the version numbers of various relevant things, etc.?
