### ISSUE TITLE
Feature request: File > New > Python File

### ISSUE THREAD

**Issue by masonlr** [jupyterlab/jupyterlab#5492]
**Describe the bug**

I primarily use JupyterLab with python files instead of notebooks, i.e. I open a `.py` file, right click and go to "Create Console for Editor". I then interactively run sections of the code using Shift+Enter.

There is currently no easy way to create new `.py` files  in JupyterLab. I can go "File > New > Text File" then rename it from `untitled.txt` to `foo.py`, or run `!touch foo.py` in the console.

Would it be useful to have a menu item for creating new python files? Or, in your opinion, would this be confusing to new users who may not know the difference between notebooks and scripts?

**Screenshots**

<img width="612" alt="screen shot 2018-10-14 at 7 08 30 pm" src="https://user-images.githubusercontent.com/5828176/46920333-9d19b180-cfe4-11e8-967c-cf0e91d26b7e.png">

**Comment by jtpio** [comment]
Good point @masonlr.

Same use case here (often creating Python files), so I took a few minutes to create a JupyterLab extension to add support for this.

If you want to give it a try (and let me know what you think!): `jupyter labextension install jupyterlab-python-file`
Source: https://github.com/jtpio/jupyterlab-python-file

It could make sense to add it to the core, unless JupyterLab wants to keep a "language agnostic" approach (without favoring Python or any other language).

**Comment by masonlr** [comment]
Can confirm https://github.com/jtpio/jupyterlab-python-file works as anticipated. Thank you @jtpio for the contribution.

**Comment by dsblank** [comment]
It can't go into core, because Jupyter is a multi-language project. Unless it allowed "File > New > Julia File" etc, etc.

**Comment by ian-r-rose** [comment]
A couple of thoughts:
* Markdown files have first-class status in JupyterLab, so I think at the very least "New Markdown File" could be a good idea.
* We could write a plugin that is file-type agnostic, and then allow the user to set the extension (and display name) that they like via the settings system. Then they could choose what kind of files they want to create automatically.

In general, I think this is a good idea. It is pretty annoying that the first thing I have to do when creating a new text file is change the extension to get syntax highlighting.

**Comment by jasongrout** [comment]
>     * We could write a plugin that is file-type agnostic, and then allow the user to set the extension (and display name) that they like via the settings system. Then they could choose what kind of files they want to create automatically.

+1. We could also pre-load the list with things for which we know we have syntax highlighting.

**Comment by dsblank** [comment]
Perhaps this could also be down under the live kernel menu. The kernel could provide language name, and filename extension.

**Comment by debanjanxy** [comment]
> **Describe the bug**
> 
> I primarily use JupyterLab with python files instead of notebooks, i.e. I open a `.py` file, right click and go to "Create Console for Editor". I then interactively run sections of the code using Shift+Enter.
> 
> There is currently no easy way to create new `.py` files in JupyterLab. I can go "File > New > Text File" then rename it from `untitled.txt` to `foo.py`, or run `!touch foo.py` in the console.
> 
> Would it be useful to have a menu item for creating new python files? Or, in your opinion, would this be confusing to new users who may not know the difference between notebooks and scripts?
> 
> **Screenshots**
> 
> <img alt="screen shot 2018-10-14 at 7 08 30 pm" width="612" src="https://user-images.githubusercontent.com/5828176/46920333-9d19b180-cfe4-11e8-967c-cf0e91d26b7e.png">
Another workaround:
You can also create a filename.txt file and rename it as filename.py
Then you can run it through the console.

**Comment by memeplex** [comment]
I think by the same token one can create a python notebook, one should be able to create a python file.

I understand the generic kernel argument, but AFAICS at some point a "create python notebook" action is added on top of this generic kernel. At the same point a "create python file" should also be added.

**Comment by lrq3000** [comment]
This should be in standard jupyterlab AND jupyter notebook! I did not even know that Jupyter could work directly on .py files, I thought these could only be generated from nbconvert (and I am very early Jupyter adopter!). Please add this functionality in standard!

**Comment by umdstu** [comment]
So yeah... where does the jupyterlab team stand on this? It's 2020 and we still can't create other useful file types without installing the aforementioned extension which only applies to Python files.

Worst case the File > New should allow an 'arbitrary' file extension to be set (in a popup), and could also give the oppotunity to set the file name rather than get Untitled by default. When you do new file in Visual Studio Code, it creates an empty input field in the file listing pane where you type in your filename (With extension), easy peasy. 

Again, thoughts on all of this?

**Comment by jasongrout** [comment]
1. You can create files of any type, but it does require an awkward two-step process of creating the file, then renaming it. I don't think anyone really likes that.
2. I think the thing to do is to really think through the workflow and ux, based on the ideas above and others, of what should be there - let's not settle for worst-case :). Clearly we can't have icons in the launcher for every file type, for example. Perhaps we can  (though I agree that having python files as a quick link makes sense, or perhaps looking up what kernels are installed and adding those file types).
3. Then it will be a matter of someone implementing it. Contributions are *certainly* welcome!

**Comment by jasongrout** [comment]
> I understand the generic kernel argument, but AFAICS at some point a "create python notebook" action is added on top of this generic kernel. At the same point a "create python file" should also be added.

We can get a list of kernels, but unfortunately the kernel metadata doesn't tell us the file extension for that language (for example, it's easy to see that we have a Julia kernel, but that [won't tell us](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs) that the file extension should be `.jl`, so we would have to have a manual lookup table for now)

**Comment by dhirschfeld** [comment]
> *the kernel metadata doesn't tell us the file extension for that language*

Maybe make it an optional extra argument that kernel authors can use or not? If not present it could default to `.txt`

**Comment by jasongrout** [comment]
It would be interesting for kernel authors to give file extensions (probably a list? C++ has at least .cpp and .hpp). That's a discussion for another repo, though. For us immediately, we can make a list of common extensions for now.

**Comment by jasongrout** [comment]
One place to add such commands is in the fileeditor-extension plugin, perhaps around here: https://github.com/jupyterlab/jupyterlab/blob/d8c66c009df2c04ceff454f88e25fe1650b58312/packages/fileeditor-extension/src/commands.ts#L583-L590

Setting as a good first issue. I could see, for example, using the `app` object to query the kernel spec manager for each kernel spec in the system, then having a lookup table of languages to file extensions and add all the appropriate file extensions for each kernel installed.

**Comment by dhirschfeld** [comment]
For maximum flexibility, it could be a user-configurable setting from JupyterLab... though this might add some complexity around the implementation.

**Comment by jasongrout** [comment]
> For maximum flexibility, it could be a user-configurable setting from JupyterLab... though this might add some complexity around the implementation.

I think that sounds fine too.

**Comment by umdstu** [comment]
I think these are some great (complex) ideas tossed around. Generating file types that can populate the list of options based on what the user has installed could become quite extensive though (I could be wrong). That said, one may even want to use Labs as a simple text editor for which no kernels are installed or associated with. User configurability would help that and dramatically reduce the possible number of entries, with a few defaults based on what's installed, eg. .rb, .c, .go, .sh, .js, .py).

That said (again)... VSCode doesn't go anywhere near as far as this. Out of the box, the basic file creation is just a little more cleaner than what is currently in Labs. Eg. Right click the left file tree pane, select New File or New Folder. You get an empty input box created in the tree with focus jumped to it, and you type in the filename (and extension), so you get exactly what you want. Same with creating folders. However in verifying the functionality between the two, I noticed that there isn't even a Right Click > New File option, just New Folder... that would be a good start between this and the above.

With respect to icons, as someone mentioned earlier, there are VSCode plugins that provide customized/additional icons, but there are dozens that are already built in, and i think that would also greatly improve the UI of the file tree on the left.

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/10009, thanks @ohrely!
