### ISSUE TITLE
Support to add a button to file browser. (Git Extension Support 1/2)

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#5498]
For the Git Extension, we're trying to integrate the experience with the existing file browser. The first order of business was to add a 'clone repo' button to the file browser. I was wondering what it would take to expose the API for the file browser so an extension could do something like this (Red outline is there to highlight the new feature, I'm not looking to add a bright red outline to the UI):
<img width="365" alt="screen shot 2018-10-15 at 9 27 45 am" src="https://user-images.githubusercontent.com/22109376/46966148-be6cb300-d061-11e8-990a-9ff8c1c4da02.png">

cc: @jaipreet-s , @weihwang

**Comment by jaipreet-s** [comment]
This is do-able in a fairly clean way today without having to resort to DOM manipulation

A plugin can request an `IFileBrowserFactory`, access the toolbar element, and add a `ToolbarButton`

```javascript
let toolbar = factory.defaultBrowser.toolbar;
 toolbar.addItem('myButton', new ToolbarButton({...});
```

**Comment by ian-r-rose** [comment]
Thanks @jaipreet-s
