### ISSUE TITLE
Investigate using azure pipelines for CI

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#5506]
Azure pipelines supports mac, linux, and windows builds with more throughput than Travis CI. I would like to investigate using them, to see if it would make it quicker to get build results after pushing. Also, they support more granular metadata analysis of the tests, so that you can see which individual tests fail regularly, which would be invaluable in finding flaky tests.

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any suggestions or questions. I'm happy to help!

**Comment by saulshanabrook** [comment]
Thanks @kaylangan! I am trying things out in a PR against my fork that has Azure Pipelines enabled: https://github.com/saulshanabrook/jupyterlab/pull/1/

Things are going pretty well, I am re-using the existing travis and appveyor scripts for now, but eventually we could move that all into the `azure-pipelines.yml` file.   

I was able to successfully enable getting metadata from the py.test run, which you can see here: https://dev.azure.com/sshanabrook/sshanabrook/_build/results?buildId=34&view=ms.vss-test-web.test-result-details

We can now see which tests failed in the web UI instead of sorting through the logs and see how long each test took.

I would like to enable this for the Jest tests as well. Do you know of any existing work on getting Jest tests to generate the right files for Azure Pipelines to parse?

**Comment by PBoraMSFT** [comment]
@saulshanabrook - you can use a JUnit reporter for Jest to generate the XML test results https://www.npmjs.com/package/jest-junit OR https://www.npmjs.com/package/jest-junit-reporter 
Then follow it up with the publish test results task in the pipeline YAML. 

This should give you the web UI reporting.

**Comment by saulshanabrook** [comment]
I got jest reporting working, so we can now see the failures in the UI, thanks for the tip. 

I am just getting a few errors now in our windows builds. @blink1073 They are all in docregistry context: https://dev.azure.com/sshanabrook/sshanabrook/_build/results?buildId=41&view=ms.vss-test-web.test-result-details Have you seen these failures before?

**Comment by blink1073** [comment]
I don't recall seeing those specifically, no.  Race conditions seem to differ on this platform vs Appveyor :smile:

**Comment by saulshanabrook** [comment]
@kaylangan Is there a way to run the azure pipelines locally maybe? We keep getting some failures more often while CI is running, than we do locally, probably due hardware or software differences.

It would be really helpful to be able to have an easy way to replicate, as much as possible, the CI environment locally.

**Comment by kaylangan** [comment]
@saulshanabrook There's not an easy way to run the pipeline locally. One option (if you're so inclined) would be to take the most recent image from our [image generation repo](https://github.com/Microsoft/azure-pipelines-image-generation/releases) and set up a VM with that image. You could then run on that VM. Not exactly the most user-friendly...

**Comment by saulshanabrook** [comment]
Hey @kaylangan, we are trying to enable pipelines on another repo in this org (https://github.com/jupyterlab/theme-cookiecutter). However, when I try to enable it, it asks me to login with OAuth and I don't want to, I want to use the App to connect. Which is what the docs recommend
<img width="963" alt="Screen Shot 2019-07-10 at 3 28 44 PM" src="https://user-images.githubusercontent.com/1186124/60998721-814efc00-a327-11e9-9043-01a2ccabdb98.png">

<img width="957" alt="Screen Shot 2019-07-10 at 3 28 59 PM" src="https://user-images.githubusercontent.com/1186124/60998727-86ac4680-a327-11e9-8424-ddeb6058884d.png">

We have the app enabled for all repos in the org. Do you have any ideas how I can setup this repo with the app?

**Comment by davidstaheli** [comment]
Hi @saulshanabrook.  Sorry for the confusion caused by that OAuth prompt.  We made a change recently that makes the flow like this:

1.  After the user chooses GitHub as the code location, **always ask them to log in with OAuth** to verify that they have access to the repos that get listed.  For example, it's possible that the GitHub App has access to a repo, but the user doesn't.
2.  Once a repo is chosen
    a. If the GitHub App is enabled on the repo, **use the app as the connection**.
    b. Otherwise, use the user's OAuth as the connection.

So the GitHub App should still be used for your pipeline's connection after you log in with OAuth.  You can verify this by looking in a PR that is built by the newly created pipeline.  Only pipelines that use the GitHub App will show build details under the Checks tab in GitHub, like this:

![image](https://user-images.githubusercontent.com/1767415/61141320-4e2d7980-a49b-11e9-9c2f-3da617112f9e.png)
