### ISSUE TITLE
somewhat inexperienced programmer, need help with finding where to fork files to

### ISSUE THREAD

**Issue by sarahefcarroll** [jupyterlab/jupyterlab#5521]
so, i need help finding where on my computer to fork these fixes for the dark theme of jupyter lab. Its probably painfully obvious but I'm new and I'm sick of opening all the folders of my computer related to anaconda/python/jupyter in an attempt to find what I'm looking for.
(I'm in this weird place where I know enough programming to just barely not be a beginner, but not enough about git and forking and how anaconda is installed to know where to put the files...)

**Comment by blink1073** [comment]
Hi @sarahefcarroll!  Our [contributing guide](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md) is meant to help you get started.  If you're a beginner to GitHub, here is a [guide](https://guides.github.com/activities/forking/) to forking.

**Comment by jasongrout** [comment]
Closing as answered. Please continue commenting if you need more help.
