### ISSUE TITLE
Services - --notebook-dir doesn't change working directory?

### ISSUE THREAD

**Issue by pavanagrawal123** [jupyterlab/jupyterlab#5522]
I'm using the jupyterlab/services module for a VSCode plugin.
I'm launching a kernel with `--notebook-dir`
and then executing commands with `.executeCode`, but this doesn't seem to keep the current working directory to what I originally started the kernel with. When a kernel is started with --notebook-dir, is the CWD not set to --notebook-dir automatically?

**Comment by jasongrout** [comment]
It seems you are using the notebook server to launch kernels? In that case, I'd suggest opening an issue in the notebook server repo: https://github.com/jupyter/notebook/
