### ISSUE TITLE
Two Notebooks sharing a kernel and Restart Kernel Issue

### ISSUE THREAD

**Issue by ea42gh** [jupyterlab/jupyterlab#5527]
Given two notebooks sharing the same kernel,
a restart of the kernel in one of the notebooks results in two separate kernels:

I am using this feature to provide Scratch cells, and find myself
repeatedly changing the kernel for the scratch notebook...

**Comment by ian-r-rose** [comment]
Hi @ea42gh, I am unable to reproduce this bug on JupyterLab master. On what version did you see this behavior?

**Comment by ea42gh** [comment]
I do not know what version it was, and I rarely use the feature.
Checking now I no longer see the issue with jupyter-lab 0.35.4

**Comment by jasongrout** [comment]
Great, thanks!
