### ISSUE TITLE
Should allow user to style the codemirror selection

### ISSUE THREAD

**Issue by futurist** [jupyterlab/jupyterlab#5528]
**Describe the bug**
Now it's lack the config options to style the codemirror selection, there are [commonly used addons for codemirror](https://codemirror.net/doc/manual.html#addons) to style these:

selection/active-line.js
selection/mark-selection.js
selection/selection-pointer.js

**Expected behavior**
The `selection` addons for codemirror should be included and set to a basic default config options.

**Screenshots**

![image](https://user-images.githubusercontent.com/159167/47544766-3f0d9800-d91b-11e8-9a72-5e105fa5c840.png)

**Desktop (please complete the following information):**

- JupyterLab [<=0.35]

**Comment by blink1073** [comment]
Looks good to me!  cc @tgeorgeux for style input.
