### ISSUE TITLE
Scroll content overflow and cover edges shadow

### ISSUE THREAD

**Issue by GreatFireWall** [jupyterlab/jupyterlab#5531]
**Describe the bug**
Scroll content overflow and cover edges shadow

**To Reproduce**

1. Enable Scrolling for Outputs

**Screenshots**
![2018-10-26_17-55-57](https://user-images.githubusercontent.com/4510984/47559702-c58c9e80-d948-11e8-8c48-7c30a4e22c71.gif)

**Desktop (please complete the following information):**

- OS: Windows 10  1803  17134.376
- Browser: Chrome 69.0.3497.100 64bit
- JupyterLab: 0.35.2

**Comment by jasongrout** [comment]
Thanks! We're tracking this at #4253.
