### ISSUE TITLE
Bizare "Error Loading Notebook" when notebook is in a folder with a specific name

### ISSUE THREAD

**Issue by fostiropoulos** [jupyterlab/jupyterlab#5533]
**Describe the bug**
There is an "Error Loading Notebook" "Error" message for EVERY notebook, and **only** when they are inside a specific folder named "affiliation".  If I rename the same folder to anything else the notebooks load fine. But in that specific folder, new notebooks can't run. 

**To Reproduce**
Not sure if and how will work on your system. I am on Ubuntu 18.04, tried it on 2 computers same version.

1. Create affiliation.py empty
2. Create affiliation folder
3. add notebook in there

**Expected behavior**
 "Error Loading Notebook" "Error" 

**Screenshots**
![image](https://user-images.githubusercontent.com/4337024/47574912-9a2c9400-d8f5-11e8-8931-fccfd5a8e816.png)
![image](https://user-images.githubusercontent.com/4337024/47574939-ae709100-d8f5-11e8-86f8-c043dc035cb8.png)
![image](https://user-images.githubusercontent.com/4337024/47574952-b6303580-d8f5-11e8-8c5f-0321ac08c376.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser Firefox
- Jupyter 4.4.0

**Comment by ian-r-rose** [comment]
Hi @fostiropoulos do you have an adblocker installed? We have seen issues like this this with overzealous blockers.  Things to try:
1. Temporarily disable any adblockers.
2. If that fixes things, you can add an exception for the domain in which you usually use JupyterLab/notebook.

**Comment by fostiropoulos** [comment]
@ian-r-rose yup! it's the ad blocker. But doesn't make much sense because it is locally hosted

**Comment by ian-r-rose** [comment]
They typically have a list of rules for which types of URLs to block. Even if it is a local url (which I agree they should not block).
