### ISSUE TITLE
Error executing Jupyter command 'lab': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by bingws** [jupyterlab/jupyterlab#5557]
The Jupyter lab is an updated version of the Jupyter Notebook. But I ran the following two commands and got different results.
Command 1:
`nvidia-docker run --rm --name tf-notebook -p 8888:8888 -p 6006:6006 tensorflow/tensorflow:latest-gpu jupyter lab --allow-root`
Result 1:
Error executing Jupyter command 'lab': [Errno 2] No such file or directory

Command 2:
`nvidia-docker run --rm --name tf-notebook -p 8888:8888 -p 6006:6006 tensorflow/tensorflow:latest-gpu jupyter notebook --allow-root`
Result 2 (it's ok):
[I 12:42:49.616 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 12:42:49.644 NotebookApp] Serving notebooks from local directory: /notebooks
[I 12:42:49.644 NotebookApp] The Jupyter Notebook is running at:
[I 12:42:49.644 NotebookApp] http://(4dcb810d7487 or 127.0.0.1):8888/?token=40db49ceb498bddb83bd1cceb4c92e1e84f71302ab2d5898
[I 12:42:49.644 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:42:49.645 NotebookApp] Copy/paste this URL into your browser when you connect for the first time,to login with a token:
     http://(4dcb810d7487 or 127.0.0.1):8888/? 
     token=40db49ceb498bddb83bd1cceb4c92e1e84f71302ab2d5898

Of course, I have successfully installed the jupyter lab. How to solve this problem?

**Comment by blink1073** [comment]
It could be that `jupyter`, and `jupyter-notebook` are installed in a different location than `jupyter-lab`.
