### ISSUE TITLE
Simplify the JupyterLab inspector.

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#5560]
Following some conversations with @BoPeng and @ellisonbg, we should make JupyterLab's inspector do fewer things and be a single-purpose extension. In addition, we should provide an extension point so that the actual *content* of the inspector can be generated by a third-party extension. This functionality and API should be solidified before 1.0:

* The `remembers` functionality  of the inspector, which has lain dormant, should be removed.
  * The toolbar for the inspector should removed as it is the main UI manifestation of the `remembers` feature.
  * The internal list of previously inspected items that are kept in memory should be removed. The inspector should basically be a simple widget that displays the currently inspected thing only.
* The concept of multiple inspectors each with their own tabs should be reduced to a single inspector. A tab bar inside the tabbed interface of JupyterLab is not a great user experience.
* The logic that transforms a MIME bundle into a widget that gets displayed inside the inspector should be moved into a standalone `JupyterLabPlugin` in order to allow third-party extension to override it and generate their own widgets to show inside the inspector.
* The concept of *types* of inspector content should probably be removed as well.

cf. https://github.com/jupyterlab/jupyterlab/pull/4879, https://github.com/jupyterlab/jupyterlab/pull/5530

*Upshot:* What this means is that the only extension points of the inspector should be:

1. Intercepting the MIME bundle and returning custom widgets to render in the inspector panel instead of using the core renderer that ships with JupyterLab.
1. Replacing the inspector altogether.

For other similar functionality within a third-party extension, it probably makes most sense to simply create a main area widget or a side area widget that ships with the extension.

**Comment by BoPeng** [comment]
👍 

Once you can come up with a PR, I will be happy to implement #4879 against the new API as the first test case.

**Comment by ellisonbg** [comment]
Thanks for writing this up @afshin - I think this plan looks good! Thanks for being patient with us @BoPeng

**Comment by vidartf** [comment]
> The logic that transforms a MIME bundle into a widget that gets displayed inside the inspector should be moved into a standalone JupyterLabPlugin in order to allow third-party extension to override it and generate their own widgets to show inside the inspector.

Just for clarification: Does it make more sense for third-party extensions to *extend* this (e.g. handle new media types) instead of *overriding*?

**Comment by afshin** [comment]
@vidartf Handling new media types would automatically happen if a new MIME renderer extension is added to lab, so that's always been an extension point. But the ability to simply create some entirely new way of showing content / functionality in the inspector is what I had in mind. What do you think?

**Comment by vidartf** [comment]
Oh I see. That makes perfect sense. Thanks for the clarification!

**Comment by BoPeng** [comment]
> The logic that transforms a MIME bundle into a widget that gets displayed inside the inspector should be moved into a standalone `JupyterLabPlugin` in order to allow third-party extension to override it and generate their own widgets to show inside the inspector.

The goal of #4879 is to provide a simple way for extensions (and kernels if https://github.com/jupyter/jupyter_client/pull/378 is accepted) to update the Inspector with a unified message type. Whereas the plugin-generating-their-own-widget mechanism is very powerful, I am wondering if the base inspector can be designed to use `transient_display_data` as its communication channel so that developers can, in a majority of cases, simply use the built-in inspector to display their own `display_data`-like data without having to create their own inspector extension.
