### ISSUE TITLE
JupyterLab Dark Theme obscures highlighting in command palette

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#5561]
**Describe the bug**
When using the JupyterLab dark theme, the filtered results of the command palette obscure the highlighted matched letters in the results. See screenshot below.

**To Reproduce**

1. Open the command palette.
2. Type "con" to filter the results.
3. See error

**Expected behavior**
The highlighting style for the command palette should be clearer.

**Screenshots**
<img width="333" alt="command palette highlight bug" src="https://user-images.githubusercontent.com/159529/47820295-72915d80-dd33-11e8-9416-902b76031b32.png">

**Desktop (please complete the following information):**

- OS: macOS 10.13.6
- Browser: Chrome 70.0.3538.77
- JupyterLab 1.0.0a0 `master`

**Comment by manuel-ruiz-23** [comment]
The problems seem to be at ''.p-CommandPalette-item.p-mod-disabled mark'' style, disabling it shows the following result 

![screenshot from 2018-10-31 18-02-32](https://user-images.githubusercontent.com/16631761/47826809-4c6dbc80-dd37-11e8-9fc1-389e0bf23189.png)

I'm new and interested in submitting this as a PR

**Comment by afshin** [comment]
@manuel-ruiz-23 Thanks for looking at this issue! When you work on this issue, please make sure that the highlighting works in both the light and the dark theme. Cheers!

**Comment by briansgo** [comment]
This bug also affects the menu titles
![image](https://user-images.githubusercontent.com/26393657/48729488-f1700c80-ebf4-11e8-8be5-0123d6ff3d39.png)
Should we re-open this issue or create another one?

**Comment by ian-r-rose** [comment]
Thanks for pointing that out @briansgo. I'll reopen this issue.

We should go to this CSS rule:
https://github.com/jupyterlab/jupyterlab/blob/9fa8616097ec5d82e4d3ca146582405e46a38e67/packages/apputils/style/commandpalette.css#L117

and add `  color: var(--jp-ui-font-color1);`

Reopening, and maintaining the good first issue status.

**Comment by briansgo** [comment]
I already tried adding the 'color1', but the headers are already bold and color1, so the highlight is imperceptible.

Then I tried with 'color0' and it does change but the difference is barely noticeable (see images)

![image](https://user-images.githubusercontent.com/26393657/48734736-8bd74c80-ec03-11e8-8c77-dad04ea967e0.png)

![image](https://user-images.githubusercontent.com/26393657/48734784-b9bc9100-ec03-11e8-8fa7-e0105dbb1916.png)

I'll really appreciate your opinion

**Comment by ian-r-rose** [comment]
Sorry for the slow response @briansgo. I was just taking a look at this with @tgeorgeux , and we thought that maybe it would be best to have the default header as `color2`, and the matched text as `color0`. This has the effect of more strongly highlighting the match.

What do you think?

**Comment by tgeorgeux** [comment]
@ian-r-rose I don't think it's a good idea to use `color2` for the headings and 'color1' for the sub-items of a menu. It's inconsistent with all our other styling.

**Comment by tgeorgeux** [comment]
@briansgo sorry, forgot to ping you above.

**Comment by briansgo** [comment]
@tgeorgeux I tried changing `bold` to `bolder` but didn't see any changes
https://github.com/jupyterlab/jupyterlab/blob/9fa8616097ec5d82e4d3ca146582405e46a38e67/packages/apputils/style/commandpalette.css#L119
I also tried to set the font weight value manually but still, no changes were visible

@ian-r-rose I think we should discuss this further to come into an agreement before implementing the changes 
We need to discuss:

-Header color (current: `color 1`)
-Matched header color (current: black, should be `color1`, but `color 1` is the same as the header)

**Comment by ian-r-rose** [comment]
Ping @tgeorgeux for a call on this one.

**Comment by jasongrout** [comment]
Assigning to Future, since @ian-r-rose says that what is still left over from this issue is not a blocker for 1.0.
