### ISSUE TITLE
Support building extensions that include resolve.alias definitions

### ISSUE THREAD

**Issue by jonmmease** [jupyterlab/jupyterlab#5566]
### Context
I'm working on building a JupyterLab extension (an ipywidget to be precise) that makes use of the CesiumJS JavaScript library.  After following the [cesium-and-webpack](https://cesiumjs.org/tutorials/cesium-and-webpack/) instructions I was able to get the extension building properly with webpack directly.

### Problem
However, when I build the extension using `jupyter labextension link`, I get a webpack `ModuleNotFoundError` that the cesium library cannot be resolved.

### Cause
After a lot of troubleshooting I think I've narrowed down the issue.  The cesium instructions require the use of a [`resolve.alias`](https://webpack.js.org/configuration/resolve/#resolve-alias) block in the webpack module exports configuration like this:

```javascript
	resolve: {
		alias: {
			// Cesium module name
			cesium: path.resolve(__dirname, cesiumSource)
		}
	},
```

However, this `resolve.alias` information is not preserved in the generation of the `share/jupyter/lab/staging/webpack.config.js` configuration file that seems to be generated during the `jupyter lab build` process.  If I manually edit `share/jupyter/lab/staging/webpack.config.js` to add the `alias` block above, then I'm able to complete the build by running `jlpm build` from the `share/jupyter/lab/staging/` directory.

### Question
I'm operating at the edge of my understanding of both webpack and JupyterLab here so I'm not certain this suggestion make sense, but would it be possible for the `jupyter lab build` process to automatically preserve this alias?

Thanks!

**Comment by bollwyvl** [comment]
Cesium is amazing, but yeah, a little unwieldy to integrate.

Can you do the webpack build yourself, and include that in your built
package? Or better still, make a package that bundles cesium, shims of the
exports, and which your (and others') extensions can use, as no sane lab
user will want two copies of that at runtime.

**Comment by jonmmease** [comment]
Thanks for your perspective @bollwyvl!

Just to get my bearings, are you suggesting that I first create a non-JupyterLab specific package that:
 1. Depends on CesiumJS
 2. Follows all of Cesium's webpack instructions
 3. Re-exports the top-level Cesium export (the thing that's aliased above)

And then have my JupyterLab extension depend on this more webpack-friendly CesiumJS package? Thanks again!

**Comment by jasongrout** [comment]
I think that is essentially what @bollwyvl is suggesting, i.e., you run webpack in your custom cesium package build step, and the package distributes the already-webpacked cesium. It might be a bit trickier than just the resolve line, since it appears that the cesium webpack instructions also involve copying over a bunch of static assets.

**Comment by jonmmease** [comment]
Thanks for taking a look @jasongrout, I'll give that a shot and report back when I have a chance. If you don't think there's anything more that JupyterLab could reasonably support here, feel free to close out the issue.

**Comment by jasongrout** [comment]
Thanks. I'm not sure how the idea will work out (it does seem somewhat complicated to bundle cesium), so if you're running into issues, please feel free to reopen this issue or open a new one.
