### ISSUE TITLE
 'ascii' codec can't decode byte 0xe5 in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by bingws** [jupyterlab/jupyterlab#5572]
An error occurred when I ran the following command：
`docker run --rm --name tf-notebook -v /home/ubt16/jpyws:/dockerDir -p 9876:8888 lab:v1 jupyter lab --allow-root`

description：
/home/ubt16/jpyws is mounted to /dockerDir, and I have a chinese-named folder under the /home/ubt16/jpyws directory.
When I jump to the web link of jupyter lab, the file named in Chinese cannot be displayed and an error is reported, ,but English-named folders can be displayed successfully.

error：
```
[W 03:18:17.131 LabApp] failed to decode filename 'AI鍏ラ棬璇剧▼鈥旂涓€鑺傝': 'ascii' codec can't decode byte 0xe5 in position 3: ordinal not in range(128)
[W 03:18:17.135 LabApp] Could not determine jupyterlab build status without nodejs
```

**Comment by blink1073** [comment]
Hi @bingws, can you please try setting `LANG=zn`, cf https://github.com/jupyterlab/jupyterlab/issues/5345#issuecomment-423568810

**Comment by bingws** [comment]
@blink1073 I tried to add a new command (I don't know if that's what you said) and reported a new error.
command：
`# docker run --rm --name tf-notebook -v /home/ubt16/jpyws:/dockerDir -p 9876:8888 lab:v1  LANG=zh_CN.UTF-8 jupyter lab --allow-root`

error：
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"LANG=zh_CN.UTF-8\": executable file not found in $PATH": unknown.`

**Comment by blink1073** [comment]
I think you need to use `-e LANG=zn` to set an environment variable.

**Comment by blink1073** [comment]
I'm not sure what the exact command would look like, here are the docs from Docker: https://docs.docker.com/engine/reference/run/#env-environment-variables

**Comment by ellisonbg** [comment]
closing for now - let us know if you have other questions

**Comment by H-huihui** [comment]
@bingws I have same problems, do u have some suggestion ?

**Comment by bingws** [comment]
@H-huihui Modify Dockerfile, this is my idea. I didn't, because users could read English.
