### ISSUE TITLE
Text overlapping when open terminal within jupyter lab on remote server

### ISSUE THREAD

**Issue by zuoxingdong** [jupyterlab/jupyterlab#5574]
I am using jupyterlab from remote server and when opening a terminal within jupyterlab, the texts are overlapped between lines, shown in the following screenshots
![image](https://user-images.githubusercontent.com/18168681/47910220-738cd100-de92-11e8-8322-1f094a3badf4.png)

It should look something like this:
![image](https://user-images.githubusercontent.com/18168681/47910213-6bcd2c80-de92-11e8-9f89-e494aacf95e8.png)

- OS: Ubuntu 16.04
- Browser: Chrome 68.0
- JupyterLab: 0.35.3

**Comment by madx** [comment]
One of my coworkers reported the same issue to me, this happens only on Chrome and not Firefox:

## Chrome

![image pasted at 2018-11-6 17-10](https://user-images.githubusercontent.com/5723/48121061-36e71e00-e274-11e8-9c38-827b7de80fb3.png)

## Firefox

![image pasted at 2018-11-6 17-10 1](https://user-images.githubusercontent.com/5723/48121062-38b0e180-e274-11e8-80e3-b3f8882606e8.png)

**Comment by blink1073** [comment]
Thanks for reporting, @zuoxingdong, we're tracking this in #5019.
