### ISSUE TITLE
Feature Request: "Run All" and "Restart Kernel and Run All" for Editor/Console

### ISSUE THREAD

**Issue by WhoIsJack** [jupyterlab/jupyterlab#5579]
When working with a `.py` file (or some other language file) in the editor and an associated console (opened through `right click > "Create Console for Editor"`), code can be run by selecting the desired lines and hitting  `Shift+Enter`.

However, sometimes one needs to run everything or - perhaps more importantly - wipe the console's state and run everything. Currently, doing the latter would require starting a new console (and closing the old one), selecting everything (`Ctrl+a`) and then hitting `Shift+Enter` (unless I'm missing something?). In particular the first step in this sequence makes this kind of cumbersome.

I think it would be nice if `"Run All"` and `"Restart Kernel and Run All"` in the `Run` menu were supported to handle these cases. Potentially, `"Restart Kernel and Run All"` could be relabeled as `"Restart Console and Run All"` when working in an editor. Finally, it could be cool to use something like `Ctrl+Shift+Enter` as a keyboard shortcut to trigger `"Restart Console and Run All"`.

**Comment by jasongrout** [comment]
I think this would possibly be a good intermediate-level first issue. The code that adds the one run menu item is at https://github.com/jupyterlab/jupyterlab/blob/6a00f4f476271379e0c04b480f04d5d2a1f9b868/packages/fileeditor-extension/src/index.ts#L698-L713 Something similar to it could be added to support the run all and restart kernel and run all menu items. Related code in the notebook is at https://github.com/jupyterlab/jupyterlab/blob/0fad4075eafebfaa7bdd82c74b4536c7478e87f7/packages/notebook-extension/src/index.ts#L1957-L1972 to see how to add those items to the menu.
