### ISSUE TITLE
Quote behavior in f-string editing

### ISSUE THREAD

**Issue by sterlinm** [jupyterlab/jupyterlab#5588]
Apologies if this is already a known issue, I searched around a bit but didn't find it. I've noticed that when typing 3.6+ style f-strings in jupyter lab the behavior for creating the quotation marks is a little buggy. I think ideally when you start an f-string by typing `f"` it would automatically add the second quotation mark and place the cursor in between the two quotation marks, similar to how it behaves for regular quotation marks, parentheses, brackets, and so forth. However, instead when you type `f"` it doesn't add the second quotation mark, and then somewhat more annoyingly, when you try to close the string it adds a two quotation marks at the end. If you try to hit delete once, it deletes both of the new quotation marks since it thinks it's a new string. Instead you have to highlight one of the quotation marks specifically to delete it. I've included a gif that is hopefully clear.

To reproduce, go to a console or notebook in jupyter lab and type `f"Hello` and then attempt to close the string.

One possibility I haven't investigated is if this would be fixed if my base environment was 3.6 (it's 3.5).

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1461273/48005793-5d754f80-e0e2-11e8-97cc-c17554b6f334.gif)

**Environment:**
Mac OS X 10.13.4
JupyterLab 0.34.12
Python 3.5.4 (base environment)
Python 3.6.5 (conda environment)
Browser [Chrome Version 70.0.3538.77]

By the way, I'm open to trying to help with this issue but I'm new to contributing and don't have a great sense of the scope or if it's a good first issue to tackle. Thanks!

**Comment by jasongrout** [comment]
Can you try JupyterLab 0.35? It works fine for me, and I think it may have been fixed in a CodeMirror upgrade (codemirror is the editor we use).

**Comment by jasongrout** [comment]
Here it is in the current CodeMirror mode, which matches what I'm seeing in jlab 0.35.4. Is this what you are seeing?

<img width="285" alt="screen shot 2018-11-13 at 7 34 34 am" src="https://user-images.githubusercontent.com/192614/48424094-bcf0e200-e716-11e8-94fc-efbd001bff0d.png">

**Comment by aldanor** [comment]
@jasongrout Hmm, ok, try this (and try hitting enter afterwards):

```python
a = g(f'{b["c"]}') # oops
```

**Comment by aldanor** [comment]
![image](https://user-images.githubusercontent.com/2418513/48486384-471e7080-e813-11e8-9bde-c210ef5692ec.png)

**Comment by aldanor** [comment]
@jasongrout The latter issue was a codemirror bug and has now been fixed upstream.

**Comment by sterlinm** [comment]
I seem to be having difficulty getting conda to update jupyter lab from 0.34 to 0.35. It tells me that it's already up to date. I'll report back when I figure that out. Thanks!

![image](https://user-images.githubusercontent.com/1461273/48625327-e6ab4280-e97c-11e8-9987-b6941f94fe1f.png)

**Comment by jasongrout** [comment]
It looks like from https://anaconda.org/conda-forge/jupyterlab/files that conda-forge is only building packages for python 3.6 or 3.7 these days. You likely have the latest version built for python 3.5. I think you'd need to install via pip to get the latest jupyterlab on python 3.5.

**Comment by jasongrout** [comment]
> @jasongrout The latter issue was a codemirror bug and has now been fixed upstream.

@aldanor - is that patch in codemirror not in a codemirror release yet? If so, let's leave this issue open as a reminder to update codemirror when it is released.

**Comment by sterlinm** [comment]
Just to update, I've updated to 0.35.4 and the f-string behavior is still the same.

**Comment by aldanor** [comment]
@jasongrout https://github.com/codemirror/CodeMirror/commit/436081e1cd8be37eea30a65f4a709137d66a47f5

**Comment by jasongrout** [comment]
Looks like the codemirror release happened (5.42), so tagging as a good first issue for upgrading the codemirror dependency.

**Comment by arredond** [comment]
Hey, sorry to reopen this three months later but I'm still seeing this behaviour.

As described above, it happens inside an f-string, whenever there's quoted text inside curly brackets:

```python
f'Hello {"world"}' # this comment would be highlighted as text, not comment
```

I'm on:
- Jupyter Lab 0.35.4 (that's the max I get from `pip`)
- Jupyter Notebook 5.7.4
- Jupyter 4.4.0

And in case it matters, I'm on:
- Firefox 65.0 (but I get the same behaviour on Chrome 72.0)
- macOS Mojave

**Comment by jasongrout** [comment]
The pr above was shipped in the prerelease a few days ago (`pip install jupyterlab --pre`), and will be in 1.0.

**Comment by jasongrout** [comment]
Usual caveats apply for installing a prerelease, of course. Install at your own risk, other plugins may not work, etc.

**Comment by Thrgd456** [comment]
I'm having the same issue.  Win 10, Jupyter 0.35.4  

I don't see a newer version.  Is there a new version out now?

**Comment by sterlinm** [comment]
I don't think the 1.0 version has been officially released yet.

**Comment by jasongrout** [comment]
We have a prerelease, 1.0a3, out. 1.0 final is not out yet.
