### ISSUE TITLE
Image in markdown cell is not shown in pdf after exporting the notebook

### ISSUE THREAD

**Issue by kdeleeuw11** [jupyterlab/jupyterlab#5593]
Hi! Thanks for using JupyterLab.

If you are reporting an issue with JupyterLab, please use the [GitHub issue](https://github.com/jupyterlab/jupyterlab/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

The JupyterLab team and Project Jupyter value our community, and JupyterLab
follows the Jupyter [Community Guides](https://jupyter.readthedocs.io/en/latest/community/content-community.html).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser [e.g. chrome 69.0, firefox 62.0]
- JupyterLab [e.g. 0.34.2]

**Additional context**

If available, please include the following details:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser console here.
</pre>
</details>

**Comment by kdeleeuw11** [comment]
When exporting a notebook to pdf, an image in a markdown cell is not included in the pdf. Eg. markdown cell:
Below an image
<img src='figs/fig_1.png'>
Above an image

In the pdf only the lines "Below an image" and "Above an image" are shown, but not the image.

When the same image is entered in the notebook in a code cell, the image is shown in the pdf. E.g. code cell:
from IPython.display import Image
Image('figs/fig_1.png')

**Comment by t-makaro** [comment]
This is a known issue with nbconvert. See https://github.com/jupyter/nbconvert/issues/552.

**Comment by jasongrout** [comment]
Thanks @kdeleeuw11 for pointing this out, and thanks @t-makaro for the reference. Let's move the conversation over to jupyter/nbconvert#552 since that is the root of the issue.
