### ISSUE TITLE
Some indication that a cell's output no longer corresponds to cell's input.

### ISSUE THREAD

**Issue by cossio** [jupyterlab/jupyterlab#5597]
Suppose I:

1. Write an input cell and execute it, generating an output cell.
2. Modifiy the input cell code without running it again.

After a while I look at this cell again and get confused, because I might assume that the output corresponds to the input code, which is not true anymore.

In Mathematica, when an input cell is modified, it loses the cell number. For example:

![image](https://user-images.githubusercontent.com/10637482/48101876-85ee6e00-e1f6-11e8-8bd2-dd2f36d150d8.png)

Then I modify the input cell:

![image](https://user-images.githubusercontent.com/10637482/48101886-8f77d600-e1f6-11e8-80dc-f3d1c633cef8.png)

Notice how the input cell's `In[1]` is gone, and the output is slightly grayed out. This alerts me that I have not evaluated the new input cell contents and therefore the output might not match.

Hopefully something similar can be implemented in Jupyter?

**Comment by manuel-ruiz-23** [comment]
@meeseeksdev tag type:Enhancement

**Comment by manuel-ruiz-23** [comment]
I would like to work on this. 

this is my proposal: 
![screenshot from 2018-11-07 09-49-16](https://user-images.githubusercontent.com/16631761/48146602-96442e80-e272-11e8-9b25-0f452b9e8a72.png)
![screenshot from 2018-11-07 09-48-50](https://user-images.githubusercontent.com/16631761/48146610-993f1f00-e272-11e8-9d11-947274c5d191.png)

any thoughts?

**Comment by vidartf** [comment]
@cossio `In` and `Out` are defined for the ipython kernel at least. So you access them by `In[1]` etc.

**Comment by bollwyvl** [comment]
Yeah, hooking the execute_reply to store the code that generated some
outputs is really interesting. Of course, the frontend could just add it.
If you got fifty outputs, though, you wouldn't want 50 copies of the code,
so it might have to go in cell meta, and changing outputs isn't nice,
anyway.

This would give some interesting metrics, as you could know, of a given
ipynb execution state, which cells hadn't been executed and which cells
showed output different from what was executed... And even show colored
diffs.

Of course, for version control purposes, this would compound the diff
problem. I would see the overall function being like timings, I guess, that
some people just wouldn't want.

**Comment by fcollonval** [comment]
Fixed by #10296
