### ISSUE TITLE
Define what parts of CSS selectors are public API

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#5600]
There are some CSS selectors that are part of the public JL API, because Phosphor uses them. These include:

* Keyboard Shortcuts
* Context Menus

So we should make sure we preserve these semantic selectors, even if we change to using non-css classes for styling.

**Comment by markellekelly** [comment]
Here are the selectors currently being used in keyboard shortcuts: 
- .jp-FileEditor
- .jp-Notebook
- .jp-SettingEditor
- .jp-ImageViewer
- .jp-CodeConsole
- .jp-CodeConsole-promptCell
- .jp-Activity
- .jp-InputArea-editor
- .jp-mod-has-primary-selection
- .jp-mod-in-leading-whitespace
- .jp-mod-completer-enabled
- .jp-mod-tooltip
- .jp-mod-editMode
- .jp-mod-commandMode
Shortcuts also use:
- [data-jp-undoer]
- [data-jp-kernel-user]
- [data-jp-code-runner]
- [data-jp-interaction-mode]

Not including those already listed under shortcuts, context menus currently use:
- .jp-SideBar
- .jp-Cell
- .jp-CodeCell
- .jp-Terminal
- .jp-CodeConsole-content
- .jp-DirListing-content
- .jp-DirListing-item
- .jp-mod-current
The selectors also include:
- [data-type]
- [data-isdir]

**Comment by tgeorgeux** [comment]
Are there any other selectors that aren't on this list that we think ought to be publicly documented? Conversely, is there anything on this list that we ought not to treat as 'public'?

**Comment by jasongrout** [comment]
I think we should also list the data-theme-light and data-theme-name selectors as public for theming.

**Comment by ellisonbg** [comment]
Thanks for hunting all these down! Where should we document these? In the dev docs? Are there any of these that look odd, or that we don't want to be public?

**Comment by tgeorgeux** [comment]
To do on this issue:

- [ ] Amend the CSS Selector section of the docs to documents with the above selectors.
- [ ] Add a section for the data-theme-light/dark selectors in the theme section of the documents.

**Comment by markellekelly** [comment]
Here are some tentative descriptions of the CSS selectors. I would appreciate any insight on .jp-Activity as well as any corrections or feedback.

The following commonly useful CSS class names are treated as public.

CSS variables that target widgets and their children
•	.jp-FileEditor: applied to file editors
•	.jp-Notebook: applied to notebooks
•	.jp-SettingEditor: applied to setting editors
•	.jp-ImageViewer: applied to image viewers
•	.jp-SideBar: applied to sidebars
•	.jp-Cell: applied to cells
•	.jp-CodeCell: applied to code cells
•	.jp-Terminal: applied to terminals
•	.jp-CodeConsole: applied to consoles
•	.jp-CodeConsole-promptCell: applied to active prompt cells in consoles
•	.jp-CodeConsole-content: applied to content panels in consoles
•	.jp-InputArea-editor: applied to cell input area editors
•	.jp-DirListing-content: applied to contents of file browser directory listings
•	.jp-DirListing-item: applied to items in file browser directory listings
•	.jp-Activity: unsure of its exact use 

CSS classes that are used to modify the state of a widget
•	.jp-mod-has-primary-selection: applied to editors that have a primary selection
•	.jp-mod-in-leading-whitespace: applied to editors that have a selection within the beginning whitespace of a line
•	.jp-mod-completer-enabled: applied to editors that can host a completer 
•	.jp-mod-tooltip: applied to the body when a tooltip exists on the page
•	.jp-mod-editMode: applied to a notebook in edit mode
•	.jp-mod-commandMode: applied to a notebook in command mode
•	.jp-mod-current: applied to elements on the current document only

CSS classes that describe elements
•	[data-jp-undoer]: applied to widgets that can undo
•	[data-jp-kernel-user]: applied to widgets that have an active kernel
•	[data-jp-code-runner]: applied to widgets that can run code
•	[data-jp-interaction-mode=”terminal”]: applied when a terminal is in use
•	[data-jp-interaction-mode=”notebook”]: applied when a notebook is in use
•	[data-type]: applied to describe the type of element, such as “document-title”, ”submenu”, ”inline”
•	[data-isdir]: applied to describe whether file browser items are directories

**Comment by ellisonbg** [comment]
`.jp-Activity` is added to anything in the main work area - we call then "activities" as some of them are not documents (the console).

**Comment by ian-r-rose** [comment]
Fixed by #6082
