### ISSUE TITLE
Figure out if tree shaking is working with blueprint

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#5601]
https://webpack.js.org/guides/tree-shaking/

See if we just use component whether it drops the ones we don't use from the bundle

**Comment by gnestor** [comment]
Here's an example of importing individual modules: https://github.com/jupyterlab/jupyterlab/pull/5538/commits/bd080f2b7561ae505883334b8a529246438368ba

**Comment by gnestor** [comment]
Doing this saves us about 0.5mb in bundle size. I also posted some findings about how blueprint affects our bundle size at https://github.com/jupyterlab/jupyterlab/issues/5170#issuecomment-436740472

**Comment by bollwyvl** [comment]
Thanks for running that down. I assume that's the dev build: what about the
prod? if we're counting bytes, it's not quite fair, as it might just be
really well documented... While I guess there's the approaches of gzip. And
service workers. And http2. But at then end of it, the more we add at the
bottom of the stack, the harder it gets to claw back real world performance.

I guess the "real" measure is the impact on a binder load... To that end,
I've often wished the jupyterlab/jupyterlab binder was a Dev environment of
the current branch with a hot dev watch with some analysis tools rather
than "last thing on conda-forge", but we'd probably need dev/master for
that, as the red line is scary.

**Comment by saulshanabrook** [comment]
> I guess the "real" measure is the impact on a binder load...

I think we do something like this Lighthouse, to test more of a real user loading time (
https://github.com/jupyterlab/jupyterlab/issues/4825)

**Comment by jasongrout** [comment]
Should we put this in the 1.0 or the future milestone?

**Comment by saulshanabrook** [comment]
I just put it in future. Ideally I would like to work on this for 1.0, but we will see if I have time.

**Comment by tgeorgeux** [comment]
Closing since we're not using blueprint.
