### ISSUE TITLE
Disable back button

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterlab/jupyterlab#5605]
When working in Jupyter Lab I occasionally accidentally press the back button on my mouse which causes the page to try and go back to the previous page (usually Jupyter Hub in my case). This can result in loss of work.

Is it possible to capture that event and suppress it? Or perhaps even re-use it, such as navigating higher up the hierarchy in the file browser?

**Comment by jasongrout** [comment]
Excellent idea! I'm adding this as a good (advanced?) first issue. I'd suggest capturing the back button and just having a small dialog that warns that you are navigating away (perhaps this should also be triggered on window close?). Perhaps with an option to disable the dialog.

Perhaps the best place to put this code is in the application package: https://github.com/jupyterlab/jupyterlab/blob/6a00f4f476271379e0c04b480f04d5d2a1f9b868/packages/application-extension/src/index.tsx

**Comment by tgeorgeux** [comment]
I completely agree, let me work on the copy for the modal. I'll update this with a simple prototype.

**Comment by jasongrout** [comment]
Actually, I noticed we *do* have a modal already. Try typing something into a document and not saving it, then try to close the browser tab. I get
<img width="766" alt="screen shot 2018-11-14 at 3 01 18 pm" src="https://user-images.githubusercontent.com/192614/48518328-2e678800-e81e-11e8-9d4f-76d6977c9778.png">

**Comment by jasongrout** [comment]
It seems that modal already comes up even if pressing the back button, but only if there is an unsaved document? Perhaps we should make it always come up when pressing the back button?

**Comment by jacobtomlinson** [comment]
Yes I had noticed this. However even if the document is saved you can lose state such as ipywidgets when returning to the notebook. 

Having this pop up every time would be ok, but still a bit jarring.

**Comment by tgeorgeux** [comment]
![screen shot 2018-11-15 at 10 10 30 am](https://user-images.githubusercontent.com/22109376/48586849-f3308c00-e8e5-11e8-9a12-b18db6243834.png)

So is this just calling a generic browser modal as opposed to something within Phosphor? Mine looks different than yours @jasongrout

**Comment by blink1073** [comment]
It is a browser security feature, iirc no browser let's you change the message and they all have their own message.

**Comment by tgeorgeux** [comment]
Ah, got it. So we just need to call the browser's warning message when the
back button is activated?

**Comment by blink1073** [comment]
Right, we currently only do that when the app state is *dirty*, cf https://github.com/jupyterlab/jupyterlab/blob/44c3407ed872f030381adc3986713d74fd32312a/packages/application-extension/src/index.tsx#L163

**Comment by seawolf42** [comment]
Agreed, this is working with reload, back, and also entering a new address in the address bar. I think the only open question is what constitutes "dirty" and does that logic need to change.

@jasongrout I suggest removing the "good first issue" tag as the easy part of this is already working as requested.

**Comment by jasongrout** [comment]
> I suggest removing the "good first issue" tag as the easy part of this is already working as requested.

Agreed.

**Comment by jasongrout** [comment]
Closing as resolved, since we do warn the user if the application is in dirty state. Please comment here if you'd like to continue discussing this.

**Comment by jacobtomlinson** [comment]
> However even if the document is saved you can lose state such as ipywidgets when returning to the notebook.

I still feel like this is an issue. If I accidentally hit back with a saved notebook I generally have to restart my kernel and run through my notebook again to get back to the state I was in.
