### ISSUE TITLE
Cannot Import unicodecsv into jupyter lab in IBM Power AI 

### ISSUE THREAD

**Issue by Blackman9t** [jupyterlab/jupyterlab#5607]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-e504739316f4> in <module>()
----> 1 import unicodecsv
      2 
      3 ## Longer version of code (replaced with shorter, equivalent version below)
      4 
      5 # enrollments = []

ModuleNotFoundError: No module named 'unicodecsv'

yet I can import and use it in ibmcognitiveclass.ai

Please help

**Comment by jasongrout** [comment]
Does it work in the classic notebook?

It seems that the issue might be that unicodecsv is not installed in your python kernel, and has nothing to do with JupyterLab.

**Comment by ellisonbg** [comment]
çlosing, let us know if more information emerges about this.
