### ISSUE TITLE
Add pep8 to jupyter lab IDE

### ISSUE THREAD

**Issue by Rpygamer** [jupyterlab/jupyterlab#5611]
Hello, 
is there any way/extension to enable pep8 code style test in the JupiterLab IDE ?

**Comment by jtpio** [comment]
There is a JupyterLab extension with support for Black, yapf and autopep8:

https://github.com/ryantam626/jupyterlab_code_formatter

**Comment by jasongrout** [comment]
Thanks for pointing it out @jtpio!
