### ISSUE TITLE
Accepting half the "0" keystrokes 

### ISSUE THREAD

**Issue by benureau** [jupyterlab/jupyterlab#5612]
**Describe the bug**
In a notebook, in any cell, when editing, only one every two zero keystroked is inputed in the cell. If I tap "0000", only "00" appears. To be clear, of, each pair, the first zero get swallowed. This does not happen with any other digit (nor with `jupyter notebook` on the same notebook, nor with any other application or webpage).

**Desktop (please complete the following information):**

- OS: macOS 10.14.1
- Browser: Chrome Version 70.0.3538.77
- JupyterLab: 0.35.4

**Additional context**

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/Users/fcyb/.pyenv/versions/3.7.1/bin
	/Users/fcyb/.pyenv/versions/3.7.1/bin
	/usr/local/Cellar/pyenv/1.2.8/libexec
	/usr/local/opt/coreutils/libexec/gnubin
	/usr/local/sbin
	~/.bin/
	/Users/fcyb/.pyenv/shims
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/Applications/VMware Fusion.app/Contents/Public
	/Library/TeX/texbin
	/usr/local/MacGPG2/bin
	/opt/X11/bin

sys.path:
	/Users/fcyb/.pyenv/versions/3.7.1/bin
	/Users/fcyb/.pyenv/versions/3.7.1/lib/python37.zip
	/Users/fcyb/.pyenv/versions/3.7.1/lib/python3.7
	/Users/fcyb/.pyenv/versions/3.7.1/lib/python3.7/lib-dynload
	/Users/fcyb/.pyenv/versions/3.7.1/lib/python3.7/site-packages

sys.executable:
	/Users/fcyb/.pyenv/versions/3.7.1/bin/python3.7

sys.version:
	3.7.1 (default, Nov  6 2018, 14:25:35)
	[Clang 10.0.0 (clang-1000.11.45.5)]

platform.platform():
	Darwin-18.2.0-x86_64-i386-64bit

which -a jupyter:
	/Users/fcyb/.pyenv/versions/3.7.1/bin/jupyter
	/Users/fcyb/.pyenv/versions/3.7.1/bin/jupyter
	/Users/fcyb/.pyenv/shims/jupyter

pip list:
	Package           Version
	----------------- -------
	appnope           0.1.0
	backcall          0.1.0
	bleach            3.0.2
	decorator         4.3.0
	defusedxml        0.5.0
	entrypoints       0.2.3
	ipykernel         5.1.0
	ipython           7.1.1
	ipython-genutils  0.2.0
	jedi              0.13.1
	Jinja2            2.10
	jsonschema        2.6.0
	jupyter-client    5.2.3
	jupyter-core      4.4.0
	jupyterlab        0.35.4
	jupyterlab-server 0.2.0
	MarkupSafe        1.1.0
	mistune           0.8.4
	nbconvert         5.4.0
	nbformat          4.4.0
	notebook          5.7.0
	pandocfilters     1.4.2
	parso             0.3.1
	pexpect           4.6.0
	pickleshare       0.7.5
	pip               18.1
	prometheus-client 0.4.2
	prompt-toolkit    2.0.7
	ptyprocess        0.6.0
	Pygments          2.2.0
	python-dateutil   2.7.5
	pyzmq             17.1.2
	Send2Trash        1.5.0
	setuptools        39.0.1
	six               1.11.0
	terminado         0.8.1
	testpath          0.4.2
	tornado           5.1.1
	traitlets         4.3.2
	wcwidth           0.1.7
	webencodings      0.5.1
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 11:24:19.978 LabApp] Searching ['/Users/fcyb', '/Users/fcyb/.jupyter', '/Users/fcyb/.pyenv/versions/3.7.1/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 11:24:19.978 LabApp] Looking for jupyter_config in /etc/jupyter
[D 11:24:19.979 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 11:24:19.979 LabApp] Looking for jupyter_config in /Users/fcyb/.pyenv/versions/3.7.1/etc/jupyter
[D 11:24:19.979 LabApp] Looking for jupyter_config in /Users/fcyb/.jupyter
[D 11:24:19.979 LabApp] Looking for jupyter_config in /Users/fcyb
[D 11:24:19.980 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 11:24:19.980 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 11:24:19.980 LabApp] Looking for jupyter_notebook_config in /Users/fcyb/.pyenv/versions/3.7.1/etc/jupyter
[D 11:24:19.980 LabApp] Looking for jupyter_notebook_config in /Users/fcyb/.jupyter
[D 11:24:19.980 LabApp] Looking for jupyter_notebook_config in /Users/fcyb
[I 11:24:20.163 LabApp] The port 8888 is already in use, trying another port.
[D 11:24:20.167 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/etc/jupyter/jupyter_notebook_config.json
[D 11:24:20.167 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 11:24:20.168 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/Users/fcyb/.pyenv/versions/3.7.1/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/Users/fcyb/.pyenv/versions/3.7.1/etc/jupyter/jupyter_notebook_config.json
[D 11:24:20.168 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/Users/fcyb/.jupyter/jupyter_notebook_config.json
[I 11:24:20.172 LabApp] JupyterLab extension loaded from /Users/fcyb/.pyenv/versions/3.7.1/lib/python3.7/site-packages/jupyterlab
[I 11:24:20.172 LabApp] JupyterLab application directory is /Users/fcyb/.pyenv/versions/3.7.1/share/jupyter/lab
[W 11:24:20.173 LabApp] JupyterLab server extension not enabled, manually loading...
[I 11:24:20.176 LabApp] JupyterLab extension loaded from /Users/fcyb/.pyenv/versions/3.7.1/lib/python3.7/site-packages/jupyterlab
[I 11:24:20.176 LabApp] JupyterLab application directory is /Users/fcyb/.pyenv/versions/3.7.1/share/jupyter/lab
[I 11:24:20.177 LabApp] Serving notebooks from local directory: /Users/fcyb
[I 11:24:20.177 LabApp] The Jupyter Notebook is running at:
[I 11:24:20.177 LabApp] http://localhost:8889/?token=80f473de9c531d64e774b6ad4c28590415af025281c6d661
[I 11:24:20.177 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:24:20.185 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=80f473de9c531d64e774b6ad4c28590415af025281c6d661
[I 11:24:20.369 LabApp] Accepting one-time-token-authenticated connection from ::1
[D 11:24:20.373 LabApp] Using contents: services/contents
[D 11:24:20.387 LabApp] 200 GET /lab?token=95ddad066a4b43a94f56d767c9a6ca4a11a193a4f7eae2d2 (::1) 18.98ms
[D 11:24:20.469 LabApp] Path main.13de647526d0a582493b.js served from /Users/fcyb/.pyenv/versions/3.7.1/share/jupyter/lab/static/main.13de647526d0a582493b.js
[D 11:24:20.470 LabApp] 304 GET /lab/static/main.13de647526d0a582493b.js (::1) 2.06ms
[D 11:24:20.472 LabApp] Path vendors~main.10079ad9676c70f28097.js served from /Users/fcyb/.pyenv/versions/3.7.1/share/jupyter/lab/static/vendors~main.10079ad9676c70f28097.js
[D 11:24:20.473 LabApp] 304 GET /lab/static/vendors~main.10079ad9676c70f28097.js (::1) 1.63ms
[D 11:24:20.759 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:20.760 LabApp] Found kernel jnns2018 in /Users/fcyb/Library/Jupyter/kernels
[D 11:24:20.760 LabApp] Found kernel bgraph in /Users/fcyb/Library/Jupyter/kernels
[D 11:24:20.760 LabApp] Found kernel kounious2016 in /Users/fcyb/Library/Jupyter/kernels
[D 11:24:20.760 LabApp] Found kernel vbpmtrnn in /Users/fcyb/Library/Jupyter/kernels
[D 11:24:20.760 LabApp] Found kernel python3 in /Users/fcyb/.pyenv/versions/3.7.1/share/jupyter/kernels
[D 11:24:20.764 LabApp] 200 GET /api/kernelspecs?1541989460756 (::1) 5.38ms
[D 11:24:20.765 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:20.766 LabApp] 200 GET /api/terminals?1541989460758 (::1) 0.69ms
[D 11:24:20.802 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:20.806 LabApp] 200 GET /lab/api/settings/@jupyterlab/application-extension:sidebar?1541989460800 (::1) 3.66ms
[D 11:24:20.807 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:20.808 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1541989460803 (::1) 1.63ms
[D 11:24:20.809 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:20.811 LabApp] 200 GET /lab/api/settings/@jupyterlab/apputils-extension:themes?1541989460803 (::1) 2.13ms
[D 11:24:20.813 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:20.831 LabApp] 200 GET /lab/api/settings/@jupyterlab/shortcuts-extension:plugin?1541989460801 (::1) 17.95ms
[D 11:24:20.836 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:20.837 LabApp] 200 GET /api/sessions?1541989460833 (::1) 1.44ms
[D 11:24:20.851 LabApp] Path @jupyterlab/theme-light-extension/index.css served from /Users/fcyb/.pyenv/versions/3.7.1/share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.css
[D 11:24:20.852 LabApp] 304 GET /lab/api/themes/@jupyterlab/theme-light-extension/index.css (::1) 0.99ms
[D 11:24:21.153 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.160 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.172 LabApp] 200 GET /api/contents/?content=1&1541989461153 (::1) 14.02ms
[D 11:24:21.174 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.176 LabApp] 200 GET /lab/api/settings/@jupyterlab/extensionmanager-extension:plugin?1541989461161 (::1) 2.73ms
[D 11:24:21.180 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.183 LabApp] 200 GET /lab/api/settings/@jupyterlab/notebook-extension:tracker?1541989461173 (::1) 2.91ms
[D 11:24:21.187 LabApp] Accepting token-authenticated connection from ::1
[I 11:24:21.267 LabApp] Node v11.1.0

[D 11:24:21.324 LabApp] 200 GET /api/nbconvert?1541989461175 (::1) 141.10ms
[D 11:24:21.327 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.330 LabApp] 200 GET /lab/api/settings/@jupyterlab/codemirror-extension:commands?1541989461230 (::1) 4.19ms
[D 11:24:21.332 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.333 LabApp] 200 GET /api/sessions?1541989461234 (::1) 1.49ms
[D 11:24:21.336 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.341 LabApp] 200 GET /lab/api/settings/@jupyterlab/fileeditor-extension:plugin?1541989461177 (::1) 5.17ms
[I 11:24:21.341 LabApp] Build is up to date
[D 11:24:21.342 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.343 LabApp] 200 GET /lab/api/workspaces/lab?1541989461273 (::1) 1.44ms
[D 11:24:21.348 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.423 LabApp] 200 GET /api/nbconvert?1541989461226 (::1) 75.23ms
[D 11:24:21.424 LabApp] 200 GET /lab/api/build?1541989461151 (::1) 270.99ms
[D 11:24:21.425 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.426 LabApp] 200 GET /api/contents/Untitled.ipynb?content=0&1541989461370 (::1) 1.20ms
[D 11:24:21.427 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.429 LabApp] 204 PUT /lab/api/workspaces/lab?1541989461373 (::1) 2.84ms
[D 11:24:21.583 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.592 LabApp] 200 GET /api/contents/?content=1&1541989461581 (::1) 9.03ms
[D 11:24:21.593 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.602 LabApp] 200 GET /api/contents/Untitled.ipynb?type=notebook&content=1&1541989461581 (::1) 9.03ms
[D 11:24:21.630 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.636 LabApp] 200 GET /api/contents/Untitled.ipynb/checkpoints?1541989461627 (::1) 6.32ms
[D 11:24:21.638 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.639 LabApp] 200 GET /api/contents/Untitled.ipynb/checkpoints?1541989461627 (::1) 1.40ms
[D 11:24:21.641 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:21.643 LabApp] 200 GET /api/contents/Untitled.ipynb/checkpoints?1541989461632 (::1) 2.60ms
[D 11:24:22.368 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:22.372 LabApp] 204 PUT /lab/api/workspaces/lab?1541989462363 (::1) 4.06ms
[D 11:24:23.840 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:23.874 LabApp] Starting kernel: ['/Users/fcyb/.pyenv/versions/3.7.1/bin/python3.7', '-m', 'ipykernel_launcher', '-f', '/Users/fcyb/Library/Jupyter/runtime/kernel-192bec5c-3cd9-4937-a750-f7d89a98e348.json']
[D 11:24:23.879 LabApp] Connecting to: tcp://127.0.0.1:56010
[D 11:24:23.880 LabApp] Connecting to: tcp://127.0.0.1:56008
[I 11:24:23.883 LabApp] Kernel started: 192bec5c-3cd9-4937-a750-f7d89a98e348
[D 11:24:23.883 LabApp] Kernel args: {'kernel_name': 'python3', 'cwd': '/Users/fcyb'}
[D 11:24:23.884 LabApp] 201 POST /api/sessions?1541989463833 (::1) 44.74ms
[D 11:24:23.892 LabApp] Initializing websocket connection /api/kernels/192bec5c-3cd9-4937-a750-f7d89a98e348/channels
[D 11:24:23.893 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:23.894 LabApp] Requesting kernel info from 192bec5c-3cd9-4937-a750-f7d89a98e348
[D 11:24:23.894 LabApp] Connecting to: tcp://127.0.0.1:56007
[D 11:24:24.193 LabApp] Initializing websocket connection /api/kernels/192bec5c-3cd9-4937-a750-f7d89a98e348/channels
[D 11:24:24.194 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 11:24:24.195 LabApp] Waiting for pending kernel_info request
[D 11:24:24.266 LabApp] activity on 192bec5c-3cd9-4937-a750-f7d89a98e348: status
[D 11:24:24.374 LabApp] activity on 192bec5c-3cd9-4937-a750-f7d89a98e348: status
[D 11:24:24.375 LabApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.1', 'implementation': 'ipython', 'implementation_version': '7.1.1', 'language_info': {'name': 'python', 'version': '3.7.1', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': "Python 3.7.1 (default, Nov  6 2018, 14:25:35) \nType 'copyright', 'credits' or 'license' for more information\nIPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.\n", 'help_links': [{'text': 'Python Reference', 'url': 'https://docs.python.org/3.7'}, {'text': 'IPython Reference', 'url': 'https://ipython.org/documentation.html'}, {'text': 'NumPy Reference', 'url': 'https://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy Reference', 'url': 'https://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib Reference', 'url': 'https://matplotlib.org/contents.html'}, {'text': 'SymPy Reference', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas Reference', 'url': 'https://pandas.pydata.org/pandas-docs/stable/'}]}
[I 11:24:24.376 LabApp] Adapting to protocol v5.1 for kernel 192bec5c-3cd9-4937-a750-f7d89a98e348
[I 11:24:24.376 LabApp] Adapting to protocol v5.1 for kernel 192bec5c-3cd9-4937-a750-f7d89a98e348
[D 11:24:24.377 LabApp] activity on 192bec5c-3cd9-4937-a750-f7d89a98e348: status
[D 11:24:24.378 LabApp] 101 GET /api/kernels/192bec5c-3cd9-4937-a750-f7d89a98e348/channels?session_id=d2e19fb4-76ee-42be-8f48-1e621b7ab1f4&token=80f473de9c531d64e774b6ad4c28590415af025281c6d661 (::1) 486.55ms
[D 11:24:24.378 LabApp] Opening websocket /api/kernels/192bec5c-3cd9-4937-a750-f7d89a98e348/channels
[D 11:24:24.378 LabApp] Getting buffer for 192bec5c-3cd9-4937-a750-f7d89a98e348
[D 11:24:24.379 LabApp] Connecting to: tcp://127.0.0.1:56007
[D 11:24:24.379 LabApp] Connecting to: tcp://127.0.0.1:56008
[D 11:24:24.380 LabApp] Connecting to: tcp://127.0.0.1:56009
[D 11:24:24.382 LabApp] 101 GET /api/kernels/192bec5c-3cd9-4937-a750-f7d89a98e348/channels?session_id=0370b7ee-802e-47a8-8232-d23173be315e&token=80f473de9c531d64e774b6ad4c28590415af025281c6d661 (127.0.0.1) 189.18ms
[D 11:24:24.382 LabApp] Opening websocket /api/kernels/192bec5c-3cd9-4937-a750-f7d89a98e348/channels
[D 11:24:24.383 LabApp] Getting buffer for 192bec5c-3cd9-4937-a750-f7d89a98e348
[D 11:24:24.383 LabApp] Connecting to: tcp://127.0.0.1:56007
[D 11:24:24.383 LabApp] Connecting to: tcp://127.0.0.1:56008
[D 11:24:24.384 LabApp] Connecting to: tcp://127.0.0.1:56009
[D 11:24:24.388 LabApp] activity on 192bec5c-3cd9-4937-a750-f7d89a98e348: status
[D 11:24:24.393 LabApp] activity on 192bec5c-3cd9-4937-a750-f7d89a98e348: status
[D 11:24:24.396 LabApp] activity on 192bec5c-3cd9-4937-a750-f7d89a98e348: status
[D 11:24:24.400 LabApp] activity on 192bec5c-3cd9-4937-a750-f7d89a98e348: status
[D 11:24:24.402 LabApp] Path base/images/favicon-busy-1.ico served from /Users/fcyb/.pyenv/versions/3.7.1/lib/python3.7/site-packages/notebook/static/base/images/favicon-busy-1.ico
[D 11:24:24.402 LabApp] 304 GET /static/base/images/favicon-busy-1.ico (::1) 1.22ms
[D 11:24:24.403 LabApp] Websocket closed 192bec5c-3cd9-4937-a750-f7d89a98e348:0370b7ee-802e-47a8-8232-d23173be315e
[D 11:24:24.406 LabApp] 304 GET /static/base/images/favicon-busy-1.ico (::1) 0.99ms
[D 11:24:30.769 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:30.771 LabApp] 200 GET /api/sessions?1541989470762 (::1) 2.34ms
[D 11:24:30.774 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:30.775 LabApp] 200 GET /api/terminals?1541989470763 (::1) 1.38ms
[D 11:24:32.159 LabApp] Accepting token-authenticated connection from ::1
[D 11:24:32.172 LabApp] 200 GET /api/contents/?content=1&1541989472155 (::1) 14.11ms
</pre>
</details>

**Comment by ian-r-rose** [comment]
I am also unable to reproduce this. I had the thought that it might be related to our keyboard shortcut for restarting the kernel (`0,0`), but that seems not to be the case for me...

**Comment by benureau** [comment]
Ok, I think I understand now. The selector is not the right one. It should be `[data-jp-kernel-user]:focus`? I carelessly copied over and edited the system default: 
```
    "runmenu:restart-and-run-all": {
      "command": "runmenu:restart-and-run-all",
      "keys": [
        ""
      ],
      "selector": "[data-jp-code-runner]",
      "title": "Restart Kernel and Run All",
      "category": "Run Menu"
    },
```
whereas the restart action default is defined as:
```
    "kernelmenu:restart": {
      "command": "kernelmenu:restart",
      "keys": [
        "0",
        "0"
      ],
      "selector": "[data-jp-kernel-user]:focus",
      "title": "Restart Kernel",
      "category": "Kernel Operations"
    },
```
I was a bit confused. Restart and Run All appears in both kernel and run menus, but is defined as a run menu in the configuration shortcut.

**Comment by ian-r-rose** [comment]
Hah, yes, we had a discussion at the time about whether it was more confusing or more useful to have that item in both menus. It seems it may be the former.

Does that change in the selector fix things for you? Focus can be an *extremely* subtle issue in the notebook, especially when it comes to edit/command mode and keyboard shortcuts.

**Comment by benureau** [comment]
Yes it does work for me now. I could not figure out how to get rid of the confirmation dialog, the same way I did in jupyter notebook. But I can live with that. Thanks. You can close this issue as far as I am concerned. 

Any documentation I could consult to understand this better by the way?

**Comment by jasongrout** [comment]
Thanks for following up. We'll be documenting those selectors (see #5600).

**Comment by ian-r-rose** [comment]
See also #5617 for some discussion of whether to allow dialogs to stop warning you. At the moment it is not possible (at least, not without writing an extension).
