### ISSUE TITLE
Make config errors fatal

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#5614]
Hi,

When jupyter is misconfigured, it warns you but does not fail. Can we make jupyter fail fast or have an option to verify the configs are valid before starting? Without this, it is very easy to miss errors.

For example, if I have a syntax error like this in my local `jupyter_notebook_config.py`:
```
c.LabApp.app_dir=/foo/bar
```
Above I did not include quotes by accident. Jupyter will tell me there is a syntax error in that config, then  start:
```
ERROR 17:46:06 Exception while loading config file /path/to/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
    ....
      File "/path/to/.jupyter/jupyter_notebook_config.py", line 781
        c.LabApp.app_dir=/foo/bar
                         ^
    SyntaxError: invalid syntax
INFO 17:50:16 [jupyter_nbextensions_configurator] enabled 0.2.8
INFO 17:50:16 JupyterLab beta preview extension loaded from /usr/...
```

**Comment by Zsailer** [comment]
Hi @mlucool 

Thanks for pointing this out. This is a relatively simple change to make (see #5716); however, it may need some discussion (as it will change the default behavior of jupyterlab). I'm not sure if this was as design choice by earlier developers of jupyterlab/notebook. 

I've opened #5716 to see what others think.

**Comment by goanpeca** [comment]
I think this has been implemented as part of https://github.com/jupyter/jupyter_core/pull/149?

Is this the case @mlucool?

**Comment by mlucool** [comment]
Yup!
