### ISSUE TITLE
playing MIDI files does not appear to work  in Lab, when it worked in Notebook

### ISSUE THREAD

**Issue by blakewest** [jupyterlab/jupyterlab#5615]
**Describe the bug**
It seems like the midi player that is showing fine with Jupyter Notebook does not seem to work with Jupyter Lab (https://github.com/jupyterlab/jupyterlab).

**To Reproduce**

```
jupyter lab
```
Then open up a new notebook with python 3.6 kernel, I tried the following:

```
from music21 import converter
melody = converter.parse("tinynotation: 3/4 c4 d8 f g16 a g f#")
melody.show('midi')
```

I do not see the player being displayed. If I use "jupyter notebook" it seems to work fine.

**Expected behavior**
A "player" would appear and play the file. Like below...

**Screenshots**
![image](https://user-images.githubusercontent.com/2524396/48383366-46ae9a00-e69a-11e8-8957-29fb33e9513f.png)

Instead.. I see this...
![image](https://user-images.githubusercontent.com/2524396/48383417-7e1d4680-e69a-11e8-893d-e95dddc9e3eb.png)

**Desktop (please complete the following information):**

- OS: Mac OSX (10.13.6)
- Browser Chrome 69.0
- JupyterLab 4.4.0 (from doing `jupyter --version`)

**Additional context**

If available, please include the following details:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.

$ jupyter troubleshoot
$PATH:
	/Users/blakewest/anaconda/envs/music_engine/bin
	/Users/blakewest/anaconda/envs/music_engine/bin
	/Users/blakewest/Desktop/google-cloud-sdk/bin
	/Users/blakewest/.rvm/gems/ruby-2.2.3/bin
	/Users/blakewest/.rvm/gems/ruby-2.2.3@global/bin
	/Users/blakewest/.rvm/rubies/ruby-2.2.3/bin
	/Users/blakewest/.node/bin
	/Users/blakewest/.pyenv/shims
	/Users/blakewest/npm/bin
	/Users/blakewest/.node/bin
	/Users/blakewest/utils
	/Users/blakewest/awseb
	/Users/blakewest/bin
	/usr/local/Cellar/ruby/2.1.1_1/bin
	/usr/local/bin
	/usr/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/opt/ImageMagick/bin
	/Users/blakewest/.rvm/bin
	/Users/blakewest/.rvm/bin

sys.path:
	/Users/blakewest/anaconda/envs/music_engine/bin
	/Users/blakewest/anaconda/envs/music_engine/lib/python36.zip
	/Users/blakewest/anaconda/envs/music_engine/lib/python3.6
	/Users/blakewest/anaconda/envs/music_engine/lib/python3.6/lib-dynload
	/Users/blakewest/anaconda/envs/music_engine/lib/python3.6/site-packages

sys.executable:
	/Users/blakewest/anaconda/envs/music_engine/bin/python3.6

sys.version:
	3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:55:02) 
	[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]

platform.platform():
	Darwin-17.7.0-x86_64-i386-64bit

which -a jupyter:
	/Users/blakewest/anaconda/envs/music_engine/bin/jupyter
	/Users/blakewest/anaconda/envs/music_engine/bin/jupyter

pip list:
	Package           Version   
	----------------- ----------
	appnope           0.1.0     
	attrs             18.2.0    
	backcall          0.1.0     
	bleach            3.0.2     
	certifi           2018.10.15
	decorator         4.3.0     
	entrypoints       0.2.3     
	ipykernel         5.1.0     
	ipython           7.1.1     
	ipython-genutils  0.2.0     
	jedi              0.13.1    
	Jinja2            2.10      
	jsonschema        3.0.0a3   
	jupyter-client    5.2.3     
	jupyter-core      4.4.0     
	jupyterlab        0.35.4    
	jupyterlab-server 0.2.0     
	MarkupSafe        1.1.0     
	mistune           0.8.4     
	mkl-fft           1.0.6     
	mkl-random        1.0.1     
	music21           5.5.0     
	nbconvert         5.3.1     
	nbformat          4.4.0     
	notebook          5.7.0     
	numpy             1.15.4    
	pandas            0.23.4    
	pandocfilters     1.4.2     
	parso             0.3.1     
	pexpect           4.6.0     
	pickleshare       0.7.5     
	pip               18.1      
	prometheus-client 0.4.2     
	prompt-toolkit    2.0.7     
	ptyprocess        0.6.0     
	Pygments          2.2.0     
	pyknon            1.2       
	pyrsistent        0.14.5    
	python-dateutil   2.7.5     
	pytz              2018.7    
	pyzmq             17.1.2    
	Send2Trash        1.5.0     
	setuptools        40.5.0    
	six               1.11.0    
	terminado         0.8.1     
	testpath          0.4.2     
	tornado           5.1.1     
	traitlets         4.3.2     
	wcwidth           0.1.7     
	webencodings      0.5.1     
	wheel             0.32.2
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>
![image](https://user-images.githubusercontent.com/2524396/48383513-e2400a80-e69a-11e8-8ca2-e7900d7eb810.png)

<details><summary>Browser Output</summary>
<pre>

</pre>
![image](https://user-images.githubusercontent.com/2524396/48383505-d94f3900-e69a-11e8-89a0-0f39a9486600.png)

</details>

**Comment by jasongrout** [comment]
What a cool package! It looks like music21 doesn't support JupyterLab yet. Here is where it supports the classic notebook: https://github.com/cuthbertLab/music21/blob/1762b9b1ac12a63ea19eba356cbe2ebd8d49e7cc/music21/converter/subConverters.py#L280-L399
It looks like someone will need to write a JupyterLab mimerender extension to understand midi. Perhaps they can use the built-in browser support for midi? I'll tag this as "Extension idea".

**Comment by bollwyvl** [comment]
Web Midi is a standard, not widely implemented... Music21 preferentially
uses the Jazz polyfill, which is a plugin. But yeah, this would be really
cool! but also a pretty big challenge... Looks like it works by calling it
to GitHub at runtime with require...

**Comment by psychemedia** [comment]
In passing, as well as playing music, `music21` has support for rendering musical scores. There's a stalled open PR that handles this in a nice JS rendering way here: https://github.com/cuthbertLab/music21/pull/326

**Comment by aishenri** [comment]
It doesn't either works in jupyter notebook, the player is displayed (badly) and no music is getting out !

**Comment by michaelharms** [comment]
I have the same problem currently and found a workaround for myself, 
maybe it helps other people here as well.

I use the StreamPlayer class from music21 (requires pygame to be installed):
https://web.mit.edu/music21/doc/moduleReference/moduleMidiRealtime.html

```python
def play_midi(file_path):
    mf = midi.MidiFile()
    mf.open(file_path)
    mf.read()
    mf.close()
    s = midi.translate.midiFileToStream(mf)
    sp = midi.realtime.StreamPlayer(s)
    sp.play()
```

This does not show a player with controls, but plays the midi upon cell execution.

**Comment by mscuthbert** [comment]
Thanks all!  I'm the principal developer of `music21` but I'm afraid I'm not going to have time to add significant new support until July 2020 because of another position at MIT taking my time till then.  I'm very happy however to take a fully featured and tested PR that I can just merge.  

I've seen some much better music21 to MIDI implementations recently -- for instance at https://orbichord.github.io/orbichord.html#module-orbichord.utils  

Thanks!

**Comment by asigalov61** [comment]
@bollwyvl @psychemedia @jasongrout @blakewest @mscuthbert 

Here is what works for me as of 06/08/2023 on ubuntu and JupyterLab

```
!sudo apt-get install -y fluidsynth
!pip install midi2audio
```

```
from midi2audio import FluidSynth
from IPython.display import Audio, display
```

```
FluidSynth("/usr/share/sounds/sf2/FluidR3_GM.sf2", 16000).midi_to_audio(str( 'midi.mid'), str( midi'.wav'))
display(Audio(str( 'midi.wav'), rate=16000))
```

**Comment by jtpio** [comment]
Just tried with the latest JupyterLab `4.3.0b3` release and the example code above:

```py
from music21 import converter
melody = converter.parse("tinynotation: 3/4 c4 d8 f g16 a g f#")
melody.show('midi')
```

And it now seems to be working well in JupyterLab!

![image](https://github.com/user-attachments/assets/75e6d424-d559-4578-b977-308fe9e9a78c)

So closing the issue as fixed. Feel free to open a new one here if there is an issue with JupyterLab, or on the `music21` repo directly otherwise. Thanks!
