### ISSUE TITLE
Incorrect rendering of code snippets in markdown lists

### ISSUE THREAD

**Issue by mdeff** [jupyterlab/jupyterlab#5616]
**Describe the bug**
In a Markdown cell, when a list contains code snippets, the snippets are not rendered with a grey background. The font is however correctly set to monospace.

**To Reproduce**
1. Put the following in a notebook markdown cell:
   ```
   * aaa `aaa`
   * bbb `bbb`
   ```
2. Render the cell with jupyterlab.

**Expected behavior**
The snippets should be typeset with monospace and appear on grey background.
It renders correctly on the regular notebook and nbviewer.

Here's a notebook that renders correctly on nbviewer and incorrectly on jupyterlab: <https://nbviewer.jupyter.org/github/mdeff/ntds_2018/blob/outputs/milestones/3_spectral_graph_theory.ipynb>

**Screenshots**
Incorrect rendering from JupyterLab:
![2018-11-13-10 06 17](https://user-images.githubusercontent.com/6806065/48403006-401d3280-e72d-11e8-9e85-f0df085f7bef.png)

Correct rendering from jupyter notebook and nbviewer:
![2018-11-13-10 06 54](https://user-images.githubusercontent.com/6806065/48403007-401d3280-e72d-11e8-825f-c4001099eab9.png)

Strangely, JupyterLab renders correctly when lists contain only one element:
![2018-11-13-10 06 31](https://user-images.githubusercontent.com/6806065/48403451-2a5c3d00-e72e-11e8-931e-d3339d570797.png)

**Desktop**
- OS: Arch Linux
- Browser: Firefox 62
- JupyterLab 0.34.9

**Comment by jasongrout** [comment]
Here it is in (approximately) current master, with an upgrade to the underlying marked library:
<img width="130" alt="screen shot 2018-11-13 at 7 49 46 am" src="https://user-images.githubusercontent.com/192614/48425169-1bb75b00-e719-11e8-81ca-d779e64fec14.png">

Inspecting the source, we have all the right rendered HTML (i.e., the `<code>` block is there), and you can see that the font is monospace for the code section. However, the background for code sections is white. This comes from this line: https://github.com/jupyterlab/jupyterlab/blob/6a00f4f476271379e0c04b480f04d5d2a1f9b868/packages/rendermime/style/index.css#L325 In that line, `var(--jp-layout-color0)` is a background color of white in the default theme, while the code block outside of the list is styled with https://github.com/jupyterlab/jupyterlab/blob/6a00f4f476271379e0c04b480f04d5d2a1f9b868/packages/rendermime/style/index.css#L333-L336 (one way to look at it is that the code block in the list is not inside of a `<p>`, so the styles at https://github.com/jupyterlab/jupyterlab/blob/6a00f4f476271379e0c04b480f04d5d2a1f9b868/packages/rendermime/style/index.css#L333-L336 are not applied.)

**Comment by jasongrout** [comment]
Setting as a good first issue, and CCing @tgeorgeux for any design guidance he might have.

**Comment by manuel-ruiz-23** [comment]
adding a <p> around the code block generates the following output 
![screenshot from 2018-11-14 16-41-17](https://user-images.githubusercontent.com/16631761/48520004-4ba35300-e82c-11e8-935f-e316443d48cd.png)
I think the correct solution would be to change 
```
background-color: var(--jp-layout-color0); 

for

background-color: var(--jp-layout-color2); 
```
the result of that modifications looks like this:
![screenshot from 2018-11-14 16-44-45](https://user-images.githubusercontent.com/16631761/48520113-ac329000-e82c-11e8-9d52-3cfc5eee9959.png)
The only thing missing would be the padding, adding the padding on jupyterlab/packages/rendermime/style/index.css line 330 does the trick, but I'm unsure if this modification would affect something else.
![screenshot from 2018-11-14 16-47-43](https://user-images.githubusercontent.com/16631761/48520251-282cd800-e82d-11e8-9341-162cb70e00bc.png)

**Comment by jasongrout** [comment]
How about just changing https://github.com/jupyterlab/jupyterlab/blob/6a00f4f476271379e0c04b480f04d5d2a1f9b868/packages/rendermime/style/index.css#L333 to be `.jp-RenderedHTMLCommon code {` ?

**Comment by jasongrout** [comment]
Thanks for bringing this up, @mdeff!

**Comment by mdeff** [comment]
You're welcome. Thanks for your amazing work on jupyterlab. A great tool with a great community. :)
