### ISSUE TITLE
Sreamlining dialog UX

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#5617]
There is the potential for a lot of dialogs in jupyterlab (as well as in classic notebooks). Sometimes, the dialogs can act more as speedbumps in your work than the safety stops they are intended as. As such, I think I see two patterns that can help alleviate this:
1. Have all commands that produce an "are you sure?" dialog take an argument that skips it, and ensure that one can bind shortcuts to supply that argument. It would be nice if this followed a consistent pattern for argument names.
2. Make a dialog utility / option to include a checkbox to "Remember my choice" / "Do not show this dialog again". This would store the choice in the settings, and any stored choice would automatically be returned.

**Comment by jasongrout** [comment]
Great idea!

**Comment by seawolf42** [comment]
I'm starting work on this.
