### ISSUE TITLE
500 Error when trying to open jupyter notebook via jupyterhub

### ISSUE THREAD

**Issue by phxedmond** [jupyterlab/jupyterlab#5618]
I dont have an issue when opening a notebook via standard jupyter.

I have everything I can think of up to date(including nbconvert).

It was working fine....

Any ideas would be appreciated 

Below is the error I get when I try and open a notebook 

> [E 2018-11-13 15:56:17.743 SingleUserNotebookApp web:1670] Uncaught exception GET /julia/user/edmond/notebooks/traffic_sources_python/testing.ipynb (10.8.149.109)
>     HTTPServerRequest(protocol='http', host='10.107.52.38', method='GET', uri='/julia/user/edmond/notebooks/traffic_sources_python/testing.ipynb', version='HTTP/1.1', remote_ip='10.8.149.109')
>     Traceback (most recent call last):
>       File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1590, in _execute
>         result = method(*self.path_args, **self.path_kwargs)
>       File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 3006, in wrapper
>         return method(self, *args, **kwargs)
>       File "/usr/local/lib/python3.5/dist-packages/notebook/notebook/handlers.py", line 59, in get
>         get_custom_frontend_exporters=get_custom_frontend_exporters
>       File "/usr/local/lib/python3.5/dist-packages/notebook/base/handlers.py", line 467, in render_template
>         return template.render(**ns)
>       File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 989, in render
>         return self.environment.handle_exception(exc_info, True)
>       File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 754, in handle_exception
>         reraise(exc_type, exc_value, tb)
>       File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
>         raise value.with_traceback(tb)
>       File "/usr/local/lib/python3.5/dist-packages/notebook/templates/notebook.html", line 1, in top-level template code
>         {% extends "page.html" %}
>       File "<template>", line 2, in top-level template code
>       File "/usr/local/lib/python3.5/dist-packages/notebook/templates/page.html", line 154, in top-level template code
>         {% block header %}
>       File "/usr/local/lib/python3.5/dist-packages/notebook/templates/notebook.html", line 120, in block "header"
>         {% for exporter in get_custom_frontend_exporters() %}
>       File "/usr/local/lib/python3.5/dist-packages/notebook/notebook/handlers.py", line 19, in get_custom_frontend_exporters
>         from nbconvert.exporters.base import get_export_names, get_exporter
>     ImportError: No module named 'nbconvert.exporters.base'
> [E 2018-11-13 15:56:17.745 SingleUserNotebookApp log:150] {
>       "Cookie": "jupyterhub-user-edmond=2|1:0|10:1542124505|22:jupyterhub-user-edmond|48:ZDFmOGRjYzYtZGMyMi00Mzk5LTk2NmItNDcyNDQxY2U0MTY4|6e3c966fb2620b889939e0dbcc2e7f3b6cb4fcee6133fd75912da86895c78a79; jupyter-hub-token-edmond=\"2|1:0|10:1541699296|24:jupyter-hub-token-edmond|44:YjFjOGQ2Y2NkOTk5NGNhYzhjMDk4NTE5ZGNmYWUzNzM=|ebcdb02658062d4ab39a985962a0975bbedfc9a3d42c8d69db71b56e89954d99\"; _xsrf=2|4464c1f4|074958e7e78ce3490d6b1048d1f754c5|1541702994; username-10-107-52-38-8888=\"2|1:0|10:1542039453|26:username-10-107-52-38-8888|44:MmQ3ZjllYTQ1OGYyNDk5ODg3Njc5YWFkYWNkOGFhMTQ=|483d02502e07cdedf33d54958c5006d5c15c6e07698d2227a4bdc4426f7bb14a\"; jupyterhub-session-id=5067b20a11824cbab169380ce7737762",
>       "Cache-Control": "max-age=0",
>       "Upgrade-Insecure-Requests": "1",
>       "X-Forwarded-For": "10.8.149.109",
>       "Connection": "upgrade",
>       "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
>       "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
>       "X-Real-Ip": "10.8.149.109",
>       "Host": "10.107.52.38",
>       "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36",
>       "Referer": "http://10.107.52.38/julia/user/edmond/tree/traffic_sources_python",
>       "Accept-Encoding": "gzip, deflate"
>     }
> [E 2018-11-13 15:56:17.745 SingleUserNotebookApp log:158] 500 GET /julia/user/edmond/notebooks/traffic_sources_python/testing.ipynb (edmond@10.8.149.109) 4.08ms

**Comment by jasongrout** [comment]
This is the JupyterLab repo. Did you mean to open this issue in the JupyterHub repo: https://github.com/jupyterhub/jupyterhub
