### ISSUE TITLE
Auto-save interval configuration

### ISSUE THREAD

**Issue by katsar0v** [jupyterlab/jupyterlab#5619]
Is there an option to set the interval of the auto-save feature? E.g. two minutes vs 30 seconds or 5 minutes. Would be also really nice to have, if not yet implemented.

**Comment by vidartf** [comment]
Is this guide still current? https://www.webucator.com/blog/2016/03/change-default-autosave-interval-in-ipython-notebook/

**Comment by ian-r-rose** [comment]
I think this would be a good target for an advanced new contributor. We currently allow the user to enable/disable autosaving via the document manager, but not customize the interval. Here is where autosaving can be turned on or off:
https://github.com/jupyterlab/jupyterlab/blob/6a00f4f476271379e0c04b480f04d5d2a1f9b868/packages/docmanager/src/manager.ts#L95-L113

And here is where that is exposed as a setting:
https://github.com/jupyterlab/jupyterlab/blob/6a00f4f476271379e0c04b480f04d5d2a1f9b868/packages/docmanager-extension/src/index.ts#L141-L144

One would implement a very similar new property on the document manager called `autosaveInterval` that the user could set via the settings system in `docmanager-extension`. Feel free to ask here if you have any questions.

@vidartf, I don't think that would work for lab.
