### ISSUE TITLE
I am not able to see autocomplete like feature and can't upgrade or change version of jupyterlab

### ISSUE THREAD

**Issue by anirudhagupta** [jupyterlab/jupyterlab#5624]
I am using Anaconda and using jupyterlab in it, I can't upgrade version 34 to 35. I am not seeing any autocomplete feature. 

Someone, please help me, how I can do that. Is there any way to get autocomplete in jupyterlab which come in latest anaconda.

Thanks

**Comment by jasongrout** [comment]
There are several different ways autocomplete is available in JupyterLab. How are you trying to access it?

Also, it looks like anaconda has the JupyterLab 0.35.3 package: https://anaconda.org/search?q=jupyterlab

**Comment by anirudhagupta** [comment]
![image](https://user-images.githubusercontent.com/35772421/48595734-0ee67180-e97c-11e8-9832-d1d6a9db6d9c.png)

@jasongrout  thanks for your reply.

please check the image,  I try to update from GUI, command and reinstall the software, still doesn't work. I see this when I was running. it shows me 34  to 34 same version to upgrade. Is there any settings that I need to check before upgrading to 0.35.

**Comment by jasongrout** [comment]
I'm not sure why your upgrade to jupyterlab 0.35 isn't working. Perhaps contact anaconda support?

I use the conda-forge packages, which we publish directly, rather than the anaconda packages: `conda install -c conda-forge jupyterlab`

**Comment by anirudhagupta** [comment]
@jasongrout  Thanks for your help,

I remove the conda and install it in python pip and it's work fine. I am missing autocomplete. now only autocomplete thing are pending.
