### ISSUE TITLE
How to comment on multiple lines of code?

### ISSUE THREAD

**Issue by PhilosopherZ** [jupyterlab/jupyterlab#5648]
How to **comment on multiple lines** of code?

**Comment by jasongrout** [comment]
It may be Command-/ on mac.

**Comment by PhilosopherZ** [comment]
thanks! @rosgori  @jasongrout  Why didn't I find this shortcut key in the commands? such as Multi-line indentation?   where are they? 
![image](https://user-images.githubusercontent.com/33093881/49226431-85c24680-f421-11e8-920a-9af446622d25.png)
