### ISSUE TITLE
Exclude node-fetch and ws using build tools

### ISSUE THREAD

**Issue by DonJayamanne** [jupyterlab/jupyterlab#5651]
Currently we're [Python Extension for VS Code](https://github.com/Microsoft/vscode-python) are bundling the `@jupyter/services` package in our extension.
When attempting to bundle this using WebPack we've found two modules `node-fetch` and `ws` do not get included in the bundle, as they arepulled in dynamically via `eval`. 

Rather than going down the path of `eval`, why not update the build scripts to avoid bundling `node-fetch` and `ws` using the `externals` option in WebPack.

**Comment by blink1073** [comment]
Hi @DonJayamanne, that is a fair point.  A PR would change these locations:

https://github.com/jupyterlab/jupyterlab/blob/0a0fbf9179814ee21c51ef15e20aeb4b1c94bdb8/packages/services/src/serverconnection.ts#L20

and 

https://github.com/jupyterlab/jupyterlab/blob/0a0fbf9179814ee21c51ef15e20aeb4b1c94bdb8/dev_mode/webpack.config.js#L102

and add those dependencies to the services package.
