### ISSUE TITLE
jupyter [build/labextension] install --dev-build cannot be set to false via CLI

### ISSUE THREAD

**Issue by andrew-humu** [jupyterlab/jupyterlab#5661]
#### Describe the bug
A few months ago, in #5099 the default value for the flag --dev-build was changed to True.  Unfortunately, (as far as I can tell) there's no way to unset this flag via the CLI now!

#### To Reproduce

1. install jupyterlab
2. run `jupyter labextension install <any extension> --dev-build=false`
3. jupyter complains with an error:

![image](https://user-images.githubusercontent.com/43152655/48881381-f5a15300-edc9-11e8-96dc-e4e7d80dbdcf.png)

#### Expected behavior
Jupyter installs the extension and rebuilds in production.

#### Additional context
This might be a separate conversation, but I was a little surprised that the default behaviour of installing an extension was to leave me with a development build.  I'm happy to leave that decision with the team though, as long as opting out is possible!

Follow-up question: Is it possible to opt-out via config file?  I haven't been able to work out what setting to set, or where to create a config file.

**Comment by Bidek56** [comment]
Is there a PR for this? The bundle size is huge in dev, we need to build prod. Thanks

**Comment by jasongrout** [comment]
See the PRs referenced above. Perhaps https://github.com/jupyterlab/jupyterlab/pull/5723 is helpful?

**Comment by Bidek56** [comment]
#5723 is not helpful, since "Merging is blocked" :)

**Comment by jasongrout** [comment]
Feel free to update the PR so it can merge :)

**Comment by jasongrout** [comment]
Actually, looks like it can merge. It's under review. Do you want to try it out and post your review to it?

**Comment by Bidek56** [comment]
I tried, `jupyter labextension install @jupyterlab/hub-extension@^0.12.0 --dev-build=False`, which seems to work until it gets to this error: 
Errored, use --debug for full output:                                               
ValueError:                                                                         
"@jupyterlab/hub-extension@0.12.0" is not compatible with the current JupyterLab    
Conflicting Dependencies:                                                           
JupyterLab              Extension              Package                              
>=1.0.0-alpha.6 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/application              
>=1.0.0-alpha.6 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/apputils                 

Sorry, I am novice when it comes to Jupyter source code, I wish I could help more.

**Comment by jasongrout** [comment]
Looks like the hub extension has not been upgraded to work with JupyterLab master.

**Comment by Bidek56** [comment]
I have found one that works: `jupyter labextension install @jupyterlab/google-drive --dev-build=False`
and I can confirm that `--dev-build=False` builds a prod and  `--dev-build=True` builds a dev.
If you can merge the PR, that would be great. Thanks for your help!!

**Comment by ian-r-rose** [comment]
Thanks for the report @Bidek56!
