### ISSUE TITLE
Get rid of npm and node

### ISSUE THREAD

**Issue by KOLANICH** [jupyterlab/jupyterlab#5662]
`npm`, `node` and whole JS ecosystem are fatally flawed. `npm` tends to put all the submodules into a subfolder (if one doesn't set it explicitly to use the system folder with `--global` flag) and many JS developers use packages recklessly, which causes bloat. Lot of malicious JS packages have been spotted in npm, some of them were once benign packages bought from their original authors and implanted with malware (python packages don't have better security, but much less malicious packages have been spotted in pypi).

All of these are good reasons to stay away of npm, node packages and whole ecosystem centered around them and do the JS development basing only on ECMA and W3C standards (only ECMA modules (they are supported by browsers), no bundlers, `babel`, other similar things and no bloaty unneeded frameworks like React or Angular).

So I ask you to reconsider usage of Node and its packages, or at least provide the basics, like `ipywidgets`, without using anything from `npm`.

**Comment by bollwyvl** [comment]
No arguments on many of the points, though the tone might be a bit aggressive. We've spent the last few years trying to bring the project more in line with the workflows that are used by the millions of developers that have chosen to build useful things on top of the node ecosystem, and _not_ requiring lots of special tricks.

> do the JS development basing only on ECMA and W3C standards (only ecma modules (they are supported by browsers)

This is mostly accurate at this point. Firefox ESR 60 just started suppoting

**Comment by KOLANICH** [comment]
>This is thousands of http requests, even if (especially if) we rewrite everything. >Aha! But what about http/2? Sure, so we'll go to a pre-release version of tornado that supports it, and require every user to run their local app under https, and get letsencrypt certs for everyone.


Not needed for a local app, `file:///` can be used. No http requests at all involved for statics. For interaction with API CORS can be used.

**Comment by minrk** [comment]
Thanks @bollwyvl for the explanation of why we can’t and shouldn’t abandon node and npm at this point. Installing bundles via conda is an option for those who want to avoid node at runtime, and targeting ES6 modules is a separate and ongoing discussion, unrelated to node and npm. I think this can be closed.

**Comment by jasongrout** [comment]
Thank you @bollwyvl and @minrk for elaborating on this.
