### ISSUE TITLE
mainmenu-extension leaks memory

### ISSUE THREAD

**Issue by PEERCRED** [jupyterlab/jupyterlab#5664]
**Describe the bug**
mainmenu-extension causes memory leaks by holding references to disposed widgets

**To Reproduce**
1) Open a big pdf-file.
2) Close the tab with the pdf-file.

Now you may open Firefox Developer Memory tool, take a snapshot and see the JSString with base64-encoded content of the pdf-file being kept in memory.

[`tabmenu:activate-#####` suggests that `mainmenu-extension`  is to blame](https://github.com/jupyterlab/jupyterlab/blob/0befb137d6a111f8a792a5f5330069ff2a3daa23/packages/mainmenu-extension/src/index.ts#L641-L653).

**Possible fix**
Listen to the widget's being added [disposed](http://phosphorjs.github.io/phosphor/api/widgets/classes/widget.html#disposed) signal and dispose the command.

**Screenshots**
![image](https://user-images.githubusercontent.com/45268116/48966091-1ee4fd80-efdb-11e8-915c-ef37283efb4c.png)
![image](https://user-images.githubusercontent.com/45268116/48966087-0d9bf100-efdb-11e8-87e3-5bdfc8bff420.png)

**Comment by ian-r-rose** [comment]
Thanks for the report @PEERCRED, a fix for this is in #5686.
