### ISSUE TITLE
Jupyterlab showing empty input prompts for Markdown cells

### ISSUE THREAD

**Issue by fonnesbeck** [jupyterlab/jupyterlab#5669]
In Jupyterlab 0.35.3, I am seeing empty input prompts in front of every Markdown cell in notebooks:

![image](https://user-images.githubusercontent.com/81476/48972629-ddad1780-eff3-11e8-94b6-557becb5083c.png)

Running Jupyterlab installed from conda on Linux and Chrome 71.

**Comment by jasongrout** [comment]
We're having a difficult time reproducing this. Do these prompts happen all the time? If not, can you give some instructions for reproducing it?

**Comment by fonnesbeck** [comment]
They do not happen all the time, but they happen frequently. They *seem* to happen after kernel restarts, but I will try and come up with a reproducible example.

**Comment by gnestor** [comment]
@fonnesbeck Any news to help debug this?

**Comment by ian-r-rose** [comment]
I have figured out how to reproduce this: If you open a notebook with a cell that produces an error, then select the "Run All Cells" menu item, the markdown cells get empty brackets: `[]` . Now to dig into why...
