### ISSUE TITLE
Feature request: an option to change the font

### ISSUE THREAD

**Issue by rosgori** [jupyterlab/jupyterlab#5673]
**Describe the feature**

I know that you can change the font and its size if you go to `Settings -> Advanced Settings Editor ->  Notebook`. And there are three options:

 * Code Cell Configuration 
 * Markdown Cell Configuration 
 * Raw Cell Configuration

But please, look at this screenshot (it looks small, please open it up in another tab)

![different_fonts](https://user-images.githubusercontent.com/33338133/48987130-03b4e380-f0ea-11e8-980f-659912cc9344.png)

The font of the output cell is different from the input cell. For example, one of the cells has the code

`model_1.check_test_point()`

which shows a font (changed by me) and the output of that cell is

```
mu_interval__         -1.39
sigma_interval__      -1.39
y_bar              -1350.85
Name: Log-probability of test_point, dtype: float64
```

which has another font. Maybe you can't see it, but I can assure you that the fonts are different. 

The goal of this feature (if it is implemented) is... well, to have the option to change that font. 

**Desktop (please complete the following information):**

- OS: Ubuntu 16.04.5 LTS
- Browser: Firefox 63.0.3
- JupyterLab: 0.35.4

**Comment by jasongrout** [comment]
@ellisonbg - we are thinking this should be moved to Future. Thoughts?

**Comment by ellisonbg** [comment]
Yes, there are deeper changes we need to make to the font configuration that are going to be hard to avoid if we tackle this. Moving to Future.

**Comment by rosgori** [comment]
I have found a hack to change that font. You have to change a line in file. Where is that file? It depends on your operative system, in my case, it is in:

```bash
~/anaconda3/share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.css
```
If you want the dark theme, change `theme-light-extension` to `theme-dark-extension`. Look for

```
--jp-code-font-family-default:
```
and change it to your favorite monospace font. Keep in mind that this will change the monospace font you see in Jupyter Lab, let me show you:

With DejaVu Sans Mono

![dejavu-pantallazo](https://user-images.githubusercontent.com/33338133/80762174-9d639a00-8b01-11ea-812d-4e159dfd2816.png)

With Fira Mono

![fira-pantallazo](https://user-images.githubusercontent.com/33338133/80762273-d13ebf80-8b01-11ea-84a5-632ab66c52dc.png)

With Ubuntu Mono

![ubuntu-m-pantallazo](https://user-images.githubusercontent.com/33338133/80762331-f3384200-8b01-11ea-96ba-35b6631a9cd2.png)

To change the size, go to `Settings -> Advanced Settings Editor -> Theme`, go the right side and change this option:

```json
"overrides": {
        "code-font-size": "14px"
    },
```

Unfortunately, I don't know if I update Jupyter Lab, this change will still be there.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/can-jupyterlab-access-use-user-installed-fonts/1623/7

**Comment by mxalbert1996** [comment]
I wonder if there is any trouble to let the user override the `--jp-code-font-family-default` (or `--jp-code-font-family`) variable since #5123 seems to have only modified that variable.

**Comment by memeplex** [comment]
Can't simply `--jp-code-font-family` be added to Theme CSS Overrides?

**Comment by telamonian** [comment]
@memeplex done as part of #7130

**Comment by memeplex** [comment]
Thanks!
