### ISSUE TITLE
Edit Cell Metadata box does not scroll when there is lots of cell metadata present

### ISSUE THREAD

**Issue by alexweav** [jupyterlab/jupyterlab#5685]
**Describe the bug**
When there is lots of cell metadata present, the Edit Cell Metadata box and the Cell Inspector panel do not scroll. This makes it difficult to edit cells with large amounts of metadata, and the other widgets in the Cell Inspector panel start to behave strangely as a result.

**To Reproduce**

1. Open the Cell Inspector panel
2. Add many lines of cell metadata - enough to fill the entire left panel
3. Notice that a scroll bar does not appear on either the Edit Cell Metadata box, or the left panel itself
4. Keep adding more lines. Notice that the widgets above the Edit Cell Metadata box try to resize themselves to fit in the panel.

**Expected behavior**
When there is a large amount of text in the Edit Cell Metadata box, either the box itself or the Cell Inspector panel should allow scrolling.

**Screenshots**
(with dummy cell metadata - the same effect begins to occur after about 40 lines of JSON data.
![image](https://user-images.githubusercontent.com/8410871/49096336-ff92de00-f22f-11e8-8d89-c2c3480cf89f.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox 63.0.3, Chrome 70.0
- JupyterLab: 0.35.3

**Comment by blink1073** [comment]
The widget is defined here: https://github.com/jupyterlab/jupyterlab/blob/d500054caee775b377e0da897d129a3cb0d622d7/packages/notebook/src/celltools.ts#L402

The CSS would be changed here: https://github.com/jupyterlab/jupyterlab/blob/d500054caee775b377e0da897d129a3cb0d622d7/packages/notebook/style/index.css#L232

**Comment by alexweav** [comment]
I've PR'd a small CSS change which should fix this. Let me know if this was the correct direction to take.
