### ISSUE TITLE
Notebook and Image Widget Compiled Issues from SCIPY User Testing

### ISSUE THREAD

**Issue by matt-bowers** [jupyterlab/jupyterlab#569]
## Notebook and Image Widget Compiled Issues from User Testing

**Cal Poly Student Team: Callisto**, July 28, 2016
### Notebook
- Rearranging cells #641
  - Drag and drop feature would be the most useful for rearranging notebook
  - A couple users noted that the move cell "arrows" UI were gone, and that would be nice to have 
- Command mode vs. Edit mode unclear to users #709
  - Terminology should be clearly defined or not used at all
- Deleting cells NO ACTION
  - Users would "Cut" cells as opposed to deleting them
  - Add UI for actually _deleting_ cells ("Trash can" icon button, etc.)
- Notebook Renaming (already covered)
  - Users **always** tried to rename the notebook using the title in the plugin's window tab.
  - This functionality should absolutely be added
- Notebook Saving confirmation (already covered)
  - Users were very frequently unsure if notebook would save due to lack of confirmation
  - Notification should subtly alert user when a notebook has successfully saved
  - Notebooks with unsaved changes should be indicated at all times (italic title, asterisk after file name, etc.)
- Selecting multiple cells #710
  - Users were trying to use mouse ("Shift+Click Multiple") and/or looking for UI to do this (were unsure to solely use the keyboard)
  - We should add mouse functionality at the very least, if not having a toolbar function as well to "Select Multiple..."
- Look into Instructor/Student notebook view (on our roadmap, but probably for Jlab 2.0)
  - Requested by a user tester who used the Jupyter notebook for education
  - Allows instructor to hide cells/cell outputs containing "answers"
### Image Widget
- Zooming (already covered)
  - People expected zoom to work with "Shift +" and "Shift -"
  - People also expected to see zoom options in a context menu (including Reset Zoom)
  - A user tried zooming by pinching the trackpad (Apple OS gesture)
  - A user requested to have a "box zoom" functionality, allowing for a user to zoom into a section of the image drawn as a rectangle using the mouse by the user
- Image file icons
  - Images in the file browser should have an "image" icon, rather than a standard "file" icon
- Image fitting
  - Images should be centered in the viewer, and should scale to fit in the window (if not zoomed in or out)
- Image uploading
  - Drag and Drop
    - Add ability to drag and drop an image from your computer into the file browser
    - Functionality should apply to other files and folders as well (file browser issue)
  - Other methods
    - A user tried uploading an image in the "File" top level toolbar tab.

**Comment by ellisonbg** [comment]
Also closing this one...
