### ISSUE TITLE
Broken UI on Chrome on Windows 10

### ISSUE THREAD

**Issue by IvanMijailovic** [jupyterlab/jupyterlab#5691]
I have 2 monitors. 
One running with 100% scale in Windows 10 and another one running at 125% scale because of different resolutions and it is recommended by system.
On the 100% scaled monitor everything looks fine, but on the 125% scaled monitor I face the following UI issues:
![kernel](https://user-images.githubusercontent.com/6985965/49160430-081a1000-f327-11e8-88fc-06d258ffecf5.PNG)
![select](https://user-images.githubusercontent.com/6985965/49160486-241db180-f327-11e8-8e08-1f692bf9ba28.PNG)

Actually, changing scale value in Display Settings on Windows 10 from 100% to 125% causes the broken UI.

**Comment by jasongrout** [comment]
@vidartf, can you try reproducing this on Windows?

**Comment by vidartf** [comment]
At least it works on only one monitor with scaling. I'll give it a new go when I get back in the office next week with access to another monitor.

**Comment by vidartf** [comment]
I cannot reproduce this on my office setup (3 monitors: 2 @ 100%, one on 125%). Some questions to try to get a handle on this @IvanMijailovic:
- Which version of Chrome are you using? 
- Which version of jupyter lab?
- Does it matter if you switch which monitor is the main one?
- What happens for other scaling values?
- Do you have any lab extensions installed? If so, could you try running lab in core mode?

**Comment by IvanMijailovic** [comment]
Thanks Vidar,

1) Which version of Chrome are you using?
Version 70.0.3538.110 (Official Build) (64-bit)
2) Which version of jupyter lab?
0.35.0
3) Does it matter if you switch which monitor is the main one?
No
4)What happens for other scaling values?
Everything works properly
4)Do you have any lab extensions installed? If so, could you try running lab in core mode?
Ok, I try it and let you know

**Comment by vidartf** [comment]
> It seems that something is wrong with 'toolbarCellTypeDropdown' style in the case of 125% scale value.

Thanks for following up. I'm not sure if I fully follow how you came to the conclusion though. I see you underlined some parts in the screenshot, but I'm not immediately able to connect the dots here. Can you explain it in more details?

**Comment by vidartf** [comment]
@IvanMijailovic Do you have the following setting turned on or off? Is there any difference if you change it? https://support.microsoft.com/en-us/help/4091364/windows-10-fix-blurry-apps

**Comment by jasongrout** [comment]
It seems that the discussion has stalled. @IvanMijailovic, would you like to continue?

**Comment by IvanMijailovic** [comment]
Hi @jasongrout @vidartf Thanks very much for your effort. We can close this issue because there is workaround.

**Comment by jasongrout** [comment]
Thanks for following up here.
