### ISSUE TITLE
JupyterLab Compiled Issues from SCIPY User Testing

### ISSUE THREAD

**Issue by faricacarroll** [jupyterlab/jupyterlab#570]
**Cal Poly Student Team: IO,** July 28, 2016
### JupyterLab
- [x] Differentiate color scheme with Chrome
  - Users would confuse the chrome bar as an extension of the Jupyterlab menu bar
- [ ] Notebook toolbar items unclear
  - When users were asked to restart kernel in a notebook, they would hover over the icon and quickly move on because of the slow tool tip response time (increase tool tip response time) #688
  - Add a functionality to delete cells (users used 'cut' instead of actually deleting the cells). LEAVE AS IS.
- [ ] Saving notebook #689
  - No user feedback for saving so users weren't sure if their file was saved
  - Should have an indicator of when the file has been saved (similar to the original Notebook)
  - Users would attempt to save by right clicking on tab
- [ ] Renaming the notebook
  - Most users would try to rename their notebook by clicking the top file tab #690
  - Include rename in context menu of file browser #691
- [ ] Opening images #692
  - Improve discoverability of zoom in/zoom out by including a toolbar and context menu in imagewidget
- [ ] Making a new folder #693
  - Creating a folder should result in that folder being selected so the user knows to rename it (similar to Apple's UI of creating a new folder in finder)
- [ ] Switching kernels #694
  - Is this a necessary functionality? What is a use case of switching kernels versus creating a new console?
  - Switching kernels deletes all text in the console anyways
- [ ] More discoverable keyboard shortcuts #695
  - Dedicated help item to show [commands][keyboard shortcut] rather than just the command palette
  - Include simple animation to show keyboard shortcut key sequences
  - Visual representation of keys instead of textual representations to make shortcuts more obvious

@spoorthyv @charnpreetsingh185 @katiewhite360

**Comment by ellisonbg** [comment]
Closing, mostly historical now...but *great* work!
