### ISSUE TITLE
Explore translation of signals to async iterators 

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#5705]
We could write a transformation from Phosphor signals to async iterables. Why would we want to do this? We have some more built in support at the language level for these than phosphor signals (we can iterate through them with async of). Also, it might be faster if we don't transform them because browsers might be optimized for this pattern, see https://v8.dev/blog/fast-async

**Comment by jasongrout** [comment]
@saulshanabrook - any more thoughts on this, especially after exploring phosphor signals a lot more now?

**Comment by saulshanabrook** [comment]
@jasongrout I explored [this a bit in a PR](https://github.com/jupyterlab/jupyterlab/pull/5825/files#diff-080940eb263f4fdc9333124bd0077df3) and it does [*work*](https://github.com/jupyterlab/jupyterlab/pull/5825/files#diff-33311a6d475e9a26393a5633ce5e8c7b) but not sure well it plays with the GC issues that Chris raised for chaining signals. 


But I think moving to observables [makes more sense](https://github.com/jupyterlab/jupyterlab/pull/5825#issuecomment-458656618) now, instead of async interables.

The idea there would be to use signals only at the ends where we need to interface with phosphor and try moving all our logic to using observables instead, because they have a composition story.

Closing this issue since https://github.com/jupyterlab/jupyterlab/issues/5792 covers it I think.
