### ISSUE TITLE
Change "Settings | Use Dark Terminal Theme" menu item to use submenu

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5713]
For consistency, I think it makes sense to have the terminal theme menu item in the settings menu be a submenu, like the text editor theme and overall theme selections.

I can imagine some people seeing "Dark" one place in the settings menu, and selecting that to change the theme to dark and wondering why nothing goes dark.

**Comment by jasongrout** [comment]
I'll assign this to myself, but if anyone wants to work on this, please do (and post a comment noting you are working on it). Thanks!

**Comment by henryiii** [comment]
What about adding an "auto" choice, that would respect [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)? (this would need to be added to all three submenus).

**Comment by fcollonval** [comment]
@jasongrout I think this issue can be closed.

**Comment by ian-r-rose** [comment]
Thanks for the reminder @fcollonval
