### ISSUE TITLE
Make running extension support third-party sessions

### ISSUE THREAD

**Issue by PEERCRED** [jupyterlab/jupyterlab#5728]
[Running extension](https://github.com/jupyterlab/jupyterlab/tree/6004961882cff0fc2a3bc75361fceef645a3a4a1/packages/running) is showing running kernel and terminal sessions.
I'm developing an extension integrating... sort of remote desktop sessions into JupyterLab and would like to add them to the Running tab, but the list of session types is currently hardcoded in the running extension.

**Comment by jasongrout** [comment]
See also some of the work done in #4724, which starts to re-imagine the running panel and the information it shows.

**Comment by jasongrout** [comment]
Fixed in #6895
