### ISSUE TITLE
Notebook not backed by a file - Proliferation of Untitled*.ipynb files in notebook directories

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#573]
The proliferation of `Untitled**.ipynb` files in most of my working directories shows is one of the most annoying feature of the current notebook. IMO, it shows that the creation of a notebook file  for every session is not the best policy, at least in my workflow.

IMO, we should only start backing the model with a file after we have saved it the first time.

This would make the creation of a new notebook faster because there would not be a need to pick a name.

**Comment by blink1073** [comment]
This is related to https://github.com/jupyter/jupyterlab/issues/335 and would require changes to the server IIRC.

cc @minrk @Carreau @takluyver

**Comment by minrk** [comment]
It is somewhat related to #335, but I don't think any changes to the server are necessary. You should be able to create a notebook model and an unattached kernel (not via sessions API, but via kernels API). Upon first save, you can create a session and attach the kernel to that session, which I think was added in notebook 4.2 by @blink1073. All the changes needed that I can see would be in JupyterLab:

1. ensure NotebookModel works with only a kernel, and no session or filename.
2. allow creating and attaching session while a notebook is open, with an existing kernel.

What other changes are needed in the notebook server?

**Comment by blink1073** [comment]
My point is that while you may not want the file to show up in your local folder, you don't want to lose it if the browser crashes.

**Comment by minrk** [comment]
Roger, good point.

**Comment by Carreau** [comment]
I think we want to have a serverside memory store, that at least persist if the server does not crash but the browser does. I agree that that `Untilted` proliferation is annoying. [hence why I recommend `c.FileContentsManager.untitled_notebook='A Notebook has No Name -'`] , but not saving is worse as you literally lose work [which I just did].

So let's focus on feature parity, so that then we can gather our effort to **improve** the experience instead of providing user with 2 different almost identical but not quite environemements.

**Comment by ellisonbg** [comment]
I agree with @Carreau that while lots of Untitled notebooks are a pain, loosing work because somethings wasn't saved is worse. Plus @jakevdp is calling this the "Jupyter Power Score":

<img width="592" alt="screen shot 2016-08-16 at 9 05 05 pm" src="https://cloud.githubusercontent.com/assets/27600/17724226/2b9cdf6c-63f5-11e6-9469-aedaa8acde0a.png">

**Comment by SylvainCorlay** [comment]
> Plus @jakevdp is calling this the "Jupyter Power Score"

That is not a reason to keep it! :)

It is more of a symptom of the problem.

**Comment by takluyver** [comment]
Sounds like someone's power score is on the low side ;-)

Mine's only 7 on this laptop :scream:

**Comment by ellisonbg** [comment]
We could use browser local storage to store notebooks before a user saves it. But @jasongrout mentions that it can be unreliable. Also Safari's private mode will be broken.

**Comment by takluyver** [comment]
I think having notebooks saved in two different kinds of storage would make
things more confusing for users. And we'd have to deal with browser local
storage getting full (the limits aren't that big if we start sticking whole
notebooks in there, IIRC). Plus I think it is per-port, so you'd have a
different set of unsaved notebooks on a server running on port 8888, on
8889, on 8890...

If we want to store 'unsaved' notebooks somewhere, a hidden directory on
disk seems preferable, but it still seems more confusing for the user.

Can we adjust the UI to nudge the user towards:
- Naming notebooks when they're created (without penalising people who just
want to play around)
- Deleting 'scratchpad' notebooks when they finish with them.

**Comment by jakevdp** [comment]
Another option for making things more useful would be to save them as something like ``Untitled-<timestamp>.ipynb`` instead. At least then the default filename is marginally useful.

**Comment by AbdealiJK** [comment]
What about having a default temporary location ? Something like ~/.jupyter/tmp where the default time to keep the notebook is 30 days at maximum since the last changed date ?

Or even /tmp or ~/tmp ?

**Comment by SylvainCorlay** [comment]
- the `~/tmp` approach would work well with the proposed  `Untitled - <timestamp> .ipynb` and would prevent cwd directory to be polluted with files.
 - not backing it by a file on creation would still make sense in my opinion. It is the default behavior of most text editors.
