### ISSUE TITLE
Drop shadow missing on screenshots of documentation

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#5730]
Hi! Thanks for using JupyterLab.

If you are reporting an issue with JupyterLab, please use the [GitHub issue](https://github.com/jupyterlab/jupyterlab/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

The JupyterLab team and Project Jupyter value our community, and JupyterLab
follows the Jupyter [Community Guides](https://jupyter.readthedocs.io/en/latest/community/content-community.html).

**Describe the bug**

The JupyterLab documentation on read the docs has a number of screenshots. When we originally wrote and released this documentation a year ago those screenshots had drop shadows. Somehow those drop shadows have disappeared, making it difficult to see the edges of the screenshots. We looked at this issue in Hawaii, but had a tough time seeing where the logic was going wrong. The correct CSS classes are being applied to those elements, and the correct CSS rules are being loaded.

**Expected behavior**

All screenshots should have drop shadows.

**Screenshots**

No drop shadows are shown:

![screen shot 2018-12-05 at 4 28 49 pm](https://user-images.githubusercontent.com/27600/49553081-e2eb4b80-f8aa-11e8-899f-ce31ae0be826.png)

**Comment by quigleyj-mavenomics** [comment]
Here's the cause:

https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/_static/custom.css#L18

The `wy` rule has no declaration block, so it's being parsed as part of the `rst-content img.jp-screenshot` selector. Since `wy rst-content img.jp-screenshot` matches no elements, the rule isn't applied.

**Comment by ellisonbg** [comment]
Great find - don't know how that file got into that state...

Want to submit a PR to fix this? ;-)

**Comment by quigleyj-mavenomics** [comment]
Sure! I'll send in a PR on my personal account (@quigleyj97) once I get some time to sit down this weekend.

**Comment by ellisonbg** [comment]
Thanks!
