### ISSUE TITLE
When I move ipynb file to different folder, it cannot find a file to open in the same directory.

### ISSUE THREAD

**Issue by seriousmac** [jupyterlab/jupyterlab#5731]
**Describe the bug**
When I move ipynb file to different folder, it cannot find a file to open in the same directory.

**To Reproduce**
1. Make an folder named A and B
2. Add a data.json file in folder A and add a read_file.ipynb file in folder B. 
3. Then move the read_fild.ipynb to A.
(+ and actually I'v changed the folder name A to C)
(All move and rename process have been done in jupyter lab)

I tried to read data.json file in the read_file.ipynb (which is in the same folder now) by 
```python
file = open('ana_list.json', 'r')
```
But an error occurred as,
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-1afb46f188d9> in <module>
      5 when = []
      6 
----> 7 file = open('ana_list.json', 'r')
      8 temp_jsons = ujson.loads(file.read())
      9 for temp_json in temp_jsons:

FileNotFoundError: [Errno 2] No such file or directory: 'ana_list.json'
```
I've tried restart kernel several times and refresh the chrome tab. But, it doesn't change anything.
I think moving and changing name make some changes.
I have often experienced file path problems when I read a file.
In this case, the procedure is clear and I submit the issue.

**Expected behavior**
Can read a file by a simple path after I move or rename files.

**Desktop (please complete the following information):**
- OS: Ubuntu 16.04.5 LTS
- Browser: chrome 69.0.3497.100 (64-bit)
- JupyterLab: 0.32.1

**Comment by jasongrout** [comment]
Did you try shutting down the kernel, then opening the notebook again?

**Comment by jasongrout** [comment]
Closing since there was no response. Please feel free to comment below if you'd like to continue discussing.
