### ISSUE TITLE
Try postcss for extending CSS

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#5736]
Follow up from https://github.com/jupyterlab/jupyterlab/issues/5703

I will submit a PR that will allow us to extend our CSS with features like nesting and autoprefixing. This should allow us to clean up our CSS a lot and make our job of maintaining a bit easier.

**Comment by krassowski** [comment]
I think this can be closed because it is 2023 and [native CSS now supports nesting](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting) and web standards evolved in the way that autoprefixing is no longer needed most of the time. Please reopen if needed.
