### ISSUE TITLE
markdown cell has "[ ]" after execution halted

### ISSUE THREAD

**Issue by yoichi-kazama** [jupyterlab/jupyterlab#5743]
**Describe the bug**
Execution indicator "[ ]" appears to markdown cells if the execution has halted. 

**To Reproduce**
1. make a markdown cell, and then a code cell that fails
2. select the both cells and execute

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/44988698/49693319-352db480-fbaa-11e8-8d9e-675db5542062.png)

**Desktop (please complete the following information):**

- OS: Windows 8.1
- Browser firefox 63.0.3
- JupyterLab 0.35.3

**Additional context**

This did not happen before JupyterLab 0.35. Might be related to #5669.

**Comment by ian-r-rose** [comment]
Fixed by #6126, thanks for the report @yoichi-kazama!
