### ISSUE TITLE
[Feature request] drag-and-drop files to markdown cells for attachments

### ISSUE THREAD

**Issue by yoichi-kazama** [jupyterlab/jupyterlab#5744]
**Feature request**
Cell attachments are an important feature to create self-contained portable notebooks, but now we have to switch to Classic Notebook when creating attachments. It would be nice if we can:

1. Drop a file outside the wb browser onto a markdown cell for local file attachments (same as Classic Notebook),
2. Drop a file from the sidebar filebrowser to a markdown cell for remote file attachments.

**Comment by jasongrout** [comment]
Thanks. Both of those sound like excellent suggestions!

**Comment by vidartf** [comment]
Xref #4306 for a related discussion.

**Comment by agoose77** [comment]
I've created an extension to restore the original UI for attachments [here](https://github.com/agoose77/jupyterlab-attachments). I'm going to look into adding the clipboard paste feature too.

**Comment by Madhu94** [comment]
Hi, picking this up

**Comment by Madhu94** [comment]
@ian-r-rose  Ha ha :) I've opened a WIP PR here - https://github.com/jupyterlab/jupyterlab/pull/5913 
I'd like to know if people have any alternative implementations in mind. Please add your feedback too, @agoose77, if you see something off.

**Comment by Madhu94** [comment]
Although the [nbformat](https://nbformat.readthedocs.io/en/latest/format_description.html#cell-attachments) spec mentions attachments for both raw and markdown cells, both the notebook implementation (https://github.com/jupyter/notebook/pull/621/) and the work done by @vidartf in https://github.com/jupyterlab/jupyterlab/pull/4373, work only with markdown cells ?

**Comment by agoose77** [comment]
Have you tested this? I recall it working when I developed the attachments plugin, but I could be misremembering.

**Comment by Madhu94** [comment]
No I hadn't, my comment was just based on the code - only the markdown cell
seemed to be using the attachments resolver and all. I'll test it

**Comment by vidartf** [comment]
@Madhu94 The code in #4373 does add support for attachments on the model of raw cells. The core renderer for raw cells does not use theses attachments, but other extensions might want to use them. One example for a raw cell that might want an attachment is latex cells I think?

**Comment by vidartf** [comment]
@agoose77 Are you happy with the stability of the extension? I had a look at the code, and it looks good enough that I think way forward is to just do one review pass on it as a PR into core. I think it could best be added as another plugin to the `notebook-extension` package. The index file there desperately needs to be split into some sub-modules, but that is probably best done after such a PR. Thoughts?

**Comment by vidartf** [comment]
Or maybe the index.ts file could be put as "attachments.ts" in the `notebook-extension` package, and then simply imported into the index for re-export. That should be less work for you as well.

**Comment by vidartf** [comment]
@Madhu94 / @agoose77 I see that the format for the mime data on the paste event are different between the drag-and-drop PR (#5913) and the extension (https://github.com/agoose77/jupyterlab-attachments). Do you guys have any opinions about how to best reconcile these?

**Comment by Madhu94** [comment]
I believe they handle different cases - (correct me if I'm wrong @agoose77 ) - The PR in #5913 handles cases where you copy the image (as datauri), from a webpage or the imageviewer in your system, and paste it into your notebook. @agoose77's extension handles pasting from filebrowser, using a custom mime type for the clipboard, and the user doesn't have to open the image document to do this. It also seems to handle pasting into multiple selected cells, which the PR doesn't.

**Comment by agoose77** [comment]
@Madhu94 sorry for the delay, I've been afk for a bit. 

@vidartf RE
> Or maybe the index.ts file could be put as "attachments.ts" in the `notebook-extension` package, and then simply imported into the index for re-export. That should be less work for you as well.

I'm not a seasoned JS developer, so I shouldn't advise on the best case RE `notebook-extension`, but the suggestion to add to a new file seems reasonable over adding to the `index.ts` there. 


RE
> @Madhu94 / @agoose77 I see that the format for the mime data on the paste event are different between the drag-and-drop PR (#5913) and the extension (https://github.com/agoose77/jupyterlab-attachments). Do you guys have any opinions about how to best reconcile these?

At the moment, I don't see that they're different anywhere? I have defined a custom MIME type for the attachment data to be stored on a clipboard. This data itself contains MIME bundles for attachments with their own MIME types. At the moment, only images are supported from the file-browser by my extension, but it seems like other MIME types can be stored and resolved as attachments (incidentally, see https://github.com/jupyterlab/jupyterlab/blob/c3fff81d3f053c4f94e84263ae785eda56cb55aa/packages/attachments/src/model.ts#L393-L406 where we do have some built-in assumptions that attachments are images, but these could probably be easily refactored). 

This is an incomplete reply that I'll finish tomorrow morning! Great work all.

**Comment by agoose77** [comment]
@Madhu94 would you be happy to rename your MIME type to something like `"vnd.jupyter.files"` or something? I think my extension might need some changes to improve functionality, but it shouldn't stop this PR being approved.

**Comment by Madhu94** [comment]
@agoose77 I'm using a custom mime-type for dragging from filebrowser, so I can rename that. But as far as the paste functionality is concerned, I'm not using a custom mime-type - when you do Ctrl + V on an image or do right click + copy image url for an image, a mime-type of ``image/png`` (or whatever type the image is) gets copied on to the clipboard. Let me know if the last sentence was unclear? I believe this is the difference @vidartf means.

**Comment by vidartf** [comment]
Ah, sorry for the confusion. I see that the code in #5913 uses the `application/vnd.jupyter.attachments` mime-type for drag-and-drop, not copy-paste. Still, I have some concerns about the closures having the same mime-type as direct data would. Maybe a parameter string is the best way to modify the mime-type? E.g. `application/vnd.jupyter.attachments;closure=true` ?

**Comment by agoose77** [comment]
> Ah, sorry for the confusion. I see that the code in #5913 uses the `application/vnd.jupyter.attachments` mime-type for drag-and-drop, not copy-paste. Still, I have some concerns about the closures having the same mime-type as direct data would. Maybe a parameter string is the best way to modify the mime-type? E.g. `application/vnd.jupyter.attachments;closure=true` ?

Absolutely - this was why I suggested to @Madhu94 to use a different MIME type for the file browser, as I think our two use cases are different (mine denotes a collection of attachment MIME bundles whereas @Madhu94 stores closures-to-promises).  I don't think there's any benefit from trying to somehow coerce them into the same format (e.g. changing my extension to store functions). 

@Madhu94 based upon @vidartf's last reply, I think we're on the same page? Let me know if you want to clarify things further :) .

**Comment by Madhu94** [comment]
> Maybe a parameter string is the best way to modify the mime-type? E.g. application/vnd.jupyter.attachments;closure=true

@vidartf I was hoping that during review, a better way to store the drag data would be suggested :) 
But if we are leaving the closures there, I'm fine with changing the mime type name. 

@agoose77 Yes, we are :)

**Comment by vidartf** [comment]
@Madhu94 / @agoose77 :
In principle, for lab to be feature compatible with classic notebook, it would need some method for adding (ideally also removing) attachments. I think the PR of @Madhu94 (#5913) should cover most of these points. The code in the extension of @agoose77 (https://github.com/agoose77/jupyterlab-attachments) adds some nice additional features. Together, both of these resolve this issue. Currently, the hope is to get #5913 in before 1.0, but to wait with the code from the extension. I want to ensure that both of you are OK with this (and that I'm not missing anything important). I guess this question is mostly to @agoose77, as you said you wanted to keep the code of the extension separate from core for a little more.
