### ISSUE TITLE
Make markdown viewer user customizable

### ISSUE THREAD

**Issue by AlbertHilb** [jupyterlab/jupyterlab#5748]
I think it would be nice if users could customize, through jupyterlab settings system, how markdown is rendered by the viewer.
I mean properties like: font family, font size, line height, line length and so on.
I'd like to submit a PR implementing this, but at moment there is a big obstacle: `markdownviewer` is a mime renderer extension, so it can't access `SettingRegistry`.
Should `markdownviewer` be rewritten as a standard extension, then?

This is related to #4587.

Cheers

**Comment by AlbertHilb** [comment]
@meeseeksdev tag type:Enhancement

**Comment by AlbertHilb** [comment]
@meeseeksdev tag pkg:markdownviewer-extension

**Comment by jasongrout** [comment]
>  Should `markdownviewer` be rewritten as a standard extension, then?

If it needs access to the settings, then yes, it would need to be rewritten as a standard extension.

**Comment by AlbertHilb** [comment]
Fixed by #5901.
