### ISSUE TITLE
Failed to load module "canberra-gtk-module", but have the module installed already

### ISSUE THREAD

**Issue by Isabella-C** [jupyterlab/jupyterlab#5749]
System: Ubuntu 18.04

I got an error msg saying: Failed to load module "canberra-gtk-module"

Jupyter-related packages installed as listed below.

intel-openmp              2019.1                      144    anaconda
ipykernel                 5.1.0           py36h24bf2e0_1001    conda-forge
ipython                   7.2.0           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.13.1                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.4                   py36_0    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge

Also, I have already tried 'sudo apt install libcanberra-gtk0 libcanberra-gtk-module'. Did not work unfortunately.

Would you pls help? Thanks in advance!

**Comment by jasongrout** [comment]
This looks like it is totally unrelated to JupyterLab. Sorry we can't be of more help.

**Comment by jasongrout** [comment]
(It does look like there are lots of similar issues discussed on the web when searching for that library name: https://www.google.com/search?q=canberra-gtk-module&ie=utf-8&oe=utf-8&client=firefox-b-1-ab - perhaps one of those discussions might help?)
