### ISSUE TITLE
Excessive output truncated

### ISSUE THREAD

**Issue by cossio** [jupyterlab/jupyterlab#5762]
I have a long running computation that prints lots of diagnostic messages along the way. However after a while Jupyter gives up printing the messages:

![image](https://user-images.githubusercontent.com/10637482/49969169-e52a5700-fef5-11e8-98ca-885d96b68b9d.png)

Is there a way to change this setting? Either remove the limit completely, or increase it?

**Comment by jasongrout** [comment]
Great question. I would first look to see if there if output is being truncated by JLab or by the notebook server. If it is the notebook server, there are server options to up the limit.

**Comment by cossio** [comment]
@jasongrout Can you say what server options I can tweak? I can try changing those and see if that fixes the issue.

**Comment by jasongrout** [comment]
Sorry, I was on a phone earlier and didn't have access to the details. The notebook server iopub_data_rate_limit and iopub_msg_rate_limit options limit the amount of data going to the frontend (see https://jupyter-notebook.readthedocs.io/en/stable/config.html)

**Comment by jasongrout** [comment]
I also couldn't find that error message in the jlab codebase, so I think the error message (and truncation) are coming from the server, not jupyterlab.

**Comment by jasongrout** [comment]
> I can try changing those and see if that fixes the issue.

I put this issue as "needs info", waiting for your response.

**Comment by jasongrout** [comment]
Closing since the author did not follow up. Please comment here if you'd like to continue the discussion.
