### ISSUE TITLE
change font for output cells

### ISSUE THREAD

**Issue by vkkodali** [jupyterlab/jupyterlab#5764]
I am able to change the default font for code, markdown and raw cells by going to 'Settings' > 'Advanced Settings Editor'. But the font used for output cells is still Source Code Pro. Is there a way to change that as well?

**Comment by jasongrout** [comment]
Not at the moment. We're tracking this feature request at https://github.com/jupyterlab/jupyterlab/issues/5673. We're happy to help people get started on implementing this!
