### ISSUE TITLE
ReactElementWidget fails to unmount React element from the DOM

### ISSUE THREAD

**Issue by quigleyj-mavenomics** [jupyterlab/jupyterlab#5766]
**Describe the bug**

We have a few React elements wrapped up in `ReactElementWidget`, as does the JupyterLab code base. One of them is particularly heavyweight, which helped surface this issue. Because ReactElementWidget makes no call to [`ReactDOM.unmountComponentAtNode()`](https://reactjs.org/docs/react-dom.html#unmountcomponentatnode), the react elements rendered using this wrapper widget never get fully cleaned up.

**To Reproduce**

I have a minimal example of the issue here:

https://codesandbox.io/s/pw8qr9lv7j

(nb. React Dev Tools doesn't seem to like the iframe, if you open the output in a new window then you will be able to inspect the React DOM)

If you have React Dev Tools, you can see the `<div>`. When you click on the "Hi" text, it disposes itself and cleans the React node up. However, if you uncomment the line `unmountComponentAtNode(this.node);` (index.tsx:13), then when it gets disposed, the react element hangs around in memory.

**Expected behavior**

I'd expect it would be disposed as part of `#dispose()`, either in ReactElementWidget or the VDomRenderer. While it's possible for subclassers to do it, it opens up a leaky abstraction if multiple ReactDOM instances are loaded on the page (you need to get the ReactDOM instance that @jupyterlab/apputils is using).

**Comment by jasongrout** [comment]
This is one of the big points addressed by #5479.

**Comment by quigleyj-mavenomics** [comment]
Awesome, thanks for following up! Looks like that will get handled in `ReactWidget#onBeforeDetatch()`, which is probably a better place than `dispose`.
