### ISSUE TITLE
Can not print in the same line

### ISSUE THREAD

**Issue by stonepy** [jupyterlab/jupyterlab#5767]
When using parameter ' end="\r" ' in print function, it doesn't print in the same line, and all lines are empty

Here is an example code:
"""
import time
sec_count = 0
while sec_count < 3600:
    sec_count += 1
    time.sleep(1)
    print("Time Elapsed: %d s" % sec_count, end="\r")
"""

- OS: [e.g. MacOS X]
- Browser [e.g. chrome 71.0.3578.98]
- JupyterLab [e.g. 0.35.4]

**Comment by jasongrout** [comment]
This works now in 1.0alpha1, which was released. I think it was fixed in https://github.com/jupyterlab/jupyterlab/pull/5907
