### ISSUE TITLE
Code cell is minimally three rows high

### ISSUE THREAD

**Issue by ghuname** [jupyterlab/jupyterlab#5768]
Hi,

jupyter --version
4.4.0
Linux HP4730s 4.14.87-1-MANJARO #1 SMP PREEMPT Sat Dec 8 15:56:41 UTC 2018 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/15207713/50042589-723fee00-0065-11e9-972b-05c4aeb0c566.png)

Every code cell is three rows high. If I put more then three rows of code in the cell, it will enlarge, but when I delete all letters, cell is minimally three rows high.

On all other windows/linux installations, cell is always one row high.
What should I do in order to get one row cell hight?

Regards

**Comment by ghuname** [comment]
Is there anything I can do?

**Comment by ian-r-rose** [comment]
Hi @ghuname, what browser and zoom level are you using? I have seen this issue on large, zoomed out monitors using Firefox. I believe that it is a bug in CodeMirror (the text editor we use), but I don't really know what the fix would be, since the rendering process of CodeMirror is pretty complex (and a bit fragile).

**Comment by ghuname** [comment]
Browser is Firefox Quantum 64.0 (64-bit)
Zoom level is 90%
Resolution is 1600 x 900.

HTH

**Comment by ian-r-rose** [comment]
Do you still see the issue at 100% zoom?

**Comment by ghuname** [comment]
Yes, the issue is present at any zoom level.

**Comment by ghuname** [comment]
Actually, it is OK at zoom level 150%

**Comment by ghuname** [comment]
As the zoom is lower than 150%, cell box is bigger and bigger. At zoom level of 30%, I have 14 rows in one cell box.

**Comment by ghuname** [comment]
What could be the problem?

**Comment by ian-r-rose** [comment]
I'm unsure what can be done. Can you check Chrome? I see the same issue, but only at zoom levels < 100%. It still seems to be a CSS bug in CodeMirror.

**Comment by ghuname** [comment]
I am using firefox on several operating systems. Only on manjaro linux I have a problem.
So... as I understand, there is no solution for this issue, isn't it?

**Comment by vidartf** [comment]
Do you have any lab extensions enabled that might be adding some styiling?

**Comment by ghuname** [comment]
How to check that?

**Comment by vidartf** [comment]
`jupyter labextension list`

**Comment by jasongrout** [comment]
Or do you have any browser extensions installed that may be affecting things? Can you try with no browser extensions installed, and in incognito mode?

**Comment by ian-r-rose** [comment]
I also see this in firefox on linux. I think it's a problem with CodeMirror CSS.

**Comment by ian-r-rose** [comment]
I see the same problem in the classic notebook interface.

**Comment by jasongrout** [comment]
Thanks for redirecting us back to your unanswered question about @ghuname's zoom level.

**Comment by ghuname** [comment]
> `jupyter labextension list`

$ jupyter labextension list
JupyterLab v0.35.4
No installed extensions

**Comment by ghuname** [comment]
Can you please update.

**Comment by jasongrout** [comment]
Perhaps the next step is to see if it happens with the stock Codemirror at https://codemirror.net/demo/resize.html. Delete the text so you just have a single line high codemirror, and see if you can replicate the problem. If it happens there, someone will have to figure out what is going on and suggest a fix to codemirror. If it doesn't happen there, then perhaps it's something in how we are using codemirror, so someone would have to figure out why it's happening in jlab specifically and suggest a fix.

**Comment by ellisonbg** [comment]
+1 on checking the stock CM on their demo site.

**Comment by ian-r-rose** [comment]
I also see the same problem with the stock CM demo that @jasongrout linked.

**Comment by ghuname** [comment]
Do we have a workaround?

**Comment by jasongrout** [comment]
I think the workaround is to zoom to 100%. Given the above comments, it sounds like the next step is to file an issue with Codemirror (or search to see if they already have an issue filed) at https://github.com/codemirror/CodeMirror

**Comment by ghuname** [comment]
As I reported before:
> As the zoom is lower than 150%, cell box is bigger and bigger. At zoom level of 30%, I have 14 rows in one cell box.

So I can only have one row at zoom level of 150%, but then letters are to small.
Thanks for pointing me to CodeMirror.
