### ISSUE TITLE
Ready for newbies or start with plain Jupyter

### ISSUE THREAD

**Issue by dentarthur** [jupyterlab/jupyterlab#5773]
Blog says "ready for users". Does that really mean "ready for beta testers" (in which case I and other newbies should wait) or does it just mean "feature incomplete" but suitable for newbies doing simple stuff?

I have briefly used Jupyter a while back and Cocalc more recently. Am planning to start serious work, but am not a developer and will mainly be catching up with basic python skills.

Would love to start with JupyterLab as looks wonderful, but I would normally wait for at least version 1.2 (on theory that 1.0 was released before masses of newbies started using anything, 1.1 improved and broke things in 1.0 and 1.2 fixed the broken stuff so it is safe for newbies).

Nothing I do will be initially "production" so that doesn't really matter. Am asking about suitability for LEARNING.

If answer is "suitable for newbies", consider putting links from main jupyter pages mentioning where to start and where to go for newbie docs (including use of previous jupyter docs) and where to go for help and for contributing to newbie tutorial docs.

I am worried that absence of such links and info confirms it is currently suitable only for experienced users.

**Comment by aldanor** [comment]
Been using it myself for half a year now; switched most of my colleagues from the notebook to jlab in the meanwhile. We are doing "serious work" as you say; and yes, it is absolutely perfectly suitable for learning too.

**Comment by dentarthur** [comment]
Thanks!

That resolves the issue for me.

Leaving open for somebody in project to close after considering my query re
providing links from main Jupyter pages.

BTW I just confirmed that the HTML FAQ for "Is JupyterLab ready for use?"
here:

https://jupyterlab.readthedocs.io/en/stable/getting_started/faq.html

points to:

https://jupyterlab.readthedocs.io/en/stable/getting_started/overview.html#releases

"The current release of JupyterLab is suitable for general daily use"

Could not follow the link from my pdf version.

That is sufficient for existing users but rapidly increasing popularity of
Jupyter suggests there will be many other newbies arriving before 1.0 and
any replacement of original. So JupyterLab docs should explicitly mention
"and also suitable for learning by new users" and there should be a link
direct to this from main Jupyter page.

**Comment by jasongrout** [comment]
Thanks, and good points. I'll tag this issue for 1.0, which is the next planned release, so that we have it on our radar in the near future.

**Comment by ellisonbg** [comment]
I want to add my observations of using JupyterLab to teach "newbies" (undergraduates learning data science, or python, or both who have never used Jupyter). At this point lab provides a better experience for these users over classic. I can provide more details to justify this claim for folks if there is interest.

**Comment by dentarthur** [comment]
Thanks! Interested but am happy to accept conclusion whether or not you add
detail.

Details might be useful as draft for something to add to the main docs/web
site.
