### ISSUE TITLE
zooming/panning in  matplotlib unresponsive

### ISSUE THREAD

**Issue by mischki** [jupyterlab/jupyterlab#5777]
Hi, 
Managed to get matplotlib to work interactively with
**%matplotlib widget** 
to the point where it displays the plot, the zoom/pan buttons appear, even the slider widget works : the  plot responds to the slider as expected. However the zoom/pan/home buttons work. Clicking on Zoom or Pan displays the usual text on the bottom-right of the plot, like _"Zoom to rectangle"_ when the mouse hovers over the zoom button. But it doesn't actually zoom or pan. I also tried running it in Safari - same story. 

Any ideas?
Thanks in advance.

Some info:
       **@jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        jupyter-matplotlib v0.3.0  enabled  OK
        jupyterlab_bokeh v0.6.3  enabled  OK
        nbdime-jupyterlab v0.6.0  enabled  OK**
Mac OSX High Sierra, Chrome.

**Comment by jasongrout** [comment]
Good question. Do you mind posting the question to the [jupyter-matplotlib](https://github.com/matplotlib/jupyter-matplotlib) repo? I think that would be the best place to look for an issue, as it seems like it is an issue with that particular plugin.
