### ISSUE TITLE
Some problems when press Tab and Shift+Tab

### ISSUE THREAD

**Issue by zhangshd** [jupyterlab/jupyterlab#5780]
Dear developers,
 I have some problems after I update all packages using "conda update --all" command as the following screenshots:
![all-1](https://user-images.githubusercontent.com/23273686/50137316-cbae5400-02d5-11e9-8a0a-bb89a9970918.png)
![all-2](https://user-images.githubusercontent.com/23273686/50137331-d49f2580-02d5-11e9-992b-67fa772ee29a.png)
It becomes less convenient when press 'Tab' or 'Shift' + 'Tab' after my updating. How can I recover the display condition to the condition before my updating?

**Comment by jasongrout** [comment]
Thanks for the very detailed images. It looks like the problems here are in ipython or ipykernel, not JupyterLab (ipykernel provides the actual completions that are displayed). See https://github.com/ipython/ipykernel/issues/299 and https://github.com/jupyter/notebook/issues/3164 for relevant discussion.
