### ISSUE TITLE
Terminal cursor blinks erratically in Safari

### ISSUE THREAD

**Issue by sballin** [jupyterlab/jupyterlab#5782]
**Describe the bug**
Terminal cursor blinks erratically after some normal usage in Safari.

**To Reproduce**

1. Open a Terminal in JupyterLab in Safari
2. Type some things, switch jupyterlab/browser tabs
3. Observe cursor blinking faster and faster

**Expected behavior**
Cursor should be blinking at a constant rate (or not blinking at all, would be nice if this was a config option). Works fine in Chrome and Firefox.

**Screenshots**
![cursor blink](https://user-images.githubusercontent.com/2719004/50186003-74b17a80-02e7-11e9-82fa-f3a92b0b5636.gif)

**Desktop:**

- OS: MacOS 10.14.1
- Browser: Safari 12.0.1
- JupyterLab 0.35.4

**Comment by jasongrout** [comment]
Can you test on JupyerLab 0.35.x?

**Comment by sballin** [comment]
I just confirmed that it happens in 0.35.4 as well, and with the server running on the same machine from which I'm accessing the web interface.

**Comment by sballin** [comment]
Looks like this is fixed in Safari 12.1, even with jupyterlab 0.35.4. I'm unable to go back to a previous version of Safari to test whether the xterm.js changes fixed it.

**Comment by themmes** [comment]
I am having this same issue

[guest]
jupyter lab 1.0.4
Python 3.6.7
running on Linux Xenial 16.04

[host]
Safari 12.1.2
running on MacOS Mojave 10.14.6

I tried to pass the xtermjs setting `cursorBlink: false` in the terminal-extension settings, however this is not a recognised property.

**Comment by jasongrout** [comment]
Just checked in safari 14.0.3 with JLab 3, and this seems to have been fixed now. Please comment if you are still seeing this issue.
