### ISSUE TITLE
Incorrectly automatching single quotation in Julia cells

### ISSUE THREAD

**Issue by ryan4yin** [jupyterlab/jupyterlab#5796]
When type a single quotation mark after square brackets, it should not automatically add another one.

![quote issue](https://user-images.githubusercontent.com/22363274/50371383-c82c0d00-05f4-11e9-856b-a414d7efbb72.gif)

and single quotation after a variable seems fine.
![right one](https://user-images.githubusercontent.com/22363274/50371469-55bc2c80-05f6-11e9-973d-fa3abf68d0eb.gif)

**Desktop:**

- OS: [Manjaro 18.0]
- Browser [Chrome 71.0.3578.98]
- JupyterLab [0.35.4]
- IJulia [v1.14.1]
- Julia [v1.0.2]

**Comment by ian-r-rose** [comment]
Thanks for the report @ryan4yin. Does this also happen in the classic notebook interface? If so, it is likely a bug in the Julia mode for CodeMirror (the editor we use).

A very similar issue came up recently with scala, and it was fixed upstream: https://github.com/jupyterlab/jupyterlab/issues/4544
I wonder if the same fix could be applied here.

**Comment by ryan4yin** [comment]
@ian-r-rose yes, it happen in the classic notebook too.

**Comment by jasongrout** [comment]
It looks like it may be as easy as the recent Scala change we submitted to CodeMirror: https://github.com/codemirror/CodeMirror/pull/5568

Can you open an issue in the CodeMirror repo, or even better, do you want to try opening a PR to CodeMirror?

**Comment by jasongrout** [comment]
Actually, it looks like it may be more complicated. In Scala, single quotes should never be paired. In Julia, single quotes delimit characters, so *sometimes* they should be paired. If things work fine for `x'`, but not for `[1,2]'`, my guess is that the actual mode parsing in CodeMirror may need to be modified to be more intelligent about single quotes. Here's the Julia mode for CodeMirror: https://github.com/codemirror/CodeMirror/blob/master/mode/julia/julia.js

Regardless, my guess is that this is an upstream issue, not an issue in JLab.

**Comment by ryan4yin** [comment]
@jasongrout I don't think I have the ability to solve this, so I open a issue in CodeMirror.
