### ISSUE TITLE
Auto-indentation problems in Julia cells

### ISSUE THREAD

**Issue by ryan4yin** [jupyterlab/jupyterlab#5797]
Incorrectly indentation in julia cells(gif recorder worked not well...):

![indentation-issue](https://user-images.githubusercontent.com/22363274/50371637-e9432c80-05f9-11e9-9acb-af8cde2b89b3.gif)

and seems fine for python3:

![indentation-right](https://user-images.githubusercontent.com/22363274/50371620-64581300-05f9-11e9-801c-bf79855f9c3b.gif)
**Desktop:**

- OS: [Manjaro 18.0]
- Browser [Chrome 71.0.3578.98]
- JupyterLab [0.35.4]
- IJulia [v1.14.1]
- Julia [v1.0.2]

**Comment by ian-r-rose** [comment]
Thanks for the report @ryan4yin, I also see weird indentation in the Julia mode. Seems like it is likely a bug in CodeMirror. Some relevant crossrefs:

https://github.com/codemirror/CodeMirror/issues/5702
https://github.com/codemirror/CodeMirror/issues/4266
https://github.com/JuliaLang/IJulia.jl/issues/119

I don't know where how to apply a fix at the moment, but perhaps somebody with codemirror mode skills can take a look.

**Comment by ryan4yin** [comment]
the issue seems has been solved at https://github.com/codemirror/CodeMirror/pull/5762, and contains in the latest version of codemirror.

**Comment by ed1d1a8d** [comment]
I tried updating to the latest jupyterlab via pip but this does not appear to be solved for me.

**Comment by fabriziopittorino** [comment]
> I tried updating to the latest jupyterlab via pip but this does not appear to be solved for me.

same here

**Comment by jasongrout** [comment]
Looks like the version of codemirror needs to be bumped. We have 5.42, and the fix is in 5.44.

**Comment by jasongrout** [comment]
> Looks like the version of codemirror needs to be bumped. We have 5.42, and the fix is in 5.44.

This is now #6313
