### ISSUE TITLE
jlpm run remove:package deletes your source code!

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/jupyterlab#5803]
While debugging #5802, I wanted to run a dev install of JupyterLab with a dev install of my extension. I followed the steps outlined in https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#extension-authoring.

Specifically, I ran:

`jlpm run add:sibling ../jupyterlab-nbmetadata/`

From the root of my jupyterlab master checkout. However, I couldn't find a command combination that'll load both my jupyterlab master and my local extension's master. `jupyter lab --dev --watch` ran just the jupyterlab master but not my extension's, and `jupyter lab --watch` ran my extension's but not master.

I decided to try the 'turn it off and on again' strategy, and ran

`jlpm run remove:package /home/yuvipanda/code/jupyterlab-nbmetadata/`

This actually *deleted* my source directory completely without warning! The documentation specifically says it won't do this. I lost all my source code since last git push, since this took the .git directory with it too.

**Comment by yuvipanda** [comment]
@afshin pointed out https://github.com/jupyterlab/jupyterlab/blob/8a141cadf904150b01886f189a10a3143676a1eb/buildutils/src/remove-package.ts#L36 which *does* seem to delete the files.

**Comment by ian-r-rose** [comment]
Thanks for catching this @yuvipanda, and sorry for the close call with your code :grimacing: 

The intention for `remove:package` was to remove packages from the JupyterLab source tree in the `packages` directory. We should probably check that the packagePath given to `remove:package` is actually in the place we expect, and error out if that is not the case.

The documentation is out-of-date (it used to be `remove:sibling`, and did not actually remove files so much as not-include them in the build).

I propose we do the following:
1. Fix the documentation to say that it actually *does* delete the package files [here](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/extension_dev.rst#extension-authoring)
2. Don't allow absolute paths for packages. This would mean removing this line: https://github.com/jupyterlab/jupyterlab/blob/8a141cadf904150b01886f189a10a3143676a1eb/buildutils/src/remove-package.ts#L32 and instead erroring out if the package does not exist.

Does that seem reasonable to you @yuvipanda?

**Comment by ian-r-rose** [comment]
Marking as a good first issue.

**Comment by yuvipanda** [comment]
@ian-r-rose yeah, sounds good to me. I'd say (1) is probably higher priority than (2), since other people might also lose their code :)

**Comment by jeanruggiero** [comment]
I'm going to give this a shot at the Pycon 2019 mentored sprints.

**Comment by ian-r-rose** [comment]
Fixed by #6307. Thanks @jeanruggiero!
