### ISSUE TITLE
figure plots

### ISSUE THREAD

**Issue by GiwaAO** [jupyterlab/jupyterlab#5805]
I am trying to make figure plots on Jupyterlab but i am not seeing any figure plots even after calling plt.show().

**Comment by jasongrout** [comment]
Can you post a code sample?

**Comment by timhoffm** [comment]
When talking about figure, I assume this is referring to matplotlib.

You must use `%matplotlib inline` or  `%matplotlib notebook` to direct the plot output to the notebook.
