### ISSUE TITLE
Code completion not working on module attributes

### ISSUE THREAD

**Issue by Panurus** [jupyterlab/jupyterlab#5808]
Hi!

**Describe the bug**
Tab code completion not working for module attributes, but works on base functions

**To Reproduce**

1. Fire up bash in windows 10 (after enabling Windows Subsystem for Linux)
2. Execute "jupyter lab"
3. Navigate to resultant URL in Chrome
4. Start a notebook with Python 3.6.
5. Cell 1: "import pandas as pd". Run cell.
6. Cell 2: Type "pr", hit tab. Autocomplete menu appear.
7. Backspace twice to delete "pr".
8. Type "pd.", hit tab. No autocomplete menu appears.

**Expected behavior**
Autocomplete menu appearance at step 8.

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.1 LTS (Bionic Beaver) on Windows 10 Home (10.0.17134 Build 17134) Windows Subsystem for Linux
- Browser: Chrome 71.0.3578.98 (Official Build) (64-bit)
- JupyterLab: 0.35.3

**Comment by Panurus** [comment]
Appears to be working now after fresh install...

**Comment by ian-r-rose** [comment]
Glad to hear it, thanks for following up @Panurus.

**Comment by drorata** [comment]
I think I have the same problem on a newly (conda) installed environment. Am I expecting something wrong?

**Comment by jasongrout** [comment]
I'm not sure. This isn't really a JupyterLab issue, but an issue to take up with the completion engine in ipython. JLab is just displaying the completions IPython is giving it to display.

**Comment by jasongrout** [comment]
So an appropriate place to open an issue is https://github.com/ipython/ipython/, or you could ask the question on the Jupyter discourse or mailing list: https://jupyter.org/community

**Comment by drorata** [comment]
Thanks! https://github.com/ipython/ipython/issues/11530 might be related
