### ISSUE TITLE
autosave directory

### ISSUE THREAD

**Issue by SleepSux** [jupyterlab/jupyterlab#5809]
This has been quite a pain because I have ".ipynb_checkpoints" in every single directory of my project.
I have not been able to find a way to simply change or give it one directory to always save in. 

This is causing issues when I'm dynamically loading files and that folder gets pulled in because its sitting just about everywhere.

Please add this next to the autosave interval or someone help me gain my sanity back by quickly showing me where I can code in this setting.

EDIT: 
The current working directory for autosave changes to where ever the user last clicks a directory. Could there be an override setting for this to have custom or at least a permanent directory?

Thanks!

**Comment by ian-r-rose** [comment]
Hi @SleepSux, sorry for the slow reply. You should be able to customize the checkpoints directory by setting the `FileCheckpoints.checkpoints_dir` configurable in your [`jupyter_notebook_config.py`](https://jupyter-notebook.readthedocs.io/en/stable/config_overview.html#configure-nbserver), or when you launch JupyterLab with
```bash
jupyter lab --FileCheckpoints.checkpoint_dir=mydirectory
```

Closing as answered, but feel free to comment here if you have further questions!

**Comment by SleepSux** [comment]
So i tried this and I receive a "NameError: name 'FileCheckpoints' is not defined" when jupyter notebook loads.

here is the full error.

[E 11:42:51.575 NotebookApp] Exception while loading config file /home/computer/.jupyter/jupyter_notebook_config.py
    Traceback (most recent call last):
      File "/home/computer/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/computer/anaconda3/lib/python3.7/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/computer/anaconda3/lib/python3.7/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/computer/anaconda3/lib/python3.7/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/home/computer/.jupyter/jupyter_notebook_config.py", line 752, in <module>
        FileCheckpoints.checkpoints_dir = '/home/computer/Documents/myProjects/notebookCheckpoints'

**Comment by ian-r-rose** [comment]
@SleepSux If you are adding it in your `jupyter_notebook_config.py`, you will need to dot into the config object, so I think you will want something like
`c.FileCheckpoints.checkpoint_dir='/home/computer/Documents/myProjects/notebookCheckpoints'`

**Comment by gsemet** [comment]
Indeed, these files are annoying and freezing the checkpoints_dir is not a satisfying solution, since it only use the filename and not the path. So if you have 2 opened "mynotebook.ipynb" file from 2 different folders they will both write in the same file.
Why not hardcoding the path in base64 (or any other hash) and use it to avoid file collision? Why not reconstructing the same path inside checkpoint_dir?

**Comment by jasongrout** [comment]
This is an issue with the Jupyter notebook server, not with JupyterLab (the code in question lives in https://github.com/jupyter/notebook/, not here). I think the best way forward is opening an issue in the notebook repo and carrying on the conversation there, if you would like to pursue this.

**Comment by gsemet** [comment]
Opened in https://github.com/jupyter/notebook/issues/4645 :)

**Comment by jasongrout** [comment]
Thanks!
