### ISSUE TITLE
Notebook selector to disable many command-mode keyboard shortcuts

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5816]
There may be many situations where some interactive output in the notebook wants to disable most notebook keyboard shortcuts. It would be great if there was an attribute you could add to a notebook output that would disable most notebook command-mode keyboard shortcuts. We could probably accomplish this by adding a `:not(data-no-notebook-shortcuts)` or something like that to the notebook keyboard shortcut selectors.

CC @mwcraig

**Comment by jasongrout** [comment]
Adding as a good first issue. It does require a bit of knowledge about CSS, but hopefully it's as easy as adding an appropriate `:not` selector to the keyboard shortcuts at https://github.com/jupyterlab/jupyterlab/blob/4797856baf212dd3c62d325a7f6958de0bb4cdff/packages/notebook-extension/schema/tracker.json

**Comment by jasongrout** [comment]
> Should be easier now that I know how to check for matches in the console 😀

A handy skill to have!

I was thinking that the shortcut-disabling class should be on specific elements, not on the notebook as a whole. Then the selector looks something like `.jp-Notebook:focus :not(.data-no-notebook-shortcuts)` (note the space, indicating a descendant to which the `:not` selector applies). It does mean that your node will need focus (so that keyboard events have the node or a descendant as a target), but I think that's good - you only get to override keyboard shortcuts when your thing has focus.

After you get it working with normal CSS classes, I'd probably switch to using an actual data attribute, which maybe is geared more to representing semantic data, similar to https://github.com/jupyterlab/jupyterlab/blob/30443877391208c749a92c86b2c59b41256addcd/packages/console-extension/schema/tracker.json#L8. You can set a data attribute by getting the DOM node and setting `node.dataset.myAttr = true` or something like that: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes.

**Comment by mwcraig** [comment]
After playing with this some more I don't think any change is needed in lab. If my node has focus then the default shortcut selectors don't match. The problem with `.jp-Notebook:focus :not(.data-no-notebook-shortcuts)` is that it doesn't match the case when the `.jp-Notebook` node has the focus.

I just tested it in ipyevents (after fooling for a while in debugger tools) and setting the focus to node I want (after adding a `tabindex` to it  to make it focusable) works, with the upside that there is now a visual cue that the widget has grabbed focus.

Still working on making the focus go back to where it was before I grabbed it :) since I'm grabbing the focus on mouseenter and releasing it on mouseleave.

In any event, would a PR to the extension author documentation discussing how to suppress shortcuts be useful?

**Comment by jasongrout** [comment]
> After playing with this some more I don't think any change is needed in lab. If my node has focus then the default shortcut selectors don't match. The problem with `.jp-Notebook:focus :not(.data-no-notebook-shortcuts)` is that it doesn't match the case when the `.jp-Notebook` node has the focus.

IIRC, the keyboard shortcuts match by starting at the target, then going up the DOM hierarchy. First match wins. So while you're right that you can *override* keyboard shortcuts with focusing an element, you won't be turning off shortcuts you aren't overriding. However, you're also right that that selector isn't matching and won't work as-is (duh! I should have realized that!). Problem here is that CSS selectors don't currently let you pick a parent element (CSS4 has a [:has](https://drafts.csswg.org/selectors-4/#relational) selector letting you do this, but [no browsers](https://caniuse.com/#feat=css-has) currently support it). So I think you're right that this would have to be a notebook-wide thing to add a class or attribute to the `.jp-Notebook` element.

As for the focusing thing, I believe the `relatedTarget` in the focus event shows what you are focusing from, if it makes sense (https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/relatedTarget)

**Comment by jasongrout** [comment]
Ah, right! Duh again! I don't know where I put my brain this morning.

So great! This means this is sort of a non-issue then, as you point out.

**Comment by jasongrout** [comment]
Given that, I'll close this issue as a non-issue. As to the mouseenter event, look at the `relatedTarget` (https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter). And be careful about choosing between mouseenter and mouseover...
