### ISSUE TITLE
Run Jupyter lab terminal as administrator

### ISSUE THREAD

**Issue by zash121** [jupyterlab/jupyterlab#5818]
Not able to create a virtual environment through jupyter lab inbuilt terminal, always shows error 'Run as administrator'.

**Comment by ian-r-rose** [comment]
What OS/browser are you using? The JupyterLab terminal should use the same shell as the underlying system.

**Comment by vidartf** [comment]
Can you create a virtual env in the system shell without administrator privileges?

**Comment by vidartf** [comment]
I do not think Windows terminals support an equivalent of `su`/`sudo`, so for jupyterlab to expose an administrator terminal, the server process would need to be run with admin privileges, which seems like a big security issue(!).

I would instead suggest that you reconfigure your virtual env manager to allow non-administrators to create a new environment.
