### ISSUE TITLE
Split up testutils package

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5821]
Right now, the base services test package relies on testutils: https://github.com/jupyterlab/jupyterlab/blob/30443877391208c749a92c86b2c59b41256addcd/tests/test-services/package.json#L17 for the purpose of pulling in a few jest config things, it seems.

However, testutils pulls in things like the notebook package, etc., which are definitely not required for services to function. It would be great if we could separate out the base layer of test utilities/jest utilities we need (that don't depend on other jlab packages), and just require those in the services package, and then have a higher-level test utils package for things like notebook utilities, etc.

**Comment by jasongrout** [comment]
One side effect of this coupling is that I can't just make changes in the services package and test them, without also taking care of all of the ramifications of the changes in the notebook codebase. It would be nice if I could work on the services codebase and nail down changes before moving up the stack to the notebook.

**Comment by ian-r-rose** [comment]
I agree with this @jasongrout. Incidentally, I've also been thinking of starting separate issue entitled "dependencies I'm not happy about".
