### ISSUE TITLE
Memory leak suspected when using bokeh plots on Mac

### ISSUE THREAD

**Issue by dbk123** [jupyterlab/jupyterlab#5823]
I've got some code that runs fine in Jupyter Notebook, but when running on a Mac in Jupyter Lab the memory associated with the localhost process continually (and fairly rapidly) grows until the notebook becomes unresponsive and crashes.  The code is creating a row of three very simple bokeh plots as shown below.  The code seems to run OK on my Windows machine at my office, but I have not yet profiled memory usage.  The problem occurs using both Safari and Chrome browsers on the Mac.  This could be a bokeh problem, but I suspect Jupyter Lab as it runs OK on Jupyter Notebook.  Happy to provide more info if needed.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/16540538/50568836-f2cd4280-0d25-11e9-8b8f-2ed043d2ddb3.png">

**Comment by dbk123** [comment]
I should have mentioned I am using version 0.35.3 of Jupyter Lab and 1.0.2 of Bokeh

**Comment by afshin** [comment]
@dbk123 Thanks for posting this issue.

It seems likely that the issue comes from the [Bokeh JupyterLab extension](https://github.com/bokeh/jupyterlab_bokeh/issues), would you mind cross-posting this issue so the Bokeh folks can take a look?

**Comment by dbk123** [comment]
Thanks.  I am in touch with them.

**Comment by timhoffm** [comment]
bokeh/bokeh#8532 has been closed. So this might be closed as well.

**Comment by jasongrout** [comment]
Thanks for following up here.
