### ISSUE TITLE
Code markdown has a different styling in lists

### ISSUE THREAD

**Issue by apcamargo** [jupyterlab/jupyterlab#5826]
When inside a list the code markdown doesn't have the grey background.

![screenshot from 2019-01-02 14 30 13](https://user-images.githubusercontent.com/22940964/50601439-49a85880-0e9b-11e9-97e2-8d926fbb5613.png)

**Comment by jasongrout** [comment]
Thanks! This is now fixed in master:

<img width="165" alt="screen shot 2019-01-02 at 9 13 38 am" src="https://user-images.githubusercontent.com/192614/50603251-b9541e80-0e6e-11e9-9223-beceb8c826bc.png">

**Comment by jasongrout** [comment]
(Previously reported at https://github.com/jupyterlab/jupyterlab/issues/5616, and fixed in #5628)
