### ISSUE TITLE
Terminal font size help

### ISSUE THREAD

**Issue by betteridiot** [jupyterlab/jupyterlab#5827]
I know that I can use the command palette to increase the terminal font size. However, this is coded to be an "increment by one" process [here](https://github.com/jupyterlab/jupyterlab/blob/cbe124d18c4d016cc630abc88e0b109e8a9b1fca/packages/terminal-extension/src/index.ts#L271-L281).

The problem with this is that there is no keyboard shortcut (since Ctrl + is used by the browser). I know the command name ("terminal:increase-font") but I don't know how to create a working shortcut that would quickly increase the font size.

As an alternative, I would love if I could just overwrite the increment function within the @juptyerlab/terminal-extension node_module (.../share/jupyter/lab/staging/node_modules/@jupyterlab/terminal-extension/lib/index.js), but the change does not seem to carry over. 

Any help would be appreciated.

**Comment by betteridiot** [comment]
Thank you. I had the first part of the increase font shortcut correct but I had no idea about the selector

**Comment by jasongrout** [comment]
Documenting those is #5600.
