### ISSUE TITLE
I just installed Anaconda and Jupyter Notebook doesn't start. help me

### ISSUE THREAD

**Issue by justin1610** [jupyterlab/jupyterlab#5832]
When I start Jupyter Notebook by clicking the icon or typing code in Anaconda Prompty
Here's the thing showed

[I 17:17:26.844 NotebookApp] JupyterLab extension loaded from C:\Anaconda3\lib\s
ite-packages\jupyterlab
[I 17:17:26.845 NotebookApp] JupyterLab application directory is C:\Anaconda3\sh
are\jupyter\lab
[I 17:17:26.848 NotebookApp] Serving notebooks from local directory: C:\Users\*
[I 17:17:26.849 NotebookApp] The Jupyter Notebook is running at:
[I 17:17:26.850 NotebookApp] http://localhost:8888/?token=57e6a6d47a0e751ba15f73
1173cbdb0399d7074813b045ae
[I 17:17:26.850 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[C 17:17:27.037 NotebookApp]

    To access the notebook, open this file in a browser:
        **
    Or copy and paste one of these URLs:
        ***

I hid some personal info . When I type *** and open in Chrome I can open Jupiter but i want it to immediately start.

**Comment by jasongrout** [comment]
What code exactly are you typing in? The browser should pop up automatically unless you are giving the `--no-browser` option.

Also, can you try doing this from the Anaconda prompt: `python -m webbrowser -n "http://www.python.org"` in order to test that launching a web browser works with python?

And finally, can you tell us what the webbrowser module thinks it should launch? `python -c "import webbrowser;print(webbrowser.get())"`

**Comment by jasongrout** [comment]
Do you have the `BROWSER` environment variable defined? That takes precedence over the default browser launching.

**Comment by justin1610** [comment]
Thank you for reply
1. I typed      jupyter notebook      in anaconda prompt and the browser doesn't pop up.
2. i typed     ' python -m webbrowser -n "http://www.python.org ' and the browser pops up so i think it works.
3. i can't understand what 'webbrowser module' is
and when i typed                python -m webbrowser -n "http://www.python.org"        it showed
<webbrowser.WindowsDefault object at 0x000000602A0964A8>
4. i can't understand what brower environment variable is, and how to define it. i'm new to assembly language so i don't have much knowledge..

**Comment by jasongrout** [comment]
This may have to do with recent notebook server changes (not JupyterLab). Can you try doing `python -m webbrowser -n **`, where `**` is the html file noted after `To access the notebook, open this file in a browser:` in your original post?

**Comment by ClimenteA** [comment]
I have the same issue, tried reinstalling it but didn't worked (Anaconda3 64bit).

The `jupyter_notebook_config.json` file is empty (has just {} ).

```
C:\Users\aclimente>jupyter-notebook --debug --no-browser
[D 11:27:04.216 NotebookApp] Searching ['C:\\Users\\aclimente', 'C:\\Users\\aclimente\\.jupyter', 'c:\\users\\aclimente\\appdata\\local\\continuum\\anaconda3\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 11:27:04.216 NotebookApp] Looking for jupyter_config in C:\ProgramData\jupyter
[D 11:27:04.216 NotebookApp] Looking for jupyter_config in c:\users\aclimente\appdata\local\continuum\anaconda3\etc\jupyter
[D 11:27:04.216 NotebookApp] Looking for jupyter_config in C:\Users\aclimente\.jupyter
[D 11:27:04.216 NotebookApp] Looking for jupyter_config in C:\Users\aclimente
[D 11:27:04.216 NotebookApp] Looking for jupyter_notebook_config in C:\ProgramData\jupyter
[D 11:27:04.216 NotebookApp] Looking for jupyter_notebook_config in c:\users\aclimente\appdata\local\continuum\anaconda3\etc\jupyter
[D 11:27:04.216 NotebookApp] Loaded config file: c:\users\aclimente\appdata\local\continuum\anaconda3\etc\jupyter\jupyter_notebook_config.json
[D 11:27:04.216 NotebookApp] Looking for jupyter_notebook_config in C:\Users\aclimente\.jupyter
[D 11:27:04.216 NotebookApp] Loaded config file: C:\Users\aclimente\.jupyter\jupyter_notebook_config.py
[D 11:27:04.216 NotebookApp] Looking for jupyter_notebook_config in C:\Users\aclimente
[D 11:27:04.216 NotebookApp] Ignoring min_open_files_limit because the limit cannot be adjusted (for example, on Windows)
[D 11:27:04.216 NotebookApp] Paths used for configuration of jupyter_notebook_config:
        C:\ProgramData\jupyter\jupyter_notebook_config.json
[D 11:27:04.216 NotebookApp] Paths used for configuration of jupyter_notebook_config:
        c:\users\aclimente\appdata\local\continuum\anaconda3\etc\jupyter\jupyter_notebook_config.d\jupyterlab.json
        c:\users\aclimente\appdata\local\continuum\anaconda3\etc\jupyter\jupyter_notebook_config.json
[D 11:27:04.216 NotebookApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\aclimente\.jupyter\jupyter_notebook_config.json
```

Without `--debug` flag doesn't show anything (just hangs).

**Comment by jasongrout** [comment]
1. If you want to launch JupyterLab, you'll need to use `jupyter lab`, not `jupyter notebook` (or `jupyter-lab`? Not sure why you need the dash?)
2. Using `--no-browser` means "do not open up a browser automatically". Are you wanting to open a browser automatically? If so, don't use that option.

**Comment by ClimenteA** [comment]
Hi Jason,

With the dash - was suggested by docs if it doesn't open (in the Scripts folder there is `jupyter-notebook.exe` )
`jupyter lab` doesn't work either probably they are dependent on each other.

I copied an embeded python version installed all needed packages on it and still the same issue...


```
D:\python381\Scripts>jupyter notebook --debug
[D 12:33:06.992 NotebookApp] Searching ['D:\\python381\\Scripts', 'C:\\Users\\aclimente\\.jupyter', 'd:\\python381\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 12:33:06.992 NotebookApp] Looking for jupyter_config in C:\ProgramData\jupyter
[D 12:33:06.992 NotebookApp] Looking for jupyter_config in d:\python381\etc\jupyter
[D 12:33:06.992 NotebookApp] Looking for jupyter_config in C:\Users\aclimente\.jupyter
[D 12:33:06.992 NotebookApp] Looking for jupyter_config in D:\python381\Scripts
[D 12:33:06.992 NotebookApp] Looking for jupyter_notebook_config in C:\ProgramData\jupyter
[D 12:33:07.008 NotebookApp] Looking for jupyter_notebook_config in d:\python381\etc\jupyter
[D 12:33:07.008 NotebookApp] Looking for jupyter_notebook_config in C:\Users\aclimente\.jupyter
[D 12:33:07.008 NotebookApp] Loaded config file: C:\Users\aclimente\.jupyter\jupyter_notebook_config.py
[D 12:33:07.008 NotebookApp] Looking for jupyter_notebook_config in D:\python381\Scripts
[D 12:33:07.008 NotebookApp] Ignoring min_open_files_limit because the limit cannot be adjusted (for example, on Windows)
[D 12:33:07.008 NotebookApp] Paths used for configuration of jupyter_notebook_config:
        C:\ProgramData\jupyter\jupyter_notebook_config.json
[D 12:33:07.008 NotebookApp] Paths used for configuration of jupyter_notebook_config:
        d:\python381\etc\jupyter\jupyter_notebook_config.json
[D 12:33:07.008 NotebookApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\aclimente\.jupyter\jupyter_notebook_config.json
```


Had some issues on Anaconda installation/uninstall  on admin/user site probably that's the issue...

I will work for sure on next windows instalation..
