### ISSUE TITLE
ABCWidgetFactory should clear signal data on dispose

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5843]
The ABCWidgetFactory class has a signal, but does not clear its signal data on dispose: https://github.com/jupyterlab/jupyterlab/blob/dab0073ad62a5cee98868f6225c3c9784e71f237/packages/docregistry/src/default.ts#L310-L315

It should do something like: https://github.com/jupyterlab/jupyterlab/blob/dab0073ad62a5cee98868f6225c3c9784e71f237/packages/completer/src/handler.ts#L130-L139

**Comment by rahulpshah** [comment]
Hi @jasongrout, if anyone is not working on this issue, I would like to work on it.

**Comment by ian-r-rose** [comment]
Go for it @rahulpshah !

**Comment by jasongrout** [comment]
It should be as straightforward as copy and pasting that other dispose function into the abcwidgetfactory.

**Comment by ajbozarth** [comment]
Closing, this was fixed by #7833
