### ISSUE TITLE
Refactor core JupyterLab APIs to make it easier to reuse components

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#5847]
@yuvipanda has been doing some fantastic work to use different JupyterLab components outside of the main lab application. Initially this work was done through improving the notebook example, but there is a broader set of usage cases where it would be really nice to have a set of APIs that make it easy to reuse core JupyterLab components in different contexts. Also relevant for widgets, dashboarding, etc.

This is a meta-issue to discuss the broader API changes needed to make this easy.  I will let others fill in the technical details, as they have been working more closely on the related PR's.

@yuvipanda @SylvainCorlay @afshin @ian-r-rose @jasongrout (and others...).

**Comment by yuvipanda** [comment]
https://github.com/jupyterlab/jupyterlab/pull/5845 is most relavent PR.

My end goal of sorts is to have a 'simplest-notebook' thing that has *just* the notebook interface, working widgets, *maybe* extensions that only do things to the Notebook itself, and nothing else.

**Comment by saulshanabrook** [comment]
Here is a list of all the public things on `JupyterLab`:

One possibility is to move some of this into separate extensions:

```typescript
    /**
     * The document registry instance used by the application.
     */
    readonly docRegistry: DocumentRegistry;
    /**
     * The command linker used by the application.
     */
    readonly commandLinker: CommandLinker;
    /**
     * The service manager used by the application.
     */
    readonly serviceManager: ServiceManager;
    /**
     * A list of all errors encountered when registering plugins.
     */
    readonly registerPluginErrors: Array<Error>;
    /**
     * A method invoked on a document `'contextmenu'` event.
     *
     * #### Notes
     * The default implementation of this method opens the application
     * `contextMenu` at the current mouse position.
     *
     * If the application context menu has no matching content *or* if
     * the shift key is pressed, the default browser context menu will
     * be opened instead.
     *
     * A subclass may reimplement this method as needed.
     */
    protected evtContextMenu(event: MouseEvent): void;
    /**
     * Whether the application is dirty.
     */
    readonly isDirty: boolean;
    /**
     * Whether the application is busy.
     */
    readonly isBusy: boolean;
    /**
     * Returns a signal for when application changes its busy status.
     */
    readonly busySignal: ISignal<JupyterLab, boolean>;
    /**
     * Returns a signal for when application changes its dirty status.
     */
    readonly dirtySignal: ISignal<JupyterLab, boolean>;
    /**
     * The information about the application.
     */
    readonly info: JupyterLab.IInfo;
    /**
     * Promise that resolves when state is first restored, returning layout description.
     *
     * #### Notes
     * This is just a reference to `shell.restored`.
     */
    readonly restored: Promise<ApplicationShell.ILayout>;
    /**
     * Walks up the DOM hierarchy of the target of the active `contextmenu`
     * event, testing the nodes for a user-supplied funcion. This can
     * be used to find a node on which to operate, given a context menu click.
     *
     * @param test - a function that takes an `HTMLElement` and returns a
     *   boolean for whether it is the element the requester is seeking.
     *
     * @returns an HTMLElement or undefined, if none is found.
     */
    contextMenuFirst(test: (node: HTMLElement) => boolean): HTMLElement | undefined;
    /**
     * Set the application state to dirty.
     *
     * @returns A disposable used to clear the dirty state for the caller.
     */
    setDirty(): IDisposable;
    /**
     * Set the application state to busy.
     *
     * @returns A disposable used to clear the busy state for the caller.
     */
    setBusy(): IDisposable;
    /**
     * Register plugins from a plugin module.
     *
     * @param mod - The plugin module to register.
     */
    registerPluginModule(mod: JupyterLab.IPluginModule): void;
    /**
     * Register the plugins from multiple plugin modules.
     *
     * @param mods - The plugin modules to register.
     */
    registerPluginModules(mods: JupyterLab.IPluginModule[]): void;
```

**Comment by saulshanabrook** [comment]
Note that the first argument to `activate` *has* to be the application, which has to have a `shell` property that point to the base widget.

**Comment by jasongrout** [comment]
Currently we do have plugins that don't depend on the JupyterLab app, like the rendermime plugins. Perhaps that's a useful pattern to explore - are there other types of simplified plugins that we can support? For example, ipywidgets could probably be a "document plugin", that just gets notified when a new document of a particular type is created, along with the widget and context for that document.

Then we build out a few stubs for supporting things like rendermime plugins, theme plugins, document plugins, etc. outside of JLab.

**Comment by quigleyj-mavenomics** [comment]
We've written a standalone notebook viewer using JupyterLab packages with some success- the biggest pain points so far have been in mocking required services for things that aren't needed for the viewer and determining a concrete list of what services *are* required.

Aside from that, it'd also be nice if we could target `IWidgetExtensions` (or their replacements) to documents-with-kernels, instead of a particular type of document widget. But I think that may be a separate concern.

**Comment by bollwyvl** [comment]
This is a great discussion. A high-value output of this would be a single
file (even icons) that could optionally be inlined into html, allowing for
archive-grade artifacts. Having a DOMContentsManager would allow raw ipynb,
csv, etc to be directly embedded without going through the json size bloat.

Packaged separately as an nbconvert module, this could be the
next-generation nbviewer. I did this in a hacky way with
https://deathbeds.github.io/jyve , but it required mocking tons of things.
While extensions would remain a 🐻, it would at least be tractable to have
builds keyed to the hashes of the the extensions on question... on
nbviewer, only a few "spins" would be practical, e.g. widgets, plotly,
bokeh, mpl, etc.

**Comment by SylvainCorlay** [comment]
> My end goal of sorts is to have a 'simplest-notebook' thing that has just the notebook interface, working widgets, maybe extensions that only do things to the Notebook itself, and nothing else.
> 

Do you plan on keeping components such as the menu bar and side tabbars? (I am asking because of the [sidecar](https://github.com/jupyter-widgets/jupyterlab-sidecar) widget)

**Comment by jasongrout** [comment]
@afshin, @yuvipanda - is this resolved now with #5845?

**Comment by afshin** [comment]
@jasongrout Yes.

**Comment by ellisonbg** [comment]
@quigleyj-mavenomics where is that standalone renderer? Have you looked at refactoring it based on #5845 ?

**Comment by quigleyj-mavenomics** [comment]
@ellisonbg It's not open source _yet_ but we (Mavenomics) should have something to announce soon-ish. It's part of a wider dashboarding suite for JupyterLab that we're codenaming "Jovian" (though that name might change). Here's a preview of what the standalone viewer looks like:

![Codename "Jovian" viewer](https://user-images.githubusercontent.com/20070398/53905297-30946300-4016-11e9-909a-04c0bfa7d848.png)

Internally, we're waiting for other bits of our framework to settle (including kicking out the layout engine to a separate package- would that be of use to https://github.com/jupyterlab/jupyterlab/issues/1640#issuecomment-464945774?), but I've done some experiments to asses risk. The `JupyterFrontEnd` changes will go a long way towards cleaning it up- We won't need to setup the various services and registries manually, and it can injest JupyterLab extensions directly (which I'm most excited about!)

**Comment by jasongrout** [comment]
That looks great! Are you or colleagues planning on being at the Dashboarding Jupyter Community Workshop in Paris? If you can come, contact @SylvainCorlay or @pbugnion. See https://blog.jupyter.org/jupyter-community-workshop-dashboarding-with-project-jupyter-b0e421bdf164

**Comment by jasongrout** [comment]
@quigleyj-mavenomics - just curious, do you have ipywidgets support in that dashboard viewer?

**Comment by ellisonbg** [comment]
@quigleyj-mavenomics ooohhh, thanks for sharing. Different parts of this may very well be related to the dashboards effort. Excited to see where this goes and have a look at the standalone renderer when it is released. When that happens could you open a new issue pointing the community to it (to be easy to find).

[as an aside, the name "jovian" is already being used in the jupyter community and I think it will confuse people to have a project with that name–totally understand its usage as a private codename though ;-)]

**Comment by quigleyj-mavenomics** [comment]
@jasongrout Yep! We have support for anything that the RenderMime registry can display (though we can do a whole lot more than just that!). IPyWidgets work using that mechanism, and we have experimental support for hooking them into our dashboard data binding (which is where the real power is). Here's an IntSlider bound to a variable called `myval`:

![An IPyWidgets IntSlider bound to a 'myval' global](https://user-images.githubusercontent.com/20070398/53916583-73fbcb00-4030-11e9-9dc8-3c050eaa8d79.png)

**Comment by jasongrout** [comment]
> as an aside, the name "jovian" is already being used in the jupyter community

Actually, it's "Jovyan", with a y of course :). https://github.com/jovyan/
