### ISSUE TITLE
cannot paste a sentence in a markdown file

### ISSUE THREAD

**Issue by PhilosopherZ** [jupyterlab/jupyterlab#5848]
Hi! Thanks for using JupyterLab.

If you are reporting an issue with JupyterLab, please use the [GitHub issue](https://github.com/jupyterlab/jupyterlab/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

The JupyterLab team and Project Jupyter value our community, and JupyterLab
follows the Jupyter [Community Guides](https://jupyter.readthedocs.io/en/latest/community/content-community.html).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser [e.g. chrome 69.0, firefox 62.0]
- JupyterLab [e.g. 0.34.2]

**Additional context**

If available, please include the following details:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser console here.
</pre>
</details>

**Comment by PhilosopherZ** [comment]
I don't know why I can't paste a sentence into a markdown file.

**Comment by jasongrout** [comment]
Thanks for asking. What did you try doing to paste a sentence? Was the markdown file opened in a code editor? Can you give the sequence of steps you tried, or a screencast showing what you did?

Also, when you open an issue, you can fill in the template that appears, instead of submitting it and then adding a comment.

**Comment by PhilosopherZ** [comment]
Sorry, I accidentally clicked the button and sent it out before I could edit the template.
For example, copy a sentence and paste it into a.md file, but it doesn't work
![image](https://user-images.githubusercontent.com/33093881/50880209-8da9d900-1418-11e9-8116-7d5181f330d5.png)
![image](https://user-images.githubusercontent.com/33093881/50880341-1759a680-1419-11e9-8bf3-8728e8669a4b.png)

**Comment by jasongrout** [comment]
How are you trying to paste into the code editor?

**Comment by jasongrout** [comment]
And what web browser, OS, JLab version, etc. are you using? Any errors in the browser Javascript console?

**Comment by PhilosopherZ** [comment]
Google Chrome, JLab 0.35.3.  I just solved it!   
I just solved it.Select default. **Thank you very much for your patience**
![image](https://user-images.githubusercontent.com/33093881/50881868-e7f96880-141d-11e9-8723-bcf1a9a087e0.png)

**Comment by jasongrout** [comment]
Great, thanks for following up here!
