### ISSUE TITLE
When importing modules in Jupyter Lab it gives an error

### ISSUE THREAD

**Issue by MichaelSchroter** [jupyterlab/jupyterlab#5851]
Hi All,

I am using Jupyter Lab and I get an error when loading the modules `Javascript Error: IPython is not defined`. Please check the code below. 

```
#!/usr/bin/env ipython
#Load the needed modules

import numpy as np
import sklearn as sk
import pandas as pd

from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import HuberRegressor
from sklearn.svm import SVR
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder

from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import StratifiedKFold

import xgboost as xgb
from xgboost import XGBRegressor

import dask.dataframe as dd
from dask import delayed
from dask.distributed import Client
from sklearn.externals.joblib import parallel_backend
client = Client(processes=False)

from imblearn.over_sampling import SMOTE, ADASYN
from imblearn.under_sampling import ClusterCentroids

%matplotlib inline
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter

import scipy.interpolate as interp

import seaborn as sns

import operator

import gc

import itertools

import math

from tqdm import tqdm
tqdm.monitor_interval = 0

from keras import models
from keras.optimizers import SGD
from keras.layers import Dense, Dropout
from keras.utils import to_categorical
from keras.datasets import mnist
from keras.utils.vis_utils import model_to_dot

from IPython.display import SVG
import livelossplot
plot_losses = livelossplot.PlotLossesKeras()

import warnings
warnings.filterwarnings("always")

import os
os.environ["TF_CPP_MIN_LOG_LEVEL"]="3"

%autosave 180

```
The above code gives the following error on Jupyter Lab:

`Javascript Error: IPython is not defined`

I am using python3.5, Jupyter Lab and firefox version 60.4.0esr (64-bit) on debian linux stretch. It would be great if some one could help me solve this problem. There was a similar issue on stackoverflow and it recommended to include %matplotlib inline. But as you could see even after it has been included the output still gives the error. This only happens when on Jupyter Lab. This error does not show in Jupyter Notebook.

It would be great if someone could help me in this regard.

Thanks

Michael

**Comment by jasongrout** [comment]
This sounds like an error in your system configuration. The code you pasted - that's in a notebook cell? The first line seems to be the first line of a python script.

Can you narrow this down to a much smaller reproducible example? What's a minimal code block that has the issue?

**Comment by MichaelSchroter** [comment]
Hi,

Thanks for the reply. I think it is from the `matplotlib` library. Furthermore I would like to let you know that jupyter lab is quite slow than jupyter notebook on my computer (with 4Gb RAM). It tends to crash on startup all the time.

Thanks

Michael
