### ISSUE TITLE
Create a "temp" workspace

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#5854]
We recently ran into an issue where clicking on a jupyter link that points to jupyter lab would cause a "you can't have two windows open with the same workspace" message to pop up.

In teaching, it's common to give students lots of links that they click on...what we'd like to do is have a jupyterlab interface but let students open multiple tabs (I'm assuming that clicking a link can never direct them to an already-open tab).

Would it be possible to reserve a specific workspace name for "temporary" workspaces? E.g. if I send you to `/lab/workspaces/TEMP`, it would:

1. Create a random name for a workspace and activate it
2. Delete that workspace after some period of inactivity

This way, we could send links to students that will generate temp workspaces under the hood, but we won't clutter their workspace lists with a bunch of randomly-generated stuff.

What do folks think?

**Comment by jasongrout** [comment]
Another thought from in-person discussion is to *always* create a temporary workspace automatically if you hit a workspace twice, including the default workspace ("untitled-435" anyone?). Then give the user the ability to rename a workspace to save it permanently.

**Comment by dhirschfeld** [comment]
Was just going to open an issue to request this exact functionality - i.e. automatically create temp workspaces rather than requesting input from the user

**Comment by afshin** [comment]
One of the biggest benefits of named workspaces is that the names carry semantic value. So if we create a paradigm where the user sees auto-generated names frequently, the names will not have any meaning.

That being said, it would be pretty straightforward to check for a specific query string parameter and generate a new workspace name. The way it works, mechanically, would be somewhat like the way the `reset` query string parameter works: before the application has loaded, it could short-circuit loading and redirect the user to a new workspace URL.

**Comment by saulshanabrook** [comment]
> One of the biggest benefits of named workspaces is that the names carry semantic value. So if we create a paradigm where the user sees auto-generated names frequently, the names will not have any meaning.

The ability to reload a page and get the same layout is also a big benefit!

**Comment by afshin** [comment]
> The ability to reload a page and get the same layout is also a big benefit! Can temporary workspaces fill the niche where you want this behavior but don't care about naming the different layouts?

Yes, that's what the upshot would be from the query string parameter short-circuiting the routing by generating a new workspace name and redirecting the user to it.

**Comment by choldgraf** [comment]
I agree that a good start would be to use a parameter to enable this (e.g., that we could bake into `nbgitpuller`, which is the main case in which we've run into this problem). Longer-term, maybe there'd be value in designing UX around automatically naming and offering users the opportunity to re-name workspaces.
