### ISSUE TITLE
tabs widget not working in JupyterLab 0.35.4

### ISSUE THREAD

**Issue by DentonGentry** [jupyterlab/jupyterlab#5859]
Hi! Thanks for using JupyterLab.

If you are reporting an issue with JupyterLab, please use the [GitHub issue](https://github.com/jupyterlab/jupyterlab/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

The JupyterLab team and Project Jupyter value our community, and JupyterLab
follows the Jupyter [Community Guides](https://jupyter.readthedocs.io/en/latest/community/content-community.html).

**Describe the bug**
Tabs widget does not render in JupyterLab 0.35.4.

The output is text that looks like the repr of the Tabs object:
Tab(children=(Text(value='', description='P0'), Text(value='', description='P1'), Text(value='', description='…

**To Reproduce**
Using the code from https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Tabs

import ipywidgets as widgets
tab_contents = ['P0', 'P1', 'P2', 'P3', 'P4']
children = [widgets.Text(description=name) for name in tab_contents]
tab = widgets.Tab()
tab.children = children
for i in range(len(children)):
    tab.set_title(i, str(i))
tab

**Expected behavior**
Widget display

**Screenshots**
Screenshot attached showing what renders on my system.

![screen shot 2019-01-11 at 3 04 51 pm](https://user-images.githubusercontent.com/1140756/51063994-4c4d3100-15b2-11e9-9ca6-ae4e4b8c9cea.png)

**Desktop (please complete the following information):**

- OS: MacOS 10.14.2
- Browser: Chrome Version 71.0.3578.98
- JupyterLab : 0.35.4

**Additional context**

If available, please include the following details:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.

$PATH:
	./venv/bin
	/Users/dgentry/Documents/Code/CodeEarth.drawdown/venv/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin

sys.path:
	/Users/dgentry/Documents/Code/CodeEarth.drawdown/venv/bin
	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip
	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7
	/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload
	/Users/dgentry/Documents/Code/CodeEarth.drawdown/venv/lib/python3.7/site-packages
	/Users/dgentry/Documents/Code/CodeEarth.drawdown/venv/lib/python3.7/site-packages/aeosa

sys.executable:
	/Users/dgentry/Documents/Code/CodeEarth.drawdown/venv/bin/python3

sys.version:
	3.7.0 (default, Aug 22 2018, 15:22:33)
	[Clang 9.1.0 (clang-902.0.39.2)]

platform.platform():
	Darwin-18.2.0-x86_64-i386-64bit

which -a jupyter:
	./venv/bin/jupyter
	/Users/dgentry/Documents/Code/CodeEarth.drawdown/venv/bin/jupyter
	/usr/local/bin/jupyter

pip list:
	Package            Version
	------------------ -------
	appnope            0.1.0
	appscript          1.0.1
	astroid            2.0.4
	atomicwrites       1.2.1
	attrs              18.2.0
	autopep8           1.4
	backcall           0.1.0
	bleach             3.0.2
	click              6.7
	cycler             0.10.0
	decorator          4.3.0
	defusedxml         0.5.0
	entrypoints        0.2.3
	Flask              1.0.2
	gunicorn           19.9.0
	ipykernel          5.1.0
	ipython            7.0.1
	ipython-genutils   0.2.0
	ipywidgets         7.4.2
	isort              4.3.4
	itsdangerous       0.24
	jedi               0.13.1
	Jinja2             2.10
	jsonschema         2.6.0
	jupyter            1.0.0
	jupyter-client     5.2.3
	jupyter-console    6.0.0
	jupyter-core       4.4.0
	jupyterlab         0.35.4
	jupyterlab-server  0.2.0
	kiwisolver         1.0.1
	lazy-object-proxy  1.3.1
	MarkupSafe         1.0
	matplotlib         3.0.2
	mccabe             0.6.1
	mistune            0.8.4
	more-itertools     4.3.0
	nbconvert          5.4.0
	nbformat           4.4.0
	notebook           5.7.0
	numpy              1.15.1
	pandas             0.23.4
	pandocfilters      1.4.2
	parso              0.3.1
	pexpect            4.6.0
	pickleshare        0.7.5
	pip                10.0.1
	pluggy             0.7.1
	prometheus-client  0.4.2
	prompt-toolkit     2.0.6
	psutil             5.4.7
	ptyprocess         0.6.0
	py                 1.6.0
	pycodestyle        2.4.0
	Pygments           2.2.0
	pylint             2.1.1
	pyparsing          2.3.0
	pytest             3.8.0
	python-dateutil    2.7.3
	pytz               2018.5
	pyzmq              17.1.2
	qtconsole          4.4.2
	scikit-learn       0.20.0
	scipy              1.1.0
	Send2Trash         1.5.0
	setuptools         39.0.1
	simplegeneric      0.8.1
	six                1.11.0
	sklearn            0.0
	terminado          0.8.1
	testpath           0.4.2
	tornado            5.1.1
	traitlets          4.3.2
	wcwidth            0.1.7
	webencodings       0.5.1
	Werkzeug           0.14.1
	widgetsnbextension 3.4.2
	wrapt              1.10.11
	xlrd               1.2.0
	xlwings            0.11.8
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.

</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser console here.
</pre>
</details>

**Comment by jasongrout** [comment]
Do you have the JupyterLab ipywidgets extension installed?

https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-the-jupyterlab-extension

**Comment by DentonGentry** [comment]
Oh, no I had not. After installing nodejs and the extension, the widgets render now.

Sorry for wasting your time, I'd searched but didn't find the page mentioning the extension. Searching again now I find many mentions, my Google-fu was weak before.
