### ISSUE TITLE
Auto advance on user input

### ISSUE THREAD

**Issue by agoose77** [jupyterlab/jupyterlab#5861]
Currently, when hitting return following entering user input in a JupyterLab notebook, the same cell remains "active", and hence you have to click the subsequent cell in order to continue manual execution. 

A better UX would involve activating the next cell after the user has finished entering user input

**Comment by agoose77** [comment]
@meeseeksdev "good first issue"

**Comment by vidartf** [comment]
I'm guessing this is related to input on `stdin`?

**Comment by agoose77** [comment]
Yes, STDIN <input> elements in the notebook effectively inhibit run-by-repeated-shift_enter, as the cell does not advance once the user hits return.

**Comment by jasongrout** [comment]
How does it work in the classic notebook?

**Comment by agoose77** [comment]
I'm closing this as I'm not going to work on it right now, and it's not helping anyone just leaving it open!
