### ISSUE TITLE
Autocomplete cycle options using <KEY>

### ISSUE THREAD

**Issue by eleijonmarck** [jupyterlab/jupyterlab#5863]
Hi! Thank you for making an amazing product. Possibility to change behaviour of TAB autocompletion cycling.

Related issue #4305.
Autocomplete suggestions are great. Would it be possible to get <TAB> (or CTRL-N / CTRL-P) to get the next option from the menu and not complete the suggestion. 

**Reproduce**
![tab_completion](https://user-images.githubusercontent.com/7727602/51146417-0a90e480-1857-11e9-85d1-8e51586e22b0.gif)

**Expected behavior**
![tab_completion_expected](https://user-images.githubusercontent.com/7727602/51146517-59d71500-1857-11e9-80a4-dc9c85755c07.gif)

Edit:
The expected behaviour is taken from ipython, which jupyter is built upon so I think it is a reasonable assumption that users would expect this behaviour.

**Comment by jasongrout** [comment]
Great idea! What's typical in other editors?

**Comment by vidartf** [comment]
Patterns I have seen:
- Arrows and page up/down to navigate list.
- Tab and Shift+Tab for next/prev (sometime with some logic to differentiate Tab = next vs Tab = accept current).

**Comment by eleijonmarck** [comment]
I have seen and use:

* ctrl + N (down)
* ctrl + P (up)

**Comment by eleijonmarck** [comment]
Pattern described is:

* ctrl + n (up)
* ctrl + p (down)

as well as adding the <TAB> functionality

**Comment by samueldy** [comment]
I do think autocomplete should not execute a completion unless you explicitly trigger it (e.g., with the Tab or Enter key). But I actually quite like using the Tab key to confirm your current choice in the menu once you've used the arrow keys to navigate to it. (E.g., the behavior in Jupyter Lab 0.35.4.) 

I often have my left finger on the Tab key to invoke autocompletion, and it's quicker to press it again with my left hand just after choosing an option than using the Enter key with my right hand (as is the case in v1.0.2). Having `completer:select-notebook` bound to Enter sometimes forces you to do both the completion selection and completion execution with one hand, which slows you down.

Could we make the behavior of the Tab key optional? I've not seen a way to bind the Tab key to both `completer:invoke-notebook` and `completer:select-notebook`. E.g., this:

```json
{"shortcuts": [
        {
            "command": "completer:select-notebook",
            "keys": [
                "Tab"
            ],
            "selector": ".jp-Notebook.jp-mod-editMode .jp-mod-completer-enabled"
        },
        {
            "command": "completer:invoke-notebook",
            "keys": [
                "Tab"
            ],
            "selector": ".jp-Notebook.jp-mod-editMode .jp-mod-completer-enabled"
        },
]}
```

disables autocomplete invocation because `completer:select-notebook` is listed first, and the opposite would happen if I reversed the order. Is there any way to allow Tab to do both again, while requiring an explicit Tab after options are displayed to do the autocompletion?

**Comment by lucasfariaslf** [comment]
What's the status on this?

**Comment by Zhou-Yucheng** [comment]
> I do think autocomplete should not execute a completion unless you explicitly trigger it (e.g., with the Tab or Enter key). But I actually quite like using the Tab key to confirm your current choice in the menu once you've used the arrow keys to navigate to it. (E.g., the behavior in Jupyter Lab 0.35.4.)
> 
> I often have my left finger on the Tab key to invoke autocompletion, and it's quicker to press it again with my left hand just after choosing an option than using the Enter key with my right hand (as is the case in v1.0.2). Having `completer:select-notebook` bound to Enter sometimes forces you to do both the completion selection and completion execution with one hand, which slows you down.
> 
> Could we make the behavior of the Tab key optional? I've not seen a way to bind the Tab key to both `completer:invoke-notebook` and `completer:select-notebook`. E.g., this:
> 
> ```json
> {"shortcuts": [
>         {
>             "command": "completer:select-notebook",
>             "keys": [
>                 "Tab"
>             ],
>             "selector": ".jp-Notebook.jp-mod-editMode .jp-mod-completer-enabled"
>         },
>         {
>             "command": "completer:invoke-notebook",
>             "keys": [
>                 "Tab"
>             ],
>             "selector": ".jp-Notebook.jp-mod-editMode .jp-mod-completer-enabled"
>         },
> ]}
> ```
> 
> disables autocomplete invocation because `completer:select-notebook` is listed first, and the opposite would happen if I reversed the order. Is there any way to allow Tab to do both again, while requiring an explicit Tab after options are displayed to do the autocompletion?

I do want this feature, too!   
That is, auto-complete with TAB key only (hit TAB twice to confirm, instead of hit ENTER).  
It will enhance efficiency greatly!

**Comment by quantum-booty** [comment]
I would love to see this too. Yes it is minor improvement, but they do make a difference when you use it hundreds of times a day.

**Comment by temiafeye** [comment]
Cycle completion, and easy access to docs in Jupyterlab would be a nice to have. I miss it while working

**Comment by joelostblom** [comment]
@eleijonmarck  I believe you can close this since PR #10147 was merged recently (I think the functionality will be available in 3.1). Thank you so much creating the PR @cameron-toy, it will be much nicer to switch between JL and other programs now that tab works consistently =)

**Comment by minhduc0711** [comment]
Hmm, is it possible to make it confirm the suggestion while tab cycling as well?

https://user-images.githubusercontent.com/34294427/119919051-cddf6700-bf93-11eb-8bc1-65dbedbc57d8.mp4

**Comment by eleijonmarck** [comment]
@joelostblom I will close the PR if you say that it is merged.

Awesome work!!!!!!!!!!!!!!!!!!!!!! everyone involved
especially @cameron-toy
