### ISSUE TITLE
UI broken by broken symlink

### ISSUE THREAD

**Issue by flying-sheep** [jupyterlab/jupyterlab#5866]
When I start a jupyterlab instance in a directory containing a broken link, the UI tries to fetch its stats and fails. This results in a “500 internal server error” popup and the files view staying blank. The traceback:

```pytb
[E 10:56:55.627 LabApp] Uncaught exception GET /api/contents/?content=1&1547546215612 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/?content=1&1547546215612', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/usr/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/usr/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/usr/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/usr/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/usr/lib/python3.7/site-packages/notebook/utils.py", line 146, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    OSError: [Errno 107] Transport endpoint is not connected: '/home/phil/Videos'
```

**Comment by jasongrout** [comment]
This looks like a problem in the Jupyter notebook server, and particularly dealing with `/home/phil/Videos`. 

1. Does Jupyter Notebook work in the same directory?
2. What kind of thing is `/home/phil/Videos`? Is it perhaps a UDF socket or something like that?
3. It looks like lots of relevant things pop up when googling for that error: "OSError: [Errno 107] Transport endpoint is not connected:"

**Comment by flying-sheep** [comment]
It’s a symlink to a mountpoint. I probably had a Linux kernel update that invalidated the mount point, making the symlink point to some broken thing instead of a mounted directory.

**Comment by jasongrout** [comment]
So this seems maybe a bit different than https://github.com/jupyter/notebook/pull/3878, in that the symlink still exists, but there is something wrong at the end of it? If it's not the same issue as that PR, do you mind opening an issue in the notebook repo?

**Comment by flying-sheep** [comment]
I don’t, but GitHub has a beta for moving issues. If you have the permissions, you could move this one to there!
