### ISSUE TITLE
Recommended way to embed theme-light-extension in a web context

### ISSUE THREAD

**Issue by rsmith96** [jupyterlab/jupyterlab#5867]
This issue is somehow related to #5849 as I cannot find the source code which produces the static/embed.css when installing theme-light-extension as a node package.

I notice static/embed.css contains a rule which affect the body tag at line 1973 (package version 0.19.1)
```
body {
  font-family: var(--jp-ui-font-family);
  background: var(--jp-layout-color3);
  margin: 0;
  padding: 0;
  overflow: hidden;
}
```

I appreciate this extension is primarily designed to be used in a jupyterlab notebook context, however I am wondering:
- why is there a rule which affects the body tag ?
- can the theme-light extension be embedded in a static html context ?
- if so what is the proper way to do it  ?

So far I am manually overriding the body rule to reset to auto as a temporary workaround.

**Comment by jasongrout** [comment]
Oh wow, thanks for pointing this out. I'm often concerned about embedding things in webpages, and having a `body` rule generally is a bad idea in my mind.
I do see some global defaults in the theme, which I wish we could scope somehow: https://github.com/jupyterlab/jupyterlab/blob/6bd774aee427ceaaf917bf4681820ca7bd449c29/packages/theme-light-extension/style/index.css#L9-L18

I see a body rule that matches what you see in the application plugin: https://github.com/jupyterlab/jupyterlab/blob/8da05c21f7ea9a48d8d6ff97d8568591d4ff1d53/packages/application/style/index.css#L13-L19

**Comment by jasongrout** [comment]
Thanks!
