### ISSUE TITLE
index.css in extension does not load

### ISSUE THREAD

**Issue by dafnamargalit** [jupyterlab/jupyterlab#5869]
I am currently creating a JupyterLab extension that will personalize the JupyterLab experience. So far, I have been able to add additional menu items to the drop down menus and add widgets, but I have been having difficulty with changing the theme (such as the colors). The current index.css file I have is almost exactly the same as that of the JupyterLab dark theme, except for a few color changes. I have been able to test what the theme looks like by loading the css file dynamically through a notebook (I attached an image of what that looks like), but how do I ensure that the theme changes I make will load automatically/with the extension?

<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/19866424/51197511-00023980-18af-11e9-8fa9-6bf4ab5d199c.png">

**Comment by timkpaine** [comment]
there are a few things to do:
- https://github.com/timkpaine/jupyterlab_iframe/blob/master/src/index.ts#L25
- https://github.com/timkpaine/jupyterlab_iframe/blob/master/package.json#L20

**Comment by dafnamargalit** [comment]
It appears that I already have those lines written in. Could it be that the index.css file I have is unreadable? Here are my package.json and tsconfig.json files:
package.json:
`
{
  "name": "rm-studio-extension",
  "version": "0.1.0",
  "description": "A JupyterLab Extension for RM studio.",
  "keywords": [
    "jupyter",
    "jupyterlab",
    "jupyterlab-extension"
  ],
  "homepage": "https://github.com/my_name/myextension",
  "bugs": {
    "url": "https://github.com/my_name/myextension/issues"
  },
  "license": "BSD-3-Clause",
  "author": "Dafna Margalit",
  "files": [
    "lib/**/*.{d.ts,eot,gif,html,jpg,js,js.map,json,png,svg,woff2,ttf}",
    "style/**/*.{css,eot,gif,html,jpg,json,png,svg,woff2,ttf}"
  ],
  "main": "lib/index.js",
  "types": "lib/index.d.ts",
  "repository": {
    "type": "git",
    "url": "https://github.com/my_name/myextension.git"
  },
  "scripts": {
    "build": "tsc",
    "clean": "rimraf lib",
    "prepare": "npm run clean && npm run build",
    "watch": "tsc -w"
  },
  "dependencies": {
    "@jupyterlab/application": "^0.19.1",
    "@jupyterlab/mainmenu": "^0.8.1"
  },
  "devDependencies": {
    "rimraf": "^2.6.1",
    "typescript": "~3.1.1"
  },
  "jupyterlab": {
    "extension": true
  }
}

`
tsconfig.json:
`{
  "compilerOptions": {
    "declaration": true,
    "lib": ["es2015", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "rootDir": "src",
    "strict": true,
    "strictNullChecks": false,
    "target": "es2015",
    "types": []
  },
  "include": ["src/*"]
}
`

**Comment by jasongrout** [comment]
Is this still an issue?
