### ISSUE TITLE
Undoing and redoing autocompletion make the editor blank

### ISSUE THREAD

**Issue by Kim-Seonghyeon** [jupyterlab/jupyterlab#5872]
I'm using JupyterLab 0.35.4 .
Each of Undoing, redoing and autocompletion works well.
But undoing and redoing autocompletion make the editor blank, sometimes (especially when the text file is large).

autocompletion 
![undo_auto2](https://user-images.githubusercontent.com/23024050/51235439-da5e5880-19b2-11e9-8b41-3dee27cb17bc.PNG)
![undo_auto3](https://user-images.githubusercontent.com/23024050/51235443-dc281c00-19b2-11e9-9b91-7a06833ea756.PNG)
and undo(ctrl+z)
![undo_auto4](https://user-images.githubusercontent.com/23024050/51235445-ddf1df80-19b2-11e9-841b-4763f5b43021.PNG)

Then, editor is blank.
Editor returns to normal, after clicking editor.

**Comment by jasongrout** [comment]
I tried reproducing this with a file that looked like your screenshot, with about a 1000 lines. I did the completion you show in the file, then did undo, and it only undid the completion, and did not clear all of the text. I tried in both 0.35.4 and 1.0a1.

Can you reproduce this consistently? Can you give more explicit directions (i.e., is it a new file, or a saved file? When was the file last saved? How did you accept the completion, with tab or enter?). If you can reproduce this consistently, can you try with the 1.0a1 prerelease (install using `pip install --pre jupyterlab`)? Thanks!

**Comment by Kim-Seonghyeon** [comment]
Yes, I tried that in all cases you listed and it happened consistently.
The results were the same when using 1.0a1.
The OS I use is Ubuntu 16.04.5 LTS.

**Comment by ian-r-rose** [comment]
I can reproduce this on Ubuntu with Firefox. As soon as there is any user interaction with the text editor, the text becomes visible again. Seems like an editor refresh issue.

**Comment by blink1073** [comment]
Played around with it in the binder (on Ubuntu with FF).  LGTM!
