### ISSUE TITLE
*Output View* is not disposed when closing a notebook

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#5873]
**Describe the bug**

*Output View* is not disposed when closing a notebook. Although it should as coded there:

https://github.com/jupyterlab/jupyterlab/blob/3e3a2c9e295703ff6d441589423e284cc6d5c245/packages/notebook-extension/src/index.ts#L1380-L1381

**To Reproduce**

1. Click on "Create a New View for Output" in the context menu
2. Close the notebook
3. The *Output View* panel is not closed

**Expected behavior**

Output view panels should be disposed when the related notebook is closed.

**Screenshots**

![bug_output_view](https://user-images.githubusercontent.com/8435071/51238535-68b4e900-1977-11e9-92b1-118c12f0a1e9.gif)

**Desktop**

- OS: Windows 7
- Browser Chrome 61
- JupyterLab 0.35.4

**Additional context**

I try following the notebook `dispose` call in the debugger. When the `disposed` signal is emitted, one of the slot is not executed as the `this` object is undefined. This prompts the error shown below.

I was unable to figure out if the called with the undefined `this` is related to the disposal of the output view panel. But if this is the case, the following correction may worked (not tested):

```diff
+  nb.disposed.connect(widget.dispose, widget);
-  nb.disposed.connect(widget.dispose);
```

<details><summary>Browser Output</summary>
<pre>
index.js:220 TypeError: Cannot read property 'isDisposed' of undefined
    at push.FmDU.Widget.dispose (widget.js:58)
    at invokeSlot (index.js:475)
    at Object.emit (index.js:433)
    at Signal.push.qUp9.Signal.emit (index.js:106)
    at Notebook.push.FmDU.Widget.dispose (widget.js:63)
    at Notebook.dispose (widget.js:199)
    at Notebook.dispose (widget.js:647)
    at NotebookPanel.dispose (panel.js:86)
    at current.context.session.shutdown.then (index.js:1450)
    at <anonymous>
</pre>
</details>

**Comment by jasongrout** [comment]
My guess is that connect line should be: `nb.disposed.connect(() => { widget.dispose(); });`

**Comment by jasongrout** [comment]
Oh, right, or what you put there should be fine too.
