### ISSUE TITLE
"Table View" button in setting editor is not visible.

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#5874]
**Describe the bug**
The "Table View" button in the setting editor has wrapped around and is no longer visible.

**To Reproduce**
Open the setting editor from the settings menu.

**Screenshots**
![table-view-missing](https://user-images.githubusercontent.com/159529/51252936-00750000-1995-11e9-9787-3b10fd5fedab.png)

**Desktop (please complete the following information):**

- OS: macOS Mojave (10.14.2)
- Browser: Chrome 71
- JupyterLab `master`

**Comment by fearless0307** [comment]
Hi,
I saw the code. I found that it is a simple CSS issue. When I changed the width of `RAW VIEW` from 50% to 49.9%, `TABLE VIEW` will appear. Actually, when I inspect the page I found that `TABLE VIEW` is just down of `RAW VIEW` due to width issue.

**Comment by bollwyvl** [comment]
The picker could just be "display: flexbox"... we might add another view (a
la react-jsonschema-form). Or better still, a phosphor tabbar app that each
view doesn't have to handle is own button state.

**Comment by fearless0307** [comment]
So, Is my solution is not suitable ??

**Comment by bollwyvl** [comment]
It would work _today_, but hard coded percent widths can run afoul of many
things... Maybe a theme increases some passing or border width, which is
added to the width, and we're back where we started. Flexbox (and maybe
text-overflow) would ensure it always does what we expect... Split the row
into two equal-spaced buttons.

Going to tab bar would also manage the highlighted state.

**Comment by fearless0307** [comment]
Ok,
Instead of hard coded, we can use flex rigth!
Add css in row:
```display: flex;```
and in both view div:
```flex: 1;```
It is also working filne.

**Comment by afshin** [comment]
@fearless0307 Please feel free to open a PR if you are interested in working on this issue.

**Comment by ellisonbg** [comment]
Saw this too, thanks for opening it!
