### ISSUE TITLE
Document React Best Practices

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#5875]
We should create some documentation outlining the best practices of integrating React with JupyterLab. 

@aschlaep gave some helpful feedback about his experience coming into the JupyterLab codebase and one of the sticking points seemed to be understanding what should be done with Phosphor and what should be done with React.

We are still figuring out the best practices here (ala https://github.com/jupyterlab/jupyterlab/issues/5792) but we are currently using React in a number of places in core. We should document things like:

* History, JL was created with Phosphor in mind for rendering, now we are moving some rendering to React components.
* So, most internal hooks require you to pass in Phosphor Widgets. To turn a React component into a widget use `ReactWidget` and `ReactWidget.create` (show examples)
* Most data that changes over time/events are represented by Phosphor signals. Often, you want to have some react component update on a signal. You can use `UseSignal` component to update a React Component dynamically based on a signal. (show example)

As for best practices, maybe:

* Try to create view only react components that aren't tied at all to Phosphor, for UI components (and maybe add to `ui-components` package?
* Follow React best practices (link to docs).
* keep everything as functional components unless you need state
* Push state as far down the tree as possible,  so that on updated data only leaves are re-rendered instead of whole tree.
* We are still figuring out how best to compose signals, or whether to use observables
* We are also still figuring out how/if we can embed phosphor widgets inside react components

**Comment by saulshanabrook** [comment]
Addressing this would close https://github.com/jupyterlab/jupyterlab/issues/5215, a previous issue raised about documenting React integration.

**Comment by saulshanabrook** [comment]
We had a discussion today in our meeting about this. @afshin brought it up in the context of the keyboard shortcut UI plugin, which passes the command registry down a bunch of levels of widgets. Which is a bit annoying and seems like a code smell.

Options that came out of the discussion:

* Use react context / hooks to get access to "globals" like command registry far down tree
* Expose this context in some global package that optionally depends on other plugins

**Comment by bionicles** [comment]
We could definitely use a simple guide to embedding jupyterlab in react apps. This would kill many birds with one stone because we could use embedded jupyterlab to control react dashboards, data platforms, apps, etc. React Native would allow us to have mobile jupyterlab, too. 

How can we improve docs / dev workflow for how to embed JupyterLab inside React, in addition to considerations of how to embed React inside JupyterLab

**Comment by saulshanabrook** [comment]
This was addressed in https://github.com/jupyterlab/jupyterlab/pull/6595
