### ISSUE TITLE
Markdown heading visual anchors inconsistent

### ISSUE THREAD

**Issue by agoose77** [jupyterlab/jupyterlab#5876]
Hi! Thanks for using JupyterLab.

[JupyterLab 0.35.4]

When defining headings in Markdown cells, Jupyter Notebook and Jupyter Lab do not provide the same behaviour. Jupyter Notebook correctly provides visual anchor elements for each heading and subheading, whereas Jupyter Lab only shows the anchor for a particular subheading.

Please see example notebook.
![broken-md-1](https://user-images.githubusercontent.com/1248413/51277312-215a4700-19cf-11e9-801e-3cba295d4000.gif)
![md-broken-2](https://user-images.githubusercontent.com/1248413/51277313-215a4700-19cf-11e9-9556-5da7cb51a1f1.gif)
```notebook
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Some Title\n",
    "## Sub Title\n",
    "***"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Contents"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

```

**Comment by agoose77** [comment]
Upon further inspection, this is the relevant HTML generated for the first cell:
```html
<div class="p-Widget jp-RenderedHTMLCommon jp-RenderedMarkdown jp-MarkdownOutput" data-mime-type="text/markdown"><h1 id="Some-Title">Some Title</h1>
<h2 id="Sub-Title">Sub Title<a target="_self" href="#Sub-Title" class="jp-InternalAnchorLink">¶</a></h2>
<hr>
</div>
```
This is the line of code which runs the anchor generation routine: https://github.com/jupyterlab/jupyterlab/blob/63090ad07a78574b1aea6ba82e1fe3ab08f9c89b/packages/rendermime/src/renderers.ts#L344

**Comment by ian-r-rose** [comment]
Thanks for the report @agoose77. I am having a hard time reproducing this, either on 0.35.4 or on current master. The notebook you have included renders with all the expected anchors.

I'm not really sure what could the be cause of what you are seeing. The implementation of `headerAnchors` looks okay to me...

**Comment by agoose77** [comment]
Whoops, my bad. This is happening because of `jupyterlab-toc`!
