### ISSUE TITLE
Trigger inspection on cursor movement

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#5899]
We currently trigger inspection requests when the text content of an editor with a kernel attached to it changes. This misses cases where the user is navigating the cursor without making edits, or when they select a new editor (e.g., a new cell). 

It would be nice to also trigger inspection for those events. We would have to go to the inspection handler and wire up more editor signals to a new text editor here: https://github.com/jupyterlab/jupyterlab/blob/b6c72e27cb53d7b87415d06c8444043cbf665dcd/packages/inspector/src/handler.ts#L62-L71

In particular, in order to trigger inspection on cursor movement, we would listen to the `editor.model.selections.changed` signal. It may also be useful to wire up an `ActivityMonitor` to throttle the rate of network requests. An example of this is here: https://github.com/jupyterlab/jupyterlab/blob/b6c72e27cb53d7b87415d06c8444043cbf665dcd/packages/docregistry/src/mimedocument.ts#L55-L63

Marking this as a good issue for a new contributor.

**Comment by ntdef** [comment]
Were you expecting that it should call 

https://github.com/jupyterlab/jupyterlab/blob/b6c72e27cb53d7b87415d06c8444043cbf665dcd/packages/inspector/src/handler.ts#L118

on `editor.model.selections.changed`? Does that mean that the function name should change as well?

**Comment by ian-r-rose** [comment]
Yeah, that's what I had in mind. Maybe something like `onEditorChange`? What do you think?

**Comment by ntdef** [comment]
Ship it

**Comment by ntdef** [comment]
Just put out a PR.
