### ISSUE TITLE
Autocomplete for large DataFrame objects wedges the UI

### ISSUE THREAD

**Issue by CSEMike** [jupyterlab/jupyterlab#5911]
Autocomplete appears to take time proportional to the number of object properties, and objects with large properties can have very, very long rendering delays that effective wedge the UI.

An example repro using try.jupyter.com follows.
![slow-completion](https://user-images.githubusercontent.com/151865/51777850-cce05700-20b3-11e9-80aa-f9630e2b051e.gif)

This demo GIF shows the completion delay for a DataFrame with 10,000 columns. The GIF is accelerated; end-to-end time to calculate and render completions is ~30s. Roughly half appears to be calculating completions at the backend. The remaining half is synchronous Javascript which renders the results returned.

I'm surprised about the backend computation time considering that `get_ipython().complete(...)` takes <1s. Perhaps other methods are being called as well.

I speculate that per-property overhead is expected behavior for the completion code, so perhaps fix will require a an upper bound on the number of properties considered and/or results returned.

For easy copy / pasting, the test snippet I used is:

```
%%time
import pandas as pd
import numpy as np
ipy = get_ipython()
rows, cols = 1000, 1000
df = pd.DataFrame(np.random.randn(rows, cols), columns=['col'+str(i) for i in range(cols)])
#_ = ipy.object_inspect('df')
#_ = ipy.complete('df.')
```

**Comment by flutefreak7** [comment]
I'm experiencing what seems to be the autocomplete just not working, but perhaps its just really long delays for some completions.... I see the kernel busy indicator very briefly then what appears like nothing.

I'm trying to autocomplete for bokeh like:

    f = figure()
    f.<TAB>

...and not seeing anything.
