### ISSUE TITLE
Close Tabs to Right disabled

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#5915]
Here is a little glitch I noticed while looking at https://github.com/jupyterlab/jupyterlab/pull/5758.

For example when a csv file is open with both `Editor` and `CSVTable`:

![image](https://user-images.githubusercontent.com/591645/51850622-644ae180-2322-11e9-8854-a5e88e24eec4.png)

The "Close Tabs to Right" entry is disabled, even though there is a tab.

When placing the `CSVTable` in the first position:

![image](https://user-images.githubusercontent.com/591645/51850651-73ca2a80-2322-11e9-86d8-dccf5808c1f0.png)

Reproducible on:

- JupyterLab 0.35.4
- master

**Comment by jasongrout** [comment]
I confirmed that text file tabs do not seem to have "Close Tabs to Right" enabled.

**Comment by jasongrout** [comment]
Actually, I'm not sure why these two functions are just implemented in the docmanager, instead of being application functions: https://github.com/jupyterlab/jupyterlab/blob/bbc1bbd20f69db70e2c38cbf4ef7d0c8f198561d/packages/docmanager-extension/src/index.ts#L722-L753

**Comment by jtpio** [comment]
Along with `closeAll`, `activateNextTab` and so on?

**Comment by afshin** [comment]
cf. https://github.com/jupyterlab/jupyterlab/issues/5979

**Comment by ellisonbg** [comment]
Should we maybe put the "Close Tabs..." in a separate section in the context menu?

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/6052 (thanks @gnestor and everyone involved for this!)
