### ISSUE TITLE
Any thoughts on an "Open recent" menu?

### ISSUE THREAD

**Issue by BoPeng** [jupyterlab/jupyterlab#5924]
I am used to the "Open recent" menu on so many applications (MS Office, VS Code, Atom, Keynote, mac vim, Adobe series of tools, etc) and just noticed that JLab does not have one. Does it make sense to add one?

**Comment by jasongrout** [comment]
I think it can make a lot of sense. Should it be stored as an attribute of the workspace? Keep in mind that if I launch jlab in a different directory, all the paths are different, so the list becomes useless in that case.

**Comment by BoPeng** [comment]
I think most applications store full path and displays only filename. MS Word shows full paths when there are ambiguities.

**Comment by jasongrout** [comment]
My point is that those full path names are relative to the server root, so they wouldn't mean anything if the server was started in a different directory (and hence had a different root).

I do think it would be great to have this when starting a server always from the same directory.

**Comment by BoPeng** [comment]
You are right, and it can be irritating to select a file and only find it missing. So the bottom line is that only files that exist with respect to the server root should be displayed.

**Comment by jasongrout** [comment]
Yes, so perhaps before displaying the list, the extension providing this menu needs to query the server to make sure the file exists. This also would handle the case where a file was deleted, etc.

**Comment by dhirschfeld** [comment]
Could you not also store the server root and then clear the list if it's different?

Or patch the paths with the difference between the saved/new roots!?

**Comment by timhoffm** [comment]
There's a plugin available: https://github.com/tslaton/jupyterlab-recents
