### ISSUE TITLE
Add workspace clearing trick to faq

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5926]
@ian-r-rose had a nice trick at https://github.com/jupyterlab/jupyterlab/issues/3872#issuecomment-459366460 - I think it would be great to have it in a faq.

**Comment by raybellwaves** [comment]
Happy to give this a go. Mind pointing me to the FAQ page?
Did a quick search for faq in the repo  (https://github.com/jupyterlab/jupyterlab/search?p=2&q=faq&unscoped_q=faq ) and found https://github.com/jupyterlab/jupyterlab/blob/c3fff81d3f053c4f94e84263ae785eda56cb55aa/packages/faq-extension/faq.md
