### ISSUE TITLE
Kernel->Restart Kernel and Run All doesn't work for text files

### ISSUE THREAD

**Issue by agoose77** [jupyterlab/jupyterlab#5935]
RE https://github.com/jupyterlab/jupyterlab/issues/5579, the kernel option for Restart Kernel & Run All Cells doesn't work.

**Comment by jasongrout** [comment]
I confirmed this in 1.0a1. The menu items in both the Run menu and the Kernel menus didn't do anything. There as a js error: "uncaught exception: No kernel to restart"
