### ISSUE TITLE
Connection problems installing plotly extension

### ISSUE THREAD

**Issue by jralfonsog** [jupyterlab/jupyterlab#5943]
Good day

I'm having trouble installing the plotly extension. I've tried most of the tips given (increasing timeout, cleaning jlpm cache...) but it doesn't work and I can't find any solution.

**Versions (Windows 10 installation):**

> (base) C:\Users\jralfonso>python --version
> Python 3.6.6 :: Anaconda custom (64-bit)
> 
> (base) C:\Users\jralfonso>jupyter lab --version
> 0.35.3
> 
> (base) C:\Users\jralfonso>ipython
> Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: import plotly
> 
> In [2]: print(plotly.__version__)
> 3.4.0
> 
> In [3]:
> Do you really want to exit ([y]/n)? y
> 
> (base) C:\Users\jralfonso>node --version
> v10.13.0

**yarn-error.log:**

> Arguments: 
> C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\node.exe C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\share\jupyter\lab\staging\yarn.js install
> 
> PATH: 
>   C:\Users\jralfonso\AppData\Local\Continuum\anaconda3;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\Library\usr\bin;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\Library\bin;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\Scripts;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\PostgreSQL\pg96\bin;C:\Program Files\Java\jdk1.8.0_172;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\PostgreSQL\pg96\bin;C:\Program Files\Java\jdk1.8.0_172;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\PostgreSQL\pg96\bin;C:\Program Files\Java\jdk1.8.0_172;C:\WINDOWS\System32;C:\spark;C:\Program Files\Git\cmd;;C:\spark;C:\Program Files\Git\cmd;;C:\spark;C:\Program Files\Git\cmd;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\Scripts\;C:\Users\jralfonso\AppData\Local\Continuum\anaconda3;C:\Program Files\apache-maven-3.5.4\bin;C:\spark\bin;C:\Program Files\Java\jdk1.8.0_172\bin;
> 
> Yarn version: 
>   1.9.4
> 
> Node version: 
>   10.13.0
> 
> Platform: 
>   win32 x64
> 
> Trace: 
>   Error: https://registry.yarnpkg.com/xterm/-/xterm-3.3.0.tgz: ESOCKETTIMEDOUT
>       at ClientRequest.<anonymous> (C:\Users\jralfonso\AppData\Local\Continuum\anaconda3\share\jupyter\lab\staging\yarn.js:138095:19)
>       at Object.onceWrapper (events.js:273:13)
>       at ClientRequest.emit (events.js:182:13)
>       at TLSSocket.emitRequestTimeout (_http_client.js:661:40)
>       at Object.onceWrapper (events.js:273:13)
>       at TLSSocket.emit (events.js:182:13)
>       at TLSSocket.Socket._onTimeout (net.js:449:8)
>       at ontimeout (timers.js:436:11)
>       at tryOnTimeout (timers.js:300:5)
>       at listOnTimeout (timers.js:263:5)
> 
> npm manifest: 
>   {
>       "name": "@jupyterlab/application-top",
>       "version": "0.19.1",
>       "private": true,
>       "scripts": {
>           "build": "webpack",
>           "build:prod": "webpack --config webpack.prod.config.js",
>           "build:prod:stats": "webpack --profile --config webpack.prod.config.js --json > stats.json",
>           "build:stats": "webpack --profile --json > stats.json",
>           "clean": "rimraf build",
>           "prepublishOnly": "npm run build",
>           "watch": "webpack --watch"
>       },
>       "dependencies": {
>           "@jupyterlab/application": "^0.19.1",
>           "@jupyterlab/application-extension": "^0.19.1",
>           "@jupyterlab/apputils": "^0.19.1",
>           "@jupyterlab/apputils-extension": "^0.19.1",
>           "@jupyterlab/attachments": "^0.19.1",
>           "@jupyterlab/cells": "^0.19.1",
>           "@jupyterlab/codeeditor": "^0.19.1",
>           "@jupyterlab/codemirror": "^0.19.1",
>           "@jupyterlab/codemirror-extension": "^0.19.1",
>           "@jupyterlab/completer": "^0.19.1",
>           "@jupyterlab/completer-extension": "^0.19.1",
>           "@jupyterlab/console": "^0.19.1",
>           "@jupyterlab/console-extension": "^0.19.1",
>           "@jupyterlab/coreutils": "^2.2.1",
>           "@jupyterlab/csvviewer": "^0.19.1",
>           "@jupyterlab/csvviewer-extension": "^0.19.1",
>           "@jupyterlab/docmanager": "^0.19.1",
>           "@jupyterlab/docmanager-extension": "^0.19.1",
>           "@jupyterlab/docregistry": "^0.19.1",
>           "@jupyterlab/extensionmanager": "^0.19.1",
>           "@jupyterlab/extensionmanager-extension": "^0.19.1",
>           "@jupyterlab/faq-extension": "^0.19.1",
>           "@jupyterlab/filebrowser": "^0.19.3",
>           "@jupyterlab/filebrowser-extension": "^0.19.2",
>           "@jupyterlab/fileeditor": "^0.19.1",
>           "@jupyterlab/fileeditor-extension": "^0.19.1",
>           "@jupyterlab/help-extension": "^0.19.1",
>           "@jupyterlab/imageviewer": "^0.19.1",
>           "@jupyterlab/imageviewer-extension": "^0.19.1",
>           "@jupyterlab/inspector": "^0.19.1",
>           "@jupyterlab/inspector-extension": "^0.19.1",
>           "@jupyterlab/javascript-extension": "^0.19.1",
>           "@jupyterlab/json-extension": "^0.18.1",
>           "@jupyterlab/launcher": "^0.19.1",
>           "@jupyterlab/launcher-extension": "^0.19.1",
>           "@jupyterlab/mainmenu": "^0.8.1",
>           "@jupyterlab/mainmenu-extension": "^0.8.1",
>           "@jupyterlab/markdownviewer-extension": "^0.19.1",
>           "@jupyterlab/mathjax2": "^0.7.1",
>           "@jupyterlab/mathjax2-extension": "^0.7.1",
>           "@jupyterlab/notebook": "^0.19.2",
>           "@jupyterlab/notebook-extension": "^0.19.1",
>           "@jupyterlab/observables": "^2.1.1",
>           "@jupyterlab/outputarea": "^0.19.1",
>           "@jupyterlab/pdf-extension": "^0.10.1",
>           "@jupyterlab/rendermime": "^0.19.1",
>           "@jupyterlab/rendermime-extension": "^0.13.1",
>           "@jupyterlab/rendermime-interfaces": "^1.2.1",
>           "@jupyterlab/running": "^0.19.1",
>           "@jupyterlab/running-extension": "^0.19.1",
>           "@jupyterlab/services": "^3.2.1",
>           "@jupyterlab/settingeditor": "^0.8.1",
>           "@jupyterlab/settingeditor-extension": "^0.14.1",
>           "@jupyterlab/shortcuts-extension": "^0.19.3",
>           "@jupyterlab/tabmanager-extension": "^0.19.1",
>           "@jupyterlab/terminal": "^0.19.1",
>           "@jupyterlab/terminal-extension": "^0.19.1",
>           "@jupyterlab/theme-dark-extension": "^0.19.1",
>           "@jupyterlab/theme-light-extension": "^0.19.1",
>           "@jupyterlab/tooltip": "^0.19.1",
>           "@jupyterlab/tooltip-extension": "^0.19.1",
>           "@jupyterlab/vdom-extension": "^0.18.1",
>           "@jupyterlab/vega4-extension": "^0.18.1",
>           "@phosphor/algorithm": "^1.1.2",
>           "@phosphor/application": "^1.6.0",
>           "@phosphor/commands": "^1.6.1",
>           "@phosphor/coreutils": "^1.3.0",
>           "@phosphor/datagrid": "^0.1.6",
>           "@phosphor/disposable": "^1.1.2",
>           "@phosphor/domutils": "^1.1.2",
>           "@phosphor/dragdrop": "^1.3.0",
>           "@phosphor/messaging": "^1.2.2",
>           "@phosphor/properties": "^1.1.2",
>           "@phosphor/signaling": "^1.2.2",
>           "@phosphor/virtualdom": "^1.1.2",
>           "@phosphor/widgets": "^1.6.0",
>           "ajv": "~5.1.6",
>           "ansi_up": "^3.0.0",
>           "codemirror": "~5.39.0",
>           "comment-json": "^1.1.3",
>           "es6-promise": "~4.1.1",
>           "marked": "~0.4.0",
>           "moment": "~2.21.0",
>           "path-posix": "~1.0.0",
>           "react": "~16.4.2",
>           "react-dom": "~16.4.2",
>           "react-paginate": "^5.2.3",
>           "sanitize-html": "~1.18.2",
>           "semver": "^5.5.0",
>           "url-parse": "~1.4.3",
>           "xterm": "~3.3.0",
>           "jupyterlab-chart-editor": "file:../extensions/jupyterlab-chart-editor-1.0.0.tgz",
>           "@jupyterlab/plotly-extension": "file:../extensions/jupyterlab-plotly-extension-0.18.2.tgz"
>       },
>       "devDependencies": {
>           "@jupyterlab/buildutils": "^0.11.1",
>           "css-loader": "~0.28.7",
>           "duplicate-package-checker-webpack-plugin": "^3.0.0",
>           "file-loader": "~1.1.11",
>           "fs-extra": "~4.0.2",
>           "glob": "~7.1.2",
>           "handlebars": "~4.0.11",
>           "html-loader": "^0.5.1",
>           "html-webpack-plugin": "~3.2.0",
>           "raw-loader": "~0.5.1",
>           "rimraf": "~2.6.2",
>           "sort-package-json": "~1.7.1",
>           "source-map-loader": "~0.2.1",
>           "style-loader": "~0.21.0",
>           "uglifyjs-webpack-plugin": "~1.2.5",
>           "url-loader": "~1.0.1",
>           "webpack": "~4.12.0",
>           "webpack-cli": "^3.0.3",
>           "webpack-merge": "^4.1.1"
>       },
>       "engines": {
>           "node": ">=6.11.5"
>       },
>       "jupyterlab": {
>           "extensions": {
>               "@jupyterlab/application-extension": "",
>               "@jupyterlab/apputils-extension": "",
>               "@jupyterlab/codemirror-extension": "",
>               "@jupyterlab/completer-extension": "",
>               "@jupyterlab/console-extension": "",
>               "@jupyterlab/csvviewer-extension": "",
>               "@jupyterlab/docmanager-extension": "",
>               "@jupyterlab/extensionmanager-extension": "",
>               "@jupyterlab/faq-extension": "",
>               "@jupyterlab/filebrowser-extension": "",
>               "@jupyterlab/fileeditor-extension": "",
>               "@jupyterlab/help-extension": "",
>               "@jupyterlab/imageviewer-extension": "",
>               "@jupyterlab/inspector-extension": "",
>               "@jupyterlab/launcher-extension": "",
>               "@jupyterlab/mainmenu-extension": "",
>               "@jupyterlab/mathjax2-extension": "",
>               "@jupyterlab/notebook-extension": "",
>               "@jupyterlab/rendermime-extension": "",
>               "@jupyterlab/running-extension": "",
>               "@jupyterlab/settingeditor-extension": "",
>               "@jupyterlab/shortcuts-extension": "",
>               "@jupyterlab/tabmanager-extension": "",
>               "@jupyterlab/terminal-extension": "",
>               "@jupyterlab/theme-dark-extension": "",
>               "@jupyterlab/theme-light-extension": "",
>               "@jupyterlab/tooltip-extension": ""
>           },
>           "mimeExtensions": {
>               "@jupyterlab/javascript-extension": "",
>               "@jupyterlab/json-extension": "",
>               "@jupyterlab/markdownviewer-extension": "",
>               "@jupyterlab/pdf-extension": "",
>               "@jupyterlab/vdom-extension": "",
>               "@jupyterlab/vega4-extension": "",
>               "jupyterlab-chart-editor": "",
>               "@jupyterlab/plotly-extension": ""
>           },
>           "name": "JupyterLab",
>           "buildDir": "./build",
>           "outputDir": "..",
>           "singletonPackages": [
>               "@jupyterlab/application",
>               "@jupyterlab/apputils",
>               "@jupyterlab/console",
>               "@jupyterlab/coreutils",
>               "@jupyterlab/docmanager",
>               "@jupyterlab/extensionmanager",
>               "@jupyterlab/filebrowser",
>               "@jupyterlab/fileeditor",
>               "@jupyterlab/imageviewer",
>               "@jupyterlab/launcher",
>               "@jupyterlab/notebook",
>               "@jupyterlab/rendermime",
>               "@jupyterlab/rendermime-interfaces",
>               "@jupyterlab/services",
>               "@jupyterlab/terminal",
>               "@jupyterlab/tooltip",
>               "@phosphor/coreutils",
>               "@phosphor/widgets"
>           ],
>           "vendor": [
>               "@phosphor/algorithm",
>               "@phosphor/application",
>               "@phosphor/commands",
>               "@phosphor/coreutils",
>               "@phosphor/datagrid",
>               "@phosphor/disposable",
>               "@phosphor/domutils",
>               "@phosphor/dragdrop",
>               "@phosphor/messaging",
>               "@phosphor/properties",
>               "@phosphor/signaling",
>               "@phosphor/virtualdom",
>               "@phosphor/widgets",
>               "ajv",
>               "ansi_up",
>               "codemirror",
>               "comment-json",
>               "es6-promise",
>               "marked",
>               "moment",
>               "path-posix",
>               "react",
>               "react-dom",
>               "react-paginate",
>               "sanitize-html",
>               "semver",
>               "url-parse",
>               "xterm"
>           ],
>           "version": "0.35.3",
>           "linkedPackages": {},
>           "staticDir": "../static"
>       }
>   }
> 
> yarn manifest: 
>   No manifest
> 
> Lockfile: 
>   No lockfile
> 

Sorry if it's pretty obvious, but I don't know what to do. Thanks a lot for your time.

**Comment by jasongrout** [comment]
It does look like connection issues. I googled for the error and found https://github.com/yarnpkg/yarn/issues/5540, which may help.

**Comment by jralfonsog** [comment]
I already tried to increase timeout, but it still gives the same problem (even before the timeout expires). Thanks anyway.

Any other idea?

**Comment by soha-namnabat** [comment]
I face a similar issue. based on  https://github.com/yarnpkg/yarn/issues/5540 we have to modify the .yarnrc file, but where should we change this? I changed .yarnrc in ~/anaconda3/share/jupyter/lab/staging but it seems it doesn't affect anything.

**Comment by aseedb** [comment]
@soha-namnabat I had the same problem. The solution was to do what you didn't do it in the right folder. For me it was:
```
cd  ~anaconda3/lib/python3.7/site-packages/jupyterlab/staging/
echo network-timeout 600000 > .yarnrc
```
To identify the folder where to put .yarnc I looked at the output of 
```
jupyter lab build
```
specifically at this line:
```
[LabBuildApp] > node /Users/bzuber/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install
```

**Comment by aliavni** [comment]
```
yarn config set network-timeout 100000
```

before jupyter lab build solved the issue for me

**Comment by jtpio** [comment]
Closing as the plotly extension can now be installed with `pip` when using JupyterLab 3+:

```
pip install plotly
```

Feel free to open an issue on the plotly repo if you are having problems installing the plotly extension: https://github.com/plotly/plotly.py

Thanks!
