### ISSUE TITLE
Follow up: Unpin pytest-check-links

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#5946]
In #5846 pytest-check-links were pinned. This issue tracks the TODO of unpinning this after a new release of that package.

**Comment by jtpio** [comment]
Thanks @vidartf for opening this follow-up issue.

Looks like this can now be closed since the pin has now been removed:

https://github.com/jupyterlab/jupyterlab/blob/5f4e3fabf33bed101e41708021a245ca59410511/setup.cfg#L68-L69
