### ISSUE TITLE
Cells stop running

### ISSUE THREAD

**Issue by victorkrook** [jupyterlab/jupyterlab#5948]
Whenever I program with inputs every now and then Jupyterlab stop reacting to my cells and the cells stop running, which means that I have to restart the kernel and run all cells again. Sometimes this happens after only a few cells ran which makes it very difficult to run big piles of codes. Especially since I'm very new to this and want to run cells quite often to make sure my code is correct.

Is this normal?

Victor

**Comment by ian-r-rose** [comment]
Hi @victorkrook, it would be helpful if you could provide a sequence of commands that show this behavior. Does it seem like the kernel is hanging? Is it possible there is an infinite loop somewhere?

**Comment by jasongrout** [comment]
It's possible your kernel is crashing for some reason, and the confusing thing is that (unlike the classic notebook), jlab doesn't currently notify you when the kernel crashes.

**Comment by kykrueger** [comment]
Even if the kernel is crashing, would like to see it provide a stack trace. How can we make this happen. 

I've had various scripts that won't run in jupyter cells, but work just fine elsewhere.

**Comment by jasongrout** [comment]
> It's possible your kernel is crashing for some reason, and the confusing thing is that (unlike the classic notebook), jlab doesn't currently notify you when the kernel crashes.

JLab does this now.

**Comment by jasongrout** [comment]
Closing since the author did not follow up. Please comment here if you'd like to continue the discussion.
