### ISSUE TITLE
Mathjax output box is too wide

### ISSUE THREAD

**Issue by AlbertHilb** [jupyterlab/jupyterlab#5949]
Mathjax output box in console or notebook cells is too wide.

![screenshot_2019-02-06](https://user-images.githubusercontent.com/1220427/52311820-a28e7380-29a8-11e9-8a35-775ba4b9cece.png)

Mathjax CSS sets the width of `Mathjax_Display` class `div`s to `100%`. In the [mathjax2 package][1], we add padding to those `div`s. The result is they exceed their parent node width, forcing horizontal scrollbar to appear.

To fix this issue we can:

1. avoid adding padding or
1. set `box-sizing` CSS property to `border-box`

I have a little preference for the first solution because, adopting it, math is displayed left aligned with the input source.

What do you think?

[1]: https://github.com/jupyterlab/jupyterlab/blob/233696dce5c6ed694124fb858740d82377c1c874/packages/mathjax2/style/index.css#L14

**Comment by jasongrout** [comment]
See also https://github.com/jupyterlab/jupyterlab/pull/5547 and https://github.com/jupyterlab/jupyterlab/issues/5276. What do you think about the issues brought up in those issues?

**Comment by AlbertHilb** [comment]
Hi @jasongrout.

Interesting! Those confirm my idea that the right solution is the first one.

This is LaTeX rendering sample from #5547:

![LaTeXSample](https://user-images.githubusercontent.com/7255416/47605251-045a3d00-d9b9-11e8-9c4f-a5dd1f3d54d3.png)

This, how it appears after fix 1 is applied:

![immagine](https://user-images.githubusercontent.com/1220427/52375774-c01f1400-2a60-11e9-8ac3-fb0fe2b2db7c.png)

As you can see inline math is left unchanged, whereas display math gains left alignment.

This happens because [troublesome extra padding][1] is added only to Mathjax display math containers.


[1]: https://github.com/jupyterlab/jupyterlab/blob/233696dce5c6ed694124fb858740d82377c1c874/packages/mathjax2/style/index.css#L14
