### ISSUE TITLE
Allow rendermime extension to access the current session?

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#5954]
Follow up from https://github.com/jupyterlab/jupyterlab/pull/5670#discussion_r254525846

Does it make sense to allow rendermime extensions to access the current session? In this instance, the vdom-extension uses the current session to send comm messages to the kernel.

**Comment by jasongrout** [comment]
I think no since it increases the dependencies for rendermime extensions.

**Comment by gnestor** [comment]
Ya it's fair to just convert vdom-extension to a regular extension because it's scope has changed.

**Comment by jasongrout** [comment]
In particular, it would mean that rendermime extensions would need to be upgraded when there was a services upgrade, where now there is no such need.

**Comment by gnestor** [comment]
Totally
