### ISSUE TITLE
vega-extension leads to frozen frontend

### ISSUE THREAD

**Issue by jakevdp** [jupyterlab/jupyterlab#5955]
If you run the following code in JupyterLab, it results in your frontend hanging:
```python
class VegaLite:
    def __init__(self, spec):
        self.spec = spec
    def _repr_mimebundle_(self, include, exclude):
        return {'application/vnd.vegalite.v2+json': spec}, {}
  
VegaLite({
 'data': {'name': 'no-data'},
 'mark': 'bar',
 'encoding': {
   'row': {'field': 'y', 'type': 'ordinal'},
   'x': {'field': 'x', 'type': 'quantitative'}
 },
})
```
First reported in https://github.com/altair-viz/altair/issues/1323

Tested in juptyerlab 0.35.3

**Comment by saulshanabrook** [comment]
@jakevdp Thanks for the report!

**Comment by stonebig** [comment]
will there be a new release of Jupyterlab this year, so we can benefit of latest and greatest altair ?

**Comment by jasongrout** [comment]
As of now (and fixing the NameError in the sample above), things seem to work in JupyterLab 2.1.4. Vegalite v2 spec does nothing, while changing v2 to v3 and v4 show a line. So I think this is fixed now. Please comment if this is still an issue.
