### ISSUE TITLE
Include specific versions of jlab packages in the yarn resolution key of package.json

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5958]
Especially with prerelease js packages, npm (and hence yarn) can end up with multiple versions of a package since the npm `^x.y.z` does not include any packages on the `next` tag. We're seeing this in ipywidgets, where the base ipywidgets package can work with a number of jlab versions (including the prerelease version, but the yarn resolution algorithm doesn't count that prerelease when you have such a large range of acceptable versions), however in a prerelease we want to certainly pin the version to the prerelease js version.

So it may be useful to pin the versions of the js packages using the yarn `resolution` key in the staging (and dev-mode) package.json to be the exact version we want.

As a simplified example, the base widget package has a dependency on services `1||2||3||4.alpha.0`, but that means the yarn resolution algorithm picks version 3 instead of version 4.alpha.0, since 3 is the `latest` tagged release.

**Comment by blink1073** [comment]
We did this in https://github.com/jupyterlab/jupyterlab/pull/6938
