### ISSUE TITLE
0.35.4 : no "Quit" button

### ISSUE THREAD

**Issue by vykozlov** [jupyterlab/jupyterlab#5965]
In https://github.com/jupyterlab/jupyterlab/pull/5226 the "Quit" button was introduced.

I install jupyterlab in my docker as
RUN pip install --no-cache-dir jupyterlab && \  
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

I can access jupyter, it says ver. **0.35.4** but there is no "Quit" button in the file menu.

**Comment by jasongrout** [comment]
Did you check the quit_button setting mentioned in the PR? What if you set it to true on the command line: `jupyter lab --LabApp.quit_button=True`

**Comment by vykozlov** [comment]
Indeed, seems to work. At first, since I am in the container, I forgot about '--allow-root', but then it works.
In the classical Jupyter notebook it is available by default, probably this is why I got puzzled.

**Comment by jasongrout** [comment]
Perhaps there is some config file somewhere that is setting it to False. Setting it on the command line would take precedence over a config file setting.
