### ISSUE TITLE
No logout button

### ISSUE THREAD

**Issue by vykozlov** [jupyterlab/jupyterlab#5966]
It is sort of re-opening of "No logout button #4414", because there is no "Logout" button:

ver. 0.35.4, installed as pip install jupyterlab in Docker container.

 #5226 introduced the "Quit" button, i.e. to shutdown jupyterlab, but what is asked in #4414 and here, is "Logout" button.

It would be really nice to have it in the jupyterlab core.

**Comment by jasongrout** [comment]
Thanks for making the distinction. I think you're right. The current Quit button seems to call `/shutdown`: https://github.com/jupyterlab/jupyterlab/blob/a99cfda0466fd6cf15a77b434e66811c1ec2c53c/packages/mainmenu-extension/src/index.ts#L385 https://github.com/jupyter/notebook/blob/cf1b7b36284dfff8ae55004d9e64789f79e842b5/notebook/notebookapp.py#L314 , but the logout button called `/logout`: https://github.com/jupyter/notebook/blob/cf1b7b36284dfff8ae55004d9e64789f79e842b5/notebook/notebookapp.py#L298

**Comment by jasongrout** [comment]
Some more references about the login button in classic notebook:

Here is the html fragment for it: https://github.com/jupyter/notebook/blob/46a887f6e0ecf50f3af5ecadaa05a6ac34675fbb/notebook/templates/page.html#L137-L147

Here is a related template for logged out users? https://github.com/jupyter/notebook/blob/b8b66332e2023e83d2ee04f83d8814f567e01a4e/notebook/templates/logout.html

Here is a reference in the main.js: https://github.com/jupyter/notebook/blob/b8b66332e2023e83d2ee04f83d8814f567e01a4e/notebook/static/terminal/js/main.js#L32-L33

There are lots of references to 'login' or 'logout' in the notebook app: https://github.com/jupyter/notebook/blob/cf1b7b36284dfff8ae55004d9e64789f79e842b5/notebook/notebookapp.py

**Comment by vykozlov** [comment]
Do I understand right that "logout" will come in 1.0.x? What would be the timeline for the release?

**Comment by jasongrout** [comment]
I put it as a 1.0 issue since it is a backwards compatibility concern. We don't have a specific timeline. I imagine "soon" (order of weeks/month/two months?), and the issue/PR queue is here: https://github.com/jupyterlab/jupyterlab/milestone/2

**Comment by Madhu94** [comment]
I'd like to work on this.

**Comment by Madhu94** [comment]
Ping @zgqallen - Would you like to take a shot at merging [jupyterlab-logout](https://github.com/zgqallen/jupyterlab-logout) into jupyterlab itself ?

**Comment by Madhu94** [comment]
@zgqallen, I'm picking this up, you can ping here if you feel like  you want to try contributing.

**Comment by byouness** [comment]
Hello all,
As a workaround, if your JupyterLab is running under `ip:port/lab`, open  `ip:port/tree` and logout using the jupyter notebook Logout button.
