### ISSUE TITLE
Anchor <a> elements don't show pointer cursor on hover

### ISSUE THREAD

**Issue by mbektasbbg** [jupyterlab/jupyterlab#5970]
On mouse hover, anchor elements shows `default` arrow cursor instead of `pointer`. Seems to be caused by blueprint resetting css.

**To Reproduce**
1. Create a markdown cell with a link on it `[test](http://google.com)`
2. Shift + Enter
3. Hover on link `test`

**Comment by jasongrout** [comment]
Thanks for pointing out this regression!

**Comment by jasongrout** [comment]
CC @gnestor

**Comment by gnestor** [comment]
Good catch @mbektasbbg! This was caused by us trying to (over) override blueprint's global styles. I'll submit a PR for this and https://github.com/jupyterlab/jupyterlab/issues/5971.

**Comment by gnestor** [comment]
Thanks for the reminder @ian-r-rose. I had already fixed this but forgot to submit a PR!
