### ISSUE TITLE
ToolbarButton with icon doesn't show icon

### ISSUE THREAD

**Issue by mbektasbbg** [jupyterlab/jupyterlab#5971]
ToolbarButtons with an icon `ToolbarButton({iconClassName:'name'})` don't show the icon. Seems to be caused by additional DOM element (`<span class="bp3-button-text"></span>`) introduced by blueprint which wraps icon and label `<span>`s. 

**To Reproduce**
create a toolbar button using
`
let button = new ToolbarButton({ iconClassName: 'iconClassName', label: 'label'});
toolbar.addItem(name, button);
`

**Comment by jasongrout** [comment]
Thanks for pointing out this regression.

**Comment by jasongrout** [comment]
CC @gnestor

**Comment by gnestor** [comment]
@mbektasbbg I can't reproduce this one. The notebook and many other extensions are creating ToolbarButtons this way and it's working on master. For example: https://github.com/jupyterlab/jupyterlab/blob/master/packages/htmlviewer/src/index.tsx#L94-L98

I tried adding a label property to that example and it appears to work:

![image](https://user-images.githubusercontent.com/512354/52819263-b0ee2680-305d-11e9-8177-3be0a013a914.png)

**Comment by mbektasbbg** [comment]
@gnestor Thank you. It turns out classes `jp-Icon jp-Icon-16` are required in `iconClassName` for the icons to properly size in new jupyterlab. Adding those to our ToolbarButtons fixed the problem!

**Comment by gnestor** [comment]
This brings up a good point. @jasongrout Should we require users to include `jp-Icon jp-Icon-16` in `iconClassName or should the `ToolbarButton` widget include those be default?
