### ISSUE TITLE
odd behaviour on Ubuntu vs. OSX

### ISSUE THREAD

**Issue by smartinsightsfromdata** [jupyterlab/jupyterlab#5972]
I have the same configuration in my  macbook OSX 10.14.3 and Ubuntu 18.04 laptops.
ipykernel                 5.1.0
ipyparallel               6.2.3
ipython                   7.2.0
ipython-autotime          0.1
ipython-genutils          0.2.0               
ipywidgets                7.4.2
jupyter                   1.0.0
jupyter-client            5.2.4
jupyter-console           6.0.0
jupyter-core              4.4.0
jupyterlab                0.35.4
jupyterlab-server         0.2.0
widgetsnbextension        3.4.2

I execute in Jupyterlab the same code for both.  The code is saving a ~84MB file in a . folder.

In OSX I can see what is happening directly  in the Jupyterlab notebook (under the cell): 
```
downloading aclImdb_v1.tar.gz
aclImdb_v1.tar.gz: 100%|██████████| 84.1M/84.1M [00:54<00:00, 1.54MB/s]
```
The latter is in pink (as for warnings etc.).

In Ubuntu I do not see anything in the notebook (but I see `Saving file at etc.` in the console).

My question is `why`?
Do I have a different setting in the two laptops (I did check the settings and they seem identical).

This is the code to reproduce:
```
import torch
from torchtext import data, datasets
TEXT = data.Field(tokenize='spacy')
LABEL = data.LabelField(dtype=torch.float)
train_data, test_data = datasets.IMDB.splits(TEXT, LABEL)
```

As noted above, in Ubuntu I see nothing, in OSX I see the message below in the actual notebook (so I understand something is happening).

What am I missing?

**Comment by jasongrout** [comment]
Interesting. Good question! (I don't know!)

**Comment by danieltomasz** [comment]
The OSX communicate looks like it was done with ` tqdm` installed (https://github.com/tqdm/tqdm). Do you have it installed on OSX or Ubuntu?
