### ISSUE TITLE
Importing workspaces shouldn't need base_url set

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/jupyterlab#5977]
Importing workspaces requires base_url to be set, with something like:

https://github.com/fperez/eclib/blob/f2ad849c585e71ddb16d0520cc00416bac6b00e6/binder/start#L4

This causes problems when running on JupyterHub.

1. Often, the same environment is built for many users. This means there would be one virtualenv or conda env (one sys.prefix) with many individual users with their own base_url. These users might not have persistent ${HOME} either. Thus, one workspace file might need to work for 'em all
2. base_url is not guaranteed to be the same across multiple logins for the same user - they can be changed pretty easily. If using named servers on JupyterHub, they *will* change whenever the user starts a new name.
3. When building containers for use, you will do a 'build' once - when you don't know the base_url and then run it each time for many users. This breaks that.

In general, base_url should be considered a 'runtime parameter' while (in my mind) workspaces are a build time parameter, and mixing runtime parameters in build places breaks JupyterHub.

**Comment by yuvipanda** [comment]
This also breaks all repo2docker based builds, like https://github.com/jupyter/repo2docker/issues/578

**Comment by bollwyvl** [comment]
Indeed. I'd like to adopt workspaces, but the fact that they aren't easy to
check in with a project and easily use on an arbitrary machine makes it
hard.

I'd even like a mime renderer for them so that a kernel can propose a
layout, potentially in a new browser tab: this would be great for
presentations.

**Comment by ian-r-rose** [comment]
@afshin Can you weigh in on how feasible it would be to remove the `base_url` from the workspace ID and have it just rely on the workspace name?

**Comment by yuvipanda** [comment]
You can also have base_url be interpolated at *runtime* in your client or server code - this is what jupyter-server-proxy does, for example. '{base_url}' is replaced by the actual base_url at runtime...

**Comment by ian-r-rose** [comment]
We have `base_url` available in the lab client code (it is used pretty prolifically to construct requests to the server). @afshin included it as part of the workspace for a reason that I can no longer remember...
