### ISSUE TITLE
Cmd-Arrow and Cmd A doesn't work in the text editor

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#5978]
In 1.0a1 and 0.35.4, the following shortcuts do nothing in the file text editor:

* cmd A (should select all)
* cmd left arrow (should go to beginning of line)
* cmd right arrow (should go to end of line)
* cmd down arrow (should go to end of codemirror)
* cmd up arrow (should go to top of codemirror)

All of these work in a notebook codemirror input.

**Comment by ian-r-rose** [comment]
This may be platform dependent. I, for instance, don't have cmd, and I am not sure I agree with all of those expectations:
* Ctrl+A *does* select all for me.
* Ctrl+left arrow goes to the next word. This conforms to my expectations (and matches the github text editor).
* Ctrl+right arrow goes to the previous word. This conforms to my expectations (and matches the github text editor).
* Ctrl+down arrow goes down one line. I'm not sure I expect it to go to the end of the editor.
* Ctrl+up arrow goes up one line. I'm not sure I expect it to go to the beginning of the editor.

**Comment by jasongrout** [comment]
> This may be platform dependent

Very likely.



> I, for instance, don't have cmd, and I am not sure I agree with all of those expectations:

Sure. However, things *do* work like this (and exactly how I expect) in a notebook code cell, so I expect that if things work like you expect in a notebook code cell right now, you won't notice if we fix the text editor on a mac.

**Comment by ian-r-rose** [comment]
> Sure. However, things _do_ work like this (and exactly how I expect) in a notebook code cell, so I expect that if things work like you expect in a notebook code cell right now, you won't notice if we fix the text editor on a mac.

That's fair. For what it's worth, I can't find any differences between notebook cells and text editors, either in the classic notebook or with lab. This is using Chrome and Firefox in ChromeOS and Linux, respectively.

**Comment by jasongrout** [comment]
This code may be relevant: https://github.com/jupyterlab/jupyterlab/blob/a6d293461ae90d4b27b8799ec81cf1918cc74e49/packages/codemirror/src/factory.ts#L18-L38

**Comment by jasongrout** [comment]
Actually, it looks like they just don't work when the text editor keymap is set to emacs. They work fine in the default and Sublime text editor keymaps.

Closing as resolved, then.
