### ISSUE TITLE
Status Bar should be optional and toggled from menu or similar

### ISSUE THREAD

**Issue by mbektasbbg** [jupyterlab/jupyterlab#5982]
There is no way to hide the status bar to save on screen real estate. A menu item can be added to toggle it.

**Comment by jasongrout** [comment]
Sounds good. I think it makes sense to have a menu entry in the view menu to toggle this status.

I can imagine that a good way to tackle this is to

1. Make a new command to do this, similar to the "Show Left Sidebar" command at https://github.com/jupyterlab/jupyterlab/blob/a496aad7e2001a36f004737dbb86922685ff6280/packages/application-extension/src/index.tsx#L463-L478

2. Add it to the menu, like the notebook adds items to the view menu in https://github.com/jupyterlab/jupyterlab/blob/930420a55914f349fe1fa6c0b7c068d20a257a5c/packages/notebook-extension/src/index.ts#L1975

3. Make it a setting that is saved for the status bar extension (a little more complicated, but basically adding a new schema file for the status bar, and then putting logic into the command to change the setting when the status bar is toggled).

**Comment by jasongrout** [comment]
Tagging as a good first issue - to do everything above is probably an advanced good first issue.
