### ISSUE TITLE
Can't edit and view HTML file side-by-side

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#5987]
![](http://g.recordit.co/AZYaDH5wQM.gif)

As you can see, every time a key is pressed, the HTMLViewer pane is focused.

To reproduce:

1. Open an HTML file with Editor and HTMLViewer
2. Drag them so that they're side-by-side
3. Try to edit the file

cc @ian-r-rose

**Comment by ian-r-rose** [comment]
It looks like we are not done yet with focus issues for `navigateToCurrentDirectory`. When it is off, HTML editing works as expected.

**Comment by gnestor** [comment]
Nooo! I will look into this now...
