### ISSUE TITLE
deleting a tab in Notebook Code Cell doesn't match the `tabSize`

### ISSUE THREAD

**Issue by johnnychen94** [jupyterlab/jupyterlab#5992]
**Describe the bug**
I'm a python user, and I override the tabSize of my notebook code cell: 
```json
{
    "codeCellConfig":{
        "tabSize": 2 
    }
}
```
`tabSize=2` is the default code style for tensorflow.

:) when I hit TAB, two spaces are inserted
:( when I hit two TABs, and hit DELETE/BACKSPACE, four instead of two spaces are deleted. This makes editing following code samples _not so smooth_:

say we want to write following codes
```python
# tabSize = 2
def greeting(namelist): 
  for name in namelist:
    print("Hello, ", name)
  print("hello all")
```
it becomes weird at the end of `print("Hello, ", name)`. **4** spaces is inserted by hitting ENTER, and _naturally_ we only hit DELETE **once**. However, with `tabSize=2`, we need to either
1. hit DELETE once **and hit TAB once**, or,
2. hit `Cmd-[` (shortcut for activate previous tab) -- not so commonly used in other editor
which makes coding not so smooth.

**Expected behavior**
I can think of two solution:

1. when hit DELETE, the spaces deleted shall check tabSize, or,
2. when hit ENTER, auto-indent shall check tabSize

**Desktop:**

- OS: Mac OS High Sierra Version 10.13.6
- Browse:  Chrome 71.0.3578.98
- JupyterLab 0.35.4

**Comment by ian-r-rose** [comment]
Thanks for the report @johnnychen94. The problem appears to be that we are indenting using the CodeMirror option`'indentUnit`, but we are deleting using the CodeMirror option `tabSize`. I think this should be fixable by changing this line to use `'indentUnit'`:
https://github.com/jupyterlab/jupyterlab/blob/bdd751bc34b1033036d8fbb7e4b98e3fcdfba60b/packages/codemirror/src/editor.ts#L1367

Marking as a good issue for a new contributor. Just making the above change would fix this issue, though we may want to do some additional checks to make sure this also works with tab indentation.

**Comment by MilanMisak** [comment]
Hi, I've created a pull request with a fix. Please review. Thanks
