### ISSUE TITLE
Duplicate file puts 'Copy1' suffix on the first '.' in the filename.

### ISSUE THREAD

**Issue by heavelock** [jupyterlab/jupyterlab#5999]
Hello!

**Describe the bug**
The bug is pretty simple and cosmetic. The option `duplicate` used on a file that contains more than one '.' puts a suffix such as 'Copy1' before first dot. 

**To Reproduce**

1. Have a file named `filename.with.dots.png`
2. Click on 'Duplicate'
3. It produces file named `filename-Copy1.with.dots.png`

**Expected behavior**
The new name should be like  `filename.with.dots-Copy1.png`

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 16.04
- Browser Opera 58.0.3135.59
- JupyterLab 0.35.4 py37_0  conda-forge

**Comment by telamonian** [comment]
I'm pretty sure this one is going to be a "won't fix". There are some standard file formats, such as zipped tarballs (eg `foo.tar.gz`), that use multiple dotted extensions. Shoehorning a `-Copy1` in after the `.tar` but before the `.gz` would likely break such files with respect to many scripts and programs.

On the other hand, it might not be a terrible idea to open a dialogue window when a user duplicates a file that lets them adjust the name of the copy. That's already the standard behavior for some IDEs when you copy a file, such as Intellij:

![image](https://user-images.githubusercontent.com/2263641/52961470-003b9c00-3369-11e9-8f17-86da5ed1e8ad.png)

**Comment by jasongrout** [comment]
> I'm pretty sure this one is going to be a "won't fix". There are some standard file formats, such as zipped tarballs (eg `foo.tar.gz`), that use multiple dotted extensions. Shoehorning a `-Copy1` in after the `.tar` but before the `.gz` would likely break such files with respect to many scripts and programs.

I agree that the behavior is good as described, for exactly this reason.

FYI, macOS breaks the extension. Making a file `del.tar.gz`, and then `Dupicate` in Finder immediately gives a copy at `del.tar copy.gz`.

I think the idea is that the copy should generally be useful immediately, but you can rename in a second step if you need a different name.

**Comment by jasongrout** [comment]
Closing as answered. Thanks!
