### ISSUE TITLE
Look into SauceLabs for Cross-Browser Testing

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#60]
https://saucelabs.com/
https://docs.travis-ci.com/user/sauce-connect/

**Comment by blink1073** [comment]
ping @parente

**Comment by parente** [comment]
We've been using it successfully over in https://github.com/jupyter-incubator/dashboards for a while.

* addons in travis: https://github.com/jupyter-incubator/dashboards/blob/master/.travis.yml
* smoke tests: https://github.com/jupyter-incubator/dashboards/tree/master/system-test
* dockerization of the environment in which the tests run on travis: https://github.com/jupyter-incubator/dashboards/blob/master/Makefile#L143

I think that's all the bits. Been a while and it's a bit messy with the make stuff in there. If you need more info, let me know.

**Comment by blink1073** [comment]
Thanks, @parente, that is a great reference for us.

**Comment by blink1073** [comment]
Closing in favor of our current `puppeteer` approach.
