### ISSUE TITLE
Close Other Tabs Behaviour

### ISSUE THREAD

**Issue by agoose77** [jupyterlab/jupyterlab#6008]
Currently, close-other-tabs closes _all_ tabs but the current tab, across all panels. I think this would better if it only closed those "other tabs" in the same panel. 
Below is a GIF of the current (undesirable) behaviour, which differs between close-tabs-to-right and close-other-tabs.

![Example of current right click behaviour](https://files.gitter.im/jupyterlab/jupyterlab/BRrW/Peek-2019-02-18-10-29.gif)

See https://github.com/jupyterlab/jupyterlab/pull/4677 which implemented this feature.

**Comment by agoose77** [comment]
Also, whilst we're at it, with Markdown previews, selecting close-other-tabs behaves inconsistently:
1. If only a markdown preview of the document is open (the source is not open in another tab), then close-other-tabs doesn't work at all.
1. If a markdown preview AND a document source is open, it leaves open the source even if you launched the command from the preview.
![peek 2019-02-21 17-14](https://user-images.githubusercontent.com/1248413/53188006-52482000-35fc-11e9-9a24-fe4f2f8bc5aa.gif)

**Comment by jtpio** [comment]
Similar to https://github.com/jupyterlab/jupyterlab/issues/5915?

It looks like when two different widgets for the same document are open (markdown preview and markdown source), one of them will be the default and the commands close-other-tabs or close-right-tabs will be acting on that default widget.

**Comment by tgeorgeux** [comment]
I agree that it doesn't seem super intuitive to close all the tabs. I also think it's a bit tough to decide on this without a bit more data. What would you think about the behavior of that command acting as it does when there is only one 'pane' in the 'main work area' and when there are multiple 'panes' in the 'main work area' it gives a sub-menu with options:
![option](https://user-images.githubusercontent.com/22109376/53846461-da65e800-3f61-11e9-82a7-c5b86bb82597.png)

**Comment by agoose77** [comment]
I know that some people don't like the idea of contextual operations, but in this case I would be happy with that behaviour :). One thing I would add is that there are lots of menus where we list several variants of a command at the same menu level, rather than using a sub-menu (e.g. "run all cells", "run all above current ..."). It might need a wider design decision on that front.

Personally, I don't see the use case for closing all-but-one window, yet that might just be me!

**Comment by ellisonbg** [comment]
I agree that this is confusing. I don't see any way to resolve this without having two separate menu items, either in a submenu, or two adjacent top-level menu items (maybe grouped). Having nested context menus is a bit painful?

**Comment by jasongrout** [comment]
-1 on submenus in the context menu if we can avoid it

I see the point in closing all tabs in all panes, but perhaps that is uncommon enough that it could be a menu item in the Tabs menu? I think closing the other tabs in a panel is probably way more common.

Or I'd probably use "Close all tabs in this panel" even more - I often drag some helpful things to the side of a panel to look at things side-by-side, but then want to just get rid of the entire side panel when I'm done. Clicking each tab's close icon is tedious. Closing other tabs would do it in two clicks, which is better.

**Comment by ellisonbg** [comment]
At a minimum, we should change the text of the current action to be unambiguous: "Close All Other Tabs"

If we want to introduce a new menu item for the "Close All Tabs in this Panel" we could consider that.

However in talking to @tgeorgeux on a call, we felt like we really don't have any good data about which of these actions (or both) is worth exposing to all users (someone could build an extension to add this). The usually way of resolving those questions would be to follow up with usability tests.

**Comment by ellisonbg** [comment]
Another point - not all users are going to understand what we mean by a panel :-)

**Comment by tgeorgeux** [comment]
https://www.figma.com/proto/SW6XIQEjWdtIjzxxZDWc8y2V/5698?node-id=3%3A51&viewport=774%2C-237%2C0.386558&scaling=scale-down

There's a simple prototype of what Brian and I spoke about this morning. I'm going to open a further issue to how we'll treat the 'cell tools' sidebar down the road. Below are the screenshots from the prototype for anybody who's having trouble loading the above:
![5698 - 1](https://user-images.githubusercontent.com/22109376/53911076-4ef46180-400a-11e9-91b0-183eb10543b0.png)
![5698 - 2](https://user-images.githubusercontent.com/22109376/53911079-5156bb80-400a-11e9-9354-4a46ea4a0996.png)

**Comment by jasongrout** [comment]
> Another point - not all users are going to understand what we mean by a panel :-)

They will after they click on it! :(

**Comment by jasongrout** [comment]
> There's a simple prototype of what Brian and I spoke about this morning.

@tgeorgeux - I think you meant to post this comment on another PR, https://github.com/jupyterlab/jupyterlab/pull/5968 ?

**Comment by tgeorgeux** [comment]
Yep, whoops. This is what happens when you have too many tabs open, and too many conversations running concurrently.

**Comment by tgeorgeux** [comment]
What if for 1.0 we just have two actions that are, "Close other tabs in this panel" and "Close all other tabs."

We can merge this and iterate further in 1.1 or 2.0

**Comment by jasongrout** [comment]
FYI, vs code calls them "groups" instead of "panels"

**Comment by jasongrout** [comment]
I opened #6482 with the minimal change (renaming the existing item) so we can bump this to 1.1

**Comment by agoose77** [comment]
Thanks @jasongrout, it's an improvement :)

**Comment by agoose77** [comment]
#6482 fixes one of these issues, and I think we can reopen this if anyone else finds issue.
