### ISSUE TITLE
Jupyter Core Meeting Agenda

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#6014]
I wanted to open this issue to track things related to JupyterLab that might be useful to talk about at the core Jupyter meeting coming up in a few weeks. Feel free to edit this or comment with your own. This would be anything that spans the Jupyter communities or just would be useful to discuss when most of the JupyterLab team is in person.

* Should we open a discourse for JupyterLab? Often I (Saul) figure out how to do something in JupyterLab, but I don't feel like putting in a PR to the docs and trying to think about where it should live. However, it would be nice to record it so other people can look at it. Often, we use issues for this sort of thing. However, the Binder project uses discourse, and I recently [added a tip to their discourse](https://discourse.jupyter.org/t/collaborating-on-one-binder-instance/407/2). I found this more pleasant than opening an issue. Discourse has a lot of small nice things that make discussions like this more fun than on github (threading, summarization, splitting topics). So I would like to hear from the Binder team about their experience using it and see what others think about using it for JupyterLab.

**Comment by jasongrout** [comment]
+1 to talking about Discourse. I was impressed with @willingc's comments about Discourse. I got the impression it is more friendly and approachable than issues or mailing lists. I'd like to try it out.

**Comment by jasongrout** [comment]
Does discourse have threading? I thought the whole point was a flat forum.

**Comment by saulshanabrook** [comment]
> Does discourse have threading? I thought the whole point was a flat forum.


I guess not exactly? But [kind of](https://meta.discourse.org/t/threaded-vs-flat-discourses-way-of-handling-responses-is-genius-but-i-have-one-small-suggestion/4053):

> Discourse uses a flat display, because a threaded display is a tree, and trees cannot be displayed on a screen in a “usable” manner. On the other hand, Discourse allows replies to earlier posts. It makes it very convenient to see the immediate parent of a reply, and even to navigate up the path of parents in case of replies to replies. That UI design is absolutely phantastic. I have talked to a number of died-in-the-wool thread-view lovers, and they had to grudgingly admit that Discourse is good. There is just one thing that they all asked for, and it is exactly the thing that came to my mind when I first looked at Discours

**Comment by saulshanabrook** [comment]
Should I ["Pin"](https://help.github.com/en/articles/pinning-an-issue-to-your-repository) this issue?

**Comment by jasongrout** [comment]
Sure, let's try it out.

**Comment by willingc** [comment]
I can do a brief demo and talk to pros/cons at the meeting too.

**Comment by BoPeng** [comment]
I will certainly appreciate it if anyone can speak up and draw some attention to this [transient display data PR](https://github.com/jupyter/jupyter_client/pull/378) and get some feed back. @jasongrout is one of the reviewers of the PR and @rgbkrk might also be there.

**Comment by jasongrout** [comment]
@BoPeng - thanks for the ping on this. I think this is an excellent time to wrap up discussion on a few open PRs about the protocol, including this one, make a decision, and move forward.

**Comment by BoPeng** [comment]
@jasongrout Thanks. I will make sure to release a version of [transient-display-data](https://github.com/vatlab/transient-display-data) and [jupyterlab-sos](https://github.com/vatlab/jupyterlab-sos) for JupyterLab 1.0.0 alpha, and update the README and the PR before the meeting so that you can give a live demo if needed.

**Comment by BoPeng** [comment]
@jasongrout As promised, I have released a jupyterlab extension [transient-display-data](https://github.com/vatlab/transient-display-data) for JupyterLab 1.0.0 alpha3 that sends all `transient_display_data` to the console panel of notebooks. I have also released a new version of [jupyterlab-sos](https://github.com/vatlab/jupyterlab-sos) to make use of this feature. I have also [updated the PR](https://github.com/jupyter/jupyter_client/pull/378) with a link to [test these features on our live server](http://128.135.144.117:8000/hub/user-redirect/lab) directly (e.g. execute a workflow with progress information displayed in console panel). I believe `transient-display-data` is a useful and straightforward addition to Jupyter and I count on you to convince other members of the Jupyter team to accept it. :smile:

**Comment by ellisonbg** [comment]
I would love to spend a good amount of time on real time collaboration, in particular understanding model design, and how they will integrate with the views. 

Also, the large notebook performance rendering issues came up again this last week.
