### ISSUE TITLE
Readthedocs not building. 

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#6019]
The docs on readthedocs have not been triggered for a couple of month. The webhook seem to have been remove (there was also a change of API on GH/RTD in the meantime). So it was hard to know whether this deactivation was on purpose or not. 

The docs triggering is broken on most of our projects (IPython, Jupyterhub, ipywidgets...), so I would suggest for anyone reading this to head to RTD.org, and pick a couple of project they have access to to see if they are building. 

Some more info on how to setup the webhook now: https://docs.readthedocs.io/en/latest/webhooks.html

**Comment by jasongrout** [comment]
Thanks for pointing this out. And thanks to whoever fixed this!

<img width="827" alt="screen shot 2019-02-22 at 8 16 52 am" src="https://user-images.githubusercontent.com/192614/53255340-48650200-367a-11e9-89f0-5ab2ef13ec45.png">

**Comment by Carreau** [comment]
Probably me. I did a couple of repos, but there are probably many left.
