### ISSUE TITLE
Visual regressions in master

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#6023]
@ellisonbg Mentioned a few visual regressions on master compared to the last release:

* Docker panel went from grey to right
* Slide handles between main area also changed color

We should compare master to the last release to track these down visually.

**Comment by ellisonbg** [comment]
@saulshanabrook I just tested master and everything looks fine:

![screen shot 2019-02-24 at 8 50 52 pm](https://user-images.githubusercontent.com/27600/53314979-fb4d7f80-3875-11e9-916d-bae9f8aa8dbe.png)

We were seeing this on the rich context work - is there a chance here is a build problem on that side. How recent of master are you working on? Do you need to rebase? Is there conflicting styles on that work?

**Comment by saulshanabrook** [comment]
@ellisonbg Some of the commenting work used bootstrap, which might have had some global styles that are affecting JL. I will also rebase the databus branch.

**Comment by ellisonbg** [comment]
Ohhh, no bootstrap please ;-) that would explain some of the styling problems of the commenting UI as well.

**Comment by saulshanabrook** [comment]
> Ohhh, no bootstrap please ;-)

Yep, we have been removing it as we worked, with a plan to remove it totally after the presentation.

**Comment by ian-r-rose** [comment]
@saulshanabrook is this resolved?

**Comment by saulshanabrook** [comment]
@ian-r-rose Yep! thanks for the reminder.
