### ISSUE TITLE
Custom keyboard shortcut not working

### ISSUE THREAD

**Issue by Rabeez** [jupyterlab/jupyterlab#6027]
I've added keyboard shortcuts to move notebook cells up/down:
```json
{
    "notebook:move-cell-down": {
      "command": "notebook:move-cell-down",
      "keys": [
        "Ctrl Shift Down"
      ],
      "selector": ".jp-Notebook:focus",
      "title": "Move Cell(s) Down",
      "category": "Notebook Cell Operations"
    },
    "notebook:move-cell-up": {
      "command": "notebook:move-cell-up",
      "keys": [
        "Ctrl Shift Up"
      ],
      "selector": ".jp-Notebook:focus",
      "title": "Move Cell(s) Up",
      "category": "Notebook Cell Operations"
    }
}
```

and these seemingly register as I can see the proper key hint in the command palette UI:
![image](https://user-images.githubusercontent.com/9392057/53280528-de616100-373c-11e9-829f-94c8b950cf23.png)

Clicking on these entries in the command palette works (not related to the keyboard shortcut) but using the shortcut itself does not do anything. 

- OS: Windows 10
- Browser: Chrome 72
- JupyterLab 0.35.3

**Comment by jasongrout** [comment]
Can you paste your shortcut key text in a code block here so it's easy to reproduce your setup?

Also, you were trying to use it in notebook command mode, right?

**Comment by Rabeez** [comment]
@jasongrout code block added, not sure why I put a screenshot there in the first place
Also, yes I'm definitely in command mode.

**Comment by jasongrout** [comment]
Thanks. Use "Ctrl Shift ArrowUp" instead of "Ctrl Shift Up". The key names are from the HTML standard, and are listed in https://w3c.github.io/uievents/#fixed-virtual-key-codes (and in the implementation at https://github.com/phosphorjs/phosphor/blob/8d99dbc8cedd4f25285bbced9d46eb790a293256/packages/keyboard/src/index.ts#L208)

**Comment by jasongrout** [comment]
I opened an issue in phosphor about logging an error when a user tries to register a keybinding with invalid key names.

**Comment by Rabeez** [comment]
Thanks, the shortcuts work now.
Also, this might be relevant. The `notebook:move-cell-down`/`up` commands aren't listed in the System Defaults panel of keyboard shortcuts. From what I could find I don't think this was a conscious omission.

**Comment by jasongrout** [comment]
In the latest prerelease, all commands (including these) are listed as a comment above the shortcuts in the settings page. IIRC, there is no default keyboard shortcut for moving cells, so that explains the omission  you saw.
