### ISSUE TITLE
Disable mirror output if many cell selected.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#603]
When selecting multiple cell and dragging, I would expect the cells to be moved around. Though right now it get the output you clicked on, which is confusing. 

I'm sure the UI could be improved and we could discuss what draginf with multiple cell selected should do, but the simplest thing right now would be to disable mirror outputs. Thoughts? 

![muli](https://cloud.githubusercontent.com/assets/335567/17375669/dbd2f8c4-5966-11e6-9fd7-eb48b191e947.gif)

Ideas of better UI, can the DragSource [is it how you call that?] get an extra class we could style differently ? Like "Hey this is what you are dragging" ?

**Comment by blink1073** [comment]
👍 for at least limiting it to one cell for now.  We'll need more discussion in general about drag-drop UI/UX in the notebook.

@danielballan, do you want to tackle implementing the guard against dragging more than one cell's output?

**Comment by danielballan** [comment]
Sure thing.

**Comment by ellisonbg** [comment]
We have completely changed the UX of all this so the issue is no longer relevant (we no longer use a drag interaction, so multi-cell logic isn't relevant).
