### ISSUE TITLE
Please add Settings for Terminal Font Size and styles

### ISSUE THREAD

**Issue by TheSarfaraz** [jupyterlab/jupyterlab#6030]
Kindly add settings to change the Terminal font sizing and other settings like line gaps, right now each line on terminal is too close to each other and some text is hidden due to that, also can not change font size separately, whole screen zooming messes up other stuff

If you are having issues with installation or configuration, you may ask for help on the [JupyterLab Gitter channel](https://gitter.im/jupyterlab/jupyterlab) or file an issue here.

**Comment by jasongrout** [comment]
Here are the terminal settings currently on the 1.0a1 prerelease, which I think covers everything you mentioned. You can get these by trying out the 1.0a1 prerelease, or you can wait (maybe a few months?) for the 1.0 release.

```javascript
{
    // Terminal
    // @jupyterlab/terminal-extension:plugin
    // Terminal settings.
    // *************************************

    // Font family
    // The font family used to render text.
    "fontFamily": "monospace",

    // Font size
    // The font size used to render text.
    "fontSize": 13,

    // Line height
    // The line height used to render text.
    "lineHeight": 1,

    // Scrollback Buffer
    // The amount of scrollback beyond initial viewport
    "scrollback": 1000,

    // Theme
    // The theme for the terminal.
    "theme": "dark"
}
```

**Comment by jasongrout** [comment]
Closing as resolved.
