### ISSUE TITLE
Re-connect to existing terminal (session) by unique identifier

### ISSUE THREAD

**Issue by AlexanderPashuk** [jupyterlab/jupyterlab#6031]
Hi guys,

I try to write simple add-on that will use terminal to lint Python code from notebooks. The problem is that now I am creating a new terminal with each browser tab refresh. It is working but every few days I have to manually turn off 5-10 created terminals...

Code snippet:

```js
import {
  Terminal
} from '@jupyterlab/terminal';

// ... code ...

term = new Terminal({initialCommand: 'echo "Opening flake8 terminal"'});
term.session = await app.serviceManager.terminals.startNew();  // app is JupyterLab instance;

// ... run something in created terminal ...
```

So my question is whether there are ways to do something like:

```js
// ... code ...

// try to find existing terminal
term = app.serviceManager.terminals.loadTerminalById('my_unique_terminal_identifier');

// create new terminal only if can't find existing
if (!term) {
    term = new Terminal({id: 'my_unique_terminal_identifier', initialCommand: 'echo "Opening new terminal"'});
}

// ... run something in created terminal ...
```

**Comment by ian-r-rose** [comment]
Hi @AlexanderPashuk, sorry for the slow response! Yes, this should be doable. In fact, the JupyterLab terminal extension already tries to reconnect based on a session name (the `'name'` argument in this command):
https://github.com/jupyterlab/jupyterlab/blob/91af807f8422ba846bb295c3c87a6c60e05e5869/packages/terminal-extension/src/index.ts#L262-L268

So you should be able to use something very similar to connect to an existing terminal session, or, if it does not exist, start one with that name.
