### ISSUE TITLE
Is there any slack channel/forum for Jupyter dev issues?

### ISSUE THREAD

**Issue by rahulpshah** [jupyterlab/jupyterlab#6033]
Hi all, thank you for such a wonderful open source software. Recently, I have tried contributing to the community by trying to address the `good-first-issue` issues. But I have realized that sometimes while resolving the issue, I get some stuck at trivial things which in hindsight could be resolved quicker if I had asked for some help. Therefore, I was wondering if there is any platform where one can post their queries. Also, one can use that platform to ask design & roadmap questions too.

Let me know your thoughts on it.

**Comment by lresende** [comment]
The Jupyter community uses Gitter, you can ask JupyterLab questions at the [JupyterLab channel](https://gitter.im/jupyter/jupyterlab)
