### ISSUE TITLE
Clicking does not work 

### ISSUE THREAD

**Issue by RunzheStat** [jupyterlab/jupyterlab#6042]
**Describe the bug**
1. No response when clicking any buttons except files. 
2. When I want to leave one cell to another,  weird jumping back happened.

The demo below is more explanatory.

**To Reproduce**
On my mac, basically after opening Jupyterlab, all clickings inside give no responses.

**Expected behavior**
A normal and smooth experience like before.

**Screenshots**
[demo](https://imgur.com/a/SsAccWK)

**Desktop (please complete the following information):**

- OS: [OSX 10.14.3]
- Browser [chrome 72.0.3626.119]
- JupyterLab [0.35.3]

**Additional context**
Jupyterlab worked well one week ago on my OS X 10.11 El Capitan. And then I  want to add a plugin (@lckr/jupyterlab_variableinspector). So I need to upgrade my node, npm and thus my OS X. After upgrading them and install the plugin, the problem happens. But I am not sure it is because of the version, because I did not use Jupyterlab in this week and may do something else to my system. I tried to disable the plugin and it did not help.

And I also tried Jupiter notebook 5.4.0(outdated) in the same environment, it worked well.

Thank you so much!

**Comment by jasongrout** [comment]
Wow, it sounds like something broke in all the upgrading. I would start by reinstalling JupyterLab if I were you.

**Comment by jasongrout** [comment]
(and I would first make sure jlab by itself worked, before installing the plugin again)

**Comment by RunzheStat** [comment]
Jason,

Thanks for the quick reply! Jupyter lab is not large and I have tried to reinstall it twice( w/o the plugin). No good luck. The clicking issue is just weird since Chrome works well, the Jupyter notebook works well and I did not update Jupyterlab itself. Any advice on what kind of extra information I can provide?

**Comment by jasongrout** [comment]
Good question. I've never heard of this happening before. Perhaps checking in the browser javascript console for errors might shed some light on the issue?

**Comment by RunzheStat** [comment]
Thanks! I just tried Safari and jlab works well. I guess I will continue to figure out what happened to my Chrome+jlab when I did not do anything to both of them.

**Comment by blois** [comment]
Perhaps try a Chrome incognito window? Sometimes extensions can get in the way.

**Comment by RunzheStat** [comment]
It does work! Thanks a lot. But I am still confused about how to reach it in a normal window? I have deleted the plugin and clear Chrome caches and restart Chrome. Below are some warnings when I deleted the plugin.

`
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
`
`
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
`
`
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
`
`
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
`

**Comment by jasongrout** [comment]
At this point, I would try disabling all of your chrome extensions, then adding them back one by one while testing.

**Comment by RunzheStat** [comment]
Solved. I finally just reinstalled the Chrome and the problem disappeared. I agree it should be caused by certain chrome extensions. Thanks a lot for your help, blois and Jason!

**Comment by jasongrout** [comment]
Great, glad it's working now!
