### ISSUE TITLE
Unset body color

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6043]
I think we shouldn't explicitly set the body color and theme:

https://github.com/jupyterlab/jupyterlab/blob/b212097539d3725bb46d1f7b92bb4c93db9827a3/packages/ui-components/style/index.css#L18-L19

This can mess up packages that end up inheriting from a body font color that is black, especially in a dark theme. Why don't we unset these like we do with other things in this override file?

CC @gnestor

**Comment by jasongrout** [comment]
Well, I can see the font-family is just putting back the style from https://github.com/jupyterlab/jupyterlab/blob/b212097539d3725bb46d1f7b92bb4c93db9827a3/packages/application/style/index.css#L14

The color probably shouldn't be hardcoded to that dark color, though.

**Comment by gnestor** [comment]
Agreed! I assume that I did that to counteract the blueprint global CSS and I haven't revisited it since. I'll find a better way of doing this.

**Comment by ellisonbg** [comment]
I commented in #6050 about this - we also shouldn't set the global font family on body as it will eventually lead to our components not rendering properly outside lab (which they should).
