### ISSUE TITLE
clone method for ABCWidgetFactory?

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6044]
When we "Create new view for X", the command 
https://github.com/jupyterlab/jupyterlab/blob/a496aad7e2001a36f004737dbb86922685ff6280/packages/docmanager-extension/src/index.ts#L709 
calls the document manager clone method: https://github.com/jupyterlab/jupyterlab/blob/2f9adfcea43142dbbe8f49368113b4eb02be88cc/packages/docmanager/src/manager.ts#L162-L175 which calls the widget manager clone method: https://github.com/jupyterlab/jupyterlab/blob/c3fff81d3f053c4f94e84263ae785eda56cb55aa/packages/docmanager/src/widgetmanager.ts#L179-L202 which then creates a brand new widget. For notebooks, this means a new rendermime is created: https://github.com/jupyterlab/jupyterlab/blob/03338d7fe749fdb3dcd71b2de765f7d9178d47bc/packages/notebook/src/widgetfactory.ts#L83-L86

However, there may be view state that should be shared among the views. For a cloned notebook view, I think it makes more sense for the rendermime to be shared. For example, we add a notebook-specific renderer to the rendermime for ipywidgets. We could share the rendermime if we knew it was a clone, rather than a brand new view.

Can we push the notion of 'clone' all the way down to the WidgetFactory creating views? We could even have a default implementation that just creates a new view, but then let specific widget factories override the clone method.

We do have an alternative for ipywidgets - we could attach the rendermime renderer to the context, which *is* shared between the views, and that way have access to the original document's renderer. However, this seems somewhat hacky, when perhaps you want the views to actually share some state.

**Comment by afshin** [comment]
If anybody wants to work on this issue before @jasongrout gets to it, please ping here and we'll re-assign the issue.

**Comment by Madhu94** [comment]
@afshin I'd like to try this.

**Comment by jasongrout** [comment]
Great!

I figured out a way to do the specific thing I was trying to do with widgets, but I think it probably is still a nice thing to have a clone method on widget factories.

**Comment by Madhu94** [comment]
Opened https://github.com/jupyterlab/jupyterlab/pull/6060 to address this
