### ISSUE TITLE
Terminals crash in flash on Win7

### ISSUE THREAD

**Issue by weitongwei** [jupyterlab/jupyterlab#6055]
I am running  jupyterlab 0.35.4. When I try to launch the terminal, it cames out with a flash and quit. 
OS: Win7-64bit, Anaconda3-64bit.
It happens on 2 Win7 computer.  On a Win10 computer, the terminal can be properly launched.

**Comment by jasongrout** [comment]
Can you launch a terminal in the classic notebook? (use the "Launch classic notebook" help menu item)

**Comment by weitongwei** [comment]
No. The same thing happened in the classic notebook.
My powershell path is:
%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe

In the Jupyter notebook starting terminal, I saw these messages:
==================
[E 21:39:37.971 NotebookApp] Uncaught exception POST /api/terminals (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri
='/api/terminals', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "d:\Anaconda3\lib\site-packages\tornado\web.py", line 1590, in _execu
te
        result = method(*self.path_args, **self.path_kwargs)
      File "d:\Anaconda3\lib\site-packages\tornado\web.py", line 3006, in wrappe
r
        return method(self, *args, **kwargs)
      File "d:\Anaconda3\lib\site-packages\notebook\terminal\api_handlers.py", l
ine 16, in post
        name, _ = self.terminal_manager.new_named_terminal()
      File "d:\Anaconda3\lib\site-packages\terminado\management.py", line 319, i
n new_named_terminal
        term = self.new_terminal()
      File "d:\Anaconda3\lib\site-packages\terminado\management.py", line 171, i
n new_terminal
        pty = PtyProcessUnicode.spawn(argv, env=env, cwd=options.get('cwd', None
))
      File "d:\Anaconda3\lib\site-packages\winpty\ptyprocess.py", line 89, in sp
awn
        'executable: %s.' % command
    FileNotFoundError: The command was not found or was not executable: powershe
ll.exe.
[W 21:39:37.974 NotebookApp] Unhandled error
[E 21:39:37.975 NotebookApp] {
      "X-Xsrftoken": "2|5315d671|6caaac0d7d87dd05552299953f69edda|1551014856",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://localhost:8888/tree",
      "Accept-Language": "zh-CN",
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) l
ike Gecko",
      "Host": "localhost:8888",
      "Content-Length": "0",
      "Connection": "Keep-Alive",
      "Cache-Control": "no-cache",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1551447490|23:username-local
host-8888|44:NDZiZDk3NTQ5NTFmNDMxOTk3MTk5Njk1NjIwZmNkZjA=|51cd2809226b4e8d9ccc13
fac7cbf02d834250863bfa66f26d60a63ce6d7ef32\"; _xsrf=2|5315d671|6caaac0d7d87dd055
52299953f69edda|1551014856"
    }
===================
weitongwei@hotmail.com

**Comment by jasongrout** [comment]
Thanks. That indicates that the problem is in the notebook server, not JupyterLab. The error above says it can't find powershell. I'm not sure why it can't find it.

However, it does seem that you can set it manually. `jupyter lab --help-all` includes this setting:

```
--LabApp.terminado_settings=<Dict>
    Default: {}
    Supply overrides for terminado. Currently only supports "shell_command".
```
That looks promising for being able to set the terminal shell command to the right path.

(I don't have experience with this issue, so I don't have a more complete example for you, but hopefully these pointers help you to find a solution.)

**Comment by weitongwei** [comment]
Thanks. I will try.

________________________________
weitongwei@hotmail.com

**Comment by jasongrout** [comment]
@weitongwei, any update on this issue?

**Comment by weitongwei** [comment]
No solution yet.

________________________________
weitongwei@hotmail.com

**Comment by jasongrout** [comment]
It looks like https://github.com/jupyterlab/jupyterlab/issues/3647 may be relevant?

**Comment by jasongrout** [comment]
Or not. Is this still an issue, since it's been almost a year?

**Comment by weitongwei** [comment]
Yes, it is still an issue on Win7, i.e. "Laucher Error: Invalid response: 500 Internal Server Error"

________________________________
weitongwei@hotmail.com

**Comment by telamonian** [comment]
One possibility is that your version of windows is too old. What version of windows 7 do you have (no updates, sp1, sp2, etc).

Powershell shipped with windows by default starting at window 7 sp1. Here's more info that may prove useful:

- install powershell: https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/install/installing-windows-powershell

- start powershell: https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/starting-windows-powershell

**Comment by JasonWeill** [comment]
Windows 7 ended support from Microsoft on January 14, 2020; Jupyter will continue to support later versions with new releases.
