### ISSUE TITLE
Stuck in "kernel reconnecting"

### ISSUE THREAD

**Issue by joeparis** [jupyterlab/jupyterlab#6062]
**Description**
On Windows, when installing and running JupyterLab under a virtual environment created with pipenv Jupyter will seemingly start without error. However, when creating either a new Notebook or Console from the Launcher the environment hangs in the "kernel reconnecting" state.

**To Reproduce**
1. Open a PowerShell window
2. Create a new directory and `cd` into it
3. Run `pipenv install jupyterlab`
4. Activate the virtualenv's shell with `pipenv shell` (this should happen automatically when you first create the virtualenv but must be done manually afterwards)
5. Launch JupyterLab with `jupyter lab`
6. In the Launcher, click to create a new Python 3 Notebook

The notebook will open but the kernel will be completely unresponsive. Restarting the kernel has no effect.

**Expected behavior**
JupyterLab should open and the kernel should respond when Python code is entered and executed.

**Screenshots**
[<img src="https://i.imgur.com/ix0WtG5b.png">](https://i.imgur.com/ix0WtG5.png)
[<img src="https://i.imgur.com/FbYpSoCb.png">](https://i.imgur.com/FbYpSoC.png)

**Desktop (please complete the following information):**

- OS: Windows 10, Version 1809 (Build 17763.316)
- PowerShell 5.1.17763 r316
- Browser: Chrome 72.0.3626.119, Firefox 65.0.2
- Python 3.7.2 and 3.6.5
- pipenv 2018.11.26
- JupyterLab 4.4.0

**Additional context**
If I install JupyterLab globally (i.e. run `pip install jupyterlab` outside of any virtualenv) it runs as expected. However, when I do this JupyterLab does not see any modules I have installed in a virtualenv so, for example, the following does **not** work:

```
C:\> pip install jupyterlab
C:\> mkdir test
C:\> cd test
C:\test\> pipenv install pandas
C:\test\> pipenv shell
(.venv) C:\test\> jupyter lab
```

JupyterLab will run as expected now but will not see pandas as being installed.

<details><summary>Troubleshoot Output</summary>
<pre>
(.venv) C:\Dev\sentdex_pandas> jupyter troubleshoot
$PATH:
        C:\Dev\sentdex_pandas\.venv\Scripts
        C:\Windows\system32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0\
        C:\Windows\System32\OpenSSH\
        C:\Program Files\Git\cmd
        C:\Program Files (x86)\Nodist\bin
        C:\Program Files\dotnet\
        C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
        C:\Program Files\Microsoft MPI\Bin\
        C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler
        C:\Program Files\Java\jdk-11.0.1\bin
        C:\Strawberry\c\bin
        C:\Strawberry\perl\site\bin
        C:\Strawberry\perl\bin
        C:\Users\joepa\AppData\Local\Programs\Python\Python37\Scripts\
        C:\Users\joepa\AppData\Local\Programs\Python\Python37\
        C:\Users\joepa\AppData\Roaming\Python\Python37\Scripts
        C:\Users\joepa\AppData\Local\Microsoft\WindowsApps
        C:\Users\joepa\AppData\Local\Programs\Microsoft VS Code\bin
        C:\Utils
        C:\kotlin-native-windows-1.3.11\bin
        C:\Users\joepa\AppData\Local\Pandoc\
        C:\Users\joepa\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\
        C:\Users\joepa\AppData\Local\Programs\Microsoft VS Code Insiders\bin
        C:\Dev\Exercism

sys.path:
        C:\Dev\sentdex_pandas\.venv\Scripts\jupyter-troubleshoot.EXE
        c:\dev\sentdex_pandas\.venv\scripts\python36.zip
        c:\dev\sentdex_pandas\.venv\DLLs
        c:\dev\sentdex_pandas\.venv\lib
        c:\dev\sentdex_pandas\.venv\scripts
        C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Lib
        C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\DLLs
        c:\dev\sentdex_pandas\.venv
        c:\dev\sentdex_pandas\.venv\lib\site-packages

sys.executable:
        c:\dev\sentdex_pandas\.venv\scripts\python.exe

sys.version:
        3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.17763-SP0

where jupyter:
        C:\Dev\sentdex_pandas\.venv\Scripts\jupyter.exe

pip list:
        Package           Version
        ----------------- -------
        attrs             19.1.0
        backcall          0.1.0
        bleach            3.1.0
        colorama          0.4.1
        decorator         4.3.2
        defusedxml        0.5.0
        entrypoints       0.3
        ipykernel         5.1.0
        ipython           7.3.0
        ipython-genutils  0.2.0
        jedi              0.13.3
        Jinja2            2.10
        jsonschema        3.0.1
        jupyter-client    5.2.4
        jupyter-core      4.4.0
        jupyterlab        0.35.4
        jupyterlab-server 0.2.0
        MarkupSafe        1.1.1
        mistune           0.8.4
        nbconvert         5.4.1
        nbformat          4.4.0
        notebook          5.7.4
        pandocfilters     1.4.2
        parso             0.3.4
        pickleshare       0.7.5
        pip               19.0.3
        prometheus-client 0.6.0
        prompt-toolkit    2.0.9
        Pygments          2.3.1
        pyrsistent        0.14.11
        python-dateutil   2.8.0
        pywinpty          0.5.5
        pyzmq             18.0.0
        Send2Trash        1.5.0
        setuptools        40.8.0
        six               1.12.0
        terminado         0.8.1
        testpath          0.4.2
        tornado           6.0.1
        traitlets         4.3.2
        wcwidth           0.1.7
        webencodings      0.5.1
        wheel             0.33.1
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
C:\Dev> cd .\sentdex_pandas\
C:\Dev\sentdex_pandas> pipenv shell
Launching subshell in virtual environment…
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Loading personal and system profiles took 670ms.
(.venv) C:\Dev\sentdex_pandas> jupyter lab --debug
[D 22:21:32.731 LabApp] Searching ['C:\\Dev\\sentdex_pandas', 'C:\\Users\\joepa\\.jupyter', 'c:\\dev\\sentdex_pandas\\.venv\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 22:21:32.732 LabApp] Looking for jupyter_config in C:\ProgramData\jupyter
[D 22:21:32.735 LabApp] Looking for jupyter_config in c:\dev\sentdex_pandas\.venv\etc\jupyter
[D 22:21:32.738 LabApp] Looking for jupyter_config in C:\Users\joepa\.jupyter
[D 22:21:32.739 LabApp] Looking for jupyter_config in C:\Dev\sentdex_pandas
[D 22:21:32.741 LabApp] Looking for jupyter_notebook_config in C:\ProgramData\jupyter
[D 22:21:32.742 LabApp] Looking for jupyter_notebook_config in c:\dev\sentdex_pandas\.venv\etc\jupyter
[D 22:21:32.744 LabApp] Looking for jupyter_notebook_config in C:\Users\joepa\.jupyter
[D 22:21:32.745 LabApp] Looking for jupyter_notebook_config in C:\Dev\sentdex_pandas
[D 22:21:33.000 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\ProgramData\jupyter\jupyter_notebook_config.json
[D 22:21:33.004 LabApp] Paths used for configuration of jupyter_notebook_config:
        c:\dev\sentdex_pandas\.venv\etc\jupyter\jupyter_notebook_config.d\jupyterlab.json
        c:\dev\sentdex_pandas\.venv\etc\jupyter\jupyter_notebook_config.json
[D 22:21:33.009 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\joepa\.jupyter\jupyter_notebook_config.json
[I 22:21:33.016 LabApp] JupyterLab extension loaded from c:\dev\sentdex_pandas\.venv\lib\site-packages\jupyterlab
[I 22:21:33.016 LabApp] JupyterLab application directory is c:\dev\sentdex_pandas\.venv\share\jupyter\lab
[W 22:21:33.019 LabApp] JupyterLab server extension not enabled, manually loading...
[I 22:21:33.021 LabApp] JupyterLab extension loaded from c:\dev\sentdex_pandas\.venv\lib\site-packages\jupyterlab
[I 22:21:33.021 LabApp] JupyterLab application directory is c:\dev\sentdex_pandas\.venv\share\jupyter\lab
[I 22:21:33.022 LabApp] Serving notebooks from local directory: C:\Dev\sentdex_pandas
[I 22:21:33.023 LabApp] The Jupyter Notebook is running at:
[I 22:21:33.025 LabApp] http://localhost:8888/?token=bfaecb97785bf7543d8d9a525ff32ebf2906a67950797f2a
[I 22:21:33.026 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:21:33.043 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/joepa/AppData/Roaming/jupyter/runtime/nbserver-596-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=bfaecb97785bf7543d8d9a525ff32ebf2906a67950797f2a
[D 22:21:34.394 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:34.396 LabApp] Using contents: services/contents
[D 22:21:34.405 LabApp] 200 GET /lab?token=bfaecb97785bf7543d8d9a525ff32ebf2906a67950797f2a (::1) 12.02ms
[D 22:21:34.429 LabApp] Path main.13de647526d0a582493b.js served from c:\dev\sentdex_pandas\.venv\share\jupyter\lab\static\main.13de647526d0a582493b.js
[D 22:21:34.432 LabApp] 304 GET /lab/static/main.13de647526d0a582493b.js (::1) 5.01ms
[D 22:21:34.439 LabApp] Path vendors~main.10079ad9676c70f28097.js served from c:\dev\sentdex_pandas\.venv\share\jupyter\lab\static\vendors~main.10079ad9676c70f28097.js
[D 22:21:34.441 LabApp] 304 GET /lab/static/vendors~main.10079ad9676c70f28097.js (::1) 3.01ms
[D 22:21:35.106 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.107 LabApp] Found kernel python3 in c:\dev\sentdex_pandas\.venv\share\jupyter\kernels
[D 22:21:35.112 LabApp] 200 GET /api/kernelspecs?1551680495102 (::1) 6.68ms
[D 22:21:35.114 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.115 LabApp] 200 GET /api/terminals?1551680495103 (::1) 2.00ms
[D 22:21:35.145 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.150 LabApp] 200 GET /lab/api/settings/@jupyterlab/application-extension:sidebar?1551680495143 (::1) 5.00ms
[D 22:21:35.151 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.177 LabApp] 200 GET /lab/api/settings/@jupyterlab/shortcuts-extension:plugin?1551680495143 (::1) 26.00ms
[D 22:21:35.179 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.189 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.191 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.194 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1551680495145 (::1) 14.98ms
[D 22:21:35.201 LabApp] 200 GET /lab/api/settings/@jupyterlab/apputils-extension:themes?1551680495146 (::1) 12.99ms
[D 22:21:35.202 LabApp] 200 GET /api/sessions?1551680495180 (::1) 11.00ms
[D 22:21:35.250 LabApp] Path @jupyterlab\theme-dark-extension\index.css served from c:\dev\sentdex_pandas\.venv\share\jupyter\lab\themes\@jupyterlab\theme-dark-extension\index.css
[D 22:21:35.252 LabApp] 304 GET /lab/api/themes/@jupyterlab/theme-dark-extension/index.css (::1) 2.05ms
[D 22:21:35.498 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.504 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.514 LabApp] 200 GET /api/contents/?content=1&1551680495493 (::1) 10.00ms
[D 22:21:35.517 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.522 LabApp] 200 GET /lab/api/settings/@jupyterlab/extensionmanager-extension:plugin?1551680495506 (::1) 6.00ms
[D 22:21:35.529 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.540 LabApp] 200 GET /lab/api/settings/@jupyterlab/notebook-extension:tracker?1551680495522 (::1) 11.99ms
[D 22:21:35.542 LabApp] Accepting token-authenticated connection from ::1
[I 22:21:35.702 LabApp] Node v11.6.0

[D 22:21:35.755 LabApp] 200 GET /api/nbconvert?1551680495524 (::1) 214.00ms
[D 22:21:35.756 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.762 LabApp] 200 GET /lab/api/settings/@jupyterlab/fileeditor-extension:plugin?1551680495528 (::1) 5.00ms
[I 22:21:35.764 LabApp] Build is up to date
[D 22:21:35.766 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.768 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.770 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.773 LabApp] 200 GET /lab/api/build?1551680495490 (::1) 275.98ms
[D 22:21:35.775 LabApp] 200 GET /lab/api/workspaces/lab?1551680495619 (::1) 10.00ms
[D 22:21:35.781 LabApp] 200 GET /lab/api/settings/@jupyterlab/codemirror-extension:commands?1551680495574 (::1) 13.01ms
[D 22:21:35.783 LabApp] 200 GET /api/sessions?1551680495580 (::1) 13.01ms
[D 22:21:35.786 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.872 LabApp] 200 GET /api/nbconvert?1551680495572 (::1) 87.00ms
[D 22:21:35.873 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.876 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.881 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.884 LabApp] 204 PUT /lab/api/workspaces/lab?1551680495795 (::1) 11.01ms
[W 22:21:35.885 LabApp] 404 GET /api/contents/Untitled.ipynb?content=0&1551680495790 (::1): No such file or directory: Untitled.ipynb
[W 22:21:35.886 LabApp] No such file or directory: Untitled.ipynb
[W 22:21:35.890 LabApp] 404 GET /api/contents/Untitled.ipynb?content=0&1551680495790 (::1) 13.99ms referer=http://localhost:8888/lab
[D 22:21:35.893 LabApp] 200 GET /api/contents/?1551680495790 (::1) 12.00ms
[D 22:21:35.948 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:35.953 LabApp] 200 GET /api/contents/?content=1&1551680495943 (::1) 6.03ms
[D 22:21:36.773 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:36.786 LabApp] 204 PUT /lab/api/workspaces/lab?1551680496762 (::1) 14.02ms
[D 22:21:39.541 LabApp] Accepting token-authenticated connection from ::1
[I 22:21:39.542 LabApp] Creating new notebook in /
[D 22:21:39.544 LabApp] Saving C:\Dev\sentdex_pandas\Untitled.ipynb
[D 22:21:39.579 LabApp] 201 POST /api/contents/?1551680499538 (::1) 37.03ms
[D 22:21:39.587 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:39.588 LabApp] 200 GET /api/contents/Untitled.ipynb?content=0&1551680499583 (::1) 2.00ms
[D 22:21:39.590 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:39.595 LabApp] 200 GET /api/contents/?content=1&1551680499583 (::1) 5.00ms
[D 22:21:39.649 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:39.660 LabApp] 200 GET /api/contents/Untitled.ipynb?type=notebook&content=1&1551680499645 (::1) 12.00ms
[D 22:21:39.702 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:39.706 LabApp] 200 GET /api/contents/?content=1&1551680499699 (::1) 5.05ms
[D 22:21:39.723 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:39.726 LabApp] 200 GET /api/contents/Untitled.ipynb/checkpoints?1551680499719 (::1) 3.01ms
[D 22:21:39.728 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:39.736 LabApp] 200 GET /api/contents/Untitled.ipynb/checkpoints?1551680499719 (::1) 8.03ms
[D 22:21:39.741 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:39.743 LabApp] 200 GET /api/contents/Untitled.ipynb/checkpoints?1551680499721 (::1) 2.01ms
[D 22:21:39.774 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:39.818 LabApp] Starting kernel: ['c:\\dev\\sentdex_pandas\\.venv\\scripts\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\joepa\\AppData\\Roaming\\jupyter\\runtime\\kernel-1f10112c-4840-4d25-b543-d56d4ba2b506.json']
[D 22:21:39.826 LabApp] Connecting to: tcp://127.0.0.1:50606
[D 22:21:39.835 LabApp] Connecting to: tcp://127.0.0.1:50604
[I 22:21:39.839 LabApp] Kernel started: 1f10112c-4840-4d25-b543-d56d4ba2b506
[D 22:21:39.840 LabApp] Kernel args: {'kernel_name': 'python3', 'cwd': 'C:\\Dev\\sentdex_pandas'}
[D 22:21:39.842 LabApp] 201 POST /api/sessions?1551680499771 (::1) 68.00ms
[D 22:21:39.866 LabApp] Initializing websocket connection /api/kernels/1f10112c-4840-4d25-b543-d56d4ba2b506/channels
[D 22:21:39.869 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:39.870 LabApp] Requesting kernel info from 1f10112c-4840-4d25-b543-d56d4ba2b506
[D 22:21:39.873 LabApp] Connecting to: tcp://127.0.0.1:50603
[D 22:21:40.168 LabApp] Initializing websocket connection /api/kernels/1f10112c-4840-4d25-b543-d56d4ba2b506/channels
[D 22:21:40.170 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 22:21:40.172 LabApp] Waiting for pending kernel_info request
[D 22:21:40.478 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:40.485 LabApp] 204 PUT /lab/api/workspaces/lab?1551680500475 (::1) 7.00ms
[D 22:21:40.892 LabApp] activity on 1f10112c-4840-4d25-b543-d56d4ba2b506: status
[D 22:21:40.893 LabApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.1', 'implementation': 'ipython', 'implementation_version': '7.3.0', 'language_info': {'name': 'python', 'version': '3.6.5', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': "Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]\nType 'copyright', 'credits' or 'license' for more information\nIPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.\n", 'help_links': [{'text': 'Python Reference', 'url': 'https://docs.python.org/3.6'}, {'text': 'IPython Reference', 'url': 'https://ipython.org/documentation.html'}, {'text': 'NumPy Reference', 'url': 'https://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy Reference', 'url': 'https://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib Reference', 'url': 'https://matplotlib.org/contents.html'}, {'text': 'SymPy Reference', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas Reference', 'url': 'https://pandas.pydata.org/pandas-docs/stable/'}]}
[I 22:21:40.896 LabApp] Adapting to protocol v5.1 for kernel 1f10112c-4840-4d25-b543-d56d4ba2b506
[I 22:21:40.899 LabApp] Adapting to protocol v5.1 for kernel 1f10112c-4840-4d25-b543-d56d4ba2b506
[D 22:21:40.900 LabApp] activity on 1f10112c-4840-4d25-b543-d56d4ba2b506: status
c:\dev\sentdex_pandas\.venv\lib\site-packages\notebook\base\zmqhandlers.py:284: RuntimeWarning: coroutine 'WebSocketHandler.get' was never awaited
  super(AuthenticatedZMQStreamHandler, self).get(*args, **kwargs)
[D 22:21:40.902 LabApp] 200 GET /api/kernels/1f10112c-4840-4d25-b543-d56d4ba2b506/channels?session_id=08f723d3-feaa-4bc7-9428-4dbcfb2066c0&token=bfaecb97785bf7543d8d9a525ff32ebf2906a67950797f2a (::1) 1037.09ms
[D 22:21:40.903 LabApp] 200 GET /api/kernels/1f10112c-4840-4d25-b543-d56d4ba2b506/channels?session_id=e83dbdae-ccc6-49ac-9919-8368ba6bfead&token=bfaecb97785bf7543d8d9a525ff32ebf2906a67950797f2a (127.0.0.1) 735.11ms
[D 22:21:41.912 LabApp] Initializing websocket connection /api/kernels/1f10112c-4840-4d25-b543-d56d4ba2b506/channels
[D 22:21:41.914 LabApp] Accepting token-authenticated connection from ::1
[W 22:21:41.915 LabApp] Replacing stale connection: 1f10112c-4840-4d25-b543-d56d4ba2b506:08f723d3-feaa-4bc7-9428-4dbcfb2066c0
[D 22:21:42.216 LabApp] Initializing websocket connection /api/kernels/1f10112c-4840-4d25-b543-d56d4ba2b506/channels
[D 22:21:42.218 LabApp] Accepting token-authenticated connection from 127.0.0.1
[W 22:21:42.219 LabApp] Replacing stale connection: 1f10112c-4840-4d25-b543-d56d4ba2b506:e83dbdae-ccc6-49ac-9919-8368ba6bfead
[D 22:21:45.115 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:45.119 LabApp] 200 GET /api/sessions?1551680505103 (::1) 5.04ms
[D 22:21:45.121 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:45.125 LabApp] 200 GET /api/terminals?1551680505105 (::1) 4.00ms
[D 22:21:50.506 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:50.509 LabApp] 200 GET /api/contents/?content=1&1551680510495 (::1) 4.98ms
[D 22:21:52.031 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:52.034 LabApp] 200 GET /api/contents/?content=1&1551680512027 (::1) 4.00ms
[D 22:21:55.106 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:55.107 LabApp] 200 GET /api/sessions?1551680515103 (::1) 1.00ms
[D 22:21:55.108 LabApp] Accepting token-authenticated connection from ::1
[D 22:21:55.110 LabApp] 200 GET /api/terminals?1551680515103 (::1) 2.03ms
[D 22:22:02.499 LabApp] Accepting token-authenticated connection from ::1
[D 22:22:02.504 LabApp] 200 GET /api/contents/?content=1&1551680522494 (::1) 5.03ms
[D 22:22:05.117 LabApp] Accepting token-authenticated connection from ::1
[D 22:22:05.120 LabApp] 200 GET /api/sessions?1551680525104 (::1) 3.99ms
[D 22:22:05.125 LabApp] Accepting token-authenticated connection from ::1
[D 22:22:05.133 LabApp] 200 GET /api/terminals?1551680525105 (::1) 8.00ms
[D 22:22:07.257 LabApp] Accepting token-authenticated connection from ::1
[I 22:22:07.259 LabApp] Shutting down on /api/shutdown request.
[D 22:22:07.272 LabApp] 200 POST /api/shutdown?1551680527252 (::1) 15.05ms
[I 22:22:07.273 LabApp] Shutting down 1 kernel
[I 22:22:07.476 LabApp] Kernel shutdown: 1f10112c-4840-4d25-b543-d56d4ba2b506
</pre>
</details>

**Comment by cdgreenidge** [comment]
Downgrading to Tornado 5.1.1 fixed this for me (`pip install tornado==5.1.1`).

**Comment by joeparis** [comment]
@cdgreenidge You were right, pinning tornado to v.5.1.1 solved the problem. I thought I had performed a thorough search for the issue before opening mine but I missed it. As this is documented in both [4441](https://github.com/jupyter/notebook/issues/4441) and [4399](https://github.com/jupyter/notebook/issues/4399) I'm going to close this issue.

**Comment by nordllar** [comment]
Thanks, I had the same problem using docker - you saved my day!

**Comment by heathcliff233** [comment]
thank you! you saved my day!!

**Comment by cpoptic** [comment]
Downgrading from version 6.0 to v.5.1.1 fixed this issue on OSX
