### ISSUE TITLE
Missing 403.html template file in static directory

### ISSUE THREAD

**Issue by BioGeek** [jupyterlab/jupyterlab#6065]
**Describe the bug**
We have a multi-user JupyterLab environment. A colleague sent me a link to a notebook in her JupyterLab instance. Instead of getting a message that I don't have permission to the lab of this other user, i get the error:

    Cannot find template: "403.html"
    
    In "/path/to/.../share/jupyter/lab/static"

**To Reproduce**

1. Suppose my user name is biogeek and the username of my colleague is otheruser.
    If I want to go to my JupyterLab instance, I go to https://my.company.com/user/biogeek/lab
2. If I go to the JupyterLab of my colleague at https://my.company.com/user/otheruser/lab, I get the above error

**Expected behavior**
A page or popup saying that you do not have access to that page.

**Screenshots**
![screenshot of 403 error](https://i.imgur.com/rLC7H6r.jpg)

**Desktop (please complete the following information):**

- OS: Windows 7
- Browser: Firefox 55.0 (32 bit)
- JupyterLab: 0.35.2-foss-2018b-Python-3.6.6

**Additional context**

I think the copying of the static data from the buildDir to the staticDir is done in webpack.config.js, but I couldn't immediately find where the static assets are located in this repository.

**Comment by BioGeek** [comment]
If you tell me where to place the 403.html template file, I'm happy to make a pull request.

**Comment by saulshanabrook** [comment]
Thanks for opening up this issue! That would be awesome. This would be a PR to `jupyterlab_server`. I think it would be adding the `403.html` file to this directory: https://github.com/jupyterlab/jupyterlab_server/tree/master/jupyterlab_server

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab_server/pull/69
