### ISSUE TITLE
Pandas_profiling: malfunctioning formatting.

### ISSUE THREAD

**Issue by LonelyDaoist** [jupyterlab/jupyterlab#6068]
While using the pandas_profiling package, the formatting seems to be malfunctioning unlike in jupyter notebook where it's rendered well, here's a screenshot demonstrating the issue

**the first one is while using jupyter lab:**
![screenshot from 2019-03-05 22-19-07](https://user-images.githubusercontent.com/44263802/53839219-3a2ab600-3f97-11e9-8791-e0f11490e270.png)

**the second one is while using jupyter notebook:**
![screenshot from 2019-03-05 22-18-17](https://user-images.githubusercontent.com/44263802/53839313-82e26f00-3f97-11e9-956d-b226bd8417c5.png)

**Additional information:**

- **OS:** Fedora 29

- **Browser:**  Chromium

- **Jupyter Lab**: 0.35.4 (same for 0.35.3)

- **Jupyter Notebook:** 5.7.4

- **pandas_profiling**: 1.4.1

**Comment by jasongrout** [comment]
Interesting. Would you mind giving instructions for reproducing this?

**Comment by jasongrout** [comment]
(also, you might check in the latest jlab prerelease, which has many, many updates: `pip install jupyterlab --pre`)

**Comment by LonelyDaoist** [comment]
The data set used is the kaggle's titanic data set:
```
import pandas as pd
import pandas_profiling
data = pd.read_csv("train.csv")

pandas_profiling.ProfileReport(data) # the issue

```

**Comment by agoose77** [comment]
Just looking at this briefly, this library uses JQuery and Bootstrap for the rendering. I suspect that we're now stripping out the Bootstrap stylesheet that provides the `label` CSS class.
If you add the script / style tags from https://github.com/pandas-profiling/pandas-profiling/blob/master/pandas_profiling/templates/wrapper.html this is this result in the current stable release of JLab
![image](https://user-images.githubusercontent.com/1248413/53876010-c66fc400-3ffd-11e9-997f-25a984978f33.png)

**Comment by LonelyDaoist** [comment]
@agoose77 Thank you for the suggestion but where do I add the tags?

**Comment by ellisonbg** [comment]
The real fix is for the library to ship its HTML with inline styling. The underlying principle is that kernel libraries should work with any frontend (classic, lab, nteract, colab, etc.). Because different frontends have different JS/CSS loaded onto the page, if you need styling, you will want to include it with the HTML representation. Also, loading bootstrap onto the JupyterLab page causes all manner of problems as its CSS is not well scoped.

**Comment by agoose77** [comment]
@LonelyDaoist 
> @agoose77 Thank you for the suggestion but where do I add the tags?
My last comment was not correct - we're not actually stripping anything. This was an issue with the default HTML representation omitting the bootstrap stylesheet. You can fix this by displaying the report with 
```python
from IPython.display import HTML
report = pandas_profiling.ProfileReport(data)
display.HTML(report.to_html())
```
This solution will interfere with JupyterLab display formatting, unfortunately. You can work around this by creating a temporary file, and using "IPython.display.IFrame" to render it. Or, you can use the `srcdata` tag of an IFrame to set the IFrame content. I'm not sure if this is something we want to allow in JupyterLab, but it works for now:
```python
inner_html = report.to_html().replace('"', "&quot;")
html = '<iframe srcdoc="{}" width=1200 height=1200>'.format(inner_html)
display.HTML(html)
```
