### ISSUE TITLE
Files in open tabs do not update on external modifications

### ISSUE THREAD

**Issue by rgerkin** [jupyterlab/jupyterlab#6069]
**Describe the bug**
Files in open tabs do not update from external modifications.  This is true even when the file is explicitly selected for viewing from the sidebar.

**To Reproduce**
1. Create a .csv file, e.g. with Pandas
2. Use the file sidebar to display it (either with the editor or CSVTable)
3. Edit and save that file with something other than the Jupyter Lab file editor (e.g. programmatically from a notebook, from Excel, etc.)
4. Notice that the file in Jupyter Lab (e.g. in the editor or CSVTable) remains unchanged.  
5. Additionally note that selecting the same file again from the file sidebar does not trigger a refresh, but just activates the tab with the old version of the file.  
6. Note that editing the same file from the Jupyter Lab file editor will trigger a refresh of the view in e.g. CSVTable in another lab tab.  

**Expected behavior**
If the file is externally edited and overwritten, the contents should be refreshed in any editor or CSVTable (or other viewer) tab when I activate that tab.  At the very least, they should be refreshed when I explicitly click on that file in the File sidebar and activate that view (e.g. CSVTable).  

**Desktop (please complete the following information):**
- Chrome 72.xxxx
- JupyterLab 0.35.3

**Comment by jasongrout** [comment]
Related to https://github.com/jupyterlab/jupyterlab/issues/541
