### ISSUE TITLE
Short cells rendered as long

### ISSUE THREAD

**Issue by polakowo** [jupyterlab/jupyterlab#6074]
If I'm importing a notebook which has long cells, change and rerun those cells to have a shorter output, close and open the notebook again, the respective cells have still the `scrolled` property enabled in the metadata. I really wouldn't care if it wasn't that distractive. I'm using jlab 35.4.

![screen shot 2019-03-07 at 20 06 43](https://user-images.githubusercontent.com/2664108/53982182-8cddac80-4114-11e9-9493-e1068fed3103.png)

**Comment by jasongrout** [comment]
In #5968, we make the scrolled property automatically saved and restored. Are you saying that you'd rather that jlab did *not* remember the scrolled state of a cell?

**Comment by jasongrout** [comment]
> I really wouldn't care if it wasn't that distractive.

Or are you saying that you wouldn't care if a cell remembered its scrolled state if the scrolled state looked different?

**Comment by polakowo** [comment]
Some Jupyter Notebooks that I import into Lab have short output cells which look like long ones because of (incorrect) metadata. For example, below is a screenshot of a short cell which was marked as scrollable and distracts my attention. The only way to disable this style is to rerun the cell and save the notebook, but somehow the metadata isn't updating. 

![screen shot 2019-03-07 at 21 10 16](https://user-images.githubusercontent.com/2664108/53986155-b6e79c80-411d-11e9-9648-12bac42b3c3e.png)

We can collapse output cells by clicking on the blue bar but I'd love to change between `"scrollable": true` and `"scrollable": false` in the metadata with one click and preserve the state once the notebook is saved.

**Comment by jasongrout** [comment]
Okay, thanks for the clarification. You can change that scrollable view with the cell right-click menu in JLab (the Enable Scrolling/Disable Scrolling options). In current jlab, to save that you have to use the "Save with View State" menu option.

With #5968, the scrollable state will automatically be remembered and saved when the notebook is saved.

**Comment by polakowo** [comment]
Okay, have overlooked this, thank you!

**Comment by ellisonbg** [comment]
I still don't understand what your first screenshot is showing - it looks like the visualization is on top of and going outside the scrollable area. Am I seeing that correctly?

**Comment by jasongrout** [comment]
> I still don't understand what your first screenshot is showing - it looks like the visualization is on top of and going outside the scrollable area. Am I seeing that correctly?

I think that is the problem tracked in #4253

**Comment by ellisonbg** [comment]
Thanks Jason.

**Comment by jasongrout** [comment]
Closing as fixed in #5968.
