### ISSUE TITLE
[Feature request] Install JupyterLab via Homebrew

### ISSUE THREAD

**Issue by martimlobao** [jupyterlab/jupyterlab#6075]
Homebrew is an extremely popular package manager for macOS (and Linux), and already supports installing jupyter using `brew install jupyter`.

Because a lot of data scientists rely on Homebrew to install software and since JupyterLab has been [stable enough for normal use](https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906) for over a year now, it would be nice to be able to install JupyterLab using a brew command, too.

**Comment by timkpaine** [comment]
`brew install python3 && python3 -m pip install jupyterlab`

**Comment by jasongrout** [comment]
Thanks for answering, @timkpaine. 

It'd be great if someone opened a PR to the brew repo with a jlab recipe.
