### ISSUE TITLE
Memory usage statusbar feature is causing an exception if nbresuse is not installed

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab#6076]
I'm seeing this after I reload JupyterLab:

```
SyntaxError: Unexpected token # in JSON at position 0
    at eval (eval at Private.makeMetricsRequest.then.response (memoryUsage.js:105), <anonymous>:1:38)
    at eval (eval at Private.makeMetricsRequest.then.response (memoryUsage.js:105), <anonymous>:2:3)
    at Private.makeMetricsRequest.then.response (memoryUsage.js:105)
```

It appears that the statusbar is trying to display a response from from [nbresuse](https://github.com/yuvipanda/nbresuse) which is a server extension that I don't have installed. I think we should either move nbresuse into core or move this statusbar feature into its own extension that is not bundled with core.

cc @ian-r-rose

**Comment by ian-r-rose** [comment]
We may want to move this functionality into the `nbresuse` repo, since that `metrics` endpoint is not in the stock notebook server. It seems that the notebook server *does* have a `metrics` endpoint for prometheus, but I don't really know what the intended use is there. Since that endpoint exists, this plugin fails silently for me (rather than producing an error). cc @yuvipanda for comments.

@gnestor What notebook version did you see this with? Do you still see it?

**Comment by gnestor** [comment]
I'm running 5.7.2. I'm still seeing it when running non-dev-mode.

**Comment by ian-r-rose** [comment]
Huh, weird. I'm not getting any 404s because of [this](https://github.com/jupyter/notebook/blob/9560e0cf4c3a3612f7e0f869035e7e3eeb5853a0/notebook/base/handlers.py#L943) handler, which is not nbresuse, but is not really what we intend here.

**Comment by gnestor** [comment]
I'll keep an eye out for it. Not sure exactly what's causing it...

**Comment by yuvipanda** [comment]
I added /metrics to notebook to replace nbresuse with a standard endpoint (prometheus), but it only provides memory usage of the notebook process itself - but not of all child processes. Once we implement that we can use that directly.

**Comment by afshin** [comment]
@gnestor Since the new polling API went in, I don't see this any more, because the polling API is supposed to handle rejection. Is this still an issue? Could you help me reproduce it to try to address it?

**Comment by gnestor** [comment]
I haven't seen it since the new polling API went it, so I'll close this for now. If I see it again, I'll reopen.
