### ISSUE TITLE
notebook toolbar steals keyboard focus, double performs actions on enter

### ISSUE THREAD

**Issue by ivanov** [jupyterlab/jupyterlab#6077]
**Describe the bug**
Clicking on a notebook toolbar icon, followed by enter, causes that action to be performed twice.

**To Reproduce**

1. Open a notebook
2. Click on the "+" in the toolbar to add a new cell:  a new cell appears
3. Press "Enter": two additional cells appear.

**Expected behavior**
at least in 0.34.0 (tested via try.jupyter.org binder) - the keyboard focus was not stolen by the toolbar, and keyboard focus remained on the cell (Enter in step 3 moved the currently active cell into edit mode)

**Desktop (please complete the following information):**

- OS: irrelevant 
- Browser: both Firefox and Chromium
- JupyterLab: master, 1.0.0a1

**Comment by ivanov** [comment]
credit to @madridnick for finding this bug!

**Comment by ivanov** [comment]
Add cell, cut, paste, run the selected cell and advance,  and restart kernel are all affected by this.

**Comment by ivanov** [comment]
also - `Space` executes the command 3 times.

**Comment by jasongrout** [comment]
I'm not seeing this in my 1.0a1 install. (macOS, Firefox)

**Comment by AlbertHilb** [comment]
I can confirm (Linux, Firefox). The issue comes from [this commit](https://github.com/jupyterlab/jupyterlab/commit/21db80eebe9df5f489f45a56023ea3f0eaf7ef78#diff-5ac906b2c5352f4f841b1481b776bbaf) that has reverted the changes from #5344.

**Comment by ellisonbg** [comment]
Ohhh, good find, surprising others hadn't found this.

**Comment by jasongrout** [comment]
@AlbertHilb - good find! CC also @gnestor.

And I'm not crazy. Both @ivanov and I can't reproduce this in my Firefox 65.0.1 macOS install, but we can reproduce it in my Chrome 72 macOS install. (and yes, I turned off the browser cache, etc.) It's really weird that the focus works fine in Firefox.

**Comment by AlbertHilb** [comment]
Hi @jasongrout.

> And I'm not crazy.

No doubt! :blush:

>  It's really weird

Indeed!

**Comment by gnestor** [comment]
Good find, @AlbertHilb! Thanks for submitting a PR so quickly!
