### ISSUE TITLE
about turtle

### ISSUE THREAD

**Issue by passengeryjy** [jupyterlab/jupyterlab#6080]
when I run ,"turtle.tracer" is false.I want to find the reason.

**Comment by agoose77** [comment]
You'll need to post more information in order for anyone to understand the problem. This might include example code, a longer description, perhaps even screenshots of the issue,

**Comment by passengeryjy** [comment]
it's ok,and i will post the result in the window

**Comment by passengeryjy** [comment]
this problem is solved
and thanks @agoose77

**Comment by agoose77** [comment]
@jasongrout I think we can close this then :)
