### ISSUE TITLE
Cannot find terminal icon

### ISSUE THREAD

**Issue by sjacob90** [jupyterlab/jupyterlab#6084]
I recently installed JupyterLab but cannot find the icon that opens the terminal.
I am using the following versions:
Python 3.6
jupyter-console 5.1.0
jupyterlab 0.35.4
![image](https://user-images.githubusercontent.com/20179695/54067703-a4d53d80-4286-11e9-9125-bf44da1cd0a8.png)

**Comment by jasongrout** [comment]
Can you check to see if the terminal is available in the classic notebook? Some systems (like some versions of windows) don't support a terminal.

**Comment by sjacob90** [comment]
Is classic notebook referring to Jupyter notebook? I believe terminal is not accessible in Jupyter notebook for windows.

**Comment by jasongrout** [comment]
I believe it is accessible from JupyterLab when it is accessible from the notebook. Perhaps that is the issue then.
