### ISSUE TITLE
Can we open multiple file browser tabs?

### ISSUE THREAD

**Issue by cocoaaa** [jupyterlab/jupyterlab#6085]
Hi, 
Is it possible to create more than a single 'File Browser' tab on the side bar?
I often need to switch between different folders to check the outputs (log files, images) or refer to other scripts, and it would be very helpful if I can have multiple file browser tabs on the sidebar.
Is this feature currently available? 

Thanks!

**Comment by timkpaine** [comment]
You may like this extension https://github.com/youngthejames/jupyterlab_filetree

**Comment by dhirschfeld** [comment]
***xref:*** #3865, #3685

**Comment by cocoaaa** [comment]
Thank you for the link and cross-references. I'll try out the extension for now.

**Comment by jasongrout** [comment]
Thanks! Closing as answered, feel free to comment below if you'd like to continue discussing.

**Comment by mocquin** [comment]
Would it be possible to actually have 2 file browser in the same tab ? 

I often have a working-folder AND a home-folder, and switch between the two. Having both available in a single tab would be quite convenient. See this "paint-made" example :

<img width="482" alt="Capture d’écran 2019-05-01 à 19 36 41" src="https://user-images.githubusercontent.com/36188368/57031904-3c348c80-6c49-11e9-9d23-cecefa3e169a.png">
