### ISSUE TITLE
Top Area

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#6088]
For now the top area has been used to display the Jupyter logo and the main menu. The rest of the space is still available to third-party extensions who can use `app.shell.add(widget, 'top')` to add their own components and widgets, which is convenient.

One example is the [jupyterlab-topbar](https://github.com/jtpio/jupyterlab-topbar) monorepo which contains a few extensions making use of this remaining space in the top area. The idea is to expose an interface similar to the notebook toolbar, so other extensions can hook themselves into this available space. This can also be a way to provide an alternative to the status bar and reclaim some screen space.

The question now is: are there any plans for using this space on the right of the top area as part of the core JupyterLab?

Related to https://github.com/jupyterlab/jupyterlab/pull/6087.

**Comment by saulshanabrook** [comment]
Thanks for the question. 

> The question now is: are there any plans for using this space on the right of the top area as part of the core JupyterLab?

Not at the moment! If you wanna chat more in depth about it, [feel free to come to one of our weekly dev calls](https://paper.dropbox.com/doc/JupyterLab-Dev-Meeting-Minutes--AZY95~fOWFUIZnQGfvO3RbpmAg-PIca1769tUfZiTNDV8Zqm)

**Comment by jtpio** [comment]
Thanks @saulshanabrook for sharing this!
