### ISSUE TITLE
Blank Screen w/ Fresh Py 3.6 Install

### ISSUE THREAD

**Issue by ajennings6767** [jupyterlab/jupyterlab#6089]
Hi,

I have been setting up a new workstation and went to install Jupyter Lab via pip. However, when I run it I get a completely blank screen.

No errors from the command prompt:
```
H:\BOND_TRA\ATJ\Quant\Projects
λ jupyter lab
[I 16:09:10.602 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 16:09:10.613 LabApp] JupyterLab extension loaded from c:\users\xbbl3nz\appdata\local\programs\python\python36\lib\site-packages\jupyterlab
[I 16:09:10.614 LabApp] JupyterLab application directory is c:\users\xbbl3nz\appdata\local\programs\python\python36\share\jupyter\lab
[W 16:09:10.617 LabApp] JupyterLab server extension not enabled, manually loading...
[I 16:09:10.621 LabApp] JupyterLab extension loaded from c:\users\xbbl3nz\appdata\local\programs\python\python36\lib\site-packages\jupyterlab
[I 16:09:10.622 LabApp] JupyterLab application directory is c:\users\xbbl3nz\appdata\local\programs\python\python36\share\jupyter\lab
[I 16:09:10.623 LabApp] Serving notebooks from local directory: H:\BOND_TRA\ATJ\Quant\Projects
[I 16:09:10.623 LabApp] The Jupyter Notebook is running at:
[I 16:09:10.624 LabApp] http://localhost:8888/?token=e5fe74355dd46c7f39ef34f1bb0c22f0389fc42b491b573c
[I 16:09:10.624 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:09:10.643 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/XBBL3NZ/AppData/Roaming/jupyter/runtime/nbserver-7952-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=e5fe74355dd46c7f39ef34f1bb0c22f0389fc42b491b573c
[I 16:09:41.876 LabApp] 302 GET /?token=e5fe74355dd46c7f39ef34f1bb0c22f0389fc42b491b573c (::1) 1.00ms
```

Current Version:
```
H:\BOND_TRA\ATJ\Quant\Projects
λ pip show jupyterlab
Name: jupyterlab
Version: 0.35.4
Summary: The JupyterLab notebook server extension.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: c:\users\xbbl3nz\appdata\local\programs\python\python36\lib\site-packages
Requires: notebook, jupyterlab-server
Required-by:
```

Any thoughts on what might be going on?

Thanks in advance for your help!

EDIT: 
Found the below in the console:
![image](https://user-images.githubusercontent.com/30580411/54233197-cf233700-44e2-11e9-8422-49845c424c8d.png)

**Comment by techgopal** [comment]
same problem for me.

**Comment by lautjy** [comment]
Having the same problem. Tried different versions of tornado, currently at tornado==4.5.3 and jupyterlab==0.35.4 and 0.35.3. All installed using *conda* from `conda-forge` channel. 

I can see the same error in Chrome as OP:

```
Refused to execute script from 'http://localhost:8888/lab/static/vendors~main.10079ad9676c70f28097.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Refused to execute script from 'http://localhost:8888/lab/static/main.13de647526d0a582493b.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

Both of those files exist and have code visible in Chrome console. So Tornado server did serve the files.

This is the header when downloading either of those files:

```
HTTP/1.1 304 Not Modified
Server: TornadoServer/4.5.3
Date: Thu, 14 Mar 2019 21:15:33 GMT
X-Content-Type-Options: nosniff
Content-Security-Policy: frame-ancestors 'self'; report-uri /api/security/csp-report
Accept-Ranges: bytes
Cache-Control: no-cache
```

My guess of what's going on:
That header is disabling the browser from "sniffing" the correct MIME type, but I don't see it specifying "application/json". Hence browser thinks its "text/plain" and won't run it.

I can't seem to get a version of jupyter lab running that works, for checking a working header.

**Comment by lautjy** [comment]
Ah, this is a known problem, and it is due to the MIME types coming from the tornado server.
For completeness I'll mention that working headers in an earlier release of "notebook" did not have the "nosniff" item.

This error is tracked correctly here:

And a workaround from there is to downgrade the "notebook" part:

`pip install notebook==5.7.5` or `conda install notebook==5.7.5` and refresh browser cache (CTRL+Shift+F5).

**Comment by ajennings6767** [comment]
That worked perfectly! Didn't see the original issue. Thanks!
