### ISSUE TITLE
Shortcut Shift-Tab not working on Safari

### ISSUE THREAD

**Issue by jingw222** [jupyterlab/jupyterlab#6091]
When I use that shortcut to show up the doc page, the page just keeps flickering non-stop, rendering it barely usable. This is no problem on Chrome. What gives?

**Comment by afshin** [comment]
In my version of Lab (current `master` ~1.0.0a3) I only see one initial flicker in Safari, which is visually jarring, but it doesn't prevent use. I've addressed that in a PR.
