### ISSUE TITLE
Relative sizing of filenames in browser

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab#6093]
When the file browser is small, filename truncation is a nasty usability problem. One option would be to elide the date info when the browser is small relative to the rest of the UI - done here manually by @ellisonbg with local CSS changes for illustration:

![image](https://user-images.githubusercontent.com/57394/54402101-2c64e700-46a1-11e9-8b24-77af44c81ad3.png)

To be clear, the above is a crop of a wider window to show the detail; the full window is here for clarity:

![image](https://user-images.githubusercontent.com/57394/54402139-4e5e6980-46a1-11e9-98da-326fbfd26b49.png)

cc @jasongrout

**Comment by saulshanabrook** [comment]
@ellisonbg wrote a "SizeWatcher" that could help here if some debouncing is added for performance reasonos https://github.com/jupyterlab/jupyterlab/pull/1624/files#diff-f8fe849165f5de57445483ab2dd1f943
