### ISSUE TITLE
Dark theme dropdown CSV delimiter menu

### ISSUE THREAD

**Issue by mellowjoey** [jupyterlab/jupyterlab#6095]
![image](https://user-images.githubusercontent.com/48363378/54472690-bf636580-47f6-11e9-8bbd-fb912aeb7242.png)
It does seem there is no styling for a dark csv delimiter menu. Delimiter menu for a light theme seems fine though.

Other types of `select` tags may also be susceptible to the same issue.

**Comment by mellowjoey** [comment]
I have fixed the issue in devtools, but unfortunately, I do not have time to look at the source code and fix it.

But what I want to recommend is to make dropdown menu classes more consistent and ordinary to mitigate further issues.

**Comment by jtpio** [comment]
@mellowjoey does https://github.com/jupyterlab/jupyterlab/pull/6097 correspond to what you had in the devtools?

On a side note, many of the other dropdowns seem to be styled differently and don't have this issue.

**Comment by mellowjoey** [comment]
@jtpio It does! Nice fix!

**Comment by saulshanabrook** [comment]
Thanks @jtpio for fixing this!
