### ISSUE TITLE
Error for npm test 

### ISSUE THREAD

**Issue by jacpan** [jupyterlab/jupyterlab#610]
![error](https://cloud.githubusercontent.com/assets/7809648/17492316/208fda98-5d60-11e6-8d79-98b0133a1bb2.jpg)

Not sure how to resolve this error

EDIT: tests work in chrome so this may just be a firefox issue

**Comment by blink1073** [comment]
I am running tests locally and on Travis using Firefox, and it is working.   I *think* I've seen this before though.  I believe nuking node_modules and re-installing fixed it.

**Comment by jacpan** [comment]
I've tried the following steps but it doesn't seem to resolve the issue:

git clean -fdx
npm install
pip install -e .
jupyter serverextension enable --py jupyterlab
jupyter lab

**Comment by blink1073** [comment]
Perhaps restart your terminal and/or OS?

**Comment by jacpan** [comment]
Yes I tried restarting and cleaning/re-installing and then restarting terminal again but neither seems to do the trick

**Comment by blink1073** [comment]
Note from @jacpan on Gitter: the problem was importing code from `src/` instead of `lib/`.  It may be worth trying to recreate the error condition and seeing if we can figure out how to get a more informative message in a catastrophic failure.

**Comment by ellisonbg** [comment]
Closing for now, please feel free to re-open if needed.
