### ISSUE TITLE
webpack command not found, node_modules folder is missing. Happens again 

### ISSUE THREAD

**Issue by yt87** [jupyterlab/jupyterlab#6102]
I am familiar with #5157. I did try solutions presented there. 
```
> jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: /tmp/miniconda3/share/jupyter/lab
        @pyviz/jupyterlab_pyviz v0.7.0  enabled  OK

Build recommended, please run `jupyter lab build`:
    @pyviz/jupyterlab_pyviz needs to be included in build

> jupyter lab build
[LabBuildApp] JupyterLab 0.35.4
[LabBuildApp] Cleaning /tmp/miniconda3/share/jupyter/lab
Cleaning /tmp/miniconda3/share/jupyter/lab...
Success!
[LabBuildApp] Building in /tmp/miniconda3/share/jupyter/lab
[LabBuildApp] Node v11.11.0

[LabBuildApp] > node /home/george.trojan/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.9.4
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[3/5] Fetching packages...
[----------------------------------------------------------------------] 0/837(node:12690) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/caniuse-db/-/caniuse-db-1.0.30000950.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/tmp/miniconda3/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[LabBuildApp] > node /home/george.trojan/miniconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build
yarn run v1.9.4
$ webpack
/bin/sh: webpack: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
The status bar in the `Fetching packages...` actually fills up with hashes showing 835/837, so I assume 835 packages are downloaded. But `miniconda3/share/jupyter/lab/staging/node_modules` is missing.
I have tried reinstalling jupyterlab, run `jupyter lab build` many times. I always can access the offending package on registry.yarnpkg.com via browser without any delays.
This might not be relevant, but I did notice that when `node` is retrying, firefox is very slow. Output from `strace` on `node` scrolls fast.

[yarn-error.log](https://github.com/jupyterlab/jupyterlab/files/2984226/yarn-error.log)

**Comment by yt87** [comment]
I got it resolved. I suspect yarn is the culprit. My steps:

```
cd ~/miniconda3/share/jupyter/lab/staging
npm install
```
Install succeeded without any network connection troubles.  The command `jupyter lab build` wiped out clean staging, so I had to repeat `npm install`. Then I commented out
`clean(self.app_dir)`  in `site-packages/jupyterlab/labapp.py` (~line 75) and few lines in `commands.py`:
```
def build(self, name=None, version=None, public_url=None,
              command='build:prod', clean_staging=False):
        """Build the application.
        """
        # Set up the build directory.
        app_dir = self.app_dir

        #self._populate_staging(
        #    name=name, version=version, public_url=public_url,
        #    clean=clean_staging
        #)

        staging = pjoin(app_dir, 'staging')

        # Make sure packages are installed.
        #self._run(['node', YARN_PATH, 'install'], cwd=staging)

        # Build the app.
        self._run(['node', YARN_PATH, 'run', command], cwd=staging)
```
The build completed with a few warnings, however geoviews examples run fine.

There were several complaints on the github yarn page about the "There appears to be trouble with your network connection" message, without a clean solution.  Should jupyterlab use npm instead?
https://iamturns.com/yarn-vs-npm-2018

**Comment by saulshanabrook** [comment]
Glad you were able to work around this one.

It is possible there was an intermittent network issue when you were installing. I have seen this before when I am on a flaky network. 

Just curious, are you building here to install an existing jupyterlab plugin? We have an issue open for supporting installing extensions without having to rebuild jupyterlab: https://github.com/jupyterlab/jupyterlab/issues/5672

**Comment by yt87** [comment]
No, I am pretty sure network is not the cause. I have tried many times
(~10) on 3 different days, the symptoms were exactly the same. I mentioned
in #6102 that at the same time when installation stalled, I was able to
access  yarn repository url from a browser. I tried "node install"  twice,
in both cases it worked without issues.
A few days earlier I did run the came installation on my home computer
(Fedora 29). I recall seeing the timeout warnings but installation
eventually succeeded. The problem system is Red Hat 7.
The same issue was raised on yarn github:
https://github.com/yarnpkg/yarn/issues/5259. Different yarn versions,
different operating systems, same symptoms, lot of attempts, no definite
answer.

My workaround is for this particular plugin: pyviz. I guess I will have to
revert to the original python code for future installation other plugins.
If there are problems  I will modify the install command in
_AppHandler.build to get yarn out of way. Would this work?

self._run(['node', YARN_PATH, 'install'], cwd=staging) ---->
self._run(['node',  'install'], cwd=staging)

I am not sure what you mean by the existing plugin. It was pyviz, installed
successfully and enabled. The issue was not webpack or node but yarn. Of
course, it would be nice to get rid of all  of them.

**Comment by vidartf** [comment]
Xref this upstream issue: https://github.com/yarnpkg/yarn/issues/5259

**Comment by yt87** [comment]
My solution was to change jupyterlab code:

```
$ diff commands.py commands.py.orig
 452,453c452
<         #self._run(['node', YARN_PATH, 'install'], cwd=staging)
<         self._run(['npm', 'install'], cwd=staging)
---
>         self._run(['node', YARN_PATH, 'install'], cwd=staging)
467,468c466
<         #self._run(['node', YARN_PATH, 'install'], cwd=staging)
<         self._run(['npm', 'install'], cwd=staging)
---
>         self._run(['node', YARN_PATH, 'install'], cwd=staging)
```
I have installed a few extensions, ran `jupyter lab build`, without any errors.
Sorry for the typo in my previous comment. It is `npm`, not `node`.

I guess the issue can be closed, unless you expect somebody else might encounter the same error. That voodoo took me a couple of days - I don't know javascript.

**Comment by vidartf** [comment]
Closing as resolved then.
