### ISSUE TITLE
Context menu for widgets

### ISSUE THREAD

**Issue by felipebmendes** [jupyterlab/jupyterlab#6105]
I'm working on the development of a jupyterlab extension. I've created a widget that contains a list of items fetched from the server and now I'm trying to add a context menu to this widget so I can execute some custom functions for each item of this list (eg: open a dialog with additional information about the chosen item), but the context menu is never presented on screen.

Is what I'm trying to do even possible to achieve? Am I wrongly implementing it? I couldn't find anything related to it in the documentation.

This is my `activate` function:

```
function activateWidgetExtension(app: JupyterLab) {
    let commands = app.commands;

    let w: ItemWidget = new ItemWidget({ commands});

	const print: string = 'sidebar:print';


	app.commands.addCommand(print, {
		execute: () => {
		  console.log('context menu');
		},
		label: 'Print'
	});

	app.contextMenu.addItem({
		type: 'separator',
		selector: '.jp-Notebook .jp-Cell',
		rank: 12
	});

    // Add a context menu item to sidebar tabs.
	 app.contextMenu.addItem({
		command: 'sidebar:print',
		selector: '.jp-CodeConsole-promptCell',
		rank: 13
	 });

	app.shell.addToRightArea(w);
}
```

Thanks in advance.

**Comment by saulshanabrook** [comment]
> I've created a widget that contains a list of items fetched from the server and now I'm trying to add a context menu to this widget so I can execute some custom functions for each item of this list (eg: open a dialog with additional information about the chosen item), but the context menu is never presented on screen.

This seems reasonable. So when you right click on the element a context menu doesn't appear? 

One reason could be that the selectors don't match the elements you are clicking on.

**Comment by felipebmendes** [comment]
It was indeed the selector referencing a wrong element. Thanks for your help, @saulshanabrook.
