### ISSUE TITLE
Workaround for Chrome Issue 455987 referer

### ISSUE THREAD

**Issue by robnagler** [jupyterlab/jupyterlab#6106]
**Describe the bug**

`Download` from the file browser doesn't work in Chrome. model.ts [adds a `download` attribute](https://github.com/jupyterlab/jupyterlab/blob/f7096cf3/packages/filebrowser/src/model.ts#L324), which causes the Referer to not be sent, which results in 403 for the user, and an error on the server `Blocking request with no referer`. 

**To Reproduce**

1. Start JupyterLab in Chrome
2. Right click Download on anything

**Expected behavior**

Download should work.

**Screenshots**

**Desktop (please complete the following information):**

- Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Additional context**

I think this patch would at least make most downloads work properly:

```diff
diff --git a/packages/filebrowser/src/model.ts b/packages/filebrowser/src/model.ts
index 57b240d..62c1d3d 100644
--- a/packages/filebrowser/src/model.ts
+++ b/packages/filebrowser/src/model.ts
@@ -321,7 +321,13 @@ export class FileBrowserModel implements IDisposable {
       let element = document.createElement('a');
       document.body.appendChild(element);
       element.setAttribute('href', url);
-      element.setAttribute('download', '');
+      if (window.chrome) {
+        // workaround https://bugs.chromium.org/p/chromium/issues/detail?id=455987
+        element.setAttribute('type', 'application/octet-stream');
+      }
+      else {
+        element.setAttribute('download', '');
+      }
       element.click();
       document.body.removeChild(element);
       return void 0;
```

**Comment by saulshanabrook** [comment]
Thanks for opening this up.

I can't reproduce it locally or on Binder, but I do see the [chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=455987) you referenced in the other thread. 

On binder, when I open the dev tools, I do see that the referrer is set:

<img width="961" alt="Screen Shot 2019-03-20 at 10 21 21 AM" src="https://user-images.githubusercontent.com/1186124/54691609-ed4bf100-4af9-11e9-8972-b67a82f10370.png">

Has anyone else seen this bug? Do you have a sense of when it is triggered?

**Comment by robnagler** [comment]
Thanks for the quick response @saulshanabrook! 

The problem is trigger for right-click Download in the file browser:

<img width="263" alt="Screen Shot 2019-03-20 at 9 00 34 AM" src="https://user-images.githubusercontent.com/5495179/54694999-d3f17780-4aee-11e9-89f3-6f8672c4fa18.png">

It looks like it succeed if you don't actually try to open the file, but it shows Failed:

<img width="225" alt="Screen Shot 2019-03-20 at 9 00 45 AM" src="https://user-images.githubusercontent.com/5495179/54694938-b02e3180-4aee-11e9-830c-3378745b46d7.png">

**Comment by saulshanabrook** [comment]
Yeah, I tried that on Binder in Chrome and it seems to work for me. Here is a link to start a binder jupyterlab server: https://mybinder.org/v2/gh/binder-examples/jupyterlab/master?urlpath=lab/tree/index.ipynb

Maybe there is something about your server that changes the permission? If you open your inspector and look at the network logs, do you see a referer sent with the request, like it is in mine?

**Comment by robnagler** [comment]
The download works on Binder, which is using an older version of `notebook`.

The code to block the request was only [added two months ago](https://github.com/jupyter/notebook/commit/7f7bfeefc08568aacd626438e22a6361aa57223a#diff-9962a6ef5ac893ea0b43a765d657689fR422). Binder is using notebook 5.7.2, which was released in Nov 2018. We're using 5.7.6, which includes `check_referer`.

**Comment by diegobenedicto** [comment]
Now the download doesn't work on Binder https://mybinder.org/v2/gh/binder-examples/jupyterlab/master?urlpath=lab/tree/index.ipynb

Binder is using notebook 5.7.6

**Comment by saulshanabrook** [comment]
Thanks for tracking down that it was the notebook version that is at the root of the issue here.

We have an open issue for this: https://github.com/jupyterlab/jupyterlab/issues/6131

**Comment by minrk** [comment]
A workaround for this should be to add `?_xsrf=...` to the download href as is done for API requests. That should ensure the xsrf check is passed even if the Referer is not sent. The Chrome bug is specific to the 'download' attribute, so I don't know if you can make it work without that. The notebook-classic download links don't use this.
