### ISSUE TITLE
all-Jupyter team meeting

### ISSUE THREAD

**Issue by Zsailer** [jupyterlab/jupyterlab#6110]
Hey all, 

I wanted to point you to the "all-Jupyter community call" happening next Tuesday, 9AM PST.  This new *monthly* call replaces the previous weekly Jupyter team call. For more information, see [this discourse post](https://discourse.jupyter.org/t/reviving-the-all-jupyter-team-meetings/423/6).

I'd love to have someone from the JupyterLab ecosystem (core member or not) share an update about the project for the community. If you have something you'd like to demo for the community, that would be great too! We can let you share your screen for ~5 minutes. Then, we'll let others ask questions. If you're interested, let me know here!

This is the first official meeting under this new format. We'll see how it goes and then ask for feedback after the call. We'll iterate from there. 

Thanks everyone!

**Comment by Zsailer** [comment]
Here's some important info:

* We'll meet at 9am PST on Zoom [here](https://calpoly.zoom.us/my/jupyter).
* The HackMD agenda is [here](https://hackmd.io/5WDMIAOjQx-SZe4_RP6wrg?both#).

Sign into the agenda if you'll be there. Also, feel free to add your topic to the agenda list!

I'll close the agenda 24 hours before the call.

**Comment by vidartf** [comment]
Ping for meeting in half an hour.

**Comment by Zsailer** [comment]
Closing this issue since the meeting happened yesterday! If you missed it, check out the video [here](https://calpoly.zoom.us/recording/share/aWb4ooDZsEESzF-LMNyodilb1Rc6PWsklp1R-fvrwh2wIumekTziMw?startTime=1553616201000).
