### ISSUE TITLE
Right to left

### ISSUE THREAD

**Issue by IlanHindy** [jupyterlab/jupyterlab#6113]
Hi,
How can I change a notebook to be right to left (rtl)?
Ilan

**Comment by jasongrout** [comment]
IIRC, there is no built-in support for RTL in JupyterLab. We welcome contributions to JupyterLab adding such support.

**Comment by jasongrout** [comment]
We're tracking adding support for this at https://github.com/jupyterlab/jupyterlab/issues/1163, and there was at least some work at https://github.com/jupyterlab/jupyterlab/pull/3316. Let's move the discussion over there if you or someone else is interested in working on this.
