### ISSUE TITLE
labextension install @jupyterlab/hub-extension

### ISSUE THREAD

**Issue by kboxk7** [jupyterlab/jupyterlab#6116]
I have a properly configured Jupyterhub on an EMR cluster. I installed JupyterLab with "pip install Jupyterlab" and it worked well. Post installation with a restart of jupyterhub services "service Jupyterhub restart" I can change URL from /tree to /lab to go to JupyterLab in the browser and it works well..

Issue : When I attempt to install jupyterlab/hub-extension it says 
"jupyter-lab labextension install @jupyterlab/hub-extension"

Error : No such file or directory: /usr/*/*/jupyter/lab/extensions/labextension

Any suggestion ?

**Comment by saulshanabrook** [comment]
I believe the command should be `jupyter labextension install @jupyterlab/hub-extension` instead of `jupyter-lab labextension install @jupyterlab/hub-extension`. Does that command work?

**Comment by kboxk7** [comment]
Agree as per documents command is jupyter labextension install
@jupyterlab/hub-extension
But once I install pip install  jupyterlab it works well

which jupyter (not mapped)
which jupyterlab (not mapped)
which jupyter-lab (seems to be in right directory)

jupyter labextension install @jupyterlab/hub-extension
says jupyter command not found

jupyter-lab labextension install @jupyterlab/hub-extension
says no such file or directory /labextension

that's the reason I am using jupyter-lab labextension install
@jupyterlab/hub-extension
I am using properly configured Jupypterhub on cluster

Am I doing something wrong ? what shall I do, please suggest.

**Comment by saulshanabrook** [comment]
If you run `pip install jupyter` does the `jupyter` command work? If not, the your `PATH` doesn't include the directory pip is installed too.

I know my Python environment has gotten pretty messed up in the past. One option would be to install [miniconda](https://conda.io/projects/conda/en/latest/user-guide/install/index.html) and create a new environment and install jupyterlab in it with conda `conda install -c conda-forge jupyterlab`

**Comment by kboxk7** [comment]
I am using "path pip3 install Jupyterlab" as I already have Jupyterhub
installed so not installing Jupyter and Jupyter command does not work.

Post installing JupterLab and restating Jupyterhub, I can see Jupyterlab is
available by changing URL /tree to /lab


"If not, the your PATH doesn't include the directory pip is installed too."

I have tried running Jupyter extension command from PIP directory but still
the same..

Can you explain on this plz

Really can't do re-engineering with environment moreover even after "conda
install -c conda-forge jupyterlab" Jupyter command is not expected to run.

I am sure I am missing something..

**Comment by vidartf** [comment]
@kboxk7 Do you have `jupyter-labextension` available as a command? Then you could do `jupyter-labextension install [...]`.

**Comment by kboxk7** [comment]
jupyter-labextension: command not found

is there a way to use "/site-packages/jupyterlab/labextensions.py" for installing extension ?
or any other recommended solution to install @jupyterlab/hub-extension

**Comment by aaronchall** [comment]
@kboxk7 if you have Python on your path and jupyterlab on your PYTHONPATH, you can do

`python -m jupyterlab.labextensions install @...`

**Comment by jasongrout** [comment]
The JupyterHub extension is now integrated in JupyterLab. Please comment here if you'd like to continue the discussion.
