### ISSUE TITLE
Editor gutter background contrast is too high

### ISSUE THREAD

**Issue by AlbertHilb** [jupyterlab/jupyterlab#6121]
Especially in dark theme, the contrast of the editor gutter background seems too high to me.
Of course this is much a matter of personal taste; however in the default theme of three of the most popular editors today, VSCode, Atom and SublimeText, the gutter background has the same color of the surrounding. I suspect this reflects the preferences of the majority of the users.
So my proposal is to use the same color for the gutter background and the text background in the jupyterlab editor as well.

The editor as it appears now:

![immagine](https://user-images.githubusercontent.com/1220427/54761979-7b57d280-4bf3-11e9-8b7a-4105b5506d78.png)

and as it would appear after the change I proposed

![immagine](https://user-images.githubusercontent.com/1220427/54762180-e43f4a80-4bf3-11e9-995b-08f1f61d6dc3.png)

If you agree I can submit a PR.

Cheers

**Comment by vidartf** [comment]
I'll leave the final call to the more design-oriented here, but I would agree that it should *at least* be as close as the color of the tab headers.

**Comment by jasongrout** [comment]
+1 to the change you propose.
