### ISSUE TITLE
Open kernel from arbitrary venv ala nb_conda_kernels

### ISSUE THREAD

**Issue by nealmcb** [jupyterlab/jupyterlab#6122]
How can I use a `jupyterlab` installation from one virtual environment (venv) to run notebooks on kernels located in other venvs?

I.e. I want something like what [`nb_conda_kernels`](https://github.com/Anaconda-Platform/nb_conda_kernels) provides for the conda environment, but I want to use standard Python 3 venv environments, but without having to manually put together KernelSpecs for each venv.

I keep my venvs in `~/Envs`, as specified by `$WORKON_HOME`.

I was hoping this would just work out of the box, but when I see a `Select Kernel` dialog box, the only options are the Python 2 and Python 3 in my base OS.

I'm using these versions on Ubuntu Bionic 18.04 LTS:

```
 $ jupyter --version
4.4.0
$ jupyter lab --version
0.35.4
```

**Comment by jasongrout** [comment]
>  but without having to manually put together KernelSpecs for each venv.

That, or having a new kernel manager on the server that does it for you similar to nb_conda_kernels, is exactly what needs to happen. JupyterLab just asks the server for whatever kernels it knows about. Getting more kernels available is something you have to do with the server's kernel manager, which is outside of JupyterLab's scope as a frontend for Jupyter.

**Comment by jasongrout** [comment]
I would suggest creating a python package similar to nb_conda_kernels that examines the venvs you have and makes available kernels for each one.

**Comment by nealmcb** [comment]
OK, I guess I need to know more about the "server" involved here (the Jupyter server?), and where the right place might be to go find folks that have implemented the right kind of kernel managers.

**Comment by jasongrout** [comment]
I would suggest first looking at how nb_conda_kernels does things, since they've already solved the problem for conda environments. Presumably the solution would be very similar for the Jupyter parts.

**Comment by nealmcb** [comment]
I'm taking notes here:

Benefits: Save time and space. Surely folks don't want to install `JupyterLab` in all of their venvs. I've got dozens of them lying around, and don't know of another way to use `JupyterLab` with the modules defined in them. I also assume folks don't want to have to run a separate `JupyterLab` for each venv they want to be working with at any given time.

* Jupyter and kernel-specs: [Making kernels for Jupyter — jupyter_client 5.2.3 documentation](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs)

I'm guessing that the "server" noted above is the Jupyter Notebook server, a web application, and it uses the `jupyter_client` API to work with the kernels we're interested in.  E.g. note that `nb_conda_kernels` uses `KernelSpecManager` from `jupyter_client.kernelspec` (see [manager.py#L13](https://github.com/Anaconda-Platform/nb_conda_kernels/blob/f2e0d06b599d037606c59961396cbc3dcd816da5/nb_conda_kernels/manager.py#L13)).

....to be continued...

**Comment by jasongrout** [comment]
Great! Let's close this issue, as we've moved beyond the scope of JupyterLab. Sounds like a great project!

**Comment by jasongrout** [comment]
(We can move further discussion to the Jupyter discourse, or the Jupyter mailing list, or issues in the relevant Jupyter repos like the notebook server or jupyter_client...)

**Comment by nealmcb** [comment]
It makes sense to move the discussion. But where to?

And I'm still puzzled by which server you're talking about, and the overall architecture involved here, so I know what needs to be modified or configured to work with what.

You reference the "notebook server". I guess you mean https://github.com/jupyter/notebook. And you also reference the `jupyter_client` that I noted. Which would seem more appropriate? Is the notebook server using the jupyter_client API to work with the kernels?

**Comment by jasongrout** [comment]
Thanks for asking questions where things are still puzzling to you.

Yes, the notebook server is  https://github.com/jupyter/notebook

From the nb_conda_kernel readme at https://github.com/Anaconda-Platform/nb_conda_kernels#nb_conda_kernels:

> The package works by defining a custom KernelSpecManager that scans the current set of conda environments for kernel specifications. It dynamically modifies each KernelSpec so that it can be properly run from the notebook environment. When you create a new notebook, these modified kernels will be made available in the selection list.

Here is where their kernelspec manager is defined (inheriting from the kernel spec manager in jupyter_client): https://github.com/Anaconda-Platform/nb_conda_kernels/blob/master/nb_conda_kernels/manager.py

After you have a kernel spec manager that can find all the kernel specs you want, you then configure your notebook server to use such a custom kernel spec manager (for example, https://jupyter-notebook.readthedocs.io/en/stable/config.html (search for kernelspecmanager)).

As for a good place for the conversation, questions about the kernel spec manager are probably best on the jupyter_client repo, and questions about configuring the notebook server to use the kernel spec manager are probably best on the jupyter/notebook repo. More general questions would be great on the Jupyter discourse or mailing list (see https://jupyter.org/community).

(I'm not trying to shut down discussion here, just trying to help the discussion be in the place where it will (a) attract the attention of relevant people, and (b) be easily found in the future by people that can benefit from the discussion.)

Does that help?
