### ISSUE TITLE
Install extensions in a modified JupyterLab

### ISSUE THREAD

**Issue by tarekbouz** [jupyterlab/jupyterlab#6132]
Hi,

I'm having trouble installing JupyterLab extensions in a modified JupyterLab.

I made some changes in @jupyterlab/services, and everything works well in development mode.
After that, I created a "python wheel package".

The package installation works well and i can see the changes but if I install an extension with "jupyter labextension install" I lose all the changes.

Is installing a new extension will always pulls the JupyterLab packages from NPM? 
Is there a solution to this problem?

Thank you!

**Comment by saulshanabrook** [comment]
> Is installing a new extension will always pulls the JupyterLab packages from NPM?

Yes, I would imagine they would, or at least could. Why? Well extensions specify dependencies in their `package.json` on the released versions of the JupyterLab packages. So it is possible that yarn/npm is seeing you don't have those versions and is pulling in the released versions.

To debug this, I would go into the `staging` subdirectory of your JupyterLab app directory (you can find this with `jupyter lab path`). From there you can see what node modules are pulled in. A helpful command is `yarn why <name of package>`. This will tell you what versions you have installed of that package and why. 

Sorry you have to dive into this JS dependency world!

**Comment by tarekbouz** [comment]
Thanks @saulshanabrook.
I fixed the problem by installing extensions into a development branch of JupyterLab(jlpm run add:sibling “path”).
