### ISSUE TITLE
Rename ErrorInvalid response: 400 Invalid header received from client

### ISSUE THREAD

**Issue by brucmao** [jupyterlab/jupyterlab#6135]
I can not rename ipynb
![](https://i.loli.net/2019/03/25/5c98aa2be051b.gif)

**Comment by brucmao** [comment]
I'm seeing this error in the powshell. so i use pip3 install --user nodejs [ via](https://github.com/jupyterlab/jupyterlab/issues/4327)
when i install the nodejs ,it still have the error

**Comment by jasongrout** [comment]
Can you rename a file in the classic notebook? That will help us determine if this is a server issue or a JupyterLab issue.

**Comment by jasongrout** [comment]
Also, can you try the new prerelease we just released? `pip install --pre jupyterlab`.

**Comment by jasongrout** [comment]
Closing since the author did not follow up. Please comment here if you'd like to continue the discussion.
