### ISSUE TITLE
Creating link in jupyterlab notebook that opens another notebook

### ISSUE THREAD

**Issue by scottwsides** [jupyterlab/jupyterlab#6136]
The closed issue #2649 addresses this, but I still don't know how to link to another jupyterlab notebook from within a notebook, and I can't find the documentation that walks through each step. Sorry to revisit this, but it would be a great feature. Can someone spell out all the steps to actually make this work. When I simply type

`[mylink](./nx-driver.ipynb)`

This doesn't work at all. First, I don't know what 'mylink' is.

Thanks,

Hi! Thanks for using JupyterLab.

If you are reporting an issue with JupyterLab, please use the [GitHub issue](https://github.com/jupyterlab/jupyterlab/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

The JupyterLab team and Project Jupyter value our community, and JupyterLab
follows the Jupyter [Community Guides](https://jupyter.readthedocs.io/en/latest/community/content-community.html).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser [e.g. chrome 69.0, firefox 62.0]
- JupyterLab [e.g. 0.34.2]

**Additional context**

If available, please include the following details:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser console here.
</pre>
</details>

**Comment by jasongrout** [comment]
The idea is that if you want to create a link to another notebook, you can type something like `[Name of notebook](./relative/path/to/notebook)` in a markdown cell. For example:

1. Create two notebooks, A.ipynb and B.ipynb, in the same directory.
2. In A.ipynb, create a markdown cell with the following contents: `[Other notebook](./B.ipynb)`.
3. Render the markdown cell in A.ipynb. Clicking on the "Other notebook" link should open B.ipynb in JupyterLab.

**Comment by scottwsides** [comment]
Ah! in a markdown cell. That worked. Thanks!
