### ISSUE TITLE
jupyter lab build ignores Yarn exit codes

### ISSUE THREAD

**Issue by rowles** [jupyterlab/jupyterlab#6137]
Environment:
`jupyterlab==0.34.12`

Example command:
```
$ jupyter lab build
```
Example stdout+stderr:
```
...
<REDACTED>
...
yarn run v1.9.4
$ webpack
/bin/sh: 1: webpack: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Regardless of that error in stdout,`jupyter lab build` returns an exit code of 0.

I briefly looked at the code and the issue may lie In [_AppHandler.build()](https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/commands.py#L429), it appears that the _AppHandler._run() returns the exit code of the two yarn commands executed, but these exit codes are ignored.

```python
    def build(self, name=None, version=None, public_url=None,
              command='build:prod', clean_staging=False):
        """Build the application.
        """
        # Set up the build directory.
        app_dir = self.app_dir

        self._populate_staging(
            name=name, version=version, public_url=public_url,
            clean=clean_staging
        )

        staging = pjoin(app_dir, 'staging')

        # Make sure packages are installed.
        # exit code ignored?
        self._run(['node', YARN_PATH, 'install'], cwd=staging)

        # Build the app.
        # exit code ignored?
        self._run(['node', YARN_PATH, 'run', command], cwd=staging)
```

**Comment by vidartf** [comment]
Thanks for the report/suggestion!

Adding some checks and returns of a decent exit code (and possibly a helpful log message?) would be a very welcome change. However, I don't think that the yarn exit codes are well documented (I'd be happy to be wrong here!). I have some vague memory that yarn might given non-0 exit codes if there were warnings for example. If that is the case, we might have to be careful in how we do this. If not, then this should be a lot more straight forward.
