### ISSUE TITLE
Jupyterlab/Jupyter Notebook opening blank page

### ISSUE THREAD

**Issue by jrkohlmeyer19** [jupyterlab/jupyterlab#6140]
Hello everyone,

Both Jupyterlab and Jupyter Notebook are currently opening a blank, white page when I launch either application. This occurs in Chrome, Firefox, and Edge. It occurs in the incognito versions of each browser as well. This issue occurs both when I launch the applications from Anaconda Navigator as well as from a command prompt.

Solutions I've tried to fix the issue: restarting the browser(s), restarting my computer, ending all Python related tasks and services in Task Manager, clearing my browser's cache & cookies, and updating my packages.

Technical Specs:
Windows 10 Enterprise, version 1803, build 17134.648
Python 3.6.8
Anaconda Navigator 1.9.6
Jupyter Notebook 5.7.6
Jupyterlab 0.35.4

Any thoughts or suggestions? Thanks for the help in the advance!

**Comment by jasongrout** [comment]
This reminds me of https://github.com/jupyterlab/jupyterlab/issues/6119.

**Comment by jrkohlmeyer19** [comment]
You are correct @jasongrout. The PR at [#4468](https://github.com/jupyter/notebook/pull/4468) fixed the issue for me!
