### ISSUE TITLE
Completion does not work on nested fields

### ISSUE THREAD

**Issue by letalvoj** [jupyterlab/jupyterlab#6146]
**Describe the bug**
Even though the kernel knows that a field is of a specific type, there is no completion 

**To Reproduce**
```
>>> df = pd.Series([1,4,3],name='col').to_frame()
>>> df.col.#<SHIFT+TAB> doc pops up (see the screenshot)
>>> df.col.#<TAB> nothing pops up:(
```

**Expected behavior**
It seems that jupyter knows the type and precise value of the field. I'd be nice if the completion worked.

**Screenshots**
<img width="761" alt="Screenshot 2019-03-28 at 15 28 52" src="https://user-images.githubusercontent.com/5262321/55165852-6a1c4200-516e-11e9-8328-1937bb76ef97.png">

**Desktop (please complete the following information):**

- OS: [e.g. macOS 10.14.3 (18D109)]
- Browser [e.g. Chrome 73.0.3683.86]
- JupyterLab [e.g. 0.35.4]

**Comment by jasongrout** [comment]
Can you check to see if you have the same issues with the ipython command-line program, or the classic notebook? The completions are provided by the kernel, and JupyterLab just shows what information the kernel gives it, so it's likely that this issue should be filed with ipython instead of here.

**Comment by letalvoj** [comment]
Yup, sorry. Wrong repository 🤦‍♂️ I found a related issue here: https://github.com/ipython/ipython/issues/11609
