### ISSUE TITLE
Shapely objects are not displayed

### ISSUE THREAD

**Issue by LostFan123** [jupyterlab/jupyterlab#6147]
In Jupyter Notebook it was possible to see [Shapely](https://shapely.readthedocs.io/en/stable/manual.html) objects. For example:

![image](https://user-images.githubusercontent.com/20144534/55165466-c16de280-516d-11e9-9256-d492b748be34.png)
In Jupyter lab though this doesn't work:

![image](https://user-images.githubusercontent.com/20144534/55165561-ed896380-516d-11e9-870a-60e498ac5d4c.png)

Minimal example code to reproduce the issue:
```python
from shapely.geometry import LineString, Point
LineString([Point(0, 0), Point(1, 1)])
```

Is this behaviour normal, or something is wrong with my setup?
I can provide more details if necessary.

- OS: Windows 8.1 Pro
- Browser Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)
- JupyterLab Version 0.32.0

**Comment by jasongrout** [comment]
It works fine for me in the latest JLab release, 0.35.4. Can you try upgrading?

<img width="472" alt="Screen Shot 2019-03-28 at 8 02 06 AM" src="https://user-images.githubusercontent.com/192614/55168302-81593080-516a-11e9-85c2-bb06759a53fe.png">

**Comment by LostFan123** [comment]
Updating to Version 0.35.4 solved the issue. Thank you!
