### ISSUE TITLE
Cannot download files after JL update

### ISSUE THREAD

**Issue by pavelatb** [jupyterlab/jupyterlab#6149]
Hello,

I've faced a download issue after the most resent version update.

More specifically, updated from 35.3 to 35.4 on Google Cloud Platform (Linux 18), updated all libraries (with "conda update --all"), and since that time I've been getting the following messages when "right-click"->"download file"
- Blocking request with no referer
- 403 GET <path-filename (my IP address)> : Blocking request from unknown origin
- 403 GET <path-filename (my IP address)> : 23.92ms referer=None
and cannot download the files.

I was trying Chrome, Opera, Firefox on Mac and Win-10 computers, and the outcome is the same. 

Creating a new instance from a snapshot with 35.3 version demonstrates positive results and everything works well.

Any advice how to fix the issue.
Thank you!

**Comment by billpku** [comment]
Same issue.
I still cannot find a good solution, but if I use Safari in Mac, I can download the file.
Maybe you can have a try.

**Comment by pavelatb** [comment]
Thanks for the advice, I'll give it a try.
As for now, I've rolled back to the 35.3 - it works well with all browsers and systems.

**Comment by b0noI** [comment]
Same issue, Download file works only on Safari. Rolling back jupyterlab package to 35.3 does not help.

**Comment by b0noI** [comment]
broken package that causing this bug: notebook
affected versions:
* 5.7.6
* 5.7.7
* 5.7.8 - latest (released on Apr 1st)

latest version without the bug: notebook-5.7.5

**Comment by b0noI** [comment]
reverting to 5.7.5 helps

**Comment by b0noI** [comment]
I also can confirm that notebook==5.7.5 work correctly with the latest 35.4, have tested it with the GCP Deep Learning VM m23, everything works after downgrading notebook package.

**Comment by billpku** [comment]
> I also can confirm that notebook==5.7.5 work correctly with the latest 35.4, have tested it with the GCP Deep Learning VM m23, everything works after downgrading notebook package.

@b0noI 
Thank you!
With you advice, I give it a try:
First: pip install jupyterlab==0.35.3
Then: pip install jupyter notebook==5.7.5

It works! I can down file again with jupyterlab in Chrome.
Thank you!

**Comment by fcollonval** [comment]
Hello,
I narrowed down the root cause in commit:
https://github.com/jupyter/notebook/commit/d7becafd593c2958d8a241928412ddf4ba801a42

This due to the addition of more validation:
https://github.com/jupyter/notebook/blob/d7becafd593c2958d8a241928412ddf4ba801a42/notebook/files/handlers.py#L38-L40

One important note is that the download still works in the classical notebook. But the code in the frontend in the classical notebook is different that the one in JLab.

**notebook** uses `window.open`:
```js
window.open(utils.url_path_join(that.base_url, 'files', utils.encode_uri_components(item_path)) + '?download=1', IPython._target);
```
https://github.com/jupyter/notebook/blob/f759e4d3beb9719e9deb4cde6691c2f135b6eae2/notebook/static/tree/js/notebooklist.js#L1119-L1130

**jlab** uses `element.click()`:
https://github.com/jupyterlab/jupyterlab/blob/c0e9eb94668832d1208ad3b00a9791ef181eca4c/packages/filebrowser/src/model.ts#L320-L330

**Comment by saulshanabrook** [comment]
@fcollonval Thanks for hunting this down!

I am looking at the [git blame](https://github.com/jupyterlab/jupyterlab/blame/c0e9eb94668832d1208ad3b00a9791ef181eca4c/packages/filebrowser/src/model.ts#L319) for these lines, to try to see why did it like this in the first place. 

Ah it looks like [there has been a change here](https://github.com/jupyterlab/jupyterlab/commit/850fe42f38210a72f7942ffeb5c5617817cacb08) recently to update this file. If you update to the latest prerelease of JupyterLab, does this problem go away? `pip install -U --pre jupyterlab`

**Comment by fcollonval** [comment]
@saulshanabrook thank you for pointing me out the modification. I can confirm that with JupyterLab 1.0.0.a3 on Chrome 73, download is restored. And the JupyterLab code is acting as the classical notebook (i.e. the to-be-downloaded file is opened in a new tab).

For me this can be closed.

**Comment by jasongrout** [comment]
Thanks!
