### ISSUE TITLE
Suggestion for highlighting in markdown files

### ISSUE THREAD

**Issue by jonathan-durbin** [jupyterlab/jupyterlab#6150]
I sometimes write paragraphs that are part of a bullet point (within a markdown file). I like using the markdown preview function in jupyter, and the text highlighting is also a plus. 

I recently started writing paragraphs with sentences on separate lines to stay organized and more easily see differences when looking through git commits. The text coloring does not continue on to other lines that are part of the same bullet point, however. I have an image to help illustrate my point below.

![md_bullet_coloring](https://user-images.githubusercontent.com/31511197/55249053-91801700-5221-11e9-8989-4e877727fc49.png)

This is probably a minor issue, but nonetheless a feature that would be nice if it were improved! I searched for a relevant issue, but couldn't find one.

**Comment by jasongrout** [comment]
Thanks! We're using standard CodeMirror here. Can you see if you can replicate the issue using upstream CodeMirror at https://codemirror.net/mode/gfm/index.html ?

**Comment by jonathan-durbin** [comment]
It looks like the same issue appears. 

![md_colored_lists_codemirror](https://user-images.githubusercontent.com/31511197/55254247-c4c8a300-522d-11e9-8669-e083f618cc1d.png)

**Comment by jasongrout** [comment]
Sounds like this is an issue to file with CodeMirror, then.

**Comment by jasongrout** [comment]
Would you file an issue there? https://github.com/codemirror/CodeMirror

**Comment by jonathan-durbin** [comment]
Sure thing. I'll close this issue, then.
