### ISSUE TITLE
Custom kernel not showing output

### ISSUE THREAD

**Issue by colombod** [jupyterlab/jupyterlab#6151]
I am developing a custom kernel, I get output printed in jupyter notebooks outside of jupyter lab but nothing on the screen when using console or notebook inside the jupyter lab. I am using the wire protocol from jupyter kernel development documentation.

**Comment by jasongrout** [comment]
Do you see any js errors? Can you capture a simple interaction message stream (execution request message, messages you are sending back) and post it here?

**Comment by colombod** [comment]
I see missing metadata error, not sure what should that field of display data contain?

**Comment by colombod** [comment]
Found it, should be empty, not null.
Thank you
