### ISSUE TITLE
Open JupyterLab terminal from a notebook

### ISSUE THREAD

**Issue by scottwsides** [jupyterlab/jupyterlab#6158]
I'd like to have a command or link in a JupyterLab notebook that opens a JupyterLab terminal tab... and if possible execute a python script in that terminal. This python script ssh-es to a remote machine and I want to be in a terminal when this script is executed.

Is this possible? Thanks!

**Comment by tgeorgeux** [comment]
Hi @scottwsides, thanks for reaching out, can you help me understand the 'why?' behind this request? 

For a little bit of background, if you launch JupyterLab, you can open a notebook (associated with a kernel), a terminal (not associated with a kernel), a console (associated with a kernel), a text file (not associated with a kernel) or a variety of other activities. 

I'm not sure how much this answers your specific scenario, if I had a bit more background I may be able to offer more help. :)

**Comment by scottwsides** [comment]
I know how to open notebook, terminal, and console through the jupyterlab gui. It would helpful for a particular workflow if there was a programatic way (from a jupyterlab notebook) of opening a terminal tab (and executing a script if possible). I have a notebook that builds a remote cluster, and I want a user to easily see a terminal open after that.

**Comment by scottwsides** [comment]
Any word on this? Is it clear what functionality I need... or should I provide more details?

**Comment by jasongrout** [comment]
Sorry, a lot of us are heads-down getting the next prerelease out. There technically is a way to make an html link that executes a JupyterLab command, but that (a) makes your notebook very specific to only working in JupyterLab, breaking the portability of the notebook, and (b) the functionality may go away, as some of us see it as a questionable idea to expose executing JupyterLab commands through an HTML link. However, if you want to use it at your own risk:

```python
from IPython.display import HTML
HTML('<a href="", data-commandlinker-command="terminal:create-new">Test command</a>')
```

**Comment by scottwsides** [comment]
That worked. One other thing, can a command be passed to the terminal to startup when it opens?

**Comment by jasongrout** [comment]
args can be passed to the command with the `data-commandlinker-args` attribute. It looks like the new terminal command does not support passing in an initial command in its args: https://github.com/jupyterlab/jupyterlab/blob/master/packages/terminal-extension/src/index.ts#L261

**Comment by ian-r-rose** [comment]
I recently removed that argument for precisely the reason you suggest @jasongrout: https://github.com/jupyterlab/jupyterlab/pull/5916

**Comment by scottwsides** [comment]
Sorry to be dense... but where exactly would the command to execute in the
newly opened terminal go? Is it another comma separate command? Is it
semi-colon separated after the terminal:create-new ? eg

HTML('<a href="",
data-commandlinker-command="terminal:create-new","ls">Open a terminal</a>')
or
HTML('<a href="", data-commandlinker-command="terminal:create-new; ls">Open
a terminal</a>')
or
HTML('<a href="", data-commandlinker-command="terminal:create-new",
data-commandlinker-command="ls">Open a terminal</a>')

or something else?

*Dr. Scott W Sides*

(303) 718-7028

**Comment by jasongrout** [comment]
The takeaway from our conversation above is that it is not possible to specify an initial command for a terminal created from JupyterLab. We removed the argument because we were uncomfortable with the security implications (for example, someone could give you a workspace layout that included executing commands in your terminal before you had a chance to review them).

**Comment by scottwsides** [comment]
Ah, sorry. I thought it was merely not recommended... not impossible.
Understood, thanks!
*Dr. Scott W Sides*
(303) 718-7028

**Comment by scottwsides** [comment]
I'm working around the lack of programatic access with Terminal windows in a very hacky way, but I can get it to work for now. Will future versions of JupyterLab expose more direct access to the Terminals? This would be a very nice feature. After you respond... you can close this one out. Thanks!

**Comment by jasongrout** [comment]
Until we sort out the security issues, we likely won't provide a command to execute code in the terminal, at least as part of the open terminal command. I'm definitely open to other approaches that may be able to satisfy the needs.

**Comment by jasongrout** [comment]
Thanks for bringing this up and having the discussion.

**Comment by dclong** [comment]
@scottwsides Would you share how you managed to it? I'm interested in how to open a file from the terminal.

**Comment by scottwsides** [comment]
What I needed was to execute a command upon opening the terminal (an ssh
command to a container running on a remote instance). What I do is a
complicated hack

1. a function in the notebook generates an html link that will open the
terminal as a tab in Jupyterlab
2. the same function dumps commands to run the ssh command to user's .bashrc
3. then when the link is clicked on these commands are executed
4. within the code to execute the ssh command that are appended to the
.bashrc are commands that restore the  user's old .bashrc so they can open
other terminals as needed.

This is uber-ugly... but for now it works. I understand the reasons for not
enabling in jupyterlab in an easier way... but it seems like this is
something *LOTS* of people want to do. It would be a nice piece of
functionality to have.

Cheers,
*Dr. Scott W Sides*
(303) 718-7028
