### ISSUE TITLE
Save the notebook from command line or line magic

### ISSUE THREAD

**Issue by PierreGuilmin** [jupyterlab/jupyterlab#6161]
Hi,

First big thanks for the incredible work you did with JupyterLab, I'm a huge fan! :clap:

Is there a way to **save a notebook** (I don't mean doing a checkpoint I mean actually saving the file on the hard drive) **using a command line or a line magic**? It would mimic the exact same behaviour of `File --> Save Notebook` or `Ctrl + S`.

As a use example I am currently using JupyterLab to create HTML standardised reports and I'd like the notebook to convert itself to HTML at the end of its execution (in the last cell) using something like:
```ipython
!jupyter nbconvert notebook.ipynb
```
The issue is that it exports the last saved version of the notebook and not the current version.

Any thoughts on this?

**Comment by jasongrout** [comment]
This may work once we move the document state to the server, but right now, the notebook lives in the browser and must be saved before it's available on the server.

**Comment by mrlocate-nutrien** [comment]
Aloha, 

I am having a similar issue, I want to save the file state right before the notebook is converted into a html report. 

Cheers,
Mark

**Comment by dnola** [comment]
Same issue here, would love it if there were a command/magic in Jupyter Lab to save the notebook similar to the hack you can use in regular Jupyter!

**Comment by NA-Dev** [comment]
+1 I am leaving a model training overnight, and want a way to save the notebook at the end before the cloud server times out and shuts itself off.

**Comment by kolibril13** [comment]
I was looking for something similar.
Here is a workaround (for mac, but might also work for windows+linux):
```py
#pip install keyboard
import keyboard
keyboard.press_and_release('command+s')
```

**Comment by krassowski** [comment]
Thanks @kolibril13. Another approach is to use [ipylab](https://github.com/jtpio/ipylab):

```python
from ipylab import JupyterFrontEnd

app = JupyterFrontEnd()
app.commands.execute('docmanager:save')
```

And yet another way is to trigger <kbd>ctrl</kbd> + <kbd>s</kbd> from JavaScript as in https://stackoverflow.com/a/66911341/6646912 (but this is very hacky and will likely break at some point in the future, so I would not recommend this one).

**Comment by kolibril13** [comment]
Thanks, @krassowska! `app.commands.execute('docmanager:save')` does exactly what it should do and is much more elegant than my workaround.

**Comment by PierreGuilmin** [comment]
Thanks to you both @krassowski and @kolibril13, using `pylab` indeed looks like the best approach. Closing the issue!
