### ISSUE TITLE
Question: app_dir real path

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#6166]
Hi,

Why does app_dir [resolve to the real path](https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/commands.py#L91) before being used?

We have a usecase where we'd like to build a new app_dir on the side then update a symlink atomically. This does not work today as app_dir will contain the real path and not the path we passed in.

Thanks for your help!

**Comment by xmnlab** [comment]
@mlucool 

could `jupyter-lab` (instead of `jupyter lab`) command work for you?

**Comment by mlucool** [comment]
I am not sure how that would help. A few places in lab call `get_app_dir` which resolves the directory we put into the config instead of passing it as is.

More explicit example:
1. Build an appdir (lets call this ad1)
2. Create a symlink to ad1 (myappdir->ad1) and set your appdir in the config to the symlink (myappdir) and restart your jupyter server
3. Copy the whole appdir directory into something with a different name (cp -r ad1 ad2). Update the symlink to point to this new directory (myappdir ->ad2)  and remove the previous real directory (rm -rf ad1). Do NOT restart the server.
4. Refresh a lab page. Things won't work because it looks for assets in the real path.

**Comment by xmnlab** [comment]
@mlucool I could replicated that. thanks for the explanation. I will take a look into that.

**Comment by saulshanabrook** [comment]
@bollwyvl @blink1073 From what I can tell on the git blame, it looks like you two touched these lines. Before I go and start removing `osp.realpath` from places, do you remember any background around why you resolve symlinks early?

**Comment by jasongrout** [comment]
Also, CC @minrk since he generally has very sage advice about such things.

**Comment by blink1073** [comment]
IIIRC I did this and meant to use abspath

**Comment by saulshanabrook** [comment]
OK I switched all uses of `realpath` to `abspath` in `jupyterlab/commands.py` and it seems to fix this use case.
