### ISSUE TITLE
1.0.0-alpha.4 release

### ISSUE THREAD

**Issue by tibdex** [jupyterlab/jupyterlab#6175]
Hi, 

I [asked on gitter](https://gitter.im/jupyter/jupyter), [watched the latest meetings](https://www.youtube.com/user/ipythondev/videos), and [looked at the milestones](https://github.com/jupyterlab/jupyterlab/milestones) but I couldn't find information about when the next alpha is planned to be released. 1.0.0-alpha.0 to 1.0.0-alpha.3 [were all released on February 5](https://www.npmjs.com/package/@jupyterlab/application?activeTab=versions) but since then no other releases have been made.

Is there a date planned for 1.0.0-alpha.4?

I'm asking because I'm building a JupyterLab extension in React and the currently stable version of JupyterLab doesn't unmount React components (see https://github.com/jupyterlab/jupyterlab/issues/5766) so it makes the UI laggy after some time. I would also like to use React Hooks (see https://github.com/jupyterlab/jupyterlab/pull/6057).

Thanks!

**Comment by jasongrout** [comment]
We're down to a handful of issues: https://github.com/jupyterlab/jupyterlab/pulls?q=is%3Aopen+is%3Apr+label%3Atag%3APre-Release. We're hoping to get the next pre-release out this week.

**Comment by jasongrout** [comment]
(The regular JLab dev meeting notes are at https://paper.dropbox.com/doc/JLab-Dev-Meeting-Minutes-2019--Aa5xI8HWXk3~wWYMG2CSv5h_Ag-Lj0P4kI2JrbA0eXHZSdY5 )

**Comment by tibdex** [comment]
Perfect! Thanks a lot Jason!
