### ISSUE TITLE
extend/override connection lost for jupyterhub

### ISSUE THREAD

**Issue by minrk** [jupyterlab/jupyterlab#6176]
In JupyterHub, there's a typical cause for "Connection Lost" (server stopped) and an action to take (go here to restart it). It would be useful to be able to customize the Connection Lost event when running with JupyterHub to point to the resolution, rather than the generic message that doesn't know how to restart the server. Does such a mechanism already exist?

cf https://github.com/jupyterhub/jupyterlab-hub/pull/84

**Comment by jasongrout** [comment]
@minrk, is this the dialog you are trying to override?

https://github.com/diagram-codesprint/jupyterlab/blob/023cddaf7df1e36919bbef02d0457eb1ec8e58cc/packages/filebrowser/src/browser.ts#L252-L256

**Comment by vidartf** [comment]
What would we say would be the recommended steps for juyterlab-hub to use the extension point from #6399? Would their install instructions need to include a step to disable the core plugin, or is this something that can be configured via a deploy step?

**Comment by ian-r-rose** [comment]
I *think* that extensions which override default tokens take precedence, though maybe we should be more explicit than that. @afshin can you comment on the resolution order of tokens?

**Comment by vidartf** [comment]
As far as I can read from the phosphor code, [trying to re-register a token will throw an exception](https://github.com/phosphorjs/phosphor/blob/f16d13f11b433089cccca82edc2e16007be581aa/packages/application/src/index.ts#L204-L207). In Lab, this seems to be side-stepped such that "first come" will be used, and subsequent registrations will have their errors suppressed, but stored:

https://github.com/jupyterlab/jupyterlab/blob/930420a55914f349fe1fa6c0b7c068d20a257a5c/packages/application/src/lab.ts#L141-L157

I'm not sure if I understand in which order extensions are loaded.

**Comment by ian-r-rose** [comment]
Re-registering the same *id* will throw an error, but providing an overriding *token* is okay, provided it has a different ID.

**Comment by ian-r-rose** [comment]
See, for instance, [this](https://github.com/phosphorjs/phosphor/blob/f16d13f11b433089cccca82edc2e16007be581aa/packages/application/src/index.ts#L191-L202) note.

**Comment by vidartf** [comment]
I'm confused, won't jupyter hub have to use *the same* token?

**Comment by vidartf** [comment]
Ah, I see now, plugin ID is different from token of course. Phosphor uses [last-write wins logic](https://github.com/phosphorjs/phosphor/blob/f16d13f11b433089cccca82edc2e16007be581aa/packages/application/src/index.ts#L217). I'm still missing the puzzle piece about module sort order to get the full picture though.

![image](https://user-images.githubusercontent.com/510760/58489443-33a97600-8163-11e9-985e-0a9dc5107097.png)

**Comment by ian-r-rose** [comment]
There is a distinction between token and plugin ids. It will provide the same token, and I think that is okay.

**Comment by ian-r-rose** [comment]
Yeah, it's was my impression that extensions are loaded later, If that is not the case, I think we should make it the case.

**Comment by vidartf** [comment]
I think all extensions are either sorted alphabetically or in random order.

Still, I am now thinking that maybe it would have been cleaner to implement this extension point as a method on `app`. There might have been some cons for that approach though?

**Comment by vidartf** [comment]
I opened https://github.com/jupyterlab/jupyterlab/issues/6434 for a more constructive suggestion for this.
