### ISSUE TITLE
Width style for a FloatProgress widget

### ISSUE THREAD

**Issue by scottwsides** [jupyterlab/jupyterlab#6178]
In your description of adjusting the labels on a widget

<img width="699" alt="Screen Shot 2019-04-09 at 6 18 31 PM" src="https://user-images.githubusercontent.com/13578795/55843209-52d93f00-5af4-11e9-830d-d96a10a46ec5.png">

Could you define exactly what you mean by 'widget width'. Without using the HBox[Label.....]
construction (its not working for me) how would you edit the style = '...' above to get both the description and the widget itself wider. Also, what is the value of 'initial'? BTW, in the title I say 'FloatProgress' bar but I imagine the same solution for the case in the image above will apply.

Thanks,

**Comment by jasongrout** [comment]
This is the issue tracker for JupyterLab, and this question is about ipywidgets. Would you mind copying this issue over to the ipywidgets repo at https://github.com/jupyter-widgets/ipywidgets and we can answer there? That way the answer will be easier to find in the future for others.

**Comment by scottwsides** [comment]
Done, thanks!

*Dr. Scott W Sides*
(303) 718-7028

**Comment by vidartf** [comment]
(https://github.com/jupyter-widgets/ipywidgets/issues/2364)
