### ISSUE TITLE
CodeMirror cursor invisible

### ISSUE THREAD

**Issue by rhsmits91** [jupyterlab/jupyterlab#6179]
Hi all,

See this comment:
https://github.com/jupyterlab/jupyterlab/pull/5898

This update is making the cursor invisible for jupyter lab 0.35.4 on various tested browsers and different resolutions (IE, Chrome, Chromium, FF).

When I use chrome's editor DevTools and change `var(--jp-code-cursor-width0)` for `CodeMirror-cursor` to `1.4px` (back to what it was), all works fine again...

Thanks,

Ron

**Comment by jasongrout** [comment]
Can you check if this is still a problem in jlab master? You can test it at https://mybinder.org/v2/gh/jupyterlab/jupyterlab/master?urlpath=lab-dev/

**Comment by jasongrout** [comment]
(note that the PR you point out was merged after 0.35.4, so it's probably not the cause of a problem in 0.35.4)

**Comment by rhsmits91** [comment]
as a quick fix this works:

```python
display(HTML(
        """
        <style>
        :root {
            --jp-code-cursor-width0: 1.4px  !important
        }
        </style>
        """
    ))
```

**Comment by rhsmits91** [comment]
@jasongrout : sorry only just see your responses (hadn't refreshed this page) but will check this now

**Comment by rhsmits91** [comment]
seems to be solved @jasongrout
