### ISSUE TITLE
Conda update causes Name or service not known error

### ISSUE THREAD

**Issue by vgensini** [jupyterlab/jupyterlab#6180]
After updating conda yesterday, I now find that my personal jupyter-lab server cannot start due to a socket error below. I have all needed settings in my `jupyter_notebook_config.py` file (it was working fine for many months prior to yesterday). 

> jupyter-lab
[I 19:35:40.600 LabApp] [nb_conda_kernels] enabled, 10 kernels found
Traceback (most recent call last):
  File "/home/vgensini/Programs/anaconda2/bin/jupyter-lab", line 11, in <module>
    sys.exit(main())
  File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 1628, in initialize
    self.init_webapp()
  File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 1378, in init_webapp
    self.jinja_environment_options,
  File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 159, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 252, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 867, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

`jupyter notebook --version` 5.7.4

Any ideas what is going on here? Is this at all similar to: https://github.com/jupyterlab/jupyterlab/issues/5385

**Comment by jasongrout** [comment]
Was tornado upgraded? Can you make sure that you have tornado version 5 something, and not tornado 6?

**Comment by vgensini** [comment]
@jasongrout 

`conda list`

tornado                   5.1.1            py27h7b6447c_0

**Comment by jasongrout** [comment]
Okay, that wasn't it, then. A few more guesses at helpful things to try:

* does `jupyter notebook` work?
* did you try rebooting?

**Comment by vgensini** [comment]
@jasongrout 

Same error for `jupyter notebook`. Reboot did nothing. `conda list` pasted below. 

`conda --version`  conda 4.6.11

`conda list`

# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py27h08a7f0c_0
_nb_ext_conf              0.4.0                    py27_1
alabaster                 0.7.12                   py27_0
anaconda                  custom           py27h4a00acb_0
anaconda-client           1.7.2                    py27_0
anaconda-navigator        1.8.4                    py27_0
anaconda-project          0.8.2                    py27_0
asn1crypto                0.24.0                   py27_0
astroid                   1.6.5                    py27_0
astropy                   2.0.9            py27hdd07704_0
atomicwrites              1.2.1                    py27_0
attrs                     18.2.0           py27h28b3542_0
babel                     2.6.0                    py27_0
backports                 1.0                      py27_1
backports.functools_lru_cache 1.5                      py27_1
backports.os              0.1.1                    py27_0
backports.shutil_get_terminal_size 1.0.0                    py27_2
backports_abc             0.5              py27h7b3c97b_0
beautifulsoup4            4.6.3                    py27_0
bitarray                  0.8.3            py27h14c3975_0
bkcharts                  0.2              py27h241ae91_0
blas                      1.0                         mkl
blaze                     0.11.3                   py27_0
bleach                    3.0.2                    py27_0
blosc                     1.14.4               hdbcaa40_0
bokeh                     1.0.2                    py27_0
boto                      2.49.0                   py27_0
bottleneck                1.2.1            py27h035aef0_1
bzip2                     1.0.6                h14c3975_5
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.14.12              h8948797_3
cdecimal                  2.3              py27h14c3975_3
certifi                   2019.3.9                 py27_0    conda-forge
cffi                      1.11.5           py27he75722e_1
chardet                   3.0.4                    py27_1
click                     7.0                      py27_0
cloudpickle               0.6.1                    py27_0
clyent                    1.2.2                    py27_1
colorama                  0.4.1                    py27_0
conda                     4.6.11                   py27_0    conda-forge
conda-build               3.0.27           py27hff9f855_0
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0            py27hf052a9d_0
configparser              3.5.0            py27h5117587_0
contextlib2               0.5.5            py27hbf4c468_0
cryptography              2.4.2            py27h1ba5d50_0
curl                      7.63.0            hbc83047_1000
cycler                    0.10.0           py27hc7354d3_0
cython                    0.29.2           py27he6710b0_0
cytoolz                   0.9.0.1          py27h14c3975_1
dask                      1.0.0                    py27_0
dask-core                 1.0.0                    py27_0
datashape                 0.5.4                    py27_1
dbus                      1.13.2               h714fa37_1
decorator                 4.3.0                    py27_0
defusedxml                0.5.0                    py27_1
distributed               1.25.1                   py27_0
docutils                  0.14             py27hae222c1_0
entrypoints               0.2.3                    py27_2
enum34                    1.1.6                    py27_1
et_xmlfile                1.0.1            py27h75840f5_0
expat                     2.2.6                he6710b0_0
fastcache                 1.0.2            py27h14c3975_2
filelock                  3.0.10                   py27_0
flask                     1.0.2                    py27_1
flask-cors                3.0.7                    py27_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_1
fribidi                   1.0.5                h7b6447c_0
funcsigs                  1.0.2            py27h83f16ab_0
functools32               3.2.3.2                  py27_1
future                    0.17.1                   py27_0
futures                   3.2.0                    py27_0
get_terminal_size         1.0.0                haa9412d_0
gevent                    1.3.7            py27h7b6447c_1
glib                      2.56.2               hd408876_0
glob2                     0.6                      py27_1
gmp                       6.1.2                h6c8ec71_1
gmpy2                     2.0.8            py27h10f8cd9_2
graphite2                 1.3.12               h23475e2_2
greenlet                  0.4.15           py27h7b6447c_0
grin                      1.2.1                    py27_4
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
h5py                      2.8.0            py27h989c5e5_3
harfbuzz                  1.8.8                hffaf4a1_0
hdf5                      1.10.2               hba1933b_1
heapdict                  1.0.0                    py27_2
html5lib                  1.0.1                    py27_0
icu                       58.2                 h9c2bf20_1
idna                      2.8                      py27_0
imageio                   2.4.1                    py27_0
imagesize                 1.1.0                    py27_0
importlib_metadata        0.6                      py27_0
intel-openmp              2019.1                      144
ipaddress                 1.0.22                   py27_0
ipykernel                 4.10.0                   py27_0
ipython                   5.8.0                    py27_0
ipython_genutils          0.2.0            py27h89fb69b_0
ipywidgets                7.4.2                    py27_0
isort                     4.3.4                    py27_0
itsdangerous              1.1.0                    py27_0
jbig                      2.1                  hdba287a_0
jdcal                     1.4                      py27_0
jedi                      0.13.2                   py27_0
jinja2                    2.10                     py27_0
jpeg                      9b                   h024ee3a_2
jsonschema                2.6.0            py27h7ed5aa4_0
jupyter                   1.0.0                    py27_7
jupyter_client            5.2.4                    py27_0
jupyter_console           5.2.0                    py27_1
jupyter_core              4.4.0                    py27_0
jupyterlab                0.33.11                  py27_0
jupyterlab_launcher       0.11.2           py27h28b3542_0
kiwisolver                1.0.1            py27hf484d3e_0
krb5                      1.16.1               h173b8e3_7
lazy-object-proxy         1.3.1            py27h14c3975_2
libarchive                3.3.3                h5d8350f_5
libcurl                   7.63.0            h20c2e04_1000
libedit                   3.1.20170329         h6b74fdf_2
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran-ng            7.3.0                hdf63c60_0
liblief                   0.9.0                h7725739_1
libpng                    1.6.35               hbc83047_0
libsodium                 1.0.16               h1bed415_0
libssh2                   1.8.0                h1ba5d50_4
libstdcxx-ng              8.2.0                hdf63c60_1
libtiff                   4.0.9                he85c1e1_2
libtool                   2.4.6                h7b6447c_5
libuuid                   1.0.3                h1bed415_2
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.8                h26e45fe_1
libxslt                   1.1.32               h1312cb7_0
linecache2                1.0.0                    py27_0
llvmlite                  0.26.0           py27hd408876_0
locket                    0.2.0            py27h73929a2_1
lxml                      4.2.5            py27hefd8a0e_0
lz4-c                     1.8.1.2              h14c3975_0
lzo                       2.10                 h49e0be7_2
markupsafe                1.1.0            py27h7b6447c_0
matplotlib                2.2.3            py27hb69df0a_0
mccabe                    0.6.1                    py27_1
mistune                   0.8.4            py27h7b6447c_0
mkl                       2019.1                      144
mkl-service               1.1.2            py27he904b0f_5
mkl_fft                   1.0.6            py27hd81dba3_0
mkl_random                1.0.2            py27hd81dba3_0
more-itertools            4.3.0                    py27_0
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.1                hdf1c602_3
mpmath                    1.1.0                    py27_0
msgpack-python            0.5.6            py27h6bb024c_1
multipledispatch          0.6.0                    py27_0
navigator-updater         0.2.0                    py27_0
nb_anacondacloud          1.4.0                    py27_0
nb_conda                  2.2.1            py27hec22543_0
nb_conda_kernels          2.1.0                    py27_0
nbconvert                 5.4.0                    py27_1
nbformat                  4.4.0            py27hed7f2b2_0
nbpresent                 3.0.2            py27hcce4ef4_1
ncurses                   6.1                  he6710b0_1
networkx                  2.2                      py27_1
nltk                      3.4                      py27_1
nose                      1.3.7                    py27_2
notebook                  5.7.4                    py27_0
numba                     0.41.0           py27h962f231_0
numexpr                   2.6.8            py27h9e4a6bb_0
numpy                     1.15.4           py27h7e9f1db_0
numpy-base                1.15.4           py27hde5b4d6_0
numpydoc                  0.8.0                    py27_0
odo                       0.5.1            py27h9170de3_0
olefile                   0.46                     py27_0
openpyxl                  2.5.12                   py27_0
openssl                   1.1.1b               h14c3975_1    conda-forge
packaging                 18.0                     py27_0
pandas                    0.23.4           py27h04863e7_0
pandoc                    1.19.2.1             hea2e7c5_1
pandocfilters             1.4.2                    py27_1
pango                     1.42.4               h049681c_0
parso                     0.3.1                    py27_0
partd                     0.3.9                    py27_0
patchelf                  0.9                  he6710b0_3
path.py                   11.5.0                   py27_0
pathlib2                  2.3.3                    py27_0
patsy                     0.5.1                    py27_0
pcre                      8.42                 h439df22_0
pep8                      1.7.1                    py27_0
pexpect                   4.6.0                    py27_0
pickleshare               0.7.5                    py27_0
pillow                    5.3.0            py27h34e0f95_0
pip                       18.1                     py27_0
pixman                    0.34.0               hceecf20_3
pkginfo                   1.4.2                    py27_1
pluggy                    0.8.0                    py27_0
ply                       3.11                     py27_0
proj4                     5.1.0                h470a237_1    conda-forge
prometheus_client         0.5.0                    py27_0
prompt_toolkit            1.0.15           py27h1b593e1_0
psutil                    5.4.8            py27h7b6447c_0
ptyprocess                0.6.0                    py27_0
py                        1.7.0                    py27_0
py-lief                   0.9.0            py27h7725739_1
py3grads                  1.0                      pypi_0    pypi
pycairo                   1.18.0           py27h2a1e443_0
pycodestyle               2.4.0                    py27_0
pycosat                   0.6.3            py27h14c3975_0
pycparser                 2.19                     py27_0
pycrypto                  2.6.1            py27h14c3975_9
pycurl                    7.43.0.2         py27h1ba5d50_0
pyflakes                  2.0.0                    py27_0
pygments                  2.3.1                    py27_0
pylint                    1.9.2                    py27_0
pyodbc                    4.0.25           py27he6710b0_0
pyopenssl                 18.0.0                   py27_0
pyparsing                 2.3.0                    py27_0
pyqt                      5.9.2            py27h05f1152_2
pysocks                   1.6.8                    py27_0
pytables                  3.4.4            py27ha205bf6_0
pytest                    4.0.2                    py27_0
python                    2.7.15               h9bab390_6
python-dateutil           2.7.5                    py27_0
python-libarchive-c       2.8                      py27_6
pytz                      2018.7                   py27_0
pywavelets                1.0.1            py27hdd07704_0
pyyaml                    3.13             py27h14c3975_0
pyzmq                     17.1.2           py27h14c3975_0
qt                        5.9.7                h5867ecd_1
qtawesome                 0.5.3                    py27_0
qtconsole                 4.4.3                    py27_0
qtpy                      1.5.2                    py27_0
readline                  7.0                  h7b6447c_5
requests                  2.21.0                   py27_0
rope                      0.11.0                   py27_0
ruamel_yaml               0.15.46          py27h14c3975_0
scandir                   1.9.0            py27h14c3975_0
scikit-image              0.14.1           py27he6710b0_0
scikit-learn              0.20.1           py27hd81dba3_0
scipy                     1.1.0            py27h7c811a0_2
seaborn                   0.9.0                    py27_0
send2trash                1.5.0                    py27_0
setuptools                40.6.3                   py27_0
simplegeneric             0.8.1                    py27_2
singledispatch            3.4.0.3          py27h9bcb476_0
sip                       4.19.8           py27hf484d3e_0
six                       1.12.0                   py27_0
snappy                    1.1.7                hbae5bb6_3
snowballstemmer           1.2.1            py27h44e2768_0
sortedcollections         1.0.1                    py27_0
sortedcontainers          2.1.0                    py27_0
sphinx                    1.8.2                    py27_0
sphinxcontrib             1.0                      py27_1
sphinxcontrib-websupport  1.1.0                    py27_1
spyder                    3.3.2                    py27_0
spyder-kernels            0.3.0                    py27_0
sqlalchemy                1.2.15           py27h7b6447c_0
sqlite                    3.26.0               h7b6447c_0
ssl_match_hostname        3.5.0.1                  py27_2
statsmodels               0.9.0            py27h035aef0_0
subprocess32              3.5.3            py27h7b6447c_0
sympy                     1.3                      py27_0
tblib                     1.3.2            py27h51fe5ba_0
terminado                 0.8.1                    py27_1
testpath                  0.4.2                    py27_0
tk                        8.6.8                hbc83047_0
toolz                     0.9.0                    py27_0
tornado                   5.1.1            py27h7b6447c_0
tqdm                      4.28.1           py27h28b3542_0
traceback2                1.4.0                    py27_0
traitlets                 4.3.2                 py27_1000    conda-forge
typing                    3.6.6                    py27_0
unicodecsv                0.14.1           py27h5062da9_0
unittest2                 1.1.0                    py27_0
unixodbc                  2.3.7                h14c3975_0
urllib3                   1.24.1                   py27_0
wcwidth                   0.1.7            py27h9e3e1ab_0
webencodings              0.5.1                    py27_1
werkzeug                  0.14.1                   py27_0
wheel                     0.32.3                   py27_0
widgetsnbextension        3.4.2                    py27_0
wrapt                     1.10.11          py27h14c3975_2
wurlitzer                 1.0.2                    py27_0
xlrd                      1.2.0                    py27_0
xlsxwriter                1.1.2                    py27_0
xlwt                      1.3.0            py27h3d85d97_0
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zeromq                    4.2.5                hf484d3e_1
zict                      0.1.3                    py27_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0

**Comment by jasongrout** [comment]
It sounds like it's probably an issue best solved at the notebook server level, not JupyterLab. I'd try (a) posting an issue on the jupyter notebook repo, and (b) seeing if upgrading the notebook to 5.7.8 helps with the notebook working. Once the notebook server is working, my guess is that JupyterLab will work.

**Comment by vgensini** [comment]
Thanks @jasongrout . I've updated to 5.7.8 with no luck. Issue cross-posted to the jupyter notebook repo.

**Comment by vgensini** [comment]
Problem solved. In your jupyter_notebook_config.py file:

Change `c.NotebookApp.ip = '*'`

to:

`c.NotebookApp.ip = '0.0.0.0'`
