### ISSUE TITLE
flat json on editor

### ISSUE THREAD

**Issue by enotspe** [jupyterlab/jupyterlab#6185]
json is on flat format on editor, don´t know why 
![json jupyter editor](https://user-images.githubusercontent.com/47488630/55960700-ee70c980-5c32-11e9-87ab-2dda227171e8.png)

**Comment by jasongrout** [comment]
I think it's just showing you the file exactly as it is. What are you expecting?

**Comment by saulshanabrook** [comment]
@enotspe If you right click on the file you should be able to open it with the JSON editor, which is a tree view.

**Comment by jasongrout** [comment]
Closing as answered. Please comment here if you'd like to continue the discussion, though.
