### ISSUE TITLE
multiple versions of extensions found 

### ISSUE THREAD

**Issue by cocoaaa** [jupyterlab/jupyterlab#6187]
Hi, 

While installing the jupyterlab bqplot extension, I got multiple warnings saying "Multiple versions of @[some-extension-name] found:". Here is a part of the error message.

![image](https://user-images.githubusercontent.com/8037983/55973920-66db8880-5c3b-11e9-8da1-ff778e4030e7.png)

Is there a way to clean this up?

Thanks!

**Comment by jasongrout** [comment]
Is this still an issue?

**Comment by cocoaaa** [comment]
Not anymore, thanks!
