### ISSUE TITLE
Interrupt kernel can't interrupt python input() calls

### ISSUE THREAD

**Issue by aquirdTurtle** [jupyterlab/jupyterlab#6196]
**Describe the bug**
If I call `input()` (e.g. `name = input("What's your name?")`), I get the box in the output expecting me to type input. 
![image](https://user-images.githubusercontent.com/4393192/56064456-51478b00-5d2f-11e9-9f24-ea012a6cbd5f.png)

If try to interrupt the kernel while the code is still waiting for the input, the kernel fails to immediately interrupt until I enter input. 

![image](https://user-images.githubusercontent.com/4393192/56064496-720fe080-5d2f-11e9-8314-0b5eec219dc2.png)

After entering input, the input call raises an exception saying the kernel was interrupted.  
![image](https://user-images.githubusercontent.com/4393192/56064516-818f2980-5d2f-11e9-8666-6bd7867bb1b9.png)

Perhaps this itself is viewed okay behavior, but it causes a more serious problem if I run the input cell twice without entering input the first time. After the second execution, the code is still waiting for the first input call to finish, but jupyter has cleared the output, so it's not possible to finish the first input call, as I just have a screen like this:

![image](https://user-images.githubusercontent.com/4393192/56064607-c1eea780-5d2f-11e9-9817-bbc89c62ec1c.png)

And since interrupt doesn't work, the only option I can figure to break this is a complete kernel restart, which is of course less than ideal. 

**To Reproduce**

Open a new notebook, enter the text 
`name = input("What's your name?")`
in a cell. Execute, then without answering the query, try to interrupt.

**Expected behavior**
Kernel interrupt should successfully interrupt `input()` calls. 

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- JupyterLab [e.g. 0.34.1]

**Comment by jasongrout** [comment]
This may be a kernel issue. Does it work in the classic notebook?

**Comment by aquirdTurtle** [comment]
It doesn't work in the classic notebook either. I can repeat the exact same behavior. Should I repost this somewhere else? https://github.com/ipython/ipykernel/issues?

**Comment by jasongrout** [comment]
The ipykernel repo would be a good place to post an issue about this.
