### ISSUE TITLE
Use json5 for settings files

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6199]
We currently use comment-json (https://www.npmjs.com/package/comment-json) to do our parsing of settings files so that we can support comments. It looks like a much more popular way to have comments is to use the json5 library: https://www.npmjs.com/package/json5. Compare 39k downloads a week (comment-json) to 13 million downloads a week (json5)

Perhaps we should just switch to json5.

Here is some place we are using comment-json:

https://github.com/jupyterlab/jupyterlab/blob/33057bfba0ee13f89888dfac9b86970a26508324/packages/coreutils/src/settingregistry.ts#L6

https://github.com/jupyterlab/jupyterlab/blob/33057bfba0ee13f89888dfac9b86970a26508324/packages/coreutils/src/settingregistry.ts#L463 (and a few more places in the file)

CC @afshin

**Comment by ian-r-rose** [comment]
Somewhat besides the point, but I really like json5 and wish it were just JSON. I would never look at YAML again...

**Comment by blink1073** [comment]
In Python we have `setup.py` (executable config), `setup.cfg` (ini), `requirements.txt` (ini-like), and `pyproject.toml` (TOML, kind of an ini).  On almost every work project I've been on we've used `yaml`.   

My ideal world would just use `json5` for all the things.  `import json; json.dumps()` would have to work too...  /rant
