### ISSUE TITLE
Jupyter lab displays a blank screen in Internet Explorer

### ISSUE THREAD

**Issue by she-kingin** [jupyterlab/jupyterlab#6206]
I was using Mozilla Firefox as the default browser for opening Jupyter but recently had to change that to Internet Explorer for easy switching between tabs while I do my Python tutorials.

But now, when I try to open the Jupyter lab, after entering the password, it displays a blank screen, but the Jupyter Notebook opens fine.

**To Reproduce**

1. Go to 'Anaconder Navigator'
2. Click on 'Jupyter Lab'
3. See error

**Expected behavior**
The jupyter lab should run on Internet Explorer.

**Comment by saulshanabrook** [comment]
@she-kingin Thanks for opening this. We unfortunately [don't support internet explorer](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#supported-browsers) currently.

If you would like to add support, you would have to rebuild jupyterlab to account for the browser incompatibilities.
