### ISSUE TITLE
File browser toolbar / breadcrumbs UX

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#6207]
The file browser's breadcrumbs are a little unclear to me when I am in the root folder:

<img width="440" alt="unclear" src="https://user-images.githubusercontent.com/159529/56202335-b99db180-603a-11e9-82c9-25e34e370623.png">

Is there a way we could make it clearer visually?

It's possible it's just me and that we do not need to change this.

**Comment by mocquin** [comment]
Agree. 
Is there a reason the absolute path to the current is not displayed ? (being in the root folder or not)

**Comment by jasongrout** [comment]
In general, with the file contents manager, paths are always from the server root directory, not from some place on disk. Different contents managers (like the postgresql one) may have completely different ways of telling you the 'server root'.

Perhaps it's helpful to show a tooltip for the home icon giving whatever server root path was provided by the server?

For more context, we've had a discussion about whether the server should even send the server root to the frontend: https://github.com/jupyterlab/jupyterlab/issues/5313

**Comment by afshin** [comment]
I would propose maybe not showing the home icon until there's a sub-path as well, that way being in the root folder is just blank space and when there is a sub-path the home icon indicates root just as it does now. What do you think?

**Comment by ellisonbg** [comment]
I think it will be confusing to have the home icon appear/disappear. For 1.0, I would go with @jasongrout idea's of adding a tooltip. Also, is the home icon clickable? (I don't have lab installed here) I think it should be.

**Comment by saulshanabrook** [comment]
Darian's original point is that the home inon by itself is confusing, it looks like the icon overflowed from the top bar.

**Comment by timhoffm** [comment]
I think a line between them is fine (new colors are hard to do and it would add too much emphasis to the bread crubs). This is with the following CSS:

~~~
.jp-FileBrowser-toolbar.jp-Toolbar {
    border-bottom: var(--jp-border-width) solid var(--jp-border-color2);
}
~~~

![image](https://user-images.githubusercontent.com/2836374/59234592-d6df9e00-8bed-11e9-85ab-3652cd8c753a.png)

Note that the line does not fully extend to the edges because the toolbar has some margin. But I actually like that because that way the tools (buttons and the breadcrumbs) are still visually closer together and set apart from the column headers.
![image](https://user-images.githubusercontent.com/2836374/59234748-77ce5900-8bee-11e9-9448-cdd429e9d253.png)

**Comment by jasongrout** [comment]
Also related to #5256

**Comment by tgeorgeux** [comment]
I think the slash gives it immediate context. In my opinion, we should render the slash no matter which icon we use. I played around with a couple of different icons below.

This one mirrors the use of the new folder button above, and it gives some context that the folder is acting as your home directory, but is still a folder. The downside is, maybe the house is too small to view easily.
![Option 1](https://user-images.githubusercontent.com/22109376/59374440-b5230b80-8d00-11e9-85cf-e8aec503c32b.png)

This one is like the classic notebook (which I would say at this point is less confusing than what we have)
![Option 2](https://user-images.githubusercontent.com/22109376/59374441-b5230b80-8d00-11e9-9914-deb4b6c84a68.png)

**Comment by jasongrout** [comment]
I like the folder without the home icon!

**Comment by jasongrout** [comment]
We currently use a small angle bracket between directories in the breadcrumbs. If we use a slash in the breadcrumb, we should use it throughout the breadcrumb.

**Comment by tgeorgeux** [comment]
I agree, but the slash makes more sense than the angle bracket. It more clearly matches what is happening on your hard drive. User's mental model meeting our conceptual model is a good thing.

**Comment by jasongrout** [comment]
I like the slash better than the angle bracket. I'm just saying we should make sure to use it all through the path, not just at the beginning.

**Comment by tgeorgeux** [comment]
I am agreeing with you but using too many words. 👍

**Comment by tgeorgeux** [comment]
Closing this out per #6553.
