### ISSUE TITLE
Copy Shareable Link will include workspace info

### ISSUE THREAD

**Issue by bobmayuze** [jupyterlab/jupyterlab#6210]
When I clicked the 'Copy Shareable Link' on a ipynb file

When I clicked the 'Copy Shareable Link’ when I am in my personal workspace, the sahreable link seems to be having my workspace info included.

Here is an example of shareable link: 
```
foo.bar/lab/workspaces/myworkspace/tree/Untitled.ipynb
```

I’m sure adding git version control to the notebook will resolve this issue for other devs on the team. However, when I am trying to share this notebook to non-technical background ppl, it becomes a problem.

My solution rn is editing the link into 
```
foo.bar/tree/Untitled.ipynb
```

By deleting  **/lab/workspaces/myworkspace** , I get to open this notebook in tree mode instead of lab mode.

**Comment by agoose77** [comment]
NB [on Gitter](https://gitter.im/jupyterlab/jupyterlab?at=5cb691c2990feb4518b4d573) @ian-r-rose wrote
> We may want to consider adding an auto-redirect query to the shareable link
that way if that workspace is in use, it would automatically clone it and redirect to an unused workspace name
