### ISSUE TITLE
Simpler linking to local files

### ISSUE THREAD

**Issue by timhoffm** [jupyterlab/jupyterlab#6213]
I understand that linking to local files is possible in markdown cells like this:

~~~
See also [my_file.txt](my_file.txt)
~~~

Is there some simpler mechanism than stating the filename twice if I just want the exact linked name displayed?

For `http://`, links are automatically generated. Would it be reasonable to do the same for `file://`?

Alternatively, would it make sense to allow `[](my_file.txt)` and infer the link text from the link target?

**Comment by jasongrout** [comment]
Good question. What you're talking about here is extending and changing markdown, which is a much bigger community than JupyterLab or Jupyter. I don't think we want to make changes to Markdown, as the notebook would then not be portable across other frontends.

**Comment by jasongrout** [comment]
Closing as answered at our level. If you want to advocate for a change to markdown, I'd suggest participating in the CommonMark specification process: https://commonmark.org/. They say there:

>  The current version of the CommonMark spec is complete, and quite robust after a year of public feedback … but not quite final.
> With your help, we plan to announce a finalized 1.0 spec and test suite in 2019.

**Comment by jasongrout** [comment]
Perhaps https://spec.commonmark.org/0.29/#autolinks is useful?

**Comment by jasongrout** [comment]
Perhaps shortcut reference links are also useful to you: https://spec.commonmark.org/0.29/#shortcut-reference-link

**Comment by timhoffm** [comment]
Thanks for the hints. It seems that CommonMark does indeed not have a shortcut specification for my desired use case:

- https://spec.commonmark.org/0.29/#autolinks do only support absolute URIs and therefore cannot be used for a relative link to the file next to the notebook.
- https://spec.commonmark.org/0.29/#shortcut-reference-link do still need to define the link label and the link reference definition. The only difference is that you can split those two. This is not a simplification with respect to `[my_file.txt](my_file.txt)`.

Semi-OT: Are you not interacting with the markdown parsing in some way to get `[my_file.txt](my_file.txt)` link to `files/my_file.txt`?

**Comment by jasongrout** [comment]
We do modify the URLs that come back from the markdown parser to convert them to URLs that work in JupyterLab. There is an extension that provides this transformation for the system.

**Comment by timhoffm** [comment]
For reference: I've posted this to the [CommonMark discussion group](https://talk.commonmark.org/t/how-should-i-create-a-link-to-a-nearby-file-answered/2460/5).

**Comment by jasongrout** [comment]
Thanks for the reference. It may make more sense to create a new thread referencing the old one, rather than resurrecting the old thread. I don't know how their community treats such things, though.

**Comment by timhoffm** [comment]
Thanks. I'll see if there is feedback. Otherwise, I can start a new thread later.
