### ISSUE TITLE
How to change location of .jupyter directory?

### ISSUE THREAD

**Issue by scottwsides** [jupyterlab/jupyterlab#6215]
I've tried changing the following environment variables

    export JUPYTER_CONFIG_DIR=/Users/swsides/hpccloud-trunk/chemistream/chemistream
    export JUPYTER_PATH=/Users/swsides/hpccloud-trunk/chemistream/chemistream
    export JUPYTER_RUNTIME_DIR=/Users/swsides/hpccloud-trunk/chemistream/chemistream

but when I do 'jupyter --paths' I get

config:
    /Users/swsides/hpccloud-trunk/chemistream/chemistream
    /Users/swsides/hpccloud-trunk/chemistream/chemistream-env/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/swsides/hpccloud-trunk/chemistream/chemistream
    /Users/swsides/Library/Jupyter
    /Users/swsides/hpccloud-trunk/chemistream/chemistream-env/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/swsides/hpccloud-trunk/chemistream/chemistream

All of the other posts I've seen don't quite answer my problem. What am I missing in order to completely specify all of the config locations?  Thanks,

**Comment by jasongrout** [comment]
This is a more general Jupyter question than just JupyterLab.

In the example app, I use JUPYTER_NO_CONFIG to turn off the automatic appending of system paths in the config system. See https://jupyter-core.readthedocs.io/en/latest/changelog.html?highlight=JUPYTER_NO_CONFIG#id4 and https://github.com/jupyterlab/jupyterlab/blob/master/examples/app/main.py#L12

Does that help?

**Comment by jasongrout** [comment]
It looks to me like there is no clean way to specify a single config directory and disable the system config directories: https://github.com/jupyter/jupyter_core/blob/51185b86423a370e62455211fe051fc569472513/jupyter_core/paths.py#L180-L198

If you'd like to do this, opening an issue (or even better, a PR) in the https://github.com/jupyter/jupyter_core repo would be the next step.

**Comment by scottwsides** [comment]
Thanks, I'll look at those links!

Maybe a better question is this (since moving the .jupyter is not an
option). Is there a way of referring to separate user configurations stored
in the *same* .jupyter directory?
*Dr. Scott W Sides*
(303) 718-7028

**Comment by scottwsides** [comment]
Help me come up to speed on your procedures. I'm not sure what's involved
in the pull request or opening an issue. I don't have the resources to fix
this myself... but you simply went for me to move my request/question to a
new issue on the jupyter_core GitHub correct?

*Dr. Scott W Sides*
(303) 718-7028

**Comment by jasongrout** [comment]
> you simply went for me to move my request/question to a new issue on the jupyter_core GitHub correct?

Yes.

**Comment by scottwsides** [comment]
this is sorted for me now, thanks!

**Comment by jeffmax** [comment]
@scottwsides would you mind sharing how you solved this issue?

**Comment by scottwsides** [comment]
jeffmax, frankly I forget what I did. Whatever issue I was seeing because of this ... seems to no longer be a problem. Sorry I can't help more.

**Comment by jeffmax** [comment]
@scottwsides Been there. Thanks for taking the time to respond.
