### ISSUE TITLE
"No renderer could be found for output" message in outputs

### ISSUE THREAD

**Issue by BenRussert** [jupyterlab/jupyterlab#6216]
**Describe the bug**
When using the [scrapbook package](https://github.com/nteract/scrapbook), the `glue` function anywhere in a cell produces a confusing message:

```
No renderer could be found for output. It has the following MIME types: application/scrapbook.scrap.json+json
```

No outputs are expected for the `glue` function alone.

**To Reproduce**

```python
# !pip install nteract-scrapbook
import scrapbook as sb
sb.glue("hello", "world")
```
or

```python
# in the same cell:
x = "world"
sb.glue("hello", x)
x
```
You would expect "world" in output, but not the message. The message is prepended however:

**Screenshots**

![jupyter-lab-no-render-message](https://user-images.githubusercontent.com/10860657/56338543-ab997f00-6167-11e9-8e99-12efd45aebd2.png)

**Expected behavior**
No output  or warning message

**Comment by jasongrout** [comment]
It sounds like this would be a great mimerender extension to provide a renderer for this mimetype. I'm a little surprised that scrapbook doesn't seem to provide a `text/plain` representation to show in frontends that don't understand that mimetype.

**Comment by MSeal** [comment]
Since the display type is meant to recall data pragmatically, it doesn't give a plain text mimetype representation. Scraps with display contents (like images) will give the normal mimetype representations one would expect to render. None of the jupyter interfaces currently render the scrapbook data mimetype, but it might be interesting to enable such rendering at some point in the future to view the data. It's intended purpose is to allow for capturing data or references to data in the notebook object that can be recalled by another process, thus an invisible rendering was the original approach.

**Comment by jasongrout** [comment]
Ah, thanks. So what I'm hearing is that JupyterLab shouldn't try to be helpful here in rendering an error?

**Comment by jasongrout** [comment]
(I'll note for myself and others that the message spec only mandates `text/plain` in mimebundles in a pager or execution_result message, not in display_data messages)

**Comment by jasongrout** [comment]
>  No output or warning message

Sorry, I think I misread the desired behavior above. It seems the answer is: "yes, don't render any output or error."

Bumping to a good first issue for 1.0.

**Comment by MSeal** [comment]
Yep, was just giving some context. The "yes, don't render any output or error." is correct.

**Comment by MSeal** [comment]
Thanks!

**Comment by saulshanabrook** [comment]
@jasongrout So to be clear, is your suggestion that if we cannot find any renderer, we simply don't render an output instead of displaying this error message?

**Comment by jasongrout** [comment]
> @jasongrout So to be clear, is your suggestion that if we cannot find any renderer, we simply don't render an output instead of displaying this error message?

Correct.

**Comment by jasongrout** [comment]
This is now marked as a good first issue. The error message is generated at https://github.com/jupyterlab/jupyterlab/blob/b5fd981d88851f597e3e2c576dead91aaf3c938b/packages/outputarea/src/widget.ts#L400-L403

**Comment by vidartf** [comment]
Maybe it still makes sense to display this message if the notebook is not trusted, and a valid renderer would have been available if it was?

**Comment by jasongrout** [comment]
> Maybe it still makes sense to display this message if the notebook is not trusted, and a valid renderer would have been available if it was?

That makes sense to me. In that case, the error message should probably reflect the idea that the trust status caused it not to render.

**Comment by saulshanabrook** [comment]
The classic notebook does not create an output div when there is no renderer available. The consensus in the meeting is that we should do the same, if we cannot render an output, then we could not create a div.

But this might be slightly painful to change, based on Phosphor messages lining up with DOM children.
