### ISSUE TITLE
Server on main pc, forwarded via router, kernel doesn't connect, status 400

### ISSUE THREAD

**Issue by zuuuhkrit** [jupyterlab/jupyterlab#6225]
I'm running jupyer-lab (version 0.35.4) on my Windows PC, runnning on port 8888

On my linux router (192.168.123.250), I made a forward such that incoming connects to port 80 get forwarded to port 8888 on my Windows PC. (port 443 is in use, and those are the only two that I'm sure I can access from university).

I can now connect to the jupyter lab interface from the outside world, and it loads the notebooks just fine. However, when I start a kernel, it doesn't seem to connect - the cell stays at evaluating and nothing happens.

Jupyter-lab --debug gives the following output:

```
[D 15:07:48.565 LabApp] 200 GET /api/terminals?1555851995248 (192.168.123.250) 0.00ms
[D 15:07:49.045 LabApp] Starting kernel: ['E:\\Apps\\Anaconda3\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\Z\\AppData\\Roaming\\jupyter\\runtime\\kernel-c29f6d7f-d0b6-4308-8e9c-bc07ddf212db.json']
[D 15:07:49.045 LabApp] Connecting to: tcp://127.0.0.1:52160
[D 15:07:49.055 LabApp] Connecting to: tcp://127.0.0.1:52158
[I 15:07:49.055 LabApp] Kernel started: c29f6d7f-d0b6-4308-8e9c-bc07ddf212db
[D 15:07:49.055 LabApp] Kernel args: {'kernel_name': 'python3', 'cwd': 'G:\\jupyter'}
[D 15:07:49.055 LabApp] 201 POST /api/sessions?1555851995494 (192.168.123.250) 230.00ms
[D 15:07:49.338 LabApp] Initializing websocket connection /api/kernels/c29f6d7f-d0b6-4308-8e9c-bc07ddf212db/channels
[D 15:07:49.348 LabApp] Requesting kernel info from c29f6d7f-d0b6-4308-8e9c-bc07ddf212db
[D 15:07:49.348 LabApp] Connecting to: tcp://127.0.0.1:52157
[D 15:07:50.596 LabApp] Received kernel info: {'status': 'ok', 'protocol_version
': '5.1', 'implementation': 'ipython', 'implementation_version': '7.4.0', 'langu
age_info': {'name': 'python', 'version': '3.6.8', 'mimetype': 'text/x-python', '
codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3
', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': "Python 3
.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64
)]\nType 'copyright', 'credits' or 'license' for more information\nIPython 7.4.0
 -- An enhanced Interactive Python. Type '?' for help.\n", 'help_links': [{'text
': 'Python Reference', 'url': 'https://docs.python.org/3.6'}, {'text': 'IPython
Reference', 'url': 'https://ipython.org/documentation.html'}, {'text': 'NumPy Re
ference', 'url': 'https://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy
 Reference', 'url': 'https://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Ma
tplotlib Reference', 'url': 'https://matplotlib.org/contents.html'}, {'text': 'S
ymPy Reference', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pa
ndas Reference', 'url': 'https://pandas.pydata.org/pandas-docs/stable/'}]}
[I 15:07:50.606 LabApp] Adapting to protocol v5.1 for kernel c29f6d7f-d0b6-4308-8e9c-bc07ddf212db
[W 15:07:50.606 LabApp] 400 GET /api/kernels/c29f6d7f-d0b6-4308-8e9c-bc07ddf212db/channels?session_id=22b722c0-376c-4122-b91e-bc4c86de34b5 (192.168.123.250) 1268.00ms referer=None
[D 15:07:50.606 LabApp] Can "Upgrade" only to "WebSocket".
[D 15:07:50.767 LabApp] Initializing websocket connection /api/kernels/c29f6d7f-d0b6-4308-8e9c-bc07ddf212db/channels
[I 15:07:50.767 LabApp] Adapting to protocol v5.1 for kernel c29f6d7f-d0b6-4308-8e9c-bc07ddf212db
[W 15:07:50.767 LabApp] 400 GET /api/kernels/c29f6d7f-d0b6-4308-8e9c-bc07ddf212db/channels?session_id=e983dcec-892a-412b-ab5f-c79834718a4e (192.168.123.250) 0.00ms referer=None
[D 15:07:50.767 LabApp] Can "Upgrade" only to "WebSocket".
[D 15:07:51.776 LabApp] Initializing websocket connection /api/kernels/c29f6d7f-d0b6-4308-8e9c-bc07ddf212db/channels
[W 15:07:51.786 LabApp] Replacing stale connection: c29f6d7f-d0b6-4308-8e9c-bc07
```

Is this setup (server only behind router) possible? Do I need to setup more?

**Comment by saulshanabrook** [comment]
I am not sure.

It might be helpful to inspect the network traces sent by you browser. If you open up the network tab in the inspector, you should see one for the websocket request. There you can see the request and response headers. That might give more information.

**Comment by timkpaine** [comment]
looks like its not forwarding websockets?

**Comment by zuuuhkrit** [comment]
I might have a general misunderstanding about websockets. I thought that forwarding only the port and hence the TCP connections would be enough. I tried to read again the guide at https://jupyter-notebook.readthedocs.io/en/stable/public_server.html, but I don't see much information about websockets. Which websockets are being used?

**Comment by timkpaine** [comment]
@zuuuhkrit feel free to ping me offline/on gitter to share a bit about your setup, but some part of one of the various connections isn't going through or is missing a header. As a trivial example of this, try to connect to my website https://ws.paine.nyc with your browser. The response will tell you that you're trying to connect to a websocket via http with the same error you're seeing. 

For jupyter details,  `/api/kernels/` is queried both via http and websockets, so a little bit of configuration magic is necessary when you start forwarding things so that both work properly.

**Comment by timkpaine** [comment]
https://gitter.im/jupyterlab/jupyterlab

**Comment by zuuuhkrit** [comment]
@saulshanabrook : I didn't think about that :) I traced the requests from my browser, and looked at the first websocket request.

**Comment by zuuuhkrit** [comment]
I was able to do some more testing, and it normally works from an external IP. It only doesn't work from my uni laptop. So I think they block the websocket connections from working properly.
