### ISSUE TITLE
Updating jupyterlab_server downgrades jupyterlab

### ISSUE THREAD

**Issue by cossio** [jupyterlab/jupyterlab#6226]
I'm updating my conda packages, so I executed `conda update jupyterlab_server`. But this results in the following warning:

```
The following NEW packages will be INSTALLED:

  jupyterlab_launch~ pkgs/main/linux-64::jupyterlab_launcher-0.13.1-py37_0

The following packages will be UPDATED:

  jupyterlab_server                            0.2.0-py37_0 --> 0.3.0-py37_0

The following packages will be DOWNGRADED:

  jupyterlab                          0.35.4-py37hf63ae98_0 --> 0.34.12-py37_0
```

**Comment by saulshanabrook** [comment]
I believe our dependency has been bumped on master https://github.com/jupyterlab/jupyterlab/commit/3b8d451e6f9a4c609e60cde5fbb3cc84aae79951 and so when the next version of JupyterLab is released, it will depend on the latest version of jupyterlab_server. Until then, I wouldn't recommend updating it.

**Comment by h2li** [comment]
The latest JupyterLab `0.35.5` just released on PyPI yesterday (April 25, 2019) is still requiring `jupyterlab_server>=0.2.0,<0.3.0`.

**Comment by blink1073** [comment]
hi @h2li, @saulshanabrook was referring to version 1.0.  0.3.5 was a bug-fix release that still depends on the previous version of the jupyterlab_server.
