### ISSUE TITLE
Objects not created when "%%time" is used

### ISSUE THREAD

**Issue by indrajitsg** [jupyterlab/jupyterlab#6233]
**Describe the bug**

When I use "%%time" in a cell which has an assignment, the assigned object does not get created. 

**Screenshots**

![jupyter1](https://user-images.githubusercontent.com/10430320/56568978-b9228f00-65d5-11e9-834e-01a512aed598.JPG)

**Expected Behavior**

The object "x" should get created.

**Operating System**

JupyterLab version: 0.35.4 
OS: Ubuntu Linux 16.04
Python: 3.6.8

**Comment by jasongrout** [comment]
Does it work in the classic Jupyter notebook? You can launch it using the JupyterLab Help menu.

I think that this issue is likely from the ipython kernel, and probably does not have to do with JupyterLab.

**Comment by indrajitsg** [comment]
Hi Jason,

I tried - it still did not work. Here is the screenshot.

![jupyter2](https://user-images.githubusercontent.com/10430320/56578142-859e2f80-65ea-11e9-8b64-506a7bd37190.JPG)

**Comment by jasongrout** [comment]
So this indicates it is not a JupyterLab issue, but an issue with the ipython kernel. I notice it works fine for the ipython started in the terminal, so it's likely an ipykernel issue. Can you open this exact issue at https://github.com/ipython/ipykernel? Make sure to include that it doesn't work in the classic notebook and jlab.

**Comment by indrajitsg** [comment]
Done

**Comment by jasongrout** [comment]
Thanks. Let's move the discussion over there, then: https://github.com/ipython/ipykernel/issues/401
