### ISSUE TITLE
remote is not working

### ISSUE THREAD

**Issue by selfcs** [jupyterlab/jupyterlab#6239]
**Describe the bug**
I can not connect the remote jupyter lab(I use jupyter notebook just 2years, lab is 1+ year)

**To Reproduce**

1. install the minicoda
2. pip install jupyterlab
3. config the jupyter_notebook_config.py 
```python
c.NotebookApp.allow_remote_access = True
c.NotebookApp.ip = '0.0.0.0'  # and I also try ‘*’ is not work too
c.NotebookApp.open_browser = False
c.NotebookApp.port = 8388
```
4. `jupyter lab`  print `The Jupyter Notebook is running at: http://(ubuntu or 127.0.0.1):8388/ `
**Desktop (please complete the following information):**

- OS: [ubuntu 16.04]
- JupyterLab [e.g. 0.35.4]

**Comment by jasongrout** [comment]
Would you mind following up here about what worked, so others can benefit from your experience?
