### ISSUE TITLE
Option to only display on Output View (no inline render)

### ISSUE THREAD

**Issue by hainm** [jupyterlab/jupyterlab#6244]
Hi all,

Is there any way to only display a widget in Output View? Please see the gif below. Basically I only want to display the "view" in the right, not in the left. Thanks.

![output_view](https://user-images.githubusercontent.com/4451957/56709169-c7fc6500-66ed-11e9-9b66-1c44f97e16f9.gif)

**Comment by hainm** [comment]
I think if there is ever an option like that, it should be default.

**Comment by jasongrout** [comment]
Please see the sidecar widget: https://github.com/jupyter-widgets/jupyterlab-sidecar

**Comment by hainm** [comment]
thanks @jasongrout. I will check it out. Cheers.

**Comment by hainm** [comment]
Look great. Thanks again.
<img width="1192" alt="Screen Shot 2019-04-25 at 12 43 55 AM" src="https://user-images.githubusercontent.com/4451957/56710277-4c9db200-66f3-11e9-90b2-f775c3b6c928.png">

**Comment by hainm** [comment]
<img width="1278" alt="Screen Shot 2019-04-25 at 12 48 31 AM" src="https://user-images.githubusercontent.com/4451957/56710374-e1a0ab00-66f3-11e9-94b7-062cad7f1172.png">

**Comment by jasongrout** [comment]
Nice! Thanks for sharing!

**Comment by mtkilic** [comment]
This is good but every time you update cell and rerun, new Sidecar window gets create instead of updating itself, like jupyterlab `output view` does. Also, you can not rearrange each Sidecar window to display under each other. So you can not view multiple plot same time.
