### ISSUE TITLE
Unable to import Session from @jupyterlab/services

### ISSUE THREAD

**Issue by hugokerstens** [jupyterlab/jupyterlab#6245]
I’m trying to use the JupyterLab services in NodeJS.

I run into some strange errors while importing the Session namespace. I'm importing the Kernel and Session like this:

`import { Session, Kernel } from “@jupyterlab/services”;`

Then, when I try to use them, Kernel is defined and usable. However, Session is undefined.
What am I doing wrong?

**Comment by hugokerstens** [comment]
Strangely enough, in my compiled script I find this:

```
/***/ "./node_modules/@jupyterlab/services/lib/session/index.js":
/*!****************************************************************!*\
  !*** ./node_modules/@jupyterlab/services/lib/session/index.js ***!
  \****************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

exports = {};


/***/ }),
```

While for `Kernel` the functions are there...

**Comment by blink1073** [comment]
Hi @hugokerstens, how did you compile the file?  The source is:

```
$ cat lib/session/index.js 
"use strict";
// Copyright (c) Jupyter Development Team.
// Distributed under the terms of the Modified BSD License.
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./manager"));
__export(require("./session"));
```

**Comment by hugokerstens** [comment]
I'm currently modifying thebelab to use `Session` instead of `Kernel`. 
I compile it like this:

https://github.com/minrk/thebelab/blob/e50059b6a9c7018b5ba880e91f18e27c45df020a/package.json#L7

**Comment by hugokerstens** [comment]
Thanks for your reply, I'm stupid. The webpack config of thebelab shims the session directory:
https://github.com/minrk/thebelab/blob/e50059b6a9c7018b5ba880e91f18e27c45df020a/webpack.config.js#L46

**Comment by blink1073** [comment]
Ha, I was about to point that line out.  No worries, configs are a rabbit-hole...
