### ISSUE TITLE
Deletion/override of system default keyboard-shortcuts

### ISSUE THREAD

**Issue by treibholz** [jupyterlab/jupyterlab#6249]
**Describe the bug**
Deletion/override of system default keyboard-shortcuts not possible with 1.0.0aX

I want to remap Ctrl-B (application:toggle-left-area) to something else, to be able to use tmux in the terminal-app.

This works in older/stable versions, but not in 1.0.0aX

**To Reproduce**

1. Go to 'Advanced Settings Editor'
2. Click on 'Keyboard Shortcuts'
3. Click in 'User Preferences'
4. Add:
```json
{
    "shortcuts": [
        {
            "command": "application:toggle-left-area",
            "keys": [
                "Accel L"
            ],
            "selector": "body"
        }
    ]
}
```
5. Save, and open a terminal.
6. CTRL-L and CTRL-B now both trigger the command application:toggle-left-area.

**Expected behavior**

Only CTRL-L should trigger it or there should be a way to unset a system-default.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win10, macOS mojave, Debian-Linux (Stretch/Buster)
- Browser: chrome 7x, Safari, Firefox
- JupyterLab: 1.0.0a[1-3]

**Additional context**
I also tried to set the command for "Accel B" to "", so the the command "application:toggle-left-area" would not be triggered, this worked, but "CTRL-B" is not unset, and is not sent to the application (tmux) inside the terminal.

**Comment by jasongrout** [comment]
You can disable a keyboard shortcut by copying it into the user overrides and adding the `disabled` key:

```
        {
            "command": "application:toggle-left-area",
            "keys": [
                "Accel B"
            ],
            "selector": "body",
            "disabled": true
        }
```

**Comment by jasongrout** [comment]
We should document this somewhere. Where in the documentation would you have looked for it?

**Comment by treibholz** [comment]
Thanks, it works!

I would have looked for it here: https://jupyterlab.readthedocs.io/en/latest/user/interface.html#keyboard-shortcuts (but I would not have watched the video!)

But, I would have expected to find it in the comments of the System Defaults, something like this:
```
{
    // Keyboard Shortcuts
    // @jupyterlab/shortcuts-extension:shortcuts
    // Keyboard shortcut settings for JupyterLab.
    // ******************************************
    // To unset a System Default add the "disabled" key:
    // {
    //      "command": "application:toggle-left-area",
    //      "keys": [
    //          "Accel B"
    //      ],
    //      "selector": "body",
    //      "disabled": true
    // }
```

**Comment by jasongrout** [comment]
For whoever works on this, the text in the advanced settings is the title attribute modified here:
https://github.com/jupyterlab/jupyterlab/blob/52b871d72ed20b2f8d38a404c43dad4036a596b4/packages/shortcuts-extension/src/index.ts#L165-L167
