### ISSUE TITLE
"Running Terminal and Kernels" appears blank

### ISSUE THREAD

**Issue by cocoaaa** [jupyterlab/jupyterlab#6252]
Hi, 

After letting jupyterlab to run for sometime on a remote server, I often encounter the "Running Terminal and Kernels" window start to display nothing:
<img src="https://user-images.githubusercontent.com/8037983/56780543-896db580-6794-11e9-8c24-dc99a3178e71.png" height="200">

Other tabs seem to work as expected. In particular, I can see that several of my notebooks are indeed running:
![image](https://user-images.githubusercontent.com/8037983/56780590-bae68100-6794-11e9-8d5f-2b28459fd903.png)
If I kill the jupyterlab process and restart it, the tab works fine in the beginning. But after some time (sorry, I'm not sure how long exactly), it displays nothing. If there is a better way to inspect what is happening, I'd be happy to try it and share the log.

I installed from conda-forge
  Jupyter 1.0.0
  Jupyterlab 0.35.4 

Thanks!

**Comment by jasongrout** [comment]
Are there any errors in the server log or the javascript console?

**Comment by cocoaaa** [comment]
I reinstalled the Jupyterlab, and the problem seems to have disappeared.  I'll report it again if it comes back. Thanks!
