### ISSUE TITLE
Markdown reference can no longer be iframe'd

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#6257]
At some point in the last few months, GitHub has prevented iframing of their markdown documentation. This means that the markdown reference in our Help menu no longer works. We should either (a) find a new authoritative markdown guide, or (b) remove the menu item.

Marking as a good first issue. The markdown reference menu item is defined here: https://github.com/jupyterlab/jupyterlab/blob/2dcdd45fea89f29ecd2865a3539a60d8e89ce67b/packages/help-extension/src/index.tsx#L75-L80

A new contributor would look around the internet for a new markdown reference from a reputable source that allows iframing. If that cannot be found, the menu item should be ignored.

**Comment by ian-r-rose** [comment]
One possible contender: https://guides.github.com/features/mastering-markdown/

**Comment by jasongrout** [comment]
Another: https://commonmark.org/help/

**Comment by blink1073** [comment]
Fixed by #6262.
