### ISSUE TITLE
Single configuration file

### ISSUE THREAD

**Issue by CavalloneChen** [jupyterlab/jupyterlab#6263]
It would be very convenient to have a single file which controls all the settings in Jupyterlab just like vscode's "settings.json". This would greatly simplifies docker deployment of jupyterlab as well as makes it easier to do version control.

**Comment by jasongrout** [comment]
The default settings are provided by each separate plugin, so they need to be separate files. Do you mean a single file for user overrides of the defaults? Right now those are stored in separate files, one for each plugin.

Note that there *is* a single file for system overrides of defaults.

**Comment by CavalloneChen** [comment]
Yes, I do mean a single file for user overrides of the defaults. I want to have control over all configurations before the docker container is started, this could help save a lot of time.

**Comment by jasongrout** [comment]
Why not use a system override, then? That would effectively change the defaults for any plugin you want, in a single file, but still allow user customization.

**Comment by jasongrout** [comment]
The system override is specifically designed for system administrators who want a single file to modify settings defaults. See https://github.com/jupyterlab/jupyterlab_server/pull/29 for instructions on how to use it. Does that satisfy your needs?

We should add a mention of this functionality to the documentation.

**Comment by CavalloneChen** [comment]
Cool, thanks a lot!

**Comment by isabela-pf** [comment]
It looks like the system override and how to use it has already been listed in the docs by @blink1073  under Extensions > Advanced Usage. I think this issue can be closed.

**Comment by blink1073** [comment]
Thanks for the heads up @isabela-pf!
