### ISSUE TITLE
Terminal not working in firefox

### ISSUE THREAD

**Issue by CavalloneChen** [jupyterlab/jupyterlab#6266]
**Describe the bug**
Terminal not working in firefox 66.0.3 on Macos 10.14.4. I can open terminal in other browsers like safari and chrome.

**Screenshots**
**In firefox**
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/28266566/56857699-754bd300-69a3-11e9-89de-8f43e242e08b.png">
**In chrome**
<img width="769" alt="image" src="https://user-images.githubusercontent.com/28266566/56857703-84328580-69a3-11e9-9eb9-2c0c9a0c73ac.png">

**Desktop (please complete the following information):**

- OS: Macos 10.14.4
- Browser firefox 66.0.3
- JupyterLab 0.35.5
- tornado 6.0.2

**Comment by CavalloneChen** [comment]
And the kernel is always busy when using firefox.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/28266566/56858653-733c4100-69b0-11e9-992d-c71d9b65863e.png">
I guess this is a tornado-related issue.

**Comment by jasongrout** [comment]
I think we don't support tornado 6 yet. Does it work with tornado 5.x?

**Comment by CavalloneChen** [comment]
Unfortunately, no. I tried another installation with tornado==5.1.1, and the problem didn't get solved.

**Comment by blink1073** [comment]
I think something else might be wrong.  I tried this on MacOS 10.14.4, Firefox 66:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2096628/56862165-9abdea00-696d-11e9-8881-528ce3ce2cbb.png">


Perhaps a browser or OS setting?

**Comment by blink1073** [comment]
(Kernels also run fine for me with proper state icon behavior).

**Comment by CavalloneChen** [comment]
Really odd. I've tried reinstalling firefox and jupyterlab several times, and I've tried altering firefox's settings, nothing works so far. Firefox beta gave me the same result.

**Comment by blink1073** [comment]
Is anything printed to the brower's JavaScript console (F12) when you load a terminal?

**Comment by CavalloneChen** [comment]
<img width="1001" alt="Xnip2019-04-28_19-16-21" src="https://user-images.githubusercontent.com/28266566/56863553-4dcc2900-69ea-11e9-948a-5df7a3244f67.png">

**Comment by blink1073** [comment]
Ah, it looks like we sockets are disabled on your Firefox.

**Comment by CavalloneChen** [comment]
Yeah, it looks like a firefox problem. I'll close the issue.
