### ISSUE TITLE
No event fired when item clicked in FileBrowser

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/jupyterlab#6269]
I'm trying to see how I can get notified from the FileBrowser component when a file is double clicked. Unfortunately, there seems to be no way to do this. The only notification mechanism available is via DocumentRegistry, which also assumes that you're going to create a new widget with it. 

Would love to have a callback that notifies it whenever an item is double clicked.

**Comment by yuvipanda** [comment]
https://github.com/yuvipanda/simplest-notebook/blob/master/src/components/filebrowser.tsx is some code

**Comment by yuvipanda** [comment]
And I couldn't attach my own handler and use browser.modelForClick since it looks like the doubleClick handler isn't being fired - possible because of preventDefault() in the JupyterLab code?

**Comment by yuvipanda** [comment]
What I'd like is a Signal in DirListing that is triggered whenever an 'open' style event (double click, enter, etc) happens.

**Comment by jasongrout** [comment]
Do you have a specific file type in mind? One thing you could do right now is register a default handler for that file type. You have to return a widget, so just return a simple widget saying "look in your other tab", and have your opening code *also* open a new tab.

I think we should also change it. Just saying what you can do for now.

**Comment by jasongrout** [comment]
I had thought that since you want to take over the open event, perhaps we should just make the openers *optionally* return a widget. If they don't return a widget, then it is assumed the opener handled the file some other way outside of jlab, and we are no longer responsible for that open view of the file.
