### ISSUE TITLE
Clonned default filebrowser and created extension and disabled default filebrowser, but not able to see new file browser extension in action .

### ISSUE THREAD

**Issue by ggbhat** [jupyterlab/jupyterlab#6271]
If you are having issues with installation or configuration, we encourage you to post in the [Jupyter Discourse forum](https://discourse.jupyter.org/c/jupyterlab) or file an issue here.

**Comment by jasongrout** [comment]
Can you give a detailed list of instructions of what you did so we can try to reproduce the issue?

**Comment by ggbhat** [comment]
Issue was due to my local dev setup. I am able to fix hence closing.
