### ISSUE TITLE
Support importing a workspace from stdin.

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#6272]
The workspaces command line interface is asymmetrical because it prints to stdout when exporting but it cannot read from stdin when importing.

So where currently we need to run:
```shell
jupyter lab workspaces import file_name.json
```
We should continue to support this, but also support:
```shell
cat file_name.json | jupyter lab workspaces import -
```

This is a "nice to have" feature so its milestone is `1.1`; but if it is implemented in time for `1.0` we can include it.

cf. https://jupyterlab.readthedocs.io/en/stable/user/urls.html#managing-workspaces-cli

**Comment by afshin** [comment]
@wonsjb volunteered to work on this (but I am not sure how to assign in GitHub). Cheers!

**Comment by wonsjb** [comment]
Done!
