### ISSUE TITLE
Exporting notebook to PDF fails 

### ISSUE THREAD

**Issue by AlbertHilb** [jupyterlab/jupyterlab#6273]
Sometimes, exporting to PDF a notebook containing an header with a LaTeX expression fails. 

To Reproduce the bug:

1. Create a new notebook
2. add a markdown cell
3. insert `Vector $\overrightarrow {AB}$` into the cell
4. export the notebook to PDF

Instead of the PDF, you'll get the following server error:

> # 500 : Internal Server Error
> nbconvert failed: PDF creating failed, captured latex output:
> This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Debian) (preloaded format=xelatex)
>  restricted \write18 enabled.
> entering extended mode
> (./notebook.tex
> LaTeX2e <2017-04-15>
> Babel <3.18> and hyphenation patterns for 3 language(s) loaded.
> (/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
> Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
> (/usr/share/texlive/texmf-dist/tex/latex/base/size11.clo))
> (/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
> (/usr/share/texlive/texmf-dist/tex/latex/base/t1enc.def)
> (/usr/share/texmf/tex/latex/lm/t1lmr.fd))
> (/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathpazo.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
> (/usr/share/texlive/texmf-dist/tex/latex/graphics-def/xetex.def)))
> (/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty
> (/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/adjustbox.sty
> (/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
> (/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex
> (/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
> (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/trimclip.sty
> (/usr/share/texlive/texmf-dist/tex/latex/collectbox/collectbox.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/tc-xetex.def))
> (/usr/share/texlive/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/varwidth/varwidth.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/xcolor/xcolor.sty
> (/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))
> (/usr/share/texlive/texmf-dist/tex/latex/tools/enumerate.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
> (/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
> For additional information on amsmath, use the `?' option.
> (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
> (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty
> (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
> (/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
> (/usr/share/texlive/texmf-dist/tex/latex/upquote/upquote.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/eurosym/eurosym.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/ucs/ucs.sty
> (/usr/share/texlive/texmf-dist/tex/latex/ucs/data/uni-global.def))
> (/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
> 
> Package inputenc Warning: inputenc package ignored with utf8 based engines.
> 
> ) (/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
> Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
> <2008/02/07> (tvz))
> (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grffile.sty
> (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
> (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
> (/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hxetex.def
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/puenc.def)
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/stringenc.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/enumitem/enumitem.sty)
> (/usr/share/texlive/texmf-dist/tex/generic/ulem/ulem.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/jknapltx/mathrsfs.sty)
> No file notebook.aux.
> (/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
> (/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ppl.fd)
> (/usr/share/texlive/texmf-dist/tex/latex/caption/ltcaption.sty)
> *geometry* driver: auto-detecting
> *geometry* detected driver: xetex
> *geometry* verbose mode - [ preamble ] result:
> * driver: xetex
> * paper: <default>
> * layout: <same size as paper>
> * layoutoffset:(h,v)=(0.0pt,0.0pt)
> * modes: 
> * h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
> * v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
> * \paperwidth=614.295pt
> * \paperheight=794.96999pt
> * \textwidth=469.75502pt
> * \textheight=650.43001pt
> * \oddsidemargin=0.0pt
> * \evensidemargin=0.0pt
> * \topmargin=-37.0pt
> * \headheight=12.0pt
> * \headsep=25.0pt
> * \topskip=11.0pt
> * \footskip=30.0pt
> * \marginparwidth=59.0pt
> * \marginparsep=10.0pt
> * \columnsep=10.0pt
> * \skip\footins=10.0pt plus 4.0pt minus 2.0pt
> * \hoffset=0.0pt
> * \voffset=0.0pt
> * \mag=1000
> * \@twocolumnfalse
> * \@twosidefalse
> * \@mparswitchfalse
> * \@reversemarginfalse
> * (1in=72.27pt=25.4mm, 1cm=28.453pt)
> 
> (/usr/share/texlive/texmf-dist/tex/latex/ucs/ucsencs.def)
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
> 
> Package hyperref Warning: Rerun to get /PageLabels entry.
> 
> (/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ppl.fd)
> (/usr/share/texlive/texmf-dist/tex/latex/psnfss/omlzplm.fd)
> (/usr/share/texlive/texmf-dist/tex/latex/psnfss/omszplm.fd)
> (/usr/share/texlive/texmf-dist/tex/latex/psnfss/omxzplm.fd)
> (/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1zplm.fd)
> (/usr/share/texlive/texmf-dist/tex/latex/jknapltx/ursfs.fd)
> 
> LaTeX Warning: No \author given.
> 
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/se-ascii-print.def)
> ! Illegal parameter number in definition of \reserved@a.
> <to be read again> 
>                    \crcr 
> l.295 ...\{AB\}}}\label{vector-overrightarrow-ab}}
>                                                   
> ? 
> ! Emergency stop.
> <to be read again> 
>                    \crcr 
> l.295 ...\{AB\}}}\label{vector-overrightarrow-ab}}
>                                                   
> No pages of output.
> Transcript written on notebook.log.
> 

My system is:

- OS: Ubuntu 18.04 
- Browser: Firefox 66.0 
- JupyterLab 1.0.0a3

The issue seems related to the autogenerated header id.
My first thought has been it was caused by the presence of the `backslash` char, but if `\overrightarrow` is replaced by `\overline`, no error is raised. So I was wrong.

Cheers

**Comment by jasongrout** [comment]
Does this work in classic notebook? If you can try the command line, can you use nbconvert directly to see if it works there?

My guess is that this is an nbconvert error, and so we should move the discussion to https://github.com/jupyter/nbconvert/

**Comment by t-makaro** [comment]
It looks like an error caused by the difference between mathjax and latex. Definitely, an nbconvert error. I suspect that it will convert fine if you remove the space between ```\overrightarrow``` and ```{AB}```.

**Comment by AlbertHilb** [comment]
@jasongrout. No, it does work neither in classic notebook nor using nbconvert from command line.

@t-makaro. Nope. Removing the space, still it doesn't work.  

I'm closing this and opening an issue on nbconvert.
