### ISSUE TITLE
Notebook settings propagation to widget is not easy to read

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#6274]
Hey,

This is not a bug. More a place where code refractoring would help its understanding.

When updating notebook settings, those are applied to all opened notebook widget through the `updateTracker` function:

https://github.com/jupyterlab/jupyterlab/blob/392dba9396a6acddd9458a44c23d9c0d613ad7ce/packages/notebook-extension/src/index.ts#L628-L633

That function is hard to understand as it uses indirectly its argument `settings`. Indeed the settings are really read in `updateConfig`. In which they are affected to the factory and some global variables.

https://github.com/jupyterlab/jupyterlab/blob/392dba9396a6acddd9458a44c23d9c0d613ad7ce/packages/notebook-extension/src/index.ts#L619-L622

Then those global variables will be used to update the tracked widgets.

I think it will be better to call `updateTracker` at the end of `updateConfig` with two optional arguments `editorConfig` and `notebookConfig`. The default values could be the default options to handle the call :
https://github.com/jupyterlab/jupyterlab/blob/392dba9396a6acddd9458a44c23d9c0d613ad7ce/packages/notebook-extension/src/index.ts#L651

**Comment by jasongrout** [comment]
I've also found this existing pattern odd. It sounds like your proposal would be an improvement. Do you want to make a PR as a next step?

**Comment by fcollonval** [comment]
I'll propose a correction in a PR.
