### ISSUE TITLE
Terminal theme appears twice in menu

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#6280]
**Describe the bug**

Submenu for choosing the terminal theme appears twice in the settings menu:

https://github.com/jupyterlab/jupyterlab/blob/0e0b82b94ff9d6a487b33c3b3e3ea24d2e2af71c/packages/terminal-extension/src/index.ts#L188-L201

**To Reproduce**

1. Click on the "Settings" Menu
2. Terminal theme appears twice

**Expected behavior**

Terminal theme submenu should appear once.

**Screenshots**

![bug_terminal_theme](https://user-images.githubusercontent.com/8435071/56914962-a9afb400-6ab5-11e9-87ff-f2c87e7cf8a8.png)

**Comment by ian-r-rose** [comment]
Hah, thanks @fcollonval, good catch! Marking this as a good first issue. A new contributor would remove one of the duplicated menu entries linked above (probably the first).

**Comment by rahulpshah** [comment]
I think this is resolved in the latest code base, here's a screenshot of the settings menu
<img width="314" alt="Screen Shot 2019-05-11 at 3 53 19 PM" src="https://user-images.githubusercontent.com/14010766/57574335-017ae300-7405-11e9-852c-6d0d8c7c5ef7.png">

**Comment by ian-r-rose** [comment]
Thanks @rahulpshah, this is a bug that is currently on `master`, but not on the latest stable release.
