### ISSUE TITLE
Ctrl-C when nothing selected clears clipboard

### ISSUE THREAD

**Issue by vincenzon** [jupyterlab/jupyterlab#6281]
**Describe the bug**
In a notebook cell, hitting Ctrl-C when nothing is selected clears the clipboard.

**To Reproduce**
1) Select some text in a notebook cell.
2) Hit Ctrl-C to copy that text to the clipboard.
3) Hit Ctrl-V to paste that text to a cell.
4) With no text selected, hit Ctrl-C again.
5) Hit Ctrl-V, nothing is pasted because the Ctrl-C in step 4 cleared the clipboard.

**Expected behavior**
The clip board does not get cleared when Ctrl-C is pressed and no text is selected.

**Desktop (please complete the following information):**

- OS: Windows 10
- Chrome
- JupyterLab

**Comment by jasongrout** [comment]
In some experiments, it looks like if I copy with nothing selected, it copies the entire line. This is how it seems to work in upstream Codemirror as well (you can try it at https://codemirror.net/).

When you did your second Ctrl-C, were you on a blank line? If so, it seems it was copying the blank line (i.e., it copies the line you were on). If you are on a line with some text, does it copy the entire line?

**Comment by vincenzon** [comment]
Yeah, that seems to be what is happening. Nevertheless, from the UX perspective, at least this U, that still is "clearing the clipboard" since I hit this problem when I unintentionally hit Ctrl-C when my intent is to hit Ctrl-V. It would be nice if this could be configurable.

**Comment by jasongrout** [comment]
I see your point. It appears this is an upstream Codemirror issue. I just searched there, are here are some relevant issues:

https://github.com/codemirror/CodeMirror/issues/2824
https://github.com/codemirror/CodeMirror/issues/2382

I haven't read through the discussions there in detail. If you'd like to pursue this, would you read through those discussions and tell us what you think?

**Comment by vincenzon** [comment]
My read of those issues and their associated ones is that there are some people that consider this a feature, and some that consider this a bug. I guess that suggests it should be configurable? It looks like the resolution in: https://github.com/adobe/brackets/issues/9311 was to do that.

**Comment by jasongrout** [comment]
Thanks for the high-level summary. It looks like https://github.com/adobe/brackets/pull/11706 is where that was implemented in brackets.

From that issue, we see that there is a codemirror preference to turn on and off the copy-line-when-no-selection behavior. We could expose that preference in our settings, just like the other codemirror preferences we are exposing.

Our facility for changing codemirror preferences is in https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror-extension/schema/commands.json and https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror-extension/src/index.ts for text editor preferences.

For notebooks, the preferences for the cell editors are exposed at https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook-extension/schema/tracker.json#L267-L331, and the generic options for an editor used in the notebook are at https://github.com/jupyterlab/jupyterlab/blob/master/packages/codeeditor/src/editor.ts#L579-L668 

Changing to good first issue. I think what would be needed is picking one of the existing codemirror options that we expose, and doing something similar for this option.

**Comment by jasongrout** [comment]
For reference, Sublime apparently has the `copy_with_empty_selection` option, defaulting to copy the current line: http://docs.sublimetext.info/en/latest/reference/settings.html

**Comment by jasongrout** [comment]
Also for reference, it seems that Visual Studio Code default behavior, when there is no selection and you do the copy shortcut, is to not copy the line if and only if the line consists of whitespace.

**Comment by peterdietz** [comment]
On Mac OSX and Chrome, Command-C, on a blank line, did not clear the buffer, and my previously copied line from Command-V was still in the buffer. So there could be some OS specific behavior here.

**Comment by ggbhat** [comment]
> Thanks for the high-level summary. It looks like [adobe/brackets#11706](https://github.com/adobe/brackets/pull/11706) is where that was implemented in brackets.
> 
> From that issue, we see that there is a codemirror preference to turn on and off the copy-line-when-no-selection behavior. We could expose that preference in our settings, just like the other codemirror preferences we are exposing.
> 
> Our facility for changing codemirror preferences is in https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror-extension/schema/commands.json and https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror-extension/src/index.ts for text editor preferences.
> 
> For notebooks, the preferences for the cell editors are exposed at https://github.com/jupyterlab/jupyterlab/blob/master/packages/notebook-extension/schema/tracker.json#L267-L331, and the generic options for an editor used in the notebook are at https://github.com/jupyterlab/jupyterlab/blob/master/packages/codeeditor/src/editor.ts#L579-L668
> 
> Changing to good first issue. I think what would be needed is picking one of the existing codemirror options that we expose, and doing something similar for this option.

Raised [PR ](https://github.com/jupyterlab/jupyterlab/pull/7842)by making above changes mentioned.

**Comment by ggbhat** [comment]
[PR ](https://github.com/jupyterlab/jupyterlab/pull/7842)Merged..

**Comment by telamonian** [comment]
fixed by #7842 

@vincenzon and for anyone else who has the same issue, you can fix it by going to the "Notebook" section of the advanced settings editor and then setting the `lineWiseCopyCut` option to `false`
