### ISSUE TITLE
Opening console from fileeditor context menu and from tab context menu not coherent

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#6284]
**Describe the bug**

Opening a console on a file with the tab title context menu is not the same as with the file editor context menu.

**To Reproduce**

1. Open a Python file
2. Right Click on the tab title
3. Click on 'New Console for Editor'

Compared to 

1. Open a Python file
2. Right Click on the file content 
3. Click on 'Create Console for Editor'

**Expected behavior**

The two entries should result in the same behavior.

**Screenshots**

![console_file](https://user-images.githubusercontent.com/8435071/56945664-3430fb80-6b28-11e9-88ed-0391332630e0.gif)

**Desktop**

- OS: Windows 10
- Browser chrome 73

**Additional context**

Here is the code used for the file editor context menu:

https://github.com/jupyterlab/jupyterlab/blob/25d8709e74c47c688b72102ce6dc2f4407186e96/packages/fileeditor-extension/src/index.ts#L403-L429

Here is the code used for the tab title context menu:

https://github.com/jupyterlab/jupyterlab/blob/25d8709e74c47c688b72102ce6dc2f4407186e96/packages/fileeditor-extension/src/index.ts#L722-L732

**Comment by fcollonval** [comment]
I'll propose a PR.

**Comment by jasongrout** [comment]
Thanks!
