### ISSUE TITLE
Stream messages are not rendered after kernel status switches to idle

### ISSUE THREAD

**Issue by AlexTugarev** [jupyterlab/jupyterlab#629]
Stream messages are not rendered after kernel status switches to idle

We would like to have stream messages rendered after the status 'idle' message was sent. 

Basically we need to display output from subprocesses which are called inside our kernel, but it shouldn't be rendered like execution results. Unfortunately the output may be read delayed in time and it's hard to identify its last line. A similar situation can be reproduced with the python kernel which makes it simpler to discuss. 

The following two screenshots show the difference in rendering of messages. I've learned that the stream messages are received on the websocket, but a quick look into the code with the debugger revealed that there is no handler registered after the idle message was handled.

Screenshot of jupyter-notebook: 

> <img width="543" alt="jupyter-notebook" src="https://cloud.githubusercontent.com/assets/914497/17563521/1f57b9e4-5f30-11e6-81cb-e87210bad1e4.png">

Screenshot of jupyter-lab: 

> <img width="601" alt="jupyter-lab" src="https://cloud.githubusercontent.com/assets/914497/17563520/1f3005d4-5f30-11e6-8a1e-694d1e7905cd.png">

Can you please clarify whether the rendering of stream messages can or wanted be adapted.

**Comment by blink1073** [comment]
Hi @AlexTugarev, thanks for reporting.  I'll look at this this afternoon.

**Comment by blink1073** [comment]
This brings up a broader issue.  By spec, a message is considered complete when we have gotten an `execute_reply` and a `status: idle` message back from the kernel.  In this case, the behavior of the existing notebook was to associate this orphaned output with the last executed cell.  

@jasongrout, @minrk, what are you thoughts on how we should handle this going forward?  Implement the existing behavior for now and readdress?

**Comment by blink1073** [comment]
cf https://jupyter-client.readthedocs.io/en/latest/messaging.html#request-reply

**Comment by jasongrout** [comment]
We have talked about having a special area for orphaned output, but that probably would be orphaned output per kernel. @AlexTugarev - I think @blink1073 is right - if you run your code, but then halfway through run another cell, the background output starts populating the new cell.

We've also talked about a way for the backend to notify the frontend that outputs are not done for a particular execution. Maybe in that case, an idle status can be sent back, but not the execute_reply.

Definitely needs discussion, as the previous behavior was at best incomplete, and at worst case wrong.

**Comment by blink1073** [comment]
A hack workaround would be not auto-dispose kernel futures, but dispose the ones that are `done` after sending the next execution, which would mimic the behavior of the classic notebook.

**Comment by AlexTugarev** [comment]
Thanks for the open discussion. 

@jasongrout, @blink1073, I absolutely share your view that it is a problem on the back end. Mixing output from previous executions into the current cell sounds completely wrong. What we are trying to deal with are few output messages (i.e. stream messages) which can come delayed. The relaxed behavior of the classic notebook works fine for us.

**Comment by minrk** [comment]
> We've also talked about a way for the backend to notify the frontend that outputs are not done for a particular execution.

Not sending the idle message would be an adequate signal that output is incomplete. I don't know of any cases where that can be done and it is known that output.

> A hack workaround would be not auto-dispose kernel futures, but dispose the ones that are done after sending the next execution, which would mimic the behavior of the classic notebook.

That would result in preferable behavior in the notebook ~all of the time. There is still an upper limit on the number of active output callbacks (the number of cells), solving the problem of disposing of futures, and one doesn't have to worry about async output ordering anymore. I think it's less of a hack than disposing of futures and then dealing with the async output in a special way.

**Comment by jasongrout** [comment]
> A hack workaround would be not auto-dispose kernel futures, but dispose the ones that are done after sending the next execution, which would mimic the behavior of the classic notebook.

When we were talking later, I realized @blink1073 meant things would be disposed after *the same cell* sent another execution. I think it would be enough to dispose after *any cell* sent another execution (though this may be harder to implement), since the backend currently will set the current execution as the header.

Note that in the case where you have someone else (maybe you in an adjacent terminal...) also interacting with the kernel, and they execute something while your thread is sending output, we will still have this problem of orphaned output  since your thread output will be sent as responses to their executions.

**Comment by blink1073** [comment]
My current thinking is that a *cell* should have at most one future that it maintains.  If you execute a cell that already has a future, it disposes the previous one.  

In the case of outputs from other sources, they would be ignored in the notebook.  The console could choose to *adopt* a message based from an `execute_input` `iopub` message using a function like `Kernel.adoptMessage(msgId: string): IFuture`.

**Comment by minrk** [comment]
> My current thinking is that a cell should have at most one future that it maintains. If you execute a cell that already has a future, it disposes the previous one.

Yes, I think that definitely makes sense. Keeping the 'current' future for each cell open, even after it receives status:idle.

**Comment by glyph** [comment]
The context where I encountered it: https://twitter.com/glyph/status/767066633076518914

**Comment by blink1073** [comment]
I agree with @minrk's comments [here](https://github.com/jupyter/notebook/pull/1826#issuecomment-253239482), to be implemented as follows: do not dispose of the future when executing on a code cell widget, but keep it as a private variable and dispose of it on the next execution.

**Comment by rgbkrk** [comment]
> do not dispose of the future when executing on a code cell widget, but keep it as a private variable and dispose of it on the next execution.

Well stated.
