### ISSUE TITLE
While trying to delete a file, 'Invalid response : 500 internal server error' occured

### ISSUE THREAD

**Issue by hellojinwoo** [jupyterlab/jupyterlab#6291]
**Describe the bug**
1. While trying to delete a file such as '.csv file' or '.ipynb file' on jupyter lab, I encountered an error message saying 'Delete failed. Invalid response : 500 internal server error'. This does not happen when I delete files on bash, but only happens on Jupyter lab UI.

2. This 'delete failed' bug takes place only on the virtual environment. With my base environment, it does not take place.

3. This error only happens on the linux environment. 
 
**To Reproduce**

1. Connect to my lab's computer with cmd (the lab computer uses Linux) : `ssh -L localhost:9999:localhost:9999 -p xxxx hellojinwoo@ip.address` ( You cannot connect to my lab's server. Just providing you with this information to give you a sense of where this error comes from) 
2. Create a new environment on linux : `conda create --name GPLVM python=3.7 -y`
3. Activate your new environment : `source activate GPLVM`
4. Open the Jupyter lab : `Jupyter lab --port 9999` 
5. Try to delete a file.

**Expected behavior**
Should delete a file

**Error Code**
```````
[W 19:24:24.024 LabApp] delete /s_2508933390.csv
[E 19:24:24.025 LabApp] Uncaught exception DELETE /api/contents/s_2508933390.csv?1556706267285 (::1)
    HTTPServerRequest(protocol='http', host='localhost:9999', method='DELETE', uri='/api/contents/s_2508933390.csv?1556706267285', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/hellojinwoo/anaconda3/lib/python3.7/site-packages/send2trash/plat_other.py", line 141, in find_ext_volume_fallback_trash
        check_create(trash_dir)
      File "/home/hellojinwoo/anaconda3/lib/python3.7/site-packages/send2trash/plat_other.py", line 86, in check_create
        os.makedirs(dir, 0o700)
      File "/home/hellojinwoo/anaconda3/lib/python3.7/os.py", line 221, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: b'/media/860evo1tb/.Trash-1013'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/hellojinwoo/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/home/hellojinwoo/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/home/hellojinwoo/anaconda3/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 235, in delete
        yield gen.maybe_future(cm.delete(path))
      File "/home/hellojinwoo/anaconda3/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 279, in delete
        self.delete_file(path)
      File "/home/hellojinwoo/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 540, in delete_file
        send2trash(os_path)
      File "/home/hellojinwoo/anaconda3/lib/python3.7/site-packages/send2trash/plat_other.py", line 191, in send2trash
        dest_trash = find_ext_volume_trash(topdir)
      File "/home/hellojinwoo/anaconda3/lib/python3.7/site-packages/send2trash/plat_other.py", line 151, in find_ext_volume_trash
        trash_dir = find_ext_volume_fallback_trash(volume_root)
      File "/home/hellojinwoo/anaconda3/lib/python3.7/site-packages/send2trash/plat_other.py", line 144, in find_ext_volume_fallback_trash
        raise TrashPermissionError(e.filename)
    send2trash.exceptions.TrashPermissionError: [Errno 13] Permission denied: b'/media/860evo1tb/.Trash-1013'
[W 19:24:24.026 LabApp] Unhandled error
[E 19:24:24.026 LabApp] {
      "Host": "localhost:9999",
      "Connection": "keep-alive",
      "Authorization": "token c69e77c0421da2e41386723803fee1a31c6b9aeed4ebaae6",
      "Origin": "http://localhost:9999",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Whale/1.5.71.15 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:9999/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
      "Cookie": "_xsrf=2|26d280e3|3ad7dc93aaa1eb0f72a2ec2f261ca072|1554251905; username-localhost-9998=\"2|1:0|10:1556178317|23:username-localhost-9998|44:MTMyOGE3OWM4MmU5NDYyYjhlZWFjNWMwODMyNDczNjE=|b057aaf4c9148b9b2fdb4a289aa27b42bd2427478906145de262f2b09a8761e1\"; username-localhost-9997=\"2|1:0|10:1556178501|23:username-localhost-9997|44:NDViZGFiZWI5ZDZkNDM5MzhhYmE1ZmI3NWJmYjZhZTk=|cd00df70d204d7f4d672a21f5bf200910d2f83c2d476d55677c71f7f7526710e\"; username-localhost-8888=\"2|1:0|10:1556705654|23:username-localhost-8888|44:M2U1MDhlNjFkMWU0NGJkNDkzOTJhYmQ4OTc0ZmZkYmI=|cf3a801a860518677ea9ab5c16434254b6cd1c1bf8857c97a501885917a423e5\"; username-localhost-9999=\"2|1:0|10:1556706263|23:username-localhost-9999|44:YjczNDk5OGRiNmE1NGY3ZThkZDk2Y2RjOWRhOTc5Mjg=|7a3a38fff7acc1f3a5a92eb284c3a761d9180ff403b99a800ffafb577a9e3fe6\""
    }
[E 19:24:24.026 LabApp] 500 DELETE /api/contents/s_2508933390.csv?1556706267285 (::1) 2.54ms referer=http://localhost:9999/lab
```````

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-47-generic x86_64)
- Browser : Naver whale v1.5.71.15 ( https://whale.naver.com/en ) 
- JupyterLab : 0.35.5

**Comment by agoose77** [comment]
Jupyter Notebook uses `send2trash` to delete files. It appears it does not have permission to create a trash directory. I'm not familiar with this, but it seems like the default trash directory doesn't exist, and this fallback doesn't have permission. @jasongrout perhaps knows?

**Comment by jasongrout** [comment]
I don't know, but I remember there being some changes in Jupyter Notebook server that had to do with trash. Regardless, this is an error with the jupyter notebook server (i.e., the backend server), not JupyterLab - JupyterLab is just showing you the error from the server.

I would: (a) try upgrading Jupyter Notebook (what version do you have?), and (b) post an issue on the jupyter notebook repo: https://github.com/jupyter/notebook/tree/master/notebook). Can you reproduce the issue with the classic notebook (launch it from the JupyterLab help menu to make sure you are getting exactly the same server).

**Comment by jasongrout** [comment]
Closing since there was no response. If you'd like to debug this further, please post here and we can reopen (though it may make more sense to open it in the notebook repo, given the errors above).

**Comment by AlbertUlysses** [comment]
I know this is late but I would like to add my experience and how I solved this issue for anyone in the future. I was trying to delete a .ipynb file but I got the same error. The issue for me was that I was still running the kernel while I was trying to delete it. In jupyter  lab you can x out of a notebook but it doesn't mean the kernel has been shutdown. After shutting down the kernel using the running tab "shut down" button, the delete was successful. I am running jupyter lab in an anaconda vm using windows.
