### ISSUE TITLE
_repr_svg_ broken WRT classic notebook

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#6295]
The `_repr_svg_` rendering seem to be incorrect:

<img width="828" alt="Screen Shot 2019-05-01 at 9 20 19 PM" src="https://user-images.githubusercontent.com/335567/57052697-fa124780-6c56-11e9-82df-14b948ff39f1.png">

Works in classic notebook (taken from ipython-in-depth tutorial)

```
from IPython.display import (
    display_svg
)
class MyCircle(object):

    def __init__(self, center=(0.0,0.0), radius=1.0, color='blue'):
        self.center = center
        self.radius = radius
        self.color = color
        
    def _repr_svg_(self):
        return """<svg width="100px" height="100px">
           <circle cx="50" cy="50" r="20" stroke="black" stroke-width="1" fill="blue"/>
        </svg>"""

display_svg(MyCircle())
```

Both in latest alpha and 0.35.

**Comment by jasongrout** [comment]
Because we use an image tag, rather than embedding the svg inline, you must include the xmlns attribute:

```python
from IPython.display import (
    display_svg
)
class MyCircle(object):

    def __init__(self, center=(0.0,0.0), radius=1.0, color='blue'):
        self.center = center
        self.radius = radius
        self.color = color
        
    def _repr_svg_(self):
        return """<svg xmlns="http://www.w3.org/2000/svg" width="100px" height="100px">
           <circle cx="50" cy="50" r="20" stroke="black" stroke-width="1" fill="blue"/>
        </svg>"""

display_svg(MyCircle())
```
Should we try to modify the user code to add that, or should we rely on the user providing that?

**Comment by jasongrout** [comment]
> Should we try to modify the user code to add that

If it's not too error-prone, we should probably modify the svg data, otherwise there may be lots of notebooks from the past that won't render svg. We may be able to get away with just replacing an initial `<svg ` with `<svg xmlns="http://www.w3.org/2000/svg" ` if we can't find the appropriate string in the svg data.

**Comment by jasongrout** [comment]
Setting to good first issue, since I think a workaround is straightforward, as noted in the last comment above.

The code to be modified is at https://github.com/jupyterlab/jupyterlab/blob/8c72b122dcf42ac5ad02a233e84fec1032b5335a/packages/rendermime/src/renderers.ts#L404-L430

**Comment by Carreau** [comment]
If we don't add this workaround, It would be great to have a warning printed. At least we should update all the tutorial material; examples, and reach to libraries to actually include the `xmlns="http://www.w3.org/2000/svg"`

**Comment by ian-r-rose** [comment]
I suspect using something like `DOMParser` might be more robust than a find/replace regex that we would write.

**Comment by bollwyvl** [comment]
I am SO torn here: on the one hand, I love being able to do things with the actual SVG DOM (like tweaking style from generated things). On the other, generated SVG has a nasty habit of including `class`es and `id`s used in fascinating ways (e.g. a gradient is a nest of references to `ref`s) that will eventually conflict providing hilarious results.

@ian-r-rose the issue with trying to parse first, namespace later, is that an `<svg>` without that namespace isn't actually well-formed, and so might parse in exciting ways. Adding a namespace dynamically is also peril-fraught. So in this case, regex might indeed be the right way to go.

**Comment by saulshanabrook** [comment]
Quick fix: Replace `<[ ]*svg[ ]` with `<svg xmlns="http://www.w3.org/2000/svg"` and hopefully this still  works if it ends up there twice.
