### ISSUE TITLE
Weird mardown code style in alpha3

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#6296]
0.35:

<img width="613" alt="Screen Shot 2019-05-01 at 9 22 43 PM" src="https://user-images.githubusercontent.com/335567/57052741-49587800-6c57-11e9-9343-99e0630ca182.png">

1.0 latest alpha

<img width="698" alt="Screen Shot 2019-05-01 at 9 22 34 PM" src="https://user-images.githubusercontent.com/335567/57052750-55dcd080-6c57-11e9-982b-3a3bba832384.png">

**Comment by jasongrout** [comment]
Looks like this is an unintended consequence of https://github.com/jupyterlab/jupyterlab/pull/5628

**Comment by jasongrout** [comment]
Looks like the `.jp-RenderedHTMLCommon code` selector needs to differentiate between inline code elements and non-inline code elements. It tried to do this before by having `.jp-RenderedHTMLCommon p > code`, but that excluded list elements, which was what #5628 was addressing.

**Comment by jasongrout** [comment]
Perhaps `.jp-RenderedHTMLCommon :not(pre) > code` works better? Here's what it looks like if I change https://github.com/jupyterlab/jupyterlab/blob/98c82e6d2bd1b65460fa038d9bc472bf6bc6cb8c/packages/rendermime/style/index.css#L334

<img width="305" alt="Screen Shot 2019-05-01 at 10 45 38 PM" src="https://user-images.githubusercontent.com/192614/57058141-8c3d3e80-6c9d-11e9-9eb1-3beceebe8d32.png">

**Comment by jasongrout** [comment]
Fixed by #6308.
