### ISSUE TITLE
matplotlib widget stdout/stderr in event handling callbacks not printed

### ISSUE THREAD

**Issue by w-hc** [jupyterlab/jupyterlab#6309]
**Describe the bug**
Under %matplotlib widget, when I attach an event handler callback to a canvas, the print statements and error messages, which can be crucial for debugging, are not displayed. However, print/error msgs can be displayed in jupyter-notebook with the same code.

**To Reproduce**

```python
%matplotlib widget
import numpy as np
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot(np.random.rand(10))

def onclick(event):
    print('%s click: button=%d, x=%d, y=%d, xdata=%f, ydata=%f' %
          ('double' if event.dblclick else 'single', event.button,
           event.x, event.y, event.xdata, event.ydata))

cid = fig.canvas.mpl_connect('button_press_event', onclick)
```

**Expected behavior**
The behavior in jupyter-lab should be consistent with that of jupyter-notebook. Outputs to stdout and stderr should not be swallowed. 

**Desktop (please complete the following information):**

- CentOS Linux 7 (Core). Jupyterlab is run remotely at this server.
- Safari Version 12.1 (14607.1.40.1.4)
- JupyterLab 0.35.5

**Comment by jasongrout** [comment]
Please use an output widget to capture these. See the ipywidgets documentation: https://ipywidgets.readthedocs.io/en/stable/examples/Output%20Widget.html#Debugging-errors-in-callbacks-with-the-output-widget

Eventually in JupyterLab we'll have a notebook-wide output section to put these messages. This is being tracked in https://github.com/jupyterlab/jupyterlab/issues/1254, where more context is given for the behavior.

**Comment by jasongrout** [comment]
To use an output widget, just declare the widget:

```python
from ipywidgets import Output
output = Output()
display(output)
```

Then decorate your callback:

```
@output.capture()
def onclick(event):
    print('%s click: button=%d, x=%d, y=%d, xdata=%f, ydata=%f' %
          ('double' if event.dblclick else 'single', event.button,
           event.x, event.y, event.xdata, event.ydata))
```

**Comment by jasongrout** [comment]
(Closing since this is being tracked in #1254)

**Comment by w-hc** [comment]
Thanks a lot!
