### ISSUE TITLE
Documentation links are broken on live site

### ISSUE THREAD

**Issue by gravitypersists** [jupyterlab/jupyterlab#6316]
for instance, click on "Document widgets" in this page:

https://jupyterlab.readthedocs.io/en/stable/developer/documents.html

it will take you to the broken link:

http://jupyterlab.github.io/jupyterlab/classes/_docregistry_src_registry_.documentregistry.html

the correct link is 

https://jupyterlab.github.io/jupyterlab/docregistry/classes/documentregistry.html

**Comment by jasongrout** [comment]
Thanks for pointing this out. This is fixed on master, evidenced by looking at the 'latest' docs: https://jupyterlab.readthedocs.io/en/latest/developer/documents.html
