### ISSUE TITLE
"Merge cells" is missing from context menu when multiple cells are selected

### ISSUE THREAD

**Issue by abetkin** [jupyterlab/jupyterlab#6318]
1. Select multiple cells by clicking on them while holding Shift.
2. Right click to show the context menu.
3. No way to merge cells is available from the menu

Screenshots

![no_merge](https://user-images.githubusercontent.com/2223279/57298180-3f60ca00-70da-11e9-882c-e5353bfb3687.png)

**Comment by mindnect** [comment]
I think 'Insert cell' is missing in the context menu too.
