### ISSUE TITLE
Find and replace menu item

### ISSUE THREAD

**Issue by bsyouness** [jupyterlab/jupyterlab#6322]
@aschlaep 

**The issue**
"Find and replace" isn't an active menu item while in a notebook. Also, although active in a text document, it spins up the older version of "find and replace".

**To Reproduce**

1. Go to the "Edit" menu
2. Go to "Find and Replace"

**Expected behavior**
The menu item "find and replace" should be active whenever a notebook, text or markdown file is open and should trigger the new "find and replace".

**Comment by jasongrout** [comment]
Can you try the latest prerelease, 1.0a3? I think this has been fixed.

**Comment by bsyouness** [comment]
I tried the latest prerelease. It hasn't.

**Comment by jasongrout** [comment]
I just confirmed that. Looks like we missed changing that menu item. And it looks like the command palette item for the new find and replace still just says "Find..." instead of "Find and Replace...".

CC @aschlaep
