### ISSUE TITLE
Syntax highlighting in f-strings

### ISSUE THREAD

**Issue by guillemglez** [jupyterlab/jupyterlab#6323]
**Describe the bug**
When adding string literals inside formatted strings (as introduced in Python 3.6) curly braces syntax highlighting gets confused and treats non-string statements as strings and vice-versa for the rest of the line.
This also includes following statements in the line, even not being part of the f-string.

**To Reproduce**
Add a string statement inside curly braces in an f-string, like:
`print(f"{'a+b'} is:", a+b)`

**Expected behavior**
Syntax highlighting should highlight correctly string and non-string characters.

**Screenshots**
An example:
![imatge](https://user-images.githubusercontent.com/25482726/57368811-5cee6c00-718c-11e9-877f-6b9492c8ca80.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Google Chrome Version 74.0.3729.131 (Official Build) (64-bit)
- JupyterLab Version 0.35.3

**Comment by jasongrout** [comment]
Fixed in master (probably by a Codemirror upgrade):
<img width="276" alt="Screen Shot 2019-05-08 at 3 09 44 PM" src="https://user-images.githubusercontent.com/192614/57411756-0b6ecd00-71de-11e9-8468-6e8dda78a021.png">
