### ISSUE TITLE
delimiters support for hash

### ISSUE THREAD

**Issue by rolandettema** [jupyterlab/jupyterlab#6324]
The current delimiters supported in the dropdown for table view of CSV are commas, semicolons, tab and pipe. Is there interest in supporting hash (#) delimitation?

**Comment by jasongrout** [comment]
If you see files like this, feel free to add it. I didn't have it in there because I've never seen that delimiter in the wild.

The code is at https://github.com/jupyterlab/jupyterlab/blob/52b871d72ed20b2f8d38a404c43dad4036a596b4/packages/csvviewer/src/toolbar.ts#L14-L22

**Comment by jasongrout** [comment]
(just curious, where do you see files with hash delimiters?)
