### ISSUE TITLE
Simple input dialogs

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#6326]
**Describe the enhancement**

In Qt framework, there are helper functions to request single information through dialog boxes: https://doc.qt.io/qt-5/qinputdialog.html#static-public-members

I think extensions authors could benefit from similar helpers like:

```ts
let n = getNumber({
 title: 'What\'s your code?',
 label: 'Code'
});
let t = getText({
 title: 'What\'s your name?',
 label: 'Name',
 placeholder: 'John Smith'
});
let i = getItem({
 title: 'Choose your favourite color',
 label: 'Color',
 items: ['red', 'blue', 'green']
});
```

**Comment by blink1073** [comment]
Sounds good!  Btw, you have a pending LinkedIn request from me. 😉
