### ISSUE TITLE
Jupyterlab won't launch with tornado 6.0.2

### ISSUE THREAD

**Issue by shivendra90** [jupyterlab/jupyterlab#6328]
When launching lab from terminal, I'm getting an attribute error related to a 'tornado.web' module. Updated to lab 0.35.5 just day before yesterday and have had no issues with any of its ever since. However, since I executed `conda update --packages` to upgrade the whole anaconda environment, it looks like the tornado module is not allowing it to launch and is more than an year old issue:
`Traceback (most recent call last):`
  `File "/Users/Shiv/anaconda3/bin/jupyter-lab", line 11, in <module>`
   ` sys.exit(main())`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance`
   ` return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance`
`    app.initialize(argv)`
`  File "</Users/Shiv/anaconda3/lib/python3.6/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error`
`    return method(app, *args, **kwargs)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1628, in initialize`
`    self.init_configurables()`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1314, in init_configurables`
 `   parent=self,`
 ` File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/nb_conda_kernels/manager.py", line 36, in __init__`
`    super(CondaKernelSpecManager, self).__init__(**kwargs)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/config/configurable.py", line 84, in __init__`
 `   self.config = config`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 585, in __set__`
`    self.set(obj, value)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 574, in set
    obj._notify_trait(self.name, old_value, new_value)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1139, in _notify_trait`
`    type='change',`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1176, in notify_change`
`    c(change)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 819, in compatible_observer`
`    return func(self, change)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/config/configurable.py", line 186, in _config_changed`
`    self._load_config(change.new, traits=traits, section_names=section_names)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/config/configurable.py", line 153, in _load_config`
`    setattr(self, name, deepcopy(config_value))`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 585, in __set__`
`    self.set(obj, value)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 559, in set`
 `   new_value = self._validate(obj, value)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 591, in _validate`
`    value = self.validate(obj, value)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1576, in validate`
`    value = self._resolve_string(value)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1507, in _resolve_string`
`    return import_item(string)`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/traitlets/utils/importstring.py", line 34, in import_item`
`    module = __import__(package, fromlist=[obj])`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/beakerx/__init__.py", line 20, in <module>`
  `  from .handlers import load_jupyter_server_extension`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/beakerx/handlers.py", line 28, in <module>`
 `   class BeakerxRestHandler(APIHandler):`
`  File "/Users/Shiv/anaconda3/lib/python3.6/site-packages/beakerx/handlers.py", line 34, in BeakerxRestHandler`
`    @tornado.web.asynchronous`
`AttributeError: module 'tornado.web' has no attribute 'asynchronous'`

**Comment by blink1073** [comment]
Hi @shivendra90, looking at your traceback, it looks like `beakerx` is not yet compatible with tornado 6.0.  Please file an issue there.  In the mean time, you can downgrade to tornado 5.0 or disable the beakerx extension.

**Comment by shivendra90** [comment]
Thanks @blink1073 !

**Comment by shivendra90** [comment]
I believe there seemed to be some issue with the existing beakerx installation 1.3.0 that was not allowing lab to launch. Removed beakerx and did a clean install of the latest 1.4.1 and now no errors, lab launches successfully. Not a problem with tornado either.
