### ISSUE TITLE
Lack of merge cell commands?

### ISSUE THREAD

**Issue by AlcoholV** [jupyterlab/jupyterlab#6330]
Notebook has "Merge Cell Above", "Merge Cell Below" commands.
But, I can't see under edit menu in the Jupyerlab.
It's very useful when cell need to be execute partially.
Also, it will be very convenient if I can run it inside the cell with a short key.

It likes,
1. Ctrl+Shift + - (Split Cell)
2. Execute and edit cell
3. Merge Cell Below (Ctrl+Shift+M)

Thanks.

## Lab Screenshot
![lab](https://user-images.githubusercontent.com/3617014/57486589-41e53e80-72e9-11e9-8876-d12a6e4b4a50.png)

## Notebook Screenshot
![notebook](https://user-images.githubusercontent.com/3617014/57480807-b0bb9b00-72db-11e9-8623-ab0561e7da29.png)

**Comment by jasongrout** [comment]
Thanks for pointing this out. It's really useful to hear people's workflows.

**Comment by lotomb** [comment]
I was looking for this. A long time ago, I worked with "The sage Notebook", where you can merge a cell with the one above it using Ctrl+Backspace inside the cell. So I find myself hitting Ctrl+Backspace to no avail.
(I seem to remember that it only worked when the cursor is at position 0 in the cell, which would make sense to me.)

**Comment by jasongrout** [comment]
> A long time ago, I worked with "The Sage Notebook", where you can merge a cell with the one above it using Ctrl+Backspace inside the cell. So I find myself hitting Ctrl+Backspace to no avail.

Good memories! I remember using that quite a bit as well.

**Comment by jasongrout** [comment]
I think it would be great to have a command for merging above/below, and a keyboard shortcut like you mention for specific cases.

Here's a related PR that deletes an empty cell with Backspace: https://github.com/jupyterlab/jupyterlab/pull/7834

**Comment by jasongrout** [comment]
I'll mention an argument for having a nice keyboard shortcut for this is that you don't have to exit edit mode in order to merge - you can stay focused in edit mode (like illustrated in the two examples above).

**Comment by jasongrout** [comment]
Setting as a good first issue. The Merge code is at https://github.com/jupyterlab/jupyterlab/blob/30aef10f21707c0ec74ee6acc487a6c0948ca821/packages/notebook/src/actions.tsx#L185, and exposed as a command https://github.com/jupyterlab/jupyterlab/blob/30aef10f21707c0ec74ee6acc487a6c0948ca821/packages/notebook-extension/src/index.ts#L1443-L1453

Setting as a good first issue - first I think would be another merge function in actions.tsx that just merges to the cell above or below the active cell, then exposing that function in a command, then finally deciding how to deal with a keyboard shortcut.
