### ISSUE TITLE
Changelog for 0.35.0 - 0.35.6?

### ISSUE THREAD

**Issue by aldanor** [jupyterlab/jupyterlab#6341]
Just wondering, are there supposed to be any entries? The last entry for pre-1.x is from half a year ago, 0.35.0 release. Is the changelog meant to be updated with micro version releases?

Cheers.

**Comment by blink1073** [comment]
Hi @aldanor.  We haven't typically made release notes for the patches. In this case it was this fix: https://github.com/jupyterlab/jupyterlab/pull/6304

**Comment by aldanor** [comment]
Fair enough, thanks! Up to you guys - I just figured I'd note it in case anyone might have unintentionally forgotten :)

**Comment by jasongrout** [comment]
Feel free to put in a pr for the change log, if you'd like

**Comment by jasongrout** [comment]
Feel free to put in a pr for the change log, if you'd like
