### ISSUE TITLE
Cannot open file via "Open from path"

### ISSUE THREAD

**Issue by bagustris** [jupyterlab/jupyterlab#6351]
**Describe the bug**
Cannot open a file, the error said: file not found. I tried both *.ipynb and *.py files, also other file types.

**To Reproduce**

1. Go to 'FIle'
2. Click on 'Open from path'
3. Insert the 'path'

**Expected behavior**
(python) files from "open from path" is opened in tab.

**Screenshots**
![Screenshot from 2019-05-15 10-55-25](https://user-images.githubusercontent.com/3158361/57743544-7483a280-7700-11e9-8f42-f3e220fb1f75.png)
![Screenshot from 2019-05-15 10-55-41](https://user-images.githubusercontent.com/3158361/57743546-7483a280-7700-11e9-8e70-9121ab980cf0.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 16.04
- Browser: Firefox 66.0.5
- JupyterLab:  0.35.6

**Comment by jasongrout** [comment]
What directory did you launch jupyterlab in, and what is the path you are trying to open? The paths for this dialog are rooted at the directory in which you launched jupyterlab.

**Comment by bagustris** [comment]
I open with in home, and I want to open directory in a place using absolute path like,
`/media/user/data/file.py`

I check the ownership of the path, and it is already owned by user.
In case of opening files in home directory, it works.

So, that feature (open from path) is only working on the current rooted directory where jupyterlab is opened?

**Comment by jasongrout** [comment]
> So, that feature (open from path) is only working on the current rooted directory where jupyterlab is opened?

Right. A security decision for the notebook server is that it will only serve files below the directory it was started in.

**Comment by jasongrout** [comment]
(note that symbolic links work - if you make a symbolic link from that file into somewhere below where the server started, it should work)

**Comment by jasongrout** [comment]
Closing as answered - feel free to ask more questions if you need, though.
