### ISSUE TITLE
Large notebooks hanging up

### ISSUE THREAD

**Issue by dkangin** [jupyterlab/jupyterlab#6353]
**Describe the bug**
When using large notebooks, they cause the whole jupyter web ui hanging up. 

**To Reproduce**
Steps to reproduce the behaviour:
- create a notebook with debug outputs in the loop
- try to open this notebook in jupyter lab
- see the web ui hanging

**Expected behaviour**
Cropping of the notebook output

**Desktop (please complete the following information):**

- OS: [ MacOS]
- Browser [ Safari 12.0.3]
- JupyterLab [ JupyterLab 0.34.5]

**Comment by jasongrout** [comment]
We're tracking this at https://github.com/jupyterlab/jupyterlab/issues/4292 and https://github.com/jupyterlab/jupyterlab/issues/1639. Let's move this discussion to one of those issues. Thanks!
