### ISSUE TITLE
Ctrl-W on windows closes browser window, not JupyterLab tab

### ISSUE THREAD

**Issue by ivanov** [jupyterlab/jupyterlab#6357]
**Describe the bug**
`Accel-W` is meant to close a JupyterLab tab, and on Windows `Accel` maps to `Ctrl`. 

**Screenshots**
![image](https://user-images.githubusercontent.com/118211/57800212-afd4a000-7705-11e9-9732-ebe567cb14be.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browsers: Chrome 74.0.3729.131, Firefox 66.0.5
- JupyterLab master  b58e1ddce3f42660f699707f9d399d908d65a240

We should do some subset of - providing an alternative keyboard shortcut on windows for closing JupyterLab tabs by default, and also at least not display the misleading `ctrl-w` shortcut on windows, since that will close the whole browser tab, not just a jupyterlab tab within that tab.

**Comment by ivanov** [comment]
in diagram-codesprint/jupyterlab#6, @corvinb also identified that this is an issue for MacOS 10.14.4 for Chrome and Safari.

**Comment by jasongrout** [comment]
Looks like Accel W is a bad shortcut for closing a tab. Any suggestions for a better one?

**Comment by vidartf** [comment]
Alt + W ?

**Comment by jasongrout** [comment]
According to https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts, Alt+W seems available.

On my mac, Alt+W inputs the greek sigma: ∑

**Comment by jasongrout** [comment]
Let's make this a good first issue to change the keyboard shortcut to Alt+W, which seems like it may not do anything in a windows browser either.

Fixing this issue is changing `Accel W` to `Alt W` here: https://github.com/jupyterlab/jupyterlab/blob/df6228712f68b332312f68cf65bef9634bdb7685/packages/application-extension/schema/main.json#L16-L20
