### ISSUE TITLE
Terminal session is not removed from manager when terminated

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#6363]
**Describe the bug**

Following the nice feature in #6339, I realized the `session` is not remove from the `Set` in the `TerminalManager` although the session has been disposed.

**To Reproduce**

1. Open a terminal
2. Type the command to exit the terminal

**Expected behavior**

Remove the disposed session from the terminal manager in `onTerminated`.

**Desktop:**

- OS:  Windows 10
- Browser chrome 73.0
- JupyterLab master 88cbc53a8949968bf93070b01f2fe94ffa7c3cc5

**Additional context**

The session should be removed in `_onTerminated` method of `TerminalManager`.

https://github.com/jupyterlab/jupyterlab/blob/88cbc53a8949968bf93070b01f2fe94ffa7c3cc5/packages/services/src/terminal/manager.ts#L285-L294.

**Comment by blink1073** [comment]
🎉
