### ISSUE TITLE
npm publish sync

### ISSUE THREAD

**Issue by ppeeou** [jupyterlab/jupyterlab#6370]
Hi! Thanks for using JupyterLab.

I am developing it by changing the source in this repo.

The packages files `ex)  @jupyterlab/coreutils`  are different from what is in the npm repository and what is in github. (Both versions are the same)

ex) @jupyterlab/coreutils 3.0.0-alpha.6
- in the npm 
not exist `getNBConvertURL` method
- github 
exist `getNBConvertURL` method
https://github.com/jupyterlab/jupyterlab/blob/master/packages/coreutils/src/pageconfig.ts#L161

Could you publish and match the version?

**Comment by blink1073** [comment]
Thanks for the heads up, @ppeeou!  Once #6312 is merged I'll cut another prerelease of the JS and Python packages.

**Comment by ppeeou** [comment]
Thank you for your response.@blink1073 
I am waiting for this issue!

**Comment by blink1073** [comment]
Fixed by @jasongrout today with the alpha 5 release!
