### ISSUE TITLE
Can't scroll down the list of "Running Terminals and Kernels" 

### ISSUE THREAD

**Issue by manuzhang** [jupyterlab/jupyterlab#6371]
**Describe the bug**
I can't scroll down the list of "Running Terminals and Kernels" when there are so many of them

**To Reproduce**

Open as many terminals and kernels as possible

**Expected behavior**
I can scroll down to open the running kernel at the bottom

**Screenshots**
![image](https://user-images.githubusercontent.com/1191767/57922833-3be7f280-78d3-11e9-8dd1-46040c50cab6.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome 74.0
- JupyterLab: 1.0.0a3

**Comment by manuzhang** [comment]
@saulshanabrook

**Comment by jasongrout** [comment]
I reproduced this. I think it would be enough to add `overflow: auto` to the `jp-RunningSessions-section` class here: https://github.com/jupyterlab/jupyterlab/blob/594076f2e79a91758caa91ed3a69c216ecece422/packages/running/style/index.css#L58-L62
