### ISSUE TITLE
Can't connect to nbserver file from container

### ISSUE THREAD

**Issue by fonnesbeck** [jupyterlab/jupyterlab#6373]
When running Jupyter from a Linux container, my browser pops up and tries to open the nbserver file:

`file:///run/user/1000/jupyter/nbserver-269-open.html`

However, this file cannot be found. However the URL works just fine. Is there any way of sending the URL instead of the file by default?

Running Jupyterlab 0.35.6 on a Pixelbook.

**Comment by blink1073** [comment]
Hi @fonnesbeck, I believe this has the same underlying cause as https://github.com/jupyter/help/issues/496

**Comment by fonnesbeck** [comment]
OK, that makes sense. So no solution, imminent then? I was hoping one could easily pass the URL to the browser instead of the filename.

**Comment by blink1073** [comment]
No, I don't see a short term solution other than disabling `open_browser` in `jupyter_notebook_config.py` and using the non-file url given at the prompt.

**Comment by jasongrout** [comment]
Fixed by https://github.com/jupyter/notebook/pull/4999
