### ISSUE TITLE
IPython.display.code syntax highlighting doesn't work in Lab

### ISSUE THREAD

**Issue by bensteers** [jupyterlab/jupyterlab#6376]
## The basic problem

Pictures are useful. Basically, syntax highlighting doesn't work with IPython.display.Code widgets in Jupyterlab, but do in Notebooks. 
### What I get with Jupyterlab:
![image](https://user-images.githubusercontent.com/6741720/57987383-a3767d00-7a4e-11e9-9478-70ade8de0fbb.png)

### Notebook (desired outcome)
![image](https://user-images.githubusercontent.com/6741720/57987375-817cfa80-7a4e-11e9-8a85-e4934608fcbc.png)

## Diagnosis

Through some quick poking around in the inspector, it turns out that everything is being output the same (tokenized correctly, styles are injected right above the element), except for the classes on the wrapping output element.

In the Notebook: `class="output_subarea output_html rendered_html output_result"`

In Jupyterlab: `class="p-Widget jp-RenderedHTMLCommon jp-RenderedHTML jp-mod-trusted jp-OutputArea-output jp-OutputArea-executeResult"`

All of the styles are defined under `.output_html` which is the class that JupyterLab is missing. 

So I guess it can be changed through IPython here:

https://github.com/ipython/ipython/blob/d3ffae3ceb2df46437e16c97e9b6c9541eecb4ce/IPython/lib/display.py#L642 

But I'm not sure how it would be changed to support both Lab and Notebooks (does IPython have a way to know if it's in a lab or notebook environment?). The other option would be to add the class onto Jupyterlab Outputs but that seems a bit hacky.

**Comment by jasongrout** [comment]
Oh, interesting. IPython hardcodes the class name `output_html`, and embeds those style tags on the page.

> The other option would be to add the class onto Jupyterlab Outputs but that seems a bit hacky.

I don't see any other way to support IPython without changing IPython (and backwards compatibility is very important to us). I think there's probably not harm to adding the `output_html` class to our html outputs, but I agree it smells a bit that we're adding it for this one usecase.

Adding this class would be a change in JLab here: https://github.com/jupyterlab/jupyterlab/blob/6185bda1b29967bfdcce3d320774e8534a51ac1c/packages/rendermime/src/widgets.ts#L140

**Comment by bensteers** [comment]
The other option would be to do this:
```python
# change from:
style = '<style>{}</style>'.format(fmt.get_style_defs('.output_html'))
# to this:
style = '<style>{}\n{}</style>'.format(fmt.get_style_defs('.output_html'), 
                                       fmt.get_style_defs('.jp-RenderedHTML'))
```

Duplicate style rules aren't perfect either, but at least it puts the fix where the problem is, instead of in some other place. But I think either are fine fixes.

**Comment by jasongrout** [comment]
We could put in a PR to IPython. It does mean that in some sense we aren't strictly backwards compatible with older notebooks, but we've always said that the css and js apis of the classic notebook were not stable, so I think it's not *really* breaking what we've said is backwards compatible.

+1 to fixing this in IPython, since IPython is the one that is assuming things about the frontend.

Do you want to put in a PR to IPython? It's this line here: https://github.com/ipython/ipython/blob/d3ffae3ceb2df46437e16c97e9b6c9541eecb4ce/IPython/lib/display.py#L642

**Comment by bensteers** [comment]
True, it's not a breaking change. It's just not going to fix already-rendered notebooks, so they'll be in the same place that they are now.

I'm pretty swamped for the next couple days but I can do it around the end of the week/weekend. 

My current workaround is just calling `out.add_class('output_html')` before I wanted to render code which is working fine for me now (in case someone else is waiting anxiously for the fix).

**Comment by jasongrout** [comment]
Closing since we've opened up https://github.com/ipython/ipython/issues/11747 upstream.
