### ISSUE TITLE
Why markdown files can't run like ipynb files?

### ISSUE THREAD

**Issue by adaaaaaa** [jupyterlab/jupyterlab#6377]
is there any extension doing the same thing like jupyter-notebook's notedown extension?

**Comment by jasongrout** [comment]
There is something like jupytext: https://github.com/mwouts/jupytext

You can also open a console and run code blocks from a markdown file with shift-enter.

**Comment by adaaaaaa** [comment]
@jasongrout 
i find a solution:
`jupytext --to ipynb *.md`
that convert all the md file in a folder to ipynb...
