### ISSUE TITLE
Code duplication: Dialog.prompt and InputDialog

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#6378]
There are duplicated functionalities between `Dialog.prompt<T>` (that I found only yesterday in the code 😢 ) and `InputDialog` introduced in #6326.

https://github.com/jupyterlab/jupyterlab/blob/fc81a1412631accde72ef8e5dd2abd76611d62d9/packages/apputils/src/dialog.ts#L570-L586

https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/inputdialog.ts

**Reference**

- JupyterLab master fc81a14

**Comment by jasongrout** [comment]
@fcollonval - would this be a good first issue?

**Comment by fcollonval** [comment]
@jasongrout thx for the suggestion. I think it's a good opportunity to list helper dialogs in the developer documentation.
