### ISSUE TITLE
Rank seems not to be working on addToTopArea

### ISSUE THREAD

**Issue by felipebmendes** [jupyterlab/jupyterlab#6379]
Hey guys,

I'm trying to add a widget I've developed to the right side of jupyter lab's `top bar`. However, as shown in the image below, the widget is being added to the left of the bar no matter what value I set to `rank`.

![image](https://user-images.githubusercontent.com/37848351/58030295-adeb5200-7af4-11e9-95ad-83715e35b3f9.png)

This is the code of my extension:

```
function activateWidgetExtension(app: JupyterLab) {
    let topBarWidget: TopBarWidget = new TopBarWidget({ app, id: 'topBar'});
    let topBar: TopBar = new TopBar(); // 
    topBar.id = 'toolbar-top';
    topBar.addClass("jp-TopBar");
    topBar.addItem('custom-btn', topBarWidget);

    app.shell.addToTopArea(topBar, { rank: 100 });
}

export class TopBar extends Toolbar<Widget> {
    addItem(name: string, item: Widget): boolean {
      item.addClass('jp-TopBar-item');
      return super.addItem(name, item);
    }
  }
```

**Comment by jasongrout** [comment]
What version of JLab?

It looks like in 0.35.x, things are added in insertion order: https://github.com/jupyterlab/jupyterlab/blob/0.35.x/packages/application/src/shell.ts

**Comment by felipebmendes** [comment]
@jasongrout the version is `0.35.4`.

I don't know if it's the best solution but I created a `Promise` that retries while the top area is empty, then I add my widget to it.

Thanks for your help.
