### ISSUE TITLE
All extensions reload on browser refresh

### ISSUE THREAD

**Issue by mayadebellis** [jupyterlab/jupyterlab#6386]
**Describe the bug**
I have multiple extensions enabled in my jupyterlab instance. If I refresh the page in my browser, all of the front end jupyterlab extensions reload from scratch. All of the previous states of my extensions are reset. In the console I get the standard `x extension is activated!` messages that print at the end of an extension's activate function. 

Why do all of extensions reactivate on browser refresh? Is there anyway to stop this from happening? 

**To Reproduce**

1. Install an extension
2. Refresh browser page. Cmd + R

**Desktop (please complete the following information):**

- OS: MacOS High Sierra
- Browser: chrome 74.0
- JupyterLab:  0.35.4

**Comment by jasongrout** [comment]
Reloading a page starts the jlab javascript from scratch - that's how javascript and browsers work. As such, each extension is activated as part of the bootstrapping process for jupyterlab.

If you want to save state across refreshes, you'll need to communicate that state to the server continually, store it in local storage continually, etc. The instance tracker restoration logic also provides a way to serialize things like layout state.
