### ISSUE TITLE
Searchable API docs

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6387]
@bionicles points out in https://github.com/jupyterlab/jupyterlab/issues/6380#issuecomment-494841791 that https://jupyterlab.github.io/jupyterlab/ has no top-level search to search over all packages, so it is *really* tedious to find something if you don't know what package it is in. We used to consolidate everything into a single typedoc interface. Now that we don't, it makes it significantly harder to explore the api docs.

We should find some way to search across all api docs again.

**Comment by krassowski** [comment]
This works as of today on both https://jupyterlab.readthedocs.io/en/latest/ and https://jupyterlab.readthedocs.io/en/latest/api/index.html. Please reopen if needed.
