### ISSUE TITLE
CSS Should not be imported in our non-extension packages

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6390]
**Describe the bug**
We currently import css in many of our `index.ts` files.  This means that consumers of the library who just want a token or to use a class must also load the css.  We should load the css separately.  

Webpack does not yet support a top level `style` [parameter](https://github.com/webpack-contrib/css-loader/issues/683) that is a path to the CSS entry point.  Eventually, we should be able to `@import url("~@jupyterlab/application");` in CSS and it would get resolved.  I verified that the current versions of Webpack and CSS loader throw the error reported by the OP in the issue linked above.  For now, we have to import the CSS in our extensions.

For now:
- Remove all CSS imports from our non-extension packages and import them in the extensions instead
   We need to make sure that dependent packages are loaded as well (e.g. cells is loaded in notebook).
- Verify that the examples still work

Once CSS loader 2.2 is released (not for our 1.0): 
- Remove all CSS imports from our packages and replace them with a `style` parameter in `package.json`
- Create `style` folders in extensions that use the above syntax to import their dependent CSS
- Add `style` metadata to the extension package.json
- Template a `dev_mode/index.css` file that imports all of the extensions that have a `style` property in their `package.json` and importthat file from `dev_mode/index.js`
- Update our examples to use the import from css pattern
- Update the cookie cutter examples to use the same pattern

**Comment by blink1073** [comment]
@vidartf, unfortunately we can't yet use `@import`, I updated the comment above.

**Comment by ellisonbg** [comment]
Will the actual CSS still be in the non-extension?

**Comment by blink1073** [comment]
Yep!
