### ISSUE TITLE
Improve chances for tree shaking

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#6392]
This issue tracks follow-ups to #6302:
- [x] Replace CSS imports in non-extension packages with use of `style` field in package.json.
  - [x] Use `@import url("~package-name")` to import CSS in extension packages.
  - [x] Add some auto-generated CSS index for applications (@blink1073).
- [x] Add `sideEffects` field to all packages.

**Comment by blink1073** [comment]
cf #6390 😜

**Comment by jasongrout** [comment]
Is this targeted for 1.0?

**Comment by jasongrout** [comment]
Oh, I guess not since it requires css-loader 2.2, which hasn't been released yet. I'll tag it for 1.1.

**Comment by blink1073** [comment]
We can improve tree-shaking for the non-extension packages prior to css-loader 2.2.

**Comment by vidartf** [comment]
Should we close this, or keep it open to track change of imports when css-loader gets support for `style` ?

**Comment by blink1073** [comment]
I think we need to close this and open an issue tracking https://github.com/webpack-contrib/css-loader/issues/683

**Comment by blink1073** [comment]
Done: #6542
