### ISSUE TITLE
Source code coloring wrong with strings inside strings

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab#6397]
**Describe the bug**

When a string is inside a larger string, the source code coloring goes awry, even so it could decipher the correct coloring from the different between the different quotes (single vs double):

<img width="650" alt="Screenshot 2019-05-23 17 36 40" src="https://user-images.githubusercontent.com/69774/58293115-75ac7380-7d81-11e9-988d-92af08bc8faf.png">

In the last line, 

```python
parent = [f"{url}/{node.get('href')}" for node in soup.find_all("a")]
```
the part `for node in soup.find_all` should not be red anymore.

**To Reproduce**

Type above source code into a Jupiter lab cell.

**Expected behavior**

`for node in soup.find_all` should stay in white color.

**Desktop (please complete the following information):**

- OS: Host: macOS 10.14.3, Server: CentOS 6.5
- Browser: Safari 12.0.3
- JupyterLab 0.35.6

**Comment by jasongrout** [comment]
Thanks for bringing this up. This is fixed in master from a codemirror upgrade.

![Uploading Screen Shot 2019-05-24 at 11.33.29 AM.png…]()
