### ISSUE TITLE
initial instance Jupyterlab, apply options

### ISSUE THREAD

**Issue by ppeeou** [jupyterlab/jupyterlab#6400]
Hi, thank you for the awesome library.

I want to use custom `Jupyterlab options` 
It seems that the options are not applied to create the initial instance, so the degree of freedom decreases.

https://github.com/jupyterlab/jupyterlab/blob/master/packages/application/src/lab.ts#L27

now
```
export class JupyterLab extends JupyterFrontEnd<ILabShell> {
  /**
   * Construct a new JupyterLab object.
   */
  constructor(options: JupyterLab.IOptions = { shell: new LabShell() }) {
    super({ shell: options.shell || new LabShell() });  // only shell option received
```

I hope it changes as below... 
or I wish I could use the option in a different way.
```
export class JupyterLab extends JupyterFrontEnd<ILabShell> {
  /**
   * Construct a new JupyterLab object.
   */
  constructor(options: JupyterLab.IOptions = { shell: new LabShell() }) {
    super({...options, shell: options.shell || new LabShell() });  // add options super
```

What do you think??

**Comment by jasongrout** [comment]
What other options are you planning to pass in?

**Comment by ppeeou** [comment]
it's `serviceManager `  :)

**Comment by jasongrout** [comment]
Great idea. Do you want to submit a PR?

**Comment by jasongrout** [comment]
(Technically you should probably strip out the options that JupyterLab added, so you are just passing up the options that the superclass declares. But I think it's probably all right for now too - those options should be just ignored by the superclass for now.)

**Comment by ppeeou** [comment]
> Great idea. Do you want to submit a PR?

I'll try it. :)


> (Technically you should probably strip out the options that JupyterLab added, so you are just passing up the options that the superclass declares. But I think it's probably all right for now too - those options should be just ignored by the superclass for now.)

You are right
I have written the above to give you an idea, I will make the code more rigorous for the interface.

**Comment by ppeeou** [comment]
Can you tell me where the problem is?
I want to see that part.
