### ISSUE TITLE
Unable to install side-by-side vega versions

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#6403]
We intend for users to be able to install different versions of vega side-by-side. This *almost* works, except that there is a plugin ID collision:
https://github.com/jupyterlab/jupyterlab/blob/master/packages/vega5-extension/src/index.ts#L133

We should change the plugin ID for our vega package, as well as those in the `jupyter-renderers` repo to include the major vega version.

cf. #6402 , cc @jakevdp

**Comment by jasongrout** [comment]
Is this a good first issue?

**Comment by ian-r-rose** [comment]
I believe it is a good first issue. That is exactly the line that needs to be changed from `vega-extension:factory` to `vega5-extension:factory`.

**Comment by domoritz** [comment]
Would it make sense to also have a Vega 5 package in https://github.com/jupyterlab/jupyter-renderers? This way one could install the new package in an old version of jupyterlab. 

Since this is a "good first issue", does that mean I should leave it for someone else to work on?

**Comment by ian-r-rose** [comment]
@domoritz as it happens, users can already install the Vega 5 extension in older versions of JupyterLab. I demonstrate that in #6402.

The side-by-side story is still broken due to conflicting IDs (this issue), but replacement of different versions works fine as is.

**Comment by domoritz** [comment]
How do we actually install the Vega 5 extension in pre 1.0 Jupyterlab?

**Comment by ian-r-rose** [comment]
The comment I linked above gives the commands.

**Comment by domoritz** [comment]
Unfortunately, it seems to install 1.0.0-alpha.4 and not 1.0.0-alpha.8 for me, though.

**Comment by ian-r-rose** [comment]
Does it work if you specify the version? We may need to fix a tag or two with the churn of the last couple of days

**Comment by domoritz** [comment]
Ahh, I have to use `@` for the version. I tried `==` as in pip but that didn't work. 

```
jupyter labextension install @jupyterlab/vega5-extension@1.0.0-alpha.8
```

**Comment by domoritz** [comment]
Hmm, something is still wrong. The style of the action button doesn't look right:

<img width="540" alt="Screen Shot 2019-05-29 at 22 11 01" src="https://user-images.githubusercontent.com/589034/58610006-b6632b80-825e-11e9-9d6d-e3fd15d69742.png">
