### ISSUE TITLE
Improved UI/UX for moving cells up or down

### ISSUE THREAD

**Issue by willzfarmer** [jupyterlab/jupyterlab#641]
## Current summary

We plan on supporting moving cells through 3 approaches:
- [ ] Add move/up down commands (#189)
- [ ] Up/down buttons in the notebook toolbar
- [ ] Drag/drop
## Original comment

So I know there's a keyboard shortcut to move cells up or down, but I can never remember it and I always just use the buttons. I would love a toolbar that had the same buttons as the traditional notebook view.

**Comment by jasongrout** [comment]
I can never remember the shortcut either :). Thanks for pointing this out.

**Comment by blink1073** [comment]
I left it out to save horizontal space, since we were planning on having side-by-side notebooks.

**Comment by willzfarmer** [comment]
What if there was a way to open an extended toolbar? Like maybe dropdown buttons or a multi-level toolbar? Would something like that work?

**Comment by blink1073** [comment]
Those both sound feasible, but we would need to reach a UI/UX consensus.

**Comment by ellisonbg** [comment]
Most UIs that provide cut/copy/paste don't offer explicit move up/down as well. We thought we might be able to get by without those. However, the classic notebook has always offered up/down, so we probably want to make a concession and include them. The other option (probably better all around) would be to offer drag/drop reordering of cells. I remember that @blink1073 did some work on that - if that is easy to implement, let's start there and see if we can get by without the toolbar buttons.

**Comment by blink1073** [comment]
I implemented cell drag/drop, but we did not have a style to accompany it: https://github.com/jupyter-attic/jupyter-js-notebook/pull/189

**Comment by spoorthyv** [comment]
Hey @blink1073 is UX the only thing holding this feature back?

**Comment by blink1073** [comment]
Yep.

**Comment by Carreau** [comment]
Are the actions here ? I don't even find them in the command palette ?

**Comment by jasongrout** [comment]
I just looked too, and it looks like the actions are not implemented (probably in favor of cut/copy/paste, like @ellisonbg mentions). cf. https://github.com/jupyter/jupyterlab/blob/master/src/notebook/plugin.ts#L192 (where the commands are registered).

**Comment by spoorthyv** [comment]
Here are my ux suggestions:
* When your mouse hovers over the drag area change the cursor style to 'move'
* When a cell is being dragged the original cell's content should turn grey. Not an overlay, but all the content itself should turn grey (not sure how feasible this is. Not too important either)
* Change the light grey dashed lines a solid blue line with a circle at the beginning (look at pic)
* Instead of showing all the cells content while dragging, show a simple icon with an indicator of how many cells are being dragged. 

<img width="1077" alt="screen shot 2016-08-29 at 1 28 56 pm" src="https://cloud.githubusercontent.com/assets/12418068/18066521/a8d131ca-6ded-11e6-821c-f79a190a96a1.png">

**Comment by Carreau** [comment]
> I just looked too, and it looks like the actions are not implemented (probably in favor of cut/copy/paste, like @ellisonbg mentions). cf. https://github.com/jupyter/jupyterlab/blob/master/src/notebook/plugin.ts#L192 (where the commands are registered).

I would be in favor of exposing them, when we removed the Ctrl-j/k shortcuts we had a non negligible number of requests as of to why, and how to restore the shortcuts. 

I understand that having them in the UI could crowed it, – and I agree – but I believe for power users having already existing action to bind to would be useful. 

I also think that copy-pasting is harder with our cell concept, and while dragging is extremely useful it does not replace the ability to do it with the the keyboard. 

Side question ; does copy-pasting preserve the Codemirror History ?

**Comment by blink1073** [comment]
@Carreau, we store only the cell model when cut/pasting, so CodeMirror History is not currently handled.

**Comment by blink1073** [comment]
See #809 for an implementation of the actions and command palette entries.  The previous notebook did not have a keybinding associated with these actions.  We already use Shift+Up for extending selection.

**Comment by ellisonbg** [comment]
@blink1073 I do think we should move forward with the drag/drop of cells. @spoorthyv has added some design mockups for that. @spoorthyv want to tackle the code part of this?

**Comment by blink1073** [comment]
We might want to bring this class from nbdime into JupyterLab and use it here:  https://github.com/vidartf/nbdime/blob/276e57ba348ffb67691128002cd32235811ad50c/nbdime/webapp/src/dragorderpanel.ts

**Comment by ellisonbg** [comment]
Also @spoorthyv want to add move up/down buttons to the notebook toolbar?

**Comment by blink1073** [comment]
cc @vidartf re: https://github.com/jupyter/jupyterlab/issues/641#issuecomment-245065543

**Comment by vidartf** [comment]
@blink1073 I actually did some more work on the code yesterday, and think I can refactor it to a nice a reusable version today. Should I PR it (here or possibly phosphor)?

**Comment by blink1073** [comment]
Hi @vidartf, yes, please.  I think `src/common` is a good target for now.
