### ISSUE TITLE
Example tester not catching errors

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6413]
**Describe the bug**
The example tester isn't catching the console errors in the app example, which is missing a required extension.

**To Reproduce**

1. Go to 'examples/app'
2. Run `jlpm build`
3. Run `python main.py`
4.  Note the console errors

**Expected behavior**
Console errors are caught in CI, example app works.

**Comment by jasongrout** [comment]
What is an example of a console error that is not being caught?

Lots of times there is a console error logged from a phosphor signal test not being disconnected, and triggering one too many times after the test is over. I've been replacing those as I see them.

**Comment by blink1073** [comment]
The application was throwing errors at startup because the status bar token could be resolved (several of the extensions now depend on it).  I had to add that extension to the example app.

**Comment by jasongrout** [comment]
Oh wow. I think that should totally be optional, like the menus.

**Comment by blink1073** [comment]
That question is orthogonal to this fix :wink:
