### ISSUE TITLE
jupyter widgets not displayed in console

### ISSUE THREAD

**Issue by akhmerov** [jupyterlab/jupyterlab#6416]
With the current versions of `jupyterlab` (0.35.6), `@jupyter-widgets/jupyterlab-manager` v0.38.1, and `ipywidgets` (7.4.2), the widgets render correctly in the notebooks, but not in the console:

notebook:

![image](https://user-images.githubusercontent.com/2069677/58380681-43cf2300-7fb4-11e9-95d5-724b0d6f6cbe.png)

console:

![image](https://user-images.githubusercontent.com/2069677/58380687-5a757a00-7fb4-11e9-91e1-1c2541272ca7.png)

![image](https://user-images.githubusercontent.com/2069677/58380690-67926900-7fb4-11e9-8f92-871688173786.png)

**Comment by jtpio** [comment]
Related to:

- https://github.com/jupyterlab/jupyterlab/issues/6165
- https://github.com/jupyter-widgets/ipywidgets/issues/2370

Let's move the conversation over to https://github.com/jupyter-widgets/ipywidgets/issues/2370?

**Comment by akhmerov** [comment]
Got it, sorry for overlooking the other issue.

**Comment by jtpio** [comment]
All good!
