### ISSUE TITLE
How to update notebook metadata on jupyterlab using javascript?

### ISSUE THREAD

**Issue by pkvprakash** [jupyterlab/jupyterlab#6417]
How to update notebook metadata on jupyterlab using javascript?

I am trying to update the cell metadata of a notebook using javascript in jupyterlab referring [this](https://habr.com/en/post/439570/)

```
%%javascript 

var setTags = function(element, tags) {
    var cell_element = element.parents('.cell');
    var index = Jupyter.notebook.get_cell_elements().index(cell_element);
    var cell = Jupyter.notebook.get_cell(index);
    cell.metadata.tags = tags;
    console.log(cell.metadata)
    console.log(cell)
};
```

I first got the following error. 
```
Javascript Error: element.parents is not a function
```

Then on the javascript console I tried executing `Jupyter` to see what all that object can provide. 
But I am getting undefined reference error for `Jupyter` object. I later realised that `Jupyter` object is not available on jupyterlab. But, at the same time it is available on jupyter notebook. 

How can I access the cell metadata of a notebook in jupyterlab using javascript?

**Comment by pkvprakash** [comment]
Only way I found is using lab extensions. Closing the issue.

**Comment by hujun123qwe** [comment]
> Only way I found is using lab extensions. Closing the issue.

Hi, i am encounting the similar problem.
please tell me which lab extension?
Or any other links ?
