### ISSUE TITLE
Labextension with file: dependency doesn't work

### ISSUE THREAD

**Issue by travigd** [jupyterlab/jupyterlab#6419]
This is for [WebIO.jl](https://github.com/JuliaGizmos/WebIO.jl).

We currently have a monorepo with this directory structure.
```
./packages/
├── blink-provider
├── generic-http-provider
├── jupyter-lab-provider
├── jupyter-notebook-provider
├── mux-provider
├── webio
├── package.json
├── lerna.json
```

Essentially the `webio` directory contains the core implementation while `jupyter-lab-provider` provides the JupyterLab glue. But because of the way lerna works, `jupyter-lab-provider` has a dependency on `file:../webio` which breaks the labextension install process.

Is there any way around this? We can publish things to NPM but it'd be nice to be able to also install the package locally (via `jupyter labextension install /path/to/jupyter-lab-provider`).

**Comment by jasongrout** [comment]
You can `jupyter labextension link` those dependencies, like we do in a dev install of ipywidgets:

https://github.com/jupyter-widgets/ipywidgets/blob/34060411e6cd6398d697acb27611343d1133e8a0/dev-install.sh#L55-L58

**Comment by jasongrout** [comment]
just checking - your package.json doesn't actually include a `file:../webio` entry, right? Lerna works by symlinking things together so they refer to each other while the package.json just gives the package name and version number (but not the disk location).
