### ISSUE TITLE
Missing dependencies in docs/environment.yml in order to successfully run doc tests

### ISSUE THREAD

**Issue by duarteocarmo** [jupyterlab/jupyterlab#6427]
**Describe the bug**
In order for a contributor to contribute to documentation he/she must follow the instructions [here](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#writing-documenation). However, in order to run the tests stated, one must also have the following packages installed:
- [pytest](https://docs.pytest.org/en/latest/)
- [pytest-check-links](https://pypi.org/project/pytest-check-links/)

Only then can the user run: 
`py.test --check-links -k .md . || py.test --check-links -k .md --lf .`
(and we should also state that this command must be run in /docs/ and not in root directory)

**To Reproduce**
1. Start with a clean anaconda environment
2. Follow the instructions by doing:
`conda env create -f docs/environment.yml`
3. Try to run the command:
`py.test --check-links -k .md . || py.test --check-links -k .md --lf .`
4. Since you don't have pytest or pytest-check-links, the command will not be recognized.

**Expected behavior**
It is expected that the stated instructions work, and that the contributor can follow them and run the tests.

**Screenshots**
<img width="701" alt="Screen Shot 2019-05-28 at 21 19 09" src="https://user-images.githubusercontent.com/26342344/58507072-2acf9900-8191-11e9-84a6-8c13031adff2.png">
Here, `check-links` not recognized because it's not in `docs/environment.yml`(see [here](https://github.com/jupyterlab/jupyterlab/blob/master/docs/environment.yml))

**Desktop (please complete the following information):**

- OS: MAC OS
- Browser not applicable
- JupyterLab latest

**Comment by kavishdahekar** [comment]
Faced this today.
Either the Contributing doc should mention this or the right dependencies should be added.

**Comment by jasongrout** [comment]
Would you be able to make a PR adding the right dependencies? You can even edit the file directly in the web interface: https://github.com/jupyterlab/jupyterlab/blob/master/docs/environment.yml

**Comment by kavishdahekar** [comment]
@jasongrout we need to add two dependencies `pytest` and `pytest-check-links`.
`pytest-check-links` is not available in conda so needs to be added via pip.
conda has stopped shipping pip in the recent versions, so we will additionally have to add pip as a dependency as well.
Finally it might look something like this:
```
name: jupyterlab_documentation
channels:
  - conda-forge
dependencies:
- python=3.5
- sphinx>=1.8
- sphinx-copybutton
- sphinx_rtd_theme
- recommonmark
- pytest
- pip
- pip:
  - pytest-check-links
```
Is this acceptable?

**Comment by jasongrout** [comment]
Sounds reasonable to me. Does it work now with that environment file?

**Comment by jasongrout** [comment]
conda-forge now only builds for python 3.6 and 3.7. If you change the python version to 3.6 or 3.7, we'll be able to use newer dependencies on conda-forge.

**Comment by duarteocarmo** [comment]
@kavishdahekar should I do it or you want to take care o

**Comment by duarteocarmo** [comment]
I’ll take care of this!
