### ISSUE TITLE
Better JupyterHub Integration

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6428]
I propose that we have better integration with JupyterHub.  In the short run, we add a flag to `labhubapp` that the front end uses to determine which connection loss dialog to show (cf #6399), and whether to add the commands/menu items that are currently provided by https://github.com/jupyterhub/jupyterlab-hub.

The next logical step would be to augment `jupyterhub-singleuser` to provide `page_config_data` and deprecate the use of `labhubapp`.

**Comment by blink1073** [comment]
cc @vidartf @ian-r-rose @yuvipanda

**Comment by blink1073** [comment]
cc @minrk

**Comment by yuvipanda** [comment]
Love it!

**Comment by blink1073** [comment]
:fist_oncoming:

**Comment by blink1073** [comment]
cc @athornton

**Comment by jasongrout** [comment]
CC @vidartf

**Comment by athornton** [comment]
Very nice.  Thumbs up.  This in fact addresses a behavior related to reporting of kernel failure I was going to open an issue for once I had sufficient reproducibility.  Plus it'd be nice to be able to get rid of labhub.  (Also please feel free to cannibalize https://github.com/lsst-sqre/jupyterlab-savequit , which at our site, pretty much everyone uses rather than the Hub menu)

**Comment by blink1073** [comment]
Quick note to self: no changes are needed to jhub, we can just add the page config ourselves if the app has a hub_prefix property.

**Comment by vidartf** [comment]
I have ~0 experience with hub, so I have no idea what this issue is implying. What would the changes to jupyterlab itself be?

**Comment by blink1073** [comment]
We would update our [extension[(https://github.com/jupyterlab/jupyterlab/blob/e0c214cde9e5145aa96b001eaa454d51de4427b7/jupyterlab/extension.py#L75) to inject more `page_config` conditionally, and then add logic `application-extension` that runs in the presence of that page config.

**Comment by blink1073** [comment]
@athornton, thanks for the pointer!  I'm wary of adding too much logic up front that might not be wanted in all contexts.  I'd prefer to start small.
