### ISSUE TITLE
Release process for alphas

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6435]
The new process from #6312 is really great! I released an alpha before breakfast!

There were two things that could be adjusted:

1. The python `v1.0.0a4` tag was put on the js release commit, not the python publish commit. I think it should be on the python publish commit. I moved the tag manually for 1.0.0a4.
2. There were a few changes, like updates to yarn.lock, some package.json dependency updates, etc., that needed to be merged after the publish command was run. I amended the publish commit with those changes, and also added the hashes of the release tarballs to the commit message. See https://github.com/jupyterlab/jupyterlab/commit/05067699a16ed532977475612cecef835f5e0da3. It may be that these changes should somehow be made before the build/release/tag process.
3. I think we should separate the python build and pip upload steps to give the release manager a chance to locally install the built artifact to have a minimal sanity check before actually uploading.

**Comment by jasongrout** [comment]
CC @blink1073

**Comment by jasongrout** [comment]
In building 1.0a5, I noticed this error after lerna published all the js packages:

```
> node buildutils/lib/update-core-mode.js
> jlpm
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning @jupyterlab/application > @jupyterlab/apputils > @jupyterlab/ui-components > @blueprintjs/core > react-popper > create-react-context > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning webpack-visualizer-plugin > react > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
> jlpm yarn-deduplicate -s fewer --fail
$ /Users/jgrout6/projects/app/release/jupyterlab/jupyterlab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
```

**Comment by jasongrout** [comment]
After the above error, it appears the script did `jlpm`, then `jlpm run build:prod`, then `jlpm integrity`. That updated `@jupyterlab/nbconvert-css`. I'm not sure why that package isn't updated before the publish step. It makes me a little worried that we are publishing nbconvert-css with old dependencies, and then updating the dependencies in the python build step.

**Comment by blink1073** [comment]
Note to self: Add verification that the things in the files field are there, and if style and schema folders exist that they are included

**Comment by jasongrout** [comment]
> if style and schema folders exist that they are included

I think we may already have this check in integrity. What we don't check, I think, is post-build pre-upload that things are there.

**Comment by ian-r-rose** [comment]
Yes, we added schema an style checks in #5947.
