### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve '@jupyterlab/mainmenu'

### ISSUE THREAD

**Issue by Zlass** [jupyterlab/jupyterlab#6436]
Not sure if I'm being stupid, but I updated my local configuration of Jupyter lab to the newest 1.0 alpha version and now it's no longer able to build. I've tried creating a new empty lab environment without my extensions to ensure it wasn't my code, but nothing changed.

Seems like the build process is getting hung up in the `documentsearch-extension` due to a messed up alias to the `mainmenu` package. [Here's a gist with the full log](https://gist.github.com/Zlass/7192f7781ba047110c6d1211df3a4588).

I checked the `tsconfigs` and `tdoptions` for the respective packages/extensions, but they look to be correct to me.

I used `pipenv install -e git+git://github.com/jupyterlab/jupyterlab.git#egg=jupyterlab`
to install jupyter lab. I had to add the editable flag because the installation process would break otherwise.

Any help would be much appreciated. Cheers!

**Comment by blink1073** [comment]
Hi @Zlass, today's release was made with a new release process, and it had some bugs.  We're working on a fix and a new release.

**Comment by Zlass** [comment]
Cool, I'll keep an eye out for the fixes. In the meantime, I'll switch back to the old version. Thanks for the Help!
