### ISSUE TITLE
Text selection mis-aligned after first line

### ISSUE THREAD

**Issue by marius311** [jupyterlab/jupyterlab#6439]
When you select all text in an input cell (e.g. Ctrl+A, or also click-drag with cursor), the selection for the first line is aligned differently than for the subsequent lines:

![image](https://user-images.githubusercontent.com/1510968/58596009-58672180-8227-11e9-965c-ae4ed5d09310.png)

I think it'd look better if all of them were aligned like the first line, i.e. with a bit of space between this and the cell border. I see this with Jupyterlab 1.0.0a3 and 1.0.0a5, on Linux both Chrome 74.0.3729.169 and Firefox 67.0.

**Comment by jasongrout** [comment]
I also notice that this doesn't happen in stock codemirror at https://codemirror.net/

**Comment by jasongrout** [comment]
Changing to 1.0 since a PR was submitted. If it doesn't make it in, we can bump back to 1.1.

**Comment by vidartf** [comment]
Note: To me, the current visual clearly represents the fact that "the previous line ending is not included in the selection". At the same time, it might fool you into thinking "you are missing a leading space in your selection". Whatever the fix, I'd like the first question to still be clearly answered.

**Comment by telamonian** [comment]
@vidartf That's an interesting point, and I hadn't really thought of it that way. However, there's already a clear visual signal for "previous line ending selected". With my fix from #6556, here's what a selection looks like without the previous line ending:

![image](https://user-images.githubusercontent.com/2263641/59420642-3c24c200-8d9b-11e9-91d2-c0eb3623497d.png)

and here's what it looks like with the previous line ending:

![image](https://user-images.githubusercontent.com/2263641/59420673-4cd53800-8d9b-11e9-9aa0-54407e64a0d3.png)

**Comment by vidartf** [comment]
@telamonian That works! Just be aware that it does require the line ending to be visible, which it might not be if the line is very long. From the PR it does seem like the change ensures that the code is in line with expectation from CSS, so at least some of it should go in though.
