### ISSUE TITLE
No horizontal scrolling in rendered markdown cells.

### ISSUE THREAD

**Issue by capslockwizard** [jupyterlab/jupyterlab#6441]
**Describe the bug**
The output of markdown cells does not support horizontal scrolling for a long and continuous string of non-white space characters. Characters that are rendered beyond the width of the cell are inaccessible.

**To Reproduce**
1. Paste and render the following string into a markdown cell:
`fgfgggfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdgggWootfgfdggg`

**Expected behavior**
A vertical scrollbar should appear to allow the user to see the full string

**Screenshots**
Markdown cell in editor mode:
![image](https://user-images.githubusercontent.com/2268615/58621340-b36a4880-82fb-11e9-8c33-1a6f829f97d7.png)
Markdown cell in render mode:
![image](https://user-images.githubusercontent.com/2268615/58621360-c0873780-82fb-11e9-8a9f-8a107b67a161.png)

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser Chrome v74.0.3729.169 (Official Build) (64-bit)
- JupyterLab v0.35.4

**Comment by jasongrout** [comment]
I confirmed that the rendered markdown output does not include a scroll bar and does not wrap either, so you can't see the end of the text.

**Comment by jasongrout** [comment]
This may be as easy as changing https://github.com/jupyterlab/jupyterlab/blob/master/packages/cells/style/widget.css#L108-L110 to `overflow: auto`.

Setting as a good first issue. Do you want to submit a PR?

**Comment by capslockwizard** [comment]
Sure

**Comment by jasongrout** [comment]
Fixed by #6444.
