### ISSUE TITLE
Feature Request: Turn cell border color green when in command mode

### ISSUE THREAD

**Issue by tmthyjames** [jupyterlab/jupyterlab#6446]
In Jupyter Notebook, the cell border being green indicates command mode; the cell border being blue indicates esc mode. In Jupyter Lab (Version 0.35.6), the cell stays blue regardless of mode.

I wasn't sure if this was an explicit design choice for Lab, but having that visual cue in Notebook was super helpful and I didn't notice how helpful until I moved to Lab and didn't have the visual cue to indicate which mode I'm in. Small change but super intuitive when you use a lot of keyboard shortcuts. 

Not sure if this is the place for feature requests. Happy to post to a more appropriate forum. Love Jupyter! Keep up the great work. 👍

**Comment by jasongrout** [comment]
Thanks for the feedback! Can you add this comment to https://github.com/jupyterlab/jupyterlab/issues/4246, where there already is a discussion for this?
