### ISSUE TITLE
Status bar hover keydown/keypress event confusion

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6452]
Notice that https://github.com/jupyterlab/jupyterlab/blob/1612332834f890d8e0e76b3cf22c7d75a09b7695/packages/statusbar/src/components/hover.tsx#L75 and https://github.com/jupyterlab/jupyterlab/blob/1612332834f890d8e0e76b3cf22c7d75a09b7695/packages/statusbar/src/components/hover.tsx#L84 we add/remove the keypress event, but the handler at https://github.com/jupyterlab/jupyterlab/blob/1612332834f890d8e0e76b3cf22c7d75a09b7695/packages/statusbar/src/components/hover.tsx#L104-L121 only handles keydown events. Surely this confusion is an error?

**Comment by ian-r-rose** [comment]
I think you are right @jasongrout. I also notice that it is adding a `window` resize handler. I wonder if that is necessary (possibly it was added because it is attached to `document.body`).

**Comment by jasongrout** [comment]
I think you're right that it's only using the window resize handler because it's doing a popup on top of everything.

**Comment by ian-r-rose** [comment]
At the very least, I think that standardizing on `keydown` (probably?) is a good first issue.
