### ISSUE TITLE
Server Connection Error, contentsModel is undefined

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [jupyterlab/jupyterlab#6456]
**Describe the bug**
I get an error message that I can find reported in any of the repos/stackoverflow etc. Upon opening in the browser I get a popup message: Server Connection Error, contentsModel is undefined. I don't notice any other unexpected behaviors, so perhaps this is an annoyance. This is running on a Docker container  (available at `docker pull genomicseducationalliance/cyverse-jupyterlab-rnaseq-qc:dev_2.0`). There are specific reasons why I could not use the existing Jupyterlab Docker containers. 

**To Reproduce**
1. This happens as soon as Jupyter lab is open in my browser window

**Desktop (please complete the following information):**
This is being run in a docker container the relevant Dockerfile is here: https://github.com/genomics-education-alliance/CyVerse-Jupyterlab-RNA-QC/tree/master/dev

- Browser [67.0 (64-bit)]
- JupyterLab [e.g. 0.35.6]

**Additional context**

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/usr/local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/usr/local/bin
	/usr/lib/python36.zip
	/usr/lib/python3.6
	/usr/lib/python3.6/lib-dynload
	/usr/local/lib/python3.6/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.6.7 (default, Oct 22 2018, 11:32:17) 
	[GCC 8.2.0]

platform.platform():
	Linux-4.9.125-linuxkit-x86_64-with-Ubuntu-18.04-bionic

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter
	/bin/jupyter

pip list:
	asn1crypto (0.24.0)
	attrs (19.1.0)
	backcall (0.1.0)
	bash-kernel (0.7.1)
	biopython (1.73)
	bleach (3.1.0)
	certifi (2018.1.18)
	chardet (3.0.4)
	command-not-found (0.3)
	cryptography (2.1.4)
	cycler (0.10.0)
	decorator (4.4.0)
	defusedxml (0.6.0)
	descartes (1.1.0)
	distro-info (0.18ubuntu0.18.04.1)
	entrypoints (0.3)
	idna (2.6)
	ipykernel (5.1.1)
	ipython (7.5.0)
	ipython-genutils (0.2.0)
	ipywidgets (7.4.2)
	jedi (0.13.3)
	Jinja2 (2.10.1)
	joblib (0.13.2)
	jsonschema (3.0.1)
	jupyter-client (5.2.4)
	jupyter-core (4.4.0)
	jupyterlab (0.35.6)
	jupyterlab-irods (2.0.1)
	jupyterlab-server (0.2.0)
	keyring (10.6.0)
	keyrings.alt (3.0)
	kiwisolver (1.1.0)
	language-selector (0.1)
	MarkupSafe (1.1.1)
	matplotlib (3.1.0)
	mistune (0.8.4)
	mizani (0.5.4)
	nbconvert (5.5.0)
	nbformat (4.4.0)
	netifaces (0.10.4)
	notebook (5.7.8)
	numpy (1.16.4)
	palettable (3.1.1)
	pandas (0.24.2)
	pandocfilters (1.4.2)
	parso (0.4.0)
	patsy (0.5.1)
	pexpect (4.7.0)
	pickleshare (0.7.5)
	pip (9.0.1)
	plotnine (0.5.1)
	prettytable (0.7.2)
	prometheus-client (0.6.0)
	prompt-toolkit (2.0.9)
	ptyprocess (0.6.0)
	pycrypto (2.6.1)
	Pygments (2.4.2)
	pygobject (3.26.1)
	pyparsing (2.4.0)
	pyrsistent (0.15.2)
	python-apt (1.6.4)
	python-dateutil (2.8.0)
	python-irodsclient (0.8.1)
	pytz (2019.1)
	pyxdg (0.25)
	PyYAML (3.12)
	pyzmq (18.0.1)
	requests (2.18.4)
	scikit-learn (0.21.2)
	scikit-misc (0.1.1)
	scipy (1.3.0)
	SecretStorage (2.3.1)
	Send2Trash (1.5.0)
	setuptools (39.0.1)
	six (1.11.0)
	ssh-import-id (5.7)
	statsmodels (0.9.0)
	terminado (0.8.2)
	testpath (0.4.2)
	tornado (6.0.2)
	traitlets (4.3.2)
	ufw (0.36)
	unattended-upgrades (0.1)
	urllib3 (1.22)
	wcwidth (0.1.7)
	webencodings (0.5.1)
	wheel (0.30.0)
	widgetsnbextension (3.4.2)
	xmlrunner (1.7.7)
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
jupyter-lab --ip=0.0.0.0 --no-browser --debug
[D 01:53:56.433 LabApp] Searching ['/home/gea_user', '/home/gea_user/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 01:53:56.434 LabApp] Looking for jupyter_config in /etc/jupyter
[D 01:53:56.435 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 01:53:56.436 LabApp] Looking for jupyter_config in /usr/etc/jupyter
[D 01:53:56.437 LabApp] Looking for jupyter_config in /home/gea_user/.jupyter
[D 01:53:56.438 LabApp] Looking for jupyter_config in /home/gea_user
[D 01:53:56.441 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 01:53:56.442 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 01:53:56.442 LabApp] Looking for jupyter_notebook_config in /usr/etc/jupyter
[D 01:53:56.443 LabApp] Looking for jupyter_notebook_config in /home/gea_user/.jupyter
[D 01:53:56.444 LabApp] Loaded config file: /home/gea_user/.jupyter/jupyter_notebook_config.py
[D 01:53:56.444 LabApp] Looking for jupyter_notebook_config in /home/gea_user
[W 01:53:57.302 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[D 01:53:57.315 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 01:53:57.318 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 01:53:57.321 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/etc/jupyter/jupyter_notebook_config.json
[D 01:53:57.323 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/gea_user/.jupyter/jupyter_notebook_config.json
[I 01:53:57.341 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 01:53:57.341 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 01:53:57.345 LabApp] Serving notebooks from local directory: /home/gea_user
[I 01:53:57.346 LabApp] The Jupyter Notebook is running at:
[I 01:53:57.346 LabApp] http://(a5d5467b7ec9 or 127.0.0.1):8888/
[I 01:53:57.346 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser console here.
</pre>
</details>

**Comment by jasongrout** [comment]
Can you file this issue with that docker container repo, since it seems specific to that container? That is a very odd error. I don't think I've ever seen something like that.
