### ISSUE TITLE
Include python package sha256 in publish commit message

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6460]
As a convention, I've been including the pypi tarball hashes into the release commit message so we have a verified record anyone can look up for exactly what was uploaded. For example, see the commit message at: https://github.com/jupyterlab/jupyterlab/commit/759515905847dece465854b166e0253ba67e09f4

I probably go overboard by including several different hashes (I do this for convenience for the user, as well as the perhaps naive assumption that checking against several hashes is more secure than just one hash). Perhaps we could include at least the sha256 hashes of the pypi tarballs in the suggested commit message at https://github.com/jupyterlab/jupyterlab/blob/2a3644a5290b592296516b5a304883ffd373a4c5/buildutils/src/publish.ts#L47

**Comment by jasongrout** [comment]
This isn't really a blocker for 1.0, so setting to 1.1.

**Comment by blink1073** [comment]
Here is the workflow I'd like to see based on the release yesterday:

- The maintainer runs `jlpm bumpversion <spec>`
  -- The script commits the python-related changes as a "prepublish" commit.  We don't yet have the changes to `jupyterlab/staging/package.json` to commit.
- The maintainer runs `jlpm publish:all`
  -- The script makes the commit with all of the checksums in the commit message.  At this point we have the updated `jupyterlab/staging` assets to commit.
  -- The script prints the prompt to verify things and then the commands to run for tag and upload
-- The maintainer runs the tag and upload commands when ready

I think creating the commits is lower risk than creating the tags and puts less burden on the release manager.

**Comment by blink1073** [comment]
Note: `skip-build` should still clean the `dist/` directory.

**Comment by blink1073** [comment]
I think we should add a --dry-run flag for publish.ts that prints the lerna publish command instead of running it. We could then run it on CI too, but it has to be done before we make any changes to the version numbers.

**Comment by blink1073** [comment]
Notes from today:
- we should remove the extra arg to `patch:release` and the associated `--force-publish` since the default `lerna version` logic is working fine
- we will use Docker files and some shell scripts to do the versioning and publishing - including testing the wheel and building the wheel before publishing

**Comment by jasongrout** [comment]
Note that the original issue is now solved. @blink1073 has a lot of other ideas above, and I'm not sure if they are solved, so I'm not sure if everything here is solved.

**Comment by blink1073** [comment]
Migrated the remaining to #7474
