### ISSUE TITLE
Audit extension dev docs for 1.0

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#6463]
With 1.0 coming out soon, we will likely/hopfully see an uptick in the creation of third party extensions. I was visiting a research lab building that is building extensions recently and they said our extension developer docs were out of date, incomplete, and incorrect at points. At a minimum for 1.0 we should:

- [x] Make sure they are up to date and reflect the current APIs, codebase, build process, etc.
- [x] Identify if there is any missing content that is really a show stopper for extension developers.

**Comment by SgtPooki** [comment]
@ellisonbg  Was anything specifically called out as incomplete/incorrect? I just went through the xkcd extension tutorial and was able to make it through the tutorial without too many issues.

**Comment by jasongrout** [comment]
Did you work through the tutorial with the jlab master branch? I think this issue is about making sure the documentation (more than just the xkcd tutorial) is up to date with current master.

**Comment by tslaton** [comment]
A few more things to consider for the documentation:
- [ ] It would be super helpful from an extension developer's perspective if there were a single page where all Tokens available for extension hooks were listed and described. As it stands, it can be tough to figure out how to get a handle on the part of JupyterLab one wants to modify, even though the handle probably exists. @jasongrout mentioned to me that this could probably be largely accomplished by an informed `grep` against the source code (eg., for "new Token"). Something like this exists [here](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html#core-tokens), but I don't think it's complete or fully fleshed-out.
- [ ] Many extensions rely on a back-end piece as well as a front-end piece. However, the documentation for JupyterLab only addresses the front-end with eg., the [xkcd extension](https://jupyterlab.readthedocs.io/en/stable/developer/xkcd_extension_tutorial.html#xkcd-extension-tutorial). I understand that this is the part that's really JupyterLab, but some mention of server extensions insofar as they can be written too (and a link on how to get started writing them) would be very helpful. As a newcomer not knowing that I could even write a server extension for the Jupyter ecosystem, I felt pretty lost for a bit trying to figure out how to get some back-end functionality with the client code.

**Comment by jasongrout** [comment]
Closing as resolved. Thanks!
