### ISSUE TITLE
`jlpm docs` fails, strange typedoc bug

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#6471]
I'm running into a strange error in one of my [CI tests (Linux Docs)](https://dev.azure.com/jupyterlab/jupyterlab/_build/results?buildId=2005&view=logs):

```
Using TypeScript 3.2.4 from /home/vsts/work/1/s/node_modules/typedoc/node_modules/typescript/lib
Error: /home/vsts/work/1/s/packages/ui-components/src/icon/icon.tsx(162)
 Type 'HTMLCollectionOf<HTMLElement>' must have a '[Symbol.iterator]()' method that returns an iterator.
```

Here's the offending code (which builds normally on my machine and passes the other tests):

```typescript
    for (let container of document.getElementsByClassName(
      className
    ) as HTMLCollectionOf<HTMLElement>) {
      this.icon({
        name: usedname,
        title: title,
        container: container,
        ...propsStyle
      });
    }
```

It seems there's some config issue with the Linux Docs test. [This thread](https://github.com/Microsoft/TypeScript/issues/10574) suggests that the root cause of the observed error was resolved by later versions of TypeScript. For whatever reason, Linux Docs uses ts 3.2.4 while all the jlab packages are on 3.5.1. It may be this version mismatch that's causing the issue.

Not a priority, but I figure this bug report might help track down the issue.

**Comment by telamonian** [comment]
I dug into this a bit, and it turns out that the declaration of `HTMLCollectionOf` is in `lib.dom.iterable.d.ts`, which needs to be added to the `lib` section of `ui-components/tdoptions.json`. However, once that was fixed, I started running into a different bug when I ran `jlpm docs`:

```
lerna ERR! yarn run docs exited 4 in '@jupyterlab/apputils'
lerna ERR! yarn run docs stdout:
$ typedoc --options tdoptions.json --theme ../../typedoc-theme src

Using TypeScript 3.2.4 from /Users/tel/usr/venv/jup-test/git/jup-test/node_modules/typedoc/node_modules/typescript/lib
Error: /Users/tel/usr/venv/jup-test/git/jup-test/node_modules/@jupyterlab/ui-components/lib/icon/icon.d.ts(59)
 ',' expected.
Error: /Users/tel/usr/venv/jup-test/git/jup-test/node_modules/@jupyterlab/ui-components/lib/icon/icon.d.ts(59)
 ',' expected.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This seems to be related to TypeStrong/typedoc#820, but it can't be the exact same thing since we're already using typedoc `1.4.2`. It's possible that the fix for this will be for them to release the latest version (`1.5.0`) on npm.

I'll add a note to the contrib docs about the `lib` field of `tdoptions.json`,  post a note about this on the typedoc repo, and then I'll close this issue.

**Comment by jtpio** [comment]
Thanks @telamonian for reporting here.

Looks like the "Linux (docs)" tests have been running fine for the past couple of months.

So let's close this one, but don't hesitate to reopen open a new one if you still notice this issue, thanks!
