### ISSUE TITLE
ENH: Always show filename of current notebook

### ISSUE THREAD

**Issue by timhoffm** [jupyterlab/jupyterlab#6475]
When having a number of files open, it is not easily possible to see which file you are in:
![image](https://user-images.githubusercontent.com/2836374/58969049-5832cd00-87b7-11e9-98bd-269c3b9015ea.png)

jupyter notebook had the filename in a prominent place at the top:
![image](https://user-images.githubusercontent.com/2836374/58969236-a8aa2a80-87b7-11e9-92d6-41679ebbadc1.png)

It would be good to have someting similar in jupyterlab. If you don't want to sacrifice extra vertical space for this, maybe one could display the filename in the toolbar:
![image](https://user-images.githubusercontent.com/2836374/58969387-e8711200-87b7-11e9-82b1-47c933d4b957.png)

**Comment by ian-r-rose** [comment]
Hi @timhoffm, in more recent versions of JupyterLab you should be able to see the current file name in the lower right corner of the status bar. Does that do the trick?

**Comment by timhoffm** [comment]
@ian-r-rose thanks for the reply. I'm on v0.35.5 (lastest in anaconda). I don't have a status bar and cannot figure out how to make it visible. Has it just been introduced recently?

**Comment by jtpio** [comment]
> Has it just been introduced recently?

@timhoffm yes it's in the alpha release (`1.0.0ax`). You can run the following to get it:

```
pip install --pre -U jupyterlab
```

**Comment by timhoffm** [comment]
Thanks, that's good enough for me!
