### ISSUE TITLE
Use non-breaking space for "SHUT DOWN" in running window

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6477]
Right now, the SHUT DOWN words wrap if the window gets too narrow. One way to deal with this is to use a nonbreaking space there. I think the change might be as easy as changing:
https://github.com/jupyterlab/jupyterlab/blob/cf984351d71fe99506bcc15f9f048763f38d2012/packages/running/src/index.tsx#L176

to say `SHUT&nbsp;DOWN`

**Comment by ibdafna** [comment]
Taking this one.

**Comment by jasongrout** [comment]
Fixed by #6489.
