### ISSUE TITLE
Cannot create new workspaces

### ISSUE THREAD

**Issue by dchandan** [jupyterlab/jupyterlab#6478]
I am attempting to create a new workspace. I navigate to a new browser tab and go to my notebook address where I am presented with the following dialogue box

![sc1](https://user-images.githubusercontent.com/5779123/58975222-733f1600-8792-11e9-84a2-4e876af19d02.png)

I enter a new name:
![sc2](https://user-images.githubusercontent.com/5779123/58975257-881ba980-8792-11e9-8eb9-e687898cec81.png)

but it doesn't create the new workspace and I am returned to the original dialogue box. Similarly, I fail to create a new work space using a command such as:

`localhost:8888/lab/workspaces/research?clone`

What am I doing wrong?

**Comment by kapilkd13** [comment]
I tried it and can't seem to reproduce it. Only time it happened is when I already have another tab with `myspace` workspace, in that case we are again presented with the dialog box. Is there a way to reproduce it. Also your setup info would help.

**Comment by roiholtzman** [comment]
I have the same issue.

**Comment by jasongrout** [comment]
This dialog is gone in jlab 1.0. Please upgrade to have it automatically generate a new workspace.
