### ISSUE TITLE
Close Other Tabs -> Close All Other Tabs

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6482]
This is a minimal change from https://github.com/jupyterlab/jupyterlab/issues/6008#issuecomment-470257771 so we can move forward and not block 1.0.

Basically, this is changing https://github.com/jupyterlab/jupyterlab/blob/eedff5483ea2992722d3c1efd931ea992663846a/packages/application-extension/src/index.tsx#L567 to say "Close All Other Tabs".

**Comment by ibdafna** [comment]
Will do this one now.

**Comment by blink1073** [comment]
Fixed by #6485.
