### ISSUE TITLE
Enhancing the releases section of the repo

### ISSUE THREAD

**Issue by raiyanalam** [jupyterlab/jupyterlab#6483]
The releases section in this repo currently is a flat list of tags and does not provide any information on the changes incorporated in the release. It would be great if with each release a list of changes are displayed or even a simple link to changelog would also help. Also, GitHub will notify watchers every time a new release is available.
![image](https://user-images.githubusercontent.com/7879476/59024004-92ab7100-886e-11e9-84c8-4345201e0abd.png)

Solution wise, since the repo already uses Azure pipelines for CI, we can potentially leverage its [built-in task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubReleaseV0) to publish release notes to GitHub. The task can be configured to create a release only when the pipeline is triggered for a matching tag. It can compute an exhaustive list of changes done in this release, list them and cross reference it with the issues. Additionally, we can also provide a list links to external sources which we think will be useful for users to get started with the release.
Here is a [sample repo](https://github.com/Microsoft/vscode-react-native/releases) that leverages this capability. Being a built in task, this can be achieved with minor changes to the CI file.

**Comment by jasongrout** [comment]
If we can make that list more useful, it would be great. We've been trying to maintain a human-readable changelog in the docs: https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html

**Comment by raiyanalam** [comment]
Having the website with changelog definitely has has its own advantages. However, simultaneously we should also leverage the in built capability provided by github for releases even if it is just posting a link to the relevant documentation. Several users scan this section to see how active the repo is and the changes that were incorporated in a release. Optionally, the task can also display an exhaustive list of changes and links to issues/commits that were included in the release. 

I would be happy to contribute to the repo by raising a PR for this. Let me know if you feel this is something that is advantageous for the users.

**Comment by jasongrout** [comment]
I think minimally adding a link to the changelog in GitHub release notifications makes sense. I really want to keep ownership of the changelog inside the repo, rather than metadata on the repo only stored at GitHub (i.e., I'd rather have the changelog in the docs than only available via the GitHub release page). Note that the changelog links to a list of issues/PRs in the milestone.

Is that a manual process to update the "GitHub release"? If it is, perhaps it is adding instructions in the release notes about adding the link manually when a release is done. Or perhaps we just add a changelog link prominently in the readme? What do you propose, given that we have a curated changelog in the documentation that is sort of the authoritative changelog?

**Comment by raiyanalam** [comment]
We can probably add a link to changelog in readme. However, we still miss the users those who scan the releases section for updates and also there wont be any notification from github when new releases are published. 

The ideal way would be to publish some vital links(including link to curated change log) in release section and then let users navigate from there. We can do this manually each time, but then having this automated means one less thing to do during a release! 😃

**Comment by jasongrout** [comment]
> having this automated means one less thing to do during a release!

definitely +1 from me. Feel free to submit a PR to add this link to our changelog in our documentation in our release process.

**Comment by jtpio** [comment]
Closing since releases are now automated.

Changelog entries are automatically generated and added to the GitHub Release description. For example:

![image](https://user-images.githubusercontent.com/591645/146037702-4021c246-8706-49e7-8da1-fc96377d5d23.png)

Thanks!
