### ISSUE TITLE
Change the name of the "inspector" to "interactive help".

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#6488]
Since many users assume "inspector" means "variable inspector" (which we don't yet offer, but may in the near future), we should rename the inspector to something that more clearly indicates what it actually does. I would propose "interactive help", which is similar to "help" in Spyder.

The immediate action here would probably be to simply change the user-facing title (*i.e.*, the command label and the tab title). We can change the underlying classes and components in the future.

**Comment by ibdafna** [comment]
Will take this one.

**Comment by jasongrout** [comment]
Definitely +1 from me.

**Comment by cquah** [comment]
+1 too!
