### ISSUE TITLE
1.0.0.0a6 not working in safari

### ISSUE THREAD

**Issue by CavalloneChen** [jupyterlab/jupyterlab#6498]
The latest preview build does not work in safari but works fine in chrome.
<img width="323" alt="Xnip2019-06-07_10-46-17" src="https://user-images.githubusercontent.com/28266566/59078420-9e9c3f00-8911-11e9-9ce5-1dc555a85c2a.png">
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/28266566/59078421-9f34d580-8911-11e9-98db-5386d30319f5.png">

**Comment by afshin** [comment]
I am seeing this as well. It should begin working if you run the command:
```shell
jupyter lab build
```
It looks as though we didn't ship all of the assets, perhaps. Although I'm a little confused about why it works in other browsers if that is the case.

**Comment by kanitw** [comment]
I got this too.

**Comment by firasm** [comment]
Note that this is still an issue in 1.0.0rc0!

Running the `jupyter lab build` command as suggested by @afshin solved the problem.

**Comment by jasongrout** [comment]
Closing as fixed now.
