### ISSUE TITLE
Avoid showing tracebacks in CLI

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6499]
We should not be showing the user full tracebacks in CLI.  

- It could extend beyond the scroll limit of their terminal
- It can be overwhelming

I think we should follow the lead of `npm` and `yarn` and create an error file that can be easily copied into an issue or given to an administrator.

**Comment by blink1073** [comment]
We should also include as part of a build failure the app directory and a note that they may be able to run `jupyter lab clean && jupyter lab build` to fix the issue.  A successful build should delete the error file, the same way it does with npm.

**Comment by blink1073** [comment]
@vidartf, are you up for tackling this one?

**Comment by vidartf** [comment]
If I can find some time. When is it needed by? :)

**Comment by blink1073** [comment]
The 17th. 😀

**Comment by vidartf** [comment]
Some related work in https://github.com/jupyterlab/jupyterlab/pull/6567. What we can do on top of that one is to add a file logger with debug log level, and only delete that log right before a successful exit.

**Comment by vidartf** [comment]
BTW, when you say CLI here, which entry points do you mean? I'm thinking that install/uninstall/build are the important ones?

**Comment by blink1073** [comment]
Yeah those sound good for now.

**Comment by vidartf** [comment]
I think the PR should now resolve this issue as well.
