### ISSUE TITLE
Mangled 'Shutdown' notice on running sidebar

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab#6501]
Hi! Thanks for using JupyterLab.

**Describe the bug**
On 1.0.0a6 with Chrome on MacOS, I am currently (at least with my font size defaults) getting the "Shutdown" buttons to get all mangled at the default width of the sidebar:

![image](https://user-images.githubusercontent.com/57394/59133143-f051c300-892b-11e9-8adf-c088ff8eb5f8.png)

If I resize it manually it's OK, but I don't recall this happening in previous versions. It's also interesting that the effect is different depending on the size of the filename:

![image](https://user-images.githubusercontent.com/57394/59133191-0fe8eb80-892c-11e9-89ca-6e744f6c372c.png)

and finally once I resize enough it does work:

![image](https://user-images.githubusercontent.com/57394/59133204-1a0aea00-892c-11e9-9694-2d05972da815.png)

**To Reproduce**

Have notebooks running and click on the "running" tab on the sidebar.

**Expected behavior**

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome 74
- JupyterLab 1.0.0a6

**Comment by jasongrout** [comment]
This should be fixed by https://github.com/jupyterlab/jupyterlab/pull/6489 (by a first-time contributor too!)
