### ISSUE TITLE
Incremental text output is broken

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#6505]
**Describe the bug**

In JupyterLab master, if you run code that adds new text output, you get the existing output appending again and again.

**To Reproduce**

Open notebook and type the code:

![Screen Shot 2019-06-07 at 9 36 41 PM](https://user-images.githubusercontent.com/27600/59142054-d97f9080-896c-11e9-9649-8e9a9cc74936.png)

**Expected behavior**

![Screen Shot 2019-06-07 at 9 39 37 PM](https://user-images.githubusercontent.com/27600/59142058-e8664300-896c-11e9-97b2-8881de4e3d19.png)

What is really weird is that if you open the *same* notebook in classic, with the output saved, it is fixed. Somehow, the output data is the same, it is how we display it.

**Comment by ellisonbg** [comment]
And if you save, close and open the same notebook in *Lab* is renders fine. So this is only while the code is running.

**Comment by jasongrout** [comment]
Is this the cause behind #6497?

**Comment by blink1073** [comment]
Maybe related to #6304?

**Comment by ellisonbg** [comment]
Yes I think this is related to the pymc issue, and likely caused by the recent change.I am going to focus on the UX work so if others can look into this that would be great :-)
