### ISSUE TITLE
Use data-fns for our time functions

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6510]
We should be able to use `date-fns` now which is significantly smaller than `moment.js` and supports tree-shaking:

https://github.com/you-dont-need/You-Dont-Need-Momentjs#brief-comparison
https://github.com/you-dont-need/You-Dont-Need-Momentjs#time-from-now
https://github.com/you-dont-need/You-Dont-Need-Momentjs#format

https://github.com/jupyterlab/jupyterlab/blob/bd04328b87c0e535565971e5621f864650516347/packages/coreutils/src/time.ts

**Comment by ibdafna** [comment]
Will look at this tonight.

**Comment by blink1073** [comment]
👍

**Comment by ibdafna** [comment]
I've had a look. One of the functions we're proposing to use, `formatDistance`, is only available in the v2 pre-release of date-fns. My questions are:

1. Are we okay with using the pre-release version?

If not, do we want to:

2. Implement the `formatDistance` functionality using the `format` and `distance` functions from the date-fns library, or:

3. Wait for the official v2 release

**Comment by jasongrout** [comment]
> Are we okay with using the pre-release version?

No, not at this point (with 1.0 so close)



>     1. Implement the `formatDistance` functionality using the `format` and `distance` functions from the date-fns library, or:

If that's easy, I don't see a problem with that



>     2\. Wait for the official v2 release

That's fine too.

**Comment by dLamSlo8** [comment]
Should we close this issue? Its development seems to have moved to the issue mentioned above.

**Comment by jasongrout** [comment]
Reopening, given https://momentjs.com/docs/#/-project-status/

**Comment by jasongrout** [comment]
Actually, date-fns may not be the best choice. I'll close and open a new issue for evaluating moment.js and all alternatives.
