### ISSUE TITLE
Lazy Load Vim Mode

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6511]
We should only load vim mode if that keymap is set (using `import('codemirror/keymap/vim.js')`).  The mode is quite large in size.

https://github.com/jupyterlab/jupyterlab/blob/f29214f64ff0f135afac2d7a784e1c43269a77ca/packages/codemirror/src/editor.ts#L52
https://github.com/jupyterlab/jupyterlab/blob/ce4c47a99296721ca38ae2727737ae95b4b0216c/packages/codemirror-extension/src/index.ts#L153

**Comment by ibdafna** [comment]
Taking this one

**Comment by blink1073** [comment]
Cheers!

**Comment by vidartf** [comment]
Fixed in #6516.
