### ISSUE TITLE
Cells doesn't wrap the number of lines in cell

### ISSUE THREAD

**Issue by Anton-Velikodnyy** [jupyterlab/jupyterlab#6514]
**Describe the bug**
On Firefox, the cell does not wrap the number of lines, if the number of lines is less than 3.
So if one or two lines of code are present, the cell size is almost 3 lines deep. (slightly less than 3 as when a 3rd line is added the cell size increases.). See screenshots as they are much more descriptive.

**To Reproduce**

1. Open jupyter lab on Ubuntu 16.04  with `~$ jupyter-lab`

**Expected behavior**
I expected the cell size to match between Chrome and Firefox

**Screenshots**
On Firefox 67 and 63
![image](https://user-images.githubusercontent.com/30283914/59150235-2008d580-89d5-11e9-84bc-e88254cb8707.png)

On Chrome 
![image](https://user-images.githubusercontent.com/30283914/59150231-fea7e980-89d4-11e9-82bc-eca23c25ce5e.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 16.04
- Browser  firefox 67.0 and firefox 63.0
- JupyterLab 0.35.6

**Comment by jasongrout** [comment]
Can you try with the latest pre-release: `pip install --pre jupyterlab`?

**Comment by Anton-Velikodnyy** [comment]
Running that I get 
```
chat 1.0.7.dev136 has requirement numpy==1.13.1, but you'll have numpy 1.16.4 which is incompatible.
chat 1.0.7.dev136 has requirement requests==2.12.1, but you'll have requests 2.21.0 which is incompatible.

```
I can't revert numpy to 1.13 as that version isn't supported by tensorflow.

**Comment by jasongrout** [comment]
That seems very odd - jupyterlab doesn't require numpy or chat...

**Comment by Anton-Velikodnyy** [comment]
Maybe broken dependencies from another installation. I'll try fresh anaconda environment tomorrow. and let you know about the results.

**Comment by jasongrout** [comment]
@Anton-Velikodnyy - any further results on this?

**Comment by Anton-Velikodnyy** [comment]
Firefox
![image](https://user-images.githubusercontent.com/30283914/65837598-3bfaf480-e2ae-11e9-97b1-2d4045e6dc9f.png)
Chrome
![image](https://user-images.githubusercontent.com/30283914/65837606-5e8d0d80-e2ae-11e9-8254-b009f8c3d425.png)

**Comment by Anton-Velikodnyy** [comment]
Firefox 69.0.1 
Chrome 75.0.3770.80
Created a new conda environment,
ran `conda install python=2.6` and
`pip install --pre jupyterlab`

**Comment by jasongrout** [comment]
I think we have upgraded codemirror since the last comment above. Do you mind trying with the latest JupyterLab 2.0 RC prerelease? Again, `pip install --pre jupyterlab`.

**Comment by Anton-Velikodnyy** [comment]
I tried it with `pip install --pre jupyterlab` (although with python 3.7) and I still have same error.

**Comment by jasongrout** [comment]
I just double-checking - that did install JupyterLab 2.0RC0, right?

**Comment by Anton-Velikodnyy** [comment]
`jupyter-lab --version` gives me `2.0.0rc0`
