### ISSUE TITLE
Text color of cell selection in dark mode

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#6520]
**Describe the bug**

Text color is dark for the name of the cell type in the cell type selector in dark mode.

**To Reproduce**

Open a new notebook.

**Expected behavior**

Text should use standard theme variables for light text in dark mode.

**Screenshots**

![Screen Shot 2019-06-09 at 1 08 51 PM](https://user-images.githubusercontent.com/27600/59166875-ede59980-8ae2-11e9-981e-74b16da84c2c.png)

**Comment by ian-r-rose** [comment]
This may be a UI item that differs between browsers (we have seen different handling of this dropdown on Firefox and Chrome before). When I look at it on dark mode (Firefox+Ubuntu), the color looks fine:
![image](https://user-images.githubusercontent.com/5728311/59204058-af88c280-8b54-11e9-9ac4-d63e9dc92d05.png)

I do, however, see that the hover color of the dropdown looks a little wonky.

**Comment by ian-r-rose** [comment]
Xref #5168, #5324

**Comment by ian-r-rose** [comment]
With regards to the hover color: looks like there are some blueprint CSS rules that need to be overridden with our theming.
