### ISSUE TITLE
Tabs in main work area have extra border.

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#6521]
**Describe the bug**

Tabs of activities in the main work area should have a borderless transition to the activity toolbar below. The tab itself now has a bottom border. As we fix this we should be very careful to understand how this happened - I am guessing we were fixing another bug. This was handled in the past by making the tab was made 1px taller, and then moved down 1px to hide that border. Should be tested in light/dark theme.

**To Reproduce**

Open any activity in the main work area.

**Screenshots**

![Screen Shot 2019-06-09 at 1 09 05 PM](https://user-images.githubusercontent.com/27600/59166951-82e89280-8ae3-11e9-9278-c4b76e6310da.png)

**Comment by jasongrout** [comment]
I don't see this in 1.0a6 on mac in either chrome or firefox.

**Comment by jasongrout** [comment]
I do see this on current master, though.

**Comment by ian-r-rose** [comment]
I would think this is related to the tab-drop-zone stuff, but that was in 1.0a6, right?

**Comment by ian-r-rose** [comment]
Looks like an unintended consequence of #6492, perhaps we should also remove `border-bottom` from that rule.

**Comment by jasongrout** [comment]
It looks like we didn't catch it right there in the screenshot on that PR.
