### ISSUE TITLE
Dev-mode broken

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#6523]
**Describe the bug**

For the current master adf2f3f421906bfb61255fa74f783d33d6def7f6, the dev mode is broken.

Nota: compiling and running in standard mode (i.e. through `jupyter lab build`) is working.

**To Reproduce**

1. Compile using `jlpm run build`
2. Run in dev mode `jupyter lab --dev-mode`

**Desktop**

- OS: Windows 10 Pro
- Browser firefox 67
- JupyterLab adf2f3f421906bfb61255fa74f783d33d6def7f6

**Additional context**

<details><summary>Troubleshoot Output</summary>
<pre>
pip list:
        Package           Version  Location
        ----------------- -------- ---------------------------------------
        attrs             19.1.0
        backcall          0.1.0
        bleach            3.1.0
        certifi           2019.3.9
        colorama          0.4.1
        decorator         4.4.0
        defusedxml        0.5.0
        entrypoints       0.3
        ipykernel         5.1.0
        ipython           7.4.0
        ipython-genutils  0.2.0
        jedi              0.13.3
        Jinja2            2.10.1
        jsonschema        3.0.1
        jupyter-client    5.2.4
        jupyter-core      4.4.0
        jupyterlab        1.0.0a6  f:\frederic\documents\github\jupyterlab
        jupyterlab-server 0.3.4
        MarkupSafe        1.1.1
        mistune           0.8.4
        nbconvert         5.4.1
        nbformat          4.4.0
        notebook          5.7.8
        pandocfilters     1.4.2
        parso             0.4.0
        pickleshare       0.7.5
        pip               19.0.3
        prometheus-client 0.6.0
        prompt-toolkit    2.0.9
        Pygments          2.3.1
        pyrsistent        0.14.11
        python-dateutil   2.8.0
        pywinpty          0.5.5
        pyzmq             18.0.0
        Send2Trash        1.5.0
        setuptools        41.0.0
        six               1.12.0
        terminado         0.8.2
        testpath          0.4.2
        tornado           5.1.1
        traitlets         4.3.2
        wcwidth           0.1.7
        webencodings      0.5.1
        wheel             0.33.1
        wincertstore      0.2
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 18:48:13.952 LabApp] Serving notebooks from local directory: F:\Frederic\Documents\GitHub
[I 18:48:13.953 LabApp] The Jupyter Notebook is running at:
[I 18:48:13.954 LabApp] http://localhost:8888/?token=7ec69afe5a71c8e26ef6e255eb4b362592eae168b364977a
[I 18:48:13.956 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:48:13.970 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/freud/AppData/Roaming/jupyter/runtime/nbserver-3744-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=7ec69afe5a71c8e26ef6e255eb4b362592eae168b364977a
[W 18:48:15.974 LabApp] 404 GET /main.d955ba4628dd88055c04.js (127.0.0.1) 41.00ms referer=http://localhost:8888/lab?token=7ec69afe5a71c8e26ef6e255eb4b362592eae168b364977a
[W 18:48:15.978 LabApp] 404 GET /vendors~main.4993eace839e53b76357.js (127.0.0.1) 2.00ms referer=http://localhost:8888/lab?token=7ec69afe5a71c8e26ef6e255eb4b362592eae168b364977a
[W 18:48:16.014 LabApp] 404 GET /vendors~main.4993eace839e53b76357.js (127.0.0.1) 1.00ms referer=http://localhost:8888/lab
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
La ressource à l’adresse « http://localhost:8888/main.d955ba4628dd88055c04.js » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff). lab
La ressource à l’adresse « http://localhost:8888/vendors~main.4993eace839e53b76357.js » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff). lab
Échec du chargement pour l’élément <script> dont la source est « http://localhost:8888/main.d955ba4628dd88055c04.js ». lab:78:1
La ressource à l’adresse « http://localhost:8888/vendors~main.4993eace839e53b76357.js » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff). lab
Échec du chargement pour l’élément <script> dont la source est « http://localhost:8888/vendors~main.4993eace839e53b76357.js ». lab:78:1
</pre>
</details>

Sorry this is in French. But basically it says that the MIME type is incorrect for two javascript files.

**Comment by jasongrout** [comment]
I did a clean compile on macos of master and things work fine for me in firefox.

Is it related to https://github.com/jupyter/notebook/issues/4467 (fix in notebook 5.7.8)?

**Comment by jasongrout** [comment]
Can you make sure you're running notebook 5.7.8 or later?

**Comment by ian-r-rose** [comment]
I saw the same thing this morning before installing the prerelease/master of `jupyterlab_server`.

**Comment by jasongrout** [comment]
ah, I wasn't even able to do a fresh compile before installing jupyterlab_server 1.0rc0

**Comment by fcollonval** [comment]
@jasongrout  and @ian-r-rose Thanks a lot for the reactivity. I can confirm, I was running notebook==5.7.8 but jupyterlab_server=0.3.4. 

After upgrading the jupyterlab-server, executing
```bash
pip install jupyterlab-server==1.0.0rc0
```

I got back the dev mode on the master 🎉
