### ISSUE TITLE
Downloading html file from file explorer opens file in new tab instead of downloading

### ISSUE THREAD

**Issue by kevmk04** [jupyterlab/jupyterlab#6525]
I have an .html file that was generated by the plotly offline.iplot function. My typical workflow is to create the file from a notebook and download the html file to share with colleagues. On an existing jupyterhub/jupyterlab install this functionality works fine. It downloads directly to my local download folder.

I recently setup a TLJH install on a new server. When I try to download the same .html file (or any html file for that matter), it opens the file in a new browser tab instead of downloading it. It also seems to try to do this with other file extensions and then downloads them normally, but it does flash open a new tab briefly before downloading. The older install does not exhibit that same flash of a new tab for other files types.

I'm using Chrome as the browser.

**Old jupyterhub/jupyterlab setup where download works:**
jupyterhub version: 0.8.1
jupyterlab version: 0.35.4
notebook version: 5.4.1
Installed manually

**New jupyterhub/jupyterlab setup where download does not work:**
jupyterhub version: 1.0
jupyterlab version: 0.35.4
notebook version: 5.7.8
Installed with TLJH installer

I'm unsure if this is a jupyterlab issue, something with TLJH install, or something else entirely.

**Comment by kevmk04** [comment]
#6139 pull request seems to be the difference between the two setups.  The older install still has the old element.setAttribute('download', ''), not sure why though.  My understanding is that the element.setAttribute('target', '_blank') forces a new window to be opened.

**Comment by scottkall** [comment]
I'm having a similar issue with a multiqc HTML report. One other variable is that Chrome may have updated. Are your Chrome versions the same across both setups?

**Comment by kevmk04** [comment]
Good call! I'll double-check what version of chrome this is but both setups were tested in the same browser session on the same computer. 

Additionally, this same behavior seems to also be happening with .png images.

**Comment by kevmk04** [comment]
My chrome is/was at Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by jasongrout** [comment]
I think this is part of an ongoing discussion of downloading (#6658, #6139, etc.). Let's move the conversation to #6658.

**Comment by kevmk04** [comment]
@jasongrout This bug is still active in V 1.0.1.  I believe this needs to be reopened. 

An html file when downloaded opens in a new tab in Chrome. The same behavior is found when trying to download an image file (.png).  It appears that chrome attempts to render the file instead of downloading. 

The behavior in Firefox is slightly different.  When the download command is selected, firefox prompts the user that it is trying to open the file and wants to know what program to use.  You get the option to save the file but it appears that JupyterLab is not forcing a download.  See the image below for the message that Firefox shows. The behavior is the same for both .html and .png files.  I would guess that other types of files that can be rendered by a browser would also see this issue. 

![image](https://user-images.githubusercontent.com/38329905/60908191-82edc680-a238-11e9-8430-96772c4a6ba1.png)
