### ISSUE TITLE
Tabs have no visible side border in dark theme

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6527]
It seems that tabs in the dock panel have background `--jp-layout-color2` and border `--jp-border-color1`: https://github.com/jupyterlab/jupyterlab/blob/48b412dbd542f952a38d53343038fe5b959bcd70/packages/application/style/tabs.css#L51-L52

This is a bit odd, since I thought we were using the same-numbered colors as pairs. It is a problem in the dark theme since those two colors are identical in the dark theme:

https://github.com/jupyterlab/jupyterlab/blob/d69ce4947da79d82d27f2d3fecb70b66acbaecbe/packages/theme-dark-extension/style/variables.css#L92-L95
https://github.com/jupyterlab/jupyterlab/blob/d69ce4947da79d82d27f2d3fecb70b66acbaecbe/packages/theme-dark-extension/style/variables.css#L202-L206

(and where is `--jp-border-color4` to match the layout color 4?)

You can see there is no visible border as well in dark:

<img width="726" alt="Screen Shot 2019-06-10 at 11 36 20 AM" src="https://user-images.githubusercontent.com/192614/59223295-db935a80-8bcb-11e9-9c91-e40f8d1083d0.png">

compared to the light theme:
<img width="702" alt="Screen Shot 2019-06-10 at 11 37 59 AM" src="https://user-images.githubusercontent.com/192614/59223306-e1893b80-8bcb-11e9-8484-3d8d947c8e46.png">

**Comment by jasongrout** [comment]
Suggestions: 

1. change tabs to use paired colors, and 
2. change the color2 variants above to be different colors.

**Comment by ellisonbg** [comment]
The tabs in the sidebars don't have this issue:

![Screen Shot 2019-06-11 at 9 34 26 AM](https://user-images.githubusercontent.com/27600/59289935-2775ec00-8c2c-11e9-8837-3cb0374fab27.png)

For 1.0, let's just copy that.

**Comment by jasongrout** [comment]
tabs in the sidebars don't have dividers between tabs either in your screenshot, so they do have this issue, right?

**Comment by jasongrout** [comment]
I played with this a bit, but didn't come up with anything I thought was great. To be clear, I think there is still work to do here. The main issue here is that inactive tabs are `--jp-layout-color2`, but that is the same as the `--jp-border-color1`, which is the tab border color, so tab borders do not show up in horizontal tabs.

**Comment by jasongrout** [comment]
> The tabs in the sidebars don't have this issue:

To be very clear, tabs in the sidebars *do* have the issue of no dividing borders between tabs. I think it's fine for these vertical tabs because they are simple icons, not text and close icons.
