### ISSUE TITLE
CSS Usage Cleanup

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6530]
Follow up to #6395 

I'll flesh this out more tomorrow:

- [x] add style fields to phosphor packages with styles
- template index.css ( in examples too)
  -- need to declare which other deps to import (like font-awesome)
  -- then we add them in dependency order
  -- then we add ./base.css
- Specify where css file was generated from

**Comment by blink1073** [comment]
Note: we can't extract css in general because the static url is dynamic on base_url (in jhub for example).

**Comment by jasongrout** [comment]
Should we wait for an alpha for this?

**Comment by blink1073** [comment]
I think if Brian takes master for a spin and doesn't see anything glaring we should release alpha and rc before this.

**Comment by blink1073** [comment]
Note to self: https://www.npmjs.com/package/dependency-graph
