### ISSUE TITLE
Open directory from Path (manually cd)

### ISSUE THREAD

**Issue by tslaton** [jupyterlab/jupyterlab#6537]
It is already possible to open a file from a path, as pictured:

<img width="501" alt="Screen Shot 2019-06-11 at 3 57 43 PM" src="https://user-images.githubusercontent.com/9665562/59312409-e5679d00-8c61-11e9-9e84-b75dd95534ab.png">

However, it is not possible to open (or `cd`) to a directory in a similar manner from the filebrowser. This could be added in the "File" menu next to "Open from Path..." or possibly via directly editing the breadcrumbs to give them a new path.

@jasongrout expressed interest in getting this out with v1.0 as it would improve quality of life for many users.

Some related issues: 
* https://github.com/jupyterlab/jupyterlab/issues/5481
* https://github.com/jupyterlab/jupyterlab/issues/6130
* https://github.com/jupyterlab/jupyterlab/issues/4566
* https://github.com/jupyterlab/jupyterlab/issues/2160

**Comment by tslaton** [comment]
@meeseeksdev tag "pkg:filebrowser" "type:Enhancement"

**Comment by jasongrout** [comment]
The pain point this addresses is that apparently it can be terribly complicated to navigate the file hierarchy in a context where the server root is the system root (which apparently is not uncommon in in HPC contexts, for example). This allows people to just easily type in a path to navigate to a folder.

**Comment by jasongrout** [comment]
@tslaton - do you want to try implementing this tomorrow? The command would basically call the file browser model's cd method: https://github.com/jupyterlab/jupyterlab/blob/03a3c01455525770d72548adc49066cbc2b7b0a0/packages/filebrowser/src/model.ts#L242

Probably the harder question is where to expose this. I could see a right-click on the breadcrumbs exposing it. A double-click would follow some existing patterns in, for example, Windows, but may be too complicated to implement before 1.0 (i.e., you'd have to somehow distinguish between single click and double click on the breadcrumbs, which maybe you could do by in the single click immediately awaiting a frame, and then checking to see if a double-click event had gone by...). A File menu entry like you said might be another possibility, but it's not clear to me what the name should be.

CC @ellisonbg as well.

**Comment by jasongrout** [comment]
On second thought, I wonder if we could repurpose the existing `Open from path...` to open a directory in the file browser when a directory is typed (right now it shows an error when you give it a directory).

**Comment by jasongrout** [comment]
On second thought about the milestone, I think this is fine to go in 1.1 (which we hope to follow up with quickly). However if we can get it done tomorrow or so, it's probably fine to go into 1.0 as well.

**Comment by tslaton** [comment]
I'm trying to look into this, but I'm having some trouble getting my fork with the latest master running locally. I'd previously had it running, but `LabApp` now seems like it can't find the bundled js files (404 errors for the hashed `main` and `vendors~main` files). 

I suspect browser caching issues, but clearing my cache hasn't fixed it.

**Comment by tslaton** [comment]
I've made some progress on this issue. I have another obligation for the new few hours, but I think it's possible I'll be able to get a PR up later tonight.

**Comment by jasongrout** [comment]
Fixed by #6561
