### ISSUE TITLE
Change file browser "home" icon to more clearly indicate server root

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6539]
As pointed out in #5256, the home icon is confusing in a situation where the server root is not the user's home directory. This apparently is not uncommon in, for example, HPC contexts, but also in other contexts where a user launches a server in a directory other than their home directory.

I think for 1.0, we can revisit changing that home icon to be something that more clearly indicates 'server root' rather than 'home'. Perhaps just a simple `/`?

**Comment by jasongrout** [comment]
CC @tgeorgeux @ellisonbg

**Comment by jasongrout** [comment]
Also, from https://github.com/jupyterlab/jupyterlab/issues/6207, perhaps we can make a tooltip for this icon show the server root provided in the page config.

**Comment by jasongrout** [comment]
On the flip side, using something like `/` instead of the home icon may confuse users about the actual real server root directory. On the other hand, the nice thing about using `/` is that opening any file in the Open From dialog starts with `/` meaning the notebook server root.

**Comment by ian-r-rose** [comment]
Fixed by #6553
