### ISSUE TITLE
Losing output after disconnecting from remote

### ISSUE THREAD

**Issue by cossio** [jupyterlab/jupyterlab#6545]
I always experience loss of output when reconnecting to a remote Jupyter session. Not only do I lose any printed output that occurred during the time I was disconnected, but I cease to see any output at all even if the computation is still running.

Is there a way to recover the missed output, and to see the new generated output?

**Comment by jasongrout** [comment]
This is a fundamental issue with the Jupyter notebook server implementation, right now the answer is no. There have been lots of design discussions about removing this limitation in the future by moving state from the browser into the server.

That said, Cocalc (by @williamstein) is the one Jupyter frontend that does preserve such output (because it keeps track of these outputs at the server, not the browser).

**Comment by cossio** [comment]
So this is not Jupyter-Lab specific? Is there an issue tracking this somewhere else?

**Comment by jasongrout** [comment]
Right, not jupyterlab specific. See https://github.com/jupyterlab/jupyterlab/issues/2833 and many other discussions from a [google search](https://www.google.com/search?client=firefox-b-d&q=jupyter+notebook+losing+outputs).

**Comment by jasongrout** [comment]
I don't think there is a canonical issue tracking this across Jupyter. @rgbkrk and the nteract project are some of the people spearheading moving this state server-side.

**Comment by williamstein** [comment]
@rgbkrk also told me he recently put in a hack to the classic notebook that addresses this problem in some limited cases, in particular, when your browser gets disconnected but you do NOT close the tab.    I hope he can comment further about what he did.

**Comment by jasongrout** [comment]
The notebook server currently buffers outputs if it has no clients connected (perhaps that is what he is referring to?). It's limited in that if any client is connected to that session, it gets the outputs and things aren't buffered.

**Comment by jasongrout** [comment]
(I think it may also have some limitations about the client session id, which is I think where the limitation about not closing your tab may come from...)

**Comment by rgbkrk** [comment]
That's correct, the server will buffer outputs when no clients are connected replaying them when the user reconnects (with the same session). If the sessions don't match, messages won't be consumed. This is largely because otherwise the frontend doesn't know how to match up message id with the cell it (might) belong to (or even if the cell exists on the frontend...)

**Comment by bjtho08** [comment]
@rgbkrk so can this hack be extended to jupyterlab in any way? Or is there some "hidden" functionality to write the output to a log file on the remote in events such as these? I often run lengthy training sessions and more often than not it crashes with some error message, which I then can't see if I was disconnected when it happened

**Comment by rgbkrk** [comment]
I don't have time to work on JupyterLab so I really can't advise.

**Comment by jasongrout** [comment]
The functionality @rgbkrk referred to [above](https://github.com/jupyterlab/jupyterlab/issues/6545#issuecomment-502300280) is in the notebook server, not the frontend, so it works with any frontend using the notebook server, including jupyterlab, without having to do anything.

**Comment by bjtho08** [comment]
@jasongrout evidently it doesn't work since we experience loss of output and the ability to produce any new output until the kernel is restarted. Mind you, cells can still be run, but no output is shown.

**Comment by jasongrout** [comment]
Can you try in the recently released JLab 1.0? We recently reworked kernel connections, and that may also have taken care of this.

**Comment by bjtho08** [comment]
Stupid question, but is it possible to update Jupyter Lab while a kernel is actively running? I'm halfway through a 50 hour training session and my ssh connection died, so now I don't get any output (data is still saved, though, so I won't lose anything by letting it run).

**Comment by williamstein** [comment]
> Or is there some "hidden" functionality to write the output to a log file on the remote in events such as these?

Naive idea -- Can you use the open command to just write whatever you need to write to a file?  E.g.,

```
f = open('output.log','a')
...
f.write("a string\n")
f.flush()
...
```

In a terminal you can then do `tail -F output.log` to watch the results.

This is how we used to do long-running computations in the old days before notebooks...   This might not be an option for you though, depending on what software/kernel you are actually running.

**Comment by bjtho08** [comment]
@williamstein  It was a good idea, but unfortunately it would require that I somehow hot plugged a library that I'm using, since it is producing all my output and I need to somehow make sure that the output is not lost when the connection dies.

**Comment by bjtho08** [comment]
I've yet to test if 1.0.0 solves my issues because when I upgraded it completely broke my installation and I now have to completely reinstall conda along with all packages from scratch (because I'm an idiot and didn't use environments).

**Comment by cossio** [comment]
I think this can be closed in favor of https://github.com/jupyterlab/jupyterlab/issues/2833.
