### ISSUE TITLE
Move to `data-theme-light` to the document body

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#6554]
Right now we have a `data-theme-light` HTML attribute on the `div.jp-LabShell` that is a child of the document body. Because we attach dialogs to the document body, this theming hint isn't available to style the dialog. The proposed solution is to move this attribute to the document body. There are also other UI elements (completer) that we attach to the body that might need access to this attribute.

**Comment by jasongrout** [comment]
An alternative to this is any component that puts things in the DOM not under the lab shell, it is responsible for working with the theme manager programmatically to inquire and expose the theme information to its DOM elements. This helps us avoid having global state.

For example, what if there are two JLab components running in a page, but not in a single application, each with its own theme manager - who wins the body data spot? In general, I think namespacing is much cleaner.

**Comment by jasongrout** [comment]
To which you would reply, of course: 'Jason, the entire theming system is in the global namespace because all of the CSS variables are in the root namespace. You cannot have two different themes on the page because of this anyway, so you might as well make it official by taking over the body element too.'

Okay, good point. It still feels a bit weird and not very clean, but so is non-namespaced global CSS, and I suppose we can't fix that anytime soon.

**Comment by jasongrout** [comment]
This is set at https://github.com/jupyterlab/jupyterlab/blob/2e9885a2c3095c5c91da64675b11294e8649ce7e/packages/apputils-extension/src/index.ts#L133-L142

If we are putting it on the body element, perhaps we should namespace it a bit more than `data-theme-light`, like at least `data-jp-theme-light`, etc.? Or maybe even `data-jupyterlab-theme-light`?

**Comment by ian-r-rose** [comment]
I agree that namespacing it would make sense. Unfortunately, this is a CSS attribute that was explicitly intended for extension authors to target, so this would be real breaking change to extension theming. But I suppose it's now or never.

**Comment by jasongrout** [comment]
Yes. That's why this is blocking the RC :).

So - was that a vote for namespacing it? What name?

**Comment by telamonian** [comment]
Namespacing a body-level attribute seems like a good plan. I vote for `data-jp-theme-light`, since that's consistent with how all of the CSS vars are namespaced.

**Comment by ian-r-rose** [comment]
I think `data-jp-theme-light` is good as well.
