### ISSUE TITLE
Pressing up when the cursor is at the top line of a code cell moves the cursor to the cell bellow

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#6557]
Like it says in the title, in recent builds of `master`, when my cursor is like this:

![image](https://user-images.githubusercontent.com/2263641/59391372-18815d80-8d42-11e9-8041-fe0edfe963eb.png)

and I hit the up button, the cursor/focus moves to the next cell:

![image](https://user-images.githubusercontent.com/2263641/59391401-2cc55a80-8d42-11e9-9dca-0607e3d63ca7.png)

Very annoying. The expected behavior is that the the cursor should move to the 0th position in the current cell:

![image](https://user-images.githubusercontent.com/2263641/59391465-64cc9d80-8d42-11e9-829f-8d0cbcf1ca4e.png)

Anyone else run into this?

**Comment by jasongrout** [comment]
Confirmed for me on master.

**Comment by telamonian** [comment]
I have a fix. I'll add a PR in a sec
