### ISSUE TITLE
User preference settings are not automatically loaded

### ISSUE THREAD

**Issue by zqwei** [jupyterlab/jupyterlab#6564]
After updating from 1.0.0a3 to 1.0.0a6 (even later in 1.0.0a8), I found that user preference settings are not automatically loaded for terminal at the moment a new terminal instance is opened (in which case it always set to the system defaults) and it is only activated after clicking Settings --> Terminal Theme --> Dark.

For example, the settings in menu is not adjusted according to the user preferences.

I wonder if there is any possibility to load user preference file automatically when opening a new terminal. Many thanks!

![Screen Shot 2019-06-13 at 1 44 32 PM](https://user-images.githubusercontent.com/13616597/59455455-3bfbe500-8de2-11e9-81de-79dc63af0ed3.png)

**Comment by saulshanabrook** [comment]
Thanks for reporting this, yep it looks like a bug. I was able to reproduce this on master.

**Comment by jasongrout** [comment]
Fixed in #6629.

**Comment by jasongrout** [comment]
Sorry, that hasn't been merged quite yet.

**Comment by jasongrout** [comment]
Now it is merged.
