### ISSUE TITLE
Rename should keep .ipynb extension

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab#6565]
**Describe the bug**
When renaming a file, the dialog does not offer any options regarding the extension. Which is fine, as I'm renaming a notebook, it's pretty sure it should stay a notebook, right?
But when I remove the current name because the whole filename is marked, by pressing delete the extension goes away as well and the newly stored file will have no extension which renders it not applicable to the notebook editor.

**To Reproduce**

1. Open a notebook
2. Right-Click->Rename
3. Delete the whole filename, provide new one without extension
4. See new file without .ipynb extension

**Expected behavior**
A renamed file with .ipynb extension, because I renamed a notebook, I think that's a reasonable expectation.

**Desktop (please complete the following information):**

- OS: macOS 10.14
- Browser Safari 12.0.3
- JupyterLab 0.35.6

**Additional context**
I guess there are 2 solutions possible:

Simpler (maybe) 1. When the file dialog opens, only preselect the stem of the filename without extension. That way, when user presses Delete, only the stem goes away while the extension stays.
More coding, I guess? 2. Make sure in the re-name code, that the new filename always receives the extension from the previous one.

I skip the details for this bug report, hope that's okay.

**Comment by jasongrout** [comment]
> 1. When the file dialog opens, only preselect the stem of the filename without extension. That way, when user presses Delete, only the stem goes away while the extension stays.

That seems like a great idea and a standard pattern



> 2. Make sure in the re-name code, that the new filename always receives the extension from the previous one.

We can't do this, since it is the only way to change file types if you actually want to do that.

**Comment by michaelaye** [comment]
Well but that’s a fringe case for a JLab env because why, inside JLab would you remove the functionality of working in the notebook editor? I’d argue you could always use File->Export if one really wants to change filetype?

**Comment by michaelaye** [comment]
In other words, I would never expect to be able to change filetype via a dialog that opens as a rename.

**Comment by telamonian** [comment]
> In other words, I would never expect to be able to change filetype via a dialog that opens as a rename.

I... definitely would expect to be able to do that? There's always going to be times when it's useful to change extension (say, removing the `.sh` or `.py` from an executable script), and it'll be real frustrating if the UI tries to fight you when you go to do that.

On the other hand I really like suggestion `1.`. That gives the user a margin of safety/convenience without tying their hands.

**Comment by jasongrout** [comment]
> In other words, I would never expect to be able to change filetype via a dialog that opens as a rename.

I've never known a rename command that prevents me from changing the filetype if I really want to.

**Comment by michaelaye** [comment]
I think you guys argue from the point of an OS tool though, but as JLab is by now also offering editing for a whole bunch of other file formats, I see what you mean.
But let me restate my workflow request as suggestion 3:

3. If the user does **NOT** provide any extension, can we use the same one as before? 

That way it would prevent creation of a file that doesn't open anywhere by default?

**Comment by jasongrout** [comment]
Thanks for a clarification. I really like your suggestion 1 - that makes it easy to rename a file and keep the type, but it is also easy to rename the entire file name if you want.

**Comment by jasongrout** [comment]
@blink1073 just checked, and our current solution is that the filename *without* the extension is highlighted in the rename dialog, so pressing delete or typing should preserve the extension.
