### ISSUE TITLE
Command + W closes window instead of tab on macOS

### ISSUE THREAD

**Issue by clapierre** [jupyterlab/jupyterlab#6574]
From Web4All Hackathon https://github.com/diagram-codesprint/jupyterlab/issues/6
**Describe the bug**
The keyboard shortcut for File -> Close Tab is Command + W.  Pressing Command + W on an open tab closes the browser window.

**To Reproduce**
1. Open a notebook.
2. Press Command + W.
3. See browser window close.

**Expected behavior**
Either 1) do not advertise the keyboard shortcut or 2) close the tab and not the window.

**Desktop (please complete the following information):**

- OS: macOS Mojave (10.14.4)
- Browser Chrome 4.0.3729.131 and Safari 12.1 (14607.1.40.1.4)
- JupyterLab 1.0.0a3

**Comment by vidartf** [comment]
Since #6357 was fixed, is also resolved?

**Comment by saulshanabrook** [comment]
@vidartf Yes I believe that PR fixed this.
