### ISSUE TITLE
Repeating File Save Error when not connected to server

### ISSUE THREAD

**Issue by Junipyr** [jupyterlab/jupyterlab#6589]
**Describe the bug**

**To Reproduce**

1. Connect to a network Jupyter server & edit a Jupyter notebook in JupyterLab.
2. Disconnect from the server (e.g. by disconnecting from the network).
3. File Save Error pop-up appears repeatedly. After a few hours of inactivity numerous pop-up messages will have stacked, requiring a large number of clicks of "OK" before JupyterLab can be used. 

**Expected behavior**
A single message box should appear. If JupyterLab tries to connect/save and the user hasn't yet clicked "OK" on the previous message box, JupyterLab shouldn't generate a new message for the same thing.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac OS Mojave 10.14.4
- Browser Safari 12.1 (14607.1.40.1.4)
- JupyterLab 0.35.6

**Comment by saulshanabrook** [comment]
Yep, we should definitely improve this UX.

**Comment by jasongrout** [comment]
Fixed by #6517.

**Comment by Junipyr** [comment]
How is this fixed by #6517?

**Comment by vidartf** [comment]
@Junipyr Mostly by commit https://github.com/jupyterlab/jupyterlab/pull/6517/commits/6ba1eb4dfd2044872a30be24ee18e2717e49f033 as far as I see it.
