### ISSUE TITLE
Regression: URL truncation following workspace prompt

### ISSUE THREAD

**Issue by consideRatio** [jupyterlab/jupyterlab#6592]
I'm experiencing the bug in #5214 on 0.35.6, perhaps it was solved in #5830 but a regression followed?

In short, visiting `<my-notebook-server>/lab/tree/Untitled.ipynb` is fine, but if a second tab is opened and I get a workspace prompt, I don't end up on `<my-notebook-server>/lab/worskapces/a/tree/Untitled.ipynb` but instead simply `<my-notebook-server>/lab/workspaces/a`.

/cc: @afshin, author of the initial fix of this issue

**Comment by saulshanabrook** [comment]
I think this is fixed on master/the latest prerelease. I just tried it and it seems to open a file OK. Now we don't pop up with the workspace dialogue, we just autocreate a new one

**Comment by saulshanabrook** [comment]
I will close this, feel free to reopen if it doesn't work on the last alpha release.

**Comment by consideRatio** [comment]
Ah :tada:! Thanks @saulshanabrook !
