### ISSUE TITLE
New Output View and Panel

### ISSUE THREAD

**Issue by hadim** [jupyterlab/jupyterlab#6594]
Is the "Create New View from Output" feature in Jupyterlab supposed to work with [Panel](https://github.com/pyviz/panel)?

It does not work for me at the moment. Please see more details here: https://github.com/pyviz/panel/issues/483

**Comment by saulshanabrook** [comment]
I believe this is an error on the panel end. I will close this and we can continue the discuss over there.

**Comment by hadim** [comment]
Apparently the issue is known for a long time. See https://github.com/pyviz/pyviz_comms/issues/3

@jlab-dev: Any ideas, what is going on? Panel devs seem to be struggling.
