### ISSUE TITLE
FAQ is broken

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#6608]
In the help menu, we have an FAQ option. It is currently broken. This raises a bigger question though about what we should do with it. Should we update it? Remove it?

**Comment by ian-r-rose** [comment]
This may be a consequence of switching to ES6 imports. I can take a look this evening. I think it makes sens to still have to FAQ, with some light updating.

**Comment by ellisonbg** [comment]
In discussion, we decided to:

* Remove the FAQ extension.
* Add a "JupyterLab FAQ" help link that points to the JupyterLab main FAQ in the docs.

**Comment by jasongrout** [comment]
> In discussion, we decided to:

To be fair, that discussion did not include @ian-r-rose's thoughts about why we should still have a FAQ.

To me, it's redundant with the docs, so not needed. We can have a menu item that opens up the doc page.

Why do you think it is still needed, @ian-r-rose?

**Comment by jasongrout** [comment]
ping @ian-r-rose for more information about why we should keep this. What are you thoughts about it?

**Comment by ian-r-rose** [comment]
Ah, I thought I had commented, must not have pressed send.

I don't have strong feelings about it, except that the Q's in the FAQ really are FA'd, so it seemed reasonable to keep it in for a while. Not everyone is an early adopter, so for a lot of people this may be the first time seeing Lab. But if that information is available elsewhere, I think we can remove it.
