### ISSUE TITLE
Downloading files is forbidden

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#6609]
**To Reproduce**

1. Right click on a file
2. Click Download

**Expected behavior**
The file downloads

**Screenshots**
<img width="228" alt="Screen Shot 2019-06-18 at 11 36 52 AM" src="https://user-images.githubusercontent.com/1186124/59710407-c9ae4a80-91bd-11e9-958b-3db7ffe95c98.png">

**Comment by jasongrout** [comment]
Download worked fine for me on master(ish) when I just tried. Can you try on master?

**Comment by jasongrout** [comment]
Since #6658 has a bit more debugging information, let's carry on the conversation there.
