### ISSUE TITLE
Use metadata from mime bundles

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#661]
Display bundles can contain metadata that influences the rendering of the item:

For example, the height/widgth of an [image](https://github.com/jupyter/notebook/blob/d11d2dd9425774c759555c8aa855687ce44e6d32/notebook/static/notebook/js/outputarea.js#L731).

**Comment by ellisonbg** [comment]
I think we have addressed this in master?

**Comment by blink1073** [comment]
We aren't using the `isolated` [metadata](https://github.com/jupyter/notebook/blob/f8d4d6ad2dcaaed68851483db1a4efe742b52278/notebook/static/notebook/js/outputarea.js#L387)

**Comment by ellisonbg** [comment]
@blink1073 did this get fixed?

**Comment by blink1073** [comment]
No, the logic from the classic Notebook is [here](https://github.com/jupyter/notebook/blob/9f7ee6830e40c805176f034d60df3b3cd19c8f39/notebook/static/notebook/js/outputarea.js#L391), that we need to emulate in the output area to wrap a rendermime output.

**Comment by jasongrout** [comment]
I'll try to take a look at this, or @blink1073 if you have time and beat me to it, feel free.
