### ISSUE TITLE
How to change which "Notebooks" folder that opens 

### ISSUE THREAD

**Issue by yabushalbak** [jupyterlab/jupyterlab#6614]
Jupyter Lab currently opens the notebook folder from...
C:\Users\Administrator\Downloads\WPy64-3680\Notebooks

However, I want it to set it so that it opens this folder instead...
C:\Users\Administrator\Dropbox\notebooks

I want to change it so that it opens up the second folder always every time I open up Jupyter lab and when I create a new notebook or delete one or edit an already existing one all of that would take place in the folder of the second path rather than the one that is preset by Jupyter lab(which is the first one)

Does anyone know how I could do that. I would imagine it is quite easy and simple to do. I am using windows. Help would be greatly appreciated. Thank you.

**Comment by jasongrout** [comment]
Use the `--notebook-dir` command-line option. See `jupyter lab --help-all` for the relevant help.
