### ISSUE TITLE
File Browser UX Defect

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#6615]
**Describe the Defect**
Icons in the file browser are oddly squared off, leaving the visual design to appear disjointed.

**To Reproduce**

1. Open JupyterLab
2. Navigate the file browser.

**Expected behavior**
Folders in the file browser should be rectangular and filled, they are square and outline. This is a misuse of the folder_open icon. That icon is used to indicate which of a group of folders are open, not the action of opening a folder. The icons should match the one we used to indicate the root folder in the toolbar above. Another icon here that should be replaced is the raw text icon, it's cut off 2/3 height to be square as well, this should be the shape of page, it currently looks mirrored and rotated 90 degrees. A third icon we could improve (minor gripe) is the python icon could be two-tone. I don't see a heavy benefit of leaving it all blue instead of blue/yellow like the standard python logo/icon (not as big a deal IMO).

**Screenshots**
<img width="348" alt="Screen Shot 2019-06-17 at 4 42 36 PM" src="https://user-images.githubusercontent.com/22109376/59714913-8fe24180-91c7-11e9-8532-10753c99f24c.png">

**Desktop (please complete the following information):**

- OS: [OS]
- Browser [Chrome]
- JupyterLab [Developer build]

**Comment by ellisonbg** [comment]
Also, while I am at it, the folder icon to the left of the breadcrumbs is slightly low:

<img width="84" alt="Screen Shot 2019-06-18 at 12 57 47 PM" src="https://user-images.githubusercontent.com/27600/59715440-b2288f00-91c8-11e9-95e5-9f2849669e5b.png">

**Comment by jasongrout** [comment]
Here is the folder icon in our sources:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/theme-light-extension/style/icons/jupyter/directory.svg

Is that squished to you? If it is, sounds like we need to redesign icons (big project?). If it isn't, then perhaps it is getting squished when put on the page (small project?).

**Comment by jasongrout** [comment]
And here's the file icon:

https://github.com/jupyterlab/jupyterlab/blob/master/packages/theme-light-extension/style/icons/jupyter/file.svg

**Comment by tgeorgeux** [comment]
@ellisonbg the folder icon is rendering in the correct alignment on my JupyterLab. But I haven't updated anything since yesterday; maybe it's a regression?

I'm on Chrome {Version 74.0.3729.169 (Official Build) (64-bit)} and the latest OS.

**Comment by ellisonbg** [comment]
Waiting until #6664 is merged to tackle this. It may have fixed it.

**Comment by ellisonbg** [comment]
Looks like this got fixed in #6664:

<img width="301" alt="Screen Shot 2019-06-20 at 4 34 22 PM" src="https://user-images.githubusercontent.com/27600/59887728-505b5700-9379-11e9-88de-8eb7f5fe5534.png">

**Comment by tgeorgeux** [comment]
In the screenshot you show here, the breadcrumbs folder icon is still too
low set.

**Comment by vidartf** [comment]
@tgeorgeux If this was not fixed somewhere else, could you reopen the issue?

**Comment by tgeorgeux** [comment]
It's not showing up on my computer. I've only ever seen it in screenshots. @ellisonbg can you replicate it with the most updated version?

**Comment by vidartf** [comment]
So, this is fully fixed?

**Comment by ellisonbg** [comment]
The icon at the top hasn't been moved up, but all the other icons are fixed.

**Comment by vidartf** [comment]
Reopened to track the low icon then. Feel free to move to 1.1 if that feels more appropriate.

**Comment by tgeorgeux** [comment]
Just checked to follow up on this. The folder is still rendering lower than it should:
<img width="363" alt="Screen Shot 2019-09-16 at 11 58 30 AM" src="https://user-images.githubusercontent.com/22109376/64985270-57f7a280-d879-11e9-8c77-1d5533eaa658.png">

**Comment by tgeorgeux** [comment]
Closing for #7575
