### ISSUE TITLE
Command Palette -  "..." Icon in header is not communicative (as is easily covered)

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#6618]
### UX Defficiency (1) Defect (2) -  "..." Icon on headers in command palette

**Context:** When you mouse over a header in the command palette, a "..." Icon appears to indicate you can filter the command palette by clicking on the dots or the header. Clicking will filter the search as shown above.

**Problem 1:** I'm not sure "..." is the correct icon usage here. When I saw the "..." icon I thought it was going to open a menu with more options. 

**Solution 1:** I think a "filter_list" icon makes more sense here. 
![baseline_filter_list_black_18dp](https://user-images.githubusercontent.com/22109376/59711878-d8e2c780-91c0-11e9-8b3c-36c825f3ef95.png)

**Problem 2:** If you're trying to click the icon that appears there's a very small window in which you can hit the icon without surfacing the slider. See the gif below.
![CommandPalletteDefect](https://user-images.githubusercontent.com/22109376/59712147-7807bf00-91c1-11e9-9db6-d24143a36ffe.gif)

**Solution 2:** This one's a bit trickier, one option would be to render the icons further left when the slider appears.

**Comment by jasongrout** [comment]
> **Solution 2:** This one's a bit trickier, one option would be to render the icons further left when the slider appears.

I think the scrollbar appearing/disappearing/overlaying is a macos thing we have no control or knowledge of in the code. I find it really annoying personally and I turn that disappearing scrollbar off as soon as I get a new mac in the system preferences.

**Comment by jasongrout** [comment]
> **Solution 1:** I think a "filter_list" icon makes more sense here.

Do we have the filter-list icon anywhere already? The code that adds the `...` is here:

https://github.com/jupyterlab/jupyterlab/blob/fd18d01404f7feb05475dfb5888ca8927a24b4eb/packages/apputils/style/commandpalette.css#L108-L112

**Comment by ellisonbg** [comment]
Will wait for #6663 to be merged to do this follow on icon work. I will use the filter list icon from MD and move it away from the scroll bar area.
