### ISSUE TITLE
Impossible action on tab bar of L/R side panel

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#6619]
The tabs in the L/R side panel are not closable, but we are showing all the actions for closing tabs in the context menu:

<img width="386" alt="Screen Shot 2019-06-18 at 1 01 11 PM" src="https://user-images.githubusercontent.com/27600/59715697-4c88d280-91c9-11e9-9f66-5cd8f66a4842.png">

We are probably using too broad of a CSS selector for the context menu items that is causing them to show up for all tabs, rather than just those in the main work area.

**Comment by tgeorgeux** [comment]
In the past, this only displayed one option, I think this behavior is an accidental regression.
