### ISSUE TITLE
Usability of settings editor

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#6623]
At the JLab sprint, we are talking about how to improve the overall usability of the settings editor. Here is where we are at today:

<img width="887" alt="Screen Shot 2019-06-18 at 1 30 23 PM" src="https://user-images.githubusercontent.com/27600/59717695-62989200-91cd-11e9-8598-b44ada810aae.png">

Some of the pain points:

* The table view is not currently useful for anything, and the Tab bar for that and the Raw View is awkward. For this, the consensus here in to remove the table view for 1.0 (time permitting).
* Horizontal space is tight, which causes the comments to wrap. Here, we could explore using a smaller width on the list of extension, and minimizing the line numbers in the second editor.

**Comment by ellisonbg** [comment]
Another point: the bug icon allows the users to toggle the error messages. Shouldn't we always show those and remove the bug icon?

**Comment by tgeorgeux** [comment]
Ringing in on the bug icon. If we want to take it out that solves the problem, but that bug icon is intended to be used to report bugs. I actually saw that in the advanced setting editor and thought it was to be used to report a bug (I expected it to launch a GitHub window or something I guess). 

The icon for debugging in VSCode is a bit more communicative. 
<img width="48" alt="Screen Shot 2019-06-19 at 8 56 20 AM" src="https://user-images.githubusercontent.com/22109376/59782900-ca091d00-9273-11e9-8e25-8d785c53f075.png">

If we decide to leave it in we should update the icon.

**Comment by jasongrout** [comment]
+1 on removing the bug icon.
