### ISSUE TITLE
Unneeded icons backgrounds

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#6624]
Some of the icons we have (launcher and gear) have backgrounds that don't add anything to the experience, and reduce contrast in some settings, such as dark mode:

<img width="216" alt="Screen Shot 2019-06-18 at 1 36 07 PM" src="https://user-images.githubusercontent.com/27600/59718074-316c9180-91ce-11e9-8617-ea27db2666e4.png">

For these icons, a transparent background will help increase the contrast and visual impact.

**Comment by afonit** [comment]
With the changes in the noted merge request, here is what it looks like:
![image](https://user-images.githubusercontent.com/1798497/59863596-02cbf380-9353-11e9-9076-16b080827784.png)
