### ISSUE TITLE
Jupyter lab opens RStudio instead of Firefox

### ISSUE THREAD

**Issue by IgorDouven** [jupyterlab/jupyterlab#6633]
After installing RStudio on Arch, typing `jupyter lab` on the command line starts RStudio instead of my default browser, Firefox. Before I installed RStudio, it worked fine. (Although there was actually a minor issue even thenl: I got many error messages in the terminal about icon sets that it couldn't find. But that didn't prevent Jupyter lab from working.)

**Comment by IgorDouven** [comment]
There just was a KDE update. I restarted the computer, started Jupyter lab again, and now both issues are solved. Don't understand why, but ... great!

**Comment by IgorDouven** [comment]
Strangely enough, today the problem re-appeared. I'm pasting the output I get when I start JupyterLab. Hopefully someone can diagnose the problem.

[I 22:41:01.556 LabApp] The port 8888 is already in use, trying another port.
[W 22:41:01.560 LabApp] JupyterLab server extension not enabled, manually loading...
[I 22:41:01.561 LabApp] Running JupyterLab in core mode
[I 22:41:01.562 LabApp] Running the core application with no additional extensions or settings
[I 22:41:01.562 LabApp] JupyterLab extension loaded from /usr/lib/python3.7/site-packages/jupyterlab
[I 22:41:01.563 LabApp] JupyterLab application directory is /usr/lib/python3.7/site-packages/jupyterlab
[I 22:41:01.564 LabApp] Serving notebooks from local directory: /home/igor
[I 22:41:01.564 LabApp] The Jupyter Notebook is running at:
[I 22:41:01.564 LabApp] http://localhost:8889/?token=f704dcc02f1b10807fb21f4ff40f4252f296c21f8e27b96c
[I 22:41:01.564 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:41:01.621 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///run/user/1000/jupyter/nbserver-4193-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=f704dcc02f1b10807fb21f4ff40f4252f296c21f8e27b96c
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/16/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/16/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/16@2x/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/16@2x/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/22/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/22/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/22@2x/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/22@2x/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/24/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/24/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/24@2x/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/32/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/32/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/32@2x/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/32@2x/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/48/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/48/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/48@2x/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/48@2x/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/64/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/64/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/64@2x/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/64@2x/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/96/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/96/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Surfn/96@2x/notifications/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Surfn/96@2x/panel/"
Icon theme "Paper" not found.
Icon theme "Sardi" not found.
Icon theme "Moka" not found.

**Comment by vidartf** [comment]
Did you try asking RStudio people about this? If so, is there any issue you can cross link to?

**Comment by IgorDouven** [comment]
I haven't -- I was supposing the problem was on the side of JupyterLab. I
searched the issues on the RStudio GitHub page, but couldn't find anything
referring to JupyterLab.

On a positive note, I removed JupyterLab, then reinstalled it, and now
everything works fine again.

Btw, the strange messages about being unable to find icon themes appear as
well when I start JupyterLab in Clear Linux, which I have running in a VM.
But I'm also using KDE there, so perhaps it's related to that desktop
environment.

Op vr 21 jun. 2019 om 13:49 schreef Vidar Tonaas Fauske <
notifications@github.com>:

**Comment by yarikoptic** [comment]
FWIW: in my case, upgraded our computing server to debian buster, and now having similar issue with a plain `ipython notebook` opening url in rstudio.  `xdg-open` opens that url in chromium. happens for multiple users (so not user-specific).

Found
<details>
<summary></summary> 

```shell
$> cat /usr/share/applications/rstudio.desktop
[Desktop Entry]
Exec=/usr/lib/rstudio/bin/rstudio %F
Icon=rstudio
Type=Application
Terminal=false
Name=RStudio
Categories=Development;
MimeType=text/x-r-source;text/x-r;text/x-R;text/x-r-doc;text/x-r-sweave;text/x-r-markdown;text/x-r-html;text/x-r-presentation;application/x-r-data;application/x-r-project;text/x-r-history;text/x-r-profile;text/x-tex;text/x-markdown;text/html;text/css;text/javascript;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;
```
</details>
removed there `text/html;`, ran `update-desktop-database` and that seemed resolved the issue -- now starts the browser (firefox) due to what seems to be a random order choice between `.desktop` specs.

**Comment by alejandrobalderas** [comment]
I just had the same issue with Kubuntu 20.04. I took the easy way out and just uninstall RStudio since I am not using it much anymore

**Comment by jasongrout** [comment]
> removed there `text/html;`, ran `update-desktop-database` and that seemed resolved the issue -- now starts the browser (firefox) due to what seems to be a random order choice between `.desktop` specs.

Thanks for sharing what fixed it!
