### ISSUE TITLE
Jupyter lab defaults to root on Ubuntu

### ISSUE THREAD

**Issue by Nathan-Furnal** [jupyterlab/jupyterlab#6636]
installed miniconda following the documentation, on Linux.  I'm using the JupyterLab but I ran into an issue. Basically my miniconda install is in /root, it follows that everytime I want to launch a notebook it requires root access and I'm not willing to give it.

​

How do you I remedy that issue without destroying my install, can I just move miniconda to /home ?

​

Thanks,

P.S : I'm using Ubuntu 19.04 on a Lenovo thinkpad S2.

**Comment by jasongrout** [comment]
I think you will need to reinstall miniconda.

**Comment by Nathan-Furnal** [comment]
@jasongrout Can't I just meddle with the path and get regular access somehow?

**Comment by vidartf** [comment]
Note that there are clean ways for you to export your current env (which packages are installed), and recreate that in a new env. See the conda docs for details:)
