### ISSUE TITLE
Notebook UX - Cell type selection button in notebook toolbar.

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#6638]
**Describe the bug**
In the notebook toolbar, the cell selection drop down menu doesn't have the correct icons or positioning. The icon is rounded like a 'font awesome' icon instead of sharp like the material version we are using on the adjacent buttons in the toolbar. The position of the icon is also off

**To Reproduce**

1. Open a notebook
2. Look at the toolbar
3. See errors

**Expected behavior**
We should have a single drop-down icon as shown here, that icon should be from the Material Filled icon set, and it should be centered vertically.
![baseline_arrow_drop_down_black_18dp](https://user-images.githubusercontent.com/22109376/59778298-1a2fb180-926b-11e9-8106-6c938890751f.png)

**Screenshots**
See in the below screenshot, the position is 5top 3 bottom instead of 4 top 4 bottom.
<img width="1680" alt="Screen Shot 2019-06-19 at 7 51 39 AM" src="https://user-images.githubusercontent.com/22109376/59777992-7e05aa80-926a-11e9-9c87-0f6132d59bf6.png">

**Comment by tgeorgeux** [comment]
This icon is also off-color in dark mode. 
<img width="730" alt="Screen Shot 2019-06-19 at 8 47 35 AM" src="https://user-images.githubusercontent.com/22109376/59780514-fa9a8800-926e-11e9-9322-8317a962751e.png">

**Comment by ellisonbg** [comment]
Will tackle after #6664

**Comment by jasongrout** [comment]
Fixed by #6672
