### ISSUE TITLE
Status Bar font consistency with the rest of Jupyterlab

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#6643]
**Describe the bug**
The font for the Status Bar is overriding the --jp-ui-font-family with Helvetica Neue. 

**To Reproduce**

1. Look at the status bar
2. Notice it's not the same font as the rest of the UI

**Expected behavior**
Consistent font with the rest of the UI

**Screenshots**
<img width="620" alt="Screen Shot 2019-06-19 at 9 54 17 AM" src="https://user-images.githubusercontent.com/22109376/59785177-05f2b100-9279-11e9-983a-95f383aa5ec8.png">

**Comment by jasongrout** [comment]
You have good eyes! I had trouble reproducing your second step: *notice* it's different :)
