### ISSUE TITLE
Jupyterlab dev watch mode doesn't work 

### ISSUE THREAD

**Issue by AlbertHilb** [jupyterlab/jupyterlab#6649]
After updated to version 1.0.0a8, jupyterlab launched with the command
```
jupyter lab --dev-mode --watch
```
does not work as expected. After each source file change, the system rebuilds, but refreshing the browser doesn't update the app.

My system is:
OS: Ubuntu 18.04
Browser: Firefox 67, Chrome 75
jupyterlab-server: 1.0.0rc0

**Comment by telamonian** [comment]
I've run into the same problem. I think it might've started before `1.0.0a8`. In each individual package, the files in `packages/*/lib` will rebuild and update when the source changes, but somehow the browser isn't "seeing" those changes. I assume there's another step or two of packing in between the files in the `lib` dirs and what the browser picks up. Does anyone know where the files that interact directly with the browser are stored during a `--watch` build?

OS: Mac 10.14.4
Browser: Chrome 74

**Comment by BoPeng** [comment]
Just to confirm that I am seeing the same problem and having to restart the Jupyter server and reload everything is annoying.
