### ISSUE TITLE
jupyterlab not showing widgets

### ISSUE THREAD

**Issue by Koushik95** [jupyterlab/jupyterlab#6659]
Hi, so I'm using a jupyterlab in the form of a docker image and I'm not able to get the display of widgets like the following :- 

I/P :- 
import ipywidgets
ipywidgets.IntSlider()

O/P :- 
A Jupyter Widget

These are my configurations :- 
jupyter lab --version
0.35.4

jupyter nbextension list
Known nbextensions:
  config dir: /home/jupyter/.jupyter/nbconfig
    tree section
      jupyter_tensorboard/tree  enabled
      - Validating: OK
  config dir: /usr/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK

jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: /usr/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK

node -v
v6.16.0

import ipywidgets
ipywidgets.__version__
'7.0.0'

The console in the inspect element of browser shows the following msg :- 
Error: "Object 'jupyter.widget' not found in registry"
@jasongrout  - can you please tell me as to what I should do to correct this?

**Comment by Koushik95** [comment]
@jasongrout - any update on this?

**Comment by vidartf** [comment]
@Koushik95 I would try updating `ipywidgets` first. Either way, I think this issue is likely to get better response if you post it on the ipywidgets repository: https://github.com/jupyter-widgets/ipywidgets

**Comment by jasongrout** [comment]
Closing as apparently resolved, since there was no followup.
