### ISSUE TITLE
Cannot open/display notebooks in the workspace if jupyterlab-manager is installed

### ISSUE THREAD

**Issue by tobiasjj** [jupyterlab/jupyterlab#6681]
Dear all,

double clicks in the file browser on a notebook start the the notebook in the background, but do not open a new editor notebook window in the workspace. Dragging a notebook from the file browser in the workspace does not open a notebook window. Clicking the launcher symbol for a new notebook creates a new one and starts the notebook in the background, but only results in a pop up window saying:
```
Launcher Error
nb.rendermime is undefined
```
Creating a terminal, opening a console, or opening a text file works fine.

Anybody else having this issue?

**To Reproduce**
Install jupyterlab and juypterlab-manager:
```
# pip3 install jupyterlab==1.0.0a10
# jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
Try to open a new/old notebook.

**Expected behavior**
Notebook editor windows should appear in the workspace.

**Desktop:**
- OS: Debian 10
- Browser: firefox 67.0.4 64bit
- JupyterLab 1.0.0a10

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/usr/local/bin
	/usr/bin
	/bin
	/usr/local/games
	/usr/games

sys.path:
	/usr/local/bin
	/usr/lib/python37.zip
	/usr/lib/python3.7
	/usr/lib/python3.7/lib-dynload
	/usr/local/lib/python3.7/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.7.3 (default, Apr  3 2019, 05:39:12) 
	[GCC 8.3.0]

platform.platform():
	Linux-5.0.0-trunk-amd64-x86_64-with-debian-10.0

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/bin/jupyter
	/bin/jupyter

pip list:
	Package             Version    
	------------------- -----------
	alabaster           0.7.8      
	AllanTools          2018.3     
	appdirs             1.4.3      
	asn1crypto          0.24.0     
	asteval             0.9.12     
	astroid             2.1.0      
	atomicwrites        1.3.0      
	attrs               19.1.0     
	Babel               2.6.0      
	backcall            0.1.0      
	beautifulsoup4      4.7.1      
	bleach              3.1.0      
	blosc               1.7.0      
	Bottleneck          1.2.1      
	bqplot              0.11.5     
	branca              0.3.1      
	Brlapi              0.6.7      
	brokenaxes          0.3.1      
	BTrees              4.5.1      
	btrfs               11         
	certifi             2018.8.24  
	cffi                1.12.3     
	cftime              1.0.3.4    
	chardet             3.0.4      
	chrome-gnome-shell  0.0.0      
	Click               7.0        
	click-plugins       1.1.1      
	cligj               0.5.0      
	cloudpickle         0.8.0      
	cryptography        2.6.1      
	cson                0.7        
	cupshelpers         1.0        
	cycler              0.10.0     
	Cython              0.29.10    
	dask                1.0.0+dfsg 
	decorator           4.4.0      
	defusedxml          0.6.0      
	distro              1.3.0      
	distro-info         0.21       
	docutils            0.14       
	entrypoints         0.3        
	Fiona               1.8.6      
	GDAL                2.4.0      
	geopandas           0.5.0      
	gpg                 1.12.0     
	greenlet            0.4.15     
	html5lib            1.0.1      
	httplib2            0.11.3     
	idna                2.6        
	imagej              0.3.1      
	imagesize           1.0.0      
	imglyb              0.3.4      
	importlib-metadata  0.18       
	ipydatawidgets      4.0.0      
	ipykernel           5.1.1      
	ipyleaflet          0.10.5     
	ipympl              0.2.1      
	ipython             7.5.0      
	ipython-genutils    0.2.0      
	ipywidgets          7.4.2      
	isort               4.3.4      
	itk                 5.0.0.post1
	itk-core            5.0.0.post1
	itk-filtering       5.0.0.post1
	itk-io              5.0.0.post1
	itk-numerics        5.0.0.post1
	itk-registration    5.0.0.post1
	itk-segmentation    5.0.0.post1
	itkwidgets          0.16.3     
	jedi                0.14.0     
	jgo                 0.4.0      
	Jinja2              2.10.1     
	jsonschema          3.0.1      
	jupyter-client      5.2.4      
	jupyter-console     5.2.0      
	jupyter-core        4.5.0      
	jupyterlab          1.0.0a10   
	jupyterlab-latex    0.4.1      
	jupyterlab-launcher 0.13.1     
	jupyterlab-server   1.0.0rc0   
	keyring             17.1.1     
	keyrings.alt        3.1.1      
	kiwisolver          1.1.0      
	lazy-object-proxy   1.3.1      
	lmfit               0.9.11     
	locket              0.2.0      
	logilab-common      1.4.2      
	louis               3.8.0      
	lxml                4.3.2      
	Mako                1.0.7      
	MarkupSafe          1.1.1      
	matplotlib          3.1.0      
	mccabe              0.6.1      
	meld                3.20.0     
	mistune             0.8.4      
	more-itertools      7.0.0      
	mpmath              1.1.0      
	msgpack             0.6.1      
	munch               2.3.2      
	nbconvert           5.5.0      
	nbformat            4.4.0      
	neovim              0.3.0      
	neovim-remote       2.1.7      
	netCDF4             1.4.2      
	networkx            2.2        
	nfft                0.1        
	notebook            5.7.8      
	numexpr             2.6.9      
	numpy               1.16.4     
	numpydoc            0.7.0      
	olefile             0.46       
	packaging           19.0       
	pandas              0.24.2     
	pandocfilters       1.4.2      
	parso               0.5.0      
	partd               0.3.9      
	pdfarranger         1.1.1      
	persistent          4.5.0      
	pexpect             4.7.0      
	pickleshare         0.7.5      
	Pillow              5.4.1      
	Pint                0.9        
	pip                 18.1       
	pkginfo             1.4.2      
	pluggy              0.12.0     
	prometheus-client   0.7.1      
	prompt-toolkit      2.0.9      
	psutil              5.6.3      
	ptyprocess          0.6.0      
	py                  1.8.0      
	pycairo             1.16.2     
	pycodestyle         2.4.0      
	pycparser           2.19       
	pycrypto            2.6.1      
	pycups              1.9.73     
	pycurl              7.43.0.2   
	pyflakes            2.0.0      
	Pygments            2.4.2      
	PyGObject           3.30.4     
	pyjnius             1.2.0      
	pylint              2.2.2      
	pymol               2.2.0      
	pynvim              0.3.2      
	PyOpenGL            3.1.0      
	pyotic              0.12.15    
	pyparsing           2.4.0      
	PyPDF2              1.26.0     
	pyproj              2.2.0      
	pyrsistent          0.15.2     
	PySimpleSOAP        1.16.2     
	pysmbc              1.0.15.6   
	PySocks             1.6.8      
	pytest              4.6.3      
	python-apt          1.8.4      
	python-dateutil     2.8.0      
	python-debian       0.1.35     
	python-debianbts    2.8.2      
	pytz                2019.1     
	PyWavelets          0.5.1      
	pyxdg               0.25       
	PyYAML              5.1.1      
	pyzmq               18.0.1     
	QtAwesome           0.4.4      
	qtconsole           4.3.1      
	QtPy                1.3.1      
	readme-renderer     24.0       
	reportbug           7.5.2      
	reportlab           3.5.13     
	requests            2.21.0     
	requests-toolbelt   0.8.0      
	roman               2.0.0      
	rope                0.10.5     
	scikit-image        0.14.2     
	scipy               1.3.0      
	scour               0.37       
	scyjava             0.2.2      
	SecretStorage       2.3.1      
	Send2Trash          1.5.0      
	setuptools          41.0.1     
	Shapely             1.6.4.post2
	simplegeneric       0.8.1      
	six                 1.12.0     
	soupsieve           1.8        
	speg                0.3        
	Sphinx              1.8.4      
	spyder              3.3.3      
	spyder-kernels      0.2.4      
	svgwrite            1.2.1      
	sympy               1.3        
	tables              3.4.4      
	terminado           0.8.2      
	testpath            0.4.2      
	tifffile            2018.11.28 
	toolz               0.9.0      
	torbrowser-launcher 0.3.1      
	tornado             5.1.1      
	tqdm                4.28.1     
	trackpy             0.4.1      
	traitlets           4.3.2      
	traittypes          0.2.1      
	transaction         2.4.0      
	twine               1.13.0     
	unattended-upgrades 0.1        
	uncertainties       3.0.2      
	urllib3             1.24.1     
	wcwidth             0.1.7      
	webencodings        0.5.1      
	wheel               0.32.3     
	widgetsnbextension  3.4.2      
	wrapt               1.10.11    
	xarray              0.12.1     
	zc.lockfile         1.4        
	ZConfig             3.4.0      
	zipp                0.5.1      
	ZODB                5.5.1      
	zodbpickle          1.0.4      
	zope.interface      4.6.0      
	zstandard           0.11.1

</pre>
</details>

<details><summary>Command Line Output clicking the launcher</summary>
<pre>
[D 12:25:48.335 LabApp] Accepting token-authenticated connection from 127.0.0.1
[I 12:25:48.336 LabApp] Creating new notebook in /
[D 12:25:48.337 LabApp] Saving /home/tobias/Untitled6.ipynb
[D 12:25:48.403 LabApp] 201 POST /api/contents/?1561112748313 (127.0.0.1) 68.08ms
[D 12:25:48.426 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:25:48.428 LabApp] 200 GET /api/contents/Untitled6.ipynb?content=0&1561112748421 (127.0.0.1) 1.74ms
[D 12:25:48.478 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:25:48.502 LabApp] 200 GET /api/contents/?content=1&1561112748431 (127.0.0.1) 24.30ms
[D 12:25:48.526 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:25:48.554 LabApp] 200 GET /api/contents/Untitled6.ipynb?type=notebook&content=1&1561112748518 (127.0.0.1) 28.08ms
[D 12:25:48.808 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:25:48.808 LabApp] 200 GET /api/contents/Untitled6.ipynb/checkpoints?1561112748801 (127.0.0.1) 1.35ms
[D 12:25:48.821 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:25:48.828 LabApp] Starting kernel: ['/usr/bin/python3', '-m', 'ipykernel_launcher', '-f', '/home/tobias/.local/share/jupyter/runtime/kernel-3d70fea0-8f11-48ad-87c2-a9eef96d2aa2.json']
[D 12:25:48.849 LabApp] Connecting to: tcp://127.0.0.1:36825
[D 12:25:48.853 LabApp] Connecting to: tcp://127.0.0.1:52983
[I 12:25:48.857 LabApp] Kernel started: 3d70fea0-8f11-48ad-87c2-a9eef96d2aa2
[D 12:25:48.857 LabApp] Kernel args: {'kernel_name': 'python3', 'cwd': '/home/tobias'}
[D 12:25:48.872 LabApp] 201 POST /api/sessions?1561112748816 (127.0.0.1) 50.70ms
[D 12:25:48.941 LabApp] Initializing websocket connection /api/kernels/3d70fea0-8f11-48ad-87c2-a9eef96d2aa2/channels
[D 12:25:48.943 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:25:48.944 LabApp] Requesting kernel info from 3d70fea0-8f11-48ad-87c2-a9eef96d2aa2
[D 12:25:48.945 LabApp] Connecting to: tcp://127.0.0.1:52333
[D 12:25:49.071 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:25:49.074 LabApp] 204 PUT /lab/api/workspaces/lab?1561112749042 (127.0.0.1) 5.73ms
[D 12:25:50.183 LabApp] activity on 3d70fea0-8f11-48ad-87c2-a9eef96d2aa2: status
[D 12:25:50.184 LabApp] activity on 3d70fea0-8f11-48ad-87c2-a9eef96d2aa2: status
[D 12:25:50.185 LabApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.1', 'implementation': 'ipython', 'implementation_version': '7.5.0', 'language_info': {'name': 'python', 'version': '3.7.3', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': "Python 3.7.3 (default, Apr  3 2019, 05:39:12) \nType 'copyright', 'credits' or 'license' for more information\nIPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.\n", 'help_links': [{'text': 'Python Reference', 'url': 'https://docs.python.org/3.7'}, {'text': 'IPython Reference', 'url': 'https://ipython.org/documentation.html'}, {'text': 'NumPy Reference', 'url': 'https://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy Reference', 'url': 'https://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib Reference', 'url': 'https://matplotlib.org/contents.html'}, {'text': 'SymPy Reference', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas Reference', 'url': 'https://pandas.pydata.org/pandas-docs/stable/'}]}
[I 12:25:50.186 LabApp] Adapting to protocol v5.1 for kernel 3d70fea0-8f11-48ad-87c2-a9eef96d2aa2
[D 12:25:50.187 LabApp] activity on 3d70fea0-8f11-48ad-87c2-a9eef96d2aa2: status
[D 12:25:50.188 LabApp] 101 GET /api/kernels/3d70fea0-8f11-48ad-87c2-a9eef96d2aa2/channels?session_id=b97f69d2-7b4f-4dad-b9e6-1b7cbd4d232e&token=75a7dd5d33c614f5f42327d34365a2add412036f0dbf3085 (127.0.0.1) 1247.00ms
[D 12:25:50.188 LabApp] Opening websocket /api/kernels/3d70fea0-8f11-48ad-87c2-a9eef96d2aa2/channels
[D 12:25:50.188 LabApp] Getting buffer for 3d70fea0-8f11-48ad-87c2-a9eef96d2aa2
[D 12:25:50.188 LabApp] Connecting to: tcp://127.0.0.1:52333
[D 12:25:50.188 LabApp] Connecting to: tcp://127.0.0.1:52983
[D 12:25:50.189 LabApp] Connecting to: tcp://127.0.0.1:41793
[D 12:25:50.194 LabApp] activity on 3d70fea0-8f11-48ad-87c2-a9eef96d2aa2: status
[D 12:25:50.194 LabApp] activity on 3d70fea0-8f11-48ad-87c2-a9eef96d2aa2: status
</pre>
</details>

<details><summary>Command Line Output double clicking a notebook in the file browser</summary>
<pre>
[D 12:23:42.605 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:23:42.630 LabApp] 200 GET /api/contents/Untitled.ipynb?type=notebook&content=1&1561112622598 (127.0.0.1) 25.28ms
[D 12:23:42.736 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:23:42.737 LabApp] 200 GET /api/contents/Untitled.ipynb/checkpoints?1561112622731 (127.0.0.1) 1.21ms
[D 12:23:42.764 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:23:42.767 LabApp] Starting kernel: ['/usr/bin/python3', '-m', 'ipykernel_launcher', '-f', '/home/tobias/.local/share/jupyter/runtime/kernel-93bf5548-6018-491e-b83c-4139121341da.json']
[D 12:23:42.772 LabApp] Connecting to: tcp://127.0.0.1:42653
[D 12:23:42.772 LabApp] Connecting to: tcp://127.0.0.1:44081
[I 12:23:42.773 LabApp] Kernel started: 93bf5548-6018-491e-b83c-4139121341da
[D 12:23:42.774 LabApp] Kernel args: {'kernel_name': 'python3', 'cwd': '/home/tobias'}
[D 12:23:42.774 LabApp] 201 POST /api/sessions?1561112622759 (127.0.0.1) 10.30ms
[D 12:23:42.791 LabApp] Initializing websocket connection /api/kernels/93bf5548-6018-491e-b83c-4139121341da/channels
[D 12:23:42.803 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:23:42.807 LabApp] Requesting kernel info from 93bf5548-6018-491e-b83c-4139121341da
[D 12:23:42.807 LabApp] Connecting to: tcp://127.0.0.1:59031
[D 12:23:43.108 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:23:43.109 LabApp] 204 PUT /lab/api/workspaces/lab?1561112623101 (127.0.0.1) 1.30ms
[D 12:23:43.459 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:23:43.459 LabApp] 200 GET /api/sessions?1561112623451 (127.0.0.1) 1.14ms
[D 12:23:43.573 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:23:43.574 LabApp] 200 GET /api/terminals?1561112623550 (127.0.0.1) 1.19ms
[D 12:23:43.607 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 12:23:43.614 LabApp] 200 GET /api/contents/?content=1&1561112623584 (127.0.0.1) 7.36ms
[D 12:23:44.129 LabApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.1', 'implementation': 'ipython', 'implementation_version': '7.5.0', 'language_info': {'name': 'python', 'version': '3.7.3', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': "Python 3.7.3 (default, Apr  3 2019, 05:39:12) \nType 'copyright', 'credits' or 'license' for more information\nIPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.\n", 'help_links': [{'text': 'Python Reference', 'url': 'https://docs.python.org/3.7'}, {'text': 'IPython Reference', 'url': 'https://ipython.org/documentation.html'}, {'text': 'NumPy Reference', 'url': 'https://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy Reference', 'url': 'https://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib Reference', 'url': 'https://matplotlib.org/contents.html'}, {'text': 'SymPy Reference', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas Reference', 'url': 'https://pandas.pydata.org/pandas-docs/stable/'}]}
[I 12:23:44.129 LabApp] Adapting to protocol v5.1 for kernel 93bf5548-6018-491e-b83c-4139121341da
[D 12:23:44.130 LabApp] 101 GET /api/kernels/93bf5548-6018-491e-b83c-4139121341da/channels?session_id=551b5526-0782-4dc5-a46e-fc4413928d3e&token=75a7dd5d33c614f5f42327d34365a2add412036f0dbf3085 (127.0.0.1) 1344.88ms
[D 12:23:44.130 LabApp] Opening websocket /api/kernels/93bf5548-6018-491e-b83c-4139121341da/channels
[D 12:23:44.130 LabApp] Getting buffer for 93bf5548-6018-491e-b83c-4139121341da
[D 12:23:44.130 LabApp] Connecting to: tcp://127.0.0.1:59031
[D 12:23:44.131 LabApp] Connecting to: tcp://127.0.0.1:44081
[D 12:23:44.131 LabApp] Connecting to: tcp://127.0.0.1:52715
</pre>
</details>

**Comment by jasongrout** [comment]
A fresh install of jlab 1.0a10 works fine for me opening and running new and old notebooks.

**Comment by tobiasjj** [comment]
OK, a clean install works. The issue appears to be related to juypterlab-manager.
````
# pip3 install jupyterlab==1.0.0a10
# jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

**Comment by tobiasjj** [comment]
XRef: jupyter-widgets/ipywidgets#2450

**Comment by tobiasjj** [comment]
XRef: jupyter-widgets/ipywidgets#2450

**Comment by tobiasjj** [comment]
Most likely the issue is that per default jupyterlab-manager version 0.39.1 gets installed. Greater versions up to 0.41 throw a "Conflicting Dependencies" error upon install. Since I did not manage to build the git version, I guess it will work with the newest version of jupyterlab-manager?!

**Comment by jasongrout** [comment]
ipywidgets has not been updated to the latest prerelease. Give us a bit of time to update it.
