### ISSUE TITLE
Toolbar buttons fire on right-click down

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#6691]
When using the toolbar buttons, I notice that they fire their actions on:
- Right-click events (possibly also other mouse buttons?)
- Mouse down

Both of which I would consider unexpected, and annoying (right click should give context menu, and I should be able to abort my action mid-click by dragging the mouse off the button before releasing).

**Comment by jasongrout** [comment]
Agreed about right click. We investigated the mousedown vs mouseup behavior, and it turns out that lots of buttons in toolbars actually take action on mousedown.

**Comment by gnestor** [comment]
Reference: https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/toolbar.tsx#L462

Is there any reason why we can't use mouseup?

**Comment by vidartf** [comment]
After Jason's comment, I remember there having been a discussion about this (with AlbertHilb I think). If somebody knows where that was and can crossref it, that would be appreciated :)

**Comment by gnestor** [comment]
Related issues: 
https://github.com/jupyterlab/jupyterlab/issues/6077
https://github.com/jupyterlab/jupyterlab/issues/5757

**Comment by gnestor** [comment]
@AlbertHilb To fix this, we could use mouseup vs. mousedown. Do you have any objections to that?

**Comment by jasongrout** [comment]
There are ux questions around using mouse up vs mouse down. @ellisonbg and I looked at a few existing patterns, and there was definitely precedence for mouse down.

**Comment by AlbertHilb** [comment]
The default browser action on `mousedown` event is to move the focus to the event target (in our case to the button). On the other side, preventing the default action on `mousedown` stops `click` and `mouseup` events from firing. So just binding action to `mouseup`, without other adjustments, causes the editor to blur when buttons are pressed.

**Comment by vidartf** [comment]
@AlbertHilb Thanks for the detailed explanation. Losing editor focus seems like a good enough motivation for me. Maybe we should include a comment next to the event binding in the code to prevent this from coming up again 😅

**Comment by ellisonbg** [comment]
We have wrestled previously with actions (toolbar buttons, menu items) that blur editor focus. Interacting with elements outside the editor should in fact blur the editor as those other elements should receive focus. Disrupting that will only cause accessibility problems and weird side effects. 

A separate question is whether we should trigger on up/down. I don't remember off hand which UI toolkits handle it which way, but it was not at all consistent between them, or between keyboard and mouse.
