### ISSUE TITLE
Document how to ship extensions

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6693]
- Point to examples of extensions that have companion package metadata and ship both the lab extension and a server extension
- Point to examples of shipped lab extensions
- Document why the extension is just a single package that has to be installed and built by the user.

**Comment by saulshanabrook** [comment]
Sometimes you are developing a local extension that also depends on another JS package you are working on. You would like to try out both local versions without having to publish either of them. You can do this if you have your extension package have a `peerDependency` on the other JS package, and install each of them with `jupyter extension link <path to dir>`.

**Comment by vidartf** [comment]
@saulshanabrook In nbdime I normally `jupyter labextension link` my library package, and `jupyter labextension install` my labextension package (which has a the library as a dependency). So for clarification, I guess it is any kind of run-time dependency (direct, or peer)?

**Comment by blink1073** [comment]
Link and install are equivalent for local folders. Yeah, I was confused that a `peerDependency` was necessary.

**Comment by telamonian** [comment]
One question I've had for a while about shipping extensions: is it possible to release different versions of a jlab-extension on npm that correspond to the user's jlab version? In other words, is it possible to release one version of an extension that works with `.35.x` and another that works with `1.0.x`? 

Probably the same question: will the extension manager automatically grab the latest compatible version of an extension from npm? Or will it just grab the latest version and then complain about version compatibility?

**Comment by jtpio** [comment]
> Probably the same question: will the extension manager automatically grab the latest compatible version of an extension from npm? Or will it just grab the latest version and then complain about version compatibility?

This should already be the case to some extent. For example when install the `@jupyter-widgets/jupyterlab-manager` extension for JupyterLab 0.35.6 with `jupyter labextension install @jupyter-widgets/jupyterlab-manager`:

```
...
jupyter-widgets-jupyterlab-manager-0.41.0.tgz
Incompatible extension:

"@jupyter-widgets/jupyterlab-manager@0.41.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        1.0.0-alpha.8    @jupyterlab/application
>=0.19.2 <0.20.0        1.0.0-alpha.9    @jupyterlab/notebook
>=0.19.1 <0.20.0        1.0.0-alpha.8    @jupyterlab/rendermime

Found compatible version: 0.38.1
...
```

**Comment by blink1073** [comment]
Right, we had considered an "engine" field similar to the top level one in package.json, and instead settled on Denver on the JS packages

**Comment by telamonian** [comment]
Okay, so I guess the trick is to set very narrow ranges for acceptable versions? Otherwise it seems like you'd have to be *very* careful about the order in which you publish the different versions, and that you might end up having to publish all versions every time you need to make a small fix to any single one.

**Comment by blink1073** [comment]
I think the default `^` used by `npm` is sufficient in this case.  Once all of our packages are 1.0+, we'll be able to put out minor releases and still allow `^` to work.
