### ISSUE TITLE
Extension install failures can sometimes break JupyterLab

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#6703]
**Describe the bug**
Attempting to install a `labextension` that breaks the `webpack` portion of JupyterLab's build sequence gets `jupyterlab` stuck in a broken state.

`jupyter lab clean` does not recover this state but uninstalling the offending extension does.

A side-effect of this bug is that it hinders extension development.

**To Reproduce**

```bash
git clone https://github.com/afshin/breaks-jupyterlab-1.0.0rc0.git
cd breaks-jupyterlab-1.0.0rc0
jlpm run build
jupyter labextension install
```
The installation of the extension will fail. When you next run `jupyter lab` you will be prompted to rebuild. The rebuild fails in the `webpack` stage.

**Expected behavior**
If an extension fails to install, it should not create any side-effects in JupyterLab going forward.

**Additional context**
If you get stuck in this state because you installed the extension in the snippet above, here is how to recover:
```bash
jupyter labextension uninstall breaks-jupyterlab-1.0.0rc0
```

**Nota Bene**
The underlying bug is that the extension is failing to export its `foo.svg` file because SVG files are not included in the `files` attribute of `package.json`. The reason `jlpm run build` works is because the file exists locally but never ships with the tarball when JupyterLab install it.

cc: @telamonian, who has been looking at `webpack` related issues here: https://github.com/jupyterlab/jupyterlab/issues/6698

**Comment by vidartf** [comment]
So, if I understand it correctly: `jupyter labextension install foo`, should not add `foo` to the permanent list of extensions if the build fails. If so, here are some points of consideration:
- For `jupyter labextension install foo bar` failing, I assume neither `foo` nor `bar` should be added.
- For `jupyter labextension install foo --no-build && jupyter lab build`, `foo` will get installed, even if it breaks the build.
- For `jupyter labextension install foo --no-build && jupyter labextension install bar`, if `foo` breaks the build, the consequence will be that `bar` does not get installed.

So, while I agree with the idea (don't install broken extensions), I foresee some challenges 😅

**Comment by afshin** [comment]
> For `jupyter labextension install foo bar` failing, I assume neither `foo` nor `bar` should be added.

I don't think this *has* to be the case. Just whatever we decide needs to be documented.

> For `jupyter labextension install foo --no-build && jupyter lab build`, `foo` will get installed, even if it breaks the build.

Yes, I suppose that's right. I don't see how we can change this behavior.

> For `jupyter labextension install foo --no-build && jupyter labextension install bar`, if `foo` breaks the build, the consequence will be that `bar` does not get installed.

Yes that's accurate. Perhaps `--no-build` is an anti-pattern?

**Comment by blink1073** [comment]
I think `--no-build` is still a valid optimistic thing that we want to allow.  We have some checks that run during the install phase, but we're never going to catch everything.  If we didn't have the `--no-build` option, you'd end up installing all of your extensions in one command line invocation in a docker script for example, and you'd be in essentially the same boat.

**Comment by jtpio** [comment]
Closing as the original post was about managing extensions with the `jupyter labextension install` command, which has now been deprecated in favor of installing extensions with `pip` and `conda` / `mamba`.

Feel free to re-open if it is still relevant or if you would like to discuss this more, thanks!
