### ISSUE TITLE
Review yarn.lock updates

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6710]
#6707 changed a lot of things in yarn.lock. I thought we were basically locking things down now that we are in RC except for critical fixes or things like documentation or other PRs that don't affect code.

Can we review those yarn.lock changes to make sure we want to make so many changes in the RC phase of our release?

If we do want to make that many changes at this stage, I think our policy has been to deduplicate the yarn.lock using yarn-deduplicate - we may want to do that too.

CC @gnestor.

**Comment by vidartf** [comment]
For that PR, I am only seeing a small diff :
![+62 lines / -1 line](https://user-images.githubusercontent.com/510760/60176541-803dab00-980e-11e9-9d93-eb586d1f0eaa.png)

**Comment by jasongrout** [comment]
Ah, I see what the issue is. I was using VS code to look at the merge commit, and for some reason my vs code is showing massive changes to the yarn.lock that stretch back to our big updates from a few months ago. I'm not sure what's going on with vs code's git extension, but it seems that the problem is not in #6707. Sorry, I withdraw my objection.
