### ISSUE TITLE
Appending a new cell from a widget

### ISSUE THREAD

**Issue by flynnplatt** [jupyterlab/jupyterlab#6717]
I'm creating a custom ipywidget following this guide (https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Custom.html) starting from this cookiecutter (https://github.com/jupyter-widgets/widget-ts-cookiecutter).

I would like to be able to append a new cell to the notebook when a user clicks on a button within the widget. I have a function firing in my `DomWidgetView` instance when the button is clicked but I do not know how to get a reference to the notebook or the current cell from the widget so I can't append a new cell.

My code is here:
https://github.com/MAAP-Project/maap-jupyter-ide/blob/283ab5ae5fbf79ce6323c250a8967f14884f982b/ipycmc/src/widget.ts#L165

So how do I get a reference to a `INotebookTracker` or `NotebookPanel` from this widget view?

**Comment by jasongrout** [comment]
You would need to require it in your jlab extension activation at https://github.com/MAAP-Project/maap-jupyter-ide/blob/283ab5ae5fbf79ce6323c250a8967f14884f982b/ipycmc/src/plugin.ts#L29
