### ISSUE TITLE
Present contextmenu on left click

### ISSUE THREAD

**Issue by felipebmendes** [jupyterlab/jupyterlab#6721]
Hey guys,

I'm developing a jupyter extension and I want to know how I can present the **contextmenu** on left click.

Thanks in advance.

**Comment by telamonian** [comment]
Here's the basic way to do it:

```
node.addEventListener('click', (event: MouseEvent) => {
  event.preventDefault();
  app.contextMenu.open(event);
});
```

where `node` is the DOM element corresponding to where you want the left click action to work, and `app` is the main Jupyterlab application widget. It'll probably need some further tweaks to do exactly what you want (the 'click' event will fire on either left or right click), so here's some further references:

https://developer.mozilla.org/en-US/docs/Web/API/EventListener
https://developer.mozilla.org/en-US/docs/Web/Events#Mouse_events
https://stackoverflow.com/a/3944291/425458

**Comment by felipebmendes** [comment]
Awesome, it worked exactly as I expected.
Thank you very much, @telamonian.
