### ISSUE TITLE
Firefox browser Version 67.0.4 (64-bit) not supporting jupyterlab

### ISSUE THREAD

**Issue by DipadityaDas** [jupyterlab/jupyterlab#6725]
Hi! Thanks for using JupyterLab.

If you are reporting an issue with JupyterLab, please use the [GitHub issue](https://github.com/jupyterlab/jupyterlab/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

The JupyterLab team and Project Jupyter value our community, and JupyterLab
follows the Jupyter [Community Guides](https://jupyter.readthedocs.io/en/latest/community/content-community.html).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser [e.g. chrome 69.0, firefox 62.0]
- JupyterLab [e.g. 0.34.2]

**Additional context**

If available, please include the following details:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser console here.
</pre>
</details>

**Comment by manycoding** [comment]
Hi @DipadityaDas, first update to the latest JupyterLab version and see if it's reproducible.

Your report doesn't make much sense to me - could you clear template text and put only the necessary information? Screenshosts can help.

I have the same Firefox version on Mac, it works.

**Comment by DipadityaDas** [comment]
After starting jupyter lab in cmd, it does not show anything in my default browser ,i.e., Firefox
![Screenshot (62)](https://user-images.githubusercontent.com/32407694/60425752-cb4c2980-9c25-11e9-9eb5-13fb395fcbc9.png)
![Screenshot (61)](https://user-images.githubusercontent.com/32407694/60425753-cd15ed00-9c25-11e9-8f1c-510a130a4ba3.png)

**Comment by vidartf** [comment]
@DipadityaDas Is there any output in the browser console? (typically Ctrl + shift + J,  or sometimes F12)

**Comment by DipadityaDas** [comment]
The problem is resolved . I just clear the cache of the browser. As per my knowledge I updated recently due to which this problem happened in the first place.
So, if any blank Screen appears in the browser, I think we should clean the cache.

**Comment by vidartf** [comment]
Thanks for reporting back with the solution!
