### ISSUE TITLE
Access to parent directories with ContentsManager

### ISSUE THREAD

**Issue by lukecelestino** [jupyterlab/jupyterlab#6728]
Hey guys,

I'm developing a jupyter extension and I'm trying to read a file's content, which is stored outside the home directory, like this:

```
const contents = new ContentsManager();
let filePath = '/opt/test/';
         contents.get(filePath + 'test.json').then(value => {
           console.log(value.content);
         });
```

However, I can't access files in directories that are parents of the server's working directory.

Does anyone know how to do it?  

Thank you.

**Comment by jasongrout** [comment]
The notebook server contents manager does not allow this. You could create a server extension, or perhaps a symbolic link would work?

**Comment by lukecelestino** [comment]
Oh ok, got it.

Could you please clarify what you mean by symbolic link?

Thanks

**Comment by jasongrout** [comment]
> Could you please clarify what you mean by symbolic link?

For example: https://en.wikipedia.org/wiki/Ln_(Unix)
