### ISSUE TITLE
JupyterLab - 403 PATCH error

### ISSUE THREAD

**Issue by YoussefElkilaney** [jupyterlab/jupyterlab#6736]
Hello,

I ran the server, as usual, changed path to some directory and then opened another tab, on same port, working on another path, when it lagged for a while, which is 190s I suppose, then opened but was empty. Below, a few lines from log, server console, has a time frame aligns with that path 'Date Modified', which was 3 minutes ago, it made sense.
<br><br>
```
[W 11:37:52.182 LabApp] 403 PATCH /api/contents/fourth%20year?1561800881604 (::1): Permission denied: fourth year/Graducation Project                                  
[W 11:37:52.182 LabApp] Permission denied: fourth year/Graducation Project                                                                                             
[W 11:37:52.183 LabApp] 403 PATCH /api/contents/fourth%20year?1561800881604 (::1) 190570.95ms referer=http://localhost:8889/lab/workspaces/auto-9tree/Dev/Include      
```
<br>
I just want to know what happened. Folder is gone, I searched for it in Recycle bin, searched in Windows Event Log for file deletions operation but nothing related, and used a utility for same purpose. Nothing worked to know how it's deleted.

**Comment by michael-burt** [comment]
I am having a related error. I am running JupyterLab behind a reverse proxy, and almost everything works. When I try to rename a folder, I get a 403 Forbidden error. I see that this is also a PATCH request to the server in the logs.

**Comment by jasongrout** [comment]
> I just want to know what happened.

That patch request is for renaming a directory: http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml#/contents/patch_api_contents__path_

**Comment by jasongrout** [comment]
Closing as answered, but feel free to comment if you'd like to continue this discussion, or open a new issue to start a new one.
