### ISSUE TITLE
Standardize registry used in dev mode

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6737]
We saw a problem during the release process yesterday where this [command](https://github.com/jupyterlab/jupyterlab/blob/e2fd4c8841a7393f9131fb6b6e8252864a8bd351/buildutils/src/publish.ts#L44) was using the yarnpkg registry instead of the registry that lerna was using.  

Note that lerna is using `npm` for all of its publish/tag related commands and yarn has deprecated https://registry.yarnpkg.org in favor of https://registry.npmjs.org: https://github.com/yarnpkg/yarn/issues/5891.

I think we should make sure we're using https://registry.npmjs.org consistently in the repo: 
- For yarn.lock files
- For lerna commands (already the default)
- For any npm command that we run

We should also audit that we're using npm and not yarn/jlpm for any commands that write to the registry.

**Comment by blink1073** [comment]
cf https://github.com/lerna/lerna/issues/1560#issuecomment-412561622

**Comment by jasongrout** [comment]
@blink1073 says this is resolved.
