### ISSUE TITLE
Better handling of linked packages

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6738]
@SylvainCorlay reported this while working on the ipywidgets upgrade.  I'm going to come up with a repro, but the general idea is:

- make an extension that depends on a published library
- check out that library locally
- bump the version number 
- run jupyter labextension link

- change directories back to the extension 
- run jupyter labextension link

At this point, jupyter lab complains that it cannot find a published version of the linked dependency.

**Comment by vidartf** [comment]
Does it matter if the extension in question has an `npm/yarn link` to the library set up?

**Comment by blink1073** [comment]
We tried that, it didn't work
