### ISSUE TITLE
Scrollbars styling

### ISSUE THREAD

**Issue by timhoffm** [jupyterlab/jupyterlab#6739]
**Describe the bug**

Scrollbars in jupyterlab are currently taken from the browser as is,  which corresponds to the OS scrollbars.

This is in particular not nice when the OS has a light color scheme but jupyterlab is dark, because the light scrollbars stand out significantly:

![image](https://user-images.githubusercontent.com/2836374/60388866-f1ec5200-9ab7-11e9-9bdf-6e74a126a773.png)

**Expected behavior**

The jupyterlab theme should style the scrollbars as well. This has recently become possible via CSS (https://caniuse.com/#search=scrollbar-color).

Firefox needs a `scrollbar-color` tag: https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color.
All ll other browsers can be customized via a `::webkit-scrollbar` selector: https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar.

**Comment by telamonian** [comment]
This is already implemented, just turned off by default. Just go to *Settings Editor -> Theme* and turn on the `theme-scrollbars` option.

**Comment by timhoffm** [comment]
Thanks!
