### ISSUE TITLE
The vim key bindings in text editor doesn't work in JupyterLab 1.0.0

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#6744]
**Describe the bug**
The Vim key bindings in the text editor doesn't work in JupyterLab 1.0.0.

**To Reproduce**
1. Pull the Docker image [dclong/jupyterlab](https://github.com/dclong/docker-jupyterlab) using the command `docker pull dclong/jupyterlab`.
2. Start a container of [dclong/jupyterlab](https://github.com/dclong/docker-jupyterlab) using the following commnd on Mac or Linux.
```
docker run -it \
    --log-opt max-size=50m \
    -p 8888:8888 \
    -e DOCKER_USER=`id -un` \
    -e DOCKER_USER_ID=`id -u` \
    -e DOCKER_PASSWORD=`id -un` \
    -e DOCKER_GROUP_ID=`id -g` \
    -v `pwd`:/workdir \
    -v `dirname $HOME`:/home_host \
    dclong/jupyterlab
```
3. Copy the token from the terminal and login to the JupyterLab server. 
2. Open a Text editor from the Launcher. 
3. Go to menu: "Settings -> Text Editor Key Map" and select `Vim`.
4. Play with the Text editor and you will find that the Vim key bindings doesn't work. 

**Expected behavior**
The Vim key bindings for the text editor should work without issues.

**Screenshots**
No applicable as it is hard to screenshot to demonstrate failure of Vim keybindings.

**Desktop (please complete the following information):**

- OS: Ubuntu 18.10 (via Docker)
- Browser: Chrome 75 on Mac Mojave (10.14.5)
- JupyterLab: 1.0.0

**Additional context**

<details><summary>Troubleshoot Output</summary>
<pre>
$ jupyter troubleshoot
$PATH:
        /usr/local/bin
        /usr/bin
        /bin
        /usr/local/games
        /usr/games

sys.path:
        /usr/local/bin
        /usr/lib/python36.zip
        /usr/lib/python3.6
        /usr/lib/python3.6/lib-dynload
        /usr/local/lib/python3.6/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.6.8 (default, Apr  9 2019, 04:59:38) 
        [GCC 8.3.0]

platform.platform():
        Linux-4.9.125-linuxkit-x86_64-with-Ubuntu-18.10-cosmic

which -a jupyter:
        /usr/local/bin/jupyter

pip list:
        Package             Version    
        ------------------- -----------
        asn1crypto          0.24.0     
        attrs               19.1.0     
        backcall            0.1.0      
        bleach              3.1.0      
        certifi             2019.6.16  
        chardet             3.0.4      
        colorama            0.4.1      
        command-not-found   0.3        
        cryptography        2.3        
        decorator           4.4.0      
        defusedxml          0.6.0      
        entrypoints         0.2.3.post3
        gitdb2              2.0.5      
        GitPython           2.1.11     
        greenlet            0.4.13     
        idna                2.6        
        ipykernel           5.1.1      
        ipython             7.6.0      
        ipython-genutils    0.2.0      
        ipywidgets          7.4.2      
        jedi                0.14.0     
        Jinja2              2.10.1     
        json5               0.8.4      
        jsonschema          3.0.1      
        jupyter             1.0.0      
        jupyter-client      5.2.4      
        jupyter-console     6.0.0      
        jupyter-core        4.5.0      
        jupyterlab          1.0.0      
        jupyterlab-server   1.0.0      
        keyring             15.1.0     
        keyrings.alt        3.1        
        MarkupSafe          1.1.1      
        mistune             0.8.4      
        msgpack             0.5.6      
        nbconvert           5.5.0      
        nbdime              1.0.6      
        nbformat            4.4.0      
        neovim              0.2.6      
        notebook            5.7.8      
        pandocfilters       1.4.2      
        parso               0.5.0      
        pexpect             4.7.0      
        pickleshare         0.7.5      
        pip                 19.1.1     
        prometheus-client   0.7.1      
        prompt-toolkit      2.0.9      
        ptyprocess          0.6.0      
        pycrypto            2.6.1      
        Pygments            2.4.2      
        PyGObject           3.30.1     
        pyrsistent          0.15.2     
        python-apt          1.7.1      
        python-dateutil     2.8.0      
        pyxdg               0.25       
        pyzmq               18.0.2     
        qtconsole           4.5.1      
        requests            2.22.0     
        SecretStorage       2.3.1      
        Send2Trash          1.5.0      
        setuptools          40.2.0     
        six                 1.11.0     
        smmap2              2.0.5      
        terminado           0.8.2      
        testpath            0.4.2      
        tornado             6.0.3      
        traitlets           4.3.2      
        unattended-upgrades 0.1        
        urllib3             1.25.3     
        wcwidth             0.1.7      
        webencodings        0.5.1      
        wheel               0.30.0     
        widgetsnbextension  3.4.2
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 11:43:41.459 LabApp] Writing notebook server cookie secret to /home/dclong/.local/share/jupyter/runtime/notebook_cookie_secret
[I 11:43:41.609 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 11:43:41.610 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[W 11:43:41.712 LabApp] JupyterLab server extension not enabled, manually loading...
[I 11:43:41.720 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 11:43:41.720 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 11:43:41.722 LabApp] Serving notebooks from local directory: /workdir
[I 11:43:41.722 LabApp] The Jupyter Notebook is running at:
[I 11:43:41.722 LabApp] http://(351db77f4635 or 127.0.0.1):8888/?token=3b25a7d36480c401973b4949b0fb59a4f2d8f5d9e2225471
[I 11:43:41.722 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:43:41.726 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/dclong/.local/share/jupyter/runtime/nbserver-35-open.html
    Or copy and paste one of these URLs:
        http://(351db77f4635 or 127.0.0.1):8888/?token=3b25a7d36480c401973b4949b0fb59a4f2d8f5d9e2225471
[I 11:48:49.731 LabApp] 302 GET / (172.17.0.1) 0.61ms
[I 11:48:49.734 LabApp] 302 GET /lab? (172.17.0.1) 0.64ms
[W 11:49:04.310 LabApp] Not allowing login redirect to '/lab?'
[I 11:49:04.310 LabApp] 302 POST /login?next=%2Flab%3F (172.17.0.1) 1.66ms
[I 11:49:04.317 LabApp] 302 GET / (172.17.0.1) 0.54ms
[W 11:49:05.440 LabApp] The extension "nbdime-jupyterlab" is outdated.
    
[I 11:49:05.461 LabApp] Build is up to date
[I 11:49:08.697 LabApp] Creating new file in /
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser console here.
</pre>
</details>

**Comment by asford** [comment]
I can confirm that this breaks https://github.com/jwkvam/jupyterlab-vim as well, through a similar traceback.

The console is showing errors in codemirror.js:7726 (trace below):

```
7722:    option("keyMap", "default", function (cm, val, old) {
7723:      var next = getKeyMap(val);
7724:      var prev = old != Init && getKeyMap(old);
7725:      if (prev && prev.detach) { prev.detach(cm, next); }
7726:      if (next.attach) { next.attach(cm, prev || null); }
7727:    });
```

Debugger is showing `val == "vim"`, and a dive into `getGetMap` is showing that this vim keymap isn't loaded.

This repro isn't fully consistent, I can occasionally get the text editor to drop into vim mode properly. My first guess would be that #6516 has introduced a race condition of some form, as I can reproduce this issue intermittently in the binder-hosted build in that PR.

```
codemirror.js:7726 Uncaught (in promise) TypeError: Cannot read property 'attach' of undefined
    at CodeMirror.<anonymous> (codemirror.js:7726)
    at codemirror.js:3908
    at CodeMirror.setOption (codemirror.js:8219)
    at index.js:122
    at Set.forEach (<anonymous>)
    at RestorablePool.forEach (restorablepool.js:168)
    at WidgetTracker.forEach (widgettracker.js:149)
    at updateTracker (index.js:119)
    at execute (index.js:202)
    at CommandRegistry.push.5TpB.CommandRegistry.execute (index.js:351)
```

A dive into

**Comment by pdenno** [comment]
Can someone confirm that the emacs keybindings don't work in this image either? They don't for me. The cause seems to be different, though.
