### ISSUE TITLE
error when run $ jupyter lab

### ISSUE THREAD

**Issue by vtrokhymenko** [jupyterlab/jupyterlab#6745]
hi

i run `$ jupyter lab` in the virtual env at `p3.7.3` on macos mojave at the safari & i didn't see normal window, only empty browser window.
but when i run from `--no-browser` i saw welcome window and after entering token again saw empty windows

**Comment by vtrokhymenko** [comment]
@afshin maybe u can help?

**Comment by saulshanabrook** [comment]
Can you look at your browser console to see if there are any errors?

**Comment by vidartf** [comment]
There was another issue recently (https://github.com/jupyterlab/jupyterlab/issues/6725) where the solution was to clear the browser cache. It would be nice if you could check if this has an effect.

**Comment by vtrokhymenko** [comment]
@saulshanabrook at inspector safari i get next:
![image](https://user-images.githubusercontent.com/8581044/60458303-e54a3400-9c46-11e9-9209-2367a9448c5b.png)

**Comment by vtrokhymenko** [comment]
unfortunately, clean cache didn't help

**Comment by vtrokhymenko** [comment]
also i have the next error at inspector
![image](https://user-images.githubusercontent.com/8581044/60458915-7968cb00-9c48-11e9-9530-246bb3a3531d.png)

**Comment by vtrokhymenko** [comment]
downgrading to `0.35.6` help solve the problem
