### ISSUE TITLE
Restart and run to current cell

### ISSUE THREAD

**Issue by timhoffm** [jupyterlab/jupyterlab#6746]
**Feature Request**
This is a feature request for a function "Restart and run to current cell".

**Motivation**
There's a tension between linear execution and non-linear execution for exploratory purposes https://github.com/jupyterlab/jupyterlab/issues/5213#issuecomment-417095977. Usually, you start linear, but at some point you start exploring data and reexecuting earlier cells.

When you are done with your exploration, you want to clean up your exploration code and move on. However, the interpreter has still all information of the exploration and you cannot be sure that the results would be the same if the cleaned code would be executed linearly. At this point you should rerun the code so far to see if everything is working.

You could "Restart and run all" but usually, you'll have to check some results at the place of the exploration, which is not necessarily at the end. I currently restart and Shift+Enter through all the cells up to after the exploration place. That's quite cumbersome and the requested function would ease that.

It sounds like a small thing, but I think this would really help with getting back to a clean linear execution after one has messed about in the notebook.

**Comment by alesgenova** [comment]
I can take a look at this!
