### ISSUE TITLE
jupyterlab do not consider $JUPYTER_CONFIG_DIR

### ISSUE THREAD

**Issue by mayanksuman** [jupyterlab/jupyterlab#6747]
jupyterlab do not respect  the environment variable `JUPYTER_CONFIG_DIR` for saving its settings. Even if the environment variable is set, the settings and workspaces for jupyterlab is saved in `~/.jupyter/lab/` instead of `$JUPYTER_CONFIG_DIR/lab` folder.

**To Reproduce**

1. Set the  `JUPYTER_CONFIG_DIR` environment variable to something other than `~/.jupyter`
2. Generate the notebook config by `jupyter notebook --generate-config`. The configuration is generated inside `JUPYTER_CONFIG_DIR` folder.
3. Start jupyterlab and try to edit the user settings. The new user setting files are still saved in `~/.jupyter/lab`

**Expected behavior**
The settings and workspaces of jupyterlab should be saved in `$JUPYTER_CONFIG_DIR/lab` if `JUPYTER_CONFIG_DIR` environment variable is set.

- OS: Debian 10
- JupyterLab 1.0.0 from conda-forge

**Comment by blink1073** [comment]
Thanks for the report!  I did some quick digging.

We're getting the user settings dir [here](https://github.com/jupyterlab/jupyterlab/blob/e2fd4c8841a7393f9131fb6b6e8252864a8bd351/jupyterlab/commands.py#L116), which should have picked up that environment variable [here](https://github.com/jupyter/jupyter_core/blob/7cb0a282fad0273a05c92d82d32a5de84eb8ad91/jupyter_core/paths.py#L173).

**Comment by mayanksuman** [comment]
> We're getting the user settings dir here, which should have picked up that environment variable here.

I have seen that. These seem to be consistent and working (I have checked that separately in IPython). I think problem is in javascript code of setting editor or loader.

**Comment by blink1073** [comment]
Hmm, I tried the following with jlab 1.0:

- `mkdir -p temp-jupyter-settings`
- `export JUPYTER_CONFIG_DIR=`pwd`/temp-jupyter-settings`
- `jupyter notebook --generate-config`
- `jupyter lab`
- Make a change to the theme settings in the advanced setting editor
- `cat tmp-jupyter-settings/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings`
```
{
    // Theme
    // @jupyterlab/apputils-extension:themes
    // Theme manager settings.
    // *************************************

    // Selected Theme
    // Application-level visual styling theme
    "theme": "JupyterLab Light",

    // Scrollbar Theming
    // Enable/disable styling of the application scrollbars
    "theme-scrollbars": false
}
```


How did you launch JupyterLab?

**Comment by mayanksuman** [comment]
I have tried to reproduce the problem. However, I can't. With `JUPYTERLAB_SETTINGS_DIR` and `JUPYTERLAB_WORKSPACES_DIR` unset, `JUPYTER_CONFIG_DIR` is being considered by jupyterlab1.0.1. 

The bug report might be due to inconsistent environment as at that time I have updated jupyterlab to 1.0.0. Hence, this bug report can be closed.
