### ISSUE TITLE
Jupyterlab blank page

### ISSUE THREAD

**Issue by spouyllau** [jupyterlab/jupyterlab#6748]
Hello,
When I launch (since few days): 

sudo jupyterhub -f /etc/jupyterhub/jupyterhub_config.py --debug

with: c.Spawner.default_url = '/lab'

I have a blank page. But with /tree, it's ok, I've notebook interface. 

Elements:
- OS: Ubuntu 18.04.2 LTS (Bionic Beaver)
- Browser: Safari
- jupyter==1.0.0
- jupyter-client==5.2.4
- jupyter-console==6.0.0
- jupyter-core==4.5.0
- jupyterhub==1.0.0
- jupyterlab==1.0.0
- jupyterlab-server==1.0.0

Logs:
<details><summary>Command Line Output</summary>
<pre>
[D 2019-07-01 12:20:35.668 JupyterHub application:555] Looking for /etc/jupyterhub/jupyterhub_config in /home/spouyllau
[D 2019-07-01 12:20:35.669 JupyterHub application:577] Loaded config file: /etc/jupyterhub/jupyterhub_config.py
[I 2019-07-01 12:20:35.671 JupyterHub app:2120] Using Authenticator: jupyterhub.auth.PAMAuthenticator-1.0.0
[I 2019-07-01 12:20:35.671 JupyterHub app:2120] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-1.0.0
[D 2019-07-01 12:20:35.672 JupyterHub app:2073] Could not load pycurl: No module named 'pycurl'
    pycurl is recommended if you have a large number of users.
[I 2019-07-01 12:20:35.672 JupyterHub app:1257] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[D 2019-07-01 12:20:35.672 JupyterHub app:1424] Connecting to db: sqlite:////etc/jupyterhub/jupyterhub.sqlite
[D 2019-07-01 12:20:35.688 JupyterHub orm:749] database schema version found: 4dc2d5a8c53c
[I 2019-07-01 12:20:35.693 JupyterHub proxy:460] Generating new CONFIGPROXY_AUTH_TOKEN
[D 2019-07-01 12:20:35.732 JupyterHub app:1910] Loading state for spouyllau from db
[D 2019-07-01 12:20:35.733 JupyterHub app:1910] Loading state for jupyter from db
[D 2019-07-01 12:20:35.733 JupyterHub app:1926] Loaded users:
    spouyllau admin
     jupyter
[I 2019-07-01 12:20:35.741 JupyterHub app:2337] Hub API listening on http://127.0.0.1:8081/hub/
[I 2019-07-01 12:20:35.742 JupyterHub proxy:645] Starting proxy @ http://:443/
[D 2019-07-01 12:20:35.742 JupyterHub proxy:646] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '443', '--api-ip', '127.0.0.1', '--api-port', '8001', '--error-target', 'http://127.0.0.1:8081/hub/error', '--ssl-key', '/etc/jupyterhub/jupyterhub.key', '--ssl-cert', '/etc/jupyterhub/jupyterhub.crt']
[D 2019-07-01 12:20:35.745 JupyterHub proxy:561] Writing proxy pid file: jupyterhub-proxy.pid
12:20:36.203 - info: [ConfigProxy] Proxying https://*:443 to (no default)
12:20:36.205 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[D 2019-07-01 12:20:36.682 JupyterHub proxy:681] Proxy started and appears to be up
[D 2019-07-01 12:20:36.683 JupyterHub proxy:314] Fetching routes to check
[D 2019-07-01 12:20:36.688 JupyterHub proxy:765] Proxy: Fetching GET http://127.0.0.1:8001/api/routes
12:20:36.696 - info: [ConfigProxy] 200 GET /api/routes 
[I 2019-07-01 12:20:36.697 JupyterHub proxy:319] Checking routes
[I 2019-07-01 12:20:36.697 JupyterHub proxy:399] Adding default route for Hub: / => http://127.0.0.1:8081
[D 2019-07-01 12:20:36.697 JupyterHub proxy:765] Proxy: Fetching POST http://127.0.0.1:8001/api/routes/
12:20:36.699 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
12:20:36.700 - info: [ConfigProxy] 201 POST /api/routes/ 
[I 2019-07-01 12:20:36.701 JupyterHub app:2422] JupyterHub is now running at http://:443/
</pre>
</details>

Have you some ideas ?

Best,

Stéphane.

**Comment by blink1073** [comment]
Hi @spouyllau!  When you launch the `/lab` page, can you please bring up the browser console (usually F12), and copy/paste the messages here?

**Comment by spouyllau** [comment]
Re,

[Error] SyntaxError: Unexpected identifier 'e'. Cannot declare a lexical variable twice: 'e'.
	(fonction anonyme) (vendors~main.e694c8bb1380bb0290ea.js:1)

S.

**Comment by DipadityaDas** [comment]
Once try to remove cache of the browser.

**Comment by spouyllau** [comment]
yes, that's it ! Shame on me :)

**Comment by michaelaye** [comment]
i have the exact same symptoms (blank white page) and error in the console (Unexpected identifier 'e' ...) in Safari@Mac only (Not in Chrome or FF on the Mac).
Clearing caches using Develop->Empty Caches and clearing history did not resolve the issue for me.

This only happened after upgrade from 0.35.x to 1.0.0 (using conda on python 3.7).

**Comment by desilinguist** [comment]
I have the exact same issue as @michaelaye. Chrome and Firefox are fine but Safari is not. I also upgraded to jupyterlab 1.0.0 using `conda` with python 3.7.

**Comment by blink1073** [comment]
@afshin, can you repro?

**Comment by vtrokhymenko** [comment]
yes, downgrading to 0.35.6 me too
i have the same problems like @desli

**Comment by yoavram** [comment]
Happens to me to on Safari and MacOS after Jupyter lab 1.0 upgrade with Conda.

BTW - If I go to `/tree`, I can use the notebook UI (but `/lab` doesn't work, gives me a blank page).

**Comment by vidartf** [comment]
Do the people who experience this issue have extensions installed? If so, you could try uninstalling them, and see if it works. If that fixes it, I would recommend reinstalling the extensions one by one to catch any faulty ones.

**Comment by vtrokhymenko** [comment]
i didn't have any extensions. install jupyterlab to empty virtualenv & get empty browser window on your last version

**Comment by afshin** [comment]
I don't know the cause yet. In a clean `conda` environment with a `conda install jupyterlab`, JupyterLab works in Firefox but not in Safari. Running:
```bash
jupyter lab build
```
fixes Safari for me.

**Comment by jasongrout** [comment]
> but not in Safari.

I see the same thing. There is a js console error in Safari:

**Comment by afshin** [comment]
I *think* the root cause is that the version of JupyterLab we ship is built for production and the production output probably has something that triggers this Safari bug: https://bugs.webkit.org/show_bug.cgi?id=189914

The reason `jupyter lab build` fixes it is because by default it triggers a dev build instead of a prod build and its output is not triggering this bug.

**Comment by afshin** [comment]
I can confirm that if you run:
```
jupyter lab build --dev=False
```
it will break Safari.

**Comment by afshin** [comment]
Here is the bug in the terser plugin we use to minify: https://github.com/terser-js/terser/issues/117

**Comment by afshin** [comment]
Adding `safari10: true` to the `TerserPlugin` instantiation options does not fix this issue.

**Comment by vtrokhymenko** [comment]
in total,
`$ jupyter lab build` helped, but lab load a long time (>1m)

**Comment by afshin** [comment]
@vtrokhymenko We'll be publishing version 1.0.1 very soon and it will contain the fix; so using `jupyter lab build` to fix this is temporary.

**Comment by vtrokhymenko** [comment]
@afshin ok, thx
will be cool, if u write in this issue about update version.

**Comment by blink1073** [comment]
I just released 1.0.1 with the fix.  Thanks @afshin!
