### ISSUE TITLE
Fail to download files from the file exploration panel

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#6754]
**Describe the bug**
JupyterLab 1.0.2 does not allow me to download a file using the file exploration panel.

**To Reproduce**

1. Pull the Docker image [dclong/jupyterlab](https://github.com/dclong/docker-jupyterlab) using the command `docker pull dclong/jupyterlab`.
2. Start a container of [dclong/jupyterlab](https://github.com/dclong/docker-jupyterlab) using the following commnd on Mac or Linux.
```
docker run -it \
    --log-opt max-size=50m \
    -p 8888:8888 \
    -e DOCKER_USER=`id -un` \
    -e DOCKER_USER_ID=`id -u` \
    -e DOCKER_PASSWORD=`id -un` \
    -e DOCKER_GROUP_ID=`id -g` \
    -v `pwd`:/workdir \
    -v `dirname $HOME`:/home_host \
    dclong/jupyterlab
```
3. Copy the token from the terminal and login to the JupyterLab server. 
2. Right click on a file in th file exploration panel to pop up the right-click menu. 
3. Click "Download" and you will see that the it fails to download the file. You will get an error message similar to the one in the screenshot below. 
![image](https://user-images.githubusercontent.com/824507/60545863-eb84f280-9cd0-11e9-9edf-1774e0dcfb0a.png)

**Expected behavior**
Downloading files using the file exploration panel should work as usual. 

**Screenshots**
![image](https://user-images.githubusercontent.com/824507/60545863-eb84f280-9cd0-11e9-9edf-1774e0dcfb0a.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.10 (via Docker)
- Browser: Chrome 75 (on Windows)
- JupyterLab: 1.0.2

**Additional context**

If available, please include the following details:

<details><summary>Troubleshoot Output</summary>
<pre>
WARNING: The directory '/home/chdu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
$PATH:
        /home/chdu/.local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/lib/jvm/java-8-openjdk-amd64/bin
        /usr/lib/jvm/java-8-openjdk-amd64/bin

sys.path:
        /usr/local/bin
        /usr/lib/python36.zip
        /usr/lib/python3.6
        /usr/lib/python3.6/lib-dynload
        /usr/local/lib/python3.6/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.6.8 (default, Apr  9 2019, 04:59:38) 
        [GCC 8.3.0]

platform.platform():
        Linux-4.4.0-143-generic-x86_64-with-Ubuntu-18.10-cosmic

which -a jupyter:
        /usr/local/bin/jupyter

pip list:
        Package             Version  
        ------------------- ---------
        alembic             1.0.11   
        asn1crypto          0.24.0   
        astroid             2.2.5    
        async-generator     1.10     
        atomicwrites        1.3.0    
        attrs               19.1.0   
        backcall            0.1.0    
        beakerx             1.4.1    
        bleach              3.1.0    
        bokeh               1.2.0    
        certifi             2018.4.16
        certipy             0.1.3    
        chardet             3.0.4    
        Click               7.0      
        cloudpickle         1.2.1    
        colorama            0.4.1    
        command-not-found   0.3      
        cryptography        2.3      
        cycler              0.10.0   
        dask                2.0.0    
        decorator           4.4.0    
        defusedxml          0.6.0    
        distributed         2.0.1    
        dsutil              0.3.2    
        entrypoints         0.3      
        flake8              3.7.7    
        gitdb2              2.0.5    
        GitPython           2.1.11   
        greenlet            0.4.13   
        HeapDict            1.0.0    
        holoviews           1.12.3   
        hvplot              0.4.0    
        idna                2.7      
        importlib-metadata  0.18     
        ipykernel           5.1.1    
        ipython             7.6.0    
        ipython-genutils    0.2.0    
        ipywidgets          7.4.2    
        isort               4.3.21   
        JayDeBeApi          1.1.1    
        jdbay               0.1.0    
        jedi                0.14.0   
        Jinja2              2.10.1   
        joblib              0.13.2   
        JPype1              0.7.0    
        json5               0.8.4    
        jsonschema          3.0.1    
        jupyter             1.0.0    
        jupyter-client      5.2.4    
        jupyter-console     6.0.0    
        jupyter-core        4.5.0    
        jupyterhub          1.0.0    
        jupyterlab          1.0.0    
        jupyterlab-server   1.0.0    
        keyring             15.1.0   
        keyrings.alt        3.1      
        kiwisolver          1.1.0    
        lazy-object-proxy   1.4.1    
        locket              0.2.0    
        loguru              0.3.0    
        Mako                1.0.12   
        Markdown            3.1.1    
        MarkupSafe          1.1.1    
        matplotlib          3.1.0    
        mccabe              0.6.1    
        mistune             0.8.4    
        more-itertools      7.1.0    
        msgpack             0.5.6    
        mypy                0.711    
        mypy-extensions     0.4.1    
        nbconvert           5.5.0    
        nbdime              1.0.6    
        nbformat            4.4.0    
        neovim              0.2.6    
        notebook            5.7.8    
        notifiers           1.0.4    
        numpy               1.16.4   
        oauthlib            3.0.1    
        packaging           19.0     
        pamela              1.0.0    
        pandas              0.24.2   
        pandocfilters       1.4.2    
        panel               0.6.0    
        param               1.9.1    
        parso               0.5.0    
        partd               1.0.0    
        pexpect             4.7.0    
        pickleshare         0.7.5    
        Pillow              6.0.0    
        pip                 19.1.1   
        pluggy              0.12.0   
        prometheus-client   0.7.1    
        prompt-toolkit      2.0.9    
        psutil              5.6.3    
        ptyprocess          0.6.0    
        py                  1.8.0    
        py4j                0.10.8.1 
        pyarrow             0.12.1   
        pycodestyle         2.5.0    
        pycrypto            2.6.1    
        pyct                0.4.6    
        pyflakes            2.1.1    
        Pygments            2.4.2    
        PyGObject           3.30.1   
        pylint              2.3.1    
        pyOpenSSL           19.0.0   
        pyparsing           2.4.0    
        pyrsistent          0.14.11  
        PySocks             1.7.0    
        pytest              5.0.0    
        python-apt          1.7.1    
        python-dateutil     2.8.0    
        python-editor       1.0.4    
        pytz                2019.1   
        pyviz-comms         0.7.2    
        pyxdg               0.25     
        PyYAML              5.1.1    
        pyzmq               18.0.2   
        qtconsole           4.5.1    
        requests            2.21.0   
        rfc3987             1.3.8    
        scikit-learn        0.21.2   
        scipy               1.3.0    
        SecretStorage       2.3.1    
        Send2Trash          1.5.0    
        setuptools          40.2.0   
        six                 1.12.0   
        smmap2              2.0.5    
        sortedcontainers    2.1.0    
        SQLAlchemy          1.3.5    
        sqlparse            0.3.0    
        tabulate            0.8.3    
        tblib               1.4.0    
        terminado           0.8.2    
        testpath            0.4.2    
        toolz               0.9.0    
        tornado             6.0.3    
        traitlets           4.3.2    
        typed-ast           1.4.0    
        unattended-upgrades 0.1      
        urllib3             1.24.2   
        wcwidth             0.1.7    
        webencodings        0.5.1    
        wheel               0.30.0   
        widgetsnbextension  3.4.2    
        wrapt               1.11.2   
        xgboost             0.90     
        xonsh               0.9.7    
        yapf                0.27.0   
        zict                1.0.0    
        zipp                0.5.1
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser console here.
</pre>
</details>

**Comment by dclong** [comment]
@jasongrout Would you help scope this issue? I personally think it should belong to milestone 1.1 as it affects the usability of JupyterLab.

**Comment by jasongrout** [comment]
> Click "Download" and you will see the issue.

What exactly does happen now that is wrong?

Do you see this also with the [official jupyterlab demo](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/try.jupyter.org?urlpath=lab)?

**Comment by dclong** [comment]
Sorry that the description was clear. I've updated the description of the issue. 

I don't see the issue with the official jupyterlab demo, so it's likely due to other reasons. I will close this issue. However, just in case it helps to identify the root cause, in the Docker image that I provided a file can be downloaded by `Right Click Menu -> Open in New Browser Tab`.

**Comment by jasongrout** [comment]
We fixed one forbidden error in jlab 1.0. Are you *sure* you are using jlab 1.0? See https://github.com/jupyterlab/jupyterlab/issues/6609 and https://github.com/jupyterlab/jupyterlab/pull/6686

**Comment by dclong** [comment]
Yes, I was using JupyterLab 1.02. I just did more testing. I can confirm that the downloading functionality of JupyterLab 1.0 is working. The issue only happens in Chrome on my office computers. It works well in Chrome on my own laptops and it works well in Safari on my office computers. Since Chrome is the official supported browser in my company, it's like due to some security/firewall setup in Chrome in my company.

**Comment by anonymone** [comment]
This issue also occurs when I use 1.0.4 on Chrome. But it works well in Edge.

**Comment by wqh17101** [comment]
I have the same issues,too. As 
![image](https://user-images.githubusercontent.com/26429138/62508074-f3d4ce00-b838-11e9-9924-c54cf038d3b3.png)
everything downloaded by `right-click Download` was forced to change the postfix as endswith .htm since the original postfix is not .htm which is a postfix forbiddened by Chrome.
It is so weird that in classic notebook i can download normally

**Comment by wqh17101** [comment]
fixed by https://github.com/jupyterlab/jupyterlab/pull/6686
