### ISSUE TITLE
Need support for disabling individual plugins

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#6755]
We support disabling an extension by module name, but we also need to support disabling extensions by plugin name.  We should also log to the console when extensions/plugins are disabled.

**Comment by vidartf** [comment]
I think disabling individual plugins are supported, xref https://github.com/jupyterlab/jupyterlab/issues/6751

**Comment by blink1073** [comment]
I tried this morning to disable our markdown extension using the full `:plugin` name and it was not disabled.

**Comment by vidartf** [comment]
@blink1073 When I run `jupyter labextension disable @jupyterlab/application-extension:layout` and try to run lab, everything fails gloriously.

**Comment by afshin** [comment]
This appears to work, now. I'll close the issue, if you find that it's not working, please feel free to re-open the issue or open a new one.

**Comment by vidartf** [comment]
@afshin I think this bit is still missing?

>  We should also log to the console when extensions/plugins are disabled.

**Comment by vidartf** [comment]
Actually that is tracked here: https://github.com/jupyterlab/jupyterlab/issues/6751
