### ISSUE TITLE
jupyter nbextension enable --py --sys-prefix isnt working!

### ISSUE THREAD

**Issue by kp6689** [jupyterlab/jupyterlab#6765]
my first post over here! The issue surrounds the problem I face everytime I run the extension enable command.
image
![image](https://user-images.githubusercontent.com/52552377/60696139-08ab0280-9f17-11e9-8dbd-bbc924517eaa.png)

^ thats the error file.

Is the issue because of mutliple python path or something else and in addition to it, there is no extension option in 'EDIT' drop down box, pls refer to the image below.

![image](https://user-images.githubusercontent.com/52552377/60696077-be298600-9f16-11e9-94f3-841c1d8d18c2.png)

image

**Comment by ian-r-rose** [comment]
Hi @kp6689, this sounds like an issue with the classic notebook interface (this repo is for the JupyterLab interface, which uses a different extension mechanism). Can you ask over there? https://github.com/jupyter/notebook
