### ISSUE TITLE
jupyterlab integration with bqplot giving error "Error displaying widget"

### ISSUE THREAD

**Issue by victoriaaa234** [jupyterlab/jupyterlab#6766]
I'm trying to use jupyterlab and bqplot to display widgets using the following installations:

`$ pip install bqplot `
`$ jupyter labextension install @jupyter-widgets/jupyterlab-manager`
`$ jupyter labextension install bqplot`

The versions I am using:
jupyterlab = 0.35.0
@jupyter-widgets/jupyterlab-manager@0.38
bqplot = 0.11.5

Example:
```import numpy as np
import bqplot.pyplot as plt

size = 100
scale = 100.
np.random.seed(0)
x_data = np.arange(size)
y_data = np.cumsum(np.random.randn(size)  * scale)

fig = plt.figure()
axes_options = {'x': {'label': 'Date', 'tick_format': '%m/%d'},
                'y': {'label': 'Price', 'tick_format': '0.0f'}}

plt.scatter(x_data, y_data, colors=['red'], stroke='black')
fig
```

Using a simple example, I get this behavior:
![image](https://user-images.githubusercontent.com/15025941/60737818-a6a3ca80-9f21-11e9-8553-ad1deab495ba.png)

and...
![image](https://user-images.githubusercontent.com/15025941/60737837-bae7c780-9f21-11e9-8fa6-a6736f2bb66f.png)

This code works on notebook, and plots the figure:

![image](https://user-images.githubusercontent.com/15025941/60738072-993b1000-9f22-11e9-81d5-f3eab029f072.png)

I am not sure how to resolve this, so any help would be greatly appreciated.

**Comment by timkpaine** [comment]
can you do
`pip show bqplot`
and
`jupyter lab extension list`

So we can check the 2 versions of bqplot

**Comment by victoriaaa234** [comment]
ah. the versions are different. 

![image](https://user-images.githubusercontent.com/15025941/60738198-1797b200-9f23-11e9-99a4-64ae0809c2d2.png)

![image](https://user-images.githubusercontent.com/15025941/60738209-22524700-9f23-11e9-819b-3f6f8497253e.png)

**Comment by victoriaaa234** [comment]
ah. the versions are different.

`pip show bqplot` gives me `Version: 0.11.5`

`jupyter labextension list` gives me `bqplot v0.4.6`

**Comment by timkpaine** [comment]
thats ok, they're not supposed to be equal. let me look up the corresponding versions

**Comment by timkpaine** [comment]
for `bqplot` python 0.11.5 you need `bqplot` js 0.4.5.

**Comment by timkpaine** [comment]
https://github.com/bloomberg/bqplot/blob/0.11.5/js/package.json

**Comment by victoriaaa234** [comment]
it worked. thank you so much!! not sure why it was installing bqplot js 0.4.6

**Comment by timkpaine** [comment]
@victoriaaa234 mind closing the issue
