### ISSUE TITLE
requestExecute should use the metadata argument

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6767]
`requestExecute` takes an optional metadata argument that isn't used: https://github.com/jupyterlab/jupyterlab/blob/4d88d60c839c3ba4a00eda1f396da6e525c84133/packages/services/src/kernel/default.ts#L572

It should be passed on to the createMessage call at https://github.com/jupyterlab/jupyterlab/blob/4d88d60c839c3ba4a00eda1f396da6e525c84133/packages/services/src/kernel/default.ts#L584-L590

Thanks to @balamuruganvg for pointing this out [on Gitter](https://gitter.im/jupyterlab/jupyterlab?at=5d1f6e9eb5d39c1bfef90472).

**Comment by balamuruganvg** [comment]
Thanks @jasongrout  for opening the issue. I have created a PR for this  at https://github.com/jupyterlab/jupyterlab/pull/6780

**Comment by blink1073** [comment]
Fixed by #6780
