### ISSUE TITLE
Put some useful actions in the notebook toolbar 

### ISSUE THREAD

**Issue by homofortis** [jupyterlab/jupyterlab#6771]
Be honest - when was the last time you clicked on the `copy` icon of the toolbar, or on the `cut`, `paste`, `run cell`, `save` icons? When was the last time you changed the cell type by clicking on the dropdown menu of the toolbar?

Seriously, if it is so hard to change the interface and add an option to hide the toolbar then at least replace the existing actions with commands as `hide all outputs`, `hide all code`, `restart the kernel and rerun all cells`, `toggle dark/light theme`, etc.

**Comment by homofortis** [comment]
Apparently, it will never happen. Seems current icons still enjoy the love of their creators. They will even get [text labels](https://github.com/jupyterlab/jupyterlab/issues/6038#issue-415207101) (or why not a few paragraphs of explanatory text ).

**Comment by jasongrout** [comment]
I personally witnessed multiple people using such toolbar buttons in the last few days to do their work.

If there are some specific buttons you'd like added to the toolbar, we welcome a constructive conversation about them. If you want to open a new issue for specific buttons to add or other ways to customize the toolbar, please use constructive language so we can move forward. Let's have a productive conversation that doesn't start with insulting sarcasm.

**Comment by homofortis** [comment]
@jasongrout  Apologies if I have insulted anyone, I didn't want my post to sound this way. I thought, Jupyter notebook and lab are mainly used by software professionals and from my personal experience, I've always put the accent on the keyboard shortcuts when it comes to the routine operations - and cut, copy, paste, run, and cell type are routine operations (correct me if I am wrong).
Regarding constructive conversation and additional buttons of the toolbar, I had suggested the following in my OP:
- add an option to hide the toolbar
- add buttons for the following actions: `hide all outputs`, hide all code, `restart the kernel and rerun all cells`, 'toggle dark/light theme'.

**Comment by jasongrout** [comment]
> I had suggested the following in my OP:

Thanks, and thanks for the apologies.  In the OP, it ended with "etc.", so it sounded to me like you were giving examples, but not asking for something very specific. Let's start the conversation again in a new issue with those specific suggestions?
