### ISSUE TITLE
Password field (ipywidgets.Password) is not properly styled

### ISSUE THREAD

**Issue by earshinov** [jupyterlab/jupyterlab#6777]
**Describe the bug**

Password field (`ipywidgets.Password`) is not properly styled.

Here it is in comparison with a simple text field (`ipywidgets.Text`):

![text vs password field](https://user-images.githubusercontent.com/52021/60767635-48165200-a0c3-11e9-980c-9a11892f82f5.png)

JupyterLab defines a bunch of styles for `.widget-text input[type="text"], .widget-text input[type="number"], .widget-textarea textarea`, but as you can see, `input[type="password"]` is not in the list.

**To reproduce**

In a notebook:

```python
import ipywidgets as widgets

display(widgets.VBox([
  widgets.Text(description='Username')
  widgets.Password(description='Password')
]))
```

**Expected behavior**

Password fields should have the same size, paddings, border color etc. as ordinary text fields.

**Environment:**

- OS: Windows 10
- Browser: Google Chrome 75.0.3770.100
- JupyterLab 0.35.6

**Comment by jasongrout** [comment]
Thanks! Can you move this to the ipywidgets repo? https://github.com/jupyter-widgets/ipywidgets
