### ISSUE TITLE
How do I upgrade the jupyterlab in anaconda to version 1.0

### ISSUE THREAD

**Issue by PhilosopherZ** [jupyterlab/jupyterlab#6784]
How do I upgrade the jupyterlab in anaconda to version 1.0？

**Comment by dlasusa** [comment]
I'd like to know this as well.
I've tried running `conda update jupyterlab`  which provides output that indicates packages are being updated, but jupyterlab is still at version 0.35.4

My Anaconda environment was downloaded and installed this morning.  Downloaded file: `Anaconda3-2019.03-Windows-x86_64.exe`

**Comment by emcangi** [comment]
`conda update -c conda-forge jupyterlab` worked for me.

**Comment by dlasusa** [comment]
@emcangi I had originally tried that command in the separate anaconda prompt (which didn't seem to help).  Running it in a terminal tab inside of jupyterlab itself seemed to do the trick for me!  Thanks!!

**Comment by sbamin** [comment]
I also get similar issue and tried following commands but do not see an update in jupyterlab.

```
conda update -c conda-forge jupyterlab
conda update -c conda-forge jupyterlab jupyterlab_server
conda upgrade jupyterlab jupyterlab_server
```

>Output

```
WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

(base) :~$pip freeze | grep lab
alabaster==0.7.12
jupyterlab==0.35.4
jupyterlab-server==0.2.0
```

Using anaconda3 v4.7.5 on cent os 6 x86_64.

**Comment by sbamin** [comment]
For time being, I did `pip install` over conda one and that worked for cent os 6. Unsure why conda install did not work.
 
[log_jupyter_upgrade_pip.txt](https://github.com/jupyterlab/jupyterlab/files/3379360/log_jupyter_upgrade_pip.txt)

**Comment by Gkchandora** [comment]
> https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html
> 
> `conda update -c conda-forge jupyterlab` worked for me on Ubuntu. If you're on Windows I think you can enter this command in the bundled terminal, or there's probably a GUI way to use conda-forge channel

I also did the same thing in my terminal ,but it didn't work for me ! Can you please give me some suggestions, my system is windows10 64 bit

**Comment by ptcane** [comment]
Mac OS Mojave fresh Anaconda Python 3.7 64-bit install could not update to 1.02 using conda or the Navigator UI. Sbamin's solution worked for me (pip install of numerous jupyter- components, not just lab). Navigator still says 0.35 on UI but opens 1.02 (as does loading from Terminal).

**Comment by echyam** [comment]
Similar situation as @ptcane 
Conda thinks jupyter lab is v1.0.2. But when I launch and check again, it says v0.32.1

screenshot from inside my jupyter window:
![image](https://user-images.githubusercontent.com/11476825/61734258-738d7380-ad36-11e9-9fb1-e0a3c8f88364.png)

**Comment by sbamin** [comment]
That's unusual as I checked on my end and I see v1.0.2 in UI.

On a side note to developers, since I updated jupyter components using pip, now when I try to install conda packages that has dependency on either jupyter or conda default packages, `conda install` forces me to downgrade jupyter core to 0.35. I checked anaconda.org and find that both, conda-forge and anaconda channels have jupyterlab 1.0 as default. I do not know how to fix this issue.

**Comment by jasongrout** [comment]
Depending on how messed up your environment is, you may want to start with a fresh clean environment. You can also try uninstalling everything you installed with pip, then using conda to install.

**Comment by ptcane** [comment]
@jasongrout Unfortunately for me at least this is what I had already done before having to then use pip commands on that fresh install to get jupyterlab to 1.02.

**Comment by jasongrout** [comment]
Sounds like anaconda has now updated to jlab 1.0. Our official installation instructions use the conda-forge channel. Either one of those means you should not have to use pip now.
