### ISSUE TITLE
React unique key error in extension manager companion dialog

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#6788]
React currently shows the following error when the kernel / server companion dialog from the extension manager is displayed:

```
Warning: Each child in a list should have a unique "key" prop.
Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.
  in p
```

The issue is similar to https://github.com/jupyterlab/jupyterlab/issues/5392, and the fix would also be similar to https://github.com/jupyterlab/jupyterlab/pull/5544.

Marking this as a good first issue.

To test the two types of dialogs (by searching in the extension manager and clicking "Install"):

- `@jupyterlab/github` has a server companion
- `jupyter-scales` has a kernel companion

**Comment by AlokTakshak** [comment]
@jtpio I would like to contribute to it ,can you just point me to corresponding file thanks

**Comment by jtpio** [comment]
Great, thanks!

The corresponding file is this one: https://github.com/jupyterlab/jupyterlab/blob/master/packages/extensionmanager/src/companions.tsx

There are a few entries that are put together in a list to populate the dialog, such as this one:

https://github.com/jupyterlab/jupyterlab/blob/c3d6801290fd5cdb527d1a9a198f97c19f890a1f/packages/extensionmanager/src/companions.tsx#L111-L115

The React documentation has more details regarding the use of `keys` inside arrays: https://reactjs.org/docs/lists-and-keys.html#keys

**Comment by AlokTakshak** [comment]
> Great, thanks!
> 
> The corresponding file is this one: https://github.com/jupyterlab/jupyterlab/blob/master/packages/extensionmanager/src/companions.tsx
> 
> There are a few entries that are put together in a list to populate the dialog, such as this one:
> 
> https://github.com/jupyterlab/jupyterlab/blob/c3d6801290fd5cdb527d1a9a198f97c19f890a1f/packages/extensionmanager/src/companions.tsx#L111-L115
> 
> The React documentation has more details regarding the use of `keys` inside arrays: https://reactjs.org/docs/lists-and-keys.html#keys


The  key we are adding should be having some standard value or i can give something like `server-companion`

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/6840.

Thanks @AlokTakshak!
