### ISSUE TITLE
1.0 Announcement on Jupyter.org

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#6789]
I've been working on the copy for the website announcement. We're looking for a message akin to: "If you've been waiting to migrate to JupyterLab wait no longer!" the post should be descriptive. My initial pass at the copy:

## The next generation Jupyter Notebook has arrived!

JupyterLab is a web-based platform that combines live code, text, images, visualizations, and data analysis into a single, interactive environment.

JupyterLab offers all the building blocks of the classic Jupyter Notebook (notebook, terminal, text editor, file browser, rich outputs, etc.) in a more extendable user interface.

#### Easy to Use

Compose notebooks, run terminals or consoles, and edit text files all within your browser. With a simple, straight-forward interface, start programming right away using any language. [p]

#### Flexible

Test your code as you go; see results immediately and iterate on your explorations. JupyterLab’s extends the Classic Notebook interface to give a desktop-like work area in which to explore data.

#### Reproducible 

Allow others to replicate and build off your work. Explain your thought process step-by-step, and share it so others can run the same analysis from anywhere in the cloud, or on their own machine.

#### Shareable 

Visualize your work and tell a story in a way that feels simple and fun. Export to a variety of formats, including a webpage, PDF, and Word document, and share it with others. 

For edits please make comments/suggestions to [this document](https://docs.google.com/document/d/121TIhinWKpPGNr9TZZlsicSvGpfNEjJjgwP0orvwjiM/edit).

I'm thinking about a screenshot/set of screenshots to use with this and am taking ideas for interesting/flashy screenshots.

**Comment by BoPeng** [comment]
The announcement could be forwarded to HackerNews, which is a good channel for such an announcement. Medium digest can also reach a lot of people but I do not know how to reach them.

**Comment by jasongrout** [comment]
At this point, I think everyone knows about 1.0 :).
