### ISSUE TITLE
Mark cell as 'edited since last run'

### ISSUE THREAD

**Issue by marwahaha** [jupyterlab/jupyterlab#6790]
👋 Hiya!

Sorry if this has been proposed before.

**User story**
As a Jupyter user, I want to know that I have changed the contents of a cell that I have previously run but have not run the latest contents yet.

This may mitigate some beginner frustrations where "my code looks right but reads wrong"; for example criticized [here](https://docs.google.com/presentation/d/1n2RlMdmv1p25Xy5thJUhkKGvjtV-dkAIsUXP-AL4ffI/edit#slide=id.g3a428e2eb8_0_223). 

Often, "Restart and Run all" fixes this sort of issue, but it should be more clear. A cell edited but not ever run (without an execution number) is more obvious than a cell edited but still showing the last execution number!

I'm looking for a "warning" or "important" style of identifier, encouraging a user to re-run cells like this as soon as possible.

**Describe the proposal**
Here are three ways to visualize the state of "edited since last run", to encourage users to rerun these cells:
1. Use a small character, like `^` or `!` after the execution number (like `[11!]: x = 2`). Users are familiar with the `*`, but might get the wrong impression (i.e. wait, instead of running the changed code).
2. Use a more obvious identifier, like `~` or `+/-` (like `[11+/-]: x = 2`). Hopefully this can signify "change" or "something needs to be run".
3. Use a small icon to the left of the execution number, like ⚠ (i.e. `⚠  [11]: x = 2`). The user might notice it, and hovering over the icon will explain that this cell has been edited since it was last run.

**Additional context**
I'm mostly interested in making the "gotchas" of Jupyter more obvious to the novice programmer, reducing the types and number of stumbling blocks while learning the tool.

**Comment by marwahaha** [comment]
See also https://github.com/jupyterlab/jupyterlab/issues/5213#issuecomment-416004010

**Comment by martinRenou** [comment]
I opened a very similar issue #9247, sorry for the duplicate.

I also thought about it when watching the "I don't like Notebooks" presentation.

It would be really nice to have a visual indicator that the cell has been changed but not executed (similar to the visual indicator in most IDEs showing that a file was modified but not saved).

Some ideas for this visual indicator:
- a small dot in the top-right corner of the code input
- a different color (orange?) for the In prompt
- a * token in the prompt, e.g. [3]* (although I agree with you it might be misleading as `*` is already used when the cell is being executed)

I like your first proposition of using `!`.

**Comment by dhirschfeld** [comment]
> [*Edit mode is indicated by a green cell border and a prompt showing in the editor area:*](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Notebook%20Basics.html#Edit-mode)

![](https://jupyter-notebook.readthedocs.io/en/stable/_images/edit_mode.png)

I was thinking, if in Edit Mode and you changed a cell without executing it, it could have a red side-bar/border.
