### ISSUE TITLE
Icons missing/poorly rendered on Chrome

### ISSUE THREAD

**Issue by fonnesbeck** [jupyterlab/jupyterlab#6796]
When opening a JupyterLab session, several icons are missing or poorly rendered. Notice the sidebar and the tab in the screen capture below:

![image](https://user-images.githubusercontent.com/81476/60926485-3d4af100-a26c-11e9-8467-6559a8adb24f.png)

All content blockers have been uninstalled.

Running version 0.35.5 on Chrome 74.

**Comment by jasongrout** [comment]
Can you try with JupyterLab 1.0, and make sure your browser zoom level is 100%?

**Comment by fonnesbeck** [comment]
Yes, works with 1.0.1. The environment.yml file I was using to create an env did not include conda-forge, and installed 0.35 automatically.

**Comment by jasongrout** [comment]
Great, thanks!
