### ISSUE TITLE
Set a specific font in terminal

### ISSUE THREAD

**Issue by luispuerto** [jupyterlab/jupyterlab#6801]
Hey! 

I've been trying to set a specific font for the terminal with no avail. I can just set font family but not an specific font I have installed as a user. 

I use zsh and I have set up powerline9k and for it work I need a nerd font that I've installed. [Here](https://discourse.jupyter.org/t/can-jupyterlab-access-use-user-installed-fonts/1623/2), it's been suggested that additional setting are needed.

**Comment by jasongrout** [comment]
The terminal font family can be set in the advanced settings. Is that what you are trying? If so, what are you setting it to?

**Comment by luispuerto** [comment]
Hey! 

Yes, I'm trying that, but it isn't able to pick an specific font. At least that isn't a system one, but a user one. 

<img width="1278" alt="Screen Shot 2019-07-11 at 09 20 56" src="https://user-images.githubusercontent.com/22882880/61067770-3d0e3b00-a3bd-11e9-9947-21bc2aecf6cf.png">
<img width="1278" alt="Screen Shot 2019-07-11 at 09 21 03" src="https://user-images.githubusercontent.com/22882880/61067771-3d0e3b00-a3bd-11e9-811f-83ef251ee479.png">

I've tried all the possible names…

**Comment by luispuerto** [comment]
PS/ did you read the post in the discourse.jupyter.org I linked in my first post? The person answering explain much better than me. 🙂

**Comment by ciyer** [comment]
This seems to be browser dependent. On chrome, it works:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/1196411/61160747-551db180-a4c6-11e9-86b0-2c1e95c50042.png">

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/1196411/61160816-a332b500-a4c6-11e9-868c-8ab8e4e88b57.png">


But on Safari, it does not:

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/1196411/61160827-af1e7700-a4c6-11e9-98ae-8355ee432104.png">

**Comment by luispuerto** [comment]
I can confirm… in firefox works too. Is there anything in safari that we could do to fix this? or it's a jupyter specific problem?

**Comment by luispuerto** [comment]
I self answer myself. 

https://stackoverflow.com/questions/52692905/font-family-display-issue-in-safari-12-on-macos-mojave#comment99450872_52805055

This is a security measure of safari, so it can only use the system fonts.

**Comment by ciyer** [comment]
It looks like there isn't much jupyter can do about this problem then. I would suggest marking the issue resolved.

**Comment by jasongrout** [comment]
Thanks for checking into it and following up here!
