### ISSUE TITLE
How can I overwrite dbclick event in filebrowser's file

### ISSUE THREAD

**Issue by daejong123** [jupyterlab/jupyterlab#6809]
I want to do something before open file when click the filebrowser's file.

![image](https://user-images.githubusercontent.com/19252403/61117247-ac248600-a4c8-11e9-8834-b2c29398275e.png)

**Comment by daejong123** [comment]
Because I have a need that add some option to openOrReveal(such as {mode: 'split-left'} etc..) when dbclick the fileItem in the fileBrowser.

**Comment by jasongrout** [comment]
It looks like the code to the filebrowser would need to be modified to modify the double-click behavior (or of course you could make a new filebrowser inheriting from this one and install that instead).

Can you elaborate on exactly what you want to do, and what the user experience looks like?

**Comment by ian-r-rose** [comment]
The filebrowser is not really intended to support custom actions upon double clicking items. That said, I have also had occasion to experiment with other actions for the file browser, and came up with this workaround:
https://github.com/ian-r-rose/jupyterlab-remote-data/blob/ec7b644b3f0e075b0b456295b8ebe08febc0f245/jupyterlab-remote-data/src/extension.ts#L37-L68

I should warn you with big flashing lights that I consider this to be a big hack, and not at all how the APIs are intended to be used. It may stop working at any time.

**Comment by daejong123** [comment]
cool! 
thx!

My needs are roughly like this：
According to the type of file clicked, decide whether to display different area in the dockpanel（such as spilt-left or tab-after)


could you give me some advice about app.shell.widgets()

**Comment by daejong123** [comment]
By the way, How can give a name to widget when i call openOrReveal method (default value is default), or How can I get all widgetNames in the Dock panel
