### ISSUE TITLE
Video Tutorials 1.0

### ISSUE THREAD

**Issue by van-8** [jupyterlab/jupyterlab#6811]
- [x] Write draft script
- [x] Record voiceover
- [x] Prepare Jupyter
- [x] Record Screen capture
- [x] Rough Edit
- [x] Submit for approval
- [x] Soundtrack
- [x] Understand JSON VEGA
- [x] include geo, dna, meteorology file types
- [x] switch to LibreOffice icons
- [x] Find citation for zika virus file
- [x] Final version compression, output, 
- [ ] Upload to?
- [x] Celebrate
- [x] Design one-pager for common keyboard shortcuts

Punt for now
- [x] Download Nick Rstudio use case
- [x] Nick Rstudio use case

**Comment by van-8** [comment]
Hey friends, here is a first attempt at a JupyterLab video tutorial from the perspective of a total beginner. The baseline script was JupyterLab ReadtheDocs, then simplified and enhanced with personal experience learning the last few weeks. I put in a bunch of Easter eggs and quick jokes cause it's my style, but can take those out if it should be more serious. 

- Haven't put in any music yet.
- It's two videos, but could be a single one.

Clicking the link will take you to the Video Review page, where you can pause at any point and leave a comment. Eager to hear criticism and feedback.

https://f.io/TmB85Oxe

Thanks for inspiring me to contribute to OSS @blink1073 @jasongrout @afshin !

**Comment by jasongrout** [comment]
Wow, this is fantastic! Amazing!

I never thought about using a new view of a notebook to preview a markdown cell. Nice!

Also, I never can remember the keyboard shortcut to change a cell to a code cell, but never get quite frustrated enough to look it up. Now I think I'll be able to remember `y`.

**Comment by ian-r-rose** [comment]
To second Jason's comments: wow. This is really fantastic, and vastly more polished than a lot of the existing tutorial material. Thanks @van-8!

I think once you are happy with this material, it might be nice to link to this in the documentation somewhere.

**Comment by dhirschfeld** [comment]
I have a lot of new-to-python/programming users and I think this is a perfect intro for  them!

**Comment by van-8** [comment]
Thanks all! Great docs and great tool, so this was lots of fun.

Any comments or critiques about the sections? Specifically, I struggle with the .JSON and .VEGA document formats, as I couldn't figure out what those are and how to show the "tree view" and other stuff. Any suggestions?

Perhaps @dhirschfeld you can send the link to a few eager newbies and get feedback? There's a few places I feel could be too fast for total beginners, but don't know any potential testers. 

I also have a number of notes on usability and user expectations; where is the proper place to humbly share those?

I was also considering creating "domain specific" video tutorials, ie how a geologist could get started with JupyterLab, a neuroscientist, an astronomer, mathematician, etc. It can be intimidating to start coding. Would that be useful?

**Comment by nickeubank** [comment]
That is *amazing*. 

The one use-case / modality I don't see (unless I missed it?) is having open a text window with your code, and selecting text and running it in an alongside kernel (analogously to how people use RStudio or Spyder). For example, this kind of work layout/flow: 

![image](https://user-images.githubusercontent.com/9683693/64611110-aa7b1f80-d39e-11e9-9967-abc6df3de76d.png)

Other than that, this is *amazing* and belongs on the jupyterlab docs front page.

**Comment by Madhu94** [comment]
@van-8 The video is awesome! I also love that you included "Celebrate" as a task in your checklist  :)

**Comment by blink1073** [comment]
Excellent work @van-8!   A couple of points:

- Our [binder](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo) has representative JSON and VEGA files, as well as GeoJSON for maps and FASTA for DNA data.
   -- JSON files are typically used for config files or for structured data.  They can have nested data, which is why we show them as a tree.   Right click on `data/Museums_in_DC.geojson` and open as JSON.
  -- VEGA files are a JSON file that describe how to draw a plot.  Right click on `data/bar.vl.json`.  https://vega.github.io/vega/
- I'm not sure what the fair use policy is, but you might consider using the LibreOffice icons for spreadsheet and presentation.

**Comment by van-8** [comment]
@nickeubank That's sounds really cool, but I'm still super novice and don't understand the feature you mention. Do you mind saving me tons of time and use QuickTime to create a short screen-recording to talk through the use case? (make sure to click the ∨ button next to the red record button and turn on the microphone) And maybe share the file you're using? 😄 

@blink1073  Perfect! Found `bar.vl.json` , `zika`, `museums` . And I think you're right, I'll switch to the LibreOffice icons.

btw, in the demo binder, how is the "JupyterLab Reference" tab displayed? Is it directly showing a webpage? Or is there an `.html` file I can't find? Is opening websites directly in JupyterLab an amazing feature I missed?

**Comment by vidartf** [comment]
> Is opening websites directly in JupyterLab an amazing feature I missed?

I think you can use this extension to do that:

https://github.com/timkpaine/jupyterlab_iframe

**Comment by blink1073** [comment]
@van-8, the documentation is rendered using a more limited version of an iframe than https://github.com/timkpaine/jupyterlab_iframe, so we didn't offer it for arbitrary html files.  We should probably absorb Tim's version at some point.

**Comment by van-8** [comment]
Edited with most of comments, didn't add nickeubank use-case as I don't understand it yet, made a dozen other mini-optimizations. Find new version here 

Should it be split into 2 videos or a single video with chapters?

Where should the final be uploaded? 

Also created a one-pager for common keyboard shortcut image. 
![keyboard shortcuts widescreen](https://user-images.githubusercontent.com/28463475/64940187-dd894b80-d895-11e9-92c2-918ff842ab45.jpg)

**Comment by nickeubank** [comment]
@van-8 wow, that's an amazing short cut sheet! you're a grpahic design wizard.

Sorry about not getting screencast. Can do later today if you still want it, but no worries if it is -- last week was rough.

**Comment by van-8** [comment]
@nickeubank no worries at all! I know how busy things get 😄 ; I just wanted to get a deliverable out there before I get swamped as well. I'm scheduling to create an "Advanced JupyterLab Tutorial" video and we can put in your use-case there, no rush at all!

**Comment by nickeubank** [comment]
[Video link](https://www.dropbox.com/s/m5p8zn6nf2tlfep/Screen%20Recording%202019-09-16%20at%2010.53.18%20AM.mov?dl=0) (ping me when downloaded so I can free my dropbox space). 

And files I use: https://github.com/nickeubank/practicaldatascience/tree/master/Example_Data/jupyter_lab

**Comment by sccolbert** [comment]
@van-8 This is absolutely fantastic. Well done!

**Comment by vidartf** [comment]
I agree with all the nice things said, very nice!  If you want a constructive nit-pick: in the first video segment, the music got loud enough at the end that it was hard for me to make out what you were saying (at least with the not very good speakers I were using). No problems otherwise.

**Comment by consideRatio** [comment]
@van-8 wow wow wow! Excellent production!

**Comment by van-8** [comment]
Made some final polishes, export optimized for YouTube recompression. Can send files to someone with YouTube credentials or if received can upload myself.

**Comment by van-8** [comment]
Sorry folks, don't know how this should work. Does a completed issue not become a pull request? Or is that only for code? Or how do I request approval by a Maintainer to close this issue?

**Comment by vidartf** [comment]
@van-8 Just to make sure I understand: What steps remain for completing this? Pull requests are for putting changes to repository files (source code, documentation, readme etc). If all steps for resolving the issue are completed it should be closed. If some changes are needed, you need to open a new PR, linking back to this issue (e.g. by writing `Fixes #6811` somewhere). Hope this helps!

**Comment by van-8** [comment]
@vidartf thanks for explaining! 
For this issue to close, the videos should be uploaded to YouTube and maybe backed up on the GitHub repo. I don't have permissions for either, so I guess I need assistance. Or someone can access the [Dropbox](https://www.dropbox.com/s/r7ij3wn0tpblr60/JuptyerLab%20How%20to%20use%20v1%20-%20HD%201080p.mov?dl=0) I setup, download and upload. Then this issue will be closed and I'll move on to the other tutorial videos.

**Comment by blink1073** [comment]
@ian-r-rose, are you able to add me to the IPython/Jupyter youtube channel?  @van-8, can you please make a pull request to add the video to https://github.com/jupyterlab/jupyterlab-media?

**Comment by ian-r-rose** [comment]
@blink1073 I've just added you as an owner -- let me know if you don't get an invite!

**Comment by blink1073** [comment]
Received, thanks!

**Comment by riordan** [comment]
@van-8 will the complete Jupyterlab for Total Beginners video be uploaded anywhere? I really appreciated the tour of the Jupyterlab interface as a separate section from the format overview.

**Comment by vidartf** [comment]
The work is currently being tracked here https://github.com/jupyterlab/jupyterlab-media/issues/7
