### ISSUE TITLE
Provide more discoverable help on where to find extensions

### ISSUE THREAD

**Issue by willingc** [jupyterlab/jupyterlab#6815]
I was looking for a link to where to find third party extensions in the UI. It would be great to surface a link to the npm search in the help menu or alternatively link to it from the FAQ.

**Comment by krassowski** [comment]
There is Extension Manager (previously jupyterlab-discovery, see #5053); not sure if it is enabled by default. It might help if it was mentioned in the FAQ.

**Comment by willingc** [comment]
It is not enabled by default in 1.0.2. It would be great if it was. Surfacing in the FAQ would be good too.

**Comment by blink1073** [comment]
Thanks, @willingc!

**Comment by jtpio** [comment]
The Extension Manager is now a [bit more discoverable](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#using-the-extension-manager) (in the menu and the command palette), but it is indeed not enabled by default (requires a builder - `nodejs` - to be available).

**Comment by willingc** [comment]
Thanks for the tip @jtpio. It would be very helpful to have the FAQ include a link to the docs or the menu item. I think this is a higher priority than enabling by default (though that would be nice too if possible).

**Comment by JasonWeill** [comment]
The extension manager is now enabled by default and is easy to enable. I'm going to close this issue now; please open a new one for future enhancements.
