### ISSUE TITLE
Unhappy face displayed with Markdown Help

### ISSUE THREAD

**Issue by willingc** [jupyterlab/jupyterlab#6816]
If you select Markdown help from the sidebar, an unhappy face displays and says it cannot connect to github page.

<img width="727" alt="Screenshot 2019-07-13 08 08 05" src="https://user-images.githubusercontent.com/2680980/61172097-95704480-a545-11e9-901e-3b262bb7f5d9.png">

**Comment by krassowski** [comment]
Works for me, which version of JupyterLab do you experience this problem with?

**Comment by willingc** [comment]
Thanks @krassowski. Confirming it works for 1.0.2. Was picking up an older version from forgetting to activate the conda environment.
