### ISSUE TITLE
Request: Add a Markdown File option to the Launcher

### ISSUE THREAD

**Issue by willingc** [jupyterlab/jupyterlab#6817]
It would be nice for folks writing documentation and README files to have an icon in the launcher for a new Markdown file next to the text file icon.

**Comment by krassowski** [comment]
Which version of JupyterLab do you use? I do have an icon for markdown files in the launcher. It was merged as a part of #5511

![Screenshot from 2019-07-13 14-16-38](https://user-images.githubusercontent.com/5832902/61172188-d9c90800-a578-11e9-8fcb-5afd42992999.png)

Or is it something else you ask for?

**Comment by willingc** [comment]
Sorry. Wrong version.
