### ISSUE TITLE
Switching between cells in the notebook does not always set a cursor position properly

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#682]
You can see it if you debug Notebook._onEdgeRequest, just step over changing active cell and when wait a bit before calling setCursor.

For our editor implementation it does not work at all because of this issue.

**Comment by jasongrout** [comment]
Can you describe what it should do?

**Comment by akosyakov** [comment]
@jasongrout if you are at the start position of one cell and press up, then a previous cell should be selected and the cursor should be positioned at the end position of the previous cell. For press down it should work other way around.

It seems to work with CodeMirror till you start debugging. If you debug as i've described above you will see that the active cell is changed but the cursor position has not been changed.

Look at the picture below, i've pressed up, the active cell is changed, but the cursor position does not.
<img width="1483" alt="screen shot 2016-08-17 at 17 47 37" src="https://cloud.githubusercontent.com/assets/3082655/17743048/b880e4de-64a2-11e6-850c-4e4ef8b2c67c.png">

For our editor it is always a case, maybe some race condition is going on here.

**Comment by ellisonbg** [comment]
Here is the relevant code:

https://github.com/jupyter/jupyterlab/blob/master/src/notebook/notebook/widget.ts#L905

**Comment by ellisonbg** [comment]
I think it is likely that we have a bug here. I am guessing that it is related to our making a change in the model (active cell), but then directly updating the view (CodeMirror) before the model change has been propagated to the view. In general we should only make changes to the view in response to model changes. We should track the cursor position in the model and let the view automatically update.

@blink1073 @afshin

**Comment by jasongrout** [comment]
Some thoughts:
1. I worry about latency if we are doing that to the extreme. In normal editing, certainly the widget will drive the model.
2. Handling multiple cursors can be tricky to get right.
3. When we have collaborative editing, we'll have to have some notion of cursor position that is broadcast to other users.

**Comment by blink1073** [comment]
We should be able to fix this after we have the abstract editor.

**Comment by blink1073** [comment]
The cursors now belong to the model.  Also, the cell cannot be activated while debugging, because it breaks normal focus behavior.  #1397 makes sure we don't get into a bad state while debugging.
