### ISSUE TITLE
IPython.display HTML is overwriting the target attribute in hyperlinks

### ISSUE THREAD

**Issue by michaele4321** [jupyterlab/jupyterlab#6827]
**Describe the bug**
When using iPython.Display HTML in Jupyter Lab code, the target attribute in hyperlinks is being overwritten with "_self" or"_blank" 

**To Reproduce**

1. Open a new Jupyter Labs notebook with a Python3 kernel
2. enter and run
```python3
from IPython.display import HTML, display
sampleHtml = '<a target="jupyter_docs" href = "https://jupyterlab.readthedocs.io/en/stable/">Jupyter Docs</a>'
display(HTML(sampleHtml))
```
3. The following link is created
```python3
<a target="_blank" href="https://jupyterlab.readthedocs.io/en/stable/" rel="noopener">Jupyter Docs</a>
```

**Expected behavior**
The link should be
```python3
<a target="jupyter_docs" href="https://jupyterlab.readthedocs.io/en/stable/" rel="noopener">Jupyter Docs</a>
```

**Desktop (please complete the following information):**

- OS: macOS Sierra 10.12
- Browser chrome 75.0
- JupyterLab 1.0.0

**Additional context**
I'm not familiar enough with the Jupyter Lab code architecture to debug this but there is code in packages/rendermime/src/renderers.ts which looks like it might cause this problem.

```python3
if (isLocal) {
        el.target = '_self';
      } else {
        el.target = '_blank';
        el.rel = 'noopener';
      }
```
The HTML spec specifies that target allows values that are [valid browsing context names or keywords](https://html.spec.whatwg.org/multipage/browsers.html#valid-browsing-context-name-or-keyword) which in practice means _blank, _self, _parent, _top, or anything else that does not start with a _.

**Comment by ian-r-rose** [comment]
Hi @michaele4321, the adding of `_blank` to links is deliberate (as you note by linking to the code). We want external links to open in a new tab.  May I ask the reason for adding a browsing context manually?

That said, I think it is reasonable for us to *not* override the `target` if the user has explicitly added the attribute to a link. I think adding that check would be a reasonable fix for a new contributor. One would go to this part of the code where we add the `_blank` target, and check to see if the element *already* has a `target` attribute: https://github.com/jupyterlab/jupyterlab/blob/079115dd36705f11067ebfd9c34f783719f1775a/packages/rendermime/src/renderers.ts#L600-L605
One would then not override the `target` attribute if it was already specified.

**Comment by michaele4321** [comment]
Hi @ian-r-rose, thanks for looking at this. The context is that I am generating an HTML table of data with each row linked to an external page. I want to use a named target so that each link opens in the _same_ external page (in my case on a second screen) rather than opening multiple new tabs.

**Comment by ian-r-rose** [comment]
Interesting, thanks for sharing @michaele4321!

**Comment by kavishdahekar** [comment]
I'd like to take this issue up.

**Comment by blink1073** [comment]
Great, thanks @kavishdahekar!

**Comment by kavishdahekar** [comment]
Unable to add reviewers for PR #7215 .
@ian-r-rose , @blink1073 could any of you please take a look? Thanks.
