### ISSUE TITLE
Downloading HTML or Image file does not force download, opens file instead

### ISSUE THREAD

**Issue by kevmk04** [jupyterlab/jupyterlab#6829]
**Describe the bug**
When attempting to download an html file (.html) or an image file (.png, .jpeg, etc) using the context menu (<Right click> + Download) from the file manager, the file is opened in a new tab by Chrome and not downloaded.  I suspect that any file that Chrome can render will exhibit this behavior. 

The behavior in Firefox is similar.  Firefox will also try to open the file but unlike Chrome it prompts the user with the option to save or open the file.  See screen shot below of the prompt Firefox presents to the user. 

Previously reported in #6525 but is not resolved in version 1.0.2.  

**To Reproduce**
Steps to reproduce the behavior (in Chrome):

1. Create or upload any html or image file to the file browser
2. Right click on the file and select Download
4. See new tab open with file displayed 

**Expected behavior**
The file downloads directly to the local machine. 

**Desktop Information:**

- OS: Windows 10
- Browser:  Chrome -- 75.0.3770.100 (Official Build) (64-bit)
                   Firefox -- 68.0 (64-bit)
- JupyterLab:  1.0.2

**FireFox ScreenShot**
![60908191-82edc680-a238-11e9-8430-96772c4a6ba1](https://user-images.githubusercontent.com/38329905/61223746-840c7100-a6da-11e9-84d2-7c3e3b575b8b.png)

**Comment by ian-r-rose** [comment]
It's possible that this will be fixed by #6686. We should revisit this once that fix is in.

**Comment by ian-r-rose** [comment]
Thanks for the report @kevmk04

**Comment by jwclark** [comment]
When attempting to download .ipynb files I also see the raw json contents in a new tab in place of a download prompt.

**Comment by jasongrout** [comment]
The bugfix is in 1.0.5 (out on pypi now, soon up on conda-forge). Can you check with 1.0.5?

**Comment by kevmk04** [comment]
1.0.5 appears to fix the issue! Nice work! I tried a few different file types and all are working properly.
