### ISSUE TITLE
It is not possible to close the console.

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#683]

**Comment by jasongrout** [comment]
For me, clicking on the X to close on a console brings up a "Shut down kernel" dialog. If I click OK, it pauses for a second or two and then closes the widget. What happens for you?

**Comment by akosyakov** [comment]
@jasongrout actually I see errors in the console, could you try to close then a kernel is already shutdown and check the console.

**Comment by akosyakov** [comment]
@jasongrout the same for the notebook, if open one without running kernel, then i see errors in the log, but in this case it does not harm so much

**Comment by eskirk** [comment]
I can't seem to replicate this :/ My console shuts down immediately upon clicking 'Ok'. Strange... I do know the issue you are talking about but I think it may have been fixed? Can anyone else confirm?

**Comment by akosyakov** [comment]
@eskirk it is another way to shutdown the kernel outside the console? and then try to open and close the console?

**Comment by jasongrout** [comment]
I replicated it:
![console](https://cloud.githubusercontent.com/assets/192614/17944675/b29efbfc-6a0e-11e6-967d-d640c512e8b0.gif)

I also saw an error in the server output:

> 410 DELETE /api/sessions/492b165e-75ee-4fe1-a719-c0feae0aae9c?1472066533075

**Comment by jasongrout** [comment]
CC @afshin

**Comment by blink1073** [comment]
This was fixed by #1107.
