### ISSUE TITLE
Keyboard shortcuts should be completely disable-able

### ISSUE THREAD

**Issue by chbrown** [jupyterlab/jupyterlab#6830]
**Bug:** I cannot disable keyboard shortcuts that Jupyter Lab (/ Notebook) and/or CodeMirror intercepts, preventing the browser from handling them upstream.

_In most cases, Jupyter's handling is what I'd prefer, but I'd like the customizability to override it when I desire some other behavior._

#### Steps to reproduce the behavior
1. Go to 'Settings' -> 'Keyboard Shortcuts'
2. Follow the instructions (thanks to @jasongrout for pointing these out on https://github.com/jupyterlab/jupyterlab/issues/6756#issuecomment-510928460 😄) for disabling a keyboard shortcut (add the following to the "User Preferences" pane):
```json
        {
            "command": "documentsearch:start",
            "keys": [
                "Accel F"
            ],
            "selector": ".jp-mod-searchable",
            "disabled": true
        },
```
3. Go back to a notebook
4. Edit a cell
5. While in edit mode, type **⌘F**
6. Note that the "find" panel opens inside the cell, and searches only that cell
7. Go back to 'Settings' and try various other things to disable that keyboard shortcut
8. Bemoan the fact that none of those attempts affect the behavior described in `6.`

#### Expected behavior
When I disable a keyboard shortcut, it should be completely ignored, allowing it to percolate upward and for the browser to handle it (if relevant). Right now, my workaround is to hit ⌘L first (Chrome shortcut to edit URL, which Jupyter/CodeMirror does not intercept), to take away the webpage's focus, and give it to the browser UI, and _then_ hit ⌘F, which 

#### Screenshots
New Jupyter Lab `1.0.*` full-notebook search-and-replace:
<img width="757" alt="Screen Shot 2019-07-15 at 11 09 33 AM" src="https://user-images.githubusercontent.com/360279/61226863-3ea76e00-a6f1-11e9-937a-b6e2222d2d0a.png">
That's disable-able, but the within-cell search is not:
<img width="759" alt="Screen Shot 2019-07-15 at 11 10 32 AM" src="https://user-images.githubusercontent.com/360279/61226873-423af500-a6f1-11e9-9b4b-fba257cd7ce0.png">
Workaround described above in "Expected behavior":
<img width="760" alt="Screen Shot 2019-07-15 at 11 22 55 AM" src="https://user-images.githubusercontent.com/360279/61227829-0ef96580-a6f3-11e9-89de-cf65cc75110f.png">

#### Environment
- OS: macOS 10.14.5
- Browser: Google Chrome 75.0
- JupyterLab: 1.0.2 (I've observed this issue in all versions `>=1.0` that I've used)

**Comment by jasongrout** [comment]
I think the codemirror behavior is that Ctrl/Cmd F opens the search, and then pressing Ctrl/Cmd F *again* exits the search and passes the search on to the browser. Can you try hitting Cmd F twice?

**Comment by chbrown** [comment]
Oh right, I forgot about that workaround, which I used in Jupyter Notebook (pre-Lab). Yeah, that drops back to the browser's built-in search... but it still throws off my muscle-memory / mental model of what happens when I hit "Cmd F" (once!) in most interfaces :(

**Comment by LoudeNOUGH** [comment]
> I think the codemirror behavior is that Ctrl/Cmd F opens the search, and then pressing Ctrl/Cmd F _again_ exits the search and passes the search on to the browser. Can you try hitting Cmd F twice?

Sorry, but a double combination doesn't work for Safari: it seems there is no possible way to use Safari search instead of lagging lab search. Thus, heavy plus to the issue.

**Comment by jasongrout** [comment]
> Sorry, but a double combination doesn't work for Safari

It does for me. You have to first disable the jlab find and replace as noted in the original issue description above.

**Comment by LoudeNOUGH** [comment]
@jasongrout Thanks a lot, should have figured it our by myself.

**Comment by LoudeNOUGH** [comment]
After relaunch you need only one press of Cmd/Ctrl + F to toggle a browser search, so the shortcut turns off completely after relaunch

**Comment by chbrown** [comment]
> After relaunch you need only one press of Cmd/Ctrl + F to toggle a browser search, so the shortcut turns off completely after relaunch

Oooh, even when you're currently editing a code cell? (I might have to give Safari a try!)

**Comment by AnakTeka** [comment]
> I think the codemirror behavior is that Ctrl/Cmd F opens the search, and then pressing Ctrl/Cmd F _again_ exits the search and passes the search on to the browser. Can you try hitting Cmd F twice?

This does not work on linux with Chromium

**Comment by chbrown** [comment]
Another headache: **⌘G** ("find next") silently fails (does nothing) if the webpage has focus, no matter how many times I hit it 😠. I had to add the following override in "Settings" -> "Keyboard Shortcuts":
```json
        {
            "command": "documentsearch:highlightNext",
            "keys": [
                "Accel G"
            ],
            "selector": ".jp-mod-searchable",
            "disabled": true
        },
```
...and then use one of the workarounds mentioned above. I.e., if you're editing a cell, double-tap **⌘G** to drop back to the browser's "find next".

**Comment by jasongrout** [comment]
> This does not work on linux with Chromium

@AnakTeka - make sure you're first disabling the jlab search following the steps in the OP.

**Comment by fenghse** [comment]
CTRL+B cannot be disabled in my case.

**Comment by jasongrout** [comment]
Thanks for updating us!

I think everyone's issues above have been resolved at this point.

**Comment by fenghse** [comment]
> `CTRL+B` cannot be disabled in my case. I need to send `CTRL+B` to make the terminal working with tmux, thank you so much for any ideas.
