### ISSUE TITLE
Feature Request: Enable quick ways to maximize/restore terminals

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#6842]
Is there any way (shortcuts, buttons) to quickly maximize a terminal and reset its size/resolution? For example, is there anyway to quickly maximize Terminal 5 in the screenshot below instead of using mouse to drag to change its size/resolution? If not, it would be great if this is supported (similar to what people can do in ITerm2 on Mac).

![image](https://user-images.githubusercontent.com/824507/61594720-df8ba280-aba3-11e9-8d0b-57aad94d28d9.png)

**Comment by ian-r-rose** [comment]
Hi @dclong, does calling the command `"terminal:refresh"` work for what you need? I was able to assign a keyboard shortcut with the following in the advanced settings editor --> keyboard shortcuts:
```javascript
{
       "shortcuts": [
        {
            command: "terminal:refresh",
            keys: ["Accel Y"],
            selector: ".jp-Terminal"
        }
    ]

}
```

**Comment by dclong** [comment]
@ian-r-rose I don't think this is what I need. `terminal:refresh` refreshes a terminal but what I want is to maximize a terminal and then be able to reset its size/resolution using shortcuts. Sorry for the confusion. I've updated the description of the issue.

**Comment by ian-r-rose** [comment]
Ah, I see. I think you may find "Single Document Mode" the feature you want. By default, this is assigned to the keyboard shortcut `Accel Shift D`, and it maximizes the currently active widget.

**Comment by dclong** [comment]
@ian-r-rose This is exactly what I was looking for! Cannot believe I don't know this extremely useful feature already exists.
