### ISSUE TITLE
Commands to run this repository on local machine and directory location.

### ISSUE THREAD

**Issue by suniljadhav01** [jupyterlab/jupyterlab#6848]
Hi,
I am new to jupyter lab.
I need the commands to run this repository on my local machine and exact directory location where to execute them.
I want to do some changes in the current repository and need to check them on local machine.
Is this possible ?
what will be exact process I have to follow to run this on my machine ?
Thanks !

**Comment by ian-r-rose** [comment]
Hi @suniljadhav01, you can set up a local development environment by following the [contributor guide](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#setting-up-a-development-environment).

Closing as answered, happy coding!
