### ISSUE TITLE
Kernel name changes in the statusbar

### ISSUE THREAD

**Issue by cnydw** [jupyterlab/jupyterlab#6850]
**Kernel name changes in the statusbar**
After an IPython notebook is opened, the statusbar shows the kernel name "Python3", then if I switch to another tab and switch back, the kernel name becomes "Python 3"

**Expected behavior**
The statusbar always shows the `display_name` in the metadata of the notebook, instead of 
first showing the `name`, then showing the `display_name`.

**Screenshots**
After the notebook is opened
![image](https://user-images.githubusercontent.com/10969537/61453499-8979ed80-a95e-11e9-94cd-f7f362f18e2f.png)
After switch to another tab and switch back
![image](https://user-images.githubusercontent.com/10969537/61453524-a1ea0800-a95e-11e9-91a6-adf668029825.png)
Notebook metadata
![image](https://user-images.githubusercontent.com/10969537/61453693-25a3f480-a95f-11e9-9363-e6845203447f.png)

**Comment by telamonian** [comment]
Should be fixed in #6852
