### ISSUE TITLE
Inconsistent capitalization of kernel name in statusbar

### ISSUE THREAD

**Issue by cnydw** [jupyterlab/jupyterlab#6851]
**The capitalization of kernel name in statusbar is inconsistent**
The kernel name in the statusbar has the first letters capitalized, while the kernel name in other places don't.

**To Reproduce**

1. Create a new kernel or modify the current kernel.json, such that in the kernel.json, `"display_name": "python 3 dev1"`
2. Reload jupyterlab
3. Create a new notebook with the kernel
4. Switch to another tab, then switch back, to see the `display_name`. (needed because of #6850) 

**Expected behavior**
A consistent capitalization rule of kernel names in jupyterlab.

**Screenshots**
- kernel name in the launcher
![image](https://user-images.githubusercontent.com/10969537/61454250-a7e0e880-a960-11e9-86a7-a3e5a53aff89.png)
- kernel name in the notebook toolbar
![image](https://user-images.githubusercontent.com/10969537/61454269-b9c28b80-a960-11e9-8bd0-150195de08d3.png)
- kernel name in the statusbar, with the first letters **CAPITALIZED**
![image](https://user-images.githubusercontent.com/10969537/61454314-d959b400-a960-11e9-9d63-2a7ca731cd7a.png)

**Comment by telamonian** [comment]
fixed in #6852
