### ISSUE TITLE
Re-publish vega4-extension

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#6856]
An accidental publish of `@jupyterlab/vega4-extension` from `jupyter-renderers` is shadowing the version of the package that we actually want published (which does the precompilation step). We need to delete that package from the `jupyter-renderers` package, and republish a version from this repo.

cf https://github.com/jupyterlab/jupyter-renderers/pull/209

cc @saulshanabrook

**Comment by jasongrout** [comment]
We could just deprecate the wrong version, and reset the latest tag on npm. No need to republish a version from here.

**Comment by jasongrout** [comment]
(We still need to delete the package from jupyter-renderers, of course)

**Comment by ian-r-rose** [comment]
Good point

**Comment by saulshanabrook** [comment]
I think a new one will be published for 1.0.3 anyway since this commit went in https://github.com/jupyterlab/jupyterlab/commit/fd28d0a122df212a10dd2ef5721473cf1e54dc87

**Comment by jasongrout** [comment]
We still want to deprecate the other one published.

**Comment by jasongrout** [comment]
I deprecated 1.0.1 and put the npm latest tag on 1.0.0:

```
% npm dist-tag ls @jupyterlab/vega4-extension                                                                                                                               
latest: 1.0.0
```
