### ISSUE TITLE
Code blocks in markdown cells not rendering

### ISSUE THREAD

**Issue by kdeleeuw11** [jupyterlab/jupyterlab#6861]
Hi! Thanks for using JupyterLab.

If you are reporting an issue with JupyterLab, please use the [GitHub issue](https://github.com/jupyterlab/jupyterlab/issues) search feature to check if your issue has been asked already. If it has, please add your comments to the existing issue.

The JupyterLab team and Project Jupyter value our community, and JupyterLab
follows the Jupyter [Community Guides](https://jupyter.readthedocs.io/en/latest/community/content-community.html).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser [e.g. chrome 69.0, firefox 62.0]
- JupyterLab [e.g. 0.34.2]

**Additional context**

If available, please include the following details:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser console here.
</pre>
</details>

**Comment by kdeleeuw11** [comment]
Today I found that when entering a code block in a markdown cell in JupyterLab, it doesn't render properly. It has been working in the past. When opening the notebook in the classic notebook, it works fine.

Below some screenshots to illustrate the issue:
Enter the code in the notebook in JupyterLab
![fig1](https://user-images.githubusercontent.com/9377284/61586003-5a0cf000-abad-11e9-89cb-d4c21fd9e014.png)
After executing the cell:
![fig2](https://user-images.githubusercontent.com/9377284/61586011-7e68cc80-abad-11e9-8037-ce616960bd96.png)
Opening the notebook in the classic notebook:
![fig3](https://user-images.githubusercontent.com/9377284/61586015-950f2380-abad-11e9-9877-78fbc19bf8f4.png)

**Comment by kdeleeuw11** [comment]
Forgot to mention that I am using JupyterLab 1.0.2

**Comment by kdeleeuw11** [comment]
I did some further testing. In the first place I tested whether it was a Google Chrome issue, the browser I am normally using. I tested the notebook in Safari and got the same result. I then tested a markdown file and when I access the Markdown Preview, it works fine. So it seems to be just a notebook issue in JupyterLab

**Comment by jtpio** [comment]
@kdeleeuw11 thanks for the report.

How about placing the last 3 backticks on the next new line, like this:

![image](https://user-images.githubusercontent.com/591645/61994494-48c75600-b07b-11e9-95da-f676a7a0cd6d.png)

Would that work for you?

**Comment by kdeleeuw11** [comment]
Yes that works. I usually put the last 3 backticks at the end of the last line of the code and that stopped working. But now it is fine. Thanks.

**Comment by jtpio** [comment]
Thanks @kdeleeuw11 for checking that.

As a side note, the GitHub markdown renderer also doesn't render this example properly when the 3 backticks are on the same line (the backticks show up)
So the fact that it works with the classic notebook might be a side effect.

Closing as answered!
