### ISSUE TITLE
download notebook from menu

### ISSUE THREAD

**Issue by lheagy** [jupyterlab/jupyterlab#6868]
Just a quick usability note: I am running a notebook on the NERSC deployment and wanted to download it to test out some things locally on my machine - finding the mechanism for downloading a notebook is challenging. The only place I could see was in the file-navigator (but I had navigated to a different directory to look at something else.. so it took me a bit to find the directory with the notebook again), it would be nice if in "File" there was an option to "download" or similarly, in the toolbar at the top of a notebook if a download icon would allow you to download it.

**Comment by jasongrout** [comment]
+1 to a file menu option. Great idea!

**Comment by PalAditya** [comment]
Hi, I like this idea. Would it be possible for me to work on it?

**Comment by acarl005** [comment]
I put in a PR for this #7480

**Comment by vidartf** [comment]
Fixed in #7480?

**Comment by tgeorgeux** [comment]
Closed via 7480
