### ISSUE TITLE
Extend the Running Sidebar

### ISSUE THREAD

**Issue by Queuecumber** [jupyterlab/jupyterlab#6876]
I'm currently doing some work on https://github.com/chaoleili/jupyterlab_tensorboard and one thing that we want to add is a list of running tensorboard sessions to the running sidebar. Currently, the hack to make this work is to add a new tab the the sidebar just for managing tensorboards. This is kind of ugly and redundant when there is already a panel for it. What we want to add isnt a kernel or terminal so it doesn't fit in cleanly. I can't seem to find an extension API for adding a new section to the running sidebar, is there one? If not can this be a feature request to add one?

**Comment by Madhu94** [comment]
Does [this](https://github.com/jupyterlab/jupyterlab/blob/cd5e119902ac1471c232af3a05e13b6c94470a4a/packages/application/src/shell.ts#L500) API help? You can choose any of [these](https://github.com/jupyterlab/jupyterlab/blob/cd5e119902ac1471c232af3a05e13b6c94470a4a/packages/application/src/shell.ts#L80) options

**Comment by Queuecumber** [comment]
I'm not entirely sure but that looks like an API to add new panels, we are looking to add something new to the existing running panel (the one that list "terminal sessions" and "kernel sessions")

**Comment by jasongrout** [comment]
Is https://github.com/jupyterlab/jupyterlab/pull/6002 helpful? We didn't get it in 1.0, but it's in the queue to be reviewed.

**Comment by Queuecumber** [comment]
yup looks like exactly what I want, I can look into reviving that PR since its been a few months since that guy said anything
