### ISSUE TITLE
conda installs 1.0.2 but jupyterlab still stuck at 0.32.1

### ISSUE THREAD

**Issue by mayadebellis** [jupyterlab/jupyterlab#6877]
Hi I am trying to update to the new version of JupyterLab. Creating a new conda environment and running `conda install -c conda-forge jupyterlab` I get the results 

```
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                1.0.2                    py36_0    conda-forge
jupyterlab_server         1.0.0                      py_1    conda-forge 
notebook                  6.0.0                    py36_0    conda-forge
```

Which looks ok to me. But when I check `jupyter lab --version` I get `0.32.1`.  When I run `jupyter lab` it launches `0.32.1`.

In my other, older conda env I am running jupyterlab version 0.35.4.

I am running on a macOS High Sierra, conda version 4.3.27. Has anyone else run into this issue/understand why this is happening? 

I see a similar issue here: https://github.com/jupyterlab/jupyterlab/issues/6784. But this issue has been closed and there doesn't seem to be a conda solution.

Thanks!

**Comment by jasongrout** [comment]
My guess is that at some time your environment was messed up, perhaps by pip installing JupyterLab or something. I would suggest starting with a clean environment, or if you can't do that, uninstalling JLab in every way (conda, pip, etc.), then installing again.

**Comment by mayadebellis** [comment]
Thank you! Yes I found some old pip versions inside the environment. Just uninstalling them fixed my issue.
