### ISSUE TITLE
Can't open terminal

### ISSUE THREAD

**Issue by daejong123** [jupyterlab/jupyterlab#6880]
Dear developers, I found that I can not open the terminal.
my jlab env:
1. windows 7
2. jlab: 1.0.2
3. chrome

error is as follows:
![image](https://user-images.githubusercontent.com/19252403/61772630-51265380-ae25-11e9-9122-e03a3d08b167.png)

**Comment by jasongrout** [comment]
Can you paste the error message from the server log?

**Comment by jasongrout** [comment]
Closing since the author did not follow up. Please comment here if you'd like to continue the discussion.
