### ISSUE TITLE
Is it possible to add a keyboard shortcut for jupyterlab theme switch?

### ISSUE THREAD

**Issue by tbrodbeck** [jupyterlab/jupyterlab#6883]
I would like to have a keyboard shortcut to toggle from light to dark theme and back in jupyterlab. Is this possible?

I tried this in my User Preferences but it does not seem to work:
```
        {
            "command": "apputils:change-theme",
            "keys": [
                "Alt T"
            ],
            "selector": ".jp-Notebook:focus"
        },

        {
            "command": "apputils:change-theme",
            "keys": [
                "Alt T"
            ],
            "selector": ".jp-Notebook.jp-mod-editMode"
        },
```

**Comment by jtpio** [comment]
@tbrodbeck there can be more than 2 themes in JupyterLab (from third-party extensions), so toggling between light and dark could be a bit tricky to achieve.

In the meantime maybe you can have a look at the [theme toggle extension](https://github.com/jtpio/jupyterlab-theme-toggle) which exposes such shortcut.

**Comment by tbrodbeck** [comment]
Oh yeah this is actually a nice solution (besides having this visual switch, but it does not mind me too much). Thanks!

> there can be more than 2 themes in JupyterLab (from third-party extensions), so toggling between light and dark could be a bit tricky to achieve.

If you have more than 2 you could simply cycle through them

>

**Comment by jtpio** [comment]
Closing as answered, since there is for now an alternative way to achieve this.

Feel free to reopen if you want to discuss it more.

**Comment by vidartf** [comment]
> Feel free to reopen if you want to discuss it more.

Correction: Feel free to comment further if you want to reopen, and a collaborator can reopen it (GH prevents reopening issues closed by collaborators)
