### ISSUE TITLE
ggpubr

### ISSUE THREAD

**Issue by dawndaras** [jupyterlab/jupyterlab#6887]
R library ggpubr is not installed and I could not install it

**Comment by jasongrout** [comment]
That would be an R issue, not a JupyterLab issue. Perhaps you can look in the R documentation for how to install an R library?

**Comment by jasongrout** [comment]
(Or perhaps https://github.com/kassambara/ggpubr is a better place to open an issue about that library)

**Comment by dawndaras** [comment]
I tried installing an R library as I did in my laptop and it said it was not supported

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jasongrout** [comment]
Again, I would suggest posting to the ggpubr repo. We don't know anything about it here, as this repo is for JupyterLab.

**Comment by dawndaras** [comment]
I’m in JupyterLab for Microsoft

**Comment by dawndaras** [comment]
Actually that github link might have done it!
Thank you 😊
