### ISSUE TITLE
[Feature Request] Single-cell find-replace-all

### ISSUE THREAD

**Issue by austinmw** [jupyterlab/jupyterlab#6888]
From what I've been told there's currently no single-cell find-replace-all option. To do this I need to go to help->launch classic notebook. In the classic notebook, the cell find/replace command is 'F', which would be great to have in jupyterlab. 

This would also be beneficial because, while full-page find/replace is slow on large notebooks, in many cases users are only interested in the cell they're working in.

**Comment by jasongrout** [comment]
I think it would be great to have the standard find and replace have a separate "scope" dropdown that lets you decide the scope of the search. For a notebook it could be "cell" or "document". For a map it could be "viewport" or "map". For a text file it could be "paragraph" or "document". For a markdown it might be even more intelligent like "section" or "document".

**Comment by jasongrout** [comment]
And then have that scope be an argument to the command, so you could tie a keybinding to a specific scope.

**Comment by slsongge** [comment]
@austinbrian Hi! How do you implement this option(single-cell find-replace-all) now?

**Comment by austinmw** [comment]
@slsongge I open jupyter notebook instead :(

**Comment by rdrussotto** [comment]
This feature already seems to exist, but only works in certain browsers/OSes. I have been running JupyterLab on a remote server and accessing it in Chrome on Windows for some time, and I can do this by typing ctrl+shift+R. This brings up a line in the top of the cell where you type what to search for, then what to replace it with, and it automatically replaces all instances in that cell only. 

But when I access the same server using a Mac, this shortcut does not work, and the most logical alternative, command+shift+R, refreshes the entire browser window. If the shortcut exists it is being overridden by the browser shortcut. On Chrome on Mac for this server, there is no find and replace option that works at all, with find in the top menu grayed out, and on Safari I can use the global find and replace function but not the version for the single cell. 

I've been relying on this shortcut for a while and I would like to see it working on a Mac. I am surprised that I cannot find descriptions of it anywhere in the documentation. Could it have been included in JupyterLab by accident, building on the underlying packages?

Also relevant issues: #2017, #8937. Maybe a separate issue should be created for this?

**Comment by jasongrout** [comment]
> Also relevant issues: #2017, #8937. Maybe a separate issue should be created for this?

Yes, please create a separate issue for the keyboard shortcut issue.

**Comment by jasongrout** [comment]
Find and replace in a single cell is being tracked at #2017 - let's move discussion there.
