### ISSUE TITLE
Remove dependency on third-party library for `ui-components`

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#6890]
Based on work that we did for JupyterLab 1.0 and for accessibility, my
sense right now is that using an existing, general purpose UI toolkit
won't solve our problems. Here is what we are seeing:

* Accessibility isn't a fundamental property of a UI toolkit, but a
relationship between the UI components and the overall application.
What I mean by this is that simple adopting Material UI or Blueprint
doesn't make JupyterLab accessible - even if those toolkits are
accessible as possible. Example: Blueprint has well designed
accessible buttons, but they use an exterior offset border to indicate
focus that doesn't work in many contexts where JupyterLab buttons are
in tight layouts and those outlines are cut off by overflow: hidden.
* Complexity. It is orders of magnitude more complex to build/use a
general purpose UI component versus building a UI component that does
just what we need it to. The general purpose nature of these UI
toolkits means that each object has dozens of props, children, styling
options. We don't need to be able to render an exponential number of
buttons - a very small, with a small number of props will do.
* Bugs. The complexity leads to bugs and accessibility problems. With
highly flexible and general components, it becomes easy to use them in
a way that disrupts accessibility or creates bugs. Example: right now,
we are (mis)-using Blueprint buttons by shoving the Icon into the
wrong place, leading to an awkward DOM hierarchy that will likely
cause accessibility problems. This happened even though the person
using Blueprint is one of the most experienced react.js devs in the
project. It is caused by the APIs being overly flexible and complex.
* Difficulty of theming. The reliance on statically compiled themes is
a huge problem for us, as we need to re-theme dynamically (we use
custom CSS properties, but that is an implementation detail).
* Decoupling: the reliance on traditional CSS is killing us, as it is
creating hidden dependencies between packages that make it easy for us
to break one thing while trying to fix another in a separate package.
We haven't decided on which CSS in JS framework we will use, but I
don't see any way we can not have this. This is maybe a softer
requirement in that Material UI and Blueprint may be compatible with
this.

_Originally posted by @ellisonbg in https://github.com/jupyterlab/jupyterlab/pull/6828#issuecomment-513887853_

So from there, the direction for the core packages tends towards building the minimal set of UI components needed. And therefore extension authors should be aware that blueprintjs shipped with the core packages will likely be removed in the future. And so if they need an UI toolkit, they should not choose blueprintjs just because its currently included.

If we move forward with this plan, it would need to be in a major (API breaking release), but that is the idea.

**Comment by vidartf** [comment]
Dev meeting discussion related to this here: https://github.com/jupyterlab/jupyterlab/issues/7574
