### ISSUE TITLE
Invisible cursor on 1.0.2

### ISSUE THREAD

**Issue by czrcbl** [jupyterlab/jupyterlab#6894]
Hi,

I updated to version 1.0.2 and the typing cursor is invisible. I have tested light and dark themes and also tested in two different environments. I am using anaconda on Ubuntu 19.04.
Downgrading to 0.35.6 solves the problem.

**Comment by jasongrout** [comment]
What is your browser, OS, and browser zoom level?

**Comment by jasongrout** [comment]
And what document types are you seeing this in? Markdown? Code? Text documents? Notebooks?

**Comment by czrcbl** [comment]
I was using Brave Browser, on Ubuntu 19.04, I think I was using default zoom level.
I saw this problem on a Python Notebook.
I will create a new environment and test on the other browsers.

**Comment by Akoopie** [comment]
I'm also experiencing the same issue. Cursor only appears on light theme, invisible in dark theme (all document types). Fixes from #4101 did not help.

**Comment by czrcbl** [comment]
I tested it again. The problem is happening only o dark theme (Brave Browser and Ubuntu 19.04).

**Comment by jasongrout** [comment]
Is it only happening on Brave? (Note that Brave is not an officially supported browser for us, but it would still be great if it works, of course)

**Comment by czrcbl** [comment]
I did not know that Brave was not supported, since it is chromium based I thought it would work the same.
I tested on Chrome, Chromium and Firefox. The problems seems to be happening only on Brave.
Thank you. I will use a supported browser now on.

**Comment by jasongrout** [comment]
Supported browsers are listed at https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#supported-browsers

Feel free to help us figure out what is happening in Brave if you'd like to pursue this further. I'm a bit surprised it doesn't work as well. Alternatively, it sounds like you could create an issue in the Brave browser for this.

**Comment by jasongrout** [comment]
Closing as resolved, but feel free to reopen if you'd like to debug what is happening in Brave.

**Comment by czrcbl** [comment]
Now it is happening on Firefox and working normally on Brave. I cannot get the pattern.
