### ISSUE TITLE
[Feature Request] Ability to save recently used folders in explorer

### ISSUE THREAD

**Issue by Nick-Hemenway** [jupyterlab/jupyterlab#6897]
When working on multiple projects at a time in Jupyterlab, I find myself having to regularly navigate back and forth in Jupyter's file explorer. It would be nice if there was an option to save select folders to appear in a quick access submenu of the file explorer so that it is easier to quickly access commonly used directories.

**Comment by jasongrout** [comment]
See https://github.com/jupyterlab/jupyterlab/issues/2043 and in particular https://github.com/jupyterlab/jupyterlab/issues/2043#issuecomment-514858972 for discussion about these.

**Comment by Nick-Hemenway** [comment]
Thank you @jasongrout , I am glad to see that this has been discussed at length and look forward to this being available!

**Comment by jasongrout** [comment]
Note that the comment linked above points to an extension you can install which will do this. CC @tslaton

**Comment by jasongrout** [comment]
So...should we close this as resolved (with @tslaton's extension), or keep it around as a feature request for an eventual file browser overhaul?

**Comment by Nick-Hemenway** [comment]
I think that the issue can be closed.
