### ISSUE TITLE
#6841 broke the filebrowser w.r.t. directories

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#6898]
In the latest build of master, the filebrowser is broken. You can't navigate to more than one level of directory by double clicking. For example, if I try to navigate to `git/jupyterlab` by first double clicking on `git` and then double clicking on `jupyterlab`, I get this error message:

![image](https://user-images.githubusercontent.com/2263641/61894605-cdc93880-aede-11e9-85bb-45eff418e35e.png)

Reverting this line from #6841 to `item.name` fixes it:

https://github.com/jupyterlab/jupyterlab/blob/cf8a33f597f258473c2ef541d0f9b8e608d5a4cd/packages/filebrowser/src/listing.ts#L925

**Comment by jasongrout** [comment]
> In the latest build of master, the filebrowser is broken

Confirmed for me as well.

**Comment by jasongrout** [comment]
I think the real problem is faulty normalization in the cd command: https://github.com/jupyterlab/jupyterlab/blob/44e7eab2c418b533296778e0904f0769b6446c72/packages/filebrowser/src/model.ts#L244

**Comment by jasongrout** [comment]
CC @afshin

**Comment by jasongrout** [comment]
Actually, it looks like `item.path` explicitly does not include the leading slash, and `model.cd` assumes a relative path (i.e., normalizing with respect to the current `model` path). So perhaps we could either do `'/'+item.path`, or switch back to `item.name` (CC @afshin for that, though)

**Comment by telamonian** [comment]
Yep, I'm trying to sort out a fix. The crux of the issue is that `cd` (which calls `normalizePath`)  expects a relative path w.r.t. the current path of the browser, and we're currently handing it an "absolute" path (absolute w.r.t).

> So perhaps we could either do `'/'+item.path`

I'm currently trying to figure out how to do just that. It's a bit awkward though from the perspective of someone currently trying to develop a custom filebrowser plugin. I think it might be better if each `Contents.IDrive` supplied it's own path normalization/resolution function, or if we got rid of that step entirely.

**Comment by jasongrout** [comment]
This works for me:
```patch
diff --git a/packages/filebrowser/src/listing.ts b/packages/filebrowser/src/listing.ts
index 224149c1f..86e9d4ded 100644
--- a/packages/filebrowser/src/listing.ts
+++ b/packages/filebrowser/src/listing.ts
@@ -922,7 +922,7 @@ export class DirListing extends Widget {
     this._onItemOpened.emit(item);
     if (item.type === 'directory') {
       this._model
-        .cd(item.path)
+        .cd(`/${item.path}`)
         .catch(error => showErrorMessage('Open directory', error));
     } else {
       let path = item.path;

```

**Comment by telamonian** [comment]
That's definitely a solution. The issue with that is that it's hard to override for a custom filebrowser. On the other hand, I'm pretty sure that ensuring that every path that gets passed to `cd` starts with `/` is the same as getting rid of `normalizePath` entirely. Which is probably good enough for my use case.

**Comment by jasongrout** [comment]
There are lots of other places that `.cd()` is called with a relative path (to go up a directory, etc.)

**Comment by jasongrout** [comment]
In general, I agree with making the distinction between names and paths that @afshin proposed in #6841.
