### ISSUE TITLE
Need UI element to go back to classic notebook

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#69]
Seem obvious to change the URI, but we literally had classed in Berkley, where student would reissue `jupyter notebook` in a new terminal each time they wanted to access the dashboard, ence having up to 50 servers running at the end of class.

**Comment by ellisonbg** [comment]
I think I understand. We need to offer a link in JupyterLab to go to the classic notebook dashboard. I fully agree that until the classic notebook is gone we need this...

**Comment by ellisonbg** [comment]
We have this in master, but it is currently broken as we are going to the wrong URL. Marking as New Contributor for hackathon today.

**Comment by blink1073** [comment]
I just tried this in master and in the v0.21.0 release and it went to the appropriate `/tree` url.

**Comment by ellisonbg** [comment]
Fixed, closing!
