### ISSUE TITLE
Enable renaming documents by clicking the filename in the tab

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#690]
We have talked about this before, but it kept coming up in user tests...

I would touch base with @sccolbert about this one...

**Comment by spoorthyv** [comment]
Hey @sccolbert what are your thoughts on this? Also how would I go about implementing this. Not sure where to even start.

**Comment by blink1073** [comment]
cf https://github.com/phosphorjs/phosphor/issues/104

**Comment by spoorthyv** [comment]
Ah. So is this not possible for now?

**Comment by blink1073** [comment]
That is correct.

**Comment by ellisonbg** [comment]
Will this eventually become possible?

Are there other approaches other than an in-tab rename, such as popping up a rename dialog that are possible?

**Comment by sccolbert** [comment]
Yes, this will eventually be possible. I'll add support for this when I add support for (re)activating a tab on click, even if it's already the current tab.

**Comment by sccolbert** [comment]
Once I put some life into the grid widget, I'll tackle these smaller ins-and-outs.

**Comment by ellisonbg** [comment]
Great, thanks!

**Comment by ellisonbg** [comment]
@sccolbert  Is this still blocked?

**Comment by blink1073** [comment]
Yes, https://github.com/phosphorjs/phosphor/issues/104 is still a blocker.

**Comment by ellisonbg** [comment]
We have decided to not go this route, closing.
