### ISSUE TITLE
Modularize FileEditor Extension code for extendibility

### ISSUE THREAD

**Issue by ajbozarth** [jupyterlab/jupyterlab#6901]
Wrapping or extending the FileEditor in an extension in order to add extra features or tools is currently not possible without copying code found in the `fileeditor-extension`'s activate function. Quite a bit of the FileEditor functionality is in that function rather than in the widget itself. I propose that we either move the functionality into the widget itself or into utility functions that could be exposed and called from a separate extension's `activate` function.

**Comment by ajbozarth** [comment]
I am unsure of which functionality to move/modularize and where it should go. I've tested pulling out (nearly) all the activate code into a single util function successfully, but when I tried to copy that util code outside jupyter lab to test in my extension code it wont build (even though it does inside JupyterLab). My hope in this issue is for discussion and guidance on how to modularize the code in the activate function, where it should go, how it should be broken up, etc. With guidance I would like to open a PR with the changes

**Comment by jasongrout** [comment]
It probably depends on which functionality we are talking about, but I imagined that it could be exported from the extension and imported in another extension.

Can we do one specific function as an example?

**Comment by ajbozarth** [comment]
My overall goal is to "extend" FileEditor without loss of any functionality. So my hope would be to include "all" of it, but some clear examples would be the `addCommand` calls, the `menu.addItem` calls, and the `palette.addItem` calls.

I can open an initial PR pulling one of those sections into a "exported" function. Would you suggest putting the function in a separate `utils.ts` file or just in the `index.ts` file?

**Comment by jasongrout** [comment]
A separate file, perhaps named more specifically than `utils`?

**Comment by ajbozarth** [comment]
ok, how does for the name maybe `extensionutils.ts` or `editorutils.ts`

**Comment by jasongrout** [comment]
or how about `commands.ts`?

**Comment by jasongrout** [comment]
One thing you'll face here is that jlab expects the extension to just export the extension datastructure, but you want to import other things besides that. Perhaps we should move the extension datastructure to `plugin.ts`, and change the `packag.json` metadata to point jupyterlab to that particular module for the extension. Then the `index.ts` file can export lots of other things that people can import and use.

So change the `package.json` `jupyterlab.extension` field from `true` to `lib/plugin`, rename the `index.ts` file to `plugin.ts`, and make a new `index.ts` file that exports from `plugin.ts` and other files what you want to import.

**Comment by jasongrout** [comment]
Or perhaps another way to do it is to export the plugin datastructure as the default export from index.ts, but also export other stuff that you could import in your package.

**Comment by ajbozarth** [comment]
ok, I'll play with that and open an initial PR that pulls out the menu section (possibly by EOD)

**Comment by ajbozarth** [comment]
@jasongrout I opened #6904 with an initial refactor based on your comments. If the refactor in that PR looks good I can follow it up with a PR pulling out further code

**Comment by akchinSTC** [comment]
@ajbozarth you can probably close this

**Comment by ajbozarth** [comment]
#6904 closes this
