### ISSUE TITLE
jupyterlab.github.io 404

### ISSUE THREAD

**Issue by jamesdbrock** [jupyterlab/jupyterlab#6906]
It looks like the GitHub Pages documentation for JupyterLab is currently offline.

https://jupyterlab.github.io/jupyterlab/index.html

> # 404
>
> There isn't a GitHub Pages site here.

**Comment by jasongrout** [comment]
You're right. We deleted that branch mistakenly when cleaning up branches. I restored it just now from a clone taken this afternoon.
