### ISSUE TITLE
Many "python interative"s on launcher

### ISSUE THREAD

**Issue by AeneasZhu** [jupyterlab/jupyterlab#6914]
![image](https://user-images.githubusercontent.com/44701446/61987540-03d6fb80-b04a-11e9-8108-20c72884ac85.png)

Why are so many "python interatives" on this launcher?

**Comment by jasongrout** [comment]
Likely there is one for each Jupyter kernel in your system. The new JupyterLab tries to do a better job of providing more space for labels for each kernel.

Run `jupyter kernelspec list` to see the registered kernels.
