### ISSUE TITLE
Terminal hasn't text in Firefox

### ISSUE THREAD

**Issue by anki-code** [jupyterlab/jupyterlab#6915]
This issue I've got after update from JupyterLab 1.0.2 to JupyterLab 1.0.4.

Terminal (ubuntu bash) looks like black window in Firefox 68.0.1:

![image](https://user-images.githubusercontent.com/1708680/61992823-ce430a00-b06b-11e9-816d-6ff5234c9147.png)

What I've tried:
* If I type any commands in the black box I see it works but without text (cursor just moves after invisible result printing).
* Reload page, reload JupyterLab, rebuild docker container, full rebuild docker container
* Switch terminal theme — no result. If I set Light the terminal looks like white window.
* Switch JupyterLab theme — no result.
* If I type `mc` and then Enter:
![image](https://user-images.githubusercontent.com/1708680/61992870-96889200-b06c-11e9-97da-3946bc546948.png)
* If I open it in the Chrome it works as expected

I haven't any special settings. This issue I've got after update from JupyterLab 1.0.2 to JupyterLab 1.0.4.

JFYI: one of my coworkers report that it catch this bug on 1.0.0 in Safari on Mac.

**Comment by anki-code** [comment]
It's unbelievable but now I see text in terminal on Firefox as expected. I did nothing for it.

**Comment by jasongrout** [comment]
Glad it's working now!

**Comment by anki-code** [comment]
@jasongrout JFYI: Maybe it looks like the issue appears after Firefox updates self in the background. I had 68.0.1 and today I've updated to 68.0.2 in the background and now I see the black terminal issue. After full restart  my Firefox the issue was resolved again.

**Comment by mirestrepo** [comment]
We see this issue in Safari as well. Changing the terminal theme to dark or light fixes the issue. I think what is happening is that the Inherit mode is displaying dark text on dark terminal...
