### ISSUE TITLE
Keyboard shortcuts are not applyed after saving.

### ISSUE THREAD

**Issue by Yurez23** [jupyterlab/jupyterlab#6916]
**Describe the bug**
When I save user settings, they do not appear in the Commands tab and do not work.

**To Reproduce**
I am entering in the User Preferences box
    
    {
           "shortcuts": [
            {
            "command": "move-cell-down",
                "keys": [
                    "Ctrl ArrowDown"
                ],
                "selector": ".jp-Notebook:focus"
            },
            {
            "command": "move-cell-up",
                "keys": [
                    "Ctrl ArrowUp"
                ],
                "selector": ".jp-Notebook:focus"
            }
        ]
    }

and then click on save user settings button.

**Expected behavior**
I expected that after saving the user preferences, I can immediately use them, but it seems that I need to apply them somehow. 

I also tried creating a new notebook and restarting the entire jupyter lab.

**Screenshots**
<img width="960" alt="jupyterlab_bug1" src="https://user-images.githubusercontent.com/32897979/61994951-cb0b4680-b08a-11e9-8485-971108ae7361.png">

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome 75.0.3770.142
- JupyterLab 1.0.2

**Comment by JohnOmernik** [comment]
I am seeing this as well. I had users running JupyterLab 0.35.5, and we upgraded to 1.0.5.   They had keyboard shortcuts as defined below that allowed JupyterLab to be like slack. (Enter ran a cell, and Shift-Enter put in a newline).  Now, not only will this code not run, but when I modify it use the newer format, nothing actually applies, and the console run keystroke menu item also does nothing.  I can't seem to change things, I don't understand the selector. Is it normal for a project to change a format like this, and provide so little documentation as to the change? 

Also, why do we have Keyboard Shortcuts under advanced settings, and yet Console Run Command is a separate first class menu item, and it's not clear which is more important?



```
  // [missing schema title]
  // [missing schema description]
  "console:linebreak": {
   "command": "console:linebreak",
   "keys": [
    "Shift Enter"
   ],
   "selector": ".jp-CodeConsole-promptCell",
   "title": "Insert Line Break",
   "category": "Console"
  },
  // [missing schema title]
  // [missing schema description]
  "console:run-forced": {
   "command": "console:run-forced",
   "keys": [
    "Enter"
   ],
   "selector": ".jp-CodeConsole-promptCell",
   "title": "Run Cell (forced)",
   "category": "Console"
  },
  // [missing schema title]
  // [missing schema description]
  "runmenu:run": {
   "command": "runmenu:run",
   "keys": [
    "Enter"
   ],
   "selector": "[data-jp-code-runner]",
   "title": "Run",
   "category": "Run Menu"
  },
  // [missing schema title]
  // [missing schema description]
  "notebook:run-cell-and-select-next": {
   "command": "notebook:run-cell-and-select-next",
   "keys": [
    "Enter"
   ],
   "selector": ".jp-Notebook.jp-mod-editMode",
   "title": "Run Cell and Select Next",
   "category": "Notebook Operations"
  }
```

**Comment by jasongrout** [comment]
@Yurez23 - the commands are active as soon as you save them. If you look in the browser javascript console, you'll likely see errors saying that the command is not registered. That's because the wrong command name is in your keyboard shortcuts (should be `notebook:move-cell-up`, etc.)

This works for me (note that I had to change the keyboard shortcut because my browser and macOS conflicted with your original keyboard shortcut):

```
{
       "shortcuts": [
        {
        "command": "notebook:move-cell-down",
            "keys": [
                "Ctrl J"
            ],
            "selector": ".jp-Notebook:focus"
        },
        {
        "command": "notebook:move-cell-up",
            "keys": [
                "Ctrl K"
            ],
            "selector": ".jp-Notebook:focus"
        }
    ]
}
```

**Comment by jasongrout** [comment]
@JohnOmernik - your issue is something different, dealing with migrating settings from 0.35. Would you mind opening a new issue? I'll respond there so we can keep this conversation here focused.

**Comment by jasongrout** [comment]
Closing as answered.
