### ISSUE TITLE
Add buttons and keyboard shortcut for zoom in/out of images

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#692]
In user tests, users had a tough time finding out how to zoom in/out of images and struggled to do this with the command palette. For now, let's add a context menu for the image plugin and keyboard shortcuts (plain, unmodified `+` and `-`)

**Comment by ellisonbg** [comment]
Once we do that, let's explore putting +/- buttons directly on top of the image that only appear when the user's mouse is over the image. See chrome's PDF viewer for an example.

**Comment by sccolbert** [comment]
Note that trapping shortcuts will require the image viewer to be updated to allow focus.

**Comment by blink1073** [comment]
It already does as part of my commit that added activation handling.

**Comment by ellisonbg** [comment]
@rnetro any update on this one?

**Comment by rnetro** [comment]
@ellisonbg, I'm stuck on adding the handlers... not quite sure how to do it.

**Comment by ellisonbg** [comment]
We have keyboard shortcuts for these and I think that is sufficient for now.
