### ISSUE TITLE
contextual help broken for R docs

### ISSUE THREAD

**Issue by rvalieris** [jupyterlab/jupyterlab#6928]
**Describe the bug**
contextual help layout looks wrong for R docs.

**To Reproduce**

1. start a new R notebook
2. open contextual help
3. type "cat"
4. look at the help panel

**Expected behavior**
correct layout

**Screenshots**
bad layout:
![screenshot](https://user-images.githubusercontent.com/6310472/62231750-0a8fa680-b39b-11e9-96bd-a49d23e0732e.png)

**Desktop (please complete the following information):**

- OS: linux
- Browser: firefox 68
- JupyterLab 1.0.4

**Additional context**
by using inspect tool of firefox I noticed that disabling "display:flex" on the help div fixes the layout issue.

**Comment by jasongrout** [comment]
What kernel are you using?

**Comment by jasongrout** [comment]
I reproduced this with the Juniper kernel. It seems that R returns help as html, which goes into a jp-RenderedHTML div. Instead of disabling flex, I also noticed that just setting `flex-direction: column` also fixed the issue.

We don't see it in python since help is returned and rendered as a jp-RenderedText.

So how come `jp-RenderedHTML` doesn't come with `flex-direction: column` automatically?

**Comment by jasongrout** [comment]
On the other hand, it is `.jp-Inspector-content` that is setting the `display: flex`, perhaps it's the thing that should be doing `flex-direction: column` (or not setting `display: flex`, like suggested above).

https://github.com/jupyterlab/jupyterlab/blob/bdf6136e67917cca364c378e145e6bdc40208fa2/packages/inspector/style/base.css#L25-L29

**Comment by jasongrout** [comment]
On the other hand, in a standard notebook `.jp-RenderedHTML` does not have `display: flex`, so perhaps we really should delete `display: flex`

**Comment by jasongrout** [comment]
@rvalieris - do you want to submit a PR deleting the display: flex line at https://github.com/jupyterlab/jupyterlab/blob/bdf6136e67917cca364c378e145e6bdc40208fa2/packages/inspector/style/base.css#L27

**Comment by rvalieris** [comment]
I am using IRKernel: https://github.com/IRkernel/IRkernel

sure I can make the PR !
