### ISSUE TITLE
Syntax highlighting error in JupyterLab 0.35.5

### ISSUE THREAD

**Issue by b-trav** [jupyterlab/jupyterlab#6939]
```
# Syntax highlighting error in JupyterLab 0.35.5

# PEP 0498 suggest that this is correct:
a = {}
a['x'] = 'x'
print(f"abc {a['x']} def")

# But Jupyter treats 'def' as a function definition (ie green)
# and erroneously auto-indents for the rest of the cell

# Here is another example
      
x = {}
x['str'] = 'should'
print(f"The words 'be red' {x['str']} be red")
print("But on my screen, they are white, and the closing parenthesis is red.")
```

- OS: Chrome OS
- Browser Chrome OS Version 75.0.3770.144 (Official Build) (64-bit)
- JupyterLab 0.35.5

**Comment by jasongrout** [comment]
Can you try in JupyterLab 1.0.4?

**Comment by b-trav** [comment]
Yes, thanks @jasongrout, upgrading fixed this issue.

As an aside, I am using conda, and upgrading is certainly not obvious for the inexperienced user.

I should probably log a separate issue for upgrading, but if you just go to the main jupyter-lab page (https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html) it simply says:
```
conda install -c conda-forge jupyterlab
```
which does not upgrade, if you already have jupyterlab. This command also doesn't work:
```
conda update jupyterlab
```
This command finally worked for me:
```
conda update --all
```
But this only got me to jupyterlab 1.0.2. I have no idea how to get to 1.0.4.

**Comment by jasongrout** [comment]
`conda update jupyterlab -c conda-forge` may work to get to 1.0.4 - that will use the conda-forge channel. 

I think the anaconda channel only has 1.0.2 at this point, so that's probably why it only upgraded to 1.0.2 for you.

You could also ask explicitly for 1.0.4: `conda install -c conda-forge jupyterlab=1.0.4`
