### ISSUE TITLE
Create a generic button dropdown widget

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#694]
We have multiple places in our UI where we want a button drop down widget for selecting among a set of options in a dropdown. Some examples:
- The new file icon in the file browser
- The cell type dropdown in the notebook toolbar
- The kernel name (which should be a drop down) in the notebook toolbar.
- Kernel name in the console.

This should support having an icon button as well as showing the currently selected item. consult @faricacarroll for visual design ideas.

**Comment by ellisonbg** [comment]
Also, we probably want to create a new subdirectory with custom UI controls for JLab that we can reuse...

**Comment by jasongrout** [comment]
We do have a minimal implementation of a dropdown in ipywidgets...

**Comment by ellisonbg** [comment]
We also have a rough implementation we are using for the new file button in the file browser...

**Comment by ellisonbg** [comment]
Here is the material design spec for menus, while not all of this is relevant for a button dropdown, some is and is well written.

**Comment by faricacarroll** [comment]
Here is an initial mockup for a generic dropdown button that can be applied to various buttons in JupyterLab. 

The menus all have a consistent menu item height of 24px. The menu item left padding is 10px. Top and bottom padding is 4px. I've also included screenshots of the design specs below that will provide more information.

Currently, the cell type dropdown menu shifts up and down depending on which language is selected. In this mockup, the menu wouldn't shift. The check icon will simply shift to what is selected.

The reason for this is I believe there was a concern about the implementation of a custom menu that behaves the way the default browser dropdown does.

**Here are screenshots of some of the original dropdown menus:** 

![screen shot 2016-08-22 at 2 10 10 pm](https://cloud.githubusercontent.com/assets/19479586/17873912/257daf62-687d-11e6-9555-beb2f53c375c.png)

![screen shot 2016-08-22 at 2 10 31 pm](https://cloud.githubusercontent.com/assets/19479586/17873915/28431cdc-687d-11e6-9009-248c45ece999.png)

**Generic dropdown menu mockups:**

![desktop hd](https://cloud.githubusercontent.com/assets/19479586/17875978/6b6ab5d4-688b-11e6-9ba3-bd6b5b6c0ae5.png)


![desktop hd2](https://cloud.githubusercontent.com/assets/19479586/17874374/19b26602-6880-11e6-8c38-02b66a1eb366.png)

![desktop hd3](https://cloud.githubusercontent.com/assets/19479586/17874375/19b29b22-6880-11e6-8e34-5c7b1e2be6dc.png)


**Dropdown menu redlines:**

![markdown](https://cloud.githubusercontent.com/assets/19479586/17876016/ba85611e-688b-11e6-856a-8c1b3bb4f2cd.png)


![newfile](https://cloud.githubusercontent.com/assets/19479586/17874384/2bed4292-6880-11e6-8d91-4a9fc69a3d0b.png)


![notebookmenu](https://cloud.githubusercontent.com/assets/19479586/17874452/978c51d2-6880-11e6-9b19-1ba36740f9d9.png)

**Comment by blink1073** [comment]
Note: the dropdown in the file browser is actually a phosphor menu.

**Comment by blink1073** [comment]
This would come in handy in #766.

**Comment by ellisonbg** [comment]
Let's focus on the following:

* Assume that the dropdowns are just standard phosphor menus and menu items.
* Design in B&W for now.
* For button drop down focus on the style of the button and where the dropdown is relative to the button.
* Do we need different sizes of buttons?
* For Selection style, what is the styling of the unselected UI? Also, where is the dropdown positioned relative to that UI?
* For now, only show mock ups with just the dropdowns and no context.

**Comment by ellisonbg** [comment]
For reference, here are some screenshots of the latest menu/menu item styling in jlab:

![screen shot 2016-08-29 at 10 49 55 am](https://cloud.githubusercontent.com/assets/27600/18061155/76abf2d2-6dd6-11e6-9ed9-35e996fb3828.png)

![screen shot 2016-08-29 at 10 50 03 am](https://cloud.githubusercontent.com/assets/27600/18061158/7aa65a58-6dd6-11e6-8737-391861241f54.png)

![screen shot 2016-08-29 at 10 50 10 am](https://cloud.githubusercontent.com/assets/27600/18061163/7dbb5d06-6dd6-11e6-811b-4296de2cd37d.png)

**Comment by ellisonbg** [comment]
We current design for menus has:

* `24px` menu item height
* `4px` L/R padding on each item
* Full width separators.

**Comment by ellisonbg** [comment]
In talking more with @faricacarroll and @matt-bowers we are going to break this up into two parts:

* General button styling (#804)
* Combining a button with a dropdown

**Comment by ellisonbg** [comment]
Closing in favor of #2880
