### ISSUE TITLE
Removing Cache-Control Header on Static Files

### ISSUE THREAD

**Issue by pkqxdd** [jupyterlab/jupyterlab#6942]
I have a jupyter lab installation in a remote location. Currently, the static files retrieved from the Jupyter Lab has `Cache-Control: no-cache` header present. While it wouldn't make a significant difference for a normal website, it does make it a very painful process to wait for my browser to reload the 30MB javascript at ~100KB/s every time I restart my browser. 

I understand that JupyterLab isn't designed to be optimal under slow connections but I think it would be a welcoming improvement to remove the header/add it to the config file. In addition, minimizing the vendor JS file would also be helpful and easy to implement.

**Comment by jasongrout** [comment]
This is being discussed at #5558 - let's move the discussion there to consolidate. Thanks!
