### ISSUE TITLE
Create a Help:Keyboard Shortcuts menu item that opens a view of all the shortcuts

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#695]
In the existing notebook, there is a Help:Keyboard Shortcuts menu item that opens a floating panel that shows all of the keyboard shortcuts. We should do the same thing in JLab, but have a view that opens in the dock panel. This would be a perfect place to use the virtual DOM rendering APIs.

**Comment by ellisonbg** [comment]
Part of what we will have to think about is:

* Unlike the existing notebook, we now have shortcuts for different plugins.
* For the notebook plugin we have command/edit mode.

**Comment by janschulz** [comment]
Please make the keymap printable, as a reference above the monitor :-)

**Comment by jasongrout** [comment]
We should make any tab printable as its own page.

**Comment by jasongrout** [comment]
cf. #822 for an issue about making any tab printable.

**Comment by ellisonbg** [comment]
@roshancvp any update on this?

**Comment by ellisonbg** [comment]
I think the settings system, in addition to the menu/command palette covers this well now.
