### ISSUE TITLE
Merge jupyterlab-celltags into core

### ISSUE THREAD

**Issue by h-vetinari** [jupyterlab/jupyterlab#6952]
Continuation of the now-locked #2277, where celltags were first defined as feature parity with notebook, then closed as moved to an [extension](https://github.com/jupyterlab/jupyterlab-celltags), then targeted to be absorbed for 1.0 (which didn't happen), and the latest [news](https://github.com/jupyterlab/jupyterlab/issues/2277#issuecomment-506498866) was that the merge was being actively planned in jupyterlab/jupyterlab-celltags#179 (which seems to have lost steam unfortunately).

PS. I don't like lock bot(s). Would have made much more sense IMO to keep tracking #2277.

**Comment by vidartf** [comment]
@h-vetinari The bot didn't close the issue, it locked the issue that was already closed. If an issue has remaining actionable items, it should not be closed, or a new issue should be created to track anything remaining. This issue solves this nicely, so thanks for that 👍

**Comment by h-vetinari** [comment]
@jasongrout 
I saw that 2.0.0 appeared on the horizon - it would be great to have this for the 2.0.0 milestone, and not postponed even further (considering that it's still missing for feature parity and was targeted for 1.0; resp. its importance for tools like papermill).

**Comment by vidartf** [comment]
@h-vetinari I'm sure any and all efforts to help create a PR for this will be appreciated. The code is available in https://github.com/jupyterlab/jupyterlab-celltags/

**Comment by markellekelly** [comment]
Hi! I recently picked this up and am working on a refactor of celltags with some UI/UX redesign. I plan on making a PR to core within the next week or two.

**Comment by vidartf** [comment]
@markellekelly Sounds good. Please reach out if you get stuck on anything!

**Comment by h-vetinari** [comment]
This has been solved by #7407.
