### ISSUE TITLE
jupyterlab interactive plots not working

### ISSUE THREAD

**Issue by ffenini** [jupyterlab/jupyterlab#6955]
Hello,

I tried to install the jupyter widgets according to[https://github.com/matplotlib/jupyter-matplotlib]( https://github.com/matplotlib/jupyter-matplotlib). Yet, whenever I try to run the cell after the magic command
%matplotlib widget, the output keeps on saying ‘Loading widget…’ without displaying it.

I installed Node js and followed the instructions, but I cannot make it work.
What am I doing wrong?

Thanks for your time

**Comment by timkpaine** [comment]
Can you provide the output of:
`jupyter labextension list`
and
`pip show ipympl`

**Comment by ffenini** [comment]
jupyter labextension list

`JupyterLab v1.0.2
Known labextensions:
   app dir: c:\users\au630261\appdata\local\continuum\anaconda3\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v1.0.2 enabled  ok
        @jupyterlab/toc v1.0.1 enabled  ok
        jupyter-matplotlib v0.4.2 enabled  ok
        jupyterlab-drawio v0.6.0 enabled  ok`

pip show ipympl

`Name: ipympl
Version: 0.2.1
Summary: Matplotlib Jupyter Extension
Home-page: http://matplotlib.org
Author: Matplotlib Development Team
Author-email: matplotlib-users@python.org
License: UNKNOWN
Requires: ipywidgets, six, ipykernel, matplotlib`

Hope this is enough

**Comment by ffenini** [comment]
jupyter labextension list

`JupyterLab v1.0.2
Known labextensions:
   app dir: c:\users\au630261\appdata\local\continuum\anaconda3\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v1.0.2 enabled  ok
        @jupyterlab/toc v1.0.1 enabled  ok
        jupyter-matplotlib v0.4.2 enabled  ok
        jupyterlab-drawio v0.6.0 enabled  ok`

pip show ipympl

`Name: ipympl
Version: 0.2.1
Summary: Matplotlib Jupyter Extension
Home-page: http://matplotlib.org
Author: Matplotlib Development Team
Author-email: matplotlib-users@python.org
License: UNKNOWN
Requires: ipywidgets, six, ipykernel, matplotlib`

Hope this is enough

**Comment by jasongrout** [comment]
Where are you trying to use widgets? In the notebook?

**Comment by ffenini** [comment]
Yes, in Jupyter Lab interface. 
The widgets work, for example 'IntSlider', 'IntRangeSlider', 'ColorPicker'.
It is only the images that are not displayed. No error occurs but the output remains ‘Loading widget…’  indefinetely.

**Comment by murison** [comment]
I have been having the same problem for several weeks now. Extensive Google searching has provided no solutions. This used to work just fine. What happened that broke it? HELP!!!

**Comment by jmp75** [comment]
Issue reproduced when trying the nb [voila-gpx-viewer](https://github.com/jtpio/voila-gpx-viewer) - fine with jupyter-notebook, "Loading widget..." from jupyter-lab.

`jupyter labextension list`

```text
JupyterLab v1.0.2
Known labextensions:
   app dir: /home/xxxyyy/anaconda3/envs/ELA/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.1  enabled  OK
        bqplot v0.4.7  enabled  OK
        jupyter-leaflet v0.11.1  enabled  OK
```

`jupyter-nbextension list` :

```text
Known nbextensions:
  config dir: /home/xxxyyy/anaconda3/envs/ELA/etc/jupyter/nbconfig
    notebook section
      bqplot/extension  enabled 
      - Validating: OK
      jupyter-leaflet/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
  config dir: /etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

**Comment by jasongrout** [comment]
Can you file an issue with that project? Is it compatible with JLab 1.0?

**Comment by jmp75** [comment]
Correction it now appears to work under jupyter-lab. The only change may have been a restart of the jupyter-lab server after registering extensions (unsure, sorry). Not working anymore with jupyter-notebook though, so a puzzle.

**Comment by jasongrout** [comment]
@ffenini - is your issue resolved? If not, but if other widgets work, it sounds like it may be an installation error with the matplotlib widget, or an issue with ipympl, and it would be better to file an issue with ipympl.

**Comment by jasongrout** [comment]
Closing as resolved.
