### ISSUE TITLE
Mitigate the horizontal squeezing of the main work area

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#696]
After playing with JupyterLab and watching people use it for a few months, I have consistently observed something about our UI:

Because we have both a R and L side panel, it is very easy to get the main dock panel area into a situation where individual panels/tabs are way too narrow. On a 13" laptop, it is almost hard to avoid.

Here is a screen shot:

<img width="1264" alt="screen shot 2016-08-17 at 7 33 23 pm" src="https://cloud.githubusercontent.com/assets/27600/17760059/7f1cee54-64b1-11e6-9dbf-6b7b3205f493.png">

I have also been watching how users interact with other UIs in this space (such as RStudio) which don't have this content squeeze effect. 

I think we should rethink how we are using the L/R side panels and how their functionality is expressed visually in the layout. Some things to consider:
- Can we get by with just a L panel? Running could be moved to the L side and the inspector could be made a panel in the dock area.
- Does it make more sense to open help links in a separate browser tab?
- The vertical tabs of the L/R panel occupy a significant amount of horizontal space. Is there a different way of expressing that layout that doesn't occupy that space.
- RStudio has a complete fixed layout that always puts the same content in the same place in the same 4 panels. While I don't want to move to something that rigid, we may want some options that rearrange the UI into a well known, fixed arrangement.

**Comment by ellisonbg** [comment]
Here are some screen shots of really nice IUs on macOs (Sketch, Pages, Keynote) that have L and/or R side panels (note the lack of vertical tabs).

<img width="1280" alt="screen shot 2016-08-17 at 7 39 32 pm" src="https://cloud.githubusercontent.com/assets/27600/17760178/8e0aab8a-64b2-11e6-9781-3c185db00f01.png">

<img width="1280" alt="screen shot 2016-08-17 at 7 39 48 pm" src="https://cloud.githubusercontent.com/assets/27600/17760181/9373bca6-64b2-11e6-9d05-e70143fd4cdd.png">

<img width="1280" alt="screen shot 2016-08-17 at 7 40 06 pm" src="https://cloud.githubusercontent.com/assets/27600/17760184/988c69d6-64b2-11e6-9e05-4a9d3bc262c2.png">

**Comment by ellisonbg** [comment]
One thing that is interesting about all of these examples is that the L/R side panels can only be hidden using an item in the view menu.

Keynote and pages have a R panel that has tabs, but I don't see how we could use that style of UI. I think that is the most difficult aspect of this - how to express tabs efficiently.

**Comment by matt-bowers** [comment]
The one thing that's different about these programs and Jupyter Lab is that although the content viewport is about the same as Jupyter Lab's, these other programs allow the user to pan and zoom in/out of the content according to their needs. With Jupyter Lab, all of the panels are displayed constantly at the same time, and their frame sizes are dependent on the viewport size, something that's not the case in the other macOS UIs.

I'm not saying that this is something we need to implement in Jupyter Lab, but I do think that it's important to note the dependency of the content from the content viewport, which is influenced heavily by these sidebars and the user-defined browser size (which also has a very small minimum width, as opposed to a larger minimum width for Pages and Keynote, just try it!).

**Comment by sccolbert** [comment]
Are we maybe over-thinking this? If your screen is too small to have three side-by-side panels along with an open side bar, maybe "just don't do that" is a sufficient answer? The point of the dock area is to allow the user to configure their panels in a way that makes the most sense for them and their current machine/workflow.

**Comment by matt-bowers** [comment]
@sccolbert I think yes and no.. I think that yes in the sense that you're right, the panel windows are adaptable so the user can adjust them accordingly for their workflow. However, I do believe that there should be some sort of "safeguard" from distorting content in panels for users that don't think about (or don't know how to) changing their workspace layout (even if this change is pushed until 1.0 or so).

Besides the viewport talk, I do think that one thing that _is_ important to figure out sooner than later is if there's a better way to switch the "tabs" for the sidebar (something that would save space, yet is expandable for the addition of other tabs in the future).

**Comment by sccolbert** [comment]
Well, the use wouldn't be able to get into that situation in the first place, if they didn't know how to configure their panels.

I'm not too attached to the sidebar. I made something similar to the side bar when I wrong Enaml's dock panel, but saw something more polished in Cloud9. What's in JLab today is closer to Cloud9. Happy to use something better if we can come up with it.

**Comment by ellisonbg** [comment]
Just met with @matt-bowers to talk about this. I think there are two separate issues:

1. What does the tab UI/UX for the L/R panels look like?
2. What content do we have in the L/R panels and do we even need a R panel?

We brainstormed on the first of these and arrived at a UI/UX proposal that fixes 1 in a very clean manner. He is going to mock that up. I think we should start there (it will be an improvement even if we keep the L/R panels) and then re-visit the second question.

**Comment by sccolbert** [comment]
Of note: If you don't have content added to a side bar, it will automatically hide. So, we don't necessarily need to get rid of the right side, just don't add anything to it by default.

**Comment by ellisonbg** [comment]
One other comments in the meantime - the problem with the "just don't do that" approach is that some actions (such as opening help) cause this problem in an unavoidable manner on even modest laptop screens. That was my big revelation about this in watching users for the last few months - basically all of them ran into this issue while actively trying to avoid it.

**Comment by sccolbert** [comment]
Currently, help is in a side bar because of iframes. We when I rigger the dock panel layout mechanism, we can have iframes as main tabs.

**Comment by ellisonbg** [comment]
* Yeah, I don't think we would entirely get rid of the R panel, as you said, at most, just stop using it.
* Another option that we have been talking about is opening help in a separate browser tab. We could do that until the dock panel layout stuff is refactored.

**Comment by matt-bowers** [comment]
I, along with the other designers at Cal Poly, have been working on an idea that @ellisonbg and I came up with when brainstorming new ways to navigate through the panes of the sidebar without having a full side-tab navigation bar that wastes lots of screen real estate.

This version allows for a familiar UI that is both compact, yet expandable for developers to add as many "tabs" as needed. This UI also has the potential for the addition of keyboard shortcuts that would allow users to quickly "switch" between tabs with only a couple of keystrokes.

![jupyter lab redesign 3 0](https://cloud.githubusercontent.com/assets/9501647/18021799/b36041b8-6b9e-11e6-897a-d6be97a34d2a.png)

We've done quite a few different iterations that involve the inclusion of other colors and functionality with command search.

![jupyter lab redesign 3 1](https://cloud.githubusercontent.com/assets/9501647/18021941/c002f234-6b9f-11e6-8b2c-ad721cc3a706.png)

![jupyter lab redesign 3 2](https://cloud.githubusercontent.com/assets/9501647/18021943/c63642aa-6b9f-11e6-8885-9b7e65f0f984.png)

![jupyter lab redesign 3 3](https://cloud.githubusercontent.com/assets/9501647/18021932/acaa9de0-6b9f-11e6-8ef9-8157217e5e76.png)

![jupyter lab redesign 3 4](https://cloud.githubusercontent.com/assets/9501647/18021957/ec174db6-6b9f-11e6-8e1c-2022ab5bba45.png)

@faricacarroll @spoorthyv @rnetro

**Comment by Carreau** [comment]
[I took the liberty of editing previous comment to include design names we can refer to , based on alt-text]. 

I have a preference for the toolbar color in design 3 4 ; though I'm unsure if it goes well with the rest of the Blue. I think my preference is because the search field is more easy to identify as clickable.

The Blue in the 3.2 toolbar seem too strong to me.

**Comment by jasongrout** [comment]
To me, at this point, it seems natural to just use tabs in the sidebar (that's basically what it looks like we have, restyled a bit). And at that point, it seems natural to let me drag the tabs to split the sidebar so I can have a filebrowser on top and command window on bottom, etc.

**Comment by ellisonbg** [comment]
@matt-bowers to help us focus on the core design questions of the tab interface, can you post some mockups with:

* The side panel and its tab bar only shown (don't should the surrounding UI)
* Black and white (to help us focus on the UX rather than visual design)
* Include some sort of UI for collapsing the side panel.

Thanks!

**Comment by ellisonbg** [comment]
@matt-bowers I know you are working on the RA stuff. Any progress on this one?

**Comment by matt-bowers** [comment]
Hey all, sorry for the absence, I've had to acclimate to the new school year and new role as a Resident Advisor! @ellisonbg I've turned everything black and white, focused on the side panel's tab bar only, and added a possible "tag-like" collapsed state interface. Let me know your opinions and comments!

**Sidebar Tab UI**
<img width="400" alt="screen shot 2016-09-30 at 4 32 32 pm" src="https://cloud.githubusercontent.com/assets/9501647/19010853/9fe41be6-873c-11e6-988f-b08df4ec87cd.png">

**Sidebar Collapsed**
![screen shot 2016-09-30 at 6 32 32 pm](https://cloud.githubusercontent.com/assets/9501647/19010852/9fe275c0-873c-11e6-9524-16e062833f24.png)

**Comment by spoorthyv** [comment]
Is there going to be a tag while the panel is open? Wondering how you would close the side panel.

**Comment by Carreau** [comment]
Here is a proposal discussed today in the lab meeting to avoid switching tab too often. Eac tab add/remove a pannel from the sidepannel.

![stack](https://cloud.githubusercontent.com/assets/335567/20013334/ef50d0ea-a26f-11e6-9814-5c23a5bf6ba8.png)

**Comment by ellisonbg** [comment]
Still not happy about the state of this one, but we may have to live with it for the beta/1.0.

One thing we should do is move all of the help links to open in the main dock panel now that iframes work fine. That will minimize how often the R panel opens...

**Comment by blink1073** [comment]
Some notes from lab discussion today:

Options for improvements:
- Add a View > Hide/Show L/R side panels.
- Collapse the space of a side bar if it has no items, with a visual indicator that items can be added.
- Add a visible or context menu to toggle which side bar panels are shown on the current panel.
- Allow dragging a side bar panel to the opposite side.
- Add a context menu to each panel tab to close or move to the other side.

**Comment by jasongrout** [comment]
Also: allow dragging a side bar panel to the main dock area.

**Comment by ellisonbg** [comment]
Another thing that would help: #1613 #1614

**Comment by ellisonbg** [comment]
@cameronoelsen

**Comment by cameronoelsen** [comment]
Coming back to this, what if we made a collapse button at the bottom left corner of the sidebar? This would help us clear up some space for the document area and it would be pretty straightfoward. Here is what I envision it will look and react to user interaction. Once the sidebar is collapsed and minimized on the side of the screen, I was thinking that the entire collapsed bar would act as a button to re-open the sidebar. Let me know what you think!

![ezgif-1-2747f39739](https://cloud.githubusercontent.com/assets/6437976/25195187/a96b1090-24f1-11e7-8328-f5544f6d8cec.gif)

**Comment by blink1073** [comment]
I like!
