### ISSUE TITLE
API docs not updating

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6960]
The API docs at http://jupyterlab.github.io/jupyterlab/ have stopped being updated, with the last automatic update on Feb 8, 2019.
```
commit 133cbc90c224c99322e0f59c3181878bbf55760e 
Author: Travis Bot <travis@travis-ci.com>
Date:   Fri Feb 8 23:47:02 2019 +0000

    Deploy to GitHub Pages
```
They should be triggered somehow from https://github.com/jupyterlab/jupyterlab/blob/f2d664b341045876626af2785d9a222dd0e9c794/scripts/travis_after_success.sh.

This might have coincided with our move to Azure for CI.

I've updated the docs manually to be current for JLab 1.0.4.

CC @saulshanabrook

**Comment by blink1073** [comment]
I just did a manual update using this process, following https://github.com/jupyterlab/jupyterlab/blob/0.35.x/scripts/travis_after_success.sh:

```
GITHUB_TOKEN=xxx
```
 
```
git clone git@github.com:jupyterlab/jupyterlab.git
cd jupyterlab
pip install -e .
jlpm build:packages
jlpm docs
 
GH_REF=github.com/jupyterlab/jupyterlab.git
cd docs/api
git init
git config user.email "travis@travis-ci.com"
git config user.name "Travis Bot"
touch .nojekyll # disable jekyll
git add .
git commit -m "Deploy to GitHub Pages"
git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
```

https://jupyterlab.github.io/jupyterlab/modules/_toc_src_index_.html

**Comment by blink1073** [comment]
cc @telamonian

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/9179
