### ISSUE TITLE
Improving usability: URL format during the launch 

### ISSUE THREAD

**Issue by thammegowda** [jupyterlab/jupyterlab#6962]
Instead of printing 
```
Or copy and paste one of these URLs:
    http://(<hostname> or 127.0.0.1):8888/?token=<token>
```

How about enumerating :
```
Or copy and paste one of these URLs:
http://<hostname>:8888/?token=<token> 
http://127.0.0.1:8888/?token=<token>
```

Goal:  Instead of making the user `Copy -> Paste -> Edit -> Go ` just `Click to go` ( if it is valid URL, terminals actually recognize make it a clickable link,)

We use this so often and its easier to fix; If you can please point me to where to look at in the code, I can send a PR 

Thanks

**Comment by jasongrout** [comment]
This is an issue with the notebook server that JupyterLab depends on. For me, it looks like this:

```
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=...
     or http://127.0.0.1:8888/?token=...
```
Which is closer to what you are thinking. However, that "or" means that I can't just triple-click that line in the terminal and copy/paste. It does sound like it would work for you, though.

So perhaps for you, just upgrade your version of the `notebook` package?

**Comment by jasongrout** [comment]
The relevant lines of code are in https://github.com/jupyter/notebook/blob/20c2c66857430a0092a5e751fbfa5555f3b74054/notebook/notebookapp.py#L1842-L1848 if you want to submit a PR to the notebook server project.

**Comment by jasongrout** [comment]
And https://github.com/jupyter/notebook/blob/20c2c66857430a0092a5e751fbfa5555f3b74054/notebook/notebookapp.py#L1461-L1479 is relevant as well.

**Comment by thammegowda** [comment]
I updated `jupyter`  package and now it works as listed in https://github.com/jupyterlab/jupyterlab/issues/6962#issuecomment-520041134 

tested on -- 
```
$ jupyter --version
jupyter core     : 4.5.0
jupyter-notebook : 6.0.0
qtconsole        : 4.5.3
ipython          : 7.7.0
ipykernel        : 5.1.2
jupyter client   : 5.3.1
jupyter lab      : 0.35.4
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.2
```
Thanks @jasongrout
