### ISSUE TITLE
Update Contributing Guidelines and Readme to explain lockbot

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#6965]
Summary:
- Issues closed over 90 days with no more activity will lock automatically
- In an effort to keep issues up to date, we welcome anybody to open new issues if a past locked issue was only partially solved. 
    - New issues addressing locked issues should reference them. 
- A locked issue does not mean an unimportant issue, we are attempting to help keep an up-to-date record of what is still a relevant issue.

@jasongrout I'm working on updating the markdown files, did I miss anything from this morning's discussion?

**Comment by blink1073** [comment]
Sounds good to me, thanks @tgeorgeux!
