### ISSUE TITLE
Docs linkcheck is failing

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#6970]
Looking at several of the recent builds (master and PRs), it looks like the job building the docs is now failing during the `linkcheck` step.

Also reproducible locally with `cd docs && make linkcheck`:

```
...
(line  337) broken    https://github.com/jupyterlab/jupyterlab/pull/5108 - 404 Client Error: Not Found for url: https://github.com/jupyterlab/jupyterlab/pull/5108
...
```

So it seems that #5108 is now giving back a 404.

Maybe just an intermittent issue with GitHub?

**Comment by jtpio** [comment]
https://github.com/jupyterlab/jupyterlab/pull/5108 is now reachable again and tests are passing.

Did anyone get a reply from the GitHub support team explaining what the problem was?

**Comment by jasongrout** [comment]
As mentioned in https://github.com/jupyterlab/jupyterlab/issues/6977 [1], I filed a request about this. I never heard back, but I did notice it started working.

Closing as resolved.

[1] (sorry, should have seen this issue was already opened before opening #6977.
