### ISSUE TITLE
Creating JupyterLab Extension following tutorial doesn't work on Windows

### ISSUE THREAD

**Issue by jcoady** [jupyterlab/jupyterlab#6972]
I tried following this tutorial to create a jupyterlab extension using a Windows machine.

https://jupyterlab.readthedocs.io/en/stable/developer/extension_tutorial.html#extension-tutorial

I was not able to perform the steps in the tutorial on a Windows machine and get a working jupyterlab extension.

The first problem I encountered was with the very first step.

conda create -n jupyterlab-ext -c conda-forge --override-channels jupyterlab cookiecutter nodejs git

This reported the following error.

I get the error
PackageNotFoundError: The following packages are not available from the current channels
-nodejs --> vs2015_runtime

The suggested workaround was to perform the following command instead.

conda create -n jupyterlab-ext --override-channels --strict-channel-priority -c conda-forge -c anaconda jupyterlab cookiecutter nodejs git

Which seemed to work.

The next problem was that  the command

jlpm install

did not seem to work. It returned 3 lines

yarn install v1.15.2
info No lockfile found.
[1/4] Resolving packages...

and then returned the command prompt so I am not sure if it installed correctly. I think on a Linux machine this command output a lot more stuff.

Next the command
jupyter lab --watch

did not open jupyterlab in a browser window. 

So I tried running jupyterlab without watch mode and it indicated that a build was required with a popup window. I clicked on the button to perform the build. After a while I got an error message that the build failed.

Build Failed

Build failed with 500, please run 'jupyter lab build' on the server for full output

So it seems that there are a lot of problems getting this jupyter labextension tutorial to work on Windows.

Maybe someone on the JupyterLab team can try running this tutorial on Windows and fix all the problems so that other users can get through the tutorial problem free on a Windows machine.

**Comment by fcollonval** [comment]
Hey John,

I try the tutorial on my pc. The conda environment fails indeed. But I do not have any problem with `jlpm`. Could you provide the results of `conda info` command for your system?
Do you get any anti-virus/firewall on your PC? It may forbid the access to the internet for `jlpm`.

**Comment by jcoady** [comment]
When I type 
jlpm
it returns only one line which says
"failed to create process"
It does this on both of my Windows machines. Here is the result of conda info

(jupyterlab-ext2) C:\Users\ecoad\jupyterlab_apod2>conda info

     active environment : jupyterlab-ext2
    active env location : C:\Users\ecoad\Miniconda3\envs\jupyterlab-ext2
            shell level : 2
       user config file : C:\Users\ecoad\.condarc
 populated config files :
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : C:\Users\ecoad\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\ecoad\Miniconda3\pkgs
                          C:\Users\ecoad\.conda\pkgs
                          C:\Users\ecoad\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\ecoad\Miniconda3\envs
                          C:\Users\ecoad\.conda\envs
                          C:\Users\ecoad\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


I am running this from my computer at home and I don't know how to check for firewall or anti-virus. I will mention that jlpm worked fine using an older version of jupyterlab 0.35.3.

**Comment by fcollonval** [comment]
@jcoady Thanks for reporting back. An error in the conda recipe was the cause of the bug. While waiting for a new package release, you could downgrade to `jupyterlab=1.0.4`.

**Comment by jcoady** [comment]
OK I downgraded to jupyterlab 1.0.4 and got to the point in the tutorial to launch jupyterlab in watch mode but nothing happens when I do so. It just seems to hang and jupyterlab doesn't open in a browser.

(base) C:\Users\ecoad>conda activate jupyterlab-ext2

(jupyterlab-ext2) C:\Users\ecoad>jupyter lab --watch
[I 13:51:01.804 LabApp] JupyterLab extension loaded from C:\Users\ecoad\Miniconda3\envs\jupyterlab-ext2\lib\site-packages\jupyterlab
[I 13:51:01.804 LabApp] JupyterLab application directory is C:\Users\ecoad\Miniconda3\envs\jupyterlab-ext2\share\jupyter\lab
[I 13:51:01.804 LabApp] Starting JupyterLab watch mode...
|

This is all I see in the Anaconda prompt window after waiting a long time.

**Comment by fcollonval** [comment]
The new package is available. When upgrading, be sure to check the version jupyterlab=1.0.6=py37_1.
What's important is the _1 after py36 or py37 (depending on the python version you use).
