### ISSUE TITLE
Modify existing commands

### ISSUE THREAD

**Issue by 1637410810** [jupyterlab/jupyterlab#6973]
Hello,
I want to modify existing commands in other extensions.

Is there any workaround?
Thanks

**Comment by 1637410810** [comment]
I have a extension, I want to modify the commands for other extended registrations

**Comment by jasongrout** [comment]
You can create new commands and register them. You may be able to replace existing commands. Can you be more specific about what you are wanting to do?

**Comment by 1637410810** [comment]
I want to limit the following files to be deleted under certain conditions.

**Comment by jasongrout** [comment]
> the following files

What files?

If you want to prevent deletion, you should probably do that with the contents manager on the server. That's where the deletion actually happens.

**Comment by 1637410810** [comment]
Thank you

**Comment by 1637410810** [comment]
How to replace the command. I did not find it in the documentation

**Comment by jasongrout** [comment]
I just checked the code, and it looks like an error is thrown if you try to register a command with the same id as an existing command. So you'd need to disable the plugin that registered the command you want to replace in the jlab config, then register your own command with that same name (and same interface, of course).

**Comment by 1637410810** [comment]
Thank you, I think I know what to do.
