### ISSUE TITLE
Docs test PR link broken

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#6977]
About three days ago, the linux doc tests were working fine. Now it seems that it can't resolve https://github.com/jupyterlab/jupyterlab/pull/5108. Indeed, I can't get to that URL in my browser - that PR seems to have disappeared from GitHub.

**Comment by jasongrout** [comment]
Hovering over the link above, I see GitHub still shows a preview. However clicking it gives a 404.

**Comment by jasongrout** [comment]
I file an issue with GitHub about this.

**Comment by blink1073** [comment]
Perhaps whoever made the PR no longer has a Github account?

**Comment by jasongrout** [comment]
I think it would be odd to delete a merged PR because someone deletes their account

**Comment by jtpio** [comment]
Issues can be deleted by not PRs it seems. So it definitely looks odd.

Also posted here: https://github.com/jupyterlab/jupyterlab/issues/6970

**Comment by jasongrout** [comment]
Yep, this is a dup of #6970.
