### ISSUE TITLE
Audit notebook cell styles

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#698]
We still have minor style differences in the notebook cell style compared to the classic notebook. Assigning to myself.
- [ ] dimensions
- [ ] Margins
- [ ] Padding
- [ ] Borders
- [ ] Different types of outputs

**Comment by blink1073** [comment]
I did some of this in #1248.

**Comment by ellisonbg** [comment]
:( that was a deliberate design choice, will need to revert at least some of it...

**Comment by ellisonbg** [comment]
Closing this - tracking the ongoing work in #12124
