### ISSUE TITLE
Silent failure of status bar components?

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#6981]
Currently, if you uninstall (disable) the statusbar extension, a lot of smaller plugins that add components to the statusbar will fail to activate (e.g. `@jupyterlab/docmanager-extension:path-status`). You would then either have to live with a bunch of errors in the JS console (livable, but makes real errors harder to spot), or disable each of them.

An alternative to this could be for these plugins to have the statusbar as an optional dependency, and simply do nothing if it is not available. I understand that is conceptually weird (a plugin that's sole purpose is to add something to the statusbar having an optional dependency on the statusbar), but it also makes sense for them to automatically turn themselves off if the statusbar is missing.

**To Reproduce**
```
jupyter labextension uninstall @jupyterlab/statusbar-extension
```

Watch the errors in the JS console on lab load afterwards.

**Comment by blink1073** [comment]
I saw this when updating the app example start up without console errors in CI.  👍 to be a no-op for these plugins.

**Comment by jasongrout** [comment]
Good first issue? Do you want to explain how to do it (maybe a link to an example PR? Or do you just want to do it?

**Comment by vidartf** [comment]
> Or do you just want to do it?

This 🚀

**Comment by vidartf** [comment]
#7001
