### ISSUE TITLE
Not a valid npm package

### ISSUE THREAD

**Issue by ndeep147** [jupyterlab/jupyterlab#6992]
I just installed anaconda and installed nodejs as recommended in the documentation (conda install -c conda-forge nodejs).

However, any jupyter lab extension that I attempt to install returns the error that the extension is not a valid npm package. Any suggestions?

**Comment by jasongrout** [comment]
Can you give us step-by-step instructions to reproduce the error, and paste the error log here?

**Comment by ndeep147** [comment]
I open the Anaconda Prompt and complete the following:

(base) C:\>jupyter labextension install jupyterlab-chart-editor@1.2
An error occured.
ValueError: "jupyterlab-chart-editor@1.2" is not a valid npm package
See the log file for details:  C:\Users\xbbld4x\AppData\Local\Temp\jupyterlab-de
bug-3r4g7uo0.log

**Error log:**
Node v12.8.0

> C:\Users\xbbld4x\AppData\Local\Continuum\anaconda3\npm.CMD pack jupyterlab-chart-editor@1.2
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to http://registry.npmjs.org/jupyterlab-chart-editor failed, reason: getaddrinfo ENOTFOUND proxy_host
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xbbld4x\AppData\Roaming\npm-cache\_logs\2019-08-12T16_02_27_295Z-debug.log

Traceback (most recent call last):

  File "c:\users\xbbld4x\appdata\local\continuum\anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "c:\users\xbbld4x\appdata\local\continuum\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 82, in start
    ans = self.run_task()

  File "c:\users\xbbld4x\appdata\local\continuum\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "c:\users\xbbld4x\appdata\local\continuum\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "c:\users\xbbld4x\appdata\local\continuum\anaconda3\lib\site-packages\jupyterlab\commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "c:\users\xbbld4x\appdata\local\continuum\anaconda3\lib\site-packages\jupyterlab\commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "c:\users\xbbld4x\appdata\local\continuum\anaconda3\lib\site-packages\jupyterlab\commands.py", line 1373, in _install_extension
    info = self._extract_package(extension, tempdir)

  File "c:\users\xbbld4x\appdata\local\continuum\anaconda3\lib\site-packages\jupyterlab\commands.py", line 1444, in _extract_package
    raise ValueError(msg % source)

ValueError: "jupyterlab-chart-editor@1.2" is not a valid npm package

Exiting application: jupyter

**Comment by jasongrout** [comment]
Looks like the relevant part of the error is:

> npm ERR! code ENOTFOUND
> npm ERR! errno ENOTFOUND
> npm ERR! network request to http://registry.npmjs.org/jupyterlab-chart-editor failed, reason: getaddrinfo ENOTFOUND proxy_host
> npm ERR! network This is a problem related to network connectivity.
> npm ERR! network In most cases you are behind a proxy or have bad network settings.
> npm ERR! network
> npm ERR! network If you are behind a proxy, please make sure that the
> npm ERR! network 'proxy' config is set properly. See: 'npm help config'

Looks like you have network issues and npm isn't able to get out to the registry. Perhaps there are proxies in the way stopping the network connection?

**Comment by ndeep147** [comment]
Yes, it was an issue with the connection because I am behind my company's firewall. Thank you for the help

**Comment by Dragon1573** [comment]
Hello, @jasongrout . I met the same problem as @ghost . I can't point out where I was wrong. 

# Operations, Logs & Configurations

<details>
<summary>Console Output from Powershell</summary>

```powershell
⨯ legen D:\..\..\..\..\Design env:base ❯❯❯ jupyter labextension install jupyterlab-toc@0.2.1
An error occured.
ValueError: "jupyterlab-toc@0.2.1" is not a valid npm package
See the log file for details:  C:\Users\legen\AppData\Local\Temp\jupyterlab-debug-zwjcq0d9.log
⨯ legen D:\..\..\..\..\Design env:base ❯❯❯
```

</details>
<details>
<summary>Contents of log file <code>jupyterlab-debug-zwjcq0d9.log</code></summary>

```log
Node v14.4.0

Yarn configuration loaded.
> C:\Users\legen\Anaconda3\npm.CMD pack jupyterlab-toc@0.2.1
系统找不到指定的路径。
系统找不到指定的路径。
npm WARN deprecated jupyterlab-toc@0.2.1: This package has been renamed '@jupyterlab/toc'
npm notice 
npm notice package: jupyterlab-toc@0.2.1
npm notice === Tarball Contents === 
npm notice 1.6kB  package.json       
npm notice 863B   README.md          
npm notice 1.5kB  LICENSE            
npm notice 2.9kB  lib/extension.js   
npm notice 11.3kB lib/generators.js  
npm notice 373B   lib/index.js       
npm notice 1.5kB  lib/registry.js    
npm notice 6.5kB  lib/toc.js         
npm notice 304B   lib/extension.d.ts 
npm notice 1.1kB  lib/generators.d.ts
npm notice 81B    lib/index.d.ts     
npm notice 2.1kB  lib/registry.d.ts  
npm notice 3.2kB  lib/toc.d.ts       
npm notice 2.1kB  style/index.css    
npm notice === Tarball Details === 
npm notice name:          jupyterlab-toc                          
npm notice version:       0.2.1                                   
npm notice filename:      jupyterlab-toc-0.2.1.tgz                
npm notice package size:  9.5 kB                                  
npm notice unpacked size: 35.5 kB                                 
npm notice shasum:        edd570ba1a523e3e2bf5811b9995f9a99e0c4fe4
npm notice integrity:     sha512-toWEuuN9zi3NM[...]qkQRGoDWupk+g==
npm notice total files:   14                                      
npm notice 
jupyterlab-toc-0.2.1.tgz

Traceback (most recent call last):

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 93, in start
    ans = self.run_task()

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 388, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 603, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1499, in _install_extension
    info = self._extract_package(extension, tempdir, pin=pin)

  File "C:\Users\legen\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1578, in _extract_package
    raise ValueError(msg % source)

ValueError: "jupyterlab-toc@0.2.1" is not a valid npm package

Exiting application: jupyter
```

</details>
<details>
<summary>Check my <code>npm</code> and <code>node</code> version in <code>git-bash</code></summary>

```bash
legen@Legend1949 MINGW64 ~
$ where npm
D:\NodeJS\npm
D:\NodeJS\npm.cmd
C:\Users\legen\Anaconda3\npm
C:\Users\legen\Anaconda3\npm.cmd

legen@Legend1949 MINGW64 ~
$ /d/NodeJS/npm -v
6.13.1

legen@Legend1949 MINGW64 ~
$ /c/Users/legen/Anaconda3/npm -v
6.14.5

legen@Legend1949 MINGW64 ~
$ where node
D:\NodeJS\node.exe
C:\Users\legen\Anaconda3\node.exe

legen@Legend1949 MINGW64 ~
$ /d/NodeJS/node -v
v13.2.0

legen@Legend1949 MINGW64 ~
$ /c/Users/legen/Anaconda3/node -v
v14.4.0

legen@Legend1949 MINGW64 ~
$
```

</details>
<details>
<summary>Contents of <code>C:\Users\legen\.npmrc</code></summary>

```text
registry=https://repo.huaweicloud.com/repository/npm/
disturl=https://repo.huaweicloud.com/nodejs
sass_binary_site=https://repo.huaweicloud.com/node-sass
phantomjs_cdnurl=https://repo.huaweicloud.com/phantomjs
chromedriver_cdnurl=https://repo.huaweicloud.com/chromedriver
operadriver_cdnurl=https://repo.huaweicloud.com/operadriver
electron_mirror=https://repo.huaweicloud.com/electron/
python_mirror=https://repo.huaweicloud.com/python
```

</details>

<details>
<summary>Install via <code>npm</code> directly</summary>

```bash
legen@Legend1949 MINGW64 ~
$ /c/Users/legen/Anaconda3/npm install jupyterlab-toc
npm WARN deprecated jupyterlab-toc@0.2.1: This package has been renamed '@jupyterlab/toc'
npm WARN deprecated json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\legen\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\legen\package.json'
npm WARN @jupyterlab/ui-components@1.2.1 requires a peer of react@~16.8.4 but none is installed. You must install peer dependencies yourself.
npm WARN legen No description
npm WARN legen No repository field.
npm WARN legen No README data
npm WARN legen No license field.

+ jupyterlab-toc@0.2.1
added 52 packages from 845 contributors in 4.423s

1 package is looking for funding
  run `npm fund` for details


legen@Legend1949 MINGW64 ~
$
```

</details>

# Other Details

- I'm in China Mainland. There is a Great Filewall (we called GFW) in my Internet environment, so I can't access to <https://registry.npmjs.org/> directly. 
- <https://mirrors.huaweicloud.com/> is a Public Repository Mirror hosted by HUAWEI DevCloud Team. For the previous reason, I'm using it as my `npm` mirror. 
- As logs above, I can install `jupyterlab-toc@0.2.1` through `npm` directly, but `jupyter labextension` command can't. 
- I'm using [Lantern Pro](https://github.com/getlantern/lantern-binaries) to help me pass through the GFW. After connecting to the proxy, I have no trouble visiting <https://registry.npmjs.org/jupyterlab-toc>. My `FeHelper` (a Google Chrome Extension) prettify the JSON response for me.
