### ISSUE TITLE
File Browser doesn't sort by ipynb files...

### ISSUE THREAD

**Issue by garrettmsft7** [jupyterlab/jupyterlab#6994]
Upgraded from v0.3x to v1.0.2.

Immediately noticed that the file browser doesn't sort / prioritize ipynb files anymore. Is anyone aware of this, and is there a fix?

**Comment by vidartf** [comment]
I think this discussion could be merged into that of https://github.com/jupyterlab/jupyterlab/issues/3237. Do you agree?

**Comment by jasongrout** [comment]
Yes. @garrettmsft7 - can you add your comments to that discussion? We'd like to keep the discussion in one place.
