### ISSUE TITLE
Completer Improvment.

### ISSUE THREAD

**Issue by daejong123** [jupyterlab/jupyterlab#6999]
Recently, I use complete automatically by pressing key 'tab', But when the result of the completion is only one, the completer complete directly to the codeCell without my selection, I think it's too aggressive of completer behavior.
Can you improve completion of the mechanism,
I found source code that is as follows: 

![image](https://user-images.githubusercontent.com/19252403/62919288-d376b780-bdd4-11e9-9331-5d5135e285e8.png)

https://github.com/jupyterlab/jupyterlab/blob/c0e9eb9466/packages/completer/src/widget.ts

**Comment by daejong123** [comment]
@JLab Team

**Comment by jasongrout** [comment]
We made the UX decision that if the user hits tab, and there is only one option, then that option is used. Are you suggesting a different behavior? What are you suggesting?

cf #6975

**Comment by daejong123** [comment]
Thanks!
I suggest that if the length of options equal one when the user hits tab, the behavior should be same with multiple option(Let users to choose in the optional list), cause sometimes I just want to see the result of the completion not if there is only one option, then that option is used.

**Comment by daejong123** [comment]
Or put this configuration in the configuration file，then developers and users customize degree will be a little higher!

**Comment by daejong123** [comment]
Or Can you help me overwrite the Completer
![image](https://user-images.githubusercontent.com/19252403/63234332-61d0ba80-c267-11e9-97ad-b10e99b7dcad.png)
