### ISSUE TITLE
What fonts are available as "fontFamily" ?

### ISSUE THREAD

**Issue by StrausMG** [jupyterlab/jupyterlab#7000]
Hi! I run JupyterLab 0.33 (Python 2) on my server and browse it via the latest macOS.

I would like to change fontFamily in advanced settings. However, I don't know the correct "names" of some fonts I want to try.  For example, this produce the expected result:  
`{"codeCellConfig": {"fontFamily": "Monaco"}}`
However, when I want to try SF Mono Regular, none of the following works:  
`{"codeCellConfig": {"fontFamily": "SFMono-Regular"}}`  
`{"codeCellConfig": {"fontFamily": "SF Mono Regular"}}`  

Where can I find the list of supported fonts ?

**Comment by telamonian** [comment]
I think the one you're looking for is `"SF Mono"` (with the quotes). On Mac, you should be able to see all of the available fonts/names listed in the `/Applications/Font Book` app, though I think there may be a few other issues that keep them all from working.

**Comment by telamonian** [comment]
This doesn't really apply to the OP's question, but here's a note on the general problem of selecting an exact font variant vs just the font family (eg `"SF Mono Regular"` vs `"SF Mono"`):

There doesn't seem to be a general CSS-compatible way to use a specific font weight variant (ie `"SF Mono Light"`, `"SF Mono Regular"`, etc) in Jupyterlab. If the font follows one particular naming convention (`"X normal"`, `"X lighter"`, `"X bold"`, etc), then those specific  variants could be assessed via the `font-weight` CSS property. For fonts named via any other convention, the browser just creates a mimic of the specified font weight variant (eg a bold mimic for `"font-weight": 700`)

**Comment by jasongrout** [comment]
Closing as answered. Thanks @telamonian!
