### ISSUE TITLE
Add `theme` to Text Editor System Defaults Settings

### ISSUE THREAD

**Issue by amarthey** [jupyterlab/jupyterlab#7005]
Similar to #4139 I would like to add `theme` to the Text Editor System Defaults Settings.

Default value would be: `"theme": "jupyter"`

**Comment by telamonian** [comment]
Can you please clarify this request a bit? Currently, the text editor theme can be set via the `Text Editor Theme` submenu in the `Settings` menu, or via the `"theme"` option in `Advanced Settings Editor -> CodeMirror`. The default in the `CodeMirror` settings is indeed `"theme": "jupyter"`.

Is the issue that it's confusing for the text editor theme to be part of the `CodeMirror` settings? Or is the issue that you want there to be a separate `"theme"` option in the `Text Editor` advanced settings, similar to the currently existing `"theme"` option in the `Terminal` settings?

**Comment by amarthey** [comment]
I didn't know that `"theme"` setting was available in `CodeMirror`. I only looked into `Settings -> Advanced Settings Editor -> Text Editor` thinking it would be linked to `Settings -> Text Editor Theme`

Issue can be closed
