### ISSUE TITLE
Support up/down arrow and tab completion when using `ipdb` to debug notebook

### ISSUE THREAD

**Issue by joelostblom** [jupyterlab/jupyterlab#7006]
I find `%debug` to enter post mortem debugging with `ipdb` really useful for debugging functions in notebooks. I think it could be made even more efficient by supporting up/down arrow to navigate in the debugging prompt history (instead of repeatedly copy and paste the last run line) and tab for completing variable names in the current namespace. Currently, up/down arrow does nothing and pressing tab moves to the next cell when pressed in the `ipdb` prompt. Both these shortcuts work as expected in the IPython terminal prompt.

Version info:

```
-----
IPython   	6.5.0
jupyter_client	5.2.3
jupyter_core	4.4.0
jupyterlab	1.0.5
notebook  	5.6.0
-----
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) [GCC 7.3.0]
Linux-5.2.6-arch1-1-ARCH-x86_64-with-arch
```

**Comment by jasongrout** [comment]
Thanks for the suggestion. My guess is that this may be difficult to do. Does the classic notebook do this?

**Comment by joelostblom** [comment]
The classic notebook behaves the same as JupyerLab.

**Comment by telamonian** [comment]
Oh my god, I would love this, but it's never been very clear how to go about making it happen. I do know that IPython implements its own `Pdb`, which is what the `%debug` magic uses. For instance, you can set a breakpoint in your code like so:

```
from IPython.core.debugger import Pdb; Pdb().set_trace()
```

So maybe it would be possible to somehow get history from the `Pdb` module? This would require some digging.

**Comment by joelostblom** [comment]
I tested a bit more:

The jupyter qtconsole (v4.5.3) also behaves similar to JupyterLab  (up/down arrow does nothing, TAB inserts tab instead of autocompletion).

The jupyter console (v5.2.0) does the same (except that up/down arrow inserts escape sequences in the terminal emulator).

**Comment by vman049** [comment]
Any updates on this? This is also something I've wanted for a long time.

**Comment by mbloem** [comment]
I'd also love this feature, both for jupyter qtconsole and jupyter lab.

**Comment by telamonian** [comment]
The [`readline`](https://docs.python.org/3.8/library/readline.html) standard lib is what normally provides this feature. However, it looks like the debugger built into ipython/jupyter [specifically avoids loading `readline`](https://ipython.readthedocs.io/en/latest/api/generated/IPython.core.debugger.html#module-IPython.core.debugger):

> Modified from the standard pdb.Pdb class to avoid including readline, so that the command line completion of other programs which include this isn’t damaged.

In other words, Jlab will have to add in it's own `readline` support for the debugger input box.

**Comment by biphasic** [comment]
this would be great!
