### ISSUE TITLE
Add time delay to search as you type feature to avoid matching hundreds of single characters

### ISSUE THREAD

**Issue by joelostblom** [jupyterlab/jupyterlab#7007]
The search (and replace) features that were added in 1.0 are great, thank you for creating them! I have noticed that the search initiates as I type, starting with a single character. This causes performance issues on large notebooks for me, where JupyterLab will lag for a bit as the search is finding hundreds of matches for a single character. I suggest adding a short delay so that a search is not triggered if a key is pressed within a certain time frame of the previous key.

I believe a time delay offers a preferable user experience to limiting the number of characters that triggers a search as there might be instances where one want to search for one or two characters. The time delay can be kept short so it really only triggers on typing a string of characters and does not noticeably impact the wait time for a search to trigger after finishing typing.

**Comment by jasongrout** [comment]
Please try JLab 1.0.5, which has some massive speed increases for the search.

**Comment by jasongrout** [comment]
(actually, I think the speed increases were in 1.0.3, but 1.0.5 has a few more fixes as well)

**Comment by joelostblom** [comment]
@jasongrout Thanks for the quick reply and my apologies for not listing version numbers. I am using 1.0.5 already.

I tried installing jupyterlab from a new environment to make sure I test this without extensions and I see the same slow down when searching. The notebook has aronud 800 lines of code, and I am installing jupyterlab via conda (I don't think this matters but I'll mention that after a fresh install of jupyterlab I still have to install the `simplegeneric` module manually and downgrade `tornado` from 6 -> 5.1 due to `'tornado.web' has no attribute 'asynchronous'`).

Full version info:

```
-----
IPython   	6.5.0
jupyter_client	5.2.3
jupyter_core	4.4.0
jupyterlab	1.0.5
notebook  	5.6.0
-----
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) [GCC 7.3.0]
Linux-5.2.6-arch1-1-ARCH-x86_64-with-arch
```

**Comment by krassowski** [comment]
I think that @jasongrout previously proposed this in an initial response to #6756 and I noted further that the debouncer is already part of the codebase: https://github.com/jupyterlab/jupyterlab/issues/6756#issuecomment-509007384.

Do we agree that this value needs increasing from 100ms to 500ms?

**Comment by jasongrout** [comment]
Sounds good to me

**Comment by joelostblom** [comment]
Thanks for addressing this so quickly!
