### ISSUE TITLE
hubUser JSON property not properly escaped

### ISSUE THREAD

**Issue by nicorikken** [jupyterlab/jupyterlab#7008]
## Description

Running JupyterLab on JupyterHub, the Javascript fails to load the `jupyter-config-data"` JSON data.
![Screenshot from 2019-08-14 07-25-34](https://user-images.githubusercontent.com/7458098/62996362-c7d2d180-be64-11e9-9be6-fef116f68f0a.png)
As a result I'm left with a blank website.

Opening the page source, I notice that the hubUser is not properly escaped (anonymized in this example):

```
<script id="jupyter-config-data" type="application/json">{
    "quitButton": "False",
    "buildAvailable": "True",
    "buildCheck": "True",
    "devMode": "False",
    "token": "61539b9e261e459688391a43d1294241",
    "notebookVersion": "[6, 0, 0]",
    "hubPrefix": "/hub/",
    "hubHost": "",
    "hubUser": "organization\userid",
    "terminalsAvailable": "True",
    ...
```

I'm running into this issue as we have a backslash in the username, as a result of using Active Directory through Keycloak as a base for usernames.
I've already solved similar issues in JupyterHub https://github.com/jupyterhub/jupyterhub/pull/2640 https://github.com/jupyterhub/jupyterhub/pull/2648 

## Reproduce

1. Ensure the hubUser name contains a backslash, or perhaps other characters that should be escaped.
2. Start JupyterLab in the webbrowser.
3. See no page loading.
4. Open the webbrowser console.
5. See the JSON parse error.

## Expected behavior

Serve a properly escaped hubUser name in the JSON, so the frontend can start.

## Context

Docker image jupyterhub/k8s-singleuser-sample:0.9-b51ffeb

Started using `jupyter-labhub` command

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/opt/conda/bin
	/opt/conda/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/opt/conda/bin
	/opt/conda/lib/python36.zip
	/opt/conda/lib/python3.6
	/opt/conda/lib/python3.6/lib-dynload
	/opt/conda/lib/python3.6/site-packages

sys.executable:
	/opt/conda/bin/python3.6

sys.version:
	3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) 
	[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]

platform.platform():
	Linux-4.19.50-coreos-r1-x86_64-with-debian-buster-sid

which -a jupyter:
	/opt/conda/bin/jupyter
	/opt/conda/bin/jupyter

pip list:
	alembic (0.9.9)
	appdirs (1.4.3)
	asn1crypto (0.24.0)
	async-generator (1.10)
	attrs (18.1.0)
	Automat (0.0.0)
	backcall (0.1.0)
	bleach (2.1.4)
	certifi (2018.8.13)
	cffi (1.11.5)
	chardet (3.0.4)
	conda (4.5.8)
	constantly (15.1.0)
	cryptography (2.2.1)
	decorator (4.3.0)
	entrypoints (0.2.3)
	html5lib (1.0.1)
	hyperlink (17.3.1)
	idna (2.7)
	incremental (17.5.0)
	ipykernel (4.8.2)
	ipython (6.5.0)
	ipython-genutils (0.2.0)
	jedi (0.12.1)
	Jinja2 (2.10)
	jsonschema (2.6.0)
	jupyter-client (5.2.3)
	jupyter-core (4.4.0)
	jupyterhub (0.9.2)
	jupyterlab (0.34.0)
	jupyterlab-launcher (0.13.1)
	Mako (1.0.7)
	MarkupSafe (1.0)
	mistune (0.8.3)
	nbconvert (5.3.1)
	nbformat (4.4.0)
	nbgitpuller (0.6.1)
	notebook (5.6.0)
	pamela (0.3.0)
	pandocfilters (1.4.2)
	parso (0.3.1)
	pexpect (4.6.0)
	pickleshare (0.7.4)
	pip (9.0.3)
	prometheus-client (0.3.0)
	prompt-toolkit (1.0.15)
	ptyprocess (0.6.0)
	pyasn1 (0.4.4)
	pyasn1-modules (0.2.1)
	pycosat (0.6.3)
	pycparser (2.18)
	pycurl (7.43.0.2)
	Pygments (2.2.0)
	pyOpenSSL (18.0.0)
	PySocks (1.6.8)
	python-dateutil (2.7.3)
	python-editor (1.0.3)
	python-oauth2 (1.0.1)
	pyzmq (17.1.2)
	requests (2.19.1)
	ruamel-yaml (0.15.44)
	Send2Trash (1.5.0)
	service-identity (17.0.0)
	setuptools (40.0.0)
	simplegeneric (0.8.1)
	six (1.11.0)
	SQLAlchemy (1.2.11)
	terminado (0.8.1)
	testpath (0.3.1)
	tornado (5.1)
	traitlets (4.3.2)
	Twisted (18.7.0)
	urllib3 (1.23)
	wcwidth (0.1.7)
	webencodings (0.5)
	wheel (0.31.1)
	zope.interface (4.5.0)

conda list:
	# packages in environment at /opt/conda:
	#
	# Name                    Version                   Build  Channel
	alembic                   0.9.9                      py_0    conda-forge
	appdirs                   1.4.3                      py_1    conda-forge
	asn1crypto                0.24.0                     py_1    conda-forge
	async_generator           1.10                       py_0    conda-forge
	attrs                     18.1.0                     py_1    conda-forge
	automat                   0.7.0                    py36_0    conda-forge
	backcall                  0.1.0                      py_0    conda-forge
	bleach                    2.1.4                      py_0    conda-forge
	ca-certificates           2018.8.13            ha4d7672_0    conda-forge
	certifi                   2018.8.13                py36_0    conda-forge
	cffi                      1.11.5                   py36_0    conda-forge
	chardet                   3.0.4                    py36_2    conda-forge
	conda                     4.5.8                    py36_1    conda-forge
	conda-env                 2.6.0                         0    conda-forge
	configurable-http-proxy   3.1.0                   node8_1    conda-forge
	constantly                15.1.0                     py_0    conda-forge
	cryptography              2.2.1            py36hdffb7b8_1    conda-forge
	decorator                 4.3.0                      py_0    conda-forge
	entrypoints               0.2.3                    py36_1    conda-forge
	gmp                       6.1.2                hfc679d8_0    conda-forge
	html5lib                  1.0.1                      py_0    conda-forge
	hyperlink                 17.3.1                     py_0    conda-forge
	idna                      2.7                      py36_2    conda-forge
	incremental               17.5.0                     py_0    conda-forge
	ipykernel                 4.8.2                    py36_0    conda-forge
	ipython                   6.5.0                    py36_0    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	jedi                      0.12.1                   py36_0    conda-forge
	jinja2                    2.10                       py_1    conda-forge
	jsonschema                2.6.0                    py36_1    conda-forge
	jupyter_client            5.2.3                      py_1    conda-forge
	jupyter_core              4.4.0                      py_0    conda-forge
	jupyterhub                0.9.2                    py36_0    conda-forge
	jupyterlab                0.34.0                   py36_0    conda-forge
	jupyterlab_launcher       0.13.1                     py_2    conda-forge
	libcurl                   7.61.0               h1ad7b7a_0    defaults
	libedit                   3.1.20170329                  0    conda-forge
	libffi                    3.2.1                         3    conda-forge
	libgcc                    7.2.0                h69d50b8_2    conda-forge
	libgcc-ng                 7.2.0                hdf63c60_3    defaults
	libsodium                 1.0.16                        0    conda-forge
	libssh2                   1.8.0                h5b517e9_2    conda-forge
	libstdcxx-ng              7.2.0                hdf63c60_3    defaults
	mako                      1.0.7                      py_1    conda-forge
	markupsafe                1.0                      py36_0    conda-forge
	mistune                   0.8.3            py36h470a237_2    conda-forge
	nbconvert                 5.3.1                      py_1    conda-forge
	nbformat                  4.4.0                      py_1    conda-forge
	nbgitpuller               0.6.1                     <pip>
	ncurses                   5.9                          10    conda-forge
	nodejs                    8.10.0                        0    conda-forge
	notebook                  5.6.0                    py36_0    conda-forge
	openssl                   1.0.2o               h470a237_1    conda-forge
	pamela                    0.3.0                    py36_0    conda-forge
	pandoc                    2.2.2                         1    conda-forge
	pandocfilters             1.4.2                      py_1    conda-forge
	parso                     0.3.1                      py_0    conda-forge
	pexpect                   4.6.0                    py36_0    conda-forge
	pickleshare               0.7.4                    py36_0    conda-forge
	pip                       9.0.3                    py36_0    conda-forge
	prometheus_client         0.3.0                      py_0    conda-forge
	prompt_toolkit            1.0.15                   py36_0    conda-forge
	ptyprocess                0.6.0                    py36_0    conda-forge
	pyasn1                    0.4.4                      py_0    conda-forge
	pyasn1-modules            0.2.1                      py_0    conda-forge
	pycosat                   0.6.3                    py36_0    conda-forge
	pycparser                 2.18                       py_1    conda-forge
	pycurl                    7.43.0.2         py36hb7f436b_0    defaults
	pygments                  2.2.0                      py_1    conda-forge
	pyopenssl                 18.0.0                   py36_0    conda-forge
	pysocks                   1.6.8                    py36_1    conda-forge
	python                    3.6.5                         1    conda-forge
	python-dateutil           2.7.3                      py_0    conda-forge
	python-editor             1.0.3                      py_0    conda-forge
	python-oauth2             1.0.1                    py36_0    conda-forge
	pyzmq                     17.1.2           py36hae99301_0    conda-forge
	readline                  7.0                           0    conda-forge
	requests                  2.19.1                   py36_1    conda-forge
	ruamel_yaml               0.15.44          py36h470a237_0    conda-forge
	send2trash                1.5.0                      py_0    conda-forge
	service_identity          17.0.0                     py_0    conda-forge
	setuptools                40.0.0                   py36_0    conda-forge
	simplegeneric             0.8.1                      py_1    conda-forge
	six                       1.11.0                   py36_1    conda-forge
	sqlalchemy                1.2.11           py36h470a237_0    conda-forge
	sqlite                    3.20.1                        2    conda-forge
	terminado                 0.8.1                    py36_0    conda-forge
	testpath                  0.3.1                    py36_0    conda-forge
	tini                      0.18.0               h470a237_1    conda-forge
	tk                        8.6.8                         0    conda-forge
	tornado                   5.1              py36h470a237_1    conda-forge
	traitlets                 4.3.2                    py36_0    conda-forge
	twisted                   18.7.0           py36h14c3975_1    defaults
	urllib3                   1.23                     py36_0    conda-forge
	wcwidth                   0.1.7                      py_1    conda-forge
	webencodings              0.5                      py36_0    conda-forge
	wheel                     0.31.1                   py36_0    conda-forge
	xz                        5.2.3                         0    conda-forge
	yaml                      0.1.7                         0    conda-forge
	zeromq                    4.2.5                hfc679d8_5    conda-forge
	zlib                      1.2.11               h470a237_3    conda-forge
	zope.interface            4.5.0            py36h470a237_0    conda-forge
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 2019-08-14 05:37:40.440 SingleUserLabApp application:177] Searching ['/home/jovyan', '/home/jovyan/.jupyter', '/opt/conda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2019-08-14 05:37:40.441 SingleUserLabApp application:555] Looking for jupyter_config in /etc/jupyter
[D 2019-08-14 05:37:40.441 SingleUserLabApp application:555] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2019-08-14 05:37:40.442 SingleUserLabApp application:555] Looking for jupyter_config in /opt/conda/etc/jupyter
[D 2019-08-14 05:37:40.442 SingleUserLabApp application:555] Looking for jupyter_config in /home/jovyan/.jupyter
[D 2019-08-14 05:37:40.447 SingleUserLabApp application:555] Looking for jupyter_config in /home/jovyan
[D 2019-08-14 05:37:40.452 SingleUserLabApp application:555] Looking for jupyter_notebook_config in /etc/jupyter
[D 2019-08-14 05:37:40.453 SingleUserLabApp application:577] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
[D 2019-08-14 05:37:40.453 SingleUserLabApp application:555] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 2019-08-14 05:37:40.454 SingleUserLabApp application:555] Looking for jupyter_notebook_config in /opt/conda/etc/jupyter
[D 2019-08-14 05:37:40.454 SingleUserLabApp application:577] Loaded config file: /opt/conda/etc/jupyter/jupyter_notebook_config.json
[D 2019-08-14 05:37:40.454 SingleUserLabApp application:555] Looking for jupyter_notebook_config in /home/jovyan/.jupyter
[D 2019-08-14 05:37:40.459 SingleUserLabApp application:555] Looking for jupyter_notebook_config in /home/jovyan
[W 2019-08-14 05:37:40.467 SingleUserLabApp configurable:168] Config option `open_browser` not recognized by `SingleUserLabApp`.  Did you mean `browser`?
[D 2019-08-14 05:37:40.806 SingleUserLabApp config_manager:98] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 2019-08-14 05:37:40.806 SingleUserLabApp config_manager:98] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2019-08-14 05:37:40.807 SingleUserLabApp config_manager:98] Paths used for configuration of jupyter_notebook_config: 
    	/opt/conda/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/opt/conda/etc/jupyter/jupyter_notebook_config.d/nbgitpuller.json
    	/opt/conda/etc/jupyter/jupyter_notebook_config.json
[D 2019-08-14 05:37:40.810 SingleUserLabApp config_manager:98] Paths used for configuration of jupyter_notebook_config: 
    	/home/jovyan/.jupyter/jupyter_notebook_config.json
[I 2019-08-14 05:37:40.814 SingleUserLabApp extension:59] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2019-08-14 05:37:40.814 SingleUserLabApp extension:60] JupyterLab application directory is /opt/conda/share/jupyter/lab
[W 2019-08-14 05:37:40.824 SingleUserLabApp labapp:215] JupyterLab server extension not enabled, manually loading...
[I 2019-08-14 05:37:40.826 SingleUserLabApp extension:59] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2019-08-14 05:37:40.826 SingleUserLabApp extension:60] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2019-08-14 05:37:40.832 SingleUserLabApp singleuser:405] Starting jupyterhub-singleuser server version 0.9.2
[W 2019-08-14 05:37:40.838 SingleUserLabApp _version:50] jupyterhub version 1.0.1dev != jupyterhub-singleuser version 0.9.2. This could cause failure to authenticate and result in redirect loops!
[I 2019-08-14 05:37:40.839 SingleUserLabApp notebookapp:1685] Serving notebooks from local directory: /home/jovyan
[I 2019-08-14 05:37:40.839 SingleUserLabApp notebookapp:1685] The Jupyter Notebook is running at:
[I 2019-08-14 05:37:40.839 SingleUserLabApp notebookapp:1685] http://(jupyter-organization-5cuserid or 127.0.0.1):8888/user/organization%5Cuserid/?token=b03156d6071240a296650bd2cbdd61ae
[I 2019-08-14 05:37:40.839 SingleUserLabApp notebookapp:1686] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2019-08-14 05:37:40.872 SingleUserLabApp notebookapp:1726] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://(jupyter-organization-5cuserid or 127.0.0.1):8888/user/organization%5Cuserid/?token=b03156d6071240a296650bd2cbdd61ae
[I 2019-08-14 05:37:41.454 SingleUserLabApp log:158] 302 GET /user/organization%5Cuserid/ -> /user/organization%5Cuserid/lab? (@172.16.139.148) 0.96ms
[I 2019-08-14 05:37:42.046 SingleUserLabApp log:158] 302 GET /user/organization%5Cuserid/ -> /user/organization%5Cuserid/lab? (@213.93.133.251) 0.87ms
[D 2019-08-14 05:37:42.262 SingleUserLabApp auth:421] No user identified
[D 2019-08-14 05:37:42.265 SingleUserLabApp auth:741] Redirecting to login url: /hub/api/oauth2/authorize?client_id=jupyterhub-user-organization%255Cuserid&redirect_uri=%2Fuser%2Forganization%255Cuserid%2Foauth_callback&response_type=code&state=eyJ1dWlkIjogIjNiYTE3NzVhZTI5ZTQ5MjQ4ZjYzMzY5MGM1ZWMwNDY4IiwgIm5leHRfdXJsIjogIi91c2VyL2FsbGlhbmRlciU1Q2FsNDk2NS9sYWI_In0
[I 2019-08-14 05:37:42.265 SingleUserLabApp log:158] 302 GET /user/organization%5Cuserid/lab? -> /hub/api/oauth2/authorize?client_id=jupyterhub-user-organization%255Cuserid&redirect_uri=%2Fuser%2Forganization%255Cuserid%2Foauth_callback&response_type=code&state=[secret] (@213.93.133.251) 3.53ms
[D 2019-08-14 05:37:42.668 SingleUserLabApp auth:421] No user identified
[D 2019-08-14 05:37:42.706 SingleUserLabApp auth:263] Cache miss: token:e23772b77e7945cda92ddb7141dade81:UxBGvFBFlLRtaLhct7VrI9SNGn8oMH
[D 2019-08-14 05:37:42.719 SingleUserLabApp auth:269] Received request from Hub user {'kind': 'user', 'name': 'organization\\userid', 'admin': False, 'groups': [], 'server': '/user/organization%5Cuserid/', 'pending': None, 'created': '2018-09-21T10:12:47.246366Z', 'last_activity': '2019-08-14T05:37:42.718385Z', 'servers': None}
[I 2019-08-14 05:37:42.720 SingleUserLabApp auth:875] Logged-in user {'kind': 'user', 'name': 'organization\\userid', 'admin': False, 'groups': [], 'server': '/user/organization%5Cuserid/', 'pending': None, 'created': '2018-09-21T10:12:47.246366Z', 'last_activity': '2019-08-14T05:37:42.718385Z', 'servers': None}
[D 2019-08-14 05:37:42.720 SingleUserLabApp auth:656] Setting oauth cookie for 213.93.133.251: jupyterhub-user-organization%5Cuserid, {'path': '/user/organization%5Cuserid/', 'httponly': True, 'secure': True}
[I 2019-08-14 05:37:42.721 SingleUserLabApp log:158] 302 GET /user/organization%5Cuserid/oauth_callback?code=[secret]&state=[secret] -> /user/organization%5Cuserid/lab? (@213.93.133.251) 53.11ms
[D 2019-08-14 05:37:42.842 SingleUserLabApp auth:778] Allowing whitelisted Hub user organization\userid
[D 2019-08-14 05:37:42.843 SingleUserLabApp handlers:264] Using contents: services/contents
[I 2019-08-14 05:37:42.853 SingleUserLabApp log:158] 200 GET /user/organization%5Cuserid/lab? (organization\userid@213.93.133.251) 11.91ms
[D 2019-08-14 05:37:43.229 SingleUserLabApp auth:778] Allowing whitelisted Hub user organization\userid
[D 2019-08-14 05:37:43.229 SingleUserLabApp handlers:770] Path vendors~main.93d7496a11ffa20d4292.js served from /opt/conda/share/jupyter/lab/static/vendors~main.93d7496a11ffa20d4292.js
[D 2019-08-14 05:37:43.235 SingleUserLabApp auth:778] Allowing whitelisted Hub user organization\userid
[D 2019-08-14 05:37:43.236 SingleUserLabApp handlers:770] Path main.cb85790a497dbbee4e40.js served from /opt/conda/share/jupyter/lab/static/main.cb85790a497dbbee4e40.js
[D 2019-08-14 05:37:43.237 SingleUserLabApp log:158] 200 GET /user/organization%5Cuserid/lab/static/main.cb85790a497dbbee4e40.js (organization\userid@213.93.133.251) 2.51ms
[D 2019-08-14 05:37:43.418 SingleUserLabApp log:158] 200 GET /user/organization%5Cuserid/lab/static/vendors~main.93d7496a11ffa20d4292.js (organization\userid@213.93.133.251) 190.32ms
[D 2019-08-14 05:37:44.108 SingleUserLabApp auth:778] Allowing whitelisted Hub user organization\userid
[D 2019-08-14 05:37:44.108 SingleUserLabApp handlers:770] Path base/images/favicon.ico served from /opt/conda/lib/python3.6/site-packages/notebook/static/base/images/favicon.ico
[D 2019-08-14 05:37:44.110 SingleUserLabApp log:158] 200 GET /user/organization%5Cuserid/static/base/images/favicon.ico (organization\userid@213.93.133.251) 2.72ms
[D 2019-08-14 05:37:44.283 SingleUserLabApp auth:778] Allowing whitelisted Hub user organization\userid
[D 2019-08-14 05:37:44.284 SingleUserLabApp handlers:770] Path vendors~main.93d7496a11ffa20d4292.js.map served from /opt/conda/share/jupyter/lab/static/vendors~main.93d7496a11ffa20d4292.js.map
[D 2019-08-14 05:37:44.285 SingleUserLabApp log:158] 304 GET /user/organization%5Cuserid/lab/static/vendors~main.93d7496a11ffa20d4292.js.map (organization\userid@213.93.133.251) 1.85ms
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
SyntaxError: JSON.parse: bad escaped character at line 4 column 28 of the JSON data
</pre>
</details>

**Comment by nicorikken** [comment]
At this point I'm not sure where the JSON `jupyter-config-data` gets generated. I'll take a look at it and try to provide a PR to resolve this issue.

**Comment by nicorikken** [comment]
I now see the JSON is build in the [jupyterlab_server](https://github.com/jupyterlab/jupyterlab_server) project. Which in turn [loads it from the page_config.json file in the settings dir](https://github.com/jupyterlab/jupyterlab_server/blob/d55c359fdc6b15167bddfa0a858d21666fb865e3/jupyterlab_server/handlers.py#L94).
In our case this is likely to originate from our Kubernetes deployment using [zero-to-jupyterhub-k8s](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/)

**Comment by nicorikken** [comment]
I see the Jupyterlab pod is created with an evironment variable `JUPYTERHUB_USER` with the value `organization\userid`.

**Comment by nicorikken** [comment]
If I understand correctly that environment variable is read in the [jupyterhub singleuser command](https://github.com/jupyterhub/jupyterhub/blob/17aee17c5f6a949038cc9bed8c64dad8b2b1831c/jupyterhub/singleuser.py#L253)

**Comment by nicorikken** [comment]
And in the [jupyterlab code](https://github.com/jupyterlab/jupyterlab/blob/b386dfb52e027d34dfab08087643d67c3469a7de/jupyterlab/extension.py#L213) the `hubUser` property is set based on the notebook settings

**Comment by nicorikken** [comment]
To solve this issue, I think the user value should not be escaped, neither should be the hubUser value in Python, but it should be escaped when it is printed to JSON in the index.html

**Comment by blink1073** [comment]
I think perhaps we should base64 encode all of the page config values and decode in the client.  We'd lose the immediate visibility we have now but avoid issues like this in the future.

**Comment by nicorikken** [comment]
This PR fixes the issue: https://github.com/jupyterlab/jupyterlab_server/pull/73

@blink1073 base64 encoding loses readability, but then again I've noticed similar escaping issues in jupyterhub as well, so the escaping edge-cases are neglected in the development process. Base64 might help there. Assuming that the API's won't change rapidly, proper escaping will be good for a while.

**Comment by blink1073** [comment]
I like the approach of escaping vs encoding, I'll play with this some this morning as well.  Thanks for the flag and the fix!

**Comment by nicorikken** [comment]
Can I expect a PR merge and PyPI merge soon? Ideally I'd like to upgrade our production system, which is dependent on this fix. If it takes a week or more, no problem, but then I'll roll my own fork for the time being instead of awaiting the updated package release.

**Comment by blink1073** [comment]
I'll make a release today (Central US afternoon time).

**Comment by blink1073** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab_server/pull/73 and the 1.0.1 release of the server.  (conda-forge pending).   Thanks @nicorikken!

**Comment by nicorikken** [comment]
@blink1073 Terrific, thank you for responding so quickly!

**Comment by nicorikken** [comment]
I've included this in my notebook Dockerfile (based on `jupyter/scipy-notebook`) using:
```
RUN conda update --quiet --yes --no-update-deps -c conda-forge jupyterlab_server
```
