### ISSUE TITLE
Shift-Enter shortcut only works with "left" shift key.

### ISSUE THREAD

**Issue by sloughin** [jupyterlab/jupyterlab#7010]
Running Jupyter in a docker container on Ubuntu 18.04 server.  I tie into the service from my desktop iMac using Safari or Chrome.  When in a notebook, I try to use the shortcut [Shift]-[Enter] to execute the current cell, but it does not work, it instead adds a "newline" in the cell  Turns out I'm using the [Shift] key on the right hand side of the keyboard, since one can do [Shift]-[Enter] one handed that way.  For kicks, I try holding the left side [Shift] key down and hitting [Enter] and it WORKS!  I try to edit the keyboard shortcuts to correct this but it doesn't seem to distinguish between left and right [Shift] keys.  While I can type with both hands now, being able to execute the code with a single hand would have been useful when my left hand was out of commission due to a broken finger.  I would think that others who do one handed typing might also find this useful.

**Comment by sloughin** [comment]
Sorry need to put detail in first.

**Comment by jasongrout** [comment]
Right-Shift-Enter executes a cell for me with JLab 1.0.5 conda-forge package, Firefox 68, on macOS. Can you give some more information like jlab version and browser and version?

**Comment by jasongrout** [comment]
Also, could you follow the diagnosis guidelines at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to help narrow down if this is a jlab issue or an issue from another component in your system?

**Comment by sloughin** [comment]
Ok - I performed the following tests, per the guidelines:

On my ubuntu server, I installed the jlab-test clean environment and ran jupyter lab, and it opened a browser on my ubuntu server, and I tested the right side [Shift]-[Enter] and, as you said, it worked.

On my iMac, I then installed the jlab-test clean environment and ran jupyter lab, and it opened Safari on my iMac, and I tested the right side [Shift]-[Enter] and it failed as before, instead inserting a newline character.  It would appear that the bug is a mac-specific behavior. 

I also tested my original docker-container based jupyter service while on my ubuntu machine and as long as I have the browser running on the ubuntu server, right-side [Shift]-[Enter] works correctly, however, if I'm connected to the same service from the iMac, the right-side [Shift]-[Enter] misbehaves.  

My iMac is running macOS Mojave (10.14.6) and I can reproduce the issue with Chrome (Version 76.0.3809.100 (Official Build) (64-bit)) and Safari (Version 12.1.2 (14607.3.9)) -- haven't tried other browsers on the mac.  My Ubuntu server is running 18.04.3 LTS and when I run jupyter lab in the test environment, it activates Google Chrome  (Version 76.0.3809.100 (Official Build) (64-bit)) which would seem to be the same version as the iMac's.

**Comment by jasongrout** [comment]
Thanks, that is helpful.

I tried with the jlab-test environment, on macOS 10.14.6, using Chrome 76.0.3809.100 (Official Build) (64-bit), and right side shift-enter executed a notebook cell and did not enter a newline.

1. Do you see any errors, particularly javascript errors in the browser js console?
2. Do you have any browser extensions installed?

This is jlab 1.0.5, right?

**Comment by sloughin** [comment]
jupyter is 4.4.0 -- I just installed today per the instructions for conda (though I used miniconda) -- here's what I see:
(base) steve-imac:~ stephenloughin$ cd dev/test
(base) steve-imac:test stephenloughin$ jupyter --version
4.4.0
(base) steve-imac:test stephenloughin$ conda activate jlab-test
(jlab-test) steve-imac:test stephenloughin$ jupyter --version
4.4.0
(jlab-test) steve-imac:test stephenloughin$ jlab --version
-bash: jlab: command not found
(jlab-test) steve-imac:test stephenloughin$ 

I don't have dev extensions on Safari, but I do for Chrome.  Here's what I see in the console:
ing application in workspace: "/lab"
default.js:56 Starting WebSocket: ws://localhost:8888/api/kernels/d01da2fe-5a19-46f1-afe7-3382214511d7
default.js:1456 Kernel: connected (d01da2fe-5a19-46f1-afe7-3382214511d7)
default.js:56 Starting WebSocket: ws://localhost:8888/api/kernels/d01da2fe-5a19-46f1-afe7-3382214511d7
default.js:1456 Kernel: connected (d01da2fe-5a19-46f1-afe7-3382214511d7)
And that doesn't change regardless of whether I do the left side [Shift]-[Enter] or the right-side [Shift]-[Enter]

**Comment by sloughin** [comment]
I've looked through the jlab-test directory in the miniconda3 folder and I don't see an obvious version marker but I ran the conda create -n jlab-test command today, so I assume it would be the current version.

**Comment by jasongrout** [comment]
`jupyter lab --version`, or you could see it in `conda env list`

**Comment by sloughin** [comment]
(jlab-test) steve-imac:test stephenloughin$ jupyter lab --version
1.0.5
(jlab-test) steve-imac:test stephenloughin$

**Comment by jasongrout** [comment]
I can't think of anything obvious, other than perhaps there is a browser plugin preventing something, or perhaps a custom jupyterlab keybinding taking effect. It would be great if you could reproduce it on a different computer.

**Comment by vidartf** [comment]
Some shots in the dark:
- Does the right shift button work for other things? (e.g. RShift + a = A)
- Does the right shift combine correctly with non-letter keys in other apps? (e.g. notebook classic, a non-browser based app)
- What kind of keyboard layout / input language do you have?

**Comment by sloughin** [comment]
aaaaaaAAARGH!  why didn't I think of this?  It seems the right-shift key is dead -- I'll try a different keyboard.  Thanks for your help!

**Comment by vidartf** [comment]
No worries, and good luck :)
