### ISSUE TITLE
Advanced settings editor not launching

### ISSUE THREAD

**Issue by KirkHadley** [jupyterlab/jupyterlab#7012]
## Description

 I just installed jupyterlab. When I click advanced settings editor, nothing happens.

## Reproduce

1. Go to settings
2. Click on 'Advanced Settings Editor'
3. Nothing happens

## Expected behavior
Expected advanced settings editor dialogue to open

## Context

- Operating System and version: Ubuntu 18.04
- Browser and version: Chrome 76
- JupyterLab version: 1.0.2

**Comment by jasongrout** [comment]
It's certainly working for me in 1.0.5. Can you try to diagnose the issue a bit more using the guidelines at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html and post your results here?

**Comment by wolfv** [comment]
I have the same issue. i wonder if it's my or some other extensions fault. I can't see any error, wether in the frontend console, nor in the backend terminal... i just upgraded the conda jupyterlab package and let's see if it works.

**Comment by ian-r-rose** [comment]
@wolfv I wonder if this might be a similar problem to https://github.com/dask/dask-labextension/issues/61 . I never really solved it to my satisfaction -- there may be an underlying bug in the Widget Tracker state restoration causing this.

Can you try to clear the state database to see if that fixes your issue? (go to `/lab?reset`)

**Comment by wolfv** [comment]
I'll try that! Most (all) other buttons and settings in the menu are working fine as far as i can tell. didn't check all of them though.
It's happening on Firefox and Chrome.

**Comment by wolfv** [comment]
jep, reset did it! Thanks!!! @ian-r-rose

**Comment by wolfv** [comment]
maybe somehow it thinks that it has restored the settings window when it didn't? I think you can have only one settings window open at a time?

**Comment by ian-r-rose** [comment]
@KirkHadley can you check if the above also resolves the issue for you?

Possible other xref: #7082

**Comment by jasongrout** [comment]
For what it's worth, I saw something similar in developing the log console extension, which only puts one window on the page. Sometimes, it appeared that the system thought that the activity was restored, but in reality it had been created and added to the DOM, but then for some reason removed from the DOM but not disposed at some point in the code where it was restoring layout. Sorry, I should have logged an issue. Resetting the workspace layout (i.e., clearing out workspace layouts) seems to have fixed the issue.

**Comment by ian-r-rose** [comment]
@jasongrout Yep, sounds like the same issue to the one I was seeing. #7082 was my attempt to track it down, but I never was really satisfied.

**Comment by kirill5pol** [comment]
> Can you try to clear the state database to see if that fixes your issue? (go to `/lab?reset`)

I had the same problem and `/lab?reset` worked for me too. Thanks!

**Comment by strickvl** [comment]
`/lab?reset` worked for me as well

**Comment by LintangWisesa** [comment]
> @wolfv I wonder if this might be a similar problem to [dask/dask-labextension#61](https://github.com/dask/dask-labextension/issues/61) . I never really solved it to my satisfaction -- there may be an underlying bug in the Widget Tracker state restoration causing this.
> 
> Can you try to clear the state database to see if that fixes your issue? (go to `/lab?reset`)

`/lab?reset` also worked for me. Thanks.

**Comment by claudio-ebel** [comment]
Using `/lab?reset` was the solution for my problem as well.

**Comment by Jacques2101** [comment]
hi, i have the same problem. Impossible to launch advanced setting on Jupyterlab (3.0 version). 
It seems that `/lab?reset` solved the same problem as mine but how to do that ? Where it is ? 
Thx.

**Comment by polzounov** [comment]
@Jacques2101 You simply append `/lab/reset?` to the end of the URL in your browser

**Comment by Omid888** [comment]
/lab?reset
worked for me. thank you.

**Comment by e410672161** [comment]
Hi, I got the same issue after adding shortcuts, then I can't lanuch the editors anymore (jupyter lab ver. 3.0.5 ).

`/lab?reset` works, thanks a lot

**Comment by w2davids** [comment]
Experienced the same issue Version 3.0.10

**Comment by Om4AI** [comment]
I even updated my jupyter lab( to latest version) but still the same issue !!

**Comment by BugApe** [comment]
> @Jacques2101 You simply append `/lab/reset?` to the end of the URL in your browser
This worked!

**Comment by ramiraza** [comment]
Nice. It solved it for me too.

**Comment by Oeaps** [comment]
it works, thanks

**Comment by bhrdj** [comment]
Just experienced this issue. I resolved it directly as described above.

For other humble n00bs who may need things spelled out a little more or else spend 15min scouring the interwebs (like me):

-  jupyter lab for me launches at: http://localhost:8888/lab
- to implement this fix, I needed to go to the url: http://localhost:8888/lab?reset
- YMMV
