### ISSUE TITLE
docmanager not compiled to ES5 / ES6 syntax

### ISSUE THREAD

**Issue by fridgerator** [jupyterlab/jupyterlab#7021]
## Description

Within my javascript (typescript) aplication, when I try to `import` from `@jupyterlab/docmanager` with docmanager version 1.0.3, I get an `unexpected token export` error.

If I inspect `node_modules/@jupyterlab/docmanager/lib/index.js` I see that there are `export` statements.  However if I view another module, for instance `@jupyterlab/coreutils/lib/index.js` I can see that it has been transpiled to ES5 / ES6 syntax correctly like: `__export(require("./activitymonitor"))`.  Older versions of docmanager (0.15.4) were also transpiled correctly.

**edit**:
Actually now that I browse more @jupyterlab modules folders I can see others are also not transpiled (completer, codemirror, codeeditor, etc...)

## Reproduce

Try to `import { DocumentManager } from '@jupyterlab/docmanager'` in a separate javascript application.

## Expected behavior

A user should be able to use jupyterlab npm modules in an external application.

## Context

- Operating System and version: Arch Linux, Mac, WIndows ( unrelated )
- Browser and version: Chrome 76.0.3809.87 ( unrelated )
- JupyterLab version:

```
"@jupyter-widgets/base": "^2.0.1",
"@jupyter-widgets/controls": "^1.5.2",
"@jupyter-widgets/html-manager": "^0.18.3",
"@jupyterlab/completer": "^1.0.3",
"@jupyterlab/docmanager": "^1.0.3",
"@jupyterlab/notebook": "^1.0.3",
"@jupyterlab/services": "^4.0.3",
"@jupyterlab/theme-light-extension": "^1.0.3",
"@phosphor/disposable": "^1.3.0",
"@phosphor/widgets": "^1.9.0",
```

**Comment by fridgerator** [comment]
docmanager previously had `module` and `target` in tsconfig: [link](https://github.com/jupyterlab/jupyterlab/blob/6d4c68f1e9f897eca3c4e549fe351342a1970aaf/packages/docmanager/tsconfig.json)

current version of docmanager does not have `module` or `target in tsconfig: [link](https://github.com/jupyterlab/jupyterlab/blob/master/packages/docmanager/tsconfig.json)

current version of coreutils has `module` in tsconfig: [link](https://github.com/jupyterlab/jupyterlab/blob/master/packages/coreutils/tsconfig.json)

**Comment by jasongrout** [comment]
We definitely can't do that in the 1.x releases, since that would be backwards incompatible with 1.0.

Just curious, what environment are you in that you need es6/commonjs? In moving to es2017 and esnext, we saw that our supported browsers have supported those for quite a while.

One possibility is adding a libes6 directory and compiling a separate set of files to there. That would be a maintenance burden, of course, so it would be good to know how often it is needed.

**Comment by fridgerator** [comment]
I'm starting to think that his may be an issue with my webpack or ts configuration.

My environment is Electron, using [electron-webpack](https://github.com/electron-userland/electron-webpack/tree/master/packages/electron-webpack).  `es2017` and `esnext` are [definitely supported](https://github.com/electron-userland/electron-webpack/blob/master/packages/electron-webpack/tsconfig-base.json)

**Comment by fridgerator** [comment]
I will just assume that it is the case that its a misconfiguration on my end.  My apologies.

**Comment by jasongrout** [comment]
No problem. If you figure it out, it would be great if you followed up here so others can benefit from your experience.

**Comment by fridgerator** [comment]
I will definitely follow up here when I resolve my issue :+1:

**Comment by fridgerator** [comment]
I've resolved the issue, in electron-webpack the jupyterlab modules needed to be [whitelisted](https://webpack.electron.build/configuration#white-listing-externals).

**Comment by jasongrout** [comment]
Great, thanks for posting a resolution.
