### ISSUE TITLE
Do not package js sourcemaps by default

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7041]
In https://github.com/conda-forge/jupyterlab-feedstock/issues/155, @jcrist suggested not packaging the js sourcemap files since they are quite large. I agree. It would be great if we could delete those files from the stock package. If people want them back, they can install node and do a simple `jupyter lab build`.

Deleting the map files from the 1.0.6 wheel seemed to shrink the wheel from about 16M to about 6.5M, so it is a huge savings.

**Comment by jasongrout** [comment]
Maybe the simplest way to do this is to delete the map files after we build them in the staging directory in the release process: https://github.com/jupyterlab/jupyterlab/blob/3592afd328116a588e3307b4cdd9bcabc7fe92bb/buildutils/src/update-core-mode.ts#L49

Another way to do it is to have one more webpack build that does not build the sourcemap files.

**Comment by vidartf** [comment]
If we don't include the source maps, it would be great to have a service that could translate a stack trace in a bug report,  given a version number. Or at least store the source maps as an artifact on GH so we can look it up if need be.
