### ISSUE TITLE
User Settings (Keyboard Shortcuts) from 0.35.5 to 1.05 not migrated. 

### ISSUE THREAD

**Issue by JohnOmernik** [jupyterlab/jupyterlab#7050]
## Description
 I had users running JupyterLab 0.35.5, and we upgraded to 1.0.5. They had keyboard shortcuts as defined below that allowed JupyterLab to be like slack. (Enter ran a cell, and Shift-Enter put in a newline). Now, not only will this code not run, but when I modify it use the newer format, nothing actually applies, and the console run keystroke menu item also does nothing. I can't seem to change things, I don't understand the selector. Is it normal for a project to change a format like this, and provide so little documentation as to the change?

Also, why do we have Keyboard Shortcuts under advanced settings, and yet Console Run Command is a separate first class menu item, and it's not clear which is more important?

```json5
  // [missing schema title]
  // [missing schema description]
  "console:linebreak": {
   "command": "console:linebreak",
   "keys": [
    "Shift Enter"
   ],
   "selector": ".jp-CodeConsole-promptCell",
   "title": "Insert Line Break",
   "category": "Console"
  },
  // [missing schema title]
  // [missing schema description]
  "console:run-forced": {
   "command": "console:run-forced",
   "keys": [
    "Enter"
   ],
   "selector": ".jp-CodeConsole-promptCell",
   "title": "Run Cell (forced)",
   "category": "Console"
  },
  // [missing schema title]
  // [missing schema description]
  "runmenu:run": {
   "command": "runmenu:run",
   "keys": [
    "Enter"
   ],
   "selector": "[data-jp-code-runner]",
   "title": "Run",
   "category": "Run Menu"
  },
  // [missing schema title]
  // [missing schema description]
  "notebook:run-cell-and-select-next": {
   "command": "notebook:run-cell-and-select-next",
   "keys": [
    "Enter"
   ],
   "selector": ".jp-Notebook.jp-mod-editMode",
   "title": "Run Cell and Select Next",
   "category": "Notebook Operations"
  }
```

## Reproduce

Use the above code block as a user code

## Expected behavior

Keyboard shortcuts should be like Slack

## Context

Shortcuts on per user settings.

**Comment by jasongrout** [comment]
Thanks for opening a new issue.

As you may have noticed, we completely rewrote the keyboard shortcut system for 1.0 (actually the entire settings system as well).

We built in a conversion that should convert most keyboard shortcuts. It looks like the selectors on some of your customizations have changed, so would need to be updated. It would be wonderful to have better documentation about any keyboard shortcut migrations, great idea! Would you help by writing up your migration? We'll help you through it.

It looks like you have three basic customizations in what you list. Let's take each one, starting with your keyboard shortcuts for code consoles. Caveat: I don't use slack, so have no idea what makes things like slack. I'm just going off of the customizations you posted here.

> Also, why do we have Keyboard Shortcuts under advanced settings, and yet Console Run Command is a separate first class menu item, and it's not clear which is more important?

For convenience, we put some top-level settings menu entries that control the settings. They are exactly the same as changing the setting in the user overrides (in fact, that's exactly what they do under the hood). 

It looks like you have two shortcuts for the console commands around running. We've added a switch for the "mode" for the console, and then added keyboard shortcuts for each mode, with a selector to tell the difference. (See the dev conversation starting around https://github.com/jupyterlab/jupyterlab/pull/5470#issuecomment-444212025 if you're interested in the technical details and evolution of the system).

For the console run command particularly, if you open the Advanced settings and go to the Code Console section, then toggle the console run shortcut menu entry, you'll see the user override switch between `"interactionMode": "notebook"` and `"interactionMode": "terminal"`. That is exactly what that menu item controls and reflects - if you change the setting manually in the overrides, you'll see the menu item change as well. 

Separately, you'll see that we provide *both* interaction mode keyboard shortcuts, scoped to a new data attribute, for example:

```json5
        {
            "command": "console:linebreak",
            "keys": [
                "Enter"
            ],
            "selector": ".jp-CodeConsole[data-jp-interaction-mode='notebook'] .jp-CodeConsole-promptCell"
        },
        {
            "command": "console:linebreak",
            "keys": [
                "Accel Enter"
            ],
            "selector": ".jp-CodeConsole[data-jp-interaction-mode='terminal'] .jp-CodeConsole-promptCell"
        },
```
This lets us provide defaults keyboard shortcuts for both modes, and lets you customize both modes, and lets you easily switch between the two modes.

As for your particular customization, perhaps just setting the console to interaction mode "terminal" is sufficient, no need to override keyboard shortcuts anymore?



Next:
```json5
  "runmenu:run": {
   "command": "runmenu:run",
   "keys": [
    "Enter"
   ],
   "selector": "[data-jp-code-runner]",
   "title": "Run",
   "category": "Run Menu"
  },
```
It looks like here you are overriding this shortcut (new style), which I got by searching for the command "runmenu:run":

```json5
        {
            "command": "runmenu:run",
            "keys": [
                "Shift Enter"
            ],
            "selector": "[data-jp-code-runner]"
        },
```
It may be enough now to just copy that to the user overrides and delete the "Shift". When I do that, the notebook cells execute when I press enter. Is that what you want?

**Comment by jasongrout** [comment]
(whew, that answer took a long to write up, and probably just as long to read :) Let us know if that helps you migrate, and even better, we'd love if you'd help the documentation by writing up what you did to migrate. We could put something like that help in the changelog, for example.

**Comment by jasongrout** [comment]
Closing as answered.
