### ISSUE TITLE
Incorrect subpath navigation / URL rewrite when using a base path

### ISSUE THREAD

**Issue by kfeinauer** [jupyterlab/jupyterlab#7052]
# Description
It appears that when navigating to a sub-path within JupyterLab directly from the browser, such as the `/lab/tree/Notebook.ipynb` URL, the URL will be incorrectly rewritten with the `/lab` prefix coming before the base URL, where it should come after.

This is happening on JupyterLab version `0.33.12`, which seems to be the highest version I can get by running `pip install jupyterlab --upgrade` on Ubuntu 16, though it appears at first glance that the problematic code has not changed much between the this version and latest (see final comments).

# Repro Steps
1. Create a JupyerLab session with a base URL

```
/usr/local/bin/jupyter lab --LabApp.base_url=/s/test --NotebookApp.base_url=/s/test
```

2. Navigate directly to a notebook in the browser

```
http://localhost:8887/s/test/lab/tree/Notebook.ipynb
```

3. Notice the URL will be rewritten in the browser window to an incorrect path:

`http://localhost:8887/lab/s/test`

4. Attempt to reload the browser page. Because the URL was written incorrectly, you will see a 404 page.

This can cause other problems when hosting the lab application, as the generated `Referrer` header for future pages will be the incorrectly rewritten URL.

# Final Comments
It looks like the problematic code is located here:

https://github.com/jupyterlab/jupyterlab/blob/4e913e665ecc462651a7ffc6a05303de62a57ad8/packages/application-extension/src/index.tsx#L276

https://github.com/jupyterlab/jupyterlab/blob/c250b1530e5c4fc382c3b09c82d5887c7adfe06d/packages/application/src/router.ts#L78-L79

The `base` variable should perhaps be prepended with the actual base URL that the lab app is being hosted out, instead of it just being `lab`, which causes the URL to be rewritten incorrectly.

**Comment by kfeinauer** [comment]
Has anyone been able to take a look at this?

**Comment by jasongrout** [comment]
Can you check with 1.1.4, the latest version?

**Comment by kfeinauer** [comment]
What's the recommended way to get the very latest (besides building from source)? When I fetch on my machine using the instructions here https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html I get the following:

```
pip install jupyterlab

...

Successfully installed jupyterlab-0.33.12
```

**Comment by jasongrout** [comment]
`pip install -U juptyerlab` for upgrading.

**Comment by jasongrout** [comment]
Running `jupyter lab --LabApp.base_url=/s/test --NotebookApp.base_url=/s/test` on the jlab 1.1.4, 1.0.2, and 0.35.4 all seem to give an infinite loop in requesting some content (the server log just keeps scrolling with something like:

```
[W 07:47:23.867 LabApp] 404 GET /api/contents/?content=1&1568904443861 (::1) 1.47ms referer=http://localhost:8889/lab
```
Not sure what the problem there is. Do you see that too?

**Comment by jasongrout** [comment]
CC also @afshin for the url routing question.

**Comment by kfeinauer** [comment]
Whenever I upgrade, I am still stuck on `0.33.12` for Jupyerlab. Is this related to some dependency not being satisfied for later versions? 

Because I'm stuck on this older version, I am not seeing the behavior you are - I see the original behavior noted in the ticket.

**Comment by jasongrout** [comment]
Can you try manually specifying the version? `pip install jupyterlab==1.1.4`

**Comment by kfeinauer** [comment]
Doesn't work, can't find the version:

```
ERROR: Could not find a version that satisfies the requirement jupyterlab==1.1.4 (from versions: 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.13, 0.1.1, 0.1.2, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.15.0, 0.15.1, 0.16.0, 0.16.2, 0.17.0, 0.17.1, 0.17.2, 0.17.4, 0.17.5, 0.18.0.dev1, 0.18.0, 0.18.1, 0.19.0, 0.20.0rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21.0rc1, 0.21.0rc2, 0.21.0rc3, 0.21.0rc4, 0.21.0rc5, 0.21.0, 0.22.0rc0, 0.22.0, 0.22.1, 0.23.0rc0, 0.23.0rc1, 0.23.0, 0.23.1, 0.23.2, 0.24.0rc0, 0.24.0rc1, 0.24.0rc2, 0.24.0, 0.24.1, 0.25.0rc0, 0.25.0rc1, 0.25.0, 0.25.1, 0.25.2rc0, 0.25.2, 0.26.0rc0, 0.26.0rc1, 0.26.0, 0.26.1, 0.26.2, 0.26.3, 0.26.4, 0.26.5, 0.27.0rc0, 0.27.0rc1, 0.27.0rc2, 0.27.0rc3, 0.27.0rc4, 0.27.0rc5, 0.27.0, 0.27.1, 0.27.2, 0.28.0rc0, 0.28.0rc1, 0.28.0rc2, 0.28.0rc3, 0.28.0, 0.28.1, 0.28.2, 0.28.3, 0.28.4, 0.28.5, 0.28.6, 0.28.7, 0.28.8, 0.28.10, 0.28.11, 0.28.12, 0.28.13, 0.28.14, 0.28.15, 0.29.0rc0, 0.29.0, 0.29.1, 0.29.2, 0.30.0rc0, 0.30.0rc1, 0.30.0, 0.30.1, 0.30.2, 0.30.3, 0.30.4, 0.30.5, 0.30.6, 0.31.0rc0, 0.31.0rc1, 0.31.0rc2, 0.31.0, 0.31.1, 0.31.2, 0.31.3, 0.31.4, 0.31.5, 0.31.6, 0.31.7, 0.31.8, 0.31.9, 0.31.10, 0.31.11, 0.31.12, 0.32.0rc0, 0.32.0rc1, 0.32.0, 0.32.1, 0.33.0rc0, 0.33.0rc1, 0.33.0, 0.33.1, 0.33.2, 0.33.3, 0.33.4, 0.33.5, 0.33.6, 0.33.7, 0.33.8, 0.33.9, 0.33.10, 0.33.11, 0.33.12)
ERROR: No matching distribution found for jupyterlab==1.1.4
```

Is this a platform related issue? I am on Ubuntu 16.

**Comment by jasongrout** [comment]
Ah, are you on python 2? We switched to python 3 a while ago.

`pip3 install jupyterlab==1.1.4`

**Comment by kfeinauer** [comment]
Ah that's it, thanks! Will try to setup python3 and see what happens.

**Comment by jasongrout** [comment]
> Running `jupyter lab --LabApp.base_url=/s/test --NotebookApp.base_url=/s/test` on the jlab 1.1.4, 1.0.2, and 0.35.4 all seem to give an infinite loop in requesting some content (the server log just keeps scrolling with something like:

This seems to have resolved itself. Perhaps it was a problem with the state restoration and particular browser local storage.

**Comment by kfeinauer** [comment]
Okay, thanks for all of your help! It looks like I cannot reproduce on the latest version, so I will close this ticket.

**Comment by jasongrout** [comment]
Great, thanks for checking. Enjoy 1.1.4!
