### ISSUE TITLE
latex rendering not working

### ISSUE THREAD

**Issue by IgorDouven** [jupyterlab/jupyterlab#7056]
LaTeX rendering is not working in Markdown cells. I'd be grateful for any suggestions as to what I could try to do. I'm running version 1.0.6 under Arch.

**Comment by blink1073** [comment]
Hi @IgorDouven, can you please paste the contents of your browser console after you've tried to render a markdown cell, as well as the contents of that markdown cell?

**Comment by IgorDouven** [comment]
Thanks for your reply -- I got it working in the meantime (don't know what
went wrong earlier).

Op di 20 aug. 2019 om 20:09 schreef Steven Silvester <
notifications@github.com>:

**Comment by jasongrout** [comment]
Great!
