### ISSUE TITLE
Can't disable jupyterlab extension

### ISSUE THREAD

**Issue by daejong123** [jupyterlab/jupyterlab#7058]
I met a problem, I try to use command:
```
jupyter labextension disable @jupyterlab/completer-extension
then I use jupyter labextension list
```
![image](https://user-images.githubusercontent.com/19252403/63408069-bec3a080-c420-11e9-9bed-b5222802fe89.png)

But, the @jupyterlab/completer-extension is still enable because codeCell can still complete.
And I try to use ``` jupyter labextension disable @jupyterlab/filebrowser-extension```
And the filebrowser is still here indeed.

the previous jupyterlab version there is no problem,

current jupyterlab==1.0.6 

my jupyter env:
```
jupyter                           1.0.0
jupyter-client                    5.2.4
jupyter-console                   6.0.0
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.4.0
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyterlab                        1.0.6
jupyterlab-code-formatter         0.3.0
jupyterlab-launcher               0.13.1
jupyterlab-mfe                    0.0.1
jupyterlab-server                 1.0.0
```

**Comment by daejong123** [comment]
I seem to find the problem：
jupyterlab==1.0.5 is ok
But jupyterlab == 1.0.6 labextension can't disable extension.

**Comment by blink1073** [comment]
Hi @daejong123, does`pip install --upgrade jinja2` fix the issue?

**Comment by daejong123** [comment]
Thank you for your reply！
But jinja2 Is already up to latest in my computer, so this can't fix my problem.
```
Jinja2                            2.10.1
```

![image](https://user-images.githubusercontent.com/19252403/63421586-6e0d7100-c43b-11e9-8ea5-ee19b23a25ff.png)

I just rollback jupyterlab to v1.0.5, it's ok, and wait for next jupyterlab version release.

**Comment by blink1073** [comment]
I can confirm the behavior, but I don't understand it.

In 1.0.5, we have:

```disabledExtensions: "[&#39;@jupyterlab/filebrowser-extension&#39;, &#39;@jupyterlab/terminal-extension&#39;]"```

in 1.0.6 we have:

```disabledExtensions: Array [ "@jupyterlab/filebrowser-extension", "@jupyterlab/terminal-extension" ]```

@jasongrout, any ideas why this would cause an issue?

**Comment by blink1073** [comment]
ooh, I know.  We were expecting all of the values to be strings, this is breaking that contract.

**Comment by blink1073** [comment]
We'll have to look at this deeper today.

**Comment by blink1073** [comment]
Found it!  #7061

**Comment by blink1073** [comment]
Thanks for the report, @daejong123!
