### ISSUE TITLE
widget not working in Jupyter Lab 1.0.4 but working in 0.35.4 (MyBinder)

### ISSUE THREAD

**Issue by cornhundred** [jupyterlab/jupyterlab#7063]
## Description
My Jupyter Widget (https://github.com/ismms-himc/clustergrammer2) is not working for me locally using Jupyter Lab version 1.0.4. I followed the instructions on https://jupyterlab.readthedocs.io/en/latest/getting_started/issue.html and made a jupyter lab test conda environment and installed the requirements (from here https://github.com/ismms-himc/clustergrammer2-notebooks/blob/master/requirements.txt). I'm seeing the following Chrome console errors:

<img width="556" alt="Screen Shot 2019-08-21 at 9 08 50 AM" src="https://user-images.githubusercontent.com/8352840/63435302-afc6f900-c3f4-11e9-9238-394b7991762d.png">

However, my widget does work on MyBinder using Jupyter Lab version 0.35.4 (see https://github.com/ismms-himc/clustergrammer2-notebooks launch jupyter lab badge or follow this link https://mybinder.org/v2/gh/ismms-himc/clustergrammer2-notebooks/master?urlpath=lab) and it works on Jupyter notebook. 

## Reproduce
1. Launch Jupyter Lab version 1.0.4
2. Open `notebooks/1.0_Running_Clustergrammer2.ipynb` 
3. Run all cells
4. See error where no widget is visualized and see errors in the browser console

## Expected behavior

I expect to see the interactive widget. The widget can correctly be seen using MyBinder which is running Jupyter Lab 0.35.4 (see https://mybinder.org/v2/gh/ismms-himc/clustergrammer2-notebooks/master?urlpath=lab)

## Context

- Operating System and version: MacOs
- Browser and version: Chrome
- JupyterLab version: 1.0.4

**Comment by agoose77** [comment]
Can you report which versions of the following packages are installed? 

**pip**:
- ipywidgets
**jupyterlab**
-jupyterlab-manager

**Comment by cornhundred** [comment]
Thanks @agoose77 

ipywidgets version is 7.5.1

How do I check the version of jupyterlab-manager?

**Comment by agoose77** [comment]
Can you post the output of `jupyter labextension list`

**Comment by cornhundred** [comment]
Here it is version v
<img width="599" alt="Screen Shot 2019-08-21 at 1 06 58 PM" src="https://user-images.githubusercontent.com/8352840/63452577-a51c5c00-c414-11e9-9a7d-cf5a2125690c.png">
1.0.2

**Comment by agoose77** [comment]
Hmm, I took another look at the traceback and the error concerning `IJupyterWidgetRegistry` is not related to the issue I was expecting. Maybe @jasongrout could offer an insight (though everyone's quite busy right now so I wouldn't expect anything immediate!)

I don't know whether it's a priority issue, i.e. whether your plugin is activating before the jupyter-widgets extension, so perhaps that's something to look into.

**Comment by fcollonval** [comment]
@cornhundred there were a bug corrected in JupyterLab 1.0.9. Could you try updating to that version and rebuild the extensions `jupyter lab build`?
I had the problem with `pythreejs` and validated that updating corrected the bug.

**Comment by jasongrout** [comment]
Update the widget, changing this line:
https://github.com/ismms-himc/clustergrammer2/blob/962ce01b4c5f3ee3ea0ce2a1650a1cb989e236f4/package.json#L48

to:

`    "@jupyter-widgets/base": "^1.1.10 || ^2",`

See https://ipywidgets.readthedocs.io/en/latest/changelog.html#updates-for-widget-maintainers

**Comment by cornhundred** [comment]
Thanks @jasongrout changing that line in the package.json (https://github.com/ismms-himc/clustergrammer2/blob/master/package.json#L48) worked. Now the widget works locally on Jupyter Lab version 1.0.4 (@fcollonval I didn't try updating to yet 1.0.9, but it was not the issue).
