### ISSUE TITLE
Issue with installing ipywidgets

### ISSUE THREAD

**Issue by csurett** [jupyterlab/jupyterlab#7065]
## Description
When installing `@jupyter-widgets/jupyterlab-manager` extension it fails with the following

## Reproduce

1. Install jupyterlab 1.0.8
2. Run `jupyter labextension install @jupyter-widgets/jupyterlab-manager`
3. Installation will fail with `KeyError: '@jupyterlab/notebook'`

This does not happen on 1.0.2

## Expected behavior

Extension should be installed.

## Context

- Operating System and version: Fedora 30 and RHEL 7
- Browser and version: Not applicable
- JupyterLab version: 1.0.8

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/suretc1/anaconda3/envs/data/bin
	/home/suretc1/anaconda3/condabin
	/home/suretc1/.local/bin
	/home/suretc1/bin
	/usr/lib64/qt-3.3/bin
	/usr/share/Modules/bin
	/usr/local/bin
	/usr/bin
	/usr/local/sbin
	/usr/sbin

sys.path:
	/home/suretc1/anaconda3/envs/data/bin
	/home/suretc1/anaconda3/envs/data/lib/python37.zip
	/home/suretc1/anaconda3/envs/data/lib/python3.7
	/home/suretc1/anaconda3/envs/data/lib/python3.7/lib-dynload
	/home/suretc1/anaconda3/envs/data/lib/python3.7/site-packages

sys.executable:
	/home/suretc1/anaconda3/envs/data/bin/python3.7

sys.version:
	3.7.3 (default, Mar 27 2019, 22:11:17) 
	[GCC 7.3.0]

platform.platform():
	Linux-5.2.7-200.fc30.x86_64-x86_64-with-fedora-30-Thirty

which -a jupyter:
	/home/suretc1/anaconda3/envs/data/bin/jupyter
	/usr/bin/jupyter

pip list:
	Package            Version  
	------------------ ---------
	asn1crypto         0.24.0   
	attrs              19.1.0   
	backcall           0.1.0    
	beautifulsoup4     4.7.1    
	bleach             3.1.0    
	certifi            2019.6.16
	cffi               1.12.3   
	chardet            3.0.4    
	cryptography       2.7      
	decorator          4.4.0    
	defusedxml         0.6.0    
	entrypoints        0.3      
	html5lib           1.0.1    
	idna               2.8      
	ipykernel          5.1.1    
	ipython            7.7.0    
	ipython-genutils   0.2.0    
	ipywidgets         7.5.0    
	jedi               0.13.3   
	Jinja2             2.10.1   
	json5              0.8.5    
	jsonschema         3.0.1    
	jupyter            1.0.0    
	jupyter-client     5.3.1    
	jupyter-console    6.0.0    
	jupyter-core       4.5.0    
	jupyterlab         1.0.8    
	jupyterlab-server  1.0.6    
	lxml               4.3.4    
	MarkupSafe         1.1.1    
	mistune            0.8.4    
	mkl-fft            1.0.12   
	mkl-random         1.0.2    
	mkl-service        2.0.2    
	nbconvert          5.5.0    
	nbformat           4.4.0    
	notebook           6.0.0    
	numpy              1.16.4   
	pandas             0.25.0   
	pandocfilters      1.4.2    
	parso              0.5.0    
	pexpect            4.7.0    
	pickleshare        0.7.5    
	pip                19.1.1   
	prometheus-client  0.7.1    
	prompt-toolkit     2.0.9    
	ptyprocess         0.6.0    
	pycparser          2.19     
	Pygments           2.4.2    
	pyOpenSSL          19.0.0   
	PyPDF2             1.26.0   
	pyrsistent         0.14.11  
	PySocks            1.7.0    
	python-dateutil    2.8.0    
	pytz               2019.1   
	pyzmq              18.0.0   
	qtconsole          4.5.2    
	requests           2.22.0   
	scipy              1.3.0    
	Send2Trash         1.5.0    
	setuptools         41.0.1   
	six                1.12.0   
	soupsieve          1.9.2    
	terminado          0.8.2    
	testpath           0.4.2    
	tornado            6.0.3    
	traitlets          4.3.2    
	urllib3            1.24.2   
	wcwidth            0.1.7    
	webencodings       0.5.1    
	wheel              0.33.4   
	widgetsnbextension 3.5.0

conda list:
	# packages in environment at /home/suretc1/anaconda3/envs/data:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                        main  
	asn1crypto                0.24.0                   py37_0  
	attrs                     19.1.0                   py37_1  
	backcall                  0.1.0                    py37_0  
	beautifulsoup4            4.7.1                    py37_1  
	blas                      1.0                         mkl  
	bleach                    3.1.0                    py37_0  
	ca-certificates           2019.5.15                     0  
	certifi                   2019.6.16                py37_1  
	cffi                      1.12.3           py37h2e261b9_0  
	chardet                   3.0.4                 py37_1003  
	cryptography              2.7              py37h1ba5d50_0  
	dbus                      1.13.6               h746ee38_0  
	decorator                 4.4.0                    py37_1  
	defusedxml                0.6.0                      py_0  
	entrypoints               0.3                      py37_0  
	expat                     2.2.6                he6710b0_0  
	fontconfig                2.13.0               h9420a91_0  
	freetype                  2.9.1                h8a8886c_1  
	glib                      2.56.2               hd408876_0  
	gmp                       6.1.2                h6c8ec71_1  
	gst-plugins-base          1.14.0               hbbd80ab_1  
	gstreamer                 1.14.0               hb453b48_1  
	html5lib                  1.0.1                    py37_0  
	icu                       58.2                 h9c2bf20_1  
	idna                      2.8                      py37_0  
	intel-openmp              2019.4                      243  
	ipykernel                 5.1.1            py37h39e3cac_0  
	ipython                   7.7.0            py37h39e3cac_0  
	ipython_genutils          0.2.0                    py37_0  
	ipywidgets                7.5.0                      py_0  
	jedi                      0.13.3                   py37_0  
	jinja2                    2.10.1                   py37_0  
	jpeg                      9b                   h024ee3a_2  
	json5                     0.8.5                    pypi_0    pypi
	jsonschema                3.0.1                    py37_0  
	jupyter                   1.0.0                    py37_7  
	jupyter_client            5.3.1                      py_0  
	jupyter_console           6.0.0                    py37_0  
	jupyter_core              4.5.0                      py_0  
	jupyterlab                1.0.8                    pypi_0    pypi
	jupyterlab-server         1.0.6                    pypi_0    pypi
	libedit                   3.1.20181209         hc058e9b_0  
	libffi                    3.2.1                hd88cf55_4  
	libgcc-ng                 9.1.0                hdf63c60_0  
	libgfortran-ng            7.3.0                hdf63c60_0  
	libpng                    1.6.37               hbc83047_0  
	libsodium                 1.0.16               h1bed415_0  
	libstdcxx-ng              9.1.0                hdf63c60_0  
	libuuid                   1.0.3                h1bed415_2  
	libxcb                    1.13                 h1bed415_1  
	libxml2                   2.9.9                hea5a465_1  
	libxslt                   1.1.33               h7d1a2b0_0  
	lxml                      4.3.4            py37hefd8a0e_0  
	markupsafe                1.1.1            py37h7b6447c_0  
	mistune                   0.8.4            py37h7b6447c_0  
	mkl                       2019.4                      243  
	mkl-service               2.0.2            py37h7b6447c_0  
	mkl_fft                   1.0.12           py37ha843d7b_0  
	mkl_random                1.0.2            py37hd81dba3_0  
	nbconvert                 5.5.0                      py_0  
	nbformat                  4.4.0                    py37_0  
	ncurses                   6.1                  he6710b0_1  
	notebook                  6.0.0                    py37_0  
	numpy                     1.16.4           py37h7e9f1db_0  
	numpy-base                1.16.4           py37hde5b4d6_0  
	openssl                   1.1.1c               h7b6447c_1  
	pandas                    0.25.0           py37he6710b0_0  
	pandoc                    2.2.3.2                       0  
	pandocfilters             1.4.2                    py37_1  
	parso                     0.5.0                      py_0  
	pcre                      8.43                 he6710b0_0  
	pexpect                   4.7.0                    py37_0  
	pickleshare               0.7.5                    py37_0  
	pip                       19.1.1                   py37_0  
	prometheus_client         0.7.1                      py_0  
	prompt_toolkit            2.0.9                    py37_0  
	ptyprocess                0.6.0                    py37_0  
	pycparser                 2.19                     py37_0  
	pygments                  2.4.2                      py_0  
	pyopenssl                 19.0.0                   py37_0  
	pypdf2                    1.26.0                   pypi_0    pypi
	pyqt                      5.9.2            py37h05f1152_2  
	pyrsistent                0.14.11          py37h7b6447c_0  
	pysocks                   1.7.0                    py37_0  
	python                    3.7.3                h0371630_0  
	python-dateutil           2.8.0                    py37_0  
	pytz                      2019.1                     py_0  
	pyzmq                     18.0.0           py37he6710b0_0  
	qt                        5.9.7                h5867ecd_1  
	qtconsole                 4.5.2                      py_0  
	readline                  7.0                  h7b6447c_5  
	requests                  2.22.0                   py37_0  
	scipy                     1.3.0            py37h7c811a0_0  
	send2trash                1.5.0                    py37_0  
	setuptools                41.0.1                   py37_0  
	sip                       4.19.8           py37hf484d3e_0  
	six                       1.12.0                   py37_0  
	soupsieve                 1.9.2                    py37_0  
	sqlite                    3.29.0               h7b6447c_0  
	terminado                 0.8.2                    py37_0  
	testpath                  0.4.2                    py37_0  
	tk                        8.6.8                hbc83047_0  
	tornado                   6.0.3            py37h7b6447c_0  
	traitlets                 4.3.2                    py37_0  
	urllib3                   1.24.2                   py37_0  
	wcwidth                   0.1.7                    py37_0  
	webencodings              0.5.1                    py37_1  
	wheel                     0.33.4                   py37_0  
	widgetsnbextension        3.5.0                    py37_0  
	xz                        5.2.4                h14c3975_4  
	zeromq                    4.3.1                he6710b0_3  
	zlib                      1.2.11               h7b6447c_3

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
(data) [suretc1@fedora-suretc1 ~]$ jupyter labextension install @jupyter-widgets/jupyterlab-manager --debug
Searching ['/home/suretc1', '/home/suretc1/.jupyter', '/home/suretc1/anaconda3/envs/data/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /home/suretc1/anaconda3/envs/data/etc/jupyter
Looking for jupyter_config in /home/suretc1/.jupyter
Looking for jupyter_config in /home/suretc1
Node v8.12.0

> /usr/bin/npm pack @jupyter-widgets/jupyterlab-manager
\npm notice 
npm notice 📦  @jupyter-widgets/jupyterlab-manager@1.0.2
npm notice === Tarball Contents === 
npm notice 2.3kB  package.json        
npm notice 1.5kB  LICENSE             
npm notice 1.9kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 380B   lib/index.js        
npm notice 5.3kB  lib/manager.d.ts    
npm notice 12.0kB lib/manager.js      
npm notice 1.9kB  lib/output.d.ts     
npm notice 5.2kB  lib/output.js       
npm notice 830B   lib/plugin.d.ts     
npm notice 6.7kB  lib/plugin.js       
npm notice 956B   lib/renderer.d.ts   
npm notice 3.3kB  lib/renderer.js     
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js  
npm notice 375B   schema/plugin.json  
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager         
npm notice version:       1.0.2                                       
npm notice filename:      jupyter-widgets-jupyterlab-manager-1.0.2.tgz
npm notice package size:  11.3 kB                                     
npm notice unpacked size: 44.0 kB                                     
npm notice shasum:        8913784a181f7fb05d79943080549893ccb45ca1    
npm notice integrity:     sha512-7c5jADfFFc16g[...]728vBtwbByyIw==    
npm notice total files:   16                                          
npm notice 
jupyter-widgets-jupyterlab-manager-1.0.2.tgz

Traceback (most recent call last):

  File "/home/suretc1/anaconda3/envs/data/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/suretc1/anaconda3/envs/data/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 82, in start
    ans = self.run_task()

  File "/home/suretc1/anaconda3/envs/data/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "/home/suretc1/anaconda3/envs/data/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "/home/suretc1/anaconda3/envs/data/lib/python3.7/site-packages/jupyterlab/commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "/home/suretc1/anaconda3/envs/data/lib/python3.7/site-packages/jupyterlab/commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/home/suretc1/anaconda3/envs/data/lib/python3.7/site-packages/jupyterlab/commands.py", line 1385, in _install_extension
    errors = _validate_compatibility(extension, deps, core_data)

  File "/home/suretc1/anaconda3/envs/data/lib/python3.7/site-packages/jupyterlab/commands.py", line 1749, in _validate_compatibility
    overlap = _test_overlap(core_deps[key], value)

KeyError: '@jupyterlab/notebook'

An error occured.
KeyError: '@jupyterlab/notebook'
See the log file for details:  /tmp/jupyterlab-debug-frb1a7s_.log
Exiting application: jupyter

</pre>
</details>

**Comment by agoose77** [comment]
(+1) I also reproduce this, but it doesn't happen on 1.0.6

**Comment by blink1073** [comment]
Confirmed locally with 1.0.8:

```
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build --debug
Searching ['/home/silvester/workspace', '/home/silvester/.jupyter', '/home/silvester/miniconda/envs/lab-test/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /home/silvester/miniconda/envs/lab-test/etc/jupyter
Looking for jupyter_config in /home/silvester/.jupyter
Looking for jupyter_config in /home/silvester/workspace
Node v12.8.1

> /home/silvester/miniconda/envs/lab-test/bin/npm pack @jupyter-widgets/jupyterlab-manager
|npm notice 
npm notice 📦  @jupyter-widgets/jupyterlab-manager@1.0.2
npm notice === Tarball Contents === 
npm notice 2.3kB  package.json        
npm notice 1.5kB  LICENSE             
npm notice 1.9kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 380B   lib/index.js        
npm notice 5.3kB  lib/manager.d.ts    
npm notice 12.0kB lib/manager.js      
npm notice 1.9kB  lib/output.d.ts     
npm notice 5.2kB  lib/output.js       
npm notice 830B   lib/plugin.d.ts     
npm notice 6.7kB  lib/plugin.js       
npm notice 956B   lib/renderer.d.ts   
npm notice 3.3kB  lib/renderer.js     
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js  
npm notice 375B   schema/plugin.json  
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager         
npm notice version:       1.0.2                                       
npm notice filename:      jupyter-widgets-jupyterlab-manager-1.0.2.tgz
npm notice package size:  11.3 kB                                     
npm notice unpacked size: 44.0 kB                                     
npm notice shasum:        8913784a181f7fb05d79943080549893ccb45ca1    
npm notice integrity:     sha512-7c5jADfFFc16g[...]728vBtwbByyIw==    
npm notice total files:   16                                          
npm notice 
jupyter-widgets-jupyterlab-manager-1.0.2.tgz

Traceback (most recent call last):

  File "/home/silvester/miniconda/envs/lab-test/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/silvester/miniconda/envs/lab-test/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 82, in start
    ans = self.run_task()

  File "/home/silvester/miniconda/envs/lab-test/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "/home/silvester/miniconda/envs/lab-test/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "/home/silvester/miniconda/envs/lab-test/lib/python3.7/site-packages/jupyterlab/commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "/home/silvester/miniconda/envs/lab-test/lib/python3.7/site-packages/jupyterlab/commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/home/silvester/miniconda/envs/lab-test/lib/python3.7/site-packages/jupyterlab/commands.py", line 1385, in _install_extension
    errors = _validate_compatibility(extension, deps, core_data)

  File "/home/silvester/miniconda/envs/lab-test/lib/python3.7/site-packages/jupyterlab/commands.py", line 1749, in _validate_compatibility
    overlap = _test_overlap(core_deps[key], value)

KeyError: '@jupyterlab/notebook'

An error occured.
KeyError: '@jupyterlab/notebook'
See the log file for details:  /tmp/jupyterlab-debug-he_w71ai.log
Exiting application: jupyter
```

**Comment by blink1073** [comment]
cf #7066.  Cutting a new release now

**Comment by blink1073** [comment]
Fixed in current release, thanks again @csurett!
