### ISSUE TITLE
Error 500 while deleting files from Jupyterlab on ui

### ISSUE THREAD

**Issue by vpanneer** [jupyterlab/jupyterlab#7075]
## Description

We encounter an error 500,  OSError: [Errno 18] Invalid cross-device link: while deleteing a file in jupyterlab UI.

## Reproduce

1/create a text file in jupyterlab. save it.
2/try to delete it.
3/ you receive an error 500.

## Context

- Operating System and version: 
Windows 10
- Browser and version:
Microsoft Edge 41.16299.1004.0, Firefox
- JupyterLab version:
Version 0.35.4
<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
error 500 indicates a server error. Please also paste in your command line output, which should give the cause of the error.

**Comment by vpanneer** [comment]
Please, find attached the screenshot of the error and the log which goes with it. 
Thanks for your reply,

[issue_#7075_log.docx](https://github.com/jupyterlab/jupyterlab/files/3530812/issue_.7075_log.docx)

**Comment by jasongrout** [comment]
Sorry, can you just paste the text here?

**Comment by vpanneer** [comment]
[D 14:46:20.633 LabApp] Sending /home/l370051/application_layer/datalab/central/TEST_PROJECT/test_for_deletion.txt to trash
[E 14:46:20.638 LabApp] Uncaught exception DELETE /jupyterlab/api/contents/application_layer/datalab/central/TEST_PROJECT/test_for_deletion.txt?1566391580610 (172.17.0.4)
    HTTPServerRequest(protocol='http', host='datalab01.sparrow-pfc.rb.echonet', method='DELETE', uri='/jupyterlab/api/contents/application_layer/datalab/central/TEST_PROJECT/test_for_deletion.txt?1566391
580610', version='HTTP/1.1', remote_ip='172.17.0.4')
    OSError: [Errno 18] Invalid cross-device link: b'/home/l370051/application_layer/datalab/central/TEST_PROJECT/test_for_deletion.txt' -> b'/home/l370051/.local/share/Trash/files/test_for_deletion.txt'

[E 14:46:20.642 LabApp] 500 DELETE /jupyterlab/api/contents/application_layer/datalab/central/TEST_PROJECT/test_for_deletion.txt?1566391580610 (172.17.0.4) 9.41ms referer=https://datalab01.sparro
w-pfc.rb.echonet/jupyterlab/lab?

**Comment by vpanneer** [comment]
Sending /TEST_PROJECT/test_for_deletion.txt to trash
Uncaught exception DELETE TEST_PROJECT/test_for_deletion.txt?
 HTTPServerRequest(protocol='http',method='DELETE', uri='/TEST_PROJECT/test_for_deletion.txt?
 OSError: [Errno 18] Invalid cross-device link: b'/TEST_PROJECT/test_for_deletion.txt' -> b'/home/l370051/.local/share/Trash/files/test_for_deletion.txt'
500 DELETE /TEST_PROJECT/test_for_deletion.txt?

**Comment by vpanneer** [comment]
Yes, I confirm that it works with a classic notebook and the problem is with notebooks opened on docker containers. 
Meanwhile, succeded to overcome the problem by configuring  the parameter c.FileContentsManager.delete_to_trash  of the jupyter_notebook_config.py file to False as explained in the issue https://github.com/jupyter/notebook/issues/3130.
Thanks all!
