### ISSUE TITLE
%autosave doesn't work in jupyter-lab (but it does in jupyter notebook)

### ISSUE THREAD

**Issue by garrettmsft7** [jupyterlab/jupyterlab#7083]
%autosave magic does not work in jupyter-lab but it does with jupyter notebook. Is this feature not supported?

Here's the error msg: **Javascript Error: IPython is not defined**

**Comment by jasongrout** [comment]
It looks like you are right, it is not supported right now, since it apparently relies on assuming it is running in the classic notebook.

**Comment by jasongrout** [comment]
Closing since the author did not follow up. Please comment here if you'd like to continue the discussion.
