### ISSUE TITLE
Feature request: dynamically showing the last N lines of results on large output

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#7086]
It is inconvenient to scroll the notebook to navigate when a cell has a large number of lines of output. Of course users can manually hide that output. However, I think a potentially better way is to automatically showing the last N lines of output dynamically on large output. When users want, they can still expand the output cell to see the full result. And it is best that if N is configurable.

**Comment by wallneradam** [comment]
Hi, I've created an extension for this: https://github.com/wallneradam/jupyterlab-output-auto-scroll

You can right click on the output and select "Enable scrolling for output". Then enable the autoscroll with the toolbar button. You can also change the size of the scrollable output with my other extension: custom_css. You can find an example in the README exactly for this.

**Comment by mlucool** [comment]
This was actually a Jupyter notebook feature that was not ported (note this showed the first N lines, not the last). I think it would make sense to build back in.

Example:
Notebook
![image](https://user-images.githubusercontent.com/1813603/72996899-793d4200-3dc9-11ea-8fac-cef5a3e64d9e.png)

Lab:
![image](https://user-images.githubusercontent.com/1813603/72996971-9b36c480-3dc9-11ea-9098-176ac748cbe1.png)

**Comment by vidartf** [comment]
@mlucool As @wallneradam pointed out, right-clicking on the left of the cell and selection "Enable scrolling for outputs" will show the partially collapsed view (so, the feature from classic notebook was ported). Showing the N last lines is the part that is requested (and which there exists an extension for).
