### ISSUE TITLE
Custom Websocket url differ in JupyterLab and Jupyter Notebook Server

### ISSUE THREAD

**Issue by sntgluca** [jupyterlab/jupyterlab#7087]
Dear all,

While searching for a workaround on another issue, I encountered a mismatch in the behaviour of JupyterLab and Jupyter Notebook server.
I post it here, as I think this is the most sensible place to discuss this, although it has partially to do with JupyterHub as well. 

The mismatch is in the setup of the custom `websocket_url` parameter. It can be replicated with this minimal JupyterHub configuration:

```
c.JupyterHub.base_url = <BASE_URL>
c.Spawner.websocket_url = "ws://<ADDRESS>/<BASE_URL>"
```
where `BASE_URL` and`<ADDRESS>` are the custom url and location of my choice.
The final websocket address should have the form `ws://<ADDRESS>/<BASE_URL>/user/{username}`

The final websocket url built by the backend Jupyter session has the form

* `ws://<ADDRESS>/<BASE_URL>` in JupyterLab
* `ws://<ADDRESS>/<BASE_URL>/user/{username}` in Jupyter Notebook Server

This inconsistency is problematic, because I cannot customise the websocket_url parameter in a way that works for both JupyterLab and Jupyter Notebook server.
How would you address this problem?

Thanks
Gianluca

**Comment by sntgluca** [comment]
A quick answer about this, in case someone else came across the same problem.

Using `notebook` version 6.0.0, the web url is defined, for the traditional notebook server, in the file `notebook/static/notebook/js/main.min.js`

Adding the following lines in row 50727

```python
+        this.ws_url = this.ws_url.replace(/^((?:\w+:)?\/\/(.+:\d+))(.*)/, '$1');
+        that.ws_url = that.ws_url.replace(/^((?:\w+:)?\/\/(.+:\d+))(.*)/, '$1');
```
removes the duplication from the notebook server websocket url, hence making both JupyterLab and Jupyter Notebook server behaving in the same way.

**Comment by jasongrout** [comment]
Which behavior do you think is more correct?

**Comment by sntgluca** [comment]
Hi @jasongrout !
I don't think there's an obvious answer to your question.

I found that modifying the `notebook` package's code was easier, and I considering JupyterLab is the default. Do you consider the patch above good enough?

The only argument for keeping the `notebook` package behaviour is that it seems simpler (as in, it doesn't _strip_ arguments from the url). But I don't consider this a strong point.
