### ISSUE TITLE
Add visual indicator for command/edit mode

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#709]
In the classic notebook we have an indicator in the notebook toolbar that shows when a cell is in edit mode. We need something in JupyterLab that shows this state, but it doesn't have to be in the notebook toolbar.

Some ideas:
- Maybe in the notification area?
- Maybe spatially colocated with the cell being edited?

**Comment by jasongrout** [comment]
Doesn't the border around the cell show this? Is it a color accessibility issue?

**Comment by spoorthyv** [comment]
I think the colors meaning are still unclear to a regular user. A lot of people didnt pick up on that visual cue and relate that to command and edit modes.

**Comment by faricacarroll** [comment]
How about changing the cursor for when it is on edit vs. command mode?

**Comment by jasongrout** [comment]
> Maybe in the notification area?

This would be a great thing to put in a status bar at the bottom, similar to a word processor puts mode information like Insert/Overwrite status. cf. https://github.com/jupyter/jupyterlab/issues/512

**Comment by ellisonbg** [comment]
Jason, yes, I really like the idea of having a status bar. Here is the one for VSCode:

<img width="958" alt="screen shot 2016-09-06 at 12 29 31 pm" src="https://cloud.githubusercontent.com/assets/27600/18287857/a2834844-742d-11e6-8f3e-b25493962acf.png">

Would you do that on a per tab basis or JupyterLab wide?

**Comment by jasongrout** [comment]
Probably Lab-wide, since I think it would be a bit heavy doing it per-tab. That would also be consistent with VSCode, Sublime, and other most other Windows MDI apps where the status bar is a global bar at the bottom of the app, which updates depending on which internal window was selected.
