### ISSUE TITLE
Can't install extensions in windows

### ISSUE THREAD

**Issue by tiagopereira** [jupyterlab/jupyterlab#7092]
## Description

I have a problem installing extensions in Windows. The same steps/versions to install jupyter lab with anaconda work fine on Linux or macOS, but labextension install fails. Jupyter lab itself runs fine.

## Reproduce

```bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

This seems to fail with any extension. The error log is:
<pre>
Node v12.8.1

> C:\Users\john\Anaconda3\envs\test\npm.CMD pack @jupyter-widgets/jupyterlab-manager
npm notice 
npm notice package: @jupyter-widgets/jupyterlab-manager@1.0.2
npm notice === Tarball Contents === 
npm notice 2.3kB  package.json        
npm notice 1.5kB  LICENSE             
npm notice 1.9kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 380B   lib/index.js        
npm notice 5.3kB  lib/manager.d.ts    
npm notice 12.0kB lib/manager.js      
npm notice 1.9kB  lib/output.d.ts     
npm notice 5.2kB  lib/output.js       
npm notice 830B   lib/plugin.d.ts     
npm notice 6.7kB  lib/plugin.js       
npm notice 956B   lib/renderer.d.ts   
npm notice 3.3kB  lib/renderer.js     
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js  
npm notice 375B   schema/plugin.json  
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager         
npm notice version:       1.0.2                                       
npm notice filename:      jupyter-widgets-jupyterlab-manager-1.0.2.tgz
npm notice package size:  11.3 kB                                     
npm notice unpacked size: 44.0 kB                                     
npm notice shasum:        8913784a181f7fb05d79943080549893ccb45ca1    
npm notice integrity:     sha512-7c5jADfFFc16g[...]728vBtwbByyIw==    
npm notice total files:   16                                          
npm notice 
jupyter-widgets-jupyterlab-manager-1.0.2.tgz

Traceback (most recent call last):

  File "C:\Users\john\Anaconda3\envs\ast4310\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\john\Anaconda3\envs\ast4310\lib\site-packages\jupyterlab\labextensions.py", line 82, in start
    ans = self.run_task()

  File "C:\Users\john\Anaconda3\envs\test\lib\site-packages\jupyterlab\labextensions.py", line 103, in run_task
    for arg in self.extra_args

  File "C:\Users\john\Anaconda3\envs\test\lib\site-packages\jupyterlab\labextensions.py", line 103, in <listcomp>
    for arg in self.extra_args

  File "C:\Users\john\Anaconda3\envs\test\lib\site-packages\jupyterlab\commands.py", line 316, in install_extension
    return handler.install_extension(extension)

  File "C:\Users\john\Anaconda3\envs\test\lib\site-packages\jupyterlab\commands.py", line 517, in install_extension
    info = self._install_extension(extension, tempdir)

  File "C:\Users\john\Anaconda3\envs\test\lib\site-packages\jupyterlab\commands.py", line 1373, in _install_extension
    info = self._extract_package(extension, tempdir)

  File "C:\Users\john\Anaconda3\envs\test\lib\site-packages\jupyterlab\commands.py", line 1446, in _extract_package
    path = glob.glob(pjoin(tempdir, '*.tgz'))[0]

IndexError: list index out of range

Exiting application: jupyter
</pre>

It doesn't appear to be finding the `tgz` file, hence the `IndexError`.

## Expected behavior

Expected to install the lab extension.

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome
- JupyterLab version: 1.0.9, py37_0, conda-forge

**Comment by vidartf** [comment]
I ran a test here (on Windows 10, clean conda env with 1.0.9), with no issues.

Some things to look into to troubleshoot:
- Is there any anti-virus or other security constraints (e.g. permission errors) that might interfere with the file?
- Are you able to reproduce on other Windows machines (if you have access to one)?

**Comment by vidartf** [comment]
- Are you able to debug the build process (e.g. use `breakpoint()`/`import pdb; pdb.set_trace()` right before the line that throws the exception? Then you can get the directory name, and can inspect its contents.

**Comment by tiagopereira** [comment]
I will try this again and report...

**Comment by jasongrout** [comment]
@tiagopereira - any follow-up on this?

**Comment by tiagopereira** [comment]
I'm sorry, I won't be able to report back on this since the Windows computer used is no longer available...

**Comment by jasongrout** [comment]
Okay, thanks for following up back here.
