### ISSUE TITLE
Jupyter lab build fails in fresh conda environment

### ISSUE THREAD

**Issue by hoangthienan95** [jupyterlab/jupyterlab#7108]
## Description
I was having trouble updating from Jupyterlab 0.35.3 to 1.0.9 so decided to just create a fresh environment to test it out
Jupyter build fails, UI missing icons.
Plus, cannot open any notebook files, but open other file types fine

![image](https://user-images.githubusercontent.com/25307953/63862804-2e82df80-c97b-11e9-9c68-831b2c35fa52.png)

When trying to install extensions:
![image](https://user-images.githubusercontent.com/25307953/63863314-03e55680-c97c-11e9-9795-a5544ca7c94e.png)

### Make environment:
`conda` version: 4.6.14
`conda create --name jupyterlab python=3.7`
`conda activate jupyterlab`
`conda install -c conda-forge jupyterlab`
`jupyter lab build`

<details><summary>Jupyterlab build Output</summary>

<pre>
(jupyterlab) anhoang@tak ~$ jupyter lab build
[LabBuildApp] JupyterLab 1.0.9
[LabBuildApp] Building in /lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-4ngyboqu.log
</pre>

<pre>
(jupyterlab) anhoang@tak ~$ cat /tmp/jupyterlab-debug-4ngyboqu.log
[LabBuildApp] Building in /lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/share/jupyter/lab
[LabBuildApp] Node v10.13.0

[LabBuildApp] Building jupyterlab assets
[LabBuildApp] > node /lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "Unknown system error -122: Unknown system error -122, mkdir '/home/anhoang/.cache/yarn/v4/npm-codemirror-5.47.0-c13a521ae5660d3acc655af252f4955065293789/node_modules/codemirror'".
info If you think this is a bug, please open a bug report with the information provided in "/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/share/jupyter/lab/staging/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/labapp.py", line 80, in start
    command=command, logger=self.log)

[LabBuildApp]   File "/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/commands.py", line 373, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab/commands.py", line 557, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab

</pre>

</details>

Looked at [this issue](https://github.com/explosion/jupyterlab-prodigy/issues/5), #6878, #6969, #6920 

<details><summary>yarn error log</summary>
</details>

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version: `conda list jupyter`
```
# Name                    Version                   Build  Channel
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                1.0.9                    py37_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
```

<details><summary>Troubleshoot Output</summary>
<pre>
(jupyterlab) anhoang@tak ~$ jupyter troubleshoot
$PATH:
	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/bin
	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/bin
	/lab/corradin_data/FOR_AN/anaconda3/bin
	/lab/corradin_data/FOR_AN/anaconda3/condabin
	/nfs/lsf8/8.0/linux2.6-glibc2.3-x86_64/etc
	/nfs/lsf8/8.0/linux2.6-glibc2.3-x86_64/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/usr/local/genome/bin

sys.path:
	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/bin
	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python37.zip
	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python3.7
	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python3.7/lib-dynload
	/home/anhoang/.local/lib/python3.7/site-packages
	/home/anhoang/.local/lib/python3.7/site-packages/hyperlearn-0.0.1-py3.7.egg
	/lab/corradin_data/FOR_AN/anaconda3/envs/bgen/lib/python3.7/site-packages/Cython-0.29.7-py3.7-linux-x86_64.egg
	/lab/corradin_data/FOR_AN/anaconda3/envs/bgen/lib/python3.7/site-packages/torch-1.1.0-py3.7-linux-x86_64.egg
	/lab/corradin_data/FOR_AN/anaconda3/envs/bgen/lib/python3.7/site-packages/torchvision-0.3.0-py3.7-linux-x86_64.egg
	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python3.7/site-packages

sys.executable:
	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/bin/python3.7

sys.version:
	3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
	[GCC 7.3.0]

platform.platform():
	Linux-4.15.0-58-generic-x86_64-with-debian-buster-sid

which -a jupyter:
	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/bin/jupyter
	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/bin/jupyter
	/lab/corradin_data/FOR_AN/anaconda3/bin/jupyter

pip list:
	Package           Version  
	----------------- ---------
	attrs             19.1.0   
	backcall          0.1.0    
	bleach            3.1.0    
	certifi           2019.6.16
	Cython            0.29.7   
	decorator         4.4.0    
	defusedxml        0.5.0    
	entrypoints       0.3      
	hyperlearn        0.0.1    
	ipykernel         5.1.2    
	ipython           7.7.0    
	ipython-genutils  0.2.0    
	jedi              0.15.1   
	Jinja2            2.10.1   
	json5             0.8.5    
	jsonschema        3.0.2    
	jupyter-client    5.3.1    
	jupyter-core      4.4.0    
	jupyterlab        1.0.9    
	jupyterlab-server 1.0.6    
	MarkupSafe        1.1.1    
	mistune           0.8.4    
	nbconvert         5.6.0    
	nbformat          4.4.0    
	notebook          6.0.1    
	pandocfilters     1.4.2    
	parso             0.5.1    
	pexpect           4.7.0    
	pickleshare       0.7.5    
	pip               19.2.3   
	prometheus-client 0.7.1    
	prompt-toolkit    2.0.9    
	ptyprocess        0.6.0    
	Pygments          2.4.2    
	pyrsistent        0.15.4   
	python-dateutil   2.8.0    
	pyzmq             18.0.2   
	Send2Trash        1.5.0    
	setuptools        41.2.0   
	six               1.12.0   
	terminado         0.8.2    
	testpath          0.4.2    
	torch             1.1.0    
	torchvision       0.3.0    
	tornado           6.0.3    
	traitlets         4.3.2    
	wcwidth           0.1.7    
	webencodings      0.5.1    
	wheel             0.33.6

conda list:
	# packages in environment at /lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                        main  
	attrs                     19.1.0                     py_0    conda-forge
	backcall                  0.1.0                      py_0    conda-forge
	bleach                    3.1.0                      py_0    conda-forge
	bzip2                     1.0.8                h516909a_0    conda-forge
	ca-certificates           2019.6.16            hecc5488_0    conda-forge
	certifi                   2019.6.16                py37_1    conda-forge
	decorator                 4.4.0                      py_0    conda-forge
	defusedxml                0.5.0                      py_1    conda-forge
	entrypoints               0.3                   py37_1000    conda-forge
	ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
	ipython                   7.7.0            py37h5ca1d4c_0    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	jedi                      0.15.1                   py37_0    conda-forge
	jinja2                    2.10.1                     py_0    conda-forge
	json5                     0.8.5                      py_0    conda-forge
	jsonschema                3.0.2                    py37_0    conda-forge
	jupyter_client            5.3.1                      py_0    conda-forge
	jupyter_core              4.4.0                      py_0    conda-forge
	jupyterlab                1.0.9                    py37_0    conda-forge
	jupyterlab_server         1.0.6                      py_0    conda-forge
	libffi                    3.2.1             he1b5a44_1006    conda-forge
	libgcc-ng                 9.1.0                hdf63c60_0  
	libsodium                 1.0.17               h516909a_0    conda-forge
	libstdcxx-ng              9.1.0                hdf63c60_0  
	markupsafe                1.1.1            py37h14c3975_0    conda-forge
	mistune                   0.8.4           py37h14c3975_1000    conda-forge
	nbconvert                 5.6.0                    py37_1    conda-forge
	nbformat                  4.4.0                      py_1    conda-forge
	ncurses                   6.1               hf484d3e_1002    conda-forge
	notebook                  6.0.1                    py37_0    conda-forge
	openssl                   1.1.1c               h516909a_0    conda-forge
	pandoc                    2.7.3                         0    conda-forge
	pandocfilters             1.4.2                      py_1    conda-forge
	parso                     0.5.1                      py_0    conda-forge
	pexpect                   4.7.0                    py37_0    conda-forge
	pickleshare               0.7.5                 py37_1000    conda-forge
	pip                       19.2.3                   py37_0    conda-forge
	prometheus_client         0.7.1                      py_0    conda-forge
	prompt_toolkit            2.0.9                      py_0    conda-forge
	ptyprocess                0.6.0                   py_1001    conda-forge
	pygments                  2.4.2                      py_0    conda-forge
	pyrsistent                0.15.4           py37h516909a_0    conda-forge
	python                    3.7.3                h33d41f4_1    conda-forge
	python-dateutil           2.8.0                      py_0    conda-forge
	pyzmq                     18.0.2           py37h1768529_2    conda-forge
	readline                  8.0                  hf8c457e_0    conda-forge
	send2trash                1.5.0                      py_0    conda-forge
	setuptools                41.2.0                   py37_0    conda-forge
	six                       1.12.0                py37_1000    conda-forge
	sqlite                    3.29.0               hcee41ef_0    conda-forge
	terminado                 0.8.2                    py37_0    conda-forge
	testpath                  0.4.2                   py_1001    conda-forge
	tk                        8.6.9             hed695b0_1002    conda-forge
	tornado                   6.0.3            py37h516909a_0    conda-forge
	traitlets                 4.3.2                 py37_1000    conda-forge
	wcwidth                   0.1.7                      py_1    conda-forge
	webencodings              0.5.1                      py_1    conda-forge
	wheel                     0.33.6                   py37_0    conda-forge
	xz                        5.2.4             h14c3975_1001    conda-forge
	zeromq                    4.3.2                he1b5a44_2    conda-forge
	zlib                      1.2.11            h516909a_1005    conda-forge
(jupyterlab) anhoang@tak ~$ 
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
(jupyterlab) anhoang@tak ~$ jupyter lab --debug --no-browser
[D 10:01:35.387 LabApp] Searching ['/home/anhoang', '/home/anhoang/.jupyter', '/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 10:01:35.387 LabApp] Looking for jupyter_config in /etc/jupyter
[D 10:01:35.387 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 10:01:35.387 LabApp] Looking for jupyter_config in /lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/etc/jupyter
[D 10:01:35.387 LabApp] Looking for jupyter_config in /home/anhoang/.jupyter
[D 10:01:35.387 LabApp] Looking for jupyter_config in /home/anhoang
[D 10:01:35.388 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 10:01:35.388 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 10:01:35.388 LabApp] Looking for jupyter_notebook_config in /lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/etc/jupyter
[D 10:01:35.389 LabApp] Loaded config file: /lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/etc/jupyter/jupyter_notebook_config.json
[D 10:01:35.389 LabApp] Looking for jupyter_notebook_config in /home/anhoang/.jupyter
[D 10:01:35.389 LabApp] Loaded config file: /home/anhoang/.jupyter/jupyter_notebook_config.py
[D 10:01:35.390 LabApp] Loaded config file: /home/anhoang/.jupyter/jupyter_notebook_config.json
[D 10:01:35.390 LabApp] Looking for jupyter_notebook_config in /home/anhoang
[D 10:01:35.395 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 10:01:35.396 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 10:01:35.396 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/etc/jupyter/jupyter_notebook_config.json
[D 10:01:35.397 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/anhoang/.jupyter/jupyter_notebook_config.json
[I 10:01:35.729 LabApp] The port 8888 is already in use, trying another port.
[I 10:01:35.729 LabApp] The port 8889 is already in use, trying another port.
[I 10:01:35.740 LabApp] JupyterLab extension loaded from /lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python3.7/site-packages/jupyterlab
[I 10:01:35.740 LabApp] JupyterLab application directory is /lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/share/jupyter/lab
[W 10:01:35.742 LabApp] Error loading server extension jupytext
    Traceback (most recent call last):
      File "/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python3.7/site-packages/notebook/notebookapp.py", line 1615, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/lab/corradin_data/FOR_AN/anaconda3/envs/jupyterlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupytext'
[I 10:01:35.743 LabApp] Serving notebooks from local directory: /home/anhoang
[I 10:01:35.743 LabApp] The Jupyter Notebook is running at:
[I 10:01:35.743 LabApp] http://localhost:8890/?token=8dd8a179d7efd49e0a964f41d358bc92bf65a8f3e4e7521f
[I 10:01:35.743 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:01:35.746 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///run/user/4638/jupyter/nbserver-2452-open.html
    Or copy and paste one of these URLs:
        http://localhost:8890/...
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by hoangthienan95** [comment]
The problem turned out to be that my home folder was full. Fixed it and was able to install Jupyter lab. However, after installing extension `celltags` and rebuild, my screen is currently like below.

![image](https://user-images.githubusercontent.com/25307953/63943574-f4c6dd00-ca3d-11e9-8a92-82314d21d759.png)

Have tried uninstalling `celltags`, `jupyter lab clean` and `jupyter lab build` but still the same. Any idea why this might happen? I think it was not able to read some static files, but don't know what to do. This error pops up intermittenly:

```
[E 08:53:51.322 LabApp] Could not open static file ''"
```

**Comment by jasongrout** [comment]
Can you follow the issue diagnosing guidelines at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to try to narrow down where the problem might be?

**Comment by hoangthienan95** [comment]
I updated Jupyterlab and the problem was solved!

**Comment by mshlis** [comment]
getting the same problem on Mac with lab 1.0.2, any other solutions other than updating?

**Comment by leonardoaraujosantos** [comment]
Guys, this issue, is not solved yet....

**Comment by Losoly** [comment]
I have the same issue since I updated my conda enviroment. I already removed all my extensions. After downgrading jupyter lab it looks okay. After updateing it again everything is still fine. But when I add an extension and rebuild jupyter lab I get the problem again. :(
