### ISSUE TITLE
Investigate UI/UX for image zooming

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#711]
The image plugin/viewer has zoom in/out, but the UI/UX is a bit odd:
- The div around the image is zoomed.
- Image is not centered if it doesn't occupy the entire area.

**Comment by ellisonbg** [comment]
@spoorthyv could you post an update on this one?

**Comment by spoorthyv** [comment]
Simplified some unrelated image-widget logic in #820. I'm not able to center anything because the width's of the image aren't defined. Unless I give the div a set width it won't be able to horizontally center it.

**Comment by ellisonbg** [comment]
Behavior in master seems decent enough - it is keyboard driven, but is intuitive.
