### ISSUE TITLE
Question: How to add option to filebrowser right click menu

### ISSUE THREAD

**Issue by echyam** [jupyterlab/jupyterlab#7112]
## Description
I'd like to add an extra option when right-clicking a file inside the filebrowser that does something with the filename.  Is there a way I can go about doing by adding an extension instead of going into filebrowser code?

I have a plugin that mirrors the `sharefile` plugin's declaration and activate function, but not sure what to do next.

**Comment by Madhu94** [comment]
Have you also done [this bit](https://github.com/jupyterlab/jupyterlab/blob/083c65d92686d23b813f0242fca5be3d8b6fae37/packages/filebrowser-extension/src/index.ts#L909) ?

**Comment by echyam** [comment]
Trying it out

**Comment by echyam** [comment]
I added that part, but crashing on load at the [line trying to get a reference to the widget tracker](https://github.com/jupyterlab/jupyterlab/blob/083c65d92686d23b813f0242fca5be3d8b6fae37/packages/filebrowser-extension/src/index.ts#L355).

**Comment by Madhu94** [comment]
Can you paste the error/code here or a link to your github repo?

**Comment by echyam** [comment]
My code is [here](https://github.com/MAAP-Project/maap-jupyter-ide/blob/e4f6e0882a5bf367261907855c71b49c740ab3fe/show_ssh_info/src/index.ts#L356).
The console log shows:
```
index.js:267 Plugin 'share-s3-url' failed to activate.
(anonymous) @ index.js:267
Promise.catch (async)
(anonymous) @ index.js:266
push.2R+v.Application.start @ index.js:265
main @ index.out.js:1868
load (async)
ANye @ index.out.js:1914
__webpack_require__ @ bootstrap:84
0 @ bootstrap:221
__webpack_require__ @ bootstrap:84
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ vendors~main.43c4e51dda4c69e05639.js:1

index.js:268 TypeError: Cannot destructure property `tracker` of 'undefined' or 'null'.
    at activateShareUrl (index.js:312)
    at index.js:147
    at async Promise.all (/dashboard/index 103)
```

**Comment by Madhu94** [comment]
The plugin declaration says that this plugin needs just the file browser factory - [here](https://github.com/MAAP-Project/maap-jupyter-ide/blob/e4f6e0882a5bf367261907855c71b49c740ab3fe/show_ssh_info/src/index.ts#L103). But the activate extension expects to be given the command palette _and_ the file browser factory - [here](https://github.com/MAAP-Project/maap-jupyter-ide/blob/e4f6e0882a5bf367261907855c71b49c740ab3fe/show_ssh_info/src/index.ts#L356).

So, in activateShareUrl function, you'd be getting the filebrowser factory assigned to 'palette' variable and 'factory' variable would be ``undefined``.
I think changing ``requires: [IFileBrowserFactory]`` to ``requires: [ICommandPalette, IFileBrowserFactory]`` should work. 

Let me know if something in the above explanation wasn't clear

**Comment by echyam** [comment]
Yeah I completely forgot to update the` requires: [IFileBrowserFactory]` to `requires: [ICommandPalette, IFileBrowserFactory`, and that was the issue!  Thanks for your help!
