### ISSUE TITLE
Dockerfile cannot build

### ISSUE THREAD

**Issue by dieface** [jupyterlab/jupyterlab#7117]
## Description

I try to build Dockerfile at my local computer, but it failed at last step described in Dockerfile.

## Reproduce

1. Download the release/Dockerfile
2. At the same root directory of Dockerfile, run CMD as $docker build -t jupyterlab-image .
3. See error 'E: Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is expired (invalid since 42d 20h 23min 25s). Updates for this repository will not be applied.
E: Release file for http://security.debian.org/debian-security/dists/buster/updates/InRelease is expired (invalid since 44d 14h 17min 57s). Updates for this repository will not be applied.'

![](https://user-images.githubusercontent.com/2155132/63936222-e7d3d900-ca91-11e9-892b-92bbb1b7771a.png)

## Context

- Operating System and version: macOS High Sierra 10.13.6
- Browser and version:
- JupyterLab version: 1.1.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
Does it work if you clone the jupyterlab repo and build it as in the dev instructions? https://github.com/jupyterlab/jupyterlab/blob/master/RELEASE.md#clean-environment-with-docker

**Comment by jasongrout** [comment]
(Note that it's been working fine for me following those instructions)

**Comment by jasongrout** [comment]
Closing since the author did not follow up. Please comment here if you'd like to continue the discussion.
