### ISSUE TITLE
Is there a reason copyToSystem doesn't accept multiple mime types?

### ISSUE THREAD

**Issue by Madhu94** [jupyterlab/jupyterlab#7119]
I want to copy an image from an output area (in user/extension land) and couldn't use [copyToSystem](https://github.com/jupyterlab/jupyterlab/blob/1aff4190084fd5993d3f7e3ae10b467264df1cd0/packages/apputils/src/clipboard.ts#L34)

Can we have an optional `format` param for this method that defaults to text ?

**Comment by blink1073** [comment]
We used text only because at least one of our supported browsers only allowed text on clipboard events.  It could be that this was IE, which we no longer support, and we could offer other types.

**Comment by Madhu94** [comment]
Thanks, shall I make a PR allowing other mime types and possibly allowing mime types ? This can help in the case of fallbacks (e.g. pasting into notepad uses text, but pasting into outlook can use html).  

(I do realize I don't actually need this PR for my extension, I can just use the clipboard API myself directly in the extension)

**Comment by blink1073** [comment]
I took another look at MDN, it looks like as long as we use text for the data itself, we can add whatever mime types we like.

https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setData

**Comment by Madhu94** [comment]
Yeah, the classic notebook has used a custom mime type for copying and
pasting cells.

**Comment by Madhu94** [comment]
Wasn't that feature deliberately left out because we can drag/drop cells across notebooks in lab ?

**Comment by blink1073** [comment]
I think we didn't do it because we have our own clipboard that can have more complex data types and didn't know how to rectify the two clipboards cleanly.

**Comment by Madhu94** [comment]
Closed via  #7202
