### ISSUE TITLE
HTML code to hide 

### ISSUE THREAD

**Issue by firasm** [jupyterlab/jupyterlab#7120]
## Description

I would like to use a bit of HTML to hide/show raw code in my JupyterLab notebooks (for a variety of reasons, related to my teaching of this particular class). The attached file shows a minimum working example that works in ipython notebooks but does not work in jupyterlab. When I say 'does not work' I mean, the cells run, but the HTML to hide and show the raw code does not work.

Here is the expected output when the button is clicked (to show raw data) and then clicked again (to hide it).

![shown](https://user-images.githubusercontent.com/2507459/63963543-23e34b80-ca4a-11e9-9693-4f3cbcd3ac34.png)
![hidden](https://user-images.githubusercontent.com/2507459/63963546-25ad0f00-ca4a-11e9-8c6c-a60c0b8cf1ef.png)

[Hidden Raw Code test.ipynb.zip](https://github.com/jupyterlab/jupyterlab/files/3556752/Hidden.Raw.Code.test.ipynb.zip)

## Reproduce

1. Download .ipynb zip file
2. unzip
3. Try running it as a regular jupyter notebook to see expected behaviour
4. Run in jupyter lab to see broken behaviour

N/A

## Expected behavior

In jupyterlab I expect the raw code cells to be hidden when clicking the button

## Context

- Operating System and version: MacOS 10.14.6
- Browser and version: Safari 12.1.2
- JupyterLab version: Tested on 1.0.4 and 1.1.0

<details><summary>Troubleshoot Output</summary>
<pre>
No output
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
No relevant output
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
This might give a hint? 
![browser](https://user-images.githubusercontent.com/2507459/63963934-e03d1180-ca4a-11e9-98b7-864f5596f1b2.png)
</pre>
</details>

Closely related to #1459 and perhaps this old method of doing it using HTML is no longer needed due to #713... will investigate.

**Comment by jasongrout** [comment]
Right - you are using jquery in that code, and jquery is not used in JupyterLab so isn't available by default. It may work to just use normal DOM apis to do the same thing.

**Comment by jasongrout** [comment]
Closing as answered.

**Comment by ociule** [comment]
FWIW, here's a version that works on Jupyter Lab. It adds jquery and uses the new div classes for input blocks in JupyterLab.

```python
from IPython.display import HTML

HTML('''
<script src='//code.jquery.com/jquery-3.3.1.min.js'></script>
<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 $('div.jp-InputArea').hide()
 } else {
 $('div.input').show();
 $('div.jp-InputArea').show();
 }
 code_show = !code_show
}
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Code on/off"></form>''')
```

**Comment by vidartf** [comment]
Note that a cleaner way to achieve these things might be to use voila: https://github.com/voila-dashboards/voila
