### ISSUE TITLE
Sidebar and notebook tabs broken

### ISSUE THREAD

**Issue by ieglonew01f** [jupyterlab/jupyterlab#7132]
## Description
The sidebar is totally broken, and icons are missing as well as for notebook tabs.

## Side Bar
<img width="112" alt="Screenshot 2019-08-30 at 2 39 51 PM" src="https://user-images.githubusercontent.com/9274615/64008638-202bf380-cb34-11e9-8b7b-55819565b701.png">

## Notebook Tab
![Screenshot 2019-08-30 at 2 40 08 PM](https://user-images.githubusercontent.com/9274615/64008639-202bf380-cb34-11e9-852f-1c608f90f2f7.png)

## JS Error in this method
![Screenshot 2019-08-30 at 2 40 15 PM](https://user-images.githubusercontent.com/9274615/64008640-20c48a00-cb34-11e9-8de2-21dd944633d9.png)

## Expected behavior

Should load the sidebar icons and notebook tab icons.

## Context

- Operating System and version: OSX Mojave
- Browser and version: Chrome 76.0.3809.100 (Official Build) (64-bit)
- JupyterLab version: 1.0.1
- Jupyter version: 4.4.0

**Comment by remborg** [comment]
I believe this is similar to https://github.com/jupyterlab/jupyterlab/issues/7122
Try updating Jupyter Lab to v1.1.1, this should fix the issue.
