### ISSUE TITLE
Reinstalled Anaconda - conda error (DDL load fail, SSL module error

### ISSUE THREAD

**Issue by anninape** [jupyterlab/jupyterlab#7134]
## After a company systems update, I was unable to launch Jupyter Lab via conda.
Here is the error code:
![image](https://user-images.githubusercontent.com/40563328/64029265-8e78b200-cb44-11e9-8504-307a4306ecab.png)

After reading online, I copied the 
libcrypto-1_1-x64.dll
libcrypto-1_1-x64.pdb
libssl-1_1-x64.dll
libssl-1_1-x64.pdb folder from anaconda3\Library\bin to anaconda3\DLLs.

This lets me start Jupyter Notebook but not Jupyter lab. Instead I get this:
![image](https://user-images.githubusercontent.com/40563328/64029707-705f8180-cb45-11e9-9ab3-09518c4ab121.png)
This I resolved with jupyter lab--core-mode.

However,  as soon as I try to import packages or recreate an environment, I get 0% loading and the following message:

"[WinError 126] The specified module could not be found"
for basically every package possible.

So I guess, the whole system is somehow corrupted. 
I tried to run do the whole uninstallment procedure with Option B (conda install anaconda-clean) specified on Anaconda's website but that does not work either

![image](https://user-images.githubusercontent.com/40563328/64029995-00053000-cb46-11e9-8d1c-abfecdd8f259.png)

So I simply deinstalled via Systems settings and deleted remaining folder manually.
I reinstalled but not success - always same outcome.
I use Windows 10 and downloaded the latest Anaconda version (Anaconda3-2019.07-Windows-x86_64.exe).

**Comment by jasongrout** [comment]
This looks like a configuration issue with your anaconda install, and particularly something to do with the network connection (proxy issues?). Can you try filing an issue with Anaconda?

**Comment by anninape** [comment]
@jasongrout done under #11241 in the anaconda-issues tracker with your comment on configuration/network connection. Fingers crossed they can help to sort it out ;)

**Comment by jasongrout** [comment]
For completeness: https://github.com/ContinuumIO/anaconda-issues/issues/11241
