### ISSUE TITLE
Disable launching browser via jupyter_notebook_config.py

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#7135]
## Description
It is not possible to disable the browser from launching when Jupyter does in jupyter_notebook_config.py.

## Reproduce
Setting `c.LabApp.browser = ''` then launching jupyter-lab still opens the default browser. 
## Expected behavior

This should work the same as `--no-browser` using via CLI. Setting `c.LabApp.browser = None` is an error.

## Context

- Operating System and version: Linux
- Browser and version: N/A
- JupyterLab version: 1.1.1

**Comment by vidartf** [comment]
Does setting `c.LabApp.browser = "none"` work?

**Comment by mlucool** [comment]
That would attempt to launch a program called `none`

**Comment by vidartf** [comment]
Did you try it? For me it only gives the warning
```
[W 14:42:10.023 LabApp] No web browser found: could not locate runnable browser.
```

Either way, I looked in the source, and the `--no-browser` flag sets the config option `LabApp.open_browser = False`, so I believe that would be what you want

**Comment by mlucool** [comment]
`LabApp.open_browser = False` is what I am looking for thanks! After you mentioned it, I was able to find [documentation here](https://jupyter-notebook.readthedocs.io/en/stable/config.html).

In general warnings add clutter so I wanted to avoid that (aside from the risk that some program called none gets added to the path at some point).
