### ISSUE TITLE
Feature request: allow multiple commands for the same shortcut

### ISSUE THREAD

**Issue by lucatrv** [jupyterlab/jupyterlab#7138]
As in subject, this may have several applications. For instance, I installed the [jupyterlab_code_formatter](https://github.com/ryantam626/jupyterlab_code_formatter) extension, and I would like to run both commands `jupyterlab_code_formatter:black` and `jupyterlab_code_formatter:isort` every time I run a cell, so I would like to redefine the `Ctrl Enter` and `Shift Enter` shortcuts accordingly.
 
This could be implemented in either one of the following ways:

1. Change the `command` field into `commands`, and have it accept a list instead of a string (similarly to the `keys` field).
2. Allow multiple shortcut definitions for the same keystroke (so for instance the `Ctrl Enter` keystroke would run all the commands of the corresponding shortcut definitions).

**Comment by jasongrout** [comment]
With option 2, there would probably be confusion about the ordering of the commands.

I could imagine something like option 1. Perhaps the easiest way to do that is to have a new command to "run these commands" with args of what commands to run. Then you just make a keyboard shortcut for that command with the args of the commands you want to run.

**Comment by jasongrout** [comment]
Whoever wants to try doing this (do you want to, @lucatrv?), I'd suggest putting the command right next to https://github.com/jupyterlab/jupyterlab/blob/3661029aa5777b1390fff262cf0da07757dbac5a/packages/apputils-extension/src/index.ts#L260-L279 and mirroring the structure of that plugin (i.e., a small activate function that adds a single command). Just take as args a list of strings, and then execute those commands one by one.

**Comment by lucatrv** [comment]
IMHO it would be more clear for the user if `command` (or better `commands`) behaved like `keys` (accepting a list). I mean it would be very clear to everyone that this capability is available.

**Comment by jasongrout** [comment]
The problem with that is how to expose the shortcut to the user? If you make a new command that executes other commands, it is easy to put it in the menu, in a command palette, etc., and the keystroke naturally shows up.

**Comment by jasongrout** [comment]
So your keyboard shortcut would have command name `apputils:execute-commands` and args `['jupyterlab_code_formatter:black', 'jupyterlab_code_formatter:isort']`. Then it is very easy to add the same command/args to a menu, etc., and the keyboard shortcut naturally follows. In fact, the `apputils:execute-commands` label can concatenate and use the labels from the other commands, so it would look nice in a menu, like "Do X, then Y" or whatever.

**Comment by jasongrout** [comment]
Basically, if we have a composition command like this, we can compose commands everywhere and it plays nicely with the current system (has a nice label, can reason about enabled and shown status, can have a shortcut that automatically shows up, can be added to menus, the palette, etc.). If we do a one-off composing commands just for shortcuts with a special syntax, it complicates the keyboard shortcut syntax and doesn't help us anywhere else we'd like to compose commands.

**Comment by lucatrv** [comment]
OK now I see your point. But sorry, unfortunately I'm not comfortable enough with TypeScript and JupyterLab to implement that new command...

**Comment by jasongrout** [comment]
No problem, I've tagged it as a good first issue for someone to pick up. We could help you through the process - it's mainly copying the code snippet I pointed out above and tweaking it.

**Comment by meetsitaram** [comment]
Let me try this.

**Comment by richardkang112** [comment]
Hello. May I work on this issue?

**Comment by meetsitaram** [comment]
> Hello. May I work on this issue?

I am no longer working on it.

**Comment by krassowski** [comment]
The suggestion from https://github.com/jupyterlab/jupyterlab/issues/7138#issuecomment-526863115 is already implemented and available in JupyterLab 3.1 thanks to #10215. This requires to define a shortcut for `apputils:run-all-enabled` and pass the commands to be run in succession in the `args` argument:

```js
{
    "command": "apputils:run-all-enabled",
    "keys": ["F3"],
    "args": {
        "commands": [
            "filemenu:open",
            "application:activate-previous-tab"
        ]
    },
    "selector": "body"
}
```

I think that all that's left is documenting this behaviour in documentation for shortcuts. Are you still interested @richardkang112?

**Comment by richardkang112** [comment]
@krassowski Sure, I'll work on the documentation. Thank you!

**Comment by anthonyaag** [comment]
Should this issue be closed? I think the documentation added solves this problem. 

Related comment, is it possible to add the documentation from #10754 to the next release?

**Comment by lucatrv** [comment]
Yes this feature has been implemented so I'm closing the issue, thanks.
