### ISSUE TITLE
Cannot use PgUp / PgDown for shortcuts? 

### ISSUE THREAD

**Issue by lucatrv** [jupyterlab/jupyterlab#7139]
I'm using JupyterLab v1.1.1 on Windows 7 with Firefox 68. I'm not sure whether this is a bug or a missing feature. I would like to define `Ctrl Alt PgUp` and `Ctrl Alt PgDown` keyboard shortcuts to switch to previous / next tabs, but they do not seem to work (while they work if I use other keystrokes). Apparently JupyterLab does not recognize the `PgUp` / `PgDown` keystrokes?

**Comment by jasongrout** [comment]
Try "PageUp" and "PageDown": https://github.com/phosphorjs/phosphor/blob/08aa9ce0ee47105547a4debc93da5cd02e5eba12/packages/keyboard/src/index.ts#L215-L216

**Comment by lucatrv** [comment]
I'm ashamed, I was sure I had already attempted that... maybe I had another issue at the time. Yes it works. I'm closing this issue right away, thanks.
