### ISSUE TITLE
tab and side tab syntax error in 1.0.5

### ISSUE THREAD

**Issue by nchos88** [jupyterlab/jupyterlab#7140]
![taberror](https://user-images.githubusercontent.com/36718545/64084223-07a22000-cd64-11e9-8c55-c777af1b96ce.png)

windows 10 
python 3.6 
jupyter lab 1.0.5

after update jupyter lab 0.35.4 to 1.0.5,  tab error occur in firefox , chrome , edge browser

-- package detail --
Package                           Version
--------------------------------- ---------
appdirs                           1.4.3
asn1crypto                        0.24.0
attrs                             18.1.0
backcall                          0.1.0
beautifulsoup4                    4.7.1
black                             19.3b0
bleach                            3.1.0
certifi                           2019.6.16
cffi                              1.11.5
chardet                           3.0.4
Click                             7.0
colorama                          0.4.1
conda                             4.7.11
conda-package-handling            1.4.1
ConfigArgParse                    0.14.0
coursera-dl                       0.11.4
cryptography                      2.4.2
decorator                         4.4.0
defusedxml                        0.5.0
entrypoints                       0.3
idna                              2.8
ipykernel                         5.1.0
ipython                           7.7.0
ipython-genutils                  0.2.0
ipywidgets                        7.4.2
jedi                              0.13.3
Jinja2                            2.10
json5                             0.8.5
jsonschema                        3.0.1
jupyter-client                    5.2.4
jupyter-console                   6.0.0
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.4.0
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.4
jupyter-nbextensions-configurator 0.4.1
jupyterlab                        1.0.5
jupyterlab-server                 1.0.0
keyring                           19.0.1
libarchive-c                      2.8
lxml                              4.3.3
MarkupSafe                        1.1.1
menuinst                          1.4.14
mistune                           0.8.4
nb-conda                          2.2.1
nb-conda-kernels                  2.2.1
nbconvert                         5.4.1
nbformat                          4.4.0
notebook                          5.7.8
numpy                             1.16.3
pandas                            0.24.2
pandocfilters                     1.4.2
parso                             0.3.4
pickleshare                       0.7.5
pip                               18.1
prometheus-client                 0.6.0
prompt-toolkit                    2.0.9
pyasn1                            0.4.5
pycosat                           0.6.3
pycparser                         2.19
Pygments                          2.3.1
pyOpenSSL                         18.0.0
pyrsistent                        0.14.11
PySocks                           1.6.8
python-dateutil                   2.8.0
pytz                              2019.1
pywin32                           223
pywin32-ctypes                    0.2.0
pywinpty                          0.5.5
PyYAML                            5.1
pyzmq                             18.0.1
qtconsole                         4.4.3
requests                          2.21.0
ruamel-yaml                       0.15.46
scikit-learn                      0.20.3
scipy                             1.2.1
Send2Trash                        1.5.0
setuptools                        40.6.3
six                               1.12.0
soupsieve                         1.9.1
terminado                         0.8.2
testpath                          0.4.2
toml                              0.10.0
tornado                           6.0.3
tqdm                              4.33.0
traitlets                         4.3.2
urllib3                           1.24.1
wcwidth                           0.1.7
webencodings                      0.5.1
wheel                             0.32.3
widgetsnbextension                3.4.2
win-inet-pton                     1.0.1
wincertstore                      0.2

**Comment by twrobinson** [comment]
This is a dup of #7122, #7132 and #7129 
Updating Jupyter Lab to v1.1.1 should fix the issue.

**Comment by blink1073** [comment]
Thanks for the report @nchos88!  I'm closing this in favor of #7158 which is tracking the same issue.
