### ISSUE TITLE
Jupyter Lab refuses to open markdown file because of encoding

### ISSUE THREAD

**Issue by asteppke** [jupyterlab/jupyterlab#7141]
With the current jupyter lab 1.0.2 I tried to open several markdown files but jupyter lab refuses. The files contain only a short text note and the error message popup looks as follows:

![image](https://user-images.githubusercontent.com/5851636/64130212-1b2fa400-cdc1-11e9-8a58-fa952816a867.png)

That is quite confusing, as jupyter lab claims to be able to edit markdown files and no further explanation is given. It turns out these files were saved with MS Notepad before and the encoding is ANSI, not UTF8. 

Can other encodings for text files be either detected or the error message adjusted accordingly? In the current form this is confusing as markdown should be compatible with any editor that understands raw text files.

**Comment by jasongrout** [comment]
Great question. Can you open the file in the classic notebook? My guess is that won't work either. I think the error here is coming from the notebook server (https://github.com/jupyter/notebook/), and JupyterLab is just relaying the message it gets from the server. In that case, let's move this conversation to the [notebook server](https://github.com/jupyter/notebook) repo to have a better error message about not being utf8-encoded.

**Comment by jasongrout** [comment]
According to https://github.com/jupyter/notebook/blob/c2d4561ba6b25ec4e0f1f9ec617c3338f4de1ef4/notebook/services/contents/fileio.py#L296-L323, it appears it should be returning an error that the file wasn't utf-8. Can you attach an example file that doesn't work?

**Comment by jasongrout** [comment]
I investigated more after making a non-utf-8 file from python:

The server is sending a better error message:
https://github.com/jupyter/notebook/blob/c2d4561ba6b25ec4e0f1f9ec617c3338f4de1ef4/notebook/services/contents/fileio.py#L318-L321

We aren't reading that better error message in JupyterLab:
https://github.com/jupyterlab/jupyterlab/blob/3661029aa5777b1390fff262cf0da07757dbac5a/packages/docregistry/src/context.ts#L580-L589

We can get that error message with `await err.response.json()`

Setting this as a good first issue - whoever takes it up could get the error response message and put that in the error dialog box. Or they could simply assume that a 'bad format' error is a utf-8 encode error and make a better error message in JupyterLab.

**Comment by jasongrout** [comment]
Here is some python code to create a simple file that is not utf8 encoded:

```python
with open('test.txt', 'wb') as f:
    f.write('example text'.encode('utf_32'))
```

**Comment by jasongrout** [comment]
(A much more advanced change to the notebook server is using something like the chardet library to try to guess the file encoding)

**Comment by asteppke** [comment]
@jasongrout Thank you for looking into this! 

If the error message points out that a non-utf-8 file is not accepted that would benefit the usability quite a bit. 

Detecting encoding might be possible as you said, but thinking more about this opens up more issues how to deal with them (conversion, display, ask about encoding on save...) and that seems not necessary for the large majority of cases and is handled well in external text editors.

**Comment by ybirajdar** [comment]
I am looking at this now

**Comment by kavishdahekar** [comment]
Hey @ybirajdar , it's been some time so if you're not looking at this anymore I'd like to take it up.
