### ISSUE TITLE
JupyterLab and IPython create too many OS threads

### ISSUE THREAD

**Issue by robnagler** [jupyterlab/jupyterlab#7149]
## Description

We run a small JupyterHub installation. At one point, we were running 10 users on one of our nodes (16 cores, 64GB), and we hit Red Hat's default process limit per user (4096), which is designed to prevent [fork bombs](https://bugzilla.redhat.com/show_bug.cgi?id=432903). The node was not overloaded (load avg < 1) nor was it a fork bomb. There were just many threads created by ipykernel_launcher and jupyter-labhub. 

It seems that the average number of threads in our environment is 250 per user (with 60 users). Does that seem right?

I was wondering if a lightweight threading system was (is being) considered for JupyterLab, at least, if not IPython. I realize this is a big architectural issue.

## Reproduce

1. Start jupyter labn
2. ps axhuH | egrep -c '(bin/jupyter-labhub|ipykernel_launcher)'

## Expected behavior

I would think there would be a handful of Unix processes, like Nginx uses.

## Context

- Operating System and version: CentOS 7 hosting Fedora 29 Docker containers
- Browser and version: n/a
- JupyterLab version: 1.1.1

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/vagrant/.pyenv/versions/jupyter/bin
	/home/vagrant/.pyenv/libexec
	/home/vagrant/.pyenv/plugins/python-build/bin
	/home/vagrant/.pyenv/plugins/pyenv-virtualenv/bin
	/home/vagrant/.pyenv/plugins/pyenv-update/bin
	/home/vagrant/.pyenv/plugins/pyenv-installer/bin
	/home/vagrant/.pyenv/plugins/pyenv-doctor/bin
	/home/vagrant/jupyter/bin
	/home/vagrant/.pyenv/plugins/pyenv-virtualenv/shims
	/home/vagrant/.pyenv/shims
	/home/vagrant/.pyenv/bin
	/home/vagrant/.local/bin
	/home/vagrant/bin
	/usr/lib64/mpich/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/home/vagrant/.pyenv/versions/3.7.2/envs/jupyter/bin
	/home/vagrant/.pyenv/versions/3.7.2/envs/jupyter/lib/python37.zip
	/home/vagrant/.pyenv/versions/3.7.2/envs/jupyter/lib/python3.7
	/home/vagrant/.pyenv/versions/3.7.2/envs/jupyter/lib/python3.7/lib-dynload
	/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7
	/home/vagrant/.pyenv/versions/3.7.2/envs/jupyter/lib/python3.7/site-packages

sys.executable:
	/home/vagrant/.pyenv/versions/3.7.2/envs/jupyter/bin/python3.7

sys.version:
	3.7.2 (default, Jul  3 2019, 16:26:37)
	[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]

platform.platform():
	Linux-3.10.0-957.1.3.el7.x86_64-x86_64-with-fedora-29-Twenty_Nine

which -a jupyter:
	/home/vagrant/.pyenv/versions/jupyter/bin/jupyter
	/home/vagrant/.pyenv/shims/jupyter

pip list:
	Package             Version
	------------------- ---------
	alembic             1.1.0
	asn1crypto          0.24.0
	async-generator     1.10
	atomicwrites        1.3.0
	attrs               19.1.0
	backcall            0.1.0
	bleach              3.1.0
	certifi             2019.6.16
	certipy             0.1.3
	cffi                1.12.3
	chardet             3.0.4
	cryptography        2.7
	cycler              0.10.0
	decorator           4.4.0
	defusedxml          0.6.0
	entrypoints         0.3
	h5py                2.9.0
	idna                2.8
	importlib-metadata  0.19
	ipykernel           5.1.2
	ipympl              0.3.3
	ipython             7.8.0
	ipython-genutils    0.2.0
	ipywidgets          7.5.1
	jedi                0.15.1
	Jinja2              2.10.1
	json5               0.8.5
	jsonschema          3.0.2
	jupyter             1.0.0
	jupyter-client      5.3.1
	jupyter-console     6.0.0
	jupyter-core        4.5.0
	jupyterhub          1.0.0
	jupyterlab          1.1.1
	jupyterlab-launcher 0.13.1
	jupyterlab-server   1.0.6
	kiwisolver          1.1.0
	Mako                1.1.0
	MarkupSafe          1.1.1
	matplotlib          3.1.1
	mistune             0.8.4
	more-itertools      7.2.0
	nbconvert           5.6.0
	nbformat            4.4.0
	nbzip               0.1.0
	notebook            6.0.1
	numpy               1.17.1
	oauthlib            3.1.0
	openPMD-viewer      0.9.0
	packaging           19.1
	pamela              1.0.0
	pandocfilters       1.4.2
	parso               0.5.1
	pexpect             4.7.0
	pickleshare         0.7.5
	pip                 19.2.3
	plotly              4.1.0
	pluggy              0.12.0
	prometheus-client   0.7.1
	prompt-toolkit      2.0.9
	ptyprocess          0.6.0
	py                  1.8.0
	pycparser           2.19
	Pygments            2.4.2
	pyOpenSSL           19.0.0
	pyparsing           2.4.2
	pyrsistent          0.15.4
	pytest              5.1.2
	python-dateutil     2.8.0
	python-editor       1.0.4
	pyzmq               18.1.0
	qtconsole           4.5.4
	requests            2.22.0
	retrying            1.3.3
	scipy               1.3.1
	Send2Trash          1.5.0
	setuptools          41.2.0
	six                 1.12.0
	SQLAlchemy          1.3.8
	terminado           0.8.2
	testpath            0.4.2
	tornado             6.0.3
	traitlets           4.3.2
	urllib3             1.25.3
	wcwidth             0.1.7
	webencodings        0.5.1
	wheel               0.33.6
	widgetsnbextension  3.5.1
	zipp                0.6.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
n/a
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
n/a
</pre>
</details>

**Comment by jasongrout** [comment]
> I was wondering if a lightweight threading system was (is being) considered for JupyterLab, at least, if not IPython. I realize this is a big architectural issue.

I don't know any work towards this. There is a new xeus-based python kernel that may have better behavior?

It sounds like perhaps this is an ipykernel or jhub issue?

**Comment by robnagler** [comment]
Could be. If I run `jupyter lab`, there are only two threads. It's when it is run via JupyterHub that the threads show up. It could be ThreadPoolExecutor being instantiated multiple times with default number of threads. We've adjusted our configuration to avoid the issue so I'll close this.
