### ISSUE TITLE
Explicitly state how to editing PATH for pip install --user

### ISSUE THREAD

**Issue by AustinWise** [jupyterlab/jupyterlab#7151]
In the [instructions](https://github.com/jupyterlab/jupyterlab#pip) for using `pip install --user`, the documentation states:

> If installing using ``pip install --user``, you must add the user-level
> ``bin`` directory to your ``PATH`` environment variable in order to launch
> ``jupyter lab``.

For non-expert users it might be helpful to include an example command for accomplishing that. For example:

```bash
echo "export PATH=\$PATH:$(python -c "import site; print(site.getuserbase())")/bin" >> ~/.profile
```

That worked for me, but I'm not sure that is covers all the cases or if it is worth including in the installation instructions.

**Comment by NathanaelGandhi** [comment]
I agree this is helpful for non-experts.

Is there any advantage to setting the PATH like this?
```
# set PATH so it includes user's private ~/.local/bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```
I came across this at https://askubuntu.com/questions/1113806/how-can-i-add-local-bin-to-my-path while trying to set my PATH environment variable.

**Comment by KaeroDot** [comment]
Or there could be at least a mention that e.g. at linux installation one can run it using
    ~/.local/bin/jupyter lab

**Comment by woswos** [comment]
Hi,
I mentioned this issue as a part of another issue I created (#8259) and I saw this issue after creating #8259. I would love to hear your feedback on my PR. 

@KaeroDot I included your suggestion as well!

**Comment by AustinWise** [comment]
@woswos Thanks for getting improvements merged!

**Comment by goodyonsen** [comment]
Any clue for adding path on windows cmd?  
I installed it like this: ` c:\> pip install jupyterlab `
And now I type these following separately at once and not getting any response for each: ` jupyterlab`, `jupyter`, `jupyter notebook`

**Comment by woswos** [comment]
@goodyonsen I couldn't test myself since I don't use windows, but this tutorial might help. They mention how to update the path as well. https://medium.com/@neuralnets/beginners-quick-guide-for-handling-issues-launching-jupyter-notebook-for-python-using-anaconda-8be3d57a209b

**Comment by goodyonsen** [comment]
Thank you sir! I guess I'm going to have to install Anaconda anyways which as far as I'm concerned isn't mentioned as a requirement here: https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html
