### ISSUE TITLE
Background color of selected text in dark theme is the same as that of selected cell.

### ISSUE THREAD

**Issue by jagkagd** [jupyterlab/jupyterlab#7152]
## Description

As the title says. Hard to know where is the selected context in dark theme.

## Reproduce

As below, when selecte `[1, 2, 3]`
Light theme:
![图片](https://user-images.githubusercontent.com/12371759/64261620-61bb0500-cf5f-11e9-8458-541ebb389010.png)

Dark theme:
![图片](https://user-images.githubusercontent.com/12371759/64261768-9b8c0b80-cf5f-11e9-8490-f12643bed61d.png)

## Context

- Operating System and version: Win 8.1
- Browser and version: Firefox 68.0.2
- JupyterLab version: 1.0.1

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
For me (JLab 1.1.1, FF 69, macOS), it is a dark blue:
<img width="274" alt="Screen Shot 2019-09-04 at 8 03 45 AM" src="https://user-images.githubusercontent.com/192614/64267112-a9537980-ceea-11e9-873e-80ef138a5348.png">


Can you try in JLab 1.1.1?

**Comment by jagkagd** [comment]
> 
> 
> For me (JLab 1.1.1, FF 69, macOS), it is a dark blue:
> <img alt="Screen Shot 2019-09-04 at 8 03 45 AM" width="274" src="https://user-images.githubusercontent.com/192614/64267112-a9537980-ceea-11e9-873e-80ef138a5348.png">
> 
> Can you try in JLab 1.1.1?

I've tried, but nothing changed.
And I also found that in the light theme there's the similar question. The black background color has covered the text.
![图片](https://user-images.githubusercontent.com/12371759/64306130-4209f800-cfc4-11e9-899a-8fabd136eda3.png)

**Comment by jagkagd** [comment]
I know what happaned. I have incorrectly enabled a stylish theme which I had used before the jupyter has a dark theme.

**Comment by tgeorgeux** [comment]
@jagkagd thank you for following up and closing the loop! I was trying to replicate the issue in 1.0 and 1.1 and was unable. Cheers.
