### ISSUE TITLE
Progress for spinner while building JupyterLab goes counter-clockwise

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7169]
To reproduce, do `jupyter lab build` and observe the character progress spinner going counter-clockwise.

Most progress spinners go clockwise. While there is nothing intrinsically wrong with going counter-clockwise, it is a bit unsettling and seems not normal, when what we are trying to convey to the user is that everything is going normally.

The relevant code is in https://github.com/jupyterlab/jupyterlab/blob/ba4c0742443e672285bc852a285737f45e1ff212/jupyterlab/commands.py#L91

I think just changing the order of those characters may be enough to switch to a clockwise spinner.

**Comment by bw-space** [comment]
I want to help solve this issue.

**Comment by bw-space** [comment]
I have made the changes and have created the following pull request:
https://github.com/jupyterlab/jupyterlab/pull/7170

**Comment by jasongrout** [comment]
Fixed by #7170
