### ISSUE TITLE
Changes not reflected after jupyterlab install with file changes

### ISSUE THREAD

**Issue by bw-space** [jupyterlab/jupyterlab#7173]
I have made some changes to some of the package files(like packages/notebook/src/actions.tsx), but I am unable to see the changes in the jupyter lab session, can you please help me with where I am going wrong.
The steps I followed were:
1. jlpm clean
2. jlpm build:packages
3. jlpm run build
4. sudo python3 -m pip install -e .
5. jupyter lab

**Comment by jasongrout** [comment]
> jupyter lab

Do `jupyter lab --dev-mode`. See https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#run-jupyterlab

**Comment by bw-space** [comment]
@jasongrout I have, commented out the body of the function: selectAbove(...) from jupyterlab/packages/notebook/src/actions.tsx
also I have changed the key bindings in the file: jupyter/packages/notebook-extension/schema/tracker.json and interchanged the [Shift ArrowUp], [Shift ArrowDown] and run-
`jupyter lab --dev-mode`,
 but there are no changes in the default action.

**Comment by jasongrout** [comment]
Did you refresh your browser, and turn off your browser cache?

To double-check, I would insert a `console.log('Running new code');` somewhere and check to make sure it is printed to the browser log, just to make sure that you are actually loading the new code.

**Comment by bw-space** [comment]
I have used a seperate browser with cache disabled, I have inserted  
`console.log('Running new code');` in packages/application-extension/src/index.tsx under
`console.log(`Starting application in workspace: "${workspace}"`);`
but "Running new code" is not shown in the browser console.

**Comment by jasongrout** [comment]
>  but "Running new code" is not shown in the browser console.

This indicates that the jupyterlab you are starting is not the one you've made changes to. I would check:

1. Make *sure* you are starting the right JupyterLab. `which jupyter-lab` can help you determine the jupyter lab you are actually starting.
2. Launch `jupyter lab --dev-mode --debug` and check that the files it is serving are the files you expect to be serving
3. Make sure there is a red top border of the page. If there isn't, it's not running in `--dev-mode`.

If all that fails, I would try making a clean new environment and follow the instructions in the contributing guidelines above.

**Comment by bw-space** [comment]
In debug mode it shows me:

> [I 23:28:30.689 LabApp] You're running JupyterLab from source.
>     If you're working on the TypeScript sources of JupyterLab, try running
>     
>         jupyter lab --dev-mode --watch
>     
>     
>     to have the system incrementally watch and build JupyterLab for you, as you
>     make changes.
I have used `jupyter lab --dev-mode --watch` it notices file changes, and re-compiles.

**Comment by bw-space** [comment]
Thanks a ton @jasongrout . Now some of the changes are being reflected. Thanks for taking some time out to reply to my queries.

**Comment by jasongrout** [comment]
Great! Closing as resolved.
