### ISSUE TITLE
Don't hardcode max memory

### ISSUE THREAD

**Issue by timkpaine** [jupyterlab/jupyterlab#7175]
These lines look wrong, for [my build](https://github.com/timkpaine/tkp_jupyterlab) i generally require ~8GB+ of memory for it to complete.
https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/staging/package.json#L9

The result when you go out of memory during the build is that it hangs forever on the spinning slashes with no indication of what happened, even when passing `--debug`. The `node yarn.js run build:prod:minimize` itself hangs when it goes oom.

**Comment by mlucool** [comment]
In node 12, this flag should *not* be used either:

> With the release of Node.js 12, the JS heap size will be configured based on available memory, which ensures Node doesn’t try to use more memory than is available and terminate processes when its memory is exhausted.
https://blog.logrocket.com/node-js-12/

**Comment by jasongrout** [comment]
That would be great to get rid of the hard-coded max memory size.

Node 12 becomes LTS at the end of October. How about we assume Node 12 for JLab 2.0 in January, and get rid of the max memory setting by then for sure.

Do you have a suggestion for what to do until then?

**Comment by mlucool** [comment]
An ugly, but easy to do solution could be to wrap webpack with a simple script deals with this. This would basically set NODE_OPTIONS if they are not set to include max_old_space then forwarding on all other args.

Once node 12 is assumed, reverting would be as simple as replacing `webpackHack.js` with `webpack` again.

**Comment by timkpaine** [comment]
I don't know if it works on windows but you can do parameter substitution of env vars:
`NODE_OPTIONS=${NODE_OPTIONS:-"--max_old_space_size=4096"}`

**Comment by jasongrout** [comment]
> I don't know if it works on windows but you can do parameter substitution of env vars:
> `NODE_OPTIONS=${NODE_OPTIONS:-"--max_old_space_size=4096"}`

That is just setting a default value?

**Comment by jasongrout** [comment]
We are currently using cross-env to set the variable. cross-env points out a variant that allows setting default values: https://www.npmjs.com/package/cross-env#other-solutions - but that variant apparently is very little used.

**Comment by jasongrout** [comment]
> An ugly, but easy to do solution could be to wrap webpack with a simple script deals with this. This would basically set NODE_OPTIONS if they are not set to include max_old_space then forwarding on all other args.

That sounds great (well, ugly, like you say, but it gets the job done until 2.0), if we can do it in a cross-platform way.

**Comment by mlucool** [comment]
> That sounds great (well, ugly, like you say, but it gets the job done until 2.0), if we can do it in a cross-platform way.

I have not tested this very much, but this worked on linux and I don't see why it wouldn't work on windows:
```
const child_process = require('child_process');

const args = process.argv.slice(2);

if(!process.env.NODE_OPTIONS) {
    process.env.NODE_OPTIONS = '--max_old_space_size=4096';
}
child_process.execFileSync(process.argv[0], args, {env: process.env, stdio: 'inherit'});
```

Using it
```
$ cat foo.js 
console.log(process.argv);
console.log(process.env);
$ node set-if.js foo.js bar
```
