### ISSUE TITLE
UI glitch with jupyter lab version 1.0.0

### ISSUE THREAD

**Issue by dchandan** [jupyterlab/jupyterlab#7178]
## Description

I recently updated my Conda packages during which jupyterlab was updated from 0.35.5 to 1.0.0. Upon starting the server and connecting to the server from the browser I was prompted in the browser to do a "build". I readily agreed to the prompt (and because of that I don't recall exact details from the prompt). Upon completion of the build I was asked to reload the page and since then I have noticed glitches in the UI as shown below. Note the issue on the left hand side and on the top along the tab-bar.

![fig2](https://user-images.githubusercontent.com/5779123/64559260-dd2c0600-d313-11e9-8041-7514cc8d7c2a.png)

It would seem that there are some error messages printed in those regions but I am unable to reveal them to understand the messages clearly. Javascript console reveals the following message:

![fig4](https://user-images.githubusercontent.com/5779123/64559452-53c90380-d314-11e9-96cc-5b51691b3db1.png)

I am unable to figure out on my own how to fix this. Any help would be appreciated.

**Comment by jasongrout** [comment]
Updating to 1.1.2 should fix this.

**Comment by jasongrout** [comment]
Can you try rebuilding now? We fixed the problem even with rebuilding 1.0.0 (c.f. #7181)

**Comment by jasongrout** [comment]
So you should be able to rebuild, but even better, we would encourage you to upgrade to 1.1.3, or at least to 1.0.10, which would also solve the issue.

**Comment by dchandan** [comment]
Thanks for the help. The problem is resolved by updating to 1.1.2.
