### ISSUE TITLE
v1.1.1/2 build fails with jupyter-widgets (Docker)

### ISSUE THREAD

**Issue by hiramf** [jupyterlab/jupyterlab#7180]
## Description

When installing version 1.1.1 or 1.1.2, there is a request to build for ipywidgets, but it fails (and takes forever). Adding a `RUN jupyter lab build` fails, but it works if you run it inside the container after it starts up.

The difference that stands out is the line for `Building jupyterlab assets`:
`(build:prod:minimize)` in docker fails, but `(build:dev)` works when you run after starting the server.

## Reproduce

Here is my Dockerfile, which comes from the official[ Jupyter datascience-notebook image](https://github.com/jupyter/docker-stacks):
```
# Jupyter docker image
FROM jupyter/datascience-notebook

RUN conda install -c conda-forge jupyterlab=1.1.2
RUN jupyter lab build

USER $NB_UID
```

And here are the logs:
```
[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Node v11.14.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 27.84s.

[LabBuildApp] > node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer
[LabBuildApp] yarn run v1.15.2
$ /opt/conda/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer
Done in 0.87s.

[LabBuildApp] > node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.15.2
$ cross-env NODE_OPTIONS=--max_old_space_size=4096 webpack --config webpack.prod.minimize.config.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labapp.py", line 96, in start
    core_config=self.core_config)

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 583, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by jasongrout** [comment]
Thanks. Who publishes that docker image? What is currently in it? Do they know about this issue?

**Comment by hiramf** [comment]
> Thanks. Who publishes that docker image? What is currently in it? Do they know about this issue?

Looks like it's made by Jupyter itself.

Added a link in my description, but here's the repo:
https://github.com/jupyter/docker-stacks

**Comment by jasongrout** [comment]
Tracing through the images, looks like it comes with jlab 1.0.4: https://github.com/jupyter/docker-stacks/blob/82d1d0bf0867e410a2abc66862fa77c3e2a8d304/base-notebook/Dockerfile#L107

**Comment by jasongrout** [comment]
Of note, `build:prod:minimize` takes significantly more time and memory. Perhaps `jupyter lab build --minimize=False` would work if it is a resource issue.

**Comment by hiramf** [comment]
> Of note, `build:prod:minimize` takes significantly more time and memory. Perhaps `jupyter lab build --minimize=False` would work if it is a resource issue.

That would be worth looking into, it seems like there is some inconsistency in whether the build fails or not. (I'm using Docker/PowerShell/Windows 10).

**Comment by jeremy886** [comment]
```
[LabBuildApp] JupyterLab 1.1.3
[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
```

I encountered the same issue here. 
After adding **build --minimize=False** to Dockerfile, it works like a charm.

**Comment by jasongrout** [comment]
Thanks! Closing as answered then. @hiramf - if you find it is still having issues, please comment below or open a new issue.
