### ISSUE TITLE
Toggle cell to "readonly" once the cell has been executed once 

### ISSUE THREAD

**Issue by KedoKudo** [jupyterlab/jupyterlab#7191]
We are current using Jupyter to perform some routine _system control_, and it is very important for us to retain a record of what has been sent to the devices.  Currently, it is very easy for someone to clear the incorrect cmds by editing or deleting the cell, which can be problematic for trouble-shooting.  Is it possible to create a new mode (with a toggle) that will turn the notebook into a special mode where:

* cell can be edited and changed as usual as long as it has not been executed.
* once a cell is executed, both the output and the cell content will be __readonly__ and cannot be deleted.

**Comment by jasongrout** [comment]
Certainly its possible to create a notebook viewer with those constraints. You could do it as a separate extension, largely built on the existing extension. Some things you might think about:

1. You can connect to kernels using consoles as well. How do you defend against that?
2. How do you deal with adding new cells at arbitrary places in the notebook? It can be confusing to execute 5 cells, then insert a new one in between them.
3. This also does not defend against other plugins connecting to the session and executing code.

Perhaps a better approach is logging at the server level?

**Comment by KedoKudo** [comment]
@jasongrout Thanks for the feedback.  Logging at the server level is our fallback solution.  However, having the history directly available in the notebook would make the trouble shooting a lot easier.  As for building the extension, what would be the best place for me to start?

**Comment by jasongrout** [comment]
A great place to start is the extension tutorial: https://jupyterlab.readthedocs.io/en/stable/developer/extension_tutorial.html

After that, the rendering extension tutorial might also be good to get a feel for how JLab handles document renderers. You can see this in the [scipy 2019 jlab tutorial video](https://www.youtube.com/watch?v=RFabWieskak) around 2 hours in (tutorial materials at https://github.com/jupyterlab/scipy2019-jupyterLab-tutorial)

**Comment by jasongrout** [comment]
After that, I think it would be looking at the current notebook extension in https://github.com/jupyterlab/jupyterlab/tree/master/packages and seeing how to override the existing classes to do what you want.

**Comment by KedoKudo** [comment]
Thanks for providing the materials 😄
I will look through these tutorials and try to build one for our special case.  As for this issue, I will close it for now unless others would like this feature to be implemented into Jupyter as well.
