### ISSUE TITLE
File directory disappears with git-extension

### ISSUE THREAD

**Issue by ianpdavies** [jupyterlab/jupyterlab#7204]
## Description
The file directory in jupyter lab has disappeared. Although I am still able to click in the white space and open up the folders that should be there, the directory text allowing me to navigate is missing. This occurred shortly after I installed the git extension in a conda env, but does not occur in my base env without the git extension. This occurs with v1.0.2.

![image](https://user-images.githubusercontent.com/24301849/64892012-3b186080-d628-11e9-8eae-9d145e577dfa.png)

## Expected behavior
When I fresh installed Anaconda yesterday, I was able to navigate the folders. 

## Context

- Operating System and version: Windows 10 (64-bit)
- Browser and version: Chrome 76.0.3809.132
- JupyterLab version: 1.0.2

<details><summary>Command Line Output</summary>
<pre>
(thesis) C:\Users\ipdavies\CPR>jupyter lab --debug
[D 13:16:49.017 LabApp] Searching ['C:\\Users\\ipdavies\\CPR', 'C:\\Users\\ipdavies\\.jupyter', 'C:\\Users\\ipdavies\\AppData\\Local\\Continuum\\anaconda3\\envs\\thesis\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 13:16:49.017 LabApp] Looking for jupyter_config in C:\ProgramData\jupyter
[D 13:16:49.018 LabApp] Looking for jupyter_config in C:\Users\ipdavies\AppData\Local\Continuum\anaconda3\envs\thesis\etc\jupyter
[D 13:16:49.019 LabApp] Looking for jupyter_config in C:\Users\ipdavies\.jupyter
[D 13:16:49.019 LabApp] Looking for jupyter_config in C:\Users\ipdavies\CPR
[D 13:16:49.023 LabApp] Looking for jupyter_notebook_config in C:\ProgramData\jupyter
[D 13:16:49.023 LabApp] Looking for jupyter_notebook_config in C:\Users\ipdavies\AppData\Local\Continuum\anaconda3\envs\thesis\etc\jupyter
[D 13:16:49.025 LabApp] Loaded config file: C:\Users\ipdavies\AppData\Local\Continuum\anaconda3\envs\thesis\etc\jupyter\jupyter_notebook_config.json
[D 13:16:49.025 LabApp] Looking for jupyter_notebook_config in C:\Users\ipdavies\.jupyter
[D 13:16:49.027 LabApp] Loaded config file: C:\Users\ipdavies\.jupyter\jupyter_notebook_config.json
[D 13:16:49.037 LabApp] Looking for jupyter_notebook_config in C:\Users\ipdavies\CPR
[D 13:16:49.048 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\ProgramData\jupyter\jupyter_notebook_config.json
[D 13:16:49.049 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\ipdavies\AppData\Local\Continuum\anaconda3\envs\thesis\etc\jupyter\jupyter_notebook_config.d\jupyterlab.json
        C:\Users\ipdavies\AppData\Local\Continuum\anaconda3\envs\thesis\etc\jupyter\jupyter_notebook_config.d\nbdime.json
        C:\Users\ipdavies\AppData\Local\Continuum\anaconda3\envs\thesis\etc\jupyter\jupyter_notebook_config.json
[D 13:16:49.052 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\ipdavies\.jupyter\jupyter_notebook_config.json
[I 13:16:49.780 LabApp] JupyterLab extension loaded from C:\Users\ipdavies\AppData\Local\Continuum\anaconda3\envs\thesis\lib\site-packages\jupyterlab
[I 13:16:49.781 LabApp] JupyterLab application directory is C:\Users\ipdavies\AppData\Local\Continuum\anaconda3\envs\thesis\share\jupyter\lab
[D 13:16:50.469 LabApp] Using default logger
[D 13:16:50.469 LabApp] Using default logger
[D 13:16:50.471 LabApp] Using default logger
[D 13:16:50.472 LabApp] Using default logger
[I 13:16:50.480 LabApp] Serving notebooks from local directory: C:\Users\ipdavies\CPR
[I 13:16:50.480 LabApp] The Jupyter Notebook is running at:
[I 13:16:50.482 LabApp] http://localhost:8888/?token=e2c604140609cceddf68a5eacda88f1392205f5cb485b6fe
[I 13:16:50.483 LabApp]  or http://127.0.0.1:8888/?token=e2c604140609cceddf68a5eacda88f1392205f5cb485b6fe
[I 13:16:50.484 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:16:50.669 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/ipdavies/AppData/Roaming/jupyter/runtime/nbserver-6556-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=e2c604140609cceddf68a5eacda88f1392205f5cb485b6fe
     or http://127.0.0.1:8888/?token=e2c604140609cceddf68a5eacda88f1392205f5cb485b6fe
[D 13:16:51.992 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:51.997 LabApp] Using contents: services/contents
[D 13:16:52.008 LabApp] 200 GET /lab?token=e2c604140609cceddf68a5eacda88f1392205f5cb485b6fe (::1) 17.03ms
[D 13:16:52.065 LabApp] Path vendors~main.a4e248898b0dd6a33caa.js served from C:\Users\ipdavies\AppData\Local\Continuum\anaconda3\envs\thesis\share\jupyter\lab\static\vendors~main.a4e248898b0dd6a33caa.js
[D 13:16:52.091 LabApp] Path main.1778448d3a8acef0b675.js served from C:\Users\ipdavies\AppData\Local\Continuum\anaconda3\envs\thesis\share\jupyter\lab\static\main.1778448d3a8acef0b675.js
[D 13:16:52.094 LabApp] 304 GET /static/lab/main.1778448d3a8acef0b675.js (::1) 5.00ms
[D 13:16:53.163 LabApp] 200 GET /static/lab/vendors~main.a4e248898b0dd6a33caa.js (::1) 1100.15ms
[D 13:16:54.688 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:54.700 LabApp] 200 GET /api/sessions?1568405814679 (::1) 13.50ms
[D 13:16:54.705 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:54.719 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:54.723 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:54.730 LabApp] 200 GET /api/terminals?1568405814687 (::1) 25.50ms
[D 13:16:54.860 LabApp] 200 GET /lab/api/settings/?1568405814703 (::1) 141.51ms
[D 13:16:54.878 LabApp] Found kernel python3 in C:\Users\ipdavies\AppData\Roaming\jupyter\kernels
[D 13:16:54.878 LabApp] Found kernel tf2 in C:\Users\ipdavies\AppData\Roaming\jupyter\kernels
[D 13:16:54.878 LabApp] Found kernel thesis in C:\Users\ipdavies\AppData\Roaming\jupyter\kernels
[D 13:16:54.894 LabApp] 200 GET /api/kernelspecs?1568405814682 (::1) 172.51ms
[D 13:16:54.905 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:54.916 LabApp] 200 GET /api/terminals?1568405814897 (::1) 11.01ms
[D 13:16:55.197 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:55.199 LabApp] 200 GET /api/sessions?1568405815191 (::1) 2.50ms
[D 13:16:55.202 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:55.204 LabApp] Found kernel python3 in C:\Users\ipdavies\AppData\Roaming\jupyter\kernels
[D 13:16:55.204 LabApp] Found kernel tf2 in C:\Users\ipdavies\AppData\Roaming\jupyter\kernels
[D 13:16:55.206 LabApp] Found kernel thesis in C:\Users\ipdavies\AppData\Roaming\jupyter\kernels
[D 13:16:55.215 LabApp] 200 GET /api/kernelspecs?1568405815193 (::1) 13.50ms
[D 13:16:55.217 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:55.241 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:55.422 LabApp] Node v12.8.1

[D 13:16:56.261 LabApp] 200 POST /git/all_history?1568405815234 (::1) 1020.54ms
[I 13:16:56.264 LabApp] Build is up to date
[D 13:16:56.268 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:56.271 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:56.273 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:56.279 LabApp] 200 GET /lab/api/build?1568405815198 (::1) 1063.04ms
[D 13:16:56.281 LabApp] 200 GET /api/sessions?1568405815457 (::1) 13.50ms
[D 13:16:56.800 LabApp] 200 GET /api/nbconvert?1568405815333 (::1) 530.51ms
[D 13:16:56.807 LabApp] 200 GET /metrics?1568405815403 (::1) 535.00ms
[D 13:16:56.808 LabApp] Path @jupyterlab\theme-dark-extension\index.css served from C:\Users\ipdavies\AppData\Local\Continuum\anaconda3\envs\thesis\share\jupyter\lab\themes\@jupyterlab\theme-dark-extension\index.css
[D 13:16:56.811 LabApp] 304 GET /lab/api/themes/@jupyterlab/theme-dark-extension/index.css (::1) 534.00ms
[D 13:16:56.813 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:57.192 LabApp] 200 GET /api/nbconvert?1568405815255 (::1) 380.27ms
[D 13:16:57.194 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:57.198 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:57.202 LabApp] 200 GET /lab/api/workspaces/lab?1568405815505 (::1) 8.00ms
[D 13:16:57.224 LabApp] 200 GET /api/contents/?content=1&1568405815614 (::1) 26.49ms
[D 13:16:57.231 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:57.248 LabApp] 200 GET /api/contents/?1568405817223 (::1) 18.00ms
[D 13:16:57.355 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:57.374 LabApp] 200 GET /api/contents/?content=1&1568405817347 (::1) 20.00ms
[D 13:16:57.980 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:57.985 LabApp] 204 PUT /lab/api/workspaces/lab?1568405817974 (::1) 6.00ms
[D 13:16:58.292 LabApp] Accepting token-authenticated connection from ::1
[D 13:16:58.302 LabApp] 200 GET /metrics?1568405818287 (::1) 10.01ms
[D 13:17:03.120 LabApp] Accepting token-authenticated connection from ::1
[D 13:17:03.132 LabApp] 200 GET /metrics?1568405823114 (::1) 12.50ms
[D 13:17:05.353 LabApp] Accepting token-authenticated connection from ::1
[D 13:17:05.354 LabApp] 200 GET /api/terminals?1568405825347 (::1) 1.50ms
[D 13:17:05.657 LabApp] Accepting token-authenticated connection from ::1
[D 13:17:05.658 LabApp] 200 GET /api/sessions?1568405825651 (::1) 1.97ms
[D 13:17:07.353 LabApp] Accepting token-authenticated connection from ::1
[D 13:17:07.368 LabApp] 200 GET /api/contents/?content=1&1568405827347 (::1) 14.50ms
</pre>
</details>

**Comment by ianpdavies** [comment]
The issue is fixed after updating to v1.1.3 - should have tried that before posting!

**Comment by jasongrout** [comment]
Yes, and we are tracking this issue for 1.0.2 in another issue.
