### ISSUE TITLE
Search using search bar is very slow

### ISSUE THREAD

**Issue by Dovermore** [jupyterlab/jupyterlab#7209]
Whenever I try to use the built-in search bar, it will take more than 2 seconds to start the search. Let alone changing the search query.

It is EXTREMELY slow to search with the builtin search bar. Is this a known issue or am I the only one experiencing it.

I am using mbp2018 model 8 core CPU with 32G ram and Chrome. So I think system resource won't be the constraint factor.

Thx

**Comment by telamonian** [comment]
Improvements to search were made in Jlab `1.0.3` (#6824). If your version of Jlab is older than `1.0.3`, you can speed up your search by just upgrading to the latest version.

**Comment by Dovermore** [comment]
Solved thanks! Closing issue
