### ISSUE TITLE
Help does not work correctly with literal values

### ISSUE THREAD

**Issue by BrenBarn** [jupyterlab/jupyterlab#7210]
## Description

When using the `?` and `??` commands, the Shift-Tab help popup, and the "contextual help" (Ctrl-I), help is not correctly shown for literal values such as strings, lists, etc.  To get the help, you have to use the name of the type itself, not an instance.

## Reproduce

For comparison, create a variable containing an empty string: `x = ''`.

Type `?x`.  You get the help for string type.  Type `?str`.  You get the same.  Type `?x.upper`.  You get the help for the string method.  Type `?str.upper`.  You get the same.  Same for `??` and contextual help.

Now type `?''`.  You get ```Object `''` not found.```  Same for `?''.upper`.  Same for `??` and same for contextual help.

Same behavior if you do `x = []`, `x = {}`, etc.

The problem appears to exist in regular Jupyter Notebook as well, so I guess it's not really a Jupyterlab-specific issue but I wasn't sure whether to raise it there or here (or somewhere else).

## Expected behavior

You should be able to get help on literal values (and their methods/attributes) in the same way you can get help on any other values.  This is the way the built-in `help` function works  (e.g., `help('')` correctly shows the help for `str`).  It is useful to be able to get help on things like string methods, especially for beginners.

## Context

- Operating System and version: Windows 7
- Browser and version: Vivaldi 2.4
- JupyterLab version: 1.0.2

**Comment by jasongrout** [comment]
The completion is a function of the kernel, not Jupyter notebook or JupyterLab. Notebook and Lab are just displaying what the kernel gives it. I think the proper place to file this issue is in the [ipython repo](https://github.com/ipython/ipython/).

**Comment by BrenBarn** [comment]
By "completion" do you mean "help"?  I'm not asking about autocompletion here, only about the displayed help.

**Comment by jasongrout** [comment]
Thanks, you're right that I was not using the right term. I meant "introspection" instead of completion, as we define it in our messaging spec to the kernel: https://jupyter-client.readthedocs.io/en/stable/messaging.html#introspection. I should have said: 

"The introspection/help is a function of the kernel, not Jupyter notebook or JupyterLab. Notebook and Lab are just displaying what the kernel gives it. I think the proper place to file this issue is in the ipython repo."

**Comment by jasongrout** [comment]
Closing this since it is being tracked in https://github.com/ipython/ipython/issues/6323
