### ISSUE TITLE
can not install extention

### ISSUE THREAD

**Issue by kennyworld** [jupyterlab/jupyterlab#7211]
## Description

when installed extension , errors occured as following:
```shell
jupyter labextension install jupyterlab-drawio

An error occured.
NameError: name 'CoreConfig' is not defined
See the log file for details:  C:\Users\LIUJIA~1\AppData\Local\Temp\jupyterlab-debug-w0f3orce.log
```

Here are contexts in log file:
```python
Traceback (most recent call last):

  File "c:\runtime\python\python3\lib\site-packages\jupyterlab\commands.py", line 1657, in _node_check
    output = subprocess.check_output([node, 'node-version-check.js'], cwd=HERE)

  File "c:\runtime\python\python3\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout

  File "c:\runtime\python\python3\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['c:\\runtime\\nodejs\\node.EXE', 'node-version-check.js']' returned non-zero exit status 1.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\runtime\python\python3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "c:\runtime\python\python3\lib\site-packages\jupyterlab\labextensions.py", line 93, in start
    ans = self.run_task()

  File "c:\runtime\python\python3\lib\site-packages\jupyterlab\labextensions.py", line 147, in run_task
    for i, arg in enumerate(self.extra_args)

  File "c:\runtime\python\python3\lib\site-packages\jupyterlab\labextensions.py", line 147, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "c:\runtime\python\python3\lib\site-packages\jupyterlab\commands.py", line 319, in install_extension
    _node_check(logger)

  File "c:\runtime\python\python3\lib\site-packages\jupyterlab\commands.py", line 1660, in _node_check
    data = CoreConfig()._data

NameError: name 'CoreConfig' is not defined

Exiting application: jupyter
```
package version info as following:
```txt
$ pip3 list
Package            Version
------------------ ---------
attrs              19.1.0
backcall           0.1.0
beautifulsoup4     4.7.1
bleach             3.1.0
bs4                0.0.1
certifi            2019.6.16
chardet            3.0.4
colorama           0.4.1
cycler             0.10.0
decorator          4.4.0
defusedxml         0.6.0
entrypoints        0.3
h5py               2.10.0
idna               2.8
imageio            2.5.0
ipykernel          5.1.1
ipython            7.7.0
ipython-genutils   0.2.0
ipywidgets         7.5.1
jedi               0.14.1
Jinja2             2.10.1
json5              0.8.5
jsonschema         3.0.1
jupyter-client     5.3.2
jupyter-core       4.5.0
jupyterlab         1.1.3
jupyterlab-server  1.0.6
kiwisolver         1.1.0
lxml               4.3.4
MarkupSafe         1.1.1
matplotlib         3.1.1
mistune            0.8.4
nbconvert          5.6.0
nbformat           4.4.0
networkx           2.3
nodejs             0.1.1
notebook           6.0.1
numpy              1.17.1
optional-django    0.1.0
pandocfilters      1.4.2
parso              0.5.1
pickleshare        0.7.5
Pillow             6.1.0
pip                19.2.3
prometheus-client  0.7.1
prompt-toolkit     2.0.9
Pygments           2.4.2
pyparsing          2.4.2
pyrsistent         0.15.4
python-dateutil    2.8.0
PyWavelets         1.0.3
pywin32            225
pywinpty           0.5.5
pyzmq              18.0.2
requests           2.22.0
scikit-image       0.15.0
scipy              1.3.1
Send2Trash         1.5.0
setuptools         40.8.0
six                1.12.0
soupsieve          1.9.2
terminado          0.8.2
testpath           0.4.2
tornado            6.0.3
traitlets          4.3.2
urllib3            1.25.3
virtualenv         16.6.1
wcwidth            0.1.7
webencodings       0.5.1
widgetsnbextension 3.5.1
xlrd               1.2.0
xlwt               1.3.0
```

**Comment by vidartf** [comment]
Thanks for the report! Would you mind including the full contents of the debug file? Some relevant entries seem to be missing. You can enclose it in the following to ensure that it is collapsible:

```html
<details><summary>Content of debug log</summary>
<pre>
Paste content here ...
</pre>
</details>
```

It will look like this:
<details><summary>Content of debug log</summary>
<pre>
Paste content here ...
</pre>
</details>

**Comment by jaipreet-s** [comment]
> subprocess.CalledProcessError: Command '['c:\\runtime\\nodejs\\node.EXE', 'node-version-check.js']' returned non-zero exit status 1.

This is the relevant part of the log.

I was able to resolve this by installing/updating `nodejs` 

```
conda install nodejs -c conda-forge
```

**Comment by Freedomisgood** [comment]
there is something wrong when i input  `jupyter lab build` or `jupyter labextension install @jupyterlab/github `. *Ubuntu 16.04, python3.5*
<details><summary>Log</summary>
<pre>
System: Ubuntu 16.04
When I run the installation
jupyter labextension install jupyterlab-spreadsheet
in my Python 3.5.2 virtualenv I get the error:

An error occured. NameError: name 'CoreConfig' is not defined See the log file for details: /tmp/jupyterlab-debug-05zbv00j.log

The log in that location outputs

Traceback (most recent call last):

File "/home/skyler/Documents/NN/tf/lib/python3.5/site-packages/jupyterlab/commands.py", line 1657, in _node_check
output = subprocess.check_output([node, 'node-version-check.js'], cwd=HERE)

File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
**kwargs).stdout

File "/usr/lib/python3.5/subprocess.py", line 708, in run
output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['/usr/bin/nodejs', 'node-version-check.js']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/home/skyler/Documents/NN/tf/lib/python3.5/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
yield

File "/home/skyler/Documents/NN/tf/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 93, in start
ans = self.run_task()

File "/home/skyler/Documents/NN/tf/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 147, in run_task
for i, arg in enumerate(self.extra_args)

File "/home/skyler/Documents/NN/tf/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 147, in
for i, arg in enumerate(self.extra_args)

File "/home/skyler/Documents/NN/tf/lib/python3.5/site-packages/jupyterlab/commands.py", line 319, in install_extension
_node_check(logger)

File "/home/skyler/Documents/NN/tf/lib/python3.5/site-packages/jupyterlab/commands.py", line 1660, in _node_check
data = CoreConfig()._data

NameError: name 'CoreConfig' is not defined

Exiting application: jupyter
</pre>
</details>


<details><summary>package version info as following:</summary>
<pre>
Package                       Version               
----------------------------- ----------------------
apturl                        0.5.2                 
attrs                         19.1.0                
backcall                      0.1.0                 
beautifulsoup4                4.4.1                 
bleach                        3.1.0                 
blinker                       1.3                   
Brlapi                        0.6.4                 
catfish                       1.4.2                 
chardet                       2.3.0                 
checkbox-support              0.22                  
command-not-found             0.3                   
cryptography                  1.2.3                 
cycler                        0.10.0                
decorator                     4.4.0                 
defer                         1.0.6                 
defusedxml                    0.6.0                 
entrypoints                   0.3                   
feedparser                    5.1.3                 
future                        0.17.1                
guacamole                     0.9.2                 
html5lib                      0.999                 
httplib2                      0.9.1                 
idna                          2.0                   
ipykernel                     5.1.2                 
ipython                       7.8.0                 
ipython-genutils              0.2.0                 
ipywidgets                    7.5.1                 
jedi                          0.15.1                
Jinja2                        2.10.1                
joblib                        0.13.2                
json5                         0.8.5                 
jsonschema                    3.0.2                 
jupyter                       1.0.0                 
jupyter-client                5.3.3                 
jupyter-console               6.0.0                 
jupyter-core                  4.5.0                 
jupyterlab                    1.1.4                 
jupyterlab-server             1.0.6                 
Keras-Applications            1.0.6                 
Keras-Preprocessing           1.0.5                 
kiwisolver                    1.0.1                 
language-selector             0.1                   
lightdm-gtk-greeter-settings  1.2.1                 
louis                         2.6.4                 
lxml                          3.5.0                 
Mako                          1.0.3                 
MarkupSafe                    1.1.1                 
matplotlib                    3.0.2                 
menulibre                     2.1.3                 
mistune                       0.8.4                 
mock                          3.0.5                 
mugshot                       0.3.1                 
nbconvert                     5.6.0                 
nbformat                      4.4.0                 
notebook                      6.0.1                 
numpy                         1.17.2                
oauthlib                      1.0.3                 
onboard                       1.2.0                 
padme                         1.1.1                 
pandocfilters                 1.4.2                 
parso                         0.5.1                 
passlib                       1.7.1                 
pexpect                       4.7.0                 
pickleshare                   0.7.5                 
Pillow                        3.1.2                 
pip                           19.2.3                
plainbox                      0.25                  
prometheus-client             0.7.1                 
prompt-toolkit                2.0.9                 
psutil                        3.4.2                 
ptyprocess                    0.6.0                 
pyasn1                        0.1.9                 
pycups                        1.9.73                
pycurl                        7.43.0                
Pygments                      2.4.2                 
pygobject                     3.20.0                
PyJWT                         1.3.0                 
pyparsing                     2.0.3                 
pyrsistent                    0.15.4                
python-apt                    1.1.0b1+ubuntu0.16.4.5
python-dateutil               2.8.0                 
python-debian                 0.1.27                
python-systemd                231                   
pyxdg                         0.25                  
pyzmq                         18.1.0                
qtconsole                     4.5.5                 
reportlab                     3.3.0                 
requests                      2.9.1                 
scikit-learn                  0.21.3                
scipy                         1.3.1                 
screen-resolution-extra       0.0.0                 
Send2Trash                    1.5.0                 
sessioninstaller              0.0.0                 
setuptools                    41.2.0                
six                           1.12.0                
ssh-import-id                 5.5                   
system-service                0.3                   
terminado                     0.8.2                 
testpath                      0.4.2                 
tornado                       6.0.3                 
traitlets                     4.3.2                 
ubuntu-drivers-common         0.0.0                 
ufw                           0.35                  
unattended-upgrades           0.1                   
unity-scope-calculator        0.1                   
unity-scope-chromiumbookmarks 0.1                   
unity-scope-colourlovers      0.1                   
unity-scope-devhelp           0.1                   
unity-scope-firefoxbookmarks  0.1                   
unity-scope-gdrive            0.7                   
unity-scope-manpages          0.1                   
unity-scope-openclipart       0.1                   
unity-scope-texdoc            0.1                   
unity-scope-tomboy            0.1                   
unity-scope-virtualbox        0.1                   
unity-scope-yelp              0.1                   
unity-scope-zotero            0.1                   
urllib3                       1.13.1                
usb-creator                   0.3.0                 
virtualenv                    15.0.1                
wcwidth                       0.1.7                 
webencodings                  0.5.1                 
wheel                         0.33.6                
widgetsnbextension            3.5.1                 
xdiagnose                     3.8.4.1               
xkit                          0.0.0                 
XlsxWriter                    0.7.3
</pre>
</details>

```
$ jupyter labextension list
JupyterLab v1.1.4
No installed extensions
```

**Comment by Freedomisgood** [comment]
I have known why I failed, I solve the problem when I update nodejs...My nodejs is v4.2.6, everything is ok when i upgrade to v10.16.3...
Solved!
