### ISSUE TITLE
Setting up jest for custom extensions

### ISSUE THREAD

**Issue by remborg** [jupyterlab/jupyterlab#7212]
## Description

I've had a hard time setting up jest to test my extension using the documentation. 
At the end I managed to get it to work by adding this line in the jest.config.js file:

    setupFiles: ['@jupyterlab/testutils/lib/jest-shim.js'],

This loads some shims and fixes the common react error `ReferenceError: fetch is not defined`.

As this line references the @jupyterlab/testutils package, is this something we should use?
If so, I'm happy to update the documentation with this line.

-- 
For reference, if it can help somebody, here is my full jest.config.js file 
```
module.exports = {
    preset: 'ts-jest/presets/js-with-babel',
    setupFiles: ['@jupyterlab/testutils/lib/jest-shim.js'],
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
    reporters: ['default', 'jest-junit'],
    coverageReporters: ['json', 'lcov', 'text', 'html'],
    globals: {
        'ts-jest': {
            tsConfig: `./tsconfig.json`
        }
    },
    transformIgnorePatterns: ['/node_modules/(?!(@jupyterlab/.*)/)']
};
```

**Comment by jaipreet-s** [comment]
The jupyterlab-git extension uses jest for frontend tests- Checkout the `jest` config for that here https://github.com/jupyterlab/jupyterlab-git/blob/master/setupJest.js

**Comment by remborg** [comment]
Thank you @jaipreet-s this is useful
