### ISSUE TITLE
How to hide the sidebar and move the editor to the center?

### ISSUE THREAD

**Issue by Yura52** [jupyterlab/jupyterlab#7213]
Hi! For me it feels unnatural when the editor is moved to the left. Honestly, the only reason why I still use Jupyter (not JupyterLab) is that the editor is placed at the center. Is it possible to do the same in JupyterLab?

**Comment by jasongrout** [comment]
Can you upload an annotated screenshot explaining what you would like it to look like?

**Comment by jasongrout** [comment]
Possibly related to https://github.com/jupyterlab/jupyterlab/issues/600

**Comment by jasongrout** [comment]
Closing as there was no followup.
