### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Deepak-Khandelwal** [jupyterlab/jupyterlab#7220]
Facing issue every time during convert a notebook into pdf.

"The server returned an invalid or incomplete response."

**Comment by jasongrout** [comment]
Does it work in the classic notebook, if you launch the classic notebook from the JLab Help menu?

**Comment by jasongrout** [comment]
Can you give more information about your setup? See https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html for more information and things you could try that would make it possible to help you more specifically.

**Comment by Deepak-Khandelwal** [comment]
Yes! it works on classic notebook. But in classic notebook i can't export the notebook into pdf . 
May be when i am trying to export the notebook into pdf, your container getting spin off so that it's giving "502 bad gateway".

**Comment by jasongrout** [comment]
Did you figure out how to resolve the issue? If so, can you share so others can benefit?

**Comment by Deepak-Khandelwal** [comment]
I'm not aware about your infrastructure but few things you need to figure out:

1. Check logs of the container (docker logs "Container-ID").
2. If your container is running into Docker swarm or kubernetes then check the workload and allocate the memory to the specific container.
3. Check your proxy server configuration.
