### ISSUE TITLE
File names not visible in Files Tab browser

### ISSUE THREAD

**Issue by amashal** [jupyterlab/jupyterlab#7221]
Has anyone had this issue where your file names are not visible? Any suggestions on how to solve this problem? Please see image attached.

![jupyterlab_issue](https://user-images.githubusercontent.com/8277951/65048099-93ee3e80-d931-11e9-8cf7-7e31c1c0e280.PNG)

**Comment by jasongrout** [comment]
This is a known issue with 1.0.1 through 1.0.6 conflicting with recent releases. We'll be hopefully making a release tomorrow fixing this issue. In the meantime, you can upgrade to jlab 1.0.10 or 1.1.3 (preferable) to fix it as well.

**Comment by amashal** [comment]
Thank you, the upgrade resolved it.
