### ISSUE TITLE
After installing an extension, the list of files disappears

### ISSUE THREAD

**Issue by euanmacinnes** [jupyterlab/jupyterlab#7223]
I installed the @jupyterlab/celltags v0.1.5 extension to be able to pass parameters via papermill, and while the lab restarts, and there's no errors in the jupyterlab rebuild, upon restarting the service the files all "disappear" from the file browser. Inspecting the html shows that the list is generated, and double clicking does open the file, but the filenames (and icons) are missing from the list.

I then uninstalled the extension, rebuilt the lab (using jupyter lab build), and the files are still visibly missing from the file browser. Swapping back to JupyterHub Classic, and the files all appear, so something's broke somewhere inside JupyterLab. 

Any ideas where/what to check?

jupyterlab 1.0.4 on Ubuntu 18.04. Result of jupyter labextension list
        @jupyter-voila/jupyterlab-preview v0.1.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v1.0.2  enabled  OK
        @jupyterlab/git v0.8.1  enabled  OK
        @jupyterlab/toc v1.0.1  enabled  OK
        @lckr/jupyterlab_variableinspector v0.3.0  enabled  OK
        ipysheet v0.4.3  enabled  OK
        jupyter-matplotlib v0.4.2  enabled  OK
        jupyterlab-gitlab v0.3.0  enabled  OK
        jupyterlab-jupytext v1.0.2  enabled  OK
        jupyterlab-plotly v1.1.0  enabled  OK
        jupyterlab-python-file v0.3.0  enabled  OK
        jupyterlab-spreadsheet v0.1.0  enabled  OK
        jupyterlab-sql v0.3.0  enabled  OK
        jupyterlab_bokeh v1.0.0  enabled  OK
        plotlywidget v1.1.0  enabled  OK

**Comment by telamonian** [comment]
The issue has already been dealt with in #7192. If you wait a day or two for the next release, you can fix your issue by doing a clean build:

```
jupyter lab clean
jupyter lab build
```

You can also skip the wait by upgrading to the latest Jlab (`v1.1.3`). You'll still probably need to do the clean build.

**Comment by telamonian** [comment]
The changes from #7192 have now been released in `v1.1.4`. If you do a clean build now, the updated package with the fix for your problem should automatically get pulled into your Jlab install.

**Comment by euanmacinnes** [comment]
Thanks! I actually did a clean build after an update to 1.1.3, and that solved the issue in Jlab.
