### ISSUE TITLE
"Switch Sidebar Side" context menu item doesn't work if you right click on the sidebar tab's icon

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#7224]
If you right click on a sidebar tab and then select "Switch Sidebar Side", it won't work if you happened have right clicked on the tab icon. I'm pretty sure this broke because the icon is now a svg child node, instead of just a background image.

**Comment by jasongrout** [comment]
Yep, that was the problem. Fix coming up.
