### ISSUE TITLE
CI check that ensures PRs are not making changes to jupyterlab/staging

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7237]
The `jupyterlab/staging` directory is only modified at publish time by the release script. We should have a CI check on PRs making sure that no PRs are modifying the staging directory.

**Comment by jasongrout** [comment]
I suppose changing the staging/yarn.js file is something done in a PR, so maybe we just whitelist a few specific files allowed to change in a PR.

**Comment by jtpio** [comment]
Maybe this action triggered on `pull_request` only could work? https://github.com/tj-actions/changed-files

**Comment by galathinius** [comment]
Hi @jasongrout I'd like to try working on this issue, could you please tell me which files would need to be whitelisted?

**Comment by jtpio** [comment]
Thanks @galathinius!

> which files would need to be whitelisted

Maybe we can start with `jupyterlab/staging/yarn.js`? https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/staging/yarn.js
Ideally this list can be configured easily, so we could add more files to it if needed, for example: https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/staging/.yarnrc

**Comment by galathinius** [comment]
I just opened a pr with my implementation, new files could be added in the workflow yaml. 
Or the list of files could be written to a separate file and read from there
