### ISSUE TITLE
Folder-wide search

### ISSUE THREAD

**Issue by mocquin** [jupyterlab/jupyterlab#7239]
Hello there,

Is there any folder-wide search feature in Jlab ? Maybe an extension ?
I'd love to be able to search text among multiple documents in a folder tree, among notebooks, text-files, etc. Kinda like Google Desktop or Mac's Spotlight, but integrated in the Jlab GUI.

**Comment by jasongrout** [comment]
No, not yet. That would be a great extension to have! Help is welcome. It would require a server-side component to do the actual searching on disk, as well as a frontend component to act as a ux.

**Comment by jasongrout** [comment]
This issue is being tracked at #1145. Let's move discussion there.
