### ISSUE TITLE
Run CI on PRs to branches

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7244]
Currently we are not running CI when we merge to a branch, for example when backporting. As we backport more and more, it is important for us to run CI on such PRs.

**Comment by jtpio** [comment]
Closing as this is now the case, for example when backporting to the `3.2.x` branch: 

https://github.com/jupyterlab/jupyterlab/blob/8b26ce7945927462c1b88a6a8b2f96f5e421f830/.github/workflows/linuxjs-tests.yml#L4-L5
