### ISSUE TITLE
reverting a notebook that does not have focus causes it to render strangely

### ISSUE THREAD

**Issue by hhuuggoo** [jupyterlab/jupyterlab#7245]
I'm working on an extension, and part of this extension has to revert notebooks that don't have focus.  Calling `context.revert` on the un-focused notebook causes it to render strangely

![image](https://user-images.githubusercontent.com/249407/65273170-8b8f3280-daee-11e9-80ea-5b0c470a7566.png)

Could I focus the widget before calling revert?  I attempted to do so, however I think there is to wait on the widget activation?

I was discussing this with @saulshanabrook 

This can be demonstrated by the following code which attempts to activate and revert each widget 

```
function revert(dm:IDocumentManager, shell:ILabShell, filesDict:any){
  let current_id:string = null;
  let widgets:any[] = [];
  let current:number = 0;

  if (shell && shell.currentWidget && shell.currentWidget.id){
    current_id = shell.currentWidget.id;
  }

  each(shell.widgets('main'), widget => {
    widgets.push(widget);
  });

  function go():void{
    if (current >= widgets.length){
      if (current_id){
        shell.activateById(current_id);
      }
      return;
    }
    const widget = widgets[current];
    const context = dm.contextForWidget(widget);
    if (context){
      if (!filesDict || filesDict[context.path]){
        shell.activateById(widget.id);
        context.revert();
      }
    }


    current++;
    setTimeout(go, 0);
  }
  go();
}
```

If I set the timeout to 1 second, I get the following behavior (each tab reverts, and renders without issue)

https://www.youtube.com/watch?v=e1WTo7gppYg&feature=youtu.be

However if I set the timeout to 0, each tab reverts, and when I go back to the notebook tab, the code cells are blank, until I click on them.

https://www.youtube.com/watch?v=lzeJE2gvq5M&feature=youtu.be

**Comment by hhuuggoo** [comment]
Turns out revert() returns a promise. waiting on that (using then), then it works!  Thanks @ahlaw 

```
function go():void{
    if (current >= widgets.length){
      if (current_id){
        shell.activateById(current_id);
      }
      return;
    }
    const widget = widgets[current];
    const context = dm.contextForWidget(widget);
    if (context && (!filesDict || filesDict[context.path])) {
      shell.activateById(widget.id);
      context.revert().then(() => {
        current++;
        go();
      });
    } else {
      current++;
      go();
    }
  }
  go();
````

**Comment by jasongrout** [comment]
Or you can probably use async/await, which may read more elegantly than `.then()`.
