### ISSUE TITLE
Allow overlapping StateDB namespaces

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#7257]
## Description

In StateDB, when filtering state based on the namespace, it only checks that the stored value *starts* with the namespace, not that the namespace matches exactly:

https://github.com/jupyterlab/jupyterlab/blob/d42744013f7793a5e001923fae34cbdcede063f0/packages/coreutils/src/statedb.ts#L298

## Reproduce

When using two widget trackers with namespaces `myplugin` and `myplugin-secondary`, all widgets from `myplugin-secondary` will try to be restored for `myplugin`, since they share a prefix.

## Expected behavior

The state for things with different namespaces are segregated.

## Proposed solution

Since ids are specified as `'namespace:identifier'`, `StateDB.Connector.list()` should split all keys on `:`, and check for strict equality to the namespace.

**Comment by jasongrout** [comment]
> Since ids are specified as `'namespace:identifier'`, `StateDB.Connector.list()` should split all keys on `:`, and check for strict equality to the namespace.

Is this an explicit requirement? I thought it was basically a convention, but not assumed or enforced.

**Comment by vidartf** [comment]
@jasongrout 
https://github.com/jupyterlab/jupyterlab/blob/d42744013f7793a5e001923fae34cbdcede063f0/packages/coreutils/src/statedb.ts#L73-L75

**Comment by jasongrout** [comment]
Thanks. That makes sense. Do you know if this is documented wherever such IDs are needed in our API?

**Comment by vidartf** [comment]
I've shared everything I know. Hoping that @afshin can chime in on some of those details since he touched the code last (and by the logic of all children, he now owns it).
