### ISSUE TITLE
ToolbarButtons with icons and labels not rendered correctly

### ISSUE THREAD

**Issue by mbektasbbg** [jupyterlab/jupyterlab#7265]
## Description
If a ToolbarButton is created with label and icon then icon and label are shown as separate rows that are centered, instead of shown as single row (label after the icon) as before.

<img width="304" alt="ToolbarButton" src="https://user-images.githubusercontent.com/40003442/65656454-eee8fb00-dfed-11e9-906a-366cf2e9121e.png">

## Reproduce
```
new ToolbarButton({
      iconClassName: 'jp-AddIcon',
      label: 'Add Timestamp',
     ...
});
```

It could be caused by changes in https://github.com/jupyterlab/jupyterlab/pull/7236

**Comment by jasongrout** [comment]
CC @telamonian 

What versions of js packages and jupyterlab do you have?

**Comment by mbektasbbg** [comment]
In sync with master. Most ^2.0.0-alpha.0. Tested using https://github.com/mbektasbbg/jupyterlab/commit/4171b71c1d8b9a24d48f95b51d5fe3605f975317

**Comment by telamonian** [comment]
@jasongrout  @mbektasbbg #7266 fixes this. Some extra SVG-specific styling was getting added to icons in the case where icon handling falls back to the old "icons as CSS background images" behavior.

Not coincidentally, the SVG styling for toolbar icon labels is also broken, so I'll fix that too in the same PR
