### ISSUE TITLE
apputils ReactWidget.render() override

### ISSUE THREAD

**Issue by jamesdbrock** [jupyterlab/jupyterlab#7281]
To override the abstract method `ReactWidget.render()`, we need to write a `render():ReactRenderElement`, but `ReactRenderElement` is not exported.

https://jupyterlab.readthedocs.io/en/latest/developer/virtualdom.html#react

**Comment by jamesdbrock** [comment]
Maybe we're not supposed to override the `render()` method, and instead call the static `ReactWidget.create()` method like this?

https://github.com/jupyterlab/jupyterlab-data-explorer/blob/f7ba324f7a688ccd474c028e26291644cf1101df/dataregistry-extension/src/explorer.tsx#L379

**Comment by jamesdbrock** [comment]
Ok yeah, we're not supposed to extend `ReactWidget`. Maybe that should be mentioned in the docs?

**Comment by jasongrout** [comment]
It looks to me like both the docs and the class definition support subclassing. It also looks like the type definition should be exported even just for the public api purposes - I'm a bit confused why typescript allows it to compile without exporting that type.
