### ISSUE TITLE
Failed to activate plugins after JupyterLab build

### ISSUE THREAD

**Issue by rabsr** [jupyterlab/jupyterlab#7283]
I have created a new conda environment and installed jupyter lab 1.0.0 version. I build the jupyter lab without doing any change and build succeeds. 
The file-browser extension is missing. Get the errors in console.

<img width="1278" alt="Screenshot 2019-09-30 at 8 11 10 PM" src="https://user-images.githubusercontent.com/8984978/65889290-a3a06500-e3be-11e9-9ac4-49cfad1a7b7e.png">

Versions:

- conda: 4.7.12/4.7.10
- pip: 9.0.1
- Jupyter Lab: 1.0.0

**Comment by jasongrout** [comment]
CC @telamonian 

As a workaround, you can probably update to JupyterLab 1.1.4, the latest released version.

**Comment by telamonian** [comment]
@rohit2618 Some more details about how you carried out the installation would be helpful to reproduce the bug. Exactly which commands did you use when installing Jupyterlab? Did you install any labextensions for Jupyterlab?

**Comment by telamonian** [comment]
For reference, the problem appears to be that 

A. The OP has a `<1.1` install of Jupyterlab
B. Somehow a `>=1.1` version of `filebrowser-extension` is getting pulled into the OP's install 
C. `filebrowser-extension` `>=1.1` has an implicit dependency on `ui-components-extension`, but the latter package was only added in `1.1`

**Comment by jasongrout** [comment]
So my guess is that it *does* pull in ui-components-extension as an npm package, but that it does *not* install ui-components-extension as a jupyterlab extension.

**Comment by jasongrout** [comment]
> Somehow a `>=1.1` version of `filebrowser-extension` is getting pulled into the OP's install

This will happen if they rebuild with JupyterLab 1.0.x for x<7, IIRC, and not for later x because of the pinning that we do then.

**Comment by rohit2618** [comment]
> @rohit2618 Some more details about how you carried out the installation would be helpful to reproduce the bug. Exactly which commands did you use when installing Jupyterlab? Did you install any labextensions for Jupyterlab?

@telamonian What's OP?

I am using the below steps to create my environment.

`conda create -n env_name python=3.5`
`conda activate env_name`
`pip install jupyterlab==1.0.0`
`conda install nodejs`

In jupyter lab staging, removed yarn.lock and ran `node yarn.js install`

Installing few of the custom lab extensions for Jupyter lab.

And, finally performed build
`jupyter lab build`

**Comment by jasongrout** [comment]
Do you have to use version 1.0.0 exactly? We've been releasing bugfixes, so you may want to upgrade to at least 1.0.10, if not 1.1.4 (the latest release). Either of these should fix the problem for you.

**Comment by telamonian** [comment]
@rohit2618 OP is "original poster" (ie you)

Okay, I figured you might be messing with `yarn.lock`. I can't think of any other way that a newer version of an extension package would get pulled in (since nothing depends on them directly). In general, you shouldn't delete `yarn.lock`. Doing so will force all dependencies to update to the absolute latest allowed by semver. Since we (the Jlab devs) haven't tested said updated dependencies, it's likely to cause you all kinds of problems.

Like @jasongrout said, the easiest way to fix your problem will be to use a newer version of jlab. Even if you still use `1.0.0`, if you do a new install (starting with a new conda env) but don't mess with `yarn.lock`, everything should work fine.

**Comment by rohit2618** [comment]
> Do you have to use version 1.0.0 exactly? We've been releasing bugfixes, so you may want to upgrade to at least 1.0.10, if not 1.1.4 (the latest release). Either of these should fix the problem for you.

Actually our lab extension does not support latest release i.e. 1.1.4. Moreover, they support 1.0.10 and it solves my problem.

@telamonian Got your point. It messed up by deleting yarn.lock. It's downloading latest of everything and thus causing issues.

Thanks a lot.

**Comment by jasongrout** [comment]
> Actually our lab extension does not support latest release i.e. 1.1.4.

1.1.4 *should* be backwards compatible with 1.0, which means that if an extension works in 1.0, it should work in 1.1.4. We'd be interested in hearing about any problems using a 1.0.0 extension with 1.1.4.
