### ISSUE TITLE
Jupyter Lab failed to build because of out of memory?

### ISSUE THREAD

**Issue by HurstSi** [jupyterlab/jupyterlab#7288]
There's a log that shows me maybe 'out of the memory' is the cause of the problem.
So I try to use this 'export NODE_OPTIONS=--max-old-space-size=4096' before building my jupyter lab. But the bug still, here's the log when I use the watch mode showed.
It's there any problems? Can someone help me with my cloud server on Vultr that has 1G RAM.
Thanks.

root@vultr:~# NODE_OPTIONS=--max-old-space-size=8192 jupyter lab --watch
[I 17:39:59.771 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.6/dist-packages/jupyterlab
[I 17:39:59.772 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab                                [I 17:39:59.772 LabApp] Starting JupyterLab watch mode...                                                               [I 17:40:07.450 LabApp] > node /usr/local/lib/python3.6/dist-packages/jupyterlab/staging/yarn.js run watch
yarn run v1.15.2                                                                                                        $ webpack --watch                                                                                                       
webpack is watching the files…

<--- Last few GCs --->

[3620:0x55a5679d5400]    62629 ms: Scavenge 307.1 (324.0) -> 305.1 (326.0) MB, 66.4 / 9.1 ms  allocation failure
[3620:0x55a5679d5400]    63412 ms: Scavenge 308.4 (326.0) -> 306.5 (334.0) MB, 37.3 / 3.9 ms  allocation failure
[3620:0x55a5679d5400]    70829 ms: Scavenge 313.7 (334.5) -> 309.6 (337.0) MB, 194.8 / 22.6 ms  allocation failure      [3620:0x55a5679d5400]    96337 ms: Scavenge 315.3 (337.0) -> 311.8 (327.5) MB, 404.2 / 15.9 ms  allocation failure      

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2d1a09098fe1 <JSObject>
    1: /* anonymous */ [/usr/local/share/jupyter/lab/staging/node_modules/acorn/dist/acorn.js:~2167] [pc=0x2e4bf5ca35b6](this=0x1388e15191d9 <Parser map = 0x1fa9ea62f229>,refDestructuringErrors=0x1388e1532459 <DestructuringErrors map = 0x1fa9ea629241>)
    2: /* anonymous */ [/usr/local/share/jupyter/lab/staging/node_modules/acorn/dist/acorn.js:~2047] [pc=0x2e4bf5cfc72e](this=0x1388e15191d9 <Par...

FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
 1: node::Abort() [/usr/bin/node]
 2: 0x55a566787011 [/usr/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/bin/node]
 5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node]    6: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 7: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/bin/node]
 8: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/bin/node]     9: 0x2e4bf58040bd
Aborted
error Command failed with exit code 134.                                                                                info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by timkpaine** [comment]
duplicate https://github.com/jupyterlab/jupyterlab/issues/7175
