### ISSUE TITLE
Error dialog for services' ResonseError should include explanation

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#7293]
Sometimes, the services API might return 4xx error codes. These are typically thrown as a [`ResponseError`](https://github.com/jupyterlab/jupyterlab/blob/5aa5927997fd8df01d6a02e99bf43b83fc279171/packages/services/src/serverconnection.ts#L145-L161), which is typically displayed using [`showErrorMessage()`](https://github.com/jupyterlab/jupyterlab/blob/5aa5927997fd8df01d6a02e99bf43b83fc279171/packages/apputils/src/dialog.ts#L42-L76).

Following the [RFC](https://tools.ietf.org/html/rfc7231#section-6.5) for 4xx errors (my emphasis added):

> Except when responding to a HEAD request, **the
   server SHOULD send a representation containing an explanation of the
   error situation**, and whether it is a temporary or permanent
   condition.  These status codes are applicable to any request method.
   **User agents SHOULD display any included representation to the user.**

Currently, we only display the status code + text, but not any included explanation for the error. This can lead to some rather opaque error messages (e.g. "Rename error: Invalid response: 400 Bad Request"), while the response actually includes some useful information (e.g. "File names cannot contain spaces"). Ideally, we should include the explanation if given.

## Possible solutions:
1) Read out the response body when creating the `ResponseError`, and include it in the error message.
2) The `ResponseError` currently includes the response as an attribute. This could be used by `showErrorMessage` to include the content in the error dialog.

I would vote for (2), as:
- The explanation is only accessible in an asynchronous way, which means (1) would need an API change.
- apputils (where `showErrorMessage` is defined) already has a dependency on services (where `ResponseError` is defined).

**Comment by vidartf** [comment]
Never mind, it just turns out you have to use the explicit `reason=` keyword for the `tornado.web.HTTPError()` constructor:

```python
raise HTTPError(400, 'My message')
# should be
raise HTTPError(400, 'Log message', reason='My user facing reason, will be included in statusText')
```

**Comment by blink1073** [comment]
So should this be an issue on `jupyter_server` to audit error codes?

**Comment by vidartf** [comment]
I haven't checked the various parts, but if anything is raising a 400 HTTPError, it should add the `reason` keyword if it can offer some helpful message to the user.

**Comment by vidartf** [comment]
(My initial errors came from custom server code)
