### ISSUE TITLE
Should tab layout should have a small '+' tab at the end

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#73]
This should likely create a tab similar to the "jupyterlab" that allow to pick up the new type of file you want. That appear to be the obvious thing my brain want to do to create a new tab, and seem a pretty-standard UI.

**Comment by jasongrout** [comment]
Are you thinking there would be a small + at the end of every tab panel?

**Comment by Carreau** [comment]
> Are you thinking there would be a small + at the end of every tab panel?

Likely to be discussed, but roughly every panel on which you could attach a new document yes. 
I can see case where the tabs content are static, non reorderable tabs, but for any dynamic one 
I think this makes a lot of sens.

From the top of my head, Firefox, Chrome, Opera, and even OS X Finder implement that.

**Comment by jasongrout** [comment]
Yes, but all of those programs have only a single tab bar. We have many tab bars, so the answer might be different.

**Comment by sccolbert** [comment]
and adding a new tab in chrome has a well defined meaning: a new browser instance. In JLab it could mean a new editor, notebook, console, terminal, etc.

**Comment by sccolbert** [comment]
Not saying we shouldn't do anything here, just saying we need some real discussion on *what* we should do here.

**Comment by Carreau** [comment]
> and adding a new tab in chrome has a well defined meaning: a new browser instance. In JLab it could mean a new editor, notebook, console, terminal, etc.

Well chrome does that well it pops up a new tab with a UI that ask you what you want in this tab. 
We do already have the UI in LAB:
<img width="428" alt="screen shot 2016-06-15 at 10 52 35" src="https://cloud.githubusercontent.com/assets/335567/16091164/4afbc218-32e7-11e6-8ea9-a12796e0e8e6.png">

What i'm saying that click PLus should pop up this tab.

**Comment by ellisonbg** [comment]
I agree with @Carreau that we probably need this. It should do the same thing as any other UI for creating a new document or dock panel item: either a dropdown or a dialog that let's you pick the type.

**Comment by ellisonbg** [comment]
I am going to be doing some work on the overall experience of how we open files/activities. Will include this idea in that discussion.

**Comment by ellisonbg** [comment]
Launcher refactor in #2380 will address this is a slight different manner, closing.
