### ISSUE TITLE
Jupyter labextensions are not shown

### ISSUE THREAD

**Issue by githubfzq** [jupyterlab/jupyterlab#7309]
When I stop anaconda and restart it, all labextensions are disappeared.
![image](https://user-images.githubusercontent.com/19188149/66537509-40979680-eb53-11e9-9e42-30655c4a9b41.png)

But when I type jupyter labextension command `jupyter labextension list` in console, it's OK:

```
(clamp) root@86c0412109d8:/# jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: /opt/conda/envs/clamp/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        @jupyterlab/git v0.6.0  enabled  OK
        @jupyterlab/github v0.10.0  enabled  OK
        @jupyterlab/toc v0.6.0  enabled  OK
        jupyterlab-jupytext v0.19.0  enabled  OK
        jupyterlab-zip v0.1.0  enabled  OK
```

Where this problem come? How to solve it?

**Comment by githubfzq** [comment]
If I re-install an extension, like this:
![image](https://user-images.githubusercontent.com/19188149/66537784-5c4f6c80-eb54-11e9-85b7-98a4e2772d13.png)

```
Kernel companions
This package has indicated that it needs a corresponding server extension: jupyterlab-git

You should make sure that the indicated packages are installed before trying to use the extension. Do you want to continue with the extension installation?
```

**Comment by bw-space** [comment]
Use jupyter labextension uninstall <ext-name>  , and then install the extension. Do you have nodejs and npm installed?

**Comment by jasongrout** [comment]
It looks like you need node installed. You can install it from anaconda - install the nodejs conda package.

**Comment by githubfzq** [comment]
> Use jupyter labextension uninstall , and then install the extension. Do you have nodejs and npm installed?

I have already uninstall all extensions, and node.js is also installed too.
```
(clamp) root@86c0412109d8:/# conda list nodejs
# packages in environment at /opt/conda/envs/clamp:
#
# Name                    Version                   Build  Channel
nodejs                    11.14.0              he1b5a44_1    conda-forge
```

**Comment by githubfzq** [comment]
> It looks like you need node installed. You can install it from anaconda - install the nodejs conda package.

I installed nodejs from conda-forge channel by:
```
conda install -c conda-forge nodejs
```
It doesn't work after fresh the page.

**Comment by githubfzq** [comment]
Maybe I got missed between different environment, the jupyter lab is actually running in another environment, where no nodejs and npm is installed.

**Comment by vidartf** [comment]
Thanks for reporting back with the root cause 👍
