### ISSUE TITLE
Log console status bar widget does not update

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7325]
## Description

Log console status bar widget sometimes does not update its message count

## Reproduce

On JupyterLab 1.2.0a1:

1. Open a new notebook
2. Open the Log Console and add a few timestamps so that there are some messages
3. Observe that the message count in the status bar is updated
3. Open a new launcher (not a notebook, just the launcher)
4. Notice that when the launcher is focused, you still see the notebook's message count.

## Expected behavior

In step 4, the message count should display zero messages.

## Context

- Operating System and version: macOS 10.14.6
- Browser and version: Firefox 69
- JupyterLab version: 1.2.0a1

CC @mbektasbbg

**Comment by bw-space** [comment]
Can you help me find the log console of step 2, I am unable to find it.

**Comment by jasongrout** [comment]
You can open it from the view menu or by clicking on the message icon in the status bar.

**Comment by mbektasbbg** [comment]
@jasongrout the reason for this behavior is, active source is updated when a new notebook is activated (https://github.com/jupyterlab/jupyterlab/blob/master/packages/logconsole-extension/src/index.tsx#L540) or a notebook is closed (https://github.com/jupyterlab/jupyterlab/blob/master/packages/logconsole-extension/src/index.tsx#L553).

I couldn't find a way to detect deactivation of a notebook/log source.

Is there a way to listen for deactivation of a notebook (or activation of another tab that is not a notebook)?

**Comment by jasongrout** [comment]
Good question. You could handle this similar to how the line numbers are handled in the status bar, and listen to the currentChanged signal on the lab shell:

https://github.com/jupyterlab/jupyterlab/blob/e04e3af5ebc285a07b9cfb879aeb741dcb31ad11/packages/statusbar-extension/src/index.ts#L228-L241
