### ISSUE TITLE
[Docs] Contributing guide overview is missing in the documentation

### ISSUE THREAD

**Issue by katsar0v** [jupyterlab/jupyterlab#7345]
## Description

Currently when somebody decides to contribute to the project, he/she needs to find [`CONTRIBUTING.MD`](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md), which is properly linked in the readme and is in the root of the project, but maybe it's worth having contribution overview in the docs as well (which might be extended later). One possibility would be to rename [Writing Documentation](https://jupyterlab.readthedocs.io/en/stable/developer/documentation.html) into something like "Contributing to JupyterLab" where you have a bit more detailed overview about contributing instead of a single link. In case the page does not get renamed, we can have an additoinal menu item about contributing, which will still be better than a single link to `CONTRIBUTING.md` :) Happy to hear your feedback!

**Comment by saulshanabrook** [comment]
Thanks for opening this. I agree it would be good to put a contributing to Jupyterlab in the sidebar. We could possibly put the writing docs as a subpage under it?

One thing that might be useful exploring is embedding our existing contributing.md in the docs by using a Sphinx plugin to read markdown.

**Comment by katsar0v** [comment]
`contributing.md` is currently outside `docs/`, do you think this would work? 

> We could possibly put the writing docs as a subpage under it?

I was thinking the same - to name the main page "Contributing" or "Contributing to JupyterLab" and make "Writing Documentatoin" a sub-point of it.

**Comment by katsar0v** [comment]
![image](https://user-images.githubusercontent.com/7236157/66704854-3c6ca400-ed20-11e9-9df8-449e2b6d78da.png)

I think something like this would do it :) What do you guys think?

**Comment by vidartf** [comment]
> I think something like this would do it, probably should go up in the menu :) What do you guys think?

Looks good from the screenshot 😃 👍

**Comment by katsar0v** [comment]
I could make a PR about this :) Would you guys agree to do this this way? I could also put "Writing Style" as a sub-point of "Writing Documentation"

**Comment by vidartf** [comment]
Closing as resolved by #7378 (if not leave a comment to reopen).
