### ISSUE TITLE
Show file-size in File browser

### ISSUE THREAD

**Issue by stefansimik** [jupyterlab/jupyterlab#7352]
Hi, 
I believe developers are frequently looking for the **size of the files** in File Browser.
One simply needs to to see how big are input *.csv files, *.pickle files or many other.
One still has to switch to the OS file-browser, to see this very basic information.

Would you find it useful to add and display this information in the FileBrowser?

_Note:
I could not find any plugin/extension, that could do this. 
But is it generally useful basic thing, that this feature should be standard part of JupyterLab interface._

**Comment by blink1073** [comment]
Hi @stefansimik, that sounds like a great idea to me!  I think at a minimum we should add some info as an HTML `title` [here](https://github.com/jupyterlab/jupyterlab/blob/master/packages/filebrowser/src/listing.ts#L1801) using the `model` info.  We do something similar for document tabs [here](https://github.com/jupyterlab/jupyterlab/blob/927d20908af3da2b7bc480417876ce66294747c0/packages/docmanager/src/widgetmanager.ts#L262). 
Docs on the `IModel` [interface](http://jupyterlab.github.io/jupyterlab/services/interfaces/contents.imodel.html).

Is this something you wanted to work on?

**Comment by stefansimik** [comment]
Hi @blink1073 , thank you for you support.
Currently, I am just heavy user and proud promoter of JupyterLab in my courses, but I am just newbie in Javascript / related technologies. Despite, if I could be of any other help, I am ready ;)

**Comment by blink1073** [comment]
Fair enough, thanks for the feedback!
