### ISSUE TITLE
How to change the output cell font-size?

### ISSUE THREAD

**Issue by ShawnDX** [jupyterlab/jupyterlab#7356]
![image](https://user-images.githubusercontent.com/30729729/66727133-cbd49d00-ee6f-11e9-94bb-db84c00b2588.png)

in the picture above
I have changed the number of Input/output cell by modifying " .\jupyter\lab\themes\@jupyterlab\theme-light-extension"  
like this
![image](https://user-images.githubusercontent.com/30729729/66727247-7ea4fb00-ee70-11e9-9c38-174b9a1bfff6.png)
BUT when I use the same way to add the css code, it DOSE NOT WORK!!
`
.jp-OutputArea-output {
  font-size: var(--jp-code-font-size)-2;
}
`
the class name was finding by "Inspect"
So I want to know how to change the output cell font-size, because it may be so lager when I run tensorflow models that it can not show all the output in a line.
![image](https://user-images.githubusercontent.com/30729729/66727363-30dcc280-ee71-11e9-9e39-8b1ffbcecb57.png)

**Comment by bw-space** [comment]
Try using "Ctrl  - " or "Cmd  -" it should change the size of the overall page.

**Comment by ShawnDX** [comment]
> Try using "Ctrl - " or "Cmd -" it should change the size of the overall page.
thx a lot, I Know that way, but that will change the whole page's font-size, but for me I just want the output Aera to be smaller, maybe I am a trouble maker XD

**Comment by ShawnDX** [comment]
> Try using "Ctrl - " or "Cmd -" it should change the size of the overall page.

thx a lot, I know that way, but that will change the whole page's font-size. For me I just want the output Aera to be smaller, maybe I am a trouble maker XD

**Comment by telamonian** [comment]
There are a number of things wrong with what you're trying. Currently, the easiest way to get what you want, assuming you're using a version of jlab `>= v1.1.0` is to go to the menus and select `Settings -> JupyterLab Theme -> Decrease Code Font Size`. This will decrease the font size in both the notebook's inputs and outputs. There's currently no way to adjust the output font size independently. However, I'm currently [in the process of adding more settings](https://github.com/jupyterlab/jupyterlab/pull/7130) that will allow users to tweak various aspects of the theme, so I can add that in as well in the near future.

I would not recommend hacking the CSS in an installed copy of jlab. If you realllly want to regardless, note that you have to use the correct class selector, which in this case would be `jp-OutputArea-output`, not `jp-OutputArea-prompt`.

**Comment by ShawnDX** [comment]
> t `jp-OutputArea-prompt`.
Thank you very much！ I will try your new method. XD

**Comment by telamonian** [comment]
The problem you're going to run into is that every time you rebuild JupyterLab for any reason (eg you upgrade JupyterLab, you install an extension, you run `jupyter lab build`, etc), any changes you make to the CSS will get wiped out.

Since this is a filthy hack, and the question has been answered, I'm going to consider the matter settled and close the issue
