### ISSUE TITLE
Installing a local extension creates a build in the current directory

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7360]
I'm not sure what is going on here with jlab 1.2.0a1:

```
pushd $(mktemp -t mytmp -d)
# we are now in an empty temporary directory
conda create -n del-testjlab -c conda-forge/label/prerelease-jupyterlab -c conda-forge jupyterlab=1.2.0a1 ipywidgets nodejs
conda activate del-testjlab
# should just install the local build of the ipywidgets jlab extension
jupyter labextension install ~/path/to/ipywidgets/packages/jupyterlab-manager
```
I expected to be in an empty directory still. However, somehow this previously empty temporary directory gets populated with what looks like a jlab build directory:
```
% ls                                                                                
extensions/  imports.css  schemas/     settings/    staging/     static/      themes/
```
Was there a change in the build process that somehow sets the current directory as the build directory?

**Comment by blink1073** [comment]
Probably related to https://github.com/jupyterlab/jupyterlab/pull/7268.   We should backport that one and https://github.com/jupyterlab/jupyterlab/pull/7249 and https://github.com/jupyterlab/jupyterlab/pull/7109 to 1.x imo

**Comment by telamonian** [comment]
I just checked, and it looks like #7079 did indeed make it into the `1.2.0a1` tag. #7079 caused the same issue before on master, and #7268 was the fix, so that does need to get backported.

**Comment by telamonian** [comment]
The backport is done, and should be available if you want to test it Jason

**Comment by telamonian** [comment]
I opened backports for #7249 and #7109 as well. I'm less familiar with these, so if you'd care to do the honors @blink1073?

**Comment by blink1073** [comment]
Thanks @telamonian!

**Comment by jasongrout** [comment]
Fixed by the backports above.
