### ISSUE TITLE
subprocess invoked from notebook does not print output of shell command

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#7365]
## Description

Shell subprocess invoked via the subprocess module does not print any output by default. 
For example, running the following code in a notebook cell doesn't print the result of `ls`. However running the following code in a Python shell does print the result of `ls`. Of course, one can manually capture the result of `subprocess.run` and print it. However, the discrepancy of the same code in Python shell and notebook cell makes me believe it is bug. 
```
import subprocess as sp
sp.run('ls', shell=True)
```
## Reproduce

Already explained in the description.

## Expected behavior

Result of subprocess should be printed when invoked from a notebook cell (similar to invoking a subprocess in a Python shell). 

## Context

- Operating System and version: Ubuntu 19.04
- Browser and version: Chrome 77
- JupyterLab version: 1.1.4

**Comment by jasongrout** [comment]
Just curious, does it print anything in the classic notebook?

**Comment by dclong** [comment]
@jasongrout No, it does not print anything in the classic notebook either. Should I create a ticket in https://github.com/jupyter/notebook?

**Comment by jasongrout** [comment]
It also doesn't print in the qtconsole. The fact that three different kernel frontends don't display it points to it being an issue with the kernel, not the frontends. Perhaps an issue on ipykernel is better?

**Comment by dclong** [comment]
@jasongrout There is already a related issue in ipykernel. 

https://github.com/ipython/ipykernel/issues/310
