### ISSUE TITLE
Allow disabling build check in normal mode

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#7368]
I would like to be able to get JupyterLab to disable the build check in normal (non dev, non core) mode. Currently it is only disabled if it is core or dev mode: https://github.com/Madhu94/jupyterlab/blob/e738aa07a7a194a621aaf99ffdffb8b4388b98e6/jupyterlab/extension.py#L140

I am trying to run automated tests on an extension and the popup interferes with them.

**Comment by vidartf** [comment]
Are you thinking to change this from the server side, or from the JS side?

**Comment by saulshanabrook** [comment]
It doesn't matter to me. Whichever is easier.

**Comment by bollwyvl** [comment]
Perhaps just allowing `page_config_data` to be authoritatively set by the config system would offer the most flexibility:

https://github.com/jupyterlab/jupyterlab/blob/735dffc6ef2cf9f3356f5bd862bb0bbfaec249ac/jupyterlab/extension.py#L141

So something like:
```json
{
  "LabApp": {
    "tornado_settings": {
      "page_config_data": {
        "buildCheck": false
      }
    }
  }
}
```

**Comment by vidartf** [comment]
@bollwyvl Yeah, we might want to change the current setting of `buildCheck` to only set the default instead of overwriting:
https://github.com/jupyterlab/jupyterlab/blob/735dffc6ef2cf9f3356f5bd862bb0bbfaec249ac/jupyterlab/extension.py#L143

**Comment by bollwyvl** [comment]
Perhaps, 
```py
page_config = {}
...
page_config['buildCheck'] = not core_mode and not dev_mode
...
page_config.update(web_app.settings.get('page_config_data', {})) 
```

**Comment by bollwyvl** [comment]
ah, nm it does lots of things based on what it finds there... each setting needs to check, and it gets used at different stages in the build lifecycle: webpack, template, tornado app startup, and all over in lab. I've certainly hacked the dumped JSON in places. 

Also, some of these values not super documented, and sometimes can be managed by `$prefix/lab/settings/page_config.json`... certainly worth a look, and will be a bit tricky to maintain backwards compatibility, but worth it. May try to take a look at it, as I'm also running into surprises on windows with node startup vs high-speed automated testing.

**Comment by saulshanabrook** [comment]
Yay! Thanks @bollwyvl for fixing this! https://github.com/jupyterlab/jupyterlab/pull/7381
