### ISSUE TITLE
jupyter lab in prompt but it doesn't work

### ISSUE THREAD

**Issue by loremauro98** [jupyterlab/jupyterlab#7369]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by loremauro98** [comment]
I run jupiter lab in the prompt of the directory that i want to work in but i receive this message 
Traceback (most recent call last):
  File "c:\users\lorem\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lorem\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lorem\AppData\Local\Programs\Python\Python37\Scripts\jupyter.exe\__main__.py", line 9, in <module>
  File "c:\users\lorem\appdata\local\programs\python\python37\lib\site-packages\jupyter_core\command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "c:\users\lorem\appdata\local\programs\python\python37\lib\site-packages\jupyter_core\command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-lab` not found.

how can i solve this issue? thanks

**Comment by stefansimik** [comment]
Isn't that, you just typed just
`jupyter-lab`
instead of correct
`jupyter lab`  ?

**Comment by IMlixingwang** [comment]
I've had this problem before，you could run "pip install -e ." more times

**Comment by loremauro98** [comment]
I ran your string but it tells me an error:
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: C:\Users\lorem\Desktop\dataset

**Comment by vidartf** [comment]
@loremauro98 How did you install jupyterlab?

**Comment by loremauro98** [comment]
with pip install

**Comment by loremauro98** [comment]
But i reinstalled it now and it works. Is it magic?

**Comment by loremauro98** [comment]
Thank you all by the way

**Comment by stefansimik** [comment]
Close the issue please, if resolved ;)
