### ISSUE TITLE
How does the modified code work when i run “jupyter lab”

### ISSUE THREAD

**Issue by IMlixingwang** [jupyterlab/jupyterlab#7373]
No bug.I have a problem and need help.I have changed the code in packages,In the development environment(jupyter lab --dev-mode) ,the modified code takes effect,but, when i run script  “jupyter lab“，it didn't work 。What can I do to make it work when i run script " jupyter lab ".

**Comment by jasongrout** [comment]
`jupyter lab --dev-mode` is how to make your custom changes be run. `jupyter lab` always runs the last published version in the repo.
