### ISSUE TITLE
Terminal hasn't text

### ISSUE THREAD

**Issue by anki-code** [jupyterlab/jupyterlab#7375]
The issue #6915 is blocked and I can't reopen it but the issue is still actual from JupyterLab 1.0.4 to actual 1.1.4.

1. I have a tab with JupyterLab in Firefox (my coworkers sometimes told about Safari too) and every 1-3 days the issue appears. 
2. I restart Firefox to fix it and the text returns. 
3. But 1-3 days passed again and when I return to terminal it is broken. 

It repeat again and again and annoying.

![image](https://user-images.githubusercontent.com/1708680/66922286-6d561d00-f02f-11e9-8a39-f99046b1f050.png)

**Comment by anki-code** [comment]
I've faced with this two or three times a week.

**Comment by vidartf** [comment]
One troubleshooting step you can try when this happens: Shift + right click on the text, Inspect element, look for "computed styles" window for the dark text, look for the entry for font color (`color` I think), and expand to see if it says where the color setting is coming from (which rule). That would help us tracking this down a lot, even if we cannot reproduce.

**Comment by anki-code** [comment]
@vidartf thanks! Let's deep dive:
1. Here it is:

![image](https://user-images.githubusercontent.com/1708680/67593871-c6c6f600-f76b-11e9-9bee-f4b8bc3246ec.png)

2. Inspect:

![image](https://user-images.githubusercontent.com/1708680/67594059-34732200-f76c-11e9-9e51-aa9cc029ff3a.png)

**Comment by anki-code** [comment]
Also I've opened new terminal window with default `.bashrc` and when I do "Shift + right click on the text, Inspect" the inspector opens developer panel but don't open the html and styles. It shows first html lines and "No elemets selected" in styles.

**Comment by anki-code** [comment]
I don't know why but when I switch the theme to Light the color still black but the text is not appears:

![image](https://user-images.githubusercontent.com/1708680/67595094-7dc47100-f76e-11e9-9bb6-4bf7b1e7ab8c.png)


![image](https://user-images.githubusercontent.com/1708680/67594987-435ad400-f76e-11e9-9291-872aa3e9c9d8.png)

**Comment by vidartf** [comment]
Oh, wow, xterm is using canvas elements to do the rendering. Looking at the code, I see that it relies on the theme manager to signal when the theme has changed in order to update the rendering with the latest colors.

@gnestor Is this check here correct?

https://github.com/jupyterlab/jupyterlab/blob/35e34fe729acca44a9ed4301628ff928a322a0de/packages/terminal-extension/src/index.ts#L177

I would have expected it to use `themeManager.theme` instead of `'inherit'`.

**Comment by vidartf** [comment]
No actually, that code makes sense I think. Just to make sure @anki-code: Which themes are we talking about here:
- What is the main lab theme? Is this the one you are changing?
- What is the terminal theme? Is this set to `inherit` ?

**Comment by anki-code** [comment]
After install I just set Dark theme from the menu without any additional changes.

**Comment by gnestor** [comment]
@vidartf I added the theme support to the terminal extension so that users can select "light," "dark," and "inherit" (inherit terminal theme from the lab theme). If this issue appears to be caused by that theme logic, let me know and I will look into it.

**Comment by anki-code** [comment]
ℹ️ I've noticed that text in JupyterLab terminal disappears when I open video. So I've reinstalled video driver a couple days ago. After that the issue hasn't repeated. 

Other users are not bumped this issue so I think it's local problem.
