### ISSUE TITLE
file browser  does not show linked folders

### ISSUE THREAD

**Issue by Liorba** [jupyterlab/jupyterlab#7382]
## Description
when I create a soft  link between folder filesystem  and jupyterlab CWD, the linked folder does show in the file browser. only when I open the terminal and run `ls -l` the file browser suddenly shows the linked folder. 

this is happing when using docker container (not related to the "docker-stacks")
as part of the Dokerfile I added a line to `.bashrc` to add this link:
`RUN echo "ln -s /opt/my_examples  /home/jovyan/examples " >>  /home/jovyan/.bashrc`

## Reproduce

1. create a symbolic link between folder in your  FS and your home dir, 
2.  launch jupyter lab from your home dir `jupyter lab --ip=0.0.0.0 --port=8888`
3. you wont see the linked folder in the file browser
4. open termial (should automatically open in your CWD) run `ls -l`
5. now the linked folder will show in the file browser 

## Expected behavior

should see the linked folder  in the file browser 

## Context

- Browser and version: chrome 77.0.3865.90
- JupyterLab version: 1.0.4

**Comment by Liorba** [comment]
see below  the following video showing my issue:
![linked_folder](https://user-images.githubusercontent.com/9528734/66994727-66361a00-f0d6-11e9-91fe-e9c2de47fb87.gif)

**Comment by Liorba** [comment]
see below a short video showcase my issue:
![linked_folder](https://user-images.githubusercontent.com/9528734/66994918-c200a300-f0d6-11e9-9cf4-84527666afd8.gif)

**Comment by Liorba** [comment]
@jasongrout I followed the instruction, and I was not able to reproduce the issue.
I did find that this is an issue related to sourcing the bashrc file.
closing the issue

**Comment by jasongrout** [comment]
Thanks for following up here!
