### ISSUE TITLE
blank screen with jupyterlab starting from version 1.0.0

### ISSUE THREAD

**Issue by eurydice76** [jupyterlab/jupyterlab#7383]
I installed `jupyterlab` with `conda`. When selecting the last available `0.*` version namely the `0.35.6`, everything is OK when launching `jupyterlab`. However starting from the version `1.*` namely the `1.0.2`, every installed version triggers a blank screen when launching `jupyterlab` server while the classic notebook view is OK. Digging a bit with the browser debugger, the following error occurs:

`syntax error missing : after property id jupyter vendors~main.5f0ef20c1b446f440307.js`

Naively, it looks like a regression. Do you have any idea about this and how to solve this without having to select a specific version through conda ?

**Comment by jasongrout** [comment]
That does look odd. Does the latest version, 1.1.4, work?

**Comment by eurydice76** [comment]
unfortunately not, being the current default one on conda this is the one I first tried.

**Comment by jasongrout** [comment]
> this is the one I first tried.

Sure. But does updating to jlab 1.1.4 work?

**Comment by eurydice76** [comment]
Yeap. After installing jlab, I checked by running jupyter lab --version and I get 1.1.4.

**Comment by jasongrout** [comment]
So it works now?

**Comment by eurydice76** [comment]
unfortunately still not

**Comment by eurydice76** [comment]
I wonder if it could not come from my firefox version. The one I use is from `ubuntu-xenial` i.e `50.0.2`. Unfortunately, I can not a newer version right now.

**Comment by eurydice76** [comment]
It is OK with firefox `69.0.2`. It seem that the version `50.0.2` was too old to support the `async` syntax. Not being a `js` (web)developer, would you know if my guess was right ? If so, the issue can be closed. Thanks for your help.

**Comment by jasongrout** [comment]
Yes, it looks like Firefox 52 was the first with support for async/await: https://caniuse.com/#feat=async-functions
