### ISSUE TITLE
jupyter lab cannot start

### ISSUE THREAD

**Issue by bjpcjp** [jupyterlab/jupyterlab#7390]
Have tried installing via pip and conda. Below is the conda debug steps:

* conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c anaconda jupyterlab
* conda activate jlab-test
* jupyter lab

error msg: Failed to write server-info to /home/bjpcjp/.local/share/jupyter/runtime/nbserver-32491.json: [Errno 13] Permission denied: '/home/bjpcjp/.local/share/jupyter/runtime/nbserver-32491.json'

**Comment by jasongrout** [comment]
Reading your error, it looks like you can adjust the permisssons on the directories/files it is complaining about?

**Comment by bjpcjp** [comment]
closed by author, due to multiple/conflicting errors.
