### ISSUE TITLE
Log console tab icon color

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7397]
As mentioned in https://github.com/jupyterlab/jupyterlab/pull/7379#issuecomment-544760867, the log console tab's icon does not change color depending on the theme. I wasn't sure how to do that with the new icon system. @telamonian - do you know how to change the icon color for a tab title depending on the theme?

**Comment by telamonian** [comment]
It's on my todo list for today. I'll look into it

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
@telamonian - we're cutting the 1.2RC. If it's possible to fix this before 1.2 ships in a few days, that would be great. If not, we'll not hold up 1.2 and just get it in 2.0.

**Comment by telamonian** [comment]
Fixed in #7436. This got away from me, but it was a simple fix: for svg icons, you have to follow a certain naming convention. If the name of the icon file is `list.svg`, then the corresponding classname is `jp-ListIcon`.
