### ISSUE TITLE
Jupyter Font Size of GUI Too Small

### ISSUE THREAD

**Issue by ShuoZ9379** [jupyterlab/jupyterlab#7404]
Hi Everyone,
could you please help me fix the problem of too small font size of Jupyter Lab GUI?

Please see the figure. Previously it worked well.
I did not remember I have changed anything of Jupyter.

Thanks so much.
<img width="1416" alt="Screen Shot 2019-10-22 at 11 29 31 PM" src="https://user-images.githubusercontent.com/33595526/67354923-e2d85680-f523-11e9-9a39-4fbdea781389.png">

**Comment by jasongrout** [comment]
Click that little magnifying glass icon in your browser address bar to reset your browser zoom back to 100%

**Comment by ShuoZ9379** [comment]
Thanks . so much.
Solved the problem.
