### ISSUE TITLE
Extensions Manager gets 500 Error if Jupyter launched as daemon in Ubuntu 

### ISSUE THREAD

**Issue by LightTemplar** [jupyterlab/jupyterlab#7418]
**Installation**:
Ubuntu Server 18.04 in home network
Anaconda installed from their repositories https://www.anaconda.com/rpm-and-debian-repositories-for-miniconda/
Jupyterlab installed from conda-forge repositories
I access Jupyter Lab over network.

**Issue**:
If I launch Jupyter Lab from ssh session, Extension Manager works, it shows me installed extensions and let discover new ones. But if I start Jupyterlab as a daemon, it gets "Error: 500 (Internal Server Error)"
I understand, it could be caused by conda installation, but I don't know, where to dig into.

**Details**:
Anaconda directory: /opt/conda, owner: root:conda, permissions; 775
My user is a member of conda group.

jupyter.service daemon file:
```
[Unit]
Description=Jupyter Notebook

[Service]
Type=simple
PIDFile=/run/jupyter.pid
ExecStart=/opt/conda/bin/jupyter lab      # I tried also /opt/conda/bin/jupyter-notebook 
User=alexander
Group=conda        # I tried also alexander
WorkingDirectory=/mnt/d_edata/devs/jpt-notebooks/
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
```

**Comment by LightTemplar** [comment]
And yes, it's all about Extension Manager, Notebooks work in both cases.

**Comment by jtpio** [comment]
@LightTemplar is there anything in the server logs? (with `journalctl -u jupyter.service`)

**Comment by LightTemplar** [comment]
@jtpio, well, yes. Strangely repetitive blocks, like this:
```
Oct 24 23:49:27 dark systemd[1]: Started Jupyter Notebook.
Oct 24 23:49:27 dark bash[24149]: /bin/bash: jupyter-notebook: command not found
Oct 24 23:49:27 dark systemd[1]: jupyter.service: Main process exited, code=exited, status=127/n/a
Oct 24 23:49:27 dark systemd[1]: jupyter.service: Failed with result 'exit-code'.
Oct 24 23:49:37 dark systemd[1]: jupyter.service: Service hold-off time over, scheduling restart.
Oct 24 23:49:37 dark systemd[1]: jupyter.service: Scheduled restart job, restart counter is at 3.
Oct 24 23:49:37 dark systemd[1]: Stopped Jupyter Notebook.
```

though Jupyter is started, I can see it with `jupyter notebook list` and access via browser. 

Looks like something from Jupyter Lab tries to execute 'jupyter-notebook' via bash, but bash can't find it. How is it started? Doesn't it use environment? I added line setting $PATH into .bashrc and .profile. Wasn't it enough?

**Comment by jtpio** [comment]
It says `/bin/bash: jupyter-notebook: command not found`. But JupyterLab should be using the `jupyter-lab` command (or `jupyter lab`).

It might be an issue with the conda environment yes.

**Comment by vidartf** [comment]
Note that the extension manager necessarily needs to *write* to disk (specific folders in the lab app directory) and *execute* commands (node / yarn). There might be an permission error related to this.

**Comment by LightTemplar** [comment]
Thanks for help!
I changed the ExecStart parameter in the jupyter.service daemon file to 
`ExecStart=/bin/bash -c ". /opt/conda/etc/profile.d/conda.sh;jupyter lab"` and it works now!

**Comment by LightTemplar** [comment]
Forgot to mention, I changed `/opt/conda/etc/profile.d/conda.sh` file, the line where $PATH was set. Original version added `/opt/conda/condabin` to the variable, my adds `/opt/conda/bin`, where all installed binaries are, uncluding jupyter.

**Comment by jasongrout** [comment]
Oh, I wouldn't change that path. Instead do something like:

```
ExecStart=/bin/bash -c ". /opt/conda/etc/profile.d/conda.sh;conda activate root;jupyter lab"
```

**Comment by LightTemplar** [comment]
@jasongrout, your solution makes more sense and more logical, actually. Thank you!
