### ISSUE TITLE
Command Palette inaccurately reflects state of 'Extension Installer' status all the time.

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#7429]
## Description

The checkmark in command palette doesn't disappear when the Extension Installer is toggled off.

## Reproduce

1. Go to the command palette
2. Click on 'Enable Extension Installer' (If not already on) to enable
3. Click 'Enable' on modal dialogue
4. Click 'Enable Extension Manager' to disable
5. Notice the checkmark doesn't disappear.
![cmd-palette-error](https://user-images.githubusercontent.com/22109376/67703947-7faa5200-f971-11e9-91d2-c6120a309d40.gif)

## Expected behavior

Checkmark should disappear when the extension is disabled.

## Context

- Operating System and version: OS High Sierra Version 10.13.16
- Browser and version: Chrome 77.0.3865.90
- JupyterLab version: 1.1.4

**Comment by jasongrout** [comment]
It seems that the first time I click on it after enabling, nothing happens, but the second time I click on it, the dialog comes up, and if I click "disable" the checkmark does indeed disappear.

I think you're right that it is not showing the disabled status. Perhaps we are not telling the system that a command is updated when we disable?

**Comment by jasongrout** [comment]
My guess is that right here:
https://github.com/jupyterlab/jupyterlab/blob/4336b1a12088aeacee5b8b786c5a339b0db63270/packages/extensionmanager-extension/src/index.ts#L87
we need to let the command registry know that it should update its rendering with `app.commands.notifyCommandChanged();` (search the code to see other places where this is used to see examples).

**Comment by agbaum** [comment]
Hi I'm new and would like to work on this! 

I'm having a little trouble, however. If I understand correctly I need to be running in devmode to run the code I've edited, but the Extension Installer is disabled in devmode, which means I can't actually test the problem. How do I run in devmode without turning of the Extension Installer? 

Thanks!

**Comment by dLamSlo8** [comment]
Hi, sorry for the inconvenience @agbaum . I started on this issue yesterday but didn't see this comment until I just merged a possible solution now.

**Comment by Zsailer** [comment]
Issue was solved in #7787. Thanks @dLamSlo8! Closing.
