### ISSUE TITLE
installation instructions do not result in working widgets

### ISSUE THREAD

**Issue by sbowman-mitre** [jupyterlab/jupyterlab#7432]
## Description
This originally started as an issue with one widgets extention, but has expanded to a larger concern. Original issue here. https://github.com/jupyter-widgets/ipywidgets/issues/2595

When I start in a fresh conda environment on CentOs7 or WSL/Ubuntu16.04 and I follow the posted installation instructions, I get an installation that does not allow lab extensions to be successfully installed. I can't use widgets in my notebooks and any attempt to perform `jupyter lab build` results in a error log file that complains that dependencies are not installed. Specifically, `semver` and `jquery` seem to be complained about every time. And when I install those manually using `npm`, I still get complaints and a non-working labextension system. 

## Reproduce

I have done this two or three times at this point on different systems and get the same result.

1. Create new conda env [using instructions](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html): `conda install -c conda-forge jupyterlab`
2. Activate the conda environment
2. Following [posted instructions](https://jupyterlab.readthedocs.io/en/stable/user/extensions.html), install nodejs: `conda install -c conda-forge nodejs`
3. Also install the jupyter-manager: `jupyter labextension install @jupyter-widgets/jupyterlab-manager`
4. Perform clean and build: `jupyter lab clean; jupyter lab build`
5. I get an error log that looks very regularly like: 
[jupyterlab-manager-install-failure.log](https://github.com/jupyterlab/jupyterlab/files/3780480/jupyterlab-manager-install-failure.log)

Note that this is all in the terminal. I have not actually started jupyter or opened any notebooks.

## Dependency Stack
I keep hoping this is a dependency conflict somewhere, but can't figure out what may be out-of-sync. 
At the `conda` level, I have this:
ipykernel 5.1.3 py37h5ca1d4c_0 conda-forge
ipython 7.8.0 py37h5ca1d4c_0 conda-forge
ipython_genutils 0.2.0 py_1 conda-forge
ipywidgets 7.5.1 py_0 conda-forge
jupyter_client 5.3.3 py37_1 conda-forge
jupyter_core 4.5.0 py_0 conda-forge
jupyterlab 1.1.4 py_0 conda-forge
jupyterlab_server 1.0.6 py_0 conda-forge
nodejs 12.11.1 h10a4023_0 conda-forge
notebook 6.0.1 py37_0 conda-forge
widgetsnbextension 3.5.1 py37_0 conda-forge

At the `npm` level, I have:
(jlab-test) sbowman@MM224395-PC:/mnt/c/Users/sbowman/git$ npm list
/mnt/c/Users/sbowman/git
└─┬ @jupyter-widgets/base@2.0.1
├─┬ @jupyterlab/services@4.1.1
│ ├─┬ @jupyterlab/coreutils@3.1.0
│ │ ├── @phosphor/commands@1.7.2 deduped
│ │ ├── @phosphor/coreutils@1.3.1 deduped
│ │ ├── @phosphor/disposable@1.3.1 deduped
│ │ ├── @phosphor/properties@1.1.3 deduped
│ │ ├── @phosphor/signaling@1.3.1 deduped
│ │ ├─┬ ajv@6.10.2
│ │ │ ├── fast-deep-equal@2.0.1
│ │ │ ├── fast-json-stable-stringify@2.0.0
│ │ │ ├── json-schema-traverse@0.4.1
│ │ │ └─┬ uri-js@4.2.2
│ │ │ └── punycode@2.1.1
│ │ ├─┬ json5@2.1.1
│ │ │ └── minimist@1.2.0 deduped
│ │ ├── minimist@1.2.0
│ │ ├── moment@2.24.0
│ │ ├── path-posix@1.0.0
│ │ └─┬ url-parse@1.4.7
│ │ ├── querystringify@2.1.1
│ │ └── requires-port@1.0.0
│ ├─┬ @jupyterlab/observables@2.3.0
│ │ ├── @phosphor/algorithm@1.2.0 deduped
│ │ ├── @phosphor/coreutils@1.3.1 deduped
│ │ ├── @phosphor/disposable@1.3.1 deduped
│ │ ├── @phosphor/messaging@1.3.0 deduped
│ │ └── @phosphor/signaling@1.3.1 deduped
│ ├── @phosphor/algorithm@1.2.0
│ ├── @phosphor/coreutils@1.3.1 deduped
│ ├─┬ @phosphor/disposable@1.3.1
│ │ ├── @phosphor/algorithm@1.2.0 deduped
│ │ └── @phosphor/signaling@1.3.1 deduped
│ ├─┬ @phosphor/signaling@1.3.1
│ │ └── @phosphor/algorithm@1.2.0 deduped
│ ├── node-fetch@2.6.0
│ └─┬ ws@7.2.0
│ └── async-limiter@1.0.1
├── @phosphor/coreutils@1.3.1
├─┬ @phosphor/messaging@1.3.0
│ ├── @phosphor/algorithm@1.2.0 deduped
│ └─┬ @phosphor/collections@1.2.0
│ └── @phosphor/algorithm@1.2.0 deduped
├─┬ @phosphor/widgets@1.9.3
│ ├── @phosphor/algorithm@1.2.0 deduped
│ ├─┬ @phosphor/commands@1.7.2
│ │ ├── @phosphor/algorithm@1.2.0 deduped
│ │ ├── @phosphor/coreutils@1.3.1 deduped
│ │ ├── @phosphor/disposable@1.3.1 deduped
│ │ ├── @phosphor/domutils@1.1.4 deduped
│ │ ├── @phosphor/keyboard@1.1.3 deduped
│ │ └── @phosphor/signaling@1.3.1 deduped
│ ├── @phosphor/coreutils@1.3.1 deduped
│ ├── @phosphor/disposable@1.3.1 deduped
│ ├── @phosphor/domutils@1.1.4
│ ├─┬ @phosphor/dragdrop@1.4.1
│ │ ├── @phosphor/coreutils@1.3.1 deduped
│ │ └── @phosphor/disposable@1.3.1 deduped
│ ├── @phosphor/keyboard@1.1.3
│ ├── @phosphor/messaging@1.3.0 deduped
│ ├── @phosphor/properties@1.1.3
│ ├── @phosphor/signaling@1.3.1 deduped
│ └─┬ @phosphor/virtualdom@1.2.0
│ └── @phosphor/algorithm@1.2.0 deduped
├─┬ @types/backbone@1.4.1
│ ├─┬ @types/jquery@3.3.31
│ │ └── @types/sizzle@2.3.2
│ └── @types/underscore@1.9.3
├── @types/lodash@4.14.144
├─┬ backbone@1.2.3
│ └── underscore@1.9.1
├── base64-js@1.3.1
├── jquery@3.4.1
└── lodash@4.17.15

Thank you!

**Comment by jasongrout** [comment]
We've had some releases in the last few weeks. Do you mind trying again and seeing if the issue is resolved? It also might be a network issue of some type, since it seems it can't get the right packages from npm - any chance there is a proxy between you and npm that might be stopping downloads?

**Comment by sbowman-mitre** [comment]
No, I'm afraid there's no change. I started with a fresh conda env and went though the installation process again. And, I still get an error log when trying to clean and build jupyter lab. And the error is still pointing to `jquery`, `@types/backbone`, `semver` as all missing dependendies. And when I install them using `npm`, the error persists.

**Comment by timb82** [comment]
Any solution so far?
I'm stuck on exactly same problem. Errors in logs are consistent with what was posted above. The only difference is that I'm on Windows 10

**Comment by sbowman-mitre** [comment]
For me, the answer is: not really. Since I originally posted this, I've switched to a new mac computer. So, no possibly conflicts still sitting around since then. I decided to try this again since @timb82 was asking. My steps above were a little unclear, so I'll show my steps again here:
* `conda create --name jupyterlab_test python=3.8`
* `conda activate juptyerlab_test` 
* `conda info` gives this:
(jupyterlab_test) ➜  gitrepos conda info
     active environment : jupyterlab_test
    active env location : /usr/local/Caskroom/miniconda/base/envs/jupyterlab_test
            shell level : 1
       user config file : /Users/sbowman/.condarc
 populated config files : /Users/sbowman/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __osx=10.15.3
       base environment : /usr/local/Caskroom/miniconda/base  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/Caskroom/miniconda/base/pkgs
                          /Users/sbowman/.conda/pkgs
       envs directories : /usr/local/Caskroom/miniconda/base/envs
                          /Users/sbowman/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.4 Darwin/19.3.0 OSX/10.15.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False

* `conda install -c conda-forge jupyterlab`
* `conda install -c conda-forge nodejs`
* `jupyter labextension install @jupyter-widgets/jupyterlab-manager` which results in:
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: npm dependencies failed to install
When I examine the log file, I see the same kind of errors as before: `error Couldn't find package "@jupyter-widgets/base@^3.0.0" required by...`

So, I don't think this is fixed. To be clear, I suspect that it does work and that there is an installation step that I'm missing. I just don't know what it that is. :(

**Comment by jasongrout** [comment]
> When I examine the npm error log file, I see the same kind of errors as before: `error Couldn't find package "@jupyter-widgets/base@^3.0.0" required by...`

Can you post your log file again? The commands you issued should all work, so it seems like you may be having problems pulling down the npm package.

**Comment by jasongrout** [comment]
You could also try pulling down that package manually with `npm pack @jupyter-widgets/base@^3`, just to see if you can get it from npm.

**Comment by sbowman-mitre** [comment]
@jasongrout : full error log from my attempt today. 
[jupyterlab-debug-error.log](https://github.com/jupyterlab/jupyterlab/files/4299038/jupyterlab-debug-error.log)

> You could also try pulling down that package manually...
Resulted in:
npm notice 
npm notice 📦  @jupyter-widgets/base@3.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE                
npm notice 467B   css/index.css          
npm notice 4.8kB  lib/backbone-patch.js  
npm notice 367B   lib/index.js           
npm notice 21.4kB lib/manager-base.js    
npm notice 7.4kB  lib/nativeview.js      
npm notice 297B   lib/registry.js        
npm notice 11.6kB lib/services-shim.js   
npm notice 11.1kB lib/utils.js           
npm notice 188B   lib/version.js         
npm notice 4.0kB  lib/viewlist.js        
npm notice 6.2kB  lib/widget_layout.js   
npm notice 4.9kB  lib/widget_style.js    
npm notice 33.9kB lib/widget.js          
npm notice 2.6kB  package.json           
npm notice 76B    lib/backbone-patch.d.ts
npm notice 264B   lib/index.d.ts         
npm notice 8.3kB  lib/manager-base.d.ts  
npm notice 1.2kB  lib/nativeview.d.ts    
npm notice 1.1kB  lib/registry.d.ts      
npm notice 5.9kB  lib/services-shim.d.ts 
npm notice 3.0kB  lib/utils.d.ts         
npm notice 105B   lib/version.d.ts       
npm notice 2.3kB  lib/viewlist.d.ts      
npm notice 972B   lib/widget_layout.d.ts 
npm notice 903B   lib/widget_style.d.ts  
npm notice 10.9kB lib/widget.d.ts        
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/base                   
npm notice version:       3.0.0                                   
npm notice filename:      jupyter-widgets-base-3.0.0.tgz          
npm notice package size:  34.8 kB                                 
npm notice unpacked size: 145.8 kB                                
npm notice shasum:        3996d566cddb742d275b007e0713de1e17f55a44
npm notice integrity:     sha512-un1ZTHALCwE/S[...]EkIZx+nOwstAQ==
npm notice total files:   27                                      
npm notice 
jupyter-widgets-base-3.0.0.tgz


Thanks. Hope that helps!

**Comment by jasongrout** [comment]
> Resulted in:
> npm notice
> npm notice 📦 @jupyter-widgets/base@3.0.0
> npm notice === Tarball Contents ===

Okay, that appeared to work. Can you try installing again, with the steps you listed above, in a clean environment? I was also having problems with npm last night, where it couldn't find a package until I manually pulled it down with npm pack. After I pulled it down, it suddenly could find it.

**Comment by sbowman-mitre** [comment]
> Can you try installing again, with the steps you listed above, in a clean environment?

Done. I fully removed the conda env and started over. But, the result was the same error log. 😞

**Comment by sbowman-mitre** [comment]
One oddity I've noticed. Even when I install `@jupyter-widgets/base@3.0.0` manually, the jupyter system seems to not know. It continues to complain about `base` not being found.  I don't have any idea why.

**Comment by jasongrout** [comment]
> Done. I fully removed the conda env and started over. But, the result was the same error log. 😞

The next step I would do if this were me to try to figure this out better is to go to the application directory (`jupyter lab path`), in the staging subdirectory, and try to build manually with `jlpm run build`, and generally poke around there to see what might be going on. It sounds like there is some sort of problem with npm here.

**Comment by timb82** [comment]
I've tried that, but I'm running into problems with "webpack". Here's where I'm at the moment, let me know if there's anything helpful in it or if I can somehow follow up.

```
(jlab) C:\Users\timb82\anaconda\envs\jlab\share\jupyter\lab\staging>jlpm run build
yarn run v1.21.1
$ webpack
'webpack' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.




(jlab) C:\Users\timb82\anaconda\envs\jlab>npm install webpack -g
....
....

+ webpack@4.42.0
updated 1 package in 11.763s

(jlab) C:\Users\timb82\anaconda\envs\jlab>npm install -g webpack-cli
C:\Users\timb82\anaconda\envs\jlab\webpack-cli -> C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\bin\cli.js
npm WARN webpack-cli@3.3.11 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.

+ webpack-cli@3.3.11
added 204 packages from 129 contributors in 11.43s




(jlab) C:\Users\timb82\anaconda\envs\jlab\share\jupyter\lab\staging>jlpm run build
yarn run v1.21.1
$ webpack
C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

Error: Cannot find module 'fs-extra'
Require stack:
- C:\Users\timb82\anaconda\envs\jlab\share\jupyter\lab\staging\webpack.config.js
- C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\bin\utils\convert-argv.js
- C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\bin\cli.js
- C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Users\timb82\anaconda\envs\jlab\share\jupyter\lab\staging\webpack.config.js:8:10)
    at Module._compile (C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\timb82\anaconda\envs\jlab\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\timb82\\anaconda\\envs\\jlab\\share\\jupyter\\lab\\staging\\webpack.config.js',
    'C:\\Users\\timb82\\anaconda\\envs\\jlab\\node_modules\\webpack-cli\\bin\\utils\\convert-argv.js',
    'C:\\Users\\timb82\\anaconda\\envs\\jlab\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\Users\\timb82\\anaconda\\envs\\jlab\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by remborg** [comment]
My coworker ran into the exact same issue yesterday evening with Jupyter Lab v1.1.3
We installed yarn globally and then installing the extension worked. 

Full story in case that doesn't work:
Before installing yarn globally we deleted the the yarn.lock file and ran `jlpm`  in the `C:\Users\...\anaconda\envs\jlab\share\jupyter\lab\staging` folder but that didn't work.
So then we installed yarn and installed all the node dependencies manually (running `jlpm` again).
It worked so we ran the extension installation command and it was all good.

**Comment by kevinpauli** [comment]
> We installed yarn globally and then installing the extension worked.

Amazing... I stumbled across this after days of frustration with inconsistent behavior trying to install jupyterlab extensions into a docker image.  Thanks to this idea, when I insert `npm install -g yarn` right before the `jupyter labextension install` statements, now it works consistently!  Thank you!

**Comment by jasongrout** [comment]
Thanks for sharing what works for you!
