### ISSUE TITLE
Access to Documents

### ISSUE THREAD

**Issue by gtancev** [jupyterlab/jupyterlab#7433]
## Description

Access to Documents Denied.

## Reproduce

I just upgraded my Mac to OS X 10.15. Had to reinstall Anaconda. JupyterLab works, but I have no access to the Documents or Desktop folder...

## Expected behavior

I expected that I could access Documents folder.

## Context

- Operating System and version: Intel Mac OS X 10.15
- Browser and version: Firefox 70.0
- JupyterLab version: 1.1.4

<details><summary>Command Line Output</summary>
<pre>
[I 21:36:38.616 LabApp] The port 8888 is already in use, trying another port.
[I 21:36:38.616 LabApp] The port 8889 is already in use, trying another port.
[I 21:36:38.617 LabApp] The port 8890 is already in use, trying another port.
[I 21:36:38.617 LabApp] The port 8891 is already in use, trying another port.
[I 21:36:38.617 LabApp] The port 8892 is already in use, trying another port.
[I 21:36:38.624 LabApp] JupyterLab extension loaded from /opt/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 21:36:38.624 LabApp] JupyterLab application directory is /opt/anaconda3/share/jupyter/lab
[I 21:36:38.626 LabApp] Serving notebooks from local directory: /Users/gtancev
[I 21:36:38.626 LabApp] The Jupyter Notebook is running at:
[I 21:36:38.626 LabApp] http://localhost:8827/?token=29c3d132e7c2f6b8636022981ff2aa208a8f13f5c5e17a34
[I 21:36:38.626 LabApp] or http://127.0.0.1:8827/?token=29c3d132e7c2f6b8636022981ff2aa208a8f13f5c5e17a34
[I 21:36:38.626 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:36:38.630 LabApp] 

To access the notebook, open this file in a browser:
file:///Users/gtancev/Library/Jupyter/runtime/nbserver-8004-open.html
Or copy and paste one of these URLs:
http://localhost:8827/?token=29c3d132e7c2f6b8636022981ff2aa208a8f13f5c5e17a34
or http://127.0.0.1:8827/?token=29c3d132e7c2f6b8636022981ff2aa208a8f13f5c5e17a34
[W 21:36:41.330 LabApp] Could not determine jupyterlab build status without nodejs
[E 21:36:43.054 LabApp] Uncaught exception GET /api/contents/Documents?content=1&1572295003048 (::1)
HTTPServerRequest(protocol='http', host='localhost:8827', method='GET', uri='/api/contents/Documents?content=1&1572295003048', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
File "/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
result = yield result
File "/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
value = future.result()
File "/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
yielded = next(result)
File "/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get
path=path, type=type, format=format, content=content,
File "/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 431, in get
model = self._dir_model(path, content=content)
File "/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 313, in _dir_model
for name in os.listdir(os_dir):
PermissionError: [Errno 1] Operation not permitted: '/Users/gtancev/Documents'
[W 21:36:43.059 LabApp] Unhandled error
[E 21:36:43.060 LabApp] {
"Host": "localhost:8827",
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:70.0) Gecko/20100101 Firefox/70.0",
"Accept": "*/*",
"Accept-Language": "de,en-US;q=0.7,en;q=0.3",
"Accept-Encoding": "gzip, deflate",
"Referer": "http://localhost:8827/lab",
"Authorization": "token 29c3d132e7c2f6b8636022981ff2aa208a8f13f5c5e17a34",
"X-Xsrftoken": "2|a4878f4c|5c563254f11bc1441cf4ce45d3d3fe85|1571860478",
"Content-Type": "application/json",
"Dnt": "1",
"Connection": "keep-alive",
"Cookie": "username-localhost-8888=\"2|1:0|10:1572289298|23:username-localhost-8888|44:ZGZhNmRhNGY0NzhmNGRjMjlkZThlZDRiNjJlNTEzNjY=|52149e0f401be8bb8c9907618439aaaf3b344089520df93fad00a598f8a0b8a8\"; username-localhost-8889=\"2|1:0|10:1572289532|23:username-localhost-8889|44:NzFkYWQ2ZWMwMjU5NGNmNThmMjQzZTVhYzIzNDgzZWU=|b118ca1ab4bb42954451736eee727a7d32932e1ef47d6ccc5af1da13c2021739\"; username-localhost-8890=\"2|1:0|10:1572289555|23:username-localhost-8890|44:M2NjY2M2Mzg4NjNkNDFiOTgxM2Y2OThjMGFjOGUwZTc=|f4957a172ee3be183f6a94bbece18599af2dcf0acf641c3fbf44099e010ff70e\"; username-localhost-8891=\"2|1:0|10:1572289811|23:username-localhost-8891|44:MmY2ZGI4ZWU0ZDAwNDg3YWFkYWQ1NWQwMmE3MjM4NDk=|e470334cb73ae2316a30c6898c10b9c83d8f194eb1333b0eca2eee2fd82ea3f3\"; username-localhost-8933=\"2|1:0|10:1569766735|23:username-localhost-8933|44:ZTgwYmFlNGUzNGY5NGYwM2JiYTBmOTAzMDg4ZWE3MjM=|906dc45c146f90c2a1987c0e5dce58fe2ecc1726a8c66149069820150a340cc1\"; username-localhost-8945=\"2|1:0|10:1572290212|23:username-localhost-8945|44:OGQyNWMzODI4YTg2NDIwYWJjMDVjZDI4ODU4MjBkYmU=|51fe5c98c0c0540d4d443f48e02f3b81bb564f911ee7c715581cacf3712f701a\"; username-localhost-8887=\"2|1:0|10:1570274954|23:username-localhost-8887|44:Njk3MjBjZTAyNmMwNGFmMDg3OGQ5ZWMwMjkxMjk1MTI=|90bea8037f4ae67ae337f14ca7404850d9ae39ec17300e7ea3911fe304f76207\"; username-localhost-8826=\"2|1:0|10:1570316792|23:username-localhost-8826|44:YjU5NzYwNDdmMzMyNDk0ZGFjZWU5MDRkMGU0MGVjNzQ=|c822faa840b930802b91bbf4a7f2f6a64aa1d6ac229f8a740752c7e929d14eb0\"; username-localhost-8839=\"2|1:0|10:1571918829|23:username-localhost-8839|44:MGUwMzIyODdlZjU3NDA1MmI2MThmYzMwOGQyNTM4Yjc=|d22a8a0eb773a29b3bb605ed0275a75f84d31892b970dde613100f8e9e00d688\"; username-localhost-8797=\"2|1:0|10:1570470729|23:username-localhost-8797|44:NTM5YTZiNTQxZmQxNDdiMDkxNzNkYzk4ZGY5NWEwNTQ=|58d5055799ee3e52ef68ff8fb35e4da9b515b4311b577a44fbe50449d4e01c29\"; username-localhost-8970=\"2|1:0|10:1570472594|23:username-localhost-8970|44:MDE5MTUxMDU5ZGY5NDY4MDk3OTY0NDE5NzBhMDNhNzE=|3fe773eae8f70e94f0421b69e41f2d0095160f1b0679e963b0568c3dc33b3542\"; username-localhost-8959=\"2|1:0|10:1570472802|23:username-localhost-8959|44:NWRlZWFlYzhhM2Q1NDkxMGIzYjM2MDljMWVlMGQ5MjY=|5c957d5e3cfa8bef3843bdf3f46f78ca4459967d75322fa6ad65c6e25c7a63f6\"; ajs_user_id=%2232077b58-baa4-5776-83ca-2fd1a403ebf9%22; ajs_group_id=null; ajs_anonymous_id=%22f1a1b0b3-eb76-4b21-b68b-97eae6aebf84%22; username-localhost-8892=\"2|1:0|10:1572289990|23:username-localhost-8892|44:NDQ0M2E5MGY4MmEwNDAyNDhjYTRjOWI0NTM0MGE1ZGM=|bae079c5b41131151bfce9a712ea7b473018b6d91166b83645deb78244db2a34\"; username-localhost-8881=\"2|1:0|10:1571737594|23:username-localhost-8881|44:YmZmZDI3YWY3MzM3NGVlNzkzMjg0ZjZiMzMyMTUwNmM=|3d717c1374a52937a61f05c37b7ddd829194a8759362e28649c9a458b60ff1bc\"; username-localhost-8827=\"2|1:0|10:1572295002|23:username-localhost-8827|44:MGRhZDAyYzJjNmNhNGQwOTk3M2RlZTA5OTAyNTU4ZmU=|e3160171a5a5bf39b0357d89ffd4d6714d008d9d2b468455c1dc3c87132f24d1\"; username-localhost-8824=\"2|1:0|10:1571860117|23:username-localhost-8824|44:OGExYTRlYmNmZTNkNDhlODhhMWE3NjEwMGYxMzgxZTc=|9873d949891529e9fbf4eea5f5d47f1ddc48bcfbdb5349b68bca8a8c8e96a652\"; _xsrf=2|a4878f4c|5c563254f11bc1441cf4ce45d3d3fe85|1571860478; username-localhost-8786=\"2|1:0|10:1571907984|23:username-localhost-8786|44:ODQxMmMxYzAzOTMzNDZjNDljZDY3OGY2ZjIyM2JjYjg=|2904c945d7466f7bd2b8674ae3516e5e1a034db3496761694f1a10c3e73e8dfa\"; username-localhost-8917=\"2|1:0|10:1572290120|23:username-localhost-8917|44:ZjVlOTBjYTVjNjNmNDM2OTkwYWFiZDAyZDc3NWI1YWI=|89939719d959721b7058dc03f9feb9b951f41dc3b30683faafaffba5886b8c2d\"; username-localhost-8880=\"2|1:0|10:1572291670|23:username-localhost-8880|44:Njk0YWNhMzAwNzRkNGI3YTgwMDI5Zjk5NTY1M2VhMjA=|cfc2958a5047961f5988a97cf4aca4fddbdf34ce37f0144e72b5e1558ec505fc\"; username-localhost-8829=\"2|1:0|10:1572294001|23:username-localhost-8829|44:N2QyNGY4YjA4NDlkNGYxZWE2ZDRmNDQ4OTU1OTRhNTA=|f9cf60d0871ee49b414e1b952ecc0cdf9d4526a3954b3caa2c3166253a509da6\"; username-localhost-8865=\"2|1:0|10:1572294295|23:username-localhost-8865|44:ZTQ0MDBkZjE5NTM1NGYyM2I3OWVlNzQxZjZhNGFjMDk=|8838a21dc2b03d2ab3f2078111932afcc7a99d1b6776c7d29a756f8069d5f36d\"; username-localhost-8965=\"2|1:0|10:1572294934|23:username-localhost-8965|44:M2Q1NzliODI0MjVlNDE0YjkzMWI5ZWI5NGUzNDk0ZDU=|81a001bea826769ff9dbda14f14684db0ffa77358de8db93dafea13a160ff069\"",
"Pragma": "no-cache",
"Cache-Control": "no-cache"
}
[E 21:36:46.439 LabApp] 500 GET /api/contents/Documents?content=1&1572295006431 (::1) 3.16ms referer=http://localhost:8827/lab

</pre>
</details>

**Comment by songxunyu** [comment]
me too!

**Comment by telamonian** [comment]
well that's not good. The underlying error you're getting is a permissions error:

```
PermissionError: [Errno 1] Operation not permitted: '/Users/gtancev/Documents'
```

My guess is that you're running into a poorly working use case of [this](https://nektony.com/duplicate-finder-free/folders-permission).

I really intensely dislike apple's accelerating policy of locking you out of bits of  your own computer in the name of security. The good thing is that there are ways to work around/turn off most of it. In this case, this [superuser answer](https://emacs.stackexchange.com/questions/53026/how-to-restore-file-system-access-in-macos-catalina) seems like the way to go. Just adapt the instruction they give for the `ruby` executable but substitute in the path to your `python` bin.

Unfortunately I can't test this myself. I'm gonna stick to 10.14 for the time being

**Comment by jasongrout** [comment]
Thanks @telamonian. Closing as answered and out of our hands.
