### ISSUE TITLE
Add a command to activate next panel

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#7434]
The main work area is great for having tabs in multiple groupings. Can we add a command with a keyboard shortcut active the next panel (sorry if my terminology is off).

This would toggle between 5 and 7 in this screenshot:
![image](https://user-images.githubusercontent.com/1813603/67717370-f5c7ac80-f9a3-11e9-8b5b-9283d439fc36.png)

Using `application:activate-next-tab` would have togged 6 next.

**Comment by jasongrout** [comment]
That sounds like a great idea to have a "jump to next panel" - of course which panel is next in a complicated layout might not be obviously the same for everyone, but I suppose any reasonable cycling is better than nothing.

Likely this would be a command implemented next to the activate next tab command: https://github.com/jupyterlab/jupyterlab/blob/4336b1a12088aeacee5b8b786c5a339b0db63270/packages/application-extension/src/index.tsx#L530-L535
and likely it would do something very similar - executing a shell method. The shell method could go next to the existing one and be similar:
https://github.com/jupyterlab/jupyterlab/blob/4336b1a12088aeacee5b8b786c5a339b0db63270/packages/application/src/shell.ts#L438

**Comment by jasongrout** [comment]
Setting as a good first issue. Let us know if you'd like to have a go at doing this.

**Comment by tgeorgeux** [comment]
Closing Via #7673
