### ISSUE TITLE
Shortcut to move cells

### ISSUE THREAD

**Issue by benthayer** [jupyterlab/jupyterlab#7447]
I just made these shortcuts, and I think it would be nice to include this or something like this as a system default. Would you be willing to accept a PR?
```
{
    "shortcuts": [
        {
            "command": "notebook:move-cell-up",
            "keys": [
                "Alt ArrowUp"
            ],
            "selector": ".jp-Notebook:focus"
        },
        {
            "command": "notebook:move-cell-down",
            "keys": [
                "Alt ArrowDown"
            ],
            "selector": ".jp-Notebook:focus"
        }
    ]
}
```

**Comment by jasongrout** [comment]
Is that both for mac (where alt=option) and windows/linux (using the alt key)?

I think it makes sense to have keyboard shortcuts like this for manipulating the notebook. Is there precedence for the alt-up/down shortcuts? In other words, are there other applications that have a list of things where alt-up/down lets you move selected items in the list?

**Comment by bthayer2365** [comment]
I'm just using this on Windows, haven't tested it on Mac or Linux.

In VSCode, you can select text and move a block of code up/down with Alt Up/Down. PyCharm uses Ctrl Shift Up/Down to accomplish the same thing. Alt Up/Down in PyCharm will move the cursor from function to function. I'm not sure if JupyterLab has something similar where you can jump the cursor from cell to cell or function to function other than when in command mode. I'm not sure what other editors do.

**Comment by KrishnaKumarHariprasannan** [comment]
> PyCharm uses Ctrl Shift Up/Down to accomplish the same thing

This behavior is shared by Notepad++ as well - I've opened https://github.com/jupyterlab/jupyterlab/pull/9031 to add the same. Let me know if you have reservations against this.
