### ISSUE TITLE
Integrate "Control Panel" and "Logout" buttons when launched from JupyterHub

### ISSUE THREAD

**Issue by sofianeh** [jupyterlab/jupyterlab#745]
These two buttons are missing, I don't see a way to logout directly from Lab
It would be nice to integrate "Control Panel" and "Logout" functionalities when Lab is launched from JupyterHub

Here's how they appear on the tree view (c.f. notebook):

![2016-08-24 16_55_06-home](https://cloud.githubusercontent.com/assets/271142/17947753/04035bca-6a1c-11e6-829c-dd534be558e4.png)

**Comment by ellisonbg** [comment]
Yep, in JupyterLab these will be handled by plugin. Pinging @minrk 

Two parts of this:

- [ ] Make sure that JupyterLab has the right extension points for add these things.
- [ ] Write the plugin that adds the functionality

**Comment by jasongrout** [comment]
I think this issue should be moved to jupyterhub, which would be the place for such a plugin to live.

**Comment by minrk** [comment]
@jasongrout - there's a task on either side. The first bullet (make sure it's possible) is on the Lab side, the second (do it) is on the JupyterHub side. In particular, I need a place in the jinja template to add items, which I don't see in the `lab.html` currently. If the static HTML injection isn't the way to go, that's fine, but I still need a way to specify to JupyterLab that things should be added to the Lab page at the Python application level.

@ellisonbg I also need some design input for how to add these things in Lab, which lacks the header of the 4.x notebook. Should it be a menu item? A command?

**Comment by jasongrout** [comment]
> If the static HTML injection isn't the way to go, that's fine, but I still need a way to specify to JupyterLab that things should be added to the Lab page at the Python application level.

Static html wouldn't be the way to go. The way to do this is to implement a plugin (javascript) and register that plugin with jupyterlab (which is a python thing). We're discussing how to do this in #224. Likely the plugin should register these as a top-level menu item, or perhaps a button over on the right of the menubar. And commands for each as well.

So, I think we should close this, since really the jupyterlab side is about getting third party extensions to work.

**Comment by jasongrout** [comment]
(and @minrk, we'd really appreciate your input on third party extensions, #728, where the discussion is happening currently)

**Comment by jasongrout** [comment]
> I think we should close this, since really the jupyterlab side is about getting third party extensions to work.

Or leave it open to address the UI issues... :)

**Comment by ellisonbg** [comment]
I actually think that JupyterHub is important enough that we should ship with support and provide a single command line flag for starting with JupyterHub support. I will begin working on this soon as I need to deploy all this in Jan...

**Comment by ellisonbg** [comment]
@danielballan is making progress on this...

**Comment by ellisonbg** [comment]
That work is here:

https://github.com/jupyterhub/jupyterhub-labextension

**Comment by blink1073** [comment]
Closing as moved to https://github.com/jupyterhub/jupyterhub-labextension.
