### ISSUE TITLE
Can I upload (donwload) all files in folder (directory)?

### ISSUE THREAD

**Issue by roccqqck** [jupyterlab/jupyterlab#7453]
I usually use jupyterlab on a remote linux server.

I know there are plenty of sftp gui softwares.

However, I still want to know
Is it possible to upload or download all files in one folder through jupyterlab?

**Comment by jasongrout** [comment]
For downloading, see https://github.com/jupyterlab/jupyterlab/pull/7294

**Comment by fcollonval** [comment]
The extension allowing archive files handling (and download directory as archive) is available there: https://github.com/hadim/jupyter-archive
