### ISSUE TITLE
JupyterLab Dark won't activate

### ISSUE THREAD

**Issue by sberglin** [jupyterlab/jupyterlab#7455]
## Description

Clicking on Settings --> JupyterLab Theme --> JupyterLab Dark does not change the theme. I stay on JupyterLab Light, with JupyterLab Light still toggled.

I tried uninstalling and reinstalling JupyterLab via `pip` (how I use JupyterLab), but had no luck.

## Context

I checked the settings file, but I see that Dark is already selected.

<img width="842" alt="Settings" src="https://user-images.githubusercontent.com/29701232/68072617-a68fcc00-fd55-11e9-8ea6-83fe1978b9cb.png">

However, Light is still showing.

A few relevant packages versions from `pip freeze` are

`ipykernel==4.6.1
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.1
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==1.2.0
jupyterlab-server==1.0.6
nbconvert==5.3.1
nbformat==4.4.0
nodejs==0.1.1
notebook==5.4.0
npm==0.1.1
widgetsnbextension==3.1.3`

If any other details would be helpful, please let me know!

**Comment by vidartf** [comment]
Which browser are you using?

**Comment by sberglin** [comment]
I am using Safari. I actually fixed it as a result of resolving problems from an incorrectly configured `kernelspec`. Fixing this in turn fixed the Dark theme.
