### ISSUE TITLE
JupyterLab 1.2.0 won't run without nodejs and npm, even with no extensions

### ISSUE THREAD

**Issue by JohnPaton** [jupyterlab/jupyterlab#7456]
## Description
The latest release (1.2.0) of Jupyter Lab seems to require NodeJS and NPM to run, even without any extensions.

## Reproduce

1. Install `jupyterlab==1.2.0` on a system without npm or nodejs
```
$ which npm
$ which nodejs
$ pip install jupyterlab==1.2.0
[ ... ]
Successfully installed MarkupSafe-1.1.1 Send2Trash-1.5.0 attrs-19.3.0 backcall-0.1.0 bleach-3.1.0 decorator-4.4.1 defusedxml-0.6.0 entrypoints-0.3 importlib-metadata-0.23 ipykernel-5.1.3 ipython-7.9.0 ipython-genutils-0.2.0 jedi-0.15.1 jinja2-2.10.3 json5-0.8.5 jsonschema-3.1.1 jupyter-client-5.3.4 jupyter-core-4.6.1 jupyterlab-1.2.0 jupyterlab-server-1.0.6 mistune-0.8.4 more-itertools-7.2.0 nbconvert-5.6.1 nbformat-4.4.0 notebook-6.0.1 pandocfilters-1.4.2 parso-0.5.1 pexpect-4.7.0 pickleshare-0.7.5 prometheus-client-0.7.1 prompt-toolkit-2.0.10 ptyprocess-0.6.0 pygments-2.4.2 pyrsistent-0.15.5 python-dateutil-2.8.0 pyzmq-18.1.0 six-1.12.0 terminado-0.8.2 testpath-0.4.2 tornado-6.0.3 traitlets-4.3.3 wcwidth-0.1.7 webencodings-0.5.1 zipp-0.6.0
```
2. Try to run `jupyter lab`
```
$ jupyter lab
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/labapp.py", line 40, in <module>
    app_version = get_app_version()
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 541, in get_app_version
    app_options, app_dir=app_dir, core_config=core_config))
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 582, in __init__
    self.registry = options.registry
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 343, in _default_registry
    config = _yarn_config(self.logger)["yarn config"]
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 1765, in _yarn_config
    node = which('node')
  File "/usr/local/lib/python3.7/site-packages/jupyterlab_server/process.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
```

Jupyter Lab 1.1.3 _does_ work:
```
$ pip install jupyterlab==1.1.3
$ jupyter lab
[I 16:25:17.289 LabApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[ ... ]
```

There are no extensions installed that would need to be built:
```
$ jupyter labextension list
JupyterLab v1.1.3
No installed extensions
```

## Expected behavior
Vanilla Jupyter Lab with no extensions should be able to run without requiring NodeJS or NPM

## Context

- Operating System and version: Debian GNU/Linux 10 (the official `python:3.7` Docker image). I have also hit the same issue on my MacBook (OSX Mojave)
- Browser and version: N/A
- JupyterLab version: 1.2.0

<details><summary>Troubleshoot Output</summary>
<pre>
$ jupyter troubleshoot
WARNING: You are using pip version 19.3; however, version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$PATH:
	/usr/local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/usr/local/bin
	/usr/local/lib/python37.zip
	/usr/local/lib/python3.7
	/usr/local/lib/python3.7/lib-dynload
	/usr/local/lib/python3.7/site-packages

sys.executable:
	/usr/local/bin/python

sys.version:
	3.7.4 (default, Oct 17 2019, 05:59:21)
	[GCC 8.3.0]

platform.platform():
	Linux-4.9.184-linuxkit-x86_64-with-debian-10.1

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter

pip list:
	Package            Version
	------------------ -------
	attrs              19.3.0
	backcall           0.1.0
	bleach             3.1.0
	decorator          4.4.1
	defusedxml         0.6.0
	entrypoints        0.3
	importlib-metadata 0.23
	ipykernel          5.1.3
	ipython            7.9.0
	ipython-genutils   0.2.0
	jedi               0.15.1
	Jinja2             2.10.3
	json5              0.8.5
	jsonschema         3.1.1
	jupyter-client     5.3.4
	jupyter-core       4.6.1
	jupyterlab         1.2.0
	jupyterlab-server  1.0.6
	MarkupSafe         1.1.1
	mistune            0.8.4
	more-itertools     7.2.0
	nbconvert          5.6.1
	nbformat           4.4.0
	notebook           6.0.1
	pandocfilters      1.4.2
	parso              0.5.1
	pexpect            4.7.0
	pickleshare        0.7.5
	pip                19.3
	prometheus-client  0.7.1
	prompt-toolkit     2.0.10
	ptyprocess         0.6.0
	Pygments           2.4.2
	pyrsistent         0.15.5
	python-dateutil    2.8.0
	pyzmq              18.1.0
	Send2Trash         1.5.0
	setuptools         41.4.0
	six                1.12.0
	terminado          0.8.2
	testpath           0.4.2
	tornado            6.0.3
	traitlets          4.3.3
	wcwidth            0.1.7
	webencodings       0.5.1
	wheel              0.33.6
	zipp               0.6.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
$ jupyter lab --debug
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/labapp.py", line 40, in <module>
    app_version = get_app_version()
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 541, in get_app_version
    app_options, app_dir=app_dir, core_config=core_config))
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 582, in __init__
    self.registry = options.registry
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 343, in _default_registry
    config = _yarn_config(self.logger)["yarn config"]
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 1765, in _yarn_config
    node = which('node')
  File "/usr/local/lib/python3.7/site-packages/jupyterlab_server/process.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
N/A
</pre>
</details>

**Comment by jasongrout** [comment]
The message makes it seem like it is related to #7109. CC @fcollonval

**Comment by stonebig** [comment]
as a remark, I think it was true also for Jupyterlab-1.1.4, on Windows 10

**Comment by fcollonval** [comment]
I'm working on a fix.

**Comment by JohnPaton** [comment]
Just tried out 1.2.1 and it seems good! Thanks for the quick fix guys 🚀
