### ISSUE TITLE
Failed to Fetch error with Folder named "Test_Advert" but not "Test_Adver"

### ISSUE THREAD

**Issue by albertmichaelj** [jupyterlab/jupyterlab#7459]
## Description

If I open Jupyter Lab (this has been tested on both Mac OS and a JupyterHub deployment running on EC2 instances with AWS Linux running in a Ubuntu 18.04 based Docker container) and then create a folder called "Test_Advert" and try to open a file in it, I get a " Launcher Error" "Failed to Fetch".
<img width="687" alt="Screen Shot 2019-11-01 at 2 10 38 PM" src="https://user-images.githubusercontent.com/5385923/68046159-91616180-fcb1-11e9-8bee-8f6771ddb4c2.png">
If I change the name to "Test_Adver" (i.e. drop the "t"), everything works fine. There are no errors in the log for Jupyter.

## Reproduce

See above.

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Expected behavior

Should be able to create and open files.

## Context

- Operating System and version:
Mac OS 10.14.6 and Ubuntu 18.04
- Browser and version:
Chrome 78
- JupyterLab version:
1.1.4

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by vidartf** [comment]
Just a screening check: do you have any ad-blockers active? Given the folder name that gets blocked, this seems a decent possibility.

**Comment by albertmichaelj** [comment]
You were exactly right. I hadn't even considered that an ad blocker might affect what kind of filenames Jupyter would open, but it makes perfect sense, and that was the problem. Thanks for your insight.

I'm closing this issue.
