### ISSUE TITLE
Make FAQ not hide the answers

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#746]
From https://github.com/jupyter/jupyterlab/issues/325#issuecomment-232096794

> Think about maybe not hiding the response in a collapsible area, and just make a TOC a the top. This woudl allow users to search with browser Ctrl-F.

CC @charnpreetsingh185.

**Comment by ellisonbg** [comment]
@charnpreetsingh185 any update on this one?

**Comment by charnpreetsingh185** [comment]
Moved to #857

**Comment by jasongrout** [comment]
Close this, then?
