### ISSUE TITLE
Output interactive plot from inside an if statement

### ISSUE THREAD

**Issue by sursu** [jupyterlab/jupyterlab#7466]
Just a question.

How can I deal with this kind of situations:

- https://github.com/plotly/plotly.py/issues/1861 ?

**Comment by jasongrout** [comment]
I answered in https://github.com/plotly/plotly.py/issues/1861#issuecomment-549317760

**Comment by jasongrout** [comment]
(feel free to continue the conversation if that answer doesn't help)
