### ISSUE TITLE
Improve command palette when no match found

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#747]
# Summary

3) The command palette show nothing when there is no matches which give an impression of emptiness, could we fill it with "no matches found" or any other placeholder, or informative text if appropriate ?
# Original issue

Thanks all for the new command palette, it looks nice. I see a few ways we can make it even better!

1) the magnifying glass seem too far from the right-side, and its position seem to be in percent of the field width, which is a bit weird (see #758).

2) the blue of the highlted items seem strangely out of place, is that on purpose, and it is just a first impression ? 

![screen shot 2016-08-24 at 14 34 23](https://cloud.githubusercontent.com/assets/335567/17949073/a5eb17a2-6a08-11e6-9a1a-4f4ae1903542.png)

3) The command palette show nothing when there is no matches which give an impression of emptiness, could we fill it with "no matches found" or any other placeholder, or informative text if appropriate ?

![screen shot 2016-08-24 at 14 41 18](https://cloud.githubusercontent.com/assets/335567/17949163/f69ec2d4-6a08-11e6-9b98-c698fb929752.png)

Sorry if this is only 1 issue, but I thought these things belong together.

**Comment by Carreau** [comment]
Link to #673 (thanks @jasongrout for providing the link in the other issue !)

**Comment by jasongrout** [comment]
> the magnifying glass seem too far from the right-side, and its position seem to be in percent of the field width, which is a bit weird.

Agreed - should be a fixed number of pixels from the right edge, methinks. Or maybe a set em-width from the right edge...

> the blue of the highlted items seem strangely out of place, is that on purpose, and it is just a first impression ?

I personally liked the previous orange better than the blue, but I'm happy to defer to the designers for the moment and customize my own theme later :).

> The command palette show nothing when there is no matches which give an impression of emptiness, could we fill it with "no matches found" or any other placeholder, or informative text if appropriate ?

+1

**Comment by jasongrout** [comment]
> the magnifying glass seem too far from the right-side, and its position seem to be in percent of the field width, which is a bit weird.

#758 is about this.

**Comment by sccolbert** [comment]
For handling "No Matches", I'll have to add some stuff to the Phosphor widget. Sounds like a good idea though.

**Comment by Carreau** [comment]
> For handling "No Matches", I'll have to add some stuff to the Phosphor widget. Sounds like a good idea though.

Wouldn't  the following be enough ? (not sure we can use multiple pseudo selectors, though)

```
.p-CommandPalette-content:empty:before{
    content:"no matches found";
    margin:10px;
}
```

**Comment by sccolbert** [comment]
Interesting idea. That may work. I was going to add to the renderer to allow for a custom "no matches" item to be rendered.

**Comment by Carreau** [comment]
> Interesting idea. That may work. I was going to add to the renderer to allow for a custom "no matches" item to be rendered.

It seem to work locally, but I agree that it tends to put some business logic (displaying a message to the user) in the css ...

**Comment by blink1073** [comment]
Fixed in master (due to updates in Phosphor):

![image](https://cloud.githubusercontent.com/assets/2096628/26175253/a872a504-3b17-11e7-9281-4841d2d29cdb.png)
