### ISSUE TITLE
Unzip archives from the file tree (enhancement)

### ISSUE THREAD

**Issue by phish108** [jupyterlab/jupyterlab#7477]
## Description

I use JupyterLab and Notebooks for teaching. The students complain  that they have to change into the terminal for unzipping archives (zip-files). 

## Current behavior 

Opening a zip file makes jupyterlab complain that "JupyterLab is unable to open this file type." 

## Expected behavior

Opening a zip-file should unzip it in the current location.

## Context

- Operating System and version: MacOS 10.14.6
- Browser and version: Chrome, Firefox, Safari
- JupyterLab version: 1.2.1

**Comment by hadim** [comment]
I have created an extension to do just this in JLab. Compressing/decompressing files in the JLab file browser: https://github.com/hadim/jupyter-archive

Please have a lool.

I am also waiting for some feedback from the JLab cor devs for a possible integration of this extension into the Jupyter stack: https://github.com/hadim/jupyter-archive/issues/2

Please report any issues.

**Comment by phish108** [comment]
just installed it, on a quick test it works like charm. thanks. 

Is there a way to trigger the jupyterlab build during installation time to avoid user hustle?

More thorough tests will follow in your repo.

**Comment by hadim** [comment]
The build should be triggered automatically during the next JLab start.

**Comment by phish108** [comment]
I noticed that and this is exactly what I want to avoid. 

I install the extension in a docker container (a variant of the official images) and the installation takes place **everytime** the container is launched. For my endusers this is annoying. 

Isn‘t it possible to trigger the installation from the command line?

**Comment by jasongrout** [comment]
You can always run `jupyter lab build` to trigger the rebuild.

**Comment by phish108** [comment]
@jasongrout and @hadim thank you for the support. 

The following installation solves this issue: 

```
> pip install jupyter-archive && jupyter lab build
```

This is very useful for extending jupyter lab from the official jupyter containers.
