### ISSUE TITLE
Extension metadata for replacement

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#7481]
## Description
Add extension metadata for replacing an extension.  The system will read this metadata and disable that extension automatically.  Currently extensions that replace core extensions have to tell their users to disable the core extension.  This would enable that to work automatically.

**Comment by mbektasbbg** [comment]
I am looking into this.

**Comment by blink1073** [comment]
We will handle this in a layered approach.

We we get [`disabled`](https://github.com/jupyterlab/jupyterlab/blob/02d1dcb85f9884a4369e34b385ec2e345f565500/jupyterlab/commands.py#L1078) metadata we will check these places in order:

- `package.json` for installed extensions - alphabetically
- `page_config.json` in the application directory
- `package.orig.json` for dynamic extensions - alphabetically
- `disabled_labextensions` trait data

Any one of these levels should be able to set either an extension or plugin pattern to `true` or `false`.  We need to add handling of `false`.
