### ISSUE TITLE
Debounce search queries in the extension manager

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#7484]
At the moment the extension manager seems to be firing a request to `npmjs.com` on every key stroke:

![debounce-extension-manager](https://user-images.githubusercontent.com/591645/68331690-b0a72700-00d5-11ea-9397-e0a23bfbc83f.gif)

It would be great to see if we can [debounce](https://github.com/jupyterlab/jupyterlab/blob/a09c3f6019837c49c2609fc7f1a549260c6ba2ae/packages/coreutils/src/ratelimiter.ts#L106) these requests or wait for the user to stop typing.

**Comment by vidartf** [comment]
Sounds good, especially now that we have some denounce helpers in coreutils :)

**Comment by Madhu94** [comment]
Can I take this up ?

**Comment by jasongrout** [comment]
I would say to go for it. We have a rate limiter in the core utilities that uses a Poll object.
