### ISSUE TITLE
Why 404 GET /example/bundle.js

### ISSUE THREAD

**Issue by FlyGreyWolf** [jupyterlab/jupyterlab#7488]
When I test the example in jupyterlab project
run the two commands "jlpm run build:examples" and "python main.py"
and the result I just see the blank page and report 404 GET /example/bundle.js
![image](https://user-images.githubusercontent.com/39620354/68383786-4653bc80-0191-11ea-8c43-5d6680ba3032.png)

**Comment by jasongrout** [comment]
Just checking, did you follow the other build instructions for setting up a dev environment, like `pip install -ve .` and `jlpm run build`?

**Comment by jasongrout** [comment]
Closing since the author did not follow up. Please comment here if you'd like to continue the discussion.
