### ISSUE TITLE
Why Cannot find module ‘typescript’

### ISSUE THREAD

**Issue by FlyGreyWolf** [jupyterlab/jupyterlab#7489]
![image](https://user-images.githubusercontent.com/39620354/68386994-3c818780-0198-11ea-9d32-c4d8dabc8804.png)

**Comment by jasongrout** [comment]
What editor are you using? It sounds like this has more to do with your editor.

Did you follow the dev setup instructions? https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#setting-up-a-development-environment

**Comment by jasongrout** [comment]
Closing as there was no follow-up. @FlyGreyWolf - feel free to comment if you want to continue discussion, and we can open this back up.
