### ISSUE TITLE
Cannot set env variables for a kernelspec in enterprise gateway through @jupyterlab/services

### ISSUE THREAD

**Issue by borremosch** [jupyterlab/jupyterlab#7498]
I am using `@jupyterlab/services` in combination with Jupyter Enterprise Gateway. Enterprise Gateway has extended the [API call to create a new kernel](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml#/kernels/post_api_kernels) with a property `env` in the request body. However, `@jupyterlab/services` does not allow me to specify this parameter. The issue can not be solved by using an `InitBody`, as this will be overwritten.

**Comment by vidartf** [comment]
Closed by #7499.
