### ISSUE TITLE
 [DISCUSS] Create a `jupyterlab-extension-examples` repository

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#7505]
This is a followup of #7502

I have seen in regular comments regarding "how to build an extension". @saulshanabrook 's [jupyterlab-webpack](https://github.com/saulshanabrook/jupyterlab-webpack) is a great start for a webpack case but I still feel the last mile (configure jlab and see the result) is missing.

I am following the [Extension Development Wishlist ](https://github.com/jupyterlab/jupyterlab/issues/7468) gathered by @saulshanabrook.

Upon the listed actions that would solve a lot of pain, I would like proposing the creation of a `jupyterlab-extension-examples` repo with very simple extension examples covering typical cases. For now, the existing options (cookiecutter, example folder in jupyterlab repo, existing extension like jupyterlab-github, Astronomy Picture of the Day...) do not answer the needs to correctly explain and guide new-comers to the various options and cases.

**Comment by echarles** [comment]
... or should we just bring more examples in the existing `examples` folder of jupyterlab/jupyterlab?

**Comment by jtpio** [comment]
@echarles there are some ideas and discussions in https://github.com/jupyterlab/jupyterlab/issues/7273 as well.

A `jupyterlab-extension-examples` repo sounds like a great idea. And it would also be useful to answer questions when they come and point to small code examples. I left a [comment](https://github.com/jupyterlab/jupyterlab/issues/7273#issuecomment-552187600) about that in  https://github.com/jupyterlab/jupyterlab/issues/7273.

Wondering whether this could be developed as a "third-party" / community initiative first before bringing it into core or under the `jupyterlab` organization?

**Comment by echarles** [comment]
Hi Jeremy, I am happy to further contribute on your fork assuming the intent is to propose it to the jupyterlab organisation and that the current original author (un)license is acceptable (which I think it is) to be accepted in the jupyterlab organisation.

I will wait more feedback (if any) on this issue before contributing to your fork. Looking forward to work together.

**Comment by jtpio** [comment]
Thanks @echarles.

Do you think we should keep this issue open or continue the conversation in https://github.com/jupyterlab/jupyterlab/issues/7273?

**Comment by saulshanabrook** [comment]
> I would like proposing the creation of a jupyterlab-extension-examples repo 

That sounds great! 

> Wondering whether this could be developed as a "third-party" / community initiative first before bringing it into core or under the jupyterlab organization?

Yep, I think that would be ideal.

**Comment by echarles** [comment]
Closing this to reduce issue congestion. Dev is happening in https://github.com/jtpio/jupyterlab-extension-tutorial. Feel free to join.
