### ISSUE TITLE
FileBrowser delete doesn't work when started from network share

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#7507]
##  Description

In the FileBrowser context menu selecting delete brings up a dialog which when you click DELETE doesn't actually delete the item.

This happens for both folders and files.

Note: the teminal logs the delete requests:
```
[I 11:02:20.131 LabApp] Creating new directory in /
[W 11:02:51.611 LabApp] delete /Untitled Folder
[W 11:03:13.929 LabApp] delete /Untitled Folder
[W 11:03:27.920 LabApp] delete /Untitled Folder
[W 11:04:17.203 LabApp] delete /Untitled Folder
[W 11:07:54.955 LabApp] delete /Untitled Folder
[I 11:08:01.607 LabApp] Creating new notebook in /
<snip>
[W 11:08:10.648 LabApp] delete /Untitled.ipynb
[W 11:09:14.508 LabApp] delete /Untitled.ipynb
```

They just don't do anything and give no error message in either the terminal or browser console.

## Context

- win64/py37 (Windows Server 2019)
- Chrome: 78.0.3904.87
- JupyterLab version: 1.2.2

***Possibly Highly Relevant:***
JupyterLab was started from PowerShell on a network share - i.e. the root of the FileBrowser is a network share rather than a local disk

**Comment by telamonian** [comment]
My money is on some flavor of permissions issue. Can you create new files using the filebrowser? And can you create/delete files directly in a Powershell?

**Comment by dhirschfeld** [comment]
I can create files and folders in the FileBrowser - I just can't delete them.

I started JupyterLab from an admin terminal and can delete the files/folders fine from the terminal.

I'm 99.9% sure this used to work fine.

**Comment by dhirschfeld** [comment]
I tested JupyterLab started from my local C drive and everything worked fine so it's definitely something to do with being started from a network share

**Comment by dhirschfeld** [comment]
Note: If I open a terminal from within JupyterLab I can delete things from there so that would tend to preclude permission issues and instead point the finger to a Windows path handling problem

**Comment by dhirschfeld** [comment]
Hard to say more as I can see *anything* in the JS console when I do any operations in the FileBrowser.

It looks like a silent, swallowed error but it could also be because I don't really know how to use the JS console properly :/

**Comment by dhirschfeld** [comment]
[*From gitter*](https://gitter.im/jupyterlab/jupyterlab?at=5dc9f08d4adf071a8411d964):
>*delete works fine from the classic notebook as well as the JupyterLab terminal*
> *It seems to be just the JupyterLab FileBrowser which has a problem*

**Comment by jasongrout** [comment]
Can you look at the Networks tab in the browser debugger, and tell us what the network request for deleting a file on a network drive looks like? I'm particularly interested in what the path is that it says to delete.

Do you know for sure if this ever worked?

What version of `notebook` do you have?

**Comment by dhirschfeld** [comment]
I'm almost certain it used to work - I've been using JupyterLab for a very long time from this folder so I'm sure I would've noticed this before if it was a problem.

I can try testing older versions but that might take me a while to get around to

**Comment by dhirschfeld** [comment]
in the networks tab I can't see anything that looks like a path?
I do see this though:
![image](https://user-images.githubusercontent.com/881019/68630116-00e91380-0532-11ea-868d-16c5b28363b3.png)

**Comment by dhirschfeld** [comment]
Tried again - same result:
![image](https://user-images.githubusercontent.com/881019/68630271-7f45b580-0532-11ea-9c71-9180148168c5.png)

**Comment by jasongrout** [comment]
What version of `notebook` do you have?

Given that it doesn't work in classic notebook either, this is almost surely either an error in the notebook server (i.e., should be reported in the https://github.com/jupyter/notebook/ repo), or some sort of installation/configuration error.

**Comment by jasongrout** [comment]
> Given that it doesn't work in classic notebook either, this is almost surely either an error in the notebook server (i.e., should be reported in the https://github.com/jupyter/notebook/ repo), or some sort of installation/configuration error.

To distinguish between these, it's probably best to have another person reproduce the error. In that case, can you give exact instructions (starting from creating a clean environment with fresh packages) to reproduce the issue?

**Comment by dhirschfeld** [comment]
On a Windows box you should be able to create a test environment with:
```
(base) C:\temp> conda create -n test-lab python=3.7 jupyterlab jupyter_server conda-forge::pyzmq conda-forge::zeromq
(base) C:\temp> conda activate test-lab
```

When started from the "normal" `C:\temp` directory it works:
```
(test-lab) C:\temp> jupyter lab
[I 10:50:48.781 LabApp] The port 8888 is already in use, trying another port.
[I 10:50:49.188 LabApp] JupyterLab extension loaded from C:\Users\dhirschf\envs\test-lab\lib\site-packages\jupyterlab
[I 10:50:49.188 LabApp] JupyterLab application directory is C:\Users\dhirschf\envs\test-lab\share\jupyter\lab
[I 10:50:49.584 LabApp] Serving notebooks from local directory: C:\temp
[I 10:50:49.585 LabApp] The Jupyter Notebook is running at:
[I 10:50:49.589 LabApp] http://localhost:8889/?token=dda10039216ad07d0af304929d9cef251470b1a373286afc
[I 10:50:49.590 LabApp]  or http://127.0.0.1:8889/?token=dda10039216ad07d0af304929d9cef251470b1a373286afc
[I 10:50:49.591 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:50:49.672 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/dhirschf/AppData/Roaming/jupyter/runtime/nbserver-12496-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=dda10039216ad07d0af304929d9cef251470b1a373286afc
     or http://127.0.0.1:8889/?token=dda10039216ad07d0af304929d9cef251470b1a373286afc
[W 10:50:52.546 LabApp] 404 GET /api/contents/untitled.txt?content=0&1573519852530 (::1): No such file or directory: untitled.txt
[W 10:50:52.548 LabApp] No such file or directory: untitled.txt
[W 10:50:52.565 LabApp] 404 GET /api/contents/untitled.txt?content=0&1573519852530 (::1) 21.00ms referer=http://localhost:8889/lab
[W 10:50:52.567 LabApp] 404 GET /api/contents/CalculateShape.ipynb?content=0&1573519852529 (::1): No such file or directory: CalculateShape.ipynb
[W 10:50:52.571 LabApp] No such file or directory: CalculateShape.ipynb
[W 10:50:52.577 LabApp] 404 GET /api/contents/CalculateShape.ipynb?content=0&1573519852529 (::1) 32.00ms referer=http://localhost:8889/lab
[I 10:50:52.902 LabApp] Build is up to date
[I 10:50:58.064 LabApp] Creating new file in /
[W 10:51:05.795 LabApp] delete /untitled.txt        <--- THIS WORKS!!!
[I 10:51:11.902 LabApp] Interrupted...
[I 10:51:11.903 LabApp] Shutting down 0 kernels
```

But if you cd to the UNC path it fails:
```
(test-lab) C:\temp> cd "\\$env:COMPUTERNAME\C$\temp\"
(test-lab) \\SERVER\C$\temp> jupyter lab
[I 10:51:41.236 LabApp] The port 8888 is already in use, trying another port.
[I 10:51:41.670 LabApp] JupyterLab extension loaded from C:\Users\dhirschf\envs\test-lab\lib\site-packages\jupyterlab
[I 10:51:41.670 LabApp] JupyterLab application directory is C:\Users\dhirschf\envs\test-lab\share\jupyter\lab
[I 10:51:42.070 LabApp] Serving notebooks from local directory: \\DC2TJUP01\C$\temp
[I 10:51:42.071 LabApp] The Jupyter Notebook is running at:
[I 10:51:42.076 LabApp] http://localhost:8889/?token=eff08ae5babb824f5ddc7ee789924024eaa61175453fdf36
[I 10:51:42.077 LabApp]  or http://127.0.0.1:8889/?token=eff08ae5babb824f5ddc7ee789924024eaa61175453fdf36
[I 10:51:42.078 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:51:42.172 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/dhirschf/AppData/Roaming/jupyter/runtime/nbserver-11316-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=eff08ae5babb824f5ddc7ee789924024eaa61175453fdf36
     or http://127.0.0.1:8889/?token=eff08ae5babb824f5ddc7ee789924024eaa61175453fdf36
[I 10:51:44.668 LabApp] 301 GET /lab/workspaces/auto-M/?clone (::1) 1.00ms
[I 10:51:46.285 LabApp] Build is up to date
[I 10:51:52.998 LabApp] Creating new file in /
[W 10:52:00.316 LabApp] delete /untitled.txt        <---  THIS FAILS SILENTLY!!!
[I 10:52:07.173 LabApp] Interrupted...
[I 10:52:07.175 LabApp] Shutting down 0 kernels
```

**Comment by dhirschfeld** [comment]
I tried a release-bisect and it didn't work all the way back to 0.35.6.

I think previously I was mapping the UNC path to a drive name so I may not have encountered the problem.

Since that workaround is easy and it's likely not a JupyterLab issue in any case I'll go ahead and close this...

**Comment by dhirschfeld** [comment]
@telamonian, @jasongrout - thanks for taking the time to figure it out with me!

**Comment by jasongrout** [comment]
> I tried a release-bisect and it didn't work all the way back to 0.35.6.

I think it's more likely to be an issue with the notebook server, not JupyterLab. Release-bisecting the notebook server is more likely to yield better information.
