### ISSUE TITLE
Moving question from Gitter

### ISSUE THREAD

**Issue by LuisFRoch** [jupyterlab/jupyterlab#7521]
Hi @jasongrout. following up the gitter question: sorry for the typo! It's plotlywidgets 1.3.0 on npm. The question is: "Is it safe to update without breaking Jlab." 
Often times when updating libs version, Jlab doesn't display the plot/widget (in my case) even when using clean env and following the suggestion of running specific commands e.g. (jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1 --no-build).  I don't have problems as of now running/displaying widgets, but I know there was a bug in go.table, where, for example, changing the font color on negative values is inconsistent (some negative values change color but also some positive ones. Already on plotly's repo), and i'd like to know if this version solves that issue and does not break Jlab. Thanks in advance.

**Comment by jasongrout** [comment]
Ah, sounds like a question for plotlywidgets?

FYI, `--no-build` means to not build the js - at *some* point that js needs to get built to be efficacious.

**Comment by LuisFRoch** [comment]
@jasongrout the question is for Jlab since sort to speak, plotly updates sometimes are not well received. 
I do get the "--no-build etc." it was just part of the commentary that I follow the detailed instructions.

**Comment by jasongrout** [comment]
> i'd like to know if this version solves that issue and does not break Jlab.

To answer your question as clearly as I can: I don't know how a plotly upgrade will change things for you. That's definitely a question for plotly.

> the question is for Jlab since sort to speak, plotly updates sometimes are not well received.

I'm not sure what you mean by that. We welcome plotly updates. I'm not aware of any incompatibilities. Whether or not a given version of plotly works with a given version of JLab is a question that plotly is better prepared to answer, though.

If it were me, I'd ask on the plotly repo if there were any known problems with upgrading plotly, or I'd just try it in a clean test environment and see for myself.

**Comment by LuisFRoch** [comment]
gotcha @jasongrout thanks for the tips!
