### ISSUE TITLE
labextension install fails when read-only template yarn.lock is copied into staging directory

### ISSUE THREAD

**Issue by MMesch** [jupyterlab/jupyterlab#7525]
## Description

`jupyter labextension install myextension --app-dir=./myapp`

fails with

```
error An unexpected error occurred: "EACCES: permission denied, open '/nix/store/lg2kmn1i3wj0473q0i6vbjbqhvrg5yky-jupyterlab-extended/staging/yarn.lock'"
```

when the template `yarn.lock` file that is included in the base jupyterlab package is readonly. In this case, it seems to be copied over to `./myapp` when the staging directory is populated without setting the appropriate access rights:
https://github.com/jupyterlab/jupyterlab/blob/172e664aa66d8c9be89960c575d24dc4051e7bb9/jupyterlab/commands.py#L1181

This naturally occurs when installing jupyterlab with Nix, where the base install has to be immutable to ensure reproducibility. A simple fix would be to set write access on the copied `yarn.lock` in the staging directory.

## Reproduce

(I can only give approximate steps for a standard conda or pip install because I am using nix to install jupyterlab)

1. install jupyter lab and find the `staging` directory.
2. set `chmod -w yarn.lock` inside of the staging directory
3. go to a temporary directory somewhere else
4. run `jupyter labextension install <<anyextension>> --app-dir=. --debug`

## Expected behavior

Jupyterlab with the extension is built successfully in `app-dir`.

## Context

- Operating System and version: Ubuntu 16.04, Nix package manager
- JupyterLab version: 1.2.2

**Comment by jluttine** [comment]
I opened a PR for nixpkgs to fix it there. Perhaps the patch could be offered to Jupyter Lab too though.

https://github.com/NixOS/nixpkgs/pull/118821

**Comment by jluttine** [comment]
Alright, PR opened: https://github.com/jupyterlab/jupyterlab/pull/10063

**Comment by blink1073** [comment]
Great, thanks @jluttine, I was just about to ask you to do that!  :smile:
