### ISSUE TITLE
add ability to dock output views to sidebar

### ISSUE THREAD

**Issue by kaiaeberli** [jupyterlab/jupyterlab#7533]
Hi!

It would be great to have the ability to dock output views in the left or right sidebar, and maybe even keep those across sessions. One could then assign a shortcut to each output view, a bit like Ctrl+B to hide the sidebar. This would be helpful to debug large data collections where several drill down views are open at the same time, but it is necessary to be able to quickly switch back to the root view.

Does something like this already exist?

**Comment by ian-r-rose** [comment]
Hi @kaiaeberli, something like this does indeed exist: https://github.com/jupyter-widgets/jupyterlab-sidecar

Does that cover what you are asking for?

**Comment by kaiaeberli** [comment]
Thanks - that is very helpful! The only part missing is how to assign a keyboard shortcut to show/hide it.

**Comment by ian-r-rose** [comment]
I suspect that would be fairly straightforward to add to that extension (and may also be a good issue for a new contributor). You may want to open an issue over there.

**Comment by kaiaeberli** [comment]
thanks will do.

**Comment by kaiaeberli** [comment]
Found it: Ctrl+Alt+Shift+C toggles the right sidebar, in which sidecar tabs are docked.
