### ISSUE TITLE
I can't create a new tab

### ISSUE THREAD

**Issue by mamu1232** [jupyterlab/jupyterlab#7536]
## Description
I want to see two files at the same time, but I can't.  
I was able to do this before by dragging a file into the work area or double-click on the file names.   
However, it just shows only one file and doesn't show its filename in the working area, though I can activate the next tab with Ctrl + Shift +].
Could you please help me fix the problem?
![tabs](https://user-images.githubusercontent.com/57478586/69110800-1e345980-0abf-11ea-912e-f1beaa199e40.png)

## Expected behavior
I want to create tabs like this.
![jupyterlab](https://user-images.githubusercontent.com/57478586/69111192-2345d880-0ac0-11ea-96cc-c89b1945cbbb.png)

## Context

- Operating System and version:
Windows 10
- Browser and version:
Firefox 70.0.1(64bit)
- JupyterLab version:
1.2.0

**Comment by jasongrout** [comment]
Go to the view menu and turn off single document mode.

We should add a status bar indicator to make this more discoverable.

**Comment by mamu1232** [comment]
Thank you so much.
Solved the problem.
