### ISSUE TITLE
Execution Time UI

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#7538]
As discussed in https://github.com/jupyterlab/jupyterlab/pull/4161#issuecomment-400687124, no UI was ever decided on for execute time. I am opening this issue to build consensus as to what is to be done so we can build it into lab. For many users, this is a critical missing piece of lab in when migrating from notebook.

To get this discussion started:
Proposal A: Build the execute time extension exactly as it was before. Nothing should be changed for V1. All parameters that were configurable become settings.

![image](https://user-images.githubusercontent.com/1813603/69173026-f3e99880-0acc-11ea-980f-68dbc0782a9f.png)

**Comment by saulshanabrook** [comment]
FYI there is now an open source jupyterlab extension for showing execution timing: https://github.com/deshaw/jupyterlab-execute-time
