### ISSUE TITLE
Read Only 

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [jupyterlab/jupyterlab#7540]
How can we edit an existing .ipynb in Jupyter Lab to be read-only?
More specifically, how can we make specific cells within an existing .ipynb become read-only?

Basically, other users would be able to edit cells that I allow them to (i.e. a cell that specifies an input data file) but all code in other analysis cells can be run but not edited. 

If I can't edit an existing .ipynb file to do this, I don't mind saving a notebook with a different name via  "Save as" if that makes things easier.

**Comment by Alexboiboi** [comment]
Hi @YogiOnBioinformatics 

You just need to add 👍 

```json
{
    "editable": false
}
```
in your cell Metadata.

If you are using Jupyterlab, you can install the [Celltags extension](https://github.com/jupyterlab/jupyterlab-celltags) for ease of metadata editing

Alex-

**Comment by YogiOnBioinformatics** [comment]
Hello @Alexboiboi thank you very much! 

This was so helpful!
