### ISSUE TITLE
Search box cut by next cell in one line displayed JSON

### ISSUE THREAD

**Issue by fabiencelier** [jupyterlab/jupyterlab#7542]
## Description

When displaying a one line JSON the search box is bigger than the displayed json and cut by the next cell.

![cut_search_box](https://user-images.githubusercontent.com/17087544/69257497-705aa500-0bbb-11ea-8428-37dea2a46e64.png)

## Reproduce

Run this in a notebook : 
```
from IPython.display import JSON
JSON({})
```

## Expected behavior

The search should be fully displayed

**Comment by ggbhat** [comment]
Issue can be closed. Fix has provided https://github.com/jupyterlab/jupyterlab/pull/7828

**Comment by fabiencelier** [comment]
Thank you !
