### ISSUE TITLE
Instead of making json view only, couldn't we treat it as a text file to make it editable? 

### ISSUE THREAD

**Issue by bbennett36** [jupyterlab/jupyterlab#7557]
I have a json document in one of the packages that I'm using that I needed to make changes too. Turns out Jupyterlab only lets you view the json. I do like the view functionality and how it makes it easier to view the structure of the json but I feel like we should be able to treat this as a text file to make edits.  
  
Not sure the consequences of doing this. However, this is how the jupyter notebooks seem to handle it so I figured it would be possible.

**Comment by jasongrout** [comment]
> Turns out Jupyterlab only lets you view the json.

If you right-click on the JSON document, you can open it in an editor as a text file.

**Comment by jasongrout** [comment]
Closing as answered. Please comment if you'd like to continue the discussion. Thanks!
