### ISSUE TITLE
Error after uninstalling an extension

### ISSUE THREAD

**Issue by ujhuyz0110** [jupyterlab/jupyterlab#7562]
## Description

I installed an extension `jupyterlab_vim`. After a while, I decided to uninstall it. I did so by clicking `disable` and `uninstall` on the UI. After that, I got the following error on the UI:
```
Error communicating with server extension. Consult the documentation for how to ensure that it is enabled.

Reason given:

Error: 500 (Internal Server Error)
```
and the following error in my terminal:
```python
[E 13:37:21.852 LabApp] Uncaught exception GET /lab/api/extensions?1574804241377 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab/api/extensions?1574804241377', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/usr/local/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 222, in get
        extensions = yield self.manager.list_extensions()
      File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 86, in list_extensions
        build_check_info = _build_check_info(app_options)
      File "/usr/local/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 56, in _build_check_info
        messages = handler.build_check(fast=True)
      File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 760, in build_check
        new_package = self._get_package_template(silent=fast)
      File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 1243, in _get_package_template
        data['dependencies'].pop(item)
    KeyError: 'jupyterlab_vim'
```

## Reproduce

I have not tried to reproduce it. It could probably be reproduced by installing and uninstalling the package `jupyterlab_vim` 

## Expected behavior

None of the errors above should happen.

## Context

- Operating System and version: Mac Mojave 10.13.3
- Browser and version: Firefox 70.0.1
- JupyterLab version: 1.2.3

## Solution (or Quickfix)

I was able to fix the issue by change line 1237 in `jupyterlab/command.py` to the following:
```python
        # Handle uninstalled core extensions.
        for item in self.info['uninstalled_core']:
            if item in jlab['extensions']:
                data['jupyterlab']['extensions'].pop(item)
            elif item in jlab['mimeExtensions']:
                data['jupyterlab']['mimeExtensions'].pop(item)
            # Remove from dependencies as well.
            if item in data['dependencies']:
                data['dependencies'].pop(item)

        return data
```

I am not sure if it is an ideal fix even though the issue went away after the changes. If it is, I could open a PR for it.

**Comment by Azurewyl** [comment]
+1

**Comment by tys1998** [comment]
@Azurewyl 

It works! 🌞 Thanks bro! 🌞
But, everytime I uninstall one extension, I need to redo this. 🤷
Is this a bug or something? 🤷

**Comment by hzfmer** [comment]
> My solution:
> 
> 1. edit share/jupyter/lab/settings/build_config.json ,then delete the key which made KeyError
> 2. jupyter lab build

@Azurewyl, I didn't found this file in my Anaconda directory..

This HTTP 500 Error just broke my Extention Manager, while the Jupyterlab works fine. It is annoying though I can only see "Error: 500 (Internal Server Error)" when I use the web extension manager. 

I tried to reinstall Jupyter through Conda, which doesn't work supprisingly. Any ideas to fix this?

**Comment by blink1073** [comment]
I'm not sure why `jupyterlab_vim` would get picked up as a core extension (I wasn't able to reproduce).  However, I was able to get an error when uninstalling `@jupyterlab/notebook-extension`.  I'll update this code to be more robust.
