### ISSUE TITLE
`npm install` fails with `sh: tsc: command not found`

### ISSUE THREAD

**Issue by bolinfest** [jupyterlab/jupyterlab#7566]
## Description

`npm install` appears to require `tsc` on the `$PATH`.
Ideally the build script would install the TypeScript compiler and use it, as necessary.

## Reproduce

At 78e7bf2d6848fe22f2b59200c832e60f83b6ad22, ran `npm install`. I saw:

```
> @jupyterlab/buildutils@2.0.0-alpha.1 build /Users/mbolin/src/jupyterlab/buildutils
> tsc

sh: tsc: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @jupyterlab/buildutils@2.0.0-alpha.1 build: `tsc`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @jupyterlab/buildutils@2.0.0-alpha.1 build script.
```

This is with:

```
$ npm --version
6.9.0
$ node --version
v10.16.0
```

## Expected behavior

`npm install` should succeed with exit code `0`.

## Context

- macOS mojave
- Browser and version: N/A
- JupyterLab version: N/A

**Comment by bolinfest** [comment]
To try to unblock myself, I ran `npm install -g typescript` and then ran `npm install` for jupyterlab again, but now I get a ton of TypeScript errors. I suspect the newest version of TypeScript is stricter than what your TypeScript code was written with, making it even more important that `npm install` download and run the appropriate version of `tsc`.

**Comment by jasongrout** [comment]
Please follow the contributor instructions and run `jlpm install`

https://github.com/jupyter/notebook/blob/master/CONTRIBUTING.rst

**Comment by jasongrout** [comment]
Sorry, wrong link. Here's the right link: https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md#setting-up-a-development-environment
