### ISSUE TITLE
UX Defect - Center File Icon in Breadcrumbs

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#7575]
## Description
File icon in breadcrumbs is not aligned correctly (too low)
![](https://user-images.githubusercontent.com/22109376/64985270-57f7a280-d879-11e9-8c77-1d5533eaa658.png)
## Reproduce

Open File Browser

## Expected behavior

The icon should be aligned with text

**Comment by jasongrout** [comment]
@telamonian looking at this as part of #7700

**Comment by telamonian** [comment]
fixed in latest version of #7700:

![image](https://user-images.githubusercontent.com/2263641/71695455-2c44ed80-2d80-11ea-8b90-f14cb070ab56.png)
