### ISSUE TITLE
JupyterLab Error

### ISSUE THREAD

**Issue by paolovelove** [jupyterlab/jupyterlab#7592]
I got this error when I run jupyter-lab on my Macbook. 

JupyterLab application assets not found in "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/share/jupyter/lab"
Please run `jupyter lab build` or use a different app directory

However, when I tried `jupyter lab build`, it stated the following error.

[LabBuildApp] Building in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/share/jupyter/lab
An error occured.
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  /tmp/jupyterlab-debug-dstdzs1o.log

**I installed it by using sudo pip install jupyterlab.

**Comment by timkpaine** [comment]
Did you install nodejs like the error said to do?

**Comment by paolovelove** [comment]
Yes, I already have nodejs and npm, but it seems like the jupyterlab doesn't recognize it.

I have following version installed:
jupyter core     : 4.6.1
jupyter-notebook : 6.0.1
qtconsole        : 4.6.0
ipython          : 7.9.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 1.1.4
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

**Comment by paolovelove** [comment]
> Did you install nodejs like the error said to do? You can also try running `jupyter lab --core-mode` to use the assets in the python package.

jupyter lab --core-mode, this works. 

Thanks!

**Comment by timkpaine** [comment]
What is the output of `which node` and `node --version`

**Comment by paolovelove** [comment]
it was at /usr/local/bin/node and version and v13.2.0.

**Comment by paolovelove** [comment]
> Did you install nodejs like the error said to do? You can also try running `jupyter lab --core-mode` to use the assets in the python package ([docs](https://github.com/jupyterlab/jupyterlab/blob/735dffc6ef2cf9f3356f5bd862bb0bbfaec249ac/jupyterlab/labapp.py#L336))

This command was working correctly

**Comment by paolovelove** [comment]
I re-install node and later did brew postinstall node. It fixed the problem.
