### ISSUE TITLE
Dark mode not working in 2.0.0a3

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#7610]
## Description
I was working in 2.0.0a3 dev mode and the toggle for 'Use JupyterLab Dark Theme' isn't working in the command palette or in the settings menu. 

## Reproduce

1. Clone JupyterLab
2. Install and Build.
3. Run `jupyter lab --dev-mode --watch` 

## Expected behavior

I expected the theme to change to the dark theme.

## Context

- Operating System and version: macOS High Sierra 10.13.6
- Browser and version: Version 78.0.3904.108 
- JupyterLab version: 2.0.0a3

**Comment by blink1073** [comment]
I'm seeing this as well, perhaps related to #7147.

**Comment by jtpio** [comment]
This should now be fixed on master (fixed by https://github.com/jupyterlab/jupyterlab/pull/7601).

**Comment by telamonian** [comment]
fixed by #7601
