### ISSUE TITLE
Initialization cell in jupyterlab notebook

### ISSUE THREAD

**Issue by scottwsides** [jupyterlab/jupyterlab#7620]
I'd like to execute a cell in a jupyterlab notebook when notebook is opened/loaded. There are many things about nbextensions online... but it looks as if this is only for the jupyter and not jupyterlab. Did I miss something. Is there a way to make this work in jupyterlab?

**Comment by jasongrout** [comment]
There is no built-in way to automatically execute code when a notebook is opened (there is something of a security risk in executing code automatically without you inspecting it).

That said, it would be possible to write a JupyterLab extension to do this. I don't know if anyone has at this point.

**Comment by scottwsides** [comment]
Thanks for the reply. I certainly admire and respect the JupyterLab team's concerns about security. But there are a few widely requested features that are not implemented because of security issues of which this is one. Perhaps you could implement these features, but they would only be available if a user chose a certain security level in the JupyterLab session (or settings in a config file). That way adventurous developers/users could use these outlaw features like init cells ;-)

**Comment by timkpaine** [comment]
What is the use case? Is it more than convenience?

**Comment by scottwsides** [comment]
There are many use cases for init cells. I'm going to leave it at that... its a common concept. One man's convenience is another necessity... so I'm not sure how to answer that. 

I think having security levels that would allow the brave to implement certain features would be a good general idea to have. Just a thought. I'll close this if you like.

**Comment by jasongrout** [comment]
How comfortable are you in writing an extension to enable this? Then those that want this could install the extension and have it. I've tagged it as an extension idea for whoever is searching for interesting extensions to implement.

**Comment by telamonian** [comment]
I have a standard preamble that I put in the first cell of all my production notebooks, and I used to really want something like this. However, I've come around to thinking that "run on open" is always a Bad Idea. It's literally the same feature that got Microsoft into so much trouble a couple of decades ago with malicious macros that ran when someone opened a word or excel doc.

**Comment by timkpaine** [comment]
@scottwsides I just mean that i've been asked for this feature a million times but its almost always been not the right solution. Here are some examples:

- I want to run the first cell which creates a widget dashboard, then hide the code cells (Voila)
- I always import pandas, so i don't want to do that (ipython's exec_lines)
- My team all have common imports, we don't want to have to write them every time (templates)

**Comment by timkpaine** [comment]
I can imagine that if there was the ability to have a pool of "hot" kernels, it would be convenient to mark the first cell for inclusion into this for faster restart times e.g. here are all my imports to run when you warm up the next kernel.

**Comment by scottwsides** [comment]
> @scottwsides I just mean that i've been asked for this feature a million times but its almost always been not the right solution. Here are some examples:
> 
> * I want to run the first cell which creates a widget dashboard, then hide the code cells (Voila)
> * I always import pandas, so i don't want to do that (ipython's exec_lines)
> * My team all have common imports, we don't want to have to write them every time (templates)

Ah, gotcha.

I have a cell that creates a basic object from which the rest of the cells in a notebook gets its functionality. When executed the cell generates a widget menu from which a user can set parameters. I'd like for that cell to get executed, so a user can see the menu and simply change values from there. 'Saving the widget state' isn't really the same thing (right?)

**Comment by jasongrout** [comment]
> 'Saving the widget state' isn't really the same thing (right?)

Correct - that won't restore the kernel state in the same variables, etc.

**Comment by mlucool** [comment]
While this does not run a specific cell (not good for the dashboard case), ipython startup files can solve some problems:
```
$ cat ~/.ipython/profile_default/startup/README 
This is the IPython startup directory

.py and .ipy files in this directory will be run *prior* to any code or files specified
via the exec_lines or exec_files configurables whenever you load this profile.

Files will be run in lexicographical order, so you can control the execution order of files
with a prefix, e.g.::

    00-first.py
    50-middle.py
    99-last.ipy
```

If you are worried about imports, [pyflyby ](https://github.com/pyflyby/pyflyby) is GREAT.

**Comment by scottwsides** [comment]
mlucool: thanks for the suggestion.

**Comment by foice** [comment]
> @scottwsides I just mean that i've been asked for this feature a million times but its almost always been not the right solution. Here are some examples:
> 
>     * I want to run the first cell which creates a widget dashboard, then hide the code cells (Voila)
> 
>     * I always import pandas, so i don't want to do that (ipython's exec_lines)
> 
>     * My team all have common imports, we don't want to have to write them every time (templates)

Maybe is not the *best* solution in any of these million times you've been asked, but doesn't it say something already the fact that you have been asked a [million+1 times](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1517)?

The capability of running init_cells is part of Jupyter and I think is also very useful. The extension for Jupyter exists already, maybe that helps?

**Comment by foice** [comment]
> @scottwsides I just mean that i've been asked for this feature a million times but its almost always been not the right solution. Here are some examples:
> 
>     * I want to run the first cell which creates a widget dashboard, then hide the code cells (Voila)
> 
>     * I always import pandas, so i don't want to do that (ipython's exec_lines)
> 
>     * My team all have common imports, we don't want to have to write them every time (templates)

Maybe here are two examples that do not fit in the three you mentioned:

- I want to pass to my students/collaborators a notebook (a single file, stricly one, not two) so that they can redo a plot or something or get started with that plot and then walk on their own. This must be one and only one file to minimize the chance that someone is not putting the right material in the right place. So in this case init_cells help the notebook to be `self-contained` with no dependency else than having installed packages via pip if really necessary

- I am developing a new feature in the ipynb and I am not yet ready to move it into my "library.py" file for this notebook. So I am changing and re-evaluating a number of cells in the developement cycle and I want to keep these cells in the current notebook to see them and use the notebook features (i.e. printing, plotting) on them.

In addition, I second @scottwsides , it is a common concept, present in Jupyter and other FrontEnd (e.g. for Wolfram Language). I agree it may not be the shiniest way to code, but it works ...

**Comment by foice** [comment]
> How comfortable are you in writing an extension to enable this? Then those that want this could install the extension and have it. I've tagged it as an extension idea for whoever is searching for interesting extensions to implement.

Has anyone written an "how to" that you would recommend? (Currently looking at [this](https://towardsdatascience.com/how-to-write-a-jupyter-notebook-extension-a63f9578a38c) but not sure I ever knew enough JavaScript ...

**Comment by foice** [comment]
I am looking at the [javascript of the jupyter extension](https://raw.githubusercontent.com/ipython-contrib/jupyter_contrib_nbextensions/master/src/jupyter_contrib_nbextensions/nbextensions/init_cell/main.js) that does exactly what discussed in this issue. I fail to see what would be wrong in using this code for a _JupyterLab_ extension. The logic seems pretty solid and there seems to be maybe just the need to switch to appropriate functions e.g. to put buttons in the toolbar and things like that. What am I missing?

**Comment by bollwyvl** [comment]
I can recommend the [official documentation](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html) which have pointers to tutorials and tooling. With tools like [cookiecutter](https://github.com/cookiecutter/cookiecutter), the overhead is relatively low to get to the one _actual_ `.ts` file you'd probably need to implement this.

**Comment by bollwyvl** [comment]
There is also the [extension-examples](https://github.com/jupyterlab/extension-examples) repository, which has a number of patterns.

**Comment by scottwsides** [comment]
Thanks! I'll try those out
*Dr. Scott W Sides*
(303) 718-7028

**Comment by GF-Huang** [comment]
I need to run the following code every notebook, This is so tiring.

```py
import jedi
jedi.settings.case_insensitive_completion = True
```

**Comment by schmidi314** [comment]
Hi all,

I had the same issue. Coming from the Mathematica world I am used to having initialization cells. 

But I think one can look at this whole init cell ssue from a broader perspective, which is why I have written a jupyterlab_scenes plugin. It allows to define various scenes (subsets of code cells), run them individually and also use a scene as initialization scene.


![scenes_init](https://user-images.githubusercontent.com/74381262/143845005-5705330f-d5ff-45b7-a780-e30caeedd1c3.gif)

A first version is available here:
[https://github.com/schmidi314/jupyterlab-scenes](https://github.com/schmidi314/jupyterlab-scenes)

**Comment by foice** [comment]
`https://github.com/schmidi314/jupyterlab-scenes` seems very promising! and I can see you have not only implemented a workflow that makes sense to someone coming from Mathematica, you made it better!
Right now I cannot test it, but I wanted to send my encouragement.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/setting-initialization-cells-for-jupyterlab/13345/2

**Comment by aaszodi** [comment]
> I had the same issue. Coming from the Mathematica world I am used to having initialization cells.

Me too. I think the security argument is only partially valid. My use case for init cells: I share notebooks with my students and these need some setup (configuration, data files etc.) Very easy to solve with init cells, a bit more convoluted to ask the students to run the cells at the beginning of the notebook. Inevitably some of those will forget and then cry for help.

> A first version is available here: https://github.com/schmidi314/jupyterlab-scenes

It works, I just tried it out. Many thanks!

**Comment by scottwsides** [comment]
So I've been using jupyterlab-scenes for this issue for a while now and it works and is amazing. I'll close issue?
