### ISSUE TITLE
Code consoles should be main area widgets.

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#7624]
The `console-extension` exports a tracker that keeps track of `ConsolePanel` instances, but this means that consoles do not have a `toolbar` and `content` like most other main area widgets.

This means that plugins (e.g. `@jupyterlab/debugger`) that want to add toolbar buttons don't have a clean way of adding toolbar buttons to both notebooks *and* consoles.

I propose we fix this and since it is a backward-incompatible API change, I propose updating this before 2.0.

**Comment by jasongrout** [comment]
+1 to having console be wrapped in a MainAreaWidget.

**Comment by KsavinN** [comment]
Hi, I will try resolve this :)

**Comment by afshin** [comment]
Thanks!

**Comment by vidartf** [comment]
Closed by lined PR.
