### ISSUE TITLE
Workaround for saving notebooks using a command

### ISSUE THREAD

**Issue by jlmanaloto** [jupyterlab/jupyterlab#7627]
Jupyterlab doesn't seem to support saving a notebook when the following is run:

```
from IPython.display import display, Javascript
display(Javascript('IPython.notebook.save_checkpoint();'))
```

Are there any workaround in order to trigger a save after running a cell?

**Comment by jasongrout** [comment]
> Jupyterlab doesn't seem to support saving a notebook when the following is run:
> 
> ```
> from IPython.display import display, Javascript
> display(Javascript('IPython.notebook.save_checkpoint();'))
> ```

Correct, that javascript code is very specific to the classic notebook, and won't work in other frontends.

> Are there any workaround in order to trigger a save after running a cell?

The way to do this in JupyterLab is to write a jupyterlab extension, which could listen to cell executions and trigger a save.

**Comment by jlmanaloto** [comment]
@jasongrout alright thanks!
