### ISSUE TITLE
bump celltags to 1.0.0

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7629]
Cell tags was merged into core in #7407. We decided around the 1.0 release that anything in core should be at least 1.0.0 so that we could release patch versions of those libraries with patch versions of jlab. Hence, I think we should bump the version of celltags to at least 1.0.0.

**Comment by telamonian** [comment]
Would it make sense to bump celltags straight to `2.0.0`? The more in lockstep all of the package versions are, the easier it is to get the versions right when defining dependencies in a `package.json`. For example, when writing an extension that targets a particular version of jlab core, I often find it pretty confusing to remember the special versioning rules for `@jupyterlab/coreutils` and `@jupyterlab/services`.

**Comment by jasongrout** [comment]
I'm okay with either one. Note that the minor versions are already off, and certainly patch numbers can be off.

**Comment by telamonian** [comment]
I'll put a PR for this on my todo list
