### ISSUE TITLE
JupyterLab does not start with a Kernel?

### ISSUE THREAD

**Issue by etjkai** [jupyterlab/jupyterlab#7632]
## Description

I am unable to get JupyterLab's Kernel to be connected to Python, even though it did so a couple of hours back. 

https://i.imgur.com/q1kaCHD.png

## Reproduce

1. Go to cmd
2. Type in "jupyter lab"

## Expected behavior

JupyterLab does not start with Kernel. Even trying to select Python 3 does not work.

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome
- JupyterLab version:Version 1.2.4

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
$PATH:
        c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pywin32_system32
        c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\pywin32_system32
        C:\Program Files (x86)\Intel\iCLS Client\
        C:\Program Files\Intel\iCLS Client\
        C:\Windows\System32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0\
        C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
        C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
        C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0\
        C:\WINDOWS\System32\OpenSSH\
        C:\Users\User\Desktop\chromedriver_win32\chromedriver.exe
        C:\Users\User\AppData\Local\Programs\Python\Python37-32
        C:\Users\User\Documents\Python Scripts
        C:\Users\User\Desktop\chromedriver_win32
        C:\Program Files\Git\cmd
        C:\Users\User\AppData\Local\Programs\Python\Python37-32\Scripts\
        C:\Users\User\AppData\Local\Programs\Python\Python37-32\
        C:\Users\User\AppData\Local\Microsoft\WindowsApps
        C:\Users\User\AppData\Local\Programs\Python\Python37-32\python.exe
        C:\Program Files\heroku\bin

sys.path:
        C:\Users\User\AppData\Local\Programs\Python\Python37-32\Scripts\jupyter-troubleshoot.EXE
        c:\users\user\appdata\local\programs\python\python37-32\python37.zip
        c:\users\user\appdata\local\programs\python\python37-32\DLLs
        c:\users\user\appdata\local\programs\python\python37-32\lib
        c:\users\user\appdata\local\programs\python\python37-32
        C:\Users\User\AppData\Roaming\Python\Python37\site-packages
        c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages
        c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\win32
        c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\win32\lib
        c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\Pythonwin

sys.executable:
        c:\users\user\appdata\local\programs\python\python37-32\python.exe

sys.version:
        3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)]

platform.platform():
        Windows-10-10.0.18362-SP0

where jupyter:
        C:\Users\User\AppData\Local\Programs\Python\Python37-32\Scripts\jupyter.exe

pip list:
        Package              Version
        -------------------- ----------
        altgraph             0.16.1
        attrs                19.3.0
        backcall             0.1.0
        bleach               3.1.0
        certifi              2019.9.11
        chardet              3.0.4
        Click                7.0
        colorama             0.4.3
        colour               0.1.5
        cycler               0.10.0
        dash                 1.7.0
        dash-core-components 1.6.0
        dash-html-components 1.0.2
        dash-renderer        1.2.2
        dash-table           4.5.1
        decorator            4.4.1
        defusedxml           0.6.0
        Django               2.2.7
        entrypoints          0.3
        et-xmlfile           1.0.1
        Flask                1.1.1
        Flask-Compress       1.4.0
        future               0.18.0
        idna                 2.8
        importlib-metadata   1.3.0
        ipykernel            5.1.3
        ipython              7.10.2
        ipython-genutils     0.2.0
        itsdangerous         1.1.0
        jdcal                1.4.1
        jedi                 0.15.1
        Jinja2               2.10.3
        json5                0.8.5
        jsonschema           3.2.0
        jupyter-client       5.3.4
        jupyter-core         4.6.1
        jupyterlab           1.2.4
        jupyterlab-server    1.0.6
        kiwisolver           1.0.1
        lxml                 4.2.4
        MarkupSafe           1.1.1
        matplotlib           2.2.3
        mistune              0.8.4
        more-itertools       8.0.2
        nbconvert            5.6.1
        nbformat             4.4.0
        notebook             6.0.2
        numpy                1.15.1
        openpyxl             3.0.2
        pandas               0.25.1
        pandocfilters        1.4.2
        parso                0.5.2
        pefile               2019.4.18
        pick                 0.6.4
        pickleshare          0.7.5
        pip                  19.3.1
        pipenv               2018.11.26
        plotly               4.4.1
        prometheus-client    0.7.1
        prompt-toolkit       3.0.2
        Pygments             2.4.2
        PyInquirer           1.0.3
        PyInstaller          3.5
        pyparsing            2.2.0
        pyrsistent           0.15.6
        python-dateutil      2.7.3
        python-docx          0.8.6
        pytz                 2018.5
        pywin32              227
        pywin32-ctypes       0.2.0
        pywinpty             0.5.7
        pyzmq                18.1.1
        regex                2019.11.1
        requests             2.22.0
        retrying             1.3.3
        scipy                1.3.3
        selenium             3.141.0
        Send2Trash           1.5.0
        setuptools           39.0.1
        six                  1.11.0
        sqlparse             0.3.0
        StyleFrame           2.0.5
        terminado            0.8.3
        testpath             0.4.4
        tornado              6.0.3
        traitlets            4.3.3
        urllib3              1.25.6
        virtualenv           16.7.6
        virtualenv-clone     0.5.3
        wcwidth              0.1.7
        webencodings         0.5.1
        Werkzeug             0.16.0
        wheel                0.31.1
        windows-curses       2.1.0
        xlrd                 1.2.0
        zipp                 0.6.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.

[I 11:09:11.037 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\User\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\User\Anaconda3\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\User\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\User\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 24, in <module>
    import zmq
  File "C:\Users\User\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\User\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\User\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\User\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\User\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\User\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by telamonian** [comment]
You don't have a JupyterLab problem, you have a Python problem. The real issue is buried in the command line output you posted:

> _File "C:\Users\User\Anaconda3\lib\site-packages\zmq\backend\cython__init__.py", line 6, in 
> 
> from . import (constants, error, message, context,
> 
> ImportError: DLL load failed: The specified module could not be found.

So there's something wrong with one of your Python packages, `zmq`. It seems to be missing some pieces.

My advice would be to try uninstalling and reinstalling the `zmq` package. It looks like you're using conda to manage your Python install, which I'm not at all familiar with, but I assume it has some way to do this.
