### ISSUE TITLE
Notebook Tools panel lifecycle

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#7643]
When the notebook widget has the focus and is then disposed, the notebook tools are removed from the left area:

![notebook-tools-lifecycle](https://user-images.githubusercontent.com/591645/71081942-7d55be80-2190-11ea-9745-8187b062898c.gif)

But when the notebook widget doesn't have the focus and is then disposed, they are not removed:

![notebook-tools-lifecycle2](https://user-images.githubusercontent.com/591645/71082009-a24a3180-2190-11ea-9890-f8caf671ae90.gif)

It would be nice for the behavior to be coherent for the different cases.

Also if the tools are accessed after the notebook has been closed, adding a tag will throw an error in the dev tools console:

![notebook-tools-lifecycle](https://user-images.githubusercontent.com/591645/71082700-d07c4100-2191-11ea-90a0-2f0b0ca0468c.gif)

Tested with JupyterLab 1.2.1 and also with the current `master` branch.

**Comment by jtpio** [comment]
This is something that is relevant to other third-party extensions that rely on the `tracker.currentChanged` signal.

After some investigation it looks like the `pool.current` is set to `null` here:

https://github.com/jupyterlab/jupyterlab/blob/6461d0bb6e51b44a533e96177de85f769995f2c8/packages/apputils/src/widgettracker.ts#L130

But in the setter since `obj` is `null`, the `currentChanged` signal will not be emitted:

https://github.com/jupyterlab/jupyterlab/blob/6461d0bb6e51b44a533e96177de85f769995f2c8/packages/coreutils/src/restorablepool.ts#L63-L66

It would actually be very useful to have this signal emitted when the number of widgets in the tracker goes down to 0 (and `currentWidget` becomes `null`).

**Comment by jtpio** [comment]
Unless there is another way to detect when `tracker.size` becomes `0`?

**Comment by jasongrout** [comment]
> It would actually be very useful to have this signal emitted when the number of widgets in the tracker goes down to 0 (and `currentWidget` becomes `null`).

+1 to having the signal be a widget OR null, and having it trigger when it goes to null. I think that is really important (some people may use the currentWidget signal to switch things off of the current widget, and they won't know when that widget goes away if the signal is not emitted when the widget becomes null).
