### ISSUE TITLE
Simplify selecting no kernel when notebook kernel is not available

### ISSUE THREAD

**Issue by lresende** [jupyterlab/jupyterlab#7646]
## Description

When a notebook is open, and the specified notebook kernel is not available, JupyterLab provides a dialog box to enable the user to select a new kernel to be used. Having said that, there are times we just want to open the notebook to check its contents without a kernel and the current user experience requires many steps for you to accomplish the `no kernel` selection. 

![jupyterlab-select-notebook-kernel-no-kernel](https://user-images.githubusercontent.com/382917/71100204-74052b80-2169-11ea-854a-235f09041825.gif)

Note that there is no cancel option on the dialog box above, so your only option is to navigate and select `no kernel` and press select. 

I would like to propose that, in this particular scenario, we could enable a cancel button labeled `no kernel` to simplify the user experience and enable notebook visualization with no kernels accomplishable in one click.

![jupyterlab-select-notebook-kernel-updated](https://user-images.githubusercontent.com/382917/71100407-d1997800-2169-11ea-8140-c59198bedba0.gif)

**Comment by jasongrout** [comment]
I think that makes UX sense.
