### ISSUE TITLE
Not change currentWidget for console properly

### ISSUE THREAD

**Issue by KsavinN** [jupyterlab/jupyterlab#7648]
## Description

during create another console and switch back current widget it still points to the new console, not focused. 

## Reproduce
![consoleIssue](https://user-images.githubusercontent.com/34033913/71103297-2bc22980-21ba-11ea-8b3b-99ec031361f3.gif)

**Comment by jasongrout** [comment]
Perhaps this is related to #7641?

**Comment by jasongrout** [comment]
I also wonder if perhaps this might be fixed by https://github.com/jupyterlab/jupyterlab/pull/7645 - wrapping the console in a main area widget takes care of some standardized focusing behaviors.

**Comment by jasongrout** [comment]
Your screenshot is cut off so we can't see the indicator on the tab. Is the blue line indicator on the tab switching appropriately?

**Comment by KsavinN** [comment]
![anotherGif](https://user-images.githubusercontent.com/34033913/71109441-7c8b4f80-21c5-11ea-9ed1-f11c44965b2c.gif)

As you @jasongrout mention its related with #7645. Could you or someone else assing me to this issue, cause I don't have privileges. And I hope that I will try to fix that as fast as I can :)

**Comment by jasongrout** [comment]
Thanks for working on this!
