### ISSUE TITLE
Nested format string variables cause extra tab(s) on next line in current cell

### ISSUE THREAD

**Issue by gessha** [jupyterlab/jupyterlab#7649]
Jupyter version: 4.4.0
Jupyter lab version: 0.35.4

Issue: when I use nested variables in a format string, there's an extra tab(s) added to the next line of the cell instead of matching the tab space of the previous line. 

Code reproduction example:
```
a = 4
b = 5
string = f"{a:0{b}d}"
            # start of next line
```

instead of the desired output:
```
a = 4
b = 5
string = f"{a:0{b}d}"
# start of next line
```
I tried searching for proper issue formatting but I couldn't find a template and I also searched for this issue but I also couldn't find anything related. 

Is this a known issue?

**Comment by vidartf** [comment]
I think this was a know issue in lab 0.35. Can you try 1.x ?

**Comment by dLamSlo8** [comment]
I just tried this on 1.2.6 and it seems to be working appropriately. Should we close this issue?

**Comment by jasongrout** [comment]
Great, thanks for testing!
