### ISSUE TITLE
Contribution ads on Stackoverflow.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#765]
I don't know if you have seen this:

http://meta.stackoverflow.com/questions/327559/open-source-advertising-2h-2016

Basically, StackOverflow is offering one of the add area for open source project to make a "call to contributors". I was wondering if you thought it would be a nice things for JupyterLab (and/or Jupyter in general).

They redo it every 6 month apparently, so no pressure.

**Comment by ellisonbg** [comment]
That is cool, would love to see what others think about this options. I don't personally ever use SO, so I feel less than qualified to comment.

**Comment by jasongrout** [comment]
If it's not hard to design a logo, it probably doesn't hurt. We've entered it several times for Sage, but I don't remember hearing of any success (not sure if we made the cutoff either...)
