### ISSUE TITLE
RuntimeError: npm dependencies failed to install - Proxy & Private npm registry issues

### ISSUE THREAD

**Issue by BlueCog** [jupyterlab/jupyterlab#7660]
##  Description

When trying to activate a JupyterLab extension, for example jupyterlab-manager by running the following command:

`jupyter labextension install '@jupyter-widgets/jupyterlab-manager@^1.1'`

I'm getting a `RuntimeError: npm dependencies failed to install` error. 

## Reproduce

Reproducing is a bit complex due our environment. But i'll try to explain:

Environment: OpenShift
Based on:  https://github.com/jupyter-on-openshift/jupyter-notebooks/tree/develop/minimal-notebook
Ref: 2.5.1.

The environment is behind an Proxy
The environment has a private NPM & PIP repository
Proxy settings are being set by using environment variables: HTTPS_PROXY, npm_config_registry, PIP_CONFIG_FILE.

## Troubleshooting

After running the command with a `--debug`: `jupyter labextension install '@jupyter-widgets/jupyterlab-manager@^1.1'` I found out that Yarn is used to install npm dependencies. 

Yarn seems not to be setting the npm config environment variables (1). So I think Yarn is depending on the default (public) NPM registry. Which is not reachable from our environment.

## Expected behavior

I'll be expecting to be able to set a Yarn proxy or registry by setting:
--proxy <host>
--https-proxy <host>
--registry <url>                    

preferably via environment variables like npm (1) and because this is an docker environment.

Something like:
`ret = self._run(['node', YARN_PATH, 'install', '--proxy NPM_CONFIG_PROXY' , '--https-proxy NPM_CONFIG_HTTPS-PROXY', '--registry NPM_CONFIG_REGISTRY', '--non-interactive'], cwd=staging)`

From te source code:
https://github.com/jupyterlab/jupyterlab/blob/5e68c8aa72f2f04a036b06dafe7029995e496d06/jupyterlab/commands.py#L673

## Context

OpenShift
RHEL based image
notebook==6.0.2
jupyterhub==1.0.0
jupyterlab==1.2.3
jupyter_kernel_gateway==2.4.0

(1) https://docs.npmjs.com/misc/config#environment-variables

**Comment by BlueCog** [comment]
Hi all,

_Please let me know if I need to add another ticket, or on how to add (tag users?) an request to change this._

After some extensive troubleshooting we noted that event adding config files (or flags) to configure private repositories or proxy the build is still failing.

We noted that the public repository is hard coded in yarn.lock (https://github.com/jupyterlab/jupyterlab/blob/5e68c8aa72f2f04a036b06dafe7029995e496d06/jupyterlab/staging/yarn.lock)

It seems that in Yarn version 2 this would be possible to override, but not in older Yarn versions (that Jupyterlab is using). So our temporary solution for now is to change this URL's in the yarn.lock file to our private repostiory.

Tips on automation (we use OpenShift):

- Command in assemble script: sed -i -e "s#<public repo>#<private repo>#g" /opt/app-root/lib/python3.6/site-packages/jupyterlab/staging/yarn.lock

- Or changing the yarn.lock and adding it as an configmap in the buildconfig

**Comment by vidartf** [comment]
This should be fixed e.g. with https://github.com/jupyterlab/jupyterlab/pull/7109. You will need to config the yarn registry, and jupyterlab should pick that up and use that (note you might also need the npm registry to be configured). When lab picks that up, it will overwrite the registry values in the lockfile.

**Comment by fcollonval** [comment]
I want to emphasize here too that setting the proxy or the registry to specific target are a matter of `npm` **and** `yarn` configurations not JupyterLab (it just uses **both** tools).

> Since #7109, JupyterLab does not make any assumptions on the registry. And it will replace the default registry in the shipped *yarn.lock* file with the one specified as yarn configuration.
