### ISSUE TITLE
MemoryUsage statusbar feature doesn't understand Prometheus metrics shape

### ISSUE THREAD

**Issue by bentkibler** [jupyterlab/jupyterlab#7663]
I'm trying to get aggregate memory usage reporting within JupyterLab, using as many built-in features as possible.  The goal is to alert users when their total memory usage is reaching the limit of their docker container (spawned by JupyterHub).  

For legacy notebooks (not in lab), we're using Tommassino's excellent [fork of nbresuse](https://github.com/yuvipanda/nbresuse/pull/22), which displays current memory and limits at the top of a notebook view, based on the Prometheus metrics data.  This server extension contributes aggregate memory usage to Prometheus at exactly the correct level for us.

For JupyterLab, the [MemoryUsage ](https://github.com/jupyterlab/jupyterlab/blob/master/packages/statusbar/src/defaults/memoryUsage.tsx) statusbar component is exactly what we want for a UI, but it expects /metrics to come from nbresuse, not the new Prometheus metrics endpoint.  Related issue #6076 was about fatal errors, but that issue was closed when the errors went away, leaving the widget unusable.

It seems like we need two pieces of work to solve this:  1) a notebook server extension to contribute aggregate memory usage along with memory limits (e.g. MEM_LIMIT and/or ulimit) to Prometheus endpoint, and 2) change MemoryUsage widget to expect Prometheus shape.  And then, Toast Notifications #6389 can eventually be used to warn users when mem usage approaches the limit.

Is anyone working on integrating MemoryUsage with Prometheus for this scenario?

**Comment by vidartf** [comment]
> Is anyone working on integrating MemoryUsage with Prometheus for this scenario?

I think you can assume not, if you want to contribute this 😃

**Comment by krinsman** [comment]
xref: https://github.com/yuvipanda/nbresuse/issues/17
https://github.com/yuvipanda/nbresuse/pull/22

**Comment by jasongrout** [comment]
Note that in 3.0, we've removed the memory usage status bar item in https://github.com/jupyterlab/jupyterlab/pull/9386 and moved it to the https://github.com/jupyter-server/jupyter-resource-usage repo. If you still want to work on this, can you open this in that repo?
