### ISSUE TITLE
Failed loading settings - display error ?

### ISSUE THREAD

**Issue by kklocker** [jupyterlab/jupyterlab#7668]
Hi, i have encountered a problem when installing jupyterlab in conda envs. The jupyter lab does not display properly (see screenshot), but the notebooks do.

In short, this is what the jupyter lab window looks like in the browser: 

![image](https://user-images.githubusercontent.com/25065744/71262412-e92a5980-233f-11ea-99f3-aeef2b5e6b29.png)

`conda install node` fixes the error message in the console log about node, but not the settings loading. (see console output below)

## Reproduce
I reproduce the error by this procedure,

```[bash]
conda create -n myenv jupyter
conda activate myenv
conda install -c conda-forge jupyterlab
```

but i have tried many different methods for fixing, and filing this as a error is a last resort. 

<details><summary>Troubleshoot Output</summary>
<pre>
(myenv) C:\Users\myusername>jupyter troubleshoot
$PATH:
        C:\Users\myusername\Anaconda3\envs\myenv\lib\site-packages\pywin32_system32
        C:\Users\myusername\Anaconda3\envs\myenv\lib\site-packages\pywin32_system32
        C:\Users\myusername\Anaconda3\envs\myenv
        C:\Users\myusername\Anaconda3\envs\myenv\Library\mingw-w64\bin
        C:\Users\myusername\Anaconda3\envs\myenv\Library\usr\bin
        C:\Users\myusername\Anaconda3\envs\myenv\Library\bin
        C:\Users\myusername\Anaconda3\envs\myenv\Scripts
        C:\Users\myusername\Anaconda3\envs\myenv\bin
        C:\Users\myusername\Anaconda3\condabin
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0
        C:\WINDOWS\System32\OpenSSH
        C:\Program Files\Git\cmd
        C:\Users\myusername\AppData\Local\Microsoft\WindowsApps
        .

sys.path:
        C:\Users\myusername\Anaconda3\envs\myenv\Scripts
        C:\Users\myusername\Anaconda3\envs\myenv\python37.zip
        C:\Users\myusername\Anaconda3\envs\myenv\DLLs
        C:\Users\myusername\Anaconda3\envs\myenv\lib
        C:\Users\myusername\Anaconda3\envs\myenv
        C:\Users\myusername\Anaconda3\envs\myenv\lib\site-packages
        C:\Users\myusername\Anaconda3\envs\myenv\lib\site-packages\win32
        C:\Users\myusername\Anaconda3\envs\myenv\lib\site-packages\win32\lib
        C:\Users\myusername\Anaconda3\envs\myenv\lib\site-packages\Pythonwin

sys.executable:
        C:\Users\myusername\Anaconda3\envs\myenv\python.exe

sys.version:
        3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.18362-SP0

where jupyter:
        C:\Users\myusername\Anaconda3\envs\myenv\Scripts\jupyter.exe

pip list:
        Package            Version
        ------------------ -------------------
        attrs              19.3.0
        backcall           0.1.0
        bleach             3.1.0
        certifi            2019.11.28
        colorama           0.4.3
        decorator          4.4.1
        defusedxml         0.6.0
        entrypoints        0.3
        importlib-metadata 1.3.0
        ipykernel          5.1.3
        ipython            7.10.2
        ipython-genutils   0.2.0
        ipywidgets         7.5.1
        jedi               0.15.1
        Jinja2             2.10.3
        json5              0.8.5
        jsonschema         3.2.0
        jupyter            1.0.0
        jupyter-client     5.3.4
        jupyter-console    5.2.0
        jupyter-core       4.6.1
        jupyterlab         1.2.4
        jupyterlab-server  1.0.6
        MarkupSafe         1.1.1
        mistune            0.8.4
        more-itertools     8.0.2
        nbconvert          5.6.1
        nbformat           4.4.0
        notebook           6.0.2
        pandocfilters      1.4.2
        parso              0.5.2
        pickleshare        0.7.5
        pip                19.3.1
        prometheus-client  0.7.1
        prompt-toolkit     3.0.2
        Pygments           2.5.2
        pyrsistent         0.15.6
        python-dateutil    2.8.1
        pywin32            227
        pywinpty           0.5.7
        pyzmq              18.1.0
        qtconsole          4.6.0
        Send2Trash         1.5.0
        setuptools         42.0.2.post20191203
        six                1.13.0
        terminado          0.8.3
        testpath           0.4.4
        tornado            6.0.3
        traitlets          4.3.3
        wcwidth            0.1.7
        webencodings       0.5.1
        wheel              0.33.6
        widgetsnbextension 3.5.1
        wincertstore       0.2
        zipp               0.6.0</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
(myenv) C:\Users\myusername>jupyter lab --debug
[D 16:01:08.368 LabApp] Searching ['C:\\Users\\myusername', 'C:\\Users\\myusername\\.jupyter', 'C:\\Users\\myusername\\Anaconda3\\envs\\myenv\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 16:01:08.371 LabApp] Looking for jupyter_config in C:\ProgramData\jupyter
[D 16:01:08.371 LabApp] Looking for jupyter_config in C:\Users\myusername\Anaconda3\envs\myenv\etc\jupyter
[D 16:01:08.371 LabApp] Looking for jupyter_config in C:\Users\myusername\.jupyter
[D 16:01:08.372 LabApp] Looking for jupyter_config in C:\Users\myusername
[D 16:01:08.373 LabApp] Looking for jupyter_notebook_config in C:\ProgramData\jupyter
[D 16:01:08.374 LabApp] Looking for jupyter_notebook_config in C:\Users\myusername\Anaconda3\envs\myenv\etc\jupyter
[D 16:01:08.374 LabApp] Looking for jupyter_notebook_config in C:\Users\myusername\.jupyter
[D 16:01:08.374 LabApp] Looking for jupyter_notebook_config in C:\Users\myusername
[D 16:01:08.375 LabApp] Ignoring min_open_files_limit because the limit cannot be adjusted (for example, on Windows)
[D 16:01:08.378 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\ProgramData\jupyter\jupyter_notebook_config.json
[D 16:01:08.381 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\myusername\Anaconda3\envs\myenv\etc\jupyter\jupyter_notebook_config.d\jupyterlab.json
        C:\Users\myusername\Anaconda3\envs\myenv\etc\jupyter\jupyter_notebook_config.json
[D 16:01:08.385 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\myusername\.jupyter\jupyter_notebook_config.json
[I 16:01:08.820 LabApp] JupyterLab extension loaded from C:\Users\myusername\Anaconda3\envs\myenv\lib\site-packages\jupyterlab
[I 16:01:08.832 LabApp] JupyterLab application directory is C:\Users\myusername\Anaconda3\envs\myenv\share\jupyter\lab
[D 16:01:08.835 LabApp] NodeJS was not found. Yarn user configuration is ignored.
[I 16:01:08.849 LabApp] Serving notebooks from local directory: C:\Users\myusername
[I 16:01:08.849 LabApp] The Jupyter Notebook is running at:
[I 16:01:08.850 LabApp] http://localhost:8888/?token=cb23eb6dd7cd471ed9dc3a91a82f306232ca13b0d52503ac
[I 16:01:08.856 LabApp]  or http://127.0.0.1:8888/?token=cb23eb6dd7cd471ed9dc3a91a82f306232ca13b0d52503ac
[I 16:01:08.858 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:01:08.924 LabApp]

</pre>
</details>

**Comment by vidartf** [comment]
Try running `jupyter lab clean` and then `jupyter lab build`. Are there any errors in the build step? If so, can you share the log file (or run with the `--debug` flag to see debug info directly in console).

**Comment by kklocker** [comment]
> Try running `jupyter lab clean` and then `jupyter lab build`. Are there any errors in the build step? If so, can you share the log file (or run with the `--debug` flag to see debug info directly in console).

I tried building, but got some errors. Here is the command line output:
<details><summary>Command Line Output</summary>
[LabBuildApp] Building in C:\Users\KarlKristian\Anaconda3\envs\myenv\share\jupyter\lab
[LabBuildApp] NodeJS was not found. Yarn user configuration is ignored.
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "C:\Users\KarlKristian\Anaconda3\envs\myenv\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "C:\Users\KarlKristian\Anaconda3\envs\myenv\lib\site-packages\jupyterlab\labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "C:\Users\KarlKristian\Anaconda3\envs\myenv\lib\site-packages\jupyterlab\commands.py", line 456, in build
    _node_check(app_options.logger)

[LabBuildApp]   File "C:\Users\KarlKristian\Anaconda3\envs\myenv\lib\site-packages\jupyterlab\commands.py", line 1748, in _node_check
    node = which('node')

[LabBuildApp]   File "C:\Users\KarlKristian\Anaconda3\envs\myenv\lib\site-packages\jupyterlab_server\process.py", line 59, in which
    raise ValueError(msg)

[LabBuildApp] ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

[LabBuildApp] Exiting application: JupyterLab

</pre>
</details>
<pre>

**Comment by vidartf** [comment]
The errors say that `node` could not be found. Did you install it in your conda env?

**Comment by kklocker** [comment]
So i ran 
`conda install nodejs` and tried building again (after cleaning). It didn't work, it is still the same problem.
<details><summary>Command Line Output</summary>
<pre>
(myenv) C:\Users\KarlKristian>jupyter lab build --debug
[LabBuildApp] Searching ['C:\\Users\\KarlKristian', 'C:\\Users\\KarlKristian\\.jupyter', 'C:\\Users\\KarlKristian\\Anaconda3\\envs\\myenv\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[LabBuildApp] Looking for jupyter_config in C:\ProgramData\jupyter
[LabBuildApp] Looking for jupyter_config in C:\Users\KarlKristian\Anaconda3\envs\myenv\etc\jupyter
[LabBuildApp] Looking for jupyter_config in C:\Users\KarlKristian\.jupyter
[LabBuildApp] Looking for jupyter_config in C:\Users\KarlKristian
[LabBuildApp] Looking for JupyterLab_config in C:\ProgramData\jupyter
[LabBuildApp] Looking for JupyterLab_config in C:\Users\KarlKristian\Anaconda3\envs\myenv\etc\jupyter
[LabBuildApp] Looking for JupyterLab_config in C:\Users\KarlKristian\.jupyter
[LabBuildApp] Looking for JupyterLab_config in C:\Users\KarlKristian
[LabBuildApp] JupyterLab 1.2.4
[LabBuildApp] Building in C:\Users\KarlKristian\Anaconda3\envs\myenv\share\jupyter\lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v10.13.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node C:\Users\KarlKristian\Anaconda3\envs\myenv\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
/[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Lockfile has incorrect entry for "@jupyterlab/nbconvert-css@~0.3.4". Ignoring it.
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 43.59s.

[LabBuildApp] > node C:\Users\KarlKristian\Anaconda3\envs\myenv\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer
/[LabBuildApp] yarn run v1.15.2
$ C:\Users\KarlKristian\Anaconda3\envs\myenv\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer
Done in 0.54s.

[LabBuildApp] > node C:\Users\KarlKristian\Anaconda3\envs\myenv\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
/[LabBuildApp] yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
Hash: 88a4b74e073060cb03a50cfc236e634b2f79ff7b4caa275dffc36e817080
Version: webpack 4.41.2
Child
    Hash: 88a4b74e073060cb03a5
    Time: 47704ms
    Built at: 2020-01-15 10:03:43
                                       Asset      Size  Chunks                                Chunk Names
                   2.9dc0997e8e8efbaac836.js   448 KiB       2  [emitted] [immutable]  [big]
               2.9dc0997e8e8efbaac836.js.map  1.34 MiB       2  [emitted] [dev]
                   3.5151c3a4c207bb7bd928.js   222 KiB       3  [emitted] [immutable]
               3.5151c3a4c207bb7bd928.js.map   711 KiB       3  [emitted] [dev]
                   4.3c35e5e107907f8e2970.js   751 KiB       4  [emitted] [immutable]  [big]
               4.3c35e5e107907f8e2970.js.map   1.8 MiB       4  [emitted] [dev]
                   5.bebab39f4cb7d3984f88.js   721 KiB       5  [emitted] [immutable]  [big]
               5.bebab39f4cb7d3984f88.js.map  1.75 MiB       5  [emitted] [dev]
                   6.f3c7cbae44163e4f1184.js  81.5 KiB       6  [emitted] [immutable]
               6.f3c7cbae44163e4f1184.js.map   335 KiB       6  [emitted] [dev]
        674f50d287a8c48dc19ba404d20fe713.eot   162 KiB          [emitted]
                   7.81f0a23a8df7947dbe17.js  3.57 KiB       7  [emitted] [immutable]
               7.81f0a23a8df7947dbe17.js.map  6.94 KiB       7  [emitted] [dev]
        912ec66d7572ff821749319396470bde.svg   434 KiB          [emitted]              [big]
      af7ae505a9eed503f8b8e6982036873e.woff2  75.4 KiB          [emitted]
        b06871f281fee6b241d60582ae9369b9.ttf   162 KiB          [emitted]
       fee66e712a8a08eef5805a46892932ad.woff  95.7 KiB          [emitted]
                                  index.html  1.74 KiB          [emitted]
                main.e22fed0f18872cabfe57.js  24.8 KiB       0  [emitted] [immutable]         main
            main.e22fed0f18872cabfe57.js.map  92.5 KiB       0  [emitted] [dev]               main
        vendors~main.b27b6f6773c76ef6900b.js  4.19 MiB       1  [emitted] [immutable]  [big]  vendors~main
    vendors~main.b27b6f6773c76ef6900b.js.map  13.3 MiB       1  [emitted] [dev]               vendors~main
    Entrypoint main [big] = vendors~main.b27b6f6773c76ef6900b.js vendors~main.b27b6f6773c76ef6900b.js.map main.e22fed0f18872cabfe57.js main.e22fed0f18872cabfe57.js.map
    [0] multi whatwg-fetch ./build/index.out.js 40 bytes {0} [built]
    [/KN4] ./node_modules/@jupyterlab/filebrowser-extension/lib/index.js + 6 modules 126 KiB {1} [optional] [built]
        |    7 modules
    [31N0] ./node_modules/@jupyterlab/csvviewer-extension/lib/index.js + 5 modules 66.1 KiB {1} [optional] [built]
        |    6 modules
    [5pV8] ./node_modules/@jupyterlab/mathjax2-extension/lib/index.js + 1 modules 4.04 KiB {1} [optional] [built]
        |    2 modules
    [8943] ./node_modules/@jupyterlab/mainmenu-extension/lib/index.js + 10 modules 37 KiB {1} [optional] [built]
        |    11 modules
    [9fgM] ./build/imports.css 1.06 KiB {0} [built]
    [ANye] ./build/index.out.js 39.6 KiB {0} [built]
    [LYgx] ./node_modules/@jupyterlab/docmanager-extension/lib/index.js + 6 modules 86.8 KiB {1} [optional] [built]
        |    7 modules
    [NHPb] ./node_modules/@jupyterlab/console-extension/lib/index.js + 6 modules 66.9 KiB {1} [optional] [built]
        |    7 modules
    [QP8U] ./node_modules/@jupyterlab/fileeditor-extension/lib/index.js + 2 modules 35.9 KiB {1} [optional] [built]
        |    3 modules
    [QbIU] ./node_modules/@jupyterlab/running-extension/lib/index.js + 1 modules 9.6 KiB {1} [optional] [built]
        |    2 modules
    [RMrj] ./node_modules/@jupyterlab/inspector-extension/lib/index.js + 1 modules 8.5 KiB {1} [optional] [built]
        |    2 modules
    [U33M] ./node_modules/@jupyterlab/logconsole-extension/lib/index.js + 6 modules 45.1 KiB {1} [optional] [built]
        |    7 modules
    [VYmV] ./node_modules/@jupyterlab/completer-extension/lib/index.js + 7 modules 61.6 KiB {1} [optional] [built]
        |    8 modules
    [ZPDT] ./node_modules/@jupyterlab/extensionmanager-extension/lib/index.js + 6 modules 43.4 KiB {1} [optional] [built]
        |    7 modules
        + 1405 hidden modules

    WARNING in entities
      Multiple versions of entities found:
        1.1.2 ./~/htmlparser2/~/entities from ./~/htmlparser2\lib\Tokenizer.js
        2.0.0 ./~/entities from ./~/entities\lib\decode.js

    Check how you can resolve duplicate packages:
    https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle


    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets:
      912ec66d7572ff821749319396470bde.svg (434 KiB)
      vendors~main.b27b6f6773c76ef6900b.js (4.19 MiB)
      2.9dc0997e8e8efbaac836.js (448 KiB)
      4.3c35e5e107907f8e2970.js (751 KiB)
      5.bebab39f4cb7d3984f88.js (721 KiB)

    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      main (4.21 MiB)
          vendors~main.b27b6f6773c76ef6900b.js
          main.e22fed0f18872cabfe57.js

    Child html-webpack-plugin for "index.html":
         1 asset
        Entrypoint undefined = index.html
        [KTNU] ./node_modules/html-loader!./templates/partial.html 703 bytes {0} [built]
        [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
        [aS2v] ./node_modules/html-webpack-plugin/lib/loader.js!./templates/template.html 1.27 KiB {0} [built]
        [yLpj] (webpack)/buildin/global.js 472 bytes {0} [built]
            + 1 hidden module
Child
    Hash: 0cfc236e634b2f79ff7b
    Time: 4722ms
    Built at: 2020-01-15 10:03:00
        Asset       Size  Chunks             Chunk Names
    index.css   85.9 KiB       0  [emitted]  index
     index.js  932 bytes       0  [emitted]  index
    Entrypoint index = index.css index.js
       4 modules
    Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/@jupyterlab/theme-dark-extension/style/index.css:
        Entrypoint mini-css-extract-plugin = *
           56 modules
Child
    Hash: 4caa275dffc36e817080
    Time: 4766ms
    Built at: 2020-01-15 10:03:00
        Asset       Size  Chunks             Chunk Names
    index.css   83.3 KiB       0  [emitted]  index
     index.js  932 bytes       0  [emitted]  index
    Entrypoint index = index.css index.js
       4 modules
    Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/@jupyterlab/theme-light-extension/style/index.css:
        Entrypoint mini-css-extract-plugin = *
           57 modules
Done in 59.86s.


</pre>
</details>

**Comment by kklocker** [comment]
Is this a possible duplicate of #4662 ?
I both tried running 
`jupyter-lab --generate-config` and reloading without cache as suggested in that thread. Neither worked. 

I also tried installing from pip in a separate environment, and it didn't work either!

**Comment by kklocker** [comment]
### UPDATE:
It finally works.  I ran `jupyter lab clean`, then manually deleted the `~/.jupyter` folder,  then  `conda install nodejs,` and then finally run `jupyter lab build`

**Comment by jasongrout** [comment]
It sounds like something was wrong in your settings in `~/.jupyter`, then. Thanks for updating on what worked for you.
