### ISSUE TITLE
Incorrect kernel execution state for a running kernel. 

### ISSUE THREAD

**Issue by m0hit-aggarwal** [jupyterlab/jupyterlab#7683]
## Description
We were using Spark IPython kernels using [Jupyter Enterprise gateway](https://github.com/jupyter/enterprise_gateway). During kernel launch, the kernel execution state immediately changed to **unknown** from **idle** in UI. Jupyter server's request at '/api/kernels/{kernel_id}' clearly shows that kernel is running and the execution state is **idle**. However, the execution state is shown as **unknown** on the frontend. Refer to the command line output shown below. **Reconnect to kernel** from the command tab also doesn't work when this happens. We faced similar issue with JupyterLab version 0.33.12 but instead of **unknown**, the kernel state is shown as **dead** on frontend.

## Reproduce
This doesn't happen every time we launch a kernel, so there is no deterministic way to reproduce it. However, on repeated launching and shutdown we faced the same issue. 

## Context

- Operating System and version: macOS Mojave Version 10.14.6
- Browser and version: Chrome Version 78.0.3904.108
- JupyterLab version: 1.2.4
- Jupyter Enterprise Gateway version: 2.0.0

<details><summary>Command Line Output</summary>
<pre>
[W 15:24:33.765 LabApp] Websocket connection has been cancelled via client disconnect before its establishment.  Kernel with ID '8a3ad746-dde3-45a6-885c-6192f14b873d' may not be terminated on Gateway: http://10.34.102.251:9090
[D 15:24:34.004 LabApp] Kernel retrieved: {u'connections': 1, u'last_activity': u'2019-12-23T09:53:06.201869Z', u'execution_state': u'idle', u'id': u'817c6599-8a6e-484a-9bb4-262997d3952f', u'name': u'mlp.mlc.linux_debian_8_11.py27.mlc-base-tf-keras'}
[D 15:24:34.005 LabApp] Request kernel at: /api/kernels/35c727a0-0a39-46c7-8da0-6af9232cb60d
[D 15:24:34.315 LabApp] Kernel retrieved: {u'connections': 1, u'last_activity': u'2019-12-23T09:53:22.267756Z', u'execution_state': u'idle', u'id': u'35c727a0-0a39-46c7-8da0-6af9232cb60d', u'name': u'mlp.mlc.linux_debian_8_11.py27.mlc-base-tf-keras'}
[D 15:24:34.316 LabApp] Request kernel at: /api/kernels/8a3ad746-dde3-45a6-885c-6192f14b873d
[D 15:24:34.420 LabApp] Kernel retrieved: {u'connections': 1, u'last_activity': u'2019-12-23T09:54:33.775276Z', u'execution_state': u'idle', u'id': u'8a3ad746-dde3-45a6-885c-6192f14b873d', u'name': u'mlp.mlc.linux_debian_8_11.py27.mlc-base-tf-keras'}
</pre>
On the fronted, execution state for kernel with the kernel_id:8a3ad746-dde3-45a6-885c-6192f14b873d was shown to be in unknown. However, it can be clearly seen in the logs that kernel with kernel id:8a3ad746-dde3-45a6-885c-6192f14b873d is in idle state.  
</details>

**Comment by jasongrout** [comment]
Is there a way for you to check from current master? We just merged in a huge PR that changes how kernel status is displayed. We will be publishing a beta soon with these changes.

**Comment by m0hit-aggarwal** [comment]
I checked with current master, issue is still there. But now frontend shows, kernel execution state as **dead** instead of **unknown**. Reconnect to kernel in command tab still doesn't work.
### Command line Output  
<pre>
[D 00:43:07.252 LabApp] Closing websocket connection /api/kernels/3d754760-9ad5-4f96-b905-4ae83f7c7a54/channels
[D 00:43:07.252 LabApp] _disconnect: future cancelled, disconnected: True
[W 00:43:07.252 LabApp] Websocket connection has been closed via client disconnect or due to error.  Kernel with ID '3d754760-9ad5-4f96-b905-4ae83f7c7a54' may not be terminated on GatewayClient: http://10.34.102.251:9090
[D 00:43:10.914 LabApp] RemoteKernelManager.kernel_model: 3d754760-9ad5-4f96-b905-4ae83f7c7a54
[D 00:43:10.914 LabApp] Request kernel at: http://10.34.102.251:9090/api/kernels/3d754760-9ad5-4f96-b905-4ae83f7c7a54
[D 00:43:10.946 LabApp] Kernel retrieved: {'id': '3d754760-9ad5-4f96-b905-4ae83f7c7a54', 'name': 'mlp.mlc.linux_debian_8_11.py27.mlc-base-tf-keras', 'last_activity': '2019-12-23T19:13:09.262874Z', 'execution_state': 'idle', 'connections': 1}
</pre>

### Context:
- Operating System and version: macOS Mojave Version 10.14.6
- Browser and version: Chrome Version 78.0.3904.108
- JupyterLab version: 2.0.0a4
- Jupyter Enterprise Gateway version: 2.0.0

**Comment by jasongrout** [comment]
We just merged in some cleanup of the kernel status code. Can you check with the latest master on git (or wait for the next beta to be published)?

**Comment by m0hit-aggarwal** [comment]
Okay, I will check with current master. When can i expect next beta release ?

**Comment by m0hit-aggarwal** [comment]
Issue seems to be fixed in current master.

**Comment by vidartf** [comment]
Thanks! Closing then 👍
