### ISSUE TITLE
Revert icons backwards compatibility workarounds

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#7685]
Looks like some of the backwards compatibility workarounds in #7182 can be reverted now master is on 2.0.

CC @telamonian

**Comment by jasongrout** [comment]
In particular, see the notes in https://github.com/jupyterlab/jupyterlab/pull/7182/files#diff-8c86f33bb6f77c0c318375327e2472fe

**Comment by telamonian** [comment]
I'm handling this as part of #7299

**Comment by jasongrout** [comment]
Is #7299 making it into the beta? We were hoping to freeze the api.

CC @blink1073

**Comment by telamonian** [comment]
I working on #7299 and the somewhat related #7574 right now. I would like to get them into 2.0, but I'll probably need at least one more day

**Comment by jasongrout** [comment]
Fixed by #7700, right?

**Comment by telamonian** [comment]
fixed by #7700
