### ISSUE TITLE
Property Inspector UX

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#7686]
## Description
Fix issues with new Property Inspector before the final release:

<img width="1049" alt="Screen Shot 2019-12-23 at 9 15 24 AM" src="https://user-images.githubusercontent.com/192614/71368676-c5e0f380-2565-11ea-81ee-8dddbff5908a.png">

And perhaps the wrench icon should be updated to something to more reflect a property inspector.

**Comment by jasongrout** [comment]
It appears the inspector is just centered, when I think it should be aligned to the top and stretched to fill the available horizontal space

**Comment by jasongrout** [comment]
CC @tgeorgeux
