### ISSUE TITLE
"Code Editor out of Sync " of message

### ISSUE THREAD

**Issue by jiaqianjing** [jupyterlab/jupyterlab#7703]
## Version:
1. jupyterlab         1.2.3
2. jupyterlab-server  1.0.6
3. Python 3.7.0
4. Linux 911c626bdc11 3.10.0_3-0-0-17 #2 SMP Tue Mar 27 15:52:12 CST 2018 x86_64 x86_64 x86_64 GNU/Linux ( Container Env)

==========

I got  "Code Editor out of Sync" of message frequently when I had opened ipynb file. And I found that my ipynb file has "\r\n" end of line.

**Comment by jiaqianjing** [comment]
![image](https://user-images.githubusercontent.com/16071449/71510848-39b72f00-28cb-11ea-8a01-a37b38b33968.png)

**Comment by guaidoukx** [comment]
I have the same issue, too. But I don't know how to fix it. My .py file ends with "\n".

**Comment by fmgithub2017** [comment]
I have the same issue.
I'm using JupyterLab from WinPython.

**Comment by Serhiy-Shekhovtsov** [comment]
Same issue when I open very big text file.

**Comment by krishnatejakanchi** [comment]
Same issue here. What's the fix ?

**Comment by jasongrout** [comment]
According to the history, this probably should have been fixed by https://github.com/jupyterlab/jupyterlab/pull/5622 a long time ago. 

Another report: https://github.com/jupyterlab/jupyterlab/issues/9340

I think to debug this better, we need to be able to reproduce it. A sample file and details about your OS, jlab version would help.

**Comment by jasongrout** [comment]
If you can reliably reproduce this error, please try with the newest jupyterlab 3.0 prerelease (`pip install --pre jupyterlab` in a clean environment) to see if it may already be fixed.

**Comment by krishnatejakanchi** [comment]
I first created notebook in jupyter lab. Then I used that notebook in vscode editor. I got this error only after i switched from vscode notebook editor to jupyter lab. So I thought vscode made some changes to the notebook. So i created new notebook in jupyter lab and i am not getting any errors

**Comment by MichaMucha** [comment]
@krishnatejakanchi 
I was experiencing the same error in the exact same situaion (VS Code and JupyterLab on Windows)

Just fixed a notebook by opening it in Editor mode (in JupyterLab) and search-replacing `\r\n` to `\n`

**Comment by telamonian** [comment]
I've personally never had this particular issue, but I used to run into similar LF/CLRF conflicts all the time when doing windows dev. When using vscode on windows, I've found the following setting to be very helpful:

```json
"files.eol": "\n",
```

This tells vscode to always use the LF line ending convention, thus avoid any potential conflict in the first place

**Comment by Anshugarg007** [comment]
I experienced the same issue just now. What is the fix?

**Comment by ymmu** [comment]
I had the same issue when I open my ipynb made in google colab.

**Comment by thinklikeanarchitect** [comment]
> @krishnatejakanchi
> I was experiencing the same error in the exact same situaion (VS Code and JupyterLab on Windows)
> 
> Just fixed a notebook by opening it in Editor mode (in JupyterLab) and search-replacing `\r\n` to `\n`

It worked, thanks. My problem was steming from transfering Google Colab file  to local. The original file gave this error.

**Comment by thinklikeanarchitect** [comment]
> I had the same issue when I open my ipynb made in google colab.

@MichaMucha explained the fix!

**Comment by jasongrout** [comment]
This bug of not handling \r\n line endings in notebook cells is now being tracked in #9465.
