### ISSUE TITLE
Notebook disappears from directory when filename is changed to a hidden file

### ISSUE THREAD

**Issue by berkser** [jupyterlab/jupyterlab#7710]
## Description

Notebook disappears from directory when filename is changed to a hidden file such as ‘.ipynb’. The notebook reappears when it is renamed using the notebook tab.  

## Reproduce

1. Click 'Rename' on any notebook in left sidebar.
2. Name it as a hidden file such as '.ipynb'.
3. File disappears from Jupyter Lab UI

## Expected behavior

Expectation would be that files can not be named as hidden files as these files are inaccessible through Jupyter Lab UI.

**Comment by jasongrout** [comment]
This would be a change to the notebook server, which is responsible for both what renamings are valid and the invisibility of hidden files.

**Comment by jasongrout** [comment]
To follow up: https://github.com/jupyter/notebook/ would be the appropriate place to file this issue. I realize this is a bit confusing when functionality is split up between the server and the front end.
