### ISSUE TITLE
Update Phosphor to Lumino in verbiage / docs

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#7714]
For example, cf. https://github.com/jupyterlab/jupyterlab/pull/7707

**Comment by isabela-pf** [comment]
I looked through the docs and don't see any instances where Phosphor is still being used except for the changelog where it makes sense to preserve the original name. I think this issue can be closed.

**Comment by afshin** [comment]
Cheers @isabela-pf!

**Comment by Zsailer** [comment]
Thanks, @isabela-pf!
