### ISSUE TITLE
Javascript Error: IPython is not defined

### ISSUE THREAD

**Issue by thomasd3** [jupyterlab/jupyterlab#7715]
I can't find any clear documentation if JS / IPython is supported with Jupyterlab, or not.

I've installed that extension:
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib

But when I'm using Backtrader (which uses Bokeh), I get the error in the title.
The same notebook in jupyter notebook works perfectly.

**Comment by agoose77** [comment]
JupyterLab uses Javascript, and IPython is still supported, but the JS API is different. It is likely that if Backtrader was written for Jupyter Notebook, it will not work directly on JupyterLab. It's not *that* hard to get extensions working in JupyterLab - you just have to write your own extension to facilitate it.

**Comment by glass-ships** [comment]
Ran into this myself recently when a bit of test code started using the `%matplotlib interactive` call. 
[This StackOverflow post](https://stackoverflow.com/a/56416229) seems to indicate that it's possible, but requires a little extra setup ahead of time. 

For example, [this extension](https://github.com/matplotlib/ipympl) turns matplotlib objects into interactive widgets. 

But the part I think maybe you're maybe interested in is: `conda install nodejs`

**Comment by thomasd3** [comment]
I have nodejs on my machine but I didn't know the ipympl extension, I will try it. thanks!

**Comment by sandboiii** [comment]
I've spent entire evening trying to solve this problem, so I came up with this code:
```
cerebro.run()

%matplotlib widget
cerebro.plot(iplot=False)
```
This way I managed to display plot in JupyterLab

**Comment by sandboiii** [comment]
using `%matplotlib inline` should also work

**Comment by nickk** [comment]
> 
> 
> I've spent entire evening trying to solve this problem, so I came up with this code:
> 
> ```
> cerebro.run()
> 
> %matplotlib widget
> cerebro.plot(iplot=False)
> ```
> 
> This way I managed to display plot in JupyterLab

Thank you, this worked!

**Comment by songhuazhang** [comment]
> I've spent entire evening trying to solve this problem, so I came up with this code:
> 
> ```
> cerebro.run()
> 
> %matplotlib widget
> cerebro.plot(iplot=False)
> ```
> 
> This way I managed to display plot in JupyterLab

this saved my day!

**Comment by MohamedNedal** [comment]
> 

Excuse me, I'm getting this error: 
`NameError: name 'cerebro' is not defined`
