### ISSUE TITLE
Restoring a console starts two consoles, doesn't open console panel in main area

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#7726]
Currently, if you have a console open and refresh the page, the console panel does not get restored. Also, for some reason another console is started. Here's what it looks like when you start one console and then refresh three times:

![image](https://user-images.githubusercontent.com/2263641/71721106-efb1da00-2df1-11ea-9094-12c65b233565.png)

**Comment by blink1073** [comment]
This is being addressed in #7705

**Comment by blink1073** [comment]
I confirmed that #7705 fixes this behavior.

**Comment by jasongrout** [comment]
This was fixed in #7693. #7705 probably already has that commit from master.
