### ISSUE TITLE
New Icon for Propterties Inspector panel

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#7732]
## Description

Proposing a new Icon for Property Inspector.

I was trying to get at the idea of 'inspecting' things, didn't really find much down that avenue except variations on magnifying or zooming in on properties. I didn't want to use a single cog because that communicates settings. and it's already used for global settings. 

Here's my final three options:
![cogs](https://user-images.githubusercontent.com/22109376/71748980-0c1d3900-2e29-11ea-8271-3e84fead0d65.png)
![cogsmag](https://user-images.githubusercontent.com/22109376/71748982-0c1d3900-2e29-11ea-8635-70b285a0f58f.png)
![settingsmag](https://user-images.githubusercontent.com/22109376/71748983-0cb5cf80-2e29-11ea-8aec-a3479d7bb753.png)

As it stands I'm leaning towards the two cogs, but if anybody has more input let me know and I can sketch something else out.

**Comment by blink1073** [comment]
I'm happy with the two cogs.  How about binoculars, to distinguish from search?
