### ISSUE TITLE
Unable to install lab extensions (jlpm yarn.js Syntax Error)

### ISSUE THREAD

**Issue by enalposi** [jupyterlab/jupyterlab#7737]
I am unable to install lab extensions after multiple attempts at clean installing latest jupyterlab both with conda and pip on Debian 9. The most recent is a pip install on a virtualenv results in the following versions:

jupyter core     : 4.6.1
jupyter-notebook : 6.0.2
qtconsole        : 4.6.0
ipython          : 7.9.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 1.2.4
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

Any lab extension related operation results in a syntax error. The most sparse command is simply issuing 'jlpm'

jlpm
.../venv/.../lib/python3.5/site-packages/jupyterlab/staging/yarn.js:1227
  var _ref27 = (0, (_asyncToGenerator2 || _load_asyncToGenerator()).default)(function* (dir, relativeDir, ignoreBasenames = new Set()) {
                                                                                                                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

Editing the file in an attempt to bypass the issue results in similar errors at other locations.

The current goal is being able to 'see' plotly output in jupyter lab, which requires extensions.
https://plot.ly/python/getting-started/ -> JupyterLab Support (Python 3.5+)

Any ideas please? Thanks

**Comment by jasongrout** [comment]
My guess is that you need to node to a newer version. Version 10 or 12 should do it?

**Comment by enalposi** [comment]
> My guess is that you need to update node to a newer version. Version 10 or 12 should do it?

Great guess - The startup error went away, I was able to install lab extensions and plotly is now working. Didn't realize how ancient this node was.

Thanks very much!
