### ISSUE TITLE
Feature idea:  Markdown preview default

### ISSUE THREAD

**Issue by sperezconesa** [jupyterlab/jupyterlab#7738]
Dear Jupyterlab community,
I think it would be nice if there could be a default mode to open markdown files either in the editor or in the markdown preview. This could be done in a file-wise basis or in general.
In addition it would also be nice if from a markdown editor tab you could right click and have an option to open the file in preview mode or viceversa. 
Keep up the good work!
Best,
Sergio

**Comment by markellekelly** [comment]
Hi Sergio, I was able to switch the default mode for opening markdown files by adding  ```"defaultViewers": {
          "markdown": "Markdown Preview"
}``` to the Document Manager section of the Advanced Settings Editor. Would something like this be an acceptable solution or are you hoping for a more explicit menu item?

Additionally, it seems you can right click in markdown editor to open preview, but not vice versa. I will look into adding a context menu to markdown preview to fix this.

**Comment by sperezconesa** [comment]
Awesome! Thanks a lot. It's true that extra menu item is needed.
Keep up the good work!

**Comment by jtpio** [comment]
Closing as fixed by #7942
