### ISSUE TITLE
Testing library

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#774]
There should be a library that provides utilities for testing, like typical mocks and assertions.

**Comment by blink1073** [comment]
Yep, agreed.

**Comment by blink1073** [comment]
I'd add a drag-drop test helper to this list.

**Comment by ellisonbg** [comment]
@blink1073 can I close this?

**Comment by blink1073** [comment]
No, it is still a useful idea.  Pushing to `Future`.
