### ISSUE TITLE
Time conflict and the "File Changed" dialog appear every time an attempt is made to save a Notebook

### ISSUE THREAD

**Issue by mpaunovi** [jupyterlab/jupyterlab#7743]
## Description
When saving a Notebook file (6.83 MB), the PUT request (api/contents/{someNotebook}) takes about 1.5 seconds. This causes a time conflict and displays the "File Changed" popup since it does not match the allowed 0.5 seconds difference between disk time and client time.

Screenshot:
![image](https://user-images.githubusercontent.com/43001714/71818777-2a35a400-308a-11ea-86b5-2bd0dd6b2082.png)

Note: The same notebook is not open on another tab or browser, and no one changes that notebook except the current user.

## Reproduce

This issue happens occasionally. It's not completely clear what causes this behavior, but once it happens it will happen every time with every attempt to save the notebook file.

## Context

- Operating System and version: macOS Mojave Version 10.14.6
- Browser and version: Chrome Version 79.0.3945.88
- JupyterLab version: 1.0.4
- Notebook version: 6.0.0

<details><summary>Server log snippet</summary>
<pre>
[I 14:18:29.230 NotebookApp] 200 GET /jupyter/jupyter-{{user_id}}/api/sessions?sessionId(IP address) 2.71ms
[I 14:18:35.744 NotebookApp] Saving file at /Some_Notebook_File.ipynb
[W 14:18:35.800 NotebookApp] Notebook Some_Notebook_File.ipynb is not trusted
[I 14:18:37.178 NotebookApp] 200 PUT /jupyter/jupyter-{{user_id}}/api/contents/Some_Notebook_File.ipynb?1************ (IP address) 1511.96ms
[I 14:18:37.234 NotebookApp] 200 GET /jupyter/jupyter-{{user_id}}/api/contents/?content=1&1************ (IP address) 53.37ms
[I 14:18:37.277 NotebookApp] 200 GET /jupyter/jupyter-{{user_id}}/api/terminals?1************(IP address) 1.88ms
[I 14:18:37.725 NotebookApp] 200 GET /jupyter/jupyter-{{user_id}}/api/contents/Some_Notebook_File.ipynb/checkpoints?1************ (IP address) 3.08ms
[I 14:18:38.316 NotebookApp] 201 POST /jupyter/jupyter-{{user_id}}/api/contents/Some_Notebook_File.ipynb/checkpoints?1************ (IP address) 590.44ms
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
context.js:602 Last saving performed Wed Dec 25 2019 17:14:10 GMT+0100 (Central European Standard Time) while the current file seems to have been saved Wed Dec 25 2019 17:14:11 GMT+0100 (Central European Standard Time)
_timeConflict @ context.js:602
(anonymous) @ context.js:535
Promise.then (async)
_maybeSave @ context.js:522
(anonymous) @ context.js:416
Promise.then (async)
_save @ context.js:414
(anonymous) @ context.js:196
Promise.then (async)
save @ context.js:195
onClick @ default-toolbar.js:56
handleMouseDown @ toolbar.js:378
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:270
executeDispatch @ react-dom.development.js:561
executeDispatchesInOrder @ react-dom.development.js:583
executeDispatchesAndRelease @ react-dom.development.js:680
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:688
forEachAccumulated @ react-dom.development.js:662
runEventsInBatch @ react-dom.development.js:816
runExtractedEventsInBatch @ react-dom.development.js:824
handleTopLevel @ react-dom.development.js:4826
batchedUpdates$1 @ react-dom.development.js:20439
batchedUpdates @ react-dom.development.js:2151
dispatchEvent @ react-dom.development.js:4905
(anonymous) @ react-dom.development.js:20490
unstable_runWithPriority @ scheduler.development.js:255
interactiveUpdates$1 @ react-dom.development.js:20489
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
</pre>
</details>

**Comment by mpaunovi** [comment]
It would be good if you could create a configurable property for the value that represents the difference between disk time and client time:
https://github.com/jupyterlab/jupyterlab/blob/master/packages/docregistry/src/context.ts#L644

Similar to what was done here: https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/notebook.js#L2784

**Comment by vidartf** [comment]
@mpaunovi That seems like a workable solution. Are you able to help implement that? Even a partial PR with TODOs for missing parts can help :)

**Comment by ggbhat** [comment]
@vidartf How about adding configuration under settings-> notebook? 
I would like to work on if it is not taken.

**Comment by vidartf** [comment]
@ggbhat Seems reasonable, please go ahead 👍

**Comment by josebrwn** [comment]
Respectfully, this has been an open issue since 2015. I may be out of my depth but what about using a checksum instead of comparing timestamps? There's always going to be a browser or an OS where this problems resurfaces as long as minute differences in timestamps trigger the warning. This just seems like a game of whack a mole!

**Comment by vidartf** [comment]
@josebrwn Unfortunately, the current Jupyter contents model does not send any checksums (https://jupyter-notebook.readthedocs.io/en/stable/extending/contents.html). If you are able to implement an alternative PR to that of @ggbhat (#7858) using checksums, that would of course be welcome 👍

**Comment by jasongrout** [comment]
Alternatively, perhaps we could keep track of the server clock time in JupyterLab, i.e., JupyterLab could keep track of the gap between the browser clock and the server clock, and only compare server timestamps with the server time (i.e., browser time adjusted by this gap).

**Comment by vidartf** [comment]
@jasongrout that still wouldn't fix the issue when the trigger is *a slow upload of a large file*

**Comment by LustigePerson** [comment]
Is there a way to manually check to current "lastModified" time of the client notebook from the browser?
I see the same issue and strangely enough it only starts appearing after a few minutes (and a few saves) but happens all the time then.
