### ISSUE TITLE
IPython Image with URL is centered instead of left-aligned

### ISSUE THREAD

**Issue by mgeier** [jupyterlab/jupyterlab#7752]
##  Description

When using `IPython.display.Image` with an `url` argument and with the default `embed=False` argument, the resulting image is centered.

With `embed=True` (and when not using `url`), the resulting image is left-aligned.

## Reproduce

```python
from IPython.display import Image
Image(url='https://www.python.org/static/img/python-logo-large.png')
Image(url='https://www.python.org/static/img/python-logo-large.png', embed=True)
```

The result in JupyterLab (`master` branch):

![image](https://user-images.githubusercontent.com/705404/71974085-e4571800-3210-11ea-84e2-32914b3deff4.png)

The same thing happens on Binder: https://mybinder.org/v2/gh/spatialaudio/nbsphinx/master?urlpath=lab/tree/doc/code-cells.ipynb

## Expected behavior

The same thing in the Classic Notebook:

![image](https://user-images.githubusercontent.com/705404/71974476-d950b780-3211-11ea-810e-ee450ad87a91.png)

... and in a Classic Binder: https://mybinder.org/v2/gh/spatialaudio/nbsphinx/master?filepath=doc/code-cells.ipynb

## Context

- Operating System and version: Linux (Debian Testing) and whatever Binder uses
- Browser and version: Chromium Version 79.0.3945.79, Firefox Version 71.0
- JupyterLab version: `master` branch and whatever Binder uses

**Comment by kinow** [comment]
The fix would be a change with a [couple of lines](https://github.com/jupyterlab/jupyterlab/blob/6777d8e674d30bab8c5a7b02953e133656200903/packages/rendermime/style/base.css#L415-L416). With `notebook`, those values are both set to `0`, whereas with `lab` they are `auto`. Not sure if that was an intentional change?

**Comment by joshz123** [comment]
Is this issue still unassigned?

**Comment by vidartf** [comment]
@joshz123 There was a linked PR above that has been merged 13 days ago which seems to resolve this. Closing as resolved. Thanks for asking!
