### ISSUE TITLE
Binder: "could not start lab-dev in time"

### ISSUE THREAD

**Issue by mgeier** [jupyterlab/jupyterlab#7761]
... when using this link:

https://mybinder.org/v2/gh/jupyterlab/jupyterlab/master?urlpath=lab-dev

Is this a temporary glitch or is there a deeper problem?

![image](https://user-images.githubusercontent.com/705404/72084281-7dfef200-3303-11ea-8d19-ab5c74274e25.png)

**Comment by blink1073** [comment]
Thanks for the heads up!
