### ISSUE TITLE
Rendermime Interfaces should be self contained

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#7765]
## Description
This package is meant to be self contained.  We picked up a dependency on `ui-components` to allow users to provide a `JLIcon`.  There is a more generic interface that we could use that would allow us to avoid the dependency.

**Comment by blink1073** [comment]
cc @telamonian

**Comment by jasongrout** [comment]
> This package is meant to be self contained.

I strongly agree.
