### ISSUE TITLE
Embedding a React.js application in Jupyterlab

### ISSUE THREAD

**Issue by carlskii** [jupyterlab/jupyterlab#7770]
Hi,

I've built simple React.js application and was wondering if it was possible to run it from within Jupyterlab. I installed the "sophon-notebook-htmlviewer-extension" but this did not seem to work for me. 

Is this possible? If so could somebody point me in the right direction.

Thanks and thanks for building an amazing application.

**Comment by jtpio** [comment]
@carlskii it is possible to embed existing React components in a JupyterLab extension.

There is some documentation here about using React in JupyterLab: https://jupyterlab.readthedocs.io/en/latest/developer/virtualdom.html
And a "ready-to-use" example here to quickly get started: https://github.com/jtpio/jupyterlab-extension-examples/tree/master/react/react-widget

Could that work for your use case?

**Comment by carlskii** [comment]
Excellent, thanks I will take a look.

**Comment by carlskii** [comment]
Whats the best way to install the @jupyterlab/apputils extension? It doesn't appear in the extensions manager. 

I also tried following the instructions here: https://github.com/jtpio/jupyterlab-extension-examples/tree/master/react/react-widget

However `jlpm build` does not seem to be a valid command.

**Comment by jtpio** [comment]
`@jupyterlab/apputils` is a dependency for the extension that is defined in the `dependencies` section in `package.json`, that should be installed after running `jlpm`.

JupyterLab should be installed first so the `jlpm` command is available.

If this is specific to the [react-widget](https://github.com/jtpio/jupyterlab-extension-examples/tree/master/react/react-widget) example we can also move the conversation to a new issue in https://github.com/jtpio/jupyterlab-extension-examples.

**Comment by carlskii** [comment]
Thanks - Will the coming Jupyterlab 2.0 provide easier/better support for including a React APP within Jupyter?

**Comment by jtpio** [comment]
For 2.0 the API should be the same as 1.0 when it comes to using React components with the `ReactWidget` wrapper.

**Comment by carlskii** [comment]
OK so I did this: 

```
$jlpm
yarn install v1.15.2
[1/4] Resolving packages...
success Already up-to-date.
$ lerna bootstrap
lerna notice cli v3.20.2
lerna info versioning independent
lerna info bootstrap root only
yarn install v1.15.2
[1/4] Resolving packages...
success Already up-to-date.
$ lerna bootstrap
lerna notice cli v3.20.2
lerna info versioning independent
lerna WARN bootstrap Skipping recursive execution
Done in 1.25s.
Done in 3.26s.
$jlpm build      
yarn run v1.15.2
error Command "build" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

However the 'build' command still does not appear to be there.

**Comment by jtpio** [comment]
And with `jlpm run build`?

**Comment by carlskii** [comment]
Exactly the same error.

**Comment by jtpio** [comment]
Are you in the right directory?

```
cd react/react-widget/
jlpm
jlpm run build
```

**Comment by carlskii** [comment]
Doh - OK. Got it thank you. I was in the project root. That works.

**Comment by jtpio** [comment]
No problem, thanks for checking.

Feel free to open an issue in https://github.com/jtpio/jupyterlab-extension-examples if you have more questions about that particular example.
