### ISSUE TITLE
[HTTP Error 500] Error communicating with server extension

### ISSUE THREAD

**Issue by tbhaxor** [jupyterlab/jupyterlab#7771]
## Description

I am unable to open the extension explorer in jupyter lab. This was actually working fine before i had uninstalled the extension named "**@deathbeds/jupyterlab-fonts**"
![image](https://user-images.githubusercontent.com/28386721/72203442-b7fdfe80-3491-11ea-88ba-f447fb0b7faa.png)

## Reproduce

1. Open the Jupyterlab in browser
2. Navigate to the extension manager

## Expected behavior
It should list all the extensions currently installed

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version:

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/terabyte/.pyenv/versions/3.7.5/bin
	/usr/share/pyenv/libexec
	/home/terabyte/.yarn/bin
	/home/terabyte/.config/yarn/global/node_modules/.bin
	/home/terabyte/.pyenv/shims
	/home/terabyte/.local/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/local/sbin
	/opt/android-sdk/tools
	/opt/android-sdk/tools/bin
	/var/lib/flatpak/exports/bin
	/usr/lib/jvm/default/bin
	/usr/bin/site_perl
	/usr/bin/vendor_perl
	/usr/bin/core_perl
	/var/lib/snapd/snap/bin
	/opt/flutter/bin
	/home/terabyte/Programs/go/bin
	/home/terabyte/.config/composer/vendor/bin
	/opt/flutter/bin
	/home/terabyte/.gem/ruby/2.6.0/bin

sys.path:
	/home/terabyte/.pyenv/versions/3.7.5/bin
	/home/terabyte/.pyenv/versions/3.7.5/lib/python37.zip
	/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7
	/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/lib-dynload
	/home/terabyte/.local/lib/python3.7/site-packages
	/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages

sys.executable:
	/home/terabyte/.pyenv/versions/3.7.5/bin/python3.7

sys.version:
	3.7.5 (default, Dec 20 2019, 13:31:25) 
	[GCC 9.2.0]

platform.platform():
	Linux-5.4.6-2-MANJARO-x86_64-with-arch-Manjaro-Linux

which -a jupyter:
	/home/terabyte/.pyenv/versions/3.7.5/bin/jupyter
	/home/terabyte/.pyenv/shims/jupyter

pip list:
	Package              Version   
	-------------------- ----------
	absl-py              0.9.0     
	altgraph             0.16.1    
	astor                0.8.1     
	astroid              2.3.3     
	attrs                19.3.0    
	autopep8             1.4.4     
	backcall             0.1.0     
	bleach               3.1.0     
	cachetools           4.0.0     
	cassandra-driver     3.20.2    
	certifi              2019.11.28
	chardet              3.0.4     
	Click                7.0       
	clingkernel          0.0.2     
	colorama             0.4.3     
	coverage             5.0       
	cycler               0.10.0    
	decorator            4.4.1     
	defusedxml           0.6.0     
	discover             0.4.0     
	docker               4.1.0     
	easydict             1.9       
	entrypoints          0.3       
	Faker                3.0.0     
	Flask                1.1.1     
	gast                 0.2.2     
	google-auth          1.10.0    
	google-auth-oauthlib 0.4.1     
	google-pasta         0.1.8     
	grpcio               1.26.0    
	gunicorn             20.0.4    
	h5py                 2.10.0    
	idna                 2.8       
	importlib-metadata   1.3.0     
	inflection           0.2.0     
	iotop                0.6       
	ipykernel            5.1.3     
	ipython              7.10.2    
	ipython-genutils     0.2.0     
	ipywidgets           7.5.1     
	isort                4.3.21    
	itsdangerous         1.1.0     
	jedi                 0.15.2    
	Jinja2               2.10.3    
	joblib               0.14.1    
	json5                0.8.5     
	jsonschema           3.2.0     
	jupyter              1.0.0     
	jupyter-client       5.3.4     
	jupyter-console      6.0.0     
	jupyter-core         4.6.1     
	jupyterlab           1.2.4     
	jupyterlab-server    1.0.6     
	Keras                2.3.1     
	Keras-Applications   1.0.8     
	Keras-Preprocessing  1.1.0     
	kiwisolver           1.1.0     
	lazy-object-proxy    1.4.3     
	linkedin-api         1.1.0     
	Markdown             3.1.1     
	MarkupSafe           1.1.1     
	matplotlib           3.1.2     
	mccabe               0.6.1     
	Ming                 0.9.1     
	mistune              0.8.4     
	mongoengine          0.19.1    
	more-itertools       8.0.2     
	nbconvert            5.6.1     
	nbformat             4.4.0     
	notebook             6.0.2     
	numpy                1.17.4    
	oauthlib             3.1.0     
	opt-einsum           3.1.0     
	pandas               0.25.3    
	pandocfilters        1.4.2     
	parso                0.5.2     
	patsy                0.5.1     
	pexpect              4.7.0     
	pickleshare          0.7.5     
	pip                  19.3.1    
	prometheus-client    0.7.1     
	prompt-toolkit       2.0.10    
	protobuf             3.11.1    
	ptyprocess           0.6.0     
	pyasn1               0.4.8     
	pyasn1-modules       0.2.7     
	pycodestyle          2.5.0     
	Pygments             2.5.2     
	PyInstaller          3.5       
	pylint               2.4.4     
	pymodm               0.4.2     
	pymongo              3.6.0     
	pyparsing            2.4.5     
	PyQt5                5.14.0    
	PyQt5-sip            12.7.0    
	pyrsistent           0.15.6    
	python-dateutil      2.8.1     
	python-dotenv        0.10.3    
	pytz                 2019.3    
	PyYAML               5.2       
	pyzmq                18.1.1    
	qtconsole            4.6.0     
	requests             2.22.0    
	requests-oauthlib    1.3.0     
	rope                 0.14.0    
	rsa                  4.0       
	scikit-learn         0.22      
	scipy                1.4.1     
	seaborn              0.9.0     
	selenium             3.141.0   
	Send2Trash           1.5.0     
	setuptools           42.0.2    
	six                  1.13.0    
	SQLAlchemy           1.3.12    
	statsmodels          0.10.2    
	tensorboard          2.0.2     
	tensorflow           2.0.0     
	tensorflow-estimator 2.0.1     
	termcolor            1.1.0     
	terminado            0.8.3     
	testpath             0.4.4     
	text-unidecode       1.3       
	tornado              6.0.3     
	tqdm                 4.41.0    
	traitlets            4.3.3     
	typed-ast            1.4.0     
	urllib3              1.25.7    
	wcwidth              0.1.7     
	webencodings         0.5.1     
	websocket-client     0.57.0    
	Werkzeug             0.16.0    
	wheel                0.33.6    
	widgetsnbextension   3.5.1     
	wrapt                1.11.2    
	yapf                 0.29.0    
	youtube-dl           2020.1.1  
	zipp                 0.6.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 16:43:47.177 LabApp] Yarn configuration loaded.
[D 16:43:47.284 LabApp] Node v13.5.0
    
[E 16:43:47.335 LabApp] Uncaught exception GET /lab/api/build?1578741226450 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab/api/build?1578741226450', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/handlers/build_handler.py", line 121, in get
        data = yield self.builder.get_status()
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/handlers/build_handler.py", line 43, in get_status
        self.app_dir, self.log, self.core_config)
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/handlers/build_handler.py", line 96, in _run_build_check
        app_dir=app_dir, logger=logger, core_config=core_config))
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/commands.py", line 507, in build_check
        return handler.build_check()
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/commands.py", line 760, in build_check
        new_package = self._get_package_template(silent=fast)
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/commands.py", line 1241, in _get_package_template
        data['jupyterlab']['mimeExtensions'].pop(item)
    KeyError: '@deathbeds/jupyterlab-fonts'
[W 16:43:47.339 LabApp] Unhandled error
[E 16:43:47.340 LabApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0",
      "Accept": "*/*",
      "Accept-Language": "en-US",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab",
      "Authorization": "token 1197dff664ecf718d19b9495de0aa1b3b1177ead9c06a23d",
      "X-Xsrftoken": "2|ba18a2ae|d10e87fbb2ea69eea93a532bfa895180|1577660620",
      "Content-Type": "application/json",
      "Connection": "keep-alive",
      "Cookie": "_xsrf=2|ba18a2ae|d10e87fbb2ea69eea93a532bfa895180|1577660620; username-localhost-8888=\"2|1:0|10:1578741225|23:username-localhost-8888|44:ZDMwYWM0OTViNDM1NGFkNGExOWM3OTM3MzVmMWMwOTk=|2cf3ab3fb80842b66fcfa9e5e64515b4c74f2eb4917bf64b9236b4e5a9da859c\"; connect.sid=s%3ATMTi2en79es3bO_JGoN0sMfDiDTdvh7P.3Hy%2BuoCBk%2BVR%2FKGiW8EtF6%2B4QOXYcvh8xBUCUteeZc0; org.cups.sid=f56a241e8b56cbc7fd776d5efc95356c; GRABIFY=s%3ADAR5ZzVVn1cRPbTXkpZsUAHoKO77N3Qi.D66FykPGV29N%2BGNe1TNVr18wtM9PWUK4H3vfreuWir4",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 16:43:47.340 LabApp] 500 GET /lab/api/build?1578741226450 (127.0.0.1) 858.39ms referer=http://localhost:8888/lab
[D 16:43:48.708 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.713 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228635 (127.0.0.1) 5.48ms
[D 16:43:48.716 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.718 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.726 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.727 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.728 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.733 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228635 (127.0.0.1) 17.58ms
[D 16:43:48.739 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228636 (127.0.0.1) 21.34ms
[D 16:43:48.744 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228636 (127.0.0.1) 18.75ms
[D 16:43:48.753 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228638 (127.0.0.1) 26.54ms
[D 16:43:48.755 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228637 (127.0.0.1) 27.25ms
[D 16:43:48.758 LabApp] Path @jupyterlab/theme-light-extension/index.css served from /home/terabyte/.pyenv/versions/3.7.5/share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.css
[D 16:43:48.765 LabApp] 200 GET /lab/api/themes/@jupyterlab/theme-light-extension/index.css (127.0.0.1) 7.46ms
[D 16:43:48.775 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.780 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228643 (127.0.0.1) 5.32ms
[D 16:43:48.781 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.783 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.784 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.787 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.789 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.795 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228638 (127.0.0.1) 14.61ms
[D 16:43:48.799 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228639 (127.0.0.1) 16.82ms
[D 16:43:48.803 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228640 (127.0.0.1) 18.92ms
[D 16:43:48.807 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228641 (127.0.0.1) 20.90ms
[D 16:43:48.811 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228642 (127.0.0.1) 22.93ms
[D 16:43:48.813 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.818 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228644 (127.0.0.1) 5.60ms
[D 16:43:48.820 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.822 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.824 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.826 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.828 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.833 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228644 (127.0.0.1) 13.30ms
[D 16:43:48.837 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228645 (127.0.0.1) 15.17ms
[D 16:43:48.841 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228646 (127.0.0.1) 17.34ms
[D 16:43:48.845 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228646 (127.0.0.1) 19.10ms
[D 16:43:48.848 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228647 (127.0.0.1) 20.73ms
[D 16:43:48.850 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.854 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228648 (127.0.0.1) 4.79ms
[D 16:43:48.855 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.857 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.859 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.861 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.863 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.868 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228649 (127.0.0.1) 12.58ms
[D 16:43:48.872 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228650 (127.0.0.1) 14.58ms
[D 16:43:48.875 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1578741228681 (127.0.0.1) 16.02ms
[D 16:43:48.877 LabApp] 200 GET /api/sessions?1578741228694 (127.0.0.1) 15.87ms
[E 16:43:48.923 LabApp] Uncaught exception GET /lab/api/extensions?1578741228732 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab/api/extensions?1578741228732', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 222, in get
        extensions = yield self.manager.list_extensions()
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 86, in list_extensions
        build_check_info = _build_check_info(app_options)
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 56, in _build_check_info
        messages = handler.build_check(fast=True)
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/commands.py", line 760, in build_check
        new_package = self._get_package_template(silent=fast)
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/commands.py", line 1241, in _get_package_template
        data['jupyterlab']['mimeExtensions'].pop(item)
    KeyError: '@deathbeds/jupyterlab-fonts'
[W 16:43:48.923 LabApp] Unhandled error
[E 16:43:48.924 LabApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0",
      "Accept": "*/*",
      "Accept-Language": "en-US",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab",
      "Authorization": "token 1197dff664ecf718d19b9495de0aa1b3b1177ead9c06a23d",
      "X-Xsrftoken": "2|ba18a2ae|d10e87fbb2ea69eea93a532bfa895180|1577660620",
      "Content-Type": "application/json",
      "Connection": "keep-alive",
      "Cookie": "_xsrf=2|ba18a2ae|d10e87fbb2ea69eea93a532bfa895180|1577660620; username-localhost-8888=\"2|1:0|10:1578741228|23:username-localhost-8888|44:ODA2MzIwM2RmMzFlNDYwMGFmYTQ2ZTk1ZjdjNWQwNWU=|264b6faf489903ec476496156a40e44244de825bb74a507389484ed47f95023e\"; connect.sid=s%3ATMTi2en79es3bO_JGoN0sMfDiDTdvh7P.3Hy%2BuoCBk%2BVR%2FKGiW8EtF6%2B4QOXYcvh8xBUCUteeZc0; org.cups.sid=f56a241e8b56cbc7fd776d5efc95356c; GRABIFY=s%3ADAR5ZzVVn1cRPbTXkpZsUAHoKO77N3Qi.D66FykPGV29N%2BGNe1TNVr18wtM9PWUK4H3vfreuWir4",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 16:43:48.924 LabApp] 500 GET /lab/api/extensions?1578741228732 (127.0.0.1) 61.00ms referer=http://localhost:8888/lab
[D 16:43:48.926 LabApp] Accepting token-authenticated connection from 127.0.0.1
[D 16:43:48.931 LabApp] 200 GET /lab/api/workspaces/lab?1578741228778 (127.0.0.1) 5.17ms
[D 16:43:48.932 LabApp] Accepting token-authenticated connection from 127.0.0.1
[E 16:43:48.975 LabApp] Uncaught exception GET /lab/api/extensions?1578741228850 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/lab/api/extensions?1578741228850', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 222, in get
        extensions = yield self.manager.list_extensions()
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 86, in list_extensions
        build_check_info = _build_check_info(app_options)
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/handlers/extension_manager_handler.py", line 56, in _build_check_info
        messages = handler.build_check(fast=True)
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/commands.py", line 760, in build_check
        new_package = self._get_package_template(silent=fast)
      File "/home/terabyte/.pyenv/versions/3.7.5/lib/python3.7/site-packages/jupyterlab/commands.py", line 1241, in _get_package_template
        data['jupyterlab']['mimeExtensions'].pop(item)
    KeyError: '@deathbeds/jupyterlab-fonts'
[W 16:43:48.976 LabApp] Unhandled error
[E 16:43:48.977 LabApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0",
      "Accept": "*/*",
      "Accept-Language": "en-US",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/lab",
      "Authorization": "token 1197dff664ecf718d19b9495de0aa1b3b1177ead9c06a23d",
      "X-Xsrftoken": "2|ba18a2ae|d10e87fbb2ea69eea93a532bfa895180|1577660620",
      "Content-Type": "application/json",
      "Connection": "keep-alive",
      "Cookie": "_xsrf=2|ba18a2ae|d10e87fbb2ea69eea93a532bfa895180|1577660620; username-localhost-8888=\"2|1:0|10:1578741228|23:username-localhost-8888|44:MmQxMDkwODZkYTE3NGRjNWFjOTVmZWJjYmQ1ZTVmMTI=|c65a14dcbb86d630bc5e29e347ba6cc036e83ace103d0011352f33db1619dd68\"; connect.sid=s%3ATMTi2en79es3bO_JGoN0sMfDiDTdvh7P.3Hy%2BuoCBk%2BVR%2FKGiW8EtF6%2B4QOXYcvh8xBUCUteeZc0; org.cups.sid=f56a241e8b56cbc7fd776d5efc95356c; GRABIFY=s%3ADAR5ZzVVn1cRPbTXkpZsUAHoKO77N3Qi.D66FykPGV29N%2BGNe1TNVr18wtM9PWUK4H3vfreuWir4",
      "Pragma": "no-cache",
      "Cache-Control": "no-cache"
    }
[E 16:43:48.977 LabApp] 500 GET /lab/api/extensions?1578741228850 (127.0.0.1) 44.65ms referer=http://localhost:8888/lab
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
schema id ignored /ISettings 54 vendors~main.581e98018a758530a69d.js:1:2581557
Starting application in workspace: "/lab" vendors~main.581e98018a758530a69d.js:1:2567000
Error: Invalid response: 500 Internal Server Error vendors~main.581e98018a758530a69d.js:1:2331073
</pre>
</details>

**Comment by Spriithy** [comment]
Same problem here

**Comment by Spriithy** [comment]
Installing latest nodejs version from upstream packages solved the issue for me.
