### ISSUE TITLE
jupyterlab 2.0.0b3 does not start with jupyterhub

### ISSUE THREAD

**Issue by enriqueartal** [jupyterlab/jupyterlab#7775]
I have tried version 2.0.0b2 in several computers. If I launch it directly it does not start, the browser asks for waiting or cleaning workspace; in both cases the page stays with jupyter lab logo, no logs indicate the problem even with the option --label. 
In other computer, which uses jupyterhub, it complains about not finding labhubapp module. No problems when using 2.0.0a2 in all those computers. Thanks, Enrique.

**Comment by enriqueartal** [comment]
Solved in 2.0.0b3

**Comment by enriqueartal** [comment]
-jupyterlab 2.0.0b3 starts locally but not with jupyterhub. No clue from logs (extension has been updated).

**Comment by blink1073** [comment]
Hi @enriqueartal, we removed `labhubapp` in 2.0 beta, you can use `c.Spawner.default_url = '/lab'` in your config.  I opened https://github.com/jupyterlab/jupyterlab/pull/7844 to make a note of this in the change log.

**Comment by enriqueartal** [comment]
It works for me now. I replaced c.Spawner.cmd = ['jupyter-labhub'] by c.Spawner.cmd = ['jupyterhub-singleuser'] in the config file.

Thanks!
