### ISSUE TITLE
Kernel selection dialog style issue

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#7778]
The down arrow in the kernel selection dialog is a bit off.

![image](https://user-images.githubusercontent.com/591645/72262883-1654e980-3618-11ea-98fc-a22dc7fd2ff7.png)

This is from the latest `master` (57cd4545b93606177950e7189d03394b26c63b0c)

**Comment by ggbhat** [comment]
Issue is reproducible.
Since the select box is inside the dialog box and dialog box is flex container. Also the padding for label inside the **JP-dialog-body** is different from the other places like the one in Property Inspector.

**Comment by jasongrout** [comment]
Thanks for narrowing down the cause so specifically. Do you want to put in a PR?
