### ISSUE TITLE
Jupyterlab 1.2.5 unable to browse desktop, downloads and documents

### ISSUE THREAD

**Issue by kochargs** [jupyterlab/jupyterlab#7795]
I recently installed Jupyterlab and after i launch it, i am unable to browse contents of Desktop, Documents and Downloads. Every other directory that it lists, i am able to browse into except these three where majority of my work is. I can click on these three folders repeated but nothing happens.

Anaconda navigator 1.9.7
Jupterlab 1.2.5
jupyter notebook 6.0.2

However, jupyternotebook works perfectly fine.

Not to mention
I have rebooted OS
clean installed anaconda navigator as mentioned on their website.
Still same issue

If i repeatedly click on any of these folders, i get this error message in anaconda-navigator

[I 00:38:38.023 LabApp] The port 8888 is already in use, trying another port.
[I 00:38:38.024 LabApp] The port 8889 is already in use, trying another port.
[I 00:38:38.024 LabApp] The port 8890 is already in use, trying another port.
[I 00:38:38.032 LabApp] JupyterLab extension loaded from /Users/a608938866/opt/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 00:38:38.032 LabApp] JupyterLab application directory is /Users/a608938866/opt/anaconda3/share/jupyter/lab
[I 00:38:38.083 LabApp] Serving notebooks from local directory: /Users/a608938866
[I 00:38:38.083 LabApp] The Jupyter Notebook is running at:
[I 00:38:38.083 LabApp] http://localhost:8891/?token=9c0f1d2e813ecda4a37bc4b0f932afa62ce1ab3749352a7a
[I 00:38:38.083 LabApp] or http://127.0.0.1:8891/?token=9c0f1d2e813ecda4a37bc4b0f932afa62ce1ab3749352a7a
[I 00:38:38.083 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:38:38.090 LabApp] 

To access the notebook, open this file in a browser:
file:///Users/a608938866/Library/Jupyter/runtime/nbserver-11144-open.html
Or copy and paste one of these URLs:
http://localhost:8891/?token=9c0f1d2e813ecda4a37bc4b0f932afa62ce1ab3749352a7a
or http://127.0.0.1:8891/?token=9c0f1d2e813ecda4a37bc4b0f932afa62ce1ab3749352a7a
[W 00:38:40.330 LabApp] Could not determine jupyterlab build status without nodejs
[E 00:38:44.801 LabApp] Uncaught exception GET /api/contents/Downloads?content=1&1579288124796 (::1)
HTTPServerRequest(protocol='http', host='localhost:8891', method='GET', uri='/api/contents/Downloads?content=1&1579288124796', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
File "/Users/a608938866/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
result = await result
File "/Users/a608938866/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
yielded = next(result)
File "/Users/a608938866/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get
path=path, type=type, format=format, content=content,
File "/Users/a608938866/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 427, in get
model = self._dir_model(path, content=content)
File "/Users/a608938866/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 309, in _dir_model
for name in os.listdir(os_dir):
PermissionError: [Errno 1] Operation not permitted: '/Users/a608938866/Downloads'
[W 00:38:44.809 LabApp] Unhandled error
[E 00:38:44.810 LabApp] {
"Host": "localhost:8891",
"Connection": "keep-alive",
"Authorization": "token 9c0f1d2e813ecda4a37bc4b0f932afa62ce1ab3749352a7a",
"X-Xsrftoken": "2|dd729d6f|7f61424b99dedd4fa186e961c4f38c87|1577702576",
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36",
"Content-Type": "application/json",
"Accept": "*/*",
"Sec-Fetch-Site": "same-origin",
"Sec-Fetch-Mode": "cors",
"Referer": "http://localhost:8891/lab",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
"Cookie": "_xsrf=2|dd729d6f|7f61424b99dedd4fa186e961c4f38c87|1577702576; username-localhost-8888=\"2|1:0|10:1579286642|23:username-localhost-8888|44:OThmNWI3N2VmNGE0NGE3ZDk5YTlmM2IzZDJjYTdiM2Q=|5ea544d56ed424f70995894f4278ee0740e3f935b0a389ae143c54e69042baad\"; username-localhost-8889=\"2|1:0|10:1579287776|23:username-localhost-8889|44:YjI2MWJmMmJmNGE3NGQ5MmEyMDM1ZjUwNDY3MDExNzk=|39ec39b11f931dc9247fcd880baac4df3c5a4e60571de7f63b0d02fb51f682f8\"; username-localhost-8890=\"2|1:0|10:1579288116|23:username-localhost-8890|44:N2M4MjU4OWMyODdlNGU0NzlkOGIyZTczYmRlOGNlYTI=|750bbfb56cb47f4ead80f6e7b20ee7047074b82354d1155590b31617d2dbe04f\"; username-localhost-8891=\"2|1:0|10:1579288124|23:username-localhost-8891|44:MTExNTE3ZjIyZWY5NGQ0N2FkZTMyYjI1YzllZWExYmY=|ab32e97344a52bacd42485f1a6b8758731ef28129ae24ad0147f11de6c9901ee\""
}
[E 00:38:44.810 LabApp] 500 GET /api/contents/Downloads?content=1&1579288124796 (::1) 10.81ms referer=http://localhost:8891/lab
[E 00:38:46.339 LabApp] Uncaught exception GET /api/contents/Documents?content=1&1579288126334 (::1)
HTTPServerRequest(protocol='http', host='localhost:8891', method='GET', uri='/api/contents/Documents?content=1&1579288126334', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
File "/Users/a608938866/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
result = await result
File "/Users/a608938866/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
yielded = next(result)
File "/Users/a608938866/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get
path=path, type=type, format=format, content=content,
File "/Users/a608938866/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 427, in get
model = self._dir_model(path, content=content)
File "/Users/a608938866/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 309, in _dir_model
for name in os.listdir(os_dir):
PermissionError: [Errno 1] Operation not permitted: '/Users/a608938866/Documents'
[W 00:38:46.340 LabApp] Unhandled error
[E 00:38:46.341 LabApp] {
"Host": "localhost:8891",
"Connection": "keep-alive",
"Authorization": "token 9c0f1d2e813ecda4a37bc4b0f932afa62ce1ab3749352a7a",
"X-Xsrftoken": "2|dd729d6f|7f61424b99dedd4fa186e961c4f38c87|1577702576",
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36",
"Content-Type": "application/json",
"Accept": "*/*",
"Sec-Fetch-Site": "same-origin",
"Sec-Fetch-Mode": "cors",
"Referer": "http://localhost:8891/lab",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
"Cookie": "_xsrf=2|dd729d6f|7f61424b99dedd4fa186e961c4f38c87|1577702576; username-localhost-8888=\"2|1:0|10:1579286642|23:username-localhost-8888|44:OThmNWI3N2VmNGE0NGE3ZDk5YTlmM2IzZDJjYTdiM2Q=|5ea544d56ed424f70995894f4278ee0740e3f935b0a389ae143c54e69042baad\"; username-localhost-8889=\"2|1:0|10:1579287776|23:username-localhost-8889|44:YjI2MWJmMmJmNGE3NGQ5MmEyMDM1ZjUwNDY3MDExNzk=|39ec39b11f931dc9247fcd880baac4df3c5a4e60571de7f63b0d02fb51f682f8\"; username-localhost-8890=\"2|1:0|10:1579288116|23:username-localhost-8890|44:N2M4MjU4OWMyODdlNGU0NzlkOGIyZTczYmRlOGNlYTI=|750bbfb56cb47f4ead80f6e7b20ee7047074b82354d1155590b31617d2dbe04f\"; username-localhost-8891=\"2|1:0|10:1579288124|23:username-localhost-8891|44:NTI5ZTMzODA0ZjI5NGY1ZDk2NTg5MDBlYWRlYmI0OWY=|824a5669276690952619b7dd018c64a74c8c43aef5c0c92ba28c4760d9be1a4c\""
}
[E 00:38:46.341 LabApp] 500 GET /api/contents/Documents?content=1&1579288126334 (::1) 3.82ms referer=http://localhost:8891/lab

**Comment by jasongrout** [comment]
Did you figure out what the issue was?

**Comment by kochargs** [comment]
i have to launch jupyter lab from CLI instead of anaconda gui and it works fine
