### ISSUE TITLE
Create clickable link to open local jupyter notebook in new jupyterlab tab

### ISSUE THREAD

**Issue by JackWehr** [jupyterlab/jupyterlab#7801]
I would like to output from a cell a clickable link to a jupyter notebook which opens in a jupyterlab tab.  This issue is somewhat similar to [#6235], however the link would be the output of a cell, hosted locally, and opened in a new jupyterlab tab as opposed to in an Iframe.

I have attempted:
`print(display(HTML("""<a href="%s">%s</a>"""%('http://localhost:8888/tree/Path/To/File.ipynb','Link'))))
`
which creates a clickable link which opens the notebook in a new *chrome* tab, and 

`print(display(HTML("""<a href="%s">%s</a>"""%('http://localhost:8888/lab/tree/Path/To/File.ipynb','Link'))))`

which creates a link which opens the notebook in a *new instance* of jupyterlab in a new chrome tab.

I understand that this can be achieved very easily in a markdown cell, however I need the links to be generated based on search results, so a code cell is required. Is this possible?

Cheers!
Jack

**Comment by vidartf** [comment]
If you are able to do it in a markdown cell, maybe you will have some luck using the `Markdown` output type?

```python
from IPython.display import Markdown
```

**Comment by JackWehr** [comment]
> If you are able to do it in a markdown cell, maybe you will have some luck using the `Markdown` output type?
> 
> ```python
> from IPython.display import Markdown
> ```

Wow, that seems like it would work very well! Thank you, I can't believe I missed that solution. I'm having an unrelated problem while trying to run code at the moment, but I'll verify this works and close the issue when I am in a position to give it a try.
