### ISSUE TITLE
Add kernel and session architecture diagram

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#7809]
There is currently a good overview of the different kernel related concepts in the [services README.md](https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/README.md#overview)

I wonder whether there could also be a diagram that explains how all the different components talk to each other. Maybe something similar to the one posted in https://github.com/jupyterlab/jupyterlab/pull/7252#issuecomment-539489451:

![image](https://user-images.githubusercontent.com/591645/72898715-e64acc00-3d24-11ea-81a2-0d075d7cc383.png)

Maybe the exact same diagram could be used, unless some of the inner details have changed.

**Comment by vidartf** [comment]
I think this is still accurate in explaining how things are in the most common case in lab, but @jasongrout  would have to confirm.

**Comment by jasongrout** [comment]
The "ClientSession" is now "SessionContext", but other than that, I think it is still essentially accurate. I suppose it's a little confusing that SessionConnection contains KernelConnection, but SessionContext is off to the side. In reality, SessionContext has a reference to a SessionConnection (or null), which in turn has a reference to a KernelConnection (or null). Thanks!

**Comment by jasongrout** [comment]
And I suppose all the "WS Bridge" boxes should be inside a "Jupyter Server" box to indicate that they are part of the server.
