### ISSUE TITLE
Default option when opening html file

### ISSUE THREAD

**Issue by mocquin** [jupyterlab/jupyterlab#7811]
Hello there,

when opening a html file, the file is, by default, opened by displaying the rendered html, not the raw data. Is it possible to configure jupyterlab to open the document within the text editor by default ?

Cheers

**Comment by ggbhat** [comment]
I don't think as of now you can have any settings for setting editor as default option. Looking at the below code it looks first option is selected by default from the **preferredWidgetFactories** method
https://github.com/jupyterlab/jupyterlab/blob/643352189fbac92c96e57f0bbe3d2bc3e53cf090/packages/docregistry/src/registry.ts#L433
https://github.com/jupyterlab/jupyterlab/blob/643352189fbac92c96e57f0bbe3d2bc3e53cf090/packages/docregistry/src/registry.ts#L437

**Comment by ggbhat** [comment]
Yes you can change the settings from advanced settings editor. Like below
```
{
        
defaultViewers: {
      html: "Editor"
     }

} 
```

**Comment by mocquin** [comment]
I feel stupid not thinking to check the advanced settings...
Works like a charm ! Thanks a lot !
