### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#7814]
After switching over to React 16.9.x (https://github.com/jupyterlab/jupyterlab/pull/7661), we now get the following warning when opening a JSON file with the JSON viewer:

![image](https://user-images.githubusercontent.com/591645/72979798-6599d780-3dd9-11ea-8b40-390c088e3d2f.png)

This seems to be an issue with the `react-json-tree` package, which has been reported here: https://github.com/reduxjs/redux-devtools/issues/480

**Comment by jtpio** [comment]
Ideally this would be fixed upstream in https://github.com/reduxjs/redux-devtools, but it looks there hasn't been a lot of activity for the past year.

**Comment by nscozzaro** [comment]
I see this warning in the console too, even without loading the JSON viewer.

**Comment by jtpio** [comment]
This should now be fixed by https://github.com/jupyterlab/jupyterlab/pull/8921.

The `componentWillReceiveProps` warning is not displayed anymore with `JupyterLab v3.0.0b1`.
