### ISSUE TITLE
Please post this details on closed issue 4662

### ISSUE THREAD

**Issue by MatMaul** [jupyterlab/jupyterlab#7815]
Hi,

Can a maintainer comment on closed issue #4662 to specify that it is probably related to a bug in Chrome with self signed certs ?

More infos here:
https://stackoverflow.com/questions/58086327/google-chrome-neterr-too-many-retries
https://bugs.chromium.org/p/chromium/issues/detail?id=488043

Thanks !

**Comment by blink1073** [comment]
Thanks @MatMaul, done!
