### ISSUE TITLE
Shift Tab in Editor

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#7821]
## Description
`tab` works as expected in the text editor, but `shift-tab` does not.

## Reproduce
Open a file like `foo.py` to use the text editor. Push `tab` and it will indent. Push `shift+tab` and it will not dedent.

## Expected behavior
This should work identical to notebook cells (i.e. `shift+tab` should dedent).

## Context

- Operating System and version: Windows
- Browser and version: Chrome
- JupyterLab version: 1.2.3

**Comment by ian-r-rose** [comment]
This is a bit subtle, but I believe that it currently works as expected. Tab completions can get completions from both the kernel and from the tokens in the text editor. When a python file has a kernel attached to it, it gets both, but when it has no kernel it only gets the latter. I suspect this is what you are seeing with <kbd>Tab</kbd> completions.

However, the <kbd>Shift</kbd>+<kbd>Tab</kbd> tooltips require a kernel connection to work, so they will *only* show up if there is a kernel attached to the text file. Can you try attaching a console with a live python session to see if you get tooltips?

cf #5049

**Comment by vidartf** [comment]
@ian-r-rose The way I'm reading this issue it is about using (shift) tab for indenting/dedenting, not completions. Is the indentation behavior related to the completion state somehow?

**Comment by jasongrout** [comment]
For compatibility with the classic notebook, pressing shift-tab in a place where completions are valid is supposed to bring up a more extensive help than just pressing tab. Pressing shift-tab at the start of a line (or perhaps anywhere in the whitespace indent at the start of a line), or pressing shift-tab when text is selected, should dedent, IIRC.

**Comment by ian-r-rose** [comment]
@vidartf you are right, my mistake, disregard the above.

**Comment by jasongrout** [comment]
> @vidartf you are right, my mistake, disregard the above.

Oh, right, this is an issue for just the text editor, not the notebook. Yep, disregard my comment as well, which was focused on the notebook.

**Comment by vidartf** [comment]
Fixed via #6127.
