### ISSUE TITLE
Focus issues when deleting a cell

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#7822]
## Description

When deleting a cell in the middle of a notebook with a large amount of output, the focus jumps incorrectly. The current active cell is not in focus and instead it scrolls to the bottom.

## Reproduce
This gif is a contrived example, but shows off the issue. You need to scroll somewhere in the output for this bug to be triggered. I would have expected the cell below the one that was cut to be centered on screen instead of this scrolling to the end of the notebook.
![funnyscroll](https://user-images.githubusercontent.com/1813603/73105748-b7b92680-3ec7-11ea-92f1-0247ae6d7147.gif)

## Context

- Operating System and version: Windows
- Browser and version: Chrome
- JupyterLab version: 1.2.3

**Comment by lemonad** [comment]
I also see some weird bugs related to this, even seems to delete the wrong cell sometimes. JupyterLab 2.0.0b2 on MacOS using Safari.

**Comment by saulshanabrook** [comment]
I was able to reproduce this on master. The issue seems to be a bit more broad. Anytime you delete a cell, it doesn't bring the newly highlighted cell into view. It seems like it *should* do this, to be consistent with adding a cell, which does bring it into view. I am looking into this.
