### ISSUE TITLE
jupyter lab build fails with [Errno 13] permission denied on WSL

### ISSUE THREAD

**Issue by duichwer** [jupyterlab/jupyterlab#7831]
## Description
After the command `jupyter lab build` I receive the following error

```bash

[LabBuildApp] JupyterLab 1.2.6
[LabBuildApp] Building in /mnt/d/User/testuser/folder/folder/.venv/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
An error occured.
shutil.Error: [('/mnt/d/User/testuser/folder/folder/.venv/lib/python3.6/site-packages/jupyterlab/staging/templates', '/mnt/d/User/testuser/folder/folder/.venv/share/jupyter/lab/staging/templates', "[Errno 13] Permission denied: '/mnt/d/User/testuser/folder/folder/.venv/share/jupyter/lab/staging/templates'")]
See the log file for details:  /tmp/jupyterlab-debug-3m7e3mf9.log
```

Log file:
```
[LabBuildApp] Building in /mnt/d/User/testuser/folder/folder/.venv/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v10.16.3

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/mnt/d/User/testuser/folder/folder/.venv/lib/python3.6/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/mnt/d/User/testuser/folder/folder/.venv/lib/python3.6/site-packages/jupyterlab/labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/mnt/d/User/testuser/folder/folder/.venv/lib/python3.6/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/mnt/d/User/testuser/folder/folder/.venv/lib/python3.6/site-packages/jupyterlab/commands.py", line 650, in build
    clean=clean_staging

[LabBuildApp]   File "/mnt/d/User/testuser/folder/folder/.venv/lib/python3.6/site-packages/jupyterlab/commands.py", line 1111, in _populate_staging
    shutil.copytree(pjoin(HERE, 'staging', 'templates'), templates)

[LabBuildApp]   File "/usr/lib/python3.6/shutil.py", line 365, in copytree
    raise Error(errors)

[LabBuildApp] shutil.Error: [('/mnt/d/User/testuser/folder/folder/.venv/lib/python3.6/site-packages/jupyterlab/staging/templates', '/mnt/d/User/testuser/folder/folder/.venv/share/jupyter/lab/staging/templates',$
[LabBuildApp] Exiting application: JupyterLab
```
## Reproduce

1. I created a new venv with poetry with package jupyterlab
2. I added the jupylab extensions for plotly, user-logging and git with --no-build
3. Execute jupyter lab build

## Expected behavior

Build dependencies

## Context

- Operating System and version: Windows 10 with WSL (Ubuntu)
- Browser and version: google chrome
- JupyterLab version: 1.2.6

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /mnt/d/User/testuser/folder/folder/.venv/bin
        /home/testuser/.nvm/versions/node/v10.16.3/bin
        /home/testuser/.local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games
        /mnt/c/Perl64/site/bin
        /mnt/c/Perl64/bin
        /mnt/c/Program Files/Haskell/bin
        /mnt/c/Program Files/Haskell Platform/8.0.2-a/lib/extralibs/bin
        /mnt/c/Program Files/Haskell Platform/8.0.2-a/bin
        /mnt/c/Program Files/Python36/Scripts/
        /mnt/c/Program Files/Python36/
        /mnt/c/Program Files (x86)/Python36-32/Scripts/
        /mnt/c/Program Files (x86)/Python36-32/
        /mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath
        /mnt/c/program files/graphicsmagick-1.3.24-q8
        /mnt/c/ProgramData/Oracle/Java/javapath
        /mnt/c/Program Files/Java/jdk1.7.0_80/bin
        /mnt/c/Program Files (x86)/Razer Chroma SDK/bin
        /mnt/c/Program Files/Razer Chroma SDK/bin
        /mnt/c/Program Files (x86)/Intel/iCLS Client/
        /mnt/c/Program Files/Intel/iCLS Client/
        /mnt/c/Windows/system32
        /mnt/c/Windows
        /mnt/c/Windows/System32/Wbem
        /mnt/c/Windows/System32/WindowsPowerShell/v1.0/
        /mnt/c/Program Files (x86)/Windows Live/Shared
        /mnt/c/Program Files/Intel/WiFi/bin/
        /mnt/c/Program Files/Common Files/Intel/WirelessCommon/
        /mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL
        /mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT
        /mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL
        /mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT
        /mnt/c/WINDOWS/system32
        /mnt/c/WINDOWS
        /mnt/c/WINDOWS/System32/Wbem
        /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/
        /mnt/c/Program Files (x86)/PuTTY/
        /mnt/c/Program Files (x86)/WinSCP/
        /mnt/c/WINDOWS/system32/config/systemprofile/AppData/Local/Microsoft/WindowsApps
        /mnt/c/Program Files (x86)/Pandoc/
        /mnt/c/Strawberry/c/bin
        /mnt/c/Strawberry/perl/site/bin
        /mnt/c/Strawberry/perl/bin
        /mnt/c/Program Files (x86)/Skype/Phone/
        /mnt/c/Coq/bin
        /mnt/c/Program Files (x86)/Codebox/BitMeterOS
        /mnt/c/Program Files/Git LFS
        /mnt/c/Program Files/Haskell Platform/8.0.2-a/mingw/bin
        /mnt/c/Program Files/nodejs/
        /mnt/c/WINDOWS/System32/OpenSSH/
        /mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR
        /mnt/c/Program Files/PuTTY/
        /mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
        /mnt/c/Program Files (x86)/Brackets/command
        /mnt/c/WINDOWS/system32
        /mnt/c/WINDOWS
        /mnt/c/WINDOWS/System32/Wbem
        /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/
        /mnt/c/WINDOWS/System32/OpenSSH/
        /mnt/c/Program Files/Git/cmd
        /mnt/c/Users/testuser/AppData/Roaming/cabal/bin
        /mnt/c/Users/testuser/AppData/Local/atom/bin
        /mnt/c/Users/testuser/AppData/Local/Microsoft/WindowsApps
        /mnt/c/Users/testuser/AppData/Local/Programs/MiKTeX 2.9/miktex/bin/
        /mnt/c/Program Files/Docker Toolbox
        /mnt/c/Users/testuser/.babun
        /mnt/c/Users/testuser/AppData/Roaming/npm
        /mnt/c/Users/testuser/AppData/Local/hyper/app-3.0.2/resources/bin
        /mnt/c/Users/testuser/AppData/Local/Programs/Microsoft VS Code/bin

sys.path:
        /mnt/d/User/testuser/folder/folder/.venv/bin
        /usr/lib/python36.zip
        /usr/lib/python3.6
        /usr/lib/python3.6/lib-dynload
        /mnt/d/User/testuser/folder/folder/.venv/lib/python3.6/site-packages
        /mnt/d/User/testuser/folder/folder/.venv/src/dbcv
        /mnt/d/User/testuser/folder/folder/.venv/src/openensembles
        /mnt/d/User/testuser/folder/folder/src

sys.executable:
        /mnt/d/User/testuser/folder/folder/.venv/bin/python3

sys.version:
        3.6.8 (default, Oct  7 2019, 12:59:55)
        [GCC 8.3.0]

platform.platform():
        Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic

which -a jupyter:
        /mnt/d/User/testuser/folder/folder/.venv/bin/jupyter
        /home/testuser/.local/bin/jupyter

pip list:
        Package              Version    Location
        -------------------- ---------- ---------------------------------------------------------------------------------------
        -ensorflow           1.15.2
        absl-py              0.9.0
        apipkg               1.5
        appdirs              1.4.3
        astor                0.8.1
        astroid              2.3.3
        attrs                19.3.0
        backcall             0.1.0
        bandit               1.6.2
        benepar              0.1.2
        black                18.9b0
        bleach               3.1.0
        blis                 0.4.1
        boto3                1.11.9
        botocore             1.14.9
        catalogue            1.0.0
        certifi              2019.11.28
        chardet              3.0.4
        Click                7.0
        coverage             5.0.3
        cycler               0.10.0
        cymem                2.0.3      
        Cython               0.29.14
        dataclasses          0.6
        DBCV                 0.0.0      /mnt/d/User/testuser/folder/folder/.venv/src/dbcv
        decorator            4.4.1
        defusedxml           0.6.0
        dill                 0.3.1.1
        docutils             0.15.2
        dparse               0.4.1
        entrypoints          0.3
        execnet              1.7.1
        flake8               3.7.9
        ftfy                 5.6
        gast                 0.2.2
        gitdb2               2.0.6
        GitPython            3.0.5
        google-pasta         0.1.8
        grpcio               1.26.0
        h5py                 2.10.0
        hdbscan              0.8.24
        htmlmin              0.1.12
        idna                 2.8
        importlib-metadata   1.4.0
        ipykernel            5.1.4
        ipython              7.11.1
        ipython-genutils     0.2.0
        ipywidgets           7.5.1
        isort                4.3.21
        jedi                 0.16.0
        Jinja2               2.11.0
        jinja2-cli           0.7.0
        jmespath             0.9.4
        joblib               0.14.1
        jsmin                2.2.2
        json5                0.8.5
        jsonschema           3.2.0
        jupyter-client       5.3.4
        jupyter-core         4.6.1
        jupyterlab           1.2.6
        jupyterlab-server    1.0.6
        Keras-Applications   1.0.8
        Keras-Preprocessing  1.1.0
        kiwisolver           1.1.0
        lazy-object-proxy    1.4.3
        livereload           2.6.1
        Markdown             3.1.1
        MarkupSafe           1.1.1
        matplotlib           3.1.2
        mccabe               0.6.1
        mistune              0.8.4
        mkdocs               1.0.4
        mkdocs-material      4.6.0
        mkdocs-minify-plugin 0.2.1
        mkdocstrings         0.7.0
        more-itertools       8.1.0
        murmurhash           1.0.2      
        nbconvert            5.6.1
        nbformat             5.0.4
        networkx             2.4
        nltk                 3.4.5
        notebook             6.0.3
        numpy                1.18.1
        OpenEnsembles        1.1.1      /mnt/d/User/testuser/folder/folder/.venv/src/openensembles
        opt-einsum           3.1.0
        packaging            20.1
        pandas               0.25.3
        pandocfilters        1.4.2
        parso                0.6.0
        pbr                  5.4.4
        pep562               1.0
        pexpect              4.8.0
        pickleshare          0.7.5
        pip                  20.0.2
        pkg-resources        0.0.0
        plac                 1.1.3
        plotly               4.5.0
        pluggy               0.13.1
        preshed              3.0.2
        prometheus-client    0.7.1
        prompt-toolkit       3.0.3
        protobuf             3.11.2
        ptyprocess           0.6.0
        py                   1.8.1
        pycodestyle          2.5.0
        pyflakes             2.1.1
        Pygments             2.5.2
        pylint               2.4.4
        pymdown-extensions   6.2.1
        pyparsing            2.4.6
        pyrsistent           0.15.7
        pytest               5.3.4
        pytest-cov           2.8.1
        pytest-forked        1.1.3
        pytest-sugar         0.9.2
        pytest-xdist         1.31.0
        python-dateutil      2.8.1
        pytz                 2019.3
        PyYAML               5.3
        pyzmq                18.1.1
        regex                2020.1.8
        requests             2.22.0
        retrying             1.3.3
        rope                 0.16.0
        s-dbw                0.4.0
        s3transfer           0.3.2
        sacremoses           0.0.38
        safety               1.8.5
        scikit-learn         0.22.1
        scipy                1.4.1
        Send2Trash           1.5.0
        sentencepiece        0.1.85
        setuptools           39.0.1
        six                  1.14.0
        sklearn              0.0
        smmap2               2.0.5
        spacy                2.2.3
        spacy-conll          0.1.6
        spacy-transformers   0.5.1
        srsly                1.0.1
        stevedore            1.31.0
        syntacticpatterns    0.1.0      /mnt/d/User/testuser/folder/folder/src
        tensorboard          1.15.0
        tensorflow           1.15.2
        tensorflow-estimator 1.15.1
        termcolor            1.1.0
        terminado            0.8.3
        testpath             0.4.4
        thinc                7.3.1
        toml                 0.10.0
        torch                1.4.0
        torchcontrib         0.0.2
        tornado              6.0.3
        tqdm                 4.42.0
        traitlets            4.3.3
        transformers         2.0.0
        typed-ast            1.4.1
        urllib3              1.25.8
        wasabi               0.6.0
        wcwidth              0.1.8
        webencodings         0.5.1
        Werkzeug             0.16.1
        wheel                0.34.1
        widgetsnbextension   3.5.1
        wrapt                1.11.2
        zipp                 2.1.0
</pre>
</details>

**Comment by jasongrout** [comment]
Thanks. I'm assuming that for some reason `/mnt/d/User/testuser/folder/folder/.venv/share/jupyter/lab/staging/templates` does not have write permission, like the error message says? Do you know why that might be?

**Comment by duichwer** [comment]
No I have no idea. Especially I can touch a file from the bash console in this folder. (as proposed in the issue https://github.com/jupyterlab/jupyterlab/issues/5233)

I checked the permissions and the SYSTEM has write permissions.
Another normal user does not have permissions, but I thought that WSL uses the SYSTEM for access rights?
![image](https://user-images.githubusercontent.com/16852427/73315493-8a0a0f80-4230-11ea-961d-a634b3533fbb.png)

**Comment by jasongrout** [comment]
>  Another normal user does not have permissions, but I thought that WSL uses the SYSTEM for access rights?

Good question that I have no idea about. CC @ivanov, who might know about WSL and venv, or may otherwise help shed light on this.

**Comment by ivanov** [comment]
@duichwer - I am able to reproduce "permission denied" errors for a touch command from WSL on a folder where I deny the Administrator modification permission. Denying SYSTEM permission had no effect, so at least when WSL is run by an administrator (as is the case for me) - it seems to respect only the Administrator permissions.

**Comment by duichwer** [comment]
Okay.
I removed the virtual environment and started with a fresh one.
Now everything works fine.

Maybe this was related to poetry. The last time I installed my project with `poetry install` and I let poetry create the venv automatically. Then an error occured since the default pip version was to old.

Now I created the virtual environment manually (`python3.6 -m venv .venv`), added it afterwards to poetry (`poetry env use .venv/bin/python` and upgrade `pip` and `setuptools` before performing installation.

Both times, I executeted the commands with the same rights on the shell...

**Comment by a2975667** [comment]
I had the same problem and was not resolved after remove and recreate a virtual env. 
Setup: WSL on windows 10
Versions: 
```
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.13.0
ipykernel        : 5.2.1
jupyter client   : 6.1.3
jupyter lab      : 2.1.0
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.0.5
traitlets        : 4.3.3
```
Executed in a virtual env (through python3 -m venv) with python 3.8.
Are there any other ways I can troubleshoot?

**Comment by a2975667** [comment]
I tried so many different methods and it still doesn't work... What should I do?

**Comment by a2975667** [comment]
Is it related to this issue?
https://bugs.python.org/issue38633

**Comment by deilanexe** [comment]
I solved this by following the recommendation from @ivanov (run WSL as admin). After that, rebuilding the UI must have a couple of flags disabled:

`jupyter lab build --dev-build=False --minimize=False`

**Comment by a2975667** [comment]
That solved my problem. Thank you!

**Comment by ivanov** [comment]
@a2975667 and @duichwer have this working, so I'm going to go ahead and close this issue. Thanks, everyone, and happy hacking! :bowtie:
