### ISSUE TITLE
ipywidgets Button click is not working

### ISSUE THREAD

**Issue by DinisCruz** [jupyterlab/jupyterlab#7850]
## Description

ipywidgets Button click is not working on new version of Jupyter (this was working a couple months ago)

## Reproduce

Using this code:
```
import ipywidgets as widgets
button = widgets.Button(description='Display Chart')
out = widgets.Output()
def on_button_clicked(b):
    button.description = 'clicked'
    with out:
        print('Ay')

button.on_click(on_button_clicked)
widgets.VBox([button, out])
```

when I click on the button (see image below), nothing happens

![image](https://user-images.githubusercontent.com/656739/73831512-63367500-47fe-11ea-8e06-552e0062350f.png)

but when invoke the button directly using 

```button.click()```

it works

![image](https://user-images.githubusercontent.com/656739/73831588-7fd2ad00-47fe-11ea-8546-d77dd23a4b25.png)

## Expected behavior

Event should be triggered when I click the button

## Context
Running on Docker image build from "jupyter/base-notebook" last week

![image](https://user-images.githubusercontent.com/656739/73832101-70079880-47ff-11ea-81ed-1432845e5271.png)

<details><summary>Troubleshoot Output</summary>
<pre>
root@c6ca5be81992:~# jupyter troubleshoot
$PATH:
        /opt/conda/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /opt/conda/bin
        /opt/conda/lib/python37.zip
        /opt/conda/lib/python3.7
        /opt/conda/lib/python3.7/lib-dynload
        /opt/conda/lib/python3.7/site-packages

sys.executable:
        /opt/conda/bin/python

sys.version:
        3.7.4 (default, Aug 13 2019, 20:35:49)
        [GCC 7.3.0]

platform.platform():
        Linux-4.9.184-linuxkit-x86_64-with-debian-buster-sid

which -a jupyter:
        /opt/conda/bin/jupyter

pip list:
        Package                  Version
        ------------------------ -------------------
        aiohttp                  3.6.2
        alembic                  1.3.3
        async-generator          1.10
        async-timeout            3.0.1
        attrs                    19.3.0
        backcall                 0.1.0
        bleach                   3.1.0
        blinker                  1.4
        boto3                    1.11.9
        botocore                 1.14.9
        cachetools               4.0.0
        certifi                  2019.11.28
        certipy                  0.1.3
        cffi                     1.13.2
        chardet                  3.0.4
        conda                    4.7.12
        conda-package-handling   1.6.0
        cryptography             2.8
        cycler                   0.10.0
        decorator                4.4.1
        defusedxml               0.6.0
        docutils                 0.15.2
        elasticsearch            7.5.1
        entrypoints              0.3
        google-api-python-client 1.7.11
        google-auth              1.11.0
        google-auth-httplib2     0.0.3
        httplib2                 0.17.0
        idna                     2.8
        importlib-metadata       1.4.0
        ipykernel                5.1.3
        ipython                  7.11.1
        ipython-genutils         0.2.0
        ipywidgets               7.5.1
        jedi                     0.15.2
        Jinja2                   2.10.3
        jira                     2.0.0
        jmespath                 0.9.4
        json5                    0.8.5
        jsonschema               3.2.0
        jupyter-client           5.3.4
        jupyter-core             4.6.1
        jupyter-telemetry        0.0.4
        jupyterhub               1.1.0
        jupyterlab               1.2.5
        jupyterlab-server        1.0.6
        kiwisolver               1.1.0
        Mako                     1.1.0
        MarkupSafe               1.1.1
        matplotlib               3.1.2
        mistune                  0.8.4
        more-itertools           8.1.0
        multidict                4.7.4
        nbconvert                5.6.1
        nbformat                 5.0.4
        notebook                 6.0.3
        numpy                    1.18.1
        oauth2client             4.1.3
        oauthlib                 3.0.1
        osbot-aws                0.6.51
        osbot-gsuite             0.2.32
        osbot-jira               0.4.4
        osbot-jupyter            0.4.2
        packaging                20.1
        pamela                   1.0.0
        pandas                   0.25.3
        pandocfilters            1.4.2
        parso                    0.5.2
        pbr                      5.4.4
        pbx-gs-python-utils      0.5.1
        pexpect                  4.8.0
        pickleshare              0.7.5
        pip                      20.0.1
        pluggy                   0.13.1
        prometheus-client        0.7.1
        prompt-toolkit           3.0.2
        ptyprocess               0.6.0
        py                       1.8.1
        pyasn1                   0.4.8
        pyasn1-modules           0.2.8
        pycosat                  0.6.3
        pycparser                2.19
        pycurl                   7.43.0.4
        Pygments                 2.5.2
        PyJWT                    1.7.1
        pyOpenSSL                19.1.0
        pyparsing                2.4.6
        pyrsistent               0.15.7
        PySocks                  1.7.1
        pytest                   5.3.4
        pytest-json              0.4.0
        python-dateutil          2.8.1
        python-editor            1.0.4
        python-json-logger       0.1.11
        pytz                     2019.3
        pyzmq                    18.1.1
        qgrid                    1.2.0
        requests                 2.22.0
        requests-oauthlib        1.3.0
        requests-toolbelt        0.9.1
        rsa                      4.0
        ruamel-yaml              0.15.80
        ruamel.yaml              0.16.6
        ruamel.yaml.clib         0.2.0
        s3transfer               0.3.2
        Send2Trash               1.5.0
        setuptools               45.1.0.post20200119
        six                      1.14.0
        slackclient              2.5.0
        SQLAlchemy               1.3.13
        terminado                0.8.3
        testpath                 0.4.4
        tornado                  6.0.3
        tqdm                     4.41.1
        traitlets                4.3.3
        uritemplate              3.0.1
        urllib3                  1.25.7
        wcwidth                  0.1.8
        webencodings             0.5.1
        wheel                    0.33.6
        widgetsnbextension       3.5.1
        yarl                     1.4.2
        zipp                     2.0.0

conda list:
        # packages in environment at /opt/conda:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       0_gnu    conda-forge
        aiohttp                   3.6.2                    pypi_0    pypi
        alembic                   1.3.3                      py_0    conda-forge
        async-timeout             3.0.1                    pypi_0    pypi
        async_generator           1.10                       py_0    conda-forge
        attrs                     19.3.0                     py_0    conda-forge
        backcall                  0.1.0                      py_0    conda-forge
        bleach                    3.1.0                      py_0    conda-forge
        blinker                   1.4                        py_1    conda-forge
        boto3                     1.11.9                   pypi_0    pypi
        botocore                  1.14.9                   pypi_0    pypi
        ca-certificates           2019.11.28           hecc5488_0    conda-forge
        cachetools                4.0.0                    pypi_0    pypi
        certifi                   2019.11.28               py37_0    conda-forge
        certipy                   0.1.3                      py_0    conda-forge
        cffi                      1.13.2           py37h8022711_0    conda-forge
        chardet                   3.0.4                 py37_1003    conda-forge
        conda                     4.7.12                   py37_1    conda-forge
        conda-package-handling    1.6.0            py37h516909a_1    conda-forge
        configurable-http-proxy   4.2.0           node13_he01fd0c_2    conda-forge
        cryptography              2.8              py37h72c5cf5_1    conda-forge
        cycler                    0.10.0                   pypi_0    pypi
        decorator                 4.4.1                      py_0    conda-forge
        defusedxml                0.6.0                      py_0    conda-forge
        docutils                  0.15.2                   pypi_0    pypi
        elasticsearch             7.5.1                    pypi_0    pypi
        entrypoints               0.3                   py37_1000    conda-forge
        google-api-python-client  1.7.11                   pypi_0    pypi
        google-auth               1.11.0                   pypi_0    pypi
        google-auth-httplib2      0.0.3                    pypi_0    pypi
        httplib2                  0.17.0                   pypi_0    pypi
        icu                       64.2                 he1b5a44_1    conda-forge
        idna                      2.8                   py37_1000    conda-forge
        importlib_metadata        1.4.0                    py37_0    conda-forge
        ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
        ipython                   7.11.1           py37h5ca1d4c_0    conda-forge
        ipython_genutils          0.2.0                      py_1    conda-forge
        ipywidgets                7.5.1                    pypi_0    pypi
        jedi                      0.15.2                   py37_0    conda-forge
        jinja2                    2.10.3                     py_0    conda-forge
        jira                      2.0.0                    pypi_0    pypi
        jmespath                  0.9.4                    pypi_0    pypi
        json5                     0.8.5                      py_0    conda-forge
        jsonschema                3.2.0                    py37_0    conda-forge
        jupyter_client            5.3.4                    py37_1    conda-forge
        jupyter_core              4.6.1                    py37_0    conda-forge
        jupyter_telemetry         0.0.4                      py_0    conda-forge
        jupyterhub                1.1.0                    py37_0    conda-forge
        jupyterlab                1.2.5                      py_0    conda-forge
        jupyterlab_server         1.0.6                      py_0    conda-forge
        kiwisolver                1.1.0                    pypi_0    pypi
        krb5                      1.16.4               h2fd8d38_0    conda-forge
        libcurl                   7.65.3               hda55be3_0    conda-forge
        libedit                   3.1.20181209         hc058e9b_0    defaults
        libffi                    3.2.1             he1b5a44_1006    conda-forge
        libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
        libgomp                   9.2.0                h24d8f2e_2    conda-forge
        libsodium                 1.0.17               h516909a_0    conda-forge
        libssh2                   1.8.2                h22169c7_2    conda-forge
        libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
        libuv                     1.34.0               h516909a_0    conda-forge
        mako                      1.1.0                      py_0    conda-forge
        markupsafe                1.1.1            py37h516909a_0    conda-forge
        matplotlib                3.1.2                    pypi_0    pypi
        mistune                   0.8.4           py37h516909a_1000    conda-forge
        more-itertools            8.1.0                      py_0    conda-forge
        multidict                 4.7.4                    pypi_0    pypi
        nbconvert                 5.6.1                    py37_0    conda-forge
        nbformat                  5.0.4                      py_0    conda-forge
        ncurses                   6.1               hf484d3e_1002    conda-forge
        nodejs                    13.7.0               h10a4023_0    conda-forge
        notebook                  6.0.3                    py37_0    conda-forge
        numpy                     1.18.1                   pypi_0    pypi
        oauth2client              4.1.3                    pypi_0    pypi
        oauthlib                  3.0.1                      py_0    conda-forge
        openssl                   1.1.1d               h516909a_0    conda-forge
        osbot-aws                 0.6.51                   pypi_0    pypi
        osbot-gsuite              0.2.32                   pypi_0    pypi
        osbot-jira                0.4.4                    pypi_0    pypi
        osbot-jupyter             0.4.2                    pypi_0    pypi
        packaging                 20.1                     pypi_0    pypi
        pamela                    1.0.0                      py_0    conda-forge
        pandas                    0.25.3                   pypi_0    pypi
        pandoc                    2.9.1.1                       0    conda-forge
        pandocfilters             1.4.2                      py_1    conda-forge
        parso                     0.5.2                      py_0    conda-forge
        pbr                       5.4.4                    pypi_0    pypi
        pbx-gs-python-utils       0.5.1                    pypi_0    pypi
        pexpect                   4.8.0                    py37_0    conda-forge
        pickleshare               0.7.5                 py37_1000    conda-forge
        pip                       20.0.1                   py37_0    conda-forge
        pluggy                    0.13.1                   pypi_0    pypi
        prometheus_client         0.7.1                      py_0    conda-forge
        prompt_toolkit            3.0.2                      py_0    conda-forge
        ptyprocess                0.6.0                   py_1001    conda-forge
        py                        1.8.1                    pypi_0    pypi
        pyasn1                    0.4.8                    pypi_0    pypi
        pyasn1-modules            0.2.8                    pypi_0    pypi
        pycosat                   0.6.3           py37h516909a_1002    conda-forge
        pycparser                 2.19                     py37_1    conda-forge
        pycurl                    7.43.0.4         py37h16ce93b_0    conda-forge
        pygments                  2.5.2                      py_0    conda-forge
        pyjwt                     1.7.1                      py_0    conda-forge
        pyopenssl                 19.1.0                   py37_0    conda-forge
        pyparsing                 2.4.6                    pypi_0    pypi
        pyrsistent                0.15.7           py37h516909a_0    conda-forge
        pysocks                   1.7.1                    py37_0    conda-forge
        pytest                    5.3.4                    pypi_0    pypi
        pytest-json               0.4.0                    pypi_0    pypi
        python                    3.7.4                h265db76_1    defaults
        python-dateutil           2.8.1                      py_0    conda-forge
        python-editor             1.0.4                      py_0    conda-forge
        python-json-logger        0.1.11                     py_0    conda-forge
        pytz                      2019.3                   pypi_0    pypi
        pyzmq                     18.1.1           py37h1768529_0    conda-forge
        qgrid                     1.2.0                    pypi_0    pypi
        readline                  7.0               hf8c457e_1001    conda-forge
        requests                  2.22.0                   py37_1    conda-forge
        requests-oauthlib         1.3.0                    pypi_0    pypi
        requests-toolbelt         0.9.1                    pypi_0    pypi
        rsa                       4.0                      pypi_0    pypi
        ruamel.yaml               0.16.6           py37h516909a_0    conda-forge
        ruamel.yaml.clib          0.2.0            py37h516909a_0    conda-forge
        ruamel_yaml               0.15.80         py37h516909a_1000    conda-forge
        s3transfer                0.3.2                    pypi_0    pypi
        send2trash                1.5.0                      py_0    conda-forge
        setuptools                45.1.0                   py37_0    conda-forge
        six                       1.14.0                   py37_0    conda-forge
        slackclient               2.5.0                    pypi_0    pypi
        sqlalchemy                1.3.13           py37h516909a_0    conda-forge
        sqlite                    3.30.1               h7b6447c_0    defaults
        terminado                 0.8.3                    py37_0    conda-forge
        testpath                  0.4.4                      py_0    conda-forge
        tini                      0.18.0            h14c3975_1001    conda-forge
        tk                        8.6.10               hed695b0_0    conda-forge
        tornado                   6.0.3            py37h516909a_0    conda-forge
        tqdm                      4.41.1                     py_0    conda-forge
        traitlets                 4.3.3                    py37_0    conda-forge
        uritemplate               3.0.1                    pypi_0    pypi
        urllib3                   1.25.7                   py37_0    conda-forge
        wcwidth                   0.1.8                      py_0    conda-forge
        webencodings              0.5.1                      py_1    conda-forge
        wheel                     0.33.6                   py37_0    conda-forge
        widgetsnbextension        3.5.1                    pypi_0    pypi
        xz                        5.2.4             h14c3975_1001    conda-forge
        yaml                      0.2.2                h516909a_1    conda-forge
        yarl                      1.4.2                    pypi_0    pypi
        zeromq                    4.3.2                he1b5a44_2    conda-forge
        zipp                      2.0.0                      py_2    conda-forge
        zlib                      1.2.11            h516909a_1006    conda-forge</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
there are no relevant messages in the Command line Output
</pre>
</details>

<details><summary>Browser Output</summary>

<img src="https://user-images.githubusercontent.com/656739/73832410-05a32800-4800-11ea-9042-019048ae514c.png"/>

</details>

**Comment by DinisCruz** [comment]
actually just noticed that I also get this error on the console every time I click the button

```
[IPKernelApp] WARNING | No such comm: f6f62c76e20242e2b67677a6039e84f7
[IPKernelApp] WARNING | No such comm: f6f62c76e20242e2b67677a6039e84f7
[IPKernelApp] WARNING | No such comm: f6f62c76e20242e2b67677a6039e84f7
[IPKernelApp] WARNING | No such comm: f6f62c76e20242e2b67677a6039e84f7
[IPKernelApp] WARNING | No such comm: f6f62c76e20242e2b67677a6039e84f7
[IPKernelApp] WARNING | No such comm: f6f62c76e20242e2b67677a6039e84f7
```

**Comment by jasongrout** [comment]
It looks like, for some reason, the button's comm was closed down or something. I would try restarting your kernel to start fresh.

**Comment by vidartf** [comment]
Yeah, the "WebScoket closed unexpectedly" message seems important.

**Comment by rodrigosnader** [comment]
I'm having the exact same problem. The button worked for the last few days. Suddenly it does nothing when clicking, while `button.click()` performs the action. I've tested this in different conda environments and the problem doesn't seem related to module incompatibility. Any clues on what could be happening?

**Comment by nsingl00** [comment]
Hey @DinisCruz Did you find out any workaround/solution for this? I am also facing the same issue. My browser console shows no error

**Comment by jasongrout** [comment]
I just tried this in a clean install of the newest jupyter notebook and ipywidgets, and the code above gave a button, which when I clicked on it, changed button name and printed "Ay", just like the code indicates.
