### ISSUE TITLE
Cannot read file

### ISSUE THREAD

**Issue by nishant2019** [jupyterlab/jupyterlab#7852]
In spite of giving corrrect file path I am getting this message

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-18-a89a5f3567ee> in <module>
      3 from pydub import AudioSegment
      4 
----> 5 wav = AudioSegment.from_wav('D://audio_test//data/Acoustic_guitar/0356dec7.wav')
      6 wav=np.array(wav.get_array_of_samples()).astype(np.float32)
      7 S = librosa.feature.melspectrogram(wav, sr=16000, n_mels=128)

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\audio_segment.py in from_wav(cls, file, parameters)
    726     @classmethod
    727     def from_wav(cls, file, parameters=None):
--> 728         return cls.from_file(file, 'wav', parameters=parameters)
    729 
    730     @classmethod

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\audio_segment.py in from_file(cls, file, format, codec, parameters, **kwargs)
    663             stdin_data = file.read()
    664 
--> 665         info = mediainfo_json(orig_file)
    666         if info:
    667             audio_streams = [x for x in info['streams']

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pydub\utils.py in mediainfo_json(filepath)
    261 
    262     command = [prober, '-of', 'json'] + command_args
--> 263     res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
    264     output, stderr = res.communicate(input=stdin_data)
    265     output = output.decode("utf-8", 'ignore')

~\AppData\Local\Programs\Python\Python37\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    798                                 c2pread, c2pwrite,
    799                                 errread, errwrite,
--> 800                                 restore_signals, start_new_session)
    801         except:
    802             # Cleanup if the child failed starting.

~\AppData\Local\Programs\Python\Python37\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1205                                          env,
   1206                                          os.fspath(cwd) if cwd is not None else None,
-> 1207                                          startupinfo)
   1208             finally:
   1209                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by vidartf** [comment]
You seem to have an inconsistent use of slashes in your path: 'D://audio_test//data/Acoustic_guitar/0356dec7.wav'

**Comment by lresende** [comment]
@vidartf seems to have found the issue with the example above. Please reopen if you are still seeing issues.
