### ISSUE TITLE
Ship newer vega and vega-lite version

### ISSUE THREAD

**Issue by davidanthoff** [jupyterlab/jupyterlab#7853]
If I understand [this](https://github.com/jupyterlab/jupyterlab/blob/master/packages/vega5-extension/package.json) file correctly, then JupyterLab 2.0 will ship vega 5.9.0 and vega-lite 4.0.2, righ? There are newer versions of both of these available: vega 5.9.1 and vega-lite 4.1.1. Any chance that those versions could be shipped as part of JupyterLab 2.0?

CC @domoritz

**Comment by domoritz** [comment]
Since these are version ranges, updates to the yarn lockfile can happen at any time. The important file is https://github.com/jupyterlab/jupyterlab/blob/master/yarn.lock.

**Comment by jasongrout** [comment]
At this point, we've cut an RC, so unless there is a pressing reason to upgrade (like a security vulnerability), it's probably better to wait until 2.0.1 or 2.1 so that 2.0 is not delayed further.

**Comment by jasongrout** [comment]
(and it's a really good reason to test the 2.0 RC that was released!)

**Comment by davidanthoff** [comment]
Maybe there could be an item on future RC checklists “make sure we ship the latest versions of x, y, z”? So that just before an RC is tagged it becomes standard to update these deps?

**Comment by jasongrout** [comment]
We update things earlier in the release cycle (more like before a beta) so we have time to test the new updates all together. I think the last full refresh we had was on Christmas Eve, just over a month ago: https://github.com/jupyterlab/jupyterlab/commit/2fd9d0be6971449c5aff661a070ed1cd24a6b20f#diff-8ee2343978836a779dc9f8d6b794c3b2

**Comment by jasongrout** [comment]
And for the record, I think putting such an item on a checklist for a beta is a great idea!

**Comment by jasongrout** [comment]
I've added this to our checklist for 3.0 beta: https://github.com/jupyterlab/jupyterlab/issues/8038

**Comment by davidanthoff** [comment]
Does this mean that at least until mid August the version of vega and vega-lite that ships with Jupyterlab will be frozen at the version that shipped with Jupyterlab 2.0.0? That is _really_ long... Is there some way to ship updated versions in 2.0.x patch releases?

**Comment by jasongrout** [comment]
> Does this mean that at least until mid August the version of vega and vega-lite that ships with Jupyterlab will be frozen at the version that shipped with Jupyterlab 2.0.0?

That is the current plan

> That is _really_ long... Is there some way to ship updated versions in 2.0.x patch releases?

Probably not in 2.0.x patch releases (those are supposed to be pretty lightweight updates with very minimal risk), but perhaps as separate plugins that can be updated at will? Incidentally, this is one reason we don't ship ipywidgets in core, so we can release and update libraries independently of JupyterLab.

As a side note, it seems like we had discussions not too long ago about the desire to support versions of vega/vega-lite indefinitely (years and years) in the future as a stable format. This seems somewhat in tension with the idea that we need to update our version of vega we ship every month or so. Usually a format is either a stable format over a long term and updating the libraries dealing with that format happens on a longer timescale, or a format is evolving quickly and requires frequent updates for supporting libraries.
