### ISSUE TITLE
Cannot save large notebooks

### ISSUE THREAD

**Issue by hzfmer** [jupyterlab/jupyterlab#7854]
## Description
I was using jupyter lab on a **remote server**, and open the notebook on my local Chrome browser.
This worked fine before, but recently I found saving some large notebooks (as large as 50 M) can be really slow, or even impossible.

Because it keeps "starting" saving, any other executation is blocked until it finally fails to save. Then, even double pressing "Ctrl + C" in the terminal to exit jupyter turns reluctant:
>Shutdown this notebook server (y/[n])? No answer for 5s: resuming operation...
Most importantly, I cannot save the changes any more.

I was wondering if this could be just a preformance issue; or it might be some issue on the server side?

## Reproduce

1. Log in a remote server:    ssh -L 8032:localhost:8032 REMOTE_SERVER_NAME
2. Open any jupyter notebook:   jupyter lab --no-browser --port=8032
3. Click 'Save Notebook
4. See 'Saving Started', no error message in the terminal

## Expected behavior
The saving process should be finished within seconds.

## Context

- Operating System and version:  Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-redhat-7.6-Maipo
- Browser and version: Chrome 79.0.3945.130
- JupyterLab version: 1.2.4

<details><summary>Troubleshoot Output</summary>
<pre>
sys.version:
	3.7.6 (default, Jan  8 2020, 19:59:22)
	[GCC 7.3.0]

platform.platform():
	Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-redhat-7.6-Maipo
which -a jupyter:
	~/anaconda3/bin/jupyter

pip list:
	Package                            Version                 Location
	---------------------------------- ----------------------- -------------------------------------------------------------------------------
	alabaster                          0.7.12
	anaconda-client                    1.7.2
	anaconda-navigator                 1.9.7
	anaconda-project                   0.8.3
	asn1crypto                         1.2.0
	astroid                            2.3.3
	astropy                            4.0
	atomicwrites                       1.3.0
	attrs                              19.3.0
	autopep8                           1.4.4
	Babel                              2.8.0
	backcall                           0.1.0
	backports.functools-lru-cache      1.6.1
	backports.os                       0.1.1
	backports.shutil-get-terminal-size 1.0.0
	backports.tempfile                 1.0
	backports.weakref                  1.0.post1
	beautifulsoup4                     4.8.2
	bitarray                           1.2.0
	bkcharts                           0.2
	bleach                             3.1.0
	bokeh                              1.4.0
	boto                               2.49.0
	Bottleneck                         1.3.1
	certifi                            2019.11.28
	cffi                               1.13.2
	chardet                            3.0.4
	click                              6.7
	cloudpickle                        1.2.2
	clyent                             1.2.2
	colorama                           0.4.3
	conda                              4.8.1
	conda-build                        3.18.11
	conda-package-handling             1.6.0
	conda-verify                       3.4.2
	configobj                          5.0.6
	contextlib2                        0.6.0.post1
	cryptography                       2.8
	cycler                             0.10.0
	Cython                             0.29.14
	cytoolz                            0.10.1
	dask                               2.9.1
	decorator                          4.4.1
	defusedxml                         0.6.0
	distributed                        2.9.1
	docutils                           0.15.2
	entrypoints                        0.3
	et-xmlfile                         1.0.1
	fastcache                          1.1.0
	filelock                           3.0.12
	flake8                             3.7.9
	Flask                              1.1.1
	fsspec                             0.6.2
	future                             0.18.2
	gevent                             1.4.0
	glob2                              0.7
	globus-cli                         1.10.1
	globus-sdk                         1.7.1
	gmpy2                              2.0.8
	greenlet                           0.4.15
	h5py                               2.9.0
	HeapDict                           1.0.1
	html5lib                           1.0.1
	hypothesis                         4.54.2
	idna                               2.8
	imageio                            2.6.1
	imagesize                          1.2.0
	importlib-metadata                 1.3.0
	ipykernel                          5.1.3
	ipympl                             0.4.0
	ipython                            7.11.1
	ipython-genutils                   0.2.0
	ipywidgets                         7.5.1
	isort                              4.3.21
	itsdangerous                       1.1.0
	jdcal                              1.4.1
	jedi                               0.15.2
	jeepney                            0.4.1
	Jinja2                             2.10.3
	jmespath                           0.9.2
	joblib                             0.14.1
	json5                              0.8.5
	jsonschema                         3.2.0
	jupyter                            1.0.0
	jupyter-client                     5.3.4
	jupyter-console                    6.0.0
	jupyter-contrib-core               0.3.3
	jupyter-core                       4.6.1
	jupyter-lsp                        0.7.0b0
	jupyter-nbextensions-configurator  0.4.1
	jupyterlab                         1.2.4
	jupyterlab-server                  1.0.6
	jupyterlab-sql                     0.3.3
	keyring                            20.0.0
	kiwisolver                         1.1.0
	lazy-object-proxy                  1.4.3
	libarchive-c                       2.8
	lief                               0.9.0
	llvmlite                           0.30.0
	locket                             0.2.0
	lxml                               4.4.2
	MarkupSafe                         1.1.1
	matplotlib                         3.1.1
	mccabe                             0.6.1
	mistune                            0.8.4
	mkl-fft                            1.0.15
	mkl-random                         1.1.0
	mkl-service                        2.3.0
	mock                               3.0.5
	more-itertools                     8.0.2
	mpmath                             1.1.0
	msgpack                            0.6.1
	multipledispatch                   0.6.0
	navigator-updater                  0.2.1
	nbconvert                          5.6.1
	nbformat                           4.4.0
	networkx                           2.4
	nltk                               3.4.5
	nose                               1.3.7
	notebook                           6.0.2
	numba                              0.46.0
	numexpr                            2.7.0
	numpy                              1.17.4
	numpydoc                           0.9.2
	obspy                              1.1.1
	olefile                            0.46
	openpyxl                           3.0.2
	packaging                          20.0
	pandas                             0.25.3
	pandocfilters                      1.4.2
	parso                              0.5.2
	partd                              1.1.0
	path                               13.1.0
	pathlib2                           2.3.5
	patsy                              0.5.1
	pep8                               1.7.1
	pexpect                            4.7.0
	pickleshare                        0.7.5
	Pillow                             7.0.0
	pip                                19.3.1
	pkginfo                            1.5.0.1
	pluggy                             0.13.1
	ply                                3.11
	post-processing                    0.0.post0.dev1+ge888678 /autofs/nccs-svm1_home1/hzfmer/file_back/scripts/py_modules/post_processing/src
	pretty-errors                      1.2.10
	prometheus-client                  0.7.1
	prompt-toolkit                     2.0.9
	psutil                             5.6.7
	ptyprocess                         0.6.0
	py                                 1.8.1
	pycodestyle                        2.5.0
	pycosat                            0.6.3
	pycparser                          2.19
	pycrypto                           2.6.1
	pycurl                             7.43.0.3
	pydocstyle                         4.0.1
	pyflakes                           2.1.1
	Pygments                           2.5.2
	PyJWT                              1.7.1
	pylint                             2.4.4
	pynvim                             0.3.2
	pyodbc                             4.0.27
	pyOpenSSL                          19.1.0
	pyparsing                          2.4.6
	pyrotd                             0.5.4
	pyrsistent                         0.15.6
	PyScaffold                         3.2.2
	PySocks                            1.7.1
	pytest                             5.3.2
	pytest-arraydiff                   0.3
	pytest-astropy                     0.7.0
	pytest-astropy-header              0.1.1
	pytest-doctestplus                 0.5.0
	pytest-openfiles                   0.4.0
	pytest-remotedata                  0.3.2
	python-dateutil                    2.8.1
	python-jsonrpc-server              0.3.2
	python-language-server             0.31.2
	pytz                               2019.3
	PyWavelets                         1.1.1
	PyYAML                             5.2
	pyzmq                              18.1.0
	QtAwesome                          0.6.0
	qtconsole                          4.6.0
	QtPy                               1.9.0
	requests                           2.22.0
	rope                               0.14.0
	ruamel-yaml                        0.15.87
	scikit-image                       0.15.0
	scikit-learn                       0.22.1
	scipy                              1.3.2
	seaborn                            0.9.0
	SecretStorage                      3.1.1
	Send2Trash                         1.5.0
	setuptools                         44.0.0.post20200106
	simplegeneric                      0.8.1
	singledispatch                     3.4.0.3
	six                                1.13.0
	snowballstemmer                    2.0.0
	sortedcollections                  1.1.2
	sortedcontainers                   2.1.0
	soupsieve                          1.9.5
	Sphinx                             2.3.1
	sphinxcontrib-applehelp            1.0.1
	sphinxcontrib-devhelp              1.0.1
	sphinxcontrib-htmlhelp             1.0.2
	sphinxcontrib-jsmath               1.0.1
	sphinxcontrib-qthelp               1.0.2
	sphinxcontrib-serializinghtml      1.1.3
	sphinxcontrib-websupport           1.1.2
	spyder                             3.3.6
	spyder-kernels                     0.5.2
	SQLAlchemy                         1.3.12
	statsmodels                        0.10.1
	sympy                              1.5
	tables                             3.6.1
	tblib                              1.6.0
	terminado                          0.8.3
	testpath                           0.4.4
	toolz                              0.10.0
	tornado                            6.0.3
	tqdm                               4.40.2
	traitlets                          4.3.3
	ujson                              1.35
	unicodecsv                         0.14.1
	urllib3                            1.25.7
	wcwidth                            0.1.7
	webencodings                       0.5.1
	Werkzeug                           0.16.0
	wheel                              0.33.6
	widgetsnbextension                 3.5.1
	wrapt                              1.11.2
	wurlitzer                          2.0.0
	xlrd                               1.2.0
	XlsxWriter                         1.2.7
	xlwt                               1.3.0
	yapf                               0.28.0
	zict                               1.0.0
	zipp                               0.6.0

conda list:
	# packages in environment at /ccs/home/hzfmer/file_back/programs/rhea/anaconda3:
	#
	# Name                    Version                   Build  Channel
	_anaconda_depends         2019.03                  py37_0
	_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
	_libgcc_mutex             0.1                        main
	alabaster                 0.7.12                   py37_0
	anaconda                  custom                   py37_1
	anaconda-client           1.7.2                    py37_0
	anaconda-navigator        1.9.7                    py37_0
	anaconda-project          0.8.4                      py_0
	asn1crypto                1.2.0                    py37_0
	astroid                   2.3.3                    py37_0
	astropy                   4.0              py37h7b6447c_0
	atomicwrites              1.3.0                    py37_1
	attrs                     19.3.0                     py_0
	autopep8                  1.4.4                      py_0
	babel                     2.8.0                      py_0
	backcall                  0.1.0                    py37_0
	backports                 1.0                        py_2
	backports.functools_lru_cache 1.6.1                      py_0
	backports.os              0.1.1                    py37_0
	backports.shutil_get_terminal_size 1.0.0                    py37_2
	backports.tempfile        1.0                        py_1
	backports.weakref         1.0.post1                  py_1
	beautifulsoup4            4.8.2                    py37_0
	bitarray                  1.2.0            py37h7b6447c_0
	bkcharts                  0.2                      py37_0
	blas                      1.0                         mkl
	bleach                    3.1.0                    py37_0
	blosc                     1.16.3               hd408876_0
	bokeh                     1.4.0                    py37_0
	boto                      2.49.0                   py37_0
	bottleneck                1.3.1            py37hdd07704_0
	bzip2                     1.0.8                h7b6447c_0
	ca-certificates           2019.11.28           hecc5488_0    conda-forge
	cairo                     1.14.12              h8948797_3
	certifi                   2019.11.28               py37_0    conda-forge
	cffi                      1.13.2           py37h2e261b9_0
	chardet                   3.0.4                 py37_1003
	click                     7.0                      py37_0
	cloudpickle               1.2.2                      py_0
	clyent                    1.2.2                    py37_1
	colorama                  0.4.3                      py_0
	conda                     4.8.1                    py37_0
	conda-build               3.18.11                  py37_0
	conda-env                 2.6.0                         1
	conda-package-handling    1.6.0            py37h7b6447c_0
	conda-verify              3.4.2                      py_1
	contextlib2               0.6.0.post1                py_0
	cryptography              2.8              py37h1ba5d50_0
	curl                      7.67.0               hbc83047_0
	cycler                    0.10.0                   py37_0
	cython                    0.29.14          py37he6710b0_0
	cytoolz                   0.10.1           py37h7b6447c_0
	dask                      2.9.1                      py_0
	dask-core                 2.9.1                      py_0
	dbus                      1.13.12              h746ee38_0
	decorator                 4.4.1                      py_0
	defusedxml                0.6.0                      py_0
	distributed               2.9.1                      py_0
	docutils                  0.15.2                   py37_0
	entrypoints               0.3                      py37_0
	et_xmlfile                1.0.1                    py37_0
	expat                     2.2.6                he6710b0_0
	fastcache                 1.1.0            py37h7b6447c_0
	filelock                  3.0.12                     py_0
	flake8                    3.7.9                    py37_0
	flask                     1.1.1                      py_0
	fontconfig                2.13.0               h9420a91_0
	freetype                  2.9.1                h8a8886c_1
	fribidi                   1.0.5                h7b6447c_0
	fsspec                    0.6.2                      py_0
	future                    0.18.2                   py37_0
	get_terminal_size         1.0.0                haa9412d_0
	gevent                    1.4.0            py37h7b6447c_0
	glib                      2.63.1               h5a9c865_0
	glob2                     0.7                        py_0
	gmp                       6.1.2                h6c8ec71_1
	gmpy2                     2.0.8            py37h10f8cd9_2
	graphite2                 1.3.13               h23475e2_0
	greenlet                  0.4.15           py37h7b6447c_0
	gst-plugins-base          1.14.0               hbbd80ab_1
	gstreamer                 1.14.0               hb453b48_1
	h5py                      2.9.0            py37h7918eee_0
	harfbuzz                  1.8.8                hffaf4a1_0
	hdf5                      1.10.4               hb1b8bf9_0
	heapdict                  1.0.1                      py_0
	html5lib                  1.0.1                    py37_0
	hypothesis                4.54.2                   py37_0
	icu                       58.2                 h9c2bf20_1
	idna                      2.8                      py37_0
	imageio                   2.6.1                    py37_0
	imagesize                 1.2.0                      py_0
	importlib_metadata        1.3.0                    py37_0
	intel-openmp              2019.4                      243
	ipykernel                 5.1.3            py37h39e3cac_0
	ipympl                    0.4.0                      py_0    conda-forge
	ipython                   7.11.1           py37h39e3cac_0
	ipython_genutils          0.2.0                    py37_0
	ipywidgets                7.5.1                      py_0
	isort                     4.3.21                   py37_0
	itsdangerous              1.1.0                    py37_0
	jbig                      2.1                  hdba287a_0
	jdcal                     1.4.1                      py_0
	jedi                      0.15.2                   py37_0
	jeepney                   0.4.1                      py_0
	jinja2                    2.10.3                     py_0
	joblib                    0.14.1                     py_0
	jpeg                      9b                   h024ee3a_2
	json5                     0.8.5                      py_0
	jsonschema                3.2.0                    py37_0
	jupyter                   1.0.0                    py37_7
	jupyter-lsp               0.7.0b0                  pypi_0    pypi
	jupyter_client            5.3.4                    py37_0
	jupyter_console           6.0.0                    py37_0
	jupyter_contrib_core      0.3.3                      py_2    conda-forge
	jupyter_core              4.6.1                    py37_0
	jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
	jupyterlab                1.2.4              pyhf63ae98_0
	jupyterlab-sql            0.3.3                    pypi_0    pypi
	jupyterlab_server         1.0.6                      py_0
	keyring                   20.0.0                   py37_0
	kiwisolver                1.1.0            py37he6710b0_0
	krb5                      1.16.4               h173b8e3_0
	lazy-object-proxy         1.4.3            py37h7b6447c_0
	ld_impl_linux-64          2.33.1               h53a641e_7
	libarchive                3.3.3                h5d8350f_5
	libcurl                   7.67.0               h20c2e04_0
	libedit                   3.1.20181209         hc058e9b_0
	libffi                    3.2.1                hd88cf55_4
	libgcc-ng                 9.1.0                hdf63c60_0
	libgfortran-ng            7.3.0                hdf63c60_0
	liblief                   0.9.0                h7725739_2
	libpng                    1.6.37               hbc83047_0
	libsodium                 1.0.16               h1bed415_0
	libssh2                   1.8.2                h1ba5d50_0
	libstdcxx-ng              9.1.0                hdf63c60_0
	libtiff                   4.1.0                h2733197_0
	libtool                   2.4.6                h7b6447c_5
	libuuid                   1.0.3                h1bed415_2
	libxcb                    1.13                 h1bed415_1
	libxml2                   2.9.9                hea5a465_1
	libxslt                   1.1.33               h7d1a2b0_0
	llvmlite                  0.30.0           py37hd408876_0
	locket                    0.2.0                    py37_1
	lxml                      4.4.2            py37hefd8a0e_0
	lz4-c                     1.8.1.2              h14c3975_0
	lzo                       2.10                 h49e0be7_2
	markupsafe                1.1.1            py37h7b6447c_0
	matplotlib                3.1.1            py37h5429711_0
	matplotlib-base           2.2.4            py37hfd891ef_0    conda-forge
	mccabe                    0.6.1                    py37_1
	mistune                   0.8.4            py37h7b6447c_0
	mkl                       2019.4                      243
	mkl-service               2.3.0            py37he904b0f_0
	mkl_fft                   1.0.15           py37ha843d7b_0
	mkl_random                1.1.0            py37hd6b4f25_0
	mock                      3.0.5                    py37_0
	more-itertools            8.0.2                      py_0
	mpc                       1.1.0                h10f8cd9_1
	mpfr                      4.0.1                hdf1c602_3
	mpmath                    1.1.0                    py37_0
	msgpack-python            0.6.1            py37hfd86e86_1
	multipledispatch          0.6.0                    py37_0
	navigator-updater         0.2.1                    py37_0
	nbconvert                 5.6.1                    py37_0
	nbformat                  4.4.0                    py37_0
	ncurses                   6.1                  he6710b0_1
	networkx                  2.4                        py_0
	nltk                      3.4.5                    py37_0
	nodejs                    10.13.0              he6710b0_0
	nose                      1.3.7                    py37_2
	notebook                  6.0.2                    py37_0
	numba                     0.46.0           py37h962f231_0
	numexpr                   2.7.0            py37h9e4a6bb_0
	numpy                     1.17.4           py37hc1035e2_0
	numpy-base                1.17.4           py37hde5b4d6_0
	numpydoc                  0.9.2                      py_0
	olefile                   0.46                     py37_0
	openpyxl                  3.0.2                      py_0
	openssl                   1.1.1d               h516909a_0    conda-forge
	packaging                 20.0                       py_0
	pandas                    0.25.3           py37he6710b0_0
	pandoc                    2.2.3.2                       0
	pandocfilters             1.4.2                    py37_1
	pango                     1.42.4               h049681c_0
	parso                     0.5.2                      py_0
	partd                     1.1.0                      py_0
	patchelf                  0.10                 he6710b0_0
	path                      13.1.0                   py37_0
	path.py                   12.4.0                        0
	pathlib2                  2.3.5                    py37_0
	patsy                     0.5.1                    py37_0
	pcre                      8.43                 he6710b0_0
	pep8                      1.7.1                    py37_0
	pexpect                   4.7.0                    py37_0
	pickleshare               0.7.5                    py37_0
	pillow                    7.0.0            py37hb39fc2d_0
	pip                       19.3.1                   py37_0
	pixman                    0.38.0               h7b6447c_0
	pkginfo                   1.5.0.1                  py37_0
	pluggy                    0.13.1                   py37_0
	ply                       3.11                     py37_0
	post-processing           0.0.post0.dev1+ge888678           dev_0    <develop>
	pretty-errors             1.2.10                   pypi_0    pypi
	prometheus_client         0.7.1                      py_0
	prompt_toolkit            2.0.9                    py37_0
	psutil                    5.6.7            py37h7b6447c_0
	ptyprocess                0.6.0                    py37_0
	py                        1.8.1                      py_0
	py-lief                   0.9.0            py37h7725739_2
	pycodestyle               2.5.0                    py37_0
	pycosat                   0.6.3            py37h7b6447c_0
	pycparser                 2.19                     py37_0
	pycrypto                  2.6.1            py37h14c3975_9
	pycurl                    7.43.0.3         py37h1ba5d50_0
	pydocstyle                4.0.1                      py_0
	pyflakes                  2.1.1                    py37_0
	pygments                  2.5.2                      py_0
	pylint                    2.4.4                    py37_0
	pyodbc                    4.0.27           py37he6710b0_0
	pyopenssl                 19.1.0                   py37_0
	pyparsing                 2.4.6                      py_0
	pyqt                      5.9.2            py37h05f1152_2
	pyrsistent                0.15.6           py37h7b6447c_0
	pyscaffold                3.2.2                      py_0    conda-forge
	pysocks                   1.7.1                    py37_0
	pytables                  3.6.1            py37h71ec239_0
	pytest                    5.3.2                    py37_0
	pytest-arraydiff          0.3              py37h39e3cac_0
	pytest-astropy            0.7.0                      py_0
	pytest-astropy-header     0.1.1                      py_0
	pytest-doctestplus        0.5.0                      py_0
	pytest-openfiles          0.4.0                      py_0
	pytest-remotedata         0.3.2                    py37_0
	python                    3.7.6                h0371630_2
	python-dateutil           2.8.1                      py_0
	python-jsonrpc-server     0.3.2                      py_0
	python-language-server    0.31.2                   py37_0
	python-libarchive-c       2.8                     py37_13
	pytz                      2019.3                     py_0
	pywavelets                1.1.1            py37h7b6447c_0
	pyyaml                    5.2              py37h7b6447c_0
	pyzmq                     18.1.0           py37he6710b0_0
	qt                        5.9.7                h5867ecd_1
	qtawesome                 0.6.0                      py_0
	qtconsole                 4.6.0                      py_1
	qtpy                      1.9.0                      py_0
	readline                  7.0                  h7b6447c_5
	requests                  2.22.0                   py37_1
	ripgrep                   11.0.2               he32d670_0
	rope                      0.14.0                     py_0
	ruamel_yaml               0.15.87          py37h7b6447c_0
	scikit-image              0.15.0           py37he6710b0_0
	scikit-learn              0.22.1           py37hd81dba3_0
	scipy                     1.3.2            py37h7c811a0_0
	seaborn                   0.9.0              pyh91ea838_1
	secretstorage             3.1.1                    py37_0
	send2trash                1.5.0                    py37_0
	setuptools                44.0.0                   py37_0
	simplegeneric             0.8.1                    py37_2
	singledispatch            3.4.0.3                  py37_0
	sip                       4.19.8           py37hf484d3e_0
	six                       1.13.0                   py37_0
	snappy                    1.1.7                hbae5bb6_3
	snowballstemmer           2.0.0                      py_0
	sortedcollections         1.1.2                    py37_0
	sortedcontainers          2.1.0                    py37_0
	soupsieve                 1.9.5                    py37_0
	sphinx                    2.3.1                      py_0
	sphinxcontrib             1.0                      py37_1
	sphinxcontrib-applehelp   1.0.1                      py_0
	sphinxcontrib-devhelp     1.0.1                      py_0
	sphinxcontrib-htmlhelp    1.0.2                      py_0
	sphinxcontrib-jsmath      1.0.1                      py_0
	sphinxcontrib-qthelp      1.0.2                      py_0
	sphinxcontrib-serializinghtml 1.1.3                      py_0
	sphinxcontrib-websupport  1.1.2                      py_0
	spyder                    3.3.6                    py37_0
	spyder-kernels            0.5.2                    py37_0
	sqlalchemy                1.3.12           py37h7b6447c_0
	sqlite                    3.30.1               h7b6447c_0
	statsmodels               0.10.1           py37hdd07704_0
	sympy                     1.5                      py37_0
	tbb                       2019.8               hfd86e86_0
	tblib                     1.6.0                      py_0
	terminado                 0.8.3                    py37_0
	testpath                  0.4.4                      py_0
	tk                        8.6.10               hed695b0_0    conda-forge
	toolz                     0.10.0                     py_0
	tornado                   6.0.3            py37h7b6447c_0
	tqdm                      4.40.2                     py_0
	traitlets                 4.3.3                    py37_0
	ujson                     1.35             py37h14c3975_0
	unicodecsv                0.14.1                   py37_0
	unixodbc                  2.3.7                h14c3975_0
	urllib3                   1.25.7                   py37_0
	wcwidth                   0.1.7                    py37_0
	webencodings              0.5.1                    py37_1
	werkzeug                  0.16.0                     py_0
	wheel                     0.33.6                   py37_0
	widgetsnbextension        3.5.1                    py37_0
	wrapt                     1.11.2           py37h7b6447c_0
	wurlitzer                 2.0.0                    py37_0
	xlrd                      1.2.0                    py37_0
	xlsxwriter                1.2.7                      py_0
	xlwt                      1.3.0                    py37_0
	xz                        5.2.4                h14c3975_4
	yaml                      0.1.7                had09818_2
	yapf                      0.28.0                     py_0
	zeromq                    4.3.1                he6710b0_3
	zict                      1.0.0                      py_0
	zipp                      0.6.0                      py_0
	zlib                      1.2.11               h7b6447c_3
	zstd                      1.3.7                h0b5b093_0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 15:41:43.516 LabApp] [jupyter_nbextensions_configurator] Loading 0.4.1
[D 15:41:43.516 LabApp] [jupyter_nbextensions_configurator]   Editing templates path to add /ccs/home/hzfmer/file_back/programs/rhea/anaconda3/lib/python3.7/site-packages/jupyter_nbextensions_configurator/templates
[D 15:41:43.516 LabApp] [jupyter_nbextensions_configurator]   Editing nbextensions path to add /ccs/home/hzfmer/file_back/programs/rhea/anaconda3/lib/python3.7/site-packages/jupyter_nbextensions_configurator/static
[D 15:41:43.516 LabApp] [jupyter_nbextensions_configurator]   Adding new handlers
[I 15:41:43.517 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 15:41:44.967 LabApp] JupyterLab extension loaded from /ccs/home/hzfmer/file_back/programs/rhea/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 15:41:44.967 LabApp] JupyterLab application directory is /ccs/home/hzfmer/file_back/programs/rhea/anaconda3/share/jupyter/lab
[D 15:41:45.947 LabApp] Yarn configuration loaded.
[I 15:41:46.156 LabApp] Loading server extension jupyterlab_sql
[I 15:41:46.157 LabApp] Serving notebooks from local directory: /gpfs/alpine/geo112/scratch/hzfmer/high_f/la_habra_small_8m_gpu_dm_abc50
[I 15:41:46.157 LabApp] The Jupyter Notebook is running at:
[I 15:41:46.157 LabApp] http://localhost:8888/?token=e64a195da429a14a4d5eaa4b3d003c6a7be3e2e2ee92fa87
[I 15:41:46.157 LabApp]  or http://127.0.0.1:8888/?token=e64a195da429a14a4d5eaa4b3d003c6a7be3e2e2ee92fa87
[I 15:41:46.157 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:41:46.167 LabApp]

    To access the notebook, open this file in a browser:
        file:///autofs/nccs-svm1_home1/hzfmer/.local/share/jupyter/runtime/nbserver-27777-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=e64a195da429a14a4d5eaa4b3d003c6a7be3e2e2ee92fa87
     or http://127.0.0.1:8888/?token=e64a195da429a14a4d5eaa4b3d003c6a7be3e2e2ee92fa87
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Download the React DevTools for a better development experience: https://fb.me/react-devtools
index.js:42 Starting application in workspace: "/lab"
2default.js:56 Starting WebSocket: ws://127.0.0.1:8031/api/kernels/c9745cbb-15af-44de-8449-63417b7db126
2default.js:1496 Kernel: connected (c9745cbb-15af-44de-8449-63417b7db126)
</pre>
</details>

**Comment by FungluiKoo** [comment]
Would that due to network connection/bandwidth? It seems that saving big files with a local Jupyter isn't a disaster

**Comment by hzfmer** [comment]
> Would that due to network connection/bandwidth? It seems that saving big files with a local Jupyter isn't a disaster

I am not sure, but I just recreated the same notebook without any figures. It worked then to save the notebook.
Now I just keep cautious not to plot too many figures, actually delete some occasionally as well, to that the size doesn't grow too fast.

**Comment by jvschoen** [comment]
Is there any other discussions about this? I use plotly for figures, and working with 4M row datasets. I'm wondering if the interactivity storing extra data in the plots is causing issues. But it's been really frustrating when the started saving pops up and doesn't finish, I've lost hours of work previously because of this.

I work with AI notebooks on GCP, which is just a VM serving jupyterlab.

**Comment by emanuelef** [comment]
I'm noticing the similar issue. Especially when using Plotly the notebook get qui large but not massive (4Mb) and it fails saving with "The network connection was lost".
If I duplicate the notebook and remove Plotly graph then it can be saved.
