### ISSUE TITLE
An icon for Tensorboard

### ISSUE THREAD

**Issue by crystal5fish** [jupyterlab/jupyterlab#7866]
![image](https://user-images.githubusercontent.com/28918823/74125408-2f998780-4c10-11ea-89d2-eaf0d4a8d761.png)

We are developing based on jupyterlab, after installed tensorboard, the name in sidebar is a little bit long and weird, would you please set an icon for Tensorboard. Thank you!!

**Comment by telamonian** [comment]
This is not an issue we can fix in jlab core, but is instead something that the [jupyterlab_tensorboard](https://github.com/chaoleili/jupyterlab_tensorboard) devs can address. You should open this issue over on [their board](https://github.com/chaoleili/jupyterlab_tensorboard/issues).
