### ISSUE TITLE
Notebook of Jupyterlab in Google AI Platform doesn't work from iPad

### ISSUE THREAD

**Issue by qbitmultiverse** [jupyterlab/jupyterlab#7868]
relevant package versions, including:
jupyterlab and notebook versions: Google AI Platform/Notebooks
browser versions affected: chrom ver 80.0.3987.88
operating system and version: iPadOS 13.3.1
relevant server and JavaScript error messages: Notebooks of AI Platform does't open so no error message is shown.
screenshots or short screencasts illustrating the issue: There is no meaningful screenshots as my problem is just that I can't open a notebook in Google AI Platform.

As mentioned above,  I can't open my notebook of AI Platform from iPad (iPadOS 13.3.1), while it is fine with macOS High Sierra(ver 10.13.4). It seems that it does't matter which browser I use to open the notebook. Could you suggest what I should do to use Notebooks function of AI Platform from iPad? thanks.

**Comment by timkpaine** [comment]
Jupyterlab will render fine on ipad, there are some related issues though:
https://github.com/jupyterlab/jupyterlab/issues/3275

**Comment by timkpaine** [comment]
Closing as this sounds like a Google-related issue, considering bringing it up directly with them.

**Comment by qbitmultiverse** [comment]
Thanks Tim, but google support told me that I should contact JupyterLab as you can see below...

-----------------------------------------------------------------------------------
Thank you for contacting Google Cloud Platform Support.

I understand that you’re trying to open the Jupyterlab Notebook on your Ipad but it’s not opening while it is opening just fine while using a MacOS.

Please note that the JupyterLab[1] notebooks is a third-party application/IDE which is already out of our scope of support and expertise, however, based on the documentation of Jupyterlab, it did not mention that it can only run on specific operating systems but rather it does have a list of supported browsers (latest versions) such as Firefox, Chrome and Safari[2]. If the your iPad does not have the latest version of the browser mentioned above, please install or update your browser then try to access the Jupyterlab Notebooks. If the issue persists even after using the latest version of the browsers, I highly recommend that you submit an issue with Jupyterlab using this link[3].

I hope this points you in the right direction. I will now mark this case as closed. Please feel free to contact us again should you have other GCP related concerns or inquiries.

[1] https://jupyter.org/
[2] https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#supported-browsers
[3] https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html
-----------------------------------------------------------------------------------------------------

**Comment by timkpaine** [comment]
If you can setup a stand-alone instance of jupyterlab (e.g. on your Mac) with no extensions or anything and connect to it from your iPad to debug, we can probably investigate further. But given that google's platform is proprietary and may have extra extensions or customizations, we cannot help any further.

**Comment by jasongrout** [comment]
@qbitmultiverse, discussion about how JupyterLab works on an ipad is at #3275. Let's continue the discussion over there to keep the conversation in one place. We know there are issues with the interface of JupyterLab on an ipad, and apparently it got better with ipados 13. Can you read that discussion carefully, and add any extra information there beyond what is reported there that you think would be helpful to understand how JupyterLab works on an ipad?

**Comment by jasongrout** [comment]
And as @timkpaine said, to make sure that your information is relevant to JupyterLab itself, and not influenced by being in the Google platform, you can connect to JupyterLab on, say, Binder to check it out: https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo

**Comment by jeff-sternberg** [comment]
@qbitmultiverse I'm interested in helping out with this issue. Can you connect with me on [LinkedIn](https://www.linkedin.com/in/jeffsternberg/)? Thanks @timkpaine for the ping. ;-)

**Comment by qbitmultiverse** [comment]
Thanks all for your comments and kindly help on this. I made sure that the JupyterLab-demo  suggested by @jasongrout worked perfectly in my ipad and communicated that to Google Cloud Support team. They said that they're working with AI Platform Notebooks engineering team to look into this issue.

**Comment by qbitmultiverse** [comment]
I'm now able to open a JupyterLab in Google AI Platform from iPad after clearing cache of Chrome thanks to suggestions and help from Google cloud support team!

**Comment by jasongrout** [comment]
That's great! Thanks for following up here on that.
