### ISSUE TITLE
Replace toggle icon missing

### ISSUE THREAD

**Issue by AlbertHilb** [jupyterlab/jupyterlab#7869]
## Description

The replace toggle button in the document search overlay has no icon. 

## Reproduce

1. Open the document search panel
2. No button to show the replace entry is visible

![Screenshot_dev_chromium](https://user-images.githubusercontent.com/1220427/74180041-03e1c600-4c3f-11ea-9095-5808af5c01a4.png)

## Expected behavior

A button to open the replace entry should be visible.

## Diagnosis

The problem seems to happen because the toggle button icon has not been converted to LabIcon. See [here][1].

Regards

[1]: https://github.com/jupyterlab/jupyterlab/blob/f17361c2d6ecf1b5ccae5b576266355150f09af2/packages/documentsearch/src/searchoverlay.tsx#L465

**Comment by blink1073** [comment]
cc @telamonian

**Comment by jasongrout** [comment]
Fixed for me in 2.0.0rc2: 
<img width="427" alt="Screen Shot 2020-02-25 at 9 17 14 AM" src="https://user-images.githubusercontent.com/192614/75270603-ace7ff00-57af-11ea-8526-cf40a9329334.png">

**Comment by vidartf** [comment]
@jasongrout Are those two arrow icons supposed to stack like that?
