### ISSUE TITLE
Cut cell not working expectedly with find widget active

### ISSUE THREAD

**Issue by dremovd** [jupyterlab/jupyterlab#7870]
## Description

When "Find..." widget is active if you use "Cut cells", then focus moves to an arbitrary place of the notebook.

## Reproduce

1. Open any large notebook
2. Command+F and find some text present in the notebook
3. Use "Cut cells"
4. Notebook instantly would be listed to another place. In other words, focus randomly changed.

## Expected behavior

4. Similar to behavior when "Find..." widget is closed -- focus not moving. 

## Context

Chrome Version 79.0.3945.130 (Official Build) (64-bit)
MacOS 10.12.6 (16G1510)
JupyerLab 1.1.3

**Comment by jasongrout** [comment]
This is likely the same underlying issue as #7845

**Comment by dremovd** [comment]
Yes, I didn't find this issue but looks like it's two cases of the same bug
