### ISSUE TITLE
UX: Select Kernel Dropdown

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#7871]
## Description

When you click on a kernel to change it, the select kernel dropdown should default select the kernel you are currently using.

## Reproduce

Start a notebook with any kernel but the first one in the select kernel list. Click on the kernel and you'll see the dropdown defaults to the first preferred kernel (which is sorted alpha-numerically).

![kernelSelect](https://user-images.githubusercontent.com/1813603/74275458-e6196d00-4ce1-11ea-849d-3edc2d32e9cc.gif)

## Expected behavior

The kernel which I am currently running should be default selected (in the above gif it should have defaulted to python2).

## Context

- Operating System and version: Windows
- Browser and version: Chrome
- JupyterLab version: 1.2.6

**Comment by isabela-pf** [comment]
This is a really good catch and makes more sense to me than the current experience. I second this proposal.

**Comment by Jessie-Newman** [comment]
Tested this at master and I believe it is fixed.

**Comment by isabela-pf** [comment]
Thanks for checking! 🌻
