### ISSUE TITLE
Too many fetch calls (20+) to "/api/settings/@jupyterlab/docmanager-extension" on the first load.

### ISSUE THREAD

**Issue by ikiw** [jupyterlab/jupyterlab#7874]
## Description

Find too many fetch calls (20+) to /api/settings/@jupyterlab/docmanager-extension on the first load.
version - tried out in 1.2.6 & 1.2.3

## Reproduce

1. Open the Dev Tools
2. Load JupyterLab
3. Find the number of calls to docmanager-extension

## Expected behavior

Avoid the redundant calls. Ideally should be only 1 fetch call.

## Context

- Operating System and version: Mac Cataline
- Browser and version: Chrome V80
- JupyterLab version: 1.2.6
<img width="1367" alt="Screenshot 2020-02-12 at 12 25 16 PM" src="https://user-images.githubusercontent.com/4917563/74320483-b54f3b80-4da6-11ea-8c36-a6190459a6ea.png">

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Attached Screenshot
</pre>
</details>

**Comment by jasongrout** [comment]
This happens to me too on JLab 2.0rc0.

**Comment by jasongrout** [comment]
I think it comes from these lines which reload the settings: https://github.com/jupyterlab/jupyterlab/blob/7a97756d3808240a5881f9d63d2f955a27acb9eb/packages/docmanager-extension/src/index.ts#L244-L246

**Comment by ikiw** [comment]
@jasongrout : Debugged it and found addWidgetFactory which emits this change event is invoked from a forEach loop.

[https://github.com/jupyterlab/jupyterlab/blob/master/packages/application/src/mimerenderers.ts#L153](url)

I was able to resolve it locally, by maintaining a check if there is already a promise yet to be resolved. Please let know if this approach is good. I can create a PR.
```

//callback to registry change that ensures not to invoke reload method when there is already a promise that is pending
    let reloadSettingsRegistry = () => {
      let promisePending = false;

      return async () => {
          if(!promisePending) {
            promisePending = true;
            await settingRegistry.reload(pluginId);
            promisePending = false;
          }
      };
    };

    // If the document registry gains or loses a factory or file type,
    // regenerate the settings description with the available options.
    registry.changed.connect(reloadSettingsRegistry());

```
