### ISSUE TITLE
Bug: replacing cell contents after executing

### ISSUE THREAD

**Issue by lesliewalcott** [jupyterlab/jupyterlab#7875]
## Description

When I execute a cell by hitting "shift enter", the cell executes, but the cell contents is replaced with the previous cell that I ran. 

Example:
In: print("hi")
Out: hi

In: 2+2
Out: 4

Upon executing, the "2+2" in my cell is replaced with "print("hi")". I took a few videos illustrating this with my actual code: https://imgur.com/a/TzifF5k

It always replaces the cell input with the last cell that was executed. If I were to run an additional cell:
In: print("Hello")
Out: Hello

It would print Hello, but also replace the cell input with "2+2". 

## Reproduce

This has happened to me at random. It happened about a month ago and I fixed it by rebooting my machine. Today it happened again and I fixed it by restarting the kernel and clearing all outputs (rebooting did NOT fix it). I have searched online to see if this happened to anyone else, but didn't find anything, so I wanted to report it here. 

## Expected behavior

I expect the cell to be executed, and the code that I typed in to not change.

## Context

- Operating System and version: Amazon Linux AMI 2018.03
- Browser and version: Chrome 79.0.3945.130
- JupyterLab version: 4.4.0

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /home/ec2-user/anaconda3/envs/DS-CUSTOMER-DISCOVERY/bin
        /home/ec2-user/anaconda3/envs/DS-CUSTOMER-DISCOVERY/bin
        /home/ec2-user/anaconda3/bin
        /usr/local/bin
        /bin
        /usr/bin
        /usr/local/sbin
        /usr/sbin
        /sbin
        /opt/aws/bin
        /home/ec2-user/.local/bin
        /home/ec2-user/bin
        /home/ec2-user/anaconda3/bin
        /opt/aws/bin
        /home/ec2-user/.local/bin
        /home/ec2-user/bin

sys.path:
        /home/ec2-user/anaconda3/envs/DS-CUSTOMER-DISCOVERY/bin
        /home/ec2-user/anaconda3/envs/DS-CUSTOMER-DISCOVERY/lib/python37.zip
        /home/ec2-user/anaconda3/envs/DS-CUSTOMER-DISCOVERY/lib/python3.7
        /home/ec2-user/anaconda3/envs/DS-CUSTOMER-DISCOVERY/lib/python3.7/lib-dynload
        /home/ec2-user/anaconda3/envs/DS-CUSTOMER-DISCOVERY/lib/python3.7/site-packages

sys.executable:
        /home/ec2-user/anaconda3/envs/DS-CUSTOMER-DISCOVERY/bin/python3.7

sys.version:
        3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
        [GCC 7.3.0]

platform.platform():
        Linux-4.14.158-101.185.amzn1.x86_64-x86_64-with-glibc2.10

which -a jupyter:
        /home/ec2-user/anaconda3/envs/DS-CUSTOMER-DISCOVERY/bin/jupyter
        /home/ec2-user/anaconda3/envs/DS-CUSTOMER-DISCOVERY/bin/jupyter
        /home/ec2-user/anaconda3/bin/jupyter
        /home/ec2-user/anaconda3/bin/jupyter
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
Thanks for reporting this. That is *very* weird, and I don't remember ever hearing of something like this happening. The first thing I think of is that perhaps a browser extension or a jupyterlab extension is messing something up.

I realize since you can't reproduce it reliably, it's hard to try to narrow things down by going through the diagnosis guidelines at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html. But at a very minimum, next time you see this, can you try disabling any browser extensions and jupyterlab extensions you may have installed?

**Comment by jasongrout** [comment]
Setting as "needs info" for a better way to reproduce this, and pending reproduction with no browser and jlab extensions installed. Also, were there any js console errors?

**Comment by lesliewalcott** [comment]
Hi Jason, if this happens again, I will comment here with more information. I don't have many Chrome extensions installed, but I have quite a few Jupyter extensions, so I will try disabling.  No js console errors.

**Comment by jasongrout** [comment]
Note that you can start JupyterLab with only the stock builtin plugins (i.e., no custom plugins you've installed) with `jupyter lab --core`. It's sort of like the "safe mode" in operating systems.

**Comment by jasongrout** [comment]
Can you go through the diagnosis guides linked above to try to narrow down what might be causing the issue, or to come up with instructions to reproduce this?
