### ISSUE TITLE
interface to manage workspaces

### ISSUE THREAD

**Issue by allefeld** [jupyterlab/jupyterlab#7876]
Under the URL `/lab/workspaces` without an appended workspace name, an interface to manage workspaces should be shown. that is:

- a list of existing workspaces, click opens it
- for each existing workspace, options to delete, rename, clone
- option to create a new workspace, either empty or as a clone of the default workspace.

**Comment by jasongrout** [comment]
Thanks for a starting point for what a workspace manager might look like. I think @afshin has been thinking about what a workspace management system might look like as well.

**Comment by jtpio** [comment]
Similar to https://github.com/jupyterlab/jupyterlab/issues/6944?

**Comment by allefeld** [comment]
@jtpio agreed, closing in favor of that issue.
