### ISSUE TITLE
Issue running ipynb file in Pycharm Professional edition

### ISSUE THREAD

**Issue by bhaskarnn9** [jupyterlab/jupyterlab#7880]
Steps to reproduce
1. Create a ipynb file in PyCharm PE
2. Run the file
3. Open console see the below error

This issue could be connected to the another issue I am facing with PyCharm: https://youtrack.jetbrains.com/issue/PY-40620

/Users/bhaskarn/.conda/envs/global/bin/jupyter notebook --no-browser
[W 00:50:25.334 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/Users/bhaskarn/.conda/envs/global/lib/python3.7/site-packages/notebook/notebookapp.py", line 1670, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/bhaskarn/.conda/envs/global/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyterlab'
[I 00:50:25.336 NotebookApp] Serving notebooks from local directory: /Users/bhaskarn/PycharmProjects/Kaggle_Titanic
[I 00:50:25.336 NotebookApp] The Jupyter Notebook is running at:
[I 00:50:25.336 NotebookApp] http://localhost:8888/?token=265d993a0681c3f8ff9788e9fd02dc33ec111bbdd0127fa4
[I 00:50:25.336 NotebookApp]  or http://127.0.0.1:8888/?token=265d993a0681c3f8ff9788e9fd02dc33ec111bbdd0127fa4
[I 00:50:25.336 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:50:25.344 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/bhaskarn/Library/Jupyter/runtime/nbserver-16396-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=265d993a0681c3f8ff9788e9fd02dc33ec111bbdd0127fa4
     or http://127.0.0.1:8888/?token=265d993a0681c3f8ff9788e9fd02dc33ec111bbdd0127fa4
[I 00:50:25.346 NotebookApp] 302 GET /api/kernelspecs/ (127.0.0.1) 0.70ms
[I 00:50:25.398 NotebookApp] Kernel started: ef52dc44-754a-4983-9cee-522209f2a749
[W 00:50:25.410 NotebookApp] No session ID specified

**Comment by vidartf** [comment]
This sees like an issue with PyCharm, and unrelated to JupyterLab. Or am I missing something?

**Comment by jasongrout** [comment]
Yes, I would recommend asking the PyCharm people about this. From the error messages, it seems that jupyterlab isn't installed or something? I'm not sure what jupyterlab has to do with running a file in pycharm.

**Comment by bhaskarnn9** [comment]
Yes. 
I have indeed reported to PyChram team. It is being worked on, as of now. Can be tracked here : https://youtrack.jetbrains.com/issue/JBR-2163?p=PY-40620
