### ISSUE TITLE
autosave overwrote manually saved notebook

### ISSUE THREAD

**Issue by ChrisIdema** [jupyterlab/jupyterlab#7888]
## Description

Last night I saved my notebook several times using the diskette icon.
This morning I found my notebook reverted to a very early version and it said it was auto-saved around the time I closed my computer. It overwrote all the work I did and saved manually last night. So it auto-saved an older version over the last manually saved version destroying all my work.

## Context

- Operating System and version: windows 10 home 10.0.18363 Build 18363
- Browser and version: Chrome Version 80.0.3987.106 (Official Build) (64-bit)
- JupyterLab version: 1.2.3
- Jupyter notebook version: 6.0.2

**Comment by vidartf** [comment]
Did the little * marking the file as changed since the last save disappear when you hit save? Is there anything in the server log? Is there anything in the browser developer console? There are multiple things that can have gone wrong, and it is hard to make any guesses without more details.

**Comment by ChrisIdema** [comment]
How do I see the server log?

**Comment by vidartf** [comment]
The server log would be anything output from starting the jupyter lab server (i.e. the output from running `jupyter lab` in a terminal).

**Comment by ChrisIdema** [comment]
I use Jupyter Notebooks in VS Code now (with much better user experience) and haven't been able to reproduce this old issue anyway, so I'm closing the issue.
