### ISSUE TITLE
Smart Deletion of indent.

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#790]
It took me a few minutes to actually fire this out as the behavior of JupyterLab is getting really close to the notebook, so this is nice !

When deleting whitespace the current notebook delete until previous location multiple of 4 spaces (when in Python mode) . This make `tab` and `delete` symmetric. JupyterLab seem to not behave this way, and I think the behavior of current notebook is more intuitive and efficient (in most case) than jupyterlab.

**Comment by ellisonbg** [comment]
This is super painful for anyone working regularly in jlab, targeting as beta.

**Comment by ellisonbg** [comment]
May actually be lower level than notebook in editor component.
