### ISSUE TITLE
Open in new browser tab is broken(File browser menu option)

### ISSUE THREAD

**Issue by ggbhat** [jupyterlab/jupyterlab#7900]
## Description
Open in new browser tab option in file browser context menu is not working as expected

## Reproduce

- Right click on file to open context menu
- click open in new browser tab option

## Expected behavior
Selected file should open in new browser tab

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version: 1 and 2

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
It seems to be working for me (the selected file does open in a new browser tab) with JLab 2.0 rc0. Can you describe exactly what it is doing that is not what you expected? Also, can you try going through the diagnostic guide https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to test in a clean environment with no extensions, etc.?

**Comment by ggbhat** [comment]
@jasongrout  I tested it in JLab 2.0 rc0, still having same issue.
![open-in-new-tab](https://user-images.githubusercontent.com/4777119/75226066-b8e4b880-57d1-11ea-9a17-381f9f265950.gif)

https://github.com/jupyterlab/jupyterlab/blob/d3c1ffbcc85db1a85a8c3d733cd66438b302d812/packages/docmanager-extension/src/index.ts#L461
```
return docManager.services.contents.getDownloadUrl(path).then(url => {
        const opened = window.open();
        if (opened) {
          opened.opener = null;
          opened.location.href = url;
        } else {
          throw new Error('Failed to open new browser tab.');
        }
      });
    },
```

In the above code it is referring to getDownloadUrl(). It is returning the download link.

**Comment by vidartf** [comment]
This issue has been bouncing back and forth between multiple behaviors I think. @ggbhat Are you able to test this on multiple browsers, and report the behavior for each of them?

**Comment by ggbhat** [comment]
I tested it on chrome and edge. Result is same. Clicking on menu option will ask for download, rather opening in new tab.

**Comment by vidartf** [comment]
Just to make sure we're talking about the same thing, you want to get a raw text view of the notebook JSON file, directly in the browser, right? There has been some finicky details previously to try to differentiate between this and downloading the file, and I'm not sure where in the code the work was done (cc @afshin who might have been involved?).

**Comment by ggbhat** [comment]
> Just to make sure we're talking about the same thing, you want to get a raw text view of the notebook JSON file, directly in the browser, right? There has been some finicky details previously to try to differentiate between this and downloading the file, and I'm not sure where in the code the work was done (cc @afshin who might have been involved?).

I am confused here, My expectation was  as menu label it should open file in new browser tab. But looking at the response in [related issue](https://github.com/jupyterlab/jupyterlab/issues/5380#issuecomment-424762514) it looks like it is downloading file in case of notebooks.
If the menu option is to download file then it is working fine. If it is to create new workspace(cloned one) to open in new browser tab then it is not working as expected.

**Comment by vidartf** [comment]
> If it is to create new workspace(cloned one) to open in new browser tab then it is not working as expected.

Ah, this is why @jasongrout asked "Can you describe exactly what it is doing that is not what you expected?" above :)

**Comment by vidartf** [comment]
Would you say this is a duplicate of #5380 then?

**Comment by jasongrout** [comment]
> Would you say this is a duplicate of #5380 then?

It looks like it to me. I've added another comment over there to try to further the discussion.

**Comment by ggbhat** [comment]
Yes its duplicate of #5380,hence closing it . 
Thanks..
