### ISSUE TITLE
Option --LabApp.override_static_url is not working on JupyterLab 1.2.6

### ISSUE THREAD

**Issue by santiagobasulto** [jupyterlab/jupyterlab#7915]
I've just upgraded to JupyterLab 1.2.6, I was working with 0.35 and this was working correctly. After updating, the `--LabApp.override_static_url` seems to have an incorrect behavior. The command I'm running is: `jupyter lab --LabApp.override_static_url='https://d397i2nmp1vg8j.cloudfront.net'`

The problem is that Jupyter Lab is prefixing the static URL with `http://localhost:8888/`, resulting in the static files being requested at `http://localhost:8888/https://d397i2nmp1vg8j.cloudfront.net/`.

For example, it's requesting (see screenshot below) `http://localhost:8888/https://d397i2nmp1vg8j.cloudfront.net/main.2b12886c9f634b6a165c.js`

![Screen Shot 2020-02-24 at 2 34 27 PM](https://user-images.githubusercontent.com/872296/75176500-077f4d80-5713-11ea-9237-9f406df70b05.png)

And I've made sure the file does exist:

```
$ curl -I https://d397i2nmp1vg8j.cloudfront.net/main.2b12886c9f634b6a165c.js
HTTP/2 200
content-type: binary/octet-stream
content-length: 69935
date: Mon, 24 Feb 2020 17:37:11 GMT
last-modified: Mon, 24 Feb 2020 14:24:09 GMT
etag: "5daed56b2b340a7849835ec71a7173a5"
cache-control: public, max-age=31536000
expires: Sun, 31 Dec 2028 00:00:00 GMT
accept-ranges: bytes
server: AmazonS3
x-cache: Miss from cloudfront
via: 1.1 c67eb79dbb5052fa8ea197696551cc5b.cloudfront.net (CloudFront)
x-amz-cf-pop: EZE51-C1
x-amz-cf-id: wIH4wDrplFuBgX-QKfclFEwOo1kPRPooRgwb28yJ8C6vItPQkKA8rQ==
```

Has any option changed? Or the default behavior of `override_static_url` is no longer the same?

**Comment by santiagobasulto** [comment]
I'm further researching this issue, and I've just found that somewhere, when building `page_config`, a forward slash is being prepended to the variable `fullStaticUrl`. This is what my `page_config` looks like:

```json
{
   ...
   "fullSettingsUrl":"/lab/api/settings",
   "fullStaticUrl":"/https://d397i2nmp1vg8j.cloudfront.net",
   "fullThemesUrl":"/lab/api/themes",
   ...
}
```

**Comment by santiagobasulto** [comment]
I've been dealing with this for a few days and still can't find the root cause. I feel like I'm close, but can't see where the initial bar in `fullStaticUrl` is added. @jasongrout can you give me a hint of where the static code could produce it? I can try fixing the bug.

**Comment by jasongrout** [comment]
I would first check here to see if it has the leading slash when we first get it (i.e., if the notebook class is adding the leading slash): https://github.com/jupyterlab/jupyterlab/blob/1.2.x/jupyterlab/extension.py#L63

**Comment by santiagobasulto** [comment]
Thanks for the hint. I remember going through that code while debugging and I think the leading slash was NOT there. I'll double check.

**Comment by jasongrout** [comment]
It looks like the problem is here: https://github.com/jupyterlab/jupyterlab_server/blob/865a6b783118d545623f5304c3d741478c673dc8/jupyterlab_server/handlers.py#L88-L94

That prefixing should probably be conditioned on testing the urls with the `is_url` function at the top of the file?

**Comment by jasongrout** [comment]
i.e., something like:

```python
url = getattr(config, name)
if is_url(url):
    full_url = url
else:
    full_url = ujoin(base_url, getattr(config, name))
```

**Comment by santiagobasulto** [comment]
Ah, it makes sense. I'm going to do a few quick tests once I get back home. I didn't see that in the code, thanks for the help. I was looking the error in the frontend portion.

**Comment by jasongrout** [comment]
Thanks for working on this! If that is the problem, the PR would be to https://github.com/jupyterlab/jupyterlab_server

**Comment by santiagobasulto** [comment]
THAT'S IT! Thanks so much @jasongrout. That was the problem and your solution fixes it.

What's the best way to submit the PR and retroactively fix it in JupyterLab 1.2.x? I see the requirement is `jupyterlab_server~=1.0.0`, but is there a release schedule or anything like that?

**Comment by jasongrout** [comment]
I think we just make a patch release of jupyterlab_server, which is used by both jlab 1 and jlab 2.

**Comment by santiagobasulto** [comment]
Alright, I'll submit a PR in a minute.

**Comment by santiagobasulto** [comment]
Fixed here: https://github.com/jupyterlab/jupyterlab_server/pull/81
