### ISSUE TITLE
Run test-services first in Linux/Windows JS CI tests

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#7918]
While working on #7864 over the weekend, the Linux/Windows JS CI tests each had at least half a dozen spurious failures. Every single time the failure occurred during the run of the test-services package. The test-whatever packages are run in alphabetical order, so test-services isn't run until near the end of the tests, at around the ~30-35 min mark.

I think it would make the CI slightly less painful to deal with if test-services ran first. The tests would still fail the same, of course, but at least that way we wouldn't have to wait 30 minutes just to see the test die. Is this a sensible proposal?

**Comment by jtpio** [comment]
Closing as `js-services` are now run separately, and are also grouped in a "Flaky" workflow so it's easier to restart them independently without restarting all the others: https://github.com/jupyterlab/jupyterlab/blob/master/.github/workflows/linuxjs-flaky-tests.yml

Thanks!
