### ISSUE TITLE
Can't load lab extensions at command nor in extension manager. suspect http proxy handling issue

### ISSUE THREAD

**Issue by kevinsneel** [jupyterlab/jupyterlab#7921]
I work behind a corporate firewall. I am trying to add extensions to Jupyter Lab, but it doesn't seem capable of reaching the network.

If I try to add from the command line, I get:
Yarn configuration loaded.
Node v10.13.0

> /net/slc10viq.us.oracle.com/scratch/kneel/packages/install/anaconda3/bin/npm pack @jupyter-widgets/jupyterlab-manager
npm ERR! code E403
npm ERR! 403 registrynpmjsblockpage: @jupyter-widgets/jupyterlab-manager@latest

If I try to search for extensions from within lab, in the extensions manager, I get:
Error searching for extensions: TypeError: NetworkError when attempting to fetch resource.

Machine: Linux 4.1.12-124.27.1.el7uek.x86_64 #2 SMP Mon May 13 08:56:17 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

Browser Firefox linux: 73.0.1 (64-bit) (I don't have any other working browser on my system)

jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.12.0
ipykernel        : 5.1.4
jupyter client   : 5.3.4
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.0.4
traitlets        : 4.3.3

**Comment by vidartf** [comment]
You might need to add configuration for npm/yarn (which lab uses to manage/fetch extensions) to reach the external package registries. Please consult you local network admins for any specifics :)
