### ISSUE TITLE
Console Example not working

### ISSUE THREAD

**Issue by rsinha25** [jupyterlab/jupyterlab#793]
I'm on Windows. Installed jupyter with anaconda. And installed jupyterlab using source from git.
I'm trying to run the console example but I get the following errors when I load it on the browser console: (I have already run npm install and npm run build as mentioned in the doc)

Failed to load resource: the server responded with a status of 501 (Not Implemented)
 http://localhost:8888/api/sessions?1472472888949 

API request failed: Not Implemented
onSessionError @ session.js:800
session.js:800

Uncaught (in promise) Object 
undefined:1

**Comment by blink1073** [comment]
Hi @rsinha25, what is the output of `jupyter notebook --version`?

**Comment by rsinha25** [comment]
4.2.1

**Comment by jasongrout** [comment]
Does jupyter lab itself work (`jupyter lab`, after you've installed the serverextension)? Does the console in jupyterlab work?

**Comment by rsinha25** [comment]
Yes, it works.

**Comment by blink1073** [comment]
This sounds like a cross-origin problem.

**Comment by blink1073** [comment]
@rsinha25, can you post the output from your terminal?  It is running the notebook server with the `--debug` flag.

**Comment by rsinha25** [comment]
Hi, here's the output on the terminal when  I run the notebook with --debug.

[D 21:08:03.421 LabApp] Searching ['C:\\Users\\...\\Documents\\...\\jupyterlab\\examples\\console','C:\\Users\\...\\.jupyter','C:\\Anaconda3\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 21:08:03.421 LabApp] Looking for jupyter_config in C:\ProgramData\jupyter
[D 21:08:03.421 LabApp] Looking for jupyter_config in C:\Anaconda3\etc\jupyter
[D 21:08:03.421 LabApp] Looking for jupyter_config in C:\Users\...\.jupyter
[D 21:08:03.421 LabApp] Looking for jupyter_config in C:\Users\...\Documents\...\jupyterlab\examples\console
[D 21:08:03.421 LabApp] Looking for jupyter_notebook_config in C:\ProgramData\jupyter
[D 21:08:03.421 LabApp] Looking for jupyter_notebook_config in C:\Anaconda3\etc\jupyter
[W 21:08:03.421 LabApp] Unrecognized JSON config file version, assuming version1
[D 21:08:03.437 LabApp] Loaded config file: C:\Anaconda3\etc\jupyter\jupyter_notebook_config.json
[D 21:08:03.437 LabApp] Looking for jupyter_notebook_config in C:\Users\...\.jupyter
[W 21:08:03.437 LabApp] Unrecognized JSON config file version, assuming version1
[D 21:08:03.437 LabApp] Loaded config file: C:\Users\...\.jupyter\jupyter_notebook_config.json
[D 21:08:03.437 LabApp] Looking for jupyter_notebook_config in C:\Users\...\Documents\...\jupyterlab\examples\console
[D 21:08:03.749 LabApp] Native kernel (python3) available from C:\Anaconda3\lib\site packages\ipykernel\resources
[I 21:08:04.731 LabApp] [nb_conda_kernels] enabled, 1 kernels found
[D 21:08:04.731 LabApp]
    - Python [Root]: C:\Anaconda3\python.exe
[I 21:08:04.872 LabApp] The port 8888 is already in use, trying another port.
[I 21:08:04.872 LabApp] The port 8889 is already in use, trying another port.
[D 21:08:04.903 LabApp] Terminals not available (error was No module named 'term
inado')
[W 21:08:04.903 LabApp] Error loading server extension ..._server
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1046,
in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked

    ImportError: No module named '..._server'
[I 21:08:04.903 LabApp] It looks like you're running JupyterLab from source.
    If you're working on the TypeScript sources of JupyterLab, try running npm run watch from the JupyterLab repo directory in another terminal window to have the system incrementally watch and build JupyterLab's TypeScript for you, as you make changes.

[I 21:08:04.903 LabApp] JupyterLab alpha preview extension loaded from c:\users\...\documents\...\jupyterlab\jupyterlab
[I 21:08:05.402 LabApp] Serving notebooks from local directory: C:\Users\...\Documents\...\jupyterlab\examples\console
[I 21:08:05.402 LabApp] 0 active kernels
[I 21:08:05.402 LabApp] The Jupyter Notebook is running at: http://localhost:8890/
[I 21:08:05.402 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 21:08:06.572 LabApp] Using contents: services/contents
[D 21:08:06.603 LabApp] 200 GET /lab (127.0.0.1) 31.20ms
[D 21:08:06.759 LabApp] 200 GET /static/components/MathJax/MathJax.js?config=TeX-AMS_HTML-full,Safe&delayStartupUntil=configured (127.0.0.1) 15.60ms
[D 21:08:06.759 LabApp] 200 GET /lab/vendor.css (127.0.0.1) 0.00ms
[D 21:08:07.040 LabApp] 200 GET /lab/vendor.bundle.js (127.0.0.1) 265.20ms
[D 21:08:07.071 LabApp] 200 GET /lab/jupyterlab.bundle.js (127.0.0.1) 31.20ms
[D 21:08:07.087 LabApp] 200 GET /static/components/MathJax/config/TeX-AMS_HTML-full.js?rev=2.6.0 (127.0.0.1) 15.60ms
[D 21:08:07.103 LabApp] 200 GET /lab/jupyterlab.css (127.0.0.1) 62.40ms
[D 21:08:07.165 LabApp] 200 GET /static/components/MathJax/config/Safe.js?rev=2.6.0 (127.0.0.1) 0.00ms
[D 21:08:07.479 LabApp] Using contents: services/contents
[W 21:08:07.546 LabApp] 404 GET /favicon.ico (127.0.0.1) 66.80ms referer=None
[D 21:08:07.577 LabApp] Native kernel (python3) available from C:\Anaconda3\lib\site-packages\ipykernel\resources
[D 21:08:08.513 LabApp] 200 GET /api/kernelspecs?1472485087467 (127.0.0.1) 936.00ms
[D 21:08:08.919 LabApp] 200 GET /api/contents/?content=1&1472485088819 (127.0.0.1) 46.80ms
[D 21:08:08.919 LabApp] Using contents: services/contents
[W 21:08:08.934 LabApp] 404 GET /api/terminals?1472485088876 (127.0.0.1) 15.60ms
 referer=http://localhost:8890/lab
[D 21:08:08.997 LabApp] 200 GET /lab/25a32416abee198dd821b0b17a198a8f.eot? (127.0.0.1) 62.40ms
[D 21:08:08.997 LabApp] 200 GET /lab/2b609d364e2e1d67ba33a81c58d9eb8a.svg (127.0.0.1) 0.00ms
[D 21:08:09.012 LabApp] 200 GET /lab/67210cba51efc06308353fa274b6d389.svg (127.0.0.1) 15.60ms
[D 21:08:09.012 LabApp] 200 GET /lab/760111b6477e3b245d6c9483f626341d.svg (127.0.0.1) 0.00ms
[D 21:08:09.028 LabApp] 200 GET /lab/a5f896d73c05dd2cec16fd54f7b6d38b.svg (127.0.0.1) 0.00ms
[D 21:08:09.199 LabApp] 200 GET /api/sessions?1472485089139 (127.0.0.1) 15.60ms
[I 21:08:18.444 LabApp] Creating new notebook in /
[D 21:08:18.444 LabApp] Saving C:\Users\...\Documents\...\jupyterlab\examples\console\Untitled1.ipynb
[D 21:08:18.506 LabApp] 201 POST /api/contents/?1472485098349 (127.0.0.1) 62.40ms
[I 21:08:18.631 LabApp] Saving file at /Untitled1.ipynb
[D 21:08:18.631 LabApp] Saving C:\Users\...\Documents\...\jupyterlab\examples\console\Untitled1.ipynb
[D 21:08:18.678 LabApp] 200 PUT /api/contents/Untitled1.ipynb?1472485098529 (127.0.0.1) 156.00ms
[D 21:08:18.724 LabApp] 200 GET /api/contents/Untitled1.ipynb/checkpoints?1472485098694 (127.0.0.1) 0.00ms
[D 21:08:18.802 LabApp] 200 GET /api/contents/?content=1&1472485098754 (127.0.0.1) 15.60ms
[D 21:08:18.818 LabApp] 200 GET /api/contents/Untitled1.ipynb/checkpoints?147248
5098750 (127.0.0.1) 15.60ms
[D 21:08:18.958 LabApp] Starting kernel: ['C:\\Anaconda3\\python.exe', '-m', 'ipykernel', '-f', 'C:\\Users\\...\\AppData\\Roaming\\jupyter\\runtime\\kernel-655fe2b4-3dc7-4105-824d-da91c29cda35.json']
[D 21:08:18.974 LabApp] Connecting to: tcp://127.0.0.1:61831
[I 21:08:18.990 LabApp] Kernel started: 655fe2b4-3dc7-4105-824d-da91c29cda35
[D 21:08:18.990 LabApp] Kernel args: {'cwd': 'C:\\Users\\...\\Documents\\...\\jupyterlab\\examples\\console', 'kernel_name': 'Python [Root]'}
[D 21:08:19.005 LabApp] 201 POST /api/sessions?1472485098744 (127.0.0.1) 187.20ms
[D 21:08:19.005 LabApp] 200 GET /api/sessions?1472485098829 (127.0.0.1) 0.00ms
[D 21:08:19.052 LabApp] 200 GET /api/kernels/655fe2b4-3dc7-4105-824d-da91c29cda35?1472485099014 (127.0.0.1) 0.00ms
[D 21:08:19.130 LabApp] Initializing websocket connection /api/kernels/655fe2b4-3dc7-4105-824d-da91c29cda35/channels
[D 21:08:19.146 LabApp] Requesting kernel info from 655fe2b4-3dc7-4105-824d-da91c29cda35
[D 21:08:19.146 LabApp] Connecting to: tcp://127.0.0.1:61828
[D 21:08:19.177 LabApp] 200 GET /api/contents/?content=1&1472485099080 (127.0.0.1) 15.60ms
[D 21:08:19.177 LabApp] Using contents: services/contents
[W 21:08:19.192 LabApp] 404 GET /api/kernelspecs/Python%20%5BRoot%5D?1472485099067 (127.0.0.1) 15.60ms referer=http://localhost:8890/lab
[D 21:08:19.192 LabApp] Using contents: services/contents
[W 21:08:19.192 LabApp] 404 GET /api/kernelspecs/Python%20%5BRoot%5D?1472485099073 (127.0.0.1) 0.00ms referer=http://localhost:8890/lab
[D 21:08:19.239 LabApp] 200 GET /api/sessions?1472485099199 (127.0.0.1) 0.00ms

[D 21:08:20.849 LabApp] Received kernel info: {'banner': 'Python 3.5.1 |Anacond 4.1.0 (64-bit)| (default, Jun 15 2016, 15:29:36) [MSC v.1900 64 bit (AMD64)]\nType "copyright", "credits" or "license" for more information.\n\nIPython 4.2.0 -- An enhanced Interactive Python.\n?         -> Introduction and overview of IPython\'s features.\n%quickref -> Quick reference.\nhelp      -> Python\'s own help system.\nobject?   -> Details about \'object\', use \'object??\' for extra details.\n', 'protocol_version': '5.0', 'implementation_version': '4.2.0', 'help_links': [{'text': 'Python', 'url': 'http://docs.python.org/3.5'}, {'text': 'IPython', 'url': 'http://ipython.org/documentation.html'}, {'text': 'NumPy', 'url': 'http://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy', 'url': 'http://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib', 'url': 'http://matplotlib.org/contents.html'}, {'text': 'SymPy', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas', 'url': 'http://pandas.pydata.org/pandas-docs/stable/'}], 'implementation': 'ipython', 'language_info': {'file_extension': '.py', 'nbconvert_exporter': 'python', 'pygments_lexer': 'ipython3', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'version': '3.5.1', 'name': 'python', 'mimetype': 'text/x-python'}}


[D 21:08:20.849 LabApp] Opening websocket /api/kernels/655fe2b4-3dc7-4105-824d-da91c29cda35/channels
[D 21:08:20.849 LabApp] Connecting to: tcp://127.0.0.1:61828
[D 21:08:20.864 LabApp] Connecting to: tcp://127.0.0.1:61829
[D 21:08:20.864 LabApp] Connecting to: tcp://127.0.0.1:61830
[D 21:08:29.386 LabApp] 200 GET /api/contents/?content=1&1472485109307 (127.0.0.1) 31.20ms
[D 21:08:29.682 LabApp] 200 GET /api/sessions?1472485109618 (127.0.0.1) 0.00ms
[D 21:08:43.600 LabApp] 200 GET /api/contents/?content=1&1472485123520 (127.0.0.1) 31.20ms
[D 21:08:43.881 LabApp] 200 GET /api/sessions?1472485123832 (127.0.0.1) 0.00ms
[D 21:08:57.582 LabApp] 200 GET /api/contents/?content=1&1472485137533 (127.0.0.1) 15.60ms
[D 21:08:57.914 LabApp] 200 GET /api/sessions?1472485137850 (127.0.0.1) 0.00ms
[D 21:09:08.457 LabApp] 200 GET /api/contents/?content=1&1472485148377 (127.0.0.1) 15.60ms
[D 21:09:08.738 LabApp] 200 GET /api/sessions?1472485148689 (127.0.0.1) 0.00ms
[D 21:09:19.558 LabApp] 200 GET /api/contents/?content=1&1472485159469 (127.0.0.1) 27.50ms
[D 21:09:19.816 LabApp] 200 GET /api/sessions?1472485159782 (127.0.0.1) 0.00ms
[D 21:09:46.352 LabApp] 200 GET /api/contents/?content=1&1472485186287 (127.0.0.1) 15.60ms
[D 21:09:58.974 LabApp] 200 GET /api/sessions?1472485186598 (127.0.0.1) 0.00ms
[D 21:10:15.428 LabApp] 200 GET /api/contents/?content=1&1472485215347 (127.0.0.1) 15.60ms
[W 21:10:45.938 LabApp] Notebook Untitled1.ipynb is not trusted
[D 21:10:45.954 LabApp] 200 GET /api/contents/Untitled1.ipynb?1472485218547 (127.0.0.1) 15.60ms
[D 21:10:45.954 LabApp] 200 GET /api/sessions?1472485215658 (127.0.0.1) 0.00ms
[I 21:10:45.985 LabApp] Saving file at /Untitled1.ipynb
[D 21:10:45.985 LabApp] Saving C:\Users\...\Documents\...\jupyterlab\examples\console\Untitled1.ipynb
[D 21:10:46.047 LabApp] 200 PUT /api/contents/Untitled1.ipynb?1472485245978 (127.0.0.1) 62.40ms
[D 21:10:56.167 LabApp] 200 GET /api/contents/?content=1&1472485256084 (127.0.0.1) 31.20ms
[D 21:10:56.463 LabApp] 200 GET /api/sessions?1472485256396 (127.0.0.1) 0.00ms

**Comment by rsinha25** [comment]
Here's the output from the terminal when I run python main.py (console):

[D 21:26:20.588 NotebookApp] Searching ['C:\\Users\\...\\Documents\\...
\\jupyterlab\\examples\\console', 'C:\\Users\\...\\.jupyter', 'C:\\Anaconda3
\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 21:26:20.588 NotebookApp] Looking for jupyter_config in C:\ProgramData\jupyte
r
[D 21:26:20.604 NotebookApp] Looking for jupyter_config in C:\Anaconda3\etc\jupy
ter
[D 21:26:20.604 NotebookApp] Looking for jupyter_config in C:\Users\...\.jup
yter
[D 21:26:20.604 NotebookApp] Looking for jupyter_config in C:\Users\...\Docu
ments\...\jupyterlab\examples\console
[D 21:26:20.604 NotebookApp] Looking for jupyter_notebook_config in C:\ProgramDa
ta\jupyter
[D 21:26:20.604 NotebookApp] Looking for jupyter_notebook_config in C:\Anaconda3
\etc\jupyter
[W 21:26:20.604 NotebookApp] Unrecognized JSON config file version, assuming ver
sion 1
[D 21:26:20.604 NotebookApp] Loaded config file: C:\Anaconda3\etc\jupyter\jupyte
r_notebook_config.json
[D 21:26:20.604 NotebookApp] Looking for jupyter_notebook_config in C:\Users\rsi
nh31\.jupyter
[W 21:26:20.604 NotebookApp] Unrecognized JSON config file version, assuming ver
sion 1
[D 21:26:20.604 NotebookApp] Loaded config file: C:\Users\...\.jupyter\jupyt
er_notebook_config.json
[D 21:26:20.604 NotebookApp] Looking for jupyter_notebook_config in C:\Users\...
\Documents\...\jupyterlab\examples\console
[W 21:26:20.604 NotebookApp] Collisions detected in jupyter_notebook_config.py a
nd jupyter_notebook_config.json config files. jupyter_notebook_config.json has h
igher priority: {
"NotebookApp": {
"nbserver_extensions": "{'nb_conda': True, 'nb_anacondacloud': True, 'nbpresent'
: True} ignored, using {'jupyterlab': True, '..._server': True}"
}
}
[D 21:26:20.885 NotebookApp] Native kernel (python3) available from C:\Anaconda3
\lib\site-packages\ipykernel\resources
[I 21:26:21.774 NotebookApp] [nb_conda_kernels] enabled, 1 kernels found
[D 21:26:21.774 NotebookApp]
- Python [Root]: C:\Anaconda3\python.exe
[D 21:26:21.930 NotebookApp] Terminals not available (error was No module named
'terminado')
[W 21:26:21.946 NotebookApp] Error loading server extension ..._server
Traceback (most recent call last):
File "C:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1046, in ini
t_server_extensions
mod = importlib.import_module(modulename)
File "C:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 986, in _gcd_import
File "<frozen importlib._bootstrap>", line 969, in _find_and_load
File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named '..._server'
[I 21:26:21.946 NotebookApp] It looks like you're running JupyterLab from source
.
If you're working on the TypeScript sources of JupyterLab, try running
npm run watch
from the JupyterLab repo directory in another terminal window to have the system

incrementally watch and build JupyterLab's TypeScript for you, as you make
changes.
[I 21:26:21.946 NotebookApp] JupyterLab alpha preview extension loaded from c:\u
sers\...\documents\...\jupyterlab\jupyterlab
[I 21:26:22.382 NotebookApp] Serving notebooks from local directory: C:\Users\...
\Documents\...\jupyterlab\examples\console
[I 21:26:22.382 NotebookApp] 0 active kernels
[I 21:26:22.382 NotebookApp] The Jupyter Notebook is running at: http://localhos
t:8888/
[I 21:26:22.382 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
Browse to http://localhost:8765
[D 21:26:38.170 NotebookApp] 200 OPTIONS /api/sessions?1472486198146 (::1) 2.00m
s
[D 21:26:38.265 NotebookApp] No kernel specified, using default kernel
[D 21:26:38.437 NotebookApp] Native kernel (python3) available from C:\Anaconda3
\lib\site-packages\ipykernel\resources
[W 21:26:39.484 NotebookApp] Kernel not found: None
[E 21:26:39.484 NotebookApp] {
"Referer": "http://localhost:8765/",
"Content-Length": "46",
"Accept": "*/*",
"Origin": "http://localhost:8765",
"Accept-Encoding": "gzip, deflate",
"Host": "localhost:8888",
"Accept-Language": "en-US,en;q=0.8",
"Content-Type": "application/json",
"User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, li
ke Gecko) Chrome/52.0.2743.116 Safari/537.36",
"Connection": "keep-alive"
}
[E 21:26:39.484 NotebookApp] 501 POST /api/sessions?1472486198146 (::1) 1219.00m
s referer=http://localhost:8765/
[D 21:26:47.457 NotebookApp] 200 OPTIONS /api/sessions?1472486207450 (::1) 1.00m
s
[D 21:26:47.477 NotebookApp] No kernel specified, using default kernel
[D 21:26:47.545 NotebookApp] Native kernel (python3) available from C:\Anaconda3
\lib\site-packages\ipykernel\resources
WARNING:tornado.access:404 GET /favicon.ico (::1) 0.00ms
[W 21:26:48.459 NotebookApp] Kernel not found: None
[E 21:26:48.459 NotebookApp] {
"Referer": "http://localhost:8765/",
"Content-Length": "46",
"Accept": "*/*",
"Origin": "http://localhost:8765",
"Accept-Encoding": "gzip, deflate",
"Host": "localhost:8888",
"Accept-Language": "en-US,en;q=0.8",
"Content-Type": "application/json",
"User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, li
ke Gecko) Chrome/52.0.2743.116 Safari/537.36",
"Connection": "keep-alive"
}
[E 21:26:48.459 NotebookApp] 501 POST /api/sessions?1472486207450 (::1) 983.00ms
 referer=http://localhost:8765/

**Comment by rsinha25** [comment]
I hope this is what you wanted?

**Comment by blink1073** [comment]
Thanks @rsinha25, that is what I was looking for, though I'm not sure why exactly the API request is failing.

**Comment by blink1073** [comment]
It could be that your environment does not have its default kernel set.  It could be that you have an older version of `nb_conda_kernels`, can you please try `conda install nb_conda_kernels`?  I have v2.0.0 installed.

**Comment by jasongrout** [comment]
@rsinha25 - is this working for you now?

**Comment by rsinha25** [comment]
Hi, So I did what you asked. The example still doesn't work. However, the error message on the console is different. Here it is: 

Starting WebSocket: ws://localhost:8888/api/kernels/4e8ed405-a2ec-47b7-ac25-7d950a942804

Uncaught (in promise) TypeError: Cannot read property 'createBanner' of undefined(…)          widget.js:74 

ConsoleWidget @ widget.js:74
ConsolePanel @ panel.js:29
startApp @ index.js:67
(anonymous function) @ index.js:27

**Comment by blink1073** [comment]
I can confirm the behavior on Windows 10, not sure of the source of the problem though.

**Comment by jasongrout** [comment]
@blink1073 or @rsinha25 - is this working now?

**Comment by blink1073** [comment]
I just tried on master (9cef810f2a137d79f7adf7238aba8cfbdc5cff8f) on Windows 10 and the console example is working.

**Comment by ian-r-rose** [comment]
Closing as fixed.
