### ISSUE TITLE
Select search expression on Ctrl+F

### ISSUE THREAD

**Issue by afruehstueck** [jupyterlab/jupyterlab#7932]
In virtually every IDE, if you hit `Ctrl+F`, the search field opens with the previous content selected, such that when you `Ctrl+F` and start typing, you can directly input a new search expression.

In contrast, in Jupyterlab, the content will not be selected, which leads to a frustrating user experience.

## Reproduce
Here's a minimal demonstration of the behavior:
![jupyterlab](https://user-images.githubusercontent.com/19155913/75353784-feca7b00-58bc-11ea-8cc1-edbb08181597.gif)

## Expected behavior
I suggest the behavior gets adjusted such that the search text is selected on `Ctrl+F`.

**Comment by jasongrout** [comment]
Excellent idea, thanks for opening an issue. 

Here is where, for example, the find is opened and focused: https://github.com/jupyterlab/jupyterlab/blob/ac4668cd5dc8288757477e4c1718a7f309851882/packages/documentsearch-extension/src/index.ts#L130

Perhaps this "focusInput" method can be changed to select the text? https://github.com/jupyterlab/jupyterlab/blob/ac4668cd5dc8288757477e4c1718a7f309851882/packages/documentsearch/src/searchinstance.ts#L71

I think here is where the focusing actually happens, and what would need to change to select the text when focusing: https://github.com/jupyterlab/jupyterlab/blob/ac4668cd5dc8288757477e4c1718a7f309851882/packages/documentsearch/src/searchoverlay.tsx#L87-L91

Setting this as a good first issue. Would you like to try submitting a PR?

**Comment by SlowMonk** [comment]
which version this issue going to be fixed?

**Comment by jasongrout** [comment]
> which version this issue going to be fixed?

It's an open issue for anyone who wants to submit a PR. Would you like to contribute this fix? We can help you get set up to do the development.

**Comment by misterbeebee** [comment]
I've started a PR 8073, but I don't have a test environment set up yet. I might have one later.

If anyone has an automatically integrating test environment set up, this is a simple change to merge in and test.

**Comment by misterbeebee** [comment]
Automatic testing of PR #8073 failed, but I can't see how failures are caused by this PR.

**Comment by GabrielFritz** [comment]
Hi, is there anyone working on this? I'd like to work on it as my first issue!

**Comment by misterbeebee** [comment]
This is fixed.
