### ISSUE TITLE
"Restart kernel, re-run whole notebook"-button missing

### ISSUE THREAD

**Issue by Beaker034** [jupyterlab/jupyterlab#7935]
Hi all,
I would love to switch from Jupyter Notebook to JupyterLab, but I really miss the "Restart kernel, re-run whole notebook"-button.
![Unbenannt](https://user-images.githubusercontent.com/44819139/75366190-a5fbe200-58be-11ea-88d8-07956d3fcf42.PNG)

Are there any plans to add it in a future version?

**Comment by jasongrout** [comment]
There is a menu option to do this in the Kernel menu. That button must have been added to the notebook recently - we were pretty faithful about duplicating the notebook toolbar when we were writing JupyterLab.

Given that the command exists, it would be pretty easy to add to the toolbar as a CommandButton. A good first issue, perhaps?

Also, in JLab 2.0, there is a new "restart and run to current cell" command.

As for an icon, we could continue to use that fast forward icon, or nteract has been exploring a new icon: https://github.com/nteract/nteract/issues/4809#issuecomment-575307726

**Comment by jasongrout** [comment]
> There is a menu option to do this in the Kernel menu.

Actually, it's there and it's *also* in the Run menu.

**Comment by joelostblom** [comment]
This has been implemented in #8024, so this issue can be closed

**Comment by jasongrout** [comment]
Thanks for flagging this.
