### ISSUE TITLE
Update jupyterlab's lint setup

### ISSUE THREAD

**Issue by ajbozarth** [jupyterlab/jupyterlab#7939]
As discussed in a recent weekly dev meeting, the latest ESLint now supports a typescript plugin which would make tslint no longer necessary. the ipywidgets repo recently updated it's lint configs to the new version and can be used as a guide on updating the lab lint configs and version.

**Comment by ajbozarth** [comment]
Making this issue to make note that I am working on this in my spare moments. The above description probably needs a bit of fleshing out and clarification still.

**Comment by ajbozarth** [comment]
Un-assigning myself since I am unsure of if/when I will get to this.

**Comment by blink1073** [comment]
I tried using `typescript-eslint` in https://github.com/jupyterlab/jupyterlab/pull/8191, but I ran into problems.  I am going to try `babel-eslint` next.

**Comment by blink1073** [comment]
...and they're in the middle of migrating it into babel core, and it has not yet been released.

https://github.com/babel/babel/issues/10752
https://github.com/babel/babel/tree/master/eslint/babel-eslint-plugin

**Comment by blink1073** [comment]
I tried matching the `ipywidgets` [config](https://github.com/jupyter-widgets/ipywidgets/blob/54941b7a4b54036d089652d91b39f937bde6b6cd/.eslintrc.json), and it uncovered an issue:

```
$ eslint --fix .
Error: Error while loading rule '@typescript-eslint/no-floating-promises': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

It looks like we will need to stick with a `tsc`-based linter one way or another because that rule catches a lot of bugs.
