### ISSUE TITLE
terminal is always black

### ISSUE THREAD

**Issue by lewisl** [jupyterlab/jupyterlab#7953]
## Description

The terminal is always black with black text.
It is impossible to change the theme.
The "use <terminal> theme" command only works to choose dark or inherit.
Text is always invisible.

## Reproduce

Just open a terminal and try to do anything to change the theme.

## Expected behavior

The text should be visible.  It should be possible to change the background color of the terminal.

## Context

- Operating System and version: MacOS 10.15.3
- Browser and version: Brave, which is Chrome
- JupyterLab version: 2.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by vidartf** [comment]
What is your terminal theme set to?

![image](https://user-images.githubusercontent.com/510760/76747844-b8f12c00-6771-11ea-83d7-1f5d62bde15c.png)

**Comment by lewisl** [comment]
It was set to light theme.

I fixed it by reinstalling and update Jupyter and related packages.  Don’t really know what happened.

Call it closed.

Thanks for your reply.
