### ISSUE TITLE
python.exe crashes up to 50% using inspect in jupyterlab

### ISSUE THREAD

**Issue by yuzhujiutian** [jupyterlab/jupyterlab#7958]
## Description

After jupyterlab uses the inspect module, the python.exe program crashes up to 50%.

Every time the kernel is restarted, python.exe crashes on the second run cell code.

## Reproduce

1. cell code
```
import sys
import os
import time
import inspect
import platform

from selenium import webdriver


_print = print
def print(*args, **kwargs):
    _print(inspect.getframeinfo(inspect.currentframe().f_back)[1], time.strftime('%Y-%m-%d %H:%M:%S', time.localtime()), '.'*5, *args, **kwargs)

print('platform info:')
print('system   :', platform.system())
print('release  :', platform.release())
print('version  :', platform.version())
print('machine  :', platform.machine())
print('processor:', platform.processor(), os.linesep)
# print('platform info: {}{}'.format(os.linesep, platform.uname()), os.linesep)

print('python version: {}{}'.format(os.linesep, sys.version))
print('python directory: {}{}'.format(os.linesep, sys.executable), os.linesep)

#  cmd.exe | conda -V
cmd_win = '%windir%\System32\cmd.exe "/K" D:\winusr\anaconda\anaconda3_201910\Scripts\activate.bat D:\winusr\anaconda\anaconda3_201910 | conda -V'
print('conda version: {}{}'.format(os.linesep, os.popen(cmd_win).read()), os.linesep)

# browser info
print('browser info:')
driver = webdriver.Chrome(r'C:\Program Files (x86)\Google\Chrome\Application\chromedriver.exe')
# driver.minimize_window()
# print('debug:', driver.capabilities)
print('name: {}{}'.format(os.linesep, driver.capabilities['browserName']))
print('version: {}{}'.format(os.linesep, driver.capabilities['version']))
print('chromedriverVersion: {}{}'.format(os.linesep, driver.capabilities['chrome']['chromedriverVersion']), os.linesep)
driver.close()
```

2. Select the Cell and Click on Triangular button 'Run the selected cells and advance'

3. Scroll down to 'output' (it's OK)
```
14 2020-03-01 16:52:51 ..... platform info:
15 2020-03-01 16:52:51 ..... system   : Windows
16 2020-03-01 16:52:51 ..... release  : 7
17 2020-03-01 16:52:51 ..... version  : 6.1.7601
18 2020-03-01 16:52:51 ..... machine  : AMD64
19 2020-03-01 16:52:51 ..... processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel 

22 2020-03-01 16:52:51 ..... python version: 
3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
23 2020-03-01 16:52:51 ..... python directory: 
D:\winusr\anaconda\anaconda3_201910\envs\wanmore\python.exe 

27 2020-03-01 16:52:52 ..... conda version: 
conda 4.8.2
 

30 2020-03-01 16:52:52 ..... browser info:
34 2020-03-01 16:52:59 ..... name: 
chrome
35 2020-03-01 16:52:59 ..... version: 
67.0.3396.62
36 2020-03-01 16:52:59 ..... chromedriverVersion: 
2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7) 
```

4. Repeat step 2

5. See error 'python.exe crashed'
![image](https://user-images.githubusercontent.com/386347/75622699-364b6700-5bde-11ea-97ad-806939c57c68.png)

## Context

- Operating System and version: win7 x64
- Browser and version: chrome 67.0.3396.62
- JupyterLab version: 
```
(wanmore) PS D:\winusr\anaconda\anaconda3_201910\envs\wanmore> conda -V
conda 4.8.2
(wanmore) PS D:\winusr\anaconda\anaconda3_201910\envs\wanmore> jupyter notebook --version
6.0.3
(wanmore) PS D:\winusr\anaconda\anaconda3_201910\envs\wanmore> conda list | findstr 'jupyterlab'
jupyterlab                2.0.0                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
(wanmore) PS D:\winusr\anaconda\anaconda3_201910\envs\wanmore>
```

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

(ps: some path values have been removed, and user name has also been replaced.)
$PATH:
	C:\Users\helloc\AppData\Roaming\Python\Python37\site-packages\pywin32_system32
	C:\Users\helloc\AppData\Roaming\Python\Python37\site-packages\pywin32_system32
	C:\Users\helloc\AppData\Roaming\Python\Python37\site-packages\pywin32_system32
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\Library\mingw-w64\bin
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\Library\usr\bin
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\Library\bin
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\Scripts
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\bin
	D:\winusr\anaconda\anaconda3_201910
	D:\winusr\anaconda\anaconda3_201910\Library\mingw-w64\bin
	D:\winusr\anaconda\anaconda3_201910\Library\usr\bin
	D:\winusr\anaconda\anaconda3_201910\Library\bin
	D:\winusr\anaconda\anaconda3_201910\Scripts
	D:\winusr\anaconda\anaconda3_201910\bin
	D:\winusr\anaconda\anaconda3_201910\condabin
	C:\Users\helloc\AppData\Roaming\Python\Python37\site-packages\pywin32_system32
	D:\winusr\anaconda\anaconda3_201910
	D:\winusr\anaconda\anaconda3_201910\Library\mingw-w64\bin
	D:\winusr\anaconda\anaconda3_201910\Library\usr\bin
	D:\winusr\anaconda\anaconda3_201910\Library\bin
	D:\winusr\anaconda\anaconda3_201910\Scripts
	D:\winusr\anaconda\anaconda3_201910\bin
	%SystemRoot%\system32\WindowsPowerShell\v1.0
	C:\Windows\System32\WindowsPowerShell\v1.0
	D:\winusr\nodejs\nodejs_v12.14.1_x64
	D:\winusr\anaconda\anaconda3_201910
	D:\winusr\anaconda\anaconda3_201910\Scripts
	D:\winusr\anaconda\anaconda3_201910\Library\bin
	D:\winusr\anaconda\anaconda3_201910\Library\usr\bin
	D:\winusr\anaconda\anaconda3_201910\Library\mingw-w64\bin
	C:\Users\helloc\AppData\Roaming\npm
	D:\winusr\microsoft\vscode\vscode_v1.42.2_x64\bin

sys.path:
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\Scripts
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\python37.zip
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\DLLs
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\lib
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore
	C:\Users\helloc\AppData\Roaming\Python\Python37\site-packages
	C:\Users\helloc\AppData\Roaming\Python\Python37\site-packages\win32
	C:\Users\helloc\AppData\Roaming\Python\Python37\site-packages\win32\lib
	C:\Users\helloc\AppData\Roaming\Python\Python37\site-packages\Pythonwin
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\lib\site-packages
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\lib\site-packages\win32
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\lib\site-packages\win32\lib
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\lib\site-packages\Pythonwin

sys.executable:
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\python.exe

sys.version:
	3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

platform.platform():
	Windows-7-6.1.7601-SP1

where jupyter:
	D:\winusr\anaconda\anaconda3_201910\envs\wanmore\Scripts\jupyter.exe

	D:\winusr\anaconda\anaconda3_201910\Scripts\jupyter.exe

pip list:
	Package            Version            

	------------------ -------------------

	astroid            2.3.3              

	attrs              19.3.0             

	backcall           0.1.0              

	bleach             3.1.1              

	certifi            2019.11.28         

	cffi               1.13.2             

	colander           0.9.9              

	colorama           0.4.3              

	comtypes           1.1.7              

	cryptography       2.8                

	decorator          4.4.2              

	defusedxml         0.6.0              

	entrypoints        0.3                

	Flask              0.10.1             

	idna               2.9                

	importlib-metadata 1.5.0              

	ipykernel          5.1.4              

	ipython            7.13.0             

	ipython-genutils   0.2.0              

	iso8601            0.1.8              

	isort              4.3.21             

	itsdangerous       1.1.0              

	jedi               0.16.0             

	Jinja2             2.11.1             

	json5              0.9.0              

	jsonschema         3.2.0              

	jupyter-client     6.0.0              

	jupyter-core       4.6.3              

	jupyterlab         2.0.0              

	jupyterlab-server  1.0.6              

	lark-parser        0.8.1              

	lazy-object-proxy  1.4.3              

	MarkupSafe         1.1.1              

	mccabe             0.6.1              

	mistune            0.8.4              

	nbconvert          5.6.1              

	nbformat           5.0.4              

	notebook           6.0.3              

	numpy              1.18.1             

	pandas             1.0.1              

	pandocfilters      1.4.2              

	parso              0.6.1              

	pickleshare        0.7.5              

	pip                20.0.2             

	prometheus-client  0.7.1              

	prompt-toolkit     3.0.3              

	psutil             5.6.7              

	pycparser          2.19               

	Pygments           2.5.2              

	pylint             2.4.4              

	pyOpenSSL          19.1.0             

	pyrsistent         0.14.11            

	PySocks            1.7.1              

	python-dateutil    2.8.1              

	pytz               2019.3             

	pywin32            227                

	pywinpty           0.5.7              

	pyzmq              19.0.0             

	redis              2.8.0              

	selenium           3.141.0            

	Send2Trash         1.5.0              

	setuptools         45.2.0.post20200209

	six                1.14.0             

	terminado          0.8.3              

	testpath           0.4.4              

	tornado            6.0.3              

	traitlets          4.3.3              

	translationstring  1.3                

	typed-ast          1.4.1              

	urllib3            1.25.7             

	wcwidth            0.1.8              

	webencodings       0.5.1              

	Werkzeug           1.0.0              

	wheel              0.34.2             

	win-inet-pton      1.1.0              

	wincertstore       0.2                

	wrapt              1.11.2             

	xlwings            0.18.0             

	zipp               3.0.0

conda list:
	# packages in environment at D:\winusr\anaconda\anaconda3_201910\envs\wanmore:

	#

	# Name                    Version                   Build  Channel

	attrs                     19.3.0                     py_0    conda-forge

	backcall                  0.1.0                      py_0    conda-forge

	bleach                    3.1.1                      py_0    conda-forge

	ca-certificates           2019.11.28           hecc5488_0    conda-forge

	certifi                   2019.11.28               py37_0    conda-forge

	cffi                      1.13.2           py37hb32ad35_0    conda-forge

	colander                  0.9.9                    pypi_0    pypi

	colorama                  0.4.3                      py_0    conda-forge

	comtypes                  1.1.7                 py37_1000    conda-forge

	cryptography              2.8              py37hb32ad35_1    conda-forge

	decorator                 4.4.2                      py_0    conda-forge

	defusedxml                0.6.0                      py_0    conda-forge

	entrypoints               0.3                   py37_1000    conda-forge

	flask                     0.10.1                   pypi_0    pypi

	idna                      2.9                        py_1    conda-forge

	importlib_metadata        1.5.0                    py37_0    conda-forge

	intel-openmp              2020.0                      166  

	ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge

	ipython                   7.13.0           py37h5ca1d4c_0    conda-forge

	ipython_genutils          0.2.0                      py_1    conda-forge

	iso8601                   0.1.8                    pypi_0    pypi

	itsdangerous              1.1.0                    pypi_0    pypi

	jedi                      0.16.0                   py37_0    conda-forge

	jinja2                    2.11.1                     py_0    conda-forge

	json5                     0.9.0                      py_0    conda-forge

	jsonschema                3.2.0                    py37_0    conda-forge

	jupyter_client            6.0.0                      py_0    conda-forge

	jupyter_core              4.6.3                    py37_0    conda-forge

	jupyterlab                2.0.0                      py_0    conda-forge

	jupyterlab_server         1.0.6                      py_0    conda-forge

	lark-parser               0.8.1                      py_0    conda-forge

	libblas                   3.8.0                    15_mkl    conda-forge

	libcblas                  3.8.0                    15_mkl    conda-forge

	liblapack                 3.8.0                    15_mkl    conda-forge

	libsodium                 1.0.17               h2fa13f4_0    conda-forge

	m2w64-gcc-libgfortran     5.3.0                         6  

	m2w64-gcc-libs            5.3.0                         7  

	m2w64-gcc-libs-core       5.3.0                         7  

	m2w64-gmp                 6.1.0                         2  

	m2w64-libwinpthread-git   5.0.0.4634.697f757               2  

	markupsafe                1.1.1            py37hfa6e2cd_0    conda-forge

	mistune                   0.8.4           py37hfa6e2cd_1000    conda-forge

	mkl                       2020.0                      166  

	msys2-conda-epoch         20160418                      1  

	nbconvert                 5.6.1                    py37_0    conda-forge

	nbformat                  5.0.4                      py_0    conda-forge

	notebook                  6.0.3                    py37_0    conda-forge

	numpy                     1.18.1           py37hc71023c_0    conda-forge

	openssl                   1.1.1d               hfa6e2cd_0    conda-forge

	pandas                    1.0.1            py37h47e9c7a_0  

	pandoc                    2.9.2                         0    conda-forge

	pandocfilters             1.4.2                      py_1    conda-forge

	parso                     0.6.1                      py_0    conda-forge

	pickleshare               0.7.5                 py37_1000    conda-forge

	pip                       20.0.2                     py_2    conda-forge

	prometheus_client         0.7.1                      py_0    conda-forge

	prompt_toolkit            3.0.3                      py_0    conda-forge

	psutil                    5.6.7            py37he774522_0  

	pycparser                 2.19                       py_2    conda-forge

	pygments                  2.5.2                      py_0    conda-forge

	pyopenssl                 19.1.0                     py_1    conda-forge

	pyrsistent                0.14.11          py37hfa6e2cd_1    conda-forge

	pysocks                   1.7.1                    py37_0    conda-forge

	python                    3.7.6                h60c2a47_2  

	python-dateutil           2.8.1                      py_0    conda-forge

	pytz                      2019.3                     py_0    conda-forge

	pywin32                   227              py37hfa6e2cd_0    conda-forge

	pywinpty                  0.5.7                    py37_0    conda-forge

	pyzmq                     19.0.0           py37h16f9016_0    conda-forge

	redis                     2.8.0                    pypi_0    pypi

	selenium                  3.141.0         py37hfa6e2cd_1000    conda-forge

	send2trash                1.5.0                      py_0    conda-forge

	setuptools                45.2.0                   py37_0    conda-forge

	six                       1.14.0                   py37_0    conda-forge

	sqlite                    3.30.1               hfa6e2cd_0    conda-forge

	terminado                 0.8.3                    py37_0    conda-forge

	testpath                  0.4.4                      py_0    conda-forge

	tornado                   6.0.3            py37hfa6e2cd_4    conda-forge

	traitlets                 4.3.3                    py37_0    conda-forge

	translationstring         1.3                      pypi_0    pypi

	urllib3                   1.25.7                   py37_0    conda-forge

	vc                        14.1                 h0510ff6_4  

	vs2015_runtime            14.16.27012          hf0eaf9b_1  

	wcwidth                   0.1.8                      py_0    conda-forge

	webencodings              0.5.1                      py_1    conda-forge

	werkzeug                  1.0.0                    pypi_0    pypi

	wheel                     0.34.2                     py_1    conda-forge

	win_inet_pton             1.1.0                    py37_0    conda-forge

	wincertstore              0.2                   py37_1003    conda-forge

	winpty                    0.4.3                         4    conda-forge

	xlwings                   0.18.0                   py37_0    conda-forge

	zeromq                    4.3.2                h6538335_2    conda-forge

	zipp                      3.0.0                      py_0    conda-forge

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

(base) PS C:\Users\helloc> conda activate wanmore
(wanmore) PS C:\Users\helloc> jupyter notebook list
Currently running servers:
http://localhost:8888/?token=d8a6b3807c48cb276c29f387baff1d2388c2808ef79888e3 ::
 C:\Users\helloc
http://localhost:8888/?token=64ebf2725cf3a26aa322d25ab622a245d67ef1bd1dd0d074 ::
 C:\Users\helloc
(wanmore) PS C:\Users\helloc> jupyter lab
[I 15:55:43.786 LabApp] JupyterLab extension loaded from D:\winusr\anaconda\anac
onda3_201910\envs\wanmore\lib\site-packages\jupyterlab
[I 15:55:43.788 LabApp] JupyterLab application directory is D:\winusr\anaconda\a
naconda3_201910\envs\wanmore\share\jupyter\lab
[I 15:55:43.796 LabApp] Serving notebooks from local directory: C:\Users\helloc
[I 15:55:43.799 LabApp] The Jupyter Notebook is running at:
[I 15:55:43.801 LabApp] http://localhost:8888/?token=41ad6c1d2d6c00dce0c8500d343
628746a0280083d4b9cdf
[I 15:55:43.804 LabApp]  or http://127.0.0.1:8888/?token=41ad6c1d2d6c00dce0c8500
d343628746a0280083d4b9cdf
[I 15:55:43.806 LabApp] Use Control-C to stop this server and shut down all kern
els (twice to skip confirmation).
[C 15:55:44.156 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/helloc/AppData/Roaming/jupyter/runtime/nbserver-2558
0-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=41ad6c1d2d6c00dce0c8500d343628746a0280083d4
b9cdf
     or http://127.0.0.1:8888/?token=41ad6c1d2d6c00dce0c8500d343628746a0280083d4
b9cdf
[I 15:55:49.792 LabApp] Build is up to date
[I 15:55:51.604 LabApp] Kernel started: 8e50c6a0-4bbc-4738-8dea-36edf94c8de5
[I 15:56:23.515 LabApp] Build is up to date
[I 15:58:22.580 LabApp] 301 GET /lab/workspaces/auto-C/?clone (::1) 1.50ms
[I 15:58:25.338 LabApp] Build is up to date
[I 15:59:38.111 LabApp] 302 GET /?token=41ad6c1d2d6c00dce0c8500d343628746a028008
3d4b9cdf (127.0.0.1) 0.50ms
[I 15:59:41.737 LabApp] Build is up to date
文件名、目录名或卷标语法不正确。

DevTools listening on ws://127.0.0.1:12963/devtools/browser/b48bc370-4faf-4318-9
166-5806efc94189
[0301/160437.077:ERROR:gl_surface_egl.cc(844)] eglInitialize D3D11 failed with e
rror EGL_NOT_INITIALIZED, trying next display type
[I 16:05:41.868 LabApp] Saving file at /jupyterlab-helloc.ipynb
[I 16:07:42.266 LabApp] Saving file at /jupyterlab-helloc.ipynb
[I 16:09:42.542 LabApp] Saving file at /jupyterlab-helloc.ipynb
文件名、目录名或卷标语法不正确。

DevTools listening on ws://127.0.0.1:12616/devtools/browser/3c5fcbe7-481b-467d-8
d0f-f5bd73f17f47
[0301/161054.234:ERROR:gl_surface_egl.cc(844)] eglInitialize D3D11 failed with e
rror EGL_NOT_INITIALIZED, trying next display type
[I 16:11:40.852 LabApp] Saving file at /jupyterlab-helloc.ipynb
文件名、目录名或卷标语法不正确。

DevTools listening on ws://127.0.0.1:12722/devtools/browser/9dd6d6dc-e4c0-4158-9
aa7-ae5bbfe726b1
[0301/161208.852:ERROR:gl_surface_egl.cc(844)] eglInitialize D3D11 failed with e
rror EGL_NOT_INITIALIZED, trying next display type
[I 16:13:41.164 LabApp] Saving file at /jupyterlab-helloc.ipynb
[I 16:14:38.871 LabApp] Kernel restarted: 8e50c6a0-4bbc-4738-8dea-36edf94c8de5
[I 16:15:38.759 LabApp] Kernel restarted: 8e50c6a0-4bbc-4738-8dea-36edf94c8de5
[I 16:15:41.238 LabApp] Saving file at /jupyterlab-helloc.ipynb
文件名、目录名或卷标语法不正确。

DevTools listening on ws://127.0.0.1:12979/devtools/browser/71d7ba20-c78a-4969-8
42d-689c98f0fc06
[0301/161554.781:ERROR:gl_surface_egl.cc(844)] eglInitialize D3D11 failed with e
rror EGL_NOT_INITIALIZED, trying next display type
[I 16:16:26.092 LabApp] Kernel restarted: 8e50c6a0-4bbc-4738-8dea-36edf94c8de5
文件名、目录名或卷标语法不正确。

DevTools listening on ws://127.0.0.1:12126/devtools/browser/5a0ab490-5ab6-4482-8
706-c2c587517fc8
[0301/161640.262:ERROR:gl_surface_egl.cc(844)] eglInitialize D3D11 failed with e
rror EGL_NOT_INITIALIZED, trying next display type
[0301/161640.848:ERROR:gles2_cmd_decoder.cc(15985)] Context lost because SwapBuf
fers failed.
[I 16:17:41.331 LabApp] Saving file at /jupyterlab-helloc.ipynb
[I 16:17:51.548 LabApp] Kernel restarted: 8e50c6a0-4bbc-4738-8dea-36edf94c8de5
文件名、目录名或卷标语法不正确。

DevTools listening on ws://127.0.0.1:12389/devtools/browser/d9fbcba1-1cb9-49be-a
6b5-c0b4a81fe1b7
[0301/161802.162:ERROR:gl_surface_egl.cc(844)] eglInitialize D3D11 failed with e
rror EGL_NOT_INITIALIZED, trying next display type
[I 16:19:41.863 LabApp] Saving file at /jupyterlab-helloc.ipynb
[I 16:23:41.940 LabApp] Saving file at /jupyterlab-helloc.ipynb
文件名、目录名或卷标语法不正确。

DevTools listening on ws://127.0.0.1:12543/devtools/browser/85990e63-fac1-4286-8
ace-174a8b7ae0ca

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by vidartf** [comment]
What happens if you run this code from a normal Python REPL (e.g. run `python`, and run the code there). What about if you put the code (twice) in a .py script and run that?

**Comment by yuzhujiutian** [comment]
code line 26 27
pycharm, has some other program ( but it has nothing to do with issure #7958.)
![image](https://user-images.githubusercontent.com/386347/75649222-70c00d00-5c8d-11ea-9e37-976793f279fe.png)


Comment code line 26 27
pycharm, run 3 times OK.
![image](https://user-images.githubusercontent.com/386347/75649129-263e9080-5c8d-11ea-99cf-53a293fb4bda.png)

Comment code line 26 27
anaconda env wanmore, python tmp.py, run 2 times OK.
![image](https://user-images.githubusercontent.com/386347/75649528-5a668100-5c8e-11ea-89ef-34a5d416d964.png)

Comment code line 26 27
jupyter lab, run 2 time, also NOK (first OK, second NOK - python.exe crashed same as issue #7958)
![image](https://user-images.githubusercontent.com/386347/75649740-01e3b380-5c8f-11ea-9340-2ed7b8370b4c.png)

**Comment by yuzhujiutian** [comment]
and if i comment code line 10 11 12
jupyter lab, run 3 times OK, no problem, so i guess it's related to the use of inspect.

![image](https://user-images.githubusercontent.com/386347/75650520-0c9f4800-5c91-11ea-8889-aa3c33fc70a0.png)


![image](https://user-images.githubusercontent.com/386347/75650483-eed1e300-5c90-11ea-9526-01d5fadebbf8.png)

**Comment by vidartf** [comment]
I'm not sure if you simply ran the script twice, or if the code is there twice in the script?

**Comment by yuzhujiutian** [comment]
simply ran the script twic

**Comment by vidartf** [comment]
That would not be similar to running the code twice in Jupyter (it would be similar to restarting the kernel between each run).
