### ISSUE TITLE
Status bar styling issue

### ISSUE THREAD

**Issue by bsyouness** [jupyterlab/jupyterlab#7963]
The status bar items (at the bottom of the window) get clipped when the window isn't wide enough to display them:
<img width="515" alt="Screen Shot 2020-03-02 at 2 18 19 PM" src="https://user-images.githubusercontent.com/2256598/75723330-eed1e300-5c90-11ea-813d-9a0d5244b079.png">

Note, this also happens when other elements appear in the status bar that don't fit within the width of the window (e.g. when a notebook is saving).

**Comment by jasongrout** [comment]
Fixed in #7964
