### ISSUE TITLE
Extension Installer disclaimer UI

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#7967]
There's been a push lately to improve JupyterLab's Extension Installer so it can ship activated in JupyterLab. There's been some discussion surrounding whitelisting/blocking extensions in #7933 as well as how to communicate that installing extensions may be a risk to the user. 

First a little background for the design.

## Who cares about the extension installer?
**New users** will have a less intimidating method to discover and install extensions, they may be less aware of the danger, and will likely be skimming over copy as they learn to use JupyterLab.

**Infrequent Users** can install extensions while staying inside JupyterLab, without having to reference special commands. We need to keep in mind that they may see the warning, then don't user JupyterLab for a period in between.

**Daily/Weekly Users** will likely have a better understanding of how JupyterLab works, I'm a little bit less worried that they need to be reminded every time, they will also have a lower tolerance for a more jarring disclaimer. There is also a higher chance that they choose to manage their extensions from the command line.

## Ideas
I think we have 2 main knobs to turn as far as how we can deal with the disclaimer: 
- How persistent is the warning?
- How jarring is the warning?

To start off with, I wanted to explore the frequency of the warning. 

First, we have a 1-time warning on each install:
![extension-installer-one-time-warning](https://user-images.githubusercontent.com/22109376/75742830-be576c80-5cc3-11ea-922a-942d01b135de.gif)
For this one we can tweak how often we show it, but it does give a pretty solid warning, and we can do something like adds a counter that checks if the installer has been used in the last month and throw another warning if not.

And here's a more persistent interface:
![extension-installer-persistant-warning](https://user-images.githubusercontent.com/22109376/75742882-ee9f0b00-5cc3-11ea-9fcf-023c59f9a1e1.gif)
We can iterate around how to hide this if it's bothersome, but this is a low-jarring, high-persistency option. 

If we want to go for jarring and persistent, we can do something more like this:
![Iterations 8 - modal](https://user-images.githubusercontent.com/22109376/75742960-2a39d500-5cc4-11ea-9879-193b90511e1e.png)
We can show this every extension install until it's disabled. 

Give me your thoughts and we can iterate further.

**Comment by echarles** [comment]
Thx @tgeorgeux. Do I understand the options correctly:

1. 1-time warning on each install (or on install after a defined amount of time).
2. Always visible checkbox in the manager (if not checked, manager is disabled).
3. Modal window that is shown one time per session (and not shown anymore if the user clicks on "don't show again")

How exclusive are those options? I guess we do not want all three at the same time, so we need to choose for one or maybe a duo of those?

**Comment by tgeorgeux** [comment]
For option 3 I was thinking it would be a warning on each extension install, but once per server session is another interesting idea.

> How exclusive are those options?
These are starting points, I think the final will some combination of these, just wanted to start on the extremes.

> I guess we do not want all three at the same time, so we need to choose for one or maybe a duo of those?
Yes, these are competing options at this point.

**Comment by echarles** [comment]
This turns out to the following:

1. One-time warning on each install (or on-install after a defined amount of time)
2. Always visible checkbox in the manager (if not checked, manager is disabled)
3. Modal warning window on each extension installation (with "don't show again" checkbox)
4. Modal warning window one time per session when activating the extension manager (with "don't show again" checkbox)

Thx @tgeorgeux for the UIs you created and that make these item lines more concrete.

**Comment by MarsBarLee** [comment]
I'm working with Tim, so here's my iteration on Tim's second blacklist idea.

**Visible checkbox in the manager (if not checked, manager is disabled). Once checked, disclaimer is collapsible.**
![JupyterLab-Extension-Manager-Disclaimer](https://user-images.githubusercontent.com/46167686/75911040-e60e1800-5e1c-11ea-9417-d35981205d8c.gif)

This way, the disclaimer isn't as jarring as a modal warning window.

It is persistent, but can be moved out of view once the disclaimer is accepted, which would be suit Daily/Weekly users.

I could see this warning with the unchecked checkbox happening only for the first time using the extension manager, or once-per-session as @echarles suggested.

**Comment by tgeorgeux** [comment]
I had a couple of questions about the existing UI.

1) Is anybody attached to the @ symbols? They are a bit repetitive, I think we can go forward without them, but if somebody has a good reason to leave them in I am unaware of please let me know.
2) Some of the extensions in the existing UI don't have orgs or usernames (see screenshot). Is this something the extension developer is doing on purpose?
<img width="415" alt="Screen Shot 2020-03-12 at 12 22 58 PM" src="https://user-images.githubusercontent.com/22109376/76568752-c2774d00-646e-11ea-9578-47a079d9dbe3.png">

**Comment by jasongrout** [comment]
>     1. Is anybody attached to the @ symbols? They are a bit repetitive, I think we can go forward without them, but if somebody has a good reason to leave them in I am unaware of please let me know.

Yes. Npm is attached to them :). They are part of the official names of the packages. See the docs at npm about scopes for more info: https://docs.npmjs.com/about-org-scopes-and-packages

**Comment by jasongrout** [comment]
> Some of the extensions in the existing UI don't have orgs or usernames (see screenshot). Is this something the extension developer is doing on purpose?

Yes. An npm package can be named just a string of characters, or it can have a `@org/` prefix as part of the name. In other words, the name of the package is `@descarteslabs/jupyterlab-viewer2`, not `jupyterlab-viewer2`

**Comment by MarsBarLee** [comment]
![disclaimer-03-14-20](https://user-images.githubusercontent.com/46167686/76684118-ad6dfb80-65df-11ea-8e70-772891a21742.png)
Hi all, Tim and I have been working out some more details.

- We're thinking of increasing the size of the icons and moving them to the left to be more visible and make it easier to tell who or what organization the extension is from. For extensions from Github users, we will be using their Github icons or identicons. What do others think?

- We're still working on the phrasing of the disclaimer and finding the good place between being explicit but not too worrying. Let us know if you have suggestion on how we can phrase this.

The grey buttons we have in the mockup are not changes we are suggesting. For the final implementation, we will be using the current JupyterLab button designs.

**Comment by echarles** [comment]
Thx @MarsBarLee @tgeorgeux 

Is it possible to open a separated issue for the icon? The icon change is not really related to the disclaimer nor the black/white listings. It is also not minor enough to onboard here and subject to discussion (where to fetch the image...). Having a dedicated issue will ease the discussions and will keep things clear.

I will integrate in the B/W list PR the current text disclaimer suggestions, including the CSS you have provided.

**Comment by echarles** [comment]
Thx @tgeorgeux for opening a dedicated issue for the icons.

Implementation of the CSS for the disclaimer:

<img width="412" alt="Screenshot 2020-03-16 at 10 36 06" src="https://user-images.githubusercontent.com/226720/76743818-80eae880-6773-11ea-927a-b58a070b502e.png">

**Comment by its-dhung** [comment]
Looks great! A couple of thoughts regarding the disclaimer dropdown.

1. I like the copy used in the modal mockup above. It's more clear in what it's warning the user about IMHO.
2. Instead of a checkbox to enable the extension manager, how about a button? A button may make it more obvious that the user needs to do something in order to access extensions. However, if we think users may want to disable the extension manager mid session, I could see an argument being made for a checkbox.

**Comment by saulshanabrook** [comment]
Added in https://github.com/jupyterlab/jupyterlab/pull/7989
