### ISSUE TITLE
PDFs are missing an icon

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab#7968]
# Description

PDF files in the file browser no longer have an accompanying icon.
It was never very good in the first place (my fault, I'm afraid), but now it is missing all together.

## Reproduce

Navigate to a PDF file i the file browser.
![image](https://user-images.githubusercontent.com/5728311/75748641-d4215d80-5cd4-11ea-8287-713f406d0f02.png)

## Context

@telamonian it looks like the file browser is intended to have a fallback icon with the new `LabIcon` setup. Might that not be working as intended?

**Comment by telamonian** [comment]
I'm on it
