### ISSUE TITLE
UX: Easier File Rename

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#7973]
## Description

When a new notebook is created, it is named `UntitledXX.ipynb`. In the old Notebook UI, this could be changed with a single click. In the current UI you need to right click then choose rename. Given how common it is to want to rename a notebook, I suggest we make this easier. 

Suggestion 1: Double click on the name in the tab should allow one to change the file name (i.e. execute `docmanager:rename`).

## Context

- Browser and version: Chrome
- JupyterLab version: 1.2.3

**Comment by jasongrout** [comment]
+1 to making this much easier to rename.

**Comment by jasongrout** [comment]
This is very similar to #4119 - should we consolidate the discussion there?

**Comment by mlucool** [comment]
Sure, I didn't see that when I searched issues. Sorry for the second issue.
