### ISSUE TITLE
Documentation 1.2.7 not available

### ISSUE THREAD

**Issue by lober-io** [jupyterlab/jupyterlab#7987]
## Description

When switching from the documentation of version "stable" to "1.27"   the page is not loaded

![image](https://user-images.githubusercontent.com/9661453/75880091-ea3a3580-5e1c-11ea-8cfd-580bd58f6d50.png)

## Reproduce

1. Go to 'https://jupyterlab.readthedocs.io/en/stable/'
2. Click on 'v: stable'
3. Click in 'v1.2.7
4. See error 'SORRY  This page does not exist yet'

## Expected behavior

Documentation for 1.27 is shown

**Comment by jasongrout** [comment]
I turned in docs for 1.2.7, but building it failed several times with an out of memory error

**Comment by blink1073** [comment]
Yes, this is related to https://github.com/jupyterlab/jupyterlab/pull/7930.  I updated the 1.x branch, and the latest build is passing, but we'll need a new tagged release.

**Comment by jasongrout** [comment]
I think the 1.x branch documentation probably works now, then?

**Comment by blink1073** [comment]
It does, but not for the v1.2.7 tag, since that commit doesn't have the docs build fix.

**Comment by jasongrout** [comment]
Yep. For now I deleted the option for 1.2.7, so there is just `latest`, `stable`, and `1.x`

**Comment by blink1073** [comment]
That seems like a fair path moving forward.

**Comment by jasongrout** [comment]
Great. Closing as resolved, then.
