### ISSUE TITLE
Incorrect cookiecutter checkout label in extension tutorial

### ISSUE THREAD

**Issue by droctothorpe** [jupyterlab/jupyterlab#7990]
## Description

The [extension tutorial](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/extension_tutorial.rst#initialize-the-project-from-a-cookiecutter) doesn't work because in the `cookiecutter` command `--checkout v2.0beta` is being passed instead of `--checkout v2.0`. The latter is compatible with JupyterLab 2.0; the former is not. 

## Reproduce

Go to the the [extension tutorial](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/extension_tutorial.rst) and follow the steps until `jupyter labextension install . --no-build`. It will fail due to a version mismatch.

```
An error occured.
ValueError:
"jupyterlab_apod@0.1.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.0.0 <2.1.0          >=1.0.0 <2.0.0 @jupyterlab/application
```

This occurs because the wrong version of the cookiecutter template is being checked out. 

I updated the checkout tag and confirmed that it works. I'll push a PR as soon as I submit this issue.

## Expected behavior

The lab extension should build. It doesn't. 

## Context

- Operating System and version:
OSX Catalina
- Browser and version:
Chrome Version 80.0.3987.122 (Official Build) (64-bit)
- JupyterLab version:
2.0

**Comment by droctothorpe** [comment]
[Link](https://github.com/jupyterlab/jupyterlab/pull/7991/files) to PR.

**Comment by lresende** [comment]
This should be fixed by the PR linked above? Otherwise, please reopen this issue.
