### ISSUE TITLE
Allow custom session startup behavior for widgets

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#7996]
We currently offer some declarative kernel preferences on the widget factories that are used to define the behavior of kernel startup.  I propose that we add an option to provide a callback function, so that the widget factory has full control over the startup behavior, and can take into account external factors such as the result of an API call or information in the document itself.

Additionally, we should expose the `NotebookWidgetFactory` as a token and a separate plugin, so it is easier to override this behavior for notebooks.

**Comment by jasongrout** [comment]
Makes sense to me.

**Comment by blink1073** [comment]
I'd like to implement just the ability to override the `NotebookWidgetFactory` in 2.1 and save the more invasive changes for 3.0.

**Comment by jasongrout** [comment]
> I'd like to implement just the ability to override the `NotebookWidgetFactory` in 2.1 and save the more invasive changes for 3.0.

Sounds good to me.
