### ISSUE TITLE
jupyterlab-hub executable needs to be removed in 2.0.0

### ISSUE THREAD

**Issue by joequant** [jupyterlab/jupyterlab#7998]
## Description

jupyterlab-hub executable still is in 2.0.0 even though the library module has been removed

## Reproduce

install jupyterlab, the executable jupyterlab-hub still exists even though it throws an error if run

## Expected behavior

Executable should be removed

## Context

- Operating System and version: linux
- Browser and version:
- JupyterLab version: 2.0.0

**Comment by jasongrout** [comment]
Tagging as 2.0 for a patch release. Thanks for bringing this to our attention.
