### ISSUE TITLE
Add UI Component - Switches

### ISSUE THREAD

**Issue by tgeorgeux** [jupyterlab/jupyterlab#8010]
@jtpio asked me about this a few days ago and I have been working on making a canonical switch for Jupyterlab. 

I started with Material Design switches as a basis, but I think Blueprint switches are also nice. Material design switches:
![mio-components_assets_1MiD-2erXPyZKDpOOdaWTsqzkHGOt9Z7R_selectioncontrols-switches-states](https://user-images.githubusercontent.com/22109376/76152867-83fe1e80-6079-11ea-960f-0820830c8163.png)
I started playing around with a way to make these more compact. One thing Material design does really well is the animations and movements fade into the background really well, one thing it doesn't do well exists in compact environments.

In order to make this a little more compact, I tried to use already existing UI shadows in JupyterLab for hover and click effect. I'm not happy with it yet, I'll play around with it more soon, just wanted to dump it here. I'm also working on a more compact version for use in toolbars and other compact locations.
![Switch](https://user-images.githubusercontent.com/22109376/76153000-e7d51700-607a-11ea-8534-6ff45f55529c.gif)

@telamonian Do you think it makes sense to make this a custom react component inside our new UI components package once it's finished?

More to come.

**Comment by telamonian** [comment]
> Do you think it makes sense to make this a custom react component inside our new UI components package once it's finished?

Definitely. Possibly it should be a variant of a LabButton component

**Comment by jtpio** [comment]
FWIW: the [theme-toggle](https://github.com/jtpio/jupyterlab-theme-toggle) extension currently uses a Blueprint Switch to switch between the light and dark themes, to get an idea of what it looks like in lab:

![theme-toggle](https://user-images.githubusercontent.com/591645/76191906-b37b6b00-61e0-11ea-8bb8-ae6fd26c1bcb.gif)

The inner text is also quite useful. Maybe we would need something similar to differentiate between two switch buttons side-by-side in a toolbar? (an icon would also work)

**Comment by fcollonval** [comment]
@jtpio could we close this?

**Comment by jtpio** [comment]
Sure.

For reference there is now a `Switch` component in the `ui-components` package:

https://github.com/jupyterlab/jupyterlab/blob/81f69be38cc9ffbea5b05706e334e5c85f58a853/packages/ui-components/src/components/switch.ts#L8-L11
