### ISSUE TITLE
[Feature Request] __file__ cell magic

### ISSUE THREAD

**Issue by geyang** [jupyterlab/jupyterlab#8012]
In my machine learning workflow, I log to a remote server using a logging prefix that mirrors the folder structure of my experiment module. When I do so from python scripts it is easy to find the path for the launch script. Currently this is not possible in the ipython kernel because the path is in the client space.

It seems that this is something that can be done cleanly using a magic command that inject the "__file__" global into the kernel runtime.

here is the proposed syntax -- it might even make sense to make this the default behavior.

```python
%__file__

print(__file__)
```
should output:
```sh
"uvpn_experiments/icml_2020/local_metric_analysis.ipynb"
```

Then whatever happens afterward can treat this runtime the same way as a standard python script.

Wanting to use notebooks under a path context is a fairly common request in the wild. It would be good for the community recognize it as such, and offer a canonical way to do so.

[will move to extension repo later]

linked issues: 
- #1643
- https://github.com/ipython/ipykernel/issues/227

**Comment by vidartf** [comment]
I'm not sure if magics are the way to go (magics are not involved with the client at all). You could write a lab extension though that:
- Monitors creation of kernels by notebooks, and does an execution of code to inject `__file__` into the global namespace.
- Monitors renames of notebooks with open kernels to update `__file__` as needed (user code would need to be careful not to cache the value, or rely on it being constant throughout the execution).
- It should probably *not* try to set the `__file__` variable if the notebook connects to a pre-existing kernel (or, it should only do so if `__file__` isn't already defined).

Such an extension would not need to be included in lab core, but could be created and released independently. A similar extension could be written for classic notebook.

**Comment by scharf** [comment]
what's the status on this? Is it possible to somehow get the filename of the current notebook?

**Comment by jasongrout** [comment]
> what's the status on this?

I think there are no status updates - as far as I know, no one has contributed development towards this yet.



>  Is it possible to somehow get the filename of the current notebook?

Right now, I do not think it is possible to get a notebook file name in the kernel.

**Comment by shouldsee** [comment]
came from jupyter book... __file__ is lost when {code-cell} with :load:

**Comment by vidartf** [comment]
If you are using a recent version of jupyter_server, the notebook filename that the kernel session was started with should be available via the environment variable `JPY_SESSION_NAME`. See https://github.com/jupyter-server/jupyter_server/pull/679 for details.

**Comment by vidartf** [comment]
Actually, I realize that the jupyter_server PR has not been released yet. I'll have a look at backporting the changes to the 1.x branch.
