### ISSUE TITLE
This extension does not yet support the current version of JupyterLab.

### ISSUE THREAD

**Issue by mochp** [jupyterlab/jupyterlab#8017]
Extension Installation Error
An error occurred installing @telamonian/theme-darcula.

Error message:

This extension does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab Extension Package

=2.0.0 <2.1.0 >=1.1.3 <2.0.0 @jupyterlab/application
=2.0.0 <2.1.0 >=1.1.3 <2.0.0 @jupyterlab/apputils

**Comment by jasongrout** [comment]
Please file an issue with that extension's repo.

**Comment by jasongrout** [comment]
I think it is https://github.com/telamonian/theme-darcula
