### ISSUE TITLE
Cannot install any package due to corporate proxy

### ISSUE THREAD

**Issue by NeoXx123** [jupyterlab/jupyterlab#8018]
I'm behind a corporate proxy with Jupyter Lab installed within WSL.
I can't install any packages, any package I try to install I get the error message:

'ValueError: "@ijmbarr/jupyterlab_spellchecker" is not a valid npm package'

I figured its because of the proxy but I've tried a few things such as 
```
npm config set http-proxy=""
npm config set https-proxy=""
```

and none seem to work.

Any suggestions?
Thanks

**Comment by stefansimik** [comment]
This is expected, if your company blocks communication.
Ask you network admin, to allow communication to most used Python / Jupyter servers:

   *.pypi.org
   *.pythonhosted.org
   *.continuum.io
   * anaconda.com
   *.conda.io
   *.github.com
   *.githubusercontent.com
   *.npmjs.com
   *.yarnpkg.com

or set real proxy user, that is allowed to communicate via network with command like

   # Set proxy for NPM
   npm config set proxy http://USER:PWD@proxy.company.com:PORT
   npm config set proxy https://USER:PWD@proxy.company.com:PORT

   # Set registry (optional)
   npm config set registry http://registry.npmjs.org/

   # Do not require SSL - optional
   npm set strict-ssl False

**Comment by jasongrout** [comment]
@stefansimik - thanks for a comprehensive answer. Would you like to add some version of this to our FAQ or documentation somewhere?

**Comment by stefansimik** [comment]
Of course, I am open to do anything useful for Jupyterlab ;)

If you can give some quick guidance, where / how it would be most useful,
I can do it, or you can use anything from my post in docs / faq if you feel you can do it.

**Comment by jasongrout** [comment]
I could see something like the above as a troubleshooting section in the extension section of the documents: https://jupyterlab.readthedocs.io/en/stable/user/extensions.html. Source file is here: https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/extensions.rst

If you add it, can you also add some text to the parts about disabling ssl discouraging disabling ssl, and explaining that disabling ssl disables encryption, which is important?

**Comment by stefansimik** [comment]
Thank you Jason, I will do according to your instructions ;)

**Comment by stefansimik** [comment]
Hi Jason,
I checkout the repo, but see, the docs is in special tech format.
Is there any web tutorial focused on developers you could recommend to :
* learn basic technology of the docs framework used here
* how to build / export the docs, so I can test  / verify final result
so I can seriously extend the docs?

**Comment by jasongrout** [comment]
The docs are in [restructuredtext](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html), and we use [sphinx](https://www.sphinx-doc.org/en/master/) to turn them into html.

To build them, go into the docs directory, install the packages in [requirements.txt](https://github.com/jupyterlab/jupyterlab/blob/master/docs/requirements.txt), and then you can do `make html` to generate the html documentation.

**Comment by jasongrout** [comment]
Some conventions we have are at https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html

**Comment by stefansimik** [comment]
I am looking for the most intuitive place in docs,
where could be located hints about installation behind firewall.

What do you think about ?https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html

My hints will be mostly about installation (using pip/conda),
with focus on solving problems related to being behind firewall.
That's why I think the installation section is the most suitable.

I would add new section at the bottom of this page with header:
**Installation behind firewall**

**Comment by akitxu** [comment]
In my case I thought that the problem was because I was behind a corporate proxy, and finally I discovered that it was because I had not registered npm by doing

`npm config set registry http://registry.npmjs.org/

jlpm config set registry https://registry.yarnpkg.com/
`

**Comment by jasongrout** [comment]
Thanks for following up here!

With this, and the documentation note above that was contributed in #8034, I think we can close this issue as resolved.
