### ISSUE TITLE
Warning message when restarting Kernel

### ISSUE THREAD

**Issue by Juan-132** [jupyterlab/jupyterlab#8021]
Select 'Kernel'
Choose either:
- Restart Kernel ...
- Restart Kernel and Clear Outputs ...
- Restart Kernel and Run All Cells ...

Result:
![Capture](https://user-images.githubusercontent.com/59505296/76251812-fcb2d580-6247-11ea-8945-f7a9ba0600e3.PNG)

Expected result:
Do not show the warning message.

I find that restarting the Kernel (and rerunning all code), is a frequent action when working with a notebook. After iterating back and forth, you want to restart with a clean slate once in a while.

As it's a frequent and common action, it believe this does not really require a warning message.
Furthermore, restarting the Kernel is not a destructive action. All code is preserved, and can be recreated by a simple rerun.
There is also the 'checkpoints' feature, if you want to revisit older code and/or results.

Can this be disabled in settings? (i've not found any option so far)
How do others feel about disabling this message by default?

**Comment by jasongrout** [comment]
We've talked about following the common pattern of a checkbox that says "Don't show me this warning again" on such dialog boxes.

CC @tgeorgeux

**Comment by krassowski** [comment]
Of note, the dialogs now support chekboxes (https://jupyterlab.readthedocs.io/en/stable/extension/ui_helpers.html) and "Do not ask me again" is implemented for prompt for renaming file on save and closing files without saving:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/cd4dec68-4121-4860-b04c-9226eceeec43)

https://github.com/jupyterlab/jupyterlab/blob/82051a9d0c6dc93677b0b66560aea48d71aaa043/packages/docmanager-extension/src/index.tsx#L905-L942

https://github.com/jupyterlab/jupyterlab/blob/82051a9d0c6dc93677b0b66560aea48d71aaa043/packages/docmanager/src/widgetmanager.ts#L414-L435

And kernel selection dialog has "Always start the preferred kernel":

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/f0c63ccb-1add-4e3c-b325-f626caa25cd1)

https://github.com/jupyterlab/jupyterlab/blob/82051a9d0c6dc93677b0b66560aea48d71aaa043/packages/apputils/src/sessioncontext.tsx#L1350-L1378
