### ISSUE TITLE
Spaces are too small

### ISSUE THREAD

**Issue by mochp** [jupyterlab/jupyterlab#8022]
![微信图片_20200310180159](https://user-images.githubusercontent.com/25894526/76301735-b918a400-62f9-11ea-83fe-f76ea5c7c9fc.png)

- Operating System and version:
   ubuntu19
- Browser and version:
  chrome
- JupyterLab version:
   2.01

**Comment by jasongrout** [comment]
What spaces are you seeing as too small? I don't see any spaces in your screenshot.

**Comment by mochp** [comment]
this is jupyter notebook,This looks pretty good。
![微信图片_20200311185554](https://user-images.githubusercontent.com/25894526/76410547-0c0e5c00-63cb-11ea-9e65-51d3c2d79dcd.png)


jupyterlab : Space between spaces looks too small

**Comment by jasongrout** [comment]
It looks like you are talking about the spaces in the editor, then? It seems that your editor font is proportional. That is not the normal default setup usually for JupyterLab, so something in your configuration is causing it to use a different font than normal.

Here is what it looks like for me in the default JupyterLab 2.0.1, current firefox on macos:
<img width="287" alt="Screen Shot 2020-03-11 at 4 40 35 AM" src="https://user-images.githubusercontent.com/192614/76413396-94044f80-6352-11ea-8510-fbdb875a7e5a.png">

In your JLab advanced settings, do you have anything under the notebook component changing the font family for code cells?

Can you reproduce this in a clean new environment with no browser plugins? See the diagnosis guidelines at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html
