### ISSUE TITLE
Documentation: MIME type for Vega Lite outdated

### ISSUE THREAD

**Issue by vogelsgesang** [jupyterlab/jupyterlab#8026]
## Description

The documentation under https://github.com/jupyterlab/jupyterlab/blob/33d3d9af0e91f25d40fa3232c86ff54aa8f4dfcf/docs/source/user/file_formats.rst documents the MIME type as `application/vnd.vegalite.v1+json`. However, the correct MIME type seems to be `application/vnd.vegalite.v3+json`

## Reproduce

1. Output a response with MIME type `application/vnd.vegalite.v1+json` 
2. See that you see nothing. JupyterLab does not render it.

**Comment by jasongrout** [comment]
Thank you. We have indeed upgraded our version of vega-lite. Do you want to submit a PR fixing that in the documentation? The file to change is here: 

https://github.com/jupyterlab/jupyterlab/blame/83d83880d8d8ea86c1dc8a41dd951bac08e29393/docs/source/user/file_formats.rst#L222

In fact, the paragraphs below it should be updated too. We currently ship renderers for: https://github.com/jupyterlab/jupyterlab/blob/83d83880d8d8ea86c1dc8a41dd951bac08e29393/packages/vega5-extension/package.json#L40-L42
