### ISSUE TITLE
Design button styles for JupyterLab

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#804]
We have buttons, but no consistent styling approach for them. This PR is for tracking the design of our buttons. We will likely need different types:
- Icon only
- Text only
- Icon+text
- Dropdown button
- Flat
- Raised

**Comment by ellisonbg** [comment]
We probably also need to cover:

* Different button sizes and their font sizes

**Comment by ellisonbg** [comment]
@faricacarroll Any update on this one?

**Comment by faricacarroll** [comment]
I've started mocking up the different styled buttons.

Here is a sketch cloud link to look at what I've mocked up so far:
https://share.sketch.cloud/0pvG

**Comment by ellisonbg** [comment]
Closing in favor of #2880
