### ISSUE TITLE
Docs cleanup - 3 empty pages at the end

### ISSUE THREAD

**Issue by stefansimik** [jupyterlab/jupyterlab#8040]
## Description

Hi, 
latest docs contain 3 links, leading to **empty** (and probably useless) pages.
Is there any value or should we remove and stop generation of these 3 links?
See image below.

![2020-03-13_001136](https://user-images.githubusercontent.com/6208056/76575641-152d2500-64c0-11ea-945b-c319d504c82b.png)

**Comment by jasongrout** [comment]
I think you're right that we can just delete theme from the bottom of https://raw.githubusercontent.com/jupyterlab/jupyterlab/5d257432cd4e585bfd6556b0564843d0010373a0/docs/source/index.rst

**Comment by stefansimik** [comment]
Pull request ready:
https://github.com/jupyterlab/jupyterlab/pull/8058
