### ISSUE TITLE
LaTeX; export as pdf fails due to incorrect parsing of tex.

### ISSUE THREAD

**Issue by suntzuisafterU** [jupyterlab/jupyterlab#8046]
## Description

When exporting a notebook that contained latex in markdown cells as a pdf I ran into the following errors:
```
nbconvert failed: PDF creating failed, captured latex output:
Failed to run "xelatex .\notebook.tex -quiet" command:
notebook.tex:414: Missing $ inserted
notebook.tex:416: 
notebook.tex:417: 
notebook.tex:417: 
notebook.tex:419: 
notebook.tex:419: 
notebook.tex:419: 
notebook.tex:419: Missing 
notebook.tex:502: Missing $ inserted
notebook.tex:503: Missing $ inserted
notebook.tex:514: Missing $ inserted
notebook.tex:518: Missing $ inserted
notebook.tex:539: Missing $ inserted
notebook.tex:540: 
notebook.tex:540: 
notebook.tex:540: 
notebook.tex:540: Missing 
notebook.tex:544: Missing $ inserted
notebook.tex:551: Missing $ inserted
notebook.tex:554: Missing $ inserted
notebook.tex:557: Missing $ inserted
notebook.tex:612: Missing $ inserted
notebook.tex:612: 
notebook.tex:712: Missing $ inserted
notebook.tex:713: 
notebook.tex:713: 
notebook.tex:713: 
notebook.tex:713: Missing 
```

Which showed up in the new tab that was launched to create the pdf.

I proceeded to export as LaTeX to see what was going on.
Here is one example from the tex document:
```tex
\$ P(F=0 \mid S=0) = \frac{P(S=0|F=0)P(F=0)}{P(S=0)} \$
```
The exporter appears to be escaping $ signs, which disables the math environment.
Then the \mid and \frac commands do not work.

## Reproduce

1. Go to file menu
2. Click on export as pdf
3. Open the new tab launched to create the pdf

Sorry for the poor reproduction instructions.  The document I am trying to export is an assignment
for a University course, so I can not post it in it's entirety here, and in any case I do not know the exact subset of latex commands that are effected.

## Expected behavior

Exported pdf, since the LaTeX compiles when the notebook is rendered.

## Context

- Operating System and version: Windows 10, Home
- Browser and version: Firefox; 74.0
- JupyterLab version: 1.2.6

<details><summary>Troubleshoot Output</summary>
<pre>

Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>

Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>

Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by rosgori** [comment]
You should upgrade `Jupyter Lab`, a program called [`pandoc`](https://pandoc.org/) and `nbconvert`. Try again. If that doesn't work, try to convert to `latex` and then to `pdf`. If that doesn't work, try with `pandoc` (although `nbconvert` uses `pandoc` internally). If that doesn't work... I don't know any other option in your case.

**Comment by jasongrout** [comment]
> Sorry for the poor reproduction instructions. The document I am trying to export is an assignment
> for a University course, so I can not post it in it's entirety here, and in any case I do not know the exact subset of latex commands that are effected.

Can you create a minimal example that exhibits the problem?
