### ISSUE TITLE
Using vim shortcuts when opening vim in terminal

### ISSUE THREAD

**Issue by chuaxr** [jupyterlab/jupyterlab#8047]
I've experienced certain cases where the usual vim shortcuts don't work in the jupyterlab terminal and are instead replaced by the browser/OS shortcuts:

1. I try to use Ctrl-V to enter vim mode, but end up pasting a block of text instead.
(Happens both on Microsoft Edge and Firefox)
2. I try to navigate between split windows with Ctrl-W, but end up closing the browser window. 
(Happens in Firefox, not Microsoft Edge)

Any workaround/fixes would be greatly appreciated.

**Comment by jasongrout** [comment]
I'm not sure we are able to override Ctrl-W in Firefox (I do notice a google search turning up http://shallowsky.com/blog/tech/web/firefox-quantum-fixing-ctrl-w.html)

We've had a lot of discussion about Ctrl-V and pasting: https://github.com/jupyterlab/jupyterlab/issues/1146 and https://github.com/jupyterlab/jupyterlab/pull/6391

**Comment by chuaxr** [comment]
Thanks for the reply, a workaround I'm trying is to remap other keys for my desired functionality (e.g. 
 [https://vi.stackexchange.com/questions/3728/how-can-i-work-with-splits-in-vim-without-ctrl-w](url)).

I also realized that v (as opposed to Ctrl-V) suffices to enter visual mode.
