### ISSUE TITLE
Where did the caret icons go?

### ISSUE THREAD

**Issue by aquirdTurtle** [jupyterlab/jupyterlab#8048]
I was using a couple of the caret icons in my "Collapsible Headers" extension. e.g. `button.style.background = "var(--jp-icon-caretright) no-repeat center";`. I believe this was drawing from jupyterlab/packages/theme-light-extension/style/images/. But these seem to have been removed for some reason in Jupyterlab 2.0, breaking the extension. Obviously I can add the files back in my own extension, but it seemed nice to reference the "official" icons for styling purposes. Is there some desired change I should make other than just adding the files back into my extension?

**Comment by jasongrout** [comment]
CC @telamonian

**Comment by telamonian** [comment]
`var(--jp-icon-caret-right)`. See https://github.com/jupyterlab/jupyterlab/blob/master/packages/ui-components/style/deprecated.css for the full list of icons available for use as CSS background images

**Comment by vidartf** [comment]
For clarity: the (deprecated) CSS caret icons got an accidental rename in 2.0 (dash added).

**Comment by jasongrout** [comment]
> For clarity: the (deprecated) CSS caret icons got an accidental rename in 2.0 (dash added).

If it was accidental - is this something we'd like to fix to ease transition? Especially if it is deprecated - the point of deprecation is to provide an easy transition so your old things keep working in the near future.

@telamonian, thoughts?
