### ISSUE TITLE
find in files feature

### ISSUE THREAD

**Issue by amitkle** [jupyterlab/jupyterlab#8051]
Hey,
Are you working on a feature like "find in files" of pycharm/notepad++ (ctrl+shift+f)?
We could really use something like that.
If not, I'm thinking of creating one of my own and wanted to know what you think about it.
I was thinking to add this to the normal find extension. Something like a checkbox of "search in files"
thanks!

**Comment by jasongrout** [comment]
I don't know of anyone working on it right now.

**Comment by jasongrout** [comment]
>  I was thinking to add this to the normal find extension. Something like a checkbox of "search in files"

I was thinking it would be a separate panel, like vs code or sublime, and leave the current find as a current document search.

**Comment by jasongrout** [comment]
>  If not, I'm thinking of creating one of my own and wanted to know what you think about it.

That would be great if you wanted to work on this!

**Comment by jasongrout** [comment]
This issue is being tracked at #1145. Let's move discussion there.
