### ISSUE TITLE
Where did execution timings go? (Jupyterlab 2.0)

### ISSUE THREAD

**Issue by aquirdTurtle** [jupyterlab/jupyterlab#8054]
Hello, I noticed a while ago when [this](https://github.com/jupyterlab/jupyterlab/pull/6864) PR was merged. In jupyterlab version 1.2.6 I can make use of this. But now, in Jupyterlab 2.0, I no longer see the `Toggle Recording Cell Timing` command, and adding the `"record_timing": true` metadata to the notebook metadata manually doesn't seem to work either. Where did it go? I was just about to implement an extension like the old notebook extension using this.

**Comment by jasongrout** [comment]
Look in the Advanced Settings for notebooks - we made it a system-wide setting, rather than a setting in specific notebooks. See the changelog at https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v2-0-0, in particular: 

> Notebook recordTiming advanced setting to control whether execution timing information is stored in notebook files (#7578)

**Comment by aquirdTurtle** [comment]
Great, thanks.

**Comment by mlucool** [comment]
@aquirdTurtle I actually already wrote a plugin that does this. Let me see if I can get it in shape to share. Would you mind holding off a week or so?

**Comment by aquirdTurtle** [comment]
@mlucool Ah, this type of thing seems to happen all the time with jupyterlab extensions. Unfortunately I've already put in a good chunk of work - if it weren't for [this](https://github.com/jupyterlab/jupyterlab/issues/8056) issue I ran into in Jupyterlab 2.0 I'd have an early version already ready to publish. But quite possibly your version would be far superior - I'm a very inexperienced with javascript and these things. I think it makes sense for - once this issue gets resolved - to go ahead and publish my work so far, but if your plugin is superior I'm happy to defer to that once it's out. Does that sound good?

**Comment by mlucool** [comment]
@aquirdTurtle check out https://www.npmjs.com/package/jupyterlab-execute-time
