### ISSUE TITLE
How to internationalize

### ISSUE THREAD

**Issue by WangChangsongGit** [jupyterlab/jupyterlab#8061]
I want to internationalize Jupyterlab's menus and other contents, but I don't see the introduction of an internationalization framework in Jupyterlab. How can I complete the internationalization without intruding into the Jupyterlab source code?

**Comment by vidartf** [comment]
Unfortunately, there is no internationalization frameworks used in lab :( While the classic notebook uses [Jed](https://messageformat.github.io/Jed/) for the client side, I think we might want to go for something more flexible? E.g. https://www.i18next.com. Thoughts?

For the server side messages (in console and sent to the client) we can probably reuse what is done by notebook (/ jupyter-server).

**Comment by jasongrout** [comment]
Let's move this conversation over to #3965 to keep it in one place. Thanks!
