### ISSUE TITLE
Pasting image from system to markdown cell either doesn't render image or adds extra text

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab#8062]
## Description
There are two seemingly related issues here. 
1. When I paste an image that I copied from the file browser the image is not embedded:
**Expected**: `![image.png](attachment:image.png)`
**Actual**: 
```
x-special/nautilus-clipboard
copy
file:///home/ian/Pictures/2020-03-20_11-21.png
```
2. When I copy an image by right clicking on the image in the system image viewer it pastes extra text into the markdown cell
**Expected** : `![image.png](attachment:image.png)`
**Actual**: `file:///home/ian/Pictures/2020-03-20_11-21.png![image.png](attachment:image.png)`

This diverges with the behavior of drag and drop or copying an image from google images. See below screencast:
![prevent_default](https://user-images.githubusercontent.com/10111092/77183272-78ace900-6aa4-11ea-9be1-ee44259d102a.gif)

## Potential root cause
This functionality was added in https://github.com/jupyterlab/jupyterlab/pull/5913, so maybe @Madhu94 is the best person to comment on this. With some digging I suspect that the cause is that the `preventDefault` method in [this line](https://github.com/jupyterlab/jupyterlab/blob/master/packages/cells/src/widget.ts#L1228) is not behaving as expected.
## Reproduce

1. open markdown cell in notebook
2. copy file from system file browser
3. paste into markdown cell

## Context

- Operating System and version: popOS 19.10 (essentially ubuntu 19.10(
- Browser and version: both Firfox 74 and Chrome 80
- JupyterLab version: both 1.26 and 2.0.1

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/ian/anaconda3/envs/jlab-test/bin
	/home/ian/anaconda3/condabin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/home/ian/opt
	/home/ian/bin

sys.path:
	/home/ian/anaconda3/envs/jlab-test/bin
	/home/ian/anaconda3/envs/jlab-test/lib/python38.zip
	/home/ian/anaconda3/envs/jlab-test/lib/python3.8
	/home/ian/anaconda3/envs/jlab-test/lib/python3.8/lib-dynload
	/home/ian/anaconda3/envs/jlab-test/lib/python3.8/site-packages

sys.executable:
	/home/ian/anaconda3/envs/jlab-test/bin/python

sys.version:
	3.8.2 | packaged by conda-forge | (default, Mar  5 2020, 17:11:00) 
	[GCC 7.3.0]

platform.platform():
	Linux-5.3.0-7642-generic-x86_64-with-glibc2.10

which -a jupyter:
	/home/ian/anaconda3/envs/jlab-test/bin/jupyter

pip list:
	Package            Version            
	------------------ -------------------
	attrs              19.3.0             
	backcall           0.1.0              
	bleach             3.1.3              
	certifi            2019.11.28         
	decorator          4.4.2              
	defusedxml         0.6.0              
	entrypoints        0.3                
	importlib-metadata 1.5.0              
	ipykernel          5.1.4              
	ipython            7.13.0             
	ipython-genutils   0.2.0              
	jedi               0.16.0             
	Jinja2             2.11.1             
	json5              0.9.0              
	jsonschema         3.2.0              
	jupyter-client     6.1.0              
	jupyter-core       4.6.3              
	jupyterlab         2.0.1              
	jupyterlab-server  1.0.7              
	MarkupSafe         1.1.1              
	mistune            0.8.4              
	nbconvert          5.6.1              
	nbformat           5.0.4              
	notebook           6.0.3              
	pandocfilters      1.4.2              
	parso              0.6.2              
	pexpect            4.8.0              
	pickleshare        0.7.5              
	pip                20.0.2             
	prometheus-client  0.7.1              
	prompt-toolkit     3.0.4              
	ptyprocess         0.6.0              
	Pygments           2.6.1              
	pyrsistent         0.15.7             
	python-dateutil    2.8.1              
	pyzmq              19.0.0             
	Send2Trash         1.5.0              
	setuptools         46.0.0.post20200311
	six                1.14.0             
	terminado          0.8.3              
	testpath           0.4.4              
	tornado            6.0.4              
	traitlets          4.3.3              
	wcwidth            0.1.8              
	webencodings       0.5.1              
	wheel              0.34.2             
	zipp               3.1.0

conda list:
	# packages in environment at /home/ian/anaconda3/envs/jlab-test:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                 conda_forge    conda-forge
	_openmp_mutex             4.5                       0_gnu    conda-forge
	attrs                     19.3.0                     py_0    conda-forge
	backcall                  0.1.0                      py_0    conda-forge
	bleach                    3.1.3              pyh8c360ce_0    conda-forge
	ca-certificates           2019.11.28           hecc5488_0    conda-forge
	certifi                   2019.11.28       py38h32f6830_1    conda-forge
	decorator                 4.4.2                      py_0    conda-forge
	defusedxml                0.6.0                      py_0    conda-forge
	entrypoints               0.3             py38h32f6830_1001    conda-forge
	importlib-metadata        1.5.0            py38h32f6830_1    conda-forge
	importlib_metadata        1.5.0                         1    conda-forge
	ipykernel                 5.1.4            py38h5ca1d4c_0    conda-forge
	ipython                   7.13.0           py38h23f93f0_1    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	jedi                      0.16.0           py38h32f6830_1    conda-forge
	jinja2                    2.11.1                     py_0    conda-forge
	json5                     0.9.0                      py_0    conda-forge
	jsonschema                3.2.0            py38h32f6830_1    conda-forge
	jupyter_client            6.1.0                      py_0    conda-forge
	jupyter_core              4.6.3            py38h32f6830_1    conda-forge
	jupyterlab                2.0.1                      py_0    conda-forge
	jupyterlab_server         1.0.7                      py_0    conda-forge
	ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
	libffi                    3.2.1             he1b5a44_1007    conda-forge
	libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
	libgomp                   9.2.0                h24d8f2e_2    conda-forge
	libsodium                 1.0.17               h516909a_0    conda-forge
	libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
	markupsafe                1.1.1            py38h1e0a361_1    conda-forge
	mistune                   0.8.4           py38h516909a_1000    conda-forge
	nbconvert                 5.6.1                    py38_0    conda-forge
	nbformat                  5.0.4                      py_0    conda-forge
	ncurses                   6.1               hf484d3e_1002    conda-forge
	notebook                  6.0.3                    py38_0    conda-forge
	openssl                   1.1.1e               h516909a_0    conda-forge
	pandoc                    2.9.2                         0    conda-forge
	pandocfilters             1.4.2                      py_1    conda-forge
	parso                     0.6.2                      py_0    conda-forge
	pexpect                   4.8.0            py38h32f6830_1    conda-forge
	pickleshare               0.7.5           py38h32f6830_1001    conda-forge
	pip                       20.0.2                     py_2    conda-forge
	prometheus_client         0.7.1                      py_0    conda-forge
	prompt-toolkit            3.0.4                      py_0    conda-forge
	ptyprocess                0.6.0                   py_1001    conda-forge
	pygments                  2.6.1                      py_0    conda-forge
	pyrsistent                0.15.7           py38h1e0a361_1    conda-forge
	python                    3.8.2           h9d8adfe_4_cpython    conda-forge
	python-dateutil           2.8.1                      py_0    conda-forge
	python_abi                3.8                      1_cp38    conda-forge
	pyzmq                     19.0.0           py38ha71036d_1    conda-forge
	readline                  8.0                  hf8c457e_0    conda-forge
	send2trash                1.5.0                      py_0    conda-forge
	setuptools                46.0.0           py38h32f6830_2    conda-forge
	six                       1.14.0                     py_1    conda-forge
	sqlite                    3.30.1               hcee41ef_0    conda-forge
	terminado                 0.8.3            py38h32f6830_1    conda-forge
	testpath                  0.4.4                      py_0    conda-forge
	tk                        8.6.10               hed695b0_0    conda-forge
	tornado                   6.0.4            py38h1e0a361_1    conda-forge
	traitlets                 4.3.3            py38h32f6830_1    conda-forge
	wcwidth                   0.1.8                      py_0    conda-forge
	webencodings              0.5.1                      py_1    conda-forge
	wheel                     0.34.2                     py_1    conda-forge
	xz                        5.2.4             h14c3975_1001    conda-forge
	zeromq                    4.3.2                he1b5a44_2    conda-forge
	zipp                      3.1.0                      py_0    conda-forge
	zlib                      1.2.11            h516909a_1006    conda-forge

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 11:53:18.558 LabApp] Kernel started: f33ff76a-6ef5-42bf-87eb-6c75836f63b4
[I 11:53:21.002 LabApp] Creating new notebook in /Documents
[I 11:53:21.272 LabApp] Kernel started: 1d13463a-7d25-4050-bbb5-f2cede8e3aa6
[I 11:55:16.537 LabApp] Saving file at /Documents/Untitled.ipynb
[I 11:55:21.683 LabApp] Saving file at /Documents/Untitled1.ipynb

</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
no output
</pre>
</details>

**Comment by jasongrout** [comment]
For me on macOS 10.14 and Firefox, I get:

* Drag and drop from Finder
  * If the image has a space in its filename, I get the text `![image with space.png](attachment:image with space.png)`, but rendering the markdown cell does *not* show the image, just this text
  * If the image does not have a space in its filename, I get the text `![image.png](attachment:image.png)` and rendering does show the image.
* Copy from Finder: Inserts the extra text you were seeing in your issue 2.

I think the issue with spaces is probably a separate issue than what we are seeing here.

> With some digging I suspect that the cause is that the `preventDefault` method in [this line](https://github.com/jupyterlab/jupyterlab/blob/master/packages/cells/src/widget.ts#L1228) is not behaving as expected.

Or perhaps we should also stop propagation if any files were actually attached?

**Comment by ianhi** [comment]
### spaces in names  
I have the same issue when there are spaces in the name. However, when I copy from the image viewer names with spaces do end up being rendered. I think this is because the spaces are replaced with `%20` by my image viewer. 
Results in this: `file:///home/ian/Pictures/name%20with%20space.png![image.png](attachment:image.png)` which does render the image.


### extra text  
1. I tried adding `event.stopPropagation()` to `_evtPaste` and this didn't help.

2. Are the `lm-dragover` and `lm-drop` lumino events? Because those seem to work correctly, perhaps lumino is doing something with paste events?

3. Are the notebook cells implemented using codemirror? I.e. they might also be affected by code in the codeeditor widget? Maybe [these lines]( https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/src/editor.ts#L166-L169) in the codemirror src are doing something weird with paste:
```typescript
    // Manually refresh on paste to make sure editor is properly sized.
    editor.getWrapperElement().addEventListener('paste', () => {
      if (this.hasFocus()) {
        this.refresh();
```
(I originally came across this issue when trying to add image pasting to the markdown files in the fileeditor)

4. Changing the function to look at the clipboard data like so:
```javascript
  private _evtPaste(event: ClipboardEvent): void {
    if (event.clipboardData) {
      for (let i=0; i<event.clipboardData.items.length; i++){
        console.log(event.clipboardData.items[i].getAsString(function (s){
          console.log(i);
          console.log(s);
        }));
        console.log(event.clipboardData.items[i].type);
      }
      this._attachFiles(event.clipboardData.items);
    }
    event.stopPropagation();
    event.preventDefault();
```
you can see that there are two different mimetypes items for each paste:
```
text/plain
image/png
```
However when pasting from google images: the types are
```
text/html
image/png
```

I think that the reason copying from google images seems to work is that whatever the first item ends up being an `<img>` tag which gets removed at some point during the paste, while for copying from the file system it's just the path which then makes it to the text. I see this behavior in a text editor as well. Pasting an image from the file system results in just the path showing up, while pasting from google images doesn't result in anything.

**Comment by jasongrout** [comment]
>     2\. Are the `lm-dragover` and `lm-drop` lumino events?

Yes, and those are completely separate from the browser drag/drop events.



>  3\. Are the notebook cells implemented using codemirror?

Yes

I'm wondering if that extra text before the image is being added *before* this handler is called (which is why it would show up first), so the stop propagation wouldn't fix it. Can you log the contents of the cell when we hit this handler to see if something has added the text already? Or even better, you can put a breakpoint on the paste event to trace through exactly everything that is happening.

**Comment by ianhi** [comment]
You're right, the extra text is being added before the handler is called.
I added a firefox debugger breakpoint on clipboard events which immediately brings us to [these](https://github.com/codemirror/CodeMirror/blob/master/src/input/TextareaInput.js#L48-L49) lines in the code mirror source:
```javascript
    on(te, "paste", e => {
      if (signalDOMEvent(cm, e) || handlePaste(e, cm)) return

      cm.state.pasteIncoming = +new Date
      input.fastPoll()
    })
```
The text appears during the `handlePaste` call.  I dug deeper into that function but I'm sure how useful any of it was, just leading deeper and deeper into the codemirror source. I'm happy to think more about this, but have to admit that I'm pretty out my depth here (never used javascript before), so suggestions about what to look into would be really helpful.

One way to deal with this is to have the eventHandler in jupyterlab delete the extra text that gets put there. Though this seems pretty hacky.

**Comment by jasongrout** [comment]
> I'm happy to think more about this, but have to admit that I'm pretty out my depth here (never used javascript before), so suggestions about what to look into would be really helpful.

I'm impressed! You seem comfortable and competent with these tools.

**Comment by jasongrout** [comment]
> One way to deal with this is to have the eventHandler in jupyterlab delete the extra text that gets put there. Though this seems pretty hacky.

Though the nice thing is that we do have exactly the data that was pasted in:

> let pasted = e.clipboardData && e.clipboardData.getData("Text")

So presumably we could easily find that data right at the cursor position, delete it, and add our own.

**Comment by jasongrout** [comment]
Even better, it appears that codemirror fires a paste event: https://codemirror.net/doc/manual.html#event_dom

It looks like you can give the event a property to have codemirror ignore it.

**Comment by ianhi** [comment]
Thanks :). Mostly, I just really like using jupyter, so I'm motivated.

I figured out a partial fix, I think with some work it could be solution though that will require more work. The codeeditor widget as an event listener for paste added [here](https://github.com/jupyterlab/jupyterlab/blob/22bc5448518337fe16eda7cb5338d2dd49bdadd1/packages/codemirror/src/editor.ts#L167-L171):
```javascript
    editor.getWrapperElement().addEventListener('paste', () => {
      if (this.hasFocus()) {
        this.refresh();
      }
    });
```
if we change this to:
```javascript
    editor.getWrapperElement().addEventListener('paste', (event) => {
      event.preventDefault()
      if (this.hasFocus()) {
        this.refresh();
      }
    }, true);
```
then this listener is called prior to the codemirror listener, and the `preventDefault` call stops the extra text from appearing, giving the expected behavior for pasting images. Unfortunately this also breaks normal text pasting. Perhaps we could add some logic that only calls prevent default when file objects are present in the clipboard data? Is there a list of all mimetypes that should be handled specially, vs letting codemirror do its default action?

**Comment by jasongrout** [comment]
Or since we've abstracted codemirror out, so the cell doesn't know it is dealing with codemirror, perhaps in the codemirror editor.ts file, we hook into the paste event and turn it off *always*, and then just handle the paste event from JupyterLab code, pasting text or files or whatever we want.

**Comment by jasongrout** [comment]
> if we change this to:

Right, this is trapping the event in the capture phase, but I think that should probably be a last resort. I think it's probably just cleaner to turn it off in codemirror always, since the codemirror default action is really very simple, and just implement it ourselves. Another option is to make this part of the abstract editor interface, so that it is exposed to user code.

**Comment by jasongrout** [comment]
For example, this turns off codemirror paste handling:

```diff
diff --git a/packages/codemirror/src/editor.ts b/packages/codemirror/src/editor.ts
index 05e8d7626..874101e8c 100644
--- a/packages/codemirror/src/editor.ts
+++ b/packages/codemirror/src/editor.ts
@@ -163,6 +163,12 @@ export class CodeMirrorEditor implements CodeEditor.IEditor {
       this._lastChange = change;
     });
 
+    // Turn off paste handling in codemirror since sometimes we want to
+    // replace it with our own.
+    editor.on('paste', (instance: CodeMirror.Editor, event: any) => {
+      event.codemirrorIgnore = true;
+    });
+
     // Manually refresh on paste to make sure editor is properly sized.
     editor.getWrapperElement().addEventListener('paste', () => {
       if (this.hasFocus()) {
```

**Comment by jasongrout** [comment]
Perhaps the editor config at https://github.com/jupyterlab/jupyterlab/blob/22bc5448518337fe16eda7cb5338d2dd49bdadd1/packages/codeeditor/src/editor.ts#L579 can be modified to have a new flag for whether the editor should handle paste events. Then the codemirror editor can look at the value of that flag and decide whether to disable codemirror handling or not dynamically. Then most editors would use the default value of having the editor handle the pasting, but markdown editors could disable the editor's paste handling and do it all by themselves.

**Comment by ianhi** [comment]
That's a good solution. Perhaps the insertion of normal text should be done using the `insertText` function that is being implemented in: https://github.com/jupyterlab/jupyterlab/pull/7908


Aside:
> Right, this is trapping the event in the capture phase, but I think that should probably be a last resort.

Can you explain why this should be a last resort?

**Comment by jasongrout** [comment]
> can be modified to have a new flag for whether the editor should handle paste events.

Something like this:

```diff
diff --git a/packages/codeeditor/src/editor.ts b/packages/codeeditor/src/editor.ts
index a7eaed221..11f1d63af 100644
--- a/packages/codeeditor/src/editor.ts
+++ b/packages/codeeditor/src/editor.ts
@@ -631,6 +631,11 @@ export namespace CodeEditor {
      */
     autoClosingBrackets: boolean;
 
+    /**
+     * Whether the editor should handle paste events.
+     */
+    handlePaste: boolean;
+
     /**
      * The column where to break text line.
      */
@@ -662,6 +667,7 @@ export namespace CodeEditor {
     insertSpaces: true,
     matchBrackets: true,
     autoClosingBrackets: true,
+    handlePaste: true,
     rulers: [],
     codeFolding: false
   };
diff --git a/packages/codemirror/src/editor.ts b/packages/codemirror/src/editor.ts
index 05e8d7626..78e57d54c 100644
--- a/packages/codemirror/src/editor.ts
+++ b/packages/codemirror/src/editor.ts
@@ -163,6 +163,14 @@ export class CodeMirrorEditor implements CodeEditor.IEditor {
       this._lastChange = change;
     });
 
+    // Turn off paste handling in codemirror since sometimes we want to
+    // replace it with our own.
+    editor.on('paste', (instance: CodeMirror.Editor, event: any) => {
+      if (!this._config['handlePaste']) {
+        event.codemirrorIgnore = true;
+      }
+    });
+
     // Manually refresh on paste to make sure editor is properly sized.
     editor.getWrapperElement().addEventListener('paste', () => {
       if (this.hasFocus()) {
```

**Comment by jasongrout** [comment]
> Can you explain why this should be a last resort?

In general, handling events in the capturing phase messes up the usual bubbling semantics, so we try to be really careful about how we use it. It definitely does the trick in here by getting to that event before codemirror, but is sort of a hack in that way. And in this case, I think it's a bad idea because this would encode in the editor component some hardcoded criteria for when the paste event would be allowed or not allowed, and I don't think that's the place for a decision like this - that should be a decision for the thing that is using the editor component.

Codemirror has a documented method for telling it to not handle the event with its own paste event, and it doesn't have other side effects like preventDefault does. Of course, we could also set the codemirrorIgnore attribute from the capture phase in the event, but it seems more, I don't know, "official" to do it using the codemirror paste event.

**Comment by ianhi** [comment]
A few thoughts about the images with spaces in the name. This seems to have been discussed somewhat extensively in https://github.com/jupyterlab/jupyterlab/issues/5153 and related issues. My understanding of the upshot is that spaces in a markdown link is not part of the markdown spec. That said it seems that images with spaces in the name ought to be allowed. This would be my expectation as a user, and when it doesn't render my first instinct would not be to change the spaces to `%20`.

I have two partial solutions for images containing names with spaces:

### 1.
For dragging and dropping the `attachFile` method can be changed to change the underlying URL like this:

```diff
diff --git a/packages/cells/src/widget.ts b/packages/cells/src/widget.ts
index facce4ae2..97fb318c6 100644
--- a/packages/cells/src/widget.ts
+++ b/packages/cells/src/widget.ts
@@ -1325,8 +1325,9 @@ export abstract class AttachmentsCell extends Cell {
       const mimeType = matches[1];
       const encodedData = matches[3];
       const bundle: nbformat.IMimeBundle = { [mimeType]: encodedData };
-      this.model.attachments.set(blob.name, bundle);
-      this.updateCellSourceWithAttachment(blob.name);
+      const name = encodeURI(blob.name)
+      this.model.attachments.set(name, bundle);
+      this.updateCellSourceWithAttachment(name);
     };
     reader.onerror = evt => {
       console.error(`Failed to attach ${blob.name}` + evt);
```
this fixes drag and drop behavior for an image with spaces in the name. It does not fix the not rendering if someone types in a path to an image file (i.e. `![image](image with space.png)`). The issue here is that marked doesn't convert that to an HTML `img` tag as it is not a valid URl. This can fixed as well by adding the below to the `renderMarkdown` method.

### 2.
This fixes both user input markdown images with spaces in the name as well as for drag and drop 
```diff
diff --git a/packages/rendermime/src/renderers.ts b/packages/rendermime/src/renderers.ts
index 6b11c712f..0ebe47fce 100644
--- a/packages/rendermime/src/renderers.ts
+++ b/packages/rendermime/src/renderers.ts
@@ -329,6 +329,12 @@ export async function renderMarkdown(
   // Separate math from normal markdown text.
   let parts = removeMath(source);
 
+  // Replace spaces in image names
+  function spaceReplacer(match:string, p1:string, p2:string) {
+     return [p1, encodeURI(p2), ')'].join('')
+    }
+  parts['text'] = parts['text'].replace(/(!\[.+\]\((?:attachment:)?)(.+)\)/g, spaceReplacer);
+
   // Convert the markdown to HTML.
   let html = await Private.renderMarked(parts['text']);
```
The caveat is that this solution will also replaces spaces in a markdown image embed inside a code block. That is:
````
```
!(image)(image with spaces.png)
```
````
will render as:
```
!(image)(image%20with%20spaces.png)
```

I would still vote for the second solution being implemented as I think the misrendering of spaces in markdown image embed statement within code blocks is a small price to pay. Though that could likely be worked around by detecting when in a code block, but I couldn't figure out a clean way to do this without lookbehinds that don't seem to be well supported by browsers.

**Comment by jasongrout** [comment]
> That said it seems that images with spaces in the name ought to be allowed.

I think we should not deviate from the markdown (commonmark) spec. That would mean every frontend displaying notebooks would have to also support this nonstandard parsing of our "markdown".

I think your first option, making sure we are inserting correct markdown links, is the right one.

**Comment by jasongrout** [comment]
@ianhi - since you already have a diff, do you want to put in a PR?

**Comment by ianhi** [comment]
Happily. I didn't because I thought it might be better do include that along the other changes fixing image embedding discussed above. Is it better to keep things more granular? If so, I'll make one now.

**Comment by ianhi** [comment]
w.r.t the original issue it is indeed pretty easy to recreate the default paste behavior using the soon to be added `replaceSelection` method but there two things I'd like input on:

1. Should markdown cells allow the pasting of rich text like HTML? They currently do not,  but seeing as they render html it seems to me that they ought to be able to accept pasted html.
     - You can paste text with html in it, but if you copy something from a website with links in it for example then the links won't show up. 
     - as and example: <a href='https://github.com/jupyterlab/jupyterlab/issues/8062'>try pasting this</a>
2. Is it ok to throw away all the text items in clipboardData if there are also files in the clipboardData?
     - Alternatively, we can check if a text item is followed by a File item, and in that case ignore it. My only worry is that this could be problematic when somehow copying a combination of files and unrelated text, though I'm not actually sure how one would achieve that.

**Comment by jasongrout** [comment]
>   as and example: [try pasting this](https://github.com/jupyterlab/jupyterlab/issues/8062)

As a datapoint, pasting that into the GitHub comment box just gives the text: as and example: try pasting this

**Comment by jasongrout** [comment]
>  Is it ok to throw away all the text items in clipboardData if there are also files in the clipboardData?

Yes? Like you, I find it difficult to imagine copying a combination of files and unrelated text that you want to paste along with the file...

**Comment by ianhi** [comment]
Does using `this.editor.replaceSelection?.(text)` count as a breaking change? ie this change:
```diff
diff --git a/packages/cells/src/widget.ts b/packages/cells/src/widget.ts
index 56f62675c..65c5c9f6c 100644
--- a/packages/cells/src/widget.ts
+++ b/packages/cells/src/widget.ts
@@ -1484,7 +1484,7 @@ export class MarkdownCell extends AttachmentsCell {
    */
   protected updateCellSourceWithAttachment(attachmentName: string, URI?: string) {
     const textToBeAppended = `![${attachmentName}](attachment:${URI ?? attachmentName})`;
-    this.model.value.insert(this.model.value.text.length, textToBeAppended);
+    this.editor.replaceSelection?.(textToBeAppended);
   }
 
   /**
```

If yes, is the correct solution something like?:
```typescript
if (this.editor.replaceSelection) {
  this.editor.replaceSelection?.(textToBeAppended);
} else {
  this.model.value.insert(this.model.value.text.length, textToBeAppended);
}
```
Using `replaceSelection` is a nice improvement because it will embed the image at the cursor location instead of the current behavior of always embedding at the end of the markdown cell.
