### ISSUE TITLE
Images that has spaces in its filename/path can't be displayed using ![](filename.png) method. 

### ISSUE THREAD

**Issue by jaepil-choi** [jupyterlab/jupyterlab#8067]
## Description
![image](https://user-images.githubusercontent.com/25889304/77233553-9a64b800-6beb-11ea-9419-97e2b123763c.png)

As you can see, a file with spaces can't be displayed using a standard `![](filename.png)` way. 

## Reproduce

It's pretty much self-explanatory. Dragging in the image doesn't solve the problem, as it invokes the same action described above. 

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Expected behavior

It should display the image but apparently it can't interpret the syntax with a filename that has spaces. 

## Context

- Operating System and version: Win 10 1909
- Browser and version: Chrome 80.0
- JupyterLab version: 
```
(deep_learning37) E:\VSCodeProjects\deep_learning_from_scratch_2>jupyter --version
jupyter core     : 4.6.1
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.0.0
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.0.4
traitlets        : 4.3.3

```
<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jaepil-choi** [comment]
Temporary solution: 

Replace all spaces to `_` using cmd command. Say, you're changing all `*.png` files. 

`$ cmd /e:on /v:on /c "for %f in ("* *.png") do (set "n=%~nxf" & set "n=!n: =_!" & ren "%~ff" "!n!" )"`

See more: https://stackoverflow.com/questions/20791264/how-to-replace-all-spaces-by-underscores-in-all-file-names-of-a-folder

**Comment by saulshanabrook** [comment]
Yeah the markdown spec doesn't allow spaces in the URL of the name. So you should replace the spaces with `%20`. 

A nice "fix" here would be to allow drag and drop from the file browser, which could take care of this for you.

**Comment by jasongrout** [comment]
Please see the long discussion at #5153 for more details.

**Comment by jaepil-choi** [comment]
> A nice "fix" here would be to allow drag and drop from the file browser, which could take care of this for you.

No, Can confirm drag & drop doesn't fix it. When you drag & drop, spaces remains and the syntax doesn't work. It just prints the syntax like regular text.
