### ISSUE TITLE
CI Linux Docs step fails due to too many requests for url

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#8068]
## Description

The Azure `Linux Docs` build step systematically fails with 

Error message taken from e.g. https://dev.azure.com/jupyterlab/jupyterlab/_build/results?buildId=5617

```
(line 1090) broken    ***/pull/3182 - 429 Client Error: too many requests for url: ***/pull/3182
(line 1099) broken    ***/pull/3182 - 429 Client Error: too many requests for url: ***/pull/3182
(line 1091) broken    ***/pull/3167 - 429 Client Error: too many requests for url: ***/pull/3167
(line 1093) broken    ***/pull/3182 - 429 Client Error: too many requests for url: ***/pull/3182
```

## Reproduce

Open an pull request on jupyterlab repository and look at the CI build result.

**Comment by blink1073** [comment]
cf https://github.com/minrk/pytest-check-links/pull/7 for a fix
