### ISSUE TITLE
Custom extension icon is transparent after upgrading to v2.0.0

### ISSUE THREAD

**Issue by samuelhwilliams** [jupyterlab/jupyterlab#8077]
## Description
I've just upgraded to JupyterLab v2.0.0. I've got a custom extension that adds a toolbar button with a database icon (via font-awesome `fa fa-database` classes). Since upgrading, the icon has become transparent. Inspecting the icon, I've found the following:

<img width="647" alt="Screenshot 2020-03-24 at 15 14 23" src="https://user-images.githubusercontent.com/2920760/77442285-39eb9b80-6de2-11ea-9301-f06c2d8d1b10.png">
<img width="891" alt="Screenshot 2020-03-24 at 15 14 36" src="https://user-images.githubusercontent.com/2920760/77442298-3bb55f00-6de2-11ea-8b99-f3e50412acba.png">

If I remove the `minimal` class, the icon reappears, or if I override the color and set it to black manually on the element it appears again. I think it's down to the styling from `.jp-Button.minimal`. Looking through the migration docs I can't clearly see what's the new way to show icons, so maybe the font awesome icons aren't supported any more? Or is there something else I need to set/unset to make it come through?

Appreciate any help.

## Reproduce

Attach a toolbar button via a custom extension:
```
    const button = new ToolbarButton({
      iconClass: 'fa fa-database',
      onClick: onClick,
      tooltip: 'Connect to databases'
    });
```

## Expected behavior

The icon is visible.

## Context

- Operating System and version: 10.14.6
- Browser and version: Chrome 79.0.3945.130 
- JupyterLab version: 2.0.0

**Comment by jasongrout** [comment]
CC @telamonian

**Comment by telamonian** [comment]
Yep, this is intentional. If you use an external framework to create your icons, you should expect to have to supply your own styling. See https://github.com/jupyterlab/jupyterlab/issues/8277#issuecomment-620294491 for more details
