### ISSUE TITLE
Enable Node 10+ to work with JupyterLab 2.1

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#8083]
We currently require Node 12+ but we should re-enable Node 10+.

**Comment by jasongrout** [comment]
See https://github.com/jupyterlab/jupyterlab/pull/7677

**Comment by jasongrout** [comment]
From https://github.com/jupyterlab/jupyterlab/pull/7677 - the situation now (I think) is that we *do* support node <12, just that many users will need to set the max memory node options variable.

**Comment by saulshanabrook** [comment]
So next step is to revert changes in that PR

**Comment by afshin** [comment]
Fixed in https://github.com/jupyterlab/jupyterlab/pull/8112
