### ISSUE TITLE
2.1 Release Plan

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#8084]
for jupyterlab server:

1. Merge in JLab server PR https://github.com/jupyterlab/jupyterlab_server/pull/82/files
2. Create release of JLab Server
3. Upgrade JupyterLab to require this newer release

for jupyterlab 

1. Create branch  from 2.0.1 release (branching after last bugfix) to create 2.0.x branch
2. Choose other bugfixes that have been merged to merge into 2.0.x (some kind of meeseeks bot will help)
3. Make 2.0.2 release on monday
4. Make 2.1.0rc release on monday
5. Make sure downstream extensions work (ipywidgets)
6. Create changelog
7. Release 2.1.0 on thursday
8. Branch master to 2.1.x so we can merge breaking changes and backport things we want to 2.1.x

**Comment by saulshanabrook** [comment]
@jasongrout I thought we made a time to meet on Monday to go through the release, but I can't find it in my calendar.  Does it still work for you to meet for this then? Would 3pm EST work for you?

cc @blink1073

**Comment by blink1073** [comment]
Yeah I can do that time.

**Comment by saulshanabrook** [comment]
Just hopped on Jupyter zoom for anyone who is around.

**Comment by saulshanabrook** [comment]
Running notes from release meeting:

I just moved merged in a couple of PRs to the newly created 2.0.x branch. I am going through and moving all PRs that I merged in there, plus the ones I based it on, to 2.0.2 milestone from 2.1.0

**Comment by saulshanabrook** [comment]
Make github action that somehow does this milestone logic for prs....

**Comment by saulshanabrook** [comment]
How to document backports in changelog? 

https://github.com/jupyterlab/jupyterlab/pull/8108

**Comment by saulshanabrook** [comment]
Is upgrading a lumino package to a minor a breaking change? https://github.com/jupyterlab/jupyterlab/pull/7927/files#diff-2a7ea8c28d7effa9e56686cee9459d1a

No, if it's not a singleton

**Comment by saulshanabrook** [comment]
What happens if we merge something then revert it? 

https://github.com/jupyterlab/jupyterlab/pull/7834

What milestone should the PRs have?

**Comment by saulshanabrook** [comment]
Initial release of 2.1 alpha finished.

**Comment by blink1073** [comment]
Thanks!

**Comment by jasongrout** [comment]
I put in https://github.com/jupyterlab/jupyterlab_server/pull/84 since it popped up for me right away using the new on-by-default extension manager.

**Comment by jasongrout** [comment]
2.1 beta and rc were released a few hours ago.

We plan to release 2.1 final Thursday

**Comment by saulshanabrook** [comment]
We are postponing 2.1 to Monday so we can tackle https://github.com/jupyterlab/jupyterlab/issues/8149.

We will release 2.0.2 today with https://github.com/jupyterlab/jupyterlab/pull/8153 once we test it.

**Comment by saulshanabrook** [comment]
We have published 2.1 and 2.0.2
