### ISSUE TITLE
PhosphorJS

### ISSUE THREAD

**Issue by stevenruidigao** [jupyterlab/jupyterlab#8092]
I was just curious, what are you guys doing / how are you guys doing things now that PhosphorJS has been discontinued?

**Comment by jasongrout** [comment]
JupyterLab 2.0 has switched to Lumino, which is a successor of Phosphor maintained by Project Jupyter (and most of the original phosphorjs developers).

**Comment by jasongrout** [comment]
https://github.com/jupyterlab/lumino

**Comment by jasongrout** [comment]
Closing as answered. Thanks!
