### ISSUE TITLE
Jupyter Lab not loading on Safari 13.1 - Mac OS 10.15.4

### ISSUE THREAD

**Issue by sanchezvivi** [jupyterlab/jupyterlab#8093]
After updating to Mac OS 10.15.4, I haven't been able to load Jupyter lab. It looks like it keeps reloading and cloning(?) updating the following messages:

[I 16:58:15.290 LabApp] 301 GET /lab/workspaces/auto-Q/?clone (::1) 0.85ms
[I 16:58:15.584 LabApp] 301 GET /lab/workspaces/auto-v/?clone=auto-Q (::1) 0.60ms
[I 16:58:15.732 LabApp] 301 GET /lab/workspaces/auto-h/?clone=auto-v (::1) 0.65ms
[I 16:58:15.930 LabApp] 301 GET /lab/workspaces/auto-N/?clone=auto-h (::1) 2.07ms
[I 16:58:16.117 LabApp] 301 GET /lab/workspaces/auto-z/?clone=auto-N (::1) 0.60ms
[I 16:58:16.268 LabApp] 301 GET /lab/workspaces/auto-l/?clone=auto-z (::1) 1.98ms
[I 16:58:16.455 LabApp] 301 GET /lab/workspaces/auto-C/?clone=auto-l (::1) 0.58ms
[I 16:58:16.583 LabApp] 301 GET /lab/workspaces/auto-J/?clone=auto-C (::1) 2.40ms
[I 16:58:16.753 LabApp] 301 GET /lab/workspaces/auto-x/?clone=auto-J (::1) 0.62ms
[I 16:58:16.899 LabApp] 301 GET /lab/workspaces/auto-O/?clone=auto-x (::1) 2.17m

I have been able, however, to load the Jupyter Notebook without problems and the Jupyter lab in an environment (lab-test) and without environment in Google Chrome Version 80.0.3987.149 (Official Build) (64-bit)

It's only in Safari Version 13.1 (15609.1.20.111.8) that it won't load. Both normal or private sessions.

Thanks in advance.
Viviane

**Comment by jasongrout** [comment]
What happens if you clear your cookies? What version of JupyterLab?

**Comment by sanchezvivi** [comment]
had already cleared the cookies =\
it’s the version 1.1.4, tried reinstalling and updating as well.

**Comment by jasongrout** [comment]
Updating to what? Does it have a problem with JupyterLab 2.0.1?

**Comment by jasongrout** [comment]
It might be this issue, I think fixed in 1.2.0: https://github.com/jupyterlab/jupyterlab/issues/6921

**Comment by sanchezvivi** [comment]
Thanks! worked after updating to Version 1.2.6 with `conda update --all`

**Comment by jasongrout** [comment]
Great!
