### ISSUE TITLE
Cannot replace with an empty text

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#8098]
## Description

Replacing text with an empty string is not possible.

![replace_does_not_work_if_empty](https://user-images.githubusercontent.com/5832902/77754261-e025e400-7022-11ea-80b8-46f81530655f.gif)

## Reproduce

1. Open search bar
2. Enter some text which exists in the document
3. Open the replace bar, do not enter anything in the replace input
4. Press the "Replace" button
4. See that nothing happens

## Expected behavior

The selected (found) match should be removed. This is how it works in Gedit, Pycharm and most other editors that I have used so far. Gedit example:

![works_in_gedit](https://user-images.githubusercontent.com/5832902/77754389-3004ab00-7023-11ea-8650-27d41e781ad1.gif)

## Context

- Operating System and version: Ubuntu 19.10
- Browser and version: Chrome 80.0.3987.149
- JupyterLab version: Version 2.0.1

**Comment by krassowski** [comment]
Also, the buttons do not have pressed (`:active`) state (as you can see on the gif it is hard to tell that I pressed the replace button many times) - should I open a bug report for that, or is this a design decision?

**Comment by jasongrout** [comment]
Thanks! Fixed in #8100
