### ISSUE TITLE
Apache Toree kernel doesn't work in Jupyterlab launched by anaconda-navigator

### ISSUE THREAD

**Issue by sammy-shao** [jupyterlab/jupyterlab#8099]
when i launch jupyterlab by anaconda-navigator,and open a file by Apache Toree scala ,
the kernel is dead ,and show its will restart, and then the kernel always show Autorestarting...
![image](https://user-images.githubusercontent.com/32064088/77759777-42590600-7070-11ea-9cb4-cd5cecc03a79.png)

however,when i launch jupyterlab by command line in shell ,it's all right...
![Uploading image.png…]()

why is that...
My Apache Toree scala is  Version 0.3.0

**Comment by sammy-shao** [comment]
![image](https://user-images.githubusercontent.com/32064088/77760057-bf847b00-7070-11ea-83ee-069dd682857b.png)
![image](https://user-images.githubusercontent.com/32064088/77760068-c14e3e80-7070-11ea-9fb7-43905d342004.png)
My Apache Toree scala is Version 0.3.0  and My jupyterlab is version 1.2.6

**Comment by jasongrout** [comment]
> when i launch jupyterlab by anaconda-navigator ... the kernel is dead

> however,when i launch jupyterlab by command line in shell ,it's all right...

This indicates you should file this issue with Anaconda, as it appears to be an Anaconda issue.

**Comment by sammy-shao** [comment]
thanks  ^_^
