### ISSUE TITLE
Document search overlay UX problems

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8101]
In Firefox, our document search overlay looks pretty bad right now with a lot of small inconsistencies.

For text files:

<img width="429" alt="Screen Shot 2020-03-27 at 7 10 53 AM" src="https://user-images.githubusercontent.com/192614/77765079-f6b84500-6ffa-11ea-828e-c5cc467e5451.png">

For notebooks:
<img width="420" alt="Screen Shot 2020-03-27 at 7 11 16 AM" src="https://user-images.githubusercontent.com/192614/77765141-0cc60580-6ffb-11ea-9f90-7b41e60574eb.png">
<img width="422" alt="Screen Shot 2020-03-27 at 7 11 28 AM" src="https://user-images.githubusercontent.com/192614/77765152-10f22300-6ffb-11ea-8167-cfcab64ba168.png">

For example:
* The text is not aligned between buttons and inputs
* The text is even off between the two inputs (I think I measured the find text at 5px above the bottom of the input, while the replace text is 4px above the bottom of the input)
* The buttons are not centered in the find input
* For the notebook search without replace, the up/down arrows are not side-by-side. Even when they are side-by-side, they are not vertically centered in the row, it seems.
* For notebooks, the search options is not left-aligned with the inputs above it.

For comparison, here it is in Chrome for me:
<img width="441" alt="Screen Shot 2020-04-01 at 9 59 26 AM" src="https://user-images.githubusercontent.com/192614/78165060-9f054980-73ff-11ea-8071-ff6d9c5a2d0a.png">

**Comment by jasongrout** [comment]
@tgeorgeux - do you have time to look at this so we can fix this for 2.1?

**Comment by tgeorgeux** [comment]
Here's a reference to the old UX review I did on this feature #6650

**Comment by Juan-132** [comment]
If would be nice if the search box could be:
* Visually separated from the kernel information ('Python 3'). Right now it's one whole.
* Reduce the number of options in the search bar, to make it easier to use.

See below an example how Chrome/Edge implemented the search bar 

Current situation Jupyter
![image](https://user-images.githubusercontent.com/59505296/79687255-4da1ea80-8246-11ea-8a4b-f6c071ae58dd.png)


How Chrome/Edge handle it
<img width="455" alt="chrome-edge" src="https://user-images.githubusercontent.com/59505296/79687131-69f15780-8245-11ea-9fd7-20ad1ac39459.png">

**Comment by fcollonval** [comment]
Status as of JupyterLab 4.0.0rc on Firefox 112:

![image](https://user-images.githubusercontent.com/8435071/234895539-a776361e-81b0-4256-b31a-4034f9bb7d04.png)

It is better. So I will close this for people to be able to open more specific issues if needed.
