### ISSUE TITLE
npm error when building jupyter lab extensions

### ISSUE THREAD

**Issue by simonlindgren** [jupyterlab/jupyterlab#8120]
My OS version is Ubuntu 18.04.
`jupyter lab --version 1.2.6`
`node --version v6.13.1`

`jupyter labextension install --debug jupyterlab-plotly`
results in:
```

Searching ['/etc/jupyterhub', '/root/.jupyter', '/opt/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /opt/anaconda3/etc/jupyter
Looking for jupyter_config in /root/.jupyter
Looking for jupyter_config in /etc/jupyterhub
Yarn configuration loaded.
Node v6.13.1

> /opt/anaconda3/bin/npm pack jupyterlab-plotly
/jupyterlab-plotly-1.5.4.tgz

Yarn configuration loaded.
Node v6.13.1

Building jupyterlab assets (build:prod:minimize)
> node /opt/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
/
npm dependencies failed to install
Traceback (most recent call last):

  File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

  File "/opt/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 660, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-_kl4jloz.log
Exiting application: jupyter
```

**Comment by afshin** [comment]
I think the issue is your version of `node`. Can you upgrade to a version that is v10+?

**Comment by simonlindgren** [comment]
This is what I have:
`which nodejs` --> `usr/bin/nodejs`
`nodejs --version` --> `v12.16.1`
`which node`--> `/opt/anaconda3/bin/node`
`node --version`--> `v6.13.1`

**Comment by blink1073** [comment]
We explicitly need the `node` executable, since that is what yarn uses.

**Comment by simonlindgren** [comment]
Sorry, not super knowledgeable about this. So, how do I get the `node` executable in the right location for the processes that need it?

**Comment by blink1073** [comment]
`/opt/anaconda3/bin/conda install --channel conda-forge nodejs=13` will upgrade your anaconda node version to the latest.

**Comment by simonlindgren** [comment]
This gets me stuck like this forever:

`/opt/anaconda3/bin/conda install --channel conda-forge nodejs=13.10.1`

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: /

**Comment by afshin** [comment]
Could you please create a brand new environment to disambiguate what is happening?

```
conda create -y -n lab-with-plotly -c conda-forge nodejs jupyterlab=1
conda activate lab-with-plotly
jupyter labextension install --debug jupyterlab-plotly
```

But if you just want it all the work out of the box for this specific extension, there is a conda recipe:

```
conda create -y -n lab-with-plotly -c conda-forge nodejs jupyterlab=1 jupyterlab-plotly-extension
```

**Comment by simonlindgren** [comment]
I ended up solving it like this:

```
curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
apt install -y nodejs
```

Delete the anaconda `node` and symlink to the newer one:
```
rm /opt/anaconda3/bin/node delete the anaconda node
ln -s /usr/bin/node /opt/anaconda3/bin/node
```

**Comment by Ismar11** [comment]
Hi, I had the same issue with MacOS 10.15.3. Log excerpt after running `jupyter lab build`

```
error ws@7.2.1: The engine "node" is incompatible with this module. Expected version ">=8.3.0". Got "6.13.1"
error Found incompatible module
```

The solution proposed by @simonlindgren worked out for me (thanks!). **Only one difference** - I had to download the bins from nodejs site https://nodejs.org/en/download/ since homebrew was failing to install it.
