### ISSUE TITLE
Jupyter Lab 1.1.4 webpage keep refreshing infinitely

### ISSUE THREAD

**Issue by hustkisas** [jupyterlab/jupyterlab#8123]
## Description

After I installed it, jupyter lab works fine. Then I installed a couple of packages Julia, JuMP, etc. When I come back to Jupyter lab, it didn't work. It keep refreshing the page. and the command window shows the following:

adminq@egsadmins-MacBook-Pro ~ % jupyter lab
[I 11:17:04.417 LabApp] JupyterLab extension loaded from /Users/adminq/opt/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 11:17:04.417 LabApp] JupyterLab application directory is /Users/adminq/opt/anaconda3/share/jupyter/lab
[I 11:17:04.418 LabApp] Serving notebooks from local directory: /Users/adminq
[I 11:17:04.418 LabApp] The Jupyter Notebook is running at:
[I 11:17:04.418 LabApp] http://localhost:8888/?token=85c4f32548443ce55a2a84eda037dbec07cd3e328696b955
[I 11:17:04.418 LabApp]  or http://127.0.0.1:8888/?token=85c4f32548443ce55a2a84eda037dbec07cd3e328696b955
[I 11:17:04.418 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:17:04.423 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/adminq/Library/Jupyter/runtime/nbserver-1518-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=85c4f32548443ce55a2a84eda037dbec07cd3e328696b955
     or http://127.0.0.1:8888/?token=85c4f32548443ce55a2a84eda037dbec07cd3e328696b955
[I 11:17:06.139 LabApp] 301 GET /lab/workspaces/auto-d/?clone (::1) 0.67ms
[I 11:17:06.296 LabApp] 301 GET /lab/workspaces/auto-G/?clone=auto-d (::1) 0.57ms
[I 11:17:06.474 LabApp] 301 GET /lab/workspaces/auto-z/?clone=auto-G (::1) 0.57ms
[I 11:17:06.637 LabApp] 301 GET /lab/workspaces/auto-E/?clone=auto-z (::1) 0.56ms
[I 11:17:06.804 LabApp] 301 GET /lab/workspaces/auto-o/?clone=auto-E (::1) 0.57ms
[I 11:17:06.983 LabApp] 301 GET /lab/workspaces/auto-k/?clone=auto-o (::1) 0.57ms
[I 11:17:07.144 LabApp] 301 GET /lab/workspaces/auto-r/?clone=auto-k (::1) 0.57ms
[I 11:17:07.303 LabApp] 301 GET /lab/workspaces/auto-5/?clone=auto-r (::1) 0.64ms
[I 11:17:07.422 LabApp] 301 GET /lab/workspaces/auto-o/?clone=auto-5 (::1) 0.59ms
[I 11:17:07.635 LabApp] 301 GET /lab/workspaces/auto-c/?clone=auto-o (::1) 0.54ms
[I 11:17:07.798 LabApp] 301 GET /lab/workspaces/auto-I/?clone=auto-c (::1) 0.56ms
[I 11:17:07.961 LabApp] 301 GET /lab/workspaces/auto-N/?clone=auto-I (::1) 0.55ms
[I 11:17:08.135 LabApp] 301 GET /lab/workspaces/auto-I/?clone=auto-N (::1) 0.61ms
[I 11:17:08.283 LabApp] 301 GET /lab/workspaces/auto-w/?clone=auto-I (::1) 0.57ms
[I 11:17:08.433 LabApp] 301 GET /lab/workspaces/auto-4/?clone=auto-w (::1) 0.57ms
[I 11:17:08.612 LabApp] 301 GET /lab/workspaces/auto-0/?clone=auto-4 (::1) 0.57ms
[I 11:17:08.788 LabApp] 301 GET /lab/workspaces/auto-I/?clone=auto-0 (::1) 0.68ms
[I 11:17:08.952 LabApp] 301 GET /lab/workspaces/auto-g/?clone=auto-I (::1) 0.55ms
[I 11:17:09.106 LabApp] 301 GET /lab/workspaces/auto-U/?clone=auto-g (::1) 0.60ms
[I 11:17:09.284 LabApp] 301 GET /lab/workspaces/auto-T/?clone=auto-U (::1) 0.59ms
[I 11:17:09.442 LabApp] 301 GET /lab/workspaces/auto-d/?clone=auto-T (::1) 0.56ms
[I 11:17:09.602 LabApp] 301 GET /lab/workspaces/auto-Z/?clone=auto-d (::1) 0.56ms
[I 11:17:09.756 LabApp] 301 GET /lab/workspaces/auto-0/?clone=auto-Z (::1) 0.50ms
[I 11:17:09.905 LabApp] 301 GET /lab/workspaces/auto-W/?clone=auto-0 (::1) 0.68ms
[I 11:17:10.075 LabApp] 301 GET /lab/workspaces/auto-W/?clone=auto-W (::1) 0.58ms
[I 11:17:10.307 LabApp] 301 GET /lab/workspaces/auto-j/?clone=auto-W (::1) 0.71ms

I searched the forum, someone talks about a similar behavior when opening multiple tabs. But I have only one tab. I tried restarting computer, close all tabs. It didn't work. Can someone shed a light on this? Thanks !

**Comment by rahulpshah** [comment]
Related - https://github.com/jupyterlab/jupyterlab/issues/6921?

**Comment by jasongrout** [comment]
Try upgrading to 1.2.8, or even better, 2.0.1.

**Comment by hustkisas** [comment]
> Try upgrading to 1.2.8, or even better, 2.0.1.

I tried to update using conda update -c conda-forge jupyterlab
I'm still jupyter lab --version   1.1.4.

**Comment by hustkisas** [comment]
> Related - #6921?

Thanks. But I don't have an old jupyterlab tab open.

**Comment by jasongrout** [comment]
Try giving the version explicitly, like `conda install -c conda-forge jupyterlab=2.0.1` or `conda install -c conda-forge jupyterlab=1.2.8`. Or you can set up a new environment with an updated JupyterLab.

**Comment by hustkisas** [comment]
> Try giving the version explicitly, like `conda install -c conda-forge jupyterlab=2.0.1` or `conda install -c conda-forge jupyterlab=1.2.8`. Or you can set up a new environment with an updated JupyterLab.

Thank you Jason. The command didn't work either. It had problem solving environment:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

**Comment by hugohuijs** [comment]
Is this still being worked on?
I have this exact problem and am unable to open jupyter lab now :(
Really don't know what to try anymore haha have seen every solution and nothing has worked (cleared the port, no existing webpages or anything running what so ever)
Please get back to me as soon as you can! Greatly appreciate the help

**Comment by hugohuijs** [comment]
Ah! I suggest it is a safari bug. 
I downloaded chrome and started jupyter lab from the terminal using: 
jupyter-lab --browser=chrome
The workspace was then opened in chrome. 
Goodluck on fixing it. Let me know when it is done :)

**Comment by blink1073** [comment]
Hi @hugohuijs, can you please try loading the page after adding `?reset` to the url?  https://jupyterlab.readthedocs.io/en/stable/user/urls.html#resetting-a-workspace

**Comment by jasongrout** [comment]
> Is this still being worked on?

The known bug in Safari is worked around in newer versions of JupyterLab. That's why we suggest upgrading above.

**Comment by jasongrout** [comment]
Closing since this is fixed in JupyterLab 1.2 or later. If you need help installing JupyterLab 1.2, please comment below.

**Comment by hugohuijs** [comment]
Hi Jason, I am unable to install the newest version with the way you described. (unable to solve with flexible environment)
