### ISSUE TITLE
Sublime Text Keymap is not working inside a cell

### ISSUE THREAD

**Issue by Scoodood** [jupyterlab/jupyterlab#8128]
## Description

The SublimeText keymap is not working in **Jupyterlab** notebook cell. However, this feature is working fine in **Jupyter Notebook**. The keymap means a lot to me in term of productivity. This is the only reason I still stick to Jupyter notebook. Is there any fix for Jupyterlab?

## Reproduce

This video is to show that the SublimeText keymap is working in Jupyter notebook, but it is broken in Jupyterlab.

![out](https://user-images.githubusercontent.com/15989924/77875623-803b6300-7205-11ea-9bc0-ee2511f70259.gif)

**Comment by ianhi** [comment]
The setting you are changing only changes the keymap for the file editor. Currently you need to an extension to implement alternate keymaps in the notebook. Seems like this extension: https://github.com/ryantam626/jupyterlab_sublime is what you want.

**Comment by Scoodood** [comment]
hi @ianhi, awesome. I followed your advice to add that extension and now it's working! Thanks
