### ISSUE TITLE
TextEditor, allow scroll past EOF

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#813]
Most editor allow to scroll past the end of a file, for example vim:

![screen shot 2016-08-30 at 10 43 50](https://cloud.githubusercontent.com/assets/335567/18100180/b700fbb6-6e9e-11e6-9d26-a7b8fa099b0c.png)

Which is extremely useful to have code at programmer eye level. 

The current text editor in JupyterLab does not seem to allow that when the text in the editor is longer than the editor window; it is far from critical, but I think is important for the long term usage of the editor. 

It might be just a codemirror option though I have not investigated.

**Comment by jasongrout** [comment]
See also #488, which is about adding it to consoles and notebooks.

**Comment by sccolbert** [comment]
There appears to be a `scrollPastEnd` addon for CodeMirror:
https://github.com/codemirror/CodeMirror/blob/master/addon/scroll/scrollpastend.js

**Comment by Carreau** [comment]
> See also #488, which is about adding it to consoles and notebooks.

Ah thanks, I search the cat:Editor category and missed that one. 

> There appears to be a scrollPastEnd addon for CodeMirror:
> https://github.com/codemirror/CodeMirror/blob/master/addon/scroll/scrollpastend.js

Indeed, I looked at the manual but missed the addons ! Nice find.

**Comment by svenefftinge** [comment]
monaco does this by default (#135)

**Comment by ellisonbg** [comment]
Assigning to @eskirk

**Comment by jzf2101** [comment]
@eskirk are you still working on this? I was hoping to tag this as sprint-friendly
