### ISSUE TITLE
Disable downloads from jupyterlab

### ISSUE THREAD

**Issue by maya-harel** [jupyterlab/jupyterlab#8142]
i am running jupyterlab with jupyterhub (with K8S) and using sensitive data, so i want to disable the option to download files from the lab to local machines
so i edited the relevant jupyterlab extensions (filebrowser, docmanager, docregisty), packaged them with npm and installed the new version (using my dockerfile)
but when running the lab i get an empty workspace (no open to create new notebook) and in the console i am getting these errors :

```
Error: No provider for: @jupyterlab/docmanager:IDocumentManager.
    at JupyterLab.push.2dC9.Application.resolveRequiredService (index.js:191)
    at index.js:149
    at Array.map (<anonymous>)
    at JupyterLab.push.2dC9.Application.activatePlugin (index.js:149)
    at JupyterLab.push.2dC9.Application.resolveRequiredService (index.js:199)
    at index.js:149
    at Array.map (<anonymous>)
    at JupyterLab.push.2dC9.Application.activatePlugin (index.js:149)
    at JupyterLab.push.2dC9.Application.resolveRequiredService (index.js:199)
    at index.js:149

```
```
Error: No provider for: @jupyterlab/filebrowser:IFileBrowserFactory.
    at JupyterLab.push.2dC9.Application.resolveRequiredService (index.js:191)
    at index.js:149
    at Array.map (<anonymous>)
    at JupyterLab.push.2dC9.Application.activatePlugin (index.js:149)
    at JupyterLab.push.2dC9.Application.resolveRequiredService (index.js:199)
    at index.js:149
    at Array.map (<anonymous>)
    at JupyterLab.push.2dC9.Application.activatePlugin (index.js:149)
    at index.js:275
    at Array.map (<anonymous>)
```

the only changes i made where to comment out the download icon + relevant download functions

or is there any other way to disable downloading from the jupyterlab ?
thanks !

**Comment by jasongrout** [comment]
Note that disabling downloading files is something that requires changes to the server. Changing the interface in JupyterLab will not disable the ability to just go to the right URL and get the file.

See #5274 for more discussion. I also found #6950 when I searched for "disable download" in this repo.

**Comment by maya-harel** [comment]
changes in the server you mean the https://github.com/jupyterlab/jupyterlab_server repo ?
if i disable the download in the lab, including the 'get download url', how can the user bypass this and download files anyway ?

**Comment by jasongrout** [comment]
> how can the user bypass this and download files anyway ?

They can just use the notebook server api by going to the url for downloading a file. You can get that URL by right-clicking on a file and selecting "Open in New Browser Tab" (the URL has `/files/path/to/file` in it, probably). Note that that URL works whether or not the menu item is there - it's part of the server api.

> changes in the server you mean the https://github.com/jupyterlab/jupyterlab_server repo ?

They could maybe be done there, or in the Jupyter Notebook repo (we inherit from the Jupyter Notebook server). The downloads (and in general the file access) are managed by the [Contents Manager](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/manager.py) (see also [here](https://jupyter-notebook.readthedocs.io/en/stable/extending/contents.html)) in the notebook.

Note also that JupyterLab itself uses the [server rest api](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml) to get the file contents, so a user could manually hit that rest api endpoint to get the contents of a file, just like JupyterLab does.
