### ISSUE TITLE
Remove experimental label from enable extension manager menu item

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#8144]
Now that the extension manager is enabled by default, we need to do something with the existing "Enable extension manager" command and UI in the settings menu.

I think for now, we should at least get rid of the "Experimental" text on it.

I would vote for keeping the command in there and the menu item there, at least until the next major version. It is still usable to disable the extension manager.

**Comment by echarles** [comment]
@saulshanabrook https://github.com/jupyterlab/jupyterlab/pull/8145 implements this.

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/8145.
