### ISSUE TITLE
jupyter lab build npm dependencies failed WSL ubuntu 18.04

### ISSUE THREAD

**Issue by Christophe-pere** [jupyterlab/jupyterlab#8147]
## Description

Hi there,

Like many of us (after reading issues) I have the issue of build failed on my ubuntu 18.04 in the WSL. 

## Reproduce
What have I done ? 

1. upgrade jupyter lab ==> v2.0.1
2. install npm (nmp v3.5.2 ; node v8.10.0)
3. run jupyter lab
4. Enable Extension Manager
5. install nbdev via pip 
6. Find in Extension manager @jupyterlab/debugger
7. Rebuild 
8. See error ' build failed'
9. Go to terminal and try 'jupyter lab build' 
10. See error:

```
[LabBuildApp] JupyterLab 2.0.1
[LabBuildApp] Building in /home/chris/.local/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (ie the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-8eh7m70_.log
```
When I read the log file I have this: 

```
[LabBuildApp] Building in /home/chris/.local/share/jupyter/lab
[LabBuildApp] Node v8.10.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod)
[LabBuildApp] > node /home/chris/.local/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@jupyter-widgets/base@^3.0.0" required by "@jupyter-widgets/jupyterlab-manager@file:../exte
nsions/jupyter-widgets-jupyterlab-manager-2.0.0.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@types/backbone@^1.4.1" required by "@jupyter-widgets/jupyterlab-manager@file:../extension
s/jupyter-widgets-jupyterlab-manager-2.0.0.tgz" on the "npm" registry.
    at /home/chris/.local/share/jupyter/lab/staging/yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (/home/chris/.local/share/jupyter/lab/staging/yarn.js:310:30)
    at /home/chris/.local/share/jupyter/lab/staging/yarn.js:323:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find package "@jupyter-widgets/controls@^2.0.0" required by "@jupyter-widgets/jupyterlab-manager@file:..
/extensions/jupyter-widgets-jupyterlab-manager-2.0.0.tgz" on the "npm" registry.
    at /home/chris/.local/share/jupyter/lab/staging/yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (/home/chris/.local/share/jupyter/lab/staging/yarn.js:310:30)
    at /home/chris/.local/share/jupyter/lab/staging/yarn.js:323:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find package "@jupyter-widgets/output@^3.0.0" required by "@jupyter-widgets/jupyterlab-manager@file:../e
xtensions/jupyter-widgets-jupyterlab-manager-2.0.0.tgz" on the "npm" registry.
    at /home/chris/.local/share/jupyter/lab/staging/yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (/home/chris/.local/share/jupyter/lab/staging/yarn.js:310:30)
    at /home/chris/.local/share/jupyter/lab/staging/yarn.js:323:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find package "jquery@^3.1.1" required by "@jupyter-widgets/jupyterlab-manager@file:../extensions/jupyter
-widgets-jupyterlab-manager-2.0.0.tgz" on the "npm" registry.
    at /home/chris/.local/share/jupyter/lab/staging/yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (/home/chris/.local/share/jupyter/lab/staging/yarn.js:310:30)
    at /home/chris/.local/share/jupyter/lab/staging/yarn.js:323:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: Couldn't find package "semver@^6.1.1" required by "@jupyter-widgets/jupyterlab-manager@file:../extensions/jupyter
-widgets-jupyterlab-manager-2.0.0.tgz" on the "npm" registry.
    at /home/chris/.local/share/jupyter/lab/staging/yarn.js:38113:17
    at Generator.throw (<anonymous>)
    at step (/home/chris/.local/share/jupyter/lab/staging/yarn.js:310:30)
    at /home/chris/.local/share/jupyter/lab/staging/yarn.js:323:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/home/chris/.local/lib/python3.6/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/home/chris/.local/lib/python3.6/site-packages/jupyterlab/labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "/home/chris/.local/lib/python3.6/site-packages/jupyterlab/labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/home/chris/.local/lib/python3.6/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/home/chris/.local/lib/python3.6/site-packages/jupyterlab/commands.py", line 652, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
```

## Context

- Operating System and version: Ubuntu 18.04 WSL windows 10
- Browser and version: Google Chrome v80.0.3987.132
- JupyterLab version: 2.0.1

<details><summary>Troubleshoot Output</summary>
<pre>

$PATH:
        /home/chris/.local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games
        /mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu18.04onWindows_2020.1804.7.0_x64__79rhkp1fndgsc
        /mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/bin
        /mnt/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/libnvvp
        /mnt/c/Program Files/tcl/bin
        /mnt/c/Program Files (x86)/RSA SecurID Token Common
        /mnt/c/ProgramData/Oracle/Java/javapath
        /mnt/c/Windows/System32
        /mnt/c/Windows
        /mnt/c/Windows/System32/wbem
        /mnt/c/Windows/System32/WindowsPowerShell/v1.0
        /mnt/c/Windows/System32/OpenSSH
        /mnt/c/Program Files (x86)/Sennheiser/SoftphoneSDK
        /mnt/c/Program Files (x86)/PuTTY
        /mnt/c/Program Files/Git/cmd
        /mnt/c/Oracle_11gR2/product/11.2.0/client_32/bin
        /mnt/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.5.0
        /mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
        /mnt/c/Users/gen06846/AppData/Local/Microsoft/WindowsApps
        /mnt/c/Users/gen06846/AppData/Local/GitHubDesktop/bin
        /snap/bin

sys.path:
        /home/chris/.local/bin
        /usr/lib/python36.zip
        /usr/lib/python3.6
        /usr/lib/python3.6/lib-dynload
        /home/chris/.local/lib/python3.6/site-packages
        /usr/local/lib/python3.6/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.6.9 (default, Nov  7 2019, 10:44:02)
        [GCC 8.3.0]

platform.platform():
        Linux-4.4.0-17763-Microsoft-x86_64-with-Ubuntu-18.04-bionic

which -a jupyter:
        /home/chris/.local/bin/jupyter

pip list:
        Package                  Version
        ------------------------ -------------------
        absl-py                  0.9.0
        arrow                    0.15.5
        asn1crypto               0.24.0
        astor                    0.8.1
        astropy                  4.0
        attrs                    19.3.0
        Automat                  0.6.0
        backcall                 0.1.0
        beautifulsoup4           4.8.2
        bleach                   3.1.1
        blessed                  1.17.2
        blinker                  1.4
        blis                     0.4.1
        bokeh                    1.4.0
        boto3                    1.12.7
        botocore                 1.15.7
        cachetools               4.0.0
        catalogue                1.0.0
        catalyst                 20.2.4
        certifi                  2018.1.18
        chardet                  3.0.4
        cirq                     0.7.0
        click                    6.7
        click-plugins            1.1.1
        cligj                    0.5.0
        cloud-init               19.4
        cloudpickle              1.2.2
        colorama                 0.3.7
        command-not-found        0.3
        configobj                5.0.6
        constantly               15.1.0
        crc32c                   2.0
        cryptography             2.1.4
        cvxopt                   1.2.4
        cycler                   0.10.0
        cymem                    2.0.3
        Cython                   0.29.15
        dask                     2.11.0
        dataclasses              0.7
        datatable                0.10.1
        decorator                4.4.1
        defusedxml               0.6.0
        dill                     0.3.1.1
        distro-info              0.18ubuntu0.18.04.1
        dlx                      1.0.4
        dm-tree                  0.1.2
        docloud                  1.0.375
        docplex                  2.12.182
        docutils                 0.15.2
        entrypoints              0.3
        fastdtw                  0.3.4
        fastscript               0.1.4
        fasttext                 0.9.1
        filelock                 3.0.12
        Fiona                    1.8.13.post1
        Flask                    1.1.1
        Flask-Compress           1.4.0
        fsspec                   0.6.2
        future                   0.18.2
        gast                     0.2.2
        gcsfs                    0.6.0
        geopandas                0.7.0
        gitdb                    4.0.2
        GitPython                3.1.0
        google-api-core          1.16.0
        google-api-python-client 1.8.0
        google-auth              1.11.2
        google-auth-httplib2     0.0.3
        google-auth-oauthlib     0.4.1
        google-pasta             0.1.8
        googleapis-common-protos 1.51.0
        grpcio                   1.27.2
        gym                      0.16.0
        h5py                     2.10.0
        hiplot                   0.1.5
        httplib2                 0.9.2
        hyperlink                17.3.1
        idna                     2.6
        imageio                  2.8.0
        imantics                 0.1.12
        importlib-metadata       1.6.0
        incremental              16.10.1
        inflection               0.3.1
        ipykernel                5.1.4
        ipython                  7.12.0
        ipython-genutils         0.2.0
        ipywidgets               7.5.1
        itsdangerous             1.1.0
        jedi                     0.16.0
        Jinja2                   2.10
        jmespath                 0.9.5
        joblib                   0.14.1
        json5                    0.9.1
        jsonpatch                1.16
        jsonpointer              1.10
        jsonschema               3.2.0
        jupyter                  1.0.0
        jupyter-client           6.0.0
        jupyter-console          6.1.0
        jupyter-core             4.6.3
        jupyterlab               2.0.1
        jupyterlab-server        1.0.6
        Keras                    2.3.1
        Keras-Applications       1.0.8
        Keras-Preprocessing      1.1.0
        keyring                  10.6.0
        keyrings.alt             3.0
        kiwisolver               1.1.0
        koalas                   0.28.0
        language-selector        0.1
        lxml                     4.5.0
        Markdown                 3.2.1
        MarkupSafe               1.0
        marshmallow              3.5.0
        marshmallow-polyfield    5.8
        matplotlib               3.1.3
        mistune                  0.8.4
        more-itertools           8.2.0
        mpmath                   1.1.0
        munch                    2.5.0
        murmurhash               1.0.2
        nbconvert                5.6.1
        nbdev                    0.2.16
        nbformat                 5.0.4
        nest-asyncio             1.2.3
        netifaces                0.10.4
        networkx                 2.3
        nltk                     3.4.5
        notebook                 6.0.3
        ntlm-auth                1.4.0
        numpy                    1.18.1
        oauthlib                 3.1.0
        opencv-python            4.2.0.32
        opt-einsum               3.1.0
        packaging                20.1
        PAM                      0.4.2
        pandas                   1.0.1
        pandoc                   1.0.2
        pandocfilters            1.4.2
        parso                    0.6.1
        patsy                    0.5.1
        pexpect                  4.8.0
        photutils                0.7.2
        pickleshare              0.7.5
        Pillow                   6.2.2
        pip                      20.0.2
        plac                     1.1.3
        ply                      3.11
        preshed                  3.0.2
        prometheus-client        0.7.1
        promise                  2.3
        prompt-toolkit           3.0.3
        protobuf                 3.8.0
        psutil                   5.7.0
        ptyprocess               0.6.0
        pyarrow                  0.14.1
        pyasn1                   0.4.2
        pyasn1-modules           0.2.1
        pybind11                 2.4.3
        pycocotools              2.0.0
        pycrypto                 2.6.1
        pyglet                   1.5.0
        Pygments                 2.5.2
        pygobject                3.26.1
        PyJWT                    1.5.3
        pyOpenSSL                17.5.0
        pyparsing                2.4.6
        pyproj                   2.5.0
        pyrsistent               0.16.0
        pyscf                    1.7.0
        pyserial                 3.4
        python-apt               1.6.5+ubuntu0.2
        python-dateutil          2.8.1
        python-debian            0.1.32
        pytz                     2019.3
        PyWavelets               1.1.1
        pyxdg                    0.25
        PyYAML                   3.12
        pyzmq                    19.0.0
        qiskit                   0.15.0
        qiskit-aer               0.4.0
        qiskit-aqua              0.6.4
        qiskit-ibmq-provider     0.4.6
        qiskit-ignis             0.2.0
        qiskit-terra             0.12.0
        qtconsole                4.6.0
        Quandl                   3.5.0
        regex                    2020.2.20
        requests                 2.23.0
        requests-ntlm            1.1.0
        requests-oauthlib        1.3.0
        requests-unixsocket      0.1.5
        retrying                 1.3.3
        rsa                      4.0
        s3transfer               0.3.3
        sacremoses               0.0.38
        safitty                  1.3
        scikit-image             0.16.2
        scikit-learn             0.22.1
        scipy                    1.4.1
        seaborn                  0.10.0
        SecretStorage            2.3.1
        Send2Trash               1.5.0
        sentencepiece            0.1.85
        service-identity         16.0.0
        setuptools               45.2.0
        Shapely                  1.7.0
        six                      1.14.0
        smmap                    3.0.1
        sortedcontainers         2.1.0
        soupsieve                2.0
        spacy                    2.2.4
        srsly                    1.0.2
        ssh-import-id            5.7
        stanfordnlp              0.2.0
        stanza                   1.0.0
        statsmodels              0.11.1
        sympy                    1.4
        systemd-python           234
        tensorboard              2.1.0
        tensorboardX             2.0
        tensorflow               2.1.0
        tensorflow-datasets      2.1.0
        tensorflow-estimator     2.1.0
        tensorflow-metadata      0.21.1
        tensorflow-quantum       0.2.0
        termcolor                1.1.0
        terminado                0.8.3
        testpath                 0.4.4
        textblob                 0.15.3
        Theano                   1.0.4
        thinc                    7.4.0
        tokenizers               0.5.2
        torch                    1.4.0
        torchvision              0.5.0
        tornado                  6.0.3
        tqdm                     4.43.0
        traitlets                4.3.3
        transformers             2.5.1
        trfl                     1.0.2
        Twisted                  17.9.0
        typesentry               0.2.7
        typing-extensions        3.7.4.1
        ufw                      0.36
        unattended-upgrades      0.1
        uritemplate              3.0.1
        urllib3                  1.22
        wasabi                   0.6.0
        wcwidth                  0.1.8
        webencodings             0.5.1
        websockets               7.0
        Werkzeug                 1.0.0
        wheel                    0.30.0
        widgetsnbextension       3.5.1
        wrapt                    1.12.0
        xeus-python              0.6.13
        xgboost                  1.0.2
        xlrd                     1.2.0
        xmljson                  0.2.0
        zipp                     3.1.0
        zope.interface           4.3.2

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
``` 
[W 09:02:02.303 LabApp] Build recommended
[W 09:02:02.304 LabApp] @jupyterlab/debugger needs to be included in build
[W 09:02:02.306 LabApp] @jupyter-widgets/jupyterlab-manager needs to be included in build
[I 09:02:11.376 LabApp] Building jupyterlab assets (build:dev)
[W 09:02:13.969 LabApp] Build failed, running a clean and rebuild
[I 09:02:13.983 LabApp] Cleaning /home/chris/.local/share/jupyter/lab...
[W 09:02:13.985 LabApp] 500 POST /lab/api/build?1585746129868 (127.0.0.1): 'AppOptions' object has no attribute 'all'
[W 09:02:13.986 LabApp] 'AppOptions' object has no attribute 'all'
[E 09:02:13.989 LabApp] {
      "Host": "127.0.0.1:8888",
      "Connection": "keep-alive",
      "Content-Length": "0",
      "Authorization": "token 815631a5fc41a557981a68cf1e8489e55b74b860c80f402d",
      "Sec-Fetch-Dest": "empty",
      "X-Xsrftoken": "2|fbe6b14f|d1a2dd7830bf1ddf6c5f1c8a7049eacd|1585575678",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://127.0.0.1:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://127.0.0.1:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
      "Cookie": "_xsrf=2|fbe6b14f|d1a2dd7830bf1ddf6c5f1c8a7049eacd|1585575678; username-127-0-0-1-8888=\"2|1:0|10:1585746120|23:username-127-0-0-1-8888|44:MmIzMjgyOGZiNjcyNDU2Yzg0ZjVlNDk5YTJkY2Q1MTg=|0f20ce0b5dd410b467cb3cec28809dd1a291ee2d57585c38ac4350a625f3dcbc\""
    }
[E 09:02:14.003 LabApp] 500 POST /lab/api/build?1585746129868 (127.0.0.1) 4116.31ms referer=http://127.0.0.1:8888/lab
```

</pre>
</details>

If someone can help me. 

Best,

C.

**Comment by jasongrout** [comment]
First, can you upgrade node to at least node 10, or preferably node 12?

**Comment by jasongrout** [comment]
What jupyterlab extensions do you have installed? `jupyter labextension list`

**Comment by Christophe-pere** [comment]
Hi,

Thanks for you answer. I just upgraded nodejs to the latest version:
```
~$node -v
v.13.12.0  
```
After that testing with 
```
~$jupyter lab build
[LabBuildApp] JupyterLab 2.0.1
[LabBuildApp] Building in /home/chris/.local/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
```
So it's working thanks a lot. 

To your last question:
```
~$jupyter labextension list
JupyterLab v2.0.1
Known labextensions:
   app dir: /home/chris/.local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/debugger v0.2.0  enabled  OK
