### ISSUE TITLE
UX: File Browser Filter

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#8157]
Hi,

In notebook, there was a [tree-filter](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/tree-filter/readme.html) plugin. This sort of concept is useful for directories that have a lot of files. While I don't think the UX is perfect from notebook, the idea of filtering files is common in many IDEs (e.g. [vscode](https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree)) and should be added to the file browser.

What do people think?

**Comment by amad-a** [comment]
Hi, I think this is a good idea and I would love to try my hand at implementing it if no one else has started yet!

**Comment by mlucool** [comment]
Linking to related request: https://github.com/jupyterlab/jupyterlab/issues/818

**Comment by echarles** [comment]
I am working on a PR to add this feature in the core filebrowser extension.

As first step, I am thinking to add a search icon to the toolbar (@tgeorgeux any input on this?)

<img width="337" alt="Screenshot 2020-06-23 at 10 08 58" src="https://user-images.githubusercontent.com/226720/85383465-44801300-b540-11ea-90eb-e6b9799199d8.png">

When the user will click on the search icon, an input text will replace the breadcrumbs and `only the current folder filtered items` will be shown.

As a second step, we can discuss to pull all the `current folder subtrees` and show the filtered items with their full path. This has an impact on the server side as we would need to add an entry point (or in jupyterlab_server, or in jupyter_server if we target jlab 3.0).

(adding also @blink1073 to the current 3 participants of this issue).

**Comment by echarles** [comment]
@saulshanabrook

**Comment by jasongrout** [comment]
This is now done in jlab 3.0: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#visual-filter-in-file-browser
