### ISSUE TITLE
Slow Repaint, Screen 1/3 white when scrolling a notebook

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/jupyterlab#816]
I'm experiencing extremely slow repaint on recent Jupyterlab, in particular in notebook, 

Hard to record but still: 

https://youtu.be/172Mmr8VjXE

With a casual scrolling I (especially scrolling up) I get up to 1/3 of my screen not repainted using a "standard" notebook with only ~30 cells, and only text output which is max ~10 lines. 

The repainting issue does not seem to appear in the classic notebook app, or at least much less and only for codemirror text.

Am I the only one that experiences that ? It seem to me that's is recent as I don't remember having seen that. Machine is not under normal usage load and only Notebook-Lab seem to suffer as well at full window resize when there is a notebook open, but there I guess there is a lot of relayout to do.

**Comment by sccolbert** [comment]
Can you test this in a different browser, and/or compare to classic notebook in another recording. To me, this looks like the browser is being slow to update its backbuffer.

I've seen what you show in your video on other Macs before, but have never seen it on my own machine.

**Comment by sccolbert** [comment]
To be clear, scrolling shouldn't be triggering any relayouts. Most browsers will render the entire scrollable area into an offscreen buffer, and then bitblt the visible region into the viewport.

**Comment by Carreau** [comment]
Things are better in classic notebook:

https://youtu.be/Mxg86-wyc8A you can see the blitting if you look for it. 

I won't bother record in FF as if works flawlessly and I see no defects.

**Comment by sccolbert** [comment]
Thanks. Do you mean JLab works flawlessly in Firefox? What browser is the troubled one?

**Comment by Carreau** [comment]
> Do you mean JLab works flawlessly in Firefox

Scrolling with JupyterLab works flawlessly, FF complain regularly about a stalled script on resize of any panel and then freeze for a few second then works again. But that's a separate issue.

Chrome is the troubled one with painting/blitting.

**Comment by sccolbert** [comment]
> stalled script on resize of any panel 
Can you open an issue for this? And if its not too much trouble, include an animated capture.

**Comment by jasongrout** [comment]
I'm seeing the same scrolling problems as @Carreau - on OS X 10.10.5 (14F1909), Chrome Version 52.0.2743.116 (64-bit) (Macbook pro), scrolling a notebook with dozens of empty cells quickly will paint slowly, often showing a third of the tab area as blank until it catches up. I don't see this with, for example, scrolling the csv. I've attached a gif that illustrates the problem (exaggerated since it's not recording 30fps...)

![scrolling](https://cloud.githubusercontent.com/assets/192614/18137937/838506c6-6f78-11e6-8a08-ed64c36e5b7f.gif)

**Comment by jasongrout** [comment]
Oh, and like Matthias, Firefox 48.0.1 seems to work fine.

**Comment by jasongrout** [comment]
This may have to do also with the hidpi screen on a macbook pro. I notice that if I scroll on an external 1440p display, there is no problem with the painting in Chrome, but it is quite noticeable on the laptop screen.

**Comment by jasongrout** [comment]
Here is the paint profiling results scrolling on an external 1440p display. This does not show any lagging of the rendering of the cells as I scroll:

![screen shot 2016-08-31 at 1 03 20 pm](https://cloud.githubusercontent.com/assets/192614/18138638/b6d27146-6f7b-11e6-8784-6f1115dd766b.png)

Here is the paint profiling results scrolling on the Macbook Pro hidpi screen. This did show lots of lagging of the rendering of cells as I scrolled:

<img width="1062" alt="screen shot 2016-08-31 at 1 04 21 pm" src="https://cloud.githubusercontent.com/assets/192614/18138675/de3e3ab2-6f7b-11e6-9894-870750a16ef9.png">

**Comment by sccolbert** [comment]
@jasongrout can you perform the same tests and profiling with the classic notebook?

**Comment by Carreau** [comment]
> Can you open an issue for this? And if its not too much trouble, include an animated capture.

I will but I want to update/check my FF, and say and try to debug which thing does that.

**Comment by jasongrout** [comment]
Classic notebook: I saw some flickering while scrolling on the hidpi screen but very minor and I didn't see white space where rendering lagged. I didn't see any lag or flickering on the 1440p external screen.

1440p external screen:

<img width="1304" alt="screen shot 2016-08-31 at 3 43 54 pm" src="https://cloud.githubusercontent.com/assets/192614/18143950/5d876846-6f92-11e6-88e4-38cfd30af3e9.png">

hidpi laptop screen:

![scrolling-oldnotebook](https://cloud.githubusercontent.com/assets/192614/18143940/4b86b16a-6f92-11e6-8776-ab18c88d05c1.gif)

<img width="1306" alt="screen shot 2016-08-31 at 3 44 34 pm" src="https://cloud.githubusercontent.com/assets/192614/18143966/6cef727e-6f92-11e6-9483-a9a1aa41c546.png">

**Comment by sccolbert** [comment]
Interesting. The timelines look similar between the two.

Are we doing any sort of custom scroll listener stuff in jlab?

**Comment by jasongrout** [comment]
that shouldn't change between the two displays, should it?

**Comment by sccolbert** [comment]
I wouldn't expect it to. But who knows. I just want to make sure it's not due to anything that we have control over.

**Comment by jasongrout** [comment]
It looks like there are quite a few more layers in the jlab notebook (It looks like at least one more per cell, of not more, if I understand the layer boundary view correctly).

**Comment by jasongrout** [comment]
I don't think we're doing any custom scroll listener stuff. https://github.com/jupyter/jupyterlab/search?utf8=%E2%9C%93&q=Scroll doesn't show anything that looks relevant.

**Comment by jasongrout** [comment]
More experiments - when I disable the `overflow:hidden` or the `position:relative` css attributes of phosphor widgets, the number of layers looks like it goes *way* down and scrolling becomes fluid again. This is on the hidpi screen.
![scrollingphosphorcss](https://cloud.githubusercontent.com/assets/192614/18145796/a88afb66-6f9a-11e6-8080-c3b13a2d7c65.gif)

**Comment by sccolbert** [comment]
Interesting. I wonder how that plays out for older versions of Chrome. Like maybe they added some new optimization which is countering out attempts at optimization.

The extra layers will definitely affect the fill-rate.

**Comment by jasongrout** [comment]
Looking more into it, it appears that every codemirror has about 10 layers, and the widgets have one or two. I think having statically rendered cells would go a long ways towards solving this issue.

**Comment by blink1073** [comment]
We have this issue marked 0.9, #958 marked 1.0, and #25 marked 2.0 that are all pointing to the same root cause.  I propose that I finish the work started in https://github.com/jasongrout/jupyterlab/commit/e296cb7a6c3a4cc122df08e9689e0ce5db3c635f and close all three issues.

**Comment by sccolbert** [comment]
Removed the "bug" label, since this is more of an optimization.
