### ISSUE TITLE
'Please use a different workspace.'

### ISSUE THREAD

**Issue by mooreann** [jupyterlab/jupyterlab#8164]
When I open Jupiter lab in terminal I've been getting the screen saying:
 
"This workspace is already in use in another JupyterLab window. Please enter another workspace name."

when the browser pops up. I've tried closing all browsers, closing all terminal windows and restarting my computer to try to reset any other previously open sessions which might be conflicting. I also went to ~/.jupyter/lab/workspaces/ and deleted all workspaces in the folder and tried to restart jupyter. And obviously, entering a new workspace name when the window shows up hasn't been working either.

I've been seeing this in the terminal when I shut it down:

Serving notebooks from local directory: /Users/mooreank
0 active kernels
Shutting down 0 kernels

So maybe the issue is actually that no kernels are starting?
Here's the full terminal output:

(base) NCATS-2003235-P:~ mooreank$ jupyter lab
[I 10:07:46.116 LabApp] JupyterLab extension loaded from /Users/mooreank/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 10:07:46.116 LabApp] JupyterLab application directory is /Users/mooreank/anaconda3/share/jupyter/lab
[W 10:07:46.117 LabApp] JupyterLab server extension not enabled, manually loading...
[I 10:07:46.120 LabApp] JupyterLab extension loaded from /Users/mooreank/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 10:07:46.120 LabApp] JupyterLab application directory is /Users/mooreank/anaconda3/share/jupyter/lab
[I 10:07:46.120 LabApp] Serving notebooks from local directory: /Users/mooreank
[I 10:07:46.120 LabApp] The Jupyter Notebook is running at:
[I 10:07:46.120 LabApp] http://localhost:8888/?token=fd7850c469abb277dc9700e0011ba34335a4d653b494bcff
[I 10:07:46.120 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:07:46.127 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/mooreank/Library/Jupyter/runtime/nbserver-956-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=fd7850c469abb277dc9700e0011ba34335a4d653b494bcff
[I 10:11:56.325 LabApp] 302 GET /?token=fd7850c469abb277dc9700e0011ba34335a4d653b494bcff (::1) 0.40ms
^C[I 10:18:25.931 LabApp] interrupted
Serving notebooks from local directory: /Users/mooreank
0 active kernels
The Jupyter Notebook is running at:
http://localhost:8888/?token=fd7850c469abb277dc9700e0011ba34335a4d653b494bcff
Shutdown this notebook server (y/[n])? ^C[C 10:18:26.074 LabApp] received signal 2, stopping
[I 10:18:26.075 LabApp] Shutting down 0 kernels

**Comment by smeylan** [comment]
Same problem on a fresh install on OS 10.14.6

**Comment by briankarlberg** [comment]
Same error in Safari on OS 10.15.4 from jupyter lab terminal launch.

Switched default browser to Chrome, fixed.

**Comment by zyrxvo** [comment]
The Chrome/Firefox workaround worked for me too, but I really wanted Jupyter Lab in Safari and I found that updating Jupyter Lab (>2.1.2) also fixed the issue. Now it works in all of my browsers.

**Comment by jasongrout** [comment]
The OP didn't fill out the issue template and include their JupyterLab version, so I can't say for sure, but my guess is this is related to https://github.com/jupyterlab/jupyterlab/pull/7316, and upgrading would fix it.

**Comment by jasongrout** [comment]
@mooreann - feel free to comment here if upgrading doesn't fix things, and let us know the information in the new issue template like browser version, jlab version, etc.
