### ISSUE TITLE
Extension manager with both blacklist and whitelist

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8165]
Just checking, this line of code: https://github.com/jupyterlab/jupyterlab/blob/d62dfab15231eb7af9a5b1c4736abd6b4128bae6/packages/extensionmanager/src/listings.ts#L66-L68

Does that mean that if both a blacklist and a whitelist are defined, all extensions are allowed through by default?

Since both blacklists and whitelists are about filtering out extensions, that would be *really* surprising to me. Typically, if a user is *trying* to be more secure, having a completely insecure default fallback for user errors is a bad idea. For example, suppose I had a blacklist of known bad extensions, and I didn't really read the docs or whatever and assume that I can also specify a whitelist. Adding one whitelist entry would then effectively disable my blacklist.

If we really don't want to support both a black and white list at this point (and just pick a precedence, or make the precedence configurable), I think falling back to an all-encompassing blacklist would be better, as it would at least be secure-by-default and give the user reason to look for the error in the js console.

**Comment by jasongrout** [comment]
CC @echarles @saulshanabrook

**Comment by jasongrout** [comment]
Thanks for looking at how things work on the server. I still think we shouldn't fall back to a less secure case, though. As it stands now, it would be easy to make a change on the server to make things work and forget to change something on the server, and then suddenly my whitelist/blacklist is gone. I think failing fast with an exception would be fine too, especially, as you say, this is a case that shouldn't happen.

I just want us to not fall back to ignoring user security preferences. That seems to be a dangerous pattern.

**Comment by echarles** [comment]
Makes sense. I have opened https://github.com/jupyterlab/jupyterlab/pull/8167 to disable the extension manager with a message if both black and white listings are configured.

**Comment by jasongrout** [comment]
Fixed by #8167
