### ISSUE TITLE
Ipywigets stopped working displaying "Error displaying widget: model not found“ after ipyaggrid is enabled

### ISSUE THREAD

**Issue by song0304** [jupyterlab/jupyterlab#8176]
## Description
Ipywigets stopped working after ipyaggrid is enabled.   The error message is  "Error displaying widget: model not found“

Chrome browser console shows there is js error "could not create a model", the underlying error is the extension dynamically injected a <script> tag in the HTML header and the HTTP request for the javascript file was refused by the server.
I learnt from https://github.com/jupyterlab/jupyterlab/issues/3118 that the injected javascript output is no longer supported in jupyterlab.

## Can you please suggest, how to make both  ipywidget and ipyaggrid work?

![RefusedToexecute](https://user-images.githubusercontent.com/15058942/78522318-921d9700-77ff-11ea-9fd6-285623e792df.png)
)

## Reproduce

1.  Open a new notebook and run below code
`    from ipywidgets import IntSlider    
    from IPython.display import display     
    slider = IntSlider(min=1, max=10)    
    display(slider)
`    

## Expected behavior

A slider is displayed in notebook

## Context

- Operating System and version: EKS 1.14
- JupyterLab version:
`jupyter-client         6.0.0              
jupyter-core           4.6.3              
jupyter-flex           0.5.0              
jupyter-server         0.1.1              
jupyter-telemetry      0.0.5              
jupyterhub             1.1.0              
jupyterlab             1.2.5              
jupyterlab-pygments    0.1.0              
jupyterlab-server      1.0.6              
vaex-jupyter           0.4.1 `

Extensions:
JupyterLab v1.2.5
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @8080labs/qgrid v1.1.1  enabled  OK
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        @pyviz/jupyterlab_pyviz v0.8.0  enabled  OK
        bqplot v0.5.3  enabled  OK
        ipyaggrid v0.2.0  enabled  OK
        jupyter-matplotlib v0.7.2  enabled  OK
        jupyter-threejs v2.2.0  enabled  OK
        jupyter-vue v1.3.0  enabled  OK
        jupyter-vuetify v1.2.2  enabled  OK
        jupyterlab-datawidgets v6.2.0  enabled  OK
        jupyterlab-plotly v1.5.2  enabled  OK
        jupyterlab_bokeh v1.0.0  enabled  OK
        plotlywidget v1.5.2  enabled  OK

**Comment by song0304** [comment]
looks similar to  https://github.com/jupyter-widgets/ipywidgets/issues/2637
CC @DGothrek and @oscar6echo

**Comment by jasongrout** [comment]
Can you file an issue with ipyaggrid? It looks like JupyterLab and ipywidgets themselves are working fine.

**Comment by jasongrout** [comment]
Out of curiosity, I just checked in a clean conda environment, installing the latest jupyterlab 2.2.9 and the latest ipywidgets, then following the instructions at https://dgothrek.gitlab.io/ipyaggrid/guide/install.html#jupyterlab to install ipyaggrid. ipywidgets works. I used the following simple example for ipyaggrid:

```python
from pandas import DataFrame
from ipyaggrid import Grid
dfm = pandas.DataFrame( [[1,2,3],[4,5,6]],columns=['A', 'B', 'C'],)
column_defs = [{'field': dfm.index.name}] + [{'field': c} for c in dfm.columns[:3]]
grid_options = {
    'columnDefs' : column_defs,
}

g = Grid(grid_data=dfm,
         grid_options=grid_options,
         index=True)
g
```
and it worked just fine for me.

**Comment by jasongrout** [comment]
Closing, since this does not seem to be an issue with JupyterLab itself. If you are having issues with ipyaggrid, please file an issue with ipyaggrid.
