### ISSUE TITLE
Cannot reopen running terminal in Firefox.

### ISSUE THREAD

**Issue by mwiebusch78** [jupyterlab/jupyterlab#8179]
I'm using JupyterLab 0.35.5 (running on a server not maintained by me) and Firefox 74.0.1. When I close a terminal tab I cannot reopen it using the 'running' tab on the side. Clicking on the terminal does nothing. It works when I use Chrome and the same server.

**Comment by blink1073** [comment]
Hi @mwiebusch78, we don't offer support for 0.35.5 any longer.  Closing since you have a work-around.
