### ISSUE TITLE
Lacking quit buttton after setting command line flag

### ISSUE THREAD

**Issue by joelostblom** [jupyterlab/jupyterlab#8188]
After running `jupyter lab --LabApp.quit_button=True` I don't see a quit button anywhere. I do have a "Shut down" menu item in the file menu but the help text is referring to a quit button in that dashboard which I can't seem to figure out where it is:

```
--LabApp.quit_button=<Bool>
    Default: True
    If True, display a button in the dashboard to quit (shutdown the notebook server).
```

This is what my jupyterlab looks like:

![image](https://user-images.githubusercontent.com/4560057/78711644-2b19e400-78cc-11ea-9027-86bab5bde993.png)

Am I missing something or is the command flag just referring to the menu item rather than a button? And where is "the dashboard", it is the same as the launcher menu?

Versions:

```
Chromium            80.0.3987.163 (Official Build) Arch Linux (64-bit)
IPython             6.5.0
jupyter_client      5.2.3
jupyter_core        4.6.3
jupyterlab          2.1.0
notebook            5.6.0
-----
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20) [GCC 7.3.0]
Linux-5.6.2-arch1-2-x86_64-with-arch
```

Similar previous issue #5965 #4414

**Comment by blink1073** [comment]
Hi @joelostblom, the default value is true, which adds the `File -> Log Out` and `File -> Shut down` buttons.  If you set `--LabApp.quit_button=False` those items do not appear in the menu.   That option comes form the `NotebookApp` [base class](https://github.com/jupyter/notebook/blob/7de8df4dd80f4da03066ddb498d1541182ad19a8/notebook/notebookapp.py#L1174).  Would you like to add an override to `LabApp` with a more appropriate wording [here](https://github.com/jupyterlab/jupyterlab/blob/15ec68bcc8c451188f010a6920b3471a056610e3/jupyterlab/labapp.py#L405)?

**Comment by joelostblom** [comment]
Thanks for the reply @blink1073!

Just to clarify, would I add something like the below where the other options are (e.g. just below [the last definition](https://github.com/jupyterlab/jupyterlab/blob/15ec68bcc8c451188f010a6920b3471a056610e3/jupyterlab/labapp.py#L483-L484):

```python
quit_button = Bool(True, config=True,
        help='If True, display the "Shut Down" and "Log Out" entries in the file menu.')
```

**Comment by blink1073** [comment]
Sounds good!  You can verify that is working with `jupyter lab --help` after running the local install instructions.

**Comment by jasongrout** [comment]
This is a regression in 3.0 - I think the page_config is not getting set properly for this option. I think we are missing

```typescript
        page_config['quitButton'] = self.quit_button
```
in jupyterlab/labapp.py.

**Comment by jasongrout** [comment]
I think we are also missing

```typescript
        page_config['exposeAppInBrowser'] = self.expose_app_in_browser
```

**Comment by jasongrout** [comment]
> This is a regression in 3.0 - I think the page_config is not getting set properly for this option. I think we are missing

Ah, reading the above, I see that the issue here was about the help text, really, not the regression in jlab 3.0. 

I fixed the regression in 3.0 so that `--ServerApp.quit_button` now works in #9262.

Aso for this issue - in jlab 3.0, the option moves to `--ServerApp.quit_button`, which still has the same help text. I think `ServerApp` should have more generic text now, first of all. Second, we should document this (and other options?) as a breaking change, or fix them so they are not breaking changes, in 3.0.

**Comment by jasongrout** [comment]
Decision from dev meeting: Add a `quit_button` trait to the LabApp class so we have backwards compatibility with jlab 2.

**Comment by jasongrout** [comment]
Right now, we do have backwards compatibility. If I invoke `jupyter lab --LabApp.quit_button=False`, for example, I do not get the shutdown/logout menu items, and I do get this message in the console:

> [W 2020-11-11 16:39:56.522 LabApp] 'quit_button' is not found in LabApp, but it was found in both NotebookApp and ServerApp. This is likely a recent change.This config will only be set in ServerApp. Please check if you should also config these traits in NotebookApp for your purpose.

I think the only thing to do here is to change the ServerApp quit_button attribute to have more generic help text. I'll put in a PR for that.
