### ISSUE TITLE
Click outside dialog is closing dialog is it feature?[JL2.0]

### ISSUE THREAD

**Issue by ggbhat** [jupyterlab/jupyterlab#8193]
In latest JL 2.0 clicking outside any dialog it is closed. Its a expected behavior?
If it is expected feature is there any settings to override this for dialog created in custom extension.

**Comment by jasongrout** [comment]
This was requested in https://github.com/jupyterlab/jupyterlab/issues/3784 and implemented in #7885. Right now there is no setting to override this. Can you elaborate more on your usecase?

CC @tgeorgeux

**Comment by jasongrout** [comment]
Note that this should be only implemented for dialogs that have a cancel button, and is equivalent to clicking the cancel button.

**Comment by ggbhat** [comment]
Thanks @jasongrout . I added an ok button still able to close while clicking outside.
Without any button also it is possible to close.
My requirement was to show error message but user should not close dialog in any means.
Is it possible to implement something like using JL dialog component?

**Comment by jasongrout** [comment]
>  My requirement was to show error message but user should not close dialog in any means.

not close by *any* means? Who eventually dismisses the dialog? Just trying to understand your usecase.

**Comment by ggbhat** [comment]
I mean there will not be any cancel/dismiss button. There will be custom button to redirect to some other app.
Usecase:

We have specific url to open Jlab, suppose user enters wrong url we need to tell user entered wrong url, please redirect by showing dialog and should do nothing by dismissing the dialog.

**Comment by jasongrout** [comment]
Looking at the code, it appears that it was always possible to close the dialog by pressing escape: https://github.com/jupyterlab/jupyterlab/blob/5643e641d0ad1f6b654beb2a8ad47b43eb0b2618/packages/apputils/src/dialog.ts#L293-L297

It looks like right now (to me, looking at the code), there is no way to prevent the dialog from dismissing with a reject, either by pressing escape or (recently) clicking outside the dialog.

**Comment by jasongrout** [comment]
I think it makes sense to have what you want, i.e., force the user to take some action and not just dismiss the dialog. Do you want to submit a PR?

**Comment by ggbhat** [comment]
Yes. We can have settings to control this behaviour. That will be good to have feature I think.

**Comment by jasongrout** [comment]
Feel free to continue discussing the technical design of such a feature, or we can continue the discussion on your PR.

**Comment by krassowski** [comment]
This seems to have been resolved by implementing `hasClose` in https://github.com/jupyterlab/jupyterlab/issues/9884/. There might be an issue with the implementation (which is tracked in https://github.com/jupyterlab/jupyterlab/issues/12896), but I think we can close this issue as resolved. Please reopen if I misunderstood.
