### ISSUE TITLE
Plotly : NPM dependencies fail to install

### ISSUE THREAD

**Issue by jtnath** [jupyterlab/jupyterlab#8198]
## Description
I'm a noob trying to make some interactive visualization using plotly on python in juypter lab. 
I use the code below and **I get no figure showing for it on jupyter lab**

import plotly.offline as pyo
from plotly.offline import init_notebook_mode,iplot
import plotly.graph_objects as go
import cufflinks as cf
pyo.init_notebook_mode(connected = True)
import pandas as pd
import plotly
df = pd.read_csv("/Users/jatinnath/Downloads/train.csv")
#labels
lab = df["Survived"].value_counts().keys().tolist()
#values
val = df["Survived"].value_counts().values.tolist()
trace = go.Pie(labels=lab, 
                values=val, 
                marker=dict(colors=['red']), 
                # Seting values to 
                hoverinfo="value"
              )
data = [trace]
layout = go.Layout(title="Survived Distribution")
fig = go.Figure(data = data,layout = layout)
pyo.iplot(fig)

**whenever i try to run jupyter lab build I get the below error.**

[LabBuildApp] JupyterLab 1.2.6
[LabBuildApp] Building in /Users/jatinnath/miniconda3/envs/JatinPyEnv/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: npm dependencies failed to install
See the log file for details:  /var/folders/dn/fqvyrns15x1dl5tvg6_k71zm0000gn/T/jupyterlab-debug-kyto13d4.log

**Attached is the log file**

[LabBuildApp] Building in /Users/jatinnath/miniconda3/envs/JatinPyEnv/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v12.16.1

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /Users/jatinnath/miniconda3/envs/JatinPyEnv/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error Couldn't find package "plotly.js@^1.48.0" required by "@jupyterlab/plotly-extension@file:../extensions/jupyterlab-plotly-extension-1.0.0-bf66bd51b5316849cb40607bb1ec5b1a7f8d0721.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/Users/jatinnath/miniconda3/envs/JatinPyEnv/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/Users/jatinnath/miniconda3/envs/JatinPyEnv/lib/python3.8/site-packages/jupyterlab/labapp.py", line 97, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "/Users/jatinnath/miniconda3/envs/JatinPyEnv/lib/python3.8/site-packages/jupyterlab/commands.py", line 458, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "/Users/jatinnath/miniconda3/envs/JatinPyEnv/lib/python3.8/site-packages/jupyterlab/commands.py", line 660, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: Mac OS Mojave Version 10.14.6 
- Browser and version:
- JupyterLab version:
jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.1.2
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by timkpaine** [comment]
is your network behind a proxy/firewall?
`info There appears to be trouble with your network connection. Retrying...`

**Comment by jtnath** [comment]
Its not, I think.
I just disabled the Mac firewall to test. The log file again gives me the same error with the same There appears to be trouble with your network connection. Retrying...

Can you tell me if what I tried is right ? or is there another way to check the network firewall..No proxies however

**Comment by jasongrout** [comment]
`npm pack plotly.js@^1.48.0` should download the package it is complaining about, which would test the network connection to npmjs for that particular file.

**Comment by jtnath** [comment]
@jasongrout tried this..but it still fails. **Error below** 

npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to http://registry.npmjs.org/plotly.js failed, reason: getaddrinfo ENOTFOUND proxy.company.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**But I'm not using a proxy. And can't figure out what could be the network connectivity issue**

**Log file Below** 
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/jatinnath/miniconda3/envs/JatinPyEnv/bin/node',
1 verbose cli   '/Users/jatinnath/miniconda3/envs/JatinPyEnv/bin/npm',
1 verbose cli   'pack',
1 verbose cli   'plotly.js@^1.48.0'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose config Skipping project config: /Users/jatinnath/.npmrc. (matches userconfig)
5 verbose npm-session e0dc35050a95cfa0
6 silly fetchPackageMetaData error for plotly.js@^1.48.0 request to http://registry.npmjs.org/plotly.js failed, reason: getaddrinfo ENOTFOUND proxy.company.com
7 verbose type system
8 verbose stack FetchError: request to http://registry.npmjs.org/plotly.js failed, reason: getaddrinfo ENOTFOUND proxy.company.com
8 verbose stack     at ClientRequest.<anonymous> (/Users/jatinnath/miniconda3/envs/JatinPyEnv/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
8 verbose stack     at ClientRequest.emit (events.js:311:20)
8 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:426:9)
8 verbose stack     at TLSSocket.emit (events.js:311:20)
8 verbose stack     at emitErrorNT (internal/streams/destroy.js:92:8)
8 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
8 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
9 verbose cwd /Users/jatinnath
10 verbose Darwin 18.7.0
11 verbose argv "/Users/jatinnath/miniconda3/envs/JatinPyEnv/bin/node" "/Users/jatinnath/miniconda3/envs/JatinPyEnv/bin/npm" "pack" "plotly.js@^1.48.0"
12 verbose node v12.16.1
13 verbose npm  v6.13.4
14 error code ENOTFOUND
15 error errno ENOTFOUND
16 error network request to http://registry.npmjs.org/plotly.js failed, reason: getaddrinfo ENOTFOUND proxy.company.com
17 error network This is a problem related to network connectivity.
17 error network In most cases you are behind a proxy or have bad network settings.
17 error network
17 error network If you are behind a proxy, please make sure that the
17 error network 'proxy' config is set properly.  See: 'npm help config'
18 verbose exit [ 1, true ]

**Comment by jasongrout** [comment]
Good news, then! It means we've tracked it down to network connectivity issues you have, so fix those and you should hopefully be good. From your error, it looks like it has to do with a proxy.

**Comment by jtnath** [comment]
But @jasongrout I really don't understand.. like I said earlier, I'm not using a proxy server. I'm just on my home password-protect wifi on a 50 Mbps speed. This error further baffles me.!  :(

**Comment by jasongrout** [comment]
Here's the error:

```
npm ERR! network request to http://registry.npmjs.org/plotly.js failed, reason: getaddrinfo ENOTFOUND proxy.company.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'
```

Did you do what it suggested, reading the `npm help config` help and checking to see if npm thinks it needs to go through a proxy? In particular, when I read the help page, I see `npm config list` helps me see what npm thinks it should do.

**Comment by jtnath** [comment]
ULTIMATE THANK YOU to you @jasongrout . It worked.! turned out that it had taken some crazy settings that once removed made it work like a charm.!
