### ISSUE TITLE
(maybe) Feature request: Async cell

### ISSUE THREAD

**Issue by JiaRu2016** [jupyterlab/jupyterlab#8201]
Sometimes I run time-consuming code in one cell, it will block here, so I can't do other things. Is there any plugin or magic command that make specific cell run "asynchronously" or run in "background" ? eg.

```
%%async
time_consuming_function()
```

**Comment by jasongrout** [comment]
This is up to the kernel, not JupyterLab, so this issue should be created in the ipython repo: https://github.com/ipython/ipython/

They do have a [top-level await](https://ipython.readthedocs.io/en/stable/interactive/autoawait.html) feature now you might check out, or you can use threads.
