### ISSUE TITLE
Can't drag image from jlab filebrowser into markdown cell + different UI on firefox and chrome

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab#8205]
## Description
If I drag an image from the jupyterlab filebrowser over a markdown cell in edit mode the image does not get embedded like it would if I had dragged from the system filebrowser.
![cant_drag](https://user-images.githubusercontent.com/10111092/79006794-e8544800-7b27-11ea-8c78-3de28c3d61b9.gif)

There also appears to be a difference in UI between firefox and chrome. The above GIF was on firefox 75 and the cursor doesn't change to indicate the status of drag and drop. Whereas the cursor does change in chrome 80:
![chrome](https://user-images.githubusercontent.com/10111092/79007215-b394c080-7b28-11ea-9d6f-126bd8d572e6.gif)

Possibly related is https://github.com/jupyterlab/jupyterlab/issues/3656 although I am also unable to drag a notebook file to main area to open it.

## Reproduce

1. Open a markdown cell
2. Try to drag a png from the filebrowser into the markdown cell

## Expected behavior
The image is embedded as an attachment to markdown cell.

## Context

- Operating System and version: popos 19.10
- Browser and version: firefox 75 + chrome 80
- JupyterLab version: 2.1

<details><summary>Troubleshoot Output</summary>
<pre>
sys.path:
	/home/ian/anaconda3/envs/jupyter_md/bin
	/home/ian/anaconda3/envs/jupyter_md/lib/python38.zip
	/home/ian/anaconda3/envs/jupyter_md/lib/python3.8
	/home/ian/anaconda3/envs/jupyter_md/lib/python3.8/lib-dynload
	/home/ian/anaconda3/envs/jupyter_md/lib/python3.8/site-packages
	/home/ian/Documents/jupyter/jupyterlab-1

sys.executable:
	/home/ian/anaconda3/envs/jupyter_md/bin/python

sys.version:
	3.8.1 (default, Jan  8 2020, 22:29:32) 
	[GCC 7.3.0]

platform.platform():
	Linux-5.3.0-7642-generic-x86_64-with-glibc2.10

which -a jupyter:
	/home/ian/anaconda3/envs/jupyter_md/bin/jupyter

pip list:
	Package           Version             Location                                
	----------------- ------------------- ----------------------------------------
	attrs             19.3.0              
	backcall          0.1.0               
	bleach            3.1.3               
	certifi           2019.11.28          
	decorator         4.4.2               
	defusedxml        0.6.0               
	entrypoints       0.3                 
	ipykernel         5.1.4               
	ipython           7.13.0              
	ipython-genutils  0.2.0               
	jedi              0.16.0              
	Jinja2            2.11.1              
	json5             0.9.3               
	jsonschema        3.2.0               
	jupyter-client    6.1.0               
	jupyter-core      4.6.3               
	jupyterlab        2.0.1               /home/ian/Documents/jupyter/jupyterlab-1
	jupyterlab-server 1.0.7               
	MarkupSafe        1.1.1               
	mistune           0.8.4               
	nbconvert         5.6.1               
	nbformat          5.0.4               
	notebook          6.0.3               
	pandocfilters     1.4.2               
	parso             0.6.2               
	pexpect           4.8.0               
	pickleshare       0.7.5               
	pip               20.0.2              
	prometheus-client 0.7.1               
	prompt-toolkit    3.0.4               
	ptyprocess        0.6.0               
	Pygments          2.6.1               
	pyrsistent        0.15.7              
	python-dateutil   2.8.1               
	pyzmq             19.0.0              
	Send2Trash        1.5.0               
	setuptools        46.0.0.post20200309 
	six               1.14.0              
	terminado         0.8.3               
	testpath          0.4.4               
	tornado           6.0.4               
	traitlets         4.3.3               
	wcwidth           0.1.8               
	webencodings      0.5.1               
	wheel             0.34.2

conda list:
	# packages in environment at /home/ian/anaconda3/envs/jupyter_md:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                        main  
	attrs                     19.3.0                   pypi_0    pypi
	backcall                  0.1.0                    pypi_0    pypi
	bleach                    3.1.3                    pypi_0    pypi
	ca-certificates           2020.1.1                      0  
	certifi                   2019.11.28               py38_0  
	decorator                 4.4.2                    pypi_0    pypi
	defusedxml                0.6.0                    pypi_0    pypi
	entrypoints               0.3                      pypi_0    pypi
	ipykernel                 5.1.4                    pypi_0    pypi
	ipython                   7.13.0                   pypi_0    pypi
	ipython-genutils          0.2.0                    pypi_0    pypi
	jedi                      0.16.0                   pypi_0    pypi
	jinja2                    2.11.1                   pypi_0    pypi
	json5                     0.9.3                    pypi_0    pypi
	jsonschema                3.2.0                    pypi_0    pypi
	jupyter-client            6.1.0                    pypi_0    pypi
	jupyter-core              4.6.3                    pypi_0    pypi
	jupyterlab                2.0.1                     dev_0    <develop>
	jupyterlab-server         1.0.7                    pypi_0    pypi
	ld_impl_linux-64          2.33.1               h53a641e_7  
	libedit                   3.1.20181209         hc058e9b_0  
	libffi                    3.2.1                hd88cf55_4  
	libgcc-ng                 9.1.0                hdf63c60_0  
	libstdcxx-ng              9.1.0                hdf63c60_0  
	markupsafe                1.1.1                    pypi_0    pypi
	mistune                   0.8.4                    pypi_0    pypi
	nbconvert                 5.6.1                    pypi_0    pypi
	nbformat                  5.0.4                    pypi_0    pypi
	ncurses                   6.2                  he6710b0_0  
	nodejs                    10.13.0              he6710b0_0  
	notebook                  6.0.3                    pypi_0    pypi
	openssl                   1.1.1e               h7b6447c_0  
	pandocfilters             1.4.2                    pypi_0    pypi
	parso                     0.6.2                    pypi_0    pypi
	pexpect                   4.8.0                    pypi_0    pypi
	pickleshare               0.7.5                    pypi_0    pypi
	pip                       20.0.2                   py38_1  
	prometheus-client         0.7.1                    pypi_0    pypi
	prompt-toolkit            3.0.4                    pypi_0    pypi
	ptyprocess                0.6.0                    pypi_0    pypi
	pygments                  2.6.1                    pypi_0    pypi
	pyrsistent                0.15.7                   pypi_0    pypi
	python                    3.8.1                h0371630_1  
	python-dateutil           2.8.1                    pypi_0    pypi
	pyzmq                     19.0.0                   pypi_0    pypi
	readline                  7.0                  h7b6447c_5  
	send2trash                1.5.0                    pypi_0    pypi
	setuptools                46.0.0                   py38_0  
	six                       1.14.0                   pypi_0    pypi
	sqlite                    3.31.1               h7b6447c_0  
	terminado                 0.8.3                    pypi_0    pypi
	testpath                  0.4.4                    pypi_0    pypi
	tk                        8.6.8                hbc83047_0  
	tornado                   6.0.4                    pypi_0    pypi
	traitlets                 4.3.3                    pypi_0    pypi
	wcwidth                   0.1.8                    pypi_0    pypi
	webencodings              0.5.1                    pypi_0    pypi
	wheel                     0.34.2                   py38_0  
	xz                        5.2.4                h14c3975_4  
	zlib                      1.2.11               h7b6447c_3

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
None
</pre>
</details>

**Comment by jasongrout** [comment]
Also reported at #8569

**Comment by ianhi** [comment]
In the linked issue @jamesdbrock reported that this functionality existed in Jupyterlab 1.2

Also the relevant code for the markdown cells can be found here:
https://github.com/jupyterlab/jupyterlab/blob/732de5f59048b81ddb10bfffdc11e56d3be5e882/packages/cells/src/widget.ts#L1160-L1161

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterlab-file-chooser-widget-server-side/4934/1

**Comment by ianhi** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/8965 :tada:
