### ISSUE TITLE
MyBinder is Outdated

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#8208]
## Description

The binder link in the README works, but it opens lab@1.0.10.

![image](https://user-images.githubusercontent.com/1813603/79024404-d89d2980-7b50-11ea-8ac6-f1d7a1d99968.png)

**Comment by jtpio** [comment]
Thanks @mlucool, good catch.

It looks like the Binder dependencies in the `jupyterlab-demo` repo need to be updated: https://github.com/jupyterlab/jupyterlab-demo/blob/master/binder/environment.yml
