### ISSUE TITLE
Create new notebook via shortcuts w/out mouse bait clicks 

### ISSUE THREAD

**Issue by curiousgg** [jupyterlab/jupyterlab#8215]
Hi, 
I would like to know why there is no shortcut at present available for creating new notebooks
without the need to use the mouse and have to click here and there.
(For instance, see classic instructions here:  https://jupyterlab.readthedocs.io/en/stable/user/notebook.html . I don't want to go through 10 clicks per session to have a new notebook created. It's frustrating and lame.) 

Additionally, I would like to be able to rename the new notebook without the need to have to use my mouse to left/right click on 'Untitled.ipynb' name.

I understand that there might be a way to create a shortcut perhaps ? If so, I would be grateful for detailed description that enable me to go ahead and produce such a  keystroke shortcut.

**Comment by jasongrout** [comment]
You can make keyboard shortcuts in the Settings > Advanced Settings interface. Click on the Keyboard Shortcuts page. It lists the available commands in the system to which you can assign shortcuts. For example, a new notebook shortcut looks like:

```json5
    {
     command: "notebook:create-new",
     selector: "body",
     keys: ["Ctrl Shift N"]
   }
```

**Comment by jasongrout** [comment]
Rename looks like:  

```json5
    {
     command: "docmanager:rename",
     selector: "body",
     keys: ["Ctrl Shift N"], // default shortcut
   }
```

**Comment by jasongrout** [comment]
Closing as answered.

**Comment by jasongrout** [comment]
> I would like to know why there is no shortcut at present available for creating new notebooks

The answer to this is no one has implemented it as a default shortcut.

**Comment by jasongrout** [comment]
Note that you can create a new Launcher panel with the default shortcut of `Shift Accel L`, and then it's one click to create a notebook with a given kernel in that panel.

**Comment by jasongrout** [comment]
You can also activate the command palette with `Shift Accel C` and type "notebook", and for me the first item is to create a new notebook.

**Comment by jasongrout** [comment]
> I don't want to go through 10 clicks per session to have a new notebook created. It's frustrating and lame.

To be clear, that example shows it is 2 clicks to create a notebook: one to create a launcher, then one to select a notebook with a given kernel. If 2 clicks is too much, of course feel free to create a shortcut - that's why we made the shortcuts customizable. But I think we'd all appreciate being clear and accurate in your statement rather than resorting to hyperbole.
