### ISSUE TITLE
%%javascript failed to load external script file

### ISSUE THREAD

**Issue by drhades** [jupyterlab/jupyterlab#8219]
I tried several ways thoses are OK in classical notebook, but failed in lab:

1) 
```
%%HTML
<script src="demo.js"></script>

```
Classic Notebook: popup the expected alert window that defined in demo.js
Lab: no sound

2)
```
%%javascript
require.config({paths: {Algebra: 'https://unpkg.com/ganja.js@1.0.99/ganja'}});
require(['Algebra'],function(Algebra){add_graph_to_notebook(Algebra)});

function add_graph_to_notebook(Algebra){
    var output = Algebra(2,0,1,()=>{
            var point = (x,y)=>1e12-x*1e02+y*1e01;    
            var line = (a,b,c)=>a*1e1+b*1e2+c*1e0;

            var A=point(-1,1), B=point(-1,-1), C=point(1,-1); 
            var L=line(-1,1,0.5)
            var M=()=>C&A;
            var D=()=>L^M;

            return this.graph([
                A, 'A',         // Render point A and label it.
                B, 'B',         // Render point B and label it.
                C, 'C',         // Render point C and label them.
                L, 'L', M, 'M', // Render and label lines.
                D, 'D',         // Intersection point of L and M
                0xff0000,       // Set the color to red.
                [B,C],          // Render line segment from B to C. 
                0xffcccc,       // Set the color to light red.
                [A,B,C]         // render polygon ABC.
            ],{grid:true});

        });

    console.log(output);
    element.append(output)
}

```
Classic Notebook: rendered the expected figure
Lab：Error output 
`Javascript` Error: Can't find variable: require`

**Comment by jasongrout** [comment]
>  Lab: no sound

Does JupyterLab load the file? (You can see it in the network panel of your browser debugger)

>  `Javascript` Error: Can't find variable: require`

JupyterLab does not include requirejs by default

**Comment by drhades** [comment]
> Does JupyterLab load the file? (You can see it in the network panel of your browser debugger)
No

> JupyterLab does not include requirejs by default
How to use requirejs like classic notebook?
Or is there recommended method to load external script?

**Comment by drhades** [comment]
remote url loading is OK:
```
%%HTML
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.js"></script>
```
But cannot load local script:
```
%%HTML
<script src="require.js"></script>
```
ps, the path of the directory containing require.js  has been added to the config item:
```
[~/.jupyter/jupyter_notebook_config.py]
c.NotebookApp.extra_static_paths
```

**Comment by drhades** [comment]
There's the way:
```
%%html
<script src='/files/demo.js'></script>
```
where `/files` corresponding to the root of application path.

**Comment by stefaneidelloth** [comment]
What is the right url when using Jupyterhub if demo.js is located in the workspace of user "test"?
