### ISSUE TITLE
Add guidance for where to raise feature requests/suggestions

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab#8226]
## Problem to be solved

Currently there doesn't seem to be any guidance in the README or the contributor documentation on if feature requests are welcomed and if they are, where they ought to be made. I think I would be nice if the position on these was clarified and an officially sanctioned avenue for them was created. None of  github issues, discourse, and gitter currently seem appropriate for the below reasons:

Quotes are from https://github.com/jupyterlab/jupyterlab#getting-help 

**Issues**:
> Please use the GitHub issues page to provide feedback or submit a bug report. 

Which along with the only template being for bug reports heavily implies that github issues should be reserved for bugs.
![image](https://user-images.githubusercontent.com/10111092/79527763-676ce300-8036-11ea-99e9-695bb22e47b6.png)

**Discourse**:
> We encourage you to ask questions on the Discourse forum. A question answered there can become a useful resource for others.

Doesn't seem like the appropriate venue for suggesting a feature.

**Gitter**:

This perhaps seems the most reasonable place to bring up a feature request. But it is also the platform that I find most intimidating to join.

### Solutions
Obviously if jupyterlab isn't actively looking for feature requests the below suggestions don't apply

1. Add a feature request template issue e.g.:
    - https://github.com/go-fed/activity/blob/master/.github/ISSUE_TEMPLATE/feature-request-template.md
    - https://github.com/wagtail/wagtail/blob/master/.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
    - https://github.com/gatsbyjs/gatsby/blob/master/.github/ISSUE_TEMPLATE/feature_request.md
2. Create multiple rooms on gitter/better document what the acceptable topics are for that chat room.

n.b. this issue mostly follows the first template I linked for solution#1, which provides an example but also feels rather meta.

**Comment by jasongrout** [comment]
Let's add a feature request template for issues. And I would probably heavily emphasize that contributions are most welcome and will help move things forward probably more than anything.

**Comment by jasongrout** [comment]
In that vein, do you want to put in a PR to add a feature template? :)

**Comment by ianhi** [comment]
Sure thing. I think that should probably also include additions in the following places:
https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html
https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md

How about the template has a basic template and suggestions on what to include, but also includes a link to a more comprehensive set of advice on how to make a good feature request somewhere in the docs? (this is how rstudio does it https://github.com/rstudio/rstudio/issues/new?template=feature_request.md)

**Comment by jasongrout** [comment]
That sounds great. Thanks!

**Comment by ianhi** [comment]
Two more thoughts:
1. What about things that aren't feature requests but rather suggestions for improvements. For example:
> I found the documentation for ____ to be pretty sparse, it would be nice if it could be expanded to include ___

This isn't really a bug report, nor is it a feature request. How do you feel about a third template with a title like "Suggestion"? I think the value this provides is lowering the emotional barrier of entry to raising an issue. If someone has a suggestion they may hold back because it doesn't feel big enough to count as a "feature request". Ultimately this may end up being treated by maintainers similarly to a feature request, but I imagine would make more people feel comfortable opening issues.

2. RStudio also includes this template:
![image](https://user-images.githubusercontent.com/10111092/79533635-56c46900-8046-11ea-80d3-e3bcaee8baea.png)
maybe something similar with a link to discourse?

**Comment by ianhi** [comment]
Also:
Any preferences about if the title should include [Feature Request] and if the issue should automatically be labelled as `type:Enhancement`. Not sure what to do about these as the answer seems to depend on the preferences of the core maintainers.

**Comment by jasongrout** [comment]
Please don't annotate the title. It takes up valuable room in the short length of titles available in the listing of issues. Please use labels instead.

**Comment by jasongrout** [comment]
As for questions, we've typically answered questions here, but have also been answering them on discourse. I don't think we have an official policy about one source being preferred. I slightly prefer here because it is clearer how we can preserve this information in the future. Others probably prefer discourse because it can be more friendly for people not already on this coding site.
