### ISSUE TITLE
Browser Check is Broken in CI

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8244]
## Description
Puppeteer v3 does not yet work in the Azure build [environments](https://github.com/puppeteer/puppeteer/issues/5674), and it is affecting anyone that uses our browser check in CI.  cf https://github.com/jupyterlab/extension-cookiecutter-ts/issues/60#issuecomment-616191849.

## Reproduce
- Install JupyterLab in an Azure build environment (GitHub Actions or Azure Pipelines)
- Run `python -m jupyterlab.browser_check`.

The solution is to pin `puppeteer` to `^2` in the [browser check](https://github.com/jupyterlab/jupyterlab/blob/f0153e0258b32674c9aec106383ddf7b618cebab/jupyterlab/browser_check.py#L147).  This should be backported to 2.1.x and 1.2.x.

**Comment by fcollonval** [comment]
The Ubuntu 18.04 image of GitHub is gonna be updated to include the missing dependency (https://github.com/actions/virtual-environments/issues/732).

So it may be better to hold on pinning puppeteer and inform about the [fix](https://github.com/jupyterlab/extension-cookiecutter-ts/issues/60#issuecomment-616191849) of installing `libgm1` for now?

**Comment by jtpio** [comment]
For reference this is the fix in the debugger extension: https://github.com/jupyterlab/debugger/pull/428

> So it may be better to hold on pinning puppeteer and inform about the [fix](https://github.com/jupyterlab/extension-cookiecutter-ts/issues/60#issuecomment-616191849) of installing `libgm1` for now?

This looks like the corresponding PR: https://github.com/actions/virtual-environments/pull/734

However there doesn't seem to be any info on when it will be rolled out.

**Comment by saulshanabrook** [comment]
Just catching up here, so it looks like this there is a fix upstream and we are just waiting for CI to be upgraded to have this fix?

**Comment by blink1073** [comment]
I've now released 1.2.12 and 2.1.1 that contain this fix.

**Comment by jtpio** [comment]
Thank you!

**Comment by blink1073** [comment]
👊
