### ISSUE TITLE
[v2.1.0] Change jupyter-labhub to jupyter-lab don't work

### ISSUE THREAD

**Issue by TuSKan** [jupyterlab/jupyterlab#8253]
![image](https://user-images.githubusercontent.com/10839799/79985540-22570f80-8481-11ea-9ce3-6345d9f44c8e.png)

## Description
I'm receiving *404 : Not Found* when load docker user
On JupyterLab 1.2.0 jupyterhub_config.py using 
`c.Spawner.cmd = ['jupyter', "labhub"]` 
works great.
On JupyterLab 2.1.0 jupyterhub_config.py using 
`c.Spawner.cmd = ['jupyter', "lab"]` 
doesn't work
Both using `c.Spawner.default_url = '/lab'`

## Reproduce
Install jupyterlab using conda
`conda install jupyterhub jupyterlab dockerspawner`
Spawner with dockerspawner

## Context

- Operating System and version: Docker Centos8
- Browser and version:  Chrome 80
- JupyterLab version: 2.1.0

<details><summary>Troubleshoot Output</summary>
<pre>
404 : Not Found
You are requesting a page that does not exist!
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by blink1073** [comment]
Hi @TuSKan, sorry for the confusion.  We removed the `labhub` command in 2.0 since it was redundant.  The updated instructions for using JupyterLab in JupyterHub are [here](https://github.com/jupyterlab/jupyterlab/blob/ed977ed782285cc797b5a333cdc2a7af14a404b8/docs/source/user/jupyterhub.rst#jupyterlab-on-jupyterhub).

**Comment by TuSKan** [comment]
Thank you for responding.
But I already using `c.Spawner.default_url = '/lab'` and `jupyter serverextension enable jupyterlab` in the past.
I just change the `c.Spawner.cmd` from `jupyter labhub` to `jupyter lab` and now I'm receiving *404 : Not Found*
Do you have any idea how can I fix it?

**Comment by blink1073** [comment]
The spawner command stays as the default `c.Spawner.cmd = ['jupyterhub-singleuser']`

**Comment by TuSKan** [comment]
Using `c.Spawner.cmd = ['jupyterhub-singleuser']` I get a redirect loop 500

**Comment by blink1073** [comment]
Can you please post the result of `jupyter troubleshoot` and also as much of your `jupyterhub_config.py` as you're conformable sharing?  If you wrap it in `<details><pre> </pre></details>` it will collapse it on this page.  Here's what I have:

<details>
<pre>
$PATH:
	/Users/stslve/.toolbox/bin
	/Users/stslve/.rodar/bin
	/Users/stslve/.toolbox/bin
	/Users/stslve/miniconda/envs/jlab-pip-2.0/bin
	/Users/stslve/miniconda/condabin
	/Users/stslve/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin

sys.path:
	/Users/stslve/miniconda/envs/jlab-pip-2.0/bin
	/Users/stslve/miniconda/envs/jlab-pip-2.0/lib/python37.zip
	/Users/stslve/miniconda/envs/jlab-pip-2.0/lib/python3.7
	/Users/stslve/miniconda/envs/jlab-pip-2.0/lib/python3.7/lib-dynload
	/Users/stslve/miniconda/envs/jlab-pip-2.0/lib/python3.7/site-packages

sys.executable:
	/Users/stslve/miniconda/envs/jlab-pip-2.0/bin/python

sys.version:
	3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16)
	[Clang 9.0.1 ]

platform.platform():
	Darwin-18.7.0-x86_64-i386-64bit

which -a jupyter:
	/Users/stslve/miniconda/envs/jlab-pip-2.0/bin/jupyter

pip list:
	Package            Version
	------------------ -------------------
	alembic            1.4.2
	appnope            0.1.0
	async-generator    1.10
	attrs              19.3.0
	backcall           0.1.0
	bleach             3.1.4
	blinker            1.4
	brotlipy           0.7.0
	certifi            2020.4.5.1
	certipy            0.1.3
	cffi               1.14.0
	chardet            3.0.4
	cryptography       2.8
	decorator          4.4.2
	defusedxml         0.6.0
	entrypoints        0.3
	graphviz           0.8.4
	idna               2.9
	importlib-metadata 1.6.0
	ipykernel          5.2.1
	ipython            7.13.0
	ipython-genutils   0.2.0
	jedi               0.17.0
	Jinja2             2.11.2
	json5              0.9.0
	jsonschema         3.2.0
	jupyter-client     6.1.3
	jupyter-core       4.6.3
	jupyter-telemetry  0.0.5
	jupyterhub         1.1.0
	jupyterlab         2.1.1
	jupyterlab-server  1.1.1
	Mako               1.1.0
	MarkupSafe         1.1.1
	mistune            0.8.4
	mxnet              1.6.0
	nbconvert          5.6.1
	nbformat           5.0.6
	notebook           6.0.3
	numpy              1.18.3
	oauthlib           3.0.1
	pamela             1.0.0
	pandocfilters      1.4.2
	parso              0.7.0
	pexpect            4.8.0
	pickleshare        0.7.5
	pip                20.0.2
	prometheus-client  0.7.1
	prompt-toolkit     3.0.5
	ptyprocess         0.6.0
	pycparser          2.20
	pycurl             7.43.0.5
	Pygments           2.6.1
	PyJWT              1.7.1
	pyOpenSSL          19.1.0
	pyrsistent         0.16.0
	PySocks            1.7.1
	python-dateutil    2.8.1
	python-editor      1.0.4
	python-json-logger 0.1.11
	pyzmq              19.0.0
	requests           2.23.0
	ruamel.yaml        0.16.6
	ruamel.yaml.clib   0.2.0
	Send2Trash         1.5.0
	setuptools         46.1.3.post20200325
	six                1.14.0
	SQLAlchemy         1.3.16
	terminado          0.8.3
	testpath           0.4.4
	tornado            6.0.4
	traitlets          4.3.3
	urllib3            1.25.9
	wcwidth            0.1.9
	webencodings       0.5.1
	wheel              0.34.2
	zipp               3.1.0

conda list:
	# packages in environment at /Users/stslve/miniconda/envs/jlab-pip-2.0:
	#
	# Name                    Version                   Build  Channel
	alembic                   1.4.2              pyh9f0ad1d_0    conda-forge
	appnope                   0.1.0           py37hc8dfbb8_1001    conda-forge
	async_generator           1.10                       py_0    conda-forge
	attrs                     19.3.0                     py_0    conda-forge
	backcall                  0.1.0                      py_0    conda-forge
	bleach                    3.1.4              pyh9f0ad1d_0    conda-forge
	blinker                   1.4                        py_1    conda-forge
	brotlipy                  0.7.0           py37h9bfed18_1000    conda-forge
	ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
	certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
	certipy                   0.1.3                      py_0    conda-forge
	cffi                      1.14.0           py37h356ff06_0    conda-forge
	chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
	configurable-http-proxy   4.2.1           node13_he01fd0c_0    conda-forge
	cryptography              2.8              py37he655712_2    conda-forge
	decorator                 4.4.2                      py_0    conda-forge
	defusedxml                0.6.0                      py_0    conda-forge
	entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
	icu                       64.2                 h6de7cb9_1    conda-forge
	idna                      2.9                        py_1    conda-forge
	importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
	importlib_metadata        1.6.0                         0    conda-forge
	ipykernel                 5.2.1            py37h43977f1_0    conda-forge
	ipython                   7.13.0           py37hc8dfbb8_2    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	jedi                      0.17.0           py37hc8dfbb8_0    conda-forge
	jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
	json5                     0.9.0                      py_0    conda-forge
	jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
	jupyter_client            6.1.3                      py_0    conda-forge
	jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
	jupyter_telemetry         0.0.5                      py_0    conda-forge
	jupyterhub                1.1.0                    py37_2    conda-forge
	jupyterhub-base           1.1.0                    py37_2    conda-forge
	jupyterlab                2.1.1                      py_0    conda-forge
	jupyterlab_server         1.1.1                      py_0    conda-forge
	krb5                      1.17.1               h1752a42_0    conda-forge
	libcurl                   7.69.1               hc0b9707_0    conda-forge
	libcxx                    10.0.0                        1    conda-forge
	libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
	libffi                    3.2.1             h4a8c4bd_1007    conda-forge
	libsodium                 1.0.17               h01d97ff_0    conda-forge
	libssh2                   1.8.2                hcdc9a53_2    conda-forge
	libuv                     1.34.0               h0b31af3_0    conda-forge
	mako                      1.1.0                      py_0    conda-forge
	markupsafe                1.1.1            py37h9bfed18_1    conda-forge
	mistune                   0.8.4           py37h9bfed18_1001    conda-forge
	mxnet                     1.6.0                    pypi_0    pypi
	nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
	nbformat                  5.0.6                      py_0    conda-forge
	ncurses                   6.1               h0a44026_1002    conda-forge
	nodejs                    13.13.0              h38d8c5a_0    conda-forge
	notebook                  6.0.3                    py37_0    conda-forge
	numpy                     1.18.3                   pypi_0    pypi
	oauthlib                  3.0.1                      py_0    conda-forge
	openssl                   1.1.1g               h0b31af3_0    conda-forge
	pamela                    1.0.0                      py_0    conda-forge
	pandoc                    2.9.2.1                       0    conda-forge
	pandocfilters             1.4.2                      py_1    conda-forge
	parso                     0.7.0              pyh9f0ad1d_0    conda-forge
	pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
	pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
	pip                       20.0.2                     py_2    conda-forge
	prometheus_client         0.7.1                      py_0    conda-forge
	prompt-toolkit            3.0.5                      py_0    conda-forge
	ptyprocess                0.6.0                   py_1001    conda-forge
	pycparser                 2.20                       py_0    conda-forge
	pycurl                    7.43.0.5         py37h75a5311_0    conda-forge
	pygments                  2.6.1                      py_0    conda-forge
	pyjwt                     1.7.1                      py_0    conda-forge
	pyopenssl                 19.1.0                     py_1    conda-forge
	pyrsistent                0.16.0           py37h9bfed18_0    conda-forge
	pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
	python                    3.7.6           h90870a6_5_cpython    conda-forge
	python-dateutil           2.8.1                      py_0    conda-forge
	python-editor             1.0.4                      py_0    conda-forge
	python-graphviz           0.8.4                    pypi_0    pypi
	python-json-logger        0.1.11                     py_0    conda-forge
	python_abi                3.7                     1_cp37m    conda-forge
	pyzmq                     19.0.0           py37haec44b1_1    conda-forge
	readline                  8.0                  hcfe32e1_0    conda-forge
	requests                  2.23.0             pyh8c360ce_2    conda-forge
	ruamel.yaml               0.16.6           py37h9bfed18_1    conda-forge
	ruamel.yaml.clib          0.2.0            py37h9bfed18_1    conda-forge
	send2trash                1.5.0                      py_0    conda-forge
	setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
	six                       1.14.0                     py_1    conda-forge
	sqlalchemy                1.3.16           py37h9bfed18_0    conda-forge
	sqlite                    3.30.1               h93121df_0    conda-forge
	terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
	testpath                  0.4.4                      py_0    conda-forge
	tk                        8.6.10               hbbe82c9_0    conda-forge
	tornado                   6.0.4            py37h9bfed18_1    conda-forge
	traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
	urllib3                   1.25.9                     py_0    conda-forge
	wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
	webencodings              0.5.1                      py_1    conda-forge
	wheel                     0.34.2                     py_1    conda-forge
	xz                        5.2.5                h0b31af3_0    conda-forge
	zeromq                    4.3.2                h6de7cb9_2    conda-forge
	zipp                      3.1.0                      py_0    conda-forge
	zlib                      1.2.11            h0b31af3_1006    conda-forge
</pre>
</details>

<details>
<pre>
c = get_config()  # noqa

from jupyterhub.auth import DummyAuthenticator

c.JupyterHub.authenticator_class = DummyAuthenticator

from jupyterhub.spawner import SimpleLocalProcessSpawner

c.JupyterHub.spawner_class = SimpleLocalProcessSpawner

c.JupyterHub.ip = 'localhost'

c.Spawner.default_url = '/lab'

c.Spawner.cmd = ['jupyterhub-singleuser']
</pre>
</details>

**Comment by TuSKan** [comment]
I just update JupyterLab to v2.1.2 and now is working fine.
Thank you very much!
