### ISSUE TITLE
Don't Always Auto-Insert On Single Suggestion In Completer

### ISSUE THREAD

**Issue by edzkite** [jupyterlab/jupyterlab#8255]
![auto_insert](https://user-images.githubusercontent.com/47993402/79288951-f1714c00-7e7c-11ea-849c-74e7647bdda7.gif)

In instances where there's only one suggestion, JupyterLab will automatically insert the suggestion. In Kite's case, the above happens when the user types "j", forcing him or her to backspace if `json` is not the desired insertion.

As such, I'd like to add a setting to JupyterLab core to be able to control this setting. 

In addition, I'd have the extension open a notification if the setting is off, to recommend the setting be toggled off for the best experience.

**Comment by telamonian** [comment]
> In instances where there's only one suggestion, JupyterLab will automatically insert the suggestion

I'm not able to reproduce the behavior you're showing in your animation on the latest master. In fact, I don't recall jupyterlab ever having the behavior of eagerly completing on one suggestion.

Not quite sure what's going on. I don't have the kite completer set up locally, so that by itself may be the difference. It may also be that jupyterlab's default python completer effectively never has only one completion, masking this behavior.

I for one would *hate* this kind of eager completion. Given that this is not just a kite issue and is actually a jlab core issue, I feel strongly that we should have eager completion off by default

**Comment by jasongrout** [comment]
What version of jlab do you have? We had a bug in an earlier version that caused this, but I think it's been fixed recently. Do you have 2.1.0?

**Comment by edzkite** [comment]
This is a dev version of the Kite extension, hence completions are being triggered even before the ".". 

This is based off the latest in master. See https://github.com/jupyterlab/jupyterlab/blob/master/packages/completer/src/widget.ts#L245 for the root cause.

**Comment by edzkite** [comment]
I assume we put this here because it may be desirable in cases where a when a user is explicitly triggering completions, which is always the case without extensions, and there's only one result, it saves time to just insert it.

**Comment by jasongrout** [comment]
Relevant: https://github.com/jupyterlab/jupyterlab/pull/5985

**Comment by jasongrout** [comment]
I thought we didn't complete until the user explicitly pressed the completion key.

**Comment by edzkite** [comment]
With jupyterlab-lsp, it'll fetch completions automatically after the "." For instance `os.$` where "$" is the cursor.

With kite, we'll start fetching completions even after `o$`, resulting in this behavior.

**Comment by jasongrout** [comment]
I've not been following this work very closely, so my comment might be off-base - if so, please ignore. It sounds like the normal tab keypress should always signify the user's intention of applying a completion, not just that a menu should be displayed. If there is more than one completion, then clearly we have to have further action from the user to choose which completion should happen. This is a slight shift from apparently what happens now, i.e., that tab brings up the completion list, and if the completion list has one element in it, it is automatically applied.

**Comment by edzkite** [comment]
All good! What happens today with a tab keypress is that a completion is automatically applied, or a suggestions list is shown if there are multiple options, no matter what.

Now, with #5985, if you're typing while the suggestions list is active, and there's only one completion left, it suggests it, but does not automatically insert it for you, since it may not match what you actually want. This is contingent on the suggestions list being visible.

The problem with Kite, in the gif above, is that the suggestions list is not visible, and there's only one suggestion, resulting in an auto-insertion.

The real crux of the issue is that unlike JupyterLab + JupyterLab LSP, which automatically displays the suggestions list only after the ".", e.g. `json.$`, Kite needs to display the suggestions list on more potential keystrokes.

To illustrate this:
Here's a gif of the current JL + LSP behavior. I don't hit tab at all during this sequence.
![Apr-22-2020 17-37-34](https://user-images.githubusercontent.com/47993402/80046659-1179be80-84c0-11ea-8080-bfea0d331e5b.gif)

With Kite:
![auto_insert](https://user-images.githubusercontent.com/47993402/79288951-f1714c00-7e7c-11ea-849c-74e7647bdda7.gif)

**Comment by edzkite** [comment]
As an alternative, what if we registered a new [completer invocation command ](https://github.com/jupyterlab/jupyterlab/blob/master/packages/completer-extension/src/index.ts#L33)that's not tied to tab?

Then, an extension can invoke completions using this command. We'd have to modify the method signatures in handlers and widgets to propagate the invocation, but it'll allow JupyterLab to keep both the preexisting behavior of having "tab" auto-insert when there's a single completion, while also branching the behavior for other key presses, such as alphanumeric characters.

**Comment by telamonian** [comment]
To help me clarify the problem, I'm posting a summary of the issue so far. Feel free to correct

- jlab autoinserts a completion only under very specific circumstances. From https://github.com/jupyterlab/jupyterlab/pull/5985#issue-253179836:
>  1. If there is exactly one in the completion request, automatically complete with that.
>  2. If there are multiple matches, but they are filtered down to one by subsequent typing, don't complete with that unless the user explicitly selects it.

- In vanilla jlab, autoinsert **never** occurs without an explicit press of <kbd>Tab</kbd>. This is because completions are only generated on <kbd>Tab</kbd> press

- With jlab-lsp, completions will also be generated after the user types a period ("."). This means that autoinsert is possible after a <kbd>Tab</kbd> or <kbd>.</kbd> press

- With the kite extension, completions can be generated after any input (presumably there's some kind of debouncing?). This means that autoinsert can happen anywhere

**Comment by telamonian** [comment]
> while also branching the behavior for other key presses, such as alphanumeric characters.

I'd support this. I also think that we should consider what jupyterlab's default completion behavior should be, regardless of the presence/absence of any particular completer extension. One of the things that made me a user of Jupyter in the first place (back in the days of IPython Notebook) is our low-key completion behavior. Completions are there when I explicitly request them, and out of the way otherwise.

On the other hand, there's no reason why we shouldn't optionally support a more agressive completion behavior. Similar to other IDEs, we could add a "show completions as you type" option (which should default to "off", in order to preserve the current behavior).

@edzkite Does this sound feasible to you?

**Comment by edzkite** [comment]
>  1. In vanilla jlab, autoinsert never occurs during normal typing of input code. This is because completions are only generated on Tab press
> 2. With jlab-lsp, autoinsert is possible after a user enters a period (".") into an input cell. This is because completions will be generated after either a . or a Tab press
> 3. With the kite extension, completions can be generated after any input (presumably there's some kind of debouncing?). This means that autoinsert can happen anywhere

1 and 3 are correct. 

For 2, that is only true if on ".", there is only one suggestion. Otherwise, with #8395, as long as the suggestions list is visible, auto-insertion will not occur.  If the suggestions list is escaped, and then tab is pressed, auto-insertion is fair game.

> "The problem with Kite, in the gif above, is that the suggestions list is not visible..." Why is the suggestion list not visible with the kite completer, when it is visible with other completers?
#8395 prevents single suggestions from being inserted, but only if the completion widget is already visible. This works fine if the widget is shown on ".", where chances are there are many suggestions, that will be filtered down as you continue to type.

With Kite, at the point I type "j", there is only one suggestions `json`. Before the widget even has a chance to render, JupyterLab inserts it, circumventing the logic in #8395.

> Is there a technical reason why kite can't support the same "show completions only on explicit request" behavior as the default completer? Or is that simply the kite team's UX preference?

If such a setting were implemented, we'd definitely work to support it. However, the LSP extension for JupyterLab is already showing completions automatically, albeit on ".". Expanding that behavior, similar to widely used IDEs such as PyCharm, could provide a strong value add to JupyterLab users.

> The current way that jlab implements showing completions on tab would not work well for showing completions on every alphanumeric input. How is this currently implemented in the kite extension? How does your suggestion of registering a new flavor of the completer:invoke command fit in?

At a high level, the path forward in my opinion is to:
- preserve the behavior of JupyterLab core completions
- Provide hooks or a setting for extensions such as Kite or JupyterLab-LSP to enable the an experience which enables automatic completions, with the option to not auto-insert single suggestions that come from typing.

Other IDEs such as Atom and VSCode provide a distinction between automatic completions and manual completions. For manual completions, auto-inserting single suggestions makes more sense, since you are explicitly asking for a completion, but not so much for automatic completions that are generated whilst typing.

Unfortunately, for extensions that wish to invoke the completer automatically, the request message used is the same as if the user manually entered tab. This makes it difficult to differentiate behavior between completions generated via typing and completions generated by an explicit user request (tab).

**Comment by krassowski** [comment]
I support @edzkite's approach. Implementation wise I was thinking about adding `completer:trigger` command (as to complement invoke, see https://github.com/krassowski/jupyterlab-lsp/pull/264) or adding an argument to `completer:invoke` command (#8406).

Also cross-referencing #6999.

**Comment by echarles** [comment]
I read this conversation and tried to understand the issue and expected solution. Therefor I done a few completion tests shown hereafter.

JupyterLab Built-In Completer

![jlab-builtin](https://user-images.githubusercontent.com/226720/83117459-61eec800-a0cd-11ea-965a-8553689cd277.gif)

JupyterLab with @krassowski/jupyterlab-lsp

![jlab-krassowski](https://user-images.githubusercontent.com/226720/83117533-792db580-a0cd-11ea-81e7-23664d7db98a.gif)

I wanted also to try with Kite Completer but came to open https://github.com/kiteco/jupyterlab-kite/issues/14

It would be great if one could confirm the behavior shown on the screencasts correctly reflect current master state and also point to the fix we need to address (I have a rough idea from the above comments but would be great to double-confirm). I will then be happy to test and review https://github.com/jupyterlab/jupyterlab/pull/8375

**Comment by edzkite** [comment]
@echarles 
Here are some screen caps with the same test cases as above. This is the Kite extension, without the PR I opened (#8375):

![not_fixed](https://user-images.githubusercontent.com/47993402/83190937-185fa680-a0e8-11ea-8ae7-918705c534ca.gif)

And this is the Kite extension with the PR:

![fixed](https://user-images.githubusercontent.com/47993402/83190947-1dbcf100-a0e8-11ea-9c4e-cac9f6197d3e.gif)

**Comment by echarles** [comment]
Thx @edzkite. These test cases clarifie the issue that needs to be addressed. I will now look at https://github.com/jupyterlab/jupyterlab/pull/8375 and ensure that the changes do not bring any regression to the built-in JupyterLab completer.
