### ISSUE TITLE
Internationalization for JupyterLab

### ISSUE THREAD

**Issue by FungluiKoo** [jupyterlab/jupyterlab#8256]
Hey everyone, I'm wondering if JupyterLab has a plan for releasing versions in languages other than English. I think there are increasingly more people using JupyterLab who come from non-English countries. So it'd be great to have that.

**Comment by jasongrout** [comment]
We would love to have internationalization support. At this time, we don't have the bandwidth or experience among the developers to do it, though, so we'd welcome community participation to make it happen. The first step, I think, is to research and adopt a system where such translations can be contributed and influence the ux.

**Comment by jasongrout** [comment]
Let's move this conversation over to #3965 to keep it in one place, though. Thanks!

**Comment by FungluiKoo** [comment]
Thanks :)
