### ISSUE TITLE
Adding a visual clue for distinguishing hidden files and folders in the file browser window

### ISSUE THREAD

**Issue by woswos** [jupyterlab/jupyterlab#8257]
Hello, it's me, @amad-a, @quangIO, and @FungluiKoo again.

We have a small suggestion for improving the file browser in the UI. Currently, when we start the JupyterLab via `jupyter lab --dev-mode --ContentsManager.allow_hidden=True`, we see that all files look the same. There is no visual clue for distinguishing hidden files and folders. 

For example in MacOS, hidden files and folders are grayed out:
<img width="761" alt="Screen Shot 2020-04-22 at 5 38 43 PM" src="https://user-images.githubusercontent.com/10498874/80037639-f60fb300-84c1-11ea-91a7-75e1fa574249.png">

Similarly, we suggest changing the opacity of the hidden files and folders. The one on the left is the current behavior, and the one on the right is our suggestion:
<img width="794" alt="Screen Shot 2020-04-22 at 5 44 57 PM" src="https://user-images.githubusercontent.com/10498874/80037630-f27c2c00-84c1-11ea-947b-a5b48363fe90.png">

Additionally, we are aware that people are already working on adding an option to display hidden files in the file browser (#2049). So, our suggestion can be a good addition to the improvement mentioned in #2049.

**Comment by jasongrout** [comment]
I like it, as long as the contrast is still great enough to pass accessibility guidelines.

**Comment by woswos** [comment]
I found [this repository](https://github.com/jupyter/accessibility), but I couldn't find anything related to the contrast of the UI. Do you have a link to the accessibility guidelines?

**Comment by jasongrout** [comment]
> I found [this repository](https://github.com/jupyter/accessibility), but I couldn't find anything related to the contrast of the UI. Do you have a link to the accessibility guidelines?

@tgeorgeux?

**Comment by tgeorgeux** [comment]
@woswos I typically use [this website](https://webaim.org/resources/contrastchecker/) to check and aim (no pun intended) for AAA contrast.

**Comment by woswos** [comment]
@tgeorgeux actually the current icons don't pass AAA contrast test for the normal text size:
<img width="733" alt="Screen Shot 2020-04-23 at 11 50 19 PM" src="https://user-images.githubusercontent.com/10498874/80173249-3d2e9e80-85bd-11ea-91e7-d9c26774ccbe.png">

So, making the icons even more faded would fail the rest of the tests as well. I have a new suggestion. We can keep using the same gray but with different icons:
<img width="794" alt="80037630-f27c2c00-84c1-11ea-947b-a5b48363fe90 copy" src="https://user-images.githubusercontent.com/10498874/80176949-2a6d9700-85c8-11ea-802c-5ce9b14a4f3f.png">

What do you think? I personally like the initial suggestion we made more than this one. However, the contrast ratio would be an issue with the initial suggestion.
