### ISSUE TITLE
Improvements to the installation steps in the README and CONTRIBUTING files

### ISSUE THREAD

**Issue by woswos** [jupyterlab/jupyterlab#8259]
These suggestions might sound very obvious and/or trivial to an experienced developer, but these were the issues that I needed to solve as a beginner to install the development environment. I am willing to contribute to making these changes happen but I wanted to get your feedback and thoughts first.

#### README file
There is a warning about adding the user-level bin directory to the `PATH` environment variable but figuring out how to do it wasn't easy. I think having a command example like `export PATH="/home/<your-username>/.local/bin:$PATH"` as a part of that warning would be helpful for nonadvanced users and contributors.

I know the exact method for updating the `PATH` changes depending on the OS and shell environment, but at least giving an example might help users to figure out the equivalent operation for their setup.

#### CONTRIBUTING file
Apparently, we need to install JupyterLab first and then proceed with the installation for the development environment. I expected the JupyterLab installation to be a separate step, but it wasn't there, and I wasn't sure about the exact order. I think mentioning the correct order under the "Setting Up a Development Environment" section would be useful. 

I also realized that the `jlpm` package manager is installed with JupyterLab but not with Jupyter Notebook. So, having JupyterLab installed first is essential for running the `jlpm install` command as a part of the development environment installation.

Finally, I observed that Python 3+ is a must for installing the packages for the development environment since not all packages are available for older Python versions. However, this is not communicated in any part of the CONTRIBUTING file. I think having it in the preamble might be useful as well.

**Comment by blink1073** [comment]
Hi @woswos, thank you for the valuable feedback from the perspective of an on-boarder.   Are you available to make PR with some of these changes?

**Comment by woswos** [comment]
Yes, I will make a PR with these changes.

**Comment by woswos** [comment]
I just saw issue #7151 and it seems to be reporting the issue I mentioned in the first part of my issue. So, I linked it to my PR as well. I will make a separate PR for the CONTRIBUTING file.

**Comment by woswos** [comment]
@blink1073 Thank you for merging the PRs!

**Comment by woswos** [comment]
@blink1073 I just realized that I need to update the website and documentation as well. I will update readthedocs documentation through [this file](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/getting_started/installation.rst) on this repository, but I am not sure about how the update the [instructions on the Project Jupyter website](https://jupyter.org/install). 

I think updating these is even more important since the beginners might try to install by using these pages.

**Comment by blink1073** [comment]
The `jupyter.org` page is [here](https://github.com/jupyter/jupyter.github.io/blob/master/install.md), you'd have to make a PR in that repo.  Thanks again for taking this on!

**Comment by woswos** [comment]
thank you!
