### ISSUE TITLE
JupyterLab and IPython in combination with jupyterhub creating too many OS threads

### ISSUE THREAD

**Issue by pkvprakash** [jupyterlab/jupyterlab#8262]
## Description

JupyterLab and IPython in combination with jupyterhub creating too many OS threads. This issue is very similar to the issue reported in #7149. In that thread (https://github.com/jupyterlab/jupyterlab/issues/7149#issuecomment-536212005) @robnagler says the issue fixed with a change in configuration. What configuration I have to change to fix the issue? 

## Context

- Operating System and version: RHEL 7
- Browser and version: 
- JupyterLab version: 1.1.0
- Python : 3.7

**Comment by robnagler** [comment]
@pkvprakash I adjusted our configuration to not run so many users on a single machine. This means we stay under the kernel limit.

**Comment by pkvprakash** [comment]
Thank you @robnagler
