### ISSUE TITLE
Empty fields in context.model.metadata.toJSON()

### ISSUE THREAD

**Issue by nscozzaro** [jupyterlab/jupyterlab#8276]
I'm working on a JupyterLab extension that leverages the notebook extension. I want to save a new field to the ipynb metadata section, but it's not working because `this.context.model.metadata.toJSON()` isn't behaving as I expect: it returns empty fields for "language_info" and "kernel_spec". Executing `context.model.metadata.set(...)` saves my new field to the metadata, and I can see it in the saved file. However, it also doesn't show up when I run `this.context.model.metadata.toJSON()`. 

What the ipynb metadata section looks like when I open it in an editor:
![image](https://user-images.githubusercontent.com/15185105/80260887-e9709380-8656-11ea-9367-fd593b839243.png)

What I get in the javascript console when I run `this.context.model.metadata.toJSON()`: doesn't match above, as I would expect.  
![image](https://user-images.githubusercontent.com/15185105/80260784-a9a9ac00-8656-11ea-9abc-3739ded41fde.png)

**Comment by jasongrout** [comment]
Can you double check that you have the right model? Does `this.context.model` match the notebook you intend to modify?

**Comment by nscozzaro** [comment]
The issue was that I was trying to use it without `this.context.ready.then(() => {...})`. Placing it inside that context ready call like `this.context.ready.then(() => {this.context.model.metadata.toJSON()})` solved the issue for me.
