### ISSUE TITLE
Jupyterlab memory limit warning with nbresuse

### ISSUE THREAD

**Issue by Gsbreddy** [jupyterlab/jupyterlab#8280]
Hi all,
I have been using the nbresuse for a week now. Everything is working fine in notebook but not in the case of jupyter-lab.
In the lab, I am able to see the memory getting displayed in status bar but when the memory crosses the mem_limit it doesn't show up warning(red colour). In notebook I can see red colour but not in Lab.

I need to know if the warning feature (showing red colour on crossing mem_limit) works/enabled in the status bar for jupyterlab.

Please help me with this information. Thanks for any inputs.
https://github.com/yuvipanda/nbresuse/issues/37

**Comment by jtpio** [comment]
> I need to know if the warning feature (showing red colour on crossing mem_limit) works/enabled in the status bar for jupyterlab.

The memory usage status bar item in JupyterLab only shows the amount of memory being used by the notebook server process (and the limit if set), but it doesn't show a red color warning:

![image](https://user-images.githubusercontent.com/591645/80348444-1a76e100-886e-11ea-9e92-b88bdb1dd65e.png)

**Comment by Gsbreddy** [comment]
Thanks fo the answer. Any work in progress to enable this?

**Comment by jtpio** [comment]
Probably not (no open PR at the moment). However this could be added to the `render` logic in:

https://github.com/jupyterlab/jupyterlab/blob/4e7b44606630e08ac215ebb3c2e1b8945f6407a9/packages/statusbar/src/defaults/memoryUsage.tsx#L30-L47

As an alternative you might want to check out this extension, which also uses `nbresuse` as the metrics backend: https://github.com/jtpio/jupyterlab-system-monitor

**Comment by Gsbreddy** [comment]
Great! I will check that extension. Thanks.

**Comment by Gsbreddy** [comment]
I have implemented code for this. If the current memory usage(903.88MB) goes beyond the max memory limit(if set, here its 218.86MB), then we show a warning (make mem background red). If this looks fine, I will raise a PR.

![image](https://user-images.githubusercontent.com/7725109/81661408-b5b8aa80-9459-11ea-80c1-110cfd9e01b9.png)

**Comment by jtpio** [comment]
Nice, thanks!

Wondering about two things:

- should the background or the color of the text be red?
- maybe the indicator should use the `mem_warning_threshold` parameter (if it is available in the metrics response), just like the classic notebook extension? https://github.com/yuvipanda/nbresuse#memory-usage-warning-threshold

**Comment by Gsbreddy** [comment]
1. I feel background and the text both should be red since that's the default behavior for vanilla notebook.
https://github.com/yuvipanda/nbresuse/blob/bfffb680712ba3e194fad759376c2e144ef12328/nbresuse/static/main.js#L19

![image](https://user-images.githubusercontent.com/7725109/81674665-2e743280-946b-11ea-96ae-566c8fae8bf3.png)


2. `mem_warning_threshold`  is not part of `/metrics`. So we can't leverage that value.
```{
  "rss": 1138876416,
  "limits": {
    "memory": {
      "rss": 1229496297,
      "warn": true
    },
    "cpu": {
      "cpu": 2.0,
      "warn": false
    }
  },
  "cpu_percent": 0.3,
  "cpu_count": 8
}```

**Comment by Gsbreddy** [comment]
Does this answer your questions @jtpio ? If yes, may I raise a PR for the same.
Thanks.

**Comment by jtpio** [comment]
Thanks @Gsbreddy for investigating.

>  `mem_warning_threshold`  is not part of `/metrics`. So we can't leverage that value.

But `warn` seems to be part of the response? Maybe we should read that value and if it is `true` show the warning? (the classic notebook extension [seems to be doing that](https://github.com/yuvipanda/nbresuse/blob/dd2d21c0832cd7d8e41b91b2e8782e8eda11464b/nbresuse/static/main.js#L38-L42))

**Comment by Gsbreddy** [comment]
Yes I’m making that change and raising a PR.
Thanks for all the inputs.

**Comment by jtpio** [comment]
Awesome, thanks for taking the time to look into it!

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/8437
