### ISSUE TITLE
How to reset the layout when the file title went away somehow?

### ISSUE THREAD

**Issue by DawnEve** [jupyterlab/jupyterlab#8286]
## Description
After installation, jupyterlab was normal for a while, but after a few key presses or clicks(I can't tell clearly) today, I sudenly found the file name tag on top went away, I tried to restore the layout, but failed.

## Reproduce
I can't undo this, nor do this again.
Even after rerun jupyterlab, the missing header layout remained.

## Expected behavior
I hope each file should have a tag, at the top of its file when editing.

## Context
Welcome to Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-74-generic x86_64)
Browser: Chrome  79.0.3945.117;
$ jupyter-lab --version
0.27.0

![FileName](https://user-images.githubusercontent.com/5974903/80377341-ba178c00-88cd-11ea-86a1-39849163b261.png)

**Comment by jasongrout** [comment]
Go to the View menu and toggle the "Single-Document Mode". This was designed as a kind of "zen mode" where you could just concentrate on a single document and hide everything else.

We should really have a status bar item when single-document mode is on that lets you toggle it off in a more user-discoverable way.

**Comment by jasongrout** [comment]
Or perhaps we should remove the default keyboard shortcut, and let people assign their own keyboard shortcut to it if they wish.

**Comment by jasongrout** [comment]
I've made my suggestions #8292, so closing this as answered.

**Comment by DawnEve** [comment]
> Go to the View menu and toggle the "Single-Document Mode". This was designed as a kind of "zen mode" where you could just concentrate on a single document and hide everything else.
> 
> We should really have a status bar item when single-document mode is on that lets you toggle it off in a more user-discoverable way.

In fact, this version doesnot have a View menu, as the screenshort shown before.
I used your keyword "Single-Document Mode" to find the keybord shortcut "ctrl+shift+enter" to recover back. But before knowing this hint, I searched, but failed to find an answer.

Thank you for your perfect job
