### ISSUE TITLE
Session name not updated in notebook server if user change file name when slow kernel is starting

### ISSUE THREAD

**Issue by zuoyuanh** [jupyterlab/jupyterlab#8289]
## Description
After user open a notebook it will immediately call the session api to start a new session (https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/sessioncontext.tsx#L756-L761) and then wait for the kernel to be started. In this request, the initial filename as name and UUID as path is sent to jupyter server.

If user rename a file, since at this time the session is not ready and the `session` property in `SessionContext` is null, it will not make PATCH request to update the session name and path (https://github.com/jupyterlab/jupyterlab/blob/master/packages/docregistry/src/context.ts#L418)

After the kernel is launched, the session is created. In `ClientSession` it calls `setPath` to the newly-created session explicitly, which make a PATCH request to jupyter server to update the path of the session in db (https://github.com/jupyterlab/jupyterlab/blob/master/packages/apputils/src/sessioncontext.tsx#L769, https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/session/default.ts#L237). Therefore the path is updated to the latest, but the name is never updated in the jupyter server db for the new session. When we call the `api/sessions` to list all running sessions we got the updated path name and old name.

The reason why the name is up-to-date after the kernel is started is because at this time we have the session so the `session` property in `SessionContext` is not null. Therefore docRegistry will call `setName` in session, which will make a PATCH request to update the filename on jupyter server.

It can be solved by calling `setName` on session after it is created.

## Reproduce

1. From Launcher create a new notebook. Make sure it is using a slow-starting kernel.
2. When the kernel is starting, rename the notebook.
3. After the kernel is started, call the `/api/sessions` to list running sessions. You will see that the name is not updated for the session of the new notebook.

**Comment by blink1073** [comment]
Fixed by #8290 and #8291
