### ISSUE TITLE
Better affordance/discoverability for single-document mode

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8292]
From time to time, people have accidentally stumbled into single-document mode and have been really confused about what happened and how to exit it (for example, see #8286). I suggest we:

1. Remove the default keyboard shortcut. It seems that people mostly stumble into it by accidentally pressing the default keyboard shortcut. Perhaps we rely on a menu item by default, and document how to set up a shortcut if desired.
2. Add a status bar item when in single-document mode. Clicking on the item could exit single-document mode. The purpose here is to make it more obvious when you've stumbled into the mode and give something you can click on to get out of it.

**Comment by telamonian** [comment]
I'm not crazy about 1. (it would help to know how many people currently use single-document mode/the shortcut), but I think 2. is a really good idea. The current UI is a bit too cryptic

**Comment by blink1073** [comment]
How to show the name of the document in Mobile mode was discussed in #8456

**Comment by jasongrout** [comment]
@ellisonbg - can you take a look at this? We're very, very close to a release this week, and it would be great if the new single-document mode was more visible.

For reference, we've discussed having a toggle on the right of the menu bar, something like:

<img width="682" alt="Screen Shot 2020-09-29 at 5 51 01 AM" src="https://user-images.githubusercontent.com/192614/94560691-da020180-0217-11eb-8a9d-63c840c683ed.png">
