### ISSUE TITLE
Tests are no more run when launching examples test suite?

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#8296]
[1] I am not sure of this, but when I run `yarn build:examples && yarn test:examples`, each of the examples server are started and then then the `chrome-test.js` node process that should be launched by `browser_check.py` is not more launched. This can be seen on e..g. [this recent CI job run](https://github.com/jupyterlab/jupyterlab/pull/8246/checks?check_run_id=617262714). You can see the log prints `Test Complete` directly without running any node.js test.

```
        http://127.0.0.1:8888/foo/?token=f84acc7f113f952cffc29e713cb3ff7464c2187097dc4545
     or http://127.0.0.1:8888/foo/?token=f84acc7f113f952cffc29e713cb3ff7464c2187097dc4545
[I 03:15:15.357 NotebookTest] Test Complete
[I 03:15:15.357 NotebookTest] Exiting normally
[I 03:15:15.357 NotebookTest] Stopping server...
[I 03:15:15.360 NotebookTest] Shutting down 0 kernels
```

If I rollback the changes of `browser_check.py` from https://github.com/jupyterlab/jupyterlab/pull/8169 which launches the node process in a async way, the node.js tests are launched.

[2] This brings to another potential issue: related to my work to run JupyterLab on Jupyter Server, I have rolled back `browser_check.py` which runs the examples tests, and with that, GitHub Actions complains with, see https://github.com/jupyterlab/jupyterlab/pull/7416/checks?check_run_id=623423988

```
Error: Failed to launch the browser process!
/opt/hostedtoolcache/Python/3.8.2/x64/share/jupyter/lab/example_test/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
```

It looks that chromium can not be launched due to a missing linux library.

@blink1073 @jasongrout  Let's first confirm [1] (if confirmed, I can open a separated issue for [2]).

**Comment by blink1073** [comment]
Yikes, good catch!  I can confirm [1].  [2] is handled in master by https://github.com/jupyterlab/jupyterlab/pull/8249.

**Comment by echarles** [comment]
@blink1073 I already had that commit but I have pulled latest master to be sure. When I run `yarn test:examples` and explicitly add an wrong statement in the `run_browser` method, or just remove the `chrome-test.js` file, the test claims to be run successfully, which makes me think the `run_browser` method is not executed.

```
async def run_browser(url):
    """Run the browser test and return an exit code.
    """

    asdf # Explicitely fail...

    target = osp.join(get_app_dir(), 'browser_test')
    if not osp.exists(osp.join(target, 'node_modules')):
        os.makedirs(target)
        await run_async_process(["jlpm", "init", "-y"], cwd=target)
        await run_async_process(["jlpm", "add", "puppeteer@^2"], cwd=target)
    shutil.copy(osp.join(here, 'chrome-test.js'), osp.join(target, 'chrome-test.js'))
    await run_async_process(["node", "chrome-test.js", url], cwd=target)

```

**Comment by echarles** [comment]
Adding a print statement is not show on the console, and the process exits directly when the server is launched (I was used to have some seconds for the node test to complete).

```
async def run_browser(url):
    """Run the browser test and return an exit code.
    """
    print('Hello, this is me...')
    target = osp.join(get_app_dir(), 'browser_test')
    if not osp.exists(osp.join(target, 'node_modules')):
        os.makedirs(target)
        await run_async_process(["jlpm", "init", "-y"], cwd=target)
        await run_async_process(["jlpm", "add", "puppeteer@^2"], cwd=target)
    shutil.copy(osp.join(here, 'chrome-test.js'), osp.join(target, 'chrome-test.js'))
    await run_async_process(["node", "chrome-test.js", url], cwd=target)
```
