### ISSUE TITLE
Jupyterlab 2.0.1 editor cannot access disk (Mac)

### ISSUE THREAD

**Issue by compleathorseplayer** [jupyterlab/jupyterlab#8299]
## Description

Standard installation from Conda

All seems fine (console works, etc.), but I cannot open from or save files to disk.

## Reproduce

1. Start the lab
2.  files from working directory are displayed, but clicking on them does not work, nor does 
Open from path...
[All else seems OK]

[By the way files I'm trying to access were created before and do not, in themselves, have permission issues - they do not need to be accessed as root.

This is such a shame, as jlab looks so promising but obviously still has a long way to go.

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
Can you fill out the rest of the context section of the issue template, for example, the jlab, browser, and os versions, outputs of the browser javascript console and server, etc.?
