### ISSUE TITLE
Allow for resizeable Dialogs

### ISSUE THREAD

**Issue by vabarbosa** [jupyterlab/jupyterlab#8300]
A possible UI improvement for Dialogs would be the ability to resize them.

In some cases, the size of the content being added into a Dialog is not easily known or can vary so trying to specify a preset/fixed size can be difficult. This can result in a widely oversized Dialog or a Dialog with messages that are hard for the user to completely read.

A possible solution for this would be to make the Dialog resizeable by including a resize handle that the user can drag to resize the dialog accordingly.

This comes from [an enhancement request in the Elyra project](https://github.com/elyra-ai/elyra/issues/426). And it may be better addressed directly in Jupyter Lab.

If this is a welcomed idea and worth investigating for Jupyter Lab, I can take on this issue to work on it.

**Comment by blink1073** [comment]
Hi @vabarbosa, yes, this contribution would be welcome!

**Comment by jasongrout** [comment]
Fixed by #8301. Thanks again!
