### ISSUE TITLE
Test Modernization Follow ups

### ISSUE THREAD

**Issue by telamonian** [jupyterlab/jupyterlab#8327]
From https://github.com/jupyterlab/jupyterlab/pull/8319#discussion_r417498943

@telamonian
> Can we give this debug config a more descriptive name, maybe "Attach to Jest test"? vscode allows comments in these json files, so we may also want to include detailed inline instructions on exactly how to spin this debug job up. I assume it's:
> 
>     * `jlpm test:debug:watch`
> 
>     * run this debug job in vscode

@blink1073 
> I like it, but as a single sweep after the migration is complete. Mind opening an issue?

**Comment by blink1073** [comment]
Adding to this other tasks once 8346 is merged:

- [ ] Use jest linter
- [ ] Add coverage handling
- [ ] Add tests for mock classes - at least hit each function
- [ ] Update contributing.md with new instructions (and a vscode screen shot)
- [ ] Update CI scripts
- [ ] Deprecate the python-based jest and karma functions
- [ ] Remap `jest-config-new.ts` to `jest-config.ts`
- [ ] Update our package template

**Comment by blink1073** [comment]
All set!  I opened #8361 to track adding tests to testutils.
