### ISSUE TITLE
Prompt for file name when creating new file from the launcher

### ISSUE THREAD

**Issue by jlumpe** [jupyterlab/jupyterlab#8334]
## Description

This is a relatively minor annoyance, but aside from when I am creating a scratch notebook (~25% of the time) when creating a new `.ipynb` or other file my very next action is always to go to the filesystem sidebar and rename it to something more descriptive. I suspect this is true for many other users.

## Reproduce

Create a new file from the Launcher tab, by clicking an item in the "Notebooks" section or the "Text File" or "Markdown File" items.

## Expected behavior

A dialog pops up prompting for a file name. The text box is pre-filled with the default value (`Untitled<n>.<ext>`) so one just has to hit enter to skip it and use the current behavior. The text is also selected (file name only for definite file types, including extension new text files) so one can immediately type the name and hit enter.

**Comment by ggbhat** [comment]
It is good to have feature. I feel it will be an good improvement to UX .

**Comment by jasongrout** [comment]
Let's consolidate this discussion over to #5207, where this is discussed in greater detail.
