### ISSUE TITLE
Line misalignment in menu bar

### ISSUE THREAD

**Issue by Yuan-Meng** [jupyterlab/jupyterlab#8336]
The horizontal lines in my Jupyter Lab menu bar are all misaligned like this:

<img width="407" alt="Screen Shot 2020-04-30 at 5 00 25 PM" src="https://user-images.githubusercontent.com/21133947/80770288-b588e880-8b04-11ea-877a-4245b2c60b62.png">

The only two things I did before having this issue was:
- Running `pyLDAvis.display()`
- Installing an extension (I can't remember which one exactly but below is the full list)

```
JupyterLab v2.1.1
Known labextensions:
   app dir: /Users/apple/opt/miniconda3/share/jupyter/lab
        @bokeh/jupyter_bokeh v2.0.1  enabled  OK
        @deathbeds/jupyterlab-font-anonymous-pro v1.0.0  enabled  OK
        @deathbeds/jupyterlab-font-dejavu-sans-mono v1.0.0  enabled  OK
        @deathbeds/jupyterlab-font-fira-code v1.0.0  enabled  OK
        @deathbeds/jupyterlab-fonts v1.0.1  enabled  OK
        @finos/perspective-jupyterlab v0.4.8  enabled  OK
        @ijmbarr/jupyterlab_spellchecker v0.1.6  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/celltags v2.1.1  enabled  OK
        @jupyterlab/debugger v0.2.0  enabled  OK
        @jupyterlab/github v2.0.0  enabled  OK
        @jupyterlab/latex v2.0.0  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @karosc/jupyterlab_dracula v2.0.3  enabled  OK
        @krassowski/jupyterlab_go_to_definition v1.0.0  enabled  OK
        jupyterlab-theme-toggle v0.5.0  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK
        sophon-notebook-htmlviewer-extension v1.0.2  enabled  OK
```

Let me know if there's any more information I should provide. Thanks!

**Comment by jasongrout** [comment]
That is very odd. Can you try to narrow the problem down, either by disabling some extensions to figure out what extension is causing this, or by seeing if it is the pyLDAvis code, or by inspecting the html there to give a clue about what might be affecting the html or css?

**Comment by jasongrout** [comment]
pyLDAvis.display is known to cause problems in JupyterLab. See https://github.com/bmabey/pyLDAvis/issues/162 for example.
