### ISSUE TITLE
Graphics are amateurishly documented

### ISSUE THREAD

**Issue by myRandomFiles** [jupyterlab/jupyterlab#8337]
The pathetically amateurish documentation for matplotlib makes Jupyterlab / Python non-competitive with Mathematica, Maple, and many more. Who the f has time to suffer through amateurish documentation when graphics with better documentation has been available for half a century. Who the fuck release shit like that. No one I never want to work with.

**Comment by jasongrout** [comment]
We invite you to open an issue in matplotlib that is considerate and respects their contributions. Even better, we invite you to contribute and help make things better!

Please see the [Code of Conduct](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md) for guidelines for how to interact with the community respectfully.

**Comment by ivanov** [comment]
Hi @myRandomFiles,

The tone of your issue is inappropriate, non-constructive. If you would like to participate in a constructive manner, have a read through the [Code of Conduct](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md).

**Comment by myRandomFiles** [comment]
> we invite you to contribute and help make things better!

I don't accept invitations to work with people who release undocumented API's.

**Comment by ivanov** [comment]
> I don't accept invitations to work with people who release undocumented API's.

And we don't accept abusive and toxic behavior. Your current behavior is unacceptable and will not be tolerated.

**Comment by myRandomFiles** [comment]
> > I don't accept invitations to work with people who release undocumented API's.
> 
> And we don't accept abusive and toxic behavior. Your current behavior is unacceptable and will not be tolerated.

I heard you. My second post omitted profanity and insults. It's a true fact about the assignments a accept and reject, though, that I don't work with people who release undocumented API's.

I could have given you two days of my time, but instead matplotlib released an undocumented API, and I wasted the two days trying to use their library. So the two days of help you could have had from me are gone forever. This is a fact about releasing undocumented API's. If you can't handle that fact, that's your issue.
