### ISSUE TITLE
Expose FileBrowserModel refresh() api

### ISSUE THREAD

**Issue by dhuebner** [jupyterlab/jupyterlab#834]
In my JL plugin I'm using IContents.IManager to create files. I would like to refresh the FileBrowser model afterwards.
I found any service to do the refresh. The current workaround is to downcast  the IPathTracker to FileBrowserModel and call refresh. All the FileBrowserModel functions are very interesting especially the fileChanged API.
Are there plans to provide a service to access the very helpful filebrowser plugin API?

**Comment by ellisonbg** [comment]
We actually ran into this somewhere else in the code base recently. I think we should expose some of the file browser API at the plugin level.

@blink1073 @afshin
