### ISSUE TITLE
Exposing local terminal to docker JupyterLab terminal

### ISSUE THREAD

**Issue by nmajin** [jupyterlab/jupyterlab#8340]
I am trying to use my local terminal commands inside of the docker JupyterLab container terminals but I cannot find any documentation on how to do this.

For example, I would like to interact with a minikube cluster installed on my laptop via kubectl commands within the JupyterLab terminal. Is there any way to do this?

**Comment by jasongrout** [comment]
It sounds like this is more of a docker question, right? Are you asking if you can interact with the host system from within a docker container's terminal?

**Comment by nmajin** [comment]
> It sounds like this is more of a docker question, right? Are you asking if you can interact with the host system from within a docker container's terminal?

Correct, and it just occurred to me using this container for the first time. Usually I want to be segmented from my host system but in this case I wanted to use this tool with existing CLIs and also hook into a k8s cluster  on my host to interact with from the container.
