### ISSUE TITLE
Consolidate Contributing Guides

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8347]
## Description
Right now our contributing guides are split between [CONTRIBUTING.md](https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md) and [docs/source/developer/contributing.rst](https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/developer/contributing.rst).   They have some differing content, but both have a "Writing Documentation" section.  I propose that `CONTRIBUTING.md` points directly to `contributing.rst` and move all content to `contributing.rst`.

**Comment by nathanrpage97** [comment]
I'm open to working on this addition.

**Comment by blink1073** [comment]
Thanks @nathanrpage97, please do!

**Comment by blink1073** [comment]
Fixed in #8373.  Thanks @nathanrpage97!
