### ISSUE TITLE
Jupyterlab icon and specific tab 

### ISSUE THREAD

**Issue by JTebeka** [jupyterlab/jupyterlab#8348]
Hi, 
my question is simple. Is it possible to : 
1) launch jupyterlab in a specific tab and not with all my previous opened tabs 
2) have a icon to launch it instead of going to anaconda to launch it (and put it in my dock)

It will be great if I can do this and easier to launch and to use...(instead of launching Anaconda and then JupyterLab)

I am on macOS Catalina 10.15.4 with Safari

Thanks

**Comment by telamonian** [comment]
This is exactly what I wrote [telamonian/jupyter-app](https://github.com/telamonian/jupyter-app) for

**Comment by telamonian** [comment]
So the short answer is that no, we don't support this in core JupyterLab, but there are a bunch of projects that wrap JupyterLab with a normal looking app

**Comment by vidartf** [comment]
> launch jupyterlab in a specific tab and not with all my previous opened tabs

Yes, you can add `?reset` to browser URL to clear out you workspace (see https://jupyterlab.readthedocs.io/en/stable/user/urls.html#resetting-a-workspace for details).

> have a icon to launch it instead of going to anaconda to launch it (and put it in my dock)

If your platform supports creating icons that will open a link in your browser, you should be able to point to this, but it will still require your lab server to be running somewhere. If you also want to start it, than Max' answer is the way to go.
