### ISSUE TITLE
Markdown table alignment specifications should be respected

### ISSUE THREAD

**Issue by deanwampler** [jupyterlab/jupyterlab#8349]
# Description

The default right-alignment is fine for data, but nothing else. It effectively means that tables can't be used for laying out text, greatly diminishing the value of notebooks for tutorials and other text-heavy content where tabular layout would be desirable. 

I know there have been other issues reported for this, but I'm creating a new issue because the current behavior means the convenience and utility of Jupyter Lab is reduced. I'll have to reconsider the decision to use Jupyter Lab for my tutorial development. I'm sure I'm not alone.

## Reproduce

Any markdown table with alignment specified:

| Head 1 | Head 2 |
| :------ | :------: |
| Some text that looks best left-aligned |  centered looks fine | 

## Expected behavior

Left- and center-aligned table content...

## Context

- Operating System and version: MacOS Catalina
- Browser and version: Chrome 81.0.4044.129, Safari 13.1, Firefox 75.0
- JupyterLab version: 1.2.6 (Conda install)

<details><summary>Troubleshoot Output</summary>
<pre>
...
	html5lib                  1.0.1                    py37_0
...
	markdown                  3.1.1                    pypi_0    pypi
	markupsafe                1.1.1            py37h1de35cc_0
...
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
N/A
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
N/A
</pre>
</details>

**Comment by jasongrout** [comment]
This code:

```markdown
| Head 1 | Head 2 |
| :------ | :------: |
| Some text that looks best left-aligned |  centered looks fine | 
```
looks like this in JupyterLab 2.1 for me:

<img width="447" alt="Screen Shot 2020-05-05 at 3 30 06 AM" src="https://user-images.githubusercontent.com/192614/81057148-bca35400-8e80-11ea-85a5-0a3169883659.png">

So it seems like it is fixed in 2.1. Please let us know if it isn't working for you in JupyterLab 2.1.
