### ISSUE TITLE
Is there any code hinting plugin for .py files?

### ISSUE THREAD

**Issue by HorieYuan** [jupyterlab/jupyterlab#8350]
Is there any code hinting plugin for .py files? 🤔

**Comment by jasongrout** [comment]
There is some basic autocomplete in base JupyterLab. There is also https://github.com/krassowski/jupyterlab-lsp and some new development work in the completion framework to interface with Kite, which would be another community extension.

Closing as answered, but feel free to continue the conversation if you wish.
