### ISSUE TITLE
Index not displaying with default dataframe display.

### ISSUE THREAD

**Issue by jameskyle** [jupyterlab/jupyterlab#8351]
## Description

When using the default Dataframe display in Jupyter Lab, the index is not show. Even when the dataframe's display style is set to true for indexes.

## Reproduce

1. Open Lab
2. Create dataframe
3. Shift+Enter with df as last item.
4. Index is not displayed.

Notice the lack of the index labels.

![image](https://user-images.githubusercontent.com/8234/80828203-b455cb00-8b99-11ea-90e1-e41862f6a66d.png)

## Expected behavior

The index should be displayed by default.

## Context

- Operating System and version: MacOS Catalina
- Browser and version: Chrome 81.0.4044.129
- JupyterLab version: 0.33.11
- Hosted Notebook, not local.

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.

$PATH:
        /usr/local/bin
        /home/udocker/.poetry/bin
        /usr/local/bin
        /usr/bin
        /bin
        /usr/local/games
        /usr/games
        /home/udocker/.internal/scripts
        /home/udocker/.local/bin

sys.path:
        /usr/local/bin
        /home/udocker/.internal/nbextensions
        /usr/lib/python2.7
        /usr/lib/python2.7/plat-x86_64-linux-gnu
        /usr/lib/python2.7/lib-tk
        /usr/lib/python2.7/lib-old
        /usr/lib/python2.7/lib-dynload
        /home/udocker/.local/lib/python2.7/site-packages
        /usr/local/lib/python2.7/dist-packages
        /usr/lib/python2.7/dist-packages

sys.executable:
        /usr/bin/python

sys.version:
        2.7.10 (default, Aug  7 2015, 10:34:58)
        [GCC 4.9.2]

platform.platform():
        Linux-4.14.138-x86_64-with-debian-8.11

which -a jupyter:
        /usr/local/bin/jupyter
        /usr/local/bin/jupyter

pip list:
        Package                            Version
        ---------------------------------- -----------------
        aenum                              2.2.3
        attrs                              19.3.0
        autovizwidget                      0.12.8-uber.dev3
        backports-abc                      0.5
        backports.functools-lru-cache      1.6.1
        backports.shutil-get-terminal-size 1.0.0
        backports.shutil-which             3.5.2
        bleach                             1.5.0
        certifi                            2020.4.5.1
        cffi                               1.14.0
        chardet                            3.0.4
        Click                              7.0
        click-plugins                      1.1.1
        cligj                              0.5.0
        colorama                           0.3.2
        configparser                       3.5.0
        cryptography                       2.9
        cycler                             0.10.0
        decorator                          4.0.11
        defusedxml                         0.6.0
        docopt                             0.6.2
        entrypoints                        0.2.2
        enum34                             1.1.6
        Fiona                              1.8.13.post1
        flake8                             3.7.8
        funcsigs                           1.0.2
        functools32                        3.2.3.post2
        future                             0.18.2
        futures                            3.3.0
        geopandas                          0.6.3
        gitdb2                             2.0.6
        GitPython                          2.1.15
        hdfs                               2.5.8
        hdijupyterutils                    0.12.8-uber.dev4
        html5lib                           0.9999999
        idna                               2.8
        iotop                              0.6
        ipaddress                          1.0.23
        ipykernel                          4.10.0
        ipython                            5.1.0
        ipython-genutils                   0.1.0
        ipywidgets                         7.4.2
        Jinja2                             2.11.1
        jsonschema                         2.5.1
        jupyter                            1.0.0
        jupyter-client                     5.2.4
        jupyter-console                    5.2.0
        jupyter-contrib-core               0.3.3
        jupyter-contrib-nbextensions       0.5.1
        jupyter-core                       4.4.0
        jupyter-highlight-selected-word    0.2.0
        jupyter-latex-envs                 1.4.6
        jupyter-nbextensions-configurator  0.4.1
        jupyterlab                         0.33.11
        jupyterlab-launcher                0.11.2
        kafka-rest-py                      0.2.12
        keplergl                           0.1.0a8
        kiwisolver                         1.1.0
        lxml                               4.5.0
        m3                                 4.2.1
        MarkupSafe                         0.23
        matplotlib                         2.2.5
        mccabe                             0.6.1
        mistune                            0.8.4
        mlvis                              0.1.0
        mock                               3.0.5
        munch                              2.5.0
        nbconvert                          5.4.1
        nbdime                             1.0.4
        nbformat                           4.4.0
        nbstripout                         0.3.3
        nose                               1.3.7
        notebook                           5.7.8
        numpy                              1.16.4
        pandas                             0.23.0
        pandocfilters                      1.4.1
        pathlib2                           2.2.1
        pexpect                            4.2.1
        pickleshare                        0.7.4
        pip                                20.0.2
        pipenv                             2018.11.26
        plotly                             2.7.0
        ply                                3.11
        prometheus-client                  0.7.1
        prompt-toolkit                     1.0.9
        psutil                             5.6.1
        ptyprocess                         0.5.1
        pycodestyle                        2.5.0
        pycparser                          2.20
        pydeck                             0.1.dev5
        pyflakes                           2.1.1
        Pygments                           2.1.3
        pykerberos                         1.2.1
        pyparsing                          2.4.7
        pyproj                             2.2.2
        Pyste                              0.9.10
        python-dateutil                    2.8.1
        pytz                               2019.3
        PyYAML                             5.3
        pyzmq                              19.0.0
        qtconsole                          4.2.1
        requests                           2.22.0
        requests-kerberos                  0.12.0
        rise                               4.0.0b1
        scandir                            1.4
        scipy                              1.2.3
        seaborn                            0.9.1
        Send2Trash                         1.5.0
        setuptools                         41.0.0
        Shapely                            1.7.0
        simplegeneric                      0.8.1
        singledispatch                     3.4.0.3
        six                                1.10.0
        smmap                              3.0.1
        smmap2                             3.0.1
        sparkmagic                         0.12.8-uber.dev16
        subprocess32                       3.5.4
        terminado                          0.8.3
        testpath                           0.3
        thriftrw                           1.8.1
        tornado                            4.4.2
        traitlets                          4.3.3
        traittypes                         0.2.1
        typing                             3.7.4.1
        ujson                              1.35
        urllib3                            1.25.8
        vega                               0.5.0
        virtualenv                         16.7.9
        virtualenv-clone                   0.5.3
        wcwidth                            0.1.7
        widgetsnbextension                 3.4.2</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Not feasible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
This seems like a pandas issue, so I'd suggest asking in the pandas support channels: https://pandas.pydata.org/

Here is an example that works for me, in accordance with the [docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html#Hiding-the-Index-or-Columns):

```python
import pandas as pd

df = pd.DataFrame([1,2,3])

df.style.hide_index()
```

**Comment by jasongrout** [comment]
Ah, I see that my example was different than what you were going for. This is still a question about pandas, though, so should be addressed to their support channel.
