### ISSUE TITLE
How to make element.append in %%javascript magic render HTML?

### ISSUE THREAD

**Issue by drhades** [jupyterlab/jupyterlab#8353]
In lab, the element.append() in %%js magic just render HTML snippet as plain text,
what can I do to make it render HTML output?

**Comment by jasongrout** [comment]
```
%%js
let b = document.createElement('b');
b.textContent='Hi there!';
element.append('A test: ')
element.append(b)
```
seems to work well for me in JupyterLab 2.1. Does it not work for you?

<img width="433" alt="Screen Shot 2020-05-05 at 3 36 49 AM" src="https://user-images.githubusercontent.com/192614/81057680-bc578880-8e81-11ea-869c-9daf29803f1b.png">

If not, can you fill out the rest of the [new issue template](https://raw.githubusercontent.com/jupyterlab/jupyterlab/master/.github/ISSUE_TEMPLATE/bug_report.md) to help troubleshoot what might be wrong?

**Comment by drhades** [comment]
Thanks @jasongrout 
It works.

I tried appending plain text snippet before, which is ok in classic notebook.
<img width="393" alt="截屏2020-05-05 20 35 53" src="https://user-images.githubusercontent.com/82670/81067285-09cf0680-8f11-11ea-9302-5f9abd12dd90.png">
