### ISSUE TITLE
Specifying the length of a graphical line is difficult

### ISSUE THREAD

**Issue by myRandomFiles** [jupyterlab/jupyterlab#8360]
I tried to draw grids in Jupyter labs but have ended up having to use ASCII. Sometimes a 2x3 grid, other times a 5x4 grid, but always with the cells the same size. I've had to use ASCII for this in JupyterLab, because when I try to look up how to do it graphically, I get led on a wild goose chase through matplotlib, which auto-sizes, auto-layouts, auto-scales everything beyond recognition, so cells change their size from one grid to the next.

I imagine this is easy for people who work in universities and can ask the person sitting next to them how to do it, but for me working with nothing but the docs, it's been more difficult in JupyterLab than it was in Atari, Allegro Common LISP, Java, Mathematica, Maple, etc. Ask on Reddit, get harassed by people who don't know the answer.

![grid2](https://user-images.githubusercontent.com/60956662/80928444-57a10e80-8d59-11ea-8a44-9ca477ce685b.png)

Shouldn't be harder than it was on Atari.

Edited to add: A [blogger ](https://kavigupta.org/2019/05/18/Setting-the-size-of-figures-in-matplotlib/)I don't know agrees:

> Setting the actual size of figures in matplotlib.pyplot is difficult....
> 
> ... The example above is full, working, code, and should honestly probably be part of matplotlib: generally speaking, when I set the size of a figure, I intend to set the actual size of the figure, not the size of the plot with some minimal padding around it.

**Comment by timkpaine** [comment]
@myRandomFiles this sounds like a matplotlib question, but it can be a bit difficult to get things  the correct size. If you have some sample code you're working from, and a view on what you're looking to produce, we can point you in the right direction.

**Comment by myRandomFiles** [comment]
Thanks for offering to help, I'm porting parts of my program to Mathematica, so that I can post working Mathematica code to clarify my issue. This is the first time I've ever had to port a program from one language to another in order to learn how to use the first language, and I think it's a bad sign after forty years as a developer.

While I appreciate your offer to answer my question, I intended this thread as a bug report. This is a hundred times more difficult to learn in JupyterLab than it was in Atari 520 ST, and I see that as nothing less than a bug in JupyterLab.

**Comment by timkpaine** [comment]
Without a clear repro it's tough to know if it's something wrong with matplotlib or jupyterlab, but I doubt it has anything to do specifically with jupyterlab since all we do is render the png that matplotlib gives us. A matplotlib figure has set_size_inches (or equivalently the figsize argument) which will set height and width in inches in the dpi set by matplotlib (defaults to 100, but obviously what is shown will change based on the viewing person's screen). 

Mathematica is a fantastic tool that is hard to beat. There are also a variety of other charting libraries in the python ecosystem that work in jupyter and jupyterlab that you can explore. Of course this ecosystem is free and open source, and relies on the contributions of many to compete and often beat proprietary products. 

I'll close this issue for now, if you've got a snippet of code that produces something you think is incorrect please post it and we can look more and reopen.

**Comment by myRandomFiles** [comment]
100% of JupyterLab users on [StackOverflow ](https://stackoverflow.com/questions/61582520/how-to-draw-a-line-with-a-specific-length-in-jupyterlab/61584124?noredirect=1#comment108948763_61584124)and [Reddit ](https://www.reddit.com/r/Python/comments/gd3vnu/how_to_draw_a_line_with_a_specific_length_in/)don't know how to draw a square inch in JupyterLab. 

"but I doubt it has anything to do specifically with jupyterlab since all we do is render the png that matplotlib gives us."

It has everything to do with JupyterLab's documentation that 100% of respondents don't know who to draw a square inch it. If 100% of the users of my software didn't know how to use my software, I'd be fixing my documentation bug, while you lock this report instead. No wonder 100% of respondents didn't know how to operate your software.

**Comment by timkpaine** [comment]
here is a square inch where each tenth of an inch box is a random color:
```python
import matplotlib.pyplot as plt
import numpy as np
fig = plt.gcf()
fig.set_size_inches(1, 1, forward=True)
plt.imshow(np.random.random((10, 10)))
```

**Comment by jasongrout** [comment]
I think there is some confusion here about what JupyterLab is. JupyterLab is a completely separate project from matplotlib, with separate help channels and documentation. Questions about matplotlib (or any other plotting library) are for that package's support channels. Unlike Mathematica, which is a comprehensive single platform that includes a plotting library, the user interface, mathematical libraries, etc., JupyterLab is just one part of a user's toolkit, just the interface to using a library. The questions about how to draw graphics are for the plotting library you are using, not for JupyterLab. As Tim mentioned, there are also lots of other plotting libraries as well, like bqplot, plotly, bokeh, altair, and others in the python ecosystem that display their results in JupyterLab. If you're using the Julia language in JupyterLab, there are many other libraries for that ecosystem that display their results in JupyterLab. If you're using R, there are other completely different plotting libraries with their own documentation, examples, and help channels. JupyterLab lets you use these libraries and displays their results, but if you have a question about how to draw graphics using a plotting library, please seek help from that particular package's help channels.

That said, one thing JupyterLab also provides is the ability to display HTML you've written. Of course, you need to know or learn what HTML would achieve your goal (which is not a JupyterLab project question), but it may be that generating an HTML table with appropriate styling would give you a square grid you could put text into. I don't know what that HTML would be. I mention this as a possible direction you could look. Here is how you would display some HTML code you've written in a Jupyter notebook, if you are using the ipython kernel to run your code:

```python
from IPython.display import HTML
display(HTML('<table><tr><td>A</td><td>B</td></tr><tr><td>C</td><td>D</td></tr></table>'))
```

**Comment by myRandomFiles** [comment]
Thanks for the code example, but that looks not adaptable to the grid I showed in the original post. With due respect for your time and efforts here, I think we're both just wasting our times.

**Comment by myRandomFiles** [comment]
> I think there is some confusion here about what JupyterLab is

I realize now what it is: It is not software that aspires to be as easy to learn as Mathematica or Maple. It's developers know it's harder to learn how to draw an inch in matplotlib than in Mathematica or Maple, but its developers don't mind; instead, it's free.

Thanks for helping me with my problem. I will be better off using Python and ASCII without JupyterLab for my needs here. That's a step back from the graphical version I did when I was 14 on Atari 520 ST, but this is getting ridiculous and I need to get work done.

**Comment by timkpaine** [comment]
ascii in a terminal has the benefit of being fixed width!

Here is a snippet for the right chart:

```python3
import matplotlib.pyplot as plt
import numpy as np
plt.xlim(0, 10)
plt.ylim(0, 10)

fig = plt.gcf()
ax = plt.gca()

fig.set_size_inches(10, 10)
ax.set_xticks(np.arange(0, 10, 1))
ax.set_yticks(np.arange(0, 10, 1))

ax.xaxis.set_ticklabels([])
ax.yaxis.set_ticklabels([])

plt.text(1, 2, 'a', color='r', fontsize=30)
plt.text(2, 3, 'b', color='r', fontsize=30)
plt.text(1, 3, 'c', fontsize=60)

plt.grid()
```

Another thing to note is that you can use Mathematica or Octave/Matlab in jupyter:
https://github.com/jupyter/jupyter/wiki/Jupyter-kernels

I've used the Matlab kernel and it works well.

**Comment by timkpaine** [comment]
Matlab: https://github.com/calysto/matlab_kernel
Octave: https://github.com/calysto/octave_kernel
Mathematica: https://github.com/WolframResearch/WolframLanguageForJupyter

**Comment by myRandomFiles** [comment]
I'm going to study your code example and maybe use it. In return for help I've been receiving here, I've been trying to help you by pointing out above that:
> 100% of [responding] JupyterLab users on StackOverflow and Reddit don't know how to draw a square inch in JupyterLab.
For my software, I'd want to know about that so I could track it and improve the user experience.

**Comment by myRandomFiles** [comment]
It's been pointed out to me, and I gather from the matplotlib documentation, that matplotlib is geared by default for graph plotting, not graphics like I'm doing. But the JupyterLab Help menu has a matplotlib entry and no better entry for graphics. That's probably why I first made the bad decision to use matplotlib for primitive graphics. I was coming from Mathematica, which integrates plotting and graphics seamlessly.

**Comment by jasongrout** [comment]
> But the JupyterLab Help menu has a matplotlib entry and no better entry for graphics.

Ah, thanks for explaining how you came here for help with matplotlib. Those links actually come from the kernel you are using, not JupyterLab, but are displayed in the JupyterLab help menu as a way for the kernel (in this case probably the [IPython kernel](https://github.com/ipython/ipykernel/blob/7b7046adb9230bfdfc59fd332ae1647cdd521e3c/ipykernel/ipkernel.py#L88-L117)) to give helpful resources. If you are using a different language kernel, you'll see different resources listed in that help menu. For example, here is what the help menu looks like when in a notebook running Julia code: 

<img width="283" alt="Screen Shot 2020-05-04 at 10 26 53 PM" src="https://user-images.githubusercontent.com/192614/81037124-86e97580-8e56-11ea-858c-6f72d8cf404a.png">

I can see the confusion about that documentation being a recommendation from JupyterLab. I've opened an issue about clarifying in the JupyterLab UX that those help menu resources are suggestions from the language kernel you are using, not from JupyterLab itself.

**Comment by myRandomFiles** [comment]
> JupyterLab is a completely separate project from matplotlib, with separate help channels and documentation. Questions about matplotlib (or any other plotting library) are for that package's support channels.

My problem has been unwanted auto-scaling of matplotlib figures rendered in JupyterLab. For all I've known, it was the JupyterLab container that was resizing / rescaling things, because in some systems, graphical containers are responsible for layout and sizing of the things contained.

The Help menu will never actually get fixed, because for that to happen, I'd have to go persuade the IPython moderators that its a legitimate issue; and I be stupid to do that when I can spend my time instead beta testing for commercial companies who value my criticism and compensate me well for it.

**Comment by myRandomFiles** [comment]
If your software project has an [SJW code of conduct](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md), you're not doing science you're doing politics.

**Comment by telamonian** [comment]
> I can spend my time instead beta testing for commercial companies who value my criticism and compensate me for it.

Good luck with that, buddy! You've clearly had a very different set of experiences wrt Mathematica and Wolfram than most people have.

For future reference, to get exactly square grids in Matplotlib, you just need to set the right [aspect ratio](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_aspect.html):

```python
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.gca()
ax.set_aspect('equal')
ax.grid(True)
plt.show()
```

![image](https://user-images.githubusercontent.com/2263641/81123251-9a511b00-8f00-11ea-8ca3-9d09e0b1835e.png)

On the other hand, if you want to draw a grid of squares that actually *display* as 1in x 1in on your current monitor, it's a bit more complex. In general, images will display at different sizes on different monitors, depending on their dpi (mine is ~109):

```python
# run this in a separate cell, can only initialize one
# QApplication per Python instance

from PyQt5.QtWidgets import QApplication
import sys

app = QApplication(sys.argv)
screen = app.screens()[0]
dpi = screen.physicalDotsPerInch()
app.quit()

# %%

# first run the dpi calculation for your screen,
# then run this

import matplotlib.pyplot as plt

dims = (3, 4)

fig = plt.figure(figsize=dims)
fig.set_dpi(dpi)

ax = fig.add_axes([0, 0, 1, 1])
ax.set_xlim(-1e-2, dims[0])
ax.set_ylim(-1e-2, dims[1])
ax.set_aspect('equal')
ax.set_facecolor('black')

for spine in plt.gca().spines.values():
    spine.set_visible(False)
ax.get_xaxis().set_visible(False)
ax.get_yaxis().set_visible(False)

for i in range(dims[0] + 1):
    ax.axhline(i, c='green')
for i in range(dims[1] + 1):
    ax.axvline(i, c='green')

plt.show()
```

![image](https://user-images.githubusercontent.com/2263641/81123444-164b6300-8f01-11ea-8dc7-d986c1639274.png)

**Comment by telamonian** [comment]
For future reference, to get exactly square grids in Matplotlib, you just need to set the right [aspect ratio](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.set_aspect.html):

```python
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.gca()
ax.set_aspect('equal')
ax.grid(True)
plt.show()
```

![image](https://user-images.githubusercontent.com/2263641/81123251-9a511b00-8f00-11ea-8ca3-9d09e0b1835e.png)

On the other hand, if you want to draw a grid of squares that actually *display* as 1in x 1in on your current monitor, it's a bit more complex. In general, images will display at different sizes on different monitors, depending on their dpi (mine is ~109):

```python
# run this in a separate cell, can only initialize one
# QApplication per Python instance

from PyQt5.QtWidgets import QApplication
import sys

app = QApplication(sys.argv)
screen = app.screens()[0]
dpi = screen.physicalDotsPerInch()
app.quit()

# %%

# first run the dpi calculation for your screen,
# then run this

import matplotlib.pyplot as plt

dims = (3, 4)

fig = plt.figure(figsize=dims)
fig.set_dpi(dpi)

ax = fig.add_axes([0, 0, 1, 1])
ax.set_xlim(-1e-2, dims[0])
ax.set_ylim(-1e-2, dims[1])
ax.set_aspect('equal')
ax.set_facecolor('black')

for spine in plt.gca().spines.values():
    spine.set_visible(False)
ax.get_xaxis().set_visible(False)
ax.get_yaxis().set_visible(False)

for i in range(dims[0] + 1):
    ax.axhline(i, c='green')
for i in range(dims[1] + 1):
    ax.axvline(i, c='green')

plt.show()
```

![image](https://user-images.githubusercontent.com/2263641/81123444-164b6300-8f01-11ea-8dc7-d986c1639274.png)
