### ISSUE TITLE
Color between windows

### ISSUE THREAD

**Issue by sorenwacker** [jupyterlab/jupyterlab#8365]
Hi, 

I use a dark mode tool for my browser which worked pretty well in the past with JupyterLab, but now then I activate the dark mode the colour in between the windows turns bright instead of dark. Did the colours change during the last release? Is there a way that I can adjust that? It is better to use the browser dark-mode than the Jupyter one because then all windows will switch to dark background rather than just the Jupyter notebook.

**Comment by jasongrout** [comment]
1. Can you provide more information, asked in the issue template, like the browser and version, and jupyterlab version?
2. Can you post a screenshot? It's hard for me to understand what parts of the UX you are talking about.

> Did the colours change during the last release?

I don't think 2.1 had any appreciable color changes. Perhaps the syntax highlighting for the dark theme changed a bit.
