### ISSUE TITLE
Autolink wrongly formats urls in angle brackets

### ISSUE THREAD

**Issue by wragge** [jupyterlab/jupyterlab#8376]
## Description

If a url is enclosed in angle brackets, the autolinking converts the closing bracket to `&gt;` and adds it to the url.

![Screenshot of url](https://dl.dropbox.com/s/a68wl58r1f1xxml/jupyter-autolink.png)

I noticed this working with HTTP headers produced by the Memento protocol which uses angle brackets to delineate the various types of links.

![Screenshot of headers](https://dl.dropbox.com/s/t8peokhcnv490z9/jupyter-autolink-headers.png)

## Expected behavior

The enclosing angle brackets should remain unchanged.

![Screenshot](https://dl.dropbox.com/s/znazvid4br0pfn8/jupyter-autolink-expected.png)

## Context

- JupyterLab version: 2.1.2

**Comment by jasongrout** [comment]
Thanks. This is also a problem after https://github.com/jupyterlab/jupyterlab/pull/8240

Interestingly, the classic notebook (which our autolinking is based on) does not have this issue:

<img width="525" alt="Screen Shot 2020-05-05 at 10 51 00 PM" src="https://user-images.githubusercontent.com/192614/81141930-f4fb6e80-8f22-11ea-80ad-6d3070f22c8c.png">

**Comment by jasongrout** [comment]
The relevant code, for anyone who can work on this, is at https://github.com/jupyterlab/jupyterlab/blob/23d7624d30ed7abc2f43480e9466947610e53ac6/packages/rendermime/src/renderers.ts#L477-L497

**Comment by wragge** [comment]
Also, just noticed that ampersands seem to get converted to HTML entities.

![Screenshot](https://dl.dropbox.com/s/0z3pjwp4jrxrqve/jupyter-autolink-entities.png)

**Comment by kdumovic** [comment]
Really hoping this gets fixed soon. This was super gnarly to debug. I thought it was an issue with my templating system.

**Comment by jasongrout** [comment]
This looks like it is fixed in 3.0rc10. Can you try it to verify?

<img width="435" alt="Screen Shot 2020-11-19 at 8 45 58 PM" src="https://user-images.githubusercontent.com/192614/99760298-45de4900-2aa8-11eb-9daa-36ab6bb93757.png">

`pip install --pre jupyterlab==3.0.0rc10` to install it.

**Comment by jasongrout** [comment]
Actually, it seems to work in 2.2.9 as well:

<img width="445" alt="Screen Shot 2020-11-19 at 8 49 43 PM" src="https://user-images.githubusercontent.com/192614/99760567-d87ee800-2aa8-11eb-91ea-b0e7487154a0.png">

**Comment by jasongrout** [comment]
Looks like this was fixed in #8496, released in 2.2.0
