### ISSUE TITLE
unable to interrupt cell execution if jupyter uses kernel from a different environment

### ISSUE THREAD

**Issue by evfro** [jupyterlab/jupyterlab#8388]
## Description
I'm using a dedicated conda environment with jupyterlab. Let's call it `jlab_env`. For a new project I create a fresh environment (without jupyterlab) and only register kernel via: `conda install ipykernel` within this environment. Let's call it `no_jlab_env`. This kernel gets visible due to `nb_conda_kernels` that I also have installed in the `jlab_env`.

Now, in the jupyterlab interface I just switch  `jlab_env` to my freshly created `no_jlab_env` kernel. Running cells in this notebooks becomes unresponsive to interrupt commands. If I switch back to `jlab_env`, cells run as normal and I can interrupt execution with no problem.

## Reproduce
```python
for i in range(50):
    print(i, end=',')
    time.sleep(0.1)
print('\nDone')
```
In the `no_jlab_env` will print all numbers from 0 to 49 as well as final "Done" line no matter how many times I press `i-i`, or select `Interrupt Kernel` from the menu, or hit the black square stop-buttton. In contrast, the same code can be interrupted at any time in the `jlab_env`.

## Expected behavior
Hitting `i-i`, or selecting `Interrupt Kernel` from the menu, or pressing the black square stop-button should immediately interrupt execution in the `no_jlab_env`. It should stop printing numbers and never print "Done".

## Context
- Operating System and version: tested on Windows 10 and several Ubuntu systems of different versions.
- Browser and version: tested in recent versions of Microsoft Edge and Mozilla Firefox
- JupyterLab version: tested on both 1.2.14 and 2.1.2 conda-forge

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/unable-to-reliably-use-single-jypyterlab-server-with-multiple-conda-environments/7979/1

**Comment by evfro** [comment]
Closing this issue as the source of the problem was identified to be `nb_conda_kernels` as pointed out in https://github.com/jupyter/notebook/issues/5985
