### ISSUE TITLE
Formatter not found !

### ISSUE THREAD

**Issue by JTebeka** [jupyterlab/jupyterlab#8398]
<img width="1175" alt="Capture d’écran 2020-05-08 à 16 58 14" src="https://user-images.githubusercontent.com/49912455/81418642-44bd7e00-914d-11ea-9ea7-27a665a521a0.png">

Hi, 
after not seeing the icon (we discussed last week to find a solution about this and you told me : try something like this jupyterlab/jupyterlab#8122...)
Now after a crash of my computer, I need to reinstall it and I can see the icon but I get a message that told me "Formater not find" when I click on it (cf picture)

- Operating System and version:  MacOS 10.15.4
- Browser and version: Safari 13.1
- JupyterLab version: 2.1.2

JupyterLab v2.1.2
Known labextensions:
   app dir: /Users/jacques/opt/anaconda3/envs/Data/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/debugger v0.2.0  enabled  OK
        @jupyterlab/shortcutui v0.5.0-beta.2  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @krassowski/jupyterlab-lsp v1.0.0  enabled  OK
        @lckr/jupyterlab_variableinspector v0.5.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.2.5  enabled  OK
        @wallneradam/output_auto_scroll v0.3.0  enabled  OK
        jupyterlab-chart-editor v4.6.0  enabled  OK
        jupyterlab-logout v0.5.0  enabled  OK
        jupyterlab-plotly v4.7.1  enabled  OK
        jupyterlab-python-file v0.4.0  enabled  OK
        jupyterlab-spreadsheet v0.3.2  enabled  OK
        jupyterlab-system-monitor v0.6.0  enabled  OK
        jupyterlab-theme-toggle v0.5.0  enabled  OK
        jupyterlab-topbar-extension v0.5.0  enabled  OK
        jupyterlab-topbar-text v0.5.1  enabled  OK
        jupyterlab_filetree v0.2.2  enabled  OK
        plotlywidget v4.7.1  enabled  OK

config dir: /Users/jacques/.jupyter
    jupyterlab_code_formatter  enabled 
    - Validating...
      jupyterlab_code_formatter  OK
config dir: /Users/jacques/opt/anaconda3/envs/Data/etc/jupyter
    jupyter_lsp  enabled 
    - Validating...
      jupyter_lsp 0.8.0 OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.1.2 OK

**Comment by JTebeka** [comment]
I add and that strange from my point of view that when I click on the left and choose "Apply Autopep8 format " it works
It's just when I click on the icon that I have the previous message. 

<img width="1175" alt="Capture d’écran 2020-05-08 à 17 18 09" src="https://user-images.githubusercontent.com/49912455/81420229-f6f64500-914f-11ea-90ee-04c91594d575.png">

**Comment by blink1073** [comment]
Hi @JTebeka, that extension isn't part of core.  Please open an issue on https://github.com/ryantam626/jupyterlab_code_formatter.
