### ISSUE TITLE
Invisible cursor in dark mode

### ISSUE THREAD

**Issue by assafv** [jupyterlab/jupyterlab#8407]
This issue still exists, for attached previous bug.

please see:
https://github.com/jupyterlab/jupyterlab/issues/7329
as this is a really annoying issue.

I would be happy to provide more info.

**Comment by lclarko** [comment]
Also experiencing this:

JupyterLab Version 2.1.5
 - Dark Theme
Chrome Version 83.0.4103.116 (Official Build) (64-bit)

Cursor is OK and flashing in Light Theme, though it disappears in dark mode

**Comment by jweill-aws** [comment]
Closing in favor of #12859 which includes a screen shot
