### ISSUE TITLE
Attachments are lost after merging two markdown cells

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#8414]
## Description

Attachments are lost when two cells are merged with "Edit -> Merge Selected Cells". 

## Reproduce

Cell 1 contains an attachment (image pasted from the clipboard), for example:

```markdown
![image.png](attachment:caf34e46-2196-4066-97d8-80e53351c0f0.png)
```

Cell 2 contains an attachment too, for example:

```markdown
![image.png](attachment:44a1114f-565f-473a-bbfd-f9244ca93af5.png)
```

![merge-cells-attachments](https://user-images.githubusercontent.com/591645/81711609-1fde4900-9474-11ea-88dc-975428bce1ea.gif)

After the merge, the source of the cell is: 

```markdown
![image.png](attachment:caf34e46-2196-4066-97d8-80e53351c0f0.png)

![image.png](attachment:44a1114f-565f-473a-bbfd-f9244ca93af5.png)
```

But only one image is displayed.

## Expected behavior

It feels like both images should be shown after merging markdown cells. Meaning that the attachments would be merged too if possible (markdown cell).

Looking at the text source of the notebook, the `attachments` metadata contains only one entry after the merge in the example above.

## Context

- Operating System and version: Ubuntu 20.04
- Browser and version: Firefox Dev Edition 77.0b4
- JupyterLab version: `master` (6d5240dda71fb3d12814e8b88b09e94e23d42875)

**Comment by jasongrout** [comment]
Indeed, I don't see any code in the merge function handling attachments. This is likely an oversight: https://github.com/jupyterlab/jupyterlab/blob/6d5240dda71fb3d12814e8b88b09e94e23d42875/packages/notebook/src/actions.tsx#L187

**Comment by jasongrout** [comment]
Would you like to submit a PR?

**Comment by jtpio** [comment]
Sure, I'll have a look.

**Comment by vidartf** [comment]
I guess it should only be a dictionary merge, but the interesting thing will be how to handle conflicting keys. If they both have the same value, I guess they can just be merged as is, but if the values differ we might want to find a unique suffix for one of them? Any such rename would when need to update any references in the markdown source as well 🤔

**Comment by jtpio** [comment]
For reference this is what the classic notebook (6.0.3) does:

![merge-cells-attachments-notebook](https://user-images.githubusercontent.com/591645/82071525-819ded80-96d6-11ea-841c-a77882d81b29.gif)

The keys are named `image.png`. There are also extra commands to copy, cut and paste cell attachments:

![image](https://user-images.githubusercontent.com/591645/82071916-0be65180-96d7-11ea-9d79-2b1bdc2d49ec.png)

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlab/jupyterlab/pull/8427 as a start.

**Comment by jasongrout** [comment]
> I guess it should only be a dictionary merge, but the interesting thing will be how to handle conflicting keys. If they both have the same value, I guess they can just be merged as is, but if the values differ we might want to find a unique suffix for one of them? Any such rename would then need to update any references in the markdown source as well 🤔

A recent change in JLab is to generate UUIDs for attachments, so hopefully for at least JupyterLab there won't be collisions. Of course, for general ipynb files there isn't that guarantee.
