### ISSUE TITLE
\b handling depends on parity of \b characters

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8440]
## Description

Something weird is going on with `\b` handling in JupyterLab and Jupyter Notebook (they seem consistent)

## Reproduce

Execute the following:

```
print("12345\bX")
print("12345\b\bX")
print("12345\b\b\bX")
print("12345\b\b\b\bX")
print("12345\b\b\b\b\bX")
print("12345\b\b\b\b\b\bX")
```
I get
```
1234X
123X
1234X
123X
1234X
123X
```

## Expected behavior

I would have expected:
```
1234X
123X
12X
1X
X
X
```

## Context

- Operating System and version: macOS Mojave
- Browser and version: Firefox 76
- JupyterLab version: 2.1.2

**Comment by jasongrout** [comment]
Actually, a real terminal would not have erased characters, just moved the cursor, to give something like this that I got from a terminal running python:

```
% python
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print("12345\bX")
1234X
>>> print("12345\b\bX")
123X5
>>> print("12345\b\b\bX")
12X45
>>> print("12345\b\b\b\bX")
1X345
>>> print("12345\b\b\b\b\bX")
X2345
>>> print("12345\b\b\b\b\b\bX")
X2345
```
I think we've already crossed that incompatibility a long time ago with the notebook, though.

**Comment by jasongrout** [comment]
Noted in https://stackoverflow.com/questions/55440152/multiple-b-doesnt-work-as-expected-in-jupyter, and @williamstein mentioned it in https://github.com/sagemathinc/cocalc/issues/2520

**Comment by jasongrout** [comment]
Of course, we have many GitHub issues and PRs over the years dealing with \r and \n. It seems we reached some conclusion about this behavior in https://github.com/jupyterlab/jupyterlab/pull/3882#discussion_r168645529

See also https://github.com/jupyter/notebook/issues/2892 for more discussion.

So I'll close this for now. Perhaps we're doomed to opening an issue like this from time to time when we forget why we had settled for inconsistent behavior with the terminal :(.

**Comment by williamstein** [comment]
@jasongrout that ticket you link to is locked so I can't comment there.   One person there writes:

> I agree with @blink1073 . Especially since libraries have been writing their stdout for things like progress bars to work with the classic notebook.

Are there any known Python libraries that use \b for progress bars, or do they all use \r?  The one we're discussing at https://github.com/sagemathinc/cocalc/issues/2520 only uses \r, with the messages looking like this:
```
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\r 52%|█████▏    | 52/100 [00:02<00:02, 19.65it/s]"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\r 54%|█████▍    | 54/100 [00:02<00:02, 19.65it/s]"
     ]
    },
...
```

**Comment by telamonian** [comment]
@williamstein I think the reason why I originally opened #3881 was to improve support for `tqdm`, which back then was doing weird things in jlab. I just grepped the current master of `tqdm`, though, and it looks like all references to `\b` have been factored out in their codebase

**Comment by williamstein** [comment]
Thanks for your comments!

>  a full xterm emulator

That makes me tempted to use xterm.js for rendering some outputs, though that would be its own can of worms...

**Comment by telamonian** [comment]
> That makes me tempted to use xterm.js for rendering some outputs

I think(?) I remember one of the Spyder devs complaining about the difficultly of implementing their outputs using xterm.js. But yeah, if we *did* want to do full xterm emulation, then switching from our hand rolled terminal emulation over to some standard library would be the first step

**Comment by jasongrout** [comment]
>  Are there any known Python libraries that use \b for progress bars, or do they all use \r?

Just to follow up - I don't know of any libraries that use \b for progress bars.
