### ISSUE TITLE
Cannot Use tf as a variable in Jupyter Lab

### ISSUE THREAD

**Issue by andibuwono** [jupyterlab/jupyterlab#8447]
## Description

Variable `tf ` can only used in the same cell its assigned or created in Jupyter Lab. The  behaviour is normal in Classic Jupyter Notebook mode.

## Reproduce
Create a variable named `tf` in jupyter lab notebook and print in the same cell and print in the following cell

Below is result in Jupyter Lab, which following cell give none Type for tf

![image](https://user-images.githubusercontent.com/9608246/82452185-2191b780-9ad9-11ea-85a4-6ba030c35c27.png)

Below is result in Jupyter Classic Notebook, which gives normal behaviour

![image](https://user-images.githubusercontent.com/9608246/82452212-2e161000-9ad9-11ea-914f-39138aafee11.png)

Currently I assume this in the server side not in the client side. But I'm not familiar with jupyter lab internal. I hope my information is enough. Thanks Before.

## Expected behavior

`tf` variable is carried to other cell following the cell it assigned or created

- Operating System and version:
Windows 10 2004
- Browser and version:
Chrome 81
- JupyterLab version:
ipython                       7.14.0
jupyter                       1.0.0
jupyter-console               6.1.0
jupyter-core                  4.6.3
jupyter-server                0.3.0
jupyterlab                    2.1.2
jupyterlab-server             1.1.4

**Comment by timkpaine** [comment]
do you have the variableinspector jupyterlab extension installed?

**Comment by andibuwono** [comment]
Yes, is it known issue?

![image](https://user-images.githubusercontent.com/9608246/82458746-48ec8280-9ae1-11ea-86fe-a73785cecaba.png)

**Comment by paw-lu** [comment]
@andibuwono @timkpaine Was just bit by this. I also have variableinspector installed—but disabled.

**Comment by paw-lu** [comment]
@andibuwono I can confirm that uninstalling variableinspector fixes this. It seems to cause this issue even when explicitly disabled. I needed to uninstall it to fix this issue.

**Comment by andibuwono** [comment]
Yes I notice that caused by variable inspector

Not yet a solution, but as Jupyter Lab 2.1.3 the behaviour is as below, and satisfy my use case.
And this is not exclusive for tf as tensorflow but as well pandas as pd and numpy as np

![image](https://user-images.githubusercontent.com/9608246/83212039-c3c03800-a188-11ea-8728-a9839a2dabf8.png)

I'm closing this as this is not jupyter lab issue, thanks everyone.
