### ISSUE TITLE
Confusing error messages when trying to create a file in a read-only folder

### ISSUE THREAD

**Issue by edschofield** [jupyterlab/jupyterlab#8453]
## Description

Attempting to create a new notebook or text file in a read-only folder causes JupyterLab to emit two confusing messages: 

![image](https://user-images.githubusercontent.com/78314/82509827-5559f500-9b4c-11ea-8c61-690d2830e6ef.png)

and then:

![image](https://user-images.githubusercontent.com/78314/82509842-6145b700-9b4c-11ea-9e60-6234bc696756.png)

## Reproduce

1. Create a folder that is read-only:

```bash
$ mkdir -p ~/myfolder
$ chmod a-w ~/myfolder
```

2. Start JupyterLab
3. Double-click to change into `myfolder`
3. File | New | Notebook or File | New | Text File
4. You see the error messages in the screenshots above

## Expected behavior

A single beginner-friendly message box with an error message like "You do not have permissions to write in this directory."

## Context

As context, we are using JupyterLab via JuptyerHub to teach Python and data science. We provision a read-only folder with the teacher's notebooks, which the learners should not modify. If the learners are in this folder when they try to create their own notebooks, they are confused by the current error messages.

- Operating System and version: Ubuntu Linux 18.04
- Browser and version: Safari 13.1 or Firefox 76.0.1
- JupyterLab version: 1.2.5

<details><summary>Browser Output (JS console)</summary>
<pre>
Failed to load resource: the server responded with a status of 403 ()
</pre>
and:
<pre>
TypeError: undefined is not an object (evaluating 'model.path')
</pre>
</details>

**Comment by fcollonval** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/10641
