### ISSUE TITLE
Add a disposed check for widgets added to shell

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8465]
## Description
In our APOD example, we are re-using a widget that has been disposed when you close the widget and re-launch it.   The result is that the widget tab label and close icon are missing (and in general the widget would be broken).  We need to check for `widget.isDisposed` when adding to the shell and raise an error.  
We also need to update the APOD example to no re-use a widget that has been closed.

## Reproduce
Run the APOD example.  Launch the widget, close it, and then re-launch it.

## Expected behavior
Widget should fail to re-add and console log an error.

## Context
N/A

**Comment by blink1073** [comment]
#8623 updates the tutorial text.

**Comment by jasongrout** [comment]
I'm pretty sure I merged the changes fixing this in APOD. Should be double-checked to make sure...

**Comment by jasongrout** [comment]
Fixed, see https://github.com/jupyterlab/jupyterlab_apod/pull/7
