### ISSUE TITLE
Jupyterlab doesn't render some input cells (shows blank box), while notebook works

### ISSUE THREAD

**Issue by dlakelan** [jupyterlab/jupyterlab#8466]
## Description

I am working with a julia notebook. Some inputs simply don't render.

Example screenshot is shown:

![Screenshot from 2020-05-23 10-45-24](https://user-images.githubusercontent.com/4332910/82737069-fbd7fe80-9ce2-11ea-9b9e-3c3a25ff2092.png)

As you can see my cursor is currently "at" line 5 on the second line of input. The code defines a function. It shows properly in the notebook version but not in the Lab version. 

## Reproduce

1. Open Document with julia code cells
2. Observe that some cells don't render. In my case it's two cells where I define functions
3. Open document in notebook. Observe that the cells render the text and can be used normally.

- Operating System and version:
- Browser and version: Firefox 71.0 on Linux (also Chromium 81.0.4044.92 on Linux)
- JupyterLab version: 2.1.3

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[I 10:05:59.649 NotebookApp] Serving notebooks from local directory: .....
[I 10:05:59.649 NotebookApp] The Jupyter Notebook is running at:
[I 10:05:59.649 NotebookApp] http://localhost:8888/?token=4f64c8ec46a5a93783c70c84bfc5e760a07c2d8b316ecb73
[I 10:05:59.649 NotebookApp]  or http://127.0.0.1:8888/?token=4f64c8ec46a5a93783c70c84bfc5e760a07c2d8b316ecb73
[I 10:05:59.649 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:05:59.665 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/dlakelan/.local/share/jupyter/runtime/nbserver-283434-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=4f6xxxxxx6ecb73
     or http://127.0.0.1:8888/?token=4f6xxxxxxxx6ecb73
[W 10:06:05.521 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20200523100559 (::1) 13.85ms referer=http://localhost:8888/notebooks/notebook/RandomTests.ipynb
[I 10:06:05.905 NotebookApp] Kernel started: 3767048e-e436-4fc5-82c2-3cd8c774cae3
Starting kernel event loops.
[I 10:06:11.071 NotebookApp] Adapting from protocol version 5.0 (kernel 3767048e-e436-4fc5-82c2-3cd8c774cae3) to 5.3 (client).
[W 10:06:54.033 NotebookApp] 404 GET /api/kernels/60ca5fd5-95ff-4d14-ac19-e8c449430052/channels?session_id=0473338a0feb4fb086858519fbcb3bbd (127.0.0.1): Kernel does not exist: 60ca5fd5-95ff-4d14-ac19-e8c449430052
[W 10:06:54.036 NotebookApp] 404 GET /api/kernels/60ca5fd5-95ff-4d14-ac19-e8c449430052/channels?session_id=0473338a0feb4fb086858519fbcb3bbd (127.0.0.1) 3.70ms referer=None
[I 10:42:05.914 NotebookApp] Saving file at /notebook/RandomTests.ipynb

</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
uncaught exception: Object
Unchecked lastError value: Error: ID already exists: open-link-in-new-temporary-container-tab ExtensionCommon.jsm:746
    withLastError resource://gre/modules/ExtensionCommon.jsm:746
    create chrome://browser/content/child/ext-menus.js:148
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface] network-response-listener.js:84
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface] network-response-listener.js:84
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface] network-response-listener.js:84
</pre>
</details>

**Comment by choforito84** [comment]
I have the same problem. Running on Ubuntu 18.04, Firefox 76.0.1 (64-bit), Jupyter Lab version 2.0.1

Opening the notebook in Visual Studio Code allows me to work with cells.

**Comment by dlakelan** [comment]
@choforito84 have you found any rhyme or reason why certain cells behave this way? obviously as can be seen in my screenshot, the first input box is fine... if I scroll down further input boxes are also fine... perhaps if there were some specific condition where input boxes render like this it would help the developers fix it... but I don't know what that is! In my case, both these inputs define functions.

also, can you see your input cells when you work in the jupyter notebook rather than jupyter lab?

**Comment by choforito84** [comment]
@dlakelan It always happens when I am trying to edit the said cell and, at the same time, the notebook is executing some code. I also had the problem with the Julia kernel with cells that were also defining functions.

In Jupyter notebook I also can't see the cell.

**Comment by jasongrout** [comment]
Can you post a minimal notebook with this problem? That is also a very odd js message, indicating somehow there may be a duplicate id on the page?

**Comment by telamonian** [comment]
@dlakelan Your error message appears to be bubbling up from some modules specific to Firefox. Would you happen to have the [temporary-containers](https://github.com/stoically/temporary-containers) firefox extension installed?

ref: https://github.com/stoically/temporary-containers/blob/main/src/background/contextmenu.ts#L26

**Comment by jasongrout** [comment]
Ah, good point. If you can look at that specifically, or more generally our guidelines for diagnosing and reporting issues at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html, that can help narrow down what the problem might be and help others reproduce it.

**Comment by dlakelan** [comment]
Yes, it's in temporary containers. Since that issue occurred, where it was happening consistently on that notebook... I have yet to see it again. So I can't give a minimal example at the moment. I've been using JupyterLab for other projects without problem... :-(

**Comment by dlakelan** [comment]
Here's a similar but different, maybe related issue... This notebook cell has **four** lines of code and yet it repeats the first three lines over and over and over... and then finally shows all 4 without syntax hilighting... weird:

![image](https://user-images.githubusercontent.com/4332910/86537586-ef7bbf80-bea4-11ea-9a5b-754348d7b19d.png)

**Comment by dlakelan** [comment]
Found another example where it doesn't work... 

![image](https://user-images.githubusercontent.com/4332910/87116058-c1420b00-c229-11ea-8a21-0ad5ffbaa09b.png)

The notebook is here:

https://github.com/dlakelan/JuliaDataTutorials/blob/master/RegressionDiscontinuityQuestion.ipynb
commit a4d0c36

You can view it in nbviewer here: https://nbviewer.jupyter.org/github/dlakelan/JuliaDataTutorials/blob/master/RegressionDiscontinuityQuestion.ipynb where it displays fine... but in JupyterLab it shows the above screenshot.

**Comment by blink1073** [comment]
I just tried the above notebook with JupyterLab 2.2.0 and all of the input cells rendered correctly, can you please try upgrading @dlakelan?

**Comment by blink1073** [comment]
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/2096628/88835226-98fb5b80-d19a-11ea-9e16-450374eb2460.png">

**Comment by dlakelan** [comment]
Updated to 2.2.2 and indeed that last example does render correctly for me. Also I re-checked the original notebook, and it's rendering correctly as well.

I'll make sure to update this if I find another example, but I think maybe whatever the bug was it may have been fixed. I hope!

**Comment by blink1073** [comment]
We upgraded CodeMirror from [`5.49.2`](https://github.com/jupyterlab/jupyterlab/blob/34a94a4e65d5606dfb82d33b0f172d579bab5e0b/jupyterlab/staging/yarn.lock#L2448) to [`5.53.2`](https://github.com/jupyterlab/jupyterlab/blob/b5024e97f8b9160dd9cef70d619027fbf7a47aa7/jupyterlab/staging/yarn.lock#L2451) between those releases.

**Comment by blink1073** [comment]
I'll close this for now then, cheers!
