### ISSUE TITLE
jupyter lab build fails on a Raspberry Pi

### ISSUE THREAD

**Issue by CleoQc** [jupyterlab/jupyterlab#8470]
## Description
 I am trying to install Jupyter Lab on a Raspberry Pi. 
`Jupyter lab build` fails with 
**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**  on a fresh install. 

I checked the [other issues ](https://github.com/jupyterlab/jupyterlab/issues/4325) to no avail. I suspect the fact that I'm on a Raspberry Pi brings in another set of issues.

## Reproduce

1. Use a Raspberry Pi 4 with 4G of ram with a newly flashed Buster Raspbian SD card

2. Edit /etc/dphys-swapfile to augment the swap file to 4096
CONF_SWAPSIZE=4096
CONF_MAXSWAP=4096
```
sudo /etc/init.d/dphys-swapfile stop
sudo /etc/init.d/dphys-swapfile start  
```
to activate new swap size, or reboot.

3. Install Jupyter 
`pip install jupyterlab`

4. Install Node
```
sudo /etc/init.d/dphys-swapfile start
sudo apt-get install -y nodejs
```

5. Install yarn - otherwise it will complain later that yarn isn't found
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt install yarn
```
At this point, I have these versions:
![image](https://user-images.githubusercontent.com/4965628/82695863-f1aaf700-9c33-11ea-828f-6762cd15bcf9.png)

6. run `jupyter lab build`  or ` NODE_OPTIONS=--max-old-space-size=4096 jupyter lab build`
Either one will fail. 
Note that jupyter lab runs fine. But a build is needed when adding some extensions. The build fails regardless of the presence or absence of extensions.

![image](https://user-images.githubusercontent.com/4965628/82695987-26b74980-9c34-11ea-95b9-fb4f4bceb6db.png)

- Operating System and version: Raspbian Buster up to date as of May 22/2020
- JupyterLab version: 2.1.2

<summary>Troubleshoot Output</summary>
[jupyter_troubleshoot.txt](https://github.com/jupyterlab/jupyterlab/files/4669687/jupyter_troubleshoot.txt)

**Comment by CleoQc** [comment]
The whole thing started when I tried to install ipywidgets which require a build
pip install ipywidgets

**Comment by jharris1993** [comment]
Can you cross-assemble on a different machine with more memory and then move to the Pi?

**Comment by jasongrout** [comment]
> Can you cross-assemble on a different machine with more memory and then move to the Pi?

Yes. The javascript should be platform independent, so you should be able to take the generated js from building it somewhere else and copy it to the pi.

**Comment by jharris1993** [comment]
Isn't JupyterLab written in Python?

I was thinking - as a workaround - could @CleoQc try the JupyterLab build on a different machine, cross-assembling to the ARM/Raspberry Pi target system? &nbsp;("cross-assembling" isn't the correct term for building on one system with the results for a different target architecture, but I forget what it is.)

If it builds there, but fails when being built on the Pi, that could provide valuable troubleshooting information.

**Comment by jasongrout** [comment]
> Isn't JupyterLab written in Python?

No, only the server portion is in Python. The bulk of JupyterLab code runs in the browser and is Typescript compiled down to Javascript.

> I was thinking - as a workaround - could @CleoQc try the JupyterLab build on a different machine, cross-assembling to the ARM/Raspberry Pi target system?  ("cross-assembling" isn't the correct term for building on one system with the results for a different target architecture, but I forget what it is.)

Yes. The Javascript code is what is being built (the web app). You could build that on another computer and copy the resulting directory over to the pi. We don't have tools to help doing that, but you could copy the directory manually.



> If it builds there, but fails when being built on the Pi, that could provide valuable troubleshooting information.

I think this is explanatory enough: 

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

The build process is quite memory intensive. You can try building with `--minimize=False` to cut down on the memory use.

**Comment by CleoQc** [comment]
Thanks for the pointers.  I will attempt to build on my Windows machine and then transfer. Which files would I need to transfer?
I also have the new Pi 8GB in transit to me, but that might not be sufficient anyway. 

@jasongrout   I had used `--minimize=False` before opening the issue. It didn't help. 

I will report back when I can successfully compile on my laptop

**Comment by CleoQc** [comment]
Not surprisingly, it builds without issues on my laptop.  At this point, all that's needed is to know which files I'm supposed to transfer and where to find them.

Thank you for your support!

**Comment by jharris1993** [comment]
[quote]

all that's needed is to know which files I'm supposed to transfer and where to find them.

[/quote]

 

Isn’t that the truth!  This sounds so much like me struggling with my projects.

**Comment by CleoQc** [comment]
I thought I had done just that, but this time I went in with a hammer and transferred everything
And here it is in all its glory! 
![image](https://user-images.githubusercontent.com/4965628/83282043-098bf900-a1a7-11ea-8bc0-02370a46cef7.png)
Thank you !

**Comment by jasongrout** [comment]
Even easier, you can do `jupyter lab path`. The "Application directory" is what you want

**Comment by jasongrout** [comment]
In jlab 3, there won't need to be a build step, so it should hopefully be much easier.

I'd love to know how the 8GB pi does. I also have a 4GB pi and saw the same problem you did.

**Comment by CleoQc** [comment]
the 8G is stuck in the mail for a while.  Last week I had ordered another 4G and it hasn't moved yet (it's been shipped, but the mail hasn't done anything with it) So it will be a while before I get my 8G...

**Comment by Kevin--R** [comment]
@CleoQc 

I see this issue is closed, but I came across this thread because I was having this same issue with a  Raspberry Pi 4 with 4G of RAM.

I resolved by by adding `export NODE_OPTIONS=--max-old-space-size=2048` to my `.bashrc` file.

I see you tried setting it to 4096, I tried this also and it fails (just guessing but maybe this has to be set to less than max or available RAM?). 

Anyway it works since I set it to 2048 - easier than having to build elsewhere and move files around.

**Comment by sven227** [comment]
`jupyter lab build` works on raspberry pi model 4 with Raspberry Pi OS (64 bit) beta test version
I have the 8GB version - Raspberry Pi 4 Model B Rev 1.4

`uname -a`
Linux raspberrypi 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
