### ISSUE TITLE
Race Condition with Slow Restarting Kernels

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#8477]
## Description

If a kernel takes a while to restart, running cells via "run cell and advance" after a restart has started puts the output into a bad state (missing output and in/out numbers), but it's clear the code really does run in the kernel. While that may sound confusing, I hope this gif clears it up.

This comes up with technology like `dask` where it takes time to release resources at exit. It does not happen when you use `Restart and run all cells`.

## Reproduce
![skippedOutput](https://user-images.githubusercontent.com/1813603/82949004-de1fc900-9f70-11ea-812e-3b45e5ef3f50.gif)
Watching the cell numbers as a good way to understand what's happening.

## Context

- Operating System and version: Windows
- Browser and version: Chrome, 83
- JupyterLab version: 2.1.1

**Comment by dharhas** [comment]
I've seen this happen in my notebooks sometimes when I'm using Dask and starting a Dask Cluster. Don't have a reproducer.

**Comment by mlucool** [comment]
Per above, with setting a long atexit, you should be able to reproduce reliably for human testing (no extension required). Which cells are affected seems to be a race condition.

**Comment by blink1073** [comment]
https://github.com/jupyterlab/jupyterlab/pull/8174 was not backported to 2.1.x, and there is no one with bandwidth to work on a 2.2 release.  We are focusing on getting the 3.0 release out on time.

**Comment by jasongrout** [comment]
Is this solved by #8174?

**Comment by blink1073** [comment]
Not sure, one way to check would be to try the same experiment in 1.2.16.

**Comment by echarles** [comment]
Hi All, I will work on this tomorrow. I will fist try to replicate the issue with @mlucool given scenario (and potentially other slow starting like spark or dask) with and without master (which includes https://github.com/jupyterlab/jupyterlab/pull/8174). Will report findings here and we can define any useful potential next steps.

**Comment by echarles** [comment]
The kernel restart is requested via HTTP Rest API but the `execute_request` can still be sent via WebSocket which should not be the case. Then the `shutdown_reply` arrives after a delay while the previously sent `execute_request` and answered or not...

<img width="952" alt="Screenshot 2020-06-07 at 19 53 29" src="https://user-images.githubusercontent.com/226720/83976208-eecd2900-a8f8-11ea-9a23-ae24913041bf.png">

In the case of `Restart Kernel and run all cells`, the `shutdown_reply` is coming and only then the cells are run. 

Just like https://github.com/jupyterlab/jupyterlab/pull/8174 has introduced a `Initiating` status/hover, we should introduce here a `Terminating` status/hover that would indicate the user what is going on.

To disable the run command, a few options:

- Throttle the received runs and send them afterwards
- Do not honor the run command and show a alert to inform that the kernel is terminating.

In the case of slow starting kernel that https://github.com/jupyterlab/jupyterlab/pull/8174, the run command invoked in `Intializing` state does not give issue as the kernel is not binded to the notebook, so the command is not run at all. In case of slow terminating kernel, we has the issue as the kernel is effectively binded to the notebook.

PS: An alternative option would be to unbind the kernel from the notebook on client side before sending the terminate kernel command to the server, but in this case we loose the advantage that the server is the truth and the client just a display of the server state.

**Comment by mlucool** [comment]
> Throttle the received runs and send them afterwards


This is my preferred solution so long as the UX is consistent. The alert/not honoring may frustrate users.

**Comment by echarles** [comment]
Thx @mlucool for your feedback as for the great and easy replication case you have posted here. It really helped to figure out the cause of the issue.

I will first implement with an alert to the end user(with needed unit tests) to then go to the throttle/queuing mechanism which I expect to be a bit more complex as I don't think the needed machinery reside today in the sources.

Also the interaction to the enduser would be to consider carefully when deferring the execution request after the restart. I am thinking to use one of those:

- The existing kernel status hover (not ideal as the user needs to place his mouse on the status icon).
- The existing bottom status bar.
- A toast which we need to further discuss as it is not available as core/lumino widget today.

**Comment by echarles** [comment]
I have opened https://github.com/jupyterlab/jupyterlab/pull/8562 to fix this issue. For now, the user is prompted that the cell can not be run while a kernel is terminating or restarting. The throttling option could be implemented in a second phase if interest. 

PS: While working on this, a few ideas/questions come to my mind which I have documented in:

- [DISCUSS] Code cell without Kernel should not be runnable https://github.com/jupyterlab/jupyterlab/issues/8563
- [DISCUSS] Running panel should Listen to Kernel Status changes https://github.com/jupyterlab/jupyterlab/issues/8564
- [DISCUSS] Colored Kernel Status Icon https://github.com/jupyterlab/jupyterlab/issues/8565

**Comment by echarles** [comment]
To simulate a slow terminating kernel, add `time.sleep(10)` in  `notebook.services.kernels.kernelmanager:shutdown_kernel()`.

For the slow restaring kernel, add `time.sleep(10)` in `notebook.services.kernels.kernelmanager: restart_kernel()`.
