### ISSUE TITLE
Design of the UX/code for the launcher opening of "activities"

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#848]
This issue is to track the UX/code design of the parts of JupyterLab that allow users to start "activities" (notebooks, terminals, consoles, etc).
## Summary

Right now users can start activities using a number of different approaches:
- The "+" button in the file browser (only file based actvities).
- The main menu for each plugin.
- The "laucher" tab that shows when JupyterLab opens (see below)
## Proposal

I propose that we consolidate all of the different approaches in to a single launcher plugin that manages these things from a code/UI/UX perspective.
- It would have a public API that different plugins that can use to register an activity that includes an icon.
- It would track the CWD of the filebrowser and pass that to newly opened activites, which could use it optionally.
- It would have a UI that displays the activities in a single location
  - It might offer multiple views (icons or list) and provide keyboard shortcuts for navigation
  - Would display the CWD
- Remove the plus button from the filebrowser.
- Remove the new activity actions from the plugin menus.
## Questions
- Where to put the launcher UI? Main dock panel? Left side panel?
- Do we also want to have a "+" button in each tab that opens up a menu based version of the activity launcher?

**Comment by ellisonbg** [comment]
Here are some screenshots of a launcher style UI, the macOS finder:

<img width="602" alt="screen shot 2016-09-06 at 11 13 51 am" src="https://cloud.githubusercontent.com/assets/27600/18285438/3bc013bc-7423-11e6-956a-fd174cdb06b5.png">

<img width="693" alt="screen shot 2016-09-06 at 11 15 20 am" src="https://cloud.githubusercontent.com/assets/27600/18285443/3f182e64-7423-11e6-92d4-adf9ed6c5fd0.png">

**Comment by ellisonbg** [comment]
We are going to keep this open for further design explorations about the launcher. We would like to remove the old launcher and figure out how to get the file browser and launcher to show at the same time.

**Comment by ellisonbg** [comment]
@sccolbert @blink1073 @afshin @jasongrout @cameronoelsen 

We talked on Friday about our model of the current working direction, file browser and launcher. Here is a proposal for the launcher part of it:

## Launcher extension

* We keep a general launcher API that all extensions can use to register "activities".
* We remove the sidebar launcher and the traditional landing page.
* We figure out how to have the cwd passed in by the context that is rendering a UI for the launcher, such as a dock panel tab, menu, launcher ui.
* I would also add a new property to each launcher item that specific if the item accepts a cwd argument.

## File browser

* In our default file browser, we integrate a default launcher UI that uses the cwd of the file browser and which is minimal in design.
* I am thinking of a design that is similar to the last mockup here:

https://cloud.githubusercontent.com/assets/6437976/23672122/787b9ae0-0322-11e7-8b02-795be8a9248d.jpg

but with an "more" icon `. . .` that opens up an additional panel with a list of activities in a minimal way. I can work with Cameron on the design of that part.

## Other launcher UIs

We could keep a variant of the existing sidebar launcher UI that is hidden by default and can be shown by the user. But then we would need to figure out how to handle the cwd in that case.

**Comment by cameronoelsen** [comment]
Here are two mockups of a potential direction that we could take for the launcher. We talked about the new user flow where the user either presses the '+' button in the file browser or selects 'New File' from the navbar. A new window would appear like this allowing the user to select the type of document that they want to create:

### Laucher Cards (Light)
![new-activity-light](https://cloud.githubusercontent.com/assets/6437976/25963387/ea0eb070-3635-11e7-94ac-a53606a3e6a0.jpg)

### Launcher Cards (Dark)
![new-activity-dark](https://cloud.githubusercontent.com/assets/6437976/25963392/edbaf1c0-3635-11e7-8a02-bb62a386db88.jpg)

I personally think that the light launcher cards fit more into the default theme that we are making for Lab. However, I definitely think that a dark version of the launcher items will be needed when we start making themes for the entire JupyterLab environment down the road. Let me know what you guys think!

**Comment by blink1073** [comment]
Looks great!

**Comment by ellisonbg** [comment]
Fixed in master.
