### ISSUE TITLE
Output Clickable hyperlink bug

### ISSUE THREAD

**Issue by jccorte20** [jupyterlab/jupyterlab#8485]
### Description 
Hi there,

I've an issue on clickables Hyperlinks on Jupyterlab output cell.
On Jupyterlab, since 2.0 version, the clickables hyperlinks converted add `amp;` chars.

### Example
This an example that I encountered : 

![image](https://user-images.githubusercontent.com/11487521/83128243-7043e080-a0db-11ea-900e-e18eaba71489.png)

### Reproduce
Encountered error on :
- jupyteralab since 2.0 version
- jupyteralab since 2.0 version on private browser

Work fine : 
- on classic Jupyter Notebook
- on jupyterlab 1.2.0 version (without clickable link)

### Packages
attrs==19.3.0
backcall==0.1.0
bleach==3.1.5
cachetools==4.1.0
certifi==2020.4.5.1
chardet==3.0.4
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
google-api-core==1.17.0
google-api-python-client==1.8.4
google-auth==1.15.0
google-auth-httplib2==0.0.3
googleapis-common-protos==1.51.0
httplib2==0.18.1
idna==2.9
importlib-metadata==1.6.0
ipykernel==5.3.0
ipython==7.14.0
ipython-genutils==0.2.0
jedi==0.17.0
Jinja2==2.11.2
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-core==4.6.3
**jupyterlab==2.1.3**
jupyterlab-server==1.1.5
MarkupSafe==1.1.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.6
**notebook==6.0.3**
numpy==1.18.4
oauth2client==4.1.3
packaging==20.4
pandas==1.0.3
pandocfilters==1.4.2
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.8.0
prompt-toolkit==3.0.5
protobuf==3.12.2
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyDrive==1.3.1
Pygments==2.6.1
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
pyzmq==19.0.1
requests==2.23.0
rsa==4.0
Send2Trash==1.5.0
six==1.15.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
uritemplate==3.0.1
urllib3==1.25.9
wcwidth==0.1.9
webencodings==0.5.1
zipp==3.1.0

**Comment by jasongrout** [comment]
Thanks. This is also reported in https://github.com/jupyterlab/jupyterlab/issues/8376. Let's move the discussion over there to consolidate things.
