### ISSUE TITLE
2.2 Release

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8488]
## Description
It has become increasingly difficult to [backport](https://github.com/jupyterlab/jupyterlab/pull/8486#issuecomment-635317953) things to the the 2.1.x branch.  I think now is a good time to cut a 2.2 release and start thinking about moving master toward 3.0 with things like #7416.

**Comment by jasongrout** [comment]
Note that master already has breaking changes, IIRC, so we if we release a 2.2, we'd need to audit it for changes that are backwards compatible.
