### ISSUE TITLE
File Browser - Visibility Beyond Current Working Directory

### ISSUE THREAD

**Issue by JDLEarley** [jupyterlab/jupyterlab#8491]
Hello JupyterLab community, I'm part of the team from UC Irvine (along with @grey280, @jabumeri, @emilythefan, and @Nastraughn) that is helping to design a new file browser experience. As the community knows, JupyterLab treats the directory from which it is launched as the top-level directory in the file browser -- even if that is not the "true" top-level directory in the local file system. Our team has come to call this the "ceiling problem," because our research suggests that users may conceive of the constraint as a ceiling blocking the way "upwards" through their local file system.

We know that there are important technical and security reasons why JupyterLab was originally set up this way. But we're curious as to whether those considerations are still important in our file browser redesign. Have any of these technical or security issues changed since JupyterLab was created? 

Ideally, our redesign would remove the ceiling if possible (giving the user "open air" above JuptyerLab's current working directory). But, we can also take the design in a couple other directions if those technical constraints require the ceiling to remain for safety purposes. Thoughts on the continued need for the "ceiling" are appreciated! Thanks!

**Comment by jasongrout** [comment]
> Have any of these technical or security issues changed since JupyterLab was created?

I don't think so. This restriction actually came from the classic notebook, and followed the well-established pattern of web servers only serving from a certain directory or below.

Note that you can start JupyterLab (or Jupyter Notebook) from any directory and control the top-level directory with the `--notebook-dir` option. For example, `jupyter notebook --notebook-dir=/` or `jupyter lab --notebook-dir=/` will start the top-level directory at the root of the filesystem.

**Comment by jasongrout** [comment]
Closing as answered.
