### ISSUE TITLE
jupyter lab build failed

### ISSUE THREAD

**Issue by Lips7** [jupyterlab/jupyterlab#8505]
## jupyter lab build failed

[I 22:05:09.822 LabApp] Building jupyterlab assets (build:dev)
[W 22:06:00.803 LabApp] Build failed, running a clean and rebuild
[I 22:06:00.828 LabApp] Cleaning /home/lips/anaconda3/share/jupyter/lab...
[W 22:06:00.829 LabApp] 500 POST /lab/api/build?1591107783960 (127.0.0.1): 'AppOptions' object has no attribute 'all'
[W 22:06:00.829 LabApp] 'AppOptions' object has no attribute 'all'
[E 22:06:00.830 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "0",
      "Dnt": "1",
      "X-Xsrftoken": "2|2ff8826a|58a70f5434ef09d76ff7c0c1464b4b43|1589726699",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab?",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en,zh-CN;q=0.9,zh;q=0.8,und;q=0.7",
      "Cookie": "_xsrf=2|2ff8826a|58a70f5434ef09d76ff7c0c1464b4b43|1589726699; username-localhost-8890=\"2|1:0|10:1589728517|23:username-localhost-8890|44:YzAzMGUxMjBhMzkwNDVhNmI4ZTRlMjFiZDhlNGVhMTM=|d2bdaa61e1701a75405c9f626c2bf32826e17cab8fd32c79f5bddb2c39a9596b\"; username-localhost-8888=\"2|1:0|10:1590896785|23:username-localhost-8888|44:NjQ4ZGRjZmUyM2ViNDczNmFkYWUwM2U2NDA1Y2M3NGY=|2465a6891f1a3ac4792ce4464053ae8fd16d38ba3310a0d569669db3e07e751d\""
    }
[E 22:06:00.830 LabApp] 500 POST /lab/api/build?1591107783960 (127.0.0.1) 51356.03ms referer=http://localhost:8888/lab?

## log
❯ cat /tmp/jupyterlab-debug-bhnouz7z.log
[LabBuildApp] Building in /home/lips/anaconda3/share/jupyter/lab
[LabBuildApp] Node v13.13.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /home/lips/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.57s.

[LabBuildApp] > node /home/lips/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.35s.

[LabBuildApp] > node /home/lips/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve 'worker-loader' in '/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/pdfjs-dist'
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:925:10
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/neo-async/async.js:6877:13
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at done (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/neo-async/async.js:2925:13)
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:449:23
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
resolve 'worker-loader' in '/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/pdfjs-dist'
  Parsed request is a module
  using description file: /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/pdfjs-dist/package.json (relative path: .)
    resolve as module
      /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/pdfjs-dist/node_modules doesn't exist or is not a directory
      /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      /home/lips/anaconda3/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /home/lips/anaconda3/share/jupyter/node_modules doesn't exist or is not a directory
      /home/lips/anaconda3/share/node_modules doesn't exist or is not a directory
      /home/lips/anaconda3/node_modules doesn't exist or is not a directory
      /home/lips/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/lips/anaconda3/share/jupyter/lab/staging/node_modules
        using description file: /home/lips/anaconda3/share/jupyter/lab/staging/package.json (relative path: ./node_modules)
          using description file: /home/lips/anaconda3/share/jupyter/lab/staging/package.json (relative path: ./node_modules/worker-loader)
            no extension
              /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/worker-loader doesn't exist
            .js
              /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/worker-loader.js doesn't exist
            .json
              /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/worker-loader.json doesn't exist
            as directory
              /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/worker-loader doesn't exist
child_process.js:632
    throw err;
    ^

Error: Command failed: /home/lips/anaconda3/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (/home/lips/anaconda3/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 26582,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/home/lips/anaconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/home/lips/anaconda3/lib/python3.7/site-packages/jupyterlab/labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "/home/lips/anaconda3/lib/python3.7/site-packages/jupyterlab/labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/home/lips/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/home/lips/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab

**Comment by tlperini** [comment]
Same problem here.
We have scheduled daily builds running at 1AM UTC.
We had successful builds until last sunday (may 31st) 1:20AM UTC.

**Comment by Lips7** [comment]
seems like node's problem

**Comment by Lips7** [comment]
ok I uninstall latex extension, all is done now

**Comment by donotpush** [comment]
@Lips7 we also facing the same issue, and it not clear for us that is related to the latex extension.

Could you give us more information? Cheers!

**Comment by donotpush** [comment]
I opened an issue, it is indeed latex extension https://github.com/jupyterlab/jupyterlab-latex/issues/135
