### ISSUE TITLE
Close Tab closes incorrect tab if tabs have same title

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab#8509]
## Description

Using the Close Tab from the context menu on a different tab will close the current tab if the two tabs have the same title.

![close-tab](https://user-images.githubusercontent.com/10111092/83555319-19c01300-a4dc-11ea-90e2-1c2bc4ca5523.gif)

I encountered this with diffs in the `jupyterlab-git` extension but it happens for any files with the same name, including markdown files and their previews:
![close-tab-2](https://user-images.githubusercontent.com/10111092/83555190-e8dfde00-a4db-11ea-88e5-cc74e3271f86.gif)

I think that this is distinct from https://github.com/jupyterlab/jupyterlab/issues/6008#issuecomment-466085325 as `Close All Other Tabs` now works as expected no matter what widget is currently focused.
![close-all-works](https://user-images.githubusercontent.com/10111092/83555475-568c0a00-a4dc-11ea-8835-d2758ff90bd4.gif)

## Reproduce
1. Open two tabs with the same name
2. Focus one of the tabs
3. Right click the other tab and select Close Tab
4. Focused tab will be closed

## Expected behavior
The tab I right clicked on would be closed.
My guess is that the widget id needs to be used somehow here:
https://github.com/jupyterlab/jupyterlab/blob/e7317f21b48183423e375dc266476a4289eb0fa3/packages/application-extension/src/index.tsx#L605-L614

compare to the id checking in Close All Other Tabs
https://github.com/jupyterlab/jupyterlab/blob/e7317f21b48183423e375dc266476a4289eb0fa3/packages/application-extension/src/index.tsx#L628-L646
## Context

- Operating System and version: PopOS 20.04
- Browser and version: Firefox 75
- JupyterLab version: 2.1.3

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by ianhi** [comment]
Maybe some trickiness is that it may not be possible to determine if a command was called via a context menu or via a keyboard shortcut? It seems that the current function is oriented towards the keyboard shortcut, rather than the context menu. But using the `contextMenuWidget` seems like it would break the keyboard shortcut functionality.

**Comment by krassowski** [comment]
Great find! Could we just combine the two approaches, i.e. first try `contextMenuWidget` and if the widget is not returned, then resort to the current version (as you say optimized for the keyboard shortcut)?

**Comment by ianhi** [comment]
> Could we just combine the two approaches, i.e. first try `contextMenuWidget` and if the widget is not returned, then resort to the current version

Happily enough whoever wrote `contextMenuWidget` had the future in mind, and it alone solves this problem
