### ISSUE TITLE
User Configured Webpack

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#8514]
### Problem

At times I would like more control of webpack. While, I acknowledge giving access to webpack opens up a very large, and complex API that most python users won't want to know about, it has a some good use cases.

1. At times, I need to set [aliases](https://webpack.js.org/configuration/resolve/#resolvealias). This is perhaps the biggest use case.
2. I may want to change how webpack [chunks](https://webpack.js.org/plugins/split-chunks-plugin/). For example, if I put a proxy in front to support HTTP2 would not want it to chunk the same way as we do for HTTP1.1. Similar things are true if I know my network is fast vs. slow.
3. I may want to template into variables during built time from the environment.

### Proposed Solution
Add a config option to point to a JS file. This function would receive the current jupyterlab webpack config and be allowed to modify it in any way the advanced user sees fit. The modified config would then be passed to webpack.

**Comment by blink1073** [comment]
Hi @mlucool, we are completely changing the build system for 3.0, see https://github.com/jupyterlab/jupyterlab/pull/8385

**Comment by blink1073** [comment]
The user won't see webpack at all, only the extension author.

**Comment by mlucool** [comment]
I have found the new build system to support most of what I need. I'll open specific requests as issues arise. Great work!
