### ISSUE TITLE
running jupyter lab build gives ModuleNotFoundError: Module not found: Error: Can't resolve 'worker-loader' in '/usr/share/jupyter/lab/staging/node_modules/pdfjs-dist'

### ISSUE THREAD

**Issue by joequant** [jupyterlab/jupyterlab#8518]
## Description

Running jupyter lab build gives the error

'''
> node /usr/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve 'worker-loader' in '/usr/share/jupyter/lab/staging/node_modules/pdfjs-dist'
    at /usr/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:925:10
    at /usr/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /usr/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /usr/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /usr/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at /usr/share/jupyter/lab/staging/node_modules/neo-async/async.js:6877:13
    at /usr/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at done (/usr/share/jupyter/lab/staging/node_modules/neo-async/async.js:2925:13)
    at /usr/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:449:23
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38
    at /usr/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/usr/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
resolve 'worker-loader' in '/usr/share/jupyter/lab/staging/node_modules/pdfjs-dist'
  Parsed request is a module
  using description file: /usr/share/jupyter/lab/staging/node_modules/pdfjs-dist/package.json (relative path: .)
    resolve as module
      /usr/share/jupyter/lab/staging/node_modules/pdfjs-dist/node_modules doesn't exist or is not a directory
      /usr/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      /usr/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /usr/share/jupyter/node_modules doesn't exist or is not a directory
      /usr/share/node_modules doesn't exist or is not a directory
      /usr/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /usr/share/jupyter/lab/staging/node_modules
        using description file: /usr/share/jupyter/lab/staging/package.json (relative path: ./node_modules)
          using description file: /usr/share/jupyter/lab/staging/package.json (relative path: ./node_modules/worker-loader)
            no extension
              /usr/share/jupyter/lab/staging/node_modules/worker-loader doesn't exist
            .js
              /usr/share/jupyter/lab/staging/node_modules/worker-loader.js doesn't exist
            .json
              /usr/share/jupyter/lab/staging/node_modules/worker-loader.json doesn't exist
            as directory
              /usr/share/jupyter/lab/staging/node_modules/worker-loader doesn't exist
child_process.js:651
    throw err;
    ^
Error: Command failed: /usr/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Object.<anonymous> (/usr/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 45337,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
JupyterLab failed to build
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield
  File "/usr/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 104, in start
    build(clean_staging=self.should_clean,
  File "/usr/lib/python3.8/site-packages/jupyterlab/commands.py", line 459, in build
    return handler.build(name=name, version=version, static_url=static_url,
  File "/usr/lib/python3.8/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)
RuntimeError: JupyterLab failed to build

'''

## Reproduce

Build jupyterlab and use cli to install several extensions such as ipyvolume

## Expected behavior

should not cause error

## Context

- Operating System and version:

linux

- Browser and version:
- JupyterLab version:

2.1.4

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /usr/bin
        /usr/lib64/python38.zip
        /usr/lib64/python3.8
        /usr/lib64/python3.8/lib-dynload
        /usr/lib64/python3.8/site-packages
        /usr/lib/python3.8/site-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.8.3 (default, May 23 2020, 19:40:11) 
        [GCC 10.1.0]

platform.platform():
        Linux-5.6.13-server-1.mga8-x86_64-with-glibc2.2.5

which -a jupyter:
        /usr/bin/jupyter
        /bin/jupyter

pip list:
        Package                           Version
        --------------------------------- ------------
        absl-py                           0.9.0
        ad                                1.3.2
        aiodns                            1.1.1
        aiofile                           1.5.2
        aiofiles                          0.5.0
        aioftp                            0.16.0
        aiohttp                           3.6.2
        aiostream                         0.4.1
        alembic                           1.4.2
        algobroker                        0.0.12
        algorithmx                        1.1.3
        alipy                             1.2.1
        altair                            4.1.0
        ansiwrap                          0.8.4
        apache-airflow                    1.10.10
        apispec                           1.3.3
        appdirs                           1.4.3
        arabic-reshaper                   2.0.15
        arch                              0+unknown
        argcomplete                       1.11.1
        arrow                             0.15.6
        arviz                             0.8.3
        asteval                           0.9.18
        astroML                           0.4.1
        astropy                           4.0.1.post1
        astunparse                        1.6.3
        async-generator                   1.10
        async-timeout                     3.0.1
        attrs                             19.3.0
        autobahn                          20.4.3
        Automat                           0.7.0
        autopep8                          1.5.3
        Babel                             2.6.0
        backcall                          0.1.0
        backports.csv                     1.0.7
        base58                            2.0.0
        bash-kernel                       0.7.2
        beakerx                           1.4.1
        beautifulsoup4                    4.9.1
        binaryornot                       0.4.4
        biopython                         1.77
        bitarray                          1.2.2
        bitcoin-etl                       1.3.1
        bitcoin-price-api                 0.0.4
        bitcoin-tools                     0.0.13
        bitfinex-tencars                  0.0.3
        bizdays                           0.3.0
        black                             19.10b0
        blaze                             0.10.1
        bleach                            3.1.4
        bokeh                             2.0.2
        boto                              2.49.0
        boto3                             1.13.23
        botocore                          1.16.23
        bqplot                            0.12.12
        branca                            0.3.1
        brewer2mpl                        1.4.1
        Brotli                            1.0.7
        bs4                               0.0.1

</pre>
</details>

**Comment by RayAlto** [comment]
I encountered the same problem as you, it seems like Latex extension's problem. I uninstalled Latex extension and everything is back to normal.

**Comment by jasongrout** [comment]
I agree that it looks like a problem with an extension. I'd encourage you to file an issue with that extension's communication channels.

**Comment by jasongrout** [comment]
It looks like a similar issue was already filed: https://github.com/jupyterlab/jupyterlab-latex/issues/135
