### ISSUE TITLE
Replace usage of insensitive terms

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8533]
We are currently using the terms "blacklist" and "whitelist" to describe what could just as readily be called "blocklist" and "allowlist", cf. https://go-review.googlesource.com/c/go/+/236857/

**Comment by blink1073** [comment]
cc @choldgraf who may want to make a similar change in JupyterHub.

**Comment by telamonian** [comment]
would just plain `exclude` and `include` be appropriate here?

**Comment by blink1073** [comment]
Yeah I think in our case those are appropriate as well.

**Comment by echarles** [comment]
I feel `blocklist` or `excludelist` mean what it is.

`allowlist` is a bit closer than `includelist`  to the notion that only the listed extension could be installed.

**Comment by blacklistisnotracist** [comment]
I do support this as long as no one starts to make this about BLM because these words have nothing to do with racial discrimination

**Comment by blink1073** [comment]
Let's follow the lead of the JupyterHub folks: https://github.com/jupyterhub/team-compass/issues/299#issuecomment-645927944

**Comment by blink1073** [comment]
Let's go with `allowed_extensions` and `blocked_extensions`, to make it clear what their function is.

This needs to be done in a backward-compatible way from the server standpoint, starting [here](https://github.com/jupyterlab/jupyterlab_server/blob/bd3779cd245e8598aa90bc68e1e5bfba3657413f/jupyterlab_server/app.py#L20).

This diff demonstrates deprecating a trait: https://github.com/jupyterhub/jupyterhub/pull/3090/files#diff-8263a63fc781091dc1195f33f5ea7fc4

**Comment by echarles** [comment]
> This needs to be done in a backward-compatible way from the server standpoint, starting here.

Do you mean that any potential users using today that black/white naming should be able to continue using it? Or they should be warned to change? Or they should fail with correct explanation?

**Comment by blink1073** [comment]
I mean that they should still be able to use the `traitlet` but get a deprecation warning, which is what JupyterHub did.

**Comment by choldgraf** [comment]
In case others are interested to follow on w/ the JupyterHub team's conversation and progress around this: https://github.com/jupyterhub/team-compass/issues/299

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/inclusive-language-in-jupyter-source-code/5266/2
