### ISSUE TITLE
`jp-CodeMirrorEditor-static`HTML element class

### ISSUE THREAD

**Issue by AlbertHilb** [jupyterlab/jupyterlab#8537]
In the [base.css][1] stylesheet from the codemirror package, there are two rules associated to the class selector `.jp-CodeMirrorEditor-static`, but I can't find any other occurence of the string `jp-CodeMirrorEditor-static` into the entire jupyterlab source tree, so I assume HTML elements with such a class can not exist. Can those rules be safely removed?

[1]: https://github.com/jupyterlab/jupyterlab/blob/master/packages/codemirror/style/base.css

**Comment by blink1073** [comment]
I'd say yes, they can be removed.
