### ISSUE TITLE
Issues in extensions whitelist/blacklist documentation

### ISSUE THREAD

**Issue by LucasVerneyDGE** [jupyterlab/jupyterlab#8539]
Hi,

There seems to be some mistakes in the whitelist/blacklist documentation for the extension manager.

1. https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/extensions.rst#listings

> Only one mode at a time is allowed. If you or your server administrator configures both black and white listings, the extension manager will be disabled.

However, it seems that enabling both blacklist and whitelist actually prevents the server from starting https://github.com/datalayer-contrib/jupyterlab-server/blob/master/jupyterlab_server/handlers.py#L308-L311.

2. https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/extensions.rst#listing-configuration

It might be useful to better emphasize that `blacklist_uris` (resp `whitelist_uris`) expects a URI to a `blacklist` file as shown below. At first, I was actually thinking this was a comma-separated list of extensions (or URIs of extensions), which was obviously not working.

Thanks!
Best

**Comment by echarles** [comment]
> However, it seems that enabling both blacklist and whitelist actually prevents the server from starting https://github.com/datalayer-contrib/jupyterlab-server/blob/master/jupyterlab_server/handlers.py#L308-L311.

There has been some last minute change and the doc does not reflect that. If you set both white and black list, the server will not start and it is intended.

> It might be useful to better emphasize that blacklist_uris (resp whitelist_uris) expects a URI to a blacklist file as shown below. At first, I was actually thinking this was a comma-separated list of extensions (or URIs of extensions), which was obviously not working.

Good to precise that also in the doc

@LucasVerneyDGE Would you open a PR to fix the doc or do you prefer me to do that?

**Comment by LucasVerneyDGE** [comment]
Here is a proposal for a PR to fix the doc https://github.com/jupyterlab/jupyterlab/pull/8540. Thanks for the very quick feedback on this!
