### ISSUE TITLE
Cell Prompt and Code Fonts are Inconsistent

### ISSUE THREAD

**Issue by dakoop** [jupyterlab/jupyterlab#8552]
## Description

I've noticed that the font used in the cell prompt versus that used in other code-like contexts does not match. I've tracked this down to #5123 which modified `--jp-code-font-family` but left `--jp-cell-prompt-font-family` unchanged. Note that both were the same `Source Code Pro, monospace` string before that change so it seems reasonable to expect that they were intended to be the same font. This was also noted in [#5547](https://github.com/jupyterlab/jupyterlab/pull/5547#issuecomment-434008713).

<img width="273" alt="Screen Shot 2020-06-12 at 12 38 00 PM" src="https://user-images.githubusercontent.com/2249780/84531059-96f04280-aca9-11ea-85c2-4ae41cc142c1.png">

## Reproduce

This is most visible in Chrome (macOS) which (at least for my configuration) defaults `monospace` to `Courier`. Safari (macOS) uses the same font for both.

## Expected behavior

The font-family for the cell prompt and the cell content should be the same.

## Context

- Operating System and version: macOS 10.15.5
- Browser and version: Chrome v83
- JupyterLab version: 2.2.0a0

**Comment by Damon-Hong** [comment]
Hi, I have noticed this problem for a while now. How can we solve this problem? Thanks.

**Comment by dakoop** [comment]
I wrote PR #8553 to address this. You need to rewrite one CSS variable in the theme:

```css
 --jp-cell-prompt-font-family: var(--jp-code-font-family-default);
```

**Comment by Damon-Hong** [comment]
Thank you for this. I have also noticed that the output font family is also fixed even you change the code cell font family. Do you know how to fix that issue? Thanks again!

**Comment by dakoop** [comment]
This depends on the type of output (the [rendermime](https://github.com/jupyterlab/jupyterlab/tree/master/packages/rendermime) package supports many types of outputs). However, something like stdout is rendered as `pre` which defaults to `--jp-code-font-family`: https://github.com/jupyterlab/jupyterlab/blob/09b739d44d5dee6ad44b0243871c12b772b1b2d8/packages/theme-light-extension/style/index.css#L8-L17 If you want to change the default `--jp-code-font-family`, note that the defaults are set in `--jp-code-font-family-default`: https://github.com/jupyterlab/jupyterlab/blob/09b739d44d5dee6ad44b0243871c12b772b1b2d8/packages/theme-light-extension/style/variables.css#L183-L184

**Comment by Damon-Hong** [comment]
Thank you so much. Can I override these settings via advanced settings page in jupyter lab? For example, in the theme section?

**Comment by dakoop** [comment]
I'm not aware of a way to do this from advanced settings currently. PR #7130 looks like it will do what you're asking for. In the meantime, if you don't want to create a new theme, you could check out the [custom-css plugin](https://github.com/wallneradam/jupyterlab-custom-css).

**Comment by Damon-Hong** [comment]
Thank you. That helps me a lot!!!
