### ISSUE TITLE
Update ToC icon usage to LabIcon

### ISSUE THREAD

**Issue by marthacryan** [jupyterlab/jupyterlab#8557]
Currently the ToC package uses icons located in `packages/toc/style/img`, but these icons should be moved to `ui-components` and imported to ToC using LabIcon. Referenced in #8546.

**Comment by marthacryan** [comment]
@ajbozarth Has volunteered to help out with this.

**Comment by ajbozarth** [comment]
Unassigned myself for now. I don't have the bandwidth for this at the moment and this is a good first issue for others to learn more about LabIcon
