### ISSUE TITLE
I'm not seeing - Select All Cells with this Tag - option

### ISSUE THREAD

**Issue by LukaPitamic** [jupyterlab/jupyterlab#8566]
## Description

Option `Select All Cells with this Tag` is missing since extension was included by default into JL. 
Some of our workflows are dependent on executing parts of the notebook which was easily achieved with this option and then executing selected cells only. 

## Reproduce

1. open cell tags UI (left side panel)
2. there is no option: Select All Cells with this Tag

## Context

- Operating System and version: MacOS
- Browser and version: Brave 1.2.80
- JupyterLab version: 2.1.3

**Comment by andswitch** [comment]
Imho this is an important feature for large notebooks. In that situation I want to create reusable code cells. Using tags, I can group dependent code cells. However, I can't efficiently run a group without this option!

**Comment by NPetz** [comment]
Hello, I'd like to try working on this one as my first contribution to OSS if nobody else is working on it and if it is needed.

As far as UI goes, would a mashup of the extension this feature comes from with the current UI be ok?
Something like in the rightmost screenshot.
<div style="display:flex;">
<img width="248" alt="current" src="https://user-images.githubusercontent.com/38439788/120341835-303cbc80-c332-11eb-86b3-cf6dab4ec04e.png">
<img width="226" alt="extension" src="https://user-images.githubusercontent.com/38439788/120341821-2ca93580-c332-11eb-8b50-5405d0d6ec09.png">
<img width="226" alt="future" src="https://user-images.githubusercontent.com/38439788/120342524-d5579500-c332-11eb-8661-29f039d21aef.png">
</div>

**Comment by LukaPitamic** [comment]
@NPetz WTG!!! It looks more than perfect to me

**Comment by krassowski** [comment]
Did this go into the TOC package? I wonder if it would be better to have it in cell tools. What is the rationale for having it in TOC rather than in cell tools?

**Comment by NPetz** [comment]
@krassowski 

I think it makes more in sense in the TOC because the cell tools (notebook tools?) is used to _edit_ cells, whereas the TOC is used to _filter/select_ cells in the entire notebook.

What do you think?

**Comment by LukaPitamic** [comment]
@NPetz (IMH) I agree with @krassowski - same tool for making tags in the first place and selecting cells with tags makes perfect sense. However the effort being put into adding feature is worth more. This was a feature I was missing for a long time.
