### ISSUE TITLE
Markdown cell FileBrowser drag-and-drop attach

### ISSUE THREAD

**Issue by jamesdbrock** [jupyterlab/jupyterlab#8569]
### Reproduce

Drag an image file from the JupyterLab FileBrowser to a notebook Markdown code cell. It's not droppable, cannot be attached to the Markdown code cell.

### Expected behavior

In JupyterLab 1.2, one could drag an image from the JupyterLab FileBrowser to attach to a Markdown cell. https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#id5 One could not drag an image from the OS (Gnome shell) to attach to a Markdown cell. 

After JupyterLab 2.0, one can drag an image from the OS (Gnome shell) to attach to a Markdown cell. One cannot drag an image from the JupyterLab FileBrowser to attach to a Markdown cell.

So in JupyterLab 2.0, we lost the ability to drag an image from the JupyterLab FileBrowser to attach to a Markdown cell. It would be nice to get that ability back.

### Context

No errors are produced in the Javascript console, or in any other place I can see. The drop-attach operation from FileBrowser to Markdown cell just fails silently.

**Comment by jamesdbrock** [comment]
Here's an easy way to reproduce the issue from Docker builds of __base-notebook__. https://hub.docker.com/r/jupyter/base-notebook/tags?page=1&name=lab-

Run JupyterLab from one of the following images. “Upload” an image file to `/home/jovyan` in the FileBrowser. Launch a new Python notebook, change the type of the first cell to __Markdown__. Then try to drag your image file from the FileBrowser to the __Markdown__ cell.

### JupyterLab 1.2.5

```
docker run --rm -p 8888:8888 --env JUPYTER_ENABLE_LAB=yes --env JUPYTER_TOKEN=x jupyter/base-notebook:lab-1.2.5
```

### JupyterLab 2.0.1

```
podman run --rm -p 8888:8888 --env JUPYTER_ENABLE_LAB=yes --env JUPYTER_TOKEN=x jupyter/base-notebook:lab-2.0.1
```

**Comment by ianhi** [comment]
Just to connect these issue - this is the same as: https://github.com/jupyterlab/jupyterlab/issues/8205

**Comment by jasongrout** [comment]
Let's consolidate the discussion over there at the earlier issue, then. Thanks! I'll put a link there pointing to this report as well.

**Comment by jasongrout** [comment]
@ianhi - I invited you to the triage team so you'd be able to help manage and triage issues.

**Comment by ianhi** [comment]
@jasongrout  thank you. Are there any codified guidelines/best practices for how to manage/triage issues?

**Comment by jasongrout** [comment]
Great question. I don't remember if we have anything written down. Sounds like that is something that we should do!

**Comment by jamesdbrock** [comment]
> Also the relevant code for the markdown cells can be found here:

From v1.2.0
https://github.com/jupyterlab/jupyterlab/releases/tag/v1.2.0

https://github.com/jupyterlab/jupyterlab/blob/ff0d9b7fef09489ee6bdd317ad39b9aa19914c6e/packages/cells/src/widget.ts#L1152-L1153

And in v2:

https://github.com/jupyterlab/jupyterlab/blob/732de5f59048b81ddb10bfffdc11e56d3be5e882/packages/cells/src/widget.ts#L1160-L1161

**Comment by ianhi** [comment]
Commenting this on this issue as well so its easy to find: this was fixed by https://github.com/jupyterlab/jupyterlab/pull/8965 so I think it will be in jlab3 but not in jlab 2

**Comment by blink1073** [comment]
I am backporting it to 2.x as well in #8966
