### ISSUE TITLE
Mouse wheel zoom doesn't work in plotly 3d output

### ISSUE THREAD

**Issue by zakutin** [jupyterlab/jupyterlab#8576]
The mouse wheel zoom is not working in plotly 3d output in jupyterlab using Firefox. In Chromium-based browser everything is fine.

jupyterlab-plotly (plotly JupyterLab extension): 4.8.1
nodejs: 14.4.0
Firefox 77.0.1 (64-bit)
jupyter-core: 4.6.3
jupyterlab: 2.1.4
plotly: 4.8.1
Python: 3.8.2

Below is the ipynb file to test:
[mesh3d_test.zip](https://github.com/jupyterlab/jupyterlab/files/4788381/mesh3d_test.zip)

**Comment by jasongrout** [comment]
Can you open the issue with the plotly jupyterlab extension, then? That is not developed by us.

I think this is the repo: https://github.com/plotly/plotly.py

**Comment by zakutin** [comment]
@jasongrout, thanks for reply, will do this.

I thought the cell output area belongs to jupyterlab. Or not?

**Comment by jasongrout** [comment]
Yes, the cell output area is from JupyterLab. Do you think this is a JupyterLab issue rather than a plotly issue? Does mouse scrolling not work for other things in the output that it should?

**Comment by jasongrout** [comment]
(for example, you can "enable scrolling for outputs" with the right-click menu, then you should be able to scroll that output)

**Comment by jasongrout** [comment]
pythreejs and ipyleaflet also use scrolling to zoom, IIRC.

**Comment by zakutin** [comment]
Here is the demonstration.

Edge (other chromium-based browser):
![edge](https://user-images.githubusercontent.com/53969222/84819857-01421380-b019-11ea-9ac6-e624895783e7.gif)

Firefox:
![firefox](https://user-images.githubusercontent.com/53969222/84819884-0b641200-b019-11ea-99e7-cb48a98f4449.gif)

**Comment by jasongrout** [comment]
Thanks. My guess is that this is a plotly issue, especially since JupyterLab is not scrolling when you do the mousewheel on the plot in firefox.

**Comment by zakutin** [comment]
Thank you for advice!
