### ISSUE TITLE
2.2 Release Plans

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#8585]
We were originally planning on making the next release 3.0, and skipping a minor release. However, we [have decided to push back the 3.0 release](https://github.com/jupyterlab/jupyterlab/issues/8038#issuecomment-645542556) and so it makes sense to do another minor release.

Unfortunately, we have started merging in breaking changes into master. So we need to figure out which PRs that were merged in since the last release should be released under 2.2.

Please make sure any PRs and issues that need to be released in the minor release (which cannot be changes) are added to [that milestone](https://github.com/jupyterlab/jupyterlab/milestone/53?closed=1).

My tentative timeline is:

* Wednesday 6/24: All relevant PRs should be merged, finish moving PRs to correct milestone
* Thursday 6/25: Create git branch for release, cherry pick commits, generate release notes, release first RC
* Thursday 7/2: Release final version (pending any large issues that arise from pre release)

Please comment if you have suggestions for the timeline.

**Comment by saulshanabrook** [comment]
@jasongrout @blink1073 Was thinking of basing the 2.2.x branch off of the 2.1.x (it just had a 2.1.5 release). Does this seem reasonable? I assume everything included in the latest 2.1.x patch releases we want in the 2.2.0 release.

**Comment by jasongrout** [comment]
> Was thinking of basing the 2.2.x branch off of the 2.1.x (it just had a 2.1.5 release). Does this seem reasonable?

Sounds good.


> I assume everything included in the latest 2.1.x patch releases we want in the 2.2.0 release.

Definitely.

**Comment by blink1073** [comment]
Sounds good, note that there may be a 2.1.6 soon based on this [comment](https://github.com/jupyterlab/jupyterlab/issues/8587#issuecomment-647857370).

**Comment by saulshanabrook** [comment]
I see some PRs to the 2.1.x branch are backports from master and some are not. 

Some of them that are backports, the primary PR would target 2.2.0, so I guess I just need to make sure to not merge in any of the PRs in master that were backported even if though they will target 2.2.0? That sound right?

**Comment by saulshanabrook** [comment]
@blink1073 could you clarify why some PRs were merged directly into 2.1.x, like https://github.com/jupyterlab/jupyterlab/pull/8599, instead of backported? Should they not be included in 2.2.0? Or in 3.0.0?

**Comment by blink1073** [comment]
If they were backported manually there should still be a "Needs manual backport " label, otherwise there should be an actuall meesseeks PR.  There may have been a couple exxeptions to that rule for DevOps PRs.

**Comment by blink1073** [comment]
Yes, #8599 was a result of https://github.com/jupyterlab/jupyterlab/pull/8593#issuecomment-647593766

**Comment by saulshanabrook** [comment]
Ah I see cool, yeah just a manual backport! Thank you!

**Comment by saulshanabrook** [comment]
Now just thinking of maybe instead just basing off master, but manually removing all merge commits for 3.0.0 targeted PRs...

**Comment by saulshanabrook** [comment]
I am realizing now that @blink1073 [already published](https://github.com/jupyterlab/jupyterlab/commit/caaecc573bd511521fce73b0aa718ea4264fc016) a 2.2.0 alpha.

It included (AFAIK) a few commits that are tagged to the 3.0.0 milestone:

* #8427
* #8422
* #8445 
* #8451 
* #8454
* #8456

There are also a number of other merges of 3.0.0 PRs that happened after that alpha:

* #8547
* #8549
* #8538
* #8531


I guess the task ahead is:

> For each of these PRs, merged before/after do we want to really want to include them in the next 2.2.0 release? For the ones merged before the last alpha, is it OK to remove them now?

**Comment by blink1073** [comment]
Alphas make no API guarantees, prune away I say.

**Comment by saulshanabrook** [comment]
I am just realizing we also might have to revert at least https://github.com/jupyterlab/jupyterlab/pull/8454 as well, since reverting the TS version change means we can no longer upgrade typedoc to the new version, because that [requires typescript 3.8.3 or greater](https://github.com/TypeStrong/typedoc/blob/9118a5ca611a040112554998b40976430396ae58/package.json#L35)

**Comment by saulshanabrook** [comment]
The alpha is released! Install it with `pip install jupyterlab==2.2.0a1`.

**Comment by saulshanabrook** [comment]
Today we decided that I should release a rc before releasing. So I will do that tomorrow, then do a final release in a few days. I also have to write up the release notes before the rc.

**Comment by saulshanabrook** [comment]
The final release is available on PyPi. Once the tests pass on the conda forge PR we can merge that: https://github.com/conda-forge/jupyterlab-feedstock/pull/225#event-3547988816

**Comment by blink1073** [comment]
Merged, thanks @saulshanabrook!
