### ISSUE TITLE
my jupyter lab icons suddenly became invisible in light themed version

### ISSUE THREAD

**Issue by Shivamani-A-B** [jupyterlab/jupyterlab#8595]
jupyterlab verison-0.34.9
notebook version - 5.6.0
google chrome -Version 84.0.4147.56 (Official Build) beta (64-bit)
windows 10 64 bit 
relevant error   - Could not determine jupyterlab build status without nodejs

**Comment by jasongrout** [comment]
This version of JupyterLab is quite old and unsupported at this point (2.x was released in January). Can you upgrade?

When you say "my icons", do you mean icons for an extension you wrote? Or do you mean some of the built-in icons? If it is some of the built in icons, I'd suggest upgrading.

**Comment by Shivamani-A-B** [comment]
Yes it was the built in icons like I cannot see the kernal button nor
creating a new launcher. I even updated it and still it's not working. But
I tried using anaconda navigator it worked in that since I'm supposed to
use the environment type to follow the course I need help in that.


Thank you for reading my queries.

**Comment by panteparak** [comment]
I'm also experiencing this issue in both light and dark theme within an isolated environment.
Tested with jupyterlab==2.1.5 on Mac OSX Chrome 83.0.4103.106 and Safari 13.1.1.

![Screen Shot 2563-06-24 at 15 16 36](https://user-images.githubusercontent.com/16161996/85521096-fa755b00-b62d-11ea-96f6-b17ff1a00994.png)

**Comment by jasongrout** [comment]
Thanks for posting a screenshot. It looks like you are using pyLDAvis? This is a known issue with that package. See https://github.com/jupyterlab/jupyterlab/issues/7959 for a long conversation, and issues https://github.com/bmabey/pyLDAvis/issues/162 and https://github.com/bmabey/pyLDAvis/issues/121#issuecomment-387215639.

@Shivamani-A-B - are you also seeing this when using pyLDAvis?

**Comment by panteparak** [comment]
I see, reading over their issue and they have not resolved yet. i guess i've to use jupyter notebook for now then.

**Comment by Shivamani-A-B** [comment]
Actually I'm learning from ur tutorial for opencv where u have given an yml
file to create the environment. So it's OK sir I actually solved the
problem I reinstalled the complete package and now it's working fine..
Thank you for the help...

**Comment by jasongrout** [comment]
Great! Closing as resolved, then.
