### ISSUE TITLE
API Docs: logconsole and logconsole-extension, file not found.

### ISSUE THREAD

**Issue by hbcarlos** [jupyterlab/jupyterlab#8598]
## Description

When trying to access the API docs pages of logconsole and logconsole-extension it says "404
File not found".

## Reproduce

You can access through API Docs main page:
[https://jupyterlab.github.io/jupyterlab/index.html](https://jupyterlab.github.io/jupyterlab/index.html)
or through these URLs:
[https://jupyterlab.github.io/jupyterlab/index.html](https://jupyterlab.github.io/jupyterlab/logconsole/index.html)
[https://jupyterlab.github.io/jupyterlab/index.html](https://jupyterlab.github.io/jupyterlab/logconsole-extension/index.html)

**Comment by telamonian** [comment]
This will get fixed as part of the API docs overhaul in #8320.

Bascially, the problem with logconsole/-extension is that the typescript build for those pkgs disables `strictNullChecks`. This is fine for the actual build, but the API docs build is somewhat stupider, and can't actually support multiple `tsconfig.json` typescript build configs.
