### ISSUE TITLE
Upgraded conda-forge Jupyter lab 2.1.4 to 2.1.5 on Windows has broken script paths

### ISSUE THREAD

**Issue by owen-synergy** [jupyterlab/jupyterlab#8602]
## Description

I upgraded Jupyter Lab 2.1.4 to 2.1.5 on Windows using conda but afterwards all the jupyter script paths seemed to be broken. See attached screenshot.

<img width="890" alt="jupyter_lab_2_1_5" src="https://user-images.githubusercontent.com/50761413/85351092-72ac2580-b535-11ea-843b-06bd5018008a.png">

## Reproduce

1. Create a conda environment with jupyter lab 2.1.4 using the conda-forge channel
2. Upgrade to jupyter lab 2.1.5
3. Attempt to run "jupyter labextension update --all" or just "jupyter lab"

## Expected behavior

I expect the update and launch scripts to run

## Context

- Operating System and version: Windows 10 Enterprise Build 17763
- Browser and version: N/A
- JupyterLab version: 2.1.5

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        C:\ProgramData\Miniconda3\envs\jupyter
        C:\ProgramData\Miniconda3\envs\jupyter\Library\mingw-w64\bin
        C:\ProgramData\Miniconda3\envs\jupyter\Library\usr\bin
        C:\ProgramData\Miniconda3\envs\jupyter\Library\bin
        C:\ProgramData\Miniconda3\envs\jupyter\Scripts
        C:\ProgramData\Miniconda3\envs\jupyter\bin
        C:\ProgramData\Miniconda3\condabin
        C:\Program Files\ImageMagick-7.0.8-Q16
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0
        C:\WINDOWS\System32\OpenSSH
        C:\Program Files (x86)\Windows Live\Shared
        C:\Program Files\dotnet
        C:\Program Files\PIPC\bin
        C:\Program Files (x86)\PIPC\bin
        C:\Program Files\nodejs
        C:\ProgramData\chocolatey\bin
        C:\Program Files\TortoiseGit\bin
        C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn
        C:\Program Files\Docker\Docker\resources\bin
        C:\ProgramData\DockerDesktop\version-bin
        C:\Program Files\Microsoft SQL Server\130\Tools\Binn
        C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn
        C:\Program Files\Git\cmd
        C:\Users\307357\.cargo\bin
        C:\Users\307357\AppData\Local\Microsoft\WindowsApps
        C:\Users\307357\AppData\Local\Programs\Microsoft VS Code\bin
        C:\Users\307357\AppData\Roaming\npm
        C:\Users\307357\.dotnet\tools

sys.path:
        C:\ProgramData\Miniconda3\envs\jupyter\Scripts
        C:\ProgramData\Miniconda3\envs\jupyter\python38.zip
        C:\ProgramData\Miniconda3\envs\jupyter\DLLs
        C:\ProgramData\Miniconda3\envs\jupyter\lib
        C:\ProgramData\Miniconda3\envs\jupyter
        C:\ProgramData\Miniconda3\envs\jupyter\lib\site-packages
        C:\ProgramData\Miniconda3\envs\jupyter\lib\site-packages\win32
        C:\ProgramData\Miniconda3\envs\jupyter\lib\site-packages\win32\lib
        C:\ProgramData\Miniconda3\envs\jupyter\lib\site-packages\Pythonwin

sys.executable:
        C:\ProgramData\Miniconda3\envs\jupyter\python.exe

sys.version:
        3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 16:59:10) [MSC v.1916 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.17763-SP0

where jupyter:
        C:\ProgramData\Miniconda3\envs\jupyter\Scripts\jupyter.exe

pip list:
        Package                   Version
        ------------------------- -------------------
        affine                    2.3.0
        aiohttp                   3.6.2
        alive-progress            1.5.1
        altair                    4.1.0
        antlr4-python3-runtime    4.7.2
        aplus                     0.11.0
        appdirs                   1.4.3
        asciitree                 0.3.3
        asn1crypto                1.3.0
        astroid                   2.4.2
        astropy                   4.0.1.post1
        astropy-healpix           0.5
        async-generator           1.10
        async-timeout             3.0.1
        atomicwrites              1.4.0
        attrs                     19.3.0
        backcall                  0.2.0
        bcpandas                  0.6.0
        beautifulsoup4            4.9.1
        black                     19.10b0
        bleach                    3.1.5
        blinker                   1.4
        blis                      0.4.1
        bokeh                     2.1.1
        boto                      2.49.0
        boto3                     1.14.8
        botocore                  1.17.8
        Bottleneck                1.3.2
        bqplot                    0.12.13
        branca                    0.3.1
        brotlipy                  0.7.0
        bulwark                   0.6.1
        bz2file                   0.98
        cachetools                4.1.0
        Cartopy                   0.18.0
        catalogue                 1.0.0
        certifi                   2020.6.20
        cf-units                  2.1.4
        cffi                      1.14.0
        cfgrib                    0.9.8.2
        cftime                    1.1.3
        chardet                   3.0.4
        click                     7.1.2
        click-plugins             1.1.1
        cligj                     0.5.0
        cloudpickle               1.4.1
        colorama                  0.4.3
        colorcet                  2.0.1
        configobj                 5.0.6
        coverage                  5.1
        cryptography              2.9.2
        cssselect                 1.1.0
        cycler                    0.10.0
        cymem                     2.0.3
        cytoolz                   0.10.1
        dask                      2.19.0
        dask-labextension         2.0.2
        datashader                0.11.0
        datashape                 0.5.4
        deap                      1.3.1
        decorator                 4.4.2
        defusedxml                0.6.0
        Deprecated                1.2.10
        descartes                 1.1.0
        dialite                   0.5.2
        distributed               2.19.0
        docker                    4.1.0
        docker-pycreds            0.4.0
        docutils                  0.15.2
        earthpy                   0.9.2
        entrypoints               0.3
        escapism                  1.0.1
        et-xmlfile                1.0.1
        Faker                     4.1.1
        fastcache                 1.1.0
        fasteners                 0.14.1
        fastparquet               0.4.0
        feedfinder2               0.0.4
        feedparser                5.2.1
        Fiona                     1.8.13
        Flask                     1.1.2
        Flask-Cors                3.0.8
        flexx                     0.8.0
        fsspec                    0.7.4
        future                    0.18.2
        GDAL                      3.0.4
        gensim                    3.8.3
        geocoder                  1.38.1
        geographiclib             1.50
        geopandas                 0.7.0
        geopy                     1.22.0
        geoviews                  1.8.1
        gitdb                     4.0.5
        GitPython                 3.1.3
        google-api-core           1.20.0
        google-auth               1.17.2
        google-cloud-core         1.3.0
        google-cloud-storage      1.28.1
        google-resumable-media    0.5.1
        googleapis-common-protos  1.52.0
        gplearn                   0.4.1
        h5py                      2.10.0
        HeapDict                  1.0.1
        holoviews                 1.13.2
        html5lib                  1.0.1
        hvplot                    0.6.0
        idna                      2.9
        imagecodecs               2020.5.30
        imageio                   2.8.0
        importlib-metadata        1.6.1
        ipycanvas                 0.4.7
        ipydatawidgets            4.0.1
        ipyevents                 0.7.1
        ipykernel                 5.3.0
        ipyleaflet                0.13.0
        ipympl                    0.5.6
        ipyscales                 0.5.0
        ipysheet                  0.4.3
        ipython                   7.15.0
        ipython-genutils          0.2.0
        ipytree                   0.1.8
        ipyvolume                 0.6.0a6
        ipyvue                    1.3.2
        ipyvuetify                1.4.0
        ipywebrtc                 0.5.0
        ipywidgets                7.5.1
        iso8601                   0.1.12
        isort                     4.3.21
        itsdangerous              1.1.0
        jdcal                     1.4.1
        jedi                      0.15.2
        jieba3k                   0.35.1
        Jinja2                    2.11.2
        jmespath                  0.10.0
        joblib                    0.15.1
        json5                     0.9.4
        jsonschema                3.2.0
        jupyter-client            6.1.3
        jupyter-core              4.6.3
        jupyter-repo2docker       0.11.0
        jupyter-server            0.1.1
        jupyter-server-proxy      1.5.0
        jupyterlab                2.1.5
        jupyterlab-code-formatter 1.3.1
        jupyterlab-pygments       0.1.1
        jupyterlab-server         1.1.5
        K3D                       2.8.2
        kiwisolver                1.2.0
        lazy-object-proxy         1.4.3
        llvmlite                  0.31.0
        locket                    0.2.0
        loguru                    0.5.0
        lxml                      4.5.1
        Markdown                  3.2.2
        MarkupSafe                1.1.1
        matplotlib                3.2.1
        mccabe                    0.6.1
        missingno                 0.4.2
        mistune                   0.8.4
        mizani                    0.7.1
        mlxtend                   0.17.2
        monotonic                 1.5
        more-itertools            8.4.0
        mpmath                    1.1.0
        msal                      1.3.0
        msgpack                   1.0.0
        multidict                 4.7.5
        multipledispatch          0.6.0
        munch                     2.5.0
        murmurhash                1.0.0
        mypy-extensions           0.4.3
        natsort                   7.0.1
        nbconvert                 5.6.1
        nbdime                    2.0.0
        nbformat                  5.0.6
        nc-time-axis              1.2.0
        nest-asyncio              1.3.3
        netCDF4                   1.5.3
        networkx                  2.4
        newspaper3k               0.2.8
        nltk                      3.4.4
        notebook                  6.0.3
        Nuitka                    0.6.8.4
        numba                     0.48.0
        numcodecs                 0.6.4
        numpy                     1.18.5
        oauthlib                  3.0.1
        olefile                   0.46
        openpyxl                  3.0.3
        OWSLib                    0.20.0
        packaging                 20.4
        palettable                3.3.0
        pandas                    1.0.5
        pandas-flavor             0.2.0
        pandocfilters             1.4.2
        panel                     0.9.6
        param                     1.9.3
        parse                     1.14.0
        parso                     0.7.0
        partd                     1.1.0
        pathspec                  0.8.0
        patsy                     0.5.1
        pi                        2019.3.3
        pickleshare               0.7.5
        Pillow                    7.1.2
        pip                       20.1.1
        plac                      0.9.6
        plotnine                  0.7.0
        pluggy                    0.13.1
        preshed                   3.0.2
        progressbar2              3.51.3
        prometheus-client         0.8.0
        prompt-toolkit            3.0.5
        protobuf                  3.12.3
        pscript                   0.7.4
        psutil                    5.7.0
        py                        1.8.2
        pyarrow                   0.17.1
        pyasn1                    0.4.8
        pyasn1-modules            0.2.8
        pycparser                 2.20
        pyct                      0.4.6
        pyepsg                    0.4.0
        Pygments                  2.6.1
        pyjanitor                 0.20.7
        PyJWT                     1.7.1
        pykdtree                  1.3.1
        pyke                      1.1.1
        pylint                    2.5.3
        pymunk                    5.6.0
        pyodbc                    4.0.30
        pyOpenSSL                 19.1.0
        pyorbital                 1.5.0
        pyparsing                 2.4.7
        pyproj                    2.6.1.post1
        PyQt5                     5.12.3
        PyQt5-sip                 4.19.18
        PyQtChart                 5.12
        PyQtWebEngine             5.12.1
        pyreadline                2.1
        pyresample                1.16.0
        pyrsistent                0.16.0
        pysal                     2.1.0
        pyshp                     2.1.0
        PySocks                   1.7.1
        pyspectral                0.9.5
        pytest                    5.4.3
        pytest-base-url           1.4.1
        pytest-html               2.1.1
        pytest-metadata           1.9.0
        pytest-runner             5.2
        pytest-selenium           1.17.0
        pytest-variables          1.7.1
        python-dateutil           2.8.1
        python-geotiepoints       1.2.0
        python-json-logger        0.1.11
        python-utils              2.4.0
        pythreejs                 2.2.0
        pytz                      2020.1
        pyviz-comms               0.7.5
        PyWavelets                1.1.1
        pywin32                   227
        pywinpty                  0.5.7
        pywwt                     0.8.0
        PyYAML                    5.3.1
        pyzmq                     19.0.1
        QtPy                      1.9.0
        rasterio                  1.1.5
        ratelim                   0.1.6
        regex                     2020.6.8
        reproject                 0.7.1
        requests                  2.24.0
        requests-file             1.5.1
        requests-kerberos         0.12.0
        requests-oauthlib         1.2.0
        requests-toolbelt         0.9.1
        rope                      0.17.0
        rsa                       4.6
        Rtree                     0.9.4
        ruamel.yaml               0.16.6
        ruamel.yaml.clib          0.2.0
        s3fs                      0.2.2
        s3transfer                0.3.3
        safer                     4.1.1
        satpy                     0.22.0
        scikit-image              0.17.2
        scikit-learn              0.23.1
        scipy                     1.3.2
        scitools-iris             2.4.0
        seaborn                   0.10.1
        selenium                  3.141.0
        semver                    2.10.2
        Send2Trash                1.5.0
        setuptools                47.3.1.post20200616
        Shapely                   1.7.0
        shellingham               1.3.2
        simpervisor               0.3
        six                       1.15.0
        smart-open                2.0.0
        smmap                     3.0.4
        snuggs                    1.4.7
        sortedcontainers          2.2.2
        soupsieve                 2.0.1
        spacy                     2.3.0
        sparse                    0.9.1
        SQLAlchemy                1.3.17
        srsly                     1.0.2
        statsmodels               0.11.1
        sympy                     1.6
        tabulate                  0.8.7
        tblib                     1.6.0
        terminado                 0.8.3
        testpath                  0.4.4
        text-unidecode            1.3
        textblob                  0.15.3
        thinc                     7.4.1
        threadpoolctl             2.1.0
        thrift                    0.11.0
        tifffile                  2020.6.3
        tldextract                2.2.0
        toml                      0.10.1
        toolz                     0.10.0
        tornado                   6.0.4
        tqdm                      4.46.1
        traitlets                 4.3.3
        traittypes                0.2.1
        trollimage                1.13.0
        trollsift                 0.3.4
        typed-ast                 1.4.1
        typer                     0.2.1
        typing-extensions         3.7.4.2
        tzlocal                   2.1
        unsync                    1.2.1
        urllib3                   1.25.9
        vaex-arrow                0.5.1
        vaex-astro                0.7.0
        vaex-core                 2.0.3
        vaex-hdf5                 0.6.0
        vaex-jupyter              0.5.2
        vaex-ml                   0.9.0
        vaex-server               0.3.1
        vaex-viz                  0.4.0
        voila                     0.1.21
        wasabi                    0.7.0
        wcwidth                   0.2.4
        webencodings              0.5.1
        webruntime                0.5.7
        websocket-client          0.57.0
        Werkzeug                  1.0.1
        wheel                     0.34.2
        widgetsnbextension        3.5.1
        win-inet-pton             1.1.0
        win32-setctime            1.0.1
        wincertstore              0.2
        winkerberos               0.7.0
        wordcloud                 1.7.0
        wrapt                     1.11.2
        xarray                    0.15.1
        xlrd                      1.2.0
        XlsxWriter                1.2.9
        yarl                      1.3.0
        yellowbrick               1.1
        zarr                      2.4.0
        zict                      2.0.0
        zipp                      3.1.0
</pre>
</details>

<details><summary>Command Line Output</summary>
Not possible
</details>

<details><summary>Browser Output</summary>
Not possible
</details>

**Comment by owen-synergy** [comment]
I checked the Scripts directory and those Python scripts in the error aren't present.

**Comment by owen-synergy** [comment]
I just tried this with a clean conda environment installing just jupyterlab 2.1.4 and its dependencies then upgrading to jupyterlab 2.1.5 and I couldn't reproduce the problem there so I'm not sure.

I'm pretty sure I've encountered this issue with the missing scripts/or bad path with an earlier jupyter lab upgrade and at that time I just reinstalled my whole conda environment to fix the problem.

**Comment by blink1073** [comment]
I downloaded https://anaconda.org/conda-forge/jupyterlab/2.1.5/download/noarch/jupyterlab-2.1.5-py_0.tar.bz2 and inspected it and it looks correct to me.  It may be an issue with noarch conda packages on Windows?

<img width="566" alt="image" src="https://user-images.githubusercontent.com/2096628/85461056-85d8e880-b569-11ea-8472-b0f82477891d.png">

**Comment by owen-synergy** [comment]
I'm not opposed to closing this ticket as I wasn't able to reproduce this problem on a new environment. I'm sure I had a number of successful Jupyter lab upgrades in that Python environment - this is just something that seems to intermittently happen. I don't have much clue what could happen that could cause those script files to go missing and yet conda still shows a successful upgrade.

**Comment by blink1073** [comment]
Let's close it, if someone else has the same issue please comment here and we can reopen.

**Comment by Episkiliski** [comment]
I'm having the same issue after upgrading from JupyterLab 2.14 to 2.1.5 on conda-forge channel. I'm on Windows 7.

![JupyterLab](https://user-images.githubusercontent.com/53902830/85589097-8fcf1a00-b643-11ea-82ff-9caaa34910d1.jpg)

**Comment by owen-synergy** [comment]
I didn't try that this time but as I recall the previous time this happened to me resinstalling jupyter lab didn't help - I had to recreate my environment.
