### ISSUE TITLE
Add info for security reporting

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8612]
## Description
Add info to issue template and documentation about security reporting.

Ref: https://jupyter-notebook.readthedocs.io/en/stable/security.html#reporting-security-issues

The issue template should include instructions for reporting security issues.
We should also migrate the security documentation.  We could migrate it to:

- jupyter_server
- jupyterlab_server
- jupyterlab

I think it makes the most sense in `jupyter_server`.   We would link to it from our documentation.

**Comment by blink1073** [comment]
cc @Zsailer

**Comment by echarles** [comment]
Security should prolly be top #1 priority for Jupyter (among the 100 other priorities).

A security issue may come from the base server, from the lab server extension, or from javascript. They should be documented and issue template should also refer to those docs.

We can certainly refer from jlab and jlab_server to jserver, but all three deserve IMHO adhoc wordings and call for actions.

**Comment by blink1073** [comment]
Agreed on all counts @echarles.

**Comment by JasonWeill** [comment]
Security reporting info is at https://jupyter.org/security and is managed by the security working group. The "new issue" page includes a link to submit a security vulnerability; we also recommend emailing security@ipython.org.
