### ISSUE TITLE
keyboard shortcuts broke on Firefox 77, Ubuntu 20.04

### ISSUE THREAD

**Issue by zhxh1** [jupyterlab/jupyterlab#8625]
## Description

Keyboard shortcuts behave weirdly on my Firefox. 
1. `ctrl a` leads to moving the cursor to the front of the line
2. `ctrl s` opens a prompt to save the webpage
3. `ctrl c` and `ctrl v` do not have any affect
4. ...

## Reproduce

1. Install miniconda3
2. `conda create -n py37 python=3.7`
3. `pip install jupyterlab`
4. run `jupyter-lab`

## Expected behavior

Keyboard shortcuts work as normal., e.g. copy with `ctrl c`, paste with `ctrl v`

## Context

- Operating System and version: `Ubuntu 20.04`
- Browser and version: `Firefox 77`
- JupyterLab version: `2.1.5`

**Comment by ianhi** [comment]
Do you have any browser extensions enabled that might be causing this? I'm using Firefox 77.01 on PopOs 20.04 (based on ubuntu) and jlab 2.1.5 and I am unable to replicate in a new conda environment.

**Comment by zhxh1** [comment]
@ianhi Thanks for your reply.

It turns out that the user-agent switcher extension caused the problem.
