### ISSUE TITLE
Contributing Guide Link is Out of Sync

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8626]
## Description
The link in https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md should point to https://jupyterlab.readthedocs.io/en/latest/developer/contributing.html, not https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html.  

Right now the content that was in `CONTRIBUTING.md` is not yet in stable, so a lot of the docs are effectively missing.

## Reproduction
1. Click the Read the Docs link in https://github.com/jupyterlab/jupyterlab/blob/master/CONTRIBUTING.md
2. Switch to the latest version in the lower left
3.  Note how many more sections there are in the contributing guide.

**Comment by alirezaghey** [comment]
Hi, I'd like to tackle this.

**Comment by blink1073** [comment]
Hi @alirezaghey, great!

**Comment by blink1073** [comment]
Fixed in #8665
