### ISSUE TITLE
Is @jupyterlab/services 5.2.0 backward incompatible with 5.1.x?

### ISSUE THREAD

**Issue by afshin** [jupyterlab/jupyterlab#8628]
### Update
The root cause of this bug appears to be that the new 5.2.x line of `@jupyterlab/services` adds a new `Status` in `src/kernel/messages.ts` (`terminating`): https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/kernel/messages.ts#L538

This status did  not exist in earlier versions so it creates a breaking change. We should likely bump the version of `@jupyterlab/services` to 6.0, cc: @saulshanabrook 

### Original issue
We are working on an extension that is built to target JupyterLab 2. Sometime in the recent past, even though the published files in the pip package ask for `"@jupyterlab/services": "^5.1.0"` what is happening is that they are picking up `@jupyterlab/services` version `5.2.0-alpha.2`

Has anyone encountered this? Is there a mistake in what we published or something else? Here is the pull request that demonstrates the issue. It was passing two weeks ago but after re-running it, it fails now. I think is has something to do with the publication of that alpha version of `@jupyterlab/services` five days ago: https://www.npmjs.com/package/@jupyterlab/services/v/5.2.0-alpha.2

Here is a pull request the demonstrates the error in the test failures: https://github.com/jupyterlab/debugger/pull/459

## Description
When trying to build an extension that was building two weeks ago (without any modification), today we get errors like these:
```
$ tsc --build tsconfig.test.json
test/debugger.spec.ts(81,5): error TS2322: Type 'import("/home/runner/work/debugger/debugger/node_modules/@jupyterlab/codemirror/node_modules/@jupyterlab/services/lib/session/session").ISessionConnection' is not assignable to type 'import("/home/runner/work/debugger/debugger/node_modules/@jupyterlab/services/lib/session/session").ISessionConnection'.
  Types of property 'kernelChanged' are incompatible.
```

cc: @KrzysztofSikoraCodete @jtpio

**Comment by afshin** [comment]
Running the `why` function of `jlpm` yields:
```
yarn why v1.21.1
[1/4] 🤔  Why do we have the module "@jupyterlab/services"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@jupyterlab/services@5.1.0"
info Has been hoisted to "@jupyterlab/services"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "@jupyterlab#cells#@jupyterlab#services"
   - Hoisted from "@jupyterlab#rendermime#@jupyterlab#services"
   - Hoisted from "@jupyterlab#statusbar#@jupyterlab#services"
   - Hoisted from "@jupyterlab#application#@jupyterlab#services"
   - Hoisted from "@jupyterlab#apputils#@jupyterlab#services"
   - Hoisted from "@jupyterlab#console#@jupyterlab#services"
   - Hoisted from "@jupyterlab#docregistry#@jupyterlab#services"
   - Hoisted from "@jupyterlab#notebook#@jupyterlab#services"
   - Hoisted from "@jupyterlab#cells#@jupyterlab#filebrowser#@jupyterlab#services"
   - Hoisted from "@jupyterlab#cells#@jupyterlab#outputarea#@jupyterlab#services"
   - Hoisted from "@jupyterlab#cells#@jupyterlab#filebrowser#@jupyterlab#docmanager#@jupyterlab#services"
info Disk size without dependencies: "1.54MB"
info Disk size with unique dependencies: "4.19MB"
info Disk size with transitive dependencies: "13.63MB"
info Number of shared dependencies: 26
=> Found "@jupyterlab/testutils#@jupyterlab/services@5.2.0-alpha.2"
info Reasons this module exists
   - "@jupyterlab#testutils" depends on it
   - Hoisted from "@jupyterlab#testutils#@jupyterlab#apputils#@jupyterlab#services"
   - Hoisted from "@jupyterlab#testutils#@jupyterlab#cells#@jupyterlab#services"
   - Hoisted from "@jupyterlab#testutils#@jupyterlab#docregistry#@jupyterlab#services"
   - Hoisted from "@jupyterlab#testutils#@jupyterlab#notebook#@jupyterlab#services"
   - Hoisted from "@jupyterlab#testutils#@jupyterlab#rendermime#@jupyterlab#services"
   - Hoisted from "@jupyterlab#testutils#@jupyterlab#cells#@jupyterlab#filebrowser#@jupyterlab#services"
   - Hoisted from "@jupyterlab#testutils#@jupyterlab#cells#@jupyterlab#outputarea#@jupyterlab#services"
   - Hoisted from "@jupyterlab#testutils#@jupyterlab#notebook#@jupyterlab#statusbar#@jupyterlab#services"
   - Hoisted from "@jupyterlab#testutils#@jupyterlab#cells#@jupyterlab#filebrowser#@jupyterlab#docmanager#@jupyterlab#services"
info Disk size without dependencies: "1.55MB"
info Disk size with unique dependencies: "4.2MB"
info Disk size with transitive dependencies: "13.63MB"
info Number of shared dependencies: 26
=> Found "@jupyterlab/codemirror#@jupyterlab/services@5.2.0-alpha.2"
info Reasons this module exists
   - "@jupyterlab#codemirror#@jupyterlab#apputils" depends on it
   - Hoisted from "@jupyterlab#codemirror#@jupyterlab#apputils#@jupyterlab#services"
   - Hoisted from "@jupyterlab#codemirror#@jupyterlab#statusbar#@jupyterlab#services"
info Disk size without dependencies: "1.55MB"
info Disk size with unique dependencies: "4.2MB"
info Disk size with transitive dependencies: "13.63MB"
info Number of shared dependencies: 26
✨  Done in 0.74s.
```

**Comment by afshin** [comment]
Thanks for the tip, @vidartf!

It looks like the alpha version of `@jupyterlab/services` is coming from the `@jupyterlab/testutils` package, which explains why we can `jlpm build` and it passes but `jlpm test` fails.

**Comment by afshin** [comment]
cc: @echarles

**Comment by echarles** [comment]
@afshin Is this issue due to the recent change in kernel api (see https://github.com/jupyterlab/jupyterlab/pull/8562#issuecomment-643607417)?

I guess the services package used in the tests be aligned to the service package against which you run the test.

**Comment by echarles** [comment]
Checking the changes, I think the API of the `apputils/src/sessioncontext.tsx` has been changed (additional methods), but the services object API have not been changed (well, `src/kernel/messages.ts` has a new `terminating` possible value, not sure if this is an API change?).

**Comment by afshin** [comment]
@echarles I believe the issue is specifically adding the `terminating` message makes the `kernelChanged` signal no longer match.

cf. https://github.com/jupyterlab/jupyterlab/pull/8562/files#diff-962e8e726d165d50ffb0de9320ebe890R538

**Comment by echarles** [comment]
@afshin I should be that.

Have you found a way to fix your issue. When I face such problem? I ensure I pull everywhere the same version of libraries enforcing the version number (or minimal version number) in the package.json.

**Comment by afshin** [comment]
We should test `@jupyterlab/debugger` to see if it is a backward incompatibility or just a multiple-versions issue. Good point, @echarles!

**Comment by jtpio** [comment]
Based on the output of `jlpm why jupyterlab/services`, it looks like it should be possible to fix it in the debugger extension, by adding `"@jupyterlab/services": "^5.2.0-rc.1"` to the `devDependencies` for now? So the versions are the same and there is no conflict w.r.t the typings.

Once 2.2 is out, then the dependencies could be relaxed to:

```
"@jupyterlab/services": "^5.2.0"
...
"@jupyterlab/testutils": "^2.2.0"
```

As to whether adding a new field, method or attribute and can be considered a breaking change or not, there is an issue that discusses this here: https://github.com/jupyterlab/jupyterlab/issues/7289. Not sure the case of the `terminating` status falls in any of the categories?

**Comment by afshin** [comment]
@jtpio yeah, I left this issue open because I wasn't sure if we are looking at a true backward incompatibility or simply two versions of the library conflicting with each other, which is fine. I think you and Eric are correct and it is the latter.
