### ISSUE TITLE
Export with nbconvert --no-input

### ISSUE THREAD

**Issue by gmoutso** [jupyterlab/jupyterlab#8629]
### Problem
I am trying to export a notebook without code cells and prompts. On the CLI I can achieve this with --no-input or with a custom template --template. In #5015 the exporters are loaded automatically, but I am not sure how to change the default behavor or add it as an option.

### Proposed Solution
I wouldn't mind changing the default for nbconvert in jupyterlab or nbconvert to always use --no-input. Clear instructions if this is possible would be a solution to me. Adding the option to eg export HTML with --no-input in the jupyterlab menu in addition to what is there would be preferable. Another solution would be to use my own nbconvert template in jupyterlab, where I have one that already excludes code cells and prompts. If this is already possible some user config documentation would be nice.

### Additional context
From what I have gathered, one would add in jupyter_nbconvert_config.py the lines
```
c.TemplateExporter.exclude_output_prompt = True
c.TemplateExporter.exclude_input = True
```
This does not seem to work, nor if I add them to jupyter_notebook_config.py instead. I have also tried the json equivalent config files, but without clear documentation on what I should do there.

**Comment by gmoutso** [comment]
Also #5199

**Comment by timkpaine** [comment]
Best bet is to add new nbconvert exporters, it is very simple to do https://github.com/timkpaine/jupyterlab_nbconvert_nocode

**Comment by gmoutso** [comment]
Thank you @timkpaine. Looks very useful.

**Comment by gmoutso** [comment]
jupyter_nbconvert_nocode installs and works perfectly well. @timkpaine, it should be on anaconda and pip and advertised.
