### ISSUE TITLE
Remove Releases from the GitHub repository home page?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#8648]
With the recent changes to the GitHub UI the "Release" section on the repository home page now shows "Beta 2" as the latest release:

![image](https://user-images.githubusercontent.com/591645/86629749-26002a00-bfcc-11ea-8384-3f89c64dfd39.png)

This can misleading to new users, and doesn't reflect the real latest release.

The simplest might be to just hide the "Releases" section from the repository page?

![image](https://user-images.githubusercontent.com/591645/86629624-fc470300-bfcb-11ea-903e-2885fb40f766.png)

**Comment by jasongrout** [comment]
Agreed, that information is out of date and confusing. I've removed the releases from the homepage view. Thanks for bringing it up!

**Comment by jasongrout** [comment]
I also removed "Packages" since we aren't using them.

**Comment by jtpio** [comment]
Looks good, thanks!
