### ISSUE TITLE
Bug: Creating a Keyboard Shortcut for `clear-all-cell-outputs`

### ISSUE THREAD

**Issue by S-UP** [jupyterlab/jupyterlab#8654]
I can set up custom keyboard shortcuts just fine. However, it does not seem to work for `clear-all-cell-outputs` nor `clear-cell-output`.

Notably, the keyboard shortcut does not appear in the menu items list. Interestingly, it has (once?) appeared in the context menu (when right-clicking). I've tried different key mappings to rule out conflicts, e.g. H that I otherwise use for `hide-cell-outputs`. 

I have not managed to get this to work.

```
{
"shortcuts": [
        {
            "command": "notebook:hide-cell-outputs",
            "keys": [
                "H"
            ],
            "selector": ".jp-Notebook:focus"
        },
        {
            "command": "notebook:show-cell-outputs",
            "keys": [
                "Shift H"
            ],
            "selector": ".jp-Notebook:focus"
        },
        {
            "command": "clear-all-cell-outputs",
            "keys": [
                "Shift Backspace"
            ],
            "selector": ".jp-Notebook.focus"
        }

    ]
}
```

**Comment by fcollonval** [comment]
Thank you for reporting @S-UP. This is a feature of JupyterLab. So I transferred your issue.

**Comment by ianhi** [comment]
Two things to change:
1. command should be `notebook:clear-all-cell-outputs`
2.  selector shold be `.jp-Notebook`
```
        {
            "command": "notebook:clear-all-cell-outputs",
            "keys": [
                "Shift Backspace"
            ],
            "selector": ".jp-Notebook"
        }
```

**Comment by S-UP** [comment]
> Two things to change:
> 
> 1. command should be `notebook:clear-all-cell-outputs`
> 2. selector shold be `.jp-Notebook`
> 
> ```
>         {
>             "command": "notebook:clear-all-cell-outputs",
>             "keys": [
>                 "Shift Backspace"
>             ],
>             "selector": ".jp-Notebook"
>         }
> ```
> 
> These are handy - I think I might use these myself now - thanks!

This did the trick. Thanks for helping me out!
