### ISSUE TITLE
Side-Scrolling

### ISSUE THREAD

**Issue by LukeAI** [jupyterlab/jupyterlab#8662]
### Problem

When printing large pandas dataframes, the output of notebook cells overflows and is difficult or impossible to read. 

### Proposed Solution

If the output cells had horizontal scroll bars, I would be able to easily inspect my dataframes, without having to trim them first 

### Additional context

How it looks now:
![image](https://user-images.githubusercontent.com/43993778/86904495-b479c600-c108-11ea-8015-d04083cab986.png)

I can work around by splitting the dataframe up, but it's not ideal:

![image](https://user-images.githubusercontent.com/43993778/86904579-d5421b80-c108-11ea-9680-9282b8c140df.png)

**Comment by aiqc** [comment]
DataFrame output cells do have horizontal scroll bars

**Comment by aiqc** [comment]
Why would you *print* them instead of *returning* them using the built-in display capability that comes with scrolling?

<img width="465" alt="image" src="https://user-images.githubusercontent.com/74990642/186894723-72675cb8-8270-427b-b61f-aa7874ed08fc.png">
