### ISSUE TITLE
Bad links/404 errors in documentation

### ISSUE THREAD

**Issue by samgalen** [jupyterlab/jupyterlab#8669]
## Description

Hi all,

It looks like somehow the API documentation for jupyterlab frontend has been modified such that links within the documentation no longer work and the search results indexed in google 404.

## Reproduce

For example, clicking on the link to source in this page https://jupyterlab.github.io/jupyterlab/modules/_terminal_src_index_.html returns a github 404 error.

For me, searching "Notebook IContentFactory jupyter" puts this link (https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjm_bu4qL7qAhU2lHIEHY0BCt4QFjAAegQIAxAB&url=https%3A%2F%2Fjupyterlab.github.io%2Fjupyterlab%2Fnotebook%2Fclasses%2Fnotebookpanel.contentfactory.html&usg=AOvVaw3-yXiP_ctRsOjSjXB8FhPj) as the first result, which also 404s

## Expected behavior

External google links should be searchable and should link to source

## Context

On Firefox, searching with Google and have not tried another search engine.

**Comment by blink1073** [comment]
Hi @samgalen, we reorganized the API docs, which documentation source were you using that is out of date?

**Comment by samgalen** [comment]
@blink1073 The API docs in the jupyterlab.github.io/jupyterlab directory seem to have bad links to the source. 

In the example I give above, if you go to https://jupyterlab.github.io/jupyterlab/modules/_terminal_src_index_.html there is a link to the source for ITerminalTracker, saying that it is defined in packages/terminal/src/token.ts, and a hyperlink to https://github.com/blink1073/jupyterlab/blob/7f317d6da/packages/terminal/src/tokens.ts#L22

However, when I click on that link, github returns a 404 message. 

It's possible that the google/searchability issue is just an artifact of the reorganization and that the new documentation hasn't been indexed yet.

**Comment by blink1073** [comment]
Ah, I see, thank you.  That's an artifact of how we're building the docs currently.  We're migrating toward hosting the API docs with our standard RTD pages.  cf https://github.com/jupyterlab/jupyterlab/issues/6960

**Comment by jasongrout** [comment]
This may be fixed when we manually publish the api docs for 3.0.

**Comment by blink1073** [comment]
Fixed by #9179
