### ISSUE TITLE
Unable to upgrade Jupyterlab from v1.x to v2.x in Anaconda 

### ISSUE THREAD

**Issue by Nafaryus** [jupyterlab/jupyterlab#8672]
## Description

Dear all,

being quite new to this bug report section, I hope I will get relevant answers to my point. I'm simply trying to upgrade my JupiterLab version from 1.2.6 to the v2.1.5  using the Anaconda-navigator 'install specific version' drop down menu. I'am on a MacBook Pro, with OS Catalina 10.15.5
Unfortunately, it doesn't run as smoothly as it should, and in the 'logs viewer' several errors appears  as shown in the screenshot below : 
<img width="1437" alt="Capture d’écran 2020-07-08 à 23 14 10" src="https://user-images.githubusercontent.com/61317083/86971747-fc810300-c171-11ea-9a7a-51f4faa647ce.png">

for information here are the current versions I get 
<img width="288" alt="Capture d’écran 2020-07-08 à 23 32 10" src="https://user-images.githubusercontent.com/61317083/86972582-7a91d980-c173-11ea-9536-24a487f2fcfa.png">

Is there any other basic way to upgrade it (using pip, brew to stg else) ? Is there stg I'm missing here ?
Thanks in advance for your replies.

**Comment by Nafaryus** [comment]
FYI, a pip install -- upgrade jupyterlab doesn't work either ....

**Comment by Nafaryus** [comment]
Any help somewhere ?

**Comment by jasongrout** [comment]
Those errors don't look familiar. Perhaps asking in the Anaconda support channels might be a good thing to try.

If you're trying to upgrade from the command line with conda and/or pip, and you're still seeing errors, please post those errors. Also, does an install in a clean environment work?

**Comment by oliveirajun** [comment]
I had the same problem in a newly installed anaconda environment. it is an issue of incompatible dependencies. You need to create a new environment and install only your packages of interest. It worked for me.
