### ISSUE TITLE
Unusable load times when opening notebooks with many cells

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#8680]
## Description

Opening a notebook with 2k cells takes ~20 minutes on my machine. Aside from the time taken, this also locks up the webpage as its blocking. It seems reasonable to question if that is even a valid notebook size, but it has come up in practice which hints it's not contrived. In this case, it was the result of writing a lot of code in a single notebook, but rendering almost every intermediate step. Many python modules are much greater than 2k LOC.

## Reproduce

Create a notebook:
```
import nbformat
import json

cells = []
for i in range(2000):
    cells.append(nbformat.v4.new_code_cell(source='print({})'.format(i)))

nb = nbformat.v4.new_notebook(cells=cells, metadata={'language': 'python',})

with open('large-notebook.ipynb', 'w') as f:
    f.write(json.dumps(nb, indent=4))
```

Now try to open `large-notebook.ipynb`. To time it, before you open the notebook, run this in dev tools `setInterval(() => console.log('now'), 5000)`. The large notebook blocked for ~20 minutes for me. Quick debugging shows it's mostly code-mirror trying to create cells. If you merge all the code into one cell, you'll see it opens slowly, but not in an unusable amount of time.

## Expected behavior

1. A notebook loading never blocks other interactions for too long
2. Large notebooks are loaded faster or in parts or ...

## Context

- Operating System and version: `2.1.2`
- Browser and version: Chrome
- JupyterLab version: Windows

**Comment by jasongrout** [comment]
We are tracking this issue at https://github.com/jupyterlab/jupyterlab/issues/1639. Let's move the conversation over there to keep it consolidated. Thanks!
