### ISSUE TITLE
Magic Function not working in Jupyter lab with debugger

### ISSUE THREAD

**Issue by pratikchhapolika** [jupyterlab/jupyterlab#8684]
I followed this instruction to install the debugger ( Windows 10, 16GB HDD with Nvidia):

https://github.com/jupyterlab/debugger

Then I tried to run magic function ( Using dark mode):

import numpy as np
from numpy.random import randint

 #A function to simulate one million dice throws.

def one_million_dice():
    return randint(low=1, high=7, size=1000000)

# New Line

%%time
throws = one_million_dice()
mean = np.mean(throws)

I get an error: 

---------------------------------------------------------------------------
SyntaxError                               Traceback (most recent call last)
File C:\Users\chhapoli\Anaconda3\envs\jupyterlab-debugger\lib\ast.py, in parse:
Line 35:    return compile(source, filename, mode, PyCF_ONLY_AST)

SyntaxError: invalid syntax (<string>, line 1)
---------------------------------------------------------------------------

Question1: How to see traceback in Jupyter Lab

Question2: How to fix it?

Question 3: Crashes when I opens up big csv file. ( 1.018 GB)

**Comment by agoose77** [comment]
The xeus kernel used by JupyterLab when you use the debugger does not support magics.

**Comment by jtpio** [comment]
Closing, as this is being tracked in https://github.com/jupyter-xeus/xeus-python/issues/303
