### ISSUE TITLE
Display the versions in the extension manager

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#8686]
### Problem

It would be nice if there was a way to know the version of an installed extension via the extension manager (and maybe also the latest for those in "Discover")

![image](https://user-images.githubusercontent.com/591645/87302129-196e5b00-c511-11ea-89be-65775718d0c7.png)

For now this can be achieved by opening a terminal and executing `jupyter labextension list`:

![image](https://user-images.githubusercontent.com/591645/87302474-c3e67e00-c511-11ea-91f9-4dc070f46920.png)

### Proposed Solution

Maybe the version could be displayed next to the name of the extension:

![image](https://user-images.githubusercontent.com/591645/87302593-f3958600-c511-11ea-8d79-944e07d37e08.png)

**Comment by echarles** [comment]
... and `Update` label could be e.g. `Update to v1.2.4`

**Comment by jtpio** [comment]
The version information should be available as part of the response:

![image](https://user-images.githubusercontent.com/591645/221201483-1a0a8814-7199-468e-a665-6b69c8b36a83.png)
