### ISSUE TITLE
Minimized build fails with terser error

### ISSUE THREAD

**Issue by jvail** [jupyterlab/jupyterlab#8688]
Hi, I am using three.js in a jupyter lab extension.
When I run a production build 

`jupyter lab build --dev-build=False`

I get an error from terser and the build fails. It is complaining about trailing commas in  a function call. Apparently (https://github.com/terser/terser/issues/412) this could be fixed here:

https://github.com/jupyterlab/jupyterlab/blob/f0153e0258b32674c9aec106383ddf7b618cebab/dev_mode/webpack.prod.minimize.config.js#L15

with the default ecma setting which is 8.

**Comment by jvail** [comment]
No idea why... but it seems to work now.

**Comment by benbovy** [comment]
I still get an error from terser, trying to build jupyterlab with minimize enabled and with an extension using three.js. (jupyterlab version 2.2.8).
