### ISSUE TITLE
Open an ipynb file from existing URL

### ISSUE THREAD

**Issue by wqj97** [jupyterlab/jupyterlab#8702]
### Problem
Sometime I would like open an ipynb from an existing URL. 

### Proposed Solution
Add an support so that when open /lab/http://foo.bar/abc.ipynb, server will download file and open it in browser.

### Additional context

Corlib solved this by this link [here](https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/df1f5ef1c1a8e1a111e88281b27829fe/finetuning_torchvision_models_tutorial.ipynb#scrollTo=y-2TM23HcGw6)

**Comment by jtpio** [comment]
Thanks @wqj97 for opening this issue.

It looks like https://github.com/jupyterlab/jupyterlab/issues/8702 is a similar issue and has a couple of comments there.

Let's close this one and move the conversation there? Thanks!
