### ISSUE TITLE
Bring back the labhub entry point

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8704]
## Description
We previously had this interface in 1.0.  We removed it in https://github.com/jupyterlab/jupyterlab/pull/7724.  However, based on the feedback from https://github.com/jupyterlab/jupyterlab/pull/8356 and @athornton on [gitter](https://gitter.im/jupyterlab/jupyterlab?at=5f171e82a15ff42fa8e1da20), we need to bring this back in order to pass settings to the lab app.

**Comment by blink1073** [comment]
@minrk is it possible to have a mixin in JupyterHub so that we can use the mixin class for our entry point, or was that a limitation in tornado?

**Comment by minrk** [comment]
There isn't a technical reason we can't make it a mixin on the JupyterHub side, just need to do it. I don't see any hurdles to that. The auth patches would also need an update, I think, but that should be minor.

**Comment by blink1073** [comment]
So for JupyterLab 3.0, we'll inline [`singleuser.py`](https://github.com/jupyterhub/jupyterhub/blob/d1a85e53dccfc7b1dd81b0c1985d158cc6b61820/jupyterhub/singleuser.py) and make the subclassing work.  Once a new `jupyterhub` is released that has the mixin, we can use that and then fall back on our implementation if it doesn't exist.
