### ISSUE TITLE
Build in dev + watch mode has warnings and does not refresh in browser

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#8705]
[1] With latest master, I run `jupyterlab --dev --watch` and receive warnings.
[2] When I change the source code, build is triggered, but changes are not reflected in my browser after a refresh (even a force refresh).

```
(node:74964) [DEP_WEBPACK_MAIN_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: MainTemplate.hooks.renderManifest is deprecated (use Compilation.hooks.renderManifest instead)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:74964) [DEP_WEBPACK_CHUNK_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: ChunkTemplate.hooks.renderManifest is deprecated (use Compilation.hooks.renderManifest instead)
(node:74964) [DEP_WEBPACK_MAIN_TEMPLATE_HASH_FOR_CHUNK] DeprecationWarning: MainTemplate.hooks.hashForChunk is deprecated (use JavascriptModulesPlugin.getCompilationHooks().chunkHash instead)
(node:74964) [DEP_WEBPACK_MAIN_TEMPLATE_GET_ASSET_PATH] DeprecationWarning: MainTemplate.getAssetPath is deprecated (use Compilation.getAssetPath instead)
(node:74964) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
(node:74964) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(node:74964) [DEP_WEBPACK_MODULE_ID] DeprecationWarning: Module.id: Use new ChunkGraph API
(node:74964) [DEP_WEBPACK_MODULE_UPDATE_HASH] DeprecationWarning: Module.updateHash: Use new ChunkGraph API
(node:74964) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
(node:74964) [DEP_WEBPACK_CHUNK_GROUP_GET_MODULE_INDEX_2] DeprecationWarning: ChunkGroup.getModuleIndex2 was renamed to getModulePostOrderIndex
(node:74964) [DEP_WEBPACK_MAIN_TEMPLATE_GET_PUBLIC_PATH] DeprecationWarning: MainTemplate.getPublicPath is deprecated (use Compilation.getAssetPath(compilation.outputOptions.publicPath, options) instead)
```

**Comment by echarles** [comment]
If others have same problem, a related fixed issue is https://github.com/jupyterlab/jupyterlab/issues/6649

Those last week (before pulling I think the webpack-5 changes, cc/ @blink1073), I was facing sometimes on my local env the browser not picking the changes, but after another rebuild, it was finally picking it. Fine tuning of webpack dev server watch time interval would have helped I guess. Now, changes are never picked (need to restart).

**Comment by blink1073** [comment]
I don't have bandwidth to look at this, my aim is to replace it soon.

**Comment by echarles** [comment]
Thx Steve for the comment. Are you saying the --watch process will be replaced by something else in the federated world?

**Comment by blink1073** [comment]
The concept will be the same, the implementation will differ a bit.  We'll also be able to load dynamic extensions in core mode.  There's a lot left to work through, I need to stay on a linear path so I don't get sidetracked anymore in the next couple weeks.

**Comment by echarles** [comment]
Sure, makes totally sense to stay on track with a goal. For this, I am even not sure if the issue is not on my side.

I one really need that browser hotreload, it is also possible to develop agains a version of 2 weeks ago, so there is a workaround. Thx again for all your work. Lot of people are looking at you :)

**Comment by echarles** [comment]
... and to @jasongrout (working with you on the federation front)
