### ISSUE TITLE
Add full screen option to JupyterLab

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8710]
### Problem

I often want to make my JupyterLab interface full screen, without any browser tabs or other window chrome, so I can concentrate on the problem at hand.

Maximizing a chrome browser in macOS almost does what I want, but only if I uncheck "Always show toolbar in Full Screen". I can't figure out a way to do this in Firefox, and I can't figure out a way to do this in Windows either.

### Proposed Solution

Add a command to make the JupyterLab root application DOM element full screen, using the [requestFullScreen](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen) api.

Add this as a menu item, perhaps under the View menu next to the Single-Document Mode?

**Comment by jasongrout** [comment]
This would likely be a command added in the application extension: https://github.com/jupyterlab/jupyterlab/blob/master/packages/application-extension/src/index.tsx

**Comment by jasongrout** [comment]
For example, pasting this into the browser console enables the behavior I'm looking for by double-clicking the jupyter logo:

```
$('#jp-MainLogo').addEventListener('dblclick', () => document.documentElement.requestFullscreen())
```
I'd love to have that behavior as a command I could assign a keyboard shortcut and have it available in the View menu next to presentation and single-document mode.

**Comment by bollwyvl** [comment]
Yes! There are, sadly, a lot of gotchas around the fullscreen apis... i've used [screenful](https://github.com/sindresorhus/screenfull.js/blob/master/src/screenfull.js) on [wxyz](https://github.com/deathbeds/wxyz/blob/master/src/ts/wxyz-html/src/widgets/fullscreen.ts) to paper over them and it works pretty well.

Going further, I'd like to be able to full-screen:

- the DockPanel, still being able to move things around (optionally with no sidebars, menus, status bars) 
- any main area widget (optionally without the toolbar)
- any cell (and maybe somehow make the source/output resizeable, or at least split left/right)
- any output

The breadth of this suggests it may be a candidate for upstreaming into lumino `Widget`, e.g. 
- if `Widget.fullscreenable` then enable a command which... 
  - calling `Widget.requestFullscreen({toolbar: false})` **inside a click/keyboard event handler** will...
     - add `class="lm-mod-fullscreen" data-lm-fullscreen-toolbar="false"`. 

Aside from convenience/consistency, my experience with wxyz has been, as soon as the fullscreen pops, there is an event/message/signal or two that aren't fired, so some of the layouts don't update properly until something happens that triggers an `updateRequest`... but if it was coming from Inside the House, it would be more easily addressed. 

Likely, this would mean re-implementing `screenful` there, but it's not a lot of code, and is considered "done" by the maintainers.

**Comment by jasongrout** [comment]
Thanks for the input! So perhaps the "good first issue" would be implementing a command that fullscreens the entire application, and a separate further development would be discussing and implementing a good UX for fullscreening other parts of the UX.

From https://caniuse.com/#feat=mdn-api_element_requestfullscreen, it appears that the main `requestFullscreen` command was supported by Edge only starting this year, and it looks like Safari still requires the webkit prefix, so perhaps it is good to support the vender-specific prefixes, like the package you mention.

**Comment by bollwyvl** [comment]
Regarding the "deep" fix of this: two demos I saw recently (open source stuff on [Jupyter Meets the Earth](https://discourse.pangeo.io/t/jupyter-meets-the-earth-earthcube-meeting-july-27/689), and a proprietary Siemens Lab downstream demo) both had custom ways for different parts of the app to be full-screened. 

Spitballing on UX: if there was an opt-in `lm-mod-fullscreenable` (e.g. the average TabBar would make no sense), a general purpose `Show Element Full Screen...`could highlight (outline?) all the things that could be full screened, and clicked (to preserve the user interaction requirement). I don't know how this could be enabled with the keyboard, as not all of these widgets would have `tabindex`...

**Comment by joelostblom** [comment]
I also think this would be nice! Currently I am always launching JupyterLab as a web app in chromium by having the following in `~/.jupyter/jupyter_notebook_config.py`:

```
c.LabApp.browser = 'chromium --incognito --app=%s'
```

This get rids of menu bars etc and make JupyterLab more like a standalone application (which I like personally, but I realize that it can seen as either a pro or con depending on what one is after).

**Comment by HarshShroff** [comment]
Open your notebook (.ipynb file) in VS Code with Jupyter extension installed and click F11 (If you're using Windows) to make it full screen.

**Comment by lucasresck** [comment]
In the same reasoning of @sarthchoudhary, one can select the address bar and press `F11` to get JupyterLab into full screen. Using address bar shortcut in Chrome, it would be like `Ctrl + L F11`.

**Comment by FaediMichele** [comment]
Would be great if the jupyter lab can be used in android. I managed to set a fullscreen mode for vscode using code-server(https://github.com/cdr/code-server) and creating a link in the home. For jupyter lab I can create a link in the home but is not fullscreen. I'm not an expert of Web so I don't know how the vscode team managed to implement that feature

**Comment by Grimoors** [comment]
Hi! This looks like a good first issue. I am new to open source and want to try to contribute to this. May I try to work on this issue

**Comment by jasongrout** [comment]
> Hi! This looks like a good first issue. I am new to open source and want to try to contribute to this. May I try to work on this issue

Absolutely!

**Comment by matteoferla** [comment]
Not a constructive comment, but a comedy comment: this is how Jupyter looks like on a piddly 4" screen which is meant to have a "hacker vibe" [according to the makers]
![image](https://user-images.githubusercontent.com/11302983/211150101-162f7637-30b0-4dfd-9907-1ad12a408bf6.jpeg)

**Comment by dining-philosopher** [comment]
Why not simply allow F11 key? When i choose "full screen" from the menu, it works fine, at least in chromium. But F11 key is disabled for no apparent reason.

**Comment by Rob-P-Smith** [comment]
We're relooking at this for a Codeday issue in a small group. We will start with a simple menu implementation using a call to
document.documentElement.requiestFullscreen() when toggleFullScreenMode boolean == true by adding a FullScreen option to view> Appearance > Fullscreen Mode, like below:
![image](https://github.com/jupyterlab/jupyterlab/assets/147754337/f3a51cd7-3232-4b44-9a2c-1f7ef6c334cd)

I am aware the browsers have this functionality built-in; however, different browsers present different issues. One example is graphical glitching in chromium as seen here:

![image](https://github.com/jupyterlab/jupyterlab/assets/147754337/b018c043-4bc1-4786-9a36-54753cf140fb)

From there we can focus on expanding into allowing specific notebooks to take fullscreen focus and fill the entirety of the screen.  Exactly how we will tackle this, we've not planned out yet. Perhaps a context menu option, check box, drag and drop area in the dock position locator, etc. More to follow as we progress.
