### ISSUE TITLE
Release 2.2 breaking change in `services` package

### ISSUE THREAD

**Issue by vidartf** [jupyterlab/jupyterlab#8736]
In https://github.com/jupyterlab/jupyterlab/pull/8279 the property `ServerConnection.defaultSettings` was removed. This broke nbdime's lab extension: https://github.com/jupyter/nbdime/issues/531

**Comment by goanpeca** [comment]
@vidartf is this issue still relevant?

**Comment by vidartf** [comment]
Well, 2.2 is still not backwards compatible with 2.1, but I assume we have moved on.
