### ISSUE TITLE
Abstract Editor Design

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#875]
On the attached picture you can see a proposed design. It consists of the following parts:
- a concrete editor interface - CodeMirror, Monaco, Ace, Orion, etc.
- the abstract editor interface that is a set of common assumptions which should hold for all concrete editors
- a concrete editor module - which is an adapter from a concrete editor interface to the abstract
- a user code - editorWidget, console, notebook, inspector, completions, e.g.

![img_7061](https://cloud.githubusercontent.com/assets/3082655/18502915/6888caf0-7a5a-11e6-8b85-429b367bb259.jpg)

There are important consequences from this design:
- a concrete editor module should be only changed if a concrete editor interface changed, e.g. if a new version of CodeMirror is used, it should not be changed if some user code changed, e.g. completions
- the abstract editor interface only abstracts over variable parts of concrete editors, it should not care  about user code

@jasongrout proposed to build a minimal concrete editor, i am not sure how it is going to help, i am not expecting that new concrete editors will be developed but rather adapters to existing. Consequently it will be more interesting to identify a set of common assumptions by looking at the existing concrete editors.

Another step will be to have a look at the existing JLab code, map to this design and identify design violation points.

Obviously it makes sense only if you are agree with such approach. If you are i could provide a set of assumptions and point out to violating code. We can review it together. And it could be done iteratively plugin by plugin.

**Comment by jasongrout** [comment]
CC @sccolbert

**Comment by akosyakov** [comment]
Hey, I've prototyped with the design above and result here: https://github.com/jupyter/jupyterlab/pull/888.

As you can see it is much less invasive than my previous PR. It consist of following changes:
1. new codeeditor module - it defines Abstract Editor Interface and a base widget that works agains it
2. codemirror plugin does not contain a based editor widget anymore but an adapter from Abstract Editor to CodeMirror
3. editorwidget plugin is still bound to CodeMirror but there is a reusable EditorWidget that does 
application logic based on Abstract Editor Interface, it probably should be move to another module that does not depend on CodeMirror, and it should be refactored a bit, like extract template method to update a title and sync with a document context
4. notebook/cells module - there is AbstractCellEditorWidget that is a base widget that does application logic based on Abstract Editor Interface, e.g. cell editor model synchronization, it can be extended 
5. all other changes only adapt the user code to Abstract Editor Interface

**Comment by blink1073** [comment]
Finished by #1140, thanks again!
