### ISSUE TITLE
[2.2.x] `import time` missing in `browser_check`

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#8752]
The package `time` is not imported in `browser_check` on branch `2.2.x`.

So the following statement raises an error:
https://github.com/jupyterlab/jupyterlab/blob/b5024e97f8b9160dd9cef70d619027fbf7a47aa7/jupyterlab/browser_check.py#L134

> Note: the exception is silenced as it happens after the test succeeds. See for example: https://travis-ci.org/github/jupyterlab/jupyterlab-git/jobs/714050835#L1169

**Comment by blink1073** [comment]
Fixed in https://github.com/jupyterlab/jupyterlab/commit/5878da5b2ab331e574f680b7646324bbd5ae7fbc

**Comment by fcollonval** [comment]
Thanks Steven
