### ISSUE TITLE
Set up end to end testing

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8755]
### Problem
We do not currently have any end-to-end tests other than `browser_check`.  We should be testing more the of the application to prevent visual regressions.

### Proposed Solution

At a minimum we should use [`galata`](https://github.com/jupyterlab/team-compass/issues/77)
We should also look into [`QA Wolf`](https://www.qawolf.com/), which converts manual actions into `playwright/jest` code.

**Comment by jtpio** [comment]
Another tool that can be useful if we decide to continue with `puppeteer` (which is also what `galata` uses).

Chromium 89 now includes an experimental recorder to easily generate puppeteer scripts from user actions: 

https://developers.google.com/web/updates/2021/01/devtools#record

**Comment by bollwyvl** [comment]
Y'all know me, I don't want to get in a fight about testing frameworks or whatever, but: I'll keep beating the [robotframework](https://robotframework.org)(-[seleniumlibrary](https://github.com/robotframework/SeleniumLibrary)) drum, as well as my wee wrapper around it, [robotframework-jupyterlibary](https://github.com/robots-from-jupyter/robotframework-jupyterlibrary) (which we would _happily_ donate to this org, though it's rather... opinionated). 

This stack has been _indispensable_ in my ability to ship things that support multiple versions of lab+dog over the last couple years.

Pro:
- uses _real_ browsers
  - if one can continuously prove something works in FF LTS on windows... _it frigging works_
- tests can look like _plain english_
  - can also be written in python and just _started_ from the novel syntax
- can drive _way more_ things than just browsers
  -  In the most extreme example: driving virtualbox to deploy jupyterhub in a VM, and then run a second machine (on a different VM/OS) to talk to the first one, with timestamp-unified logs and whole-screen recording
- RF has a couple [jupyter](https://github.com/robots-from-jupyter/robotkernel) [kernels](https://github.com/jupyter-xeus/xeus-robot)

Con:
- robot syntax is _weird_ at first
- the selenium stack is _notoriously_ more flaky than more recent integrations based on custom (chromium) browsers
- the chromium stack has made it _extremely difficult_ to stay compatible
  - their webdriver implementation and the specific version of browser have to match down the (sometimes non-matching) build level 
- its definitely _slower_
- it's _non-trivial_ (if not _impossible_) to get browser logs
  - there is no webdriver spec for it (though this is getting better)
- seleniumlibrary's maintainer is _tired_
  - there's a lot of f500's using it, quietly, but not so much _contributing_

**Comment by jtpio** [comment]
Closing as end to end testing is now setup in https://github.com/jupyterlab/jupyterlab/tree/master/galata.

>  We should also look into [`QA Wolf`](https://www.qawolf.com/), which converts manual actions into `playwright/jest` code.

Since Galata is built on Playwright, it's possible to use the playwright `codegen` to convert actions to code: https://playwright.dev/docs/cli/#generate-code
