### ISSUE TITLE
Jupyter notebook in aws sagemaker studio

### ISSUE THREAD

**Issue by priyanga24** [jupyterlab/jupyterlab#8759]
Hi,
when I try to change my instance type from medium to any other large instance, I get this error. Please help, thanks!

> `Failed to change to instance ml.m5.12xlargeAn error occurred (ResourceLimitExceeded) when calling the CreateApp operation: The account-level service limit 'KernelGateway Apps running on ml.m5.12xlarge instance' is 0 Apps, with current utilization of 0 Apps and a request delta of 1 Apps. Please contact AWS support to request an increase for this limit.`

**Comment by blink1073** [comment]
Hi @priyanga24, those resource limits are specific to SageMaker Studio.  Please contact AWS support directly to request a  limit increase for your account.

**Comment by jasongrout** [comment]
Closing as answered. Thanks!
