### ISSUE TITLE
Include `@` operator in Codemirror jupyter mode 

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#876]
cf https://github.com/jupyter/notebook/pull/1763

Adds support for the `@` operator in Python 3.5+.

**Comment by ClaytonPassmore** [comment]
@blink1073 In the linked PR, `@` is defined as an operator for all python versions, not just 3.5+. Are you okay with that here as well?

**Comment by blink1073** [comment]
I think that is fair, we don't have a good way to distinguish python versions on the front end.
