### ISSUE TITLE
Missing workspacesUrl in index HTML for PageConfig?

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#8761]
Hi, While working working on [JupyterLab as Server Extension](https://github.com/jupyterlab/jupyterlab/pull/7416), the workspace clone is broken. It turns out that workspacesUrl is no more generated

  <script id="jupyter-config-data" type="application/json">
..., "treeUrl": "/lab/tree", "userSettingsDir": "/Users/echar4/.jupyter/lab/user-settings", "workspacesApiUrl": "/lab/api/workspaces", "workspacesDir": "/Users/echar4/.jupyter/lab/workspaces", "workspacesUrl": "/lab/workspaces", "wsUrl": ""}...
  </script>

I have looked in the current master, but can not find where this key/value is generated.

If I set `workspaces: '/lab/workspaces',` in `lab.ts`, the workspace cloning works fine.

**Comment by ellisonbg** [comment]
The workspaces URL and tree URL are going away in JLab 3.0. The PR for this has been merged into jupyterlab_server, but not JupyterLab yet.

**Comment by echarles** [comment]
Thx @ellisonbg for feedback. Closing this, we can iterate on master if needed.
