### ISSUE TITLE
Feature Requeat: Open notebooks from Markdown

### ISSUE THREAD

**Issue by pylang** [jupyterlab/jupyterlab#8774]
### Problem

Given a markdown file of links, I would like to:

- Open the markdown file (rendered)
- Click on a link to a notebook
- Open the notebook

Right now, I think such links attempt to download the notebook rather than open them.

### Proposed Solution

Main idea
- Render markdown previews in Jupyterlab so that links to notebook files open them as rendered notebooks (not as a raw file, or attempt to download the file)

### Additional context

I use this functionality all the time with an older Anaconda/Notebook setup.

- Start Anaconda from a Jupyter Notebook icon
- The terminal opens and runs the server in the background
- Open a browser
- Click on a bookmark to my markdown file of links
- The file renders nicely in the browser
- Click on a link to a notebook
- The notebook opens in the browser

Details

Here is a working example from an existing jupyter setup:

A - Markdown file of relative paths to notebooks
![a](https://user-images.githubusercontent.com/10778668/89541814-d67c6c00-d7cc-11ea-80b7-28eb042f0ee6.png)

B - Rendered markdown file (bookmarked to access quickly)
![b](https://user-images.githubusercontent.com/10778668/89541306-34f51a80-d7cc-11ea-8d0a-8f967841f3ce.png)

C - Rendered notebook opened from the link
![c](https://user-images.githubusercontent.com/10778668/89541314-37577480-d7cc-11ea-9ffc-87bb820e5a1f.png)

- The address of the mentioned bookmark that I used looks like this:
`http://localhost:8888/nbextensions/nbextensions_configurator/rendermd/tree/markdown_file_w_links.md`

This feature helps me organize 100s of notebooks into custom groups.

**Comment by krassowski** [comment]
Hi @pylang, this sound like a very useful feature (I use markdown links often too), thanks for opening this issue!

I tried to check what is the current behaviour and saw both notebooks and markdown files open smoothly from the rendered markdown preview in JupyterLab 2.2 - see the screencast below. 
What version of JupyterLab did you encounter the behaviour of downloading the notebook instead?

![ok-3](https://user-images.githubusercontent.com/5832902/89549416-2e809600-d800-11ea-8466-813384040d08.gif)

Or, did I mis-understood your intend and you actually aim for something different?

**Comment by pylang** [comment]
Great response.  Thank you.

Indeed, I have an old version of Jupyterlab (v0.32), so perhaps that's why I didn't observe what you showed in your screencast.  I'm glad to see this is already a feature.  

The main issue is solved, but I have related question.  Is there a way to "bookmark" files?   As an example, to get to your `README.md`, I assume you have to navigate the directory tree.  I'd rather bookmark it or have some quick access mechanism, rather than click through directories.

Thanks again.

**Comment by krassowski** [comment]
Would "Copy shareable link" as demonstrated here: #3396 work for you?

**Comment by pylang** [comment]
Yep, that should do it.  I'm not sure how I would have discovered that so thanks.
