### ISSUE TITLE
Mirror operating system's dark/light mode setting

### ISSUE THREAD

**Issue by stsievert** [jupyterlab/jupyterlab#8777]
### Problem

* Currently, JupyterLab supports toggling between dark and light mode.
* Various operating systems also support this feature, including [macOS], [Windows] and [Ubuntu].
* Many browsers support the CSS query `prefers-color-scheme`, which mirrors the OS theme ([MDN prefer-color-scheme docs][1])

Despite these features, Jupyter Lab does not support automatically toggling between dark/light mode to mirror the OS theme.

A good example of a site that has this support is the WebKit blog,  https://webkit.org/blog/.

[2]:https://stsievert.com/
[1]:https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
[macOS]:https://support.apple.com/en-us/HT208976
[Windows]:https://www.cnet.com/how-to/how-to-enable-dark-mode-in-windows-10/
[Ubuntu]:https://www.howtogeek.com/669755/how-to-enable-dark-mode-on-ubuntu-20.04-lts/

### Proposed Solution

Add an option to for JupyterLab to automatically toggle between light and dark mode depending on the OS theme. Maybe "Settings > Theme > Auto."

### Additional context

Here's a good site describing how to implement `prefers-color-scheme`: https://www.bram.us/2019/05/23/css-color-scheme-queries-dark-mode-css/. They show this demo:

<img src="https://user-images.githubusercontent.com/1320475/89561520-3af3f700-d7de-11ea-8a63-f3126e96c1d2.gif" width="300px" />

This demo shows  https://webkit.org/blog/ and toggles the OS light/dark mode (see the navigation bar of the web browser window).

**Comment by krassowski** [comment]
I think that we should add "Settings > Theme > Auto/System" option, which when active would detect [@media/prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) in JS and automatically switch the light/dark theme. Some useful examples are given on [SO](https://stackoverflow.com/questions/56393880/how-do-i-detect-dark-mode-using-javascript).

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/is-there-any-notebook-theme-which-changes-with-the-day-time-from-light-to-dark-mode/11562/4

**Comment by jasongrout** [comment]
If we had an auto option, I think we should also have a setting for the preferred light theme and the preferred dark theme.
