### ISSUE TITLE
[DISCUSS] Benchmarks in own repo?

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#8784]
We have now a `benchmark` folder. The goal is to bring more test coverage, but maybe also store  benchmark results.

We could have also different release cycles than the other jlab core packages (sometimes, we would want to release benchmark faster that other packages).

We also want to run the benchmark on various branches/tags in a automated way.

An option to bring more flexibility (in terms of csv, png... results content storage, release...) and to avoid noise on the jupyterlab issues, is to create `https://github.com/jupyterlab/benchmarks`.

For the CI run, we still would have the flexibility to run benchmark in main `jupyterlab` repo based on a published npm artifact or in the `benchmarks` repo (with bots...).

**Comment by saulshanabrook** [comment]
I agree, we should move this to its own repo, then optionally pull it in on CI in JupyterLab actions if we want.

**Comment by echarles** [comment]
Great. I think we can process with that already now. `benchmarks` in jupyterlab org would be a good place to put and analyze the results.

**Comment by echarles** [comment]
The idea is to move the current `benchmarks` to that new repo.

**Comment by saulshanabrook** [comment]
Great, I created https://github.com/jupyterlab/benchmarks

We should try to extract out that folder and preserve git history if possible?

**Comment by saulshanabrook** [comment]
Opened https://github.com/jupyterlab/benchmarks/issues/2 to track that.
