### ISSUE TITLE
App version is not properly handled

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8812]
## Description
After the switch to `jupyter_server`, the `app_version` is not properly handled.  A workaround is to force a call to `self.app_version = self._default_app_version()`, which I've done temporarily in #8810 

## Reproduce
- `pip install jupyterlab==3.0.0a8`
- `jupyter lab`
- Go to `Help -> About` and look at the version

## Expected behavior
Shows the version as `3.0.0a8`

**Comment by echarles** [comment]
@blink1073 This is fixed in https://github.com/jupyterlab/jupyterlab_server/pull/117 and https://github.com/jupyterlab/jupyterlab/pull/8889
