### ISSUE TITLE
Opening Terminal or Refreshing Terminal shows auth token transmitted within URL 

### ISSUE THREAD

**Issue by tirumerla** [jupyterlab/jupyterlab#8813]
### Problem

* When the terminal is opened or refreshed in jupyterlab inspecting the flow on the browser reveals that the auth token is passed within URL as opposed to headers of the request when switching protocols to websocket. This poses security risk as the attacker who can view URL parameters can retrieve this token that can allow access to jupyter notebooks.

### Proposed Solution

* Pass auth token in request headers as opposed to concatenating with URL.

### Additional context
*  Environment Details - Jupyterhub running on Amazon EKS

Amazon EKS - `v1.16.8/v1.15.11 ( tested on both versions )`
Spawner details - `Kubespawner v0.12.1.dev0`
```
5cd193ad30c6:~$ jupyter-lab --version
2.0.1
5cd193ad30c6:~$ jupyterhub --version
1.1.0
5cd193ad30c6:~$ jupyter-notebook --version
6.0.3
```
**Logs**

```
[I 2020-08-11 17:51:50.395 SingleUserNotebookApp log:174] 200 POST /hub/user/john_doe/api/terminals?1597168310266 (john_doe@10.56.1.20) 49.73ms
[D 2020-08-11 17:51:50.509 SingleUserNotebookApp auth:871] Allowing whitelisted Hub user john_doe
[D 2020-08-11 17:51:50.509 SingleUserNotebookApp auth:744] Setting oauth cookie for 10.56.1.20: jupyterhub-user-john_doe, {'path': '/hub/user/john_doe/', 'httponly': True, 'secure': True}
[I 2020-08-11 17:51:50.511 SingleUserNotebookApp log:174] 200 GET /hub/user/john_doe/api/terminals?1597168310441 (john_doe@10.56.1.20) 2.72ms
[D 2020-08-11 17:51:50.924 SingleUserNotebookApp auth:871] Allowing whitelisted Hub user john_doe
[D 2020-08-11 17:51:50.924 SingleUserNotebookApp auth:744] Setting oauth cookie for 10.56.1.20: jupyterhub-user-john_doe, {'path': '/hub/user/john_doe/', 'httponly': True}
[I 2020-08-11 17:51:50.926 SingleUserNotebookApp log:174] 101 GET /hub/user/john_doe/terminals/websocket/2?token=[secret] (john_doe@10.56.1.20) 2.34ms
[D 2020-08-11 17:51:50.926 SingleUserNotebookApp zmqhandlers:157] Opening websocket /hub/user/john_doe/terminals/websocket/2
TermSocket.open: 2
TermSocket.open: Opened 2
[D 2020-08-11 17:51:51.208 SingleUserNotebookApp auth:871] Allowing whitelisted Hub user john_doe
[D 2020-08-11 17:51:51.208 SingleUserNotebookApp auth:744] Setting oauth cookie for 10.56.1.20: jupyterhub-user-john_doe, {'path': '/hub/user/john_doe/', 'httponly': True, 'secure': True}
[I 2020-08-11 17:51:51.213 SingleUserNotebookApp log:174] 204 PUT /hub/user/john_doe/lab/api/workspaces/lab?1597168311142 (john_doe@10.56.1.20) 5.85ms
[D 2020-08-11 17:51:51.962 SingleUserNotebookApp auth:871] Allowing whitelisted Hub user john_doe
[D 2020-08-11 17:51:51.962 SingleUserNotebookApp auth:744] Setting oauth cookie for 10.56.1.20: jupyterhub-user-john_doe, {'path': '/hub/user/john_doe/', 'httponly': True, 'secure': True}
```

**Steps to reproduce** 
1. Once the user pod spawns, open browser inspect window 
2. Open launcher > click on terminal
3. You will see `wss://xyz.com/hub/user/john_doe/terminals/websocket/1?token=xxxxxxxxxxxxxx` in the request URL.
Anyone having access to the above URL can get into that user's environment using `https://xyz.com/hub/user/john_doe/?token=xxxxxxxxxxxxxx`

Would be great to know if there is a way to fix this issue.
    
Thanks.

**Comment by tirumerla** [comment]
@blink1073  Any updates on this?

**Comment by blink1073** [comment]
Hi @tirumerla, I just got back from vacation.  Looking at [https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url](owasp), this is low risk because it is not a user-facing URL.  However, I will make a fix and backport it to 2.x and 1.x.   Thanks for the report!

**Comment by tirumerla** [comment]
> Hi @tirumerla, I just got back from vacation. Looking at [https://owasp.org/www-community/vulnerabilities/Information_exposure_through_query_strings_in_url](owasp), this is low risk because it is not a user-facing URL. However, I will make a fix and backport it to 2.x and 1.x. Thanks for the report!

Awesome thank you so @blink1073 for your quick response.

**Comment by jcleyba** [comment]
@blink1073 Hey Steven, looks like without the token in the url, websocket connection fails with 403 when trying to use the `services` library. I guess that in the context of jupyterlab, auth happens via cookies (maybe) but outside of that context, connection fails. 
This has been reported for terminal interface in issue https://github.com/jupyterlab/jupyterlab/issues/9070 and it also happens for kernel interface. How do websockets authenticate without token?

Thanks.

**Comment by tirumerla** [comment]
Hi @jasongrout we also observed `session_id` is being passed into the URL. People can easily inherit the session unless there is a validation of the session. 
https://github.com/jupyterlab/jupyterlab/blob/9ddc7853beddcd8d5a01901c881afdc7f4471ade/packages/services/src/kernel/default.ts#L1216
Wondering if there is something that can be changed here to pass it as a header rather than concatenating to the URL.

**Comment by jasongrout** [comment]
Can you open a new issue, since this is closed now?
