### ISSUE TITLE
Double-click action on dashboard

### ISSUE THREAD

**Issue by michaelaye** [jupyterlab/jupyterlab#882]
Currently, when double-clicking a notebook name, instead of opening it, the renaming UI becomes active. Instead, one has to click on the much smaller area for the icon to open the notebook.
I find this UI harder to use than before, where a single-click on the filename opens the notebook.
Could we have this at least configurable to the user's preference? (best-case scenario) I find the renamer-UI pops up so often, it get's annoying rather fast.

Using 0.2.0 from conda-forge on OSX 10.11 with Safari 9.1.2

**Comment by ellisonbg** [comment]
Fixed in master.
