### ISSUE TITLE
Phosphor shim is not fully functional

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8822]
The phosphor [shim](https://github.com/jupyterlab/jupyterlab/blob/master/buildutils/src/webpack.config.base.ts#L66) relies on a local `@lumino` package being installed.   We probably need some more advanced logic to install `lumino` if we detect that `@phosphor` packages are installed.

cc @jasongrout

**Comment by jasongrout** [comment]
The easiest way to do this is to make buildutils depend on the lumino packages, right?

**Comment by blink1073** [comment]
Good point, yep
