### ISSUE TITLE
Help translate JupyterLab

### ISSUE THREAD

**Issue by goanpeca** [jupyterlab/jupyterlab#8829]
If you want to help translate JupyterLab to your language of choice, please head over to [Crowdin](https://crowdin.com/project/jupyterlab) and join to start translating!

<img width="804" alt="Screen Shot 2020-08-13 at 11 21 24" src="https://user-images.githubusercontent.com/3627835/90160238-21f7c280-dd57-11ea-8f60-572f1d21cbf9.png">

If you do not yet see your language listed, just ask for it to one of the project managers in the Crowdin interface.

**Comment by bobmayuze** [comment]
are we planning on pushing this multi-language support to the 3.0 release?

**Comment by goanpeca** [comment]
Hi @bobmayuze, yes the infrastructure is already inside master (3.x). The availability of languages is subject to the progress made in crowdin for a given language.

As languages are completed and proofread, the language packs will then become available.

**Comment by comradekingu** [comment]
I would contribute if this was on Weblate instead, because of https://github.com/jitsi/jitsi-meet/issues/5056#issuecomment-612239691
In two months, only one language has coverage, which is par for the course on Crowdin.

**Comment by fitojb** [comment]
It’s unfortunate that you are subjecting your contributors to use a proprietary platform like that.

**Comment by JasonWeill** [comment]
Closing; this should be surfaced on our Discourse forum and other social channels. Thanks!
