### ISSUE TITLE
Add unit tests for prebuilt extensions

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8867]
### Problem
We do not have any unit tests covering dynamic extensions.

### Proposed Solution
Add unit tests for prebuilt extensions

**Comment by fish-dango** [comment]
I can take a try at this!

**Comment by NoobMaster1999** [comment]
I want to solve this issue. Can anyone please assign me the issue..???

**Comment by blink1073** [comment]
@fish-dango, were you currently working on this?  If not, we can assign it to @NoobMaster1999.

**Comment by NoobMaster1999** [comment]
No I am not working on this. I want to start

**Comment by NoobMaster1999** [comment]
@blink1073 is there any update??

**Comment by blink1073** [comment]
I've assigned you @NoobMaster1999

**Comment by JasonWeill** [comment]
Closing because extensions now have unit tests; please open other issues if you have further questions.
