### ISSUE TITLE
toolbar button missing 

### ISSUE THREAD

**Issue by SonakshiGrover** [jupyterlab/jupyterlab#8873]
Hello,

I am trying to add a toolbar button to my jupyterlab Notebook. For that, I am following the instructions here [https://jupyterlab.readthedocs.io/en/stable/developer/notebook.html?highlight=cookie%20cutter#adding-a-button-to-the-toolbar](https://jupyterlab.readthedocs.io/en/stable/developer/notebook.html?highlight=cookie%20cutter#adding-a-button-to-the-toolbar)

![image](https://user-images.githubusercontent.com/16288623/90824136-c5af1880-e2eb-11ea-88f4-227e69072252.png)

The button seems to be working as intended but its icon doesn't show up (icon should show up where the red circle is in the above fig). There is a discussion on an issue similar to this [7959](https://github.com/jupyterlab/jupyterlab/issues/7959). Referring to what @jasongrout commented in that thread, I checked the same for my button and the button doesn't seem to have a path for SVG. I think its something to with the npm modules version, but I am not sure what those are and how to resolve this. 

Any suggestions would be very helpful!

PS: I am using jupyter lab 2.2.2.

**Comment by rahulpshah** [comment]
Hi @SonakshiGrover do you see any errors in the JS console? Is the environment you are running a fresh install or it has some extensions installed. You might want to look at this issue (https://github.com/jupyterlab/jupyterlab/issues/7129) or check this out - https://jupyterlab.readthedocs.io/en/stable/developer/ui_components.html#reusing-jupyterlab-ui

**Comment by SonakshiGrover** [comment]
Hi @rahulpshah Here is what my JS console shows:

![image](https://user-images.githubusercontent.com/16288623/90840599-403d5f80-e30f-11ea-9337-24a8473b24c7.png)

The environment I am running it in, is basically a fresh install and on top of it I have added an extension (for adding this button on the toolbar). So all the buttons which come by default with jupyter lab are visible, but the button I added myself doesn't show up in the sense that the icon for it is not visible.

**Comment by fcollonval** [comment]
@SonakshiGrover could you provide more details on the CSS class you used to add an icon or did you use a custom svg?
From the error you seem to be willing to obtain the icon from an erroneous url.

**Comment by fcollonval** [comment]
Closing as targeting an unsupported version
