### ISSUE TITLE
Display identifying kernel name when shared by multiple notebooks/consoles

### ISSUE THREAD

**Issue by Gdsimms** [jupyterlab/jupyterlab#8881]
### Problem

When sharing a kernel between notebooks (for example making scratch calculations in one without altering the main workflow in the other) both interfaces simply display (for example) "Python 3 ◯" in the top right of their toolbar. However, they also display the same thing if they are _not_ sharing a kernel, and additional notebooks also display the same thing. So really, it is displaying a _kernel type_, not a _kernel name_ or unique identifier for the active kernel for that notebook.

Moreover, when one uses the "Select Kernel" dialog, the dialog does not indicate the particular kernel that the notebook or console is currently using. 

**It would be helpful for users who have multiple documents and/or consoles running with some kernels shared, to have some simple way of displaying a unique identifier for the particular kernel instance that is being used by their interface (notebook or console).**

(Console sessions don't display the kernel type openly, but it is in a tooltip when hovering the mouse over the tab. Notebooks do _not_ display this information in the tooltip when hovering over their tab.)

### Proposed Solution

Make use of the right hand side of the toolbar that currently displays things like "Python 3 ◯" to instead display "Python 3 (2 of 3) ◯" or "Python 3 (NotebookFileName.ipynb) ◯". I actually prefer the "(n of m)" description because it isn't too verbose and it should be very easy to keep track of and implement. 

The same information could be in the mouse-hover tooltip in the tab for console sessions.

**Comment by jweill-aws** [comment]
Closing in favor of #1072.
