### ISSUE TITLE
Unable to submit `body: FormData` in `ServerConnection.makeRequest()`

### ISSUE THREAD

**Issue by faucct** [jupyterlab/jupyterlab#8890]
When I submit `body: FormData` to `ServerConnection.makeRequest()` `Content-Type` header (`multipart/form-data ...`) gets overridden with `application/json`. According to the [code](https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/serverconnection.ts#L298), this happens when `Request#bodyUsed` is `false`. I believe that in my case `bodyUsed` should be `true`, but it is not:

```
form_data = new FormData()
form_data.append('key', 'value')
new Request('http://example.com', {body: form_data, method: 'POST'}).bodyUsed
// false
```

I also tried to get `bodyUsed` with some other body type (e.g. string), but have failed:

```
new Request('http://example.com', {body: 'key=value', method: 'POST'}).bodyUsed
// false
```

I have tried Safari 13.1.2 (15609.3.5.1.3), Yandex 20.8.0.893 and Firefox 79.0.

What should this code work like?
I believe that the check should be changed from `!request.bodyUsed` to `!request.headers.has('Content-Type')`.

**Comment by faucct** [comment]
Here is the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Body/bodyUsed) for this field, which makes me think that this field is not about presence of `body`, if I understand correctly what you are trying to achieve here.

**Comment by faucct** [comment]
Could this get a release, please? It looks like it is not easy to install a patched version with `pip`.

**Comment by blink1073** [comment]
Hi @faucct, are you building against JupyterLab 2.2 or 3.0 alpha?

**Comment by faucct** [comment]
2.2 it is.

**Comment by blink1073** [comment]
In progress: https://github.com/jupyterlab/jupyterlab/pull/8892

**Comment by faucct** [comment]
Thanks!
