### ISSUE TITLE
set_next_input delayed execution when run within widget on_click function

### ISSUE THREAD

**Issue by JohnOmernik** [jupyterlab/jupyterlab#8893]
# Description

When running a set_next_input it works find run from a cell, but if you do it in a function call on a button widget on_click, it only works after the next cell you run. 

## Reproduce
This  in a cell will insert a cell bellow with the print statement in it

```from IPython.display import display
from ipywidgets import widgets
ipy = get_ipython()
ipy.set_next_input("print('No Button')")
```

This however, running this:
```
from IPython.display import display
from ipywidgets import widgets
ipy = get_ipython()
def button_click(b):
    ipy.set_next_input("print('In Button')")
    
mybutton = widgets.Button(description="Press")
mybutton.on_click(button_click)
display(widgets.VBox([mybutton]))
```
and pressing the button will do nothing, until you next your run cell. For example, if you put
```
print("")
```
in another cell, it will show the 
```
print('In Button")
```
From the previous run. 

## Expected behavior

When you press the button, it should insert a cell, and fill it with the code requested. 

## Context

- Operating System and version: Running on MacOS using Conda
- Browser and version: Chrome 84.0.4147.105 
- JupyterLab version: 2.1.4

**Comment by jasongrout** [comment]
I think a comm message (which is the part of the jupyter protocol that the button uses for the click events) does not support set_next_input.

**Comment by jasongrout** [comment]
To be more technical and specific, for those that want the details: set_next_input uses the [payload attribute](https://jupyter-client.readthedocs.io/en/stable/messaging.html#payloads-deprecated) of an execute_request reply message. Since buttons use comm messages to communicate values, the payload option is not available.

In short, it's not supported by the underlying protocol. It's only supported by directly executed cells.

**Comment by jasongrout** [comment]
I wish there were an easier and more fruitful answer. As it is, we don't have a lot of ways that a kernel can influence the structure of the document on the frontend. Part of that is design, keeping the kernel execution and the document structure cleanly separated. Even set_next_input is relying on a deprecated feature of the Jupyter protocol.

Thanks again for making a clear issue so we could answer the heart of the matter quickly.

**Comment by JohnOmernik** [comment]
This is frustrating because it's "sorta" working. (When you put in the next input manually, you get the result you wanted from the button push).   This is also frustrating because the deprecated feature was not replaced something to handle this situation. (i.e. the set_next_input working in a way that makes sense).  Is there any way for me to be able to have Widget put data into the next cell? I don't even care about running it, I just want to fill it.  This is a really handy tool for being able to walk users through complicated code to do things like visualizations, while showing them what they are doing...

**Comment by jasongrout** [comment]
>  Is there any way for me to be able to have Widget put data into the next cell?

Sorry, not that I can think of right now. Again, it's mostly about the general design principle in Jupyter protocols to keep the document structure and kernel execution separate, with this one special case of setting the next input supported in limited circumstances.

**Comment by JohnOmernik** [comment]
Hey Jason, quick question. 

I am back at this problem, I thought "why not use asyncio?"  

Basically, my flow is this:

1. start a async function within a class that watches for when a class variable is filled.  It just loops watching for that. When it sees that variable is filled, it runs the set next input. 

2. display my widget display grid.   When a user presses a button widget, instead of running the set_next_input, it just just fills the variable that being watched in 1
3. The function should see the variable fill and call the next_input and we are all happy. 

The issue is this:

I run the asyncio function and it starts watching ( I put in some debug statements to validate this) (In fact, if I DON'T call the display() function on the displaygrid, it will happily just keep counting input without blocking the execution of the next cell. 

However, when I run display, it "appears" to stop counting. However it is not. Display is somehow taking focus away from the notebook and only into the widget. 

Pressing the button does not fill the next cell.  But more importantly, if I don't press the button, and instead just go to the next cell and type print("") it will show my counter from the previous asyncio function, and start displaying the counting again (in the next cell)!

I think I have narrowed it down to pressing the button, I've included basic code here 

```
import asyncio
from ipywidgets import GridspecLayout, widgets
from IPython.display import display_html, display, Javascript, FileLink, FileLinks, Image

class Counter:
    counter = 0
    running = False
    width="600px"
    height="200px"
    dg = None
    def __init__(self):
        self.counter = 0
        self.dg = GridspecLayout(3, 6, width=self.width, height=self.height)
        self.out_graph = widgets.Output()
        self.btn_gen = widgets.Button(description="Press me")
        self.btn_gen.on_click(self.gen)
        self.dg[1, 2:3] = self.btn_gen
        self.dg[2, :] = self.out_graph
    def displayGrid(self):
        display(self.dg)
    async def run(self, taskname):
        while True:
            mytask = None
            self.counter += 1
            print(self.counter)
            if self.counter >= 15:
                for task in asyncio.all_tasks():
                    if task.get_name() == taskname:
                        mytask = task
                        break
                task.cancel()    
                self.running = False
                self.reset()
            await asyncio.sleep(1.0)
    def gen(self, b):
        pass
        #with self.out_graph:
        #    print("Hi")
        #print("yo")
    def startLoop(self):
        if self.running:
            print("Already Running")
        else:
            print("Starting")
            asyncio.create_task(self.run("myname"), name="myname")
            self.running = True
            self.displayGrid()
    def reset(self):
        self.counter = 0
    ```
Then run this in the next cell
```
t = Counter()
```
And then start the counter:
```
t.startLoop()
```


When you press the button, the counter stops displaying, but the counting is still happening in the background.  It's the action of pressing the button that basically stops ALL automatic interactions (including set_next_input, but I've removed that aspect here)

Is there a way, after pressing a button to hand the control back to notebook, so things like asyncio can work properly and keep displaying?
