### ISSUE TITLE
Module federation without a webpack dependency

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8895]
### Problem

Right now, extensions require a dependency on `@jupyterlab/builder`, which in turn has a dev dependency on webpack. This is a pretty heavy-weight dependency.

### Proposed Solution

Investigate if we can build an extension without depending on webpack. Possible tools include these webpack config options:

* [context](https://webpack.js.org/configuration/entry-context/#context)
* [resolve modules](https://webpack.js.org/configuration/resolve/#resolvemodules)
* [resolveLoader](https://webpack.js.org/configuration/resolve/#resolveloader) to point the loaders to the extension system files
* as a last resort, a [loader plugin](https://webpack.js.org/configuration/resolve/#resolveplugins)

**Comment by jasongrout** [comment]
@blink1073 - you had some thoughts from when you experimented with this for why the extension had to depend on webpack. Can you jot these down here?

**Comment by blink1073** [comment]
Initial thought: it is a devDependency, and doesn't affect the runtime.  I don't think it is worth exploring this in the short term.

**Comment by blink1073** [comment]
Bottom line is we need there to be a single webpack compiler instance.  I'm not sure how to rectify that without having webpack as a devDependency in the same node_modules tree.

**Comment by jasongrout** [comment]
> it is a devDependency

Good point. I forgot it was a dev dependency. I've modified the OP to reflect that.

> Bottom line is we need there to be a single webpack compiler instance.

My initial thinking was that the single webpack compiler is shipped with JupyterLab, and we use the resolve config options to point to the extension's source and node_modules. Are you saying an extension might have webpack installed for some other reason, and somehow that will get instantiated when compiling?

One effect of having the webpack as a dev dependency of an extension (like it is now) is that an extension can include other webpack loaders to influence how their extension is compiled (i.e., they can use the webpack bang notation to use a custom loader). Most people would probably think of this as a positive thing.

**Comment by jasongrout** [comment]
>  I don't think it is worth exploring this in the short term.

I'll take this off the 3.0 milestone. You're right that we have more pressing needs, and it's not *clear* that this thought will be way better than our current system.

**Comment by jasongrout** [comment]
Closing as there is not a clear present need. Can reopen later if there the need is there.
