### ISSUE TITLE
Chrome browser CPU usage high

### ISSUE THREAD

**Issue by steevenlee** [jupyterlab/jupyterlab#8901]
Hi,

I'm seeing high Chrome CPU usage once open a jupyter tab in chrome. By pressing "shift+esc" and open chrome inter task monitor, the jupyterlab tab consumes about ~40% cpu, and broswer process consumes ~10% cpu. This cpu consumption is constant it shorten laptop battery.

No frequent URL access from server log.

**Comment by jasongrout** [comment]
Please fill out the [bug report issue template](https://raw.githubusercontent.com/jupyterlab/jupyterlab/master/.github/ISSUE_TEMPLATE/bug_report.md) with the information it requests about your version of JupyterLab, Chrome, OS, etc.

Also, I would suggest going through the troubleshooting/diagnosis guide in the documentation at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to try to narrow down the problem.

**Comment by jasongrout** [comment]
Closing as there was no followup.
