### ISSUE TITLE
Revert Shadow DOM PR for 3.0

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#8907]
In the past couple of dev meetings we have talked about some issues related to switching the notebook to use Shadow DOM https://github.com/jupyterlab/jupyterlab/pull/8584.

On one hand, we appreciate the work that was done in that PR and think it does possibly bring some nice encapsulation to the implementation. On the other, there are a number of breaking issues it introduced, and we don't have conclusive evidence that it makes things better.

So what we decided was that we have to figure out if we want to keep it in by the RC release date. I am not sure when this is, but I assume in a month or so?

Before that time, if we want to keep it in, someone needs to:

* Do further benchmarks to see where it improves performance and if it is meaningful: https://github.com/jupyterlab/jupyterlab/pull/8584#issuecomment-680027095
* Fix depredations caused to switching to dark theme as well as to the debugger plugin. I am not sure if there are more issues than this. Please chime in with details if you have them.

If no one has bandwidth to work on this in that timeframe, then I think the plan is to revert the merge, at least for the initial 3.0.0 release, until someone has time to look into these.

cc @AlbertHilb

**Comment by goanpeca** [comment]
>Do further benchmarks to see where it improves performance and if it is meaningful:

Working on this ✋

**Comment by echarles** [comment]
We are now running the benchmark in a more automated with various scenarii. (https://github.com/jupyterlab/benchmarks/actions).

I have extracted a few runs that compare before/after shadow dom. The trend is an enhancement, but content-visibility effect seems to be annihilated by shadow dom (the order of magnitude of the enhancement content-visibility gives is the same as the shadow dom). 

Base on the unexpected side effects we have now with the extensions loading, I think we should rollback the shadow dom.

![comparison-1](https://user-images.githubusercontent.com/226720/92690781-dd554c00-f341-11ea-8fc5-61402b2d4c79.png)

![comparison-2](https://user-images.githubusercontent.com/226720/92690796-e1816980-f341-11ea-95b7-59a17e0fec44.png)

![comparison-3](https://user-images.githubusercontent.com/226720/92690806-e47c5a00-f341-11ea-8461-a66bebe3e90c.png)

**Comment by echarles** [comment]
@jasongrout We have well received your yesterday comment on `calibration`. We will try the shadow-dom comparison in the same virtual machine to remove that dependency. We will post here the results as soon as we have them.

**Comment by jasongrout** [comment]
In the dev meeting today, we reviewed some benchmarks @echarles has been doing that show some great performance benefits using `display: block` and content-hidden css, which apparently don't work when using a shadow dom for the codemirror. We decided to revert this change for 3.0, and if someone is willing to continue pursuing it and the correlated fixes needed, taking it up after 3.0.
