### ISSUE TITLE
Extension which gets run automatically when an .ipynb file is opened

### ISSUE THREAD

**Issue by SonakshiGrover** [jupyterlab/jupyterlab#8922]
Is it possible to run a jupyterlab extension when a notebook file is opened, without adding a button to the toolbar or adding any UI component. I want to basically just modify a cell in the currently opened .ipynb file and run all the cells (to refelect the change in the modified cell) without any manual intervention like clicking of button, etc. 

@minrk, @jasongrout  Please let me know if that's possible!!

I did find a way to do it in classic jupyter notebooks, but couldn't find an equivalent for jupyterlab. Sorry of this has been asked before. 

PS: I am running jupyterlab with jupyterhub. So I am also trying to reflect this extension for all the users in jupyterhub.

**Comment by jasongrout** [comment]
Yes. In order to add a button to the toolbar, for example, you supply a callback that is called when a notebook is opened. Just use that callback to do whatever else you want.

**Comment by SonakshiGrover** [comment]
@jasongrout Thanks for the prompt reply. Though could you please be more elaborate. 
This is what I am trying to do. Say for example this is my code for extension.

```
export class ButtonExtension implements DocumentRegistry.IWidgetExtension<NotebookPanel, INotebookModel> {
 
  createNew(panel: NotebookPanel, context: DocumentRegistry.IContext<INotebookModel>): IDisposable {
    let callback = () => {
      NotebookActions.runAll(panel.content, context.sessionContext);
    };
    let button = new ToolbarButton({
      className: 'myButton',
      iconClass: 'fa fa-fast-forward',
      onClick: callback,
      tooltip: 'Run All'
    });

    panel.toolbar.insertItem(0, 'runAll', button);
    return new DisposableDelegate(() => {
      button.dispose();
    });
  }
}

```
```
function activate(app: JupyterFrontEnd) {
  app.docRegistry.addWidgetExtension('Notebook', new ButtonExtension());
};
```

I understand I just have to change callback(), but how do I run it automatically when the notebook is opened. Right now the callback() is called only when the button is clicked. Is there something like a NotebookExtension(), analogous to a buttonExtension used here, which calls callback() when the Notebook is opened?

**Comment by jasongrout** [comment]
Delete the body of `createNew` and do whatever you want in it instead. `createNew` is called with the new notebook widget. In the example, we add a toolbar button, but you can do whatever else you want with it as well.

**Comment by jasongrout** [comment]
To be clearer:

```typescript
export class ButtonExtension implements DocumentRegistry.IWidgetExtension<NotebookPanel, INotebookModel> {
 
  createNew(panel: NotebookPanel, context: DocumentRegistry.IContext<INotebookModel>): IDisposable {
    // Do what you want right here. panel is the notebook widget.
  }
}
```

**Comment by SonakshiGrover** [comment]
Hi @jasongrout Thanks! This makes sense to me now! I actually created a new extension to try this out and for that I used cookiecutter basic template and somehow that's giving me "**myextension@0.1.0 is not compatible with the current JupyterLab**" Tried upgrading my jupyterlab, but still the same error. Wasn't getting this error with my previous extension. I'll work on fixing this and let you know if I was able to run the above extension.

**Comment by jasongrout** [comment]
Great. Since we answered the original question, closing as answered.

**Comment by SonakshiGrover** [comment]
Since createNew is not a void function(), could you please let me know how to set the return value for this function? I tried: `return new DisposableDelegate(() => void);`  but that's giving an error.

**Comment by jasongrout** [comment]
Does `return new DisposableDelegate();` work? If not that, then `return new DisposableDelegate(() => {});`

**Comment by jasongrout** [comment]
I opened an issue to make it possible to not return anything. It's a good first issue for a new contributor - feel free to fix it if you like! #8927

**Comment by SonakshiGrover** [comment]
`return new DisposableDelegate()` doesn't work, though `return new DisposableDelegate(() => {});` works!! Yes I agree. Its should be possible to not return anything!

**Comment by SonakshiGrover** [comment]
Though the weird thing is that after this modification, npm build runs without any errors but the NotebookActions api I used in my createNew(),  are not executing when a new notebook is opened. I put a few debuggers like console.log() to check if the extension is running or not. The extension seems to be running as I can see the prints on the console but the NotebookActions.insertAbove() and  NotebookActions.runAll() are somehow not working.

**Comment by SonakshiGrover** [comment]
Just wanted to follow up on this issue. I haven't yet been able to run this extension. All I want is to run all the cells automatically when a notebook is opened. The weirdest part is that when I create a ToolBar button and use the index.ts code provided in the documentation, it works. But the below extension code, for running it with a new notebook widget, doesn't work. 

```
const plugin: JupyterFrontEndPlugin<void> = {
  activate,
  id: 'my-extension-name:buttonPlugin',
  autoStart: true
};

export
class ButtonExtension implements DocumentRegistry.IWidgetExtension<NotebookPanel, INotebookModel> {
  
   createNew(panel: NotebookPanel, context: DocumentRegistry.IContext<INotebookModel>): IDisposable {
    console.log("new notebook opened");
    NotebookActions.runAll(panel.content, context.sessionContext);
    return new DisposableDelegate(() => {});
      
  }
}

function activate(app: JupyterFrontEnd) {
  app.docRegistry.addWidgetExtension('Notebook', new ButtonExtension());
};


export default plugin;
```

I do get the print "new notebook opened" on the console but NotebookActions.runAll does seem to be working. And npm run build isn't giving me any error too, so i am not able to find the cause of this not working. 

Not sure if I am doing anything wrong here. @jasongrout  @blink1073  Any help/suggestion would be helpful. Thanks!

**Comment by agoose77** [comment]
@SonakshiGrover looking at [the documentation](https://jupyterlab.github.io/jupyterlab/classes/_notebook_src_index_.notebookactions.html#runall), `NotebookActions.runAll` returns a promise. You need to await that promise in order for it to be executed.

**Comment by SonakshiGrover** [comment]
@agoose77  Thanks for pointing this out. I am new to javascript and was overlooking this. I added the `NotebookActions.runAll` inside an async function and called it from within `createNew().` Though this doesn't seem to work. 

```
const plugin: JupyterFrontEndPlugin<void> = {
  activate,
  id: 'my-extension-name:buttonPlugin',
  autoStart: true
};

export
class ButtonExtension implements DocumentRegistry.IWidgetExtension<NotebookPanel, INotebookModel> {
  
   createNew(panel: NotebookPanel, context: DocumentRegistry.IContext<INotebookModel>): IDisposable {
      console.log("new notebook opened");
    
      async function f1(){
         console.log( await NotebookActions.runAll(panel.content, context.sessionContext));
      }
      f1();
      console.log('after f1'); 
      return new DisposableDelegate(() => {});
      
  }
}

function activate(app: JupyterFrontEnd) {
  app.docRegistry.addWidgetExtension('Notebook', new ButtonExtension());
};


export default plugin;
```

Whenever a notebook is opened, I do get the output of Promise variable as _**True**_ but I am getting the console print for the Promise variable after the print _**'after f1'**_. Isn't `await` supposed to halt the code execution until the Promise variable's value is returned?

**Comment by agoose77** [comment]
@SonakshiGrover as far as I recall, calling `f1()` returns the promise, rather than
