### ISSUE TITLE
Error archive age in years in file explorer

### ISSUE THREAD

**Issue by l2radamanthys** [jupyterlab/jupyterlab#8923]
## Description

The file explorer don't show correctly the archive age on file explorer, for example a file from 22 Feb 2019, age show 2 years, current date is 27 Aug 2020.  

![2020-08-27_20-42](https://user-images.githubusercontent.com/125394/91505577-4c449680-e8a6-11ea-81cf-e2a7f3bd3657.png)

![2020-08-27_20-46](https://user-images.githubusercontent.com/125394/91505670-81e97f80-e8a6-11ea-8458-858a84caf02c.png)

I suspect the rounding of dates is causing this bug

**Comment by fcollonval** [comment]
Thanks @ianhi for the user support. I transferred the issue.

**Comment by JasonWeill** [comment]
In Lab 4.1.0, a file that is 18 months old now shows a creation date, relatively, as "last year". Files that are "2 years ago" were created between 2 and 3 years before the present.
