### ISSUE TITLE
maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by jmtyson10** [jupyterlab/jupyterlab#8924]
I am new to this whole world and am in a Python class. I entered in some code and keep getting the error 'RecursionError: maximum recursion depth exceeded in comparison'.
I saved this script as permute.py in Jupyter Lab.
```python
def permute1(seq):
    if not seq:
        retrn [seq]
    else:
        res=[]
        for i in range(len(seq)):
            rest=seq[:i]+seq[i:+1:]
            for x in permute1(rest):
                res.append(seq[i:i+1]+x)
            return res
```
Opened a new notebook an imported it
```python
from permute import permute1
permute1('abc')
```
clicked run then the error popped up. I've even tried importing sys and using the sys.setrecursionlimit(10**6) and the kernel will crash and restart with out running the code.

Any help would be greatly appreciated. Thank you.

I should note that I have gotten this code to work in a Python Command Prompt just not in Jupyter.

**Comment by jasongrout** [comment]
I get a recursion error in python too.

```
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 07:56:27) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def permute1(seq):
...     if not seq:
...         retrn [seq]
...     else:
...         res=[]
...         for i in range(len(seq)):
...             rest=seq[:i]+seq[i:+1:]
...             for x in permute1(rest):
...                 res.append(seq[i:i+1]+x)
...             return res
... 
>>> permute1('abc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 8, in permute1
  File "<stdin>", line 8, in permute1
  File "<stdin>", line 8, in permute1
  [Previous line repeated 994 more times]
  File "<stdin>", line 6, in permute1
RecursionError: maximum recursion depth exceeded in comparison
```
This really sounds like a python question, not specific to Jupyter. Likely it's a runaway recursion in the code, like the error indicates.
