### ISSUE TITLE
Widget extensions shouldn't have to return a disposable

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8927]
### Problem

Currently, when creating a widget extension (like the notebook toolbar button example), the `createNew` function *must* return an IDisposable. However, an extension may want to do something with the widget without needing to dispose anything. It should be possible to not return anything.

### Proposed Solution

Here is where the interface is defined. Probably change the `IDisposable` return type to `IDisposable | void`

https://github.com/jupyterlab/jupyterlab/blob/5a67a646608797e7f4b8a1977092f72218e7545c/packages/docregistry/src/registry.ts#L1127

Then handle the case where nothing is returned here: https://github.com/jupyterlab/jupyterlab/blob/5a67a646608797e7f4b8a1977092f72218e7545c/packages/docmanager/src/widgetmanager.ts#L102-L104

### Additional context

This fixes the issue brought up in https://github.com/jupyterlab/jupyterlab/issues/8922#issuecomment-682466661

**Comment by biniona** [comment]
I'll take a go at this one if it's alright!

**Comment by LuiGiovanni** [comment]
@jasongrout Hello is this issue still open? I'd like to give it a go I'm new to contributions, is there something I need to do?

**Comment by jasongrout** [comment]
I think it is still open. If you want to open a PR fixing it, go for it!

**Comment by LuiGiovanni** [comment]
Perfect! I'll get to work on it right away thanks! Is there something I should be aware of or should know? This would be my very first contribution @jasongrout

**Comment by LuiGiovanni** [comment]
Hello, I found that this issue must be solved using Typescript, I'm sorry but I won't be able to help, if anyone else wishes to contribute go ahead. Thank you.
