### ISSUE TITLE
Fix FIXMEs in testing kernel mocks

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8929]
In https://github.com/jupyterlab/jupyterlab/pull/8921/commits/ea33b6d942a005265fefb9d0cfde96236d5efdbc, there were three FIXMEs that were ignoring typing errors. We should fix these properly.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/11159
