### ISSUE TITLE
Keyboard shortcut editor

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#893]
A user should be able to configure the keyboard shortcuts using a well designed UI and have those settings saved.

**Comment by Alok** [comment]
Any updates on this?

**Comment by jasongrout** [comment]
I think @afshin started working on a prototype, but I don't think anyone is actively working on it right now. Help is most definitely welcome!

**Comment by jasongrout** [comment]
This is now being worked on as part of https://github.com/jupyterlab/jupyterlab-shortcutui
