### ISSUE TITLE
Drag from file browser to dock panel no longer works

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#8934]
In previous versions of JupyterLab, you could drag a file from the file browser to the dock panel and pick where the file would be opened. This no longer works in master. That might have been a deliberate decision, but want to make sure before we release 3.0

**Comment by ianhi** [comment]
This is may be related to https://github.com/jupyterlab/jupyterlab/issues/8205

Also what you describe is also broken for me on version 2.1.1

**Comment by blink1073** [comment]
This was an oversight when we changed from `phosphor` -> `lumino`.  This line https://github.com/jupyterlab/jupyterlab/blob/be73243cc502bc6a3a5e33919a39e4066dfa0766/packages/filebrowser/src/listing.ts#L198 needs to updated to accommodate the expected [mimetype](https://github.com/jupyterlab/lumino/blob/938804120f58bf61e795bde9d596f6ce7573e920/packages/widgets/src/dockpanel.ts#L560)
