### ISSUE TITLE
[LabApp] Websocket ping timeout after 90000ms

### ISSUE THREAD

**Issue by xiaoland** [jupyterlab/jupyterlab#8935]
I mapped my jupyterlab server from the internal network to the external network to facilitate remote debugging. But when I tried to run the code, the kernel didn't respond, and I could see multiple outputs from the background: [LabApp] Websocket ping timeout after 90000ms.
My mapping tunnel uses TCP, there is no problem with the speed guarantee, and you can see the ws:// return with the 101 status code in the browser debugging tool.
I'm really troubled, if you know what's wrong with this, please tell me, thanks.

**Comment by Richardosgrapevine** [comment]
I encountered the same problem, how did you solve this exactly? Desperately looking for a solution.
