### ISSUE TITLE
Build API Tests Failing on Windows

### ISSUE THREAD

**Issue by blink1073** [jupyterlab/jupyterlab#8936]
## Description
We are currently skipping the build tests in `jupyterlab/tests/test_build_api.py` on Windows.  We should reinstate them and fix the underlying error.

## Reproduce
Uncomment the skipped tests and run CI on Windows.

**Comment by jasongrout** [comment]
@ivanov or @vidartf - if you have time, could you double-check if `jupyter lab build` in the latest beta (3.0.0b4) works on windows?

**Comment by vidartf** [comment]
For what is it worth: With a windows dev install, the tests fail locally as well. I'll try to troubleshoot them.

**Comment by jasongrout** [comment]
The underlying issue might be explored at https://github.com/jupyterlab/jupyterlab/issues/9698
