### ISSUE TITLE
Left sidebar panel very narrow at startup

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8938]
## Description

Compare the width of the left sidebar in JLab 2.x:

<img width="539" alt="Screen Shot 2020-08-31 at 9 23 21 AM" src="https://user-images.githubusercontent.com/192614/91742954-e7ba5d80-eb6b-11ea-8474-9e8c79b52bc7.png">

to the width in 3.0.0b1:

<img width="448" alt="Screen Shot 2020-08-31 at 9 22 15 AM" src="https://user-images.githubusercontent.com/192614/91742925-d8d3ab00-eb6b-11ea-88a9-528d43dda2c8.png">

## Reproduce

Install jlab 2.x and 3.0.0b1 and start it up to see the default sidebar width.

## Expected behavior

To me, it would be better to have the wider sidebar by default, exposing the extra column in the file browser, and it doesn't feel so crammed.

Was the change to make it narrower an explicit UX decision?

**Comment by schaffino** [comment]
I'm also seeing this in 2.1.5

**Comment by jasongrout** [comment]
Interesting. I tested on the currently released jupyterlab (just `conda install jupyterlab`, presumably 2.2.6 or something) and it seemed fine (that's where my first screenshot came from)

**Comment by ellisonbg** [comment]
Since 2.x, the left sidebar width has been set as a percentage width of the window. If there a chance you opened it in a narrow window?

**Comment by jasongrout** [comment]
I haven't noticed this recently, so I'll close this now.

**Comment by ellisonbg** [comment]
I am now running into this - should be fixed before the final release.

**Comment by jasongrout** [comment]
We saw it with @afshin yesterday too. He says he's been seeing it sporadically for a year or so.
