### ISSUE TITLE
Binder bot dev mode does not redirect to JupyterLab

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#8943]
## Description

Looks like the Binder link posted by the bot on new PRs does not redirect to the dev mode lab anymore:

![image](https://user-images.githubusercontent.com/591645/91857134-c76fc900-ec67-11ea-97df-62e98b074271.png)

## Reproduce

Go to an open PR and click on the Binder link:

![image](https://user-images.githubusercontent.com/591645/91866428-cdb77280-ec72-11ea-8e60-0639730a085f.png)

**Comment by jtpio** [comment]
This might be related to https://github.com/jupyterhub/repo2docker/issues/945

**Comment by blink1073** [comment]
@Zsailer and I talked about this.  We think the best path forward is to re-instate JupyterLab as a classic notebook extension for JupyterLab 3.0, removing in JupyterLab 4.0.

This would entail re-instating [`extension.py`](https://github.com/jupyterlab/jupyterlab/blob/ea2a2bf1251a13a5e129d70a1ada8e618d3276ea/jupyterlab/extension.py) and the [`config`](https://github.com/jupyterlab/jupyterlab/blob/ea2a2bf1251a13a5e129d70a1ada8e618d3276ea/jupyter-config/jupyter_notebook_config.d/jupyterlab.json).

**Comment by jasongrout** [comment]
Is this decision still in effect? I notice that the dependencies in setup.py do *not* list the classic notebook server, but instead list jupyter_server.

**Comment by jasongrout** [comment]
I think I understand better now - what we have now is that jupyterlab works both as a classic notebook extension and as a jupyter server extension (using the classic notebook server extension shim), but defaults to depending on jupyter server.
