### ISSUE TITLE
Core mode still loads dynamic extensions

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8951]
## Description

`jupyter lab --core-mode` loads dynamic extensions

## Reproduce

1. Install jupyterlab 3.0b1 and a dynamic extension
2. `jupyter lab --core-mode`. It claims "Running the core application with no additional extensions or settings"
3. Note that the dynamic extension is active

## Expected behavior

Not sure. Definitely we should change the claim if we are going to load dynamic extensions. If `--core-mode` is really like a safe mode, perhaps we don't load dynamic extensions.

## Context

- JupyterLab version: JupyterLab 3.0b1

**Comment by blink1073** [comment]
I think core mode should not load dynamic extensions.  It is meant be the "pristine" version of the application.
