### ISSUE TITLE
Extensions should be able to specify module sharing options for dependencies

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8953]
### Problem

In JLab 3.0 right now, there is no way for an extension to specify that certain dependencies should not be bundled, or should be considered singletons, i.e., options in the module federation. It would be very useful if they could to cut down on code size. For example, ipywidget custom widgets should be able to specify that the base widget package is a singleton and not imported (bundled), since it will be provided by the system. (It has to be provided by the system, since it provides a token we use).

### Proposed Solution

Perhaps such information can be listed in the package.json jupyterlab key and used to modify the webpack config when compiling.

**Comment by blink1073** [comment]
:+1: to making this configurable in the jupyterlab key.
