### ISSUE TITLE
Capstone Assignment W1

### ISSUE THREAD

**Issue by pq70pq** [jupyterlab/jupyterlab#8955]
#!/usr/bin/env python
# coding: utf-8

# This Python notebook is created for submission of the first Assignment of Applied Data Science Capstone. In this notebook I will import pandas library and numpy library and then push it to my github repository.

# In[3]:

import pandas as pd
import numpy as np

# In[4]:

print("Hello Capstone Project Course!")

# In[ ]:

**Comment by blink1073** [comment]
I believe this was opened on accident.  Cheers!
