### ISSUE TITLE
Some UI overlap issues in the beta

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab#8957]
I just upgraded to the new beta and noticed some UI quirks that I wanted to raise. The "filter files by name" box seems to be overlapping with the elements around it. 

![image](https://user-images.githubusercontent.com/1839645/92182184-e608c800-edff-11ea-955c-5403a31e793c.png)

This overlapping weirdness also seems to happen in single document mode:

![image](https://user-images.githubusercontent.com/1839645/92182172-e012e700-edff-11ea-8ae9-6165bae783c5.png)

**Comment by jasongrout** [comment]
What is your browser zoom level? If it's not 100%, do you still see the problems when you set the browser zoom level to 100%

What browser and beta are you using?

**Comment by choldgraf** [comment]
I just started it up again and can no longer reproduce this problem (on multiple zoom levels). So I'm gonna close this but feel free to re-open if you think it's worth digging into.

FWIW, latest Chrome, W10, latest beta (just ran `pip install -U --pre jupyterlab`)
