### ISSUE TITLE
Problems with settings in master

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#8958]
## Description

I am seeing two issues with the settings system in master:

1. A flood of error messages in the console

![Screen Shot 2020-09-04 at 11 18 24 AM](https://user-images.githubusercontent.com/27600/92273595-80b8e380-eea0-11ea-8116-4ccb9fe14b42.png)

2 When I try to open the advanced settings editor, nothing happens. No UI pops up and no error message.

## Reproduce

I have now observed this in Chrome and Firefox, in a clean conda env, after starting from scratch using:

```
time (git clean -fdx \
    && pip uninstall -y jupyterlab \
    && pip install -U -v -e . \
    && jlpm install \
    && jlpm run build \
    && jlpm run build:core \
    && jupyter lab clean \
    && jupyter lab build \
    && say "I finished that super long thing I was doing.")
```

## Expected behavior

No error messages in the console, and advanced settings editor should open.

## Context

- Operating System and version: Mac Mojave 10.14.6
- Browser and version: Latest Firefox and Chrome
- JupyterLab version: master

**Comment by ianhi** [comment]
I looked into this a little bit (need settings for some vim keymap stuff) and found that these errors started appearing in `3.0.0a5` and that the settings worked as expected in `3.0.0a4`. This corresponds to a jump in `jupytelabr_server` from 1.2 to 2

**Comment by ianhi** [comment]
Oh and there is indeed an issue there about this: https://github.com/jupyterlab/jupyterlab_server/issues/113

**Comment by afshin** [comment]
Thanks @ianhi! I forgot I'd actually thought about this at all before 😂

**Comment by jasongrout** [comment]
@afshin, pinging you on this one...

**Comment by afshin** [comment]
This should be fixed when we publish https://github.com/jupyterlab/jupyterlab_server/pull/125
