### ISSUE TITLE
Use block display instead of flex display for Notebook panel

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#8967]
For better performance when opening notebook, an option is to use block display instead of flex display.

This has been discussed during last weekly meeting with @jasongrout @vidartf and @blink1073 

I have worked with @goanpeca on this and the preliminary result are published on https://jupyterlab-benchmarks.readthedocs.io/en/latest/strategies/index.html#block-div This test is for 2.2.x branch which does not have shadow dom. We still need to try with master with shadow dom.

**Comment by krassowski** [comment]
Closing as implemented in https://github.com/jupyterlab/jupyterlab/pull/8968 which was then forward-ported in https://github.com/jupyterlab/jupyterlab/pull/10127
