### ISSUE TITLE
Remove Copy Shareable Link?

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#8973]
There is currently a "Copy Shareable Link" in the file browser context menu. This made sense to have previously, but now, all URLs in JupyterLab are fully shareable. Because of this, I think we should remove the Copy Shareable Link.

**Comment by ellisonbg** [comment]
Leaving as is - the Copy Shareable Link is working fine in master and provides a way for a user to get a link to a document that isn't open.

**Comment by timkpaine** [comment]
@ellisonbg I also like the idea/feature of overriding the functionality of "Copy Shareable Link" [here](https://github.com/jupyterlab/jupyterlab/issues/5388) as it allows you to overload this functionality to e.g. point to a `Voilà` instance of the app, or any other customizations you want
