### ISSUE TITLE
The jupyter paths overrides of `TestEnv` prevents nbconvert 6.0 from finding templates

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#8976]
This causes `browser_check` to fail over missing nbconvert templates.

**Comment by blink1073** [comment]
We rely on these overrides for test isolation.

**Comment by SylvainCorlay** [comment]
The problem is that nbconvert requires the templates in `PREFIX/share/jupyter/nbconvert/templates` and can't be found with these overrides.

**Comment by blink1073** [comment]
Understood, but we need this behavior, which is why I opened https://github.com/jupyter/nbconvert/pull/1367.

**Comment by blink1073** [comment]
Fixed by nbconvert 6.0.1
