### ISSUE TITLE
search for whole words

### ISSUE THREAD

**Issue by gittar** [jupyterlab/jupyterlab#8981]
### Problem

When searching I often need to find the exact whole word e.g. 

    point

and not any longer strings containing this word, e.g. 

    pointer

or 

    datapoint

Currently to do this I have to activate regep (".*") in the searchbox and enclose the search term with with the word boundary expressions, i.e. the search box must contain 

    \bpoint\b

This is somewhat cumbersome and I need this quite frequently.

### Proposed Solution
I propose - as e.g. present in the search box of the widely-used VS Code - to add a switch "Ab" (whole word)  to the existing switches "Aa" (capitalization) and ".*" (regular expression). Thus the current list of switches

    "Aa", ".*"

should be changed to

    "Aa", "Ab", ".*"

which is the same order as in VS Code. This would make searching more comfortable while being compatible with VS Code

**Comment by saraafernandeez** [comment]
This improvement would be perfect!

**Comment by krassowski** [comment]
@saraafernandeez you will then be happy to hear that this was added in JupyterLab 4.0 (by https://github.com/jupyterlab/jupyterlab/pull/13777). You should be able to access this function by clicking on `[ab]` icon in the search box:

![image](https://github.com/jupyterlab/jupyterlab/assets/5832902/09ae9b34-406f-4a60-b9ce-4446ef9f213d)

I am closing as completed :tada:
