### ISSUE TITLE
Update jupyter.org to point to latest release

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#8986]
We are still announcing JupyterLab 1.0 on jupyter.org, as well as sending them to a 1.0 binder.

This confused at least one person: https://discourse.jupyter.org/t/list-of-supported-dependency-version-for-binder/5945/3

This should be updated to no longer reference 1.0, as well as updating the binder link to point to the latest release of jlab.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/list-of-supported-dependency-version-for-binder/5945/7

**Comment by goanpeca** [comment]
Fixed by https://github.com/jupyter/jupyter.github.io/pull/383
