### ISSUE TITLE
UI for kernel startup and error alerts

### ISSUE THREAD

**Issue by danielballan** [jupyterlab/jupyterlab#899]
JupyterLab is currently missing the notebook UI that displays notifications about the kernel startup. When a kernel fails to start, the UI provides a way for the user to see the traceback from the notebook server.

To reproduce this feature:
- Make a normal kernelspec but provide a wrong path to the Python binary.
- Open a notebook.
- Wait for the kernel startup process to time out. A red error notification will appear in the top right.
- Clicking that red patch opens a modal containing the traceback from the server.

Categorizing this as "component:Notebook" because it is needed for notebook parity, but clearly it would be useful on anything that has a kernel attached.

**Comment by blink1073** [comment]
Notes from digging:  we have this information on `Session.startNew().catch(err)` in `err.xhr.response`, we need to add a handler to `context.ts` and the console, and a UX to present this information.
