### ISSUE TITLE
Install jupyterLab-code-snippets Conflicting Dependencies

### ISSUE THREAD

**Issue by saber-project** [jupyterlab/jupyterlab#8993]
## My System Info

my system：ubuntu 18.04.3
my jupyter version:
      jupyter core : 4.6.1
      jupyter-notebook : 6.0.3
      qtconsole  : 4.6.0
      ipython   : 7.12.0
      ipykernel   : 5.1.4
      jupyter client  : 5.3.4
      jupyter lab  : 1.2.6
      nbconvert  : 5.6.1
      ipywidgets  : 7.5.1
      nbformat  : 5.0.4
      traitlets   : 4.3.3

## Operation Description and Error

1. Enter the anaconda environment ‘base’
2. Execute commands in the terminal
(base) sss@ubuntu:~/project$  jupyter labextension install jupyterlab-code-snippets
An error occured.
ValueError: No version of jupyterlab-code-snippets could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.

Conflicting Dependencies:
JupyterLab　　　　　Extension　　　　Package
'>=1.2.1 <1.3.0　　　>=2.1.2 <3.0.0　　 @jupyterlab/application'
'>=1.2.1 <1.3.0　　　>=2.2.4 <3.0.0　　 @jupyterlab/apputils'
'>=3.2.0 <3.3.0　　　>=4.1.0 <5.0.0　　 @jupyterlab/coreutils'
'>=1.2.1 <1.3.0　　　>=2.1.2 <3.0.0　　 @jupyterlab/docmanager'
'>=1.2.1 <1.3.0　　　>=2.1.2 <3.0.0　　 @jupyterlab/fileeditor'
'>=1.2.2 <1.3.0　　　>=2.1.2 <3.0.0　　 @jupyterlab/notebook'
'>=1.2.1 <1.3.0　　　>=2.1.1 <3.0.0　　 @jupyterlab/rendermime'
'>=4.2.0 <4.3.0　　　>=5.0.0 <6.0.0　　 @jupyterlab/services'
See the log file for details:  /tmp/jupyterlab-debug-85gm_yay.log

## Log File content
Yarn configuration loaded.
Node v12.16.2

'> /usr/bin/npm pack jupyterlab-code-snippets'

Fetching URL: https://registry.yarnpkg.com/jupyterlab-code-snippets
Fetching URL: https://registry.yarnpkg.com/jupyterlab-code-snippets
Traceback (most recent call last):

  File "/home/sss/anaconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/sss/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 93, in start
    ans = self.run_task()

  File "/home/sss/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/home/sss/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 149, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/home/sss/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 398, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/home/sss/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 611, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/home/sss/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 1549, in _install_extension
    raise ValueError(msg)

ValueError: No version of jupyterlab-code-snippets could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.

Conflicting Dependencies:
JupyterLab　　　　Extension　　　Package
'>=1.2.1 <1.3.0　　>=2.1.2 <3.0.0　@jupyterlab/application'
'>=1.2.1 <1.3.0　　>=2.2.4 <3.0.0　@jupyterlab/apputils'
'>=3.2.0 <3.3.0　　>=4.1.0 <5.0.0　@jupyterlab/coreutils'
'>=1.2.1 <1.3.0　　>=2.1.2 <3.0.0　@jupyterlab/docmanager'
'>=1.2.1 <1.3.0　　>=2.1.2 <3.0.0　@jupyterlab/fileeditor'
'>=1.2.2 <1.3.0　　>=2.1.2 <3.0.0　@jupyterlab/notebook'
'>=1.2.1 <1.3.0　　>=2.1.1 <3.0.0　@jupyterlab/rendermime'
'>=4.2.0 <4.3.0　　>=5.0.0 <6.0.0　@jupyterlab/services'

Exiting application: jupyter

**Comment by jahn96** [comment]
Hi, 
jupyterlab-code-snippets extension only works in JupyterLab version 2.0 or higher.

**Comment by jtpio** [comment]
Thanks @saber-project and @jahn96.

Closing as this is specific to the `jupyterlab-code-snippets` extension: https://github.com/jupytercalpoly/jupyterlab-code-snippets
