### ISSUE TITLE
Can not properly install JupyterLab debugger 

### ISSUE THREAD

**Issue by gassysoil** [jupyterlab/jupyterlab#8998]
Many thanks to Jeremy Tuloup @jtpio and other team members, we are able to use visual debugger for JupyterLab!

I am trying to install it on my mac, but without success yet. Therefore, I am turning to the community for some guidance. I am pretty new to computer/data science, any advice would be extremely helpful! 

Basically, I followed the steps listed in this post: https://github.com/jupyterlab/debugger

The entire installation seems fine (please refer to the screen recording I am attaching), but I could not find the xpython kernel when I log into JupyterLab.  Once in the JupyterLab, the "debugger" function seems not installed yet. 

Link to screen recording: 
https://drive.google.com/drive/folders/12x9yBzV12I8yCIKIQKfgP3EJAI3t8M69?usp=sharing

Let me know if there are any important steps that I missed, or it's related to other settings of my environment. Much appreciated!

Best, 
John

**Comment by jtpio** [comment]
Thanks @gassysoil for posting here, and thanks for the detailed screencast!

It looks like the JupyterLab launched via the Anaconda Navigator is different than the one from the `jupyterlab-debugger` environment.

Would it be possible to launch JupyterLab from the terminal to check the extension and kernel are installed correctly?

```
conda activate jupyterlab-debugger
jupyter lab
```

**Comment by gassysoil** [comment]
@jtpio Amazing, opening the lab using your way actually makes it work! 
Thanks very much, Jeremy!
John
