### ISSUE TITLE
load vendors~main.js slowly, spend 10~20 minutes

### ISSUE THREAD

**Issue by icankeep** [jupyterlab/jupyterlab#8999]
## Description

I start a server through the hub(jupyter labhub). Most of the time it is completely normal, but sometimes it takes a long time (10 to 20 minutes) to load the JS file when I enter the Lab Web page through the browser. I execute kill-9 labhub PID by entering the server machine, and then I can quickly enter lab. As shown in the figure below:

![image](https://user-images.githubusercontent.com/39434627/93057367-5a652600-f6a0-11ea-8b17-da1450b77b9f.png)

## Context

- Operating System and version: CentOS Linux release 7.6.1810 (Core) 
- Browser and version: Chrome 84.0.4147.125
- JupyterLab version: 2.2.4
- JupyterHub version: 1.0.0
- JupyterNotebook version: 5.7.8

**Comment by jasongrout** [comment]
This should be fixed in jlab 3.0, which splits up the javascript much more.
