### ISSUE TITLE
can you tell me how to set  linewrapping?  

### ISSUE THREAD

**Issue by YuanlongZhao** [jupyterlab/jupyterlab#9001]
I mean when code is long, I want the  linewrapping?

**Comment by cmaass** [comment]
Settings->Advanced Settings Editor->Notebook
Change 'User Preferences' to `{
    "codeCellConfig": {
        "lineWrap": "off"
    }
}`
However, since it's not a bug/missing feature, Stackoverflow would have been a better place to ask :)

**Comment by YuanlongZhao** [comment]
thank you so much!!!

**Comment by jtpio** [comment]
Closing as answered, thanks @cmaass!

**Comment by gloryVine** [comment]
> Settings->Advanced Settings Editor->Notebook
> Change 'User Preferences' to `{ "codeCellConfig": { "lineWrap": "off" } }`
> However, since it's not a bug/missing feature, Stackoverflow would have been an easier place to ask for help :)

This does not work for me. I get 

> [additional property error]
