### ISSUE TITLE
Could not install jupyterlab on Python 3.6.1

### ISSUE THREAD

**Issue by Beadsworth** [jupyterlab/jupyterlab#9006]
## Description

Cannot pip install to python 3.6.1

## Reproduce

1. Create venv with interpreter python 3.6.1
2. activate venv
3. pip install jupyterlab from wheel
4. get error: traitlets requires Python '>=3.7' but the running Python is 3.6.1

## Expected behavior

successful install of jupyterlab on python 3.6.1, PYPI page list python 3.5+ as requirement: https://pypi.org/project/jupyterlab/

## Context

- Operating System and version: Windows 7 Professional, 64 bit
- Browser and version: N/A
- JupyterLab version: 2.2.8

<details><summary>Command Line Output</summary>
<pre>
Looking in links: H:\Python\downloaded_wheels
Collecting jupyterlab
Collecting notebook>=4.3.1 (from jupyterlab)
Collecting tornado!=6.0.0,!=6.0.1,!=6.0.2 (from jupyterlab)
Collecting jupyterlab-server<2.0,>=1.1.5 (from jupyterlab)
Collecting jinja2>=2.10 (from jupyterlab)
Collecting ipython-genutils (from notebook>=4.3.1->jupyterlab)
Collecting jupyter-client>=5.3.4 (from notebook>=4.3.1->jupyterlab)
Collecting terminado>=0.8.3 (from notebook>=4.3.1->jupyterlab)
Collecting ipykernel (from notebook>=4.3.1->jupyterlab)
Collecting nbconvert (from notebook>=4.3.1->jupyterlab)
Collecting traitlets>=4.2.1 (from notebook>=4.3.1->jupyterlab)
traitlets requires Python '>=3.7' but the running Python is 3.6.1

</pre>
</details>

**Comment by Beadsworth** [comment]
Looks like traitlets dropped python 3.6 support in v5.0.0: https://traitlets.readthedocs.io/en/stable/changelog.html

**Comment by jasongrout** [comment]
That's unfortunate. Traitlets dropping support for 3.6 basically forces most of the Project Jupyter projects to drop support for 3.6.

**Comment by jasongrout** [comment]
Interesting, using conda to create an environment with python 3.6, but then still using pip to install, pip correctly determines that it needs to install traitlets 4.x instead of 5.x:

```
conda create -n testpy36 python=3.6
pip install --pre jupyterlab
```
installs JupyterLab 3.0b4 and traitlets 4.x.

Even without the `--pre`, I still get JLab 2.2.8 and traitlets 4.3.3.

I'm not very familiar with venv - can you give more explicit instructions, or perhaps someone like @ivanov can try to reproduce this?

**Comment by jasongrout** [comment]
And just to double-check, I downloaded the jlab 2.2.8 wheel and installed from it, and still pip picked up traitlets 4.3.3 instead of traitlets 5

**Comment by Beadsworth** [comment]
Hello @jasongrout,

When I have some time soon, I will try to write a more explicit description.

Please don't invest too much time into this issue yet -- it may very well be something on my end.  I am on an internet-free computer, which is why I'm trying to install from wheel.  I may also have Visual C++ 14 installs needed to fix other issue -- probably unrelated.

I was able to manually install an earlier version of traitlets, but haven't been able to finish other installs.

**Comment by jasongrout** [comment]
>  I am on an internet-free computer, which is why I'm trying to install from wheel.

Perhaps it's because your cache only has traitlets 5, then?

Okay, we'll wait for your further experiments.
