### ISSUE TITLE
Notebook Kernel in busy state is not connected correctly after refreshing the page

### ISSUE THREAD

**Issue by skukhtichev** [jupyterlab/jupyterlab#9010]
## Description
Notebook Kernel in busy state is not connected correctly after refreshing the page. After reloading the page kernel state is shown is idle and no messages are received in frontend. Interrupting the kernel execution prints error log in Browser's console (Chrome browser):
<img width="763" alt="Screenshot 2020-09-15 at 16 36 19" src="https://user-images.githubusercontent.com/12250108/93224720-b51a8280-f771-11ea-80eb-1915de6e40a1.png">
Reproducible with the latest stable JupyterLab 2.2.8 release

## Reproduce

1. Create a new notebook
2. Execute the following code:
```
while True:
    pass
```
3. While code is executing refresh the page
4. After Jupyter notebook is loaded kernel status is shown as `idle`
5. create new cell and execute any code
6. Kernel will be shown as `idle` and cell's execution status will be switched to `running`: `[*]`

## Expected behavior
After refreshing JupyterLab Notebook page with busy kernel Kernel should be shown as `busy` and all messages produced by the kernel should be registered in JupyterLab

## Context

- Operating System and version: MacOS 10.15.6
- Browser and version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
- JupyterLab version: 2.2.4 and 2.2.8

**Comment by karlaspuldaro** [comment]
Hi @skukhtichev 

I was still able to reproduce this in lab v3.0 branch with a related fix by #8432 
Upon reload the kernel status circle in the UI is being rendered as `idle`, but on a mouse over it says `Kernel Connecting`. Even after a new cell execution is indicated as running `[*]`.

In the classic notebook, the kernel status circle is rendered black, indicating the user it still busy after restart.
I guess we would expect that same behaviour here.
I can take a deeper look into that.

**Comment by jasongrout** [comment]
After #9172, the kernel indicator indicates the status is unknown when the page is refreshed after executing `while True: pass`, which correctly reflects what we know (the frontend has not got a status message from the kernel, so it does not know if it is busy or idle or whatever).

<img width="159" alt="Screen Shot 2020-10-17 at 3 33 30 AM" src="https://user-images.githubusercontent.com/192614/96334975-9259e300-1029-11eb-82f6-0e37a8b1a28b.png">

**Comment by jasongrout** [comment]
Fixed in #9172.
