### ISSUE TITLE
Jupyterlab UI is not coming up after jupyterlab build

### ISSUE THREAD

**Issue by aniket02k** [jupyterlab/jupyterlab#9037]
## Description

Hi,
I am trying to install labextensions on top of jupyterlab and building jupyterlab. After building jupyterlab, jupyterlab UI is not visible and observing some errors in browser console.

## Console Errors
![image](https://user-images.githubusercontent.com/24222712/93576117-1e8bd280-f9b8-11ea-8d71-16b2d6e1dd45.png)

## Jupyterlab UI

![image](https://user-images.githubusercontent.com/24222712/93576593-ad005400-f9b8-11ea-842a-b34c2039cafc.png)

## Reproduce

1. Install @jupyter-widgets/jupyterlab-manager extension
2. Build jupyterlab
3. Spawn Single user server

- Operating System and version: CentOs 7.6
- Browser and version: Google Chrome 85.0.4183.102 
- JupyterLab version: 2.2.1

**Comment by S664813266** [comment]
your CSS loser
