### ISSUE TITLE
Text editor settings not rendered in the dropdown menu

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab#9042]
## Description
The options for the text editor keymap and text editor theme are not rendering in the settings menu

![image](https://user-images.githubusercontent.com/10111092/93657896-7a7c4880-fa04-11ea-82d7-6f2d67b762a7.png)
![image](https://user-images.githubusercontent.com/10111092/93657910-9f70bb80-fa04-11ea-995a-a157bf7e0ed8.png)

All the other settings are rendering correctly for me. There are errors and warnings in the console (pasted below) but none seemed directly relevant

## Reproduce
```
conda create -n jlab3 python=3
pip install --pre --upgrade jupyterlab
```

## Context

- Operating System and version: PopOS 20.04
- Browser and version: Firefox 80.0.1
- JupyterLab version: 3.0.0b8

<details><summary>Troubleshoot Output</summary>
<pre>$PATH:
	/home/ian/.local/bin
	/home/ian/anaconda3/envs/jlab3/bin
	/home/ian/anaconda3/condabin
	/home/ian/.local/bin
	/home/ian/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin
	/home/ian/opt
	/home/ian/bin

sys.path:
	/home/ian/anaconda3/envs/jlab3/bin
	/home/ian/anaconda3/envs/jlab3/lib/python38.zip
	/home/ian/anaconda3/envs/jlab3/lib/python3.8
	/home/ian/anaconda3/envs/jlab3/lib/python3.8/lib-dynload
	/home/ian/anaconda3/envs/jlab3/lib/python3.8/site-packages

sys.executable:
	/home/ian/anaconda3/envs/jlab3/bin/python

sys.version:
	3.8.5 (default, Sep  4 2020, 07:30:14) 
	[GCC 7.3.0]

platform.platform():
	Linux-5.4.0-7642-generic-x86_64-with-glibc2.10

which -a jupyter:
	/home/ian/anaconda3/envs/jlab3/bin/jupyter

pip list:
	Package             Version
	------------------- -------------------
	argon2-cffi         20.1.0
	async-generator     1.10
	attrs               20.2.0
	Babel               2.8.0
	backcall            0.2.0
	bleach              3.2.1
	certifi             2020.6.20
	cffi                1.14.2
	chardet             3.0.4
	decorator           4.4.2
	defusedxml          0.7.0rc1
	entrypoints         0.3
	idna                2.10
	ipykernel           5.3.4
	ipython             7.18.1
	ipython-genutils    0.2.0
	jedi                0.17.2
	Jinja2              3.0.0a1
	json5               0.9.5
	jsonschema          3.2.0
	jupyter-client      6.1.7
	jupyter-core        4.6.3
	jupyter-server      1.0.1
	jupyterlab          3.0.0b8
	jupyterlab-pygments 0.1.1
	jupyterlab-server   2.0.0rc0
	MarkupSafe          2.0.0a1
	mistune             0.8.4
	nbclassic           0.2.0
	nbclient            0.5.0
	nbconvert           6.0.3
	nbformat            5.0.7
	nest-asyncio        1.4.0
	notebook            6.1.4
	packaging           20.4
	pandocfilters       1.4.2
	parso               0.7.1
	pexpect             4.8.0
	pickleshare         0.7.5
	pip                 20.2.2
	prometheus-client   0.8.0
	prompt-toolkit      3.0.7
	ptyprocess          0.6.0
	pycparser           2.20
	Pygments            2.7.1
	pyparsing           3.0.0a2
	pyrsistent          0.17.3
	python-dateutil     2.8.1
	pytz                2020.1
	pyzmq               19.0.2
	requests            2.24.0
	Send2Trash          1.6.0b1
	setuptools          49.6.0.post20200814
	six                 1.15.0
	terminado           0.9.0
	testpath            0.4.4
	tornado             6.0.4
	traitlets           5.0.4
	urllib3             1.25.10
	wcwidth             0.2.5
	webencodings        0.5.1
	wheel               0.35.1

conda list:
	# packages in environment at /home/ian/anaconda3/envs/jlab3:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                        main  
	argon2-cffi               20.1.0                   pypi_0    pypi
	async-generator           1.10                     pypi_0    pypi
	attrs                     20.2.0                   pypi_0    pypi
	babel                     2.8.0                    pypi_0    pypi
	backcall                  0.2.0                    pypi_0    pypi
	bleach                    3.2.1                    pypi_0    pypi
	ca-certificates           2020.7.22                     0  
	certifi                   2020.6.20                py38_0  
	cffi                      1.14.2                   pypi_0    pypi
	chardet                   3.0.4                    pypi_0    pypi
	decorator                 4.4.2                    pypi_0    pypi
	defusedxml                0.7.0rc1                 pypi_0    pypi
	entrypoints               0.3                      pypi_0    pypi
	idna                      2.10                     pypi_0    pypi
	ipykernel                 5.3.4                    pypi_0    pypi
	ipython                   7.18.1                   pypi_0    pypi
	ipython-genutils          0.2.0                    pypi_0    pypi
	jedi                      0.17.2                   pypi_0    pypi
	jinja2                    3.0.0a1                  pypi_0    pypi
	json5                     0.9.5                    pypi_0    pypi
	jsonschema                3.2.0                    pypi_0    pypi
	jupyter-client            6.1.7                    pypi_0    pypi
	jupyter-core              4.6.3                    pypi_0    pypi
	jupyter-server            1.0.1                    pypi_0    pypi
	jupyterlab                3.0.0b8                  pypi_0    pypi
	jupyterlab-pygments       0.1.1                    pypi_0    pypi
	jupyterlab-server         2.0.0rc0                 pypi_0    pypi
	ld_impl_linux-64          2.33.1               h53a641e_7  
	libedit                   3.1.20191231         h14c3975_1  
	libffi                    3.3                  he6710b0_2  
	libgcc-ng                 9.1.0                hdf63c60_0  
	libstdcxx-ng              9.1.0                hdf63c60_0  
	markupsafe                2.0.0a1                  pypi_0    pypi
	mistune                   0.8.4                    pypi_0    pypi
	nbclassic                 0.2.0                    pypi_0    pypi
	nbclient                  0.5.0                    pypi_0    pypi
	nbconvert                 6.0.3                    pypi_0    pypi
	nbformat                  5.0.7                    pypi_0    pypi
	ncurses                   6.2                  he6710b0_1  
	nest-asyncio              1.4.0                    pypi_0    pypi
	notebook                  6.1.4                    pypi_0    pypi
	openssl                   1.1.1g               h7b6447c_0  
	packaging                 20.4                     pypi_0    pypi
	pandocfilters             1.4.2                    pypi_0    pypi
	parso                     0.7.1                    pypi_0    pypi
	pexpect                   4.8.0                    pypi_0    pypi
	pickleshare               0.7.5                    pypi_0    pypi
	pip                       20.2.2                   py38_0  
	prometheus-client         0.8.0                    pypi_0    pypi
	prompt-toolkit            3.0.7                    pypi_0    pypi
	ptyprocess                0.6.0                    pypi_0    pypi
	pycparser                 2.20                     pypi_0    pypi
	pygments                  2.7.1                    pypi_0    pypi
	pyparsing                 3.0.0a2                  pypi_0    pypi
	pyrsistent                0.17.3                   pypi_0    pypi
	python                    3.8.5                h7579374_1  
	python-dateutil           2.8.1                    pypi_0    pypi
	pytz                      2020.1                   pypi_0    pypi
	pyzmq                     19.0.2                   pypi_0    pypi
	readline                  8.0                  h7b6447c_0  
	requests                  2.24.0                   pypi_0    pypi
	send2trash                1.6.0b1                  pypi_0    pypi
	setuptools                49.6.0                   py38_0  
	six                       1.15.0                   pypi_0    pypi
	sqlite                    3.33.0               h62c20be_0  
	terminado                 0.9.0                    pypi_0    pypi
	testpath                  0.4.4                    pypi_0    pypi
	tk                        8.6.10               hbc83047_0  
	tornado                   6.0.4                    pypi_0    pypi
	traitlets                 5.0.4                    pypi_0    pypi
	urllib3                   1.25.10                  pypi_0    pypi
	wcwidth                   0.2.5                    pypi_0    pypi
	webencodings              0.5.1                    pypi_0    pypi
	wheel                     0.35.1                     py_0  
	xz                        5.2.5                h7b6447c_0  
	zlib                      1.2.11               h7b6447c_3

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Unsatisfied version 16.13.1 of shared singleton module react (required ^15.5.4) main.0313e2382b40eec43bd6.js:1:29927
Some cookies are misusing the recommended “SameSite“ attribute 117
Ignored setting registry preload errors. 
(1) […]
​
0: Object { dataPath: "", keyword: "timeout", message: "Transforming @jupyterlab/shortcuts-extension:shortcuts timed out.", … }
​
length: 1
​
<prototype>: Array []
5281.5181b130c626ade47a87.js:2:4927
Ignored setting registry preload errors. 
(1) […]
​
0: Object { dataPath: "", keyword: "timeout", message: "Transforming @jupyterlab/docmanager-extension:plugin timed out.", … }
​
length: 1
​
<prototype>: Array []
5281.5181b130c626ade47a87.js:2:4927
Starting application in workspace: "default" 9000.6e9486dd090279600532.js:2:1727
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    ac http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    d http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    h http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Vi http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    qa http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Gu http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Uu http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Lu http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Pu http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    si http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    unstable_runWithPriority http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    ai http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    si http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    ci http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Tu http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    enqueueSetState http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    setState http://localhost:8890/static/lab/7294.b73e54424beb85970edd.js:2
    slot http://localhost:8890/static/lab/2218.9ee3a302b4947ed656b6.js:2
    v http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    u http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    emit http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    _emitTabsChanged http://localhost:8890/static/lab/9000.6e9486dd090279600532.js:2
    v http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    u http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    emit http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    _layoutDebouncer http://localhost:8890/static/lab/895.ed9a5676ba9ebeee054e.js:1
    factory http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    u http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    s http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    l http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    l http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    factory http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    _execute http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    s http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
3935.4c0b07dfcc7757b90057.js:2:85071
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    ac http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    d http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    h http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Vi http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    qa http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Gu http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Uu http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Lu http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Pu http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    si http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    unstable_runWithPriority http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    ai http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    si http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    ci http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    Tu http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    enqueueSetState http://localhost:8890/static/lab/3935.4c0b07dfcc7757b90057.js:2
    setState http://localhost:8890/static/lab/7294.b73e54424beb85970edd.js:2
    slot http://localhost:8890/static/lab/2218.9ee3a302b4947ed656b6.js:2
    v http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    u http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    emit http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    _emitTabsChanged http://localhost:8890/static/lab/9000.6e9486dd090279600532.js:2
    v http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    u http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    emit http://localhost:8890/static/lab/4016.1ec12a46e3e5dc138e78.js:1
    _layoutDebouncer http://localhost:8890/static/lab/895.ed9a5676ba9ebeee054e.js:1
    factory http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    u http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    s http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    l http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    l http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    factory http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    _execute http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
    s http://localhost:8890/static/lab/3114.24d1b1f50e8147a4d1d3.js:2
4016.1ec12a46e3e5dc138e78.js:1:953
Starting WebSocket: ws://localhost:8890/api/kernels/77898450-7f9a-4999-b873-3102b4109ac7 6240.c35b958c455f31f4ae75.js:1:18118
Starting WebSocket: ws://localhost:8890/api/kernels/43c71a74-6bc2-4ef9-b4ea-1c44c5c37d31 6240.c35b958c455f31f4ae75.js:1:18118
Starting WebSocket: ws://localhost:8890/api/kernels/43c71a74-6bc2-4ef9-b4ea-1c44c5c37d31
</pre>
</details>

**Comment by ianhi** [comment]
If I try to click on the editor keymap settings anyway I get this error in the console:
![image](https://user-images.githubusercontent.com/10111092/93658089-97b21680-fa06-11ea-9954-9d8342462849.png)
```
@jupyterlab/codemirror-extension:commands validation errors: 
(1) […]
​
0: Object { keyword: "type", dataPath: ".keyMap", schemaPath: "#/properties/keyMap/type", … }
​
length: 1
​
<prototype>: Array []
5281.5181b130c626ade47a87.js:2:5140
Failed to set @jupyterlab/codemirror-extension:commands:keyMap - @jupyterlab/codemirror-extension:commands failed to validate; check console. 9000.6e9486dd090279600532.js:2:34081

```

**Comment by ianhi** [comment]
and the user settings also get populated with the value incorrectly set as a list and with the values doubled:
```
    // Key Map
    // Configures the keymap to use
    "keyMap": [
        "vim",
        "vim"
    ]
```

**Comment by jasongrout** [comment]
CC @afshin
