### ISSUE TITLE
Lock down webpack version in builder if webpack is still prerelease

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9045]
Right now, we depend on a `~` range for webpack versions:

https://github.com/jupyterlab/jupyterlab/blob/2e10aae88634e496c1506176fbfaca7eeadf55f6/builder/package.json#L67

Since webpack is still beta, we risk them having a backwards-incompatible change before the final release. If we do a final release before webpack releases their final, we should lock that version of webpack to a specific version to guard against incompatible changes.

They have said their abi is pretty stable at this point, but sometimes they are still making small backwards-incompatible changes in the latest betas (such as https://github.com/webpack/webpack/pull/11495 in their latest beta 32).

We can always release a point release of jlab (or of the builder) that updates the webpack 5.0 final if there are no backwards-incompatible changes that affect us.

**Comment by jasongrout** [comment]
Hooray! webpack is now in RC for 5.0.

I think it probably still makes sense to pin, and then release a jlab 3.0.1 when they release their final

**Comment by bollwyvl** [comment]
rc4 just dropped this morning:

https://www.npmjs.com/package/webpack/v/5.0.0-rc.4

**Comment by jasongrout** [comment]
This is no longer necessary since Webpack 5 final was released today. Our upgrade is at #9148
