### ISSUE TITLE
Rename `Renderer` to `WidgetFactory` in JupyterLab

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#905]
Right now in JupyterLab we are using the `IRenderer` pattern from phosphor, but in an overly zealous way. The original pattern was meant to allow a pluggable way for phosphor widgets to render children DOM nodes. However, we have started to use this same name as a widget factory. We should rename these examples using a more appropriate name such as `NotebookWidgetFactory`.

**Comment by blink1073** [comment]
I'd prefer `CellFactory` since we use `WidgetFactory` in the `DocumentRegistry`.

**Comment by ellisonbg** [comment]
Yes, being more specific is definitely better.
