### ISSUE TITLE
Single Document Mode menu bar styling

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9065]
### Problem

As mentioned by @bollwyvl in #9044, the styling of the menu bar in current master looks really odd in single document mode. Notice that when you have a menu open especially, not having a top border looks incomplete (to me):
<img width="513" alt="Screen Shot 2020-09-23 at 4 31 40 PM" src="https://user-images.githubusercontent.com/192614/94084506-8ed09480-fdba-11ea-9372-9b7385ccd841.png">

### Proposed Solution

Add a top border to the menu bar? That seems like maybe a busy solution - not sure what to do here. Perhaps move the document title below the menu bar? It does seem odd that the menu bar is below the document title, in that you can switch documents and create new documents from the menu.

CC @ellisonbg

**Comment by jasongrout** [comment]
Perhaps the activity title should be over on the *left* of the menu bar when in single document mode? That way you don't have so much space taken up by two lines. Something like 
<img width="683" alt="Screen Shot 2020-09-23 at 4 42 28 PM" src="https://user-images.githubusercontent.com/192614/94085006-cbe95680-fdbb-11ea-9d5f-1c4538cab0f9.png">

In fact, that title can double as a document switcher, or perhaps double-clicking on it lets you rename the file, like @bollwyvl suggested. Or perhaps right-clicking on it gives you the menu you get when you right-click on the corresponding tab.

**Comment by jasongrout** [comment]
@ellisonbg and I were brainstorming more about the UX for switching to/from single document mode, and one idea that seemed appealing was a toggle slider over on the right side of the menu bar. Then it is easily accessible, discoverable, and that might be an ideal place to put the title, next to the thing that toggles single-document mode.

**Comment by ellisonbg** [comment]
I believe that users have a set of things they are looking for in prototypical document oriented interfaces and that the single document mode in JupyterLab didn't closely follow that pattern, so was viewed as not document oriented. Some of those things:

1. Document title in primary position above the menu bar.
2. Each document in a separate page.
3. Toolbar below the menu bar.
4. Lightweight feeling to the L panel.
5. No gaps in the layout.

I can't think of any application that is document oriented in this way that doesn't have (1) which is why I put the menu at the top. In terms of the top border, I think that segment should have a similar styling as the rest of the menu, which I think is a subtle border and drop shadow.

**Comment by jasongrout** [comment]
I realize that I wasn't engaged earlier in the ux conversations, so it's not the time to rehash big UX decisions.

I think some tweaks could make it feel more unified and intentional:

1. The empty space to the left of the menu and above the menu feels, I don't know, disorienting? I think adding the top border like the rest of the menu would make a big difference for above the menu. For the left, perhaps moving the menu bar all the way to the left edge would help?
2. The font size (and is it bolder?) for the name feels a bit out of place so close to the menu font size. Or maybe it's the actual font used? It feels a bit like the font sizes are close enough that they end up clashing to me.

**Comment by jasongrout** [comment]
As an example, here's Google Docs:
<img width="463" alt="Screen Shot 2020-09-24 at 4 02 56 PM" src="https://user-images.githubusercontent.com/192614/94208781-80987c00-fe7f-11ea-8022-bd7a78667023.png">

Notice how the icon fills in that empty space to the left of the menu? To me, that is another way to take care of that awkward empty space to the left of the menu below the Jupyter icon. In fact, we could just use the icon for the tab, which indicates what kind of file or activity we are dealing with.

**Comment by jasongrout** [comment]
For reference, here is what Google Docs does for an open menu below the doc title:
<img width="361" alt="Screen Shot 2020-09-28 at 2 11 27 PM" src="https://user-images.githubusercontent.com/192614/94486675-9e722380-0194-11eb-8ff2-49f8763153a9.png">
