### ISSUE TITLE
Terminal token authentication broken

### ISSUE THREAD

**Issue by languy** [jupyterlab/jupyterlab#9070]
## Description
When configuring jupyter server with token authentication, the terminal fails to connect.
It appears that the latest service/terminal code ignores the `token` field passed in `ServerConnection.ISettings` when establishing the websocket connection.

The url should look like: `wss://__my_hostname__/notebook/terminals/websocket/1?token=__my_token__`
but is missing the `?token=__my_token__` part.

I believe the faulty code is in [service/terminal/default.ts](https://github.com/jupyterlab/jupyterlab/blob/2bade97edadea865b294eb49c8d693d4261ca404/packages/services/src/terminal/default.ts#L261). The url is constructed without the token parameter (if specified), right before establishing the websocket connection.

The package `@jupyterlab/services@4.2.0` used to work and properly form the url with the token in the query parameters, but I believe the latest refactoring from `TerminalSession` to `TerminalManager` broke it.

## Reproduce
1. Configure jupyter server to use token authentication
2. Open new terminal using `@jupyterlab/services@5.2.4` and `@jupyterlab/services@2.2.3`.

An error appears in the console:
```
WebSocket connection to 'wss://__hostname__/notebook/terminals/websocket/1' failed: HTTP Authentication failed; no valid credentials available
```
Notice the token missing in the url parameters.

## Expected behavior
Terminal connects to jupyter server and a prompt appears.

## Context

- Operating System and version: Windows 10
- Browser and version: MS Edge 85.0.564.51 (Chromium version)
- JupyterLab version: @jupyterlab/services@5.2.4

**Comment by languy** [comment]
I'm submitting a patch for this: #9080 .

**Comment by jcleyba** [comment]
@languy 
The code introduced in your PR is almost identical to the one removed in this commit: 

https://github.com/jupyterlab/jupyterlab/commit/e58660c11a6eed62fcb788b823dc9b36886bf21c#diff-326d12d41a9e5bac8f0f5572beb988f3

I don't understand why this was removed from all of the websocket connection handlers (kernel/default.ts for example) and this is causing problems to connect to websockets using the services library. 
Updating to 5.2.4 caused this websocket failure for me throwing a 403 error.

**Comment by jasongrout** [comment]
For reference, the code was removed in https://github.com/jupyterlab/jupyterlab/pull/8835, fixing https://github.com/jupyterlab/jupyterlab/issues/8813

#8813 claims it is a security issue to have the token in the url. Can you comment on that?

**Comment by languy** [comment]
Thanks for being so responsive with this PR! I didn't realize the code had been there, but removed.

#8813 makes two valid points:
1) we would be leaking the token in the URL and any 3rd-party sitting between the client and the server could see it (browser history, bookmarks, router, logs). Since the token doesn't change, someone looking at the network traffic logs for example, could reuse the url and successfully authenticate.
2) It is somewhat mitigated, because it is not a user-facing URL.

There are better ways to authenticate:
* pass credentials via initial http request header (the http request that establishes the websocket connection). I've never seen it done, but don't see why it can't be possible.
* authenticate inside the client-server (encrypted) traffic after the websocket connection is established (e.g. servers sends challenge message, client responds with creds/token, then conversation happens). That's the better alternative I've seen, but not without downsides (establishing websocket connection is expensive, client error handling (when server breaks connection in the middle of conversation), cleanup to name a few).

I would argue that it doesn't matter anyway, unless the jupyter server supports other means of authentication (than token-in-url). Jupyterlab is the client and should support whatever the server allows even if its security is weak. Simply removing the token from the url disables the client's ability to authenticate, but doesn't solve the security problem. In fact, any websocket traffic uses the same authentication, so the kernel communication should also already be implementing this token-in-url method and suffer from the same security issue.

Lastly, when I start the jupyter server, I have the option to open the notebook webpage with a token in the URL: that would be a similar leak, but with a user-facing url.
So I believe, token authentication in jupyter in general is weak, but should be supported by the client at the user's risk.

**Comment by jcleyba** [comment]
@languy Agree about the security point. If the user has selected token based authentication, the token is still exposed in request headers. 
Unfortunately I don't know enough about how Jupyter authenticates websockets but without the token, **I think** the only way to verify credentials is via cookies and if using cookies is a problem -as it is in my use case- the latest version of the library is not useful.
@jasongrout Any comments or ideas?

**Comment by minrk** [comment]
> pass credentials via initial http request header (the http request that establishes the websocket connection). I've never seen it done, but don't see why it can't be possible.

Passing http headers with websocket requests [is not possible in javascript](https://stackoverflow.com/a/4361358/938949). So the only options for authenticating websocket connections without accepting them are in the URL and with cookies. Since cookies don't work for cross-host requests (e.g. a page from one host getting kernels from another, such as mybinder.org with thebe), cookies cannot be relied upon in general. The only truly general options are:

- in URL params, or
- accept all unauthenticated connections and negotiate auth via handshake messages
