### ISSUE TITLE
command palette behavior on refocus

### ISSUE THREAD

**Issue by ivanov** [jupyterlab/jupyterlab#908]
We have currently gone down the path that Sublime/Atom take on focusing the command palette - which is that the previously typed command stays there.

Microsoft VS:Code has the opposite behavior - every invocation starts off listing all of the commands.

We can evaluate which of these make the most sense as a default.

We will want to make behavior toggle-able and persist it to the the user settings.

**Comment by sccolbert** [comment]
I'm :+1: on a general consensus of "what to do" here, but I think I'm :-1: on making it configurable (YAGNI principle). We "just picked" when deciding on the original behavior, which may have been the wrong pick. In any case, we'll need to update Phosphor for this.

**Comment by ellisonbg** [comment]
I am in favor of resetting state of the command palette on each invocation, but opposed to making this configurable by users. We keep going back and forth on the default behavior. Do folks mind if I call this one?

**Comment by sccolbert** [comment]
I think I slightly leaning towards resetting as well, which I think is enough consensus at this point. I think we can close this and open an issue on Phosphor. It's a pretty simple fix.

**Comment by ivanov** [comment]
Hang on - we're discussing this at the lab meeting, and @afshin  and I are both leaning the other way.

**Comment by jasongrout** [comment]
I'm +1 on trying out resetting the command palette after a command is executed for a while, and get more experience in it. I think we should also make the filtering interaction much better, like having an easy way to recall previous filters (Ctrl+P/Ctrl+N?), create new pre-filtered command palettes (all commands in the notebook category?), and perhaps more filtering criteria than just command?

Also, +1 on the idea of having an explicit `redo last command`, perhaps with a keybinding, so it's easy to execute something like 'increase font size' over and over agaon.

**Comment by sccolbert** [comment]
> I think we should also make the filtering interaction much better, like having an easy way to recall previous filters (Ctrl+P/Ctrl+N?)

:-1: on that. It's just as easy to type a few characters to filter.

> Also, +1 on the idea of having an explicit redo last command command, perhaps with a keybinding, so it's easy to execute something like 'increase font size' over and over agaon.

Why not just a specific key-binding to increase font size?

The command palette is for discoverability. I imagine most will use the key bindings once learned.

>  and perhaps more filtering criteria

also :-1: That is making things *way* more complex for what my gut tells me would be a little-used feature. I would definitely want to see more data points showing an actual need for this, before implementing it.

**Comment by jasongrout** [comment]
> 👎 on that. It's just as easy to type a few characters to filter.

if it's a few characters. If it's a few words, it gets a lot more tedious.

> Why not just a specific key-binding to increase font size?

Sure, that's great too. That still doesn't help when you have a command that's not used real often, but does need to be used several times in a row (for example, for several different documents). It's still useful to have a keybinding for the last executed command from the command palette.

> 
> The command palette is for discoverability. I imagine most will use the key bindings once learned.

I highly doubt that most people will learn enough keyboard shortcuts that improvements to the command palette to aid a workflow aren't necessary. I think the vast majority of people probably use menus and other 'discovery' mechanisms to execute commands in other applications, and will probably use similar mechanisms (including the command palette) in JLab.


> and perhaps more filtering criteria
> also 👎 That is making things way more complex for what my gut tells me would be a little-used feature. I would definitely want to see more data points showing an actual need for this, before implementing it.

I definitely agree that we don't have enough experience in knowing how users will work with JLab to try to design something like this now.

**Comment by sccolbert** [comment]
> It's still useful to have a keybinding for the last executed command from the command palette.

Sounds like you want history support, like you get with a console/terminal bound to the up/down arrow keys.

**Comment by jasongrout** [comment]
> Sounds like you want history support, like you get with a console/terminal bound to the up/down arrow keys.

Yes, exactly, but as was brought up in the jlab dev meeting, up/down is already taken to navigate the command palette command list.

**Comment by jasongrout** [comment]
> Yes, exactly, but as was brought up in the jlab dev meeting, up/down is already taken to navigate the command palette command list.

Sorry, there are two things here: (a) recalling a previous filter for the command palette easily, which is command palette history support, and (b) having a quick "redo" command, probably bound to a keyboard shortcut, which is more about executing a single command multiple times.

**Comment by afshin** [comment]
@ivanov, I don't feel strongly about leaving the previous text in, I do have a slight preference for that, but I'm happy for @ellisonbg to make the call to clear the state.

I think our other discussions in this thread are orthogonal and can be dealt with as a separate feature request / issue.

**Comment by blink1073** [comment]
This is fixed in master, as it is the new behavior of the phosphor command palette.
