### ISSUE TITLE
Jupyter Notebook not linking with JupyterLab

### ISSUE THREAD

**Issue by jgreenwo34** [jupyterlab/jupyterlab#9081]
files created in Jupyter Notebook are _NOT_ opening in JupyterLab....please help!.....__

**Comment by afonit** [comment]
@jgreenwo34 , do you have an example notebook you can upload somewhere?
Can you post the errors you are seeing?

**Comment by jgreenwo34** [comment]
Please ignore this message.....
thanks......


Sent from Yahoo Mail for iPhone


On Tuesday, September 29, 2020, 8:57 AM, afonit <notifications@github.com> wrote:




@jgreenwo34 , do you have an example notebook you can upload somewhere?
Can you post the errors you are seeing?

**Comment by jasongrout** [comment]
@afonit - thanks for trying to help here.

Closing per @jgreenwo34's request.
