### ISSUE TITLE
Cycle completion with tab and automatically insert parenthesis

### ISSUE THREAD

**Issue by quantum-booty** [jupyterlab/jupyterlab#9082]
Currently the tab triggers the completion, then I would have to go reach for the arrow keys to cycle through the  options. It would be much more convenient of I could cycle the options with tab and shift tab.
I would also very convenient if completion inserts parenthesis when I hit enter.

**Comment by joelostblom** [comment]
I would also really like to see tab cycling, at least as an option. This has also been requested here https://github.com/jupyterlab/jupyterlab/issues/5863

**Comment by cameron-toy** [comment]
I think this a great issue and something I'd love to work on! Seems like a feature that should have been included for a while. I also like the idea of making cycling optional as suggested in #5863

**Comment by joelostblom** [comment]
@quantum-booty I believe you can close this since PR #10147 was merged recently (I think the functionality will be available in 3.1). Thank you so much creating the PR @cameron-toy, it will be much nicer to switch between JL and shells now that tab works the same in both =)
