### ISSUE TITLE
Expand width of docstring pop up to accomodate commonly used docstring widths

### ISSUE THREAD

**Issue by joelostblom** [jupyterlab/jupyterlab#9085]
The docstring pop up (Shift + Tab) currently wraps lines that are over 75 characters. Many libraries have docstrings that are just a bit longer than this. I believe the common longer lengths include 77, 80, and 82, and I wonder if you would consider changing the default width to wrap at 83 characters instead to avoid line spillover which makes the doscstring hard to read, see screenshots below

Current behavior:
![image](https://user-images.githubusercontent.com/4560057/69971234-de8a5a80-151f-11ea-9360-98300bc68dcf.png)

Suggested behavior:
![image](https://user-images.githubusercontent.com/4560057/69971262-e77b2c00-151f-11ea-88e5-9767cf88750d.png)

I did this [change in the plotly](https://github.com/plotly/plotly.py/pull/1939) source earlier and just [suggested it to Altair](https://github.com/altair-viz/altair/issues/2300), but I figured it would be easier if JupyterLab (and maybe IPython) could increase the width just slightly instead of me trying to fix one library at a time. Docstrings following the pep8 72 char recommendation would still look good, just have a bit extra space on the side.

I can make this change if someone can point me to where in the code I need to change something, but I am also happy for someone else to do it since I imagine it is just tweaking a number for the width of the popup.

**Comment by jasongrout** [comment]
Without investigating too much, my guess is that this is the relevant line: https://github.com/jupyterlab/jupyterlab/blob/8eba49bbb3981fefd16c55f70fb03e6bc03855ad/packages/tooltip/style/base.css#L11

**Comment by joelostblom** [comment]
Thanks @jasongrout ! You are correct and I opened this PR with the change https://github.com/jupyterlab/jupyterlab/pull/9134.
