### ISSUE TITLE
Single Document Mode: disable the splash screen animation?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9099]
### Problem

Using JupyterLab 3.0.0rc1.

Double clicking on a file in the file browser to open a document opens a new browser tab, and triggers the splash screen animation.

![sdm-splashscreen](https://user-images.githubusercontent.com/591645/94573972-ebc4c280-0272-11eb-8017-302de47921d9.gif)

### Proposed Solution

It might feel a bit more natural to disable the splash screen when SDM is enabled, as one could expect the splash screen to show only once when lab is started.

**Comment by jasongrout** [comment]
Oh wow, is it really supposed to open a new browser window, rather than just switch to that document in the same browser window? I would have expected it to open the document in the same browser window.

@ellisonbg?

**Comment by jasongrout** [comment]
The splash screen animation is an important part of the app startup process, showing a nice interface while everything is coming online. It's not (or should not be) just for show, or take more time than necessary.

**Comment by jasongrout** [comment]
I have noticed recently that the splash screen seems to restart halfway through, i.e., the animation resets to the beginning halfway through. That does seem odd.

**Comment by jtpio** [comment]
> is it really supposed to open a new browser window, rather than just switch to that document in the same browser window?

Opening in a new browser tab just like the classic notebook I think.

**Comment by jtpio** [comment]
But "Right Click > Open" opens in the same tab (same as drag & drop):

![sdm-open](https://user-images.githubusercontent.com/591645/94608473-bf726b80-029d-11eb-9070-da5217831c5f.gif)

**Comment by telamonian** [comment]
> But "Right Click > Open" opens in the same tab (same as drag & drop):

It would be nice to finally fix the fact that double-click-open and command-open don't use the same code path:

https://github.com/jupyterlab/jupyterlab/blob/0aab1cd03756d4c9ed3df5ce774382f68e5ff131/packages/filebrowser/src/listing.ts#L968-L986

https://github.com/jupyterlab/jupyterlab/blob/0aab1cd03756d4c9ed3df5ce774382f68e5ff131/packages/filebrowser-extension/src/index.ts#L647-L672

but I suppose first we have to pick a behavior. Maybe we would want to explicitly add a new "open in new browser tab" command/menu item for single document mode?

**Comment by jasongrout** [comment]
To answer the OP question, the splash screen is an integral part of launching a new jlab.

As for whether opening a new jlab is a good idea, and the consistency with right-click open - let's take that in consideration with the rest of the feedback we are collecting in #9117 for 3.1.

**Comment by jtpio** [comment]
> but I suppose first we have to pick a behavior

Maybe the double click event and pressing the enter key should also use the `docmanager:open` command?
