### ISSUE TITLE
Variable inspection in the debugger sidebar

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/jupyterlab#9114]
Asking the variables with the sequence of `StackTrace`, `Scopes` and `Variables` requests does not work if execution did not stop on a breakpoint.

A solution to this would be to add a command in the protocol, let's say `inspectVariables`, that would make the interpreter execute `globals` and return its result.

**Comment by krassowski** [comment]
Closing as implemented in #10025 and released in 3.1. Please correct me if I am wrong here.

**Comment by JohanMabille** [comment]
Please notice the backend has been improved to return an array of `IVariable` when receiving an `inspectVariable` request. This way the behavior is consistent with the `variables` request and no further change is required in the frontend.

See https://github.com/ipython/ipykernel/pull/753
