### ISSUE TITLE
Watch mode for non-federated third-party extensions

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9116]
## Description

Follow-up to https://github.com/jupyterlab/jupyterlab/pull/9101 and https://github.com/jupyterlab/jupyterlab/issues/9089

Running `jupyter lab --no-browser --watch` doesn't seem to pick up changes when the extension is built. 

## Reproduce

Create a new environment and install lab with `python -m pip install --pre jupyterlab`.

Tested while updating the `@jupyter-voila/jupyterlab-preview` extension to support 3.0, but without switching to the new structure (yet): https://github.com/voila-dashboards/voila/pull/732

The extension seems to be picked up and linked correctly though:

```
JupyterLab v3.0.0rc2
Other labextensions (built into JupyterLab)
   app dir: /path/to/miniconda/envs/voila/share/jupyter/lab
        @jupyter-voila/jupyterlab-preview v1.1.0 enabled OK*


   local extensions:
        @jupyter-voila/jupyterlab-preview: /path/to/git/voila/packages/jupyterlab-voila

```

## Context

JupyterLab 3.0.0rc2

**Comment by jtpio** [comment]
With the build command being the one from the 2.0 cookiecutter (running `tsc`):

https://github.com/jupyterlab/extension-cookiecutter-ts/blob/cb9ca8c37bf1c5c28be61b31e6fcd0cf60487a5f/%7B%7Bcookiecutter.extension_name%7D%7D/package.json#L30

**Comment by telamonian** [comment]
The easy fix will be to just do a union regex. This will need some testing, but then I'll open a PR:

```python
WEBPACK_EXPECT = re.compile(r'(?:.*/index.out.js)|(?:.*theme-light-extension/style/index.css)')
```
