### ISSUE TITLE
Add a migration guide from 2.x to 3.x for extension authors

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9118]
As discussed during today's call, we can add a new migration guide to the main documentation.

The guide would live next to the existing `1.x -> 2.x` one: https://jupyterlab.readthedocs.io/en/latest/developer/extension_migration.html

And would mention the use of the upgrade script:

```bash
python -m jupyterlab.upgrade_extension .
```

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterlab-3-0-release-candidate-available/6248/5
