### ISSUE TITLE
Modal command palette doesn't respond to mouse clicks on a command

### ISSUE THREAD

**Issue by nmichaud** [jupyterlab/jupyterlab#9121]
The modal command palette doesn't let you select commands using the mouse (the click event seems to be ignored).

## Reproduce

1. Bring up modal command palette (Cmd-Shift-C)
2. Click on first option ("New Console" in my case)
3. Nothing happens and command palette is closed

## Expected behavior

Command is executed

## Context

- Operating System and version: OS X 10.12
- Browser and version: Chrome 85.0.4183.121
- JupyterLab version: 3.0.0rc2

**Comment by ellisonbg** [comment]
Ohh, good catch!

**Comment by jasongrout** [comment]
Fixed in #9210
