### ISSUE TITLE
Federated extensions can't add CodeMirror addons directly

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab#9124]
## Description
In a downstream federated 3.0 extension, addons to CodeMirror don't "stick" to the one provided by `ICodeMirror` (#9067) when used as shown in the codemirror documentation, which relies on an "extend by import" model. While rare, it's not unique, so this may be indicative of some larger issue.

It is appears to sometimes be _possible_ to work around this with some [poorly-typed tricks](https://github.com/jupyterlab/jupyterlab/issues/9044#issuecomment-702478898), reproduced (ha) below.

## Reproduce

```ts
import * as simpleMode from 'codemirror/addon/mode/simple';
import * as MyCodeMirror from 'codemirror';

export function defineSomeMode(TheCodeMirror: any) {
  console.warn(MyCodeMirror.modeInfo); // usually 156
  console.warn(TheCodeMirror.modeInfo); // usually 158, because ipython(gfm)
  TheCodeMirror.simpleMode = (MyCodeMirror as any).simpleMode.bind(TheCodeMirror);
  TheCodeMirror.defineMode(MODE_NAME, function(config: any) {
    return (MyCodeMirror as any).simpleMode.apply(TheCodeMirror, [config, STATES]);
  });
  TheCodeMirror.defineMIME(t, MODE_NAME);
  TheCodeMirror.modeInfo.push({
    ext: EXTENSIONS,
    mime: MIME_TYPE,
    mode: MODE_NAME,
    name: MODE_NAME
  });
}
```

> A poor workaround for _the particular_ example is on #9123

## Expected behavior

There should be a way, preferably close to the codemirror docs, to use addons, etc. for codemirror. The solution _might_ need to be generalized to more cases that make heavy use of library-level static values with side-effects... none in particular come to mind.

## Context
Extracted from #9044 while investigating [migrating](https://github.com/deathbeds/lintotype) [some](https://github.com/deathbeds/jupyterlab-simple-syntax) [extensions](https://github.com/deathbeds/jupyterlab_graphviz) to Lab 3.0 that use CodeMirror addons.

**Comment by ianhi** [comment]
This is also an issue for keymaps (in particular because vim is lazy-loaded) and I think will make it really tricky/impossible for multiple vim extensions to coexist.

**Comment by ianhi** [comment]
Is there an example of how to use CodeMirrorSingleton? I'm trying to update the `jupyterlab-vim` extension to 3.0 but running into all sorts of trouble around this. 

Based on the above example I think the correct approach is to do something like this:
I'm trying to use the new CodeMirrorSingleton so I can do something like

```typescript
import CodeMirrorSingleton from '@jupyterlab/codemirror-extension';

...

TheCodeMirror = CodeMirrorSingleton
TheCodeMirror.addKeymap(myCodeMirror.Vim)
```
but I'm getting this error:
```
Error: Shared module @jupyterlab/codemirror-extension doesn't exist in shared scope default
```

any advice on how to get around this would be greatly appreciated.

**Comment by ianhi** [comment]
If this remains tricky a workaround that would make jupyterlab-vim work would be to not lazy-load the vim keymap:
https://github.com/jupyterlab/jupyterlab/blob/0bec95d5364986eaf19dab4721a98c75f13db40f/packages/codemirror/src/editor.ts#L55-L57

**Comment by jasongrout** [comment]
> Is there an example of how to use CodeMirrorSingleton?

The codemirror singleton is for calling the static global codemirror functions, not for calling editor-specific functions like addKeymap (IIRC, addKeymap is for an instance, not a global static function).

If you wanted to use a global static function (like `defineMode`), you get it from the dependency injection framework, not by importing it. Something like (totally not tested, just off the top of my head).

```typescript

import ICodeMirror from '@jupyterlab/codemirror';



const myplugin: JupyterFrontEndPlugin<void> = {
  id: 'mypluginid',
  requires: [ICodeMirror],
  activate: activatemyplugin
};

 function activatemyplugin(app: JupyterFrontEnd, codemirror: ICodeMirror): void { 
    codemirror.CodeMirror.addKeymap(...);
}
```

**Comment by ianhi** [comment]
@jasongrout that was helpful thanks, I was definitely approaching the import incorrectly.

However, even with that I still am unable to get vim in the notebook working.
```typescript
    (jCodeMirror.CodeMirror as any).Vim = (CodeMirror as any).Vim;
```
still results in an error when I try to set a fileeditor or cell to use the vim keymap.  I think this because the vim setup does something at the start (That I definitely don't understand) to grab a reference to a global codemirror
https://github.com/codemirror/CodeMirror/blob/55d0333907117c9231ffdf555ae8824705993bbb/keymap/vim.js#L37-L44
and then uses that throughout the vim setup. 

I don't think that theres an easy way for me to have the jlab codemirror be used by the vim keymap file, though I'm happy to be wrong on that one. In the absence of some javascript trickery, I think one of the following will need to happen to allow the vim extension(s) to work with 3.0
1. jlab always imports vim keymap
2. ICodeMirror provides an `ensureVimKeymap` function that extensions can call.

The evidence that these would fix it is that the sublime keymap is not lazily-loaded and I'm able to get that working without errors.

**Comment by bollwyvl** [comment]
Sorry, hadn't been tracking this harder... the way codemirror does its extend-by-import business is indeed going to make this very tricky with recursive deps. i cheated with simplemode, as it is very small, but vim starts packing a huge punch that is difficult to justify for every user page load.

we may need a semi-automated way to expose _all_ of the addons as lazy imports... e.g. 
```ts
/* this file is generated */

export const _CodeMirrorAddons = {
  {% for addon in addons %}
  {{ addon.mangled_name }}: () => await import('codemirror/{{ addon.path }}')
  {% endfor %}
}
```

@jasongrout i haven't dug into the way singletons are declared in the federated build, but would making codemirror one of them avoid all these hacks?

**Comment by bollwyvl** [comment]
also, once the next rc drops, i will start https://github.com/jupyterlab/extension-examples/issues/129 so at least we'll have a place to start...

**Comment by ianhi** [comment]
Does it make sense to add this to the `3.0` milestone so it gets looked at again before the final release? Currently it seems that there is no way for the `jupyterlab-vim` extension to work on 3.0 which for me at least would be a pretty significant regression.

**Comment by jtpio** [comment]
> also, once the next rc drops, i will start jupyterlab/extension-examples#129 so at least we'll have a place to start...

Thanks @bollwyvl!

3.0.0rc5 was released today, if you want to give it a try.

**Comment by ianhi** [comment]
re vim things I was misunderstanding the difference between federated and non-federated (is there a definition of federated out there on the internet?). My new understanding is that non-federated extensions are still allowed and will be able to add modes and keymaps - so this is not as crucial for vim as I thought: https://github.com/jupyterlab/jupyterlab/pull/9161#issuecomment-713732536. people will just need to endure the occasional build step a bit longer

**Comment by jasongrout** [comment]
Bumping to 3.1 since this hasn't seen any more activity.

**Comment by afshin** [comment]
@bollwyvl Could you please check to see if this issue has been resolved?

**Comment by bollwyvl** [comment]
I haven't had a chance to get back to this.

Probably the only way to be _sure_ would be a `sharedPackages` CodeMirror singleton...
