### ISSUE TITLE
Installing on Ubuntu 18 works, installing on Ubuntu 20 failes

### ISSUE THREAD

**Issue by adamgit** [jupyterlab/jupyterlab#9127]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by agoose77** [comment]
You need to report more information than this, otherwise the team can do very little to debug the issue.

**Comment by adamgit** [comment]
I did not submit this issue - this is a bug in the Github Issues system. This fake issue should be deleted (would be nice if GH would fix the bug too). I don't know what the backend cause is, but it appears that hitting "edit" on an issue's title can cause a new duplicate issue to be created - that's all I did (and normally hitting Edit keeps the issue number. I have no idea why in this case it created a second one!)

You can see what I actually wrote here: https://github.com/jupyterlab/jupyterlab/issues/9128
