### ISSUE TITLE
Make the mktemp command OS agnostic

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9132]
Follow-up to https://github.com/jupyterlab/jupyterlab/pull/9130 and https://github.com/jupyterlab/jupyterlab/pull/9131

We could switch to Python instead for the `mktemp` command hereL  

Here:

https://github.com/jupyterlab/jupyterlab/blob/14776bb75832c0a474933dc46aba67cda16ced9e/scripts/release_prep.sh#L9

and here:

https://github.com/jupyterlab/jupyterlab/blob/14776bb75832c0a474933dc46aba67cda16ced9e/scripts/release_test.sh#L11

To avoid differences between operating systems and shells.

**Comment by jasongrout** [comment]
Just curious, what was the problem you were seeing? I usually release on macOS - were you using something different?

**Comment by jasongrout** [comment]
Ah, I missed your statement at https://github.com/jupyterlab/jupyterlab/pull/9130#issue-497115841:

> This command would otherwise fail on Ubuntu with zsh:

**Comment by jtpio** [comment]
> Just curious, what was the problem you were seeing? I usually release on macOS - were you using something different?

Yes and Ubuntu 20.04 with `zsh`.

This:

```
mktemp: too few X's in template ‘foo’
```


![image](https://user-images.githubusercontent.com/591645/94969982-f34eca80-0503-11eb-818d-20d615cc9e50.png)

**Comment by agoose77** [comment]
This might be stupid, but is the name itself important? Can we just append `XXXXXX` to the test dir pattern, and increase the release dir X count to 6?

**Comment by jtpio** [comment]
Yes maybe we are good to go for now by just adding extra Xs, so it's fine on both MacOS and Linux.

Not sure what would happen on Windows but maybe no-one cuts releases from Windows.

**Comment by jtpio** [comment]
Closing as this should not be relevant anymore when using the Jupyter Releaser to make releases.
