### ISSUE TITLE
Activate the debugger sidebar when debugging is enabled

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9144]
## Description

At the moment, turning the debugger on for a notebook will expand the right area:

![debugger-sidebar-expand](https://user-images.githubusercontent.com/591645/95433472-497e9c00-0950-11eb-900d-247ff9762013.gif)
 
This is meant to make to debugger sidebar most discoverable.

However when there is more than one item in the right area, the first one is shown to the user and might it not be the debugger sidebar:

![debugger-sidebar-expand-binder](https://user-images.githubusercontent.com/591645/95434367-72536100-0951-11eb-962c-cc67a83b2c1e.gif)

## Reproduce

For example on Binder with rc4:

https://mybinder.org/v2/gist/jtpio/8d392846c2f3ee6fab38cdfab5a364ec/422ca8cc6d275e2d0bdf4af4f70d59fe7043883e?urlpath=/lab/tree/debugger.ipynb

## Expected behavior

The debugger sidebar should be activated.

**Comment by jtpio** [comment]
Tagging as "good first issue", as the fix might be to replace this line:

https://github.com/jupyterlab/jupyterlab/blob/a595a001937c39e68fc8a289c8a1f37209d9b4e0/packages/debugger-extension/src/index.ts#L499

By something like:

```typescript
labShell.activateById(sidebar.id);
```

**Comment by sszaman37** [comment]
Hello! Could I try to work on this?

**Comment by jtpio** [comment]
Fixed by #9452, thanks @hbcarlos!
