### ISSUE TITLE
Notebook config is not populated with user settings in the StaticNotebook constructor if Notebook is restored from workspace

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#9152]
## Description

The notebook config is not populated with user settings in the StaticNotebook constructor in 

https://github.com/jupyterlab/jupyterlab/blob/f8ac9b14958c285b7fdf137ec12d3767da6a4fc2/packages/notebook/src/widget.ts#L179-180

## Reproduce

Add some user setting for notebook

```json
{
"defaultCell": "mardown"
}
```

Log ` this.notebookConfig` in the StaticNotebook constructor. This object should be populated with the user values, but it is not.

```
{scrollPastEnd: true, defaultCell: "code", recordTiming: false, numberCellsToRenderDirectly: 10, renderCellOnIdle: true, …}
...
defaultCell: "code"

...
scrollPastEnd: true
__proto__: Object
```

## Expected behavior

User values should override the default ones.

**Comment by vidartf** [comment]
Just as an FYI, your repro example seems to have a typo, which I assume is unintended.

**Comment by echarles** [comment]
Thx @vidartf for spotting the typo. I should have typed `markdown` and not `mardown`. I put a screenshot of a log of the notebookconfig that is initialized ini the StaticNotebook constructor which confirms the reported issue.

```js
    this.notebookConfig =
      options.notebookConfig || StaticNotebook.defaultNotebookConfig;
    console.log('--- this.notebookConfig in Static Notebook constructor:', this.notebookConfig);
```

<img width="837" alt="Screenshot 2020-10-13 at 15 09 57" src="https://user-images.githubusercontent.com/226720/95864997-6eb34600-0d66-11eb-9517-11e7039d85a8.png">

**Comment by echarles** [comment]
Tracking down the source, this begins at the docmanager level

https://github.com/jupyterlab/jupyterlab/blob/40095fcd9b0afaba581438faa80b15757c9a1516/packages/docmanager/src/widgetmanager.ts#L79-L85


where `factory.createNew(context);` does not provide any optional `source` to the docregistry

https://github.com/jupyterlab/jupyterlab/blob/40095fcd9b0afaba581438faa80b15757c9a1516/packages/docregistry/src/default.ts#L404-L406

resulting the notebook widgetmanager to rely on the harcoded default notebookconfig (source being null)

https://github.com/jupyterlab/jupyterlab/blob/40095fcd9b0afaba581438faa80b15757c9a1516/packages/notebook/src/widgetfactory.ts#L91-L109

**Comment by echarles** [comment]
Some more precisions on the reported issue: it only arise if the notebook is restored from the workspace (so not opened directly on lab load without user clicking on the notebook).

When the user clicks a notebook to open after everyting is loaded, the issue does not show up as the fetch settings has been called.

The following block code updating the notebook widget factory config is invoked after the notebook restored are created, hence 

https://github.com/jupyterlab/jupyterlab/blob/d9506b271743315fa5a8d33ee2c68dc0a1125c1b/packages/notebook-extension/src/index.ts#L665

I have moved the restoration block code a bit below and invoked the fetch settings inside and it fixes the issue.

https://github.com/jupyterlab/jupyterlab/blob/d9506b271743315fa5a8d33ee2c68dc0a1125c1b/packages/notebook-extension/src/index.ts#L580-L597

I will wait a bit here any feedback before opening a PR.

**Comment by echarles** [comment]
Closing, this is fixed in https://github.com/jupyterlab/jupyterlab/pull/9149
