### ISSUE TITLE
Stylesheet failed to load in case of a path segment that includes a :

### ISSUE THREAD

**Issue by jschaeck** [jupyterlab/jupyterlab#9159]
Hi.

We are integrating JupyterLab into a cloud environment that has some special path handling. 

It uses urls like this: https://host-name/path1/abc:xyz/lab

JupyterLab loads fine but at the place it generates absolute urls for CSS files it seems to make an error that leads to

Error Loading Theme
Stylesheet failed to load: abc:/path1/abc:xyz/lab/api/themes/@jupyterlab/theme-light-extension/index.css

It might be related to the way that urls are generated here: https://github.com/blink1073/jupyterlab/blob/e633ff77d39b00284359b6ae8eea5ec7f7bdd813/packages/coreutils/src/url.ts#L55

**Comment by ajbozarth** [comment]
I'll take a look at this

**Comment by ajbozarth** [comment]
@jschaeck I'm trying to recreate this and wanted to confirm you only see this when there's a `:` in the url path and not in other cases?

**Comment by ajbozarth** [comment]
Opened #9169 with a fix and tagged it for backport

**Comment by jschaeck** [comment]
@ajbozarth Thanks for looking into this. I only checked with : as that it what appears in our infra.
