### ISSUE TITLE
2.2.9 release

### ISSUE THREAD

**Issue by karlaspuldaro** [jupyterlab/jupyterlab#9160]
Proposing a new 2.x release (2.2.9) in order to make the following bug fixes available:
- #9010 - Notebook kernel state bug on page reload ( Fixed by #9077 - merged )
- #9159 - Stylesheet url load bug ( Fixed by #9169 - merged)

**Comment by lresende** [comment]
Thanks @karlaspuldaro, I added the `backport` tag to the issues mentioned above.

**Comment by echarles** [comment]
This PR https://github.com/jupyterlab/jupyterlab/pull/9173 revert the latest commits related to Performance (virtual notebook, CSS).

**Comment by ajbozarth** [comment]
for tracking these seem to be the open prs:

Open back port PRs:
https://github.com/jupyterlab/jupyterlab/pull/9173
https://github.com/jupyterlab/jupyterlab/pull/9168

Open PR that would need to be back ported:
https://github.com/jupyterlab/jupyterlab/pull/9189

**Comment by ajbozarth** [comment]
All 2.2.9 PRs are merged, @marthacryan will be cutting the release tomorrow

**Comment by lresende** [comment]
The release has been published.
