### ISSUE TITLE
Bad styling on a generic tag

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#9170]
The following style can break extension (for instance I'm using checkbox from material-ui and the `height: auto` is actually reducing the clickable area) because it does not scope down the input to the container:

https://github.com/jupyterlab/jupyterlab/blob/d9506b271743315fa5a8d33ee2c68dc0a1125c1b/packages/extensionmanager/style/base.css#L361-L366

I don't really know what is the best solution to fix this as it seems that there is no more checkbox involved within the extension manager. If so I'm happy to push a PR removing this style.

**Comment by vidartf** [comment]
I agree that it should either be scoped, or if unused, removed 👍

**Comment by vidartf** [comment]
(Doing a git blame dive, I'm the original author of that block, and I cannot find any reasoning or memories for why it is unscoped, so I'm going to assume it just slipped through).

**Comment by jasongrout** [comment]
Yes, @fcollonval, please submit a PR, then.

**Comment by fcollonval** [comment]
Thanks @vidartf and @jasongrout for the feedback. I push a PR #9222 to address this issue specifically that could be backported on 2.x.
