### ISSUE TITLE
Issues with 3.0.0-rc5 tutorial

### ISSUE THREAD

**Issue by dsblank** [jupyterlab/jupyterlab#9174]
## Description

Attempting to go through the `jupyterlab_apod` demo with jupyterlab 3.0.0-rc5

## Reproduce

Followed directions. I think the point where my setup differs is that I was trying to install into `~/.local`

## Issues

1. jupyter_packaging was not mentioned until later, but is needed much earlier.  Suggest adding `pip install jupyter_packaging` with jupyterlab
2. `pip install -ve .` does not work with `--user`; I had to use `--prefix=~/.local`
3. Even then, there is an error in where to put /share/ items.

```
$ pip install -ve . --prefix=/home/dblank/.local
...
Creating /home/dblank/.local/lib/python3.8/site-packages/jupyterlab-apod.egg-link (link to .)
Adding jupyterlab-apod 0.1.0 to easy-install.pth file

Installed /home/dblank/jupyterlab_apod
creating /usr/share/jupyter
error: could not create '/usr/share/jupyter': Permission denied
```

**Comment by dsblank** [comment]
Third issue is fixed with: https://github.com/jupyter/jupyter-packaging/pull/52

**Comment by jasongrout** [comment]
Is the second issue also an issue with `jupyter-packaging`?

**Comment by dsblank** [comment]
@jasongrout I think there is something broken with python3.8 (or my local setup) and "pip install -e ." because I am getting the error on many packages.

In any event, I think my PR over on jupyter_packaging is now correct.

Thanks!
