### ISSUE TITLE
Ctrl F move things in (??), inside brackets to the start of the line.

### ISSUE THREAD

**Issue by kessido** [jupyterlab/jupyterlab#9181]
Example:
using `map??` as a cell would print the following:
![image](https://user-images.githubusercontent.com/16467000/96448220-ba109d00-121b-11eb-8c00-85ecc4a760c1.png)

If you ctrl-f "Make", this it would results in this:
![image](https://user-images.githubusercontent.com/16467000/96448294-d57ba800-121b-11eb-8e7e-435d2db0722a.png)
![image](https://user-images.githubusercontent.com/16467000/96448312-db718900-121b-11eb-92d2-c8a8342eb999.png)

So far so good.
On the other hand, if you Ctrl-F "self", this would result int this:
![image](https://user-images.githubusercontent.com/16467000/96448368-f47a3a00-121b-11eb-98e3-c91e03fe0e43.png)
![image](https://user-images.githubusercontent.com/16467000/96448390-f9d78480-121b-11eb-9dac-7853a7cdeca2.png)

I have no clue as to why this happens, but thought I should at least report this ^^

I had a code like `y = f(x, z)` and when ctrl-f `x` I saw a line like `xy = f(,z)`, so I was wondering what is this new python convention where you leave the first item in a function empty! Didn't know of such syntax... lol

**Comment by jasongrout** [comment]
Thanks for posting clear instructions and screenshots. Can you also list the other information from the new issue template, like browser and jlab version?

**Comment by jasongrout** [comment]
I reproduced this in jlab 3.0rc5 on firefox on macos.

I think this was filed in a different issue, though I'm having trouble finding it in a quick search.

**Comment by ianhi** [comment]
I think it's more generally things in an output than just from the result of `??`. The other issue is about this https://github.com/jupyterlab/jupyterlab/issues/8224

**Comment by jasongrout** [comment]
> The other issue about this is #8224

Thanks for finding this!
