### ISSUE TITLE
Jupyter Lab custom workspace doesn't work always

### ISSUE THREAD

**Issue by SatanikRay91** [jupyterlab/jupyterlab#9186]
## Description

I have been trying to create a custom workspace for Jupyter Lab session(s) but it works only 50 % of the time. Rest of the time it ignores the Config file and just dumps me back into the deafult. 

## Reproduce

$ # Exports the default JupyterLab workspace
$ jupyter lab workspaces export
{"data": {}, "metadata": {"id": "/lab"}}
$
$ # Exports the workspaces named `foo`
$ jupyter lab workspaces export foo
{"data": {}, "metadata": {"id": "/lab/workspaces/foo"}}
$
$ # Exports the workspace named `foo` into a file called `file_name.json`
$ jupyter lab workspaces export foo > file_name.json
$
$ # Imports the workspace file `file_name.json`.
$ jupyter lab workspaces import file_name.json
Saved workspace: <workspaces-directory>/labworkspacesfoo-54d5.jupyterlab-workspace

Now run the Jupyter lab instance and connect to the created workspace via - 
http(s)://<server:port>/<lab-location>/lab/workspaces/foo

Followed https://jupyterlab.readthedocs.io/en/stable/user/urls.html#managing-workspaces-ui to create a new workspace 

## Expected behavior

Expected behavior is custom workspace, but 50% of the time get dumped back to default workspace

**Comment by fcollonval** [comment]
@SatanikRay91 I transferred your issue in the correct project as it does not relate to the git extension for JupyterLab.

**Comment by jtpio** [comment]
@SatanikRay91 which version of JupyterLab are you using?

**Comment by SatanikRay91** [comment]
The issue is resolved. It was related to the path of the file explorer widget. An invalid path corrupts the workspace and forces the default workspace. Seem a reasonable thing to do.
