### ISSUE TITLE
Context Menu on session indicator in toolbar

### ISSUE THREAD

**Issue by svenefftinge** [jupyterlab/jupyterlab#919]
In the toolbar it would be useful to have a context menu on the session indicator.
It should allow things like
 -> open console
 -> switch kernel session

**Comment by ellisonbg** [comment]
Yep! We now have universal context menus that will make this easy. But we could put the items on the full notebook div to make it easier to find.

**Comment by markroth8** [comment]
WIP. Discussed with @ellisonbg and we decided:

1. Open Console will be a menu item in the Notebook menu and a context menu item in the notebook
2. Switch Kernel Session will replace the kernel name label with a button that launches the switch kernel command.

**Comment by blink1073** [comment]
Fixed by #2189 and #2195.
