### ISSUE TITLE
v3.0.0rc5 extensions don't work

### ISSUE THREAD

**Issue by lodka** [jupyterlab/jupyterlab#9192]
When I tried to migrate some local extensions I changed dependencies in my extension to fit latest version of jupyterlab
```
"dependencies": {
    "@jupyterlab/application": "3.0.0-rc.5",
    "@jupyterlab/apputils": "3.0.0-rc.5",
    "@jupyterlab/mainmenu": "3.0.0-rc.5",
    "@jupyterlab/statusbar": "3.0.0-rc.5",
```

but when I'm trying to install them via `jupyter labextension link .` I'm getting this error

```
An error occured.
ValueError:
"some-extension@0.0.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension           Package
>=3.0.0-rc.5 <3.1.0     3.0.0-rc.5          @jupyterlab/application
>=3.0.0-rc.5 <3.1.0     3.0.0-rc.5          @jupyterlab/apputils
>=3.0.0-rc.5 <3.1.0     3.0.0-rc.5          @jupyterlab/mainmenu
>=3.0.0-rc.5 <3.1.0     3.0.0-rc.5          @jupyterlab/statusbar
```

**Comment by jtpio** [comment]
@lodka were you able to migrate your extensions now that JupyterLab 3.0 is released? 

Would you mind trying with the latest 3.2.1? Thanks!

**Comment by jtpio** [comment]
> but when I'm trying to install them via `jupyter labextension link .` I'm getting this error

Also you might want to convert your extension to be a prebuilt extension (added in JupyterLab 3.0): https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html#upgrading-library-versions-using-the-upgrade-script

**Comment by jtpio** [comment]
Marking as answered, since `3.0.0rc5` was released more than a year ago. and there hasn't been any follow-up.

@lodka you might want to try again with a more recent release, for example `3.3.1`. Feel free to comment here or open a new issue if you are still experiencing issues. Thanks!
