### ISSUE TITLE
Jupyter  notebook in windows

### ISSUE THREAD

**Issue by khemlalnirmalkar** [jupyterlab/jupyterlab#9198]
Hello,
Can we install jupyter notebook in windows10? if yes, please can you share any guide for that?

Thanks,

**Comment by DonatasTamosauskas** [comment]
You can use Anaconda to use Jupyter Notebook / Lab on windows, [here's the link](https://www.anaconda.com/products/individual)

**Comment by khemlalnirmalkar** [comment]
Thanks @DonatasTamosauskas

**Comment by telamonian** [comment]
closing this as solved
