### ISSUE TITLE
Make it harder to accidentally close sub-menus by hovering over the menu-bar.

### ISSUE THREAD

**Issue by stuaxo** [jupyterlab/jupyterlab#9201]
Currently if the user clicks New->  then opens the submenu, you it's very easy to accidentally close it again by hovering over 'edit' or one of the top menus (which is easy as you move the cursor to the right).

It would be good to give the user more of a chance to get the submenu, maybe there would be a slight delay where the top menu wasn't sensitive to hover, or more of a gap between the menu and the menu-bar.

**Comment by jasongrout** [comment]
There currently is a delay. Perhaps it can be adjusted if you find it is still too easy to move to another item when tracking to a submenu. This code is in the Lumino project, which provides the base elements for JupyterLab: https://github.com/jupyterlab/lumino/blob/e348a0d5120db21099b8d65d002ea2a5f5e21dfe/packages/widgets/src/menu.ts#L858-L900 https://github.com/jupyterlab/lumino/blob/e348a0d5120db21099b8d65d002ea2a5f5e21dfe/packages/widgets/src/menu.ts#L1380-L1384

**Comment by jasongrout** [comment]
Another idea discussed while doing the menus years ago is to track the mouse pointer and if the trajectory is directly towards a submenu item (i.e., in the cone formed by the mouse position when the submenu opens and the left edge of the submenu), delay closing by a longer amount. This is more forgiving for moving the mouse naturally across top-level items directly towards a submenu item. This would probably involve a change in the mouse move handler in that same Lumino file.

**Comment by stuaxo** [comment]
The cone idea is nice.

I find I try and click on the sub menu for some reason (not sure if that is just voodoo), either way, a lot of the time I hit the title bar and close it.

It may not help that I have the text a bigger than the default as I tend to zoom in a bit.

**Comment by jasongrout** [comment]
FYI, you can also use keyboard navigation to select menu items.

**Comment by jasongrout** [comment]
Trying to understand: you mention hitting the title bar, and hovering over the menu bar. The menu bar is the top-level listing of menus. How are you hitting that when trying to pick something in a submenu? For example:

<img width="754" alt="Screen Shot 2020-10-22 at 10 19 19 AM" src="https://user-images.githubusercontent.com/192614/96907604-4d321880-1450-11eb-9ab1-34c1aac8efd8.png">

**Comment by jasongrout** [comment]
Oh, are you saying that for some submenus at the top of the menu, like in the pic below, if you move the mouse along the blue path, everything is fine, but if you move the mouse along the red path, a new top-level menu item opens, and that is what you find frustrating?

<img width="500" alt="Screen Shot 2020-10-22 at 10 22 24 AM" src="https://user-images.githubusercontent.com/192614/96908035-eeb96a00-1450-11eb-9a52-86ddd39abddb.png">

**Comment by stuaxo** [comment]
Yes, New-) New Notebook is something I use relatively often.

Maybe there is some UI element I could use instead, but I only swapped from Notebook to Lab a week ago

**Comment by jasongrout** [comment]
It does seem like there is no delay when you accidentally go over the top menu bar, which is inconsistent. Let's open this issue in Lumino (where that menu code is) and go from there. I agree it should be fixed.

**Comment by jasongrout** [comment]
I opened https://github.com/jupyterlab/lumino/issues/125, where the code for that delay lives. Let's continue discussion there, where the fix would be implemented.

Thanks for bringing this up. In the meantime, you may find it helpful to use keyboard arrow navigation if this gets too frustrating.
