### ISSUE TITLE
Linked packages cannot be found in 3.0

### ISSUE THREAD

**Issue by ajbozarth** [jupyterlab/jupyterlab#9203]
After updating our packages to 3.0, but not switching to federated build, we are able to successfully build and install our extensions but on `jupyter lab build` we get the following error for each use of a linked library by an extension.

```
ERROR in resolving fallback for shared module @elyra/application
Module not found: Error: Can't resolve 'file:linked_packages/elyra-application-2.0.0-dev-505867c7eec03453457e70c8d6b636759257fdd4.tgz' in '/Users/ajbozart/anaconda3/envs/elyra/share/jupyter/lab/staging/node_modules/@elyra/code-snippet-extension/lib'
```

We see this when running `make install` on the following branch of the Elyra project with JupyterLab rc5 installed: https://github.com/ajbozarth/elyra/tree/jupyterlab3-fork

**Comment by ajbozarth** [comment]
@jasongrout this is the issue I pinged you on gitter about yesterday

**Comment by jasongrout** [comment]
Is there a way to get a simpler reproduction with just a simple sample extension?

**Comment by ajbozarth** [comment]
I don't know of any simple extensions that have a library package. I could wrote up a pair of library and extension packages from scratch, though it'd take me some time

**Comment by ajbozarth** [comment]
Ok I created a lib package and an extension that uses it using the cookie cutter and uploaded them to a temp repo here: https://github.com/ajbozarth/libexpl

You just need to follow the typical install steps for each package, using `jupyter labextension link` for the lib rather than `install`

I also confirmed that this is a reproducible issue, and unique to lab 3, the same steps success when using lab 2

**Comment by ajbozarth** [comment]
I added the steps to reproduce on the readme for that repo

**Comment by jasongrout** [comment]
Thanks. That helped a lot. Applying the changes in #9213 manually to the webpack.config.js makes things work for me.
