### ISSUE TITLE
Jupyterlab kernel keeps busy after all cells finish

### ISSUE THREAD

**Issue by arache** [jupyterlab/jupyterlab#9212]
## Description

When click "restart kernel and run all cells", JupyterLab kernel keeps busy (CPU 100%) even after all cells are done.
However it doesn't happen when running in "Classic Notebook".
It only happens on very few notebooks that calling C++ code, but not all notebooks calling C++ code having that problem.

## Reproduce

I guess it's hard to reproduce because it involves some our own libs.

But I tried to dump the stack when all the cells are done (and 100% CPU), and found the issue might be related to protobuf.
We're using protobuf 3.1.0.

## Context

- Operating System and version:
- Browser and version: Chrome 85.0.4183.83
- JupyterLab version: 2.1.5
- protobuf version: 3.1.0

Just want to understand what's the difference when executing a notebook in jupyterlab V.S. in notebook, and what can be the root cause.

**Comment by jasongrout** [comment]
> Just want to understand what's the difference when executing a notebook in jupyterlab V.S. in notebook, and what can be the root cause.

There shouldn't be a difference.

Can you check with the latest JupyterLab, or even better the 3.0 RC?

**Comment by arache** [comment]
Hi @jasongrout , we finally managed to figure out the root cause.
Basically it was caused by the @lckr/jupyterlab_variableinspector plugin.
I believe the plugin is keeping inspecting the kernel when all cells are done. If there are deep nested variables it causes the high CPU usage.
The problem went away after uninstalling the plugin.

Please close this issue if needed.

**Comment by jasongrout** [comment]
Thanks for following up here
