### ISSUE TITLE
Does py3Dmol Jupyterlab extension work with JupyterLab >2.2?

### ISSUE THREAD

**Issue by scottwsides** [jupyterlab/jupyterlab#9219]
I've tried using the 'jupyter labextension install jupyterlab_3dmol' py3dmol extension but I'm still getting blank images. I could be screwing something up so I wanted to check if this is a known problem?

**Comment by telamonian** [comment]
Looking at their repo https://github.com/3dmol/jupyterlab_3Dmol, it appears that they haven't even updated to support jlab 1.x, much less 2.x, and that the project hasn't been touched in more than two years. Try opening an issue on their github board about it, but if you can't get the attention of the original devs you're only option would be to fork it and make the needed improvements yourself.

Overall, I'd recommend that you find an alternative extension for view 3d mol structs.

Closing as this issue has nothing to do with jlab core

**Comment by scottwsides** [comment]
Yep, looking into nglview which looks better and is supported. Seems like a
good replacement.
*Dr. Scott W Sides*
(303) 718-7028
