### ISSUE TITLE
Can't plot in interactive window

### ISSUE THREAD

**Issue by coldspark29** [jupyterlab/jupyterlab#9226]
## Description
When I plot something, it does not plot in a separate window, but alway inline. When I plot something in a .py file it automatically opens in a separate window where I can zoom etc. I want the same for Jupyter. I have searched a bit online and it says I am supposed to install ``juypter-matplotlib`` and then use ``%matplotlib widget``, but then I get no plot at all. Only ``Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …`` is shown. 

## Reproduce
```
%matplotlib widget
import numpy as np
import scipy.signal as signal
from scipy.io.wavfile import read
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

# read audio samples
input_data = read("audio.wav")
audio = input_data[1]
L = len(audio)
# plot 
plt.plot(audio[0:L])
# label the axes
plt.ylabel("Amplitude")
plt.xlabel("Time")
# set the title  
plt.title("Sample Wav")
# display the plot
plt.show()
```

**Comment by ianhi** [comment]
It seems like you missing the part of the `ipympl` installation steps for jupyterlab. see https://github.com/matplotlib/ipympl#install-the-jupyterlab-extension

In short you should do the following:
```bash
pip install ipympl
conda install -c conda-forge nodejs
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
then refresh the browser page when thats done.

In `jupyterlab3` this will simplify to `pip install ipympl` :tada: 

Also you can still have a separate window pop up by using a non-inline backend such as the `qt` backend by switch `%matplotlib widget` to `%matplotlib qt`

**Comment by coldspark29** [comment]
@ianhi I was pretty sure I had nodejs installed, but you were right and it was missing. I can plot as widget now, but still not in a separate window. When I try ``%matplotplib qt`` I get ``Warning: Cannot change to a different GUI toolkit: qt. Using widget instead.``

But well apart from that: Wow this is much faster than Matlab xD

**Comment by ianhi** [comment]
> When I try %matplotplib qt I get Warning: Cannot change to a different GUI toolkit: qt. Using widget instead. 

This should work if you restart the notebook kernel first.

> But well apart from that: Wow this is much faster than Matlab xD

:tada: :tada:

**Comment by ianhi** [comment]
Closing as resolved. If you end up having further matplotlib specific questions then two good places to ask them are:
1. https://discourse.matplotlib.org/
2. https://github.com/matplotlib/ipympl

**Comment by coldspark29** [comment]
Thanks! It worked now. Thought the kernel would restart, when your restart the server... Thank for the links. I will definitely join! This project is very very exciting ! ! !
