### ISSUE TITLE
Default keyboard shortcuts cannot be overriden through overrides.json

### ISSUE THREAD

**Issue by LVerneyPEReN** [jupyterlab/jupyterlab#9228]
Hi,

## Description

By putting a `settings/override.json` file in the Application directory as reported by `jupyter lab path`, one can customize the default configuration system-wide.

This works for most of the configuration options but not for overriding default shortcuts.

## Reproduce

1. Create a `settings/override.json` file in the Application directory as reported by `jupyter lab path` with the following content:

```
{
"@jupyterlab/shortcuts-extension:shortcuts":  {
  "shortcuts": [
        {
            "command": "apputils:activate-command-palette",
            "keys": [
                "Ctrl Shift C"
            ],
            "selector": "body",
            "disabled": true
        }
    ]
}
```

2. Restart JupyterLab, go to the Advanced settings editor and notice this setting was ignored.

By the way, note that this setting is required to have a working shortcut when using https://jupyterlab.readthedocs.io/en/stable/user/terminal.html#copy-paste.

## Expected behavior

The default keyboard shortcuts should be overriden. This works well with other settings, for instance :
```
{
        "@jupyterlab/apputils-extension:themes": {
                "theme": "JupyterLab Dark"
        }
}
```

## Context

- Operating System and version: Ubuntu 18.04
- Browser and version: any browser
- JupyterLab version: 2.2.8

Note that this issue has been reported twice on Discourse this year, without any follow up comment : https://discourse.jupyter.org/t/keyboard-shortcuts-with-overrides-json/5751 and https://discourse.jupyter.org/t/some-configs-in-overrides-json-does-not-work-as-i-intended/3955. I could not find any trace of this issue in Github.

Best,

**Comment by fcollonval** [comment]
@jasongrout  I think this can be closed by #9858
