### ISSUE TITLE
Keep track of where an extension came from so you know how to uninstall it

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9231]
### Problem
Right now, you can use `jupyter labextension uninstall` to uninstall an extension that was installed by a python package (either as a federated extension, or as a static extension). I think this is not good - then you are deleting files that should be tracked by another package manager.

I think `jupyter labextension` should keep track of which extensions it installed, and only be able to uninstall those extensions. Extensions installed by other package managers should be uninstalled by those package managers.

In order to cleanly do this, we need to have an idea of how extensions were installed, and appropriate information to uninstall them.

### Proposed Solution

I think extensions installed by copying files somewhere on disk should be accompanied with a metadata file that at least lists what installed them, as well as information for how to uninstall them. Then we can tell users "this extension is being managed by conda. To uninstall this extension, do xxx".

This will also help with the confusion that comes from extension names not matching up to python/conda package names. It will also help when extensions are installed via debian, R, etc.

### Use cases

1. An extension is installed with a python package, and should be uninstalled with the same package manager. To be really clear and explicit, a conda package should be able to easily patch the python package it wraps to give conda-specific instructions.
3. An extension is installed via a system package manager (think Debian, for example). Debian should have a way to tell users using jlab tools that the extension installation is managed by a certain debian package.
2. An extension is installed by a system administrator copying files (for example, directly copying files in a Docker file setup). The user should know to contact the sysadmin directly to uninstall the extension.
3. JupyterLab (in some future version) gains the capability to install federated extensions directly from npm. JupyterLab needs a way of recording that it is managing the federated extension itself, so it knows it can uninstall it. This record needs to be stored on disk somewhere since we don't have a long-running jlab process to keep it in memory.

For now, we concentrate on federated extensions. Dealing with non-federated extensions should also be done eventually, but it is also an existing problem (compared to a new problem we are creating in 3.0).

### Work

- [X] https://github.com/jupyterlab/jupyterlab/pull/9239
- [x] https://github.com/jupyterlab/extension-cookiecutter-ts/pull/109
- [x] https://github.com/jupyterlab/jupyterlab_server/pull/132
- [x] https://github.com/jupyterlab/jupyterlab/pull/9244 (which includes https://github.com/jupyterlab/jupyterlab/pull/9232)
- [x] Should we make the file called `install.json` instead of `metadata.json`? See [below](https://github.com/jupyterlab/jupyterlab/issues/9231#issuecomment-718299644). *Edit: I went ahead and made this change since it made sense to me - let me know if you want me to revert it*

**Comment by goanpeca** [comment]
@jasongrout I have a question that might be related to this. Is there a way I can know a given package name for a given module? This is related to the schemas that define settings for a given package. So basically the plugins list that populates the advacend settings editor, is there a way to know the package names of those plugins?

**Comment by jasongrout** [comment]
Diving into this a bit more:

1. We don't have a good place for metadata in the share directory: `share/jupyter/labextensions/package-name/` directly contains the static files. We should have made the static files a subdirectory, and then we could encode the metadata in that directory. I remember thinking briefly about this, but we took the easy way.
2. Once we have a place for metadata, what do we need? I think minimally this needs to be in a JSON file in that `share/jupyter/labextensions/package-name/` directory:
   - package manager - one short word
   - package name - the package name in that package system
   - Uninstall message - a help message presented to uninstall the package
3. `pip uninstall` does not remove the empty directory if we have a scoped package. For example, `pip install jupyterlab_widgets` creates `share/jupyter/labextensions/@jupyter-widgets/jupyterlab-manager`, but `pip uninstall jupyterlab_widgets` only deletes the `jupyterlab-manager` directory, so we still have `share/jupyter/labextensions/@jupyter-widgets` on disk, even though it is empty. Perhaps we should have made each npm package a single directory instead of two-deep, perhaps by replacing `/` with some other non-URL-safe character (so it was never ambiguous what the substitution was). For example, converting `@jupyter-widgets/jupyterlab-manager` to `@jupyter-widgets#jupyterlab-manager` or something. A colon would also be an obvious choice except windows filenames cannot contain colons.

**Comment by jasongrout** [comment]
> 1. We don't have a good place for metadata in the share directory:

We could take a page out of some package manager's strategies and just put a metadata directory as a sibling of the static files directory, though I think it would be nicer to have everything self-contained in the directory. For example, pip packages have a `packagename-version.dist-info` directory as a sibling to the package directory in `site-packages`. We could do something like that.

**Comment by jasongrout** [comment]
>     1. We don't have a good place for metadata in the share directory: `share/jupyter/labextensions/package-name/` directly contains the static files.

Of course, a counter to this is that such metadata about how a package was installed is useful in the frontend too - perhaps this is just yet another file, say `metadata.json`, in the dist directory already distributed. The one bad thing is that this static directory is deleted and remade every build, whereas probably you want a single metadata.json file just checked into your python package.

**Comment by jasongrout** [comment]
Some decisions that came out of a tech discussion following the dev meeting today:

1. Keep the two-deep directory structure for package names with an organization - it would be too disruptive and confusing to try to do a substitution in the package name to put all extensions in the same directory tree, and this is consistent with how we are handling things in schemas, etc.
1. Move the webpack-generated js assets down to a `static/` directory, keep the package.json and build_log.json at the top level, and move the schemas and themes directories to the top level. Add an optional `metadata.json` file controlled by the package manager. This involves changing the builder script to put the themes and schemas at the top level.
1. The `metadata.json` file has fields for:
    - package manager - one short word
    - package name - the package name in that package system
    - Uninstall message - a help message presented to uninstall the package

**Comment by jasongrout** [comment]
Example changes in a package are outlined in the cookiecutter: https://github.com/jupyterlab/extension-cookiecutter-ts/pull/109

**Comment by jasongrout** [comment]
Given https://github.com/jupyterlab/extension-cookiecutter-ts/pull/109, should we change this default directory from `static` to `labextension`?
https://github.com/jupyterlab/jupyterlab/blob/27a5ececfd986f2b9f5dcd878269d7f6405a66e1/jupyterlab/federated_labextensions.py#L206

**Comment by jasongrout** [comment]
Here are jupyterlab_server changes: https://github.com/jupyterlab/jupyterlab_server/pull/132 as part of the approach outlined here.

**Comment by jasongrout** [comment]
>     2\. Add an optional `metadata.json` file controlled by the package manager.

After playing with it for a bit, I think `metadata.json` is too broad - it's not clear exactly what data is in this file and who maintains it. I think we should call this `installer.json`, `install_metadata.json`, or something similar, to indicate who has the responsibility of maintaining this file (i.e., the package manager installing the extension).

**Comment by jtpio** [comment]
> Given jupyterlab/extension-cookiecutter-ts#109, should we change this default directory from static to labextension?

Sounds like it would make sense :+1: 

A couple of Python packages that ship both a lab extension and a classic notebook extension have started to do that (custom widgets for example).

**Comment by jasongrout** [comment]
If you or anyone else can review the PRs listed in the original description above, I can move forward with merging and releasing a new RC so we can test it out more thoroughly in the wild.

**Comment by jasongrout** [comment]
Looks like everything is done and merged now. Thanks!
