### ISSUE TITLE
Extensions cannot be disabled in 3.0

### ISSUE THREAD

**Issue by ajbozarth** [jupyterlab/jupyterlab#9234]
## Description

Disabling extensions no longer works in 3.0, extensions are listed as disabled bug still available when running jupyterlab.

From an initial look this seems to be caused by some mishandling of the deprecation of page_config.json and the name change of the relevant config from `disabledExtensions` to `disabled_labextensions`, it's not clear if the problem is in the `jupyterlab` repo or `jupyterlab_server` repo.

## Reproduce

Run the following:
```
jupyter labextension disable @jupyterlab/launcher-extension
jupyter labextension list
```
Then run JupyterLab and note that the launcher still works

## Expected behavior

In this case the launcher should not work, this would be necessary when a 3rd party extension wishes to provide it's own launcher (eg https://github.com/elyra-ai/elyra)

## Context

Running JupyterLab 3.0 rc6

**Comment by ajbozarth** [comment]
@jasongrout this is the root of the issues I was discussing with you yesterday. I will be looking into this but given this is a 3.0 blocker IMHO, more eyes on it would be appreciated. I plan to raise it at the dev meeting tomorrow as well.

**Comment by jasongrout** [comment]
When you look at this, can you also update the docs at https://github.com/jupyterlab/jupyterlab/blob/master/docs/source/user/directories.rst#page_configjson to refer to the new page config system?

**Comment by ajbozarth** [comment]
@jasongrout we were able to find a solution and opened an PR on jupyterlab_server with the fix https://github.com/jupyterlab/jupyterlab_server/pull/131
