### ISSUE TITLE
Using path/PathExt.relative in an Lab 3.0 extension fails

### ISSUE THREAD

**Issue by lresende** [jupyterlab/jupyterlab#9243]
## Description

Using path/PathExt.relative in an Lab 3.0 extension fails

## Reproduce

```
path.resolve(path.dirname(pipelinePath), nodePath)
```
or
```
PathExt.resolve(path.dirname(pipelinePath), nodePath)
```
which causes:

```
path.js:437 Uncaught TypeError: {}.cwd is not a function
    at Object.posix.resolve (path.js:437)
    at Object.posix.relative (path.js:507)
    at Function.getPipelineRelativeNodePath (PipelineService.tsx:284)
    at CanvasManager.addNode (canvas.ts:96)
    at PipelineEditorWidget.tsx:778
    at Array.map (<anonymous>)
    at PipelineEditor.handleAddFileToPipelineCanvas (PipelineEditorWidget.tsx:767)
    at PipelineEditor.handleEvent (PipelineEditorWidget.tsx:1326)
    at Object.dispatchDrop (index.es6.js:812)
    at Drag._evtMouseUp (index.es6.js:254)
```

## Expected behavior

This works ok on previous releases of JupyterLab

## Context

```
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.5
ipython          : 7.16.1
ipykernel        : 5.3.2
jupyter client   : 6.1.6
jupyter lab      : 3.0.0rc6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
```

**Comment by lresende** [comment]
I am trying to "shimm" as suggested on the JupyterLab dev meeting. I was trying that at the extension webpack level without much success, is this something that needs to be "shimmed" on the JupyterLab level?

**Comment by jasongrout** [comment]
Do you have a simple reproduction? Perhaps using the cookie cutter to make a minimal example?

**Comment by jasongrout** [comment]
For what it's worth, we use PathExt.resolve several places in JupyterLab without any shimming.

I think a simple reproduction will help us track down what the problem might be.

**Comment by jasongrout** [comment]
It looks like we use path-posix here: https://github.com/jupyterlab/jupyterlab/blob/9284892500c9338852532d79d6c5b467c61d797b/packages/coreutils/src/path.ts#L4

When we really should probably be using the much more widely used browser polyfill `path-browserify`: https://www.npmjs.com/package/path-browserify

path-browserify is what webpack 4 shimmed the nodejs path module to: https://github.com/browserify/path-browserify#install, https://github.com/webpack/webpack/blob/5573fed586aa3960794e8e4ad39f8766e3de88a4/lib/ModuleNotFoundError.js#L24

**Comment by jasongrout** [comment]
Can someone try switching our import from `path-posix` to `path-browserify` and see if that solves your issues?

**Comment by lresende** [comment]
I gave it a quick try [here](https://github.com/lresende/jupyterlab/commit/53fa75c31f021251b9d0bf4d0c2c1e953c02f7c6) without much success, but I am not sure I am missing something. 

Also, while debugging deeper on the stack, here is what I am seeing:

![Screen Shot 2020-10-31 at 9 08 47 PM](https://user-images.githubusercontent.com/382917/97796131-a5dd8000-1bcb-11eb-8590-ae0d23393b8e.png)

**Comment by jasongrout** [comment]
Just curious, what are the actual paths you are calling resolve on here? Does it end up with a relative path, so that it needs some idea of a working directory to give an absolute path? See the semantics of how relative directories work at https://nodejs.org/api/path.html#path_path_resolve_paths.

**Comment by lresende** [comment]
So, from our code, we call PathExt.relative:

![image](https://user-images.githubusercontent.com/382917/97796526-38801e00-1bd0-11eb-8377-9d3e6d865b45.png)

And relative tries to resolve both paths:

![image](https://user-images.githubusercontent.com/382917/97796539-5baacd80-1bd0-11eb-8226-c1f654322704.png)

Which then fails:

![image](https://user-images.githubusercontent.com/382917/97796575-dbd13300-1bd0-11eb-8fd8-53f4c155d162.png)

with:

![image](https://user-images.githubusercontent.com/382917/97796587-f86d6b00-1bd0-11eb-8816-b5fbb2b6b243.png)

**Comment by lresende** [comment]
A not so simple way to reproduce the issue is to do the following:

```
git clone git@github.com:elyra-ai/elyra.git
cd elyra
git checkout -b jupyterlab3 origin/jupyterlab3
make install
jupyter lab
```
Then create a pipeline and try to drag-drop a notebook file to the pipeline editor...
But I will continue to look into this further...

**Comment by jasongrout** [comment]
So can you prepend a `/` on both of your paths, to make the paths absolute so it doesn't have to wonder what directory you are currently in?

**Comment by lresende** [comment]
Yeah, the problem is sort of gone with this hack, as it does not require `process.cwd` anymore, but, isn't the idea of calling `relative` to find the `relative relative` from the `working directory` versus `from /`?

**Comment by jasongrout** [comment]
Looks like this is also the root issue at #9253 - the error (that is masked) is this same exact error that occurs when trying to change a relative url in a markdown image to a server-specific absolute url.

**Comment by jasongrout** [comment]
I think I figured out the change in 3.x that is causing this. In 2.x, I think process was being polyfilled to have `process.cwd()` always return `"/"`. However, in our configuration for 3.x, we [manually define](https://github.com/jupyterlab/jupyterlab/blob/13c1964250d2772739fe3688360e4ef3f25564c0/builder/src/webpack.config.base.ts#L86) `process.env`, but that has the side effect of defining the `process` global to be just `{}`. If I change https://github.com/jupyterlab/jupyterlab/blob/13c1964250d2772739fe3688360e4ef3f25564c0/builder/src/webpack.config.base.ts#L86 to instead by `{cwd: () => "/"}`, things work over in #9264 and presumably work here too.

**Comment by jasongrout** [comment]
@lresende - can you see if #9264 fixes your issue?
