### ISSUE TITLE
Visual indicator that a cell has been changed

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/jupyterlab#9247]
### Problem

One pitfall expressed in the ["I don't like Notebooks"](https://www.youtube.com/watch?v=7jiPeIFXb6U&feature=emb_logo) presentation is the fact that you can re-edit a cell after it was executed, and then it's very difficult to reason about the execution state, because the cell you see is not what was executed.

### Proposed Solution

It would be really nice to have a visual indicator that the cell has been changed but not executed (similar to the visual indicator in most IDEs showing that a file was modified but not saved).

Some ideas for this visual indicator:
- a small dot in the top-right corner of the code input
- a different color (orange?) for the `In` prompt
- a `*` token in the prompt, e.g. `[3]*`

**Comment by jasongrout** [comment]
Thanks! This issue is already filed at #6790, so let's consolidate the discussion over there.

**Comment by jasongrout** [comment]
Would you mind adding your ideas for indicators to that issue?

**Comment by martinRenou** [comment]
Yes! Sorry for the duplicate
