### ISSUE TITLE
jupyterhub not present in page config data

### ISSUE THREAD

**Issue by cnydw** [jupyterlab/jupyterlab#9248]
## Description

When I tried to use the jupyterlab==3.0.0rc6 release in my jupyterhub environment, the two items related to jupyterhub (Hub Control Panel, Log Out) in the `File` menu are gone.

JL2.x release:
![image](https://user-images.githubusercontent.com/10969537/97585512-8131ae80-19f9-11eb-99b2-7d5207b9bcb8.png)

JL3.0rc6 release:
![image](https://user-images.githubusercontent.com/10969537/97585681-b63e0100-19f9-11eb-87f6-e392de3ebd96.png)

And if I check the `jupyter-config-data` in the page's source file, the `hubHost": "", "hubPrefix": "/hub/", "hubServerName": "", "hubUser": "username"` fields are not present anymore. Also, the `notebookVersion": "[6, 1, 4]"` in the 2.x release becomes `"notebookVersion": "[1, 0, 5, \"\"]"`, which refers to `jupyter-server`'s version.

So maybe this issue is related to the replacement of notebook server by jupyter-server?

**Comment by jasongrout** [comment]
Indeed, it looks like the hub extension looks for `hubPrefix` and has an early exit if it doesn't find it:
https://github.com/jupyterlab/jupyterlab/blob/6a8561fe94e15b10f7bf60674d7f3d960aa3f1a7/packages/hub-extension/src/index.ts#L136-L139

**Comment by jasongrout** [comment]
More (possibly) relevant issues: https://github.com/jupyterlab/jupyterlab/pull/8806, https://github.com/jupyterlab/jupyterlab/issues/8704 - Do those help? (I don't have any experience running lab in hub, but just trying to be helpful here)

**Comment by jasongrout** [comment]
Indeed, here are the docs for running 3.0 in JupyterHub: https://jupyterlab.readthedocs.io/en/latest/user/jupyterhub.html

**Comment by jasongrout** [comment]
@cnydw - can you check your setup, and see if the instructions for 3.0 at https://jupyterlab.readthedocs.io/en/latest/user/jupyterhub.html work, and let us know if there still is a problem?

**Comment by cnydw** [comment]
To make sure that the issue wasn't introduced by using an old version (1.1.0) of jupyterhub, I upgraded my jupyterhub to the latest version `1.2.0`. And I replaced my old `c.Spawner.cmd=["jupyterhub-singleuser"]` by `c.Spawner.cmd=["jupyter-labhub"]`.

However, this introduced a new python import error when the jupyterlab instance is started from hub


```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-labhub", line 5, in <module>
    from jupyterlab.labhubapp import main
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/labhubapp.py", line 19, in <module>
    from jupyterhub.singleuser import (
ImportError: cannot import name 'dedent' from 'jupyterhub.singleuser' (/usr/local/lib/python3.7/site-packages/jupyterhub/singleuser/__init__.py)
```

The modules being imported in 
https://github.com/jupyterlab/jupyterlab/blob/6a8561fe94e15b10f7bf60674d7f3d960aa3f1a7/jupyterlab/labhubapp.py#L19-L22 are not exposed by https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/singleuser/__init__.py in the new jupyterhub release anymore.

@blink1073
