### ISSUE TITLE
Optimizing LayoutRestorer to Save Widget with large state variables

### ISSUE THREAD

**Issue by TK-21st** [jupyterlab/jupyterlab#9249]
### Problem

The current way I'm using `tracker.save` is to connect it with a `modelChanged` signal to my widget. This is able to make sure the state is tracked constantly but leads to `tracker.save` getting called too often, which is causing a noticeable lag in the UI when it happens. 

I suspect that the frequency of the `tracker.save` is not so much of an issue alone, it's more of an issue because of the size of the model data that is being saved. The model data that is saved are 3D voxels which can get quite large as more and more objects are added to a scene. Calling tracker. save and updating that data all the time is very costly.

### Proposed Solution

So for my widget which has `metadata`(very small) and `data`(can be quite large), it can be helpful to only ask the tracker to save the widget state right before the browser is refreshed/closed. 

I was trying to use the `onbeforeunload` callback from the `window` API but doesn't seem to be triggered currently.
```
window.onbeforeunload = function(event: any): any
    {
      alert('Unloading window');
      if (!widget.isDisposed) {
        void tracker.save(widget);
      }
      return null;
    };
```

I was also considering using the `dirty` state check for notebooks to force a manual state save by the user but am unsure how to do it without using docregistry since the widget that I'm referring to only renders 3D data and is not backed by a document currently.

**Comment by jasongrout** [comment]
You could follow the pattern used by the file model:
https://github.com/jupyterlab/jupyterlab/blob/6a8561fe94e15b10f7bf60674d7f3d960aa3f1a7/packages/filebrowser/src/model.ts#L106
then on dispose, remove the listener:
https://github.com/jupyterlab/jupyterlab/blob/6a8561fe94e15b10f7bf60674d7f3d960aa3f1a7/packages/filebrowser/src/model.ts#L209
