### ISSUE TITLE
JupyterLab 3.0 doesn't support relative path for image in Markdwon

### ISSUE THREAD

**Issue by ruoyu0088** [jupyterlab/jupyterlab#9253]
JupyterLab Version 3.0.0rc6

There is a notebook file and an image file "1.png" in the same folder which's name is "myfolder". In JupyterLab 2.x, I can insert the image in the notebook by:

```md
![test](1.png)
```

the HTML it generated is:

```html
<img src="http://127.0.0.1:8888/files/1.png?_xsrf=2%7Cc62cd295%7Cb0489cf1b91864230b760df8c42f571f%7C1602720566&amp;1604039331513" alt="test">
```

JupyterLab 3.0.0rc6 is failed to show the image. The HTML it generated is:

```html
<img src="" alt="test">
```

I need to change it to:

```md
![test](/files/myfolder/1.png)
```

**Comment by eeyrjmr** [comment]
I can confirm this. All notebooks now show broken links. I had resorted to embedding (dragging in) but this means a simple update of image source does not get reflected in the notebook.

For now since the issue is explained as being relative referencing  I can work with that.

Version 3.0.0rc6

**Comment by jasongrout** [comment]
Confirmed on current master as well.
