### ISSUE TITLE
UX: I would prefer if, after "Enable Scrolling for Outputs" for one cell, it is assured that the collapsed cell remains visible

### ISSUE THREAD

**Issue by jd41** [jupyterlab/jupyterlab#9255]
Related: #1309, #3154. I skimmed these but didn't find a discussion of what I want to say at first glance.

I had a long output of a cell in my NB -  5000 lines of outputting an array for debugging purposes. I scrolled upwards through the NB to get somewhere else, and while I was in the middle of that output, I got too annoyed to scroll past the 5000 lines. So I right-clicked and clicked "Enable Scrolling for Outputs" in the context menu. But apparently, the UI didn't adapt the scroll position after I clicked, so I found myself at the end of the notebook and had to scroll more than I needed!

I would have preferred if, after clicking "Enable Scrolling for Outputs", the UI had ensured that the cell I am collapsing is still on-screen.

For example, I would have liked if the border between cell and cell output turns out to be in the middle of the screen in this particular case. I realize this wouldn't be ideal if the expanded output is minimal - then the NB shouldn't jump around unnecessarily. But the exact implementation is much less important to me personally than having some implementation that makes sure the cell always stays visible.

**Comment by jasongrout** [comment]
Here is the code for changing the output scrolling: https://github.com/jupyterlab/jupyterlab/blob/c370df576b86c4b85dfe45e0edfc6de07208acea/packages/notebook/src/actions.tsx#L1251-L1269

That handleState call at the end is supposed to make sure the active cell is scrolled into view: https://github.com/jupyterlab/jupyterlab/blob/c370df576b86c4b85dfe45e0edfc6de07208acea/packages/notebook/src/actions.tsx#L1465-L1479

Perhaps what is happening is that it is scrolling the view, and *then* content is being changed. This *may* be as simple as calling that handleState in a promise so that it takes effect after whatever happens on the page when the cell's output is changed.

**Comment by jd41** [comment]
I am sorry if I didn't get something: Is the variable scrollIfNeeded supposed to be set to true somewhere in this in this call of scrollIfNeeded?

**Comment by jasongrout** [comment]
Oh, good point. Yes, then maybe it is as easy as setting that parameter. Would you like to try setting that value, testing to see if it fixes it, and submitting a PR?

**Comment by jd41** [comment]
Would you mind doing that? I put 20-30 minutes into learning how to do that already (also related to my suboptimal laptop), and my ETA for me figuring it out is an order of magnitude higher than that for you doing it.

I don't even know if TS needs to be compiled in some way somewhere, or can be changed directly in some path, what is the path to change it etc... (you don't need to answer that in text).

It also seems advisable to me that a codebase expert submitting or reviewing the PR greps through the codebase for handleState, confirms that the scrollIfNeeded parameter is set to the intended value everywhere, and documents that confirmation in the PR message.

**Comment by jd41** [comment]
I discovered the "jupyterlab-dev-mode" bot in the meantime and, if it's possible that it generates a Binder link for my branch, I will try this change myself after all (see #9259).
