### ISSUE TITLE
pdf viewer Invalid in jupyterlab-3.0.0rc6

### ISSUE THREAD

**Issue by iotctech** [jupyterlab/jupyterlab#9261]
I can not open pdf format file in v3.0.0rc6, but the v2.2.9 is fine.

what is wrong with the latest version?

**Comment by ianhi** [comment]
I see the same with this error:
![image](https://user-images.githubusercontent.com/10111092/97911973-20b4b100-1d1a-11eb-86a8-d7a26182d7c4.png)
should be fixed by the linked PR
