### ISSUE TITLE
Fix usage tests uninstalling federated extensions

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9280]
The `usage` tests have started to fail recently, which seems to be related to the new check that prevents uninstalling extensions installed by other means than `jupyter labextension install`.

Example run: https://github.com/jupyterlab/jupyterlab/pull/9275/checks?check_run_id=1349786158

```
JupyterLab cannot uninstall @jupyterlab/mock-extension since it was installed outside of JupyterLab. Use the same method used to install this extension to uninstall this extension
```

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/how-do-we-uninstall-extensions-that-have-been-installed-using-jupyter-labextension-develop-overwrite/7845/1
