### ISSUE TITLE
Update dependencies for 3.0

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9297]
There seems to be a couple of dependency warnings when building extensions with the latest rc7 packages:

```
warning @jupyterlab/application > @jupyterlab/ui-components > @blueprintjs/core > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning @jupyterlab/application > @jupyterlab/ui-components > @blueprintjs/core > react-popper > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning @jupyterlab/builder > @jupyterlab/buildutils > crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
warning "@jupyterlab/application > @jupyterlab/ui-components > @blueprintjs/select@3.14.3" has incorrect peer dependency "react@^15.3.0 || 16".
warning "@jupyterlab/application > @jupyterlab/ui-components > @blueprintjs/select@3.14.3" has incorrect peer dependency "react-dom@^15.3.0 || 16".
warning "@jupyterlab/application > @jupyterlab/ui-components > @blueprintjs/core > react-popper@1.3.7" has incorrect peer dependency "react@0.14.x || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/application > @jupyterlab/ui-components > @blueprintjs/core > react-popper > create-react-context@0.3.0" has incorrect peer de
```

Most seem to be related to the recent update to React 17: https://github.com/jupyterlab/jupyterlab/pull/9227

**Comment by jasongrout** [comment]
Yep, I've noticed that too, especially in the browser console, where it complains that react is the wrong version.

**Comment by fcollonval** [comment]
blueprintjs have just added React 17 as peer dependency: https://github.com/palantir/blueprint/pull/4403

Xref https://github.com/jupyterlab/jupyterlab/pull/9227#issuecomment-725384681

**Comment by jtpio** [comment]
Nice, thanks @fcollonval for the heads-up!

**Comment by jtpio** [comment]
For `css-loader`, it looks like we are 2 major versions behind. And upgrading would involve some updates to address the breaking changes: https://github.com/jupyterlab/jupyterlab/pull/8921#issuecomment-683708017

**Comment by jtpio** [comment]
Some of the warnings are now gone in rc8:

![image](https://user-images.githubusercontent.com/591645/98984186-24b6af00-2522-11eb-98ce-279f3623360a.png)

**Comment by jasongrout** [comment]
We decided in the dev meeting that these warnings are fine in 3.0 (given that react 17 is *very* backwards compatible), and they will get better over time as the community migrates. We might recant this if there are user-visible warnings in the js console.

**Comment by jasongrout** [comment]
> We might recant this if there are user-visible warnings in the js console.

JupyterLab 3.0rc10 does not have these sorts of warnings for me in the browser js console.

**Comment by jtpio** [comment]
Updated the title to " Update dependencies for 3.0".

We should be able to close this issue, since updating `css-loader` can be addressed later:

https://github.com/jupyterlab/jupyterlab/pull/9364#issuecomment-730852589

Unless we want to update a couple more, for example the eslint dev dependencies.

**Comment by jasongrout** [comment]
- [ ] 
  > warning "@typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".

- [ ]
  > warning " > react-docgen-typescript-loader@3.7.2" has unmet peer dependency "typescript@*".

- [ ]
  > warning "react-docgen-typescript-loader > @webpack-contrib/schema-utils@1.0.0-beta.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".

- [ ]
  > warning "react-docgen-typescript-loader > react-docgen-typescript@1.20.3" has unmet peer dependency "typescript@>= 3.x".

- [ ]
  > warning " > typedoc@0.17.0-3" has unmet peer dependency "typescript@>=3.7".

- [ ]
  > warning " > @jupyterlab/ui-components@3.0.0-rc.10" has unmet peer dependency "react@^17.0.1".

- [X] Discussed at #9364
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/application-top > css-loader@3.2.1" has incorrect peer dependency "webpack@^4.0.0".

- [ ] TODO
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/example-federated-middle > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".

- [ ] TODO
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/extensionmanager > react-paginate@6.3.2" has incorrect peer dependency "react@^16.0.0".

- [ ] TODO
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".

- [ ] react-json-tree is not updated yet
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".

- [ ] react-json-tree is not updated yet
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".

- [ ] TODO
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/ui-components > awesome-typescript-loader@5.2.1" has incorrect peer dependency "typescript@^2.7 || ^3".

- [ ] Spurious warning?
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/ui-components > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".

- [ ] See https://github.com/nteract/outputs/issues/48 - no update available
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".

- [ ] https://github.com/palantir/blueprint/pull/4403#issuecomment-731366331
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/ui-components > @blueprintjs/core > react-popper@1.3.7" has incorrect peer dependency "react@0.14.x || ^15.0.0 || ^16.0.0".

- [ ] https://github.com/palantir/blueprint/pull/4403#issuecomment-731366331
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/ui-components > @blueprintjs/core > react-popper > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".

- [ ]
  > warning "workspace-aggregator-8cdbb08c-5596-4d6c-b0cd-64b3ff91330b > @jupyterlab/ui-components > @storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".

**Comment by jasongrout** [comment]
If someone can takeover looking at each of these and either deciding they are not important for 3.0, or if we should do something about them, and updating the comment above, that would help us keep track of what we are doing for 3.0 and what we are leaving on the table for later.

**Comment by fcollonval** [comment]
Comment: following #9227, it would be good to update to @types/react v17 that was release a week ago (https://www.npmjs.com/package/@types/react/v/17.0.0).

**Comment by jtpio** [comment]
Sounds good, thanks @fcollonval.

I was wondering why `@types/react` is in `dependencies` and not `devDependencies` in the first place, but there seems to be some details about this in https://github.com/jupyterlab/jupyterlab/pull/4367 and https://github.com/jupyterlab/jupyterlab/pull/4386.

**Comment by fcollonval** [comment]
> I was wondering why `@types/react` is in `dependencies` and not `devDependencies` in the first place, but there seems to be some details about this in #4367 and #4386.

Ja this is still weird for me. Thanks for pointing to the related PR. It may be that with typescript being more mature now the situation is improved and the types could be moved to dev dependencies. But this definitely will require testing.

**Comment by jtpio** [comment]
> But this definitely will require testing

Yes probably something to reconsider post 3.0. It indeed looks like they could eventually be moved back to `devDependencies`.

**Comment by blink1073** [comment]
Closing as addressed for this release
