### ISSUE TITLE
Question: Create a Remote Kernel Connection

### ISSUE THREAD

**Issue by samborba** [jupyterlab/jupyterlab#9299]
Good night guys, is everything all right?

First of all, I would like to thank you for the excellent project. Undoubtedly, it is one of the best open source projects I've ever had contact with.

I've been working on an extension that allows me to connect to a remote Kernel. My goal is to be able to use all the features of my machine that is currently in the company I work for.

I have some doubts when using Jupyter packages:

I have the kernel websocket address that is on my remote machine and it is already cross origin enabled. How do I send the frontend input code to this socket address? Through this extension, I am instantiating a new KernelManager and SessionManager, but it appears that the session I create is not that it is communicating with the frontend...

Thanks for the help,
See ya

**Comment by agoose77** [comment]
Have you looked at Jupyter kernel gateway?
