### ISSUE TITLE
jupyterlab==3.0.0-rc7 incompatibilities with latest lumino 

### ISSUE THREAD

**Issue by dsblank** [jupyterlab/jupyterlab#9303]
I was just trying out jupyterlab==3.0.0-rc7

and had to move these two packages' versions down from the latest due to incompatibilities:

```
    "@lumino/datagrid": "^0.13.0",
    "@lumino/widgets": "^1.14.0",
```
I think the issue was related to inconsistent `Widget` definitions. 

This worked:

```
  "dependencies": {
    "@jupyterlab/application": "^3.0.0-rc.7",
    "@jupyterlab/launcher": "^3.0.0-rc.7",
    "@jupyterlab/mainmenu": "^3.0.0-rc.7",
    "@jupyterlab/translation": "^3.0.0-rc.7",
    "@lumino/algorithm": "^1.3.3",
    "@lumino/coreutils": "^1.5.3",
    "@lumino/datagrid": "^0.13.0",
    "@lumino/widgets": "^1.14.0",
    "@lumino/disposable": "^1.4.3"
  },
 ```

But later versions of widgets and datagrid caused problems.

**Comment by jasongrout** [comment]
Can you give a little more details about how to reproduce the problem?
