### ISSUE TITLE
How to delete Icon？

### ISSUE THREAD

**Issue by S664813266** [jupyterlab/jupyterlab#9313]
How to delete the others Icon？
![image](https://user-images.githubusercontent.com/56161895/98796848-d1236300-2446-11eb-80a1-c2784687bd0b.png)

**Comment by jtpio** [comment]
@S664813266 you might be able to achieve this by disabling the extensions:

```
jupyter labextension disable @jupyterlab/terminal-extension @jupyterlab/inspector-extension
```
