### ISSUE TITLE
Cannot build ipywidgets extension on Beaglebone

### ISSUE THREAD

**Issue by tjcrone** [jupyterlab/jupyterlab#9314]
## Description

I am trying to install ipywidgets for Jlab on the Beaglebone, which has limited memory. The system recommends that I rebuild: 

```
$ jupyter labextension list
JupyterLab v2.2.9
Known labextensions:
   app dir: /home/debian/test5/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK

Build recommended, please run `jupyter lab build`:
    @jupyter-widgets/jupyterlab-manager needs to be included in build
```
Building generates the following:
```
$ jupyter lab build --minimize=False
[LabBuildApp] JupyterLab 2.2.9
[LabBuildApp] Building in /home/debian/test5/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (ie the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-uxugpb4d.log
```
and the log file:
```
$ cat /tmp/jupyterlab-debug-uxugpb4d.log
[LabBuildApp] Building in /home/debian/test5/share/jupyter/lab
[LabBuildApp] Node v10.21.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:prod)
[LabBuildApp] > node /home/debian/test5/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 140.88s.

[LabBuildApp] > node /home/debian/test5/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ /home/debian/test5/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 18.63s.

[LabBuildApp] > node /home/debian/test5/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod
[LabBuildApp] yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.config.js
/usr/bin/node[1327]: ../src/node_platform.cc:416:std::shared_ptr<node::PerIsolatePlatformData> node::NodePlatform::ForIsolate(v8::Isolate*): Assertion `data' failed.
child_process.js:650
    throw err;
    ^

Error: Command failed: /home/debian/test5/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.config.js
    at checkExecSyncError (child_process.js:629:11)
    at Object.execFileSync (child_process.js:647:13)
    at Object.<anonymous> (/home/debian/test5/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/home/debian/test5/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/home/debian/test5/lib/python3.7/site-packages/jupyterlab/labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "/home/debian/test5/lib/python3.7/site-packages/jupyterlab/labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/home/debian/test5/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/home/debian/test5/lib/python3.7/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

## Reproduce

1) Run `jupyter lab build --minimize=False`

## Expected behavior

I expect the build to work and ipywidgets to work in Jlab.

## Context

- Operating System and version: Debian 10 (buster)
- Browser and version: Chrome
- JupyterLab version: 2.2.9

<details><summary>Troubleshoot Output</summary>
<pre>
$ jupyter troubleshoot
$PATH:
	/home/debian/test5/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/local/games
	/usr/games

sys.path:
	/home/debian/test5/bin
	/usr/lib/python37.zip
	/usr/lib/python3.7
	/usr/lib/python3.7/lib-dynload
	/home/debian/test5/lib/python3.7/site-packages

sys.executable:
	/home/debian/test5/bin/python3

sys.version:
	3.7.3 (default, Jul 25 2020, 13:03:44) 
	[GCC 8.3.0]

platform.platform():
	Linux-4.19.94-ti-r42-armv7l-with-debian-10.6

which -a jupyter:
	/home/debian/test5/bin/jupyter

pip list:
	Package             Version  
	------------------- ---------
	argon2-cffi         20.1.0   
	async-generator     1.10     
	attrs               20.3.0   
	backcall            0.2.0    
	bleach              3.2.1    
	certifi             2020.11.8
	cffi                1.14.3   
	chardet             3.0.4    
	decorator           4.4.2    
	defusedxml          0.6.0    
	entrypoints         0.3      
	idna                2.10     
	importlib-metadata  2.0.0    
	ipykernel           5.3.4    
	ipython             7.19.0   
	ipython-genutils    0.2.0    
	ipywidgets          7.5.1    
	jedi                0.17.2   
	Jinja2              2.11.2   
	json5               0.9.5    
	jsonschema          3.2.0    
	jupyter-client      6.1.7    
	jupyter-core        4.6.3    
	jupyterlab          2.2.9    
	jupyterlab-pygments 0.1.2    
	jupyterlab-server   1.2.0    
	jupyterlab-widgets  0.6.15   
	MarkupSafe          1.1.1    
	mistune             0.8.4    
	nbclient            0.5.1    
	nbconvert           6.0.7    
	nbformat            5.0.8    
	nest-asyncio        1.4.2    
	nodejs              0.1.1    
	notebook            6.1.5    
	optional-django     0.1.0    
	packaging           20.4     
	pandocfilters       1.4.3    
	parso               0.7.1    
	pexpect             4.8.0    
	pickleshare         0.7.5    
	pip                 18.1     
	pkg-resources       0.0.0    
	prometheus-client   0.8.0    
	prompt-toolkit      3.0.8    
	ptyprocess          0.6.0    
	pycparser           2.20     
	Pygments            2.7.2    
	pyparsing           2.4.7    
	pyrsistent          0.17.3   
	python-dateutil     2.8.1    
	pyzmq               19.0.2   
	requests            2.24.0   
	Send2Trash          1.5.0    
	setuptools          40.8.0   
	six                 1.15.0   
	terminado           0.9.1    
	testpath            0.4.4    
	tornado             6.1      
	traitlets           5.0.5    
	urllib3             1.25.11  
	wcwidth             0.2.5    
	webencodings        0.5.1    
	widgetsnbextension  3.5.1    
	zipp                3.4.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
$ jupyter lab --no-browser --debug
[D 12:40:35.100 LabApp] Searching ['/home/debian', '/home/debian/.jupyter', '/home/debian/test5/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 12:40:35.106 LabApp] Looking for jupyter_config in /etc/jupyter
[D 12:40:35.109 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 12:40:35.112 LabApp] Looking for jupyter_config in /home/debian/test5/etc/jupyter
[D 12:40:35.117 LabApp] Looking for jupyter_config in /home/debian/.jupyter
[D 12:40:35.121 LabApp] Looking for jupyter_config in /home/debian
[D 12:40:35.134 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 12:40:35.137 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 12:40:35.140 LabApp] Looking for jupyter_notebook_config in /home/debian/test5/etc/jupyter
[D 12:40:35.143 LabApp] Looking for jupyter_notebook_config in /home/debian/.jupyter
[D 12:40:35.146 LabApp] Looking for jupyter_notebook_config in /home/debian
[D 12:40:35.166 LabApp] Raising open file limit: soft 1024->4096; hard 1048576->1048576
[D 12:40:35.219 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/etc/jupyter/jupyter_notebook_config.json
[D 12:40:35.229 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 12:40:35.240 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/debian/test5/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/home/debian/test5/etc/jupyter/jupyter_notebook_config.json
[D 12:40:35.254 LabApp] Paths used for configuration of jupyter_notebook_config: 
    	/home/debian/.jupyter/jupyter_notebook_config.json
[I 12:40:54.079 LabApp] JupyterLab extension loaded from /home/debian/test5/lib/python3.7/site-packages/jupyterlab
[I 12:40:54.082 LabApp] JupyterLab application directory is /home/debian/test5/share/jupyter/lab
[I 12:40:54.121 LabApp] Serving notebooks from local directory: /home/debian
[I 12:40:54.124 LabApp] Jupyter Notebook 6.1.5 is running at:
[I 12:40:54.125 LabApp] http://localhost:8888/?token=9f1524e652875f68d0143965ea8f42dba41e9cf9555f42c1
[I 12:40:54.127 LabApp]  or http://127.0.0.1:8888/?token=9f1524e652875f68d0143965ea8f42dba41e9cf9555f42c1
[I 12:40:54.129 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:40:54.181 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/debian/.local/share/jupyter/runtime/nbserver-1345-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=9f1524e652875f68d0143965ea8f42dba41e9cf9555f42c1
     or http://127.0.0.1:8888/?token=9f1524e652875f68d0143965ea8f42dba41e9cf9555f42c1
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by tjcrone** [comment]
I was able to keep the build going for about an hour or so with
```
export NODE_OPTIONS=--max-old-space-size=1024
```
But memory filled and the process slowed to a crawl and I did not wait to see if it would finish. I tried with node 12 and 14, and with a few Jupyterlab 3.x release candidates, as well as node 10 and Jlab 2.2. No dice. But Jupyterlab works great on the Beaglebone otherwise as long as it doesn't need to be built.

I am going to give up on building Jupyterlab on Beaglebone for now. If there is a way to cross-build it might be worth looking into that, but I do not have a solution for this at this stage. Thanks and good luck!

**Comment by jasongrout** [comment]
Just curious - can you try adding `--dev-build=True` as well?

```
export NODE_OPTIONS=--max-old-space-size=1024
jupyter lab build --dev-build=True --minimize=False
```

JupyterLab 3 has a new extension system that allows you to install extensions systems without rebuilding, so that should help tremendously.

**Comment by tjcrone** [comment]
Hi @jasongrout, thank you for replying. I believe I did try `--dev-build=True` a few times, and it did not work, but I do not think I tried with Jupyterlab 3. I bounced around between a few versions of node and Jupyterlab but I didn't work through this very systematically. I would be happy to try a few things for you if this would be of assistance, but I'm guessing that the number of people who want to run Jupyterlab on the Beaglebone is small. Beaglebone is a great hardware/IoT platform so having widgets would be great for the development process, to push buttons to control hardware things, but the amount of memory on this board is pretty small (512 MB) so it might not be a great fit.

One of the reasons I bumped to Jupyterlab 3.0.0r6 and r7 was to try this new extension system that didn't require a rebuild, but as soon as I installed widgets (which did not work at first), a rebuild was recommended (via the pop-up and also on the command line), and the rebuild usually failed. Is there a process for installing widgets without a rebuild that I did not do correctly? Thanks!

**Comment by jasongrout** [comment]
> Is there a process for installing widgets without a rebuild that I did not do correctly? Thanks!

Yes, using the pre-release `jupyterlab_widgets` package:

```
pip install --pre jupyterlab
pip install ipywidgets
pip install --pre jupyterlab_widgets
```
Then launch JupyterLab `jupyter lab` and widgets should work.

**Comment by tjcrone** [comment]
Thank you for this helpful advice. I will give it a shot tomorrow and let you know how it goes. Greatly appreciate your help and Jupyterlab as well!

**Comment by tjcrone** [comment]
@jasongrout your suggestion worked great. Thank you for your help!!

**Comment by jasongrout** [comment]
Awesome! Glad to know of another concrete case where these pre-built extensions are useful.
