### ISSUE TITLE
Close a (big) notebook while it is still loading (virtual notebook) for 2.x branch

### ISSUE THREAD

**Issue by goanpeca** [jupyterlab/jupyterlab#9315]
## Reproduce

1. Open a very big notebook, that benefits from virtual notebook work
2. Try to close it while has not fully loaded
3. It will not close.

## Expected behavior

Notebook should be closable even if not fully loaded.

Pinging @echarles and @mlucool 

Jlab: 2.2.3a1

**Comment by jtpio** [comment]
Closing as this was targeting `2.3.x` is there is now a virtual notebook implementation in `4.0.0`.
