### ISSUE TITLE
Federated labextensions: package name logic

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/jupyterlab#9320]
## Description

When using the federated labextension script, the logic for finding the package name fails if the directory contains e.g. a `docs` directory that is a valid Python module. `find_packages` will find the `docs` module and look for the `_jupyter_labextension_paths` function there.
https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/federated_labextensions.py#L373-L381

## Reproduce

1. Make a `docs` directory that contains an `__init__.py` file in the extension
2. Run `jupyter labextension develop .` in the root directory of the extension
 

## Expected behavior

If I can suggest a slight change in the current logic, it looks to me that the `package = find_packages()[0]` could be more of a "fallback" solution for when the `setup.py --name` is not defined, instead of the other way around.

I can come up with a PR myself if this change would be ok:
- first look for `setup.py --name`
- if it fails, look for `find_packages()[0]`

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
> I can come up with a PR myself if this change would be ok:
> 
>     * first look for `setup.py --name`
> 
>     * if it fails, look for `find_packages()[0]`

That sounds reasonable to me. Thanks!
