### ISSUE TITLE
Warn of untracked files when doing a release

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9322]
I just released 3.0.0rc8, in which a new file had been added to `dev_mode` and hence during the release was added to `staging/`, but wasn't already tracked as a file under version control. Turns out that updating `staging/` did not commit the new file, so I ended up having a release commit that did not include one of the files needed (and master then started failing tests since `staging/` was missing a file).

I committed this file and pushed to master. We still have one more untracked file, `jupyterlab/tests/mock_packages/mimeextension/yarn.lock` - not sure what to do about this one.

However, in general, it would be good to have a warning during the release if there are untracked files in the repo so this doesn't happen again.

**Comment by jtpio** [comment]
Thanks @jasongrout for reporting this.

Do you know if this is still happening recently? Now that we are using the Jupyter Releaser for making releases there are a couple more checks in place to detect uncommitted changes and potential other issues:

- via `check-manifest`
- this check before bumping the version:

https://github.com/jupyterlab/jupyterlab/blob/5f4e3fabf33bed101e41708021a245ca59410511/buildutils/src/utils.ts#L212-L224

**Comment by jasongrout** [comment]
I haven't done too many releases with this recently, but also haven't seen any problems. If you feel it's been taken care of, great!

**Comment by jtpio** [comment]
> We still have one more untracked file, `jupyterlab/tests/mock_packages/mimeextension/yarn.lock` - not sure what to do about this one.

Just checked in the `sdist` for `4.0.0a21` (https://pypi.org/project/jupyterlab/4.0.0a21/#files) and this particular file doesn't seem to be there (which is expected):

```
$ ls jupyterlab/tests/mock_packages/mimeextension 
index.js  package.json
```

I would say let's close and open new issues if we notice something later. Thanks!
