### ISSUE TITLE
Make filebrowser double-clicking and "open" context menu do the same in single-document mode

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9323]
### Problem

Using 3.0.0rc8 (or a previous 3.0 release candidate), switch to single-document mode, then:

* double-click on a file. It opens a new browser tab.
* right click on the file and select "open". It opens the file in the existing JupyterLab.

Having these do two different things is confusing to me.

Opening a file in a new browser tab more closely mimics the feel of the classic Notebook, however it is also a pretty large departure from how JupyterLab has worked. Opening the file in a new browser tab is also available by right-clicking on a file and selecting "Copy Shareable Link", then opening a new browser tab and pasting in the link.

This is mentioned in #9099 and #9117.

### Proposed Solution

I strongly think:
* both actions (double-click and right-click and "open") should do the same thing
* if we support both default open behaviors, I think there should be a setting allowing the user to choose between the two behaviors.

I have a preference for the default action being to open the file in the existing browser tab, i.e., what the "open" menu item does now. (Disclaimer: in addition to personal preference, this will also make embedding JupyterLab into products like the product I'm helping to support easier.)

Perhaps we can also have a new context menu entry that allows for opening the file in JupyterLab a new browser tab (instead of copying the shareable link, opening a tab, pasting it in).

**Comment by jasongrout** [comment]
CC @ellisonbg who implemented this behavior

**Comment by agoose77** [comment]
What's the purpose of the existing open-in-new-tab menu item? In my testing, it serves the notebook content rather than opening it in JupyterLab

![image](https://user-images.githubusercontent.com/1248413/99047747-8b70b280-258c-11eb-8e63-6edf93254890.png)

My preference here is default to open in the same browser tab, and expose the "in new tab" functionality via the existing "in new tab" context menu item, but then I'm not currently a big user of single document mode.

**Comment by jasongrout** [comment]
> What's the purpose of the existing open-in-new-tab menu item?

It is to open a file "raw" in a new browser tab. For example, opening an html file should just open the raw html in the browser, opening a pdf should just open the raw pdf in a browser tab, etc. This has confused people as well, who expected this to open the file in jlab in a new tab.

**Comment by jasongrout** [comment]
I looked into the code more that implements this. I think that while this behavior has a lot of merit in this usecase (single-document mode), there are enough inconsistencies and rough edges with it in its current form that we should revert the behavior for 3.0 and iterate with the other feedback we are going to get on the single-document mode.

1. Default opening in a new browser tab is a pretty big departure from JupyterLab behavior up to this point
2. This double-click behavior is inconsistent with the "open" context menu item.
3. It is inconsistent with other behaviors that open a file (for example, clicking on a link in a markdown file)
4. It's not easy to override for environments embedding JupyterLab in a single tab (disclosure: I help support one such environment)

I think if we are going to support the paradigm that activities/files are in separate browser tabs, we should probably go all the way and make this a setting in the doc manager that is used consistently across all document openings, rather than an option for opening a specific file used in the one case of double-clicking in the file browser. We should also probably address how to handle activities that might be opened that are not documents.

**Comment by jasongrout** [comment]
>  We should also probably address how to handle activities that might be opened that are not documents.

For example, how do we handle creating a new view for an output? It would be nice if we were able to share state between the two windows (either as a child window with direct access to js objects, or using real-time collaboration).

**Comment by jasongrout** [comment]
> I think that while this behavior has a lot of merit in this usecase (single-document mode)

For example, jlab persists the mode across restarts. If a user persistently works in single-document mode, it might be really confusing where all of their documents are being opened, or tiresome to switch between documents, and likely they want separate browser tabs for each activity. This would mirror single-document interfaces like the classic Notebook, google docs, etc. But again, I think we need to think more carefully about making this paradigm pervasive throughout jlab if this is what we are going for.

As for making it easy to switch between documents, I'm sure we can do more. For example, we can make a right-click menu on the document title that shows a list like in the Tab menu that lets you choose a different document to display.

**Comment by telamonian** [comment]
I think eventually the open behavior should be a user option. There's some users who would prefer the new "open in new tab" behavior; I've definitely seen some feedback to that effect. There's also plenty of prior art for making this kind of file open behavior configurable by a user. For example, see the [`"window.openFoldersInNewWindow"` option in vscode](https://code.visualstudio.com/docs/getstarted/userinterface#_window-management).

However, if the current implementation of the feature isn't well-baked enough to justify sticking it into the 3.0 release then I think it makes sense to completely revert it for now.

**Comment by jasongrout** [comment]
> I think eventually the open behavior should be a user option.

Absolutely, or maybe eventually when it works much more seamlessly across jlab, it can be a default.

> However, if the current implementation of the feature isn't well-baked enough to justify sticking it into the 3.0 release then I think it makes sense to completely revert it for now.

This is where I think we are at right now.

**Comment by ellisonbg** [comment]
Will catch up on the discussion, definitely more work to do...

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/seeking-feedback-jupyterlab-single-document-mode-switch-position/6715/14
