### ISSUE TITLE
"Server Not Running" popup can be Misleading

### ISSUE THREAD

**Issue by moghtader** [jupyterlab/jupyterlab#9324]
## Description

I am running JupyterLab remotely behind a VPN. When someone disconnects from the VPN or WiFi, they get a "Server Not Running" popup, which confuses many users. Should the wording be changed? 

## Reproduce

Connect to JupyterLab in a remote configuration and start running a notebook. Disconnect from WiFi. You will see the "Server Not Running" 

## Expected behavior

"Server unavailable or unreachable" could be potential ways to word it better. Also a "Refresh/Reconnect" button on the popup to allow a user to reconnect without refreshing the entire page. 

## Context

- Operating System and version: Mac OS 10.15.6
- Browser and version: Chrome 86
- JupyterLab version: 2.29

**Comment by jasongrout** [comment]
Great idea!

To find the place in the code where this message is, you can paste `"Server Not Running"` in the Search box at the upper left of this webpage. That leads to https://github.com/jupyterlab/jupyterlab/blob/4e7c446dccae5e82b1eba9af3eb1705917bc91a5/packages/hub-extension/src/index.ts#L153

Can one of you submit a pull request changing the wording? I think your "Server unavailable or unreachable" would be excellent. You can edit the file and submit a pull request following these instructions: https://docs.github.com/en/enterprise/2.13/user/articles/editing-files-in-another-users-repository

**Comment by jasongrout** [comment]
Fixed by #9325. Thanks again @lacrosse91!
