### ISSUE TITLE
Shared module is not available for eager consumption

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9329]
Testing with rc8 and a mix of federated and non-federated extensions.

The federated extension shares its copy of the shared package metadata with:

```json
  "sharedPackages": {
      "mypackage": {
        "requiredVersion": "^0.6.0",
        "bundled": true,
        "singleton": true
      }
    }
```

The non-federated extension defines the shared package metadata with:

```json
"sharedPackages": {
      "mypackage": {
        "requiredVersion": "^0.6.0",
        "bundled": false,
        "singleton": true
      }
    }
```

Would yield the following in the browser console:

```
Error: Shared module is not available for eager consumption: webpack/sharing/consume/default/mypackage
```

(see https://github.com/jtpio/jupyterlab-topbar/pull/53 for more details)

It looks like it may be related to the eager mode added in https://github.com/jupyterlab/jupyterlab/pull/9312

**Comment by jtpio** [comment]
Patching `[site-packages]/jupyterlab/staging` to remove `eager: true`, followed by `jupyter lab clean && jupyter lab build` seems to fix it.

**Comment by jtpio** [comment]
At the moment it looks like `eager` is set to all shared package. Which could also explain why there is a big bundle with almost everything in it.

**Comment by jasongrout** [comment]
Yes, I thought I tested setting all to eager (as opposed to just setting core packages to eager), and I thought the loading worked out, since we load all federated extensions shared packages before loading the main file.

**Comment by jasongrout** [comment]
If needed, we could just set the core resolutions to eager, but that will take away a lot of the benefits of the eager (since installed extensions are likely the bulk of the javascript)

**Comment by jasongrout** [comment]
I'll check again with eager. Do I have the setup right?

- provider is a pre-built extension
- consumer is a source extension, depends on provider, but does not bundle it

Or is it:

- provider-extension is a pre-built extension, depends on provider (which exports a token), and bundles provider
- consumer is a source extension, depends on provider, but does not bundle it

**Comment by jtpio** [comment]
> I thought I tested setting all to eager (as opposed to just setting core packages to eager)

I think this is what is happening at the moment: all are set to `eager`.

If pre-built = federated, then the setup is the first one:

> * provider is a pre-built extension
> 
> * consumer is a source extension, depends on provider, but does not bundle it

**Comment by jasongrout** [comment]
> If pre-built = federated

Yes. Sorry, I'm trying out some of the new terms we've been brainstorming over on the other issue.

**Comment by jasongrout** [comment]
Confirmed that there is a problem with this example in 3.0.0rc8: https://github.com/jupyterlab/jupyterlab/pull/9310#issuecomment-725178396

**Comment by jtpio** [comment]
> If needed, we could just set the core resolutions to eager, but that will take away a lot of the benefits of the eager (since installed extensions are likely the bulk of the javascript)

I was playing with this idea a little bit locally, which also addresses this particular use case. Although the number and size of bundles look similar in both cases (a couple more in the second case).

All set to eager:

![image](https://user-images.githubusercontent.com/591645/99105523-f77e0580-25e2-11eb-9acd-06101f6cb979.png)

Only `@jupyterlab/` / `@lumino` / `react` set to eager:

![image](https://user-images.githubusercontent.com/591645/99105487-e7662600-25e2-11eb-8964-0e7bb315644f.png)

**Comment by jasongrout** [comment]
I've also been playing around this. The fundamental problem here is that even though the provider is loaded in the module cache before the main jlab code runs, extensions are provided by default async, and the eager built-in modules expect to immediately use code (not to wait for async loads). This strikes me as essentially the async function coloring issue.

Two possible ways forward:

A. One thing we could do is just make the core built-in extensions eager. Since built-in extensions are typically activated at startup, that would mean that we go back to having a ton of files loaded at startup async if you have lots of extensions installed. The good news is that we expect most extensions to migrate to prebuilt extensions, so perhaps this case won't be the common case "soon".
B. Another thing we could do is to make all federated extensions bundle their main extension export as eager, i.e., propagate the eagerness throughout the system. If a plugin is activated at startup, I think there's not really any reason to not be eager - we'll have to load that code anyway. Most plugins are activated at startup, so perhaps that should be our default?

**Comment by jasongrout** [comment]
How about for now, to get a new RC out that fixes this breakage, we take the middle path (eager for core things we know we are providing, async for everything else), and we discuss whether we want to make everything async or everything eager.

(Note that even if we default everything to eager, extensions authors can still explicitly opt-out for certain dependencies to async load them. For example, even though we have core extensions eager, we are still explicitly loading some codemirror things async.)

**Comment by jasongrout** [comment]
> How about for now, to get a new RC out that fixes this breakage, we take the middle path (eager for core things we know we are providing, async for everything else), and we discuss whether we want to make everything async or everything eager.

Implemented in #9332. If you want to review, I can merge and do another RC to fix the breakage.

**Comment by jtpio** [comment]
> How about for now, to get a new RC out that fixes this breakage, we take the middle path (eager for core things we know we are providing, async for everything else), and we discuss whether we want to make everything async or everything eager.

Yes that sounds like a good middle ground for now :+1:

**Comment by jasongrout** [comment]
Actually, I think webpack should probably package together the async loads together. I'll post a reproduction and question on webpack to ask why async packages aren't being packaged together.
