### ISSUE TITLE
Scroll Bar Location when Clearing Output

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#9331]
## Description

If you clear output on a cell, the scroll bar should move back to the selected cell, not where it is left off. Otherwise, it gives the appearance of jumping cells.

This seems to be another variant of https://github.com/jupyterlab/jupyterlab/issues/7822

## Reproduce
![scrollJump](https://user-images.githubusercontent.com/1813603/99113584-86782700-25bd-11eb-851f-9c3a78b2e4e0.gif)

## Expected behavior

The selected cell remains on screen.

## Context

- Operating System and version: Windows
- Browser and version: Chrome
- JupyterLab: 2.3.0a1

**Comment by jasongrout** [comment]
Another related issue:  #9255 (fixed in #9273), and part of an audit of focus behavior after notebook operations: #9283

Do you want to make a PR with a fix for this specific issue?
