### ISSUE TITLE
Code Editor out of Sync Please open your browser JavaScript console for bug report instructions

### ISSUE THREAD

**Issue by GF-Huang** [jupyterlab/jupyterlab#9340]
`vendors~main.e39d4a65a871fe1cc8fa.js:2 Please paste the following to https://github.com/jupyterlab/jupyterlab/issues/2951`

`vendors~main.e39d4a65a871fe1cc8fa.js:2 {"model":"dataset = df_train_norm.to_numpy(na_value=)\r","view":"dataset = df_train_norm.to_numpy(na_value=)\n","selections":[{"uuid":"a7c46ed9-6bda-40be-9b63-536d5f496754","start":{"line":0,"column":0},"end":{"line":0,"column":0},"style":{"className":"","displayName":"","color":"black"}}],"cursor":{"line":0,"column":0},"lineSep":null,"mode":"text/x-ipython","change":{"from":{"line":0,"ch":0,"sticky":null},"to":{"line":1,"ch":0,"sticky":null},"text":["dataset = df_train_norm.to_numpy(na_value=)",""],"origin":"setValue","removed":["dataset = df_train_norm.to_numpy()",""]}}
_checkSync @ vendors~main.e39d4a65a871fe1cc8fa.js:2`

**Comment by jasongrout** [comment]
What version of JupyterLab are you using? It looks like that issue was solved in jlab 1.0.

**Comment by GF-Huang** [comment]
I thinks it's the latest, because I install it just last night by `pip install jupyterlab`.

**Comment by jasongrout** [comment]
Can you check with `jupyter lab --version`?

**Comment by jasongrout** [comment]
(or you can look in the Help menu, "About JupyterLab")

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/99295562-88254180-2880-11eb-9686-cd5b9bc74819.png)

**Comment by jasongrout** [comment]
Thanks.

Confirming that:

A. the code for reporting this issue is still in JupyterLab
B. from the report above, it does appear to be a \r vs \n issue, just like in #2951

Thanks for reporting.

**Comment by jasongrout** [comment]
It looks like similar errors have been recently reported over in #7703. Let's consolidate the discussion over there.

**Comment by suuuehgi** [comment]
> Please paste the following to https://github.com/jupyterlab/jupyterlab/issues/2951

```
{"model":"# TODO\r\nlat_dims = [2, 4, 8, 16, 32, 64, 128\n]r foNdims x in lat_dims:\r\n  model = VAE(image_size=28, latent_dims=x, capacity=32)\r\n  model.to(device)\r\n  optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)\r\n  train_loss, test_loss, mean_train_loss, mean_test_loss, mu, logvar = train_model(model, optimizer, vae_loss, train_loader, test_loader, epochs, device)\r\n  fig, ax = plt.subplots()\r\n  ax.plot(np.arange(1,epochs+1), mean_train_loss)\r\n  ax.plot(np.arange(1,epochs+1), mean_test_loss)\r\n  fig.suptitle(\"Latent dimensions = \" + str(x))\r\n  plt.show()\r\n  with torch.no_grad():\r\n    model.train()\r\n    samples = model.sample(mu, logvar)\r\n    samples = model.fc_z(samples)\r\n    samples = samples.unflatten(1, (64, 7, 7))\r\n    images_recon = model.decode(samples.to(device))\r\n    images_recon = images_recon.cpu()\r\n    show_grid(images_recon[0:(images_columns * images_rows)], images_columns, images_rows)","view":"# TODO\nlat_dims = [2, 4, 8, 16, 32, 64, 128]\n\nfoNdims x in lat_dims:\n  model = VAE(image_size=28, latent_dims=x, capacity=32)\n  model.to(device)\n  optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)\n  train_loss, test_loss, mean_train_loss, mean_test_loss, mu, logvar = train_model(model, optimizer, vae_loss, train_loader, test_loader, epochs, device)\n  fig, ax = plt.subplots()\n  ax.plot(np.arange(1,epochs+1), mean_train_loss)\n  ax.plot(np.arange(1,epochs+1), mean_test_loss)\n  fig.suptitle(\"Latent dimensions = \" + str(x))\n  plt.show()\n  with torch.no_grad():\n    model.train()\n    samples = model.sample(mu, logvar)\n    samples = model.fc_z(samples)\n    samples = samples.unflatten(1, (64, 7, 7))\n    images_recon = model.decode(samples.to(device))\n    images_recon = images_recon.cpu()\n    show_grid(images_recon[0:(images_columns * images_rows)], images_columns, images_rows)","selections":[{"uuid":"368f496e-99bb-4efa-8a13-efd94346151f","start":{"line":2,"column":0},"end":{"line":2,"column":0},"style":{"className":"","displayName":"","color":"black"}}],"cursor":{"line":2,"column":0},"lineSep":null,"mode":"text/x-ipython","change":{"from":{"line":1,"ch":37,"sticky":"before","xRel":119.64999389648438},"to":{"line":1,"ch":37,"sticky":"before","xRel":119.64999389648438},"text":["",""],"origin":"+input","removed":[""]}}
```

**Comment by gstripling** [comment]
Thanks!

**Comment by pseudo-usama** [comment]
> > Please paste the following to #2951
> 
> ```
> {"model":"# TODO\r\nlat_dims = [2, 4, 8, 16, 32, 64, 128\n]r foNdims x in lat_dims:\r\n  model = VAE(image_size=28, latent_dims=x, capacity=32)\r\n  model.to(device)\r\n  optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)\r\n  train_loss, test_loss, mean_train_loss, mean_test_loss, mu, logvar = train_model(model, optimizer, vae_loss, train_loader, test_loader, epochs, device)\r\n  fig, ax = plt.subplots()\r\n  ax.plot(np.arange(1,epochs+1), mean_train_loss)\r\n  ax.plot(np.arange(1,epochs+1), mean_test_loss)\r\n  fig.suptitle(\"Latent dimensions = \" + str(x))\r\n  plt.show()\r\n  with torch.no_grad():\r\n    model.train()\r\n    samples = model.sample(mu, logvar)\r\n    samples = model.fc_z(samples)\r\n    samples = samples.unflatten(1, (64, 7, 7))\r\n    images_recon = model.decode(samples.to(device))\r\n    images_recon = images_recon.cpu()\r\n    show_grid(images_recon[0:(images_columns * images_rows)], images_columns, images_rows)","view":"# TODO\nlat_dims = [2, 4, 8, 16, 32, 64, 128]\n\nfoNdims x in lat_dims:\n  model = VAE(image_size=28, latent_dims=x, capacity=32)\n  model.to(device)\n  optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)\n  train_loss, test_loss, mean_train_loss, mean_test_loss, mu, logvar = train_model(model, optimizer, vae_loss, train_loader, test_loader, epochs, device)\n  fig, ax = plt.subplots()\n  ax.plot(np.arange(1,epochs+1), mean_train_loss)\n  ax.plot(np.arange(1,epochs+1), mean_test_loss)\n  fig.suptitle(\"Latent dimensions = \" + str(x))\n  plt.show()\n  with torch.no_grad():\n    model.train()\n    samples = model.sample(mu, logvar)\n    samples = model.fc_z(samples)\n    samples = samples.unflatten(1, (64, 7, 7))\n    images_recon = model.decode(samples.to(device))\n    images_recon = images_recon.cpu()\n    show_grid(images_recon[0:(images_columns * images_rows)], images_columns, images_rows)","selections":[{"uuid":"368f496e-99bb-4efa-8a13-efd94346151f","start":{"line":2,"column":0},"end":{"line":2,"column":0},"style":{"className":"","displayName":"","color":"black"}}],"cursor":{"line":2,"column":0},"lineSep":null,"mode":"text/x-ipython","change":{"from":{"line":1,"ch":37,"sticky":"before","xRel":119.64999389648438},"to":{"line":1,"ch":37,"sticky":"before","xRel":119.64999389648438},"text":["",""],"origin":"+input","removed":[""]}}
> ```
> 
> JupyterLab version 2.2.9.
> 
> The notebook came from a Google Colab instance with:
> 
> ```
> jupyter core     : 4.5.0
> jupyter-notebook : 5.2.2
> qtconsole        : 4.5.2
> ipython          : 5.5.0
> ipykernel        : 4.10.1
> jupyter client   : 5.3.1
> jupyter lab      : not installed
> nbconvert        : 5.5.0
> ipywidgets       : 7.5.0
> nbformat         : 4.4.0
> traitlets        : 4.3.2
> ```
> 
> **P.s.** In the mean time for anyone stumbling on this error, it seems to be sufficient to create a new cell above / below the affected one, copy pase everything over and delete the old one.

It worked!

**Comment by jasongrout** [comment]
We're now tracking this bug of not handling \r\n line endings in notebook cells over in #9465
