### ISSUE TITLE
Eager consumption for shared direct dependencies

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9343]
This will sound similar to https://github.com/jupyterlab/jupyterlab/issues/9329 addressed in https://github.com/jupyterlab/jupyterlab/pull/9332.

Testing with the following setup:

- JupyterLab 3.0.0rc9
- A local extension installed with `jupyter labextension install`

It looks webpack is giving the same "Shared module is not available for eager consumption" error at runtime as in #9329.

`@blueprintjs/core` is a direct dependency of `@jupyterlab/ui-components`, and `@jupyterlab/ui-components` is added to the  `eager` packages:

```json
"@jupyterlab/ui-components": {
  "requiredVersion": "~3.0.0-rc.9",
  "eager": true,
  "singleton": true
},
"@jupyterlab/ui-components-extension": {
  "requiredVersion": "~3.0.0-rc.9",
  "eager": true
},
```

At the same time, `@blueprintjs/core` is also a direct dependency of the third-party extension. So it is added to the shared scope, but not as an eager package: 

```json
"@blueprintjs/core": {
  "requiredVersion": "^3.32.1"
},
```

So we end up in this configuration:

- `@jupyterlab-ui-components` (with `eager: true`) -> `@blueprintjs/core`
- `local-extension` (without `eager: true`) -> `@blueprintjs/core` (without `eager: true`)

To reproduce:

- Create a new environment with JupyterLab 3.0.0rc9
- Install a non-federated extension that depends on `@blueprintjs/core` with `jupyter labextension install`

In theory this should reproducible with another package than `@blueprintjs/core` too, as long as it is a direct dependency of one of the core packages but not a core package itself.

For example (and quick testing) here is the setup I've been using:

```bash
conda create -n jlab-eager -c conda-forge/label/jupyterlab_rc -c conda-forge/label/jupyterlab_server_rc -c conda-forge jupyterlab=3 nodejs python -y
conda activate jlab-eager

jupyter labextension install jupyterlab-topbar-extension jupyterlab-theme-toggle

jupyter lab
```

**Comment by jtpio** [comment]
Ah it could be because this block:

https://github.com/jupyterlab/jupyterlab/blob/781c61561b4531774418e44212eb0547f5b9beaa/dev_mode/webpack.config.js#L195

Only iterates through the  `*-extension` packages.

Which would skip the dependencies of the core package itself.

**Comment by jasongrout** [comment]
Thanks, you're right. We need to do a full transitive dependency analysis for those eager packages. I'm putting in a PR, but I may also just give up on eager packages for now. I'm also testing again to make sure to see if we can get the bundling benefits with full async shared modules.

**Comment by jtpio** [comment]
Thinking about options B and C from https://github.com/jupyterlab/jupyterlab/issues/9329#issuecomment-726939036, I was also wondering whether we should consider the more conservative option C to opt-out from using the `eager` flag.

> We need to do a full transitive dependency analysis for those eager packages.

It sounds like defining the boundary between eager and non-eager packages might lead to some tricky edge cases. Unless going with option B and trying to push the eager through the whole pipeline, which sounds a bit risky at this stage. Or doing the full dependency analysis yes.

**Comment by jasongrout** [comment]
> It sounds like defining the boundary between eager and non-eager packages might lead to some tricky edge cases. Unless going with option B and trying to push the eager through the whole pipeline, which sounds a bit risky at this stage. Or doing the full dependency analysis yes.

In the end, I eliminate eager packages over in #9348.

**Comment by jasongrout** [comment]
3.0.0rc10 is out now with this fix. Can you try again with 3.0rc10?

**Comment by jtpio** [comment]
Thanks.

I was testing locally with the patch from https://github.com/jupyterlab/jupyterlab/pull/9348, but will check with rc10 too :+1:
