### ISSUE TITLE
Node packages like "path": polyfill not available for extensions

### ISSUE THREAD

**Issue by martinRenou** [jupyterlab/jupyterlab#9345]
### Problem

I was updating an extension to the federated extensions system, and had an issue because it depends on "path" and webpack 5 does not include a polyfill for this package anymore.

One solution proposed by @jtpio in my case was to extend the webpack.config of the JupyterLab builder to add:

```javascript
resolve: {
    fallback: {
        "path": require.resolve("path-browserify")
    }
}
```

This works (given that "path-browserify" is added as a dependency), but I was wondering if this should be added to the webpack.config of the JupyterLab builder?

This issue might be raised also for other node modules.

### Proposed Solution

Updating the webpack.config to expose this module.

**Comment by jtpio** [comment]
Thanks Martin for opening this issue :+1: 

We might also want to add some extra notes to the [migration guide](https://jupyterlab.readthedocs.io/en/latest/developer/extension_migration_2_3.html), since webpack 5 does not provide polyfills anymore which could break some extensions.

**Comment by jasongrout** [comment]
We could provide a few common polyfills for prebuilt extensions. Any others besides path that would be good?

**Comment by jasongrout** [comment]
On the other hand, look at the migration suggestions for webpack 5: https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

* Try to use frontend-compatible modules whenever possible. - Can you just use and depend on `path-browserify` rather than node's `path`?
* Package authors: Use the browser field in package.json to make a package frontend-compatible. Provide alternative implementations/dependencies for the browser - can you depend on `path-browserify` in your package and use the `browser` field of your package.json to specify the fallback?

Both of those options seem more sustainable in the long term because they put the fallback in the module author's hands.

**Comment by jasongrout** [comment]
> Use the browser field in package.json to make a package frontend-compatible.

We do this in coreutils now: https://github.com/jupyterlab/jupyterlab/blob/5c4e5bf21647a7637033ed8b5923b53b1cca181d/packages/coreutils/package.json#L17-L19

Does something similar work for your package?

**Comment by jtpio** [comment]
When we looked at it, I think it was the dependency / dependencies of a dependency that was problematic. For example `vfile`: https://github.com/vfile/vfile

So yes ideally those packages should support both node and browser environments. But it was a couple of them that had to be updated if I recall correctly.

**Comment by jasongrout** [comment]
> When we looked at it, I think it was the dependency / dependencies of a dependency that was problematic.

I was afraid you were going to say that. What do you think? Should we support standardized polyfills for the time being for a few packages so that people don't have to modify their webpack config? We could support them for now and remove them in the next version of jlab, hoping that the world fixes itself as webpack 5 becomes more popular.

**Comment by martinRenou** [comment]
We still have the solution of extending the `webpack.config`, which works well. This could simply be documented so you don't have to include it in JupyterLab

**Comment by jtpio** [comment]
If we are able to seamlessly address a wide number of cases by adding this to the builder base webpack config, then that would be great because extension authors wouldn't have to take extra actions.

Otherwise yes this could documented:

- add `browser` to `package.json` if possible (own package or can raise a PR)
- add a custom webpack config

**Comment by jasongrout** [comment]
What modules? Here is the list from webpack 4:

https://github.com/webpack/webpack/blob/3471c776059ac2d26593ea39f9c47c1874253dbb/lib/ModuleNotFoundError.js#L13-L42

```js
const previouslyPolyfilledBuiltinModules = {
	assert: "assert/",
	buffer: "buffer/",
	console: "console-browserify",
	constants: "constants-browserify",
	crypto: "crypto-browserify",
	domain: "domain-browser",
	events: "events/",
	http: "stream-http",
	https: "https-browserify",
	os: "os-browserify/browser",
	path: "path-browserify",
	punycode: "punycode/",
	process: "process/browser",
	querystring: "querystring-es3",
	stream: "stream-browserify",
	_stream_duplex: "readable-stream/duplex",
	_stream_passthrough: "readable-stream/passthrough",
	_stream_readable: "readable-stream/readable",
	_stream_transform: "readable-stream/transform",
	_stream_writable: "readable-stream/writable",
	string_decoder: "string_decoder/",
	sys: "util/",
	timers: "timers-browserify",
	tty: "tty-browserify",
	url: "url/",
	util: "util/",
	vm: "vm-browserify",
	zlib: "browserify-zlib"
};
```

**Comment by jasongrout** [comment]
Should we just start with `path`, and add more if we hear more complaints?

I think `path` is the only one we ran across in the core jlab code.

**Comment by jasongrout** [comment]
Note: this polyfill just needs to be added to the [base webpack config](https://github.com/jupyterlab/jupyterlab/blob/master/builder/src/webpack.config.base.ts) (and the dependency added to the builder package) to be available to both prebuilt and source extension packages.

**Comment by jtpio** [comment]
> Note: this polyfill just needs to be added to the [base webpack config](https://github.com/jupyterlab/jupyterlab/blob/master/builder/src/webpack.config.base.ts) (and the dependency added to the builder package) to be available to both prebuilt and source extension packages.

Ah nice that's handy. It is indeed used here: https://github.com/jupyterlab/jupyterlab/blob/5c4e5bf21647a7637033ed8b5923b53b1cca181d/dev_mode/webpack.config.js#L14

> Should we just start with path, and add more if we hear more complaints?

@martinRenou do you remember what module it was for the other packages? 

It's possible `process` was also one of them.

**Comment by jasongrout** [comment]
> It's possible `process` was also one of them.

We explicitly provide a process "polyfill" already: https://github.com/jupyterlab/jupyterlab/blob/5c4e5bf21647a7637033ed8b5923b53b1cca181d/builder/src/webpack.config.base.ts#L89-L91

**Comment by martinRenou** [comment]
> @martinRenou do you remember what module it was for the other packages

Only, `path` was an issue if I remember correctly.

**Comment by martinRenou** [comment]
To add to the list:
- The `buffer` polyfill is needed in ipycanvas
- The `crypto` polyfill is needed in ipyleaflet

Maybe those would be worth adding?

**Comment by martinRenou** [comment]
I am happy to come up with a PR if you agree

**Comment by jasongrout** [comment]
If the polyfill is needed by an extension, do you think it is better in general to ask authors to add the fallbacks to their `browser` package metadata? Then they have control over the polyfill, and it is closer to the code.

On the other hand, if it is a dependency of theirs that needs the polyfill, and that dependency does not have `browser` specified, perhaps that's a really good reason for us to have it in the webpack config.
