### ISSUE TITLE
Please make 'Reconnect to Kernel' more available

### ISSUE THREAD

**Issue by kevin-bates** [jupyterlab/jupyterlab#9353]
This is probably a duplicate of #2526 but I've never thought the solution in #2654 is all that helpful.   Granted the functionality _exists_ but it's completely natural for a user that requires reconnection to their kernel to look for such an option in the Kernel menu - which is exactly what they do in classic Notebook.  

In JL 3.0, it appears that the "command palette" is no longer on the left-hand column and now must be accessed via `View->Activate Command Palette` only then to have to search for reconnect - where its found next to the plethora of kernel restart options - all of which themselves are also represented in the Kernel menu.

Why is reconnect not in the Kernel menu as well?  Would such a PR to include Reconnect in the menu be accepted?

Thanks

**Comment by jasongrout** [comment]
+1 from me to having a reconnect option in the jlab kernel menu. Confirmed that it is a menu option in the classic notebook.

**Comment by jasongrout** [comment]
Do you want to review #9356? I'm not sure exactly how to test the reconnection, but I used essentially the same code as the reconnect command palette item.
