### ISSUE TITLE
Reuse the Switch component for the debugger

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9354]
When the debugger was added to core there was no default switch component in lab yet: https://github.com/jupyterlab/jupyterlab/issues/8010

So it brought its own here:

https://github.com/jupyterlab/jupyterlab/blob/5c4e5bf21647a7637033ed8b5923b53b1cca181d/packages/debugger/style/icons.css#L11

Now that `ui-components` has a `Switch`, currently used to toggle the single document mode:

![image](https://user-images.githubusercontent.com/591645/99427621-ef390980-2905-11eb-8aa2-4fc9f6457788.png)

We should be able to reuse in the `debugger` extension too:

https://github.com/jupyterlab/jupyterlab/blob/5c4e5bf21647a7637033ed8b5923b53b1cca181d/packages/ui-components/src/components/switch.ts#L11

**Comment by jasongrout** [comment]
Adding to 3.0, not as a blocker, but as (I think) an important ux polish issue for 3.0 if we can get to it.
