### ISSUE TITLE
Add isToggleable to toggleable lumino objects

### ISSUE THREAD

**Issue by marthacryan** [jupyterlab/jupyterlab#9365]
For accessibility, buttons that can be toggled need to be marked as toggleable. Since jupyterlab/lumino#129 was merged, we can now add that to lumino objects that can be toggled.

**Comment by saulshanabrook** [comment]
@marthacryan I saw you closed your PR to fix this. What are the next steps here?

**Comment by marthacryan** [comment]
Oh oops I forgot to close this issue! Refer to the discussion on #9487 for an explanation of closing this
