### ISSUE TITLE
[Question] mp4 video created by ffmpeg doesn't display with IPython.display.Video

### ISSUE THREAD

**Issue by austinmw** [jupyterlab/jupyterlab#9366]
Hi, I'm creating mp4 videos from jpegs with ffmpeg, using the following command:

`ffmpeg -f image2 -i jpegs/%05d.jpg -framerate 10 video.mp4`

The resulting video will play fine with VLC, but will not play in jupyter lab (or notebook) via:

```python
from IPython.display import Video
Video('./video.mp4')
```
This is the result:
![Screen Shot 2020-11-18 at 2 16 29 PM](https://user-images.githubusercontent.com/12224358/99576974-ad14d400-29a8-11eb-97c2-6a7525d4e128.png)

This notebook video functionality has worked for me in the past, so I guess maybe there's some mismatch between the format ffmpeg outputs and the format the Video function expects?

**Comment by jasongrout** [comment]
IIRC, the video display just uses the browser video tag (you can check this by right-clicking on the element and "inspect"ing it to see what is in the browser), so will recognize whatever the browser recognizes. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#Usage_notes for more info about what browsers recognize.

**Comment by austinmw** [comment]
Hi @jasongrout thanks for your response. I don't seem to have an inspect option on the video element:

![Screen Shot 2020-11-18 at 3 25 09 PM](https://user-images.githubusercontent.com/12224358/99583964-501e1b80-29b2-11eb-9000-c7800e708da4.png)

**Comment by austinmw** [comment]
Solved the issue. I needed to add `-vcodec libx264` to my ffmpeg command.

**Comment by jasongrout** [comment]
Great, thanks for following up here with a solution so others can benefit.

**Comment by jasongrout** [comment]
> I don't seem to have an inspect option on the video element:

Sorry - shift-right click bypasses the jupyterlab context menu to bring up the browser menu - I should have said that.
