### ISSUE TITLE
Extension manager should be as helpful as labextension for prebuilt extensions

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9367]
Currently, `jupyter labextension uninstall` and `jupyter labextension list` give extra information for packages with an `install.json`, namely listing the package manager and package name, and also the uninstall instructions.

The extension manager should give similar information for those just using the UX.

**Comment by jasongrout** [comment]
@echarles - is there some time, maybe tomorrow or early next week, that we could coordinate getting this done? We can divide the work so that I do the server side api and you do the extension manager ux, for example.

**Comment by echarles** [comment]
@jasongrout Sure, let's do that. If this works for you, you can open a PR to update the REST endpoint, I will then take it over to update the UI. We can work on two separate branches or on a single one (easier). To work on a single branch, I have given you write access to https://github.com/datalayer-contrib/jupyterlab. We can do the work at another place if you prefer.

If design is not clear and a discussion is welcome, we can plan that a call on Monday.

**Comment by jasongrout** [comment]
If you submit a PR and check the box to let maintainers contribute, we can both just push to that PR.

**Comment by jasongrout** [comment]
> you can open a PR to update the REST endpoint,

Oh, I guess I'm the one to first open a PR, then you should be able to just push to my PR.

**Comment by echarles** [comment]
> Oh, I guess I'm the one to first open a PR, then you should be able to just push to my PR.

Let's do that. Looking forward to you PR so I can contribute to it.

**Comment by jasongrout** [comment]
> Let's do that. Looking forward to you PR so I can contribute to it.

@echarles, an initial implementation of the API improvement is in #9390, if you want to take over and push to that PR (or if it's easier, merge that PR and follow up in a different PR). Thanks for working on the front end part of this!

**Comment by krassowski** [comment]
Thank you everyone for working on this. I wonder if there are plans on improving the metadata utilisation, especially providing a link to the extension webpage/documentation. It seems that currently the prebuilt extensions are at disadvantage and the extension manager is not as helpful for them as for the node-based extensions (no description, no link, no pic):

![Screenshot from 2021-01-03 01-57-19](https://user-images.githubusercontent.com/5832902/103470189-0a9d8e00-4d67-11eb-8392-89c98d47570d.png)

Is this intended?

**Comment by jasongrout** [comment]
Yes. This was the first step, and we invite help to make things better.
