### ISSUE TITLE
Multiple keyboard shortcuts

### ISSUE THREAD

**Issue by flow2k** [jupyterlab/jupyterlab#9369]
Is it possible assign multiple keyboard shortcuts to a single function? For example, I'd like Cmd-W and Alt-W to both close the current tab. The config is currently as follows:
```
        {
            "command": "application:close",
            "keys": [
                "Alt W"
            ],
            "selector": ".jp-Activity"
        }
```
Looks like I can only replace the "Alt W".

**Comment by jasongrout** [comment]
You can just define another shortcut with exactly the same information except different keys.

**Comment by jasongrout** [comment]
> Cmd-W

This is covered in your other issue at #9370  - I think the browser reserves this and it is not available to JupyterLab (unless the browser is started in application mode, I think).

**Comment by jasongrout** [comment]
Closing as answered.

**Comment by flow2k** [comment]
Thanks, @jasongrout.
