### ISSUE TITLE
Replace browser shortcut key

### ISSUE THREAD

**Issue by flow2k** [jupyterlab/jupyterlab#9370]
It seems when the shortcut key conflicts with an already-existing browser shortcut key, the browser intercepts the keystroke rather than JupyterLab. Is it possible to have JupyterLab intercept the key? For example

```
        {
            "command": "application:close",
            "keys": [
                "Accel W"
            ],
            "selector": ".jp-Activity"
        }
```

On Chrome, Chrome intercepts this.

**Comment by jasongrout** [comment]
> Is it possible to have JupyterLab intercept the key?

Sometimes not. We do all we can to intercept shortcuts as early as possible in the browser handling, but for some shortcuts, the browser does not even give them to the webpage to handle. I think probably `Accel W` is one of the ones we cannot override.

Likely starting the browser in application mode opens up some of these keyboard shortcuts to be overridden.

**Comment by jasongrout** [comment]
Closing as answered. If you find another way to work around this, please let us know here!

**Comment by flow2k** [comment]
Sure, thanks for the response.
