### ISSUE TITLE
File Save Error 403: Invalid Response when saving the notebooks

### ISSUE THREAD

**Issue by tirumerla** [jupyterlab/jupyterlab#9377]
## Description

Hi Guys,

I'm running into issue of **"File Save Error"** error with `403: Invalid Response` and `403: Forbidden` when i try to save the notebook with _any url's in the output of the cell_ or when there is auto-save it keeps popping. 
What i observed was if you run `print("://")` in the notebook and save it. This throws `403: invalid response` but when i run `print(":\//")` in the notebook it saves without any issue.

## Reproduce

**Test 1 -**
1. Create a notebook in jupyterlab. (This can be "Untitled.ipynb" or any other notebook.)
2. Run the command `print("://")` to see the output in the cell.
3. Save the notebook or let the auto save run.
4. You will see `403: Invalid Response` error on the notebook. 

- You can dismiss and continue to work but the command won't be saved.

**Test 2 -** 
1. Create a notebook in jupyterlab. (This can be "Untitled.ipynb" or any other notebook.)
2. Run the command `print(":\//")` to see the output in the cell.
3. Save the notebook or let the auto save run.
4. You will see saving of notebook is successful. 

I first tried to run `env` command in the notebook and save it. I noticed we were getting `403: Invalid Response` when saving.
I was able to save notebooks if i don't have **url's ( specifically `://` )** in the output of the cells.

## Expected behavior

- Save the notebook without any issues.

## Context

- Environment Details - Jupyterhub running on Amazon EKS
- Amazon EKS - `v1.17.9`

- Operating System and version: `Linux 4.14.193-149.317.amzn2.x86_64`
- Browser and version: Tried it on Firefox `81.0.2` and chrome `85.0.4183.102`.
- JupyterLab version: `2.2.6`

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /opt/conda/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /opt/conda/bin
        /opt/conda/lib/python36.zip
        /opt/conda/lib/python3.6
        /opt/conda/lib/python3.6/lib-dynload
        /opt/conda/lib/python3.6/site-packages

sys.executable:
        /opt/conda/bin/python

sys.version:
        3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
        [GCC 7.3.0]

platform.platform():
        Linux-4.14.193-149.317.amzn2.x86_64-x86_64-with-debian-buster-sid

which -a jupyter:
        /opt/conda/bin/jupyter
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data vendors~main.d6ae31c7fff1f92f0bb6.js:2:2450711
Uncaught (in promise) Error: Invalid response: 403 Forbidden
PUT | https://<host-name>/hub/user/<user_name>/api/contents/Untitled.ipynb?1605774970033= [HTTP/2 403 Forbidden 92ms]
Error in Auto-Save Invalid response: 403 Forbidden
</pre>
</details>

I assume this issue #8949 could be related.

Appreciate your help. 

Thanks.

**Comment by jasongrout** [comment]
I did your test 1 and test 2 in a clean conda environment with jupyterlab 2.2.9 installed, and did not see any problems (both files saved, there were no errors), on Firefox 83 on macOS Catalina.

```
conda create -y -n jlab-9377 -c conda-forge jupyterlab
conda activate jlab-9377
jupyter lab
```
Can you check in the browser messages exactly what the save request and response was? Perhaps it is EKS giving you a permission error of some type?

**Comment by tirumerla** [comment]
Thanks @jasongrout for the response. I'm attaching the screenshots. Not sure if this is a bug in `2.2.6` 
<img width="798" alt="Screen Shot 2020-11-19 at 12 03 48 PM" src="https://user-images.githubusercontent.com/57160285/99718511-d3e21180-2a5f-11eb-93f5-cc97595dcbb0.png">
<img width="1792" alt="Screen Shot 2020-11-19 at 11 50 34 AM" src="https://user-images.githubusercontent.com/57160285/99718517-d6dd0200-2a5f-11eb-85b3-193f9b9aea88.png">

**Comment by jasongrout** [comment]
It looks to me like your server is returning a 403, and the JupyterLab frontend is correctly telling you it is getting a 403. It sounds like something is wrong with permissions in the setup you have. The key here is figuring out why you are getting a 403 error from the server. For that, I would look into the server logs to find the permission error.

**Comment by tirumerla** [comment]
> It looks to me like your server is returning a 403, and the JupyterLab frontend is correctly telling you it is getting a 403. It sounds like something is wrong with permissions in the setup you have. The key here is figuring out why you are getting a 403 error from the server. For that, I would look into the server logs to find the permission error.

Yep I'm digging through the logs as we speak. What's interesting is if you do `print(":\//")` there are no issues at all.

**Comment by tirumerla** [comment]
Hi @jasongrout - I found the issue, this is due to our WAF firewall rules that `://` is causing WAF to block ( thinking it's an XSS attack ) the request. 
Appreciate your help with the issue. We can close the this ticket now.
