### ISSUE TITLE
Single-document mode switch label

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9378]
We now have a top-level ux control for toggling single-document mode. Initially it was labeled something like "Single Document Mode", but that takes up a *lot* of space. More recently, we've shortened that to just "Mode". In https://discourse.jupyter.org/t/seeking-feedback-jupyterlab-single-document-mode-switch-position/6715, several people thought that was too generic and confusing. You can also see we use the word "Mode" already in the status bar to indicate the notebook command/edit mode.

![](https://user-images.githubusercontent.com/591645/98399029-1f5cee80-2062-11eb-9531-ac1277017cd1.gif)

One suggestion was to change the "Mode" label to "Single Document".

Is this a tweak we want to make before 3.0? If not, I'll add it to the single-document feedback issue.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/seeking-feedback-jupyterlab-single-document-mode-switch-position/6715/15

**Comment by choldgraf** [comment]
Why not ‘doc’? That’s what the URL of this mode uses, right?

**Comment by joelostblom** [comment]
Another suggestion would be "focus" or similar. There is also a suggestion with an icon in the statusbar now, which would be another way of solving this https://github.com/jupyterlab/jupyterlab/pull/9389
