### ISSUE TITLE
Use CSS property contain to display a notebook

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#9381]
### Problem

While experimenting to find the root cause of the performance issues (https://github.com/jupyterlab/jupyterlab/issues/9279), we have found that the CSS property `contain` could be used to mitigate multiple forced layout rendering

https://developer.mozilla.org/en-US/docs/Web/CSS/contain

### Proposed Solution

Before displaying a notebook, set the content with contain=strict. Only when the notebook creation process is complete, set the content with CSS property with contain=none.

**Comment by krassowski** [comment]
Closing as implemented in https://github.com/jupyterlab/jupyterlab/pull/9382 which was forward-ported in https://github.com/jupyterlab/jupyterlab/pull/10127
