### ISSUE TITLE
Do not refresh codeeditor on update-request

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#9383]
### Problem

While experimenting to find the root cause of the performance issues (https://github.com/jupyterlab/jupyterlab/issues/9279), we have found that the the an `update-request` signal was triggering the editor (code mirror) refresh, see https://github.com/jupyterlab/benchmarks/issues/49#issuecomment-726066068

If we remove that refresh call, we gain significant performance (e..g 7s to load instead of 13s), without apparent user impact

# Proposed Solution

Remove in `codeeditor/src/widget.ts`

```
   protected onUpdateRequest(msg: Message): void {
      if (this.isVisible) {
       this._hasRefreshedSinceAttach = true;
      this.editor.refresh();  
     }
   }
```

prolly `_hasRefreshedSinceAttach` attribute should also be removed.

**Comment by fcollonval** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/11638
