### ISSUE TITLE
Session id concatenated with URL

### ISSUE THREAD

**Issue by tirumerla** [jupyterlab/jupyterlab#9387]
## Description
Hi,

When using jupyterlab inspecting the flow on the browser reveals that the `auth token` is passed along with `session id` within URL `https://[HOST_NAME]/hub/user/[USER_NAME]/api/kernels/[TOKEN]/channels?session_id=[TOKEN]` as opposed to headers of the request. This poses security risk as the attacker who can view URL parameters can retrieve this token & inherit the session by using the session id that can allow access to jupyter notebooks.

https://github.com/jupyterlab/jupyterlab/blob/9ddc7853beddcd8d5a01901c881afdc7f4471ade/packages/services/src/kernel/default.ts#L1216

## Proposed Solution

- Pass session id & token in request headers as opposed to concatenating with URL 
or 
- Send sensitive data and parameters as part of the request body (POST method) 

## Expected behavior

- URL shouldn't have any sensitive information concatenated. 

## Context

- Environment Details - Jupyterhub running on Amazon EKS

Amazon EKS - `v1.17` 

```
~$ jupyter-lab --version
2.2.6
~$ jupyterhub --version
1.1.0
```
This issue is an extension of #8813 

Appreciate your help.

**Comment by jasongrout** [comment]
To be clear, we have an auth token and separately a client session id, right? I believe the auth token was taken out of the url in #8835, so we're just talking about the session_id url parameter, not the authentication token (fixed in #8835), right?

I believe this client session_id parameter is an informational identifier, not something used for security, but of course it would be good to check.

**Comment by tirumerla** [comment]
> To be clear, we have an auth token and separately a client session id, right? I believe the auth token was taken out of the url in #8835, so we're just talking about the session_id url parameter, not the authentication token (fixed in #8835), right?

If i have the url `ws://localhost:8000/user/johndoe/api/kernels/85c81fd7-72e1-49d5-a396-945c3dff5881/channels?session_id=08251f50-e9cb-4ee9-9937-1cc454085ce9`. I assume `85c81fd7-72e1-49d5-a396-945c3dff5881` is unique identifier for that user but not token in anyway or not "sensitive" correct? If that is the case we are just talking about session_id url parameter.

**Comment by jasongrout** [comment]
> `85c81fd7-72e1-49d5-a396-945c3dff5881`

That is a unique identifier for the kernel, just telling you what kernel the websocket is connected to.

The session_id is unique to a user, but is informational, i.e., (if I recall correctly) no authentication is done with it in the server.

**Comment by jasongrout** [comment]
> (if I recall correctly) no authentication is done with it in the server.

It's used here, after authentication is done: https://github.com/jupyter-server/jupyter_server/blob/d1cb381195cacb82de530e57f0f8bebed07bf518/jupyter_server/base/zmqhandlers.py#L268-L269

**Comment by tirumerla** [comment]
Got it. Thanks @jasongrout for the information. I validated a test on my end trying to hijack a session with the session_id i get `403: forbidden`.  I will close this ticket for now and open a new ticket if i encounter any other issues from my other tests.

Appreciate all your help.

**Comment by jasongrout** [comment]
Great, thanks for checking this!
