### ISSUE TITLE
Autocomplete path shows root directory for folders ending with +

### ISSUE THREAD

**Issue by nspiller** [jupyterlab/jupyterlab#9396]
## Description
Autocompleting a path in a python string (tab completion) does not work if the "parent" directory ends with a plus (`+`) sign. Then, the suggestion starts at the root directory (`/`).

## Reproduce

1. create folder: `mkdir ~/test+`
2. create file: `touch ~/test+/test_file`
3. try to autocomplete in jupyter lab: `s = '~/test+/`
4. suggested files/folders is the content of `/` not of `~/test+/`

## Expected behavior
Autocompletion should suggest contents of `~/test+`

## Context

- Operating System and version: 18.04.1-Ubuntu
- Browser and version: Firefox 83.0 (64-bit)
- JupyterLab version: 2.2.8

**Comment by jasongrout** [comment]
This is an issue with the ipython kernel, not JupyterLab. Can you file the issue at https://github.com/ipython/ipython/?

Thanks!

**Comment by jasongrout** [comment]
(You can test this by seeing if you have the same problem when just launching `ipython` straight from the terminal.)
