### ISSUE TITLE
error occured when pip install -e . after an extension project created

### ISSUE THREAD

**Issue by levi-li-yi** [jupyterlab/jupyterlab#9401]
## Description

hi,

I was developing an jupyterlab extension.  I followed the guideline to create an extension project, and initialized the project from a cookiecutter using "cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts". After I ran "pip install -e . ", the error happened. 

In fact, before 3 weeks I was working on a similar task, everything was well. Also, I didn't change my environment recently.

## Reproduce

1. run command : cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts
2. change to the directory the cookiecutter created
3. pip install -e . 
4. See the error 

Installing collected packages: jupyterlab-publishappsvc
  Running setup.py develop for jupyterlab-publishappsvc
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\liyi\Miniconda3\envs\jupyterlab-ext\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\sinux_project\\ML_Jupyter_Plugin\\jupyterlab-publishappsvc\\setup.py'"'"'; __file__='"'"'D:\\sinux_project\\ML_Jupyter_Plugin\\jupyterlab-publishappsvc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: D:\sinux_project\ML_Jupyter_Plugin\jupyterlab-publishappsvc\
    Complete output (52 lines):
    running develop
    running jsdeps
    > jlpm run build:all
    yarn run v1.21.1
    $ jlpm run build:labextension
    $ cd jupyterlab_publishappsvc && rimraf labextension && mkdirp labextension && cd labextension && npm pack ../..
    npm ERR! code 1
    npm ERR! path D:/sinux_project/ML_Jupyter_Plugin/jupyterlab-publishappsvc
    npm ERR! command failed
    npm ERR! command C:\Windows\system32\cmd.exe /d /s /c "jlpm run clean && jlpm run build"
    npm ERR! $ jlpm run clean:lib
    npm ERR! info If you think this is a bug, please open a bug report with the information provided in "D:\\sinux_project\\ML_Jupyter_Plugin\\jupyterlab-publishappsvc\\yarn-error.log".
    npm ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    npm ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    npm ERR! error An unexpected error occurred: "Cannot create property 'module' on string '{\"module\":\"C:\\\\Users\\\\liyi\\\\.npm-init.js\"}'".
    npm ERR! error Command failed with exit code 1.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\liyi\AppData\Local\npm-cache\_logs\2020-11-26T01_16_24_056Z-debug.log
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\sinux_project\ML_Jupyter_Plugin\jupyterlab-publishappsvc\setup.py", line 85, in <module>
        setuptools.setup(**setup_args)
      File "C:\Users\liyi\AppData\Local\Temp\pip-build-env-fyh4a64d\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\liyi\Miniconda3\envs\jupyterlab-ext\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\liyi\Miniconda3\envs\jupyterlab-ext\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\liyi\Miniconda3\envs\jupyterlab-ext\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\liyi\AppData\Local\Temp\pip-build-env-fyh4a64d\overlay\Lib\site-packages\jupyter_packaging\setupbase.py", line 466, in run
        [self.run_command(cmd) for cmd in cmds]
      File "C:\Users\liyi\AppData\Local\Temp\pip-build-env-fyh4a64d\overlay\Lib\site-packages\jupyter_packaging\setupbase.py", line 466, in <listcomp>
        [self.run_command(cmd) for cmd in cmds]
      File "C:\Users\liyi\Miniconda3\envs\jupyterlab-ext\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\liyi\Miniconda3\envs\jupyterlab-ext\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\liyi\AppData\Local\Temp\pip-build-env-fyh4a64d\overlay\Lib\site-packages\jupyter_packaging\setupbase.py", line 261, in run
        c.run()
      File "C:\Users\liyi\AppData\Local\Temp\pip-build-env-fyh4a64d\overlay\Lib\site-packages\jupyter_packaging\setupbase.py", line 367, in run
        run(npm_cmd + ['run', build_cmd], cwd=node_package)
      File "C:\Users\liyi\AppData\Local\Temp\pip-build-env-fyh4a64d\overlay\Lib\site-packages\jupyter_packaging\setupbase.py", line 212, in run
        return subprocess.check_call(cmd, **kwargs)
      File "C:\Users\liyi\Miniconda3\envs\jupyterlab-ext\lib\subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\users\\liyi\\appdata\\local\\temp\\pip-build-env-fyh4a64d\\overlay\\scripts\\jlpm.exe', 'run', 'build:all']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\liyi\Miniconda3\envs\jupyterlab-ext\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\sinux_project\\ML_Jupyter_Plugin\\jupyterlab-publishappsvc\\setup.py'"'"'; __file__='"'"'D:\\sinux_project\\ML_Jupyter_Plugin\\jupyterlab-publishappsvc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

![image](https://user-images.githubusercontent.com/39943001/100329469-a8839780-3008-11eb-8bb1-12b268ffddbf.png)

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome 58
- JupyterLab version: 2.2.9

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by rohithGoudM** [comment]
Hi @levi-li-yi,

I'm receiving a similar error:
` Command '['C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-build-env-sidk851e\\overlay\\Scripts\\jlpm.EXE', 'install']' returned non-zero exit status 1`

Did you get any closure on your issue? If yes, it might help resolve mine too.

**Comment by jtpio** [comment]
@levi-li-yi just checking if you were able to give this another try and whether you are still seeing the issue?

An alternative could be to use the extension template instead of the cookiecutter, as advertised in the extension tutorial: https://jupyterlab.readthedocs.io/en/latest/extension/extension_tutorial.html
