### ISSUE TITLE
Widgets not shown latest release (3.0.0rc10)

### ISSUE THREAD

**Issue by cvanelteren** [jupyterlab/jupyterlab#9403]
## Description
Plots are not visible for `plotly` && `ipycytoscape`
Edit:
They do work under normal `notebook` mode.

## Reproduce

```python
from plotly import graph_objects as go
go.Figure().show()
```
No error produced.

## Expected behavior
Show the widget

## Context

```
jupyter core     : 4.7.0
jupyter-notebook : 6.1.5
qtconsole        : not installed
ipython          : 7.19.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 3.0.0rc10
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5
```
<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
These packages have not been updated to the 3.0 prerelease yet, so this is expected right now.

**Comment by cvanelteren** [comment]
Yeah that's the thing, they are also broken on `2.x` releases..

**Comment by cvanelteren** [comment]
In particular I tested `2.0`/`2.2.8`/`2.2.9`/`3.0.0rc10`. For versions `2.0 < x < 3.0x` I get `loading widget...`. Under normal notebook mode the widgets work normally, is there a qualitative difference with how `jupyterlab` handles the widgets?

**Comment by jasongrout** [comment]
Do the standard widgets work? `import ipywidgets; ipywidgets.IntSlider()`?

Did you install the jlab ipywidgets extension? https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-the-jupyterlab-extension

* if `ipywidgets` does not work, let's take this up as an ipywidgets issue, so please file it here: https://github.com/jupyter-widgets/ipywidgets (and check to make sure ipywidgets is installed, and the JupyterLab extension is installed as well: https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-the-jupyterlab-extension
* if ipywidgets works, but plotly or ipycytoscape do not, then please file issues in their respective projects.

**Comment by cvanelteren** [comment]
It's the latter. `ipywidgets` works
![image](https://user-images.githubusercontent.com/19485143/100374841-28abfc00-300d-11eb-82c9-7321656a7c4f.png)

I will open an issue on the respective packages, however why do the widgets work under the notebook work, i.e. `localhost:8888/notebook/whatever.ipynb`? Does `lab` use a different protocol?

**Comment by cvanelteren** [comment]
ah ok that will explain it. Thanks! :heart:
