### ISSUE TITLE
report

### ISSUE THREAD

**Issue by HandsomeLuoyang** [jupyterlab/jupyterlab#9406]
{"model":"第二种算法得到的相对变化与条件数一致， 而第一种算法的结果则有过大的变化。 Julia的计算与R的结果类似但不相同。\r\n\r\n※※※※※\r\n\r\n稳定性研究经常用**倒推法**： 设精确结果应该为$y=f(x)$,&nbsp;$x$是输入，&nbsp;$y$是输出。 有误差的结果记作$y^*=f^*(x)$, 设$y^*$等于某个输入$x^*$的精确结果$f(x^*)$， 则$\\| x - x^* \\|$的大小代表了算法的稳定程度,&nbsp;$\\| x-x^* \\|$称为倒推误差，&nbsp;$\\| x - x^* \\| / \\| x \\|$称为倒推相对误差。 如果$\\| x-x^* \\| / \\| x \\|$很小则称算法是倒推稳定的。\r\n\r\n**例2.12 (浮点数加法的倒推误差)&nbsp;**考虑两个大小相近的浮点数加法的倒推稳定性。\r\n\r\n令$f(\\boldsymbol x) = x_1 + x_2$, 则浮点运算结果为f^*(\\boldsymbol x) = \\mbox{fl}( \\mbox{fl}(x_1) + \\mbox{fl}(x_2) )(这里不考虑加法运算本身的误差)， 于是\\begin{align*}\n  f^*(x) =& x_1 + \\delta_1 x_1 + x_2 + x_2 + \\delta_2 x_2 + \\delta_3 (x_1 + x_2) \\\\\n  =& \\left[ x_1 + (\\delta_1 + \\delta_3) x_1 \\right] \n    + \\left[ x_2 + (\\delta_2 + \\delta_3) x_2 \\right] \\\\\n  =& f\\left( (x_1 + (\\delta_1 + \\delta_3) x_1, \\; x_2 + (\\delta_2 + \\delta_3) x_2 )^T \\right)\n\\end{align*}其中$|\\delta_i| \\leq U$,&nbsp;$i=1,2,3$。 倒推相对误差为\\begin{align*}\n  \\frac{\\| \\boldsymbol x^* - \\boldsymbol x \\|}{\\| \\boldsymbol x \\|}\n  =& \\frac{\\| ( (\\delta_1 + \\delta_3) x_1, \\; (\\delta_2 + \\delta_3) x_2 )^T \\|}{\\| \\boldsymbol x \\|}\n  \\leq 2U = \\varepsilon_{\\text{m}} .\n\\end\n据四舍五入到指定有效位数)。 把结果与使用高精度计算的结果比较。\r\n\r\n#### 习题6","view":"第二种算法得到的相对变化与条件数一致， 而第一种算法的结果则有过大的变化。 Julia的计算与R的结果类似但不相同。\n\n※※※※※\n\n稳定性研究经常用**倒推法**： 设精确结果应该为$y=f(x)$,&nbsp;$x$是输入，&nbsp;$y$是输出。 有误差的结果记作$y^*=f^*(x)$, 设$y^*$等于某个输入$x^*$的精确结果$f(x^*)$， 则$\\| x - x^* \\|$的大小代表了算法的稳定程度,&nbsp;$\\| x-x^* \\|$称为倒推误差，&nbsp;$\\| x - x^* \\| / \\| x \\|$称为倒推相对误差。 如果$\\| x-x^* \\| / \\| x \\|$很小则称算法是倒推稳定的。\n\n**例2.12 (浮点数加法的倒推误差)&nbsp;**考虑两个大小相近的浮点数加法的倒推稳定性。\n\n令$f(\\boldsymbol x) = x_1 + x_2$, 则浮点运算结果为f^*(\\boldsymbol x) = \\mbox{fl}( \\mbox{fl}(x_1) + \\mbox{fl}(x_2) )(这里不考虑加法运算本身的误差)， 于是\\begin{align*}\n  f^*(x) =& x_1 + \\delta_1 x_1 + x_2 + x_2 + \\delta_2 x_2 + \\delta_3 (x_1 + x_2) \\\\\n  =& \\left[ x_1 + (\\delta_1 + \\delta_3) x_1 \\right] \n    + \\left[ x_2 + (\\delta_2 + \\delta_3) x_2 \\right] \\\\\n  =& f\\left( (x_1 + (\\delta_1 + \\delta_3) x_1, \\; x_2 + (\\delta_2 + \\delta_3) x_2 )^T \\right)\n\\end{align*}其中$|\\delta_i| \\leq U$,&nbsp;$i=1,2,3$。 倒推相对误差为\\begin{align*}\n  \\frac{\\| \\boldsymbol x^* - \\boldsymbol x \\|}{\\| \\boldsymbol x \\|}\n  =& \\frac{\\| ( (\\delta_1 + \\delta_3) x_1, \\; (\\delta_2 + \\delta_3) x_2 )^T \\|}{\\| \\boldsymbol x \\|}\n  \\leq 2U = \\varepsilon_{\\text{m}} .\n\\end{align*}\n","selections":[{"uuid":"f0ecd6e4-ed24-4d5a-b6da-140a45307240","start":{"line":18,"column":0},"end":{"line":18,"column":0},"style":{"className":"","displayName":"","color":"black"}}],"cursor":{"line":18,"column":0},"lineSep":null,"mode":"text/x-ipythongfm","change":{"from":{"line":17,"ch":12,"sticky":null},"to":{"line":17,"ch":12,"sticky":null},"text":["",""],"origin":"+input","removed":[""]}}

**Comment by jtpio** [comment]
Closing as this appears to be a mistake.

@HandsomeLuoyang feel free to open a new issue if you encountered problems using JupyterLab.
