### ISSUE TITLE
Jupyter Notebook crashes with segmentation fault when trying to execute Python code on macOS Big Sur (new M1 chip)

### ISSUE THREAD

**Issue by juneja2** [jupyterlab/jupyterlab#9408]
>
![Screen Shot 2020-11-28 at 7 07 31 PM](https://user-images.githubusercontent.com/38742950/100530995-c6d6c800-31ad-11eb-856b-fcd04633654e.png)

List of things that I did on the new Mac mini
1. Installed pip3 by using a curl command.
2. Ran the get-pip.py file with python
2. pip3 install notebook
3. Added ~Library/Python/3.8/bin to the /etc/paths directory.
4. Ran command jupyter notebook
5. Navigated to the directory where I wanted the file.
6. Created a Python3 file
7. Renamed the file
8. Wrote a very small program 
    print('Hello world')
9. Got the error

Things done so far
1. Installed XCode Command Line tools for developers or something.
2. Installed X2go client (3rd party software)

**Comment by jasongrout** [comment]
minrk/appnope#7 may be the root cause here. Can you try again in a clean environment (and make sure it uses appnope 0.1.1)?

**Comment by jasongrout** [comment]
> Ran command jupyter notebook

Also, this seems like it is not a Jupyter Lab issue report (which would be the command `jupyter lab`). If it still doesn't work after upgrading appnope, please file the issue with https://github.com/jupyter/notebook/
