### ISSUE TITLE
Validation error when changing text indentation setting through UI

### ISSUE THREAD

**Issue by Abrackadabra** [jupyterlab/jupyterlab#9411]
## Description

Validation error when changing text indentation setting through UI

![image](https://user-images.githubusercontent.com/1352887/100703179-4a0d3f00-33a3-11eb-89b3-672e789a9405.png)

## Reproduce

1. Start a clean install of jupyter lab 2.2.9.
2. Click on Settings > Text Editor Indentation > anything.
3. See error in browser console.

## Expected behavior

No error, settings change applied.

## Context

- Operating System and version: macOS 10.15.7
- Browser and version: Chrome 87.0.4280.67
- JupyterLab version: 2.2.9

<details><summary>Troubleshoot Output</summary>
<pre>
WARNING: You are using pip version 20.2.3; however, version 20.3 is available.
You should consider upgrading via the '/Users/abra/projects/jupyter/.venv/bin/python3 -m pip install --upgrade pip' command.
$PATH:
	/Users/abra/projects/jupyter/.venv/bin
	/Users/abra/brew/bin
	/Users/abra/brew/sbin
	/Users/abra/bin
	/Users/abra/.poetry/bin
	/usr/local/git/current/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/local/sbin
	/usr/sbin
	/sbin
	/Users/abra/brew/bin
	/Library/Apple/usr/bin

sys.path:
	/Users/abra/projects/jupyter/.venv/bin
	/Users/abra/brew/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python39.zip
	/Users/abra/brew/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9
	/Users/abra/brew/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload
	/Users/abra/projects/jupyter/.venv/lib/python3.9/site-packages

sys.executable:
	/Users/abra/projects/jupyter/.venv/bin/python3

sys.version:
	3.9.0 (default, Nov 30 2020, 12:05:44)
	[Clang 11.0.3 (clang-1103.0.32.62)]

platform.platform():
	macOS-10.15.7-x86_64-i386-64bit

which -a jupyter:
	/Users/abra/projects/jupyter/.venv/bin/jupyter

pip list:
	Package             Version
	------------------- ---------
	appnope             0.1.0
	argon2-cffi         20.1.0
	async-generator     1.10
	attrs               20.3.0
	backcall            0.2.0
	bleach              3.2.1
	certifi             2020.11.8
	cffi                1.14.4
	chardet             3.0.4
	decorator           4.4.2
	defusedxml          0.6.0
	entrypoints         0.3
	idna                2.10
	ipykernel           5.3.4
	ipython             7.19.0
	ipython-genutils    0.2.0
	jedi                0.17.2
	Jinja2              2.11.2
	json5               0.9.5
	jsonschema          3.2.0
	jupyter-client      6.1.7
	jupyter-core        4.7.0
	jupyterlab          2.2.9
	jupyterlab-pygments 0.1.2
	jupyterlab-server   1.2.0
	MarkupSafe          1.1.1
	mistune             0.8.4
	nbclient            0.5.1
	nbconvert           6.0.7
	nbformat            5.0.8
	nest-asyncio        1.4.3
	notebook            6.1.5
	packaging           20.7
	pandocfilters       1.4.3
	parso               0.7.1
	pexpect             4.8.0
	pickleshare         0.7.5
	pip                 20.2.3
	prometheus-client   0.9.0
	prompt-toolkit      3.0.8
	ptyprocess          0.6.0
	pycparser           2.20
	Pygments            2.7.2
	pyparsing           2.4.7
	pyrsistent          0.17.3
	python-dateutil     2.8.1
	pyzmq               20.0.0
	requests            2.25.0
	Send2Trash          1.5.0
	setuptools          49.2.1
	six                 1.15.0
	terminado           0.9.1
	testpath            0.4.4
	tornado             6.1
	traitlets           5.0.5
	urllib3             1.22
	wcwidth             0.2.5
	webencodings        0.5.1
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>[D 07:01:33.152 LabApp] Searching ['/Users/abra/projects/jupyter', '/Users/abra/.jupyter', '/Users/abra/projects/jupyter/.venv/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 07:01:33.152 LabApp] Looking for jupyter_config in /etc/jupyter
[D 07:01:33.152 LabApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 07:01:33.152 LabApp] Looking for jupyter_config in /Users/abra/projects/jupyter/.venv/etc/jupyter
[D 07:01:33.153 LabApp] Looking for jupyter_config in /Users/abra/.jupyter
[D 07:01:33.153 LabApp] Looking for jupyter_config in /Users/abra/projects/jupyter
[D 07:01:33.154 LabApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 07:01:33.154 LabApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 07:01:33.154 LabApp] Looking for jupyter_notebook_config in /Users/abra/projects/jupyter/.venv/etc/jupyter
[D 07:01:33.154 LabApp] Looking for jupyter_notebook_config in /Users/abra/.jupyter
[D 07:01:33.154 LabApp] Looking for jupyter_notebook_config in /Users/abra/projects/jupyter
[D 07:01:33.155 LabApp] Raising open file limit: soft 256->4096; hard 9223372036854775807->9223372036854775807
[D 07:01:33.159 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/etc/jupyter/jupyter_notebook_config.json
[D 07:01:33.160 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 07:01:33.160 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/Users/abra/projects/jupyter/.venv/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/Users/abra/projects/jupyter/.venv/etc/jupyter/jupyter_notebook_config.json
[D 07:01:33.162 LabApp] Paths used for configuration of jupyter_notebook_config:
    	/Users/abra/.jupyter/jupyter_notebook_config.json
[I 07:01:33.742 LabApp] JupyterLab extension loaded from /Users/abra/projects/jupyter/.venv/lib/python3.9/site-packages/jupyterlab
[I 07:01:33.742 LabApp] JupyterLab application directory is /Users/abra/projects/jupyter/.venv/share/jupyter/lab
[I 07:01:33.748 LabApp] Serving notebooks from local directory: /Users/abra/projects/jupyter
[I 07:01:33.748 LabApp] Jupyter Notebook 6.1.5 is running at:
[I 07:01:33.748 LabApp] http://localhost:8888/?token=3ea7516e117376ffbb90a9ca9194e8383f49ed42d8196b95
[I 07:01:33.748 LabApp]  or http://127.0.0.1:8888/?token=3ea7516e117376ffbb90a9ca9194e8383f49ed42d8196b95
[I 07:01:33.748 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 07:01:33.757 LabApp]

    To access the notebook, open this file in a browser:
        file:///Users/abra/Library/Jupyter/runtime/nbserver-64807-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=3ea7516e117376ffbb90a9ca9194e8383f49ed42d8196b95
     or http://127.0.0.1:8888/?token=3ea7516e117376ffbb90a9ca9194e8383f49ed42d8196b95
[D 07:01:35.079 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:35.082 LabApp] Using contents: services/contents
[D 07:01:35.088 LabApp] 200 GET /lab?token=3ea7516e117376ffbb90a9ca9194e8383f49ed42d8196b95 (::1) 8.96ms
[D 07:01:35.312 LabApp] Path main.f8135314e37a20e33940.js served from /Users/abra/projects/jupyter/.venv/share/jupyter/lab/static/main.f8135314e37a20e33940.js
[D 07:01:35.313 LabApp] 304 GET /static/lab/main.f8135314e37a20e33940.js (::1) 1.32ms
[D 07:01:35.329 LabApp] Path vendors~main.e39d4a65a871fe1cc8fa.js served from /Users/abra/projects/jupyter/.venv/share/jupyter/lab/static/vendors~main.e39d4a65a871fe1cc8fa.js
[D 07:01:35.329 LabApp] 304 GET /static/lab/vendors~main.e39d4a65a871fe1cc8fa.js (::1) 0.99ms
[D 07:01:35.701 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:35.702 LabApp] Found kernel python3 in /Users/abra/projects/jupyter/.venv/share/jupyter/kernels
[D 07:01:35.706 LabApp] 200 GET /api/kernelspecs?1606802495696 (::1) 5.65ms
[D 07:01:36.368 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:36.400 LabApp] 200 GET /lab/api/settings?1606802495722 (::1) 33.02ms
[D 07:01:36.401 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:36.402 LabApp] 200 GET /api/kernels?1606802495744 (::1) 1.35ms
[D 07:01:36.403 LabApp] Using contents: services/contents
[D 07:01:36.407 LabApp] 200 GET /lab/workspaces/auto-9?clone (::1) 5.57ms
[D 07:01:37.062 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:37.064 LabApp] 200 GET /api/sessions?1606802495745 (::1) 1.64ms
[D 07:01:37.064 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:37.065 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:37.066 LabApp] 200 GET /api/terminals?1606802495746 (::1) 1.50ms
[D 07:01:37.066 LabApp] Found kernel python3 in /Users/abra/projects/jupyter/.venv/share/jupyter/kernels
[D 07:01:37.067 LabApp] 200 GET /api/kernelspecs?1606802495913 (::1) 2.16ms
[D 07:01:37.386 LabApp] 304 GET /static/lab/main.f8135314e37a20e33940.js (::1) 0.81ms
[D 07:01:37.437 LabApp] 304 GET /static/lab/vendors~main.e39d4a65a871fe1cc8fa.js (::1) 1.38ms
[D 07:01:37.764 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:37.764 LabApp] Found kernel python3 in /Users/abra/projects/jupyter/.venv/share/jupyter/kernels
[D 07:01:37.765 LabApp] 200 GET /api/kernelspecs?1606802497745 (::1) 1.57ms
[D 07:01:38.505 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:38.534 LabApp] 200 GET /lab/api/settings?1606802497768 (::1) 28.81ms
[D 07:01:38.535 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:38.536 LabApp] 200 GET /api/kernels?1606802497794 (::1) 1.24ms
[D 07:01:38.537 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:38.537 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:38.538 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:38.538 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:38.539 LabApp] 200 GET /api/sessions?1606802497795 (::1) 2.40ms
[D 07:01:38.539 LabApp] 200 GET /api/terminals?1606802497796 (::1) 2.22ms
[D 07:01:38.540 LabApp] Found kernel python3 in /Users/abra/projects/jupyter/.venv/share/jupyter/kernels
[D 07:01:38.541 LabApp] 200 GET /api/kernelspecs?1606802497885 (::1) 3.10ms
[D 07:01:38.609 LabApp] Node v15.3.0

[D 07:01:38.633 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:38.893 LabApp] Yarn configuration loaded.
[D 07:01:39.034 LabApp] 200 GET /api/nbconvert?1606802498625 (::1) 401.33ms
[I 07:01:39.034 LabApp] Build is up to date
[D 07:01:39.035 LabApp] 200 GET /lab/api/build?1606802498044 (::1) 496.46ms
[D 07:01:39.035 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:39.036 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:39.036 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:39.274 LabApp] 200 GET /api/nbconvert?1606802498652 (::1) 238.89ms
[D 07:01:39.277 LabApp] 200 GET /metrics?1606802498693 (::1) 241.16ms
[D 07:01:39.277 LabApp] 200 GET /lab/api/listings/@jupyterlab/extensionmanager-extension/listings.json?1606802498823 (::1) 241.07ms
[D 07:01:39.278 LabApp] Path @jupyterlab/theme-light-extension/index.css served from /Users/abra/projects/jupyter/.venv/share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.css
[D 07:01:39.278 LabApp] 304 GET /lab/api/themes/@jupyterlab/theme-light-extension/index.css (::1) 241.41ms
[D 07:01:39.279 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:39.282 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1606802498896 (::1) 2.66ms
[D 07:01:39.283 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:39.283 LabApp] 200 GET /lab/api/workspaces/lab?1606802498850 (::1) 1.16ms
[D 07:01:39.292 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:39.551 LabApp] Yarn configuration loaded.
[D 07:01:39.554 LabApp] 200 GET /lab/api/extensions?1606802499282 (::1) 262.00ms
[D 07:01:39.555 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:39.556 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:39.560 LabApp] 200 GET /metrics?1606802499288 (::1) 5.40ms
[D 07:01:39.585 LabApp] 200 GET /lab/api/settings?1606802499312 (::1) 29.13ms
[D 07:01:39.843 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:39.844 LabApp] 204 PUT /lab/api/workspaces/lab/workspaces/auto-9?1606802499838 (::1) 1.14ms
[D 07:01:40.483 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:40.490 LabApp] 200 GET /api/contents?content=1&1606802499871 (::1) 7.72ms
[D 07:01:40.491 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:40.492 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:40.496 LabApp] 200 GET /metrics?1606802500042 (::1) 5.00ms
[D 07:01:40.498 LabApp] 200 GET /lab/api/extensions?1606802500287 (::1) 6.44ms
[D 07:01:40.526 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:40.527 LabApp] 204 PUT /lab/api/workspaces/lab/workspaces/auto-9?1606802500504 (::1) 1.40ms
[D 07:01:44.693 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:44.697 LabApp] 200 GET /metrics?1606802504685 (::1) 4.75ms
[D 07:01:48.713 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:48.713 LabApp] 200 GET /api/kernels?1606802508703 (::1) 1.01ms
[D 07:01:48.714 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:48.715 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:48.715 LabApp] 200 GET /api/sessions?1606802508705 (::1) 1.32ms
[D 07:01:48.716 LabApp] 200 GET /api/terminals?1606802508706 (::1) 1.18ms
[D 07:01:50.536 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:50.541 LabApp] 200 GET /api/contents?content=1&1606802510529 (::1) 5.72ms
[D 07:01:53.641 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:53.645 LabApp] 200 GET /metrics?1606802513633 (::1) 4.85ms
[D 07:01:58.731 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:58.732 LabApp] 200 GET /api/kernels?1606802518722 (::1) 0.98ms
[D 07:01:58.733 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:58.733 LabApp] Accepting token-authenticated connection from ::1
[D 07:01:58.734 LabApp] 200 GET /api/sessions?1606802518723 (::1) 1.32ms
[D 07:01:58.734 LabApp] 200 GET /api/terminals?1606802518725 (::1) 1.13ms
[D 07:02:00.555 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:00.560 LabApp] 200 GET /api/contents?content=1&1606802520549 (::1) 5.39ms
[D 07:02:05.994 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:05.999 LabApp] 200 GET /metrics?1606802525989 (::1) 5.19ms
[D 07:02:08.744 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:08.745 LabApp] 200 GET /api/kernels?1606802528735 (::1) 1.09ms
[D 07:02:08.746 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:08.747 LabApp] 200 GET /api/sessions?1606802528738 (::1) 0.84ms
[D 07:02:08.747 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:08.748 LabApp] 200 GET /api/terminals?1606802528739 (::1) 0.69ms
[D 07:02:10.572 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:10.578 LabApp] 200 GET /api/contents?content=1&1606802530565 (::1) 5.74ms
[D 07:02:18.761 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:18.762 LabApp] 200 GET /api/kernels?1606802538752 (::1) 1.21ms
[D 07:02:18.763 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:18.764 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:18.765 LabApp] 200 GET /api/sessions?1606802538753 (::1) 1.70ms
[D 07:02:18.765 LabApp] 200 GET /api/terminals?1606802538753 (::1) 1.58ms
[D 07:02:18.792 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:18.797 LabApp] 200 GET /metrics?1606802538786 (::1) 5.99ms
[D 07:02:20.591 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:20.596 LabApp] 200 GET /api/contents?content=1&1606802540584 (::1) 4.72ms
[D 07:02:28.779 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:28.780 LabApp] 200 GET /api/kernels?1606802548770 (::1) 1.02ms
[D 07:02:28.781 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:28.781 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:28.782 LabApp] 200 GET /api/sessions?1606802548772 (::1) 1.82ms
[D 07:02:28.783 LabApp] 200 GET /api/terminals?1606802548772 (::1) 1.78ms
[D 07:02:30.607 LabApp] Accepting token-authenticated connection from ::1
[D 07:02:30.612 LabApp] 200 GET /api/contents?content=1&1606802550602 (::1) 5.28ms
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
vendors~main.e39d4a65a871fe1cc8fa.js:2 @jupyterlab/fileeditor-extension:plugin validation errors: Array(1)0: dataPath: ".editorConfig"keyword: "additionalProperties"message: "should NOT have additional properties"params: additionalProperty: "handlePaste"__proto__: ObjectschemaPath: "#/definitions/editorConfig/additionalProperties"__proto__: Objectlength: 1__proto__: Array(0)
_save @ vendors~main.e39d4a65a871fe1cc8fa.js:2
vendors~main.e39d4a65a871fe1cc8fa.js:2 Failed to set @jupyterlab/fileeditor-extension:plugin: @jupyterlab/fileeditor-extension:plugin failed to validate; check console.
(anonymous) @ vendors~main.e39d4a65a871fe1cc8fa.js:2
</pre>
</details>

**Comment by ValentinB10** [comment]
I have the exact same error using JupyterLab in version 2.3.1.

It seems that an invalid property is added to the settings. If I remove the handlePaste property, the text indentation is applied but when I reapply a new text indentation though UI, it breaks again.

![Capture d’écran de 2021-04-10 20-30-16](https://user-images.githubusercontent.com/58490749/114280952-f17a3c80-9a3b-11eb-8c8c-9fbe3a6007f4.png)
