### ISSUE TITLE
Options to use the client renderer only

### ISSUE THREAD

**Issue by erhild** [jupyterlab/jupyterlab#9415]
Hello is there a way to just use the client of jupyter as renderer without the jupyter server, then use it on another website as a feature. in my case, I would like to use it inside my nuxt application to render ipynb, markdown, or other text files.
Thanks

**Comment by jasongrout** [comment]
Absolutely. Feel free to use any of the `@jupyterlab` packages (in the `packages/` directory) however you want. We tried to build them as reusable javascript modules.

**Comment by jasongrout** [comment]
See the notebook and other examples in the `examples` directory for some examples of how to use components.

**Comment by jasongrout** [comment]
Closing as answered, but feel free to continue the discussion if you like.

**Comment by erhild** [comment]
Thanks for the answer, I have tried to build a separate project that contains notebook only and it works. But still confused about how to just use the client only without the jupyter server.
