### ISSUE TITLE
Decrease yarn timeout

### ISSUE THREAD

**Issue by orangelynx** [jupyterlab/jupyterlab#9418]
## Problem Description

When the network is not configured correctly on the machine (in my case a corporate proxy), the yarn install will idle for **277 hours** before aborting, which is very unhelpful.

https://github.com/jupyterlab/jupyterlab/blob/master/jupyterlab/staging/.yarnrc

**Comment by jasongrout** [comment]
That does indeed seem unreasonable. Can you submit a PR changing it?

**Comment by orangelynx** [comment]
I lack experience on what a suitable timeout might be. If the repository usually experiences high load, a timeout in the < 10 minute range might be in order, otherwise a couple of seconds should be sufficient.

**Comment by jasongrout** [comment]
Looks like from https://github.com/jupyterlab/jupyterlab/pull/8104 and the issue it fixed it was supposed to be 100 seconds. Did we make a mistake in the units?

**Comment by jasongrout** [comment]
Looks like it is actually 1000 seconds currently, right?

**Comment by orangelynx** [comment]
Not sure, I found contradicting information on this. But then again I didn't find the original issue that warranted the increase (even though I literally entered "yarn" and "timeout" into the issue search as keywords).

I think it should be miliseconds, so 1000 seconds right now, which is still rather high (16 minutes).

**Comment by jasongrout** [comment]
FYI, I found the issue by looking at the file you linked, clicking the history button to see the commits affecting the file, then following the link to the pr that contained the commit.
