### ISSUE TITLE
Debugger variables view mode UI

### ISSUE THREAD

**Issue by karlaspuldaro** [jupyterlab/jupyterlab#9425]
### Problem
The current debugger UI allows variables display to toggle between table and tree views.
Maybe a toggle-switch may not be the best UI approach, as it implies on/off behaviour. Even though there are only 2 view modes to choose, the switch button purpose is only clarified on a mouse hover label `Table/Tree view`.

![debugger](https://user-images.githubusercontent.com/25207344/101084818-81831380-357c-11eb-9307-edf993bc637f.gif)

### Proposed Solution
My suggestion would be using a button with an icon, giving the user a more clear visual understanding of its purpose.
An example would be the file browser view mode buttons on mac

![Screen Shot 2020-12-03 at 1 35 49 PM](https://user-images.githubusercontent.com/25207344/101086456-df185f80-357e-11eb-963d-f603abdfd3a3.png)

Either something like this where current view mode is highlighted, or, 
keeping one button on display which on click switches the label & icon

![image](https://user-images.githubusercontent.com/25207344/101088359-96ae7100-3581-11eb-8a6f-228de72cc1d0.png)

Would like to hear more thoughts about this :)

**Comment by jtpio** [comment]
Thanks @karlaspuldaro!

> Maybe a toggle-switch may not be the best UI approach, as it implies on/off behaviour.

Agree. I think the reason there is a switch to toggle between the table and the tree views is because it was reused from the one in the toolbar.

> Either something like this where current view mode is highlighted, or,
keeping one button on display which on click switches the label & icon

Having these icons instead sounds like a better alternative :+1: Would you like to open a PR so it can be tested out?

**Comment by karlaspuldaro** [comment]
Thanks @jtpio for the feedback. Yes, I can definitely start implementing this idea for testing :)

**Comment by jtpio** [comment]
Nice, thanks!

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlab/jupyterlab/pull/9502, thanks @karlaspuldaro!
