### ISSUE TITLE
Let a console cell react on a console state change

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#943]
It would be nice if:
- `ConsoleContent` has means to signal about changes, e.g. via an observable list of cell widgets as the notebook does
- `ConsoleContent` is passed as a context to `IRenderer` to construct new cells, e.g. to let a cell react on console state changes

**Comment by akosyakov** [comment]
Could I propose a PR if it makes sense to you?

**Comment by ellisonbg** [comment]
I think this sounds reasonable, but what usage case you thinking of?

**Comment by akosyakov** [comment]
@ellisonbg in our case behaviour of a cell depends on a cell position relatively to other cells, e.g. proposals in cell 3 depends on content of cells 1 and 2, and if a position has been changed we have to update our models

Generally it would be nice if `ConsoleContent` has explicit representation of an underlying model, regardless of widget composition.
