### ISSUE TITLE
"bail" will still exit webpack when the first error is found.

### ISSUE THREAD

**Issue by echarles** [jupyterlab/jupyterlab#9435]
## Description

Develop extensions in watch mode, (terminal 1: `jlpm watch`- terminal 2: jupyter lab --dev-mode --watch -extensions-in-dev-mode`).

Terminal 2 logs a warning at launch : `You are using "bail" with "watch". "bail" will still exit webpack when the first error is found.`

When the extension compilation breaks (eg. because the developer has made a type), terminal 1 compilation fails but at some point recovers if the developer fixes the issues.

However, in terminal 2, watch mode is no more working after the first terminal 1 failure, and the developer has no other choice that restarting his terminal 2 process, which is not what he wants (he just want watch to continue).

**Comment by echarles** [comment]
@jasongrout I have tagged this issue wit Milestone 3.0. This can be moved to 3.1 if we think we should not consider that for now. An easy fix would be to replace `bail` with `watch`(working for me), but there may be a reason to use `bail`?

**Comment by jasongrout** [comment]
Moving this to 3.1 since it is not a blocker. If someone fixes it soon, great, we'll merge it. Thanks!

**Comment by jasongrout** [comment]
Comment from the dev meeting is that this is a reasonable fix.

**Comment by echarles** [comment]
Thx @jasongrout for the feedback. I have just opened https://github.com/jupyterlab/jupyterlab/pull/9450 to fix this.
