### ISSUE TITLE
Increasing font size is not respected in currently open code editor

### ISSUE THREAD

**Issue by vadimkantorov** [jupyterlab/jupyterlab#9438]
Probably a dupe of https://github.com/jupyterlab/jupyterlab/issues/7909 (unfortunately both the issue and the PR are blocked for new comments), but in jlab version 2.2.9.

When I open a new code editor, the new settings are reflected, but not in the currently open ones

**Comment by raffaem** [comment]
To increase code editor font size: Settings -> JupyterLab Theme -> Increase code font size

I don't know what Settings->Increase Text Editor Font Size does

**Comment by JasonWeill** [comment]
Still an issue; closing in favor of #16182.
