### ISSUE TITLE
disabledExtensions are interpreted as strings and as regexes

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9455]
In https://github.com/jupyterlab/jupyterlab/blob/2bf9ba8a633117d68004e800a1e7b354860e1149/packages/coreutils/src/pageconfig.ts#L308-L310 and https://github.com/jupyterlab/jupyterlab/blob/2bf9ba8a633117d68004e800a1e7b354860e1149/packages/coreutils/src/pageconfig.ts#L317-L319, we see that a plugin is disabled (or deferred) if the string given in the corresponding config either matches exactly *or* is a regex that matches the plugin id.

I think this is a mistake to conflate raw strings and strings that are meant to be interpreted as regexes. The simplicity we offer by treating the strings as raw strings that are compared exactly is illusionary since if that raw string contains a character special to regexes (like `.`), it would unintentionally match more. For example, if a package has two plugins `mypackage:my.plugin` and `mypackage:myAplugin`, you cannot disable `mypackage:my.plugin` as an exact string because it would also match `mypackage:myAplugin`. Also, if there is a plugin `mypackage:pluginA` and another extension `pluginA`, you cannot disable extension `pluginA` using an exact string without also disabling `mypackage:pluginA`.

In general, I think the user should be explicit about which strings should be treated as raw strings that are matched exactly, and which strings should be treated as regexes. They do not have that capability in our current extension disable or defer configuration.

(Caveat: I haven't tested these cases above yet - just reasoned through the logic in the code)

**Comment by jasongrout** [comment]
An easy way out of this is to consider all of these things regexes only - then there is no ambiguity, and most people will still be able to just treat it as a string (though likely will want to use `^` and `$` to anchor the string).

**Comment by jasongrout** [comment]
Another way out is for regex matches to be specified as objects, perhaps with the default of a string being a raw string: `disabledExtensions: [{match: '^packageA', type: 'regex'}, {match: 'packageB', type: 'string'}, 'packageC']` would match `packageC` and `packageB` as raw strings, and `^packageA` as a regex, for example.

**Comment by jasongrout** [comment]
Since this would be a breaking change, I set this as 3.0 for a quick discussion if we want to do something about this in 3.0. If not (because we are so close to 3.0), then we can bump it to 4.0.

**Comment by vidartf** [comment]
My suggestions would just to drop the regex support, and just support `*` wildcards (matches 0 or more characters).

**Comment by jasongrout** [comment]
> My suggestions would just to drop the regex support, and just support `*` wildcards (matches 0 or more characters).

I like that idea, I think it's a really nice compromise between having a simple default (exact string match) that gives a lot of the common usecase of regex (i.e., `*`)

**Comment by jasongrout** [comment]
I think I would suggest using https://www.npmjs.com/package/minimatch to do the glob matching.
