### ISSUE TITLE
Extension Compatibility with 3.0

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#9461]
When 3.0 lands I'd like to hit the ground running, but to really make use of it I need at least a minimal set of extensions to be compatible. 

I've found understanding which extensions are compatible with 3.0 to be a bit difficult to understand due to there being no central catalogue so I've compiled the below list which I'll endeavour to keep up to date (as time allows). This is just a best efforts basis and I make no claim that the information is correct or up-to-date, but if anyone comments here with updated or new information I'll include it in the table below.

----

<br>

Extension | PR | Compatible Version
-- | -- | --
https://github.com/jupyter-widgets/ipywidgets         | jupyter-widgets/ipywidgets#2973        | [(`7.6`)](https://ipywidgets.readthedocs.io/en/stable/changelog.html#id1)
https://github.com/jupyter-widgets/ipyleaflet         | jupyter-widgets/ipyleaflet#714         | [(`0.13.5`)](https://github.com/jupyter-widgets/ipyleaflet/releases/tag/0.13.5)
https://github.com/jupyter-widgets/jupyterlab-sidecar | jupyter-widgets/jupyterlab-sidecar#58  | [(`0.5.0`)](https://github.com/jupyter-widgets/jupyterlab-sidecar/releases/tag/0.5.0)
https://github.com/plotly/plotly.py                   | plotly/plotly.py#3016                  | [(`4.14.3`)](https://github.com/plotly/plotly.py/releases/tag/v4.14.3) - source<br>[(`5.0.0`)](https://github.com/plotly/plotly.py/releases/tag/v5.0.0) - prebuilt
https://github.com/plotly/jupyterlab-chart-editor     | plotly/jupyterlab-chart-editor#53      | [(`4.14.3`)](https://github.com/plotly/jupyterlab-chart-editor/releases/tag/v4.14.3)
https://github.com/bokeh/jupyter_bokeh                | bokeh/jupyter_bokeh#120                | [(`3.0.0`)](https://github.com/bokeh/jupyter_bokeh/releases/tag/3.0.1)
https://github.com/matplotlib/ipympl                  | matplotlib/ipympl#272                  | [(`0.6.1`)](https://github.com/matplotlib/ipympl/releases)
https://github.com/jupyterlab/jupyterlab-git          | jupyterlab/jupyterlab-git#818          | [(`0.30.0`)](https://github.com/jupyterlab/jupyterlab-git/releases/tag/v0.30.0)
https://github.com/jupyterlab/jupyter-renderers       | jupyterlab/jupyter-renderers#232, jupyterlab/jupyter-renderers#233       | <table><tr><td>fasta-extension</td><td>3.0.0</td></tr><tr><td>geojson-extension</td><td>3.0.0</td></tr><tr><td>katex-extension</td><td>3.0.0</td></tr><tr><td>mathjax3-extension</td><td>4.0.0</td></tr><tr><td>vega2-extension</td><td>3.0.0</td></tr><tr><td>vega3-extension</td><td>3.0.0</td></tr></table>
https://github.com/jupyterlab/jupyterlab-github       | jupyterlab/jupyterlab-github#112       | [(`3.0.1`)](https://github.com/jupyterlab/jupyterlab-github/releases/tag/v3.0.1) - prebuilt
https://github.com/jupyterlab/jupyterlab-latex        | jupyterlab/jupyterlab-latex#154        | [(`3.0.0`)](https://github.com/jupyterlab/jupyterlab-latex/releases/tag/3.0.0) - source<br>[(`3.1.0`)](https://github.com/jupyterlab/jupyterlab-latex/releases/tag/3.1.0) - prebuilt
https://github.com/jupyter/nbdime                     | jupyter/nbdime#551                     | beta
https://github.com/jupyter-lsp/jupyterlab-lsp          | jupyter-lsp/jupyterlab-lsp#452          | [(`3.0.0`)](https://github.com/jupyter-lsp/jupyterlab-lsp/releases/tag/v3.0.0)
https://github.com/dask/dask-labextension             | dask/dask-labextension#162             | [(`5.0.0`)](https://github.com/dask/dask-labextension/releases/tag/5.0.0)
https://github.com/bqplot/bqplot                      | bqplot/bqplot#1222                     | [(`0.12.22`)](https://github.com/bqplot/bqplot/releases/tag/0.12.22)
https://github.com/jtpio/jupyterlab-system-monitor    | jtpio/jupyterlab-system-monitor#49     | [(`0.7.0`)](https://github.com/jtpio/jupyterlab-system-monitor/releases/tag/0.7.0)
https://github.com/jtpio/ipylab                       | jtpio/ipylab#51                        | [(`0.4.1`)](https://github.com/jtpio/ipylab/releases/tag/0.4.1)
https://github.com/jpmorganchase/jupyter-fs           | jpmorganchase/jupyter-fs#75            | [(`0.3.1final0`)](https://github.com/jpmorganchase/jupyter-fs/releases/tag/v0.3.1final0)
https://github.com/jpmorganchase/nbcelltests          | jpmorganchase/nbcelltests#215          | N
https://github.com/jpmorganchase/ipyregulartable      | jpmorganchase/ipyregulartable#33       | [(`0.2.0`)](https://github.com/jpmorganchase/ipyregulartable/releases/tag/v0.2.0)
https://github.com/jpmorganchase/jupyterlab_templates | jpmorganchase/jupyterlab_templates#104 | [(`0.3.0`)](https://github.com/jpmorganchase/jupyterlab_templates/releases/tag/v0.3.0)
https://github.com/finos/perspective                  | finos/perspective#1269                 | [(`0.6.2`)](https://github.com/finos/perspective/releases/tag/v0.6.2)
https://github.com/holoviz/pyviz_comms                | holoviz/pyviz_comms#72                 |[(`2.0.1`)](https://github.com/holoviz/pyviz_comms/releases/tag/v2.0.1)
https://github.com/QuantStack/jupyterlab-drawio       | QuantStack/jupyterlab-drawio#71        | [(`0.8.0`)](https://github.com/QuantStack/jupyterlab-drawio/releases/tag/0.8.0)
https://github.com/QuantStack/ipygany                 | QuantStack/ipygany#70                  | [(`0.5.0`)](https://github.com/QuantStack/ipygany/releases/tag/0.5.0)
https://github.com/timkpaine/ipydagred3               | timkpaine/ipydagred3#32                | [(`0.3.0`)](https://github.com/timkpaine/ipydagred3/releases/tag/v0.3.0)
https://github.com/timkpaine/jupyterlab_autoversion   | timkpaine/jupyterlab_autoversion#36    | [(`0.3.0`)](https://github.com/timkpaine/jupyterlab_autoversion/releases/tag/v0.3.0)
https://github.com/timkpaine/jupyterlab_commands      | timkpaine/jupyterlab_commands#30       | [(`0.3.0`)](https://github.com/timkpaine/jupyterlab_commands/releases/tag/v0.3.0)
https://github.com/timkpaine/jupyterlab_email         | timkpaine/jupyterlab_email#39          | N
https://github.com/timkpaine/jupyterlab_iframe        | timkpaine/jupyterlab_iframe#72         | [(`0.3.0`)](https://github.com/timkpaine/jupyterlab_iframe/releases/tag/v0.3.0)
https://github.com/sodennis/ipymonaco                 |                                        | W*
https://github.com/ipyannotate/ipyannotate            |                                        | W*
https://github.com/Yomguithereal/ipysigma             |                                        | W*
https://github.com/lineupjs/lineup_widget             |                                        | W*
https://github.com/martinRenou/ipycanvas              |                                        | [(`0.8.1`)](https://github.com/martinRenou/ipycanvas/releases/tag/0.8.1)
https://github.com/elyra-ai/elyra                     | elyra-ai/elyra#1167                    | [(`2.0.0`)](https://github.com/elyra-ai/elyra/releases/tag/v2.0.0)
https://github.com/glue-viz/bqplot-image-gl           | glue-viz/bqplot-image-gl#35            | [(`1.1.0`)](https://github.com/glue-viz/bqplot-image-gl/releases/tag/1.1.0)
https://github.com/maartenbreddels/ipyvolume          | maartenbreddels/ipyvolume#355          | [(`0.6.0a8`)](https://github.com/maartenbreddels/ipyvolume/releases/tag/v0.6.0-alpha.8)
https://github.com/mariobuikhuizen/ipyvue             | mariobuikhuizen/ipyvue#19              | [(`1.5.0`)](https://github.com/mariobuikhuizen/ipyvue/releases/tag/v1.5.0)
https://github.com/mariobuikhuizen/ipyvuetify         | mariobuikhuizen/ipyvuetify#110         | [(`1.6.1`)](https://github.com/mariobuikhuizen/ipyvuetify/releases/tag/v1.6.1)
https://github.com/nmearl/ipysplitpanes               | nmearl/ipysplitpanes#7                 | [`0.2.0`](https://github.com/nmearl/ipysplitpanes/releases/tag/v0.2.0)
https://github.com/nmearl/ipygoldenlayout             | nmearl/ipygoldenlayout#12              | [(`0.4.0`)](https://github.com/nmearl/ipygoldenlayout/releases/tag/v0.4.0)
https://github.com/jupyter/pythreejs                  | jupyter-widgets/pythreejs#350          | [`2.3.0`](https://github.com/jupyter-widgets/pythreejs/releases/tag/2.3.0)
https://github.com/vidartf/ipydatawidgets             | vidartf/ipydatawidgets#41              | [(`4.2.0`)](https://github.com/vidartf/ipydatawidgets/releases/tag/4.2.0)
https://github.com/vidartf/ipyscales                  | vidartf/ipyscales#25                   | [(`0.6.0`)](https://github.com/vidartf/ipyscales/releases/tag/0.6.0)
https://github.com/mwouts/jupytext                    | mwouts/jupytext#683                    | [(`1.9.1`)](https://github.com/mwouts/jupytext/releases/tag/v1.9.1)
https://github.com/voila-dashboards/voila             | voila-dashboards/voila#802             | [(`0.2.6`)](https://github.com/voila-dashboards/voila/releases/tag/0.2.6)
https://github.com/lckr/jupyterlab-variableInspector  | lckr/jupyterlab-variableInspector#174  | [(`3.0.3`)](https://github.com/lckr/jupyterlab-variableInspector/releases/tag/v3.0.3)
https://github.com/ryantam626/jupyterlab_code_formatter | ryantam626/jupyterlab_code_formatter#181 | [(`1.4.2`)](https://github.com/ryantam626/jupyterlab_code_formatter/releases/tag/v1.4.2)
https://github.com/rapidsai/jupyterlab-nvdashboard    | rapidsai/jupyterlab-nvdashboard#84     | [(`0.6.0`)](https://github.com/rapidsai/jupyterlab-nvdashboard/releases/tag/v0.6.0)
https://github.com/visgl/deck.gl/ | issue: visgl/deck.gl/issues/5615 | N

(W*) Conditional on `ipywidgets`, may require incrementing version dependency in `package.json`

**Comment by timkpaine** [comment]
@dhirschfeld filled out a few more that im aware of

**Comment by stonebig** [comment]
I notice i can install "Jupyterlab2" extension, "à la" Jupyterlab2, and it apparently works with Jupyterlab-3.0.0rc15: bqplot, ipympl, ipyleaflet.

Is it normal ?

**Comment by jasongrout** [comment]
For ipywidgets, the important thing is to have `jupyterlab_widgets` 1.0 installed. So ipywidgets 7.5 works just fine with jlab 3. ipywidgets 7.6 just automatically also pulls in `jupyterlab_widgets` 1.0, so installing ipywidgets 7.6 works as well. That may be too confusing, but may also be helpful to those that have ipywidgets 7.5 and cannot upgrade for some reason.

**Comment by stonebig** [comment]
pyviz_comms-2.01 seems compatible [now](https://github.com/holoviz/pyviz_comms/commit/17efe42b0534ee2b9224614c86355bb08309dbe3)

**Comment by dhirschfeld** [comment]
https://github.com/matplotlib/ipympl/releases/tag/0.6.1

**Comment by dhirschfeld** [comment]
https://github.com/jupyter-widgets/ipyleaflet/releases/tag/0.13.5

**Comment by dhirschfeld** [comment]
https://github.com/timkpaine/jupyterlab_autoversion/releases/tag/v0.3.0

**Comment by dhirschfeld** [comment]
https://github.com/timkpaine/jupyterlab_commands/releases/tag/v0.3.0

**Comment by jasongrout** [comment]
Some more compatibility information is being collected over at https://github.com/spacetelescope/jdaviz/issues/327

**Comment by karlaspuldaro** [comment]
Can we also add [Elyra](https://github.com/elyra-ai/elyra/) to the list? 
Lab3 support PR: https://github.com/elyra-ai/elyra/pull/1063
Compatible version 2.0.0  - release is coming out soon

**Comment by dhirschfeld** [comment]
Added `elyra`, it looks like final support is still WIP - https://github.com/elyra-ai/elyra/pull/1167

Will update when 2.0.0 is released...

**Comment by krassowski** [comment]
Updated status of lsp extension. Should we also add https://github.com/ijmbarr/jupyterlab_spellchecker?

**Comment by goanpeca** [comment]
@krassowski I will be releasing the language packs next week. Would be great to look back at the dictionary dpelling check work :)

**Comment by krassowski** [comment]
I used up all my open source time for this week when updating the lsp extension but will look into it next!

**Comment by dhirschfeld** [comment]
> Some more compatibility information is being collected 

Added `jdaviz` extensions.

**Comment by martinRenou** [comment]
bqplot 0.12.20 is out :)

**Comment by mariobuikhuizen** [comment]
ipyvue v1.5.0 and ipyvuetify v1.6.1 have JLab 3.0 compatibility now!

**Comment by potoo0** [comment]
[jupyterlab_code_formatter](https://github.com/ryantam626/jupyterlab_code_formatter) have JLab 3.0 compatibility, [v1.4.2](https://github.com/ryantam626/jupyterlab_code_formatter/releases/tag/v1.4.2)

**Comment by ostrokach** [comment]
Status for `jupyterlab-nvdashboard` is tracked here: rapidsai/jupyterlab-nvdashboard#84.

**Comment by CodeCox** [comment]
RE: @pyviz/jupyterlab_pyviz 

A little elaboration on the [pyviz_comms-2.01](https://github.com/holoviz/pyviz_comms) entry since it does not mention the underlying _chain_ that it can enable. eg. **hvplot --> holoviews --> bokeh**. There are still some related open PR's in these repos (eg. as listed in the table for the _jupyter_bokeh_ extension), but I have this toolchain running in JLab3 on Windows 10.
- hvplot            0.7.0   
- bokeh             2.2.3   
- holoviews       1.14.1
- pyviz_comms  2.0.1

A conda install of the high-level package _hvplot=0.7.0_ painlessly installs this prebuilt extension with the other dependancies.

**Comment by karlaspuldaro** [comment]
[Elyra](https://github.com/elyra-ai/elyra) released [v2.0.0](https://github.com/elyra-ai/elyra/releases/tag/v2.0.0) and is now compatible with JLab3.0 :)

**Comment by jakirkham** [comment]
Can't edit the OP, but jupyterlab-latex is tracking this with issue ( https://github.com/jupyterlab/jupyterlab-latex/issues/154 )

**Comment by maartenbreddels** [comment]
bqplot-image-gl 1.1.0 is lab3 compatible (modulo a bqplot dependency not playing nit https://github.com/bqplot/bqplot/pull/1271 )

**Comment by dhirschfeld** [comment]
I bumped the `bqplot` compatible release to 0.12.22 due to [potential issues](https://github.com/bqplot/bqplot/pull/1271) with the 0.12.20 release:

**Comment by dhirschfeld** [comment]
Just noting that the `plotly` extension is a *source* extension.
The issue tracking a prebuilt extension is https://github.com/plotly/plotly.py/issues/3036

**Comment by maartenbreddels** [comment]
` ipyvolume==0.6.0a8` is compatible with lab 3.0

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/out-of-memory-error-in-running-build/8914/2

**Comment by krassowski** [comment]
I released `jupyterlab-github` and updated the table; there are two more extensions with PRs merged but pending a release:
- https://github.com/jupyter-widgets/pythreejs (CC @vidartf - please correct me if I missed the tag/release)
- https://github.com/jpmorganchase/nbcelltests (CC @timkpaine - please correct me if I missed the tag/release)

**Comment by vidartf** [comment]
@krassowski I had forgot to push the 2.3.0 tag of pythreejs, but the release has been out since Feb. I have pushed the tag now as well.

**Comment by ohk2kt3t4** [comment]
Perhaps [pydeck](https://github.com/visgl/deck.gl/issues/5615) could be added to the OP table as well?

**Comment by krassowski** [comment]
Thanks, I updated `pythreejs` in table and added `deck.gl` - but I could not find a PR here.

**Comment by krassowski** [comment]
Closing as the above list is essentially complete and we are now tracking 4.0 compatibility in https://github.com/jupyterlab/jupyterlab/issues/14590.
