### ISSUE TITLE
external in webpack.config.js (gmaps extension) causes all widgets to fail

### ISSUE THREAD

**Issue by joequant** [jupyterlab/jupyterlab#9469]
## Description

including 
        externals: ['@jupyter-widgets/base', '@jupyter-widgets/controls'],
in a webpack config causes all plugin widgets to fail

https://github.com/pbugnion/gmaps/blob/master/js/webpack.config.js

## Reproduce

1) install gmaps plugin
2) there are multiple directores under jupyter-widgets and widgets will no longer display
3) there is then an error log about unable to register plugin with registry
4) looking at webpack directories in firefox development mode shows multiple copies of jupyter-widget/base/lib

The widgets disappeared after adding a lot of plugins.  Then used firefox development mode to see multiple copies of jupyter-widget/base/lib in webpack, and then figured out that gmaps was causing the problem

## Context

- Operating System and version: Linux mageia
- Browser and version: Firefox nightly
- JupyterLab version: 2.2.9

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
此頁面使用了不標準的屬性「zoom」，請考慮在相關屬性中改用 calc()，或改用「transform」以及「transform-origin: 0 0」。 home
某些 Cookie 誤用「SameSite」屬性，將無法正常運作 222
Removing intrinsics.Promise.any lockdown.js:2516:17
Removing intrinsics.Reflect.@@toStringTag lockdown.js:2516:17
Removing intrinsics.%ArrayPrototype%.at lockdown.js:2516:17
Removing intrinsics.%StringPrototype%.replaceAll lockdown.js:2516:17
Removing intrinsics.%StringPrototype%.at lockdown.js:2516:17
Removing intrinsics.%ErrorPrototype%.stack lockdown.js:2516:17
Removing intrinsics.%TypedArrayPrototype%.at lockdown.js:2516:17
MetaMask: MetaMask will soon stop reloading pages on network change.
For more information, see: https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange 
Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning. inpage.js:1:22488
unreachable code after return statement ScatterGL.js:228
Download the React DevTools for a better development experience: https://fb.me/react-devtools react-dom.development.js:25195
因為會影響使用者的使用體驗，已棄用主執行緒中的同步 XMLHttpRequest。若需更多資訊請參考 http://xhr.spec.whatwg.org/ modulated.js:10837
MIME 類型（「text/html」）不符合，所以來自「http://dev1.bitquant.com.hk:8085/jupyterhub/user/user/css/common.css」的資源被封鎖（X-Content-Type-Options: nosniff）。 auto-n
d3 loaded widget_utils.js:9
Object { version: Getter, bisect: Getter, bisectRight: Getter, bisectLeft: Getter, ascending: Getter, bisector: Getter, cross: Getter, descending: Getter, deviation: Getter, extent: Getter, … }
widget_utils.js:10
Qgrid was unable to load base/js/dialog. Full screen button won't be available qgrid.widget.js:14
Starting commenting service 
Object { getOption: getOption(name), setOption: setOption(name, value), getBaseUrl: getBaseUrl(), getTreeUrl: getTreeUrl(), getShareUrl: getShareUrl(), getTreeShareUrl: getTreeShareUrl(), getWsUrl: getWsUrl(baseUrl), getNBConvertURL: getNBConvertURL(), getToken: getToken(), getNotebookVersion: getNotebookVersion(), … }
service_connection.js:12
Plugin 'bqplot' failed to activate. index.es6.js:282
    promises index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
    promises index.es6.js:283
Plugin 'ipyvolume' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'jupyter.extensions.jupyter-threejs' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
    promises index.es6.js:283
Plugin 'algorithmx-jupyter' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'matplotlib-jupyter:main' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'jupyter.extensions.datawidgets' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'itkwidgets' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin '@bokeh/jupyter_bokeh' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'ipylab:plugin' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'ipyaggrid' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'ipysheet' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'qgrid' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'ipycanvas:plugin' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'ipyevents' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'plotlywidget' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'vispy' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
Plugin 'jupyter-gmaps' failed to activate. index.es6.js:282
Error: No provider for: jupyter.extensions.jupyterWidgetRegistry.
    resolveRequiredService index.es6.js:197
    required index.es6.js:155
    activatePlugin index.es6.js:155
    promises index.es6.js:281
    start index.es6.js:280
    main index.out.js:1947
index.es6.js:283
hub-extension: Found configuration  
Object { hubHost: "", hubPrefix: "/jupyterhub/hub/" }
index.js:31
Starting application in workspace: "/lab/workspaces/auto-n" index.js:50
JupyterLab extension jupyterlab_filetree is activated! index.js:10
JupyterLab extension jupyterlab-jupytext is activated index.js:105
Jupytext: adding command=jupytext:ipynb with rank=1 index.js:214
Jupytext: adding command=jupytext:auto:light with rank=2 index.js:214
Jupytext: adding command=jupytext:auto:percent with rank=3 index.js:214
Jupytext: adding command=jupytext:auto:hydrogen with rank=4 index.js:214
Jupytext: adding command=jupytext:auto:nomarker with rank=5 index.js:214
Jupytext: adding command=jupytext:md with rank=6 index.js:214
Jupytext: adding command=jupytext:md:myst with rank=7 index.js:214
Jupytext: adding command=jupytext:Rmd with rank=8 index.js:214
Jupytext: adding command=jupytext:custom with rank=9 index.js:214
Jupytext: adding command=jupytext:none with rank=10 index.js:214
Starting WebSocket: ws://dev1.bitquant.com.hk:8085/jupyterhub/user/user/api/kernels/3b2e8c31-a84d-481c-ade3-501f1034bea1 default.js:51
Loading comments... service.js:300
The JupyterLab GitHub server extension appears to be missing. If you do not install it with application credentials, you are likely to be rate limited by GitHub very quickly contents.js:44
Uncaught (in promise) TypeError: can't access property "type", object is undefined
    createTreeElement filetree.js:199
    buildTableContents filetree.js:129
    buildTable filetree.js:74
    FileTreeWidget filetree.js:52
filetree.js:199
error loading comments JSON.parse: unexpected character at line 2 column 1 of the JSON data service.js:320
Routing /lab/workspaces/auto-n?clone was short-circuited by apputils:load-statedb router.js:131
Source Map 錯誤: Error: NetworkError when attempting to fetch resource.
資源網址: moz-extension://5266cf57-68c2-47a7-aac4-31b089a84679/inpage.js
Source Map 網址: ../sourcemaps/inpage.js.map
Source Map 錯誤: Error: NetworkError when attempting to fetch resource.
資源網址: moz-extension://5266cf57-68c2-47a7-aac4-31b089a84679/contentscript.js
Source Map 網址: ../sourcemaps/contentscript.js.map
Source Map 錯誤: Error: NetworkError when attempting to fetch resource.
資源網址: moz-extension://5266cf57-68c2-47a7-aac4-31b089a84679/inpage.js
Source Map 網址: ../sourcemaps/inpage.js.map
unreachable code after return statement ScatterGL.js:228

</pre>
</details>

**Comment by jasongrout** [comment]
> then figured out that gmaps was causing the problem

Can you file an issue with gmaps, then?

**Comment by jasongrout** [comment]
(To be more clear, the gmaps webpack config is run before anything gets to jupyterlab - this may be a problem with gmaps and its webpack config, but is very unlikely to be a problem with JupyterLab itself)

**Comment by joequant** [comment]
The problem is that a single plugin shouldn't have the ability to crash jupyterlab

**Comment by joequant** [comment]
Having a single plugin able to crash all of jupyterlab in a non-obvious way seems to me to be a design issue.

**Comment by joequant** [comment]
The issue seems to be that gmaps causes webpack to behave in a way that causes jupyterlab/widget-manager to get reordered in a way that causes all of the other widgets to fail.
