### ISSUE TITLE
Cell tag widget is not in sync with metadata panel

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#9472]
## Description

When adding new tag (except the first one) or when deleting the `tags` entry in metadata, the cell tagging widget and the metadata panel are not in sync:

![cell-tag-troubles](https://user-images.githubusercontent.com/8435071/102203363-ca19c580-3ec8-11eb-8cd7-4d2b5c904689.gif)

## Reproduce

1. Open a notebook
2. Add two tags
2b. The metadata panel displays only one tag.
3. Click a new cell and come back to see them in the metadata panel
4. Remove the tag entry in the metadata panel
4b. The cell tag widget is not updated

## Expected behavior

Cell tag widget and metadata are in sync

The issue has two reasons:
- Not handling carefully mutable `tags` array from metadata; in particular new tag are pushed to the existing array. Then the same array is set => value (pointer to the array) does not change => no cell metadata changed signal emitted.

L77 should be changed by:
```
-    let tags = cell.model.metadata.get('tags') as string[];
+    let tags = [...((cell.model.metadata.get('tags') as string[]) || [])];
```

And for the removal, the value is removed by splicing the original array and setting it.

L104 should be changed by:
```
-    const tags = cell.model.metadata.get('tags') as string[];
+    const tags = [...((cell.model.metadata.get('tags') as string[]) || [])];
```
- In the metadata changed listener, if `tags` is not found, there is no cleaning of existing tag widgets:

https://github.com/jupyterlab/jupyterlab/blob/9a8dadf59424ed2a6ff2a3c84001d46e37104d75/packages/celltags/src/tool.ts#L251-L255

## Context

- Operating System and version: Windows 10
- Browser and version: Firefox 83
- JupyterLab version: 2.2.9

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
Thanks! Do you want to submit a PR? Also, I think you can use ?? instead of ||

**Comment by fcollonval** [comment]
Thanks for the tip about `??`. I'll try to push a PR.
