### ISSUE TITLE
`jupyter lab` doesn't run

### ISSUE THREAD

**Issue by artgoldberg** [jupyterlab/jupyterlab#9474]
## Description

Following the instructions in [installation](https://jupyterlab.readthedocs.io/en/latest/getting_started/issue.html). But `jupyter lab` doesn't run.

## Reproduce

    # `Conda` and `anaconda` updated
    $ conda update conda
    $ conda update anaconda
    # jupyterlab installed
    $ conda install -c conda-forge jupyterlab
    # installation & version OK
    $ jupyter serverextension enable --py jupyterlab --sys-prefix
    Enabling: jupyterlab
    - Writing config: /anaconda3/etc/jupyter
        - Validating...
          jupyterlab 0.32.1 OK
    $ jupyter notebook --version
    5.5.0
    # jupyter lab doesn't run:
    $ jupyter lab
    /anaconda3/bin/pythonw: line 3: /anaconda3/python.app/Contents/MacOS/python: No such file or directory
    # jupyter runs
    $ jupyter -h
    usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                   [--paths] [--json]
                   [subcommand]

    Jupyter: Interactive Computing

    positional arguments:
      subcommand     the subcommand to launch

    optional arguments:
      -h, --help     show this help message and exit
      --version      show the jupyter command's version and exit
      --config-dir   show Jupyter config dir
      --data-dir     show Jupyter data dir
      --runtime-dir  show Jupyter runtime dir
      --paths        show all Jupyter paths. Add --json for machine-readable
                     format.
      --json         output paths as machine-readable json

    Available subcommands: bundlerextension console contrib kernel kernelspec lab
    labextension labhub migrate nbconvert nbextension nbextensions_configurator
    notebook qtconsole run serverextension troubleshoot trust

Full log:
<pre>
[25  --- :~]$ conda update conda
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /anaconda3

  added / updated specs:
    - conda

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.9.2                |   py36hecd8cb5_0         2.9 MB
    conda-package-handling-1.7.2|   py36h22f3db7_0         1.5 MB
    ripgrep-12.1.1             |                0         1.3 MB
    tqdm-4.54.1                |     pyhd3eb1b0_0          55 KB
    websocket-client-0.57.0    |           py36_2          59 KB
    ------------------------------------------------------------
                                           Total:         5.7 MB

The following packages will be REMOVED:

  libarchive-3.3.3-h786848e_5
  lz4-c-1.8.1.2-h1de35cc_0
  python-libarchive-c-2.9-py_0
  python_abi-3.6-1_cp36m
  zstd-1.3.7-h5bba6e5_0

The following packages will be UPDATED:

  conda-package-han~                   1.6.1-py36h1de35cc_0 --> 1.7.2-py36h22f3db7_0
  ripgrep                                 11.0.2-he32d670_0 --> 12.1.1-0
  tqdm                                          4.49.0-py_0 --> 4.54.1-pyhd3eb1b0_0
  websocket-client                            0.57.0-py36_1 --> 0.57.0-py36_2

The following packages will be SUPERSEDED by a higher-priority channel:

  conda              conda-forge::conda-4.9.2-py36h79c6626~ --> pkgs/main::conda-4.9.2-py36hecd8cb5_0

Proceed ([y]/n)? y                     

Downloading and Extracting Packages
conda-package-handli | 1.5 MB    | ####################################################### | 100% 
ripgrep-12.1.1       | 1.3 MB    | ####################################################### | 100% 
websocket-client-0.5 | 59 KB     | ####################################################### | 100% 
conda-4.9.2          | 2.9 MB    | ####################################################### | 100% 
tqdm-4.54.1          | 55 KB     | ####################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
[26  --- :~]$ conda update anaconda
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

[27  --- :~]$ conda install -c conda-forge jupyterlab
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /anaconda3

  added / updated specs:
    - jupyterlab

The following NEW packages will be INSTALLED:

  python_abi         conda-forge/osx-64::python_abi-3.6-1_cp36m

The following packages will be SUPERSEDED by a higher-priority channel:

  conda               pkgs/main::conda-4.9.2-py36hecd8cb5_0 --> conda-forge::conda-4.9.2-py36h79c6626_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
[28  --- :~]$ jupyter serverextension enable --py jupyterlab --sys-prefix
Enabling: jupyterlab
- Writing config: /anaconda3/etc/jupyter
    - Validating...
      jupyterlab 0.32.1 OK
[29  --- :~]$ jupyter notebook --version
5.5.0
[30  --- :~]$ jupyter lab
/anaconda3/bin/pythonw: line 3: /anaconda3/python.app/Contents/MacOS/python: No such file or directory
[31  --- :~]$ jupyter
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]
jupyter: error: one of the arguments --version subcommand --config-dir --data-dir --runtime-dir --paths is required
[32  --- :~]$ jupyter -h
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

optional arguments:
  -h, --help     show this help message and exit
  --version      show the jupyter command's version and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json

Available subcommands: bundlerextension console contrib kernel kernelspec lab
labextension labhub migrate nbconvert nbextension nbextensions_configurator
notebook qtconsole run serverextension troubleshoot trust
[33  --- :~]$ jupyter lab
/anaconda3/bin/pythonw: line 3: /anaconda3/python.app/Contents/MacOS/python: No such file or directory
[34  --- :~]$ 

</pre>

## Expected behavior

`jupyter lab` should run.

## Context

- Operating System and version: macOS 10.13.6 
- Browser and version: NA
- JupyterLab version: see above

<details><summary>Troubleshoot Output</summary>
<pre>
WARNING: You are using pip version 20.3.2; however, version 20.3.3 is available.
You should consider upgrading via the '/anaconda3/bin/python -m pip install --upgrade pip' command.
$PATH:
	/anaconda3/bin
	/anaconda3/bin
	/Library/Frameworks/Python.framework/Versions/3.5/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin
	/usr/local/MacGPG2/bin
	/opt/X11/bin
	/Applications/Wireshark.app/Contents/MacOS
	.
	/usr/local/mysql/bin

sys.path:
	/anaconda3/bin
	/Users/<my uid>/gitOnMyLaptopLocal/wc_dev_repos/wc_sim
	/Users/<my uid>/gitOnMyLaptopLocal/wc_dev_repos/wc_lang
	/Users/<my uid>/gitOnMyLaptopLocal/wc_dev_repos/obj_model
	/anaconda3/lib/python36.zip
	/anaconda3/lib/python3.6
	/anaconda3/lib/python3.6/lib-dynload
	/Users/<my uid>/.local/lib/python3.6/site-packages
	/anaconda3/lib/python3.6/site-packages
	/anaconda3/lib/python3.6/site-packages/aeosa

sys.executable:
	/anaconda3/bin/python

sys.version:
	3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
	[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

platform.platform():
	Darwin-17.7.0-x86_64-i386-64bit

which -a jupyter:
	/anaconda3/bin/jupyter
	/anaconda3/bin/jupyter
	/Library/Frameworks/Python.framework/Versions/3.5/bin/jupyter

pip list:
	Package                            Version
	---------------------------------- ----------
	abduct                             2.0.1
	alabaster                          0.7.10
	anaconda-client                    1.6.14
	anaconda-navigator                 1.9.7
	anaconda-project                   0.8.2
	appdirs                            1.4.4
	appnope                            0.1.0
	appscript                          1.0.1
	asn1crypto                         0.24.0
	astroid                            1.6.3
	astropy                            3.0.2
	attrdict                           2.0.0
	attrs                              18.1.0
	Babel                              2.5.3
	backcall                           0.1.0
	backports.shutil-get-terminal-size 1.0.0
	beautifulsoup4                     4.6.0
	bitarray                           0.8.1
	bkcharts                           0.2
	blaze                              0.11.3
	bleach                             2.1.3
	bokeh                              0.12.16
	boto                               2.48.0
	Bottleneck                         1.2.1
	cement                             3.0.0
	certifi                            2018.4.16
	cffi                               1.11.5
	chardet                            3.0.4
	click                              6.7
	cloudpickle                        0.5.3
	clyent                             1.2.2
	cobra                              0.15.1
	colorama                           0.3.9
	conda                              4.9.2
	conda-build                        3.18.9
	conda-package-handling             1.7.2
	configobj                          5.0.6
	configparser                       3.5.0
	contextlib2                        0.5.5
	coverage                           5.1
	cryptography                       2.2.2
	cycler                             0.10.0
	Cython                             0.28.2
	cytoolz                            0.9.0.1
	dask                               0.17.5
	datashape                          0.5.4
	decorator                          4.3.0
	depinfo                            1.5.1
	diskcache                          3.0.6
	distributed                        1.21.8
	docker                             3.5.1
	docker-pycreds                     0.4.0
	docker-squash                      1.0.7
	docutils                           0.14
	entrypoints                        0.2.3
	enum34                             1.1.6
	et-xmlfile                         1.0.1
	fastcache                          1.0.2
	filelock                           3.0.4
	Flask                              1.0.2
	Flask-Cors                         3.0.4
	future                             0.17.1
	gevent                             1.3.0
	gitdb2                             2.0.4
	GitPython                          2.1.11
	glob2                              0.6
	gmpy2                              2.0.8
	greenlet                           0.4.13
	h5py                               2.7.1
	heapdict                           1.0.0
	html5lib                           1.0.1
	idna                               2.6
	imageio                            2.3.0
	imagesize                          1.0.0
	ipykernel                          4.8.2
	ipython                            6.4.0
	ipython-genutils                   0.2.0
	ipywidgets                         7.2.1
	isort                              4.3.4
	itsdangerous                       0.24
	jdcal                              1.4
	jedi                               0.12.0
	Jinja2                             2.10
	jsonschema                         2.6.0
	jupyter                            1.0.0
	jupyter-client                     5.2.3
	jupyter-console                    5.2.0
	jupyter-contrib-core               0.3.3
	jupyter-contrib-nbextensions       0.5.0
	jupyter-core                       4.4.0
	jupyter-highlight-selected-word    0.2.0
	jupyter-latex-envs                 1.4.6
	jupyter-nbextensions-configurator  0.4.0
	jupyterlab                         0.32.1
	jupyterlab-launcher                0.10.5
	kiwisolver                         1.0.1
	lazy-object-proxy                  1.3.1
	libroadrunner                      1.5.2
	libroadrunner-tr                   1.0.0
	llvmlite                           0.23.1
	lml                                0.0.4
	locket                             0.2.0
	log                                2016.10.12
	lxml                               4.2.1
	MarkupSafe                         1.0
	matplotlib                         2.2.2
	mccabe                             0.6.1
	mendeleev                          0.4.3
	mistune                            0.8.3
	mkl-fft                            1.0.0
	mkl-random                         1.0.1
	more-itertools                     4.1.0
	mpmath                             1.0.0
	msgpack                            1.0.1
	msgpack-python                     0.5.6
	multipledispatch                   0.5.0
	navigator-updater                  0.2.1
	nbconvert                          5.3.1
	nbformat                           4.4.0
	networkx                           2.1
	nltk                               3.3
	nose                               1.3.7
	notebook                           5.5.0
	numba                              0.38.0
	numexpr                            2.6.5
	numpy                              1.14.3
	numpydoc                           0.8.0
	odo                                0.5.1
	olefile                            0.45.1
	openpyxl                           2.5.3
	optlang                            1.4.4
	packaging                          17.1
	pandas                             0.23.0
	pandocfilters                      1.4.2
	parso                              0.2.0
	partd                              0.3.8
	path.py                            11.0.1
	pathlib2                           2.3.2
	patsy                              0.5.0
	pep8                               1.7.1
	pexpect                            4.5.0
	pickleshare                        0.7.4
	Pillow                             5.1.0
	Pint                               0.8.1
	pip                                20.3.2
	pipdeptree                         0.13.2
	pkg-utils                          0.0.3
	pkginfo                            1.4.2
	pluggy                             0.6.0
	ply                                3.11
	prompt-toolkit                     1.0.15
	psutil                             5.4.5
	ptyprocess                         0.5.2
	py                                 1.5.3
	pycodestyle                        2.4.0
	pycosat                            0.6.3
	pycparser                          2.18
	pycrypto                           2.6.1
	pycurl                             7.43.0.1
	pyexcel                            0.5.9.1
	pyexcel-io                         0.5.9.1
	pyfiglet                           0.7.5
	pyflakes                           1.6.0
	Pygments                           2.2.0
	pylint                             1.8.4
	pyodbc                             4.0.23
	pyOpenSSL                          18.0.0
	pyparsing                          2.2.0
	PySocks                            1.6.8
	pytest                             5.3.5
	pytest-arraydiff                   0.2
	pytest-astropy                     0.3.0
	pytest-doctestplus                 0.1.3
	pytest-openfiles                   0.3.0
	pytest-remotedata                  0.2.1
	python-dateutil                    2.7.3
	python-libsbml                     5.17.0
	python-libsbml-experimental        5.17.2
	pytz                               2018.4
	PyWavelets                         0.5.2
	PyYAML                             5.1
	pyzmq                              17.0.0
	QtAwesome                          0.4.4
	qtconsole                          4.3.1
	QtPy                               1.4.1
	qualname                           0.1.0
	requests                           2.18.4
	requirements-parser                0.2.0
	rope                               0.10.7
	ruamel-yaml                        0.15.35
	ruamel.yaml                        0.15.91
	scikit-image                       0.13.1
	scikit-learn                       0.19.1
	scipy                              1.1.0
	seaborn                            0.8.1
	Send2Trash                         1.5.0
	setuptools                         39.1.0
	simplegeneric                      0.8.1
	singledispatch                     3.4.0.3
	six                                1.11.0
	smmap2                             2.0.4
	snowballstemmer                    1.2.1
	sortedcollections                  0.6.1
	sortedcontainers                   1.5.10
	Sphinx                             1.7.4
	sphinxcontrib-websupport           1.0.1
	spyder                             3.2.8
	SQLAlchemy                         1.2.7
	statsmodels                        0.9.0
	swiglpk                            4.65.0
	sympy                              1.1.1
	tables                             3.4.3
	tabulate                           0.8.3
	TBB                                0.1
	tblib                              1.3.2
	terminado                          0.8.1
	testpath                           0.3.1
	texttable                          1.4.0
	toolz                              0.9.0
	tornado                            5.0.2
	tqdm                               4.54.1
	traitlets                          4.3.2
	typing                             3.6.4
	unicodecsv                         0.14.1
	urllib3                            1.22
	wc-env-manager                     0.0.1
	wc-utils                           0.0.1a5
	wcwidth                            0.1.7
	webencodings                       0.5.1
	websocket-client                   0.57.0
	Werkzeug                           0.14.1
	wheel                              0.31.1
	widgetsnbextension                 3.2.1
	wrapt                              1.10.11
	xlrd                               1.1.0
	XlsxWriter                         1.0.4
	xlwings                            0.11.8
	xlwt                               1.2.0
	zict                               0.1.3

conda list:
	# packages in environment at /anaconda3:
	#
	# Name                    Version                   Build  Channel
	_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0  
	abduct                    2.0.1                    pypi_0    pypi
	alabaster                 0.7.10           py36h174008c_0  
	anaconda                  5.2.0                    py36_3  
	anaconda-client           1.6.14                   py36_0  
	anaconda-navigator        1.9.7                    py36_0  
	anaconda-project          0.8.2            py36h9ee5d53_0  
	appdirs                   1.4.4                      py_0  
	appnope                   0.1.0            py36hf537a9a_0  
	appscript                 1.0.1            py36h9e71e49_1  
	asn1crypto                0.24.0                   py36_0  
	astroid                   1.6.3                    py36_0  
	astropy                   3.0.2            py36h917ab60_1  
	attrdict                  2.0.0                    pypi_0    pypi
	attrs                     18.1.0                   py36_0  
	babel                     2.5.3                    py36_0  
	backcall                  0.1.0                    py36_0  
	backports                 1.0              py36ha3c1827_1  
	backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2  
	beautifulsoup4            4.6.0            py36h72d3c9f_1  
	bitarray                  0.8.1            py36h1de35cc_1  
	bkcharts                  0.2              py36h073222e_0  
	blas                      1.0                         mkl  
	blaze                     0.11.3           py36h02e7a37_0  
	bleach                    2.1.3                    py36_0  
	blosc                     1.14.3               hd9629dc_0  
	bokeh                     0.12.16                  py36_0  
	boto                      2.48.0           py36hdbc59ac_1  
	bottleneck                1.2.1            py36hbd380ad_0  
	bzip2                     1.0.6                h1de35cc_5  
	ca-certificates           2018.03.07                    0  
	cement                    3.0.0                    pypi_0    pypi
	certifi                   2018.4.16                py36_0  
	cffi                      1.11.5           py36h342bebf_0  
	chardet                   3.0.4            py36h96c241c_1  
	click                     6.7              py36hec950be_0  
	cloudpickle               0.5.3                    py36_0  
	clyent                    1.2.2            py36hae3ad88_0  
	cobra                     0.15.1                   pypi_0    pypi
	colorama                  0.3.9            py36hd29a30c_0  
	conda                     4.9.2            py36h79c6626_0    conda-forge
	conda-build               3.18.9                   py36_3  
	conda-package-handling    1.7.2            py36h22f3db7_0  
	configobj                 5.0.6                    pypi_0    pypi
	configparser              3.5.0                    pypi_0    pypi
	contextlib2               0.5.5            py36hd66e5e7_0  
	cryptography              2.2.2            py36h1de35cc_0  
	curl                      7.60.0               ha441bb4_0  
	cycler                    0.10.0           py36hfc81398_0  
	cython                    0.28.2           py36h1de35cc_0  
	cytoolz                   0.9.0.1          py36h1de35cc_0  
	dask                      0.17.5                   py36_0  
	dask-core                 0.17.5                   py36_0  
	datashape                 0.5.4            py36hfb22df8_0  
	dbus                      1.13.2               h760590f_1  
	decorator                 4.3.0                    py36_0  
	depinfo                   1.5.1                    pypi_0    pypi
	diskcache                 3.0.6                    pypi_0    pypi
	distributed               1.21.8                   py36_0  
	docker                    3.5.0                    pypi_0    pypi
	docker-py                 3.5.1                 py36_1001  
	docker-pycreds            0.3.0                    pypi_0    pypi
	docker-squash             1.0.7                    pypi_0    pypi
	docutils                  0.14             py36hbfde631_0  
	entrypoints               0.2.3            py36hd81d71f_2  
	enum34                    1.1.6                    pypi_0    pypi
	et_xmlfile                1.0.1            py36h1315bdc_0  
	expat                     2.2.5                hb8e80ba_0  
	fastcache                 1.0.2            py36h1de35cc_2  
	filelock                  3.0.4                    py36_0  
	flask                     1.0.2                    py36_1  
	flask-cors                3.0.4                    py36_0  
	freetype                  2.8                  h12048fb_1  
	future                    0.17.1                   pypi_0    pypi
	get_terminal_size         1.0.0                h7520d66_0  
	gettext                   0.19.8.1             h15daf44_3  
	gevent                    1.3.0            py36h1de35cc_0  
	gitdb2                    2.0.4                    pypi_0    pypi
	gitpython                 2.1.11                   pypi_0    pypi
	glib                      2.56.1               h35bc53a_0  
	glob2                     0.6              py36h94c9186_0  
	gmp                       6.1.2                hb37e062_1  
	gmpy2                     2.0.8            py36hf9c35bd_2  
	greenlet                  0.4.13           py36h1de35cc_0  
	h5py                      2.7.1            py36ha8ecd60_2  
	hdf5                      1.10.2               hfa1e0ec_1  
	heapdict                  1.0.0                    py36_2  
	html5lib                  1.0.1            py36h2f9c1c0_0  
	icu                       58.2                 h4b95b61_1  
	idna                      2.6              py36h8628d0a_1  
	imageio                   2.3.0                    py36_0  
	imagesize                 1.0.0                    py36_0  
	intel-openmp              2018.0.0                      8  
	ipykernel                 4.8.2                    py36_0  
	ipython                   6.4.0                    py36_0  
	ipython_genutils          0.2.0            py36h241746c_0  
	ipywidgets                7.2.1                    py36_0  
	isort                     4.3.4                    py36_0  
	itsdangerous              0.24             py36h49fbb8d_1  
	jbig                      2.1                  h4d881f8_0  
	jdcal                     1.4                      py36_0  
	jedi                      0.12.0                   py36_1  
	jinja2                    2.10             py36hd36f9c5_0  
	jpeg                      9b                   he5867d9_2  
	jsonschema                2.6.0            py36hb385e00_0  
	jupyter                   1.0.0                    py36_4  
	jupyter-contrib-core      0.3.3                    pypi_0    pypi
	jupyter-contrib-nbextensions 0.5.0                    pypi_0    pypi
	jupyter-highlight-selected-word 0.2.0                    pypi_0    pypi
	jupyter-latex-envs        1.4.6                    pypi_0    pypi
	jupyter-nbextensions-configurator 0.4.0                    pypi_0    pypi
	jupyter_client            5.2.3                    py36_0  
	jupyter_console           5.2.0            py36hccf5b1c_1  
	jupyter_contrib_core      0.3.3                      py_2    conda-forge
	jupyter_contrib_nbextensions 0.5.0                 py36_1000    conda-forge
	jupyter_core              4.4.0            py36h79cf704_0  
	jupyter_highlight_selected_word 0.2.0                 py36_1000    conda-forge
	jupyter_latex_envs        1.4.4                 py36_1000    conda-forge
	jupyter_nbextensions_configurator 0.4.0                 py36_1000    conda-forge
	jupyterlab                0.32.1                   py36_0  
	jupyterlab_launcher       0.10.5                   py36_0  
	kiwisolver                1.0.1            py36h792292d_0  
	lazy-object-proxy         1.3.1            py36h2fbbe47_0  
	libcurl                   7.60.0               hf30b1f0_0  
	libcxx                    4.0.1                h579ed51_0  
	libcxxabi                 4.0.1                hebd6815_0  
	libedit                   3.1.20170329         hb402a30_2  
	libffi                    3.2.1                h475c297_4  
	libgfortran               3.0.1                h93005f0_2  
	libiconv                  1.15                 hdd342a3_7  
	liblief                   0.10.1               h0a44026_0  
	libpng                    1.6.34               he12f830_0  
	libroadrunner             1.5.2                    pypi_0    pypi
	libroadrunner-tr          1.0.0                    pypi_0    pypi
	libsodium                 1.0.16               h3efe00b_0  
	libssh2                   1.8.0                h322a93b_4  
	libtiff                   4.0.9                hcb84e12_1  
	libxml2                   2.9.8                hab757c2_1  
	libxslt                   1.1.32               hb819dd2_0  
	llvmlite                  0.23.1           py36hc454e04_0  
	lml                       0.0.4                    pypi_0    pypi
	locket                    0.2.0            py36hca03003_1  
	log                       2016.10.12               pypi_0    pypi
	lxml                      4.2.1            py36h7166777_0  
	lzo                       2.10                 h362108e_2  
	markupsafe                1.0              py36h3a1e703_1  
	matplotlib                2.2.2            py36ha7267d0_0  
	mccabe                    0.6.1            py36hdaeb55d_0  
	mendeleev                 0.4.3                    pypi_0    pypi
	mistune                   0.8.3            py36h1de35cc_1  
	mkl                       2018.0.2                      1  
	mkl-service               1.1.2            py36h7ea6df4_4  
	mkl_fft                   1.0.1            py36h917ab60_0  
	mkl_random                1.0.1            py36h78cc56f_0  
	more-itertools            4.1.0                    py36_0  
	mpc                       1.0.3                h7a72875_5  
	mpfr                      3.1.5                h711e7fd_2  
	mpmath                    1.0.0            py36hf1b8295_2  
	msgpack                   1.0.1                    pypi_0    pypi
	msgpack-python            0.5.6            py36h04f5b5a_0  
	multipledispatch          0.5.0                    py36_0  
	navigator-updater         0.2.1                    py36_0  
	nbconvert                 5.3.1            py36h810822e_0  
	nbformat                  4.4.0            py36h827af21_0  
	ncurses                   6.1                  h0a44026_0  
	networkx                  2.1                      py36_0  
	nltk                      3.3.0                    py36_0  
	nose                      1.3.7            py36h73fae2b_2  
	notebook                  5.5.0                    py36_0  
	numba                     0.38.0           py36h1702cab_0  
	numexpr                   2.6.5            py36h057f876_0  
	numpy                     1.14.3           py36h9bb19eb_1  
	numpy-base                1.14.3           py36h479e554_1  
	numpydoc                  0.8.0                    py36_0  
	odo                       0.5.1            py36hc1af34a_0  
	olefile                   0.45.1                   py36_0  
	openpyxl                  2.5.3                    py36_0  
	openssl                   1.0.2o               h26aff7b_0  
	optlang                   1.4.4                    pypi_0    pypi
	packaging                 17.1                     py36_0  
	pandas                    0.23.0           py36h1702cab_0  
	pandoc                    1.19.2.1             ha5e8f32_1  
	pandocfilters             1.4.2            py36h3b0b094_1  
	parso                     0.2.0                    py36_0  
	partd                     0.3.8            py36hf5c4cb8_0  
	path.py                   11.0.1                   py36_0  
	pathlib2                  2.3.2                    py36_0  
	patsy                     0.5.0                    py36_0  
	pcre                      8.42                 h378b8a2_0  
	pep8                      1.7.1                    py36_0  
	pexpect                   4.5.0                    py36_0  
	pickleshare               0.7.4            py36hf512f8e_0  
	pillow                    5.1.0            py36hfcce615_0  
	pint                      0.8.1                    pypi_0    pypi
	pip                       20.3.2                   pypi_0    pypi
	pipdeptree                0.13.2                   pypi_0    pypi
	pkg-utils                 0.0.3                    pypi_0    pypi
	pkginfo                   1.4.2                    py36_1  
	pluggy                    0.6.0            py36hb1d0581_0  
	ply                       3.11                     py36_0  
	prompt_toolkit            1.0.15           py36haeda067_0  
	psutil                    5.4.5            py36h1de35cc_0  
	ptyprocess                0.5.2            py36he6521c3_0  
	py                        1.5.3                    py36_0  
	py-lief                   0.10.1           py36haf313ee_0  
	pycodestyle               2.4.0                    py36_0  
	pycosat                   0.6.3            py36hee92d8f_0  
	pycparser                 2.18             py36h724b2fc_1  
	pycrypto                  2.6.1            py36h1de35cc_8  
	pycurl                    7.43.0.1         py36hdbc3d79_0  
	pyexcel                   0.5.9.1                  pypi_0    pypi
	pyexcel-io                0.5.9.1                  pypi_0    pypi
	pyfiglet                  0.7.5                    pypi_0    pypi
	pyflakes                  1.6.0            py36hea45e83_0  
	pygments                  2.2.0            py36h240cd3f_0  
	pylint                    1.8.4                    py36_0  
	pyodbc                    4.0.23           py36h0a44026_0  
	pyopenssl                 18.0.0                   py36_0  
	pyparsing                 2.2.0            py36hb281f35_0  
	pyqt                      5.9.2            py36h11d3b92_0  
	pysocks                   1.6.8                    py36_0  
	pytables                  3.4.3            py36h5ca999c_2  
	pytest                    3.5.1                    py36_0  
	pytest-arraydiff          0.2                      py36_0  
	pytest-astropy            0.3.0                    py36_0  
	pytest-doctestplus        0.1.3                    py36_0  
	pytest-openfiles          0.3.0                    py36_0  
	pytest-remotedata         0.2.1                    py36_0  
	python                    3.6.5                hc167b69_1  
	python-dateutil           2.7.3                    py36_0  
	python-libsbml            5.17.0                   py36_0    SBMLTeam
	python-libsbml-experimental 5.17.2                   pypi_0    pypi
	python.app                2                        py36_8  
	python_abi                3.6                     1_cp36m    conda-forge
	pytz                      2018.4                   py36_0  
	pywavelets                0.5.2            py36h2710a04_0  
	pyyaml                    5.1                      pypi_0    pypi
	pyzmq                     17.0.0           py36h1de35cc_1  
	qt                        5.9.5                h02808f3_0  
	qtawesome                 0.4.4            py36h468c6fb_0  
	qtconsole                 4.3.1            py36hd96c0ff_0  
	qtpy                      1.4.1                    py36_0  
	qualname                  0.1.0                    pypi_0    pypi
	readline                  7.0                  hc1231fa_4  
	requests                  2.18.4           py36h4516966_1  
	requirements-parser       0.2.0                    pypi_0    pypi
	ripgrep                   12.1.1                        0  
	rope                      0.10.7           py36h68959ac_0  
	ruamel-yaml               0.15.91                  pypi_0    pypi
	ruamel_yaml               0.15.35          py36h1de35cc_1  
	scikit-image              0.13.1           py36h1de35cc_1  
	scikit-learn              0.19.1           py36hffbff8c_0  
	scipy                     1.1.0            py36hcaad992_0  
	seaborn                   0.8.1            py36h595ecd9_0  
	send2trash                1.5.0                    py36_0  
	setuptools                39.1.0                   py36_0  
	simplegeneric             0.8.1                    py36_2  
	singledispatch            3.4.0.3          py36hf20db9d_0  
	sip                       4.19.8           py36h0a44026_0  
	six                       1.11.0           py36h0e22d5e_1  
	smmap2                    2.0.4                    pypi_0    pypi
	snappy                    1.1.7                he62c110_3  
	snowballstemmer           1.2.1            py36h6c7b616_0  
	sortedcollections         0.6.1                    py36_0  
	sortedcontainers          1.5.10                   py36_0  
	sphinx                    1.7.4                    py36_0  
	sphinxcontrib             1.0              py36h9364dc8_1  
	sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1  
	spyder                    3.2.8                    py36_0  
	sqlalchemy                1.2.7            py36hb402a30_0  
	sqlite                    3.23.1               hf1716c9_0  
	statsmodels               0.9.0            py36h917ab60_0  
	swiglpk                   4.65.0                   pypi_0    pypi
	sympy                     1.1.1            py36h7f3cf04_0  
	tabulate                  0.8.3                    pypi_0    pypi
	tbb                       2020.0               h04f5b5a_0  
	tbb4py                    2020.0           py36h04f5b5a_0  
	tblib                     1.3.2            py36hda67792_0  
	terminado                 0.8.1                    py36_1  
	testpath                  0.3.1            py36h625a49b_0  
	texttable                 1.4.0                    pypi_0    pypi
	tk                        8.6.7                h35a86e2_3  
	toolz                     0.9.0                    py36_0  
	tornado                   5.0.2                    py36_0  
	tqdm                      4.54.1             pyhd3eb1b0_0  
	traitlets                 4.3.2            py36h65bd3ce_0  
	typing                    3.6.4                    py36_0  
	unicodecsv                0.14.1           py36he531d66_0  
	unixodbc                  2.3.6                h3efe00b_0  
	urllib3                   1.22             py36h68b9469_0  
	wc-env-manager            0.0.1                    pypi_0    pypi
	wc-utils                  0.0.1a5                  pypi_0    pypi
	wcwidth                   0.1.7            py36h8c6ec74_0  
	webencodings              0.5.1            py36h3b9701d_1  
	websocket-client          0.53.0                   pypi_0    pypi
	werkzeug                  0.14.1                   py36_0  
	wheel                     0.31.1                   py36_0  
	widgetsnbextension        3.2.1                    py36_0  
	wrapt                     1.10.11          py36hc29e774_0  
	xlrd                      1.1.0            py36h336f4a2_1  
	xlsxwriter                1.0.4                    py36_0  
	xlwings                   0.11.8                   py36_0  
	xlwt                      1.2.0            py36h5ad1178_0  
	xz                        5.2.4                h1de35cc_4  
	yaml                      0.1.7                hc338f04_2  
	zeromq                    4.2.5                h378b8a2_0  
	zict                      0.1.3            py36h71da714_0  
	zlib                      1.2.11               hf3cbc9b_2
    </pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
/anaconda3/bin/pythonw: line 3: /anaconda3/python.app/Contents/MacOS/python: No such file or directory
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
NA
</pre>
</details>

**Comment by jasongrout** [comment]
>       jupyterlab 0.32.1 OK

That is a *very* old version of JupyterLab. You might try installing with `conda install -c conda-forge jupyterlab=2`, or using the anaconda version `conda install jupyterlab=2` if you are using all anaconda packages.
