### ISSUE TITLE
Pass session id in headers as opposed to concatenating in URL

### ISSUE THREAD

**Issue by tirumerla** [jupyterlab/jupyterlab#9481]
Hi @blink1073 @jasongrout,

As an extension to #9387 ,  I was wondering if we could pass `session_id` in request headers as opposed to concatenating with URL even though it's only an informational identifier as a best practice.
https://github.com/jupyterlab/jupyterlab/blob/3d81e1ae214ff0c9591fc31772f48093a9635e05/packages/services/src/kernel/default.ts#L1219

Wondering what you guys think about it?

Thanks.

**Comment by tirumerla** [comment]
Any update on this?

**Comment by tirumerla** [comment]
Hey @blink1073 @jasongrout could you guys respond to this? This is blocking our development; we would like to get your opinion on this on how we can move the session id to be part of the cookie within headers.

**Comment by minrk** [comment]
session id is not really sensitive information, so leaking it in the url ought to be no more relevant than leaking the kernel id which is also in the url. It's not used for authentication or anything like that.

> if we could pass session_id in request headers 

Unfortunately, [headers cannot be set on websockets](https://stackoverflow.com/a/4361358/938949), so this can't be done for a javascript application.

**Comment by tirumerla** [comment]
Thanks @minrk for the response and the confirmation. Makes sense to me.
