### ISSUE TITLE
Make Copy Path more useful

### ISSUE THREAD

**Issue by dlukes** [jupyterlab/jupyterlab#9485]
### Problem

The file browser context menu currently offers a *Copy Path* command which copies the path to the item relative to the file browser's root dir. This is not really helpful when trying to copy a path to paste into a file located elsewhere than in the file browser's root. Consider a layout like this:

```
.
├── foo
│  └── bar.ipynb
└── baz.txt
```

If I'm working on `bar.ipynb` and I copy the path to `baz.txt`, it will be just `baz.txt`, which is not appropriate for pasting into `bar.ipynb`.

### Proposed Solution

Could *Copy Path* copy the absolute file path to the item instead of the relative one? Alternatively, there could be an additional *Copy Absolute Path* command if there's a reason to keep the original command around. (I personally would rather not, it's a footgun for beginners.)

A more complicated solution would be for *Copy Path* to yield a path relative not to the file browser's root, but relative to the directory of the file currently being edited.

### Additional context

#4074, which originally requested the *Copy Path* feature, [mentioned both relative and absolute paths as options in the OP](https://github.com/jupyterlab/jupyterlab/issues/4074#issue-301350293), and one of the commenters expressed their [support for absolute paths](https://github.com/jupyterlab/jupyterlab/issues/4074#issuecomment-371573947). No one argued specifically for relative paths, though admittedly not many people weighed in.

**Comment by amblina** [comment]
This would be really helpful for us. Our users are beginners working on jupyter potentially as their first experience of command line etc and this is something they trip up on regularly.

**Comment by giemmecci** [comment]
Yes! Please allow copying the absolute path instead of the relative one

**Comment by pauky** [comment]
+1, it will be very useful for us.
