### ISSUE TITLE
Quick easy landmark fixes plus 1 that's not

### ISSUE THREAD

**Issue by manfromjupyter** [jupyterlab/jupyterlab#9491]
So I overestimated. 24 lines + whatever for the final piece changed instead of just 8.

## Landmark Fixes (16 lines)
-Add Landmarks to various parts on the page so user can jump around at will.
- [x] The role of navigations should really be `<nav>` tags but role="navigation" will suffice for now. Lower risk of running into an issue with it with the build if just added an attribute instead of changing the tag. Same thing below for `<header>` and `<footer>`. If using `role="banner"` and `role="contentinfo"` is safer or easier approved, use them for now.
![aria-landmarks-1-edited](https://user-images.githubusercontent.com/51969207/102535032-a051d180-4075-11eb-8482-f6adde627f1c.png)
s://user-images.githubusercontent.com/51969207/102534965-8912e400-4075-11eb-8d2e-e5caa21300e7.png)
![aria-landmarks-2-edited](https://user-images.githubusercontent.com/51969207/102534976-8adca780-4075-11eb-944d-74b4c638ac70.png)
![aria-landmarks-3-edited](https://user-images.githubusercontent.com/51969207/102534981-8ca66b00-4075-11eb-8e0f-291703c05d7f.png)

- [x] THEN, apply a similar `role="region"` and `aria-label="{TAB NAME}"` to the `<div>` on each of the other side bar pages when expanded (ex. "Extensions Manager section", "Running Terminal and Kernel section", "Open Tabs section", "Commands sections", and "Property Inspector section").

## Housekeeping Items (8 lines)
- [x] Remove <header> tags from numerous areas that shouldn't have it. Instead replace with a head **ing** or a div.
![sessions tab section change headers to div](https://user-images.githubusercontent.com/51969207/102407824-b8b0e600-3fba-11eb-8e57-977cea19e016.PNG)
![open tabs change from header to div](https://user-images.githubusercontent.com/51969207/102407825-b8b0e600-3fba-11eb-917b-934eb5bf5002.PNG)
![packages section change from header to div](https://user-images.githubusercontent.com/51969207/102407827-b9497c80-3fba-11eb-81df-0df0103960a7.PNG)
![change header tag to div](https://user-images.githubusercontent.com/51969207/102407828-b9497c80-3fba-11eb-9671-cb8bc0d55d80.PNG)
- [ ] Remove tab-index="-1" on the header main nav section. Not breaking anything just doesn't do anything so doesn't need to be there and will make it harder to next steps after this.
![remove-tabindex--1-on-header---edited](https://user-images.githubusercontent.com/51969207/102534858-6da7d900-4075-11eb-9140-81079cba6e21.png)

## The Main Nav Menu issue and possible fixes (not as easy)
- [ ] With the changes above we get the following as shown in the screenshots. What this means via text is that the reason arrow keys don't work for the header main nav section is because clicking/entering on the `<li>` tag is the only thing that opens the dropdown. In the example below I show you what the screenreader sees. Main nav when jumped to, then the list of elements, the `<ul>` (which could get rid of by moving navigation role or `<nav>` element 1 deeper and then another arrow key jumps past the `<li>` and to div underneath it.
![header-on-region-jump-edited](https://user-images.githubusercontent.com/51969207/102534894-76001400-4075-11eb-8ccc-a6c23e86bbd8.png)
![header-down-arrow-once-edited](https://user-images.githubusercontent.com/51969207/102534895-76001400-4075-11eb-8ab4-405d55555fc9.png)
![header-on-second-down-arrow-edited](https://user-images.githubusercontent.com/51969207/102534893-76001400-4075-11eb-8f30-72898b794141.png)

### Potential Solutions to main nav menu issue
- [ ] Change script to accept if the text within the `<li>` is selected (note wont have additional padding so might make it harder for others to click it and the focus styling might not highlight all it used to.
- [ ] Change the HTML to get rid of the div and just put the text in the `<li>` and use the icon (although invisible) to be used as a :before element if it's even needed anymore.
- etc

One thing to note, whatever you do decide, we still need to make it all tabable so tabindexes and/or  `<a>` tags need to be added eventually so we will have to revisit this section anyway, don't need to go too crazy on it.

I know original issue was just to fix just this last issue but the JS on load jumps you past the header so need these landmarks (and need them for WCAG compliance eventually anyway).

**Comment by marthacryan** [comment]
Looks like that last item was actually fixed by the changes in the first part, so this issue is complete (there is still some tabindex stuff that needs to be addressed but that seems outside of the scope of this issue)
