### ISSUE TITLE
PDF viewer not working in Safari

### ISSUE THREAD

**Issue by huaiyuli** [jupyterlab/jupyterlab#9494]
## Description
Under Safari 14.0.2 running on macOS 11.1 with M1 chip, when opening a pdf file it does not open. Instead, it freezes the whole tab's controls. The safari development tools cannot be activated after this bug is triggered, and in some cases the page cannot close. Sometimes if the session in opened long enough to save the state then it happens again after reopening jupyterlab. In this case it looks like this:
<img width="1440" alt="Screenshot 2020-12-18 at 19 41 02" src="https://user-images.githubusercontent.com/68199579/102645014-73cbb180-416a-11eb-8574-b96cc12f8813.png">
With the wheel rolling and file list not loading, no button works. It happens with the official binder and official 3.0.0rc13 binder too, so it cannot be the problem with installation.
(BTW, disabling the two safari extensions does not help either.)

## Reproduce

1. Open a binder of the newest jupyterlab versions.
2. Open any PDF file in it.
3. The tab is frozen.

## Context

- Operating System and version: macOS 11.1
- Browser and version: Safari Version 14.0.2 (16610.3.7.1.9)
- JupyterLab version: 2.2.9, 3.0.0rc13

<details><summary>Troubleshoot Output</summary>
<pre>
Irrelevant since it happens with official binder too.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Nothing special. 
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Weirdly, not available.
</pre>
</details>

**Comment by sheinb** [comment]
## Same behavior observed on Intel Mac

Using JupyterLab 3.0.1 in Safari 14.0.2 on macOS 11.1 on a MacBook Pro (Intel i7) also hangs in the PDF preview window when a .pdf file is selected for viewing.  Chrome appears to work fine for this.
