### ISSUE TITLE
Fix linking in API docs

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9495]
In the upgrade at https://github.com/jupyterlab/jupyterlab/pull/9483, we noticed that our new typedoc configuration broke a lot of the nice linking we had before in the api docs.

See https://github.com/jupyterlab/jupyterlab/pull/9483#issuecomment-747614183, for example.

Setting as 3.0 since we'll be working on it, however if it doesn't get done in time for release, we can bump it.

**Comment by jasongrout** [comment]
@telamonian - just curious, were you planning on working on this before 3.0 (i.e., Wednesday)? I know you said it was fine for 3.0, but should be fixed soon - should I move this issue to 3.1? Either way is fine.

**Comment by blink1073** [comment]
cf https://github.com/TypeStrong/typedoc/issues/1414#issuecomment-747851855, the author of TypeDoc is aware of the issue but doesn't have a fix yet.  I'd say move this to 3.1.

**Comment by jasongrout** [comment]
The linking I'm talking about is not between the docs and the source files (those still work), but between the docs of different packages, i.e., the old documentation at https://jupyterlab.github.io/jupyterlab/modules/_fileeditor_extension_src_index_.html had working links to IStatusBar, JupyterFrontEnd, etc. - things defined in other packages. Now those links are not working:

<img width="743" alt="Screen Shot 2020-12-21 at 12 30 57 PM" src="https://user-images.githubusercontent.com/192614/102819496-68ee6800-4388-11eb-9337-2d14c1748f1b.png">

**Comment by blink1073** [comment]
The docs aren't hosted on https://jupyterlab.github.io anymore ;)

**Comment by blink1073** [comment]
Interesting, some of the links work, like https://jupyterlab.readthedocs.io/en/latest/api/classes/notebook_src.notebookmodel.contentfactory-1.html#modeldb has a link to https://jupyterlab.readthedocs.io/en/latest/api/interfaces/observables_src.imodeldb.html

**Comment by blink1073** [comment]
Might be parameterized links

**Comment by blink1073** [comment]
Or it could be an order issue as described in https://github.com/TypeStrong/typedoc/issues/1414#issue-758106090

**Comment by jasongrout** [comment]
> https://jupyterlab.readthedocs.io/en/latest/api/classes/notebook_src.notebookmodel.contentfactory-1.html#modeldb

Oh, nice, I was wondering where the docs were now. I'll update the links we have in the rst docs then too.

**Comment by fcollonval** [comment]
Closed by https://github.com/jupyterlab/jupyterlab/pull/14367
