### ISSUE TITLE
Determine exactly the right sharedPackages recommendation for token imports

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9496]
I've been recommending that if you import a token from a package that you are planning to require from the system, you should list that package in your sharedPackages config as `bundled: false, singleton: true`.

I'm not so sure we want `singleton: true`, because that ignores the version requirements. I think we still want `bundled: false`, to use the version of the token package provided by the service. Should we also recommend strictVersion to be true?

Here are the possible options: https://github.com/webpack/webpack/blob/eb58387a398b037e9d45cb473dcb7e98984ac0ea/declarations/plugins/sharing/ConsumeSharedPlugin.d.ts#L41-L74.

Lets say the `token` package exports a token that `provider` imports and uses to provide a service to the system, and `consumer` imports to request the service from the system. I think the options we need to decide are `bundled` (i.e., webpack's `import`), `singleton`, and `strictVersion`.

What should we recommend for these three options for the provider?
What should we recommend for these three options for a consumer requiring the service?
What should we recommend for these three options for a consumer requesting the service as an optional service?

Setting as 3.0 so we can get the documentation and cookiecutter straight on this.

**Comment by jasongrout** [comment]
For the `bundled` option (`bundled: false` translates to `import: false` in the webpack options, and signifies that version of the shared package will not be bundled):

The provider definitely should bundle the token package, since it will need it available no matter what other sharing and extensions are available.

For the consumer, if the token is optional, the consumer will need to bundle the token package--otherwise it would give errors if the optional service is not available, which defeats the purpose of the optional token.

If the token is required by the consumer, it's probably better to not bundle. It makes the consumer bundle smaller, ensures the consumer uses exactly the package the provider is sharing with the system, and doesn't upgrade the shared package the provider is using (if the consumer bundled a later version than the provider did, it would replace the provider version).

**Comment by blink1073** [comment]
I agree with the above for documentation, with a recommendation to keep the default `true` for `strictVersion` so you don't end up with an interface that doesn't match expectations.

Summary:
- `singleton` and `strictVersion` always `false` (both defaults)
- `bundled` is `true` if providing a token or consuming an optional token
- `bundled `is `false` if consuming a  required token

**Comment by jtpio** [comment]
> * `bundled` is `true` if providing a token or consuming an optional token

Isn't this going to create two instances of the token, making the third-party plugin that depends on the optional service fail to activate?

It sounds like the case of third-party plugins depending on optional services provided by other third-party plugins (for example `IJupyterWidgetRegistry` from `@jupyter-widgets/base` that might or might not be provided depending on whether `jupyterlab_widgets` is installed)

**Comment by jasongrout** [comment]
> with a recommendation to keep the default `true` for `strictVersion`

seems to contradict with your summary:

> singleton and strictVersion always false (both defaults)

Which are you recommending?

I think I would recommend strictVersion being true.

**Comment by blink1073** [comment]
> I think I would recommend strictVersion being true.

Good catch, I updated my summary

**Comment by jasongrout** [comment]
I spent some time today reacquainting myself with the webpack module federation code (it's been a while since I looked at it). Here are some notes.

The ModuleFederationPlugin [creates a SharePlugin](https://github.com/webpack/webpack/blob/eb58387a398b037e9d45cb473dcb7e98984ac0ea/lib/container/ModuleFederationPlugin.js#L74-L79) with the sharing config. There are two parts to the SharePlugin: configuring the modules we will [consume](https://github.com/webpack/webpack/blob/eb58387a398b037e9d45cb473dcb7e98984ac0ea/lib/sharing/SharePlugin.js#L47-L58), and configuring the modules we will [provide](https://github.com/webpack/webpack/blob/eb58387a398b037e9d45cb473dcb7e98984ac0ea/lib/sharing/SharePlugin.js#L59-L69). All modules that are shared are set up as being consumed, and that is the only place `strictVersion` and `singleton` are used.

For us, the `bundled` attribute (which defaults to true, and if false gets translated to `import: false` in the sharing config) just determines if the dependency is bundled and registered with the system. In general, that means that we may have many versions of any given module registered.

When someone wants to consume a module, the general strategy is to find the highest valid version (i.e., satisfying the requiredVersion). If `bundled: true`, then we know that there is at least one valid version. If no valid version exists, find the highest version at all. Note that if we have `bundled: true`, then we are providing a valid version to the system. We have the following cases:

* `bundled: true`, `strictVersion: true`, `singleton: true`: find the first version that has already been consumed by someone else (because we have `singleton: true`). If no version has been loaded, then find the highest valid version. If we are retreiving a version that has already been loaded and incompatible, then fail with an error (because we have `strictVersion: true`).
* `bundled: true`, `strictVersion: true` or `strictVersion: false`, `singleton: false`: find the highest valid version and return it.
* `bundled: true`, `strictVersion: false`, `singleton: true`: find the first version that has already been consumed by someone else (because we have `singleton: true`). If no version has been loaded, then find the highest valid version. If we are retrieving a version that has already been loaded and is incompatible, then log a warning and use it anyway.

* `bundled: false`, `strictVersion: true`, `singleton: true`: find the first version that has already been consumed by someone else (because we have `singleton: true`). If no version has been loaded, then find the highest valid version, and if no valid version exists, find the highest version at all. Then check to see if this version is valid (it may not be if someone else loaded an incompatible version, or if no valid version exists in the system). If we do not have a valid version, fail with an error (because we have `strictVersion: true`).
* `bundled: false`, `strictVersion: true`, `singleton: false`: find the highest valid version, and if one does not exist, find the highest version at all. Then check to see if this version is valid (it may not be if no valid version exists in the system, for example, if we did not bundle a copy). If we do not have a valid version, fail with an error (because we have `strictVersion: true`).
* `bundled: false`, `strictVersion: false`, `singleton: true`: find the first version that has already been consumed by someone else (because we have `singleton: true`). If no version has been loaded, then find the highest valid version, and if no valid version exists, find the highest version at all. If the version is invalid, log a warning and proceed with using that version of the module.
* `bundled: false`, `strictVersion: false`, `singleton: false`: Find the highest valid version, and if no valid version exists, find the highest version at all. If the version is invalid, log a warning and proceed with using that version of the module.

**Comment by jasongrout** [comment]
I think:

* `strictVersion` should always be true by default
* `singleton` should be true any time it is important for a package to be shared across all of jlab, e.g., any time a package exports a token
* when dealing with tokens, bundled is true if providing a token or consuming an optional token, and false if consuming a required token

**Comment by blink1073** [comment]
Nice detective work!  I like your most recent summary.

**Comment by jasongrout** [comment]
Closing as answered. I've incorporated these recommendations into the docs over at #9252.

**Comment by maartenbreddels** [comment]
Thanks Jason, very clarifying, feels like a Christmas 🎁

**Comment by jasongrout** [comment]
Thanks! Fyi, the summary information is in the docs at https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#deduplication-of-dependencies
