### ISSUE TITLE
Jupyter Lab UI Icons Not Showing on Launch #8006

### ISSUE THREAD

**Issue by JalalMirzayev** [jupyterlab/jupyterlab#9504]
## Description

Jupyter Lab UI Icons do not show up. In the first few seconds I can see the icons but then they are removed from the ui.

My system is a Windows 10, Python 3.7 and IntelliJ IDE.

What I have tried:
- Used three browsers: Edge, Chrome, Chromium and Opera and all show the same problem.
- Removed my virtual environment and reinstalled only jupyter lab (still same problem)
- Downgraded to version 1.2.7 (icons on left showed up like in #8006 but the other icons were not visible)
- Downgraded to version 2.0.0 (all icons are invisible after start up).
- Current version is 2.2.8
- Using jupyter notebook does not have the same issue.

**Comment by JalalMirzayev** [comment]
opening new notebook resolved the issue.

**Comment by jasongrout** [comment]
We've seen this happen before if a library adds CSS to the page that disables the icons on the page. For example, this was (is?) a long-standing problem with pyLDAviz library: https://github.com/jupyterlab/jupyterlab/issues/7959
