### ISSUE TITLE
Build linkcheck cache for the changelog

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9506]
Right now our link check is often timing out since it appears that GitHub is throttling us to one link check a minute. The changelog has a *lot* of links to GitHub.

I think we can make a PR that causes a series of action runs that gradually build up the link cache for the changelog links. For example, submit a PR that deletes most of the changelog, then adjust the link cache in the action file and submit another commit that adds a chunk of the changelog to continue requests. The important thing in gradually building up this cache is that each test *must* succeed in order for those links to be saved in the cache (caches are not saved unless the run was successful), and we must adjust the [name of the link cache](https://github.com/jupyterlab/jupyterlab/blob/36e051248472cccfd4244f327f92e3ec4be22f68/.github/workflows/linuxtests.yml#L70) slightly each time (so we save a new version) - I suggest just appending different to the cache name, so each cache builds on the previous one, just adding to it.

Eventually, we'll have all of the github links in the cache. Oh, I guess it's also important to do this over the period of a week or more, so that all of the links don't expire at the same time. In the end, I suppose we'll have to keep adjusting the cache name automatically so that the 1-week link timeout leads to a new cache being saved...

Or - we just ignore the changelog links for now in the link check? The other links in the documentation don't take that long to check.

**Comment by bollwyvl** [comment]
Howdy! I put the caching stuff into check-links, and am happy to help upstream if we can imagine a feature that would improve the situation... maybe some kind of arg for short-circuiting the request for certain patterns.

```bash
pytest-check-links --check-links-handlers='{"http://regex-in.json/in/bash/gah/.*": "some.alternate_checker"}'
```

Let's say we had that: if the bulk of the github links are things that will exist "forever" as data on the GitHub API, we could use (and cache) API requests, which yield you up to 100 issues per page. We could then keep _that_ around, either as a branch, or a separate repo altogether... might even make for some nice binder demos. This could be run nightly to capture incremental pages, as most issues would appear in the CHANGELOG after 24 hours, and what few that did would not strain the API rate limit too much, and be handled by the normal cache.

**Comment by jtpio** [comment]
Looks like most of this now comes from upstream actions, like `jupyterlab/maintainer-tools/.github/actions/base-setup@v1` defined here:

https://github.com/jupyterlab/jupyterlab/blob/d80bedb5633e53f5b773609a1fc56d7629ed65e5/.github/workflows/check-release.yml#L22-L23

Which handles the caching including markdown files like the changelog:

https://github.com/jupyterlab/maintainer-tools/blob/e6eae0613f9df3f9fca24b3d2deb1fa62b5b817d/.github/actions/base-setup/action.yml#L43-L50

With the actual link check now being performed by `jupyter-server/jupyter_releaser/.github/actions/check-links@v1`:

https://github.com/jupyterlab/jupyterlab/blob/d80bedb5633e53f5b773609a1fc56d7629ed65e5/.github/workflows/check-release.yml#L32-L34

Link checks have not been timing out recently, so I would say we can close this one and keep on eye on new timeouts if any.

Thanks all!
