### ISSUE TITLE
Jupyterlab 3.0 not launching extension and on chrome 

### ISSUE THREAD

**Issue by Jacques2101** [jupyterlab/jupyterlab#9512]
Hi, 
I tried to install 3.0 version of jupyterlab with ```conda install -c conda-forge jupyterlab=3.0 ```
the problems are : 

1. It is on safari and not chrome as the previous 2.2.9 version. It is as if it does not load jupyter_notebook_config file 
2. my extensions are not loaded 

## Context

- Operating System and version: MacOs Big Sur 
- Browser and version: Chrome normally but safari here (cf. the bug description)
- JupyterLab version:3.0.0

**Comment by jasongrout** [comment]
> It is on safari and not chrome as the previous 2.2.9 version. It is as if it does not load jupyter_notebook_config file

I'll let someone else answer that. We did switch to the Jupyter Server as the server, so perhaps that is what is going on.

> my extensions are not loaded

Extensions will need to be updated to work with JupyterLab 3

**Comment by echarles** [comment]
>> It is on safari and not chrome as the previous 2.2.9 version. It is as if it does not load jupyter_notebook_config file

> I'll let someone else answer that. We did switch to the Jupyter Server as the server, so perhaps that is what is going on.

@Jacques2101 You will need to rename `jupyter_notebook_config.py` to `jupyter_server_config.py`. We have ensured that the existing configuration of notebook `NotebokkApp`will show a warning so that you migrate/rename them to `ServerApp`, but you have to provide them in `jupyter_server_config.py`.

I realze that we don't have a documentation for that on https://jupyterlab.readthedocs.io/en/stable

**Comment by Jacques2101** [comment]
concerning the extensions, I should do something or it is the developpers job ?

**Comment by romainx** [comment]
@echarles The documentation explaining the change of `jupyter_server_config.py` can be found in [Migrating from Notebook Server][1].

[1]: https://jupyter-server.readthedocs.io/en/latest/operators/migrate-from-nbserver.html

**Comment by jasongrout** [comment]
This migration guide should be called out in the user-facing changes in the changelog. Right now, we only have a section in the developer-facing part, and it doesn't list that documentation: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#jupyter-server

**Comment by jasongrout** [comment]
> @jasongrout concerning the extensions, I should do something or it is the developpers job ?

Most likely a new version of the extension will need to be released, and often you are welcome to help contribute to the needed changes. As to it being the developers "job" - probably the extensions you are referring to are open source projects—the developers do not have an obligation to the public to do this work, and often appreciate help and support in such updates.

**Comment by krassowski** [comment]
Also, it might be good to have `_jupyter_labextension_paths` documented (I spent some time looking for it).

**Comment by Jacques2101** [comment]
What do you mean ?

**Comment by Jacques2101** [comment]
What do you mean ? Where it is ?   De : Michał Krassowski <notifications@github.com>Date : samedi, 2 janvier 2021 à 17:28À : jupyterlab/jupyterlab <jupyterlab@noreply.github.com>Cc : Jacques <jacques.tebeka@gmail.com>, Mention <mention@noreply.github.com>Objet : Re: [jupyterlab/jupyterlab] Jupyterlab 3.0 not launching extension and on chrome (#9512)Also, it might be good to have _jupyter_labextension_paths documented (I spent some time looking for it).—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jasongrout** [comment]
> Also, it might be good to have `_jupyter_labextension_paths` documented (I spent some time looking for it).

Can you open another issue for that (or even better, a pull request :).

**Comment by jasongrout** [comment]
I added a note to the changelog about migrating notebook configuration in #9546.

**Comment by jasongrout** [comment]
Fixed the todo item from the original issue - documenting migrating config from notebook to Jupyter server.
