### ISSUE TITLE
logout and control panel on Jupyter 3.0.0 and JupyterHub 1.3.0

### ISSUE THREAD

**Issue by spouyllau** [jupyterlab/jupyterlab#9517]
### Problem

On "file" menu, "logout" and "control panel" links no longer exist (?).

### Proposed Solution

Add "logout" and "control panel" on JupyterLab interface.

### Additional context

I'm on Jupyter 3.0.0 and JupyterHub 1.3.0, with oauthenticator.generic.GenericOAuthenticator. I note on Classic Notebook, this features exist.

**Comment by motionlife** [comment]
same issue here, does anyone know how to solve?

**Comment by motionlife** [comment]
Had to solve this problem by writing an extension myself. :), you can install mine, or just follow the extension dev example, very easy.
![Capture](https://user-images.githubusercontent.com/8056257/103335263-16711380-4a3a-11eb-8bce-8641db518bc2.JPG)

**Comment by spouyllau** [comment]
Thanks ! I'll see this ! But, officially isn't a important feature for users? Is there an official reason for his disappearance?

**Comment by motionlife** [comment]
> Thanks ! I'll see this ! But, officially isn't a important feature for users? Is there an official reason for his disappearance?
Yeah I agree. dunno y they miss it

**Comment by jasongrout** [comment]
> On "file" menu, "logout" and "control panel" links no longer exist (?).

I notice you invoke classic Notebook. Did they exist in previous JupyterLab versions as well?

**Comment by spouyllau** [comment]
Yes, on 2.2.9 in cases.
