### ISSUE TITLE
Feature: KernelSpec Management

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#9528]
### Problem

Jupyter assumes that there is some small number of variants of kernels I may want, so I should configure them on the command line and reuse them between notebooks. In practice this is only partially true; I find there are many parameters I wish I could pass to the kernel when creating a notebook (e.g. memory limit, environment variables, parameters to tell it where to find a host or reserve a GPU). We should make kernels drastically easier for users to parameterize.

### Proposed Solution

1. Create an API where kernel can be parameterized on the fly (this is an extension of the argv already in the `kernel.json`)
2. Create a small, extendable UI for common operations for all kernels (e.g. env variables).
  a. Taking this one step further, kernels could include opt-parse like data so the UI can let a user enter options in a constrained way along with descriptive help. If the UI is extendable, then the this is less important for me.
  b. Similar to kernel name, all kernel parameters should be stored in the notebook metadata.

### Additional context

N/A

**Comment by echarles** [comment]
Related to this enhancement request, a draft JEP is available [[DRAFT] Parameterized Kernel Launch](https://github.com/jupyter/enhancement-proposals/pull/46) and other issues have been opened:

- [Adding Option to Customize Parameters when Launching & Changing Kernels](https://github.com/jupyterlab/jupyterlab/issues/9374)  
- [Kernel gateway `envs` parameter](https://github.com/jupyterlab/jupyterlab/issues/7640)  

I think @blink1073 has also written something on this at some point, but can not find it back.

Adding also @kevin-bates and @Zsailer to this thread.

**Comment by jasongrout** [comment]
Can we add to the conversation over at https://github.com/jupyterlab/jupyterlab/issues/9374 rather than continuing this issue (and close this issue)? It will help us be more focused in our discussion, rather than scattering the conversation across multiple issues.

**Comment by echarles** [comment]
@jasongrout Makes sense. It looks like https://github.com/jupyterlab/jupyterlab/issues/9374 is targeted to Jupyter Enterprise Gateway while this feature requests is more generic for any kernel. I guess the impact on JupyterLab would be the same in those 2 options (launching a classic kernel vs launching a kernel via EG).

**Comment by mlucool** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/issues/9374
