### ISSUE TITLE
Opening empty CSV file doesn't work

### ISSUE THREAD

**Issue by adammclaurin** [jupyterlab/jupyterlab#9531]
It seems like opening an empty CSV file with JupyterLab causes an infinite loop (the page stalls). I'm using JupyterLab v2.2.8.

**Comment by krassowski** [comment]
I can confirm this bug, it is also on JupyterLab 3.0 when running from Chrome 87 and reproducible on Binder (which uses 2.x).

## To reproduce:

1. Create an empty file
2. Rename it to `something.csv`
3. Close the (text) file editor panel
4. Open the file in default CSV viewer
5. See error:

```typescript
model.js:437 Uncaught (in promise) RangeError: offset is out of bounds
    at Uint32Array.set (<anonymous>)
    at d._computeRowOffsets (model.js:437)
    at r (model.js:331)
    at d.parseAsync (model.js:352)
    at new d (model.js:98)
    at S._updateGrid (widget.js:295)
    at widget.js:209
_computeRowOffsets @ model.js:437
r @ model.js:331
parseAsync @ model.js:352
d @ model.js:98
_updateGrid @ widget.js:295
(anonymous) @ widget.js:209
Promise.then (async)
S @ widget.js:208
t @ widget.js:367
D @ widget.js:331
createNewWidget @ widget.js:380
createNew @ default.js:344
createWidget @ widgetmanager.js:62
_createOrOpenDocument @ manager.js:461
open @ manager.js:279
openOrReveal @ manager.js:303
_handleOpen @ listing.js:837
_evtDblClick @ listing.js:915
handleEvent @ listing.js:553
```

**Comment by jasongrout** [comment]
Here are two paths forward:

1. Shortcut the processing when we detect an empty file. This probably involves putting a bunch of special cases in various places in the code, and may not help if the file, say, is all whitespace (perhaps that is a problem too?)
2. The better fix is probably figuring out where the parsing is having a problem with the empty file, and solving the issue. Looks like it has an assumption somewhere that there is at least one offset or something.

Code is at https://github.com/jupyterlab/jupyterlab/tree/master/packages/csvviewer/src, and that specific function looks like it is at https://github.com/jupyterlab/jupyterlab/blob/22f33dabe5728cc0895815e27caca25e8ab5d174/packages/csvviewer/src/model.ts#L406
