### ISSUE TITLE
Get a Framework :: Jupyter :: Lab (:: 3) classifier

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab#9538]
### Problem

With more extensions being distributed on PyPI, and the discussions about discovering such extensions, it may be worth it to lobby for a [trove classifier](https://github.com/pypa/trove-classifiers).

### Proposed Solution

Propose the following new classifiers to `trove-classifiers` under the [existing `Framework :: Jupyter`](https://github.com/pypa/trove-classifiers/blob/master/src/trove_classifiers/__init__.py#L105) classifier:

```py
    ...
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 1",
    "Framework :: Jupyter :: JupyterLab :: 2",
    "Framework :: Jupyter :: JupyterLab :: 3",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Mime Renderers",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Themes",
    ...
```

Add this to docs, cookiecutters, etc. and link to the top-level search.

#### Versioned Classifiers
Since it was _possible_ to ship npm tarballs with `data_files` to `$PREFIX/share/lab/extensions` as far back as lab 1, the other version back-datings are not inaccurate, and no doubt would apply to _some_ extensions... but is unlikely to be retroactively added much, nor see many new releases. 

So we could just start with the versionless one  and the `3` version. I don't think a `Lab :: 3 Only` (such as exists for Python 3) offers much value... ideally, moving forward we will find a way to make `3+4` compatible extensions through common tooling, etc.

### Additional context

Unfortunately, it doesn't yet appear there is a readily-queryable way to use these classifiers programmatically for the extension manager... the old XML-RPC approach (which was/is down for a month) does have `browse` but the JSON API does not support this yet, apparently.

**Comment by jasongrout** [comment]
Thanks. We discussed this a while ago when talking about adding recommended keywords for pypi, but I can't find any record of the discussion in the issues, so thanks for making an issue!

+1 to applying for a trove classifier.

**Comment by jasongrout** [comment]
Ah, the discussion was over on the cookie cutter: https://github.com/jupyterlab/extension-cookiecutter-ts/issues/106#issuecomment-716037510

**Comment by bollwyvl** [comment]
We already have it!

https://github.com/pypa/trove-classifiers/blob/master/src/trove_classifiers/__init__.py#L105

**Comment by bollwyvl** [comment]
I think it's good for the brand to go nested, though `Jupyter :: JupyterLab` vs `Jupyter :: Lab` could be debated. I have a feeling hitting 10 :package:  is not going to be a problem :laughing: .

**Comment by bollwyvl** [comment]
Also, leave it to windows to demonstrate there is no nesting limit:
```
    "Operating System :: Microsoft :: Windows :: Windows Server 2008",
```

**Comment by jasongrout** [comment]
> We already have it!

Oh, nice! In that case, +1 to `:: Lab :: 3`.

I guess one argument for `JupyterLab` vs `Jupyter :: Lab` is that we've always written it as one word, JupyterLab, so it's a bit weird to break it up as if it was two words. But if we already have the Jupyter classifier, might as well use it - it will make for a stronger brand connection.

**Comment by bollwyvl** [comment]
except `jupyter lab --no-browser` but of course I see your point.

**Comment by bollwyvl** [comment]
Looking through it, other sluggers like `django` and `plone` go down to the `3.1` level... i guess that's a challenge for another day

**Comment by bollwyvl** [comment]
Discoverability came up a few times again on gitter, recently. I think is still probably offers the best, self-organizing way to get started, and can be complemented later by the "extension mall" approach or whatever we come up with.

Anyhow, cleaned up the text (and proposed classifiers) a bit.

Any more thoughts here? If there aren't loud objections, I think we should probably move forward with the PR so folks can start slapping this on their releases...

**Comment by telamonian** [comment]
@bollwyvl I think the classifier suggestions in your first post are really good. My only concern is that if we use eg:

```
"Framework :: Jupyter :: Lab :: 3"
```

 to discover the list of extensions for the frontend extensions UI, we might end up with at least some pypi packages (potentially including `jupyterlab` itself) that jlab 3 related, but aren't actually extensions.

I think we have two options to resolve this ambiguity:

- Add extension specific classifiers in addition to the ones @bollwyvl already suggested:
  ```
  "Framework :: Jupyter :: Lab :: 3 :: extension",
  "Framework :: Jupyter :: Lab :: 2 :: extension",
  ```

- In addition the trove classifiers, `setup.py` also supports a non-restricted `keywords` field. So we can require extension authors to add both a `"jupyterlab-extension"` keyword and a `"Framework :: Jupyter :: Lab :: 3"` classifier

Which sounds better to you guys?

refs:
https://packaging.python.org/specifications/core-metadata/#keywords
https://www.python.org/dev/peps/pep-0566/
https://setuptools.readthedocs.io/en/latest/references/keywords.html

**Comment by jasongrout** [comment]
>     * In addition the trove classifiers, `setup.py` also supports a non-restricted `keywords` field. So we can require extension authors to add both a `"jupyterlab-extension"` keyword and a `"Framework :: Jupyter :: Lab :: 3"` classifier

To me this sounds like a good idea.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/no-marketplace-for-jupyter-extensions/9141/2

**Comment by krassowski** [comment]
Should we go ahead an open an issue/PR on https://github.com/pypa/trove-classifiers? Is there a need to vote on `Jupyter :: Lab` vs `Jupyter :: JupyterLab``?

**Comment by bollwyvl** [comment]
Yeah, it would be good to get it going.

Even though `3.1` has some significant changes, I still think we want to stick to the major values so that it only takes one PR a year, and indicates that we are serious about not breaking backwards compatibility within major releases.

> Jupyter :: Lab vs Jupyter :: JupyterLab?

From an SEO perspective, `JupyterLab` is probably better, and most of the classifiers are very wordy anyways. I'd say if nobody strongly objects, we should move forward with that.

> "Framework :: Jupyter :: Lab :: 3 :: extension",

To avoid combinatorial explosion, perhaps we split these concerns, so something that ships a little of everything, works back to 1.0 release, includes its own base application (a la `retrolab`, `voila`), does something in IPython, exposes its own kernel, modifies how hub works, does some nbconvert junk, might have:

```
Framework :: IPython
Framework :: Jupyter :: Kernels
Framework :: Jupyter :: Widgets
Framework :: Jupyter :: nbconvert
Framework :: Jupyter :: nbconvert :: 5
Framework :: Jupyter :: nbconvert :: 6
Framework :: Jupyter :: nbconvert :: Templates
Framework :: Jupyter :: nbconvert :: Preprocessors
Framework :: Jupyter :: nbconvert :: Postprocessors
Framework :: Jupyter :: nbconvert :: Exporters
Framework :: Jupyter :: nbconvert :: Filters
Framework :: Jupyter :: JupyterHub
Framework :: Jupyter :: JupyterHub :: 1
Framework :: Jupyter :: JupyterHub :: Services
Framework :: Jupyter :: JupyterHub :: Authenticators
Framework :: Jupyter :: JupyterHub :: Spawners
Framework :: Jupyter :: JupyterLab :: 1
Framework :: Jupyter :: JupyterLab :: 2
Framework :: Jupyter :: JupyterLab :: 3
Framework :: Jupyter :: JupyterLab :: Themes
Framework :: Jupyter :: JupyterLab :: Extensions
Framework :: Jupyter :: JupyterLab :: Renderers
Framework :: Jupyter :: JupyterLab :: Applications
Framework :: Jupyter :: Server :: Extension
```

This takes cues from existing nested classifiers... and might benefit from coordinating with more parts of the ecosystem so we're not nickle-and-diming little PRs. I'll hoist this to discourse.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/expanding-the-jupyter-trove-classifier-on-pypi/9928/1

**Comment by bollwyvl** [comment]
Opened up this: https://github.com/jupyterlab/jupyterlab/pull/10731

**Comment by vidartf** [comment]
Closable now?

**Comment by bollwyvl** [comment]
Let's keep it until the warehouse pr is merged. 😜

**Comment by astrojuanlu** [comment]
xref: https://github.com/pypa/warehouse/pull/9882

**Comment by fcollonval** [comment]
Closing as the classifiers are official now.

> I updated the initial post to reflect the final classifiers list.

**Comment by bollwyvl** [comment]
Thanks! 😊
