### ISSUE TITLE
Enter debug on exception

### ISSUE THREAD

**Issue by e-dorigatti** [jupyterlab/jupyterlab#9544]
This extension is gold, thank you!

I would like to propose a new feature, namely to enter debug when an uncaught exception occurs. This would allow the user to directly investigate the crime scene, check variables, and so on. It would really help development, especially when long-running computations are involved.

This would work just like when you run a script through `python -m ipdb -c c script.py`, and get a pdb prompt in case of troubles.

**Comment by goanpeca** [comment]
Pinging @mlucool

**Comment by krassowski** [comment]
Closing since #9544 was merged.
