### ISSUE TITLE
Log Console ignores logging log level

### ISSUE THREAD

**Issue by ItamarShDev** [jupyterlab/jupyterlab#9554]
When using logging logger, the log level seems to be ignored, and all logs prints to info level.

See attached:

No log at Error level:      
![image](https://user-images.githubusercontent.com/953371/103639487-1a7bc480-4f57-11eb-8cac-28795a504b57.png)

Log is in Info level:     
![image](https://user-images.githubusercontent.com/953371/103639522-24052c80-4f57-11eb-9812-13b6da6bcca1.png)

How to reproduce:
```python
import logging
l = logging.getLogger('je')
l.error("Error!")
```
Will print to the info level

> JupyterLab 2.0.1

**Comment by jasongrout** [comment]
Thanks for asking. The jlab log console is not for displaying python log messages, but for logging messages from JupyterLab frontend components themselves.

Closing as answered.

**Comment by jasongrout** [comment]
(The notebook logs all output it receives as info messages, for example - that's what you are seeing)

**Comment by ofirbit** [comment]
I've also noticed this issue. Frontend Javascript errors actually appear only on the browser debug console (F12), not in the jlog log console. I've also noticed that we do get the correct error level when logging from an Ipywidgets observe callback. I wonder why it doesn't work on a normal log print.

![image](https://user-images.githubusercontent.com/45560972/103740408-d395d980-4fff-11eb-9f7c-51b30271db72.png)

**Comment by jasongrout** [comment]
Right - jlab components themselves are responsible for sending things to the logs. ipywidgets explicitly sends things to the log (in this case, output from a notebook that the user would not normally see), and other components can explicitly log things to the log console as well if they want.

Errors in the js components themselves are js errors logged in the browser console, as is standard for web applications. Those errors are mainly for developers of jlab and extensions, not end-users of jlab.
