### ISSUE TITLE
Jupyter lab 3.0.1 and jupyterhub

### ISSUE THREAD

**Issue by enriqueartal** [jupyterlab/jupyterlab#9558]
## Description

After upgrading to jupyterlab 3.0.0 (the same with 3.0.3), a jupyterhub installation fails at interpretting LaTeX commands in Markdown (no output) and also to display with the command show in Sagemath. It works executing directly jupyter lab.

Best, Enrique.

## Reproduce

1. Log in a jupyterhub server in a system with jupyterlab 3.
2. If the the hub config file contains the line `c.Spawner.cmd = ['jupyterhub-singleuser'] ` it opens a jupyterlab session. Markdown cells do not interpret LaTeX commands. If the kernel is sage, the command show produces no output. The menu `File` does not contain `Hub control panel` and `log out` entries
3.  If the the hub config file contains the line `c.Spawner.cmd = ['jupyter-labhub'] `a 404 page shows, nothing to do even changing lab to tree in the address line of the browser.

## Expected behavior

Normal behaviour as it happens with jupyter lab 2.2.9.

## Context

- Fedora 33:
- Chrome 87.0.4280.141:
- JupyterLab version:3.0.3

**Comment by twrobinson** [comment]
I am getting the same behaviour -- 404 with JupyterLab 3.x from JupyterHub 1.3 (or earlier). I have the  c.Spawner.cmd = ['jupyter-labhub']. With c.Spawner.cmd = ['jupyterhub-singleuser'] I get lab, but without the Hub menu items, as expected. This issue should be fixed in https://github.com/jupyterlab/jupyterlab/pull/9256, so I'm trying to work out why it's failing.

**Comment by enriqueartal** [comment]
In the second case, do you have also the issue about LaTeX input and markdown? For me, it happens with the kernel of Sage but also with Python3

**Comment by twrobinson** [comment]
Yes, same issue with LaTeX. As these are probably unrelated issues it might be worth resubmitting them as separate issues?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-with-jupyterlab-3-x-getting-404/7482/3

**Comment by enriqueartal** [comment]
Not now, but thanks since maybe someone could post a solution there. Thanks! Anyway, I will resubmit the Markdwon-LaTeX issue.

> This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:
> 
> https://discourse.jupyter.org/t/jupyterhub-with-jupyterlab-3-x-getting-404/7482/3

**Comment by blink1073** [comment]
Fixed by #9604, will cut a release today.

**Comment by enriqueartal** [comment]
Confirmed, it works using jupyter-labhub in the config (menu and MathJax). Thanks!
