### ISSUE TITLE
Lab3.x: In Simple Interface, there isn't an obvious way to close the Advanced Settings Editor tab

### ISSUE THREAD

**Issue by pybokeh** [jupyterlab/jupyterlab#9559]
## Description

Not sure if this is a bug, but when I'm in "Simple Interface" mode, if I then go to "Settings" menu, then click on "Advanced Settings Editor", the Settings" tab shows up, but there isn't an obvious way to close the settings tab.  I notice that when I go back to the Settings menu at the top, the check mark is not to the left of "Advanced Settings Editor" label, this is where I'm not sure if there is supposed to be a check mark or not.  So I clicked on the "Advanced Settings Editor" label again, but that didn't close the Settings tab.  I also tried CTRL+, but didn't close the Settings tab.  So there is only 2 ways to close the Settings tab.  Turn off "Simple Interface" mode, then you can click on the "X" to close out the Settings tab.  The other way is to go to "File" menu, then choose "Close Tab".

For better UX experience, I would hope we can provide a much better method to close the "Settings" tab while in "Simple Interface" mode.

Browser: Chrome version 87

**Comment by jasongrout** [comment]
I think it's a general issue with any tab, not just Advanced Settings, right?

You can also go to the tabs sidebar and close it from there.

In general, there should probably be an easy way to close a tab in Simple Interface - perhaps an X on the far right, across from the document title?

**Comment by pybokeh** [comment]
@jasongrout Thanks for you response.  Yes, you are right.  This is actually a problem for any tab that is open in Simple Interface mode.  I guess due to the check mark symbols next to the options, I guess I thought the tab would toggle on and off.  

If you mean the tabs sidebar on the left for "Running Terminals and Kernels", then yes, I realized you can close the Settings tab there.  So I guess that's a 3rd way to close the Settings tab.  I didn't think to look there since I thought it was for terminals and kernels.

I do like your suggestion for an X on the far right.  That sounds reasonable and intuitive to me.  You can mark this as a features enhancement if you like.

**Comment by jasongrout** [comment]
Let's move this discussion over to #9117, then, where we are consolidating feedback about the simple interface.

I've summarized over there at https://github.com/jupyterlab/jupyterlab/issues/9117#issuecomment-754993302
