### ISSUE TITLE
Add helper for Windows on `jupyter labextension develop`

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab#9564]
symlink is not allowed by default on Windows. So that line will failed

https://github.com/jupyterlab/jupyterlab/blob/136d2ec216ebfc429a696e6ee75fee5f8ead73e2/jupyterlab/federated_labextensions.py#L113

But on Windows 10 with Python >= 3.8, users can activate the developer mode to allow them.

https://docs.python.org/3/library/os.html#os.symlink
https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development

What about updating the documentation to point that out and maybe catch the OSError to print a more user friendly error in such case.

**Comment by ktaletsk** [comment]
This is really useful information and should probably be included in the documentation.
Also, to save everybody a click, you can enable it in Developer Settings -> Choose Developer mode instead of Sideload apps

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/extension-development-on-windows/9286/4
