### ISSUE TITLE
Interactive console while debugging

### ISSUE THREAD

**Issue by Steph71** [jupyterlab/jupyterlab#9570]
### Problem

When Debugging my python code I usually run to the point where I suspect the problem. To do so I set a breakpoint in my favourite IDE. Then I drop into an interactive console, where I can execute arbitrary code. I am using variants of pydev for that.

Now I am very pleased that jupyterlab adds support for visual debugging. But when I hit a breakpoint I can only statically observe variables and the stack. I cannot use a debug console to interactively evaluate my workspace ....

or am I missing something ?

### Proposed Solution

Provide an option to open an interactive console, that is still resonsive, if a breakpoint is hit.

### Additional context

pycharm amd pydev (eclipse) have an ineractive debug console, that can evaluate arbitrary python code, after a script has stoppend at a breakpoint

**Comment by jtpio** [comment]
Thanks @Steph71.

This sounds similar to: https://github.com/jupyterlab/jupyterlab/issues/9111 (I just updated the title of the issue so it's more explicit)

Should we move the discussion there so it's all in one place?

**Comment by Steph71** [comment]
yes, this is the 100 % replicate ...  so we can close this and followup there.
