### ISSUE TITLE
Jupyter lab --no-browser opens browser

### ISSUE THREAD

**Issue by Eisbrenner** [jupyterlab/jupyterlab#9575]
macos bs: 11.1
python: 3.8.5
jupyter lab: 3.0.1
nodejs: v15.2.1

## Description

When running the following command

```bash
jupyter lab --no-browser
```

jupyter opens in a browser.

## Logs

```
jupyter lab --no-browser            
[I 2021-01-08 15:02:12.087 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2021-01-08 15:02:12.099 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-01-08 15:02:12.332 ServerApp] The module 'jupyterlab_black' could not be found. Are you sure the extension is installed?
[I 2021-01-08 15:02:12.812 ServerApp] dask_labextension | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2021-01-08 15:02:12.812 ServerApp] dask_labextension | extension was successfully linked.
[I 2021-01-08 15:02:12.813 ServerApp] jupyter_server_proxy | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2021-01-08 15:02:12.813 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2021-01-08 15:02:12.813 ServerApp] nbclassic | extension was successfully linked.
[I 2021-01-08 15:02:12.842 ServerApp] dask_labextension | extension was successfully loaded.
[W 2021-01-08 15:02:12.867 ServerApp] Failed to fetch commands from language server spec finder`python-language-server`:
    'NoneType' object has no attribute 'origin'
Traceback (most recent call last):
  File "/miniconda3/lib/python3.8/site-packages/jupyter_lsp/manager.py", line 209, in _autodetect_language_servers
    specs = spec_finder(self)
  File "/miniconda3/lib/python3.8/site-packages/jupyter_lsp/specs/utils.py", line 74, in __call__
    if not spec.origin:  # pragma: no cover
AttributeError: 'NoneType' object has no attribute 'origin'
[I 2021-01-08 15:02:12.926 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2021-01-08 15:02:12.940 ServerApp] jupyter_server_proxy | extension was successfully loaded.
[I 2021-01-08 15:02:12.941 LabApp] JupyterLab extension loaded from /miniconda3/lib/python3.8/site-packages/jupyterlab
[I 2021-01-08 15:02:12.941 LabApp] JupyterLab application directory is /miniconda3/share/jupyter/lab
[I 2021-01-08 15:02:12.945 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-01-08 15:02:12.949 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-01-08 15:02:12.949 ServerApp] Serving notebooks from local directory: 
[I 2021-01-08 15:02:12.949 ServerApp] Jupyter Server 1.2.0 is running at:
[I 2021-01-08 15:02:12.949 ServerApp] http://localhost:8888/lab?token=f5abd5617372a591a45f0b03904568ab3eaf70
[I 2021-01-08 15:02:12.950 ServerApp]  or http://127.0.0.1:8888/lab?token=f5abd5617372a591a45f02cb8ca1904568ab3eaf70
[I 2021-01-08 15:02:12.950 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-01-08 15:02:12.955 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Library/Jupyter/runtime/jpserver-38800-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=f5abd5617372a591a45f02a1960b03904568ab3eaf70
     or http://127.0.0.1:8888/lab?token=f5abd5617372a591a45f960b03904568ab3eaf70
[W 2021-01-08 15:02:17.548 LabApp] The extension "@jupyterlab/toc" is outdated.
    
[W 2021-01-08 15:02:17.551 LabApp] The extension "dask-labextension" is outdated.
    
[I 2021-01-08 15:02:18.236 LabApp] Build is up to date
```

**Comment by evanpjensen** [comment]
Also experiencing this issue on Linux.

**Comment by blink1073** [comment]
The new release of `jupyter_server` should fix this (`pip install -U jupyter_server`), cf https://github.com/jupyter-server/jupyter_server/pull/379

**Comment by cmarquardt** [comment]
Also happens on MacOS, with jupyter-server 1.2.1 - that's the latest version available from pypi and also from GitHub right now. 

Is that the one that should fix it?

**Comment by jasongrout** [comment]
Can you check with JupyterLab 3.0.3, jupyter_server 1.2.1, and jupyterlab_server 2.1.1?

**Comment by jasongrout** [comment]
Note that the `open_browser` option defaults to:

* False in ServerApp
* True in ExtensionApp
* (inherited as) True in LabApp

The more specific configuration takes precedence. So if you just set ServerApp.open_browser to False, the ExtensionApp/LabApp setting True value takes precedence. So do:

```
c.LabApp.open_browser=False
```
to make sure Lab does not open a browser (or `c.ExtensionApp.open_browser=False`).

**Comment by jasongrout** [comment]
> to make sure Lab does not open a browser (or `c.ExtensionApp.open_browser=False`).

That's why the help for `--no-browser` says:

```
--no-browser
    Prevent the opening of the default url in the browser.
    Equivalent to: [--ServerApp.open_browser=False --ExtensionApp.open_browser=False]
```
because the open_browser setting default is changed between ServerApp and ExtensionApp, the ExtensionApp needs to be set.

**Comment by cmarquardt** [comment]
Ah - thanks - for the information to upgrade and also for the explanation of the configuration options. Yes, this works.

I think part of the problem was that for some reason I generated the configuration file with `jupyter server --generate-config` which doesn't have any ExtensionApp settings inside. With  `jupyter lab --generate-config` I produced one which had them inside, including documentation...

By the way, when there's both a `jupyter_server_config.py` and a `jupyter_lab_config.py` configuration file in `~/.jupyter`, it seems that the server configuration file is used, not the one for Jupyter Lab - is that intended?

I understand that the confusion and some lack of documentation (the Jupyter Lab documentation still mentions `jupyter_notebook_config.py`which does, however, seem to be ignored with Jupyter Lab 3) are due to the ongoing transition to v3 - many, many thanks to you for taking the time to explain here!

**Comment by jasongrout** [comment]
This should be fixed with our most recent release of jupyterlab, jupyterlab_server, and jupyter_server.

**Comment by jasongrout** [comment]
> By the way, when there's both a `jupyter_server_config.py` and a `jupyter_lab_config.py` configuration file in `~/.jupyter`, it seems that the server configuration file is used, not the one for Jupyter Lab - is that intended?

Good question. Not sure - hopefully someone chimes in about this.

> I understand that the confusion and some lack of documentation (the Jupyter Lab documentation still mentions `jupyter_notebook_config.py`which does, however, seem to be ignored with Jupyter Lab 3) are due to the ongoing transition to v3 - many, many thanks to you for taking the time to explain here!

Do you want to submit a PR? We probably missed updating that part of the documentation.

**Comment by Eisbrenner** [comment]
Thanks, updating to `jupyter_server>=1.2.1` solved this for me :)

**Comment by eromoe** [comment]
```
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-core                       4.7.1
jupyter-packaging                  0.7.12
jupyter-server                     1.4.1
jupyterlab                         3.0.14
jupyterlab-pygments                0.1.2
jupyterlab-server                  2.4.0
jupyterlab-widgets                 1.0.0
```

Below doesn't work
```
jupyter_lab_config.py   :  c.ServerApp.open_browser = False
jupyter_notebook_config.py   :  c.NotebookApp.open_browser = False
```

Don't open browser after adding
```
c.LabApp.open_browser=False
c.ExtensionApp.open_browser=False
```
