### ISSUE TITLE
Data visualization using Poltly

### ISSUE THREAD

**Issue by birdalugureren** [jupyterlab/jupyterlab#9584]
I want to visualize my data using the Plotly chart library. Everything works fine in the jupyter notebook. But jupyterlab does not show anything.

![Screenshot from 2021-01-09 15-01-55](https://user-images.githubusercontent.com/26383184/104091029-c9880b00-528b-11eb-8ce3-51c11e43264d.png)

**Comment by Alexboiboi** [comment]
Hi @birdalugureren,
The plotly extensions habe not yet been updated.
See here plotly/plotly.py#2994

**Comment by jasongrout** [comment]
Plotly has now been updated.
