### ISSUE TITLE
Workspace restoration issue

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9590]
## Description

Using the latest `3.0.3` JupyterLab, it looks like there is an issue with the restorer:

![workspace-restoration](https://user-images.githubusercontent.com/591645/104137535-dbf26980-539d-11eb-8480-57068c92971c.gif)

This might be related to the issue mentioned in https://github.com/jupyterlab/jupyterlab-demo/pull/102 that uses the `jupyter lab workspaces import` command to load a default workspace.

## Reproduce

1. Open 2 documents side by side
2. Save the current workspace as.
3. Close the documents
4. Right click to open the workspace with the `Workspaces loader`
5. Wait for the reload 
6. The two documents are not restored

## Expected behavior

Opening the workspace file should restore the two documents previously created.

## Context

- Operating System and version: Ubuntu 20.04
- Browser and version: Firefox 84 and Latest Chromium
- JupyterLab version: 3.0.3

**Comment by jasongrout** [comment]
I confirmed that the steps you show above also have the same result for me in 3.0.4, latest Firefox, macOS Catalina.

**Comment by LustigePerson** [comment]
To me it seems like workspaces are not correctly loaded at all. I had a workspace defined for our server in JLab 2.* and I can't manage to have this workspaces loaded with JLab 3.0. Unfortunately there is also nothing to be found in the debug log.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/create-a-jupyterhub/9188/4

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/mybinder-jupyterlab-link-to-a-repo-subfolder-works-but-not-to-a-specific-notebook-in-that-folder/9443/4

**Comment by krassowski** [comment]
Could it be also the cause of https://github.com/jupyterlab/jupyterlab/issues/10195?
