### ISSUE TITLE
JupyterLab 3 returns blank page

### ISSUE THREAD

**Issue by gabrielecalvo** [jupyterlab/jupyterlab#9592]
## Description

I have tried installing the new version of JupyterLab (version 3) on a fresh conda environament but when I run "jupyter lab" from the terminal an empty page opens on 

## Reproduce

1. create a conda environment with the new version of Lab: `conda create -n test -c conda-forge jupyterlab=3`
2. activate the enviroment `conda activate test`
3. run `jupyter lab`

A blank page opens on http://localhost:8888/lab

Opening the js console I see the following messages (the first is an error):
> main.41ae8658af88b434f6d9.js:1 Uncaught SyntaxError: Unexpected token '?'
> content.js:94 Content Server Web Browser Extension: not applicable for href='http://localhost:8888/lab'; 

If I downgrade to version 2 with `conda install -c conda-forge jupyterlab=2` then I see the usual interface correctly.

## Expected behavior

On loading of http://localhost:8888/lab the juptyer lab interface should be rendered

## Context

- Operating System and version: Windows 10
- Browser and version: Chrome Version 77.0.3865.120 (Official Build) (64-bit)
- JupyterLab version: 3.0.3

<details><summary>Troubleshoot Output</summary>
<pre>
jupyter troubleshoot
$PATH:
        C:\Users\Gabe\Anaconda3\envs\test
        C:\Users\Gabe\Anaconda3\envs\test\Library\mingw-w64\bin
        C:\Users\Gabe\Anaconda3\envs\test\Library\usr\bin
        C:\Users\Gabe\Anaconda3\envs\test\Library\bin
        C:\Users\Gabe\Anaconda3\envs\test\Scripts
        C:\Users\Gabe\Anaconda3\envs\test\bin
        C:\Users\Gabe\Anaconda3\condabin
        C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0
        C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files\Git\cmd
        C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn
        C:\Program Files\curl-7.72.0-win64-mingw\bin
        .
        C:\Program Files\Git LFS
        C:\Program Files\Docker\Docker\resources\bin
        C:\ProgramData\DockerDesktop\version-bin
        C:\Users\Gabe\AppData\Local\Programs\Python\Python38
        C:\Users\Gabe\AppData\Local\Programs\Python\Python38\Scripts
        C:\Users\Gabe\AppData\Local\Programs\Microsoft VS Code\bin
        C:\Users\Gabe\AppData\Local\GitHubDesktop\bin
        C:\Users\Gabe\Anaconda3
        C:\Users\Gabe\Anaconda3\Lib
        C:\Users\Gabe\Anaconda3\Scripts
        C:\Users\Gabe\AppData\Local\Microsoft\WindowsApps
        C:\Users\Gabe\AppData\Local\Graphviz\bin
        .

sys.path:
        C:\Users\Gabe\Anaconda3\envs\test\Scripts
        C:\Users\Gabe\Anaconda3\envs\test\python39.zip
        C:\Users\Gabe\Anaconda3\envs\test\DLLs
        C:\Users\Gabe\Anaconda3\envs\test\lib
        C:\Users\Gabe\Anaconda3\envs\test
        C:\Users\Gabe\Anaconda3\envs\test\lib\site-packages
        C:\Users\Gabe\Anaconda3\envs\test\lib\site-packages\win32
        C:\Users\Gabe\Anaconda3\envs\test\lib\site-packages\win32\lib
        C:\Users\Gabe\Anaconda3\envs\test\lib\site-packages\Pythonwin

sys.executable:
        C:\Users\Gabe\Anaconda3\envs\test\python.exe

sys.version:
        3.9.1 | packaged by conda-forge | (default, Jan 10 2021, 02:50:22) [MSC v.1916 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.18362-SP0

where jupyter:
        C:\Users\Gabe\Anaconda3\envs\test\Scripts\jupyter.exe
        C:\Users\Gabe\AppData\Local\Programs\Python\Python38\Scripts\jupyter.exe
        C:\Users\Gabe\Anaconda3\Scripts\jupyter.exe

pip list:
        Package                       Version
        ----------------------------- -------------------
        anyio                         2.0.2
        argon2-cffi                   20.1.0
        async-generator               1.10
        attrs                         20.3.0
        Babel                         2.9.0
        backcall                      0.2.0
        backports.functools-lru-cache 1.6.1
        bleach                        3.2.1
        brotlipy                      0.7.0
        certifi                       2020.12.5
        cffi                          1.14.4
        chardet                       4.0.0
        colorama                      0.4.4
        cryptography                  3.3.1
        decorator                     4.4.2
        defusedxml                    0.6.0
        entrypoints                   0.3
        idna                          2.10
        importlib-metadata            3.4.0
        ipykernel                     5.4.2
        ipython                       7.19.0
        ipython-genutils              0.2.0
        jedi                          0.18.0
        Jinja2                        2.11.2
        json5                         0.9.5
        jsonschema                    3.2.0
        jupyter-client                6.1.11
        jupyter-core                  4.7.0
        jupyter-server                1.2.1
        jupyterlab                    3.0.3
        jupyterlab-pygments           0.1.2
        jupyterlab-server             2.1.1
        MarkupSafe                    1.1.1
        mistune                       0.8.4
        nbclassic                     0.2.6
        nbclient                      0.5.1
        nbconvert                     6.0.7
        nbformat                      5.0.8
        nest-asyncio                  1.4.3
        notebook                      6.1.6
        packaging                     20.8
        pandocfilters                 1.4.2
        parso                         0.8.1
        pickleshare                   0.7.5
        pip                           20.3.3
        prometheus-client             0.9.0
        prompt-toolkit                3.0.10
        pycparser                     2.20
        Pygments                      2.7.3
        pyOpenSSL                     20.0.1
        pyparsing                     2.4.7
        pyrsistent                    0.17.3
        PySocks                       1.7.1
        python-dateutil               2.8.1
        pytz                          2020.5
        pywin32                       228
        pywinpty                      0.5.7
        pyzmq                         20.0.0
        requests                      2.25.1
        Send2Trash                    1.5.0
        setuptools                    49.6.0.post20210108
        six                           1.15.0
        sniffio                       1.2.0
        terminado                     0.9.2
        testpath                      0.4.4
        tornado                       6.1
        traitlets                     5.0.5
        urllib3                       1.26.2
        wcwidth                       0.2.5
        webencodings                  0.5.1
        wheel                         0.36.2
        win-inet-pton                 1.1.0
        wincertstore                  0.2
        zipp                          3.4.0

conda list:
        # packages in environment at C:\Users\Gabe\Anaconda3\envs\test:
        #
        # Name                    Version                   Build  Channel
        anyio                     2.0.2            py39hcbf5309_4    conda-forge
        argon2-cffi               20.1.0           py39hb82d6ee_2    conda-forge
        async_generator           1.10                       py_0    conda-forge
        attrs                     20.3.0             pyhd3deb0d_0    conda-forge
        babel                     2.9.0              pyhd3deb0d_0    conda-forge
        backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
        backports                 1.0                        py_2    conda-forge
        backports.functools_lru_cache 1.6.1                      py_0    conda-forge
        bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
        brotlipy                  0.7.0           py39ha3862ff_1001    conda-forge
        ca-certificates           2020.12.5            h5b45459_0    conda-forge
        certifi                   2020.12.5        py39hcbf5309_1    conda-forge
        cffi                      1.14.4           py39h0878f49_1    conda-forge
        chardet                   4.0.0            py39hcbf5309_1    conda-forge
        colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
        cryptography              3.3.1            py39h0878f49_1    conda-forge
        decorator                 4.4.2                      py_0    conda-forge
        defusedxml                0.6.0                      py_0    conda-forge
        entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
        idna                      2.10               pyh9f0ad1d_0    conda-forge
        importlib-metadata        3.4.0            py39hcbf5309_0    conda-forge
        importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
        ipykernel                 5.4.2            py39he1a07ef_0    conda-forge
        ipython                   7.19.0           py39h832f523_0    conda-forge
        ipython_genutils          0.2.0                      py_1    conda-forge
        jedi                      0.18.0           py39hcbf5309_2    conda-forge
        jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
        json5                     0.9.5              pyh9f0ad1d_0    conda-forge
        jsonschema                3.2.0                      py_2    conda-forge
        jupyter_client            6.1.11             pyhd8ed1ab_0    conda-forge
        jupyter_core              4.7.0            py39hcbf5309_0    conda-forge
        jupyter_server            1.2.1            py39hcbf5309_0    conda-forge
        jupyterlab                3.0.3              pyhd8ed1ab_0    conda-forge
        jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
        jupyterlab_server         2.1.1              pyhd8ed1ab_0    conda-forge
        libsodium                 1.0.18               h8d14728_1    conda-forge
        m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
        m2w64-gcc-libs            5.3.0                         7    conda-forge
        m2w64-gcc-libs-core       5.3.0                         7    conda-forge
        m2w64-gmp                 6.1.0                         2    conda-forge
        m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
        markupsafe                1.1.1            py39hb82d6ee_3    conda-forge
        mistune                   0.8.4           py39hb82d6ee_1003    conda-forge
        msys2-conda-epoch         20160418                      1    conda-forge
        nbclassic                 0.2.6              pyhd8ed1ab_0    conda-forge
        nbclient                  0.5.1                      py_0    conda-forge
        nbconvert                 6.0.7            py39hcbf5309_3    conda-forge
        nbformat                  5.0.8                      py_0    conda-forge
        nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
        notebook                  6.1.6            py39hcbf5309_0    conda-forge
        openssl                   1.1.1i               h8ffe710_0    conda-forge
        packaging                 20.8               pyhd3deb0d_0    conda-forge
        pandoc                    2.11.3.2             h8ffe710_0    conda-forge
        pandocfilters             1.4.2                      py_1    conda-forge
        parso                     0.8.1              pyhd8ed1ab_0    conda-forge
        pickleshare               0.7.5                   py_1003    conda-forge
        pip                       20.3.3             pyhd8ed1ab_0    conda-forge
        prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
        prompt-toolkit            3.0.10             pyha770c72_0    conda-forge
        pycparser                 2.20               pyh9f0ad1d_2    conda-forge
        pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
        pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
        pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
        pyrsistent                0.17.3           py39hb82d6ee_2    conda-forge
        pysocks                   1.7.1            py39hcbf5309_3    conda-forge
        python                    3.9.1           h7840368_3_cpython    conda-forge
        python-dateutil           2.8.1                      py_0    conda-forge
        python_abi                3.9                      1_cp39    conda-forge
        pytz                      2020.5             pyhd8ed1ab_0    conda-forge
        pywin32                   228              py39hb82d6ee_1    conda-forge
        pywinpty                  0.5.7            py39hde42818_1    conda-forge
        pyzmq                     20.0.0           py39h6e08c89_1    conda-forge
        requests                  2.25.1             pyhd3deb0d_0    conda-forge
        send2trash                1.5.0                      py_0    conda-forge
        setuptools                49.6.0           py39hcbf5309_3    conda-forge
        six                       1.15.0             pyh9f0ad1d_0    conda-forge
        sniffio                   1.2.0            py39hcbf5309_1    conda-forge
        sqlite                    3.34.0               h8ffe710_0    conda-forge
        terminado                 0.9.2            py39hcbf5309_0    conda-forge
        testpath                  0.4.4                      py_0    conda-forge
        tornado                   6.1              py39hb82d6ee_1    conda-forge
        traitlets                 5.0.5                      py_0    conda-forge
        tzdata                    2020f                he74cb21_0    conda-forge
        urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
        vc                        14.2                 hb210afc_2    conda-forge
        vs2015_runtime            14.28.29325          h5e1d092_0    conda-forge
        wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
        webencodings              0.5.1                      py_1    conda-forge
        wheel                     0.36.2             pyhd3deb0d_0    conda-forge
        win_inet_pton             1.1.0            py39hcbf5309_2    conda-forge
        wincertstore              0.2             py39hcbf5309_1006    conda-forge
        winpty                    0.4.3                         4    conda-forge
        zeromq                    4.3.3                h0e60522_3    conda-forge
        zipp                      3.4.0                      py_0    conda-forge

conda env:
        name: test
        channels:
          - conda-forge
          - defaults
        dependencies:
          - anyio=2.0.2=py39hcbf5309_4
          - argon2-cffi=20.1.0=py39hb82d6ee_2
          - async_generator=1.10=py_0
          - attrs=20.3.0=pyhd3deb0d_0
          - babel=2.9.0=pyhd3deb0d_0
          - backcall=0.2.0=pyh9f0ad1d_0
          - backports=1.0=py_2
          - backports.functools_lru_cache=1.6.1=py_0
          - bleach=3.2.1=pyh9f0ad1d_0
          - brotlipy=0.7.0=py39ha3862ff_1001
          - ca-certificates=2020.12.5=h5b45459_0
          - certifi=2020.12.5=py39hcbf5309_1
          - cffi=1.14.4=py39h0878f49_1
          - chardet=4.0.0=py39hcbf5309_1
          - colorama=0.4.4=pyh9f0ad1d_0
          - cryptography=3.3.1=py39h0878f49_1
          - decorator=4.4.2=py_0
          - defusedxml=0.6.0=py_0
          - entrypoints=0.3=pyhd8ed1ab_1003
          - idna=2.10=pyh9f0ad1d_0
          - importlib-metadata=3.4.0=py39hcbf5309_0
          - importlib_metadata=3.4.0=hd8ed1ab_0
          - ipykernel=5.4.2=py39he1a07ef_0
          - ipython=7.19.0=py39h832f523_0
          - ipython_genutils=0.2.0=py_1
          - jedi=0.18.0=py39hcbf5309_2
          - jinja2=2.11.2=pyh9f0ad1d_0
          - json5=0.9.5=pyh9f0ad1d_0
          - jsonschema=3.2.0=py_2
          - jupyter_client=6.1.11=pyhd8ed1ab_0
          - jupyter_core=4.7.0=py39hcbf5309_0
          - jupyter_server=1.2.1=py39hcbf5309_0
          - jupyterlab=3.0.3=pyhd8ed1ab_0
          - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
          - jupyterlab_server=2.1.1=pyhd8ed1ab_0
          - libsodium=1.0.18=h8d14728_1
          - m2w64-gcc-libgfortran=5.3.0=6
          - m2w64-gcc-libs=5.3.0=7
          - m2w64-gcc-libs-core=5.3.0=7
          - m2w64-gmp=6.1.0=2
          - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
          - markupsafe=1.1.1=py39hb82d6ee_3
          - mistune=0.8.4=py39hb82d6ee_1003
          - msys2-conda-epoch=20160418=1
          - nbclassic=0.2.6=pyhd8ed1ab_0
          - nbclient=0.5.1=py_0
          - nbconvert=6.0.7=py39hcbf5309_3
          - nbformat=5.0.8=py_0
          - nest-asyncio=1.4.3=pyhd8ed1ab_0
          - notebook=6.1.6=py39hcbf5309_0
          - openssl=1.1.1i=h8ffe710_0
          - packaging=20.8=pyhd3deb0d_0
          - pandoc=2.11.3.2=h8ffe710_0
          - pandocfilters=1.4.2=py_1
          - parso=0.8.1=pyhd8ed1ab_0
          - pickleshare=0.7.5=py_1003
          - pip=20.3.3=pyhd8ed1ab_0
          - prometheus_client=0.9.0=pyhd3deb0d_0
          - prompt-toolkit=3.0.10=pyha770c72_0
          - pycparser=2.20=pyh9f0ad1d_2
          - pygments=2.7.3=pyhd8ed1ab_0
          - pyopenssl=20.0.1=pyhd8ed1ab_0
          - pyparsing=2.4.7=pyh9f0ad1d_0
          - pyrsistent=0.17.3=py39hb82d6ee_2
          - pysocks=1.7.1=py39hcbf5309_3
          - python=3.9.1=h7840368_3_cpython
          - python-dateutil=2.8.1=py_0
          - python_abi=3.9=1_cp39
          - pytz=2020.5=pyhd8ed1ab_0
          - pywin32=228=py39hb82d6ee_1
          - pywinpty=0.5.7=py39hde42818_1
          - pyzmq=20.0.0=py39h6e08c89_1
          - requests=2.25.1=pyhd3deb0d_0
          - send2trash=1.5.0=py_0
          - setuptools=49.6.0=py39hcbf5309_3
          - six=1.15.0=pyh9f0ad1d_0
          - sniffio=1.2.0=py39hcbf5309_1
          - sqlite=3.34.0=h8ffe710_0
          - terminado=0.9.2=py39hcbf5309_0
          - testpath=0.4.4=py_0
          - tornado=6.1=py39hb82d6ee_1
          - traitlets=5.0.5=py_0
          - tzdata=2020f=he74cb21_0
          - urllib3=1.26.2=pyhd8ed1ab_0
          - vc=14.2=hb210afc_2
          - vs2015_runtime=14.28.29325=h5e1d092_0
          - wcwidth=0.2.5=pyh9f0ad1d_2
          - webencodings=0.5.1=py_1
          - wheel=0.36.2=pyhd3deb0d_0
          - win_inet_pton=1.1.0=py39hcbf5309_2
          - wincertstore=0.2=py39hcbf5309_1006
          - winpty=0.4.3=4
          - zeromq=4.3.3=h0e60522_3
          - zipp=3.4.0=py_0
        prefix: C:\Users\Gabe\Anaconda3\envs\test
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 2021-01-11 10:19:13.232 ServerApp] Searching ['C:\\Users\\Gabe', 'C:\\Users\\Gabe\\.jupyter', 'C:\\Users\\Gabe\\Anaconda3\\envs\\test\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 2021-01-11 10:19:13.233 ServerApp] Looking for jupyter_config in C:\ProgramData\jupyter
[D 2021-01-11 10:19:13.235 ServerApp] Looking for jupyter_config in C:\Users\Gabe\Anaconda3\envs\test\etc\jupyter
[D 2021-01-11 10:19:13.235 ServerApp] Looking for jupyter_config in C:\Users\Gabe\.jupyter
[D 2021-01-11 10:19:13.238 ServerApp] Looking for jupyter_config in C:\Users\Gabe
[D 2021-01-11 10:19:13.239 ServerApp] Looking for jupyter_server_config in C:\ProgramData\jupyter
[D 2021-01-11 10:19:13.240 ServerApp] Looking for jupyter_server_config in C:\Users\Gabe\Anaconda3\envs\test\etc\jupyter
[D 2021-01-11 10:19:13.241 ServerApp] Looking for jupyter_server_config in C:\Users\Gabe\.jupyter
[D 2021-01-11 10:19:13.241 ServerApp] Looking for jupyter_server_config in C:\Users\Gabe
[D 2021-01-11 10:19:13.246 ServerApp] Paths used for configuration of jupyter_server_config:
        C:\ProgramData\jupyter\jupyter_server_config.json
[D 2021-01-11 10:19:13.247 ServerApp] Paths used for configuration of jupyter_server_config:
        C:\Users\Gabe\Anaconda3\envs\test\etc\jupyter\jupyter_server_config.d\jupyterlab.json
        C:\Users\Gabe\Anaconda3\envs\test\etc\jupyter\jupyter_server_config.d\nbclassic.json
        C:\Users\Gabe\Anaconda3\envs\test\etc\jupyter\jupyter_server_config.json
[D 2021-01-11 10:19:13.251 ServerApp] Paths used for configuration of jupyter_server_config:
        C:\Users\Gabe\.jupyter\jupyter_server_config.json
[I 2021-01-11 10:19:13.274 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-01-11 10:19:13.298 ServerApp] The 'min_open_files_limit' trait of a ServerApp instance expected an int, not the NoneType None.
[D 2021-01-11 10:19:13.298 ServerApp] Ignoring min_open_files_limit because the limit cannot be adjusted (for example, on Windows)
[I 2021-01-11 10:19:13.346 LabApp] JupyterLab extension loaded from C:\Users\Gabe\Anaconda3\envs\test\lib\site-packages\jupyterlab
[I 2021-01-11 10:19:13.346 LabApp] JupyterLab application directory is C:\Users\Gabe\Anaconda3\envs\test\share\jupyter\lab
[I 2021-01-11 10:19:13.352 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-01-11 10:19:13.776 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-01-11 10:19:14.001 ServerApp] Serving notebooks from local directory: C:\Users\Gabe
[I 2021-01-11 10:19:14.001 ServerApp] Jupyter Server 1.2.1 is running at:
[I 2021-01-11 10:19:14.002 ServerApp] http://localhost:8888/lab?token=c3ececba5ef25c9923d73f487e73a9d008427321895cdfc3
[I 2021-01-11 10:19:14.005 ServerApp]  or http://127.0.0.1:8888/lab?token=c3ececba5ef25c9923d73f487e73a9d008427321895cdfc3
[I 2021-01-11 10:19:14.005 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-01-11 10:19:14.085 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/Gabe/AppData/Roaming/jupyter/runtime/jpserver-3732-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=c3ececba5ef25c9923d73f487e73a9d008427321895cdfc3
     or http://127.0.0.1:8888/lab?token=c3ececba5ef25c9923d73f487e73a9d008427321895cdfc3
[D 2021-01-11 10:19:15.386 ServerApp] Accepting token-authenticated connection from ::1
[D 2021-01-11 10:19:15.393 ServerApp] Paths used for configuration of page_config:
        C:\ProgramData\jupyter\labconfig\page_config.json
[D 2021-01-11 10:19:15.395 ServerApp] Paths used for configuration of page_config:
        C:\Users\Gabe\Anaconda3\envs\test\etc\jupyter\labconfig\page_config.json
[D 2021-01-11 10:19:15.397 ServerApp] Paths used for configuration of page_config:
        C:\Users\Gabe\.jupyter\labconfig\page_config.json
[D 2021-01-11 10:19:15.404 LabApp] Using contents: services/contents
[D 2021-01-11 10:19:15.416 LabApp] 200 GET /lab?token=c3ececba5ef25c9923d73f487e73a9d008427321895cdfc3 (::1) 31.00ms
[D 2021-01-11 10:19:15.444 ServerApp] Path main.41ae8658af88b434f6d9.js served from C:\Users\Gabe\Anaconda3\envs\test\share\jupyter\lab\static\main.41ae8658af88b434f6d9.js
[D 2021-01-11 10:19:15.446 ServerApp] 304 GET /static/lab/main.41ae8658af88b434f6d9.js (::1) 4.00ms
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Uncaught SyntaxError: Unexpected token '?'
content.js:94 Content Server Web Browser Extension: not applicable for href='http://localhost:8888/lab'; 
</pre>
</details>

**Comment by jasongrout** [comment]
Can you try running `jupyter lab clean` after the 3.0 upgrade?

**Comment by jasongrout** [comment]
I just checked on Windows 10, and it works for me with JupyterLab 3.0.3 (though using Chrome 87, not 77).

Your error message makes me think this has to do with an extension you have installed in chrome - I don't know of a "content.js" file having a "Content Server Web Browser Extension". Can you try (a) using Chrome incognito mode with no extensions, (b) typing in the URL manually (`http://localhost:8888/lab`), or (c) using a different browser?

**Comment by gabrielecalvo** [comment]
Hi Jason,
Thank you very much for the quick reply. 

It looks like it might be an extension since it works fine on Firefox.
I can't remove/deactivate the extension as it is applied by policy but it looks like that might be the issue.

Thank you very much again. Great work with this project!
You can close the issue.

**Comment by jasongrout** [comment]
Just curious: is it a public extension? If so, can you list what it is? It might help others with the same issue.

**Comment by gabrielecalvo** [comment]
> Just curious: is it a public extension? If so, can you list what it is? It might help others with the same issue.

Yes, it is a public one, here is the link: https://chrome.google.com/webstore/detail/content-server-browser-we/hlphpjodcfdblfmbbdjodbfmlonmidfh

Although, while looking for the link I realised that the "allow in incognito" is set to false so it shouldn't be running in incognito, but I am still having the same issue there.

**Comment by jasongrout** [comment]
Actually, looking at the error more closely, it looks like it is two lines and two different errors. The first line is: `main.41ae8658af88b434f6d9.js:1 Uncaught SyntaxError: Unexpected token '?'`.

Can you look in the browser debugger to see why that file has a `?` as the first character? You can see it in the Network Tools, if you look at that request response. It seems that you are getting a file that may not be javascript.

**Comment by gabrielecalvo** [comment]
That was a great idea. I think the issue is with the "??" nullish coalescing operator that is only supported in Chrome 80+:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

**Comment by jasongrout** [comment]
Looks like this file has a `??` that it shouldn't: https://github.com/jupyterlab/jupyterlab/blob/45a0516f94f2ddfaa7cbca8a3569a405276627b0/dev_mode/bootstrap.js#L34

**Comment by jasongrout** [comment]
Do you want to submit a PR? If not, I'll probably submit a PR today fixing this.

**Comment by jasongrout** [comment]
I submitted #9606 to try to get it into today's patch release.

**Comment by gabrielecalvo** [comment]
Wow, that was quick. Thanks Jason!

**Comment by jasongrout** [comment]
@gabrielecalvo, can you try 3.0.4, which was just released?

**Comment by gabrielecalvo** [comment]
> @gabrielecalvo, can you try 3.0.4, which was just released?

yep, works like a charm 👍 
thank you

**Comment by osdiego** [comment]
Hello,

I'm trying to use the 3.x versions but I can't, always a blank page (all browsers). I can use 1.x and 2.x versions, do you have any idea?

Thank you!

**Comment by sparanoid** [comment]
@osdiego @bsun0802 What web browser are you using and the specific version? 

IFIAK the nullish coalescing operator introduced in ES2020 only works for newer browsers:

https://caniuse.com/mdn-javascript_operators_nullish_coalescing

This usage should be transpiled for compatibility.

**Comment by bsun0802** [comment]
@sparanoid I'm using the newest safari browse.

**Comment by pbdanny** [comment]
Hi also experience the same problem on Mac Safari
Jupiter : 3.0.11
Safari : 14.0.3

Revert back to Jupiter lab 3 could solved the issue (with `conda install jupyter=2`)

**Comment by jasongrout** [comment]
Please update to jlab 3.0.12. There was an issue with safari and 3.0.11.
