### ISSUE TITLE
[Debugger] Starts the debugger for many notebooks

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/jupyterlab#9595]
## Description

With the last release, it is impossible to start the debugger for other notebooks that the first opened.

## Reproduce

- Launch a xpython kernel. The toggle button to start the debugger is visible in the upper right corner of the notebook panel.
- Launch a new xpython kernel. The toggle button is missing, and you canno tdebug the second notebook.

## Expected behavior

It is possible to start and debug many kernels.

## Context

- Operating System and version: Gentoo (but reproducible on Binder)
- Browser and version: Google Chrome
- JupyterLab version: 3.0.3 (and 3.0.0 on Binder)

**Comment by jtpio** [comment]
Thanks @JohanMabille.

I can confirm this is an issue with `3.0.3` when testing on Binder:

![debugger-only-one](https://user-images.githubusercontent.com/591645/104204895-0c81e400-542e-11eb-9ec5-830f2efa8ab9.gif)
