### ISSUE TITLE
Extract a title updater module

### ISSUE THREAD

**Issue by akosyakov** [jupyterlab/jupyterlab#960]
Currently there is a duplicate code between the editor widget and notebook to update a title based on a document context, e.g. change a title name and manage dirty state styles. User defined UI components most likely would like to apply the same logic. It would be nice to have a separate module that can be applied to any widget from any widget factory.

**Comment by ellisonbg** [comment]
Yep!

**Comment by ellisonbg** [comment]
This would probably go into apputils now.

**Comment by jasongrout** [comment]
This is done now in the #3499
