### ISSUE TITLE
Remove 15MB upload limit

### ISSUE THREAD

**Issue by HuJK** [jupyterlab/jupyterlab#9601]
## Description

There is a hardcoded 15MB upload limit in new version of jupytelab, please fix it.

![image](https://user-images.githubusercontent.com/15907444/104290011-c2b00100-54f4-11eb-90d7-5f317c505bba.png)

## Reproduce

1. install jupyterlab==3.0.3
2. Go to jupyterlab
3. Upload a file which > 15MB

## Expected behavior

 I downgrade jupyterlab to version 2.0.0, It works.

![image](https://user-images.githubusercontent.com/15907444/104289778-84b2dd00-54f4-11eb-967f-08a81c6a06c3.png)
![image](https://user-images.githubusercontent.com/15907444/104289834-93998f80-54f4-11eb-860d-a706bb0a2e87.png)

## Context

- Operating System and version: Ububtu 20.04
- Browser and version: Google Chrome 87.0.4280.88
- JupyterLab version: jupyterlab==3.0.3

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games

sys.path:
        /usr/local/bin
        /usr/lib/python38.zip
        /usr/lib/python3.8
        /usr/lib/python3.8/lib-dynload
        /usr/local/lib/python3.8/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3

sys.version:
        3.8.5 (default, Jul 28 2020, 12:59:40)
        [GCC 9.3.0]

platform.platform():
        Linux-5.4.0-60-generic-x86_64-with-glibc2.29

which -a jupyter:
        /usr/local/bin/jupyter

pip list:
        Package                Version
        ---------------------- --------------------
        acme                   1.11.0
        alembic                1.4.3
        anyio                  2.0.2
        argon2-cffi            20.1.0
        async-generator        1.10
        attrs                  19.3.0
        Automat                0.8.0
        Babel                  2.9.0
        backcall               0.2.0
        beautifulsoup4         4.9.3
        bleach                 3.2.1
        blinker                1.4
        certbot                1.11.0
        certbot-dns-cloudflare 1.11.0
        certbot-dns-powerdns   0.2.0
        certifi                2019.11.28
        certipy                0.1.3
        cffi                   1.14.4
        chardet                3.0.4
        Click                  7.0
        cloud-init             20.2
        cloudflare             2.8.15
        colorama               0.4.3
        command-not-found      0.3
        ConfigArgParse         1.2.3
        configobj              5.0.6
        constantly             15.1.0
        cryptography           2.8
        dbus-python            1.2.16
        decorator              4.4.2
        defusedxml             0.6.0
        distro                 1.4.0
        distro-info            0.23ubuntu1
        dns-lexicon            3.5.3
        dnspython              2.1.0
        entrypoints            0.3
        filelock               3.0.12
        future                 0.18.2
        httplib2               0.14.0
        hyperlink              19.0.0
        idna                   2.8
        importlib-metadata     1.5.0
        incremental            16.10.1
        ipykernel              5.4.2
        ipython                7.19.0
        ipython-genutils       0.2.0
        jedi                   0.18.0
        Jinja2                 2.10.1
        josepy                 1.5.0
        Js2Py                  0.70
        json5                  0.9.5
        jsonlines              2.0.0
        jsonpatch              1.22
        jsonpointer            2.0
        jsonschema             3.2.0
        jupyter-client         6.1.11
        jupyter-core           4.7.0
        jupyter-server         1.2.1
        jupyter-telemetry      0.1.0
        jupyterhub             1.3.0
        jupyterlab             3.0.3
        jupyterlab-pygments    0.1.2
        jupyterlab-server      2.1.1
        keyring                18.0.1
        language-selector      0.1
        launchpadlib           1.10.13
        lazr.restfulclient     0.14.2
        lazr.uri               1.0.3
        Mako                   1.1.3
        MarkupSafe             1.1.0
        mistune                0.8.4
        mock                   4.0.3
        more-itertools         4.2.0
        nbclassic              0.2.6
        nbclient               0.5.1
        nbconvert              6.0.7
        nbformat               5.0.8
        nest-asyncio           1.4.3
        netifaces              0.10.4
        notebook               6.1.6
        oauthlib               3.1.0
        packaging              20.8
        pamela                 1.0.0
        pandocfilters          1.4.3
        parsedatetime          2.6
        parso                  0.8.1
        pcp                    5.0
        pexpect                4.8.0
        pickleshare            0.7.5
        pip                    20.3.3
        prometheus-client      0.9.0
        prompt-toolkit         3.0.10
        ptyprocess             0.7.0
        pyasn1                 0.4.2
        pyasn1-modules         0.2.1
        pycparser              2.20
        Pygments               2.7.3
        PyGObject              3.36.0
        PyHamcrest             1.9.0
        pyjsparser             2.7.1
        PyJWT                  1.7.1
        pymacaroons            0.13.0
        PyNaCl                 1.3.0
        pyOpenSSL              19.0.0
        pyparsing              2.4.7
        pyRFC3339              1.1
        pyrsistent             0.15.5
        pyserial               3.4
        python-apt             2.0.0+ubuntu0.20.4.3
        python-dateutil        2.8.1
        python-debian          0.1.36ubuntu1
        python-editor          1.0.4
        python-json-logger     2.0.1
        pytz                   2020.5
        PyYAML                 5.3.1
        pyzmq                  20.0.0
        requests               2.22.0
        requests-file          1.5.1
        requests-toolbelt      0.9.1
        requests-unixsocket    0.2.0
        ruamel.yaml            0.16.12
        ruamel.yaml.clib       0.2.2
        SecretStorage          2.3.1
        Send2Trash             1.5.0
        service-identity       18.1.0
        setuptools             45.2.0
        simplejson             3.16.0
        six                    1.14.0
        sniffio                1.2.0
        soupsieve              2.1
        speedtest              0.0.1
        SQLAlchemy             1.3.22
        ssh-import-id          5.10
        systemd-python         234
        terminado              0.9.2
        testpath               0.4.4
        tldextract             3.1.0
        tornado                6.1
        traitlets              5.0.5
        Twisted                18.9.0
        tzlocal                2.1
        ubuntu-advantage-tools 20.3
        ufw                    0.36
        unattended-upgrades    0.1
        urllib3                1.25.8
        wadllib                1.3.3
        wcwidth                0.2.5
        webencodings           0.5.1
        wheel                  0.34.2
        zipp                   1.0.0
        zope.component         4.6.2
        zope.deferredimport    4.3.1
        zope.deprecation       4.4.0
        zope.event             4.5.0
        zope.hookable          5.0.1
        zope.interface         4.7.1
        zope.proxy             4.3.5
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Nothing shown
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Cannot upload file (>15 MB). ubuntu-20.04.1-live-server-amd64.iso
upload @ jlab_core.a6bd38f47ff66b08e9e2.js:formatted:28380
(anonymous) @ jlab_core.a6bd38f47ff66b08e9e2.js:formatted:27880
_onInputChanged @ jlab_core.a6bd38f47ff66b08e9e2.js:formatted:27880

![image](https://user-images.githubusercontent.com/15907444/104290610-85983e80-54f5-11eb-8b77-a8cc8cd5d94b.png)
</pre>
</details>

# My comment

It's hardcoded 15MB upload limit in frontend. 
I use jupyterlab as a server management tool instead of a python environment cuz browser is much more convenient than FileZilla.
I need to to upload large file usually, and my server & my browser can handle it. 
Maybe we can configure it instead?

![image](https://user-images.githubusercontent.com/15907444/104292210-816d2080-54f7-11eb-9abc-d21acf05a788.png)
=================
![image](https://user-images.githubusercontent.com/15907444/104292128-65697f00-54f7-11eb-9431-7f614c7b0e44.png)

**Comment by wldh-g** [comment]
I agree with @HuJK . I usually upload experiment sensor data and download trained ML model in convenient using jupyterlab web interface, and their sizes are generally over 15MB.

**Comment by jasongrout** [comment]
That hard-coded limit is for notebook < 5.1. The problem here is that we've switched to Jupyter Server, and it advertises itself as notebook version 1.2.1.

I've removed the check, now that we do not have to accommodate notebook 5.0 or earlier.

**Comment by jasongrout** [comment]
Fixed in https://github.com/jupyterlab/jupyterlab/pull/9616
