### ISSUE TITLE
JupyterHub, JupyterLab 3 and MarkDown-LaTeX

### ISSUE THREAD

**Issue by enriqueartal** [jupyterlab/jupyterlab#9605]
## Description

After upgrading to jupyterlab 3.0.3, when using jupyterhub, markdown cells cannot interpret `LaTeX` commands in markdown.  See https://github.com/jupyterlab/jupyterlab/issues/9558 for some maybe unrelated issues.

## Reproduce

1. Type, e.g., `$x+1$` in a markdown cell (with kernels Python3 or Sage). Other option type `show(x)` in a code cell with Sage kernel
2. In the first case, after evaluating, the characters `$x+1$` are still shown. In the second case nothing appears.

## Expected behavior

For the first case the evaluated markdown would be shown, interpretting the LaTeX orders. For the second case, a typeset output would be shown. That's what happens in the same computer when jupyter lab runs outside jupyterhub.

## Context

- Operating System and version: Fedora 33 fully updated
- Browser and version: Chrome 87.0.4280.141
- JupyterLab version: 3.0.3

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by blink1073** [comment]
This can be fixed by updating your version of `jupyterlab_server` to 2.1.1

**Comment by twrobinson** [comment]
MathJax rendering fixed in 2.1.2. Thanks @blink1073 !
