### ISSUE TITLE
New table style truncates columns

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterlab/jupyterlab#961]
Whilst I like the aesthetics of the new table styles introduced in #904 it appears that columns are being truncated so that you can't actually see your data!
![image](https://cloud.githubusercontent.com/assets/881019/18861959/40ae4326-84cc-11e6-9495-e17a97bbd690.png)

IMHO it would be good if the columns expanded to fit the size of the content

**Comment by jorisvandenbossche** [comment]
I also commented about this on the original pull request: https://github.com/jupyter/jupyterlab/pull/910#issuecomment-248599489. In any case, the current limit is a serious usability issue and is too low I think.

I personally would go for putting no limit on the width whatsoever in jupyter, and leaving it to the libraries that produce the tables (like pandas) to provide limited output as they see best (eg in pandas the maximum width of the column in configurable, so you can always see the full output if you want).

**Comment by ellisonbg** [comment]
This is really difficult to handle in pure CSS based table styling. The problem is that we have no idea what types of tables a user will open. We have to pick defaults that look decent for any possible table. It is just as likely a user will have:

* Many columns or few
* Columns with narrow content or wide

If we increase the max width or remove it all together, a single wide content *cell* can make a table completely unreadable. I am willing to make the default wider, but not much...

What we really need is a more advanced JS-based table widget that allow column widths to be adjusted. We are working on that type of thing, but it is beyond the scope of pure HTML/CSS tables.

**Comment by ellisonbg** [comment]
Let's try increasing `max-width` to 150px.

**Comment by jorisvandenbossche** [comment]
The problem with making the default a bit larger, is that this is completely hard coded in jupyter (this is correct?), and there is no way for a user to *see* his/her data when truncated. This is a serious usability issue IMO. 
You really very quickly hit this limit (the example dataframe you show in the original PR has even a truncated column name (https://github.com/jupyter/jupyterlab/pull/910#issue-177955882), and not seeing your column name is not really handy).

Question (css noob here): can we override this width from pandas? By adding some `<style>` to our tables we output?

cc @TomAugspurger

**Comment by TomAugspurger** [comment]
IIRC by default we include 'dataframe' in the class tag for `DataFrame._repr_html_`. We should be able to override it. Im building the latest jupyterlab now and will test that out.

**Comment by TomAugspurger** [comment]
![screen shot 2016-10-06 at 4 28 20 pm](https://cloud.githubusercontent.com/assets/1312546/19171367/f2b0dd24-8be1-11e6-8a78-f6db568fa9b6.png)

Caveat: I'm also a CSS noob. I'm using DataFrame.style there to set the max-width for ease of testing, but we would include that in the default `_repr_html_` (limiting it to just the `.dataframe` CSS class).

That said, I kind of like the truncated version :) Maybe a bit too narrow, but I've thought pandas' current one is too wide.

> What we really need is a more advanced JS-based table widget that allow column widths to be adjusted. We are working on that type of thing, but it is beyond the scope of pure HTML/CSS tables.

👍Let us know if there's anything that can be adjusted on the pandas side to help with that.

**Comment by jorisvandenbossche** [comment]
> That said, I kind of like the truncated version :) Maybe a bit too narrow, but I've thought pandas' current one is too wide.

I agree that our current one is probably too wide, but the current default of 50 chars corresponds roughly to 300px, and then only 100 or 150 px is really a big difference. 
If even a plain normal datetime index with up to seconds just fits in 150px (it needs 140 in my test), then IMO 150px is still on the narrow side (but certainly an improvement over 100px!).

Besides, I think it is important that this is configurable for the case you are dealing with a dataframe with longer cells (eg street names will often not fit in 150px), but it seems we can probably fix this on the pandas side.

**Comment by dhirschfeld** [comment]
I was going to suggest that the width of a timestamp `01-Jan-2017 00:00` might be a good default but pandas' printing every timestamp at nanosecond resolution would still result in truncation :|

Is there some way a user can override this setting? That should be sufficient.

**Comment by dhirschfeld** [comment]
> What we really need is a more advanced JS-based table widget that allow column widths to be adjusted. We are working on that type of thing, but it is beyond the scope of pure HTML/CSS tables.

**Comment by gnestor** [comment]
I'm seeing that the text value of the `td` DOM node is actually truncated :

![image](https://cloud.githubusercontent.com/assets/512354/19207408/83759570-8ca5-11e6-9f35-32cb1fec92fd.png)

Which suggests that the issue is not a CSS one but a pandas (or somewhere between pandas and CSS). Fortunately, it's a pandas issue:

![image](https://cloud.githubusercontent.com/assets/512354/19207472/26afa2da-8ca6-11e6-91a2-9515912f18bf.png)

So for future reference, just set a higher 'max_colwidth' if you see cell content truncated in the table using `pandas.set_option('max_colwidth', WIDTH_GREATER_THAN_50)`.

**Comment by jorisvandenbossche** [comment]
@gnestor I am not sure how you get this result, but the `max-width: 100px` is for some reason crossed out. When I tried this with the latest jupyterlab release, that was not the case. 
So my point that I tried to make is that the way of configuring with pandas that you show above does actually *no longer* work. As everything gets truncated at 100px, no matter what option you set in pandas for `'max_colwidth'`. See eg the picture @TomAugspurger posted above (https://github.com/jupyter/jupyterlab/issues/961#issuecomment-252095223), where it is truncated at much shorter text as in your example.

**Comment by gnestor** [comment]
@jorisvandenbossche I tested this is classic notebook. I recently updated the notebook's table styles to match those of jupyterlab, so they should be equivalent. Unfortunately, I'm having issues installing the current version of jupyterlab locally so I won't able to test this in jupyterlab until that's resolved.

**Comment by gnestor** [comment]
@jorisvandenbossche Ok, my jupyterlab install is working again and I see the `max-width: 100px` rule on `.jp-RenderedHTMLCommon td`. My opinion is that being able to see the contents of your data outweighs the aesthetics of greatly varying column widths, but it seems like the consensus is to leave the max-width or slightly increase it.

**Comment by dhirschfeld** [comment]
ping!
![image](https://cloud.githubusercontent.com/assets/881019/20505038/4bb2d688-b096-11e6-84ef-b3d3b95a1ea8.png)
Having to put the above cell in every notebook is far from ideal, but better than having unreadable tables which kind-of defeats the whole purpose of a notebook IMHO cf. before/after below:

![image](https://cloud.githubusercontent.com/assets/881019/20505121/ab43b306-b096-11e6-8823-7b1667268025.png) ![image](https://cloud.githubusercontent.com/assets/881019/20505140/c435537e-b096-11e6-8fe3-82a82b082dbf.png)
