### ISSUE TITLE
Property inspector is using a lot of white space

### ISSUE THREAD

**Issue by asteppke** [jupyterlab/jupyterlab#9610]
In the current 3.0 release the property inspector icon moved to the right hand side and is creating a lot of unused screen space. The column is not removable or minimizes for smaller browser window widths. 

As far as I can see this change tripped other people as well (https://github.com/jupyterlab/jupyterlab/issues/8038) and I am looking for a configuration option or other possibilities to revert this and free the area of unused space:

![image](https://user-images.githubusercontent.com/5851636/104453364-9784ea80-55a4-11eb-976d-6486fc95eb73.png)

**Comment by jtpio** [comment]
Thanks @asteppke for the feedback.

It's possible to move the property inspector to the left side, with `Right Click > Switch Sidebar Side`:

![property-inspector-side](https://user-images.githubusercontent.com/591645/104467313-788f5400-55b6-11eb-9ced-b53431a29ab6.gif)


Normally this should be persisted in the settings and be applied on subsequent restarts.

**Comment by jasongrout** [comment]
Closed as answered. Thanks Jeremy!

**Comment by jasongrout** [comment]
You can also change it in the Advanced Settings > Sidebar.

**Comment by jtpio** [comment]
Linking to the changelog entry for reference: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html?#property-inspector-moved-to-right-sidebar

**Comment by asteppke** [comment]
Great, thanks a lot for the swift reply and that this is easily configurable. Really enjoying the 3.0 experience!
