### ISSUE TITLE
Create notebook from (public ) URL

### ISSUE THREAD

**Issue by ptitzler** [jupyterlab/jupyterlab#9615]
### Problem

As a user, I commonly explore notebooks that are stored in a public location, for example on GitHub or S3. Currently there does not appear to be an (obvious) way to create a notebook in JupyterLab from an external source without "downloading" it first to the local machine.

Example:
A user would like to try the JupyterLab debugger example notebook, which is located here: https://github.com/jupyterlab/debugger/blob/master/examples/index.ipynb
To use the notebook, the user currently either has to clone the entire Git repository (using the git extension or outside of JupyterLab), or download the notebook source to the local machine (e.g. using a web browser).

### Proposed Solution

General workflow:
 - User provides a URL as an input (e.g. `https://raw.githubusercontent.com/jupyterlab/debugger/master/examples/index.ipynb`)
 - An attempt is made to retrieve the URL using an HTTP GET request.
 - If the request succeeded, a new notebook is created using the content of the downloaded file.

Potential integration points:
- Extend the "File" > "New Notebook" dialog to accept an optional text input. 
- Create new "File" > "New Notebook from URL" command

**Comment by jasongrout** [comment]
For a GitHub-specific solution, you can look at https://github.com/jupyterlab/jupyterlab-github - it adds a new filebrowser and works with notebooks directly from GitHub.

Having a more general "Download and open this notebook" would be nice. I suppose it would be created in whatever the current filebrowser directory is.

**Comment by krassowski** [comment]
And there is also: https://github.com/IBM/jupyterlab-s3-browser for S3

**Comment by ptitzler** [comment]
> And there is also: https://github.com/IBM/jupyterlab-s3-browser for S3

I did test drive that extension a while ago for a different project. It's designed to provide access to protected S3 resources, which makes perfect sense. However, it's unfortunately not addressing the public resource scenario, where there's no need for an S3 client to access the files. (I'm not saying that the extension should!)

**Comment by jtpio** [comment]
Maybe it's possible to do it client-side by fetching the content with the browser `fetch`, and upload via the contents manager from `@jupyterlab/services`. With the current directory being tracked by the file browser.

Linking to https://github.com/jupyterlab/jupyterlab/issues/10570 which expresses a similar idea.
