### ISSUE TITLE
More flexible cell/results presentation

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#962]
To generate tidy reports, sometimes we want to keep only cells/outputs. It's appealing to have feature support of the following.
1. being able to delete a cell but keep it's results
2. being able to keep a cell but delete it's results
3. being able to collapse a cell but display it's results
4. being able to display a cell but collapse it's results

**Comment by jasongrout** [comment]
See #713 for discussion around (3) and (4)

**Comment by jasongrout** [comment]
> being able to delete a cell but keep it's results

@dclong - Can you explain some usecases for deleting a cell, but keeping the result? Part of the goal for the notebook is to encourage reproducible computation, and deleting a cell and only showing the results seems at odds with that.

**Comment by jasongrout** [comment]
> being able to keep a cell but delete it's results

We already have this in the "Clear cell output(s)" command.

**Comment by dclong** [comment]
@jasongrout,
Sorry that I don't have a usecase for deleting a cell but keeping the results if feature 3 is implemented. I just list some of my thoughts which can make JupyterLab more friendly for making reports.
