### ISSUE TITLE
TAB complete not working... again

### ISSUE THREAD

**Issue by forestille-deg-uendelig** [jupyterlab/jupyterlab#9620]
Hello Jupyterlab!

For whatever reason, I am not able to use the Intellisense and Autocomplete functions in my Jupyter Lab. I am running Jupyter Lab 3.0.1, Python 3.9.1, and Conda 4.9.1 (if that matters). I tried to put "%config IPCompleter.greedy=True" on the first line of my notebook, but am still not able to list all methods and/or attributes by pressing TAB after a period. Example:

import plotly as pl
pl.

If it matters, I ran Jupyter Lab from a conda venv in which Jupyter and all my libraries for this project are installed. I am also not able to see any keyboard shortcuts. Thank you in advance for the help you are able to provide.

R/S
FDU

- Operating System and version: Fedora 33 (Workstation Edition)
- Browser and version: Chrome 87.0.4280.88
- JupyterLab version: Jupyter Lab 3.0.1

sys.version:
	3.9.1 (default, Dec 11 2020, 14:32:07) 
	[GCC 7.3.0]

platform.platform():
	Linux-5.9.16-200.fc33.x86_64-x86_64-with-glibc2.32

pip list:
	Package                       Version
	----------------------------- -------------------
	anyio                         2.0.2
	argon2-cffi                   20.1.0
	async-generator               1.10
	attrs                         20.3.0
	Babel                         2.9.0
	backcall                      0.2.0
	backports.functools-lru-cache 1.6.1
	beautifulsoup4                4.9.3
	billiard                      3.6.3.0
	bleach                        3.2.1
	brotlipy                      0.7.0
	bs4                           0.0.1
	certifi                       2020.12.5
	cffi                          1.14.4
	chardet                       4.0.0
	coala-utils                   0.5.1
	cryptography                  3.3.1
	cycler                        0.10.0
	decorator                     4.4.2
	defusedxml                    0.6.0
	entrypoints                   0.3
	idna                          2.10
	importlib-metadata            3.3.0
	ipykernel                     5.4.2
	ipython                       7.19.0
	ipython-genutils              0.2.0
	ipywidgets                    7.6.2
	jedi                          0.18.0
	Jinja2                        2.11.2
	json5                         0.9.5
	jsonschema                    3.2.0
	jupyter                       1.0.0
	jupyter-client                6.1.7
	jupyter-console               6.2.0
	jupyter-core                  4.7.0
	jupyter-server                1.1.4
	jupyterlab                    3.0.1
	jupyterlab-pygments           0.1.2
	jupyterlab-server             2.0.0
	jupyterlab-widgets            1.0.0
	kiwisolver                    1.3.1
	lab                           6.2
	lxml                          4.6.2
	MarkupSafe                    1.1.1
	matplotlib                    3.3.3
	mistune                       0.8.4
	nbclassic                     0.2.5
	nbclient                      0.5.1
	nbconvert                     6.0.7
	nbformat                      5.0.8
	nest-asyncio                  1.4.3
	notebook                      6.1.6
	numpy                         1.19.5
	oauthlib                      3.1.0
	packaging                     20.8
	pandas                        1.2.0
	pandocfilters                 1.4.3
	parso                         0.8.1
	pexpect                       4.8.0
	pickleshare                   0.7.5
	Pillow                        8.1.0
	pip                           20.3.3
	plotly                        4.14.1
	prometheus-client             0.9.0
	prompt-toolkit                3.0.9
	ptyprocess                    0.7.0
	pycparser                     2.20
	Pygments                      2.7.3
	pyOpenSSL                     20.0.1
	pyparsing                     2.4.7
	pyrsistent                    0.17.3
	PySocks                       1.7.1
	python-dateutil               2.8.1
	pytz                          2020.5
	pyzmq                         20.0.0
	qtconsole                     5.0.1
	QtPy                          1.9.0
	requests                      2.25.1
	requests-oauthlib             1.3.0
	retrying                      1.3.3
	Send2Trash                    1.5.0
	setuptools                    51.0.0.post20201207
	simplejson                    3.17.2
	six                           1.15.0
	sniffio                       1.2.0
	soupsieve                     2.1
	terminado                     0.9.2
	testpath                      0.4.4
	tornado                       6.1
	traitlets                     5.0.5
	tweepy                        3.10.0
	twitterscraper                1.6.1
	txt2tags                      3.7
	urllib3                       1.26.2
	viola                         0.3.8
	wcwidth                       0.2.5
	webencodings                  0.5.1
	wheel                         0.36.2
	widgetsnbextension            3.5.1
	zipp                          3.4.0

conda list:
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                        main  
	anyio                     2.0.2            py39hf3d152e_3    conda-forge
	argon2-cffi               20.1.0           py39hbd71b63_2    conda-forge
	async_generator           1.10                       py_0    conda-forge
	attrs                     20.3.0             pyhd3deb0d_0    conda-forge
	babel                     2.9.0              pyhd3deb0d_0    conda-forge
	backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
	backports                 1.0                        py_2    conda-forge
	backports.functools_lru_cache 1.6.1                      py_0    conda-forge
	beautifulsoup4            4.9.3              pyhb0f4dca_0  
	billiard                  3.6.3.0                  pypi_0    pypi
	blas                      1.0                    openblas  
	bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
	brotlipy                  0.7.0           py39h38d8fee_1001    conda-forge
	bs4                       0.0.1                    pypi_0    pypi
	ca-certificates           2020.12.8            h06a4308_0  
	certifi                   2020.12.5        py39h06a4308_0  
	cffi                      1.14.4           py39h261ae71_0  
	chardet                   4.0.0            py39hf3d152e_0    conda-forge
	coala-utils               0.5.1                    pypi_0    pypi
	cryptography              3.3.1            py39h3c74f83_0  
	cycler                    0.10.0                   pypi_0    pypi
	decorator                 4.4.2                      py_0    conda-forge
	defusedxml                0.6.0                      py_0    conda-forge
	entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
	idna                      2.10               pyh9f0ad1d_0    conda-forge
	importlib-metadata        3.3.0            py39hf3d152e_2    conda-forge
	importlib_metadata        3.3.0                hd8ed1ab_2    conda-forge
	ipykernel                 5.4.2            py39hef51801_0    conda-forge
	ipython                   7.19.0           py39hef51801_0    conda-forge
	ipython-genutils          0.2.0                    pypi_0    pypi
	ipython_genutils          0.2.0                      py_1    conda-forge
	ipywidgets                7.6.2                    pypi_0    pypi
	jedi                      0.18.0           py39hf3d152e_1    conda-forge
	jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
	json5                     0.9.5              pyh9f0ad1d_0    conda-forge
	jsonschema                3.2.0                      py_2    conda-forge
	jupyter                   1.0.0                    pypi_0    pypi
	jupyter-console           6.2.0                    pypi_0    pypi
	jupyter_client            6.1.7                      py_0    conda-forge
	jupyter_core              4.7.0            py39hf3d152e_0    conda-forge
	jupyter_server            1.1.4            py39hf3d152e_0    conda-forge
	jupyterlab                3.0.1              pyhd8ed1ab_0    conda-forge
	jupyterlab-widgets        1.0.0                    pypi_0    pypi
	jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
	jupyterlab_server         2.0.0              pyhd8ed1ab_0    conda-forge
	kiwisolver                1.3.1                    pypi_0    pypi
	lab                       6.2                      pypi_0    pypi
	ld_impl_linux-64          2.33.1               h53a641e_7  
	libedit                   3.1.20191231         h14c3975_1  
	libffi                    3.3                  he6710b0_2  
	libgcc-ng                 9.1.0                hdf63c60_0  
	libgfortran-ng            7.3.0                hdf63c60_0  
	libopenblas               0.3.10               h5a2b251_0  
	libsodium                 1.0.18               h36c2ea0_1    conda-forge
	libstdcxx-ng              9.1.0                hdf63c60_0  
	lxml                      4.6.2                    pypi_0    pypi
	markupsafe                1.1.1            py39h38d8fee_2    conda-forge
	matplotlib                3.3.3                    pypi_0    pypi
	mistune                   0.8.4           py39hbd71b63_1002    conda-forge
	nbclassic                 0.2.5              pyhd8ed1ab_0    conda-forge
	nbclient                  0.5.1                      py_0    conda-forge
	nbconvert                 6.0.7            py39hf3d152e_3    conda-forge
	nbformat                  5.0.8                      py_0    conda-forge
	ncurses                   6.2                  he6710b0_1  
	nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
	notebook                  6.1.6            py39hf3d152e_0    conda-forge
	numpy                     1.19.5                   pypi_0    pypi
	numpy-base                1.19.2           py39h0f7b65f_0  
	oauthlib                  3.1.0                    pypi_0    pypi
	openssl                   1.1.1i               h27cfd23_0  
	packaging                 20.8               pyhd3deb0d_0    conda-forge
	pandas                    1.2.0            py39ha9443f7_0  
	pandoc                    2.11.3.2             h7f98852_0    conda-forge
	pandocfilters             1.4.3                    pypi_0    pypi
	parso                     0.8.1              pyhd8ed1ab_0    conda-forge
	pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
	pickleshare               0.7.5                   py_1003    conda-forge
	pillow                    8.1.0                    pypi_0    pypi
	pip                       20.3.3           py39h06a4308_0  
	plotly                    4.14.1             pyhd3eb1b0_0  
	prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
	prompt-toolkit            3.0.9              pyha770c72_0    conda-forge
	ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
	pycparser                 2.20               pyh9f0ad1d_2    conda-forge
	pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
	pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
	pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
	pyrsistent                0.17.3           py39hbd71b63_1    conda-forge
	pysocks                   1.7.1            py39h079e4ff_2    conda-forge
	python                    3.9.1                hdb3f193_2  
	python-dateutil           2.8.1                      py_0    conda-forge
	python_abi                3.9                      1_cp39    conda-forge
	pytz                      2020.5             pyhd8ed1ab_0    conda-forge
	pyzmq                     20.0.0                   pypi_0    pypi
	qtconsole                 5.0.1                    pypi_0    pypi
	qtpy                      1.9.0                    pypi_0    pypi
	readline                  8.0                  h7b6447c_0  
	requests                  2.25.1             pyhd3deb0d_0    conda-forge
	requests-oauthlib         1.3.0                    pypi_0    pypi
	retrying                  1.3.3                      py_2  
	send2trash                1.5.0                      py_0    conda-forge
	setuptools                51.0.0           py39h06a4308_2  
	simplejson                3.17.2                   pypi_0    pypi
	six                       1.15.0           py39h06a4308_0  
	sniffio                   1.2.0            py39hf3d152e_0    conda-forge
	soupsieve                 2.1                pyhd3eb1b0_0  
	sqlite                    3.33.0               h62c20be_0  
	terminado                 0.9.2            py39hf3d152e_0    conda-forge
	testpath                  0.4.4                      py_0    conda-forge
	tk                        8.6.10               hbc83047_0  
	tornado                   6.1              py39hbd71b63_0    conda-forge
	traitlets                 5.0.5                      py_0    conda-forge
	tweepy                    3.10.0                   pypi_0    pypi
	twitterscraper            1.6.1                    pypi_0    pypi
	txt2tags                  3.7                      pypi_0    pypi
	tzdata                    2020d                h14c3975_0  
	urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
	viola                     0.3.8                    pypi_0    pypi
	wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
	webencodings              0.5.1                    pypi_0    pypi
	wheel                     0.36.2             pyhd3eb1b0_0  
	widgetsnbextension        3.5.1                    pypi_0    pypi
	xz                        5.2.5                h7b6447c_0  
	zeromq                    4.3.3                h58526e2_3    conda-forge
	zipp                      3.4.0                      py_0    conda-forge
	zlib                      1.2.11               h7b6447c_3

conda env:
	channels:
	  - conda-forge
	  - defaults
	dependencies:
	  - _libgcc_mutex=0.1=main
	  - anyio=2.0.2=py39hf3d152e_3
	  - argon2-cffi=20.1.0=py39hbd71b63_2
	  - async_generator=1.10=py_0
	  - attrs=20.3.0=pyhd3deb0d_0
	  - babel=2.9.0=pyhd3deb0d_0
	  - backcall=0.2.0=pyh9f0ad1d_0
	  - backports=1.0=py_2
	  - backports.functools_lru_cache=1.6.1=py_0
	  - beautifulsoup4=4.9.3=pyhb0f4dca_0
	  - blas=1.0=openblas
	  - bleach=3.2.1=pyh9f0ad1d_0
	  - brotlipy=0.7.0=py39h38d8fee_1001
	  - ca-certificates=2020.12.8=h06a4308_0
	  - certifi=2020.12.5=py39h06a4308_0
	  - cffi=1.14.4=py39h261ae71_0
	  - chardet=4.0.0=py39hf3d152e_0
	  - cryptography=3.3.1=py39h3c74f83_0
	  - decorator=4.4.2=py_0
	  - defusedxml=0.6.0=py_0
	  - entrypoints=0.3=pyhd8ed1ab_1003
	  - idna=2.10=pyh9f0ad1d_0
	  - importlib-metadata=3.3.0=py39hf3d152e_2
	  - importlib_metadata=3.3.0=hd8ed1ab_2
	  - ipykernel=5.4.2=py39hef51801_0
	  - ipython=7.19.0=py39hef51801_0
	  - ipython_genutils=0.2.0=py_1
	  - jedi=0.18.0=py39hf3d152e_1
	  - jinja2=2.11.2=pyh9f0ad1d_0
	  - json5=0.9.5=pyh9f0ad1d_0
	  - jsonschema=3.2.0=py_2
	  - jupyter_client=6.1.7=py_0
	  - jupyter_core=4.7.0=py39hf3d152e_0
	  - jupyter_server=1.1.4=py39hf3d152e_0
	  - jupyterlab=3.0.1=pyhd8ed1ab_0
	  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
	  - jupyterlab_server=2.0.0=pyhd8ed1ab_0
	  - ld_impl_linux-64=2.33.1=h53a641e_7
	  - libedit=3.1.20191231=h14c3975_1
	  - libffi=3.3=he6710b0_2
	  - libgcc-ng=9.1.0=hdf63c60_0
	  - libgfortran-ng=7.3.0=hdf63c60_0
	  - libopenblas=0.3.10=h5a2b251_0
	  - libsodium=1.0.18=h36c2ea0_1
	  - libstdcxx-ng=9.1.0=hdf63c60_0
	  - markupsafe=1.1.1=py39h38d8fee_2
	  - mistune=0.8.4=py39hbd71b63_1002
	  - nbclassic=0.2.5=pyhd8ed1ab_0
	  - nbclient=0.5.1=py_0
	  - nbconvert=6.0.7=py39hf3d152e_3
	  - nbformat=5.0.8=py_0
	  - ncurses=6.2=he6710b0_1
	  - nest-asyncio=1.4.3=pyhd8ed1ab_0
	  - notebook=6.1.6=py39hf3d152e_0
	  - numpy-base=1.19.2=py39h0f7b65f_0
	  - openssl=1.1.1i=h27cfd23_0
	  - packaging=20.8=pyhd3deb0d_0
	  - pandas=1.2.0=py39ha9443f7_0
	  - pandoc=2.11.3.2=h7f98852_0
	  - parso=0.8.1=pyhd8ed1ab_0
	  - pexpect=4.8.0=pyh9f0ad1d_2
	  - pickleshare=0.7.5=py_1003
	  - pip=20.3.3=py39h06a4308_0
	  - plotly=4.14.1=pyhd3eb1b0_0
	  - prometheus_client=0.9.0=pyhd3deb0d_0
	  - prompt-toolkit=3.0.9=pyha770c72_0
	  - ptyprocess=0.7.0=pyhd3deb0d_0
	  - pycparser=2.20=pyh9f0ad1d_2
	  - pygments=2.7.3=pyhd8ed1ab_0
	  - pyopenssl=20.0.1=pyhd8ed1ab_0
	  - pyparsing=2.4.7=pyh9f0ad1d_0
	  - pyrsistent=0.17.3=py39hbd71b63_1
	  - pysocks=1.7.1=py39h079e4ff_2
	  - python=3.9.1=hdb3f193_2
	  - python-dateutil=2.8.1=py_0
	  - python_abi=3.9=1_cp39
	  - pytz=2020.5=pyhd8ed1ab_0
	  - readline=8.0=h7b6447c_0
	  - requests=2.25.1=pyhd3deb0d_0
	  - retrying=1.3.3=py_2
	  - send2trash=1.5.0=py_0
	  - setuptools=51.0.0=py39h06a4308_2
	  - six=1.15.0=py39h06a4308_0
	  - sniffio=1.2.0=py39hf3d152e_0
	  - soupsieve=2.1=pyhd3eb1b0_0
	  - sqlite=3.33.0=h62c20be_0
	  - terminado=0.9.2=py39hf3d152e_0
	  - testpath=0.4.4=py_0
	  - tk=8.6.10=hbc83047_0
	  - tornado=6.1=py39hbd71b63_0
	  - traitlets=5.0.5=py_0
	  - tzdata=2020d=h14c3975_0
	  - urllib3=1.26.2=pyhd8ed1ab_0
	  - wcwidth=0.2.5=pyh9f0ad1d_2
	  - wheel=0.36.2=pyhd3eb1b0_0
	  - xz=5.2.5=h7b6447c_0
	  - zeromq=4.3.3=h58526e2_3
	  - zipp=3.4.0=py_0
	  - zlib=1.2.11=h7b6447c_3
- pip:
	    - billiard==3.6.3.0
	    - bs4==0.0.1
	    - coala-utils==0.5.1
	    - cycler==0.10.0
	    - ipython-genutils==0.2.0
	    - ipywidgets==7.6.2
	    - jupyter==1.0.0
	    - jupyter-console==6.2.0
	    - jupyterlab-widgets==1.0.0
	    - kiwisolver==1.3.1
	    - lab==6.2
	    - lxml==4.6.2
	    - matplotlib==3.3.3
	    - numpy==1.19.5
	    - oauthlib==3.1.0
	    - pandocfilters==1.4.3
	    - pillow==8.1.0
	    - pyzmq==20.0.0
	    - qtconsole==5.0.1
	    - qtpy==1.9.0
	    - requests-oauthlib==1.3.0
	    - simplejson==3.17.2
	    - tweepy==3.10.0
	    - twitterscraper==1.6.1
	    - txt2tags==3.7
	    - viola==0.3.8
	    - webencodings==0.5.1
	    - widgetsnbextension==3.5.1

Ignored setting registry preload errors. Array(1)0: {dataPath: "", keyword: "timeout", message: "Transforming @jupyterlab/shortcuts-extension:shortcuts timed out.", schemaPath: ""}length: 1__proto__: Array(0)
(anonymous) @ jlab_core.3099b1be2bd042406f2c.js:2
jlab_core.3099b1be2bd042406f2c.js:2 Ignored setting registry preload errors. Array(1)0: {dataPath: "", keyword: "timeout", message: "Transforming @jupyterlab/docmanager-extension:plugin timed out.", schemaPath: ""}length: 1__proto__: Array(0)
(anonymous) @ jlab_core.3099b1be2bd042406f2c.js:2

**Comment by forestille-deg-uendelig** [comment]
I just tried:
conda install jedi====0.17.2

stopped my Jupyter Lab, re-opened Jupyter Lab, still not able to use intellisense and/or autocomplete.

**Comment by forestille-deg-uendelig** [comment]
Fix:

pip uninstall parso
pip uninstall jedi
pip install parso
pip install jedi

required versions:
ipython             7.19.0
jedi                  0.18.0
parso               0.8.1

**Comment by forestille-deg-uendelig** [comment]
aaaaand it isn't working again. I have tried Jedi==0.17.2 as recommended, and it doesn't work.

**Comment by forestille-deg-uendelig** [comment]
aaaaand it isn't working again. I have tried Jedi==0.17.2 as recommended, and it doesn't work.

**Comment by forestille-deg-uendelig** [comment]
I'm obviously new to all this...^. Will someone please graciously guide me and tell me why nobody has responded to my request? I am trying to learn...

**Comment by tcapelle** [comment]
```
%config Completer.use_jedi = False
```
try this

**Comment by forestille-deg-uendelig** [comment]
It works!!! Thank you so much @tcapelle.
