### ISSUE TITLE
Disabling line wrapping in text editor seems broken

### ISSUE THREAD

**Issue by tomdries** [jupyterlab/jupyterlab#9623]
## Description

My goal was to turn off line wrapping in the text editor: 

![linebreaks](https://user-images.githubusercontent.com/22589103/104714201-36d0eb80-5725-11eb-94ba-47d8e4f31e5f.png)

To do so, I added the following to my user preferences, as suggested [here](https://github.com/jupyterlab/jupyterlab/pull/4936) by @AlbertHilb: 

`{
    "editorConfig": {
        "lineWrap": "off"
    }
}`

However, the lines still break. Is this a bug, or have I misunderstood the lineWrap option? If the latter is the case, is there an option to turn off line wrapping for the text editor? I like to keep most of my function definitions separate from my jupyter code, and the option to have it open in a split window is great for this workflow. However, I find that the line wrapping make function definitions look messy and confusing.
## Reproduce

1. Go to 'settings -> Advanced Settings Editor'
2. Add `{
    "editorConfig": {
        "lineWrap": "off"
    }
}` to User Preferences
3. Notice that lines still break in the text editor when decreasing window size 

## Expected behavior
I expect that the lines do not break, in other words flow beyond the border of the window (in the background). Similar to the screenshot example in the code cell at the bottom of the jupyter file. 

## Context

- Operating System and version: Windows Version 10.0.19041 Build 19041

- Browser and version: Firefox 84.0.2 (64-bit)
- JupyterLab version: Version 2.2.9 (problem persists in 3.0.5)

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	C:\Users\Tom\venvs\general\Scripts
	C:\Windows\system32
	C:\Windows
	C:\Windows\System32\Wbem
	C:\Windows\System32\WindowsPowerShell\v1.0\
	C:\Windows\System32\OpenSSH\
	C:\Program Files\Git\cmd
	C:\Program Files\MATLAB\R2020b\bin
	C:\Program Files\nodejs\
	C:\Users\Tom\AppData\Local\Programs\Python\Python38\Scripts\
	C:\Users\Tom\AppData\Local\Programs\Python\Python38\
	C:\Users\Tom\AppData\Local\Microsoft\WindowsApps
	C:\Users\Tom\AppData\Local\Programs\Microsoft VS Code\bin
	C:\Users\Tom\AppData\Roaming\npm

sys.path:
	C:\Users\Tom\venvs\general\Scripts\jupyter-troubleshoot.EXE
	C:\Users\Tom\AppData\Local\Programs\Python\Python38\python38.zip
	C:\Users\Tom\AppData\Local\Programs\Python\Python38\DLLs
	C:\Users\Tom\AppData\Local\Programs\Python\Python38\lib
	C:\Users\Tom\AppData\Local\Programs\Python\Python38
	c:\users\tom\venvs\general
	c:\users\tom\venvs\general\lib\site-packages
	c:\users\tom\venvs\general\lib\site-packages\win32
	c:\users\tom\venvs\general\lib\site-packages\win32\lib
	c:\users\tom\venvs\general\lib\site-packages\Pythonwin

sys.executable:
	c:\users\tom\venvs\general\scripts\python.exe

sys.version:
	3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]

platform.platform():
	Windows-10-10.0.19041-SP0

where jupyter:
	C:\Users\Tom\venvs\general\Scripts\jupyter.exe

pip list:
	Package                           Version

	--------------------------------- -----------

	argon2-cffi                       20.1.0

	astroid                           2.4.2

	async-generator                   1.10

	attrs                             20.2.0

	autopep8                          1.5.4

	backcall                          0.2.0

	beautifulsoup4                    4.9.3

	bleach                            3.2.1

	certifi                           2020.6.20

	cffi                              1.14.3

	chardet                           3.0.4

	click                             7.1.2

	click-plugins                     1.1.1

	cligj                             0.5.0

	colorama                          0.4.3

	cycler                            0.10.0

	decorator                         4.4.2

	defusedxml                        0.6.0

	docopt                            0.6.2

	entrypoints                       0.3

	et-xmlfile                        1.0.1

	Fiona                             1.8.17

	GDAL                              3.1.3

	geographiclib                     1.50

	geopandas                         0.8.1

	geopy                             2.0.0

	idna                              2.10

	ipykernel                         5.3.4

	ipython                           7.18.1

	ipython-genutils                  0.2.0

	ipywidgets                        7.5.1

	isort                             5.6.0

	jdcal                             1.4.1

	jedi                              0.17.2

	Jinja2                            2.11.2

	joblib                            0.17.0

	Js2Py                             0.70

	json5                             0.9.5

	jsonschema                        3.2.0

	jupyter                           1.0.0

	jupyter-client                    6.1.7

	jupyter-console                   6.2.0

	jupyter-contrib-core              0.3.3

	jupyter-contrib-nbextensions      0.5.1

	jupyter-core                      4.6.3

	jupyter-highlight-selected-word   0.2.0

	jupyter-latex-envs                1.4.6

	jupyter-nbextensions-configurator 0.4.1

	jupyterlab                        2.2.9

	jupyterlab-pygments               0.1.2

	jupyterlab-server                 1.2.0

	kiwisolver                        1.2.0

	lazy-object-proxy                 1.4.3

	lxml                              4.6.2

	MarkupSafe                        1.1.1

	matplotlib                        3.3.2

	mccabe                            0.6.1

	mistune                           0.8.4

	munch                             2.5.0

	nbclient                          0.5.0

	nbconvert                         6.0.6

	nbformat                          5.0.7

	nest-asyncio                      1.4.1

	nodejs                            0.1.1

	notebook                          6.1.4

	numpy                             1.19.2

	openpyxl                          3.0.5

	optional-django                   0.1.0

	packaging                         20.4

	pandas                            1.1.2

	pandas-read-xml                   0.0.8

	pandocfilters                     1.4.2

	parso                             0.7.1

	pickleshare                       0.7.5

	Pillow                            7.2.0

	pip                               20.3.3

	pipwin                            0.5.0

	prometheus-client                 0.8.0

	prompt-toolkit                    3.0.7

	pyarrow                           0.17.1

	pycodestyle                       2.6.0

	pycparser                         2.20

	Pygments                          2.7.1

	pyjsparser                        2.7.1

	pylint                            2.6.0

	pyparsing                         2.4.7

	PyPrind                           2.11.2

	pyproj                            2.6.1.post1

	pyrsistent                        0.17.3

	pySmartDL                         1.3.4

	python-dateutil                   2.8.1

	pytz                              2020.1

	pywin32                           228

	pywinpty                          0.5.7

	PyYAML                            5.3.1

	pyzmq                             19.0.2

	qtconsole                         4.7.7

	QtPy                              1.9.0

	requests                          2.24.0

	rijksdriehoek                     0.0.1

	Rtree                             0.9.4

	scikit-learn                      0.23.2

	scipy                             1.5.2

	seaborn                           0.11.0

	Send2Trash                        1.5.0

	setuptools                        49.2.1

	Shapely                           1.7.1

	six                               1.15.0

	sklearn                           0.0

	soupsieve                         2.0.1

	terminado                         0.9.1

	testpath                          0.4.4

	threadpoolctl                     2.1.0

	toml                              0.10.1

	tornado                           6.0.4

	traitlets                         5.0.4

	tzlocal                           2.1

	urllib3                           1.25.10

	utm                               0.7.0

	wcwidth                           0.2.5

	webencodings                      0.5.1

	widgetsnbextension                3.5.1

	wrapt                             1.12.1

	xlrd                              1.2.0

	xmltodict                         0.12.0

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
FYI, you can temporarily change the line wrapping of the text editor by the View menu > Wrap Words. I don't believe that preference is saved, though, and is a per-editor thing rather than a default for all editors.

**Comment by jasongrout** [comment]
I'm having the same issue you are having: setting that option in advanced settings does not seem to have any effect on word wrapping in existing or new editor windows.

**Comment by b-trav** [comment]
As pointed out by @tomdries, word wrapping is not working for me in a markdown file in the text editor, but it is working within a markdown file in a notebook.
I am running Jupyter 3.0.14 in Chrome on a Ubuntu 18.04 machine
![image](https://user-images.githubusercontent.com/16848340/120606459-c8958700-c481-11eb-812b-79aa9df67bb7.png)

**Comment by HerculesJack** [comment]
Same issue for jupyterlab 3.0.16, Firefox 90.0.2 and MacOS 11.3.1.

**Comment by Mithil467** [comment]
I tested a few things and I think this issue can be further generalized to User preferences for the Text Editor section not being considered. I would like to try and fix this issue.

**Comment by fcollonval** [comment]
Hey @Mithil467 as you mentioned on Gitter, I confirm that the text editor settings are not taking into account :confused: 

To give you some pointers:
- The settings are defined and handle in the `fileeditor-extension`
  - They are set to a global variable with `Commands.updateSettings` at https://github.com/jupyterlab/jupyterlab/blob/bac24a158a6ba887996edac12796da9c2009c0f9/packages/fileeditor-extension/src/commands.ts#L175
  - The settings should then be applied to all opened editors with `Commands.updateTracker` at https://github.com/jupyterlab/jupyterlab/blob/bac24a158a6ba887996edac12796da9c2009c0f9/packages/fileeditor-extension/src/commands.ts#L191
  
So I would suggest looking into those functions to see if the settings are passed as expected.

**Comment by fcollonval** [comment]
This is fixed by #10868
