### ISSUE TITLE
User Preferences Not Working

### ISSUE THREAD

**Issue by unkn0wn-dev** [jupyterlab/jupyterlab#9624]
Whenever I edit my user preferences, they do not do anything.  I was working on a project and wanted to change a keybinding, so I changed running a cell to "Ctrl Enter", saved, and it did take effect.  I had a few other changed bindings as well, but so I close out of JupyterLab, open it back up, and none of them work.  I checked the preferences and they were just as left them, but to no avail they didn't change anything.  Every binding was the default in the settings.  All I messed with was the keybindings and I have checked to make sure there are no syntax errors in the user preferences.  They isn't much of a need for pictures because every key binding is the same as on the default settings.  Is there something that changed that I have to do to make my settings take effect?
Thanks in advance.

**Comment by jasongrout** [comment]
I just tried changing the evaluate cell keyboard shortcut, and it persisted across a jlab restart (jlab 3.0.5, macos Catalina, Firefox)

Please fill out the [bug report issue template](https://raw.githubusercontent.com/jupyterlab/jupyterlab/master/.github/ISSUE_TEMPLATE/bug_report.md) with the information it requests about your version of JupyterLab, browser, OS, etc., as well as a step-by-step reproduction of the issue you are seeing.

Also, I would suggest going through the troubleshooting/diagnosis guide in the documentation at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to try to narrow down the problem.

**Comment by unkn0wn-dev** [comment]
Alright, my hard drive just went out so I'll be reinstalling JupyterLab anyways.  I'll find out when I get a new PC set up.

**Comment by jasongrout** [comment]
Thanks. We'll close this for now, and if you have troubles again, please open another issue and fill out the reporting template.

**Comment by jasongrout** [comment]
> Alright, my hard drive just went out

Sorry to hear that!
