### ISSUE TITLE
Support more notebook file extensions

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#963]
For people who use other languages rather Python, it's appealing to being able to specify other file extensions (e.g., `irnb` for R, `ijlnb` for Julia, etc.) rather than `.ipynb` only. However, the current current notebook viewer supports only the `.ipynb` notebook file extension.

**Comment by blink1073** [comment]
Hi @dclong, this is a limitation of the notebook server itself, see https://github.com/jupyter/notebook/issues/1545

**Comment by jasongrout** [comment]
See also #4924 and #5247, which should allow contents managers that identify other files as notebooks to be opened with the notebook viewer.

**Comment by jasongrout** [comment]
Closing since the jlab portion is resolved in #5247, though the notebook limitation requires using a custom contents manager to identify other extensions as notebooks.
