### ISSUE TITLE
No kernell available

### ISSUE THREAD

**Issue by averri** [jupyterlab/jupyterlab#9637]
## Description
Jupyter lab shows no kernel available.

![image](https://user-images.githubusercontent.com/1898447/104946426-ecb06a00-59b1-11eb-8051-5b205560861b.png)

## Reproduce

1. Install Jupyter lab with `pip install jupyterlab`.
2. Start with `jupyter lab`

## Expected behavior
Jupyter lab shoud start with normally and show the kernels.

## Context

- Operating System and version: Ubuntu 18
- Browser and version: Chrome
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
$PATH:
	/home/alex/.local/bin
	/home/alex/.yarn/bin
	/home/alex/.config/yarn/global/node_modules/.bin
	/home/alex/.nvm/versions/node/v13.11.0/bin
	/home/alex/.local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/home/alex/.local/bin
	/usr/lib/python2.7
	/usr/lib/python2.7/plat-x86_64-linux-gnu
	/usr/lib/python2.7/lib-tk
	/usr/lib/python2.7/lib-old
	/usr/lib/python2.7/lib-dynload
	/home/alex/.local/lib/python2.7/site-packages
	/usr/local/lib/python2.7/dist-packages
	/usr/lib/python2.7/dist-packages
	/usr/lib/python2.7/dist-packages/gtk-2.0
	/usr/lib/python2.7/dist-packages/wx-3.0-gtk3

sys.executable:
	/usr/bin/python2

sys.version:
	2.7.17 (default, Jul 20 2020, 15:37:01) 
	[GCC 7.5.0]

platform.platform():
	Linux-4.15.0-118-generic-x86_64-with-Ubuntu-18.04-bionic

which -a jupyter:
	/home/alex/.local/bin/jupyter
	/home/alex/.local/bin/jupyter

pip list:
	asn1crypto (0.24.0)
	backports-abc (0.5)
	backports.functools-lru-cache (1.6.1)
	backports.shutil-get-terminal-size (1.0.0)
	backports.ssl-match-hostname (3.5.0.1)
	beautifulsoup4 (4.6.0)
	bleach (2.1.3)
	cached-property (1.3.1)
	certifi (2018.1.18)
	chardet (3.0.4)
	Cheetah (2.4.4)
	configparser (3.5.0)
	cryptography (2.1.4)
	cycler (0.10.0)
	decorator (4.4.2)
	docker (2.5.1)
	docker-compose (1.17.1)
	docker-pycreds (0.2.1)
	dockerpty (0.4.1)
	docopt (0.6.2)
	entrypoints (0.2.3)
	enum34 (1.1.10)
	funcsigs (1.0.2)
	functools32 (3.2.3.post2)
	futures (3.3.0)
	gyp (0.1)
	html5lib (1.0.1)
	idna (2.6)
	ipaddress (1.0.22)
	ipykernel (4.10.1)
	ipython (5.10.0)
	ipython-genutils (0.2.0)
	ipywidgets (7.3.1)
	Jinja2 (2.10)
	jsonschema (2.6.0)
	jupyter (1.0.0)
	jupyter-client (5.3.5)
	jupyter-console (5.2.0)
	jupyter-core (4.6.3)
	keyring (10.6.0)
	keyrings.alt (3.0)
	lxml (4.2.3)
	Markdown (2.6.9)
	MarkupSafe (1.0)
	matplotlib (2.1.1)
	mistune (0.8.3)
	mock (2.0.0)
	mysql-connector-python (2.1.6)
	mysql-utilities (1.6.4)
	nbconvert (5.3.1)
	nbformat (4.4.0)
	networkx (1.11)
	notebook (5.6.0)
	numpy (1.13.3)
	olefile (0.45.1)
	pandocfilters (1.4.2)
	paramiko (2.0.0)
	pathlib2 (2.3.5)
	pbr (3.1.1)
	pexpect (4.8.0)
	pickleshare (0.7.5)
	Pillow (5.1.0)
	pip (9.0.1)
	prometheus-client (0.3.0)
	prompt-toolkit (1.0.18)
	ptyprocess (0.7.0)
	pushnotify (0.5.1)
	pyasn1 (0.4.2)
	pycairo (1.16.2)
	pycrypto (2.6.1)
	Pygments (2.5.2)
	pygobject (3.26.1)
	PyICU (1.9.8)
	pyodbc (4.0.17)
	PyOpenGL (3.1.0)
	pyOpenSSL (17.5.0)
	pyparsing (2.2.0)
	pysqlite (2.7.0)
	python-dateutil (2.8.1)
	pytz (2018.3)
	pyxdg (0.25)
	PyYAML (3.12)
	pyzmq (19.0.2)
	qtconsole (4.3.1)
	requests (1.1.0)
	scandir (1.10.0)
	scipy (0.19.1)
	SecretStorage (2.3.1)
	Send2Trash (1.5.0)
	setuptools (44.1.1)
	simplegeneric (0.8.1)
	singledispatch (3.4.0.3)
	six (1.15.0)
	subprocess32 (3.2.7)
	terminado (0.8.1)
	testpath (0.3.1)
	texttable (0.9.1)
	tornado (5.1.1)
	traitlets (4.3.3)
	urllib3 (1.22)
	wcwidth (0.2.5)
	webencodings (0.5.1)
	websocket-client (0.44.0)
	wheel (0.30.0)
	widgetsnbextension (3.3.1)
	wxPython (3.0.2.0)
	wxPython-common (3.0.2.0)

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[D 2021-01-18 17:22:09.005 ServerApp] Searching ['/home/alex', '/home/alex/.jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2021-01-18 17:22:09.006 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2021-01-18 17:22:09.006 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2021-01-18 17:22:09.006 ServerApp] Looking for jupyter_config in /usr/etc/jupyter
[D 2021-01-18 17:22:09.006 ServerApp] Looking for jupyter_config in /home/alex/.jupyter
[D 2021-01-18 17:22:09.006 ServerApp] Looking for jupyter_config in /home/alex
[D 2021-01-18 17:22:09.007 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2021-01-18 17:22:09.008 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2021-01-18 17:22:09.008 ServerApp] Looking for jupyter_server_config in /usr/etc/jupyter
[D 2021-01-18 17:22:09.008 ServerApp] Looking for jupyter_server_config in /home/alex/.jupyter
[D 2021-01-18 17:22:09.008 ServerApp] Looking for jupyter_server_config in /home/alex
[D 2021-01-18 17:22:09.011 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/etc/jupyter/jupyter_server_config.json
[D 2021-01-18 17:22:09.012 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/usr/local/etc/jupyter/jupyter_server_config.json
[D 2021-01-18 17:22:09.012 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/usr/etc/jupyter/jupyter_server_config.json
[D 2021-01-18 17:22:09.012 ServerApp] Paths used for configuration of jupyter_server_config: 
    	/home/alex/.jupyter/jupyter_server_config.json
[I 2021-01-18 17:22:09.022 ServerApp] jupyterlab | extension was successfully linked.
[D 2021-01-18 17:22:09.023 ServerApp] Raising open file limit: soft 1024->4096; hard 4096->4096
[I 2021-01-18 17:22:09.050 LabApp] JupyterLab extension loaded from /home/alex/.local/lib/python3.7/site-packages/jupyterlab
[I 2021-01-18 17:22:09.051 LabApp] JupyterLab application directory is /home/alex/.local/share/jupyter/lab
[I 2021-01-18 17:22:09.054 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-01-18 17:22:09.054 ServerApp] Serving notebooks from local directory: /home/alex
[I 2021-01-18 17:22:09.054 ServerApp] Jupyter Server 1.2.2 is running at:
[I 2021-01-18 17:22:09.054 ServerApp] http://localhost:8888/lab?token=61108277bef323d5c0fa1d8ae8205e24cf68e1612d12710a
[I 2021-01-18 17:22:09.054 ServerApp]  or http://127.0.0.1:8888/lab?token=61108277bef323d5c0fa1d8ae8205e24cf68e1612d12710a
[I 2021-01-18 17:22:09.054 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2021-01-18 17:22:09.077 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/alex/.local/share/jupyter/runtime/jpserver-20782-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=61108277bef323d5c0fa1d8ae8205e24cf68e1612d12710a
     or http://127.0.0.1:8888/lab?token=61108277bef323d5c0fa1d8ae8205e24cf68e1612d12710a
[D 2021-01-18 17:22:10.454 ServerApp] Accepting token-authenticated connection from 127.0.0.1
[D 2021-01-18 17:22:10.458 ServerApp] Paths used for configuration of page_config: 
    	/etc/jupyter/labconfig/page_config.json
[D 2021-01-18 17:22:10.459 ServerApp] Paths used for configuration of page_config: 
    	/usr/local/etc/jupyter/labconfig/page_config.json
[D 2021-01-18 17:22:10.459 ServerApp] Paths used for configuration of page_config: 
    	/usr/etc/jupyter/labconfig/page_config.json
[D 2021-01-18 17:22:10.460 ServerApp] Paths used for configuration of page_config: 
    	/home/alex/.jupyter/labconfig/page_config.json
[D 2021-01-18 17:22:10.461 LabApp] Using contents: services/contents
[D 2021-01-18 17:22:10.468 LabApp] 200 GET /lab?token=61108277bef323d5c0fa1d8ae8205e24cf68e1612d12710a (127.0.0.1) 14.32ms
[D 2021-01-18 17:22:10.502 ServerApp] Path main.0db8c5dcfd4ee1b4ae00.js served from /home/alex/.local/share/jupyter/lab/static/main.0db8c5dcfd4ee1b4ae00.js
[D 2021-01-18 17:22:10.503 ServerApp] 304 GET /static/lab/main.0db8c5dcfd4ee1b4ae00.js (127.0.0.1) 2.86ms
[D 2021-01-18 17:22:10.522 ServerApp] Path jlab_core.ec15f8c091a46864d4c7.js served from /home/alex/.local/share/jupyter/lab/static/jlab_core.ec15f8c091a46864d4c7.js
[D 2021-01-18 17:22:10.523 ServerApp] 304 GET /static/lab/jlab_core.ec15f8c091a46864d4c7.js (127.0.0.1) 0.99ms
[D 2021-01-18 17:22:10.524 ServerApp] Path 2719.c37de80033ca3a5d5fc7.js served from /home/alex/.local/share/jupyter/lab/static/2719.c37de80033ca3a5d5fc7.js
[D 2021-01-18 17:22:10.524 ServerApp] 304 GET /static/lab/2719.c37de80033ca3a5d5fc7.js (127.0.0.1) 1.00ms
[D 2021-01-18 17:22:10.528 ServerApp] Path 9473.efbac28893cee30cbf10.js served from /home/alex/.local/share/jupyter/lab/static/9473.efbac28893cee30cbf10.js
[D 2021-01-18 17:22:10.528 ServerApp] 304 GET /static/lab/9473.efbac28893cee30cbf10.js (127.0.0.1) 1.31ms
[D 2021-01-18 17:22:10.535 ServerApp] Path 3906.e016c64f40b873694c86.js served from /home/alex/.local/share/jupyter/lab/static/3906.e016c64f40b873694c86.js
[D 2021-01-18 17:22:10.536 ServerApp] 304 GET /static/lab/3906.e016c64f40b873694c86.js (127.0.0.1) 6.72ms
[D 2021-01-18 17:22:10.536 ServerApp] Path 6700.1559a2ad210fd059979c.js served from /home/alex/.local/share/jupyter/lab/static/6700.1559a2ad210fd059979c.js
[D 2021-01-18 17:22:10.537 ServerApp] 304 GET /static/lab/6700.1559a2ad210fd059979c.js (127.0.0.1) 5.99ms
[D 2021-01-18 17:22:10.537 ServerApp] Path 2156.5874bab119ec82f63eef.js served from /home/alex/.local/share/jupyter/lab/static/2156.5874bab119ec82f63eef.js
[D 2021-01-18 17:22:10.538 ServerApp] 304 GET /static/lab/2156.5874bab119ec82f63eef.js (127.0.0.1) 4.64ms
[D 2021-01-18 17:22:10.540 ServerApp] Path 1033.c3c916187bd5ca1af850.js served from /home/alex/.local/share/jupyter/lab/static/1033.c3c916187bd5ca1af850.js
[D 2021-01-18 17:22:10.540 ServerApp] 304 GET /static/lab/1033.c3c916187bd5ca1af850.js (127.0.0.1) 1.12ms
[D 2021-01-18 17:22:10.543 ServerApp] Path 4570.65a6dc1e8df29e6d6ef6.js served from /home/alex/.local/share/jupyter/lab/static/4570.65a6dc1e8df29e6d6ef6.js
[D 2021-01-18 17:22:10.545 ServerApp] 304 GET /static/lab/4570.65a6dc1e8df29e6d6ef6.js (127.0.0.1) 2.77ms
[D 2021-01-18 17:22:10.547 ServerApp] Path 807.f93649ae3be8abed3a71.js served from /home/alex/.local/share/jupyter/lab/static/807.f93649ae3be8abed3a71.js
[D 2021-01-18 17:22:10.549 ServerApp] 304 GET /static/lab/807.f93649ae3be8abed3a71.js (127.0.0.1) 2.56ms
[D 2021-01-18 17:22:10.552 ServerApp] Path 7294.8fc496565326be3733e8.js served from /home/alex/.local/share/jupyter/lab/static/7294.8fc496565326be3733e8.js
[D 2021-01-18 17:22:10.553 ServerApp] 304 GET /static/lab/7294.8fc496565326be3733e8.js (127.0.0.1) 3.09ms
[D 2021-01-18 17:22:10.556 ServerApp] Path 3935.477614ef891d92966eeb.js served from /home/alex/.local/share/jupyter/lab/static/3935.477614ef891d92966eeb.js
[D 2021-01-18 17:22:10.556 ServerApp] 304 GET /static/lab/3935.477614ef891d92966eeb.js (127.0.0.1) 2.89ms
[D 2021-01-18 17:22:10.559 ServerApp] Path 4631.d7314a0f87e485d17182.js served from /home/alex/.local/share/jupyter/lab/static/4631.d7314a0f87e485d17182.js
[D 2021-01-18 17:22:10.559 ServerApp] 304 GET /static/lab/4631.d7314a0f87e485d17182.js (127.0.0.1) 2.49ms
[D 2021-01-18 17:22:10.565 ServerApp] Path 7409.ee0bd0d96f254957f5fe.js served from /home/alex/.local/share/jupyter/lab/static/7409.ee0bd0d96f254957f5fe.js
[D 2021-01-18 17:22:10.566 ServerApp] 304 GET /static/lab/7409.ee0bd0d96f254957f5fe.js (127.0.0.1) 8.09ms
[D 2021-01-18 17:22:10.567 ServerApp] Path 7755.f8e1b362bda58bfd1192.js served from /home/alex/.local/share/jupyter/lab/static/7755.f8e1b362bda58bfd1192.js
[D 2021-01-18 17:22:10.568 ServerApp] 304 GET /static/lab/7755.f8e1b362bda58bfd1192.js (127.0.0.1) 7.64ms
[D 2021-01-18 17:22:10.570 ServerApp] Path 2747.4b495147989b5a9a29f8.js served from /home/alex/.local/share/jupyter/lab/static/2747.4b495147989b5a9a29f8.js
[D 2021-01-18 17:22:10.571 ServerApp] 304 GET /static/lab/2747.4b495147989b5a9a29f8.js (127.0.0.1) 1.78ms
[D 2021-01-18 17:22:10.573 ServerApp] Path 1902.d5b9664dd812aa89e101.js served from /home/alex/.local/share/jupyter/lab/static/1902.d5b9664dd812aa89e101.js
[D 2021-01-18 17:22:10.573 ServerApp] 304 GET /static/lab/1902.d5b9664dd812aa89e101.js (127.0.0.1) 2.07ms
[D 2021-01-18 17:22:10.579 ServerApp] Path 1249.e510628228e20c1d52eb.js served from /home/alex/.local/share/jupyter/lab/static/1249.e510628228e20c1d52eb.js
[D 2021-01-18 17:22:10.580 ServerApp] 304 GET /static/lab/1249.e510628228e20c1d52eb.js (127.0.0.1) 1.86ms
[D 2021-01-18 17:22:10.586 ServerApp] Path 1358.5d13bafd71e17aa4c0e6.js served from /home/alex/.local/share/jupyter/lab/static/1358.5d13bafd71e17aa4c0e6.js
[D 2021-01-18 17:22:10.586 ServerApp] 304 GET /static/lab/1358.5d13bafd71e17aa4c0e6.js (127.0.0.1) 2.51ms
[D 2021-01-18 17:22:10.589 ServerApp] Path 911.7d289642557a8018cbaa.js served from /home/alex/.local/share/jupyter/lab/static/911.7d289642557a8018cbaa.js
[D 2021-01-18 17:22:10.590 ServerApp] 304 GET /static/lab/911.7d289642557a8018cbaa.js (127.0.0.1) 1.49ms
[D 2021-01-18 17:22:10.597 ServerApp] Path 4429.fa7e08d5a51ece1132ad.js served from /home/alex/.local/share/jupyter/lab/static/4429.fa7e08d5a51ece1132ad.js
[D 2021-01-18 17:22:10.597 ServerApp] 304 GET /static/lab/4429.fa7e08d5a51ece1132ad.js (127.0.0.1) 5.68ms
[D 2021-01-18 17:22:10.598 ServerApp] Path 126.c560e3971209c7f561f6.js served from /home/alex/.local/share/jupyter/lab/static/126.c560e3971209c7f561f6.js
[D 2021-01-18 17:22:10.600 ServerApp] 304 GET /static/lab/126.c560e3971209c7f561f6.js (127.0.0.1) 7.48ms
[D 2021-01-18 17:22:10.601 ServerApp] Path 3496.8d122ae6b046af048cf5.js served from /home/alex/.local/share/jupyter/lab/static/3496.8d122ae6b046af048cf5.js
[D 2021-01-18 17:22:10.603 ServerApp] 304 GET /static/lab/3496.8d122ae6b046af048cf5.js (127.0.0.1) 8.74ms
[D 2021-01-18 17:22:10.605 ServerApp] Path 1641.568068a89387fdfe68d4.js served from /home/alex/.local/share/jupyter/lab/static/1641.568068a89387fdfe68d4.js
[D 2021-01-18 17:22:10.605 ServerApp] 304 GET /static/lab/1641.568068a89387fdfe68d4.js (127.0.0.1) 9.47ms
[D 2021-01-18 17:22:10.606 ServerApp] Path 714.db04278404689f9f8301.js served from /home/alex/.local/share/jupyter/lab/static/714.db04278404689f9f8301.js
[D 2021-01-18 17:22:10.606 ServerApp] 304 GET /static/lab/714.db04278404689f9f8301.js (127.0.0.1) 3.02ms
[D 2021-01-18 17:22:11.216 ServerApp] Accepting token-authenticated connection from 127.0.0.1
[E 2021-01-18 17:22:11.281 ServerApp] Uncaught exception GET /api/kernelspecs?1610990531212 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernelspecs?1610990531212', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 528, in get
        value = obj._trait_values[self.name]
    KeyError: 'kernel_dirs'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/alex/.local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/home/alex/.local/lib/python3.7/site-packages/jupyter_server/services/kernelspecs/handlers.py", line 65, in get
        kspecs = await ensure_async(ksm.get_all_specs())
      File "/home/alex/.local/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 252, in get_all_specs
        d = self.find_kernel_specs()
      File "/home/alex/.local/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 164, in find_kernel_specs
        for kernel_dir in self.kernel_dirs:
      File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 556, in __get__
        return self.get(obj, cls)
      File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 535, in get
        value = self._validate(obj, dynamic_default())
      File "/home/alex/.local/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 150, in _kernel_dirs_default
        from IPython.paths import get_ipython_dir
      File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 48, in <module>
        from .core.application import Application
      File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 25, in <module>
        from IPython.core import release, crashhandler
      File "/usr/lib/python3/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
        from IPython.core import ultratb
      File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 124, in <module>
        from IPython.utils import path as util_path
      File "/usr/lib/python3/dist-packages/IPython/utils/path.py", line 18, in <module>
        from IPython.utils.process import system
      File "/usr/lib/python3/dist-packages/IPython/utils/process.py", line 19, in <module>
        from ._process_posix import system, getoutput, arg_split, check_pid
      File "/usr/lib/python3/dist-packages/IPython/utils/_process_posix.py", line 24, in <module>
        import pexpect
      File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
        from .pty_spawn import spawn, spawnu
      File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 14, in <module>
        from .spawnbase import SpawnBase
      File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 224
        def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                       ^
    SyntaxError: invalid syntax
[W 2021-01-18 17:22:11.286 ServerApp] Unhandled error

</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
</pre>
</details>

**Comment by jasongrout** [comment]
Looks like there is an error when trying to find kernels:

```
Traceback (most recent call last):

File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 528, in get

value = obj._trait_values[self.name]

KeyError: 'kernel_dirs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/alex/.local/lib/python3.7/site-packages/jupyter_server/services/kernelspecs/handlers.py", line 65, in get
    kspecs = await ensure_async(ksm.get_all_specs())
  File "/home/alex/.local/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 252, in get_all_specs
    d = self.find_kernel_specs()
  File "/home/alex/.local/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 164, in find_kernel_specs
    for kernel_dir in self.kernel_dirs:
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/alex/.local/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 150, in _kernel_dirs_default
    from IPython.paths import get_ipython_dir
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/usr/lib/python3/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 124, in <module>
    from IPython.utils import path as util_path
  File "/usr/lib/python3/dist-packages/IPython/utils/path.py", line 18, in <module>
    from IPython.utils.process import system
  File "/usr/lib/python3/dist-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/usr/lib/python3/dist-packages/IPython/utils/_process_posix.py", line 24, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax
```

The error points to "async" - perhaps this is an old version of pexpect that has "async", which IIRC now is a reserved keyword in python 3?

* You can confirm by running `jupyter kernelspec list` to get the list of kernels. You likely will have the same error.
* Perhaps upgrading pexpect, which is where the error seems to come from? I'd suggest a new clean environment too.

**Comment by averri** [comment]
Hi @jasongrout, thank you. I had resolved by installing a new virtual environment with Python 3.8.
jupyterlab is working fine now.
