### ISSUE TITLE
JupyterLab3.0.5 not load settings for jupytext in `jupyter_notebook_config.py`?

### ISSUE THREAD

**Issue by DevGosugi** [jupyterlab/jupyterlab#9638]
## Description
I want the feature that auto creating `.py` with `.ipynb` and converting in JupyterLab.
But I can't, but, **I can use the feature in JupyterNotebook**.
Is it necessary Node.js ...? How should I do?

## Reproduce
- Environment
  - OS: MacOS Catalina
  - Python3.7.9 on pipenv
1. Install `jupyterlab3.0.5` with `pipenv`.
  ```
  $ pipenv install jupyterlab jupytext
  ```
2. Create `jupyter_notebook_config.py` and add settings.
  ```
  $ pipenv run jupyter notebook --generate-config
  $ echo 'c.NotebookApp.contents_manager_class = "jupytext.TextFileContentsManager"' >> ~/.jupyter/jupyter_notebook_config.py
  $ echo 'c.ContentsManager.default_jupytext_formats = "ipynb,py"' >> ~/.jupyter/jupyter_notebook_config.py
  ```
3. Launch JupyterLab.
  ```
  $ pipenv run jupyter lab
  ```
4. Check whether `.py` created when you create `.ipynb`.

**Comment by jasongrout** [comment]
See https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#jupyter-server for instructions on migrating `jupyter_notebook_config.py` settings to JupyterLab 3.0.

**Comment by DevGosugi** [comment]
@jasongrout 
Thanks!
And solved!

As you say, maybe the change dependent to Jupyter Server caused.
But we can solve by changing settings in jupyter_notebook_config.py(not juipyter_server_config.py!) below.
```
from jupytext.contentsmanager import build_jupytext_contents_manager_class
from jupyter_server.services.contents.largefilemanager import LargeFileManager
c.NotebookApp.contents_manager_class = build_jupytext_contents_manager_class(LargeFileManager)

c.ContentsManager.default_jupytext_formats = "ipynb,py"
```

**Comment by DevGosugi** [comment]
Duplicate of https://github.com/mwouts/jupytext/issues/713
