### ISSUE TITLE
delete folder recursively in file explorer

### ISSUE THREAD

**Issue by romeokienzler** [jupyterlab/jupyterlab#9644]
### Problem
In the file explorer I can't delete a folder when it is not empty. So I have to open a terminal and enter the delete command manually. 

![image](https://user-images.githubusercontent.com/5694071/105145836-8cc7d980-5aff-11eb-9b70-66af6ea17258.png)

### Proposed Solution

When right-clicking on a non-empty folder I should be able to tick a checkbox or click an additional button "delete recursively"

![image](https://user-images.githubusercontent.com/5694071/105146044-cdbfee00-5aff-11eb-811e-c3aa46fb6572.png)

Currently, I'm getting an error message:

![image](https://user-images.githubusercontent.com/5694071/105146188-f9db6f00-5aff-11eb-9370-1c17d57cf611.png)

**Comment by WentingTan** [comment]
May I ask on what OS did you run the jlab app? @romeokienzler

**Comment by romeokienzler** [comment]
I've tested it on JL 3.2.4 and it works, not sure in which version it was fixed but thank you very much!
