### ISSUE TITLE
cell id changes on save 

### ISSUE THREAD

**Issue by teucer** [jupyterlab/jupyterlab#9645]
The new version of `nbformat` has introduced cell ids.

I wanted to test the new functionality

## Reproduce

1. Opened a new jupyter notebook
2. Added a cell with content print("hello") and saved the notebook
3. Stored the cell id
4. Added a second cell with the content print("world") and saved the notebook

## Expected behavior

Compare the cell id of the first cell in step 4. with the one stored in step 3. they should be the same.

## Context

- Operating System and version: Windows 7
- Browser and version: Chrome Version 86.0.4240.183 
- JupyterLab version: 3.0.5

<details><summary>Troubleshoot Output</summary>
<pre>
The two ids are different.
</pre>
</details>

**Comment by jasongrout** [comment]
JupyterLab does not support cell ids yet. I was just commenting on the issue a few hours ago over at #9064

**Comment by callegar** [comment]
Indeed it looks like all cells IDs change on save. This is very inconvenient: the notebook is substantially a text file and it would be desirable to diff it even without specialized tools, but the ID changes make the output extra polluted (every cell appears as changed). Furthermore, many VCS work efficiently by using deltas and hashes. The current situation makes deltas unnecessarily large and hashes change even when nothing has actually changed (you re-save the file without any change and you still get a different file and a different hash).

**Comment by andioz** [comment]
I'm struggling with this issue for some time now. In combination with git, it is nearly impossible to see if I have changes in my notebooks or just reverted it after some tests to the original state. I hope this will be fixed soon.

**Comment by ian-s-mcb** [comment]
This issue has been a major frustration for last couple months. I'm also hoping for a fix. Fortunately, Jupyter Notebook doesn't have this issue, so that's what I'll be using for now.

I had a hard time searching for this issue, so I'm wondering if @teucer could expand the issue description. @callegar explained the issue well. Spelling out why the cell id changes are problematic would be good.

**Comment by andioz** [comment]
> Jupyter Notebook doesn't have this issue

Good to know this 👍

**Comment by jasongrout** [comment]
> I had a hard time searching for this issue, so I'm wondering if @teucer could expand the issue description. @callegar explained the issue well. Spelling out why the cell id changes are problematic would be good.

See also https://github.com/jupyterlab/jupyterlab/issues/9729, and a work-in-progress PR at https://github.com/jupyterlab/jupyterlab/pull/10018

**Comment by ian-s-mcb** [comment]
Thanks @jasongrout . I missed that issue. Now I know where to look for updates on the eventual fix.
