### ISSUE TITLE
Command palette not searching for keywords correctly

### ISSUE THREAD

**Issue by falconair** [jupyterlab/jupyterlab#9659]
## Description
I open the command palette and search for "clear", expecting to find all commands related to clearing cells. It shows me "clear outputs", but not "clear all outputs". 
![image](https://user-images.githubusercontent.com/365542/105441152-8fc0e800-5c2d-11eb-9800-3ac1b9fa8528.png)
For that, I have to search for "all"
![image](https://user-images.githubusercontent.com/365542/105441218-b1ba6a80-5c2d-11eb-8d19-f6c257cd3e75.png)

## Reproduce

1. Open a notebook in JupyterLab (3.0)
2. Press ctrl+shift+c (or open from menu)
3. type in 'clear'

## Expected behavior
I expect to see "Clear outputs" but also "Clear all outputs"

## Context

- Operating System and version:
- Browser and version: Chrome, windows 10, 87.0.4280.141 (Official Build) (64-bit) (cohort: Stable)
- JupyterLab version: 3.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
This is really confusing because the headings are hidden. Here's what we see in JLab 2, which shows the headings. You'll notice that it still isn't very good because it shows all of the bad matches in that notebook category before showing the best matches in another category, but at least you kind of see what is going on. In JLab 3, the categories are not displayed, so it just is really confusing.

<img width="315" alt="Screen Shot 2021-01-21 at 9 28 46 PM" src="https://user-images.githubusercontent.com/192614/105450636-c1d34980-5c2f-11eb-941e-c5112720b350.png">

**Comment by jasongrout** [comment]
Ideally we put the category names back in the command palette for each item, and we sort by best match without regard to the category the item is in.

**Comment by jasongrout** [comment]
> Ideally we put the category names back in the command palette for each item, and we sort by best match without regard to the category the item is in.

FYI, this would be a Lumino change.

**Comment by dharmaquark** [comment]
I'd like to try to tackle this one if it's unclaimed! (happy to link to lumino issue if easier?)

**Comment by dharmaquark** [comment]
> I'd like to try to tackle this one if it's unclaimed! (happy to link to lumino issue if easier?)

looking into the existing lumino command palette logic, it looks like this is where we currently render the header, so trying to test locally to see how this would need to be updated to add back the category names in the command palette for items:
https://github.com/jupyterlab/lumino/blob/578509cae6af5567975a6ed2e6bc9d8a1927a078/packages/widgets/src/commandpalette.ts#L331

**Comment by JasonWeill** [comment]
This is still an issue in 4.2.1:

<img width="294" alt="image" src="https://github.com/jupyterlab/jupyterlab/assets/93281816/2089e037-a840-48dc-9b4e-d29c6b544019">
