### ISSUE TITLE
Empty toolbar not updating when switching to simple interface

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9665]
## Description

In https://github.com/jupyterlab/jupyterlab/blob/74ccaf4b02c6540c974c8d337b492a0badeb9e8e/packages/apputils/style/toolbar.css#L107-L112 we see that a "micro toolbar", i.e., an activity toolbar that has been collapsed because nothing is in it, is supposed to be completely collapsed in simple interface mode. Normally it has a height of 8px, which is set by a CSS variable: https://github.com/jupyterlab/jupyterlab/blob/74ccaf4b02c6540c974c8d337b492a0badeb9e8e/packages/apputils/style/toolbar.css#L21 https://github.com/jupyterlab/jupyterlab/blob/74ccaf4b02c6540c974c8d337b492a0badeb9e8e/packages/theme-light-extension/style/variables.css#L314

However, it seems that at least Launcher widgets are not updated when switching to simple interface, so they retain the 8px micro toolbar. New launchers respect the 0px micro toolbar, so you see a bit of jumping when creating a new launcher. When you create a new launcher in the simple interface, it starts out with a 0px microtoolbar, but toggling simple interface off and then back on reverts things back to an 8px toolbar.

While this is sort of a small visual issue, it points to something not being refreshed when it should be refreshed. In general, widgets may change their appearance when in Simple Interface, and this is showing that there are problems right now with the update being called when switching to Simple Interface.

## Reproduce

1. Make sure you are not in Simple Interface, create a launcher. It helps to see how things are working if you resize the window to be narrow enough that the launcher has a scrollbar.
2. Switch to simple interface. Note the toolbar space still is 8px high, visible as the space between the scrollbar and the top of the launcher panel.
2. Create a new launcher panel. Notice that the scrollbar now goes up to the top of the panel (i.e., the 8px high toolbar space is gone)
3. Toggle off simple interface, then back on. Notice that the toolbar now is 8px high.

## Expected behavior

The toolbar to go to 0px in Simple Interface when I toggle Simple Interface.

## Context

- Operating System and version: macOS Catalina
- Browser and version: Firefox 84
- JupyterLab version: 3.0.5

**Comment by krassowski** [comment]
The toolbars were rewritten in 4.1, does it still appear in this release? Do you have a screenshot to demonstrate the issue?

**Comment by JasonWeill** [comment]
@jasongrout @krassowski Any update about whether this still appears in 4.1.x?
