### ISSUE TITLE
Interface issue

### ISSUE THREAD

**Issue by gorodion** [jupyterlab/jupyterlab#9669]
please return 2.2.x Jupyter lab interface. That was better.

**Comment by krassowski** [comment]
Is there a specific interface element in 3.0 version that is an annoyance to you?

**Comment by gorodion** [comment]
Hello
I think switch "Simple" in the lower part is useless and also it's could be better to return the "property inspector" to the left panel of icons. This is just my personal perception

**Comment by jasongrout** [comment]
You can move the property inspector back to the left side by right-clicking on the sidebar icon and choosing the option to move it.

**Comment by gorodion** [comment]
Oh, thanks
