### ISSUE TITLE
Automatically switch to scrolling mode of output cells when the output is long

### ISSUE THREAD

**Issue by falconair** [jupyterlab/jupyterlab#9673]
### Problem

Coming from the classic notebook, I never cared about printing an output which was a few hundred lines long. However, in JupyterLab 3.0, the whole output is printed to the output cell and the cell does not switch to a scrolling mode. This is a huge usability issue.

This is particularly worse for newbies. For example, a student might print a matrix and all of a sudden, they have to scroll for miles to navigate their notebook.

### Proposed Solution

I think the ideal solution is to set some threshold. If an output goes beyond that threshold, change the output cell to scroll.

I never explicitly thought about it in notebook, but I think things are better there. What's more, I can click on the gutter to display the whole output or just part of it.

**Comment by jasongrout** [comment]
Good news! @echarles (and others?) has been experimenting with implementing this, currently released in 2.3.0rc0, with the idea that this would be ported to 3.1. Feel free to try it out in 2.3.0rc0 and tell us what you think of the implementation.

**Comment by jruales** [comment]
@echarles could you please confirm if this mean implementing "scrolled":"auto" mode that classic Jupyter Notebook supports in addition to "scrolled":true and "scrolled":false? When "auto" scrolling mode is enabled in Jupyter Notebook, an output shows as scrolled (within a scroll area of height 336px) if and only if the output height exceeds ~1778px in height (equivalent of ~100 lines of text).

**Comment by echarles** [comment]
@jruales I am not sure. We have in 2.3 a feature called "stripped output" which only shows the first and last N rows of an output. This feature is being ported to master branch.

**Comment by goanpeca** [comment]
>@jruales I am not sure. We have in 2.3 a feature called "stripped output" which only shows the first and last N rows of an output. This feature is being ported to master branch.

This feature has been ported to master branch :) and will be available for 3.1

**Comment by jruales** [comment]
@jasongrout It seems like the feature that @echarles and @goanpeca are talking about, although somewhat similar in nature, is actually not the same as the one mentioned in the current GitHub issue. Is the enhancement requested in this GitHub issue also planned for 3.1?

**Comment by krassowski** [comment]
It looks that another issue was opened to track exactly this in the meantime and attracted a bit more attention: #11760. I will close this one in favour of the newer duplicate to reduce duplication of issues but it is still very much on the agenda!
