### ISSUE TITLE
Turning on and off debugger makes line numbers dissapear

### ISSUE THREAD

**Issue by joseberlines** [jupyterlab/jupyterlab#9675]
If you have line numbers on (personal setting) when I turn on the debugger mode and turn it off again the line numbers dissapear.

![image](https://user-images.githubusercontent.com/33203439/105806811-eff4b880-5fa4-11eb-872d-9a6e3a463689.png)

now turning off the debugger. lines are gone

![image](https://user-images.githubusercontent.com/33203439/105806842-026ef200-5fa5-11eb-946e-43324c363279.png)

**Comment by joseberlines** [comment]
btw, in the same screenshot include in this issue there might be another one. 
from Ipython.display import image does not work in Xpython (but it works in python 3.8)

**Comment by jtpio** [comment]
>  from Ipython.display import image does not work in Xpython (but it works in python 3.8)

There is ongoing work about this in https://github.com/jupyter-xeus/xeus-python/pull/393, so it might be worth looking into the `xeus-python` repository for this particular issue.

**Comment by martinRenou** [comment]
> There is ongoing work about this in jupyter-xeus/xeus-python#393, so it might be worth looking into the xeus-python repository for this particular issue.

Yes. It has been a longstanding issue but it will soon be fixed. The fix is quite ugly but IPython 8 will bring some changes that will make this cleaner.

**Comment by pplonski** [comment]
Just want to add that a similar bug is in the file editor (not only in the notebooks). Switching debugger hides the line numbers.
