### ISSUE TITLE
MathJax error when base_url is changed on systemwide installation of JupyterLab

### ISSUE THREAD

**Issue by julianrosen** [jupyterlab/jupyterlab#9678]
In some instance, MathJax seems to stop working when base_url option is changed in the config file.

Here is the situation: I install jupyterlab system-wide with `sudo pip3 install jupyterlab` (I know running pip as root poses a security risk). After generating the jupterlab config file, I change the appropriate line to `c.ServerApp.base_url = 'some_base_url'`, then start jupyterlab. When I connect to the notebook server in by browser and open a notebook, jupyter gives my the following message in the terminal:
`[W 2021-01-26 12:02:17.751 ServerApp] 404 GET /some_base_url/some_base_url/static/notebook/components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full,Safe&amp;delayStartupUntil=configured (127.0.0.1) 1.49ms referer=http://desktop:8888/some_base_url/lab/tree/Untitled.ipynb`
MathJax then will not render in the notebook.

MathJax works fine if I leave `c.ServerApp.base_url` at its default value. Everything is also fine if I instead install jupyterlab with `pip3 install jupyterlab` (resulting in an installation for just one user).

This bug occurs for me on Ubuntu 20.04.1 and on Raspberry Pi OS (Raspbian 10 buster). The bug replicates on a fresh OS installation on the Raspberry Pi, so this seems to rule out some conflict with another package. I tried connecting to the notebook server with Chromium and with Firefox, same result.

`jupyter-lab --version` returns `3.0.5`, and `jupyter notebook --version` returns `6.2.0`.

**Comment by jasongrout** [comment]
This looks like a duplicate of https://github.com/jupyterlab/jupyterlab_server/issues/152 and is fixed at https://github.com/jupyterlab/jupyterlab_server/pull/153. Let's move further discussion to those issues. Thanks!

**Comment by jasongrout** [comment]
Looks like the fix has been released in jupyterlab_server 2.1.3 just now.
