### ISSUE TITLE
Invalid URL print preprocessing

### ISSUE THREAD

**Issue by TIPConsulting** [jupyterlab/jupyterlab#9679]
## Description

Attempting to print a url string improperly encodes the output, resulting in a broken link.  Specifically, ampersands in the query string are being converted to `&amp;`.  This is not valid and the printed value is not a valid link

## Reproduce

![image](https://user-images.githubusercontent.com/17582002/105972139-8c23cb80-6048-11eb-8e25-900852a5270d.png)

## Expected behavior

The printed output should be exactly the same as the value visible in the string variable.  Jupyter Notebook handles this properly when tested on the same computer

## Context

- Operating System and version: Win10 2004
- Browser and version: Chrome
- JupyterLab version: 2.1.5

**Comment by jasongrout** [comment]
This has been reported at https://github.com/jupyterlab/jupyterlab/issues/8722. Let's consolidate the conversation over there. Thanks!

**Comment by jasongrout** [comment]
This works in jlab 3 for me. Likely fixed in #8496?

<img width="488" alt="Screen Shot 2021-01-27 at 8 42 49 AM" src="https://user-images.githubusercontent.com/192614/106023524-ba6ece80-607b-11eb-9053-b89952f883bd.png">

Looks like it might have been fixed in jlab 2.2.0
