### ISSUE TITLE
Files does not show on Finder

### ISSUE THREAD

**Issue by xtream111** [jupyterlab/jupyterlab#9680]
Hello everyone, just encountered an annoying thing when working with Jupyter Lab.

I started up Jupyter Lab on a folder and started working on my things as you can see here

![Captura de pantalla 2021-01-27 a las 12 11 48](https://user-images.githubusercontent.com/59622725/105983387-f9f7e380-6098-11eb-969d-32114b16b775.png)

However, when I go to the same folder In my laptop, I cannot find the files that you can see there. Picture attached.

![Captura de pantalla 2021-01-27 a las 12 13 39](https://user-images.githubusercontent.com/59622725/105983488-1f84ed00-6099-11eb-91c7-37b3c43da4e5.png)

What is the solution to this, I know that downloading manually works but shouldn't it save automatically in my finder as well?

**Comment by jasongrout** [comment]
Are you absolutely sure these are the same folders? Do the timestamps of the files you see match up?

**Comment by xtream111** [comment]
I am sure it is the same folder because I created one specifically for this notebook.

Using `pwd` in the notebook gives me the same location as well.

Timestamps do not match

**Comment by jasongrout** [comment]
If timestamps do not match, it is likely a different folder.

I haven't heard of a problem like this before. If you can give a set of reproducible instructions, I can try testing. 

Please fill out the [bug report issue template](https://raw.githubusercontent.com/jupyterlab/jupyterlab/master/.github/ISSUE_TEMPLATE/bug_report.md) with the information it requests about your version of JupyterLab, browser, OS, etc. It seems you deleted or ignored the information requested.

Also, I would suggest going through the troubleshooting/diagnosis guide in the documentation at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to try to narrow down the problem. It may also help to launch jlab with `--debug` to see exactly what folder it is considering the root.

**Comment by jasongrout** [comment]
> Using `pwd` in the notebook gives me the same location as well.

Depending on how you have kernels set up, a kernel may be started in a different directory than the notebook. The default is to start the kernel with the current working directory of the notebook, of course, so this is puzzling indeed.
