### ISSUE TITLE
Clearly label labextension build/develop/watch commands as developer commands

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9700]
We've mixed the user-level commands and the developer-level commands in `jupyter labextension`. We see some confusion at https://discourse.jupyter.org/t/jupyterlab-build-terminology/7714, for example. It's doubly confusing because for a long time now we've forced users to think about "building" jupyterlab, but the build referred to here is not about building jlab, but building a prebuilt extension.

Ideally we would separate out these developer-facing subcommands (build/develop/watch) so users are not always seeing them. Perhaps we can make this breaking change in jlab 4.

For now, I think we should clearly label each of these subcommands as being purely for extension developers in the `jupyter labextension -h` help.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterlab-build-terminology/7714/3
