### ISSUE TITLE
Add a tab reopen feature

### ISSUE THREAD

**Issue by apcamargo** [jupyterlab/jupyterlab#9703]
### Problem

If you close a notebook tab and need to reopen it, you need to navigate to the file (which might not be in the current directory) and open it again.

### Proposed Solution

Add a "Reopen close tab" to a context menu in the tabs bar.

**Comment by kpinnipa** [comment]
Is there anyone working on this issue?

**Comment by goanpeca** [comment]
Hi @kpinnipa it seems no one is working on this (yet), would you like to take a stab at it :) ?

Happy to provide pointers. Cheers!

**Comment by kpinnipa** [comment]
Thanks for the quick response! I thought I might have some time this week but got a bit busy; might try to work on it in the future but not sure so I'll follow up if I do (although totally fine if someone else takes it on instead).

**Comment by krassowski** [comment]
Closing as this was implemented in https://github.com/jupyterlab/jupyterlab/pull/16250 and released in JupyterLab 4.2.0.
