### ISSUE TITLE
update jupyterlab to 3.0.x，open browser with empty page of "A Jupyter Server Is Running"

### ISSUE THREAD

**Issue by tobycc1990** [jupyterlab/jupyterlab#9713]
![image](https://user-images.githubusercontent.com/9333992/106465750-5b72e480-64d5-11eb-9c64-fa7fbf71c017.png)
After I upgrade jupyterab to 3.x, run "python3 -m jupyterab"  start jupyterlab, opened in browser is a empty page with a line "A Jupyter Server Is Running" aboved. 
use"ps aux" view the process is running normally.

after "pip3 install jupyterab == 2.x" after backing down the jupyterlab version, the jupyterlab in browser is normal. 

I didn't find the relevant answers in Google, and "python3 -m jupyter lab --help" tried the relevant parameters for a long time, but it didn't work

**Comment by jtpio** [comment]
@tobycc1990 can you give the list of dependencies in your environment, with `pip list`?

Alternatively, have you tried installing it in a new virtual environment?

**Comment by tobycc1990** [comment]
> @tobycc1990 can you give the list of dependencies in your environment, with `pip list`?
> 
> Alternatively, have you tried installing it in a new virtual environment?

@jtpio I have already run in a docker image enviroment, pip list is as follows:

Package                Version
---------------------- ---------
absl-py                0.11.0
anyio                  2.0.2
argon2-cffi            20.1.0
astunparse             1.6.3
async-generator        1.10
attrs                  20.3.0
Babel                  2.9.0
backcall               0.2.0
bleach                 3.2.3
byted-tensorflow       2.4.0
bytedbackgrounds       0.0.3
byteddps               0.0.8
bytedenv               0.4.0
bytedmetrics           0.9.0
bytedservicediscovery  0.13.0
bytedtcc               1.1.5
cachetools             4.2.0
certifi                2020.12.5
cffi                   1.14.4
chardet                4.0.0
cloudpickle            1.6.0
decorator              4.4.2
defusedxml             0.6.0
distro-info            0.21
dnspython              2.1.0
entrypoints            0.3
flatbuffers            1.12
gast                   0.3.3
google-auth            1.24.0
google-auth-oauthlib   0.4.2
google-pasta           0.2.0
grpcio                 1.32.0
h5py                   2.10.0
horovod                0.21.0
idna                   2.10
importlib-metadata     3.3.0
iotop                  0.6
ipaddress              1.0.23
ipykernel              5.4.3
ipython                7.19.0
ipython-genutils       0.2.0
jedi                   0.18.0
Jinja2                 2.11.3
json5                  0.9.5
jsonschema             3.2.0
jupyter-client         6.1.11
jupyter-core           4.7.1
jupyter-server         1.2.3
jupyterlab             3.0.6
jupyterlab-pygments    0.1.2
jupyterlab-server      2.1.3
Keras-Preprocessing    1.1.2
Markdown               3.3.3
MarkupSafe             1.1.1
mistune                0.8.4
nbclassic              0.2.6
nbclient               0.5.1
nbconvert              6.0.7
nbformat               5.1.2
nest-asyncio           1.5.1
notebook               6.2.0
numpy                  1.19.4
oauthlib               3.1.0
opt-einsum             3.3.0
packaging              20.9
pandocfilters          1.4.3
parso                  0.8.1
pexpect                4.8.0
pickleshare            0.7.5
pip                    20.3.1
prometheus-client      0.9.0
prompt-toolkit         3.0.14
protobuf               3.14.0
psutil                 5.7.3
ptyprocess             0.7.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
pycurl                 7.43.0.2
Pygments               2.7.4
PyGObject              3.30.4
PyJWT                  1.7.1
pyparsing              2.4.7
pyrsistent             0.17.3
python-apt             1.8.4.2
python-dateutil        2.8.1
python-etcd            0.4.5
pytz                   2020.5
PyYAML                 5.3.1
pyzmq                  22.0.2
requests               2.25.1
requests-oauthlib      1.3.0
rsa                    4.6
schedule               0.6.0
Send2Trash             1.5.0
setuptools             51.0.0
six                    1.15.0
sniffio                1.2.0
tensorboard            2.4.0
tensorboard-plugin-wit 1.7.0
tensorflow-estimator   2.4.0
termcolor              1.1.0
terminado              0.9.2
testpath               0.4.4
tornado                6.1
traitlets              5.0.5
typing-extensions      3.7.4.3
unattended-upgrades    0.1
urllib3                1.26.2
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.36.1
wrapt                  1.12.1
zipp                   3.4.0

**Comment by jtpio** [comment]
Thanks @tobycc1990.

Would you be able to try with `jupyter_server==1.2.2`? It looks like `1.2.3` might have introduced a breaking change: https://github.com/jupyterlab/jupyterlab/pull/9706#issuecomment-770280369

**Comment by tobycc1990** [comment]
> Thanks @tobycc1990.
> 
> Would you be able to try with `jupyter_server==1.2.2`? It looks like `1.2.3` might have introduced a breaking change: [#9706 (comment)](https://github.com/jupyterlab/jupyterlab/pull/9706#issuecomment-770280369)

@jtpio thanks, it works in jupyter_server==1.2.2, but how to use it in 1.2.3? will it fixed in jupyter_server in the future, or should i change jupyter lab config for this breaking change

**Comment by jtpio** [comment]
`1.2.3` has been yanked on PyPI, so unless explicitly pinned on this version it should not be pulled.

Similarly, the release has been marked as broken on `conda-forge`: https://anaconda.org/conda-forge/jupyter_server/files?version=1.2.3

You might have to rebuild the docker image so it pulls `1.2.2`.
