### ISSUE TITLE
jupyterhub, jupyterlab 3.0.6 and mathjax

### ISSUE THREAD

**Issue by enriqueartal** [jupyterlab/jupyterlab#9718]
## Description

Problems rendering mathjax output (e.g., LaTeX in Markdown or output of `show` with sage kernel) when combining jupyterhub an jupyterlab 3.0.6

## Reproduce

1. Type $x$ in a markdown cell (resp. `show(x)` with kernel  sage) and evaluate
2. Running jupyter lab (3.0.6), one gets the expected mathjax output
3. Running jupyterhub wiht lab 3.0.5, one gets the expected mathjax output
4. Running jupyterhub wiht lab 3.0.6, the markdown cell keeps the expression (resp. no output).

## Expected behavior

What happened in cases 2, 3

## Context

- Operating System and version:Fedora 33
- Browser and version: Chrome 88.0.4324
- JupyterLab version: 3.0.6

<details><summary>Troubleshoot Output</summary>
<pre>

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>

</pre>
</details>

<details><summary>Browser Output</summary>
<pre>

</pre>
</details>

**Comment by Igorgro** [comment]
I had the same issue in 3.0.0, but it was fixed in 3.0.6. Could you please provide a screenshot from Chrome Dev Tools console? There is an error with MathJax loading.

**Comment by enriqueartal** [comment]
I tried to do this, but today it works with 3.0.5 and 3.0.6, I do not understand what happens. I close it but this intermitent behaviour has appeared other times.

**Comment by jasongrout** [comment]
Note that there was a fix for mathjax in jupyterlab_server, particularly for the case where you are running in jupyterhub and have a base_url: https://github.com/jupyterlab/jupyterlab_server/pull/153

It may be that you are hitting that bug, and updating jupyterlab_server is actually what fixed it.

**Comment by enriqueartal** [comment]
I am not sure since the failure is intermitent, but anyway I updated jupyterlab_server and built jupyter lab (I do not know if it was necessary) and it works. Thank you very much!
