### ISSUE TITLE
[File browser] Allow naming new files upon creation

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#9730]
When creating a new folder, the user is given the opportunity to name the new folder upon creation.

When creating a new file, it just creates `untitled.txt` and we need to use the rename dialog button.

**Creating folder:**

<img src="https://user-images.githubusercontent.com/2397974/106796720-0ad9c380-665c-11eb-9155-9a8d4beeb2fc.png" width=200px>

**Creating file:**

<img src="https://user-images.githubusercontent.com/2397974/106797175-918ea080-665c-11eb-8ad5-4336d4697fc9.png" width=200px>

**Comment by bollwyvl** [comment]
Please no more block-the-world dialogs :(

**Comment by jahn96** [comment]
If no one is working on it rn, I will give it a try :)

**Comment by telamonian** [comment]
@jahn96 It looks like you've already been scooped. In the last month there's already been two PRs that address this:

- #10181: When you create a new file, the node containing the name in the filebrowser will be editable and focused. This is pretty much what @SylvainCorlay initially suggest in this issue.

- #10043: Separately (and to me, at least, it seems really reedundant), if a file is not renamed upon creation, on first save a dialog box will pop to let you rename it automatically.

I honestly don't really think we need both of those. It feels a bit confusing to me. It would be nice to have some options in the settings to enable/disable each of two above rename-helper behaviors. And then maybe a followup discussion as to what the default value of each of those options should be.

In any cases, that means that this issue has already been resolved, possibly doubly so, so I'll close

**Comment by krassowski** [comment]
10043

**Comment by krassowski** [comment]
10043 addresses notebooks created from launcher rater than files created from browser though. I do agree a further discussion is needed, I was confused by this to.
