### ISSUE TITLE
Allow searching (and replacing) in multiple files

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#9732]
The current search and replace tool only applies to the current file.

Maybe we could allow searching in 

 - all open files
 - all files in the current directory

Note: this is somewhat related to the issue of searching current cell #2017 (changing the scope of the search tool).

... 

**Proposal:**

The search tool could be placed outside of the current tab, with optional form controls for changing the scope of the search and replace tool.

**Comment by Hoeze** [comment]
Please!
I always open Kate for search+replace functionality:
![image](https://user-images.githubusercontent.com/1200058/107070972-57500b00-67e4-11eb-819a-8afa98caf44c.png)
It would save me quite some time to do search+replace within Jupyterlab.

**Comment by Hoeze** [comment]
Please!
Search+replace in a single file would already be a huge improvement.
I always open Kate for search+replace functionality:
![image](https://user-images.githubusercontent.com/1200058/107070972-57500b00-67e4-11eb-819a-8afa98caf44c.png)
It would save me quite some time if Jupyterlab would have proper search+replace functionality.

**Comment by krassowski** [comment]
@Hoeze JupyterLab already has search and replace functionality for single files: https://stackoverflow.com/a/59700577/6646912
If there is an improvement you would like to see, or something does not work as expected it would be good to open a new issue (feel free to tag me).

**Comment by Hoeze** [comment]
OMG, I can't believe I never saw that arrow is clickable!! :facepalm: 
Thanks for the hint @krassowski :)

**Comment by jasongrout** [comment]
This issue is being tracked at #1145. Let's move discussion there.
