### ISSUE TITLE
Pluggable logging console

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#9735]
There are several logging consoles that were implemented for various purposes.

 - the one in core lab, for kernel logs etc, messages without a parent id...
 - the js errors console, which capture js errors https://github.com/QuantStack/jupyterlab-js-logs by @jtpio.
 - the ROS logging console from jupyterlab-ros https://github.com/RoboStack/jupyterlab-ros/tree/master/js/src/logconsole by @hbcarlos.

I think that it would be interesting for all of these logging consoles to simply be tabs in the same logging tool. Extension authors could add their own specialized logging tool, and that would help constraining a bit more the general application layout.

**Comment by jasongrout** [comment]
Or perhaps the messages can be in a single log output, but have filtering (like in the browser network connection log which lets you filter connections by type).

I'd probably want to avoid tabs specifically, because then you have this tabs inside of jlab tabs (inside of browser tabs), and that can get confusing. If we wanted to introduce a multipane ui in a single jlab activity, perhaps the ui pattern of the settings panel could be another way to do it.

**Comment by jtpio** [comment]
> Or perhaps the messages can be in a single log output, but have filtering (like in the browser network connection log which lets you filter connections by type).

+1

Pretty much came to the same observation after the first iteration on the `jupyterlab-js-logs` extension: https://github.com/QuantStack/jupyterlab-js-logs/issues/2

**Comment by SylvainCorlay** [comment]
I think it makes a lot of sense to have tabs with different sub-tabs of the logging console, because some of these warnings don't really make so much sense to mix.

For example, you are monitoring ROS logs in one tab, but want to keep the current logging console in another.

**Comment by fcollonval** [comment]
In IDE, it is quite common to have a bottom area that stack information. This allows to contain information in a specific area without mixing with the content of interest.

As those information even if they are logs can be of different types with different rendering, I would favor the approach of @SylvainCorlay. For example, we could add a `StackedPanel` at the bottom of the main area (see [Theia example](https://www.typefox.io/blog/flexible-window-layout-in-theia-ide)). So the general look and feel will be similar except that there will be no mixing between widget in the bottom area and in the main area.

Xref #5133

**Comment by fcollonval** [comment]
Fixed in #10201
