### ISSUE TITLE
Doubling clicking the new folder icon creates a folder without a name

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab#9750]
## Description
If you accidentally click twice in a row on the folder icon in the filebrowser then a folder will be created but it's name will not be populated. In order to get the names to show up you have to enter a folder and then come back.

![Peek 2021-02-05 13-59](https://user-images.githubusercontent.com/10111092/107077112-6752f500-67ba-11eb-9eb0-c393957ca02b.gif)

## Reproduce

1. Click on new folder icons multiple times in a row

## Expected behavior
The folder name shows up immediately

## Context

- Operating System and version: Ubuntu 20.04
- Browser and version: Firefox 84.0.2
- JupyterLab version: 3.0.7

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @ianhi.

I just tested on 3.2.1 with both Firefox and Chromium and it doesn't seem to be an issue anymore:

https://user-images.githubusercontent.com/591645/139737120-e938533b-8e25-41ec-afe2-df10ee61c96b.mp4

Closing as fixed, feel free to reopen if it's still an issue. Thanks!
