### ISSUE TITLE
Warning messages at launch since update to 3.0

### ISSUE THREAD

**Issue by Sid281216** [jupyterlab/jupyterlab#9752]
Hi I get all these messages when I run jupyterlab, unfortunately I really didnt found anything to try resolves them..I use a notebook_config file in .jupyter folder
Hope you can help ! 
You do a great job 

[I 2021-02-06 00:49:12.623 ServerApp] jupyterlab | extension was successfully linked.
[W 2021-02-06 00:49:12.623 NotebookApp] 'terminado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-06 00:49:12.623 NotebookApp] 'browser' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-06 00:49:12.623 NotebookApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-02-06 00:49:12.655 ServerApp] notebook_dir is deprecated, use root_dir
[W 2021-02-06 00:49:12.670 ServerApp] The 'min_open_files_limit' trait of a ServerApp instance expected an int, not the NoneType None.

**Comment by jasongrout** [comment]
See the changelog entry about the migration: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#jupyter-server (in particular, https://jupyter-server.readthedocs.io/en/stable/operators/migrate-from-nbserver.html)

**Comment by Sid281216** [comment]
Thanks it really helped !! 
I still get the message about the notebook_dir and just renamed it to root_dir in the conf file, fixed the issue.
By chance I founded a command to generate a completely new serverapp config file:  jupyter server --generate-config
So I just modified this new one and deleted  the notebook_config.

It still have one issue, extensions are loaded but it suggest to move them to jupyter server's extensions path, how I can do that ?

[I 2021-02-06 09:40:03.464 ServerApp] nbdime | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2021-02-06 09:40:03.464 ServerApp] nbdime | extension was successfully linked.
[I 2021-02-06 09:40:03.511 ServerApp] nbresuse | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2021-02-06 09:40:03.511 ServerApp] nbresuse | extension was successfully linked.
[I 2021-02-06 09:40:03.511 ServerApp] nbclassic | extension was successfully linked.
[I 2021-02-06 09:40:03.542 LabApp] JupyterLab extension loaded from c:\users\mehdi\appdata\local\programs\python\python39\lib\site-packages\jupyterlab
[I 2021-02-06 09:40:03.542 LabApp] JupyterLab application directory is C:\Users\mehdi\AppData\Local\Programs\Python\Python39\share\jupyter\lab
[I 2021-02-06 09:40:03.542 ServerApp] jupyterlab | extension was successfully loaded.
[I 2021-02-06 09:40:03.557 ServerApp] nbclassic | extension was successfully loaded.
[I 2021-02-06 09:40:03.620 ServerApp] nbdime | extension was successfully loaded.
[I 2021-02-06 09:40:03.620 ServerApp] nbresuse | extension was successfully loaded.

**Comment by Sid281216** [comment]
I just uninstalled nbdime and nbresuse, not primordial after all 

Thanks for your help

**Comment by Cbarrow98** [comment]
Hello Sid,

Can you run me through exactly what you did please. Ever since I updated anaconda --all I have been getting the following message below when I open Jupyter notebooks and doesn't proceed to go to my notebooks and just keeps saying waiting for localhost?

Here's my issue:

[W 2021-05-12 16:41:48.674 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-05-12 16:41:48.674 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.

**Comment by Sid281216** [comment]
Hi sorry I changed for vscode since January, but as I can read my self, I executed this "pip uninstall nbdime nbresuse" on cmd

**Comment by ariel-co** [comment]
The warning message about `min_open_files_limit` being None also happens in a brand new installation, created according to the ![“Reporting an issue” page](https://jupyterlab.readthedocs.io/en/latest/getting_started/issue.html):

```
[W 2021-06-01 23:27:53.996 ServerApp] The 'min_open_files_limit' trait of a ServerApp instance expected an int, not the NoneType None.
[D 2021-06-01 23:27:53.997 ServerApp] Config changed: {'ExtensionApp': {'log_level': 'DEBUG'}, 'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'nbclassic': True}>}}
[D 2021-06-01 23:27:53.998 ServerApp] Ignoring min_open_files_limit because the limit cannot be adjusted (for example, on Windows)
```

**Comment by XBH5** [comment]
Hi, I had the same problem as you and I would like to know how you solved it.

**Comment by XBH5** [comment]
> Hello Sid,
> 
> Can you run me through exactly what you did please. Ever since I updated anaconda --all I have been getting the following message below when I open Jupyter notebooks and doesn't proceed to go to my notebooks and just keeps saying waiting for localhost?
> 
> Here's my issue:
> 
> [W 2021-05-12 16:41:48.674 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2021-05-12 16:41:48.674 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.

Hi, I had the same problem as you and I would like to know how you solved it.
