### ISSUE TITLE
Edit on GitHub button does not work in documentation (stable)

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#9755]
When on https://jupyterlab.readthedocs.io/en/stable/# the `Edit on GitHub` button goes to `https://github.com/jupyterlab/jupyterlab/blob/origin/3.x/docs/source/index.rst` which does not exist; the origin part is spurrious, the correct URL would be: `https://github.com/jupyterlab/jupyterlab/blob/3.x/docs/source/index.rst`.

Probably trivial to fix, but opening the issue anyways, i.e. how could we make sure that it works in the future. Would it be worth to set up an automated check for dead links in documentation?

**Comment by krassowski** [comment]
the `latest` tag works ok. It seems that the url is configured in RTD because the version in `conf.py` is set to master on `3.x`:

https://github.com/jupyterlab/jupyterlab/blob/dbcfeef5253e61502252a06222acb82fe79532d2/docs/source/conf.py#L174

So it must be using the `github_url` from `meta` instead:

https://github.com/jupyterlab/jupyterlab/blob/d8d6f9147b78dbacd3f77940aa54a50873891711/docs/source/_templates/breadcrumbs.html#L14-L19

but this is not appearing in the code anywhere else so I assume it is somewhat set by RTD.

**Comment by jasongrout** [comment]
Is that what these lines are doing?

https://github.com/jupyterlab/jupyterlab/blob/ae9300a4eaf09fa42f17ca56c7409104721649d6/docs/source/conf.py#L64-L78

**Comment by krassowski** [comment]
I don't think so. It seems to be related to https://github.com/readthedocs/readthedocs.org/issues/1637

**Comment by whurd-redcanary** [comment]
> I don't think so. It seems to be related to [readthedocs/readthedocs.org#1637](https://github.com/readthedocs/readthedocs.org/issues/1637)

It looks as if you need to update the version of sphinx running https://jupyterlab.readthedocs.io/ ? 

https://github.com/sfstoolbox/sfs-python/pull/48

**Comment by krassowski** [comment]
I just confirmed that the workaround in #11149 fixed both the links on `stable` and `latest` versions (`latest` stopped working recently), closing.
