### ISSUE TITLE
Cannot "trust" a notebook with blank cells

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9765]
## Description

In https://discourse.jupyter.org/t/jupyterlab-not-remembering-trust-for-notebooks/7869, a user told about how they had difficult persisting trust state in a new notebook. I tried trusting a new notebook, and could not get JLab to do so.

## Reproduce

In JupyterLab 3.0.7 in a clean environment (but also in latest JLab 2 or JLab 1, from my experiments):

1. Create a new notebook and evaluate a few cells and have a few blank cells
2. Check the trust status in the status bar. For me, it says for example "Notebook not trusted: 3 cells of 4 cells trusted", where I have 4 cells and one of them is blank.
3. Run the "Trust notebook" command from the command palette, and see that the trust status bar icon still says the same thing.
4. Close and shutdown the notebook, then open it again. None of the cells will be trusted (which IIRC is expected behavior if at least one cell was untrusted when saved)
5. Run all the cells and delete the empty cells. Then the trusted status bar icon shows the notebook is trusted.

## Expected behavior

Running all the cells in a notebook should trust all the cells (and thus trust the notebook as a whole). Probably blank cells (both input and output) should be considered trusted by default.

## Context

- Operating System and version: macOS Catalina
- Browser and version: Firefox 85
- JupyterLab version: 3.0.7

It does not look like there are any relevant errors in the js console or in the server log.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterlab-not-remembering-trust-for-notebooks/7869/2

**Comment by echarles** [comment]
> In JupyterLab 3.0.7 in a clean environment (but also in latest JLab 2 or JLab 1, from my experiments):
> Create a new notebook and evaluate a few cells and have a few blank cells
> Check the trust status in the status bar. For me, it says for example "Notebook not trusted: 3 cells of 4 cells trusted", where I have 4 cells and one of them is blank.
> Run the "Trust notebook" command from the command palette, and see that the trust status bar icon still says the same thing.
> Close and shutdown the notebook, then open it again. None of the cells will be trusted (which IIRC is expected behavior if at least one cell was untrusted when saved)
> Run all the cells and delete the empty cells. Then the trusted status bar icon shows the notebook is trusted.

Tried this scenario on latest 3.1, and can not reproduce it. The trust is showing fine when closing and reopening.

However, the trusted metadata is not shown in the notebook metadata panel

<img width="481" alt="Screenshot 2021-10-21 at 08 13 05" src="https://user-images.githubusercontent.com/226720/138221551-ad46c5c5-cf9e-444a-ba0f-db3f8b3bf6b6.png">

> I am not sure if this is this issue getting worse/another variant/unrelated, but I am seeing the trust issue across multiple environments with a fresh install of lab. The easiest reproducer I could think of was using HTML to display a script, but I have seen this with other mime renders.

@mlucool I have followed your screencast. Are you saying that the javascript should not be executed if the notebook is not trusted?

**Comment by utkonos** [comment]
That would be an excellent addition to the documentation for Jupyter.

**Comment by krassowski** [comment]
It is documented here https://jupyter-notebook.readthedocs.io/en/stable/security.html#our-security-model; if you would like to contribute by adding a relevant fragment to the JupyterLab documentation, I will be happy to review the pul request.

**Comment by utkonos** [comment]
I'd be happy to contribute. Also, I had searched in the JupyterLab documentation rather than the Jupyter Notebook documentation for the keyword "trust".

https://jupyterlab.readthedocs.io/en/stable/search.html?q=trust&check_keywords=yes&area=default
https://jupyter-notebook.readthedocs.io/en/stable/search.html?q=trust&check_keywords=yes&area=default

I will work on a contribution over the weekend and make a PR.
