### ISSUE TITLE
Check file changes based on content instead of the last_modified metadata

### ISSUE THREAD

**Issue by skukhtichev** [jupyterlab/jupyterlab#9769]
### Problem
JupyterLab mechanism to detect a file changes is based on last_modified parameter set in the metadata: https://github.com/jupyterlab/jupyterlab/blob/b4db7f03d2ad0b91a9c8c252c56ae5e4a9408fbb/packages/docregistry/src/context.ts#L644-L649. 
If the file last_modified parameter was changed without changing the content then JupyterLab shows the following message
![image (11)](https://user-images.githubusercontent.com/12250108/107552472-dc1b9a00-6bd3-11eb-9c8c-3cf7b274e0c1.png)
The issue happens when sync tools are used that updates files last modified timestamp.

### Proposed Solution
Using content based check mechanism (e.g. hash) will prevent showing the dialog when the last modified timestamp changed without changing a file content

**Comment by telamonian** [comment]
👍 I like this, definitely worth trying out

There's several different ways you could implement this, and you could do the actual hash in either the frontend or in the backend jupyter_server.

**Comment by robinovitch61** [comment]
I would be interested in taking a crack at this unless you're particularly gung-ho @skukhtichev

**Comment by blink1073** [comment]
xref https://github.com/jupyter-server/jupyter_server/issues/409

**Comment by vidartf** [comment]
xref https://github.com/jupyterlab/jupyterlab/issues/9777

**Comment by vidartf** [comment]
> The issue happens when sync tools are used that updates files last modified timestamp.

It seems weird that the sync tool updates the last modified timestamp even if no change is made. Do you know why this happens, and if it is possible to avoid it? If possible, that would be a better fix, rather than building some special case workaround into the frontend.

**Comment by fcollonval** [comment]
Closing as fixed by https://github.com/jupyterlab/jupyterlab/pull/15577
