### ISSUE TITLE
Disable "Launch Classic Notebook"

### ISSUE THREAD

**Issue by mwakaba2** [jupyterlab/jupyterlab#9770]
Jupyterlab version: 2.2.9
Jupyter_server version: 1.1.1

Hi, is it possible to disable the "Launch Classic Notebook" option? We have a Jupyterlab application with a jupyter server backend, and we no longer support the classic interface. The option still shows up and is confusing to the user as it shows a 404 page (/tree). 

<img width="283" alt="Screen Shot 2021-02-10 at 12 46 08 PM" src="https://user-images.githubusercontent.com/3497137/107563364-33067c80-6b9e-11eb-82b3-2ab5648d7e3f.png">

**Comment by jasongrout** [comment]
The code that adds that is in the help extension. Search https://github.com/jupyterlab/jupyterlab/blob/dd73fa37ef5a4daed6a900ee729cab53f84c7141/packages/help-extension/src/index.tsx for "launch" to see where the command is added to the palette and the menu.

Two of the simplest ways forward are:

1. Write your own help extension that replaces the built-in help extension and omits that command and menu item
2. Contribute a PR to JupyterLab that moves adding that menu item and command to a new plugin in the help extension, which you can then disable in your configuration.

**Comment by mwakaba2** [comment]
@jasongrout Thanks for the suggestions! I'll look into it.
