### ISSUE TITLE
Cull idle kernels even when the browser tab is open (even possible?)

### ISSUE THREAD

**Issue by ma-sadeghi** [jupyterlab/jupyterlab#9778]
I wonder if there's a way to cull idle kernels even when the browser tab is open. I'm not sure if that's even possible based on how it's declared that a kernel is idle.

**Comment by mikepqr** [comment]
Apparently not. See #9379.

**Comment by jtpio** [comment]
@ma-sadeghi it might be possible to use the `MappingKernelManager.cull_connected` option to cull an idle kernel even if there is a connection (browser tab open)

https://jupyter-server.readthedocs.io/en/latest/other/full-config.html?

**Comment by mikepqr** [comment]
@jtpio correct, that will work. I misunderstood @ma-sadeghi's question.

So if you start with something like this:

```
jupyter lab \
    --log-level=DEBUG \
    --MappingKernelManager.cull_idle_timeout=10 \
    --MappingKernelManager.cull_interval=10 \
    --MappingKernelManager.cull_connected=True
```

then idle kernels (kernels that have not done work in the past 10-20 seconds in this case) will be shut down whether or not a notebook/console with a connection to that terminal is open in a browser. 

#9379 refers to the fact that, as long as the browser is open, the server process does not become idle.

**Comment by jtpio** [comment]
Thanks @mikepqr.

Then let's close the issue as answered.

The `--MappingKernelManager.cull_connected` setting is more related to Jupyter Server than JupyterLab, but don't hesitate to comment here or open a new issue if you think there should be a mention or reference link in the documentation.
