### ISSUE TITLE
Login page in jupyterlab 3.x missing css (2.x version still working)

### ISSUE THREAD

**Issue by AnhQuanTran** [jupyterlab/jupyterlab#9791]
## Reproduce

1. Start docker container with base image is ubuntu:18.04
2. Run apt install -y python3-pip 
3. Run pip3 install jupyterlab==3.0.7 or 3.0.6
4. Run jupyter serverextension enable --py jupyterlab --sys-prefix
5. Run jupyter server --generate-config
6. Run jupyter notebook password
7. Input some value
8. Run jupyter lab --allow-root --ip 0.0.0.0 --port=8888 --no-browser
9. Access http://localhost:8889/lab on browser
10. See

![image](https://user-images.githubusercontent.com/21956433/107861833-1195e100-6e7b-11eb-8887-4b24dfc92fe7.png)

## Expected behavior
But if i try with version 2.2.9, it's still working

![image](https://user-images.githubusercontent.com/21956433/107861943-d47e1e80-6e7b-11eb-9857-2afa3632a2cf.png)

## Context

- Operating System and version: ubuntu 18.04
- Browser and version: Microsoft Edge Version 88.0.705.63 (Official build) (64-bit)
- JupyterLab version: 3.0.7

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @AnhQuanTran.

This should normally be fixed with the latest version of `jupyter_server`.

Would you mind trying again with a newer version? Or update it with `pip install -U jupyter_server`?
