### ISSUE TITLE
"Editor" shows up instead of "Create Console for Editor" in tab menu for files

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#9793]
## Description

Localization work changed "Create Console for Editor" to "Editor"

## Reproduce

1. Open new file
2. Open context menu over the tab
3. See "Editor" instead of "Create Console for Editor"

![Screenshot from 2021-02-13 22-25-37](https://user-images.githubusercontent.com/5832902/107863305-3bcfaa80-6e4b-11eb-8ca8-3ed0d318ad96.png)

## Expected behavior

Should show "Create Console for Editor"

## Context

- JupyterLab version: 3.0.7

**Comment by krassowski** [comment]
Relevant code:

https://github.com/jupyterlab/jupyterlab/blob/b4db7f03d2ad0b91a9c8c252c56ae5e4a9408fbb/packages/fileeditor-extension/src/commands.ts#L1198-L1202

https://github.com/jupyterlab/jupyterlab/blob/d0d202690f3b6ba280b7148c4026e8c5656638f4/packages/mainmenu-extension/src/index.ts#L365-L375

**Comment by jasongrout** [comment]
@meeseeksdev please backport to 3.0.x
