### ISSUE TITLE
Jupyterlab 3.0.7 build is not possible.

### ISSUE THREAD

**Issue by kwon14** [jupyterlab/jupyterlab#9803]
Recently, I installed a new extension and tested it, and the Jupyterlab build is not working.

I am a mac os user, and I am using Jupyterlab by building with dockerfile.

A part of the dockerfile and an error code are attached, 
so please check this problem.!!
Thank you!!

Here is my part of dockerfile..
----------------------------------
RUN jupyter contrib nbextension install --user && \
    jupyter nbextension enable hide_input_all/main --sys-prefix && \
    jupyter nbextension enable freeze/main --sys-prefix && \
    jupyter nbextension enable highlighter/highlighter --sys-prefix && \
    jupyter nbextension enable execute_time/ExecuteTime --sys-prefix && \
    jupyter nbextension disable nbexamples/submit-example-button && \
    #lsp install
    jupyter labextension install @krassowski/jupyterlab-lsp@3.4.0 --no-build && \
    #toc install
    jupyter labextension install @jupyterlab/toc --no-build && \
    jupyter lab build --dev-build=False && \
    jupyter lab clean -y && \
    rm -rf $CONDA_DIR/share/jupyter/lab/staging && \
    rm -rf /home/$NB_USER/.cache/yarn

Here is "error code"
-----------------------------------------------
[LabBuildApp] JupyterLab 3.0.7
[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] WARNING | The extension "@jupyterlab/git" is outdated.

[LabBuildApp] WARNING | The extension "nbdime-jupyterlab" is outdated.

Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-03ryamgu.log
The command '/bin/bash -o pipefail -c jupyter contrib nbextension install --user &&     jupyter nbextension enable hide_input_all/main --sys-prefix &&     jupyter nbextension enable freeze/main --sys-prefix &&     jupyter nbextension enable highlighter/highlighter --sys-prefix &&     jupyter nbextension enable execute_time/ExecuteTime --sys-prefix &&     jupyter nbextension disable nbexamples/submit-example-button &&     jupyter labextension install @krassowski/jupyterlab-lsp@3.4.0 --no-build &&     jupyter labextension install @jupyterlab/toc --no-build &&     jupyter lab build --dev-build=False &&     jupyter lab clean -y &&     rm -rf $CONDA_DIR/share/jupyter/lab/staging &&     rm -rf /home/$NB_USER/.cache/yarn' returned a non-zero code: 1

**Comment by krassowski** [comment]
> See the log file for details: /tmp/jupyterlab-debug-03ryamgu.log

The contents of this log file would help.

```
#lsp install
jupyter labextension install @krassowski/jupyterlab-lsp@3.4.0 --no-build &&
```

This is not optimal and currently [might cause problems](https://github.com/krassowski/jupyterlab-lsp/issues/518). Please install this extension using pip or conda [as described in the README](https://github.com/krassowski/jupyterlab-lsp#installation) rather than using `jupyter labextension install`. It will also reduce the build times for you too.

**Comment by telamonian** [comment]
>  jupyter labextension install @jupyterlab/toc --no-build

you definitely need to remove this from your install command. `toc` is now part of jlab core, the external `@jupyterlab/toc` should only be used with jlab 2.x
