### ISSUE TITLE
Publishing an npm prebuilt extension package that is not a source extension

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9807]
### Problem

In https://github.com/krassowski/jupyterlab-lsp/issues/518#issuecomment-779892803, @krassowski asks if it is possible to publish the npm package that is used to create a prebuilt extension, but to have that published package *not* be a source extension. You might want to do this if you only want to support a prebuilt extension, but want to provide the npm package for others to build on (for example, you may export tokens or UI components, etc., that others might want to import and use).

### Proposed Solution

I gave some ideas for how to do this in [that issue](https://github.com/krassowski/jupyterlab-lsp/issues/518#issuecomment-780088901), copied here for completeness:

Here are three ideas for publishing an npm package that is not extension, while still being able to build a prebuilt extension from it. First, remove the `jupyterlab-extension` keyword from the npm package to avoid it being listed in the extension manager.
1. Remove the `jupyterlab.extension` and `jupyterlab.mimeExtension` keys from the package.json before publishing to npm. IIRC, those are the keys JupyterLab uses to determine if a package is really an extension.
2. Remove those two package.json keys permanently, and just add them back in when prebuilding an extension.
3. Perhaps `jupyter labextension build` should have some command line arguments to give those two extension entry points, which would override what it finds in the package.json, i.e., something you could use like `jupyter labextension build --extension ./lib/plugin.js --mimeExtension ./lib/mime`. In this case, like in the option above, we would permanently remove the keys from package.json. This is probably the cleanest solution.

**Comment by krassowski** [comment]
Another very useful mitigation would be being able to communicate a message to users prior to installation of the source package, e.g. "Source packages are no longer supported please do ...". It could use a similar mechanism as is already used for server companion:

```js
{"jupyterlab": {
  "extension": true,
  "discovery": {
    "server": {
      "base": {"name": "jupyterlab_lsp"},
      "managers": ["pip", "conda"]
  },
  // display an inputDialog telling user that "This extension is now available
  // as a federated extension from pip and/or conda, and authors of this
  // extension recommend to install it that way instead".
  // There could be two buttons: [Install anyways] and [See the instruction on extension website]
  "recommendFederated": true,
  // in addition I think that it would be very useful to:
  // allow to communicate to users that the package is no longer maintained,
  // even though the semver ranges match the installed jupyterlab version
  // and cause the extension to be displed in the extension manager
  "deprecated": true
}}
```

I have no strong feeling about whether there should be an action attached to the deprecated field and whether developers should be allowed to specify a custom message (e.g. instead of using jupyterlab-spreadsheet-editor please install jupyterlab-spreadsheet-editor-2)

**Comment by krassowski** [comment]
Forgot to mention: this approach of communication over removal from registry would be particularly useful because (right now) the federated extensions are not searchable from the extension manager.
