### ISSUE TITLE
Npm security vulnerability in @jupyterlab/rendermime dependency

### ISSUE THREAD

**Issue by mwouts** [jupyterlab/jupyterlab#9808]
Hello all,

Recently we have committed the `yarn.lock` file for the jupyterlab extension in the Jupytext project (https://github.com/mwouts/jupytext/pull/741).

Because of this I have received a security alert from GH's _Dependabot_, not unsimilar to https://github.com/jupyterlab/jupyterlab/issues/6479. 

The advice is to upgrade `marked` to version `2.0.0` due to https://github.com/markedjs/marked/issues/1927

But apparently this can't be done automatically because of:
```
@jupyterlab/application@3.0.0 requires marked@^1.1.1 via a transitive dependency on @jupyterlab/rendermime@3.0.0
@jupyterlab/notebook@3.0.0 requires marked@^1.1.1 via a transitive dependency on @jupyterlab/rendermime@3.0.0
```

Is that something that is easy to fix?

Thanks

_____________
![image](https://user-images.githubusercontent.com/29915202/108137515-4e9ce600-70bc-11eb-9cce-9551304b4895.png)

**Comment by telamonian** [comment]
> Is that something that is easy to fix?

It appears that it was (assuming the CI passes). There's a PR at #9809

**Comment by mwouts** [comment]
Well done! Thank you @telamonian !
