### ISSUE TITLE
Inline whiteboard

### ISSUE THREAD

**Issue by RR11WK** [jupyterlab/jupyterlab#9815]
### Problem

While JupyterLab is great for visualizations, markup and code. We'd like to introduce another dimension, whiteboarding. Providing the ability to draw things!

### Proposed Solution

There looks to be a few options around the implementation here. I think this is still TBD.

### Additional context

There have been quite a few duplicate issues raised in the past,
 https://github.com/jupyterlab/jupyterlab/issues/9194 & https://github.com/jupyter/notebook/issues/1999

**Comment by jasongrout** [comment]
Thanks! To clarify: is this different than #9194? If it is the same proposal, we usually consolidate discussion on one issue (typically the earlier issue, which would be #9194 in this case, and close duplicate issues). If this proposal is different, can you elaborate on how it is different?

**Comment by RR11WK** [comment]
Hello, Okay i'll close this one and use #9194
