### ISSUE TITLE
[Question]: How to list running servers in JupyterLab 3? 

### ISSUE THREAD

**Issue by dclong** [jupyterlab/jupyterlab#9823]
### Problem

I would like to get information of running servers in JupyterLab 3. 
Before JupyterLab 3 in which notebook instead of jupyter_server was used, we can use the following code to get running servers. 
```
#!/usr/bin/env python3
import json
from notebook import notebookapp

servers = list(notebookapp.list_running_servers())
print(json.dumps(servers, indent=4))
```
I tried to change notebook to jupyter_server and notebookapp to serverapp (see the code below), but it didn't work. 
```
import json
from jupyter_server import serverapp

servers = list(serverapp.list_running_servers())
print(json.dumps(servers, indent=4))
```
### Proposed Solution

Add documentation on how to get information of running servers in JupyterLab 3 in which jupyter_server is leveraged.

**Comment by afshin** [comment]
Hi @dclong!

This should be able to accomplish what you want:

```python
import json
from jupyter_server import serverapp
servers = list(serverapp.list_running_servers())
print(json.dumps(servers, indent=4))
```

**Comment by dclong** [comment]
I tried again and can confirm that it works in JupyterLab. However, it doesn't work in JupyterHub. Not sure whether it's becuase JupyterHub doesn't fully support jupyter_server yet. I will create an issue in JupyterHub.
