### ISSUE TITLE
Server Connection error-A connection to the Jupyter server could not be established. Jupyterlab will continue trying to connect. Check your network connection or Jupyter server configuration.

### ISSUE THREAD

**Issue by UNS-AI** [jupyterlab/jupyterlab#9827]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jasongrout** [comment]
Please fill out the [bug report issue template](https://raw.githubusercontent.com/jupyterlab/jupyterlab/master/.github/ISSUE_TEMPLATE/bug_report.md) above with the information it requests about your version of JupyterLab, browser, OS, etc., as well as instructions to reproduce this.

Also, I would suggest going through the troubleshooting/diagnosis guide in the documentation at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to try to narrow down the problem.

**Comment by UNS-AI** [comment]
Hi,
   Thank you jasongrout. I am new in Jupyterlab. I encountered this problem when I tried to rename the title of Jupyter notebook, run the cells etc- within any new environments created by me.  But works fine within base(root) environment. On checking it is found that the tornado 6.0.4 is in base(root) environment where as tornado 6.1 is in any new environment I create. 
Using cmd.exe (with- pip install --upgrade tornado==6.0.4) I have succeeded in changing the version of tornado to 6.0.4- from within a new environment in Anaconda navigator. I confirmed the change to version 6.0.4 by checking the folder - F:/anacond/envs/newenv/lib/site-packages/tornado-6.0.4. But on searching, using search box under environments tab of Navigator, tornado 6.1 shows as before. Also the problem remains same as it was before when running cells, renaming notebook title etc. I repeated the process by creating new environments. Reinstalled Anaconda as a whole. But issue remains as it is.
I tried to proceed with base(root) environment. But it has another issue. It lacks Keras. I tried to import Keras to it and ended up with a long list of errors-conflicts of packages.
OS: Windows 7 ultimate-64 bit
Browser: Firefox 85.0.2
Jupyterlab: 2.2.6

Thank you
[AI_screenshots.docx](https://github.com/jupyterlab/jupyterlab/files/6009085/AI_screenshots.docx)

**Comment by UNS-AI** [comment]
I tested with classic Jupyter Notebook (by accessing from help menu of Jupyter lab). The problem repeats. Please see the screen shots uploaded along with last comment. 1st, 2nd & 4th screen shots -same in Jupyter lab & classic Jupyter Notebook with a new environment created by me. 3rd one is in Jupyter lab  with base(root) environment due to the absence of Keras. 
Some body please help.

**Comment by UNS-AI** [comment]
Problem solved. I changed my computer. Now working fine. It might be an OS related issue. Previous computer has OS windows 7 ultimate & new one has OS windows 8.
Jasongrouts guidance also helped. Thank you

**Comment by jasongrout** [comment]
Thanks for following up, and I'm glad it's working now!
