### ISSUE TITLE
Current tab doesn't receive dock panel focus

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#983]
See screencast. In this example, the terminal tab is top of the R panel, and when its tab is clicked on, it doesn't get focused. If that same tab is in the back of another, it would get focused.

![tabbug](https://cloud.githubusercontent.com/assets/27600/18884665/5feca7c0-84b6-11e6-9cbb-74d1db6dd91e.gif)

**Comment by ellisonbg** [comment]
Same problem exists for all widgets in the dock panel

**Comment by sccolbert** [comment]
I have to fix Phosphor for this. c.f. https://github.com/phosphorjs/phosphor/issues/104

**Comment by sccolbert** [comment]
Are you willing to update JLab's Phosphor before the talk?

**Comment by ellisonbg** [comment]
Mmm, probably not, worried there would be style changes. Also, this one isn't as big of a deal...

**Comment by sccolbert** [comment]
Ok. Then this will be fixed when the updated DockPanel is released in the next version of Phosphor.

**Comment by afshin** [comment]
This problem appears to be resolved now.
