### ISSUE TITLE
JupyterLab drag-and-drop copy doesn't work for folders

### ISSUE THREAD

**Issue by adammclaurin** [jupyterlab/jupyterlab#9838]
I'm trying to drag-and-drop both files and folders from the Windows File Explorer to the JupyterLab (v2.2.8) file browser pane. It works fine for files, but doesn't for folders. See screenshot below. The response from the UI suggests that it should work - it just doesn't do anything. I'm trying from Chrome on Windows 10. JupyterLab is being hosted by JupyterHub 1.0 running on Linux. 

![jupyterlab 2 2 8 folder drop](https://user-images.githubusercontent.com/66390593/108629337-5dbdc400-742d-11eb-895c-db24991ef7b6.png)

**Comment by jasongrout** [comment]
Thanks for opening this. Indeed, uploading folders does not work. I'm not sure if we can know if you are dropping a folder or file before you drop it, but at very least we should display an error message afterwards indicating that it is not supported. Of course, even better would be figuring out how to support it.

**Comment by jasongrout** [comment]
For whoever wants to take this up, it does look fairly straightforward to selectively enable the drop based on examining what is being dragged: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Drag_operations#droptargets

**Comment by jasongrout** [comment]
Relevant parts of the JupyterLab codebase are below, for whoever wants to work on this:

https://github.com/jupyterlab/jupyterlab/blob/41e2d54a0550812b8ab28be5fd517a7f48aea515/packages/filebrowser/src/listing.ts#L1082-L1094

https://github.com/jupyterlab/jupyterlab/blob/41e2d54a0550812b8ab28be5fd517a7f48aea515/packages/filebrowser/src/listing.ts#L666-L678

**Comment by jasongrout** [comment]
Adding the good first issue label - I think it would be pretty straightforward to disable the drop indicator when dragging a file by selectively calling `.preventDefault` only when we can handle it (i.e., files but not folders).

More complicated is actually supporting a folder drop, which probably is more advanced than a good first issue.

**Comment by adammclaurin** [comment]
Thanks @jasongrout. If it helps, this is how the MinIO Browser does it, which is essentially the user experience I have in mind:
https://github.com/minio/minio/blob/master/browser/app/js/uploads/Dropzone.js

**Comment by dharmaquark** [comment]
going to take a pass at this one, if it's unclaimed!

**Comment by yash112-lang** [comment]
Hello, @adammclaurin, is this issue is still open. I am new to open source & want to contribute.

**Comment by Nazeeh21** [comment]
I would like to work on this issue!

**Comment by murari2401** [comment]
I am interested to work on this issue .. Can someone assign me with this

**Comment by blink1073** [comment]
Hi @murari2401, @Nazeeh21 has already been assigned the issue and has a work in progress pull request in #10596
