### ISSUE TITLE
possible extension changes in 3.x (from 2.x) break themes with bundled fonts

### ISSUE THREAD

**Issue by myyc** [jupyterlab/jupyterlab#9839]
Apologies in advance if this is not strictly a jupyterlab issue but something broke on 3.0 and I'm trying to figure out how to fix it. I've been trying to port this to jupyterlab 3.0: https://github.com/yeebc/jupyterlab-neon-theme.

Building it throws this error: `Error: Automatic publicPath is not supported in this browser`, which seems to be a Webpack error. I managed to debug it enough to figure out that it fails because of the `fonts.css` file which includes some `font-face` definitions, which in turn refer to some fonts that are bundled in the theme (`style/fonts/`).

The theme used to compile under jupyterlab 2.1 and I can't seem to find any info on how to properly include fonts in a Jupyterlab extension/theme – the new cookiecutter and the guide don't seem to refer to a way to do it.

Any clue?

I'm using the latest everything (jupyterlab 3.0.8, etc. etc.) as I'm working on a fresh install that's 2 hours old.

**Comment by bollwyvl** [comment]
Yep, fonts aren't fun. Here's an earlier report on the theme cookiecutter:

https://github.com/jupyterlab/theme-cookiecutter/issues/20

Mentioned there, but for those that find this:

> ```bash
>  jlpm add --dev base64-inline-loader
>  ```
>
> And then:
> ```css
> @font-face {
>    font-family: 'Whatever';
>    src: url('!!base64-inline-loader!./fonts/Whatever.ttf') format('truetype');
>    font-weight: 400;
>    font-style: normal;
> }
> ```

**Comment by myyc** [comment]
ah magic, it works. thanks!

**Comment by jasongrout** [comment]
Thanks for posting the work-around, Nick. Putting as 3.1 since we should still solve the underlying issue.

**Comment by jasongrout** [comment]
FYI, switching to the automatic public path was #9062. We may need to reconsider that PR and possibly revert if we can't find a good way to address this problem.

**Comment by jasongrout** [comment]
I updated the description in #9062 to give a bit more context about the change and background behind the change.

**Comment by rfox12** [comment]
Based on Jason's work, where would one put static files (images, fonts) a pre-built extension cookie cutter layout?  Or is the guidance to still use base64-inline-loader?  Appreciate any help.

**Comment by JasonWeill** [comment]
We no longer use the cookiecutter, and we now package extensions using webpack or a similar package. Closing this out; please open new issues for extension issues in 4.x. Thanks.
