### ISSUE TITLE
Extensions cannot be installed from pip command

### ISSUE THREAD

**Issue by humbledude** [jupyterlab/jupyterlab#9842]
## Description
I cannot install extensions by `pip install` command.
I think my environment could be complex,
- using `PYTHONPATH` for storing 3rd party libs on user path
- using `JUPYTERLAB_DIR` for storing jupyterlab build (with extensions) on user path

Because I use jupyterhub + k8s, and I wanted to keep user's environment to PV.

I thought `pip install EXTENSION` should install tarball extensions to `$JUPYTERLAB_DIR/extensions` but it does not.
Could anyone help me?

The old `jupyter labextension install xx` seems work fine.

## Reproduce

1. `pip install jupyterlab_vim` (or any extension)
2. pip install is successful but nothing happend on jupyterlab

## Context

- Operating System and version: centos 7
- Browser and version: chrome 88.0.4324.150
- JupyterLab version: 3.0.7

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /opt/pyenv/versions/3.6.8/bin
        /opt/pyenv/libexec
        /opt/pyenv/plugins/python-build/bin
        /opt/pyenv/plugins/pyenv-virtualenv/bin
        /opt/pyenv/plugins/pyenv-update/bin
        /opt/pyenv/plugins/pyenv-installer/bin
        /opt/pyenv/plugins/pyenv-doctor/bin
        /opt/pyenv/plugins/python-build/bin
        /opt/pyenv/plugins/pyenv-virtualenv/bin
        /opt/pyenv/plugins/pyenv-update/bin
        /opt/pyenv/plugins/pyenv-installer/bin
        /opt/pyenv/plugins/pyenv-doctor/bin
        /opt/pyenv/plugins/pyenv-virtualenv/shims
        /opt/pyenv/shims
        /opt/hadoop-client-env-v2/target/jdk/jdk8u181-b13/bin
        hadoop-client-env-path-start
        /opt/hadoop-client-env-v2/target/Doopey/hadoop-2.6.0-cdh5.14.2/share/hadoop/mapreduce/bin
        /opt/hadoop-client-env-v2/target/Doopey/hive-1.1.0-cdh5.14.2/bin
        /bin
        /opt/hadoop-client-env-v2/target/Doopey/spark-2.3.1-bin-without-hadoop/bin
        /bin
        /opt/hadoop-client-env-v2/target/Doopey/zookeeper-3.4.5-cdh5.14.2/bin
        hadoop-client-env-path-end
        /opt/pyenv/shims
        /opt/pyenv/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/lib/java/jdk8u232-b09/bin
        /home/app/.local/bin
        /home/app/bin

sys.path:
        /opt/pyenv/versions/3.6.8/bin
        /home/app/python_libs
        /opt/pyenv/versions/3.6.8/lib/python36.zip
        /opt/pyenv/versions/3.6.8/lib/python3.6
        /opt/pyenv/versions/3.6.8/lib/python3.6/lib-dynload
        /home/app/.local/lib/python3.6/site-packages
        /opt/pyenv/versions/3.6.8/lib/python3.6/site-packages

sys.executable:
        /opt/pyenv/versions/3.6.8/bin/python3.6

sys.version:
        3.6.8 (default, Nov  3 2020, 16:46:12) 
        [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

platform.platform():
        Linux-4.15.0-136-generic-x86_64-with-centos-7.6.1810-Core

which -a jupyter:
        /opt/pyenv/versions/3.6.8/bin/jupyter
        /opt/pyenv/shims/jupyter
        /opt/pyenv/shims/jupyter

pip list:
        Package             Version
        ------------------- ---------
        alembic             1.5.5
        anyio               2.1.0
        argon2-cffi         20.1.0
        async-generator     1.10
        attrs               20.3.0
        Babel               2.9.0
        backcall            0.2.0
        bleach              3.3.0
        certifi             2020.6.20
        certipy             0.1.3
        cffi                1.14.3
        chardet             3.0.4
        configparser        5.0.1
        contextvars         2.4
        cryptography        3.2.1
        dataclasses         0.8
        decorator           4.4.2
        defusedxml          0.6.0
        docopt              0.6.2
        entrypoints         0.3
        findspark           1.4.2
        future              0.18.2
        hdfs                2.5.8
        idna                2.10
        immutables          0.15
        importlib-metadata  3.4.0
        ipykernel           5.5.0
        ipython             7.16.1
        ipython-genutils    0.2.0
        jedi                0.18.0
        Jinja2              2.11.3
        json5               0.9.5
        jsonschema          3.2.0
        jupyter-client      6.1.11
        jupyter-core        4.7.1
        jupyter-server      1.4.0
        jupyter-telemetry   0.1.0
        jupyterhub          1.3.0
        jupyterlab          3.0.7
        jupyterlab-pygments 0.1.2
        jupyterlab-server   2.3.0
        kerberos            1.3.0
        Mako                1.1.4
        mandoo              1.2.1
        MarkupSafe          1.1.1
        minio               6.0.0
        mistune             0.8.4
        mysqlclient         2.0.1
        nbclassic           0.2.6
        nbclient            0.5.2
        nbconvert           6.0.7
        nbformat            5.1.2
        nest-asyncio        1.5.1
        notebook            6.2.0
        numpy               1.19.4
        oauthlib            3.1.0
        packaging           20.9
        pamela              1.0.0
        pandas              1.1.4
        pandocfilters       1.4.3
        parso               0.8.1
        pexpect             4.8.0
        pickleshare         0.7.5
        pip                 21.0.1
        prometheus-client   0.9.0
        prompt-toolkit      3.0.16
        psycopg2            2.8.6
        ptyprocess          0.7.0
        py4j                0.10.7
        pycparser           2.20
        pycrypto            2.6.1
        Pygments            2.8.0
        PyHive              0.6.3
        pykerberos          1.2.1
        pyOpenSSL           20.0.1
        pyparsing           2.4.7
        pyrsistent          0.17.3
        pyspark             2.3.1
        python-dateutil     2.8.1
        python-editor       1.0.4
        python-json-logger  2.0.1
        pytz                2020.4
        pyzmq               22.0.3
        requests            2.24.0
        requests-kerberos   0.12.0
        ruamel.yaml         0.16.12
        ruamel.yaml.clib    0.2.2
        sasl                0.2.1
        Send2Trash          1.5.0
        setuptools          40.6.2
        six                 1.15.0
        sniffio             1.2.0
        SQLAlchemy          1.3.20
        terminado           0.9.2
        testpath            0.4.4
        thrift              0.13.0
        thrift-sasl         0.4.2
        tornado             6.1
        traitlets           4.3.3
        typing-extensions   3.7.4.3
        urllib3             1.25.11
        wcwidth             0.2.5
        webencodings        0.5.1
        zipp                3.4.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by krassowski** [comment]
`jupyterlab_vim` is not on the `pip list` included in your troubleshoot output. Are you sure that you are installing in the same pyenv version that jupyterlab is installed in?

**Comment by humbledude** [comment]
sorry I tried again, again.. then I pasted wrong version of troubleshoot output.
could you check this?

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /opt/pyenv/versions/3.6.8/bin
        /opt/pyenv/libexec
        /opt/pyenv/plugins/python-build/bin
        /opt/pyenv/plugins/pyenv-virtualenv/bin
        /opt/pyenv/plugins/pyenv-update/bin
        /opt/pyenv/plugins/pyenv-installer/bin
        /opt/pyenv/plugins/pyenv-doctor/bin
        /opt/pyenv/plugins/python-build/bin
        /opt/pyenv/plugins/pyenv-virtualenv/bin
        /opt/pyenv/plugins/pyenv-update/bin
        /opt/pyenv/plugins/pyenv-installer/bin
        /opt/pyenv/plugins/pyenv-doctor/bin
        /opt/pyenv/plugins/pyenv-virtualenv/shims
        /opt/pyenv/shims
        /opt/hadoop-client-env-v2/target/jdk/jdk8u181-b13/bin
        hadoop-client-env-path-start
        /opt/hadoop-client-env-v2/target/Doopey/hadoop-2.6.0-cdh5.14.2/share/hadoop/mapreduce/bin
        /opt/hadoop-client-env-v2/target/Doopey/hive-1.1.0-cdh5.14.2/bin
        /bin
        /opt/hadoop-client-env-v2/target/Doopey/spark-2.3.1-bin-without-hadoop/bin
        /bin
        /opt/hadoop-client-env-v2/target/Doopey/zookeeper-3.4.5-cdh5.14.2/bin
        hadoop-client-env-path-end
        /opt/pyenv/shims
        /opt/pyenv/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/lib/java/jdk8u232-b09/bin
        /home/app/.local/bin
        /home/app/bin

sys.path:
        /opt/pyenv/versions/3.6.8/bin
        /home/app/python_libs
        /opt/pyenv/versions/3.6.8/lib/python36.zip
        /opt/pyenv/versions/3.6.8/lib/python3.6
        /opt/pyenv/versions/3.6.8/lib/python3.6/lib-dynload
        /home/app/.local/lib/python3.6/site-packages
        /opt/pyenv/versions/3.6.8/lib/python3.6/site-packages

sys.executable:
        /opt/pyenv/versions/3.6.8/bin/python3.6

sys.version:
        3.6.8 (default, Nov  3 2020, 16:46:12) 
        [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

platform.platform():
        Linux-4.15.0-136-generic-x86_64-with-centos-7.6.1810-Core

which -a jupyter:
        /opt/pyenv/versions/3.6.8/bin/jupyter
        /opt/pyenv/shims/jupyter
        /opt/pyenv/shims/jupyter

pip list:
        Package             Version
        ------------------- ---------
        alembic             1.5.5
        anyio               2.1.0
        argon2-cffi         20.1.0
        async-generator     1.10
        attrs               20.3.0
        Babel               2.9.0
        backcall            0.2.0
        bleach              3.3.0
        certifi             2020.12.5
        certipy             0.1.3
        cffi                1.14.5
        chardet             4.0.0
        configparser        5.0.1
        contextvars         2.4
        cryptography        3.2.1
        dataclasses         0.8
        decorator           4.4.2
        defusedxml          0.6.0
        docopt              0.6.2
        entrypoints         0.3
        findspark           1.4.2
        future              0.18.2
        hdfs                2.5.8
        idna                2.10
        immutables          0.15
        importlib-metadata  3.4.0
        ipykernel           5.5.0
        ipython             7.16.1
        ipython-genutils    0.2.0
        jedi                0.18.0
        Jinja2              2.11.3
        json5               0.9.5
        jsonschema          3.2.0
        jupyter-client      6.1.11
        jupyter-core        4.7.1
        jupyter-packaging   0.7.12
        jupyter-server      1.4.0
        jupyter-telemetry   0.1.0
        jupyterhub          1.3.0
        jupyterlab          3.1.0a3
        jupyterlab-pygments 0.1.2
        jupyterlab-server   2.3.0
        jupyterlab-vim      0.13.0
        kerberos            1.3.0
        Mako                1.1.4
        mandoo              1.2.1
        MarkupSafe          1.1.1
        minio               6.0.0
        mistune             0.8.4
        mysqlclient         2.0.1
        nbclassic           0.2.6
        nbclient            0.5.2
        nbconvert           6.0.7
        nbformat            5.1.2
        nest-asyncio        1.5.1
        notebook            6.2.0
        numpy               1.19.4
        oauthlib            3.1.0
        packaging           20.9
        pamela              1.0.0
        pandas              1.1.4
        pandocfilters       1.4.3
        parso               0.8.1
        pexpect             4.8.0
        pickleshare         0.7.5
        pip                 21.0.1
        prometheus-client   0.9.0
        prompt-toolkit      3.0.16
        psycopg2            2.8.6
        ptyprocess          0.7.0
        py4j                0.10.7
        pycparser           2.20
        pycrypto            2.6.1
        Pygments            2.8.0
        PyHive              0.6.3
        pykerberos          1.2.1
        pyOpenSSL           20.0.1
        pyparsing           2.4.7
        pyrsistent          0.17.3
        pyspark             2.3.1
        python-dateutil     2.8.1
        python-editor       1.0.4
        python-json-logger  2.0.1
        pytz                2021.1
        pyzmq               22.0.3
        requests            2.25.1
        requests-kerberos   0.12.0
        ruamel.yaml         0.16.12
        ruamel.yaml.clib    0.2.2
        sasl                0.2.1
        Send2Trash          1.5.0
        setuptools          53.0.0
        six                 1.15.0
        sniffio             1.2.0
        SQLAlchemy          1.3.20
        terminado           0.9.2
        testpath            0.4.4
        thrift              0.13.0
        thrift-sasl         0.4.2
        tornado             6.1
        traitlets           4.3.3
        typing-extensions   3.7.4.3
        urllib3             1.26.3
        wcwidth             0.2.5
        webencodings        0.5.1
        zipp                3.4.0
</pre>
</details>

**Comment by humbledude** [comment]
I found that `pip install --user EXTENSION`  installs extensions to user dir (`$HOME/.local/share/jupyter/labextension)
So I could retain user extension in user dir in PV.
Thank you
