### ISSUE TITLE
Debugger not launching as in the doc. 

### ISSUE THREAD

**Issue by Jacques2101** [jupyterlab/jupyterlab#9849]
## Description
I follow the doc to install the debugger on jupyterlab 3.0 ie:
```
conda create -n jupyterlab-debugger -c conda-forge jupyterlab=3 xeus-python
```
but nothing happens after that when I launch Jupyterlab. I don't see the debugger 

## Context
- Operating System and version: MacOS 11.2.1
- Browser and version: Chrome Version 88.0.4324.182 (Build officiel) (x86_64)
- JupyterLab version: 3.0.8

**Comment by jtpio** [comment]
@Jacques2101 did you also activate the environment before launching JupyterLab?

```bash
conda activate jupyterlab-debugger
```

Do you see the xeus-python kernel in the JupyterLab launcher?

![image](https://user-images.githubusercontent.com/591645/108751588-b632b580-7542-11eb-9d4f-f5cafe201a40.png)

**Comment by Jacques2101** [comment]
No. I don't see it neither in the launcher.

**Comment by jtpio** [comment]
> No. I don't see it neither in the launcher.

ok then it's probably because JupyterLab is not started from the environment that has `xeus-python`?

**Comment by Jacques2101** [comment]
Right !
It works now. 
thx.

**Comment by jtpio** [comment]
Nice, thanks for checking!
