### ISSUE TITLE
LaTeX equations in Headings are not correctly displayed following recent update to 3.0.7

### ISSUE THREAD

**Issue by tzxiong** [jupyterlab/jupyterlab#9852]
Hi,

I recently upgraded my local JupyterLab from 1.0.x to 3.0.7 on Feb.7th, 2021, and I found that all math equations in the headings are not correclty rendered. The effect is rather stochastic, for instance:

Original markdown code:

![Screen Shot 2021-02-07 at 7 07 30 PM](https://user-images.githubusercontent.com/55631424/107170222-cd43a600-698d-11eb-97ef-748c5f5704ef.png)

Effect 1:

![Screen Shot 2021-02-07 at 7 08 12 PM](https://user-images.githubusercontent.com/55631424/107170235-d5034a80-698d-11eb-8a85-814694d02710.png)

Effect 2:

![Screen Shot 2021-02-07 at 7 07 16 PM](https://user-images.githubusercontent.com/55631424/107170252-de8cb280-698d-11eb-87c4-7fd091e338f2.png)

These two effects are both for the same cell at different times. The second effect has also been observed by a separate colleague who updated Jupyter Lab in late December, 2020 (v 3.0.4). 

This problem appears to only affect a running notebook, as exporting to HTML appears normal.

**Comment by jasongrout** [comment]
Looks like it's easy to transfer the issue. Thanks for flagging this, @krassowski

**Comment by jasongrout** [comment]
Checking this out, here is my example text:

```markdown
# Heading $\frac{x}{y}$
```
Here is JLab 2.2.9
<img width="249" alt="Screen Shot 2021-02-22 at 12 09 29 PM" src="https://user-images.githubusercontent.com/192614/108763955-d8a6dd80-7506-11eb-815b-191bce9b2494.png">

Here is JLab 3.0.8:
<img width="250" alt="Screen Shot 2021-02-22 at 12 10 11 PM" src="https://user-images.githubusercontent.com/192614/108764038-efe5cb00-7506-11eb-8d11-2e3dfe758d98.png">

**Comment by jasongrout** [comment]
Interestingly, installing the mathjax3 extension in jlab 3 renders the heading correctly initially, but when I click on the heading (selecting the cell), the math part of the heading completely disappears.

**Comment by jasongrout** [comment]
Fixed by #9932
