### ISSUE TITLE
[Debugger] Rich mimetype rendering in the variable inspector

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/jupyterlab#9867]
### Problem

For now the debugger displays variables in a pretty simple manner:

![image](https://user-images.githubusercontent.com/591645/108988421-b9d65180-7694-11eb-857d-ed52fa4448f0.png)

### Proposed Solution

It would be nice to have a more visual way of inspecting variables.

Possible sources of inspirations could be [Spyder](https://docs.spyder-ide.org/current/variableexplorer.html#numpy-arrays):

![image](https://user-images.githubusercontent.com/591645/108988218-7ed41e00-7694-11eb-9176-69aa4bfa94e5.png)

Or the [JupyterLab Variable inspector extension](https://github.com/lckr/jupyterlab-variableInspector), for example rendering widgets:

![image](https://raw.githubusercontent.com/lckr/jupyterlab-variableInspector/master/ipywidgets.png)

**Comment by besbesmany** [comment]
when jupyterlab 4.0 is released?

the  JupyterLab Variable inspector extension, is not working on current last version 3.0.14
