### ISSUE TITLE
Inconsistent use of ellipses

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab#9874]
## Description

In various places in the interface (menus, command palette, etc.), we indicate that a command will open a dialog with either three dots `...` or a proper unicode ellipsis `…` (i.e., a single ellipsis character). We should be consistent about this. I think we should convert the three dots to unicode ellipses.

This may be as easy as searching for `...'` and .ts files and replacing it with `…'` (hand-checking those replacements to make sure they are appropriate, of course).

## Reproduce

For example, the File > Print... menu item has three dots, and many other examples

## Expected behavior

The File > Print... item should use an ellipsis instead of three dots, for example.

## Context

- Operating System and version:
- Browser and version:
- JupyterLab version: JupyterLab 3.0

**Comment by saulshanabrook** [comment]
Thanks Jason for filing this :)

I am working with a few folks who would like to use this issue as a way to get familiar with how to contribute, so we can tackle it!

**Comment by jasongrout** [comment]
> Thanks Jason for filing this :)

Thanks. Sometimes I wonder why I spending 2-3 times longer filing the issue than it would take to fix it, but that is exactly the reason :).

**Comment by manurampandit** [comment]
I would like to pick this up as my first attempt to contribute.

**Comment by saulshanabrook** [comment]
I went searching for `...` and only found one that I could actually see in the UI, the filter in the JSON extension:
 
<img width="394" alt="Screen Shot 2021-03-16 at 4 07 49 PM" src="https://user-images.githubusercontent.com/1186124/111372991-c33e5280-8671-11eb-9f4e-d639d3877b3f.png">

It also shows up in the code for pagination of the extension manager, but not sure how to enable the pagination.

**Comment by jasongrout** [comment]
FYI, I see 16 occurrences of `...'` in packages/

**Comment by telamonian** [comment]
you can see a whooole bunch of them in the names of various menu items

![image](https://user-images.githubusercontent.com/2263641/111374306-50ce7200-8673-11eb-9aba-a6f9f88f510d.png)

**Comment by shngt** [comment]
Should this issue be closed? Seems like it's been resolved

**Comment by blink1073** [comment]
> Should this issue be closed? Seems like it's been resolved

Agreed, thanks for the heads up!
