### ISSUE TITLE
Selecting Browser

### ISSUE THREAD

**Issue by felixxcheng** [jupyterlab/jupyterlab#9877]
Hi, I installed LBRY on my computer and suddenly my Jupyter Lab does not launch from the Linux CLI. 
Is there a way to fix this?  

Also, I have more than one browser installed, is there a way to choose browser Jupyter Lab launches?

Thank you

**Comment by krassowski** [comment]
`jupyter lab --help` will show you the arguments available for launching JupyterLab, one of which is `--browser` (see the help output for more). Make sure that you have the latest version of jupyterlab and jupyterlab-server installed as there were some improvements with browser handling. It is also possible to configure jupyterlab to always launch with specified browser; I am not currently able to find reliable documentation source for that so this might require improvements.

**Comment by jtpio** [comment]
It should indeed be possible to create a `jupyter_server_config.py` file in one of the directories returned by `jupyter --paths`, for example in `~/.jupyter/jupyter_server_config.py`, with the following content:

```python
c.ServerApp.browser = '/usr/bin/firefox'
```

**Comment by felixxcheng** [comment]
So before I was just inputting 'jupyter lab' into the CLI and a Brave browser would launch with the notebook.  Now I am getting " [W 15:18:29.525 LabApp] No web browser found: could not locate runnable browser."  When putting in:
jupyter lab --browser='/usr/bin/brave-browser'

Ideally I could just go back to the way things were, thank you

**Comment by krassowski** [comment]
Have you updated `jupyterlab`, `jupyterlab_server`, and `jupyter_server` as recommended above? What versions of those packages do you have installed? If it happens in the most recent versions (it should not), then please fill in the information as requested in the [bug report issue template](https://github.com/jupyterlab/jupyterlab/issues/new?assignees=&labels=&template=bug_report.md) as that helps the volunteers answering your questions to help you.

**Comment by felixxcheng** [comment]
yes, all of those are updated.

I fixed the issue by deleting all browsers fother than the one I wanted to use.
