### ISSUE TITLE
`jupyter lab build` fails on Windows because of `node.EXE`

### ISSUE THREAD

**Issue by axelboc** [jupyterlab/jupyterlab#9888]
## Description

When I run `jupyter lab build` on Windows, I get:

```
Fail to get yarn configuration. 'node.EXE' is not recognized as an internal or external command, 
operable program or batch file.
```

Windows is case sensitive, so executing `node` or `node.exe` works fine, but not `node.EXE`:

![image](https://user-images.githubusercontent.com/2936402/109654632-b1818900-7b62-11eb-97ee-f70f101a111b.png)

## Context

- `python`: 3.7.9
- `jupyter core`: 4.7.1
- `jupyter lab`: 2.2.9

**Comment by jasongrout** [comment]
Just curious: does it work for you with JupyterLab 3.0.9?

**Comment by jasongrout** [comment]
And secondly, it would be helpful to know exactly where in the build process it is stopping, so if you could copy the log here, we could pinpoint better which call to node seems to be the problem.

**Comment by bollwyvl** [comment]
> Windows is case sensitive

This is very curious indeed, as I'm pretty sure `cmd` and `ps1` _aren't_ case sensitive. Are you running some kind of hybrid command environment? I think the behavior in cygwin/WSL, etc. is _undefined_, at best...

**Comment by axelboc** [comment]
Hmm, you're right @bollwyvl -- it's just my `node` executable that doesn't seem to be. I made a pretty bad generalisation there, sorry 😓. I've installed Node with [Volta](https://volta.sh/), which is probably the culprit, then. Will take the issue there. Thanks!
