### ISSUE TITLE
Docs for building docs list outdated requirements file

### ISSUE THREAD

**Issue by saulshanabrook** [jupyterlab/jupyterlab#9891]
## Description

The docs for getting set up to build the docs say to run `pip install -r docs/requirements.txt`. However, that file no longer exists. There is however a `docs/environment.yml` file that has the dependencies that are required for build the documentation . There is also a `docs` section in the `setup.py` `install_requires`, but it is outdated. It doesn't contain the `myst_parser` dependency, which is required. 

To resolve this, I would suggest either keeping the install using pip, and updating our `setup.py` dpcs section to have all the proper dependencies. Or to take out that section, because it is out of date, and say to use conda in the docs.

## Reproduce

Try to follow the [guide for building the docs in the Contributing documentation](https://jupyterlab.readthedocs.io/en/stable/developer/contributing.html#writing-documentation) and you won't be able to install the dependencies.

## Expected behavior

Dependencies would be installed. 

## Context

N/A

**Comment by jtpio** [comment]
Closing as the docs should now be up-to-date.
