### ISSUE TITLE
Command linker support in markdown cells

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab#9899]
### Problem

As a user, I would like to add buttons and other simple UI elements by writing HTML in markdown cells that trigger JupyterLab commands. For example, I would like to add a button in a markdown cell that runs all of the cells of a notebook:

```html
<button data-commandlinker-command="terminal:create-new">Create Terminal</button>
``` 

### Proposed Solution

We have a command linker that works in output areas but not in markdown areas. I believe it will be straightforward to wire up the command linker to work in rendered markdown cells.

**Comment by agoose77** [comment]
Just throwing some thoughts out there - would your use case be facilitated if this were implemented with a mime-renderer? Could you use `ipywidgets.Button` to trigger a call to `display()`?

**Comment by agoose77** [comment]
Ah, I see that this is an existing extension mechanism for JupyterLab, and your request is just to permit this behaviour in the MD sanitiser.
