### ISSUE TITLE
Git prompt in terminal

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterlab/jupyterlab#990]
This is probably more of a terminado issue. In the terminal window, I am seeing the following message, while I don't have this problem in a regular (desktop) terminal session.

`bash: __git_ps1: command not found`

ping @takluyver

**Comment by takluyver** [comment]
Nothing immediately springs to mind. Can you work out what's looking for that command (e.g. `PROMPT_COMMAND`?) and where it's set?

**Comment by SylvainCorlay** [comment]
On OS X, I have the following thing in my bash profile:

````
# Git autocompletion and prompt
source /usr/local/etc/bash_completion.d/git-completion.bash
source /usr/local/etc/bash_completion.d/git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=true
export PS1='[\u@mbp \w$(__git_ps1)]\$ '
```

**Comment by takluyver** [comment]
Can you set some random env variable in that file to check whether it's getting sourced in the web terminals? e.g. `export ZARNIWOOP=foo`. It could be something to do with the difference between login shells and non login shells, which always confuses me.

**Comment by fperez** [comment]
FWIW, I'm not seeing this either, this is a screenshot overlaying a plain terminal atop the JLab one, and I get the same (correct) behavior in both, my git branch in `(green)` at the prompt:

![image](https://cloud.githubusercontent.com/assets/57394/20691171/f33dbcf0-b583-11e6-9975-7b264d381e85.png)

I suggest closing this one unless @SylvainCorlay has more info to reproduce it...

**Comment by blink1073** [comment]
Closing...
