### ISSUE TITLE
Mimerender Ranks

### ISSUE THREAD

**Issue by mlucool** [jupyterlab/jupyterlab#9901]
Hi,

Is there any guidance on mimerender ranks? The cookie cutter [default rank is 0](https://github.com/jupyterlab/mimerender-cookiecutter-ts/blob/master/%7B%7Bcookiecutter.python_name%7D%7D/src/index.ts#L62). If everything set its rank as 0, it's hard to override a preference of ordering (at least AFAIK).

Left/Right Areas gives [this guidance](https://jupyterlab.readthedocs.io/en/stable/extension/extension_points.html#left-right-areas):
```
The recommended ranges for this rank are:
0-500: reserved for first-party JupyterLab extensions.
501-899: reserved for third-party extensions.
900: The default rank if none is specified.
1000: The JupyterLab extension manager.
```

**Comment by afshin** [comment]
I'd say we should either set it to `501` or `900` then. What do you think?

**Comment by ellisonbg** [comment]
Agree about `501` or `900`. Maybe `501` as `900` was meant to handle the case of a rank not being specified?

**Comment by fcollonval** [comment]
Actually the documentation points to the sidebars tab rank. But for the rendermime registry the default value is 100:
https://github.com/jupyterlab/jupyterlab/blob/9850b1a0461ae7d32374ca970185bdd12029fa62/packages/rendermime/src/registry.ts#L220-L222

I pushed a PR with 100: https://github.com/jupyterlab/mimerender-cookiecutter-ts/pull/28

**Comment by mlucool** [comment]
Thanks for making the update to cookiecutter. Can we also update the docs to provide official guidance?
