### ISSUE TITLE
Table of contents, contract & expand options

### ISSUE THREAD

**Issue by akitxu** [jupyterlab/jupyterlab#9902]
Dear all.
I work with a notebook with up to 30 sections with their corresponding subsections in the table of contents. It would make it easier for me to locate the subsections, and it would make it possible to improve these indices, have an option that allows contracting and expanding this index. Although I am not yet fully aware of all the currently available options, I have not identified this one. Thanks a lot.

**Comment by lresende** [comment]
Would you be able to illustrate a little more the issue, maybe with some screen captures?

**Comment by akitxu** [comment]
Thanks for your attention. This is a imagen of one of my notebooks.
![Captura de pantalla de 2021-03-05 20-51-16](https://user-images.githubusercontent.com/40218417/110166482-b9585c00-7df4-11eb-8684-febd9a585dd7.png)

Collapsing the indexes would allow me to see the table of contents, for example, with only the first level (1 ..., 2 ...., 3 ..., etc.), being able to click on any of them, expand it to show sublevels.

**Comment by cameron-toy** [comment]
Seems like a good feature! I'll work on it if no one else currently is. Also @akitxu, wow, I have never seen such a long Notebook! 🙀

**Comment by cameron-toy** [comment]
![collapse](https://user-images.githubusercontent.com/38936057/116629505-43f59d00-a906-11eb-8dcc-7674f584fce5.gif)

I'm not sure if it was just recently added but it looks like collapsing sections is supported!

**Comment by krassowski** [comment]
I will close this issue as it seems that this behaviour was implemented since the inclusion of ToC into JupyterLab core in 3.0.

Further option to also collapse cells in notebooks is also coming in #10545. I think that this question might have been a result of missing documentation for ToC which is now tracked in #10597.
