### ISSUE TITLE
Enable kite server in order to run kite in jupyter lab

### ISSUE THREAD

**Issue by ThamuMnyulwa** [jupyterlab/jupyterlab#9906]
I am trying to install kite on jupyter-lab 3.0.5 using a Linux terminal but the server extension is not working. Instead, I am getting this error message:

    Server Extension Unreachable
    
    The jupyterlab-kite extension will not work because the jupyter-kite server extension could not be reached.
    
    To fix this, please ensure the jupyter-kite server extension is installed and active (`jupyter serverextension list`), then restart the JupyterLab process.

I have tried uninstalling it and reinstalling it using:

    pip install "jupyterlab-kite>=2.0.2"

but I cannot get the server extension to work. When I try to enable the server extension, I get an error as shown below.

<pre><font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ jupyter server extension enable jupyter_kite
Enabling: jupyter_kite
- Writing config: /usr/etc/jupyter
    - Validating jupyter_kite...
      jupyter_kite 2.0.2 <font color="#4E9A06">OK</font>
     <font color="#CC0000"> X</font> Validation failed: [Errno 13] Permission denied: &apos;/usr/etc&apos;
</pre>

I have found what I think is a solution on [GITHUB here](https://github.com/jupyterlab/jupyterlab/issues/8122) but I have not installed Jupyter using Anaconda so this address (<code><conda_root>/share/jupyter/lab/settings/build_config.json</code>) is not the same as on my computer to delete the <code>build_config.json</code> file. Does anyone know how else I could find this file in order to enable the kite server?

**Comment by agoose77** [comment]
Can you run the following and report their results? I'm not 100% on how exactly the server extension chooses the config directory, but I'm guessing something's been installed as root.

* `jupyter --paths`
* `python -m site`
* `which pip`
* `jupyter server extension list`

**Comment by ThamuMnyulwa** [comment]
Hi @agoose77 , thanks for the help. I have put the output below:

<pre><font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ jupyter --paths
config:
    /home/thamu/.jupyter
    /usr/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/thamu/.local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/thamu/.local/share/jupyter/runtime
<font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ python - site

Command &apos;python&apos; not found, did you mean:

  command &apos;python3&apos; from deb python3
  command &apos;python&apos; from deb python-is-python3

<font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ python3 - site
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
</pre>

thamu@thamu-PC:~$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

<pre><font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ jupyter server extension list
Config dir: /home/thamu/.jupyter

Config dir: /usr/etc/jupyter

Config dir: /usr/local/etc/jupyter

<font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ jupyter serverextension list
config dir: /home/thamu/.jupyter
    jupyterlab_code_formatter <font color="#4E9A06"> enabled </font>
    - Validating...
      jupyterlab_code_formatter  <font color="#4E9A06">OK</font>
    jupyter_nbextensions_configurator <font color="#4E9A06"> enabled </font>
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 <font color="#4E9A06">OK</font>
<font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ </pre>

**Comment by agoose77** [comment]
Have you installed `jupyter-kite` via `pip`?

**Comment by ThamuMnyulwa** [comment]
Hi @agoose77  yes I have.

<pre><font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ pip3 install jupyter-kite
Requirement already satisfied: jupyter-kite in ./.local/lib/python3.8/site-packages (2.0.2)
</pre>

**Comment by ThamuMnyulwa** [comment]
I also showed the log file that was produced when I tried to enable the server [here](https://github.com/kiteco/issue-tracker/issues/608).

**Comment by agoose77** [comment]
Hmm, there seems to be a lot going on here. 

Are you using virtual environments? Which version of JupyterLab are you using?

**Comment by ThamuMnyulwa** [comment]
I am not using any virtual environments. My OS is Ubuntu 20.04.1 . I am running the code on the jupyter lab  3.0.5 .

<pre><font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.4
ipython          : 7.15.0
ipykernel        : 5.3.0
jupyter client   : 6.1.3
jupyter lab      : 3.0.5
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3
</pre>

<pre><font color="#4E9A06"><b>thamu@thamu-PC</b></font>:<font color="#3465A4"><b>~</b></font>$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
</pre>

**Comment by agoose77** [comment]
Ideally you should use a virtualenv to avoid installing everything globally. Sometimes the "nuke-and-recreate" option granted by using a contained environment is quite useful. 

In JupyterLab 3.0 you shouldn't need to run any `labextension`, `serverextension`, or even `server extension` commands for Kite (from what I can see). It uses the new prebuilt extension delivery mechanism (so no need to install the labextension from npm), and I think it can activate the server extension itself. 

You only need `pip install "jupyterlab-kite>=2.0.2"`. However, you should make sure that you don't have any errors upon installation e.g. if you don't have `wheel` installed, you'll get an error about `bdist_wheel`. 

Because you've already installed a lot of these things, you might need to do some cleanup first. I'd suggest uninstalling `jupyter-kite` and `jupyterlab-kite` if either is currently installed. Then, uninstall the `jupyterlab-kite` JupyterLab extension too. If it were me, I would probably manually remove the packages from the `site-packages` directory (along with their egg-infos) along with JupyterLab, delete the JupyterLab user data in `$HOME/.jupyter and `$HOME/.local/share/jupyter`. Then use a virtualenv for reinstalling `jupyterlab` and `jupyterlab-kite`
