### ISSUE TITLE
Allow for a Python console at a breakpoint

### ISSUE THREAD

**Issue by LucaMarconato** [jupyterlab/jupyterlab#9922]
### Problem

Modern Python IDEs allows for opening a Python REPL console at a breakpoint (when the breakpoint is set in a `*.py` file, so that you can execute custom Python code with all the values that you end up with at that specific breakpoint. This feature is extremely useful and makes me code much faster. 

Unfortunately with JupyterLab this is not possible. There are two aspects here:
* In standard JupyterLab you can open an additional "Console for notebook". There is no debugger in the interface, but you can use the command `breakpoint()` (or `import pdb; pdb.set_trace()`. If you do that the console that you opened is "frozen", if you run commands there they will be executed only after you exit from the breakpoint (for instance typing `q` and then pressing `<return>`).
* It is now possible to add a [debugger plugin](https://github.com/jupyterlab/debugger) to JupyterLab, which is [based on a `xeus-python` kernel](https://github.com/jupyter-xeus/xeus-python). With that you can set breakpoints by placing the usual red circles on the left of the code, stop the program and see the values of the variables at the breakpoint. But still, there is no way of running commands on a REPL console at that point. I have already opened the issue in the `xeus-python` repository, but I have been told that it is something it should be handled by JupyterLab itself. Issue here: https://github.com/jupyter-xeus/xeus-python/issues/423#event-4420295879

### Proposed Solution

When the program executing is halted at a breakpoint, any console for the notebook should be able to send commands. Or maybe one could open a new "Debug console"

**Comment by telamonian** [comment]
I agree, a REPL is conspiciously lacking from the debugger. Being able to interact with the breakpoint-ed state is enormously helpful for figuring out what's going wrong with something, and it's a tool I use a lot in other IDEs.

@afshin @jtpio Do you guys think this is feasible? Any sense of what the workload for implementing an interactive prompt in the debugger would be like?

Quoting @JohanMabille from the issue the OP cites:

> While the backend already supports executing code when stopped on a breakpoint, the frontend has not implemented the GUI to do so yet. This issue should be opened on the JupyterLab repo.

So I guess that means it's possible to do on our end, but I don't have a sense of how hard it would be

**Comment by jtpio** [comment]
Linking to https://github.com/jupyterlab/jupyterlab/issues/9111 which also discussing this, and using the `evaluate` request from the DAP.

**Comment by jtpio** [comment]
> Any sense of what the workload for implementing an interactive prompt in the debugger would be like?

It might be possible to reuse components similar to the input cells to enter the code to evaluate. They could be presented as `Dialog`, or be added to the debugger sidebar.

**Comment by jtpio** [comment]
Let's move the discussion to https://github.com/jupyterlab/jupyterlab/issues/9111 to consolidate the issue there. Thanks all for the input!

> But really what I want is just some form of interactive prompt or another as part of the debugger sidebar

@telamonian if you have suggestions for the UI / UX, please don't hesitate to post in https://github.com/jupyterlab/jupyterlab/issues/9111, thanks!
