### ISSUE TITLE
Color in headers no more working in JupyterLab 3

### ISSUE THREAD

**Issue by nelijuc** [jupyterlab/jupyterlab#9926]
## Description

In JupyterLab 3.0.10 changing the color of the headers in markdown cells doses not work, everything in rendered in black. This is working in JupyterLab 2.2.9 as well as with the classical notebook interface.

## Reproduce

In JupyterLab 3.0.10, put the following in a markdown cell:
`# aaa <span style="color:red">red</span> bb`
and evaluate.

## Expected behavior

In JupyterLab 3.0.10 everything is rendered in black, whereas in JupyterLab 2.2.9 or in JupyterNotebook 6.2.0, red is rendered in red, which is the expected behavior.

## Context

Colors outside headers are working fine.

The handling of colors in headers is even a bit more complicated. Executing:
from IPython.display import Markdown
`Markdown('# aaa <span style="color:red">red</span> bb')`
will display the word red in red for a second, and then back to black, see the screencast.

https://user-images.githubusercontent.com/52205139/110624762-ed3dd380-819e-11eb-85db-5f487195e493.mp4

**Comment by jasongrout** [comment]
It looks like it might be the sanitizer deleting the style tag. Here's what is in the DOM when I do the header:

![Screen Shot 2021-03-10 at 3 00 31 PM](https://user-images.githubusercontent.com/192614/110709690-765e0600-81b1-11eb-9187-3e07b48444e2.png)

**Comment by jasongrout** [comment]
I also confirmed that the red style works in jlab 2.2.9.

**Comment by jasongrout** [comment]
I tracked it down to the new table of contents extension. This line is resetting the heading html with its own sanitized version, which uses different sanitization options than the original markdown renderer: https://github.com/jupyterlab/jupyterlab/blob/524d8f9c4e3df44d31e74cfa19edf53e826ee4ba/packages/toc/src/generators/notebook/get_rendered_html_heading.ts#L72

It looks like it is rewriting the html element to add the automatic numbering if it is turned on. Fix coming up.

**Comment by nelijuc** [comment]
Thanks for your quick fix!
