### ISSUE TITLE
Vega-Lite 5

### ISSUE THREAD

**Issue by davidanthoff** [jupyterlab/jupyterlab#9929]
Vega-Lite 5 is out :) Would be great if Jupyter Lab could ship with that. And I actually also noticed that for example vega and the other related deps are also quite outdated, so probably would make sense to update them all as well?

CC @domoritz

**Comment by domoritz** [comment]
We made sure most of Vega-Lite 5 is backwards compatible (even if the schema is not backwards compatible for example for selections).

**Comment by jasongrout** [comment]
Thanks for letting us know!

Interestingly, our extension is for vega 4 and vega-lite 4. I don't think we considered the possibility of vega still being version 4, but vega-lite being updated to a new major version.

I just published updated versions of the vega2 and vega3 packages as well. Perhaps an easy path forward is to publish a vega-lite 5 extension over in https://github.com/jupyterlab/jupyter-renderers - then we wouldn't have to wait until jlab 4 (or even jlab 3.1).

**Comment by jasongrout** [comment]
@domoritz - a couple of questions about vega-lite (and vega):

1. I see the activity in the vega repo slowing down. Is vega maturing, so that the major updates will be more in vega-lite and other projects, but vega remains a stable base with a very slow major version cycle? Or am I reading too much into the vega repo activity right now?
2. Are there any changes needed to how we are using vega-lite (a quick glance at the release notes indicates no real changes?): https://github.com/jupyterlab/jupyterlab/blob/82604b43eb5563b0cee5fc69fcf4ee52ef46b15c/packages/vega5-extension/src/index.ts#L118-L124
3. Does vega-lite version 5.0 understand vega-lite 4 specs? Can we use vega-lite version 5 similar to how we are supporting vega-lite 3 and 4 currently (by passing any vl3 or vl4 spec into vega-lite 4). I know we talked about backwards compatibility last time, and I'm sure this will keep coming up...


Ideally, all we would need to do is add one more mimetype to our existing plugin for the new vega-lite 5 specs, update our vega-lite npm dependency to version 5, and feed all the specs we support (vega-lite 3, vega-lite 4, or vega-lite 5) into the vega-lite npm package version 5, and things would work. Please tell me this is the case :).

**Comment by domoritz** [comment]
1. Vega is quite mature at this point and I personally don't see a reason why it would break backward compatibility anytime soon. @jheer can comment on his view on this. 

2. No changes needed.

3. Yes, Vega-Lite 5 understands Vega-Lite 4. We translate selections to params so we don't break existing specs. However, we did remove `rangeStep`, which was already deprecated. @kanitw that was it, right?

Re mime types. One thing I wanted to note is that Altair is not yet on Vega-Lite 5 (see https://github.com/altair-viz/altair/issues/2425) and it's the biggest user of Vega in Jupyter Lab. Would we break it with an update?

**Comment by davidanthoff** [comment]
> Would we break it with an update to the mimetype?

I think the proposal at the moment is that vega-lite 5 would be used to render vega-lite 3,4,5 MIME types, right? So as long as the vega-lite 5 lib can render these MIME types, I think everything should be ok?

Two random (more medium term) comments: 1) I still think that the nteract way of handling all of this is really excellent, i.e. where they ship a copy of all major vega and vega-lite lib versions out of the box, and then they use the "correct" lib depending on the MIME type that shows up. That seems (long term) just a much safer way to guarantee backwards compat. 2) I'm wondering why vega-lite 5 did get a major version bump at all? Or is it just not following semver?

**Comment by jasongrout** [comment]
> I think the proposal at the moment is that vega-lite 5 would be used to render vega-lite 3,4,5 MIME types, right? So as long as the vega-lite 5 lib can render these MIME types, I think everything should be ok?

Correct, that is what I'm proposing. We currently support [Vega-lite 3](https://github.com/jupyterlab/jupyterlab/blob/master/packages/vega5-extension/src/index.ts#L189-L194) and [Vega-lite 4](https://github.com/jupyterlab/jupyterlab/blob/master/packages/vega5-extension/src/index.ts#L183-L188) in JLab 3 core, so I think we have an obligation to maintain support for those spec versions in core until at least JLab 4, i.e., for the remainder of this year.


> 1) I still think that the nteract way of handling all of this is really excellent, i.e. where they ship a copy of all major vega and vega-lite lib versions out of the box, and then they use the "correct" lib depending on the MIME type that shows up.

We do that, but not in core, i.e., we separately ship (vega 2/vega-lite 1) and (vega 3/vega-lite 2) renderers as [non-core extensions](https://github.com/jupyterlab/jupyter-renderers#packages) that use the respective versions of the libraries, and people can install those independently if they want to maintain support for the older versions of the spec (with the actual older versions of the libraries). I don't recall all of the reasons we decided not to ship all the older libraries in core, but I think it at least had to do with:
1. Good practices of not shipping unmaintained libraries in core (security best practices, as well as not giving the illusion that we are maintaining the libraries for bugfixes, etc.)
2. Since we maintain a uniform build process for core, we were having problems compiling the older libraries with a newer typescript/build chain, IIRC
3. Size - perpetually shipping original versions of libraries seems like it is signing up for scaling issues

Instead, IIRC, we talked with upstream about vega-lite (current version) being able to support and auto-convert spec versions from older versions of the spec to the current rendering engine, at least for some reasonable backwards compatibility window, allowing us to ship just the currently-maintained library in core, but still support some window of older versions of the spec.

> 2) I'm wondering why vega-lite 5 did get a major version bump at all? Or is it just not following semver?

The changes they talk about in the release notes look pretty exciting! They did include some backwards-incompatible changes in a new version of the spec: https://github.com/vega/vega-lite/releases/tag/v5.0.0

(By the way, I think it's helpful to differentiate between the vega-lite JSON spec version and the vega-lite npm package version when talking about versions, even if they agree and can be conflated now. There could conceivably be a backwards-incompatible change in the npm package, bumping to npm package version to 6.0, while still maintaining the spec version at 5.0. We've seen that in our nbformat package, for example, where for a while the python package version and notebook format spec version aligned, but now is out of sync. We've also seen it in ipywidgets, etc.)

**Comment by domoritz** [comment]
So far we haven't had the need to update the library without bumping the spec version (and the opposite isn't really an issue). Therefore, we haven't had a situation where the spec and library diverged.

**Comment by jasongrout** [comment]
> So far we haven't had the need to update the library without bumping the spec version (and the opposite isn't really an issue). Therefore, we haven't had a situation where the spec and library diverged.

Understood. My point is that being careful to disambiguate the version numbers in conversation and documentation now will save confusion in the future if/when it happens. We certainly had confusion when those version numbers separated which we could have avoided by being careful with the terminology before.

**Comment by jasongrout** [comment]
@domoritz - just checking the outstanding question: will vega-lite package version 5.0 be able to handle vega-lite spec version 3? (I think you already said it should be able to handle spec version 4 in your comment above)

**Comment by domoritz** [comment]
rangeStep will be ignored if the spec uses it. Other than that, specs should still work. We deprecated rangeStep in the v4 release in 2019.

**Comment by davidanthoff** [comment]
Bump, would be fantastic if we could somehow get vega-lite 5 shipping :) We would like to update VegaLite.jl to vega-lite 5, but we can't until JuptyerLab ships with the vega-lite 5 binaries...

**Comment by domoritz** [comment]
Would it be possible for you to generate html that loads Vega-Lite from a CDN? I know it wouldn't work offline but it would allow you to load any Vega-Lite version.

**Comment by kimmolinna** [comment]
@jasongrout are you still planning to upgrade vega-lite to version 5.x or what's the situation?
@domoritz do you see any obstacle in upgrading process?

**Comment by domoritz** [comment]
I don't see any obstacles.

**Comment by jasongrout** [comment]
> @jasongrout are you still planning to upgrade vega-lite to version 5.x or what's the situation?

Unfortunately, I probably won't be able to do this work this time. PRs are certainly welcome, though!

**Comment by joelostblom** [comment]
@jasongrout We talked about this in the Altair repo and one of the Altair contributors might be able to help. Would you be able to give a high level description of what needs to change in which files (or point to a previous PR with similar changes)? Then we can attempt a PR which would be important for us as Altair is soon being updated to only work with vega lite 5.

**Comment by domoritz** [comment]
You can look at my existing PRs like https://github.com/jupyterlab/jupyterlab/pull/4107/files. Vega-Lite 5 should support Vega-Lite 4 specs even though the schema is not satisfied.

**Comment by ChristopherDavisUCI** [comment]
Thanks @domoritz, @joelostblom and @jasongrout!  I hope it's okay that I made a very naive Draft PR #13893 as a starting point.  Offline rendering for Altair charts using Vega-Lite v5 worked in my first tests, but I'm sure there are further changes which should be made.

**Comment by joelostblom** [comment]
As #13893 has been merged I think this issue can be closed

**Comment by akshay00711** [comment]
vega-5 is compatible with angular 8 ??

**Comment by akshay00711** [comment]
Getting Error after updating to latest Vega packages.
Angular venison 8

ERROR in ../node_modules/vega-lite/build/src/compositemark/index.d.ts:10:1 - error TS1128: Declaration or statement expected.

10 export type { BoxPlotConfig } from './boxplot';
   ~~~~~~
../node_modules/vega-lite/build/src/compositemark/index.d.ts:10:13 - error TS1005: ';' expected.

10 export type { BoxPlotConfig } from './boxplot';
               ~
../node_modules/vega-lite/build/src/compositemark/index.d.ts:10:36 - error TS1005: ';' expected.

10 export type { BoxPlotConfig } from './boxplot';
                                      ~~~~~~~~~~~
../node_modules/vega-lite/build/src/compositemark/index.d.ts:11:1 - error TS1128: Declaration or statement expected.

11 export type { ErrorBandConfigMixins } from './errorband';
   ~~~~~~
../node_modules/vega-lite/build/src/compositemark/index.d.ts:11:13 - error TS1005: ';' expected.

11 export type { ErrorBandConfigMixins } from './errorband';
               ~
../node_modules/vega-lite/build/src/compositemark/index.d.ts:11:44 - error TS1005: ';' expected.

11 export type { ErrorBandConfigMixins } from './errorband';
                                              ~~~~~~~~~~~~~
../node_modules/vega-lite/build/src/compositemark/index.d.ts:12:1 - error TS1128: Declaration or statement expected.

12 export type { ErrorBarConfigMixins } from './errorbar';
   ~~~~~~
../node_modules/vega-lite/build/src/compositemark/index.d.ts:12:13 - error TS1005: ';' expected.

12 export type { ErrorBarConfigMixins } from './errorbar';
               ~
../node_modules/vega-lite/build/src/compositemark/index.d.ts:12:43 - error TS1005: ';' expected.

12 export type { ErrorBarConfigMixins } from './errorbar';
                                             ~~~~~~~~~~~~
../node_modules/vega-lite/build/src/index.d.ts:3:1 - error TS1128: Declaration or statement expected.

3 export type { Config } from './config';
  ~~~~~~
../node_modules/vega-lite/build/src/index.d.ts:3:13 - error TS1005: ';' expected.

3 export type { Config } from './config';
              ~
../node_modules/vega-lite/build/src/index.d.ts:3:29 - error TS1005: ';' expected.

3 export type { Config } from './config';
                              ~~~~~~~~~~
../node_modules/vega-lite/build/src/index.d.ts:5:1 - error TS1128: Declaration or statement expected.

5 export type { TopLevelSpec } from './spec';
  ~~~~~~
../node_modules/vega-lite/build/src/index.d.ts:5:13 - error TS1005: ';' expected.

5 export type { TopLevelSpec } from './spec';
              ~
../node_modules/vega-lite/build/src/index.d.ts:5:35 - error TS1005: ';' expected.

5 export type { TopLevelSpec } from './spec';
                                    ~~~~~~~~
../node_modules/vega-lite/build/src/normalize/base.d.ts:1:13 - error TS1005: '=' expected.

1 import type { SignalRef } from 'vega';
              ~
../node_modules/vega-lite/build/src/normalize/base.d.ts:[93m1:32 - error TS1005: ';' expected.

1 import type { SignalRef } from 'vega';
                                 ~~~~~~
../node_modules/vega-lite/build/src/normalize/index.d.ts:1:13 - error TS1005: '=' expected.

1 import type { SignalRef } from 'vega';
              ~
../node_modules/vega-lite/build/src/normalize/index.d.ts:1:32 - error TS1005: ';' expected.

1 import type { SignalRef } from 'vega';
                                 ~~~~~~
../node_modules/vega-lite/build/src/normalize/index.d.ts:13:1 - error TS1128: Declaration or statement expected.

13 export type { NormalizerParams };
   ~~~~~~
../node_modules/vega-lite/build/src/normalize/index.d.ts:13:13 - error TS1005: ';' expected.

13 export type { NormalizerParams };
               ~
../node_modules/vega-lite/build/src/predicate.d.ts:1:13 - error TS1005: '=' expected.

1 import type { SignalRef } from 'vega';
              ~
../node_modules/vega-lite/build/src/predicate.d.ts:1:32 - error TS1005: ';' expected.

1 import type { SignalRef } from 'vega';
                                 ~~~~~~
../node_modules/vega-lite/build/src/scale.d.ts:2:13 - error TS1005: '=' expected.

2 import type { ColorScheme } from 'vega-typings';
              ~
../node_modules/vega-lite/build/src/scale.d.ts:2:34 - error TS1005: ';' expected.

2 import type { ColorScheme } from 'vega-typings';
                                   ~~~~~~~~~~~~~~
../node_modules/vega-lite/build/src/spec/base.d.ts:10:1 - error TS1128: Declaration or statement expected.

10 export type { TopLevel } from './toplevel';
   ~~~~~~
../node_modules/vega-lite/build/src/spec/base.d.ts:10:13 - error TS1005: ';' expected.

10 export type { TopLevel } from './toplevel';
               ~
../node_modules/vega-lite/build/src/spec/base.d.ts:10:31 - error TS1005: ';' expected.

10 export type { TopLevel } from './toplevel';
                                 ~~~~~~~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:16:1 - error TS1128: Declaration or statement expected.

16 export type { BaseSpec, LayoutSizeMixins } from './base';
   ~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:16:13 - error TS1005: ';' expected.

16 export type { BaseSpec, LayoutSizeMixins } from './base';
               ~
../node_modules/vega-lite/build/src/spec/index.d.ts:16:49 - error TS1005: ';' expected.

16 export type { BaseSpec, LayoutSizeMixins } from './base';
                                                   ~~~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:17:1 - error TS1128: Declaration or statement expected.

17 export type { GenericHConcatSpec, GenericVConcatSpec, NormalizedConcatSpec } from './concat';
   ~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:17:13 - error TS1005: ';' expected.

17 export type { GenericHConcatSpec, GenericVConcatSpec, NormalizedConcatSpec } from './concat';
               ~
../node_modules/vega-lite/build/src/spec/index.d.ts:17:83 - error TS1005: ';' expected.

17 export type { GenericHConcatSpec, GenericVConcatSpec, NormalizedConcatSpec } from './concat';
                                                                                     ~~~~~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:19:1 - error TS1128: Declaration or statement expected.

19 export type { GenericFacetSpec, NormalizedFacetSpec } from './facet';
   ~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:19:13 - error TS1005: ';' expected.

19 export type { GenericFacetSpec, NormalizedFacetSpec } from './facet';
               ~
../node_modules/vega-lite/build/src/spec/index.d.ts:19:60 - error TS1005: ';' expected.

19 export type { GenericFacetSpec, NormalizedFacetSpec } from './facet';
                                                              ~~~~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:21:1 - error TS1128: Declaration or statement expected.

21 export type { GenericLayerSpec, LayerSpec, NormalizedLayerSpec } from './layer';
   ~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:21:13 - error TS1005: ';' expected.

21 export type { GenericLayerSpec, LayerSpec, NormalizedLayerSpec } from './layer';
               ~
../node_modules/vega-lite/build/src/spec/index.d.ts:21:71 - error TS1005: ';' expected.

21 export type { GenericLayerSpec, LayerSpec, NormalizedLayerSpec } from './layer';
                                                                         ~~~~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:23:1 - error TS1128: Declaration or statement expected.

23 export type { RepeatSpec } from './repeat';
   ~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:23:13 - error TS1005: ';' expected.

23 export type { RepeatSpec } from './repeat';
               ~
../node_modules/vega-lite/build/src/spec/index.d.ts:23:33 - error TS1005: ';' expected.

23 export type { RepeatSpec } from './repeat';
                                   ~~~~~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:25:1 - error TS1128: Declaration or statement expected.

25 export type { TopLevel } from './toplevel';
   ~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:25:13 - error TS1005: ';' expected.

25 export type { TopLevel } from './toplevel';
               ~
../node_modules/vega-lite/build/src/spec/index.d.ts:25:31 - error TS1005: ';' expected.

25 export type { TopLevel } from './toplevel';
                                 ~~~~~~~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:26:1 - error TS1128: Declaration or statement expected.

26 export type { FacetedUnitSpec, GenericUnitSpec, NormalizedUnitSpec, UnitSpec } from './unit';
   ~~~~~~
../node_modules/vega-lite/build/src/spec/index.d.ts:26:13 - error TS1005: ';' expected.

26 export type { FacetedUnitSpec, GenericUnitSpec, NormalizedUnitSpec, UnitSpec } from './unit';
               ~
../node_modules/vega-lite/build/src/spec/index.d.ts:26:85 - error TS1005: ';' expected.

26 export type { FacetedUnitSpec, GenericUnitSpec, NormalizedUnitSpec, UnitSpec } from './unit';
                                                                                       ~~~~~~~~
../node_modules/vega-lite/build/src/vega.schema.d.ts:1:13 - error TS1005: '=' expected.

1 import type { AggregateOp, BandScale, BaseScale, BinOrdinalScale, ColorValueRef, Compare as VgCompare, ExprRef as VgExprRef, GeoShapeTransform as VgGeoShapeTransform, IdentityScale, LayoutAlign, LinearScale, LogScale, Mark, MarkConfig, NumericValueRef, OrdinalScale, PointScale, PowScale, ProjectionType, QuantileScale, QuantizeScale, RangeBand, RangeRaw, RangeScheme, ScaleData, ScaleDataRef, ScaledValueRef, ScaleMultiDataRef, ScaleMultiFieldsRef, SequentialScale, SignalRef, SortField as VgSortField, SqrtScale, SymLogScale, ThresholdScale, TimeInterval, TimeIntervalStep, TimeScale, Title as VgTitle, Transforms as VgTransform, UnionSortField as VgUnionSortField } from 'vega';
              ~
../node_modules/vega-lite/build/src/vega.schema.d.ts:1:675 - error TS1005: ';' expected.

1 import type { AggregateOp, BandScale, BaseScale, BinOrdinalScale, ColorValueRef, Compare as VgCompare, ExprRef as VgExprRef, GeoShapeTransform as VgGeoShapeTransform, IdentityScale, LayoutAlign, LinearScale, LogScale, Mark, MarkConfig, NumericValueRef, OrdinalScale, PointScale, PowScale, ProjectionType, QuantileScale, QuantizeScale, RangeBand, RangeRaw, RangeScheme, ScaleData, ScaleDataRef, ScaledValueRef, ScaleMultiDataRef, ScaleMultiFieldsRef, SequentialScale, SignalRef, SortField as VgSortField, SqrtScale, SymLogScale, ThresholdScale, TimeInterval, TimeIntervalStep, TimeScale, Title as VgTitle, Transforms as VgTransform, UnionSortField as VgUnionSortField } from 'vega';
                                                                                                                                                          
                                                                                                                                                          
                                                                                                                                                          
                                                                                                                                                          
                                                            ~~~~~~
../node_modules/vega-lite/build/src/vega.schema.d.ts:6:1 - error TS1128: Declaration or statement expected.

6 export type { VgSortField, VgUnionSortField, VgCompare, VgTitle, LayoutAlign, ProjectionType, VgExprRef };
  ~~~~~~
../node_modules/vega-lite/build/src/vega.schema.d.ts:6:13 - error TS1005: ';' expected.

6 export type { VgSortField, VgUnionSortField, VgCompare, VgTitle, LayoutAlign, ProjectionType, VgExprRef };
              ~
../node_modules/vega-typings/types/runtime/runtime.d.ts:53:61 - error TS1110: Type expected.

53   data?: { [name: string]: ('input' | 'output' | 'values' | `index:${string}`)[] };
                                                               ~~~~~~~~~
../node_modules/vega-typings/types/runtime/runtime.d.ts:53:78 - error TS1005: ';' expected.

53   data?: { [name: string]: ('input' | 'output' | 'values' | `index:${string}`)[] };
                                                                                ~
../node_modules/vega-typings/types/runtime/runtime.d.ts:53:82 - error TS1128: Declaration or statement expected.

53   data?: { [name: string]: ('input' | 'output' | 'values' | `index:${string}`)[] };
                                                                                    ~
../node_modules/vega-typings/types/runtime/runtime.d.ts:57:10 - error TS1109: Expression expected.

57   parent?: OperatorParam;
            ~
../node_modules/vega-typings/types/runtime/runtime.d.ts:58:9 - error TS1109: Expression expected.

58   scale?: string;
           ~
../node_modules/vega-typings/types/runtime/runtime.d.ts:59:12 - error TS1109: Expression expected.

59   metadata?: { [k: string]: unknown };
              ~
../node_modules/vega-typings/types/runtime/runtime.d.ts:59:18 - error TS1005: ']' expected.

59   metadata?: { [k: string]: unknown };
                    ~
../node_modules/vega-typings/types/runtime/runtime.d.ts:59:26 - error TS1005: ',' expected.

59   metadata?: { [k: string]: unknown };
                            ~
../node_modules/vega-typings/types/runtime/runtime.d.ts:59:27 - error TS1136: Property assignment expected.

59   metadata?: { [k: string]: unknown };
                             ~
../node_modules/vega-typings/types/runtime/runtime.d.ts:68:9 - error TS1109: Expression expected.

68   react?: boolean;
           ~
../node_modules/vega-typings/types/runtime/runtime.d.ts:76:12 - error TS1109: Expression expected.

76   initonly?: boolean;
              ~
../node_modules/vega-typings/types/runtime/runtime.d.ts:77:1 - error TS1128: Declaration or statement expected.

77 }

**Comment by domoritz** [comment]
This is not the right place to ask about angular.
