### ISSUE TITLE
Kernel state is "Python 3 | Disconnected" after long time between ssh reconnections

### ISSUE THREAD

**Issue by mrvlasyuk** [jupyterlab/jupyterlab#9931]
## Description

JupyterLab is running on my server. I'm using ssh connection with port-forwarding. 
If ssh connection is broken for a long time (for a night) then kernel status became "Python 3 | Disconnected".
* Reload of notebook page helps. But because of many notebooks and plots it takes a long time, it resets Collapsible headings and pretty painful every morning.
* Restart kernel button works without reloading the page.

## Reproduce

1. Run JupyterLab on remote server
2. Connect to the server via ssh with port-forwarding.
3. Open JupyterLab page in browser.
4. Disconnect ssh for 8 hours (I don't know min time required to reproduce). Don't close Browser tab!
5. Connect to the server again.
6. Kernel won't reconnect. State is "Python 3 | Disconnected"

## Expected behavior

Kernel reconnects even after a long time disconnect.

## Context

- JupyterLab version: 3.0.10 (2.xx -- has the same issue)
- Browser: Chrome 88

**Comment by jasongrout** [comment]
There is a timeout and set number of retries for trying to automatically reconnect to a kernel. If you explicitly choose the "Kernel > Reconnect to Kernel", does it reconnect for you?

**Comment by mrvlasyuk** [comment]
It works! I've searched for this action in the menu several times but somehow missed it. Thanks a lot!
