### ISSUE TITLE
Allow code console to display input/output from kernel submitted by external client

### ISSUE THREAD

**Issue by atticusmatticus** [jupyterlab/jupyterlab#9936]
### Problem

I use the [jupyter-vim](https://github.com/jupyter-vim/jupyter-vim/) plugin which allows a jupyter notebook like experience where you can submit cells or lines of code within vim and have those run on the jupyter kernel and output to a `console` or `qtconsole`. 

Some output of libraries like fastai are designed to be run in a jupyter notebook-like environment because it outputs tables in HTML form. These objects don't display correctly in `console` or `qtconsole`, instead they are displayed as `<IPython.core.display.HTML object>`. 

I tried using a jupyter lab code console for my output window, which seems like the perfect solution. However, the code console doesn't show any output when code is sent to the kernel. So I opened an [issue with jupyter-vim](https://github.com/jupyter-vim/jupyter-vim/issues/58) but they said that the problem lies with the jupyter-vim code console allowing code sent to the kernel to display. Furthermore, they identified this line, https://github.com/jupyterlab/jupyterlab/blob/b4db7f03d2ad0b91a9c8c252c56ae5e4a9408fbb/packages/console/src/foreign.ts#L94, as the culprit for why this problem is occurring.

### Proposed Solution

Please allow for code sent to the jupyterlab kernel to display on the jupyterlab code console. I believe that this has something to do with this line of code:

https://github.com/jupyterlab/jupyterlab/blob/b4db7f03d2ad0b91a9c8c252c56ae5e4a9408fbb/packages/console/src/foreign.ts#L94

if there are questions regarding this please ask me or comment on [my jupyter-vim issue.](https://github.com/jupyter-vim/jupyter-vim/issues/58)

While Jupyter is an amazing tool I think that many of us prefer the vim/emacs editor experience, (that we have usually put a lot of time into customizing), for writing code and tools like jupyter-vim allow for the best of both of these worlds.

**Comment by jasongrout** [comment]
Does right-clicking on the console and selecting "Show all kernel activity" do what you want?
<img width="399" alt="Screen Shot 2021-03-12 at 1 57 15 PM" src="https://user-images.githubusercontent.com/192614/111002808-ec41a900-833a-11eb-8926-b373653462b8.png">

**Comment by atticusmatticus** [comment]
yes this does fix it! thank you so much
