### ISSUE TITLE
Message Jupyter lab

### ISSUE THREAD

**Issue by fabiopedroza** [jupyterlab/jupyterlab#9940]
I'm working with jupyter lab version Version 2.2.4 and today started giving the error below (print). What to do to fix?

![image](https://user-images.githubusercontent.com/59176849/111053190-5b54f580-8440-11eb-8d7f-bded9d59b9a2.png)
![message_jupyter](https://user-images.githubusercontent.com/59176849/111053269-29905e80-8441-11eb-98c4-8be6bf7af069.PNG)

**Comment by jasongrout** [comment]
Just curious: is this with a notebook from Colab? If so, then this is likely the same issue as reported in https://github.com/jupyterlab/jupyterlab/issues/9465. There are some workarounds mentioned in that issue for now.
