### ISSUE TITLE
Copy Shareable Link doesn't work if there is a space in the file name.

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab#9953]
## Description
Using copy shareable link will not generate a valid url when there is a space in the notebook name.

## Reproduce
1. Go to the ipywidgets binder: https://mybinder.org/v2/gh/jupyter-widgets/ipywidgets/7.x?urlpath=lab/tree/docs%2Fsource%2Fexamples?urlpath=lab
2. Open the file browser and copy a shareable link

![image](https://user-images.githubusercontent.com/10111092/111569488-26ff7300-8779-11eb-8c19-9c0df03a0967.png)

3. Paste the link into a new browser tab
4. See this error:
![image](https://user-images.githubusercontent.com/10111092/111569546-41395100-8779-11eb-8ab4-5f7f5301bf62.png)

The generated for me was: `https://hub.gke2.mybinder.org/user/jupyter-widgets-ipywidgets-ljukl42u/doc/tree/docs/source/examples/Widget%2520Alignment.ipynb`

## Expected behavior
The space in the notebook name is encoded as `%20` rather than `%2520` and the shareable link works.

## Context
Per https://stackoverflow.com/a/16085190/835607 this is due to the url being encoded multiple times.

- Operating System and version: Whatever binder is running - linux?
- Browser and version: Firefox
- JupyterLab version: 3.0.7 on binder

**Comment by jasongrout** [comment]
I think you are right. My guess is that encodeURI and either normalize or getURL are doing the url encoding, so we get a double encoding:

https://github.com/jupyterlab/jupyterlab/blob/60ccaf42ae31f52f7a26466e195d2096170d3069/packages/filebrowser-extension/src/index.ts#L436-L446

Probably take out the encodeURI?

**Comment by jasongrout** [comment]
Marking as a good first issue, but feel free to do it if you want too, @ianhi.

**Comment by jasongrout** [comment]
It looks like commit 0e1f5ebdfe2894fea8ea53d205c3f7000ce38673 in #8715 introduced the normalization, but didn't delete the encodeURI step.

**Comment by ianhi** [comment]
And `2.x` has it's own issues https://github.com/jupyterlab/jupyterlab/issues/9352 

I think that that commit was probably meant to fix that issue?

**Comment by ognjenjevremovic** [comment]
Hey @jasongrout 👋 

May I ask where the associated tests (for this functionality) are located?
I'd like to provide a PR for this issue, however I am not quite sure where the unit test should be added regarding this.
May you give some instructions?

Thanks! 🙂

**Comment by jasongrout** [comment]
Looks like we don't have tests for this (in general, the -extension packages should have end-to-end tests, which will be much easier as we start using the new Galata framework more).

**Comment by ognjenjevremovic** [comment]
Can you please guide me to some of the packages from within the project that contains the e2e tests which I can use as a reference?
If there's no support for e2e tests just yet, do you think just providing the fix (and testing it manually / locally) would be sufficient?

**Comment by jasongrout** [comment]
>  If there's no support for e2e tests just yet, do you think just providing the fix (and testing it manually / locally) would be sufficient?

Yes


> Can you please guide me to some of the packages from within the project that contains the e2e tests which I can use as a reference?

That's still a work-in-progress, IIRC, with the ongoing work around Galata. I don't think we have such tests yet.
