### ISSUE TITLE
Path Autocomplete broken when there is a space or @ in the path

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab#9957]
## Description
Autocompletion of a path when typing in a string is (an absolutely fantastic feature) not working when there is a space or an `@` symbol in the path name. It correctly picks up the part of the path with the offending character, but fails to find and any files in a directory containing those characters.

In the gif below I keep hitting tab and would expect `Untitled.txt` to be autocompleted.

![Peek 2021-03-18 13-41](https://user-images.githubusercontent.com/10111092/111672111-feff2680-87ef-11eb-8b28-de756fb4ec32.gif)

## Reproduce
1. Create a folder named `folder-with space` or `folder-with-@`
2. Put a file in that folder
3. Try to autocomplete a string to reference that file.

## Expected behavior
Autocomplete works like normal

## Context

- Operating System and version: Ubuntu 20.04
- Browser and version: Firefox 81
- JupyterLab version: 3.0.11

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/ian/.local/bin
	/home/ian/mambaforge/envs/jlab-test/bin
	/home/ian/mambaforge/condabin
	/home/ian/.local/bin
	/home/ian/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin
	/home/ian/opt
	/home/ian/bin

sys.path:
	/home/ian/mambaforge/envs/jlab-test/bin
	/home/ian/mambaforge/envs/jlab-test/lib/python38.zip
	/home/ian/mambaforge/envs/jlab-test/lib/python3.8
	/home/ian/mambaforge/envs/jlab-test/lib/python3.8/lib-dynload
	/home/ian/mambaforge/envs/jlab-test/lib/python3.8/site-packages

sys.executable:
	/home/ian/mambaforge/envs/jlab-test/bin/python

sys.version:
	3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
	[GCC 9.3.0]

platform.platform():
	Linux-5.8.0-7630-generic-x86_64-with-glibc2.10

which -a jupyter:
	/home/ian/mambaforge/envs/jlab-test/bin/jupyter

pip list:
	Package                       Version
	----------------------------- -------------------
	anyio                         2.2.0
	argon2-cffi                   20.1.0
	async-generator               1.10
	attrs                         20.3.0
	Babel                         2.9.0
	backcall                      0.2.0
	backports.functools-lru-cache 1.6.1
	bleach                        3.3.0
	brotlipy                      0.7.0
	certifi                       2020.12.5
	cffi                          1.14.5
	chardet                       4.0.0
	cryptography                  3.4.6
	decorator                     4.4.2
	defusedxml                    0.7.1
	entrypoints                   0.3
	idna                          2.10
	importlib-metadata            3.7.3
	ipykernel                     5.5.0
	ipython                       7.21.0
	ipython-genutils              0.2.0
	jedi                          0.18.0
	Jinja2                        2.11.3
	json5                         0.9.5
	jsonschema                    3.2.0
	jupyter-client                6.1.12
	jupyter-core                  4.7.1
	jupyter-packaging             0.7.12
	jupyter-server                1.4.1
	jupyterlab                    3.0.11
	jupyterlab-pygments           0.1.2
	jupyterlab-server             2.3.0
	MarkupSafe                    1.1.1
	mistune                       0.8.4
	nbclassic                     0.2.6
	nbclient                      0.5.3
	nbconvert                     6.0.7
	nbformat                      5.1.2
	nest-asyncio                  1.4.3
	notebook                      6.2.0
	packaging                     20.9
	pandocfilters                 1.4.2
	parso                         0.8.1
	pexpect                       4.8.0
	pickleshare                   0.7.5
	pip                           21.0.1
	prometheus-client             0.9.0
	prompt-toolkit                3.0.17
	ptyprocess                    0.7.0
	pycparser                     2.20
	Pygments                      2.8.1
	pyOpenSSL                     20.0.1
	pyparsing                     2.4.7
	pyrsistent                    0.17.3
	PySocks                       1.7.1
	python-dateutil               2.8.1
	pytz                          2021.1
	pyzmq                         22.0.3
	requests                      2.25.1
	Send2Trash                    1.5.0
	setuptools                    49.6.0.post20210108
	six                           1.15.0
	sniffio                       1.2.0
	terminado                     0.9.3
	testpath                      0.4.4
	tornado                       6.1
	traitlets                     5.0.5
	urllib3                       1.26.4
	wcwidth                       0.2.5
	webencodings                  0.5.1
	wheel                         0.36.2
	zipp                          3.4.1

conda list:
	# packages in environment at /home/ian/mambaforge/envs/jlab-test:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                 conda_forge    conda-forge
	_openmp_mutex             4.5                       1_gnu    conda-forge
	anyio                     2.2.0            py38h578d9bd_0    conda-forge
	argon2-cffi               20.1.0           py38h497a2fe_2    conda-forge
	async_generator           1.10                       py_0    conda-forge
	attrs                     20.3.0             pyhd3deb0d_0    conda-forge
	babel                     2.9.0              pyhd3deb0d_0    conda-forge
	backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
	backports                 1.0                        py_2    conda-forge
	backports.functools_lru_cache 1.6.1                      py_0    conda-forge
	bleach                    3.3.0              pyh44b312d_0    conda-forge
	brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
	ca-certificates           2020.12.5            ha878542_0    conda-forge
	certifi                   2020.12.5        py38h578d9bd_1    conda-forge
	cffi                      1.14.5           py38ha65f79e_0    conda-forge
	chardet                   4.0.0            py38h578d9bd_1    conda-forge
	cryptography              3.4.6            py38ha5dfef3_0    conda-forge
	decorator                 4.4.2                      py_0    conda-forge
	defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
	entrypoints               0.3             py38h32f6830_1002    conda-forge
	idna                      2.10               pyh9f0ad1d_0    conda-forge
	importlib-metadata        3.7.3            py38h578d9bd_0    conda-forge
	importlib_metadata        3.7.3                hd8ed1ab_0    conda-forge
	ipykernel                 5.5.0            py38h81c977d_1    conda-forge
	ipython                   7.21.0           py38h81c977d_0    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	jedi                      0.18.0           py38h578d9bd_2    conda-forge
	jinja2                    2.11.3             pyh44b312d_0    conda-forge
	json5                     0.9.5              pyh9f0ad1d_0    conda-forge
	jsonschema                3.2.0            py38h32f6830_1    conda-forge
	jupyter-packaging         0.7.12             pyhd8ed1ab_0    conda-forge
	jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
	jupyter_core              4.7.1            py38h578d9bd_0    conda-forge
	jupyter_server            1.4.1            py38h578d9bd_0    conda-forge
	jupyterlab                3.0.11             pyhd8ed1ab_0    conda-forge
	jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
	jupyterlab_server         2.3.0              pyhd8ed1ab_0    conda-forge
	ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
	libffi                    3.3                  h58526e2_2    conda-forge
	libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
	libgomp                   9.3.0               h2828fa1_18    conda-forge
	libsodium                 1.0.18               h516909a_1    conda-forge
	libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
	markupsafe                1.1.1            py38h497a2fe_3    conda-forge
	mistune                   0.8.4           py38h497a2fe_1003    conda-forge
	nbclassic                 0.2.6              pyhd8ed1ab_0    conda-forge
	nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
	nbconvert                 6.0.7            py38h578d9bd_3    conda-forge
	nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
	ncurses                   6.2                  h58526e2_4    conda-forge
	nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
	notebook                  6.2.0            py38h578d9bd_0    conda-forge
	openssl                   1.1.1j               h7f98852_0    conda-forge
	packaging                 20.9               pyh44b312d_0    conda-forge
	pandoc                    2.12                 h7f98852_0    conda-forge
	pandocfilters             1.4.2                      py_1    conda-forge
	parso                     0.8.1              pyhd8ed1ab_0    conda-forge
	pexpect                   4.8.0            py38h32f6830_1    conda-forge
	pickleshare               0.7.5           py38h32f6830_1002    conda-forge
	pip                       21.0.1             pyhd8ed1ab_0    conda-forge
	prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
	prompt-toolkit            3.0.17             pyha770c72_0    conda-forge
	ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
	pycparser                 2.20               pyh9f0ad1d_2    conda-forge
	pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
	pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
	pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
	pyrsistent                0.17.3           py38h497a2fe_2    conda-forge
	pysocks                   1.7.1            py38h578d9bd_3    conda-forge
	python                    3.8.8           hffdb5ce_0_cpython    conda-forge
	python-dateutil           2.8.1                      py_0    conda-forge
	python_abi                3.8                      1_cp38    conda-forge
	pytz                      2021.1             pyhd8ed1ab_0    conda-forge
	pyzmq                     22.0.3           py38h2035c66_1    conda-forge
	readline                  8.0                  he28a2e2_2    conda-forge
	requests                  2.25.1             pyhd3deb0d_0    conda-forge
	send2trash                1.5.0                      py_0    conda-forge
	setuptools                49.6.0           py38h578d9bd_3    conda-forge
	six                       1.15.0             pyh9f0ad1d_0    conda-forge
	sniffio                   1.2.0            py38h578d9bd_1    conda-forge
	sqlite                    3.34.0               h74cdb3f_0    conda-forge
	terminado                 0.9.3            py38h578d9bd_0    conda-forge
	testpath                  0.4.4                      py_0    conda-forge
	tk                        8.6.10               hed695b0_1    conda-forge
	tornado                   6.1              py38h497a2fe_1    conda-forge
	traitlets                 5.0.5                      py_0    conda-forge
	urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
	wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
	webencodings              0.5.1                      py_1    conda-forge
	wheel                     0.36.2             pyhd3deb0d_0    conda-forge
	xz                        5.2.5                h516909a_1    conda-forge
	zeromq                    4.3.4                h9c3ff4c_0    conda-forge
	zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
	zlib                      1.2.11            h516909a_1010    conda-forge

conda env:
	name: jlab-test
	channels:
	  - conda-forge
	  - defaults
	dependencies:
	  - _libgcc_mutex=0.1=conda_forge
	  - _openmp_mutex=4.5=1_gnu
	  - anyio=2.2.0=py38h578d9bd_0
	  - argon2-cffi=20.1.0=py38h497a2fe_2
	  - async_generator=1.10=py_0
	  - attrs=20.3.0=pyhd3deb0d_0
	  - babel=2.9.0=pyhd3deb0d_0
	  - backcall=0.2.0=pyh9f0ad1d_0
	  - backports=1.0=py_2
	  - backports.functools_lru_cache=1.6.1=py_0
	  - bleach=3.3.0=pyh44b312d_0
	  - brotlipy=0.7.0=py38h497a2fe_1001
	  - ca-certificates=2020.12.5=ha878542_0
	  - certifi=2020.12.5=py38h578d9bd_1
	  - cffi=1.14.5=py38ha65f79e_0
	  - chardet=4.0.0=py38h578d9bd_1
	  - cryptography=3.4.6=py38ha5dfef3_0
	  - decorator=4.4.2=py_0
	  - defusedxml=0.7.1=pyhd8ed1ab_0
	  - entrypoints=0.3=py38h32f6830_1002
	  - idna=2.10=pyh9f0ad1d_0
	  - importlib-metadata=3.7.3=py38h578d9bd_0
	  - importlib_metadata=3.7.3=hd8ed1ab_0
	  - ipykernel=5.5.0=py38h81c977d_1
	  - ipython=7.21.0=py38h81c977d_0
	  - ipython_genutils=0.2.0=py_1
	  - jedi=0.18.0=py38h578d9bd_2
	  - jinja2=2.11.3=pyh44b312d_0
	  - json5=0.9.5=pyh9f0ad1d_0
	  - jsonschema=3.2.0=py38h32f6830_1
	  - jupyter-packaging=0.7.12=pyhd8ed1ab_0
	  - jupyter_client=6.1.12=pyhd8ed1ab_0
	  - jupyter_core=4.7.1=py38h578d9bd_0
	  - jupyter_server=1.4.1=py38h578d9bd_0
	  - jupyterlab=3.0.11=pyhd8ed1ab_0
	  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
	  - jupyterlab_server=2.3.0=pyhd8ed1ab_0
	  - ld_impl_linux-64=2.35.1=hea4e1c9_2
	  - libffi=3.3=h58526e2_2
	  - libgcc-ng=9.3.0=h2828fa1_18
	  - libgomp=9.3.0=h2828fa1_18
	  - libsodium=1.0.18=h516909a_1
	  - libstdcxx-ng=9.3.0=h6de172a_18
	  - markupsafe=1.1.1=py38h497a2fe_3
	  - mistune=0.8.4=py38h497a2fe_1003
	  - nbclassic=0.2.6=pyhd8ed1ab_0
	  - nbclient=0.5.3=pyhd8ed1ab_0
	  - nbconvert=6.0.7=py38h578d9bd_3
	  - nbformat=5.1.2=pyhd8ed1ab_1
	  - ncurses=6.2=h58526e2_4
	  - nest-asyncio=1.4.3=pyhd8ed1ab_0
	  - notebook=6.2.0=py38h578d9bd_0
	  - openssl=1.1.1j=h7f98852_0
	  - packaging=20.9=pyh44b312d_0
	  - pandoc=2.12=h7f98852_0
	  - pandocfilters=1.4.2=py_1
	  - parso=0.8.1=pyhd8ed1ab_0
	  - pexpect=4.8.0=py38h32f6830_1
	  - pickleshare=0.7.5=py38h32f6830_1002
	  - pip=21.0.1=pyhd8ed1ab_0
	  - prometheus_client=0.9.0=pyhd3deb0d_0
	  - prompt-toolkit=3.0.17=pyha770c72_0
	  - ptyprocess=0.7.0=pyhd3deb0d_0
	  - pycparser=2.20=pyh9f0ad1d_2
	  - pygments=2.8.1=pyhd8ed1ab_0
	  - pyopenssl=20.0.1=pyhd8ed1ab_0
	  - pyparsing=2.4.7=pyh9f0ad1d_0
	  - pyrsistent=0.17.3=py38h497a2fe_2
	  - pysocks=1.7.1=py38h578d9bd_3
	  - python=3.8.8=hffdb5ce_0_cpython
	  - python-dateutil=2.8.1=py_0
	  - python_abi=3.8=1_cp38
	  - pytz=2021.1=pyhd8ed1ab_0
	  - pyzmq=22.0.3=py38h2035c66_1
	  - readline=8.0=he28a2e2_2
	  - requests=2.25.1=pyhd3deb0d_0
	  - send2trash=1.5.0=py_0
	  - setuptools=49.6.0=py38h578d9bd_3
	  - six=1.15.0=pyh9f0ad1d_0
	  - sniffio=1.2.0=py38h578d9bd_1
	  - sqlite=3.34.0=h74cdb3f_0
	  - terminado=0.9.3=py38h578d9bd_0
	  - testpath=0.4.4=py_0
	  - tk=8.6.10=hed695b0_1
	  - tornado=6.1=py38h497a2fe_1
	  - traitlets=5.0.5=py_0
	  - urllib3=1.26.4=pyhd8ed1ab_0
	  - wcwidth=0.2.5=pyh9f0ad1d_2
	  - webencodings=0.5.1=py_1
	  - wheel=0.36.2=pyhd3deb0d_0
	  - xz=5.2.5=h516909a_1
	  - zeromq=4.3.4=h9c3ff4c_0
	  - zipp=3.4.1=pyhd8ed1ab_0
	  - zlib=1.2.11=h516909a_1010
	prefix: /home/ian/mambaforge/envs/jlab-test
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
None
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
None
</pre>
</details>

**Comment by jasongrout** [comment]
Completions are handled by your kernel, in this case probably IPython, so that is the place to file this. I think this may be tracked in one or more of the following issues:
https://github.com/ipython/ipython/issues/9316
https://github.com/ipython/ipython/issues/4519
https://github.com/ipython/ipython/issues/2463
maybe https://github.com/ipython/ipython/issues/2657 also?

If one of those issues does not cover your situation, can you open a new issue in the IPython repo?
