### ISSUE TITLE
Improve Filebrowser Context Menu order

### ISSUE THREAD

**Issue by ianhi** [jupyterlab/jupyterlab#9960]
### Problem

The current options for the filebrowser are not always logically grouped. I also think that the order of the current logical groups could be improved.

Currently the order is:

![image](https://user-images.githubusercontent.com/10111092/111714189-86b45780-8827-11eb-912e-22c0e29283a7.png)

### Proposed Solution

1. Move `Paste` up be near `Delete`, `Cut` etc..
2. Swap `Download` and `Shutdown Kernel`
     - Download feels logical to group with with copy shareable link and copy download link
2. Move the `New ___` operations above the link sharing commands. I suspect that the `New` items are far more fequently used than things like `Copy Shareable Link`

It might also be nice to visually delineate these logical groupings with a small gray line like is done in the menus from the topbar
![image](https://user-images.githubusercontent.com/10111092/111714444-093d1700-8828-11eb-8e51-5a32d224a481.png)

**Comment by ianhi** [comment]
Also ideally the `Shut Down kernel` option would not be in the menu when you click on items that do not support a kernel. Currently it shows up for any file type.

**Comment by jtpio** [comment]
> Also ideally the `Shut Down kernel` option would not be in the menu when you click on items that do not support a kernel. Currently it shows up for any file type.

It might be possible to add the `isVisibile` field to the corresponding command here to hide the entry depending on the items in the current selection:

https://github.com/jupyterlab/jupyterlab/blob/60ccaf42ae31f52f7a26466e195d2096170d3069/packages/filebrowser-extension/src/index.ts#L862-L872

**Comment by jtpio** [comment]
@ianhi is this still an issue, now that the context menu has been improved in the latest versions?

![image](https://user-images.githubusercontent.com/591645/139735181-4c3e6d20-e285-42f7-8acc-a252d1c5cb78.png)

Also the context menu can now be configured via the settings:

https://jupyterlab.readthedocs.io/en/stable/extension/extension_points.html?#context-menu

> Also ideally the `Shut Down kernel` option would not be in the menu when you click on items that do not support a kernel. Currently it shows up for any file type.

This one is still relevant but could be tracked in a separate issue.

**Comment by ianhi** [comment]
Much improved! 

> This one is still relevant but could be tracked in a separate issue.

:+1:

**Comment by jasongrout** [comment]
I also notice Paste is still down at the bottom. It looks like the rationale is that the bottom section is for things that create files, but I do agree that Paste is more typically found up with cut and copy.

**Comment by ianhi** [comment]
> I also notice Paste is still down at the bottom. 

ohhh I missed that. I think that was my main concern when opening this issue. (I shouldn't be closing issues after midnight...)

I'll reopen this then, but if it's decided that `Paste` should stay down there then closing is ok with me

**Comment by fcollonval** [comment]
Closing as _Paste_ is next to copy and cut since 

![image](https://user-images.githubusercontent.com/8435071/151026406-602de0bf-ced0-4144-b602-4cc3bae4338a.png)
