### ISSUE TITLE
3.0.11 broken on Safari, due to lookbehind regex introduced in PR #9938 / #9943

### ISSUE THREAD

**Issue by dge8** [jupyterlab/jupyterlab#9961]
## Description

jupyterlab fails to load on Safari 14.0.3. Reverting pull #9943 solves the issue.

According to [https://caniuse.com/js-regexp-lookbehind](https://caniuse.com/js-regexp-lookbehind) the Javascript regex lookbehind is not supported in any version of Safari.

## Reproduce

1. Start jupyterlab.
2. Does not load in Safari (blank white screen). Console shows error "Invalid regular expression: invalid group specifier name".

## Context

- Operating System and version: macOS 10.15.7 19H524
- Browser and version: Safari 14.0.3
- JupyterLab version: 3.0.11 installed via Homebrew

[Edit 1]: Relevant StackOverflow Q: [https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group/51568859](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group/51568859)

[Edit 2]: Ping to PR #9938

**Comment by dge8** [comment]
@meeseeksdev tag "type:Bug"

**Comment by tomigee** [comment]
Oh thank god someone else is getting the same issue as I am. My context details are as follows:

- OS: macOS Big Sur 11.2.1
- Browser and version: Safari 14.0.3
- Jupyter Lab version: 3.0.11
