### ISSUE TITLE
One extensions to depend on other extension.

### ISSUE THREAD

**Issue by m0hit-aggarwal** [jupyterlab/jupyterlab#9964]
### Problem
Hi,
I have an extension A that implements some functionality. I want to reuse that functionality in an extension B instead of having to rewrite the same code in extension B. Is it it possible for one extension to "depend" on another extension ? Further is it possible for that when one is installed the other is also installed ?

**Comment by bollwyvl** [comment]
Yes, this works for both JupyterLab 2 (everything gets built together in the deployed environment) as well as JupyterLab 3 (where they can be installed/updataed independently and interactively). A read-through of the [official documentation](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#plugins-interacting-with-each-other) is recommended.

In a nutshell, for you:
- in js:
  - add `@extension/b` to the `dependencies` of `@extension/a`
  - in `@extension/a` you would `import {thing_you_want} from `@extensions/b`
- in 3
  - in js:
    - ensure whatever is reused is exposed in the `main` from `package.json` (conventionally `lib/index.js`)
  - in python:
    - release and specify the dependency in `extension_a` on `extension_b` in `setup.(py|cfg)` or `project.toml`

For your users:
- In 2:
  - the end user _must_ explicitly install both extensions
- In 3:
  - the end user would install both extensions from pypi

Some other approaches:
- use "loose" coupling mechanisms like commands
- make a third package (not an extension) that both of the packages have in their `dependencies`
  - in lab 3, you'd need to add this new package to `sharedPackages`

**Comment by jtpio** [comment]
And to provide a concrete example for one way to this, you might want to have a look at the [`jupyterlab-topbar`](https://github.com/jtpio/jupyterlab-topbar) and [`jupyterlab-system-monitor`](https://github.com/jtpio/jupyterlab-system-monitor) prebuilt extensions for JupyterLab 3.0, sharring a common token provided in another package:

1. `jupyterlab-topbar` exposes its functionality in a plugin [here](https://github.com/jtpio/jupyterlab-topbar/blob/4dc23fc4c6244fe924cc3885254aa57ca955f321/packages/jupyterlab-topbar-extension/src/index.ts#L26)
2. the `jupyterlab-topbar` extension exposes the shared package `jupyterlab-topbar` [here](https://github.com/jtpio/jupyterlab-topbar/blob/4dc23fc4c6244fe924cc3885254aa57ca955f321/packages/jupyterlab-topbar-extension/package.json#L62-L68)
3. `jupyterlab-system-monitor` depends on `jupyterlab-topbar` [here](https://github.com/jtpio/jupyterlab-system-monitor/blob/a05a27d4d5be23259a14272f455b621d705b7d89/setup.py#L70) to add indicators to the top area space exposed by `jupyterlab-topbar`
4. `jupyterlab-system-monitor` expects to find `jupyterlab-topbar` [here](https://github.com/jtpio/jupyterlab-system-monitor/blob/a05a27d4d5be23259a14272f455b621d705b7d89/packages/system-monitor/package.json#L72-L77), to be able to use it [here](https://github.com/jtpio/jupyterlab-system-monitor/blob/a05a27d4d5be23259a14272f455b621d705b7d89/packages/system-monitor/src/index.ts#L50)

**Comment by m0hit-aggarwal** [comment]
Hi 
@jtpio and @bollwyvl that was really helpful.
Thanks for the help.
