### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by charelstoncrabb** [jupyterlab/jupyterlab#9979]
I love the jupyterlab webapp, but the light theme gives me a headache while marathon coding, and the dark theme hurts my eyes bc of too high contrast.  I also love atom and their [themes and customizability](https://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/), but overall it doesn't even nearly match the wonderful python development workflow enablement from the lab.

Customizable themes or even just more darker/low-contrast themes would be amaaaaazing.

**Comment by jasongrout** [comment]
> I love the jupyterlab webapp

Thanks!

There are plenty of other themes available for JupyterLab (I did a quick search for "jupyterlab theme" on npm and got tons of packages that claimed to be jlab themes). Or make one yourself from the [cookiecutter](https://github.com/jupyterlab/theme-cookiecutter).

**Comment by jasongrout** [comment]
Or maybe even easier, you can search "theme" in the Extension manager and see lots of packages with that keyword.

**Comment by charelstoncrabb** [comment]
Thanks!
