### ISSUE TITLE
JupyterLab 3.0.12 not working with Safari.

### ISSUE THREAD

**Issue by cf250024** [jupyterlab/jupyterlab#9985]
I installed JupyterLab 3.0.12 with clean conda env and tested with Safari (Version 13.1.3 (15609.4.1). It seems JupyterLab has trouble to connect to kernel with error messages. It works fine with Chrome and Firefox. 

The error messages are show in screen shot below once trying to switch kernel from No Kernel to Python 3.

<img width="1417" alt="Screen Shot 2021-03-23 at 1 09 46 PM" src="https://user-images.githubusercontent.com/59401847/112211526-3cd9c180-8bd9-11eb-8b7b-18b8e5b3c066.png">

**Comment by jasongrout** [comment]
I tested Safari 13.1.2 on macOS High Sierra, as well as Safari 14.0.3 on macoS Catalina, and a clean install of only `jupyterlab` evaluating in the python kernel seems to work okay.

Can you post more details about your setup to reproduce this, with maybe step-by-step instructions for creating a new environment demonstrating the problem? For example, it looks like it says "No Kernel" in your notebook and your syntax doesn't seem to be python.

**Comment by jasongrout** [comment]
It does seem like googling for that error "ReadableStream uploading is not supported" yields lots of possible things that could cause this in Safari.

**Comment by cf250024** [comment]
It seems working at first for me. But the error message shows up when I switch the kernel between python and no kernel. Is Safari console clean without errors for you as well ? My macOS is Catalina version 10.15.7.

**Comment by jasongrout** [comment]
I tried in both Safari 13 and 14, creating a new notebook with no kernel, then switching to the python kernel (and back again), and things seemed to work just fine and I had no errors in the js console log.

Can you give step-by-step instructions for installing your clean environment and exactly what you are clicking on to show the error?

**Comment by cf250024** [comment]
Thanks, @jasongrout. Here is what I followed as you suggested:
https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html.

1. conda create -n jlab-test --override-channels --strict-channel-priority -c conda-forge -c anaconda jupyterlab
2. conda activate jlab-test
3. jupyter lab
4. Check jupyter lab version with "About Jupyter Lab" (version 3.0.12.)
4. When I try to open "Python 3" button from Launcher, it gives error popup "ReadableStream uploading is not supported".
5. Then I open empty "Untitled.ipynb" created with Chrome, I saw the error again.
6. Then I try to switch kernel. If I choose kernel "Python 3", the error shows up.

I guess some packages may be different between our environments. 
I tried two MacOS and the same error shows up on my both machines. However Jupyter lab works for Chrome and Firefox on both my machines but not Safari.  

jupyter_core              4.7.1
jupyter_server            1.4.1
jupyterlab_server         2.3.0

**Comment by bollwyvl** [comment]
Is this an m1?

Also try without `anaconda`... you won't be missing anything, and their stuff lags behind `conda-forge`, which we actively participate in maintaining.

**Comment by cf250024** [comment]
I encountered this issue without conda at the beginning. Here is my pip env. Somehow I have this issue persistently on my env. Thanks.

$ pip list | grep jupyter
jupyter-client      6.1.11
jupyter-core        4.7.0
jupyter-packaging   0.7.11
jupyter-server      1.4.1
jupyterlab          3.0.12
jupyterlab-pygments 0.1.1
jupyterlab-server   2.3.0
