### ISSUE TITLE
Approach to bundle custom JupyterLab 

### ISSUE THREAD

**Issue by m0hit-aggarwal** [jupyterlab/jupyterlab#9986]
### Problem
I have this use case where I want to make changes to one of the packages say @jupyterlab/apputils or @jupyterlab/services.
I have tested out my changes are working fine using the dev mode. Now I want to package jupyterlab with my version of @jupyterlab/apputils so that it can be distributed. Is there some preferred approach to achieve this ? Is it possible to uninstall default @jupyterlab/apputils and install my version from directory path and package it ?

**Comment by bollwyvl** [comment]
As long is it's not something that's instantiated _directly_ by core (e.g. `@jupyterlab/services`) the dependency injections machinery does what you need, cleanly... this might not be the case for parts of `apputils`, however.

From [the docs](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#disabling-other-extensions), in your `package.json` you can provide:

```yaml
"jupyterlab": {
  "disabledExtensions": ["@jupyterlab/apputils:some-plugin"]
}
```

If you need to change something directly... monkeypatching is the only _simple_ way to ship something that can be upgraded by end users.

At release time, the `package.json` and `yarn.lock` that are in `jupyterlab/staging` and `jupyterlab/static` are what are copied to `$SHARE`, and rely on the _public_ packages being available.

If you're shipping a _product_, and don't care/allow your users to install extensions, you can just run a `dev:build:prod`, and copy the goods from `dev_mode` right into `../jupyterlab/static` and (by extension) `$PREFIX/share/jupyter/lab/static`. You'd then need to publish your project under a different name, but it works, and will likely _keep_ working, with the federated extension machinery.

**Comment by jasongrout** [comment]
FYI: the instructions we use to package JupyterLab officially are in https://github.com/jupyterlab/jupyterlab/blob/master/RELEASE.md.
