### ISSUE TITLE
Setting dark theme before first run

### ISSUE THREAD

**Issue by rijobro** [jupyterlab/jupyterlab#9988]
## Description

I'm struggling to set the jupyter lab theme prior to first load. I don't mind if this is done via config files or passing command line argument when starting the notebook.

Perhaps this is obvious, but I can't see it documented.

## Reproduce

Fresh jupyter lab install:
```
jupyter lab --generate-config
mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/
echo '{ "theme":"JupyterLab Dark" }' > themes.jupyterlab-settings
```

To no effect, I also tried as described in the readthedocs: https://jupyterlab.readthedocs.io/en/stable/user/directories.html?#advanced-usage:

```bash
mkdir -p ~/.local/share/jupyter/lab/settings
cat > ~/.local/share/jupyter/lab/settings/overrides.json<< EOF
{
  "@jupyterlab/apputils-extension:themes": {
    "theme": "JupyterLab Dark"
  }
}
EOF
```

## Expected behavior

Jupyter lab loads in dark mode.

**Comment by jasongrout** [comment]
You can use the settings overrides file to give new system-wide defaults. See the example at https://jupyterlab.readthedocs.io/en/stable/user/directories.html#overridesjson

**Comment by jasongrout** [comment]
> You can use the settings overrides file to give new system-wide defaults. See the example at https://jupyterlab.readthedocs.io/en/stable/user/directories.html#overridesjson

Sorry, I missed that you already tried that. To find the right directory, do `jupyter lab path` and use the Application directory, usually `<sys.prefix>/share/jupyter/lab/settings/overrides.json`

**Comment by rijobro** [comment]
@jasongrout thanks for getting back to me. I tried using `jupyter lab path`, have I taken the wrong `sys.prefix` from it?

```
➜  ~ jupyter lab path
Application directory:   /usr/local/share/jupyter/lab
User Settings directory: /Users/rich/.jupyter/lab/user-settings
Workspaces directory: /Users/rich/.jupyter/lab/workspaces

➜  ~ cat ~/local/share/jupyter/lab/settings/overrides.json
{
  "@jupyterlab/apputils-extension:themes": {
    "theme": "JupyterLab Dark"
  }
}
```
When I run jupyter lab using the above, it still loads in light mode.

**Comment by jasongrout** [comment]
The Application directory is `/usr/local/share/jupyter/lab`, so the system settings directory is `/usr/local/share/jupyter/lab/settings` - write your overrides.json file there.

**Comment by jasongrout** [comment]
I tried to clarify where this file is over in https://github.com/jupyterlab/jupyterlab/pull/9989

**Comment by rijobro** [comment]
Thanks, it turns out I was being careless and modifying inside of `~/local` when I should have been modifying inside of `/usr/local`.
