### ISSUE TITLE
Can't interrupt kernel in a remote Windows session via Mac Chrome

### ISSUE THREAD

**Issue by guillochon** [jupyterlab/jupyterlab#9991]
## Reproduce

1. Start `jupyter lab` on a Windows machine.
2. `ssh` into Windows machine hosting Jupyter, forward port 8888 -> 8889 via a `LocalForward` directive in `.ssh/config`.
3. Browse to `localhost:8889` on the local machine (I used a Mac, not sure if it's specific to the Windows/Mac combo).
4. In a new notebook, paste the following code in a cell and execute it:
    ```
    import time

    for i in range(10):
        time.sleep(1)
    ```
    The above is just MWE code, I see the same behavior with my own code and large packages like `pytorch`, etc.
5. Attempt to interrupt the calculation using the "stop" button, or by pressing `i,i`.
6. Calculation is not interrupted. Only indication that the interruption was processed is a message like `[I 2021-03-23 06:49:56.297 ServerApp] Kernel interrupted: b6aa6f89-f96b-47c3-8e1e-868c0f9f00a7`, but the calculation continues unabated until 10 seconds have elapsed.

## Expected behavior

Jupyter calculations should be interrupted.

## Context

- Operating System and version: Windows 10 (19041.867)
- Browser and version: Chrome 89.0.4389.82 (Mac)
- JupyterLab version: 3.0.12

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        C:\Program Files\ArcGIS\Pro\bin
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\Library\mingw-w64\bin
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\Library\usr\bin
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\Library\bin
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\Scripts
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\bin
        C:\Program Files\ArcGIS\Pro\bin\Python\condabin
        C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin
        C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\libnvvp
        C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin
        C:\Python38\Scripts
        C:\Python38
        C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin
        C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp
        C:\Program Files\ImageMagick-7.0.8-Q16
        C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS
        C:\windows\system32
        C:\windows
        C:\windows\System32\Wbem
        C:\windows\System32\WindowsPowerShell\v1.0
        C:\Program Files\dotnet
        C:\Program Files\Git\cmd
        C:\software\cmake-3.13.4-win64-x64\bin
        C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
        C:\Program Files\Amazon\AWSCLIV2
        C:\ProgramData\chocolatey\bin
        C:\Go\bin
        C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
        C:\Program Files\Docker\Docker\resources\bin
        C:\ProgramData\DockerDesktop\version-bin
        C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
        C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0
        C:\WINDOWS\System32\OpenSSH
        C:\Program Files\NVIDIA Corporation\Nsight Compute 2020.3.1
        C:\Users\jam11491\AppData\Local\Microsoft\WindowsApps
        C:\Program Files\ArcGIS\Pro\bin\Python\Scripts

sys.path:
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\Scripts
        C:\Program Files\ArcGIS\Pro\Resources\ArcPy
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\python37.zip
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\DLLs
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\lib
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning
        C:\Users\jam11491\AppData\Roaming\Python\Python37\site-packages
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\lib\site-packages
        C:\Program Files\ArcGIS\Pro\bin
        C:\Program Files\ArcGIS\Pro\Resources\ArcToolbox\Scripts
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\lib\site-packages\future-0.18.2-py3.7.egg
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\lib\site-packages\pytz-2020.1-py3.7.egg
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\lib\site-packages\win32
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\lib\site-packages\win32\lib
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\lib\site-packages\Pythonwin
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\lib\site-packages\pywin32_ctypes-0.2.0-py3.7.egg
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\lib\site-packages\pywin32security
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\lib\site-packages\sympy-1.5.1-py3.7.egg

sys.executable:
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\python.exe

sys.version:
        3.7.9 [MSC v.1922 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.19041-SP0

where jupyter:
        C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning\Scripts\jupyter.exe

pip list:
        Package                           Version
        --------------------------------- -------------------
        -orch                             1.7.0
        absl-py                           0.11.0
        aiohttp                           3.6.3
        anyio                             2.2.0
        appdirs                           1.4.4
        arcgis                            1.8.3
        argon2-cffi                       20.1.0
        args                              0.1.0
        asn1crypto                        1.4.0
        astunparse                        1.6.3
        async-generator                   1.10
        async-timeout                     3.0.1
        atomicwrites                      1.4.0
        attrs                             20.2.0
        Babel                             2.9.0
        backcall                          0.2.0
        basemap                           1.2.1
        beautifulsoup4                    4.9.3
        black                             19.10b0
        bleach                            3.2.1
        blinker                           1.4
        blis                              0.4.1
        bokeh                             2.2.3
        Bottleneck                        1.3.2
        brotlipy                          0.7.0
        cached-property                   1.5.2
        cachetools                        4.2.0
        Cartopy                           0.18.0
        catalogue                         1.0.0
        certifi                           2020.12.5
        cffi                              1.14.3
        cftime                            1.0.0b1
        chardet                           3.0.4
        click                             7.1.2
        clint                             0.5.1
        cloudpickle                       1.6.0
        colorama                          0.4.3
        coverage                          5.5
        cryptography                      2.8
        cycler                            0.10.0
        cymem                             2.0.4
        cytoolz                           0.11.0
        dask                              2020.12.0
        dataclasses                       0.6
        decorator                         4.4.2
        defusedxml                        0.6.0
        despatch                          0.1.0
        dill                              0.3.3
        entrypoints                       0.3
        et-xmlfile                        1.0.1
        fastai                            1.0.60
        fastcache                         1.1.0
        fastprogress                      0.2.3
        flake8                            3.8.3
        flatbuffers                       1.12
        fsspec                            0.8.5
        future                            0.18.2
        gast                              0.3.3
        google-auth                       1.24.0
        google-auth-oauthlib              0.4.2
        google-pasta                      0.2.0
        grpcio                            1.32.0
        h5py                              2.10.0
        html5lib                          1.1
        idna                              2.10
        imagecodecs                       2020.5.30
        imageio                           2.8.0
        importlib-metadata                1.7.0
        iniconfig                         0.0.0
        ipykernel                         5.3.4
        ipython                           7.19.0
        ipython-genutils                  0.2.0
        ipywidgets                        7.5.1
        isort                             5.7.0
        jdcal                             1.4.1
        jedi                              0.17.2
        Jinja2                            2.11.2
        joblib                            1.0.0
        json5                             0.9.4
        jsonschema                        3.2.0
        jupyter                           1.0.0
        jupyter-bokeh                     2.0.4
        jupyter-client                    6.1.11
        jupyter-console                   6.3.0
        jupyter-contrib-core              0.3.3
        jupyter-contrib-nbextensions      0.5.1
        jupyter-core                      4.7.1
        jupyter-highlight-selected-word   0.2.0
        jupyter-latex-envs                1.4.4
        jupyter-nbextensions-configurator 0.4.1
        jupyter-packaging                 0.7.12
        jupyter-server                    1.4.1
        jupyterlab                        3.0.12
        jupyterlab-code-formatter         1.4.3
        jupyterlab-pygments               0.1.1
        jupyterlab-server                 2.3.0
        jupyterlab-widgets                1.0.0
        Keras                             2.4.3
        Keras-Applications                1.0.8
        Keras-Preprocessing               1.1.2
        keyring                           21.4.0
        kiwisolver                        1.2.0
        lerc                              2.2
        lxml                              4.5.2
        Markdown                          3.3.3
        MarkupSafe                        1.1.1
        matplotlib                        3.3.1
        mccabe                            0.6.1
        mistune                           0.8.4
        mkl-fft                           1.2.0
        mkl-random                        1.2.0
        mkl-service                       2.3.0
        mpmath                            1.1.0
        multidict                         4.7.6
        multiprocess                      0.70.11.1
        murmurhash                        1.0.5
        mypy-extensions                   0.4.3
        nb-conda-kernels                  2.3.1
        nbclassic                         0.2.6
        nbclient                          0.5.0
        nbconvert                         5.6.1
        nbformat                          5.1.2
        nest-asyncio                      1.3.2
        netCDF4                           1.5.4
        networkx                          2.5
        nose                              1.3.7
        notebook                          6.2.0
        ntlm-auth                         1.4.0
        numexpr                           2.7.1
        numpy                             1.19.5
        oauthlib                          3.1.0
        olefile                           0.46
        openpyxl                          3.0.5
        opt-einsum                        3.3.0
        OWSLib                            0.22.0
        packaging                         20.4
        pandas                            1.1.1
        pandocfilters                     1.4.2
        parso                             0.7.0
        pathspec                          0.7.0
        patsy                             0.5.1
        pefile                            2019.4.18
        pickleshare                       0.7.5
        Pillow                            7.1.2
        pip                               21.0.1
        plac                              1.1.0
        pluggy                            0.13.1
        pooch                             1.0.0
        preshed                           3.0.2
        pro-notebook-integration          2.5
        prometheus-client                 0.8.0
        prompt-toolkit                    3.0.5
        protobuf                          3.13.0
        psutil                            5.7.2
        py                                1.9.0
        pyasn1                            0.4.8
        pyasn1-modules                    0.2.8
        pycodestyle                       2.6.0
        pycparser                         2.20
        pyepsg                            0.4.0
        pyflakes                          2.2.0
        Pygments                          2.7.0
        PyJWT                             1.7.1
        pykdtree                          1.3.1
        pyOpenSSL                         19.1.0
        pyparsing                         2.4.7
        pyproj                            2.6.1.post1
        pyrsistent                        0.17.3
        pyshp                             2.1.2
        PySocks                           1.7.1
        pytest                            0.0.0
        python-certifi-win32              0.0.0
        python-dateutil                   2.8.1
        pytorch-lightning                 1.1.7
        pytz                              2020.1
        PyWavelets                        1.1.1
        pywin32                           300
        pywin32-ctypes                    0.2.0
        pywinpty                          0.5.7
        PyYAML                            5.3.1
        pyzmq                             19.0.2
        qtconsole                         5.0.3
        QtPy                              1.9.0
        regex                             2020.7.14
        requests                          2.24.0
        requests-kerberos                 0.12.0
        requests-negotiate-sspi           0.0.0
        requests-ntlm                     1.1.0
        requests-oauthlib                 1.3.0
        requests-toolbelt                 0.9.1
        rsa                               4.7
        scikit-image                      0.17.2
        scikit-learn                      0.24.1
        scipy                             1.5.2
        seaborn                           0.11.1
        Send2Trash                        1.5.0
        setuptools                        49.6.0.post20200814
        Shapely                           1.7.1
        simplegeneric                     0.8.1
        six                               1.15.0
        sniffio                           1.2.0
        soupsieve                         2.1
        spacy                             2.2.4
        srsly                             1.0.2
        statsmodels                       0.12.1
        sympy                             1.5.1
        tensorboard                       2.4.1
        tensorboard-plugin-wit            1.6.0
        tensorflow                        2.4.1
        tensorflow-estimator              2.4.0
        termcolor                         1.1.0
        terminado                         0.8.3
        testpath                          0.4.4
        thinc                             7.4.0
        threadpoolctl                     2.1.0
        tifffile                          2021.1.11
        toml                              0.10.1
        toolz                             0.11.1
        torch                             1.8.0+cu111
        torchaudio                        0.8.0
        torchvision                       0.9.0+cu101
        tornado                           6.1
        tqdm                              4.55.1
        traitlets                         4.3.3
        typed-ast                         1.4.1
        typing-extensions                 3.7.4.3
        ujson                             3.1.0
        urllib3                           1.25.10
        wasabi                            0.6.0
        wcwidth                           0.2.5
        webencodings                      0.5.1
        Werkzeug                          1.0.1
        wheel                             0.35.1
        widgetsnbextension                3.5.1
        win-inet-pton                     1.1.0
        wincertstore                      0.2
        winkerberos                       0.7.0
        wrapt                             1.12.1
        x86cpu                            0.4
        xarray                            0.16.2
        xlrd                              1.2.0
        xlwt                              1.3.0
        yarl                              1.5.1
        zipp                              3.1.0

conda list:
        # packages in environment at C:\Users\jam11491\AppData\Local\ESRI\conda\envs\deeplearning:
        #
        # Name                    Version                   Build  Channel
        _tflow_select             2.3.0                       gpu
        absl-py                   0.11.0             pyhd3eb1b0_1
        aiohttp                   3.6.3            py37he774522_0
        anyio                     2.0.2                    pypi_0    pypi
        appdirs                   1.4.4                      py_0
        arcgis                    1.8.3                 py37_1668    esri
        arcgispro                 2.7                           0    esri
        arcpy                     2.7             py37_arcgispro_26810  [arcgispro]  esri
        argon2-cffi               20.1.0           py37he774522_1
        args                      0.1.0                    pypi_0    pypi
        asn1crypto                1.4.0                      py_0
        astunparse                1.6.3                      py_0
        async-timeout             3.0.1                    py37_0
        async_generator           1.10                       py_0
        atomicwrites              1.4.0                      py_0
        attrs                     20.2.0                     py_0
        babel                     2.9.0              pyhd3deb0d_0    conda-forge
        backcall                  0.2.0                      py_0
        basemap                   1.3.0            py37ha7665c8_0
        beautifulsoup4            4.9.3              pyhb0f4dca_0
        black                     19.10b0                    py_0
        blas                      1.0                         mkl
        bleach                    3.2.1                      py_0
        blinker                   1.4                      py37_0
        blosc                     1.20.1               h7bd577a_0
        bokeh                     2.2.3                    pypi_0    pypi
        bottleneck                1.3.2                    pypi_0    pypi
        brotli                    1.0.9                ha925a31_2
        brotlipy                  0.7.0           py37he774522_1000
        bzip2                     1.0.8                he774522_0
        ca-certificates           2021.1.19            haa95532_1
        cached-property           1.5.2                      py_0
        cachetools                4.2.0              pyhd3eb1b0_0
        cartopy                   0.18.0           py37hd77ba2b_0
        catalogue                 1.0.0                    py37_0    esri
        certifi                   2020.12.5        py37h03978a9_1    conda-forge
        cffi                      1.14.3           py37h7a1dbc1_0
        cftime                    1.0.0b1                  py37_0    esri
        chardet                   3.0.4                 py37_1003
        charls                    2.1.0                h33f27b4_2
        click                     7.1.2                      py_0
        clint                     0.5.1                    pypi_0    pypi
        cloudpickle               1.6.0                      py_0
        colorama                  0.4.3                      py_0
        coverage                  5.5                      pypi_0    pypi
        cppzmq                    4.4.1                         2    esri
        cryptography              2.8                      py37_0    esri
        cudatoolkit               10.2.89              h74a9793_1
        cycler                    0.10.0                   py37_0
        cymem                     2.0.4            py37hd77b12b_0
        cython-blis               0.4.1                    py37_0    esri
        cytoolz                   0.11.0           py37he774522_0
        dask-core                 2020.12.0          pyhd3eb1b0_0
        dataclasses               0.6                      pypi_0    pypi
        decorator                 4.4.2                      py_0
        defusedxml                0.6.0                      py_0
        despatch                  0.1.0                    py37_0    esri
        dill                      0.3.3                    pypi_0    pypi
        entrypoints               0.3                      py37_0
        et_xmlfile                1.0.1                   py_1001
        fastai                    1.0.60                   py37_0    esri
        fastcache                 1.1.0            py37he774522_0
        fastprogress              0.2.3                    py37_0    esri
        flake8                    3.8.3                      py_0
        flatbuffers               1.12                     pypi_0    pypi
        freetype                  2.10.1                   vc14_0  [vc14]  esri
        fsspec                    0.8.5                    pypi_0    pypi
        future                    0.18.2                   py37_0    esri
        gast                      0.3.3                      py_0
        gdal                      2.3.3           arcgispro_py37_16713  [arcgispro]  esri
        geos                      3.8.0                h33f27b4_0
        giflib                    5.2.1                h62dcd97_0
        google-auth               1.24.0             pyhd3eb1b0_0
        google-auth-oauthlib      0.4.2              pyhd3eb1b0_2
        google-pasta              0.2.0                      py_0
        grpcio                    1.32.0                   pypi_0    pypi
        h5py                      2.10.0          py37_arcgispro_9  [arcgispro]  esri
        html5lib                  1.1                        py_0
        icc_rt                    2019.0.5            arcgispro_0  [arcgispro]  esri
        icu                       58.2                 ha925a31_3
        idna                      2.10                       py_0
        imagecodecs               2020.5.30        py37hb1be65f_2
        imageio                   2.8.0                    py37_0    esri
        importlib-metadata        1.7.0                    py37_0
        importlib_metadata        1.7.0                         0
        iniconfig                 1.0.1                      py_0
        intel-openmp              2020.0            arcgispro_166  [arcgispro]  esri
        ipykernel                 5.3.4            py37h5ca1d4c_0
        ipython                   7.19.0                   pypi_0    pypi
        ipython_genutils          0.2.0                    py37_0
        ipywidgets                7.5.1                      py_1
        isort                     5.7.0                    pypi_0    pypi
        jdcal                     1.4.1                      py_0
        jedi                      0.17.2                   py37_0    esri
        jinja2                    2.11.2                     py_0
        joblib                    1.0.0                    pypi_0    pypi
        jpeg                      9d                            0    esri
        json5                     0.9.4                    py37_0    esri
        jsonschema                3.2.0                    py37_1
        jupyter                   1.0.0            py37h03978a9_6    conda-forge
        jupyter-client            6.1.11                   pypi_0    pypi
        jupyter-console           6.2.0                    pypi_0    pypi
        jupyter-contrib-core      0.3.3                    pypi_0    pypi
        jupyter-contrib-nbextensions 0.5.1                    pypi_0    pypi
        jupyter-nbextensions-configurator 0.4.1                    pypi_0    pypi
        jupyter-packaging         0.7.12             pyhd8ed1ab_0    conda-forge
        jupyter-server            1.3.0                    pypi_0    pypi
        jupyter_bokeh             2.0.4                      py_0    bokeh
        jupyter_client            6.1.7                      py_0
        jupyter_console           6.3.0              pyhd8ed1ab_0    conda-forge
        jupyter_core              4.7.1            py37haa95532_0
        jupyter_highlight_selected_word 0.2.0                    py37_2    esri
        jupyter_latex_envs        1.4.4                    py37_1    esri
        jupyter_server            1.4.1            py37h03978a9_0    conda-forge
        jupyterlab                3.0.7                    pypi_0    pypi
        jupyterlab-code-formatter 1.4.3                    pypi_0    pypi
        jupyterlab-server         2.2.0                    pypi_0    pypi
        jupyterlab-widgets        1.0.0                    pypi_0    pypi
        jupyterlab_pygments       0.1.1                      py_1    esri
        jupyterlab_server         2.3.0              pyhd8ed1ab_0    conda-forge
        keras-applications        1.0.8                      py_1
        keras-base                2.4.3                      py_0
        keras-gpu                 2.4.3                         0
        keras-preprocessing       1.1.2                    pypi_0    pypi
        keyring                   21.4.0                   py37_0    esri
        kiwisolver                1.2.0            py37h74a9793_0
        lcms2                     2.11                 hc51a39a_0
        lerc                      2.2                        py_0    esri
        libaec                    1.0.4                h33f27b4_1
        libpng                    1.6.37               h2a8f88b_0
        libprotobuf               3.13.0.1             h200bbdf_0
        libsodium                 1.0.18                        1    esri
        libtiff                   4.1.0                         0    esri
        libuv                     1.40.0               he774522_0
        libxml2                   2.9.10              arcgispro_0  [arcgispro]  esri
        libxslt                   1.1.34               he774522_0
        libzopfli                 1.0.3                ha925a31_0
        lxml                      4.5.2            py37h1350720_0
        lz4-c                     1.9.2                hf4a77e7_3
        markdown                  3.3.3            py37haa95532_0
        markupsafe                1.1.1            py37hfa6e2cd_1
        matplotlib                3.3.1           py37_arcgispro_0  [arcgispro]  esri
        matplotlib-base           3.2.2            py37h64f37c6_0
        mccabe                    0.6.1                    py37_1
        mistune                   0.8.4           py37hfa6e2cd_1001
        mkl                       2020.0            arcgispro_167  [arcgispro]  esri
        mkl-service               2.3.0            py37hb782905_0
        mkl_fft                   1.2.0            py37h45dec08_0
        mkl_random                1.2.0                    py37_0    esri
        mpmath                    1.1.0                    py37_0
        multidict                 4.7.6            py37he774522_1
        multiprocess              0.70.11.1                pypi_0    pypi
        murmurhash                1.0.5            py37hd77b12b_0
        mypy_extensions           0.4.3                    py37_0
        nb_conda_kernels          2.3.1            py37haa95532_0
        nbclassic                 0.2.6              pyhd8ed1ab_0    conda-forge
        nbclient                  0.5.0                      py_0    esri
        nbconvert                 5.6.1                    py37_0    esri
        nbformat                  5.1.2              pyhd3eb1b0_1
        nest-asyncio              1.3.2                      py_0    esri
        netcdf4                   1.5.4           py37_arcgispro_5  [arcgispro]  esri
        networkx                  2.5                      py37_0    esri
        ninja                     1.10.2           py37h6d14046_0
        nlohmann_json             3.7.0                         1    esri
        nodejs                    10.13.0                       0
        nose                      1.3.7                 py37_1004
        notebook                  6.2.0            py37haa95532_0
        ntlm-auth                 1.4.0                      py_0    esri
        numexpr                   2.7.1            py37h25d0782_0
        numpy                     1.19.5                   pypi_0    pypi
        nvidia-ml-py3             7.352.0                    py_0    esri
        oauthlib                  3.1.0                      py_0
        olefile                   0.46                     py37_0
        openjpeg                  2.3.0                h5ec785f_1
        openpyxl                  3.0.5                      py_0
        openssl                   1.1.1j               h8ffe710_0    conda-forge
        opt-einsum                3.3.0                    pypi_0    pypi
        owslib                    0.22.0             pyhd3eb1b0_0
        packaging                 20.4                       py_0
        pandas                    1.1.1            py37ha925a31_0
        pandocfilters             1.4.2                    py37_1
        parso                     0.7.0                      py_0
        pathspec                  0.7.0                      py_0
        patsy                     0.5.1                    py37_0
        pefile                    2019.4.18                  py_0
        pickleshare               0.7.5                 py37_1001
        pillow                    6.2.2                    py37_0    esri
        pillow-simd               7.1.2                    py37_3    esri
        pip                       21.0.1                   pypi_0    pypi
        plac                      1.1.0                    py37_1
        pluggy                    0.13.1                   py37_0
        pooch                     1.0.0                    py37_0    esri
        preshed                   3.0.2                    py37_0    esri
        pro_notebook_integration  2.7                      py37_1    esri
        proj                      6.2.1                h9f7ef89_0
        prometheus_client         0.8.0                      py_0    esri
        prompt_toolkit            3.0.5                      py_0    esri
        protobuf                  3.13.0.1         py37ha925a31_1
        psutil                    5.7.2            py37he774522_0
        py                        1.9.0                      py_0
        pyasn1                    0.4.8                      py_0
        pyasn1-modules            0.2.8                      py_0
        pybind11                  2.3.0                         1    esri
        pycodestyle               2.6.0                      py_0
        pycparser                 2.20                       py_2
        pyepsg                    0.4.0                      py_0
        pyflakes                  2.2.0                      py_0
        pygments                  2.7.0                      py_0    esri
        pyjwt                     1.7.1                    py37_0
        pykdtree                  1.3.1            py37h8c2d366_2
        pyopenssl                 19.1.0                     py_1
        pyparsing                 2.4.7                      py_0
        pypdf2                    1.26.0                     py_2    esri
        pyproj                    2.6.1.post1      py37hcfa1391_1
        pyqt                      5.9.2            py37h6538335_2
        pyrsistent                0.17.3           py37he774522_0
        pyshp                     2.1.2                      py_0
        pysocks                   1.7.1                    py37_1
        pytest                    6.1.1                    py37_0    esri
        python                    3.7.9                         2    esri
        python-certifi-win32      1.2                      py37_0    esri
        python-dateutil           2.8.1                      py_0
        python_abi                3.7                     1_cp37m    conda-forge
        pytorch-lightning         1.1.7                    pypi_0    pypi
        pytz                      2020.1                   py37_0    esri
        pywavelets                1.1.1            py37he774522_2
        pywin32                   300                      pypi_0    pypi
        pywin32-ctypes            0.2.0                    pypi_0    pypi
        pywin32-security          228                      py37_3    esri
        pywinpty                  0.5.7                    py37_0    esri
        pyyaml                    5.3.1            py37he774522_1
        pyzmq                     19.0.2                   py37_1    esri
        qt                        5.9.7            vc14h73c81de_0
        qtconsole                 5.0.2                    pypi_0    pypi
        qtpy                      1.9.0                      py_0    conda-forge
        regex                     2020.7.14        py37he774522_0
        requests                  2.24.0                     py_0
        requests-kerberos         0.12.0                        0    esri
        requests-negotiate-sspi   0.5.2                    py37_1    esri
        requests-oauthlib         1.3.0                      py_0
        requests-toolbelt         0.9.1                      py_0
        requests_ntlm             1.1.0                      py_0    esri
        rsa                       4.7                pyhd3eb1b0_1
        scikit-image              0.17.2                   py37_1    esri
        scikit-learn              0.24.1                   pypi_0    pypi
        scipy                     1.5.2            py37h9439919_0
        seaborn                   0.11.1             pyhd3eb1b0_0
        send2trash                1.5.0                    py37_0
        setuptools                49.6.0                   py37_0
        shapely                   1.7.1            py37h210f175_0
        simplegeneric             0.8.1                    py37_2
        sip                       4.19.8           py37h6538335_0
        six                       1.15.0                     py_0
        snappy                    1.1.8                h33f27b4_0
        sniffio                   1.2.0            py37h03978a9_1    conda-forge
        soupsieve                 2.1                pyhd3eb1b0_0
        spacy                     2.2.4                    py37_0    esri
        sqlite                    3.33.0               h2a8f88b_0
        srsly                     1.0.2                    py37_0    esri
        statsmodels               0.12.1           py37h2bbff1b_0
        sympy                     1.5.1                    py37_0    esri
        tensorboard               2.4.1                    pypi_0    pypi
        tensorboard-plugin-wit    1.6.0                      py_0
        tensorflow                2.4.1                    pypi_0    pypi
        tensorflow-estimator      2.4.0                    pypi_0    pypi
        tensorflow-gpu            2.3.0                he13fc11_0
        termcolor                 1.1.0                    py37_1
        terminado                 0.8.3                    py37_0
        testpath                  0.4.4                      py_0
        thinc                     7.4.0                    py37_0    esri
        threadpoolctl             2.1.0                    pypi_0    pypi
        tifffile                  2021.1.11          pyhd3eb1b0_1
        toml                      0.10.1                     py_0
        toolz                     0.11.1                     py_0
        torch                     1.4.0                    pypi_0    pypi
        torchaudio                0.8.0                    pypi_0    pypi
        torchvision               0.9.0+cu101              pypi_0    pypi
        tornado                   6.1              py37h2bbff1b_0
        tqdm                      4.55.1             pyhd3eb1b0_0
        traitlets                 4.3.3                    py37_0
        typed-ast                 1.4.1            py37he774522_0
        typing_extensions         3.7.4.3                    py_0
        ujson                     3.1.0            py37ha925a31_0
        urllib3                   1.25.10                    py_0
        vc                        14.2                 h21ff451_1
        vs2015_runtime            14.27.29016          h5e58377_2
        wasabi                    0.6.0                    py37_0    esri
        wcwidth                   0.2.5                      py_0
        webencodings              0.5.1                    py37_1
        werkzeug                  1.0.1                      py_0
        wheel                     0.35.1                     py_0
        widgetsnbextension        3.5.1                    py37_0
        win_inet_pton             1.1.0                    py37_0
        wincertstore              0.2                      py37_0
        winkerberos               0.7.0                    py37_1
        winpty                    0.4.3                         4
        wrapt                     1.12.1           py37he774522_1
        x86cpu                    0.4                      py37_1    esri
        xarray                    0.16.2             pyhd3eb1b0_0
        xeus                      0.24.1                        1    esri
        xlrd                      1.2.0                      py_0
        xlwt                      1.3.0                    py37_0
        xtl                       0.6.5                         1    esri
        xz                        5.2.5                h62dcd97_0
        yaml                      0.2.5                         0    esri
        yarl                      1.5.1                    pypi_0    pypi
        zeromq                    4.3.2                         2    esri
        zipp                      3.1.0                      py_0
        zlib                      1.2.11               h62dcd97_4
        zstd                      1.4.5                h04227a9_0

conda env:
        name: deeplearning
        channels:
          - defaults
          - esri
        prefix: C:\Users\jam11491\.conda\envs\deeplearning
</pre>
</details>

<details><summary>Command Line Output</summary>
Outputs the following when I interrupt, otherwise normal output:
<pre>
[I 2021-03-23 06:49:56.297 ServerApp] Kernel interrupted: b6aa6f89-f96b-47c3-8e1e-868c0f9f00a7
</pre>
</details>

<details><summary>Browser Output</summary>
No abnormal messages printed in the javascript console.
</details>

**Comment by kevin-bates** [comment]
This issue should probably be forwarded to `jupyter_client` - Lab (and the web handlers in Server) are delivering the request correctly.  The informational message is logged by the [`MultiKernelManager.interrupt_kernel()`](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/multikernelmanager.py#L276) method following the _delivery_ of the interrupt by the [`KernelManager.interrupt_kernel()`](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L577-L597) method.

As you can see, the interrupt handling is special-cased for Windows so I suspect there's something amiss there.  That particular interrupt event is set up when the kernel is started.  I'd be surprised the port-forwarding has anything to do with this, but it's odd that it only happens in that scenario (if I recall the gitter posts correctly).  

Might there be any subprocesses or threads involved within the notebook?
Can you confirm that not using the port forwarding leads to successful interrupts?

**Comment by guillochon** [comment]
I verified I see this issue locally as well when the kernel is not the kernel from which `jupyter lab` was launched when using `nb_conda_kernels`, as I am.

I think this issue covers what I'm seeing: https://github.com/Anaconda-Platform/nb_conda_kernels/issues/180
